### ISSUE TITLE
PowerShell listed doesn't retrieve all mailboxes

### ISSUE THREAD

**Issue by quidan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10007]
In the PowerShell script, it may not retrieve all mailboxes in large tenants.

For the line that starts with:
$Room_UPNs = get-mailbox | Where-Object { $_.recipientTypeDetails -eq "roomMailbox" } | Select-Object DisplayName, PrimarySmtpAddress, ExternalDirectoryObjectId 

It should be altered to be: 
$Room_UPNs = get-mailbox -ResultSize unlimited | Where-Object { $_.recipientTypeDetails -eq "roomMailbox" } | Select-Object DisplayName, PrimarySmtpAddress, ExternalDirectoryObjectId 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 46740b3f-d12b-f40f-1b71-f66da9422fc6
* Version Independent ID: 46740b3f-d12b-f40f-1b71-f66da9422fc6
* Content: [Find Teams Rooms devices with unsupported licenses - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/rooms/license-check)
* Content Source: [Teams/rooms/license-check.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/license-check.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @quidan, thank you for your feedback.

It's the same issue:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/10007

I'm applying an update to the script.

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
