### ISSUE TITLE
Missing or bad link to xls file.

### ISSUE THREAD

**Issue by d1bjo0** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10012]
[Enter feedback here]

The link to the country list is broken. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c3c28e5-f52e-259b-e01d-fb88f23778ed
* Version Independent ID: 2c3c28e5-f52e-259b-e01d-fb88f23778ed
* Content: [Country/region availability - Audio Conferencing, Calling Plans - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/calling-plan-overview)
* Content Source: [Teams/calling-plan-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/calling-plan-overview.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hello @d1bjo0 
Removed in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/fd187c9e1afd13d292709d89dcb020dc8ca4904b
