### ISSUE TITLE
"user-level policies"

### ISSUE THREAD

**Issue by cedwards-telis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10010]
This document assumes that all the users use RDS/VDI all the time, whereas in the real world users might use desktops and notebooks sometimes and RDS/VDI others.  Is there no way of disabling Calling and Meetings on a per machine basis?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80cf547a-2220-53ac-4da6-50a654158eb7
* Version Independent ID: 6c12b7eb-7c37-907b-80b7-2ad102018556
* Content: [Use Teams with remote desktop services - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-on-rdp)
* Content Source: [Teams/teams-on-rdp.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-on-rdp.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @cedwards-telis 
How are you?
Yes, at the moment those policies are user-based.

For feedback you can use this resource https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472

Thank you
