### ISSUE TITLE
The Service Administrator role has been renamed

### ISSUE THREAD

**Issue by DarCampbell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10014]
The 3 Built-in roles are now Teams Rooms Pro Manager, Site lead, and Site Technician. We should update the names and pictures that point to this old role.
![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/40171398/3da6f46c-5b0f-44e5-8bf7-26769e63b02d)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9211ee7-1c36-f653-9c3c-dfda04fdf77c
* Version Independent ID: b9211ee7-1c36-f653-9c3c-dfda04fdf77c
* Content: [Role-based access control in the Microsoft Teams Pro Management Portal - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-pro-rbac)
* Content Source: [Teams/rooms/rooms-pro-rbac.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-pro-rbac.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @altsou
* Microsoft Alias: **altsou**

**Comment by get-itips** [comment]
Thanks @DarCampbell  !
