### ISSUE TITLE
Updated devices needed. 

### ISSUE THREAD

**Issue by ASeabrook36** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10029]
The devices section is severely out of date. Can it be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3e16a13-c655-a78d-cdf5-8395bcfe54d6
* Version Independent ID: f06b064f-a9f2-8ed7-48f7-8d4e21934e6a
* Content: [Meeting room guidance for Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/room-planning-guidance?source=recommendations&tabs=emtr&culture=en-us&country=US)
* Content Source: [Teams/rooms/room-planning-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/room-planning-guidance.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dstrome** [comment]
@ASeabrook36 - the devices listed are examples and not meant to be an exhaustive list.
