### ISSUE TITLE
Circular link in note about Cloud Connector Edition on direct-routing-plan.md

### ISSUE THREAD

**Issue by rcdun** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10032]
In the note on https://learn.microsoft.com/en-us/microsoftteams/direct-routing-plan:

> Cloud Connector Edition will retire July 31, 2021 along with Skype for Business Online. Once your organization has upgraded to Teams, learn how to connect your on-premises telephony network to Teams using [Direct Routing](https://learn.microsoft.com/en-us/microsoftteams/direct-routing-landing-page).

https://learn.microsoft.com/en-us/microsoftteams/direct-routing-landing-page redirects to https://learn.microsoft.com/en-us/microsoftteams/direct-routing-plan i.e. this page, so the link is circular.

I also noticed that it says "will retire July 31, 2021" - we're now in 2023, so presumably it's been retired by now and the future tense isn't right?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d964547-6b38-cc5f-6b2b-7a50a1c7dae9
* Version Independent ID: fa5850f9-1b92-9727-c344-bcffc227cbd6
* Content: [Plan Direct Routing - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/direct-routing-plan)
* Content Source: [Teams/direct-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Thanks for your feedback
