### ISSUE TITLE
webdir.online.lync.com missing HTTPS or 30x redirect to HTTPS

### ISSUE THREAD

**Issue by wesonate** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10033]
Following this article introduces a security vulnerability into the customer's DNS.  Specifically, the DNS alias for "lyncdiscover" to "webdir.online.lync.com".  

![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/81455058/bb3e4776-5f9e-4f04-8127-ee1c511bac8f)

Details:
webdir.online.lync.com does not enforce https (HTTPS or 30x redirect to HTTPS is not found).  Please pass this along to the appropriate team.

**Comment by scanum** [comment]
Hi @wesonate hope all is well. Could you please share a link of the article you are referring to? Thanks!

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
