### ISSUE TITLE
Need to replace  Azure AD Powershell to Graph API method for Turn off password expiration.

### ISSUE THREAD

**Issue by yuki-iwagishi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10039]
https://learn.microsoft.com/en-us/microsoftteams/hybrid-meetings-device-config-password?tabs=azure-active-directory2-password

Need to replace  Azure AD Powershell to Graph API method for Turn off password expiration.

https://learn.microsoft.com/en-us/powershell/azure/active-directory/overview?view=azureadps-2.0
Azure AD Powershell is planned to be deprecated on June 30, 2023.

`Connect-MgGraph -Scopes "User.ReadWrite.All"`

`Update-MgUser -UserId ConferenceRoom01@contoso.com -PasswordPolicies DisablePasswordExpiration -PassThru`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3beec0ce-0b72-9c12-6068-dbff759f1d56
* Version Independent ID: 3beec0ce-0b72-9c12-6068-dbff759f1d56
* Content: [Step 5 - Turn off password expiration - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/hybrid-meetings-device-config-password?tabs=azure-active-directory2-password)
* Content Source: [Teams/hybrid-meetings-device-config-password.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hybrid-meetings-device-config-password.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Thanks for your feedback!
