### ISSUE TITLE
Spelling mistake on the Teams Application

### ISSUE THREAD

**Issue by Raj-MCITP** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10038]
When you access https://admin.teams.microsoft.com/policies/manage-apps and navigate to Org-wide setting.. there is a typo on this paragraph. Word - Adminstrator

Please report this to correct team. 

Blocked apps may still have access to data from the teams they're installed in. To turn off app data access, ask your Global **Adminstrator**, Application Administrator, or Cloud Application Administrator to turn off user sign-in in the [Azure Active Directory admin center](https://portal.azure.com/#blade/Microsoft_AAD_IAM/StartboardApplicationsMenuBlade/AllApps/menuId/?WT.mc_id=TeamsAdminCenterCSH). [Learn more](https://learn.microsoft.com/en-US/microsoftteams/user-requests-approve-apps)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fbbcabee-fa96-2878-e983-3c966f84ee15
* Version Independent ID: 02fa4fd8-77e0-5cb2-a4af-576cbb68322f
* Content: [Manage your apps in the Microsoft Teams admin center - Microsoft Teams](https://learn.microsoft.com/en-US/microsoftteams/manage-apps?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/manage-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-apps.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by ashishguptaiitb** [comment]
Hello @scanum, this is not a `doc-bug` as there's no feedback on docs but on the product UI content. I'm changing the labels. Let me know if this is OK.
Can we consider adding `content design` label, here in the GitHub repo?

**Comment by ashishguptaiitb** [comment]
I've shared it internally with the relevant team so closing this issue. 
CC @scanum and @Raj-MCITP
