### ISSUE TITLE
Consider adding a different symbol than x in the table

### ISSUE THREAD

**Issue by ashishguptaiitb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10030]
In the tables, consider adding a `Y` or a &#9745; tick symbol instead of `x`. The latter may be ambiguous for some folks (yes this feature is available versus no this feature is crossed out and is not available).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c100aa6e-f8a3-053f-f5c6-d3e543dea5a0
* Version Independent ID: c100aa6e-f8a3-053f-f5c6-d3e543dea5a0
* Content: [Microsoft Teams Premium licensing - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/licensing-enhance-teams#how-does-teams-premium-compare-to-teams)
* Content Source: [Teams/teams-add-on-licensing/licensing-enhance-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/licensing-enhance-teams.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by ashishguptaiitb** [comment]
Oh hey @DaniEASmith :-) I wasn't aware of this. Thanks!
Does Unicode (say, `&#x2713;` for &#x2713; ) not work in our MD?

**Comment by DaniEASmith** [comment]
@ashishguptaiitb I may be able to use an ✔️ emoji.

**Comment by DaniEASmith** [comment]
@ashishguptaiitb How does this look? https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/licensing-enhance-teams#how-does-teams-premium-compare-to-teams.

**Comment by ashishguptaiitb** [comment]
It looks better than before @DaniEASmith . I am closing this issue. Feel free to reopen if required.
