### ISSUE TITLE
This script need some updating

### ISSUE THREAD

**Issue by wearslipper** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10046]
[Enter feedback here]

I could not run parts of this script.  

The GetOnlineUser '.ObjectID' statements are invalid and must be updated to '.Identity'

for example:
$dialByNameApplicationInstanceID = (Get-CsOnlineUser "ContosoDialByNameAA-RA@contoso.com").ObjectID

It would also be better to organize the user creations and license assignments as dependencies at the top since the Admin Roles required are different from the Teams components.  In enterprise settings these are often different IT teams and require coordination in order to execute.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ad1c0f2-1ddc-5c9c-8eec-1d0c90f5d48f
* Version Independent ID: 6ad1c0f2-1ddc-5c9c-8eec-1d0c90f5d48f
* Content: [Create an auto attendant via cmdlets - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/create-a-phone-system-auto-attendant-via-cmdlets)
* Content Source: [Teams/create-a-phone-system-auto-attendant-via-cmdlets.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-auto-attendant-via-cmdlets.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@CLYVR For visibility regarding the auto attendant PowerShell script.

**Comment by CLYVR** [comment]
@wearslipper Thanks for bringing this to our attention. I have submitted the changes for ObjectID to Identity and they should be available publically within the next few days.  I'll review the other suggestion about how to group the functions differently.

cc: @DaniEASmith

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
