### ISSUE TITLE
Clarify license required for Microsoft Teams Android Devices User Interfaces

### ISSUE THREAD

**Issue by hh-trj** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10048]
The page [here](https://learn.microsoft.com/en-us/microsoftteams/devices/teams-android-devices-user-interface) says:

> An E3 or E5 license supports all sign-in modes.

Is this referring to Office 365 E3 or Microsoft 365 E3 licensing? There are few different places within the article where E3 and E5 licenses are mentioned, but it doesn't specify.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62d58962-9b2f-0231-187b-58c845e52a0c
* Version Independent ID: b3045cca-8bcb-8d30-0dda-49aed3009172
* Content: [Set Microsoft Teams Android devices user interface - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/devices/teams-android-devices-user-interface)
* Content Source: [Teams/devices/Teams-Android-devices-user-interface.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/Teams-Android-devices-user-interface.md)
* Service: **msteams**
* Sub-service: **itpro-devices**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @hh-trj 
How are you?
Otherwise stated, that refers to Office 365 E3/E5 and Microsoft 365 E3/E5, I could confirm.
