### ISSUE TITLE
Request removal of 'Calendar Pro' from list of apps supported by Teams 'shared channel'

### ISSUE THREAD

**Issue by Xyvir** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10044]
Please see my last comment on the previously closed issue:

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9856

-Tyler

**Comment by get-itips** [comment]
Hello @Xyvir 
I'm working on this and I'll get back.
