### ISSUE TITLE
get-mailbox command in "Check the license of multiple Microsoft Teams Rooms devices" script not working in big tenants

### ISSUE THREAD

**Issue by orandev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10041]
Hello,
We have a very large number of mailboxes in our tenant and the PowerShell script indicated in "Check the license of multiple Microsoft Teams Rooms devices" section is not working correctly (it's returning 0 resource account mailboxes).

I fixed and optimized the script by replacing:

`$Room_UPNs = get-mailbox | Where-Object { $_.recipientTypeDetails -eq "roomMailbox" } | Select-Object DisplayName, PrimarySmtpAddress, ExternalDirectoryObjectId`

with

`$Room_UPNs = Get-Mailbox -ResultSize unlimited -Filter "RecipientTypeDetails -eq 'RoomMailbox'" | Select-Object DisplayName, PrimarySmtpAddress, ExternalDirectoryObjectId`

Could you update the script with this change please?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 46740b3f-d12b-f40f-1b71-f66da9422fc6
* Version Independent ID: 46740b3f-d12b-f40f-1b71-f66da9422fc6
* Content: [Find Teams Rooms devices with unsupported licenses - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/rooms/license-check)
* Content Source: [Teams/rooms/license-check.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/license-check.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @orandev thanks for your feedback, I'll make a small change to your proposal

`Get-EXOMailbox -RecipientTypeDetails roommailbox -ResultSize unlimited` and create a PR to update the script
