### ISSUE TITLE
Time to update powershell cmdlets 

### ISSUE THREAD

**Issue by JohanssonMarkus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10042]
I guess you should update the page with Graph calls instead of old API calls, any plan for that?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a560986f-99b6-9e5e-a3a3-2a10309d4247
* Version Independent ID: a560986f-99b6-9e5e-a3a3-2a10309d4247
* Content: [Create resource accounts for rooms and shared Teams devices - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/create-resource-account?tabs=m365-admin-center%2Cazure-active-directory2-password)
* Content Source: [Teams/rooms/create-resource-account.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/create-resource-account.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
