### ISSUE TITLE
Unable to download postman folder

### ISSUE THREAD

**Issue by kdbhatt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10049]
I am unable to download postman older mentioned here:

Import the folder postman in the [downloaded zip file](https://learn.microsoft.com/en-us/microsoftteams/aa-cq-cqd-historical-reports#v3xx-desktop-installation) instructions into Postman.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f10dcb86-8529-c107-a208-36e09a27cd9b
* Version Independent ID: f10dcb86-8529-c107-a208-36e09a27cd9b
* Content: [Auto attendant and call queue historical reports - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/aa-cq-cqd-historical-reports)
* Content Source: [Teams/aa-cq-cqd-historical-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/aa-cq-cqd-historical-reports.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@CLYVR For your review of this issue.

**Comment by CLYVR** [comment]
@kdbhatt I have added the postman folder and it should now be available if you download the file again.  Apologies for the inconvenience.

**Comment by kdbhatt** [comment]
I can see the postman folder now.
