### ISSUE TITLE
Link to admin center

### ISSUE THREAD

**Issue by pauldaustin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10045]
[Enter feedback here]

Please add a link to https://admin.teams.microsoft.com/
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams meeting recording - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/meeting-recording?tabs=meeting-policy#turn-on-or-turn-off-recording-transcription)
* Content Source: [Teams/meeting-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-recording.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback
