### ISSUE TITLE
This policy does not appear when using GDAP

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10055]
This Voicemail policy tab does not appear in Teams Admin Center (TAC)  when using GDAP. Roles combination tried without success: Teams administrator, Skype for Business administrator, User administrator, Billing administrator
It does appear as when using in tenant user with same admin roles.

Please advise GDAP roles required to work or add that it does not currently work via GDAP.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85634d87-7729-6449-9663-556097e75504
* Version Independent ID: b75446bd-07af-a7f2-d346-fe7634634548
* Content: [Manage Voicemail Policies - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-voicemail-policies)
* Content Source: [Teams/manage-voicemail-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-voicemail-policies.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @SvenBell, thank you for your feedback.

You can find the information in a specific GDAP article:
https://learn.microsoft.com/partner-center/gdap-supported-workloads#teams-admin-center

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
