### ISSUE TITLE
[Doc-Bug] Group policy assignment in TAC note

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10068]
I see following note in documentation:
Currently, policy assignment to groups using the Microsoft Teams admin center **is only available for Teams calling policy**, Teams call park policy, Teams policy, Teams live events policy, Teams meeting policy, and Teams messaging policy. For other policy types, use PowerShell.

But i see Group policy assignment is available in TAC for App setup policy as well. So, please update note accordingly.
![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/69682598/da87b5ca-52dd-4556-8629-9e78c6221e32)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 888fe05b-1160-452f-90ba-deb19adb740f
* Version Independent ID: 4091c5e4-7a90-7fe4-2741-16bbb1f297c1
* Content: [Assign policies to users and groups - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/assign-policies-users-and-groups)
* Content Source: [Teams/assign-policies-users-and-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-policies-users-and-groups.md)
* Service: **msteams**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by get-itips** [comment]
Hello @SubbaReddi How are you?
Thanks for your feedback.
