### ISSUE TITLE
wrong date of the document

### ISSUE THREAD

**Issue by minyang-ttni** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1006]
did i see the date wrong? Is it a document from future? 12/18/2018?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aea70bc6-2241-f153-33a4-8bebe509a09a
* Version Independent ID: 6a15940a-c0a0-3fa3-d818-fa7f4597ffcb
* Content: [Data API for Call Quality Dashboard (CQD) in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/call-quality-dashboard/data-api)
* Content Source: [Skype/SfbServer/management-tools/call-quality-dashboard/data-api.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/management-tools/call-quality-dashboard/data-api.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@minyang-ttni thanks for catch. I wish I had a nice story like I went into future. :) It is set from metadata though.

@AndreaBarr - to fix this you can remove the  ms.date   section from the metadata. You will see it shows 12/18/2018. Just remove that line completely and then the date will default to the last published date. Thanks!

**Comment by jamesrhea** [comment]
@AndreaBarr, it looks like a Nov 14th revert by David Strome fixed this issue. The article now shows a Nov 14 last published date: https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/call-quality-dashboard/data-api

Here's the revert commit:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/eac1f54721d4241cd8162c94bbfeb21935400478#diff-541189683fccdfec1554239509cd09ab
