### ISSUE TITLE
# & * keypad keys are no longer reserved by system and need assignment

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10066]
Hi Team, The Language support section on this page suggests "Press * on the keypad to repeat the list of options." Unfortunately, this feature no longer works. It no longer works as a system reserved option to repeat the menu. It seems you now have to assign the * (asterisk) or # (hash/pound) key an assignment. Unfortunately the best option to repeat them mean is to either:
1. Redirect to VoiceApp, to same Auto-Attendant (but also suffering the greeting part, not just the menu greeting repeating).
2. Use the Announcement option (but menu options not listening during announcement if you repeat the menu via Announcement option), so just Announce something like "Repeating menu" which then loops back to replay just the menu, but has large pauses between (so not a smooth user experience).
3. Advise caller at end of menu script "or, hold to hear these menu option again", (menu only repeats 3 times before disconnecting with "Sorry we were unable to help" or redirected to an operator if (defined for the Auto-Attendant)

It would be good if the doco was updated with how things have changed and a suggestion on how best to repeat a menu now the reserved feature is no longer an option.

Many Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 016be911-545f-28e4-97d2-549f1078a196
* Version Independent ID: 9021aad0-83c0-1173-01ae-6cc68217e8d4
* Content: [Auto attendant and call queue dialing and voice recognition reference - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/dial-voice-reference)
* Content Source: [Teams/dial-voice-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/dial-voice-reference.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@CLYVR Tagging you for visibility and guidance on this GitHub issue.

**Comment by CLYVR** [comment]
@DaniEASmith I'm reviewing.

**Comment by get-itips** [comment]
Thanks @CLYVR

**Comment by get-itips** [comment]
@scanum
