### ISSUE TITLE
Document effect of changing the bot ID in an app package

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10076]
> Change the ID of the bot using the botId property.

Other than triggering consent for the upgrade, this also 
- leaves the old bot in the chat to preserve chat history
- disconnects the bot from the app manifest, reverting the bot icon and name to what is in the BF registration

Clarify: What permission policies apply to the disconnected bot (the old bot ID)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 307f3f54-bd2e-2b85-91fd-35c3cce97e8b
* Version Independent ID: a9ec4bbb-64d7-718c-f585-cc496300123f
* Content: [Apps update experience in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/apps-update-experience)
* Content Source: [Teams/apps-update-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/apps-update-experience.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by ashishguptaiitb** [comment]
Thanks Adrian. I've created a PR to address this improvement.

**Comment by ashishguptaiitb** [comment]
Hi @aosolis , the updates are published live now. I hope this addresses the issue. Kindly review.

**Comment by ashishguptaiitb** [comment]
We've published the updated docs. Closing this issue now. Please reopen with more info, if required.
Thanks @aosolis and @scanum .
