### ISSUE TITLE
Voice commands

### ISSUE THREAD

**Issue by LadyFaeriedragon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10071]
Hello,

Please could you add a line clarifying the voice commands? It currently says "The following voice commands are available for speech recognition", which reads like there are no scope for custom voice commands. My understanding is that those are _always_ available, but that you can add one word custom commands too, so it would be good to have that included.

**Comment by scanum** [comment]
Hi @LadyFaeriedragon thanks for the feedback. Please link the documentation you are referring to.

**Comment by get-itips** [comment]
Hello @LadyFaeriedragon Please include the link of the article you are talking about thanks!

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
