### ISSUE TITLE
Correction : Front End with two Front End Pools

### ISSUE THREAD

**Issue by NeeranjanShettar** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1007]
There must be correction to be done for the item, "Front End with two Front End Pools" 
The document is incorrect for Skype for Business 2019 as the Skype for Business doesn't support Two nodes in a enterprise Pool and it actually throws an error and prevent the topology from being published . Either this document to be reviewed and updated saying "Front End with two Front End Pools" is not supported or product team to work on the issue if it is bug..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0494aea2-041e-3aa3-ce86-2453586de0ec
* Version Independent ID: 92317b83-036f-92a1-a15d-9d35eefc9b57
* Content: [Plan for high availability and disaster recovery in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/high-availability-and-disaster-recovery/high-availability-and-disaster-recovery)
* Content Source: [Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/high-availability-and-disaster-recovery.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/high-availability-and-disaster-recovery.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by AndreaBarr** [comment]
@NeeranjanShettar Thank you for this inquiry

I am not sure if this is a potential bug or not. Let me get this over to the Skype for Business team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by LolaJacobsen** [comment]
@MicrosoftHeidi I'm assigning the related VSO work item to you too.

**Comment by NeeranjanShettar** [comment]
@MicrosoftHeidi - Any updated here, it's been long time no response, thanks in advance.

**Comment by scanum** [comment]
@MicrosoftHeidi Any updates on this? Thanks!

**Comment by MicrosoftHeidi** [comment]
The documentation is incorrect, and any reference to two nodes should be removed.

**Comment by msbemba** [comment]
@NeeranjanShettar Thank you for your feedback. Looks like the references to two nodes have been removed from the document https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/high-availability-and-disaster-recovery/high-availability-and-disaster-recovery

**Comment by scanum** [comment]
@NeeranjanShettar Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
