### ISSUE TITLE
[teams] Broken links

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10072]
In `Teams as part of Microsoft 365` section, all links are broken

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ad624-9792-91b7-c85f-09b839b1ea44
* Version Independent ID: e8288f91-11bd-599b-8a88-074917b315a4
* Content: [Microsoft Teams IT architecture and voice solutions posters - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-architecture-solutions-posters)
* Content Source: [Teams/teams-architecture-solutions-posters.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-architecture-solutions-posters.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks @shivtorov !
