### ISSUE TITLE
Transcription available for  GCC 

### ISSUE THREAD

**Issue by dipinn26592** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10084]
The Doc says " Meeting transcription is not yet available in GCC." 

However the below doc says its rolled out.

[[Enter feedback here]](https://learn.microsoft.com/en-us/officeupdates/governmentchannel#gcc-customers-10)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a8e28688-73cd-6845-3fcf-a1e8ee9ea188
* Version Independent ID: a8e28688-73cd-6845-3fcf-a1e8ee9ea188
* Content: [Configure transcription and captions for Teams meetings - Microsoft Teams](https://learn.microsoft.com/en-US/microsoftteams/meeting-transcription-captions)
* Content Source: [Teams/meeting-transcription-captions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-transcription-captions.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback
