### ISSUE TITLE
Accessing VAAC outside of Power BI

### ISSUE THREAD

**Issue by jdacorr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10082]
At the "Auto attendant and call queue historical reports" ([doc link](https://learn.microsoft.com/en-us/microsoftteams/aa-cq-cqd-historical-reports#accessing-vaac-outside-of-power-bi%22https://learn.microsoft.com/en-us/microsoftteams/aa-cq-cqd-historical-reports#accessing-vaac-outside-of-power-bi%22)) there is a section explaining how we can use the VAAC API outside Power BI however the zip file provider do not include any API specification or Postman project...

Where can I find the API spec or the Postman project mentioned at the documentation?

Thanks

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jdacorr** [comment]
> Thank you for submitting feedback. I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs. Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

But the documentation is not right. There in an entire section explaining how to use VAAC with Postman but then the files needed to follow the instructions do not exist... As explained above the zip file downloaded through the link at the documentation do not include the API specification needed to create the project in Postman in order to use the API. Can you let me know here I can download that specification?
