### ISSUE TITLE
Page is wrong

### ISSUE THREAD

**Issue by sid-swirl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10080]
This page is incorrect. There is no "Resources" section on this page.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ccc5e95-049b-4132-3353-85804949edeb
* Version Independent ID: 8ccc5e95-049b-4132-3353-85804949edeb
* Content: [Step 2 - Create a resource account - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/hybrid-meetings-device-config-account?tabs=m365-admin-center)
* Content Source: [Teams/hybrid-meetings-device-config-account.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hybrid-meetings-device-config-account.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @sid-swirl 

If you refer to 

> Go to **Resources** in the left panel, and then select Rooms & equipment. If these options aren't available in the left panel, you may need to select Show all first.

You need to search that in the admin center and Resources option is there.

Thanks
