### ISSUE TITLE
Teams Admin account requirement.

### ISSUE THREAD

**Issue by d1bjo0** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10088]
[Enter feedback here]

FYI- For the [prerequisites](https://learn.microsoft.com/en-us/MicrosoftTeams/custom-meeting-backgrounds#prerequisites) - The Teams Admin account does not need to be licensed with the Teams Premium licenses to modify the config of meeting backgrounds. The account only needs a Teams license as per: https://learn.microsoft.com/en-us/microsoftteams/using-admin-roles#teams-roles-and-capabilities
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c3d5c2e-7936-6966-078f-304b628c9b74
* Version Independent ID: 1c3d5c2e-7936-6966-078f-304b628c9b74
* Content: [Custom meeting backgrounds for Teams meetings - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/custom-meeting-backgrounds)
* Content Source: [Teams/custom-meeting-backgrounds.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/custom-meeting-backgrounds.md)
* Service: **msteams**
* GitHub Login: @wlibebe
* Microsoft Alias: **wlibebe**

**Comment by get-itips** [comment]
Hello @d1bjo0 
From my point of view, the bulleted list of requirements is not stating that the Teams admin needs to be assigned the SKU listed in the previous bullet point.
Please let me know if I understood you correctly.
Thank you for your feedback!

**Comment by get-itips** [comment]
@scanum Closing, it can be re-opened if submitter comes back.
