### ISSUE TITLE
Max post size incorrect for channel

### ISSUE THREAD

**Issue by bandtank** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10089]
The channel post size is larger than 28 KB. It is listed as 40 KB in some places, so the documentation is inconsistent.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hello @bandtank Anthony,
Can you please point me where you saw 40 KB as listed? That will help me dig into this.
Thank you

**Comment by bandtank** [comment]
One of many places: https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/format-your-bot-messages

**Comment by get-itips** [comment]
That seems to be scoped to Bots, but I'll try to confirm, thanks

**Comment by get-itips** [comment]
Closing as that is scoped to bots currently.
