### ISSUE TITLE
How do I get the free numbers?

### ISSUE THREAD

**Issue by Mobilemaverick** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10098]
[Enter feedback here]

This does not work.  Chat support sent me to another site for the users to sign up at a user level. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e37f13b-cb86-955e-147c-fa916da063f9
* Version Independent ID: 4dd77188-abcb-fae2-3cf3-12b82b591bad
* Content: [Getting phone numbers for your users - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/getting-phone-numbers-for-your-users)
* Content Source: [Teams/getting-phone-numbers-for-your-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/getting-phone-numbers-for-your-users.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
