### ISSUE TITLE
Health - Microsoft 365 network connectivity

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10092]
Hi together

How can we download the following report over powershell?, please add in the documentation about health state in teams:
![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/26062079/710fc515-aa36-4895-834d-ddc448d86975)

I was not able to find it here:
https://learn.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-reporting-reference?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2202664-dfd1-d700-f72a-2262593d92bc
* Version Independent ID: 795f9821-b46d-0414-8569-d4d3513bbf04
* Content: [Verify service health for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/service-health?view=o365-worldwide)
* Content Source: [Teams/service-health.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/service-health.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
