### ISSUE TITLE
Missing part on the technical details of external transfer

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10090]
This link https://learn.microsoft.com/en-us/microsoftteams/create-a-phone-system-auto-attendant?tabs=general-info#external-phone-number-transfers---technical-details

There is a bullet point "External phone number - any phone number. See [external transfer technical details](https://learn.microsoft.com/en-us/microsoftteams/create-a-phone-system-auto-attendant?tabs=general-info#external-phone-number-transfers---technical-details)." but this ink does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a42f9e2c-aeee-76c4-620a-668cce21ba10
* Version Independent ID: 6ff06eab-9c80-9c30-95ef-c17e157fbea1
* Content: [Set up a Microsoft Teams auto attendant - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/create-a-phone-system-auto-attendant?tabs=general-info)
* Content Source: [Teams/create-a-phone-system-auto-attendant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/create-a-phone-system-auto-attendant.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@Larryngolog It seems like a Markdown issue where there was a missing space between the "---" line and the previous text line that wasn't properly closing out the tabbed conceptual section. Adding the line break seemed to add the missing section back into the article.

**Comment by DaniEASmith** [comment]
This will be updated today, so I'm closing this issue.
