### ISSUE TITLE
Extension Dialing/Auto Attendant

### ISSUE THREAD

**Issue by MBExatt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10093]
If a customer wants extension dialing but always wants to have a live person answer the phone, can they enable the Auto attendant feature but have incoming calls bypass the auto attendant and go straight to the receptionist?  If so, how would they do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 016be911-545f-28e4-97d2-549f1078a196
* Version Independent ID: 9021aad0-83c0-1173-01ae-6cc68217e8d4
* Content: [Auto attendant and call queue dialing and voice recognition reference - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/dial-voice-reference)
* Content Source: [Teams/dial-voice-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/dial-voice-reference.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by MBExatt** [comment]
@CLYVR Sorry I should have been more specific.  The customer would like to have extension dialing between internal users, or for transferring calls to other users, but not for inbound callers to use with the Auto Attendant.

**Comment by CLYVR** [comment]
@MBExatt Thanks for the clarification.  You will need two AAs.  

The first AA is for the external callers.  During business hours it will just forward the call to the operator (which may be a person or you may want to put the operator in a Call Queue if there are multiple operators).  

The second AA is for internal users and for external callers outside of business hours and when the operator doesn't answer.

**Comment by MBExatt** [comment]
@CLYVR Thank you.  The customer intends to have calls answered live 24/7.  So with that said, the first AA would always forward to an Operator.  In this case, do they still need the 2nd AA?

**Comment by CLYVR** [comment]
@MBExatt The second AA is needed for the internal callers.

**Comment by MBExatt** [comment]
@CLYVR Thanks.  So with the 2nd AA for the internal callers, will they also be able bypass the AA and just dial the 3 or 4 digit extension of the person they are trying to call, or will they need to go through AA prompts first?
