### ISSUE TITLE
Allow specific channels for guests access

### ISSUE THREAD

**Issue by itak006** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1009]
Allow specific channels for guests access instead of the whole team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams Guest Access checklist](https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist#-step-6-enable-specific-settings-for-channels)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @romanma
* Microsoft Alias: **romanma**

**Comment by AndreaBarr** [comment]
@itak006 Thank you for this suggestion.

I know the product teams are always looking for user feedback and how to make Teams better. They keep a close tab on User Voice [https://microsoftteams.uservoice.com/forums/555103-public/suggestions/31374577-guest-access-should-be-implemented-at-the-channel](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/31374577-guest-access-should-be-implemented-at-the-channel) and if you don't mind it would be awesome if you could look through and give your input in User Voice. I have upvoted this as well. It does look like they are working on it but even still the more upvotes we get for this the better.  
 
Thank you for your contribution to make the docs better! Much appreciated!
