### ISSUE TITLE
This form is no longer needed

### ISSUE THREAD

**Issue by ct-crayon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10102]
[Enter feedback here]
The request form is obsolete..."This form is no longer needed"
https://forms.office.com/pages/responsepage.aspx?id=v4j5cvGGr0GRqy180BHbR1ax4zKyZjVBmutzKVo1pVtURTVXM0wzSldCTjVERDlYRE1WWktQRDhURCQlQCN0PWcu

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6eb2244d-b82d-0559-0255-ac0cb7ce05e3
* Version Independent ID: e3a7a842-7efe-40db-e3c7-da56d7b24c02
* Content: [Export content with the Microsoft Teams Export APIs - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/export-teams-content#prerequisites-to-access-teams-export-apis)
* Content Source: [Teams/export-teams-content.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/export-teams-content.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback!
