### ISSUE TITLE
No Call Me Once Admitted to Meeting

### ISSUE THREAD

**Issue by D1441** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10107]
When I'm finally admitted to a meeting, I'm only given the option to call in.  There is not call-out option nor do I find a way to have it call me.  I could only turn computer audio mic on or off.  In meetings where I don't have to be admitted, I get the option to provide a phone number, select one of my known numbers, or get call-in numbers.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b759f354-bf74-3cff-0c96-3b28a27ee997
* Version Independent ID: fb2d8a68-f35a-bbee-a306-72ee20a450a3
* Content: [Set up the Call me feature for your users - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/set-up-the-call-me-feature-for-your-users)
* Content Source: [Teams/set-up-the-call-me-feature-for-your-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/set-up-the-call-me-feature-for-your-users.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
