### ISSUE TITLE
Update licensing requirement.

### ISSUE THREAD

**Issue by Pratikd-msft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10103]
As per MC533652 

Updated May 8, 2023: While in Public Preview, Avatars for Microsoft Teams was supported for all SKUs. However, at General Availability, Avatars for Microsoft Teams will only be supported for the following SKUs: Microsoft 365 Enterprise E3, Microsoft 365 Enterprise E5, Microsoft 365 Business Standard, Microsoft 365 Business Premium or Teams Premium. 

Current documentation does not include Teams Premium. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 122d9ead-09d3-f605-1bfb-6ae0fce81636
* Version Independent ID: 122d9ead-09d3-f605-1bfb-6ae0fce81636
* Content: [Set up avatars for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/meeting-avatars)
* Content Source: [Teams/meeting-avatars.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/meeting-avatars.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Information is now in the article.
