### ISSUE TITLE
The Video TMT 2.1 Remote Capture Tool can't install

### ISSUE THREAD

**Issue by Stevenli0205** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1010]
System: Win8.1 x64
"RemoteCaptureTool.Windows_2.1.0.21_x86_x64_arm.cer" has expired. One possible cause is the system clock isn't set to the correct date and time. If the system settings are correct, contact the app owner to re-create a package or bundle with a valid certificate.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 62fe7364-968f-95d3-0c3c-9e77984b3f51
* Version Independent ID: 226f9a66-2409-c1c8-4971-a21c1a75bb2f
* Content: [Skype for Business certification program - Test Specifications](https://docs.microsoft.com/zh-tw/SkypeForBusiness/certification/test-spec)
* Content Source: [Skype/SfbPartnerCertification/certification/test-spec.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbPartnerCertification/certification/test-spec.md)
* Service: **skype-for-business**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by Stevenli0205** [comment]
> 
>
>System: Win8.1 x64 
> "RemoteCaptureTool.Windows_2.1.0.21_x86_x64_arm.cer" has expired. One possible cause is the system clock isn't set to the correct date and time. If the system settings are correct, contact the app owner to re-create a package or bundle with a valid certificate.
> #### 文件詳細資料
> 
> ⚠ _請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。_
> 
>     * ID: 62fe7364-968f-95d3-0c3c-9e77984b3f51
> 
>     * Version Independent ID: 226f9a66-2409-c1c8-4971-a21c1a75bb2f
> 
>     * Content: [Skype for Business certification program - Test Specifications](https://docs.microsoft.com/zh-tw/SkypeForBusiness/certification/test-spec)
> 
>     * Content Source: [Skype/SfbPartnerCertification/certification/test-spec.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbPartnerCertification/certification/test-spec.md)
> 
>     * Service: **skype-for-business**
> 
>     * GitHub Login: @jambirk
> 
>     * Microsoft Alias: **jambirk**

**Comment by AndreaBarr** [comment]
@Stevenli0205 Thank you for this feedback

I am not sure why the TMT 2.1 won't install. I want to get you over to Support since they have more resources than we do here to dig in and find a solution for this install issue. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by ggcleyang** [comment]
> System: Win8.1 x64
> "RemoteCaptureTool.Windows_2.1.0.21_x86_x64_arm.cer" has expired. One possible cause is the system clock isn't set to the correct date and time. If the system settings are correct, contact the app owner to re-create a package or bundle with a valid certificate.
> 
> #### 文件詳細資料
> ⚠ _請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。_
> 
> * ID: 62fe7364-968f-95d3-0c3c-9e77984b3f51
> * Version Independent ID: 226f9a66-2409-c1c8-4971-a21c1a75bb2f
> * Content: [Skype for Business certification program - Test Specifications](https://docs.microsoft.com/zh-tw/SkypeForBusiness/certification/test-spec)
> * Content Source: [Skype/SfbPartnerCertification/certification/test-spec.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbPartnerCertification/certification/test-spec.md)
> * Service: **skype-for-business**
> * GitHub Login: @jambirk
> * Microsoft Alias: **jambirk**

**Comment by ggcleyang** [comment]
the issue fixed？ I have  same issue， Video TMT 2.1 Remote Capture Tool can't install
system：win10 x64
the issue result， can‘t conect remote client and capture frames.

**Comment by vishnu001** [comment]
@AndreaBarr We are trying to use RemoteCaptureTool and facing same issue as @Stevenli0205 . is there a way to solve this issue ?
