### ISSUE TITLE
Teams Android Devices - Hot Desk Conditional Access issues

### ISSUE THREAD

**Issue by dbradley-expo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10108]
Hi Teams, 

I am looking at page Teams/rooms/supported-ca-and-compliance-policies.md which relates to supported conditional access settings for Teams Android devices. I see an issue when a user logs in to the Teams Android device through the HotDesk feature that the device information does not get passed during login and device filters (based on the ID, Model, Manufacturer etc) do not apply in Conditional Access. 

For example, if I have a Common Area Teams Android devices logged in with a user that is assigned a Teams Shared Device license, when I then click on HotDesk and sign in with a user account (this user account is subject to a conditional access policy with app protection), even with a device filter on this conditional access policy to exclude, the filter is ignored and the login is blocked.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
