### ISSUE TITLE
Emoto-human analytics in MSoft Teams

### ISSUE THREAD

**Issue by BedeInOz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10101]
Hello all,
A short trawl of search engines looking for "MSoft teams emoji analytics" delivered a good range of stories about deployment and the 'excitement and fun' (yawn) of expressing immediate sentiment for a user within a chat environment.

The ecosystem within MSoft Teams also makes extensive use of sentiment expression /reaction via emojis.

Search results such as....
_Celebrate success using Together Emojis in Microsoft Teams
What’s New in Microsoft Teams Feature Spotlight – New Fluent Emoji ...
Fluent Emojis Arrive in Microsoft Teams
Microsoft Teams public preview adds over 800 emojis and new in-meeting ...
Send an emoji, GIF, or sticker in Teams - Microsoft Support__

Ok, my simple issues are:
  -   where does one find, build or run a report on emoji use?
  -   analysis of the words within the chat seeking statistical relevance of words used, and
  -  AI support looking at themes, issues and serious vs fun commentary

Any pointers or insight is as always warmly appreciated.
Am not here all that often, here is a direct email for responses  >>  yua5i9p9d@mozmail.com

Thank you,
BedeInOz

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78ade1a4-092c-1132-44df-ee2c683fdd33
* Version Independent ID: 396b1aee-2f40-9895-9b00-07e38d11d31b
* Content: [Microsoft Teams analytics and reporting - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-reporting-reference)
* Content Source: [Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/teams-analytics-and-reports/teams-reporting-reference.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
