### ISSUE TITLE
Loop components and pages switched from using the .fluid extension to the .loop extension

### ISSUE THREAD

**Issue by lornemaclen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10110]
As per MC533813, Loop components and pages switched from using the .fluid extension to the .loop extension, to align with the Microsoft Loop brand in April 2023.  
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 276b708d-786c-3981-7b22-2fdb5e96599a
* Version Independent ID: 276b708d-786c-3981-7b22-2fdb5e96599a
* Content: [Overview of Loop components in Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/loop-components-in-teams)
* Content Source: [Teams/loop-components-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/loop-components-in-teams.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Document has been updated
