### ISSUE TITLE
Locations vs CQD upload

### ISSUE THREAD

**Issue by s1satya** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1011]
I am planning to upload network data for my organization and i see both of the below options still available to upload data:

1. Locations under modern portal
2. Tenant data upload under CQD portal
which one are we suppose to use?

I uploaded a sample data under CQD portal which didn't show up under locations tab in modern portal, so at this point i am not sure which option to use. Can anyone comment on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f8119c9-61af-b469-af98-ddd37764c0ca
* Version Independent ID: 7d829a74-9df7-5b6f-8e1c-44d3e5d38f75
* Content: [Adding and updating Locations data](https://docs.microsoft.com/en-US/microsoftteams/learn-more-about-site-upload?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/learn-more-about-site-upload.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/learn-more-about-site-upload.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **lolaj**

**Comment by CrystalThomasMS** [comment]
Thanks for your patience! Here's a response from one of our PMs: 

"It’s my understanding that these endpoints are reciprocal, meaning uploading in the Teams admin center & uploading in CQD hits the same back-end location.  My suspicion though is that the data is still being processed in the back-end."

If this doesn't help and your issue still unresolved, I recommend opening a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be clarified in the documentation. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind, please keep us posted here on the resolution!
