### ISSUE TITLE
[Doc-Enhancement] "Review permissions and consent" button leading to error

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10114]
If the third-party app don't have any Graph API permissions added to app registration and if the Global admin click on "Review Permissions and consent", it is showing error as "**We can't grant consent to the permissions you requested. Try again. If you continue to have problems, contact [Microsoft customer support]**(https://learn.microsoft.com/en-US/office365/admin/contact-support-for-business-products?WT.mc_id=TeamsAdminCenterCSH)." in Teams admin center.

This is an expected behavior.
If the app registration don't have minimum User.Read Graph API permission, then admin cannot provide consent. So, the specific button click leads to error. So, please mention the note in documentation.

![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/69682598/6549b81f-4853-4469-a245-e9ad13653f57)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa7ace5-8129-5f9c-e8b1-7a10b985c8ff
* Version Independent ID: e4b85639-1cf9-e3f2-8429-c7e92391f5c2
* Content: [View app permissions and grant admin consent in the Microsoft Teams admin center - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/app-permissions-admin-center)
* Content Source: [Teams/app-permissions-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/app-permissions-admin-center.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by ashishguptaiitb** [comment]
Thanks @SubbaReddi for sharing this. I tried and I'm getting a slightly different error. I shall document that some error is received. Separately, I shall find what errors are possible in this scenario.
 
CC @dariomws and @scanum

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
