### ISSUE TITLE
Not working in GCC

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10119]
We have been troubleshooting for hours and this is not working in GCC for us.  **IF NOT SUPPORTED IN GCC YOU MUST ADD THIS INFO TO THE LIMITATION SECTION!!!!**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e4c946e-ec50-995e-87ec-4de4ec9009fd
* Version Independent ID: 6e4c946e-ec50-995e-87ec-4de4ec9009fd
* Content: [Adobe Acrobat as a default PDF viewer in Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/adobe-acrobat-pdf-viewer-teams)
* Content Source: [Teams/adobe-acrobat-pdf-viewer-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/adobe-acrobat-pdf-viewer-teams.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by get-itips** [comment]
Thanks for your feedback

**Comment by ssmiller60** [comment]
What was done here to address this???
I am reviewing the public document and GCC is still not mentioned????

**Comment by get-itips** [comment]
It takes some time until the published version of the article is updated after PR merge.

**Comment by ssmiller60** [comment]
Shouldn't the issue remain open until it is resolved in the public facing
document?
