### ISSUE TITLE
Communications credit not required in some situations?

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10111]
Hi, the following note from this page does not seem to be completely accurate:

_To route calls to unassigned Microsoft Calling Plan subscriber numbers, your tenant needs to have available [Communications Credits](https://learn.microsoft.com/en-us/microsoftteams/what-are-communications-credits)._

I tested this and found this not to be accurate. I setup an unassigned number routing rule for an Operator Connect tenancy without any Microsoft Communications credits. I rang a few unassigned numbers and the rules worked without MS Comms credits for unassigned user/subscriber numbers or unassigned VoiceApp numbers.

The tenancy is in Australia where typically only a Caller pays for the cost of a call. The Operator Connect provider was Telstra.

Could you please review and ensure documentation is accurate and note any exceptions for scenarios in other countries or difference between call plans/Operator Connect/Direct Route with regards to unassigned number routing rules? this should help this document to be even better :)

Many Thanks 🙂

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed4beab-bb0d-fba4-814e-147d22fd97e5
* Version Independent ID: 8ed4beab-bb0d-fba4-814e-147d22fd97e5
* Content: [Routing calls to unassigned numbers - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/routing-calls-to-unassigned-numbers)
* Content Source: [Teams/routing-calls-to-unassigned-numbers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/routing-calls-to-unassigned-numbers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @SvenBell 
Please let me know if I misunderstood

You say you tested using Operator Connect but the quote mentions specifically Calling Plans...

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by SvenBell** [comment]
Yes, you are correct the quote does say "**Microsoft calling plan** subscriber numbers". (That could be highlighted ;))

It would be good to note for reference any differences when it comes to Operator Connect/Direct Route/Telstra Call plan unassigned subscriber numbers. Also, it says Subscriber but could you clarify do you mean User/Service or Both number types?
