### ISSUE TITLE
Inaccurate information regarding "Configure conditional access"

### ISSUE THREAD

**Issue by blakebourgeois** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10129]
The article notes "If your devices are on the new sign-in experience, then you should exempt either the Teams app or the SIP Gateway App (ID - 0ab9de21-b802-4d77-b279-1ad41ca233b4) from conditional access checks."

The Sip Gateway API (resource ID 0ab9de21-b802-4d77-b279-1ad41ca233b4) and the Sip Gateway UserApp (582b2e88-6cca-4418-83d2-2451801e1d26) that can be seen for the related signins in the Azure AD portal are **not available for adding to Conditional Access inclusion or exclusion lists**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 05173ea8-db7c-a20d-3783-178b3d649190
* Version Independent ID: 05173ea8-db7c-a20d-3783-178b3d649190
* Content: [Configure SIP Gateway - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/sip-gateway-configure#configure-conditional-access)
* Content Source: [Teams/sip-gateway-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/sip-gateway-configure.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Sentence has been updated to clarify.
Thank you!

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by blakebourgeois** [comment]
It's now got a typo and it's still inaccurate to how the experience with conditional access actually works.
