### ISSUE TITLE
Update for new available and announced features

### ISSUE THREAD

**Issue by Kofl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10127]
Any update on new features like Smart camera for Android and announcements made here:
https://techcommunity.microsoft.com/t5/microsoft-teams-blog/what-s-new-for-microsoft-teams-rooms-and-teams-meetings-at/ba-p/3843949

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 64cc650b-b313-cfab-9f45-190b94c128f4
* Version Independent ID: 9e93ac07-3f1b-9fd4-1907-17f0075bd837
* Content: [Teams Rooms on Windows and Android feature comparison - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/teams-devices-feature-comparison)
* Content Source: [Teams/rooms/teams-devices-feature-comparison.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/rooms/teams-devices-feature-comparison.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by get-itips** [comment]
I could get information that the article is in the process of being updated
