### ISSUE TITLE
Typo - the word "Inference" should be "Interference"

### ISSUE THREAD

**Issue by ThurstBuster** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10120]
Reading through this doc and the word "Inference" is used when I believe "Interference" was the intent.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78187b02-b08d-5b10-587d-82c81652b675
* Version Independent ID: 78187b02-b08d-5b10-587d-82c81652b675
* Content: [Plan for Microsoft Teams Rooms - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-plan)
* Content Source: [Teams/rooms/rooms-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/rooms/rooms-plan.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by get-itips** [comment]
Thanks for your feedback
