### ISSUE TITLE
List of available update settings are not accurate

### ISSUE THREAD

**Issue by born-slippy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10130]
Reference:  https://learn.microsoft.com/en-us/microsoftteams/public-preview-doc-updates#set-the-update-policy

In the Teams Admin center: https://admin.teams.microsoft.com/policies/updatemanagement

The available options for 'Show Teams preview features' when configuring an update policy are:

- Off
- Users can opt in
- On for users in Current Channel (Preview)
- On for everyone

The documentation should be updated to reflect the current setting values.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5f1cdd1-09ff-f95d-6d50-e7880d34020f
* Version Independent ID: 59219640-305b-30c1-bc10-87e2633d95db
* Content: [Public preview in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/public-preview-doc-updates)
* Content Source: [Teams/public-preview-doc-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/public-preview-doc-updates.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Article has been updated.
Thank you!
