### ISSUE TITLE
These instruction are not completable in the first few steps.  Communication Credits, is no longer an option provided in the Purchase Services page.

### ISSUE THREAD

**Issue by nationalparcel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10136]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 277cf140-5c6c-82c7-cc56-490ef2188754
* Version Independent ID: 72e7de29-fd71-23bf-15a7-172634c2a5fd
* Content: [Set up Communications Credits for your organization - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/set-up-communications-credits-for-your-organization)
* Content Source: [Teams/set-up-communications-credits-for-your-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/set-up-communications-credits-for-your-organization.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@nationalparcel I just ran a test in the tenant, and I am able to view and purchase Communication Credits. The "Featured" tag has to be unmarked, or you can search for Communicaton Credits. If you're still not seeing Communication Credits in your tenant, you should submit a support ticket.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
