### ISSUE TITLE
Document Review with new Information.

### ISSUE THREAD

**Issue by jabangas** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10135]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

Update Document with the following URL , that needs to be allowed : portal.sdg.teams.microsoft.com

Also mention this two IPs 13.107.246.60 / 13.107.213.60 , that need to be allowed and they are documented on aka.ms/o365ip and which BGP Community they are under.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 05173ea8-db7c-a20d-3783-178b3d649190
* Version Independent ID: 05173ea8-db7c-a20d-3783-178b3d649190
* Content: [Configure SIP Gateway - Microsoft Teams](https://review.learn.microsoft.com/en-us/microsoftteams/sip-gateway-configure?branch=main)
* Content Source: [Teams/sip-gateway-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/sip-gateway-configure.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by tonysmit** [comment]
The customer must use the most update to date reference we have (https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#skype-for-business-online-and-microsoft-teams). I'm working with the PM to remove all IP addresses from this article and then link to the article here. It's kept up to date and adding more IP addresses just makes it harder to manage. Thanks!
