### ISSUE TITLE
1:1 calls support status for Safari browser is incorrect

### ISSUE THREAD

**Issue by Draykan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10148]
Web browser compatibility table states this for Safari 13.1+ and 14+ browsers:
**"1:1 calls not supported. Group calls fully supported."**

I already reported this error with issue #9184 but it has been closed without merging the changes in #9222 to correct the table.

In the past, roadmap item 87312 was available highlighting that 1:1 calls had been introduced to Safari but it seems that now it has been removed from [Microsoft 365 roadmap website](https://www.microsoft.com/en-us/microsoft-365/roadmap?searchterms=87312).

However, I can assure you that 1:1 calls have been working on Safari for a long time and there are a lot of references still available on the Internet about the now missing Feature ID 87312:
• https://mspoweruser.com/microsoft-teams-1-to-1-calling-apple-safari/
• https://pupuweb.com/mc286561-microsoft-teams-calling-safari-browser/
• https://www.reddit.com/r/M365Reports/comments/pt132t/now_you_can_initiate_teams_11_call_from_safari/
• https://app.cloudscout.one/evergreen-item/87312/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c86f401-cff4-93b3-ff69-b9787a87e644
* Version Independent ID: c0808bd3-cf63-0625-4c3c-65469c26fb3e
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/get-clients?tabs=Windows#web-client)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @Draykan 
I'll dig into why the past PR was closed before creating a new one.
Thanks for your feedback,

**Comment by get-itips** [comment]
The past PR was merged, closing.
