### ISSUE TITLE
Can't delete apps.  It's not listed even though the docs say it's there.

### ISSUE THREAD

**Issue by VNJoe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10141]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 632a367f-0c30-fc21-5040-d2d80f184bdb
* Version Independent ID: 6cab37af-6dcf-d2c1-3d68-14fc7375f1f5
* Content: [Upload your custom apps in the Microsoft Teams admin center - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/upload-custom-apps)
* Content Source: [Teams/upload-custom-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/upload-custom-apps.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by get-itips** [comment]
Hello @VNJoe how are you?
Can you please detail what you are not seeing on your Teams admin center so I can try to reproduce? Thank you

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by ashishguptaiitb** [comment]
Hi @VNJoe , I've mentioned how to delete custom apps here -> https://learn.microsoft.com/en-us/microsoftteams/teams-custom-app-policies-and-settings#delete-custom-apps-from-your-organizations-catalog
Another insert in the docs is about stopping usage of an app -> https://learn.microsoft.com/en-us/microsoftteams/manage-apps#stop-app-usage-and-remove-app

Not sure if you were looking for all this info but see if it helps.

**Comment by ashishguptaiitb** [comment]
> Hi @VNJoe , I've mentioned how to delete custom apps here -> https://learn.microsoft.com/en-us/microsoftteams/teams-custom-app-policies-and-settings#delete-custom-apps-from-your-organizations-catalog Another insert in the docs is about stopping usage of an app -> https://learn.microsoft.com/en-us/microsoftteams/manage-apps#stop-app-usage-and-remove-app
> 
> Not sure if you were looking for all this info but see if it helps.

CC @get-itips and @scanum as FYI.
