### ISSUE TITLE
Missing -resultsize unlimited in the Get-ExoMailbox command

### ISSUE THREAD

**Issue by ZD4LIFE** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10145]
Someone needs to add in the -resultsize unlimited  argument in the Get-ExoMailbox command.  In larger environments it will only pull back the default 1000 objects.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 46740b3f-d12b-f40f-1b71-f66da9422fc6
* Version Independent ID: 46740b3f-d12b-f40f-1b71-f66da9422fc6
* Content: [Find Teams Rooms devices with unsupported licenses - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/rooms/license-check)
* Content Source: [Teams/rooms/license-check.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/rooms/license-check.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by get-itips** [comment]
Thanks for your feedback
