### ISSUE TITLE
"Privacy Mode" may no longer be a thing

### ISSUE THREAD

**Issue by FC-EricWeller** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10142]
[Enter feedback here]
There are mutiple references to "Privacy Mode" on this page.  Example:
"In Teams, presence sharing is always enabled for users in the organization unless Privacy mode is enabled. In Privacy mode, presence is not visible to external users."

There is no link or reference regarding Privacy Mode, it's features or constraints, or how to manage it.  A search of the rest of the Teams documentation reveals that only this page contains the term.

The feature is either deprecated and references to it need to be updated, or more detailed documentation about managing the feature needs to be included or linked.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a162ef5c-3099-7f58-4178-d29e3ec2b5a7
* Version Independent ID: 6ca31e56-052d-6c62-1323-b5aaaae1f04a
* Content: [User presence in Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/presence-admins#user-configured-states-expiration)
* Content Source: [Teams/presence-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/presence-admins.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @FC-EricWeller thanks for your feedback

**Comment by FC-EricWeller** [comment]
#10159 doesn’t appear to change this issue?  The link in the preview appears to be invalid (https://github.com/get-itips/OfficeDocs-SkypeForBusiness/blob/patch-255/powershell/module/skype/set-csprivacyconfiguration#-enableprivacymode)

For what it’s worth  we opened a ticket with MS Support on this issue and were told that the EnablePrivacyMode setting from SfB is NOT supported for Teams.


Eric F. Weller
Manager, IS Operations
9275 W Russell Rd, Suite 240, Las Vegas, NV 89148
T:702.692.8060
***@***.***





CONFIDENTIALITY NOTICE:
The information contained in this message may be protected by the attorney-client privilege. 
If you believe that it has been sent to you in error, do not read it. Please immediately reply 
to the sender that you have received the message in error. Then delete it. 
Thank you.
