### ISSUE TITLE
Global Reader cannot view Teams Rooms Pro Management

### ISSUE THREAD

**Issue by loaderladdy-work** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10140]
is having the Global Reader role not being able to view the Teams Rooms Pro Management Portal by design? or an error in developing the product?

If it is the former can the documentation explain why Global Reader does not have access to the portal please?

Thanks,

Pete

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9211ee7-1c36-f653-9c3c-dfda04fdf77c
* Version Independent ID: b9211ee7-1c36-f653-9c3c-dfda04fdf77c
* Content: [Role-based access control in the Microsoft Teams Rooms Pro Management Portal - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-pro-rbac)
* Content Source: [Teams/rooms/rooms-pro-rbac.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/rooms/rooms-pro-rbac.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @altsou
* Microsoft Alias: **altsou**

**Comment by get-itips** [comment]
Hello @loaderladdy-work how are you?
The current roles that can access the portal are the ones described in the article, from what I could dig in the past that is by design, if that changes in the future the documentation will be updated.
Thank you,

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by loaderladdy-work** [comment]
thank you @get-itips .  I appreciate your feedback 💯
