### ISSUE TITLE
Match regions for licenses and resource account numbers.

### ISSUE THREAD

**Issue by Richiana** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10143]
[Enter feedback here]
When assigning a Microsoft Teams Phone Resource Account license, make it clear to select the region in which the account is assigned to from the drop down list at the top of the license selection page.  Otherwise when searching for a phone number to assign to a Resource Account, if the regions don't match, you won't see your number.  For example, if the region in licenses is set to United Kingdom, and the resource account number is a US number, only +44 numbers will be listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts for service numbers - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-resource-accounts)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by get-itips** [comment]
Thanks for your feedback!
