### ISSUE TITLE
Side-by-side migration is not new

### ISSUE THREAD

**Issue by stevenvanh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1014]
Side-by-side migration is not new, so that should not be mentioned as such under "What's new"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6d0f328-2191-7333-28e8-e8bf93418252
* Version Independent ID: 61598753-26f9-3ed7-f2d1-de55c8cb5bd6
* Content: [What's new in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/whats-new#installation-and-upgrade-side-by-side-migration)
* Content Source: [Skype/SfBServer2019/whats-new.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/whats-new.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by LolaJacobsen** [comment]
@jambirk is updating the article. Closing this out here.
