### ISSUE TITLE
Teams Android Meeting UI Licensing Documentation Incorrect

### ISSUE THREAD

**Issue by hh-trj** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10152]
As of Microsoft Teams phone app version 1.0.94.2023060906 released June 15, the E3 and E5 licenses mentioned in the article can no longer be used to enable the Meeting UI. The article says:

> An E3 or E5 license supports all sign-in modes.

However, this is not true as of the latest app version. As soon as the app is updated to the latest version, the UI reverts from the Meeting UI to the User UI, even though the IPPhonePolicy SignInMode is set to "MeetingSignIn".

Microsoft Support has confirmed for us in ticket #35771137 that E3 and E5 licenses are not supported mechanisms to use the MeetingSignIn mode, contrary to what the documentation says.

I hope that this is a bug and support is incorrect, but as of right now with the latest Teams desk phone app, the documentation is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62d58962-9b2f-0231-187b-58c845e52a0c
* Version Independent ID: b3045cca-8bcb-8d30-0dda-49aed3009172
* Content: [Set Microsoft Teams Android devices user interface - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/devices/teams-android-devices-user-interface)
* Content Source: [Teams/devices/Teams-Android-devices-user-interface.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/devices/Teams-Android-devices-user-interface.md)
* Service: **msteams**
* Sub-service: **itpro-devices**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by get-itips** [comment]
Hello @hh-trj I'm working on this

**Comment by get-itips** [comment]
I was let known that a document update is on the works
