### ISSUE TITLE
"Communication Credits" Not found under "Purchase Services"

### ISSUE THREAD

**Issue by Zepolian16** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10156]
Hello,
We are in need to apply the communication credits for a toll free 1-800 number.
We are unable to find this option via the tenant directly nor via our CSP.

All appropriate licenses have been applied.
Is there something else that is needed or a request that must be submitted to have this option available?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
