### ISSUE TITLE
Error messages need further detail

### ISSUE THREAD

**Issue by CB72** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10153]
[Enter Comment here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69c67496-cace-f833-7cfc-dca7722fef3e
* Version Independent ID: 5a14f81c-529c-4971-5ce8-39633834d4d3
* Content: [Assign, change, or remove a phone number for a user - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/assign-change-or-remove-a-phone-number-for-a-user)
* Content Source: [Teams/assign-change-or-remove-a-phone-number-for-a-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/assign-change-or-remove-a-phone-number-for-a-user.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CB72** [comment]
It would be good to see some documentation on what the various error messages mean.

e.g. What does it actually mean when we see an error message like:

"The location can't be updated because the activation state is pending".

Like, what controls the activation state? How long should we expect to wait for it to change state?
Is there anything we can do to expedite the activation?
We've had a number stuck in this state for 2 weeks now. Not good for business.

**Comment by get-itips** [comment]
Hello @CB72 how are you?
I'll pass this feedback on to the Docs team, in the meantime, and to resolve your issue, maybe the best would be to open a support request from your tenant, if you didn't already done that.
Thank you

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
