### ISSUE TITLE
Incorrect date

### ISSUE THREAD

**Issue by born-slippy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10165]
The chart in this section:  https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin#update-channels-1

Lists:
<html>
<body>

Semi-Annual Enterprise Channel, Semi-annual Extended, LTSC, and remaining channels | Mid January 2023
-- | --

</body>
</html>

The date should read as **Mid January 2024**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Version Independent ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Content: [The new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin)
* Content Source: [Teams/new-teams-desktop-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-desktop-admin.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello, thanks for your feedback
