### ISSUE TITLE
Update Article with information about the free-audio conferencing SKU available for E1/E3.

### ISSUE THREAD

**Issue by cadasi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10169]
We need to improve information in this article on how the new (not so new anymore, since around May/2022) free Audio-Conferencing SKU works with E3 and E1 and what a customer needs to do.  We also need to explain that the free Audio Conferencing license for E3/E1 includes only domestic calling. It's very confusing to understand that and there's no information here to help or in any other Microsoft Teams/Audio Conferencing article that I could find - it also leads to believe that only E5 has Audio Conferencing included, which is not true anymore.
We received an escalation from a strategic (S500) customer on this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed33488-1a24-f443-dd56-c5327188b5a4
* Version Independent ID: 8da32180-396d-c7a8-6410-472beabff9ce
* Content: [Set up Audio Conferencing for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/set-up-audio-conferencing-in-teams)
* Content Source: [Teams/set-up-audio-conferencing-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/set-up-audio-conferencing-in-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by MicrosoftHeidi** [comment]
I'm working with Carlos on this outside of this thread.
