### ISSUE TITLE
Yealink-T55/T56/T58 Incorrect Name/Missing Full name.

### ISSUE THREAD

**Issue by amirislam117** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10167]
Hello Team,

Please be informed that "Teams phones Yealink-T55/T56/T58, Firmware: 58.15.0.124, on this article "https://learn.microsoft.com/en-us/microsoftteams/devices/remote-provision-remote-login" is not properly mentioned. For example, the exact model is T58A, which is not mentioned as per Yealink Website nomenclature. Also, can you kindly mention that These model numbers have 3 variants and, in some cases, different Firmware versions which may be confusing sometimes, as T58A has SFB version and Teams Version as well. Screenshot Attached.

https://www.yealink.com/en/product-detail/microsoft-teams-phone-t58a
https://www.yealink.com/en/product-list/eol-products?filter=all-eol-products

![Teams Devices](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/138701301/2796c223-45cd-4846-b1c6-d906886af152)

Kindly update this detail.
Thanks and With regards.

**Comment by get-itips** [comment]
Thanks for your feedback

**Comment by amirislam117** [comment]
Hello

Thanks a lot for the update, really appreciate your feedback and quick approval. Please correct me if I am wrong as I am not aware of how these requests and contributions work and are managed via GitHub, My question is since my Query was raised before shouldn't the newer query be merged with Older Query, instead of the opposite? Also, will it add my name to the contributors of the page "Remote provisioning and sign in for Teams Android devices - Microsoft Teams | Microsoft Learn<https://learn.microsoft.com/en-us/microsoftteams/devices/remote-provision-remote-login>".


Thanks


With Regards

Amirul Islam | Email: ***@***.******@***.***>

Microsoft 365 Tier 2 Support Ambassador

Working Hours: Monday to Friday (05:30 AM to 02:30 PM EST)

My Technical Lead: Aparna Shukla | Email: ***@***.******@***.***>

My Team Manager: Ravinder Mallidi | Email: ***@***.******@***.***>

Technical Advisor: Aparna Dhopatkar | ***@***.******@***.***>

________________________________

**Comment by amirislam117** [comment]
Hello

Thanks a lot for the update, really appreciate your feedback and quick approval. Please correct me if I am wrong as I am not aware of how these requests and contributions work and are managed via GitHub, My question is since my Query was raised before, shouldn't the newer Query be merged with Older Query, instead of the opposite? Also, will it add my name to the contributors of the page "Remote provisioning and sign in for Teams Android devices - Microsoft Teams | Microsoft Learn<https://learn.microsoft.com/en-us/microsoftteams/devices/remote-provision-remote-login>".

Thanks

With Regards
Amirul Islam | Email: ***@***.******@***.***>
Microsoft 365 Tier 2 Support Ambassador
Working Hours: Monday to Friday (05:30 AM to 02:30 PM EST)
My Technical Lead: Aparna Shukla | Email: ***@***.******@***.***>
My Team Manager: Ravinder Mallidi | Email: ***@***.******@***.***>
Technical Advisor: Aparna Dhopatkar | ***@***.******@***.***>

**Comment by tiburd** [comment]
@amirislam117 
Hello,

We appreciate that you took time to provide detailed feedback via this GitHub issue.

Issues are not necessarily resolved in the order they are received, and for the changes to appear in the article, a pull request must be created and merged.

Submitting an issue about an article does not add your GitHub ID to the contributors list for the article. If you submit a pull request that the article author approves, your GitHub ID is added to the list of contributors after the pull request is merged.

For information about creating pull requests, see:

- [Microsoft Learn documentation contributor guide overview](https://learn.microsoft.com/en-us/contribute/)

Best regards,
--Tina

**Comment by amirislam117** [comment]
Hello Tina,

Thanks for the response, and clarification, I had no idea how to create a pull request, because normally what people do is go to the bottom of the page and click on the GitHub feedback link and submit an issue request. Also do you mean to say that if someone creates a Normal Issue request and if that request is a valid/strong issue/BUG, some other experienced contributor can come and create the pull request, merge the issue for the exact same thing and get his/her name on the document contributors list. I genuinely feel It is not fair, again being of lesser experience, I may be completely wrong with my feelings. Just an additional information, it took me 17 Days of troubleshooting, fixing correct firmware, working on multiple Cases via DFM (CSS) to find the issue and report it.


Thanks


With Regards

Amirul Islam | Email: ***@***.******@***.***>

Microsoft 365 Tier 2 Support Ambassador

Working Hours: Monday to Friday (05:30 AM to 02:30 PM EST)

My Technical Lead: Aparna Shukla | Email: ***@***.******@***.***>

My Team Manager: Ravinder Mallidi | Email: ***@***.******@***.***>

Technical Advisor: Aparna Dhopatkar | ***@***.******@***.***>

________________________________

**Comment by tiburd** [comment]
I understand your concerns. They are both due to GitHub design.

Pull requests are often created to resolve customer-submitted issues. The pull request to resolve the issue you submitted was created by our freelance partner, not by a customer. After our freelance partner, Andres/get-itips, created the pull request, the article author, Tony Smith, reviewed, approved, and merged the pull request.

The pull request includes a link to your issue, so if someone researches the change, their search should lead them to the pull request, which leads them to the issue that you submitted.

**Comment by amirislam117** [comment]
Hello Tina,

First of all, I would like to express my sincere appreciation for all the freelancers and testers out there working on Bug Fixes and maintenance of these articles without you guys none of this would be possible, includes everyone.

My understanding as of now is that basically, there is no way that someone (freelance partner) could have told or instructed/guided me to create a pull request myself which would have been nice, if that's not possible and if only Freelance Partners can create Pull requests how come there are 14 Contributors on the article most of them are just one time contributors, and If Tony Smith is the author why was he recently added as 14th contributor on his own authored article.

Kindly understand that it is very important for me to get my name on the contributors due to several reasons. Is there a way we can fix it. Please guide.

![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/138701301/96b4ccd5-a2ee-4194-8c36-8f19f87a0d64)
