### ISSUE TITLE
Terrible Teams Installation

### ISSUE THREAD

**Issue by TotallyInformation** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1016]
"installed in that user's appdata folder" - the creation of the MSI completely misses the actual issue with the Teams client on Windows. Many enterprise desktops block applications except in "Program Files". Also, using appdata increases roaming profile sizes enormously. Teams is NOT a consumer tool. Please give your dev team a serious talking to and get Teams installed to the correct and manageable location. There are dozens of requests for this on UserVoice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b13006b-d1de-8bc7-e0c6-b7022af0e731
* Version Independent ID: d29dae65-bb28-8767-cfd7-07d2ed5fd460
* Content: [Install Microsoft Teams using MSI](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @Lester-Hewett
* Microsoft Alias: **lehewe**

**Comment by AndreaBarr** [comment]
@TotallyInformation Thank you for this suggestion. 

I know that this is something that we have been actively working on getting set up. I found a user voice that says they have an install that installs to Program files. I will list the link below. If this doesn't work for you please let me know. 

https://microsoftteams.uservoice.com/forums/555103-public/suggestions/17380159-improve-install-options-install-for-all-users-an

**Comment by TotallyInformation** [comment]
Thanks Andrea, I will check that out.

**Comment by TotallyInformation** [comment]
Please note that the referenced article does NOT solve the issue. The MSI install only installs the `setup.exe` application to `program files` and runs it the first time a new user logs in. The application itself still installs to `%userprofile%\AppDaa\Local\Microsoft\Teams`.

**Comment by PBrawn** [comment]
Yes, they ignored the part about installing and running from program files directories, fixed everything else and marked it as closed.

**Comment by TotallyInformation** [comment]
I think a new issue should be opened. In the meantime, I'm compiling a list of Teams and Teams client issues for a contact within Microsoft.
