### ISSUE TITLE
Instructions Incorrect & Missing Stronger Troubleshooting Steps

### ISSUE THREAD

**Issue by RyanBlakeIT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10162]
The instructions show to use `^\+?15555551212$`, however this did not result in the number being blocked.  I opened a ticket with Microsoft Support and they provided me with the format of: `^\+15555551212`.  I was later given the instructions of just area code with number `5555551212`.  There should also be ways to review real call logs and see where this is working outside of running just a Test script that is included in these instructions as part of troubleshooting.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91c40ca3-c19e-eac3-3adb-815e45ce2388
* Version Independent ID: 1193b36e-8870-aca9-cb9c-59c5fb1f5412
* Content: [Block inbound calls in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/block-inbound-calls)
* Content Source: [Teams/block-inbound-calls.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/block-inbound-calls.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @RyanBlakeIT Ryan,
How are you?
I think that your post, when converted to markdown, stripped down some characters, can you please review the reg ex you shared here so I can exactly understand and try to reproduce to see if we need to adjust documentation? Thanks

**Comment by RyanBlakeIT** [comment]
Hi @get-itips - I have edited my original comment and made sure that the code tag was set for the REGEX.

**Comment by get-itips** [comment]
Edit was not approved. Closing.
