### ISSUE TITLE
Typo in release date for the Semi-Annual Enterprise Channel: Jan 2024, not 2023

### ISSUE THREAD

**Issue by BernEdel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10164]
The Semi-Annual Enterprise Channel should get it in January 202**4**, not 2023 (typo)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Version Independent ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Content: [The new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin)
* Content Source: [Teams/new-teams-desktop-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-desktop-admin.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello, thanks for your feedback
