### ISSUE TITLE
Voicemail Group(s) option

### ISSUE THREAD

**Issue by Korbyn72** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10172]
Can we get the Voicemail / Voicemail (Shared) options for Auto Attendant and for Call Queues updated to it included Distribution Groups?  Its not just M365 Groups, Distribution Groups also work and have been for more than 2 years since I've noticed.

In the TAC Instead of just "Search for a Microsoft 365 Group" it should be "Search for a Microsoft 365 Group, Distribution Group or Mail Enabled Security Group".  Security groups, or basically non-mail-enabled groups are all that do not work.

Korbyn

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba71bea5-f386-7dcd-0c24-053f9ed0f4f1
* Version Independent ID: ba71bea5-f386-7dcd-0c24-053f9ed0f4f1
* Content: [Plan your call routing flow for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/plan-your-call-routing-flow)
* Content Source: [Teams/plan-your-call-routing-flow.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/plan-your-call-routing-flow.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Korbyn72** [comment]
There’s nothing to resolve.  I, and many many customers love the fact we can use DG’s and mail-enabled Security Groups instead of M365 groups.  I’m suggesting that the web page documenting Voicemail Shared and the Teams Admin Console be updated to reflect this.

**Comment by Venkat-Munta** [comment]
I have tested this. and it seems we can add Distribution list and mail-enabled security groups under voicemail option.
@get-itips can you please look into this and confirm the same?

**Comment by BrianMcNeese** [comment]
Can we get an ETA when this doc will be updated? Many of our customers need to see our public docs to ensure confidence in supportability.

**Comment by get-itips** [comment]
Hello I am looking into this
