### ISSUE TITLE
Unable to update Microsoft Modern USB-C Speaker

### ISSUE THREAD

**Issue by jmw1480** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10177]
macOS 13.4.1 (latest) and Microsoft Accessory Updater app (version 1.2.2) - app recognizes the connected device and shows serial number and ver (1.48-1.23-1.9) - also says "new version available" with "bug fixes."  However, when I click 'Update,' it says "Couldn't update device[.] Keep this app open and try again later."  I've been trying for over a week!

Believe it's an app issue - see https://apps.apple.com/us/app/microsoft-accessory-updater/id1599783787

<img width="1026" alt="Screenshot 2023-07-10 at 4 54 12 PM" src="https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/120040383/2035e791-760d-43bf-8161-0f70a7c2db35">

**Comment by jmw1480** [comment]
Background: at some point very recently the volume on my speaker has been limited/reduced/become muffled.  At max volume it sounds as if it's at 10-15%.  However, the speaker works fine on other computers, so I assume there's a conflict with some other update (Windows 10, Teams, some other driver or software).  But, I was trying to start by updating the speaker driver before chasing down other possibilities.

**Comment by jmw1480** [comment]
My next attempt will be to uninstall/reinstall the drivers (Intel SST for USB audio and Modern USB-C speaker), but since my Windows 10 device - where I primarily use the speaker - is enterprise, I cannot access the Microsoft Store (to use the Microsoft Accessory Center) to do the update; and will need admin privileges to remove/reinstall the drivers... i.e. an IT help ticket.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
