### ISSUE TITLE
Wrong Date in Aritcel New Teams (Section semi annual default client)

### ISSUE THREAD

**Issue by PhilvdHeide** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10176]
There is a wrong date listed in the articel. 
Section "When will the new Teams become the default client?" ([LINK](https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin#when-will-the-new-teams-become-the-default-client)) > Semi-Annual Enterprise Channel > Mid Jan 2023.
This should be 2024 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Version Independent ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Content: [The new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin#new-teams-rollout-schedule)
* Content Source: [Teams/new-teams-desktop-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-desktop-admin.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by PhilvdHeide** [comment]
ah sorry overseeing it;  identical with #10165

**Comment by get-itips** [comment]
Hello, thanks for your feedback
