### ISSUE TITLE
Porting "Out"

### ISSUE THREAD

**Issue by scapero** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10174]
[Enter feedback here]
Some may have the expectation that Microsoft is able to move ported numbers out to other providers. We believe the correct answer is that a "port in" request would need to be filed with the other provider - that no provider pushes out numbers to other providers.
It would be helpful if this article made some mention of the process of porting numbers already ported to Microsoft.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ca4cd82c-d4e0-fd46-a9d6-19c46e217b7a
* Version Independent ID: d4a536ae-1f0d-fab5-4617-a414b829374a
* Content: [Manually submit a port order - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/phone-number-calling-plans/manually-submit-port-order)
* Content Source: [Teams/phone-number-calling-plans/manually-submit-port-order.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/phone-number-calling-plans/manually-submit-port-order.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello, @scapero how are you? that's answered here 

https://learn.microsoft.com/en-us/MicrosoftTeams/phone-number-calling-plans/port-order-overview#can-i-port-out-my-numbers-from-teams-to-a-different-phone-service-provider-or-carrier
