### ISSUE TITLE
Dead Links

### ISSUE THREAD

**Issue by mikeconjoice** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1017]
Links from Step 2 ("#who-can-create-and-schedule-live-events" and "#who-can-watch-live-events") don't go anywhere

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9aa4676-855a-fddb-bb0b-96b7095c695e
* Version Independent ID: 7c39f08c-0d56-6d29-1356-879d9d6ff51c
* Content: [Set up for live events in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/set-up-for-teams-live-events#step-2-get-and-assign-licenses)
* Content Source: [Teams/teams-live-events/set-up-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/set-up-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @tonysmith
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@mikeconjoice Thank you for pointing this out

I will get this information about these links not working to our Teams team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by CrystalThomasMS** [comment]
These links have been fixed. Thanks for alerting us to this! 
https://docs.microsoft.com/en-us/MicrosoftTeams/teams-live-events/set-up-for-teams-live-events
