### ISSUE TITLE
Set up Virtual Front Desk on Teams displays

### ISSUE THREAD

**Issue by yuki-iwagishi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10171]
Teams Displays introduced new feature Virtual Front Desk on 1449/1.0.95.2023042701. However, learn.microsoft.com doc hasn't covered how to enable it. Please add "Set up Virtual Front Desk on Teams displays" topics on the following sections.

[Set up hot-desking on Teams displays](https://learn.microsoft.com/en-us/microsoftteams/devices/teams-displays#set-up-hot-desking-on-teams-displays)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 006adec0-78ea-ed8c-07c0-ecf811ef023c
* Version Independent ID: d7c830df-9964-c066-8686-8f9e359f5e96
* Content: [Microsoft Teams displays - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/devices/teams-displays)
* Content Source: [Teams/devices/teams-displays.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/devices/teams-displays.md)
* Service: **msteams**
* Sub-service: **itpro-devices**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by get-itips** [comment]
Thanks for your feedback
