### ISSUE TITLE
Customize Praise badges in Teams App version 1.2.6

### ISSUE THREAD

**Issue by hlager** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10178]
Hello, 
There are several third party documentations about how to customize the badges within the Praise app. Unfortunately we cant find this option for the version 1.2.6 in the Teams Admin center.

App settings
**There isn't any setting information that is available for this app.**

https://www.youtube.com/watch?v=mWPqwkDxZZo

Thanks and best regards
Hendrik

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2033a3-a651-78f3-90c2-ad582e182731
* Version Independent ID: 057e7da2-4e65-7f8d-5843-b15d92ffff02
* Content: [Manage the Praise app in the Teams admin center - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-praise-app?WT.mc_id=M365-MVP-4038268)
* Content Source: [Teams/manage-praise-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/manage-praise-app.md)
* Service: **msteams**
* GitHub Login: @samanro
* Microsoft Alias: **samanro**

**Comment by get-itips** [comment]
Hello @hlager 
There was a note in past versions of this article that warned about that

_Starting February 2022, people can only send and receive default badges. Custom badges are no longer available and options for custom badges have been removed from the Teams admin center._

Hope this information helps you,
