### ISSUE TITLE
Allow endpoints list includes dangerous wildcards

### ISSUE THREAD

**Issue by dsample** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10175]
In the Allow Endpoints section of the Avatar page there is this list:

  * `*.microsoft.com`
  *  `*office.com`
  * `*office.net`

First first in the list is reasonable as it's all subdomains under `microsoft.com` but the other two are suggesting allowing all domains which have the suffix `office.com/net`, which would presumably include non-Microsoft domains like `fakeoffice.com`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 122d9ead-09d3-f605-1bfb-6ae0fce81636
* Version Independent ID: 122d9ead-09d3-f605-1bfb-6ae0fce81636
* Content: [Set up avatars for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/meeting-avatars#allow-endpoints)
* Content Source: [Teams/meeting-avatars.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/meeting-avatars.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback!
