### ISSUE TITLE
Hard to give feedback

### ISSUE THREAD

**Issue by GOSSAMER2000** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10170]
Hi,

I'm having some issues with the new version of teams,

it's taken me more than 10 minutes to find a feedback button, 

and when I finally do, i have to create a github account to give feedback???

My feedback:

1. Put more buttons to give feedback. You have issues that you need to be told about
2. Don't make people create accounts for 3rd party paltforms when we already have accounts for your platform.

Now I need to go to another link to give feedback on the actual issues I had with MS Teams. 
What a waste of time.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Version Independent ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Content: [Rollout schedule for the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-known-issues)
* Content Source: [Teams/new-teams-known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-known-issues.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
