### ISSUE TITLE
Teams Room Custom Backgrounds

### ISSUE THREAD

**Issue by jblasongame** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10173]
I tried this multiple times. It seems this is not working in the XML file. Am I doing something wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 104c1570-b5b0-fe02-0d8c-c3d31518e8d7
* Version Independent ID: 104c1570-b5b0-fe02-0d8c-c3d31518e8d7
* Content: [Set up and manage Teams Rooms on Windows custom backgrounds - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/custom-backgrounds?tabs=Enhanced&source=docs)
* Content Source: [Teams/rooms/custom-backgrounds.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/rooms/custom-backgrounds.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
