### ISSUE TITLE
Could you please be more specific in this documentation for co-organizer role

### ISSUE THREAD

**Issue by eugenianegut** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10179]
[Enter feedback here]
Hi,
This documentation is ambiguous, it says that for large meetings (I understand by large meetings also Live Events) : "Define a co-organizer via meeting options (Public preview)" but, while testing this is not possible in Live Events.
In Roadmap I do not see this feature for live events.
Could you please be more specific in this documentation for co-organizer role?
Thank you!
Eugenia

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 92fcb1f6-5cc2-f6bd-cfa9-11d811f1dbf1
* Version Independent ID: 9a571e6d-8cb3-9ff8-a5c2-62deab146264
* Content: [Meetings, webinars, and live events - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/quick-start-meetings-live-events#live-events)
* Content Source: [Teams/quick-start-meetings-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/quick-start-meetings-live-events.md)
* Service: **msteams**
* Sub-service: **meetings**
* GitHub Login: @wlibebe
* Microsoft Alias: **wlibebe**

**Comment by get-itips** [comment]
Hello @eugenianegut 

Large Meetings here are considered regular meetings with more than 300 attendees, if you follow the link in this article https://support.microsoft.com/en-us/office/best-practices-for-a-large-meeting-in-microsoft-teams-ce2cdb9a-0546-43a4-bb55-34ab98ab6b16

> A good estimate for a large Teams meeting is 300 or more attendees. 

and

> For the best experience attending large meetings, webinars, and live events

Hope this information helps you,

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
