### ISSUE TITLE
Lack of visibility regarding the limitation of the Application-based authentication

### ISSUE THREAD

**Issue by vlethiec** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10188]
Hello, 

Do you know when the limitation below will be lifted?

"All cmdlets are supported now, except for the cmdlets mentioned below.

[Get|Set|New|Sync]-CsOnlineApplicationInstance
*-CsUserCallingSettings
*-CsUserCallingDelegate"

Thanks in advance for your feedback. 

Regards,

Vincent

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32304edf-550b-72a3-57df-6dcc29dba56d
* Version Independent ID: 32304edf-550b-72a3-57df-6dcc29dba56d
* Content: [Application-based authentication in Teams PowerShell Module - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/teams-powershell-application-authentication)
* Content Source: [Teams/teams-powershell-application-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/teams-powershell-application-authentication.md)
* Service: **msteams**
* GitHub Login: @pbafna03
* Microsoft Alias: **pbafna**

**Comment by vlethiec** [comment]
Hi, 

Any news on that topic?
Thanks in advance. 

Regards, 

Vincent

**Comment by scanum** [comment]
@tiburd 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
