### ISSUE TITLE
Powershell references

### ISSUE THREAD

**Issue by NCSTman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1018]
Hi, Would like to confirm if there's a technique available to add a domain to the list of allowed domains via Power Shell. I'm looking myself but haven't found anything concrete and this article would benefit from that knowledge as well. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee122b1c-c1c6-bb32-38db-a7f7c52c1f28
* Version Independent ID: 1f335848-baeb-9396-f753-8f72017447ce
* Content: [Allow users to contact external Skype for Business users](https://docs.microsoft.com/en-us/skypeforbusiness/set-up-skype-for-business-online/allow-users-to-contact-external-skype-for-business-users)
* Content Source: [Skype/SfbOnline/set-up-skype-for-business-online/allow-users-to-contact-external-skype-for-business-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-skype-for-business-online/allow-users-to-contact-external-skype-for-business-users.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@NCSTman Thank you for this inquiry

I am not sure if there is a Power Shell way to add a domain to your list. Let me get this over to the Skype for Business team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by LolaJacobsen** [comment]
Check out the Skype for Business PowerShell reference: https://docs.microsoft.com/en-us/powershell/module/skype/?view=skype-ps
