### ISSUE TITLE
Incorrect PowerShell command

### ISSUE THREAD

**Issue by docpauluk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10187]
on the page https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-operations, under the section named "Remote Management using PowerShell", the PowerShell command text for "To Get Attached Devices" should read "Camera" and not "Image", as the PNPClass "Image" is not correct. - see below:

invoke-command {Write-Host "VIDEO DEVICES:" 
gwmi -Class Win32_PnPEntity | where {$_.PNPClass -eq "Camera"} | Format-Table Name,Status,Present; Write-Host "AUDIO DEVICES:" 
gwmi -Class Win32_PnPEntity | where {$_.PNPClass -eq "Media"} | Format-Table Name,Status,Present; Write-Host "DISPLAY DEVICES:" 
gwmi -Class Win32_PnPEntity | where {$_.PNPClass -eq "Monitor"} | Format-Table Name,Status,Present} -ComputerName <Device fqdn>

Hope that helps...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd52fe62-457b-c9e1-ad13-a9b1f24c9c38
* Version Independent ID: 6a8c3285-30e1-15a8-6472-f0cfe5b30e20
* Content: [Microsoft Teams Rooms maintenance and operations - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-operations)
* Content Source: [Teams/rooms/rooms-operations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/rooms/rooms-operations.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by get-itips** [comment]
Hello @docpauluk how are you?

I was able to query filtering both by PNPClass "Image" and "Camera"

**Comment by docpauluk** [comment]
Hi Andres,

Thanks for the feedback - whilst "Image" is a valid query, it won't return
any video devices.

With Camera, we see the cameras listed:
[image: image.png]

With Image - no cameras listed for the same Teams Room:

[image: image.png]

I guess for completeness you could add an OR in there so it returned both
Image and Camera devices...
and optionally move from Get-WMIObject to Get-CIMInstance (gcim).

I hope that helps.

Paul Hargrove

**Comment by get-itips** [comment]
Hello @docpauluk 
Your images weren't attached to your message, can you check so I can compare and investigate further?
Thanks

**Comment by docpauluk** [comment]
Sorry about that, I've added the images to the post.

**Comment by get-itips** [comment]
Thanks.
While something that could be valid for your MTR device maybe can't be valid for another and unfortunately I don't have a way to test every device. I'll try to confirm if we can change the current filters.
Thank you

**Comment by docpauluk** [comment]
Ok, thanks.

According to Microsoft docs, PnPClass Image is for still image devices such
as digital cameras and scanners, whilst PnP Class Camera is for universal
Camera drivers.
Also, Teams Rooms need Windows 21H2 or later so cameras should be using the
Class Camera.

References:
https://learn.microsoft.com/en-us/windows-hardware/drivers/install/system-defined-device-setup-classes-available-to-vendors
https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-lifecycle-support

For some background context, I manage over 500 Teams Rooms from different
vendors and I've never seen one that returns anything using the PnP Class
Image.

Paul Hargrove
