### ISSUE TITLE
Error when using @mention at people in the owner organization as external contractor

### ISSUE THREAD

**Issue by kawslab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10189]
When invited to a Shared Channel in another tenant, the host tenant users can tag me in chats, mentions, and comments. When I try to mention them back (comment in Lists) I'm getting the error in the attached image

![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/48711748/49b24d75-97aa-459f-8a2c-2626f41d0fac)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 138ac890-8786-c6e6-db7e-1e90a94e6c9b
* Version Independent ID: 138ac890-8786-c6e6-db7e-1e90a94e6c9b
* Content: [Shared channels errors in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/shared-channels-errors)
* Content Source: [Teams/shared-channels-errors.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/shared-channels-errors.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
