### ISSUE TITLE
Need a clear date for when Microsoft will increase the Live Events attendees limit to 20K

### ISSUE THREAD

**Issue by eugenianegut** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10193]
[Enter feedback here]
Hi, we need a clear date for when Microsoft will increase the Live Events attendees limit to 20K. In this article is "through dec 31 2023" but in other articles is June 30 2023 (https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
Here is dec 2023 also https://adoption.microsoft.com/en-us/virtual-event-guidance/assistance/
Please align this documentation and put the correct date, we cannot afford inviting 20K users and see that the event is working only for half of them.
and what does this "through" mean? starting when?
Thank you
Eugenia Negut
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@eugenianegut it should be December 31, 2023. I submitted an update to the limits article. The increased limit is in effect now has been available for some time.
