### ISSUE TITLE
Walkie Talkie app does not exist.

### ISSUE THREAD

**Issue by jpeterson540** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10198]
I have found many references to this app.  It is not available when you search in the admin console or from teams itself.  About 80% of Teams tutorials and information does not work.  Really poor.  I want to switch to Teams phones, but you are missing so many basic features.  You need someone with logic working there.  
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d91ddefc-3722-8bc2-bd9b-4a90ede28944
* Version Independent ID: 35e56a9d-a01c-4126-3750-aae1ed984f55
* Content: [Walkie Talkie app in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/walkie-talkie#deploying-walkie-talkie)
* Content Source: [Teams/walkie-talkie.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/walkie-talkie.md)
* Service: **msteams**
* GitHub Login: @samanro
* Microsoft Alias: **samanro**

**Comment by samanro** [comment]
Hi @jpeterson540 - I'm sorry to hear that you are frustrated with this documentation and Walkie Talkie. Some reasons you might not be able to find the app in Teams itself: it must be configured from the Teams Admin Center, and is only available on Android or iOS, not Desktop. There are also policies that control whether the app is available to users. I hope this helps.

**Comment by jpeterson540** [comment]
Nope.   It is not in the teams admin center under manage apps.  We are Microsoft Business 365 Standard.  Running a Teams phone trial and  you forgot to consider a lot of basic things for phone systems.  Really poor.

Many Thanks,

JP
John Peterson AIA

DALGLIESH GILPIN PAXTON ARCHITECTS
206 Fifth Street NE
Charlottesville Virginia 22902
434 977 4480
dgparchitects.com

CHARLOTTESVILLE  BALTIMORE  URBANA

**Comment by samanro** [comment]
It looks like you are not the only one having trouble with the mobile Walkie Talkie app on Business Standard. Here's a Q&A thread - you can add your info here to see if there's an update or solution: https://learn.microsoft.com/en-us/answers/questions/765722/walkie-talkie-feature-cant-be-added-to-ms-teams

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by jpeterson540** [comment]
Did you read that article?  It provides no information, nor do the documents it links to.

Many Thanks,

JP
John Peterson AIA

DALGLIESH GILPIN PAXTON ARCHITECTS
206 Fifth Street NE
Charlottesville Virginia 22902
434 977 4480
dgparchitects.com

CHARLOTTESVILLE  BALTIMORE  URBANA

**Comment by jpeterson540** [comment]
It was not resolved at all.  I was sent a different thread to read that had no information whatsoever about the issue.  I've come across a lot that doesn't work lately in tutorials and articles published by Microsoft.  I think you need help in quality control.  Also Teams phone just isn't cutting it.  Basic things any phone system needs is the ability to page someone, or everyone, and a decent screen to handle and transfer calls.  The person logged into the queue cannot see how many other calls are in the queue, they can't see which calls they have parked while they try to reach a Team member to see if they want to take a call.  Yes we have a real person that talks to callers and transfers calls to us after confirming we are able to speak at that time.  We are not always at our desks with the phone within reach.  Sometimes we are at another work area in our space, or conferring with a colleague.   Yes I realize things are changing and you think everyone always has there cell phone in their pocket.  They don't.

Many Thanks,

JP
John Peterson AIA

DALGLIESH GILPIN PAXTON ARCHITECTS
206 Fifth Street NE
Charlottesville Virginia 22902
434 977 4480
dgparchitects.com

CHARLOTTESVILLE  BALTIMORE  URBANA
