### ISSUE TITLE
NCE Tenants

### ISSUE THREAD

**Issue by cristinitu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10196]
As per the note "The Microsoft Teams Exploratory experience isn't currently available to tenants on the New Customer Experience (NCE). The Teams Exploratory license will become available to NCE tenants in late June 2023." which means that TE is not available on (almost all) new trial tenants. 
Is there any update about this?

**Comment by scanum** [comment]
Hi @cristinitu 
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
