### ISSUE TITLE
Set-Drive Error while formatting USB Drive

### ISSUE THREAD

**Issue by grahambird80** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1019]
I have tried to run this script a few times now with different USB drives and get the following error each time;

Formatting and partitioning the target drive... Set-Disk : Not Supported
Activity ID: {ca2f214f-f76a-4fc7-8e63-22fab8bc8e32}
At C:\Temp\CreateSrsMedia.ps1:1250 char:9
+         Set-Disk -PartitionStyle MBR
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (StorageWMI:ROOT/Microsoft/..._StorageCmdlets) [Set-Disk], CimExceptio
   n
    + FullyQualifiedErrorId : StorageWMI 1,Set-Disk

Transcript stopped, output file is C:\Users\gbird\Documents\PowerShell_transcript.UABZLTCZ0LNH2.R9MvjGKm.20181105222658.txt
New-Partition : The disk has not been initialized.
Activity ID: {f8d6a778-6b18-4719-be43-e7a2d905f4b2}
At C:\Temp\CreateSrsMedia.ps1:1259 char:17
+ ...     $part = New-Partition -DiskNumber $TargetDisk.DiskNumber -UseMaxi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (StorageWMI:ROOT/Microsoft/Windows/Storage/MSFT_Disk) [New-Partition], Cim
   Exception
    + FullyQualifiedErrorId : StorageWMI 41000,New-Partition

Has anyone else experienced this issues?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51d42140-9f7b-a6f3-7a3e-76cc7331cf22
* Version Independent ID: a7dacc56-c2df-55fb-76a3-ecb194564fae
* Content: [Configure a Skype Room Systems v2 console](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/console)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/console.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by grahambird80** [comment]
I have fixed this error by adjusting line 1249 - 1250 of the script from;

Clear-Disk -Number $TargetDisk.DiskNumber -RemoveData -RemoveOEM -Confirm:$false -PassThru |
        Set-Disk -PartitionStyle MBR

To

Clear-Disk -Number $TargetDisk.DiskNumber -RemoveData -RemoveOEM -Confirm:$false -PassThru |
        Initialize-Disk -PartitionStyle MBR

As the disk was not Initalized after being Cleared the Set command would not work

**Comment by Travis-Snoozy** [comment]
If you could, please post the transcript of the original failure ("C:\Users\gbird\Documents\PowerShell_transcript.UABZLTCZ0LNH2.R9MvjGKm.20181105222658.txt").

**Comment by grahambird80** [comment]
Here you go

**********************
Windows PowerShell transcript start
Start time: 20181105222658
Username: DOMAIN\gbird
RunAs User: DOMAIN\gbird
Configuration Name: 
Machine: UABZLTCZ0LNH2 (Microsoft Windows NT 10.0.17134.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Process ID: 17020
PSVersion: 5.1.17134.228
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17134.228
BuildVersion: 10.0.17134.228
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\gbird\OneDrive\Documents\PowerShell_transcript.UABZLTCZ0LNH2.R9MvjGKm.20181105222658.txt
Script version 1.4.1
Downloading CreateSrsMedia...
done
Validating signature for update.ps1...
success.

What type of customer are you?
Please make sure you have all of the following available:

1. A USB drive with sufficient space (16GB+).
   The contents of this drive WILL BE LOST!
2. Windows 10 Enterprise media that matches your SRSv2 deployment kit.
   Enterprise customers can access Windows 10 Enterprise media from the Volume Licensing Service Center:
   http://www.microsoft.com/licensing/servicecenter
3. Any language pack (LP and/or LIP) files to be included.
   MPSA customers:         http://go.microsoft.com/fwlink/?LinkId=125893
   Other volume licensees: http://www.microsoft.com/licensing/servicecenter

Please do not continue until you have all these items in order.

Found deployment kit already downloaded.
Validating signature for SRSDeploymentKit-4.0.27.0.msi...
success.
Extracting the deployment kit...
done.
This deployment kit is built for Windows build 10.0.17134.1.
This deployment kit draws its drivers from %configsetroot%\AutoUnattend_Files\DistShare\Out-of-Box Drivers.

Please indicate what drivers you wish to use with this installation.
[ 0] Logitech SmartDock
[ 1] Crestron SR
[ 2] Polycom MSR
[ 3] Lenovo Hub 500
[ 4] LRS
[ 5] None
Selected option 0.
[ 0] Surface Pro 4
[ 1] Surface Pro (2017)
Selected option 1.
Found driver already downloaded.
Validating signature for SurfacePro_WIFI_Win10_16299_1802107_6.msi...
success.
Extracting SurfacePro_WIFI_Win10_16299_1802107_6.msi...
done.
Identifying language packs...
... done identifying language packs.
Found update KB4340917 already downloaded.
Validating signature for windows10.0-kb4340917-x64_ed5f586fa9d7064d61e45c523f20ba7fc1ff142a.msu...
success.
WARNING: THIS IS YOUR ONLY CHANCE TO PRE-INSTALL LANGUAGE PACKS.
Because you are pre-installing an update, you will NOT be able to pre-install language packs to the image at a later point.
You are currently building an image with NO pre-installed language packs.
Are you ABSOLUTELY SURE this is what you intended?
WARNING: PROCEEDING TO GENERATE SLIPSTREAM IMAGE WITH NO PRE-INSTALLED LANGUAGE PACKS.

Reminder: all data on the drive you select will be lost!

[ 0] SanDisk Cruzer Edge
Selected option 0.

Creating Enterprise media.

Creating UEFI-compatible media.

Using SRSv2 kit:       C:\Temp\SRSDeploymentKit-4.0.27.0.msi
Using driver pack:     C:\Temp\SurfacePro_WIFI_Win10_16299_1802107_6.msi
Using Windows media:   D:\
Using language packs:
Using updates:
    C:\Temp\windows10.0-kb4340917-x64_ed5f586fa9d7064d61e45c523f20ba7fc1ff142a.msu
Writing stick:         SanDisk Cruzer Edge

Formatting and partitioning the target drive...
Set-Disk : Not Supported
Activity ID: {ca2f214f-f76a-4fc7-8e63-22fab8bc8e32}
At C:\Temp\CreateSrsMedia.ps1:1250 char:9
+         Set-Disk -PartitionStyle MBR
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (StorageWMI:ROOT/Microsoft/..._StorageCmdlets) [Set-Disk], CimException
    + FullyQualifiedErrorId : StorageWMI 1,Set-Disk
Set-Disk : Not Supported
Activity ID: {ca2f214f-f76a-4fc7-8e63-22fab8bc8e32}
At C:\Temp\CreateSrsMedia.ps1:1250 char:9
+         Set-Disk -PartitionStyle MBR
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (StorageWMI:ROOT/Microsoft/..._StorageCmdlets) [Set-Disk], CimExceptio
   n
    + FullyQualifiedErrorId : StorageWMI 1,Set-Disk

PS>TerminatingError(New-Partition): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The disk has not been initialized.
Activity ID: {e5c5b469-0258-4a05-9693-a8d770a6318a}"
PS>TerminatingError(New-Partition): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The disk has not been initialized.
Activity ID: {f8d6a778-6b18-4719-be43-e7a2d905f4b2}"
**********************
Windows PowerShell transcript end
End time: 20181105223012
**********************

**Comment by AndreaBarr** [comment]
@Travis-Snoozy Do you have an update for this issue?

**Comment by rafaelfozzy** [comment]
Hi! 
I have a problem with the creation of the media. 
I cannot run the script.
I'm using a Surface Pro 4.

Can you help me?

**Comment by Travis-Snoozy** [comment]
@AndreaBarr -- negative, I was never able to repro the issue. My development branch has a change it it that might by pure happenstance resolve the problem, but given I can't induce the described behavior to begin with, I can't actually verify it.

**Comment by kenwith** [comment]
I think it would be best to open a support ticket on this one. It sounds like @Travis-Snoozy on the devices team might have noticed it is already resolved. Support engineers would be able to walk through if it is resolved and if not why it is not resolved on a particular system. Going to go ahead and close this out but please re-open if there is something in the docs that we can fix. Here is the link for link to open support for your tenant: https://docs.microsoft.com/office365/admin/contact-support-for-business-products

**Comment by StoiaCode** [comment]
Sorry for defiling this old thread but I had this issue just now as well. 
I ended up deleting the volume from the USB stick and THEN running the tool. That worked out. I have no idea why or what happend.

**Comment by Travis-Snoozy** [comment]
Please always include the corresponding transcript when requesting help. Reviewing the script, it already clears all partitions and re-initializes the target device.

```
     # Partition & format
    Write-Host "Formatting and partitioning the target drive... " -NoNewline
    Get-Disk $TargetDisk.DiskNumber | Initialize-Disk -PartitionStyle MBR -ErrorAction SilentlyContinue
    Clear-Disk -Number $TargetDisk.DiskNumber -RemoveData -RemoveOEM -Confirm:$false
    Get-Disk $TargetDisk.DiskNumber | Initialize-Disk -PartitionStyle MBR -ErrorAction SilentlyContinue
    Get-Disk $TargetDisk.DiskNumber | Set-Disk -PartitionStyle MBR
```
