### ISSUE TITLE
Supported OS

### ISSUE THREAD

**Issue by mtgriger** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#102]
Is it possible install Teams over MSI to server OS? On Windows 2008 R2 installer ended with error.

MSI (c) (C0:D4) [09:36:55:471]: Note: 1: 1728 
MSI (c) (C0:D4) [09:36:55:471]: Note: 1: 2205 2:  3: Error 
MSI (c) (C0:D4) [09:36:55:471]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1728 
MSI (c) (C0:D4) [09:36:55:471]: Note: 1: 2205 2:  3: Error 
MSI (c) (C0:D4) [09:36:55:471]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (c) (C0:D4) [09:36:55:471]: Product: Teams Machine-Wide Installer -- Configuration completed successfully.

**Comment by tonysmit** [comment]
Hi. Thanks for the feedback. I'm investigating this and trying to find a PM that I can assign this issue. Thanks, Tony

**Comment by tonysmit** [comment]
I've assigned two PMs from the product group to lend you a hand. We appreciate the feedback. If there are addition/corrections/suggestions to the docs, please edit the topic by clicking Edit (on the right side of the topic) or use VsCode/GtiHub desktop. Let me know how I can help further.

**Comment by tonysmit** [comment]
@juturu - Should we update this topic with a note? https://docs.microsoft.com/en-us/MicrosoftTeams/get-clients

**Comment by kenwith** [comment]
@mtgriger - I have added a User Voice item to get this voted up. I would love to have my Teams on my server OSs too. Please up vote: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/34795573-support-microsoft-teams-client-on-windows-server
