### ISSUE TITLE
Direct Routing SBA - Edit request to add a note on ETA for the new token lifetime (known issues section)

### ISSUE THREAD

**Issue by ajeob** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10203]
Hello,

As reference to the following known issue about the SBA related token 24 hours lifetime that limit the Teams users survivability from 1h to 24 hours (too restrictive for many customers who want to buy the solution but can't accept it as few hours of survivability is not enough to get the time to fix the issue, for many locations).

My request, if possible: Microsoft confirmed last year the development starting on Q1-2023 to extend the token lifetime from 24hours to at least 72hours (up to a week). Can you please sync with the product team to add the estimated time of delivery to the related note in the "Known issues" section:

**Known issues**

- As SBA relies on authentication tokens that are valid for 24 hours and are renewed daily, presently SBA can support outages for up to 24 hours from the last authentication. This means that if an outage occurs 20 hours after the last authentication token renewal, SBA will be operational only for the remaining 4 hours.

Thank you,
Best regards,
Anthony.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 183fc921-e9b1-cc74-2bcb-26d32b994919
* Version Independent ID: 1765bda3-dd62-76d7-1e2d-9f5496ac9094
* Content: [Direct Routing SBA - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/direct-routing-survivable-branch-appliance)
* Content Source: [Teams/direct-routing-survivable-branch-appliance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/direct-routing-survivable-branch-appliance.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @ajeob 

Can you please point me into this announcement?

> Microsoft confirmed last year the development starting on Q1-2023

So I can start digging into this. Thank you

**Comment by CarolynRowe** [comment]
Adding @FilippSe

**Comment by ajeob** [comment]
Hello @get-itips,

> Hello @ajeob
> 
> Can you please point me into this announcement?
> 
> > Microsoft confirmed last year the development starting on Q1-2023
> 
> So I can start digging into this. Thank you

Here is the answer we had from Filipp Seljanko:
![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/126698102/c2458e66-22fe-48b9-8a3f-3a882c3ffd30)

Thank you for you support,
regards.

**Comment by CarolynRowe** [comment]
Hello @get-itips, @ajeob, @FilippSe:  GitHub issues should be about content issues--it is not the forum to discuss development dates.  @ajeob: Please follow your normal technical support channels.  Thank you.

**Comment by ajeob** [comment]
Hello,
Sorry, I thought it would be possible to add the planning information on the documentation as there is an impact for customers. 

The Direct Routing SBA can help them on sites where the WAN/Internet connectivity is not reliable (for example in south America), but they can't accept having only few hours of survivability. So the Microsoft DR-SBA product can't be sold.

We'll see if we can try again with normal technical support channel.

Thank you,
best regards.

**Comment by get-itips** [comment]
Closing.
