### ISSUE TITLE
Error in Script 

### ISSUE THREAD

**Issue by grahambird80** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1020]
On line 334 there is a 1 at the end of the line that is causing the script to fail

 $strDisplayName = Read-Host -Prompt "Please enter the display name you would like to use for $strUpn"1

I have run the script without the 1 and it proceeds past that point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d495057-36be-b228-0483-aae89fd01666
* Version Independent ID: f02fa875-b84b-5501-5879-17ea3d017142
* Content: [Configure accounts for Skype Room Systems v2](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/room-systems-v2-configure-accounts)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/room-systems-v2-configure-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/room-systems-v2-configure-accounts.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Hi Graham, are you a Microsoft employee?

**Comment by grahambird80** [comment]
Hello Jambirk, 

No I work for an Oil and Gas company and I am in charge of the deployment of SRS to our meeting rooms to simplify our existing meeting room experance.

**Comment by AndreaBarr** [comment]
@grahambird80 Thank you for pointing this out to us. 

I will get this script error over to the Skype for Business team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by scanum** [comment]
@jambirk Any updates on this? Thanks!

**Comment by jambirk** [comment]
@davgroom @Travis-Snoozy @gregbari This seems like a very minimal but needed correction to the posted script. Can we get this change made alongside the next MSI update?

**Comment by scanum** [comment]
@davgroom @Travis-Snoozy @gregbari any updates on this issue? Thanks!

**Comment by jwinte** [comment]
Still not updated. I had to troubleshoot line 334 myself and got it working as grahambird80 specified before. You should post the script on github at the least so it can be branched.

**Comment by jambirk** [comment]
The correction was made the other day to the master version of the script. The script is not going to be posted to GH any time soon. The available link is to download center, and the script will be updated the next time there is an MSI update on download center.

**Comment by scanum** [comment]
@jwinte @grahambird80 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
