### ISSUE TITLE
Hyperlinks broken

### ISSUE THREAD

**Issue by kumaarrahul** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10206]
[Enter feedback here]

The 2 hyperlinks under heading Direct Routing are broken/points to a resource which is no longer available.

Link Headings:

Plan for success with Microsoft Teams Direct Routing

Updates for Direct Routing

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41435e57-1d6a-7094-9d5a-15c5517b45b6
* Version Independent ID: d20c6512-b2d2-f790-e18a-a8e5c93a037b
* Content: [Contoso case study: Phone System for a multi-national corporation - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/voice-case-study-phone-system#site-type-b-traditional-legacy-telephony-systems)
* Content Source: [Teams/voice-case-study-phone-system.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/voice-case-study-phone-system.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Thanks for your feedback!
