### ISSUE TITLE
Need link to end user documentation for intelligent recap

### ISSUE THREAD

**Issue by dipinn26592** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10207]
We do not have any mention of intelligent recap as feature, we should have link to end user docs called out here. : https://support.microsoft.com/en-gb/office/meeting-recap-in-microsoft-teams-c2e3a0fe-504f-4b2c-bf85-504938f110ef 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a5338e6-ae08-bb92-3769-4af2932bf02c
* Version Independent ID: 7a5338e6-ae08-bb92-3769-4af2932bf02c
* Content: [Microsoft Teams Premium - Overview for administrators - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/enhanced-teams-experience)
* Content Source: [Teams/enhanced-teams-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/enhanced-teams-experience.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hello @dipinn26592 
How are you?
This article is an overview for administrators, not for end users, so I'm not sure about linking to that other resource.
And a link to this comparison is already included https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/licensing-enhance-teams#meeting-recap-and-intelligent-recap and mentions intelligent recap.
Thanks for your feedback,
