### ISSUE TITLE
Update Documentation on Manage app permission policies

### ISSUE THREAD

**Issue by polaran** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10213]
Please update the following MS article:
https://learn.microsoft.com/en-us/microsoftteams/teams-app-permission-policies

It was recently confirmed by MS technical support team that needing to visit the App store on Teams client for the first time when any app is been added so that changes (added application/enabled applications) gets sync. As confirmed, this was by-design. Please add this as a note in the article to set the right expectations and guidance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b51eda6c-168c-7d99-7cc1-992b3d8feef2
* Version Independent ID: 118a1b8f-f4b7-a778-70b1-d3161fc548ab
* Content: [Manage app permission policies in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-app-permission-policies)
* Content Source: [Teams/teams-app-permission-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/teams-app-permission-policies.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by ashishguptaiitb** [comment]
Thanks @polaran for sharing this enhancement. It'd help if you can explain the scenario a bit more.

Where is the app added - by user in their client or by a dev to the app store? 
Also, what information is synchronized?

**Comment by ashishguptaiitb** [comment]
A gentle reminder @polaran to help us understand the required clarification.

Hi @tseward , could you decipher what the ask is?

**Comment by get-itips** [comment]
@polaran Can you please share more details? Thank you

**Comment by ashishguptaiitb** [comment]
Hi @polaran , I'm closing this issue for lack of inputs/clarity. Please do re-open when you share more details. Thanks.

CC @scanum , @get-itips
