### ISSUE TITLE
Doc date is wrong "12/19/2018"

### ISSUE THREAD

**Issue by Rajeshvadlamani** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1021]
Doc date is wrong "12/19/2018"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aea70bc6-2241-f153-33a4-8bebe509a09a
* Version Independent ID: 6a15940a-c0a0-3fa3-d818-fa7f4597ffcb
* Content: [Data API for Call Quality Dashboard (CQD) in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/call-quality-dashboard/data-api)
* Content Source: [Skype/SfbServer/management-tools/call-quality-dashboard/data-api.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/management-tools/call-quality-dashboard/data-api.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@AndreaBarr - for this one, and any others where date is wrong, you can remove the ms.date in the metadata at the top of doc and it will use the date the article was modified.

@Rajeshvadlamani - thanks for catch and reporting!

**Comment by AndreaBarr** [comment]
@Rajeshvadlamani This has been fixed. I am going to close this issue as resolved. If this issue is not resolved please re-open this issue.
