### ISSUE TITLE
Possible inaccurate license requirement for SIP devices

### ISSUE THREAD

**Issue by howardzhangmsft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10211]
This article states that Skype for Business Online (Plan 2) is a must.

**Hardware, software, and licenses**
If you have a 3PIP or SIP device, you must have the following:

[Microsoft Teams]
Skype for Business Online (Plan 2)
    Skype for Business Online (Plan 2) isn't a standalone license that can be purchased.
[Microsoft Phone System]
[PSTN Connectivity]

As I verified in my lab, a SIP phone (AudioCodes 405HD) which was granted M365 F3 + Teams phone standard license can register with SIP gateway without issues despite M365 F3 contains Skype for Business Online (Plan 1) 
Therefore, I believe it's not correct to state Skype for Business Online (Plan 2) is a must.

Please clarify, thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44863905-42d1-cd3f-0d97-af2570649e89
* Version Independent ID: 44863905-42d1-cd3f-0d97-af2570649e89
* Content: [Plan SIP Gateway - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/sip-gateway-plan)
* Content Source: [Teams/sip-gateway-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/sip-gateway-plan.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by howardzhangmsft** [comment]
Any update pls @scanum

**Comment by get-itips** [comment]
Hello @howardzhangmsft I'm working on this

**Comment by get-itips** [comment]
I checked internally, Skype for Business Online (Plan 2) **service plan** is still required.
Thanks
