### ISSUE TITLE
Supported Analog devices?

### ISSUE THREAD

**Issue by ryderi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10225]
[Enter feedback here]

Back in Ignite 2022 it was announcement supported for analog telephones beginning in early 2023.  I know it’s possible to register analog devices now via the SIP gateway (and have done so), but has it been formally entered support?  I can’t seem to find anything apart from the initial Ignite Annoucement made - https://techcommunity.microsoft.com/t5/microsoft-teams-blog/what-s-new-in-microsoft-teams-microsoft-ignite-2022/ba-p/3614158#phoneannouncements

I’m surprised no analog devices have made it onto the SIP Gateway compatible device pages - Is there a plan to update the documentation to included supported analog devices, or are you leaving this to the vendors to publish within their documentation.  Or have I missed the updated document?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44863905-42d1-cd3f-0d97-af2570649e89
* Version Independent ID: 44863905-42d1-cd3f-0d97-af2570649e89
* Content: [Plan SIP Gateway - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/sip-gateway-plan)
* Content Source: [Teams/sip-gateway-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/sip-gateway-plan.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by Chandranshu-Singh** [comment]
@ryderi

Analog device support on SIP Gateway is currently in Preview. We do not include Preview devices in our documentation as the information is likely to change frequently. We have GA planned for September, documentation will be updated to include compatible analog telephony adapters at GA.

**Comment by get-itips** [comment]
Closing, thanks @Chandranshu-Singh
