### ISSUE TITLE
Wrong year for Semi-Annual Enterprise Channel, Semi-annual Extended, LTSC, and remaining channels

### ISSUE THREAD

**Issue by myfope** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10224]
Wrong year at _Semi-Annual Enterprise Channel, Semi-annual Extended, LTSC, and remaining channels_?
This is the last channel and states January 2023 - should be 2024, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Version Independent ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Content: [The new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin)
* Content Source: [Teams/new-teams-desktop-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-desktop-admin.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello thanks for your feedback, there is an update pending that will fix that.
