### ISSUE TITLE
New Teams desktop - custom app support concerns

### ISSUE THREAD

**Issue by AlexSapple** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10227]
Hi guys, 

just had news that rollout of new Teams desktops are planned for September onwards - keen to understand what the deal is with custom apps. When I've tried the preview, I've not got the "add a tab" option to add an app - specifically we maintain a custom app that runs with the following tab config; 

    "configurableTabs": [
      {
        "configurationUrl": "***redacted***",
        "canUpdateConfiguration": true,
        "scopes": ["team", "groupchat"],
        "meetingSurfaces": ["stage", "sidePanel"],
        "context": ["meetingDetailsTab", "meetingSidePanel", "meetingStage"]
      }
    ],

so we expect to be able to essentially add the app to a meeting and access/interact with it within the surfaces of the meeting (main and side panel) 

I totally get that we are still looking at a preview of new Teams - but with a rollout start scheduled quite soon, we're slightly nervous about getting a chance to regression test custom apps on the new desktop.. 

have you got any detail on when we might be able to use custom apps in the normal way on the new desktop before roll out? or just any words of comfort that will help me sleep :)

many thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Version Independent ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Content: [Rollout schedule for the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-known-issues)
* Content Source: [Teams/new-teams-known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-known-issues.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @AlexSapple 
I'm afraid here we are limited to documentation fixes.
For sure when something changes regarding custom apps, this article will be updated, I also recommend, official blog articles at tech community and also https://adoption.microsoft.com/en-us/new-microsoft-teams/
If I happen to found out something about this topic I'll return here.
Thanks

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
