### ISSUE TITLE
change unit type

### ISSUE THREAD

**Issue by sdavisnz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10232]
[Enter feedback here]  at the bottom of the page there is information about microphone distances, all the rooms sizes are in feet, can we have an option for this info in metres please.

thanks - steve

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 385700f1-12d2-e4a2-a649-051f8401d8a3
* Version Independent ID: 385700f1-12d2-e4a2-a649-051f8401d8a3
* Content: [Teams Rooms certified systems and peripherals - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/certified-hardware?tabs=Android)
* Content Source: [Teams/rooms/certified-hardware.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/rooms/certified-hardware.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by get-itips** [comment]
Hello, I'll propose it and let's see if it gets approval. thank you for your feedback
