### ISSUE TITLE
Update doc to reflect 500 line limit

### ISSUE THREAD

**Issue by techbev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10233]
Can the document be updated to reflect there is a 500 line limit on Get-CsPhoneNumberAssignment cmdlet?

Customers need to loop the command to retrieve all results over 500. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 224b0537-e144-f5ed-6974-6e34733bceb2
* Version Independent ID: 4f1875c6-77ef-f636-669e-5f3af9691f7d
* Content: [See a list of telephone numbers in your organization - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/see-a-list-of-phone-numbers-in-your-organization)
* Content Source: [Teams/see-a-list-of-phone-numbers-in-your-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/see-a-list-of-phone-numbers-in-your-organization.md)
* Service: **skype-for-business-online**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Thanks for your feedback
