### ISSUE TITLE
Script Errors when trying to create mailbox

### ISSUE THREAD

**Issue by grahambird80** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1023]
When I run the script and select for it to create the mailbox on Exchange On-Premise I am always getting an error relating to changing the password, the account I use has full AD, Exchange, Skype Admin permissions;

Creating Mailbox
..............................You don't have permission to directly change a mailbox account password without providing old password. Reset Password role is required for directly changing password.
    + CategoryInfo          : NotSpecified: (skype.room3@domain.com:MailboxIdParameter) [Set-Mailbox], TaskArgumentException
    + FullyQualifiedErrorId : [Server=UABZEX02,RequestId=f531b30d-a990-4b74-a967-d3735964ceb4,TimeStamp=06/11/2018 12:55:02] [FailureCategory=Cmdlet-TaskArgumentException] 8A097A14,Microsoft.Exchange.Management.Re
   cipientTasks.SetMailbox
    + PSComputerName        : ex02.domain.com

Failed to create a new mailbox on exchange.
Remove-PSSession : Cannot bind parameter 'Id'. Cannot convert the "[PSSession]Session4" value of type "System.Management.Automation.Runspaces.PSSession" to type "System.Int32".
At X:\20 Infrastructure\Powershell\Skype\SkypeRoomProvisioningScript-Updated.ps1:77 char:30
+         Remove-PSSession -Id $sessExchange
+                              ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-PSSession], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.RemovePSSessionCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d495057-36be-b228-0483-aae89fd01666
* Version Independent ID: f02fa875-b84b-5501-5879-17ea3d017142
* Content: [Configure accounts for Skype Room Systems v2](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/room-systems-v2-configure-accounts)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/room-systems-v2-configure-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/room-systems-v2-configure-accounts.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by AndreaBarr** [comment]
@grahambird80 Thank you for this inquiry. 

I am not sure why you are getting a change your password error with this script. I want to make sure you get the best help possible. I think the best thing is to get you over to Support. They have more resources to dig into this issue and find a resolution. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
