### ISSUE TITLE
with New Teams again dial tone from Skype for Business on prem client

### ISSUE THREAD

**Issue by WillemVerwijs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10234]
Hi Team, so recently I enabled the New Teams (i hate the word new, because how are you gonna the next new version? new new Teams or newer Teams?) and an issue that had just recently been resolved, immediately reappeared: a dial tone from the skype for business client can be heard after ending a Teams meeting. Now the question is... does anybody read this comment and more important... will anyone relay this to the product group? And how will I know that that is done?

Looking forward to not a dial tone in the "New" teams.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist voor de koppeling learn.microsoft.com ➟ GitHub-probleem.*

* ID: 163ad900-960d-4ac0-1dde-082be316f282
* Version Independent ID: 163ad900-960d-4ac0-1dde-082be316f282
* Content: [Deploy new Microsoft Teams with Microsoft 365 Apps - Microsoft Teams](https://learn.microsoft.com/nl-nl/MicrosoftTeams/new-teams-deploy-with-m365apps)
* Content Source: [Teams/new-teams-deploy-with-m365apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-deploy-with-m365apps.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @WillemVerwijs I'm sorry, I'm afraid that here we are limited to ***documentation fixes***, not product issues.
The best in this case would be to use the feedback tool from the Teams app.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
