### ISSUE TITLE
Linking teams and adding user

### ISSUE THREAD

**Issue by TateGunning** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10238]
####

- need to renew
- trying to link teams and add users
- interested in data residency
- restarting my computer

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84f319aa-94de-bed1-2e5d-c6fe24436dac
* Version Independent ID: ee6daf32-7e03-801c-dd1b-50bf35e4635e
* Content: [Location of data in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/location-of-data-in-teams)
* Content Source: [Teams/location-of-data-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/location-of-data-in-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
