### ISSUE TITLE
Invalid regexp ?

### ISSUE THREAD

**Issue by ocean2706** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10235]
According to https://www.regexpal.com/ 
^+1(\d{10})$ is invalid regexp. 
 Should be ^\\+1(\d{10})$ 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6981866f-a685-d802-d64f-98685a5c658d
* Version Independent ID: a1f83744-abb7-4c33-6f60-19ff2732871c
* Content: [Translate phone numbers for Direct Routing - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/direct-routing-translate-numbers)
* Content Source: [Teams/direct-routing-translate-numbers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/direct-routing-translate-numbers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @ocean2706 George, the \ is there, it's just that when the article was converted from markdown, isn't on the published version of the article, I'll try to fix it. Thanks for your feedback!!
