### ISSUE TITLE
It doesn't make any sense or help in understanding what it is. I still have no idea after reading the page.

### ISSUE THREAD

**Issue by LeonOrtoo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10239]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-exploratory)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by get-itips** [comment]
Hello @LeonOrtoo 
Thanks for your feedback.
Can you please specify what do you see can be fixed in this article? or explain more in detail.
Thank you

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
