### ISSUE TITLE
Limited team creation

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1024]
We have limited teams creation via powershell. One of the results of this policy is that the menu for "Create a Team" that pops up the window as shown above does not exist for anyone, including admins who are in the security group designated for teams creation. 

Is there a method of creating an org-wide team without going through the above menu?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by AndreaBarr** [comment]
@thedrum808 Thank you for this feedback

I feel like there is another way to create teams other than that menu but I'm not sure. Let me get this over to the Teams team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by thedrum808** [comment]
Andrea - The only other method I'm aware of (when group creation is limited) is to do so via creating an O365 group from the admin center, being an admin in the AllowedToCreateGroups group as detailed here (https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide). With these settings on, when in Teams, the "Create a Team" option is invisible, and the only thing you can see is "Create from existing group" or joining other existing teams.

**Comment by LanaChin** [comment]
I've followed up with the Teams team and learned that an org-wide team can only be created by using the Teams client. There's not another way to do so outside the Teams client (ie. using PowerShell, Microsoft Graph or any other client).  The team shared two workarounds and the article has been updated with the workaround information. See the FAQ section.  Cheers.
