### ISSUE TITLE
Redmond dial plan table?

### ISSUE THREAD

**Issue by HandyAndyOnGitHub** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10240]
Regarding the table following the text "The following table illustrates a sample dial plan for Redmond, Washington, United States, based on the normalization rules shown in the previous table"; should the table have more than one column?  It appears to be lacking any useful information.

Regards
Andy

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 847c0505-3441-b5db-1f81-c7759bffd1e3
* Version Independent ID: 3c6b3820-349f-caf5-c510-a771a3b7a770
* Content: [What are dial plans? - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/what-are-dial-plans#normalization-rules)
* Content Source: [Teams/what-are-dial-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/what-are-dial-plans.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @HandyAndyOnGitHub how are you?

Maybe that's because it could also be shown as a bulleted list, like this

Redmond dial plan _has this rules assigned_
- 5digitExtension
- 7digitcallingRedmond
- RedmondSitePrefix
- RedmondOperator

I can understand that a table with only one column could be confusing.

Thank you

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
