### ISSUE TITLE
Two prerequisite links are same

### ISSUE THREAD

**Issue by geektocore** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10243]
Obtain organization's subscription and user licensing... and assign permissions... are same links. Is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2bc431d8-32c4-957d-9b3b-84bee4778ca5
* Version Independent ID: 2bc431d8-32c4-957d-9b3b-84bee4778ca5
* Content: [Search the audit logs for app management events - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/audit-app-management-activities)
* Content Source: [Teams/audit-app-management-activities.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/audit-app-management-activities.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by ashishguptaiitb** [comment]
Hi @geektocore , thanks for sharing this issue. I've updated the docs to point these to the respective sections in the same article. Closing this issue now.

**Comment by ashishguptaiitb** [comment]
Ah! Thanks.
