### ISSUE TITLE
Document needs to be updated with new features

### ISSUE THREAD

**Issue by beeface** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10242]
Document needs to be updated to include newer features. Bluejeans for example isn't included 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 25a70665-5bf1-14f7-1df0-7596effcaf48
* Version Independent ID: 813cf005-2777-9419-d1ce-3f9401ac267c
* Content: [Remotely manage Microsoft Teams Rooms device settings - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/xml-config-file)
* Content Source: [Teams/rooms/xml-config-file.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/rooms/xml-config-file.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by get-itips** [comment]
Hello @beeface I'm working on this

**Comment by tonysmit** [comment]
I reached out to the PM @NancyForero.

**Comment by tonysmit** [comment]
I just reached out to the PM and BlueJeans is going away. Verizon bought them and are closing them out.
