### ISSUE TITLE
Possible date error?

### ISSUE THREAD

**Issue by dmitriygpak** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10241]
[Enter feedback here]
In this section - https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin#update-channels-1 - it says that for "Semi-Annual Enterprise Channel, Semi-annual Extended, LTSC, and remaining channels" the date is Mid January 2023. Is it an error and it should be 2024 instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Version Independent ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Content: [The new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin)
* Content Source: [Teams/new-teams-desktop-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-desktop-admin.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Already fixed, thank you!
