### ISSUE TITLE
The user info for bots requires development effort

### ISSUE THREAD

**Issue by geektocore** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10244]
The tip about user reporting for bot usage needs help from a developer. It isn't mentioned here. The doc claims that I can do it as an admin.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2bc431d8-32c4-957d-9b3b-84bee4778ca5
* Version Independent ID: 2bc431d8-32c4-957d-9b3b-84bee4778ca5
* Content: [Search the audit logs for app management events - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/audit-app-management-activities)
* Content Source: [Teams/audit-app-management-activities.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/audit-app-management-activities.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by ashishguptaiitb** [comment]
Thanks @geektocore . I've updated the help article to mention that an admin will need to commission the custom development. Hope it helps. I'm closing this issue now.
