### ISSUE TITLE
Max # of policies that can be created?

### ISSUE THREAD

**Issue by davidjfriedman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10247]
Team,

Is it possible to document whether or not there are limitations on the maximum number of policies that can be created by Teams admins (whether that be an overall max limit, or max limits per specific types of policies)?

Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hello @davidjfriedman David, I'm trying to get this information, any special use case where you hit a limit?
Thanks

**Comment by davidjfriedman** [comment]
Nothing unique--just a question that has come up so figured worth checking to see if it could be documented.  Thank you

**Comment by shivtorov** [comment]
"New-CsTenantDialPlan:  Maximum[1000] tenant Dial plans number limitation is reached for this tenant. Remove any unused tenant Dial Plans and try again..."

**Comment by get-itips** [comment]
> "New-CsTenantDialPlan: Maximum[1000] tenant Dial plans number limitation is reached for this tenant. Remove any unused tenant Dial Plans and try again..."

That one is documented here https://learn.microsoft.com/en-us/microsoftteams/what-are-dial-plans

**Comment by get-itips** [comment]
@davidjfriedman I was given the information that there is no max number of policies
