### ISSUE TITLE
Add Information about the number of federated external domains limit

### ISSUE THREAD

**Issue by cadasi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10256]
It seems that when you used closed federation/external communications where you just allow domains instead of open communications with anyone external, the limit of domains that we can add as allowed is 4000 based on tests that we did.
there's no Public Documentation on that. The only way for us to validate this, was by testing, but, this does not make the information official or documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external meetings and chat with people and organizations using Microsoft identities - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/trusted-organizations-external-meetings-chat?tabs=organization-settings&source=docs#specify-trusted-microsoft-365-organizations)
* Content Source: [Teams/trusted-organizations-external-meetings-chat.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/trusted-organizations-external-meetings-chat.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @cadasi Carlos, I'm working on this.

**Comment by get-itips** [comment]
PR was closed, closing issue for now as it is being discussed internally.
