### ISSUE TITLE
When Microsoft will add any information about ExplicitRecordingConsent and Attendance reports?

### ISSUE THREAD

**Issue by eugenianegut** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10251]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a8b1087-ae40-6813-16bc-a69c90e50d19
* Version Independent ID: b808e843-80d8-4a96-c6ed-e8175968eb73
* Content: [Attendance report for meetings and webinars in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/meeting-attendance-report)
* Content Source: [Teams/teams-analytics-and-reports/meeting-attendance-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/teams-analytics-and-reports/meeting-attendance-report.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
