### ISSUE TITLE
Wrong help information

### ISSUE THREAD

**Issue by Peter186** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10252]
To address a message which informs me our orgs are set up to talk, I am directed to go to Admin and then select 'External Users'.  There isn't any option for 'External Users'.  This is happening all the time:  instructions that direct me to select options that don't exist. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external meetings and chat with people and organizations using Microsoft identities - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/trusted-organizations-external-meetings-chat?tabs=organization-settings)
* Content Source: [Teams/trusted-organizations-external-meetings-chat.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/trusted-organizations-external-meetings-chat.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
