### ISSUE TITLE
Hidden in the Exchange GAL also hides from AA Directory Search

### ISSUE THREAD

**Issue by Korbyn72** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10250]
It should be Noted that is a user is Hidden from the Exchange GAL, they are also hidden from the Teams Auto Attendant "Dial by name/extension" functionality.  I spent a week with a cx troubleshooting why a certain user wasn't reachable by their extension.  Even opened up a premier support case, and spent a couple days with them before having an epiphany to ask if the user was hidden from the Exchange GAL.  They were, and shortly after unhiding her, which they don't know why she was even hidden in the first place, it started to work.

MS Support were also unaware:  TrackingID#2307070010002721

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 016be911-545f-28e4-97d2-549f1078a196
* Version Independent ID: 9021aad0-83c0-1173-01ae-6cc68217e8d4
* Content: [Auto attendant and Call queue dialing and voice recognition reference - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/dial-voice-reference#search-considerations)
* Content Source: [Teams/dial-voice-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/dial-voice-reference.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by get-itips** [comment]
Hello @Korbyn72 
How are you?
I see it is documented here https://learn.microsoft.com/en-us/MicrosoftTeams/create-a-phone-system-auto-attendant?WT.mc_id=TeamsAdminCenterCSH&tabs=dial-scope

> If a user is in both lists or if they are hidden from the Exchange GAL, they are excluded from the directory.

**Comment by Korbyn72** [comment]
I see it there now that you point it out, page looks like it was updated June 27, 2023.  However, it really should be on the https://learn.microsoft.com/en-us/microsoftteams/dial-voice-reference page.  Having been deploying Teams AA/CQ's for the last 4-5 years, changes/developments should be on the reference page more so then Step 5 of the the deployment steps.
