### ISSUE TITLE
Known Issue page title when pasting URL is incorrect.

### ISSUE THREAD

**Issue by bholzmmc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10267]
Page title pastes into Word/OneNote/Outlook as "Rollout schedule for the new Microsoft Teams desktop client - Microsoft Teams | Microsoft Learn" with correct address instead of "New Teams desktop client: Known issues"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Version Independent ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Content: [Rollout schedule for the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-known-issues)
* Content Source: [Teams/new-teams-known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-known-issues.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by bholzmmc** [comment]
Example from OneNote
![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/37308535/ac5f8967-17b5-49b5-bcbb-d8539ca4d820)

**Comment by get-itips** [comment]
Thanks for your feedback!

**Comment by get-itips** [comment]
Article title has been fixed in another PR
