### ISSUE TITLE
No pricing information on the referenced page

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10262]
Hi! Pages linked under "Pricing information" do not provide any details on the calling rates for calling plans nor audio conferencing.

Where can we find per minute cost of calling from PYAG calling plan as well when minutes included in calling plans are used up as well as cost of conferencing calls.

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla witryny learn.microsoft.com ➟ Linkowanie do problemu w usłudze GitHub.*

* ID: 33bfc660-573d-b57e-8b67-6aa1fbe820ad
* Version Independent ID: 53318fba-10e9-cd4b-f0ee-397cd10e8c0c
* Content: [Microsoft Calling Plans for Teams - Microsoft Teams](https://learn.microsoft.com/pl-pl/microsoftteams/calling-plans-for-office-365)
* Content Source: [Teams/calling-plans-for-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/calling-plans-for-office-365.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @Larryngolog I'm working on this
