### ISSUE TITLE
What is the default policy..?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10263]
Hi, 
When taking policies using the PowerShell, I'm getting:

**PS C:\> Get-CsTeamsUpdateManagementPolicy | ft Identity, AllowPublicPreview, UseNewTeamsClient**

Identity                                          AllowPublicPreview  UseNewTeamsClient
........                                          ..................  .................
Global                                            FollowOfficePreview AdminDisabled
Tag:Default                                       FollowOfficePreview MicrosoftChoice

Anybody have ideas what is this "**Default**"? I cannot remember that I have added such, And it is not visible on the Teams Admin center eithers.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 97f0f8f2-89c3-7b94-78df-3b0864c35b04
* Version Independent ID: 97f0f8f2-89c3-7b94-78df-3b0864c35b04
* Content: [Deploy the new Teams client using policies - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-deploy-using-policies?tabs=teams-admin-center)
* Content Source: [Teams/new-teams-deploy-using-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-deploy-using-policies.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @Petri-X 
The "Tag:Default" one can't be edited, as far as I know it is for internal use.

**Comment by Petri-X** [comment]
Thanks @get-itips, normally there has been some indication of those internal use policies. But this was also what I was expected to be. So thanks to confirming my thoughts :)
