### ISSUE TITLE
Content on this page points to a broken link.

### ISSUE THREAD

**Issue by billbliss** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1026]
In the section https://docs.microsoft.com/en-us/microsoftteams/known-issues#administration, there's a link to https://msdn.microsoft.com/microsoft-teams/connectors. That is not the correct link and leads to a 404.

This is probably what it should link to: https://docs.microsoft.com/en-us/MicrosoftTeams/enable-features-office-365#apps based on the text above it, but given the rest of the text in that row, perhaps it really should link to something like https://answers.microsoft.com/en-us/msoffice/forum/msoffice_o365admin-mso_teams-mso_o365b/how-to-enable-or-disable-connectors-in-office-365/33d4b2c1-00eb-420a-ad83-01a2b42ad098. Not sure which.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@billbliss Thank you for pointing this out to us

I will get this information about the broken link to the Teams team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by LolaJacobsen** [comment]
Per Marc Lauinger, this is the correct link: 
https://answers.microsoft.com/en-us/msoffice/forum/msoffice_o365admin-mso_teams-mso_o365b/how-to-enable-or-disable-connectors-in-office-365/33d4b2c1-00eb-420a-ad83-01a2b42ad098 

I've updated the article, it'll go live later today.
