### ISSUE TITLE
Audio Conferencing is supposed to be included with M365 E3 by now

### ISSUE THREAD

**Issue by kmckeowncasto** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10272]
[Enter feedback here]
Audio conferencing is supposed to be included with M365 E3 licensing by now as well. However, this page only states that it is included with M365 E5.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed33488-1a24-f443-dd56-c5327188b5a4
* Version Independent ID: 8da32180-396d-c7a8-6410-472beabff9ce
* Content: [Set up Audio Conferencing for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-US/microsoftteams/set-up-audio-conferencing-in-teams?WT.mc_id=365AdminCSH_inproduct)
* Content Source: [Teams/set-up-audio-conferencing-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/set-up-audio-conferencing-in-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hello @kmckeowncasto 
How are you?
Do you have some backing information about that? I've just checked on a tenant with M365 E3 Licenses at the audio conferencing service plan is not there.
Thank you,
