### ISSUE TITLE
Microsoft does not charge for phone numbers

### ISSUE THREAD

**Issue by 3017mark** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10277]
The statement in documentation is misleading.  "Microsoft will become your service provider and will bill you for those phone numbers."  In fact, the only requirement is that end-users must have a valid phone system license.  Please update to properly reflect this fact.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0b31da6-4820-3685-984d-960c2d63e205
* Version Independent ID: a0b31da6-4820-3685-984d-960c2d63e205
* Content: [Transfer phone numbers to Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/phone-number-calling-plans/transfer-phone-numbers-to-teams)
* Content Source: [Teams/phone-number-calling-plans/transfer-phone-numbers-to-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/phone-number-calling-plans/transfer-phone-numbers-to-teams.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Thanks for your feedback
