### ISSUE TITLE
No mention of limit for @mentions

### ISSUE THREAD

**Issue by mirlenbrink** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10285]
The limits specification documentation does not mention a limit on the number of @mentions that are allowed in each individual message.  Through trial and error I have discovered that there is a limit of 20 @mentions per message and you are presented with this in an error message when including more than 20 in a message.  The documentation should be updated to include this limit.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hello @mirlenbrink Brian, I was able to mention 21 people on a Group Chat, can you attach here the error that you received? Thanks

**Comment by mirlenbrink** [comment]
Hi @get-itips .... please see the error I receive below.  I should have mentioned originally that I am posting this message as a reply and I'm using Power Automate.  So, the error is surfacing through to the Power Automation action _Reply with a message in a channel_.

`
{
  "statusCode": 400,
  "headers": {
    "Access-Control-Allow-Methods": "GET, PUT, PATCH, DELETE, POST",
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Max-Age": "3600",
    "Access-Control-Expose-Headers": "*",
    "Date": "Fri, 11 Aug 2023 21:04:18 GMT",
    "Content-Length": "332",
    "Content-Type": "application/json"
  },
  "body": {
    "error": {
      "code": 400,
      "message": "Maximum number of @mentions of users allowed is 20.",
      "source": "flow-apim-msmanaged-na-centralus-01.azure-apim.net",
      "path": "choose[24]\\when[1]\\choose\\when[1]\\send-request",
      "policyId": ""
    }
  }
}
`

**Comment by get-itips** [comment]
Please, can you confirm if you receive the same error if you do not use Power Automate, so I understand how I'll try to reproduce this, thanks

**Comment by get-itips** [comment]
@mirlenbrink Brian, have you seen my last question? Thank you

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
