### ISSUE TITLE
Can admins remove auto-installed app

### ISSUE THREAD

**Issue by geektocore** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10283]
Can admins uninstall a previously auto-installed app for everyone? It just says users can remove admin-installed app for themselves. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0216493-15c9-7371-89c2-f09c45c3d5c1
* Version Independent ID: a0216493-15c9-7371-89c2-f09c45c3d5c1
* Content: [Auto install approved Teams apps - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/auto-install-approved-apps)
* Content Source: [Teams/auto-install-approved-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/auto-install-approved-apps.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by ashishguptaiitb** [comment]
Thanks @geektocore . I am checking with the feature team and shall update the docs accordingly.

**Comment by ashishguptaiitb** [comment]
Hi @geektocore, an admin cannot remove apps for anyone, whether it's installed through Auto install approved apps feature, installed by user, or installed by app setup policies. The only way to `remove` an app is for users to remove it. Or admins can prevent usage by blocking the app completely in the tenant for everyone OR block one or more users from accessing the app by using app permission policy.

How to block an app is documented at https://learn.microsoft.com/microsoftteams/manage-apps#allow-and-block-apps 

Hope this helps. I'm closing this issue.
