### ISSUE TITLE
Microsoft Teams Rooms licenses out of date

### ISSUE THREAD

**Issue by systemswizard** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10293]
This documentation needs to be updated as Teams Room Basic licenses do not allow us to join our rooms to live events anymore.

![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/5238672/11ad2b60-6165-4d30-8992-d94bd28bd793)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/rooms/rooms-licensing.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by get-itips** [comment]
Hello @systemswizard 
To dig into this, can you please detail me more information, are you trying to join as attendee or presenter? Thanks

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
