### ISSUE TITLE
New Teams missing"Manage API" and "Third-party app API" section, aka third-party device support

### ISSUE THREAD

**Issue by timdonovanuk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10298]
I do not see this mentioned as a missing feature here: https://learn.microsoft.com/en-gb/microsoftteams/new-teams-desktop-admin?branch=jhendr-teams21&amp%3Btabs=teams-admin-center#what-features-are-still-missing

The documentation for Old Teams is here: https://support.microsoft.com/en-au/office/connect-to-third-party-devices-in-microsoft-teams-aabca9f2-47bb-407f-9f9b-81a104a883d6

Is MS withdrawing support for connecting to third-party devices?

**Comment by get-itips** [comment]
Hello @timdonovanuk 
I think the best would be to follow updates to the mentioned Microsoft Adoption resource to understand what's still missing from the new teams. 
Thank you,
