### ISSUE TITLE
Issues Page need updation

### ISSUE THREAD

**Issue by RohitY24** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10297]
The Issues page for the new Teams App needs to be updated. Many features noted in the Known Issues page are available or have been resolved, but not updated there yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Version Independent ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Content: [Rollout schedule for the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-known-issues)
* Content Source: [Teams/new-teams-known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-known-issues.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @RohitY24 so I can dig into this, can you specify which issues you see are resolved so I can confirm? Thank you

**Comment by RohitY24** [comment]
Hi @get-itips, I think that the team will need to check exactly which ones have been fixed 😅
I was checking the list of Known Issues for the new Teams app in areas in LOB Apps and a few more areas and found them to be updated. The list was last updated weeks ago and might need a regular fresh updating.
