### ISSUE TITLE
The Interactive Guides are producing a DNS Server Unavailable error message. Is there any fix for this?

### ISSUE THREAD

**Issue by SherriBeck** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10309]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 752a6dc8-4018-88aa-faa4-c07c1c0a1719
* Version Independent ID: 7d6d29c5-f699-2abd-71c2-7c49061dd068
* Content: [Admin training resources - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/itadmin-readiness?source=docs#teams-rooms-foundations-for-it---av-pros)
* Content Source: [Teams/ITAdmin-readiness.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/ITAdmin-readiness.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
