### ISSUE TITLE
Roles Clarity

### ISSUE THREAD

**Issue by DarCampbell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10300]
The roles description for this page does not accurately reflex the level of detail that a company would need to understand what role a user would need and what each role can do. An example is both the Teams Administrator and Teams Communication Administrator say "Manage voice, including calling policies and phone number inventory and assignment.1,3" but this does not include call queue assigning to a Teams channel that can only be done in Teams Administrator.

![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/40171398/1d657cf3-4f18-4c3e-b183-28a320624188)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b434530-6bf2-6e00-6eae-6fa043d022ce
* Version Independent ID: caab785f-e3a4-831a-87d8-26934a9f834f
* Content: [Use Microsoft Teams administrator roles to manage Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/using-admin-roles)
* Content Source: [Teams/using-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/using-admin-roles.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
