### ISSUE TITLE
Page not up to date

### ISSUE THREAD

**Issue by MHDufau** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10308]
Hello
This page is not up to date.
The explanations on the "Live Share" configuration are missing.
Thank You for update

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9e8bc321-43b2-5155-536c-2be64e26e345
* Version Independent ID: 625609b4-e633-7e26-367f-da17f3e4f54b
* Content: [Manage meeting policies for content sharing - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/meeting-policies-content-sharing)
* Content Source: [Teams/meeting-policies-content-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/meeting-policies-content-sharing.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @MHDufau 
How are you?
Can you please specify what is missing regarding meeting policies and the feature you mention?
Thanks,

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
