### ISSUE TITLE
New/Set-CsAutoAttendant Needs To Support "Authorized Users"

### ISSUE THREAD

**Issue by ajacks88** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10311]
New/Set-CsCallQueue supports setting authorized users, the same needs to be true for Auto Attendants.

**Comment by scanum** [comment]
Hi @ajacks88 thanks for the feedback. Please link the article you are referring to. Thanks.

**Comment by get-itips** [comment]
Closing as no answer from submitter.
