### ISSUE TITLE
Customer push back on MFA usage due to this doc

### ISSUE THREAD

**Issue by cypheredout** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10314]
Hey there!  In the blue box for MFA we mention that it "shouldn't" be used, not that it is not supported.  Internally we have an ask for this to be review but wanted to get it flagged here as well for review.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f7e3603-9bec-acfc-1854-2c1275950cde
* Version Independent ID: 2aed2376-277a-3e93-5000-e509ff53434d
* Content: [Authentication in Microsoft Teams Rooms on Windows - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-authentication)
* Content Source: [Teams/rooms/rooms-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/rooms/rooms-authentication.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by dstrome** [comment]
@cypheredout - Please don't post issues related to customer feedback in this public repo. Please contact @tonysmit directly. I am deleting this issue.
