### ISSUE TITLE
Teams Premium notation of feature enablement

### ISSUE THREAD

**Issue by cypheredout** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10310]
Working on internal project with TM Premium (bkendrick@microsoft.com).  Can we work on notating that when Teams Premium licensing gets assigned it may take up to 24 hours for enablement?  Similar to the calling plan blurb:

"After assigning a Microsoft Calling Plan to a user, it can take up to 24 hours before they'll see the dial pad in their Teams client. If the dial pad isn't shown in 24 hours, check your [dial pad configuration](https://learn.microsoft.com/en-us/microsoftteams/dial-pad-configuration). If necessary, you can also [contact support](https://support.office.com/article/32a17ca7-6fa0-4870-8a8d-e25ba4ccfd4b)."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed46e6b1-48c5-5302-2f38-89c315d4bff7
* Version Independent ID: 81053999-79ca-888d-38fa-8978276b6228
* Content: [Assign Teams add-on licenses to users - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/assign-teams-add-on-licenses)
* Content Source: [Teams/teams-add-on-licensing/assign-teams-add-on-licenses.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/teams-add-on-licensing/assign-teams-add-on-licenses.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by get-itips** [comment]
Thanks for your feedback
