### ISSUE TITLE
Update the issues page for call queues.

### ISSUE THREAD

**Issue by jptechie** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10327]
Hi- can you please update this list for Call Queues? There is no Call tabs in the channel to view history in the new team's client or see how many agents are opt'd into the queue. When will this be available? Right now, the workaround is to go back to classic teams. Thank you.
Classic Teams
![classicteams](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/56977377/07a60c10-6f35-4b41-9813-609d1d7af2fe)
New Teams
![New teams client](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/56977377/e51d5701-68f5-44cf-96dc-c8cdefd8a3ed)

**Comment by scanum** [comment]
Hi @jptechie 
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jptechie** [comment]
what? is it expected to see this in the new teams client? please advise.
