### ISSUE TITLE
Update the hyperlink for DigiCert Global Root G2

### ISSUE THREAD

**Issue by AnjumRazaTole** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10336]
[Enter feedback here]
Need to update the hyperlink as below

The new CA certificate can be downloaded directly from DigiCert: [DigiCert Global Root G2](https://cacerts.digicert.com/DigiCertGlobalRootG2.crt)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e18d7c72-cd78-c0fe-42d4-d08275b68793
* Version Independent ID: e18d7c72-cd78-c0fe-42d4-d08275b68793
* Content: [What's New Direct Routing - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/direct-routing-whats-new?source=docs)
* Content Source: [Teams/direct-routing-whats-new.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/direct-routing-whats-new.md)
* Service: **msteams**
* GitHub Login: @wlibebe
* Microsoft Alias: **wlibebe**

**Comment by AnjumRazaTole** [comment]
Link address is - https://cacerts.digicert.com/DigiCertGlobalRootG2.crt

**Comment by get-itips** [comment]
@AnjumRazaTole Hello how are you? Thank you, however, there is no link to update, the current text has no link and instructs to download directly from the certificate provider.
