### ISSUE TITLE
Accounts without CA policies for Virtual Front Desk

### ISSUE THREAD

**Issue by yuki-iwagishi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10332]
https://support.microsoft.com/en-us/office/what-s-new-in-microsoft-teams-devices-eabf4d81-acdd-4b23-afa1-9ee47bb7c5e2#ID0EBD=Teams_displays
Teams Displays- Virtual Front Desk discription says 
`This feature is available on Teams certified displays on the Teams Shared Devices license and is recommended for accounts without CA policies.`

Accounts with CA policies works fine for Teams Display-Resource accounts. This might be coming from Hot Deesking topics. So please remove the statement "and is recommended for accounts without CA policies." from this what's new topic.

**Comment by get-itips** [comment]
Hello @yuki-iwagishi how are you?

Support.Microsoft.com articles are not stored on GitHub/Microsoft Learn so unfortunately I can't take action on it.

Thank you,
