### ISSUE TITLE
Inaccurate information

### ISSUE THREAD

**Issue by cowens16** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10339]
[After some testing- the document statement that 'Team Owners can see the names of all private channels' is FALSE. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/private-channels)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @cowens16 

How are you? Hope you are doing good.
I tested this, the owner, not part of the private channel, can see it by going to Team Settings - Channels.

Thanks
