### ISSUE TITLE
Links to Coffee in the Cloud PowerPoint decks no longer working

### ISSUE THREAD

**Issue by davidjfriedman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10334]
Team,

The following links in the "Technical training" table are now resulting in a GitHub 404 page:

https://aka.ms/teams-foundations-deck
https://aka.ms/teams-direct-routing-deck
https://aka.ms/teams-dec-deck
https://aka.ms/teams-governance-deck
https://aka.ms/teams-live-events-deck
https://aka.ms/teams-phone-system-deck
https://aka.ms/media-in-teams-deck
https://aka.ms/teams-media-flows-deck
https://aka.ms/teams-meetings-intro-deck
https://aka.ms/teams-security-compliance-deck
https://aka.ms/teams-upgrade-deck
https://aka.ms/teams-clients-deck

Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 752a6dc8-4018-88aa-faa4-c07c1c0a1719
* Version Independent ID: 7d6d29c5-f699-2abd-71c2-7c49061dd068
* Content: [Admin training resources - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/itadmin-readiness#technical-training)
* Content Source: [Teams/ITAdmin-readiness.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/ITAdmin-readiness.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
I'm working on this

**Comment by traya1** [comment]
Hi Team,

Thanks for your patience. We are working on resolving the issue.

**Comment by davidjfriedman** [comment]
@scanum, we noticed this was closed but the links to the decks are still resulting in a 404.  Should we re-open or is there an expected delay in when the data will become available again?  Thank you
