### ISSUE TITLE
Federation limit

### ISSUE THREAD

**Issue by buildbod** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10337]
Is there a limit for the number of domains that can be federated with using an AllowedDomains list?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [IT Admins - Manage external meetings and chat with people and organizations using Microsoft identities - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/trusted-organizations-external-meetings-chat?tabs=organization-settings)
* Content Source: [Teams/trusted-organizations-external-meetings-chat.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/trusted-organizations-external-meetings-chat.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by buildbod** [comment]
The limit appears to be 4,000 based on running the PowerShell command and feedback from Microsoft support. It would be good for the limit to be reflected in the documentation and the limits of the service.




CONFIDENTIAL
