### ISSUE TITLE
Detailing additional restrictions of the 'self-service' trail of Team Exploratory

### ISSUE THREAD

**Issue by delsassergh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10335]
[Enter feedback here]
I am seeing references to the 'self-service' trial of Team Exploratory, which I am dealing with. Later in the document statements are made about how to remove the trial from your tenant but they do not take into account the self-service trial an not be removed. 
This has caused an issue with our IdP product (Okta) leveraging the MSGraph API to add/remove enterprise licensing. Some additional clarity here could help direct a quicker troubleshooting session.
Product in question is labeled:
"Microsoft_Teams_Exploratory_Dept" (SKUID: e0dfc8b9-9531-4ec8-94b4-9fec23b05fc8)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-exploratory#how-long-does-the-teams-exploratory-experience-last)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@delsassergh Thank you for the feedback. We have updated the article to add the appropriate clarify text. The updates will be published today.

GitHub PR reference: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/pull/12509

**Comment by get-itips** [comment]
updated in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/f9d21a98ecd93336880d436076493d826265de87
