### ISSUE TITLE
Teams owners do not see private channels

### ISSUE THREAD

**Issue by dmittel07** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10338]
"Team owners can see the names of all private channels in their team and can also delete any private channel in the team. (A deleted private channel can be restored within 30 days after it's deleted). Team owners can't see the files in a private channel or the conversations and member list of a private channel unless they're members of that private channel."

After testing our Teams owners do not see any information about private channels.  They do not show up in the channel list in the regular teams view nor in the Manage Team/Channels section

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/private-channels)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @dmittel07 please see https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/10339#issuecomment-1709047955
