### ISSUE TITLE
The instructions for adding the trial subscription are incorrect (at least for educational organizations)

### ISSUE THREAD

**Issue by Eric-SeattleU** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10340]
The directions for adding the trial subscription were incorrect for my tenant (an educational organization). Instead of finding a trial license when searching for Teams Premium, I instead had to go to the details of the paid Teams Premium for Faculty license and then there was a "Start free trial" link next to the Buy button.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 89daab79-5c8a-4693-2218-50027e1249b2
* Version Independent ID: 89daab79-5c8a-4693-2218-50027e1249b2
* Content: [Roll out a Teams Premium trial - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-premium-trial#add-the-teams-premium-trial-to-your-organization-and-assign-licenses)
* Content Source: [Teams/teams-premium-trial.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/teams-premium-trial.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @Eric-SeattleU 
I was able to find _Teams Premium for Faculty Trial_ without the need to first go to the  paid version.
Please let me know if I misunderstood.
Thanks for your feedback!

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
