### ISSUE TITLE
Missing SFB Server 2019 updates info

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10346]
Please add missing SFB updates. For example, SFB Server 2019 update version 2046.524 released August 2023.

Content: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Skype/SfbServer/sfb-server-updates.md

**Comment by get-itips** [comment]
Hello @shivtorov 
If I follow the link for https://support.microsoft.com/kb/4470124 it says it is "July 2023" update and it matches the build that you included (7.0.2046.524)

Please let me know if I am missing something
