### ISSUE TITLE
Can we add a note that clarifies that sync is one way from PMP to SNOW, changes to SNOW ticket to PMP portal are not supported. 

### ISSUE THREAD

**Issue by mjtart** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10345]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 99171a71-5bc9-731e-fbd2-2234bc0c68c5
* Version Independent ID: 3a0b7200-97ba-9467-97b7-bac6ca16e9fa
* Content: [Configure ServiceNow for Teams Rooms - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/microsoft-teams-rooms-configure-servicenow)
* Content Source: [Teams/rooms/microsoft-teams-rooms-configure-servicenow.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/rooms/microsoft-teams-rooms-configure-servicenow.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @altsou
* Microsoft Alias: **altsou**

**Comment by get-itips** [comment]
Hello @mjtart how are you?
Can you please include some backing information so I can start investigating this to push an update to the article?
Thank you

**Comment by get-itips** [comment]
Hello @mjtart were you able to see my comment here? Thank you

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
