### ISSUE TITLE
Guest Access in Teams in GCCH

### ISSUE THREAD

**Issue by J227668** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10348]
Please update this page to include that guest access in GCCH is in fact available across cloud. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5f080a5c-4268-1db4-566f-f1edc27920b5
* Version Independent ID: ac556a92-58af-3e05-f53b-0fc00afc96c0
* Content: [Use guest access and external access to collaborate with people outside your organization - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/communicate-with-users-from-other-organizations)
* Content Source: [Teams/communicate-with-users-from-other-organizations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/communicate-with-users-from-other-organizations.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @J227668 
How are you?
It says here https://www.microsoft.com/en-ww/microsoft-365/roadmap?filters=&searchterms=teams%2Cguest%2Ccross it will roll out this month.
I see you are a Microsoft employee, can you please confirm this is rolled out for all tenants so we can push an update to the article?
Thank you,

**Comment by get-itips** [comment]
@J227668 Were you able to see my comment here? thanks

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
