### ISSUE TITLE
Is there another way to obtain the Windows 11 Enterprise ISO?

### ISSUE THREAD

**Issue by SenseiTechDT69** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10344]
[Enter feedback here]
We do not have a VLSC agreement, however we do have an E5 subscription. It's my understanding that VLSC is transitioning to the new billing portal in M365. I have been unable to locate and download the specific ISO that this article refers to: https://learn.microsoft.com/en-us/microsoftteams/rooms/console. 
Is there another way to obtain this very specific ISO (Windows 11, version 22H2 (updated Sept 2022) x64)?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Build a Microsoft Teams Rooms image - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/console)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/rooms/console.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
