### ISSUE TITLE
Bandwidth note is out of place

### ISSUE THREAD

**Issue by williamlooney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1034]
This note: "Teams bandwidth handling improves on Skype for Business Online: for a high quality calling or meeting experience (with audio, video, and sharing), Teams requires only 1.2 Mbps. It can also scale up further for super high quality if there is enough available bandwidth. When a Teams request encounters a low bandwidth condition, Teams can quickly readjust bandwidth usage to adapt to available bandwidth" does not relate to CQD and should not be on this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a455280-ea8e-2ddf-2965-60d9dcc0e21d
* Version Independent ID: 7fb320d3-fa69-23fa-113c-53e9d2e11ada
* Content: [Dimensions and measures available in Call Quality Dashboard](https://docs.microsoft.com/en-us/microsoftteams/dimensions-and-measures-available-in-call-quality-dashboard#feedback)
* Content Source: [Teams/dimensions-and-measures-available-in-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/dimensions-and-measures-available-in-call-quality-dashboard.md)
* Service: **skype-for-business-online**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by LolaJacobsen** [comment]
@williamlooney I removed the note. Thanks for the heads up. The update will go live later today.
