### ISSUE TITLE
Page needs to be updated.

### ISSUE THREAD

**Issue by Yeemonjr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10357]
This Part - This setting also affects webinars.

Prerequisites
Verify that you haven’t blocked access to [Viva Engage’s IPs and URLs.](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges)
To allow users in your organization to add Q&A to Teams meetings, you need to confirm that sign-ins for the Office 365 Viva Engage service are enabled in Azure Active Directory. Follow the steps below to confirm that sign-ins are enabled:
Go to the Azure AD admin center > All services > Enterprise Applications > Office 365 Viva Engage > Properties.
For the Enabled for users to sign-in? option, select Yes if necessary. 

This needs to be updated or corrected.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3b814e8-f9e4-7396-b016-62b8bd385585
* Version Independent ID: e3b814e8-f9e4-7396-b016-62b8bd385585
* Content: [Manage Q&A in Teams Meetings - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/manage-qna-for-teams)
* Content Source: [Teams/manage-qna-for-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/manage-qna-for-teams.md)
* Service: **msteams**
* GitHub Login: @wlibebe
* Microsoft Alias: **wlibebe**

**Comment by get-itips** [comment]
Hello @Yeemonjr 
The article already states that it applies to Webinars, it was added in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/56a0ac1554647257e01c73a7a7e926958010ccfa

**Comment by Yeemonjr** [comment]
The issue that there is no setting in Azure AD / Entra to configure permission for Viva Engage. I have searched within an active tenant and not seen it. 

The documentation is around QA for both Engage and Teams Meetings. 

<img width="1888" alt="image" src="https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/97365153/8ad5ea24-aba1-4aff-bb86-3ee1100af3c4">

<img width="1792" alt="image" src="https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/97365153/4073fada-f259-42cc-a58d-86ecd644780c">

Please verify,
 
Thank you,

**Comment by get-itips** [comment]
I found it following Azure AD admin center > All services > Enterprise Applications > Office 365 Viva Engage > Properties but by clearing the filter

**Comment by Yeemonjr** [comment]
I did your step, still no "Office 365 Viva Engage"

<img width="416" alt="image" src="https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/97365153/d0008f97-4466-4af4-a17b-788c2ba7723c">

I found yammer though

<img width="426" alt="image" src="https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/97365153/eeafa85b-f0c5-454e-9ee4-b177fcef6d57">

Thus is this function is rolling out.
