### ISSUE TITLE
Premium Webniar instead of Premium Event

### ISSUE THREAD

**Issue by LennartaeHoefer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10355]
https://learn.microsoft.com/en-us/microsoftteams/enhanced-teams-experience#premium-events
its a bit confusing to name Webinars as Events because it can be easily mixed with Live Events. It would be better to name it Premium Webinars.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a5338e6-ae08-bb92-3769-4af2932bf02c
* Version Independent ID: 7a5338e6-ae08-bb92-3769-4af2932bf02c
* Content: [Microsoft Teams Premium - Overview for administrators - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/enhanced-teams-experience)
* Content Source: [Teams/enhanced-teams-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/enhanced-teams-experience.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hello @LennartaeHoefer 
How are you?
Hope you are doing good.
I understand your feedback, however this term is spread in multiple communications, also in the description it is stated that this is for webinars.
I'll also pass this feedback on.
Thank you!
