### ISSUE TITLE
Support for Static Tabs in "NEW" Teams client?

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10351]
[Enter feedback here]
Not listed in the Known Issues but the static tabs configured in Custom Apps (via Manifest files) are not displaying in the new Teams client while they display fine in the legacy clients.

What is the timeline for support of this feature as it is rendering many LOB apps ineffective.

If it is supported already then does it require any changes to manifest.json for the staticTabs to be recognized?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Version Independent ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Content: [Known issues in the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-known-issues)
* Content Source: [Teams/new-teams-known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-known-issues.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@GauravES 
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by GauravES** [comment]
I dont think this is a tenant specific issue but a general issue with support for Static Tabs in the new teams client.   We have reviewed this on several tenants where the existing/Legacy teams client displays the Static Tabs  in Teams Apps/Bots while the new one does not.     As such this is a candidate for explicitly calling out in the Known Issues. Perhaps refer to product team for clarification?
