### ISSUE TITLE
Teams Rooms for Android - Wrong Product

### ISSUE THREAD

**Issue by kreischl68** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10354]
[We are setting Logitech Roommate device and found this page to setup auto-answer.  The documentation says "Microsoft Teams Rooms on Android" which is what this device is.  We also had a meeting with Logitech since it did not work and they confirmed this is a missing feature for video calls on Teams Room devices.  I am wondering if this article is incorrect when it said Room systems.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ffdd3ead-73c3-b335-0d98-b197e06f7fe9
* Version Independent ID: ffdd3ead-73c3-b335-0d98-b197e06f7fe9
* Content: [Set up auto answer for Teams Android devices - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/set-up-auto-answer-on-teams-android)
* Content Source: [Teams/set-up-auto-answer-on-teams-android.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/set-up-auto-answer-on-teams-android.md)
* Service: **msteams**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by get-itips** [comment]
@kreischl68 were you able to see my comment here? Thanks

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
