### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by volquar3** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10356]
[Enter feedback here]
Typo Here: Ability to build Teams personsal apps usings Adaptive cards
Assuming should say personal

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Version Independent ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Content: [The new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin)
* Content Source: [Teams/new-teams-desktop-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-desktop-admin.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thank you!
Fixed in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/3bab2cfec45ccc09b40bf40976a229e06da441e8
