### ISSUE TITLE
Add warning about Federated vs. Managed domain in Direct Routing planning/config guidance

### ISSUE THREAD

**Issue by davidjfriedman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10365]
The document states "In addition to the domain registered in your tenant, it's important that there's a user with that domain and an assigned E3 or E5 license".

In some situations, IT admins may be unable to assign a user to a domain, such as with a subdomain of AuthenticationType "Federated".  In such cases, it may be necessary to change the AuthenticationType from Federated to Managed for the subdomain.  Ref: https://learn.microsoft.com/en-us/azure/active-directory/enterprise-users/domains-verify-custom-subdomain

It would be ideal for the service to output a graceful error to guide the end user in these situations.  Additionally, suggest adding warning verbiage to this document and/or https://learn.microsoft.com/en-us/microsoftteams/direct-routing-plan to reduce chance of IT admins running into this.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad7d5051-1177-c5cf-bf28-8639d7b6fbd1
* Version Independent ID: 2a9aa4e1-3767-cd46-50fe-f9dd8b0997be
* Content: [Connect your Session Border Controller (SBC) to Direct Routing - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/direct-routing-connect-the-sbc)
* Content Source: [Teams/direct-routing-connect-the-sbc.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/direct-routing-connect-the-sbc.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @davidjfriedman How are you?
Are you a Microsoft employee? If so, can you link your GH to your Microsoft account?
I'll propose to add that to the article.
