### ISSUE TITLE
Unclear documentation about Approvals history retention 

### ISSUE THREAD

**Issue by KhisteMahesh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10366]
https://learn.microsoft.com/en-us/microsoftteams/approval-admin#retention-policy 
It unclear that for how many days Approvals history is available to users ?It mentions that its stored in Dataverse and Forms database but retention duration is unclear.
I would suggest better clarification  on following topics would help users and admins:
 Approvals responses data retention , Approval custom templates retention, Approvals history shown in Approvals hub and Approvals flow retention ( for ex Approval is sent to a person and if that person doesn't approve in 30 days , will that flow be still available after that or broke / error out , what error will be showed ?)

**Comment by get-itips** [comment]
Hello @KhisteMahesh 
I'm working on this

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by get-itips** [comment]
Re-Opening this one

**Comment by get-itips** [comment]
Article has been updated.
Thanks
