### ISSUE TITLE
List AvePoint in the partner list for backuping Teams Chat

### ISSUE THREAD

**Issue by jeffangama** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10368]
Hi

AvePoint is also Certified for Microsoft Teams backup, using Cloud Backup for Microsoft 365.
Here is the product description : https://www.avepoint.com/products/cloud/backup/microsoft-office-365-backup
Cloud Backup for Microsoft 365

Is it possible to add the option on the page ?
https://learn.microsoft.com/en-us/microsoftteams/export-teams-content#general-usagemodel-b-scenarios

Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6eb2244d-b82d-0559-0255-ac0cb7ce05e3
* Version Independent ID: e3a7a842-7efe-40db-e3c7-da56d7b24c02
* Content: [Export content with the Microsoft Teams Export APIs - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/export-teams-content)
* Content Source: [Teams/export-teams-content.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/export-teams-content.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
I've managed to pass the feedback along, thank you
