### ISSUE TITLE
What are the minimam licensing needs for Updates App

### ISSUE THREAD

**Issue by balajinarni** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10364]
Is there a place to indicate what are the licensing needs to use Updates App? Can a frontline license user can use Updates App? It would be helpful if you can add those limitations? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c19d4972-fa39-2908-c33c-f7e1a84d06c5
* Version Independent ID: c19d4972-fa39-2908-c33c-f7e1a84d06c5
* Content: [Manage the Updates app for your organization - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-updates-app#give-feedback-or-report-an-issue)
* Content Source: [Teams/manage-updates-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/manage-updates-app.md)
* Service: **msteams**
* GitHub Login: @Lana-Chin
* Microsoft Alias: **v-chinlana**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
