### ISSUE TITLE
Missing Slide decks

### ISSUE THREAD

**Issue by Atreidae** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10362]
Hi Team.
Looks like a lot of the Slidedecks from the [technical training section](https://learn.microsoft.com/en-us/MicrosoftTeams/itadmin-readiness#technical-training) are missing from the Github Repo. 
The links resolve to aka.ms links, but the redirection on the aka.ms link points to files that no longer exist in the public fork of the GitHub Repo.

Here are a few examples
| Text                                     | Slidedeck Aka.ms link                         | Links to                                                                                                                           | Result |
|------------------------------------------|-----------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------|--------|
| Foundations - Core components            | https://aka.ms/teams-foundations-deck         | https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/downloads/SkillsEnablement_Teams_Foundations.pptx   | 404    |
| Direct routing                           | https://aka.ms/teams-direct-routing-deck      | https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/downloads/SkillsEnablement_Direct_Routing.pptx      | 404    |
| Governance, management, and lifecycle    | https://aka.ms/teams-governance-deck          | https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/downloads/SkillsEnablement_Governance.pptx          | 404    |
| Live events                              | https://aka.ms/teams-live-events-deck         | https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/downloads/SkillsEnablement_Live-Events.pptx         | 404    |
| Phone system introduction                | https://aka.ms/teams-phone-system-deck        | https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/downloads/SkillsEnablement_Phone_System.pptx        | 404    |
| Media - Why meetings are simple          | https://aka.ms/media-in-teams-deck            | https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/downloads/SkillsEnablement_Media_in_Teams.pptx      | 404    |
| Media - Media flow                       | https://aka.ms/teams-media-flows-deck         | https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/downloads/networking-media-flows-v2-part2.pptx      | 404    |
| Meetings introduction                    | https://aka.ms/teams-meetings-intro-deck      | https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/downloads/SkillsEnablement_Meetings.pptx            | 404    |
| Security & Compliance                    | https://aka.ms/teams-security-compliance-deck | https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/downloads/SkillsEnablement_Security_Compliance.pptx | 404    |
| Upgrade from Skype for Business to Teams | https://aka.ms/teams-upgrade-deck             | https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/downloads/SkillsEnablement_Upgrade.pptx             | 404    |
| Windows desktop client                   | https://aka.ms/teams-clients-deck             | https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/downloads/SkillsEnablement_DesktopClients.pptx      | 404    |

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 752a6dc8-4018-88aa-faa4-c07c1c0a1719
* Version Independent ID: 7d6d29c5-f699-2abd-71c2-7c49061dd068
* Content: [Admin training resources - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/itadmin-readiness)
* Content Source: [Teams/ITAdmin-readiness.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/ITAdmin-readiness.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Please see https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/10334#issuecomment-1699669855
