### ISSUE TITLE
"caller ID" mentioned twice

### ISSUE THREAD

**Issue by saiful-suherman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10369]
"caller ID" is mentioned twice under **Teams Phone Standard** in the section: [Which capabilities can I get with add-on licenses?
](https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: abae7324-861d-7ca7-7239-a5df8fd927d5
* Version Independent ID: 8a30bd2f-9bc3-a0a8-8b31-d53836ead4d0
* Content: [Microsoft Teams add-on licenses - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing)
* Content Source: [Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by Venkat-Munta** [comment]
@saiful-suherman #10372 
Created a pull request for this.
Thank you for the info.

**Comment by get-itips** [comment]
PR was merged, thanks
