### ISSUE TITLE
Is it possible to limit access to read only CQD somehow?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10371]
Hi,

If we should enable user to read only CQD logs and not reading other audit logs as it says on the page:
_In addition to reading CQD reports, the Reports Reader **can view all the activity reports**_

So is this possible somehow?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb8d8b48-561b-6817-1ce0-4b2aedc261a8
* Version Independent ID: dfd5cf4a-509a-3ed1-0267-6281c251fbef
* Content: [Call Quality Dashboard (CQD) setup - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/turning-on-and-using-call-quality-dashboard)
* Content Source: [Teams/turning-on-and-using-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/turning-on-and-using-call-quality-dashboard.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @Petri-X 
How are you?
Let me know if I understand correctly, do you mean a Reports Reader that has access to **only** CQD?

**Comment by Petri-X** [comment]
Yes I was wondering if there can be fine tuned the accesses. But I believe the correct roles are:
**Teams Communications Support Engineer** and 
**Teams Communications Support Specialist**

Source: [Teams roles and capabilities](https://learn.microsoft.com/en-us/microsoftteams/using-admin-roles#teams-roles-and-capabilities)
