### ISSUE TITLE
Typo in sbc address references

### ISSUE THREAD

**Issue by ashokgop** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10379]
[Enter feedback here]
The reference to sbc1.contoso.biz, sbc2.contoso.biz, sbc3.contoso.biz and sbc4.contoso.biz in the section "Example 1: Voice routing with one PSTN usage" should instead refer to the sbc's as sbc1.contoso.com, sbc2.contoso.com, sbc3.contoso.com and sbc4.contoso.com to keep it consistent with the diagram that shows two examples of voice routing policies.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d277994f-f0bb-ed3b-a94c-460c7f033abf
* Version Independent ID: 7a2b1511-a35a-18e4-611a-db0093d034b4
* Content: [Configure call routing for Direct Routing - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/direct-routing-voice-routing?source=docs)
* Content Source: [Teams/direct-routing-voice-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/direct-routing-voice-routing.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @ashokgop Thanks for your feedback, I'm already on this.
