### ISSUE TITLE
Duplicate content

### ISSUE THREAD

**Issue by alihirsch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1037]
At the end of the section "Mobile clients", the last paragraph is a duplicate of the earlier "Decision Point" paragraph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/get-clients#desktop-client)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by MishaTravis** [comment]
@alihirsch - Thank you for submitting this feedback.

I was able to get this into the backlog for the Teams team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by LolaJacobsen** [comment]
Fixed - will go live later today. Thanks, @alihirsch
