### ISSUE TITLE
Known issues and when they apply are a bit vague

### ISSUE THREAD

**Issue by patrichard** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10387]
The list of known issues should point out WHEN those issues apply. For example, the last option about Auto Attendants and Call Queues I believe only applies during an Internet outage. The way it's worded now could be inferred as to mean those features NEVER work if an SBA is in the infrastructure.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dbab466f-88f8-302a-7cda-d53bc743e831
* Version Independent ID: b5634fb3-6627-3fcd-101c-0ebc419d7b19
* Content: [Local Media Optimization for Direct Routing - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/direct-routing-media-optimization#known-issues)
* Content Source: [Teams/direct-routing-media-optimization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/direct-routing-media-optimization.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @patrichard Pat,

Probably you refer to this

"To support Local Media Optimization and Media Bypass in these scenarios, Calls Queues must be configured for transfer mode (Conference Mode = OFF)."

https://learn.microsoft.com/en-us/microsoftteams/location-based-routing-plan#inbound-calls-through-voice-apps-auto-attendant-or-call-queue

Please let me know if I understood you correctly,
