### ISSUE TITLE
ByDesign | Unable to create chat thread if external users with Teams accounts not managed by org is set to "OFF"

### ISSUE THREAD

**Issue by Aamir-Baig** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10395]
Hi Team,

I would like to raise a request to update this document, recently we had an internal ICM where it was identified that there is a by-design behavior which contradicts to the said document. i.e.

When the following Admin Center Policies are set:

* People in my organization can communicate with Teams users whose accounts aren't managed by an organization = **ON**

* External users with Teams accounts not managed by an organization can contact users in my organization = **OFF**

The expected behavior is that in-tenant users can initiate chats with unmanaged users but that unmanaged users cannot initiate chats with in-tenant users.

However, the current by-design behavior is that external users get an accept/block banner, but then get an error message when click on accept. Refer the below image, it would be good to add this as a note so that the admin's making changes are aware of this.

![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/87613995/61895e70-b690-4431-8683-accfd1caf6c2)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [IT Admins - Manage external meetings and chat with people and organizations using Microsoft identities - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/trusted-organizations-external-meetings-chat?tabs=organization-settings#manage-chat-with-external-teams-users-not-managed-by-an-organization)
* Content Source: [Teams/trusted-organizations-external-meetings-chat.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/trusted-organizations-external-meetings-chat.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
Handling this internally.
