### ISSUE TITLE
Meeting Notes?

### ISSUE THREAD

**Issue by DontNeedNoGit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10398]
This page makes no mention that anonymous external users cannot access meeting notes in Teams. Is that a bug that needs reported to Microsoft Support or is that information missing from this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 605b38b9-4b1c-567d-81e9-9480d7850daa
* Version Independent ID: 605b38b9-4b1c-567d-81e9-9480d7850daa
* Content: [Manage anonymous participant access to Teams meetings (IT admins) - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/anonymous-users-in-meetings)
* Content Source: [Teams/anonymous-users-in-meetings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/anonymous-users-in-meetings.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @DontNeedNoGit how are you?
Do you refer to *Collaborative* Meeting notes? (the loop component)
Thanks for clarifying.

**Comment by DontNeedNoGit** [comment]
Yes, the collaborative meeting notes that are Loop components. They seem to be entirely inaccessible to anyone otuside of our company. That should be listed in big bold letters / maybe in one of the purple boxes. 

I don't know what developer added a meeting notes functionality that completely leaves external participants out in the cold, but someone should roll back that implementation until Loop compononets are available to external meeting participants. 

Thank you for updating the article to reflect this.

**Comment by get-itips** [comment]
Hello @DontNeedNoGit 
As far as I know, collab meeting notes are still public preview feature, in the TC announcement, it is noted that limitation https://techcommunity.microsoft.com/t5/microsoft-teams-public-preview/now-in-public-preview-amp-targeted-release-collaborative-meeting/m-p/3848392

Once it gets to GA, it will probably added to Learn documentation with said limitations.
Thank you for your feedback

**Comment by DontNeedNoGit** [comment]
The article is out of date. I have Preview Features disabled in the Global (org-wide) policy in my tenant and this is the only Meeting Notes option that we have. It is now in GA and _your_ article is therefore out of date.

**Comment by get-itips** [comment]
@DontNeedNoGit I'm proposing to add a note to the article, if it gets approval, it will be in the published version of the article.
Thank you
