### ISSUE TITLE
RealTimeCallQueueMetricsPermission query

### ISSUE THREAD

**Issue by petermccrindle** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10393]
[I am wondering, when this becomes available, will we able to view how many calls are waiting in the relevant queue?  Currently, my understanding is that call data is only made available 15 minutes after the call ends?  SO I am wondering if this is due to change?]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4ab419c-9686-8abe-d1f3-85806a25e630
* Version Independent ID: a4ab419c-9686-8abe-d1f3-85806a25e630
* Content: [Manage voice applications policies for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-US/microsoftteams/manage-voice-applications-policies)
* Content Source: [Teams/manage-voice-applications-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/manage-voice-applications-policies.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
