### ISSUE TITLE
What about external members?

### ISSUE THREAD

**Issue by fei0x** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10391]
I am trying to understand what is trying to be conveyed here about external members. Particularly in the section: "Licensing for guest access". Perhaps you can improve the documentation to be more explicit?

1. Is it correct to assume, that you mean External Users here and not Guests?
2. If I have external member in my tenant (perhaps by performing a "Convert to External User" action on an internal member)? Can this person use teams without an explicit license? or does he count as a 'guest' for the MAU pricing?
3. What do you mean when you say teams doesn't support converting users? If I convert a user from member to guest or vice versa using PowerShell or the Azure portal does that mean this user can no longer use teams? What if I tenant sync an external user as a member, but I really wanted a guest, so I convert them, does that mean they can no longer use teams? what specifically does teams not do?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2492e210-08f9-a476-97ec-008926def961
* Version Independent ID: adcb0dd9-4a3c-b665-6e34-ce3276c89b4d
* Content: [Guest access in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/guest-access#licensing-for-guest-access)
* Content Source: [Teams/guest-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/guest-access.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @fei0x 
How are you?
Can you please expand or detail a little bit more why would you think it is referring to an external user and not guest?
Thank you,

**Comment by fei0x** [comment]
> Hello @fei0x
> How are you?
> Can you please expand or detail a little bit more why would you think it is referring to an external user and not guest?
> Thank you,

As far as I know, there are no licenses that are based on guests, only external identities. 

These two links describe how pricing works for external users (not guests):

https://learn.microsoft.com/en-us/azure/active-directory/external-identities/external-identities-pricing#about-monthly-active-users-mau-billing (which you reference in the article)

https://azure.microsoft.com/en-ca/pricing/details/active-directory-external-identities/  (linked from the above link. notably, this page doesn’t use the word Guest at all.)

If there is some other license pertaining to guests that you’re referencing, I’d love to see the documentation for it.

**Comment by get-itips** [comment]
Hello @fei0x 
I checked internally and the recommendation is to open a support request from your tenant to clarify this.
Thank you for your feedback,
