### ISSUE TITLE
Microsoft Teams for Education

### ISSUE THREAD

**Issue by DwayneSelsig** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10397]
I see the option to create a shared channel on a Microsoft Team. I don't see the option to create a shared channel on a Microsoft Teams for Education in the same tenant as team owner. Is this by design? I can't find any documentation on that.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82e6deaf-68f5-e3c9-7259-775ed7662d85
* Version Independent ID: 82e6deaf-68f5-e3c9-7259-775ed7662d85
* Content: [Shared channels in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/shared-channels#adding-and-removing-owners-and-members)
* Content Source: [Teams/shared-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/shared-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @DwayneSelsig 
From what I could test, shared channels are not available in Class type teams. Hope that answers your question.
