### ISSUE TITLE
Regex limitations on the Dialed Number Pattern.

### ISSUE THREAD

**Issue by Korbyn72** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10392]
How filtered can we be on the Dialed Number Pattern for voice routes?  I'm trying to use something like:  ^\+1(\d{10});ext=(\d{5})$  to work for routing to a specific direct routing SBC, or ^\+12363175552;ext=(\d{5})$  but it seems to hit the ; and ignore anything after that.  Seems that there are limits to the regex on this field, what are they?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d277994f-f0bb-ed3b-a94c-460c7f033abf
* Version Independent ID: 7a2b1511-a35a-18e4-611a-db0093d034b4
* Content: [Configure call routing for Direct Routing - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/direct-routing-voice-routing)
* Content Source: [Teams/direct-routing-voice-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/direct-routing-voice-routing.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
