### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by Vindicator007** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10403]
The article seems to be out of date.  The new client is available in GCC.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Version Independent ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Content: [The new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin)
* Content Source: [Teams/new-teams-desktop-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-desktop-admin.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @Vindicator007 Vin, how are you?
The [adoption page](https://adoption.microsoft.com/en-us/new-microsoft-teams/) still lists that cloud as coming later, are you a GCC customer and already see it available and you could use it?
Thanks

**Comment by Vindicator007** [comment]
> Hello @Vindicator007 Vin, how are you? The [adoption page](https://adoption.microsoft.com/en-us/new-microsoft-teams/) still lists that cloud as coming later, are you a GCC customer and already see it available and you could use it? Thanks

Yes, I'm a GCC customer and can use New Teams.

**Comment by JoanneHendrickson** [comment]
@Vindicator007  @get-itips  

  Hi all!  This article is being actively updated, including the dates about GCC, the public preview, etc.  The changes should be reflected by tomorrow.  Thanks.  Joanne

**Comment by tiburd** [comment]
@JoanneHendrickson 
Thank you! Closing this issue.
