### ISSUE TITLE
Inaccuracy

### ISSUE THREAD

**Issue by JoshJ-MSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1040]
Are we sure this is accurate:
"If you use Lync 2013 Mobile on Apple devices, you no longer need push notification."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9ea7778-a0ea-1720-dcc1-cb2cb183f327
* Version Independent ID: 4441ef1c-1597-598c-8ffb-b8af139e0025
* Content: [Lync Server 2013: Configuring for push notifications](https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-configuring-for-push-notifications)
* Content Source: [Lync/LyncServer/lync-server-2013-configuring-for-push-notifications.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Lync/LyncServer/lync-server-2013-configuring-for-push-notifications.md)
* GitHub Login: @dstrome2

**Comment by MishaTravis** [comment]
@JoshJ-MSFT - Thanks for submitting this feedback.

I was able to get this into the backlog for the team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by LolaJacobsen** [comment]
@JoshJ-MSFT closing as won't fix.
