### ISSUE TITLE
File Sharing Information

### ISSUE THREAD

**Issue by DontNeedNoGit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10401]
Please expand on the capability to share files and folders with people not in the channel. There are limitations in "shared channels" (despite what the name implies), but I believe file and folder sharing is fully possible from "Private channels" right? This page only barely touches on this. Are there any limitations (e.g. only inside the company? Tenant Guests? Microsoft accounts? Unknown/Anonymous external user? What about types of files or folders? Your page only really mentiones OneNote notebooks.), or can anything in a Private channel be shared with all of these user types? There's conflicting information in this article and I encourage someone familiar with this product to read through and look for ways to add clarity on this issue and around these questions. 

There's one pink box in particular that seems to reference Shared channel sites, but it's not clear if it means the Private channel's shared site. _“Only people with owner or member permissions in the channel will have access to content in the shared channel site."_
The confusion about "shared channel" in that statement is one issue, but this sentence also implies "content" isn't able to be shared. This is one clear example of 'conflicting information' that I mentioned. But I request that you add more information about file and folder sharing capabilities. There's even a section for it, but you only discuss OneNote notebooks there, and include this statement: "Creating a team OneNote notebook is the same as sharing access to any other item in a private channel SharePoint site with a user." without any explanation of what "sharing access to any other item in a private channel" means.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/private-channels)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@DontNeedNoGit I updated the article with some additional information to address your questions.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
