### ISSUE TITLE
Need samples of JSON and more

### ISSUE THREAD

**Issue by mjw913** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10402]
Could not get Postman to work using the documentation provided
Would be very helpful to have JSON samples that the VAAC gets.  
Would be helpful to have better descriptions of the fields, possible values, and samples
Need more information on the different permissions needed to use the VaaC

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f10dcb86-8529-c107-a208-36e09a27cd9b
* Version Independent ID: f10dcb86-8529-c107-a208-36e09a27cd9b
* Content: [Auto attendant and Call queue historical reports - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/aa-cq-cqd-historical-reports#accessing-vaac-outside-of-power-bi)
* Content Source: [Teams/aa-cq-cqd-historical-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/aa-cq-cqd-historical-reports.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by get-itips** [comment]
Hello @mjw913 

how are you?

**_Could not get Postman to work using the documentation provided_**

We just followed the instructions in the documentation and it worked, we don't have the specific errors that you received.

**_Would be very helpful to have JSON samples that the VAAC gets._**

There is an example of a valid query in the documentation: https://learn.microsoft.com/en-us/microsoftteams/aa-cq-cqd-historical-reports#constructing-a-valid-query
The actual queries that Power BI performs are available in Power BI for further samples.

**_Would be helpful to have better descriptions of the fields, possible values, and samples_**

Every field that is available is itemized here: https://learn.microsoft.com/en-us/microsoftteams/aa-cq-cqd-historical-reports#dimensions-and-measurements

 Each field is marked with its type: Text, Whole Number, DateTime, Boolean, etc.

**_Need more information on the different permissions needed to use the VaaC_**

https://learn.microsoft.com/en-us/microsoftteams/aa-cq-cqd-historical-reports#permissions-to-access-the-cqd-pipeline


Hope this information helps you,

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
