### ISSUE TITLE
CodecPriority is not valid/used anymore

### ISSUE THREAD

**Issue by Adminiuga** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10418]
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/16a982cbc165b40e39f2f4c7713d500462a2c77c/Teams/direct-routing-connect-the-sbc.md?plain=1#L154-L155 Mention "CodecPriority" and "ExcludedCodec" which are no longer valid output, as those parameters were removed in https://github.com/MicrosoftDocs/office-docs-powershell/pull/8869

++ @FilippSe for visibility

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad7d5051-1177-c5cf-bf28-8639d7b6fbd1
* Version Independent ID: 2a9aa4e1-3767-cd46-50fe-f9dd8b0997be
* Content: [Connect your Session Border Controller (SBC) to Direct Routing - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/direct-routing-connect-the-sbc)
* Content Source: [Teams/direct-routing-connect-the-sbc.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/direct-routing-connect-the-sbc.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Thanks for your feedback
