### ISSUE TITLE
Teams channel 

### ISSUE THREAD

**Issue by akkawamu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10410]
please add comment  about Teams channel support client .
Mobile client and Phone device cannnot use the Collaborative Calling interface to mobile clients.
but these can user standard call queues and make outbound call using dynamic call ID.

-----------------------
ORIGINAL SOURCE.:ICM 311990315
Colin Longman answered following 
Q:Currently, mobile clients can receive calls,  can users continue to receive incoming calls on their mobile clients?
A: agents on mobile clients can be part of collaborative calling queues (and standard call queues), can make outbound calls using dynamic clid but they won't have the the collaborative calling user interface.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b755d9ae-13ac-019f-f5f4-a95b1eee2989
* Version Independent ID: f7afd8ad-e6e0-6c79-aed1-4ee87d48ba12
* Content: [Create a Call queue in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue?tabs=call-answering#teams-channel)
* Content Source: [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/create-a-phone-system-call-queue.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by get-itips** [comment]
Discussed this with @CLYVR and this is already documented in https://learn.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue?tabs=general-info#call-queue-feature-compatibility
