### ISSUE TITLE
Serial routing method needs more clear explanation

### ISSUE THREAD

**Issue by tiagoroxo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10413]
Description:         
Looking into our documentation, we have contradicting information, we can read:

“Serial routing rings all call agents one by one in the order specified in the Call agents list. "

And we can also read:

“4. It's not possible to set the order the agents are presented with calls.”

Suggestion:

I believe the documentation should include an better explanation on point number 4, maybe adding that sorting with DL/Group is done via alphabetical order automatically and that's the reason why you cannot sort. And/or mention that order agents in this method is possible if you add them one by one in the list, and if you add a DL/Group, it's not possible to sort them manually.

Documentation:

[https://learn.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue?tabs=agent-selection#step-4-select-your-agent-routing-options](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fmicrosoftteams%2Fcreate-a-phone-system-call-queue%3Ftabs%3Dagent-selection%23step-4-select-your-agent-routing-options&data=05%7C01%7Ctiago.roxo%40microsoft.com%7C4e94d44c85f7478afe0908dbbdd9e840%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638312515853651151%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WH%2BnYvrp5DAuBxy2z6fiPuppYgJRtBGV1kKhr2xrn7s%3D&reserved=0)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b755d9ae-13ac-019f-f5f4-a95b1eee2989
* Version Independent ID: f7afd8ad-e6e0-6c79-aed1-4ee87d48ba12
* Content: [Create a Call queue in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue?tabs=agent-selection#step-4-select-your-agent-routing-options)
* Content Source: [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/create-a-phone-system-call-queue.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by get-itips** [comment]
Hello @tiagoroxo 
The sentence you propose is very similar to the previous sentence that this article had so I'm trying to understand why it was changed to the current one. I'll get back when I have details.
Thanks

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
