### ISSUE TITLE
How to get to the Teams Admin Center ?

### ISSUE THREAD

**Issue by bcraigie** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10412]
[Enter feedback here]
There's always the first step missing in these documents - how to get there in the first place.  _How_ do we initially get to the Teams Admin Center ?  What's the web address?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b51b67a-d89c-723f-3520-87cb2dc93b90
* Version Independent ID: 78d10cbc-d75b-2b02-d49c-2c3fe1579807
* Content: [Manage teams in the Microsoft Teams admin center - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-teams-in-modern-portal)
* Content Source: [Teams/manage-teams-in-modern-portal.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/manage-teams-in-modern-portal.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @bcraigie Brian,
It's at the beginning of the article

> You can access the admin center at https://admin.teams.microsoft.com/
