### ISSUE TITLE
Incorrect URL ATA & SIP Gateway

### ISSUE THREAD

**Issue by Lolu8080** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10426]
URL https://noam.ipp.sdg.teams.microsoft.com/tenantid/<your-tenant-ID-guid>/mac.in should be https://noam.ipp.sdg.teams.microsoft.com/tenantid/%3Cyour-tenant-ID-guid%3E/mac.ini - missing the last i in 'ini' - thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 05173ea8-db7c-a20d-3783-178b3d649190
* Version Independent ID: 05173ea8-db7c-a20d-3783-178b3d649190
* Content: [Configure SIP Gateway - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/sip-gateway-configure)
* Content Source: [Teams/sip-gateway-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/sip-gateway-configure.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by lindspea** [comment]
Hi @Lolu8080 thank you for reaching out. I've just had a look at the article, and it seems it is reflecting correctly now. Please confirm from your side, and let me know if there is anything else I can help with.

**Comment by Lolu8080** [comment]
Hi Lindsay,

It all looks good now.

Thanks & Regards

Lolu

**Comment by lindspea** [comment]
Thanks for letting me know @Lolu8080. 
@scanum this can be closed thank you.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
