### ISSUE TITLE
Misleading wording on international calling plans

### ISSUE THREAD

**Issue by RobC-CTL** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10427]
On the page the international calling plan detail is:

_"With the International Calling Plan, licensed users can call out to numbers located in the country/region where their Microsoft 365 license is assigned to the user based on the user's location, and to international numbers in [196 countries/regions]"_

This reads like you only need to license the user with the International Calling plan license and that will allow them to dial domestic numbers (based on their local in M365) and international numbers.  However this is not the case, for example if a user was based in the UK and they needed to call UK and US numbers they would need a Domestic Calling plan AND a International Calling plan to be able to do this.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 33bfc660-573d-b57e-8b67-6aa1fbe820ad
* Version Independent ID: 53318fba-10e9-cd4b-f0ee-397cd10e8c0c
* Content: [Microsoft Calling Plans for Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/calling-plans-for-office-365)
* Content Source: [Teams/calling-plans-for-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/calling-plans-for-office-365.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @RobC-CTL I'm working on this

**Comment by get-itips** [comment]
Hello @RobC-CTL Rob,
The international calling plan includes Domestic calling.

https://www.microsoft.com/en-us/microsoft-teams/compare-microsoft-teams-bundle-options

I'll try to clarify the sentence.

**Comment by RobC-CTL** [comment]
Hi @get-itips 

Thanks for looking into this.  The bundles you link to are for Teams Essentials.  If you are using any of the Business packages this includes Teams so you wouldn't need "Teams Essentials" .  When you have "full" Teams you have to purchase a Teams Phone license as well as a Calling plan.  There are three Business SKUs as far as I can see "Domestic Calling", "International Calling" and there is also a bundle that is "Domestic and International" which is approximately the same costs as the the two individual plans together.  Teams licensing is a complex beast (as it most licensing with MS) so I can see where the original wording does make sense but only for the one SKU.  I've not got involved with Enterprise so there could me more complications there :)
