### ISSUE TITLE
DFS

### ISSUE THREAD

**Issue by ThomasBIDAULT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1043]
It would be nice to have precision on DFS parameter supported : 
- Do we support DFS-R + DFS-N ?
- Should we use specific targeting for DFS target ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3ca816c-d7cf-500e-4710-8693b584b5ab
* Version Independent ID: 511bacc3-dd79-52bd-a4a2-baa667693b68
* Content: [File sharing high availability in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/high-availability-and-disaster-recovery/file-sharing?toc=/SkypeForBusiness/toc.json#feedback)
* Content Source: [Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/file-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/file-sharing.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by LolaJacobsen** [comment]
@MicrosoftHeidi - can you handle this one please? I assigned the related VSO item to you - 2691961

**Comment by mregaya** [comment]
Hello,

Do we have any update regarding this query ? 

Thank you.

**Comment by MicrosoftHeidi** [comment]
Thanks for your follow-up. This is not in my current sprint, I will be looking at it in CY19. I need to identify a good resource to discuss this with.

**Comment by dariomws306** [comment]
Hi @ThomasBIDAULT , you should use DFSN and DFSR, install both roles, etc. The article redirect you to https://go.microsoft.com/fwlink/?LinkId=524384 which explains this.

**Comment by scanum** [comment]
@ThomasBIDAULT  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
