### ISSUE TITLE
Relation between Device Tag and Policy "tag"

### ISSUE THREAD

**Issue by samuelhuiyp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10436]
Hi There, 

Is there any relation between the device tag and the identity from Teams Phone Policy Powershell Get-CsTeamsIPPhonePolicy ?

Custom policies showed as "tag:xxxxx", do that means I setup and assign a device tag as "xxxxx" and the device will have the policy applied?  Or if there have any usage about the device tag beside of filtering devices from the view?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
