### ISSUE TITLE
Incorrect year in the "Important" box under Rooms View

### ISSUE THREAD

**Issue by NoelFairclough** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10430]
[Enter feedback here]
The 2nd bullet point in the important box has the wrong year.

"Starting October 2, 2923 all devices without Pro or Premium licenses assigned to them will lose access to the pro management capabilities until valid licenses are assigned to them"

I believe it should be 2023.  Unless it really is 900 years notice. :o

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing#rooms-view)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/rooms/rooms-licensing.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by lindspea** [comment]
@NoelFairclough thank you for reaching out and helping to improve Microsoft Docs. It looks like the error has been fixed in the interim. Please can you have a look to confirm from your side. Thanks again.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
