### ISSUE TITLE
Self Contradicting

### ISSUE THREAD

**Issue by JoshJ-MSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1044]
From a link within this article:   Dual or multi-homed configurations are not supported for Front End Servers

Yet this article appears to be giving instructions on how to do just that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a8b25c0-a81d-44e1-e0fb-b5f2ac6e1f66
* Version Independent ID: 202330a0-4da0-c1c2-8241-c85ebc6d7b52
* Content: [Configure IP address types in Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/network-requirements/ip-address-types)
* Content Source: [Skype/SfbServer/plan-your-deployment/network-requirements/ip-address-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/network-requirements/ip-address-types.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by LolaJacobsen** [comment]
Back to @jambirk for incorporating the changes from Carolyn Blanding (see VSO 2691975)

**Comment by scanum** [comment]
@jambirk Any updates on this issue? Thanks!

**Comment by jambirk** [comment]
Looks like the needed update was merged a while ago. Closing.
