### ISSUE TITLE
Wrong Slash

### ISSUE THREAD

**Issue by benhbom** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10442]
In Step 1, Option A, point 3, the slash in the command is the wrong way. It should be as per the screenshot in point 4

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b73fb04-90e1-de2e-e81d-3495c004b2b5
* Version Independent ID: 4b73fb04-90e1-de2e-e81d-3495c004b2b5
* Content: [Bulk deploy the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-bulk-install-client)
* Content Source: [Teams/new-teams-bulk-install-client.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-bulk-install-client.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by lindspea** [comment]
@benhbom thank you for reaching out and helping to improve Microsoft Docs. I have corrected the issue. It should reflect once the PR has been merged. Thanks again.

**Comment by JoanneHendrickson** [comment]
@benhbom @jyotsnaravikumar   This has been corrected.
