### ISSUE TITLE
What does "Microsoft Controlled" mean for Use new Teams client?

### ISSUE THREAD

**Issue by matthewjlevy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10443]
This documentation doesn't cover the setting "Use new Teams client" and what each of the options mean.
I see in my tenant there are currently four options:

1. Not enabled
2. Classic Teams as default
3. Microsoft Controlled
4. New Teams as default

I would like to know what Microsoft Controlled means in this case and where I can refer customers to check what it means if it is likely to change in the future?

I would also like to know what "Not enabled" means, but I am going to test that myself.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5f1cdd1-09ff-f95d-6d50-e7880d34020f
* Version Independent ID: 59219640-305b-30c1-bc10-87e2633d95db
* Content: [Public preview in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/public-preview-doc-updates)
* Content Source: [Teams/public-preview-doc-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/public-preview-doc-updates.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum*** 
*

**Comment by MikePlumleyMSFT** [comment]
@matthewjlevy the new Teams client settings are covered in [Upgrade to the new Teams using policies](https://learn.microsoft.com/microsoftteams/new-teams-deploy-using-policies).

**Comment by matthewjlevy** [comment]
Thanks @MikePlumleyMSFT
