### ISSUE TITLE
Incorrect RegEx

### ISSUE THREAD

**Issue by bhargavshukla** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10449]
https://learn.microsoft.com/en-us/microsoftteams/block-inbound-calls

The RegEx in the first example on the page states: "New-CsInboundBlockedNumberPattern -Name "BlockRange1" -Enabled $True -Description "Block Contoso" -Pattern "^\+?1312555\d{4}$"

The example states: "In the next example, the tenant administrator wants to block all calls coming from the number 1 (412) 555-1234. To turn on the number pattern, the Enabled parameter is set to True."

The RegEx doesn't match 412-555 number in the example given, it only works for numbers starting with 312-555. Please correct the article so description matches the example.

**Comment by bhargavshukla** [comment]
Hello @JensTrier,

You are correct! I read the example and then I read the explanation below, completely missing the fact that the description is for next example, not the prior... now I feel embarrassed!

Cheers,
Bhargav

**Comment by JensTrier** [comment]
No worries @bhargavshukla!
