### ISSUE TITLE
Wrong / \

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10447]
In multiple places on this page / is used when \ should be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e58e411-8997-2db1-5965-cc657dc862db
* Version Independent ID: 7e58e411-8997-2db1-5965-cc657dc862db
* Content: [Troubleshooting the new Teams installation - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-troubleshooting-installation)
* Content Source: [Teams/new-teams-troubleshooting-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-troubleshooting-installation.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by lindspea** [comment]
@hoyty76 thank you for reaching out and helping to improve Microsoft Docs. I've had a look at the document and the punctuation marks might have been fixed in the interim. Please can you check to confirm, or point out where you noticed a correction that is necessary. Thanks again.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
