### ISSUE TITLE
Upgrade the new Teams application Option A didn't install New Teams for all users.

### ISSUE THREAD

**Issue by loupyre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10458]
[Enter feedback here]
After following the directions in the Section "Upgrade the new Teams application: Option A" New Teams was installed for the current user but not for any of the other users on the computer or any new users logging in. Other users were required to "Get Teams for Work or School"; this is something I'd like to avoid. I don't want my everyday users to have to figure out how to do this; most of them are not comfortable enough with these computers to upgrade on their own let alone download and install.
For reference, the computers are running Windows 11 enterprise. I was hoping New Teams would just install with our Office365 download and install but no luck there either; it still installs the old Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b73fb04-90e1-de2e-e81d-3495c004b2b5
* Version Independent ID: 4b73fb04-90e1-de2e-e81d-3495c004b2b5
* Content: [Bulk deploy the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-bulk-install-client)
* Content Source: [Teams/new-teams-bulk-install-client.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-bulk-install-client.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
