### ISSUE TITLE
Incorrect REST API link regarding Teams CQD 

### ISSUE THREAD

**Issue by deividfoggi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10455]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

Considering the section "Many ways to access CQD data", there is a comment pointing to an API documentation regarding Skype for Business Server that will not work with Teams data. Please confirm if there is an alternative in Teams or remove it from Teams CQD documentation.

![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/39340082/06d372bb-f61f-4a09-abcd-97074446c5f2)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 718b597f-258b-3d61-17b8-1d41c8436d07
* Version Independent ID: 78f3333e-36cd-384a-8b5b-29bae7e1ed88
* Content: [Data and reports in Call Quality Dashboard (CQD) - Microsoft Teams](https://review.learn.microsoft.com/en-us/microsoftteams/cqd-data-and-reports?branch=main#many-ways-to-access-cqd-data)
* Content Source: [Teams/CQD-data-and-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/CQD-data-and-reports.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by ParkesJ** [comment]
This continues to be a viable option for accessing CQD data for Teams.

This is similar to how the current CQD Powershell module works, and is the same mechanism by which older versions of our Call Queue / Auto Attendant reports worked before their latest revisions.

As such, this is valid guidance and will remain in the documentation.

**Comment by get-itips** [comment]
Thank you @ParkesJ
