### ISSUE TITLE
The Bulk Installer does not have logic for ARM64 installation, and installs x64 builds instead of the correct ARM64 build.

### ISSUE THREAD

**Issue by mdoose23** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10451]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b73fb04-90e1-de2e-e81d-3495c004b2b5
* Version Independent ID: 4b73fb04-90e1-de2e-e81d-3495c004b2b5
* Content: [Bulk deploy the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-bulk-install-client)
* Content Source: [Teams/new-teams-bulk-install-client.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-bulk-install-client.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
@mdoose23   @get-itips   The articles have now been updated to include all 3 options listed -- x86, x64, & ARM 64.
