### ISSUE TITLE
Teamsbootstrapper.exe is not suitable for bulk deployment

### ISSUE THREAD

**Issue by ptilsen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10465]
This article describes bulk deployment of teams using a bootstrap installer of Teams. This defeats the primary purposes of bulk deployment using tools like Intune, Configuration Manager, or Group Policy; there is no version control, no assurance of delivery, and no means of caching the applications content. This article serves as poor documentation for organizations of even moderate size who need to consider Internet or other WAN bandwidth consumption. The article should describe using the bootstrapper to download offline-deployable Teams content (seemingly not possible) or deploying an offline installer, such as [MSTeams-x86.msix](https://go.microsoft.com/fwlink/?linkid=2196060&clcid=0x409&culture=en-us&country=us). It seems that the developers have somehow overlooked this common need with new Teams (see feedback: [Teamsbootstrapper.exe needs a full download option for use with ConfigMgr](https://feedbackportal.microsoft.com/feedback/idea/96fa5e2e-9856-ee11-a81c-0022484e5453)), but since there _is_ a full installer available and it's possible to bulk-deploy it, the documentation should cover deploying it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b73fb04-90e1-de2e-e81d-3495c004b2b5
* Version Independent ID: 4b73fb04-90e1-de2e-e81d-3495c004b2b5
* Content: [Bulk deploy the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-bulk-install-client)
* Content Source: [Teams/new-teams-bulk-install-client.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-bulk-install-client.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
@ptilsen  Thank you for reaching out with your concerns. I have contacted the product team and will keep you updated.  Joanne

**Comment by get-itips** [comment]
Thanks @JoanneHendrickson

**Comment by JoanneHendrickson** [comment]
@ptilsen  @get-itips   

H Patrick -- An offline install mode of the bootstrapper will be available very soon (like within days). In the meantime, I've inserted a note in the topic noting it is pending. The topic will be updated as soon as this feature is released. Thanks again for your feedback -- truly!  Joanne

**Comment by JoanneHendrickson** [comment]
@ptilsen  Hi Patrick:  Following up to let you know an offline method is now available.  This topic has been updated with the info.  Thanks!  Joanne
