### ISSUE TITLE
Need the powershell code for step number 3. This is the same issue as #7598 which was closed but the information was not provided.

### ISSUE THREAD

**Issue by dabaco** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10466]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 829f0c8b-26e4-c175-249e-ae5ffa9438cb
* Version Independent ID: 1ecb9e4c-530a-bb71-0902-cf9b3426e60b
* Content: [Migrate hybrid application endpoints to the cloud - Skype for Business Hybrid](https://learn.microsoft.com/en-us/skypeforbusiness/hybrid/decommission-move-on-prem-endpoints)
* Content Source: [Skype/SfbHybrid/hybrid/decommission-move-on-prem-endpoints.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Skype/SfbHybrid/hybrid/decommission-move-on-prem-endpoints.md)
* Service: **skype-for-business-server**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
