### ISSUE TITLE
Support for "Third-party app API"

### ISSUE THREAD

**Issue by lafe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10477]
Currently, the new Teams client does not support the "Third-party app API" that is used by the Stream Deck plugin to control Teams during a call. There is no mention on the roadmap or in the change list of it, so it would be great, if the roadmap is updated to reflect this API. Several colleagues as well as me are still using the old client, because of this missing feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Version Independent ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Content: [Known issues in the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-known-issues)
* Content Source: [Teams/new-teams-known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-known-issues.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @lafe I'm working on this

**Comment by get-itips** [comment]
Hello @lafe I'm still digging into this, are you still facing problems to use it?

**Comment by lafe** [comment]
Just checked and the "Third-party app API" section has appeared in the new client. So this issue should be fixed.
