### ISSUE TITLE
No Contacts in new Teams, no People App

### ISSUE THREAD

**Issue by Roman3** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10476]
About this information:
You no longer can access Contacts from Chat. Instead, use the new People app.

I would like to know where is this People app?
You don't say: "You will be able to use People app", but: "use the new People app"
So - where is it?

There are a lot of apps, but no People app.

Now imagine me, cursing about it for whole f****** day!

Ok, I know, that the person reading this is not responsible, so please forward this to the person, who is!

With Regards, Roman

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Version Independent ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Content: [Known issues in the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-known-issues)
* Content Source: [Teams/new-teams-known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-known-issues.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
The [Microsoft Open Source Code of Conduct][1], which outlines the expectations for community
interactions in and around docs.microsoft.com, is designed to help provide a welcoming and inspiring
community for all. The content of this issue appears to be out of sync with the code of conduct,
so we have closed it.

[1]: https://opensource.microsoft.com/codeofconduct/

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
