### ISSUE TITLE
Command Parameter is not there. 

### ISSUE THREAD

**Issue by lvilla02** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10474]
I tried running the command and the parameter, AllowTownhallRecordingPublishing  is not available. I did a Get-CsTeamsEventsPolicy and I don't see the attributes. This is all I see. Is this working? Is this command available yet? 

PS C:\WINDOWS\system32> Get-CsTeamsEventsPolicy

Identity          : Global
AllowWebinars     : Enabled
EventAccessType   : Everyone
AllowTownhalls    : Enabled
AllowEmailEditing : Enabled
Description       : Default policy

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68a48ea8-979b-8506-5a15-d7f15643aa40
* Version Independent ID: 68a48ea8-979b-8506-5a15-d7f15643aa40
* Content: [Manage VOD publishing for webinars and town halls - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-vod-publishing)
* Content Source: [Teams/manage-vod-publishing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/manage-vod-publishing.md)
* Service: **msteams**
* Sub-service: **meetings**
* GitHub Login: @wlibebe
* Microsoft Alias: **wlibebe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
