### ISSUE TITLE
why always hard to find something on microsoft help pages

### ISSUE THREAD

**Issue by dokumacifatih** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10475]
Just I need to open a setting to make my users eligible to call external users. 
give the link. show the setting SS thats it. what you have on a page:
History of the setting
Why Microsoft decided to put this setting
When it is developed by Microsoft
Who is eligible to change it 
what if doesn't work 

I don't need all these fucking info. Give the link like : 

Step 1-) CLICK HERE : https://admin.teams.microsoft.com/notifications/rules
Step 2-) Change XYZ to  On/OFF

That's it 
I couldnt give permission to my users to call external users 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c97ab6f5-4ca8-6116-a182-b418ccf4e523
* Version Independent ID: c97ab6f5-4ca8-6116-a182-b418ccf4e523
* Content: [Plan for meetings with external participants in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/plan-meetings-external-participants)
* Content Source: [Teams/plan-meetings-external-participants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/plan-meetings-external-participants.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
The [Microsoft Open Source Code of Conduct][1], which outlines the expectations for community
interactions in and around docs.microsoft.com, is designed to help provide a welcoming and inspiring
community for all. The content of this issue appears to be out of sync with the code of conduct,
so we have closed it.

[1]: https://opensource.microsoft.com/codeofconduct/
