### ISSUE TITLE
unclear guide

### ISSUE THREAD

**Issue by ServiceDeskRunshaw** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10485]
[Enter feedback here]

It's not clear how to access these preview features. Is this customers who have switched on the preview items in the new policy or is it customers you have invited only.

e.g. we have swtiched on Real Time Call Queue Metrics, but they dont seem to appear online or in the client.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4ab419c-9686-8abe-d1f3-85806a25e630
* Version Independent ID: a4ab419c-9686-8abe-d1f3-85806a25e630
* Content: [Manage voice applications policies for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-voice-applications-policies)
* Content Source: [Teams/manage-voice-applications-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/manage-voice-applications-policies.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by get-itips** [comment]
Hello @ServiceDeskRunshaw how are you?
I asked internally, that means private preview/invite only.
Hope this answers your question,
Thanks
