### ISSUE TITLE
Add to Known Issues in the new Microsoft Teams desktop client page

### ISSUE THREAD

**Issue by AB-PL** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10499]
Known Issues in the new Microsoft Teams desktop client page: 
https://learn.microsoft.com/en-us/microsoftteams/new-teams-known-issues

When adding a Guest contact setup in EntraID to a Private Channel within a Teams space, this does not work within the new Teams client and displays a generic error message.
Works fine using Teams classic on desktop and web to do so.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Version Independent ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Content: [Known issues in the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-known-issues)
* Content Source: [Teams/new-teams-known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-known-issues.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @AB-PL 
Can you please detail this generic error message so I can dig into this to see if we need to update the documentation or is actively being worked on?
Thanks

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
