### ISSUE TITLE
Don't understand

### ISSUE THREAD

**Issue by Germling** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10495]
I want MS Teams to call my phone and add me to meetings automatically as soon as the meeting starts. The reason is that I don't have MS Teams on my phone.
Does this work?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b759f354-bf74-3cff-0c96-3b28a27ee997
* Version Independent ID: fb2d8a68-f35a-bbee-a306-72ee20a450a3
* Content: [Set up the Call me feature for your users - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/set-up-the-call-me-feature-for-your-users)
* Content Source: [Teams/set-up-the-call-me-feature-for-your-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/set-up-the-call-me-feature-for-your-users.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
