### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by agenadro** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#105]
in the following paragraph the link to the  **Office 365 URLs and IP address** ranges is broken:

Go to **Office 365 URLs and IP address ranges** for a detailed and up-to-date list of the URLs, IP addresses, ports, and protocols that must be correctly configured for Teams. Microsoft is continuously improving the Office 365 service and adding new functionality, which means the required ports, URLs, and IP addresses may change over time. We recommend that you subscribe via RSS to receive notifications when this information is updated or changed.

here is the failing link:
https://support.office.com/article/8548a211-3fe7-47cb-abb1-355ea5aa88a2#bkmk_teams

it used to work fine a week ago.

thank you.

**Comment by tonysmit** [comment]
@agenadro  Can you tell me the topic you are looking at? I can then pass it on and get it fixed. Thanks, Tony
