### ISSUE TITLE
What to do, when the toggle switch is not showing up?

### ISSUE THREAD

**Issue by wikiux** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10502]
I have the newest version of Teams and want to check out the new Teams on mac.
Somehow the described toggle switch does not show up for me. 
Can you link some troubleshooting stept or even better some terminal commands to force it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce41ba02-ead8-68cc-65ce-869a88561486
* Version Independent ID: ce41ba02-ead8-68cc-65ce-869a88561486
* Content: [Install and prerequisites for the Microsoft new Teams for the Mac - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-mac-install-prerequisites#how-to-try-new-teams-app-switcher)
* Content Source: [Teams/new-teams-mac-install-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-mac-install-prerequisites.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by FreakyxD** [comment]
I was able to get the new Teams by using the "Download new Teams" button here: https://www.microsoft.com/en-us/microsoft-teams/download-app
Keep in mind that this new app doesn't work with personal Microsoft accounts yet.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
