### ISSUE TITLE
Excellent article 

### ISSUE THREAD

**Issue by abdulsalamkhan82** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10504]
[Excellent article, opened my brain]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76c2487c-044d-1349-708a-5841fcb21ab8
* Version Independent ID: b7033454-1a9c-48d4-8004-78415c5feb89
* Content: [Implement Quality of Service in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/qos-in-teams)
* Content Source: [Teams/QoS-in-Teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/QoS-in-Teams.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for the feedback!
