### ISSUE TITLE
Make new Teams content time agnostic and add screenshots

### ISSUE THREAD

**Issue by ashishguptaiitb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10511]
Two feedback:

- `What features are changing` section can benefit from screenshots that show before-after comparison. At least for some items.
- Consider making the docs time agnostic or things get out of date soon. For example, the article lists a few enhancements that are coming in Oct but within 1 week, article owner will have to ratify it with PM team + add new timeline. This diligence to keep info fresh will make this type of timeline-based content a never ending governance item. Consider adding coming soon or some such verbiage. Of course, check with marketing and PM team if we can document a promise of future features. If yes, best to link to the M365 roadmap item if those roadmap entries are available from PM team.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Version Independent ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Content: [Known issues in the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-known-issues)
* Content Source: [Teams/new-teams-known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-known-issues.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @ashishguptaiitb 
I passed this feedback to the article's author.
Thank you,
