### ISSUE TITLE
The installation failed with the commands as described in this doc.

### ISSUE THREAD

**Issue by tsnakaya** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10518]
Option A in Step.1 presents the following as installation commands.

**> 3. At the prompt enter: ./teamsbootstrapper.exe -p**

However, when execute on command pronto, it fails with the following error

**> C:\temp>./teamsbootstrapper.exe -p**
**> '.' is not recognized as an internal or external command,**
**> operable program or batch file.**

Any of the following would be appropriate, including the command in the image.

**> .\teamsbootstrapper.exe -p**
**> teamsbootstrapper.exe -p**

The customer has pointed this out to us, so could you please check and correct it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b73fb04-90e1-de2e-e81d-3495c004b2b5
* Version Independent ID: 4b73fb04-90e1-de2e-e81d-3495c004b2b5
* Content: [Bulk deploy the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-bulk-install-client)
* Content Source: [Teams/new-teams-bulk-install-client.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-bulk-install-client.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by tsnakaya** [comment]
Sorry, the issue was duplicated.
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/10442#issue-1927411601

 Waiting for the documentation to be corrected.

**Comment by get-itips** [comment]
Fixed in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/b3aa95149d6a8c2fa9ca10feb02f82ddfaee6f68
Thanks!
