### ISSUE TITLE
Hyperlinks for Neat Devices

### ISSUE THREAD

**Issue by grahammw** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10520]
[Enter feedback here]
Please can you add the hyperlinks for the Neat Products just like the Cisco ones.

Neat Bar - https://neat.no/bar
Neat Bar Pro - https://neat.no/bar-pro/
Neat Board - https://neat.no/board
Neat Pad touch console - https://neat.no/pad

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 385700f1-12d2-e4a2-a649-051f8401d8a3
* Version Independent ID: 385700f1-12d2-e4a2-a649-051f8401d8a3
* Content: [Teams Rooms certified systems and peripherals - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/certified-hardware?tabs=Windows)
* Content Source: [Teams/rooms/certified-hardware.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/rooms/certified-hardware.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by get-itips** [comment]
Thanks @grahammw Graham
