### ISSUE TITLE
E1\F1\F3 meeting participant limit ? 

### ISSUE THREAD

**Issue by dipinn26592** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10521]
The article does not call out details about all the sku's e.g E1, F1, F3 etc. What is the meeting limit for these sku's 300 or 1000 ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams#meetings-and-calls)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hello @dipinn26592 

All enterprise plans allow for up to 1,000 people and Office 365 E1, F1/F3 are enterprise plans

https://learn.microsoft.com/en-us/microsoftteams/overview-meetings-webinars-town-halls

**Comment by dipinn26592** [comment]
Hi @get-itips , Can we please have this called out in the above article as well, thanks.
