### ISSUE TITLE
Provide Definition or Context for "Trusted Orgs"

### ISSUE THREAD

**Issue by hey-jason** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10523]
This article could use some additional context or a link to a related doc as to what "trusted orgs" are and how those can be defined within the meeting host organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b5d6aab-04dc-1eef-6430-304d72f4a724
* Version Independent ID: 0b5d6aab-04dc-1eef-6430-304d72f4a724
* Content: [Configure the Microsoft Teams meeting lobby for sensitive meetings - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/configure-lobby-sensitive-meetings)
* Content Source: [Teams/configure-lobby-sensitive-meetings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/configure-lobby-sensitive-meetings.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@hey-jason trusted orgs is covered in [Manage external meetings and chat with people and organizations using Microsoft identities](https://learn.microsoft.com/microsoftteams/trusted-organizations-external-meetings-chat?tabs=organization-settings#specify-trusted-microsoft-365-organizations). I'll add a link to this article.

**Comment by get-itips** [comment]
Link was added in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/5633329d98112da47665b9818fe5623b16caa70c
Thanks @MikePlumleyMSFT
