### ISSUE TITLE
PC crashes after opening a file in desktop-app

### ISSUE THREAD

**Issue by lf1717** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10528]
Hi,

I have a new issue using the new teams.
When I open a file (word, excel or powerpoint) in teams and I would like to edit it in the desktop-app. I click on open in desktop-app and after a few secondes, the PC crashes.
Do you  have a solution for that?
I disabled in the old teams the option: run in the background. But this does not solve the problem. 

Thanks.
Regards,
Lydia

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
