### ISSUE TITLE
Link for "Download  MSIX" downloads only x86 version

### ISSUE THREAD

**Issue by gjozic** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10536]
Link for "Download  MSIX" downloads only x86 version. i can imagine that most of the users need x64.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db74252a-f531-8fcf-4da0-5e439cfdfd8d
* Version Independent ID: db74252a-f531-8fcf-4da0-5e439cfdfd8d
* Content: [New Microsoft Teams for Virtualized Desktop Infrastructure (VDI) - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-vdi-requirements-deploy)
* Content Source: [Teams/new-teams-vdi-requirements-deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-vdi-requirements-deploy.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by aliefamzari** [comment]
The public link also point to the same x86 MSIX, Although MS said both 32bit and 64bit client is agnostic, but they eventually recommending 64bit.

**Comment by scanum** [comment]
#10534 Duplicate
