### ISSUE TITLE
msix link is wrong

### ISSUE THREAD

**Issue by NP1982** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10530]
the link for the msix is wrong. It redirects to https://learn.microsoft.com/en-gb/SharePoint/install/hardware-and-software-requirements?redirectedfrom=MSDN#section2

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b73fb04-90e1-de2e-e81d-3495c004b2b5
* Version Independent ID: 4b73fb04-90e1-de2e-e81d-3495c004b2b5
* Content: [Bulk deploy the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-bulk-install-client)
* Content Source: [Teams/new-teams-bulk-install-client.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-bulk-install-client.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Fixed in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/5e1aff2bd9bb8f4227b20c1f4dfb2ba6034823b9
