### ISSUE TITLE
teamsbootstrapper.exe latest version can only be use once

### ISSUE THREAD

**Issue by aliefamzari** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10533]
The next execution will produce an error. Even Teams have been removed, the teamsbootstrapper.exe can no longer be use.

![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/29467714/8801a9ac-eec6-49b0-8531-20374ee9ff6e)
![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/29467714/8341831f-a817-459a-bcf4-b5672cafbec8)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b73fb04-90e1-de2e-e81d-3495c004b2b5
* Version Independent ID: 4b73fb04-90e1-de2e-e81d-3495c004b2b5
* Content: [Bulk deploy the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-bulk-install-client)
* Content Source: [Teams/new-teams-bulk-install-client.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-bulk-install-client.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @aliefamzari how are you?
Here we are limited to documentation issues and fixes, while I'll try to pass this on, I think the best would be to open a support request from your tenant.
Thank you,
