### ISSUE TITLE
Incorrect link for MSIX download

### ISSUE THREAD

**Issue by Motdog92** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10534]
The download link for the MSIX file is wrong, it redirects to a Microsoft Learn page for Sharepoint 2016.

https://learn.microsoft.com/en-us/microsoftteams/new-teams-vdi-requirements-deploy#deploy-the-new-microsoft-teams-client

Step 2 has the wrong link.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db74252a-f531-8fcf-4da0-5e439cfdfd8d
* Version Independent ID: db74252a-f531-8fcf-4da0-5e439cfdfd8d
* Content: [New Microsoft Teams for Virtualized Desktop Infrastructure (VDI) - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-vdi-requirements-deploy)
* Content Source: [Teams/new-teams-vdi-requirements-deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-vdi-requirements-deploy.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Already fixed. thanks
