### ISSUE TITLE
Still None the Wise - Don't know what Microsoft Teams Exploratory Trial is …

### ISSUE THREAD

**Issue by Simon-lfd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10549]
[Enter feedback here]
### Hopeless
Surely this page is meant to clarify things?
What is an 'Entra user'?
Do I have to do anything/pay money? We've been running happily on our office/exchange accounts for years. If we need to do more to avoid the removal of services, this is a price increase and to suggest anything else is dishonest.

Generally if you send me an email suggesting I pay for something - I would like a nice, clear page explaining what it is and what the benefits are. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-exploratory)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
