### ISSUE TITLE
NDI support in New Teams

### ISSUE THREAD

**Issue by JamesGutherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10547]
Is NDI support going to be ready for when we are forced to transition? It is a critical part of our workflow and is the main reason holding us back from transitioning.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67786821-0151-66c1-2fa1-498d88e3b3b3
* Version Independent ID: 67786821-0151-66c1-2fa1-498d88e3b3b3
* Content: [Classic Teams users to be automatically updated to new Teams - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/new-teams-automatic-upgrade-announced)
* Content Source: [Teams/new-teams-automatic-upgrade-announced.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-automatic-upgrade-announced.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
