### ISSUE TITLE
Section "Meeting Engagement" needs updates

### ISSUE THREAD

**Issue by janetslei** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10546]
"Meeting engagement" section is missing a new control already showing in Teams admin center, the control is "External meeting chat". can someone explain what this control does?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Teams settings and policies reference - Microsoft Teams](https://learn.microsoft.com/en-US/microsoftteams/settings-policies-reference?WT.mc_id=TeamsAdminCenterCSH#meeting-engagement)
* Content Source: [Teams/settings-policies-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/settings-policies-reference.md)
* Service: **msteams**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by get-itips** [comment]
Thank you for your feedback, I'll add it to the article
