### ISSUE TITLE
Tags for Shared Channels would be useful.

### ISSUE THREAD

**Issue by joaomcabrita** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10548]
[Enter feedback here]
We use Shared Channels to collaborate with different people within organisation. And often there are different roles. So having this feature would be beneficial to the product. Instead I need to find every person instead of using tags as intended.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b16e659e-cf07-268a-e224-fa444749ac29
* Version Independent ID: ee822a8d-b331-998f-e336-b1fa510f35c0
* Content: [Manage tags in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-tags)
* Content Source: [Teams/manage-tags.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/manage-tags.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
I know the product teams are always looking for user feedback and how to make SharePoint better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice 
SharePoint: https://sharepoint.uservoice.com/.
Skype for Business: https://www.skypefeedback.com/.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.
Thank you for your contribution to make the docs better! Much appreciated!
