### ISSUE TITLE
teamsbootstrapper.exe doesn't work - "errorCode": "0x80004004"

### ISSUE THREAD

**Issue by holoholo808** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10542]
I have tested on several devices. Same error message everywhere. Doesn't matter with the Online or offline method.

.\teamsbootstrapper.exe -p -o "c:\path\to\teams.msix"
.\teamsbootstrapper.exe -p

Results in this error:
{
"success": false,
"errorCode": "0x80004004"
}

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by aarony99** [comment]
I installed once with teamsbootstrapper -p -o C:\MyTestPath\MSTeams-x64.msix

Then I tested removal with teamsbootstrapper -x and it worked to remove it.

Then I tried to provision again, and from now on get the 0x80004004.

Provisioning manually with Add-AppxProvisionedPackage works.

Fix this silly teamsbootstrapper.exe business.

**Comment by Vess99** [comment]
Same here, bootstrapper does not work, same error code 0x80004004. Does anyone actually test software anymore before releasing it?

**Comment by holoholo808** [comment]
@Vess99 
I guess, we do the testing.

@scanum 
I will not open a ticket. Everyone facing the same issue.
https://www.reddit.com/r/MicrosoftTeams/comments/17mowi6/teamsbootstrapper_0x80004004/?utm_source=share&utm_medium=web2x&context=3

 Just try to install in the way it's documented with the ".\teamsbootstrapper.exe -p" command.

**Comment by Vess99** [comment]
".\teamsbootstrapper.exe -p’ does not work, same error.

**Comment by holoholo808** [comment]
You have to delete both keys before:

Remove-ItemProperty -Path "HKLM:Software\Wow6432Node\Microsoft\Office\Teams" -Name "maglevExitCode"
Remove-ItemProperty -Path "HKLM:Software\Wow6432Node\Microsoft\Office\Teams" -Name "maglevInstallationSource"
