### ISSUE TITLE
No app switcher visible

### ISSUE THREAD

**Issue by kleynjan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10541]
[Enter feedback here]

App switcher button is not visible. Completely unclear how to get from Teams classic (Mac) to the New Teams.

The product seems to be a bigger mess than ever before -- and the documentation is no better.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce41ba02-ead8-68cc-65ce-869a88561486
* Version Independent ID: ce41ba02-ead8-68cc-65ce-869a88561486
* Content: [Install and prerequisites for the Microsoft new Teams for the Mac - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-mac-install-prerequisites)
* Content Source: [Teams/new-teams-mac-install-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-mac-install-prerequisites.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
