### ISSUE TITLE
Previous Schedules Still Apply?

### ISSUE THREAD

**Issue by jmaiher** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10543]
How does this impact the schedules defined here? Seems to add a layer of confusion: https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin#new-teams-schedule-for-clients

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67786821-0151-66c1-2fa1-498d88e3b3b3
* Version Independent ID: 67786821-0151-66c1-2fa1-498d88e3b3b3
* Content: [Classic Teams users to be automatically updated to new Teams - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/new-teams-automatic-upgrade-announced)
* Content Source: [Teams/new-teams-automatic-upgrade-announced.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-automatic-upgrade-announced.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @jmaiher 
How are you?
Maybe I am missing something but I don't see any dates beyond March 2024 in this article https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin#new-teams-schedule-for-clients

Please let me know if I understood you correctly,
Thanks

**Comment by jmaiher** [comment]
That’s true, but, the announcement doesn't explicitly call out the different dates depending on update channel. My management as well as others I’ve read online are now unsure if the update schedule dates are still being adhered to (for example - monthly enterprise will set New Teams client as default in December 2023), or, if we now have until March of 2024 instead.
________________________________

**Comment by get-itips** [comment]
Hello @jmaiher 
How are you?
The way I understand it, is, March 2024 is a hard date for every classic Teams to be upgraded to new Teams, regarding any previous schedule, that still apply.
The MC is not invalidating any previous communication or schedule.
If you still feel it is not clear please let me know.

**Comment by get-itips** [comment]
Hello @jmaiher could you see my comment here? Thanks

**Comment by jmaiher** [comment]
I did. The other article shows a schedule for the different update channels and then they'll be mandated to "New Teams" by default, with Government Cloud (GCC, GCC High) Preview, and Government Cloud (DoD) Preview being March 2024. Some update channels are mandated already, with others following this month, December, and January 2024. This article seems redundant, at best, and confusing to IT admins who are already familiar with the other article and all the schedules listed. Since you confirmed to me through this comment section the schedules still apply, that's good enough for me & my organization.

**Comment by get-itips** [comment]
Hello @jmaiher 
Please also take into account what the article with the schedules says in the important note

>**These schedules only apply if your organization has set the Teams Update policy "Use new Teams Client" to either:**
Microsoft controlled (the value in the Teams Admin Center) or
Microsoft choice (if you are using PowerShell)

Closing for now but it can be re-opened.
