### ISSUE TITLE
Missing Info & Do not override our settings!

### ISSUE THREAD

**Issue by DontNeedNoGit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10544]
Your page indicates your _recommendation_ to change the New Teams Client setting from Not Enabled to _your preference_. However, New Teams is still **_very_** buggy (more buggy than Teams CAlssic, which is also buggy, but less). Can you please confirm and add to this page that you will **not** override our setting from Not Enabled to using the New Teams?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67786821-0151-66c1-2fa1-498d88e3b3b3
* Version Independent ID: 67786821-0151-66c1-2fa1-498d88e3b3b3
* Content: [Classic Teams users to be automatically updated to new Teams - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/new-teams-automatic-upgrade-announced)
* Content Source: [Teams/new-teams-automatic-upgrade-announced.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-automatic-upgrade-announced.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @DontNeedNoGit 
How are you?
Do you mean continuing using classic teams beyond March 31, 2024?
Thanks for clarifying

**Comment by DontNeedNoGit** [comment]
Yes. And also that you will not override our Teams update policy that currently has the 'Use the new Teams client' set to 'not enabled'. That should not be changed by the announcement. Our IT team continues to test New Teams (via a separate update policy) but we don't want staff to be able to opt in, let alone be forced into New Teams until more of the bugs are addressed.

**Comment by get-itips** [comment]
Hello @DontNeedNoGit 
After some internal digging, I got a reply for you to please contact your account manager to provide this feedback.
They will be able to confirm.
Thank you
