### ISSUE TITLE
Teams upgrade for Mac?

### ISSUE THREAD

**Issue by kleynjan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10545]
Announcements of Teams for Mac refer to this page, but this only describes the process for Windows users.

**Comment by scanum** [comment]
@kleynjan thanks for the feedback. Please link the documentation you are referring to.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
