### ISSUE TITLE
Config.office.com - > modern app settings blocks installation of classic teams aswell. 

### ISSUE THREAD

**Issue by CarlFredrikGammelsaeter** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10552]
After disabling according to the below chapter:
https://learn.microsoft.com/en-us/microsoftteams/new-teams-deploy-with-m365apps#how-to-exclude-new-teams-from-new-installations

Our teams classic client uninstalled aswell. 
Article doesnt mention this at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 163ad900-960d-4ac0-1dde-082be316f282
* Version Independent ID: 163ad900-960d-4ac0-1dde-082be316f282
* Content: [Upgrade to new Microsoft Teams with Microsoft 365 Apps - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-deploy-with-m365apps)
* Content Source: [Teams/new-teams-deploy-with-m365apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-deploy-with-m365apps.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
