### ISSUE TITLE
Enabling/disabling notifications on a channel post is crucial

### ISSUE THREAD

**Issue by mschickler** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10550]
The ability to enable/disable notifications on a channel post is crucial to my Teams workflow.  This seems like such a basic feature of any collaboration platform.  How could this be removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Version Independent ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Content: [Known issues in the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-gb/microsoftteams/new-teams-known-issues)
* Content Source: [Teams/new-teams-known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-known-issues.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
