### ISSUE TITLE
Update to indicate how Intelligent Meeting Recap uses customer data in relation to LLMs/AI

### ISSUE THREAD

**Issue by airmnichols** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10557]
Can this document be updated to reflect how Intelligent Meeting Recap works regarding data privacy and AI/LLMs?

For example, a statement that indicates that the data in transcripts is not used to train the AI LLMs, isn't available to other customers, etc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cd0e0f68-d088-d0b7-cbb7-56bb16e4026f
* Version Independent ID: 8a107028-31a6-6821-a150-1ebdd7a7d440
* Content: [Microsoft Teams Privacy - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-privacy)
* Content Source: [Teams/teams-privacy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/teams-privacy.md)
* Service: **msteams**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@airmnichols   We're in the process of working on a standalone article about Intelligent Meeting Recap. We're hoping to have it published by the end of this week. We'll respond back to this thread when it's published. Thanks.

**Comment by get-itips** [comment]
Thanks @DHB-MSFT

**Comment by DHB-MSFT** [comment]
@airmnichols   FYI, we've published an article about intelligent recap: [Data, privacy, and security for intelligent recap in Teams Premium](https://learn.microsoft.com/en-us/MicrosoftTeams/privacy/intelligent-recap). Hope that helps.

**Comment by airmnichols** [comment]
Thanks!
