### ISSUE TITLE
Typo maybe? 

### ISSUE THREAD

**Issue by johnsr85** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10555]
[Enter feedback here]

Oi see anything wrong with this sentence? 

""The Teams MSI places an installer in %SystemDrive%\Program Files\Teams Installer on 32-bit Windows and %SystemDrive%\Program Files (x86)\Teams Installer on 64-bit Windows. "" 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Bulk install Teams using Windows Installer (MSI) - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
see https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/10479#issuecomment-1779666492
