### ISSUE TITLE
Any improvement on user mark when organizers will begin seeing notification for view-only, and the notification content?

### ISSUE THREAD

**Issue by FionaW-ms** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10554]
[Enter feedback here]
Since one cx has been chasing for update on why starting at 500 user mark, since the capacity is 1000, and this has caused participants and organizers confusion. Hope you could help clarify the following two points, Thanks.
For the doc https://learn.microsoft.com/en-us/microsoftteams/view-only-meeting-experience: 
1. About "Meeting organizers will begin seeing notifications for view-only experience around the 500 user mark.", 
->Could you pls confirm if any update on the number of user mark when organizers will begin seeing notification for view-only?
2. From the screenshot in the article, notification message says "This meeting has reached capacity. Participants who join now will have view-only access".
->Since capacity is 1000, What should be the exact correct notification message?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2bf705c2-1f24-bdb5-e712-e8408b941aca
* Version Independent ID: ddedd7e0-7d85-06e0-7f20-8b83b3dccec7
* Content: [View-only meeting experience - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/view-only-meeting-experience)
* Content Source: [Teams/view-only-meeting-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/view-only-meeting-experience.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by FionaW-ms** [comment]
This needs product team to clarify. Could you pls have the product team to review the content of the article? Thanks.
