### ISSUE TITLE
Teams Music On Hold Options Multiple Audio Files

### ISSUE THREAD

**Issue by FredPCode** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10561]
When configuring Music On Hold (MoH) for Teams, how versatiles is that feature?
Is MoH restricted to one song? 
Is there a song time/lenght limit, or file size limit?
My organization owns the full rights to dozens of songs, and MoH would be a good use of them.
Can we upload multiple songs for MoH and have them played successively / in order?
Could a playlist be utilized to dictate the order of playback on multiple music files, and intersperse an "Announcement" file that would get played in between each music file/track. 
Is there something I forgot to ask about MoH and multiple songs?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 416f3cdb-ca75-8224-bc04-985e5f7ea9dd
* Version Independent ID: 6e8c6f33-8043-e367-b44b-74b5f5ee96f2
* Content: [Music on Hold - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/music-on-hold)
* Content Source: [Teams/music-on-hold.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/music-on-hold.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
