### ISSUE TITLE
The "Share this Window" Option is Missing from the Taskbar

### ISSUE THREAD

**Issue by esiemiat** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10565]
This button is present in the classic version of Teams while participating in a Team's call, but it is missing from the new version. There was an entry on the "Known Issues" page saying that this feature would return in an October update, but October is gone and so is that entry.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
