### ISSUE TITLE
Need multiple roles, or does Comm Admin include the support roles?

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1056]
I'd like to see the 4 roles clarified to show if there is any overlap, or if we need to be made a member of 2 or more. For example, Communications Administrator says "troubleshoot user call quality problems using advanced troubleshooting toolset". Communication Support Engineer also mentions "advanced tools", but includes "Call analytics" which does not appear under Communications Administrator.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b434530-6bf2-6e00-6eae-6fa043d022ce
* Version Independent ID: caab785f-e3a4-831a-87d8-26934a9f834f
* Content: [Use Microsoft Teams admin roles to manage Teams](https://docs.microsoft.com/en-us/microsoftteams/using-admin-roles)
* Content Source: [Teams/using-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/using-admin-roles.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by MishaTravis** [comment]
@TorrenManson - Thank you for submitting this feedback.

I was able to get this into the backlog for the Teams team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by LolaJacobsen** [comment]
@islubin can you review this one for us please?

**Comment by islubin** [comment]
Comms admin includes advanced call analytics tools.  We should make that clear in the description of the role - good catch!  @LolaJacobsen could you or Sharon make that change or should I?

**Comment by LolaJacobsen** [comment]
@islubin - Happy New Year! Pinging you to get this back on your radar.

**Comment by islubin** [comment]
I submitted a PR that I believe makes it more clear - Lola take a look and feel free to edit.

**Comment by LanaChin** [comment]
Thanks for making the updates @islubin. The changes are live.
