### ISSUE TITLE
"Give Control" missing in new version of teams

### ISSUE THREAD

**Issue by JarrodGross** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10562]
"Give Control" missing in new version of teams

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Version Independent ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Content: [Known issues in the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-known-issues)
* Content Source: [Teams/new-teams-known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-known-issues.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @JarrodGross 
I do see it and use it in new teams.
Please let me know if I understood you correctly,

**Comment by JarrodGross** [comment]
Hello, my team of 6 instructors did not have this feature last week but when we came to the office this week it was back.
Not sure if this is something done by Microsoft or my Tenant-Admin.
OK to mark this as resolved. Thank you
