### ISSUE TITLE
unclear firewall requirements

### ISSUE THREAD

**Issue by DrLippert** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10563]
Under 'Check Network availability' the second point says, 'Access to HTTP ports 80 and 443.'
Does that mean to any destination? if so, it should be stated! And if not the necessary destinations should be in linked document 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a711c07e-10b3-baf0-b92c-9dbcf6ab9474
* Version Independent ID: 2038cd48-44b1-1ed1-6e50-48290eef5605
* Content: [Prepare your Environment - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-prep)
* Content Source: [Teams/rooms/rooms-prep.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/rooms/rooms-prep.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by get-itips** [comment]
Hello @DrLippert Peter, I'm working on this

**Comment by tonysmit** [comment]
I'm working on this.

**Comment by tonysmit** [comment]
Fixed the article and submitted a PR to main. I changed the text to: Open ports HTTP (port 80) and HTTPS (port 443). To see the destinations when you are configuring the firewall rules, please see  the
Skype for Business Online and Microsoft Teams table in [Microsoft 365 and Office 365 URLs and IP address ranges](/microsoft-365/enterprise/urls-and-ip-address-ranges)
for those destinations.
