### ISSUE TITLE
Looking for setting to change default web browser

### ISSUE THREAD

**Issue by eternalmatt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10566]
Fall out from: [Web links from Outlook emails or Teams chats now open in Microsoft Edge](https://support.microsoft.com/en-us/topic/web-links-from-outlook-emails-and-teams-chats-open-in-microsoft-edge-b0e1a1c1-bd62-462c-9ed5-5938b9c649f0)

I have searched [Microsoft Edge - Policies](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies) and [Teams settings and policies reference](https://learn.microsoft.com/en-us/microsoftteams/settings-policies-reference).

What is the setting or registry entry to update Teams to use the system default web browser?

Please add this to the documentation.

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
