### ISSUE TITLE
Best Practices as default settings

### ISSUE THREAD

**Issue by kathyfurtado** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1057]
Why doesn't MS just make the "Best Practices" the default settings for rollout? It would save us all time. For example:
"Allow only team owners to post to the General channel"
and
"Turn off @team and @[team name] mentions"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by MishaTravis** [comment]
@kathyfurtado - Thanks for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make Teams better. They keep a close tab on User Voice - https://microsoftteams.uservoice.com/forums/555103-public - and if you don't mind, it would be awesome if you could look through and give your input in User Voice; if you don't see a similar request already, you could open one. Let us know and we can up-vote your request, too.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by kathyfurtado** [comment]
I opened a new request at https://microsoftteams.uservoice.com/forums/555103-public/suggestions/36049615-make-best-practices-the-default-settings-for-tea called “"best practices" the default settings for teams rollout”

Thank you,

Kathy
206-455-1278

**Comment by get-itips** [comment]
Hi @kathyfurtado thanks for your feedback.
As you suggested the idea to UserVoice @yogkumgit  will proceed to close this issue.
We really appreciate your comments.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @kathyfurtado 
Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
