### ISSUE TITLE
Teams meeting active participants list and hovering over users

### ISSUE THREAD

**Issue by JarrodGross** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10571]
In the previous version of microsoft teams, you could open a meeting chat and hover over the user/avatars at the top to see the user's full display name, well as hover over the "+2 users" circle to see additional names. This feature no longer works in the new teams

![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/149718494/c22ff233-be83-442e-9a41-b067f4c5bc13)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Version Independent ID: 442f8c6b-95ba-a09e-639d-b9dd141198f6
* Content: [Known issues in the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-known-issues)
* Content Source: [Teams/new-teams-known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-known-issues.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @JarrodGross 
 I've just experienced this and I could expand the list by clicking on the icon next to the (11)

**Comment by JarrodGross** [comment]
Hello, clicking the icon next to it shows a list of all users invited to the meeting, but does not necessarily reflect the list of participants currently live/logged into an active meeting.
The only way on the new teams to see all users who are "active" in the meeting, is to go join it yourself and look at the people list.
Otherwise, the old teams allowed you to hover over persons initials or the (+#) and provided you a tooltip/popup of their name / who else is in the meeting.
Thank you.

**Comment by get-itips** [comment]
Hello @JarrodGross 
After asking internally, I got the reply for you to please support feedback directly from the new teams, Help -> Give Feedback.
Thank you

**Comment by JarrodGross** [comment]
Thank you, I will do so.
