### ISSUE TITLE
How are we supposed to provide feedback when everything is labelled a support case

### ISSUE THREAD

**Issue by advisorgee** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10573]
Genuinely curious, how are we supposed to provide feedback on the New Teams if you are telling people to open a support case?. I came here to provide similar feedback about the now removed notifications in channels feature. Someone already opened a feedback item for it, but it was recommended to open a case with support and the case was closed. How am I supposed to comment on that or upvote it to have it included back in?

I can't log a case with support as suggested above as that is for admins to log and I am but a lowly end user.

**Comment by scanum** [comment]
I know the product teams are always looking for user feedback and how to make SharePoint better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice 
SharePoint: https://sharepoint.uservoice.com/.
Skype for Business: https://www.skypefeedback.com/.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.
Thank you for your contribution to make the docs better! Much appreciated!
