### ISSUE TITLE
Automatic recording teams meeting

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10587]
Please share detailed steps for automatic teams meeting recording.  my Cusotmer are struggling to enable this feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 733c7b3e-1daa-7569-9059-c3c335262155
* Version Independent ID: 733c7b3e-1daa-7569-9059-c3c335262155
* Content: [Manage Microsoft Teams meeting recording options for sensitive meetings - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-meeting-recording-options)
* Content Source: [Teams/manage-meeting-recording-options.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/manage-meeting-recording-options.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@robinpoulose1 normally the meeting organizer sets automatic recording as part of the [meeting options](https://support.microsoft.com/office/53261366-dbd5-45f9-aae9-a70e6354f88e). You can also use a [meeting template](https://learn.microsoft.com/microsoftteams/create-custom-meeting-template) or [sensitivity label](https://learn.microsoft.com/purview/sensitivity-labels-meetings). I'll add some links to the article.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
