### ISSUE TITLE
Notifications in New teams - Windows

### ISSUE THREAD

**Issue by livewire-itsupport** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10583]
Hi the badges in system tray of new teams icon doesn't show in Microsoft Windows 11, could you please look into this? The classic version of teams is displaying the notification badges on classic teams icon. Thanks.

**Comment by talmroth** [comment]
For the sake of Austin, please bring this back.

**Comment by Isopolito** [comment]
Yes for the sake of me, please do

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
