### ISSUE TITLE
Clarify the retention policies / give an example

### ISSUE THREAD

**Issue by obhayes** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1058]
I was struggling to tell the difference between the last two bullet points, they seem to be the same thing..as if you set the last option to 1 year, you are effectively preserving the data until then, could you add a bit more clarity please or example when you would use one over the other. Thanks 
"Teams retention policies do support:
•Preservation: Keep Teams data for a specified duration and then do nothing
•Preservation and then delete: Keep Teams data for a specified duration and then delete
•Deletion: Delete Teams data after a specified duration"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb40cf43-557e-d443-578b-49edca4a3179
* Version Independent ID: f78c9566-767f-bfae-7ba0-4e81d313034e
* Content: [Retention policies in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/retention-policies)
* Content Source: [Teams/retention-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/retention-policies.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by obhayes** [comment]
ok it actually clarifies this a bit better in the admin centre on the information hover overs.

**Comment by scanum** [comment]
@obhayes  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
