### ISSUE TITLE
MTRS on Windows supported?

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10581]
Hi, the article https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-release-note?tabs=Windows#416400-3242023 mentions that from version 4.16.40.0 the MTRS on Windows are supported for E2EE. But this article says otherwise. Can you please check what is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b601b72a-bcaa-2afd-22f7-8123856d2a97
* Version Independent ID: b601b72a-bcaa-2afd-22f7-8123856d2a97
* Content: [Require end-to-end encryption for sensitive Teams meetings - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/end-to-end-encrypted-meetings)
* Content Source: [Teams/end-to-end-encrypted-meetings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/end-to-end-encrypted-meetings.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback
