### ISSUE TITLE
Issues with statuses, Teams desktop app disappearing

### ISSUE THREAD

**Issue by SirJacobus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10590]
Hi,

we´re having quite widespread issues, especially with the New Teams, within our company environment.
At first (approx. 2 weeks ago) the statuses have become completely unreliable and random, often marking people as offline while they´re online on their side, or in meeting while being online etc. Restarts, reinstallations don´t really help, only for a while. 

Then, after another update, the Teams desktop app (mainly on Windows 10 22H2), started to disappear completely, users reporting they could not find the app anymore. We have an SW distribution system but it doesn´t affect Teams like this, without any notice etc. so the only viable explanation is the native Teams automatic updater.

Additionally, the Outlook Teams Meeting addin that is distributed with the New Teams is constantly disappearing from Outlook or cannot be manually activated at all, we´re always trying in the correct launch order but no success so eventually, we need to install the Classic Teams to enable the addin. Note: we have on-premise Exchange in combination with 365 Business Standard licenses (mostly)

I realise there´s probably no immediate solution but since I couldn´t find much info online (that would be posted in Oct / Nov) - does MS know about this? Will a next update address these bugs? The "Known Issues" site doesn´t really mention anything from the above...

Thank you
Jakub

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
