### ISSUE TITLE
Columns are cut off unless screen is maximized

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10596]
I have an ultrawide monitor. While trying to work with this page set to half the screen width in Win 11, the table is cut off. There is a horizontal scroll bar at the bottom, however the table is very very tall. If I stretch the screen out wider, the table pops up fully with a right margin roughly 50% of the width of the table, which is several inches on an UW monitor.

If I maximize the page, I do get the entire table, however the margins around the table are massive.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a455280-ea8e-2ddf-2965-60d9dcc0e21d
* Version Independent ID: 7fb320d3-fa69-23fa-113c-53e9d2e11ada
* Content: [Dimensions and measurements - Call Quality Dashboard (CQD) - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/dimensions-and-measures-available-in-call-quality-dashboard)
* Content Source: [Teams/dimensions-and-measures-available-in-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/dimensions-and-measures-available-in-call-quality-dashboard.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by TorrenManson** [comment]
Hi,

I think there's a misunderstanding. The issue isn't with a product, the issue is with the rendering of the learn.microsoft.com webpage.

Here's a 2/3 wide screen, showing the table cut off and plenty of white space where the table could be.

[cid:4e0dc311-3d8c-4774-bb2c-ebf04ab54095]

cheers,
Torren
________________________________
