### ISSUE TITLE
Type Error: To update and existing custom app, follow these steps:

### ISSUE THREAD

**Issue by ChetanSharma-msft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10613]
Please verify and update the content:
![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/59052547/832046e7-dd8d-4530-96be-2289dc3a1363)

Section link: https://learn.microsoft.com/en-us/microsoftteams/teams-custom-app-policies-and-settings#update-a-custom-app-using-teams-admin-center

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 632a367f-0c30-fc21-5040-d2d80f184bdb
* Version Independent ID: 6cab37af-6dcf-d2c1-3d68-14fc7375f1f5
* Content: [Manage custom app policies and settings - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-custom-app-policies-and-settings#upload-a-custom-app-using-teams-admin-center)
* Content Source: [Teams/teams-custom-app-policies-and-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/teams-custom-app-policies-and-settings.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by get-itips** [comment]
Thanks for your feedback!

**Comment by ashishguptaiitb** [comment]
Thanks @get-itips for the fix.
