### ISSUE TITLE
I have set what mentioned in article and there is still no option for webex meeting

### ISSUE THREAD

**Issue by michael-zajic** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10616]
I have set what mentioned in article and there is still no option for webex meeting (all three option checked). ANy idea what it is wrong ?

![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/151998303/82e3ce04-89d8-4e09-8ba7-2baa3e2860a5)
![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/151998303/40d44af2-d6b1-4e2e-83f1-172104097fac)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c62081e-2421-80b9-8ba9-aaf8fd55e432
* Version Independent ID: 5df3c5e5-978f-cfa7-9e5c-3cd7f65fa8ff
* Content: [Enable Teams Rooms devices to join third-party meetings - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/third-party-join)
* Content Source: [Teams/rooms/third-party-join.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/rooms/third-party-join.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by michael-zajic** [comment]
OK, thanks


[ Michael Zajíc, (+420) 737805636] 
 
________________________________
Od: Manuela Scanu ***@***.***>
Odesláno: pondělí 27. listopadu 2023 0:21
Komu: MicrosoftDocs/OfficeDocs-SkypeForBusiness
Kopie: michael-zajic; Author
Předmět: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] I have set what mentioned in article and there is still no option for webex meeting (Issue #10616)

Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
