### ISSUE TITLE
Supported Win10 builds

### ISSUE THREAD

**Issue by bpe71** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1061]
"Create the Windows 10 Enterprise package":
Maybe point to the doc info with supported OS version / SRS version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29b0551a-0c9b-8934-5e4b-d34fe292ec8e
* Version Independent ID: 1e19dcb0-59cd-5e9f-0afc-e30bc4cbf80f
* Content: [Deploy Skype Room Systems by using System Center Configuration Manager](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/room-systems-scale)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/room-systems-scale.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/room-systems-scale.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @Turgayo
* Microsoft Alias: **jambirk**

**Comment by MishaTravis** [comment]
@bartpe71  - Thank you for submitting this feedback.

I was able to get this into the backlog for the Skype team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by LolaJacobsen** [comment]
@Turgay Öngün Could you help with this Skype note, please?

**Comment by jambirk** [comment]
@Turgayo  Please have a look here.

**Comment by scanum** [comment]
@Turgayo Any updates on this issue? Thanks!

**Comment by jambirk** [comment]
Turgayo is no longer with the group. We will need to address this once the rebrand work is finished.

The heart of the answer is that we don't document the required OS version for each SRS installer version. It changes with every MSI release, and the guidance is to run the console setup script once to determine the best OS version for a given MSI.

**Comment by Reeced40** [comment]
@jambirk thank you for that. Can I add a note to the doc stipulating this?

**Comment by scanum** [comment]
@bpe71 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
