### ISSUE TITLE
Limitations?

### ISSUE THREAD

**Issue by oradcliffe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10612]
What are the limits of shared calling?  How many users can use this, how many concurrent calls using the same line?  Surely I can't just bring an entire org of 10k people under one number.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dae4f3dc-c617-d8b8-8a6b-bda47a6e9755
* Version Independent ID: dae4f3dc-c617-d8b8-8a6b-bda47a6e9755
* Content: [Plan for Shared Calling - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/shared-calling-plan)
* Content Source: [Teams/shared-calling-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/shared-calling-plan.md)
* Service: **msteams**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by oradcliffe** [comment]
I'm confused.  I don't have an issue in my tenant, I'm not using this feature.  Your docs do not state how many people can share a line or how many calls can use a line concurrently.. that's what I'm asking.  This is a product question and there's no way support would have an answer for this.
