### ISSUE TITLE
Add Note to clarify that sideloading enables chats with bots through GUID or direct link in Teams

### ISSUE THREAD

**Issue by marianocalero** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10621]
Please add a note to this doc explaining that if the ability to sideload is turned off in the Teams App Setup policy, that users will no longer be able to access bots through a GUID or direct link to the chat. This has become an increasingly frequent issue due to the rollout of the new Teams client. 

https://learn.microsoft.com/en-us/microsoftteams/teams-custom-app-policies-and-settings#app-setup-policy-settings-for-custom-apps

In the above section, please add a note saying, "**If the ability to upload custom apps is turned off in the Teams App Setup policy, users will no longer be able to access bots through a GUID or direct link to the chat.**"

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 632a367f-0c30-fc21-5040-d2d80f184bdb
* Version Independent ID: 6cab37af-6dcf-d2c1-3d68-14fc7375f1f5
* Content: [Manage custom app policies and settings - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-custom-app-policies-and-settings)
* Content Source: [Teams/teams-custom-app-policies-and-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/teams-custom-app-policies-and-settings.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by Namita2015-lab** [comment]
Looking for the same documentation update. Thanks.

**Comment by get-itips** [comment]
Hello @marianocalero I'm working on this

**Comment by ashishguptaiitb** [comment]
Taking this internally with you @marianocalero . Closing this issue here.
Let's not make the doc update yet, @get-itips .
