### ISSUE TITLE
Unable to open 2 tenants in separate window

### ISSUE THREAD

**Issue by bobojobaxter** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10625]
Prior to this latest client update, I could open a commercial tenant and GCCH tenant side by side. I can no longer have them be separate windows. This is highly requested in my org.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
