### ISSUE TITLE
Unable to add people as a guest account

### ISSUE THREAD

**Issue by bobojobaxter** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10624]
Logged into a commercial tenant with a GCCH tenant Guest account. I can't adhoc add 2 people to a chat. 

![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/24656010/21353682-2567-46d2-8701-e3eb85051988)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
