### ISSUE TITLE
Bad links for "Teams interactions with Microsoft 365 services" files

### ISSUE THREAD

**Issue by aamillerMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10626]
The links for "Teams interactions with Microsoft 365 services" PDF and Visio files result in 404.

> Teams interactions with Microsoft 365 services
> Teams interacts with multiple services in Microsoft 365 - including data governance, security, and compliance capabilities.
> 
> This series of illustrations provides a view into the logical architecture of productivity services for enterprise architects.
> 
> Thumb image for Teams logical architecture poster.
> [PDF](https://raw.githubusercontent.com/MicrosoftDocs/OfficeDocs-Enterprise/public/Enterprise/downloads/msft-m365-teams-logical-architecture.pdf) | [Visio](https://raw.githubusercontent.com/MicrosoftDocs/OfficeDocs-Enterprise/public/Enterprise/downloads/msft-m365-teams-logical-architecture.vsdx)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ad624-9792-91b7-c85f-09b839b1ea44
* Version Independent ID: e8288f91-11bd-599b-8a88-074917b315a4
* Content: [Microsoft Teams IT architecture and voice solutions posters - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-architecture-solutions-posters)
* Content Source: [Teams/teams-architecture-solutions-posters.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/teams-architecture-solutions-posters.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hello @aamillerMSFT I'm working on this

**Comment by get-itips** [comment]
Links were fixed and an updated version of the article will soon be published. Thank you
