### ISSUE TITLE
What if I continue to use policy?

### ISSUE THREAD

**Issue by geektocore** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10640]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f0f6177-da44-cc08-d8d3-ca1d90bd4d2d
* Version Independent ID: 4f0f6177-da44-cc08-d8d3-ca1d90bd4d2d
* Content: [App centric management to manage app access - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/app-centric-management)
* Content Source: [Teams/app-centric-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/app-centric-management.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
