### ISSUE TITLE
There is no explanation about the accepted SMTP domains of Email integration.

### ISSUE THREAD

**Issue by lyncjp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1068]
It is necessary to press "space" key when entering domain.
Also, need to turn off the allow setting to enable accepted domain.
Despite the need for complicated operations, the item for this parameter does not exist.
Please describe about the details of Email integration setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9b7f77-061d-a224-ff1c-8d3e15d21221
* Version Independent ID: 00fa9550-c4c4-3398-ffbb-271cc724048f
* Content: [Manage Microsoft Teams features in your Office 365 organization](https://docs.microsoft.com/en-us/microsoftteams/enable-features-office-365)
* Content Source: [Teams/enable-features-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enable-features-office-365.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by MishaTravis** [comment]
@lyncjp  - Thank you for submitting this feedback.

I was able to get this into the backlog for the Teams team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by LolaJacobsen** [comment]
@ritika2502 - should we update the article?

**Comment by Chatou7** [comment]
Still is unclear about he "Accepted SMTP domains". Is it required or not ??

**Comment by get-itips** [comment]
Hi @lyncjp hope you are doing great.
**Thanks for your comments**.
This specific article doesn't mention Accepted Domains, is this maybe the article you are referring to? https://docs.microsoft.com/en-us/microsoftteams/manage-external-access

You can find more information about email integration here https://support.office.com/en-us/article/send-an-email-to-a-channel-in-teams-d91db004-d9d7-4a47-82e6-fb1b16dfd51e

Hope this information has helped  you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @lyncjp 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
