### ISSUE TITLE
Error after install windows "Wlindows could not apply unattend settings during pass [offlineServicing]."

### ISSUE THREAD

**Issue by mart-th** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1069]
I prepare the installation media is success

Using updates:        
    C:\Users\Mart\Downloads\windows10.0-kb4340917-x64_ed5f586fa9d7064d61e45c523f20ba7fc1ff142a.msu
Writing stick:         USB Flash Disk

Formatting and partitioning the target drive... done.
Copying Windows... done.
Copying the installation image... done.
Mounting the installation image... done.
Applying language packs... done.
Applying updates... done.
Cleaning up the installation image... done.
Unmounting the installation image... done.
Splitting the installation image... done.
Injecting drivers... done.
Copying Rigel build... done.
Configuring unattend files... done.
Selecting image... done.
Cleaning up... done.

Please safely eject your USB stick before removing it.
WARNING: DO NOT PRE-INSTALL LANGUAGE PACKS AFTER THIS POINT
WARNING: You have applied a Windows Update to this media. Any pre-installed language packs must be added BEFORE Windows updates.
Transcript stopped, output file is C:\Users\Mart\Documents\PowerShell_transcript.DESKTOP-MB8MNR1._Mp4trPx.20181115090601.txt

After install windows but before restart. Windows have error "Wlindows could not apply unattend settings during pass [offlineServicing].". I'm not sure what is problem. Can you help me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51d42140-9f7b-a6f3-7a3e-76cc7331cf22
* Version Independent ID: a7dacc56-c2df-55fb-76a3-ecb194564fae
* Content: [Configure a Skype Room Systems v2 console](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/console)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/console.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by MishaTravis** [comment]
@mart-th - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind, please keep us posted here on the resolution as I really want to get this information you are discovering back into the docs.
