### ISSUE TITLE
Typo - Skype for Business Server 2019 was released in October 2019

### ISSUE THREAD

**Issue by albertherd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1070]
I'm assuming that it should read "was released in October 2018"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbeb59c4-349f-944c-5183-4fb26a34c22b
* Version Independent ID: 2beb18af-35a6-de0a-d90f-89c94533b8da
* Content: [FAQ - Upgrade Journey from Skype for Business to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/faq-journey)
* Content Source: [Teams/FAQ-journey.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/FAQ-journey.md)
* Service: **msteams**
* GitHub Login: @dearbeen
* Microsoft Alias: **dearbeen**

**Comment by MishaTravis** [comment]
@albertherd  - Thank you for submitting this feedback.

I was able to get this into the backlog for the Teams team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by LolaJacobsen** [comment]
@dearbeen - OK to update?

**Comment by dearbeen** [comment]
Yes the date should be Oct 2018. Thanks.

**Comment by LolaJacobsen** [comment]
Article has been updated. Thanks, Debbie.
