### ISSUE TITLE
What happens when you add a Surface HUB to a team?

### ISSUE THREAD

**Issue by ToSur** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1071]
What does actually happen to a Surface HUB when it has MS Teams installed, and someone adds the Surface HUB to a team?

Does anyone has any experience with this or is there any article on this matter?

**Comment by MishaTravis** [comment]
@ToSur  - thank you for submitting feedback; that's a good question.

I think the best way forward is if you can open a service ticket in your tenant so your question can get resolved ASAP. Based on the outcome, let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind, please keep us posted here on the resolution, as I really want to get this information you are discovering back into the docs.
