### ISSUE TITLE
Stream included in Business Essentials and Business Premium plans, update

### ISSUE THREAD

**Issue by jorgv** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1072]
According to [August Microsoft Blog](https://www.microsoft.com/en-us/microsoft-365/blog/2018/08/31/new-to-microsoft-365-in-august-tools-to-achieve-more-in-the-modern-workplace)  Business Essentials and Business Premium plans include Microsoft stream. Documentation should be updated to avoid confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by MishaTravis** [comment]
@jorgv  - Thank you for submitting this feedback.

I was able to get this into the backlog for the Teams team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by LolaJacobsen** [comment]
I updated the article - it'll go live later today:
### Enable Microsoft Stream for users in the organization

Microsoft Stream is available as part of eligible Office 365 subscriptions or as a standalone service.  See the [Stream licensing overview](https://docs.microsoft.com/stream/license-overview) for more details.  Microsoft Stream is now included in Microsoft 365 Business, Office 365 Business Premium, and Office 365 Business Essentials.
