### ISSUE TITLE
Missing Powershell cmdlets for Teams Trial Licensing

### ISSUE THREAD

**Issue by AlexHill90** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1073]
Hi, I'd say it should be noted that the SKU appears only after the first trial has been activated, otherwise you can't assign them from admin portal

The second thing: what's this SKU powershell cmdlet to enable mass trial activation? Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the Microsoft Teams Commercial Cloud Trial offer](https://docs.microsoft.com/en-gb/MicrosoftTeams/iw-trial-teams)
* Content Source: [Teams/iw-trial-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/iw-trial-teams.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by MishaTravis** [comment]
@AlexHill90  - Thank you for submitting this feedback.

I was able to get this into the backlog for the Teams team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @AlexHill90 **Thanks for your feedback, we really appreciate it**.

I tested in lab and the "Microsoft Teams Trial" toggle appeared once the first user signed up for it.
So it's true that from that point, you will be able to assign the trial to other users through Admin Portal, I'll create a Pull Request to clarify this.

About PowerShell, you would have to use Office 365 PowerShell cmdlet Set-MsolUserLicense to assign licenses.

**Hope this information has helped you!**
