### ISSUE TITLE
Exchange Hybrid 

### ISSUE THREAD

**Issue by joaoalhinho** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1075]
Is Exchange Hybrid deployment necessary to send voice mails to Exchange Onprem?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e342c08-c1d8-8c1d-944d-d6489a17c42b
* Version Independent ID: 5c9987d5-4c98-8115-55c8-f629dbd25799
* Content: [Plan Cloud Voicemail service](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-cloud-voicemail)
* Content Source: [Skype/SfBServer2019/hybrid/plan-cloud-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/hybrid/plan-cloud-voicemail.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by MishaTravis** [comment]
@joaoalhinho - Thanks for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind, please keep us posted here on the resolution; I really want to get this information you are discovering back into the docs.
