### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by joaoalhinho** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1076]
Does the Onprem users need any Office365 license in order CDRs QoE be visible in Call Analytics? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a4a9d16-296f-00fd-1899-c6a982ba91ec
* Version Independent ID: 776dd776-b0b0-3088-6549-ec01b549f1d0
* Content: [Plan Call Data Connector](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-call-data-connector)
* Content Source: [Skype/SfBServer2019/hybrid/plan-call-data-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/hybrid/plan-call-data-connector.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by MishaTravis** [comment]
@joaoalhinho - Thanks for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind, please keep us posted here on the resolution; I really want to get this information you are discovering back into the docs.

**Comment by dariomws306** [comment]
Hi @joaoalhinho , Thanks for submitting feedback. Onprem user don't require a license to use Call Data Connector.
