### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by christianpilz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#108]
The " Creating a Cluster KB article " link is dead...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 854766da-e557-2338-0aea-262e67a0b984
* Version Independent ID: 20b49404-62d7-83f8-118d-b8189b87da0b
* Content: [Environmental requirements for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/environmental-requirements#Fileshare)
* Content Source: [Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/environmental-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/environmental-requirements.md)
* Service: **unspecified**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by kenwith** [comment]
@christianpilz - thank you for reporting this one. I have updated the link and also fixed some formatting. Sorry for the delay. It is greatly appreciated your taking the time to provide feedback to make the docs better!
