### ISSUE TITLE
Solution needed for roaming user profiles in virtual environment

### ISSUE THREAD

**Issue by rdangleton** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1081]
Almost all virtual desktop environments require the ability to roam a user's profile between available virtual desktops. Teams installs 600MB and thousands of files directly into the user's profile. That is a far bigger concern to any virtual desktop administrator than the questions addressed on this page. Please elaborate on what options are available to work around this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193173fd-b838-d4b1-2768-dd298b03d3ad
* Version Independent ID: d8bd6cae-7013-6c38-79fe-5113197afc4c
* Content: [Run Microsoft Teams in a virtual environment](https://docs.microsoft.com/en-us/microsoftteams/virtual-environment-teams)
* Content Source: [Teams/virtual-environment-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/virtual-environment-teams.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by MishaTravis** [comment]
@rdangleton  - Thank you for submitting this feedback.

I was able to get this into the backlog for the Teams team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by teepirat** [comment]
Are there any News in this topic?

**Comment by jasonfare** [comment]
This document is no longer present online and was part of the documentation being provided to a large client converting from Lync On Prem to Teams through their M365 E5 enablement.  Any idea when this document will go back to being available?

**Comment by AndreaBarr** [comment]
@heyadamGIT Could you please investigate this issue?

**Comment by LolaJacobsen** [comment]
@LanaChin - this article is no longer in our docset. Please investigate.

**Comment by LanaChin** [comment]
This article is being reviewed for updates and will be reposted once those updates are made.

**Comment by LanaChin** [comment]
This article will be replaced by new documentation.
