### ISSUE TITLE
Request for non-media bypass clarification

### ISSUE THREAD

**Issue by eunegut** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1082]
Hello,

Can you please clarify what "Pending" for Non-Media Bypass | Media Bypass means for the added SBCs ? Thank you!
 
-- | --

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1a1c01-10a9-7f69-1c7b-1a566b0f5112
* Version Independent ID: 329ee759-40fc-98fb-b91e-87786c63024b
* Content: [List of Session Border Controllers certified for Direct Routing](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-border-controllers)
* Content Source: [Teams/direct-routing-border-controllers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-border-controllers.md)
* Service: **msteams**
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
I believe that means that official support is currently under investigation but not yet completed.

**Comment by MishaTravis** [comment]
@eunegut  - Thank you for submitting this feedback.

I was able to get this into the backlog for the Teams team. The team will get this clarification prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by LolaJacobsen** [comment]
@CarolynRowe - this one's yours.

**Comment by jonathanrsantos1** [comment]
In Skype for Business we have SBC certificated and supported (By Provider), we have the same concept to Teams?

**Comment by get-itips** [comment]
Hi @eunegut thanks for your feedback.
As @jambirk says, Pending means that Microsoft is still working to certify that feature with SBC vendors.

Hope this information has helped you.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @eunegut 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
