### ISSUE TITLE
Activation User License

### ISSUE THREAD

**Issue by tposton** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1083]
Does the activation user license need to persist indefinitely? Can it be removed after the SIP address has been provisioned and appears in the SfB/Teams Admin Center? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure a Session Border Controller for multiple tenants](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants#deploy-and-configure-the-sbc)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by MishaTravis** [comment]
@tposton  - Thank you for submitting this feedback.

I was able to get this into the backlog for the Teams team. The team will get this clarification prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by CarolynRowe** [comment]
@tposton 
Yes, for now the activation user license need to persist indefinitely.  Thank you for the feedback.

**Comment by mazhagiah** [comment]
Does it require to provide E5 license for Activation user or just sip address is enough?
