### ISSUE TITLE
Depencencies on Exchange for meeting scheduling

### ISSUE THREAD

**Issue by doulouz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1091]
the document states: "For creating and viewing meetings, it's a mixed bag: Creating and viewing meetings is supported for Exchange 2016 cumulative update 3 (CU3) and above, but not for versions prior to Exchange 2016 CU3". Actually a user provisioned with Teams license only and without an Exchange mailbox in place (whether it's online or on-prem) CAN schedule a meeting. Please fix this statement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact](https://docs.microsoft.com/en-us/MicrosoftTeams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@doulouz Thank you for pointing this out

I will get this to the Teams writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@nsshommo Could you please investigate this issue.

**Comment by nsshommo** [comment]
> @nsshommo Could you please investigate this issue.

Okay, I am investigating this one.

**Comment by get-itips** [comment]
Hi @doulouz **Thanks for your feedback, we really appreciate it.**

I tested in a lab the scenario you have described and when a user enabled for teams without Exchange License (onprem or online) tries to use the _Schedule a Meeting_ button, a message saying that the mailbox doesn't exist will show up.

 Hope this information has helped you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @doulouz 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
