### ISSUE TITLE
Not enough explanation

### ISSUE THREAD

**Issue by jumpinf00l** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1095]
The current article doesn't explain whether the user will be blocked either; only if they attempt to host a meeting, or if they attempt to host+join a meeting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fea6bb01-9614-b8a1-2d18-94fea656cfda
* Version Independent ID: 5b27d62e-f4a2-9f65-8fff-9da6d58e036c
* Content: [Blocked user licenses for Skype Meeting Broadcast](https://docs.microsoft.com/en-us/SkypeForBusiness/set-up-your-network-for-skype-meeting-broadcast/blocked-user-licenses-for-skype-meeting-broadcast?redirectSourcePath=%252fen-us%252farticle%252farticle-b898557c-547f-4055-9478-d17fb653285f)
* Content Source: [Skype/SfbOnline/set-up-your-network-for-skype-meeting-broadcast/blocked-user-licenses-for-skype-meeting-broadcast.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-your-network-for-skype-meeting-broadcast/blocked-user-licenses-for-skype-meeting-broadcast.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@jumpinf00l Thank you for pointing this out

I will get this request for clarification over to the Skype for Business writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @jumpinf00l **Thanks for your feedback**, the document has been improved after your comment, clarifying that the user won't be able to **host** a meeting.

Thank you!

**Comment by jumpinf00l** [comment]
Awesome, thanks guys!
