### ISSUE TITLE
Locations in Office 365

### ISSUE THREAD

**Issue by adamoh1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1099]
How does locations in Skype for Business work in Office 365?

**Comment by get-itips** [comment]
Hi @adamoh1 how are you?

There is no article referenced in your issue, besides that, if you refer to the location info you can set using Skype For Business Client, it has no difference with the On-Prem version. See https://support.office.com/en-us/article/customize-your-location-info-in-skype-for-business-a8559d54-e628-43f2-a0f5-2e92bfb9735e

Hope this information helps you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @adamoh1 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
