### ISSUE TITLE
Documentation is for the "old experience" and should be updated for the "new and improved" eDiscovery experience.

### ISSUE THREAD

**Issue by dgorgone** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1104]
This current documentation is over one year old, and it documents the "old experience" that is used for doing a Content Search.  The Security & Compliance Center now has a "new and improved" eDiscovery experience, and we do have documentation that goes into detail on this new experience, but it's not specific to Microsoft Teams.  Can we update this Teams specific documentation to describe the new and improved user experience?  This is the documentation for general eDiscovery with the new experience: https://docs.microsoft.com/en-us/Office365/SecurityCompliance/ediscovery-cases?redirectSourcePath=%252farticle%252f9a00b9ea-33fd-4772-8ea6-9d3c65e829e6. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5346de0f-d09a-86ce-8390-5a33d8139bfb
* Version Independent ID: 5052193b-fd71-d1fe-e64c-f2c47218531c
* Content: [Use Content Search in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/content-search)
* Content Source: [Teams/content-search.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/content-search.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@dgorgone Thank you for pointing this out

I will get this infromation about the article needing updated over to the Teams writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Thanks for the heads up @dgorgone  . We’ve updated the article and removed the screen shots. We also moved the link to the existing Office 365 Content Search documentation to the top of the article so it’s easier to find full documentation for this feature

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @dgorgone 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
