### ISSUE TITLE
中文有很多地方把“Skype for business”翻译成了“ for Business 的 Skype”

### ISSUE THREAD

**Issue by tony-xia** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1105]
中文有很多地方把“Skype for business”翻译成了“ for Business 的 Skype”

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 56ab9d91-d5c4-be13-660e-10b1fdacadec
* Version Independent ID: efdd6696-1415-26ae-ab56-5e758a34311c
* Content: [升级的基本任务清单-Microsoft 团队](https://docs.microsoft.com/zh-cn/MicrosoftTeams/upgrade-basic#feedback)
* Content Source: [Teams/upgrade-basic.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.zh-CN/blob/live-sxs/Teams/upgrade-basic.md)
* Service: **msteams**
* GitHub Login: @dearbeen
* Microsoft Alias: **dearbeen**

**Comment by AndreaBarr** [comment]
@tony-xia Thank you for pointing this out

I will get this translation information over to the Teams writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by samanthaw** [comment]
@tony-xia this is fixed
