### ISSUE TITLE
Microsoft Teams Public Team

### ISSUE THREAD

**Issue by PhoonHuat** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1107]
Are we able to chat with public groups without joining as members?

Or do we need to join as member, chat and exit the group? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d86301b-ce9c-388c-e563-9e5e5c27132e
* Version Independent ID: 07e4ae23-0966-e8f3-9b7c-4f6c02569eb0
* Content: [Office 365 Groups and Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/office-365-groups)
* Content Source: [Teams/Office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-groups.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@PhoonHuat thank you for this inquiry

I am not sure if you have to join the group to be able to chat with the members of that group. Let me get this over to the Teams writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by LolaJacobsen** [comment]
@islubin do you know the answer to PhoonHuat's question?

**Comment by get-itips** [comment]
Hi @PhoonHuat How are you? **Thanks for your feedback**.
Currently, you need to join as a member to a public group to participate in it.
Hope this information helps you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @PhoonHuat 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
