### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by ChrisHaleyAvanade** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1108]
The link "Getting started with Office 365 Connectors for Microsoft Teams," in the last paragraph does not direct to the mentioned content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5eb6a35-32fa-6703-8ed2-0855e602b7d5
* Version Independent ID: 7890ca09-d505-35a9-071a-8662a4b19275
* Content: [Use Office 365 and custom connectors in Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/office-365-custom-connectors)
* Content Source: [Teams/Office-365-custom-connectors.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-custom-connectors.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@ChrisHaleyAvanade Thank you for pointing this out

I will get this link information over to the Teams writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by fracklen** [comment]
The link is still dead. - Looking for a map of what I can put into my webhook JSON payload.

**Comment by jamesrhea** [comment]
@fracklen, is this the doc you're looking for? https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors

If so, I'll go ahead an update the link. Thanks!

**Comment by fracklen** [comment]
Nope.
I'm building a custom webhook notification, so i need to build my own json
blob. There seems to be no documentation of what I can put in my json.


tor. d. 20. dec. 2018 17.34 skrev James Rhea <notifications@github.com>:

**Comment by jamesrhea** [comment]
@fracklen, if your notification uses actionable message cards, this doc might be what you're after:
https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-connectors

There's also a message card reference doc:
https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference

**Comment by AndreaBarr** [comment]
@ChrisHaleyAvanade  It looks like James has resolved your issue. I am going to close this issue at this time. If this issue is not resolved please re-open this issue.
