### ISSUE TITLE
Certificated and Supported appliance

### ISSUE THREAD

**Issue by jonathanrsantos1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1109]
In Skype for Business we have SBC certificated and supported (By Provider), we have the same concept to Teams?

**Comment by NMuravlyannikov** [comment]
Hi @jonathanrsantos1  here is the list of Session Border Controllers certified for Teams. https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-border-controllers

**Comment by jonathanrsantos1** [comment]
Updated :)

![image](https://user-images.githubusercontent.com/44894877/49303457-a3df8380-f4c1-11e8-8696-1e7f5f99e841.png)

**Comment by yogkumgit** [comment]
@NMuravlyannikov  Thank you very much for the contribution and sharing this explanation. @jonathanrsantos1 Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
