### ISSUE TITLE
Tables and the explanation are quite hard to understand

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1111]
Tables 1 ,  2 
while the text offers both a table , as well as an textual explanation, these seem to be mostly unrelated.
this makes it very,very hard, to understand the explanation. 
the able formatting is unclear ( ie is the vertical bar in the middle an OR , or intended as a separator ?
in addition the table formatting (bold / italics ) is intended to transfer meaning , but is not all to clear 

can you please 
- explain the meaning for the headers in the tables, ie what does the column ''
- layout the tables more clear 
- explain the tables , ie by offering a 'walk through' of one or two of the rows in each table as part of the text 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169a20a6-ebf7-1093-3cb1-fb438b9b7e13
* Version Independent ID: b2074fd8-724e-75fa-bafb-a0f7966bf593
* Content: [Coexistence with Skype for Business](https://docs.microsoft.com/en-us/microsoftteams/coexistence-chat-calls-presence)
* Content Source: [Teams/coexistence-chat-calls-presence.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/coexistence-chat-calls-presence.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **francoid**

**Comment by AndreaBarr** [comment]
@Josverl Thank you for this feedback

I will get this request to clarify the tables over to the Teams writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by jambirk** [comment]
I'm working with the product group on this now. Should have an update later this week.

**Comment by CrystalThomasMS** [comment]
Thanks for brining this up! Our team is revising this article now, and your feedback will be incorporated. We'll report back here when the article has been revised.

**Comment by surajj72** [comment]
Has the document been revised? The tables still are not very descriptive.

**Comment by FrancoiD** [comment]
Yes it has. The tables are also explained in the text.
