### ISSUE TITLE
In-tenant presence section

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1112]
the first paragraph of this section seems to be a Copy/Paste from another section and does not discuss the 'In-Tenant Presence'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169a20a6-ebf7-1093-3cb1-fb438b9b7e13
* Version Independent ID: b2074fd8-724e-75fa-bafb-a0f7966bf593
* Content: [Coexistence with Skype for Business](https://docs.microsoft.com/en-us/microsoftteams/coexistence-chat-calls-presence)
* Content Source: [Teams/coexistence-chat-calls-presence.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/coexistence-chat-calls-presence.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **francoid**

**Comment by AndreaBarr** [comment]
@Josverl Thank you for pointing this out to us

I will get this information over to the Teams writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by jambirk** [comment]
I'm working with the product group on this now. Should have an update later this week.

**Comment by CrystalThomasMS** [comment]
Thanks for brining this up! Our team is revising this article now, and your feedback will be incorporated. We'll report back here when the article has been revised.

**Comment by FrancoiD** [comment]
Article has been revised and this matter should be closed.
