### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mitchhawkins** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1113]
Possibilities typo in the example email - "and discover the possibilites of Teams."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b8299a4-20c0-62b9-976d-c3ea271c2a1a
* Version Independent ID: aeae12b9-53cc-5a48-ab55-d45a9101ab44
* Content: [Onboard early adopters to Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/get-started-with-teams-onboard-early-adopters#feedback)
* Content Source: [Teams/get-started-with-teams-onboard-early-adopters.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-started-with-teams-onboard-early-adopters.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by AndreaBarr** [comment]
@mitchhawkins Thank you for pointing this out. 

I will get this typo over to the Teams writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by CrystalThomasMS** [comment]
Thanks for bringing this to our attention! This typo has been corrected.
