### ISSUE TITLE
why is autoattendant topic missing from on-premise PSTN

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1114]
why is autoattendant topic missing from on-premise PSTN?
there needs to be statements about / reference to supporting capability for onpremise service numbers et al.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc7ed866-d928-70e8-c08f-c05695747e95
* Version Independent ID: b243d41d-61e9-04a3-d0ce-8fbdc66bed6b
* Content: [Plan Phone System in Office 365 with on-premises PSTN connectivity in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/plan-phone-system-with-on-premises-pstn-connectivity)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/plan-phone-system-with-on-premises-pstn-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/plan-phone-system-with-on-premises-pstn-connectivity.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by AndreaBarr** [comment]
@bakerm00 Thank you for pointing this out

I will get this information about the autoattendant topic missing ove to the Skype for Business writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by CarolynRowe** [comment]
Thank you for your feedback.  The purpose of this article is not to describe all Phone System features.  The topic does link to the appropriate Phone System article, which lists auto attendant as a supported feature:  https://docs.microsoft.com/en-us/microsoftteams/here-s-what-you-get-with-phone-system?toc=/skypeforbusiness/toc.json&bc=/skypeforbusiness/breadcrumb/toc.json.

**Comment by bakerm00** [comment]
It doesn’t support on prem PSTn breakout ; porting numbers is required which we cannot do
The feature I’m asking for Is apparently roadmap

But you gloss over support scenarios just as you have with your statement below

Mike Baker
Infrastructure Architect
Elsevier
+44(0)7747020245

________________________________
