### ISSUE TITLE
MD5, SHA-1, or SHA-256 hashes

### ISSUE THREAD

**Issue by AJ-Acevedo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#112]
There is no way to validate that the downloaded MSI is legitimate. The document should include an MD5, SHA-1, or SHA-256 hash.

Reference: https://docs.microsoft.com/en-us/MicrosoftTeams/msi-deployment

**Comment by tonysmit** [comment]
Hi. Thanks for the feedback. I'm investigating this and trying to find a PM that I can assign this issue. Thanks, Tony

**Comment by tonysmit** [comment]
I've assigned two PMs from the product group to lend you a hand. We appreciate the feedback. If there are addition/corrections/suggestions to the docs, please edit the topic by clicking **Edit** (on the right side of the topic) or use VsCode/GtiHub desktop. Let me know how I can help further.

**Comment by juturu** [comment]
This is resolved and newer downloads should include the signatures on the msi. Thanks for the report.

**Comment by tonysmit** [comment]
Should we included a note in the topic?
