### ISSUE TITLE
blue box "important" outdated . 

### ISSUE THREAD

**Issue by stvollet** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1124]
I suggest an update of this document, the blue box "important" about dependency to exchange online seems outdated as per https://docs.microsoft.com/en-gb/office365/securitycompliance/search-cloud-based-mailboxes-for-on-premises-users?redirectSourcePath=%252fen-us%252farticle%252fsearching-cloud-based-mailboxes-for-on-premises-users-in-office-365-3f7dde1a-a8ea-4366-86da-8ee6777f357c

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@stvollet Thank you for pointing this out

I will get this upated information for the important box over to the Teams writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by CrystalThomasMS** [comment]
The article has been revised based on your feedback. Thank you for your contribution!
