### ISSUE TITLE
Wrong Uri

### ISSUE THREAD

**Issue by martinsedina** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1125]
Hi Team,

I think you have wrong Uri on the example command for New-CsServerApplication. The Uri must be http:// instead of https://. This took me hard time to find out to get LBRouting application registered.

Regards,

Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 154129f7-079b-d56a-461a-3749decbb16c
* Version Independent ID: 8862d04d-599a-f778-6dff-5fe4d1b7c863
* Content: [Location-Based Routing for Conferencing in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/enterprise-voice-solution/lbr-for-conferencing)
* Content Source: [Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/lbr-for-conferencing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/lbr-for-conferencing.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by AndreaBarr** [comment]
@martinsedina Thank you for pointing this out

I will get the url information over to the Skype for Busness writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
