### ISSUE TITLE
Member limit

### ISSUE THREAD

**Issue by DDog80sRocked** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1127]
Is there still a 2500 member limit when using a dynamic group with Teams?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a578ddb-6494-9bda-529e-0156e5ab7c30
* Version Independent ID: 57d519c9-90f0-873d-ffef-589f0b3b3ac9
* Content: [Overview of dynamic membership for teams](https://docs.microsoft.com/en-us/microsoftteams/dynamic-memberships)
* Content Source: [Teams/dynamic-memberships.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/dynamic-memberships.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Yes, but that's a limitation across Teams rather than one specific to dynamic groups. We've added a link to the document describing Team size limits and other limitations.

**Comment by AndreaBarr** [comment]
@DDog80sRocked  It seems like James was able to answer your question. I am going to close this as resolved. If this issue is not resolved please re-open this issue.
