### ISSUE TITLE
What Office 365 plans will be affected with it?

### ISSUE THREAD

**Issue by ILK-estas** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1128]
My company uses Business Premium. Tried to convert Team group to Dynamic, but get an error. :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a578ddb-6494-9bda-529e-0156e5ab7c30
* Version Independent ID: 57d519c9-90f0-873d-ffef-589f0b3b3ac9
* Content: [Overview of dynamic membership for teams](https://docs.microsoft.com/en-us/microsoftteams/dynamic-memberships)
* Content Source: [Teams/dynamic-memberships.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/dynamic-memberships.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Do you have the AD License described as a prerequisite?

**Comment by ILK-estas** [comment]
Nope... Only what comes with o365BP...
Didn't find that in the article (read it in rush).
Thanks!
