### ISSUE TITLE
Suggest a modified SQL view to get the report data

### ISSUE THREAD

**Issue by georgerozgonyigmailcom** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#113]
The below SQL views eliminate the duplicated records in the original script and add some technical data to the submitted user response (IP, client, client type, etc) 

dbo.a_CfR

SELECT        SUBSTRING(Submitter.URI, CHARINDEX('@', Submitter.URI) + 1, LEN(Submitter.URI)) AS Domain, Submitter.URI, CQF.SubmissionTime, CQF.Rating, dbo.a_CF1.TokenDescription, CQF.FeedbackText, 
                         dbo.Session.ConferenceDateTime, dbo.Session.StartTime, dbo.Session.EndTime, Endpoint_1.OS AS CallerEndpoint, dbo.Endpoint.OS AS CalleeEndpoint, UserAgent_1.UserAgent AS CallerUserAgent, 
                         dbo.UserAgent.UserAgent AS CalleeUserAgent, Callee.URI AS CeeURI, Caller.URI AS CerURI, Callee.LastPoorCallTime, eR_IP.IpAddress AS eR_IP, Med.CallerPort AS eR_Port, dbo.IpAddress.IpAddress AS ee_IP, 
                         Med.CalleePort AS ee_Port, dbo.Session.DialogCategory
FROM            dbo.CallQualityFeedback AS CQF INNER JOIN
                         dbo.Session ON CQF.ConferenceDateTime = dbo.Session.ConferenceDateTime AND CQF.SessionSeq = dbo.Session.SessionSeq INNER JOIN
                         dbo.[User] AS Caller ON dbo.Session.CallerPAI = Caller.UserKey INNER JOIN
                         dbo.[User] AS Callee ON dbo.Session.CalleePAI = Callee.UserKey INNER JOIN
                         dbo.[User] AS Submitter ON CQF.FromURI = Submitter.UserKey INNER JOIN
                         dbo.MediaLine AS Med ON dbo.Session.ConferenceDateTime = Med.ConferenceDateTime AND dbo.Session.SessionSeq = Med.SessionSeq INNER JOIN
                         dbo.IpAddress AS eR_IP ON Med.CallerIPAddr = eR_IP.IpAddressKey INNER JOIN
                         dbo.IpAddress ON Med.CalleeIPAddr = dbo.IpAddress.IpAddressKey INNER JOIN
                         dbo.Endpoint ON dbo.Session.CalleeEndpoint = dbo.Endpoint.EndpointKey INNER JOIN
                         dbo.Endpoint AS Endpoint_1 ON dbo.Session.CallerEndpoint = Endpoint_1.EndpointKey INNER JOIN
                         dbo.UserAgent ON dbo.Session.CalleeUserAgent = dbo.UserAgent.UserAgentKey INNER JOIN
                         dbo.UserAgent AS UserAgent_1 ON dbo.Session.CallerUserAgent = UserAgent_1.UserAgentKey LEFT OUTER JOIN
                         dbo.a_CF1 ON CQF.ConferenceDateTime = dbo.a_CF1.ConferenceDateTime

Sub select

dbo.a_CF1

SELECT        CT.ConferenceDateTime, CT.SessionSeq, Tf.TokenDescription
FROM            dbo.CallQualityFeedbackToken AS CT LEFT OUTER JOIN
                         dbo.CallQualityFeedbackTokenDef AS Tf ON CT.TokenId = Tf.TokenId
WHERE        (CT.TokenValue <> 0)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d678ef9-0f4c-873f-e437-cef92841ebff
* Version Independent ID: 04e7966a-2bee-11a2-c3be-6ef1b0a100cd
* Content: [Rate my Call in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/manage/health-and-monitoring/rate-my-call)
* Content Source: [Skype/SfbServer/manage/health-and-monitoring/rate-my-call.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/health-and-monitoring/rate-my-call.md)
* Service: **unspecified**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Per one of our escalation engineers: 
1)	t-SQL is not complete. There are just two views (even create view statement is missing) that could be potentially used in audio and video t-SQL queries to provide similar non duplicated information
2)	I agree that is good way as removes duplicates and provide extra info however this particular statement is not very optimized for large tables ‘SUBSTRING(Submitter.URI, CHARINDEX('@', Submitter.URI) + 1, LEN(Submitter.URI)) AS Domain,’ Maybe removing this field would be good idea
3)	Author should complete t-SQL (including create view) and rewrite audio and video t-SQL query to make use of this new view

**Comment by georgerozgonyigmailcom** [comment]
Hi 
You are right, it is not a complete solution. It meant to correct the suggested Select command in the Technet article only. (That is why it is a simple command rather than a script.)

Also you are right the sip domain can be omitted from here and added later in Power Bi / Power Qry step if needed. 
On the other hand it does not do too much harm as we not expect to receive millions on call quality feedback records. 

Regards 

George Rozgonyi

**Comment by jambirk** [comment]
If you're suggesting a modification of what's there, please make the specific change. If It clears the vetting process we'll incorporate it.
