### ISSUE TITLE
Really?

### ISSUE THREAD

**Issue by NormundsKarklins** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1134]
Obviously adding the domain to tenant whitelist resolves most of if not all email deliverability issues, however is that really a practicable solution at present time, considering the 'well-known' nature of the domain in question? Will it never be spoofed by anyone??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43bc0cae-682a-7227-35d6-d3c37545a3a4
* Version Independent ID: fbcd00ac-8899-fb95-28aa-dfc523b81c65
* Content: [Add the Microsoft Teams SMTP domain as an allowed sender domain in Exchange Online](https://docs.microsoft.com/en-us/microsoftteams/smtp-accepted-domain)
* Content Source: [Teams/SMTP-accepted-domain.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/SMTP-accepted-domain.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@NormundsKarklins Thank you for this inquiry

I am not sure of the answer for this domain whitelist inquiry. Let me get this over to the Teams writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by kenwith** [comment]
@NormundsKarklins - thank you for taking the time to submit feedback on the content. I can work with you to figure out how to make the content better.

**Comment by kenwith** [comment]
@NormundsKarklins - I am reading through the article and thinking what could be done to the article to make it better and address your concern about spoofing. Do you have any suggestions? As you mentioned, any domain could be spoofed to avoid a spam filter. 

Perhaps the best thing to do is add a note to the article that if you prefer not to whitelist the domain then you need to make sure your users check their spam folder? Open to any suggestions here. Thanks.

**Comment by NormundsKarklins** [comment]
In my humble opinion, Teams ‘as a service’ should not transpose the responsibility to Customers for this matter in first place.

Apologies for being unable to provide a perfect suggestion here – I do not work at Microsoft and I have no experience in interacting with Exchange ‘Forefront’ (aka EOP) or ATP people of Microsoft 365 platform (where the false-positive spam detection apparently can occur).

If it is impractical to achieve satisfactory cooperation with the Microsoft cloud service teams in charge for spam detection, I’d personally think of a possibility to insert into message headers of Teams a tenant-configurable text string which then respective mailserver admins could use to ‘whitelist’ the actual messages from Teams.
It is a bit old school approach in the modern days of domain validation means such as DMRD/DKIM/SPF being available, of course, but if the circumstances require additional actions to assure messages from Teams are not junked by Recipients, then ‘wholesale’ domain whitelisting, in my humble opinion, should be the last resort in case of a well-known source domain.

Sincerely,

N.Karklins

**Comment by kenwith** [comment]
@NormundsKarklins - this is great information and I agree with you that there needs to be a better way to handle this. I know the Teams group gets their user information from a place called User Voice ( microsoftteams.uservoice.com ) and they do work across teams to focus on the user experience and not the internal organization. In the past Microsoft was a very different place but now it seems the organizational structure takes a far back seat to the customer needs and experience.

I did a search on 'whitelist' on the User Voice, https://microsoftteams.uservoice.com/forums/555103-public?query=whitelist and I am going to go through and up vote similar issues too. If you don't mind taking a look and if you would want to open another specific issue please let me know and I will use my up votes to up vote it. I think it is really good feedback that the Teams group should hear. I will close this out and head over to User Voice but you can continue to reply here if you want to let everyone know of a specific User Voice that we can all up vote. Thanks again for taking the time to improve the content and the product. I hear first hand how much everyone around Microsoft and the community appreciates it.
