### ISSUE TITLE
_sipinternaltls._tcp. should be an SRV record. It is marked as a A/AAAA

### ISSUE THREAD

**Issue by swinster** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1137]
_sipinternaltls._tcp. should be an SRV record. It is marked as a A/AAAA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94881ba-6f06-a946-47a3-c9c683ddd303
* Version Independent ID: 081684f7-3570-fdfd-c32d-90b6e07d81b4
* Content: [DNS requirements for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/network-requirements/dns)
* Content Source: [Skype/SfbServer/plan-your-deployment/network-requirements/dns.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/network-requirements/dns.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by AndreaBarr** [comment]
@swinster Thank you for pointing this out

I will get this A/AAAA record issue over to the Skype for Business writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by jambirk** [comment]
The article was updated recently, this was addressed. Closing the issue.
