### ISSUE TITLE
Statement above not clear

### ISSUE THREAD

**Issue by jasonfare** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1141]
Under Enable/Disable recording transcription for users is a statement that says it's disabled enabled by default.  I believe it's actually Disabled, but I was looking for the default setting.

"Unless you have assigned a custom policy to the users, they get Global policy, which has disabled enabled by default."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@jasonfare Thank you for this inquiry

I will get this request for clarification over to the Teams writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@get-itips Could you please investigate this issue?

**Comment by get-itips** [comment]
Yes. Of Course

**Comment by jasonfare** [comment]
While fixing what mschultz-bcbsne requested looks to be done, what I originally opened this for has not.  The article still says "disabled enabled by default"

**Comment by get-itips** [comment]
@jasonfare hello, how are you?
It takes time from the moment a PR is created and  merged and it is actually live.
For example, now the live version shows the correct sentence.
Thanks

**Comment by scanum** [comment]
@jasonfare  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
