### ISSUE TITLE
Option not available

### ISSUE THREAD

**Issue by jasonfare** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1142]
In "Steps when you are unassigning a service phone number for a conferencing bridge"  Step 3, it states that you click unassign.  While the option is there, this is a dedicated toll conference bridge and the option to remove is grayed out (it is not the default and is not assigned to any users).  When you hover over it, a message shows "Default or shared numbers can't be unassigned from the bridge.  To unassign dedicated toll numbers, please contact support."  So it would seem that this capability is no longer available to end users and can only be performed by Microsoft Support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 485c3bcb-41f9-6873-bd04-2f4110d07655
* Version Independent ID: df1cd65a-1636-73b7-3245-674dfb6b86cf
* Content: [Change the phone numbers on your Audio Conferencing bridge](https://docs.microsoft.com/en-us/microsoftteams/change-the-phone-numbers-on-your-audio-conferencing-bridge)
* Content Source: [Teams/change-the-phone-numbers-on-your-audio-conferencing-bridge.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/change-the-phone-numbers-on-your-audio-conferencing-bridge.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@jasonfare Thank you for this feedback

I am not sure why the steps and what you are seeing are different. Let me get this over to the Teams writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

@chuckedmonson Could you take a look at this for us since your covering for some of Tony's things?

**Comment by scanum** [comment]
@chuckedmonson Any updates on this? Thanks!

**Comment by tonysmit** [comment]
@ruizoscar - Can you help on this issue? And then let us know how to correct this in the article? Thanks, Tony

**Comment by scanum** [comment]
@ruizoscar Any updates on this?

**Comment by ruizoscar** [comment]
Apologies for the delay, just set a pull request with the suggested corrections.

Thanks,
Oscar

**Comment by scanum** [comment]
@ruizoscar Appreciate it! Could you please link PR? Thanks!

**Comment by scanum** [comment]
@ruizoscar Any updates on this? Thanks!

**Comment by tonysmit** [comment]
@ruizoscar - Do you have the PR for reference where you made the changes? I can merge it or can you provide me with the changes and I will publish them for you. Thanks, Tony

**Comment by ruizoscar** [comment]
Hi,

I sent the PR and I believe it was already merged: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/2168

Thanks,
Oscar



Thanks,
Oscar

**Comment by ruizoscar** [comment]
Hi,

I sent the PR and I believe it was already merged: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/2168

Thanks,
Oscar

**Comment by scanum** [comment]
@jasonfare Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
