### ISSUE TITLE
Skype For Business 2019 Auto Attendant

### ISSUE THREAD

**Issue by ChrisBell1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1143]
Hi there,

I'm currently working on upgrading an environment to SfB2019 which will mean that Cloud Voicemail will be used for any accounts migrated to the new SfB Pool (currently users are on Lync2013).

We require the use of Auto Attendants and I see the support is coming soon for on prems use of the Cloud AA which is great.

If I leave the Exchange AA Contact on our existing Lync2013 pool, will the users on the SFB2019 pool be able to use it and access their voicemail and vice versa?

Cheers,

**Comment by jambirk** [comment]
See https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-cloud-voicemail#migration-and-interoperability which should explain when and why you'd migrate Exchange UM to Cloud VM or Cloud AA. It depends largely on the version of Exchange your users are set up with.

**Comment by AndreaBarr** [comment]
@ChrisBell1 Did what James referred you to resolve your issue?

**Comment by get-itips** [comment]
Hi @ChrisBell1 we appreciate your comments.
Have you seen the article that @jambirk sent to you? does it answer your question?
Thank You

**Comment by jambirk** [comment]
There were some delays with release of call queues and auto attendants, but the features should go live later this month.

**Comment by yogkumgit** [comment]
@get-itips  and @jambirk  Thank you very much for the contribution and sharing this explanation. @ChrisBell1 Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
