### ISSUE TITLE
Anycast VIP not responding to pings

### ISSUE THREAD

**Issue by ang216** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1146]
Hello,

The Anycast VIP 13.107.8.2 indicated in this article is currently not responding to pings from North Eastern US and Bermuda, but it is responding to pings from Austin, Texas. Are there plans to resolve this, or will the IP address change? We use this IP address to monitor connectivity performance to the Microsoft Network Edge at all of our locations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66e291cc-5a58-f435-d6c3-b8ba4973f13a
* Version Independent ID: 9ba1e56d-54b2-05d6-fe15-95677e2c0967
* Content: [Media Quality and Network Connectivity Performance](https://docs.microsoft.com/en-us/skypeforbusiness/optimizing-your-network/media-quality-and-network-connectivity-performance)
* Content Source: [Skype/SfbOnline/optimizing-your-network/media-quality-and-network-connectivity-performance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/optimizing-your-network/media-quality-and-network-connectivity-performance.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by khorne3** [comment]
Hi @ang216! I just wanted to follow-up with you on this -- I'm sorry for the delay! Are you still seeing this issue? It appears that the Anycast VIP address provided should be responding to all pings, so if this isn't the case, you may need to get in touch with your sysadmin (or your sysadmin may need to escalate to Microsoft support). Thanks!

**Comment by get-itips** [comment]
Hi @ang216 as @khorne3 says, do you still face this issue? if yes, I would suggest to contact Support services.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and guiding the him through. @ang216 
Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
