### ISSUE TITLE
"Remove accounts that might not belong" not working

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1147]
Even after manually removing all service accounts from the team, they are being added back in to the team automatically. How can this be prevented? We can't delete them, but we also don't want them to appear in the team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by erlendwtf** [comment]
I'm having the same issue

**Comment by get-itips** [comment]
Hi @thedrum808 How are you? 

I tested the scenario that you describe and did not experience the same, as this doesn't seem to be an issue with documentation, @yogkumgit will redirect you to Microsoft Support, they could help you better with the situation you are facing.

**Thank you**

**Comment by yogkumgit** [comment]
@thedrum808 Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by maxpeet** [comment]
Same here - in the General channel, it announces that all the accounts I previously removed have joined again.  This occurs about a day after I remove them, using the Teams app.  I have over 40 accounts to remove, so it's tedious.
