### ISSUE TITLE
What triggers these reasons?

### ISSUE THREAD

**Issue by alexalpb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1148]
Especially the Client Initiated Deregistration . Which events cause Client Initiated Deregistration? Turning off the laptop or going sleep mode or just killiing the SKype client or signing out... ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3d78ad2-c9b3-ceb9-d0f1-3523cd71b287
* Version Independent ID: d1c31b1c-d3de-4894-c55b-8e697f17f7bc
* Content: [DeRegisterType table in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/schema-reference/call-detail-recording-cdr-database-schema/deregistertype)
* Content Source: [Skype/SfbServer/schema-reference/call-detail-recording-cdr-database-schema/deregistertype.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/schema-reference/call-detail-recording-cdr-database-schema/deregistertype.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hi @alexalpb How are  you? Hope you are doing just great.

Client initiated deregistration is any action initiated by the user like for example the actions you described. So as you might know, the server can then indicate a caller that the callee is currently unavailable and avoid sending unnecessary packets.
Essentially this action are based on SIP Protocol, the protocol that uses Skype For Business for communications.

Hope this information helps you.

Thank you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @alexalpb 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
