### ISSUE TITLE
Teams Configuration Latency

### ISSUE THREAD

**Issue by dhoegl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1149]
It seems there is a delay in updating the Teams Apps settings when making changes to what apps are viewable from within the Teams site.

Is it possible to find out from the PG whether there is a known time-delay before seeing these changes take effect? I've not waited too long (~5 minutes after changing the settings), but unsure if I should wait xx minutes/hours before seeing the changes take effect.
Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 143108bb-d6e6-48a8-a7cb-d11b89ebeaab
* Version Independent ID: 145773e2-149e-1c1c-5797-433c13f13b22
* Content: [Admin settings for apps in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/admin-settings)
* Content Source: [Teams/admin-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/admin-settings.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by dhoegl** [comment]
Okay, so I waited about 10 minutes, and noticed that my changes have taken effect. Should this be updated in the documentation? Thanks!

**Comment by get-itips** [comment]
Hi @dhoegl 
**Thanks for your feedback! We really appreciate it!**
I tested the scenario you described and the app showed up with no delay to users, so in this case we do not see the need to update the documentation to reflect some delay.
**Thank You**

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @dhoegl 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by dhoegl** [comment]
👍🏼
    	
    	

    	Thank you!
    
  




On Mon, Mar 11, 2019 at 6:22 AM -0400, "Yogesh Kumar" <notifications@github.com> wrote:












@get-itips  Thank you very much for the contribution and sharing this explanation. @dhoegl

Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
