### ISSUE TITLE
no desktop shortcut

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1150]
Neither the last version or this version creates a shortcut to teams for us.  I have tested on 4 different windows 10 computers.   I use the noAutoStart=true switch to deploy from SCCM as we prefer to make usage optional.  There doesn't appear to be anything in the start menu or on the desktop.  I found that if I browse to the exe in program files and run it, a shortcut is then created on the desktop only.  

I have also manually run the installer with no switches and still no shortcuts, even after a reboot.  Is there something special about how this shortcut is created.  I would assume you just create one in "C:\programdata\Microsoft\Windows\Start Menu\Programs" OR C:\Users\Public\Desktop - nothing in either.  We do have a quite hardened SOE with things like CMD and run and runonce reg keys blocked but I couldn't find anything there either.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b13006b-d1de-8bc7-e0c6-b7022af0e731
* Version Independent ID: d29dae65-bb28-8767-cfd7-07d2ed5fd460
* Content: [Install Microsoft Teams using MSI](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment#how-the-microsoft-teams-msi-package-works)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @Lester-Hewett
* Microsoft Alias: **lehewe**

**Comment by AdamFlowers** [comment]
Is there a switch for the MSI to not add a desktop shortcut? I used the base msi options (msiexec /i Teams_windows_x64.msi OPTIONS="noAutoStart=true") and we get the desktop shortcut, but this not the behavior we want.

**Comment by get-itips** [comment]
Hi @PaulKlerkx and @AdamFlowers  How are you? Thanks for your feedback, we appreciate it a lot.
From the issue description, I see that your inquiries are better for Microsoft Support, @yogkumgit will kindly redirect you to it.
**Thank You!**

**Comment by yogkumgit** [comment]
@PaulKlerkx Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
