### ISSUE TITLE
Outlook Web javascript error preventing the page to complete.

### ISSUE THREAD

**Issue by intensite** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1151]
Outlook Web javascript error preventing the page to complete.  As a result the spinning icon on chrome tab never goes away.  

I tracked the issue to this page:
https://webpoolbl20a24.infra.lync.com/ucwa/oauth/v1/applications/112963265580/events?ack=52&key=

The page somehow never returns and always has the pending status code.
![image](https://user-images.githubusercontent.com/7981384/49236932-2c2f2d00-f3cb-11e8-9d4a-127958a9e38f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 427c5507-02f5-3f2a-cc5d-dca1409fd7c8
* Version Independent ID: c3f76881-a543-e4dc-c8ed-6e2a1fe5d402
* Content: [Skype for Business Online support in Outlook on the web](https://docs.microsoft.com/en-us/skypeforbusiness/set-up-skype-for-business-online/skype-for-business-online-support-in-outlook-on-the-web)
* Content Source: [Skype/SfbOnline/set-up-skype-for-business-online/skype-for-business-online-support-in-outlook-on-the-web.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-skype-for-business-online/skype-for-business-online-support-in-outlook-on-the-web.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by yogkumgit** [comment]
@intensite  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link https://www.youtube.com/watch?v=puuOy0sEg1Y
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with your valuable piece of information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
