### ISSUE TITLE
Link from Message Centre points here but no relevant info on the page.

### ISSUE THREAD

**Issue by alexlushsevernunival** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1156]
I got linked to here (https://docs.microsoft.com/en-us/MicrosoftTeams/quality-of-experience-review-guide#diagnostic-alerts) from an O365 Message Centre post.
The issue highlighted was 'Usage of TCP for media transport is causing a poor Skype for Business experience.' however the Diagnostic Alerts section does not mention this issue or provide me more information on it. 
Please update this document to provide information on remediating the 'Usage of TCP for media transport is causing a poor Skype for Business experience.' issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a04f5de-2679-37c7-7d00-607471ea516d
* Version Independent ID: c96ec0af-910a-d9f8-9d3b-95564b39d7fa
* Content: [Quality of Experience Review Guide for Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/quality-of-experience-review-guide#diagnostic-alerts)
* Content Source: [Teams/quality-of-experience-review-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/quality-of-experience-review-guide.md)
* Service: **msteams**
* GitHub Login: @rmw2890
* Microsoft Alias: **MyAdvisor**

**Comment by get-itips** [comment]
Hi @alexlushsevernunival thanks for taking the time to submit your valuable feedback.
I checked the information in the document and I found information regarding the impact of using TCP in Skype For Business, please review the information in this section https://docs.microsoft.com/en-us/MicrosoftTeams/quality-of-experience-review-guide#tcp to see if it helps to resolve your problem.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @alexlushsevernunival  Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by alexlushsevernunival** [comment]
@get-itips Thanks for the link, that's the information I was looking for!! I'll go ahead and close this now.
