### ISSUE TITLE
Clarification regarding sampling rate support for SkypeforBusiness Audio Specification Personal_Devices_Custom_Processing

### ISSUE THREAD

**Issue by a-martirosyan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1157]
I have a question regarding audio sample rate restriction that is set in SkypeforBusiness_AudioSpecification_Personal_Devices_Custom_Processing_3_0_Final.pdf

The document states:
---------------------------------------------------
Skype will enable the offloading only on products verified to provide sufficient quality. The logo specification testing is one and most important input to this decision, but other checks can be included depending on the product group and complexity of the product. The enabling of 3rd party audio processing object processing can be rejected or revoked in some cases listed below:
-  Custom processing enables only wideband audio (16kHz sampling) whereas Skype processing can enable super wideband audio (24kHz sampling) in the same device.
------------------------------------------------
I wonder what do you mean saying "enable wide band audio"? If actual processing of my app is done on 16k, but it works with any sampling rate by down/upsampling to 16k if needed, can I say that my app enables super wideband?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6da8e2d9-613a-570b-9755-5161bc39acf7
* Version Independent ID: 5ef5dc6f-f1af-2e6f-350a-4a65bf9e8a8d
* Content: [Skype for Business and Teams certification program](https://docs.microsoft.com/en-us/SkypeForBusiness/certification/overview)
* Content Source: [Skype/SfbPartnerCertification/certification/overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbPartnerCertification/certification/overview.md)
* Service: **skype-for-business**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by dougand-MSFT** [comment]
Hello @a-martirosyan , if you work for one of our active partners in the certification program please forward questions about the specification through the regular communication that we already have. Otherwise if we believe we can make changes to clarify this question we'll do so on the next release of the specification.

**Comment by a-martirosyan** [comment]
@dougand-MSFT I don't have another communication channel. I'm just interested in evaluating my technology to see where it stands in terms of skype test spec. This is one of the questions that was not clear from the doc. I also have another question regarding test vectors that are assumed to be taken as cleen speech examples (page 73). It would be good to have opportunity to clarify these. How can I clarify these questions now?

**Comment by dougand-MSFT** [comment]
Hello @a-martirosyan we currently discuss the specs in detail with our active certification partners, but this is not a breadth program so we are not able to answer general spec questions in this forum.

**Comment by a-martirosyan** [comment]
@dougand-MSFT can you pls point me to the right forum/person who can clarify these things for me?
