### ISSUE TITLE
Voicemail button not available when user logged in to Basic client

### ISSUE THREAD

**Issue by dipinn26592** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1159]
When a EV enabled user logs in to Skype for Business **Baisc** client and another user searches for this user and Call to voicemail button is missing ( search > right click > call > voicemail button missing )

suggestion for correction : 
- we can add granularity of each feature which wont work
Or
- Add a generalized statement " some of the advanced EV feature wont work"

Impact  : user cannot leave the voicemail directly

**Comment by get-itips** [comment]
Hi @dipinn26592 can you kindly reference the document you are talking about in this issue?
Thanks for sharing this feedback, we really appreciate it.

**Comment by yogkumgit** [comment]
@dipinn26592  Thank you very much for oping the issue. @get-itips could help if  reference document would be available. If you find the one please feel free to reopen this issue. Thanks again for taking out some time to open this issue.

**Comment by dipinn26592** [comment]
https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/desktop-feature-comparison

**Comment by get-itips** [comment]
Hi @dipinn26592 thanks for sharing the referenced document.
I'll take a look at it and if it needs some edits I'll do it. Thank you again
