### ISSUE TITLE
Updated PowerShell Requirements

### ISSUE THREAD

**Issue by ndambrosio** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1162]
Hello, Tony,
I think we need to update the PowerShell and Windows Management Framework requirements for the SfBO module.  PowerShell 5.1 is now a prerequiste for running the latest SfBO Module.  The Windows Management Framework version would also need to be updated depending on the OS as well.

Thanks,
Nick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b28923a-a756-398d-87b9-a4c6b0290297
* Version Independent ID: 1e168778-e113-987f-af44-7040ae007bc8
* Content: [Download and install Windows PowerShell 3.0](https://docs.microsoft.com/en-us/skypeforbusiness/set-up-your-computer-for-windows-powershell/download-and-install-windows-powershell-3-0)
* Content Source: [Skype/SfbOnline/set-up-your-computer-for-windows-powershell/download-and-install-windows-powershell-3-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-your-computer-for-windows-powershell/download-and-install-windows-powershell-3-0.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@ndambrosio  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
