### ISSUE TITLE
Business Server 2015 with CU8 update

### ISSUE THREAD

**Issue by ChenRahimi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1164]
Hi,
Can't find CU8 download location, CU7 (July 2018) shown as the latest version.

It there any other way to address this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 006dc464-2228-0d91-8726-223770c91411
* Version Independent ID: 28877a22-b558-4da6-551b-9bcd9bac96c4
* Content: [Choose your upgrade journey - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/upgrade-and-coexistence-of-skypeforbusiness-and-teams#upgrade-journeys)
* Content Source: [Teams/upgrade-and-coexistence-of-skypeforbusiness-and-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-and-coexistence-of-skypeforbusiness-and-teams.md)
* Service: **msteams**
* GitHub Login: @lsOmi
* Microsoft Alias: **lsomi**

**Comment by khorne3** [comment]
Hi @ChenRahimi. CU7 is the most recent update for Skype for Business Server 2015. I'll fix the doc to reflect this.

**Comment by ChenRahimi** [comment]
Hi,

There is any alternative way to move users to Teams smoothly while using
Skype for Business Server 2015?

**Comment by get-itips** [comment]
Hi @ChenRahimi at the time, CU8 is available here https://www.microsoft.com/en-us/download/details.aspx?id=47690 thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ChenRahimi 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
