### ISSUE TITLE
Teams or チーム？

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1165]
Teams or チーム？

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 01f00359-e536-fdd5-2c6e-859247d6f578
* Version Independent ID: dbba7a52-9c65-dc96-c0b6-1aed6c414000
* Content: [ユーザーが積極的にマイクロソフトのチームでマイクロソフトのチームでのメリットをもたらします](https://docs.microsoft.com/ja-jp/microsoftteams/continue-journey)
* Content Source: [Teams/continue-journey.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.ja-JP/blob/live-sxs/Teams/continue-journey.md)
* Service: **msteams**
* GitHub Login: @dearbeen
* Microsoft Alias: **dearbeen**

**Comment by samanthaw** [comment]
@hyoshioka0128 this is fixed

**Comment by jamesrhea** [comment]
@AndreaBarr this issue can be closed.

**Comment by hyoshioka0128** [comment]
"チーム" needs to be replaced with "Teams" 

https://docs.microsoft.com/ja-jp/microsoftteams/continue-journey

**Comment by jamesrhea** [comment]
@hyoshioka0128, is there a specific location in this article you're referring to? When I search the page for チーム I don't find any instances.

**Comment by hyoshioka0128** [comment]
@jamesrhea .The problem part has returned from Japanese to English.(Sorry for my poor English.)

**Comment by hyoshioka0128** [comment]
The problem part has returned from Japanese to English.

**Comment by samanthaw** [comment]
@hyoshioka0128 the issue is fixed
