### ISSUE TITLE
Remove "& #39"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1166]
アップグレードする旅は、組織 & #39 に適した; ビジネス要件でしょうか。
→アップグレードする旅は、組織に適したビジネス要件でしょうか。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 006dc464-2228-0d91-8726-223770c91411
* Version Independent ID: 28877a22-b558-4da6-551b-9bcd9bac96c4
* Content: [アップグレードの旅では、マイクロソフトのチームを選択します。](https://docs.microsoft.com/ja-jp/microsoftteams/upgrade-and-coexistence-of-skypeforbusiness-and-teams)
* Content Source: [Teams/upgrade-and-coexistence-of-skypeforbusiness-and-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.ja-JP/blob/live-sxs/Teams/upgrade-and-coexistence-of-skypeforbusiness-and-teams.md)
* Service: **msteams**
* GitHub Login: @lsOmi
* Microsoft Alias: **lsomi**

**Comment by khorne3** [comment]
Hi @hyoshioka0128. Thank you for logging an issue! Would you be able to translate your request to English?

**Comment by jambirk** [comment]
via Bing translator: 
"Upgrade your journey suitable for your organization & #39;
Is it a business requirement? Is the journey to be upgraded a business requirement for your organization?"

**Comment by hyoshioka0128** [comment]
"Which upgrade journey is suitable to your organization's business requirements?"
　→"organization & #39; s"
"& #39;" is the char code for single quote in HTML
