### ISSUE TITLE
Desktop Icon keep showing up after deletion 

### ISSUE THREAD

**Issue by Perazzi97** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#117]
After installation the desktop icon for Team keeps showing up after a user deletes it after a logoff or reboot. Is there a way to keep this behavior from happening?

**Comment by tonysmit** [comment]
Hi. Thanks for the feedback. I'm investigating this and trying to find a PM that I can assign this issue. Thanks, Tony

**Comment by tonysmit** [comment]
@juturu and @voltarone  Do you have any feedback on this issue? If you are assign an issue, you must help the customer find a resolution. If it's a bug for engineering create a bug for them, if not and a topic needs updated, you can fix the article and issue a PR. Lastly, if it's a no repo or can't be fixed, then let the customer know and close this out.

**Comment by kenwith** [comment]
@Perazzi97 - sorry for the delay on this and thank you for submitting feedback. It has been a very long time and I am hoping you have already resolved this issue. If you haven't,  I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
