### ISSUE TITLE
Direct call pickup

### ISSUE THREAD

**Issue by Root-wuxl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1172]
Is sfb support direct call pickup？

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b0d958a-9d50-5320-5601-2479ad501515
* Version Independent ID: 95968d67-8b43-0725-bb8c-b1fbf9a3f277
* Content: [Plan for Group Call Pickup in Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/enterprise-voice-solution/group-call-pickup)
* Content Source: [Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/group-call-pickup.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/group-call-pickup.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by get-itips** [comment]
Hi @Root-wuxl **Thanks for your feedback.**

Direct Call Pickup is the action by, dialing the extension of the user that is receiving the call, you pick up the call. Is that what you are talking about ?
Group Call Pickup is different in a way that you have to dial a special virtual extension that have no user or phone assigned to them, that is the only difference, you could also pick up a call of a colleague, as long as he is part of that Call Pickup Group.

**Hope this information helps you!**

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Root-wuxl 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
