### ISSUE TITLE
Avalible in teams admin portal?

### ISSUE THREAD

**Issue by WithHolm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1173]
Is there any plans of adding this functionality to admin.teams.microsoft aswell (also no requirement for being group admin, as this site would only be avalibe for org-admins)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a2187e-570d-f235-3536-69df8eaa906a
* Version Independent ID: da949f22-1617-c737-d5a4-5c51704443e8
* Content: [Enhance Existing Office 365 groups with Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/enhance-office-365-groups)
* Content Source: [Teams/enhance-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enhance-office-365-groups.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by get-itips** [comment]
Hi @WithHolm **thanks for your feedback!**

Currently, this functionality is inside Teams client, I suggest you add this idea [here](https://microsoftteams.uservoice.com/forums/555103-public)

Thank you!

**Comment by yogkumgit** [comment]
@WithHolm  Thank you very much for your kind feedback, as advised by @get-itips please visit the User voice link. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
