### ISSUE TITLE
"Enrolled in Teams"

### ISSUE THREAD

**Issue by realmnm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1174]
Hi,
Could you please elaborate what devices is "certified" and can be expected to show up in the device portal.
When I read the instructions it says:
-"Devices must be certified for Teams and enrolled in Teams. A device is automatically enrolled the first time a user signs in to Teams on the device."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a627b5d-3edc-1add-b921-1dcd49c38653
* Version Independent ID: a2e2bd3a-31c0-471a-05fb-fd64bd942c4a
* Content: [Manage your devices in Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/device-management)
* Content Source: [Teams/device-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/device-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by aaronhauber** [comment]
Is there a way to delete devices from the portal after the devices have been retired?

**Comment by get-itips** [comment]
Hi @realmnm **thanks for your feedback**.
You can find certified devices in the same section as this document  that is called "Supported Devices", for example https://docs.microsoft.com/en-us/microsoftteams/phones-for-teams and as the document says, _A device is automatically enrolled the first time a user signs in to Teams on the device_.

@aaronhauber this option is not currently present in Teams Admin Portal

Hope this information has helped you!

**Thank You!**

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @realmnm 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by pik10** [comment]
I had to factory reset one yealink phone.  After the reset, the phone shows twice.  One is online when I signed in and the other shows offline.  I don't see any option to delete the offline phone.

**Comment by westovsb** [comment]
@pik10 I have had to do the same thing. It is really annoying to have the same phone listed twice. How did you factory reset your device? I have another device that the screen is blinking "Unfortunately, Teams has stopped." Not sure how to do anything when the screen is dead.

**Comment by pik10** [comment]
I went to the phone's web configuration page by using it's IP address.  If you know the phones IP address you may be able to login.  I used the default user name admin. From there I was able to factory reset the phone.

**Comment by westovsb** [comment]
All I get when I do that is "This site can’t be reached (IP address) took too long to respond." Could it have been assigned a new ip?

**Comment by pik10** [comment]
You can probably find the IP address in your DHCP server.

**Comment by westovsb** [comment]
Yes, I just figured that out. Thanks! I will be calling Yealink.
