### ISSUE TITLE
Coexistance setting not visible for any of our clients

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1175]
The Coexistance mode dropdown in this interface lists "Islands" and "Skype for Business only". Opened a ticket with MS Support and they did not have an ETA for when the portal would have these options for all tenants.
Use the powershell commands below to view and change the global policy:

# Current Upgrade Policy
Get-CsTeamsUpgradePolicy -Identity Global

# Change Global Policies
Grant-CsTeamsUpgradePolicy -PolicyName tag:UpgradeToTeams
Grant-CsTeamsInteropPolicy -PolicyName tag:DisallowOverrideCallingTeamsChatTeams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffbf0bfd-c15e-b10b-0cc9-6a27ac1e6634
* Version Independent ID: 58575371-9e09-fadb-76f6-7491df8580a3
* Content: [Setting your coexistence and upgrade settings](https://docs.microsoft.com/en-us/MicrosoftTeams/setting-your-coexistence-and-upgrade-settings)
* Content Source: [Teams/setting-your-coexistence-and-upgrade-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/setting-your-coexistence-and-upgrade-settings.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by dariomws306** [comment]
Hi @jonwbstr , thank your for your comment.

Yes, it's true, we still don't have a date when all tenant will get all the upgrade options in the admin center. In this article you can see a note about this:

"If you’re an admin on your Office 365 tenant, you may soon start seeing upgrade options in the Microsoft Teams admin center. Having the option to upgrade doesn’t necessarily mean your organization is ready for this change. For the best user experience, confirm that Teams meets your collaboration and communication requirements, make sure that your network is ready to support Teams, and implement your user readiness plan before upgrading users to Teams."

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @jonwbstr 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
