### ISSUE TITLE
FEs to O365 via HTTPS

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#118]
I would add details to firewall/ports for FE communication with SfBO, especially from CSCP or PoSH.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ce52f6-cec3-8572-2a78-2f4c3419dc28
* Version Independent ID: 44e7910e-d955-1bb1-0f9c-e8047c994bdc
* Content: [Plan hybrid connectivity between Skype for Business Server and Skype for Business Online](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-hybrid-solutions/plan-hybrid-connectivity)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/plan-hybrid-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-hybrid-connectivity.md)
* Service: **unspecified**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by kenwith** [comment]
@TorrenManson - just a quick update. We are still syncing on this and will get this feedback on the backlog. Thank you for reporting!

**Comment by kenwith** [comment]
Please re-open to let us know the gap and we can figure a way to get this resolved. Thank you for taking the time to submit the feedback.
