### ISSUE TITLE
Manage Teams does not show all the Teams in our Tenant

### ISSUE THREAD

**Issue by KatrinW** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1181]
I see most but not all of the Teams in our tenant. Is there a bug causing it to not show all Teams? I still need to rely on PowerShell to produce a report of all Microsoft Teams because this admin center does not appear to show complete information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b51b67a-d89c-723f-3520-87cb2dc93b90
* Version Independent ID: 78d10cbc-d75b-2b02-d49c-2c3fe1579807
* Content: [Manage teams in the Microsoft Teams & Skype for Business Admin Center](https://docs.microsoft.com/en-us/microsoftteams/manage-teams-in-modern-portal)
* Content Source: [Teams/manage-teams-in-modern-portal.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-teams-in-modern-portal.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by MarcoCarampanta** [comment]
@KatrinW
A few steps have just been added to the troubleshooting part of the article, bound to correct this issue.

For now, it would perhaps be best to go through with these steps, until the core issue is adressed.

**Comment by dariomws306** [comment]
Hi @KatrinW and @MarcoCarampanta , thank your for your comments.

Marco is right, they are still in the process. He explained this in detail.

Thanks!

**Comment by yogkumgit** [comment]
@dariomws306  and @MarcoCarampanta Thank you very much for the contribution and sharing this explanation. @KatrinW Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
