### ISSUE TITLE
Meeting Recording includes PSTN calls?

### ISSUE THREAD

**Issue by billvolt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1184]
Does this recording feature all recording of typical inbound and outbound PSTN calls or those not considered meetings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by dariomws306** [comment]
@billvolt , Thank you very much for your feedback. 

PSTN calls are not considered yet.

Considering your valuable feedback, I suggest that you vote on user voice site. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
User Voice Link:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/19013110-audio-call-recording-in-teams

**Comment by scanum** [comment]
@billvolt  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
