### ISSUE TITLE
Outdated procedure?

### ISSUE THREAD

**Issue by StessVictinus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#119]
Hi, for Skype for Business On-Prem the procedure seems to have changed to setup the Skype Consumer federation.
https://pic.lync.com is not valid anymore and instead one should use: https://support.microsoft.com/oas/. Got this info from O365 support:

Thank you for contacting PayOps CBO.  Our team is unable to assist with this request as it falls out of our scope as of 2/6/2018.   For O365 provisioning assistance, please raise a request with Customer Support at the link below: 
 
https://support.office.com/en-us/article/Contact-support-for-business-products-Admin-Help-32a17ca7-6fa0-4870-8a8d-e25ba4ccfd4b?ui=en-US&rs=en-US&ad=US 
 
 
If On Premise, please contact the below: 
 
800.936.4900 - Professional 
https://support.microsoft.com/oas/ 
 
We will now be closing this request.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 1210ada3-644f-fec5-f52e-9644008daf90
* Version Independent ID: 10a6e831-e15e-cc4e-4c01-aedaed9a007c
* Content: [Deploy Skype Connectivity in Skype for Business Server 2015](https://docs.microsoft.com/nl-be/skypeforbusiness/deploy/deploy-skype-connectivity)
* Content Source: [Skype/SfbServer/deploy/deploy-skype-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-skype-connectivity.md)
* Service: **unspecified**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@StessVictinus - thank you for reporting. This issue affects multiple cmdlet links so I will get these updated and report back. Thanks again for taking the time to make the docs better!

**Comment by kenwith** [comment]
@StessVictinus - Did Microsoft support give you a new URI to use instead of the pic.lync.com that is referenced in the article? I am trying to get to the bottom of this one.

**Comment by kenwith** [comment]
@StessVictinus - after investigating I think the link that was given was for you to open a support ticket with Microsoft and not the link to use as per the article states. If I am misunderstanding please re-open this ticket. I also have a number of threads open to validate any changes to the procedure in the article you referenced and anything I find I will update in article. Closing this out but feel free to re-open if I am wrong.
