### ISSUE TITLE
remove "s"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1195]
Request:
 'Decide the timeline of your organization's upgrade journey based on messaging, meetings, and calling business requirements.'

Translate:
　組織 & #39; のタイムラインを決める s アップグレードの旅は、メッセージング、会議、およびビジネス要件を呼び出すことに基づきます。
→組織のタイムラインを決めるアップグレードの旅は、メッセージング、会議、およびビジネス要件を呼び出すことに基づきます。

#1 organization's →"organization & #39; s"
　　"& #39;" is the char code for single quote in HTML
#2 "決める s" → "決める" remove "s"

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 006dc464-2228-0d91-8726-223770c91411
* Version Independent ID: 28877a22-b558-4da6-551b-9bcd9bac96c4
* Content: [アップグレードの旅では、マイクロソフトのチームを選択します。](https://docs.microsoft.com/ja-jp/microsoftteams/upgrade-and-coexistence-of-skypeforbusiness-and-teams#feedback)
* Content Source: [Teams/upgrade-and-coexistence-of-skypeforbusiness-and-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.ja-JP/blob/live-sxs/Teams/upgrade-and-coexistence-of-skypeforbusiness-and-teams.md)
* Service: **msteams**
* GitHub Login: @lsOmi
* Microsoft Alias: **lsomi**

**Comment by samanthaw** [comment]
@hyoshioka0128 this is fixed

**Comment by hyoshioka0128** [comment]
@samanthaw Thanks!
