### ISSUE TITLE
Change the scope to link

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1196]
"&lt;li&gt;&lt;span data-ttu-id="70885-131"&gt;チーム&lt;a href="https://products.office.com/business/office-365-roadmap?filters=microsoft%20teams" data-linktype="external"&gt;のロードマップ&lt;/a&gt;を監視します。&lt;/span&gt;&lt;span class="sxs-lookup"&gt;&lt;span data-stu-id="70885-131"&gt;Monitor the Teams &lt;a href="https://products.office.com/business/office-365-roadmap?filters=microsoft%20teams" data-linktype="external"&gt;roadmap&lt;/a&gt;.&lt;/span&gt;&lt;/span&gt;&lt;/li&gt;"

　チーム&lt;a href="https://products.office.com/business/office-365-roadmap?filters=microsoft%20teams" data-linktype="external"&gt;のロードマップ&lt;/a&gt;

→チームの&lt;a href="https://products.office.com/business/office-365-roadmap?filters=microsoft%20teams" data-linktype="external"&gt;ロードマップ&lt;/a&gt;

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 01f00359-e536-fdd5-2c6e-859247d6f578
* Version Independent ID: dbba7a52-9c65-dc96-c0b6-1aed6c414000
* Content: [ユーザーが積極的にマイクロソフトのチームでマイクロソフトのチームでのメリットをもたらします](https://docs.microsoft.com/ja-jp/MicrosoftTeams/continue-journey)
* Content Source: [Teams/continue-journey.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.ja-JP/blob/live-sxs/Teams/continue-journey.md)
* Service: **msteams**
* GitHub Login: @dearbeen
* Microsoft Alias: **dearbeen**

**Comment by samanthaw** [comment]
@hyoshioka0128 this is fixed

**Comment by jamesrhea** [comment]
@AndreaBarr this issue can be closed.

**Comment by hyoshioka0128** [comment]
＜"の" was deleted＞(Sorry for my poor English.)

　Teams<a href="https://products.office.com/business/office-365-roadmap?filters=microsoft%20teams" data-linktype="external">ロードマップ</a>
→Teamsの<a href="https://products.office.com/business/office-365-roadmap?filters=microsoft%20teams" data-linktype="external">ロードマップ</a>

**Comment by samanthaw** [comment]
@hyoshioka0128 the issue is fixed
