### ISSUE TITLE
Change the scope to link

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1197]
"&lt;p&gt;&lt;span data-ttu-id="5aa69-108"&gt;ビジネスの Skype に中核となる概念、フレームワーク、およびアップグレード ・ パスを含む、チームのアップグレード旅の概要について&lt;a href="https://aka.ms/UpgradeOverview" data-linktype="external"&gt;の概要&lt;/a&gt;を表示します。&lt;/span&gt;&lt;span class="sxs-lookup"&gt;&lt;span data-stu-id="5aa69-108"&gt;View this &lt;a href="https://aka.ms/UpgradeOverview" data-linktype="external"&gt;overview&lt;/a&gt; for an introduction to the Skype for Business to Teams upgrade journey, including core concepts, framework, and upgrade paths.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;"

チームのアップグレード旅の概要について&lt;a href="https://aka.ms/UpgradeOverview" data-linktype="external"&gt;の概要&lt;/a&gt;

→チームのアップグレード旅の概要についての&lt;a href="https://aka.ms/UpgradeOverview" data-linktype="external"&gt;概要&lt;/a&gt;

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f7b32af2-59db-a872-6ed4-fc7b4cd910b3
* Version Independent ID: 38fd3a1a-ee6d-dd63-0de9-5f726d7419cf
* Content: [Skype ビジネスでマイクロソフトのチームのアップグレード](https://docs.microsoft.com/ja-jp/MicrosoftTeams/journey-skypeforbusiness-teams)
* Content Source: [Teams/Journey-SkypeforBusiness-Teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.ja-JP/blob/live-sxs/Teams/Journey-SkypeforBusiness-Teams.md)
* Service: **msteams**
* GitHub Login: @dearbeen
* Microsoft Alias: **dearbeen**

**Comment by jamesrhea** [comment]
@samanthaw, is this a localization issue?

**Comment by samanthaw** [comment]
@jamesrhea looking into it

**Comment by samanthaw** [comment]
@hyoshioka0128 this is fixed

**Comment by jamesrhea** [comment]
@AndreaBarr this issue can be closed. Thanks!
