### ISSUE TITLE
Admin Credentials

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1198]
What kind of admin credentials are required, Global or SkypeForBusiness? please clarify in the text above

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2c88f9f-8e46-966a-30be-5c2506cf578c
* Version Independent ID: 5568a567-2432-f76a-2179-daa43edf257b
* Content: [Plan hybrid connectivity between Skype for Business Server and Skype for Business Online](https://docs.microsoft.com/en-us/SkypeForBusiness/skype-for-business-hybrid-solutions/plan-hybrid-connectivity)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/plan-hybrid-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-hybrid-connectivity.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws306** [comment]
Hi @DeanGross , thank you for your feedback.

Could you specify in what area in the text you think we should clarify this? I couldn't find references about permissions in the article, it's a plan article so I think you will find this kind of information in a "Deploy" article.

**Comment by scanum** [comment]
@DeanGross  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
