### ISSUE TITLE
Lync Online is Obsolete

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1199]
I think that Lync Online is an obsolete term. please update the text as appropriate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2c88f9f-8e46-966a-30be-5c2506cf578c
* Version Independent ID: 5568a567-2432-f76a-2179-daa43edf257b
* Content: [Plan hybrid connectivity between Skype for Business Server and Skype for Business Online](https://docs.microsoft.com/en-us/SkypeForBusiness/skype-for-business-hybrid-solutions/plan-hybrid-connectivity#multi-forest-support)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/plan-hybrid-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-hybrid-connectivity.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
thank you for taking the time to submit feedback on the content @DeanGross  I'll review your recommendation.

**Comment by scanum** [comment]
@DeanGross Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
