### ISSUE TITLE
Need clarification about Other Activity tracked in the report

### ISSUE THREAD

**Issue by aalbisuc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#120]
In the Microsoft Teams user activity report, which other activities are included under Other Activity value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81440b2f-391b-5856-a216-15866f37082a
* Version Independent ID: cdd15cd4-d4ed-c413-e2b9-ebf6dad8b33b
* Content: [Use activity reports for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-activity-reports)
* Content Source: [Teams/teams-activity-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-activity-reports.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by chuckedmonson** [comment]
Regarding Other Activity: Other activity is any action a user takes within the app, such as clicking, scrolling, or hovering inside the app. In our telemetry it's any event with EventInfo_BaseType: panelaction. 
Hope that helps. Thank you.
