### ISSUE TITLE
End User Control 

### ISSUE THREAD

**Issue by Arcass** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1200]
Can the client list be updated to include the Teams client that support the Outbound Caller ID functionality? Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a55064a-f85f-6f10-1e3d-be6177868338
* Version Independent ID: cabebb99-c0a7-a147-0c61-5b32cacc0651
* Content: [How can caller ID be used in your organization](https://docs.microsoft.com/en-us/skypeforbusiness/what-are-calling-plans-in-office-365/how-can-caller-id-be-used-in-your-organization)
* Content Source: [Skype/SfbOnline/what-are-calling-plans-in-office-365/how-can-caller-id-be-used-in-your-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/what-are-calling-plans-in-office-365/how-can-caller-id-be-used-in-your-organization.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by dariomws306** [comment]
Hi @Arcass , thank you for your comment.

Teams client aren't listed because they don't support End User Control of Outbound Caller ID yet.

**Comment by scanum** [comment]
@Arcass  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
