### ISSUE TITLE
Whitelisting Teams

### ISSUE THREAD

**Issue by PeteWestlake** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1201]
All UK public sector bodies are instructed to follow NCSC End User Device Guidance (which is essentially just good practice) https://www.ncsc.gov.uk/guidance/eud-security-guidance-windows-10-1709#applicationwhitelistingsection which instructs enterprises not to install applications to locations where users can write files - which includes AppData. Opening up AppData to allow users to run any application is a massive security hole, but whitelisting by application ID is no way to permit it to run as this can change. Please stop ignoring the feedback on user voice and change the way the installer works so that the application is installed to Program Files. AppData should be for just that - data relating to applications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b13006b-d1de-8bc7-e0c6-b7022af0e731
* Version Independent ID: d29dae65-bb28-8767-cfd7-07d2ed5fd460
* Content: [Install Microsoft Teams using MSI](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @Lester-Hewett
* Microsoft Alias: **lehewe**

**Comment by get-itips** [comment]
Hi @PeteWestlake  **thanks for your feedback, we really appreciate it**.

As this is to inform of issues specific to documentation, it seems that your question is more suitable to User Voice, @yogkumgit will gently direct you to that resource, but if you already created a user voice sugggestion there, I invite you to post the link to it here, so everyone can see it or up vote it.

**Thank you**

**Comment by yogkumgit** [comment]
@PeteWestlake  Thank you very much for your kind feedback. as you are already aware of Uservoice process, you are following it up, we are sure concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
