### ISSUE TITLE
Is PowerShell content coming?

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1207]
The PowerShell "content" here is pretty weak. Any plans to include real steps to accomplish the task? Or maybe link to it here https://docs.microsoft.com/en-us/microsoftteams/change-the-phone-numbers-on-your-audio-conferencing-bridge?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dc173c-0c98-1b94-a2f7-0a34781c985a
* Version Independent ID: a1c44ccb-67f3-f98e-6569-f938e88ddc63
* Content: [Set the phone numbers included on invites in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-the-phone-numbers-included-on-invites-in-teams)
* Content Source: [Teams/set-the-phone-numbers-included-on-invites-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-the-phone-numbers-included-on-invites-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by dariomws306** [comment]
Hi @TorrenManson , thank you for your feedback.

I have add the article on "related content" sections.

**Comment by scanum** [comment]
@TorrenManson  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by jason-ra** [comment]
Agreed that the PowerShell section doesn’t actually say anything. Either add the specific commands related to this topic or remove the section, because in its current form it’s so generic you could add the same words to any page.
