### ISSUE TITLE
Should Teams match OS architecture or Office 2016 architecture?

### ISSUE THREAD

**Issue by mconwell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#121]
Should Teams match OS architecture or Office 2016 architecture?

For example, computers running Windows 10 x64 and Office 2016 x86. Should the Team's architecture match Windows or Office? Or does it matter?

**Comment by tonysmit** [comment]
I'm investigating this with the PMs. I will report back my findings. Thanks, Tony

**Comment by juturu** [comment]
Teams matching Office architecture is better for integration related features.

**Comment by mconwell** [comment]
I think this should be added to the documentation making this clear.  Thank you for your help.

**Comment by tonysmit** [comment]
It says it: 
![image](https://user-images.githubusercontent.com/31015534/39631752-efeb97d2-4f67-11e8-92ed-5fda84fb8a91.png)

**Comment by mconwell** [comment]
I believe this should be modified to include the information @juturu added.   Perhaps:

The architecture (32-bit vs. 64-bit) of Microsoft Teams is agnostic to the architecture of Office that is installed, however matching the Office architecture is better for integrated related features.

**Comment by tonysmit** [comment]
I can do that. If you have feedback, you can click the Edit button and add/remove as needed. I can massage the text then and republish. Thanks, Tony
