### ISSUE TITLE
Is SKU name of Communications Credits correct?

### ISSUE THREAD

**Issue by lyncjp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1214]
In this document, SKU name is described "MCOPSTNPP".
However, it is failed to assign license with this SKU name.
In currently, I think "MCOPSTNC" is correct name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78f8c5e1-7f2e-3f29-2b97-6472c7fc292c
* Version Independent ID: 0b8e237a-c6b2-fe4a-5236-891658fcf1e2
* Content: [Assign Skype for Business and Microsoft Teams licenses](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-and-microsoft-teams-add-on-licensing/assign-skype-for-business-and-microsoft-teams-licenses)
* Content Source: [Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/assign-skype-for-business-and-microsoft-teams-licenses.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/assign-skype-for-business-and-microsoft-teams-licenses.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by dariomws306** [comment]
Hi @lyncjp , thank your for your feedback.

I have created a Pull Request to modify this.

**Comment by scanum** [comment]
@lyncjp  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by lyncjp** [comment]
Thanks!
