### ISSUE TITLE
Documented Import-Csv example does not work

### ISSUE THREAD

**Issue by gtimread** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1216]
The documented example does not work: import-csv subnet.csv | foreach {New-CsNetworkSubnet $_IPAddress -MaskBits $_.mask -Description $_.description -NetworkSiteID $_.NetworkSiteID}. The New-CsNetworkSubnet command requires the Identity parameter.

Instead, you could use the text from Example 2 in this doc, which does work as expected (or adapt example 2 to include a Description in the CSV file and the necessary command): https://docs.microsoft.com/en-us/powershell/module/skype/new-csnetworksubnet?view=skype-ps#examples

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c55d0b8b-1976-63cc-0167-cec4c0a103d7
* Version Independent ID: f2472d70-f7cf-7e2a-e2be-5392c11b3294
* Content: [Deploy network regions, sites and subnets in Skype for Business](https://docs.microsoft.com/en-gb/skypeforbusiness/deploy/deploy-enterprise-voice/deploy-network)
* Content Source: [Skype/SfbServer/deploy/deploy-enterprise-voice/deploy-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-enterprise-voice/deploy-network.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by yogkumgit** [comment]
@gtimread Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
