### ISSUE TITLE
Example Title Names

### ISSUE THREAD

**Issue by rriggstx** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1219]
The list of suggested channels includes "How do I ?".  However, channel names cannot contain special characters.  The screen shot shows it correctly as "How do I".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c9902e8-a0b7-b6af-4656-2024849a5e8b
* Version Independent ID: 85beb9a7-2682-b52e-210b-20e598e3dab3
* Content: [Create your first teams and channels in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-started-with-teams-create-your-first-teams-and-channels)
* Content Source: [Teams/get-started-with-teams-create-your-first-teams-and-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-started-with-teams-create-your-first-teams-and-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by greiginsydney** [comment]
Thanks @rriggstx for pointing that out. 👍
