### ISSUE TITLE
Steps in wrong place

### ISSUE THREAD

**Issue by leeford** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#122]
Unless I'm reading it wrong, steps 4 onwards for "Create an account and set Exchange properties" should actually be step 3 onwards under "Add an email address for your on-premises domain account"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9978e48b-5b8d-df59-d8d3-d3c90a8efafb
* Version Independent ID: 52429f1d-39a1-49fb-c9dd-d4bafa19760d
* Content: [Deploy Skype Room Systems v2 with Exchange Online (Hybrid)](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/with-exchange-online)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/with-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/with-exchange-online.md)
* Service: **unspecified**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
verified with Travis Snoozy and made the requested change.
