### ISSUE TITLE
Documentation is wrong on teams for mac

### ISSUE THREAD

**Issue by sDaniel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1220]
It should be possible with the new version.... But I don't see the button when creating an event. Only the Skype button is shown.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Verwenden des Microsoft Teams-Besprechungs-Add-Ins in Outlook](https://docs.microsoft.com/de-de/microsoftteams/teams-add-in-for-outlook)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.de-DE/blob/live-sxs/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by polo4096** [comment]
Hi , Have you found any solution ?

**Comment by eerstech** [comment]
..check that ... Authentication requirements

**Comment by scanum** [comment]
@PhillipGarding Hi! Any updates on this issue? Thanks!

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by PhillipGarding** [comment]
I am not the owner for any documentation for Teams on Mac.  Check with Anirudh Narayan or @Mike RothKugel<mailto:microthk@microsoft.com>.

**Comment by EmiliaDeica** [comment]
@sDaniel This should do it:
https://support.office.com/en-ie/article/teams-meeting-button-is-missing-in-outlook-for-mac-0d6608c7-96a5-4dba-9dc1-55f724ecb543

**Comment by lindspea** [comment]
@sDaniel Thanks for pointing this out.  Please confirm if this link resolved the issue.  Thanks for that @EmiliaDeica.

**Comment by scanum** [comment]
@sDaniel  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
