### ISSUE TITLE
Web Client Participant

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1221]
How does a web client (guest) participant receive a dial out to join via phone?  Does the organizer have to call them or can the participant do it themselves?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cf7bbd2-ebf4-48e6-c157-8035f976259e
* Version Independent ID: a6897ddf-473b-0109-9f4e-72c59981b631
* Content: [Dialing out from a Microsoft Teams meeting so other people can join it](https://docs.microsoft.com/en-us/MicrosoftTeams/dialing-out-from-a-teams-meeting-so-other-people-can-join-it)
* Content Source: [Teams/dialing-out-from-a-teams-meeting-so-other-people-can-join-it.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/dialing-out-from-a-teams-meeting-so-other-people-can-join-it.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by khorne3** [comment]
@AndreaBarr I can tackle this issue.

**Comment by yogkumgit** [comment]
@khorne3  Thank you very much for the contribution and updating the documentation with PR. @danmyhre  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by danmyhre** [comment]
Not totally clear...so guests can't use dial out?  Those are the ones you would want this capability to easily join audio via phone.
