### ISSUE TITLE
Conversation History

### ISSUE THREAD

**Issue by Deusly** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1222]
How as Microsoft Teams can we actively monitor chat abuse ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 840dd36b-8c29-9738-4adc-ea9a7d277fd0
* Version Independent ID: b12c43c3-ed81-ace5-dfeb-77cac0f97fe9
* Content: [Conduct an eDiscovery investigation of content in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/ediscovery-investigation)
* Content Source: [Teams/eDiscovery-investigation.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/eDiscovery-investigation.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by dariomws306** [comment]
Hi @Deusly , thank your for your feedback.

Could you elaborate further? What do you think that it would be helpful to add to this document?

**Comment by Deusly** [comment]
Scenario:

User 1 sends abusive messages to user 2. User 2 complains about harassment. IT perform investigation but the messages have since been edited/deleted.

IT cannot safeguard our users from online bullying because the user has edited the message. Users need to be able to edit / delete messages due to the nature and size of their posts into channels.

I would like an audit or conversation history of all messages ever sent to be able to protect user 2 from online harassment and abuse.


Rob

On 15 Mar 2019, at 23:48, Dario Woitasen <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @Deusly<https://github.com/Deusly> , thank your for your feedback.

Could you elaborate further? What do you think that it would be helpfuview it on GitHub<https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/1222#issuecomment-473474855>l to add to this document?

—
You are receivingview it on GitHub<https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/1222#issuecomment-473474855>this because you were mentioned.view hit on GitHub<https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/1222#issuecomment-473474855>

**Comment by dariomws306** [comment]
Hi @Deusly , thank you for your comment.

You should use retention policies to achieve what you need:
https://docs.microsoft.com/microsoftteams/retention-policies

Also there are messaging policies to avoid message edition/deletion:
https://docs.microsoft.com/en-us/microsoftteams/messaging-policies-in-teams

**Comment by scanum** [comment]
@Deusly  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
