### ISSUE TITLE
Cannot copy image from chat to other places (Request)

### ISSUE THREAD

**Issue by Kosmosas** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1230]
When trying to drag and drop image to site or copy image to other place than "Teams" - it does not work. 

Workaround - download image, open it and then use it with drag and drop or copy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues#feedback)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by Arie-Kanarie** [comment]
+1. Really weird that this isn't possible by default.

**Comment by dariomws306** [comment]
Hi @Kosmosas , thank you for your feedback.

Are you talking about copy or drag and drop from Teams outside Teams, right?

**Comment by dariomws306** [comment]
![image](https://user-images.githubusercontent.com/33589238/54468740-90091600-476e-11e9-836a-5431264ec062.png)

**Comment by scanum** [comment]
@Kosmosas  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
