### ISSUE TITLE
Add to Surface Hub Admin Guide

### ISSUE THREAD

**Issue by danieldhudson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1231]
This guide should be in the Surface Hub Admin Guide, not the Teams guide, as this is specifically about a particular device and not the general Teams client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f256cd5b-3ec8-2d55-9ae4-ff9849d52eae
* Version Independent ID: 52c2271b-df38-5dc9-c2a1-553cdf3b5496
* Content: [Deploy Microsoft Teams for Surface Hub](https://docs.microsoft.com/en-us/microsoftteams/teams-surface-hub)
* Content Source: [Teams/teams-surface-hub.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-surface-hub.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by dariomws306** [comment]
Hi @danieldhudson , thank you for your feedback.

Are you sure? It's on the Install Teams clients section...

**Comment by scanum** [comment]
@danieldhudson  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
