### ISSUE TITLE
new domain comment

### ISSUE THREAD

**Issue by IlyaBelovRR** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1236]
After adding a new domain it takes hours to propagate to Teams/Skype for Business systems. Please include that in description. In my case took over 8 hours to allow New-CsOnlinePSTNGateway command for the new FQDN

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure a Session Border Controller for multiple tenants](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by fotsopp** [comment]
Seeing the same myself. Added a domain from a SBC provider and I am not able to add the PSTN Gateway since the domain is not propagated. I also tried adding a new user with E5 license to the new domain. That was a suggested sollution to speed up the propagation, but have had no luck so far.

**Comment by NMuravlyannikov** [comment]
Feedback taken

**Comment by get-itips** [comment]
Thanks @IlyaBelovRR @fotsopp for your feedback, based on it, we will add a note to improve the documentation.

**Comment by rkreienbuehl** [comment]
I also have the same problem. I added the domain yesterday and the setup was completed. The I added a user with that domain. Now I am waiting since about 22 hours, trying from time to time to add the SBC, but I always get the same error: Can not use the "xxx.xxx.com" domain as it was not configured for this tenant.
Is this normal that this takes so long?

**Comment by eworthington1** [comment]
Also agree. We are at 48 hours now, still cannot run the command. Double and triple checked (inc peer review) documentation to ensure we have completed every step.

**Comment by rkreienbuehl** [comment]
@eworthington1 for your Info: On Friday after about 24 hours it also didn't work on our installation. On the weekend and on Monday I was not able to try if it worked, but when I tried yesterday morning, I was able to add the SBC. I cannot say how long it really took, but after 4 days I was able to add the SBC.

**Comment by eworthington1** [comment]
@rkreienbuehl Thanks for the info. I'll keep trying.

**Comment by scanum** [comment]
@rkreienbuehl @eworthington1  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
