### ISSUE TITLE
keeping log duration

### ISSUE THREAD

**Issue by akkawamu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1238]
The data mart that is the source of data for this report by default holds the data for ca 365 days since the call end. 
However if the user making the call was in location (country code) AU then retention happens after 2190 days. For CA,NO - 150 days, DE,IT,NL, SE 180 days, DK -1825 days and GB 450 days.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 433c52a1-5721-a082-ab60-62e49d4bf330
* Version Independent ID: b961db7c-77b3-31c8-30f7-7f984c5805c0
* Content: [PSTN の使用状況のレポート](https://docs.microsoft.com/ja-jp/SkypeForBusiness/skype-for-business-online-reporting/pstn-usage-report)
* Content Source: [Skype/SfbOnline/skype-for-business-online-reporting/pstn-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.ja-JP/blob/live-sxs/Skype/SfbOnline/skype-for-business-online-reporting/pstn-usage-report.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by get-itips** [comment]
Hi @akkawamu how are you? hope you are doing good. Thanks for your feedback, could you please explain what specific information is wrong with the article? Thank you

**Comment by scanum** [comment]
@akkawamu  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
