### ISSUE TITLE
Teams take longer time to sync for enterprise voice

### ISSUE THREAD

**Issue by mazhagiah** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1239]
After enabling enterprise voice for Teams user, 'call' button is not immediately available on Teams application. It takes more than 24 hours to sync and get this options. This would affect our customer / user experience with Teams and Direct Routing.

Is there any option to sync forcefully or replicate the changes quick. 

Regards
Raja

**Comment by dariomws306** [comment]
Hi @mazhagiah , thank your for your feedback.

Are you following any special document/article to enable enterprise voice?

**Comment by scanum** [comment]
@mazhagiah  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
