### ISSUE TITLE
For Mac clients - Lync

### ISSUE THREAD

**Issue by mjtart** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1243]
Mac section is incorrect now, delegates can be added directly to delegate group from contact search. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0ca278a-2391-087e-8310-1d403496fbc5
* Version Independent ID: 5bb130e6-37c5-37ea-1a99-2f3697ca9916
* Content: [Set up and troubleshoot Skype for Business Online delegation](https://docs.microsoft.com/en-us/SkypeForBusiness/set-up-skype-for-business-online/set-up-and-troubleshoot-skype-for-business-online-delegation)
* Content Source: [Skype/SfbOnline/set-up-skype-for-business-online/set-up-and-troubleshoot-skype-for-business-online-delegation.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-skype-for-business-online/set-up-and-troubleshoot-skype-for-business-online-delegation.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by CarolynRowe** [comment]
Thank you for your feedback.  I've checked with one of our Skype for Business engineers... according to the engineer, Skype for Business for MAC still doesn’t have the ability to sync delegates from Exchange via MAPI.  The text should remain as is.
