### ISSUE TITLE
Update docs with Mobile client version requirement for QoS

### ISSUE THREAD

**Issue by NicholasBurkhammer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1245]
Per mobility EEE in PG, this was added in 6.17 version of the mobile clients. Please reach out to me directly for any reference documentation and to link you over to the EEE if necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f5a97d-6e1c-d26a-8b51-7f8c73e72f9a
* Version Independent ID: bfac7530-39f1-70eb-ab55-c96cbe45b180
* Content: [Enabling QoS for devices that are not based on Windows](https://docs.microsoft.com/en-us/skypeforbusiness/manage/network-management/qos/enabling-qos-for-devices-that-are-not-based-on-windows)
* Content Source: [Skype/SfbServer/manage/network-management/qos/enabling-qos-for-devices-that-are-not-based-on-windows.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/network-management/qos/enabling-qos-for-devices-that-are-not-based-on-windows.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by khorne3** [comment]
@AndreaBarr I can work on this.

**Comment by AndreaBarr** [comment]
@khorne3 I got direction to have Crystal work on this one. 

@CrystalThomasMS I was directed by James to have you take this one since you were the one who originally worked on it.

**Comment by CrystalThomasMS** [comment]
@NicholasBurkhammer, can you tell me what specific changes need to be made to the documentation?

**Comment by NicholasBurkhammer** [comment]
I’ll defer to @Premal Gandhi<mailto:premgan@microsoft.com> who is the EEE with the PG for mobile clients.

@Premal, this is related to explicitly stating which clients, versions, etc., need to be documented in documentation.

Note:  I will be out of the office on holiday 12/19/2018-12/25/2018.  During this time I will not have access to email.  If you need assistance while I am out of the office, contact your account team or Product Support Services to request reassignment if necessary.  Due to current volume, any reassignment requests are expected to take several business days to complete.

Regards,

Nicholas Burkhammer
Microsoft ● Unified Communications ● Support Escalation Engineer
Email: nichburk@microsoft.com<mailto:nichburk@microsoft.com>
Phone: +1 980-776-2946
Hours: Monday-Friday 0900-1800 ET
Manager ● Craig Fischer ● mailto:Craig.Fischer@microsoft.com

[SummitAward_2018-OutlookSign]

**Comment by scanum** [comment]
@CrystalThomasMS

**Comment by scanum** [comment]
@CrystalThomasMS Hi Crystal, any updates on this?

**Comment by CrystalThomasMS** [comment]
Sorry, it's not clear to me what this work item is. It looks like a request for some sort of documentation change was made by @NicholasBurkhammer, who deferred to  @premal Gandhi<mailto:premgan@microsoft.com>, but I don't see any further discussion or clarification on the requested change and/or addition. Can you clarify what the work being requested is? I'm not familiar with the content, other than having formatted and published it late last year.

**Comment by NicholasBurkhammer** [comment]
It was to add mobile client versions that started supporting QoS because a couple of colleagues had cases regarding this.  We had to RFC it to Premal.  Since there are multiple mobile client versions, it is recommended to reach out to Premal with the PG to obtain the authoritative information.

Regards,

Nicholas Burkhammer
Microsoft ● Unified Communications ● Support Escalation Engineer
Email: nichburk@microsoft.com<mailto:nichburk@microsoft.com>
Phone: +1 980-776-2946
Hours: Monday-Friday 0900-1800 ET
Manager ● Craig Fischer ● mailto:Craig.Fischer@microsoft.com

[SummitAward_2018-OutlookSign]

**Comment by CrystalThomasMS** [comment]
Thanks, Nicholas.

@Premal Gandhi<mailto:premgan@microsoft.com>, can you provide the information mentioned by Nicholas below? This is in regard to the following article:

Enabling QoS for devices that are not based on Windows<https://docs.microsoft.com/en-us/skypeforbusiness/manage/network-management/qos/enabling-qos-for-devices-that-are-not-based-on-windows>

Thank you,
Crystal
