### ISSUE TITLE
There are typos and inaccuracies in the gpupdate and gpresult command lines

### ISSUE THREAD

**Issue by SiloReed** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1246]
1. The document reads: "gpudate.exe /force" (it's missing a "p"). It should read:
gpupdate.exe /force

2. "gpresult /H &gt;gp.html" is not valid, the "&gt;" redirector should be removed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76c2487c-044d-1349-708a-5841fcb21ab8
* Version Independent ID: b7033454-1a9c-48d4-8004-78415c5feb89
* Content: [Quality of Service in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/qos-in-teams)
* Content Source: [Teams/QoS-in-Teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/QoS-in-Teams.md)
* Service: **msteams**
* GitHub Login: @rmw2890
* Microsoft Alias: **MyAdvisor**

**Comment by khorne3** [comment]
@AndreaBarr I can work on this.
