### ISSUE TITLE
Set upgrade options for all users in your organization section 

### ISSUE THREAD

**Issue by munrobasher** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1248]
It does correspond with what you currently see. Only the option to set co-existence mode is there. Nothing about notification, preferred app, background download?

https://i.imgur.com/OSsnF7G.png

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffbf0bfd-c15e-b10b-0cc9-6a27ac1e6634
* Version Independent ID: 58575371-9e09-fadb-76f6-7491df8580a3
* Content: [Setting your coexistence and upgrade settings](https://docs.microsoft.com/en-gb/MicrosoftTeams/setting-your-coexistence-and-upgrade-settings#feedback)
* Content Source: [Teams/setting-your-coexistence-and-upgrade-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/setting-your-coexistence-and-upgrade-settings.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by dariomws306** [comment]
Hi @munrobasher , thank your for your feedback.

Based on the last comment, do you think we can improve this article?

**Comment by scanum** [comment]
@munrobasher We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
