### ISSUE TITLE
Wrong Parameter Name

### ISSUE THREAD

**Issue by zweckj** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1249]
In command stated above
"Get-CsMeetingMigrationStatus -UserId "ashaw@contoso.com""
the parameter "UserId" is used. However that parameter does not exist and is instead called "-Identity".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 990ca74b-6bba-a14b-071a-d13adb723a4c
* Version Independent ID: 52f55a58-30ce-c140-3ee7-8042b1d105f0
* Content: [Setting up the Meeting Migration Service (MMS)](https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/setting-up-the-meeting-migration-service-mms#using-powershell-to-manage-your-skype-for-business-organization)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/setting-up-the-meeting-migration-service-mms.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/setting-up-the-meeting-migration-service-mms.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by get-itips** [comment]
Referencing merged PR https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/1253

**Comment by scanum** [comment]
@zweckj Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
