### ISSUE TITLE
Set-csAccessEdgeConfiguration cmdlet syntax needs additional context

### ISSUE THREAD

**Issue by BSwagger** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1254]
Within the Set-CsAccessEdgeConfiguration cmdlet, the -EnablePartnerDiscovery $True parm/value is specified.  This essentially will make the on-premise deployment "open Federation" meaning the use of allowed domains list is no longer applicable and users can lookup/communicate to any federated partner simply with using DNS lookup, provided the remote deployment is also "open fed".  In the online SFBO tenant, this is set by default, so the cmdlet in this article as-is, is just matching the default setting in online tenant which is required for support.  However, this can corrected by configuring the online tenant to only use allowed domains list as well and matching the onprem allowed lists versus just setting -EnablePartnerDiscovery $true.  There should be more context behind this, otherwise folks may blindly implement not realizing what it is doing...only that it's seemingly required for Hybrid per documentation.

Lastly, the cmdlet currently in the article is:  Set-CSAccessEdgeConfiguration -AllowOutsideUsers 1 -AllowFederatedUsers 1 -UseDnsSrvRouting -EnablePartnerDiscovery $True

Be consistent and either use 1 or $true, both not both in the same example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa67aa04-cb94-d744-7bce-a5ed35944062
* Version Independent ID: 79cc9cf3-5968-20c6-7463-54a35c074de7
* Content: [Lync Server 2013: Configure federation with Lync Online](https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-configure-federation-with-lync-online)
* Content Source: [Lync/LyncServer/lync-server-2013-configure-federation-with-lync-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Lync/LyncServer/lync-server-2013-configure-federation-with-lync-online.md)
* GitHub Login: @dstrome2

**Comment by scanum** [comment]
@BSwagger Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@BSwagger thank you for reaching out and helping improve MS Docs. Please could you let me know how you would suggest fixing the cmdlet in this article and I can investigate further.

**Comment by scanum** [comment]
@BSwagger  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
