### ISSUE TITLE
Missing P2P comms requirements

### ISSUE THREAD

**Issue by jupfeiff** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1255]
the article misses the information about what protocols and ports need to be opened for peer to peer communications between clients. ICE will be used and without these ports open the media will always hairpin via a Teams Media Relay at Microsoft.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e8b2651-40bb-0d26-6126-d88689047f23
* Version Independent ID: 5be83c7d-ef7f-5582-4a6c-f0709fb2ec7b
* Content: [Prepare your network for upgrading to Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/upgrade-prepare-environment-prepare-network)
* Content Source: [Teams/upgrade-prepare-environment-prepare-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-prepare-environment-prepare-network.md)
* Service: **msteams**
* GitHub Login: @Turgayo
* Microsoft Alias: **turgayo**

**Comment by oradcliffe** [comment]
Jeff, by default Teams will use 50000-50059 TCP/UDP.

**Comment by dariomws306** [comment]
Hi @jupfeiff and @oradcliffe , thank you for your valuable feedback.

About 1:1 communications I understand it will use the same ports:
![image](https://user-images.githubusercontent.com/33589238/54477455-c4b8b400-47e6-11e9-867e-50165700f3c3.png)

Please check this:
https://myignite.techcommunity.microsoft.com/sessions/65521?source=sessions#ignite-html-anchor

**Comment by scanum** [comment]
@jupfeiff  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
