### ISSUE TITLE
GitHub Links

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1264]
The links for the powershell commands at the bottom are pointing to GitHub instead of docs.microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a67695fd-98de-576c-b1cd-e9a63a553bcb
* Version Independent ID: b313b61a-43ef-0fbc-ed23-5ff7e38b6a2b
* Content: [Planning to turn off Legacy authentication methods internally and externally to your network](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/modern-authentication/turn-on-modern-auth)
* Content Source: [Skype/SfbServer/plan-your-deployment/modern-authentication/turn-on-modern-auth.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/modern-authentication/turn-on-modern-auth.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by jambirk** [comment]
I just fixed the source file, changes should be visible later today
