### ISSUE TITLE
automatically admit users is not on/off.

### ISSUE THREAD

**Issue by rolandfalcon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1265]
Options are Everyone, Everyone in organization, Everyone in your organization and federated organizations. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Meeting policies in Teams](https://docs.microsoft.com/en-US/MicrosoftTeams/meeting-policies-in-teams?WT.mc_id=TeamsAdminCenterCSH#bkparticipantsandguests)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by jamesrhea** [comment]
@rolandfalcon, is this an accurate update to the last bullet point?

**Automatically admit users** If you turn this off, then meeting participants will be left in the lobby until someone starts the meeting. To automatically admit some users, select between the following options: _Everyone_, _Everyone in organization_, or _Everyone in your organization and federated organizations_.

**Comment by malimal99** [comment]
in GCC the option for "Off\On" is not available. only the ones @rolandfalcon listed.

**Comment by dariomws306** [comment]
Hi @rolandfalcon , @jamesrhea and @malimal99 , thank you for your valuable feedback.

I have udpated this article according to this feedback.

**Comment by ArttuArstila** [comment]
"Automatically admit users If you turn this off, then meeting participants will be left in the lobby until someone starts the meeting. If it's on, meeting participants will be allowed to join the meeting automatically."  For this settings, the Teams Admin Center help button says "You can turn on or off if people that dial in using a phone are automatically joined to a meeting.". 

So is this about the overall lobby bypass or for mobile users only? We see in several tenants that this setting does not fully affect the lobby bypass the way it should be.

**Comment by dariomws306** [comment]
Hi @ArttuArstila, thank you for your feedback.

I am applying this update:

**Automatically admit people** Determines what types of participants will automatically be added to meetings organized by this user. Set this to "Everyone in organization" if you would like meetings to place every external user in the lobby but allow all users in the company to join the meeting immediately. Set this to "Everyone" if you'd like to admit anonymous users by default. Set this to "Everyone in your organization and federated organizations" if you would like meetings to allow federated users to join like your company's users, but place all other external users in a lobby.

**Comment by scanum** [comment]
@rolandfalcon Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by Argon0** [comment]
Need to reopen this issue as, for my tenant, it is making no difference: 

"So is this about the overall lobby bypass or for mobile users only? We see in several tenants that this setting does not fully*affect the lobby bypass* the way it should be."
