### ISSUE TITLE
Change documentation to reflect a step that is required for changes to take effect.

### ISSUE THREAD

**Issue by NicholasBurkhammer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1266]
Recommend putting a note in section (this is confirmed as required by RFC to PG) https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/modern-authentication/turn-on-modern-auth#how-to-get-the-get--and-set-csauthconfig-cmdlets

Note:  After configuring the CsAuthConfig, you must run Enable-CsComputer on each computer in order for the settings to take effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a67695fd-98de-576c-b1cd-e9a63a553bcb
* Version Independent ID: b313b61a-43ef-0fbc-ed23-5ff7e38b6a2b
* Content: [Planning to turn off Legacy authentication methods internally and externally to your network](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/modern-authentication/turn-on-modern-auth#how-to-get-the-get--and-set-csauthconfig-cmdlets)
* Content Source: [Skype/SfbServer/plan-your-deployment/modern-authentication/turn-on-modern-auth.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/modern-authentication/turn-on-modern-auth.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by get-itips** [comment]
Thanks Nicholas, I will take this one @AndreaBarr

**Comment by scanum** [comment]
@NicholasBurkhammer  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
