### ISSUE TITLE
Update supported operating systems

### ISSUE THREAD

**Issue by NicholasBurkhammer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1268]
The following changes should be made to specify Windows Server 2016 is only supported with Skype for Business Server 2019 Call Quality Dashboard.  This is in response to RFC clarifying supportability and the documentation

Under section "Infrastructure Requirements For CQD" (https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/call-quality-dashboard/plan#infrastructure-requirements-for-cqd):

Add  Windows Server 2016 to the following line.  Example below.

"Supported Operating Systems:  Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2, and Windows Server 2016 (Skype for Business Server 2019 CQD only)"

Under section "Software Requirements" (https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/call-quality-dashboard/plan#software-requirements):

The line that currently states, "Windows Server 2016 with IIS" should be changed to "Windows Server 2016 with IIS 10.0 (Skype for Business Server 2019 CQD only)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f91216e8-0b6c-88b1-635a-401529556f78
* Version Independent ID: 0b0e068d-b870-bbd2-550d-07917ec63926
* Content: [Plan for Call Quality Dashboard for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/call-quality-dashboard/plan)
* Content Source: [Skype/SfbServer/management-tools/call-quality-dashboard/plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/management-tools/call-quality-dashboard/plan.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@NicholasBurkhammer Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
