### ISSUE TITLE
Metadata from CDR Sessions table in Skype for Business Server missing from Skype online Sessions table.

### ISSUE THREAD

**Issue by justinthorne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1270]
Is there any way to get session details like what was stored in the CDR database of Skype for Business Server?  Some of the metadata missing from this table for example is in IM's User1MessageCount, User2MessageCount and response time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4785e60-a102-98e3-bf8c-0d0d8d9e961b
* Version Independent ID: 2fb7ccc6-a09a-7d0a-c455-00c065cac694
* Content: [Session table](https://docs.microsoft.com/en-us/skypeforbusiness/schema-reference/quality-of-experience-qoe-database-schema/session)
* Content Source: [Skype/SfbServer/schema-reference/quality-of-experience-qoe-database-schema/session.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/schema-reference/quality-of-experience-qoe-database-schema/session.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws306** [comment]
Hi @justinthorne , thank you for your feedback.

Information about 1:1 sessions on SfBO/Teams are found in the Admin Portal under Analytics & reports.

**Comment by scanum** [comment]
@justinthorne Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
