### ISSUE TITLE
External Teams communication not working

### ISSUE THREAD

**Issue by seaSide974** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1273]
Hello,

By default on a tenant, if we activate the external access, Teams could communicate to each other if I understand the article ? This is not working when i research an email, no email are showing.

So i tried adding each domain (toto.onmicrosoft.com and mydomain.com) to each tenant as allowed domained, still not working.

For both tests I used a 5g connection on my phone, and used the team app on the phone,

Please let me know if the steps I followed are correct , thank you.

A test domain feature would be useful to ensure that technically the pre requisites are met (network / firewall).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Communicate with Teams users in another organization](https://docs.microsoft.com/en-us/microsoftteams/let-your-teams-users-communicate-with-other-people#)
* Content Source: [Teams/let-your-teams-users-communicate-with-other-people.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/let-your-teams-users-communicate-with-other-people.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by dawander** [comment]
We have the same exact issue and support says "teams isn't quite ready."  I've been trying to get help from different resources.  I don't see what the firewall has to do with it.  If the other tenant uses their mobile phone outside the office as do I, we are still unable to chat.  To me, it seems the issue is on the backend and not the client side.

**Comment by dawander** [comment]
I forgot to mention that calls (audio and video) both work just fine from/to all platforms.  Only text/chat messaging fails.

**Comment by gcormier** [comment]
Not working for us either. A global admin account can do external chats and search for external users, but a regular user is unable to search for external users, or do external chats.

**Comment by tonysmit** [comment]
@nomorephones (Jamie) - any ideas?

**Comment by jamesKAC** [comment]
All of my issues took time to resolve themselves.  I created a new tenant and it took about 3-4 days for external chat to start working.  When I enabled guest access it took another couple days for that to start working.  I made no changes on my end (other than turning on guest access).  My external access was set to on by default in new tenant.

**Comment by pkohn-sva** [comment]
Would be great, if we hear something official have the same problem with two tenants here both "TeamsOnly" ...federated Chat not working

Regards Philipp

**Comment by vination** [comment]
Can someone confirm if the coexistence mode needs to be set to Teams only for both organizations for this to work or not?

**Comment by jackvinson** [comment]
We are seeing something similar.  We've enabled communication with them.com, and we are able to initiate Chat to them.com users.  But them.com users are unable to initiate chat with us - they get a message that says that we are unavailable.  if we Chat with them first, then they are able to communicate back.  But after a short period of time (15 mins?), they are unable to reply or chat back.

**Comment by bryhall** [comment]
@jackvinson, this sounds like an SIP session timeout which may happen between Teams and Skype. https://docs.microsoft.com/en-us/microsoftteams/coexistence-chat-calls-presence#chats-and-calls-from-pre-existing-threads

**Comment by FrancoiD** [comment]
There are multiple aspects.
One, federation follows the upgrade modes but does not require TeamsOnly, see the doc pasted above by @bryhall 
Second, when the sender is in Islands mode with SFB onprem, the sender must use SFB for federation. The document is not explicit enough about that, I will modify it.
Third, it is also correct that SIP sessions will time out, in about 10 min, therefore reply from Teams may not always be possible after the session has expired.
Last, if the users' modes just changed, there can be some latency before federation between them works. We are working on reducing that latency.

**Comment by scanum** [comment]
@seaSide974  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by rane52** [comment]
I see this issue been close with no resolution!! Can someone confirm if the coexistence mode needs to be set to Teams only for both organizations for this to work or not? I have users on Island mode and they cant chat or search for external users but only TeamsOnly mode users in the same tenets are able to search and start a chat with external users.
