### ISSUE TITLE
"Teams Only" not availabe yet

### ISSUE THREAD

**Issue by SteffanH** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1277]
Org-wide Settings &gt; Teams Upgrade -&gt; Teams Only is not yet an option for all tenants; when will this be GA ?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56ab9d91-d5c4-be13-660e-10b1fdacadec
* Version Independent ID: efdd6696-1415-26ae-ab56-5e758a34311c
* Content: [Upgrade Basic checklist - Microsoft Teams](https://docs.microsoft.com/en-gb/MicrosoftTeams/upgrade-basic)
* Content Source: [Teams/upgrade-basic.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-basic.md)
* Service: **msteams**
* GitHub Login: @dearbeen
* Microsoft Alias: **dearbeen**

**Comment by dariomws306** [comment]
Hi @SteffanH , thank you for your comment.

Did you try with Grant-CsTeamsUpgradePolicy?

Thanks!

**Comment by scanum** [comment]
@SteffanH We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
