### ISSUE TITLE
Cannot Remove Emergency Location

### ISSUE THREAD

**Issue by saubermfg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1278]
I have an incorrect emergency location listed and would like to remove it. I have removed all users from this invalid location I have reassigned them to a valid one. Step 5 under the removal instruction set references a "Remove" link, which does not appear to be available for me. It would be good to be able to remove this location, because right now, it could accidentally be assigned, which would be bad in an emergency.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800d0cd9-8964-f27c-49f3-0bf4fdaa1b6f
* Version Independent ID: d6b5f936-f920-d289-41c2-00e76bc1b2c3
* Content: [Add, change, or remove an emergency location for your organization](https://docs.microsoft.com/en-us/skypeforbusiness/what-are-calling-plans-in-office-365/add-change-or-remove-an-emergency-location-for-your-organization)
* Content Source: [Skype/SfbOnline/what-are-calling-plans-in-office-365/add-change-or-remove-an-emergency-location-for-your-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/what-are-calling-plans-in-office-365/add-change-or-remove-an-emergency-location-for-your-organization.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@saubermfg  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
