### ISSUE TITLE
After dialed # connects, cannot dial an extension

### ISSUE THREAD

**Issue by cjecwest** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1279]
There doesn't seem to be an easy way to pull up the 10 key pad to dial an extension after the initial add participant phone connection is established.  Am I missing something?  I am doing this flow: "Meet Now"  --&gt; Add Participant --&gt; Dial #  --&gt; connect to user at POTS #  --&gt; Cannot dial extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d26a08af-4176-49a2-a884-ef436f12ce4b
* Version Independent ID: f218dfc6-a3e5-5c4e-c0db-9127c3d88fc9
* Content: [Dialing out from a Skype for Business meeting so other people can join it](https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/dialing-out-from-a-meeting-so-other-people-can-join-it)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/dialing-out-from-a-meeting-so-other-people-can-join-it.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/dialing-out-from-a-meeting-so-other-people-can-join-it.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@cjecwest - thanks for this feedback and finding the area where the article needs to be clearer.

@jamesrhea and I are working on figuring out how to get this resolved in the content.

@chuckedmonson - might be able to help too.

**Comment by jamesrhea** [comment]
@cjecwest, you should be able to use extension numbers after the call has been connected. Do you see a Call Controls button in the bottom right of the conference window?

You can see the icon and available options here, which should include the 10-key pad. https://support.office.com/en-us/article/make-and-receive-calls-using-skype-for-business-228e03aa-7361-4997-8dfa-1dd9bdc717f6

**Comment by kenwith** [comment]
@cjecwest - I am going to go ahead and close this out as @jamesrhea posted a link for the 10-key pad icon. Let us know if you don't see it the way the article describes or there is something wrong in either of the articles. @jamesrhea - if you think the article for this issue (first post in thread) should be updated please submit a PR for it too and we can get it merged so we can avoid any confusion between the support.office.com article you posted and the article for this issue.
