### ISSUE TITLE
Skype for Business Online?

### ISSUE THREAD

**Issue by BenGVSU** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1285]
Does this same documentation apply to Skype for Business Online Rate My Call report?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d678ef9-0f4c-873f-e437-cef92841ebff
* Version Independent ID: 04e7966a-2bee-11a2-c3be-6ef1b0a100cd
* Content: [Rate my Call in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/manage/health-and-monitoring/rate-my-call)
* Content Source: [Skype/SfbServer/manage/health-and-monitoring/rate-my-call.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/health-and-monitoring/rate-my-call.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by get-itips** [comment]
Hi BenGVSU, I am sorry to inform you that this same doc only applies to Skype For Business On premises. But [Set-CsClientPolicy](https://docs.microsoft.com/en-us/powershell/module/skype/set-csclientpolicy?view=skype-ps) that is used in an example in the document  applies to both versions. @AndreaBarr

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @BenGVSU 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
