### ISSUE TITLE
Add coverage for GCC customers

### ISSUE THREAD

**Issue by RomanMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1293]
Allowed domain would need to be gcc-email.teams.microsoft.com for a GCC customer, as opposed to a conventional MT customer...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43bc0cae-682a-7227-35d6-d3c37545a3a4
* Version Independent ID: fbcd00ac-8899-fb95-28aa-dfc523b81c65
* Content: [Add the Microsoft Teams SMTP domain as an allowed sender domain in Exchange Online](https://docs.microsoft.com/en-us/MicrosoftTeams/smtp-accepted-domain)
* Content Source: [Teams/SMTP-accepted-domain.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/SMTP-accepted-domain.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by dariomws306** [comment]
Hi @RomanMSFT , thank you for your feedback.

There is a line in the article for this:
"The difference being the domain FQDN of the SMTP message is “@email.teams.microsoft.com” for Commerical/Business tenants and "@GCC-email.teams.com" for Government tenants and could be caught by spam filtering."

Do you think it needs more detail?

Thanks!

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @RomanMSFT 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
