### ISSUE TITLE
No Phone System Option for Nonprofit Office 365?

### ISSUE THREAD

**Issue by davidshq** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1300]
Hi Folks,
It appears that these instructions don't work for Office 365 for nonprofits. The only "Phone System" option I have is, "Common Area Phone (Nonprofit Staff Pricing)" - but this does not appear to be identical to the above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8daf2547-3cd5-a95a-f164-3dd447987e81
* Version Independent ID: cb8a7faf-2631-a822-0af7-0a127e065520
* Content: [Office 365 Business Premium ](https://docs.microsoft.com/en-us/SkypeForBusiness/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/office-365-business-premium-plan)
* Content Source: [Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/office-365-business-premium-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/office-365-business-premium-plan.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by dariomws306** [comment]
Hi @davidshq , thank you for your comment.

Phone System add-on is not available for Office 365 Business. As you can see at the end of the article, to get this add-on you need to switch to the E1 or E3 plan.

More information:
https://docs.microsoft.com/office365/admin/subscriptions-and-billing/buy-or-edit-an-add-on#available-add-ons

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @davidshq 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by scanum** [comment]
@davidshq We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by davidshq** [comment]
FYI, I was able to add an E1 license and a phone system license to one user, I'll be playing around with it. It appears that E1 licenses are free for nonprofits and can be used in combination with the Business license. It does not appear I have access to purchase E2-E4 licenses, only E5 is available in addition to E1.

**Comment by dariomws306** [comment]
Hi @davidshq, thank you for your comment. Please let us know if you have more information.
