### ISSUE TITLE
Can not see the "Teams-Only" option

### ISSUE THREAD

**Issue by chenxizhang** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1302]
I can not see the "Teams-only" option in the Teams admin center. something I missed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffbf0bfd-c15e-b10b-0cc9-6a27ac1e6634
* Version Independent ID: 58575371-9e09-fadb-76f6-7491df8580a3
* Content: [Setting your coexistence and upgrade settings](https://docs.microsoft.com/en-us/microsoftteams/setting-your-coexistence-and-upgrade-settings)
* Content Source: [Teams/setting-your-coexistence-and-upgrade-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/setting-your-coexistence-and-upgrade-settings.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AlexSchwerzmann** [comment]
Hi chenxizhang
You can use the following cmdlet to set your users to "Teams-only"
Grant-CsTeamsUpgradePolicy -PolicyName tag:UpgradeToTeams
(see also: https://docs.microsoft.com/en-us/powershell/module/skype/grant-csteamsupgradepolicy?view=skype-ps)

**Comment by chenxizhang** [comment]
Thank you

**Comment by yogkumgit** [comment]
@AlexSchwerzmann  Thank you very much for the contribution and sharing this explanation. @chenxizhang  Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by chenxizhang** [comment]
OK, thank You
