### ISSUE TITLE
Step 9

### ISSUE THREAD

**Issue by khojs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1303]
Step 9 should be start the start-CSWindowsService ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3de48a6d-4cce-eaee-d9e8-7e001d890fea
* Version Independent ID: 3e2ad9ee-3b50-58a9-b78e-8db14387cf29
* Content: [Patch or update a Back End Server or Standard Edition server in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/manage/topology/patch-or-update-a-back-end-or-standard-edition-server)
* Content Source: [Skype/SfbServer/manage/topology/patch-or-update-a-back-end-or-standard-edition-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/topology/patch-or-update-a-back-end-or-standard-edition-server.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by nenonix** [comment]
@khojs Thank you for your feedback. I will work with you to improve the content. Can you help me with some more detail? Are you suggesting that we need to add a step or that Step 9 is incorrect?

**Comment by nenonix** [comment]
Hi @khojs  After consulting with the documents team we feel that the steps are correct as documented and do not need to be changed. Please see here: https://support.microsoft.com/en-us/help/3061064/updates-for-skype-for-business-server-2015 for more detail.
​
