### ISSUE TITLE
Clarification of who a "Guest" is

### ISSUE THREAD

**Issue by jlrd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#131]
I'm understanding from use and vaguely from the documentation from above that a "Guest" has to be outside the Office 365 Tenant? For example if someone in the tenant (example.com) with a Exchange Plan 1 license and an jdoe@example.com email address can not be granted access to Teams as a guest, but someone outside at say jsmith@acme.com could be. So any email users within the Tenant would still require a E3 or greater license to access a Teams correct? Maybe that could be clarified a little plainer in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2492e210-08f9-a476-97ec-008926def961
* Version Independent ID: adcb0dd9-4a3c-b665-6e34-ce3276c89b4d
* Content: [Guest access in Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/guest-access)
* Content Source: [Teams/guest-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access.md)
* Service: **msteams**
* GitHub Login: @laithalshamri
* Microsoft Alias: **laal**

**Comment by tonysmit** [comment]
@arachmanGitHub, can you comment on this and see if there is a work item for me please? Thanks.

**Comment by arachmanGitHub** [comment]
We clearly stated about what "guest" is on the fifth (5th) paragraph, but good point on making the clarification of what to do if current subscription plan is EXO only @jlrd. @tonysmit, I'll raise a work item on this.

**Comment by tonysmit** [comment]
Did you want to fix this, or I may have to?

**Comment by tonysmit** [comment]
Ok. That sounds good. With Lola out I’m scrambling. I will see the PR and will merge it to live. Thanks.

Sent with only my thumbs.
________________________________

**Comment by kenwith** [comment]
@jlrd - I believe this was updated. If there is still room for improvement please go ahead and re-open. Also, if you are open to submitting a Pull Request so your knowledge and expertise can get captured in the docs you can do so with the instructions on the README in the main REPO here: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness  You will then get credit as a contributor. If you would rather we do it you can always just open an issue too. Sorry for the very long delay on this.
