### ISSUE TITLE
enq

### ISSUE THREAD

**Issue by yiuyu2357** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1312]
how to look up the manu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b07cfcf-8f31-91ed-b1de-c7826a1ab91d
* Version Independent ID: dfbc4212-8f47-326a-f872-8186a915ae1e
* Content: [Country and region availability for Audio Conferencing and Calling Plans](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by jamesrhea** [comment]
@yiuyu2357, can you say a bit more about what you're trying to do?

**Comment by yiuyu2357** [comment]
xmas and thx




James Rhea <notifications@github.com> 於 2019年1月23日 週三 上午9:38寫道：

**Comment by KDawg05** [comment]
A question about Telephony within O365. If the tenant is in a North American DC and the users are geo-dispursed, does the calls made from a user in India within India get treated as local or are they long distance because the tenant is not in India? More specific, how are local and long-distance calls differentiated if the tenant where the user resides is not in their geographic local?

**Comment by yiuyu2357** [comment]
sure


________________________________
寄件者: James Rhea <notifications@github.com>
寄件日期: 2019年1月23日 1:38
收件者: MicrosoftDocs/OfficeDocs-SkypeForBusiness
副本: yu kwong yiu wilson; Mention
主旨: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] enq (#1312)


@yiuyu2357<https://github.com/yiuyu2357>, can you say a bit more about what you're trying to do?

**Comment by dariomws306** [comment]
Hi @KDawg05 , thank you for your feedback.

For example, if when you have configured the license for this user you chose India as location, calls to Indian numbers will be treated as local. You can see this information here:
https://docs.microsoft.com/en-us/microsoftteams/calling-plans-for-office-365#pricing-information

**Comment by scanum** [comment]
@KDawg05  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

@yiuyu2357  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by yiuyu2357** [comment]
James Rhea <notifications@github.com> 於 2019年1月23日 週三 上午9:38寫道：

**Comment by yiuyu2357** [comment]
bluesky321@netvigator.com,pui.catherine@gmail.com; pui.catherine@gmail.com,
jj01hk@yahoo.com.hk, walodoris@yahoo.com.hk, juliechau@hotmail.com,
kennliu2000@yahoo.com.hk


Dario Woitasen <notifications@github.com> 於 2019年3月30日 週六 上午8:47寫道：

**Comment by yiuyu2357** [comment]
jack wong <h2helibebc@gmail.com> 於 2019年4月9日 週二 上午9:55寫道：
