### ISSUE TITLE
jeanSerri2019

### ISSUE THREAD

**Issue by yiuyu2357** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1313]
https://github.com/login?client_id=Iv1.d31913c6812a3ef4&return_to=%2Flogin%2Foauth%2Fauthorize%3Fclient_id%3DIv1.d31913c6812a3ef4%26redirect_uri%3Dhttps%253A%252F%252Fdocs.microsoft.com%252Fapi%252Fgithubauth%252Fauthorized%26state%3Df57e58aa4d0d81219236f357919d9e794c3fab7ee1c41821354ce4a577839936df3e520a3b68e63deff9f5caaefb5a5251f14a00c6510375109f3ef19d75eca5a665ad20f16f985af2aad08cfecb1f9b3042a348e48c4c614c3f201d49c42f8bb51576b3821a705c4834a7b655028530ea74d669bb166baa3334fd95375441493cf7c202e2aa259cc1e2729c903b1b8418b3035546e55805772020f3520c4e8272adec59

**Comment by jamesrhea** [comment]
@yiuyu2357, is there something we can help you with? Did you have a recommendation for how to improve the Skype for Business documentation?

**Comment by yogkumgit** [comment]
@yiuyu2357 Request you to log the issues with complete information and help us to refer it in right context.  Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
