### ISSUE TITLE
SfB Online user can reset their PIN

### ISSUE THREAD

**Issue by naminakao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#133]
SfB Online user no longer has to ask administrator to reset the PIN. They can reset their PIN via SfB Setting Portal based on the following techcommunity article. 

Page Title: Skype for Business settings portal: Reset your pin and more
URL: https://techcommunity.microsoft.com/t5/Skype-for-Business-Blog/Skype-for-Business-settings-portal-Reset-your-pin-and-more/ba-p/68689

I was able to go to Skype for Business Setting Portal by clicking "Forgot your dial-in PIN" in a meeting invitation and successfully rest the PIN either when I sign in as a meeting requestor or a meeting participant.

However the following page still says Skype for Business Online user must ask their admin to reset the PIN.

Page Title: Reset the Audio Conferencing PIN for a user
URL: https://docs.microsoft.com/en-us/SkypeForBusiness/audio-conferencing-in-office-365/reset-the-audio-conferencing-pin-for-a-user
![image](https://user-images.githubusercontent.com/34467132/38966783-e4b4b308-43be-11e8-9535-de5b7a92ccd1.png)

**Comment by tonysmit** [comment]
It's updated and republished. Thanks for your feedback!
