### ISSUE TITLE
Unclear whether a tab added is accessible to all

### ISSUE THREAD

**Issue by zehawki** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1334]
I came to this document to understand just one thing, unfortunately that is missing. When a tab is added by a owner or member, is it visible to and accessibly by all? (or is the tab private to the person who added it?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d33f55c-db55-923e-544f-fccb97f3c7a3
* Version Independent ID: 9cb02e00-311e-ec7d-c422-ae1cb9e6d31e
* Content: [Use built-in and custom tabs in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/built-in-custom-tabs#develop-custom-tabs)
* Content Source: [Teams/built-in-custom-tabs.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/built-in-custom-tabs.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by khorne3** [comment]
Hi @zehawki. When you're adding a tab, it is accessible (or not) based on the permissions you've set for the affiliated Office 365 Group. Hope that helps!

**Comment by scanum** [comment]
@zehawki  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by dariomws306** [comment]
Hi @zehawki , thank you for your feedback.

In your case when you create a Team (and channels under it) owners and members can see all, including tabs added by owners or members.
Teams is based on Office 365 groups, so when you create a Team from an existing Office 365 Group, permissions are inherited.
Please check:
https://docs.microsoft.com/en-us/microsoftteams/assign-roles-permissions

**Comment by scanum** [comment]
@zehawki Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
