### ISSUE TITLE
"Tip" content table 

### ISSUE THREAD

**Issue by alisalih1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1335]
Tip content table doesn't format correctly on desktop browser. (Neither mobile)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c43928-84c0-0a75-9354-66aef3b83e46
* Version Independent ID: f95298ae-de58-02eb-0b49-8390ab161d4c
* Content: [Plan for governance in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/plan-teams-governance)
* Content Source: [Teams/plan-teams-governance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-teams-governance.md)
* Service: **msteams**
* GitHub Login: @rmw2890
* Microsoft Alias: **MyAdvisor**

**Comment by jamesrhea** [comment]
@alisalih1 thanks for the feedback. This looks like it's due to the formatting applied when a table is within a note, combined with the lengthy content in the Details column. My updates should resolve the display issues.
