### ISSUE TITLE
Permissions for access to CQD

### ISSUE THREAD

**Issue by JamesMemmott** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1340]
The document describes the level of helpdesk permission (tier 1 & 2) required to access Call Analytics. However, there is no mention of the access levels required to access CQD

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dedf646c-c5dc-5645-54a2-1bca0d406f45
* Version Independent ID: 9a52f0b1-2970-559e-2d18-8e565662ca26
* Content: [Call Analytics and Call Quality Dashboard](https://docs.microsoft.com/en-gb/microsoftteams/difference-between-call-analytics-and-call-quality-dashboard)
* Content Source: [Teams/difference-between-call-analytics-and-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/difference-between-call-analytics-and-call-quality-dashboard.md)
* Service: **skype-for-business-online**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by GageAmes** [comment]
Thank you for the feedback, @JamesMemmott.  The list of roles that can access CQD were added to the document in 2ac471ed11bf3dad48ebda1243e9b63523fc7d1c.
@yogkumgit that should be sufficient to close the issue.

**Comment by yogkumgit** [comment]
@GageAmes  Thank you very much for the contribution and sharing this explanation. @JamesMemmott 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
