### ISSUE TITLE
What happen after trial expires with users data?

### ISSUE THREAD

**Issue by walkercz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1343]
What happen after trial expires with users data?

**Comment by dariomws306** [comment]
Hi @walkercz , thank you for your feedback.

Could you let me know tha article or product you are talking about? Thanks.

**Comment by walkercz** [comment]
Hello,
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/iw-trial-teams.md

Question is about what happen to user data when teams trial expires.

**Comment by dariomws306** [comment]
Thank you @walkercz.

The same apply to all licenses:
"When you remove or delete a license, the user's old email, contacts, and calendar are retained for 30 days, then permanently deleted. If you remove or delete a license but don't delete the account, the content in the user's OneDrive will remain accessible to you even after 30 days. "

**Comment by scanum** [comment]
@walkercz  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
