### ISSUE TITLE
Can't deploy msi during Autopilot

### ISSUE THREAD

**Issue by PJMarcum** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1344]
The Teams msi does not install during autopilot. Per the documentation. "We recommend that you deploy the package to the computer" however when it's imported in to Intune I see "Execution Context: Per-User" which is a value read from the msi which cannot be changed. When I assign the msi to all devices Autopilot will hang on the teams install, it looks to me like the msi never even launches. I say because it doesn't generate a log file which indicates to me that it never launched.

**Comment by dariomws306** [comment]
Hi @PJMarcum , thank you for your feedback.

Could you let me know the article you are talking about? Thanks.

**Comment by scanum** [comment]
@PJMarcum  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
