### ISSUE TITLE
Duplicate graphic

### ISSUE THREAD

**Issue by jahaney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1345]
The Scaled Consolidated Edge with DNS Load balancing appears to use the same graphic as the Scaled Consolidated Edge with Hardware Load Balancing. Information is the same, but it might be more clear to remove the HLB from the DNS LB image

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44959660-7464-6f77-6558-d49333fc9320
* Version Independent ID: 56ace341-deb0-1560-b847-31e9ebd0ca86
* Content: [Edge Server scenarios in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/edge-server-deployments/scenarios)
* Content Source: [Skype/SfbServer/plan-your-deployment/edge-server-deployments/scenarios.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/edge-server-deployments/scenarios.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by dariomws306** [comment]
Hi @jahaney , thank you for your valuable feedback.

"Scaled consolidated Skype for Business Server Edge pool, with DNS load balancing and public IP addresses" is the same image as "Scaled consolidated Skype for Business Server Edge pool, with hardware load balancing".

First one is wrong, I will try to get the right image.

**Comment by dariomws306** [comment]
@MicrosoftHeidi could you help me with this?

Plan_LyncServer_Edge_Scenario_ScaledConsolidatedEdgeDNSLBPublicIP.jpg is the same image as Plan_LyncServer_Edge_Scenario_ScaledConsolidatedEdgeHLB.jpg. Do you have the original images?

**Comment by MicrosoftHeidi** [comment]
The original images may not exist, I can check around with any of my colleagues who may have been here at that time.

**Comment by dariomws306** [comment]
Thank you @MicrosoftHeidi !

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@MicrosoftHeidi Hi Heidi, any updates on this issue?

**Comment by MicrosoftHeidi** [comment]
None at this time.

**Comment by scanum** [comment]
@MicrosoftHeidi Thanks Heidi! Please let us know when there is an update.

**Comment by SerdarSoysal** [comment]
@MicrosoftHeidi is working on it. We should update by next week.

**Comment by scanum** [comment]
@SerdarSoysal Hi! Thanks for letting us know. Wondering if there are any updates on this?

**Comment by scanum** [comment]
@SerdarSoysal @MicrosoftHeidi  Following up on this issue. Please let me know if there are any updates.

**Comment by scanum** [comment]
@SerdarSoysal @MicrosoftHeidi Following up on this issue. Thanks.

**Comment by scanum** [comment]
@SerdarSoysal @MicrosoftHeidi Following up on this issue. Thanks.

**Comment by scanum** [comment]
@SerdarSoysal @MicrosoftHeidi Following up on this issue. Thanks.

**Comment by scanum** [comment]
@SerdarSoysal @MicrosoftHeidi Following up on this issue. Thanks.

**Comment by scanum** [comment]
@SerdarSoysal @MicrosoftHeidi Following up on this issue. Thanks.

**Comment by MicrosoftHeidi** [comment]
This is completed, duplicate graphic has been removed.

**Comment by dariomws306** [comment]
Thank you @MicrosoftHeidi! Looks like it's not live yet, I will check in some days.
