### ISSUE TITLE
The Import-Module command looks unnecessarily complex.

### ISSUE THREAD

**Issue by PSPally** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1347]
You don't need all the double slashes.  :-)
The document has "Import-Module "C:\\Program Files\\C...", the reason to use double quotes in PowerShell is because you want things inside the quotes evaluated.  Like including a variable.  Since your not doing that single quotes, like ', would be the type to use.  And since you're not  having it evaluated the \\ can be changed to a \.
Although I would expect Import-Module -Name SkypeOnlineConnector to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41978fab-1959-adc5-ee3a-aa16678f31f3
* Version Independent ID: 62d32d00-4aae-bd5a-d093-d3a6266d6548
* Content: [Set the Caller ID for a user](https://docs.microsoft.com/en-us/skypeforbusiness/what-are-calling-plans-in-office-365/set-the-caller-id-for-a-user)
* Content Source: [Skype/SfbOnline/what-are-calling-plans-in-office-365/set-the-caller-id-for-a-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/what-are-calling-plans-in-office-365/set-the-caller-id-for-a-user.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by dariomws306** [comment]
Hi @PSPally , thank you for your feedback.

I am applying an update on this article.

**Comment by scanum** [comment]
@PSPally  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
