### ISSUE TITLE
What about Homeoffice or just mobile anywhere?

### ISSUE THREAD

**Issue by SusanKocerka** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1348]
There is not always classified network range or something. I mean is there a kind of exception to say: If it is not one of those networks, then this person is on the road or homeoffice.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2f8119c9-61af-b469-af98-ddd37764c0ca
* Version Independent ID: 7d829a74-9df7-5b6f-8e1c-44d3e5d38f75
* Content: [Hinzufügen und Aktualisieren von Daten für Speicherorte](https://docs.microsoft.com/de-DE/microsoftteams/learn-more-about-site-upload?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/learn-more-about-site-upload.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.de-DE/blob/live-sxs/Teams/learn-more-about-site-upload.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **lolaj**

**Comment by dariomws306** [comment]
Hi @SusanKocerka , thank you for your feedback.

I think you just not add these networks to the file. And then you know if it's not clasified, it's not some of your networks.

**Comment by scanum** [comment]
@SusanKocerka  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by SusanKocerka** [comment]
Well if you ask me:

No it's still a Case! @dariomws306 : I've added the networks to the / a file, but the only thing it's worth for seems to be the "call quality dashboard".
Within S4B everybody had the chance to "Setup" the location / site / whatever… in Teams is no Option available actually. As an Administrator, I thought: ok, give "Locations" a Chance, but NO... Just "call Quality Dashboard" an no chance for users to get the location of their teammates within ONE APP.

**Comment by scanum** [comment]
@officedocsbot reopen

**Comment by dariomws306** [comment]
Hi @SusanKocerka , please help me to understand.

Do you think it's an issue in the documentation or your concern is that there isn't a place with a simple and unique interface to add locations?

Thank you so much!

**Comment by SusanKocerka** [comment]
Hi @dariomws306 ,

Thank you for your reply

I think, that there should be a note in the documentation, that the location data added there, is just for the "Call Quality Dashboard".

Although it would be a good opportunity to integrate these locations (by networks) into Teams apps. Maybe there is a way to add that for contacts (right behind or beneath the name).

**Comment by dariomws306** [comment]
Hi @SusanKocerka , thank you again for your feedback.

I think there is a text wich specify that:
"This file is used by Call Analytics and Call Quality Dashboard for generating reports"

To generete a request to add this feature or similar the right place to do it is User Voice:
https://microsoftteams.uservoice.com/forums/555103-public

Thank you.

**Comment by dariomws306** [comment]
Don't worry!

It's the same article:
https://docs.microsoft.com/en-us/microsoftteams/learn-more-about-site-upload
