### ISSUE TITLE
Doc is not updated with the most recent SQL Server editions

### ISSUE THREAD

**Issue by pgrlopes** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1351]
AlwaysOn section of the Back End High Availability for Skype for Business is outdated, showing that the only supported SQL server versions are 2012 and 2014. This article states that sql server 2016 is supported: https://support.microsoft.com/en-us/help/4100776/sql-server-2016-sp1-is-available-for-the-back-end-servers-of-skype
Sql server 2017 should be too.

Customers are getting confused on this, multiple threads have been closed stating that the issue is fixed, but it doesn't seem to be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8c5958a-c5e5-5aba-211a-2886c86ba831
* Version Independent ID: e53ed9d2-4ee4-346a-054b-6cf44b6a189b
* Content: [Back End Server high availability in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/high-availability-and-disaster-recovery/back-end-server)
* Content Source: [Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/back-end-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/back-end-server.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hi @pgrlopes thanks for your feedback!
The article has been improved including missing SQL Supported Versions after your comment.
Thank you!

**Comment by msordakis** [comment]
Always on section still shows that only SQL Server 2014 Enterprise Edition and SQL Server 2012 Enterprise Edition are supported. Could you change that please?

**Comment by scanum** [comment]
@get-itips Andres could you please look at this? Thanks!

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by PrometheusRising1** [comment]
AlwaysOn still shows support only for 2012 and 2014 SQL Server - please update with all possible versions.  It is important, or Skype teams will mark the newer versions as "not supported" and the upgrade path will be more difficult.

**Comment by get-itips** [comment]
Hello @PrometheusRising1 thanks for your feedback, actually, a Pull Request is created with the needed changes, although it hasn't been merged yet. Will try to accelerate that. Thanks

**Comment by scanum** [comment]
@pgrlopes Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
