### ISSUE TITLE
This assumes ADFS

### ISSUE THREAD

**Issue by oradcliffe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1355]
This is a little confusing, as it assumes only ADFS as STS.  We can also use AzureAD as STS, as this article suggests:
https://techcommunity.microsoft.com/t5/Skype-for-Business-Blog/Hybrid-Modern-Authentication-for-Skype-for-Business/ba-p/134751

We should have this page updated with this information as well so customers don't assume you can only use ADFS as token signer for modern auth with Skype on-prem deployments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcc8ce50-2000-041a-9489-0acea7b2e24a
* Version Independent ID: 0839378b-1455-b5b5-f315-29e55c25cee8
* Content: [How to use Modern Authentication (ADAL) with Skype for Business](https://docs.microsoft.com/en-us/SkypeForBusiness/manage/authentication/use-adal?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json)
* Content Source: [Skype/SfbServer/manage/authentication/use-adal.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/authentication/use-adal.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by MSFTTracyP** [comment]
Thank you for this feedback. I'll look into this.

**Comment by onimrk** [comment]
Does this work with any other STS or only ADFS and AAD?

**Comment by get-itips** [comment]
Hi @oradcliffe Thanks for your feedback, we really appreciate it. As that is a feature of Office 365 Enterprise, the content to use SfB Onpremises with Azure AD STS is in Office 365 Enterprise section, please see

https://docs.microsoft.com/en-us/office365/enterprise/configure-skype-for-business-for-hybrid-modern-authentication

**Thank You**

**Comment by oradcliffe** [comment]
Understood, it might make it helpful to link to that page in this doc and mention that ADFS isn't the only option for implementing MA with SfB on-prem though.  Thanks!

**Comment by get-itips** [comment]
Agree, I'll probably make a PR to add a link into the Top-Level Document about SfB Authentication. Thank you.

**Comment by scanum** [comment]
@oradcliffe  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
