### ISSUE TITLE
Server address is different than one setup by the 365 domain setup wizard.

### ISSUE THREAD

**Issue by webstaff** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1356]
As titled the address sipdir.online.microsoft.com is different than the one in the domain setup wizard which is sipdir.online.lync.com Which one should you use, not that either one is working for me currently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81793c63-4503-3acf-4dd8-3e5548baedd1
* Version Independent ID: 57ba26be-8787-5690-f0d3-fd5fbb802772
* Content: [Troubleshooting Skype for Business Online sign-in errors for administrators](https://docs.microsoft.com/en-us/SkypeForBusiness/set-up-skype-for-business-online/troubleshooting-sign-in-errors-for-admins#update-dns-service)
* Content Source: [Skype/SfbOnline/set-up-skype-for-business-online/troubleshooting-sign-in-errors-for-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-skype-for-business-online/troubleshooting-sign-in-errors-for-admins.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@webstaff  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
