### ISSUE TITLE
No Teams documentation? Wow

### ISSUE THREAD

**Issue by Jason6311** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1358]
How can the Office 365 section of this deployment documentation not have a single mention of Teams? This is a fail. Please address that issue here, or create a separate page dedicated to the transition of SRS rooms from SfBO to Teams. Big miss here folks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41965bc8-45c0-e4eb-aa36-5ef5adbe460a
* Version Independent ID: 97de65ad-04fc-5b62-c7c7-fba8d0aeb1de
* Content: [Deploy Skype Room Systems v2 with Office 365](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/with-office-365#feedback)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/with-office-365.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by danmyhre** [comment]
Separate page for Teams...surprising this was missed given the huge focus on Teams

**Comment by scanum** [comment]
@jambirk Hi James, any updates on this issue? Thanks!

**Comment by jambirk** [comment]
We just released a rebrand of the doc set to reflect the product rename made in January. We're hoping to get this out of our backlog and into an upcoming spring plan.

**Comment by scanum** [comment]
@Jason6311 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
