### ISSUE TITLE
SfB Server 2015 online documentation flops to SfB Server 2019 pages when links on left are reviewed

### ISSUE THREAD

**Issue by swakhlu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1364]
I start with SfB Server 2015 page title on left of screen. But as I select links underneath the page title shifts to SfB Server 2019. So hard to know if I am reading about SfB Server 2019 or 2015 feature.  I am guessing every link after the Whats new is based on common content between the two versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54dbd858-1cd1-8351-3ed6-6dd1f54ebc4b
* Version Independent ID: 73b28e85-2e71-b037-a98e-e8913c2e343b
* Content: [What's new in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/what-s-new-in-skype-for-business-server)
* Content Source: [Skype/SfbServer/what-s-new-in-skype-for-business-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/what-s-new-in-skype-for-business-server.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by dariomws306** [comment]
Hi @swakhlu , thank you for your feedback.

Are you talking about these links?

![image](https://user-images.githubusercontent.com/33589238/54784880-a77b4f80-4c03-11e9-9c59-5c7303e7f064.png)

**Comment by dariomws306** [comment]
I see that you only are redirected if you click on "Skype for Business downloads and updates". But it looks good because it's the same for 2015 and 2019.

**Comment by swakhlu** [comment]
Hi Dario
I was referring to a wider set of tabs then "Skype for Business downloads
and updates" under Skype for Business 2015 online documentation.
But the reason you give could in that case equally apply to those tabs. For
example - going down to > Plan , > Deploy etc many of the sub-tabs go back
to 2019.

This becomes confusing because one is browsing between tabs on the left of
page starting with 2015 you find suddenly the top heading has changed to
2019 version.

Hope this explains why I raised the initial issue on GitHub.

Regards
Sam

**Comment by kenwith** [comment]
hi @swakhlu  - thanks for taking the time to provide this feedback. This is a known issue we are working to resolve. The reason it is happening is that many of the articles are 'evergreen' meaning that they apply to both 2015 and 2019. But not all of them. There is a TOC file for 2015 and one for 2019. And in some articles the 2019 points to the evergreened article and it causes problems in the TOC rendering. This is a known problem we are solving and I am capturing our progress here: #1861

This is all open source and being done transparently so if you are interested you can see what I am referring in the TOC article here: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/tree/live/Skype/SfbServer/sfbstoc and here: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/tree/live/Skype/SfBServer2019/sfbs2019toc

Hoping to get this resolved ASAP. Thanks again for taking the time to make the content and experience better. It is much appreciated!

CC @SerdarSoysal
