### ISSUE TITLE
Changing global policy doesnt work

### ISSUE THREAD

**Issue by JBFulc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1368]
I have tried to change the global (org-wide default) policy so that chat is enabled.
The button switched to on and I was able to save. The chat functionality was not enabled.

I created a new policy as a copy of the default and applied it to my account. Chat was enabled within minutes.
This would be OK apart from the fact there is no way that I can see to set this policy to all users. I have to go through each user one by one??!

Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34f3188-0af5-f972-9d28-959f5f7866a2
* Version Independent ID: fab26e11-a729-92a4-3ea6-8668dca55dd0
* Content: [What are Messaging policies in Teams?](https://docs.microsoft.com/en-us/microsoftteams/messaging-policies-in-teams)
* Content Source: [Teams/messaging-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/messaging-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by JBFulc** [comment]
So the next problem now that chat is enabled. I get this when trying to chat with another person. They also get the same when they try to chat to me:
![image](https://user-images.githubusercontent.com/41430508/50910892-a325ff80-1426-11e9-9369-b367911ae2be.png)

Going to the old console that manages this I found:
![image](https://user-images.githubusercontent.com/41430508/50910943-bf29a100-1426-11e9-8c28-82be35a8df1c.png)

**Comment by TehWez** [comment]
Have the same exact issue.  I changed the Messaging policy in Microsoft teams for that user, now that user can send chat messages but not relieve them.  Very frustrating.

**Comment by scanum** [comment]
@JBFulc  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
