### ISSUE TITLE
Guest Experience

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1369]
Please add information about the Guest Experience with SharePoint Online and Teams.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60fd4eb7-6f1a-2dfa-27db-01c3a0d00f30
* Version Independent ID: c1688075-18bf-534d-f402-ee062840d83f
* Content: [How SharePoint Online and OneDrive for Business interact with Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/sharepoint-onedrive-interact)
* Content Source: [Teams/SharePoint-OneDrive-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/SharePoint-OneDrive-interact.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by get-itips** [comment]
Hi @DeanGross how are you?
Are this articles answering  your question?

https://docs.microsoft.com/en-us/microsoftteams/guest-experience

https://support.office.com/en-us/article/guest-capabilities-in-teams-d03fdf5b-1a6e-48e4-8e07-b13e1350ec7b?ui=en-US&rs=en-US&ad=US

Thank you

**Comment by DeanGross** [comment]
Thanks, those pages have good information. I was thinking that it would be good to add some of that information or links to those pages to this specific page to help readers understand how the experience changes for different types of users.

**Comment by get-itips** [comment]
Thank you @DeanGross I'll create a new version of the article adding a link to guest experience information.

**Comment by scanum** [comment]
@officedocsbot close
