### ISSUE TITLE
License for activation user in Direct Routing multi tenant

### ISSUE THREAD

**Issue by mazhagiah** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1373]
Does it require to provide E5 license for Activation user or just sip address is enough in customer's tenant for Direct Routing in multi-tenant ?

**Comment by get-itips** [comment]
Hi @mazhagiah do you have a specific article that you are talking about that needs to be corrected?  I think this article might answer your question https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants
Hope it helps you.

**Comment by scanum** [comment]
@officedocsbot close
