### ISSUE TITLE
Message formatting dropped when originating from the command-bar

### ISSUE THREAD

**Issue by robertjacobson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1374]
Messages that contain links, markdown, or other text formatting started from the command bar (entire message content is added to the command bar) is not auto-formatted appropriately on Mac OS (10.14.2). Essentially, a new message originating from the command bar that contains a link, the message is formatted as plain text and the link is not click-able.

**Comment by get-itips** [comment]
Hi  @robertjacobson thanks for your feedback. Can you kindly give us the reference article that needs to be corrected? is there any issue with documentation? Thank you

**Comment by scanum** [comment]
@officedocsbot close
