### ISSUE TITLE
Needs updating to include Meeting Migration Service

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1376]
Articled needs to be updated to included MMS https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/setting-up-the-meeting-migration-service-mms

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2c88f9f-8e46-966a-30be-5c2506cf578c
* Version Independent ID: 5568a567-2432-f76a-2179-daa43edf257b
* Content: [Plan hybrid connectivity between Skype for Business Server and Skype for Business Online](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-hybrid-solutions/plan-hybrid-connectivity)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/plan-hybrid-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-hybrid-connectivity.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by nenonix** [comment]
@TorrenManson Thanks for pointing this out.  Is this the right article?  If so, are you suggesting we add the article as a link? Please give me some more details so I can work with you to amend the documentation.

**Comment by TorrenManson** [comment]
Hi,

Yes, it’s the right article.

The section “User accounts and data”, the very last bullet in the section says “Conferencing data, meeting content, and scheduled meetings…users must reschedule meetings…”

However, the Meeting Migration Service will do this automatically when a user is migrated from SfB server to SfBO or Teams.

Cheers,
Torren
