### ISSUE TITLE
Adoption Team model - image resolution

### ISSUE THREAD

**Issue by liesnys** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1379]
Hi,
would it be possible to publish the Large Scale Corporate Adoption Model image with a higher resolution, please? 

Many thanks!
regards,
Liz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3382a91-be9f-bfab-d91f-3197a6655b97
* Version Independent ID: 51459c35-8bb3-1aaa-0da0-2128d29251ea
* Content: [Define outcomes and success for your Microsoft Teams adoption](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-adoption-define-outcomes)
* Content Source: [Teams/teams-adoption-define-outcomes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-adoption-define-outcomes.md)
* Service: **msteams**
* GitHub Login: @karuanag
* Microsoft Alias: **karuanag**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @jambirk 

Kindly look into this issue. Or suggest us if we need to report this issue to some other team? Thank you.

**Comment by scanum** [comment]
@jambirk Hi James, any updates on this?

**Comment by Reeced40** [comment]
@liesnys Thank you for your feedback, I'm investigating further.

**Comment by jambirk** [comment]
I don't know who would have the original source file. While I agree the image is fuzzy and poor quality, redoing it without that source file might be difficult.  @LanaChin and @karuanag might have the originals. With that, getting a resized image would be possible.

**Comment by scanum** [comment]
@karuanag @LanaChin Hi! Following up on this issue. Are there any updates on this? Thanks!

**Comment by LanaChin** [comment]
@scanum - I've sent you the replacement image in email. Thank you.

**Comment by Reeced40** [comment]
@scanum This can be closed, thanks.

**Comment by scanum** [comment]
@liesnys Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
