### ISSUE TITLE
Testing for Teams client

### ISSUE THREAD

**Issue by d1bjo0** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1381]
You might want to update the "End User Control" Section to detail the setting on the Teams client. Under Settings-&gt;Calls an end user (if enabled by the admin) can select "Hide my phone number and profile information for all calls" option. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a55064a-f85f-6f10-1e3d-be6177868338
* Version Independent ID: cabebb99-c0a7-a147-0c61-5b32cacc0651
* Content: [How can caller ID be used in your organization](https://docs.microsoft.com/en-us/SkypeForBusiness/what-are-calling-plans-in-office-365/how-can-caller-id-be-used-in-your-organization?toc=/MicrosoftTeams/toc.json&bc=/microsoftteams/breadcrumb/toc.json#feedback)
* Content Source: [Skype/SfbOnline/what-are-calling-plans-in-office-365/how-can-caller-id-be-used-in-your-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/what-are-calling-plans-in-office-365/how-can-caller-id-be-used-in-your-organization.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by lindspea** [comment]
@d1bjo0 Hi Bruce.  Thanks for pointing this out.  I will have the changes reviewed and implemented as soon as possible.  Thanks for your valued input in helping improve MS docs.

**Comment by lindspea** [comment]
@AndreaBarr @yogkumgit this can be closed thank you.

**Comment by yogkumgit** [comment]
@lindspea Thank you very much for the contribution and updating the documentation with PR. @d1bjo0  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
