### ISSUE TITLE
Nothing helpful on typical  daily business work

### ISSUE THREAD

**Issue by funzel1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1390]
Still a role missing if you have different IT teams for Exchange, Skye and Teams.
So a Sharepoint admin for example should be abler to set , change Teams owner, members (o365group) and able to run ps get-team against any Team.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6b434530-6bf2-6e00-6eae-6fa043d022ce
* Version Independent ID: caab785f-e3a4-831a-87d8-26934a9f834f
* Content: [Verwenden der Microsoft Teams-Administratorrollen zum Verwalten von Teams](https://docs.microsoft.com/de-de/microsoftteams/using-admin-roles)
* Content Source: [Teams/using-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.de-DE/blob/live-sxs/Teams/using-admin-roles.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@funzel1  - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make Skye for Business better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://www.skypefeedback.com/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by scanum** [comment]
@officedocsbot close
