### ISSUE TITLE
January 2019 updates missing

### ISSUE THREAD

**Issue by bubbletroubles** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1400]
The January 2019 Cumulative Update for Skype for Business Server 2015 is not listed on this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be9f745c-5925-3a7b-9430-b5e61b4384ba
* Version Independent ID: bc23dce3-f38b-9e81-1614-d16aed1d8684
* Content: [Skype for Business Server updates](https://docs.microsoft.com/en-us/skypeforbusiness/sfb-server-updates#skype-for-business-server-2015-update-history)
* Content Source: [Skype/SfbServer/sfb-server-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/sfb-server-updates.md)
* Product: **skypeforbusiness-server-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
@Ariantor can you respond please?

**Comment by jambirk** [comment]
Ari added the release, thank you for pointing this out.
