### ISSUE TITLE
Requirement for Exchange Online mailbox

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1404]
Hi! Is it required to have an exchange online mailbox to schedule live event?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @tonysmith
* Microsoft Alias: **tonysmit**

**Comment by get-itips** [comment]
Hi @Larryngolog thanks for your feedback.
I tested in a lab and could not schedule a live event without a mailbox.
Will update the article to add a note about this.
Thank you!

**Comment by scanum** [comment]
@officedocsbot close
