### ISSUE TITLE
Sway Link Broken 

### ISSUE THREAD

**Issue by tech4ce** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1406]
"View this overview for an introduction to the Skype for Business to Teams upgrade journey, including core concepts, framework, and upgrade paths." - Overview link is broken. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7b32af2-59db-a872-6ed4-fc7b4cd910b3
* Version Independent ID: 38fd3a1a-ee6d-dd63-0de9-5f726d7419cf
* Content: [Skype for Business to Microsoft Teams upgrade](https://docs.microsoft.com/en-US/MicrosoftTeams/journey-skypeforbusiness-teams?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/Journey-SkypeforBusiness-Teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Journey-SkypeforBusiness-Teams.md)
* Service: **msteams**
* GitHub Login: @dearbeen
* Microsoft Alias: **dearbeen**

**Comment by jamesrhea** [comment]
Thanks for catching this, @tech4ce. I'll look into what we can do to resolve the issue, @AndreaBarr.

**Comment by jamesrhea** [comment]
@tech4ce the link is fixed now. @AndreaBarr, this issue can be closed. Thanks!
