### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by dougkillmer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#141]
Start-CcDownload returns a warning when trying to download this file:

Downloading file from https://go.microsoft.com/fwlink/?LinkId=852532 to C:\Users\Administrator\CloudConnector\SiteRoot\Bits\KB2982006\478232_intl_x64_zip.exe...
WARNING: Cannot download file 478232_intl_x64_zip.exe. Run Start-CcDownload cmdlet again. If retry keep failing, manually download file '478232_intl_x64_zip.exe' to folder 
WARNING: 'C:\Users\Administrator\CloudConnector\SiteRoot\Bits\KB2982006'. Failure exception: Exception calling "DownloadFile" with "2" argument(s): "Unable to connect to the remote server"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fb5390-e0c3-6013-0903-50aa3b01a65b
* Version Independent ID: fc0233ec-d235-f22e-1b4b-0438a49a3d7f
* Content: [Start-CcDownload](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/start-ccdownload)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/start-ccdownload.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/start-ccdownload.md)
* Service: **unspecified**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by tonysmit** [comment]
Hi. Thanks for the feedback. I'm investigating this and trying to find a PM that I can assign this issue. Thanks, Tony

**Comment by dougkillmer** [comment]
Thanks, Tony.  Here are some additional screenshots of the issue. I've also opened an Office 365 support request #7932819.  They are gathering more information about the problem.

![image](https://user-images.githubusercontent.com/11560014/39199414-41c8c696-479e-11e8-8d7b-cd9bfa6ad7d4.png)
![image](https://user-images.githubusercontent.com/11560014/39199441-51a16456-479e-11e8-9bc5-49a3e30d6aab.png)

**Comment by tonysmit** [comment]
@CarolynRowe, I passing this over to you because it's cloud connector.

**Comment by tonysmit** [comment]
Thanks Doug! I assigned this to Carolyn on my team as she owns the hybrid space for Skype.

Thanks, Tony

**Comment by dougkillmer** [comment]
The Office 365 Support Engineer had me run the following command to download the missing file:

`Start-CcDownload -DownloadBitsOnly`

This fixed the issue and I was able to continue installation.

**Comment by CarolynRowe** [comment]
Closing this issue.
