### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by MichaelNiederle** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1413]
Product Name "Surface Hub" is translated to "die Fläche Hub", which should not happen.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: f256cd5b-3ec8-2d55-9ae4-ff9849d52eae
* Version Independent ID: 52c2271b-df38-5dc9-c2a1-553cdf3b5496
* Content: [Bereitstellen von Microsoft-Teams für die Fläche Hub](https://docs.microsoft.com/de-de/microsoftteams/teams-surface-hub#feedback)
* Content Source: [Teams/teams-surface-hub.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.de-DE/blob/live-sxs/Teams/teams-surface-hub.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by lindspea** [comment]
@samanthaw @MollyMalone

**Comment by lindspea** [comment]
@MichaelNiederle Thank you for pointing this out Michael.  I will work to have this fixed as soon as possible. Thank you for your valuable contribution in helping improve MS docs.

**Comment by MollyMalone** [comment]
@lindspea Hi Lindsay, FYI, @samanthaw manages the translated Skype + Teams + Kaizala content.   I own the Office, SharePoint, Exchange, Project content.   Regards Tina (a.k.a. Molly)

**Comment by lindspea** [comment]
@samanthaw

**Comment by samanthaw** [comment]
looking into it

**Comment by samanthaw** [comment]
@MichaelNiederle the issue is fixed

**Comment by lindspea** [comment]
@AndreaBarr @yogkumgit seems this can be closed thank you.
