### ISSUE TITLE
Filters on teams analytics and reports

### ISSUE THREAD

**Issue by danielsykes84** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1416]
Great product addition, thanks! It would be great to have filter and sort options on all columns on these reports, e.g. Display name, Privacy, Active users, Guests, Active channels, Messages, etc. Or alternatively, an Export to Excel option. This would give us greater ability to process and make interpretations from these useful reports.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ade1a4-092c-1132-44df-ee2c683fdd33
* Version Independent ID: 396b1aee-2f40-9895-9b00-07e38d11d31b
* Content: [Microsoft Teams analytics and reporting](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-reporting-reference)
* Content Source: [Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by baluilag** [comment]
Spelling mistake on this page under topic "Teams reporting references".
word "particpated" must be corrected as "participated".

**Comment by scanum** [comment]
@danielsykes84  - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make Skye for Business better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://www.skypefeedback.com/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by scanum** [comment]
@officedocsbot close
