### ISSUE TITLE
Desktop Logs

### ISSUE THREAD

**Issue by baluilag** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#142]
For windows client, below mentioned location will not work. 
Client	Location
Windows	%appdata%\Roaming\Microsoft\Teams\logs.txt

It must be 
Windows: 	%appdata%\Microsoft\Teams\logs.txt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d5e6d3-b7e0-d79f-0dea-ed423186a157
* Version Independent ID: ec6e68aa-552f-ab45-3c8e-92eff526b173
* Content: [Use log files in troubleshooting Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/log-files#feedback)
* Content Source: [Teams/log-files.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/log-files.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by tonysmit** [comment]
@baluilag - I checked my installation on Windows 10 and it is C:\Users\<user>\AppData\Roaming\Teams\logs

**Comment by MatthewSteeples** [comment]
I'm with @baluilag. While @tonysmit has the path correct, %appdata% resolves to C:\Users\Username\AppData\Roaming so the instructions ask for Roaming to be in the folder path twice
