### ISSUE TITLE
Licensing Too Vague

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1430]
"assign an Office 365 license'  - what exactly needs to be licensed with this?  This must be specific to ensure that I assign the correct license.    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9978e48b-5b8d-df59-d8d3-d3c90a8efafb
* Version Independent ID: 52429f1d-39a1-49fb-c9dd-d4bafa19760d
* Content: [Deploy Skype Room Systems v2 with Exchange Online](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/with-exchange-online)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/with-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/with-exchange-online.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by lindspea** [comment]
@r-milne Thank you for your valuable contribution to improving MS docs.  Would you suggest perhaps changing the wording to read "Activate the service using your valid Microsoft Office 365 license"...?

**Comment by lindspea** [comment]
@r-milne we would like to resolve this issue for you, so please reach out to us again by opening another issue if we can be of further assistance.

**Comment by lindspea** [comment]
@yogkumgit @AndreaBarr This issue can be closed.
