### ISSUE TITLE
Exchange Remote PowerShell

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1431]
Why is the current MFA PowerShell missing?  Advocating the use of non-MFA is not secure.  At a minimum you need to provide both.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9978e48b-5b8d-df59-d8d3-d3c90a8efafb
* Version Independent ID: 52429f1d-39a1-49fb-c9dd-d4bafa19760d
* Content: [Deploy Skype Room Systems v2 with Exchange Online](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/with-exchange-online)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/with-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/with-exchange-online.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@jambirk Hi James, any updates on this issue? Thanks!

**Comment by jambirk** [comment]
@r-milne can you clarify please? Are you referring to the use of AD 1.0 commands rather than 2.0 equivalents? The older (MSOLUser) commands are used because the 2.0 commands are not yet tested on this device. A test plan to correct that is being crafted, but is still in early stages.

**Comment by scanum** [comment]
@r-milne  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
