### ISSUE TITLE
Exhcange Hybrid

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1432]
Please add in a detailed technical note stating why your approach does not involve the use of new-remotemailbox or enable-remote-mailbox cmdlets.  These cmdlets are designed for hybrid use.  Is this due to the EnableRoomMailboxAccount parameter ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9978e48b-5b8d-df59-d8d3-d3c90a8efafb
* Version Independent ID: 52429f1d-39a1-49fb-c9dd-d4bafa19760d
* Content: [Deploy Skype Room Systems v2 with Exchange Online](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/with-exchange-online)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/with-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/with-exchange-online.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@jambirk Hi James! Any updates on this issue? Thanks.

**Comment by jambirk** [comment]
@r-milne Those commands are untested on Rigel. @sohailta and @gregbari may be able to comment further.

**Comment by scanum** [comment]
@sohailta @gregbari Hi, any updates on this issue?

**Comment by scanum** [comment]
@r-milne Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
