### ISSUE TITLE
Step 4 - Connect to Azure AD

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1433]
"You need to connect to Azure AD to apply some account settings. "

There are no documented settings of changes in this section.  Why is this here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9978e48b-5b8d-df59-d8d3-d3c90a8efafb
* Version Independent ID: 52429f1d-39a1-49fb-c9dd-d4bafa19760d
* Content: [Deploy Skype Room Systems v2 with Exchange Online](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/with-exchange-online)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/with-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/with-exchange-online.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@jambirk Hi James! Any updates on this issue? Thanks!

**Comment by jambirk** [comment]
It looks like step 4 of "create account" can indeed be safely moved to the next section, where we apply licenses and so on.

**Comment by jambirk** [comment]
moved, closing the issue
