### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1434]
In section
Add an email address for your on-premises domain account

"click New, and the click User"

I suspect that this should have been "click New, and then click Use"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9978e48b-5b8d-df59-d8d3-d3c90a8efafb
* Version Independent ID: 52429f1d-39a1-49fb-c9dd-d4bafa19760d
* Content: [Deploy Skype Room Systems v2 with Exchange Online](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/with-exchange-online)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/with-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/with-exchange-online.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by lindspea** [comment]
@r-milne. Thank you for your help in improving MS docs.  I will work to have the typo fixed as soon as possible.

**Comment by lindspea** [comment]
@yogkumgit  @AndreaBarr this can be closed
