### ISSUE TITLE
Vague Step

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1436]
"After you've created the account, run a directory synchronization. When it's complete, go to the users page and verify that the two accounts created in the previous steps have merged."

How do I run this?  Do I need a full or a delta? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9978e48b-5b8d-df59-d8d3-d3c90a8efafb
* Version Independent ID: 52429f1d-39a1-49fb-c9dd-d4bafa19760d
* Content: [Deploy Skype Room Systems v2 with Exchange Online](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/with-exchange-online)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/with-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/with-exchange-online.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@jambirk Hi James, any updates on this issue? Thanks!

**Comment by scanum** [comment]
@jambirk Hi James, any updates on this issue? Thanks!

**Comment by jambirk** [comment]
Either a full or a delta will work. @scanum, the specific command is **Set-MsolDirSyncConfiguration  -Force**    Please add a mention of the specific command or the powershell reference page:
https://docs.microsoft.com/en-us/powershell/module/msonline/set-msoldirsyncconfiguration?view=azureadps-1.0

**Comment by scanum** [comment]
@r-milne Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
