### ISSUE TITLE
Language Quesiton

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1437]
In section

"Assign an Office 365 license"

The user account needs to have a valid Office 365 license to ensure that Exchange and Skype for Business Server will work. If you have the license, you need to assign a usage location to your user account

It says "IF" I have a license available.  Did it not just say that licenses are required?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9978e48b-5b8d-df59-d8d3-d3c90a8efafb
* Version Independent ID: 52429f1d-39a1-49fb-c9dd-d4bafa19760d
* Content: [Deploy Skype Room Systems v2 with Exchange Online](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/with-exchange-online)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/with-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/with-exchange-online.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by lindspea** [comment]
@r-milne.  Thank you for pointing this out and for your valuable contribution to improving MS docs.  How does this sound? "Use your valid license to assign a usage location to your user account."

**Comment by jambirk** [comment]
@r-milne, could you please contact me at my Microsoft Alias? Sounds like these issues should all be dealt with in one go, preferably with @davgroom and @sohailta involved.

**Comment by lindspea** [comment]
@AndreaBarr @yogkumgit this issue can be closed.
