### ISSUE TITLE
More install parameters for Teams MSI please

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1439]
We want to keep Teams from starting up on boot by default.

I thought OPTIONS="noAutoStart=true" would solve this, but this is only for disabling auto start after install success.

* Do you have more install parameters for the Teams MSI installer?
* Where are install parameters documented? If nowhere, please add documentation
* Please don't install teams silently (teams_installer.exe) when using common parameters for getting help. Like "/?", "-?", "--?", "/h", "-h", "--h", "/help", "-help", "--help". I used the /? in hope of getting help regarding install switches, teams_installer.exe ended up overwriting my previous installation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Microsoft Teams using MSI](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment#disable-auto-launch-for-the-msi-installer)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @Lester-Hewett
* Microsoft Alias: **lehewe**

**Comment by pchatham** [comment]
I second this. More OPTIONS would be great.
"openAsHidden=true"

**Comment by hack-o-holic** [comment]
Yes parameters for all four options in the APPLICATION area of settings are needed!
Auto-Start
Open in background
On Close, leave running
Register Teams as default chat app

**Comment by msiriski** [comment]
Absolutely. We are holding off the roll out because we aren't able to control the behavior in every scenario.

**Comment by papan0x** [comment]
Something that would prevent the desktop icon would be appreciated.  Also a way to add this to my startlayout.xml.  It seems the application installs as the profile is being built so it gets skipped.

**Comment by PhilFancy** [comment]
Would support this as well! Would like to deploy and have Teams start hidden.

**Comment by scanum** [comment]
@o-l-a-v - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

Also, I know the product teams are always looking for user feedback and how to make Skype for Business better . They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://www.skypefeedback.com/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by scanum** [comment]
@officedocsbot close

**Comment by gstoneNYC** [comment]
did anyone actually get an answer besides "open a ticket"?

**Comment by msiriski** [comment]
> did anyone actually get an answer besides "open a ticket"?

This is absurd. My TAM tells me to submit an issue on support.microsoft.com, I find the existing issue multiple customers are posting about and then some random person references a completely different product and closes the issue. Good job Microsoft!

**Comment by gstoneNYC** [comment]
I actually opened a ticket, the person that initially called me sent me 3 articles for deploying Teams... the same 3 KB's I've already seen.... Now they are going back to their team to look into it further

#QualitySupport

**Comment by msiriski** [comment]
> I actually opened a ticket, the person that initially called me sent me 3 articles for deploying Teams... the same 3 KB's I've already seen.... Now they are going back to their team to look into it further
> 
> #QualitySupport

good man! if you don't mind, **please** keep us peasants informed if you get an actual response.

**Comment by gstoneNYC** [comment]
> 
> 
> > I actually opened a ticket, the person that initially called me sent me 3 articles for deploying Teams... the same 3 KB's I've already seen.... Now they are going back to their team to look into it further
> > #QualitySupport
> 
> good man! if you don't mind, **please** keep us peasants informed if you get an actual response.

support keeps getting better, they called back saying the options I gave them as examples were  per user settings, but not an actual answer of the available options. They are going back to their people to try again...

**Comment by gstoneNYC** [comment]
so after a good amount of run around by Microsoft.... Back at square 1! It was a nice circle they dragged me around in....  There's no answers, just another closed support ticket stating to open a new ticket.

**Comment by msiriski** [comment]
> so after a good amount of run around by Microsoft.... Back at square 1! It was a nice circle they dragged me around in.... There's no answers, just another closed support ticket stating to open a new ticket.

That's fantastic, classic Microsoft. I'm at a loss with words here. They flat out do not care about user experience.

**Comment by SnickersJF** [comment]
Hi all,

maybe a bit late but I changed the settings via PS-script after the installation using the Teams_windows_x64.exe using silent installation. This can be easily deployed via e.g. SCCM.

The .json file C:\Users\%User%\AppData\Roaming\Microsoft\Teams\desktop-config.json contains all necessary user settings and will be created during installation process. 

After the installation just run a few PS command to import, modify and write back the .json back to file system. (Make sure not using Out-File to save the .json as it will add byte order marks to the json and teams won't accept the file any more and just override it.

Settings we changed:
- openAtLogin = $false
- runningOnClose = $false

In addition delete the following RegKey: HKCU:\Software\Microsoft\Windows\CurrentVersion\Run\com.squirrel.Teams.Teams which is also created during installation and is triggering the autostart.

If you need additional info or code snippets let me know.
