### ISSUE TITLE
Initiating conversations from Teams to Skype for business users?

### ISSUE THREAD

**Issue by cory-rkmi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1445]
Is it possible to initiate a conversation from within Teams (Teams Only) to someone who is Skype for Business only?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d53d0cb0-90a6-5932-f78e-7de6fcc4d481
* Version Independent ID: 3d468027-cc37-5199-32ec-819bf62b2caa
* Content: [Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability)
* Content Source: [Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md)
* Service: **msteams**
* GitHub Login: @lsOmi
* Microsoft Alias: **lsomi**

**Comment by nduijvelshoff** [comment]
Same question here. :D

**Comment by ljr55555** [comment]
I had assumed so based on "Skype for Business users can chat one-on-one with Teams users, _**and vice versa**_" (emphasis mine). Creating a test account configured with Skype Only, it was my experience as well -- I could initiate a conversation from Teams to this Skype Only account & the message was delivered in Skype. The subsequent three accounts we set to Skype Only, though, worked as if they were in Island Mode. As of today, I am able to initiate conversations with all of my Skype Only accounts from Teams (both Teams Only & Island Mode users). I'm curious if others saw the Skype Only functionality change recently as well.

**Comment by pezlin** [comment]
I currently experience problems with chats initiated in Teams (by user in TeamsOnly mode) sent to Skype for Business (user in SkypeForBusinessOnly mode and without Teams license) not getting a message. Instead an email is sent to the receiver (a few minutes later) that a message was sent to Teams suggesting to launch Teams. Our org-wide setting is currently Island mode.

**Comment by RapotOR** [comment]
Same issue. Our default organization configuration is Islands (automatically setup). I assigned the SkypeOnly mode to few users to initiate some tests from my TeamsOnly account. From the documentation, all messages should be routed to Skype but that's not the case. If I try to initiate a chat (from the search bar) with the SkypeOnly users, it opens the full-featured teams chat for all of them except one! Also, if i try to add a chat (originally initiated by the SkypeOnly user) to favorites, it adds the Teams chat to favorites; only the pinned chat works.

**Comment by blgadmin** [comment]
I am having the same issue. I have switched my account to teams only and when a user sends a message from Skype is starts a thread correctly and I can respond but I cannot start a new thread to a new person using S4B from teams. Need this to work so we can have the option for more testing.

**Comment by tsaxfo** [comment]
Need to be able with Teams only to contact S4b-users and also skype consumer users

**Comment by scanum** [comment]
@cory-rkmi - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by RapotOR** [comment]
After clearing the cache, it solved the issues on my side. It looks like Teams doesnt understand the correct routing after any mode change.
https://blog.valeconsulting.co.uk/2018/09/28/clear-the-microsoft-teams-client-cache/
