### ISSUE TITLE
We need more use-case-based instructions

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1448]
Hello,
Up front, docs.microsoft.com is the best documentation offering I've ever seen. Thank you. I would like to suggest Use-case-based instructions for this particular doc.
Rationale: 
- I don't know what the ramifications are for allowing "Members can invite" in my Azure AD
- I don't know if I need to configure O365 Groups

If there were use cases such as...
1. Invite External users to join a Microsoft Team
2. Invite External users to create, edit, delete files from a Sharepoint Online site
3. Etc.
... it would ensure that the more unexperienced people (EVERYONE entering the Microsoft Suite via the PowerPlatform, aka "Citizen Developers") do not expose themselves to security issues. 
As Microsoft opens its Enterprise suite up to non-traditional users and "sudden admins", this will become more and more of an issue.
Thanks for your consideration,
SeaDude

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams Guest Access checklist](https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @somakbhattacharyya
* Microsoft Alias: **sbhatta**

**Comment by get-itips** [comment]
Hi @SeaDude Thanks for your feedback, and comments, we really appreciate them.

Article has been improved after you created this issue, I hope the new information fullfills your needs.

Thank you!

**Comment by scanum** [comment]
@officedocsbot close
