### ISSUE TITLE
Connect to the doc

### ISSUE THREAD

**Issue by cvanoosbree** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1449]
Hi All, unsure if this is SRSv2 related, but thought I would ask here.

Win10 E  v1809
OS: 17763.292
Doc: Logitech SmartDock

we get as far as the UI advising is to plug into the doc and press next (which I believe is the final step) however, "next" is never enabled .. its always faded (unable to be pressed). We can see the 2nd screen on the TV (this lets us know the HDMI cables work on the Doc.. but we are stuck

Has anyone ever seen this issue?

**Comment by scanum** [comment]
@cvanoosbree - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
