### ISSUE TITLE
Call Queue and Auto attendant licensing

### ISSUE THREAD

**Issue by nicolasbroisin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1452]
Hello,
I'm a little bit confused about this recommendation : 
"Your organization must have (at a minimum) an Enterprise E3 plus Skype for Business Cloud PBX license or an Enterprise E5 license. "

What I saw, Auto Attendant and Call Queue are both features available in the Skype admin center only with E1 + Phone system licenses. This part of the documentation brings some confusions. Is it Something possible to correct the recommentation to minimum Enterprise E1 rather than "at minimum" E3 ?
Thank you.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 40ed9cf1-93cc-698a-a974-44584c2ad448
* Version Independent ID: 10b1f715-8c08-7943-2bbf-699e1a59b358
* Content: [Que sont les standards automatiques de système téléphonique ?](https://docs.microsoft.com/fr-fr/microsoftteams/what-are-phone-system-auto-attendants?toc=/skypeforbusiness/toc.json&bc=/skypeforbusiness/breadcrumb/toc.json)
* Content Source: [Teams/what-are-phone-system-auto-attendants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.fr-FR/blob/live-sxs/Teams/what-are-phone-system-auto-attendants.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by jambirk** [comment]
@waseemhashem  can you comment on this question?

**Comment by waseemhashem** [comment]
@nicolasbroisin  the statement "Your organization must have (at a minimum) an Enterprise E3 plus Skype for Business Cloud PBX license or an Enterprise E5 license." is wrong, @jambirk and I replaced in the resource accounts doc with more details that you can borrow: 
https://docs.microsoft.com/en-us/MicrosoftTeams/manage-resource-accounts

If you plan to assign a Direct Routing number, you need to acquire and assign the following licenses to your resource accounts (Office 365 Enterprise E1, E3 or E5, with the Phone System add-on).
If you are assigning a Microsoft service number instead, you need to acquire and assign the following licenses to your resource account (Office 365 Enterprise E1, E3 or E5, with the Phone System add-on and a Calling Plan).

**Comment by tonysmit** [comment]
@waseemhashem and @jambirk 

If you are going to assign a Direct Routing phone number to a resource account, you must assign an E1/E3 license with a Phone System license or an E5 license to that resource account.

If you are going to assign a service phone number (toll) for Audio Conferencing to a resource account, you must assign an E1/E3 license with a Phone System license or an E5 license and a domestic or domestic and international Calling Plan to that resource account.

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@nicolasbroisin  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by eschrader** [comment]
You need Skype from what I can tell, so just the Common Phone or F1 wont work. I had to throw an E3 at my user account before I could configure it for Voice in the old Legacy Skype Portal.
