### ISSUE TITLE
Broken Link in Understand the Journey from Skype for Business to Teams

### ISSUE THREAD

**Issue by J-a-k-o-b** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1453]
In the part "Understand the Journey from Skype for Business to Teams" https://docs.microsoft.com/en-us/MicrosoftTeams/tutorial-journey-skypeforbusiness-to-teams?tutorial-step=1 the link to the sway presentation is broken: https://aka.ms/upgradeabstract is not valid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7163e6d-66a6-da7e-ea25-4c8bed58f3fd
* Version Independent ID: d3d57584-d218-7ef2-996c-93a26f3a0f76
* Content: [Upgrade from Skype for Business to Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/tutorial-journey-skypeforbusiness-to-teams?tutorial-step=9)
* Content Source: [Teams/Tutorial-Journey-SkypeforBusiness-to-Teams.yml](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/blob/live/Teams/Tutorial-Journey-SkypeforBusiness-to-Teams.yml)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **tbinder**

**Comment by nenonix** [comment]
@J-a-k-o-b  Thank you for pointing this out, we really appreciate feedback that improves Microsoft Docs.  We will look into it and fix the link.

**Comment by nenonix** [comment]
@yogkumgit @J-a-k-o-b the sway link has been fixed
