### ISSUE TITLE
Management only with Teams GUI

### ISSUE THREAD

**Issue by jeffbrushie** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1455]
To be able to manage devices in this portal user must login by Teams GUI (AudioCodes C450)? If user is logged in by SfB GUI the device will not be listed correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a627b5d-3edc-1add-b921-1dcd49c38653
* Version Independent ID: a2e2bd3a-31c0-471a-05fb-fd64bd942c4a
* Content: [Manage your devices in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/device-management#what-devices-can-you-manage)
* Content Source: [Teams/device-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/device-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by jamesrhea** [comment]
@jeffbrushie, thanks for the question. The device management mentioned in this article occurs via the Microsoft Teams & Skype for Business Admin Center, which is neither the SfB GUI nor the Teams GUI. You can read more about the Microsoft Teams & Skype for Business Admin Center in this article: https://docs.microsoft.com/en-us/microsoftteams/manage-teams-skypeforbusiness-admin-center

Does this help?

**Comment by yogkumgit** [comment]
@jamesr Thank you very much for the contribution and sharing this explanation. @jeffbrushie 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
