### ISSUE TITLE
DNS disaster recovery table

### ISSUE THREAD

**Issue by rimroot** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1456]
I think that DNS disaster recovery table is incorrect. In "CNAME records" column, record should point to GeoDNS record, i.e Meet.contoso.com to Meet-int.geolb.contoso.com for internal, or Meet.contoso.com to Meet-ext.geolb.contoso.com for external. 

The folowing article says that as well https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/network-requirements/simple-urls#disaster-recovery-option-for-simple-urls

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b18631a6-4392-e820-ab6e-07660097a5f2
* Version Independent ID: b484ef53-75ab-9b4c-f663-41446e9c8b68
* Content: [Advanced Edge Server DNS planning for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/edge-server-deployments/advanced-edge-server-dns)
* Content Source: [Skype/SfbServer/plan-your-deployment/edge-server-deployments/advanced-edge-server-dns.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/edge-server-deployments/advanced-edge-server-dns.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by lindspea** [comment]
@rimroot.  Thank you for pointing this out and for your valuable contribution in helping improve MS docs.  I will investigate further and will implement changes as soon as possible.

**Comment by BrianMcNeese** [comment]
Hi Lindsay, that sounds correct to me. And the Pool2 FQDN's could be removed out from under CNAME records as well.

**Comment by kenwith** [comment]
@lindspea - Brian is a expert engineer in this area so he can sign off for us. Go ahead and make update and submit PR and let me know and I will merge it. Thanks all! CC @yogkumgit

**Comment by lindspea** [comment]
Ok done.
[image: Picture]

**Comment by kenwith** [comment]
Merged, @BrianMcNeese  and @rimroot let @lindspea know if any other updates. Thanks for the feedback and making the docs better!  @yogkumgit - I am going to go ahead and close this one out. Let me know if I should re-open since you are coordinator on this repo.

**Comment by rimroot** [comment]
Hi all,
Thanks for the update. Actually the same change applies for all services - Dialin, Lyncdiscoverinternal, Lyncdiscover and Scheduler. All of them are running on the same servers under the same load balancer.

**Comment by lindspea** [comment]
Ok thank you.  I will amend the others as well.

[image: Picture]

**Comment by lindspea** [comment]
Done
[image: Picture]

**Comment by yogkumgit** [comment]
@kenwith  fresh feedback is received and new  PR is created, please merge it.

**Comment by kenwith** [comment]
Merged.
