### ISSUE TITLE
Spelling corrections:

### ISSUE THREAD

**Issue by chinster01** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1458]
Cumulative and business is also spelled incorrectly. Also it's on-premises.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caf24a35-ba53-0dff-962a-cf08a1cbcb31
* Version Independent ID: 5f40982a-e006-0b12-1b48-c5a3e04375cd
* Content: [Migrate Lync Room System devices to Skype Room System version 2](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/lrs-migration)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/lrs-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/lrs-migration.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Hi @chinster01, thanks for catching those. I've made the corrections and the updated article should be visible later today.
