### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by StPhil** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1459]
This has not been updated since the release of Teams Admin roles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81440b2f-391b-5856-a216-15866f37082a
* Version Independent ID: cdd15cd4-d4ed-c413-e2b9-ebf6dad8b33b
* Content: [Use activity reports for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-activity-reports#feedback)
* Content Source: [Teams/teams-activity-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-activity-reports.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by jambirk** [comment]
We have a plan to update this article in February, great timing!

**Comment by scanum** [comment]
@jambirk Hi James, any updates on this issue? Thanks!

**Comment by jambirk** [comment]
@LanaChin last updated this article on Feb 11.  I think we can close this, and if @StPhil disagrees we would need to know with a lot of specifics what else needs to be updated.

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@StPhil Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
