### ISSUE TITLE
Cant enroll phone if android policy requires encryption

### ISSUE THREAD

**Issue by tpmeredith** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1460]
It is impossible to enroll T58 or T56 phones if you have active intune policies requiring encryption on android devices. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5e07e81-0eca-e34c-7997-28b7cb1c86fa
* Version Independent ID: 371c473a-16a1-c6e0-d7da-0fa03ece0786
* Content: [Buying and deploying Microsoft Teams IP phones](https://docs.microsoft.com/en-us/microsoftteams/buying-and-deploying-teams-ip-phones)
* Content Source: [Teams/buying-and-deploying-teams-ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/buying-and-deploying-teams-ip-phones.md)
* Service: **skype-for-business**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
@tpmeredith This article is about to be removed in favor of another article. Can you suggest another article where mentioning that would be approriate?

**Comment by jambirk** [comment]
Appreciate the technical point, but we're removing this article. Closing the issue.
