### ISSUE TITLE
Get Attached Devices - Missing Logitech MeetUp

### ISSUE THREAD

**Issue by rogersau** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1461]
The get attached devices script seem to miss the Logitech MeetUp Camera. As in device manager this is under the PNPClass of "Camera" rather than "Image"

Suggest updating to; 
gwmi -Class Win32_PnPEntity | where {$_.PNPClass -eq "Image" -or $_.PNPClass -eq "Camera"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68cba21-b43e-ed44-449c-da752f5a0f53
* Version Independent ID: 5a2a2c5e-ad0e-833d-6ab7-74ed26f63d4a
* Content: [Skype Room Systems v2 maintenance and operations](https://docs.microsoft.com/en-us/skypeforbusiness/manage/skype-room-systems-v2/room-systems-v2-operations)
* Content Source: [Skype/SfbServer/manage/skype-room-systems-v2/room-systems-v2-operations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/skype-room-systems-v2/room-systems-v2-operations.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by lindspea** [comment]
@rogersau Thank you for pointing this out and helping improve MS Docs. I have updated the wording as per your suggestion.

**Comment by jambirk** [comment]
We've checked with the product group, and this change to the commands is inadvisable. We'll leave this as it's currently written.
