### ISSUE TITLE
Will you be working with Cisco UC Phone System?

### ISSUE THREAD

**Issue by vigitalmoe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1462]
WOrk for a company that is looking to implement MS Teams and just implemented Cisco UC.  Will there be integration at some point considering Cisco and Lync were integrated.   Curious, can't find any information on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1a1c01-10a9-7f69-1c7b-1a566b0f5112
* Version Independent ID: 329ee759-40fc-98fb-b91e-87786c63024b
* Content: [List of Session Border Controllers certified for Direct Routing](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-border-controllers)
* Content Source: [Teams/direct-routing-border-controllers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-border-controllers.md)
* Service: **msteams**
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by NMuravlyannikov** [comment]
Hi you can integrate with Cisco CUCM using one of the supported SBCs now.

**Comment by yogkumgit** [comment]
@NMuravlyannikov  Thank you very much for the contribution and sharing this explanation. @vigitalmoe Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
