### ISSUE TITLE
The documentation is wrong on AAD dependency on Guest Access for IT Admins only

### ISSUE THREAD

**Issue by AlexHill90** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1467]
Hi, the documentations states that: 

"Members can invite: Yes means that non-admin members of your directory can invite guests to collaborate on resources secured by your Azure AD, such as SharePoint sites or Azure resources. No means that only admins can invite guests to your directory."

I also realized that it states that the AAD "Members can Invite" needs to be setup to Yes for correct usage, so how does this stop the normal user to invite guests? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b05e642-c4e5-f1b5-5315-d3ef1690a0cd
* Version Independent ID: 01b7e0b5-3e50-3de0-e3e9-aeeeda43da12
* Content: [Authorize guest access in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-dependencies)
* Content Source: [Teams/Teams-dependencies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-dependencies.md)
* Service: **msteams**
* GitHub Login: @somakbhattacharyya
* Microsoft Alias: **sbhatta**

**Comment by AlexHill90** [comment]
Hi, I realized I was incorrect, although the documentation is rather unclear on this.

I was able to achieve the scenario in which only admins can add by disabling both O365 Groups guests can invite and the AAD setting for "Members can Invite". I don't understand why it says this latter field has to be set to "Yes" since I was able to redeem correctly the invitation from the guest side.. 

With this I was able to correctly restrict only to user management admins and global administrators the possibility to invite guests in Teams.

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @AlexHill90 

Thanks for reaching out!

"Members can invite" : This means you’ve enabled AzureAD B2B accounts and allowed all the members of your tenant to invite a B2B guest through the Azure Access Panel (myapps.microsoft.com). While AzureAD is the fundamental core of identity for Office 365, it’s also the place where you can publish your own SSO applications. This ‘Members can invite’ permission means that if you delegated ownership of one of your AzureAD published applications, or the membership of an AzureAD group to a user, they can now invite external B2B guests to that group.

Before you changed this setting that permission was only available to your admins, or to users you specifically granted the ‘guest inviter’ role.

Hope this information helps you. Kindly confirm. Thank you.

**Comment by AlexHill90** [comment]
Guest inviter role doesn't work for Teams yet, so I don't know what is this referencing.

**Comment by sowjanya365** [comment]
Hi @AlexHill90 

Yes, it has been mentioned on the doc with a "Note". It says - Currently, Teams doesn't support the guest inviter role. at a minimum the Members can invite toggle must be set to Yes for guest access to work in Teams.

Thank you.

**Comment by scanum** [comment]
@AlexHill90 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
