### ISSUE TITLE
Broken Link 

### ISSUE THREAD

**Issue by slate1cronos** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1472]
The "Browse all devices Certified for Teams." link is broken.

Is there an updated list?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcc58c9c-b20c-0515-55e6-165f23a66dbf
* Version Independent ID: e76e89bc-2e4b-af6f-5518-84435bca70ea
* Content: [Phones and Devices for Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/certification/devices-ip-phones?toc=/MicrosoftTeams/toc.json&bc=/microsoftteams/breadcrumb/toc.json)
* Content Source: [Skype/SfbPartnerCertification/certification/devices-ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbPartnerCertification/certification/devices-ip-phones.md)
* Service: **skype-for-business**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
The one at the bottom of the page? I just tried it and it worked.

**Comment by jambirk** [comment]
Closing this as fixed.
