### ISSUE TITLE
CQD 2019 Support with Skype for Business Server 2015

### ISSUE THREAD

**Issue by ThomasBIDAULT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1476]
Could you confirm that CQD 2019 is supported with Skype for Business server 2015 deployment ?

Thanks

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: f91216e8-0b6c-88b1-635a-401529556f78
* Version Independent ID: 0b0e068d-b870-bbd2-550d-07917ec63926
* Content: [Planifier pour le tableau de bord qualité appel Skype pour Business Server](https://docs.microsoft.com/fr-fr/skypeforbusiness/management-tools/call-quality-dashboard/plan#feedback)
* Content Source: [Skype/SfbServer/management-tools/call-quality-dashboard/plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.fr-FR/blob/live-sxs/Skype/SfbServer/management-tools/call-quality-dashboard/plan.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@rito2k  Thank you very much for the contribution and sharing this explanation. @ThomasBIDAULT 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
