### ISSUE TITLE
Behavior described in Pre-Existing Threads doesn't match user's experience

### ISSUE THREAD

**Issue by mschultz-bcbsne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1477]
The note in the "Chats and calls from pre-existing threads" section indicates that an existing thread between a Teams user (User A) and a Skype for Business user (User B) will become disabled once User B is upgraded to Teams because the interop no longer has a path to deliver the conversation to SfB.

In our experience, though, the old interop thread remains available and active.  Further, in most cases the Teams client even seems to prefer it over a Teams-to-Teams thread between the same user.  For example, if User A has two threads with User B (one interop thread from before User B switched to Teams only, and one native thread), when User A searches for User B, the Teams client opens the interop thread, not the newer one.  In many cases it also displays a message above the compose box in the native Teams thread indicating that "User B has switched to Skype for Business" and shows a link directing the user to "Start a new chat," which takes the user to the interop thread.

This is extremely confusing to the users.  We have opened a case with Support to identify if this is a bug, or if the functionality described here is not yet enabled.  Can you confirm if the behavior described here should be live for all tenants?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169a20a6-ebf7-1093-3cb1-fb438b9b7e13
* Version Independent ID: b2074fd8-724e-75fa-bafb-a0f7966bf593
* Content: [Coexistence with Skype for Business](https://docs.microsoft.com/en-us/microsoftteams/coexistence-chat-calls-presence#chats-and-calls-from-pre-existing-threads)
* Content Source: [Teams/coexistence-chat-calls-presence.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/coexistence-chat-calls-presence.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **francoid**

**Comment by StuBeck32** [comment]
We're currently having the same problem. Unfortunately we've had other issues with documentation here, and it seems like the documentation written is how they want it to work, not actually how it is working.

**Comment by FrancoiD** [comment]
Thank you for reporting.
The behavior described is accurate and in production. There is no issue with the documentation.
You must be hitting an issue where policies recently changed for a user take a long time to be followed by the client. We are actively working to improve that.
In the interim, you can ask your support person to open an ICM and request urgent whitelisting for the fix.

**Comment by StuBeck32** [comment]
What’s icm? 

Also if this is expected there needs to be documentation stating what is expected. We are having it happen for more than 24 hours after switching to teams and a ticket I opened 20 hours ago has gone ignored by Microsoft support.

**Comment by mschultz-bcbsne** [comment]
@FrancoiD We have this same problem and are waiting for a response from support on getting “whitelisted” for the fix. Even with this fix, it’s my understanding from the support engineer that it can still take up to 24 hours for the change to fully take effect. That’s nowhere in the docs and needs to be clearly called out, in my opinion. He also didn’t mention that it would block the interop threads from working, as the docs indicate will happen. Is that still an accurate desicription of how the service works?

It’s been frustrating that many Teams docs seem to describe a to-be state for the service, not an as-is. I understand changes & features may roll out in waves, but the docs need to indicate something like “this behavior is currently rolling out with an expected completion of March 2019” or whatever is appropriate. Without it, as a customer I have to assume the docs describe how the product actually works, which more frequently seems like it’s not the case.

@StuBeck32 It took almost 2 weeks for our ticket to be assigned and worked, and that was only after several times engaging our TAM for escalation. Not sure what’s going on there, but if you have a TAM, definitely ask them for assistance.

**Comment by FrancoiD** [comment]
@mschultz-bcbsne : the reason why the policy aspect is relevant here is that the client will disable the thread and offer a new thread once it knows that the recipient policy has changed. As long as it does not know of the policy change, the client can't do that.
The docs do describe the behavior once the policy is set. The behavior is not rolling out, it is implemented as such, as soon as the client has the policy.
Here we are facing a short term issue of policy latency. We are working hard to resolve that issue. Once it is resolved, you will observe the behavior as described on a consistent basis.
Until we have completed roll out of the policy latency fix, affected customers should indeed work with support and raise an ICM (that's a specific type of incident management process) which will enable us to whitelist them for the fix. Again, that's not a change in the behavior as described, only ensures the policy lands without the latency.

**Comment by StuBeck32** [comment]
If it’s relevant please document it. Thanks.

**Comment by FrancoiD** [comment]
Hi Stu, what I am saying above is that it's only relevant in the context of the temporary policy latency we are experiencing, not as a matter of the ongoing principle that this documentation is providing (as are other documentations on other behavior also potentially affected by policy latency). If anything, it's not here that policy latency issues should be documented. Let me explore whether we have a mechanism to expose that issue and its resolution. Thank you

**Comment by StuBeck32** [comment]
Thanks. It’s clear we won’t agree about what should be stated way. 

There needs to be a central means of showing this is an issue though. It’s likely out of context for here, but this should be on the office 365 portal as an advisory for example or as a notice when making changes. It could also be in the updated documentation for switching to teams as an issue which needs to be known.

**Comment by FrancoiD** [comment]
We agree on a central means, let me discuss that internally.

**Comment by StuBeck32** [comment]
Just as a followup, we're still having this issue 16 days later. The users have been switched over and this can't be the latency issue as the changes needed are never taking effect.

**Comment by FrancoiD** [comment]
@Stubeck32 do you still see the issue?

**Comment by StuBeck32** [comment]
Yep. Support gave up on trying to help

**Comment by mcbainsr** [comment]
@StuBeck32  - have you tried asking your users to log out and back in?  In extreme cases we also asked them to clear their local cache in Teams by deleting these folders 

%appdata%\Microsoft\teams\application cache\cache
%appdata%\Microsoft\teams\blob_storage
%appdata%\Microsoft\teams\Cache
%appdata%\Microsoft\teams\databases
%appdata%\Microsoft\teams\GPUcache
%appdata%\Microsoft\teams\IndexedDB
%appdata%\Microsoft\teams\Local Storage
%appdata%\Microsoft\teams\tmp

**Comment by StuBeck32** [comment]
Yep, gone through all of that multiple times. My hunch is its caused by the switch over from SFB to Teams as the default, as we can no longer set users to "Org Wide settings" as it produces an error. We had no problems with this with moving two users over last year, but now that its "ready" we're having a lot more issues. 

I was planning to have everyone switched over to Teams by now, but rather than doing this as a stepped approach, since SFB to Teams and back communication isn't supported, I'm going to have to switch everyone all at once. Its going to be a bit of a training nightmare.

**Comment by scanum** [comment]
@jambirk Hi James, any updates on this issues? Thanks!

**Comment by jambirk** [comment]
@FrancoiD  please advise on what action to take, or whether to close thi issue.

**Comment by scanum** [comment]
@FrancoiD Hi, any updates on this issue?

**Comment by Jetski5822** [comment]
I hit this every day.... any update?

**Comment by StuBeck32** [comment]
There won’t be an update. It’s a known issue but with the impending forced switch to Teams it’s not something they will fix.

**Comment by scanum** [comment]
@mschultz-bcbsne, @StuBeck32 @Jetski5822  - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make Skype for Business better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice  https://www.skypefeedback.com​​​​​​​.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by scanum** [comment]
@officedocsbot close
