### ISSUE TITLE
Proxy - Step 4

### ISSUE THREAD

**Issue by brcallicott** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1478]
This step seems to be missing some steps.  Clicking on the HKEY_USER doesn't prompt you for a new key name.  Seems to be a step missing between these two points.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07f79b5a-ff7d-aa85-f909-d8a0e87be892
* Version Independent ID: 4fc74222-3f6d-925e-182a-db2c3b4ca246
* Content: [Prepare your Environment](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/srs-v2-prep)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/srs-v2-prep.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/srs-v2-prep.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by get-itips** [comment]
Thanks @brcallicott for your feedback, we will correct the article as needed.

**Comment by scanum** [comment]
@officedocsbot close
