### ISSUE TITLE
Alll the URL in the link below point to the same URL. Doesn't seem to make sense to have this page.

### ISSUE THREAD

**Issue by sritodi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1479]
[Enter feedback here]
Alll the URL in the link below point to the same URL. Doesn't seem to make sense to have this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eee287a9-c9d1-6275-53b7-57e6a3c4196d
* Version Independent ID: 48e7f5c9-7cac-4033-05b9-d82b7bf891fb
* Content: [The Skype for Business Online cmdlets](https://docs.microsoft.com/en-us/lyncserver/the-skype-for-business-online-cmdlets#feedback)
* Content Source: [Lync/LyncServer/the-skype-for-business-online-cmdlets.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Lync/LyncServer/the-skype-for-business-online-cmdlets.md)
* GitHub Login: @dstrome2

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@sritodi Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
