### ISSUE TITLE
Request for consolidated matrix of configuration settings and policies

### ISSUE THREAD

**Issue by sklinger83** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1480]
This page covers many available features and what they do, but a matrix of settings and policies that is consolidated into a table would be very helpful for enterprises as they look to adopt Teams and rationalize configurations for their environment. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9b7f77-061d-a224-ff1c-8d3e15d21221
* Version Independent ID: 00fa9550-c4c4-3398-ffbb-271cc724048f
* Content: [Manage Microsoft Teams features in your Office 365 organization](https://docs.microsoft.com/en-us/MicrosoftTeams/enable-features-office-365)
* Content Source: [Teams/enable-features-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enable-features-office-365.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by sklinger83** [comment]
In addition - this list would not be recommended settings and policies, just what is available to be configured and what they do.

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hello @sklinger83 

Thank you for your suggestions and making the docs better. We really appreciate them.

We see there are two kind of setting listed on the document. One is "Tenant-wide settings" and the other one is "Teams org-wide settings". And respective contents or features are listed under these two categories. We feel that it looks good with the contents in the sequential order. 

Hope this information is helpful. Kindly confirm. Thank you.

**Comment by sklinger83** [comment]
Hi - representing my customer, I have to say that this is not what they were hoping to see.  I was able to get a list of links to them and they were able to move forward.  I think their feedback would be the same though that a table of all settings and a concise explanation is what they were hoping for.

**Comment by scanum** [comment]
@sklinger83 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
