### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by bcraigie** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1483]
I have turned on external access a month ago and just tried to add my personal skype, but it says "We are unable to set up the conversation because the contact you entered wasn't found".  So, the documentation needs to be clearer.  If you can't use teams to communicate with personal skype users, you should make that clear (also make clear when it will become possible) and save us all wasting our time trying until it is ready.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Communicate with Teams users in another organization](https://docs.microsoft.com/en-US/MicrosoftTeams/let-your-teams-users-communicate-with-other-people?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/let-your-teams-users-communicate-with-other-people.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/let-your-teams-users-communicate-with-other-people.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @bcraigie 

Thanks for reaching out! 

Currently, there is no integration between public Skype (not Skype for Business) and Teams. There is a user voice created to implement this feature and it is under review now. Please refer to the below URL.

https://microsoftteams.uservoice.com/forums/555103-public/suggestions/16958347-skype-integration-consumer-federation

Hope this information helps. Kindly confirm. Thank you.

**Comment by scanum** [comment]
@bcraigie Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
