### ISSUE TITLE
Required Licenses section

### ISSUE THREAD

**Issue by Arcass** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1484]
Could this section be updated to include a break down of the licensing requirement rather than just linking out to other articles? As I understand it a Microsoft Phone system license and a calling plan or Common Area phone license are needed. So two/three bullet points would be great. 
It would make the article more complete and a better single point of information about getting Teams IP Phones up and running. 
Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5e07e81-0eca-e34c-7997-28b7cb1c86fa
* Version Independent ID: 371c473a-16a1-c6e0-d7da-0fa03ece0786
* Content: [Buying and deploying Microsoft Teams IP phones](https://docs.microsoft.com/en-us/microsoftteams/buying-and-deploying-teams-ip-phones)
* Content Source: [Teams/buying-and-deploying-teams-ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/buying-and-deploying-teams-ip-phones.md)
* Service: **skype-for-business**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
@LolaJacobsen : is this article being restructured in one of your efforts? Let's discuss offline.

**Comment by lindspea** [comment]
@jambirk Hi James.  Just following up on this article as well.  Let me know if you would like me to do a PR for this one as well.

**Comment by jambirk** [comment]
Lola and I did discuss this before she left. This article is being removed from the content set in favor of  https://docs.microsoft.com/en-us/skypeforbusiness/certification/devices-ip-phones?toc=/MicrosoftTeams/toc.json&bc=/microsoftteams/breadcrumb/toc.json which is more actively maintained. Time to close this issue.
