### ISSUE TITLE
Federation only partially working

### ISSUE THREAD

**Issue by jackvinson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1487]
We are on Office365 (small company - using the Business account).  Our colleagues are still on Skype for Business in a large company.  They are already Office365 and are moving (slowly) to Teams.

We setup federation - External access is enabled on our side. And it seems it is enabled on their side.  From our organization, we can chat with them.  And they can reply to those chat messages.  But if they attempt to initiate a chat with us, it never comes through.  They get a message about the user being unavailable or offline.  I have set External Access as on for anyone - I haven't set a specific permission for the partner organziation. From what I've read, that shouldn't matter.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Communicate with Teams users in another organization](https://docs.microsoft.com/en-us/microsoftteams/let-your-teams-users-communicate-with-other-people)
* Content Source: [Teams/let-your-teams-users-communicate-with-other-people.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/let-your-teams-users-communicate-with-other-people.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by LennyDayberry** [comment]
Is there a status on this post?

**Comment by lindspea** [comment]
@jackvinson. Thank you for pointing this out.  I'm investigating further and will update you as soon as I have some feedback. Thanks for your contribution in helping improve MS docs.

**Comment by AndreaBarr** [comment]
I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by jackvinson** [comment]
FYI.  Heard back from the helpful support team on Office365.  This is a known issue between organizations already on Teams and those still in Skype for Business.  

Quote from support desk:
> As per consulting this is a known issue under the communication platform of Microsoft Teams and Skype for Business. Microsoft are encouraging as users will soon be forced to shift to the Teams services. as the Skype for Business will be decommissioned soon.
> 
> For your reference this would be a official road map of Microsoft to transition to Teams:
> 
> https://skypeandteams.blob.core.windows.net/artefacts/Skype%20for%20Business%20to%20Teams%20Capabilities%20Roadmap.pdf 
> 
> Rest assured that the back end Engineers are working on this known issue but as of the moment there's no estimated time of completion. Sincerely I apologize for the inconvenience and thank you so much for your patience!  
>
