### ISSUE TITLE
Dead link "devices Certified for Teams"

### ISSUE THREAD

**Issue by 3k09** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1492]
The Browse all devices Certified for Teams (http://products.office.com/microsoft-teams/across-devices/devices) does not work. It's pointing to https://products.office.com/de-de/microsoft-teams/across-devices/devices?rtc=1 and results in a 404 not found.

You might change the link to point to https://docs.microsoft.com/en-us/MicrosoftTeams/buying-and-deploying-teams-ip-phones

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcc58c9c-b20c-0515-55e6-165f23a66dbf
* Version Independent ID: e76e89bc-2e4b-af6f-5518-84435bca70ea
* Content: [Phones and Devices for Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/certification/devices-ip-phones?toc=/MicrosoftTeams/toc.json&bc=/microsoftteams/breadcrumb/toc.json)
* Content Source: [Skype/SfbPartnerCertification/certification/devices-ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbPartnerCertification/certification/devices-ip-phones.md)
* Service: **skype-for-business**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
@dougand-MSFT Would this be your preferred target for this link? 

@samanthaw adding as this may be a loc issue

**Comment by jambirk** [comment]
@3k09 

The link works for me, but I notice you're being redirected to a german Loc version of the site, which may not exist. Looking into that.

The alternate link you suggest is to an article that's being removed from the content set.

**Comment by samanthaw** [comment]
@3k09 we're working on this issue

**Comment by 3k09** [comment]
@jambirk & @samanthaw Thanks. 
Yes, by default I'm on the DE-DE pages. I'd now suggest to point from the de-de source page to en-us page https://products.office.com/en-us/microsoft-teams/across-devices/devices this one seems to work.

**Comment by jambirk** [comment]
@3k09 
Hard coding in the locale like that is definitely a last resort. I understand a more comprehensive localization solution is being worked on, but if it's going to take a long time I'll use your suggestion.
