### ISSUE TITLE
Skype for Business should be called Communicator in first sentence?

### ISSUE THREAD

**Issue by lordmafi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1493]
[...] then you should configure the personal contact store on any client computers running Skype for Business. [..]
Note that this is not required on computers running Skype for Business.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38c5f2da-bdca-d810-2b9e-995aabac63c6
* Version Independent ID: 66be603b-8e20-2499-86c1-e7dc430ac562
* Content: [Configure the personal contacts store on client computers for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/integrate-with-exchange-server/personal-contacts-store?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json)
* Content Source: [Skype/SfbServer/deploy/integrate-with-exchange-server/personal-contacts-store.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/integrate-with-exchange-server/personal-contacts-store.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by lindspea** [comment]
@lordmafi Thank you for pointing this out and for your valuable contribution in helping improve MS docs.  Just to get some clarification.  Should the words "Skype for Business" in your quoted sentence be replaced by the word "Communicator"?

@AndreaBarr @scanum please assign to me.

**Comment by lordmafi** [comment]
Hi Lindsay,
for me it was an eyecatcher that it stated "you should configure on any client running SfB" and in the next sentence "Not required on computers running SfB" 
After further investigation I think only Lync 2010 and older uses HKLM\[...]\Communicator
since Lync 2013 it is set through Policy (New-CsClientPolicyEntry -Name "PersonalContactStoreOverride" -Value "1")
So maybe this can be clarified or maybe I don't unterstand clearly the meaning of the passage.

BR Martin

**Comment by jambirk** [comment]
I suspect this passage got a bit mangled a few years ago when we were rebranding in anticipation of SFB server 2015. I'll have a look.

**Comment by jambirk** [comment]
Agree that this procedure is only applicable to legacy client users. it may be time to retire this article.

**Comment by jambirk** [comment]
Agreed this procedure only applies to client computers using the Lync 2010 client, which should be a tiny proportion at this point. @lindspea please ping me on teams around 10am.

**Comment by lindspea** [comment]
Thanks @jambirk.
