### ISSUE TITLE
Seems there is an error in "other considerations" 

### ISSUE THREAD

**Issue by stvollet** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1494]
In other considerations third bullet point "Currently, you can only invite people from within your company, as it is not yet possible for external users to join meetings." 
this seems to be an outdated statement, please correct. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Use the Microsoft Teams Meeting add-in in Outlook](https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by lindspea** [comment]
@stvollet Thank you for pointing this out.  Could I ask you what you would suggest to put in place thereof?

**Comment by stvollet** [comment]
I suggest to just remove that particular bullet point . Thank you

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yogkumgit** [comment]
@lindspea  Thank you very much for the contribution and updating the documentation with PR. @stvollet  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
