### ISSUE TITLE
Need to list Planner

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1500]
Planner isn't mentioned specifically, although OneNote is. Can we get a line for Planner? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7faee29-6d56-f3bf-766c-6deaefe92e34
* Version Independent ID: 6029b6f8-7d49-6474-fa40-2793000c74a4
* Content: [Plan for Microsoft 365 Government - GCC deployments - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/plan-for-government-gcc)
* Content Source: [Teams/plan-for-government-gcc.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-for-government-gcc.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lehewe**

**Comment by lindspea** [comment]
@npherson Thank you for pointing this out.  I will investigate further and have it added to the document.

**Comment by npherson** [comment]
Forms, too! :)

________________________________

**Comment by lindspea** [comment]
@npherson Hi Nash, please see my previous reply and let me know regarding planner and forms.

**Comment by mortenya** [comment]
I'm on GCC and Forms and Planner are not options for new tabs.

**Comment by lindspea** [comment]
@yogkumgit @AndreaBarr this can be closed thank you.

**Comment by yogkumgit** [comment]
@lindspea Thank you very much for the contribution and updating the documentation with PR. @nphersom Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
