### ISSUE TITLE
What about when Lync is deployed within an environment using Split DNS?

### ISSUE THREAD

**Issue by mtwelve** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1507]
Hello,

The article indicates that this should be a record added to external DNS only however the validation step 'Log on to a client computer in the domain' indicates that this should be resolvable by internal clients too.

What is the recommended way to configure DNS when Lync has been deployed in an environment with split DNS in place for the domain name used as SIP namespace?

Do we need to add an entry to the internal DNS too?

We are having issues with requests to the OVA number attached to the Exchange Online Dial Plan being dropped.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad55fc92-cee1-e92c-41dd-fed820fb96db
* Version Independent ID: 86ea683b-c913-a837-92e9-13f3a8d26818
* Content: [Create a DNS SRV record for integration with hosted Exchange UM](https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-create-a-dns-srv-record-for-integration-with-hosted-exchange-um)
* Content Source: [Lync/LyncServer/lync-server-2013-create-a-dns-srv-record-for-integration-with-hosted-exchange-um.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Lync/LyncServer/lync-server-2013-create-a-dns-srv-record-for-integration-with-hosted-exchange-um.md)
* GitHub Login: @dstrome2

**Comment by mtwelve** [comment]
......?

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@mtwelve Thank you for reaching out and helping improve MS Docs.  I'll have the team look into this and get back to you soonest.

**Comment by scanum** [comment]
@mtwelve thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
