### ISSUE TITLE
See Option 3

### ISSUE THREAD

**Issue by mitchelljb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1508]
(Optional) Follow the steps in [Create a dial plan](GET LINK AFTER MIGRATION) through step 11 or [Modify a dial plan](GET LINK AFTER MIGRATION) through step 10.

Missing some links here, guess after migrating the page to the current location the link isn't included yet! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e79d5d5-b66f-6d11-5644-47958a5c445e
* Version Independent ID: 8a7760c6-fe18-3530-f9dc-bd3e070b8ee6
* Content: [Defining normalization rules in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/manage/voice-routing/defining-normalization-rules#create-or-modify-a-normalization-rule-manually)
* Content Source: [Skype/SfbServer/manage/voice-routing/defining-normalization-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/voice-routing/defining-normalization-rules.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@mitchelljb Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
