### ISSUE TITLE
Images fuzzy and hard to read

### ISSUE THREAD

**Issue by gdfrick** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1511]
Could you provide links the authorization images?  They are fuzzy and hard to read.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b05e642-c4e5-f1b5-5315-d3ef1690a0cd
* Version Independent ID: 01b7e0b5-3e50-3de0-e3e9-aeeeda43da12
* Content: [Authorize guest access in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-dependencies)
* Content Source: [Teams/Teams-dependencies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-dependencies.md)
* Service: **msteams**
* GitHub Login: @somakbhattacharyya
* Microsoft Alias: **sbhatta**

**Comment by jambirk** [comment]
Just converted the diagrams from Powerpoint to Visio. @AndreaBarr  and @yogkumgit  please close this out by filing an art request, asking a designer to do minor cleanup

**Comment by jambirk** [comment]
@AndreaBarr I retract the last request. Let's leave the diagrams as they are now. Closing the issue.

@gdfrick Thanks for helping us to make the documentation better. The diagrams are updated and the updates are available in Visio format which can be easily resized without definition loss.
