### ISSUE TITLE
User coexistence mode changes are not taking effect.

### ISSUE THREAD

**Issue by jwittner** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1512]
We have changed several individual users from the org-wide setting ( S4B only ), to Islands, but all calls/messages for these users are still being routed through S4B. We have waited over 30 minutes now, and restarted Teams, closed S4B, and restarted the computers, all to no effect. Is there an undocumented step or time frame we're missing here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffbf0bfd-c15e-b10b-0cc9-6a27ac1e6634
* Version Independent ID: 58575371-9e09-fadb-76f6-7491df8580a3
* Content: [Setting your coexistence and upgrade settings](https://docs.microsoft.com/en-us/microsoftteams/setting-your-coexistence-and-upgrade-settings)
* Content Source: [Teams/setting-your-coexistence-and-upgrade-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/setting-your-coexistence-and-upgrade-settings.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by jwittner** [comment]
Coming back the next day and trying again the changes seem to have taken effect. I think you'd do well to document that these changes may take quite some time to propagate for users.

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by JoshuaLowery** [comment]
> 
> 
> Coming back the next day and trying again the changes seem to have taken effect. I think we'd do well to document that these changes may take quite some time to propagate for users.

I am running into the same.  Could do for an update in the article explaining anticipated propagation time.

**Comment by sowjanya365** [comment]
Hi @jwittner 

Thank you very much for posting this issue. We've not found anything documented related to this issue.
Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution/clarification. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by scanum** [comment]
@jwittner Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by jwittner** [comment]
A little confused here, do the changes take time to propagate or should they be instantaneous and @JoshuaLowery  and I are both seeing unexpected errors.

I wouldn't expect you to find any documentation in the issue as my issue was that there is no document in the propagation time...

**Comment by korbinianbartholdy** [comment]
Same problem here. Neither do I understand why it takes apparently a day (or a night?) for the changes to be effective, nor why this 'hidden knowledge', as MS Service doesn't seem to be able to confirm this.

**Comment by korbinianbartholdy** [comment]
@officedocsbot open
