### ISSUE TITLE
"ビジネス オンラインの Skype～" needs to be replaced with "Skype for Business Online～"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1513]
"ビジネス オンラインの Skype を施設内でのユーザーの移動" needs to be replaced with "ユーザーをオンプレミスから Skype for Business Online に移動する"

[ユーザーをオンプレミスから Skype for Business Online に移動する](https://docs.microsoft.com/ja-jp/skypeforbusiness/skype-for-business-hybrid-solutions/deploy-hybrid-connectivity/move-users-from-on-premises-to-skype-for-business-online)

https://docs.microsoft.com/ja-jp/microsoftteams/upgrade-to-teams-execute-skypeforbusinesshybridonprem

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8d9d75e7-638b-1738-e102-b87d95b5b51d
* Version Independent ID: d7a64df1-2d66-1ab2-9aa3-afab785bf69a
* Content: [Skype のビジネス ・ ハイブリッドまたは設置型の展開: マイクロソフトのチームからのチームへのアップグレードします。](https://docs.microsoft.com/ja-jp/microsoftteams/upgrade-to-teams-execute-skypeforbusinesshybridonprem)
* Content Source: [Teams/upgrade-to-Teams-execute-SkypeforBusinessHybridOnPrem.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.ja-JP/blob/live-sxs/Teams/upgrade-to-Teams-execute-SkypeforBusinessHybridOnPrem.md)
* Service: **msteams**
* GitHub Login: @arachmanGitHub
* Microsoft Alias: **arachman**

**Comment by OfficeGSX** [comment]
The article has been HumanTranslated and published live. Issue is fixed

Best Regards,
Michal

**Comment by hyoshioka0128** [comment]
@OfficeGSX Thanks.
