### ISSUE TITLE
Licensing Issue

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1514]
This part is wrong - it reference plan 3 (don't think that even is a thing)

In the Assign licenses section, you need to select Skype for Business Online (Plan 2) or Skype for Business Online (Plan 3), depending on your licensing and what you've decided in terms of needing Enterprise Voice. You'll have to use a Plan 3

It also does not align with the details here:
https://docs.microsoft.com/en-us/SkypeForBusiness/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/skype-room-systems-v2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41965bc8-45c0-e4eb-aa36-5ef5adbe460a
* Version Independent ID: 97de65ad-04fc-5b62-c7c7-fba8d0aeb1de
* Content: [Deploy Skype Room Systems v2 with Office 365](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/with-office-365)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/with-office-365.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@jambirk @sohailta Any updates on this issue? Thanks!

**Comment by jambirk** [comment]
@danmyhre is this page still an issue? we made a couple updates recently.

**Comment by jambirk** [comment]
@danmyhre We posted an update to this file recently, is it better now in your opinion?

**Comment by danmyhre** [comment]
There is a broken link to the teams licensing reference page in this section:
https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/with-office-365#requirements

Where it says:
See Microsoft Teams Rooms Licensing for details.

**Comment by danmyhre** [comment]
Also, this whole thing should probably get moved under Teams in docs instead of being under sfb

https://docs.microsoft.com/en-us/MicrosoftTeams/Microsoft-Teams

**Comment by jambirk** [comment]
@danmyhre  fixing the broken link will be quick, moving the files not so much. Still doable.

**Comment by lindspea** [comment]
@jambirk just following up on this issue. Is there anything that still needs to be done that I can help with?

**Comment by jambirk** [comment]
the files have been moved. go ahead and close.

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedosbot close
