### ISSUE TITLE
What to do when having multiple Skype pools

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1518]
Hi,
The document says:
"_To run this script, you must provide the URL for the Skype for Business Server authentication metadata document; this will typically be the fully qualified domain name of the **Skype for Business Server pool** followed by the suffix_"

But it gives no information what shall we do if we have multiple Skype pools deployed. Can we use the simple URLs for AuthMetadataUrl? When looking for what .ps1 does, it only take the public key from OAuth, so is there really point to have multiple times the same entry?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d458976f-b1c2-7a2d-a41a-f6219e65e691
* Version Independent ID: 7617f7d2-1e8d-99c4-82b8-ff84a7fe0818
* Content: [Configure partner applications in Skype for Business Server 2015 and Exchange Server](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/integrate-with-exchange-server/configure-partner-applications)
* Content Source: [Skype/SfbServer/deploy/integrate-with-exchange-server/configure-partner-applications.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/integrate-with-exchange-server/configure-partner-applications.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@Petri-X Thank you for helping improve MS Docs.  I'll have the team look into this soonest.

**Comment by lindspea** [comment]
@carolynblanding

**Comment by scanum** [comment]
@Petri-X We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
