### ISSUE TITLE
3P?

### ISSUE THREAD

**Issue by chinster01** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1520]
I assume 3P should be VTC?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 046dec87-2354-a9db-ae19-3bfaa2626bef
* Version Independent ID: 23e7d18f-bbab-75e1-7c85-9b0d0e8f4382
* Content: [Cloud Video Interop for Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/cloud-video-interop)
* Content Source: [Teams/cloud-video-interop.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-video-interop.md)
* Service: **msteams**
* GitHub Login: @lolaj
* Microsoft Alias: **lolaj**

**Comment by lindspea** [comment]
@joagonzalez thank you for sending that information. @chinster01 If there are no further questions I will be closing this issue.

**Comment by lindspea** [comment]
@AndreaBarr @yogkumgit this can be closed thank you.
