### ISSUE TITLE
Trial start date

### ISSUE THREAD

**Issue by kszicsillag** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1524]
As an org admin where can I see the date of the first activation (i.e. the start date of the trial)? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the Microsoft Teams Commercial Cloud Trial offer](https://docs.microsoft.com/en-us/microsoftteams/iw-trial-teams#manage-the-trial)
* Content Source: [Teams/iw-trial-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/iw-trial-teams.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @kszicsillag 

Thanks for reaching out!

To find the trail details, please navigate to O365 admin center -> Billing -> Subscriptions. 

Hope this information is helpful. Kindly confirm. Thank you.

**Comment by ThePangy** [comment]
@sowjanya365 - The Teams trial is not listed in our subscriptions. Is there somewhere to view the trial start date? I have a feeling we are getting close to it and we need to know when Teams will stop working for all the people who think they are licensed for it.

**Comment by kszicsillag** [comment]
We have an ongoing trial and it is not listed in the subscriptions for us either.

**Comment by scanum** [comment]
@kszicsillag  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
