### ISSUE TITLE
More phones

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1526]
More phones are listed here https://partnersolutions.skypeforbusiness.com/solutionscatalog/ip-phones

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcc58c9c-b20c-0515-55e6-165f23a66dbf
* Version Independent ID: e76e89bc-2e4b-af6f-5518-84435bca70ea
* Content: [Phones and Devices for Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/certification/devices-ip-phones)
* Content Source: [Skype/SfbPartnerCertification/certification/devices-ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbPartnerCertification/certification/devices-ip-phones.md)
* Service: **skype-for-business**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by lindspea** [comment]
@eschrader. Thank you for pointing this out Eric.  I will have the additional information added to the content as soon as possible.

**Comment by dianavank** [comment]
Solutions Catalog is being deprecated soon, please don't add link from docs.  We are gathering all the necessary information to update docs for SfB, anticipate to have all the updates done by 2/28.

**Comment by jambirk** [comment]
Thanks Diana. @eschrader thank you for the suggestion, but for the reasons mentioned we'll keep the page as-is.
