### ISSUE TITLE
Huge delay in syncing the users between Azure AD and Teams

### ISSUE THREAD

**Issue by advdberg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1538]
While this document states that it can take up to two hours for changes to be reflected in Teams, we see at a lot of tenants that it takes much more time to reflect the changes, sometimes even up to more than 12 hours. 

Is there a way to speed this up? Can we trigger this synchronisation somehow? Will it take longer if your tenant has an Active Directory sync? Does the amount of users within Azure Active directory have impact on the duraction of the sync?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d86301b-ce9c-388c-e563-9e5e5c27132e
* Version Independent ID: 07e4ae23-0966-e8f3-9b7c-4f6c02569eb0
* Content: [Office 365 Groups and Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/office-365-groups)
* Content Source: [Teams/Office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-groups.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by EagleAdam** [comment]
Agreed, I am seeing the same issue. Created a Microsoft Teams private team, it's now 48 hours later and still no Office365 group.

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @advdberg 

Thanks for reaching out!

Kindly open a support ticket with the Office 365 support team. Team will analyse this technical issue and propose a solution. Thank you.

**Comment by scanum** [comment]
@advdberg  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by advdberg** [comment]
@scanum and any other person who's interested: 
We've found out that when we provide the owners and members directly on creating the group (with New-PnPSite), then promoting it to a Team will have all users and owners directly inside the Team and they all can see the Team almost instantly. 

When first creating the New-PnPSite and afterwards adding owners and member to the Group via Graph api calls either before or after promoting the group to a Team, the delay appears.
