### ISSUE TITLE
edge server requirements

### ISSUE THREAD

**Issue by jdubyaeber** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1539]
"somebody" should review this document for edge server requirements.  The section "Software that should be installed before a Skype for Business Server 2019 deployment" implies that ALL SfB servers "...need the following."  This includes Edge server I presume.  If so, then I think recommending that IIS be installed to support http activation is in disagreement with running production edge servers Also, I do not think that asp.net 4.x is needed for an edge server, nor is WIF.  
EDIT 1347 20190204... 2019 Edge server on Server 2019 want .net 3.5 from \sources\sxs also.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd40e9bf-6fb5-b597-5494-b9ccc17e4660
* Version Independent ID: 46d0d0a0-2ea9-efbd-1ef8-63686f7fef62
* Content: [System requirements for Skype for Business Server 2019](https://docs.microsoft.com/en-us/SkypeForBusiness/plan/system-requirements#file-share)
* Content Source: [Skype/SfBServer2019/plan/system-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/plan/system-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hi @jdubyaeber thanks for your feedback.
HTTP Activation belongs to Microsoft .NET Framework Software/Role not IIS.
I can confirm you that listed roles are needed for Edge.
Thank you

**Comment by scanum** [comment]
@officedocsbot close
