### ISSUE TITLE
Missing Items - Install required roles and features for front-end servers!

### ISSUE THREAD

**Issue by finnsloss** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#154]
If you follow the "Install required roles and features for front-end servers" process and enable the roles using the GUI there are a few components missing. This will cause problems with F5 (and probably other) load balancers identifying the web services are running successfully.
The following components are not in the list:
What if: Performing installation for "[Web Server (IIS)] Directory Browsing".
What if: Performing installation for "[Web Server (IIS)] Request Monitor".
What if: Performing installation for "[Web Server (IIS)] Basic Authentication".
What if: Performing installation for "[Web Server (IIS)] IIS 6 Management Compatibility".
What if: Performing installation for "[Web Server (IIS)] IIS 6 Metabase Compatibility".
What if: Performing installation for "[Background Intelligent Transfer Service (BITS)] Background Intelligent Transfer Service (BITS)".
What if: Performing installation for "[Background Intelligent Transfer Service (BITS)] IIS Server Extension".
What if: Performing installation for "[Web Server (IIS)] HTTP Redirection".
Thanks, Finn.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 926aca42-526a-6a46-c49f-60a83ccb72d8
* Version Independent ID: 601bbeaf-7568-ecfe-59ad-4488c270c82f
* Content: [Install prerequisites for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/install/install-prerequisites)
* Content Source: [Skype/SfbServer/deploy/install/install-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/install/install-prerequisites.md)
* Service: **unspecified**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@finnsloss - thank you for reporting this. I wrote this article originally and will check this out ASAP and report back here.

**Comment by kenwith** [comment]
Just to follow up I got some great info from support engineers and they reference me to [Installing Prerequisites for Skype for Business Server 2015](https://blogs.technet.microsoft.com/dodeitte/2015/05/04/installing-prerequisites-for-skype-for-business-server-2015/) and [Install Requirements for Skype for Business Server 2015 on Server 2012 R2](https://gallery.technet.microsoft.com/lync/Install-Requirements-for-aabf7358) so I am going to add this to my backlog to get the referenced article here updated with those other references. Unless you would be interested to help and get the [contributor](https://github.com/MicrosoftDocs/office-docs-powershell/graphs/contributors) credit? 😀 

At any rate I will leave this open until I can get this resolved. Thank you very much @finnsloss for taking the time to report!

**Comment by finnsloss** [comment]
On further investigation, I think that "Directory Browsing" was the feature that made the load balancer happy. It was testing that services were up by requesting the root page from each front end. Without Directory Browsing installed the front ends just served an entirely blank page (not even headers), which the load balancer interprets as a fail.

I'm not sure whether the other components that are installed by powershell are required or not?

**Comment by finnsloss** [comment]
I've also noticed that your page does include "Directory Browsing" (so apologies for this!). My colleague who configured the prerequisites was following the instructions on the "Plan your deployment > Requirements For Your Environment > Server Requirements" which don't include "Directory Browsing". The other 2 links you mention also don't include the features in their lists.

**Comment by kenwith** [comment]
@finnsloss - ok thanks for this info. I will leave this open and go through and make sure all the areas line up. Thanks for reporting and if you see other areas that need improvement please let us know or submit a Pull Request directly and we will merge it.

**Comment by kenwith** [comment]
I consolidated so that there is only one place where the prerequisites are listed and I added a cross-link. Thank you for finding this and reporting @finnsloss .  Closing this one out.
