### ISSUE TITLE
Module only has 2 commands

### ISSUE THREAD

**Issue by intared** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1541]
The SkypeOnlineConnector only has two commands available {New-CsOnlineSession, Set-WinRMNetworkDelayMS}.

Why's everything else missing? - And how do I get them?

PowerShell 5.1.17134.407
SkypeOnlineConnector 7.0.0.0

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3117c408-39c5-df82-7238-3e842e953a64
* Version Independent ID: 80a85e4e-a1b3-68a7-bb9c-544925bcb3ef
* Content: [Set up your computer for Windows PowerShell](https://docs.microsoft.com/en-gb/SkypeForBusiness/set-up-your-computer-for-windows-powershell/set-up-your-computer-for-windows-powershell)
* Content Source: [Skype/SfbOnline/set-up-your-computer-for-windows-powershell/set-up-your-computer-for-windows-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-your-computer-for-windows-powershell/set-up-your-computer-for-windows-powershell.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by eimann** [comment]
Try https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell

After logging in, this should list some more functions:

> Get-Command *onlinePSTNGateway*

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-CsOnlinePSTNGateway                            1.0        tmp_b541tfex.rlp
Function        New-CsOnlinePSTNGateway                            1.0        tmp_b541tfex.rlp
Function        Remove-CsOnlinePSTNGateway                         1.0        tmp_b541tfex.rlp
Function        Set-CsOnlinePSTNGateway                            1.0        tmp_b541tfex.rlp

**Comment by scanum** [comment]
@intared - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
