### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1543]
There's a typo in step 1 under Enable Location-Based Routing for users - missing the 'e' in 'online'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 471f2c60-5cb1-6863-30d5-4692f40d695a
* Version Independent ID: 2c4c5ea5-41e6-514c-b675-0bc2c0b5aaa9
* Content: [Enable Location-Based Routing for Direct Routing](https://docs.microsoft.com/en-us/microsoftteams/location-based-routing-enable)
* Content Source: [Teams/location-based-routing-enable.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/location-based-routing-enable.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by lindspea** [comment]
@TorrenManson Thank you for pointing this out and helping improve MS docs.  I will have the typo fixed as soon as possible.

**Comment by lindspea** [comment]
@scanum @AndreaBarr This can be closed thank you.
