### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1544]
New-Cs-TenantTrustedIPAddress has an extra -, in "Define External Subnets"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c64c973-c329-2cd4-d4c3-258f254fcccd
* Version Independent ID: fb3f5ebd-9bab-0a02-ba1f-d30445450d87
* Content: [Configure network settings for Location-Based Routing](https://docs.microsoft.com/en-us/microsoftteams/location-based-routing-configure-network-settings)
* Content Source: [Teams/location-based-routing-configure-network-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/location-based-routing-configure-network-settings.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by lindspea** [comment]
@TorrenManson thank you for pointing this out.  I will have the extra '-' removed as soon as possible.  Thanks again for your valuable contribution in helping improve MS Docs.

**Comment by lindspea** [comment]
@AndreaBarr  @scanum This can be closed thank you.
