### ISSUE TITLE
How much does it cost?

### ISSUE THREAD

**Issue by nwc01** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1548]
I was interested in possibly adding a voice conferencing plan to my Skype for Business account, but there is nothing here that tells me how much it costs or how to purchase the add-on license.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2b2f00a-d4ee-28ab-8c9f-fdc858eb30a4
* Version Independent ID: 07d9aa8b-7e6c-a340-bc75-f0c8159f6c57
* Content: [Availability in the United States (U.S.)](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-states-u-s)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-states-u-s.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-states-u-s.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @nwc01 

Thanks for reaching out! Please refer to the below URL for "Pricing for Audio Conferencing".

https://products.office.com/microsoft-teams/online-meeting-solutions

Hope this information helps you. Kindly confirm. Thank you.

**Comment by scanum** [comment]
@ We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
