### ISSUE TITLE
"Medium" rooms listed are larger than the "Large" rooms

### ISSUE THREAD

**Issue by Travis-Snoozy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#155]
In both room size/peripheral tables, the "Medium" room is bigger (18'x20') than the "Large" room (15'x20'). Typo/accidental swap?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 515e5db8-20be-f979-5de9-3998713518dd
* Version Independent ID: a284fee3-f324-2984-431e-df14d3c4bd2d
* Content: [Skype Room Systems v2 requirements](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/requirements)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/requirements.md)
* Service: **unspecified**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
REviewed the room definition spec for audio testing, the large room is actually 15 x 32 and not 15 x 20. Republishing with adjusted dimensions.
