### ISSUE TITLE
Poor example subnet (invalid)

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1552]
The subnet in the example for the New-CsTenantTrustedIPAddress command is a poor choice. 192.168.0.1 is an RFC1918 address, and is always internal by definition.

The blocks 192.0.2.0/24 (TEST-NET-1), 198.51.100.0/24 (TEST-NET-2), and 203.0.113.0/24 (TEST-NET-3) are provided for use in documentation, and an IP address from one of these ranges should be used instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c64c973-c329-2cd4-d4c3-258f254fcccd
* Version Independent ID: fb3f5ebd-9bab-0a02-ba1f-d30445450d87
* Content: [Configure network settings for Location-Based Routing](https://docs.microsoft.com/en-us/microsoftteams/location-based-routing-configure-network-settings)
* Content Source: [Teams/location-based-routing-configure-network-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/location-based-routing-configure-network-settings.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@TorrenManson Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
