### ISSUE TITLE
Misleading info in "Add call agents to a call queue" section

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1553]
In the "Add call agents to a call queue" section (https://docs.microsoft.com/en-us/skypeforbusiness/what-is-phone-system-in-office-365/create-a-phone-system-call-queue#add-call-agents-to-a-call-queue), the documentation says:

"Call agents (200 maximum) can be:
* An Online user with a Phone System license and enabled for Enterprise Voice or with a Calling Plan
* Online users with a Phone System license and a Calling Plan that are added to an Office 365 Group, a mail-enabled Distribution List, or a Security Group"

This piece suggests that we can add individual users to the call agents list.
In fact, we can only add groups to the call agents list

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f7c992d-94f2-8257-21f2-a67fcb34f177
* Version Independent ID: 17c3237d-439d-7930-ff02-53a9a60c8d96
* Content: [Create a Phone System call queue](https://docs.microsoft.com/en-us/skypeforbusiness/what-is-phone-system-in-office-365/create-a-phone-system-call-queue#add-call-agents-to-a-call-queue)
* Content Source: [Skype/SfbOnline/what-is-phone-system-in-office-365/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/what-is-phone-system-in-office-365/create-a-phone-system-call-queue.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by jambirk** [comment]
@tonysmit please take a look at this and contact me.

**Comment by gschilten** [comment]
Same problem. I can only define a group, but if I want to use serial routing, how can I define the order If I don't see the agents?

**Comment by scanum** [comment]
@jambirk Hi James, any updates on this issue? Thanks!

**Comment by jambirk** [comment]
I'm reasonably sure that the Serial Routing algorhithm itself defines the order, it's not user-configurable. @tonysmit or @waseemhashem might be able to correct me on that.

**Comment by scanum** [comment]
@waseemhashem Hi! Any updates on this issue?

**Comment by tonysmit** [comment]
@waseemhashem -ping.

@jambirk - calling this to your attention so you can update the content.

1. There isn't any configuration that I know of that a customer can change it. It's part of the algorithm as James said. 
2. Change this:
Call agents (200 maximum) can be:
An Online user with a Phone System license and enabled for Enterprise Voice or with a Calling Plan
Online users with a Phone System license and a Calling Plan that are added to an Office 365 Group, a mail-enabled Distribution List, or a Security Group"

to:
Call agents (200 maximum) must be a member of an Office 365 group, a mail-enabled distribution list or security group. Each person (call agent) in the group must have a Phone System license and a Call Plan assigned to them to be able to take incoming calls.

**Note:** You can't search and add a single user to a call queue. However, you can create a supported group and add a single user with a Phone System license and a Calling Plan to the group. You can the reorder each of those groups to direct calls to a single person.
