### ISSUE TITLE
Good information, but I hate the links

### ISSUE THREAD

**Issue by texexpat** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1554]
There is great information in this article, but the way it it presented is VERY awkward, clumsy, and distracting.  I want to read a single, well organized article.  But this article is arranged with every little piece in bits that the reader has to click on.  That means rather than being able to simply glance back at a previous section, I have to click on something to get there, then click something else to get back.

Please rearrange this guide as a single document.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3815835e-b1d2-cde8-89ac-591aec11bf66
* Version Independent ID: 13c9ee30-43ac-f619-88d1-2b4d2ebaa294
* Content: [Migration phases](https://docs.microsoft.com/en-us/skypeforbusiness/migration/migration-phases#feedback)
* Content Source: [Skype/SfBServer2019/migration/migration-phases.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/migration/migration-phases.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@texexpat  We appreciate any feedback that improves the content in the Microsoft docs and we will consider changing this in the future.
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
