### ISSUE TITLE
Tabs not working since Conditional Access was enabled 

### ISSUE THREAD

**Issue by DonPetry-EY** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1557]
Seeking an update on this.  We are blocked from using Flow and DevOps from Teams Tabs.

**Comment by scanum** [comment]
@DonPetry-EY  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by DavidLHannah** [comment]
Hi, I was able to work around this and allow Conditional Access protected web tabs in the Teams Desktop App.
