### ISSUE TITLE
"電源の BI" needs to be replaced with "Power BI"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1558]
https://docs.microsoft.com/ja-jp/microsoftteams/get-started-with-teams-monitor-usage-and-feedback

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd6683c0-a685-d279-538f-f0df86113911
* Version Independent ID: efe3afd1-f9c2-9db4-509f-8caaad6f0be0
* Content: [Monitor usage and feedback in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-started-with-teams-monitor-usage-and-feedback)
* Content Source: [Teams/get-started-with-teams-monitor-usage-and-feedback.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-started-with-teams-monitor-usage-and-feedback.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@samanthaw @MollyMalone Hi! Could you please aid with this request? Thanks

**Comment by samanthaw** [comment]
@hyoshioka0128 Thank you for reporting this issue, at this time we will not fix the over-translation of Microsoft Teams. It is a known issue that some of our product names are being unnecessarily translated by the machine translation. We are looking into a solution to fix these issues.
