### ISSUE TITLE
Storage of credentials for connectors to Teams

### ISSUE THREAD

**Issue by ginevr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1560]
Can you say something about how credentials of connected services (ex. DropBox) are stored in Teams?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6383162-7bcd-70cc-f7dd-b818d236bfdf
* Version Independent ID: 34c9897a-29ae-0048-30ce-da5abaffb76a
* Content: [Identity models and authentication in Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/identify-models-authentication)
* Content Source: [Teams/identify-models-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/identify-models-authentication.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by sowjanya365** [comment]
Hi @ginevr 

Thanks for reaching out!

Credentials of these connected services are not stored in Teams. 

The general idea is that the user will be redirected to Dropbox to authorize your app to access their Dropbox data. After the user has approved your app, they'll be sent back to your app with an authorization code. At this point your app will exchange the authorization code for an access token which can be used to make subsequent requests to the Dropbox API. This way user logs into Dropbox and authorizes your app. Dropbox redirects the user back to your app. Your app exchanges the authorization code for a reusable access token.

Hope this information is helpful. Kindly confirm. Thank you.

**Comment by scanum** [comment]
@ginevr - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
