### ISSUE TITLE
Test feedback

### ISSUE THREAD

**Issue by MollyMalone** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1568]
Test feedback

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ade1a4-092c-1132-44df-ee2c683fdd33
* Version Independent ID: 396b1aee-2f40-9895-9b00-07e38d11d31b
* Content: [Microsoft Teams analytics and reporting](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-reporting-reference#feedback)
* Content Source: [Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by RussC19** [comment]
@MollyMalone 

Could you please elaborate on 'Test feedback' as I see no test on which to feedback, and no feedback function on which to test? 

Thanks,

Russ

![image](https://user-images.githubusercontent.com/47165527/53060886-859c8900-34ee-11e9-9d00-930337e04ad2.png)

**Comment by MollyMalone** [comment]
@RussC19 Sorry, I was just testing the process for how to leave feedback.   I notice that some users were leaving feedback that links to localized content and I can't figure out how they are doing that as the Feedback control is disabled on the localized pages.  Anyway you can close this.

**Comment by RussC19** [comment]
Will do, thanks.
