### ISSUE TITLE
Incorrect example flag ReinviteResponceCode

### ISSUE THREAD

**Issue by MySkypeLab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1572]
The example command given in the document is "Set-CSOnlinePSTNGateway -Identity sbc1.contoso.com -ReinviteResponceCode "408""

The flag should be "-FailoverResponceCodes" instead of "-ReinviteResponceCode"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 485ba3d8-4016-aeb6-214c-22645d4ed439
* Version Independent ID: 328e0dac-7821-7607-0d89-8fba7711b11c
* Content: [Trunk failover on outbound calls](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-trunk-failover-on-outbound-call)
* Content Source: [Teams/direct-routing-trunk-failover-on-outbound-call.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-trunk-failover-on-outbound-call.md)
* Service: **msteams**
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by RussC19** [comment]
@MySkypeLab - I was assigned to modify this, but it looks as if it's already been done. Would you please confirm? 

Thanks.

Russ
![image](https://user-images.githubusercontent.com/47165527/53060816-4f5f0980-34ee-11e9-8a0b-18805c6d71d5.png)

**Comment by MySkypeLab** [comment]
Hi Russ,

Yep, looks like Shane Hoey already got a change implemented for this one. 

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/656e180b5986028dae24d94d38a82bf69979f8ca#diff-c631df4b65d286d1d49fcded934c981f

Thanks,
James

**Comment by RussC19** [comment]
HI James, thanks. I'll close this and initiate the pull request.

Russ
