### ISSUE TITLE
paragraphs returned from Japanese to English.

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1574]
After fix #1468, All the problematic paragraphs returned from Japanese to English.

https://docs.microsoft.com/ja-jp/microsoftteams/plan-teams-governance
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 20c43928-84c0-0a75-9354-66aef3b83e46
* Version Independent ID: f95298ae-de58-02eb-0b49-8390ab161d4c
* Content: [Teams でのガバナンスを計画する - Microsoft Teams](https://docs.microsoft.com/ja-jp/MicrosoftTeams/plan-teams-governance)
* Content Source: [Teams/plan-teams-governance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.ja-JP/blob/live-sxs/Teams/plan-teams-governance.md)
* Service: **msteams**
* GitHub Login: @rmw2890
* Microsoft Alias: **MyAdvisor**

**Comment by scanum** [comment]
@samanthaw @MollyMalone Hi! Can you please aid with this issue?

**Comment by samanthaw** [comment]
@scanum looking into it

**Comment by scanum** [comment]
@samanthaw any update on this issue? Thanks!

**Comment by samanthaw** [comment]
@scanum the bug is resolved (3173099), @OfficeGlobal to confirm if it's fixed (I still see some English paragraphs)

**Comment by OfficeGlobal** [comment]
@hyoshioka0128  Article is HumanTranslated and published live. The issue is fixed

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
Close #1574
