### ISSUE TITLE
URL broken

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1579]
Very first URL to the EHLO blog is incorrect, should be https://blogs.technet.microsoft.com/exchange/2019/02/08/retiring-unified-messaging-in-exchange-online/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63f7281d-e17d-c4e8-ced8-f4d695785e6c
* Version Independent ID: 40876324-10aa-e412-e1c2-868d1be2b9b1
* Content: [Exchange Unified Messaging Online migration support](https://docs.microsoft.com/en-us/SkypeForBusiness/plan/exchange-unified-messaging-online-migration-support)
* Content Source: [Skype/SfBServer2019/plan/exchange-unified-messaging-online-migration-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/plan/exchange-unified-messaging-online-migration-support.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @heidip
* Microsoft Alias: **heidip**

**Comment by phess67** [comment]
Thanks will get this corrected.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @TorrenManson 

We've verified the very first URL that you've referred in the document and we've found that it has been correctly pointing to the URL as you mentioned in the issue description. Kindly recheck and confirm us to close this issue. Thank you.

**Comment by TorrenManson** [comment]
Hi,

The URL was fixed on Feb 8th.

You can close this issue.

Thanks,
Torren

**Comment by sowjanya365** [comment]
Thank you for the confirmation, @TorrenManson.

**Comment by jimbchoi** [comment]
To be clear, only version SfB/Lync would get impacted due to EXUM online retirement is 2010, right? Lync server 2013 and SfB server 2015 already working with ExUM Online should be still supported with Cloud Voice without any manual intervention, I assume. Would someone please confirm this? Thanks a lot!

**Comment by scanum** [comment]
@TorrenManson  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
