### ISSUE TITLE
User Data after Trail?

### ISSUE THREAD

**Issue by dgonzaITpro** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1580]
What happens to a users data, files, etc... the trials ends? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the Microsoft Teams Commercial Cloud Trial offer](https://docs.microsoft.com/en-us/microsoftteams/iw-trial-teams)
* Content Source: [Teams/iw-trial-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/iw-trial-teams.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @dgonzaITpro 

Thank you for reaching out. 

Soon after the 30 day grace period, your trial account information and data is permanently erased. 

Hope this information is helpful. Kindly confirm and thank you for your patience.

**Comment by scanum** [comment]
@dgonzaITpro  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
