### ISSUE TITLE
"マイクロソフト チームのヘルプを表示します。" needs to be replaced with "Microsoft Teams でヘルプを利用する".

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1589]
https://docs.microsoft.com/ja-jp/microsoftteams/get-help-in-microsoft-teams

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4e853a70-3794-7f23-2dba-da09abf822e0
* Version Independent ID: d3dc0161-e075-df4d-d82c-a8f87c58da89
* Content: [マイクロソフト チームのヘルプを表示します。](https://docs.microsoft.com/ja-jp/microsoftteams/get-help-in-microsoft-teams)
* Content Source: [Teams/get-help-in-microsoft-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.ja-JP/blob/live-sxs/Teams/get-help-in-microsoft-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by samanthaw** [comment]
@hyoshioka0128 Thank you for reporting this issue, at this time we will not fix the over-translation of Microsoft Teams. It is a known issue that some of our product names are being unnecessarily translated by the machine translation. We are looking into a solution to fix these issues.
