### ISSUE TITLE
URL broken. [Plan Cloud auto attendant](～/plan-cloud-auto-attendant.md) → (～/plan-cloud-auto-attendant)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1592]
[Plan Cloud auto attendant]https://docs.microsoft.com/en-us/SkypeForBusiness/hybrid/plan-cloud-auto-attendant.md
↓
[Plan Cloud auto attendant]https://docs.microsoft.com/en-us/SkypeForBusiness/hybrid/plan-cloud-auto-attendant

https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Managing resource accounts in Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts?cid=kerryherger)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by hyoshioka0128** [comment]
Misunderstanding
Close #1592
