### ISSUE TITLE
Administratively remove Outlook add-in

### ISSUE THREAD

**Issue by xMarcus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1596]
How does an admin remove the Skype Outlook add-in for all users? Specifically the "New Skype Meeting" button in Outlook calendars.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e763c267-2c3a-190d-29e2-b5c81448fc10
* Version Independent ID: 98b73595-54ea-503c-ac3c-9df176543e9e
* Content: [Upgrade Skype for Business Online to Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/upgrade-to-teams-execute-skypeforbusinessonline)
* Content Source: [Teams/upgrade-to-Teams-execute-SkypeforBusinessOnline.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-to-Teams-execute-SkypeforBusinessOnline.md)
* Service: **msteams**
* GitHub Login: @arachmanGitHub
* Microsoft Alias: **arachman**

**Comment by FrancoiD** [comment]
This is done by granting either of the Teams Only or SfBWithTeamsCollabAndMeetings modes. At that point, the Teams application will remove the SFB plugin.

**Comment by FrancoiD** [comment]
It may require a restart of both Teams and Outlook. Also note that policy may take a few hours to propagate.

**Comment by scanum** [comment]
@xMarcus  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
