### ISSUE TITLE
Shared Mailbox in Teams

### ISSUE THREAD

**Issue by najimaga** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1597]
Hello,

I would like to ask about the Exchange Online Share Mailbox integration. I've test with creating multiple Teams groups and I cannot find this Shared Mailbox associated to the Teams group. It creates an Office 365 group that has a calendar. The Teams application itself has a calendar for scheduling meetings and audio-conferences, but the channel doesn't seem to have a Shared Mailbox or a Calendar, besides the one that comes with the Office 365 group and the additional third-party apps.

Maybe I am missing something, a clarification from your side would be highly appreciated.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e1b8fbb-3047-dd3a-6a9c-ae6b1d5a0222
* Version Independent ID: 42c418d1-8473-2243-81bc-558e0a0688aa
* Content: [Welcome to Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-overview)
* Content Source: [Teams/Teams-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by DeanGross** [comment]
It is hidden, see https://docs.microsoft.com/en-us/microsoftteams/office-365-groups#how-office-365-groups-work

**Comment by najimaga** [comment]
Hello Dean,

Thank you for your message, but I cannot agree with this.

The office 365 group is hidden with the parameter -HiddenFromExchangeClients and -HiddenFromAddressListsEnabled. Those commands are for unified group aka office 365 group. A shared mailbox is something different. So the part about the shared mailbox is confusing and not relevant. 

Thanks.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@najimaga - thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
