### ISSUE TITLE
How to Join link

### ISSUE THREAD

**Issue by poz1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1605]
Make "How to join" a link to the page in the last paragraph: "If you are a vendor seeking to join the certification program, see How to Join for requirements and available programs."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886ea065-904f-9ee9-e98c-6af2ba3216bc
* Version Independent ID: d3aaba1d-ef63-22ed-2d34-ef267999a84e
* Content: [Phones and Devices for Teams](https://docs.microsoft.com/en-us/skypeforbusiness/certification/teams-ip-phones)
* Content Source: [Skype/SfbPartnerCertification/certification/teams-ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbPartnerCertification/certification/teams-ip-phones.md)
* Service: **skype-for-business**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by v-calem** [comment]
Updating text with the link in question.

**Comment by jambirk** [comment]
this is resolved, closing the issue.
