### ISSUE TITLE
Meetings > Live events settings screenshots not valid as menu item does not exist

### ISSUE THREAD

**Issue by martinagrom** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1607]
"Meetings &gt; Live events settings" screenshots and description are not valid as menu item does not exist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b358007-ded1-e7e2-01ff-e646a0d8f9b6
* Version Independent ID: ef681dd5-896c-1b48-7009-63cf5847f126
* Content: [Configure live event settings in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/configure-teams-live-events)
* Content Source: [Teams/teams-live-events/configure-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/configure-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @tonysmith
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @martinagrom 

Thanks for reaching out! Please refer to the below link. It describes "Who can create live events".

https://support.office.com/article/get-started-with-microsoft-teams-live-events-d077fec2-a058-483e-9ab5-1494afda578a

Hope this information is helpful. Kindly confirm. Thank you for your patience.

**Comment by scanum** [comment]
@martinagrom  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
