### ISSUE TITLE
Outdated I think

### ISSUE THREAD

**Issue by labanex** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1609]
Set-UnifiedGroup -Identity "DISPLAY NAME or EMAIL ID of the group" -HiddenFromExchangeClientsEnabled:$false -HiddenFromAddressListsEnabled:$false
The note above may need to be adjusted. This command works for me. Unless, this is a command -HiddenFromExchangeClientsEnabled:$false that has not been released to all tenants yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d86301b-ce9c-388c-e563-9e5e5c27132e
* Version Independent ID: 07e4ae23-0966-e8f3-9b7c-4f6c02569eb0
* Content: [Office 365 Groups and Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/office-365-groups)
* Content Source: [Teams/Office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-groups.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by j7gordon** [comment]
+1

**Comment by lindspea** [comment]
@labanex Thanks for reaching out and helping improve MS docs.  Please could you confirm where this note appears. Is it in the actual MS doc or in a link?

**Comment by get-itips** [comment]
Hi @labanex hope you are doing good, thanks for your feedback.
I think you talk about  [this article](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/set-unifiedgroup?view=exchange-ps)

I tried the cmdlet with the HiddenFromAddressListsEnabled and HiddenFromExchangeClientsEnabled and it worked.

Is there a chance is working for your tenant now?

Thanks

**Comment by get-itips** [comment]
Hi @labanex how are you? Thanks for your feedback. Can you kindly describe what is the exact issue you identified with the article?
Thank you!

**Comment by scanum** [comment]
@officedocsbot close
