### ISSUE TITLE
Can see Heartbeats but no SRS-App Events

### ISSUE THREAD

**Issue by danielmarker** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#161]
After adding the "Skype Room System" into Windows Logs and installing the agent - I am unable to see any events apart from Heartbeats, any troubleshooting steps available for this which could be added to this document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef7ceb43-d37f-8918-855e-ac8375875e6e
* Version Independent ID: 1b48ad59-2737-7ac4-8ad5-80904c0e3ccc
* Content: [Deploy Skype Room Systems v2 management with OMS](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/with-oms)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/with-oms.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/with-oms.md)
* Service: **unspecified**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Turgay will have to be the one to answer this, but thanks for bringing it to our attention.

**Comment by Turgayo** [comment]
Hey Daniel,
Can you confirm that the Heartbeat events you are getting are from the Skype Room System event log, not the generic heartbeat messages generated by the OMS agent itself.

To do that, can you please check if the query below returns any data?
Event | where Source == "SRS-App"
