### ISSUE TITLE
SFB 2015 on-premise without hybrid configuration 

### ISSUE THREAD

**Issue by DBailey618** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1613]
We are currently running SFB 2015 on-premise and do not mind the migration to cloud voicemail, but not able to configure hybrid configuration (at this time).  The article states that this is mandatory.  Is there a work around to use cloud voicemail without a hybrid configuration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63f7281d-e17d-c4e8-ced8-f4d695785e6c
* Version Independent ID: 40876324-10aa-e412-e1c2-868d1be2b9b1
* Content: [Exchange Unified Messaging Online migration support](https://docs.microsoft.com/en-us/SkypeForBusiness/plan/exchange-unified-messaging-online-migration-support#exchumo-and-azure-cloud-based-services-feature-matrix)
* Content Source: [Skype/SfBServer2019/plan/exchange-unified-messaging-online-migration-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/plan/exchange-unified-messaging-online-migration-support.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @heidip
* Microsoft Alias: **heidip**

**Comment by phess67** [comment]
Unfortunately not. Without DirSync the CVM (online) service can not discover the mailboxes of the users receiving voicemails.

**Comment by scanum** [comment]
@DBailey618 Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
