### ISSUE TITLE
Add and configure tabs in Exchange on-premises

### ISSUE THREAD

**Issue by boehmmic** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1617]
In the table it is written that adding and configuring tabs in Teams with Exchange on-premises is not supported. In my company with EX2016 CU11 it is working fine. Why is there a "no" in the table above?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact#feedback)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by Larryngolog** [comment]
Also, we state in paragraph above article states "Users hosted on [..] or Exchange on-premises, must be synchronized to Azure Active Directory for Office 365. They can [..] configure tabs".

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hi @boehmmic thanks for your feedback, article was updated and improved.

**Comment by scanum** [comment]
@officedocsbot close
