### ISSUE TITLE
Meeting limit was raised to 250

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1619]
This article states that meetings have limit of 250 users https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams, here we see limit of 80 users per meeting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/known-issues)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@Larryngolog Thank you for reaching out and helping improve MS docs.  Please specify what you think should be changed to the MS document.  Just to clarify, 250 is the number of teams a user can create. Just need to be sure of what needs amending in the doc.

**Comment by Larryngolog** [comment]
Hi @lindspea. I'm talking about this wording: "Attendee maximum for meetings Each Microsoft Teams meeting can have up to 80 attendees.". As I have stated in my original post, this has been raised and documented in the article mentioned: "Number of people in a meeting 250"

**Comment by lindspea** [comment]
@Larryngolog So just to confirm this issue has been resolved and there are no changes to be made to the MS doc?

**Comment by Larryngolog** [comment]
Hi Lindspea, I'm not sure if I understand your question. When I go to article for which this issue was opened "Known issues for Microsoft Teams" https://docs.microsoft.com/en-us/MicrosoftTeams/known-issues you can find in the "Meetings" paragraph (https://docs.microsoft.com/en-us/MicrosoftTeams/known-issues#meetings) the following issue: "Attendee maximum for meetings " and the behavior is "Each Microsoft Teams meeting can have up to 80 attendees. ". This is an old limit, currently the limit is 250 users, as you can verify if you go to different article, that talks about Teams limits.

When you go here https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams you can see that "Number of people in a meeting" states "250". You need to update the Known issues for Microsoft Teams article. Also I suggest adding in the workaround column info about ability to create live events in teams which can host 10000 users.

**Comment by lindspea** [comment]
@Larryngolog Ok great, I understand now.  Thanks for your contribution.  I'll update the article soonest.

**Comment by scanum** [comment]
@Larryngolog  Thank you for submitting this feedback.

From our understanding, the issue has been resolved and Lindsay has updated the article. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
