### ISSUE TITLE
How up to date is the firmware compatibility list for skype room systems ?

### ISSUE THREAD

**Issue by JorisDes** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#162]
Dear, since we expercience severe problems with our Logitech Group set since a recent update to FW version 8.6.102, I was wondering if the certified firmware versions (some of them old) on the site are up to date ? 

Site: https://docs.microsoft.com/nl-nl/skypeforbusiness/plan-your-deployment/clients-and-devices/requirements

**Comment by jambirk** [comment]
The firmware versions presented are the Minimum Required versions and not necessarily Recommended versions, so it's unsurprising that some of them are not current. Can you provide more info on the problems you're seeing? I can alert the product group.
