### ISSUE TITLE
How to find out if we can get a local number

### ISSUE THREAD

**Issue by Lowell-Syncrety** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1623]
So 5 cities in Canada are listed where you can get a toll number... how can we find out if we can get a toll number elsewhere, or if we can port over our existing number?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae54019f-73df-4e8a-be75-3310fd585a61
* Version Independent ID: 581970cc-d568-b626-2895-3a66ee934f57
* Content: [Availability in Canada](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-canada)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-canada.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-canada.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@Lowell-Syncrety thank you for reaching out.  @cmcatee-MSFT

**Comment by cmcatee-MSFT** [comment]
@lindspea These are different from the contact support #s. @tonysmit owns this area and can help find out.

**Comment by tonysmit** [comment]
@Lowell-Syncrety - The only way to see the latest and available toll numbers (and others) is to use the Search and Acquire UI to find a number from our inventory. If you have a current phone number, you can easily port (transfer) it over to us. Here is a good doc to read: https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization/manage-phone-numbers-for-your-organization?toc=/skypeforbusiness/toc.json&bc=/skypeforbusiness/breadcrumb/toc.json and https://docs.microsoft.com/en-us/microsoftteams/transfer-phone-numbers-to-office-365
