### ISSUE TITLE
How to assign a policy

### ISSUE THREAD

**Issue by elenanakhmanson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1626]
The article says "assign it to the users you want to manage", but how and where do we do it? Could you provide links to the additional information? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce30163-6327-899b-281d-d4ef982fce5e
* Version Independent ID: e61dcbb8-4877-ef6f-1987-981cdd7fc82f
* Content: [Configure desktop sharing in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/configure-desktop-sharing)
* Content Source: [Teams/configure-desktop-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/configure-desktop-sharing.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **Lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @elenanakhmanson 

Thanks for reaching out. 

Kindly refer to the below link for more details on the "Manage meeting policies in Teams".

https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams

Hope this article helps you with the required information. Kindly confirm. Thank you.

**Comment by scanum** [comment]
@elenanakhmanson  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
