### ISSUE TITLE
PowerShell Typo

### ISSUE THREAD

**Issue by BrianMcNeese** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1630]
PowerShell cmd is missing an 's':
Set-CsOnlineDialInConferencingTenantSetting**s** -AllowPSTNOnlyMeetingsByDefault $true | $false

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83f060f3-5817-be29-e8b6-ffb41682c83a
* Version Independent ID: e4831799-4fa0-224f-1d1b-d7bc3ee45971
* Content: [Start an Audio Conference over the phone without a PIN in Skype for Business Online](https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/start-an-audio-conference-over-the-phone-without-a-pin)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/start-an-audio-conference-over-the-phone-without-a-pin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/start-an-audio-conference-over-the-phone-without-a-pin.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by lindspea** [comment]
@AndreaBarr @yogkumgit please assign to me.

**Comment by lindspea** [comment]
@BrianMcNeese Hi Brian.  Thank you for pointing this out and helping improve MS docs.  Please can you specify where the 's' is missing so I can insert it in the correct place.

**Comment by BrianMcNeese** [comment]
Hi, under "Using Windows Powershell", the cmdlet 'Set-CsOnlineDialInConferencingTenantSetting' should have an 's' on the end, so: 'Set-CsOnlineDialInConferencingTenantSettings'
