### ISSUE TITLE
"Lync Basic 2013" incorrectly named as "Lync Basic 2013 Trial"

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1631]
In the "Lync Basic 2013 Trial Software" section, there are 3 instances of incorrect "Package Name".
It is named here as "Trial". But the software is free. There is no evaluation/trial version of it.
The correct name is on Download Center (https://www.microsoft.com/en-us/download/details.aspx?id=35451) - "Microsoft Lync Basic 2013 (32 Bit)" (without word "Trial")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc1999a1-66c4-1236-54e5-6491c8b70c1c
* Version Independent ID: 8b423b6d-793b-52ee-0031-1f80ea453a3c
* Content: [Latest updates for versions of Skype for Business that use Windows Installer (MSI)](https://docs.microsoft.com/en-us/skypeforbusiness/sfb-client-updates?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json#lync-basic-2013-trial-software)
* Content Source: [Skype/SfbServer/sfb-client-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/sfb-client-updates.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
This correction is on its way, thanks for bringing it to us.
