### ISSUE TITLE
A paragraph containing "Guest" is returning from Japanese to English

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1634]
After #715, All the problematic paragraphs returned from Japanese to English.

https://docs.microsoft.com/ja-jp/microsoftteams/teams-dependencies

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2b05e642-c4e5-f1b5-5315-d3ef1690a0cd
* Version Independent ID: 01b7e0b5-3e50-3de0-e3e9-aeeeda43da12
* Content: [Microsoft Teams でのゲスト アクセスを承認する](https://docs.microsoft.com/ja-jp/microsoftteams/teams-dependencies)
* Content Source: [Teams/Teams-dependencies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.ja-JP/blob/live-sxs/Teams/Teams-dependencies.md)
* Service: **msteams**
* GitHub Login: @somakbhattacharyya
* Microsoft Alias: **sbhatta**

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by OfficeGlobal** [comment]
@samanthaw  Working on a fix (Bug 3233070)

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 The article has been re-processed, all paragraphs are transalted

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
Close #1634
