### ISSUE TITLE
External domain access list : MS teams and SfBOlnine

### ISSUE THREAD

**Issue by Arcass** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1635]
Is the External Domain Access list shared between Microsoft Teams and Skype for Business Online or are they maintained as separate lists? 
If they are common, can I use the New-CsEdgeAllowList cmdlet to manage the Microsoft Teams allowed domains list?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31588a25-f3ee-e888-aa67-203be3d34489
* Version Independent ID: 3b498bcf-69a9-01ac-973a-4d5dbeea587c
* Content: [Manage external access (federation) in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @Arcass 

Thanks for reaching out!

Yes, external domain access list is shared between Microsoft Teams and Skype for Business Online. So you can manage the teams external list using the "New-CsEdgeAllowList" cmdlet as well. 

Hope this information is helpful. Looking forward to your confirmation. Thank you.

**Comment by scanum** [comment]
@Arcass  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
