### ISSUE TITLE
Standard Edition

### ISSUE THREAD

**Issue by Michal-Witwicki** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1636]
Microsoft announced that there will be no Standard version available in the 2019 edition. Documentation in a few places refers to the Standard edition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd40e9bf-6fb5-b597-5494-b9ccc17e4660
* Version Independent ID: 46d0d0a0-2ea9-efbd-1ef8-63686f7fef62
* Content: [System requirements for Skype for Business Server 2019](https://docs.microsoft.com/en-us/skypeforbusiness/plan/system-requirements#DBs)
* Content Source: [Skype/SfBServer2019/plan/system-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/plan/system-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by VLG17** [comment]
During the last Ignite in September 2018 it was confirmed that Skype for Business Standard Edition is there to say. For reference, the session is called "Everything you need to know about Skype for Business Server".

**Comment by scanum** [comment]
@Michal-Witwicki  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
