### ISSUE TITLE
Missing information about what happens when a user leaves a team

### ISSUE THREAD

**Issue by rolleddice** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1637]
When assigning or editing the dynamic group the users should join or leave the group as you define. But I am missing some information about what happens if a user that becomes a member of a group dynamically decides to leave the Team.

Firstly I think that the behavior of this should be the same as in Groups. I cannot decide to leave a group that I am dynamically a member of. In Teams I can and when doing this a cannot find a way to join the group again.

How is this designed? Membership is separate from Groups and only get updated when changing dynamic membership rules?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a578ddb-6494-9bda-529e-0156e5ab7c30
* Version Independent ID: 57d519c9-90f0-873d-ffef-589f0b3b3ac9
* Content: [Overview of dynamic membership for teams](https://docs.microsoft.com/en-us/microsoftteams/dynamic-memberships)
* Content Source: [Teams/dynamic-memberships.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/dynamic-memberships.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
@rolleddice Interesting question. I've asked the experts, waiting on an answer from them.

**Comment by jambirk** [comment]
And here's the answer:  "Members of Teams backed by dynamic groups can not leave the team. Owners of these teams can add members. Reason being the membership is locked down and fully controlled by the rules that define team members."

I'll add a not to clarify.
