### ISSUE TITLE
Where to define the new SBA in the Topology - in case SBA Skype 2015

### ISSUE THREAD

**Issue by OE10** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1638]
Hi,
Where we need to define the new SBA 2015 on Skype 2019 Topology- under branch site there are subfolders: Lync 2013/Skyoe 2015/Skype2019 - in case its SBA 2015 do we need to put under Skype 2015 or 2019?
Thanks
Erez

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e21d998-d4db-a632-6560-ab9a796b5159
* Version Independent ID: 13438ad4-3a7e-6700-4127-b59d99b53543
* Content: [Connect a Survivable Branch Appliance](https://docs.microsoft.com/en-us/skypeforbusiness/migration/connect-a-survivable-branch-appliance)
* Content Source: [Skype/SfBServer2019/migration/connect-a-survivable-branch-appliance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/migration/connect-a-survivable-branch-appliance.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @OE10 

Thanks for reaching out!

If your organization is planning to migrate to Skype 2019 you should define the new SBA under Skype 2019 folder. 

Hope this information is helpful. Kindly confirm. Thank you.

**Comment by OE10** [comment]
Hi,
So maybe there is a mistake on the link: Skype/SfBServer2019/migration/connect-a-survivable-branch-appliance.md
Because you can see the below steps that talk about legacy SBA (for Skype 2019 need to use the same SBA for Skype 2015 – which means a legacy SBA)

To associate the legacy SBA to the Skype for Business Server 2019 Front End pool:
i.	Expand the branch site that has been created.
ii.	Right-click on legacy version, and then click New.
iii.	Click Survivable Branch Appliance.

**Comment by sowjanya365** [comment]
Hi @OE10 

Thanks for your patience. Appreciate it. 

Apologies for creating the confusion. If you are looking for associating the legacy SBA to the Skype for Business Server 2019 Front End pool, you need create a new survivable branch appliance on the legacy version(in this scenario it is Skype for business server 2015). 

Hope this information is helpful. Looking forward to your confirmation. Thank you.

**Comment by scanum** [comment]
@OE10  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
