### ISSUE TITLE
List complete?  

### ISSUE THREAD

**Issue by itthing** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1642]
Is this list supposed to be complete?  Dell is listing their UC350 headset as Skype for Business Certified at https://www.dell.com/en-us/work/shop/dell-pro-stereo-headset-uc350-skype-for-business/apd/750-aavm/pc-accessories

I'm looking for options, but don't want to narrow the vendor selection further than necessary if there is other legitimate hardware to consider.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63af828-0b5a-ba28-7fa6-0016b0b9a355
* Version Independent ID: 0e7b881f-f4bd-94b9-cefc-0bcc2040a7c1
* Content: [Phones and Devices for Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/certification/devices-usb-devices)
* Content Source: [Skype/SfbPartnerCertification/certification/devices-usb-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbPartnerCertification/certification/devices-usb-devices.md)
* Service: **skype-for-business**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
My understanding is that this list should be complete and up to date. @dougand-MSFT can you provide more information here?

**Comment by dougand-MSFT** [comment]
the list is updated periodically, so the most recently certified devices may not be listed.  In general the best place to look first is: https://products.office.com/en-us/microsoft-teams/across-devices/devices

that site is more curated so will have the most information about devices, though it may not have all devices (especially older ones).

**Comment by yogkumgit** [comment]
@dougand-MSFT  Thank you very much for the contribution and sharing this explanation. @itthing 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
