### ISSUE TITLE
article has not been updated since 2014 - lots of missing builds

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1644]
article says "check out this frequently updated list" - what a joke :)
it has not been updated since 2014.
lots of missing Lync 2013 client builds

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91cb10fb-a51b-edc0-7a3e-75f23f124d70
* Version Independent ID: 3a1965f8-a0b1-da45-545b-a5dd85336d32
* Content: [Lync 2013: Updates for client and server](https://docs.microsoft.com/en-us/lyncserver/lync-2013-updates-for-client-and-server)
* Content Source: [Lync/LyncServer/lync-2013-updates-for-client-and-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Lync/LyncServer/lync-2013-updates-for-client-and-server.md)
* GitHub Login: @dstrome2

**Comment by shivtorov** [comment]
the article should be updated with a link to the page with recent updates https://docs.microsoft.com/en-au/SkypeForBusiness/sfb-client-updates#lync-2013-client-updates

**Comment by shivtorov** [comment]
also, all URLs in the "KB article" column are broken:
* labels are correct, e.g. "http://support.microsoft.com/kb/2899507"
* but the actual URLs do not work, e.g. "http://go.microsoft.com/fwlink/p/?linkid=3052%26kbid=2899507"

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@officedocsbot close

**Comment by scanum** [comment]
@shivtorov  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.
