### ISSUE TITLE
clarify .Net Framework version support

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1645]
Could you please clarify support for .Net Framework versions? Especially for the 4.7.x versions.

For 4.6.x - https://blogs.technet.microsoft.com/nexthop/2016/02/11/on-net-framework-4-6-2-and-skype-for-businesslync-server-compatibility/ - says:
"Both Lync Server 2013 and Skype for Business Server 2015 are supported with the .Net Framework 4.6.2.
Lync Server 2013 must have the November 2016 update, or later installed."

PS: 
In SFB Server 2015 documentation, .Net Framework support is clearly defined:
https://docs.microsoft.com/en-au/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/server-requirements 
"Skype for Business Server works with the following Microsoft .NET Framework versions: 
• .NET 3.5 
• .NET 4.5 
• .NET 4.6.x 
• .NET 4.7.1 and higher (for Skype for Business Server CU 5 or later releases) 
• .NET 4.7.2 and higher (for Skype for Business Server CU 6 or later releases)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5fa61e2-cc2e-279f-d3b2-c33a1ea576c1
* Version Independent ID: dc8a2829-fef0-7494-b971-ae8194243ec6
* Content: [Lync Server 2013: Additional software requirements](https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-additional-software-requirements)
* Content Source: [Lync/LyncServer/lync-server-2013-additional-software-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Lync/LyncServer/lync-server-2013-additional-software-requirements.md)
* GitHub Login: @dstrome2

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @shivtorov 

Thanks for reaching out!

There is no official confirmation on the Lync server 2013 support with .Net 4.7.x versions. So please read it as unsupported. 

Hope this information helps you. Kindly confirm.

**Comment by scanum** [comment]
@shivtorov  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
