### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by jaypatrick** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1646]
This link is 404: https://docs.microsoft.com/en-us/MicrosoftTeams/phones-for-teams.md#microsoft-teams-phones-feature-set

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886ea065-904f-9ee9-e98c-6af2ba3216bc
* Version Independent ID: d3aaba1d-ef63-22ed-2d34-ef267999a84e
* Content: [Phones and Devices for Teams](https://docs.microsoft.com/en-us/skypeforbusiness/certification/teams-ip-phones)
* Content Source: [Skype/SfbPartnerCertification/certification/teams-ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbPartnerCertification/certification/teams-ip-phones.md)
* Service: **skype-for-business**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
You are correct, but I believe that whole page has been removed and its contents redistributed, and other work in this area is still underway. I'll check back on this later today and update the link to the new location.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@jaypatrick @jambirk Just need to confirm if this has been updated and issue solved?

**Comment by jambirk** [comment]
Just verified that the link is working now.
