### ISSUE TITLE
Desktop Logs - Help menu does not include "Get Logs" option

### ISSUE THREAD

**Issue by tomlaciano** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1649]
Under the Desktop log section for Windows, there are 2 problems: 
Problem 1 - There is no Get Logs option inside the Teams Help as suggested 
I see no Get Logs option from within the Teams client and this option should be removed or more precise navigation should be provided. 
Problem 2 - Teams Help is not a pull-down menu  
There are 2 places to find Help (Note: neither of these include a Get Logs option) 
The lower left of the Teams client
The 3 ellipses in the left navigation bar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d5e6d3-b7e0-d79f-0dea-ed423186a157
* Version Independent ID: ec6e68aa-552f-ab45-3c8e-92eff526b173
* Content: [Use log files in troubleshooting Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/log-files)
* Content Source: [Teams/log-files.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/log-files.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@tomlaciano - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by tomlaciano** [comment]
I believe you have misunderstood my feedback. I don't have a problem to be solved, I am stating that the Help content has incorrect or inaccurate references to the UI elements for finding or getting logs.

**Comment by get-itips** [comment]
Thanks @tomlaciano the article will be improved after your comment.
