### ISSUE TITLE
External app list no longer showing in O365 Services and Add-Ins

### ISSUE THREAD

**Issue by dcnoren** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1650]
Environment used to be like screenshot above with things like "Adobe Creative Cloud" showing in the list of External Apps. This list is no longer showing, however all of the other settings are. Where did this list move to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 143108bb-d6e6-48a8-a7cb-d11b89ebeaab
* Version Independent ID: 145773e2-149e-1c1c-5797-433c13f13b22
* Content: [Admin settings for apps in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/admin-settings)
* Content Source: [Teams/admin-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/admin-settings.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by TheSharePointProfessional** [comment]
Since Apps settings have been greyed out from the old Teams > Services & add-ins page. and not replicated anywhere in the new Teams admin center, it seems as if you have taken away the ability to effectively manage these settings #wtf

**Comment by murray79** [comment]
I also have this problem. Was a resolution found?

**Comment by mpcrossley** [comment]
Same here - I can't load my app studio app because of this now

**Comment by dcnoren** [comment]
For whatever reason, the change seems to be that actually you have to disable sideloading of apps to see the list of the third-party apps. Weird. But, turn off sideloading, and now you can manage third-party apps.

![image](https://user-images.githubusercontent.com/3228595/53793219-59f6b580-3f68-11e9-982d-0e6d96e691fc.png)

Disable it and:

![image](https://user-images.githubusercontent.com/3228595/53793240-64b14a80-3f68-11e9-947c-c62477d0e0a7.png)

(By the way, this is accessed via https://admin.microsoft.com/Adminportal/Home?source=applauncher#/Settings/ServicesAndAddIns and then selecting Teams, then apps)

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@dcnoren  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
