### ISSUE TITLE
[Office 365 導入ガイド] replace the link destination from English(en-us) to Japanese(ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1654]
https://docs.microsoft.com/ja-jp/microsoftteams/continue-journey

[Office 365 導入ガイド]"https://go.microsoft.com/fwlink/?linkid=859045"
 "https://fto365dev.blob.core.windows.net/media/Default/DocResources/en-us/Office_365_Adoption_Guide.pdf"
 ↓
 "https://fto365dev.blob.core.windows.net/media/Default/DocResources/ja-jp/Office_365_Adoption_Guide.pdf"

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 01f00359-e536-fdd5-2c6e-859247d6f578
* Version Independent ID: dbba7a52-9c65-dc96-c0b6-1aed6c414000
* Content: [Microsoft Teams ユーザーの導入計画](https://docs.microsoft.com/ja-jp/microsoftteams/continue-journey)
* Content Source: [Teams/continue-journey.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.ja-JP/blob/live-sxs/Teams/continue-journey.md)
* Service: **msteams**
* GitHub Login: @dearbeen
* Microsoft Alias: **dearbeen**

**Comment by samanthaw** [comment]
@OfficeGlobal

**Comment by OfficeGlobal** [comment]
@samanthaw tracking bug 3201150

@hyoshioka0128 The link target destination was updated and verified on our side and is working as expected.

**Comment by yogkumgit** [comment]
@samanthaw  Thank you very much for the contribution and sharing this explanation. @hyoshioka0128 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by hyoshioka0128** [comment]
Closed #1654.
