### ISSUE TITLE
Duplicated content in this article.

### ISSUE THREAD

**Issue by BChaloupka** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#166]
In the Microsoft Teams infrastructure section there is duplicated text starting with "Teams also provides a calling and meetings experience that is built on the next ..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e1b8fbb-3047-dd3a-6a9c-ae6b1d5a0222
* Version Independent ID: 42c418d1-8473-2243-81bc-558e0a0688aa
* Content: [Overview of Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-overview#feedback)
* Content Source: [Teams/Teams-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by kenwith** [comment]
@BChaloupka - thank you for spotting this and reporting. I will work to get this resolved asap.

**Comment by kenwith** [comment]
Removed the duplicate content and should render as live shortly.
