### ISSUE TITLE
How Long Will SFB stay in support

### ISSUE THREAD

**Issue by abegeman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1663]
We are currently still migrating to SFB online as Teams does not have full feature parity. How long will SFB online continue to be supported?

**Comment by FrancoiD** [comment]
Hello @abegeman 
What specific capabilities of SfBOnline are you missing in Teams that prevent you from switching to it?
Thank you

**Comment by abegeman** [comment]
Hi, BYOT isn't fully supported yet in our region, call handling and, call queues still in progress. Our users just want to use it as a phone system and don't like the heavy large interface. Hoping that in the future the option for a snap out smaller client for phone calls will be available. There are more things but these are just a few off the top of my head

**Comment by FrancoiD** [comment]
I am not a specialist of Direct Routing, but it was my understanding that you could use it anywhere in the world. Call Queues are available, maybe there is one specific aspect of Call Queues you are looking for? Not sure what you meant by Call Handling. Maybe the situation has evolved and it may be worth reevaluating the Teams readiness? Thanks

**Comment by abegeman** [comment]
Hi FrancoiD thanks for your comments, it's under constant review, it can't do what we need at this time. I do need the original question answered, if anyone from Microsoft has the answer it would take some of the uncertainty away

**Comment by FrancoiD** [comment]
We would really, really appreciate specifics as what you state is not our perception, and if there are gaps, we would be happy to consider them for investment.

There is no information I can share on your specific question. We have not announced any end of service.

**Comment by abegeman** [comment]
Hello, one of the major pain points for us and what appears to be universally disliked by all our users is that the GUI. We get feedback that it’s too big and clunky. There is no immediate way of just using it is a detachable phone dialler. 90% of the time our SFB users are using it for just this.  There is no compact mode, no detachable chats. When users want a one-off chat they can’t do it without being a member of the Teams. Sometimes you just need to contact someone one-off and they don’t need to be in a Team. SFB was well laid out and quick to use when just needing to make a phone call. Teams needs to have some sort of pop out dialler or lite option. Aside from this on last check the below doesn’t work: 
•	No ability to add another PSTN caller to a current phone call on any platform/device
•	No caller id mapping to the local address book
•	Add external/federated contact to contact group.
•	Possibility to do desktop sharing during a 1-1 chat.
•	 no way to share desktop without being on a meeting
My other concerns are around Direct Routing. I haven’t had huge amount of experience with this yet, only Cloud Connector Edition, but I remember reading somewhere and this may have been resolved or untrue is that you lose control of some of the features we use our Session Boarder Controller for such as masking or changing outbound CLI information. To be honest we plan on staying with SFB until the pain points of Teams has been worked out and then changing only when we have to. SFB is working well for us ATM.

**Comment by scanum** [comment]
@abegeman  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocspr
