### ISSUE TITLE
Wenn der Teambesitzer das Unternehmen verlassen hat

### ISSUE THREAD

**Issue by SophieGvB** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1664]
Kann man über den Adminaccount an die Inhalte eines Teams kommen, wenn der einzige Besitzer das Unternehmen verlassen hat?
Oder kann man einrichten, dass der Admin bei jedem Team Besitzer ist?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 20423b44-629b-1bee-280c-fb55680cd33e
* Version Independent ID: a60f6a48-89d7-98b6-4245-4be171fd06fd
* Content: [Weisen Sie Team-Besitzer und Membern im Microsoft-Teams](https://docs.microsoft.com/de-de/microsoftteams/assign-roles-permissions)
* Content Source: [Teams/assign-roles-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-roles-permissions.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by jambirk** [comment]
Translated:  "Can you get to a team's content through the admin account if the only owner has left the company? Or can you set up that the admin is an owner with each team?"

@tonysmit can you comment here? @LolaJacobsen is unavailable

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by OfficeGlobal** [comment]
@MollyMalone , @scanum - this is not related to INTL content, but it's a question from the end user. Could you please follow up accordingly? Thank you

**Comment by MollyMalone** [comment]
@scanum or @tonysmit can you help with this?  See @jambirk's translation of the user question above.

**Comment by morphmax** [comment]
Is there any way to restrict access on a channel to selected team members within a team?

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@SophieGvB - https://blogs.technet.microsoft.com/skypehybridguy/2017/11/29/microsoft-teams-help-the-team-owner-left-the-company-and-we-dont-know-what-to-do/
Microsoft is working on Channels permission, but I don't think it's available just yet.

**Comment by scanum** [comment]
@L3vin  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
