### ISSUE TITLE
URL not working http://go.microsoft.com/fwlink/p/?LinkId=285379

### ISSUE THREAD

**Issue by tiagoroxo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1670]
URL not working http://go.microsoft.com/fwlink/p/?LinkId=285379

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad033838-b374-d225-12aa-33504335d70a
* Version Independent ID: 3d8bcc2a-236c-02cf-c144-657108891d72
* Content: [Lync Server 2013: Managing Quality of Service (QoS)](https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-managing-quality-of-service-qos)
* Content Source: [Lync/LyncServer/lync-server-2013-managing-quality-of-service-qos.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Lync/LyncServer/lync-server-2013-managing-quality-of-service-qos.md)
* GitHub Login: @dstrome2

**Comment by jambirk** [comment]
@tiagoroxo   It looks like the link target may have been retired.   how about https://docs.microsoft.com/en-us/powershell/module/netqos/?view=winserver2012-ps as a target to point to?

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@tiagoroxo please confirm if this issue has been solved. Thank you for reaching out and helping improve MS docs.

**Comment by tiagoroxo** [comment]
@lindspea I just tried on the page https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-managing-quality-of-service-qos but the URL "http://go.microsoft.com/fwlink/p/?LinkId=285379" still not working.

**Comment by lindspea** [comment]
@tiagoroxo Did you try the link James suggested: https://docs.microsoft.com/en-us/powershell/module/netqos/?view=winserver2012-ps

**Comment by tiagoroxo** [comment]
yep the Link that James suggested seems to be ok.

**Comment by scanum** [comment]
@tiagoroxo - Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
