### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1674]
Please add documentation for the settings shown in the Devices section of the Team Settings page in the Org-wide Area of the Teams Admin Center

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd1a01d8-95ab-89d3-d832-1b3ce139be5c
* Version Independent ID: ece856fc-11d9-2220-3646-b6d5f16829e6
* Content: [Phones and Devices for Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/certification/devices-meeting-rooms?toc=/MicrosoftTeams/toc.json&bc=/microsoftteams/breadcrumb/toc.json)
* Content Source: [Skype/SfbPartnerCertification/certification/devices-meeting-rooms.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbPartnerCertification/certification/devices-meeting-rooms.md)
* Service: **skype-for-business**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
@dougand-MSFT  please consider this suggestion and respond.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @DeanGross 

Thanks for reaching out!

Would you be so kind to elaborate more on this? It will help us to understand the requirement and take appropriate action.

Thank you.

**Comment by jambirk** [comment]
Hi @DeanGross 

Is your issue with the devices or the UX for Teams admin center?  Adding @tonysmit in case of the latter.

**Comment by DeanGross** [comment]
The problem is that there does not seem to be any documentation for the settings shown on this page https://admin.teams.microsoft.com/company-wide-settings/client-settings. There should be a page in the documentation that aligns with this page to describe the options for each of the configuration settings.

**Comment by sowjanya365** [comment]
Hi @DeanGross 

The following link describes the options present on the the "client-settings" page. 

https://docs.microsoft.com/en-us/microsoftteams/enable-features-office-365

Hope this information is helpful. Kindly confirm. Thank you.

**Comment by tonysmit** [comment]
I updated the code with the correct URL. Thanks.
________________________________

**Comment by scanum** [comment]
@DeanGross  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
