### ISSUE TITLE
Needs an update related to DFS shares to specify the RTC groups that should be in place on DFS shares since SfB cannot query them.

### ISSUE THREAD

**Issue by NicholasBurkhammer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1675]
Note:  If the file store is hosted on a DFS share, the following warning will be received.

Warning: Unable to access share permissions for "\\&lt;domain&gt;\&lt;share&gt;". This is expected if you are not an administrator on the file server, or if this is a Distributed File System (DFS) share. If the share permissions have already been configured, this warning can be ignored. If it is a new share, refer to the documentation for details on manually configuring share permissions.

Due to the inability to access the share permissions on a DFS share, Skype for Business Server will not be able to explicitly set groups on the file share.  To ensure Skype for Business Server components can access the file share with the appropriate permissions, ensure the following RTC groups are added with Change level share permissions in addition to the local Administrators with Full Control share permissions.

RTCHSUniversalServices
RTCComponentUniversalServices
RTCUniversalServerAdmins

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d0a3f4e-96f7-e32a-b84d-17d2892134c0
* Version Independent ID: f0c43daa-c85c-177a-4f38-75d99a093b4c
* Content: [Create a file share in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/install/create-a-file-share#feedback)
* Content Source: [Skype/SfbServer/deploy/install/create-a-file-share.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/install/create-a-file-share.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by Cloud-Writer** [comment]
@Ken Withee, this update has been approved by Sr. SPM Corbin Meek. Would you please approve this pull request? Nicholas technically requested this about a year ago but the update didn't get made because of the Docs migration. Many thanks!

**Comment by kenwith** [comment]
@Cloud-Writer - which Pull Request? This is an Issue. :)

**Comment by Cloud-Writer** [comment]
Oops! I thought my comment would be appended to the pull request ☹. It is #1675. https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/1675

Apologies Ken!

--Meera

**Comment by kenwith** [comment]
No worries, these are all "GitHub Issues" though.. the Pull Requests are on another tab.. here: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pulls

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@NicholasBurkhammer Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
