### ISSUE TITLE
Disabling Teams Features

### ISSUE THREAD

**Issue by jpwgc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1676]
"Currently, there are no policy options for turning Teams, or a subset of Teams features, on or off at an individual user level outside of licensing". Actually Chat can be turned on/off per user via policy. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cccdd91a-7f05-abd5-ed94-e82152b86914
* Version Independent ID: 3532d0a8-119c-f7d0-0d4f-a865ad32570f
* Content: [Manage user access to Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/user-access)
* Content Source: [Teams/user-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/user-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by FrancoiD** [comment]
That is entirely correct, this section is obsolete. @Jambirk

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@jpwgc  Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
