### ISSUE TITLE
Powershell linked but no commands found

### ISSUE THREAD

**Issue by junterpfe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1677]
for the section "Make changes to the email messages that are sent to them" it links to the powershell ref for teams but none of the commands allow you to change the from address.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0cd207e-eec4-11a5-9037-5d72a9ad5044
* Version Independent ID: b3757462-ceca-36ab-1b7a-8568a7481743
* Content: [Emails sent to users when their settings change in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/emails-sent-to-users-when-their-settings-change-in-teams)
* Content Source: [Teams/emails-sent-to-users-when-their-settings-change-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/emails-sent-to-users-when-their-settings-change-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@junterpfe  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
