### ISSUE TITLE
Reference to cmdlet but link to where the code is not available

### ISSUE THREAD

**Issue by theangellmethod** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1685]
In the first note it mentions that a cmdlet will be provided: "For customers that want to continue with the existing behavior of showing these groups in Outlook, an Exchange Online PowerShell cmdlet will be provided which can enable the group for the Outlook experience." 

How can we access the cmdlet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d86301b-ce9c-388c-e563-9e5e5c27132e
* Version Independent ID: 07e4ae23-0966-e8f3-9b7c-4f6c02569eb0
* Content: [Office 365 Groups and Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/office-365-groups)
* Content Source: [Teams/Office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-groups.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @theangellmethod 

Thank you for reaching out here and raising your concern. We appreciate it. The cmdlet is not yet published on the docs and the team is working on the update. Hope this helps. Thank you.

**Comment by scanum** [comment]
@theangellmethod We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by theangellmethod** [comment]
@scanum what kind of a response did you expect?  There is no question in the comment back to me.  There is no resolution for where to get the cmdlet.  The cmdlet is still not available.  Why would you close this?
