### ISSUE TITLE
not include *.broadcast.skype.com?

### ISSUE THREAD

**Issue by TomoharuMisawa** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1686]
Do not use * .broadcast.skype.com at the meeting Broadcast?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c7bea6c-13d8-f610-5d8d-47d463841ae3
* Version Independent ID: 739ff101-e66b-ea3e-2079-f9b7a3b303be
* Content: [Set up your network for Skype Meeting Broadcast](https://docs.microsoft.com/en-us/skypeforbusiness/set-up-your-network-for-skype-meeting-broadcast/set-up-your-network-for-skype-meeting-broadcast)
* Content Source: [Skype/SfbOnline/set-up-your-network-for-skype-meeting-broadcast/set-up-your-network-for-skype-meeting-broadcast.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-your-network-for-skype-meeting-broadcast/set-up-your-network-for-skype-meeting-broadcast.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @TomoharuMisawa 

Would you be so kind as to elaborate more on this issue? It would help us to understand it better and take appropriate steps to resolve or clarify. Thank you.

**Comment by TomoharuMisawa** [comment]
I'm sorry. I missed Step2.

**Comment by scanum** [comment]
@TomoharuMisawa  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
