### ISSUE TITLE
Skype or Teams not available

### ISSUE THREAD

**Issue by JumbaJookiba** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1688]
Using provisioning 0 and 1, I have the preferred application in the Start screen (either Skype or Teams), but the other one is not present anywhere, including All Apps.
Since Skype is not even listed in the Store, I cannot launch it from there.
This does not allow me using both, and this is a problem, because only through Skype I can reach my Videxio rooms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f256cd5b-3ec8-2d55-9ae4-ff9849d52eae
* Version Independent ID: 52c2271b-df38-5dc9-c2a1-553cdf3b5496
* Content: [Deploy Microsoft Teams for Surface Hub](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-surface-hub)
* Content Source: [Teams/teams-surface-hub.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-surface-hub.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by hoodahoop** [comment]
Hi there same issue. Can't see Skype after using provisioning 1. Thoughts on how to get it back/reinstall? Thanks!

**Comment by scanum** [comment]
@JumbaJookiba and @hoodahoop   - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
