### ISSUE TITLE
Team member maximum of 2500 

### ISSUE THREAD

**Issue by PhilFancy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1689]
I think this is outdated. I think max members count is 5000, isn't it?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Bekannte Probleme für Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/known-issues)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @PhilFancy 

Thanks for reaching out. 

Yes, each Microsoft Team can have a maximum of 5000 members per team. And it is documented in the content source.

Kindly share with us the link which you are referring to now (Max team member limit is 2500). It would help us to understand it better. 

Thank you.

**Comment by YuriySamorodov** [comment]
@sowjanya365 Here is an article showing up that there is a limit of 2500 members per Team:
https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team

**Comment by sowjanya365** [comment]
Hi @YuriySamorodov 

Thanks for your comments. You are right. 

Maximum number of members in a team is 5,000 and Maximum number in an org-wide team is 2,500.

Hope this information is helpful. Kindly confirm.

Thank you.

**Comment by scanum** [comment]
@PhilFancy @YuriySamorodov  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
