### ISSUE TITLE
The link to Security and Compliance powershell goes to EXO powershell.  

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#169]
There doesn't yet seem to be docs articles for set-teamsretentioncompliance* anywhere in that area.  Trying to find more info on preservation lock for Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca579d63-182b-d6f5-8777-79248fa27ed9
* Version Independent ID: b4c27d1b-b2f1-41ac-b15c-d12b448a539e
* Content: [Overview of security and compliance in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/security-compliance-overview)
* Content Source: [Teams/security-compliance-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/security-compliance-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by kenwith** [comment]
@chrislehr - I agree it is hard to find those. I will add the direct links to this article. In the meantime, you can find the cmdlets here:
1.  Go to [Exchange Online Cmdlet Reference](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell?view=exchange-ps)
2. On the left nav, expand Reference > Exchange > policy-and-compliance-retention.

Hope that helps and thank you for the feedback on this!

**Comment by kenwith** [comment]
@chrislehr - Ack, sorry I misread this one. I thought it was asking for the link to Exchange Online PowerShell. I will track this down.

**Comment by kenwith** [comment]
@chrislehr - I found out these cmdlets are in fact supposed to be in Exchange cmdlet content set since they directly relate those modules. I will add direct links in the article. I will keep this open until the links are added. Thanks again for pointing this out. I am sure a number of customers had the same confusion and I really appreciate you taking the time to submit feedback.

**Comment by kenwith** [comment]
Added direct links to the cmdlets in the [article](https://docs.microsoft.com/en-us/microsoftteams/security-compliance-overview). Thanks again for pointing this out!

**Comment by chrislehr** [comment]
This is the most impressed with a feedback loop ive been in recent memory. Awesome work. Thanks.

----------
Chris Lehr


On May 4, 2018, at 3:15 PM, Ken Withee <notifications@github.com<mailto:notifications@github.com>> wrote:


Added direct links to the cmdlets in the article<https://docs.microsoft.com/en-us/microsoftteams/security-compliance-overview>. Thanks again for pointing this out!
