### ISSUE TITLE
Configuring Closed Federation and Hybrid

### ISSUE THREAD

**Issue by JeffBrownTech** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1690]
Can additional documentation be included to show how to configure hybrid but leave closed federation and manage through allowed/blocked lists? The above command enables partner discovery, which will open a previously closed federation environment to an open federation. Having the closed federation with hybrid scenario documented would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18231e84-6544-85f9-802e-195f5272aeab
* Version Independent ID: 7d3161d7-9e00-c8f0-4ee7-acce85f469d8
* Content: [Configure Skype for Business hybrid](https://docs.microsoft.com/en-us/SkypeForBusiness/hybrid/configure-federation-with-skype-for-business-online?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json)
* Content Source: [Skype/SfbHybrid/hybrid/configure-federation-with-skype-for-business-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-federation-with-skype-for-business-online.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @JeffBrownTech 

Would you be so kind to elaborate more on this? It would help us to understand your concern and take the appropriate steps to address it. Thank you.

**Comment by JeffBrownTech** [comment]
This article gives an overview of the issue:
https://mikeparker365.co.uk/2016/11/14/skype-for-business-hybrid-with-closed-federation/

The documentation for enabling hybrid also enables partner discovery, which not all organizations have enabled. Disabling partner discovery allows organizations to only allow communication with domains listed in Allowed Domains. If these same companies want to enabled hybrid, then the documentation only states they have to enable partner discovery, therefore enable open federation. Additional documentation on if leaving partner discovery disabled is supported would be great.

**Comment by scanum** [comment]
@JeffBrownTech Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
