### ISSUE TITLE
Microphone only works for one meeting

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1695]
The microphone on my Surface Headphones will only work for one meeting. After hanging up from the meeting, the microphone doesn't work in my next meeting. Attempting to change the input to the mic built into the Surface Studio causes Microsoft Teams to freeze up; I can still hear others talking, but they can't hear me and the UI is frozen and the app will not close. When this happens, only a reboot will fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@sparkitect  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
