### ISSUE TITLE
Step 6

### ISSUE THREAD

**Issue by chall324** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1696]
I'm an administrator at work, we don't currently use MS Teams accept for this one user, who is wanting to share a file with a contractor. I have followed each step, however when I reach step 6, those settings simply don't exist. I still cannot find the user when trying to invite them to the team either. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams Guest Access checklist](https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @somakbhattacharyya
* Microsoft Alias: **sbhatta**

**Comment by jantoney** [comment]
This is a little confusing to get to.
Click the team name from the list on the left > Select the General channel
Up the top of the screen, under search, click the team name then Settings tab.
Guest permissions are there

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @chall324 

Thank you for reaching out!

If you're a team owner, you can change guest permission settings by going to the team name and clicking More options More options button > Manage team. 

Go to the Settings tab, and then click Guest permissions. Currently, you can give guests permission to add or remove channels.

Note: To add or change properties like the guest's display name, phone number, or title, talk to your IT admin.

Hope this clarifies your query. If not, would you be so kind to elaborate more on this.

 Kindly confirm. Thank you.

**Comment by scanum** [comment]
@chall324 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
