### ISSUE TITLE
How to add Company App to Default apps catalog

### ISSUE THREAD

**Issue by AndresCgaehd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1701]
I would like to know if is there a way to add a Company App to the default apps section in MS Teams. 

I'm trying to add a Bot app to all the company users by default in MS Teams, Is this possible in some way?

![image](https://user-images.githubusercontent.com/48034631/53451111-a760a900-39e3-11e9-9fef-4a8399ba0cc3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9b7f77-061d-a224-ff1c-8d3e15d21221
* Version Independent ID: 00fa9550-c4c4-3398-ffbb-271cc724048f
* Content: [Manage Microsoft Teams features in your Office 365 organization](https://docs.microsoft.com/en-us/microsoftteams/enable-features-office-365)
* Content Source: [Teams/enable-features-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enable-features-office-365.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by Gustavo935** [comment]
Same doubt here, I'm trying to avoid the installation process to the end users and enable Bot App by default to all the Organization.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @AndresCgaehd 

Thanks for reaching out!

Please refer to the link below. It explains how to publish apps to the Microsoft teams tenant apps catalog.

https://docs.microsoft.com/en-us/microsoftteams/tenant-apps-catalog-teams

Hope this clarifies your query. Kindly confirm.

Thanks.

**Comment by scanum** [comment]
@AndresCgaehd  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
