### ISSUE TITLE
Guest Inviter Role not supported (yet?)

### ISSUE THREAD

**Issue by almertes** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1703]
Guest Inviter Role not supported (yet?), but this is not documented here, which is a frequently used one stop shop for issues with TEAMS. Can you add this documentation and whether this is on the roadmap, etc.?  This Ignite session eluded to it coming, but still today it does not work: Real-world best practices for managing Office 365 groups - BRK3274.... https://www.youtube.com/watch?v=Q0uAKigosCM

Teams doesn't support the guest inviter role 
https://docs.microsoft.com/en-us/microsoftteams/teams-dependencies 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @almertes 

Thank you for your raising your concern here. We appreciate it. 

"Teams doesn't support the guest inviter role". This doesn't come under the issue list. It is a good to have feature. That's the reason team had document only in the following URL.

https://docs.microsoft.com/en-us/microsoftteams/teams-dependencies

Hope this is clear now. Thank you.

**Comment by scanum** [comment]
@almertes  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
