### ISSUE TITLE
Dead link - pricing

### ISSUE THREAD

**Issue by jason-ra** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1707]
Link to pricing page is 404: https://products.office.com/en-AU/skype-for-business/audio-conferencing#Requirements

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c6e2b61-656c-a4f8-94a7-ec3c14e4d65e
* Version Independent ID: 77932de0-0312-95c5-f356-89ece9b3aabd
* Content: [Phone numbers for Audio Conferencing in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/phone-numbers-for-audio-conferencing-in-teams)
* Content Source: [Teams/phone-numbers-for-audio-conferencing-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phone-numbers-for-audio-conferencing-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@jason-ra Thank you for pointing this out.  I have just checked and the link does work.  Please confirm if you're still having an issue with the link.

**Comment by jason-ra** [comment]
Still not working for me. I've just checked and the actual link in the doc is https://products.office.com/skype-for-business/audio-conferencing which returns a "302 Moved Temporarily" that redirects my browser to https://products.office.com/en-AU/skype-for-business/audio-conferencing.

If I replace 'en-au' with 'en-gb' or 'en-us' it does work. So just seems to be an issue with Australian locale 'en-au'

**Comment by kenwith** [comment]
@jason-ra - I wonder if it could be a caching issue? Can you try in an 'in-private' browsing window so that it doesn't look at any cache? I am trying this link: https://products.office.com/en-au/microsoft-teams/online-meeting-solutions#Requirements and it is rendering for me.

There is also a localization team we can check with if it still isn't working for you. Or perhaps something in the redirect was just fixed that I am not aware of. We will get this sorted out though and really appreciate you taking the time to submit the issue to make the docs better!

**Comment by jason-ra** [comment]
I've tried from my home PC with the same results. Link of https://products.office.com/skype-for-business/audio-conferencing#Requirements takes me to https://products.office.com/en-AU/skype-for-business/audio-conferencing#Requirements which is 404.

If I replace 'en-au' with 'en-gb', then:
https://products.office.com/en-gb/skype-for-business/audio-conferencing#Requirements redirects me to https://products.office.com/en-gb/microsoft-teams/online-meeting-solutions#Requirements which loads successfully.

**Comment by kenwith** [comment]
I am getting page not found on the en-au link too. @OfficeGlobal could this be a translation issue where link is not coming through for en-au language? If we switch to other language the link works fine.

**Comment by scanum** [comment]
@officedocsbot assign @officeglobal

**Comment by OfficeGlobal** [comment]
Hello @scanum, we have checked the article, mentioned link is hardcoded as _https://products.office.com/skype-for-business/audio-conferencing#Requirements_ therefore if you click the link it redirects to target page based on your browser settings.

**Comment by kenwith** [comment]
@OfficeGlobal - the issue we are seeing though is that if someone is   'en-au'   Austrialian English language, then there is a 404. Others seem to work fine though.

I confirmed by going directly to redirect to en-au language: https://products.office.com/en-AU/skype-for-business/audio-conferencing#Requirements

Is this something you could help with?

**Comment by OfficeGlobal** [comment]
@kenwith We're not able to fix the redirection from our side. But we recommend to add "/en-us/" to the link --> https://products.office.com/en-us/skype-for-business/audio-conferencing#Requirements 

Note: in such case all MachineTranslated markets will redirect to ENG page

**Comment by scanum** [comment]
@jason-ra Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
