### ISSUE TITLE
Spelling mistake on page Microsoft Teams analytics and reporting

### ISSUE THREAD

**Issue by baluilag** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1708]
Teams reporting reference:

1:1 calls a user **particpated** in
Messages a user posted in a team chat
Messages a user posted in a private chat
Last activity date of a user.

"Particpated" word should be as "participated"

URL: https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-reporting-reference

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@baluilag Thank you for pointing this out and making MS docs better.  I'll have this fixed as soon as possible.

**Comment by lindspea** [comment]
@scanum @AndreaBarr this can be closed thank you.

**Comment by scanum** [comment]
@baluilag Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
