### ISSUE TITLE
UCMA 3.0 Runtime download

### ISSUE THREAD

**Issue by heebtob** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#171]
Why is there no UCMA 3.0 Runtime download available from Microsoft?
The article describes how to use SEFAUtil with SfB 2015 and it's part of the ResKit for SfB 2015 but it only works with UCMA 3.0???
At least give us the possibility to download UCMA 3.0 Runtime or much better would be to update the SEFAUtil to UCMA 5.0.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 5e97f81b-dfc0-6b20-fb06-4addeface54b
* Version Independent ID: 830ab805-b0a2-41a4-42a6-ee248ae1bacb
* Content: [Bereitstellen des SEFAUtil-Tools in Skype for Business 2015](https://docs.microsoft.com/de-de/skypeforbusiness/deploy/deploy-enterprise-voice/deploy-the-sefautil-tool)
* Content Source: [Skype/SfbServer/deploy/deploy-enterprise-voice/deploy-the-sefautil-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.de-DE/blob/live-sxs/Skype/SfbServer/deploy/deploy-enterprise-voice/deploy-the-sefautil-tool.md)
* Service: **unspecified**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@heebtob - thank you for the feedback on this. I am looking into this now and will update this issue as I find more information. Thanks for taking the time to make the docs better!

**Comment by kenwith** [comment]
@heebtob - I was in contact with a senior escalations engineer internally and found at that you are exactly right that SEFAUtil is compiled against UCMA 3.0. We are filing a bug to request SEFAUtil to be compiled against UCMA 5.

Everyone agrees with you that we should keep the 3.0 runtime available for download since other customer's applications might be relying on it. The SDK would install the runtime. Here is the link: https://www.microsoft.com/en-us/download/details.aspx?id=10566

I am not a subject matter expert in this area so submitted the following Pull Request to improve the document. I added a link to the download. Please let me know what you think. Also, these are open source docs now and if there is a better way to improve it would be awesome if you were open to submit a Pull Request too but if you would rather not I can edit my PR too.

My PR is: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/177

**Comment by kenwith** [comment]
Update - It was noticed that UCMA 5.0 Runtime should be used when running SEFAUtil shipping with Skype for Business Server 2015. I am updating the Pull Request now with this info.

**Comment by kenwith** [comment]
PR updated - please check. I am also checking internally to confirm this is correct info: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/177

**Comment by heebtob** [comment]
@kenwith - Thank you for helping me. My use case is to disable call forwardings with a simple web service. The web service calls the SEFAUtil to disable them. It's a special development for a customer. 

The problem is that the SEFAUtil doesn't work on my server and I don't know why. It's a Windows Server 2016 with UCMA Runtime 4.0 and 5.0 installed. The server is already part of an application pool with an application endpoint (runs with UCMA 5.0) for another application. So everything related to certifcates etc. already works. I just added a new application endpoint for sefautil and tried to disable a call forward. It doesn't work but the application throws no error message at all. The only hint I had from the article was that I need UCMA 3.0. I couldn't install the SDK because I have no Visual Studio 2010 on the server. It tells me that Visual Studio 2010 is a requirement for the installation.

It's really hard to troubleshoot because the SEFAUtil gives no error message. I hope you're right and I don't need UCMA 3.0. I will do some wireshark sniffing and some sniffing on the SfB server side. Maybe I will find the cause this way.

**Comment by kenwith** [comment]
@heebtob - I think we might need an official support. Do you have a way to open a support ticket? I am going to keep talking to people too that might know but with a support ticket it will go straight to the right person that can help. This is really valuable info you are finding so I will capture when we resolve this and get the article updated. It concerns me that you would have to go to Wireshark for a product that should work so if you can open a support ticket and let me know the reference I will follow up internally too to make sure this is resolved. It is really not a good experience to have to go to the levels you are going to get this to work and I want to get it solved on the product level.

**Comment by chtartMSFT** [comment]
@heebtob Please try running Steps 1, 2, and 3 from the SfB Deployment Wizard on the Trusted Application Computer.  SEFAUtil requires the local configuration store to be present, as well as a certificate.  I believe that is another aspect missing in the docs.

**Comment by kenwith** [comment]
@chtartMSFT thanks for this! I will get this in the doc ASAP.

**Comment by kenwith** [comment]
I updated the doc and am pushing it out.. takes a little time to pull over to german. Thanks for reporting!

**Comment by kenwith** [comment]
Awesome, thanks for reporting.
