### ISSUE TITLE
Clarification required here

### ISSUE THREAD

**Issue by summone** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1710]
Correct me here if I am wrong with the following example.
We apply 3 yr retention policy for eol, spo, od4b. Next, we apply the same retention but form chat and msgs in teams. 
Now I delete say Rodgers account after one year.  His files are deleted now but the retention policy says we hold onto his personal data for 3 years for compliance reasons.
So we need the Teams channel msgs and chats retention policy to make sure we still keep hold of the persistent chat and msgs otherwise all Rodgers chat and msgs will be deleted and break the flow of all the chat flow he was involved in.
Or are you saying the channel chats are still persistent does not matter if you delete the user's profile and repositories? Any files Rodger uploaded to teams will still be accessible and not give you a "file not found msg"? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb40cf43-557e-d443-578b-49edca4a3179
* Version Independent ID: f78c9566-767f-bfae-7ba0-4e81d313034e
* Content: [Retention policies in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/retention-policies)
* Content Source: [Teams/retention-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/retention-policies.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @summone 

Thanks for reaching out!

If you set the 3 year retention policy for your "Teams channel messages and Teams chats" and 1 year deletion policy for your SharePoint Online and OneDrive for Business locations, you'll get a "File not found" error. But you can still access the "Teams channel messages and Teams chats."

Hope this information is helpful. Kindly confirm. Thank you.

**Comment by scanum** [comment]
@summone We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
