### ISSUE TITLE
what are the Teams IP phones requirements ?

### ISSUE THREAD

**Issue by piqueora** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1711]
I don't see in the Teams doc where Teams IP phones requirements are defined : DHCP settings required & optional, access to Teams using NAT / HTTP or socks proxy, ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae4c265a-8df4-647d-fc42-5054e3340c20
* Version Independent ID: 249c7301-9c82-b1c4-8401-54553370302b
* Content: [Phones for Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/phones-for-teams)
* Content Source: [Teams/phones-for-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phones-for-teams.md)
* Service: **skype-for-business**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Hi, thanks for your comment. The technical requirements for the phones and other devices are made available to manufacturers, and their equipment is tested and certified for Teams. These devices are available through http://office.com/teamsdevices which is linked in the page.  The particulars are not published, they are shared under an NDA. Manufacturers wishing to obtain them are directed to https://docs.microsoft.com/en-us/SkypeForBusiness/certification/how-to-join 

I suspect that doesn't answer the question you asked, but if you're trying to determine if a particular IP phone meets the requirements, the best thing to do is see if it shows up in the Teams Marketplace at https://products.office.com/en-us/microsoft-teams/across-devices/devices/category?devicetype=34 .
