### ISSUE TITLE
What is the defination of <  your Verified Domain >

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1712]
Hi, it looks that this document has been updated in 2017, but e.g. the previous comment "Multiple SIP/SMTP domains" from @rgsteele has been written in 2018. So that comment has been closed, but not implemented?

But to my comment is about defination of "**<  your Verified Domain >**"
On the step 1 you say:
> Specify a verified domain for your Skype for Business Online organization. This domain should be the same domain used as the primary SIP domain used for the cloud-based accounts.

But then on Step 7 you say:

> This domain should be the same domain used as the primary SMTP domain used for the on-premises Exchange accounts. This domain is referred as <your Verified Domain> in the following procedure.

Isn't that 10x easier to say, it is the domains you get by the command **get-cssipdomain**? Why to make it too complicated?

So would be any possibilities to clarify what do you mean by this, and how this should affect if you have 15 SIP domains in use? What steps I need to run 15 times?

regards
Petri

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19d818da-830e-c813-08af-6192eb403ccc
* Version Independent ID: 575c0a11-f6e1-c571-4ad4-d490915faa15
* Content: [Configure OAuth between Skype for Business Online and Exchange on premises](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/integrate-with-exchange-server/oauth-with-online-and-on-premises?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json)
* Content Source: [Skype/SfbServer/deploy/integrate-with-exchange-server/oauth-with-online-and-on-premises.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/integrate-with-exchange-server/oauth-with-online-and-on-premises.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Hi Petri, 

The comment has been closed in GitHub, and an issue added to our internal backlog, as @kenwith explained: "I was able to get this into the backlog for the Skype team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better."  I can understand frustration with the delay, but we are tracking this internally and will get to it when we're able.

**Comment by kenwith** [comment]
Also, this new Issue that was just opened will get picked up by a new process to work on improving articles based on the valuable feedback of people like you @Petri-X . Your knowledge is what makes the docs better so please keep up the great work. Sorry for the long delay before. It took me some time to get a process worked out but we are up and running with it now and working through these issues with content actively.

**Comment by Petri-X** [comment]
Okay, great to hear :)

And @jambirk the "frustration" might be a bit too strong term :D But thanks to share this.

**Comment by scanum** [comment]
@officedocsbot assign @scanum
