### ISSUE TITLE
Call Flag

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1713]
In my CDR database, I am seeing CallFlag's of 64 - Is there a full list somewhere of what these codes map to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99bd4293-407d-98be-740c-8b631527319b
* Version Independent ID: 63f6663c-5698-c7ad-1186-8f160a7d0ed2
* Content: [ConferenceSessionDetails table in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/schema-reference/call-detail-recording-cdr-database-schema/conferencesessiondetails-0)
* Content Source: [Skype/SfbServer/schema-reference/call-detail-recording-cdr-database-schema/conferencesessiondetails-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/schema-reference/call-detail-recording-cdr-database-schema/conferencesessiondetails-0.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@danieledwardgeorgehitchcock thank you for reaching out.  I'll investigate and get back to you soonest.

**Comment by scanum** [comment]
Hi @danieledwardgeorgehitchcock we do not have all available codes listed anywhere. This is an issue that the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by lindspea** [comment]
@scanum this can be closed.

**Comment by scanum** [comment]
@officedocsbot close
