### ISSUE TITLE
Step 7 when Exchange hybrid is already inplace

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1714]
Hi,
Scratching my head a bit with this. When I do have already working Exchange hybrid done I do have (most likely because of the Exchange Hybrid Wizard) the service principal names applied. There are at least followings already:
 - ..000/ews.contoso.com
 - ..000/autodiscover.contoso.com
 - ..000/contoso.com
Is there some other FQDNs needed as your code is adding "*.contoso.com"?

regards
Petri

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19d818da-830e-c813-08af-6192eb403ccc
* Version Independent ID: 575c0a11-f6e1-c571-4ad4-d490915faa15
* Content: [Configure OAuth between Skype for Business Online and Exchange on premises](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/integrate-with-exchange-server/oauth-with-online-and-on-premises)
* Content Source: [Skype/SfbServer/deploy/integrate-with-exchange-server/oauth-with-online-and-on-premises.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/integrate-with-exchange-server/oauth-with-online-and-on-premises.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by jambirk** [comment]
@Petri-X  contoso.com is a generic user domain name used in many of our powershell examples. We assume you'll know this because you've read other articles, and when you see it in scripts you'll edit the scripts to reflect the domain name of the actual environment.

**Comment by Petri-X** [comment]
Hi @jambirk 
The question was not about the domain name (contoso.com).

I already have Exchange hybrid up and running. Because of the actions taken with enabling the Exchange hybrid I already have those principal names added (most likely because of Exchange hybrid wizard). So the question to you was: do I still need to run this step? This script add principal name *.contoso.com, while Exchange hybrid has added the namess I listed earlier. What other principal names you do expect to see together with those?

**Comment by jambirk** [comment]
I honestly don't know. If you skip step 7 and your environment works, great.

**Comment by Petri-X** [comment]
Let me ask the original question:
How this document takes care of situation where Exchange hybrid is already setup? As these instructions overlay very strongly with the work what Exchange Hybrid Wizard has done.

I hope your team just not overlook this issue by "Exchange is not our problem" as these two products are so close to each others.

**Comment by jambirk** [comment]
As you say, this page has heavy overlap with exchange content, and since it is expressly oriented to Skype for Business Online admins, why it is located in the SFB server content set is a question worth answering. We're having internal discussions about either moving the page or taking it down completely. We'll let you know soon what the determination is.

**Comment by Petri-X** [comment]
@jambirk 
Ok, sounds interesting. While having that discussing, keep in mind that we seems to missing the documentation which have a direct path to the goal. Especially when the target is to have hybrid for both Exchange and Skype. Good luck for the work!
