### ISSUE TITLE
broken link at the end of the article.

### ISSUE THREAD

**Issue by rishire** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1715]
https://docs.microsoft.com/skypeforbusiness/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/enable-the-users-for-enterprise-voice-on-premises#special-considerations-when-enabling-users-for-enterprise-voice-on-premises

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b8da7c-87fe-fde4-ca1f-c36e062ab309
* Version Independent ID: bbfd16f1-7b78-5335-7dc5-4f6a39a4f81d
* Content: [User accounts in a hybrid environment with PSTN connectivity](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-user-accounts-in-a-hybrid-environment)
* Content Source: [Teams/direct-routing-user-accounts-in-a-hybrid-environment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-user-accounts-in-a-hybrid-environment.md)
* Service: **msteams**
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@rishire Hi Rick! Thank you very much for your feedback. We are currently working on this broken link and we will have this resolved ASAP.

**Comment by scanum** [comment]
PR #1717

**Comment by scanum** [comment]
@rishire  Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
