### ISSUE TITLE
Step 7, what should be replaced

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1716]
Hi,
On step you are asking:

> Save the following text to a PowerShell script file named, for example, RegisterEndpoints.ps1. This example uses a wildcard to register all endpoints for contoso.com. **Replace contoso.com with a hostname authority** for your on-premises Exchange organization

Could you explain where you have "contoso.com" on the script? Would be nice to know also what is the "hostname authority" which should be used?

regards
Petri

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19d818da-830e-c813-08af-6192eb403ccc
* Version Independent ID: 575c0a11-f6e1-c571-4ad4-d490915faa15
* Content: [Configure OAuth between Skype for Business Online and Exchange on premises](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/integrate-with-exchange-server/oauth-with-online-and-on-premises)
* Content Source: [Skype/SfbServer/deploy/integrate-with-exchange-server/oauth-with-online-and-on-premises.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/integrate-with-exchange-server/oauth-with-online-and-on-premises.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@Petri-X I'll do some investigating and let you know soonest.  Thanks for helping improve MS docs.

**Comment by jambirk** [comment]
@scanum :  contoso.com bolded in the comment above needs to be replaced with <your Verified Domain> to match the other procedures. The term "hostname authority" is completely misapplied here, should probably be FQDN instead.

**Comment by Petri-X** [comment]
Hi @jambirk 
I believe you misread me. The text says: "...Replace contoso.com with a hostname authority...". But if you look the lines below that text, there is no "contoso.com" anywhere on there to be replaced.

What should I say about the instructions if even you are saying: "..should probably be..". Does anybody really know how this should be? :)

**Comment by jambirk** [comment]
I just made a commit that resolves this, the whole step was removed.
