### ISSUE TITLE
About Enterprise Content Delivery Network (eCDN)

### ISSUE THREAD

**Issue by marielleneomabs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1719]
Is it mandatory to use eCDN, and to choose a partner ? 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: becbf3ca-b88c-b033-a145-9a1af201ced3
* Version Independent ID: 41a6a9b5-d3dd-d8c9-9e97-920ff2fd1a24
* Content: [Quelles sont les Teams Microsoft live événements ?](https://docs.microsoft.com/fr-fr/microsoftteams/teams-live-events/what-are-teams-live-events#feedback)
* Content Source: [Teams/teams-live-events/what-are-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/what-are-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @tonysmith
* Microsoft Alias: **tonysmit**

**Comment by lindspea** [comment]
@marielleneomabs thank you for reaching out.  I'll have an answer for you shortly.

**Comment by scanum** [comment]
@marielleneomabs  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
