### ISSUE TITLE
Need a clear statement on SFB server 2019 supported SQL AlwaysOn editions/versions 

### ISSUE THREAD

**Issue by howardzhangmsft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1720]
Please update this section with info below (obtained from PM/PG):
AlwaysOn Availability Groups and AlwaysOn Failover Cluster Instances

SQL Server 2017 Enterprise Edition
SQL Server 2016 Enterprise Edition
SQL Server 2017 Standard Edition with limitations*
SQL Server 2016 Standard Edition with limitations*
SQL server 2014 Enterprise Edition
SQL server 2012 Enterprise Edition

* SQL 2016 and 2017 Standard Edition limitation:

Always On availability groups is not supported, you can only choose Always On failover cluster instances.

Refer to below link:
https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-2016?view=sql-server-2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8c5958a-c5e5-5aba-211a-2886c86ba831
* Version Independent ID: e53ed9d2-4ee4-346a-054b-6cf44b6a189b
* Content: [Back End Server high availability in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/high-availability-and-disaster-recovery/back-end-server#alwayson-availability-groups-and-alwayson-failover-cluster-instances)
* Content Source: [Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/back-end-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/back-end-server.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by ivanja81** [comment]
The guidance for SQL AG groups is unclear. SFB 2019 seems only supported for 2016 and 2016. Hence the statement shows  "AlwaysOn Availability Groups and AlwaysOn Failover Cluster Instances are supported only on SQL Server 2014 Enterprise Edition and SQL Server 2012 Enterprise Edition. Skype for Business Server supports AlwaysOn Availability Groups only as active/passive, not active/active." This is contradicted.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@howardzhangmsft @ivanja81 Thank you for reaching out. Please confirm if this issue has been sorted or if any changes still need to be made.

**Comment by howardzhangmsft** [comment]
@lindspea please make the proposed changes, thanks.

**Comment by scanum** [comment]
@howardzhangmsft Thank you for submitting this feedback.

From our understanding, the issue has been resolved and Lindsay has updated the section. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
