### ISSUE TITLE
"セット CsTeamsMeetingPolicy" needs to be replaced with "Set-CsTeamsMeetingPolicy"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1726]
https://docs.microsoft.com/ja-jp/microsoftteams/configure-desktop-sharing

[Set-CsTeamsMeetingPolicy](https://docs.microsoft.com/ja-jp/powershell/module/skype/set-csteamsmeetingpolicy)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 9ce30163-6327-899b-281d-d4ef982fce5e
* Version Independent ID: e61dcbb8-4877-ef6f-1987-981cdd7fc82f
* Content: [Microsoft Teams でのデスクトップ共有を構成する](https://docs.microsoft.com/ja-jp/microsoftteams/configure-desktop-sharing#feedback)
* Content Source: [Teams/configure-desktop-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/configure-desktop-sharing.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **Lolaj**

**Comment by scanum** [comment]
@OfficeGlobal -Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 the overlocalized text has been fixed ( + Issue #1725)

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
Close #1726
