### ISSUE TITLE
Powershell update command omits full path to APPX

### ISSUE THREAD

**Issue by Travis-Snoozy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#173]
The command:

    Add-AppxPackage -Update -ForceApplicationShutdown -Path \\<share>\Rigel\x64\Ship\AppPackages\*\*.appx -DependencyPath (Get-ChildItem \\<share>\Rigel\x64\Ship\AppPackages\*\Dependencies\x64\*.appx | Foreach-Object {$_.FullName})

Should instead be:

    Add-AppxPackage -Update -ForceApplicationShutdown -Path '\\<share>\$oem$\$1\Rigel\x64\Ship\AppPackages\*\*.appx' -DependencyPath (Get-ChildItem '\\<share>\$oem$\$1\Rigel\x64\Ship\AppPackages\*\Dependencies\x64\*.appx' | Foreach-Object {$_.FullName})

Note the **single** quotes around the share paths, and the addition of the "$oem$\\$1\\" portion to the start of the paths.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510cc36b-9716-8ca4-5121-8cfb83fbc879
* Version Independent ID: 64279b69-7e33-e1b1-7d64-95a598807c53
* Content: [Manage Skype Room Systems v2](https://docs.microsoft.com/en-us/skypeforbusiness/manage/skype-room-systems-v2/skype-room-systems-v2)
* Content Source: [Skype/SfbServer/manage/skype-room-systems-v2/skype-room-systems-v2.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/skype-room-systems-v2/skype-room-systems-v2.md)
* Service: **unspecified**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
fixing this right now
