### ISSUE TITLE
GitHub Tab - Cannot add organization repository to teams tab

### ISSUE THREAD

**Issue by seannybgoode** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1730]
When adding a Github Tab to a teams page, users can only see their private github repos.

Steps:
1. Create a github user that has both private and organization repositories
2. Go to Microsoft Teams and add a tab for Github
3. Login with your github user

Result: User only has access to personal repositories to select for the team tab
Expected Result: User has access to both personal and organizational repositories

Note: The azure app service continuous deployment pipeline has options for organizational repositories. Seems like an oversight for this to be missing from Teams.

**Comment by scanum** [comment]
@seannybgoode - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
