### ISSUE TITLE
Elaborate on what needs exactly to be checked for verifying replication of CMS

### ISSUE THREAD

**Issue by rito2k** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1731]
For completeness and better understanding of the last steps, include what needs to be checked after running both Cmdlets, since just executing them does not necessarily mean everything is correct:
- Get-CsManagementStoreReplicationStatus: Check if UpToDate value is showing TRUE for all Replicas.
- Get-CsHostingProvider -LocalStore: doublecheck if the information shown matches the changes committed in the previous steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7c752a9-3e2d-c972-6dd5-182237e3f5e0
* Version Independent ID: 943a60d2-1afc-abb6-cdc9-3eef700a3c28
* Content: [Configure integration between on-premises Skype for Business Server and Outlook Web App](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/integrate-with-exchange-server/outlook-web-app)
* Content Source: [Skype/SfbServer/deploy/integrate-with-exchange-server/outlook-web-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/integrate-with-exchange-server/outlook-web-app.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@rito2k Thanks for helping improve docs.  I'll have this implemented as soon as possible.

**Comment by scanum** [comment]
@rito2k  Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
