### ISSUE TITLE
Do Archived Teams count against the limit on the total number of Teams in a tenant?

### ISSUE THREAD

**Issue by Hitchcock3** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1732]
Would be good to specify if Archived teams do or do not count against the 500,000 limit of the number of teams in a tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#feedback)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@Hitchcock3 Thank you for reaching out.  I'll look into this and give you an answer as soon as possible.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by Hitchcock3** [comment]
My question was not about per user limits but the limit on the number of teams in a tenant, which is 500,000. 

Put the question another way, can a tenant have 200,000 active teams and 400,000 archived teams?

**Comment by scanum** [comment]
@officedocsbot open

**Comment by LolaJacobsen** [comment]
Good question, @Hitchcock3 . @phecdalouie - can you tell us whether archived teams count toward the per-tenant limit?

**Comment by lindspea** [comment]
@Hitchcock3 @phecdalouie

**Comment by lindspea** [comment]
@Hitchcock3 still looking into this for you.  Will let you know as soon as I have the answer. @LolaJacobsen

**Comment by LolaJacobsen** [comment]
@Hitchcock3 - thanks for your patience. It took a while to track down the PM who knew the definitive answer. "Given that every team is backed by a group and archived teams are not deleted, archived teams WILL count against the total number of teams in a tenant."
