### ISSUE TITLE
Oh no..we can't connect to the Internet

### ISSUE THREAD

**Issue by TaquiM** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1733]
Mon Dec 10 2018 13:08:26 GMT+0530 (India Standard Time) <22180> -- event -- peakWorkingSetSize: 55500, privateBytes: 43544, sharedBytes: 32324, workingSetSize: 55288, status: success, scenario: f922837a-74a8-41f7-a922-e33d3c09d004, scenarioName: desktop_renderer_preload, name: desktop_renderer_preload, step: stop, sequence: 1, delta: 10, scenarioDelta: 10, elapsed: 2820, Scenario.Name: desktop_renderer_preload, Scenario.Step: stop, Scenario.Status: success,  
Mon Dec 10 2018 13:08:26 GMT+0530 (India Standard Time) <22180> -- info -- startPage: Base url fetched from qsp of start page 
Mon Dec 10 2018 13:08:26 GMT+0530 (India Standard Time) <22180> -- info -- startPage: dom loaded, checking for network connectivity 
Mon Dec 10 2018 13:08:26 GMT+0530 (India Standard Time) <22180> -- info -- startPage: XHR request executed for url: desktopclient/settings method: GET 
Mon Dec 10 2018 13:08:27 GMT+0530 (India Standard Time) <22180> -- info -- setting initial zoom to 0 
Mon Dec 10 2018 13:08:28 GMT+0530 (India Standard Time) <22180> -- error -- startPage: XHR request error status: 0 
Mon Dec 10 2018 13:08:28 GMT+0530 (India Standard Time) <22180> -- info -- Logging telemetry event: security_unsupported_ipc_channel 
Mon Dec 10 2018 13:08:28 GMT+0530 (India Standard Time) <22180> -- event -- channel: fetchEcsSettingFirstRetry, method: send, name: security_unsupported_ipc_channel,  
Mon Dec 10 2018 13:08:31 GMT+0530 (India Standard Time) <22180> -- info -- startPage: XHR request response for url: desktopclient/settings method: GET 
Mon Dec 10 2018 13:08:31 GMT+0530 (India Standard Time) <22180> -- info -- startPage: Error fetching ecs settings app seems to be offline queuing a retry 
Mon Dec 10 2018 13:08:31 GMT+0530 (India Standard Time) <22180> -- info -- startPage: XHR request executed for url: desktopclient/settings method: GET 
Mon Dec 10 2018 13:08:31 GMT+0530 (India Standard Time) <22180> -- error -- startPage: XHR request error status: 0 
Mon Dec 10 2018 13:08:34 GMT+0530 (India Standard Time) <22180> -- info -- startPage: XHR request response for url: desktopclient/settings method: GET 
Mon Dec 10 2018 13:08:34 GMT+0530 (India Standard Time) <22180> -- info -- startPage: Error fetching ecs settings app seems to be offline queuing a retry 
Mon Dec 10 2018 13:08:34 GMT+0530 (India Standard Time) <22180> -- info -- startPage: XHR request executed for url: desktopclient/settings method: GET 
Mon Dec 10 2018 13:08:34 GMT+0530 (India Standard Time) <22180> -- error -- startPage: XHR request error status: 0 
Mon Dec 10 2018 13:08:37 GMT+0530 (India Standard Time) <22180> -- info -- startPage: XHR request response for url: desktopclient/settings method: GET 
Mon Dec 10 2018 13:08:37 GMT+0530 (India Standard Time) <22180> -- info -- startPage: Error fetching ecs settings app seems to be offline queuing a retry 
Mon Dec 10 2018 13:08:37 GMT+0530 (India Standard Time) <22180> -- info -- startPage: XHR request executed for url: desktopclient/settings method: GET 
Mon Dec 10 2018 13:08:37 GMT+0530 (India Standard Time) <22180> -- error -- startPage: XHR request error status: 0 
Mon Dec 10 2018 13:08:40 GMT+0530 (India Standard Time) <22180> -- info -- startPage: XHR request response for url: desktopclient/settings method: GET 
Mon Dec 10 2018 13:08:40 GMT+0530 (India Standard Time) <22180> -- info -- startPage: Error fetching ecs settings app seems to be offline queuing a retry 
Mon Dec 10 2018 13:08:40 GMT+0530 (India Standard Time) <22180> -- info -- startPage: XHR request executed for url: desktopclient/settings method: GET 
Mon Dec 10 2018 13:08:40 GMT+0530 (India Standard Time) <22180> -- error -- startPage: XHR request error status: 0 
Mon Dec 10 2018 13:08:40 GMT+0530 (India Standard Time) <22180> -- info -- startPage: XHR request response for url: desktopclient/settings method: GET 
Mon Dec 10 2018 13:08:40 GMT+0530 (India Standard Time) <22180> -- info -- startPage: Error fetching ecs settings app seems to be offline queuing a retry 
Mon Dec 10 2018 13:08:40 GMT+0530 (India Standard Time) <22180> -- info -- startPage: Navigate to oops page in progress... 
Mon Dec 10 2018 13:08:40 GMT+0530 (India Standard Time) <22180> -- warning -- ipcRenderer: send called with unsupported channel fetchEcsSettingFirstRetry 
Mon Dec 10 2018 13:08:40 GMT+0530 (India Standard Time) <22180> -- event -- panelview: Panel.Type: oopsPage, Panel.Region: main, Panel.LaunchMethod: userInitiated, DataBag.OopsReason: network_connection_error,  
Mon Dec 10 2018 13:08:40 GMT+0530 (India Standard Time) <22180> -- warning -- Loading oops page due to: network_connection_error

**Comment by scanum** [comment]
@TaquiM  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
