### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Chukaka** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1736]
Found a small typo in the "Step 2: Get and assign licenses" section:

"After you buy the Audio Conferencing licenses, you will ned to assign them..." =&gt; "you will need"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86cb3a85-1dba-b63d-c9a4-f5229c1e462a
* Version Independent ID: c0fb6068-b27b-ff9a-e040-a63891caeb1c
* Content: [Set up Audio Conferencing for Skype for Business and Microsoft Teams](https://docs.microsoft.com/en-us/SkypeForBusiness/audio-conferencing-in-office-365/set-up-audio-conferencing#feedback)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/set-up-audio-conferencing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/set-up-audio-conferencing.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@Chukaka thank you for pointing this out and helping improve MS docs.  I'll have this rectified as soon as possible.

**Comment by scanum** [comment]
@Chukaka Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
