### ISSUE TITLE
App Studio Manifest Editor and Card editor blank

### ISSUE THREAD

**Issue by corymcm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1737]
After installing the App studio I was able to view the app studio manifest editor once now after installing my own hello world sample the manifest and card editor are blank. The hello world tab is also blank and the echo bot doesn't echo back to me. I've tried uninstalling the apps and all of teams as well as using the web application.

**Comment by scanum** [comment]
@corymcm - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
