### ISSUE TITLE
Apps and Bots and affect on security and compliance.

### ISSUE THREAD

**Issue by gasperj** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#174]
As Apps and Bots are a significant feature in Teams, it would be helpful to clarify how their use might affect compliance and security. Calling out Microsoft's own Apps and Bots for Teams and if their use invalidates any compliance and security would be helpful. Ideally, as 3rd-parties register their App or Bot, they should have to place their service in one of the Compliance Framework categories (A-D) or specify they don't meet any - this could help companies and institutes having to individually evaluate 3rd-party services and help these 3rd-party services increase data protection, compliance, and privacy.  One bad App or Bot will be more problem for Teams PR than the company responsible for the bad service. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca579d63-182b-d6f5-8777-79248fa27ed9
* Version Independent ID: b4c27d1b-b2f1-41ac-b15c-d12b448a539e
* Content: [Overview of security and compliance in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/security-compliance-overview)
* Content Source: [Teams/security-compliance-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/security-compliance-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by kenwith** [comment]
@gasperj - thank you for taking the time to submit the feedback. Would you mind submitting a Pull Request with recommendations? Since you already have a GitHub account you can click the Edit button in the upper right of the docs.microsoft.com article and start making edits. This will generate a Pull Request with your input.

Also, looping @ninadara, @alihirsch  who contributed this article.

**Comment by kenwith** [comment]
@billbliss - thank you for this information! @gasperj - this is really thoughtful and helpful feedback and greatly appreciated. This is on the radar of the product team. I am closing this one out but feel free to re-open if there is something more. Thanks!
