### ISSUE TITLE
Update link to youtube vide for "To learn more about the details on the media path that is chosen..."

### ISSUE THREAD

**Issue by d1bjo0** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1744]
Consider updating the YouTube video reviewing media flows to the more recent Ignite 2018 session at https://www.youtube.com/watch?v=1tmHMIlAQdo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c84773-337e-9df7-7fbd-fc9d94280711
* Version Independent ID: 223a78a0-67fd-8b96-be3f-153bb400101b
* Content: [Microsoft Teams Online Call Flows](https://docs.microsoft.com/en-us/microsoftteams/microsoft-teams-online-call-flows#feedback)
* Content Source: [Teams/microsoft-teams-online-call-flows.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/microsoft-teams-online-call-flows.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@d1bjo0 Thank you for pointing this out and helping improve MS docs.  I'll have a look and have the changes implemented soonest.

**Comment by scanum** [comment]
@d1bjo0 Thank you for submitting this feedback.

From our understanding, the issue has been resolved and Lindsay has updated the link. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
