### ISSUE TITLE
Has the cmdlet New-CsTeamsInteropPolicy been removed from the SfB Online module? What is then the alternative to create new custome Teams Interop policies without this cmdlet?

### ISSUE THREAD

**Issue by rrgonzalezz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#175]
I cannot create a new custom Teams Interop Policy as described in the guide. Whenever I try to create a new Teams Interop Policy I get the following error message: "New-CsTeamsInteropPolicy : The term 'New-CsTeamsInteropPolicy' is not recognized as the name of a cmdlet, function, script file or operation program."

Additionally, I do not see the cmdlet listed under the Skype PowerShell reference: https://docs.microsoft.com/en-us/powershell/module/skype/?view=skype-ps

However, the cmdlets Get-CsTeamsInteropPolicy and Grant-CsTeamsInteropPolicy are available and work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8354e80d-02da-7f51-a713-e698322e8ec1
* Version Independent ID: ef42d9af-336a-e014-de0a-b7bf7bb1f87d
* Content: [Quick start guide - Configuring Calling Plans in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/configuring-teams-calling-quickstartguide)
* Content Source: [Teams/configuring-teams-calling-quickstartguide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/configuring-teams-calling-quickstartguide.md)
* Service: **msteams**
* GitHub Login: @arachmanGitHub
* Microsoft Alias: **MyAdvisor**

**Comment by tonysmit** [comment]
Hi and thanks for the feedback. Here is a response from the PG.

There is no need to create a new instance of TeamsInteropPolicy. All the necessary instances are already created. Also, we are retiring TeamsInteropPolicy and at this point only 3 instances of TeamsInteropPolicy are supported to be granted.
• DisallowOverrideCallingDefaultChatDefault
• DisallowOverrideCallingSfbChatSfb
• DisallowOverrideCallingTeamsChatTeams

Going forward TeamsUpgradePolicy replaces TeamsInteropPolicy. During the transition, customers should set both InteropPolicy and UpgradePolicy.

These basics are explained here: https://docs.microsoft.com/en-us/powershell/module/skype/grant-csteamsinteroppolicy?view=skype-ps. Shortly we’ll also add docs for TeamsUpgradePolicy.

Hope this helps. Tony
