### ISSUE TITLE
Confusing in Dubai

### ISSUE THREAD

**Issue by Strick1969** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1753]
[Enter feedback here]
https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-india

We say that the TF numbers are available, but also that they are NOT available???? 

Toll and toll-free numbers for services

Are toll numbers available? | No 
-- | --
Are toll-free numbers available? | Yes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a570df73-ffc3-73cd-a5aa-0fc1cd8b9fae
* Version Independent ID: 796b055c-3952-ecde-a8dd-873ad1c0a73d
* Content: [Availability in the United Arab Emirates (UAE)](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-arab-emirates-uae)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-arab-emirates-uae.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-arab-emirates-uae.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Hello,

Thanks for your feedback.  Can you please clarify:  Is this comment about availability in India or the United Arab Emirates (UAE)?

**Comment by Strick1969** [comment]
Apologies, mutli-tasking 😊

UAE

We say no Toll numbers are available, but that toll-free are. Its very confusing to the customer



Very Respectfully,

Duane S Friedlander
Premier Field Engineer
Office 365 | SKype | Teams
Email: duane.friedlander@microsoft.com<mailto:duane.friedlander@microsoft.com>
Office: 954-308-4349

[Logo_test][SummitAward_2018-OutlookSign]


                                Need Help Now?
Call Microsoft Premier Support 24x7x365: +1 800 936 3100
       Premier Online: https://premier.microsoft.com<https://premier.microsoft.com/>

**Comment by CarolynRowe** [comment]
Thanks for the clarification.  It sounds like there is confusion about the definition of toll and toll-free.  This is standard terminology, but we will consider adding a definition.
