### ISSUE TITLE
Showing "指定可能な****設定" (Markdown notation) 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1757]
https://docs.microsoft.com/ja-jp/skypeforbusiness/optimizing-your-network/security-guide-for-skype-for-business-online

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 283fb363-d163-1d92-ef82-41d35e8206d3
* Version Independent ID: 0fc4982a-91de-b60f-9170-c4cb4579842b
* Content: [Skype for Business Online セキュリティ ガイド](https://docs.microsoft.com/ja-jp/skypeforbusiness/optimizing-your-network/security-guide-for-skype-for-business-online)
* Content Source: [Skype/SfbOnline/optimizing-your-network/security-guide-for-skype-for-business-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/optimizing-your-network/security-guide-for-skype-for-business-online.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@OfficeGlobal

**Comment by scanum** [comment]
@hyoshioka0128  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
