### ISSUE TITLE
"テナント リモート パワーシェル" needs to be replaced with "Tenant Remote PowerShell"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1758]
https://docs.microsoft.com/ja-jp/skypeforbusiness/optimizing-your-network/security-guide-for-skype-for-business-online

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 283fb363-d163-1d92-ef82-41d35e8206d3
* Version Independent ID: 0fc4982a-91de-b60f-9170-c4cb4579842b
* Content: [Skype for Business Online セキュリティ ガイド](https://docs.microsoft.com/ja-jp/skypeforbusiness/optimizing-your-network/security-guide-for-skype-for-business-online)
* Content Source: [Skype/SfbOnline/optimizing-your-network/security-guide-for-skype-for-business-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/optimizing-your-network/security-guide-for-skype-for-business-online.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@OfficeGlobal Could you please check and advise? Thanks

**Comment by kenwith** [comment]
@officeglobal test

**Comment by lindspea** [comment]
Test.

**Comment by lindspea** [comment]
Test @OfficeGlobal

**Comment by OfficeGlobal** [comment]
related issue #1757
___
@samanthaw Working on a fix (Bug 3233087)

**Comment by scanum** [comment]
@OfficeGlobal Any updates on this? Thanks

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 Article has been HumanTranslated and published live

**Comment by lindspea** [comment]
@scanum this can be closed once merged.

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
Close #1758
