### ISSUE TITLE
"*ブロードキャストです officeapps.live.com。" needs to be replaced with "*broadcast.officeapps.live.com" 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1759]
https://docs.microsoft.com/ja-jp/skypeforbusiness/plan-your-deployment/clients-and-devices/minimum-network-requirements

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2f2b4ce6-d23b-2320-3064-f4537f2736b8
* Version Independent ID: e504bb96-92c3-fde7-3535-1409db82d477
* Content: [Skype 会議アプリの最小ネットワーク要件](https://docs.microsoft.com/ja-jp/skypeforbusiness/plan-your-deployment/clients-and-devices/minimum-network-requirements?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/minimum-network-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/minimum-network-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by OfficeGlobal** [comment]
@samanthaw We're working on a fix (Bug 3232882)

**Comment by OfficeGlobal** [comment]
@samanthaw , @hyoshioka0128  The article has been HumanTranslated and published live. The issue is fixed

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
Close #1759
