### ISSUE TITLE
conferenceid

### ISSUE THREAD

**Issue by gwjsmith** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#176]
resetConferenceId does not work. when setting the conference ID. All you need is conferenceID.

should be.... set-CsOnlineDialinConferencingUser -identity "user.name" -conferenceID

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04f02841-8def-d3af-f4bf-cd92654b6364
* Version Independent ID: bf92954c-cc85-d5a7-f190-0636467a2490
* Content: [See, change, and reset a conference ID assigned to a user](https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/see-change-and-reset-a-conference-id-assigned-to-a-user)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/see-change-and-reset-a-conference-id-assigned-to-a-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/see-change-and-reset-a-conference-id-assigned-to-a-user.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by tonysmit** [comment]
Hi and thank you for the feedback. I have created a work item to begin fixing this issue. Thanks, Tony

**Comment by kenwith** [comment]
@gwjsmith - The cmdlet recently had some addition information added. In particular:

ConferenceId and ResetConferenceId are mutually exclusive. When ConferenceId is specified the new ConferenceId will be assigned to the user. When ResetConferenceId is specified, the user will get an auto-generated ConferenceId.

Which shows up under the ConferenceId parameter. Here is the link to the source: https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineDialInConferencingUser.md

I am not a SME in this area but can help track down. Does the article you mentioned still need to be fixed or is it correct based on the information in the cmdlet?

Sorry for the long delay on this.

**Comment by kenwith** [comment]
I believe the work item Tony created solved this but if there is still an issue in the documentation please re-open. Thanks for taking the time on this!
