### ISSUE TITLE
Issues with Guest Access via iPhone

### ISSUE THREAD

**Issue by nikitache** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1760]
Hi! We have set up guest access for some of the users. Android users can access the Team normally but iPhone users are not able to access it. Guests have access to the team and team's planner. They are able to access Teams from iPhone, but when then need to open the planner (added as a tab to the channel), the Planner app would open neither in browser nor in the app. Have you encountered this issue before?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2492e210-08f9-a476-97ec-008926def961
* Version Independent ID: adcb0dd9-4a3c-b665-6e34-ce3276c89b4d
* Content: [Guest access in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-access)
* Content Source: [Teams/guest-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access.md)
* Service: **msteams**
* GitHub Login: @somakbhattacharyya
* Microsoft Alias: **sbhatta**

**Comment by scanum** [comment]
@nikitache  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
