### ISSUE TITLE
End of life date has been extended to 1st April 2020

### ISSUE THREAD

**Issue by alexlushsevernunival** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1761]
End of life date has been extended to 1st April 2020 as communicated in Message Centre post MC175441. All references to 1st April 2019 need updating to 1st April 2020.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 411be1af-0377-1d2c-0d07-04edb445a42a
* Version Independent ID: 5ad12387-b987-6cda-8c56-052c79274f2c
* Content: [End of life program for the integration of Skype for Business with third-party audio conferencing providers ](https://docs.microsoft.com/en-us/skypeforbusiness/legal-and-regulatory/end-of-integration-with-3rd-party-providers#feedback)
* Content Source: [Skype/SfbOnline/legal-and-regulatory/end-of-integration-with-3rd-party-providers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/legal-and-regulatory/end-of-integration-with-3rd-party-providers.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@alexlushsevernunival thank you for pointing this out and helping improve MS docs.  I will have it fixed as soon as possible.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by scanum** [comment]
@alexlushsevernunival  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.
