### ISSUE TITLE
Teams only mode

### ISSUE THREAD

**Issue by rossual** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1762]
The teams only mode scenarios don;t seem accurate in the upgrade modes table. comments in {}
They are:

Some users need to stay on Skype for Business {Teams only does not satisfy this}

You’re upgrading your Skype for Business Online users to Teams while keeping Skype for Business on-premises users on Skype for Business Server {Teams only does not satisfy this}

You might have already deployed users in islands mode and are ready to retire Skype for Business for groups of users {Valid}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 006dc464-2228-0d91-8726-223770c91411
* Version Independent ID: 28877a22-b558-4da6-551b-9bcd9bac96c4
* Content: [Microsoft Teams upgrade from Skype for Business](https://docs.microsoft.com/en-us/microsoftteams/upgrade-and-coexistence-of-skypeforbusiness-and-teams)
* Content Source: [Teams/upgrade-and-coexistence-of-skypeforbusiness-and-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-and-coexistence-of-skypeforbusiness-and-teams.md)
* Service: **msteams**
* GitHub Login: @lsOmi
* Microsoft Alias: **lsomi**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@rossual Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@rossual Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by jdimeglio** [comment]
We have the same problem as users above - ie; we need to get coexistence modes option enabled and fast. How do we do that?
