### ISSUE TITLE
If you do NOT want Teams as an option when creating meetings in Outlook mobile then you must disable Teams for the entire organization.

### ISSUE THREAD

**Issue by systopher** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1767]
Recent enhancement message links to this page when referring to disabling Teams at the org level, but this page shows that disabling access is only possible at the user level.

"If you do NOT want Teams as an option when creating meetings in Outlook mobile, even if select users are enabled for Teams, then you must disable Teams for the entire organization. Please see Additional Information for details on managing user access."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cccdd91a-7f05-abd5-ed94-e82152b86914
* Version Independent ID: 3532d0a8-119c-f7d0-0d4f-a865ad32570f
* Content: [Manage user access to Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/user-access#feedback)
* Content Source: [Teams/user-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/user-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@systopher Thank you for reaching out.  Please could you elaborate where the change should be made.  It's a bit unclear.

**Comment by scanum** [comment]
@systopher We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
