### ISSUE TITLE
admin center name is wrong

### ISSUE THREAD

**Issue by wstaelens** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1776]
In the section "Enable business-to-business communications for your users". There you have in step 2 "In the Office 365 admin center, go to Admin Centers &gt; Skype for Business".

I don't see this. I need to click "Teams". and in Teams i need to click on "Legacy Portal" behind the skype icon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee122b1c-c1c6-bb32-38db-a7f7c52c1f28
* Version Independent ID: 1f335848-baeb-9396-f753-8f72017447ce
* Content: [Allow users to contact external Skype for Business users](https://docs.microsoft.com/en-us/SkypeForBusiness/set-up-skype-for-business-online/allow-users-to-contact-external-skype-for-business-users)
* Content Source: [Skype/SfbOnline/set-up-skype-for-business-online/allow-users-to-contact-external-skype-for-business-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-skype-for-business-online/allow-users-to-contact-external-skype-for-business-users.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@wstaelens Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
