### ISSUE TITLE
Poor documentation on Skype Plan 1 vs 2

### ISSUE THREAD

**Issue by knssub** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#178]
There is no comparison of Skype Plan 1 vs 2, to understand what is the difference and how partners can build services and offer various solutions. It took me over 15 mins and yet to find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 390e7a34-ce99-5641-3007-9ab2afd3b2b8
* Version Independent ID: 5e2a796d-6377-a40b-7dbe-c75d40f73ab1
* Content: [Office 365 Premium, Office 365 ProPlus, or Skype for Business Online Plan 2](https://docs.microsoft.com/en-us/SkypeForBusiness/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/office-365-premium-pro-plus-or-business-online-plan)
* Content Source: [Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/office-365-premium-pro-plus-or-business-online-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/office-365-premium-pro-plus-or-business-online-plan.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by tonysmit** [comment]
Hi and thank you for the feedback. I have created a work item to begin fixing this issue. Thanks, Tony

**Comment by tonysmit** [comment]
Hi and thank you for the feedback. I have created a work item to begin fixing this issue. Thanks, Tony

**Comment by kenwith** [comment]
@knssub - as Tony mentioned this is in the backlog for the writing team and they will update here once fixed. Thanks for your feedback and sorry for the long delay.

**Comment by scanum** [comment]
@tonysmit Any updates on this issue? Thanks!

**Comment by tonysmit** [comment]
@knssub - SFB Plan 1 doesn't allow any cloud voice features, so we focus on SP2 because of this. For some Business plans you can add SP2 then add voice features to it, however, we recommend upgrading to an E3/E5 plan because you will end up with more features that SP2 and it may cost less in the long run depending on what you are adding to SP2.
