### ISSUE TITLE
Which SBCs are being reviewed now for possible/probably inclusion in the list?

### ISSUE THREAD

**Issue by uttampcu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1782]
Cisco is one of the most popular, is it being reviewed for possible/probable inclusion in the list of certified SBCs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1a1c01-10a9-7f69-1c7b-1a566b0f5112
* Version Independent ID: 329ee759-40fc-98fb-b91e-87786c63024b
* Content: [List of Session Border Controllers certified for Direct Routing](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-border-controllers#feedback)
* Content Source: [Teams/direct-routing-border-controllers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-border-controllers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by CarolynRowe** [comment]
Thank you for your feedback.  This article is updated as soon as a new vendor is certified so please check back often.  However, we are not able to comment on certifications in process in this forum.
