### ISSUE TITLE
Add note under conferencing support that viewing embedded video in PPT isn't supported.

### ISSUE THREAD

**Issue by NicholasBurkhammer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1789]
This isn't supported in Skype for Business on Android or iOS per RFC to PG.  Recommend adding a circle with number 3 next to "View shared PowerPoint files" with a note that states, "Viewing embedded video in PowerPoint presentations is not supported."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 257dc4a1-8091-23db-64c4-f46b0519e14e
* Version Independent ID: c5094b34-c69d-9e8d-40cb-9197b924e632
* Content: [Mobile client feature comparison for Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/mobile-feature-comparison)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/mobile-feature-comparison.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/mobile-feature-comparison.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
@PhillipGarding can you please comment?

**Comment by NicholasBurkhammer** [comment]
Let me know if you need the RFC URL for reference.  Happy to provide it.

Regards,

Nicholas Burkhammer
Microsoft ● Unified Communications ● Support Escalation Engineer
Email: nichburk@microsoft.com<mailto:nichburk@microsoft.com>
Phone: +1 980-776-2946
Hours: Monday-Friday 0900-1800 ET
Manager ● Craig Fischer ● mailto:Craig.Fischer@microsoft.com

[SummitAward_2018-OutlookSign]

**Comment by PhillipGarding** [comment]
This is correct.  Viewing of video embedded in an uploaded PowerPoint presentation is not supported on iOS and Android.  Please update the documentation appropriately.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@NicholasBurkhammer Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
