### ISSUE TITLE
Billing clarification for EA customers

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1790]
It isn't clear how an EA customer would get billed. As we have to purchase this separately our reseller wasn't able to advise either.
When I go to the final step of the checkout it already has my EA number selected and an empty box for a purchase order number. Does this mean I will get a separate monthly/quarterly/annual invoice just for the spent credits (with the relevant PO number listed) or it will come through as part of the annual true-up/reservation invoice (in which case the PO would be ignored)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 277cf140-5c6c-82c7-cc56-490ef2188754
* Version Independent ID: 72e7de29-fd71-23bf-15a7-172634c2a5fd
* Content: [Set up Communications Credits for your organization](https://docs.microsoft.com/en-us/microsoftteams/set-up-communications-credits-for-your-organization)
* Content Source: [Teams/set-up-communications-credits-for-your-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-communications-credits-for-your-organization.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@thommck Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

@officedocsbot close
