### ISSUE TITLE
Powershell

### ISSUE THREAD

**Issue by tsylvia88** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1791]
How do you assign an emergency location via powershell?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e880ddd3-f279-7293-dbd0-cabce392de31
* Version Independent ID: 7b2d414e-4f05-f744-fddf-965fedfb0349
* Content: [Assign or change the emergency location for a user](https://docs.microsoft.com/en-us/skypeforbusiness/what-are-calling-plans-in-office-365/change-the-emergency-location-for-a-user#feedback)
* Content Source: [Skype/SfbOnline/what-are-calling-plans-in-office-365/change-the-emergency-location-for-a-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/what-are-calling-plans-in-office-365/change-the-emergency-location-for-a-user.md)
* Service: **skype-for-business-online**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by CarolynRowe** [comment]
Please see the following:  https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinevoiceuser?view=skype-ps 

We will update the emergency location article to include a link to the cmdlet description.

**Comment by scanum** [comment]
@tsylvia88 Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

@officedocsbot close
