### ISSUE TITLE
Intune conditional access and Exchange Online and Teams.

### ISSUE THREAD

**Issue by zaicnupagadi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1793]
Hey all, when applying conditional access on Exchange Online application the same applies on Teams - when having only Teams on phone need to install company portal, I understand this is because there are some interactions between these two applications, but it is definitely worth mentioning that when applying policy to one of these apps - the other one will also be restricted with conditional access even if not explicitly and directly defined within the rule.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact](https://docs.microsoft.com/en-us/MicrosoftTeams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@zaicnupagadi  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

@officedocsbot close
