### ISSUE TITLE
Typo in heading for "Plan or media byass with Direct Routing"

### ISSUE THREAD

**Issue by moreaboutmatt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1794]
Typo in heading for "Plan or media byass with Direct Routing"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10b198f4-9576-a14d-4359-1e8cc0319cda
* Version Independent ID: ba7c3252-21d4-9be1-2a84-de2d51646f7b
* Content: [Plan for media bypass with Direct Routing](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan-media-bypass#requirements-for-direct-media-traffic-between-the-teams-client-and-the-sbc)
* Content Source: [Teams/direct-routing-plan-media-bypass.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan-media-bypass.md)
* Service: **msteams**
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Hello, I am looking at the live file and not seeing the typo.  Both the title and the TOC say Plan for...   Can you be more specific about where you're seeing this problem?

**Comment by moreaboutmatt** [comment]
Hi Carolyn,

Here's a pic of the typo:

[image: image.png]

Thanks...

Matt

**Comment by CarolynRowe** [comment]
This is fixed.
