### ISSUE TITLE
Need Easier Way To Exclude Groups

### ISSUE THREAD

**Issue by jaypatrick** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1804]
In any non-trivial AD deployment, there are going to be hundreds (or even thousands) of types of users who shouldn't be auto-added to the org-wide channel, so there needs to be an easy way to exclude them. For example, we use MAC based authentication accounts, and we put them in a group. These accounts should not be added to Teams, and as it is now, we have to delete them one by one. A mechanism to exclude AD groups needs to be added to make this even remotely useful, otherwise we are flooded by accounts that dont need to be there. Same thing for service accounts, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by gerybtiscca** [comment]
I may add that, through Azure AD Connect, disabled users are also added to the team, which is very annoying.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@jaypatrick Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

@officedocsbot close

**Comment by erlendwtf** [comment]
How has this been solved?

**Comment by scanum** [comment]
@sukihanabi updated the doc by adding the following: 

**Action Taken:**

- added reference to uservoice

Analysis:
-The answer to user question might not be available to the public because for the devices to be certified and be part of SBC, MS needs to perform an intense test.
-But it was indicated on the article: " If you have any questions about SBC certification program for Direct Routing please email to drsbccertification@microsoft.com"
-Can we instead direct the user to email the support or perhaps a uservoice?

**Comment by scanum** [comment]
We think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

Also, I know the product teams are always looking for user feedback and how to make Skype for Business better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://www.skypefeedback.com.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
