### ISSUE TITLE
"セット CsTeamsMessagingPolicy" needs to be replaced with "Set-CsTeamsMessagingPolicy"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1808]
https://docs.microsoft.com/ja-jp/microsoftteams/inline-message-translation-teams

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 19e91f77-0c01-5d38-0bd4-65ee44aab5cb
* Version Independent ID: 08ea83b3-c241-979c-3afb-3355ab322489
* Content: [Microsoft Teams でインライン メッセージの翻訳を使用する](https://docs.microsoft.com/ja-jp/microsoftteams/inline-message-translation-teams)
* Content Source: [Teams/inline-message-translation-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/inline-message-translation-teams.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@officedocsbot assign @OfficeGlobal

**Comment by scanum** [comment]
@officeglobal could you please take a look at this? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 Article has been HumanTranslated and published live. The issue is fixed

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
Close #1808
