### ISSUE TITLE
"%Appdata%\Microsoft\チーム" needs to be replaced with "%Appdata%\Microsoft\Teams"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1810]
https://docs.microsoft.com/ja-jp/microsoftteams/get-clients

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Microsoft Teams のクライアントを取得する](https://docs.microsoft.com/ja-jp/microsoftteams/get-clients)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @officeglobal

**Comment by scanum** [comment]
@officeglobal could you please take a look at this? Thanks!

**Comment by OfficeGlobal** [comment]
Article has been HumanTranslated and published live. The issue is fixed

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
Closed #1810
