### ISSUE TITLE
Licensing requirements appear incorrect or misleading

### ISSUE THREAD

**Issue by manderson97** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#182]
The title of the article - including Office 365 Pro Plus - seems to imply that Audio Conferencing can be added for customers who only have Office 365 Pro Plus.  I believe that is incorrect - that minimally Skype Online Plan 2 is required. 

Although obviously if they want to use the Skype client - they'll need O365 Pro Plus (or Office Pro Plus w/ Skype).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 390e7a34-ce99-5641-3007-9ab2afd3b2b8
* Version Independent ID: 5e2a796d-6377-a40b-7dbe-c75d40f73ab1
* Content: [Office 365 Premium, Office 365 ProPlus, or Skype for Business Online Plan 2](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/office-365-premium-pro-plus-or-business-online-plan)
* Content Source: [Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/office-365-premium-pro-plus-or-business-online-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/office-365-premium-pro-plus-or-business-online-plan.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@manderson97 - as Tony mentioned this is in the backlog for the writing team. Thanks for taking the time to provide this feedback and make the docs clearer. The writer will update this issue when clarifications and made on the article.
