### ISSUE TITLE
Pay per minute charge

### ISSUE THREAD

**Issue by pik10** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1820]
How does pay per minute charge work?
Let's say I organize a conference with 5 participants.  Would I pay per minute for the conference line or pay per minute times 5 participants?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fac515b-9c6b-c70c-330e-53557dc23fd2
* Version Independent ID: d515841e-f412-286d-1a97-30507bb50040
* Content: [Audio Conferencing pay-per-minute](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-pay-per-minute#feedback)
* Content Source: [Teams/audio-conferencing-pay-per-minute.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-pay-per-minute.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@pik10 Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

@officedocsbot close
