### ISSUE TITLE
Uniqueness violation

### ISSUE THREAD

**Issue by wakeyyc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1831]
![error](https://user-images.githubusercontent.com/5334832/54565628-63cede80-4994-11e9-9986-4d3e60dc8690.png)

I keep getting this error on step 7. Everything else works fine and I'm able to login but I can't get this step to work.

**Comment by wakeyyc** [comment]
https://docs.microsoft.com/en-us/skypeforbusiness/deploy/integrate-with-exchange-server/oauth-with-online-and-on-premises#feedback 

when doing step 7

**Comment by jambirk** [comment]
which version of Active Directory do you have? if you've imported AzureAD 2.0 I would expect the commands to fail.  The procedure assumes AzureAD 1.0, https://docs.microsoft.com/en-us/powershell/module/?view=azureadps-1.0

**Comment by wakeyyc** [comment]
> which version of Active Directory do you have? if you've imported AzureAD 2.0 I would expect the commands to fail. The procedure assumes AzureAD 1.0, [https://docs.microsoft.com/en-us/powershell/module/?view=azureadps-1.0 ](https://docs.microsoft.com/en-us/powershell/module/?view=azureadps-1.0%C2%A0)

I'm using 1.0, I already noticed that you must be using 1.0 for this.

**Comment by jambirk** [comment]
You may need to file a support ticket then, sorry.

**Comment by scanum** [comment]
@wakeyyc  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
