### ISSUE TITLE
Tenant settings not understood by the Teams client

### ISSUE THREAD

**Issue by piqueora** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1832]
Hello
Our tests show that the tenant settings for the Teams Upgrade Policy are currently not well understood by the current Teams client. 
For example if the tenant is in SfBOnly mode, the Teams client will continue to send its IM to the Teams client instead of the Sfb client, so that this IM will be lost.
If this explicit setting is set on the user, the Teams client processes it correcly, so that an IM from Teams will reach the SfB client.
This is the workaround we use, the tenant is for information only, but as it is not currently reliable, we also set explicit settings for all users, including SFB on-premises.
We still have to check if other Teams devices, such as IP-Phones or web browsers, have this same bug than the desktop client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49921e8a-55ac-f547-d4e2-d329f5089c2e
* Version Independent ID: 91c3433a-3684-95cd-3426-4a5877b33106
* Content: [Migration and interoperability guidance for organizations using Teams together with Skype for Business](https://docs.microsoft.com/en-us/microsoftteams/migration-interop-guidance-for-teams-with-skype#feedback)
* Content Source: [Teams/migration-interop-guidance-for-teams-with-skype.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/migration-interop-guidance-for-teams-with-skype.md)
* Service: **msteams**
* GitHub Login: @arachmanGitHub
* Microsoft Alias: **MyAdvisor**

**Comment by scanum** [comment]
@piqueora - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
