### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by ivanja81** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1837]
Can you make an extra note that when adding servers to the pool the admin must deploy the server immediately and run bootstrapper? You can't add servers and not deploy wizard. It seems a bit confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8480732-de6a-92b0-2c9f-4cc1eba51c08
* Version Independent ID: 3ea7d917-2ba3-77f1-9f8f-31b0e5d430ea
* Content: [Manage Front End Servers in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/manage/topology/manage-front-end-servers)
* Content Source: [Skype/SfbServer/manage/topology/manage-front-end-servers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/topology/manage-front-end-servers.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @ivanja81 
Thanks for your feedback.
I created a Pull Request to improve the article based on your comments.
Thank you

**Comment by scanum** [comment]
@ivanja81  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
