### ISSUE TITLE
Option #1 for Starting a meeting when using a phone to dial-in

### ISSUE THREAD

**Issue by netlander1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1839]
We are being told by Microsoft Tech Support that option #1, for starting a meeting when using a phone to dial in, is not supported. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad892c60-f7e4-0790-66f7-219d28f44ee6
* Version Independent ID: 36e86cca-c5a3-eb4d-477e-1fb7b0b5d7f1
* Content: [Audio Conferencing common questions](https://docs.microsoft.com/en-us/MicrosoftTeams/audio-conferencing-common-questions)
* Content Source: [Teams/audio-conferencing-common-questions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-common-questions.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by tonysmit** [comment]
@netlander1 - In Teams, go to **Meetings** > **Meeting policies** > under **Participants and guests** > select **Allow people that dial in to start a meeting**.
