### ISSUE TITLE
First party vs third party

### ISSUE THREAD

**Issue by tmaheshwar** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1840]
First party templates are these going to appear via General Tab, which are 3rd party Templates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb17d752-d62d-1d41-fa98-5eafe2c057d9
* Version Independent ID: 3ced31b7-2ac5-e140-b848-f97eee63a52f
* Content: [Get started with Teams templates for Healthcare organizations](https://docs.microsoft.com/en-us/microsoftteams/healthcare/healthcare-templates#feedback)
* Content Source: [Teams/healthcare/healthcare-templates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/healthcare/healthcare-templates.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@tmaheshwar  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

@officedocsbot close

**Comment by BakerTeams** [comment]
IS there a step by step guide for the templates. I have been trying to get them to import using powershell and cannot get it.
