### ISSUE TITLE
MFA 

### ISSUE THREAD

**Issue by joaoalhinho** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1842]
If the admin account is MFA enabled (Hybrid Modern Auth) you can't bypass the credentials in a variable. Correct move Cmdlet will be 
Move-CsUser -Identity username@contoso.com -Target sipfed.online.lync.com -HostedMigrationOverrideUrl $url

In that way a login window will appear to enter credentials and 2nd factor. Please update the manual. Thks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40129d20-5ce3-8f23-90a3-490e4d3498bb
* Version Independent ID: 6104ec9f-c48a-f6a2-6d78-af6f58fe493e
* Content: [Move users from on premises to Skype for Business Online](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/move-users-from-on-premises-to-skype-for-business-online#feedback)
* Content Source: [Skype/SfbHybrid/hybrid/move-users-from-on-premises-to-skype-for-business-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/move-users-from-on-premises-to-skype-for-business-online.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@joaoalhinho Thank you for submitting feedback. We understand that this issue has been resolved. 
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by tiagoroxo** [comment]
The same problem can be found in the other way around document to move the users from online to on-premises.

**Comment by anuanumula** [comment]
As mentioned above, when we dont specify credential parameter for the accounts with MFA it should show a window to enter the credentials, but it does not show any window for me prompting for credentials and I am receiving the error for:
"Move-CsUser -Identity <UserSIPid> -Target sipfed.online.lync.com -HostedMigrationOverrideUrl $url"
as 
Move-CsUser : Object reference not set to an instance of an object.
