### ISSUE TITLE
How to create user cohorts?

### ISSUE THREAD

**Issue by nicknow** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1843]
Under Upgrade Users in Stages under Step 1 it says "To create your user cohorts (Add link to user selection page)" but there is no more information on how to create user cohorts.

It does not appear that you can create any type of user cohort or groups to apply the Teams Upgrade policies too, that they must be applied per-user or org-wide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e763c267-2c3a-190d-29e2-b5c81448fc10
* Version Independent ID: 98b73595-54ea-503c-ac3c-9df176543e9e
* Content: [Upgrade Skype for Business Online to Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/upgrade-to-teams-execute-skypeforbusinessonline#feedback)
* Content Source: [Teams/upgrade-to-Teams-execute-SkypeforBusinessOnline.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-to-Teams-execute-SkypeforBusinessOnline.md)
* Service: **msteams**
* GitHub Login: @arachmanGitHub
* Microsoft Alias: **arachman**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@nicknow Thank you for reaching out.  Please let me know if these steps should be added to the article, and if they will help.
    Step 1: Create your user cohorts for the upgrade. 
    Step 2: Set the user mode to Islands. 
    Step 3: Set notification for the user (optional) 
    Step 4: Set the user mode to Teams Only.

**Comment by scanum** [comment]
@nicknow  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
