### ISSUE TITLE
New announcements

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1845]
Given the announcements on Legal Hold here: https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/What-s-new-in-Microsoft-Teams-the-Enterprise-Connect-feature/ba-p/376255 I think this page requires a content update on legal hold with Exchange on-prem, if it indeed applies as the linked article suggests. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by thedrum808** [comment]
Link has since been updated to reflect features are coming soon. Please close.

**Comment by scanum** [comment]
@thedrum808 Thank you for submitting feedback! We strongly appreciate your inputs. Please keep contributing to the docs.

@officedocsbot close
