### ISSUE TITLE
eDiscovery of guest-to-guest chats how-to?

### ISSUE THREAD

**Issue by MaximAeon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1846]
Thank you for pointing out that there is a mechanism to index guest-to-guest chats. Would it be possible to provide content that shows how to configure AAD Guest accounts so their chats go to cloud/phantom mailbox?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 840dd36b-8c29-9738-4adc-ea9a7d277fd0
* Version Independent ID: b12c43c3-ed81-ace5-dfeb-77cac0f97fe9
* Content: [Conduct an eDiscovery investigation of content in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/ediscovery-investigation#feedback)
* Content Source: [Teams/eDiscovery-investigation.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/eDiscovery-investigation.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @MaximAeon 

Thanks for reaching out!

See this article for adding the guest users to the directory

https://docs.microsoft.com/azure/active-directory/b2b/add-users-administrator

And for more details on the cloud-based storage and it's features please refer to the below article. 

https://docs.microsoft.com/office365/securitycompliance/search-cloud-based-mailboxes-for-on-premises-users

Hope this information helps you. Kindly confirm. Thank you.

**Comment by MaximAeon** [comment]
> Hi @MaximAeon
> Thanks for reaching out!
> See this article for adding the guest users to the directory
> https://docs.microsoft.com/azure/active-directory/b2b/add-users-administrator
> And for more details on the cloud-based storage and it's features please refer to the below article.
> https://docs.microsoft.com/office365/securitycompliance/search-cloud-based-mailboxes-for-on-premises-users
> Hope this information helps you. Kindly confirm. Thank you.

My apologies but I'm not sure what these links have to do with implementing the suggested Exchange method for capturing Guest-to-Guest chats in Teams?

**Comment by sowjanya365** [comment]
Hi @MaximAeon 

Thank you for your response. The second URL explains how the Guest to Guest chats are stored. Please refer to it and let us know if you are still looking for any clarification. Please include detailed information if you are looking for any particular scenario. This would help us to understand it more clear and assist you with the proper response. 

Looking forward to your confirmation. Thank you.

**Comment by scanum** [comment]
@MaximAeon  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by jgoakley** [comment]
I think this issue should be re-opened.

sssseossss is correct that the second URL provided by sowjanya365 does not mention guest accounts at all and only mentions cloud-based mailboxes in the context of syncing on-premise accounts to the cloud.

The section titled "eDiscovery of guest-to-guest chats" is self contradicting because it states:

> "Presently, for a scenario where only guests are participating in 1:1 or 1:N chat, we don't support eDiscovery of those chat messages. Without a mailbox, guest-to-guest chats (1xN chats in which there are no home tenant users) would not be indexed, and as a result, would not be included in eDiscovery."

And then immediately following states:

> "To facilitate eDiscovery for guest-to-guest chats, a cloud-based mailbox (or phantom mailbox) is created to store the 1xN data. After the Teams chat data is stored in the cloud-based mailbox, it is indexed for eDiscovery and compliance content search."

From the text it is unclear what steps, if any, can or need to be taken to enable eDiscovery of guest-to-guest chats.

Thanks!

**Comment by dariomws** [comment]
Hi @jgoakley, thank you for your feedback.

This article was updated 3 days ago and now we only have this note about "guest-to-guest chats":
"At this time, we don't support eDiscovery of chat messages in scenarios where guest users are the only participants in a 1:1 or 1:N chat. These types of chats are also called guest-to-guest chats because they don't include home tenant users."

**Comment by markdepalma** [comment]
The current version of this article does not mention this anymore. What is the current status of this?

**Comment by dariomws** [comment]
Hi @markdepalma,

This information was removed in April so I think it´s supported now.

@mattpennathe3rd and @hakankes could you kindly help me to confirm this? Thanks!

**Comment by dariomws** [comment]
Hi @markjjo,

Could you kindly help us to confirm this information? It seems that this note was removed here:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/4c4048d14fa2b339965cd3d1c8cc0aa4f4150304#diff-5f074cf81d8b3992324c2d03f0205e34eb66312414e30355fbbd333460b42ed0

**Comment by markjjo** [comment]
@dariomws What specifically are you asking about?

**Comment by dariomws** [comment]
@markjjo the following note you added on March was removed on April. Do you think we should add it back or eDiscovery of *guest-to-guest* chat is fully supported now? Thanks!

> [!NOTE]	
> At this time, we don't support eDiscovery of chat messages in scenarios where guest users are the only participants in a 1:1 or 1:N chat. These types of chats are also called *guest-to-guest* chats because they don't include home tenant users.
