### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Chukaka** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1847]
In the "Teams certified IP phones" section, the link to the "See Currently certified IP Phones for current supported devices." is broken.

Current link it points to:
https://docs.microsoft.com/en-us/SfbPartnerCertification/certification/teams-ip-phones.md#currently-certified-ip-phones?toc=/MicrosoftTeams/toc.json&bc=/microsoftteams/breadcrumb/toc.json

However the one in "See also" at the bottom is working fine and points to the following url so the top one should be adjusted.
https://docs.microsoft.com/en-us/skypeforbusiness/certification/teams-ip-phones?toc=/MicrosoftTeams/toc.json&bc=/microsoftteams/breadcrumb/toc.json

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae4c265a-8df4-647d-fc42-5054e3340c20
* Version Independent ID: 249c7301-9c82-b1c4-8401-54553370302b
* Content: [Phones for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/phones-for-teams#feedback)
* Content Source: [Teams/phones-for-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phones-for-teams.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
The fix for this was implemented earlier today, it just hasn't propagated to the web yet.
