### ISSUE TITLE
The link to this PowerShell reference fails from the main Teams page

### ISSUE THREAD

**Issue by ChrisLGardner** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1848]
On the main Teams overview on Docs (https://docs.microsoft.com/en-gb/MicrosoftTeams/Microsoft-Teams#pivot=home&panel=home-all) the PowerShell link is a 404 (https://docs.microsoft.com/en-gb/powershell/module/teams/?view=teams-ps) and should almost certainly go to this page instead. The suggestions even point to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26362d70-cfce-2eea-077b-4aaa50f92e8b
* Version Independent ID: f52dcd4d-4f58-05c4-11b0-f1e3c95f4d89
* Content: [Teams PowerShell Overview](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-overview#feedback)
* Content Source: [Teams/teams-powershell-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @ChrisLGardner 

Thanks for reaching out!

We see that the issue is resolved now. Link is working fine and taking us to the correct URL. Please check and let us know if there is any issue. Thank you.

**Comment by ChrisLGardner** [comment]
That link now works correctly. 

Thanks
