### ISSUE TITLE
"zh-(香港)" needs to be replaced with "zh-HK"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1852]
https://docs.microsoft.com/ja-jp/MicrosoftTeams/audio-conferencing-supported-languages

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: cd03c696-b6c1-9033-ce8a-dbaf427706b5
* Version Independent ID: 956891fd-7496-cada-d2cb-0b7c6b724db6
* Content: [電話会議でサポートされている言語](https://docs.microsoft.com/ja-jp/MicrosoftTeams/audio-conferencing-supported-languages)
* Content Source: [Teams/audio-conferencing-supported-languages.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-supported-languages.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@Officedocsbot assign @OfficeGlobal

**Comment by scanum** [comment]
@OfficeGlobal Could you please take a look? Thanks!

**Comment by OfficeGlobal** [comment]
The language codes were updated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
Close #1852
