### ISSUE TITLE
Needs a "bolded" statement about no voicemail support

### ISSUE THREAD

**Issue by d1bjo0** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1856]
Common Area Phones do not support voicemail. However this is often missed by customers and creates confusion. Please make a bolded or "important note" statement declaring that there is no support for voicemail. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ab5215-f24f-75cf-bb92-16ac0ff5e5ca
* Version Independent ID: 701cc58f-d2ea-cbb6-f5fc-47b9fbfb1119
* Content: [Set up the Common Area Phone license for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-common-area-phones#feedback)
* Content Source: [Teams/set-up-common-area-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-common-area-phones.md)
* Service: **msteams**
* GitHub Login: @lolaj
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@d1bjo0 Thank you for pointing this out, I'll have it amended as soon as possible.

**Comment by scanum** [comment]
@d1bjo0 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
