### ISSUE TITLE
Private chat limit

### ISSUE THREAD

**Issue by rishire** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1858]
There are some exceptions documented here (Dec 17th 2018)
https://support.office.com/en-us/article/what-s-new-in-microsoft-teams-d7092a6d-c896-424c-b362-a472d5f105de

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#feedback)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@rishire Thank you for pointing that out and helping improve MS Docs.  I'll have the link added to the article soonest.

**Comment by seanyb88** [comment]
Hi is there any plans to increase the Number of people in a private chat Max Limit? We utilize Teams quite heavily for collaboration between multiple sub-teams and are currently having to be selective in not including certain sub teams and/or individuals as we have hit the 50 person limit. Removing the limit and/or increasing to 75-100 would certainly help out.

**Comment by scanum** [comment]
@rishire -  thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
