### ISSUE TITLE
Assigning a meeting policy to a user

### ISSUE THREAD

**Issue by alanbmhs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1859]
Apparently "You can also do this by going to Microsoft Teams admin center &gt; Meetings &gt; Meeting policies. Select the policy and then select Manage users. In the Manage users pane, search for the user by display or user name. Select the name and select Add. When you are finished adding users, select Save." There is no 'Manage users' option available in this view to select.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies](https://docs.microsoft.com/en-US/microsoftteams/meeting-policies-in-teams?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@alanbmhs  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
