### ISSUE TITLE
How to remove a dead device from the Devices management ?

### ISSUE THREAD

**Issue by piqueora** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1863]
All the possible actions described above assume the device is working and online. But this is not the case for one of our phone, which is now full dead and will never be online.
As there is no Delete or Remove action possible on a offline device, how can we remove this dead device from the list of the devices in the GUI ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a627b5d-3edc-1add-b921-1dcd49c38653
* Version Independent ID: a2e2bd3a-31c0-471a-05fb-fd64bd942c4a
* Content: [Manage your devices in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/device-management)
* Content Source: [Teams/device-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/device-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@piqueora  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
