### ISSUE TITLE
device management with cmdlets

### ISSUE THREAD

**Issue by piqueora** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1864]
this page describes the management using the Teams Admin GUI (and there is at least the Delete action which is missing currently: see #1863), but there is no description of what can be managed with other means : cmdlets at least, maybe a Graph API, or any other way (Intune ?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a627b5d-3edc-1add-b921-1dcd49c38653
* Version Independent ID: a2e2bd3a-31c0-471a-05fb-fd64bd942c4a
* Content: [Manage your devices in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/device-management)
* Content Source: [Teams/device-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/device-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by get-itips** [comment]
Hello @piqueora 
**Thanks for your feedback.**

Currently, there is no cmdlet or GraphAPI function to manage devices of Microsoft Teams but I am pretty sure the Team is working on them.
If you want, kindly visit https://microsoftteams.uservoice.com/forums/555103-public to make suggestions.

Thank you

**Comment by scanum** [comment]
@piqueora  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
