### ISSUE TITLE
Missing critical step

### ISSUE THREAD

**Issue by oldkingcolemsscna** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1865]
After step 10, this article should refer the reader to install Skype For Business Server 2019 before proceeding with the "Verify pilot pool..." step.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ec4d122-ff87-2c4b-6caa-299795190dc5
* Version Independent ID: de2481bd-8b21-b5d7-3898-1a4b40d0bfd2
* Content: [Deploy pilot pool](https://docs.microsoft.com/en-us/skypeforbusiness/migration/deploy-pilot-pool#feedback)
* Content Source: [Skype/SfBServer2019/migration/deploy-pilot-pool.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/migration/deploy-pilot-pool.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @oldkingcolemsscna 
Thanks for your feedback, we really appreciate it.
I created a Pull Request to improve the article adding the missing step.
Thank you

**Comment by scanum** [comment]
@oldkingcolemsscna Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

@officedocsbot close
