### ISSUE TITLE
Missing important comments

### ISSUE THREAD

**Issue by oldkingcolemsscna** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1866]
This article should mention that those migrating from Skype For Business Server 2015 should follow the steps under Migrate before installing as a migration does not want to create a new topology

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f4e937-e0cb-bc45-2876-d1f76a33d116
* Version Independent ID: ae02a73f-0968-6bf9-3709-798a5cd66aea
* Content: [Create and publish new topology in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/install/create-and-publish-new-topology?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json)
* Content Source: [Skype/SfbServer/deploy/install/create-and-publish-new-topology.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/install/create-and-publish-new-topology.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @oldkingcolemsscna 
**Thank you to taking the time to submit feedback.**

Actually, this article is for SfB 2015.
If you started browsing content related to SfB 2019 and ended up in this page, this is known issue described here https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/1861 and is currently being taken care of.
Thank You!

**Comment by scanum** [comment]
@oldkingcolemsscna  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
