### ISSUE TITLE
Logo URL

### ISSUE THREAD

**Issue by quickclix75** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1867]
When you configure the Logo URL in the Teams admin center, the example in the field uses .png and I was also able to apply and use a png file.. How strict a rule is the "Remember that it must be in JPG format!" comment above ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Customize meeting invitations in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/customize-meeting-invitations)
* Content Source: [Teams/customize-meeting-invitations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/customize-meeting-invitations.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @quickclix75 thanks for your feedback, I created Pull Request to improve the documentation.
Thanks

**Comment by scanum** [comment]
@quickclix75  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
