### ISSUE TITLE
Teams IP-Phones deployment requirements must be indicated somewhere, for Internet access especially

### ISSUE THREAD

**Issue by piqueora** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1868]
This page well described the current features offered by Teams devices for users or marketing people. Another page describes how to currently "Manage your devices in Microsoft Teams". 
Nowhere it is described how such devices can be deployed and provisioned in a enterprise using a proxy for controling all Internet accesses.
From our tests, we conclude that all Teams devices in the current release v0.225 can NOT be deployed in such environments for 3 reasons : 
1) it does not understand the WPAD DNS mechanism, 
2) it does not understand the DHCP Option 252 giving the URL for the customer WPAD configuration file, 
3) no other mechanism is described.
Thank you to confirm or infirm explicitely this somewhere in Microsoft Docs for Teams, so that implementors know this critical constraint on their customer networks.
In such cases, customers networks will first have to be modified for using a NAT mechanism for Internet access without proxy, at least for all Office 365 targets : not a minor change, and not done by the same team!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae4c265a-8df4-647d-fc42-5054e3340c20
* Version Independent ID: 249c7301-9c82-b1c4-8401-54553370302b
* Content: [Phones for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/phones-for-teams)
* Content Source: [Teams/phones-for-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phones-for-teams.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
@kruthikaponnusamy Can you please comment? Sounds like we might need to create some new content here.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by kruthikaponnusamy** [comment]
This is mostly a partner work item, but we should have a backlog for this. How is this done?

Thanks,
Kruthika

**Comment by piqueora** [comment]
@kruthikaponnusamy  answered "This is mostly a partner work item, but we should have a backlog for this. How is this done?"
On the 1st point, the partner responded something like "this is Microsoft code, it's up to Microsoft to document their product, ask them".
On the 2nd point "how this done ?", that's precisely the point ! Thanks

**Comment by jambirk** [comment]
I believe @kruthikaponnusamy was addressing me, and didn't realize the comment was going to GitHub as well as email. She'll get back to you when she has an answer for your question.

**Comment by JoergBrors** [comment]
I have a question regarding deploying phones as an meeting room equipment, is there a special easy link to add an equipment mailbox/phone license to a device so that there is no need to signin to device manually or how the it solve that issue?

**Comment by jambirk** [comment]
@JoergBrors I think the recommended solution for Meeting Rooms is Microsoft Teams Rooms, see HTTP://aka.ms/MTRDocs

**Comment by JoergBrors** [comment]
@jambirk 
I follow the trail and find a way which descripts the surface hub deployment and creating a CSMeetingroom who will enabled with a special exchange policy. In my case I have a android based device with an Teams apk Software predefined by vendor and certified by Microsoft. And I have an existing Exchange account I used already on my Trio Skype for Buissines. Is there is an solution for that inside the Dokumentation which are working wir Android and Teams.APK ? If there is one can you offer a small migration path document?

**Comment by jambirk** [comment]
To my knowledge, Android devices are considered mobile clients and not meeting room devices. if you can't use MTR for whatever reason, I'm not sure what to suggest. @kruthikaponnusamy would have to answer further questions.

**Comment by kruthikaponnusamy** [comment]
@JoergBrors What device model do you want to use in your conference room? We support Yealink CP960 and Crestron M100 with Teams. Remote sign-in is currently not supported. It is a feature we are tracking in our backlog.

**Comment by JoergBrors** [comment]
@kruthikaponnusamy, We are using Trio 8800 and have testet M100. With Trio Right now there is a Teams Client available yet. But with this I can’t say what my strategy will be because I can‘t pin password under the phone System Trio or M100. When there is a plan to release and why vendors don’t have the possibility to influence?

**Comment by scanum** [comment]
@piqueora @kruthikaponnusamy @JoergBrors - thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot
