### ISSUE TITLE
Please add an explanation that defines External Access options more thoroughly

### ISSUE THREAD

**Issue by LisaJo48** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1869]
What is the difference between 'External Access' and 'Users can communicate with external Skype for Business Users'? 

Also, it appears that this screen shot and its explanation needs to be updated. My admin portal now says 'Users can communicate with Skype for Business Users and Teams users'; it no longer offers 'External Users'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31588a25-f3ee-e888-aa67-203be3d34489
* Version Independent ID: 3b498bcf-69a9-01ac-973a-4d5dbeea587c
* Content: [Manage external access (federation) in Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/manage-external-access#feedback)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @LisaJo48 
Thanks for your feedback! I created a PR to improve the article based on your comments.
Thank you

**Comment by scanum** [comment]
@LisaJo48  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
