### ISSUE TITLE
Database mirroring

### ISSUE THREAD

**Issue by hmank** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1879]
Database mirroring is not supported in Skype for Business 2019, it is only supported in Skype for Business Server 2015. Can you please update the document to reflect this information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8c5958a-c5e5-5aba-211a-2886c86ba831
* Version Independent ID: e53ed9d2-4ee4-346a-054b-6cf44b6a189b
* Content: [Back End Server high availability in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/high-availability-and-disaster-recovery/back-end-server)
* Content Source: [Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/back-end-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/back-end-server.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @hmank How are you?
Thanks for your feedback.
Actually, this article is also used for previous versions like SfB 2015, and depending on how you get to it, you will see in navigation Skype For Business 2019 or 2015.
That's the reason this article as a Special Note that says:

> SQL Mirroring is available in Skype for Business Server 2015 but is no longer supported in Skype for Business Server 2019. The AlwaysOn Availability Groups, AlwaysOn Failover Cluster Instances (FCI), and SQL failover clustering methods are preferred with Skype for Business Server 2019.

Thank you

**Comment by hmank** [comment]
I understand the note however it is confusing to the user when there is already a sepearate section for  Skype for business 2015 planning located here:
https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/server-requirements#DBs

And this one is for only Skype for Business 2019 see the image as well
https://docs.microsoft.com/en-us/skypeforbusiness/plan/system-requirements#DBs
![sfb2019db](https://user-images.githubusercontent.com/32819512/55100414-3e2e8d00-5098-11e9-8801-1874974dfe3c.jpg)

Thanks

**Comment by kenwith** [comment]
hi @hmank - thanks for taking the time to provide this feedback. This is a known issue we are working to resolve. The reason it is happening is that many of the articles are 'evergreen' meaning that they apply to both 2015 and 2019. But not all of them. There is a TOC file for 2015 and one for 2019. And in some articles the 2019 points to the evergreened article and it causes problems in the TOC rendering. This is a known problem we are solving and I am capturing our progress here: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/1861

This is all open source and being done transparently so if you are interested you can see what I am referring in the TOC article here: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/tree/live/Skype/SfbServer/sfbstoc and here:  https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/tree/live/Skype/SfBServer2019/sfbs2019toc

Hoping to get this resolved ASAP. Thanks again for taking the time to make the content and experience better. It is much appreciated!

CC @SerdarSoysal
