### ISSUE TITLE
Azure Monitor vs OMS

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1885]
Seems like the same article as with OMS ([link](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/with-oms)). Any plans to merge the Azure Monitor/OMS documentation? It somewhat brings confusion which solution to use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd80c884-93f3-8dac-f94d-a131fd79bba7
* Version Independent ID: e82ae6e4-4b10-fe5d-6ece-641a6375a085
* Content: [Deploy Skype Room Systems v2 management with Azure Monitor](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/azure-monitor#additional-solutions)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/azure-monitor.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/azure-monitor.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
The older OMS method is no longer supported, the OMS content was unlinked from the TOC. The OMS articles should be gone completely by end of day.
