### ISSUE TITLE
Logs (classic) no longer available

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1886]
In **Map custom fields** section, the **Logs (classic)** is no longer available. Should be updated to reflect the new **Logs** with screenshots.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd80c884-93f3-8dac-f94d-a131fd79bba7
* Version Independent ID: e82ae6e4-4b10-fe5d-6ece-641a6375a085
* Content: [Deploy Skype Room Systems v2 management with Azure Monitor](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/azure-monitor#feedback)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/azure-monitor.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/azure-monitor.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@JonesMikael Thank you for pointing this out, I will investigate further with the Microsoft team.

**Comment by jambirk** [comment]
@sohailta  Is Azure monitor management for rooms near end of life as a feature? Not sure if this doc update is really warranted.

**Comment by sohailta** [comment]
@jambirk I am not sure if the feature is near end of life. Kyle Spiess owns management and should be able to investigate and get back to you.

**Comment by scanum** [comment]
@kdspiess Hi Kyle, wondering if you could assist us on next steps on this issue? Thanks!

**Comment by scanum** [comment]
@jambirk Hi James, any updates on this? Thanks!

**Comment by jambirk** [comment]
@scanum  Just pinged Kyle on Teams

**Comment by kdspiess** [comment]
@scanum @jambirk   Sorry this has been slipping through the cracks on my priority list.  I'll look to address this next week.  Sorry for the delay.

**Comment by jambirk** [comment]
@kdspiess any update here?

**Comment by scanum** [comment]
@kdspiess Following up on this issue. Please let me know if there are any updates. Thanks!

**Comment by scanum** [comment]
@kdspiess Following up on this issue. Thanks.

**Comment by scanum** [comment]
@kdspiess Following up on this issue. Thanks.

**Comment by scanum** [comment]
@kdspiess Following up on this issue. Thanks.

**Comment by scanum** [comment]
@kdspiess Following up on this issue. Thanks.

**Comment by scanum** [comment]
@SerdarSoysal wondering who this should be assigned to? I haven't got an answer from @kdspiess

**Comment by rjagiewich** [comment]
@JonesMikael - I checked on the status of this issue. @kdspiess is currently working on this. We hope to have an update in a couple weeks.

**Comment by scanum** [comment]
@rjagiewich Thanks Rebecca!

**Comment by scanum** [comment]
@rjagiewich Hi Rebecca, wondering if there is an update on this issue?
Thanks!

**Comment by scanum** [comment]
@rjagiewich Hi Rebecca, wondering if there is an update on this issue?
Thanks!

**Comment by scanum** [comment]
@rjagiewich Hi Rebecca, wondering if there is an update on this issue?

**Comment by Reeced40** [comment]
@rjagiewich Hi Rebecca, any possible updates on this?

**Comment by Kateyanne** [comment]
Closed per Kyle Spiess.
