### ISSUE TITLE
"If your organization has no more than 1,000 users, you can create an org-wide team"

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1890]
The limit has since been raised to 5,000 for org-wide teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06059d07-6687-2924-7d0a-3c03220a1650
* Version Independent ID: bb293f92-9394-b156-2e08-0baead5c3bbe
* Content: [Overview of teams and channels in Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/teams-channels-overview?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/teams-channels-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-channels-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@thedrum808 Thank you for reaching out, I'm working on it.

**Comment by scanum** [comment]
@thedrum808 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
