### ISSUE TITLE
Too many 9s in the port range...

### ISSUE THREAD

**Issue by moreaboutmatt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1895]
Under "Requirements for using Transport Relays" the port range is listed as "50 000 – 59 9999" - too many 9s

Thanks...

Matt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10b198f4-9576-a14d-4359-1e8cc0319cda
* Version Independent ID: ba7c3252-21d4-9be1-2a84-de2d51646f7b
* Content: [Plan for media bypass with Direct Routing](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan-media-bypass)
* Content Source: [Teams/direct-routing-plan-media-bypass.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan-media-bypass.md)
* Service: **msteams**
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by jambirk** [comment]
@scanum this is an easy typo to confirm, please remove an extra 9 and republish.

@CarolynRowe Do you concur?

**Comment by CarolynRowe** [comment]
Thanks for your feedback.  I've already fixed this and it will be published soon.  Closing this issue.
