### ISSUE TITLE
Should AllowGuestAccessToGroups be AllowGuestsToAccessGroups setting name

### ISSUE THREAD

**Issue by JefTek** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1897]
I believe the setting referenced in this document should be "AllowGuestsToAccessGroups" and not "AllowGuestAccessToGroups" as per this document https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-guest-access-in-groups?view=o365-worldwide#use-powershell-to-control-guest-access

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18cf5b2f-9527-c59d-cacf-04ea9d4f61f3
* Version Independent ID: a34cff52-ce5c-1830-69e9-3b07cf111ce9
* Content: [Use PowerShell to control guest access to a team](https://docs.microsoft.com/en-us/microsoftteams/guest-access-powershell)
* Content Source: [Teams/guest-access-PowerShell.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-PowerShell.md)
* Service: **msteams**
* GitHub Login: @somakbhattacharyya
* Microsoft Alias: **sbhatta**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@JefTek Thank you for reaching out, working on it.

**Comment by scanum** [comment]
@JefTek Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
