### ISSUE TITLE
Ability to add a specific sheet from Excel workbook

### ISSUE THREAD

**Issue by ttorrisi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1899]
My use case is as follows: I have a Excel workbook stored in Sharepoint with a master sheet, and client specific sheets. I want to be able to add a specific sheet to a specific channel. Is this possible, or on the roadmap at least? Having to keep multiple workbooks updated and living in Teams is not ideal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d33f55c-db55-923e-544f-fccb97f3c7a3
* Version Independent ID: 9cb02e00-311e-ec7d-c422-ae1cb9e6d31e
* Content: [Use built-in and custom tabs in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/built-in-custom-tabs#feedback)
* Content Source: [Teams/built-in-custom-tabs.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/built-in-custom-tabs.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@ttorrisi  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
