### ISSUE TITLE
Open application in background

### ISSUE THREAD

**Issue by Refalm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1901]
Where is the option to set "open application in background"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Microsoft Teams using MSI via SCCM](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment#feedback)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @Lester-Hewett
* Microsoft Alias: **lehewe**

**Comment by o-l-a-v** [comment]
Press your profile picture (top right), then settings.
![image](https://user-images.githubusercontent.com/6450056/55101698-fffb9280-50c4-11e9-8302-e0e5b3389651.png)

**Comment by scanum** [comment]
@Refalm  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
