### ISSUE TITLE
dead link: Plan your Phone System in Office 365 (Cloud PBX) solution: 

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1903]
this link doesn't work: "Plan your Phone System in Office 365 (Cloud PBX) solution: "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33bc456f-7b95-8779-3970-e3f476a5a4fb
* Version Independent ID: f0549691-87ab-e7d8-d00d-a5169a8cddb7
* Content: [Here's what you get with Phone System in Office 365](https://docs.microsoft.com/en-us/microsoftteams/here-s-what-you-get-with-phone-system#feedback)
* Content Source: [Teams/here-s-what-you-get-with-phone-system.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/here-s-what-you-get-with-phone-system.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by SkyTechGit** [comment]
What Mike said. Dead link

**Comment by CarolynRowe** [comment]
Thank you for your feedback.  This has been fixed and will go live today.
