### ISSUE TITLE
The download link is not working

### ISSUE THREAD

**Issue by davidchenrsg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1904]
https://www.microsoft.com/en-us/download/details.aspx?id=39366

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27364aed-dc10-dcaf-8446-bc93e39bd4ca
* Version Independent ID: 907a29a6-6ff3-5c91-5c74-cf98cf71ad88
* Content: [Download and install the Skype for Business Online Connector module](https://docs.microsoft.com/en-us/skypeforbusiness/set-up-your-computer-for-windows-powershell/download-and-install-the-skype-for-business-online-connector#feedback)
* Content Source: [Skype/SfbOnline/set-up-your-computer-for-windows-powershell/download-and-install-the-skype-for-business-online-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-your-computer-for-windows-powershell/download-and-install-the-skype-for-business-online-connector.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@davidchenrsg Thank you for helping improve MS Doc. I have made the necessary changes.

**Comment by scanum** [comment]
@davidchenrsg Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by cschafft** [comment]
The download link is no longer working.

**Comment by CarlosFarrica** [comment]
The download link is no longer working.
