### ISSUE TITLE
Add Exchange Server 2013 or later into this document

### ISSUE THREAD

**Issue by bament-hun** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1905]
As many other article for SfB Server 2015/2019 contains that we have the same requirements for Exchange 2013 as Exchange 2013 later, this article should be also updated with the information that what we can find here is valid for Exchange Server 2013 or later as well.
reference:
https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/compatibility-with-office#exchange-server-and-skype-for-business
https://docs.microsoft.com/en-us/skypeforbusiness/deploy/integrate-with-exchange-server/oauth-with-online-and-on-premises?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65c7d113-8640-4878-c766-a4ef4c4fabf9
* Version Independent ID: dc9432a5-be50-25d0-9dfc-a1974653c245
* Content: [Manage server-to-server authentication (OAuth) and partner applications in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/manage/authentication/server-to-server-and-partner-applications#feedback)
* Content Source: [Skype/SfbServer/manage/authentication/server-to-server-and-partner-applications.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/authentication/server-to-server-and-partner-applications.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by msbemba** [comment]
@bament-hun Thank you for your feedback. We have added a link to the compatibility doc on https://docs.microsoft.com/en-us/skypeforbusiness/deploy/integrate-with-exchange-server/oauth-with-online-and-on-premises?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json  via PR https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/2355

**Comment by scanum** [comment]
@bament-hun Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
