### ISSUE TITLE
Two points Needs attention 

### ISSUE THREAD

**Issue by teharia** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1909]
Important
If Communications Credits haven't been set up, Audio Conferencing won't work for any users with pay-per-minute licenses.

 Note
If you have Audio Conferencing pay-per-minute licenses, you don't have to assign Communications Credits licenses separately to each user specifically for Audio Conferencing usage (you might still need to assign them for other services).

These two appears to be contradicting with each other. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6634d348-095c-a531-fb56-d61349b708cd
* Version Independent ID: 85407958-97f6-babf-6043-899449ba998f
* Content: [Try or purchase Audio Conferencing in Office 365 for Skype for Business Online](https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/try-or-purchase-audio-conferencing-in-office-365#feedback)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/try-or-purchase-audio-conferencing-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/try-or-purchase-audio-conferencing-in-office-365.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by msbemba** [comment]
@teharia Thank you for your feedback. We have removed the contradicting statement via PR https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/2351

**Comment by scanum** [comment]
@teharia Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
