### ISSUE TITLE
Capabilities granted to anonymous users

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1910]
Please provide information about what an Anonymous user in a meeting is allowed to do and an explanation of their experience in the mobile, web, and desktop app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c8aee4f-05cd-85bf-8e8a-e11fa62b4f08
* Version Independent ID: addd3d3c-e615-67e1-0678-c1d4dc451815
* Content: [Manage meeting settings](https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams#feedback)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by jeffmparker** [comment]
Could the experience of a user joining a meeting please also be described, and the interactions of the related settings? I have external and guest access set on, but an external invitee could not access a meeting yesterday, and I'm not sure if that is because anonymous is turned off.

**Comment by get-itips** [comment]
Hello @LanaChin as the referenced article where this issue was created talks about the needed settings to manage anon access, it does not seem the right place to add how is the experience of an anon user. Something more like [this](https://docs.microsoft.com/en-us/microsoftteams/guest-experience) but for anon, do you know if an article will be created or can we just add a note to current article describing anonymous capabilities on a meeting?
Thank you

**Comment by scanum** [comment]
@LanaChin Hi Lana, hope you are doing well. Any updates on this? Thanks!

**Comment by LanaChin** [comment]
I've reached out to the PM on this.

**Comment by LanaChin** [comment]
@get-itips @scanum I'm working with the PMs and content teams to update the documentation to provide more detail about the anonymous user experience for joining meetings.

**Comment by get-itips** [comment]
@LanaChin We appreciate. Thanks

**Comment by scanum** [comment]
@LanaChin Any updates on this? Thanks!

**Comment by LanaChin** [comment]
There are several teams collaborating on this. I'll add a comment when I have an update to share. Thanks!

**Comment by scanum** [comment]
@LanaChin Hi Lana, following up on this issue? Any updates? Thanks!

**Comment by scanum** [comment]
@LanaChin Hi Lana, following up on this issue. Thanks.

**Comment by scanum** [comment]
@LanaChin Following up on this issue. Please let me know if there are any updates. Thanks!

**Comment by scanum** [comment]
@LanaChin Following up on this issue. Thanks!

**Comment by LanaChin** [comment]
I've updated the "Allow anonymous users to join meetings" section of this article with a link to a new article on support.office.com that describes the join experience.  Thanks for contributing to improve docs.
