### ISSUE TITLE
Language Clarity

### ISSUE THREAD

**Issue by MySkypeLab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1913]
"Each Files tab in Teams runs on a SharePoint Online backend, so the storage limits above apply to each Channel within a Team." - I believe that this line could be misinterpreted as meaning that each channel gets the full limit within the table, However, Channels share the storage limits of the team that they belong to. So clearer language might be something more like this: "Public Channels are backed by folders within the SharePoint Online Site Collection created for the Team, so Files tabs within Channels share the storage limits of the Team they belong to."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by msbemba** [comment]
@MySkypeLab Thank you for your feedback. We have made necessary changes to reflect clarity on the doc. The changes can be tracked via PR https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/2354

**Comment by scanum** [comment]
@MySkypeLab Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
