### ISSUE TITLE
No explanation about do I have to add domains or block them to make external usage possible

### ISSUE THREAD

**Issue by eino-makitalo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1915]
Your page is showing nice pictures but no explanation what is the meaning of adding domains to Add Domain list :-(

If I allow external usage is it then open to every domain
and I can block hostile ones?
If I dont allow ... then I can block?

This is not very logical and intuitive so add some description

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31588a25-f3ee-e888-aa67-203be3d34489
* Version Independent ID: 3b498bcf-69a9-01ac-973a-4d5dbeea587c
* Content: [Manage external access (federation) in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access#feedback)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@eino-makitalo Thank you for reaching out and helping improve MS Docs.  I'll have the team look into this and advise you soonest.

**Comment by scanum** [comment]
@eino-makitalo We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
