### ISSUE TITLE
Listener healthcheck

### ISSUE THREAD

**Issue by rimroot** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1917]
Please change KnownServersCount to KnownServerCount

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91a4a6b7-573d-8b5b-c3d5-b728439c19f6
* Version Independent ID: 234fec3b-22a0-24d7-a4ce-b64623a0a749
* Content: [Deploy Statistics Manager for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/statistics-manager/deploy#feedback)
* Content Source: [Skype/SfbServer/management-tools/statistics-manager/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/management-tools/statistics-manager/deploy.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@rimroot Thank you so much for reaching out. I have fixed the wording

**Comment by scanum** [comment]
@rimroot Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
