### ISSUE TITLE
Exporting

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1920]
how can we export the data used in these reports?
how can we use this data in PowerBI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ade1a4-092c-1132-44df-ee2c683fdd33
* Version Independent ID: 396b1aee-2f40-9895-9b00-07e38d11d31b
* Content: [Microsoft Teams analytics and reporting](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-analytics-and-reports/teams-reporting-reference)
* Content Source: [Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officedocs assign @scanum

**Comment by get-itips** [comment]
Hello @DeanGross How are you? Thanks for your feedback.
Currently, Teams Admin Portal or Teams Powershell do not have an option to export this reports.
You can explore [Microsoft Graph reports API](https://docs.microsoft.com/en-us/graph/reportroot-concept-overview) if it suits your needs. Also, you can make a suggestion in [Teams User Voice](https://microsoftteams.uservoice.com)

Hope this informations helps you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by scanum** [comment]
@DeanGross - thank you for submitting feedback.

As @get-itips mentioned, we think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Mike-Crowley** [comment]
> 
> 
> Hello @DeanGross How are you? Thanks for your feedback.
> Currently, Teams Admin Portal or Teams Powershell do not have an option to export this reports.
> You can explore [Microsoft Graph reports API](https://docs.microsoft.com/en-us/graph/reportroot-concept-overview) if it suits your needs. Also, you can make a suggestion in [Teams User Voice](https://microsoftteams.uservoice.com)
> 
> Hope this informations helps you.

These reports don't seem to be exposed in the Graph API. I can only find the activity reports - not the analytics reports. Where are they specifically?
