### ISSUE TITLE
Missing Downloads

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1921]
Where is the Report Download feature shown in the screenshot,? we don't have that in our tenant.
Please label screenshots with the status of the feature if it not yet deployed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b138331-2f10-a05d-7e88-68e62e0b3e4f
* Version Independent ID: f923b648-ffe4-8a8a-c189-6e31f1032c10
* Content: [Microsoft Teams usage report](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-analytics-and-reports/teams-usage-report)
* Content Source: [Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officedocs assign @scanum

**Comment by atagliacozzo** [comment]
Need to download data/report

**Comment by get-itips** [comment]
@SharS Sent you an email about this as the author of the commit that included that screenshot. Thanks!

**Comment by get-itips** [comment]
Hello @DeanGross thanks for your feedback.
The feature is rolling out gradually, it should appear on your tenant soon.
Hope this information helps you.
Thanks

**Comment by scanum** [comment]
@DeanGross Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
