### ISSUE TITLE
Mic icon remains active on local view, but turns off on other attendees' views.

### ISSUE THREAD

**Issue by ASunday47** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1922]
During a Skype4B meeting the microphone icon is deceiving for the user. It leads the user to believe their microphone is picking up sounds when it is not. 
For the following example, I'm considering an inactive mic icon to be the blue mic icon with no lines around it. An active icon is the blue mic icon with the small vertical lines around it symbolizing activity. 

Example -&gt;
 - User A dials into a meeting with Users B & C. 
 - User A will talk causing their mic icon to show active. The User A mic icon will also be active on User B and C's display. The call monitor will also show a blue line under that persons picture during this time. This is expected.
- User A will stop talking. 
 -&gt; 1) User B and C will see a fast response of the User A mic icon becoming inactive. User B and C will also see the blue line disappear under the photo icon. This is all expected. 
 -&gt; 2) The issue that occurs here is that the mic icon on User A's display will still show as active. The blue line under their own name will still be there. After some time (10+ seconds), the mic icon will be come inactive and the blue line will disappear. 

This behavior can be deceptive for a user. It leads the user to believe their microphone is picking up noise. I spent a considerable amount of time trying to tweak my microphone settings to prevent suspected noise from my mic when in fact, there was no noise on the other lines, just a delayed icon adjustment.

I would suggest that the icon should go inactive as quickly as it does on User B and C's side. 

Version: Skype for Business for Office 365 MSO (16.0.10730.20264) 32 bit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1b3c395-1757-2618-6255-b99b9403f7fc
* Version Independent ID: 08f0c55c-7671-df62-3181-c327386e05b3
* Content: [Troubleshoot problems with Skype for Business Online](https://docs.microsoft.com/en-us/skypeforbusiness/set-up-skype-for-business-online/troubleshoot-problems-with-skype-for-business-online#feedback)
* Content Source: [Skype/SfbOnline/set-up-skype-for-business-online/troubleshoot-problems-with-skype-for-business-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-skype-for-business-online/troubleshoot-problems-with-skype-for-business-online.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@ASunday47  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
