### ISSUE TITLE
VoIP users + Exchange On-premises

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1930]
Per the announcement that voicemail would be coming to all VoIP users, and that voicemail is stored in the Exchange Online mailbox, will users with on-premises Exchange be able to use voicemail features (using the shadow Exchange Online mailbox) or will it be unavailable altogether?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8228f9b2-a7de-abb4-6f41-70db0b3af155
* Version Independent ID: 8fd9fafb-dd76-59a8-e609-56f06d539a31
* Content: [Set up Cloud Voicemail](https://docs.microsoft.com/en-us/microsoftteams/set-up-phone-system-voicemail)
* Content Source: [Teams/set-up-phone-system-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-phone-system-voicemail.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Please see the following topic and let us know if it doesn't answer your question:  https://docs.microsoft.com/en-us/SkypeForBusiness/hybrid/plan-um-migration

We will also add a link in the Set up Phone System voicemail topic.
