### ISSUE TITLE
Typo in diagram

### ISSUE THREAD

**Issue by MySkypeLab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1933]
The first diagram says "Skype for Business 2019 with Clound voicemail", should be "Cloud"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 469ac0c8-5c06-7f7f-fe1d-8cadb205572a
* Version Independent ID: 5c9987d5-4c98-8115-55c8-f629dbd25799
* Content: [Plan Cloud Voicemail service for on-premises users](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-cloud-voicemail)
* Content Source: [Skype/SfbHybrid/hybrid/plan-cloud-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/plan-cloud-voicemail.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Thank you for your feedback.  The diagram has been fixed.
