### ISSUE TITLE
Does Teams CAP work with Direct Routing?

### ISSUE THREAD

**Issue by rrgonzalezz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1936]
Does the CAP license work with Teams and Direct Routing. All the documentation I have encountered so far only makes reference to the set up of Teams / SfB Online CAPs with Calling Plans, but I have been searching for Microsoft documentation stating or confirming if Teams CAPs are also supported with Direct Routing to no avail so far.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ab5215-f24f-75cf-bb92-16ac0ff5e5ca
* Version Independent ID: 701cc58f-d2ea-cbb6-f5fc-47b9fbfb1119
* Content: [Set up the Common Area Phone license for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-common-area-phones#feedback)
* Content Source: [Teams/set-up-common-area-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-common-area-phones.md)
* Service: **msteams**
* GitHub Login: @lolaj
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by get-itips** [comment]
@LolaJacobsen how are you? do you maybe have information about this?
**Thank you**

**Comment by scanum** [comment]
@LolaJacobsen Any updates on this? Thanks!

**Comment by scanum** [comment]
@CarolynRowe Hi Caroly, Lola mentioned that this is an area of your expertise. Could you please help us with this?

Thanks!

**Comment by CarolynRowe** [comment]
I don't know the answer, but I've contacted the PM, Nikolay M.

**Comment by NMURAV** [comment]
I am a PM, Yes CAP works with Direct Routing. I'll take a lead to change the documentation

**Comment by scanum** [comment]
@NMURAV @CarolynRowe @NMuravlyannikov Any updates on this issue? Thanks!

**Comment by scanum** [comment]
@NMURAV @CarolynRowe @NMuravlyannikov Any updates on this issue? Thanks!

**Comment by toddportz** [comment]
@NMURAV @CarolynRowe Any news on this. This is impacting our rollout in Healthcare as well. We have a lot of common area phones.

**Comment by NMuravlyannikov** [comment]
@toddportz yes the CAP work with Direct Routing. I'll change the documentation

**Comment by scanum** [comment]
@NMuravlyannikov Hi NMuravlyannikov, could you please link the PR once you change the documentation? Thanks!

**Comment by scanum** [comment]
@NMuravlyannikov Hi Nikolay following up on this issue? Please let me know if there are any updates. Thanks!

**Comment by SerdarSoysal** [comment]
@tonysmit please review the licensing question.

**Comment by scanum** [comment]
@tonysmit HI Tony, any updates on this issue? Thanks!

**Comment by tonysmit** [comment]
Looks like this will need new screenshots and the UX rewritten. @SerdarSoysal - What "licensing question"?

**Comment by scanum** [comment]
@SerdarSoysal Following up on this issue. Please let me know if there are any updates. Thanks!

**Comment by SerdarSoysal** [comment]
@tonysmit I was referring to the CAP license question in the original issue, but Nikolay has already addressed this.

@NMuravlyannikov do we have a PR for this yet?

**Comment by scanum** [comment]
@NMuravlyannikov Following up on this issue. Thanks!

**Comment by robgeach** [comment]
is nikolay muravylannikov the only person at microsoft with the capability to describe how teams CAP licensing interacts with direct routing, and if so how many people are tasked with protecting his life?

if fate should befall him are we doomed to never see official documentation on the intended interaction between these two concepts? 

does such a valuable feature really necessitate 6 months of hemming and hawing about how to present it to the public at large after already admitting it works?

if every single technical employee who reports to nikolay is so busy they can't slap something together in less than a couple days over the course of 6 months then can someone at microsoft find it within their heart and annual budget to give him a functional employee who could handle this stuff on his behalf?

Thanks.

**Comment by pelmore-web** [comment]
Any update ??? We need documentation on setting up CAP with either SfBO with on prem PSTN or Teams and/or Direct Routing.

**Comment by oradcliffe** [comment]
Also looking for an update here.

**Comment by scanum** [comment]
@SerdarSoysal @NMuravlyannikov Following up on this issue. Thanks!

**Comment by oradcliffe** [comment]
Hey guys just checking in :)

**Comment by scanum** [comment]
@SerdarSoysal @NMuravlyannikov Following up on this issue. Thanks!

**Comment by scanum** [comment]
@SerdarSoysal @NMuravlyannikov Following up on this issue. Thanks!

**Comment by oradcliffe** [comment]
Do we have an answer somewhere?

**Comment by SerdarSoysal** [comment]
We have a support statement added here https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan#supported-end-points  We also revised this topic as well and it's in the publishing pipeline right now. Changes should be live in 10-15 minutes.

Apologies to all for how long this took. This isn't typical.

**Comment by oradcliffe** [comment]
All good.  Thank you!
