### ISSUE TITLE
No mention of how long it takes for guest access to start working after enabling guest users

### ISSUE THREAD

**Issue by Shlibidi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1937]
It would be really nice if this documentation (or even better, a warning after enabling it in the Teams Admin Center) mentioned that it takes between 8 and 24 hours until you're able to invite guest users to Teams after enabling Guest Users. 
As it is right now: we enable Guest Users and test it and worry that something is wrong with the configuration instead of being aware that it just takes really long until the change takes effect.

Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b05e642-c4e5-f1b5-5315-d3ef1690a0cd
* Version Independent ID: 01b7e0b5-3e50-3de0-e3e9-aeeeda43da12
* Content: [Authorize guest access in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-dependencies#control-guest-access-in-office-365-groups)
* Content Source: [Teams/Teams-dependencies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-dependencies.md)
* Service: **msteams**
* GitHub Login: @somakbhattacharyya
* Microsoft Alias: **sbhatta**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by truekonrads** [comment]
Suggested fixes:
1) if a user types an e-mail address into invite and it is an external e-mail address - not found, it should take to the relevant documentation.
2) when enabling guest access, a big pop-up should warn about the delay

**Comment by scanum** [comment]
@Shlibidi Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
