### ISSUE TITLE
Team apps > Permission policies doesn't exist in Teams admin center!?!

### ISSUE THREAD

**Issue by jg11jg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1948]
"In the left navigation of the Microsoft Teams admin center, go to Teams apps &gt; Permission policies."

I'm at https://admin.teams.microsoft.com/teams/manage, the header of the page says "Microsoft Team admin center" and there is a left navigation bar.  However, the left navigation bar does NOT have a "Teams apps" menu item.  It has Dashboard, Teams, Devices, Locations, Users, Meetings, Messaging policies, Voice, Analytics & Reports, Org-wide settings, Legacy portal, Call quality dashboard, Firstline Worker configuration.

The Teams icon does not take me anywhere I can manage permissions.  The org-wide settings has a Teams Settings sub-menu, but again,  nothing permissions related, nothing that looks like your screenshot above.

WHERE CAN I ACTUALLY FIND ALL THESE OPTIONS ABOVE YOU ARE REFERRING TO?

Ultimately, I'm trying to enable uploading of custom apps into teams as an org-wide setting, but this document is not helping at all :(

[Note: I'm the owner and admin of the teams account/subscription/office 365 subscription so I don't believe that my own level of permission are a problem].

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d51bb7b1-801e-6801-dcaf-afa3e38e6941
* Version Independent ID: d8e726a1-cbf2-53c7-da4d-cc155b48612b
* Content: [Manage custom app policies and settings in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-custom-app-policies-and-settings#feedback)
* Content Source: [Teams/teams-custom-app-policies-and-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-custom-app-policies-and-settings.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@jg11jg  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
