### ISSUE TITLE
how to delete

### ISSUE THREAD

**Issue by WillemVerwijs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1950]
This website is about managing teams yet there is not info on how to delete a team via the teams Admin website. what can i do to get that described as well. does anybody ever read comments like this and how can i know they are read

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 3b51b67a-d89c-723f-3520-87cb2dc93b90
* Version Independent ID: 78d10cbc-d75b-2b02-d49c-2c3fe1579807
* Content: [Teams beheren in het beheercentrum van Microsoft Teams](https://docs.microsoft.com/nl-nl/microsoftteams/manage-teams-in-modern-portal#feedback)
* Content Source: [Teams/manage-teams-in-modern-portal.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-teams-in-modern-portal.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@WillemVerwijs thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
