### ISSUE TITLE
What permission wins Priority

### ISSUE THREAD

**Issue by Mzucchi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1951]
What permission is the winning permission when a domain is in the external access domain list, and a  user of the domain is a Guest of a team?

**Comment by scanum** [comment]
@Mzucchi - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
