### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1953]
Should be MAKE in the paragraph

You can also use Direct Routing to allow your users to mand and receive PSTN calls. To learn how to set up Direct Routing, read Configure Direct Routing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8354e80d-02da-7f51-a713-e698322e8ec1
* Version Independent ID: ef42d9af-336a-e014-de0a-b7bf7bb1f87d
* Content: [Quick start guide - Configuring Calling Plans in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/configuring-teams-calling-quickstartguide#feedback)
* Content Source: [Teams/configuring-teams-calling-quickstartguide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/configuring-teams-calling-quickstartguide.md)
* Service: **msteams**
* GitHub Login: @arachmanGitHub
* Microsoft Alias: **MyAdvisor**

**Comment by nenonix** [comment]
@jantoney Thanks for pointing this out.

**Comment by scanum** [comment]
@jantoney Thank you for submitting feedback. We strongly appreciate your contributions. We understand that this issue has been resolved, so I am going to go ahead and close it. 

@officedcosbot close

**Comment by scanum** [comment]
@officedocsbot close
