### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by mhunsberger** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1954]
Misspelling: After you create a policy and make your changes, you can then assign "uses" (should be "users") to the policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by nenonix** [comment]
@mhunsberger  Thanks for pointing this out.

**Comment by scanum** [comment]
@mhunsberger Thanks for submitting feedback, we strongly appreciate your contributions. Please continue to add value to our community. We understand that this issue has been resolved, so we are going to go ahead and close it.

**Comment by scanum** [comment]
@officedocsbot close
