### ISSUE TITLE
Are there plans for adding username/password sign in for Skype for Business Online phones with MFA?

### ISSUE THREAD

**Issue by msegura22** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1955]
Only works with Web Sign in with Polycom VVX phones. Is this in the works where users can just enter the password on the prompt in the computer when paired, without having to do web sign in?

**Comment by scanum** [comment]
@msegura22  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
