### ISSUE TITLE
SBC list is out of date

### ISSUE THREAD

**Issue by MySkypeLab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1973]
The listed SBCs on this page for Media Bypass support is out of date. Update to link to this page: https://docs.microsoft.com/en-us/microsoftteams/direct-routing-border-controllers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a65beb81-260d-8b98-b3c3-32e93b728e69
* Version Independent ID: 13c7c654-5182-eaf6-2d66-66b1b5e943ca
* Content: [Configure media bypass with Direct Routing](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-configure-media-bypass)
* Content Source: [Teams/direct-routing-configure-media-bypass.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-configure-media-bypass.md)
* Service: **msteams**
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Thank you for your feedback, which has been incorporated and will go live today.
