### ISSUE TITLE
Table - Additional information request

### ISSUE THREAD

**Issue by MySkypeLab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1975]
Can the Media Processors and Transport relay table by updated to give more information about where in the world the Transport Relays are located? Currently is says the are located in "Multiple" locations, what does this mean? For example if this means they are located in every O365/Azure DC then it may be beneficial to turn on Media Bypass and force calls via local relays rather than up to the regional media processors in the case of non-media bypass scenarios.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10b198f4-9576-a14d-4359-1e8cc0319cda
* Version Independent ID: ba7c3252-21d4-9be1-2a84-de2d51646f7b
* Content: [Plan for media bypass with Direct Routing](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan-media-bypass)
* Content Source: [Teams/direct-routing-plan-media-bypass.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan-media-bypass.md)
* Service: **msteams**
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@MySkypeLab Thank you for reaching out.  The answer to your question is that Media Processors are deployed in the US, East and West Coast data centers, in Amsterdam and Dublin and in Singapore and Hong Kong. There are many media relays deployed in almost every Azure DC.

**Comment by scanum** [comment]
@MySkypeLab Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
