### ISSUE TITLE
This document it's wrong.

### ISSUE THREAD

**Issue by tiagoroxo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1976]
You cannot use the cmdlets "Move-CsRgsConfiguration" to move RGS from 2019 pool to 2019 pool... This document it's wrong.
As you can see in the following article move cannot be used here: https://docs.microsoft.com/en-us/powershell/module/skype/move-csrgsconfiguration?view=skype-ps
Also, seems like this document it's a copy of the 2013 one: https://docs.microsoft.com/en-us/lyncserver/migrate-response-groups

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79304a6a-71f0-a632-2bfd-564b7e26cbc5
* Version Independent ID: ecfd23fa-dced-21f7-b320-05a9beb12df7
* Content: [Migrate response groups](https://docs.microsoft.com/en-us/skypeforbusiness/migration/migrate-response-groups)
* Content Source: [Skype/SfBServer2019/migration/migrate-response-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/migration/migrate-response-groups.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@tiagoroxo Thank you for reaching out.  Could you perhaps suggest the changes to the document that you would recommend.

**Comment by lindspea** [comment]
@dariomws306 @get-itips

**Comment by dariomws306** [comment]
Hi @tiagoroxo, you can use this cmdlet to move from legacy version to newer version. You cannot use it to move from one pool no another pool with the same version (including 2019) as you say, but it's explained in the article:
"The Move-CsRgsConfiguration cmdlet is only for migrating from Office Communications Server 2007 R2 or Lync Server 2010 to Skype for Business Server; you cannot use this cmdlet to migrate from one instance of Skype for Business Server to a new instance of Skype for Business Server. That type of migration can only be done by using the new Import-CsRgsConfiguration and Export-CsRgsConfiguration cmdlets."

**Comment by scanum** [comment]
@tiagoroxo Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
