### ISSUE TITLE
Just link the deployment kit, please.

### ISSUE THREAD

**Issue by oddhair** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1982]
The current version of the script doesn't succeed at downloading the deployment kit, and plenty of articles point here for the deployment kit. There's no good reason to stop people getting at the deployment kit.  Luckily the error has the address for the deployment kit listed, I guess I'll do it manually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51d42140-9f7b-a6f3-7a3e-76cc7331cf22
* Version Independent ID: a7dacc56-c2df-55fb-76a3-ecb194564fae
* Content: [Configure a Microsoft Teams Rooms console](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/console#feedback)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/console.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Hi @oddhair 

The script is needed to ensure a correct match between the Windows 10 version and the MSI version, mismatches can result in failed installations and malfunctioning devices. Please don't try to do this manually. If you're experiencing issues with the script, we can pass along details of the failure to the product development group if you can provide them.

**Comment by oddhair** [comment]
Thanks for that; we were part of the Rigel TAP while it was ongoing so I've built it a number of times over the years. I'm trying to run it now and it seems to have an undefined variable ($LanguagePack) though I'm not great at reading this advanced of Powershell syntax. In any case when I run it it downloads a presumably newer version of the script yet it's failing for me and I don't even need to add any language packs.

**Comment by jambirk** [comment]
So far I wouldn't hazard a quess about root cause, but it's worth investigating. Do you have a support case open for this? That might be a really good idea, they'd probably be able to eliminate a lot of other factors.
@Travis-Snoozy  might have some follow-up questions here.

**Comment by Travis-Snoozy** [comment]
@oddhair -- Each time the script starts, it will output the name of the log file that it's logging its transcript to. Please run the script, replicate the fault, and paste the contents of that file to this issue so that I can analyze the problem.

Please also make sure you're running the very [latest version of the script](https://go.microsoft.com/fwlink/?linkid=867842), if you have not done so already.

**Comment by oddhair** [comment]
Thank you Travis, I must admit I didn't think I could address this via a support case; I'm simply chasing down something for a client. Here's the transcript with the failure, it's version 1.4.3 which seems most recent. Line 1232 of the script has the variable I'm referring to:

**********************
Windows PowerShell transcript start
Start time: 20190405114601
Username: <snip>
RunAs User: <snip>
Configuration Name: 
Machine: COBBLER (Microsoft Windows NT 10.0.17134.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Process ID: 29420
PSVersion: 5.1.17134.1
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17134.1
BuildVersion: 10.0.17134.1
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is \\jellybean\users\<snip>\PowerShell_transcript.COBBLER.6K0zBNZb.20190405114601.txt
Script version 1.4.3
Downloading CreateSrsMedia...
done
Validating signature for update.ps1...
success.

919C06207B8A9C6B71423B7916AB61D3F6EF6DC7BD04AD4EC9CB172053B3317991E8274D1DC0F6335D27B8F4E299F7336FEE6F5966624F2A5815A7EB8293884E
68308

What type of customer are you?
Please make sure you have all of the following available:

1. A USB drive with sufficient space (16GB+).
   The contents of this drive WILL BE LOST!
2. Windows 10 Enterprise media that matches your SRSv2 deployment kit.
   Enterprise customers can access Windows 10 Enterprise media from the Volume Licensing Service Center:
   http://www.microsoft.com/licensing/servicecenter
3. Any language pack (LP and/or LIP) files to be included.
   MPSA customers:         http://go.microsoft.com/fwlink/?LinkId=125893
   Other volume licensees: http://www.microsoft.com/licensing/servicecenter

Please do not continue until you have all these items in order.

Found deployment kit already downloaded.
Validating signature for SRSDeploymentKit-4.0.78.0.msi...
success.
Extracting the deployment kit...
done.
This deployment kit is built for Windows build 10.0.17134.1.
This deployment kit draws its drivers from %configsetroot%\AutoUnattend_Files\DistShare\Out-of-Box Drivers.

Please indicate what drivers you wish to use with this installation.
[ 0] Logitech SmartDock
[ 1] Crestron SR
[ 2] Polycom MSR
[ 3] Lenovo Hub 500
[ 4] LRS
[ 5] HP Slice 2.0
[ 6] Crestron Flex
[ 7] None
Selected option 5.
WARNING: The HP Slice 2.0 does not have a driver pack for this SRSv2 build. Continuing with no pre-installed drivers.
Identifying language packs...
PS>TerminatingError(Get-WindowsPackage): "The system cannot find the file specified.
"
**********************
Windows PowerShell transcript end
End time: 20190405114623
**********************

**Comment by Travis-Snoozy** [comment]
Do you have one or more CAB files in the same directory as the script? If so, try removing it (or moving the script into an empty directory and running it from there). I think I see the error; I'll double-check that the problem is what I think it is, and put in a corresponding fix.

**Comment by oddhair** [comment]
I do in fact have a single cab file, Rigel-StoreApp-0.179.0.cab, along with a stack of other files. I'll try isolating them. edit: that worked, it got past the language pack question and now I just need to find exactly the correct version of Windows 10. Thanks for your help, Travis and jambirk!

**Comment by jambirk** [comment]
Thanks @oddhair : it looks like we have a couple small improvements that came out of this, both in the doc and script.
