### ISSUE TITLE
Listed documentation to setup Teams Room does not work

### ISSUE THREAD

**Issue by jwinte** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1987]
Thank you for writing a nice, condensed article that covers Microsoft Teams rooms! We have been fighting an issue with sign-in that support does not know how to correct. I have followed your documentation exactly and have ensured we meet all requirements listed. Can you please give me some guidance on how we can move forward?

**Our Environment**

- Exchange 2013 On-Premise w/ SP1 and CU22
- On-premise Skype for Business with autodiscover DNS entries pointed on-prem
- Office 365 E3 with all necessary licensing added per article
- Azure AD Sync

**Things that may be missing from the article**

- Required DNS entries - There is no direction in the article for DNS entries(we have tried changing the UPN of the Teams Room to @onmicrosoft.com)
- Domain field (bottom of Teams Room provisioning page - There is no direction in the article regarding what you should use for sign-in information. 
<img width="346" alt="TeamsRoom" src="https://user-images.githubusercontent.com/49342002/55670202-395f9b00-5847-11e9-93cd-facbaed4b71f.png">

**Things that are working**

- We can sign-in to https://teams.microsoft.com using the on-prem synced room account
- We can get the calendar showing by using the Exchange address of @onpremdomain.com and using the domain\username field.
- If we keep the Skype sign-in and Exchange sign-in fields exactly the same using @onmicrosoft.com address, the room account is able to sign-in successfully, but then obviously it breaks the calendar fetching.

**Things that are not working**

- We cannot get BOTH the calendar fetching and Teams Room sign-in working at the same time. We can only get one or the other. I'm making an educated guess here that it doesn't like the DNS entries we have for autodiscover for our on-premise S4b. It could very well be that we need to fill in the "Configure Domain" with something, but there's no clear direction on what that should be if we have on-premise S4b possibly conflicting with the Teams autodiscover. That's why I thought we might be able to get away with @onmicrosoft.com but that doesn't appear to be working at this time. I do have a test domain where we could configure proper autodiscover entries that point to O365 for Skype and Exchange on-prem, which would rule out any sort of bug in the code that doesn't want to let us use a mix of domains.

Thank you for any assistance you can provide!

**Comment by scanum** [comment]
@jwinte  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
