### ISSUE TITLE
DST not recognized 

### ISSUE THREAD

**Issue by crossitwe11** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1988]
The phones are not adjusting for DST!   I created a configuration and added my audiocodes C450HD phones.   They are showing the right time according to the time zone, but it is not adjusting for DST.    Please help!

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@crossitwe11  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
