### ISSUE TITLE
Assign a call park policy

### ISSUE THREAD

**Issue by lcansby** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1998]
Looks like the "Manage users" is not available in Teams Admin Center.
The way to assign a Call Part Policy is
1. Go to Microsoft Teams admin center &gt; Users.
2. In the Users page, search for the user by display name or by user name, select the name, and then open user by clicking on the username.
3. In the Assigned policies section click Edit
4. Select the Call park policy from the drop down list. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e03ef3d-81d8-c98f-8427-fe7c008ea30f
* Version Independent ID: 17af3418-b94d-f233-60c0-778b2e8dc02b
* Content: [Call park and retrieve in Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/call-park-and-retrieve?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/call-park-and-retrieve.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/call-park-and-retrieve.md)
* Service: **msteams**
* GitHub Login: @lolaj
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@lcansby Thank you for pointing this out.  I have amended the document to read correctly.

**Comment by scanum** [comment]
@lcansby - We appreciate any feedback that improves the content in the Microsoft docs but we have determined that these changes are not needed. However, in the future we might implement this.
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
