### ISSUE TITLE
Currently MS Teams client is not supported in non-persistent VDI environments

### ISSUE THREAD

**Issue by a-mosheh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2]
Currently MS Teams client is not supported innon-persistent VDI environments. This is not published in the articles and customers are asking for official statement from MS regarding that.

**Comment by alihirsch** [comment]
@ninadara Hi - Can you confirm this statement, or recommend someone on product side who could? (Also, need suggestions on where to include this info in the docs, if it's accurate and necessary.) Thank you.

**Comment by LolaJacobsen** [comment]
@Turgayo can you confirm that we've answered a-mosheh's question in your recent updates to the article?

**Comment by tonysmit** [comment]
@Turgayo. We need you to confirm please.

**Comment by tonysmit** [comment]
@a-mosheh, thanks for the feeback. I'm investigating and trying to find someone on the PG side that can own this issue. In the meantime, if you have a statement or a suggested update to the article, please include it here by doing the update and doing a Pull Request. Thanks, Tony

**Comment by kenwith** [comment]
Ping @Turgayo

**Comment by tonysmit** [comment]
I've assigned two PMs from the product to lend you a hand. We appreciate the feedback. If there are addition/corrections/suggestions to the docs, please edit the topic by clicking Edit (on the right side of the topic) or use VsCode/GtiHub desktop. Let me know how I can help further.

**Comment by tonysmit** [comment]
@juturu and @voltarone  Do you have any feedback on this issue? If you are assign an issue, you must help the customer find a resolution. If it's a bug for engineering create a bug for them, if not and a topic needs updated, you can fix the article and issue a PR. Lastly, if it's a no repo or can't be fixed, then let the customer know and close this out.

**Comment by jambirk** [comment]
@krishra85, can you offer any insight here?

**Comment by krishra85** [comment]
Yes, Teams does not have capabilities to support A/V & conferencing in VDI environments yet. The current articles we have only reference Skype for Business capabilities, so I believe this should be taken up as feedback for the Microsoft Teams team (recommend upvoting a User Voice post for this).

**Comment by jambirk** [comment]
Would it be appropriate to mention this in the Known Issues article for Teams, or is there a better place to surface this?

**Comment by kenwith** [comment]
I added this idea to User Voice here: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/34795351-add-capabilities-to-support-a-v-conferencing-in   Please up-vote everyone so we can get some traction on it. Thank you @a-mosheh for the idea. Sorry for the long delay on this!
