### ISSUE TITLE
Unclear how to configure direct routing resource account in non hybrid scenario

### ISSUE THREAD

**Issue by radderz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2004]
Unclear how to add a Direct Routing based endpoint. It says to use New-CsHybridApplicationEndpoint but is it considered hybrid to use direct routing when it isn't a hybrid deployment?

Can you put in a Direct Routing specific example.

**Comment by radderz** [comment]
https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by radderz** [comment]
@scanum There is a docs linked issue that this could be merged with #2021

**Comment by scanum** [comment]
@radderz - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
