### ISSUE TITLE
Other considerations update?

### ISSUE THREAD

**Issue by MySkypeLab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2007]
There are many out of date points in the Other Considerations list, eg:

- "Currently, you can only invite people from within your company, as it is not yet possible for external users to join meetings."
- "Some online meeting features, such as recording, polling, and whiteboarding are not yet available."
- "Currently, the Teams Meeting add-in in Outlook is only available for Windows users, but support for Mac is coming."

Someone reported one of these 3 months ago and the response was that the documentation was being updated? Status check?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Use the Microsoft Teams Meeting add-in in Outlook](https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@MySkypeLab Thank you for pointing this out and helping improve MS Docs. Could you possibly suggest the changes you recommend to the article and I can have them implemented soonest.

**Comment by scanum** [comment]
@MySkypeLab  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
