### ISSUE TITLE
Office 365 Meeting Room System Licence

### ISSUE THREAD

**Issue by lcansby** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2008]
Missing the option with the new Meeting Room License available in Office 365, please add that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faafee1e-726e-ff90-32bb-59b280a400b3
* Version Independent ID: 82db8cd5-dcd4-1c12-90e0-e5703b760879
* Content: [Microsoft Teams Rooms](https://docs.microsoft.com/en-us/SkypeForBusiness/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/skype-room-systems-v2#feedback)
* Content Source: [Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/skype-room-systems-v2.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/skype-room-systems-v2.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@lcansby Thank you for pointing that out and helping improve MS Docs.  I've added the change.

**Comment by scanum** [comment]
@lcansby Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
