### ISSUE TITLE
HDMI-CEC

### ISSUE THREAD

**Issue by Polleke66** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2011]
In Front of Room Displays you advise to buy Displays that support HDMI-CEC. The Logitech Smartdock does not support this feature, see https://support.logitech.com/en_us/product/smartdock/faq#link_Does-SmartDock-support-CEC-for-attached-displays so maybe it is better to rephrase this text. I have now 22 Samsung screens with HDMI-CEC support that I can't use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68cba21-b43e-ed44-449c-da752f5a0f53
* Version Independent ID: 5a2a2c5e-ad0e-833d-6ab7-74ed26f63d4a
* Content: [Microsoft Teams Rooms maintenance and operations](https://docs.microsoft.com/en-us/skypeforbusiness/manage/skype-room-systems-v2/room-systems-v2-operations#feedback)
* Content Source: [Skype/SfbServer/manage/skype-room-systems-v2/room-systems-v2-operations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/skype-room-systems-v2/room-systems-v2-operations.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by jambirk** [comment]
@davgroom @sohailta 

Please have a look at this comment.  --jambirk

**Comment by scanum** [comment]
@davgroom @sohailta Any updates on this?

**Comment by sohailta** [comment]
Not all MTR systems supports CEC.  Some NUC miniPC supports CEC and provides a BIOS setting to enable it. Unfortunately they cannot be controlled by application SW, therefore is not very useful. You may want to consider some external pass through device like the one below, if you intend to use CEC for your system.
https://www.extron.com/article/hdctl100ad

**Comment by scanum** [comment]
@Polleke66 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by Polleke66** [comment]
@scanum, nope issue has not been resolved, at least to my knowlede. 
On the microsoft site there is still a Note that we should buy screens with CEC for SRS systems:


> A consumer TV used as a front of room display needs to support/enable the Consumer Electronics Control (CEC) feature of HDMI so that it can switch automatically to an active video source from standby mode. This feature is not supported on all TVs.
https://docs.microsoft.com/en-gb/MicrosoftTeams/room-systems/room-systems-v2-operations

Logitech says the exact opposite:

> Logitech SmartDock with Microsoft Surface Pro does not support CEC. It is recommended to use commercial displays with power management capabilities such as schedule on/off times.
https://support.logi.com/hc/en-us/articles/360023367273

**Comment by Polleke66** [comment]
@officedocsbot reopen

**Comment by Polleke66** [comment]
@officedocsbot open
