### ISSUE TITLE
Where did blocking numbers go to?

### ISSUE THREAD

**Issue by Japeth** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2012]
There used to be a doc for blocking incoming numbers in SfB/Teams.
Now this doc is missing?

https://docs.microsoft.com/en-us/skypeforbusiness/what-are-calling-plans-in-office-365/block-incoming-calls

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by CarolynRowe** [comment]
Thank you for your feedback.  Please see the following topic:  https://docs.microsoft.com/en-us/skypeforbusiness/what-are-calling-plans-in-office-365/set-the-caller-id-for-a-user
