### ISSUE TITLE
Inconsistent Database mirroring statement

### ISSUE THREAD

**Issue by ThomasBIDAULT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2013]
Looking at the database mirroring version support, it states that the feature is supported with SQL Server 2016 whereas it's listed as deprecated for SQL 2016 https://docs.microsoft.com/en-us/sql/database-engine/deprecated-database-engine-features-in-sql-server-2016?view=sql-server-2016 . Please update this article accordingly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8c5958a-c5e5-5aba-211a-2886c86ba831
* Version Independent ID: e53ed9d2-4ee4-346a-054b-6cf44b6a189b
* Content: [Back End Server high availability in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/high-availability-and-disaster-recovery/back-end-server#feedback)
* Content Source: [Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/back-end-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/back-end-server.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@ThomasBIDAULT thank you for reaching out. I'll look into this to have the article updated soonest.

**Comment by tomtorggler** [comment]
Is database mirroring supported for Skype for Businesss 2019? If no, why is Database mirroring listed as option for back-end server high availability? Thanks.

**Comment by lindspea** [comment]
@tomtorggler still looking into this.  Will let you know as soon as I have an answer.

**Comment by MicrosoftHeidi** [comment]
This has been resolved in-article.
