### ISSUE TITLE
Set coexistence at group-level?

### ISSUE THREAD

**Issue by guesswho369** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2014]
It would be very useful to have guidance/ability to set coexistence mode at a group level as well as user. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffbf0bfd-c15e-b10b-0cc9-6a27ac1e6634
* Version Independent ID: 58575371-9e09-fadb-76f6-7491df8580a3
* Content: [Setting your coexistence and upgrade settings](https://docs.microsoft.com/en-us/microsoftteams/setting-your-coexistence-and-upgrade-settings)
* Content Source: [Teams/setting-your-coexistence-and-upgrade-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/setting-your-coexistence-and-upgrade-settings.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @guesswho369 thanks for your feedback.
You can create that suggestion in [Teams UserVoice](https://microsoftteams.uservoice.com) as the scope of this issue system is documentation.
Thank you

**Comment by scanum** [comment]
@officedocsbot close
