### ISSUE TITLE
blog post link is dead.

### ISSUE THREAD

**Issue by DaveVernon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2016]
blog post link is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5444a78-4bb2-fbfa-1a91-5af45ad34cad
* Version Independent ID: 0f3e0fff-ca4b-3295-13ea-39da5455a53d
* Content: [GOV, EDU, and non-profit organizations](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/gov-edu-and-nonprofit-organizations)
* Content Source: [Teams/teams-add-on-licensing/gov-edu-and-nonprofit-organizations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/gov-edu-and-nonprofit-organizations.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Jcoetsee** [comment]
@tonysmit Can you potentially look at this and provide an alternative link or URL that provides the information so we can add it back to the article?

**Comment by tonysmit** [comment]
@MicrosoftHeidi - Adding Heidi. She own .GOV stuff and probably can give you a different URL.

**Comment by Jcoetsee** [comment]
Thanks, @MicrosoftHeidi Let me know when you have an alternative URL so I can put in a Pull Request to have the content added please.

**Comment by Jcoetsee** [comment]
@tonysmit If we don't receive a response from Heidi I think I'm going to put in a PR so we have the link removed rather for now so we don't have a link in there since it's not functional.

**Comment by tonysmit** [comment]
Sure go ahead.

________________________________

**Comment by scanum** [comment]
@DaveVernon Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
