### ISSUE TITLE
The IP range of the Media Processors

### ISSUE THREAD

**Issue by AlSmithAU** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#202]
In the Media Processors sections it says "The IP range of the Media Processors is shown in the following table", but the table only has port ranges, not IP ranges. The IP addresses of the Media Processors are not addressed in the document at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff7cb2cb-46b0-92c4-2ce4-871bba863d4e
* Version Independent ID: 351bac36-507d-e4f2-e1e5-1da13ec3233b
* Content: [Plan Direct Routing](https://docs.microsoft.com/en-us/SkypeForBusiness/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/plan-direct-routing#public-trusted-certificate-for-the-sbc)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/plan-direct-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/plan-direct-routing.md)
* Service: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Thank you for your comment.  This is still preview material.  We are planning to address the IP range of the media processors soon, but, in the meantime, we will investigate changing the description of the table to avoid confusion.
