### ISSUE TITLE
Direct Routing

### ISSUE THREAD

**Issue by radderz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2021]
Not clear how to setup a non-hybrid Direct Routing endpoint for an auto attendant resource account. New-CsHybridApplicationEndpoint appears to not be part of the CsOnlineSession imported functions and not clear how to use this to create the resource account without skype for business.

Can you please add a example of setting up a direct routing resource account that doesn't use Skype for Business. We are using an SBC that is certified but has no Skype for Business connection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by radderz** [comment]
#2004 this is a linked question

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @radderz how are you?

I can see that currently that feature is in development, I recommend looking into this resources for more information:

https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=queue

https://techcommunity.microsoft.com/t5/Microsoft-Teams/Auto-Attendant-and-Call-Queues-with-Direct-Routing/td-p/269038

As soon as it is released, documentation will be updated.

Thank you

**Comment by scanum** [comment]
@radderz We appreciate your feedback, we encourage you to keep making the docs better.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by radderz** [comment]
@scanum @get-itips  This feature is released now (Direct routing for Auto Attendant), but the docs aren't clear how to setup a direct routing (from SBC directly) resource account. Can an example be done now?

**Comment by jambirk** [comment]
@waseemhashem  Please contact me so we can resolve this together.

**Comment by scanum** [comment]
@waseemhashem @jambirk Any updates on this? Thanks

**Comment by scanum** [comment]
@waseemhashem @jambirk Any updates on this? Thanks

**Comment by jambirk** [comment]
This is now the final example in the "Create a resource account in Powershell" section. If more is needed please let us know.
