### ISSUE TITLE
Where are the Powershell commands references ?

### ISSUE THREAD

**Issue by nicolasbroisin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2025]
This could be very useful if we could have links references from Powershell cmdlets .. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c8aee4f-05cd-85bf-8e8a-e11fa62b4f08
* Version Independent ID: addd3d3c-e615-67e1-0678-c1d4dc451815
* Content: [Manage meeting settings](https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams#feedback)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @nicolasbroisin 
**Thanks for your feedback.**
Currently, there are no Teams-specific cmdlets to set this configurations, you could also add this suggestion to the Teams user voice https://microsoftteams.uservoice.com/forums/555103-public

Hope this information helps you.

**Comment by scanum** [comment]
@nicolasbroisin We understand this issue has been resolved. Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you for your feedback, we encourage you to keep making the docs better.

**Comment by scanum** [comment]
@officedocsbot close
