### ISSUE TITLE
Followed this article but... Are changes instantaneous?

### ISSUE THREAD

**Issue by Argon0** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2029]
I set a user up with a policy to allow everyone to dial in, (Automatically admit people  set to everyone), and Allow people that dial in to start a meeting  set to on. But a meeting organised by the user, STILL asks for organiser pin, AND says wait for organiser to admit you.

Does it take a certain amount of time for the changes to take effect, or should it be instantaneous, or only on users next login?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@Argon0  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by Argon0** [comment]
Well, when I got to the office this morning it was all working...

Andy
