### ISSUE TITLE
Messaging limits...

### ISSUE THREAD

**Issue by quickclix75** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2030]
I asumme these are in MB ? ta

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#feedback)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by ndambrosio** [comment]
@quickclix75 the values for **File attachments limit ‡** and **Inline images limit ‡** indicate the maximum number of attachments or images allowable for an email sent to a channel’s email address.  The double dagger ‡ next to both features in the table indicates a footnote is present.  Below is the footnote listed under the table:

*‡ If the number of attachments or images exceeds this limit, the message will not be processed and an NDR e-mail will be sent back to the sender notifying them of the error.*

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@quickclix75 Thank you for reaching out and helping improve MS Docs.  Please see @ndambrosio reply above.  I believe this answers your question.  It's the NUMBER of files/attachment, and not MB, TB, etc.

**Comment by quickclix75** [comment]
Thanks both.. totally missed that! Thanks for clarifying.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@quickclix75  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
