### ISSUE TITLE
Round Robin

### ISSUE THREAD

**Issue by ibachus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2031]
Hi, this page is showing Round Robin style for the distribution method but we cannot find this method anywhere in our Call Queue configuration.  Is this feature coming soon or is it already there?  Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b755d9ae-13ac-019f-f5f4-a95b1eee2989
* Version Independent ID: f7afd8ad-e6e0-6c79-aed1-4ee87d48ba12
* Content: [Create a call queue](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue#feedback)
* Content Source: [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-call-queue.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
@waseemhashem  can you comment here? I thought that was already at GA.

**Comment by tonysmit** [comment]
I did look at a Production build and they are available. @waseemhashem - we will need to look further into this and why his organization doesn't see the options.

**Comment by waseemhashem** [comment]
Its coming our with the service update we are rolling out, we started the roll out couple of days ago, we expect it to be available to all customers in 2 weeks

**Comment by ibachus** [comment]
Thank you very much!!  We will look for it soon! :)

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by waelschakaki** [comment]
In both of our customer's tenants we cannot see Microsoft Teams admin center, Voice > Call queues, the only options are Direct routing and Call park, but nothing about voice or phone number, still waiting for this featuer.

**Comment by tonysmit** [comment]
@waseemhashem - any updates? Thanks.

**Comment by waseemhashem** [comment]
The roll-out is still going, we came across couple of issues and paused the expansion for couple of days but now we're on track again. Apologies for the delays, auto attendant and call queues are business critical applications and we want to make sure expansion speed does not compromise the service quality.

**Comment by scanum** [comment]
@ibachus Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by ibachus** [comment]
The feature is there now in our org.  Thank you everyone. :)
