### ISSUE TITLE
Pay per minute rate location - "from" and "to"

### ISSUE THREAD

**Issue by d1bjo0** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2032]
In the section above, "Dial out from meetings" & "Call me at" Details, it notes that rates are based on the "dial out" to location, regardless of where the person on the bridge is located. What is not clear is what defines the origination location. You need a "from" and "to" in order to accurately get the per minute rate from the rate table.  I am going to assume the originating country is based on the meeting organizer license usage location,  but this needs to be stated clearly in the paragraph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 037fe22c-ba09-e381-231d-c37f6bb2a774
* Version Independent ID: e8046130-d407-3155-53c5-9043110cd793
* Content: [Audio Conferencing subscription “Dial-Out”/“Call Me At” benefit](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-subscription-dial-out#feedback)
* Content Source: [Teams/audio-conferencing-subscription-dial-out.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-subscription-dial-out.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @d1bjo0 Thanks for your feedback.

I checked the article and I think that it's self-explanatory and as you also concluded, the from is _Meeting organizer license usage location_ and the to is the _Destination dialed_

**Thank you.**

**Comment by scanum** [comment]
@d1bjo0 We understand this issue has been solved. Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you, we encourage you to keep providing feedback and improving the docs.

**Comment by scanum** [comment]
@officedocsbot close
