### ISSUE TITLE
"在 Microsoft 团队中添加来宾"建议“在 Microsoft Teams中添加来宾”

### ISSUE THREAD

**Issue by tony-xia** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2034]
"在 Microsoft 团队中添加来宾"建议“在 Microsoft Teams中添加来宾”

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 2492e210-08f9-a476-97ec-008926def961
* Version Independent ID: adcb0dd9-4a3c-b665-6e34-ce3276c89b4d
* Content: [Microsoft Teams 中的来宾访问](https://docs.microsoft.com/zh-cn/microsoftteams/guest-access?view=o365-worldwide#feedback)
* Content Source: [Teams/guest-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access.md)
* Service: **msteams**
* GitHub Login: @somakbhattacharyya
* Microsoft Alias: **sbhatta**

**Comment by scanum** [comment]
@officedocsbot assign @officeglobal

**Comment by scanum** [comment]
@OfficeGlobal Hi! Could you please take a look at this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by scanum** [comment]
@OfficeGlobal Any updates on this issue? Thanks

**Comment by OfficeGlobal** [comment]
@tony-xia , @scanum article has been HumanTranslated. The issue is fixed

**Comment by scanum** [comment]
@tony-xia Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
