### ISSUE TITLE
"来宾随时可以通过 Teams Web 和桌面客户端离开团队“

### ISSUE THREAD

**Issue by tony-xia** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2035]
建议改成”来宾随时可以通过 Teams 网页和桌面客户端离开团队“

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 754022e3-49eb-dbd5-e4f5-891c8ebeb491
* Version Independent ID: b73a6f64-d36f-298f-d9ac-34860abad42b
* Content: [来宾加入团队的方式](https://docs.microsoft.com/zh-cn/microsoftteams/guest-joins?view=o365-worldwide)
* Content Source: [Teams/guest-joins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-joins.md)
* Service: **msteams**
* GitHub Login: @somakbhattacharyya
* Microsoft Alias: **sbhatta**

**Comment by scanum** [comment]
@officedocsbot assign @officeglobal

**Comment by scanum** [comment]
@OfficeGlobal Hi! Could you please take a look at this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by scanum** [comment]
@OfficeGlobal Any updates on this issue? Thanks!

**Comment by OfficeGlobal** [comment]
@tony-xia , @scanum article has been HumanTranslated and published live. The issue is fixed

**Comment by scanum** [comment]
@tony-xia Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
