### ISSUE TITLE
"每个来宾的姓名旁边显示“GUEST”标签"

### ISSUE THREAD

**Issue by tony-xia** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2036]
建议改成：每个来宾的姓名旁边显示“来宾”标签
目前中文版本Teams上显示的我记得就是”来宾“

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [来宾体验介绍](https://docs.microsoft.com/zh-cn/microsoftteams/guest-experience?view=o365-worldwide)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @somakbhattacharyya
* Microsoft Alias: **sbhatta**

**Comment by tony-xia** [comment]
说错了，是：每个来宾的姓名旁边显示“访客”标签
目前中文版本Teams上显示的我记得就是”访客”

**Comment by scanum** [comment]
@officedocsbot assign @officeglobal

**Comment by scanum** [comment]
@OfficeGlobal Hi! Could you please take a look at this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by scanum** [comment]
@OfficeGlobal Any updates on this? Thanks.

**Comment by OfficeGlobal** [comment]
@tony-xia , @scanum article has been HumanTranslated and published live. The issue is fixed

**Comment by scanum** [comment]
@tony-xia Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
