### ISSUE TITLE
"Azure Active Directory 中的控件来宾访问"

### ISSUE THREAD

**Issue by tony-xia** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2037]
建议翻译成”在Azure Active Directory中控制来宾的访问“

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 2b05e642-c4e5-f1b5-5315-d3ef1690a0cd
* Version Independent ID: 01b7e0b5-3e50-3de0-e3e9-aeeeda43da12
* Content: [在 Microsoft Teams 中授权来宾访问](https://docs.microsoft.com/zh-cn/microsoftteams/teams-dependencies?view=o365-worldwide)
* Content Source: [Teams/Teams-dependencies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-dependencies.md)
* Service: **msteams**
* GitHub Login: @somakbhattacharyya
* Microsoft Alias: **sbhatta**

**Comment by scanum** [comment]
@officedocsbot assign @officeglobal

**Comment by scanum** [comment]
@OfficeGlobal Hi! Could you please take a look at this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by scanum** [comment]
@OfficeGlobal Hi, any updates on this? Thanks!

**Comment by OfficeGlobal** [comment]
@tony-xia , @scanum article has been HumanTranslated and published live. The issue is fixed

**Comment by scanum** [comment]
@tony-xia Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
