### ISSUE TITLE
Tenant disabled for : Set-CsOnlineVoiceApplicationInstance

### ISSUE THREAD

**Issue by rcvengel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2038]
When i try to use the Set-CsOnlineVoiceApplicationInstance command. It says my tenant is disabled for this.
How can i enable my tenant for this?

Your tenant is Disabled for this service. You are not permitted to use this cmdlet.
    + CategoryInfo          : NotSpecified: (:) [Set-CsOnlineVoiceApplicationInstance], BvdCmdletException
    + FullyQualifiedErrorId : TenantNotEnabledPSTN,Microsoft.Rtc.Management.Hosted.Bvd.SetVoiceAppEndpointCmdlet
    + PSComputerName        : admin1e.online.lync.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/manage-resource-accounts#feedback)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by rcvengel** [comment]
And the link for the more information about Set-CsOnlineVoiceApplicationInstance is not working. 404 error

**Comment by jambirk** [comment]
The feature is still in the process of rolling out.   @waseemhashem may have more detail, and may also know why the documentation for that powershell command isn't live yet.

**Comment by waseemhashem** [comment]
looking into it

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by rcvengel** [comment]
When does this go live?
We are testing out Direct Routing for a few months now. And we really need the Auto Attendant to work with Direct Routing.

**Comment by aluethi** [comment]
Any news on this? Or a timeline when this feature will be available?

**Comment by waseemhashem** [comment]
The rollout of the service upgrade that supports DR with AA started already, we are rolling out gradually and it should be available to all customers in couple of weeks.

**Comment by rcvengel** [comment]
The option Resource accounts is now available in my Teams Admin

**Comment by waelschakaki** [comment]
I am getting the same error message 
Your tenant is Disabled for this service. You are not permitted to use this cmdlet
with some information
TenantNotEnabledPSTN
does it mean that we need to have the calling plan license to use the call queue with a number from the Teams direct routing ? or is it possible at all to use any number in this command ?
Set-CsOnlineVoiceApplicationInstance -Identity testra1@contoso.com
 -TelephoneNumber +14255550100

**Comment by Andersoersted** [comment]
Any news as to how the rollout is going? I to get the error message "Your tenant is Disabled for this service. You are not permitted to use this cmdlet."

**Comment by networkerzz** [comment]
I am also getting the error at Set-CsOnlineVoiceAppliactionInstance :
Your tenant ist Disabled for this service. You are not permitted to use this cmdlet. FullQualifiedErrorId : TenantNotEnabledPSTN,Microsoft.Rtc.Management.Hosted.Bvd.SetVoiceAppEndpintCmdlet

This feature with using your on premise Direct Routing PSTN number would be the feature we are waiting since years and since PSTN Calling Plans are not available in our region. SfB Online Call Queues with MS Service Numbers are not showing up in Teams so they are useless at the moment.

I hope they are rolling out this feature as soon as possible.

**Comment by scanum** [comment]
@networkerzz - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@rcvengel Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
