### ISSUE TITLE
Step 12 screen shot is Skype for Business Server 2015, not 2019

### ISSUE THREAD

**Issue by timhaintz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2039]
The final screen shot displays Skype for Business Server 2015 and should be the 2019 screen shot.
Thanks, Tim.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9131450-3053-fff6-0e01-36c7b3fd076f
* Version Independent ID: 0ad5a095-cbfd-5bcb-6f75-6f696b8215e7
* Content: [Prepare Active Directory for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/install/prepare-active-directory#feedback)
* Content Source: [Skype/SfbServer/deploy/install/prepare-active-directory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/install/prepare-active-directory.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @timhaintz 
**Thank you to taking the time to submit feedback.**

Actually, this article is for both version, this is known issue described here https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/1861 and is currently in the process of being fixed.

Thank You!

**Comment by scanum** [comment]
@timhaintz  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
