### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by ivanja81** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2048]
This documentation is WRONG. See here

We do not, and have never, supported failover by multiple DNS SRV records with different priorities. We support HA by DNS LB across multiple IP addresses published for a single federated partner FQDN – if one edge server goes down then the remaining server(s) will receive all of the inbound traffic.
 
In general, a given customer can have only one edge pool for federation. If they have multiple pools (like SfBO) then all pools must have the exact same certificate and there has to be some external mechanism to route traffic to each site, typically by geo-DNS (like GTM).
 
So documentation is wrong - https://technet.microsoft.com/en-us/library/jj687960(v=ocs.15).aspx. Please submit a content request change (can be done through contentidea)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 391c63a0-d790-1ab0-05ea-c82b8ba366b5
* Version Independent ID: 51fefab7-7fc5-a66e-871b-ff3377f49107
* Content: [Lync Server 2013: Edge Server disaster recovery](https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-edge-server-disaster-recovery)
* Content Source: [Lync/LyncServer/lync-server-2013-edge-server-disaster-recovery.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Lync/LyncServer/lync-server-2013-edge-server-disaster-recovery.md)
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@ivanja81 Thank you for reaching out and helping improve MS Docs.  I can have the content corrected. Could you perhaps give your suggestions for the wording to be amended.  Your help is greatly appreciated.

**Comment by lindspea** [comment]
@ivanja81 Thanks for that information, but please could you clarify which part of the document you suggest needs to be removed and changed/amended.  I will create a PR here which will implement the changes, but I just need more clarity please.

**Comment by ivanja81** [comment]
https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-edge-server-disaster-recovery

“For federation relationships with other organizations running Lync Server, inbound federation requests will continue to work as long as you have configured each Edge pool to have a different priority in your SRV records. Any federation requests that come to an Edge pool that is down will fail back and then connect to an Edge pool which is running”
NOTE: It’s important to understand that federation failover does not provide failover with priority in SRV. Solutions like geo-dns or GTM can help you provide disaster recovery capabilities for federation.

**Comment by lindspea** [comment]
@ivanja81 Thanks Ivan.  So you're suggesting adding that information only, and not removing anything from the article?

**Comment by ivanja81** [comment]
Remove the yellow part as that’s the confusing.

**Comment by lindspea** [comment]
@ivanja81 Sorry for the confusion.  I don't see anything in yellow. Are you suggesting removing this - “For federation relationships with other organizations running Lync Server, inbound federation requests will continue to work as long as you have configured each Edge pool to have a different priority in your SRV records. Any federation requests that come to an Edge pool that is down will fail back and then connect to an Edge pool which is running” and adding this - "NOTE: It’s important to understand that federation failover does not provide failover with priority in SRV. Solutions like geo-dns or GTM can help you provide disaster recovery capabilities for federation."

**Comment by ivanja81** [comment]
Proposal

For federation relationships with other organizations running Lync Server, inbound federation requests will continue to work as long as you have solutions like Geo-DNS GTM.  It’s important to understand that federation failover does not provide failover with priority in SRV records. Solution earlier provided can help you provide disaster recovery capabilities for (inbound) federation."

**Comment by scanum** [comment]
@ivanja81  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
