### ISSUE TITLE
Wrong vendor name

### ISSUE THREAD

**Issue by Polleke66** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2050]
The Sennheiser Evolve 65T should be a Jabra Evolve 65T if you ask me.

regards, Paul

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63af828-0b5a-ba28-7fa6-0016b0b9a355
* Version Independent ID: 0e7b881f-f4bd-94b9-cefc-0bcc2040a7c1
* Content: [Phones and Devices for Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/certification/devices-usb-devices)
* Content Source: [Skype/SfbPartnerCertification/certification/devices-usb-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbPartnerCertification/certification/devices-usb-devices.md)
* Service: **skype-for-business**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@Polleke66 Thank you for reaching out and helping improve MS Docs.  I'll have the changes made and approved soonest.

**Comment by scanum** [comment]
@Polleke66  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
