### ISSUE TITLE
Teams Usage Report very inaccurate

### ISSUE THREAD

**Issue by SamCosby** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2052]
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md#microsoft-teams-usage-report

This needs to be updated and reflected to what's accurrate. Today, there's no option to download reports, or print reports in the Modern Portal. Additionally, there are multiple filters that do not exist that show in the screenshots, which is confusing customers and causing tickets to be created.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@SamCosby Thank you for pointing this out and helping improve MS docs.  I'll have the team look into this.

**Comment by LanaChin** [comment]
The reporting articles have been reviewed, updated, and republished.  Thank you.
