### ISSUE TITLE
The section "NAT Requirements for External User Access" deserves some simplification

### ISSUE THREAD

**Issue by robertpp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2055]
#### Issue Description:

The article is a bit confusing in its attempt to associate the apparently non-standard denomination ChangeDST/ChangeSRC with various NAT features and names. There is also a lot of repetition in the article.

---

#### Proposed Change:

+ Update the title of the section "[NAT Requirements for External User Access](https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-determine-external-a-v-firewall-and-port-requirements#nat-requirements-for-external-user-access)" to "NAT requirements for A/V Edge service".
+ Remove all references to ChangeDST and ChangeSRC.
+ Remove the key points.
+ Replace the required NAT behavior description with the text below.
+ Add the updated NAT requirements section in the ['Edge Environmental Requirements](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/edge-server-deployments/edge-environmental-requirements)' article from the Skype for Business Server documentation.

---

The NAT behavior required for the external interface of the Edge Server is as follows:

- For traffic from the Internet **or a local A/V Edge service**, change the destination IP address:
  - Leave intact the source IP address.
  - Change the destination IP address from the NAT-enabled public IP address of the A/V Edge service to its external IP address.

- For traffic from the A/V Edge service to the Internet, change the source IP address:
  - Change the source IP address from the external IP address of the A/V Edge service to the NAT-enabled public IP address.
  - Leave intact the destination IP address.

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 979e5087-7b5e-0718-adab-75d35efb4e58
* Version Independent ID: 668ef845-73a5-9574-4a26-9a34a04d3499
* Content: [Lync Server 2013: Determine external A/V firewall and port requirements](https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-determine-external-a-v-firewall-and-port-requirements#nat-requirements-for-external-user-access)
* Content Source: [Lync/LyncServer/lync-server-2013-determine-external-a-v-firewall-and-port-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Lync/LyncServer/lync-server-2013-determine-external-a-v-firewall-and-port-requirements.md)
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by robertpp** [comment]
At second thought, the addition marked in bold looks more like an optimization than a requirement. The full NAT should also apply to the media traffic between two federated A/V Edge servers.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@robertpp Thank you for reaching out and helping improve MS Docs.  Please could you send your final suggestions for wording and I can have the team approve it soonest.

**Comment by robertpp** [comment]
**NAT requirements for the Edge service**

The following NAT requirements apply if you choose to configure non-routable private IP addresses for the Edge service:

- NAT can only be used with DNS load-balancing. NAT is not supported with a hardware load balancing (HLB)  Edge topology.
- NAT can only be used on the external Edge interface. NAT is not supported on the internal Edge interface.
- NAT must be symmetric for incoming and outgoing traffic.
- For traffic from the Internet, NAT must change the destination IP address from the NAT-enabled public IP address of the A/V Edge service to its external IP address. The source IP address must remain intact, so that the A/V Edge service can find the optimal media path.

   For example, in the inbound direction in the figure below, the public IP address 131.107.155.30 was changed to the external (private) IP address 10.45.16.10. The source IP address remained unchanged.

- For traffic from the A/V Edge service to the Internet, NAT must change the source IP address from the external IP address of the A/V Edge service to the NAT-enabled public IP address.

   For example, in the outbound direction in the figure below, the external (private) IP address 10.45.16.10 was changed to the public IP address 131.107.155.30.

**Figure. How NAT changes the destination IP address for inbound traffic and the source IP Address for outbound traffic**

**Comment by lindspea** [comment]
@robertpp Are you suggesting removing all the text under "NAT Requirements for External User Access" and replacing it with your suggested points above and changing the title to "NAT requirements for the Edge service."?

**Comment by robertpp** [comment]
Yes. The change comes a bit late in the product’s lifecycle. I think it’s not too late to make this change, since it might take a while before the article is retired, while have clearer information may still be of use.

Kind regards,
Robert Panduru

Support Escal Eng
Unified Communications
Customer Services and Support

+40 (31) 133-0704
robertpp@microsoft.com<mailto:robertpp@microsoft.com>
Mon-Fri 9-18 UTC+2 Bucharest

[Microsoft Logo]
Team Manager | Mirela Oprisan (simonamo@microsoft.com<mailto:simonamo@microsoft.com> | +40 (31) 133-0733
Technical Advisor | Andrea Hauszar (ahauszar@microsoft.com<mailto:ahauszar@microsoft.com> | +40 (35) 663-2277

Microsoft is committed to protecting your privacy. Please read the Microsoft Privacy Statement<http://privacy.microsoft.com/en-gb/default.mspx> for more information.

**Comment by scanum** [comment]
@robertpp Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by robertpp** [comment]
@scanum: Thank you for the update. I do not know how to re-open the issue and if possible I would like not to open another issue for the same.

There are just two corrections still needed:
a. The two 'For example...' paragraphs are part of the bullets above them. The current alignments make them look as new (stand-alone) paragraphs. Apologies for this not being evident in the original proposal.
b. The 'Key points: ...' paragraph under the picture is no longer relevant and must be removed. Its information is also provided in the 'For example...' paragraphs mentioned above.

**Comment by scanum** [comment]
@robertpp Hi Robert, thanks for getting back to us. We appreciate your contribution to the docs, we will take the information and suggestions provided in order to create a future doc for this theme.  As for right now, the 2013 document will stay the same. However, as I mentioned, suggestions and comments will be considered when making a new version of this document. Thanks again.

**Comment by robertpp** [comment]
Thank you for the answer and for your efforts, Manuela. I have no further suggestions at this time.
