### ISSUE TITLE
Can this be created in PowerShell?

### ISSUE THREAD

**Issue by rhymeswithmogul** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2057]
Can an org-wide team be created with PowerShell?  I've seen several links on personal blogs and other websites linking to a page on Microsoft.com that has since be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@rhymeswithmogul Thank you for reaching out.  Let me check with the team and I'll get back to you soonest.

**Comment by rhymeswithmogul** [comment]
> @rhymeswithmogul Thank you for reaching out. Let me check with the team and I'll get back to you soonest.

Thank you.  The broken link I'd seen shared around the Internet was: https://www.microsoft.com/en-us/download/details.aspx?id=56501  The link died and there's no redirect to the current documentation; just an error page.

**Comment by lindspea** [comment]
@rhymeswithmogul I understand you cannot. To create Teams from Powershell you should use New-Team cmdlet and it allows you to create public or private teams:   https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps

**Comment by scanum** [comment]
@rhymeswithmogul Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
