### ISSUE TITLE
TeamsAppPermissionPolicy

### ISSUE THREAD

**Issue by toddjohnson39** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2059]
Is 'TeamsAppPermissionPolicy' available? I can't find any documentation on how to configure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9f904e5-d015-70b0-b809-9b0b62931ab5
* Version Independent ID: aa59fcc6-0a6d-c82f-6b5e-ffb85e08ea8a
* Content: [Manage Teams during the transition to the new Microsoft Teams admin center](https://docs.microsoft.com/en-US/microsoftteams/manage-teams-skypeforbusiness-admin-center)
* Content Source: [Teams/manage-teams-skypeforbusiness-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-teams-skypeforbusiness-admin-center.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@toddjohnson39 Thank you for reaching out.  I'll have an answer for you in the next couple of days.

**Comment by lindspea** [comment]
@toddjohnson39 Please have a look at this article and let me know if you need any further assistance.
https://docs.microsoft.com/microsoftteams/enable-features-office-365.

**Comment by scanum** [comment]
@toddjohnson39 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by toddjohnson39** [comment]
I reviewed that link and it doesn't talk about how to setup a TeamsAppPermissionPolicy. The comment on this page references this policy type, however there is no link provided that details how to implement. "Default apps and external apps can be enabled and disabled at the user level in TeamsAppPermissionPolicy. Additionally, apps can be blocked at the tenant level in org-wide app settings which overrides any user and tenant-level settings."

**Comment by toddjohnson39** [comment]
The configuration in the link provided would apply to all users, what I am trying to achieve is the ability to create custom policies for different user groups.

**Comment by lindspea** [comment]
@toddjohnson39 Hope this one helps.  https://docs.microsoft.com/microsoftteams/teams-custom-app-policies-and-settings. Please let me know soonest if this link helps.

**Comment by toddjohnson39** [comment]
Thanks, This link doesn't discuss app permission policies, but led me to the correct article that does.

https://docs.microsoft.com/en-us/microsoftteams/teams-app-permission-policies

Thanks!
[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/microsoftteams/teams-app-permission-policies>

Manage app permission policies in Microsoft Teams | Microsoft Docs<https://docs.microsoft.com/en-us/microsoftteams/teams-app-permission-policies>
Say, for example, you want to block all third-party apps and allow specific apps from Microsoft for the HR team in your organization. You would create a custom policy named HR App Permission Policy, set it to block and allow the apps that you want, and then assign it to users on the HR team.
docs.microsoft.com


________________________________

**Comment by lindspea** [comment]
@toddjohnson39 That's great news. Thanks for letting me know.
