### ISSUE TITLE
Typo on Allowing a Number Section (Get-CsInb undBlockedNumberPattern)

### ISSUE THREAD

**Issue by martinboam** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#206]
Typo spotted - Get-CsInb undBlockedNumberPattern

I think this should be Get-CsInboundBlockedNumberPattern

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d542d4a-7613-70a9-e70f-7b51e673edcf
* Version Independent ID: 7486d73b-717a-18a8-c909-5658f1ba0de3
* Content: [Block Inbound Calls in Skype for Business Online](https://docs.microsoft.com/en-us/skypeforbusiness/what-are-calling-plans-in-office-365/block-incoming-calls)
* Content Source: [Skype/SfbOnline/what-are-calling-plans-in-office-365/block-incoming-calls.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/what-are-calling-plans-in-office-365/block-incoming-calls.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@martinboam - exactly correct and I submitted this [PR](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/compare/live...kenwith-patch-6?quick_pull=1) to fix. Thanks for noticing this! 

Also, these docs are open now and if you are interested to submit a Pull Request to fix typos like this you will show up in the Contributor list so the community can see your effort.

Thanks for taking the time to report!
