### ISSUE TITLE
On the Chinese translation of the name of General channel

### ISSUE THREAD

**Issue by excelcaptain** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2060]
The English version of "General " is "综合" on the Chinese version, but the Chinese Docs help use "常规", which is wrong

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6c9902e8-a0b7-b6af-4656-2024849a5e8b
* Version Independent ID: 85beb9a7-2682-b52e-210b-20e598e3dab3
* Content: [在 Microsoft Teams 中创建首批团队和频道](https://docs.microsoft.com/zh-cn/MicrosoftTeams/get-started-with-teams-create-your-first-teams-and-channels#feedback)
* Content Source: [Teams/get-started-with-teams-create-your-first-teams-and-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-started-with-teams-create-your-first-teams-and-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@Office Global.

**Comment by scanum** [comment]
@officeglobal Hi, could you please investigate this issue? Thanks.

**Comment by scanum** [comment]
@OfficeGlobal any updates on this issue?

**Comment by scanum** [comment]
@OfficeGlobal any updates on this issue?

**Comment by OfficeGlobal** [comment]
Working on fix.

**Comment by scanum** [comment]
@OfficeGlobal Any updates on this? Thanks!

**Comment by OfficeGlobal** [comment]
@scanum , @excelcaptain article has been HumanTranslated and published live. The issue is fixed

**Comment by scanum** [comment]
@excelcaptain Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
