### ISSUE TITLE
Adding a bot by GUID is for testing only

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2062]
We don't recommend adding a bot by GUID for anything other than testing purposes. Doing so severely limits the functionality of a bot. Bots in production use should be added to Teams as part of an app. See:

https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-create
 https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-test

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1257b9b-73ca-8a97-3f65-a7c8d5937e8c
* Version Independent ID: 5f9b5fad-dceb-3f9e-192c-a31ca05e0b83
* Content: [Add bots for private chats and channels in Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/add-bots#feedback)
* Content Source: [Teams/add-bots.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/add-bots.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@clearab Thank you for reaching out.  I'll investigate with the team and add the necessary changes to the information in the document once approved.

**Comment by LolaJacobsen** [comment]
@larryjin is the PM for this feature area. Larry, could you respond to this issue please?

**Comment by lindspea** [comment]
@larryjin

**Comment by scanum** [comment]
Hi @larryjin Any updates on this? Thanks!

**Comment by clearab** [comment]
Hi - I actually work for Larry and own the Teams Platform developer documentation. Would you like me to submit a PR with suggested changes?

**Comment by lindspea** [comment]
That would be great thanks Andrew.

**Comment by lindspea** [comment]
@clearab Hi Andrew, just following up on PR when you get a chance thank you.

**Comment by lindspea** [comment]
@clearab @larryjin just following up with regards to the PR?  Please let me know if you're still able to submit a PR with suggested changes. Thanks in advance for your help.

**Comment by scanum** [comment]
@clearab We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot open

**Comment by scanum** [comment]
@clearab Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@officedocsbot close

**Comment by nitishr06** [comment]
Hi Team,
After uploading the app package, when I tried to install bot for the testing from Test and Distribute section, it's giving me an error "You don't have permissions to add #bot_name to this team." when i clicked on intall button. kindly guide me what permisson i require to install the bot.
