### ISSUE TITLE
Dial-in users are not recorded

### ISSUE THREAD

**Issue by cistaroj** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2065]
There should be a caveat to this document that indicates that a dial-in user is not recorded on the MP4 artifact.  There should be some explanation as to why?  It is curious that when dialed-in, the IVR announce that the recording has started/stopped...Yet the telephone joiners are not actually recorded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc7d1bd2-f89d-4ae6-d5e3-a226b7039237
* Version Independent ID: e86b7c7b-a3d8-9e89-96f9-5d5415d8205d
* Content: [Let people record their audio and video conferences](https://docs.microsoft.com/en-us/skypeforbusiness/set-up-skype-for-business-online/let-people-record-their-audio-and-video-conferences#feedback)
* Content Source: [Skype/SfbOnline/set-up-skype-for-business-online/let-people-record-their-audio-and-video-conferences.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-skype-for-business-online/let-people-record-their-audio-and-video-conferences.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@cistaroj  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
