### ISSUE TITLE
Typo and Number Patterns

### ISSUE THREAD

**Issue by martinboam** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#207]
Few things i wanted to check

Think theres a typo here. Should be OnPremLineURI not OnPremisLineURI
Set-CsUser - “Spencer Low" -OnPremisLineURI tel:+14255388797 -EnterpriseVoiceEnabled $true -HostedVoiceMail $true

Number pattern is wrong on "Which Should return" for other +1
Identity        : Other +1 
Priority            : 4
Description     : 
NumberPattern       : ^\+1(425|206) (\d{7})$
OnlinePstnUsages    : {US and Canada}    
OnlinePstnGatewayList   : {sbc5.contoso.biz, sbc6.contoso.biz}
Name            : Other +1

Creating a Voice Routing Policy with several PSTN Usages diagram 
- Bottom one shows sbc3 and 4 and i think should be sbc 5 and 6.
- Having priorities with numbers may be better than having auto assigned on diagram
- Is the number pattern for other +1 correct in diagram
- Same diagram is then used for assigning voice routing policy with several pstn usages so updates to other diagrams may be needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0853cc6-9088-41e3-17f8-2fac2baecb8a
* Version Independent ID: 1e62ee34-a122-8152-a75f-e2a2c8e35aa0
* Content: [Configure Direct Routing](https://docs.microsoft.com/en-us/SkypeForBusiness/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/configure-direct-routing)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/configure-direct-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/configure-direct-routing.md)
* Service: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Thanks for the corrections. We'll have to verify with someone in the product group and they're travelling at the moment. Give us a few days to sort this out?

**Comment by jambirk** [comment]
Issue should be resolved by https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/pull/1093
