### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2073]
This page is blank, but it's the first search result from here https://docs.microsoft.com/en-us/search/index?search=cloud+voicemail

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 283d323b-ac4e-e9a6-9fa2-19f4945a0376
* Version Independent ID: f9b5a089-3fb7-4194-1736-293aea7a753e
* Content: [Cloud Voicemail](https://docs.microsoft.com/en-us/skypeforbusiness/what-is-phone-system-in-office-365/phone-system-voicemail/phone-system-voicemail)
* Content Source: [Skype/SfbOnline/what-is-phone-system-in-office-365/phone-system-voicemail/phone-system-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/what-is-phone-system-in-office-365/phone-system-voicemail/phone-system-voicemail.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@TorrenManson Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
