### ISSUE TITLE
KB 4340904 link is incorrect

### ISSUE THREAD

**Issue by AmandaAZ** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2074]
KB 4340904 link is pointing to https://support.microsoft.com/en-us/help/3134260/march-2016-cumulative-update-6-0-9319-235-for-skype-for-business-serve. It should be linked to https://support.microsoft.com/help/4340904.

**Comment by scanum** [comment]
@AmandaAZ  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
