### ISSUE TITLE
Invalid charactor in the sample script.

### ISSUE THREAD

**Issue by shinicht** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2077]
in the following line has invalid character of '–'.

        Remove-Item –Path $TeamsPath -Recurse

The '–'  in the –Path argument is invalid. This is not '-' .
Please fix this. Thanks,  

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: c642df17-1656-7c29-9fc3-04f70689f902
* Version Independent ID: 63bef712-cfb2-9efc-0b62-f68b0968b84c
* Content: [Microsoft Teams の展開のクリーン アップを支援する PowerShell スクリプトのサンプル](https://docs.microsoft.com/ja-jp/microsoftteams/scripts/powershell-script-teams-deployment-clean-up#feedback)
* Content Source: [Teams/scripts/Powershell-script-teams-deployment-clean-up.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/scripts/Powershell-script-teams-deployment-clean-up.md)
* Service: **msteams**
* GitHub Login: @Lester-Hewett
* Microsoft Alias: **lehewe**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by ojrb** [comment]
Hi @scanum ! the PR #2198 solved this issue ! Please review and Merge !

**Comment by scanum** [comment]
@shinicht Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
