### ISSUE TITLE
Way to cancel the upgrade?

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2082]
We've already moved over to Teams for everyone, yet the page still says that we'll be upgrading in the next few weeks. Is there a way to cancel this notice from being sent to users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56ab9d91-d5c4-be13-660e-10b1fdacadec
* Version Independent ID: efdd6696-1415-26ae-ab56-5e758a34311c
* Content: [Upgrade checklist](https://docs.microsoft.com/en-US/MicrosoftTeams/upgrade-basic?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/upgrade-basic.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-basic.md)
* Service: **msteams**
* GitHub Login: @dearbeen
* Microsoft Alias: **dearbeen**

**Comment by scanum** [comment]
@StuBeck32  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
