### ISSUE TITLE
Can't push out Custom Theme to Skpe Room Systems Computer.

### ISSUE THREAD

**Issue by rbramble** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2083]
I am trying to follow the directions but I get "Network Path Not Found" 
I am wondering if the $targetDevice line is correct or not.
This is the current $targetDevice line. 
$targetDevice = "\\&lt;Device fqdn&gt; \Users\Skype\AppData\Local\Packages\Microsoft.SkypeRoomSystem_8wekyb3d8bbwe\LocalState\SkypeSettings.xml";

It has an extra space around &lt;Device fqdn&gt; and \Users.
I have tried a couple of variations but I am not having much luck.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68cba21-b43e-ed44-449c-da752f5a0f53
* Version Independent ID: 5a2a2c5e-ad0e-833d-6ab7-74ed26f63d4a
* Content: [Microsoft Teams Rooms maintenance and operations](https://docs.microsoft.com/en-us/skypeforbusiness/manage/skype-room-systems-v2/room-systems-v2-operations#feedback)
* Content Source: [Skype/SfbServer/manage/skype-room-systems-v2/room-systems-v2-operations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/skype-room-systems-v2/room-systems-v2-operations.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@rbramble  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by rbramble** [comment]
I think it is because we joined these devices to the domain and turned on the firewall. I don't think we have the group policies right yet to allow access to the file locations yet.
