### ISSUE TITLE
Requirements for Cloud Voicemail

### ISSUE THREAD

**Issue by JeffBrownTech** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2088]
Under the section "Cloud-only environments: Set up Cloud Voicemail", it mentions that a phone number must be assigned before cloud voicemail is enabled. I believe this was recently changed where VoIP-only users will now have cloud voicemail enabled even if they do not have a phone number assigned:

https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&filters=&searchterms=33579

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8228f9b2-a7de-abb4-6f41-70db0b3af155
* Version Independent ID: 8fd9fafb-dd76-59a8-e609-56f06d539a31
* Content: [Set up Cloud Voicemail](https://docs.microsoft.com/en-us/microsoftteams/set-up-phone-system-voicemail#feedback)
* Content Source: [Teams/set-up-phone-system-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-phone-system-voicemail.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by tonysmit** [comment]
@JeffBrownTech - All users ( PSTN to desktop phone - not Teams enabled, PSTN and Teams client on a Teams enabled phone, Teams app to Teams app) calls have cloud voice mail.

**Comment by CarolynRowe** [comment]
I am reopening this issue because we are revising this topic and the on-premises cloud voicemail topic to ensure both are in sync.

**Comment by rae-alisyed** [comment]
How do we disable voicemail feature that was enabled automatically in our Teams application?

**Comment by tonysmit** [comment]
Hey @rae-alisyed - You can disable voicemail for a single user or all users in your org buy using the Set-TeamsCallingPolicy cmdlet. There is no UI to do it. 

To disable it for everyone:
Set-CsTeamsCallingPolicy -Identity Global -AllowVoiceMail $false

https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps
