### ISSUE TITLE
SRSv2 not working correctly after SCCM deployment

### ISSUE THREAD

**Issue by jholl016** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#209]
I have successfully configured the task sequence described in this article, but the SRS app is not working correctly.  The build appears to complete fine, the Skype user automatically signs in, and the SRS app runs by default. I can login to the SRS app with the room account just fine.  The one piece that's not working is the "Settings" command (accessed via the menu that appears when you press the settings icon at the bottom right of the UI).  When I choose "Settings" from that menu, I hear a Windows message/error "ding" in the background, but nothing appears on the screen and no UI changes occur.

I think there are a couple problems with these instructions:
* When I connect to the SRS system with remote management tools, I can see that the Skype user exists, but the Admin user does not. There probably needs to be an additional Task Sequence step for that.
* The FinalSetup.ps1 script includes steps to install the appx package for both users: Skype and Admin.  It correctly passes a PSCredential to run the appx install for the Skype user.  However, it makes no similar accommodation for the Admin user.  As far as I can tell, the author of that FinalSetup.ps1 script assumed that the script would always be run as the Admin user.  The SCCM task sequence has that script executing under SYSTEM context.  So that won't work.  FinalSetup.ps1 either needs to be revised to pass the appropriate PSCredential to install the appx for Admin.  Or, perhaps the corresponding task sequence step could be modified to run under the proper execution context?

I'm tinkering with this now and trying to get it to work.  If I stumble upon a working configuration, I'll reply here.  If you have any ideas or pointers, I'm all ears.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29b0551a-0c9b-8934-5e4b-d34fe292ec8e
* Version Independent ID: 1e19dcb0-59cd-5e9f-0afc-e30bc4cbf80f
* Content: [Deploy Skype Room Systems by using System Center Configuration Manager](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/room-systems-scale)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/room-systems-scale.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/room-systems-scale.md)
* Service: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
That topic is a new one from the SOF/Fast Track folks. I’ve assigned the guy who wrote and verified that page.

____________________________________________________________
James Birkinshaw     |    Skype for Business ITPro Content

**Comment by jholl016** [comment]
UPDATE: I got everything working.  I think the erroneous behavior was being triggered by some Group Policies that were screwing things up.  Sorry for the false alarm.  Once I stumbled across the page about "Domain Join Considerations", I realized I had more to correct on my end.  Everything seems to be working correctly now using the task sequence as currently published.  Thanks.

**Comment by jholl016** [comment]
This is the article that was extremely helpful: https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/domain-joining-considerations

**Comment by jholl016** [comment]
Also, with regard to the 'Admin' local account, it seems that account is not needed for a domain-joined room system.  So, that's why it was left out of the task sequence. :)

**Comment by jholl016** [comment]
With regard to FinalSetup.ps1, it contains this code:
```
# Install Rigel App for Admin user
start-process -FilePath powershell.exe -wait -ArgumentList @("-executionpolicy","Unrestricted","$Env:SystemDrive\Rigel\x64\Scripts\Provisioning\InstallSkype.ps1")
```
When executed by SCCM in system context, this process errors out, b/c you can't install appx packages to the system account.  If you watch the SCCM build very diligently, you can actually see this error appear on screen briefly.  Ultimately, it doesn't affect the successful completion of the task sequence, though.

**Comment by Turgayo** [comment]
I am glad to hear that you got everything working as expected. 
Thanks for the feedback on the Group Policies. I will update the guidance to include reference to the domain considerations, to gets everyone's attention to that important topic.

**Comment by Turgayo** [comment]
Also remember that you can use [OMS Guidance](https://docs.microsoft.com/en-us/SkypeForBusiness/plan-your-deployment/clients-and-devices/oms-management) to monitor your Skype Room Systems v2 deployments.
