### ISSUE TITLE
Not deploying in Task Sequence

### ISSUE THREAD

**Issue by jwillenborg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2090]
Hello,

Anybody else having trouble getting this MSI deployed in a task sequence. I had it working a week ago, however I redownloaded the MSI (for updates) and now when I drop it in my MDT task sequence, Teams installs, however it ignores msiexec /i Teams_windows_x64.msi OPTIONS="noAutoStart=true" switch. It works fine manually, however autostart will not disable from task sequence.

**Comment by scanum** [comment]
@jwillenborg - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
