### ISSUE TITLE
AppSharing Port Start and count Protocol is incorrect.

### ISSUE THREAD

**Issue by greganth1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2091]
Protocol for AppSharing should be TCP, not UDP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43190e0d-852f-8066-510f-76cad6fcae85
* Version Independent ID: ee3209ad-6e6e-6640-c46d-4017d628358f
* Content: [Video based Screen Sharing for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/manage/video-based-screen-sharing#feedback)
* Content Source: [Skype/SfbServer/manage/video-based-screen-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/video-based-screen-sharing.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@greganth1 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
