### ISSUE TITLE
MSI switches ignored during MDT Task Sequence

### ISSUE THREAD

**Issue by jwillenborg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2092]
Hello,
Anybody else having trouble getting this MSI deployed in a task sequence. I had it working a week ago, however I redownloaded the MSI (for updates) and now when I drop it in my MDT task sequence, Teams installs, however it ignores msiexec /i Teams_windows_x64.msi OPTIONS="noAutoStart=true" switch. It works fine manually, however autostart will not disable from task sequence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Microsoft Teams using MSI via SCCM](https://docs.microsoft.com/en-us/MicrosoftTeams/msi-deployment#feedback)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @Lester-Hewett
* Microsoft Alias: **lehewe**

**Comment by scanum** [comment]
@jwillenborg  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by jwillenborg** [comment]
I figured out the issue. When I was creating my image, i didn't know Microsoft had started to include Teams into the Office 365 ProPlus installer. I was essentially trying to install the Teams MSI on a device that already had Teams (doesn't work out). To fix, I just deleted the Teams that came with the ProPlus installer and now my deployments are working fine.
