### ISSUE TITLE
Privileges required to Enable Skype Meeting Broadcast

### ISSUE THREAD

**Issue by HoCGeek** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2094]
Please explain why Global Admin privileges are required to enable an SfB feature.  Why would this require Global Admin rather than Skype for Business Administrator?  What's the point in having 30 different "administrator" roles in AzureAD for more granularity of permissions if all operations are going to require Global Admin?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61e646a9-4d87-5d52-c2ad-bb389beb35fa
* Version Independent ID: 531ac427-7f6e-4b6b-2495-7adcaed9f23b
* Content: [Enable Skype Meeting Broadcast](https://docs.microsoft.com/en-us/skypeforbusiness/set-up-your-network-for-skype-meeting-broadcast/enable-skype-meeting-broadcast#feedback)
* Content Source: [Skype/SfbOnline/set-up-your-network-for-skype-meeting-broadcast/enable-skype-meeting-broadcast.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-your-network-for-skype-meeting-broadcast/enable-skype-meeting-broadcast.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @HoCGeek 

Thank  you for reaching out!

We can enable the Broadcast feature using the Skype/Team admin account as well. It has not been mentioned on the document that this feature can only be enabled with the global admin account. It works with the skype admin account as well. 

Hope this clarifies your query. Kindly confirm. Thank you.

**Comment by HoCGeek** [comment]
Are you saying that the configuration can be completed using a Skype for Business administrator account or a Teams Service Administrator account?  What about a Teams Communications administrator account?  

Where would someone be able to see that any of these levels of permissions would be adequate to configure this feature?  How would we be expected to figure this out?  Trial and error?

You're right that it doesn't explicitly say that this feature can only be enabled with a global admin account, but the fact that 
1) step one says "Sign in with your Office 365 global admin account"
2) no description is provided for the access required to perform the configuration 
3) no alternative levels of privileges are even mentioned 
… certainly implies that Global Admin credentials are required.  If that is not the intent, then I would suggest changing the first instruction to either "Sign in with an account with XXX privileges to your Office 365 subscription" or "Sign in to your Office 365 subscription as a Global administrator, Skype for Business administrator, Teams Service Administrator, or Teams Communications Administrator".

Shortcutting the documentation to suggest using Global Admin privileges is a lazy, insidious habit that leads to too many permissions being granted to too many people when they don't need them.  This is against Microsoft's own recommended best practices.  As part of the governance team for our Azure subscription, I have little to no leverage to tell requestors that they can't have Global Admin access when they can point to your own documentation and say "look, Microsoft's instructions say 'Sign in with your Office 365 global admin account', so I need a Global Admin account".  Please do better at documenting the actual required permissions - preferably using the least-privilege model.

Thanks,

Dan

**Comment by sowjanya365** [comment]
Hi @HoCGeek 

Thank you very much for the contribution and sharing your views. Much appreciated.

Yes, Skype meeting broadcast can be enabled by the Skype or Global administrator. Document has been updated accordingly now. 

Hope this clarifies your query. Kindly confirm. Thank you.

**Comment by HoCGeek** [comment]
Which document was updated?  When I check the document here: https://docs.microsoft.com/en-us/skypeforbusiness/set-up-your-network-for-skype-meeting-broadcast/enable-skype-meeting-broadcast it looks the same as before.  As a matter of fact, I found additional issues with the document while looking for the changes you mentioned…


  *   The first section says “To do this, you need to know how to use Windows PowerShell.”, but the second section explains how to make the change using the admin center, no PowerShell required.
  *   The second section (Enable Skype Meeting Broadcast using the Skype for Business admin center) still says “Sign in with your Office 365 global admin account…” – suggesting global admin rights are required
  *   The third section (Enable Skype Meeting Broadcast using PowerShell) tells you how to connect using PowerShell, but gives no guidance at all about what level of permissions are required to make the configuration change.

Please let me know if/when the documentation has been updated.

Thanks,

Dan

**Comment by sowjanya365** [comment]
Hi @HoCGeek 

We've created this PR with the required changes. Once it gets merged with the current document you will be able to see the changes. 

And regarding the level of permissions required with the PowerShell, It's the same as GUI permissions. One who executes the commands needs to be a Skype for business administrator or global administrator. 

Thank you for your contribution.

**Comment by sowjanya365** [comment]
Hi @scanum 

Kindly coordinate and get this PR approved. 

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/2330

Thank you.

**Comment by scanum** [comment]
@HoCGeek Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
