### ISSUE TITLE
 Skype for Business Admin center missing

### ISSUE THREAD

**Issue by KNormanGH** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2098]
We do not have a Skype for Business admin center in our portal.  I do see Skype under Settings, Services and Add-ins, but it fails to load. Error:  Unable to retrieve settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd7daebf-3721-4820-bb37-9d0c403612a3
* Version Independent ID: e1f28553-2c7f-ba46-1758-271c8921a868
* Content: [Admins Configure Skype for Business settings for individual users](https://docs.microsoft.com/en-us/skypeforbusiness/set-up-skype-for-business-online/configure-skype-for-business-settings-for-individual-users#feedback)
* Content Source: [Skype/SfbOnline/set-up-skype-for-business-online/configure-skype-for-business-settings-for-individual-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-skype-for-business-online/configure-skype-for-business-settings-for-individual-users.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@KNormanGH - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
