### ISSUE TITLE
Ambiguous statement

### ISSUE THREAD

**Issue by NickElniff** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2099]
This statement is ambiguous:
"A call is determined to be domestic if the called phone number is in the same country as the country that has been set in Office 365"

This needs specific definition of where is location setting is at. Is it the Country Location attribute within the Office 365 Product Licensing page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 938c01a5-36d8-5f7a-38e6-d569928d785d
* Version Independent ID: d6d0be5f-0119-84ad-75f7-bc429841df51
* Content: [Outbound calling restriction policies for Audio Conferencing and user PSTN calls](https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/outbound-calling-restriction-policies#feedback)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/outbound-calling-restriction-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/outbound-calling-restriction-policies.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@NickElniff Thanks for reaching out and helping improve MS Docs.  I'll have the wording edited soonest.

**Comment by scanum** [comment]
@NickElniff Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
