### ISSUE TITLE
Certificate Requirements / Process

### ISSUE THREAD

**Issue by securityvoid** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2104]
This page references:
Set the path for the external Edge certificate

However, nowhere does it mention the requirements or creation process for the certificate. Elsewhere on the web I see an indication that this must be a certificate from a typical trusted certificate authority, and can't be self-signed, but there are not any details here or even where I found out about that on the details.

It would be really helpful if there was litterally a step-for-step guide for this somewhere. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f8755fc-851d-7fca-4bb6-02b8b6713d4f
* Version Independent ID: 070aa207-eb18-1c13-c9b8-59723359123f
* Content: [Prepare your Cloud Connector appliance](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/prepare-your-cloud-connector-appliance#feedback)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/prepare-your-cloud-connector-appliance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/prepare-your-cloud-connector-appliance.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@securityvoid. Thanks for your input and helping improve MS Docs.  Do you perhaps have the step-by-step instructions that I could add to the document?

**Comment by scanum** [comment]
@securityvoid We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by securityvoid** [comment]
@lindspea I do not have step-by-step instructions on how to do this. If I had figured it out, I would have posted it when I opened the ticker, or submitted a pull request. I ended up putting this project on hold because I could not get it working in a reasonable period of time.

That documentation you have provided appears to be for Skype for Business Server, not for the Skype for Business Cloud Connector. Since the latter is a light-weight version of the former, some form of what you linked might work. However, if you notice at the referenced documentation there isn't any information about host names or other details when setting things up. As a result without additional details / information its not possible to even tell if some of that other documentation might help / work. 

If you have any technical person at Microsoft work from ONLY the Skype Cloud Connector documentation to attempt to set it up, I'm pretty sure they're going to fail miserably without bringing in a lot of external sources. If it was even half-way decent documentation that shouldn't be the case. 

Can we please re-open this and get proper documentation created?

Seemed kind of weird to close a request for documentation enhancement because the individual couldn't provide what that enhancement should look like. If it was that easy to figure out, the documentation wouldn't be needed.

@officedocsbot open

**Comment by lindspea** [comment]
@CarolynRowe could you perhaps assist please?

**Comment by lindspea** [comment]
@securityvoid Hi Doug. I have requested to have it re-opened. @scanum
