### ISSUE TITLE
CAP Provisioning 

### ISSUE THREAD

**Issue by patbennett** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2106]
How does this relate if we have AzureAD Premium with password writeback enabled? 
I am using an user synced Active Directory to AAD via ADFS, will Skype CAP fail to reset this users password?

> If you have synced an on premises Active Directory to AAD and you use a third-party IDP or ADFS, CAP provisioning will fail.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@patbennett  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
