### ISSUE TITLE
Question about Teams

### ISSUE THREAD

**Issue by vormbat** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2109]
I have some question. 

If i develope the headset like jabra ...

and if I use microsoft teams with that headset, Do I have to develop something more for Teams?

For example 
-Authentication for Teams or 
-Registering device for Teams or 
-Join Skype for Business and Teams certification program )

If I do not those, the headset that I develope is not work on Teams, Skype ?

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@vormbat  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
