### ISSUE TITLE
Options not available

### ISSUE THREAD

**Issue by akp87** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2111]
Settings > Services & add-ins > Microsoft Teams does not give the same options anymore. It say options have been moved to Teams Admin center.

I cant find this option in Teams Admin center either.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@akp87 - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
