### ISSUE TITLE
Teams users chat and communicate with users in Skype for Business on-prem organization

### ISSUE THREAD

**Issue by sjuratov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2113]
Please add another section on this page making it clear that Teams users can chat and communicate with users in pure Skype for Business on-prem organisation (so organisation without Skype for Business Online co-existence).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Communicate with Teams users in another organization](https://docs.microsoft.com/en-us/microsoftteams/let-your-teams-users-communicate-with-other-people#feedback)
* Content Source: [Teams/let-your-teams-users-communicate-with-other-people.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/let-your-teams-users-communicate-with-other-people.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by ndambrosio** [comment]
This article is specifically outlining how Teams users in one organization can can be allowed to talk with Teams users in another organization.  Teams doesn't yet support native federation without the users SIP profile being homed in Skype for Business Online.  If you are looking for how the TeamsOnly User (OrgA) <-> SfB On-premisesOnly (OrgB) scenario would work, this is done the same way Skype for Business Online Federation is handled today.  This article provides a better overview of how this would work: [Coexistence with Skype for Business](https://docs.microsoft.com/en-us/MicrosoftTeams/coexistence-chat-calls-presence)

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@sjuratov  Thank you for submitting feedback and making the documentation better, we see that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
