### ISSUE TITLE
Federation with *pure* Skype for Business on-prem customers (without SfBO co-existence)

### ISSUE THREAD

**Issue by sjuratov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2114]
Please comment/mention *pure* Skype for Business on-prem customers in "Federation Considerations" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49921e8a-55ac-f547-d4e2-d329f5089c2e
* Version Independent ID: 91c3433a-3684-95cd-3426-4a5877b33106
* Content: [Migration and interoperability guidance for organizations using Teams together with Skype for Business](https://docs.microsoft.com/en-us/microsoftteams/migration-interop-guidance-for-teams-with-skype#federation-considerations)
* Content Source: [Teams/migration-interop-guidance-for-teams-with-skype.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/migration-interop-guidance-for-teams-with-skype.md)
* Service: **msteams**
* GitHub Login: @arachmanGitHub
* Microsoft Alias: **MyAdvisor**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@sjuratov Thank you for reaching out.  Are you suggesting adding a bullet point to say "chats and calls initiated from pure Skype for Business on-prem customers?"

**Comment by sjuratov** [comment]
Yes, that would be a pivot. If customer is pure on-prem SfB, what are MS Teams Federation Considerations?

**Comment by lindspea** [comment]
@sjuratov thanks for that.  I work on the actual document side to improve docs, so if you have any recommendations for wording to be added/amended please be so kind to let me know and I'll have it implemented soonest. I can chat to the team if you have any other questions or suggestions with regards to the article.

**Comment by sjuratov** [comment]
Thank you. I'd appreciate mentioned clarifications, so yes, please talk to the team on how best address this gap.

**Comment by lindspea** [comment]
@sjuratov Thank you for your patience.  I'm still investigating with the team. Does this recently updated link perhaps help with your questions.  https://docs.microsoft.com/MicrosoftTeams/coexistence-chat-calls-presence

**Comment by sjuratov** [comment]
I have looked at the page below and unfortunately I still don’t see clear statement on supportability of federation with *pure* Skype for Business on-prem customers (without SfBO co-existence).

If you feel I have missed something, please let me know where on the page I should be looking at.

Best Regards,
Sasa

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by lindspea** [comment]
@sjuratov, everything that is not directly mentioned in this article is not supported. I have confirmed this with the team, so the document will remain as is. Thank you for reaching out and please let me know if there is anything else I can help with.

**Comment by scanum** [comment]
@sjuratov Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
