### ISSUE TITLE
IW acronym

### ISSUE THREAD

**Issue by mamrouni** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#212]
I guess IW means Information Worker , but don't think all users know this acronym.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the IW trial offer for Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/iw-trial-teams)
* Content Source: [Teams/iw-trial-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/iw-trial-teams.md)
* Service: **msteams**
* Product: **unspecified**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by chuckedmonson** [comment]
Thank you for the feedback. It has been clarified.
