### ISSUE TITLE
This tool was retired and no longer available.

### ISSUE THREAD

**Issue by ndambrosio** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2120]
The Lync Connectivity Analyzer was retired in 2017.  It is no longer available for download.  The URL to the download site is no longer valid.  This article should be removed to prevent further confusion with SfB and Lync Server customers.

For reference:
https://blogs.technet.microsoft.com/nexthop/2017/06/13/retirement-of-the-lync-connectivity-analyzer-tool/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaf8ace8-4567-1286-ed82-80c7a628e9e3
* Version Independent ID: a66030ef-701b-fb41-f0aa-7762d2fe8185
* Content: [Lync Server 2013: Using Lync Connectivity Analyzer](https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-using-lync-connectivity-analyzer)
* Content Source: [Lync/LyncServer/lync-server-2013-using-lync-connectivity-analyzer.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Lync/LyncServer/lync-server-2013-using-lync-connectivity-analyzer.md)
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by ndambrosio** [comment]
Note: We’re also linking to this article and the tool download URL from the Remote Connectivity Analyzer site as well.

 https://testconnectivity.microsoft.com/?tabid=client

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@ndambrosio Thank you for reaching out and helping improve MS Docs.  I'll chat to the team to get it sorted soonest.

**Comment by SharS** [comment]
Retired article.
