### ISSUE TITLE
Microsoft Teams Rooms Licensing Link

### ISSUE THREAD

**Issue by rohanbrooker** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2125]
The Microsoft Teams Rooms Licensing link (https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/skype-room-systems-v2.md) currently throws a 404.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Office 365](https://docs.microsoft.com/en-au/MicrosoftTeams/room-systems/with-office-365)
* Content Source: [Teams/room-systems/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/with-office-365.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Thanks for letting us know, we'll adjust the link today. That whole block of content was moved recently so most Room system links are relocated now.   @LanaChin please handle this correction
