### ISSUE TITLE
Does the app setup policy affect Teams mobile app?

### ISSUE THREAD

**Issue by chenxizhang** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2126]
Hi there
This is a must-to-have feature for enterprise customer. Thank you for the effort.

I've tested this feature, It will work well in PC client. But I don't find the way for how it can work for mobile app. The custom apps which I defined in the policy just disappear in mobile app.

Does the app setup policy affect Teams mobile app as same as PC client?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f91604a-35b0-dfbb-55b2-b601cb0841b0
* Version Independent ID: 84bcd0d7-b4ed-f13e-c84b-2ec6a7661ae9
* Content: [Manage app setup policies in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-app-setup-policies)
* Content Source: [Teams/teams-app-setup-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-setup-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by chenxizhang** [comment]
More details information

This is the app policy

![image](https://user-images.githubusercontent.com/1996954/56910976-b0600c00-6a60-11e9-91aa-374a19412266.png)


This is the UI of PC client
![image](https://user-images.githubusercontent.com/1996954/56911025-ca015380-6a60-11e9-84da-1ef1399d69d3.png)

This is the UI of mobile app
![image](https://user-images.githubusercontent.com/1996954/56911076-eac9a900-6a60-11e9-9c92-e09553392f66.png)

**Comment by scanum** [comment]
Hi @chenxizhang thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
