### ISSUE TITLE
"_gt"  needs to be replaced with ">"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2127]
https://docs.microsoft.com/ja-jp/microsoftteams/create-an-org-wide-team

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Microsoft Teams で組織全体にわたるチームを作成する](https://docs.microsoft.com/ja-jp/microsoftteams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officeglobal Hi! Could you please review this issue? Thanks.

@officedocsbot assign @officeglobal

**Comment by OfficeGlobal** [comment]
related issue: #2128

**Comment by Reeced40** [comment]
@OfficeGlobal Could you please specify where the change needs to be made or has it already been done?

**Comment by scanum** [comment]
@OfficeGlobal following up on this issue? Could you please update status? Thanks

**Comment by Reeced40** [comment]
@samanthaw

**Comment by OfficeGlobal** [comment]
@Reeced40 please check the ENG live article https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team, you'll see \*\*@mentions\*\* instead of **@mentions**. In the GH repository it's displayed properly. not sure where is the issue

![image](https://user-images.githubusercontent.com/47977325/58249389-0b82d700-7d5f-11e9-8bff-e3cb6da6f03f.png)

**Comment by OfficeGlobal** [comment]
@hyoshioka0128  "_gt" string was updated and it's displayed properly as >

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
Close #2127
