### ISSUE TITLE
Showing "**@mentions**" (extra asterisks appears) (en-us & ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2128]
https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team (en-us)
https://docs.microsoft.com/ja-jp/microsoftteams/create-an-org-wide-team (ja-jp)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Microsoft Teams で組織全体にわたるチームを作成する](https://docs.microsoft.com/ja-jp/microsoftteams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officeglobal Could you please review this issue? Thanks! 

@officedocsbot assign @officeglobal
@officedocsbot assign @scanum

**Comment by OfficeGlobal** [comment]
@scanum We will check and fix the issue. However could you please update source, the \*\*@mentions\*\* is displayed in ENG version as well

**Comment by Reeced40** [comment]
@OfficeGlobal Could you please specify where the change needs to be made or has it already been done?

**Comment by scanum** [comment]
@OfficeGlobal Could you please confirm that changes have been made? Thanks.

**Comment by Reeced40** [comment]
@samanthaw

**Comment by OfficeGlobal** [comment]
@Reeced40 please check the ENG live article https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team, you'll see \*\*@mentions\*\* instead of **@mentions**. In the GH repository it's displayed properly. not sure where is the issue

![image](https://user-images.githubusercontent.com/47977325/58249389-0b82d700-7d5f-11e9-8bff-e3cb6da6f03f.png)

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 the asterisks were fixed in JPN version - text is displayed as bold

**Comment by Reeced40** [comment]
@OfficeGlobal @hyoshioka0128  Hi there. I'm unable to create PR for this issue. The 'propose file change' option is not open for me to create the PR.  This is also linked to #2127 but I see that one has been closed.  Please advise if there is anything that needs to be done from my side for both issues.

**Comment by OfficeGlobal** [comment]
Hi @Reeced40 , 
 - no action needed for issue #2127 from your side.
 - #2128 asterisks displayed at ENG live site, there might be a build problem - as there is \*\*\@text... 
     We had similar issue in the past and for us helped to escape \@ character (e.g. \*\*\\\@mentions\*\*) but it's only my guess.
     Second option is no bold formatting

**Comment by Reeced40** [comment]
> 
> 
> Hi @Reeced40 ,
> 
>     * no action needed for issue #2127 from your side.
> 
>     * #2128 asterisks displayed at ENG live site, there might be a build problem - as there is **@text...
>       We had similar issue in the past and for us helped to escape @ character (e.g. **\@mentions**) but it's only my guess.
>       Second option is no bold formatting

@OfficeGlobal As mentioned, I'm unable to propose changes in making a PR. The "Propose File Change" icon is not highlighted.

**Comment by hyoshioka0128** [comment]
@OfficeGlobal @Reeced40 Thanks.  (I'm Poor English.)
 ja-jp is fixed. 
 I made a pull request with en-us.  #2329 
 Close #2128
