### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2129]
I dont see an option to purchase the Domestic or International plan. I only see Common Area Phone license.
After you buy Phone System licenses, you can buy the Calling Plan by signing in to the Office 365 admin center, choose Billing &gt; Purchase services &gt; Add-on subscriptions, and then clicking Buy now. You'll see the Calling Plans there.

Is this documentation still accurate?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 243fa83d-b7bf-323a-a14a-026915d3d058
* Version Independent ID: fd4a310b-3144-4a8b-1bde-c2efd0c87377
* Content: [Calling Plans for Office 365](https://docs.microsoft.com/en-us/microsoftteams/calling-plans-for-office-365)
* Content Source: [Teams/calling-plans-for-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/calling-plans-for-office-365.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@eschrader  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by eschrader** [comment]
After I purchased a Common Phone license, I could go back in and purchase a Domestic license for those plans. I could not add them on during my checkout until I purchased the first Common Phone license. Can the documentation be updated to reflect this process?
