### ISSUE TITLE
Error with Setup

### ISSUE THREAD

**Issue by brendenbowie** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#213]
Hi,

After creating a USB setup disk, we are able to launch Windows Setup.  However, we receive the message of "Windows cannot read the <ProductKey> setting from the unattend answer file.".  If we pull the USB drive, we can continue setup but the Skype part of the install doesn't happen - it's just Windows 10.  Any ideas?  Have looked at many posts but no luck.  We are using the latest ISO and even tried following steps at https://content.cloudguides.com/guides/Configure%20the%20Skype%20Room%20Systems%20console.  Thanks in advance and sorry if this isn't the best spot to post about this.  

B

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51d42140-9f7b-a6f3-7a3e-76cc7331cf22
* Version Independent ID: a7dacc56-c2df-55fb-76a3-ecb194564fae
* Content: [Configure a Skype Room Systems v2 console](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/console#see-also)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/console.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by Travis-Snoozy** [comment]
Hi Brenden,

That guide is out of date. If you have not done so already, please follow the current instructions on ("Configure a Skype Room Systems v2 console")[https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/console#prepare-the-installation-image]. The most-recent script, available on that page, will automatically generate a transcript. If you are running that script for the first time, or you were using an older version of the script that did not automatically generate a transcript, please be sure to run the script with the additional `-Debug` command line flag, to make the output more verbose for debugging.

Once you have the transcript in hand, please supply it. That will allow me to assess the nature of your problem.

Thank you,

--
Travis

**Comment by brendenbowie** [comment]
[PowerShell_transcript.CVG-GFHM3M2.Cb9hK97H.20180517151111.txt](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/files/2014923/PowerShell_transcript.CVG-GFHM3M2.Cb9hK97H.20180517151111.txt)

Thanks for the quick reply, Travis!  Makes sense why we weren't having any luck xD.  Please see attached for the most recent transcript that we have. 

Many thanks!

**Comment by Travis-Snoozy** [comment]
Alrighty -- this transcript shows that the script did not complete. It doesn't appear to have even started copying Windows.

It seems like you were having trouble specifying your source media -- with a series of paths that didn't exist, or didn't point to valid media.

Do you have either a Windows 10 Enterprise DVD, or an ISO file for a Windows 10 Enterprise DVD? If the former, you should specify the drive letter of the DVD (or the mounted ISO -- you can mount the ISO in Windows 10 just by double-clicking it) at the prompt. For example, you'd enter:

    D:

if your ISO or DVD were mounted at D:.

**Comment by jambirk** [comment]
I'll keep this issue open for another day or so. Please let us know if further action is needed.

**Comment by brendenbowie** [comment]
Thanks, Travis.  Yes, we have the ISO mounted as D:.  We've tried D:\ and D: but keep receiving "Please enter the path to the root of your Windows install media: D:
The path provided does not seem to point to valid Windows installation media. Please specify a path that is the root of the Windows installation media you wish to use."  

Thoughts?

**Comment by Travis-Snoozy** [comment]
The transcript indicates that D: is a removable, FAT32-formatted USB disk -- it's your only target option. Are you trying to use D: both as your source and your destination?

**Comment by brendenbowie** [comment]
Sorry for the confusion, that was a prior attempt.  We now have D: as the mounted ISO and the USB disk as F:.

**Comment by Travis-Snoozy** [comment]
output of

    dir f:
    dir f:\sources\install.*

for reference?

**Comment by brendenbowie** [comment]
C:\Users\Brenden Bowie>dir f:\sources\install.*
 Volume in drive F has no label.
 Volume Serial Number is 6CB4-3FC2

 Directory of f:\sources

File Not Found

C:\Users\Brenden Bowie>dir f:
 Volume in drive F has no label.
 Volume Serial Number is 6CB4-3FC2

 Directory of F:\

05/17/2018  05:55 PM    <DIR>          Provisioning
05/17/2018  05:55 PM    <DIR>          sources
               0 File(s)              0 bytes
               2 Dir(s)  30,388,486,144 bytes free

**Comment by Travis-Snoozy** [comment]
Sorry, let me re-ask a question I've already asked -- you have a Windows 10 Enterprise DVD or ISO mounted at that path? Normally, they should have output like:

     Directory of K:\

    2017-09-27  09:54               128 autorun.inf
    2017-09-29  08:05    <DIR>          boot
    2017-09-29  08:03           397,752 bootmgr
    2017-09-29  08:03         1,236,376 bootmgr.efi
    2017-09-29  08:05    <DIR>          efi
    2017-09-29  08:03            80,696 setup.exe
    2017-09-29  08:06    <DIR>          sources
    2017-09-29  08:06    <DIR>          support
                   4 File(s)      1,714,952 bytes
                   4 Dir(s)               0 bytes free


And...

     Directory of k:\sources

    2017-09-29  08:04     3,710,809,457 install.wim
                   1 File(s)  3,710,809,457 bytes
                   0 Dir(s)               0 bytes free


... you're sure that whatever's on your F: is a Windows 10 Enterprise installation DVD or ISO that would boot by itself, if you dropped it into a desktop computer?

**Comment by Travis-Snoozy** [comment]
Derp. I got it backwards. Sorry.

    dir D:
    dir D:\sources\install.*

... one more time. :)

**Comment by brendenbowie** [comment]
:)

C:\Users\Brenden Bowie>dir d:\sources\install.*
 Volume in drive D is ESD-ISO
 Volume Serial Number is E224-794A

 Directory of d:\sources

05/17/2018  04:37 PM     3,121,805,766 install.esd
               1 File(s)  3,121,805,766 bytes
               0 Dir(s)               0 bytes free

C:\Users\Brenden Bowie>dir d:
 Volume in drive D is ESD-ISO
 Volume Serial Number is E224-794A

 Directory of D:\

04/12/2018  06:27 AM    <DIR>          boot
04/12/2018  06:27 AM    <DIR>          efi
05/17/2018  04:37 PM    <DIR>          sources
04/12/2018  06:27 AM    <DIR>          support
04/12/2018  05:53 AM               128 autorun.inf
04/12/2018  06:23 AM           407,582 bootmgr
04/12/2018  06:23 AM         1,257,376 bootmgr.efi
04/12/2018  06:23 AM            80,648 setup.exe
               4 File(s)      1,745,734 bytes
               4 Dir(s)               0 bytes free

**Comment by brendenbowie** [comment]
And also we verified that the ISO does work for a install of Windows 10 (Enterprise).

**Comment by Travis-Snoozy** [comment]
Okay, let me run through the script logic. I don't know why that would be failing the test, but I guess that's an improvement that could be made to the script output. Standby.

**Comment by brendenbowie** [comment]
Got it. Thanks!

**Comment by brendenbowie** [comment]
For reference, here's where we got the ISO.  Thinking now, not 100% that it's Enterprise (was just going based on what we selected in PowerShell).  If it's not, is there a good link for Enterprise ISO?  
https://www.microsoft.com/en-us/software-download/windows10

**Comment by Travis-Snoozy** [comment]
OH! It's "Install.esd" not "install.wim" -- that's why it's barfing, that was a downloaded web package. Yes, I should put an explicit check in for that and give a better error message. :)

I'm not exactly sure where Enterprise customers are supposed to get Enterprise media -- I don't _think_ that the official channel is via MSDN, but then, I've also never personally gone through the process of purchasing Enterprise from Microsoft. Who handles your volume licensing? Maybe you'd get it from the [MPSA site](http://go.microsoft.com/fwlink/?LinkId=125893), if that's how your licensed?

**Comment by Travis-Snoozy** [comment]
Oh... [your link](https://www.microsoft.com/en-us/software-download/windows10) actually has a section at the bottom for "more download options" -- it says that you should download Enterprise from the [Volume Licensing Service Center](https://www.microsoft.com/licensing/servicecenter/default.aspx).

**Comment by Travis-Snoozy** [comment]
Alright -- I've got changes staged to the script to:

- ID and very explicitly reject Media Creation Tool-generated media, and
- Add information about where to download the Enterprise image from.

The next time the script is released, it should include the above changes. We've also requested that the out-of-date guide be taken down.

Thank you for reaching out to us -- please let me know if there are any other unresolved aspects to this matter. :)

**Comment by brendenbowie** [comment]
Thanks, Travis!  Looking forward to checking out the new script.

**Comment by brendenbowie** [comment]
Hey Travis,

Just wanted to let you know that we tried out the new script with a new Windows 10 Enterprise ISO and it was successful!  Thanks again for all of your help!

Brenden
