### ISSUE TITLE
Legacy Portal

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2131]
WHen will we be able to add a phone number in the Teams Admin center and not Legacy Portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9abca078-b003-f11c-31d5-ca150a3e4364
* Version Independent ID: b78f0415-895b-2c35-f9c0-7a350a1c33a0
* Content: [Assign, change, or remove a phone number for a user](https://docs.microsoft.com/en-us/skypeforbusiness/what-are-calling-plans-in-office-365/assign-change-or-remove-a-phone-number-for-a-user)
* Content Source: [Skype/SfbOnline/what-are-calling-plans-in-office-365/assign-change-or-remove-a-phone-number-for-a-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/what-are-calling-plans-in-office-365/assign-change-or-remove-a-phone-number-for-a-user.md)
* Service: **skype-for-business-online**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@eschrader  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
