### ISSUE TITLE
Change a user number to a service number.

### ISSUE THREAD

**Issue by cjbarto** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2133]
Changing a user number to a service number is supported when using Telstra Calling for Office 365.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20eb7315-4f08-4ff7-2435-5ed2cbbd1223
* Version Independent ID: 88cef007-a180-e19e-350e-db359355d5d5
* Content: [Phone number management for Australia](https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization/phone-number-management-for-australia#feedback)
* Content Source: [Teams/manage-phone-numbers-for-your-organization/phone-number-management-for-australia.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-phone-numbers-for-your-organization/phone-number-management-for-australia.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@cjbarto Thank you for your feedback. I will get this over to investigation.

@officedocsbot assign @scanum

**Comment by scanum** [comment]
@cjbarto Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
