### ISSUE TITLE
Error when creating ISO

### ISSUE THREAD

**Issue by Powelljl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2134]
Hello,
Trying to build ISO but running up against errors in the last bit, the script just errors at the end, 

`**********************
Windows PowerShell transcript start
Start time: 20190429221450
Username: INSPIRETEC\Josh.Powell
RunAs User: INSPIRETEC\Josh.Powell
Configuration Name: 
Machine: DIAMOND (Microsoft Windows NT 10.0.17763.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Process ID: 3524
PSVersion: 5.1.17763.316
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17763.316
BuildVersion: 10.0.17763.316
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\josh.powell\Documents\PowerShell_transcript.DIAMOND.xdL66VIJ.20190429221450.txt
Script version 1.4.3
Downloading CreateSrsMedia...
done
Validating signature for update.ps1...
success.

919C06207B8A9C6B71423B7916AB61D3F6EF6DC7BD04AD4EC9CB172053B3317991E8274D1DC0F6335D27B8F4E299F7336FEE6F5966624F2A5815A7EB8293884E
68308

What type of customer are you?
Please make sure you have all of the following available:

1. A USB drive with sufficient space (16GB+).
   The contents of this drive WILL BE LOST!
2. Windows 10 Enterprise media that matches your SRSv2 deployment kit.
   Enterprise customers can access Windows 10 Enterprise media from the Volume Licensing Service Center:
   http://www.microsoft.com/licensing/servicecenter
3. Any language pack (LP and/or LIP) files to be included.
   MPSA customers:         http://go.microsoft.com/fwlink/?LinkId=125893
   Other volume licensees: http://www.microsoft.com/licensing/servicecenter

Please do not continue until you have all these items in order.

Found deployment kit already downloaded.
Validating signature for SRSDeploymentKit-4.0.85.0.msi...
success.
Extracting the deployment kit...
done.
This deployment kit is built for Windows build 10.0.17134.1.
This deployment kit draws its drivers from %configsetroot%\AutoUnattend_Files\DistShare\Out-of-Box Drivers.

Please indicate what drivers you wish to use with this installation.
[ 0] Logitech SmartDock
[ 1] Crestron SR
[ 2] Polycom MSR
[ 3] Lenovo Hub 500
[ 4] LRS
[ 5] HP Slice 2.0
[ 6] Crestron Flex
[ 7] None
Selected option 0.
[ 0] Surface Pro 4
[ 1] Surface Pro (2017)
[ 2] Surface Pro 6
Selected option 0.
Found driver already downloaded.
Validating signature for SurfacePro4_Win10_16299_1803301_1.msi...
success.
Extracting SurfacePro4_Win10_16299_1803301_1.msi...
done.
Identifying language packs...
... done identifying language packs.
Found update KB4340917 already downloaded.
Validating signature for windows10.0-kb4340917-x64_ed5f586fa9d7064d61e45c523f20ba7fc1ff142a.msu...
success.
WARNING: THIS IS YOUR ONLY CHANCE TO PRE-INSTALL LANGUAGE PACKS.
Because you are pre-installing an update, you will NOT be able to pre-install language packs to the image at a later point.
You are currently building an image with NO pre-installed language packs.
Are you ABSOLUTELY SURE this is what you intended?
WARNING: PROCEEDING TO GENERATE SLIPSTREAM IMAGE WITH NO PRE-INSTALLED LANGUAGE PACKS.

Reminder: all data on the drive you select will be lost!

[ 0] SanDisk Ultra Fit
Selected option 0.

Creating Enterprise media.

Creating UEFI-compatible media.

Using SRSv2 kit:       C:\Users\josh.powell\Desktop\SRSv2\SRSDeploymentKit-4.0.85.0.msi
Using driver packs:
    C:\Users\josh.powell\Desktop\SRSv2\SurfacePro4_Win10_16299_1803301_1.msi
Using Windows media:   C:\Users\josh.powell\Desktop\SRSv2\Windows
Using language packs:
Using updates:
    C:\Users\josh.powell\Desktop\SRSv2\windows10.0-kb4340917-x64_ed5f586fa9d7064d61e45c523f20ba7fc1ff142a.msu
Writing stick:         SanDisk Ultra Fit

Formatting and partitioning the target drive...
PS>TerminatingError(New-Partition): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Not enough available capacity
Activity ID: {01b69fd2-a7d3-4155-8fdf-6567211b5bc4}"
done.
Copying Windows...
done.
PS>TerminatingError(New-Item): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: An item with the specified name C:\Users\josh.powell\Desktop\SRSv2\com-mnt already exists."
>> TerminatingError(Dismount-WindowsImage): "The directory could not be completely unmounted.  This is usually due to applications that still have files opened within the mount directory.  Close these files and unmount again to complete the unmount process.
"
Confirm
The item at C:\Users\josh.powell\Desktop\SRSv2\com-mnt has children and the Recurse parameter was not specified. If you continue, all children will be removed with the item. Are you sure you want to continue?
&Yes  Yes to &All  &No  No to A&ll  &Suspend
N
**********************
Windows PowerShell transcript end
End time: 20190429221812
**********************
`

**Comment by jambirk** [comment]
@Powelljl please open a support case. This isn't clearly an issue with the documentation and will require more investigation than we are able to do.

**Comment by Powelljl** [comment]
> @Powelljl please open a support case. This isn't clearly an issue with the documentation and will require more investigation than we are able to do.

@jambirk trying to find a location too? Where would you recommend?

**Comment by jambirk** [comment]
You can call 800-936-4900 to file case over the phone.

**Comment by scanum** [comment]
@Powelljl  - thank you for submitting feedback.

As @jambirk mentioned I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
