### ISSUE TITLE
How do I currently enable apps for my org?

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2138]
What happened to the guidance on how to enable apps & sideloading? If the guidance on this page isn't enabled yet, how do you do this currently?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b51eda6c-168c-7d99-7cc1-992b3d8feef2
* Version Independent ID: 118a1b8f-f4b7-a778-70b1-d3161fc548ab
* Content: [Manage app permission policies in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-app-permission-policies#feedback)
* Content Source: [Teams/teams-app-permission-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-permission-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@clearab  - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@clearab Hi Andrew.  Thanks for reaching out and helping improve MS Docs.  Please let me know if this article helps - https://docs.microsoft.com/microsoftteams/enable-features-office-365

**Comment by scanum** [comment]
@clearab We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by clearab** [comment]
Can you add a link to that page at the top of this article? And also a link to the appropriate page for the other articles in this section that are marked as "not in production yet"? It is very confusing with the articles being in different sections of the ToC.

**Comment by clearab** [comment]
@scanum Can you re-open this please? There really needs to be a link to where in the documentation end-users are supposed to go to learn about this topic, otherwise this article (and the others similar in this section) are dead ends.

**Comment by scanum** [comment]
@officedocsbot reopen

**Comment by lindspea** [comment]
> 
> 
> Can you add a link to that page at the top of this article? And also a link to the appropriate page for the other articles in this section that are marked as "not in production yet"? It is very confusing with the articles being in different sections of the ToC.

@clearab Thanks Andrew.  I'll add the link to this article.  Please specify which other articles you are referring to.  Each article will need to have a PR to add the link, if I'm understanding you correctly, so it would be best to open an issue on the relevant articles you are referring to.

**Comment by lindspea** [comment]
@clearab

**Comment by clearab** [comment]
Looks like the only other article is this one: https://docs.microsoft.com/en-us/MicrosoftTeams/teams-custom-app-policies-and-settings

I'm not sure what article is the current guidance in this space

**Comment by lindspea** [comment]
@clearab Hi Andrew. The link you provided above is the one I suggested to be added to the original article referenced in this issue, but I see for both articles, they mention some features are not yet available in Microsoft Teams.  The roadmaps are currently linked to both articles at the top of each.  Sorry for the confusion, but could you please be a bit more specific on what links need to be added to both articles? Perhaps one of these?  https://docs.microsoft.com/microsoftteams/teams-app-setup-policies or https://docs.microsoft.com/microsoftteams/manage-teams-skypeforbusiness-admin-center

**Comment by clearab** [comment]
So both:
1) https://docs.microsoft.com/en-us/MicrosoftTeams/teams-app-permission-policies
2) https://docs.microsoft.com/en-us/MicrosoftTeams/teams-custom-app-policies-and-settings

Should have a link to:
https://docs.microsoft.com/en-us/MicrosoftTeams/enable-features-office-365

With a note that says something like:
"For the current method of managing apps in Microsoft Teams, see here"

**Comment by LolaJacobsen** [comment]
I merged the related PR. Thanks @clearab

**Comment by scanum** [comment]
@clearab Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
