### ISSUE TITLE
Landing Page broken link

### ISSUE THREAD

**Issue by shanehoey** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2139]
On the main landing page  https://docs.microsoft.com/en-us/MicrosoftTeams/Microsoft-Teams there is a broken link again this time the link for the Posters page is pointing at https://review.docs.microsoft.com incorrectly 

/cc @kenwith

**Comment by kenwith** [comment]
@LolaJacobsen and @CarolynRowe just moved the poster to make it more prominent I think.. might be something with that. We will get it sorted. Thanks for opening the issue, much appreciated Shane!

**Comment by scanum** [comment]
@shanehoey  - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by CarolynRowe** [comment]
Thanks for the feedback. This is fixed now.
