### ISSUE TITLE
Out of date information

### ISSUE THREAD

**Issue by hapodger** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2140]
This page does not mention the Teams Meeting Room license (MeetingRoom ShrdSvr ALNG SubsVL MVL PerDvc) which is designed specifically for this purpose. Can it please be updated, as this is a far more efficient method of licensing rooms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses](https://docs.microsoft.com/en-us/microsoftteams/room-systems/skype-room-systems-v2#feedback)
* Content Source: [Teams/room-systems/skype-room-systems-v2.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/skype-room-systems-v2.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@hapodger - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@hapodger Thank you, I'm working on it.

**Comment by jambirk** [comment]
@sohailta will need to approve this, the suggested change isn't ready for publish as-is.

**Comment by jambirk** [comment]
The change suggested by @Reeced40 can't be used, we need to work with the product team to add that license type to the table in the article.
