### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by moreaboutmatt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2141]
Just a small typo in the following command:

Set-CsOnlineDialInConferencingTenantSetting -AutomaticallySendEmailsToUsers $false

The cmdlet needs an 's' on the end. It's Settings not Setting.

Matt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5786cbf8-6fea-46f2-df43-ad7b46b8c9fa
* Version Independent ID: 8323b8b8-80f6-630e-d472-93df6fae43b1
* Content: [Emails sent to users when their settings change in Skype for Business Online](https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/emails-sent-to-users-when-their-settings-change#feedback)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/emails-sent-to-users-when-their-settings-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/emails-sent-to-users-when-their-settings-change.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@moreaboutmatt - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@moreaboutmatt Thank you for reaching out, working on it.

**Comment by scanum** [comment]
@moreaboutmatt Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
