### ISSUE TITLE
Install ALLUSER=1 error

### ISSUE THREAD

**Issue by Everink** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2142]
When trying to install with the ALLUSER=1 switch I'm getting the error:
"cannot install for all users when a VDI environment is not detected"

Any info on why this is happening? Some hidden restriction or requirement to install on a per-machine basis?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi#feedback)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Everink - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by jhol5** [comment]
I am also getting this error when trying to create an captured application using VMware AppVolumes.

Here is the log: https://pastebin.com/daNNZ1kD

**Comment by scanum** [comment]
@Everink  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by Chireven** [comment]
The installer looks for VDI registry keys.  If it doesn't find them, then it throws the error that you can't install it.  If you use create the keys it's looking for, then it will let you install it.  I had to do this to package it for my environment, too -- since my packaging machine doesn't have a VDI client installed on it.  I created HKLM\Software\Citrix\PortICA and it was enough to allow me to continue packaging.

**Comment by jhol5** [comment]
Thanks for the info @Chireven. Using this I have found the VMware equivalent as well which is:
HKLM\SOFTWARE\VMware, Inc.\VMware VDM\Agent

**Comment by CIGAdmin** [comment]
I, too, get the "Installation has failed" error, "Cannot install for all users when a VDI environment is not detected."  I use neither VMware nor Citrix but, ironically, Hyper-V.  So, it can't detect that I'm using Hyper-V?  No?  Microsoft, don't you want to promote Hyper-V?  You really need to get this fixed.
