### ISSUE TITLE
Wording issue

### ISSUE THREAD

**Issue by vwethan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2143]
The sentence regarding a location passing validation has the word pass used twice. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18d8e82c-b0ef-1b4d-f552-8d121bf33744
* Version Independent ID: d37315fd-b36e-28d3-f240-966e832e6207
* Content: [What is address validation?](https://docs.microsoft.com/en-us/SkypeForBusiness/what-are-calling-plans-in-office-365/what-is-address-validation#feedback)
* Content Source: [Skype/SfbOnline/what-are-calling-plans-in-office-365/what-is-address-validation.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/what-are-calling-plans-in-office-365/what-is-address-validation.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@vwethan 0 Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@vwethan Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
