### ISSUE TITLE
Amend licensing details

### ISSUE THREAD

**Issue by MarkBratton** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2144]
Can we please remove the ambiguity here? Using "such as" leaves the impression that there may be other ways to license this, and there are not. The only thing missing is the equivalent edu and gov offers. Also should be "feature is" or "features are". 

**Required licenses and permissions**
Currently, the information barrier features is in private preview. When these features are generally available, they'll be included in subscriptions, such as:
Microsoft 365 E5
Office 365 E5
Office 365 Advanced Compliance
Microsoft 365 E5 Compliance

I suggest changing to:

"Currently, the information barrier features are in private preview. When these features are generally available, they'll be included in the following subscritions:

Microsoft 365 E5/A5/G5
Office 365 E5/A5/G5
Office 365 Advanced Compliance
Microsoft 365 E5/A5/G5 Compliance"

Thanks!
Mark

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85a288bc-9192-8c65-4ce9-b5abb260206e
* Version Independent ID: 1f953ea6-e6e5-5e71-d541-3962637f25f9
* Content: [Information barriers in Microsoft Teams preview](https://docs.microsoft.com/en-us/MicrosoftTeams/information-barriers-in-teams)
* Content Source: [Teams/information-barriers-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/information-barriers-in-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@MarkBratton - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@MarkBratton Thanks for pointing this out and helping improve MS Docs.  I'll have the changes approved and implemented soonest.

**Comment by LolaJacobsen** [comment]
@lindspea - I merged the PR.
