### ISSUE TITLE
Enroll devices into Microsoft Teams Admin Portal

### ISSUE THREAD

**Issue by SPENCER-JONES** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2145]
Hi,

Sorry if this is an old but our organization is starting to introduce Microsoft Teams Rooms. We have purchased certified devices based on Microsoft's recommendation (_Logitech SmartDock Flex with Surface Pro_). In Microsoft's documentation it states "_A device is automatically enrolled the first time a user signs in to Teams on the device_.", however our devices do not show up in the Teams Admin portal. How do we get the device into the Teams Admin portal to properly manage it?

Here is the referenced Microsoft article...

https://docs.microsoft.com/en-US/microsoftteams/device-management?WT.mc_id=TeamsAdminCenterCSH

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@SPENCER-JONES  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
