### ISSUE TITLE
Preview Status

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2146]
This is no longer in private preview as this page notes.  It is public preview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85a288bc-9192-8c65-4ce9-b5abb260206e
* Version Independent ID: 1f953ea6-e6e5-5e71-d541-3962637f25f9
* Content: [Information barriers in Microsoft Teams preview](https://docs.microsoft.com/en-us/microsoftteams/information-barriers-in-teams)
* Content Source: [Teams/information-barriers-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/information-barriers-in-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocs assign @scanum

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@danmyhre Thanks for pointing that out.  I have added the change.

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
