### ISSUE TITLE
Please clarify powershell management capability

### ISSUE THREAD

**Issue by ALINRUISU** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2147]
Is there an possibility to use powershell to manage and configure this setting? (Allow anonymous users to join meetings)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c8aee4f-05cd-85bf-8e8a-e11fa62b4f08
* Version Independent ID: addd3d3c-e615-67e1-0678-c1d4dc451815
* Content: [Manage meeting settings](https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams#feedback)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ALINRUISU  - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@ALINRUISU - I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
