### ISSUE TITLE
How to Disable Team Discovery Across the Organization

### ISSUE THREAD

**Issue by ThePangy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2151]
Suppose an organization does not want any of their private Teams discoverable. Owners can manage their own Teams and should not be bothered with requests from people to join the Team. The organization wants private Team discovery to function as it always has where no private Teams are discoverable. Where is the global option to turn off private Team discovery? This only mentions setting a Team as discoverable at the Team level and controlling if users can see private Teams at the user level. There needs to be a global option for this in the Teams admin portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5920152-5fee-41ed-56df-ad7b51b25cc2
* Version Independent ID: 88cfc850-5e36-48ee-ba99-088b2b653f1e
* Content: [Manage discovery of private teams in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-discovery-of-private-teams)
* Content Source: [Teams/manage-discovery-of-private-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-discovery-of-private-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ThePangy  - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@ThePangy - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

Also, we encourage you to I know the product teams are always looking for user feedback and how to make Skype for Business better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://www.skypefeedback.com.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by scanum** [comment]
@officedocsbot close

**Comment by ThePangy** [comment]
Hi @scanum - I did a little more digging and it looks like it can be done with the Set-CsTeamsChannelsPolicy to modify the "Global" policy. The below cmdlet looks like it should work, but since private Teams won't be discoverable until early June, we have no way to test this now.

Set-CsTeamsChannelsPolicy -Identity Global -AllowPrivateTeamDiscovery $false
