### ISSUE TITLE
Specify hybrid scenario

### ISSUE THREAD

**Issue by Per-Torben** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2152]
"Before you set up or define policies, you must enable scoped directory search in Microsoft Teams. Wait at least 24 hours after enabling scoped directory search before you set up or define policies for information barriers."

According to your own documentation scoped directory search does not work in a hybrid environment. https://docs.microsoft.com/en-us/microsoftteams/teams-scoped-directory-search

So is Information barriers availble and supported for customers in a hybrid environment or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85a288bc-9192-8c65-4ce9-b5abb260206e
* Version Independent ID: 1f953ea6-e6e5-5e71-d541-3962637f25f9
* Content: [Information barriers in Microsoft Teams preview](https://docs.microsoft.com/en-us/microsoftteams/information-barriers-in-teams#required-licenses-and-permissions)
* Content Source: [Teams/information-barriers-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/information-barriers-in-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Per-Torben - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

@officedocsbot assign @scanum

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@Per-Torben Thank you for reaching out and helping improve MS Docs.  Please let me know if this link helps answer your question or if you have any suggestions for wording to be added to the article for clarity. https://docs.microsoft.com/skype-sdk/skype-for-business-bot-framework/docs/bot-hybrid-support

**Comment by Per-Torben** [comment]
@lindspea The link does not answer my question. There is a huge demand for this feature for customers who are, and will stay, in Hybrid configuration. I'm looking for a clear "Yes" or "No" answer from you (Microsoft) if this feature works in a hybrid environment or not.

**Comment by anders-back** [comment]
@Per-Torben, Address book policies ("ABP") in Exchange will not "traverse" a hybrid configuration, that is ABPs created in Onprem will not be "migrated/copied" to Exchange Online, so in order for scoped directory search in Microsoft Teams to work you have to (re)create ABPs in Exchange Online.

**Comment by Per-Torben** [comment]
@anders-back I know this and it's not what I'm asking. Ms Teams can't segregate on ABPs in a hybrid environment, even if you (re)create the ABPs in Exchange Online. I've tested this more than once and so have my colleagues. Does Information barriers in Teams work in a hybrid environment or not?

**Comment by lindspea** [comment]
@LolaJacobsen

**Comment by LolaJacobsen** [comment]
@juturu please review this issue and let us know what changes are needed to reconcile these 2 articles.

**Comment by scanum** [comment]
@juturu Hi Hari, any updates on this? Thanks.

**Comment by anders-back** [comment]
Any updates on this issue?

**Comment by lindspea** [comment]
@anders-back Sorry for the delay.  The team is still working on this issue.  We will let you know as soon as we have an update. @juturu @LolaJacobsen

**Comment by scanum** [comment]
@MicrosoftHeidi Hi Heidi, PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@Per-Torben Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
