### ISSUE TITLE
Configure a Microsoft Teams Room console link is broken

### ISSUE THREAD

**Issue by c016smith** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2153]
Final paragraph: Use the right version of Windows 10: For customers who want to deploy Windows 10 images to their devices, see Configure a Microsoft Teams Rooms console.

I tried the link, but get a 404 error message. Is this a capability Microsoft is allowing for customers to provide their own PCs with Windows as a Microsoft Teams Room console? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses](https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/skype-room-systems-v2)
* Content Source: [Teams/room-systems/skype-room-systems-v2.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/skype-room-systems-v2.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@c016smith - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@c016smith Thank you for reaching out, I will have it sorted out soonest.

**Comment by TokyoScarab** [comment]
Thank you @c016smith for bringing this issue up with the GitHub team!  It does appear the link is broken.  I have found the appropriate page it is supposed to point to and will make the changes to fix it. The link is the one [here](https://docs.microsoft.com/microsoftteams/room-systems/console).  I believe this page will have the information you are looking for.  If it doesn't, feel free to comment below and we'll be glad to assist you further, thanks!

**Comment by scanum** [comment]
@c016smith Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
