### ISSUE TITLE
Microsoft E5 repeated two times?

### ISSUE THREAD

**Issue by wrooot** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2154]
What is the difference between Microsoft 365 E5 and Microsoft 365 E5 Compliance? Maybe latter one should be E3 or without E5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85a288bc-9192-8c65-4ce9-b5abb260206e
* Version Independent ID: 1f953ea6-e6e5-5e71-d541-3962637f25f9
* Content: [Information barriers in Microsoft Teams preview](https://docs.microsoft.com/en-us/microsoftteams/information-barriers-in-teams#feedback)
* Content Source: [Teams/information-barriers-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/information-barriers-in-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@wrooot - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by TokyoScarab** [comment]
@wrooot Hello and thank you for bringing up this issue!  It would seem this bulleted points were either correct at one point or mistakenly filled in as the page the link goes to for the pricing has completely different information.  I'll update these points to reflect the current page's pricing plan information.  Thanks!

**Comment by scanum** [comment]
@TokyoScarab

**Comment by wrooot** [comment]
Why is this change incorrect and is the current state correct with E5 repeated two times? Or is Microsoft 365 E5 Compliance not actually part of E5, but a separate add-on, just sharing a name? This is confusing, Microsoft. Maybe you should then add some disclaimer (add word add-on, pack, and also that it is used along with E1/E3 plan).

**Comment by scanum** [comment]
@wrooot We really appreciate your suggestions, we will consider adding a disclaimer in the future. Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
