### ISSUE TITLE
The steps for setting up policy should mention shift of location

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2156]
Enabling shifts is currently done at https://admin.microsoft.com/Adminportal/Home#/Settings/ServicesAndAddIns then the app setup policy changes sites to https://admin.teams.microsoft.com/policies/app-setup . You might want to mention this in the instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58ea9573-59b1-1499-fb83-517d0ee0f034
* Version Independent ID: bf98f739-ff51-0b90-dbc5-c594d3dacecd
* Content: [Manage the Shifts app for your organization in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams#availability-of-shifts)
* Content Source: [Teams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams.md)
* Service: **msteams**
* GitHub Login: @kenwith
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hoyty76 - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@hoyty76 Thank you for reaching out, I'll investigate further.

**Comment by TokyoScarab** [comment]
Hello @hoyty76 and thank you for bringing this up!  We will take this into consideration in the future updating of this page.

**Comment by scanum** [comment]
@hoyty76 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
