### ISSUE TITLE
Need more details: Allow people that dial in to start a meeting

### ISSUE THREAD

**Issue by NickDorak** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2157]
We need more details on the option "Allow people that dial in to start a meeting". Will the meeting organizer be prompted to enter their PIN to start the meeting? (like in Skype) After users have been prompted for PIN and successfully entered, then I would assume they have now been "authenticated". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies](https://docs.microsoft.com/en-US/MicrosoftTeams/meeting-policies-in-teams?WT.mc_id=TeamsAdminCenterCSH#bkparticipantsandguests)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@NickDorak - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by chrism0n** [comment]
I also have the same question.  Will the meeting moderator be allowed to dial in, enter pin, and thereby start the meeting.

**Comment by Reeced40** [comment]
@NickDorak @chrism0n Thank you for reaching out, I'm looking into it.

**Comment by DagTBP** [comment]
I had to automatically allow everyone in the meeting via meeting policies to overcome this issue, which is not really ideal, so having the option for the organizer to start the meeting when dialling in would be great.

**Comment by TokyoScarab** [comment]
Thank you @NickDorak for raising this issue with the GitHub team!  The short answer to your question is yes.  This is referenced in other areas of the Teams documentation and I will make sure to add reference to it in this section of documentation.  Thanks!

**Comment by scanum** [comment]
@NickDorak Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
