### ISSUE TITLE
Additional Requirement?

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2158]
We are trying to enable the Transcription feature for recorded meetings in Teams, but when we do, we get the following error. 

There is nothing in the instructions about needing to change AllowPSTNUsersToBypassLobby to true. Is this an additional requirement?

Thanks

PS CM1:\&gt; Set-CsTeamsMeetingPolicy -Identity Global -AllowTranscription $true
Invalid value combination AutoAdmittedUsers: Everyone and AllowPSTNUsersToBypassLobby: False. When AutoAdmittedUsers is set to Everyone, AllowPSTNUsersToBypassLobby must not be False.
    + CategoryInfo          : InvalidArgument: (Microsoft.Rtc.M...msMeetingPolicy:TeamsMeetingPolicy) 
[Set-CsTeamsMeetingPolicy], ArgumentException
    + FullyQualifiedErrorId : CustomValidationFailed,Microsoft.Rtc.Management.Internal.SetTeamsMeetingPolicyCmdlet
    + PSComputerName        : admin1a.online.lync.com
Invalid value combination AutoAdmittedUsers: Everyone and AllowPSTNUsersToBypassLobby: False. When AutoAdmittedUsers is set to Everyone, AllowPSTNUsersToBypassLobby must not be False.
    + CategoryInfo          : InvalidArgument: (Microsoft.Rtc.M...msMeetingPolicy:TeamsMeetingPolicy) [Set-CsTeamsMeetingPolicy], ArgumentException
    + FullyQualifiedErrorId : CustomValidationFailed,Microsoft.Rtc.Management.Internal.SetTeamsMeetingPolicyCmdlet
    + PSComputerName        : admin1a.online.lync.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording#turn-on-or-turn-off-recording-transcription)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@DeanGross - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@DeanGross - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
