### ISSUE TITLE
Outside Contacts?

### ISSUE THREAD

**Issue by Michael-Sampson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2160]
"This is useful if, for example, one department is handling information that shouldn’t be shared with other departments or a group needs to be prevented from communicating with any outside contacts."

To my eye, the term "outside contacts" gives the impression of external contacts / beyond the organization / beyond the tenant. What about " ... or a group needs to be prevented from communicating with anyone not in the group."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85a288bc-9192-8c65-4ce9-b5abb260206e
* Version Independent ID: 1f953ea6-e6e5-5e71-d541-3962637f25f9
* Content: [Information barriers in Microsoft Teams preview](https://docs.microsoft.com/en-us/microsoftteams/information-barriers-in-teams)
* Content Source: [Teams/information-barriers-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/information-barriers-in-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Michael-Sampson - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@Michael-Sampson Thank you for reaching out, I'm working on it.

**Comment by TokyoScarab** [comment]
Hi @Michael-Sampson! Thank you for raising this issue with the GitHub team!  I do agree the wording on this isn't as good as it could be.  I'll make sure to update this in the documentation to reword it.  Thanks!

**Comment by scanum** [comment]
@Michael-Sampson Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
