### ISSUE TITLE
Broken link "csTeamsMeetingPolicy コマンドレットの使用方法に関する詳細情報"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2167]
Showing " csTeamsMeetingPolicy コマンドレットの使用方法に関する詳細情報 (https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps)。"

https://docs.microsoft.com/ja-jp/microsoftteams/configure-desktop-sharing
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 9ce30163-6327-899b-281d-d4ef982fce5e
* Version Independent ID: e61dcbb8-4877-ef6f-1987-981cdd7fc82f
* Content: [Microsoft Teams でのデスクトップ共有を構成する](https://docs.microsoft.com/ja-jp/microsoftteams/configure-desktop-sharing)
* Content Source: [Teams/configure-desktop-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/configure-desktop-sharing.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **Lolaj**

**Comment by scanum** [comment]
@hyoshioka0128 - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@OfficeGlobal

**Comment by scanum** [comment]
@OfficeGlobal following up on this issue? Could you please update status? Thanks

**Comment by Reeced40** [comment]
@samanthaw

**Comment by scanum** [comment]
@officeglobal any updates on this? Thanks

@officedocsbot assign @officeglobal

**Comment by OfficeGlobal** [comment]
@scanum, @hyoshioka0128 the links are updated and displayed properly

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
