### ISSUE TITLE
Chat between GCC and Commercial Cloud doesn't work

### ISSUE THREAD

**Issue by atguilmette** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2171]
Chat between meeting participants in GCC and commercial clouds doesn't work, so it shouldn't be listed as working.

**Comment by scanum** [comment]
@atguilmette
Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@atguilmette  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by tonysmit** [comment]
Bouncing back here. Cross cloud federation isn't supported.
