### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by eimann** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2172]
Hi,

do the Network and Network Range columns support IPv6?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f8119c9-61af-b469-af98-ddd37764c0ca
* Version Independent ID: 7d829a74-9df7-5b6f-8e1c-44d3e5d38f75
* Content: [Adding and updating Locations data](https://docs.microsoft.com/en-US/microsoftteams/learn-more-about-site-upload?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/learn-more-about-site-upload.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/learn-more-about-site-upload.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@eimann
Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@eimann  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by eimann** [comment]
Hi @scanum,

thanks for your feedback. I don't have a service issue, I have a documentation issue.

From my understanding the documentation should reflect if there's feature parity between IPv4 and IPv6 for Network Locations or not. In my opinion, this is something product management or engineering can provide for this specific component.

Cheers,
Dominik
