### ISSUE TITLE
Confusing "call answering options" description

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2173]
The text in "Select the call answering options" section says:
"You can select up to 200 call agents belonging to specified mailing lists or groups. Call agents must be either:
* An Online user with a Phone System license and enabled for Enterprise Voice or with a Calling Plan.
* Online users with a Phone System license and a Calling Plan that are added to ... a ... Group."

It is slighly better than it was before, but still very confusing.
Please refer to https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/1553

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b755d9ae-13ac-019f-f5f4-a95b1eee2989
* Version Independent ID: f7afd8ad-e6e0-6c79-aed1-4ee87d48ba12
* Content: [Create a call queue](https://docs.microsoft.com/en-us/MicrosoftTeams/create-a-phone-system-call-queue#feedback)
* Content Source: [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-call-queue.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@shivtorov
Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@shivtorov Thank you for reaching out, I'm looking into it.

**Comment by TokyoScarab** [comment]
Hello @shivtorov and thank you for contacting the GitHub team!  I agree that the wording in that section could be a lot better.  I will sort out the wording to not only flow a lot smoother, but also make a lot more sense.  If you have any other questions regarding this, feel free to comment them below, thanks!

**Comment by shivtorov** [comment]
hi @TokyoScarab 
I suggest to further clarify your phrase "mailing lists or groups" with more specific list:

- Office 365 group
- security group
- distribution list

**Comment by scanum** [comment]
@TokyoScarab

**Comment by TokyoScarab** [comment]
@scanum I have made all the suggested edits.  Everything should be in place

**Comment by scanum** [comment]
@shivtorov Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
