### ISSUE TITLE
Where to run the Powershell scripts?

### ISSUE THREAD

**Issue by GrooveCS** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2191]
Is the Meeting Migration Service (MMS) in 
1. Azure
2. SharePoint On-Premises
3. Windows Computer on the domain network

It wonderful that this service exists yet this documentation assumes too much.  The related topic maybe 
[Connect PowerShell to Office 365 services](https://support.office.com/en-us/article/connect-powershell-to-office-365-services-06a743bb-ceb6-49a9-a61d-db4ffdf54fa6)

The question is which resource should one use in Office 365

1. Azure Active Directory      Connect to Office 365 PowerShell
2. Exchange Online      Connect to Exchange Online PowerShell
3. Security & Compliance Center      Connect to Office 365 Security & Compliance Center PowerShell
4. Skype for Business Online      [Connecting to Skype for Business Online by using Windows PowerShell](https://go.microsoft.com/fwlink/p/?LinkId=691607)
5. SharePoint Online      Connect to SharePoint Online PowerShell

I am starting at Skype for Business Online. Grateful, if someone can verify that I'm on the right track. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 990ca74b-6bba-a14b-071a-d13adb723a4c
* Version Independent ID: 52f55a58-30ce-c140-3ee7-8042b1d105f0
* Content: [Using the Meeting Migration Service (MMS)](https://docs.microsoft.com/en-us/SkypeForBusiness/audio-conferencing-in-office-365/setting-up-the-meeting-migration-service-mms?toc=%2FMicrosoftTeams%2Ftoc.json&bc=%2Fmicrosoftteams%2Fbreadcrumb%2Ftoc.json#feedback)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/setting-up-the-meeting-migration-service-mms.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/setting-up-the-meeting-migration-service-mms.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@GrooveCS  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
