### ISSUE TITLE
"Meet Now" missing on Android

### ISSUE THREAD

**Issue by vsegal** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#220]
The "Meet Now" button is missing in the Android app.  But this page claims Android supports "Start an unscheduled group conversation with multiple participants directly from your client or device".  Can someone please clarify?  "Meet Now" is available on iOS, but why not on Android?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 257dc4a1-8091-23db-64c4-f46b0519e14e
* Version Independent ID: c5094b34-c69d-9e8d-40cb-9197b924e632
* Content: [Mobile client feature comparison for Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/mobile-feature-comparison)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/mobile-feature-comparison.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/mobile-feature-comparison.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
check removed from box. apparently this was never actually supported, no reason is available.

**Comment by vsegal** [comment]
This is unfortunate, since this is such a useful feature, being able to make conference call with multiple people using Skype VOIP instead of using clunky 3-way mobile calling.  I'm really hoping this will be eventually added to Android, since I don't see a reason why not - especially that it's already there in iOS.  Does Microsoft provide a page where I can submit a "suggested feature" for this product?

**Comment by jambirk** [comment]
https://www.skypefeedback.com/ is a place that customers can vote on suggested improvements.
