### ISSUE TITLE
What is the FREECALL capability?

### ISSUE THREAD

**Issue by ThePangy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2201]
We run this report monthly and today was the first time I saw a capability of "FREECALL". This is not listed in the documentation above as an available capability. What is this referring to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 433c52a1-5721-a082-ab60-62e49d4bf330
* Version Independent ID: b961db7c-77b3-31c8-30f7-7f984c5805c0
* Content: [PSTN usage report](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-online-reporting/pstn-usage-report)
* Content Source: [Skype/SfbOnline/skype-for-business-online-reporting/pstn-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/skype-for-business-online-reporting/pstn-usage-report.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@ThePangy Thanks for submitting feedback. We will get this investigated.

**Comment by scanum** [comment]
@ThePangy - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
