### ISSUE TITLE
How to register device in Teams

### ISSUE THREAD

**Issue by rtenhet** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2202]
I am confused as how a new Teams device gets registered. 
 "A device is automatically enrolled the first time a user signs in to Teams on the device."

I have signed into a new Team Room System, however, no device is showing up in the Teams Admin console.  This is a Logitech certified system, so I assume it should just register?  What am I missing, are there other prereqs?

Thanks.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@rtenhet Thanks for submitting feedback. We will get this investigated.

**Comment by scanum** [comment]
@rtenhet - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
