### ISSUE TITLE
link dead

### ISSUE THREAD

**Issue by mnblacklock** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2206]
Plan your Phone System in Office 365 (Cloud PBX) solution

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 243fa83d-b7bf-323a-a14a-026915d3d058
* Version Independent ID: fd4a310b-3144-4a8b-1bde-c2efd0c87377
* Content: [Calling Plans for Office 365](https://docs.microsoft.com/en-us/microsoftteams/calling-plans-for-office-365)
* Content Source: [Teams/calling-plans-for-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/calling-plans-for-office-365.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@mnblacklock Thanks for submitting feedback. We will get this investigated.

**Comment by Reeced40** [comment]
@mnblacklock Thanks for reaching out, I'm working on it.

**Comment by Reeced40** [comment]
@mnblacklock Please could you check if this document would work for you - https://docs.microsoft.com/microsoftteams/what-is-phone-system-in-office-365

**Comment by scanum** [comment]
@mnblacklock Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
