### ISSUE TITLE
User can communicate with Skype users - no information ?!

### ISSUE THREAD

**Issue by MattPfe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2209]
Every setting except "User can communicate with Skype users" is mentioned on this site.

Is this for Skype Consumer or why is the setting OFF?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31588a25-f3ee-e888-aa67-203be3d34489
* Version Independent ID: 3b498bcf-69a9-01ac-973a-4d5dbeea587c
* Content: [Manage external access (federation) in Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/manage-external-access?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@MattPfe Thanks for submitting feedback. We will get this investigated.

**Comment by scanum** [comment]
@MattPfe - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by danmyhre** [comment]
This is probably just the toggle for skype for business users, as this was a feature that was possible with Skype for Business.  The documentation needs to be updated to reflect that.  #reopen

**Comment by danmyhre** [comment]
@mattpfe - they just changed the language in the portal to reflect this.  It now says "Skype for Business users can communicate with Skype users".  Hopefully this will get added for Teams users as well.  

It is confusing that this setting is in the Teams admin center when it currently has nothing to do with Teams.  

@scanum - please re-open as the documentation here still needs to be fixed.  In fact, this page doesn't even mention this radio button on the Org-Wide Settings->External Access page of the admin center.

#reopen
