### ISSUE TITLE
Mac Add-In

### ISSUE THREAD

**Issue by lundejd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#221]
Can you give us a timeline for the Mac add-on?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Use the Microsoft Teams Meeting add-in in Outlook](https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* Product: **unspecified**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by chuckedmonson** [comment]
To find out about this and to stay on top of what else is coming in Teams, please visit the [Teams product roadmap](https://aka.ms/TeamsRoadmap). 
This falls under "In Development" ("Microsoft Teams - Outlook meeting schedule from other platforms"). Thank you.

**Comment by idarlund** [comment]
Microsoft Teams - Outlook meeting schedule from other platforms (OWA, OLK mobile)
This is one of the SfB meeting capabilities coming to Teams. This feature will enable meeting scheduling on mobile, web, and Mac platforms. This feature is targeted for availability by Q2 CY 2018.
**Estimated Release: June CY2018**
Feature ID: 24221
Added to Roadmap: 10/24/2017
Last modified : 06/14/2018
Tags: Microsoft Teams

**Comment by naronneSovLabs** [comment]
Any updated ETA on the Mac integration for Outlook/Teams?

**Comment by willdrobins** [comment]
Can somebody from the product team comment on a new date since we are past June?

**Comment by chuckedmonson** [comment]
@ninadara -- Can you provide some information about this inquiry? Thank you.

**Comment by michaelcsilva** [comment]
Mac outlook integration with MS Teams is a must.  Please provide this feature.

**Comment by chuckedmonson** [comment]
@voltarone @juturu -- Can you please answer the inquiries about the Teams add-in or direct to the appropriate person? Thank you.

**Comment by jbrickey** [comment]
+1 for this Mac capability. Scheduling recurring meetings in TEAMS is very cumbersome and I can't look to far into the future. Outlook is the only effective way of doing this AFAI can see.

**Comment by blachole** [comment]
This is now live and working in Outlook 16.18 release on Mac.

**Comment by lundejd** [comment]
I've got 16.18 (180827) Teams 1.1.00.19253. and see no Teams add-in.   Did you install something else to get this by chance?

**Comment by blachole** [comment]
@lundejd Nope, just got prompted for it this morning and saw it was there after. See photo: https://ibb.co/hdMO59

**Comment by lundejd** [comment]
@blachole well its a positive sign it does work for you.  This means Microsoft is working on it at least. 

I'll keep checking.   I wonder if there is a tenant side change that needs to take place.   (Ours always seems to be at the tail end of any rolling updates)

Interested to hear if anyone else got theirs working.

**Comment by jbrickey** [comment]
Yes works for me to. I changed my preference in the updates to be in the fast lane and got 16.18.

**Comment by jrockett** [comment]
I for 16.18 (180827) and reinstalled teams and nothing on my end. Anything special you had to do?

**Comment by jbrickey** [comment]
@jrockett, nothing special. I would try to shut down bot outlook and teams. Start teams then outlook. Teams option should show when you schedule a new meeting.

**Comment by idarlund** [comment]
Not working for me either. I only have Skype Meeting button. Even tho teams are running and skype is not..
![image](https://user-images.githubusercontent.com/3417634/45212321-e152bd00-b294-11e8-97be-da7caed8af1e.png)
Any idea how to activate the new teams meeting button?

**Comment by AndreaBarr** [comment]
@lundejd Thank you for this feedback 

I have checked and made sure that this issue is in the Backlock. We will make sure to reply with an update as soon as we know anything further. We are working on this and appricate you checking in with us on this MAC button issue.

**Comment by Squuiid** [comment]
February 28th 2019 and we STILL don't have a Teams button in Outlook for Mac.
This is pathetic.

**Comment by blachole** [comment]
Anyone still having the issue of the plugin not showing up, I posted a fix for forcing it over on Reddit: https://reddit.com/r/MicrosoftTeams/comments/beoh1a/fix_teams_meeting_plugin_for_outlook_on_mac/
