### ISSUE TITLE
PowerShell instructions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2210]
In the instructions at https://docs.microsoft.com/en-us/SkypeForBusiness/audio-conferencing-in-office-365/turn-on-or-off-entry-and-exit-announcements-for-meetings#want-to-know-how-to-manage-with-windows-powershell the first bullet provides helpful details that are not included on this page. Could you please add that information onto this page also

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07eca314-7a40-c7ee-1d31-7a858adff741
* Version Independent ID: dede6892-d7e3-d44d-f8f6-eb4bd50c07f0
* Content: [Turn on or off entry and exit announcements for meetings in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/turn-on-or-off-entry-and-exit-announcements-for-meetings-in-teams#feedback)
* Content Source: [Teams/turn-on-or-off-entry-and-exit-announcements-for-meetings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/turn-on-or-off-entry-and-exit-announcements-for-meetings-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@DeanGross Thanks for submitting feedback. We will get this investigated.

**Comment by get-itips** [comment]
Hello @DeanGross 
How are you? Do you mean to include the information to _Turn on or off entry and exit announcements for meetings in Microsoft Teams_ but using Teams Powershell module?

**Comment by scanum** [comment]
@DeanGross  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
