### ISSUE TITLE
Update on "Appropriate Licensing Model?"

### ISSUE THREAD

**Issue by scotchpb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2211]
Is there an update on the time frame of when Microsoft will address and fix the licensing for auto attendants and call queues? It seems ridiculous to have to purchase a combination of rather expensive licenses (e.g. E1 + Phone System + Calling Plan ... or ... E5 + Calling Plan) in order to utilize the auto attendant and call queue features which should be basic offerings of Microsoft's PBX offering without having to pay additional fees, especially for small businesses that don't have hundreds of O365 licenses. I understand that there are technical reasons built into the licensing system that require these licenses be assigned to resource accounts so that all the requirements of being able to assign a phone number, etc. within Teams are satisfied, but forcing a combined monthly fee of anywhere from $28 to $47 for each instance of an auto attendant and call queue is unacceptable. Again, these are basic features of any PBX system and should already be included in a cloud-based PBX like Microsoft Teams without additional fees.

Perhaps, until the back-end work can be done to actually develop an appropriate licensing model for auto attendants and call queues, could Microsoft setup a recurring bill credit to offset the licenses assigned to resource accounts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40ed9cf1-93cc-698a-a974-44584c2ad448
* Version Independent ID: 10b1f715-8c08-7943-2bbf-699e1a59b358
* Content: [What are Cloud auto attendants?](https://docs.microsoft.com/en-us/microsoftteams/what-are-phone-system-auto-attendants#feedback)
* Content Source: [Teams/what-are-phone-system-auto-attendants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-phone-system-auto-attendants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@scotchpb Thanks for submitting feedback. We will get this investigated.

**Comment by scanum** [comment]
@scotchpb - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
