### ISSUE TITLE
Needs updates

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2213]
Still not showing Planner, Live Captioning, Background Blur, and more...  Can this list get a comprehensive review for features that are not in GCC?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7faee29-6d56-f3bf-766c-6deaefe92e34
* Version Independent ID: 6029b6f8-7d49-6474-fa40-2793000c74a4
* Content: [Plan for Microsoft 365 Government - GCC deployments - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/plan-for-government-gcc#feedback)
* Content Source: [Teams/plan-for-government-gcc.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-for-government-gcc.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lehewe**

**Comment by npherson** [comment]
Forms, Website tab were the other 2 I couldn't think of right away.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@npherson Thanks for submitting feedback. We will get this investigated.

**Comment by NivineZakhari** [comment]
Also any difference in limits, where applicable. https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams

**Comment by LolaJacobsen** [comment]
I will ask PM Karvell Li about this.

**Comment by karvell** [comment]
The message size, file attachment, and inline images limits are the same across licenses.

**Comment by LolaJacobsen** [comment]
I updated limits-specifications-teams. I circled back with @karvell about updating the GCC article.

**Comment by LolaJacobsen** [comment]
Checking with PM David Rosenthal.

**Comment by LolaJacobsen** [comment]
@npherson - we're getting ready to do an all-up review/update of our Government/GCC content, so I'm not going to make further updates to this article right now. The PM has your feedback, and he'll include it in the upcoming updates. Thank you!
