### ISSUE TITLE
Information about where is data stored for Teams and Channels vs Chats vs Meetings vs Apps

### ISSUE THREAD

**Issue by ritika2502** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2218]
I am at customer summits this week and there are a lot of questions around where is what type of data stored and is DLP and retention enforced on those... something along the lines 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06059d07-6687-2924-7d0a-3c03220a1650
* Version Independent ID: bb293f92-9394-b156-2e08-0baead5c3bbe
* Content: [Overview of teams and channels in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-channels-overview#feedback)
* Content Source: [Teams/teams-channels-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-channels-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@ritika2502 Thanks for submitting feedback. We will get this investigated.

**Comment by LolaJacobsen** [comment]
Thank you for your feedback, @ritika2502. I updated teams-channels-overview:

-   **Channels** are dedicated sections within a team to keep conversations organized by specific topics, projects, disciplines—-whatever works for your team! Files that you share in a channel (on the Files tab) are stored in SharePoint. To learn more, read [How SharePoint Online and OneDrive for Business  interact with Teams](SharePoint-OneDrive-interact.md).

    -   Team channels are places where everyone on the team can openly have conversations. Private chats are only visible to those people in the chat (and files that you share in a chat are stored in OneDrive for Business). 

    -   Channels are most valuable when extended with apps that include tabs, connectors, and bots that increase their value to the members of the team. To learn more, see [Apps, bots, & connectors in Teams](deploy-apps-microsoft-teams-landing-page.md).
