### ISSUE TITLE
ability for guest to add files to a files tab

### ISSUE THREAD

**Issue by joeruder** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#223]
It is not clear if a guest can add a file.  We are not able to get our Guests to do that as of yet...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [What the guest experience is like](https://docs.microsoft.com/en-us/microsoftteams/guest-experience)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* Product: **unspecified**
* GitHub Login: @laithalshamri
* Microsoft Alias: **laal**

**Comment by chuckedmonson** [comment]
@alihirsch -- Can you follow up on this customer comment please? Thank you

**Comment by joeruder** [comment]
Thanks chuckedmonson  - this was just brought up again in our IT standup this AM from another internal team.  It would be great if guest access could be the same as normal access but configurable by the team owners.  As it is we have pretty much given up on using teams for anything except internal projects which *really* is hurting out adoption rate.  We are trying to replace Mikogo and other screen sharing and meeting software but with the lack of being able to QUICKLY add somebody to a meeting or experience it is going to be a non-starter for us.

**Comment by alihirsch** [comment]
Thanks @chuckedmonson. I don't know the answer. Adding @rramesan who, last I knew, was leading the guest access work.

**Comment by somakbhattacharyya** [comment]
Thanks for reaching out. Guests can add files into the ‘Files’ library associated with the Team and can attach those files in to their posts. Guests can also share files uploaded from their devices. Guests however don’t have ODB provisioned.

**Comment by joeruder** [comment]
Perhaps we had / have something configured wrong.  Our guest accounts were not able to do that, or at least that is what they said.
I will be happy to test tomorrow and verify.

Thank you --

Joe

**Comment by lis1313** [comment]
So can guest users also edit the documents via Teams, like co-authoring, edit in browser etc?  Thanks so much!

**Comment by lis1313** [comment]
@somakbhattacharyya So can guest users also edit the documents via Teams, like co-authoring, edit in browser etc? Thanks so much!

**Comment by lis1313** [comment]
Also if user is blocked from Downloading the actual Teams client on their computer- can they access via Chrome browser- a guest user just tried- and it was not working- does end user have to have latest version of Chrome? thanks!

**Comment by kenwith** [comment]
It sounds like this is resolved but if not I think the best way forward to get any open issues resolved ASAP is to open a service ticket in your tenant. Then this can be prioritized and routed correctly so it doesn't linger here in doc issues. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

Thank you very much everyone for the great feedback and help. It is a really awesome community going here!

**Comment by somakbhattacharyya** [comment]
@lis1313 yes, once enabled, co-authoring is available for Guests. Guests can use any supported browser if they don't have access to the desktop app.

I'll highly recommend you to check our [official documentation](https://docs.microsoft.com/en-us/MicrosoftTeams/Microsoft-Teams) which goes into details of setup, supported features and guest licensing requirements.

**Comment by joeruder** [comment]
Thank you for the help.  I am not sure if it is resolved only because we quit using guests and simply made them team members of our organization.
