### ISSUE TITLE
Feature List is not complete

### ISSUE THREAD

**Issue by Kupferschmid** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2248]
For example: Share Desktop or send Emojis. We need a full list of all Features. Especially for external federated communication?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 31588a25-f3ee-e888-aa67-203be3d34489
* Version Independent ID: 3b498bcf-69a9-01ac-973a-4d5dbeea587c
* Content: [Verwaltung des externen Zugriffs (Verbund) in Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/manage-external-access#feedback)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Kupferschmid Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@Kupferschmid Thank you for reaching out, I'm investigating further.

**Comment by scanum** [comment]
@Kupferschmid Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
