### ISSUE TITLE
Guest can't sign in using Gmail.com

### ISSUE THREAD

**Issue by tsf1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#225]
While [this document ](https://docs.microsoft.com/en-us/MicrosoftTeams/guest-access) clearly states that "anyone with a [...] consumer email account (with Outlook.com, Gmail.com or others) can participate as a guest in Teams," the guest can't authenticate unless he uses a MSA. **Is a non-MSA like Gmail.com allowed?**

Scenario: I invited a gmail.com user as a Guest. When the user clicks on the email link they're taken to a page asking them to authenticate. When trying to use the Gmail.com address, it won't authenticate. It displays an error message stating "We couldn't find an account with that username." As soon as the person switches to using a MSA, it let's them right in. What's wrong and how can this be corrected?

**Comment by kenwith** [comment]
@tsf1 - sorry for the delay on this and thank you for submitting feedback. It has been a very long time and I am hoping you have already resolved this issue. If you haven't, I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
