### ISSUE TITLE
[LOC] "来園者" needs to be replaced with "ゲスト" 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2254]
https://docs.microsoft.com/ja-jp/microsoftteams/guest-access-powershell

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 18cf5b2f-9527-c59d-cacf-04ea9d4f61f3
* Version Independent ID: a34cff52-ce5c-1830-69e9-3b07cf111ce9
* Content: [PowerShell を使用してチームへのゲスト アクセスを制御する](https://docs.microsoft.com/ja-jp/microsoftteams/guest-access-powershell)
* Content Source: [Teams/guest-access-PowerShell.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-PowerShell.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@OfficeGlobal

**Comment by scanum** [comment]
@OfficeGlobal following up on this issue? Could you please update status? Thanks

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum string was updated and published live. The issue is fixed

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
