### ISSUE TITLE
Groups to Teams 

### ISSUE THREAD

**Issue by jaiave** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#227]
How do we link an existing group to a team ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d86301b-ce9c-388c-e563-9e5e5c27132e
* Version Independent ID: 07e4ae23-0966-e8f3-9b7c-4f6c02569eb0
* Content: [Office 365 groups and Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/office-365-groups)
* Content Source: [Teams/Office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-groups.md)
* Service: **msteams**
* Product: **unspecified**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by chuckedmonson** [comment]
You can't create a new team from an existing group, but but you can take an existing team, and link it to an existing group.

![imgpsh_mobile_save](https://user-images.githubusercontent.com/33042436/40390390-eef9df9e-5dc9-11e8-835e-ca25618686e7.jpg)

You will only see this option if you are an owner of a group that isn't a team.

**Comment by jaiave** [comment]
Thank you for your quick response
