### ISSUE TITLE
XLS Files not downloadable?

### ISSUE THREAD

**Issue by TobieFysh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2270]
The three files referenced here do not appear to be live.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a64e4ff2-8500-ae6c-2670-477ae7152a0d
* Version Independent ID: 8bdb79d5-4460-b383-e38d-2db72d4d54f4
* Content: [Lync Server 2013: Operations checklists](https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-operations-checklists)
* Content Source: [Lync/LyncServer/lync-server-2013-operations-checklists.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Lync/LyncServer/lync-server-2013-operations-checklists.md)
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@TobieFysh Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@TobieFysh Thank you for reaching out to improve MS Doc, it will be sorted out soonest.

**Comment by Reeced40** [comment]
@LanaChin

**Comment by scanum** [comment]
@LanaChin Hi Lana, any updates on this? Thanks!

**Comment by LanaChin** [comment]
The article is updated with links to the downloadable checklist files.  Thanks.
