### ISSUE TITLE
Teams DSCP Value

### ISSUE THREAD

**Issue by keffen611** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2272]
Hi,

I would like to know if the packets transmitted from "Teams / Skype for Business" has DSCP value configured by default?
Then I just need to config DiffServ on Switch then I would be good to go for Switch config.
Do I need to config "Teams / Skype for Business" to tag the packets with DiffServ explicitly?
Thanks.

David

**Comment by scanum** [comment]
@keffen611 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
