### ISSUE TITLE
Chrome Mobile Support

### ISSUE THREAD

**Issue by joeljanke** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2273]
This page states that Chrome is a supported browser, however, real world experience shows that Microsoft is blocking the Chrome mobile browser whether that is in Desktop mode or mobile mode.  It was stated elsewhere that if Chrome is supported it is supported regardless of OS.  So is it supported or not?  Ideally I would like to see the Chrome Mobile browser be supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/get-clients#feedback)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@joeljanke Hi, Chrome is a supported browser, both web and mobile. thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
