### ISSUE TITLE
Licensing of "old" queues

### ISSUE THREAD

**Issue by SRE93** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2275]
Hi, the new licensing model in teams for resource accounts to assign attendants or queues to phone numbers is huge crap. Now we have to subscribe to dozens of additional licenses to use these functions, especially since teams telephony is already a luxury product compared to the competition.
When can a reasonable, revised model be expected?
How will the "old", unlicensed attendants and queues migrated from the S4B legacy portal be handled? Is there a transitional phase until these have to be licensed as well?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b755d9ae-13ac-019f-f5f4-a95b1eee2989
* Version Independent ID: f7afd8ad-e6e0-6c79-aed1-4ee87d48ba12
* Content: [Erstellen einer Anrufwarteschlange](https://docs.microsoft.com/de-de/microsoftteams/create-a-phone-system-call-queue#step-1---get-started)
* Content Source: [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-call-queue.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@SRE93 - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make Skype for Business better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://www.skypefeedback.com.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by scanum** [comment]
@officedocsbot close
