### ISSUE TITLE
VIS port

### ISSUE THREAD

**Issue by waelschakaki** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2278]
Hello,
Could you please add the port range for the VIS server ? is it the same Video port range which is used for conferencing servers? or is it the same as the client video port range ?
Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5164207-7822-cf54-717e-6216e0627ebd
* Version Independent ID: 786f5413-3660-06eb-484f-8d5758d3ec59
* Content: [Port and protocol requirements for servers](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/network-requirements/ports-and-protocols)
* Content Source: [Skype/SfbServer/plan-your-deployment/network-requirements/ports-and-protocols.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/network-requirements/ports-and-protocols.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@waelschakaki  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@waelschakaki Thank you for reaching out, I'm looking into it.

**Comment by scanum** [comment]
@waelschakaki  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
