### ISSUE TITLE
Article Migrating Lync Online users to Lync on-premises in Lync Server 2013 needs urgent review

### ISSUE THREAD

**Issue by cadasi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2287]
This file has an invalid link to an **internal** Microsoft server, and the file is not even there! I would fix the file myself, but I couldn't find a valid Public link to download the certificate chain, and I am not even sure that the chain mentioned in the article is **valid** anymore.

Article is:
https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-migrating-lync-online-users-to-lync-on-premises?lc=1033

Problem is here:

Confirm that on your on-premises Edge Servers, you have the certificate chain that enables connection to Lync Online, as shown in the following table. You can download this chain here: **https://corp.sts.microsoft.com/Onboard/ADFS_Onboarding_Pack/corp_sts_certs.zip .**

If it will take a long time to review, I would just remove that section, as once again, really bad that is pointing to an **internal** Microsoft server.

**Comment by cadasi** [comment]
To add to that comment, maybe it would be better to redirect customer to this article:
https://support.office.com/en-ie/article/office-365-certificate-chains-0c03e6b3-e73f-4316-9e2b-bf4091ae96bb 
And remove the table with the certificate chain to not cause confusion.

**Comment by scanum** [comment]
@cadasi Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by VLG17** [comment]
@cadasi @scanum the article looks ok now, and it references the correct article, which was mentioned above.

**Comment by scanum** [comment]
@cadasi Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
