### ISSUE TITLE
Missing last two updates - March security update and CU9 published in May.

### ISSUE THREAD

**Issue by ksagala** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2289]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be9f745c-5925-3a7b-9430-b5e61b4384ba
* Version Independent ID: bc23dce3-f38b-9e81-1614-d16aed1d8684
* Content: [Skype for Business Server updates](https://docs.microsoft.com/en-us/skypeforbusiness/sfb-server-updates#feedback)
* Content Source: [Skype/SfbServer/sfb-server-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/sfb-server-updates.md)
* Product: **skypeforbusiness-server-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by VLG17** [comment]
@ksagala the article has been updated and includes the info about CU9. The newer CUs contains the security update.

**Comment by scanum** [comment]
@ksagala Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
