### ISSUE TITLE
Conflicting information

### ISSUE THREAD

**Issue by chraymu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2291]
This document that states that Calling through Direct Routing is supported in Islands Mode AND states that it is only supported in Teams Only mode. 
•	“Teams Only is required for Phone System with Teams” – Fundamental Concepts, bullet point 8
•	“Islands with Phone System and Direct Routing for Teams” – Detailed Mode descriptions, Islands section, PSTN functionality bullet point.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49921e8a-55ac-f547-d4e2-d329f5089c2e
* Version Independent ID: 91c3433a-3684-95cd-3426-4a5877b33106
* Content: [Migration and interoperability guidance for organizations using Teams together with Skype for Business](https://docs.microsoft.com/en-us/microsoftteams/migration-interop-guidance-for-teams-with-skype)
* Content Source: [Teams/migration-interop-guidance-for-teams-with-skype.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/migration-interop-guidance-for-teams-with-skype.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@chraymu Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@chraymu Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
