### ISSUE TITLE
This information should be edited or removed

### ISSUE THREAD

**Issue by brandonmarcus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2293]
According to the Exchange online admin console, the domain "email.teans.microsoft.com" should not be added. The interface reads, "WARNING: Do not add domains you own or popular domains (e.g. microsoft.com) to the Domain allow list. This is considered high risk since it creates opportunities for bad actors to send you mail that would otherwise be filtered out."
What is the recommended guidance here? Or is this Sept 2017 article dated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43bc0cae-682a-7227-35d6-d3c37545a3a4
* Version Independent ID: fbcd00ac-8899-fb95-28aa-dfc523b81c65
* Content: [Add the Microsoft Teams SMTP domain as an allowed sender domain in Exchange Online](https://docs.microsoft.com/en-us/microsoftteams/smtp-accepted-domain#feedback)
* Content Source: [Teams/SMTP-accepted-domain.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/SMTP-accepted-domain.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@brandonmarcus Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by VLG17** [comment]
@brandonmarcus The article states to "consider" adding Microsoft Teams SMTP domain to the allowed sender domains. It does not state that this is a must. 

If you have configured SPF, DKIM and DMARC correctly, adding "@email.teams.microsoft.com" to the list should not create a threat (spoofing for example).

**Comment by scanum** [comment]
@brandonmarcus Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
