### ISSUE TITLE
Incorporate O365 Meeting Room License into chart

### ISSUE THREAD

**Issue by jdayon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2294]
Unclear how that O365 Meeting Room License relates to chart below it. For example, I want to 'Join a scheduled meeting' and I have 'Office 365 Premium, Office 365 ProPlus, or Skype for Business Standalone Plan 2'. The chart suggests I need to buy 'Skype for Business Standalone Plan 1'. Do I need to buy that _in addition_ to O365 Meeting Room License?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses](https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/skype-room-systems-v2#feedback)
* Content Source: [Teams/room-systems/skype-room-systems-v2.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/skype-room-systems-v2.md)
* Service: **skype-for-business-online**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@jdayon Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum
