### ISSUE TITLE
Screenshot is different than language in tenant

### ISSUE THREAD

**Issue by marklitwin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2297]
The screenshot showing how to disable External Access is different than how it is written in the tenants.  Not clear which has the newer verbiage, but this article should be clear if disabling External Access also impacts the ability for external users to be invited or join meetings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31588a25-f3ee-e888-aa67-203be3d34489
* Version Independent ID: 3b498bcf-69a9-01ac-973a-4d5dbeea587c
* Content: [Manage external access (federation) in Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/manage-external-access?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@marklitwin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@marklitwin Thank you for reaching out to improve MS Doc, it will be sorted out soonest.

**Comment by Reeced40** [comment]
@marklitwin It seems that the screenshot has been corrected in the doc, so it should be reading correctly now. Let me know if you have any further queries. Thanks.

**Comment by scanum** [comment]
@marklitwin Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
