### ISSUE TITLE
Issue with "Note" - cummulative updates

### ISSUE THREAD

**Issue by hirshah** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2298]
The link for cumulative updates in "Notes" points to cumulative updates for SFB Server 2015 and not 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4efe6d13-f662-6864-5362-3076746c56a5
* Version Independent ID: 2ed0bbda-9214-cac8-7a3b-c299dfd4fa42
* Content: [Install Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/install/install?toc=%2FSkypeForBusiness%2Ftoc.json&bc=%2FSkypeForBusiness%2Fbreadcrumb%2Ftoc.json#feedback)
* Content Source: [Skype/SfbServer/deploy/install/install.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/install/install.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hirshah Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by jambirk** [comment]
@scanum The link is correct, that page will in fact be where cumulative updates are listed once they are released. CU1 for Server 2019 has not yet been released.

**Comment by scanum** [comment]
@hirshah Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
