### ISSUE TITLE
Is Skype for Business mobile client supported for RGS

### ISSUE THREAD

**Issue by brodyriver** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2299]
When you say "The Response Group application is not supported on Lync mobile clients", are you including "Skype for Business" mobile clients too or are they supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4146039-6a62-7a47-9f02-5600cb026c6c
* Version Independent ID: ab460f03-0253-4cdc-df42-4268f8987be2
* Content: [Plan for the Response Group application in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/enterprise-voice-solution/response-group#feedback)
* Content Source: [Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/response-group.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/response-group.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@brodyriver Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by EirikLind** [comment]
I just checked this with a Hunt Group, and to my suprise this now works on Skype for Business for Android. I don't know when this was updated, but it's a welcome change for sure. (I can't verify that it works on iOS)

**Comment by scanum** [comment]
@brodyriver Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
