### ISSUE TITLE
Support version of Firefox

### ISSUE THREAD

**Issue by naminakao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#23]
I have a customer telling us they cannot display Teams on FireFox ESR 52.3.0. I also found out that I cannot display Teams using FireFox ESR 52.5.2.
If we don't support ESR version, would you update the Known workaround for Safari web client support to tell users FireFox ESR is not supported.

**Comment by tonysmit** [comment]
@LolaJacobsen - I was here. Not sure if you seen this.

**Comment by alihirsch** [comment]
Per mail on 2/7 w/lolaj, get-clients topic updated with language agreed to w/PM: "yes “current + 2 previous” is the final verbiage we agreed on." Topic updated and published.
