### ISSUE TITLE
Incorrect statement about extenrla users?

### ISSUE THREAD

**Issue by thatmattwade** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2300]
In the "Other Considerations" section of this page, it states "Currently, you can only invite people from within your company, as it is not yet possible for external users to join meetings." I believe this is outdated or incorrect. If it's accurate, it must relate to something specific to the Outlook plug in, but is causing confusion in a different forum. So further details should be added if it's accurate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Use the Microsoft Teams Meeting add-in in Outlook](https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook#feedback)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@thatmattwade Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by msbemba** [comment]
@thatmattwade Thank you for your feedback. We have corrected the other consideration section with necessary changes. This has been tracked via PR https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/2331

**Comment by scanum** [comment]
@thatmattwade Thank you for submitting feedback. We appreciate your inputs and will consider them when updating this doc in the future.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
