### ISSUE TITLE
Admin settings for apps does not show in Tenant 

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2302]
can you add documentation on how to revert the apparently blocking setting for :
&gt;&gt; If you enabled the org-wide app permission policy setting, Allow interaction with custom apps, you may not see app setup policies yet in the Microsoft Teams admin center. 

the current documentation only shows how to configure his , _After_ the feature is enabled / deployed 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 143108bb-d6e6-48a8-a7cb-d11b89ebeaab
* Version Independent ID: 145773e2-149e-1c1c-5797-433c13f13b22
* Content: [Admin settings for apps in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/admin-settings#feedback)
* Content Source: [Teams/admin-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/admin-settings.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Josverl Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by msbemba** [comment]
@Josverl Thank you for your feedback.  The document https://docs.microsoft.com/en-us/microsoftteams/teams-app-permission-policies shows how to manage org wide app settings. 

Hope this helps!

Regards
Sriraman

**Comment by scanum** [comment]
@Josverl Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
