### ISSUE TITLE
Removing an application instance

### ISSUE THREAD

**Issue by Digitalmocking** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2303]
The documentation states to remove the phone number before you remove the Application Instance, but there's no documentation on how to do that.

**Comment by scanum** [comment]
@Digitalmocking What documentation? Thanks!

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@Digitalmocking  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
