### ISSUE TITLE
New ADAL Library also needs the following redirect URI for Microsoft.AAD.BrokerPlugIn

### ISSUE THREAD

**Issue by bwilsonms** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2304]
When using newer versions of Microsoft Skype for Business you might see errors in the AAD operational log similar to denies as the URI in https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-native-uwp-wam/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcc8ce50-2000-041a-9489-0acea7b2e24a
* Version Independent ID: 0839378b-1455-b5b5-f315-29e55c25cee8
* Content: [How to use Modern Authentication (ADAL) with Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/manage/authentication/use-adal#feedback)
* Content Source: [Skype/SfbServer/manage/authentication/use-adal.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/authentication/use-adal.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@bwilsonms Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@bwilsonms Thank you for your feedback, I'm looking into it.

**Comment by bwilsonms** [comment]
The original link in the issue above is no longer there?

**Comment by Reeced40** [comment]
@bwilsonms I can't see exactly what you're referring to, is there anything you could suggest?

**Comment by bwilsonms** [comment]
Sure, if you look above it shows the following:
Content: How to use Modern Authentication (ADAL) with Skype for Business
Content Source: Skype/SfbServer/manage/authentication/use-adal.md
The first hyperlink now longer goes to that page, it goes to: https://docs.microsoft.com/en-us/office365/enterprise/hybrid-modern-auth-overview#feedback
The second link (content source) is missing.

The whole point of this was because the scripts customers were downloading to configuring their ADFS servers for office, were not including the new URIs required for programs using the Windows 10 WEB (Web Account Manager).

**Comment by bwilsonms** [comment]
I see the following at the top level of the documentation:
![image](https://user-images.githubusercontent.com/40600428/58883894-51b82e80-86ad-11e9-9625-84c7e9f09004.png)

@MSFTTracyP
MSFTTracyP Delete use-adal.md  …
Delete
Latest commit 54f926c  13 days ago

**Comment by Reeced40** [comment]
@bwilsonms thanks for letting me know.  It looks like the author has removed the link from the article.  Let me know if there are any other changes/additions that you recommend for the article.

**Comment by scanum** [comment]
@bwilsonms 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
