### ISSUE TITLE
Missing Event ID 20033

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#231]
Event ID 20033 and 31060 is missing the table.

I have found something helpful in the following link: https://social.technet.microsoft.com/Forums/lync/en-US/d36af8ab-60cb-4e96-8b6e-7bf8a528812a/lsucwaskype-ucwa-encountered-an-unobserved-task-exceptionevent-id-200331099?forum=sfbfr

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4af2f16-9c6e-c02a-8e89-0893f4284483
* Version Independent ID: 002fecfc-91a5-bd8e-3c59-922c4f3b59b3
* Content: [UCWA events in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/manage/health-and-monitoring/ucwa-events#feedback)
* Content Source: [Skype/SfbServer/manage/health-and-monitoring/ucwa-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/health-and-monitoring/ucwa-events.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by nsshommo** [comment]
I need to know about event 20029, this list only goes up to 20027. The cause and resolution column would be very helpful if contains more info.

**Comment by jambirk** [comment]
Sorry, It's not possible to expand this table.
