### ISSUE TITLE
Adding SBC Vendor to Config Section

### ISSUE THREAD

**Issue by 0llieRoberts** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2311]
[Enter feedback here]
Could you please add Oracle Communications to the Configure and Deploy Section of the guide.  Proposed bullet copy:

Oracle Communications:  To configure an [Oracle E-SBC for Microsoft Teams](https://www.oracle.com/industries/communications/enterprise-session-border-controller/microsoft.html) Direct Routing, please reference the Technical App Note under the Related Resources section for our certified platforms.

Thanks
Ollie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure a Session Border Controller for multiple tenants](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-sbc-multiple-tenants#feedback)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@0llieRoberts Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@0llieRoberts Thank you for your feedback, I'm working on it.

**Comment by tonysmit** [comment]
@CarolynRowe - can you confirm this with the PM before it gets added please?

**Comment by scanum** [comment]
@CarolynRowe Hi Carolyn, any updates on this? Thanks!

**Comment by CarolynRowe** [comment]
@NMuravlyannikov Can you review this issue and let us know.  Thanks.

**Comment by NMuravlyannikov** [comment]
Replied in a different thread, will add by end of this week.

Regards,

Nikolay Muravlyannikov,
Principal Program Manager, Microsoft
Email: nmurav@microsoft.com<mailto:nmurav@microsoft.com>, phone: +1 (425) 538-23-01

**Comment by Reeced40** [comment]
@CarolynRowe

**Comment by CarolynRowe** [comment]
Reminder to @nikolay:  Are you OK with this change?

**Comment by CarolynRowe** [comment]
Wrong Nikolay.  Sorry.  @NMuravlyannikov

**Comment by scanum** [comment]
@NMuravlyannikov Hi Nikolay, following up on this issue. Thanks!

**Comment by NMuravlyannikov** [comment]
I added Oracle using a different case

**Comment by NMuravlyannikov** [comment]
We can close this one

**Comment by CarolynRowe** [comment]
Closing...
