### ISSUE TITLE
Can't invite from Teams with AAD “Admins and users in the guest inviter role can invite” enabled

### ISSUE THREAD

**Issue by HandyAndyOnGitHub** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2312]
My experience in attempting to add an external Guest user to a Microsoft Team has been confusing.  

I am a Global Admin and the Team Owner, but I could not add the external Guest to the Team from the Team "Add Members" interface using the methods detailed in this documentation.  Instead I received the "We didn't find any matches" error while trying to add a Guest from the Teams interface.  

Points to note:
(1) I have the Azure AD option “Admins and users in the guest inviter role can invite” is enabled to provide control around Guest access. This setting is found in Azure Active Directory &gt; Users &gt; User Settings &gt; External Users Manage external collaboration settings &gt; “Admins and users in the guest inviter role can invite”.
(2) I had already added my Guest as a Guest user in Azure AD.
(3) I am a Global Admin and the Team Owner (mentioned previously).

The only way I have found to add an external Guest (with “Admins and users in the guest inviter role can invite” enabled) is from the Teams Admin Portal &gt; Teams &gt; Select the relevant Team &gt;  Team Members &gt; Add members.  

Please consider updating content on this page and throughout this Guest Access section of documentation to clarify the situation when “Admins and users in the guest inviter role can invite” is enabled.

Kind regards
Andy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93906e31-cd28-702d-bb7e-fcc2529df363
* Version Independent ID: afe4d6ed-cdcb-77e0-0951-f3c69e2463e1
* Content: [Add a guest to a team](https://docs.microsoft.com/en-us/microsoftteams/add-guests#feedback)
* Content Source: [Teams/add-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/add-guests.md)
* Service: **msteams**
* GitHub Login: @somakbhattacharyya
* Microsoft Alias: **sbhatta**

**Comment by HandyAndyOnGitHub** [comment]
... basically the text on this page "Global admins who are owners of a team and owners of a team can add a guest to a team through either the Microsoft Teams desktop or the web clients" is not correct when AAD>"Admins and users in the guest inviter role can invite” is enabled.

**Comment by scanum** [comment]
@HandyAndyOnGitHub thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@HandyAndyOnGitHub Thank you for your feedback, I will have it sorted soonest.

**Comment by Xander99** [comment]
I am also experiencing this issue. It's actually become a blocker in our company moving from Slack to Teams as we collaborate quite heavily with 3rd Parties using our Slack setup.
Hope this is fixed soon!

**Comment by Reeced40** [comment]
@Xander99 Thank you for letting me know.  I'm still investigating with the team and will keep you posted on developments.

**Comment by Reeced40** [comment]
@HandyAndyOnGitHub I will add a note with regards to your second comment thank you.  The original issue at the top - are you referring to this article or a link in this article.  Please could you be a bit more specific so I can add clarification to the doc.  Thanks in advance.

**Comment by HandyAndyOnGitHub** [comment]
@Reeced40 I'm referring to this article.  What I'm saying is that due to a bug/feature in the code the article is not correct under the conditions that I've described.  Without fixing the code, the text on this page could note the odd behaviour until such time as the code is corrected :)

**Comment by scanum** [comment]
@HandyAndyOnGitHub thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
