### ISSUE TITLE
Basic features not supported

### ISSUE THREAD

**Issue by arnileibovits** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2314]
Basic things that worked in Skype for Business or now missing from Teams. How do I create group chats with external users? How do I share my screen? This is useless!

**Comment by scanum** [comment]
@arnileibovits thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
