### ISSUE TITLE
email SMTP domain

### ISSUE THREAD

**Issue by bayesfactor** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2315]
How do we whitelist SMTP domains? I see an option to do so in the admin portal called "Accept channel email from these SMTP domains", but I cannot enter a value in that text form and save it. Why not? How do I use that feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9b7f77-061d-a224-ff1c-8d3e15d21221
* Version Independent ID: 00fa9550-c4c4-3398-ffbb-271cc724048f
* Content: [Manage Microsoft Teams settings for your organization](https://docs.microsoft.com/en-US/microsoftteams/enable-features-office-365?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/enable-features-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enable-features-office-365.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by bayesfactor** [comment]
Here is an example screenshot. I can enter text into that field but I can't save the change. If I refresh the page, the text in the SMTP domain field is cleared.

![image](https://user-images.githubusercontent.com/16023856/58192535-c9319b00-7c75-11e9-8ee2-63cb2c75bf26.png)

**Comment by scanum** [comment]
@bayesfactor thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
