### ISSUE TITLE
ACPInfo

### ISSUE THREAD

**Issue by b-bagley** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2316]
This line doesn't seem to be working for me: $users =  $allUsersInTenant | ?{$_.AcpInfo -ne $null -and $_.ACPInfo.Name -eq $ACPProviderName}

It doesn't seem to pull in the info from the ACPInfo details of users.  I've verified that I'm getting that data from get-csonlineuser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d1ccd4c-9662-11f6-7227-24d104af8796
* Version Independent ID: 1e1843b6-9bf8-1226-f33a-589eb4b38f1e
* Content: [Assign Microsoft as the audio conferencing provider](https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/assign-microsoft-as-the-audio-conferencing-provider#feedback)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/assign-microsoft-as-the-audio-conferencing-provider.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/assign-microsoft-as-the-audio-conferencing-provider.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@b-bagley @ Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@b-bagley thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
