### ISSUE TITLE
Getting the correct image of Windows 10 using the new licence scheme

### ISSUE THREAD

**Issue by DavidBovine** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2318]
"A specific version of Windows 10 is required, and this version is only available to volume licensing customers. You can get a copy from the Volume Licensing Service Center."

How is this affected by the move toward licensing Windows Enterprise as a 356 licence? I have an Windows Enterprise E3 licence that I purchased for this system but I'm not sure how I can apply it in this scenario. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console](https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/console#feedback)
* Content Source: [Teams/room-systems/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/console.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by jambirk** [comment]
@sohailta, please address this question.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@sohailta any updates? Thanks!

**Comment by scanum** [comment]
@DavidBovine A message from @sohailta - Some NUC miniPC supports CEC and provides a BIOS setting to enable it. Unfortunately they cannot be controlled by application SW, therefore is not very useful. You may want to consider some external pass through device like the one below, if you intend to use CEC for your system.
https://www.extron.com/article/hdctl100ad

**Comment by scanum** [comment]
@DavidBovine Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
