### ISSUE TITLE
Teams users talking to Skype consumer users not working.

### ISSUE THREAD

**Issue by carrillo-dot-cz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2319]
MS Support confirmed that "Unfortunately, communicating from Teams to a Regular Skype is not yet available. "  - 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31588a25-f3ee-e888-aa67-203be3d34489
* Version Independent ID: 3b498bcf-69a9-01ac-973a-4d5dbeea587c
* Content: [Manage external access (federation) in Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/manage-external-access?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@carrillo-dot-cz Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by msbemba** [comment]
@carrillo-dot-cz Thank you for your feedback. This feature is not available yet, however it is under review and if you like the idea you can up-vote at https://microsoftteams.uservoice.com/forums/555103-public/suggestions/16958347-skype-integration-consumer-federation

Hope this helps!

Regards
Sriraman

**Comment by scanum** [comment]
@carrillo-dot-cz Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
