### ISSUE TITLE
"Drained"

### ISSUE THREAD

**Issue by TobieFysh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2326]
please remove the word "drained"

This command does not drain CCE. All calls in progress going via the device are dropped. The following line is factually incorrect: "The appliance is "drained"—that is, all existing calls will complete, but new calls are rejected."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 857063c3-e4d2-fd72-6643-8a4ecda0112e
* Version Independent ID: 446736cd-9690-53d7-a71d-ef668b39f136
* Content: [Enter-CcUpdate](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/enter-ccupdate)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/enter-ccupdate.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/enter-ccupdate.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@TobieFysh Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by msbemba** [comment]
@TobieFysh Thank you for your feedback. We have made changes to the description via PR https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/2352

**Comment by scanum** [comment]
@TobieFysh Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
