### ISSUE TITLE
Update Web Browser Support

### ISSUE THREAD

**Issue by d1bjo0** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2327]
Please update web browser support & functionality, its not explicit enough. Example: Edge (RS2+) doesn't support desktop share. Can send/receive A/V, .   Chrome supports desktop share but not sending video in a p2p call, but it does support video in a meeting.  There needs to be better definition of supported features in the two primary modes: calling & meetings. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/get-clients#feedback)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@d1bjo0 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@d1bjo0 Thank you for reaching out in helping improve MS Docs. Are you suggesting that we add the information that you supplied, or is there more information necessary?

**Comment by d1bjo0** [comment]
I would say better define the scope of what works with what browser.  For instance  calling, video, desktop sharing, ppt sharing, whiteboarding, app sharing, remote control.  This for both 1:1 and for meetings.  The different browsers each support different features.

Thanks,

Bruce

**Comment by Reeced40** [comment]
@d1bjo0 Thank you, I will get this over to the team.

**Comment by LolaJacobsen** [comment]
@voltarone @juturu please review and let me know what additional details you'd like to add to the Browser-support table under Web clients.

**Comment by scanum** [comment]
@juturu @voltarone any updates on this? Thanks

**Comment by scanum** [comment]
@juturu @voltarone any updates on this? Thanks

**Comment by LolaJacobsen** [comment]
PM Neeraj Jain will look at it.

**Comment by scanum** [comment]
@LolaJacobsen Any updates on this? Thanks!

**Comment by LolaJacobsen** [comment]
Ping'd PM Neeraj Jain again today.

**Comment by LolaJacobsen** [comment]
I got the full details on browser support from the PM. I'll be updating the content later this week.
