### ISSUE TITLE
Broken Link in Document

### ISSUE THREAD

**Issue by tracyb1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2328]
Can someone fix the broken link under Success Story - "Aruba Networks saves $2 Million dollars by cutting the cord" ..." or provide access to this document? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dc1b48-2589-d3b2-f45a-61968e7aa096
* Version Independent ID: 9895310d-c8ba-15f8-7942-b0ab47ebe058
* Content: [Planning for Optimal Skype for Business Experience over Wi-Fi](https://docs.microsoft.com/en-us/skypeforbusiness/certification/plan-wifi#feedback)
* Content Source: [Skype/SfbPartnerCertification/certification/plan-wifi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbPartnerCertification/certification/plan-wifi.md)
* Service: **skype-for-business**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@tracyb1 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by tracyb1** [comment]
Thank you Manuela!

**Comment by Jcoetsee** [comment]
Hi there @tracyb1 can you check the following external link and confirm if this is the document you are talking about. it appears this is the case study/story in question.

https://www.arubanetworks.com/assets/cs/CS_WCU.pdf

**Comment by tracyb1** [comment]
Thank you JC.  Unfortunately, this is not the document I'm referring to. The document title is "Aruba Networks saves $2 million dollars by "cutting the cord" and moving to an all wireless Skype for Business unified communications platform."  It is referenced at docs.microsoft.com in the following document https://docs.microsoft.com/en-us/skypeforbusiness/certification/plan-wifi#feedback<https://t.sidekickopen75.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPdSD1CW1qwc2q2zGr7TLxT-LQF4Sl103?t=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fskypeforbusiness%2Fcertification%2Fplan-wifi%23feedback&si=8000000000438822&pi=d5502f49-adba-4361-93dd-efadddfccfd8>. Also see the google search for this document below. Are you able to locate this for me? Thanks so much!



[cid:image004.png@01D509C3.B6EB8A20]

**Comment by Jcoetsee** [comment]
@tracyb1 Hi there I actually changed the link but it appears like it still had the old one. is it this link perhaps?

https://www.scansourcecommunications.com/~/media/communications-us/brands/microsoft-lync/aruba-casestudy-lync-2015.pdf

**Comment by tracyb1** [comment]
Yes.. this is the link. Thank you so much JC! 😉 Are you able to put this case study back on customers.microsoft.com<https://t.sidekickopen75.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPdSD1CW1qwc2q2zGr7TLxT-LQF4Sl103?t=https%3A%2F%2Fdoc.microsoft.com&si=8000000000438822&pi=3ddb7c1f-8686-4632-af70-ecb1d874c738> for another few weeks? I am a Microsoft Partner and I have a Microsoft client who wants to see this case study back on customers.microsoft.com so she can see it within the parameters of the customers.microsoft.com format.

Thanks so much,

Tracy

**Comment by Jcoetsee** [comment]
@tracyb1 I will put in the request to have it changed on the original article yes

**Comment by tracyb1** [comment]
Thank you so much JC 😊 !!
