### ISSUE TITLE
Incorrect Descriptions of URI Types

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#233]
The descriptions are incorrect:
0 = User URI
1 = Phone URI

Kindly check and let me know if I am correct. I can submit a PR if confirmed.

--

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 404edb8b-aaf7-23af-ad56-f5e1aeb80121
* Version Independent ID: 2cd376ca-cb29-0604-cd8c-2a96f714545d
* Content: [UriTypes table](https://docs.microsoft.com/en-us/skypeforbusiness/schema-reference/call-detail-recording-cdr-database-schema/uritypes)
* Content Source: [Skype/SfbServer/schema-reference/call-detail-recording-cdr-database-schema/uritypes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/schema-reference/call-detail-recording-cdr-database-schema/uritypes.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by jambirk** [comment]
Verified the necessary changes, publishing  later today

**Comment by nsshommo** [comment]
Thanks. :)

**Comment by jambirk** [comment]
fixed as part of 
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/pull/1046#issuecomment-394461962
