### ISSUE TITLE
Documentation calling plans not complete

### ISSUE THREAD

**Issue by Vleugelsjef** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2332]
In the documentation there are only two options: domestic calling plan (12$) and international calling plan (24$). In the Netherlands and Belgium there are four options: domestic calling plan (120 minutes) ; domestic calling plan (240 minutes); domestic calling plan (1200 minutes); domestic and international calling plan. 
![image](https://user-images.githubusercontent.com/50658846/58459763-6e43ec00-812c-11e9-84db-5dc8bd2d6e6d.png)
see on https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-netherlands

**Comment by scanum** [comment]
@Vleugelsjef hank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by msbemba** [comment]
@Vleugelsjef Thank you for your feedback. Could you please provide us the original document that you are referring to where the information is incomplete or incorrect?

**Comment by Vleugelsjef** [comment]
Hi @msbemba I was looking at different sources: not all contains the same information:
https://docs.microsoft.com/en-us/microsoftteams/calling-plans-for-office-365 (only two)
https://docs.microsoft.com/en-us/microsoftteams/calling-plan-landing-page 
https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-and-microsoft-teams-add-on-licensing/assign-skype-for-business-and-microsoft-teams-licenses (only referring two types MCOPSTN1 and 2)

**Comment by msbemba** [comment]
@Vleugelsjef Thank you for your feedback. 

The first two links provide information about the different calling plans available and doesnt not go deep into the options within the calling plan. So I think it is Ok to leave those as it is , however the third link with SKU has been updated via PR https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/2401

**Comment by tonysmit** [comment]
@msmikedavis - Can you confirm that there are four calling plan options in the Netherland? See the first entry here. Thanks, Tony

**Comment by msmikedavis** [comment]
Yes

**Comment by Vleugelsjef** [comment]
Thank you @msbemba. Can you also adjust the following place: https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/licensing-service-plan-reference 
Then people can find this information on multiple places.

**Comment by scanum** [comment]
@msbemba

**Comment by msbemba** [comment]
@Vleugelsjef Thank you for the feedback and sorry about the delay.  We have added the guid and other details for MCOPSTN5 - Domestic Calling Plan (120 min calling plan) via PR  https://github.com/MicrosoftDocs/azure-docs/pull/34468
Note that MCOPSTN6 is on limited availability.

Once again thank you for making our docs look better.

Thanks
Sri

**Comment by Vleugelsjef** [comment]
You're welcome!
