### ISSUE TITLE
missing SfB 2019 info

### ISSUE THREAD

**Issue by WillemVerwijs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2333]
Hi Team I seem to miss the updates info of SfB 2019. What can I do to get that on this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4bec075-beb2-2aba-3bbb-d9b337990068
* Version Independent ID: 6eb9ba9d-413a-03e5-0a02-272ed973930d
* Content: [Skype for Business downloads and updates](https://docs.microsoft.com/en-us/skypeforbusiness/software-updates?toc=%2FSkypeForBusiness%2Ftoc.json&bc=%2FSkypeForBusiness%2Fbreadcrumb%2Ftoc.json#feedback)
* Content Source: [Skype/SfbServer/software-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/software-updates.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by jambirk** [comment]
There hasn't been a CU for SFB 2019 yet, once one is released the page will be updated to include that.

**Comment by scanum** [comment]
@WillemVerwijs Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
