### ISSUE TITLE
Will this work if the tenant is enabled for multifactor authentication?

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#234]
Will this work if the tenant is enabled for multifactor authentication? Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 263b9c6e-b581-5b51-0bce-76fa12437e4f
* Version Independent ID: be5c7725-f60d-3727-9602-c3df4957be71
* Content: [Configure a hybrid environment in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/manage/authentication/configure-a-hybrid-environment)
* Content Source: [Skype/SfbServer/manage/authentication/configure-a-hybrid-environment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/authentication/configure-a-hybrid-environment.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.
