### ISSUE TITLE
Misspelling above..

### ISSUE THREAD

**Issue by d1bjo0** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2343]
Near the top of the page it states "View and reset a conference ID assigned to a user in Microsoft Teasms."  &lt;-- Change to "Teams".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04f02841-8def-d3af-f4bf-cd92654b6364
* Version Independent ID: bf92954c-cc85-d5a7-f190-0636467a2490
* Content: [See, change, and reset a conference ID assigned to a user in Skype for Business Online](https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/see-change-and-reset-a-conference-id-assigned-to-a-user)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/see-change-and-reset-a-conference-id-assigned-to-a-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/see-change-and-reset-a-conference-id-assigned-to-a-user.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@d1bjo0 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum
