### ISSUE TITLE
Contradictory statement

### ISSUE THREAD

**Issue by alexjmoore** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2346]
The section:

"""There's no way to change the system language for only one person in your organization. You can only change the greeting language for everyone on your organization.

 Note

Users can change their own greeting language through their settings after they sign in."""

Seems to be contradictory, i.e. "there is no way", but at the same time "users can change their own"....   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5586a3f7-0a24-3720-1ad5-336737c44275
* Version Independent ID: c5800980-2d9f-ee75-4193-bc5e8e9a68b9
* Content: [Change the default language for greetings and emails](https://docs.microsoft.com/en-us/microsoftteams/change-the-default-language-for-greetings-and-emails#feedback)
* Content Source: [Teams/change-the-default-language-for-greetings-and-emails.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/change-the-default-language-for-greetings-and-emails.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@alexjmoore Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @alexjmoore 

Thank you for reporting and making the docs better. Much appreciated.

Yes, you are correct. Sentences are contradictory. 

Users can't change the language but they can change the greeting. So note has been modified accordingly. You will be able to see the changes once the PR gets merged. Thank you.

**Comment by dstrome** [comment]
The content is correct. Administrators can't change the prompt language for a single user, but users themselves can change their own prompt language by following the link in the text below the note. As a result, I've closed the PR without merging.

**Comment by alexjmoore** [comment]
Sorry, but I believe this could be made clearer.  The opening statement in question is "There's no way to change the system language for only one person in your organization." - that is factually wrong, because a user themselves can do it.  Put another way "Can a single person change their system language?"...the answer is "yes".

**Comment by scanum** [comment]
@alexjmoore Thank you for submitting feedback. We appreciate your suggestions, we will take these into consideration for future updating of these docs. 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by JorgeALeitao** [comment]
I must agree with @alexjmoore  the way the the article is write is confusing.
I suggest we reopen this and find a way to make it clear.  

One one the sources of confusion is - mixing two different concepts in a single statement
There's no way to change the **system** language for only one person in your organization. You can only change the **greeting** language for everyone on your organization.

Changing the system language has much more profound effects than change the greeting language.

Perhaps it should read There's no way for an admin to change the **greeting** language for a single  person in an organization. An admin can only change the greeting language for everyone on your organization - **by changing the System Language which by it turns adjust the Greeting Language**
