### ISSUE TITLE
Copy image from App to Outlook

### ISSUE THREAD

**Issue by SDmorgan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2358]
Trying to copy image from Teams to Outlook. 

To reproduce. 

Image sent in chat on Teams App. 
Click on image: image shows up in Modal
Right click and "copy image"

Open new email in Outlook App (latest version all patches applied)
Go to body of email and paste (both right click and paste or crtl v give same result)
Image appears to be posted as there is a box where the image should be; however, the image itself does not show.

Microsoft Teams Version 1.2.00.8864 (64-bit). It was last updated on 5/17/19 running on Windows 10

![image](https://user-images.githubusercontent.com/24552890/58661371-cda12800-82f5-11e9-89e6-1f41c7f34811.png)

**Comment by scanum** [comment]
@SDmorgan thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
