### ISSUE TITLE
The 'move StaffHub team' feature is not enabled for your tenant

### ISSUE THREAD

**Issue by jarrodmast** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2359]
Move-StaffHubTeam command fails with an error stating that the move feature is not enabled for our tenant?

{"error":{"code":"PreconditionFailed","message":"The 'move StaffHub team' feature is not enabled for your tenant.","details":[],"innererror":{"code":"FeatureNotEnabled"}}}

Any suggestions as to how this is to be enabled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f64dee1-c968-9d64-757e-7ca3263a4fc4
* Version Independent ID: a3157a8b-a127-0726-2ee4-8972e773a785
* Content: [Move your StaffHub teams to Shifts in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/expand-teams-across-your-org/shifts/move-staffhub-teams-to-shifts-in-teams)
* Content Source: [Teams/expand-teams-across-your-org/shifts/move-staffhub-teams-to-shifts-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/expand-teams-across-your-org/shifts/move-staffhub-teams-to-shifts-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@jarrodmast thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by tftda23** [comment]
Could you confirm the solution for this? We are also experiencing this issue.
