### ISSUE TITLE
Need to add limits for number of users in a screen share

### ISSUE THREAD

**Issue by lizvdp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2365]
Please update limits information to describe limits for adhoc screen sharing in private group chat vs screensharing in a meeting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#feedback)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@lizvdp Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @lizvdp 

Thank you for reaching out!

All users in the meeting should be able to view the screen share. As we know that the limit for number of users to join a meeting is 250, so the same would be the limit for number of users in a screen share. 

Hope this clarifies your query. Kindly confirm. Thank you.

**Comment by scanum** [comment]
@lizvdp  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
