### ISSUE TITLE
missing a letter on the attribute

### ISSUE THREAD

**Issue by CarlosFarrica** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2369]
sRTCSIP-UserEnabled

msRTCSIP-UserEnabled

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39433e8c-e9f0-3df2-0c8d-4dbd1a6ec190
* Version Independent ID: b9fd94fe-7461-bb91-92e8-0d450b12e5b1
* Content: [Lync Server 2013: Migrating Lync Online users to Lync on-premises](https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-migrating-lync-online-users-to-lync-on-premises#feedback)
* Content Source: [Lync/LyncServer/lync-server-2013-migrating-lync-online-users-to-lync-on-premises.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Lync/LyncServer/lync-server-2013-migrating-lync-online-users-to-lync-on-premises.md)
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@CarlosFarrica  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@CarlosFarrica Thank you for submitting feedback. We understand that this issue has been resolved by PR #2397.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
