### ISSUE TITLE
Can not get past "Connect the room console to the dock"

### ISSUE THREAD

**Issue by terrilllr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2370]
I am using a Surface Pro 4 and I have followed the instructions carefully several times. I have connected the Surface to two different docs to ensure it is not a doc issue. But I can't get past the dock check. Please help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console](https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/console#install-windows-10-and-the-microsoft-teams-rooms-console-app)
* Content Source: [Teams/room-systems/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/console.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@terrilllr thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close

**Comment by MatthewSBZ** [comment]
What was the resolution for this issue? 

Also using Surface 4. 
Using Microsoft Dock, dock is detecting the second screen, the finish is showing up gray.

**Comment by BongaDev** [comment]
@scanum Hi was there any solution to this problem?
