### ISSUE TITLE
Inconsistency for plan requirements between this page and the support.office.com article

### ISSUE THREAD

**Issue by Shlibidi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2371]
Hi,

For license/plan requirements to create Live Events:

-this page here says that Office 365 Enterprise E1 users can create Live Events.
-The support.office.com article about Live Events only mentions E3, E5, A3 and A5 as being required: https://support.office.com/en-us/article/get-started-with-microsoft-teams-live-events-d077fec2-a058-483e-9ab5-1494afda578a

I just submitted this feedback on the support.office.com article but, could anyone confirm if Enterprise E1 users can or cannot create Live Events in Teams? 

I'm currently troubleshooting this for an E1 user and, as far as I can tell right, it doesn't seem like E1 users can create Live Events. 
If that is the case then, this page would need to be corrected to remove the mention of E1.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-live-events/plan-for-teams-live-events#feedback)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @tonysmith
* Microsoft Alias: **tonysmit**

**Comment by tonysmit** [comment]
Checking with a PM. Please hold. :)

**Comment by tonysmit** [comment]
Yes, E1 can also be used. I've sent a request to the owner of the support.office.com article to add E1 to it. Thanks!

**Comment by Shlibidi** [comment]
Thanks tonysmit! 
You're absolutely right, this page here is correct and the issue I was dealing with my user was caused by good old propagation of the service (had just switched user's license and 24 hours later, all was working fine).
Hopefully the support.office.com article gets updated soon. I've just sent another feedback on it again.
