### ISSUE TITLE
Phone Numbers

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2373]
This says to go here: Microsoft Teams admin center &gt; Voice &gt; Phone numbers

This page doesn't exist.  Phone numbers are still in the legacy portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b755d9ae-13ac-019f-f5f4-a95b1eee2989
* Version Independent ID: f7afd8ad-e6e0-6c79-aed1-4ee87d48ba12
* Content: [Create a call queue](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue)
* Content Source: [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-call-queue.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by tonysmit** [comment]
@jambirk - there are errors on this page. Please update. @danmyhre is correct here. For WW, they need to use the Legacy portal. The Phone Numbers in TAC, isn't available. Please follow up on this.

@danmyhre - thanks for the feedback. @jambirk will make the needed changes.
