### ISSUE TITLE
Powershell

### ISSUE THREAD

**Issue by CallMeByMyName** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2376]
Hello,
How to assign phone number by Powershell ?

[Tapez vos commentaires ici]

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 69c67496-cace-f833-7cfc-dca7722fef3e
* Version Independent ID: 5a14f81c-529c-4971-5ce8-39633834d4d3
* Content: [Affectation, modification ou suppression du numéro de téléphone d’un utilisateur](https://docs.microsoft.com/fr-fr/microsoftteams/assign-change-or-remove-a-phone-number-for-a-user)
* Content Source: [Teams/assign-change-or-remove-a-phone-number-for-a-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-change-or-remove-a-phone-number-for-a-user.md)
* Service: **skype-for-business-online**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@CallMeByMyName thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close

**Comment by rramdoyal** [comment]
How to do this is the new team admin centre? We cant do it in the legacy portal now

**Comment by tonysmit** [comment]
Hey everyone. So, you are just looking for the cmdlet? If so, here it is  https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinevoiceuser?view=skype-ps

@rramdoyal - I'm checking with my PMs to see when TNM: Assigning phone numbers is going live. Please hold.

**Comment by tonysmit** [comment]
@rramdoyal - Can you explain why you can't find it in the legacy portal? Can you please be specific about your click path please?

**Comment by rramdoyal** [comment]
For me it concern ressource account

From the legacy portal it says that we should  do it on the new team admin centre

But on the new team portal when we try to add the phone number to says it's not available  but have been able to assign the phone number using powershell.
Set-csonlinevoiceapplicationinstance

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by tonysmit** [comment]
@rramdoyal are you trying to assign a phone number to an Auto Attendant or Call queue?

**Comment by rramdoyal** [comment]
Auto attendant

**Comment by tonysmit** [comment]
@rramdoyal - ok. The intital requested started out with editing a different doc (Assigning numbers topic) above. So, for auto attendants, here is the topic you need to assign phone numbers to auto attendants using Resource Accounts. We released a call routing update for AAs and CQs that now use Resource Accounts and will no long support phone numbers directly. See if this articled helps. It has the steps for using PS:  https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts
