### ISSUE TITLE
Lync mediation server  DNS high availablity issue 

### ISSUE THREAD

**Issue by DavidHuang0305** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2377]
Hi guys,

         I want to know how DNS high availablity work on lync mediation server, such as we have 2 mediation server me1 and me2, if i shut down me1, all inbound call and outbound call will go to me2 itself? or need me to refresh dns? or others?  If me1 doesnt be shut down but it cant be connected, will DNS high availablity work?

**Comment by scanum** [comment]
@DavidHuang0305 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
