### ISSUE TITLE
Port out process for other countries

### ISSUE THREAD

**Issue by brucelaing** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2378]
The section "Can you transfer or port out numbers?" relates to setting a PIN Code which only relates to numbers held within the United States. This should be expanded to the other regions that you allow transfers from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a17293e0-4c49-0e97-d5da-b48322f10928
* Version Independent ID: c38c0726-5dec-d374-6948-2188d43025ef
* Content: [Transferring phone numbers common questions](https://docs.microsoft.com/en-us/microsoftteams/transferring-phone-numbers-common-questions#feedback)
* Content Source: [Teams/transferring-phone-numbers-common-questions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/transferring-phone-numbers-common-questions.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@brucelaing Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by tonysmit** [comment]
@brucelaing - you will need to submit a request to UserVoice (https://microsoftteams.uservoice.com/forums/555103-public) to add this feature. Thanks.
