### ISSUE TITLE
Do we have to upgrade at all?

### ISSUE THREAD

**Issue by Javs02** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2379]
Do we have to upgrade at all? Will this be a forced upgrade at some point? Will Teams communicate with regular Skype users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e763c267-2c3a-190d-29e2-b5c81448fc10
* Version Independent ID: 98b73595-54ea-503c-ac3c-9df176543e9e
* Content: [Upgrade Skype for Business Online to Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/upgrade-to-teams-execute-skypeforbusinessonline#feedback)
* Content Source: [Teams/upgrade-to-Teams-execute-SkypeforBusinessOnline.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-to-Teams-execute-SkypeforBusinessOnline.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Javs02 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
