### ISSUE TITLE
Global Administrator Role

### ISSUE THREAD

**Issue by paulenkelaar** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#238]
The document mentions that to assign voice services to a user, that you need to "log in to your Office 365 tenant with an account that is an Office 365 Global Administrator role".

Is this correct? I would have thought a SfB Admin role should be enough...?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 328cfd03-27e5-7756-f004-811f2dc7d2ef
* Version Independent ID: 010d16a6-1474-61ae-a55e-47f299705a74
* Content: [Configure Cloud Connector integration with your Office 365 tenant](https://docs.microsoft.com/en-au/skypeforbusiness/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/configure-cloud-connector-integration-with-your-office-365-tenant)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/configure-cloud-connector-integration-with-your-office-365-tenant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/configure-cloud-connector-integration-with-your-office-365-tenant.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by kenwith** [comment]
@paulenkelaar - thank you for this question and feedback and sorry about the long delay. I am confirming this as it does seem logical that SfB Admin role should be enough but I am finding other documentation that also states Global Admin is required. I am confirming with product team and will get this updated.

**Comment by kenwith** [comment]
@paulenkelaar - I was able to get ahold of the product team on this one and you are correct that the SfB Admin role should be enough. They are going to submit a Pull Request to get the documentation updated. Thank you very much for taking the time and providing feedback!
