### ISSUE TITLE
Showing "(Apps, bots, & connectors)[deploy-apps-microsoft-teams-landing-page.md]" (Markdown notation)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2384]
en-us:"https://docs.microsoft.com/en-us/microsoftteams/enable-features-office-365"
 "(Apps, bots, & connectors)[deploy-apps-microsoft-teams-landing-page.md]"

ja-jp:"https://docs.microsoft.com/ja-jp/microsoftteams/enable-features-office-365"
 "(アプリ、ボット、およびコネクタ) [deploy-apps-microsoft-teams-landing-page.md] "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9b7f77-061d-a224-ff1c-8d3e15d21221
* Version Independent ID: 00fa9550-c4c4-3398-ffbb-271cc724048f
* Content: [Manage Microsoft Teams settings for your organization](https://docs.microsoft.com/en-us/microsoftteams/enable-features-office-365)
* Content Source: [Teams/enable-features-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enable-features-office-365.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by OfficeGlobal** [comment]
Duplicated #1894

**Comment by scanum** [comment]
@hyoshioka0128 Since this is a duplicated issue and a solution has been implemented and just waiting to be approved I am going to go ahead and close this issue. 

Thanks,

Manuela

**Comment by scanum** [comment]
@officedocsbot close
