### ISSUE TITLE
Modern Authentication

### ISSUE THREAD

**Issue by luciodj** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2385]
In the section above "Authentication Requirements", it is suggested that the user should have "Modern Authentication" enabled, yet the link provided to the Identity Models and Authentication in Microsoft Teams"  does not mention any such option...
I am Mac user of Outlook 365 and Teams and I have only Skype and Webex showing as meeting options when I create a meeting event in teh calendar... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Use the Microsoft Teams Meeting add-in in Outlook](https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook#feedback)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@luciodj Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hello @luciodj 

Thanks for reaching out!

As per the following document, "Every organization that uses Microsoft Teams already has modern authentication—the app has been delivered with modern authentication hard-wired into it, and it should be able to recognize your credentials as linked to your Office 365 account. If you're not able to complete the sign in process, there might be something wrong with your domain or your company's Office 365 account. Your IT admin or sysadmin will be your point person in terms of resolving the issue, so get in touch with them to get more information and next steps."

https://support.office.com/article/why-am-i-having-trouble-signing-in-to-microsoft-teams-a02f683b-61a3-4008-9447-ee60c5593b0f

https://docs.microsoft.com/microsoftteams/sign-in-teams#mac-users

Hope this clarifies your query. Kindly confirm. Thank you.

**Comment by luciodj** [comment]
Thanks for the clarification, 
Then I am not sure why my Office 365 (Outlook) does not recognise my Teams tool and add it to the menu bar when creating a new meeting event on the calendar?
According to the instructions this should happen automatically as it has added automatically the link to One Note, Skype for business and Webex:




As you can see, no Teams option… 

Any suggestions???

Thanks in advance
	Lucio

**Comment by scanum** [comment]
@luciodj thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
