### ISSUE TITLE
Resource acounts vs Groups

### ISSUE THREAD

**Issue by Alex-igloo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2388]
Have you noticed you can now have both a AUS@x.com resource group and a AUS@x.com resource account? this scares the living crap out of me how is email routed? what's the differentiator? in SfB online you could assign a service number to a resource group. Naming wise this makes sense why did you change it other than to charge for a license?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams](https://docs.microsoft.com/en-US/microsoftteams/manage-resource-accounts?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@Alex-igloo thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
