### ISSUE TITLE
Years might not be correct...

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2391]
[Enter feedback here]
When looking for the versions and the dates behind them, I get a feeling that something might be wrong:
4.0.85.0 (04/8/2018)  << Correct year ?
4.0.78.0 (03/14/2018)  << Correct year ?
4.0.76.0 (03/04/2019)
4.0.64.0 (12/14/2018)

I believe the latest two are from 2019 not 2018.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1365f9b8-001c-daa7-592e-d88b9bb3a10e
* Version Independent ID: ffba1b4d-1f19-4dac-0b55-053d98fe26b7
* Content: [Release notes](https://docs.microsoft.com/en-gb/MicrosoftTeams/room-systems/srs2-release-note)
* Content Source: [Teams/room-systems/srs2-release-note.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/srs2-release-note.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum
