### ISSUE TITLE
Conditional Access web tabs in Teams Desktop.

### ISSUE THREAD

**Issue by DavidLHannah** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2395]
Can anybody else validate a workaround?

From the Conditional Access policy, under Access Control, under Grant enable the Grant Access radio button but do not check any of the required controls. In the Session controls area, enable Use Conditional Access App Control and select Use Custom Policy. You can then create a policy in Office 365 Cloud App Security to do evaluations that fail when using Conditional Access required controls. For instance verifying domain membership.

_Originally posted by @DavidLHannah in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/1557#issuecomment-499317991_

**Comment by scanum** [comment]
@DavidLHannah thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
