### ISSUE TITLE
Account never signs in - Teams Room System

### ISSUE THREAD

**Issue by KosslowK** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2398]
I was able to follow all the directions for the account, including testing logging into the Teams app via the portal and I'm able to see the calendar entry on the console, however the "signing in..." never seems to disappear.

**Comment by scanum** [comment]
@KosslowK thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
