### ISSUE TITLE
ALLUSER=1 -> ALLUSERS=1

### ISSUE THREAD

**Issue by ueda123** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2402]
Make sure that the command is correct.
I think that "S" is missing.

msiexec /i &lt;path_to_msi&gt; /l*v &lt;install_logfile_name&gt; ALLUSER=1
↓
msiexec /i &lt;path_to_msi&gt; /l*v &lt;install_logfile_name&gt; ALLUSERS=1

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [仮想デスクトップ インフラストラクチャ用の Teams](https://docs.microsoft.com/ja-jp/microsoftteams/teams-for-vdi#feedback)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ueda123 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@OfficeGlobal

**Comment by OfficeGlobal** [comment]
potencial source issue: https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi

![image](https://user-images.githubusercontent.com/47977325/60660346-e3a38a80-9e57-11e9-8d86-f92e2091ecc2.png)

Once the source updated, we'll update INTL

**Comment by lindspea** [comment]
Done. Thanks @OfficeGlobal

**Comment by LolaJacobsen** [comment]
NO - it's "ALLUSER." I just fixed this the other day per the PM.
