### ISSUE TITLE
Device-specific considerations not mentioned

### ISSUE THREAD

**Issue by banzaisi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2404]
Include a section for device-specific consideration as well. Or mention Meeting Room devices that won’t support Teams need to be replaced with supporting devices OR to get update from vendor on such devices to support teams, before moving to teamsonly mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a2fc46c-d6fb-fd8b-e2aa-fdee7c742230
* Version Independent ID: e0d36a99-2823-68a2-7e97-0c1ba66efd51
* Content: [Teams Only mode considerations](https://docs.microsoft.com/en-us/microsoftteams/teams-only-mode-considerations)
* Content Source: [Teams/teams-only-mode-considerations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-only-mode-considerations.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@banzaisi Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@banzaisi Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
