### ISSUE TITLE
Can you please confirm, whether all existing private Teams are automatically discoverable after this feature launch?

### ISSUE THREAD

**Issue by gurubn** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2405]
Can you please confirm, whether all existing private Teams are automatically discoverable after this feature launch?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5920152-5fee-41ed-56df-ad7b51b25cc2
* Version Independent ID: 88cfc850-5e36-48ee-ba99-088b2b653f1e
* Content: [Manage discovery of private teams in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-discovery-of-private-teams)
* Content Source: [Teams/manage-discovery-of-private-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-discovery-of-private-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@gurubn Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by edhans** [comment]
So I guess the "Team Code" section in Team Settings goes away with the new Team Discovery" section? We still have the Team Code section. Looking forward to this new method for allowing people to discover private teams.

**Comment by scanum** [comment]
@gurubn thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
