### ISSUE TITLE
License requirements for Authenticated Attendees

### ISSUE THREAD

**Issue by NickElniff** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2407]
The Licensing requirements should include Authenticated Attendees.

“For Organizer, Producer, Event Team member, and authenticated attendees, an Office 365 license is required”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events#feedback)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @tonysmith
* Microsoft Alias: **tonysmit**

**Comment by tonysmit** [comment]
@sonu-arora - can you confirm please?

**Comment by tonysmit** [comment]
@scanum - once Sonu replies, looks like a quick fix.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@sonu-arora Hi! Any updates on this? thanks

**Comment by tonysmit** [comment]
Pinged her in Teams.

**Comment by scanum** [comment]
@tonysmit Any response from Sonu? Thanks!!

**Comment by tonysmit** [comment]
No, I will send her an email again.

**Comment by sonu-arora** [comment]
I thought I already responded to this.  Authenticated attendees do require Teams license.

**Comment by scanum** [comment]
@NickElniff Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
