### ISSUE TITLE
Ambiguity about Polycom Trio

### ISSUE THREAD

**Issue by rgsteele** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2408]
The Polycom Trio is listed twice on this page: once under "Conference phones" as "RealPresence Trio 8800", and again under "Desk phones" as "Trio Series 8800/8500 IP Phone" with a different version and qualification date. 

Both the Trio 8500 and Trio 8800 (also known as the RealPresence Trio 8500 and RealPresence Trio 8800 [1]) should be listed under conference phones, not desk phones, and the correct supported firmware needs to be confirmed.

[1] Per https://documents.polycom.com/bundle/trio-sfb-ug-5-9-0-AA/page/c1435771.html, "The Polycom Trio 8500 and Polycom Trio 8800 systems... are also known as Polycom RealPresence Trio 8500 system [and] Polycom RealPresence Trio [8800] system".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcc58c9c-b20c-0515-55e6-165f23a66dbf
* Version Independent ID: e76e89bc-2e4b-af6f-5518-84435bca70ea
* Content: [Phones and Devices for Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/certification/devices-ip-phones)
* Content Source: [Skype/SfbPartnerCertification/certification/devices-ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbPartnerCertification/certification/devices-ip-phones.md)
* Service: **skype-for-business**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@rgsteele Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by TokyoScarab** [comment]
@rgsteele Thank you for bringing this up.  I will be looking into this issue and updating the documentation accordingly, thanks!

**Comment by rgsteele** [comment]
This was already fixed by @dianavank: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/f7342f80bf5d37694c3a6ea38befdad8ef0c947d#diff-700007bea724da9f70a26ab28e5b22c7

**Comment by TokyoScarab** [comment]
@rgsteele Yea, I noticed this once I started looking into it.  Thanks for commenting though!

**Comment by scanum** [comment]
@rgsteele Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
