### ISSUE TITLE
The VTC conference id.

### ISSUE THREAD

**Issue by poxiaosyb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2411]
what is the formate of VTC id? for example?

**Comment by scanum** [comment]
@poxiaosyb Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@poxiaosyb thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
