### ISSUE TITLE
Notifications showing in account selector, when none are unread

### ISSUE THREAD

**Issue by richardacre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2422]
I have two Teams accounts, both use my online AD account as the login email address, the account drop-down in the top right often (most of the time) shows a red circle with a number in, presumably the number of unread items it thinks is in one (or both? or the other?) account(s), but on using the dropdown and switching to the other account I can see no notifications, and nothing unread in Activity.

**Comment by scanum** [comment]
@richardacre thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close

**Comment by richardacre** [comment]
I don't understand, that page asks me for a country then gives me a phone number, where do I report the bug?
