### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by mth11** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2423]
Published on 05/20/2019 and as of 6/11/2019 broken link....  
To get the latest updates and most up-to-date information on supported devices, see the Skype for Business Device Catalog.
end of first paragraph, Please fix, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d90a8756-a729-a39b-518e-62d3c147d2c2
* Version Independent ID: e1f1ceb1-5dbe-8e3a-3cd5-d978c504d96d
* Content: [Getting phones for Skype for Business Online](https://docs.microsoft.com/en-us/SkypeForBusiness/what-is-phone-system-in-office-365/getting-phones-for-skype-for-business-online/getting-phones-for-skype-for-business-online?redirectSourcePath=%252fen-us%252farticle%252fGetting-phones-for-Skype-for-Business-Online-91f2d947-45fc-4fab-bd8b-2e313531c477#feedback)
* Content Source: [Skype/SfbOnline/what-is-phone-system-in-office-365/getting-phones-for-skype-for-business-online/getting-phones-for-skype-for-business-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/what-is-phone-system-in-office-365/getting-phones-for-skype-for-business-online/getting-phones-for-skype-for-business-online.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@mth11 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by TokyoScarab** [comment]
@mth11 Thank you for pointing this out! I will update the link to point to where it is supposed to.

**Comment by scanum** [comment]
@mth11 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
