### ISSUE TITLE
The German MT translation for this article is really poor.

### ISSUE THREAD

**Issue by ilocit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2427]
I wanted to help and "Edit" as it was suggested in the "note" that popped up at the top. But I don't see an Edit pencil on my page!

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 56ab9d91-d5c4-be13-660e-10b1fdacadec
* Version Independent ID: efdd6696-1415-26ae-ab56-5e758a34311c
* Content: [Upgrade-Checkliste](https://docs.microsoft.com/de-DE/microsoftteams/upgrade-basic?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/upgrade-basic.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-basic.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ilocit Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum
@officedocsbot assign @Officeglobal

**Comment by scanum** [comment]
Hi @officeglobal, could you please aid with this ticket? Thanks!

**Comment by OfficeGlobal** [comment]
We're working on a fix (Bug 3423072)

**Comment by OfficeGlobal** [comment]
@ilocit , @scanum article has been HumanTranslated and published live

**Comment by scanum** [comment]
@ilocit Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
