### ISSUE TITLE
Invite device to meeting

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2433]
How do you setup Teams so you can invite a Room to a meeting and have the invite show up on the device? Do you have to use the Legacy Skype portal to set this up or PowerShell?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae4c265a-8df4-647d-fc42-5054e3340c20
* Version Independent ID: 249c7301-9c82-b1c4-8401-54553370302b
* Content: [Phones for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/phones-for-teams)
* Content Source: [Teams/phones-for-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phones-for-teams.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@eschrader thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by jambirk** [comment]
If your room is equipped with just a phone the behavior will be different from a room equipped with a room system, and that really sounds like what you're expecting. Setting up a room system is documented at aka.ms/MTRDocs and it does involve setting up an account for the device.
