### ISSUE TITLE
Need clarification

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#244]
The article describes the procedures for an old product. "Lync" as a product name has been outdated for years now and installing the plugin to a local PC seems not to enable Skype for business via office 365 to use audio and/or video.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 515a2310-9d3d-d056-0996-dea9c9427d12
* Version Independent ID: eb81761a-d223-7849-855e-2b8ec9140f9a
* Content: [Deploy the Lync VDI plug-in with Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/deploy-the-lync-vdi-plug-in)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/deploy-the-lync-vdi-plug-in.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/deploy-the-lync-vdi-plug-in.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
So far as we've been informed, the VDI plugin originally produced for Lync 2013 is still available and works with either Skype for Business Server 2015 or Lync Server 2013. The plugin predates the name change and was named the Lync VDI plugin, and was never officially rebranded.
