### ISSUE TITLE
(En)Force enable Teams to auto-start whenever the user logs in

### ISSUE THREAD

**Issue by SCCMAdmin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2440]
Hi Team, your page does not show admins how to control the auto-start setting ongoing. Scenario is the enterprise wants to enforce auto-start beyond/after the first launch as described in normal behavior. Currently after the normal behavior the customer can uncheck "Auto-start application" and essentially stop signing in. We want this uncheck ability to be locked (by GPO ideally or Registry key) so the checkbox stays checked on and customers are always being signed into Teams. Microsoft wants the take up of Teams right?

It would be ideal to control the other checkboxes too, all four of them:
1. Auto-start application - needed to encourage use.
2. Open application in background - needed to stop a full screen annoyance on logon.
3. On close, keep the application running - needed to encourage use.
4. Register Teams as the chat app for Office - needed to move off S4B.

None of this is addressed on this web page and we really do need to know the answers to these important configuration steps. Please provide some steps whilst the page is being updated OR get them into the page... even if it is to mention a future update will handle configuration options such as... etc. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Microsoft Teams using MSI via SCCM](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment#deployment-procedure-recommended)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@SCCMAdmin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by TokyoScarab** [comment]
@SCCMAdmin Thank you for bringing this to our attention.  These sound like some amazing suggestions.  If you would like, you can submit them to the [Microsoft Teams Uservoice](https://microsoftteams.uservoice.com) where they can be seen and potentially added in the future.  For more specific help with the questions you posted, a detailed and fast response can be given by going through [Microsoft Support](https://support.microsoft.com).  If you hear information back from them that would be beneficial in updating the current documentation, please post it down below and we can work more on the issue.

**Comment by scanum** [comment]
@SCCMAdmin Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
