### ISSUE TITLE
There is no "Team discovery" option in the settings

### ISSUE THREAD

**Issue by wy62** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2444]
I don't see the "Team discovery" section in the settings for any of my Teams. Why might this be?

Are non-discoverable private Teams actually even a thing? This article seems to suggest it is. I understand this was going to be rolled out as the default for private Teams but the roll out was cancelled (MC129787 in the Message Center).

In our tenant when I search for a private Team that exists it does not find it, which tells me private Teams are not discoverable by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5920152-5fee-41ed-56df-ad7b51b25cc2
* Version Independent ID: 88cfc850-5e36-48ee-ba99-088b2b653f1e
* Content: [Manage discovery of private teams in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-discovery-of-private-teams#feedback)
* Content Source: [Teams/manage-discovery-of-private-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-discovery-of-private-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@wy62 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by effyl01** [comment]
with our tenant its the same as in @wy62 tenant - the "Team discovery" is missing at the teams -> settings.
The article is mentioned as "This is a preview or early release feature". Will it help if I'll contact the support? can they just activate this feature?

**Comment by shashanksrivastava8184** [comment]
Same problem in our tenant. Do we know the solution ?

**Comment by shashanksrivastava8184** [comment]
@wy62 : Did it get resolve for you ?

**Comment by wy62** [comment]
> @wy62 : Did it get resolve for you ?

@shashanksrivastava8184 Nope, I still don't see the "Team Discovery" section in the settings of any of my teams.

**Comment by scporse** [comment]
Also missing the Team Discovery setting...

**Comment by Naz9mm** [comment]
im also missing this feature!

**Comment by mymebenha** [comment]
I'm also missing this feature.

**Comment by Naz9mm** [comment]
You need to update this setting under search by name from >Org wide Settinggs>Teams Settings

[cid:image001.png@01D5B689.98471DF0]

Thanks

Naz Momoniat  ::  Infrastructure Technician
t. 01675 466 477  ::   [image] <https://twitter.com/thinkcrimson>   [LinkedIn] <https://www.linkedin.com/company/crimson>   [image] <https://www.youtube.com/thinkcrimson>   [Facebook] <https://www.facebook.com/crimsonuk/>    ::  www.crimson.co.uk

[image]<https://www.crimson.co.uk/>
