### ISSUE TITLE
Does not provide information on how to resolve number in pending mode

### ISSUE THREAD

**Issue by eperez-eig** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2445]
If a resource account is deleted what is to be done if it is stuck in pending mode?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts#feedback)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@eperez-eig thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
