### ISSUE TITLE
Broken link for the Logitech SmartDock

### ISSUE THREAD

**Issue by kelemvor33** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2447]
This link doesn't work: https://partnersolutions.skypeforbusiness.com/solutionscatalog/all/logitech-smart-dock

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf01435-a73b-4bf2-5845-e4cf50c4c3a2
* Version Independent ID: 166e1800-80b1-2496-7160-3040c5b23c3d
* Content: [Microsoft Teams Rooms requirements](https://docs.microsoft.com/en-us/microsoftteams/room-systems/requirements)
* Content Source: [Teams/room-systems/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@kelemvor33 hank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by TokyoScarab** [comment]
@kelemvor33 Thank you for alerting us to this!  I have gone and made an edit to fix that link.

**Comment by scanum** [comment]
@kelemvor33 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
