### ISSUE TITLE
Script fails after downloading.

### ISSUE THREAD

**Issue by kelemvor33** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2455]
I saved the script file to C:\Temp and ran it from there.  It downloads the file just fine but then errors out with the error below.  Anyone have any suggestions on what might cause this?  When I go to the SRSv2 folder, it is empty.  I can run the MSI file manually but then it wants to install things to Program Files.

C:\temp\CreateSrsMedia.ps1 : Exception calling "Load" with "1" argument(s): "Could not find a part of the path
'C:\temp\SRSv2\Skype Room System Deployment Kit\AutoUnattend.xml'."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console](https://docs.microsoft.com/en-us/microsoftteams/room-systems/console#Reimage)
* Content Source: [Teams/room-systems/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/console.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by kelemvor33** [comment]
Disregard this.  My computer had msiexec.exe stuck running which made the Extract step not work.

**Comment by scanum** [comment]
@kelemvor33 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
