### ISSUE TITLE
I think you do not have to specify Hostedmigration url for online to onprem move.

### ISSUE THREAD

**Issue by Rajeshvadlamani** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2457]
[Enter feedback here]
This document says to use Hostedmigrationoverride and URL. It throws an error stating " did not return expected status code from request for WWW-Authenticate header". 

The move command works 100% well when you just key in online tenant creds and just Move-csuser - Identity - Target pool01.corp.xx -credential $cred

This works just as you do it from SFB CPL too where you just key in online creds only !

![Uploading image.png…]()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32e86ceb-2d6c-498d-94d8-2524bf4ea63a
* Version Independent ID: d34e5952-3188-27d6-db61-dd05087d0329
* Content: [Move users from the cloud to on premises](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/move-users-from-the-cloud-to-on-premises)
* Content Source: [Skype/SfbHybrid/hybrid/move-users-from-the-cloud-to-on-premises.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/move-users-from-the-cloud-to-on-premises.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Rajeshvadlamani Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by CarolynRowe** [comment]
The PM contact is BJ Whalen.  Please check with him.

**Comment by scanum** [comment]
@bjwhalen Hi BJ, could you please help with this issue? Thanks!

**Comment by scanum** [comment]
@bjwhalen Hi BJ, any updates on this? Thanks!

**Comment by bjwhalen** [comment]
hosted migration url is *sometimes* needed, as already called out in the content on this page.

"If the account with permissions in Office 365 does not end in “on.microsoft.com”, you must specify the -HostedMigrationOverrideUrl parameter, with the correct value as described in Required administrative credentials."

**Comment by scanum** [comment]
@Rajeshvadlamani 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
