### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Jannnie** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#246]
棒

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 72d9c2af-b933-f9a2-e189-387c881cffd0
* Version Independent ID: a614d386-7ce8-5c96-690e-b40231e67118
* Content: [Skype for Business Server 2015 的边缘服务器环境要求](https://docs.microsoft.com/zh-cn/skypeforbusiness/plan-your-deployment/edge-server-deployments/edge-environmental-requirements#feedback)
* Content Source: [Skype/SfbServer/plan-your-deployment/edge-server-deployments/edge-environmental-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.zh-CN/blob/live-sxs/Skype/SfbServer/plan-your-deployment/edge-server-deployments/edge-environmental-requirements.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by kenwith** [comment]
@Jannnie - I ran this through translate but couldn't get what the feedback is related on. I am wondering if maybe this was submitted by mistake? If you have more information please re-open this issue and we will get it over to our localization team. Thanks!
