### ISSUE TITLE
June SFB 2016 MSI update is missing in this page https://docs.microsoft.com/en-us/skypeforbusiness/sfb-client-updates

### ISSUE THREAD

**Issue by venkat-kashinathan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2460]
June SFB 2016 client MSI update is missing in this page https://docs.microsoft.com/en-us/skypeforbusiness/sfb-client-updates

**Comment by scanum** [comment]
@venkat-kashinathan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @venkat-kashinathan 
Thanks for your feedback, I created a pull request (referenced here) to add missing updates to date.
Thank you

**Comment by scanum** [comment]
@venkat-kashinathan Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
