### ISSUE TITLE
Step 7 is completely wrong

### ISSUE THREAD

**Issue by jupfeiff** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2461]
Step 7 contains 2 bad mistakes (On the next page, make sure that All applications is selected and then click Next. This setting instructs the network to look for all packets with a DSCP marking of 46, not just packets created by a specific application.):
1. this needs to be filtered down to lync.exe in order to not tag any other traffic using ports out of the range defined in step 10.
2. a QoS GPO can't instruct the network anything. All it will do is taking all traffic on the client that uses source ports out of the range from 10 and tag that traffic as defined in the policy.
The article seems to be old and for Lync 2013, but since there is no equivalent for Skype for Business Server, this is still the #1 reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e11441ac-62cb-9e72-9069-f7e61c8c02a4
* Version Independent ID: 70619c9b-aae7-277c-3d3a-35d82379f19b
* Content: [Lync Server 2013: Configuring Quality of Service policies for clients running on Windows 7 or Windows 8](https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-configuring-quality-of-service-policies-for-clients-running-on-windows-7-or-windows-8)
* Content Source: [Lync/LyncServer/lync-server-2013-configuring-quality-of-service-policies-for-clients-running-on-windows-7-or-windows-8.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Lync/LyncServer/lync-server-2013-configuring-quality-of-service-policies-for-clients-running-on-windows-7-or-windows-8.md)
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by jambirk** [comment]
that article served as a baseline for a similar procedure in https://docs.microsoft.com/en-us/MicrosoftTeams/qos-in-teams-clients -- is that also wrong?

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@jupfeiff Thank you for reaching out and helping improve MS Docs. Please check @jambirk comment and let me know what wording should be changed in step 7 for both articles.

**Comment by jupfeiff** [comment]
Hi,
this needs to be rewritten to configure the policies with the required executable names in it, which are different per server role (e.g. Front End different than Mediation). The Edge server role needs to be handled entirely different since one can only use local policies there.
Here are the names for the executables:

  *   Front End: AVMCUSvc.exe; OcsAppServerHost.exe
  *   Mediation Server: MediationServerSvc.exe
  *   Edge Server: MediaRelaySvc.exe

Let me know if that helps.
Best regards,
Jürgen

**Comment by get-itips** [comment]
Hello @jupfeiff 

Thanks for your feedback, we appreciate it.
I reviewed your suggestions, you are right that this is the most recent article between Lync 2013 and Windows 7/8, there is also one for Skype For Business client and Windows 10 that is very similar [here](https://docs.microsoft.com/en-us/skypeforbusiness/manage/network-management/qos/configuring-port-ranges-for-your-skype-clients)

I checked and selecting "All Applications" on step 7 is still the recommended option, so I do not see a need to change that, I've also configured this in the past and this has been the recommended option, but I agree with you that the phrase "This setting instructs the network to look for all packets with a DSCP marking of 46" is confusing in this step, so I'll create a pull request to improve the article on that step, also for the SfB/Win10 one.

About your last message: that would apply for a GPO at server level, not client level, so it is a totally different article.

Thank you for your contributions.

**Comment by jupfeiff** [comment]
Hi there,
not sure who recommends “all applications” and why, but this is wrong. This scope is looser than it needs to be and can affect other traffic as well which then accidentally gets prioritized.
I’m currently busy where this occurred and flooded the EF queue with SAP traffic. Why our PFE and Escalation Engineers haven’t identified this is another story but it could have been avoided entirely.
We’re now facing a situation where a customer had terrible voice quality for 6 months and we need to do everything that the customer doesn’t sue us! Just due to this “all applications”.
I’m working in the real time communications space since 12 years and trust me, I know what I’m talking about.
Best regards,
Jürgen

**Comment by get-itips** [comment]
Hello @jupfeiff 
Thanks for your reply, I think that **you did not read my last edit of the reply**, that is here, it said that on a second though I created a pull request to replace the all applications with the lync executable (got confused in my head with the server configuration).
Hopefully this pull request will be approved by someone from the product team and will be on the live version soon.
Thanks

**Comment by jupfeiff** [comment]
Hello Andres,
I read that one but don’t know what “pull request” is and what that means. Thanks for getting this sorted out.
Re Teams-article at https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2FMicrosoftTeams%2Fqos-in-teams-clients&data=02%7C01%7CJUPFEIFF%40MICROSOFT.COM%7C035536704b704a3c7ebe08d6f0e2ca90%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636961254185692009&sdata=3OZcRtAtF2FX6nQOrkIsv%2B%2BNFt%2FEREItRDIDBgIq5gQ%3D&reserved=0 : Here it clearly states the application name and therefore is good for me.
On the next page, select Only applications with this executable name and enter the name Teams.exe, and then click Next. This setting instructs the policy to only prioritize matching traffic from the Teams client.

Thanks and best regards,
Jürgen

**Comment by scanum** [comment]
@jupfeiff Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
