### ISSUE TITLE
Teams Outlook Add-In

### ISSUE THREAD

**Issue by tiapatel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2464]
Hello!

Up until very recently (today we noticed), we were unable to get the Teams Add-In in Outlook 2010. This was something that was confirmed as as expected by an SME in the FastTrack team. However, today we noticed that some users are now able to use the Teams Add-In in Outlook 2010.

Has something been added/changed by Microsoft to make this happen?

**Comment by scanum** [comment]
@tiapatel thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
