### ISSUE TITLE
Please enter the path to the root of your windows media

### ISSUE THREAD

**Issue by ebrownaw** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2467]
I've tried several Windows 10 Enterprise versions downloaded from the Microsoft Volume Licensing Service.  However, the script does not tell me which version I need.
Says OEMs must order physical Windows 10 Enterprise IoT media
But I am unable to find any sources online to how this might be done.

The closest I was able to find was the Windows 10 IoT Enterprise
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/iot-ent-overview
Which I don't think is the correct media either.

**Comment by scanum** [comment]
@ebrownaw thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
