### ISSUE TITLE
One Source Networks site isn't accessible

### ISSUE THREAD

**Issue by JadedRedDragon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2468]
The site for One Source Networks, http://www.onesourcenetworks.com/, is no longer available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7032678-5e68-61a5-efbb-e020933bd971
* Version Independent ID: dfba555c-3cb1-59e4-da83-5faeebe8cd4f
* Content: [Services for Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/certification/services-sip-trunking#feedback)
* Content Source: [Skype/SfbPartnerCertification/certification/services-sip-trunking.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbPartnerCertification/certification/services-sip-trunking.md)
* Service: **skype-for-business**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@JadedRedDragon Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by jambirk** [comment]
@scanum please verify and remove the dead link 
FYI @dougand-MSFT

**Comment by get-itips** [comment]
@JadedRedDragon thanks for your feedback, I verified, so I created a pull request to remove the 404 link.
Thank you

**Comment by scanum** [comment]
@JadedRedDragon Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
