### ISSUE TITLE
Dead Link.

### ISSUE THREAD

**Issue by js-securecom** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2469]
Unified Communications certificate partners link on this page is a dead link. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 854766da-e557-2338-0aea-262e67a0b984
* Version Independent ID: 20b49404-62d7-83f8-118d-b8189b87da0b
* Content: [Environmental requirements for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/environmental-requirements#feedback)
* Content Source: [Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/environmental-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/environmental-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@js-securecom Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum
