### ISSUE TITLE
Guidance on QoS for SRS

### ISSUE THREAD

**Issue by phsmiths** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#247]
Where can I find more information on "It is advised to enable Quality of Service (QoS) for Skype Room System."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d24bf2b-244d-0c6a-3984-f65def69bbb1
* Version Independent ID: 33b21755-7b6f-2093-8983-34694327bb8f
* Content: [Skype Room System domain joining considerations](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/domain-joining-considerations)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/domain-joining-considerations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/domain-joining-considerations.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
I've updated the topic with some links to QoS information. Update should be visible later today.
