### ISSUE TITLE
No upper limit documented in : How many apps can be added to a policy?

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2470]
This section only mentions the minimum number of apps in a policy, while this is the primary question raised on this topic.
 
Is there a maximum, if so what is the maximum .
Is it the same for Mobile / Desktop ?
and if not , how is this difference handled ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f91604a-35b0-dfbb-55b2-b601cb0841b0
* Version Independent ID: 84bcd0d7-b4ed-f13e-c84b-2ec6a7661ae9
* Content: [Manage app setup policies in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-app-setup-policies#feedback)
* Content Source: [Teams/teams-app-setup-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-setup-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Josverl  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @LanaChin can I kindly ask you if we can get the max number of apps that can be added to a policy from the PG? Thank you

**Comment by get-itips** [comment]
More info: I tested in my lab and could succesfully add 20+ apps, also, a pop-up list gets created on the menu with a scroll with the list of added apps, it appears that there is no upper limit.
Probably @LanaChin will confirm this.

**Comment by scanum** [comment]
@LanaChin Any updates on this? Thanks!

**Comment by scanum** [comment]
@LanaChin Hi Lana, any updates on this? Thanks!

**Comment by LanaChin** [comment]
Followed up with the PM on this.

**Comment by LanaChin** [comment]
Pinged PM again.

**Comment by LanaChin** [comment]
Pinged PM.

**Comment by LanaChin** [comment]
Updated article to note that there's no limit on the number of apps that can be added to a policy: https://docs.microsoft.com/en-us/microsoftteams/teams-app-setup-policies#how-many-apps-can-be-added-to-a-policy.
