### ISSUE TITLE
Bot doesn't work in public conversation

### ISSUE THREAD

**Issue by Morgannik8** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2473]
Why simple QnA Bot don't work in public chat or Team? I selected the Group chat and Team check box under the scope section.
1:1 bot working, but with conversation it doesn't. Why? 

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: c1257b9b-73ca-8a97-3f65-a7c8d5937e8c
* Version Independent ID: 5f9b5fad-dceb-3f9e-192c-a31ca05e0b83
* Content: [Добавление ботов для приватных чатов и каналов в Microsoft Teams](https://docs.microsoft.com/ru-ru/microsoftteams/add-bots#feedback)
* Content Source: [Teams/add-bots.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/add-bots.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Morgannik8 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
