### ISSUE TITLE
Wrong information about license information - There is no 5 guests per user limit

### ISSUE THREAD

**Issue by marcoscheel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2474]
The following segment is wrong or at least missing the information about premium functions:

Paragraph: If your guests are seeing license errors
"For each paid Azure AD license that you assign to a user, your users can invite up to five guest users under the External User Allowance."

The B2B docs are precise that the 1:5 ratio is only about paid Azure AD services (Azure AD P1 and higher like MFA, TOS, ...)
https://docs.microsoft.com/en-us/azure/active-directory/b2b/licensing-guidance
With Azure Active Directory (Azure AD) business-to-business (B2B) collaboration, you can invite External Users (or "guest users") to use your paid Azure AD services. For each paid Azure AD license that you assign to a user, you can invite up to five guest users under the External User Allowance.
B2B guest user licensing is automatically calculated and reported based on the 1:5 ratio. Currently, it’s not possible to assign B2B guest user licenses directly to guest users.
Additionally, guest users can use free Azure AD features with no additional licensing requirements. Guest users have access to free Azure AD features even if you don’t have any paid Azure AD licenses.

I would suggest to remove the paragraph or add the bit about the premium services from Azure AD!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams guest access checklist](https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist#feedback)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@marcoscheel Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @marcoscheel thanks for your feedback, as a first step, I created a pull request to add the link to B2B collab license guidance to the referenced article, and also, and as a 2nd step I would like to invite @LanaChin to check with the product group if we can get more info to clarify better the current statement about the premium/free features and guest users.
Thank you

**Comment by scanum** [comment]
@LanaChin Any updates on this? Thanks!

**Comment by LanaChin** [comment]
I've reached out to the PM to get clarity.

**Comment by LanaChin** [comment]
The PM recommended to add a link to the Azure AD B2B licensing guidance, which @get-itips already did (thanks!).

I've also removed the bullet  point in question ("For each paid Azure AD license that you assign to a user, your users can invite up to five guest users under the External User Allowance.") to avoid confusion.  That bullet point is in the Azure AD B2B guidance article and so readers can find the information there in context.
