### ISSUE TITLE
Tab: Website - function list

### ISSUE THREAD

**Issue by Mikelsoft99** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2475]
Hi,
I'd like to adopt my webapp to fit the ms teams windows desktop client. It's written in react, the webapp is loading but as soon as it gets to the fetch and promis API it seems to hang.
It's hard to get some debug info out of it.

Is there a function list, which is supported by the javascript engine there, or a possibility to test against it?

Thank you
Mike

**Comment by scanum** [comment]
@Mikelsoft99 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
