### ISSUE TITLE
License requirement

### ISSUE THREAD

**Issue by Batre-MSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2481]
For Exchange On-Premises and teams integration, only AAD sync is mentioned as requirement. Please mention required license needs to be assigned for AAD Synced user

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact#feedback)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@Batre-MSFT Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@Batre-MSFT thank you for pointing this out and helping improve MS Docs.  Do you perhaps know which license is required so I can add a note in the article?

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by abkaberi** [comment]
Can anyone please confirm the license requirement for "when you have EXCH on prem 2016 CU11+ running in a hybrid environment with EXO" which means AAD connect is by default provisioned--> In this scenario, do we still need to assign EXO license to the synced user when his/her mailbox resides in Oprem EXCH 2016 server to leverage Calendar feature within Teams?
