### ISSUE TITLE
Step 1 doesn't include the 'Collaboration restrictions' available in the new admin center

### ISSUE THREAD

**Issue by robertpp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2482]
No reference exists about the 'Collaboration restrictions' available in the new admin center. This section allows controlling the domains to which the invitation for external collaboration can be sent.

Another missing item is the preview option 'Enable Email One-Time Passcode for guests'. This could be added later, after it passed the validation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams guest access checklist](https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist#feedback)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@robertpp Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@robertpp Thank you for pointing this out.  Would you suggest adding a note under step 1 as follows: "Collaboration restrictions are available in the new admin center. This section allows controlling the domains to which the invitation for external collaboration can be sent."? 
Where should I add the information about Enable Email One-Time Passcode for guests?

**Comment by robertpp** [comment]
Hi Lindsay. Thank you for the question. I actually don't know. 

The screenshot in step 1 no longer matches the current look in the Azure Active Directory admin center, so clearly there's been a change since the document was written. Yet, we cannot talk about a 'new admin portal' in the same way as for the Office 365 admin portal. A screenshot of the current UI is available in [
Enable B2B external collaboration and manage who can invite guests](https://docs.microsoft.com/en-us/azure/active-directory/b2b/delegate-invitations). I would suggest we adapt the current article to match the description and the screenshot from the newer one. 

> - **Enable Email One-Time Passcode for guests (Preview)**: For more information about the one-time passcode feature, see [Email one-time passcode authentication (preview)](https://docs.microsoft.com/en-us/azure/active-directory/b2b/one-time-passcode).
> - **Collaboration restrictions**: For more information about allowing or blocking invitations to specific domains, see [Allow or block invitations to B2B users from specific organizations](https://docs.microsoft.com/en-us/azure/active-directory/b2b/allow-deny-list).
 
Another point I just noticed is that the current document fails to make it clear why having the option **Members can invite** set to _Yes_ is compulsory for Teams. The article '[Authorize guest access in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-dependencies)' does it in a note:

> Currently, Teams doesn't support the guest inviter role. At a minimum the Members can invite toggle must be set to Yes for guest access to work in Teams.

Since the current article is the most likely to be used by support to troubleshoot Guest Access, I would suggest we include this note, before the following one. I do not have sufficient experience with Guest Access in Teams to tell if this note is valid, so I would keep it until we know for a fact that it's false.

> If you set Members can invite to No and then enable guest access in Office 365 Groups and Microsoft Teams, admins can control guest invitations to your directory. After guests are in the directory, they can be added to teams by non-admin members who are team owners.

**Comment by scanum** [comment]
@robertpp Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by baron-zhang-avepoint** [comment]
Is there any API which can help us to get the setting details of Collaboration restrictions?
