### ISSUE TITLE
Are the Hardware Requirements the MINIMUM requirements?

### ISSUE THREAD

**Issue by kelemvor33** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2487]
I see that all the Surfaces listed as being compatible with this system list the Core i5 processor.  We have surfaces that run the Core i7 processor.  Is the i5 the minimum or will this not work with the i7 processor?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf01435-a73b-4bf2-5845-e4cf50c4c3a2
* Version Independent ID: 166e1800-80b1-2496-7160-3040c5b23c3d
* Content: [Microsoft Teams Rooms requirements](https://docs.microsoft.com/en-us/microsoftteams/room-systems/requirements)
* Content Source: [Teams/room-systems/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@kelemvor33 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
