### ISSUE TITLE
Typo on "gateway's" (apostrophe)

### ISSUE THREAD

**Issue by campbellkerr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2490]
Appears 3 times on page. If you're intending to say plural of gateway, it should be "gateways" :). Cheers!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72d9c2af-b933-f9a2-e189-387c881cffd0
* Version Independent ID: a614d386-7ce8-5c96-690e-b40231e67118
* Content: [Edge Server environmental requirements in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/edge-server-deployments/edge-environmental-requirements)
* Content Source: [Skype/SfbServer/plan-your-deployment/edge-server-deployments/edge-environmental-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/edge-server-deployments/edge-environmental-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@campbellkerr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@campbellkerr Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
