### ISSUE TITLE
Added external domain, how much time to wait to have it enabled?

### ISSUE THREAD

**Issue by carloreggiani** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2491]
Hi
There is any time estimation to have a new external domain configured? We did it 3 hours ago but we're still not able to initiate any chat with contacts in the new federated domani.

Maybe better add in documentation a time-related info abount effective activation.

Thanks in advance

Carlo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31588a25-f3ee-e888-aa67-203be3d34489
* Version Independent ID: 3b498bcf-69a9-01ac-973a-4d5dbeea587c
* Content: [Manage external access (federation) in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@carloreggiani Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by tonysmit** [comment]
Hi Carlo. It may take up to 24 hours for the service to distribute it to all datacenters so try to be patient. Unfortunately it takes time. However, if it doesn't show up, reply back here and I will try to help.

**Comment by scanum** [comment]
@carloreggiani We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
