### ISSUE TITLE
Missing a critical organization profile

### ISSUE THREAD

**Issue by daverooney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2493]
"I'm currently using Skype for Business Online, and I have no need or desire to move to Teams."  This is a critical, majority use-case, and should be addressed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b131c7fd-ec71-6b6f-4443-ddaf5cb44bf6
* Version Independent ID: 0c1fb61b-a6cc-e856-d969-54bc13ec699c
* Content: [How to roll out Microsoft Teams](https://docs.microsoft.com/en-US/MicrosoftTeams/how-to-roll-out-teams#feedback)
* Content Source: [Teams/How-to-roll-out-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/How-to-roll-out-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@daverooney thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by daverooney** [comment]
Foisting this off on the service team is an inappropriate approach.  This is a matter of Microsoft policy and communications.
