### ISSUE TITLE
[LOC] Not fixed #1894 (en-us is fiexd, but ja-jp is not fixed.)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2496]
Not fixed #1894 (en-us is fiexd, but ja-jp is not fixed.)

en-us:https://docs.microsoft.com/en-us/microsoftteams/enable-features-office-365
![enable-features-office-365_e](https://user-images.githubusercontent.com/40815708/59960800-ccd07000-9508-11e9-9f97-b68f164b5064.png)

ja-jp:https://docs.microsoft.com/ja-jp/microsoftteams/enable-features-office-365
![enable-features-office-365_j](https://user-images.githubusercontent.com/40815708/59960802-d22dba80-9508-11e9-9606-22fbf49c4bca.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2c9b7f77-061d-a224-ff1c-8d3e15d21221
* Version Independent ID: 00fa9550-c4c4-3398-ffbb-271cc724048f
* Content: [組織の Microsoft Teams の設定を管理する](https://docs.microsoft.com/ja-jp/microsoftteams/enable-features-office-365)
* Content Source: [Teams/enable-features-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enable-features-office-365.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officeglobal Hi could you please aid with this issue? Thanks!

@officedocsbot assign @scanum
@officedocsbot assign @officeglobal

**Comment by OfficeGlobal** [comment]
INTL is being updated according to fixed source

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum topic has been updated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks. fixed. Close #2496
![enable-features-office-365_j2](https://user-images.githubusercontent.com/40815708/60109676-c01c7800-97a5-11e9-9142-868e0626863e.png)

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
