### ISSUE TITLE
Documentation incorrect in several places.

### ISSUE THREAD

**Issue by TravitoDLM** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#250]
"Enable-Mailbox 'PROJECTRIGEL01@contoso.com' -RemoteRoutingAddress 'PROJECTRIGEL01@contoso.com' -Room" <- "RemoteRoutingAddress" is not a valid parameter on Exchange 2013. I see no mention anywhere indicating that Exchange 16 is required.

The documentation says that only "Password never expires" should be ticked on the account. This conflicts with the fact that a room mailbox can't be enabled for a logon-enabled account.

The second code block seems entirely wrong. For one thing, why one earth are we supposed to change the execution policy to run standard commands, with no .ps1 scripts in sight? Furthermore, why is the connectionuri for Office 365 Exchange online, if these instructions are for Exchange On Prem with Skype for Business Online?

I've tried following the instructions to the letter, changing only what is needed for our environment. The instructions simply do not work at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c724919-9729-2e8e-4669-3643de86ff0b
* Version Independent ID: 931ce9da-daba-3d0d-8dca-1821123cc819
* Content: [Deploy Skype Room Systems v2 with Exchange on premises (Hybrid)](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/with-exchange-on-premises#feedback)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/with-exchange-on-premises.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/with-exchange-on-premises.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by TravitoDLM** [comment]
I'll add, I did find a script on the configure accounts page. But if this separate page is going to exist it needs to have correct information.

**Comment by jambirk** [comment]
I've notified the product group team that provided this information, they're discussing it an we will update the page once they have consensus on the best recommendations.

**Comment by kenwith** [comment]
@davgroom or @Travis-Snoozy .. any update if we should update the docs? Support got some info coming in on this too. Thanks!

**Comment by Turgayo** [comment]
@kenwith, I am working on that one and still validating each code snippets we have on the docs. I will raise a PR with the updates soon.

**Comment by TravitoDLM** [comment]
@Turgayo would you all like further information from me regarding what, specifically is not working? The all in one script from another page is not working either. we are on prem exchange 13 with synced AD and skype for business online.

**Comment by Turgayo** [comment]
@TravitoDLM that would be great, if you can provide more information. 
Meanwhile, have you tried https://myadvisor.fasttrack.microsoft.com/CloudVoice/Downloads?SelectedIDs=5_2_0_4,5_2_0_5 too?

**Comment by jambirk** [comment]
I just approved Turgay's updates. Please let us know if more updates are needed to resolve the issue.

**Comment by kenwith** [comment]
Merged, thanks!
