### ISSUE TITLE
SQL Backend architecture requirements

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2509]
Missing from this doc is language previously found on Technet around backend architecture. Specifically, SQL backend must be "well connected" or local to the SfB Front-Ends (and not across a low speed link), and that it is not supported to share SQL backends between 2 or more pools.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c475b5d-09ed-7f58-86d4-27f28e33ef7a
* Version Independent ID: f0ad50f3-ea93-9424-6de8-a0b778e90b23
* Content: [Server requirements for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/server-requirements#back-end-databases-that-will-work-with-skype-for-business-server-2015)
* Content Source: [Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@TorrenManson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@TorrenManson Thank you for reaching out and helping improve MS Docs.  Just for clarification, are you suggesting adding a note in the article with your wording mentioned?

**Comment by TorrenManson** [comment]
I’m happy for you to use my wording if that works for you. I can’t find the technet wording, otherwise I’d suggest it be used.

**Comment by scanum** [comment]
@TorrenManson Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
