### ISSUE TITLE
Interop for on-prem homed Skype users

### ISSUE THREAD

**Issue by embj** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#251]
Can the interop requirements be made a little clearer to say that the interop only works if the Teams user is homed to Skype Online? We were looking to setup interop between Skype on-prem (we have no Skype Online users) and Teams. After setting up Skype hybrid and spending a good deal of time trying to get interop to work, we discovered that this isn't supported only after opening up a ticket.

Can the info about unified presence also be updated now that support for it is rolling out?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d53d0cb0-90a6-5932-f78e-7de6fcc4d481
* Version Independent ID: 3d468027-cc37-5199-32ec-819bf62b2caa
* Content: [Microsoft Teams and Skype for Business interoperability](https://docs.microsoft.com/en-us/microsoftteams/teams-and-skypeforbusiness-interoperability#skype-for-business-hybrid-deployment-topology)
* Content Source: [Teams/Teams-and-SkypeforBusiness-interoperability.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-and-SkypeforBusiness-interoperability.md)
* Service: **msteams**
* Product: **unspecified**
* GitHub Login: @arachmanGitHub
* Microsoft Alias: **MyAdvisor**

**Comment by arachmanGitHub** [comment]
hi @embj, we're in the process of updating this document and for full technical details, please refer to this document https://docs.microsoft.com/en-us/MicrosoftTeams/migration-interop-guidance-for-teams-with-skype

**Comment by embj** [comment]
Thanks, Agus. The link to the technical deep dive is extremely helpful, too.
