### ISSUE TITLE
Guest user file access in person to person chat

### ISSUE THREAD

**Issue by sav169** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2513]
I need some clarity on one of the point in the **limitations for guests** - https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist

- Upload files to a person-to-person chat
Eg: 
A normal user initiates a one-to-one/one-to-many chat with a guest user. In the chat the normal user attaches a file. The guest user is not able to open the file and they get error message “This item might not exist or is no longer available" when they click on the file

Should the guest user see the file or is this an expected limitation ?

![teams person to person chat file](https://user-images.githubusercontent.com/39164385/60024574-e6e88a80-968f-11e9-8c67-7cfc95eed6b1.png)

**Comment by scanum** [comment]
@sav169 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
