### ISSUE TITLE
Create/view meeting and edit profil pic is not supported with Exchange 2016 CU3+

### ISSUE THREAD

**Issue by boehmmic** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2517]
In the table it says "Yes (Exchange 2016 CU3+)" for Create and view meetings as well es Modify user profile picture. We have Exchange 2016 CU11 and in our environment we don't have a Meeting Tab at all or Meeting Schedule option. Furthermore it says "To let Microsoft Teams work with Exchange on-premises, you must configure the new Exchange OAuth authentication protocol as described in Configure OAuth authentication between Exchange and Exchange Online organizations -&gt; Link https://docs.microsoft.com/en-us/exchange/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help"  where the link leads to an Exchange 2013 documentation for a complex hybrid scenario which is kind of confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact#feedback)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@boehmmic Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Nico255** [comment]
I support this question as we are running an hybrid configuration with Exchange 2016 latest CU and on-prem users do not have a "Meetings" tab while cloud users do. Please clarify asap what the expected behavior is.

**Comment by lindspea** [comment]
@boehmmic  @Nico255 Thank you for pointing this out and helping improve MS Docs.  I'm investigating with the team and will revert soonest.

**Comment by scanum** [comment]
@boehmmic thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
