### ISSUE TITLE
http (non-https) links to installers

### ISSUE THREAD

**Issue by Conan1989** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#252]
links to installers are non-https

http://aka.ms/teams64bitmsi
http://aka.ms/teams32bitmsi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b13006b-d1de-8bc7-e0c6-b7022af0e731
* Version Independent ID: d29dae65-bb28-8767-cfd7-07d2ed5fd460
* Content: [Install Microsoft Teams using MSI](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* Product: **unspecified**
* GitHub Login: @ninadara
* Microsoft Alias: **ninadara**

**Comment by kenwith** [comment]
@Conan1989 - this is fixed and should be live shortly. Thanks for pointing out!
