### ISSUE TITLE
Cannot see any calling policies in the Teams admin center

### ISSUE THREAD

**Issue by bertrandsophie** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2521]
In the Teams admin center / Voice / Calling policies : no policies at all are displayed.
- I cannot see the predefined ones.
- I cannot see the ones I created in powershell
- I can create a new policy from the admin center but it does not appear. However I can check it was correctly created with Get-CsTeamsCallingpolicy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410fc30b-f530-8443-0602-9150c9cba115
* Version Independent ID: c5b33b25-147b-f7d4-056a-987088950e7c
* Content: [Calling policies in Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-calling-policy#feedback)
* Content Source: [Teams/teams-calling-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-calling-policy.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@bertrandsophie thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
