### ISSUE TITLE
Disabling PINs

### ISSUE THREAD

**Issue by EspoDevMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2527]
I believe this is incorrect.   it certainly doesnt work.

If anonymous access, or not requiring a PIN to start a meeting, is disabled:

- If the meeting hasn't started (there's no one in the meeting yet): A caller won't be prompted if she's the organizer, and she'll never be prompted for the PIN. Because the setting of the organizer is set to off, the meeting will start and the anonymous callers will join the meeting.

**Comment by scanum** [comment]
@EspoDevMSFT Could you please link the article you are referring to? Thanks!

**Comment by scanum** [comment]
@EspoDevMSFT We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
