### ISSUE TITLE
Interaction with SPO external sharing settings

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2533]
Please add some information about how these settings integrate with the external sharing settings in SharePoint Online. Specifically, what needs to be done to ensure that no conflicts occur and to ensure that external users are granted access in accordance with an organizations requirements. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Communicate with Teams users in another organization](https://docs.microsoft.com/en-us/microsoftteams/let-your-teams-users-communicate-with-other-people)
* Content Source: [Teams/let-your-teams-users-communicate-with-other-people.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/let-your-teams-users-communicate-with-other-people.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@DeanGross Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@DeanGross Thanks for reaching out Dean.  Is there anything specific you could suggest to add to the article? Alternatively please have a look at these articles and let me know if adding the relevant links in this article would help clarify the above - https://docs.microsoft.com/sharepoint/sharing-permissions-modern-experience or https://docs.microsoft.com/sharepoint/external-sharing-overview.

**Comment by DeanGross** [comment]
It would be good if the prereqs stated what External Sharing option needs to be enabled in the associated SPO site. A matrix that shows Teams External Users and Guest vs SPO External Sharing settings with the enabled/disabled functionality for each option would be very useful

**Comment by tonysmit** [comment]
Hi @DeanGross - So, I would like to talk about this a bit more. So are you recommending to add a third column with SPO settings? I think this is a good idea but I would like for you to explain more in detail if you can. Keep in mind I have worked with SP since 2013. :)

**Comment by scanum** [comment]
@DeanGross We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
