### ISSUE TITLE
Interaction with SharePoint External Sharing settings

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2534]
Please add some information about how these settings integrate with the external sharing settings in SharePoint Online. Specifically, what needs to be done to ensure that no conflicts occur and to ensure that Guests are granted access in accordance with an organizations requirements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31588a25-f3ee-e888-aa67-203be3d34489
* Version Independent ID: 3b498bcf-69a9-01ac-973a-4d5dbeea587c
* Content: [Manage external access (federation) in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access#more-information)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@DeanGross Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@DeanGross Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
