### ISSUE TITLE
Microsoft Teams - GiphyContentRating

### ISSUE THREAD

**Issue by Dizzle87** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2537]
In the Microsoft Teams Admin Center web interface, it is possible to change "Giphy Content rating" to "No restriction", but running the Powershell command (_get-team -displayname "NameofTheTeams" | fl giphyContentRating_) returns the value "**unknownFutureValue**". 
This results in the giphyContentRating still being stuck on Moderate in Teams, despite showing "No restrictions" in the web interface. 

Is there a way to bypass this in order to get "No restriction" for a Team?

**Comment by scanum** [comment]
@Dizzle87 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
