### ISSUE TITLE
New Teams Admin portal

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2538]
Is there an article like this but more basic on how to use the MS Teams Admin center to do all of this? There are SO MANY footnotes in this article with crazy old PowerShell commands. I feel like Teams is supposed to be nice and easy, but a lot of these articles are not easy to setup a simple phone auto attendant. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40ed9cf1-93cc-698a-a974-44584c2ad448
* Version Independent ID: 10b1f715-8c08-7943-2bbf-699e1a59b358
* Content: [What are Cloud auto attendants?](https://docs.microsoft.com/en-us/microsoftteams/what-are-phone-system-auto-attendants)
* Content Source: [Teams/what-are-phone-system-auto-attendants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-phone-system-auto-attendants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@eschrader @ Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@eschrader Hi Eric. Thank you for reaching out.  Please have a look at this link and let me know if it helps sort out your issue. https://docs.microsoft.com/microsoftteams/manage-teams-in-modern-portal.

**Comment by scanum** [comment]
@eschrader We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by eschrader** [comment]
> @eschrader Hi Eric. Thank you for reaching out. Please have a look at this link and let me know if it helps sort out your issue. https://docs.microsoft.com/microsoftteams/manage-teams-in-modern-portal.

Thank you for the response! What part of this article goes over Auto Attendant settings in the new admin portal? This article seems like a generic overview of Teams Admin portal, which is the issue I am bringing up for lack of documentation around setting up a phone system with Teams Admin Portal and auto attendants.
