### ISSUE TITLE
Need Help Understanding Capacity Planning

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#254]
It would be helpful to understand capacity planning, what treatment is received when a call arrives to a response group that is beyond the capacity of the system e.g. 17th call per second received on a front end pool.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4146039-6a62-7a47-9f02-5600cb026c6c
* Version Independent ID: ab460f03-0253-4cdc-df42-4268f8987be2
* Content: [Plan for the Response Group application in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/enterprise-voice-solution/response-group)
* Content Source: [Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/response-group.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/response-group.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by dariomws306** [comment]
Hi @nsshommo , Capacity Planning in this case (and usually) means that these values are the max. supported. If you go beyond them, you are out of support, you need to deploy a new enterprise pool.
