### ISSUE TITLE
This page is out of date

### ISSUE THREAD

**Issue by dschuette01** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2540]
The information provided here is not accurate. The Communications Credits have been moved somewhere and are no longer able to be purchased as described above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d8f6008-136f-52a1-70c8-f721f1be0491
* Version Independent ID: efaeb679-a1c9-ab98-9f0b-f253a19cecec
* Content: [Add funds and manage Communications Credits](https://docs.microsoft.com/en-us/microsoftteams/add-funds-and-manage-communications-credits#feedback)
* Content Source: [Teams/add-funds-and-manage-communications-credits.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/add-funds-and-manage-communications-credits.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@dschuette01 @ Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@dschuette01 Thank you for pointing this out and helping improve MS Docs.  Are you suggesting retiring the whole article or just removing the section about the subscription page and communication credits?

**Comment by scanum** [comment]
@dschuette01 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

**Comment by NickDorak** [comment]
Why was this closed without updating the out of date documentation?
