### ISSUE TITLE
Table of External Access seems wrong

### ISSUE THREAD

**Issue by EFXCraig** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2551]
The comparison table on the page is quite wrong in regards to External Access Users. 
With External Access users on (whitelisted companies) and Guest Access off: 
Presence is displayed: No
Screen sharing mode: Yes
Use Giphy in conversation: Yes
Use memes in conversation: Yes
Use stickers in conversation: Yes
User can be added to a group chat: Yes
Addition users can be added to a chat with an external user: Yes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31588a25-f3ee-e888-aa67-203be3d34489
* Version Independent ID: 3b498bcf-69a9-01ac-973a-4d5dbeea587c
* Content: [Manage external access (federation) in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@EFXCraig @ Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@EFXCraig Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
