### ISSUE TITLE
https://aka.ms/UpgradeOverview is a dead link

### ISSUE THREAD

**Issue by rgsteele** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2555]
In the paragraph beginning "View this overview for an introduction to the Skype for Business to Teams upgrade journey", the link on "Overview" points to https://aka.ms/UpgradeOverview. This redirects to https://skypeandteams.fasttrack.microsoft.com/, which currently returns a "404 Web site not found" message.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7b32af2-59db-a872-6ed4-fc7b4cd910b3
* Version Independent ID: 38fd3a1a-ee6d-dd63-0de9-5f726d7419cf
* Content: [Upgrade Skype for Business to Microsoft Teams](https://docs.microsoft.com/en-US/MicrosoftTeams/journey-skypeforbusiness-teams?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/Journey-SkypeforBusiness-Teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Journey-SkypeforBusiness-Teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@rgsteele @ Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@rgsteele Thank you for your feedback, I will have it sorted out shortly.

**Comment by tonysmit** [comment]
@LolaJacobsen - she might be able to assist.

**Comment by LanaChin** [comment]
Followed up with the PM.

**Comment by LanaChin** [comment]
The link is no longer needed. The page that contained the link, Journey-SkypeforBusiness-Teams.md, page redirects to https://docs.microsoft.com/MicrosoftTeams/upgrade-start-here, which doesn't contain the link.
