### ISSUE TITLE
ALLUSER=1

### ISSUE THREAD

**Issue by denniskn** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2556]
Hi, in "VDI Installation" point number 2 you have this command line:
msiexec /i &lt;path_to_msi&gt; /l*v &lt;install_logfile_name&gt; ALLUSERS=1

This should be ALLUSER instead of ALLUSERS
msiexec /i &lt;path_to_msi&gt; /l*v &lt;install_logfile_name&gt; ALLUSER=1

You also refer to this page, and that one mentions the right command:
https://docs.microsoft.com/en-us/MicrosoftTeams/teams-for-vdi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Microsoft Teams using MSI via SCCM](https://docs.microsoft.com/en-us/MicrosoftTeams/msi-deployment#feedback)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@denniskn @ Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@denniskn Thank you for reaching out and helping improve MS Docs.  I've just had a look at the article and it is currently reading ALLUSER=1. Please let me know if it's reading correctly on your side as well now.

**Comment by denniskn** [comment]
Yes it's OK now. Thank you!
