### ISSUE TITLE
No undo button?

### ISSUE THREAD

**Issue by michaelharkless** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2557]
Can you please add this cmdlet so we can erase our configuration to start over?
Remove-csclouddatconnectorconfiguration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b62ec34b-8685-a805-dc4d-40dab2d22e8b
* Version Independent ID: d39906c3-daa8-507f-5110-1b48a6876b3c
* Content: [Configure Call Data Connector](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/configure-call-data-connector#feedback)
* Content Source: [Skype/SfbHybrid/hybrid/configure-call-data-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-call-data-connector.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@michaelharkless @ Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@michaelharkless Thank you for reaching out and helping improve MS Docs.  I'll have the cmdlet added to the article.  Please could you specify in which part of the article you would recommend adding it.

**Comment by scanum** [comment]
@michaelharkless Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
