### ISSUE TITLE
Commands use -Tenant Parameter not -TenantID

### ISSUE THREAD

**Issue by MikeParker365** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2558]
I was implementing this with a customer recently and found the cmdlet needed to use the parameter -Tenant not -TenantID. I've tried updating the page directly without success. Was my experience the correct one? Can we get the page updated with the change if so? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec8b8afb-b9ca-8136-b907-5bbff4c9dcf1
* Version Independent ID: d4f68818-6fe6-5bb7-f108-e26a643f2cc7
* Content: [Configure Cloud Voicemail service for on-premises users](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/configure-cloud-voicemail)
* Content Source: [Skype/SfbHybrid/hybrid/configure-cloud-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-cloud-voicemail.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@MikeParker365 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Parroman** [comment]
-TenantID worked for me. Have just set this today.

**Comment by lindspea** [comment]
@MikeParker365 Hi Mike. Thanks for reaching out.  Please let me know if you agree with @Parroman as -TenantID worked for him. If not, I can have it changed in the article.

**Comment by scanum** [comment]
@MikeParker365 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by oradcliffe** [comment]
TenantID is not a valid parameter for me either.  Latest CU on SfB Server 2015, I do not have TenantID, I only have Tenant as an available parameter.

**Comment by Parroman** [comment]
https://chrishayward.co.uk/2020/02/06/skype-for-business-server-cloud-voicemail-configuration-tenant-or-tenantid/

It actually looks like you have taken out -tenant or -tenantID now from Set-CsHostedVoicemailPolicy -Identity Global -Description "Global Cloud Voicemail Policy" -Destination exap.um.outlook.com -Organization YourDefaultDomain.onmicrosoft.com -Tenant “11111111-1111-1111-1111-111111111111”. 
Good idea to update this document to remove it as it works without it now.
