### ISSUE TITLE
Dial Plans in Microsoft Teams Audio Conferencing - 404

### ISSUE THREAD

**Issue by DKiefer770** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2559]
Target not foud

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 243b9f9c-de59-d1b3-42be-5367526059e0
* Version Independent ID: d1435070-4b51-b487-dddc-2d8dc16798f9
* Content: [Onboarding checklist for configuring cloud voice workloads in Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/onboarding-checklist-configure-cloud-voice-workloads-in-microsoft-teams)
* Content Source: [Teams/onboarding-checklist-configure-cloud-voice-workloads-in-Microsoft-Teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/onboarding-checklist-configure-cloud-voice-workloads-in-Microsoft-Teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@DKiefer770 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Fixing broken link on PR #2585

**Comment by scanum** [comment]
@DKiefer770 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
