### ISSUE TITLE
Where is lcslog - the archiving database?

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#256]
Where is lcslog - the archiving database, where can I find it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfbe74fb-9f37-d757-cd86-160de8a0293f
* Version Independent ID: 53b9bac5-009d-5486-a38a-013b55699a1f
* Content: [Schema reference for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/schema-reference/schema-reference)
* Content Source: [Skype/SfbServer/schema-reference/schema-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/schema-reference/schema-reference.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by jambirk** [comment]
are you asking where in the network lcslog is placed? or asking where the reference describing the file and its structure is?
