### ISSUE TITLE
Port Orders not available in Legacy Teams Portal

### ISSUE THREAD

**Issue by DKiefer770** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2560]
??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1829a37-a7a1-4dd1-fde8-82125c593ff1
* Version Independent ID: dfedc4c5-eec4-2137-e975-399866aaafad
* Content: [Transfer phone numbers to Office 365](https://docs.microsoft.com/en-us/microsoftteams/transfer-phone-numbers-to-office-365?toc=/skypeforbusiness/toc.json&bc=/skypeforbusiness/breadcrumb/toc.json)
* Content Source: [Teams/transfer-phone-numbers-to-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/transfer-phone-numbers-to-office-365.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@DKiefer770 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@DKiefer770 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by Chrisb1e** [comment]
For anyone else who stumbles across this page and has the same problem like I did.

I reached out to Microsoft via Office 365 admin portal. I was told that once my account has an E5 licence then the option would show up. I am currently exploring options for soft phones and wanted to see the process but we are on E3 licences.
