### ISSUE TITLE
Missing URL

### ISSUE THREAD

**Issue by jefftrnka** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2564]
Missing your "o365filtering.com" URL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96088236-4cde-fe10-9023-67f3d339bdbe
* Version Independent ID: 2f4cb807-2a4d-1165-836d-7c2c688b1a2c
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/microsoftteams/office-365-urls-ip-address-ranges)
* Content Source: [Teams/Office-365-URLs-IP-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-URLs-IP-address-ranges.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@jefftrnka  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@jefftrnka Thank you for your feedback, I'll have the issue sorted shortly.

**Comment by scanum** [comment]
@jefftrnka We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
