### ISSUE TITLE
CreateSrsMedia.ps1 Times out when downloading driver

### ISSUE THREAD

**Issue by PaulShadwell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2567]
I have tried this several times now on different Windows 10 machines both in the office and on my home network. No matter how I run the script it fails at downloading drivers. The temp file is created but stays at 0bytes then eventually times out.
I have looked at the other answers to issues with the script but for me, it consistently fails at the driver download.
Any assistance would be appreciated.

**Comment by scanum** [comment]
@thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
