### ISSUE TITLE
Currently: Number of members in an org-wide team -> $5,000

### ISSUE THREAD

**Issue by maduroq** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2568]
The dollar sign is included for members amount limit.
I expected it to be:
Number of members in an org-wide team -&gt; 5,000 like mentioned on the page: https://docs.microsoft.com/nl-nl/microsoftteams/create-an-org-wide-team 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Beperkingen en specificaties voor Microsoft Teams](https://docs.microsoft.com/nl-nl/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@maduroq Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@maduroq Thank you for reaching out and helping improve MS Docs. I've had a look at the article and I can't see the $ sign that you are referencing.  Perhaps it's been fixed in the interim.  Please confirm if you're still seeing the issue.

**Comment by maduroq** [comment]
@lindspea it's been fixed in the interim. Thank you!

**Comment by scanum** [comment]
@maduroq Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
