### ISSUE TITLE
Missing screenshot in section "Don't attempt to open the topology in the legacy Topology Builder"

### ISSUE THREAD

**Issue by aalejandroaraujo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2569]
Section says: "If you attempt to open the topology using the legacy Topology Builder, you will encounter the error below."

However, there's no picture of the error shown below. Please add it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4754981d-a773-8872-09cc-41b5691a99df
* Version Independent ID: 9abe5981-ceb1-1bdc-787c-07f15f9a5bbf
* Content: [Verify pilot pool coexistence with legacy pool](https://docs.microsoft.com/en-us/SkypeForBusiness/migration/verify-pilot-pool-coexistence-with-legacy-pool#feedback)
* Content Source: [Skype/SfBServer2019/migration/verify-pilot-pool-coexistence-with-legacy-pool.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/migration/verify-pilot-pool-coexistence-with-legacy-pool.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@aalejandroaraujo  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@aalejandroaraujo Thank you for pointing this out and helping improve MS Docs.   I'll have the image added soonest.

**Comment by scanum** [comment]
@aalejandroaraujo Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
