### ISSUE TITLE
Need clarification about "Meeting Delegation"

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#257]
Please clarify if this statement pertains to the Exchange mailbox being in the same forest, or the Skype user being on-prem or online? 

"Meeting delegation - Supported only when both users are homed online in the same forest, or both are homed on-premises". 

Will delegation not work if one user is on homed on Skype on-prem and the other is on Skype online?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 912ac235-0901-7054-ba50-130b2b38c53d
* Version Independent ID: 289d976b-4441-f2d7-4d33-0faf094cf196
* Content: [Integration with Exchange and SharePoint](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-hybrid-solutions/integration-with-exchange-and-sharepoint)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/integration-with-exchange-and-sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/integration-with-exchange-and-sharepoint.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
It refers to where the user is homed:  on-prem or online.

**Comment by kenwith** [comment]
Added PR to cross link with more info.
