### ISSUE TITLE
No picture shown, while there's a reference to "in the image below"...

### ISSUE THREAD

**Issue by aalejandroaraujo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2570]
Please add the picture

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80287166-1902-b8f5-376b-89b5dcfd1b57
* Version Independent ID: e8d10b7b-0451-236f-ea7a-24bf154af500
* Content: [View current users in legacy pool](https://docs.microsoft.com/en-us/SkypeForBusiness/migration/view-current-users-in-legacy-pool)
* Content Source: [Skype/SfBServer2019/migration/view-current-users-in-legacy-pool.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/migration/view-current-users-in-legacy-pool.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@aalejandroaraujo  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@aalejandroaraujo Thank you for point that outand helping improve MS Docs.  I'll investigate and add the image soonest.

**Comment by j0rt3g4** [comment]
Thank you @lindspea, (I was not able to find anything related to it on the Docs so far), probably the author has it on his disk and forgot to publish it 👍  )

**Comment by scanum** [comment]
@aalejandroaraujo Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
