### ISSUE TITLE
Please, Confirm that delete a Team deletes completely!

### ISSUE THREAD

**Issue by FrankD004** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2571]
Hello,
could you please confirm that deleting a Team deletes *all*. The SharePoint Site Collection, the O365 Group aka Modern Group and all other parts.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf689b7-a7c1-121f-578e-029e8a89c4f0
* Version Independent ID: 7e6b449e-bd77-2fc4-2c3d-1f2e364e1b76
* Content: [Archive or delete a team in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/archive-or-delete-a-team#feedback)
* Content Source: [Teams/archive-or-delete-a-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/archive-or-delete-a-team.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@FrankD004 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
