### ISSUE TITLE
licensing requirements incorrect

### ISSUE THREAD

**Issue by aamillerMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2572]
[This](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan#licensing-and-other-requirements) section says that Audio Conferencing is required for Direct Routing.  It is not.  At best the paragraph under it could be turned into a note about enabling that specific but separate scenario.  Or a note about escalating from a 1:1 call would require Audio Conferencing.

```
Licensing and other requirements
Users of Direct Routing must have the following licenses assigned in Office 365:

Microsoft Phone System
Microsoft Teams
**Microsoft Audio Conferencing
The Audio Conferencing license is required for adding external participants to scheduled meetings, either by dialing out to them or by providing the dial-in number.**
```

**Comment by scanum** [comment]
@aamillerMSFT  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum
