### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2575]
The text
     (for example, *customers.adatum.biz). 
should be:
     (for example, *.customers.adatum.biz).

With a period between * and customers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure a Session Border Controller for multiple tenants](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-sbc-multiple-tenants)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@TorrenManson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@TorrenManson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by dariomws306** [comment]
In the following section there are also some improvements to make in the format:
https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants#create-a-trunk-and-provision-users

**Comment by scanum** [comment]
@TorrenManson Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
