### ISSUE TITLE
HDMI-CEC

### ISSUE THREAD

**Issue by Polleke66** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2578]
#2011 
@scanum, nope issue has not been resolved. The documentation of Microsoft and Logitech are still contradicting each other.

On the microsoft site there is still a Note that we should buy screens with CEC for SRS systems:

> A consumer TV used as a front of room display needs to support/enable the Consumer Electronics Control (CEC) feature of HDMI so that it can switch automatically to an active video source from standby mode. This feature is not supported on all TVs.
https://docs.microsoft.com/en-gb/MicrosoftTeams/room-systems/room-systems-v2-operations

Logitech says the exact opposite:

> Logitech SmartDock with Microsoft Surface Pro does not support CEC. It is recommended to use commercial displays with power management capabilities such as schedule on/off times.
https://support.logi.com/hc/en-us/articles/360023367273

Logitech is right, the Smartdock does not support CEC, Probably other vendors don't do it as well, but I don't have all the different SRS flavors available to me.

Regards, Paul

**Comment by scanum** [comment]
@Polleke66 Thanks for letting us know I will go ahead and solve this ASAP.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Hello  @Polleke66 
I'm not sure if I'm mistaken but please, correct me if I'm wrong.

On that note says that To use Front of Room displays the TV must be supported (by CEC feature on HDMI), and on Logitech side says "the doc with the surface doesn't support CEC" . which clearly guide us to "Front of Room" displays TVs won't support work because CEC is not supported with the Dock and Surface combination.

**Comment by Polleke66** [comment]
Hello @j0rt3g4 ,
Sorry, but I don't understand what you are trying to say. 
It seems you are trying to say that Front of Room displays are not supported by Logitech, but the only purpose of the SRS is to use Front of Room Displays. 
The problem is that Microsoft says that we should use (consumer TV) screens that support CEC (to turn the screen on and off when the surface/SRS wakes and sleeps), but that Logitech says it does not support CEC, and it clearly doesn't because I bought screens with CEC support and they are not turning on when the SRS wakes up. I had to buy Extron HD CTL 100 boxes that convert HDMI signal loss/return to CEC power off/on signals for the screens to turn off and on again.
A normal professional display that does not support CEC normally goes into standby on HDMI signal loss and wakes up on signal return. These work perfectly with the Logitech Smartdock, whereas CEC screens don't, they need the help of the Extron HD CTL 100..

CEC screens can't be controlled by the Logitech Smartdock (and probably also not by the SRS solutions from other vendors) so the note does not make sense, Microsoft is advising customers to buy screens that can't be controlled by the Smartdock and probably other SRS/MTR solutions.

Regards, Paul

**Comment by scanum** [comment]
@j0rt3g4

**Comment by rodelmurex** [comment]
i was also confuse by this until we bought the crestron HD-MD-400-C-E rx tx last year  . We are also using consumer TV works now perfectly with logitech smartdock - wake and turn off display.

**Comment by j0rt3g4** [comment]
@rodelmurex  @Polleke66  Alright then! , let's fix this!

**Comment by j0rt3g4** [comment]
Solved on PR #2941

**Comment by jambirk** [comment]
Hi @Polleke66, 

I reviewed this with the product group, and it turns out the note isn't inaccurate as much as it leaves some things unsaid.  MTR software supports CEC (and a bunch of other things too, so there's a lot more to MTR than a front of room display) but it doesn't require that feature is supported on the devices running MTR. If this optional feature is important to you, an Extron or comparable device is necessary when the device doesn't support CEC, as is a TV that supports CEC. The coming update clarifies that.

**Comment by Polleke66** [comment]
Hi @jambirk ,
The MTR software might support CEC, but the Logitech Smartdock does not. Probably most other HW that runs MTR does not support CEC. CEC is actually more an OS thing then an MTR thing, so I don't know whether MTR sw has any CEC controls in it. So it's not at all about the Front of Room Display, it's about the fact that CEC is not supported by the HW that should drive the Front of Room Display. When using the Logitech SmartDock MTR solution it is better to buy screens that don't support CEC so that there is no need to buy an Extron or similar box that converts HDMI sleep/wake into CEC signals.

I just wanted this to be clear for all the others that might mistakenly buy CEC screens to find out that they don't work properly, then have to go and find a solution, which is either replace screens or find the Extron box. That was actually quite a hard search!

Regards, Paul

P.S. If things are not clear give me a call: +31703403331

**Comment by Polleke66** [comment]
@rodelmurex 
If you want to save some money and only use the box for the CEC signalling then you can also consider the Extron HD CTL 100. It works flawless for us since May of this year.

**Comment by scanum** [comment]
@Polleke66 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
