### ISSUE TITLE
"...you can now use the cost-free Phone System Virtual User license. "

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2584]
Thanks for updating the documentation.... Where does one find/acquire the new cost-free Phone System Virtual User License mention above in the latest documentation? It does not seem to appear under licenses or Purchase Services yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts#feedback)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by abegeman** [comment]
Hi, yes I have spent the best part of an hour looking for this, the only reference I can find on the net for this license is in this document

**Comment by shivtorov** [comment]
go https://admin.microsoft.com/Adminportal/Home
In the new admin center UI, choose Billing -> Purchase services. Scroll down to the end of page, click "Add-ons" url. Then scroll to the end - you will see "Phone System - Virtual User" licenses.
If it is not there, you'll need to wait some time until it arrives to your tenant

**Comment by SvenBell** [comment]
Thank you shivtorov
It is showing up now in APAC region and looks like this:
![image](https://user-images.githubusercontent.com/52518943/60699550-c1813980-9f37-11e9-8430-7c5f2a0fa2ee.png)

**Comment by scanum** [comment]
@SvenBell Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by jambirk** [comment]
@scanum actually, the info Shivtorov provided needs to go in this article and in other places. Let's keep this open a few days while I get to that.

**Comment by jambirk** [comment]
@Waseemhashem please comment

**Comment by scanum** [comment]
@jambirk Sounds good thanks! 
@officedocsbot assign @scanum

**Comment by tonysmit** [comment]
This needs to be handed off to someone that has access to the catalog to ensure this is updated. @msmikedavis - Can you help us here get this updated in the catalog? Thanks, Tony

**Comment by tonysmit** [comment]
I'm having a conversation with the dev about this. I'm updating this because I found out yesterday that this license is different in function from a regular Phone System license and is used for resource accounts. When we check for a license in the UX, this is what it's looking for. I will report back when I get more information.

**Comment by jambirk** [comment]
This new license has some wrinkles: a certain number of licenses are free based on the number of users, we'll need to create a page that spells out these specifics.

**Comment by tonysmit** [comment]
@jambirk They can either buy a Phone System license or use a Phone System - virtual user license for resource accounts. However, for the time being, they must also have a Calling Plan. They need three licenses to be assigned to a resource account: Phone System (either), Calling Plan, Communication Credits.

**Comment by jambirk** [comment]
@Tonysmit I'm putting together a stub topic for these licenses today, will include that for sure

**Comment by tonysmit** [comment]
@jambirk - I pinged the licensing PM as well.

**Comment by msmikedavis** [comment]
Who is the licensing PM?

**Comment by tonysmit** [comment]
Jefferson.

**Comment by RussellReadMSFT** [comment]
@tonysmit @jambirk My understanding is that the requirement for these Resource Accounts to have a Calling Plan license assigned has been removed. @waseemhashem advised me of this and he's commented publicly on this via his blog article https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/Auto-Attendant-and-Call-Queues-Service-Update/ba-p/564521/page/4#comments. Look for the comments dated June 18th.

**Comment by SvenBell** [comment]
The following instruction only works when Microsoft 365 admin center is in Preview mode, the Phone System - Virtual User does does not currently list as available in normal mode. I have raised a ticket (Ticket #:15434498) to get this fixed, however a not in the documentation would save readers a lot of time:
3. Obtain a Phone System or Phone System Virtual User license. From the Microsoft 365 admin center, go to Billing > Purchase services > Add-on subscriptions and scroll to the end - you will see "Phone System - Virtual User" license. Select Buy now.

**Comment by jambirk** [comment]
Just completed a full scrub of the licensing issues for these accounts. The page will update later today, closing this issue.

**Comment by tonysmit** [comment]
Yes, last week.

**Comment by bhakuparkharsohtun** [comment]
I don't see Phone System - Virtual User  in Office 365 A5 Faculty Plan

**Comment by tonysmit** [comment]
@bhakuparkharsohtun - Does it say that A5 is supported somewhere? The only ones I know of are E-based, and F1 plans are supported. Thanks.

**Comment by scanum** [comment]
@bhakuparkharsohtun Hi, any updates on this? Thanks

**Comment by SvenBell** [comment]
New Phone System Virtual User license has disapeared for over a week now for O365 tenants that don't already have it purchased. You can't even scroll on the Purchase Services page. This maybe a region specific issue, I am in Australia. Anyone outside Australia have the same issue?

**Comment by SvenBell** [comment]
It was fixed yesterday but back on the blink again today. So frustrating!
It's like today we get the non Preview appearance in preview mode but with no scroll.
Microsoft support's workaround is to give us a 200 user 90 day Trial product key. But we need a different key for each client we are trying to deploy PSTN enabled Auto-Attendants too. 
This only seems to affect tenancies who don't have the Virtual User license already.

**Comment by bhakuparkharsohtun** [comment]
> @bhakuparkharsohtun Hi, any updates on this? Thanks
Phone System Virtual User license is now available on the A5 faculty plan. It starts rolling out since August 1, 2019.

**Comment by jambirk** [comment]
@Svenbell Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by SvenBell** [comment]
Yes, resolved now thank you.

> @SvenBell Thank you for submitting feedback. We understand that this issue has been resolved.
> Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by insane101** [comment]
We have a subscription to Office 365 A1. I cannot find this in the Add-On licensing section. Any help would be appreciated. We have are currently running Skype4Business hybrid and have some Auto-Attendants and Exchange UM setup.
