### ISSUE TITLE
Stop autostart Teams (in View horizon) for specific users

### ISSUE THREAD

**Issue by kafipause** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2587]
Hi there,

I have installed Microsoft Teams (VMWare Horizon edition) on my master image. Teams will be automatically started by a HKLM registry key.

Not all users in VDI will use Teams, so I would like to start Teams for those users in a specific group but not for the others.

This owuld require a HKCU registry key but this seems to not work.

Any suggestions how to tackle that?

Thanks
Kafipause

**Comment by scanum** [comment]
@kafipause thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
