### ISSUE TITLE
Need detail information

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#259]
Where can I get more information or a link to detailed information? A link to the predefined roles would be helpful. Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca8a34ff-3787-e1e7-10ef-a76d4cecf684
* Version Independent ID: 9efbad5a-a3f8-6c8a-480d-864f24adcefa
* Content: [Role-based access control (RBAC) for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/security/role-based-access-control-rbac)
* Content Source: [Skype/SfbServer/plan-your-deployment/security/role-based-access-control-rbac.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/security/role-based-access-control-rbac.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
Added link to RBAC roles.
