### ISSUE TITLE
Oracle SBC not listed

### ISSUE THREAD

**Issue by mxella** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2591]
Why Oracle SBCs are not listed in the beginning of the page since they are also homologated by Microsoft for Direct Routing ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df318fdb-6d58-86f8-de31-6eca533a9746
* Version Independent ID: a2248abf-bdf0-2c22-2604-74b482156684
* Content: [Configure Direct Routing](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-configure#feedback)
* Content Source: [Teams/direct-routing-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-configure.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@mxella thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
