### ISSUE TITLE
What combination of settings are allowed?

### ISSUE THREAD

**Issue by makeneko** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#260]
I am not an administrator, but I'd like to enable "allow side applications of external applications"
and I would like to inform the administrator how to set it up.

At that time, I heard that different settings will change in conjunction.
I want to know which patterns are permitted with the following settings.
(1) Allow external apps in Teams (true/false)
(2) Allow sideloading of external apps (true/false)
(3) checkboxes for third party app (enable/disable)
(4) Enable new external apps by default (true/false)

For example, it is "true, true, enable, false" in the captured image of this page.
Will not you tell me all the patterns?
(so (3) is passive, I think that it will be less than 8 patterns.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 143108bb-d6e6-48a8-a7cb-d11b89ebeaab
* Version Independent ID: 145773e2-149e-1c1c-5797-433c13f13b22
* Content: [Admin settings for apps in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/admin-settings)
* Content Source: [Teams/admin-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/admin-settings.md)
* Service: **msteams**
* Product: **unspecified**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by mplwork** [comment]
I'd also like a detailed reply. The question is very good and to the point. The effect of sideloading is rather obsure in my view (switch #2). For one it allows to use custom bots but at the same time it enables all third party apps. To me, these are two different settings. Custom bots are desired, all the other stuff is not. Seems like I can't achieve that.

**Comment by David201406** [comment]
I also would like to know how to allow to custom bots without enabling all third party apps. Is following the right way doing it:
- Turn off Allow sideloading of external apps
- Turn off any apps I don't want
- Turn off Enable new external apps by default
- Team Owner uploading a zip file directly to a team. 

Right? If not, how to enable in a organisation custom bots, without allowing all available bots?

**Comment by scanum** [comment]
@David201406 @mplwork thank you for submitting feedback.

As Ken mentioned,  the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
