### ISSUE TITLE
Misplaced step

### ISSUE THREAD

**Issue by agoldenlife** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2604]
The last line in "Save-Module"  should be place as the first in Step 8.  You can run that until the Save-Module command has been updated.  So you need to exit then restart powershell. Then run the "Save-Module" and "Install-Module" for MicrosoftStaffHub

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ff2099-489e-1bab-640a-6f92e975dbfd
* Version Independent ID: 677d5aa5-bb07-33f4-da33-7d3a3a17fcfd
* Content: [Install the StaffHub PowerShell module](https://docs.microsoft.com/en-us/microsoftteams/expand-teams-across-your-org/shifts/install-the-staffhub-powershell-module#feedback)
* Content Source: [Teams/expand-teams-across-your-org/shifts/install-the-staffhub-powershell-module.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/expand-teams-across-your-org/shifts/install-the-staffhub-powershell-module.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@agoldenlife Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by dplotnikov** [comment]
@LanaChin please merge the PR and feel free to close this issue

**Comment by LanaChin** [comment]
Merged by @MicrosoftHeidi. Closing issue.
