### ISSUE TITLE
spelling/grammar

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2607]
"premise" should be "premises".  "coexistence" should be "coexistence".  I made a pull request for those, but GitHub is having its bug where the commit button doesn't work.  Also, the graphic says "premise" when it should say "premises".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d3bc9d7-fd9e-be9f-1c46-1cc16a5c0789
* Version Independent ID: a6a46add-33de-d3b9-0169-64b642562191
* Content: [Plan a Cloud auto attendant](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-cloud-auto-attendant)
* Content Source: [Skype/SfbHybrid/hybrid/plan-cloud-auto-attendant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/plan-cloud-auto-attendant.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@jordanmills  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by dplotnikov** [comment]
@jambirk please merge the PR and feel free to close this issue
