### ISSUE TITLE
Wrong URLs

### ISSUE THREAD

**Issue by lcansby** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2608]
URLs for powershell commands are leading to pages that are not updated anymore. Example Set-CsOnlineDialInConferencingTenantSettings should go to https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinedialinconferencingtenantsettings?view=skype-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f93a7606-45b2-2032-c7b0-d79b07e65399
* Version Independent ID: 39c20b9e-713f-bf2b-9c41-3945d64d07b1
* Content: [Manage the Audio Conferencing settings for my organization in Skype for Business Online](https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/manage-the-audio-conferencing-settings-for-my-organization)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/manage-the-audio-conferencing-settings-for-my-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/manage-the-audio-conferencing-settings-for-my-organization.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@lcansby Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum
