### ISSUE TITLE
Clarification on the 5 externals per licensed internal user

### ISSUE THREAD

**Issue by CraigHumphrey** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2609]
I believe this just refers to Azure AD paid/premium features, not Teams (SharePoint, etc) specifically.

https://docs.microsoft.com/en-us/azure/active-directory/b2b/licensing-guidance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2492e210-08f9-a476-97ec-008926def961
* Version Independent ID: adcb0dd9-4a3c-b665-6e34-ce3276c89b4d
* Content: [Guest access in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-access)
* Content Source: [Teams/guest-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@CraigHumphrey Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@CraigHumphrey Thank you for reaching out and helping improve MS Docs.  Do you think adding this link to the article would help? https://docs.microsoft.com/sharepoint/create-b2b-extranet

**Comment by LolaJacobsen** [comment]
I updated the article, per PM @SomakBhattacharyya.
