### ISSUE TITLE
Welche Office Pläne bzw. Optionen sind nötig?

### ISSUE THREAD

**Issue by bauinformatiker** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#261]
Irgendwo steht, dass die Anrufoption für Videokonferenzen im E5 Plan enthalten ist. Wir haben Business Premium, ich finde aber nirgends einen Artikel, der mir sagt, wie ich die Option hinzubuchen kann.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 02354090-59c2-297d-2415-70a2cbdd15c4
* Version Independent ID: c6dfc9e6-e2f8-2f3c-6172-e15f6311d0aa
* Content: [Verfügbarkeit in Deutschland](https://docs.microsoft.com/de-de/skypeforbusiness/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-germany#feedback)
* Content Source: [Skype/SfbOnline/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-germany.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.de-DE/blob/live-sxs/Skype/SfbOnline/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-germany.md)
* Service: **skype-for-business-online**
* Product: **unspecified**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@bauinformatiker - thank you for your feedback. I am afraid my German is really bad even though I took 4 years in high school and 3 years in college (though unfortunately at my age that was a long time ago). You might try to look at this link: https://docs.microsoft.com/en-us/skypeforbusiness/what-is-phone-system-in-office-365/getting-service-phone-numbers 

I think the best solution though will be to open a service ticket from within your tenant so this can be routed right away locally for you. Here is a quick video for opening a service ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

Please let me know if there is something we can add back into the documentation once you get the issue resolved.
