### ISSUE TITLE
Freemium federation

### ISSUE THREAD

**Issue by Ayanmullick** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2613]
This document should have more details about federation with a freemium account. Can a premium account add a hotmail account as guest in it's tenant and talk to them without switching Organisations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31588a25-f3ee-e888-aa67-203be3d34489
* Version Independent ID: 3b498bcf-69a9-01ac-973a-4d5dbeea587c
* Content: [Manage external access (federation) in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Ayanmullick Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@Ayanmullick Thank you for reaching out and helping improve MS Docs.  Do you think adding this link to the article would help? - https://support.office.com/article/differences-between-microsoft-teams-and-microsoft-teams-free-0b69cf39-eb52-49af-b255-60d46fdf8a9c?ui=en-US&rs=en-US&ad=US

**Comment by Ayanmullick** [comment]
@lindspea ,  Thanks you for your response. The link you shared doesn't document how to federate a free and a premium account and or what to expect after that; specifically that a premium account can't talk to a free account without switching Organizations even if the free account is added as a guest in the premium tenant.

**Comment by tonysmit** [comment]
@Ayanmullick - I added a link from this topic over to the top just above here. Thanks, Tony.
