### ISSUE TITLE
Skype for business Server 2019 installation links missing

### ISSUE THREAD

**Issue by hirenshah1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2614]
This page should also contain link to download and install Server 2019. Isn't it ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be9f745c-5925-3a7b-9430-b5e61b4384ba
* Version Independent ID: bc23dce3-f38b-9e81-1614-d16aed1d8684
* Content: [Skype for Business Server updates](https://docs.microsoft.com/en-us/skypeforbusiness/sfb-server-updates?toc=%2FSkypeForBusiness%2Ftoc.json&bc=%2FSkypeForBusiness%2Fbreadcrumb%2Ftoc.json#feedback)
* Content Source: [Skype/SfbServer/sfb-server-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/sfb-server-updates.md)
* Product: **skypeforbusiness-server-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hirenshah1 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@hirenshah1 Thank you for your feedback, I will look into and revert soonest.

**Comment by jambirk** [comment]
fixed this already
