### ISSUE TITLE
Skype for Business Server 2019 update links missing

### ISSUE THREAD

**Issue by hirenshah1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2615]
Skype for Business Server updates heading has subheadings of Server 2015, Lync 2013 and Lync 2010. But the latest build Server 2019 installation link is missing 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4bec075-beb2-2aba-3bbb-d9b337990068
* Version Independent ID: 6eb9ba9d-413a-03e5-0a02-272ed973930d
* Content: [Skype for Business downloads and updates](https://docs.microsoft.com/en-us/skypeforbusiness/software-updates?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json)
* Content Source: [Skype/SfbServer/software-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/software-updates.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hirenshah1 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by jambirk** [comment]
fixing this in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/pull/3249
