### ISSUE TITLE
Which tenants have access to this currently?

### ISSUE THREAD

**Issue by Skempf94** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2616]
In this article it states:
'In the left navigation, go to Voice &gt; Phone numbers, and then click Get new numbers.'

Is this live yet? As I cannot see the 'Phone numbers' location in my own tenant at the moment. Is this only available for select tenants?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e37f13b-cb86-955e-147c-fa916da063f9
* Version Independent ID: 4dd77188-abcb-fae2-3cf3-12b82b591bad
* Content: [Getting phone numbers for your users](https://docs.microsoft.com/en-us/microsoftteams/getting-phone-numbers-for-your-users#feedback)
* Content Source: [Teams/getting-phone-numbers-for-your-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/getting-phone-numbers-for-your-users.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Skempf94 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
