### ISSUE TITLE
Context information is missing

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#262]
Context information is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21a56928-a6c7-51f3-01ad-de26b518b082
* Version Independent ID: 1f2581bd-7942-f55e-663a-18d324c83558
* Content: [Configure SharePoint Server to search for archived Skype for Business data](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/integrate-with-exchange-server/sharepoint-to-search-for-archived-data)
* Content Source: [Skype/SfbServer/deploy/integrate-with-exchange-server/sharepoint-to-search-for-archived-data.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/integrate-with-exchange-server/sharepoint-to-search-for-archived-data.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
This is not an actionable comment. Ironically, it's inactionable because the context for which information is missing is itself missing.

**Comment by kenwith** [comment]
Not clear what this issues is regarding. Closing it but re-open if there is more specific information.
