### ISSUE TITLE
Service numbers/virtual phone system license

### ISSUE THREAD

**Issue by mbigus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2628]
Beginning of doc states: "If you are assigning a Microsoft service number instead, you need to acquire and assign the following licenses to your resource account (Office 365 Enterprise E1, E3 or E5, with the Phone System add-on)." 

Yet the resource  accounts page listed above (https://docs.microsoft.com/en-US/microsoftteams/manage-resource-accounts ) - states that a virtual user phone system license can be used alone at no cost for a service number resource account. 

"If you are assigning a phone number to a resource account you can now use the cost-free Phone System Virtual User license. This provides Phone System capabilities to phone numbers at the organizational level, and allows you to create auto attendant and call queue capabilities."

Which is correct? Should explain somewhere how/when virtual licenses can be used or be more clear on this page if referring to the regular or virtual phone system license. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a42f9e2c-aeee-76c4-620a-668cce21ba10
* Version Independent ID: 6ff06eab-9c80-9c30-95ef-c17e157fbea1
* Content: [Set up a Cloud auto attendant](https://docs.microsoft.com/en-US/microsoftteams/create-a-phone-system-auto-attendant#feedback)
* Content Source: [Teams/create-a-phone-system-auto-attendant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-auto-attendant.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/2633 resolves

**Comment by jambirk** [comment]
There is more info on the virtual user license pending, but definitely the right call to remove that E1 E3 E5 reference. Added info will be published as it becomes available.

**Comment by tonysmit** [comment]
@jambirk - You're correct because they can use a Small Business Essentials license and add Phone System and a Calling Plan. Please add that to the doc. Thanks.

**Comment by jambirk** [comment]
Closing this issue, I've done a full scrub on Licensing for  CQ/ AA resource accounts, update will publish later today.
