### ISSUE TITLE
How to run diagnostics test?

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#263]
How to run diagnostics test?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7602e86d-8136-d297-22ec-d420e7069abe
* Version Independent ID: ff6109bc-1f25-5792-4ecf-d55b30275548
* Content: [Test Device](https://docs.microsoft.com/en-us/skypeforbusiness/help-topics/help-lscp/test-device)
* Content Source: [Skype/SfbServer/help-topics/help-lscp/test-device.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/help-topics/help-lscp/test-device.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by kenwith** [comment]
There is a link now in related links on creating a new test. Thanks.
