### ISSUE TITLE
Screenshot shows old content

### ISSUE THREAD

**Issue by svenseidenberg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2630]
The screenshot below the "Retrieve Teams data from the audit log" shows an old version of the admin center I think this could confuse people looking for how to find things.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 37e51e97-ff97-c5eb-6517-21ce9a563ca4
* Version Independent ID: d3dc21b2-d90a-fbe7-8473-fff0b55feafb
* Content: [Suchen nach Überwachungsprotokoll für Ereignisse in Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/audit-log-events#feedback)
* Content Source: [Teams/audit-log-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audit-log-events.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@svenseidenberg Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Solving and updating issue #2630 with PR #2746

**Comment by scanum** [comment]
@svenseidenberg Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
