### ISSUE TITLE
OS for Domain Controllers

### ISSUE THREAD

**Issue by joaolloureiro** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2632]
Please change the following section to include reference that Windows Server 2019 is also supported as per below. You can contact either me either Shirmay Chang from SFB Server test team to confirm this scenario was tested.

OS for Domain Controllers
So, what Domain Controller OS can be used? We have the following list:
•	Windows Server 2019
•	Windows Server 2016
•	Windows Server 2012 R2
•	Windows Server 2012
•	Windows Server 2008 R2
•	Windows Server 2008
Now, the domain functional level of any domain you deploy Skype for Business Server 2015 into, and the forest functional level of any forest you deploy Skype for Business Server 2015 into, have to be one of the following:
•	Windows Server 2019
•	Windows Server 2016
•	Windows Server 2012 R2
•	Windows Server 2012
•	Windows Server 2008 R2
•	Windows Server 2008
•	Windows Server 2003

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 854766da-e557-2338-0aea-262e67a0b984
* Version Independent ID: 20b49404-62d7-83f8-118d-b8189b87da0b
* Content: [Environmental requirements for Skype for Business Server 2015](https://docs.microsoft.com/en-us/SkypeForBusiness/plan-your-deployment/requirements-for-your-environment/environmental-requirements#AD)
* Content Source: [Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/environmental-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/environmental-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@joaolloureiro Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jambirk** [comment]
@MicrosoftHeidi may have something to add here

**Comment by scanum** [comment]
@joaolloureiro Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
