### ISSUE TITLE
Common Area Phone

### ISSUE THREAD

**Issue by BRobinson85** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2637]
Is shared line appearance possible on common area phone?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3dd879-564e-62ca-2095-3ef6ae4fab2d
* Version Independent ID: 8ed3dff3-b2b8-b3db-6db9-6bbecdb6cf5c
* Content: [Shared line appearance in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/shared-line-appearance)
* Content Source: [Teams/shared-line-appearance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/shared-line-appearance.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@BRobinson85 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
