### ISSUE TITLE
Need update

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#264]
It would be nice if DFS-R is discussed here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3ca816c-d7cf-500e-4710-8693b584b5ab
* Version Independent ID: 511bacc3-dd79-52bd-a4a2-baa667693b68
* Content: [File sharing high availability in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/high-availability-and-disaster-recovery/file-sharing)
* Content Source: [Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/file-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/file-sharing.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by dariomws306** [comment]
Hi @nsshommo , you should use DFSN and DFSR, install both roles, etc. The article redirect you to https://go.microsoft.com/fwlink/?LinkId=524384 which explains this.
