### ISSUE TITLE
Conflicting information about Meetings migration

### ISSUE THREAD

**Issue by bertrandsophie** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2643]
It is written in this page in note 2 about TeamsOnly mode:
 If desired, you can leave these meetings as Skype for Business meetings either by specifying -MigrateMeetingsToTeams $false when granting TeamsUpgradePolicy

However, in the description of the Grant-CsTeamsUpgradePolicy, you can read about  -MigrateMeetingsToTeams : 
This parameter can only be true if the mode of the specified policy instance is either TeamsOnly or SfBWithTeamsCollabAndMeetings, and if the policy instance is being granted to a specific user

What is the correct information ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49921e8a-55ac-f547-d4e2-d329f5089c2e
* Version Independent ID: 91c3433a-3684-95cd-3426-4a5877b33106
* Content: [Migration and interoperability guidance for organizations using Teams together with Skype for Business](https://docs.microsoft.com/en-us/microsoftteams/migration-interop-guidance-for-teams-with-skype)
* Content Source: [Teams/migration-interop-guidance-for-teams-with-skype.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/migration-interop-guidance-for-teams-with-skype.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@bertrandsophie Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
I would think that the 1st thing to solve is what are the lists of instances of TeamUpgradePolicy are for SfB Online, https://docs.microsoft.com/powershell/module/skype/get-csteamsupgradepolicy?view=skype-ps

If after using 
```Powershell
Get-CsTeamsUpgradePolicy
```
and you find out that information for each user: and if it's TeamsOnly or SfBWithTeamsCollabAndMeetings, then you can just use ```true```, if it's any other you can use false.

Now if you apply a change on the UpgradePolicy for teams that are no-showed here you'd get an error.

Those policies are Tenant wide a User wide, tenant wide eats "user wide" so the remaining would be the "user's one at the end"

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
