### ISSUE TITLE
.NET 4.7 isn't clearly identified as a requirement.

### ISSUE THREAD

**Issue by NicholasBurkhammer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2644]
On Windows Server 2016, if you do not have .NET 4.7 installed, the installer with terminate and tell you it is required.  The section that identifies software that must be installed states we work with a number of .NET Framework versions.  It does not explicitly state that you need to have 4.7 in order to run Setup.  This should be documented so that users performing deployments can proactively prepare to have that installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd40e9bf-6fb5-b597-5494-b9ccc17e4660
* Version Independent ID: 46d0d0a0-2ea9-efbd-1ef8-63686f7fef62
* Content: [System requirements for Skype for Business Server 2019](https://docs.microsoft.com/en-us/skypeforbusiness/plan/system-requirements#feedback)
* Content Source: [Skype/SfBServer2019/plan/system-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/plan/system-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@NicholasBurkhammer Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@NicholasBurkhammer Thank you for pointing this out. Would you agree with this note suggestion: "Without .NET 4.7 installed, the installer will terminate. .NET 4.7 is required in order to run Setup."

**Comment by lindspea** [comment]
@NicholasBurkhammer Thank you. I see it's been updated in the interim under: Microsoft .NET Framework: "Skype for Business Server requires Microsoft .NET Framework 4.7 though, so you'd probably need to update it. You can find the update here."

**Comment by scanum** [comment]
@NicholasBurkhammer Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
