### ISSUE TITLE
Voice > Phone numbers option Missing

### ISSUE THREAD

**Issue by mymebenha** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2645]
The Voice &gt; Phone numbers option is missing from my portal.  Instead I need to go to the Legacy portal to assign numbers.  Why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c67496-cace-f833-7cfc-dca7722fef3e
* Version Independent ID: 5a14f81c-529c-4971-5ce8-39633834d4d3
* Content: [Assign, change, or remove a phone number for a user](https://docs.microsoft.com/en-us/microsoftteams/assign-change-or-remove-a-phone-number-for-a-user#feedback)
* Content Source: [Teams/assign-change-or-remove-a-phone-number-for-a-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-change-or-remove-a-phone-number-for-a-user.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by tonysmit** [comment]
This feature is only available to TAP and Early Adopters. Thanks.

**Comment by derekhansell** [comment]
This option is still missing...
