### ISSUE TITLE
Microsoft Teams deployment clean up 

### ISSUE THREAD

**Issue by joshrpg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2646]
It should be noted that this script will only work on user-based installs. It does not work on installs with the "ALLUSER=1" as it only looks in appdata, not program files. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Microsoft Teams using MSI via SCCM](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment#feedback)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@joshrpg Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by voytas75** [comment]
@scanum Are the results of the investigation already available?

**Comment by lindspea** [comment]
@voytas75 Are you suggesting adding a note to the article?

**Comment by voytas75** [comment]
Yeas, please. If you have those results, add them.

**Comment by lindspea** [comment]
@voytas75 Please see related doc issue https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2868.

**Comment by voytas75** [comment]
@lindspea thx

**Comment by scanum** [comment]
@joshrpg Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
