### ISSUE TITLE
Unacceptable search limitation

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2647]
The fact that searching is limited to the beginning of the Team name and therefore cannot find a word that is in a team name with multiple words is totally unacceptable. This should never had made it into production with this kind of limitation. Basic functionality like this is expected in all products when they are in the beta review process. Please get this fixed ASAP. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b51b67a-d89c-723f-3520-87cb2dc93b90
* Version Independent ID: 78d10cbc-d75b-2b02-d49c-2c3fe1579807
* Content: [Manage teams in the Microsoft Teams admin center](https://docs.microsoft.com/en-us/microsoftteams/manage-teams-in-modern-portal#search)
* Content Source: [Teams/manage-teams-in-modern-portal.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-teams-in-modern-portal.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@DeanGross Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jambirk** [comment]
@DeanGross The limitation you describe is a function of the app, the documentation feedback isn't the right venue for submitting an improvement suggestion for the Teams client. 

@scanum can you please post the recommended channel for client improvements? This also sounds like it may be a possible addition to the Known Issues article until the product group makes a change here.

**Comment by DeanGross** [comment]
@jambirk  I agree, but this issue has been open for a long time with no action, https://microsoftteams.uservoice.com/forums/555103-public/suggestions/31907344-search-all-the-words-in-a-team-name-when-searching. I'm hoping that be opening it here also that it gets the attention that it deserves.

**Comment by jambirk** [comment]
@DeanGross That's not how things work, we don't have the ability to escalate priority on a feature or improvement suggestion.
