### ISSUE TITLE
Need list of diagnostic ID

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#265]
Can you add the list of the error codes called diagnostic ID? Or can you tell where can it be found? Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9ada06b-e018-969a-69fe-77be812a952a
* Version Independent ID: d289b855-df31-2eb8-9c62-8b7afe554dc1
* Content: [Peer-to-Peer Session Detail Report in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/manage/health-and-monitoring/peer-to-peer-session-detail-report)
* Content Source: [Skype/SfbServer/manage/health-and-monitoring/peer-to-peer-session-detail-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/health-and-monitoring/peer-to-peer-session-detail-report.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
A comprehensive listing of diagnostic IDs is not available.
