### ISSUE TITLE
http://SkypeandTeams.com Not Working

### ISSUE THREAD

**Issue by jaysonvelasco** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2653]
Link not working.

404 Web Site not found.
You may be seeing this error due to one of the reasons listed below :
Custom domain has not been configured inside Azure. See how to map an existing domain to resolve this.
Client cache is still pointing the domain to old IP address. Clear the cache by running the command ipconfig/flushdns.
Checkout App Service Domain FAQ for more questions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7163e6d-66a6-da7e-ea25-4c8bed58f3fd
* Version Independent ID: d3d57584-d218-7ef2-996c-93a26f3a0f76
* Content: [Upgrade from Skype for Business to Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/tutorial-journey-skypeforbusiness-to-teams?tutorial-step=9#feedback)
* Content Source: [Teams/Tutorial-Journey-SkypeforBusiness-to-Teams.yml](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/blob/live/Teams/Tutorial-Journey-SkypeforBusiness-to-Teams.yml)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **tbinder**

**Comment by scanum** [comment]
@jaysonvelasco Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@LolaJacobsen please merge the PR and feel free to close the issue

**Comment by scanum** [comment]
@jaysonvelasco Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
