### ISSUE TITLE
Reason for Block

### ISSUE THREAD

**Issue by ICT4ALL** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2655]
Is the reason Safeguarding of pupils or is it for Financial reasons.  How do education users go about getting the correct licence?  Can only one user in an School be assigned the relevant licence?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fea6bb01-9614-b8a1-2d18-94fea656cfda
* Version Independent ID: 5b27d62e-f4a2-9f65-8fff-9da6d58e036c
* Content: [Blocked user licenses for Skype Meeting Broadcast](https://docs.microsoft.com/en-gb/SkypeForBusiness/set-up-your-network-for-skype-meeting-broadcast/blocked-user-licenses-for-skype-meeting-broadcast#feedback)
* Content Source: [Skype/SfbOnline/set-up-your-network-for-skype-meeting-broadcast/blocked-user-licenses-for-skype-meeting-broadcast.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-your-network-for-skype-meeting-broadcast/blocked-user-licenses-for-skype-meeting-broadcast.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@ICT4ALL thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
