### ISSUE TITLE
Gpudate.exe /force

### ISSUE THREAD

**Issue by crmlgb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2660]
This command is wrong.
should be Gpupdate /force. There is a p lost which makes command not running.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6c3533f-ff4a-cbb5-5e3b-055756def68e
* Version Independent ID: 0f8acc5e-138e-61f1-a35c-4caa50899d83
* Content: [Configuring port ranges and a Quality of Service policy for your clients](https://docs.microsoft.com/en-us/skypeforbusiness/manage/network-management/qos/configuring-port-ranges-for-your-skype-clients#feedback)
* Content Source: [Skype/SfbServer/manage/network-management/qos/configuring-port-ranges-for-your-skype-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/network-management/qos/configuring-port-ranges-for-your-skype-clients.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@crmlgb Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jambirk** [comment]
@scanum bring questions to me if you have them

**Comment by crmlgb** [comment]
Hi James,
there is a wrong command showing microsoft docs,

Gpudate.exe /force (#2660)

it should be Gpupdate /force. There’s a “p” missing.

thanks 
crmlgb@gmail.com


在 2019年7月20日，上午12:02，James Birkinshaw <notifications@github.com> 写道：

@scanum bring questions to me if you have them

**Comment by dplotnikov** [comment]
@jambirk I've just made a change, please merge the PR and feel free to close this issue

**Comment by scanum** [comment]
@crmlgb Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
