### ISSUE TITLE
Addition of Audio Conferencing

### ISSUE THREAD

**Issue by umayrsufi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2661]
Audio Conferencing is now generally available for Office 365 Business Premium plans, allowing users to add the dial-in feature to their tenants. This should be reflected on this page as it could help guide decisions on how to use the product. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 177f5cdc-62a7-327f-64e8-97c5b01b70fc
* Version Independent ID: 0aa4a92b-26c5-29eb-5ebd-0117c35c177a
* Content: [Office 365 Business Premium ](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/office-365-business-premium)
* Content Source: [Teams/teams-add-on-licensing/office-365-business-premium.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/office-365-business-premium.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@umayrsufi Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tonysmit** [comment]
@umayrsufi - It says it here: To get Audio Conferencing:
Sign in to the Microsoft 365 admin center.
Go to Billing > Purchase services > Add-on subscriptions.
You'll see the prices and option to buy Audio Conferencing.

**Comment by umayrsufi** [comment]
Awesome!

Thanks for adding this in.

Umayr Sufi  |  Cloud Technical Expert – Palo Alto, CA
umayr.sufi@microsoft.com<mailto:umayr.sufi@microsoft.com> |  650.798.2900 work | linkedin.com/in/umayrsufi<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Flinkedin.com%2Fin%2Fumayrsufi&data=02%7C01%7CUmayr.Sufi%40microsoft.com%7Cb3bfc50e602d4c32dabe08d6a43185f6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636876930274406068&sdata=E%2FpRsYQahTDLTusfqc7Nf1QleDaJGeWBkvu5h4F9upY%3D&reserved=0>
Microsoft
[cid:image003.jpg@01D4D5D7.538420C0]
Privacy Statement<https://go.microsoft.com/fwlink/?LinkId=521839>
Microsoft Corporation
One Microsoft Way
Redmond, WA 98052
