### ISSUE TITLE
Receiving an error when trying to create the installation media

### ISSUE THREAD

**Issue by RCGaber** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2663]
Has anyone been able to resolve this issue?

Mount-WindowsImage : The parameter is incorrect.
At C:\CreateSrsMedia.ps1:1422 char:13
+             Mount-WindowsImage -ImagePath "$NewInstallWim" -Path "$In ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Mount-WindowsImage], PSArgumentException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.MountWindowsImageCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console](https://docs.microsoft.com/en-us/microsoftteams/room-systems/console#feedback)
* Content Source: [Teams/room-systems/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/console.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@RCGaber thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
