### ISSUE TITLE
Assigning Registrar Pools

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2668]
The instructions indicating the need to manually assign a specific registrar pool seem to point out a pool that no longer exists. The step should be clarified to have the user ensure that all new MTR accounts are created in the same RegistrarPool. That's all the matters, right? No need to list a specific pool in the docs here - it'll just confuse people.

Error: Service identifier cannot be found for registrar pool "sippoolbl20a04.infra.lync.com".  Run Get-CsService -Registrar to enumerate the available registrars. (Fun fact - Get-CsService isn't a valid command for S4BO tenancies)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Office 365](https://docs.microsoft.com/en-us/microsoftteams/room-systems/with-office-365)
* Content Source: [Teams/room-systems/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/with-office-365.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@pyoungberg  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@LanaChin

**Comment by cbrandon2** [comment]
This appears to not have been resolved yet. Any update on this? I am having this issue as well.

**Comment by lindspea** [comment]
@cbrandon2 @pyoungberg We are just awaiting PR approval at which time the changes will reflect in the article soon after. @sohailta

**Comment by jambirk** [comment]
@pyoungberg We appreciate the suggestion and your help in trying to make the documentation better.   However, the product group has declined to make this update as suggested. For what it's worth, all the articles on account creation for MTR are slated for major update soon.

**Comment by crshovrd41** [comment]
So... What's the solution? I'm just trying to get this setup and it seems the step is wrong... but no solution is given.
