### ISSUE TITLE
Show GUI steps for creating MTR account

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2669]
I don't see any specific requirement to use PowerShell to make MTR accounts based off the variables I've seen used, save setting the password to never expire Please include a section that shows how to make these accounts through the O365 Admin Center and ExO Admin Center. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Office 365](https://docs.microsoft.com/en-us/microsoftteams/room-systems/with-office-365)
* Content Source: [Teams/room-systems/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/with-office-365.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@pyoungberg  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jambirk** [comment]
@pyoungberg The account creation process will be undergoing big changes soon, and at that time we'll change the documentation to reflect that. In the meantime the plan is to leave things as they are.
