### ISSUE TITLE
Azure AD Module v2.0 not supported?

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2670]
Why isn't the Azure AD Module v2.0 supported here? Here's the instructions for setting a password to never expire on a user account: https://docs.microsoft.com/en-us/office365/admin/add-users/set-password-to-never-expire?view=o365-worldwide#set-a-password-to-never-expire. Seems important to show AADv2 commands as AADv1/MSOnline commands are steadily being depreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Office 365](https://docs.microsoft.com/en-us/microsoftteams/room-systems/with-office-365)
* Content Source: [Teams/room-systems/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/with-office-365.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@pyoungberg  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jambirk** [comment]
@pyoungberg 
Those commands are not yet tested and verified for Microsoft Teams Rooms. When that happens, we'll update the documentation and that command set will be the preferred and documented method. The full deprecation of the 1.0 command set won't happen until well after CY 2020, so there is plenty of time.
