### ISSUE TITLE
Teams retention during hybrid

### ISSUE THREAD

**Issue by Absarm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2671]
4 Retention will use a shadow mailbox for the online user to store messages. Microsoft Teams Supports eDiscovery for Teams user in an Exchange Hybrid environment.

the ref link of Techcommunity still states that Teams retention can't be applied for shadow mailbox, through practically it can be applied, as I am awaiting result for use case, can you check/confirm whether Teams retention policy capability has been added and will process deletion as defined in Teams retention, if yes, please update the technote as well to reflect same

**Comment by scanum** [comment]
@Absarm Please link the document you are referring, thanks!

**Comment by Absarm** [comment]
https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact

https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/Microsoft-Teams-supports-eDiscovery-for-Teams-users-in-a/ba-p/200009

**Comment by j0rt3g4** [comment]
Please @scanum  could you please get involve the author of the threat? thank you

**Comment by scanum** [comment]
Hi @dstrome Could you please aid us in next steps of issue resolution. Thanks!

**Comment by dstrome** [comment]
@scanum  - taking a look.

**Comment by j0rt3g4** [comment]
Thank you @dstrome

**Comment by scanum** [comment]
@dstrome Hi David, hope you are doing well. Any updates on this issue? Thanks!

**Comment by scanum** [comment]
@dstrome Following up on this issue. Please let me know if there are any updates. Thanks!

**Comment by scanum** [comment]
@dstrome Following up on this issue. Thanks!

**Comment by scanum** [comment]
@dstrome Following up on this issue. Thanks!

**Comment by dstrome** [comment]
@Ansuman777 - looks like you're the owner of the Tech Community post referenced in this issue. Can you please take a look at the request above and let us know whether the docs article or the Tech Community post is correct?

**Comment by scanum** [comment]
@Ansuman777 Any updates on this? thanks!

**Comment by scanum** [comment]
@Ansuman777 Any updates on this? thanks!

**Comment by dstrome** [comment]
I can no longer see references to shadow mailboxes in the tech community blog post referenced in the original issue. If there's still confusion, please create a new comment with the specific text that's conflicting between the help article and the tech community post. thanks.
