### ISSUE TITLE
[LOC] Broken links and image - guest-access-checklist.md

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2672]
**FileName:** guest-access-checklist.md
**Author:** lanachin
**GH topic:** https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md

**Broken links:**

Link Text | Link URL
-- | --
Email one-time passcode authentication   (preview) | one-time-passcode.md
Allow or block invitations to B2B users   from specific organizations | allow-deny-list.md

![image](https://user-images.githubusercontent.com/47977325/61444756-4f9feb80-a94c-11e9-8e81-6e98687914a0.png)

**Broken image:**

Image ALT text | Image name
-- | --
External collaboration settings | control-who-to-invite.png

![image](https://user-images.githubusercontent.com/47977325/61444665-1d8e8980-a94c-11e9-830c-d9b776c0ef81.png)

**Comment by scanum** [comment]
@OfficeGlobal  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@OfficeGlobal Thank you for your feedback. The links are correct my side, please confirm on your side.

**Comment by OfficeGlobal** [comment]
Hello @Reeced40 , I checked the links at live page (https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist)
 - link _Allow or block invitations to B2B users from specific organizations_ still redirects to 404

 - second link and image seems to be fixed

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
