### ISSUE TITLE
Cannot open OneNote with Chrome

### ISSUE THREAD

**Issue by decatur** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2673]
We are not able to open OneNote documents in Teams web interface with Chrome 71.0.
The page is simple not loaded, the spinner keeps spinning.
The JavaScript console shows multiple errors, including

`wacBoot.min.js:8 Uncaught ReferenceError: onenoteSync is not defined`

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Bekannte Probleme für Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/known-issues#feedback)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@decatur  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@decatur thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
