### ISSUE TITLE
1:1 Federation Chat doesnt seem to work

### ISSUE THREAD

**Issue by AndrewCalvo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2677]
I've done everything suggested in this document for 1:1 Federated chat to work, and nothing seems to work. Each time an error appears stating "Failed to send. We ran into a problem sending this message. Try again later". I've test this with three or four different O365 Tenants that have Teams functional internally - it's the external federation that seems to not be working. Additionally, the scenario 1, 2 and 3 do not make sense - how can open federation on one tenant allow incoming and outgoing messages, yet the second tenant requires the domain to be added in "Allow"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external access (federation) in Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/manage-external-access?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@AndrewCalvo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tonysmit** [comment]
@nomorephones - can you help out here please?

**Comment by tonysmit** [comment]
@AndrewCalvo - Did you wait 24 hours to test it?

**Comment by tonysmit** [comment]
@AndrewCalvo - What apps are you trying to get working?

**Comment by AndrewCalvo** [comment]
@tonysmit I did wait 24 hours, and it seems to be working between certain tenants. I was under the impression that it would be instantaneous, it didn't indicate that it may take 24 hours to take effect. One tenant it is not working through is one that is on the GCC, could that be a limitation whereas a Non-GCC and GCC tenant cannot have 1:1 Federation? 

The app we were trying to get working is just basic Microsoft Teams chat, either via web interface or smartphone app.

In addition, I'll reiterate that the instructions are confusing in **Scenario 1**; the instructions state "It lets people in your organization find, call and send instant messages, as well as set up meetings with people external to your organization". Yet the next sentence states external domains must be setup to allow your domain. If both organizations are setup as "Open Federation" then the requirement to "allow your domain" is not relevant.

**Comment by tonysmit** [comment]
@AndrewCalvo - Thanks for the explanation and details. I will make sure to include a note that replication across DCs may take up to 24 hours. I'm not sure of the limitations with GCC, but I will ping the PM. 

For the last part in **Scenario 1**: I copied this sentence from the doc.
"When you use this set up, your users can communicate with ALL external domains that are running Teams but have set up their domain/organization to allow your domain."

The other Teams domain/organization must also either being using Open Federation OR have your domain listed as an allowed domain. I don't see the problem with that sentence to be honest.

**Comment by AndrewCalvo** [comment]
@tonysmit - By adding that additional sentence "The other Teams domain/organization must also either be using Open Federation OR have your domain listed as an allowed domain" clears up any confusion. 

Due to the text "..but have setup their domain/organization to allow your domain" I read **Scenario 1:** as requiring Tenant B needing to be setup as specified as **Scenario 2:**. In order words, two Open Federation tenants cannot communicate with each other - unless one of the two tenants is utilizing the Allow or Block scenario. 

Thank you for clarifying this for me.

**Comment by tonysmit** [comment]
@AndrewCalvo - Of course and thanks for the feedback. It makes it very clear now. Appreciate it.
