### ISSUE TITLE
TOC says PowerShell 3.0, Content is for 5.1

### ISSUE THREAD

**Issue by danyeh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2679]
TOC says PowerShell 3.0, Content is for 5.1. TOC should not mention version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d14a27a6-81b9-c7e7-d16a-08366aa9bb13
* Version Independent ID: 67c83b4c-8a33-8715-7f58-7e4c00165154
* Content: [Download and install Windows PowerShell 5.1](https://docs.microsoft.com/en-us/skypeforbusiness/set-up-your-computer-for-windows-powershell/download-and-install-windows-powershell-5-1#feedback)
* Content Source: [Skype/SfbOnline/set-up-your-computer-for-windows-powershell/download-and-install-windows-powershell-5-1.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-your-computer-for-windows-powershell/download-and-install-windows-powershell-5-1.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@danyeh Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@danyeh Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
