### ISSUE TITLE
Purchase instructions only work when Microsoft 365 admin center is in Preview mode

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2680]
The following instruction only works when Microsoft 365 admin center is in Preview mode i.e. the Phone System - Virtual User does not currently list as available in normal mode. 
I have raised a ticket (Ticket #:15434498) to get this fixed, however a note in the documentation would save readers a lot of time:

> 3. Obtain a Phone System or Phone System Virtual User license. From the Microsoft 365 admin center, go to Billing &gt; Purchase services &gt; Add-on subscriptions and scroll to the end - you will see "Phone System - Virtual User" license. Select Buy now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@SvenBell Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@jambirk please merge the PR and feel free to close this issue

**Comment by jambirk** [comment]
Purchase instructions were already in the article, line 74
