### ISSUE TITLE
Assign a policy package to multiple users

### ISSUE THREAD

**Issue by alanbmhs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2685]
There is an error or rather omission from point 3 of this section. It should read:
"In the Manage users pane, search for the user by display name or by user name, select the name, and then click Add. Repeat this step 1,749 times or whatever is the number of users in your organisation that you want to add."

Thanks for making it easier "when managing policies for groups of users across your organization."

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3f54e11-f5b6-1ab9-6148-f053c66dd79b
* Version Independent ID: 27b514bf-1500-ef6d-ac11-e1860416ec04
* Content: [Manage policy packages in Microsoft Teams](https://docs.microsoft.com/en-nz/MicrosoftTeams/manage-policy-packages)
* Content Source: [Teams/manage-policy-packages.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-policy-packages.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@alanbmhs Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tonysmit** [comment]
@LanaChin - Can you follow up with this and make the correction please? Thanks, Tony

**Comment by dasGstehtfuerGoennung** [comment]
I can't decide which is funnier: this issue or the section it refers to.

**Comment by bamslib** [comment]
There should be a PowerShell cmdlet to make this easier, or a way to accept csv containing users id.

**Comment by filtavaz** [comment]
Or according to licence?

**Comment by tonysmit** [comment]
https://docs.microsoft.com/en-us/powershell/module/teams/new-csbatchpolicypackageassignmentoperation?view=teams-ps
New-CsBatchPolicyPackageAssignmentOperationThis cmdlet submits an operation that applies a policy package to a batch of users in a tenant. Provide one or more user identities to assign the package.

**Comment by tonysmit** [comment]
Content is being updated. Here is a doc as well that does this:  https://docs.microsoft.com/en-us/microsoftteams/assign-policies#assign-a-policy-package-to-a-batch-of-users
