### ISSUE TITLE
Icon missing if user is in different Tenant with Teams-Client

### ISSUE THREAD

**Issue by ihloff** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2686]
If you switch the tenant with your teams desktop client, the add-in for teams is missing. Steps to reproduce:
- Close Outlook
- Switch tenant in teams to a tenant that is not your "home" / where you are a guest-user
- Start Outlook again -&gt; Teams-Meeting-Button is missing

If you switch back to your home tenant and restart Outlook -&gt; Teams Meeting Button is available.

My environment: Win 10 1809, Office 365 Pro Plus Monthly Channel.

If this is a common problem it should be in the troubleshooting section of this page.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Verwenden des Microsoft Teams-Besprechungs-Add-Ins in Outlook](https://docs.microsoft.com/de-de/microsoftteams/teams-add-in-for-outlook)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@ihloff Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@ihloff this one looks like a product issue. Did you file the issue to Microsoft?

**Comment by dplotnikov** [comment]
@ihloff I assume you've filed the issue so this issues will be closed shortly

**Comment by ihloff** [comment]
Hi, I thought it would be a good addition to the section "Troubleshooting". I'm not sure if it is a bug or a missing feature of the product itself - I didn't file this to Microsoft but I'll do so next week.

**Comment by scanum** [comment]
@ihloff We appreciate any feedback that improves the content in the Microsoft docs  and will consider adding this in the future.
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by ihloff** [comment]
I just got the information from Microsoft Support that it is not a bug. In this case I think it should be added in the documentation.

**Comment by dplotnikov** [comment]
@ihloff do you have any official confirmation?

**Comment by ihloff** [comment]
@dplotnikov 
I opened a ticket at the support ( Ticket #:15956324) and got this information. Don't know if this official enough but I don't have any other ways to get an answer from Microsoft.
