### ISSUE TITLE
Add UDP ports note for Transport Relay

### ISSUE THREAD

**Issue by ilantz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2687]
We should document that turning on "Insert Quality of Service (QoS) markers for real-time media traffic" will also enable communication to the Transport Relay with port 3479 (Audio) ,3480 (Video) and 3481 (Sharing)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Manage meeting settings](https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ilantz Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@LanaChin please merge the PR and feel free to close this issue

**Comment by scanum** [comment]
@ilantz Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by TheITguy666** [comment]
The information might be outdated.
I have customer tenants with QoS disabled, but I can see on the meeting clients network traffic those UDP ports in use...
