### ISSUE TITLE
Can we avoid sending data with feedback?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2688]
Have you though about this from the data leaking point of view? Why not allowing us to give feedback to you, but without sending the data from the session. Or can you at least describing what information will be delivered to Microsoft but also to Microsoft's subcontractors by this feedback feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bf3bc26-4cac-56c0-8669-6540adf3c502
* Version Independent ID: bd7cd483-e40e-88c2-b9ee-b21a9ea73005
* Content: [Manage feedback policies in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-feedback-policies-in-teams)
* Content Source: [Teams/manage-feedback-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-feedback-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by no2cl** [comment]
Can't find that PowerShell command in Teams module! New-CsTeamsFeedbackPolicy
Where is it available?!

**Comment by Petri-X** [comment]
> Can't find that PowerShell command in Teams module! New-CsTeamsFeedbackPolicy
> Where is it available?!

At least I found it from here:
[Manage Skype for Business Online with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell)
It is not available on the Teams module. Which sounds of course very logically :D

**Comment by no2cl** [comment]
Thks!

The Microsoft Logic's amazing... ;-)

**Comment by j0rt3g4** [comment]
Added into MS documentation, PR #2869

**Comment by j0rt3g4** [comment]
@rpodric It doesn't make sense that is on sfB module, but it's the way it is so far and is not on our power to change it, at least we create another issue.

**Comment by rpodric** [comment]
But what version?  The latest one available at this time dates to several months ago, well before the preview was announced. The command isn't available in that one.

**Comment by j0rt3g4** [comment]
Latest version:
- https://www.powershellgallery.com/packages/MicrosoftTeams/1.0.1
- https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/Microsoft-Teams-PowerShell-Module-General-Availability/ba-p/480934

**Comment by rpodric** [comment]
That's Teams.

I'm not having any problem finding the SfB download. I'm just asking what specific version you think is the one actually containing the command. The one I mentioned above is not it, barring something very strange.

That's why I asked if there was a more contemporary version that's subsequently been pulled. That would make sense.

**Comment by j0rt3g4** [comment]
Well, latest search for it and download it.

**Comment by rpodric** [comment]
I posit that the version containing the command was later than the January version currently posted.

But I will consider time travel in resolving the issue.

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by rpodric** [comment]
The link points to a version of Skype for Business Online, Windows PowerShell Module from JANUARY, which predates the availability of said command, but whatever, sure, resolved.

**Comment by j0rt3g4** [comment]
Hello @rpodric  if you go here:
https://docs.microsoft.com/en-us/microsoftteams/manage-feedback-policies-in-teams
The 1st line says 
**This is a preview or early release feature.**

This means that this feature it's on a preview, so probably is not there in production still.
And actually there is no more updates being shipped to skype for business.

Please go here and check what is on development or launched on the O365 site. I particularly didn't see the skype for business anymore, so get ready for teams.

https://www.microsoft.com/en-us/microsoft-365/roadmap?SilentAuth=1&wa=wsignin1.0&filters=

**Comment by rpodric** [comment]
Oh, my head hurts. Yes, I know it's a preview. So what?  I'm just actually trying to get it.

That _module_ I mentioned, which is the latest version currently posted, and the one that people repeatedly say is the one to get to effect the command in the article, doesn't actually have it.

And that's because said module predates said command by _several months_. My theory is that a later version of the module was available for a short time but was pulled.

I'm not sure why you're mentioning Skype for Business in any other context. I'm not.
