### ISSUE TITLE
Dead Link "Microsoft Teams Rooms Licensing"

### ISSUE THREAD

**Issue by jdayon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2699]
In 2nd section "Microsoft Teams Rooms Components", link for https://docs.microsoft.com/en-us/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/skype-room-systems-v2.md resolves to a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c25c286-2a25-19d1-6847-f2324b3deb73
* Version Independent ID: 0c82ef28-f9c8-1845-c167-ce2756478d9c
* Content: [Plan for Microsoft Teams Rooms](https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/skype-room-systems-v2-0)
* Content Source: [Teams/room-systems/skype-room-systems-v2-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/skype-room-systems-v2-0.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@jdayon Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@LanaChin please merge the PR and feel free to close this issue

**Comment by jambirk** [comment]
fixed this in  https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/pull/3285
