### ISSUE TITLE
broken link to Network Readiness Assessment.

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2705]
The link to the NRA is broken 
around the usage of the tool can be found here: `Network Readiness Assessment`. 

The url : https://go.microsoft.com/fwlink/?linkid=855800 cannot be resolved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d996cf7-9f48-2b30-7759-afaf3fe82caa
* Version Independent ID: 24dd6cdf-d35f-53b2-06c2-0a27891825d4
* Content: [Prepare your organization's network for Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/prepare-network)
* Content Source: [Teams/prepare-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/prepare-network.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Josverl  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Josverl Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
