### ISSUE TITLE
Please clarify where to find the network planner

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2706]
it would make sense to clarify in the first paragraph where to find the planner 
Teams Admin &gt; Org Settings &gt; network planner.

without that it is somewhat frustrating to be welcomed to something that you cannot find unless you already know, or need to download and review the pptx linked ad the bottom of the article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18f0a6ad-85d4-1d26-2e7c-496f0699e418
* Version Independent ID: c1283d82-a691-19aa-9fb9-be51031f0f39
* Content: [Use the Network Planner for Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/network-planner)
* Content Source: [Teams/network-planner.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/network-planner.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by jxs0900** [comment]
Opening with "Welcome to the Network Planner. " is misleading.  This page is not the Network Planner, why would you say welcome to the Network Planner when we are not at the Network Planner?  Why not "Welcome to the Network Planner Reference Guide" followed by something like "The actual Network Planner can be found here [link to Network Planner]".

**Comment by tonysmit** [comment]
Done and merged.
