### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Cutflo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2709]
That would be nice to translate those kind of posters. A lot of my collaboraters would apprecicate. 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: ad3ad624-9792-91b7-c85f-09b839b1ea44
* Version Independent ID: e8288f91-11bd-599b-8a88-074917b315a4
* Content: [Illustrations architecture IT Microsoft Teams et solutions téléphonie](https://docs.microsoft.com/fr-fr/microsoftteams/teams-architecture-solutions-posters#feedback)
* Content Source: [Teams/teams-architecture-solutions-posters.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-architecture-solutions-posters.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Cutflo  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Cutflo We will pass this on to the team and consider  adding it in the future.
