### ISSUE TITLE
Please improve translation.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#271]
Please improve English to German translation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7b3c872-0b2a-22e6-0ec3-433225d253f6
* Version Independent ID: 475c1607-b614-68c5-639c-aa86c88b893e
* Content: [Direct SIP connections in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/enterprise-voice-solution/direct-sip)
* Content Source: [Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/direct-sip.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/direct-sip.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by kenwith** [comment]
@samanthaw - is this one you can help with? This issue is actually from the old TechNet but maybe something to check on the translation?
