### ISSUE TITLE
Exchange Support?

### ISSUE THREAD

**Issue by adamfowlerit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2716]
Although the article mentions the photo in Exchange 2016 or 2013 (2013 being the minimum supported), it doesn't mention Exchange 2019 or Exchange Online. I am not sure if either are supported or not for Skype for Business On-Premises.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66ad8b3a-aac0-7eba-29e3-2d621fa46a54
* Version Independent ID: bba6f915-d50e-08c2-cd54-a56d2c25198e
* Content: [Configure the use of high-resolution photos in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/integrate-with-exchange-server/high-resolution-photos)
* Content Source: [Skype/SfbServer/deploy/integrate-with-exchange-server/high-resolution-photos.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/integrate-with-exchange-server/high-resolution-photos.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@adamfowlerit  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by adamfowlerit** [comment]
I logged a Microsoft case on this too Ticket #:15961688. Closed as it's not supported:

"If Modern auth was enabled, then Exchange Online Autodiscover service will not include “X-SOAP-Enabled: True” in the 401 response; therefore, Skype for business client will always use POX Autodiscover method; in this case, Exchange online web service will not return “ExternalPhotoUrl” in “GetUserSetting” response.""As I shared, product engineering team marked this bug as “Won’t fix” for now, the bug id is VSTS 1223001.
They have had deployed the fix a while back, however due to massive regression, they decided to turn off the fix.  It turns out SfB takes a dependency on the broken behavior and will go haywire if they correct it.  Skype team fixed it in most recent client versions but since SfB is client software, not everyone will upgrade to the latest version.  They cannot turn this on in Exchange Online datacenter as it will break real customers.

Workaround here is to disable modern auth by using below registry setting, however this will break MFA.

HKCU\SOFTWARE\Microsoft\Office\1X.0\Common\Identity\EnableADAL 
REG_DWORD 
0
"

Based on this, Skype for Business does not support photos in Exchange Online, if MFA is enabled (which it should be for everyone!). I'd rather be wrong and have photo support though...

**Comment by scanum** [comment]
@adamfowlerit thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by adamfowlerit** [comment]
@scanum Those comments were from a ticket logged saying it wasn't supported at all if MFA was on. Spent quite a bit of time on it... and what that ticket says should be reflected on this documentation, as they don't match up?
