### ISSUE TITLE
Must be in Islands Mode or Teams Only Coexistence mode for Org Wide setting for Guest Chat

### ISSUE THREAD

**Issue by AmericanPete** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2720]
We want to move our Org-wide Coexistence mode to SfB with Collaboration from Islands mode but when the org-wide policy changes the guests users are not able to one on one chat even for individual users that have been placed directly in Island mode. This is not documented anywhere. The guest users follows the Org-Wide settings for Coexistence mode and can not be changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external access (federation) in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access#feedback)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@AmericanPete  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Added this as an important note on #2870

**Comment by scanum** [comment]
@AmericanPete Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
