### ISSUE TITLE
Media Logs Information Looks Incorrect

### ISSUE THREAD

**Issue by ThePangy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2721]
This information for the Media Logs seems to be inaccurate now. I have used this previously, but it looks like MS may have changed the log file names as there are now folders for "media-stack" and "skylib". Neither folder contains the file names mentioned above for the Media Logs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d5e6d3-b7e0-d79f-0dea-ed423186a157
* Version Independent ID: ec6e68aa-552f-ab45-3c8e-92eff526b173
* Content: [Use log files in troubleshooting Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/log-files#feedback)
* Content Source: [Teams/log-files.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/log-files.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@ThePangy  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by ChristySA** [comment]
I also don't see a Get Logs option when I right click on the Teams icon in the application tray.

**Comment by dplotnikov** [comment]
@ThePangy it's okay on Mac, will check on Windows later

**Comment by dplotnikov** [comment]
@ThePangy I confirm there was a formatting issue and it should be clear now. As for missing files, it looks like the product and not docs issue

@ChristySA I see the button and it looks like the product and not docs issue

**Comment by dplotnikov** [comment]
@LolaJacobsen please merge the PR and feel free to close this issue

**Comment by ThePangy** [comment]
@dplotnikov - What formatting issue? I was reporting that the files listed for the media logs do not exist. I am on Windows 10 and I do not have any of these files:

%appdata%\Microsoft\Teams\media-stack*.blog
%appdata%\Microsoft\Teams\skylib*.blog
%appdata%\Microsoft\Teams\media-stack*.etl

I do have FOLDERS named:

%appdata%\Microsoft\Teams\media-stack
%appdata%\Microsoft\Teams\skylib

However, they do not contain the specific file names mentioned above.

**Comment by dplotnikov** [comment]
@ThePangy this is what I fixed actually but the fix is not live yet. The article has a typo where it should be %appdata%\Microsoft\Teams\media-stack\\\*.blog and not just %appdata%\Microsoft\Teams\media-stack*.blog

as for your 2nd statement, it looks like a product issue but this repository is just about documentation

**Comment by LolaJacobsen** [comment]
I'll contact the PM to review this PR.

**Comment by LolaJacobsen** [comment]
The PM approved the updates to the article, which have been made: 
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/2784/commits/86209ce780ba79bdc0abdb21182436c9cbc64f9c
