### ISSUE TITLE
Update link to retirement plan for third-party support

### ISSUE THREAD

**Issue by rhelm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2722]
Replace: 
A retirement plan for third-party support was announced last year in this blog, https://blogs.technet.microsoft.com/exchange/2017/07/18/discontinuation-of-support-for-session-border-controllers-in-exchange-online-unified-messaging

With:
A retirement plan for third-party support was announced last year in this blog, https://techcommunity.microsoft.com/t5/Exchange-Team-Blog/New-date-for-discontinuation-of-support-for-Session-Border/ba-p/607853

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63f7281d-e17d-c4e8-ced8-f4d695785e6c
* Version Independent ID: 40876324-10aa-e412-e1c2-868d1be2b9b1
* Content: [Exchange Unified Messaging Online migration support](https://docs.microsoft.com/en-us/SkypeForBusiness/plan/exchange-unified-messaging-online-migration-support#feedback)
* Content Source: [Skype/SfBServer2019/plan/exchange-unified-messaging-online-migration-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/plan/exchange-unified-messaging-online-migration-support.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@rhelm  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@MicrosoftHeidi please merge the PR and feel free to close this issue

**Comment by scanum** [comment]
@rhelm Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
