### ISSUE TITLE
Update statement about Auto Attendant capabilities (Mar. 2019)

### ISSUE THREAD

**Issue by rhelm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2723]
Please update the following statement:
Microsoft plans to deliver additional Auto Attendant capabilities that customers consider critical for their migration by March 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63f7281d-e17d-c4e8-ced8-f4d695785e6c
* Version Independent ID: 40876324-10aa-e412-e1c2-868d1be2b9b1
* Content: [Exchange Unified Messaging Online migration support](https://docs.microsoft.com/en-us/SkypeForBusiness/plan/exchange-unified-messaging-online-migration-support#feedback)
* Content Source: [Skype/SfBServer2019/plan/exchange-unified-messaging-online-migration-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/plan/exchange-unified-messaging-online-migration-support.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@rhelm  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@rhelm not sure what needs to be updated here

**Comment by rhelm** [comment]
"Microsoft plans to deliver additional Auto Attendant capabilities that customers consider critical for their migration by March 2019." It's now August 2019. Were the capabilities delivered? If not, are they still planned?

**Comment by tonysmit** [comment]
I do know that there were a bunch of updates made, I'm not sure where they ended up with the migration plan. Adding PG.
@waseemhashem or @roykuntz  - Can you assist hear please?

CC: @jambirk

**Comment by dplotnikov** [comment]
@tonysmit @waseemhashem @roykuntz @jambirk do you guys have any word on this?

**Comment by jambirk** [comment]
I'll take care of this later today.

**Comment by dplotnikov** [comment]
thank you @jambirk this issue is ready to be closed!

**Comment by rhelm** [comment]
Thanks, y'all.
Rob
