### ISSUE TITLE
Conflicting information on "Plans Shifts is available in" 

### ISSUE THREAD

**Issue by umayrsufi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2726]
Under the following link : https://docs.microsoft.com/en-us/MicrosoftTeams/expand-teams-across-your-org/shifts/microsoft-staffhub-to-be-retired#which-plans-is-shifts-available-in

The document states that Shifts is available in the plans listed below without any additional cost. To the user this implies other plans induce costs. However, if one navigates to the link provided "Availability of Shifts" which provides further information on the following link : 

https://docs.microsoft.com/en-us/MicrosoftTeams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams#availability-of-shifts

This takes them to the following information which states : 
"Shifts is available in all Office 365 subscriptions that include Teams, with a couple of exceptions. The exceptions are US Government Cloud Community (GCC) and Teams free. Shifts isn't available in Office 365 US Government or Teams free offerings." 

The link below this line takes them to the list of subscriptions which provide Microsoft Teams as part of the subscription. This includes plans that are not present on this page, including Office 365 Business essentials, Microsoft 365 Business - and much more. 

We should modify our wording in the mentioned three pages to become clear and not confuse the customer. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 600d2e5e-2e98-4885-c9ec-94c927680cbd
* Version Independent ID: d5930285-52f4-6d20-fae8-7202c0b480d7
* Content: [Microsoft StaffHub to be retired](https://docs.microsoft.com/en-us/MicrosoftTeams/expand-teams-across-your-org/shifts/microsoft-staffhub-to-be-retired#which-plans-is-shifts-available-in)
* Content Source: [Teams/expand-teams-across-your-org/shifts/microsoft-staffhub-to-be-retired.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/expand-teams-across-your-org/shifts/microsoft-staffhub-to-be-retired.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@umayrsufi  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@LanaChin Could you please aid us in the next steps for issue resolution? Thanks

**Comment by LanaChin** [comment]
Pinged the PMs for clarification.

**Comment by scanum** [comment]
@LanaChin Hi Lana, Any updates on this issue? Thanks

**Comment by LanaChin** [comment]
following up with PM.

**Comment by scanum** [comment]
@LanaChin Any updates on this? Thanks!

**Comment by scanum** [comment]
@LanaChin Following up on this issue. Thanks!

**Comment by scanum** [comment]
@LanaChin Following up on this issue. Thanks!

**Comment by LanaChin** [comment]
@umayrsufi, @scanum - both Shifts topics docs have been updated. Thanks so much for your feedback.
