### ISSUE TITLE
Media Flow in call forwarding scenario

### ISSUE THREAD

**Issue by waelschakaki** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2727]
Could you please explain the call flow in call forwarding scenario in case of media bypass? as in this scenario Teams client is not used, so i am not sure if the Transport relays are used? or if the media will be from\to SBC as a local media traffic ?!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10b198f4-9576-a14d-4359-1e8cc0319cda
* Version Independent ID: ba7c3252-21d4-9be1-2a84-de2d51646f7b
* Content: [Plan for media bypass with Direct Routing](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-plan-media-bypass)
* Content Source: [Teams/direct-routing-plan-media-bypass.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan-media-bypass.md)
* Service: **msteams**
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@waelschakaki Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@waelschakaki Thank you for reaching out and helping improve MS Docs. Please have a look at this article and let me know if it helps answer any of your questions. https://docs.microsoft.com/microsoftteams/microsoft-teams-online-call-flows

**Comment by waelschakaki** [comment]
Hello @lindspea , that is really helpful, thanx.
