### ISSUE TITLE
Using ExpressRoute with Skype for Business Server 

### ISSUE THREAD

**Issue by js101-stack** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2736]
Please can you discuss how to leverage ExpressRoute when using Skype for Business Server (on-prem) option for a small organisation (&lt;250 people) located globally across multiple geographies. Is this feasible, and if so, how? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7494f700-f2f6-9e30-8c3b-07ad2ecbdebc
* Version Independent ID: 16898d99-7806-8449-c5c0-6d870c7cf2c0
* Content: [Call flow using ExpressRoute](https://docs.microsoft.com/en-us/skypeforbusiness/optimizing-your-network/call-flow-using-expressroute#feedback)
* Content Source: [Skype/SfbOnline/optimizing-your-network/call-flow-using-expressroute.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/optimizing-your-network/call-flow-using-expressroute.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@js101-stack Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@js101-stack Thank you for reaching out.  Please have a look at this article and let me know if it helps with any of your questions and I can have the link added to the article for clarity for other users as well. https://docs.microsoft.com/office365/enterprise/network-planning-with-expressroute

**Comment by scanum** [comment]
@js101-stack We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
