### ISSUE TITLE
Need update.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#274]
This page is only accurate if you are deploying to a greenfield or upgrading from Lync 2010. If you are upgrading from Lync 2013, not schema changes are made. The schema version for Lync 2013 and SfB 2015 are the same (ms-rtc-sip-schemaversion = 1150). It would be best if a note is added clarifying this!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 712898ae-85a9-dc16-1285-c2e833245716
* Version Independent ID: b8ce52b4-b3a0-143c-45cc-9784a25a59be
* Content: [Schema changes in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/schema-reference/active-directory-schema-extensions-classes-and-attributes/schema-changes)
* Content Source: [Skype/SfbServer/schema-reference/active-directory-schema-extensions-classes-and-attributes/schema-changes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/schema-reference/active-directory-schema-extensions-classes-and-attributes/schema-changes.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by dariomws306** [comment]
Hi @nsshommo , a note was added to clarify this.

Thank you for your feedback!
