### ISSUE TITLE
Examples for Adding Derived trunk

### ISSUE THREAD

**Issue by kamleshtv** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2741]
Hi Could you please add some examples for adding the derived trunk in the customer tenant in the voice routing policy ?

**Comment by scanum** [comment]
@kamleshtv Please reference the issue you are speaking about. Thanks

**Comment by scanum** [comment]
@kamleshtv We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by kamleshtv** [comment]
Hi, This is in reference to Microsoft Teams Direct Routing for multi tenant carrier model.
https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants

**Comment by kamleshtv** [comment]
Hi,

I am unable to reopen  the issue as I did not close it.

Kamlesh
