### ISSUE TITLE
DSCP markings for Teams with ExpressRoute?

### ISSUE THREAD

**Issue by JorgeALeitao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2742]
Under https://docs.microsoft.com/en-US/microsoftteams/qos-in-teams#choose-initial-port-ranges-for-each-media-type 

It states "The following table shows the required DSCP markings for Teams with ExpressRoute" - I reckon that DSCP settings are the same regardless of ExpressRoute been used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76c2487c-044d-1349-708a-5841fcb21ab8
* Version Independent ID: b7033454-1a9c-48d4-8004-78415c5feb89
* Content: [Implement Quality of Service in Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/qos-in-teams#feedback)
* Content Source: [Teams/QoS-in-Teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/QoS-in-Teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@JorgeALeitao Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tonysmit** [comment]
@jambirk - Can you follow up on this please?

**Comment by jambirk** [comment]
fair comment: both Teams and Expressroute use these specific DSCP markings, and it's not the marking that's customizable here, just the port ranges.
