### ISSUE TITLE
PDF of Compliance Framework is not up-to-date

### ISSUE THREAD

**Issue by SorenPedersen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2748]
The link to "Compliance Framework for Industry Standards and Regulations" is working now, but the file it links to is not up-to-date. It is from 2017 and says that Teams is Tier C. The article says that it is Tier D. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca579d63-182b-d6f5-8777-79248fa27ed9
* Version Independent ID: b4c27d1b-b2f1-41ac-b15c-d12b448a539e
* Content: [Overview of security and compliance in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/security-compliance-overview#feedback)
* Content Source: [Teams/security-compliance-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/security-compliance-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@SorenPedersen Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@SorenPedersen Thank you for your feedback, I'll investigate further.

**Comment by scanum** [comment]
@SorenPedersen Hi Soren, we are yet to generate an organization link. Once we do, we will update this issue. We will be closing the issue for now. Thanks.
