### ISSUE TITLE
BTN is porting number

### ISSUE THREAD

**Issue by mbigus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2750]
"If you are doing a partial-port, leave the service Billing Telephone Number (BTN) out of this list."

What if you are doing a port of one number, and that number is also the BTN?  That is impossible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1829a37-a7a1-4dd1-fde8-82125c593ff1
* Version Independent ID: dfedc4c5-eec4-2137-e975-399866aaafad
* Content: [Transfer phone numbers to Office 365](https://docs.microsoft.com/en-us/microsoftteams/transfer-phone-numbers-to-office-365?toc=/skypeforbusiness/toc.json&bc=/skypeforbusiness/breadcrumb/toc.json)
* Content Source: [Teams/transfer-phone-numbers-to-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/transfer-phone-numbers-to-office-365.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by mbigus** [comment]
This is inferred above but perhaps should be stated more directly. On another site I found: 
"However, you cannot port the BTN if not doing a full transfer."
https://blog.enablingtechcorp.com/skype-for-business-online-telephone-numbers-and-porting-faq

**Comment by tonysmit** [comment]
@mbigus - Yes, that is possible. The BTN in that case would be the same. Thanks, Tony

**Comment by mbigus** [comment]
@tonysmit  - how is it possible? The docs I reference above say NOT to include the BTN in the list of numbers to port. So, when the BTN is the number to be ported, how does one do it?

**Comment by tonysmit** [comment]
The docs are incorrect and need to be updated. Can you call out the section/line for me and I will get it fixed. If you have a single phone number on an account, then that *is* the BTN. Think of your mobile phone bill.

**Comment by mbigus** [comment]
@tonysmit - it's the note on line 76. Although, I think it is correct as far as the online wizard/submission form. As when I contacted the porting team I ended up having to fill out the LOA form, specify as a service number, but also tell them the remaining number at the provider that would then become the BTN. So this note may be correct for the online form in the skype portal but another note would have saved me a great deal of time with support. Something along the lines of :

"If you require a partial port that INCLUDES the BTN, please fill out the LOA form available for your country here: https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization/manage-phone-numbers-for-your-organization.  Include the BTN in the list of numbers to be transferred within the form. Email this form to the porting team (p**@microsoft.com)  and within the email indicate one of the remaining numbers that we should make the BTN at your previous provider."

(I am not sure if in all cases the porting team can select the BTN as specified or if the user needs to arrange with their provider in advance, but in this case, the porting team handled it)

**Comment by mbigus** [comment]
@tonysmit Also line 92 in https://docs.microsoft.com/en-us/microsoftteams/transferring-phone-numbers-common-questions

**Comment by drandhawaitforce** [comment]
Also, Not able to select a CANADIAN PROVINCE from your dropdown of 'State' when trying to port a Canadian number to Teams, you would think its pretty obvious. PLEASE FIX!!

**Comment by zyead** [comment]
؟؟

الحصول على Outlook لـ iOS<https://aka.ms/o0ukef>
________________________________
من: drandhawaitforce <notifications@github.com>
‏‏تم الإرسال: Friday, August 2, 2019 6:58:56 PM
إلى: MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com>
نسخة: Subscribed <subscribed@noreply.github.com>
‏‏الموضوع: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] BTN is porting number (#2750)


Also, Not able to select a CANADIAN PROVINCE from your dropdown of 'State' when trying to port a Canadian number to Teams, you would think its pretty obvious. PLEASE FIX!!

**Comment by tonysmit** [comment]
@drandhawaitforce - you are using SFBO (legacy portal)?

**Comment by drandhawaitforce** [comment]
@tonysmit - Yes, using the legacy portal

**Comment by tonysmit** [comment]
@drandhawaitforce  - Please contact the PSTN service desk @ ptn@microsoft.com so they can help you. See https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization/phone-number-management-for-the-u-s for more information.

Under **Get numbers transferred to us** > download the PDF and send it along with your email. They usually have a pretty quick turnaround.
