### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by j3ss1caL** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2751]
Teamss 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1829a37-a7a1-4dd1-fde8-82125c593ff1
* Version Independent ID: dfedc4c5-eec4-2137-e975-399866aaafad
* Content: [Transfer phone numbers to Office 365](https://docs.microsoft.com/en-us/MicrosoftTeams/transfer-phone-numbers-to-office-365#feedback)
* Content Source: [Teams/transfer-phone-numbers-to-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/transfer-phone-numbers-to-office-365.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@j3ss1caL Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@j3ss1caL 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
