### ISSUE TITLE
One Scenario missing: Internal user + no access to SBS's public address

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2753]
Have you thought us who are behind the FWs, and having no access to SBC's public address? But we could have access to SBC's internal address.

Could you draw the call flow for scenario for internal users. As far as I have understood, that is not so strange configuration on your customers. And even better can you make possible to use the internal address of SBC for media bypass.

**Comment by scanum** [comment]
@Petri-X Please reference the documentation you want this added on. Thanks!

**Comment by Petri-X** [comment]
Now I understood why the view was so difference compared to previous reports :)

I'll close this, and create a correct feedback :)

Have a great day !
