### ISSUE TITLE
Under Feature Support, Server Side Conversation History is not supported with Exchange 2010 On-Premise.

### ISSUE THREAD

**Issue by NicholasBurkhammer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2756]
Should be changed from Y to Y (needs Exchange 2016/2013).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f91868fa-0a46-a7e7-eaae-388fc90e195d
* Version Independent ID: 193c6ccc-3fc0-5146-ed08-55f9d8871341
* Content: [Plan to integrate Skype for Business and Exchange](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/integrate-with-exchange/integrate-with-exchange#feature-support)
* Content Source: [Skype/SfbServer/plan-your-deployment/integrate-with-exchange/integrate-with-exchange.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/integrate-with-exchange/integrate-with-exchange.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@NicholasBurkhammer Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@NicholasBurkhammer Thank you for your feedback, I'll investigate further.

**Comment by scanum** [comment]
@NicholasBurkhammer We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
