### ISSUE TITLE
Is this supported on GCC or GCC High Tenants?

### ISSUE THREAD

**Issue by vscurtis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2757]
Licensing seems ambiguous, not all Vars seem to have this SKU available. Additionally there is no mention of the Government tenant licensing / availability.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses](https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/skype-room-systems-v2#feedback)
* Content Source: [Teams/room-systems/skype-room-systems-v2.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/skype-room-systems-v2.md)
* Service: **skype-for-business-online**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@vscurtis Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by msbemba** [comment]
@vscurtis Thank you for your feedback. I have added GCC and GCC High Dod to the Note. This can be tracked Via PR  https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/2821.

Meeting SKU is available on all Versions of Enterprise and GCC licenses

Regards
Sri

**Comment by jambirk** [comment]
GCC or GCC High and DoD SKUs are not supported for use with MTR. Hope that answers your question.

**Comment by vscurtis** [comment]
So teams meeting rooms will or will not be available in GCC / GCC High? seems we have conflicting answers here.

**Comment by jambirk** [comment]
@vscurtis Teams Meeting Room devices don't use those particular licenses at present. This isn't the correct channel to make assertions about what licenses might be supported in the future. Should the licesninge requirements change, the page will be updated ASAP. 

The OP had a question that was misinterpreted as a definitive statement or correction needed, and without checking someone initiated a PR to make the "correction," which was not approved because it was in error. If there were conflicting "answers" (speculation seems more likely) they have been overridden by the official answer from the product group.

**Comment by vscurtis** [comment]
@jambirk i understand that there is a tendency to speak in whatever lingo seems appropriate for internal groups at the moment but i am afraid you are using terms that are not clear to me as an outsider. what is 'OP' or 'PR' and how on earth does one know who is providing a definitive answer because everyone here looks to be a 'contributor' 

You appear to be speaking with a tone of some authority here but assumptions are a bad thing.

Back to my original ask: our organization is evaluating the use of the MTR sku because we have some meeting room devices we are looking into to make things easier on the executives. The switch from Skype for Business to Teams was less than transparent about hardware impacts and so we avoid making the same mistakes we have been talking with experts and one of the recommendations was this license option. HOWEVER we are in the process of also migrating off of the consumer based cloud to government community cloud and we want to be absolutely certain that when we move over there any devices or licenses we get in consumer have a direct correlation in GCC and GCC High.

If we get hardware / software that utilizes the Teams Room License; will we be able to find a comparable license for GCC and if not is there some work around process that can be used instead to support that hardware?

**Comment by jambirk** [comment]
@vscurtis
I am the original writer of this article, but for licensing questions I always check with the development team that creates the product. The article is accurate and doesn't require a correction.

OP (in this case you) refers to Original Poster, which has been parlance in threaded discussions for a long, long time. PR is a Pull Request (at least on GitHub) and msbemba is a freelancer who acted prematurely in creating one.

Questions about what is coming would require me to either speculate or pre-announce a change, and that's not appropriate in product documentation.  I simply can't answer this question in the article or in an issue thread. Your best options are to either open a support ticket, or direct your question to the discussions in a marketing blog article like this one:  https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/An-inclusive-meeting-experience-for-everyone-in-any-room-with/ba-p/805877
