### ISSUE TITLE
Transfer to PSTN number externally was due Q2CY19

### ISSUE THREAD

**Issue by markdomansky** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2758]
I tried setting up an AA with transfer to PSTN and it does not have that option.  When will that be available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63f7281d-e17d-c4e8-ced8-f4d695785e6c
* Version Independent ID: 40876324-10aa-e412-e1c2-868d1be2b9b1
* Content: [Exchange Unified Messaging Online migration support](https://docs.microsoft.com/en-us/SkypeForBusiness/plan/exchange-unified-messaging-online-migration-support#feedback)
* Content Source: [Skype/SfBServer2019/plan/exchange-unified-messaging-online-migration-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/plan/exchange-unified-messaging-online-migration-support.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@markdomansky thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
