### ISSUE TITLE
Charges after the trial?

### ISSUE THREAD

**Issue by tereshi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2759]
My group has just started exploring Teams (some of us on E3, others on perpetual Plan1 license -which will have Teams Trial access for 1 year until next year). What happens to our subscription charges after the 1 year trial lapses (for the people on Plan1)? Would charges automatically begin to kick in?

**Comment by scanum** [comment]
@tereshi thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
