### ISSUE TITLE
Conference ID will be 7 digits by default

### ISSUE THREAD

**Issue by 3k09** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2761]
Hello, 
could you please verify the statement "The conference ID for all of your audio conferencing users will be 7 digits by default, and the number of digits can't be changed."?
On my tenant and my Teams/Office 365 audio conferencing invitations all conference IDs are 8 digits be default. E.g. 123 456 78# Is the conference ID space also dynamically growing due to more and more users are enabled for audio conferencing within the global O365 cloud?
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2167d5b2-c4c4-3164-2ed2-9582c8a0f95b
* Version Independent ID: cbbf9c78-5708-a0a9-31c3-d2cb4b31f6d3
* Content: [See, change, and reset a conference ID assigned to a user in Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/see-change-and-reset-a-conference-id-assigned-to-a-user-in-teams#feedback)
* Content Source: [Teams/see-change-and-reset-a-conference-id-assigned-to-a-user-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/see-change-and-reset-a-conference-id-assigned-to-a-user-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by tonysmit** [comment]
@ruizoscar - I think this is incorrect, I want to verify. Can you please submit a PR to update this please? Thanks, Tony

@3k09 - PINs are now dynamically generated based on the policy setting for the bridge, however, I think the 7 digits by default has changed. Also, no they are only based on the tenant setting. Oscar can confirm.

**Comment by msbemba** [comment]
@3k09  Thank you for your feedback. We have created a PR https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/2811 to reflect the changes in the doc.

**Comment by scanum** [comment]
@3k09 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
