### ISSUE TITLE
example to connect

### ISSUE THREAD

**Issue by TiloGit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2763]
Can you please add an example how to connect after setup of PS is done?

or link to: https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3117c408-39c5-df82-7238-3e842e953a64
* Version Independent ID: 80a85e4e-a1b3-68a7-bb9c-544925bcb3ef
* Content: [Set up your computer for Windows PowerShell](https://docs.microsoft.com/en-us/SkypeForBusiness/set-up-your-computer-for-windows-powershell/set-up-your-computer-for-windows-powershell)
* Content Source: [Skype/SfbOnline/set-up-your-computer-for-windows-powershell/set-up-your-computer-for-windows-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-your-computer-for-windows-powershell/set-up-your-computer-for-windows-powershell.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@TiloGit Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by msbemba** [comment]
@TiloGit  Thank you for your feedback. We have created a PR # https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/2810 to reflect the changes in the doc.

**Comment by scanum** [comment]
@TiloGit 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
