### ISSUE TITLE
user activity tracking

### ISSUE THREAD

**Issue by timdvj** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2764]
Hi, how can I analyze which individual Teams & Channels my users are visiting? 
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81440b2f-391b-5856-a216-15866f37082a
* Version Independent ID: cdd15cd4-d4ed-c413-e2b9-ebf6dad8b33b
* Content: [Use activity reports for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-activity-reports#feedback)
* Content Source: [Teams/teams-activity-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-activity-reports.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by tonysmit** [comment]
Go to Teams admin > Analytics and reports > Teams activity report.

@chuckedmonson - can you add a link to your doc please?

**Comment by msbemba** [comment]
@timdvj  Thank you for feedback. We have added a doc "https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report" which talks specifically about the teams activity report.

Hope this helps!

Regards
Sri

**Comment by scanum** [comment]
@timdvj Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
