### ISSUE TITLE
Something wrong?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2766]
When running the command:
**Get-StaffHubTeamsForTenant | Get-Member**
I only get the following properties:

**Name           MemberType            Definition**
.
.
Item           ParameterizedProperty Shiftr.PublicApiBeta.Models.Te
Capacity       Property              int Capacity {get;set;}
Count          Property              int Count {get;}
IsFixedSize    Property              bool IsFixedSize {get;}
IsReadOnly     Property              bool IsReadOnly {get;}
IsSynchronized Property              bool IsSynchronized {get;}
SyncRoot       Property              System.Object SyncRoot {get;}

Most likely this is because the TypeName is: **TypeName: System.Collections.Generic.List**

As an additional, when giving the command:
**Get-StaffHubTeamsForTenant -ManagedBy "Staffhub"**
I get the error:
_Get-StaffHubTeamsForTenant : A parameter cannot be found that matches parameter name 'ManagedBy'._

Question is: how do you expect those investigations can be done?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f64dee1-c968-9d64-757e-7ca3263a4fc4
* Version Independent ID: a3157a8b-a127-0726-2ee4-8972e773a785
* Content: [Move your StaffHub teams to Shifts in Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/expand-teams-across-your-org/shifts/move-staffhub-teams-to-shifts-in-teams)
* Content Source: [Teams/expand-teams-across-your-org/shifts/move-staffhub-teams-to-shifts-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/expand-teams-across-your-org/shifts/move-staffhub-teams-to-shifts-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Petri-X** [comment]
I had incorrect PowerShell version from StaffHub module.

Have a nice day ! 💃
