### ISSUE TITLE
How to get skype PS module - documentation seems inaccurate

### ISSUE THREAD

**Issue by Sambsamb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2768]
This document https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-overview states 
"Skype for Business PowerShell module: The Skype for Business PowerShell module contains the cmdlets to manage policies, configurations, and other Teams tools."
which links to https://www.microsoft.com/en-us/download/details.aspx?id=39366 which downloads the SkypeOnlineConnector PS module which contains only 2 cmdlets; New-CsOnlineSession and Set-WinRMNetworkDelayMS. It does not contain Get-CsTeamsMeetingPolicy cmdlet for example referenced in the document, which belongs to the 'skype' PS module. 
Q1. Can you correct this document to reference the correct skype PS module that contains the PS cmdlet referenced here, and
Q2. Can you provide information and link to obtain the required skype PS module

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26362d70-cfce-2eea-077b-4aaa50f92e8b
* Version Independent ID: f52dcd4d-4f58-05c4-11b0-f1e3c95f4d89
* Content: [Teams PowerShell Overview](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-overview)
* Content Source: [Teams/teams-powershell-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Sambsamb Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@LolaJacobsen Could you please aid us on next steps for this issue's resolution. Thanks

**Comment by get-itips** [comment]
Hello @Sambsamb Sam, how are you? Hope you are doing great.
The article points to the right Skype For Business Online Powershell Module, when you install it, it could seem that cmdlets are missing, however, all necessary cmdlets to connect to your tenant's SfB Online are in there, once you connect, a remote PS Session will be established and all necessary cmdlets will be imported into your session:

See an example

![image](https://user-images.githubusercontent.com/36666927/66346320-4e1d0880-e928-11e9-88d8-857c12fd23ab.png)

See this to know [how to connect using the SfB module](https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell)

**Comment by kenwith** [comment]
What is PR link? I will get it merged right away.

**Comment by kenwith** [comment]
Merged.
