### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#277]
Missing TCP 4092 & TCP 10000.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5164207-7822-cf54-717e-6216e0627ebd
* Version Independent ID: 786f5413-3660-06eb-484f-8d5758d3ec59
* Content: [Port and protocol requirements for servers](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/network-requirements/ports-and-protocols)
* Content Source: [Skype/SfbServer/plan-your-deployment/network-requirements/ports-and-protocols.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/network-requirements/ports-and-protocols.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
adding Thomas Binder to the discussion to verify or refute.

**Comment by thomasbinder** [comment]
I'm not aware of these ports being required.

@nsshommo can you provide more information what these ports are used for?
