### ISSUE TITLE
License note, not correct?

### ISSUE THREAD

**Issue by lcansby** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2773]
"Phone System is an add-on license available with Office 365 F1, E1, E3, and Office Premium licenses. Phone System is also included as part of Office 365 E5 licenses."

Is it new that F1 and "Office Premium" (I guess you mean Business Premium) can have the Phone System add-on license? If you change to following:
"Phone System is an add-on license available with Office 365 E1 and E3 licenses. Phone System is also included as part of Office 365 E5 licenses."

https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/office-365-business-premium

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6891495-01c6-117b-c28b-28232782ba74
* Version Independent ID: 1c23b35a-e9ba-ffdd-9baa-a3f83f4ed9ca
* Content: [Phone System–Virtual User licenses ](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/virtual-user#feedback)
* Content Source: [Teams/teams-add-on-licensing/virtual-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/virtual-user.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@lcansby Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jambirk** [comment]
@waseemhashem please comment

**Comment by SvenBell** [comment]
at least 75% of customer tenants are still missing the ability to purchase the free Virtual User license version.  I am based in Australia so this may be a regional issue that needs fixing. When comparing a rare tenant that lists license vs tenant that doesn't is seem both have a different portal version despite both being on preview mode. I have logged a ticket with Microsoft support: [Ticket #:15434498] and they are having to dish out full Phone System product keys on a 90 day trial, to allow us to license resource accounts on client tenancies.

**Comment by SvenBell** [comment]
@waseemhashem The purchasing instructions above only work in preview mode and that the Preview mode is working which it is again broken today for the Purchase services page. It's like today we get the non preview mode view in Preview mode but missing the Phone System - Virtual User license and the page won't scroll. It worked yesterday for the fist time in over a week and it's back on the blink again today. I have tested this on multiple tenants and another Microsoft partner has confirmed they experience the frustrating experience. We now have 2 weeks to Teams deployments backed up because we cannot get these essential licenses to assign PSTN numbers to Auto-Attendant/Call-Queues. Ticket #:15434498

**Comment by msbemba** [comment]
@lcansby  Thank you for the feedback. The note is correct "Phone System is an add-on license available with Office 365 F1, E1, E3, and Office Premium licenses. Phone System is also included as part of Office 365 E5 licenses." Let me know what exactly you are looking to correct ?

Regards
Sri

**Comment by lcansby** [comment]
@msbemba In the section "Virtual User license allocation" there is a note that the phone system add-on licenses are available for "Office 365 F1, E1, E3, and Office Premium licenses". According to other documentation and Phone system add-on is only available for E1 and E3.

**Comment by msbemba** [comment]
@lcansby I got what you are saying. The doc (https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/office-365-business-premium) is now updated stating that "If you decide to buy an Enterprise E5 license, it includes a Phone System license. If you use an Enterprise E1 or E3 license or an Office 365 Business Essentials or Office 365 Business Premium license you will need to buy the Phone System add-on."

Hope this helps!

Regards
Sri

**Comment by lcansby** [comment]
@msbemba Is that really correct that you can add Phone System license to an Office 365 Business Essentials or Office 365 Business Premium subscription? That is new in that case, earlier you only been able to add Phone system to Enterprise licenses, not Business.

https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/virtual-user
This page still states that Phone System add-on is available on F1 and the unknown license "Office Premium".

**Comment by SvenBell** [comment]
@msbemba if you add F1, It think you are bang on. As long as this is what Microsoft support vs what actually works but isn't supported.

**Comment by msbemba** [comment]
@lcansby  Thank you for your feedback. I have made changes to the doc to refelect the licensing options correctly. PR https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/2819 . you are correct with the statement that Business premium or essentials do not have option to add phone system as add-on.

Regards
Sri

**Comment by jambirk** [comment]
@waseemhashem please comment

**Comment by SvenBell** [comment]
Option 3 in this Microsoft document specifies Phone System as an Add-On for Office 365 Essentials : https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/office-365-business-premium
