### ISSUE TITLE
The Date should probably change?

### ISSUE THREAD

**Issue by BjornAnd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2776]
on the english site it is another date.
https://docs.microsoft.com/en-us/skypeforbusiness/legal-and-regulatory/end-of-integration-with-3rd-party-providers
:)

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 411be1af-0377-1d2c-0d07-04edb445a42a
* Version Independent ID: 5ad12387-b987-6cda-8c56-052c79274f2c
* Content: [Slutet av livscykel-program för integrering av Skype för företag med tredjepartsföretag som tillhandahåller ljudkonferenser ](https://docs.microsoft.com/sv-se/skypeforbusiness/legal-and-regulatory/end-of-integration-with-3rd-party-providers)
* Content Source: [Skype/SfbOnline/legal-and-regulatory/end-of-integration-with-3rd-party-providers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/legal-and-regulatory/end-of-integration-with-3rd-party-providers.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@BjornAnd Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by msbemba** [comment]
@BjornAnd  Thank you for the feedback. The date has been corrected on all versions of the document.

Regards
Sri

**Comment by scanum** [comment]
@BjornAnd Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
