### ISSUE TITLE
Special requirement for SFB for MAC to join meetings anonymously

### ISSUE THREAD

**Issue by howardzhangmsft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2777]
Please add the following important information so everybody knows the requirement for SFB for Mac to join meetings anonymously:

Although we have introduced MeetingUxUseCdn in SFB server 2015 CU5, the default value was set to False. 
It causes an issue where Skype for Business for Mac client is unable to join non-federated partners' meetings as guest even if SFB admin has sets MeetingUxUseCdn to True. 
To resolve the issue, customer must upgrade their SFB server 2015 to CU7 (6.0.9319.534) or later. 
In CU7, product engineering intentionally set MeetingUxUseCdn to True as default value, only after which SFB server would send CDN based response to SFB for Mac clients. Please refer to KB article below:
https://support.microsoft.com/en-us/help/4132312/enable-skype-meetings-app-to-replace-skype-for-business-web-app 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db59b2a2-95b3-a7d9-c390-1489d4d93053
* Version Independent ID: 612310eb-8c79-8e91-4f7e-0a1874cda558
* Content: [Deploy Web downloadable clients in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/deploy-web-downloadable-clients#enable-skype-meetings-app-to-replace-skype-for-business-web-app-optional-skype-for-business-server-2015-only)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/deploy-web-downloadable-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/deploy-web-downloadable-clients.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@howardzhangmsft Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@howardzhangmsft thank you for this information. I'll investigate to have the necessary information added as soon as possible.

**Comment by scanum** [comment]
@howardzhangmsft Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
