### ISSUE TITLE
Mistake in example.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#278]
The second example with "set-cscertificate -type oauthtokenissuer" does not contain "-identity global" which is mandatory. Am I right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbb586e8-9c5d-c4da-a3ac-db93ea727e09
* Version Independent ID: 64df6b50-ba8a-5d6f-2c40-eb2b5307817c
* Content: [Stage AV and OAuth certificates in Skype for Business Server 2015 using -Roll in Set-CsCertificate](https://docs.microsoft.com/en-us/skypeforbusiness/manage/authentication/stage-av-and-oauth-certificates)
* Content Source: [Skype/SfbServer/manage/authentication/stage-av-and-oauth-certificates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/authentication/stage-av-and-oauth-certificates.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.
