### ISSUE TITLE
Deleting a group hides the team from admin center but the team remains

### ISSUE THREAD

**Issue by snarkshark** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2789]
I'm not sure where in the documentation it best makes sense to report this, but after deleting a group, the team is removed from the Manage Teams table in the teams admin center and stops being returned by get-teams in powershell, but the channels remain in the channel table in powershell (if you use the deleted group's id). Permanently deleting the group also leaves the orphaned channel objects (as evidenced by previously noting the ID then using it to pull the attached channels). If you use [Graph](https://docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-1.0), you can also still pull the team using that deleted group ID. Both expose internal IDs, which I read to mean the team and channel entries are independent of the group and the tenant and don't require them to continue to exist. The settings also continue to save to the team, even though it no longer appears in the Teams listed in the admin center. So the objects seem to exist independent from the group, and it seems like they're left orphaned after the group is deleted, leaving the possibility for a team to exist attached to the tenant that only the members and owner are aware exist and is otherwise out of reach of administration, and as far as I can tell the only way to discover this team if the group has been deleted permanently is to be made owner/member. The graph method requires a group ID to return result and thus doesn't return these orphaned objects unless the group ID was previously noted, and I'm not sure that's a reasonable expectation.

This may clean itself up after 30 days - I haven't been investigating this long enough to tell. I do know the team can still be queried from Graph using the permanently deleted group's ID an hour after the group was permanently deleted though. And it still appears in Teams, and settings can still be changed and are still saved, even across incognito browsers, so it doesn't seem to be some sort of client-side caching.

It might be a good idea to add a blurb suggesting to take ownership of a team and delete it through teams or the admin center before deleting the group to prevent these orphaned objects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d86301b-ce9c-388c-e563-9e5e5c27132e
* Version Independent ID: 07e4ae23-0966-e8f3-9b7c-4f6c02569eb0
* Content: [Office 365 Groups and Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/office-365-groups)
* Content Source: [Teams/Office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-groups.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by snarkshark** [comment]
It may also be worth considering if this affects GDPR "right to erasure" requests. IANAL but this seems to fall under "the personal data is no longer necessary for the purpose which you originally collected or processed it for", if the admin deleted the group with the intent to also delete the team. https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/right-to-erasure/

Should we then file support requests to request the deletion of any orphaned channels we can't query anymore because the group's been deleted?

**Comment by snarkshark** [comment]
I went further - created a user, set it as the new owner, deleted the group, left the team, deleted that user. Permanently deleted both. The team can still be pulled using graph, but the owner and member list apparently can't be modified even using graph. Since it seems one needs to be a member/owner of the team to be able to recover the group ID to then fetch the group using this method (which by extension allows deleting straight from teams) and this team now has neither owner nor member, I can't see an obvious way an admin would be able to identify and delete this. I tried by graph using the group ID I had noted, and GET continues to return the team but DELETE returns No HTTP resource was found that matches the request URI 'https://api.teams.skype.com/v1.0/teams('redacted')'

**Comment by snarkshark** [comment]
I can still pull the pure orphan team today, I'll continue monitoring until the 30-day mark passes since after that this should have been deleted.

**Comment by scanum** [comment]
@snarkshark

**Comment by snarkshark** [comment]
Hello @scanum!

So I just tried pulling the pure orphan team again, it's still there

**Comment by scanum** [comment]
@snarkshark  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by snarkshark** [comment]
Thank you! Should I keep reporting the status of the orphan team, just to have a sense of how long it takes to clear out? I'll advise on day 31 either way, since at that point it's past the retention period too so that might be a bit more problematic.

On that note, it still exists today

**Comment by lindspea** [comment]
@snarkshark thank you for keeping us up to date on the developments.  I'll investigate further as well and see where we can improve the documentation.  Please let me know if there is anything you could suggest to improve the article.

**Comment by snarkshark** [comment]
Well, mostly I'd suggest just putting one of those purple information blurbs saying to delete the associated team before deleting a group because otherwise the team will be orphaned, invisible in PS and admin center, and possibly entirely unmanageable (though perhaps with a bit of editorial flair so it sounds better than that).

**Comment by lindspea** [comment]
@snarkshark "Before deleting a group, the associated team must be deleted, otherwise the team will be invisible in PowerShell and the Admin center. " Does that cover everything?

**Comment by snarkshark** [comment]
I think that covers the gist of it - there is still a concern if the team will self-delete after 30 days, but I'll update this in 12 if it doesn't

**Comment by lindspea** [comment]
Thanks @snarkshark. I'll wait to hear from you in case more information needs to be added. Thanks for all your help so far.

**Comment by snarkshark** [comment]
So it's been 32 days, the orphan team still exists, which means the data persists 30 days after the intent to delete it was submitted and in this case there's no way for the admin to remediate the situation.

I'd say the issue has been addressed and the suggested note would resolve it - that said, there may be reasons to be concerned that this object persists more than 30 days after that intent to delete.

**Comment by scanum** [comment]
@snarkshark Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
