### ISSUE TITLE
Typo in heading, no space after question mark.

### ISSUE THREAD

**Issue by Atreidae** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2790]
The heading:
Will current third-party IP (3PIP) phones continue to work with Microsoft Teams?And if so, how long? 
Should read: 
Will current third-party IP (3PIP) phones continue to work with Microsoft Teams? And if so, how long?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbeb59c4-349f-944c-5183-4fb26a34c22b
* Version Independent ID: 2beb18af-35a6-de0a-d90f-89c94533b8da
* Content: [FAQ - Upgrading from Skype for Business to Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/faq-journey#feedback)
* Content Source: [Teams/FAQ-journey.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/FAQ-journey.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by tonysmit** [comment]
@jambirk - Although this is upgrading content, do you know the answer here?

**Comment by jambirk** [comment]
purely a typo, the fix is sent to live
