### ISSUE TITLE
Uploading custom apps is not allowed

### ISSUE THREAD

**Issue by svoltmer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2801]
There is no setting in the Teams Admin to allow the uploading of custom apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9b7f77-061d-a224-ff1c-8d3e15d21221
* Version Independent ID: 00fa9550-c4c4-3398-ffbb-271cc724048f
* Content: [Manage Microsoft Teams settings for your organization](https://docs.microsoft.com/en-us/MicrosoftTeams/enable-features-office-365#feedback)
* Content Source: [Teams/enable-features-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enable-features-office-365.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@svoltmer

**Comment by lindspea** [comment]
@svoltmer Thank you for reaching out and helping improve MS Docs.  Please let me know if these instructions work:
    In the left navigation of the Microsoft Teams admin center, go to Teams apps > Setup policies.
    Click Add.
    Turn on or turn off Allow uploading custom apps.
    Click Save.
Link for reference - https://docs.microsoft.com/microsoftteams/teams-custom-app-policies-and-settings. Please let me know if this helps at all.

**Comment by scanum** [comment]
@svoltmer  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
