### ISSUE TITLE
Island mode VS TeamsOnly Mode external access can search for external users 

### ISSUE THREAD

**Issue by rane52** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2802]
![teams external search](https://user-images.githubusercontent.com/53837069/62578589-5a1c1980-b856-11e9-97d4-81ff1e1cd378.PNG)
Users on Island mode unable to search and start a new chat with external users but users on TeamsOnly mode are able to search and start a new chat with external users. org-wide settings external access are enabled for both options but ONLY TeamsOnly mode users are seeing the search for the external user when they start tying email address in the search bar for Teams. for Island mode unable to search or find any external users by search or new chat request.
Can someone confirm that user in Island mode can chat with external users, not guest access

**Comment by scanum** [comment]
@rane52 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
