### ISSUE TITLE
Clarification on base domain and subdomains with multiple tenant SBC

### ISSUE THREAD

**Issue by SirChristopher** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2805]
It would be helpful to make sure there is clarification on the section labeled **Register a base domain and subdomains**. 
In the example Table, can the Base domain (adatum.biz) also be used to provide voice to itself with an SBC name of sbc0.customers.adatum.biz?
Or is the Base domain (adatum.biz) not allowed to have the voice services tied to the Base domain name that is used?

Link for Reference: https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants

**Comment by scanum** [comment]
@SirChristopher Could you please link the issue you are referring to? Thanks

**Comment by lindspea** [comment]
@CarolynRowe please could you assist?

**Comment by dariomws306** [comment]
Hi @SirChristopher and @lindspea,

I have this environment working and you can use sbcX.customers.adatum.biz in the carrier tenant to enable voice there.

**Comment by lindspea** [comment]
Thanks @dariomws306. I think I should add this in a note in the doc to help other users?

**Comment by dariomws306** [comment]
I think it's a good idea.

**Comment by scanum** [comment]
@officedocsbot reopen

**Comment by scanum** [comment]
@SirChristopher 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
