### ISSUE TITLE
Broken link - Overview 2. Virtual User License

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2806]
2. Obtain a free Phone System - [Virtual User license](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-add-on-licensing/virtual-user.md) or a paid Phone System license to use with the resource account.

https://docs.microsoft.com/en-us/MicrosoftTeams/teams-add-on-licensing/virtual-user.md
Hyperlink is broken = 404 - Page not found 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0703860-c3db-c723-317f-7fab164c006d
* Version Independent ID: c6384e2b-ac37-265d-8c33-f004eca97673
* Content: [Configure a resource account in Skype for Business Server 2019](https://docs.microsoft.com/en-us/SkypeForBusiness/hybrid/configure-onprem-ra#feedback)
* Content Source: [Skype/SfbHybrid/hybrid/configure-onprem-ra.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-onprem-ra.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
fixed in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/eba0ad472f55156c80e56ae8171be4e381018309#diff-0d26df467624d373d8cfa1b28c8c0595
