### ISSUE TITLE
Instructions not working

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2807]
As a Gold Partner deploying Teams calling, I am currently experiencing at least 75% of customer tenants are still missing the ability to purchase the free **Phone System - Virtual User** license version. I am based in Australia so this may be a regional issue that needs fixing.
When comparing a rare tenant that lists license vs tenant that doesn't is seem both have a different portal version/appearance despite both being in preview mode. The broken portal as i call it doesn't even let you scroll the screen, you have to reduce the zoom to see all options.
I have logged a ticket with Microsoft support: [Ticket #:15434498] and they are having to dish out full Phone System product keys on a 90 day trial, to allow us to license resource accounts on client tenancies. This will mean double handling customer roll-outs when this eventually gets fixed.
NB. Customers with this issue already have Phone System licenses and Call Plans.
For the rare tenant where virtual user licenses are actually listed for purchase, it's worth noting that the admin portal has to be in Preview mode for the instructions in this doco to work.

**Comment by SvenBell** [comment]
@waseemhashem  The purchasing instructions above only work in preview mode and Preview mode is again broken today for the Purchase services page. It's like today we get the non preview mode view in Preview mode but missing the **Phone System - Virtual User** license and the page won't scroll. It worked yesterday for the fist time in over a week and it's back on the blink again today. I have tested this issue on multiple tenants and another Microsoft partner has also confirmed they experience the same frustrating experience. We now have 2 weeks of Teams deployments backed up because we cannot get these essential licenses to assign PSTN numbers to Auto-Attendant/Call-Queues. Ticket #:15434498

**Comment by scanum** [comment]
@SvenBell  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@SvenBell Thank you for reaching out. Please can you send the link to the article you are referring to.  I work on the MS Docs side improving the articles where I can to help all users.

**Comment by scanum** [comment]
@SvenBell  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by SvenBell** [comment]
> As a Gold Partner deploying Teams calling, I am currently experiencing at least 75% of customer tenants are still missing the ability to purchase the free Phone System - Virtual User license version. I am based in Australia so this may be a regional issue that needs fixing.
> When comparing a rare tenant that lists license vs tenant that doesn't is seem both have a different portal version/appearance despite both being in preview mode. The broken portal as i call it doesn't even let you scroll the screen, you have to reduce the zoom to see all options.
> I have logged a ticket with Microsoft support: [Ticket #:15434498] and they are having to dish out full Phone System product keys on a 90 day trial, to allow us to license resource accounts on client tenancies. This will mean double handling customer roll-outs when this eventually gets fixed.
> NB. Customers with this issue already have Phone System licenses and Call Plans.
> For the rare tenant where virtual user licenses are actually listed for purchase, it's worth noting that the admin portal has to be in Preview mode for the instructions in this doco to work.

This issue was resolved after two weeks.

**Comment by SvenBell** [comment]
> @SvenBell  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
> Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/virtual-user

Document should state one needs to be in preview mode for instructions to work to purchase Phone System virtual user license.

**Comment by scanum** [comment]
@officedocsbot reopen

**Comment by scanum** [comment]
@SvenBell 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
