### ISSUE TITLE
Business Essentials included?

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2808]
RE: 

> Note
> Phone System is an add-on license available with Office 365 F1, E1, E3, and Office Premium licenses. Phone System is also included as part of Office 365 E5 licenses.

Q. Is Phone System also an add-on for Business Essentials? Teams works pretty good in a browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6891495-01c6-117b-c28b-28232782ba74
* Version Independent ID: 1c23b35a-e9ba-ffdd-9baa-a3f83f4ed9ca
* Content: [Phone System–Virtual User licenses ](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-add-on-licensing/virtual-user#feedback)
* Content Source: [Teams/teams-add-on-licensing/virtual-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/virtual-user.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@SvenBell thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by SvenBell** [comment]
Hi, Support will refer me to documentation, now documenter referring to support... Infinite loop?

**Comment by jambirk** [comment]
@scanum  This question needs a definitive answer from @waseemhashem who is unavailable until next week. This is not a question for support.

**Comment by waseemhashem** [comment]
no, Phone System is not an add on for Business Essentials

**Comment by SvenBell** [comment]
What defines if something is an add-on or not? nothing stops phone system being assigned to a user with Teams and Teams is included with Essentials: https://docs.microsoft.com/en-us/microsoftteams/office-365-licensing.
Phone System is speficied as a Team add-on: https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing
Is it just a case of what combinations of licenses that Microsoft is deciding to support? even if it technically works...
Please clarify
Many Thanks

**Comment by waseemhashem** [comment]
Thank you for sharing this feedback. At this time however, phone system is not available as an add-on to Office 365 Business Essentials subscription. To use the phone system in Office 365, there are alternative subscriptions such as Office 365 E1 and E3 that can be used together today.

**Comment by SvenBell** [comment]
@waseemhashem, Thank you for trying to clarify...
However...  
Option 3 in this Microsoft document specifies Phone System as an Add-On for Office 365 Essentials : https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/office-365-business-premium

Phone System is specified as a Microsoft Teams add-on in the following document: https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing
Are you now saying Phone System is not an add-on of Teams but rather selected subscriptions, which would make these documents incorrect?

Please clarify as there seems to be inconsistences in what is being said.
