### ISSUE TITLE
Instructions not working...

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2809]
As a Gold Partner deploying Teams calling, I am currently experiencing at least 75% of customer tenants are still missing the ability to purchase the free **Phone System - Virtual User** license version. I am based in Australia so this may be a regional issue that needs fixing.
When comparing a rare tenant that lists license vs tenant that doesn't is seem both have a different portal version/appearance despite both being in preview mode. The broken portal as I call it doesn't even let you scroll the screen, you have to reduce the zoom to see all options.
I have logged a ticket with Microsoft support: [**Ticket #:15434498**] and they are having to dish out full Phone System product keys on a 90 day trial, to allow us to license resource accounts on client tenancies. This will mean double handling customer roll-outs when this eventually gets fixed.
NB. Customers with this issue already have Phone System licenses and Call Plans.
For the rare tenant where virtual user licenses are actually listed for purchase, it's worth noting that the admin portal has to be in Preview mode for the instructions in this doco to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6891495-01c6-117b-c28b-28232782ba74
* Version Independent ID: 1c23b35a-e9ba-ffdd-9baa-a3f83f4ed9ca
* Content: [Phone System–Virtual User licenses ](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-add-on-licensing/virtual-user#feedback)
* Content Source: [Teams/teams-add-on-licensing/virtual-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/virtual-user.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by SvenBell** [comment]
@waseemhashem The purchasing instructions above only work in preview mode and Preview mode is again broken today for the Purchase services page. It's like today we get the non preview mode view in Preview mode but missing the Phone System - Virtual User license and the page won't scroll. It worked yesterday for the fist time in over a week and it's back on the blink again today. I have tested this issue on multiple tenants and another Microsoft partner has also confirmed they experience the same frustrating experience. We now have 2 weeks of Teams deployments backed up because we cannot get these essential licenses to assign PSTN numbers to Auto-Attendant/Call-Queues. Ticket #:15434498

**Comment by SvenBell** [comment]
**The latest from Microsoft Support:**

We have answered your questions below. Kindly provide your most convenient time for a callback. Thank you. 

1.	The Phone System Virtual User license was missing off the normal admin portal but was available in preview mode since 1st July, 2019. (this was after a 6 week period of Call Queues and Auto-Attendants having been migrated to Teams and then requiring paid licenses in the interim). As of 29th August the new free ($0.00) Phone System Virtual User license has also gone missing from the purchase service page in the admin portal for tenants who didn’t acquire it prior (yet those who have it already can increase these license numbers)
_As part of our ongoing process to update Call Queues and Auto Attendants in Microsoft Teams, Microsoft recently announced the transition to our latest cloud platform to improve performance and enable new features that customers have requested. However this is not yet officially available.  You may be able to view them to some tenants but not all since this is still a work in progress. Rest assured that once it is available, everyone should be able to have access to this either on preview on or off._ 
2.	The Purchase Services page does still not allow user to scroll on page to see all available products, unless you reduce magnification and have a large 4K screen to be able to read it.
_This portion is being determine by the settings on your pc, we can ask our technical team’s assistance on this._ 
3.	When will the Phone System Virtual User license be available again for purchase via Admin portal? I believe you mentioned by end of Q3 on phone.
_We expect commercial version to be available in early CY19-Q3. When the $0 SKU is available, customers can add the licenses to their tenant and use them to create Auto Attendants and Call Queues._
4.	While the provided 36 x 90 day product keys for Phone System Virtual User license be individual so I can apply them to any tenant in any quantity as required? (we are a Microsoft gold partner rolling Teams out to a large number of customers in our sales pipeline)
_The key provided to the customer will grant them 250 Phone System trial licenses that are valid for 90-days from the date of adding the licenses to the tenant. Customers must understand that they will need to replace these licenses with the $0 licenses before the 90-day expiration date
Kindly raise another ticket if you require another tenant with Phone System since the key is per tenant._ 
5.	Should I require further product keys what is the most efficient procedure?
_The best option is to wait for the $0 SKUs to be published. Each customer will be able to acquire 25 Voice Apps SKUs plus 1 Voice App SKU for every 10 Phone System (or E5) licenses they own. As an example, a customer with 1000 phone system licenses (add-on or E5) will be entitled to 125 (25+100) $0 Voice Apps licenses. These licenses can be used to enable Auto-Attendant and Call Queues with service phone numbers._
6.	Will our existing client Phone System Virtual User licenses need to be replaced at some stage in the future if you are releasing a new Phone System Virtual User license SKU? (you mentioned that the new license would added further features and functionality)
_There should be no impact on existing Phone system virtual user licenses. The new SKU will apply on new orders._ 
7.	Why has this licensing change/issue not been publicly announced?
_There were Microsoft blogs mentioning the $0 SKU: Auto Attendant and Call Queues Service Update blog_ 
8.	Could you please provide a more details explanation of what has happened?
_Unfortunately the work to implement the new licensing enforcement was completed ahead of availability of the $0 Voice Apps SKU. This created issues for some customers. Specifically, they were not able to create new Auto Attendants of Call Queues._ 
 
If you have any question, please don’t hesitate to let me know. We are always here to assist you.

**Comment by scanum** [comment]
@SvenBell thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by SvenBell** [comment]
This has finally been resolved after 2 weeks. Documentation is now reflecting reality.

**Comment by jambirk** [comment]
I think it's a case of reality changing to reflect the documentation, which captured the intended behavior. Still, glad it's resolved.
