### ISSUE TITLE
Incorrect link (fwlink) address.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#281]
Link to Skype Debugging tools is wrong.  It takes to the Lync 2013 version. Please update the fwlink.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888fcfa7-e18a-f60d-734c-a38293e2baf0
* Version Independent ID: c85ef7a6-9323-5828-4544-c284f821c242
* Content: [Centralized Logging Service in Skype for Business 2015](https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/centralized-logging-service/centralized-logging-service)
* Content Source: [Skype/SfbServer/management-tools/centralized-logging-service/centralized-logging-service.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/management-tools/centralized-logging-service/centralized-logging-service.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
fwlink updated.
