### ISSUE TITLE
Firewall mentions in https://docs.microsoft.com/en-us/microsoftteams/manage-external-access#step-2---test-it

### ISSUE THREAD

**Issue by aparadis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2816]
In the test section, there are mentions of a firewall causing possible connectivity issues with external orgs.   This section should link to or contain which firewall ports/flows need to be verified.

Otherwise, blaming a firewall without any troubleshooting steps doesn't help either the user experiencing the issue, or the sysadmin that will read this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external access (federation) in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access#step-2---test-it)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@aparadis  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@aparadis Thank you for reaching out and helping improve MS Docs. Please have a look at this link to see if it helps answer your question. https://docs.microsoft.com/microsoftteams/connectivity-issues.

**Comment by scanum** [comment]
@aparadis  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
