### ISSUE TITLE
Link not working.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#282]
Link for "Deploy the Skype for Business client for your organization" is not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f197a2aa-a594-2060-214d-13feec001241
* Version Independent ID: 168908eb-a176-42c6-8071-631aeafa13c7
* Content: [Deploy clients for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/deploy-clients)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/deploy-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/deploy-clients.md)
* Service: **unspecified**
* Product: **skype-for-business-itpro**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by jambirk** [comment]
I just tried. It worked for me.

**Comment by kenwith** [comment]
Works for me too.

**Comment by kenwith** [comment]
@nsshommo - did you check and it was not working? Can  you check again? closing this but reopen if it is not working for you.

**Comment by kenwith** [comment]
The link is not working for me now either.

**Comment by kenwith** [comment]
@jambirk - can you see if it works for you? It was working when I first clicked but not now.. maybe link went away on SOC? It is the link in the See Also section.

**Comment by jambirk** [comment]
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/pull/1032 contains the fix

**Comment by jambirk** [comment]
fix is merged with master, the next master -> live merge will resolve
