### ISSUE TITLE
UI way to do this?

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2823]
I want to have a Teams Phone in the conference room so users can invite that room on their Exchange Online calendars, then go in the room and join from the shared team phone device. Do I really need a bunch of PowerShell to do this? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Office 365](https://docs.microsoft.com/en-us/microsoftteams/room-systems/with-office-365)
* Content Source: [Teams/room-systems/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/with-office-365.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@eschrader thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by eschrader** [comment]
Thanks Scanum, my question is related to this documentation and if there is an OOTB way to do this that is not a custom PS Script with a large amount of custom functions. If there is a way in the UI to add a new room account, I would like to request that method is documented.  Thank you, Eric
