### ISSUE TITLE
Commandlets for tabs/apps? 

### ISSUE THREAD

**Issue by NewJ123** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2824]
Any plans to release command lets for adding tabs and apps to channels?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26362d70-cfce-2eea-077b-4aaa50f92e8b
* Version Independent ID: f52dcd4d-4f58-05c4-11b0-f1e3c95f4d89
* Content: [Teams PowerShell Overview](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-overview)
* Content Source: [Teams/teams-powershell-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@NewJ123 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by NewJ123** [comment]
I don't think there is anything to resolve in my tenant and/or its a tenant specific ask/issue. My question is about the roadmap of PS command-lets to create/configure tabs in teams. I don't see any command available as of now, so wanted to check if its in roadmap and/or possible eta
