### ISSUE TITLE
Main note ...

### ISSUE THREAD

**Issue by rickleye** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2826]
Just wanted to mention that not all the servers need to be domain joined. Especially the edge servers and possibly reverse proxy as well. Perhaps we could be more clearer. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9131450-3053-fff6-0e01-36c7b3fd076f
* Version Independent ID: 0ad5a095-cbfd-5bcb-6f75-6f696b8215e7
* Content: [Prepare Active Directory for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/install/prepare-active-directory?toc=%2FSkypeForBusiness%2Ftoc.json&bc=%2FSkypeForBusiness%2Fbreadcrumb%2Ftoc.json#feedback)
* Content Source: [Skype/SfbServer/deploy/install/prepare-active-directory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/install/prepare-active-directory.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@rickleye Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LanaChin** [comment]
Merged changes by @VLG17.
