### ISSUE TITLE
Phone System and Calling Plans available with Office 365 Business Essentials/Premium??

### ISSUE THREAD

**Issue by AndySanchezVM** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2827]
This is a little confusing. Can you please clarify?  According to Option 3, #2 above "If you use an Enterprise E1 or E3 license or an Office 365 Business Essentials or Office 365 Business Premium licsense you will need to buy the Phone System add-on." 

However, under the How to see prices and buy section it mentions: "To get Phone System and a Calling Plan: 1. Switch to the E1 or E3 plan."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 177f5cdc-62a7-327f-64e8-97c5b01b70fc
* Version Independent ID: 0aa4a92b-26c5-29eb-5ebd-0117c35c177a
* Content: [Office 365 Business Premium ](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-add-on-licensing/office-365-business-premium#feedback)
* Content Source: [Teams/teams-add-on-licensing/office-365-business-premium.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/office-365-business-premium.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@AndySanchezVM Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LucaVitali** [comment]
Hi,
agree with AndySanchezVM, also the "Option 2" is strange, it say to keep your plan (Business Plan in this case) and add Phone System license, but if I'm not wrong there aren't any Phone System Licence available in Business Plan, it's available in Enterprise Plan only.

"Option 2. Keep your plan, and buy a Phone System and a Domestic or Domestic and International Calling Plan."

**Comment by Joshtehira** [comment]
I agree this is odd. However I would be very happy if this is correct as the licensing for voice on Teams compared to Skype for Business is lacking. To do voice, all we needed was Skype for Business P2, and once Skype for Business P1 was retired all Business Plans had the entitlements for Skype for Business P2 (which enabled voice) But as you can only get phone system as an addon to Enterprise plans I can see why we would need to have one to attach Phone System. If MS could clarify that would be great as we want to deliver a fully supported Direct Routing offer to clients using Business Premium.

**Comment by LucaVitali** [comment]
> we want to deliver a fully supported Direct Routing offer to clients using Business Premium.

Agree with you, we want/need to deliver the same to our customers

**Comment by Joshtehira** [comment]
Hi Luca, I may have found the solution to our problem. Let me give it a try.

**Comment by scanum** [comment]
@AndySanchezVM Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by AndySanchezVM** [comment]
@sabinn-msft - I think we can all agree that this issue has **NOT** been resolved.  Please re-open this and/or let us know what your "solution" is.

**Comment by sabinn-msft** [comment]
Sorry, you probably have the wrong contact.

**Comment by AndySanchezVM** [comment]
> Sorry, you probably have the wrong contact.

Sorry about that Sabinn.
