### ISSUE TITLE
Can't use this feature for a certain number

### ISSUE THREAD

**Issue by rwgeach** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2830]
ticket 15527507

try to call a 931 area code number from Teams/Skype p2p and it rings and the person on the other end hears the ring and can pick the call up.

try to call the same number using Audio Conferencing Dial-Out and it never rings.  IT NEVER RINGS.

try to call any other number in the United States and it rings the destination.  ANY OTHER NUMBER AND IT RINGS.

someone please explain why I have to futz around with MPN support for 3 weeks just to try and perform a PSTN dial-out from from a black-box service?

get it together microsoft.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 037fe22c-ba09-e381-231d-c37f6bb2a774
* Version Independent ID: e8046130-d407-3155-53c5-9043110cd793
* Content: [Audio Conferencing subscription “Dial-Out”/“Call Me At” benefit](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-subscription-dial-out#feedback)
* Content Source: [Teams/audio-conferencing-subscription-dial-out.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-subscription-dial-out.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@rwgeach Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@rwgeach I have looked into this but could not find any known issues. Keeping in mind that it works for any other number in the US except those starting with "931", this sound like a specific issue which needs support intervention - which you already did, keeping in mind that you attached a support ticket.

Did support manage to solve this? I'm sorry you had to wait so long and that it's not something that i can help with.

**Comment by rwgeach** [comment]
support is still working on it, but no resolution so far.

**Comment by scanum** [comment]
@rwgeach Once you get a response please let us know to see if there is a way for us to implement it into the docs. For now, I will close this issue. Thanks for your feedback.

**Comment by robgeach** [comment]
the response from support has been inadequate which is why the issue was opened here.  now the response from here is also inadequate.
