### ISSUE TITLE
Supported .NETversion with CQD 2019

### ISSUE THREAD

**Issue by rimroot** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2835]
What is the latest .NET version supported by CQD 2019? I have installed it on Windows Server 2016 with .NET 4.8 and it does not work properly. I am getting error when trying to save new report. Now I am not sure whether it is .NET version issue, or something else. The error says "We couldn't save the report. Try saving again".

![image](https://user-images.githubusercontent.com/29730129/63017828-f7eb9600-be9f-11e9-96b1-d30173b84c3c.png)

Error in the event log:
![image](https://user-images.githubusercontent.com/29730129/63017891-26697100-bea0-11e9-8874-4daeb93baa81.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f91216e8-0b6c-88b1-635a-401529556f78
* Version Independent ID: 0b0e068d-b870-bbd2-550d-07917ec63926
* Content: [Plan for Call Quality Dashboard for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/call-quality-dashboard/plan#feedback)
* Content Source: [Skype/SfbServer/management-tools/call-quality-dashboard/plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/management-tools/call-quality-dashboard/plan.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@rimroot 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
