### ISSUE TITLE
IP Phone comparison workbook

### ISSUE THREAD

**Issue by D-Jeffrey** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2839]
The link does not work.  Should it be something like https://products.office.com/en-ca/microsoft-teams/across-devices/devices instead?  Is there a comparison view?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aa4ede2-1b9a-f63f-541f-ddadb4bdd3cf
* Version Independent ID: 37bea9e3-4a9b-22a9-4476-ea82c9d5ed77
* Content: [Partner qualification for Lync](https://docs.microsoft.com/en-us/skypeforbusiness/lync-cert/ip-phones#feedback)
* Content Source: [Skype/SfbPartnerCertification/lync-cert/ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbPartnerCertification/lync-cert/ip-phones.md)
* Service: **skype-for-business-online**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by dougand-MSFT** [comment]
@kruthikaponnusamy is this something you or Vijay would know about?

**Comment by scanum** [comment]
@D-Jeffrey  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
