### ISSUE TITLE
Documentation doesn't inform users that separate procedures are required for blocking default apps

### ISSUE THREAD

**Issue by Krytical13** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2847]
The documentation might want to mention that there is no way to prevent users from accessing the default apps:
"Chat, Activity, Calls, Files, Help, Stream, Teams, Wiki"

For companies like us that are using Skype For Business for IM/Screen Share, and want to move to Teams without all of the extra features, it would save a lot of time researching and testing...
 (We just wanted the "Chat" app, for now, nothing else until we can properly manage those other features)

We have created policies set to "block all apps" for the "Microsoft Apps" section of the policy, however, it does not block those default apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 143108bb-d6e6-48a8-a7cb-d11b89ebeaab
* Version Independent ID: 145773e2-149e-1c1c-5797-433c13f13b22
* Content: [Admin settings for apps in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/admin-settings#feedback)
* Content Source: [Teams/admin-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/admin-settings.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Krytical13 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@Krytical13 The issue you are raising has been addressed multiple times on UserVoice for Teams - https://microsoftteams.uservoice.com/. I recomment to watch the threads on UserVoice and vote in order to get as much traction as possible on implementing the changes.

Although i have not tested this related to Teams, you could in theory use Graph to tweak Teams into looking as you want (not applicable to default apps/tabs) : https://docs.microsoft.com/en-us/graph/api/teamsappinstallation-list?view=graph-rest-1.0&tabs=http

**Comment by Krytical13** [comment]
Thanks, VLG17.
I was more pointing out that this isn't properly documented anywhere in the Official Microsoft documentation.
The official documentation might have you believe that you are able to simply block everything, including the default apps, without jumping through hoops in multiple locations.

But as an aside, I personally think it's terrible practice to have users checking UserVoice, and Community Forums and Official Documentation, and Blog Articles on Technet or whatever the new support site is for MS...
How are people even supposed to find out about these "unofficial" documentation sources in the first place?  Google?
There are SO MANY PLACES to find information...  
The official documentation should be the only place that Administrators should have to go to find this information because it's the only one that people are guaranteed to be able to find through official channels.

**Comment by scanum** [comment]
@Krytical13 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
