### ISSUE TITLE
Mismatch between text and screenshot

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2848]
In [this section](https://docs.microsoft.com/en-us/microsoftteams/teams-app-permission-policies#manage-org-wide-app-settings) the text says the setting is "Allow third-party or custom apps in Teams:", but the screenshot shows "Allow third-party apps in Teams". Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b51eda6c-168c-7d99-7cc1-992b3d8feef2
* Version Independent ID: 118a1b8f-f4b7-a778-70b1-d3161fc548ab
* Content: [Manage app permission policies in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-app-permission-policies#manage-org-wide-app-settings)
* Content Source: [Teams/teams-app-permission-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-permission-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@clearab Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@clearab I have checked and the text is right (the screenshot is outdated)

![image](https://user-images.githubusercontent.com/41186174/65018777-8be2ce80-d932-11e9-8351-fff4d55fa070.png)
