### ISSUE TITLE
Teams Guest User

### ISSUE THREAD

**Issue by robertv42** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2849]
Hallo Team,
wenn ich einen Nutzer außerhalb meiner Domain in Teams einlade. 
Wie kann ich ihn dann Zugriff auf moodle gewähren?
Beste Grüße
Robert

Hello Team, 
if I invite a user to MS Teams, how can I provide these user access to moodle. 
Regards
Robert

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 66c68e6d-936e-68f0-7405-d1e0fec62670
* Version Independent ID: f954014f-8c01-08fa-9afb-476feeb346b2
* Content: [Installieren der Moodle-Integration in Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/install-moodle-integration#feedback)
* Content Source: [Teams/install-moodle-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/install-moodle-integration.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@robertv42 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
