### ISSUE TITLE
We use Office365 fBE and I just need to know what I need to do to keep it going

### ISSUE THREAD

**Issue by TrojanekZ** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2854]
Absolutely confused text that doesn't solve my underlying problem at all: How users in the company will interact with corporate customers who continue to use Lync / SfB. Confused talk about MS Azure accounts won't help me. We use Office365 fBE and I just need to know what I need to do to keep it going.

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 56ab9d91-d5c4-be13-660e-10b1fdacadec
* Version Independent ID: efdd6696-1415-26ae-ab56-5e758a34311c
* Content: [Upgrade checklist](https://docs.microsoft.com/cs-CZ/microsoftteams/upgrade-basic?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/upgrade-basic.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-basic.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by jambirk** [comment]
Coexistence gets complex: have a look at https://docs.microsoft.com/microsoftteams/migration-interop-guidance-for-teams-with-skype  which may answer your questions

**Comment by scanum** [comment]
@TrojanekZ 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
