### ISSUE TITLE
Moodle translation to Russian

### ISSUE THREAD

**Issue by dgaripov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2855]
Hi colleagues, I would recommend to translate "Moodle" to Russian language as "Мудл", not as "Мудле". It's how this LMS traditionally sounds in our conversations. Or even left Moodle name in English. "Мудле" sounds in Russian quite strange :).

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 66c68e6d-936e-68f0-7405-d1e0fec62670
* Version Independent ID: f954014f-8c01-08fa-9afb-476feeb346b2
* Content: [Установка интеграции Мудле с Microsoft Teams](https://docs.microsoft.com/ru-ru/microsoftteams/install-moodle-integration#feedback)
* Content Source: [Teams/install-moodle-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/install-moodle-integration.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@dgaripov  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@MollyMalone

**Comment by OfficeGlobal** [comment]
@dgaripov article has been HumanTranslated and published live. The string "Moodle" was left in ENG

**Comment by scanum** [comment]
@dgaripov 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Odilbukh** [comment]
![image](https://user-images.githubusercontent.com/22895615/87128528-9fa24d00-c244-11ea-9cb4-04edfdebb99c.png)

What is wrong? Please help! 
Thanks!
