### ISSUE TITLE
Incorrect Documentation

### ISSUE THREAD

**Issue by NickDorak** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#286]
There is a note "To save time or automate this, you can use the Set-CsOnlineDialInConferencingBridge cmdlet", but this command doesn't appear to have the option to change this setting. Perhaps you should include an example. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02fca567-f57d-89b9-e342-354df84f0a5f
* Version Independent ID: 3f12a800-3722-d015-e522-a5db4eed4b0c
* Content: [Turn on or off entry and exit announcements for meetings](https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/turn-on-or-off-entry-and-exit-announcements-for-meetings)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/turn-on-or-off-entry-and-exit-announcements-for-meetings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/turn-on-or-off-entry-and-exit-announcements-for-meetings.md)
* Service: **skype-for-business-online**
* Product: **unspecified**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@NickDorak - we are currently adding more examples to the cmdlets. I opened an issue in the repo where the cmdlet lives so you can track. Here is a link: https://github.com/MicrosoftDocs/office-docs-powershell/issues/1406

Thanks for the feedback and for taking the time to provide this gap. It is appreciated!

**Comment by kenwith** [comment]
@NickDorak - I was able to confirm today you were exactly right. Thank you for taking the time to report. This should be to: https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinedialinconferencingtenantsettings?view=skype-ps

I have submitted a Pull Request with the fix here: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/538
