### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2860]
The link on: "**Cumulative update 7 for Skype for Business Server 2015, Front End server and Edge server**" is:
https://support.microsoft.com/kb/3134260
But in my mind it should be:
https://support.microsoft.com/kb/4340904

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be9f745c-5925-3a7b-9430-b5e61b4384ba
* Version Independent ID: bc23dce3-f38b-9e81-1614-d16aed1d8684
* Content: [Skype for Business Server updates](https://docs.microsoft.com/en-us/skypeforbusiness/sfb-server-updates)
* Content Source: [Skype/SfbServer/sfb-server-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/sfb-server-updates.md)
* Product: **skype-for-business-server**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Petri-X  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Petri-X** [comment]
Not in my mind. At least when looking for the source of the page it still says:

Cumulative update 7 for Skype for Business Server 2015, Front End server and Edge server
< href="https://support.microsoft.com/kb/3134260" >KB 4340904
July 2018
