### ISSUE TITLE
What about deleted Channels?

### ISSUE THREAD

**Issue by Arkano87** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2861]
How to recovery a deleted Channel, guys??

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 5bf689b7-a7c1-121f-578e-029e8a89c4f0
* Version Independent ID: 7e6b449e-bd77-2fc4-2c3d-1f2e364e1b76
* Content: [Arquivar ou excluir uma equipe no Microsoft Teams](https://docs.microsoft.com/pt-BR/MicrosoftTeams/archive-or-delete-a-team#feedback)
* Content Source: [Teams/archive-or-delete-a-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/archive-or-delete-a-team.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Arkano87  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@MollyMalone @OfficeGlobal

**Comment by lindspea** [comment]
@Arkano87 Please see note in article regarding deleting Teams, channels, etc. - 
"Important - Archived teams can be reactivated, but you can’t undelete a team that has been deleted. Consider archiving the team first, and postpone the deletion until you're sure that you no longer need the team."

**Comment by scanum** [comment]
@Arkano87 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Mariaap84392498** [comment]
Windows 10 version1709 very good, thank you.
