### ISSUE TITLE
Error in PowerShell example "to enable CDR in multiple locations"

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2867]
The PowerShell code in section "To use a single command to enable CDR in multiple locations" is incorrect.

current (incorrect) code:
Get-CsCdrConfiguration | Set-CsCdrConfiguration "site:Redmond" -EnableCDR $True

correct code:
Get-CsCdrConfiguration | Set-CsCdrConfiguration -EnableCDR $True

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6948c4-9823-430c-a8e3-129a51574033
* Version Independent ID: 3ad280e3-c3c8-ad7e-19c8-e894dbce7095
* Content: [Enable call detail recording in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/manage/health-and-monitoring/enable-cdr?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json)
* Content Source: [Skype/SfbServer/manage/health-and-monitoring/enable-cdr.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/health-and-monitoring/enable-cdr.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@shivtorov Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
