### ISSUE TITLE
64-bit versus 32-bit compatibility 

### ISSUE THREAD

**Issue by chelsrichards** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#287]
The Teams Meeting add-in isn't appearing in Outlook for my team members, and I was hoping to find out if it's due to a 64-bit versus 32-bit compatibility issue from this article. Our company's Windows server is 64-bit, but our Outlook is 32-bit. The Teams desktop version we've downloaded is 64-bit. Could this be why we're not seeing the add-in? Please update the article if this is the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Use the Microsoft Teams Meeting add-in in Outlook](https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* Product: **unspecified**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by kenwith** [comment]
@chelsrichards - I am sorry for the long delay and for this stagnating in the issues list here. 

It has been a very long time and I am hoping you have already resolved this issue. If you haven't, I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
