### ISSUE TITLE
Error in powershell cmd for Skype for Business Server

### ISSUE THREAD

**Issue by lcansby** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2875]
In the section "Enable the user account with Skype for Business Server" the powershell for checking available RegistrarPool should be changed from:
Get-CsOnlineUser -Identity 'alice@contoso.com'| fl *registrarpool*
to:
Get-CsUser -Identity 'alice@contoso.com'| fl *registrarpool*

Since the article is about activating on a Skype for Business server and not Skype for Business Online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee417633-3d52-646b-2ef0-94f71535db75
* Version Independent ID: 527bb7f0-b4a7-108c-6f86-8fadced63b86
* Content: [Deploy Microsoft Teams Rooms with Exchange Online](https://docs.microsoft.com/en-us/microsoftteams/room-systems/with-exchange-online#feedback)
* Content Source: [Teams/room-systems/with-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/with-exchange-online.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@LanaChin Could you please aid us by confirming the issue raiser's solution? Thanks

**Comment by LanaChin** [comment]
@sohailta - can you help us confirm whether the command should be changed? Thank you.

**Comment by scanum** [comment]
@sohailta Hi Sohail, any updates on this? Thanks!

**Comment by LanaChin** [comment]
@scanum - confirmed that its OK to make this change.  Thank you.

**Comment by LanaChin** [comment]
Merged PR. Closing issue. Thanks.
