### ISSUE TITLE
Import PSSession missing

### ISSUE THREAD

**Issue by lcansby** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2876]
In the section "Create an account and set Exchange properties" Step 1 the powershell should end with importing the PSSession: 
Import-PSSession $sess -DisableNameChecking 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee417633-3d52-646b-2ef0-94f71535db75
* Version Independent ID: 527bb7f0-b4a7-108c-6f86-8fadced63b86
* Content: [Deploy Microsoft Teams Rooms with Exchange Online](https://docs.microsoft.com/en-us/microsoftteams/room-systems/with-exchange-online#feedback)
* Content Source: [Teams/room-systems/with-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/with-exchange-online.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@lcansby Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
