### ISSUE TITLE
typo in example 

### ISSUE THREAD

**Issue by bigred3142** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2877]
In this paragraph -&gt;      The SBC requires a certificate to authenticate the connections. For the SBC hosting scenario, the carrier needs to request a certificate with SAN *.base_domain (for example, *customers.adatum.biz). This certificate can be used to authenticate connections to multiple tenants served from a single SBC.

the example is missing the dot  (should be *&lt;dot&gt;customers.adatum.biz) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure a Session Border Controller for multiple tenants](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-sbc-multiple-tenants)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by lindspea** [comment]
@bigred3142 Thank you for pointing this out and helping improve MS Docs.  It looks like the article has been updated in the interim. Please check from your side and let me know.

**Comment by scanum** [comment]
@bigred3142 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
