### ISSUE TITLE
Issue with Hyperlinks

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2879]
hyperlinks on the page need to be checked as several go to a 404 Page Not Found. 

IE: An example of a small business implementation is available in Small business example - Set up an auto attendant and Small business example - Set up a call queue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0703860-c3db-c723-317f-7fab164c006d
* Version Independent ID: c6384e2b-ac37-265d-8c33-f004eca97673
* Content: [Configure a resource account in Skype for Business Server 2019](https://docs.microsoft.com/en-us/SkypeForBusiness/hybrid/configure-onprem-ra#feedback)
* Content Source: [Skype/SfbHybrid/hybrid/configure-onprem-ra.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-onprem-ra.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Fixed the links, should update in under an hour.
