### ISSUE TITLE
メーカー「Yealink」の正しい翻訳、表示をお願いいたします

### ISSUE THREAD

**Issue by qloogfukaumi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2880]
担当者様

正しいメーカー名での表示がなされるよう、ご修正をお願いいたします。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: aaaef9e1-8f1c-ebf0-7856-4c007342a2c3
* Version Independent ID: 3eaf671f-375e-8787-9c66-3947c3606559
* Content: [Teams 用の電話とデバイス](https://docs.microsoft.com/ja-jp/microsoftteams/teams-ip-phones)
* Content Source: [Teams/teams-ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-ip-phones.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by OfficeGlobal** [comment]
@TinaMcN , @scanum Working on a fix (Bug 3590631)

**Comment by OfficeGlobal** [comment]
@qloogfukaumi , @TinaMcN , @scanum  the article has been HumanTranslated and published live

**Comment by qloogfukaumi** [comment]
@OfficeGlobal 
Hi Team ,
Thank you for taking your time to fix that.
Regards,

**Comment by naoki0311** [comment]
@OfficeGlobal 

https://docs.microsoft.com/ja-jp/microsoftteams/teams-ip-phones

昨年修正のご対応いただいたページをたまたま本日眺めていたところ、
一部だけまだ、【ごみ箱】記載が残っています。
お手数をおかけしますが修正対応いただけないでしょうか。

![image](https://user-images.githubusercontent.com/2058708/77597507-76360d80-6f42-11ea-93de-fcf7dd7fd1b0.png)
