### ISSUE TITLE
Get Teams Template

### ISSUE THREAD

**Issue by ashleywb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2883]
Is it possible to identify which template a Microsoft Team has been created from using the API? Looking I can't see this information when Getting a Team or Listing Teams?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d884cb-c126-b5dc-ff90-1a31aa61bf5b
* Version Independent ID: ed5054d7-d679-7fad-fd5d-9cd393644b9d
* Content: [Get started with Teams templates](https://docs.microsoft.com/en-us/MicrosoftTeams/get-started-with-teams-templates#feedback)
* Content Source: [Teams/get-started-with-teams-templates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-started-with-teams-templates.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by lindspea** [comment]
@LolaJacobsen could you perhaps assist? Is this available yet?

**Comment by lindspea** [comment]
@ashleywb Thank you for reaching out and helping improve MS Docs. Please see information from this article - https://docs.microsoft.com/graph/api/team-post?view=graph-rest-beta. "Base template types are special templates that Microsoft created for specific industries. These base templates often contain proprietary apps that aren't available in the store and team properties that are not yet supported individually in Microsoft Teams templates." Let me know if you need further assistance. Please see also https://docs.microsoft.com/graph/api/team-post?view=graph-rest-beta

**Comment by scanum** [comment]
@ashleywb Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by akarczag** [comment]
Those articles don't inform how to find the template for an existing Team. How can that be accomplished?
