### ISSUE TITLE
Enable local monitoring databases?

### ISSUE THREAD

**Issue by tylerwb15** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2886]
Based on the first diagram, it appears that the Call Data Connector can be configured to send data only to the online CQD:
"With Call Data Connector, the Skype for Business Server pushes call data to the cloud service so that you can leverage the Skype for Business Online Call Analytics (CA) and Call Quality Dashboard (CQD) tools, as shown in the following diagram"
Additionally, the second diagram explains an ability to submit data to both Online CQD and premise monitoring:  "Of course, you might want to keep some call quality data on premises."
This implies that there is an alternative deployment for cloud only monitoring and a hybrid solution of on-premise and cloud based monitoring.

However, this article also states that "monitoring must be enabled on the front end pool".  

The question: Is there a way to enable the "local Monitoring Databases" in SfB on Premise (i.e. the caching monitoring databases on the frontend), without deploying a Monitoring SQL server backend?  If so, how?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87ba30d1-a7b1-7b12-66e3-dbd75ee62a47
* Version Independent ID: 776dd776-b0b0-3088-6549-ec01b549f1d0
* Content: [Plan Call Data Connector](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-call-data-connector#feedback)
* Content Source: [Skype/SfbHybrid/hybrid/plan-call-data-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/plan-call-data-connector.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by lindspea** [comment]
@tylerwb15 thank you for reaching out and helping improve MS Docs.  Please have a look at this recent article.  Hopefully this helps. https://docs.microsoft.com/skypeforbusiness/deploy/deploy-monitoring/deploy-monitoring

**Comment by scanum** [comment]
@tylerwb15 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
