### ISSUE TITLE
what is an "organization" and who is defined as "the first person whi signs up"?

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2887]
Can you explain how exactly this is defined?
"In the free version of Microsoft Teams, the first person who signs up in your organization has a limited admin role"
What is a teams organization?
Where this organization in teams is shown?
Where and how a non admin can see, who is the admin of this organization?
Is ist the first person the person, who registered to teams?
The issue: I registered to teams, I am not an admin, so I can't add members. But I don't know, who is marked as admin of my "organization".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9cf9c6a-ae69-3bf6-9123-0d5b24c63c8c
* Version Independent ID: 3becb7ac-cddf-01f8-cf48-114b4771dc3f
* Content: [Manage the free version of Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-freemium#feedback)
* Content Source: [Teams/manage-freemium.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-freemium.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by lindspea** [comment]
@aisbergde thank you for reaching out. Please have a look at this article and let me know if it helps answer some of your question - https://support.office.com/article/manage-your-teams-free-organization-5208c55a-5d66-416c-b99a-1028c3fef637

**Comment by aisbergde** [comment]
Hallo Lindsay,

what I miss in the documentation:
- the link to the admin center, like https://admin.teams.microsoft.com/
- the explanation, what is an organisation. For example: "if a user
registers with aaa.bbb@xxxx.zz then xxxx.zz is the organization" Or show
the "organization" in teams
- an information, who is the administrator of the organization. If you are
in teams and don't have admin rights, how you will know who (from your
organization) to contact?
--
Grüße
*Germo Görtz*
Arzt-Kybernetiker
Experte für Business Intelligence mit Microsoft SQL Server
goertz@aisberg.de
Chat, Anruf: http://telegram.me/germo_goertz

Telefon (Hauptnummer, O2):
+49 179 5460319, +49 30 40797874
beides gleiche SIM, aktuell im Projekt schlecht erreichbar
VOIP (satellite.me):
+47 15678 682219, dort gerne Nachricht hinterlassen
falls alle anderen nicht funktionieren (Vodafone):
+49 1522 2305138

IT-Profil bei freelancermap:
https://www.freelancermap.de/freelancer-verzeichnis/profile/entwicklung/154512-profil-germo-goertz-microsoft-bi-architekt-entwickler-analyticscreator-dwh-elt-etl-tsql-ssas-olap-mdx-machine-learning.html

IT-Profil bei GULP:
http://www.gulp.de/gulp2/home/profil/aisberg

*Bewerten Sie bitte die Zusammenarbeit mit mir! *
http://goo.gl/VTLVDj
Die Bewertung erscheint auf meinem freelancermap Profil.

*exzellente russische zeitgenössische Kunst meiner Familie:*
http://www.boruch-art.de/
http://www.levitskaia-art.de/
http://artoftherussias.wordpress.com/category/jewish/eduard-steinberg/

*evolutionärer Vorteil der Zweigeschlechtlichkeit:*
http://sexualdimorphismus.blogspot.de/


Am Di., 27. Aug. 2019 um 16:25 Uhr schrieb Lindsay <notifications@github.com

**Comment by lindspea** [comment]
@aisbergde Here is another article that might help - https://docs.microsoft.com/microsoftteams/manage-freemium

**Comment by lindspea** [comment]
@aisbergde see this tech community article for more information. Let me know if this helps. https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/Introducing-a-free-version-of-Microsoft-Teams/ba-p/214592

**Comment by scanum** [comment]
@aisbergde Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by lindspea** [comment]
Related issue #2889
