### ISSUE TITLE
Link auf Vorgehensweise bei der kostenlosen Teams Version

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2888]
Da das hier beschriebene wohl nicht auf die kostenlose Version von Teams zutrifft (oder doch?), wäre ein entsprechender Hinweis und Link nützlich, wie die kostenlosen Teams-Versionen verwaltet werden.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6b434530-6bf2-6e00-6eae-6fa043d022ce
* Version Independent ID: caab785f-e3a4-831a-87d8-26934a9f834f
* Content: [Verwenden von Microsoft Teams-Administratorrollen zum Verwalten von Teams](https://docs.microsoft.com/de-de/microsoftteams/using-admin-roles)
* Content Source: [Teams/using-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/using-admin-roles.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by OfficeGlobal** [comment]
**Bing translator:** "Since the one described here probably does not apply to the free version of Teams (or is it?), a corresponding hint and link would be useful on how the free teams versions are managed."
___
@scanum It seems the question is for a writer not for a loc. team

**Comment by lindspea** [comment]
@aisbergde https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2887 See related issue.

**Comment by scanum** [comment]
@aisbergde 
Thank you for submitting feedback. We understand that this issue is already being resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
