### ISSUE TITLE
last command is incorrect

### ISSUE THREAD

**Issue by Lelivienne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2890]
first of all objects from AAD do not have 'emailaddress' atrribute - should 'mail'
second of all, mail is not identity. i'd rather use 'UserPrincipalName' which is valid user identity. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58ea9573-59b1-1499-fb83-517d0ee0f034
* Version Independent ID: bf98f739-ff51-0b90-dbc5-c594d3dacecd
* Content: [Manage the Shifts app for your organization in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams#feedback)
* Content Source: [Teams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams.md)
* Service: **msteams**
* GitHub Login: @kenwith
* Microsoft Alias: **v-lanac**

**Comment by lindspea** [comment]
@Lelivienne Thank you for reaching out and helping improve MS Docs. Are you suggesting changing the command from $members | ForEach-Object { Grant-CsTeamsAppSetupPolicy -PolicyName "FirstlineWorker" -Identity $_.EmailAddress TO $members | ForEach-Object { Grant-CsTeamsAppSetupPolicy -PolicyName "FirstlineWorker" -UserPrincipalName

**Comment by Lelivienne** [comment]
yes. that's what i used. 'emailaddress' is definitely wrong as such attribute do not exist on the object.

**Comment by scanum** [comment]
@Lelivienne Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
