### ISSUE TITLE
flowchart should be an image 

### ISSUE THREAD

**Issue by bigred3142** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2895]
too small to read - cant be manipulated at all 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c93b9d8-9949-4586-2429-b4c73d4e077c
* Version Independent ID: e7d46cc4-620d-6779-3412-3e3fe4dac770
* Content: [Lync Server 2013: Upgrade or update Front End Servers](https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-upgrade-or-update-front-end-servers)
* Content Source: [Lync/LyncServer/lync-server-2013-upgrade-or-update-front-end-servers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Lync/LyncServer/lync-server-2013-upgrade-or-update-front-end-servers.md)
* Product: **lync-server-2013**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@bigred3142 Thank you for submitting feedback and contributing to the docs. We are looking into this.

**Comment by dplotnikov** [comment]
@bigred3142 there are some certain policies on the size of the images in the article but basically all images have the proper size. As a workaround, you can just copy image address via your browser and open in another tab or you can just zoom in and out in the page on the article and you'll see the image is okay and fully readable.

**Comment by scanum** [comment]
@bigred3142 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by j0rt3g4** [comment]
@bigred3142  I've redone the image on a PR: #2963 
you can download the full size and on pdf format for your consult in here:
https://1drv.ms/u/s!AsDC94k7vMVfl68ZeVU6CS3wGZGXgw?e=bDSYTm
