### ISSUE TITLE
Page not updated to SFB2019

### ISSUE THREAD

**Issue by Mickael-Br** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2898]
Maximum number of Front-End in a pool is now 16, however the tables here max-out at 12 (old number).

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 3cd12943-2c9d-bcfb-8a7f-9b184c34f4e4
* Version Independent ID: 6576e82d-b941-b14c-88e5-34d968dcd44f
* Content: [Haute disponibilité et gestion du pool frontal](https://docs.microsoft.com/fr-fr/skypeforbusiness/plan-your-deployment/high-availability-and-disaster-recovery/high-availability#feedback)
* Content Source: [Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/high-availability.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/high-availability.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Mickael-Br  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Hello @Mickael-Br I was not able to verify your source, could you please add your source here?

**Comment by scanum** [comment]
@Mickael-Br We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Mickael-Br** [comment]
Hello,

Sorry about the lack of response.

The current version shows the pool table going up to 12, but in Skype for Business 2019 the maximum pool size is 16:
https://docs.microsoft.com/en-us/skypeforbusiness/plan/user-model-2019
"The maximum number of Front End Servers in a pool is 16."
