### ISSUE TITLE
typo for Office 365 URLs and IP address ranges

### ISSUE THREAD

**Issue by naminakao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#29]
"Known issues for Microsoft Teams" page has the hyperlink for Office 365 URLs and IP address ranges. The link has typo and unable to open a page.

Title: Known issues for Microsoft Teams
URL: https://docs.microsoft.com/en-us/microsoftteams/known-issues

Hyperlink in question:
httpds://support.office.com/en-us/article/Office-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2#bkmk_teams

**Comment by tonysmit** [comment]
@LolaJacobsen - I was here. Not sure if you seen this.

**Comment by karuanag** [comment]
Typo fixed.  Pending publication

**Comment by alihirsch** [comment]
Updated topic published by lolaj on 2/6,
