### ISSUE TITLE
all sudden lunch screen visible when I dock my laptop to other monitors.

### ISSUE THREAD

**Issue by manishkarn2000** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#290]
This is happening very consistent, whenever I am changing from my laptop monitor to extended monitor, it annoys me, having two screens (one is the lunch screen)

![image](https://user-images.githubusercontent.com/21974819/40751898-03f805c0-6422-11e8-882a-9cf3d77214ad.png)

**Comment by jambirk** [comment]
Please file this concern with https://www.skypefeedback.com/
