### ISSUE TITLE
Unclear use of uploaded data

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2900]
It is unclear to me how the uploaded Building and Endpoint data files are used for Call Quality.  I uploaded building data expecting to be able to see reports that show data between Building A and B or Network A and B but there are no such options.  So, what is the point of uploading the data files?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb8d8b48-561b-6817-1ce0-4b2aedc261a8
* Version Independent ID: dfd5cf4a-509a-3ed1-0267-6281c251fbef
* Content: [Turning on and using Call Quality Dashboard](https://docs.microsoft.com/en-us/microsoftteams/turning-on-and-using-call-quality-dashboard)
* Content Source: [Teams/turning-on-and-using-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/turning-on-and-using-call-quality-dashboard.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Canis-Lupis  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Canis-Lupis** [comment]
Thanks. Your help is appreciated.

**Comment by j0rt3g4** [comment]
Hello @Canis-Lupis from reading your request this feature is not still officially available.
Right now is on the beta process, but not launched officially yet.

I would recommend you to create a support ticket where you can get the best attention possible since we are on the documentation side and we are not able to enter and review what is the steps that you're missing or what's wrong.

**Comment by Canis-Lupis** [comment]
Thank you for the feedback.  Will you be documenting how to utilize it once it is launched?
________________________________

**Comment by j0rt3g4** [comment]
Indeed we should (as team), but in case it's not you can open up a new issue (no problem at all).

**Comment by scanum** [comment]
@Canis-Lupis Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
