### ISSUE TITLE
Plaats van de tabs

### ISSUE THREAD

**Issue by pieterhoenderken** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2902]
Is het ook mogelijk om de volgorde van de tabs aan te passen? Ik wil graag "Bestanden" als eerste en daarna de rest zoals gesprekken en wiki

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 8d33f55c-db55-923e-544f-fccb97f3c7a3
* Version Independent ID: 9cb02e00-311e-ec7d-c422-ae1cb9e6d31e
* Content: [Ingebouwde en aangepaste tabbladen gebruiken in Microsoft Teams](https://docs.microsoft.com/nl-nl/microsoftteams/built-in-custom-tabs#feedback)
* Content Source: [Teams/built-in-custom-tabs.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/built-in-custom-tabs.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@pieterhoenderken  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.


Translation:: " 
Is it also possible to adjust the order of the tabs? I want "Files" first and then the rest such as conversations and wiki"

**Comment by dplotnikov** [comment]
@pieterhoenderken it's not possible at the moment and I've added a PR with a clarification about this

**Comment by scanum** [comment]
@pieterhoenderken Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
