### ISSUE TITLE
Need clarification

### ISSUE THREAD

**Issue by howardzhangmsft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2904]
It is not clear in documentation around the exchange licensing requirements to hold Teams data.
Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f55c52a5-5841-b9c9-1607-2013dc3f2e20
* Version Independent ID: 16d93458-5e01-646f-dac5-31306cc7f3fb
* Content: [Microsoft Teams retention policies FAQ](https://docs.microsoft.com/en-us/microsoftteams/retention-policies-faq)
* Content Source: [Teams/retention-policies-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/retention-policies-faq.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@howardzhangmsft  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Solving Issue on PR #3020

**Comment by j0rt3g4** [comment]
@scanum

**Comment by scanum** [comment]
@howardzhangmsft 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
