### ISSUE TITLE
Photoshop template file out-of-date

### ISSUE THREAD

**Issue by Renaud83** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2906]
Hi, since the latest release of Microsoft Teams Rooms app, the photoshop template file is obsolete. can you provide a newer version ? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25a70665-5bf1-14f7-1df0-7596effcaf48
* Version Independent ID: 813cf005-2777-9419-d1ce-3f9401ac267c
* Content: [Manage a Microsoft Teams Rooms console settings remotely with an XML configuration file](https://docs.microsoft.com/en-us/microsoftteams/room-systems/xml-config-file#feedback)
* Content Source: [Teams/room-systems/xml-config-file.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/xml-config-file.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Renaud83  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Added new Photoshop file on PR #2964

**Comment by jambirk** [comment]
The updated template file will be available soon, and the same link will work when it becomes available.

**Comment by scanum** [comment]
@Renaud83 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mizzou626** [comment]
I wouldn't consider this issue resolved since the updated template file isn't available yet. Are there any updates on the new file?
