### ISSUE TITLE
In my Teams admin portal there is no Phone number option under Voice.

### ISSUE THREAD

**Issue by bleach832** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2907]
In my Teams admin portal there is no Phone number option under Voice. I have to go into the Skype legacy portal to assign phone numbers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c67496-cace-f833-7cfc-dca7722fef3e
* Version Independent ID: 5a14f81c-529c-4971-5ce8-39633834d4d3
* Content: [Assign, change, or remove a phone number for a user](https://docs.microsoft.com/en-us/microsoftteams/assign-change-or-remove-a-phone-number-for-a-user#feedback)
* Content Source: [Teams/assign-change-or-remove-a-phone-number-for-a-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-change-or-remove-a-phone-number-for-a-user.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@bleach832 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
