### ISSUE TITLE
Technical Requirements

### ISSUE THREAD

**Issue by RSEEGATZ** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2908]
Does this feature also work for users, who have their mailbox on on-premises Exchange servers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84066c98-38a4-e59a-893f-da38a4a11bf3
* Version Independent ID: 890a4978-0e9b-2691-a2ab-8b5512e5e76f
* Content: [Use Microsoft Teams scoped directory search](https://docs.microsoft.com/en-us/microsoftteams/teams-scoped-directory-search#feedback)
* Content Source: [Teams/teams-scoped-directory-search.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-scoped-directory-search.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@RSEEGATZ  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by colin-small** [comment]
I really need to know this as well. We use Exchange on-premise. Can we still create the ABP's in Office 365 to enable scoped directory search in Microsoft Teams?

Basically, I need to prevent people from searching for other people in Microsoft Teams. I would like to take it a step further and enable information barriers after the scoped directory search is enabled.

I'm on pause waiting for Microsoft to respond on if this is possible or not so I hope they respond quickly.

**Comment by colin-small** [comment]
I just noticed that the question seems to have been answered in [2965](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/2965)

Sounds like we have no options here. :(

**Comment by scanum** [comment]
@RSEEGATZ Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
