### ISSUE TITLE
Any way to on/off moderation by admin in tenant setting ?

### ISSUE THREAD

**Issue by moegitree** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2909]
I can see moderation setting is shown in channel setting. But is it possible for admin to disable moderation in tenant level?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 097ecd40-1157-98ae-f438-96f9208afc03
* Version Independent ID: ea36ff93-46dc-920d-8d52-9b3b81420958
* Content: [Microsoft Teams でチャネルのモデレーションを設定および管理する](https://docs.microsoft.com/ja-jp/microsoftteams/manage-channel-moderation-in-teams#feedback)
* Content Source: [Teams/manage-channel-moderation-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-channel-moderation-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@moegitree  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LolaJacobsen** [comment]
Thanks so much for the feedback. I updated the article to make it clearer.
