### ISSUE TITLE
[LOC] Table is broken(ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2910]
ja-jp:"https://docs.microsoft.com/ja-jp/microsoftteams/deploy-meetings-microsoft-teams-landing-page"
![deploy-meetings-microsoft-teams-landing-page_j](https://user-images.githubusercontent.com/40815708/63927521-d4704000-ca88-11e9-9270-e205434736e4.png)

en-us:"https://docs.microsoft.com/en-us/microsoftteams/deploy-meetings-microsoft-teams-landing-page"
![deploy-meetings-microsoft-teams-landing-page_e](https://user-images.githubusercontent.com/40815708/63927534-da662100-ca88-11e9-8c8b-44b15116e6a8.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8485ffe7-52ea-ef91-4983-2f02d6e3bb96
* Version Independent ID: 2bb5e8af-2c5b-ab1f-f69b-be8668b181b4
* Content: [Microsoft Teams でのミーティングと会議](https://docs.microsoft.com/ja-jp/microsoftteams/deploy-meetings-microsoft-teams-landing-page)
* Content Source: [Teams/deploy-meetings-microsoft-teams-landing-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/deploy-meetings-microsoft-teams-landing-page.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@hyoshioka0128  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 Could you please verify on your side? I can't see the broken table. 
Probably fixed by an update

PrintScreen:
![image](https://user-images.githubusercontent.com/47977325/65142997-34b52a80-da14-11e9-9084-dc0475ce69fa.png)

**Comment by hyoshioka0128** [comment]
@OfficeGlobal - Fixed by an update.
Closed #2910
Thank you.
