### ISSUE TITLE
[LOC] Back-Translation "新規-CsTeamsMeetingBroadcastPolicy"→"New-CsTeamsMeetingBroadcastPolicy"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2911]
https://docs.microsoft.com/ja-jp/microsoftteams/teams-live-events/set-teams-live-events-policies-using-powershell
![set-teams-live-events-policies-using-powershell](https://user-images.githubusercontent.com/40815708/63927823-75f79180-ca89-11e9-8069-8aba487a1e9e.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8cb395f1-fce4-2d64-c66e-36a6cd818ca6
* Version Independent ID: 79bf1d7e-8cbc-5146-dfda-a6ae38d49be7
* Content: [PowerShell を使用して Microsoft Teams でのライブ イベント ポリシーを設定する](https://docs.microsoft.com/ja-jp/microsoftteams/teams-live-events/set-teams-live-events-policies-using-powershell)
* Content Source: [Teams/teams-live-events/set-teams-live-events-policies-using-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/set-teams-live-events-policies-using-powershell.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@hyoshioka0128  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@OfficeGlobal @MollyMalone

**Comment by OfficeGlobal** [comment]
@TinaMcN , @Reeced40 Working on a fix (Bug 3641029)

**Comment by scanum** [comment]
@OfficeGlobal Hi! Any updates on this? Thanks!

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum article has been Human Translated, the issue is fixed

**Comment by hyoshioka0128** [comment]
@OfficeGlobal - Fixed. Thank you.
Closed #2911
