### ISSUE TITLE
[LOC] not translated 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2912]
ja-jp:"https://docs.microsoft.com/ja-jp/microsoftteams/teams-live-events/plan-for-teams-live-events"
![plan-for-teams-live-events_j](https://user-images.githubusercontent.com/40815708/63928219-2ebdd080-ca8a-11e9-962b-54e45f8bb599.png)

en-us:"https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events"
![plan-for-teams-live-events_e](https://user-images.githubusercontent.com/40815708/63928227-31b8c100-ca8a-11e9-8c3e-f7ff2bc60d5b.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Microsoft Teams でのライブ イベントの計画](https://docs.microsoft.com/ja-jp/microsoftteams/teams-live-events/plan-for-teams-live-events)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@hyoshioka0128  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@OfficeGlobal @MollyMalone

**Comment by OfficeGlobal** [comment]
@TinaMcN , @Reeced40 Working on a fix (Bug 3641029)

**Comment by scanum** [comment]
@OfficeGlobal Hi! Any updates on this issue?

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum article has been Human Translated, the issue is fixed

**Comment by hyoshioka0128** [comment]
@OfficeGlobal - Fixed. Thank you.
Closed #2912
