### ISSUE TITLE
there is no preview

### ISSUE THREAD

**Issue by Lelivienne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2913]
you providing commands available in preview...but how to get this preview? no link on the page, it's not on github, and checking find-module MicrosoftTeams -AllowPrerelease do not find it either... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26362d70-cfce-2eea-077b-4aaa50f92e8b
* Version Independent ID: f52dcd4d-4f58-05c4-11b0-f1e3c95f4d89
* Content: [Teams PowerShell Overview](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-overview)
* Content Source: [Teams/teams-powershell-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Lelivienne  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@Lelivienne hello, the table has a pretty straightforward note "Prior to 1.0 release only". The latest version that is before 1.0 is 0.9.6 and you should run the following command in order to install it `Install-Module -Name MicrosoftTeams -RequiredVersion 0.9.6`

**Comment by j0rt3g4** [comment]
@Lelivienne Please let us know if the information given by @dplotnikov  worked for you and if you need further assistance

**Comment by scanum** [comment]
@Lelivienne We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
