### ISSUE TITLE
German Translation Says 1st of October Rather Than 1st of September

### ISSUE THREAD

**Issue by teodordeaconescu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2915]
This sentence:

[quote]
Seit dem 1. Oktober 2019 werden neue alle Office 365-Kunden in Microsoft Teams integriert und erhalten keinen Zugriff auf Skype for Business Online. 
[/quote]

Should probably say "Ab dem 1. September 2019...." -- all other languages I checked (EN-US and FR-FR) say 1st of September, not October. 

Thanks.

**Comment by scanum** [comment]
@teodordeaconescu Hello, we strongly appreciate your feedback. Could you please link the document you are reffering to? Thanks!

**Comment by teodordeaconescu** [comment]
@scanum - here's the article in German that appears to be incorrect:
https://docs.microsoft.com/de-de/microsoftteams/faq-journey

here's the article in English, where the information is correct:
https://docs.microsoft.com/en-us/microsoftteams/faq-journey

Thanks,
Teodor

**Comment by Reeced40** [comment]
@samanthaw @OfficeGlobal

**Comment by scanum** [comment]
@OfficeGlobal Could you please assist in this issue? Thanks!

**Comment by OfficeGlobal** [comment]
@teodordeaconescu , @scanum the date was updated. Thank you

**Comment by scanum** [comment]
@teodordeaconescu Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
