### ISSUE TITLE
How does one "Make sure single sign-on (SSO) is enabled"?

### ISSUE THREAD

**Issue by yaronyg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#292]
I can't get the Teams meeting plugin to show up in Outlook (I'm the latest internal release). I followed the instructions above until the last step and it's not working. I even checked my list of Add-ins and nothing that mentions Teams is listed there. But the one step I couldn't do was "Make sure single sign-on (SSO) is enabled." No instructions are provided for how this is supposed to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Use the Microsoft Teams Meeting add-in in Outlook](https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook#troubleshooting)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* Product: **unspecified**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by kenwith** [comment]
@yaronyg - I am very sorry for the long delay on this one and thank you for submitting feedback. It has been a very long time and I am hoping you have already resolved this issue. If you haven't, I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. 

Based on outcome let me know if it is something that can be called out in the docs. I did see another thread regarding 32-bit and 54-bit but I am not sure if there was a resolution yet. I am very interested to hear your results from the service ticket and what I can do to make the doc better.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by yaronyg** [comment]
It turns out that the problem is that the ring I'm deployed on doesn't support the Teams plugin for Outlook. :( So there is no solution for me but to wait for that feature to be pushed out to my ring.

**Comment by yaronyg** [comment]
Sorry I didn't mean to re-open.
