### ISSUE TITLE
.net framework 4.8 supportability

### ISSUE THREAD

**Issue by Erdem-Oz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2922]
Hello,

I could not find if Skype for Business Server works with 4.8 .net framework. There should be a list with all supported .net framework and what level of CU patch is needed for a .net framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd40e9bf-6fb5-b597-5494-b9ccc17e4660
* Version Independent ID: 46d0d0a0-2ea9-efbd-1ef8-63686f7fef62
* Content: [System requirements for Skype for Business Server 2019](https://docs.microsoft.com/en-us/SkypeForBusiness/plan/system-requirements)
* Content Source: [Skype/SfBServer2019/plan/system-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/plan/system-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@Erdem-Oz  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Info added on PR #2966

**Comment by jambirk** [comment]
@Erdem-oz  

The article refers specifically to support for 4.7 which was accurate at initial release. I've verified that 4.8 is also supported now The matrix you're suggesting is premature, since there's only two .NET versions supported and only one CU so far for Server 2019.

@microsoftheidi I'll leave you to approve the PR.

**Comment by j0rt3g4** [comment]
@scanum  Added the correct sentence to the PR.
