### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by NeilPetersen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2923]
Hi,
The 'To find out how much it costs, see the rates here.' link is broken = it redirects to https://products.office.com/en-GB/skype-for-business/pstn-calling-plans and a 404 is presented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 277cf140-5c6c-82c7-cc56-490ef2188754
* Version Independent ID: 72e7de29-fd71-23bf-15a7-172634c2a5fd
* Content: [Set up Communications Credits for your organization](https://docs.microsoft.com/en-us/microsoftteams/set-up-communications-credits-for-your-organization#feedback)
* Content Source: [Teams/set-up-communications-credits-for-your-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-communications-credits-for-your-organization.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@NeilPetersen  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@NeilPetersen Hi there, thank you for reaching out. I've checked the link and it seems to be working fine, please can you confirm from your side.

**Comment by scanum** [comment]
@NeilPetersen We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by MattWharton** [comment]
I'm experiencing the same 404 page for the link https://products.office.com/en-GB/skype-for-business/pstn-calling-plans that @NeilPetersen was getting. When I try the equivalent en-US page it then redirects to https://products.office.com/en-us/microsoft-teams/voice-calling which does contain the required information.

**Comment by kitleyn** [comment]
@scanum @Reeced40 I have found the same broken link that @NeilPeterson and @MattWharton found. The en-gb version of the link goes to 404 page
