### ISSUE TITLE
Grant-CsTeamsInteropPolicy no longer exists

### ISSUE THREAD

**Issue by chrisbardon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2925]
Has this cmdlet been deprecated?  It's not recognized, and the Grant-CsTeamsUpdatePolicy seems to be all you need now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25f11980-56c3-6000-7f9e-620f9e04a754
* Version Independent ID: 9603c9fa-7963-2bdf-3f96-2d095f84b860
* Content: [Basic Upgrade PowerShell](https://docs.microsoft.com/en-us/microsoftteams/upgrade-basic-powershell)
* Content Source: [Teams/upgrade-basic-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-basic-powershell.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@chrisbardon  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@tonysmit hey I need your assistance with it. As far as I know, TeamsUpgradePolicy replaced TeamsInteropPolicy. During the transition, customers should set both InteropPolicy and UpgradePolicy. Does it mean that this article should be updated just by removing all TeamsInteropPolicy calls?

**Comment by j0rt3g4** [comment]
@chrisbardon, @dplotnikov  as long as I know. I think that this cmdlet is obsolete after Microsoft has migrated already most tenants into "teams only" and after that, it can't be changed it, so it gets grayed out on the portal.

**Comment by dplotnikov** [comment]
@j0rt3g4 so what's your suggestion here then?

**Comment by j0rt3g4** [comment]
@dplotnikov  wait for the author
I already asked @scanum  to contact him and see what he has to add or what to proceed with this article.

**Comment by chicojrelliott** [comment]
it works just run the following: 
#Connect using a Skype for Business Online administrator account with multifactor authentication
Import-Module SkypeOnlineConnector
$sfbSession = New-CsOnlineSession
Import-PSSession $sfbSession
$Users = Import-Csv -Path c:\temp\TeamsOnlyMode.csv
foreach($User in $Users)
{
Grant-CsTeamsUpgradePolicy -Identity $User.UserPrincipalName -PolicyName UpgradeToTeams
}

Anyone know how to add "Notify the Skype for Business user"?

**Comment by scanum** [comment]
@LanaChin Hi Lana, could you please assist us on this issue? Thanks!

**Comment by LanaChin** [comment]
@scanum - We received confirmation from the PM that that the three Grant-CsTeamsInteropPolicy command lines in the doc should be removed.  Thank you.

**Comment by dplotnikov** [comment]
@LanaChin feel free to merge the change and close this issue

**Comment by LanaChin** [comment]
Done!  Thanks.
