### ISSUE TITLE
Migration "Call Admission Control"?

### ISSUE THREAD

**Issue by Kofl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2926]
Dear team,

is seems the topic regarding the migration of Call Admission Control is missing?
If its enabled on the legacy server and set for the site as CAC server, it must also migrated to the new Sfb server 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc80438-19bc-4747-1786-dfdcd36097bf
* Version Independent ID: f2d4d6fc-80db-3cca-767e-f0fc1495a2dd
* Content: [Migration to Skype for Business Server 2019](https://docs.microsoft.com/en-us/skypeforbusiness/migration/migration-to-skype-for-business-server-2019#feedback)
* Content Source: [Skype/SfBServer2019/migration/migration-to-skype-for-business-server-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/migration/migration-to-skype-for-business-server-2019.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by Kofl** [comment]
Found, it located under "Decommission legacy pools" at https://docs.microsoft.com/en-us/skypeforbusiness/migration/reset-call-admission-control

**Comment by scanum** [comment]
@Kofl thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
