### ISSUE TITLE
[LOC] Back-Translation "チームの追加ユーザー"→"Add-TeamUser"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2927]
ja-jp:https://docs.microsoft.com/ja-jp/microsoftteams/teams-powershell-overview
![teams-powershell-overview_j](https://user-images.githubusercontent.com/40815708/64088026-7b4f2780-cd7a-11e9-83ca-4f8cd04879f7.png)

en-us:https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-overview
![teams-powershell-overview_e](https://user-images.githubusercontent.com/40815708/64088032-81dd9f00-cd7a-11e9-9624-3c925c011e7e.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 26362d70-cfce-2eea-077b-4aaa50f92e8b
* Version Independent ID: f52dcd4d-4f58-05c4-11b0-f1e3c95f4d89
* Content: [Teams での PowerShell の概要](https://docs.microsoft.com/ja-jp/microsoftteams/teams-powershell-overview)
* Content Source: [Teams/teams-powershell-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@hyoshioka0128  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@samanthaw @OfficeGlobal

**Comment by OfficeGlobal** [comment]
@TinaMcN , @Reeced40 Working on a fix (Bug 3641029)

**Comment by scanum** [comment]
@OfficeGlobal Hi! Any updates on this? Thanks!

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum article has been Human Translated, the issue is fixed

**Comment by hyoshioka0128** [comment]
@OfficeGlobal - Fixed. Thank you.
Closed #2927
