### ISSUE TITLE
"Moderator" in message setting needs to be clarified when channel moderation is OFF.

### ISSUE THREAD

**Issue by moegitree** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2928]
When channel moderation is OFF, members are allowed to post new message in channel with "Everyone can reply" and "You and moderators can reply" being available in format setting. So who are moderators here when moderation itself is OFF? This need to be clarified in the article I think.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097ecd40-1157-98ae-f438-96f9208afc03
* Version Independent ID: ea36ff93-46dc-920d-8d52-9b3b81420958
* Content: [Set up and manage channel moderation in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-channel-moderation-in-teams)
* Content Source: [Teams/manage-channel-moderation-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-channel-moderation-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by pyoungberg** [comment]
agreed, it's confusing

**Comment by LolaJacobsen** [comment]
Thanks so much for the feedback. I updated the article to make it clearer.
