### ISSUE TITLE
link to 'https://admin.teams.microsoft.com' would be helpfull

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2929]
If a user doesn't kow how to find the admin center then the documentation is useless. It is required to enable the user to find the admin center. So why you don't include a link like https://admin.teams.microsoft.com?
It is not easy to find out that link, it is missing in the documentation. This is frustating for the user.

**Comment by jambirk** [comment]
@aisbergde That's a pretty reasonable request, but it's impractical to implement for every article, and your issue doesn't seem to be linked to a specific article. Can you suggest one or more articles where you think this would be most helpful?

**Comment by jambirk** [comment]
@aisbergde I've reviewed this again: The Teams admin center isn't actually relevant. Account creation and management for Teams Rooms isn't available in Admin center yet, and all the current account creation instructions are dependent upon Powershell commands shared by SfBO and Teams. When the Teams admin center more fully supports MTR we already have plans to update the instructions, but for now providing the link is more of a by-the-way side note. 

@scanum  Unless we get a different answer from aisbergde, please add that link in a note to the  with-exchange-on-premises and with-office-365  account creation articles, mentioning that Admin center support for MTR account creation and management is planned but not yet available,.

**Comment by j0rt3g4** [comment]
hello @aisbergde I'd be adding the links can you add me the md files, please? ty in advance

**Comment by jambirk** [comment]
The md files were mentioned by name in my earlier message.

**Comment by scanum** [comment]
@aisbergde We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by aisbergde** [comment]
I miss a link from this github item to the original documentation article. So it is hard for me to comment if the current solution is fine or not and to take part in this discussion.
I remember that I was lost in documentation and this was the reason to create this issue.
