### ISSUE TITLE
Perhaps mispelling?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2930]
Hi,
On the page you say one of the metric for poor calls is:
RRatioConcealedSamplesAvg
but when looking for the SQL database there is no such a column, but RatioConcealedSamplesAvg but there is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fafaebfc-a2d3-2af9-87ef-335dbce0f429
* Version Independent ID: 55bccc6f-aeeb-8df3-796c-e25b78474eb7
* Content: [Use Call Quality Dashboard for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/call-quality-dashboard/use)
* Content Source: [Skype/SfbServer/management-tools/call-quality-dashboard/use.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/management-tools/call-quality-dashboard/use.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by Petri-X** [comment]
Same goes to the DDegradationAvg vs. DegradationAvg

**Comment by jambirk** [comment]
Thank you for catching that, the typo has been fixed.
