### ISSUE TITLE
ATP Anti Phishing is blocking missed conversation email alerts from Teams

### ISSUE THREAD

**Issue by JohnE2** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2932]
[ATP is blocking the missed conversation emails. I believe they are being flagged especially when protected users is enabled within ATP. The sending SMTP address is NOREPLY@EMAIL.TEAMS.MICROSOFT.COM with a display name of " FIRST NAME LAST NAME in Teams".

The missed conversation email alerts is an important feature to alert people of conversations when they are not logged in or away from Teams. Please check into . Thx]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues#feedback)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@JohnE2  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Hi @JohnE2  I think that you should create a support ticket.
And come back with the resolution so we can add important information into the documentation.

**Comment by scanum** [comment]
@JohnE2 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
