### ISSUE TITLE
Need more details about SBC logs

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2935]
It's cool that the doc says, refer to the SBC Logs. I am new to all of this and don't have a clue about where I can find SBC logs. I gather that they may be Session Border Controller logs, and they may be located there.... by where (directory) etc.?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9374347d-42cb-4955-6eac-3efd04eef66d
* Version Independent ID: 985dbd00-b456-13c3-5928-b423084d3a87
* Content: [Monitor and troubleshoot Direct Routing](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-monitor-and-troubleshoot#feedback)
* Content Source: [Teams/direct-routing-monitor-and-troubleshoot.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-monitor-and-troubleshoot.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Jmartinez589  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
@Jmartinez589 the SBCs are a piece of hardware, they should save their files like the routers does, so I think they handle its own logs files.

Here's a list of supported:
https://docs.microsoft.com/en-us/microsoftteams/direct-routing-border-controllers

**Comment by scanum** [comment]
@Jmartinez589  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
