### ISSUE TITLE
S2015 CU's kb link points to S2019

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2937]
Hi,

This might be a mistake:

"Skype for Business Server 2015 Cumulative Update 10 Hotfix 1" have link:
https://support.microsoft.com/en-us/help/4470124/updates-for-skype-for-business-server-2019

That might not be the purpose?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be9f745c-5925-3a7b-9430-b5e61b4384ba
* Version Independent ID: bc23dce3-f38b-9e81-1614-d16aed1d8684
* Content: [Skype for Business Server updates](https://docs.microsoft.com/en-us/skypeforbusiness/sfb-server-updates)
* Content Source: [Skype/SfbServer/sfb-server-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/sfb-server-updates.md)
* Product: **skype-for-business-server**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by jambirk** [comment]
@ariantor please address this

**Comment by Ariantor** [comment]
Done, James.
I have put your alias in the comment as you have suggested.

I have not got a chance to fix the access permission. We have upcoming releases for Exchange I need to deal with.

Thanks,
Ari.-

**Comment by jambirk** [comment]
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/2942 resolves
