### ISSUE TITLE
App Permission Policy

### ISSUE THREAD

**Issue by oradcliffe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2938]
While this is true:

"Optionally, should you want to hide the Teams and Channels application from the left navigation of your users’ Teams client to further focus their experience on meetings, that can be achieved by using the App Permission policy,"

should you decide to use this, the experience isn't good.  When a user first signs into Teams, they will load in on the Teams app anyway, but since they don't have the Teams app available on the sidebar, when they navigate away they cannot get back.  This is very confusing for most people.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12d73609-83a4-cdd4-8461-59fc1a9152fc
* Version Independent ID: b72ffa6e-f060-c296-e42d-eb3815a932ea
* Content: [Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/meetings-first)
* Content Source: [Teams/meetings-first.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meetings-first.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@oradcliffe  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @oradcliffe, thank you for your feedback.

Could you kindly give me more detail? Do you think we should update the article or it's a product improvement?

Thank you again.

**Comment by scanum** [comment]
@oradcliffe We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
