### ISSUE TITLE
Teams gets installed but Outlook add-in don't get install

### ISSUE THREAD

**Issue by rajeshkhanikar** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2939]
Unable to get the Outlook add-in.
1. Installed Teams with Office 365 ProPlus package, it won't install the Outlook add-in (installation is assigned to device security to skip the UAC prompt)

2.  Installed Teams Machine-Wide installer (MSI). App install context is user by default (cannot change).
![image](https://user-images.githubusercontent.com/43844200/64290586-a4cca680-cf66-11e9-8378-172242109adc.png)

But still Outlook add-in won't get install. Outlook add-in appears only if Teams is installed interactively (exe installation).

**Comment by scanum** [comment]
@rajeshkhanikar  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by rajeshkhanikar** [comment]
@scanum Looks like this is a known issue when Teams is deployed with Office packages. For the add-in to appear we need to exit both Outlook and Teams, and then start and sign-in to Teams, after that start Outlook (in that order - restarting the computer doesn't fix the issue). [https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook](url)

> If users do not see the Teams Meeting add-in, instruct them to close Outlook and Teams, then restart the Teams client first, then sign in to Teams, and then restart the Outlook client, in that specific order.
