### ISSUE TITLE
Office 365-groep <> Microsoft Teams

### ISSUE THREAD

**Issue by rsybesma** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#294]
Ik werk met Office 365-groepen. Uit de documentatie wordt niet duidelijk waarom ik voor Microsoft Teams zou moeten kiezen.
Wordt Outlook Groups opgeheven?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 43a2187e-570d-f235-3536-69df8eaa906a
* Version Independent ID: da949f22-1617-c737-d5a4-5c51704443e8
* Content: [Bestaande Office 365-groepen uitbreiden met Microsoft Teams](https://docs.microsoft.com/nl-nl/microsoftteams/enhance-office-365-groups)
* Content Source: [Teams/enhance-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.nl-NL/blob/live-sxs/Teams/enhance-office-365-groups.md)
* Service: **msteams**
* Product: **unspecified**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by JValck** [comment]
Here is the main difference between Team Groups and Outlook Groups as quoted from the [docs](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/teams_api_overview):

> The main difference between a team and an Office 365 group is the mode of communication between members. Team members communicate by persistent chat in the context of a specific team. Office 365 group members communicate by group conversations, which are email conversations that occur in the context of a group in Outlook.

Tip voor de toekomst: aangezien de feedback op de docs bij Microsoft sinds kort werkt met GitHub issues, rapporteer je best in het Engels.

**Comment by kenwith** [comment]
Thank you for the feedback. Please let me know if there is something we can add to the docs to clarify. Sorry for the delay on the response. Closing this but feel free to re-open if needed.
