### ISSUE TITLE
Supported clients for media bypass

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2940]
This article's content is two-year-old.
Could you please update the client support statement, which currently says "With the first release of media bypass, the only supported client is the Skype for Business 2016 Windows Client that is part of Office 365 ProPlus, version 16.0.7870.2020 or greater."
Specifically, what about CCE Media Bypass support by MSI-based SFB Windows clients and SFB mobile for iOS/Android clients?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5545a91-2562-e992-7c80-68dbf51aac23
* Version Independent ID: df33bfca-15ad-c802-c140-8cc7a67710d5
* Content: [Plan for media bypass in Cloud Connector Edition](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/plan-for-media-bypass-in-cloud-connector-edition#supported-clients-for-media-bypass)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/plan-for-media-bypass-in-cloud-connector-edition.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/plan-for-media-bypass-in-cloud-connector-edition.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by shivtorov** [comment]
and what about 3PIP phones such as Poly(com) VVX series handsets?

**Comment by scanum** [comment]
@shivtorov Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
This question is extremely specific for hardware items, @scanum  I'd like the intervention of the PG or author of the article.

**Comment by scanum** [comment]
@CarolynRowe Hi Carolyn, could you please assist in the resolution of this issue? We need your assistance since this is very specific.

**Comment by scanum** [comment]
@CarolynRowe Following up on this issue, any updates? Thanks

**Comment by scanum** [comment]
@CarolynRowe Following up on this issue. Please let me know if there are any updates. Thanks!

**Comment by scanum** [comment]
@CarolynRowe Following up on this issue. Please let me know if there are any updates. Thanks!

**Comment by scanum** [comment]
@CarolynRowe Following up on this issue. Please let me know if there are any updates. Thanks!

**Comment by scanum** [comment]
@CarolynRowe Following up on this issue. Please let me know if there are any updates. Thanks!

**Comment by scanum** [comment]
@CarolynRowe Following up on this issue. Please let me know if there are any updates. Thanks!

**Comment by shivtorov** [comment]
closing the ticket due to no progress in 5 months
