### ISSUE TITLE
Content Camera Mounting Kits for Compatible Webcams

### ISSUE THREAD

**Issue by mizzou626** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2946]
I see a content camera kit is coming soon for both the Logitech BRIO and Creston Huddly IQ. Is there a content camera kit in the works for the Logitech 930e?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b06af4b9-8034-c287-b30c-ca009b8549c1
* Version Independent ID: bf2e1bd9-9b86-68a9-42dd-89001bedf0cd
* Content: [Manage a Microsoft Teams Rooms console settings remotely with an XML configuration file](https://docs.microsoft.com/en-us/microsoftteams/room-systems/content-camera#supported-cameras)
* Content Source: [Teams/room-systems/content-camera.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/content-camera.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@mizzou626  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jambirk** [comment]
@scanum please bring this directly to the article's ms.reviewer.

**Comment by lynnroe** [comment]
The Logitech C930e is a suitable content camera.
If you are not seeing the content camera option in the settings, make sure you have installed all the windows updates to ensure the room system updates.

**Comment by mizzou626** [comment]
@lynnroe - That doesn't answer my question.

**Comment by jambirk** [comment]
@lynnroe  -- MTR devices are deliberately staggered backwards from the most current windows updates. Advising updates beyond what the devices are already set to do puts the devices in an unsupported state.  See https://docs.microsoft.com/en-us/microsoftteams/room-systems/srs2-lifecycle-support 

@mizzou626 -- supported devices/cameras are listed at  https://docs.microsoft.com/en-us/microsoftteams/room-systems/requirements#certified-firmware-versions-for-usb-audio-and-video-peripherals  and information about what is or isn't in development will have to come from @sohailta.  A Logitech kit with the camera, mounting hardware, etc.,  may be available soon, I can't really say for sure. When and if it ever becomes available, it would be listed at  https://aka.ms/teamsdevices

**Comment by scnbwy** [comment]
logitech C930e is supported content camera,I have a blog that describes the content camera.
https://blog.51cto.com/scnbwy/2434429

**Comment by jambirk** [comment]
Closing, the technical documentation is not the place to answer questions about things that aren't even in Preview yet.
