### ISSUE TITLE
Is the HP Elite Slice compatible with Teams Rooms?

### ISSUE THREAD

**Issue by Skempf94** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2948]
Hi, please can you clarify as per the title?
Under the header 'Other Supported Microsoft Teams Rooms consoles'
it states that the: 'HP Elite Slice G2 Audio Ready with Microsoft Teams Rooms' should be compatible with this.

However, this device isn't listed on this support page:
https://products.office.com/en-us/microsoft-teams/across-devices/devices/category?devicetype=20&page=2

Additionally the device will prompt for a dock during setup and cannot proceed past this stage, even though there doesn't seem to be a dock for this particular device.

Please let me know if you have any further information you can share regarding this device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf01435-a73b-4bf2-5845-e4cf50c4c3a2
* Version Independent ID: 166e1800-80b1-2496-7160-3040c5b23c3d
* Content: [Microsoft Teams Rooms requirements](https://docs.microsoft.com/en-us/microsoftteams/room-systems/requirements#feedback)
* Content Source: [Teams/room-systems/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/requirements.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Skempf94 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jambirk** [comment]
@scanum please bring this directly to the article's ms.reviewer.

**Comment by jholl016** [comment]
@Skempf94 We have several HP Elite Slice G2 units deployed successfully, though we're mostly Logitech in our environment.  We use SCCM to deploy our SRS units (wipe and reimage).  Make sure you have all the peripherals connected to the Slice while building and setting up the unit.  Doing it this way, we haven't had any issues.

**Comment by cclevert** [comment]
I have installed the srs media onto a Surface Go. I am not being prompted for any further installation or account setup. Is that due to the device not being compatible or do I need dock to activate the Teams meeting room account setup.

**Comment by jambirk** [comment]
Surface Go isn't a supported device. Expected behavior is probably that startup of the out of box setup fails on two counts: device support check and dock presence both fail. You won't be able to run Teams Rooms on that device.

**Comment by scanum** [comment]
@Skempf94 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by cclevert** [comment]
> @cclevert
> 
> Surface Go isn't a supported device. Expected behavior is probably that startup of the out of box setup fails on two counts: device support check and dock presence both fail. You won't be able to run Teams Rooms on that device.

Thanks for the reply! Thats exactly what is happening. Back to management for a Surface Pro!

**Comment by cclevert** [comment]
I've upgraded to a Surface Pro 4 and finally get to the setup page. I am trying to use a Surface dock but it is not recognized by the setup application. I find it hard to believe that Microsoft requires the purchase of a 3rd party $600+ dock in order to proceed through the install. Is there anything that officially states that the Surface Dock is not a supported piece of hardware for the Teams Meeting room System?
