### ISSUE TITLE
Showing "(manage-phone-numbers-for-your-organization/manage-phone-numbers-for-your-organization.md)"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2949]
ja-jp:https://docs.microsoft.com/ja-jp/microsoftteams/set-up-calling-plans
![set-up-calling-plans_j](https://user-images.githubusercontent.com/40815708/64412802-305f4800-d0cb-11e9-9a2a-60a294375e68.png)

en-us:https://docs.microsoft.com/en-us/microsoftteams/set-up-calling-plans
![set-up-calling-plans_e](https://user-images.githubusercontent.com/40815708/64412809-33f2cf00-d0cb-11e9-83e9-4cd4adabaab5.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a0b2993f-74b2-a59a-fee1-0a5ddcf9e9ff
* Version Independent ID: 01a02c95-cd74-9c82-f5a4-a6bc9adb52a9
* Content: [通話プランの設定](https://docs.microsoft.com/ja-jp/microsoftteams/set-up-calling-plans)
* Content Source: [Teams/set-up-calling-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-calling-plans.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@samanthaw @OfficeGlobal

**Comment by OfficeGlobal** [comment]
@TinaMcN , @Reeced40 Working on a fix (Bug 3641029)

**Comment by TinaMcN** [comment]
@Reeced40 thanks for looping in @OfficeGlobal.  FYI, you don't need to loop in @samanthaw any more for Skype issues, I have taken over the management of Skype content localization on Docs from Sam.  The @OfficeGlobal team will continue doing a great job fixing any localization issues in Office/Skype/Teams content.

**Comment by scanum** [comment]
@OfficeGlobal Any updates on this issue? Thanks!

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum article has been Human Translated, the issue is fixed

**Comment by hyoshioka0128** [comment]
@OfficeGlobal - Fixed. Thank you.
Closed #2949
