### ISSUE TITLE
[LOC] Broken translation (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2950]
ja-jp:https://docs.microsoft.com/ja-jp/microsoftteams/accessibility-declaration-of-conformance-in-france-for-teams
![accessibility-declaration-of-conformance-in-france-for-teams_j](https://user-images.githubusercontent.com/40815708/64413466-81237080-d0cc-11e9-977b-30a1fba90cf2.png)

en-us:https://docs.microsoft.com/en-us/microsoftteams/accessibility-declaration-of-conformance-in-france-for-teams
![accessibility-declaration-of-conformance-in-france-for-teams_e](https://user-images.githubusercontent.com/40815708/64413481-8680bb00-d0cc-11e9-967e-f1cb21c6df3b.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a543ab26-751f-b8b7-d142-cd2556705000
* Version Independent ID: f3acdfea-3780-332f-fd09-06ef76014ad4
* Content: [フランスでの Teams のアクセシビリティに関する適合宣言](https://docs.microsoft.com/ja-jp/microsoftteams/accessibility-declaration-of-conformance-in-france-for-teams)
* Content Source: [Teams/accessibility-declaration-of-conformance-in-france-for-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/accessibility-declaration-of-conformance-in-france-for-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@OfficeGlobal @samanthaw

**Comment by OfficeGlobal** [comment]
@Reeced40 I can see french text included in ENG version as well. Could you please confirm it's correct or it's a Source Issue? Based on TOC title "Accessibility declaration of conformance in France for Microsoft Teams" I guess it's expected

https://docs.microsoft.com/en-us/microsoftteams/accessibility-declaration-of-conformance-in-france-for-teams

![image](https://user-images.githubusercontent.com/47977325/65133824-9e790880-da03-11e9-9bb3-07430530573f.png)

**Comment by Reeced40** [comment]
@OfficeGlobal please could you clarify? Are you suggesting that the TOC should be in French? Or which part needs to be edited?

**Comment by OfficeGlobal** [comment]
@Reeced40 the article itself is related to France, I guess it's on purpose. @tonysmit , could you please verify the article is correct and French is expected https://docs.microsoft.com/en-us/microsoftteams/accessibility-declaration-of-conformance-in-france-for-teams

**Comment by scanum** [comment]
@tonysmit Hi Tony, could you please assist us on the next steps to solving this issue? Thanks!

**Comment by SerdarSoysal** [comment]
This article is intended for French market only, and is not localized on purpose. It only exists in the en-us docset in French because that is our source repo.
