### ISSUE TITLE
[LOC] Broken translation (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2951]
ja-jp:"https://docs.microsoft.com/ja-jp/microsoftteams/accessibility-solutions-in-france"
![accessibility-solutions-in-france_j](https://user-images.githubusercontent.com/40815708/64413810-28a0a300-d0cd-11e9-9d42-9ef90804607b.png)

en-us:"https://docs.microsoft.com/en-us/microsoftteams/accessibility-solutions-in-france"
![accessibility-solutions-in-france_e](https://user-images.githubusercontent.com/40815708/64413822-2dfded80-d0cd-11e9-92c8-dcf00ccb15c1.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 78884968-d899-5744-dda1-b74276c33c07
* Version Independent ID: b8d04634-e8f3-cdc4-6ad2-5b8a9a67982a
* Content: [Skype for Business Online および Microsoft Teams のアクセシビリティ ソリューション](https://docs.microsoft.com/ja-jp/microsoftteams/accessibility-solutions-in-france)
* Content Source: [Teams/accessibility-solutions-in-france.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/accessibility-solutions-in-france.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@OfficeGlobal @samanthaw

**Comment by OfficeGlobal** [comment]
related to #2950 
___

@Reeced40  It seem, it's the same issue - is the french text expected in ENG version?

**Comment by Reeced40** [comment]
@OfficeGlobal I see the heading is in English but the content is in French, what would you suggest?

**Comment by OfficeGlobal** [comment]
@tonysmit could you please confirm French is expected in ENG article?

**Comment by scanum** [comment]
@tonysmit Following up on the above request. Thanks!

**Comment by SerdarSoysal** [comment]
This article is intended for French market only, and is not localized on purpose. It only exists in the en-us docset in French because that is our source repo.
