### ISSUE TITLE
Missing a step/details between 4 and 5

### ISSUE THREAD

**Issue by BillStrait** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2953]
I'm trying to follow along using a free instance of Teams. I add my bot as described in step 4, but I do not see any place to load an app package; and I'm not sure what an app package consists of.

If I push on and click 'Install' on the 'Test and distribute' tab I get an error saying 'Uploading custom apps is not allowed.' At this point I'm not sure if that's because I'm missing the app package, or if there is a limitation on the free version of Teams that prevents it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1257b9b-73ca-8a97-3f65-a7c8d5937e8c
* Version Independent ID: 5f9b5fad-dceb-3f9e-192c-a31ca05e0b83
* Content: [Add bots for private chats and channels in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/add-bots)
* Content Source: [Teams/add-bots.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/add-bots.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@BillStrait Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @BillStrait, thank you for your feedback.

I think custom apps are not available in the free version and you cannot enable it because you don't have access to admin tools for managing apps.

@LolaJacobsen could you kindly confirm please?

**Comment by LolaJacobsen** [comment]
Dariomws306 is correct - Teams Free does not provide admin tools for managing users and apps. Here's information about upgrading to a paid version:
https://docs.microsoft.com/MicrosoftTeams/upgrade-freemium
