### ISSUE TITLE
Configuring derived trunks

### ISSUE THREAD

**Issue by lagerstedt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2954]
"Sbc1.customers.adatum.biz – the derived trunk in a customer tenant that does not need to be created in PowerShell. You can simply add the name of the derived trunk in the customer tenant in the online voice routing policy without creating it.""

To me its unclear how I go about and do this. What command should I use to configure the derived trunk for the tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure a Session Border Controller for multiple tenants](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-sbc-multiple-tenants#feedback)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@lagerstedt Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lagerstedt** [comment]
Any updates about this?

**Comment by fanzhangrob** [comment]
Hi all. Any update on this case? I'm facing the same confusion when dealing with the derived trunk.

**Comment by dariomws306** [comment]
Hi @lagerstedt and @fanzhangrob, thank you for your feedback.

"You can simply add the name of the derived trunk in the customer tenant in the online voice routing policy without creating it."

You need to create a Online Voice Routing Policy using New-CsOnlineVoiceRoutingPolicy.

Please check this article:
https://docs.microsoft.com/en-us/microsoftteams/direct-routing-configure#enable-users-for-direct-routing-service

You should follow the steps under "Enable users for Direct Routing Service" for each customer tenant and you shouldn't apply the steps under "Pair the SBC to the Direct Routing Service of Phone System".

**Comment by fanzhangrob** [comment]
Hi Dario,

Thanks for your attention but I am still quite confused. As I understand to
create a Online Voice Routing Policy I need to create a  Online Voice
Route. However in the  Online Voice Route I need to specify the FQDN of the
Gateway which is not required to be created. I tested it and the
New-CsonlineVoiceRoute command returns a alert saying " Cannot find
specified Gateway"
[image: image.png]
Could you explain a little more on that?

Regards,
Rob Zhang



Dario Woitasen <notifications@github.com> 于2019年9月28日周六 下午10:51写道：

**Comment by dariomws306** [comment]
Yes, you have to run:
New-CsOnlineVoiceRoute -Identity <SomeIdentity> -NumberPattern <SomePattern> -OnlinePstnGatewayList sbc1.customers.domain.com -Priority 1 -OnlinePstnUsages <SomePSTNUsage>

Then:
New-CsOnlineVoiceRoutingPolicy <SomeName> -OnlinePstnUsages <SameUsageAsAbove>

If it doesn't work please put the screenshot again here.

Thanks!

@CarolynRowe could you kindly help with this? Thanks!

**Comment by fanzhangrob** [comment]
Hi Dario,

As I said it does not work.
[image: image.png]

Regards,
Rob Zhang

Dario Woitasen <notifications@github.com> 于2019年9月29日周日 上午1:42写道：

**Comment by lagerstedt** [comment]
@fanzhangrob You still need to configure the domain in the customer tenant. When I looked in to this I got Teams configured but I never got it to work. Teams would fail on incoming INVITEs (error indicated a broken setup). I have an open case with support about that but it does not seem to be going anywhere (been several weeks now).

**Comment by fanzhangrob** [comment]
Hi Carl,

Thanks for your kind reply.
I did exactly what the document tells me to do: domain in the carrier and
customer's tenant, txt DNS record... but the result is what I've captured.
I'm doing it in the old-school way now for my hoisting project. At least it
works.


Carl-Emil Lagerstedt <notifications@github.com>于2019年9月30日 周一下午4:24写道：

**Comment by lagerstedt** [comment]
I came to the same conclusion. Derived trunks does not seem to really work.

**Comment by hsbsandrecv** [comment]
I was struggling with the setup of a derived trunk for a few days now, but I finally was able to create a VoiceRoute without adding a PSTNGateway.
I do agree that Doc could be clear, but it as all there.

Assuming my carrier domain sbc.carrier.com, and customers domains being cust1.sbc.carrier.com, cust2.sbc.carrier.com....
sbc is working with FQDN sbc.carrier.com 

1) On Carrier Tenant: create a subdomain sbc.carrier.com
2) On Carrier Tenant: create a user in this subdomain and assign a E5 license
3) On Carrier Tenant: wait for the user to appear on get-csonlineuser
4) On Carrier Tenant: Create PSTNGateway and verify SIP Options are working (tip to use a SSL Verification Utility to make sure TLS will work)
... set-csonlineuser 
... create PSTNUsage, VoiceRoute, VoiceRoutingPolicy, Grant-CsOnlineVoiceRoutingPolicy ...

5) On Tenant domain: create a subdomain cust1.sbc.carrier.com
6) On Carrier Tenant: create a user in this subdomain and assign a E5 license
7) On Carrier Tenant: wait for the user to appear on Get-CsOnlineUser -Identity "<User name>" | fl RegistrarPool

8) Set-CsUser -Identity "<User name>" -EnterpriseVoiceEnabled $true -HostedVoiceMail $true -OnPremLineURI tel:<E.164 phone number>

* step 8 was prereq to step 10

9) Set-CsOnlinePstnUsage -Identity Global -Usage @{Add="Carrier"}

10) New-CsOnlineVoiceRoute -Identity "Carrier" -NumberPattern ".*" -OnlinePstnGatewayList cust1.sbc.carrier.com -OnlinePstnUsages "Carrier"

11) New-CsOnlineVoiceRoutingPolicy "Carrier" -OnlinePstnUsages "Carrier"
12) Grant-CsOnlineVoiceRoutingPolicy  ....

**Comment by donlassini** [comment]
@hsbsandrecv:
"On Carrier Tenant: create a user in this subdomain and assign a E5 license"
Is that possible? That domain is not registered in your carrier tenant but int the customer tenant?

**Comment by godril** [comment]
This doc needs update. I struggled at first and then I can confirm that you dont have to create PSTNGateway (New-CsOnlinePSTNGateway) on the customer powershell. Here is how:

In the carrier tenant, you add domain for the direct routing, for example, domain.tld. Then create dummy user to assign O365 + Phone Systsem, for example siptrunk@domain.tld.  In the carrier tenant powershell, we add gateway as usual with New-CsOnlinePSTNGateway, then add the PSTNUsage, adding CSOnlineVoiceRoute, and last create CSOnlineVoiceRoutingPolicy. Remember, these all happen in Carrier tenant powershell. 

Now at the client tenant, add the derived domain, eg client1.domain.tld, add the TXT dns, and so on until it verified. And then add user dummy, eg siptrunk@client1.domain.tld. Best thing is, you dont have to assign any office365 and phone system. In the customer tenant powershell, you dont have to add PSTNGateway, just go straight creating Set-CsOnlinePstnUsage, create New-CSOnlineVoiceRoute with client1.domain.tld as parameter, and then creat CSOnlineVoiceRoutingPolicy. Assuming all users are ready with EnterpriseVoice enabled and DID, Grant the newly created CSOnlineVoiceRoutingPolicy to users. You should be able to make call without having PSTNGateway. If you dont, sometimes msteams cloud need sometimes between creating user dummy and create csonlinevoiceroute, ranging from minutes to days, to let the change kicks in. Just wait.  Downside is in TAC you wont see any SBC status in the Voice menu.

Good luck.

**Comment by solarmon** [comment]
@hsbsandrecv 

I agree with @donlassini - I think steps 5, 6 and 7 and onwards should be for 'Customer Tenant', since you have the steps for 'Carrrier Tenant' in 1 to 4?

**Comment by dariomws** [comment]
Hi @donlassini and @solarmon, I cannot find the section you are talking. Could you please copy and paste it?

**Comment by solarmon** [comment]
@dariomws 

We are talking about the steps listed in the last post by @hsbsandrecv - https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2954#issuecomment-547672717

**Comment by dariomws** [comment]
Thanks @solarmon. I think step 2 is right, if you miss this step you will get an error. You must create a user and assign a license for the final activation of the base domain. It´s documented here:
https://docs.microsoft.com/MicrosoftTeams/direct-routing-sbc-multiple-tenants#activate-the-domain-name
