### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by oradcliffe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2957]
TenantID is not a valid parameter on Set- or New-CsHostedVoicemailPolicy.  Tenant is available, but throws an error when you try to use that with your tenant ID from AAD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec8b8afb-b9ca-8136-b907-5bbff4c9dcf1
* Version Independent ID: d4f68818-6fe6-5bb7-f108-e26a643f2cc7
* Content: [Configure Cloud Voicemail service for on-premises users](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/configure-cloud-voicemail)
* Content Source: [Skype/SfbHybrid/hybrid/configure-cloud-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-cloud-voicemail.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@oradcliffe Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dewaltk** [comment]
Is there any update on this? I am trying to setup Cloud Voicemail for a Skype for Business Server 2015 environment instead of having to go through the process of first going to UM online and waiting for Microsoft to move over to Cloud Voicemail next year.

**Comment by ablanken** [comment]
I'm also trying to configure Cloud Voicemail with Skype for Business Server 2019 without success. Please review this documentation ASAP.

**Comment by ablanken** [comment]
I'm using SFB 2019. I don't have the 'TenantId' or 'Tenant' parameters available with the 'Set-CSHostedVoicemailPolicy' command.

When modifying the HostedVoicemailPolicy, I left out the Tenant parameter, enabled a test user for Cloud Voicemail and it worked anyway after a couple of minutes...

Other things I noticed: The command help for Set and New-CSHostedVoicemailPolicy included the 'Tenant' parameter which wasn't available for use in practice. The 'Tenant' parameter was available for use with the 'Grant-CSHostedVoicemailPolicy' command. I was going to try that next but didn't need to.

**Comment by dariomws306** [comment]
Hi @oradcliffe, @dewaltk and @ablanken,

Thanks for your feedback.

I have been trying in my labs and I can see this:
- With SfB 2015, -Tenant parameter exist on Set/New-CsHostedVoicemailPolicy
- With SfB 2019, -Tenant parameter appear on Grant-CSHostedVoicemailPolicy

I will try to get more information about that. Thanks again.

@dstrome maybe you can help here? Thanks!

**Comment by dariomws306** [comment]
@oradcliffe, @dewaltk and @ablanken,

Have you tried without -Tenant? I think that the use of -Organization could be enough.

**Comment by oradcliffe** [comment]
I have tried just using org, but no dice.  It created the policy and I
applied it to users but it didn't actually work.

**Comment by dariomws306** [comment]
Thanks @oradcliffe, I will try to get more help/information.

**Comment by SanguptaMSFT** [comment]
i guess the concern is only in SfB server 2019 from CU1 where there is no -Tenant switch.

SfB 2019 RTM version has the switch.
SfB 2015 never had the switch and i can confirm CVM works fine.

**Comment by dariomws306** [comment]
Thank you @SanguptaMSFT.

I can see it in my lab:
![image](https://user-images.githubusercontent.com/33589238/66822886-7eae0500-ef1b-11e9-9a02-31972ce54663.png)

**Comment by SanguptaMSFT** [comment]
@dariomws306 this is what i was talking about..

RTM Version
![image](https://user-images.githubusercontent.com/40053255/66824433-e721d400-ef65-11e9-8c24-479fc278c93f.png)

SfB 2019 CU1 HF1
Doesn’t have the tenant id parameter.. 
![image](https://user-images.githubusercontent.com/40053255/66824513-12a4be80-ef66-11e9-88e6-c6d6cee8cfc2.png)

SfB 2015 
![image](https://user-images.githubusercontent.com/40053255/66824891-cc039400-ef66-11e9-99ab-60c8be5074f0.png)

**Comment by dariomws306** [comment]
Oh ok, you are talking about -TenantId, you have written "-Tenant" in your first comment.

I think TenantId should be added or maybe there is another way to configure it. I'm waiting for more information.

**Comment by SanguptaMSFT** [comment]
ok :)
yeah Tenant id is missing from SfB 2019 CU1.
i have raised the concern with Skype for business Product group. hoping to hear back soon..

**Comment by scanum** [comment]
@oradcliffe Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
