### ISSUE TITLE
Microsoft Skype Room system v2

### ISSUE THREAD

**Issue by mcterzioglu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2960]
Dear Sir/Madam, I don't have much information about the skype room system. I've got a question for you. I just want to install the Microsoft Skype Room System V2 on my Lenovo y700 laptop. Can I do it?

*I have an Office 365 Business Premium account.
Why do I want this? 
*I want to install a fixed computer in my room and just open the Skype application.

**Comment by scanum** [comment]
@mcterzioglu thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
