### ISSUE TITLE
Unable to Switch Coexistence Mode

### ISSUE THREAD

**Issue by cpotter101** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2967]
We wanted to run in Islands mode, but the Admin Portal switched us to Teams Only mode and doesn't allow us to change back to Islands mode for users.

**Comment by scanum** [comment]
@cpotter101 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@cpotter101 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
