### ISSUE TITLE
Unlear wording

### ISSUE THREAD

**Issue by joturans** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2968]
In the first sentance the word "automatically" is a little missleading. Interaction from the user is still required to translate a message initally. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19e91f77-0c01-5d38-0bd4-65ee44aab5cb
* Version Independent ID: 08ea83b3-c241-979c-3afb-3355ab322489
* Content: [Turn on inline message translation in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/inline-message-translation-teams#feedback)
* Content Source: [Teams/inline-message-translation-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/inline-message-translation-teams.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@joturans Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Solved on PR #3038

**Comment by scanum** [comment]
@joturans 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
