### ISSUE TITLE
PPKG files on private Onedrive

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2969]
Why the PPG files are hosted on private OneDrive and not on GitHub?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f256cd5b-3ec8-2d55-9ae4-ff9849d52eae
* Version Independent ID: 52c2271b-df38-5dc9-c2a1-553cdf3b5496
* Content: [Deploy Microsoft Teams for Surface Hub](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-surface-hub)
* Content Source: [Teams/teams-surface-hub.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-surface-hub.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Larryngolog https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2968

**Comment by mvkaurelium** [comment]
@scanum, this has nothing to do with his (or my, or anyones) tenant or deployment. This is really ridiculous...
