### ISSUE TITLE
OneNote-tab in Microsoft Teams asks to accept cookies

### ISSUE THREAD

**Issue by foriamkate** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2970]
We added a OneNote-File as a new tab in a channel. Everything is fine when I open the tab. But a colleague gets the message displayed above the OneNote, that the website uses cookies and by using the website he accepts their usage. The problem is he can't get rid of the message and it uses quite some space on the screen.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 8d33f55c-db55-923e-544f-fccb97f3c7a3
* Version Independent ID: 9cb02e00-311e-ec7d-c422-ae1cb9e6d31e
* Content: [Verwenden von integrierten und benutzerdefinierten Registerkarten in Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/built-in-custom-tabs#feedback)
* Content Source: [Teams/built-in-custom-tabs.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/built-in-custom-tabs.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@foriamkate Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@foriamkate 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
