### ISSUE TITLE
Adding Configure server-to-server authentication for a Skype for Business Server hybrid environment as requirements

### ISSUE THREAD

**Issue by joaolloureiro** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2971]
In requirement section should also be mentioned that server-to-server authentication to be properly configured is required - https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-call-data-connector

Please contact me for further details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87ba30d1-a7b1-7b12-66e3-dbd75ee62a47
* Version Independent ID: 776dd776-b0b0-3088-6549-ec01b549f1d0
* Content: [Plan Call Data Connector](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-call-data-connector)
* Content Source: [Skype/SfbHybrid/hybrid/plan-call-data-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/plan-call-data-connector.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@joaolloureiro Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
PR #3039

**Comment by scanum** [comment]
@joaolloureiro Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
