### ISSUE TITLE
Scenario 6

### ISSUE THREAD

**Issue by joaolloureiro** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2972]
As per modern auth PM (Natasha Desai) all permutations of hybrid scenario 6 are supported, just not listed because are too many to specifically call out.
Suggested to include a note to explicit call that out as support/customer assume scenarios like Exchange hybrid and pure SFB online are not supported which is not the case as per Natasha.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a88a465-43d0-a866-f90d-dc4cb12bcac0
* Version Independent ID: 70af13e1-6c93-6134-ae5e-f6a6df84fa52
* Content: [Skype for Business topologies supported with Modern Authentication](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/modern-authentication/topologies-supported)
* Content Source: [Skype/SfbServer/plan-your-deployment/modern-authentication/topologies-supported.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/modern-authentication/topologies-supported.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by MSFTTracyP** [comment]
Both scenarios are already documented and supported (https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/modern-authentication/topologies-supported). See your original thread for details, as I updated it with the supported topologies and article URL.
