### ISSUE TITLE
Sound Recorder does not exist in Windows 10

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2974]
Sound Recorder does not exist in Windows 10. Instead there is a per-installed app "Voice Recorder", but this does not create files in a compatible format.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cda4d7d-c9c2-d154-7a59-23a7e5098546
* Version Independent ID: 1d9fa050-062a-867e-79c3-b7b3cdd4305f
* Content: [Small business example - Set up a Call Queue](https://docs.microsoft.com/en-us/skypeforbusiness/what-is-phone-system-in-office-365/tutorial-cq?tutorial-step=4)
* Content Source: [Skype/SfbOnline/what-is-phone-system-in-office-365/tutorial-cq.yml](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/blob/live/Skype/SfbOnline/what-is-phone-system-in-office-365/tutorial-cq.yml)
* Service: **skype-for-business-online**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@Mike-Crowley Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
