### ISSUE TITLE
...So how is CNAM configured for tenants *IN* the United States?

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2976]
The above article states that Microsoft provides reliable CLID information, and that Microsoft supports "originating" CNAM information within the united states. I'm not sure what originating means in this context, but my question is how do I control this CNAM value on outbound calls? For example, my CNAM appears as "Mt. Savage Maryland", but I'd prefer it to say the name of my organization, as per the company settings (or some value not related to the 3-digit number prefixes, which are almost never relevant ).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 460aeaa2-0475-1a17-a9b1-d8e44f7f6e21
* Version Independent ID: 3c47839b-40f4-f94d-0eef-1d9ff7c9402b
* Content: [More about Calling Line ID and Calling Party Name](https://docs.microsoft.com/en-us/microsoftteams/more-about-calling-line-id-and-calling-party-name)
* Content Source: [Teams/more-about-calling-line-ID-and-calling-party-name.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/more-about-calling-line-ID-and-calling-party-name.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@Mike-Crowley Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jonverbeek** [comment]
@scanum - I would also like to understand how to do this.   Please include me in your response.   Thanks!

**Comment by j0rt3g4** [comment]
Hello @Mike-Crowley 

I think that originating means that you could "change or custom" the CNAM information in the United States only.

Either way @scanum please add the author of this article for clarification or confirmation of this comment. Thank you!

**Comment by scanum** [comment]
@tonysmit Hi Tony, could you please help us on clarifying and confirming the comment submitted by the issue raiser? Thanks!

**Comment by scanum** [comment]
@tonysmit Hi Tony, any updates on this issue?

**Comment by rpieken80** [comment]
@mike-crowley @tonysmit   I am also needing to get this set for my organization.   Any help would be greatly appreciated!

**Comment by itthing** [comment]
In my experience you need to email the porting team at ptn@microsoft.com to have them add the CNAM information for the relevant numbers your organization owns.  CNAM is limited to 15 characters.

**Comment by tonysmit** [comment]
Hi @Mike-Crowley - Yes, the PSTN service desk will help you with it. Email them at ptn@microsoft.com. This is for the US only.  Thanks!

**Comment by Mike-Crowley** [comment]
ok great. I'd imagine others would want to do this as well, so perhaps the document could be updated to mention this?

**Comment by Mike-Crowley** [comment]
Update here - I was able to contact the alias above and they updated the field for our tenant. I think there are some useful notes for this article:

- the email address to make the request
- it is a per-tenant, not per-number value (presumably)
- there is a 15 character limit (per the support folks)
