### ISSUE TITLE
Users getting activity notifications for Teams channels they're not following

### ISSUE THREAD

**Issue by WChoPB** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2979]
We have users sometimes getting notified of other users' activity for channels they are not following and have set to only receive notifications if they're @mentioned in said channel. For example, " [name] replied ..." or "[name] posted ...".

**Comment by scanum** [comment]
@WChoPB Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@WChoPB thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
