### ISSUE TITLE
Broken link "How to troubleshoot sign-in issues in Skype for Business Online"

### ISSUE THREAD

**Issue by amunns** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2983]
OfficeDocs-SkypeForBusiness/Skype/SfbOnline/set-up-skype-for-business-online/troubleshoot-problems-with-skype-for-business-online.md

**Comment by scanum** [comment]
@amunns Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
hi there @amunns I was not able to find any broken link, could you be more specific?

**Comment by j0rt3g4** [comment]
Solved on PR #3022  Ignore other submissions. Thank you

**Comment by j0rt3g4** [comment]
Copy review @nenonix @JohanFreelancer9 is required on this one guys. Thank you in advance!

**Comment by scanum** [comment]
@amunns Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
