### ISSUE TITLE
Update Options  to reflect Direct Routing to a Carrier hosting SBC and Trunk

### ISSUE THREAD

**Issue by tomlaciano** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2986]
Microsoft Telephony option 2 for direct routing currently depicts a design where the customer owns the SBC, however there are carriers that will host the certified SBCs and do the provisioning. 
Image wise it would look very similar to option 1 where the Phone System connects to a PSTN provider, however it would not be Microsoft. 

Suggestions on how to update the visio/pdf 
Duplicate the image in Option 2 and remove the grey On Premises box and label the Telephony Trunk as Direct Routing Carrier Telephony Trunk. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ad624-9792-91b7-c85f-09b839b1ea44
* Version Independent ID: e8288f91-11bd-599b-8a88-074917b315a4
* Content: [Microsoft Teams IT architecture and telephony solutions posters](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-architecture-solutions-posters#feedback)
* Content Source: [Teams/teams-architecture-solutions-posters.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-architecture-solutions-posters.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@tomlaciano Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@tomlaciano Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
