### ISSUE TITLE
Reference to Lync server needs to be updated to Skype4B

### ISSUE THREAD

**Issue by Atreidae** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2989]
In the section "Recovery time for pool failover and pool failback" the article describes how the RTO/RPO numbers were calculated, but still references "Lync" instead of "Skype for Business"

"... users enabled for Lync with respect to a pre-defined ..."  should be "... users enabled for Skype for Business with respect to a pre-defined ..."
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a149f64a-4b09-8377-cd87-47b8d50f96ea
* Version Independent ID: 6ad233b2-625d-95a8-7ef4-c6c30558c79d
* Content: [Front End pool disaster recovery in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/high-availability-and-disaster-recovery/disaster-recovery?toc=%2FSkypeForBusiness%2Ftoc.json&bc=%2FSkypeForBusiness%2Fbreadcrumb%2Ftoc.json#feedback)
* Content Source: [Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/disaster-recovery.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/disaster-recovery.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by j0rt3g4** [comment]
Solved in PR #3025

**Comment by scanum** [comment]
@Atreidae Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
