### ISSUE TITLE
Please check if the information is correct and need more information.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#299]
In the load balancer details, port 8080 is described as providing client and device retrieval of root certificate. Please check if this is correct? 

It would be nice to include a diagram summarizing all of the flow and ports.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5164207-7822-cf54-717e-6216e0627ebd
* Version Independent ID: 786f5413-3660-06eb-484f-8d5758d3ec59
* Content: [Port and protocol requirements for servers](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/network-requirements/ports-and-protocols#feedback)
* Content Source: [Skype/SfbServer/plan-your-deployment/network-requirements/ports-and-protocols.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/network-requirements/ports-and-protocols.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
The workloads poster serves as the summary of flow and ports. 

Why do you question whether the LB details are correct? Are you encountering a problem?
