### ISSUE TITLE
120/240 Calling Plans are incorrect

### ISSUE THREAD

**Issue by aamillerMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2990]
MCOPSTN5 and MCOPSTN6 are available in the US.  This site says otherwise and should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed46e6b1-48c5-5302-2f38-89c315d4bff7
* Version Independent ID: 81053999-79ca-888d-38fa-8978276b6228
* Content: [Assign Teams licenses](https://docs.microsoft.com/en-us/microsoftteams/assign-teams-licenses#feedback)
* Content Source: [Teams/assign-teams-licenses.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-teams-licenses.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@aamillerMSFT Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Solving Issue PR #3029

**Comment by scanum** [comment]
@aamillerMSFT Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
