### ISSUE TITLE
Broken link "csTeamsMeetingPolicy コマンドレットの使用方法に関する詳細情報" 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2991]
related: #1726 | #2167

ja-jp:"https://docs.microsoft.com/ja-jp/microsoftteams/configure-desktop-sharing"
![configure-desktop-sharing_j](https://user-images.githubusercontent.com/40815708/64751752-25d40100-d558-11e9-9709-f41ab5b52282.png)

en-us:"https://docs.microsoft.com/en-us/microsoftteams/configure-desktop-sharing"
![configure-desktop-sharing_e](https://user-images.githubusercontent.com/40815708/64751755-2b314b80-d558-11e9-9aad-57e549f74516.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 9ce30163-6327-899b-281d-d4ef982fce5e
* Version Independent ID: e61dcbb8-4877-ef6f-1987-981cdd7fc82f
* Content: [Microsoft Teams でのデスクトップ共有を構成する](https://docs.microsoft.com/ja-jp/microsoftteams/configure-desktop-sharing)
* Content Source: [Teams/configure-desktop-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/configure-desktop-sharing.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **Lolaj**

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@OfficeGlobal @samanthaw

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 Could you please verify on your side? I'm not able to see the issue, it might be fixed by an update

PrintScreen:
![image](https://user-images.githubusercontent.com/47977325/65134598-d2086280-da04-11e9-87d7-f973705ead00.png)

**Comment by hyoshioka0128** [comment]
@OfficeGlobal - Fixed by an update.
Close #2991
Thank you.
