### ISSUE TITLE
Maximum number of teams that user can join need to be added.

### ISSUE THREAD

**Issue by moegitree** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2993]
Maximum number of teams that user can join need to be added. For Office365 group, this upper limit is 1000. 
Is this the same for teams? 
Office 365 group: https://docs.microsoft.com/en-us/office365/admin/create-groups/office-365-groups?view=o365-worldwide

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Microsoft Teams の制限事項と仕様](https://docs.microsoft.com/ja-jp/microsoftteams/limits-specifications-teams#feedback)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@moegitree Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@OfficeGlobal @samanthaw

**Comment by Reeced40** [comment]
@moegitree Thank you for reaching out, we're investigating this.

**Comment by scanum** [comment]
@moegitree Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
