### ISSUE TITLE
Allow Chat in Meetings Setting

### ISSUE THREAD

**Issue by MikeParker365** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2994]
In this document this is listed as coming soon and under "Content Sharing" section. This is now available and is part of the "Participants & guests" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams#meeting-policy-settings---audio--video)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@MikeParker365 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@MikeParker365 Thank you for reaching out. Are you suggesting removing the 'coming soon' from the document.

**Comment by scanum** [comment]
@MikeParker365 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by thewrabbit** [comment]
Not sure if commenting will re-open this, but yes this feature is available so would suggest removing coming soon.  It is also not a per organizer setting, but a per user setting.  If chat disabled users can view chat in the meeting but not contribute.  If enabled users can chat.
