### ISSUE TITLE
Link to "Teams Adoption Guide" is broken

### ISSUE THREAD

**Issue by benleach** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2995]
as per title, goes to a 404 error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eba12367-7fe2-b316-3049-48aec995e112
* Version Independent ID: acca35eb-c728-a728-b731-eada916c43a2
* Content: [Understand teams and channels in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-adoption-understand-teams-and-channels#feedback)
* Content Source: [Teams/teams-adoption-understand-teams-and-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-adoption-understand-teams-and-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@benleach Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@benleach Thank you for reaching out, could this be the correct link that you're looking for - https://docs.microsoft.com/microsoftteams/adopt-microsoft-teams-landing-page

**Comment by LanaChin** [comment]
@Reeced40  - This is the link to the Teams Adoption Guide:  https://aka.ms/teamstoolkit.

**Comment by LanaChin** [comment]
Link fixed. Closing issue.
