### ISSUE TITLE
Screenshots from Teams would be helpful

### ISSUE THREAD

**Issue by StPhil** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2997]
In the links to policies set in Microsoft Groups (expiration being the prime example) there are screen shots referencing the visual expectation in email. It would be helpful to see some screen shots specific to what these look like in Teams in this Doc. Thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c43928-84c0-0a75-9354-66aef3b83e46
* Version Independent ID: f95298ae-de58-02eb-0b49-8390ab161d4c
* Content: [Plan for governance in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/plan-teams-governance#group-and-team-expiration-retention-and-archiving)
* Content Source: [Teams/plan-teams-governance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-teams-governance.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@StPhil Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
@scanum Because the specific of this query, can you contact product group and see if it's possible to get some graphics here?. I'm unable to run governance teams.

**Comment by scanum** [comment]
@LanaChin Hi Lana, could we please have product group see if it is possible to get a graph here? Thanks!

**Comment by LolaJacobsen** [comment]
Thanks for the suggestion, @StPhil. At this point, we don't have any plans to add screen shots to this article.
