### ISSUE TITLE
Manage app permission policies in Microsoft Teams : Not Working

### ISSUE THREAD

**Issue by satyansh-sagar** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2998]
I created a new custom access policy in teams following this article [Click Here](https://docs.microsoft.com/en-US/microsoftteams/teams-app-permission-policies?WT.mc_id=TeamsAdminCenterCSH)

In organization wide settings I blocked all the Tenant apps and in my custom policy I gave access to one of my Chat Bot i recently added. event then all the suers are able to access the bot and chat with it.

Can anyone help me on this? @msft-jinayoon  @msftgits  @msftbrking

**Comment by scanum** [comment]
@satyansh-sagar Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@satyansh-sagar thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by satyansh-sagar** [comment]
@scanum Thank you for writing. The issue got resolved. The thing was the policy takes a minimum of 2 hours to a max of 24 hours to get reflected. Id possible please include that in the documentation.
