### ISSUE TITLE
Need detail information.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#300]
It would be very helpful if there are more explanations on this page on what every thing on the picture means or at least links to other useful sites where all the terminologies are explained.

It would be nice if you add logical network topology for deploying Skype for Business. I found how to   connect to public internet but can not find how to connect the private company wan.

--

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b56523-5d43-fe49-d754-ec50d2ac43a8
* Version Independent ID: 4d729a96-65a1-bf26-f789-a5cf1b55532b
* Content: [Technical diagrams for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/technical-diagrams)
* Content Source: [Skype/SfbServer/technical-diagrams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/technical-diagrams.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
detailed explications of most of the posters would defeat the purpose, they are summaries and not detailed docs by their nature.

A workloads poster for SfBO has been proposed and shot down already. The information changes too frequently to make such a poster practical.
