### ISSUE TITLE
[LOC] Back-Translation "新規-CsVideoInteropServiceProvider"→"New-CsVideoInteropServiceProvider"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3007]
ja-jp:"https://docs.microsoft.com/ja-jp/microsoftteams/cloud-video-interop"
![cloud-video-interop_j](https://user-images.githubusercontent.com/40815708/64905000-f7e3ed80-d70c-11e9-80ab-0bf9abcfb033.png)

en-us:"https://docs.microsoft.com/en-us/microsoftteams/cloud-video-interop"
![cloud-video-interop_e](https://user-images.githubusercontent.com/40815708/64904997-f1ee0c80-d70c-11e9-825b-6919e78073ff.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 046dec87-2354-a9db-ae19-3bfaa2626bef
* Version Independent ID: 23e7d18f-bbab-75e1-7c85-9b0d0e8f4382
* Content: [Microsoft Teams のクラウド ビデオ相互運用性](https://docs.microsoft.com/ja-jp/microsoftteams/cloud-video-interop)
* Content Source: [Teams/cloud-video-interop.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-video-interop.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Hello @scanum  I'm not sure if we could fix that type of translation error by modifying something on our end.
I've reviewed the md file but I was not able to find out what makes it translate or not, please contact the author for it. Thank you.

**Comment by hyoshioka0128** [comment]
related:  #2927 "[LOC] Back-Translation "チームの追加ユーザー"→"Add-TeamUser""
 ↑ Similar mistranslation:"→"新しい-チーム"→"New-Team"

**Comment by scanum** [comment]
@officeglobal Hi! Is this something you can maybe help with this? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@hyoshioka0128, @scanum article has been HumanTranslated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal - Corrected.
Closed  #3007.
Thanks.
