### ISSUE TITLE
Bad link in Medium Org - DNS Load balancing

### ISSUE THREAD

**Issue by Atreidae** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3009]
Seems to be a copy paste error in the Medium Org - DNS Loadbalancing heading. 
Paragraph looks like its supposed to link to something, but has text that appears to be a relative link

"...as the hardware load balancers are needed only for HTTP traffic. For more information, see (../../plan-your-deployment/network-requirements/load-balancing.md#BKMK_DNSLoadBalancing)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8833bcab-c38d-60b2-40c0-50f7e5fe2dc2
* Version Independent ID: 8d7d3a8d-f626-15b4-d1ff-dabe33de228a
* Content: [Reference topologies for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/topology-basics/reference-topologies#reference-topology-for-a-medium-organization)
* Content Source: [Skype/SfbServer/plan-your-deployment/topology-basics/reference-topologies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/topology-basics/reference-topologies.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Atreidae Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Atreidae  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by msbemba** [comment]
@Atreidae Thank you for the feedback. The URL is updated now and you should be viewing the correct link for DNS load Balancing.

Thanks
Sri
