### ISSUE TITLE
Disable Automatic Updates!

### ISSUE THREAD

**Issue by JamesHeathcote** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3010]
How do you prevent Microsoft pushing firmware updates to phones managed through the Teams Site.  I have wasted two weeks fixing and issue, only to find this morning that Microsoft have broken all my phones AGAIN!

I had set the policy Set-CsIPPhonePolicy -EnableDeviceUpdate $false but this is being ignored.

We use Yealink T55a for Microsoft Teams devices.  At present calls from our call queues cannot be answered for our Main DDI line.  Microsoft are pushing the firmware 58.15.0.45.  Your very own site says that the only version of firmware support is 58.15.0.36.  I had this successfully working on Friday only to come in this morning to find it broken again.

https://docs.microsoft.com/en-us/microsoftteams/teams-ip-phones

To say I am unhappy is an understatement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a627b5d-3edc-1add-b921-1dcd49c38653
* Version Independent ID: a2e2bd3a-31c0-471a-05fb-fd64bd942c4a
* Content: [Manage your devices in Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/device-management?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/device-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/device-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@JamesHeathcote Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jambirk** [comment]
@JamesHeathcote   I'm not seeing an option in the device management part of admin center for suppressing updates. If suppression via Powershell if also failing, please open a support ticket for your issue. If you've already done so, please provide the ticket number. 

@scanum At minimum, this may be an issue to cover in our Known issues article.

**Comment by TokyoScarab** [comment]
@JamesHeathcote Hello and thank you for bringing up this issue.  I'll be investigating this and will be getting back to you on this issue, thanks!

**Comment by TokyoScarab** [comment]
@JamesHeathcote Were you able to open a support ticket and hear anything back from that?

**Comment by scanum** [comment]
@JamesHeathcote Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
