### ISSUE TITLE
 Another Lync Server product with version 6.0.9319.0 is already installed

### ISSUE THREAD

**Issue by rane52** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3011]
5 out of 6 Front end servers in two pools works as you suggested  but I keep getting this error on one of the FE server 
Product: Microsoft Lync Server 2013, Backup Service -- Another Lync Server product with version 6.0.9319.0 is already installed. Lync Server products with different versions cannot be installed together. Installation cannot continue.

Couldnt find any services for Skype Backup in the machine anywhere!! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5213c253-ce94-34bb-1e33-cf975c8c1b53
* Version Independent ID: f51f945f-96be-c46e-b71a-1a2d4fa2cff8
* Content: [Deploy paired Front End pools for disaster recovery in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-high-availability-and-disaster-recovery/front-end-pools-for-disaster-recovery)
* Content Source: [Skype/SfbServer/deploy/deploy-high-availability-and-disaster-recovery/front-end-pools-for-disaster-recovery.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-high-availability-and-disaster-recovery/front-end-pools-for-disaster-recovery.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@rane52 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jambirk** [comment]
@rane52 have you opened a support ticket for this issue?

**Comment by msbemba** [comment]
@rane52  Thank you for your feedback. This seems more like an issue with the local server. I do not see anything to be changed in the document that you are referring to. I would suggest contact support to resolve the problem. In case if you feel anything needs to updated in this document, Do let us know.

@scanum Could you please help @rane52 with contact details for Support?

Thanks
Sri

**Comment by scanum** [comment]
@rane52 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
