### ISSUE TITLE
Unclear/conflicting information about supported OS

### ISSUE THREAD

**Issue by jholl016** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3012]
This page only specifies a minimum OS version of Windows 10 1709.  A non-specific note about a 6-month delay for feature updates delivered through Windows Update is also included.  However, organizations that deliver feature updates via other means (such as SCCM) need more specific direction about supported versions.  For instance, this blog post from July suggests that 1809 is not supported: https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/Microsoft-Teams-Rooms-July-Update/ba-p/758164  and that 1903 support is "coming soon".

There should be a clear and concise list on this page that says exactly which builds of Windows 10 are approved for use with Microsoft Teams Rooms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ecd6ee6-8850-f346-5684-9c5d2444789f
* Version Independent ID: a55a7a01-211d-147a-5332-b68e1051a2a1
* Content: [Version Support](https://docs.microsoft.com/en-us/microsoftteams/room-systems/srs2-lifecycle-support)
* Content Source: [Teams/room-systems/srs2-lifecycle-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/srs2-lifecycle-support.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@jholl016 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jambirk** [comment]
@scanum this isn't a correction, it requires new content and collaboration with the product group. Please create a work item for Lana to handle this.

**Comment by TokyoScarab** [comment]
@jholl016 Hello and thank you for bringing up this issue.  I'll be investigating this and will be getting back to you on this issue, thanks!

**Comment by jambirk** [comment]
@sohailta  can you provide input needed here?

**Comment by TokyoScarab** [comment]
@scanum  After going into this more, I agree with @jambirk that this would require input from the product group.

**Comment by scanum** [comment]
@sohailta Hi Sohail, any updates on this? Thanks!

**Comment by jambirk** [comment]
@jholl016  The update addressing this should be visible tomorrow morning. Thanks for bringing it to our attention, I think the article is greatly improved now.

**Comment by jholl016** [comment]
Looks great. Very much improved. Thanks everyone!
