### ISSUE TITLE
Missing link under "Routing Group Level quorum loss"

### ISSUE THREAD

**Issue by Atreidae** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3017]
At the bottom of the Routing Group Level quorum loss paragraph, there is supposed to be a link with more information. But it is missing.

"For more information about how to use this cmdlet, see ."

I assume its supposed to be pointing here?
https://docs.microsoft.com/en-us/powershell/module/skype/reset-cspoolregistrarstate?view=skype-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cd12943-2c9d-bcfb-8a7f-9b184c34f4e4
* Version Independent ID: 6576e82d-b941-b14c-88e5-34d968dcd44f
* Content: [Front End Pool high availability and management](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/high-availability-and-disaster-recovery/high-availability?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json)
* Content Source: [Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/high-availability.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/high-availability.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Atreidae Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by msbemba** [comment]
@Atreidae Thank you for the feedback. We have added the link with more information via PR https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/3057

Thanks
Sri

**Comment by scanum** [comment]
@Atreidae Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
