### ISSUE TITLE
Re-open case #2898

### ISSUE THREAD

**Issue by Atreidae** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3018]
Original reporter has posted source in comment. https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2898#issuecomment-531345595

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cd12943-2c9d-bcfb-8a7f-9b184c34f4e4
* Version Independent ID: 6576e82d-b941-b14c-88e5-34d968dcd44f
* Content: [Front End Pool high availability and management](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/high-availability-and-disaster-recovery/high-availability?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json)
* Content Source: [Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/high-availability.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/high-availability.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Atreidae Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jambirk** [comment]
The file is probably shared content between 2015 and 2019 versions. This update will require making this difference between the versions unambiguous, without requiring a split in the topic.

**Comment by TokyoScarab** [comment]
@Atreidae Hello and thank you for bringing up this issue.  I'll be investigating this and will be getting back to you on this issue, thanks!

**Comment by j0rt3g4** [comment]
PR #3141

**Comment by scanum** [comment]
@Atreidae Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
