### ISSUE TITLE
Where?

### ISSUE THREAD

**Issue by joesko** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#302]
I am unable to find the Skype App in the Office 365 admin area.  I want to use it for my https://sko.tv business.  Where exactly is it?  Could you include screen shots, that would be super helpful?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3e575c6-fa35-d9ba-259f-14d4bd12550a
* Version Independent ID: f3b6b892-7859-c1ca-6cce-b3826d77e50f
* Content: [Set up Skype for Business Online](https://docs.microsoft.com/en-us/skypeforbusiness/set-up-skype-for-business-online/set-up-skype-for-business-online)
* Content Source: [Skype/SfbOnline/set-up-skype-for-business-online/set-up-skype-for-business-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-skype-for-business-online/set-up-skype-for-business-online.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@joesko - The Skype for Business Online app is a client app you can download and install on your computer. Microsoft Teams has the same functionality and might be a better option. You can open Microsoft Teams by clicking the 'waffle' menu and selecting Teams. Here are some details on Teams: https://docs.microsoft.com/en-us/microsoftteams/teams-overview    Here is an article on the Teams clients including the web version: https://docs.microsoft.com/en-us/microsoftteams/get-clients
