### ISSUE TITLE
Inconsistent content on Dutch version

### ISSUE THREAD

**Issue by JetzeMellema** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3030]
Compare https://docs.microsoft.com/nl-nl/microsoftteams/direct-routing-migrating and https://docs.microsoft.com/en-us/microsoftteams/direct-routing-migrating

In the column in section 'User provisioning end-state for various PSTN connectivity options', row TeamsUpgradePolicy1, the most right cell contains TeamsOnly. The Dutch version says 'Eilanden- of TeamsOnly' with translates to Islands or TeamsOnly.

Machine translation to Dutch is terrible and in general useless because 90% of the Dutch speak English. But it get's worse when the content between both versions are not consistent.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: a67f6690-eb59-153f-a6b1-4bb14398a05c
* Version Independent ID: 9cddeb98-498a-8c5b-2690-5d0f79da795e
* Content: [Migreren naar directe routering](https://docs.microsoft.com/nl-nl/microsoftteams/direct-routing-migrating)
* Content Source: [Teams/direct-routing-migrating.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-migrating.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@JetzeMellema  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@JetzeMellema Hello and thank you for bringing up this issue.  I'll be investigating this and will be getting back to you on this issue, thanks!

**Comment by TokyoScarab** [comment]
@CarolynRowe As the page author, I would appreciate your input on this issue, thanks!

**Comment by CarolynRowe** [comment]
We should change the Dutch version to match the English version.  You will need to contact localization.  @TinaMcN will know who to contact.

**Comment by TinaMcN** [comment]
@JetzeMellema thank you very much for reporting this.  We have a few issues with our machine translation tool but I haven't seen this particular issue before.  I assigned a bug to the MT tool team to investigate it.   As that may take some time @OfficeGlobal please uplift this topic to human translation.  The same issue occurs for other languages (German, Japanese etc.) so please uplift for those languages also.

**Comment by OfficeGlobal** [comment]
@TinaMcN Working on a fix (Bug 3695998)

**Comment by TokyoScarab** [comment]
@CarolynRowe Thank you very much for your help!

**Comment by OfficeGlobal** [comment]
@JetzeMellema, @TinaMcN  article was HumanTranslated and published live

**Comment by scanum** [comment]
@JetzeMellema Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
