### ISSUE TITLE
Enabling Scoped Directory Search - Bypassable

### ISSUE THREAD

**Issue by jelliott7** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3031]
Currently, enabled the scoped search in Teams via ABP works properly if the user is in the Teams app, however they are still able to search for and join any Team through the OWA/Outlook app ("Discover Groups"/search team name).

The feature on this page should hide visibility of groups/teams universally throughout the tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84066c98-38a4-e59a-893f-da38a4a11bf3
* Version Independent ID: 890a4978-0e9b-2691-a2ab-8b5512e5e76f
* Content: [Use Microsoft Teams scoped directory search](https://docs.microsoft.com/en-us/microsoftteams/teams-scoped-directory-search#feedback)
* Content Source: [Teams/teams-scoped-directory-search.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-scoped-directory-search.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@jelliott7  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@jelliott7 Hello and thank you for bringing up this issue.  I'll be investigating this and will be getting back to you on this issue, thanks!

**Comment by TokyoScarab** [comment]
@jelliott7 So if I understand you correctly, you are pointing out a suggestion?  Is that right?

**Comment by jelliott7** [comment]
No. It's a bug.

This feature is meant to act as an ethical firewall to prevent visibility of teams/groups as defined in Exchange Address Book policies.

The problem lies in that there is a workaround for users to still access teams that they shouldn't be able to access. They do this by simply navigating to the Outlook Desktop App, clicking the "Browse Groups" button, and searching for any Team in the tenant (even those restricted by the ABPs).

This workaround should be considered a bug as it effectively moots the entire feature.

**Comment by scanum** [comment]
@jelliott7 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
