### ISSUE TITLE
Room Systems

### ISSUE THREAD

**Issue by microsoftsearch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3033]
Are room systems also supported or is it only conference phones and desk phones?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a627b5d-3edc-1add-b921-1dcd49c38653
* Version Independent ID: a2e2bd3a-31c0-471a-05fb-fd64bd942c4a
* Content: [Manage your devices in Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/device-management?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/device-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/device-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@microsoftsearch  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@microsoftsearch thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by microsoftsearch** [comment]
They couldn't help either and this is the only documentation that I could find regarding this feature. Based on the way the document is structured, I would imagine it's not supported because it explicitly states that it supports conference phones and desk phones.
