### ISSUE TITLE
Feature Release

### ISSUE THREAD

**Issue by skahlam** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3035]
Hi there, 
I am wondering why there is so much information floating around about Teams Private Channels but the feature has yet to be rolled out.  Latest I heard was by end of October.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd13cd2b-3dca-1b7c-9970-c0f8c2348712
* Version Independent ID: 318c6208-531a-3600-e45b-c43ea845db86
* Content: [Manage teams policies in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-policies#feedback)
* Content Source: [Teams/teams-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@skahlam thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by skahlam** [comment]
I have already spoken to MS Support and they have told me this feature is not available yet and recently info surfaced stating it would not be rolled out til end of October 2019.


Cheers!


 
Stephanie Kahlam | Consultant
Regroove Solutions Inc. |  
www.regroove.ca
Phone: 250.220.4575
