### ISSUE TITLE
Incorrect PowerShell code for "To test the effective settings of a dial plan"

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3040]
Current PowerShell example says:

> To test the effective settings of a dial plan, run:
> `Test-CsEffectiveTenantDialPlan -DialedNumber 14255551234 -Identity 1849827b-a810-40a8-8f77-e94250d4680b_US_TenantDialPlanRedmond`

Above example is incorrect.

Correct syntax:

**option 1:**
`Test-CsEffectiveTenantDialPlan -DialedNumber 14255551234 -Identity amos.marble@contoso.com`

**option 2:**
`Test-CsEffectiveTenantDialPlan -DialedNumber 14255551234 -EffectiveTenantDialPlanName 1849827b-a810-40a8-8f77-e94250d4680b_US_TenantDialPlanRedmond`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 451b44cf-961a-5bf5-e4b3-16b96e008dd7
* Version Independent ID: 54e706e1-aaa2-3a03-b8c6-5e96244b85ac
* Content: [Create and manage dial plans](https://docs.microsoft.com/en-us/microsoftteams/create-and-manage-dial-plans)
* Content Source: [Teams/create-and-manage-dial-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-and-manage-dial-plans.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by shivtorov** [comment]
_additional note_
not sure what's the current naming convention for US tenant dial plan, but all AU tenant dial plans I create these days have the following naming convention:
**<guid>_<TenantDialPlanName>_<CountryCode>**
e.g. _"3551d27d-1415-4685-b333-0f7bf705d86e_au08_AU"_

but in your example, the naming convention is different:
**<guid>_<CountryCode>_<TenantDialPlanName>**
i.e. _"1849827b-a810-40a8-8f77-e94250d4680b_US_TenantDialPlanRedmond"_

**Comment by shivtorov** [comment]
related issue: https://github.com/MicrosoftDocs/office-docs-powershell/issues/4012

**Comment by scanum** [comment]
@shivtorov  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@shivtorov Hello and thank you for bringing up this issue.  I'll be investigating this and will be getting back to you on this issue, thanks!

**Comment by shivtorov** [comment]
@TokyoScarab, the cmdlet article has been fixed (https://docs.microsoft.com/en-us/powershell/module/skype/test-cseffectivetenantdialplan).
You can now just copy/paste command example from there to this article.

**Comment by shivtorov** [comment]
@officebot #close
