### ISSUE TITLE
Incorrect PowerShell code for "Configure online hybrid Mediation Server Settings"

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3041]
PowerShell code in "Configure online hybrid Mediation Server Settings" section currently says:
**Gets**-CsOnlineUser -Identity &lt;UserPrincipalName&gt;

This is wrong.
Correct code:
**Get**-CsOnlineUser -Identity &lt;UserPrincipalName&gt;

note: "Gets" vs "Get"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 328cfd03-27e5-7756-f004-811f2dc7d2ef
* Version Independent ID: 010d16a6-1474-61ae-a55e-47f299705a74
* Content: [Configure Cloud Connector integration with your Office 365 tenant](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/configure-cloud-connector-integration-with-your-office-365-tenant)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/configure-cloud-connector-integration-with-your-office-365-tenant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/configure-cloud-connector-integration-with-your-office-365-tenant.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by TokyoScarab** [comment]
@shivtorov Hello and thank you for bringing up this issue.  I'll be investigating this and will be getting back to you on this issue, thanks!

**Comment by scanum** [comment]
@shivtorov Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
