### ISSUE TITLE
Incorrect note in section "Enable users for Phone System"

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3042]
The note block in "Enable users for Phone System" section says:

>
> Note
> You can also specify a user's Identity by their SIP address, User Principal name (UPN), domain name and username (domain\username), and display name in Active Directory ("Bob Kelly").
>

I believe this is wrong. This is SFBO (with CCE) environment.
**"domain name and username (domain\username)" format for user's Identity is not allowed.**

I guess the note should say something like: 

_User Identities can be specified using one of the following formats: 1) the user's SIP address; 2) the user's user principal name (UPN); or, 3) the user's Active Directory display name (for example, Ken Myer).
You can use the asterisk (*) wildcard character when using the Display Name as the user Identity. For example, the Identity "* Smith" returns all the users who have a display name that ends with the string value " Smith"._

reference: 
"-Identity" parameter
https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 328cfd03-27e5-7756-f004-811f2dc7d2ef
* Version Independent ID: 010d16a6-1474-61ae-a55e-47f299705a74
* Content: [Configure Cloud Connector integration with your Office 365 tenant](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/configure-cloud-connector-integration-with-your-office-365-tenant)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/configure-cloud-connector-integration-with-your-office-365-tenant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/configure-cloud-connector-integration-with-your-office-365-tenant.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@shivtorov  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@shivtorov Hello and thank you for bringing up this issue.  I'll be investigating this and will be getting back to you on this issue, thanks!
