### ISSUE TITLE
Incorrect Management Pack link on this page 

### ISSUE THREAD

**Issue by cruelhughes** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3047]
The link listed on this page is incorrect.  https://www.microsoft.com/download/details.aspx?id=42320
  Skype Room System Management Pack   actually points to the Microsoft Lync Room System Management Pack which will not work for Skype Room.  The discovery is based upon a reg key for Lync. I have not been able to find a MP that supports Skype Room

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbf1cb56-ad48-dfd3-d4a4-b3bc85675734
* Version Independent ID: 8aab81ca-15f5-f147-e26b-0de07447f12d
* Content: [Skype Room System manageability and tools](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/manageability-and-tools#feedback)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/manageability-and-tools.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/manageability-and-tools.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@cruelhughes  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@cruelhughes Hello and thank you for bringing up this issue.  I'll be investigating this and will be getting back to you on this issue, thanks!

**Comment by TokyoScarab** [comment]
@LanaChin Being the page author, what are your thoughts? I know that there has been an integration with SRS becoming Microsoft Teams Rooms.  What would be the most appropriate action for this link, redirecting it or removing it altogether? If it's the later, where would you suggest?

**Comment by scanum** [comment]
@LanaChin Hi Lana, could you please aid us with next steps? Thanks!

**Comment by LanaChin** [comment]
Pinged the PM.

**Comment by LanaChin** [comment]
This section is not applicable and has been removed. Thanks for bringing up this issue.  Cheers.
