### ISSUE TITLE
Change Kollective link

### ISSUE THREAD

**Issue by arianasexton** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3049]
We'd like the Kollective link to point to our Teams page  https://kollective.com/microsoft-pilot/ rather than our homepage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: becbf3ca-b88c-b033-a145-9a1af201ced3
* Version Independent ID: 41a6a9b5-d3dd-d8c9-9e97-920ff2fd1a24
* Content: [What are Microsoft Teams live events?](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/what-are-teams-live-events#feedback)
* Content Source: [Teams/teams-live-events/what-are-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/what-are-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@arianasexton Closing this issue because it is duplicated.
