### ISSUE TITLE
Kollective URL

### ISSUE THREAD

**Issue by arianasexton** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3050]
We'd like the Kollective link to point to our Teams page: https://kollective.com/microsoft-pilot/ rather than our homepage. Is that possible? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9aa4676-855a-fddb-bb0b-96b7095c695e
* Version Independent ID: 7c39f08c-0d56-6d29-1356-879d9d6ff51c
* Content: [Set up for live events in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/set-up-for-teams-live-events)
* Content Source: [Teams/teams-live-events/set-up-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/set-up-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@arianasexton  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by msbemba** [comment]
@arianasexton  Thank you for the feedback. We have updated the doc to reflect the team's link. This can be tracked via PR https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/3056

Thanks 
Sri

**Comment by scanum** [comment]
@arianasexton 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
