### ISSUE TITLE
Kollective URL 

### ISSUE THREAD

**Issue by arianasexton** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3051]
Hello - we'd like the Kollective hyperlink to point to our Teams page https://kollective.com/microsoft-pilot/ rather than our homepage. Can you please change this? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5372edb-6ffe-34a3-0839-587e48f66f6b
* Version Independent ID: 43903b13-37de-7dde-5b8c-739586cc2d87
* Content: [Microsoft Teams live event usage report](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-live-event-usage-report)
* Content Source: [Teams/teams-analytics-and-reports/teams-live-event-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-live-event-usage-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@arianasexton Closing this issue because it is duplicated.
