### ISSUE TITLE
[LOC] Back-Translation "新規-CsRgsAgentGroup"→"New-CsRgsAgentGroup"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3052]
ja-jp:"https://docs.microsoft.com/ja-jp/lyncserver/lync-server-2013-response-group-application-cmdlets"
![lync-server-2013-response-group-application-cmdlets_j](https://user-images.githubusercontent.com/40815708/65210583-ae155180-dad6-11e9-91ab-fe735ba99aa5.png)

en-us:"https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-response-group-application-cmdlets"
![lync-server-2013-response-group-application-cmdlets_e](https://user-images.githubusercontent.com/40815708/65210576-a786da00-dad6-11e9-8e47-3caf52971320.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a68b0094-9985-e3e3-f064-14ad8e83a68e
* Version Independent ID: 7faa8a43-6e9d-84a8-09b2-87e7520a1c32
* Content: [Lync Server 2013: 応答グループのアプリケーションコマンドレット](https://docs.microsoft.com/ja-jp/lyncserver/lync-server-2013-response-group-application-cmdlets)
* Content Source: [Lync/LyncServer/lync-server-2013-response-group-application-cmdlets.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Lync/LyncServer/lync-server-2013-response-group-application-cmdlets.md)
* Product: **lync-server-2013**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hyoshioka0128  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by msbemba** [comment]
@hyoshioka0128 thank you for your feedback.

@scanum Can you include Tina to sort this localization issue? 

Thanks Sri

**Comment by scanum** [comment]
@officeglobal Hi! Could you please aid on this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum article has been HumanTranslated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal - Thank you.
Closed #3052
