### ISSUE TITLE
[LOC] Back-Translation "新規-CsExUmContact"→"New-CsExUmContact"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3053]
ja-jp:"https://docs.microsoft.com/ja-jp/lyncserver/lync-server-2013-exchange-um-cmdlets"
![lync-server-2013-exchange-um-cmdlets_j](https://user-images.githubusercontent.com/40815708/65212352-be302f80-dadc-11e9-94d4-2afa3fe77bb4.png)

en-us:"https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-exchange-um-cmdlets"
![lync-server-2013-exchange-um-cmdlets_e](https://user-images.githubusercontent.com/40815708/65212359-c25c4d00-dadc-11e9-92ba-5c4cc68626ff.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: efd94d96-7aa0-74b5-3962-88c5d0fc4443
* Version Independent ID: cb841140-62db-4e17-abc3-41c0e53149ba
* Content: [Lync Server 2013: Exchange UM コマンドレット](https://docs.microsoft.com/ja-jp/lyncserver/lync-server-2013-exchange-um-cmdlets)
* Content Source: [Lync/LyncServer/lync-server-2013-exchange-um-cmdlets.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Lync/LyncServer/lync-server-2013-exchange-um-cmdlets.md)
* Product: **lync-server-2013**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hyoshioka0128  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@MollyMalone

**Comment by TinaMcN** [comment]
@OfficeGlobal  please uplift this topic to human translation.

**Comment by OfficeGlobal** [comment]
@TinaMcN Working on a fix (Bug 3686897)

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @TinaMcN article has been HumanTranslated and published live.

**Comment by hyoshioka0128** [comment]
@TinaMcN  @OfficeGlobal  - Thank you.
Closed #3053
