### ISSUE TITLE
No current 0365 license yet?

### ISSUE THREAD

**Issue by wlee714** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3054]
Hi - is this free trial available only to those with existing 0365 subscriptions? How about those without existing O365 subscriptions or using competing products? thanks

**Comment by scanum** [comment]
@wlee714 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
