### ISSUE TITLE
What happens when the trial ends?

### ISSUE THREAD

**Issue by liamgsmith** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3055]
Explicitly, what happens when the trial ends? What does the end user see? Does functionality stop? The purple Note talks about not losing data which is great but is there a trigger for the Admin to realise what the problem might be?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the Microsoft Teams Commercial Cloud Trial offer](https://docs.microsoft.com/en-us/microsoftteams/iw-trial-teams#feedback)
* Content Source: [Teams/iw-trial-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/iw-trial-teams.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@liamgsmith  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@liamgsmith Thank you for reaching out. The grace period is usually 30 days. Thereafter everything will be erased.

**Comment by scanum** [comment]
@liamgsmith Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
