### ISSUE TITLE
Same commands as to set up unified messaging? 

### ISSUE THREAD

**Issue by briandahlincoyne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3058]
These steps are identical from a powershell command perspective to setting up  the soon to be retired Unified messaging, is that to be expected? 

https://blogs.technet.microsoft.com/nagshettykadwadi/2017/10/18/integrate-skype-for-business-server-with-exchange-online-unified-messaging-in-hybrid-scenario/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec8b8afb-b9ca-8136-b907-5bbff4c9dcf1
* Version Independent ID: d4f68818-6fe6-5bb7-f108-e26a643f2cc7
* Content: [Configure Cloud Voicemail service for on-premises users](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/configure-cloud-voicemail#feedback)
* Content Source: [Skype/SfbHybrid/hybrid/configure-cloud-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-cloud-voicemail.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@briandahlincoyne  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@briandahlincoyne thanks for pointing this out. I'll investigate further and get back to you.

**Comment by lindspea** [comment]
@dstrome could you perhaps assist please.

**Comment by dstrome** [comment]
Checking

**Comment by dstrome** [comment]
@briandahlincoyne if you're referring to the new hosting provider command, the endpoint configuration is the same. We handle routing to the proper service via routing on the backend.
