### ISSUE TITLE
Is trial length validity visible to client? Ability to shorten it? What is the base O365 license that can be used?

### ISSUE THREAD

**Issue by wlee714** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3059]
Hi is the length of the trial visible to the client? If this is a partner driven trial and the partner would like to shorten the length to say 6 months - would it be possible to do so without the customer seeing that the default length is 1 year?  
Also which current O365 licenses are qualified? or rather unqualified (if that is a shorter list) 
thank you

**Comment by scanum** [comment]
@wlee714 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
