### ISSUE TITLE
Need help on deploying analog devices.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#306]
Can you help me to find how to deploy analog devices in SfB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 501f4f70-449c-de13-affd-fe505623102a
* Version Independent ID: 2ad73563-87c6-d2a1-6046-b9fd708cb9f6
* Content: [PSTN connectivity components in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/enterprise-voice-solution/pstn-connectivity)
* Content Source: [Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/pstn-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/pstn-connectivity.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by jambirk** [comment]
analog devices such as rotary and touch tone desk phones can't be deployed in SfB.
