### ISSUE TITLE
Inline Translation for Guests

### ISSUE THREAD

**Issue by sir-benniboy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3060]
Guests are not able to use inline translation. This should either be included or specified in the comparison list. (Team member vs guests)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [What the guest experience is like](https://docs.microsoft.com/en-us/MicrosoftTeams/guest-experience#feedback)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@sir-benniboy  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@sir-benniboy. Thank you for reaching out and helping improve MS Docs. Please have a look at this doc and let me know if it helps with this. https://docs.microsoft.com/microsoftteams/inline-message-translation-teams

**Comment by sir-benniboy** [comment]
Hi Lindsay
No it doesn't. Inline translation can be activated on your own teams tenant, but won't work when connected as a guest to another company. That information is missing from the MS docs page on which I raised a ticket.
Kind regards
Benjamin

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by scanum** [comment]
@sir-benniboy Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
