### ISSUE TITLE
[LOC] Back-Translation "CsDeviceUpdateConfigurationオプションの削除"→" Remove-CsDeviceUpdateConfiguration"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3061]
ja-jp:"https://docs.microsoft.com/ja-jp/lyncserver/lync-server-2013-delete-a-collection-of-device-update-configuration-settings"
![lync-server-2013-delete-a-collection-of-device-update-configuration-settings_j](https://user-images.githubusercontent.com/40815708/65318164-20218f80-dbd8-11e9-9a5e-0d2cf71bbc98.png)

en-us:"https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-delete-a-collection-of-device-update-configuration-settings"
![lync-server-2013-delete-a-collection-of-device-update-configuration-settings_e](https://user-images.githubusercontent.com/40815708/65318179-23b51680-dbd8-11e9-9722-ac4eca3f51cf.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: cdd3b238-d171-30ef-ad60-b81bfda1afc5
* Version Independent ID: c6d2a9ed-21f3-d0c9-d446-f3aaf97a7a2f
* Content: [Lync Server 2013: デバイス更新プログラムの構成設定のコレクションを削除する](https://docs.microsoft.com/ja-jp/lyncserver/lync-server-2013-delete-a-collection-of-device-update-configuration-settings)
* Content Source: [Lync/LyncServer/lync-server-2013-delete-a-collection-of-device-update-configuration-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Lync/LyncServer/lync-server-2013-delete-a-collection-of-device-update-configuration-settings.md)
* Product: **lync-server-2013**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hyoshioka0128  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@MollyMalone

**Comment by TinaMcN** [comment]
@OfficeGlobal please uplift this topic to human translation.

**Comment by OfficeGlobal** [comment]
@TinaMcN Working on a fix (Bug 3686897)

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @TinaMcN article has been HumanTranslated and published live

**Comment by hyoshioka0128** [comment]
@TinaMcN @OfficeGlobal - Thank you.
Closed #3061
