### ISSUE TITLE
[LOC] Back-Translation "新しい-CsDeviceUpdateConfiguration"→"New-CsDeviceUpdateConfiguration"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3062]
ja-jp:"https://docs.microsoft.com/ja-jp/lyncserver/lync-server-2013-create-or-modify-a-collection-of-device-update-configuration-settings"
![lync-server-2013-create-or-modify-a-collection-of-device-update-configuration-settings_j](https://user-images.githubusercontent.com/40815708/65318499-a8a03000-dbd8-11e9-8dd9-ea2ea447b370.png)

en-us:"https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-create-or-modify-a-collection-of-device-update-configuration-settings"
![lync-server-2013-create-or-modify-a-collection-of-device-update-configuration-settings_e](https://user-images.githubusercontent.com/40815708/65318504-ac33b700-dbd8-11e9-98e0-020ece4afb9f.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e3559a6c-26ba-3d74-e635-519a92f5494e
* Version Independent ID: a5c3829f-1642-949b-985b-92f458a94c6d
* Content: [デバイス更新構成設定のコレクションを作成または変更する](https://docs.microsoft.com/ja-jp/lyncserver/lync-server-2013-create-or-modify-a-collection-of-device-update-configuration-settings)
* Content Source: [Lync/LyncServer/lync-server-2013-create-or-modify-a-collection-of-device-update-configuration-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Lync/LyncServer/lync-server-2013-create-or-modify-a-collection-of-device-update-configuration-settings.md)
* Product: **lync-server-2013**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hyoshioka0128  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@MollyMalone

**Comment by TinaMcN** [comment]
@OfficeGlobal please uplift this topic to human translation.

**Comment by OfficeGlobal** [comment]
@TinaMcN Working on a fix (Bug 3686897)

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @TinaMcN article was HumanTranslated and published live

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
