### ISSUE TITLE
SRSv2 SCCM Task Sequence

### ISSUE THREAD

**Issue by jtelling325** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3064]
I have followed the article below, but when I go to import the task sequence, it fails with the error "Cannot validate a dependency to Package TRG00002"

https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/room-systems-scale

**Comment by scanum** [comment]
@jtelling325 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
