### ISSUE TITLE
"Store" is now called "Apps"

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3066]
In Teams desktop and web clients, as of today.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbcabee-fa96-2878-e983-3c966f84ee15
* Version Independent ID: 02fa4fd8-77e0-5cb2-a4af-576cbb68322f
* Content: [Publish apps in the Microsoft Teams Tenant Apps Catalog](https://docs.microsoft.com/en-us/microsoftteams/tenant-apps-catalog-teams)
* Content Source: [Teams/tenant-apps-catalog-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tenant-apps-catalog-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@softwarecraft  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@softwarecraft thanks for reaching out. Are you suggesting having a screenshot added reflecting "Apps" instead of "Store"?

**Comment by softwarecraft** [comment]
Yes, and any text in the doc that refers to "Store" should be updated.

**Comment by lindspea** [comment]
@scanum, @tseward will be helping with this.

**Comment by LolaJacobsen** [comment]
I updated the article. "Store" -> "Apps"

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
