### ISSUE TITLE
Office 365 admin portal > Tenant Apps Catalog is disabled in my O365 tenant

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3067]
Under "Tenant-wide settings &gt; Apps" there is a yellow sticky "Apps settings have moved to the new Microsoft Teams & Skype for Business admin center." and all settings are greyed out / disabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbcabee-fa96-2878-e983-3c966f84ee15
* Version Independent ID: 02fa4fd8-77e0-5cb2-a4af-576cbb68322f
* Content: [Publish apps in the Microsoft Teams Tenant Apps Catalog](https://docs.microsoft.com/en-us/microsoftteams/tenant-apps-catalog-teams)
* Content Source: [Teams/tenant-apps-catalog-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tenant-apps-catalog-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@softwarecraft  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@softwarecraft Thank you for reaching out and helping improve MS Docs. Please see this note and let me know if this applies to your account.  "Note: You need to be signed in to the Microsoft Teams client with an account that has either the global admin or teams service admin role enabled to publish apps for your organization." Once you have the app package, you can add it to the enterprise app catalog. While all users in the tenant can view the app catalog, only global admins and teams service admins have the ability to publish and manage it.

**Comment by softwarecraft** [comment]
I am global admin. I am able to access all functions from Teams admin centre. 

My point is that the docs under https://docs.microsoft.com/en-us/microsoftteams/tenant-apps-catalog-teams#use-the-office-365-admin-portal-to-manage-the-tenant-apps-catalog are out of date as they advise to use the O365 Admin site but this no longer works as it is greyed out, so folks need to go to the Teams Admin site.

**Comment by lindspea** [comment]
@softwarecraft thanks for clearing that up. Would you suggest changing this sentence"- "If you have apps that need bug fixes, you can temporarily disable apps through the Office 365" and replacing Office 365 with Teams Admin center?

**Comment by tseward** [comment]
We can wrap this up with #3306 which addresses the remaining pictures. The information on the Admin portal will be overhauled, including the picture.

**Comment by lindspea** [comment]
@scanum this can be closed thanks.

**Comment by scanum** [comment]
@softwarecraft 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
