### ISSUE TITLE
Microsoft Teams Graph API

### ISSUE THREAD

**Issue by GaneshPrabuBaburaj** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3068]
”Any directory object in Azure Active Directory counts towards this limit. Global admins are exempt from this limit, as are apps calling Microsoft Graph using application permissions.”

Does the above sentence meant to say the Microsoft teams number of teams count limit exempt Global admin and the Apps calling Graph API using application permission?

Also Do we have any limit for Clone Team API. We are using this API to provision Teams

**Comment by scanum** [comment]
@GaneshPrabuBaburaj thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
