### ISSUE TITLE
Need Update.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#307]
Need to update to add more details about gateway, sba, sbs etc.

Can you post the vision diagrams for these? Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8833bcab-c38d-60b2-40c0-50f7e5fe2dc2
* Version Independent ID: 8d7d3a8d-f626-15b4-d1ff-dabe33de228a
* Content: [Reference topologies for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/topology-basics/reference-topologies)
* Content Source: [Skype/SfbServer/plan-your-deployment/topology-basics/reference-topologies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/topology-basics/reference-topologies.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.
