### ISSUE TITLE
General channel restriction?

### ISSUE THREAD

**Issue by JayDeeJaye** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3070]
If there's a restriction on setting moderator preferences in the General channel, please add a note to that effect.  The only options available for the General tab are to prevent non-owners from posting to General conversations, which also prevents non-owners from replying to posts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097ecd40-1157-98ae-f438-96f9208afc03
* Version Independent ID: ea36ff93-46dc-920d-8d52-9b3b81420958
* Content: [Set up and manage channel moderation in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-channel-moderation-in-teams#feedback)
* Content Source: [Teams/manage-channel-moderation-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-channel-moderation-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@JayDeeJaye  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@JayDeeJaye thank you for reaching out. This article has been updated recently with information regarding channels. Please confirm if the information is reflecting on your side.

**Comment by scanum** [comment]
@JayDeeJaye We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
