### ISSUE TITLE
Clarification of availale SharePoint storage and Teams storage

### ISSUE THREAD

**Issue by Apoc70** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3072]
The difference between "Storage" available in an Office 365 tenant and the "Storage for Teams files" needs clarification. 

It can be read as 1TB+ SharePoint storage in a tenant for standard SharePoint site collection and sites. And additional "hidden" storage of 25TB per Team. Especially in (automatically) translated version of the en-US text this is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Apoc70  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Apoc70 Thank you for pointing this out. I'll investigate further to add clarity. In the meantime let me know if you have any suggestions for adding/changing the wording for better clarity for other users as well.

**Comment by scanum** [comment]
@Apoc70 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
