### ISSUE TITLE
Latest updates missing - https://docs.microsoft.com/en-us/SkypeForBusiness/sfb-client-updates

### ISSUE THREAD

**Issue by vekashi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3073]
Post June 2019 MSI update, no new updates are documented

**Comment by scanum** [comment]
@vekashi thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jambirk** [comment]
@scanum, this is not a support related issue, why are you referring this to support? It's a content issue. 

@qingy are you handling this again? I know Phillip is no longer involved. If not, can you please look into it?

**Comment by scanum** [comment]
@jambirk Sorry about this I will list it for resolution. Thanks

**Comment by VLG17** [comment]
@vekashi everything should be up-to-date after the PR gets merged.

**Comment by scanum** [comment]
@vekashi 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
