### ISSUE TITLE
Messages size limits?

### ISSUE THREAD

**Issue by dgancho** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3074]
Please add to this article max message size limits for a) bot messages and b) user messages (if different), so we know the limits and can handle them instead of receiving (213) PayloadTooLarge unexpectedly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@dgancho Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @dgancho, thank you for your feedback.

Maybe I don't understand you, but there is a chat size limit: "Approximately 28 KB per post":
https://docs.microsoft.com/microsoftteams/limits-specifications-teams#chat

**Comment by scanum** [comment]
@dgancho Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
