### ISSUE TITLE
Prisbild för tilläggstjänsterna

### ISSUE THREAD

**Issue by nidelius** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3077]
Saknar prisbild för tilläggstjänsterna?

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: f5c5f251-1fdf-6b3f-e9b5-494afb8f3c9c
* Version Independent ID: 20e9a555-21ad-d47c-bd16-b357dc4bdf40
* Content: [Planer för Office 365 Enterprise, E1, E3 och E4](https://docs.microsoft.com/sv-se/skypeforbusiness/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/office-365-enterprise-e1-e3-e4#feedback)
* Content Source: [Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/office-365-enterprise-e1-e3-e4.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/office-365-enterprise-e1-e3-e4.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by nidelius** [comment]
Missing prices or reference to prices pages for the add-on services

**Comment by scanum** [comment]
@nidelius Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
added information on PR #3429

**Comment by scanum** [comment]
@nidelius We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
