### ISSUE TITLE
Google Chrome Calling Support

### ISSUE THREAD

**Issue by MySkypeLab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3079]
It appears the Google Chrome now includes calling features (Calling tab, Dial pad, etc). Is the browser support table going to be updated to remove "Support for Calling is coming soon"? and add any limitations, etc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by davidslight** [comment]
A month later and you still haven't updated this page ... this is a key reference page for browser support etc.

**Comment by j0rt3g4** [comment]
Hello @MySkypeLab  I was not able to find "Support for Calling" text on the whole article.

**Comment by scanum** [comment]
@MySkypeLab 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
