### ISSUE TITLE
Need list of numbers and failures.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#308]
Adding a list of all the numbers and failures would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe46dc7d-266c-f16e-31be-46a000713c01
* Version Independent ID: 43568def-29f2-cdad-3bc0-f5b78f7e0e74
* Content: [Diagnostic Report in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/manage/health-and-monitoring/diagnostic-report)
* Content Source: [Skype/SfbServer/manage/health-and-monitoring/diagnostic-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/health-and-monitoring/diagnostic-report.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
I agree, but the information isn't available. No further action possible here.
