### ISSUE TITLE
Machine-wide installer MSI via SCCM - should Deployment Type be set to "Install for User"

### ISSUE THREAD

**Issue by edeitz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3081]
I am using SCCM to deploy the Teams Machine-wide installer.

Step 2 of the Deployment Procedure states "Use the defaults prepopulated by the MSI."

When I load the MSI into SCCM, it creates a Deployment Type. On the User Experience tab, "Installation behavior" is set to "Install for user". When I deploy it, it will only install when a user is logged-in, as expected with this setting. This creates logical issues with our deployments. Should it truly be set to Install for user? Or, could it be set to "Install for system" and still install into each user's profile when they login?

**Comment by scanum** [comment]
@edeitz Thank you for submitting feedback and contributing to the docs. We are currently investigating this. Could you please link the document?

**Comment by edeitz** [comment]
https://docs.microsoft.com/en-us/microsoftteams/msi-deployment

**Comment by j0rt3g4** [comment]
Hello @edeitz, yes I'd think that if you use "Install for system" and it will install one installation for all users instead of one for each user.

Please  @scanum could you please help me validate this answer with the author?

**Comment by scanum** [comment]
@LanaChin Could you please help us on this following issue? Just to confirm the following information. Thanks!

**Comment by scanum** [comment]
@LanaChin Could you please help us on this following issue? Just to confirm the following information. Thanks!

**Comment by LanaChin** [comment]
Hello @edeitz - following up on this and have question for you. Can you confirm whether you are deploying Teams on VDI?  Thank you.

**Comment by LanaChin** [comment]
Closing this issue for now due to age. @edeitz - let us know if you have additional questions or if you need to revisit this issue. Thanks.
