### ISSUE TITLE
Calling Plan explanation . 

### ISSUE THREAD

**Issue by Domouprav** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3082]
I Think we have to specify if "calling plan" needed if people want to use teams room system as a phone  outside of meeting . We get this question all the time . 
Regards.

**Comment by scanum** [comment]
@Domouprav thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
