### ISSUE TITLE
please remove "Windows 8" from operating system section

### ISSUE THREAD

**Issue by ikukoyoneda** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3084]
The support lifecycle of Windows 8 is already ended, so please remove "Windows 8" from supported operating system

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 29a61ff5-b3a5-158d-149a-dec344060e05
* Version Independent ID: 97fac351-a283-aaa8-cde1-fbd9cf4e8504
* Content: [Microsoft Teams アプリのハードウェア要件](https://docs.microsoft.com/ja-jp/microsoftteams/hardware-requirements-for-the-teams-app)
* Content Source: [Teams/hardware-requirements-for-the-teams-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hardware-requirements-for-the-teams-app.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@ikukoyoneda Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Molly Malone

**Comment by TinaMcN** [comment]
@lindspea @scanum The English content includes Windows 8 + Windows 7 SP1.

Operating system | Windows 10, Windows 8.1, Windows 8, or Windows 7 Service Pack 1 in 32-bit and 64-bit. For the best experience, use the latest version of any operating system.

According to this article there is extended support available until January 2020. https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet
Can you please determine if the English content should be updated?

**Comment by scanum** [comment]
@ikukoyoneda Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
