### ISSUE TITLE
Screen shot not showing what is described

### ISSUE THREAD

**Issue by Marshall-L-D** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3085]
Page says, "For example, in the following screenshot, the values are in yellow for Average jitter, Max jitter, and Average packet loss rate."  However, the screenshot immediately below shows no data in yellow and no data about jitter or packet loss rate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea52e6be-e0ae-4941-7bab-aeea5c5fc708
* Version Independent ID: a38a6f0c-cb99-ea4d-e406-968fd07ec0c2
* Content: [Use Call Analytics to troubleshoot poor call quality](https://docs.microsoft.com/en-us/microsoftteams/use-call-analytics-to-troubleshoot-poor-call-quality#feedback)
* Content Source: [Teams/use-call-analytics-to-troubleshoot-poor-call-quality.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/use-call-analytics-to-troubleshoot-poor-call-quality.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by dplotnikov** [comment]
@Marshall-L-D it has the wrong image there for sure

**Comment by scanum** [comment]
@Marshall-L-D Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Marshall-L-D thank you for pointing this out.  I'm working to have this issue fixed soonest.

**Comment by lindspea** [comment]
Hi @LolaJacobsen. Please could you assist with the screenshot and I'll add it in a PR?

**Comment by scanum** [comment]
@LolaJacobsen Following up on this issue. Thanks.

**Comment by LolaJacobsen** [comment]
We're preparing a complete overhaul of the CQD documentation over the upcoming weeks, so this artwork will get revised as part of that effort. Thanks for the heads up!
