### ISSUE TITLE
Teams Recording Resolution

### ISSUE THREAD

**Issue by blwilker** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3087]
What resolution does Teams record meetings in?  (IE: 480i, 720p, 1080p)

**Comment by dplotnikov** [comment]
@blwilker what was the article link where you were trying to find this?

**Comment by blwilker** [comment]
@dplotnikov I was not able to find this in any article that I was looking in.  But I got here from this one...https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams

**Comment by scanum** [comment]
@blwilker Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@blwilker Thank you for reaching out. I work on the writing/editing side of the docs, so please let me know which document you are referring to that needs clarity on the recording resolution?

**Comment by scanum** [comment]
@blwilker We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
