### ISSUE TITLE
Is this for Phones in a Conference Room?

### ISSUE THREAD

**Issue by kelemvor33** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3091]
Is the Meeting Room license what we'd assign to a Conference Room phone logged in with a resource account for calendaring so the phone could dial out from the phone in the room?  We tried this with a Yealink CP960 but get an error stating that it's not provisioned for dialing out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses](https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/skype-room-systems-v2#feedback)
* Content Source: [Teams/room-systems/skype-room-systems-v2.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/skype-room-systems-v2.md)
* Service: **skype-for-business-online**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by jambirk** [comment]
No, I'm pretty sure what you are describing is what we'd call a common area phone, and not a room system. A room system would support a set of peripherals like cameras and multiple front of room monitors as well as a console that can be used to make calls.

The license is specific to the Microsoft Teams Rooms app/device solution, supported devices for this solution are listed at:  
https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/requirements#hardware-requirements  

The Yealink CP960 isn't a supported device, and not part of MTR.
