### ISSUE TITLE
Please add a note that you need to apply the CU again after the service has been installed after step 

### ISSUE THREAD

**Issue by mamoelle** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3093]
We have seen customers installing the backup service and forgot to apply the CU again for the backup service. The result was a crashing backup service. 
So this would be a helpful note to reduce troubleshooting time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5213c253-ce94-34bb-1e33-cf975c8c1b53
* Version Independent ID: f51f945f-96be-c46e-b71a-1a2d4fa2cff8
* Content: [Deploy paired Front End pools for disaster recovery in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-high-availability-and-disaster-recovery/front-end-pools-for-disaster-recovery)
* Content Source: [Skype/SfbServer/deploy/deploy-high-availability-and-disaster-recovery/front-end-pools-for-disaster-recovery.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-high-availability-and-disaster-recovery/front-end-pools-for-disaster-recovery.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@mamoelle Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Added a note in PR #3430

**Comment by scanum** [comment]
@mamoelle 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
