### ISSUE TITLE
AllowPrerelease parameter cannot be found

### ISSUE THREAD

**Issue by NigelClarkExient** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3094]
Under the step: Install-Module -Name MicrosoftStaffHub -AllowPrerelease, Windows 10 is unable to install with -AllowPrerelease parameter. Removing this allowed the module to install.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ff2099-489e-1bab-640a-6f92e975dbfd
* Version Independent ID: 677d5aa5-bb07-33f4-da33-7d3a3a17fcfd
* Content: [Install the StaffHub PowerShell module](https://docs.microsoft.com/en-gb/MicrosoftTeams/expand-teams-across-your-org/shifts/install-the-staffhub-powershell-module)
* Content Source: [Teams/expand-teams-across-your-org/shifts/install-the-staffhub-powershell-module.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/expand-teams-across-your-org/shifts/install-the-staffhub-powershell-module.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by gt-adeangelis** [comment]
To add to the above, when removing the "-AllowPrerelease" it seems that does not enable all the features so future commands are not found. 

For example, command referenced on this page: https://docs.microsoft.com/en-us/microsoftteams/expand-teams-across-your-org/shifts/move-staffhub-teams-to-shifts-in-teams#prepare

PS C:\Powershell> Get-StaffHubTeamsForTenant -ManagedBy "Staffhub"
Get-StaffHubTeamsForTenant : A parameter cannot be found that matches parameter name 'ManagedBy'.
At line:1 char:28
+ Get-StaffHubTeamsForTenant -ManagedBy "Staffhub"
+                            ~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-StaffHubTeamsForTenant], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.OutlookApps.StaffHub.PowershellCmdlets.Commands.GetStaffHubTeamsForTenant

**Comment by versatu** [comment]
I had the same issue with the AllowPrerelease and I made it work by installing this modules:

Install-Module -Name PackageManagement -Repository PSGallery -Force
Install-Module -Name PowerShellGet -Repository PSGallery -Force
#Then restart shell
Install-Module -Name MicrosoftStaffHub -AllowPrerelease -Force

**Comment by scanum** [comment]
@NigelClarkExient Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by 50monkeys** [comment]
I have had the StaffHub module installed for a while now and am logged in with a Global Admin account, but am getting "Operation returned an invalid status code 'Forbidden'" when I run "Get-StaffHubTeamsForTenant". I tried the above, to update the module version, but it's not updating either. It's staying at version 1.0.1.

**Comment by gt-adeangelis** [comment]
@versatu - that solution appears to have worked for me as well.

**Comment by gtwy** [comment]
Versatu's solution worked for me as well. Was finally able to access the "Move-StaffHub" cmdlet.

**Comment by lindspea** [comment]
@NigelClarkExient @versatu thank you for reaching out and helping improve MS Docs. Did @versatu's recommendation work?  Would it be helpful to have it added to the article?

**Comment by scanum** [comment]
@NigelClarkExient We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by diorcula** [comment]
> 
> 
> I had the same issue with the AllowPrerelease and I made it work by installing this modules:
> 
> Install-Module -Name PackageManagement -Repository PSGallery -Force
> Install-Module -Name PowerShellGet -Repository PSGallery -Force
> #Then restart shell
> Install-Module -Name MicrosoftStaffHub -AllowPrerelease -Force

This worked for me, but on a completely unrelated issue with PowerLine haha

**Comment by AntaresShao** [comment]
> I have had the StaffHub module installed for a while now and am logged in with a Global Admin account, but am getting "Operation returned an invalid status code 'Forbidden'" when I run "Get-StaffHubTeamsForTenant". I tried the above, to update the module version, but it's not updating either. It's staying at version 1.0.1.

Me **EITHER**!!!
My PowerShell:
```shell
powershell as root | 23:57:18
警告: The version '1.4.7' of module 'PackageManagement' is currently in use.
Retry the operation after closing the applications.
```
So confused! How did you solve this problem?

**Comment by simohauml** [comment]
> 
> 
> > I have had the StaffHub module installed for a while now and am logged in with a Global Admin account, but am getting "Operation returned an invalid status code 'Forbidden'" when I run "Get-StaffHubTeamsForTenant". I tried the above, to update the module version, but it's not updating either. It's staying at version 1.0.1.
> 
> Me **EITHER**!!! My PowerShell:
> 
> ```shell
> powershell as root | 23:57:18
> 警告: The version '1.4.7' of module 'PackageManagement' is currently in use.
> Retry the operation after closing the applications.
> ```
> 
> So confused! How did you solve this problem?

Same problem.

**Comment by j0rt3g4** [comment]
Hello All I think I got a solution for this:
Issue comes with the PowershellGet version

So Open CMD as administrator and run
![image](https://user-images.githubusercontent.com/5489996/142736630-abd0a350-b2fb-4a41-872f-207a186db22b.png)
```Powershell
powershell -noprofile
Uninstall-Module PowershellGet -AllVersions -Force -COnfirm:$false
```

Then:
```Powershell
$PSVersionTable
```
Must be 5.1 minimal (if it's not then update it, and reboot the computer)

```Powershell
Get-module PowershellGet
```
Should be empty after uninstall

```Powershell
Find-module PowershellGet
```
To check the latest version

Finally, Reinstall again
```Powershell
Install-Module PowershellGet -Force
```
Here you'll probably get the error
```
 The version '1.4.7' of module 'PackageManagement' is currently in use.
Retry the operation after closing the applications.
```

This is normal, the point is to make sure you have the latest version you saw in here:
```Powershell
Find-module PowershellGet
Get-module PowershellGet
```


Close and reopen, and run the Get to get the latest version that should enable the allowprerelease now.
```Powershell
Install-Module -Name MicrosoftTems -AllowPrerelease
```
