### ISSUE TITLE
Supported Web Application Proxy Servers

### ISSUE THREAD

**Issue by ablanken** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3101]
Are there any plans to certify the Web Application Proxy role on Windows Server 2016 and/or 2019? The following resource only lists Windows Server 2012 R2:

https://docs.microsoft.com/en-us/skypeforbusiness/certification/infra-rev-proxy
Skype/SfbPartnerCertification/certification/infra-rev-proxy.md

Are there any known issues with running later version WAP servers?

We are currently running SFB2015 which is working fine with our later version WAP servers. We are in the process of migrating to SFB 2019 and have raised a support case as mobility functionality isn't working as expected. The support rep referenced this page and said we need to deploy 2012 R2 servers.

**Comment by ablanken** [comment]
Update - It turns out I ran into a known issue with our WAP 2019 farm which I was able to work around.... Is there a central location where these types of issues are published?

http://uk2us88.com/skype-for-business-wap-2019/

https://social.technet.microsoft.com/Forums/windowsserver/en-US/8ddf1ed4-5278-42c9-a70e-c1c48aa84e8b/web-application-proxy-2019-sharepoint-2016-and-office-online-server-sites-wont-load?forum=ADFS

**Comment by scanum** [comment]
@ablanken Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Hello @ablanken  I'd ask to verify with @scanum  and the author.

Basically there's is not a WAP 2019 troubleshoot page still.

https://blogs.technet.microsoft.com/rmilne/2017/07/19/wap-2016-published-application-not-working-http-error-503/

**Comment by scanum** [comment]
@dougand-MSFT Hi! Could you please help us confirm the following? Thanks.

**Comment by scanum** [comment]
@dougand-MSFT Hi! Could you please help us confirm the following? Thanks.

**Comment by dougand-MSFT** [comment]
The subject mentions web application proxy servers, which is not something I’m involved in.

I found Gayatri Narayan listed as GEM for proxy server in a status report email thread.. @Gayatri Narayan<mailto:Gayatri.Narayan@microsoft.com> can you add someone to this thread that could answer docs related questions about proxy server support for SfB?

**Comment by rjagiewich** [comment]
@v-bhagan-can you advise on how to handle this issue? Thanks!

**Comment by lindspea** [comment]
@gayatri any update on this?

**Comment by scanum** [comment]
@gayatri any update on this?

**Comment by scanum** [comment]
@gayatri any update on this?

**Comment by scanum** [comment]
@gayatri any update on this?

**Comment by lindspea** [comment]
@gayatri

**Comment by tiburd** [comment]
8/25: gayatri is no longer with the company, and Doug does not have any info (per email).
