### ISSUE TITLE
Dead Link:Pricing for Phone System

### ISSUE THREAD

**Issue by VNJoe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3112]
This doesn't take you to phone system.  It takes you to a generic Office 365 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33bc456f-7b95-8779-3970-e3f476a5a4fb
* Version Independent ID: f0549691-87ab-e7d8-d00d-a5169a8cddb7
* Content: [Here's what you get with Phone System in Office 365](https://docs.microsoft.com/en-us/microsoftteams/here-s-what-you-get-with-phone-system#feedback)
* Content Source: [Teams/here-s-what-you-get-with-phone-system.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/here-s-what-you-get-with-phone-system.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@VNJoe Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by VNJoe** [comment]
No, it hasn't.  It takes you to a landing page.  You have to click again, which takes you to an Office Subscription page, and then THAT page doesn't have it on there, either.

But thanks for closing it without checking it, that makes me feel like a valuable customer...
