### ISSUE TITLE
Missing information regarding managing Azure Dynamic Group Teams through the Teams Admin Center

### ISSUE THREAD

**Issue by ebahsadmin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3113]
We have noticed that dynamic user groups belonging to Teams can still be managed through the Teams Admin Center. Is this expected behaviour and if so, will modifying membership within the admin center break anything in Azure?

**Comment by scanum** [comment]
@ebahsadmin thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
