### ISSUE TITLE
Text and missing images

### ISSUE THREAD

**Issue by greganth1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3115]
In the third sentence it would be nice to make https://cqd.teams.microsoft.com a hyperlink that opens in a new tab.
Under Latest Changes and Updates the second sentence doesn't read properly.
There is also and report interactivity to support new scenarios such as:
Under the Drill Through Functionality section the screenshots are not displaying.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb8d8b48-561b-6817-1ce0-4b2aedc261a8
* Version Independent ID: dfd5cf4a-509a-3ed1-0267-6281c251fbef
* Content: [Turn on and use Call Quality Dashboard](https://docs.microsoft.com/en-us/MicrosoftTeams/turning-on-and-using-call-quality-dashboard)
* Content Source: [Teams/turning-on-and-using-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/turning-on-and-using-call-quality-dashboard.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by jambirk** [comment]
This is now resolved
