### ISSUE TITLE
Later Versions

### ISSUE THREAD

**Issue by TobieFysh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3116]
Can the page be updated to state if this is the minimum version that needs to be installed. Or if it is *THE* supported version and moving to a later version will leave you unsupported as per the note "Microsoft reserves the right to reject support cases where a non-certified device is connected to the Phone System via Direct Routing."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1a1c01-10a9-7f69-1c7b-1a566b0f5112
* Version Independent ID: 329ee759-40fc-98fb-b91e-87786c63024b
* Content: [List of Session Border Controllers certified for Direct Routing](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-border-controllers)
* Content Source: [Teams/direct-routing-border-controllers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-border-controllers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@TobieFysh Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Hello @TobieFysh 
I don't think this item would be updated anytime soon but we could ask the author...
@scanum Thank you

**Comment by scanum** [comment]
@TobieFysh Thanks for submitting feedback. We will go ahead and update this in the future.

**Comment by weyCC81** [comment]
@scanum Has there been an update on this documentation (cant find anything in the file history)?

**Comment by TobieFysh** [comment]
@weyCC81 - The line that was added was:
"_Note the certification granted to a major version. That means that firmware with any number in the SBC firmware following the major version is supported._"
Which fulfilled my ask.
