### ISSUE TITLE
TSV/CSV download link

### ISSUE THREAD

**Issue by BSiefferman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3117]
Why not include a link where you can download the tsv/csv file on this page? Instead of having to go to https://docs.microsoft.com/en-US/microsoftteams/learn-more-about-site-upload?WT.mc_id=TeamsAdminCenterCSH to download the file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb8d8b48-561b-6817-1ce0-4b2aedc261a8
* Version Independent ID: dfd5cf4a-509a-3ed1-0267-6281c251fbef
* Content: [Turn on and use Call Quality Dashboard](https://docs.microsoft.com/en-us/microsoftteams/turning-on-and-using-call-quality-dashboard#feedback)
* Content Source: [Teams/turning-on-and-using-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/turning-on-and-using-call-quality-dashboard.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@BSiefferman Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
