### ISSUE TITLE
Need step by step instruction for setting up SfB

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#312]
I need all the step for setting up Skype hybrid with on-prem Skype for Business.
Also need information on what to do to actually establish hybrid connectivity between SfB on-premises   and online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3e9b04c-e93b-7ea5-4ac7-39276428241e
* Version Independent ID: a715ee2f-c518-ffd7-1d2f-3faf264877e9
* Content: [Deploy hybrid connectivity between Skype for Business Server and Skype for Business Online](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-hybrid-solutions/deploy-hybrid-connectivity/deploy-hybrid-connectivity)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/deploy-hybrid-connectivity/deploy-hybrid-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/deploy-hybrid-connectivity/deploy-hybrid-connectivity.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by nsshommo** [comment]
The step by step guide is here: https://lucavitali.wordpress.com/2018/01/31/sfb-sfbo-hybrid-setup-quick-guide/

It is based on: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-hybrid-connectivity.md

Information on "what to do to actually establish hybrid connectivity between SfB on-premises and online" is already in the content under "Plan hybrid connectivity between Skype for Business Server and Skype for Business Online." Link: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-hybrid-connectivity.md

**Comment by nsshommo** [comment]
@AndreaBarr Please let me know if I can put the step by step guide on the content (cmdlet) and submit a PR.

**Comment by kenwith** [comment]
Let's ping @CarolynRowe for advice if she would want this documentation added.

**Comment by kenwith** [comment]
I believe this is already being covered in content that BJ created. Going to close this one out.
