### ISSUE TITLE
Instructions using pictures will be more helpful.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#313]
Its very good and helpful document, however; if screen shot can be attached as per the configuration on server that would be more helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93aec556-e897-9651-55ce-bfee7fd7f021
* Version Independent ID: b411b2f5-49c6-d883-6570-d5526f636a6b
* Content: [Plan for outbound voice routing in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/enterprise-voice-solution/outbound-voice-routing)
* Content Source: [Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/outbound-voice-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/outbound-voice-routing.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.
