### ISSUE TITLE
Needs to include Guests in the behavior matrices

### ISSUE THREAD

**Issue by CorbinMeek** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3130]
We've got some growing customer confusion as exampled in the following case: https://rave.microsoft.com/cases/33e6290b-981f-409a-bcc2-5e0f6e98c2d0 about Guest user expected behavior for Chat and other activity to IslandsMode users in an Interop Scenario.  This document needs to include Guest account behaviors in the matrices, AND, the Guest Access documentation should reference this document for those behaviors.  While we're in there we should include External (Federated) Users, hopefully we can do all of this with release of Native Federation a.k.a. Fed V2.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169a20a6-ebf7-1093-3cb1-fb438b9b7e13
* Version Independent ID: b2074fd8-724e-75fa-bafb-a0f7966bf593
* Content: [Coexistence with Skype for Business](https://docs.microsoft.com/en-us/microsoftteams/coexistence-chat-calls-presence#feedback)
* Content Source: [Teams/coexistence-chat-calls-presence.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/coexistence-chat-calls-presence.md)
* Service: **msteams**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@CorbinMeek - received and I will figure out what we can do to resolve.

**Comment by kenwith** [comment]
Added this to an internal work item @LolaJacobsen has open. Closing this one.
