### ISSUE TITLE
how to open .blog file

### ISSUE THREAD

**Issue by jianwu3** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3137]
I installed MS Teams, but webcam doesn't work. 
%appdata% has MS Teams's media log, but the log file is xxxx.BLOG. 
any reader could open the xxx.BLOG file.
Thanks.

**Comment by dplotnikov** [comment]
@jianwu3 you can open it via regular Notepad in Windows

**Comment by scanum** [comment]
@jianwu3 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
