### ISSUE TITLE
Page update to new admin centre

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3139]
The page needs to be updated with instructions for the new Microsoft 365 Admin centre.
IE: step 2 - In the left navigation of the Microsoft 365 admin center, go to Billing &gt; Subscriptions &gt; Add subscriptions
Should be
Billing &gt; Purchase Services.. etc etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 277cf140-5c6c-82c7-cc56-490ef2188754
* Version Independent ID: 72e7de29-fd71-23bf-15a7-172634c2a5fd
* Content: [Set up Communications Credits for your organization](https://docs.microsoft.com/en-us/microsoftteams/set-up-communications-credits-for-your-organization#feedback)
* Content Source: [Teams/set-up-communications-credits-for-your-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-communications-credits-for-your-organization.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@jantoney Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Solving on PR #3431

**Comment by scanum** [comment]
@jantoney 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
