### ISSUE TITLE
Mostly talk about Lync and SfB, but should be Teams

### ISSUE THREAD

**Issue by aamillerMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3140]
Mostly talk about Lync and SfB, but should be Teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33bc456f-7b95-8779-3970-e3f476a5a4fb
* Version Independent ID: f0549691-87ab-e7d8-d00d-a5169a8cddb7
* Content: [Here's what you get with Phone System in Office 365](https://docs.microsoft.com/en-us/MicrosoftTeams/here-s-what-you-get-with-phone-system)
* Content Source: [Teams/here-s-what-you-get-with-phone-system.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/here-s-what-you-get-with-phone-system.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@aamillerMSFT Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by mschmidtwest** [comment]
Agree... maybe a table showing what's supported in SfB and what's in Teams?

**Comment by aamillerMSFT** [comment]
Since it only applies to online, and SfBO is effectively [EOL](https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/Skype-for-Business-Online-to-Be-Retired-in-2021/ba-p/777833)  I would just make it focused on Teams.

**Comment by j0rt3g4** [comment]
Updates from SfB to Teams #3427

**Comment by j0rt3g4** [comment]
@aamillerMSFT  Focused on Teams mostly, just some of the features or documentation are not there for teams.

**Comment by CarolynRowe** [comment]
Updates to this topic are in progress.  Thanks for the feedback.

**Comment by scanum** [comment]
@CarolynRowe Hi Carolyn, any updates on this? thanks!

**Comment by scanum** [comment]
@CarolynRowe Hi Carolyn, any updates on this? thanks!

**Comment by CarolynRowe** [comment]
This document has been updates and is currently in PM review.  It will go live soon.  Will go ahead and close this issue.
