### ISSUE TITLE
SFB to Teams upgrade- Dialpad, Chat functionality appearance

### ISSUE THREAD

**Issue by tmaheshwar** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3144]
While we migrate a SFB user to Teams with different workloads e.g. Chat, Meeting, enterprise voice, there is no consistent time after which these tabs will appear in Teams client; is there a way to validate how many migration requests are in queue and when same will be executed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues#skype-for-business-to-teams-upgrade)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@tmaheshwar Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
I'd go with the :
```Powershell
Get-CsMeetingMigrationStatus -SummaryOnly
```
https://docs.microsoft.com/skypeforbusiness/audio-conferencing-in-office-365/setting-up-the-meeting-migration-service-mms

##Aditional information:
- https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/move-users-from-on-premises-to-teams
- https://docs.microsoft.com/en-us/microsoftteams/migration-interop-guidance-for-teams-with-skype

**Comment by scanum** [comment]
@tmaheshwar 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
