### ISSUE TITLE
TLS 1.0, 1.1 for Skype for Business server 2019

### ISSUE THREAD

**Issue by Erdem-Oz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3145]
In SFB server 2015 TLS 1.0 and 1.1 is enabled still for the Lync Phone Edition, thus these devices are in extended support still. Is it possible to enable TLS 1.0 in SFB server 2019? Regarding the article it is only TLS 1.3 and TLS 1.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7679160-fb98-6e52-07f3-b844ba979065
* Version Independent ID: a137b9d1-7721-c4ba-b2bd-0122795e80b6
* Content: [Encryption for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/security/encryption)
* Content Source: [Skype/SfbServer/plan-your-deployment/security/encryption.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/security/encryption.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by jambirk** [comment]
@CorbinMeek might be the best person to answer this.

**Comment by CorbinMeek** [comment]
+ @João Loureiro<mailto:joaol@microsoft.com> - @James Birkinshaw<mailto:jambirk@microsoft.com> I am skeptical of that document stating 2019 will only offer 1.3 and 1.2 – but I don’t know for sure, so added Joao who might.  If he does not then we would need to get this in front of Engineering team.

**Comment by CorbinMeek** [comment]
Adding @Hiren Shah<mailto:Hiren.Shah@microsoft.com> and @Ravi Kant Rao<mailto:ravrao@microsoft.com>

I think what was meant with that particular note was that sfb server 2019 would offer tls 1.3 and tls 1.2 prior to 1.1 / 1.0. Not that tls 1.1/1.0 was disabled by default. @Hiren Shah<mailto:Hiren.Shah@microsoft.com> @Ravi Kant Rao<mailto:ravrao@microsoft.com> Please let me know if my understanding is correct.

Regards,
Joao

From: Corbin Meek <corbinm@microsoft.com>
Sent: Thursday, October 3, 2019 17:29
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness <reply@reply.github.com>; MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com>; João Loureiro <joaol@microsoft.com>; James Birkinshaw <jambirk@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] TLS 1.0, 1.1 for Skype for Business server 2019 (#3145)

+ @João Loureiro<mailto:joaol@microsoft.com> - @James Birkinshaw<mailto:jambirk@microsoft.com> I am skeptical of that document stating 2019 will only offer 1.3 and 1.2 - but I don't know for sure, so added Joao who might.  If he does not then we would need to get this in front of Engineering team.

**Comment by Erdem-Oz** [comment]
Any update regarding this issue? 

We have also tested it to enable TLS 1.0, TLS 1,1 on SFB 2019 but the Lync Phone Edition wont connect.

**Comment by j0rt3g4** [comment]
Hello @Erdem-Oz 
Since TLS 1.0 has a lot of years being vulnerable, I don't think it would be possible to go back and allow TLS 1.0 or TLS 1.1 into a server suite from Microsoft in 2019-2020.

https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn786446(v=ws.11)?redirectedfrom=MSDN

I have doubt relative to the TLS 1.3, so @scanum  would you please tag the author to determine if this requires Product Team intervention to get this clear?.

**Comment by Erdem-Oz** [comment]
@j0rt3g4 The problem is that the lync phone editions are still supported. And it works only with TLS 1.0 or there must be an update to support TLS 1.2 / 1.3?

**Comment by CorbinMeek** [comment]
> @j0rt3g4 The problem is that the lync phone editions are still supported. And it works only with TLS 1.0 or there must be an update to support TLS 1.2 / 1.3?

Hi @Erdem-Oz hopefully we can set the record straight here.

First, Lync Phone Edition is **_unsupported_** on Skype for Business Server 2019.  See: https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/clients-and-devices#legacy-clients

So if you have legacy LPE devices you need to maintain for a bit longer as you execute your plan to retire those, you should keep a SfB Server 2015 pool or Std Edition server around.

Second, TLS 1.0 is supported on Skype for Business Server 2019, the documentation doesn't explicitly state this but we can mention that, however, it won't change the supportability stance on LPE.  

Third - it may still work anyway.  Check out [this discussion thread](https://techcommunity.microsoft.com/t5/Skype-for-Business-Server-2019/LPE-Device-Support/m-p/221717).  

We wouldn't recommend it, but if you have to run LPE for a bit longer as you move to modern 3PIP phones or soft phones, you could potentially get away with this.  Just understand that Microsoft Support would not be obligated to assist with troubleshooting connectivity or update problems.  If you maintain a 2015 Pool or SE server to connect LPE to, then sure, fully supported.

Finally - LPE will not be updated to work with higher versions of TLS, this is well established and settled.

Hope this helps you proceed with your implementation plans!

**Comment by j0rt3g4** [comment]
I'd say, that answer solves the issue.

**Comment by scanum** [comment]
@Erdem-Oz 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Erdem-Oz** [comment]
> > @j0rt3g4 The problem is that the lync phone editions are still supported. And it works only with TLS 1.0 or there must be an update to support TLS 1.2 / 1.3?
> 
> Hi @Erdem-Oz hopefully we can set the record straight here.
> 
> First, Lync Phone Edition is **_unsupported_** on Skype for Business Server 2019. See: https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/clients-and-devices#legacy-clients
> 
> So if you have legacy LPE devices you need to maintain for a bit longer as you execute your plan to retire those, you should keep a SfB Server 2015 pool or Std Edition server around.
> 
> Second, TLS 1.0 is supported on Skype for Business Server 2019, the documentation doesn't explicitly state this but we can mention that, however, it won't change the supportability stance on LPE.
> 
> Third - it may still work anyway. Check out [this discussion thread](https://techcommunity.microsoft.com/t5/Skype-for-Business-Server-2019/LPE-Device-Support/m-p/221717).
> 
> We wouldn't recommend it, but if you have to run LPE for a bit longer as you move to modern 3PIP phones or soft phones, you could potentially get away with this. Just understand that Microsoft Support would not be obligated to assist with troubleshooting connectivity or update problems. If you maintain a 2015 Pool or SE server to connect LPE to, then sure, fully supported.
> 
> Finally - LPE will not be updated to work with higher versions of TLS, this is well established and settled.
> 
> Hope this helps you proceed with your implementation plans!

Thank you for answer everything is clear now :)
