### ISSUE TITLE
ADFS

### ISSUE THREAD

**Issue by mbroaders** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3151]
Does this process work when the tenant has ADFS implemented? Setting a password doesn't appear to work for a federated account. We have had to convert the user to managed and back to federated previously to get this to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee417633-3d52-646b-2ef0-94f71535db75
* Version Independent ID: 527bb7f0-b4a7-108c-6f86-8fadced63b86
* Content: [Deploy Microsoft Teams Rooms with Exchange Online](https://docs.microsoft.com/en-us/microsoftteams/room-systems/with-exchange-online#feedback)
* Content Source: [Teams/room-systems/with-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/with-exchange-online.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@mbroaders Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Hello @mbroaders, ADFS is not even mentioned in the article. Either way, I'd add this as a note so the author can double-check about it :)

**Comment by LanaChin** [comment]
@mbroaders, thanks for your input. The article has been updated: https://docs.microsoft.com/en-us/microsoftteams/rooms/with-exchange-online.
