### ISSUE TITLE
Old Sharepoint Admin Portal Referenced

### ISSUE THREAD

**Issue by MySkypeLab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3153]
Step 5 in this page references the settings in the old Sharepoint Admin Portal. The new Sharepoint has a vastly different layout and setting names than this document references. Please update to use the new Sharepoint Portal details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams guest access checklist](https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@MySkypeLab Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Solved on PR #3424

**Comment by LanaChin** [comment]
@MySkypeLab, thanks for your input. The article has been updated to reflect the settings in the new SharePoint admin center. @j0rt3g4, I made some edits and merged your updates. Thank you.

**Comment by j0rt3g4** [comment]
@LanaChin  Thank you!
