### ISSUE TITLE
Leaving a channel

### ISSUE THREAD

**Issue by clisc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3155]
How do I leave, mute, or otherwise ignore a channel?  (This page appears to talk more about teams than about channels.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06059d07-6687-2924-7d0a-3c03220a1650
* Version Independent ID: bb293f92-9394-b156-2e08-0baead5c3bbe
* Content: [Overview of teams and channels in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-channels-overview)
* Content Source: [Teams/teams-channels-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-channels-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@clisc Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Issue solved on PR #3418

**Comment by LolaJacobsen** [comment]
The Teams admin documentation isn't intended to provide end user guidance. To see how to leave, mute, or otherwise ignore a channel, check out https://support.office.com/article/teams-and-channels-df38ae23-8f85-46d3-b071-cb11b9de5499.
