### ISSUE TITLE
Microsoft Teams Rooms Licensing Link

### ISSUE THREAD

**Issue by greenchevy65** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3158]
Microsoft Teams Rooms Licensing Link in the See Also section is still broken.  There had been previous feedback but it was closed.  So, either it wasn't fixed or it is broken again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Office 365](https://docs.microsoft.com/en-us/microsoftteams/room-systems/with-office-365#feedback)
* Content Source: [Teams/room-systems/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/with-office-365.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@greenchevy65  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jambirk** [comment]
@LanaChin this looks like another rebranding impact should point to file currently at https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/skype-room-systems-v2 which presumably will need to be renamed.

**Comment by LanaChin** [comment]
@scanum - the link should point to https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/skype-room-systems-v2.

**Comment by scanum** [comment]
@LanaChin Thanks!

**Comment by LanaChin** [comment]
Merged updates by @j0rt3g4.
