### ISSUE TITLE
Broken link goes to 404

### ISSUE THREAD

**Issue by j0rt3g4** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3159]
on https://docs.microsoft.com/en-us/microsoftteams/room-systems/skype-room-systems-v2#feedback "Country and region availability for Audio Conferencing and Calling Plans" there's a broken link

https://docs.microsoft.com/en-us/microsoftteams/room-systems/skype-room-systems-v2.md

Document Details
⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

Content:[skype-room-systems-v2](https://docs.microsoft.com/en-us/microsoftteams/room-systems/skype-room-systems-v2)
Content Source: Teams/room-systems/skype-room-systems-v2.md
Service: msteams
GitHub Login: @LanaChin
Microsoft Alias: v-lanac

**Comment by j0rt3g4** [comment]
@scanum Found this one today while working on Support.

**Comment by j0rt3g4** [comment]
PR #3162

**Comment by jambirk** [comment]
@LanaChin is this an artifact of your rebranding work?

**Comment by jambirk** [comment]
closing as this appears to have been filed in error

**Comment by LanaChin** [comment]
I've tested the link and it works.

**Comment by j0rt3g4** [comment]
Hi @LanaChin  @jambirk 
The link works correctly when you're in the US or using an English location.

The link is broken for Latin or Spanish locations...
I'm talking to @kenwith about it on our MS teams of our team.

It's a weird issue because it works correctly for English languages, but when comes into Spanish...
![image](https://user-images.githubusercontent.com/5489996/66368187-e339f480-e95c-11e9-878e-73cf6122141c.png)
