### ISSUE TITLE
Need to fix figure or link of figure.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#316]
"The following figures show a dual stack configuration for the internal interface and the external interface." - There are no figure or link to figure is found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a8b25c0-a81d-44e1-e0fb-b5f2ac6e1f66
* Version Independent ID: 202330a0-4da0-c1c2-8241-c85ebc6d7b52
* Content: [Configure IP address types in Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/network-requirements/ip-address-types)
* Content Source: [Skype/SfbServer/plan-your-deployment/network-requirements/ip-address-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/network-requirements/ip-address-types.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
removing the reference to the figures, and their captions.
