### ISSUE TITLE
Dead link - "USB Devices Certified for Skype for Business"

### ISSUE THREAD

**Issue by SCS-sysadmin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3160]
Please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583a3231-1a39-bc08-d36f-30b902ea6355
* Version Independent ID: 979504c3-f963-90c7-003c-457dcf6248c1
* Content: [Plan users' experience of Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/5-envision-plan-my-users-experience)
* Content Source: [Teams/5-envision-plan-my-users-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/5-envision-plan-my-users-experience.md)
* Service: **msteams**
* GitHub Login: @rmw2890
* Microsoft Alias: **Rowille**

**Comment by scanum** [comment]
@SCS-sysadmin  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Issue fixed on PR #3419

**Comment by scanum** [comment]
@SCS-sysadmin Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
