### ISSUE TITLE
Port orders

### ISSUE THREAD

**Issue by Yoeeee** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3163]
Port orders are no longer available in legacy admin portal.

Is there any other way to integrate tot transfer your phone numbers to Teams

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1829a37-a7a1-4dd1-fde8-82125c593ff1
* Version Independent ID: dfedc4c5-eec4-2137-e975-399866aaafad
* Content: [Transfer phone numbers to Office 365](https://docs.microsoft.com/en-us/microsoftteams/transfer-phone-numbers-to-office-365#feedback)
* Content Source: [Teams/transfer-phone-numbers-to-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/transfer-phone-numbers-to-office-365.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Yoeeee  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
@scanum  Please verify this content with the author, I'm not really sure if ports are required for this one.

**Comment by scanum** [comment]
@CarolynRowe Hi Carolyn, could you please help us out on next steps for this issue's resolution? Thanks!

**Comment by scanum** [comment]
@CarolynRowe Hi Carolyn, could you please help us out on next steps for this issue's resolution? Thanks!

**Comment by CarolynRowe** [comment]
Hello,
Is there a reason you cannot use the Teams admin center?

**Comment by CarolynRowe** [comment]
Please see the instructions in the topic:  https://docs.microsoft.com/en-us/MicrosoftTeams/phone-number-calling-plans/transfer-phone-numbers-to-teams.

Fill out an LOA for the country/region and for the type of numbers you are looking for. From this page select the country, then download, fill out and send in the PDF to the PSTN service desk.

https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization/manage-phone-numbers-for-your-organization

Optionally, use this topic: https://docs.microsoft.com/en-us/microsoftteams/phone-number-calling-plans/manually-submit-port-order

Closing this issue for now.
