### ISSUE TITLE
Read receipts is not available

### ISSUE THREAD

**Issue by stokara** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3165]
Based on this documentation from June 2019, I was led to believe that receipts were either released or would be so imminently; however, read receipts are still on the roadmap as in development with a (twice updated) target of 3Q 2019. We are now in 4Q 2019 and it still is not functional!   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb00b844-c949-c5a7-a56f-65301afe4186
* Version Independent ID: 9f400d96-70ac-0233-4bf0-43e10b9081c3
* Content: [Get started with Secure Messaging for Healthcare organizations](https://docs.microsoft.com/en-us/MicrosoftTeams/expand-teams-across-your-org/healthcare/messaging-policies-hc)
* Content Source: [Teams/expand-teams-across-your-org/healthcare/messaging-policies-hc.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/expand-teams-across-your-org/healthcare/messaging-policies-hc.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@stokara Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Hello, @stokara Basically that's something that you can complain about on a support ticket.

You can see the progress here:
https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=In%20development

**Comment by scanum** [comment]
@stokara Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
