### ISSUE TITLE
Change Kollective URL

### ISSUE THREAD

**Issue by arianasexton** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3167]
Hello - Can we change the Kollective link in the last sentence of this page to go to this page: https://kollective.com/microsoft-pilot/ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5372edb-6ffe-34a3-0839-587e48f66f6b
* Version Independent ID: 43903b13-37de-7dde-5b8c-739586cc2d87
* Content: [Microsoft Teams live event usage report](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-live-event-usage-report)
* Content Source: [Teams/teams-analytics-and-reports/teams-live-event-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-live-event-usage-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@arianasexton Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@arianasexton thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
