### ISSUE TITLE
Change the Kollective Link

### ISSUE THREAD

**Issue by arianasexton** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3168]
Hello - can we change the link to Kollective to go to this page: https://kollective.com/microsoft-pilot/

Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: becbf3ca-b88c-b033-a145-9a1af201ced3
* Version Independent ID: 41a6a9b5-d3dd-d8c9-9e97-920ff2fd1a24
* Content: [What are Microsoft Teams live events?](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/what-are-teams-live-events)
* Content Source: [Teams/teams-live-events/what-are-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/what-are-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@arianasexton thank you for submitting feedback.

We will change the specified link.

**Comment by scanum** [comment]
@arianasexton 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
