### ISSUE TITLE
Need to know minimum disk space required for installing SfB.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#317]
Can anyone help me to find the minimum amount of disk space required to install Skype for Business 2016 on client system? Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2369c8dd-2f4d-e2c2-e7fa-745466cb3455
* Version Independent ID: 90e0764d-de05-254c-d32d-a9522df6b49a
* Content: [Skype for Business compatibility with Office apps](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/compatibility-with-office)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/compatibility-with-office.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/compatibility-with-office.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.
