### ISSUE TITLE
New Feature vs current docs

### ISSUE THREAD

**Issue by D-Jeffrey** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3170]
Related to MC189163 / Roadmap ID 54235 (from 365 admin message center)

With the message it states "Tenants that do not have PSTN-calling enabled will have access to a sub-set of features, which includes transferring a call to Cloud Voicemail."
That is in contrast to the "Note - Enterprise Voice enable requirement" on this this.
How do those features compare between Enterprise voice enable and not PSTN-calling enabled?  And what is the difference between PSTN-calling enabled and Enterprise voice enabled?

Additionally is this Cloud Voicemail the same as Team Cloud Voicemail (https://docs.microsoft.com/en-us/microsoftteams/set-up-phone-system-voicemail)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec8b8afb-b9ca-8136-b907-5bbff4c9dcf1
* Version Independent ID: d4f68818-6fe6-5bb7-f108-e26a643f2cc7
* Content: [Configure Cloud Voicemail service for on-premises users](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/configure-cloud-voicemail)
* Content Source: [Skype/SfbHybrid/hybrid/configure-cloud-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-cloud-voicemail.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@D-Jeffrey Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@D-Jeffrey thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
