### ISSUE TITLE
Create custom teams templates

### ISSUE THREAD

**Issue by NickSevens** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3171]
Is it, or will it be, possible to create custom templates with your own apps and tab definitions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d884cb-c126-b5dc-ff90-1a31aa61bf5b
* Version Independent ID: ed5054d7-d679-7fad-fd5d-9cd393644b9d
* Content: [Get started with Teams templates](https://docs.microsoft.com/en-us/MicrosoftTeams/get-started-with-teams-templates#feedback)
* Content Source: [Teams/get-started-with-teams-templates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-started-with-teams-templates.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@NickSevens thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
