### ISSUE TITLE
No specifications of addresses or ports

### ISSUE THREAD

**Issue by donlassini** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3172]
This article should mention the relevant FQDNs or IPs that should be exempted from proxy use.
Or at least there should be a link to another article where said documentation could be found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 826084d1-06f7-e837-bcfc-d86d427288f6
* Version Independent ID: 9b36168e-d398-0188-c510-4dc5dd5f9563
* Content: [Proxy servers for Teams or Skype for Business Online](https://docs.microsoft.com/en-us/microsoftteams/proxy-servers-for-skype-for-business-online#feedback)
* Content Source: [Teams/proxy-servers-for-skype-for-business-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/proxy-servers-for-skype-for-business-online.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@donlassini Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@donlassini Thank you for reaching out and helping improve MS Docs.  I'll investigate to find the link. In the meantime if you have found the correct link please let me know and I'll have it added.

**Comment by lindspea** [comment]
@donlassini please have a look at this link and let me know if it helps. https://docs.microsoft.com/microsoftteams/office-365-urls-ip-address-ranges#

**Comment by sunzoom** [comment]
Hi ,

Can anybody tell me?

Where is the proxy settings configured for teams? I have an issue in which there's no setting configured in the IE connections but teams is prompting for proxy authentication to a PAC file which we were testing. I can't seem to find it in registry of appdata > teams. Is it in a DB format?

**Comment by lindspea** [comment]
Hi @sunzoom. See this link.  Let me know if it helps. https://techcommunity.microsoft.com/t5/Office-365/MS-Teams-App-and-Video-Proxy/m-p/310259

**Comment by scanum** [comment]
@donlassini 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
