### ISSUE TITLE
Teams Galery empty by default

### ISSUE THREAD

**Issue by mathieuremy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3173]
How could i view all the public teams (and discoverable private ones) in the Teams Galery by default? I get only 2 tiles : create a new team or join with a code (meanwhile we have plenty of registered plublic teams...)

Workaround : how could i search for any team using the team's serach engine? (* or % not working)

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: fd13cd2b-3dca-1b7c-9970-c0f8c2348712
* Version Independent ID: 318c6208-531a-3600-e45b-c43ea845db86
* Content: [Gérer les stratégies d’équipes dans Microsoft teams](https://docs.microsoft.com/fr-fr/microsoftteams/teams-policies#feedback)
* Content Source: [Teams/teams-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@mathieuremy Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@mathieuremy Thank you for reaching out.  It seems the article might have been updated in the interim. The article mentions the following:
"Choose the settings that you want:
Discover private teams: Turn on this setting to allow users to discover private teams in search results and in the team gallery.
Create private channels: Turn on this setting to allow users to create private channels.
Click Save."
Let me know if this helps or if you need further assistance.

**Comment by scanum** [comment]
@mathieuremy 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
