### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by rogermicrosoft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3174]
I am trying to download the Planning Tool https://go.microsoft.com/fwlink/p/?LinkID=282725 but the link does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 488d7d17-8fcd-bf2a-0209-6ff599e04efd
* Version Independent ID: 451f45f8-26a3-7915-6cb6-737e531c7808
* Content: [Skype for Business Server 2015 Planning Tool](https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/planning-tool/planning-tool#feedback)
* Content Source: [Skype/SfbServer/management-tools/planning-tool/planning-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/management-tools/planning-tool/planning-tool.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@rogermicrosoft Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LanaChin** [comment]
Thanks for bringing this to our attention. The link is now fixed.
