### ISSUE TITLE
Need connectivity diagram.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#318]
Hard to map services. End to end connectivity diagram would be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 385809f9-3db5-23d4-bd86-2811da8410b0
* Version Independent ID: 396d1631-1fcf-2775-b9e3-2ecad7e3a0cc
* Content: [Load balancing requirements for Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/network-requirements/load-balancing)
* Content Source: [Skype/SfbServer/plan-your-deployment/network-requirements/load-balancing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/network-requirements/load-balancing.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
We could add a copy of the diagram used in the DNS planning article.

**Comment by nsshommo** [comment]
Thanks. Please reply here when diagram is added.
