### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by tmaheshwar** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3180]
How files will come in "downloads" option

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ade1a4-092c-1132-44df-ee2c683fdd33
* Version Independent ID: 396b1aee-2f40-9895-9b00-07e38d11d31b
* Content: [Microsoft Teams analytics and reporting](https://docs.microsoft.com/en-US/microsoftteams/teams-analytics-and-reports/teams-reporting-reference?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@tmaheshwar Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@tmaheshwar thank you for reaching out. Just to clarify, are you asking how to download a file on MS Teams? Here is a link for that - https://support.office.com/article/download-a-file-from-teams-c55bc870-7419-4d18-acdd-dc102d6d2b4a.  Let me know if this helps.

**Comment by tmaheshwar** [comment]
Hi,

My query is to download PSTN reports files directly from download option available in Teams Admin Portal
Please address same

Best Regards
Maheshwar Tayal

**Comment by lindspea** [comment]
@tmaheshwar thank you for clearing that up.  Here is an article that should help - https://docs.microsoft.com/skypeforbusiness/skype-for-business-online-reporting/pstn-usage-report

**Comment by tmaheshwar** [comment]
Thanks!
Link you had referred to me is for old SFB portal
My ask is for New TEAMS Admin center PSTN reports export

Best Regards
Maheshwar Tayal

**Comment by lindspea** [comment]
@tmaheshwar for my investigation it seems the option to export/download the report is not yet available.  You can explore https://docs.microsoft.com/graph/reportroot-concept-overview if that suits your needs.

**Comment by scanum** [comment]
@tmaheshwar 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
