### ISSUE TITLE
Table rendering for above table is broken

### ISSUE THREAD

**Issue by scottamoore1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3182]
The rendering for the table above is broken in both Firefox and Chrome.  Not readable.  Please QA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 218ba0df-815a-d0fd-ecdd-228e62e34429
* Version Independent ID: a33def62-a717-67e3-bda9-76b838ec7370
* Content: [Skype for Business Certification Program - Session Border Controllers](https://docs.microsoft.com/en-us/skypeforbusiness/certification/infra-sbc#feedback)
* Content Source: [Skype/SfbPartnerCertification/certification/infra-sbc.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbPartnerCertification/certification/infra-sbc.md)
* Service: **skype-for-business-online**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
converted HTML table to full markdown, doing QA on result

**Comment by jambirk** [comment]
I have a fix for this ready. Due to scheduling issues it may not be ready to publish until 10/14.
