### ISSUE TITLE
Document is not updated

### ISSUE THREAD

**Issue by LeoW-MS** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3184]
Page content is out of date again. There are updates through October 2019 that are missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc1999a1-66c4-1236-54e5-6491c8b70c1c
* Version Independent ID: 8b423b6d-793b-52ee-0031-1f80ea453a3c
* Content: [Latest updates for versions of Skype for Business that use Windows Installer (MSI)](https://docs.microsoft.com/en-us/skypeforbusiness/sfb-client-updates)
* Content Source: [Skype/SfbServer/sfb-client-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/sfb-client-updates.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @PhillipGarding
* Microsoft Alias: **phillipg**

**Comment by scanum** [comment]
@LeoW-MS Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Hello @LeoW-MS  Can you be a little more specifics in what changes are you reporting?

Thank you

**Comment by LeoW-MS** [comment]
Jose,
A customer landing on this page<https://docs.microsoft.com/en-us/skypeforbusiness/sfb-client-updates> will see the title  “Latest updates for versions of Skype for Business that use Windows Installer (MSI)”  and see the date (currently 09/05/2019)

If you look at the section titled “Skype for Business client updates”, it appears to the customer that the June 2019 update  KB (4464576) is the latest available for Skype for Business 2016.

However, since June, there have been three other updates for Skype for Business 2016, which are not included in the page:


  *   October 1, 2019, update for Skype for Business 2016 (KB4484102)
  *   September 3, 2019, update for Skype for Business 2016 (KB4475577)
  *   August 6, 2019, update for Skype for Business 2016 (KB4475548)

I haven’t checked the other updates but they appear not to be current either.

The document needs to be kept up to date with the latest updates or be modified to remove the indication that that is the latest information available as this is leading to customer confusion.



[cid:image002.jpg@01D58440.4FDF3820]


Thanks,

Leonard.

**Comment by j0rt3g4** [comment]
#Solving isue #3232

**Comment by scanum** [comment]
@LeoW-MS Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
