### ISSUE TITLE
Microsoft Teams Connectors giving 503 - Something went wrong :'( 

### ISSUE THREAD

**Issue by apatils** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3186]
I am getting this error when I am trying to add new connector in Microsoft teams, also my pre-configured Incoming Webhooks are not working. 
<img width="594" alt="connector_issue" src="https://user-images.githubusercontent.com/41283108/66542619-ba7a5080-eb50-11e9-91e7-0bcd6920ff86.PNG">

**Comment by scanum** [comment]
@apatils 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content
