### ISSUE TITLE
Perhaps some updates needed?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3188]
You wrote on the page:
"_As the additional coexistence modes, (i.e. Skype for Business with Teams collaboration and Skype for Business with Teams collaboration and meetings), are **become progressively fully available in the next few months**,_"

This seems to be available already. So perhaps that need some updates...?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 006dc464-2228-0d91-8726-223770c91411
* Version Independent ID: 28877a22-b558-4da6-551b-9bcd9bac96c4
* Content: [Microsoft Teams upgrade from Skype for Business](https://docs.microsoft.com/en-us/microsoftteams/upgrade-and-coexistence-of-skypeforbusiness-and-teams)
* Content Source: [Teams/upgrade-and-coexistence-of-skypeforbusiness-and-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-and-coexistence-of-skypeforbusiness-and-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Petri-X The author is doing a full rewrite of this article. Thanks for your feedback.
