### ISSUE TITLE
Need description/explanation of listed items.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#319]
More detailed description/explanation of items would be very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33008873-3b6c-0698-87b6-269d2de59292
* Version Independent ID: 7dfc9673-e083-5c20-1c25-3aae7c64a8d1
* Content: [UserAgentDef table](https://docs.microsoft.com/en-us/skypeforbusiness/schema-reference/call-detail-recording-cdr-database-schema/useragentdef)
* Content Source: [Skype/SfbServer/schema-reference/call-detail-recording-cdr-database-schema/useragentdef.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/schema-reference/call-detail-recording-cdr-database-schema/useragentdef.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by jambirk** [comment]
Can't perform an update based on this comment.
