### ISSUE TITLE
Please clearly describe what "Device switching" does, and how it is used.

### ISSUE THREAD

**Issue by liliang-ms** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3191]
Not sure how it is feature used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33bc456f-7b95-8779-3970-e3f476a5a4fb
* Version Independent ID: f0549691-87ab-e7d8-d00d-a5169a8cddb7
* Content: [Here's what you get with Phone System in Office 365](https://docs.microsoft.com/en-us/MicrosoftTeams/here-s-what-you-get-with-phone-system#feedback)
* Content Source: [Teams/here-s-what-you-get-with-phone-system.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/here-s-what-you-get-with-phone-system.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@liliang-ms Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
The definition of device switching is explained with these devices on the following video:

https://www.youtube.com/watch?v=5VBRa4s1hVM

**Comment by scanum** [comment]
@liliang-ms Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
