### ISSUE TITLE
Clarification of Guest Licensing FAQ Answer

### ISSUE THREAD

**Issue by yeag** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3192]
FAQ: How many guests can I invite?  Answer provided: You can add up to 5 guests per licensed user.

The 1:5 licensing ratio as I understand it is based on guests accessing paid Azure AD services.  Reference:  https://docs.microsoft.com/en-us/azure/active-directory/b2b/licensing-guidance

Does adding a guest to a Team require access to paid Azure AD services?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [What the guest experience is like](https://docs.microsoft.com/en-us/microsoftteams/guest-experience#feedback)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@yeag Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Hello @yeag 

The relation is 1:5.
So each user you provide on O365, in the background it's provided on Azure AD.
For this reason, each license you provide on the O365 portal, in the background is being provisioned on Azure AD.

So the relation on a license of office 365 and "azure AD" it's the same thing in the background. 
So the relation 1:5 remains 
1 User licensed or in Azure AD with the valid license: 5 guess access

**Comment by scanum** [comment]
@yeag Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
