### ISSUE TITLE
What is the difference between the 3rd and 4th issue of Client issue on Symlink or mapping a drive ?

### ISSUE THREAD

**Issue by liyunjun** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3193]
Are the two issues the same issue? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues#feedback)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by liyunjun** [comment]
The 3rd item in Client issue is the mixture of the 2nd and 4th item. You should remove the 3rd item in Client issue.

**Comment by scanum** [comment]
@liyunjun Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
HI @liyunjun 

The cases are different.

On the 3rd the installation is done by "installation scripts", and you can have a typo on them or have been moved the default location of the teams' folder. What this specific issue means is that basically the solution is to make sure you don't have any errors or typos or have moved to any particular location other than *"C:\Users\jorte\AppData"*

On the 4th case, you installed teams using regular O365 installation or standalone, or just changed the default route of the software which is given already *"C:\Users\jorte\AppData"*. So basically do not change the default installation path of teams and that will solve both.

So the difference is how Microsoft teams is installed on the computer.

**Comment by scanum** [comment]
@liyunjun Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
