### ISSUE TITLE
Mistranslated are in some items in Japanese. 

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3194]
The following items are mistranslated.

![image](https://user-images.githubusercontent.com/13634805/66620052-16f57280-ec1a-11e9-884c-30dbc6fb991b.png)

![image](https://user-images.githubusercontent.com/13634805/66620069-22489e00-ec1a-11e9-8422-1ecf00d9e8fa.png)

**The actual values are:**

・Guests => ゲスト
・Type => 種類

![image](https://user-images.githubusercontent.com/13634805/66620159-75225580-ec1a-11e9-92a0-60276a116ee4.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3c93d512-6e5a-09c7-1c9f-c7eeb94555da
* Version Independent ID: f289f914-6b58-6c29-8997-a2fbd017ffe7
* Content: [Teams でのチーム間およびチームごとの分析の表示](https://docs.microsoft.com/ja-jp/microsoftteams/teams-analytics-and-reports/cross-team-per-team-analytics#feedback)
* Content Source: [Teams/teams-analytics-and-reports/cross-team-per-team-analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/cross-team-per-team-analytics.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officeglobal Hi Could you please aid with the following? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@kefujino , @scanum article was HumanTranslated and published live

**Comment by kefujino** [comment]
Thank you!
Perfect!

**Comment by scanum** [comment]
@kefujino Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
