### ISSUE TITLE
Powershell linked but no commands found

### ISSUE THREAD

**Issue by JohanssonMarkus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3195]
For the section "Make changes to the email messages that are sent to them" it links to the powershell ref for teams but none of the commands allow you to change the from address.
This is not solved, please add details on how to configure this feature. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0cd207e-eec4-11a5-9037-5d72a9ad5044
* Version Independent ID: b3757462-ceca-36ab-1b7a-8568a7481743
* Content: [Emails sent to users when their settings change in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/emails-sent-to-users-when-their-settings-change-in-teams#feedback)
* Content Source: [Teams/emails-sent-to-users-when-their-settings-change-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/emails-sent-to-users-when-their-settings-change-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@JohanssonMarkus Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Hi @JohanssonMarkus 
What it's said is that you can change the "Display Name" not the "from" address, which cannot be changed.

**Comment by JohanssonMarkus** [comment]
@j0rt3g4  Ok I see. little confusing though. 
I guess it would be better to link direct to [cmdlet](https://docs.microsoft.com/sv-se/powershell/module/teams/Set-TeamMessagingSettings?view=teams-ps)? 

And you are saying that this cmdlet will be updated with new features as it seems it is depricated?

**Comment by j0rt3g4** [comment]
**I guess it would be better to link directly to cmdlet?**

_Well, sadly, it's brand new, and it's not even on the module just yet, it will be in the future._

**And you are saying that this cmdlet will be updated with new features as it seems it is deprecated?**

_Not it just doesn't exist right now. So it's not depreciated is just doesn't exist just yet; it will be available soon when the module is fully developed. Right now is not developed, so the documentation template is there for all the cmdlets in the module, but they are on development._

**Comment by scanum** [comment]
@JohanssonMarkus Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
