### ISSUE TITLE
No information on updates for phone devices

### ISSUE THREAD

**Issue by pracsol** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3196]
Teams documentation is treating the certified phones (Yealink T58A, etc) like forgotten step-children. What is the update cycle for these devices? They've been so neglected - we still don't have a speed dial to display on the phone, no sidecar support: basic features of the 3PIP SFB phones these devices are meant to displace. How about a timeline for next app update for phone devices?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6da28da-eb7b-d3ae-4c2f-8f87803b1830
* Version Independent ID: 8c42d7a2-80c6-86dd-347a-ed6d8d909c41
* Content: [Teams updates](https://docs.microsoft.com/en-us/microsoftteams/teams-client-update#feedback)
* Content Source: [Teams/teams-client-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-client-update.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@pracsol Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Hello @pracsol  

We are a documenting team, we are not involved directly or indirectly on updates.

Please fill up a formal requirement to the engineering team on the user's voice
https://microsoftteams.uservoice.com/

If they have been so neglected as you mentioned, for sure, somebody else has filled up a ticket on this. So my recommendation is to create a petition and ask the people on your company to fill it up so they can have some votes to get any sort of priority on this.

The roadmap of the O365 updates can be seen here:
http://www.roadmapwatch.com/
and search it here: http://roadmap.office.com/

**Comment by pracsol** [comment]
My note was specifically about the documentation not being detailed enough. I understand feature requests go elsewhere, which is why I provided my feedback on the documentation to you.

Sent from my iPhone

On Oct 16, 2019, at 7:19 PM, Jose Gabriel Ortega Castro <notifications@github.com> wrote:

﻿

Hello @pracsol<https://github.com/pracsol>

We are a documenting team, we are not involved directly or indirectly on updates.

Please fill up a formal requirement to the engineering team on the user's voice
https://microsoftteams.uservoice.com/

If they have been so neglected as you mentioned, for sure, somebody else has filled up a ticket on this. So my recommendation is to create a petition and ask the people on your company to fill it up so they can have some votes to get any sort of priority on this.

The roadmap of the O365 updates can be seen here:
http://www.roadmapwatch.com/
and search it here: http://roadmap.office.com/

**Comment by j0rt3g4** [comment]
Alright, let's make another couple of eyes to see the specifics of your request.
@scanum  Could you please tag the authors and help me with some insights about the @pracsol requests?. Thank you in advantage.

**Comment by scanum** [comment]
@LolaJacobsen Hi Lola! Could you please aid on next steps? Thanks

**Comment by joturans** [comment]
I would also like some documentation on how devices which run Andriod version of Teams, such as a Poly Trio recvie client updates. There is no user facing app store like an Andriod mobile device.

**Comment by scanum** [comment]
@LolaJacobsen Following up on this issue. Thanks!

**Comment by GiantCrocodile** [comment]
An update on this regarding Android devices in general would be nice. Thank you!

**Comment by scanum** [comment]
@LolaJacobsen Following up on this issue. Thanks!

**Comment by LolaJacobsen** [comment]
reassigned to @dstrome

**Comment by scanum** [comment]
@dstrome Wondering if there is an update on this issue? Thanks!

**Comment by dstrome** [comment]
hi all,

A list of certified phones for Teams is located here - https://docs.microsoft.com/en-us/MicrosoftTeams/teams-ip-phones

A list of supported features on certified phones is located here - https://docs.microsoft.com/en-us/MicrosoftTeams/phones-for-teams

Please contact the device manufacturer for information about their update cadence.

If the above topics are lacking information you're looking for, please open a comment on one or both of them with specific examples of what you'd like to see. 

thanks!
