### ISSUE TITLE
Search is now called Search by name

### ISSUE THREAD

**Issue by Kmemenza** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3197]
Hello! Just a small edit - the Search section is now called Search by name. It may also be beneficial to let users know that this change can take up to 24 hours to replicate. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84066c98-38a4-e59a-893f-da38a4a11bf3
* Version Independent ID: 890a4978-0e9b-2691-a2ab-8b5512e5e76f
* Content: [Use Microsoft Teams scoped directory search](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-scoped-directory-search#feedback)
* Content Source: [Teams/teams-scoped-directory-search.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-scoped-directory-search.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Kmemenza Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Kressmark** [comment]
Also, "Scope directory search in Teams using an Exchange address book policy (ABP)" is shortened to "Scope directory search using an Exchange address book policy".

**Comment by j0rt3g4** [comment]
@Kressmark create a new issue for it and let us know

**Comment by scanum** [comment]
@Kmemenza 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
