### ISSUE TITLE
Include Enable-CsOnlineSessionForReconnection to mitigate PS session timeout issue

### ISSUE THREAD

**Issue by ndambrosio** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3198]
By default, the PS session times out after an hour, and you have to close and launch a new PS session to reconnect. 

There is a new function in the Skype Online PowerShell module called Enable-CsOnlineSessionForReconnection that can be used to mitigate the timeout issue.  The PS session will reconnect and authenticate, allowing it to be reused without having to launch a new instance to reconnect.  
 
We published the newest version of the Skype Online Powershell module (below) for administering Skype for Business Online as well as Skype for Business Server for hybrid administration.  

**Skype for Business Online, Windows PowerShell Module** (2046.123 - Published 10/2/2019)
[https://www.microsoft.com/en-us/download/details.aspx?id=39366](https://www.microsoft.com/en-us/download/details.aspx?id=39366)

Can we get this incorporated into this document?  It may also make sense to add it to the PowerShell repo as well.

https://github.com/MicrosoftDocs/office-docs-powershell

Let me know if you have any questions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 332f86e2-a5d4-e2fd-3001-73ba9cb7e591
* Version Independent ID: c03f7691-b2d9-b68a-dc96-bf91c16362bb
* Content: [Diagnose connection problems with the Skype for Business Online Connector](https://docs.microsoft.com/en-us/skypeforbusiness/set-up-your-computer-for-windows-powershell/diagnose-problems-with-the-skype-for-business-online-connector)
* Content Source: [Skype/SfbOnline/set-up-your-computer-for-windows-powershell/diagnose-problems-with-the-skype-for-business-online-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-your-computer-for-windows-powershell/diagnose-problems-with-the-skype-for-business-online-connector.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@ndambrosio Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Hello @ndambrosio 
I've added the important note in PR #3234 
Please create the new issue on the Powershell Repository as well.

@scanum Please help me follow up this to do the transition to the Powershell Gallery smoothy

**Comment by scanum** [comment]
@ndambrosio Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
