### ISSUE TITLE
Delays with picking up calls from a call queue

### ISSUE THREAD

**Issue by itthing** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3199]
This documentation should include information about the delay between accepting a call and when a call is actually connected when a call queue is involved.  We are typically seeing delays of several seconds when able to answer a call.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e94dd85e-2ca7-23a6-90be-022ef5e08915
* Version Independent ID: 59cd2a22-f1bb-0702-149a-f672e7878d71
* Content: [Answer auto attendant and call queue calls directly from Teams](https://docs.microsoft.com/en-us/microsoftteams/answer-auto-attendant-and-call-queue-calls)
* Content Source: [Teams/answer-auto-attendant-and-call-queue-calls.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/answer-auto-attendant-and-call-queue-calls.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@itthing Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@itthing thank you for reaching out and helping improve MS Docs.  I'll investigate with the team. In the meantime is there anything you could suggest adding to the article to make it clearer for other users?

**Comment by prohand** [comment]
I have a same problem with SFB2019 CU1.

**Comment by scanum** [comment]
@itthing We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
