### ISSUE TITLE
Need to update with more detailed information.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#320]
This guide only mentions installing the RTM client. It do not tell anything about deploying a fully updated client, i.e. embedding MSP files into the update folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3814804c-1dfc-06f0-a4f4-8a03f65379de
* Version Independent ID: 1ffd80ba-b6f2-ae27-0146-6dda75321054
* Content: [Customize Windows client installation in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/customize-windows-client-installation)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/customize-windows-client-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/customize-windows-client-installation.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by jambirk** [comment]
This seems to be out of scope for the article, you'd deploy an installer and update along with other O365 updates.
