### ISSUE TITLE
 lync 2010 cu 18 download link 404

### ISSUE THREAD

**Issue by kongqi0** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3202]
cannot download lync 2010 cu 18 https://support.microsoft.com/en-sg/help/2493736/updates-for-lync-server-2010 ,the download page is 404

**Comment by scanum** [comment]
@kongqi0 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
