### ISSUE TITLE
Not able to download Video TMT 2.1 for Skype - download link is invalid

### ISSUE THREAD

**Issue by dsureshmadhu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3203]
Hi, 

I tried to download Video TMT 2.1 for Skype tool. But the download link given on the below page is not valid anymore. Can you point where to download the tool?

https://docs.microsoft.com/en-us/skypeforbusiness/certification/test-spec

Thanks for your help. 

Regards
Suresh

**Comment by scanum** [comment]
@dsureshmadhu Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jambirk** [comment]
The link should be working now, please re-open if this isn't the case for you.

**Comment by dsureshmadhu** [comment]
The link is working now..
Thanks!!

Regards
Suresh
