### ISSUE TITLE
Giphy

### ISSUE THREAD

**Issue by Everett42** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3206]
It does not appear changing the Giphy content rating does anything.  According the documentations above:

    No restriction This means that your users will be able to insert any Giphy in chats regardless of the content rating.

Our teams has been set to "no restriction" for weeks, but the available gifs are greatly restricted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34f3188-0af5-f972-9d28-959f5f7866a2
* Version Independent ID: fab26e11-a729-92a4-3ea6-8668dca55dd0
* Content: [Manage messaging policies in Teams](https://docs.microsoft.com/en-us/microsoftteams/messaging-policies-in-teams#feedback)
* Content Source: [Teams/messaging-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/messaging-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@Everett42 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by stevencurl** [comment]
Just adding my hat here to get updates, changed this setting Globally, and then a test team last week, still seeing filtered results only.

**Comment by lindspea** [comment]
@Everett42 @stevencurl Thank you for reaching out.  I'll investigate with the team and get back to you soonest.

**Comment by stevencurl** [comment]
The documentation only specifies values of Strict and Moderate.

When I Get-Team on my group, the relevant setting is neither of those (and I'm assuming a placeholder value).
`AllowGiphy                        : True
GiphyContentRating                : unknownFutureValue`

Perhaps there's an undocumented option for the GiphyContentRating setting

**Comment by lindspea** [comment]
@stevencurl just checking, is it turned on in the tenant?

**Comment by stevencurl** [comment]
Yes, it’s on and confirmed in the tenant.

**Comment by lindspea** [comment]
@tonysmit could you possible assist?

**Comment by lindspea** [comment]
@tonysmit

**Comment by scanum** [comment]
@tonysmit Could you please assist us with the next steps on this issue? Thanks!

**Comment by scanum** [comment]
@tonysmit Could you please assist us with the next steps on this issue? Thanks!

**Comment by lindspea** [comment]
@Everett42 I see the article has been updated in January. Has the issue been solved?

**Comment by scanum** [comment]
@Everett42 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
