### ISSUE TITLE
Migration from the previous model to the carrier trunk

### ISSUE THREAD

**Issue by Nfon-JH** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3207]
Hi there,

With regards to this line:
**We highly encourage migrating to the new solution as soon as possible as we will be enhancing monitoring and provisioning using the carrier and derived trunk model.**

When can we expect the enhanced monitoring to be rolled out? Is there a road map for this?

Also does this enhanced monitoring include some sort of stats showing up under Voice > Direct Routing in the tenant account?

**Comment by scanum** [comment]
@Nfon-JH Could you please link the document you are referring to?

**Comment by lindspea** [comment]
@Nfon-JH Thank you for reaching out. For us to be able to assist you, we need the article that you are referencing.  Please send the link when you get a chance.

**Comment by Nfon-JH** [comment]
@lindspea - https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants#register-a-subdomain-name-in-a-customer-tenant

Under **Migration from the previous model to the carrier trunk**

**Comment by lindspea** [comment]
@Nfon-JH Let me know if this helps. https://www.microsoft.com/en-za/microsoft-365/roadmap

**Comment by Nfon-JH** [comment]
@lindspea - I've had a look at this but I'm probably missing something as I can't find anything. Could you point me to the relevant roadmap section?

**Comment by lindspea** [comment]
@Nfon-JH I've updated the link with the latest roadmap. Hope this helps.

**Comment by scanum** [comment]
@Nfon-JH Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
