### ISSUE TITLE
Need a list of Diagnostic IDs.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#321]
A list of diagnostic IDs and their meanings will be really helpful. Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adf572e7-902f-6bee-efd2-8d1916ff875a
* Version Independent ID: b9e916e3-2b3f-391d-9e74-43f457ef0ec1
* Content: [Failure List Report in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/manage/health-and-monitoring/failure-list-report)
* Content Source: [Skype/SfbServer/manage/health-and-monitoring/failure-list-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/health-and-monitoring/failure-list-report.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
I agree, but this information is not available.
