### ISSUE TITLE
NVidia Driver version

### ISSUE THREAD

**Issue by sindharta** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3212]
My Nvidia driver version is 436.48, and this versioning looks very different from what is written in this page: [0.0.0.0] - [21.21.13.7848].

I am wondering if hardware acceleration can enabled on my computer ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e7f4e46-0e6a-3d42-022d-b07fd17792b3
* Version Independent ID: 5217778e-130d-6bed-beb7-f3834331f8ed
* Content: [Hardware decoder and encoder driver recommendations](https://docs.microsoft.com/en-us/microsoftteams/hardware-decoders-and-encoders#feedback)
* Content Source: [Teams/hardware-decoders-and-encoders.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hardware-decoders-and-encoders.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@sindharta Thanks for submitting feedback. We are currently investigating this.

**Comment by scanum** [comment]
@sindharta thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
