### ISSUE TITLE
Missing many of the reports

### ISSUE THREAD

**Issue by kelemvor33** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3214]
Howdy,
I was trying to pull a report to show total minutes used per person but I found that I'm missing many of the reports listed on this page.  The only ones I see are:
Teams user activity, Teams device usage, Teams usage, Teams live event usage, PSTN usages, and PSTN blocked users.
I seem to be missing the Calling Plans and Minute Pools reports and maybe some others.  Any idea why?  We use Teams as our phone system so that's what I wanted to report on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ade1a4-092c-1132-44df-ee2c683fdd33
* Version Independent ID: 396b1aee-2f40-9895-9b00-07e38d11d31b
* Content: [Microsoft Teams analytics and reporting](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-reporting-reference)
* Content Source: [Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@kelemvor33 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@kelemvor33 Thank you for reaching out. Please let me know if these links help. - https://docs.microsoft.com/graph/reportroot-concept-overview. The reports in the Microsoft Teams admin center are separate from the activity reports for Teams that are part of the Office 365 reports in the Microsoft 365 admin center. For more information about the activity reports in the Microsoft 365 admin center, see https://docs.microsoft.com/microsoftteams/teams-activity-reports.

**Comment by scanum** [comment]
@kelemvor33 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
