### ISSUE TITLE
Camera Location Image

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3215]
The image in Camera Location section (https://docs.microsoft.com/en-us/microsoftteams/room-systems/content-camera#camera-location) does not render well in 'Dark Theme'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b06af4b9-8034-c287-b30c-ca009b8549c1
* Version Independent ID: bf2e1bd9-9b86-68a9-42dd-89001bedf0cd
* Content: [Manage a Microsoft Teams Rooms console settings remotely with an XML configuration file](https://docs.microsoft.com/en-us/microsoftteams/room-systems/content-camera#camera-location)
* Content Source: [Teams/room-systems/content-camera.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/content-camera.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
@scanum Please initiate an art request to get this redone in Visio.

**Comment by lindspea** [comment]
@shivtorov Thank you for reaching out and helping improve MS Docs. Are you suggesting having the image changed to a colour so it's visible in dark and light theme?

**Comment by shivtorov** [comment]
all images in this documentation set (https://docs.microsoft.com/en-us/microsoftteams/room-systems/) has non-transparent background, thus look identically good regardless of the active theme (light/dark/high-contrast). Example: https://docs.microsoft.com/en-us/microsoftteams/room-systems/skype-room-systems-v2-0#identify-who-will-undertake-the-key-activities-throughout-your-deployment

The only exception is the image reported in my initial post. It uses transparent background thus unreadable when 'dark' and 'high contrast' themes are used.

The author needs to re-export image from his Visio file ensuring non-transparent background  color

**Comment by lindspea** [comment]
@SerdarSoysal

**Comment by j0rt3g4** [comment]
PR  #3382

**Comment by lindspea** [comment]
@SerdarSoysal any update with this yet?

**Comment by scanum** [comment]
@SerdarSoysal Following up on this issue. Could you please help us with next steps? Thanks!

**Comment by SerdarSoysal** [comment]
Looks like this was already fixed in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/3488. Closing this issue as resolved.
