### ISSUE TITLE
Please describe the scenario about federation between MS Teams and pure on-prem Lync/SfB.

### ISSUE THREAD

**Issue by lyncjp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3218]
Currently, the federation connection is successful between MS Teams and pure on-prem SfB/Lync. MS Teams teant does not need hybrid configuration. Please update this article if it is officially supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external access (federation) in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access#feedback)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@lyncjp Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LeratoLetswalo** [comment]
Hi,

My name is Lerato, I’m from South Africa. I seem to have a problem with my MS teams account, every time I try to make a call externally teams won’t allow me to. Video calling those on the same domain is not a problem only people outside my domain. The only method available for video calling external participants is to create an outlook teams meeting. External access is enabled... I would like to know if there is a way I can make (meet now) videos calls?

Your help would be highly appreciated.

**Comment by lindspea** [comment]
@lyncjp Thank you for reaching out and helping improve MS Docs.  Everything that is not directly mentioned in this article is not supported, but please let me know if you have found an error/change where the article needs to be updated. Any help will be appreciated.

**Comment by white-tim** [comment]
Does that mean federation between an organsiation that SFB on-premises and an organisation that is Teams only is not supported?  I can't see it listed on this page.

**Comment by scanum** [comment]
@lyncjp We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
