### ISSUE TITLE
SIP Test link

### ISSUE THREAD

**Issue by danielategan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3226]
The sip testerlink does not work...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99036b5e-f358-fda3-d9b1-1279952b59a5
* Version Independent ID: 9ea42c59-7db5-9c66-ef58-98b4909ccd10
* Content: [PowerShell script to test Direct Routing Session Border Controller connections](https://docs.microsoft.com/en-us/microsoftteams/sip-tester-powershell-script#feedback)
* Content Source: [Teams/sip-tester-powershell-script.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sip-tester-powershell-script.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by FilippSe** [comment]
Link was fixed. Works fine now.

**Comment by LanaChin** [comment]
Link works now. Closing issue. Thank you.
