### ISSUE TITLE
iOS Teams client does not support PAC proxy for media

### ISSUE THREAD

**Issue by mjtart** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3227]
Could this limitation be listed, see ICM 14694517.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e8b2651-40bb-0d26-6126-d88689047f23
* Version Independent ID: 5be83c7d-ef7f-5582-4a6c-f0709fb2ec7b
* Content: [Prepare your network for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/upgrade-prepare-environment-prepare-network)
* Content Source: [Teams/upgrade-prepare-environment-prepare-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-prepare-environment-prepare-network.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@mjtart Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@mjtart thank for reaching out. Could you perhaps elaborate a bit. Which section of the article needs to be updated?

**Comment by scanum** [comment]
@mjtart We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
