### ISSUE TITLE
Need information about serverusername.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#323]
Need to know where SfB get its serverusername. Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 179ab3b0-2834-2b99-fc12-2f62b51c054d
* Version Independent ID: 4f910a3d-1de8-60d1-b12d-8ff58be5b8e6
* Content: [User and client authentication for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/security/user-and-client-authentication)
* Content Source: [Skype/SfbServer/plan-your-deployment/security/user-and-client-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/security/user-and-client-authentication.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.
