### ISSUE TITLE
Figure 2 is incomplete

### ISSUE THREAD

**Issue by fshields** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3230]
Figure 2 does not indicate which icon is User A and which is User B.  Flows 2 & 4 do not connect to any internal users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c84773-337e-9df7-7fbd-fc9d94280711
* Version Independent ID: 223a78a0-67fd-8b96-be3f-153bb400101b
* Content: [Microsoft Teams call flows](https://docs.microsoft.com/en-us/microsoftteams/microsoft-teams-online-call-flows#feedback)
* Content Source: [Teams/microsoft-teams-online-call-flows.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/microsoft-teams-online-call-flows.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by lindspea** [comment]
@fshields thank you for pointing this out and helping improve MS Docs. @CarolynRowe could you possibly help with the correct image please, and I'll have it uploaded.

**Comment by lindspea** [comment]
@CarolynRowe

**Comment by scanum** [comment]
@fshields Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
