### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by danielategan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3231]
Hi there, can you be more clear with screenshots on how to use this script. I keep getting this error: ERBOSE: Acquiring AAD token...DONE
VERBOSE: Enqueueing test...
VERBOSE: POST https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites with -1-byte payload
Run-SIPTest : Enqueueing test...FAILED: The remote server returned an error: (401) Unauthorized.
At C:\SFB Resources\siptesterclient\SipTesterClient.ps1:382 char:17
+ ... statusResult = Run-SIPTest $EndpointUrl $testBody $CertificateContent
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Run-SIPTest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99036b5e-f358-fda3-d9b1-1279952b59a5
* Version Independent ID: 9ea42c59-7db5-9c66-ef58-98b4909ccd10
* Content: [PowerShell script to test Direct Routing Session Border Controller connections](https://docs.microsoft.com/en-us/microsoftteams/sip-tester-powershell-script#feedback)
* Content Source: [Teams/sip-tester-powershell-script.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sip-tester-powershell-script.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by FilippSe** [comment]
I think you have an issue with adal.ps package, it did not install automatically on your machine. Documentation specifies: The script needs the Adal.ps package for execution. If it's not present, the script will try to install it automatically. For this, run the script in administrator mode (first execution only).

Please run manually in powershell admin console, Install-Package -Name adal.ps 

The script will be updated soon (might take a day) to avoid this in the future.

**Comment by LanaChin** [comment]
@FilippSe, @danielategan: The updated script is now available in the download package.  Thank you.

**Comment by oradcliffe** [comment]
Using the updated script, installed adal.ps automatically worked, however I still get the above error as described.

**Comment by sgtdonny** [comment]
I have the same problem. Script doesn'T work with this "Token exeption".
Adal.ps is installed.
The documentation gives no information what schould happen, login after starting or do you have to login before starting?

**Comment by trecee13** [comment]
> I have the same problem. Script doesn'T work with this "Token exeption".
> Adal.ps is installed.
> The documentation gives no information what schould happen, login after starting or do you have to login before starting?

I too have the same error on muliple tenants on mulitple environments, i am installing the correct adal package but i just get get past GET https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/14402277-6cf3-4eb8-99a3-8c9387829191 with 0-byte payload   
Here are my results, Please if anyone has run this test successfully i would appreciate some more details on how you accomplilshed this?   


VERBOSE: Acquiring AAD token...
VERBOSE: Loading module from path 'C:\Users\urbin\Documents\WindowsPowerShell\Modules\ADAL.PS\3.19.8.1\ADAL.PS.psd1'.
VERBOSE: Importing function 'Clear-ADALTokenCache'.
VERBOSE: Importing function 'Get-ADALAuthenticationContext'.
VERBOSE: Importing function 'Get-ADALToken'.
VERBOSE: Importing function 'New-ADALClientCredential'.
VERBOSE: Importing function 'New-ADALUserIdentifier'.
VERBOSE: Acquiring AAD token...DONE
VERBOSE: Enqueueing test...
VERBOSE: POST https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites with -1-byte payload
VERBOSE: received 407-byte response of content type application/json; charset=utf-8
VERBOSE: Enqueueing test...DONE
VERBOSE: Test status link: https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/14402277-6cf3-4eb8-99a3-8c9387829191
VERBOSE: Checking test status...
VERBOSE: GET https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/14402277-6cf3-4eb8-99a3-8c9387829191 with 0-byte payload
VERBOSE: received 1119-byte response of content type application/json; charset=utf-8
VERBOSE: Test in 'scheduled' state; Checking again in 10 seconds...
VERBOSE: GET https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/14402277-6cf3-4eb8-99a3-8c9387829191 with 0-byte payload
VERBOSE: received 2894-byte response of content type application/json; charset=utf-8
VERBOSE: Test in 'failed' state


Test: Outbound to Inbound

state     code flow    
-----     ---- ----    
signedOut      outbound
failed    1000 inbound

**Comment by livaht** [comment]
Hello @trecee13, 

thank you for notifying. We have checked the logs for request https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/14402277-6cf3-4eb8-99a3-8c9387829191
_AADSTS50126: Error validating credentials due to invalid username or password._

Can you please double check the test user credentials and let us know if that helped? 
We are improving the error message displayed, so this would be immediately clear from test results.

**Comment by kthemall** [comment]
hi, i have a problem with executing the script:


VERBOSE: Acquiring AAD token...DONE
VERBOSE: Enqueueing test...
VERBOSE: POST with 417-byte payload
Write-Error: C:\Apps\SipTesterClient.ps1:409
Line |
 409 |  … statusResult = Run-SIPTest $EndpointUrl $testBody $CertificateContent
     |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Enqueueing test...FAILED: Unspecified Failure

False



any ideas? logging in with account works fine but then the error occurs.

thx tom
#
