### ISSUE TITLE
.net framework 4.8 supportability Skype for Business 2015

### ISSUE THREAD

**Issue by ExaSD** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3235]
Hi Team,

Can you please make it clear is the .net 4.8 working SfB 2015? 

Regards,
Mat

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c475b5d-09ed-7f58-86d4-27f28e33ef7a
* Version Independent ID: f0ad50f3-ea93-9424-6de8-a0b778e90b23
* Content: [Server requirements for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/server-requirements#feedback)
* Content Source: [Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ExaSD Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Erdem-Oz** [comment]
Hi,

I also asked in a different ticket on the SFB 2019 page, but for  SFB2015 i have not installed it and let it still on 4.7. On the page it still says with an older CU: • .NET 4.7.1 and higher (for Skype for Business Server CU 5 or later releases). And in the new CU updates i did not see anything about the .net 4.8 framework.

**Comment by lindspea** [comment]
@ExaSD @Erdem-Oz Thanks for reaching out. I'll investigate further with the team.

**Comment by lindspea** [comment]
@ExaSD @Erdem-Oz  please see this related issue that was solved. https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2922

**Comment by Erdem-Oz** [comment]
@lindspea Hi, it was only mentioned for SFB Server 2019, but not 2015. In that ticket i meant both versions. So it is still unclear if it is supported for SFB server 2015

**Comment by lindspea** [comment]
@Erdem-Oz I've done some more investigating and found that it is not supported for SFB server 2015. Let me know if you need any further assistance.

**Comment by Erdem-Oz** [comment]
@lindspea Thank you for your reply, can it be changed in the docs? Is it clear that it will be supported in the next CU's?

**Comment by Erdem-Oz** [comment]
I have made changes to the document. it needs to be reviewed

**Comment by lindspea** [comment]
Hi @Erdem-Oz  I'm still investigating with the team regarding the next CU.  Just waiting for an answer and then I will do a PR to add a note in the document for clarity for other users? Do you have a PR number for the changes you made?

**Comment by Erdem-Oz** [comment]
@lindspea Hi, my commit is: 957913a

**Comment by lindspea** [comment]
Thanks @Erdem-Oz, I've done a PR with recommended changes. Once approved by the team it will reflect in the document. At this stage I can't give you an answer regarding the next CU for supportability. Let me know if you need further assistance.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@ExaSD We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
