### ISSUE TITLE
Set-CsUser cmdlet returns an error

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3236]
Hi! When we try to run the Set-CsUser on S4B Online then we get the following error "A parameter cannot be found that matches parameter name 'OnPremLineUri'. This article https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/online-configuration/admins-cant-use-set-csuser states that this cmdlet cannot be used with parameters mentioned in above article. Please advise which cmdlet should be used to configure direct routing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df318fdb-6d58-86f8-de31-6eca533a9746
* Version Independent ID: a2248abf-bdf0-2c22-2604-74b482156684
* Content: [Configure Direct Routing](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-configure#configure-the-phone-number-and-enable-enterprise-voice-and-voicemail)
* Content Source: [Teams/direct-routing-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-configure.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Larryngolog Thank you for reaching out. Please have a look at this article and let me know if it helps at all. https://docs.microsoft.com/powershell/module/skype/new-csonlinevoiceroute?view=skype-ps

**Comment by Larryngolog** [comment]
Hi! Unfortunately not. This cmdlet defines the route that is taken by specific numbers but does not assign these numbers to users.
We have checked internally on different environments and it looks like the cmdlet is working as described in the "Configure Direct Routing". It looks like the Troubleshooting article is not correct or does not include information under which scenarios set-csuser will not work.

**Comment by lindspea** [comment]
@Larryngolog thanks for clearing that up. Is this the troubleshooting article you are referring to that doesn't reflect correctly. https://docs.microsoft.com/microsoftteams/direct-routing-monitor-and-troubleshoot

**Comment by lindspea** [comment]
@CarolynRowe

**Comment by scanum** [comment]
@CarolynRowe Could you please help out with this issue? Thanks!

**Comment by scanum** [comment]
@CarolynRowe Could you please help out with this issue? Thanks!

**Comment by CarolynRowe** [comment]
What is the ask specifically?  To update the troubleshooting article?  To configure Direct Routing, you should be following the instructions in Configure Direct Routing, which were correct?  Can you explain what sent you to the troubleshooting article?

**Comment by scanum** [comment]
@lindspea Please see Carolyn's comment.

**Comment by lindspea** [comment]
@Larryngolog please see @CarolynRowe comments above and elaborate please. Thank you for taking the time to help improve MS Docs.

**Comment by Larryngolog** [comment]
Hi @CarolynRowe  as I mentioned we were trying to configure Direct Routing using the provided cmdlet and got an error. We searched for the error and found the troubleshooting article. I thought that there are contrary information in this article and the troubleshooting articles. So either article needs clarification as this article states that you should use the "Set-CsUser" cmdlet with -EnterpriseVoiceEnabled HostedVoiceMail and OnPremLineURI parameters, and the troubleshooting one states that "AudioVideoDisabled is the only parameter that you can use together with the Set-CsUser cmdlet in Skype for Business Online". When we get error when configuring Direct Routing we get contradictory statements and do not know if this is by design or not.

**Comment by scanum** [comment]
@CarolynRowe Following up on this issue. Thanks!

**Comment by CarolynRowe** [comment]
Please follow the instructions under Configure Direct Routing.  I will follow up with the PMs about whether we need to update the troubleshooting content.  If you continue to have problems configuring Direct Routing, please contact technical support.

**Comment by onehit** [comment]
In case anyone else runs into this issue, we resolved it by adding the "Skype for Business Administrator" role to the admin user - despite being Teams Only tenant-wide, "Teams Service Administrator" was not enough to get this property when connecting to the online connector.
