### ISSUE TITLE
Mistake in article

### ISSUE THREAD

**Issue by sho74** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3238]
In phrase "In Belgium, France, Germany, Ireland, Netherlands, and Spain i's important to understand.... "  please review it for "i's"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd65a979-367c-001c-7462-ead0f0cfd989
* Version Independent ID: f430e334-25d4-b457-4350-7819953e199e
* Content: [Add, change, or remove an emergency location for your organization](https://docs.microsoft.com/en-us/microsoftteams/add-change-remove-emergency-location-organization)
* Content Source: [Teams/add-change-remove-emergency-location-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/add-change-remove-emergency-location-organization.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by sho74** [comment]
Also in phrase " which os used to acquire the number"   what does it mean "os"?

**Comment by LanaChin** [comment]
Thanks for bringing this up. Fixed the typos.  os-> is  and i's -> it's.
