### ISSUE TITLE
Need to know about Anti-virus feature is available or not.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#324]
Is there any anti-virus measures included in Skype for Business with respect to document transfer using Skype? Can you point me to any link, where I can find it? Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5795e94-a3bd-4c84-ce20-cfc2ea3fc407
* Version Independent ID: 6b7fdc3b-69f8-3b91-ab45-8a7789d777ef
* Content: [Key security features in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/security/key-security)
* Content Source: [Skype/SfbServer/plan-your-deployment/security/key-security.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/security/key-security.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@nsshommo thank you for your feedback. Checking on this.

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.
