### ISSUE TITLE
Incorrect parameter referenced in example

### ISSUE THREAD

**Issue by kitleyn** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3240]
Withing the example command 'Get-CsMeetingMigrationStatus| Where {$_.State -eq "Failed"}| Format-Table Identity, LastMessage' the parameter Identity is incorrect in this context. It should be UserPrincipalName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 990ca74b-6bba-a14b-071a-d13adb723a4c
* Version Independent ID: 52f55a58-30ce-c140-3ee7-8042b1d105f0
* Content: [Using the Meeting Migration Service (MMS)](https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/setting-up-the-meeting-migration-service-mms#feedback)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/setting-up-the-meeting-migration-service-mms.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/setting-up-the-meeting-migration-service-mms.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@kitleyn Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@kitleyn Thank you for reaching out and helping improve MS Docs. Are you suggesting changing it to read as follows:  Get-CsMeetingMigrationStatus| Where {$_.State -eq "Failed"}| UserPrincipalName ?

**Comment by robertpp** [comment]
@lindspea: I believe the intent was to replace only the Identity:

`Get-CsMeetingMigrationStatus| Where {$_.State -eq "Failed"}| Format-Table UserPrincipalName, LastMessage`

**Comment by lindspea** [comment]
@scanum this can be closed thanks.

**Comment by scanum** [comment]
@kitleyn Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
