### ISSUE TITLE
Remote Capture Tool Download Link

### ISSUE THREAD

**Issue by dsureshmadhu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3241]
Hi,

I am planning to run the tests for Miscorsoft Teams Skype certification testing. Remote capture tools shall be installed and used inorder to run most of the tests as Microsoft Team video capture specification (Microsoft_Teams_VideoSpecification_4_Final.pdf). I have referred below page and downloaded and installed Video TMT 2.3 and Skype Certification Video analyzer tools but I couldn't find any link to download Remote capture tool.

https://docs.microsoft.com/en-us/skypeforbusiness/certification/test-spec

Can you please point where to download the remote capture tool?

Regards
Suresh

**Comment by dsureshmadhu** [comment]
Hi,

I could find Remote Control Package in %ProgramFiles(x86)%\Microsoft Corp\Video TMT\Remote Capture Tool\ location and I am getting below error when I tried to install it using powershell. Can you please help me to install this tool?


Found bundle: C:\Program Files (x86)\Microsoft Corp\Video TMT\Remote Capture Tool\RemoteCaptureTool\RemoteCaptureTool\RemoteCaptureTool.Windows_2.1.0.21_Test\RemoteCaptureTool.Windows_2.1.0.21_x86_x64_arm.appxbundle
Found certificate: C:\Program Files (x86)\Microsoft Corp\Video TMT\Remote Capture Tool\RemoteCaptureTool\RemoteCaptureTool\RemoteCaptureTool.Windows_2.1.0.21_Test\RemoteCaptureTool.Windows_2.1.0.21_x86_x64_arm.cer
Error: The developer certificate "C:\Program Files (x86)\Microsoft Corp\Video TMT\Remote Capture Tool\RemoteCaptureTool\RemoteCaptureTool\RemoteCaptureTool.Windows_2.1.0.21_Test\RemoteCaptureTool.Windows_2.1.0.21_x86_x64_arm.cer" has expired. One possible cause is the system clock isn't set to the correct date and time. If the system settings are correct, contact the app owner to re-create a package or bundle with a valid certificate.

Regards
Suresh

**Comment by scanum** [comment]
@dsureshmadhu Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@dsureshmadhu thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
