### ISSUE TITLE
Direct Routing

### ISSUE THREAD

**Issue by Erdem-Oz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3242]
Hi,
Is this report for direct routing or only Microsoft calling plans?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8107d4a3-a55e-4891-ee72-27f79f647a1e
* Version Independent ID: b71f24c6-b54d-8a0f-ea0e-8839ff5481a4
* Content: [Microsoft Teams PSTN minute pools report](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/pstn-minute-pools-report)
* Content Source: [Teams/teams-analytics-and-reports/pstn-minute-pools-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/pstn-minute-pools-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Erdem-Oz Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Erdem-Oz Thank you for reaching out.  Please have a look at this article for direct routing - https://docs.microsoft.com/microsoftteams/direct-routing-configure.  Let me know if it helps.

**Comment by Erdem-Oz** [comment]
@lindspea Thank you for the reply, I was only questioning if the report for PSTN minute Pools also report Direct Routing calls? Soms of the reports are working for Direct Routing

**Comment by lindspea** [comment]
@Erdem-Oz I've investigated and found that it does. See roadmap - https://www.microsoft.com/microsoft-365/roadmap?filters=O365&searchterms=56507. Running the report provides an output where you can choose between Direct Routing and Calling Plan calls, as well as export to CSV and apply filters to view to the data. Hope this answers your question.

**Comment by lindspea** [comment]
@scanum this can be closed thanks.

**Comment by scanum** [comment]
@Erdem-Oz Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
