### ISSUE TITLE
How to know which group was created

### ISSUE THREAD

**Issue by jbramwell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3243]
If I create a new team in Teams, how do I know the name of the corresponding group in Office 365? Am I able to see this in Teams somewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d86301b-ce9c-388c-e563-9e5e5c27132e
* Version Independent ID: 07e4ae23-0966-e8f3-9b7c-4f6c02569eb0
* Content: [Office 365 Groups and Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/office-365-groups#feedback)
* Content Source: [Teams/Office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-groups.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@jbramwell Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@jbramwell Thank you for reaching out.  You should be able to see this in the Admin Center of Teams.  Please have a look at this article and let me know if it helps. https://docs.microsoft.com/microsoftteams/manage-teams-in-modern-portal

**Comment by jbramwell** [comment]
Thanks! However, if you don't have access to the Admin Center (for Teams) is there any way of knowing the group name for the Team that I just created?

--- Thanks, Jeff Bramwell
Visual Studio ALM MVP|<http://blog.devmatter.com>BLOG<http://blog.devmatter.com>|+1.402.212.3444
________________________________

**Comment by lindspea** [comment]
@jbramwell if you go to the top right next to your name/profile pic there is a dropdown arrow.  When you click on that it will show all the groups that you have been added to or created. Hope this helps.

**Comment by scanum** [comment]
@jbramwell Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
