### ISSUE TITLE
Wrong Uri

### ISSUE THREAD

**Issue by joaolloureiro** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3247]
Uri should be http://www.microsoft.com/LCS/SharedLineAppearance and not http**s**://www.microsoft.com/LCS/SharedLineAppearance

For more details please check https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-deploy-shared-line-appearance and IcM 153783001 or contact joaol

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a4b809c-321d-507d-a6ef-6fb0c3244a14
* Version Independent ID: a684d7c3-83c4-4783-73e5-da576cb15d61
* Content: [Deploy Shared Line Appearance in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-enterprise-voice/deploy-shared-line-appearance)
* Content Source: [Skype/SfbServer/deploy/deploy-enterprise-voice/deploy-shared-line-appearance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-enterprise-voice/deploy-shared-line-appearance.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@joaolloureiro  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @joaolloureiro thanks for noticing, created a pr to correct the URI.
Thanks

**Comment by get-itips** [comment]
@scanum pr was merged, this can be closed. Thanks

**Comment by scanum** [comment]
@joaolloureiro Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
