### ISSUE TITLE
Deleted channel retention

### ISSUE THREAD

**Issue by yemiade** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3248]
30 day retention of deleted channel is incorrect. It is 21 days. A recently updated doc has the correct information https://docs.microsoft.com/en-us/microsoftteams/plan-teams-lifecycle#stage-3-end. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#feedback)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@yemiade  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @yemiade 
Thanks for sharing this, created a pr to propose correcting this info.

**Comment by scanum** [comment]
@yemiade Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
