### ISSUE TITLE
Visitor access?

### ISSUE THREAD

**Issue by aaronsteers** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3249]
Understanding that Members and Owners are the only two levels of access natively understood by Teams, what is the default behavior for the "Visitors" group in the underlying SharePoint site? Can we use this for instance for users who should have read access to from the documents library and/or the planner - without giving those users write access?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20423b44-629b-1bee-280c-fb55680cd33e
* Version Independent ID: a60f6a48-89d7-98b6-4245-4be171fd06fd
* Content: [Assign team owners and members in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/assign-roles-permissions)
* Content Source: [Teams/assign-roles-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-roles-permissions.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@aaronsteers  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @aaronsteers 
Thanks for your feedback.

As you know, Teams Sharepoint Sites are created as Team Sites, and each SharePoint team site is part of an Office 365 group and:

> Office 365 groups don't have a visitors permission for view-only access, so any users you wish to have view permissions on the site must be added directly to the visitors group on the site

[Source](https://docs.microsoft.com/en-us/sharepoint/modern-experience-sharing-permissions)

If you browse the Team Site associated to the Teams, you can add users to the Visitors Group for them to browse the Team Site and I think that fulfills what you want to do, please tell me if I understood correctly.

**Comment by scanum** [comment]
@aaronsteers Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
