### ISSUE TITLE
Software requirement to operate Lync 2013.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#325]
What are the software required to operate the Lync 2013 integrity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042aae71-299f-d58d-44c8-f500de8e8917
* Version Independent ID: 1c6533e6-3cc0-824d-db8f-083398c8e36e
* Content: [Windows client requirements and software support](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/windows-requirements)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/windows-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/windows-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Question is unclear. The page referred to is about the SfB client, not the Lync 2013 client.

**Comment by nsshommo** [comment]
Yes, that was also my confusion. If possible, you can add a link to "software requirement to operate the Lync 2013", so others can find it here.

**Comment by jambirk** [comment]
we'll probably need to save that until after Lync 2013 content is migrated to this new platform.

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.
