### ISSUE TITLE
no dot in 365 domain 

### ISSUE THREAD

**Issue by bigred3142** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3250]
in the section To move a user to Teams Only mode using Move-CsUser:

---------------
If the account with permissions in Office 365 does not end in “on.microsoft.com”, 

that should be 'onmicrosoft.com' - no dot 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca38b93a-773e-3864-45b6-128dd3163f37
* Version Independent ID: 7c32e933-94f2-196e-1163-3881df3aaf5a
* Content: [Move users from Skype for Business Server 2019 to Teams](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/move-users-from-on-premises-to-teams)
* Content Source: [Skype/SfbHybrid/hybrid/move-users-from-on-premises-to-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/move-users-from-on-premises-to-teams.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@bigred3142  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @bigred3142 
Thanks for your feedback and noticing that, created a pr to correct the article.

**Comment by get-itips** [comment]
@scanum PR Merged, this can be closed.

**Comment by scanum** [comment]
@bigred3142 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
