### ISSUE TITLE
Speaker mute in TEAMS

### ISSUE THREAD

**Issue by Tiffanychen1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3251]
The speaker mute doesn’t trigger properly from the Teams client. 
The speaker mutes but the OS volume bar didn't shows mute.

**Comment by scanum** [comment]
@Tiffanychen1 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
