### ISSUE TITLE
Is Azure AD Basic EDU still a thing?

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3252]
The page has an information block with the following content:

```Using the Office 365 Groups Naming Policy requires Azure Active Directory Premium P1 licenses or Azure AD Basic EDU licenses for each unique user that is a member of one or more Office 365 groups.```

Where can I find additional information about "Azure AD Basic EDU" and how can it be enabled within a tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 815d1ce1-cb68-25b5-6a59-435461559495
* Version Independent ID: 1f6ac386-4ca4-1cde-bae0-ed6df8c94d61
* Content: [Microsoft Education governance FAQ for IT pros - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/plan-teams-governance-edu)
* Content Source: [Teams/plan-teams-governance-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-teams-governance-edu.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by MaratMussabekov** [comment]
answered in https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/785

**Comment by andikrueger** [comment]
Thank you @MaratMussabekov
