### ISSUE TITLE
Include Guest Meeting Experience

### ISSUE THREAD

**Issue by StPhil** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3254]
We don't currently have any visible information on what the guest experience is like when joining a meeting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [What the guest experience is like](https://docs.microsoft.com/en-us/MicrosoftTeams/guest-experience)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@StPhil  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by bebobebo** [comment]
This is an issue for our organisation as we're having trouble managing guests in meetings. They seem to be clicking on the wrong meeting links in a channel which causes a lot of confusion as participants are attending different simultaneous online meetings. 
Do guests have to "accept" meeting invitations ? We certainly can't count on them all using Outlook...

**Comment by TokyoScarab** [comment]
@StPhil Thank you for raising this issue! I'll be looking into it!

**Comment by TokyoScarab** [comment]
@bebobebo In addition to the meeting links, is there anything else you would like to see added to this documentation?

**Comment by bebobebo** [comment]
For those inside the tenancy it's really hard to see what the guest sees at each stage of the experience. We cannot support them as we have no experience to guide them with. So a series of screenshots or a video showing the actual guest journey would help enormously.

**Comment by scanum** [comment]
@TokyoScarab Wondering if there is an update for this issue? Thanks!

**Comment by adagioajanes** [comment]
I would also like to see this added. It will make support the experience for external users alot easier.

**Comment by scanum** [comment]
@TokyoScarab Wondering if there is an update for this issue? Thanks!

**Comment by scanum** [comment]
@TokyoScarab Wondering if there is an update for this issue? Thanks!

**Comment by scanum** [comment]
@TokyoScarab  Any updates here? Thanks!

**Comment by dariomws** [comment]
Hi @StPhil, thank you for your feedback.

The following sections was added to the article on April, 22:
-------------------------------------------------------------------------------------------------------------
Check out these videos about the guest experience in Teams:
- [Join a team as a guest](https://support.office.com/article/join-a-team-as-a-guest-928d1eef-61e2-49ec-b754-c2fe86b34824)
- [Join a Teams meeting with guests](https://support.office.com/article/join-a-company-meeting-a120c282-063d-46b8-b973-851197ab75d8)
-------------------------------------------------------------------------------------------------------------

I think it is what you were requesting.

There are more articles with the same or similar information. For example:
https://support.microsoft.com/office/join-a-meeting-without-a-teams-account-c6efc38f-4e03-4e79-b28f-e65a4c039508
https://support.microsoft.com/office/join-a-meeting-in-teams-1613bb53-f3fa-431e-85a9-d6a91e3468c9

Hope it helps.
