### ISSUE TITLE
Applying Policies to groups

### ISSUE THREAD

**Issue by zag2me** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3259]
This help article is great but at the top it says:

 "You can use the default policy that is created automatically or create one or more custom messaging policies for people in your organization. After you create a policy, you can assign it to a user or ***group of users*** in your organization." 

But there are no instructions on how to apply a policy to a ***group*** (rather than a user). I've looked around the teams admin center and can't find any way to do it. Is it possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34f3188-0af5-f972-9d28-959f5f7866a2
* Version Independent ID: fab26e11-a729-92a4-3ea6-8668dca55dd0
* Content: [Manage messaging policies in Teams](https://docs.microsoft.com/en-us/microsoftteams/messaging-policies-in-teams)
* Content Source: [Teams/messaging-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/messaging-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@zag2me  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by rbahne** [comment]
@scanum Any update?

**Comment by get-itips** [comment]
@rbahne You will have to leverage the use of [Grant-CSTeamsMessagingPolicy](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csteamsmessagingpolicy?view=skype-ps) cmdlet and Get-CsOnlineUser, for example

`Get-CsOnlineUser -Filter {Department -eq 'Executive Management'}
| Grant-CsTeamsMessagingPolicy -PolicyName "Executives"`

Will propose a PR adding this information to the article.

**Comment by scanum** [comment]
@zag2me Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
