### ISSUE TITLE
Update 2015 to 2019

### ISSUE THREAD

**Issue by hmizael** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3260]
Where it reads Skype for Business 2015, it should be Skype for Business 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94881ba-6f06-a946-47a3-c9c683ddd303
* Version Independent ID: 081684f7-3570-fdfd-c32d-90b6e07d81b4
* Content: [DNS requirements for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/network-requirements/dns?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json)
* Content Source: [Skype/SfbServer/plan-your-deployment/network-requirements/dns.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/network-requirements/dns.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hmizael  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @hmizael 
Actually, there is currently a documented issue with the content of Skype For Business where the previous versions share the same article with the 2019 version, so if we edit the article that, under navigation says "2019" we are actually editing the article for all versions, including 2015.
The team is aware of this issue and is working on it.
Thanks!

**Comment by scanum** [comment]
@hmizael Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
