### ISSUE TITLE
Return Sign-In Experience

### ISSUE THREAD

**Issue by Rbhoward** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3264]
What is the experience for guests after they initially sign-in? Do they have to go back to the original link they were sent? Do they use sign-in with the Teams web app or desktop app? If they did not initially have an Azure AD or O365 account and created a free Microsoft account, do they sign in with that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [What the guest experience is like](https://docs.microsoft.com/en-us/microsoftteams/guest-experience#feedback)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Rbhoward  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Rbhoward I think this article will clarify that for you https://docs.microsoft.com/en-us/microsoftteams/guest-joins
Hope this information helps you

**Comment by scanum** [comment]
@Rbhoward Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
