### ISSUE TITLE
64-bit MSI installer for teams has platform 32-bit, preventing targeting installation

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3265]
The 64-bit MSI Teams_windows_x64.msi has the Platform property set to target x86 rather than x64 devices. This means deployment software (e.g. Software Installation in Group Policy) which use the Platform property to determine which installer is appropriate for 32-bit and 64-bit machines attempt to install the x64 version on an x86 device - preventing the correct installer being deployed.

It also means if someone tries to run the x64 version on an x86 machine it will not prompt them with an error - instead, it will proceed to set up with the x64 binaries which won't run - instead of prompting the user to install the x86 version as it should.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Microsoft Teams using MSI via SCCM](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment#how-the-microsoft-teams-msi-package-works)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ChrisAtMAF Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@ChrisAtMAF Thank you for raising this issue! I'll be looking into it!

**Comment by Manfred538** [comment]
while looking into that; also change the registy entry (reg81FF20B1B50A706C9CA188B86C189198) "#%%ProgramFiles%\Teams Installer\Teams.exe --checkInstall --source=[SOURCE]" to "#%[APPLICATIONROOTDIRECTORY]Teams.exe --checkInstall --source=[SOURCE]" to prevent the problem of changing install location breaks install as stated in the note above.

**Comment by TokyoScarab** [comment]
@LanaChin Would you be able to pass this information along to the appropriate group or tag them in here?

**Comment by mrik23** [comment]
Yes choosing the 64 bit package it still all installed in 32 bit (x86), and so it's not working when calling %ProgramFiles%\Teams Installer\Teams.exe --checkInstall --source=default.

Also not sure why, but the package is set for installation "Per-user" instead of "Per-machine".

**Comment by LanaChin** [comment]
Looking into this.

**Comment by LanaChin** [comment]
Thanks for your feedback @ChrisAtMAF, @Manfred538, and @mrik23. I've passed your comments  along to the Teams product team. Also just want to let you know that the article has been recently updated to inclue the ALLUSERS=1 parameter.
