### ISSUE TITLE
Access Outlook Contacts?

### ISSUE THREAD

**Issue by bpwhitehouse** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3266]
The top row of the table suggests that Teams users with mailboxes hosted in Exchange Online, can 'Access Outlook Contacts'.
Which contacts? GAL? User's own contacts? Shared Mailbox contacts? 

In any case, O365 support team lead today tells me this is incorrect, and currently Teams cannot access Outlook contacts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact#feedback)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@bpwhitehouse Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by philippreichl** [comment]
any news?

**Comment by VLG17** [comment]
@bpwhitehouse According to the /help function in Teams, when searching after "contacts", you have all your organization's contacts imported in Teams.

![image](https://user-images.githubusercontent.com/41186174/72072362-6f5e0e00-32f6-11ea-8dac-04c0d9cd938f.png)

When i test with my mailbox hosted in Exchange Online, i can find in the Search bar within Teams anyone from my organization's GAL, but i cannot find a Contact (has external address) i have created within Outlook.

I don't have a way to check this, but one thing that could be preventing this is a custom ABP (Address Book Policy) that excludes the All Contacts Address List (which includes all mail contacts - so the external ones).

This is doable for Teams by using the option described in [this article](https://docs.microsoft.com/en-us/microsoftteams/teams-scoped-directory-search):

![image](https://user-images.githubusercontent.com/41186174/72075570-b4853e80-32fc-11ea-937a-f880168a2a75.png)

I don't know if this is the case in your scenario, but it's worth a check.

**Comment by scanum** [comment]
@bpwhitehouse Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
