### ISSUE TITLE
Link zum Admin -Center

### ISSUE THREAD

**Issue by gitc-admin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3267]
Die Dokumentation hilft niemandem, wenn es keinen Link zum Teams Admin-Center gibt!

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: ffbf0bfd-c15e-b10b-0cc9-6a27ac1e6634
* Version Independent ID: 58575371-9e09-fadb-76f6-7491df8580a3
* Content: [Festlegen Ihrer Einstellungen für Koexistenz und Upgrades](https://docs.microsoft.com/de-de/MicrosoftTeams/setting-your-coexistence-and-upgrade-settings#feedback)
* Content Source: [Teams/setting-your-coexistence-and-upgrade-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/setting-your-coexistence-and-upgrade-settings.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officeglobal Hi! Can you please aid with this issue? Thanks!

**Comment by OfficeGlobal** [comment]
@scanum it seems the note is related to an autor
Bing translate: "_The documentation doesn't help anyone if there is no link to the Teams Admin-Center!_"
Once article updated, we'll pick up the updates for a loc.

**Comment by TokyoScarab** [comment]
@gitc-admin  Thank you for raising this issue! I'll be looking into it!

**Comment by VLG17** [comment]
@gitc-admin Vielen Dank für das Feedback. Der Link zum Teams Admin-Center lautet: "https://admin.teams.microsoft.com"

Ich habe ein Pull Request erstellt, um diese Info im Artikel hinzuzufügen.

**Comment by VLG17** [comment]
@OfficeGlobal I have create a PR for the original "en-us" article and added the link to the Teams Admin Center.

**Comment by scanum** [comment]
@gitc-admin Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
