### ISSUE TITLE
Removing Guest Access

### ISSUE THREAD

**Issue by kjulson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3268]
This Guest Access section is missing how to remove guest user access. Just removing their Azure AD account does not remove their access. This should be very specially covered as it is not as simple as it should be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams guest access checklist](https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by kjulson** [comment]
Clarification: When you remove the Azure AD account, it takes roughly an hour to process. If a guest's account should be compromised, Microsoft has left us with no way to protect ourselves. Not being able to block a guest account leaves is a potentially large security hole.

**Comment by scanum** [comment]
@kjulson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Bart-Hoofd** [comment]
You can disable Guest access immediately by disabling the Azure AD account: 
Set-AzureADUser -ObjectId user_hotmail.com#EXT#@tenant.onmicrosoft.com -AccountEnabled $False

**Comment by sowjanya365** [comment]
Hi @kjulson 

Thank you for reaching out!

Hope your query is clarified. Let me know if you are still looking for help. Thank you!

**Comment by scanum** [comment]
@kjulson https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3384

**Comment by kjulson** [comment]
A. A PowerShell answer to a GUI interface is poor at best.
B. There is no mention of this in either this article or in the article linked on the page "Turn on or turn off guest access to Microsoft Teams"
C. Article closed by scanum without actually checking if this was resolved.

So a whole bunch of fail on Microsoft's part.
