### ISSUE TITLE
Need Clarification.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#327]
Here an OCS 2007 R2 document is included for db-analyze and it does not apply in the slightest.  No WMI is used for this in SfB server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a279530-e333-d1ad-4626-4a4872560594
* Version Independent ID: 9c015bec-b047-986c-d986-ea5fd12b543e
* Content: [Skype for Business Server 2015 Resource Kit Tools Documentation](https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/resource-kit-tools)
* Content Source: [Skype/SfbServer/management-tools/resource-kit-tools.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/management-tools/resource-kit-tools.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
We won't be able to update this document.
