### ISSUE TITLE
Machine Wide / MSI Installer / VDI

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3274]
Are the:  https://aka.ms/teams64bitmsi  &  https://teams.microsoft.com/downloads/desktopurl?env=production&plat=windows&download=true&managedInstaller=true&arch=x64

the exact same MSI file?  and the ALLUSER=1 flag is the only thing that makes it run the VDI ALLUSER features?

It's kind of confusing have a Machine-Wide MSI Installer that also has a ALLUSER flag as well...

**Comment by scanum** [comment]
@mattsmacblog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by mattsmacblog** [comment]
I am having issues running the Teams_windows_x64.msi installer with and without the ALLUSER flag, just keep getting "Cannot install for all users when a VDI environment is not detected". Same error in either mode which doesn't really make sense.  The MSI is just supposed to be an "MSI for deployment with tools like SCCM" is it not? and the ALLUSER feature is what triggers the machine-wide / VDI style install?   

Even making a custom Transforms file that sets "allUsersInstallSupported" = "0" isn't getting around it on Win10 1803.  On 1903 that worked for me...

Has the Teams_windows_x64.msi installer logic been changed recently?

**Comment by mattsmacblog** [comment]
If this helps, pulling out some old versions and running the same command I get these results on an 1803 PC:

msiexec /i Teams_windows_x64.msi /qn /norestart /l*v C:\temp\log1.txt OPTIONS="noAutoStart=true"

1.2.00.27559 - Fails to install VDI Error.
1.2.00.21068 - Fails to install VDI Error.
1.2.00.17057 - Fails to install VDI Error.
1.2.00.1758 - Installs, no errors...

**Comment by scanum** [comment]
@mattsmacblog thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
