### ISSUE TITLE
RWDC 

### ISSUE THREAD

**Issue by tiagoroxo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3275]
Statment:
**"Can you have read-only domain controllers in these environments? Sure, as long as there are also writable domain controller available."**

Request:
Can you please edit the document and explicit say: If the RWDC must be available in the same site or available in any other site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 854766da-e557-2338-0aea-262e67a0b984
* Version Independent ID: 20b49404-62d7-83f8-118d-b8189b87da0b
* Content: [Environmental requirements for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/environmental-requirements#AD)
* Content Source: [Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/environmental-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/environmental-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@tiagoroxo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LanaChin** [comment]
Updated (thanks for your input, @tiagoroxo), and merged (thanks @dariomws).
