### ISSUE TITLE
Gerenciar Licenças

### ISSUE THREAD

**Issue by Mariaap84392498** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3276]
[Insira comentários aqui] Gerenciar licenças Produtos 

---
#### Detalhes do documento $ true 

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: a9f904e5-d015-70b0-b809-9b0b62931ab5
* Version Independent ID: aa59fcc6-0a6d-c82f-6b5e-ffb85e08ea8a
* Content: [Gerenciar equipes durante a transição para o novo centro de administração do Microsoft Teams](https://docs.microsoft.com/pt-br/MicrosoftTeams/manage-teams-skypeforbusiness-admin-center#feedback)
* Content Source: [Teams/manage-teams-skypeforbusiness-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-teams-skypeforbusiness-admin-center.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by Mariaap84392498** [comment]
Gerenciar Licenças Produtos
In version $ true visa our MasterCar da forma de pagamento, cuja equipes durante a transição dos serviços tais como: locatários; reuniões; nuvens... usuários do Office 365 na precisão do Portal de Administração do Escritório 365.

**Comment by scanum** [comment]
@Mariaap84392498 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
