### ISSUE TITLE
Need information to understand Collocated Database.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#328]
It would be very helpful if collocated databases are defined and given examples of when someone would have collocated databases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3de48a6d-4cce-eaee-d9e8-7e001d890fea
* Version Independent ID: 3e2ad9ee-3b50-58a9-b78e-8db14387cf29
* Content: [Patch or update a Back End Server or Standard Edition server in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/manage/topology/patch-or-update-a-back-end-or-standard-edition-server)
* Content Source: [Skype/SfbServer/manage/topology/patch-or-update-a-back-end-or-standard-edition-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/topology/patch-or-update-a-back-end-or-standard-edition-server.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by jantoney** [comment]
In regards to Archiving or Monitoring databases. If you open SQL Server Management Studio, you should be able to connect to your default \RTC SQL server instance. If you have Archiving or Monitoring databases then there will also be other instances for each one. \ARCHIVE & \MONITOR respectively.
Hopefully this will help anyone else that comes across this. Took me a while just coming into the S4B world!
