### ISSUE TITLE
Hybrid Azure Active Directory Endpoints Missing

### ISSUE THREAD

**Issue by joaomanuelpinto** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3280]
Hello Team!
The endpoints for hybrid Azure Active Directory are not present in these documents
(https://docs.microsoft.com/en-us/azure/active-directory/devices/hybrid-azuread-join-manual
https://enterpriseregistration.windows.net
https://login.microsoftonline.com
https://device.login.microsoftonline.com)

Can you update the documentation please?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96088236-4cde-fe10-9023-67f3d339bdbe
* Version Independent ID: 2f4cb807-2a4d-1165-836d-7c2c688b1a2c
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/microsoftteams/office-365-urls-ip-address-ranges#feedback)
* Content Source: [Teams/Office-365-URLs-IP-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-URLs-IP-address-ranges.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@joaomanuelpinto  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @joaomanuelpinto, thank you for your feedback.

I see them here:
https://docs.microsoft.com/office365/enterprise/urls-and-ip-address-ranges

**Comment by scanum** [comment]
@joaomanuelpinto 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
