### ISSUE TITLE
Reference to OrgAA is outdated

### ISSUE THREAD

**Issue by thomasbinder** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3281]
You might want to update "Organizational Auto Attendant (the replacement for auto attendant in Exchange Online UM) isn't available at GA but will be available later in 2018."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29e6436f-d73b-6ccb-c7ca-2d9e42648b6e
* Version Independent ID: 8ac96788-c9e6-9f4b-0d9f-0966bb6a012f
* Content: [Plan for Skype for Business Server and Exchange Server migration](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-um-migration#feedback)
* Content Source: [Skype/SfbHybrid/hybrid/plan-um-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/plan-um-migration.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@thomasbinder  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @thomasbinder, thank you for your feedback.

I replaced this line with Cloud Auto Attendant.

**Comment by scanum** [comment]
@thomasbinder 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
