### ISSUE TITLE
Update including Microsoft Authenticator.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#329]
Smart card is not the only dual authentication method.  Microsoft Authenticator is not even mentioned here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dbec130-a914-89ce-c710-e93723b5a78f
* Version Independent ID: c800233f-de33-6607-0e6b-4cac86c51291
* Content: [Use two-factor authentication with Skype for Business client and Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/manage/authentication/use)
* Content Source: [Skype/SfbServer/manage/authentication/use.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/authentication/use.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.
