### ISSUE TITLE
How to query PSTN usage report using PowerBI or Powershell

### ISSUE THREAD

**Issue by floydpreyes** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3293]
Is this report accessible via PowerBI or Powershell so we can automate the delivery to managers and stakeholders without the need of going into the admin console? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ad0c889-56d5-35fe-de15-177b6d922d07
* Version Independent ID: e4363647-33e1-b665-5881-169fb619a5b3
* Content: [Microsoft Teams PSTN usage report](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/pstn-usage-report#feedback)
* Content Source: [Teams/teams-analytics-and-reports/pstn-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/pstn-usage-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@floydpreyes Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by floydpreyes** [comment]
Appreciate this Manuela @scanum :) our data team has informed me that accessing it via API will also work for them, if MS can somehow allow that as well.

**Comment by TokyoScarab** [comment]
@floydpreyes  Thank you for raising this issue. I will be looking into it.

**Comment by floydpreyes** [comment]
thank you @tokyoscarab, please let me know how you go so I can inform our team to start working on it once accessible. We moved from on-premises PSTN to Teams and we used to have an automated reporting solution that tracks individual calls received/made per staff, we need to provide the same functionality to our internal managers as they are requesting for it.

**Comment by TokyoScarab** [comment]
@LanaChin From what I've been able to find, it doesn't appear that Teams PSTN usage reports are accessible through PowerShell or PowerBI as of yet. Can you verify that? Do you know if it's being worked on or will be implemented in the future?

**Comment by scanum** [comment]
@LanaChin Hi Lana, could you please help with this issue? Thanks!

**Comment by darque808** [comment]
This is also something of interest to me.  Until it was deprecated in 2018, it was possible to extract PSTN usage metrics using the Powershell cmdlet "Get-CsPSTNUsageDetailReport", and from what I've gathered there is no equivalent/replacement.

**Comment by LanaChin** [comment]
Pinged PMs.

**Comment by LanaChin** [comment]
@floydpreyes, @TokyoScarab, @darque808 - thanks for your question. I reached out to the PM and received confirmation that the PSTN usage report isn't available through PowerShell. And, currently, there's no plans for availability through PowerShell.

**Comment by OzakaMax** [comment]
Hello. I think what the community needs is a method to extract the PSTN usage data grammatically, rather than through the console.
What does Microsoft recommend as a way to achieve this, ideally also as a schedule?

**Comment by SanderSade** [comment]
Beta version of PSTN usage report in Graph is now available - see https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta
