### ISSUE TITLE
Installing Microsoft Teams does not install the add-in in Outlook 2019

### ISSUE THREAD

**Issue by hex64dbg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3298]
Installing Microsoft Teams does not install the add-in in Outlook 2019.
I am using Windows 10 and Office Pro Plus 2019

I followed these instructions : https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook

- I launched the Microsoft Teams installer as administrator
- I tried uninstalling / reinstalling both Microsoft Teams and Office pro plus 2019
- I did not install Office from the Microsoft Store, it was downloaded from https://my.visualstudio.com/

![image](https://user-images.githubusercontent.com/3956685/67762013-be5d0c80-fa44-11e9-8ac1-59394752019f.png)

**Comment by scanum** [comment]
@hex64dbg Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@hex64dbg Thank you for raising this issue. I will be looking into it.

**Comment by TokyoScarab** [comment]
@hex64dbg Is there any more information you can provide on the steps taken? I would also suggest opening a ticket with [Microsoft Support](https://support.microsoft.com) and report back with what you find. If there's something helpful that can improve the documentation, I would love to hear about it!

**Comment by scanum** [comment]
@hex64dbg We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
