### ISSUE TITLE
Wrong Link for Shared Management Objects for SQL Server 2014 SP2

### ISSUE THREAD

**Issue by thomasbinder** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3299]
The link for "Shared Management Objects for SQL Server 2014 SP2" points to the not SP2 version. Correct link is: https://www.microsoft.com/en-us/download/details.aspx?id=53164

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8abfab81-725e-2c4c-6409-d796b82ee5b1
* Version Independent ID: 5f506445-eed0-3e0c-2979-5e20a13257c9
* Content: [Disable TLS 1.0/1.1 in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/manage/topology/disable-tls-1.0-1.1#prerequisites-and-process)
* Content Source: [Skype/SfbServer/manage/topology/disable-tls-1.0-1.1.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/topology/disable-tls-1.0-1.1.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@thomasbinder Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@thomasbinder Thank you for raising this issue. I will be looking into it.

**Comment by LanaChin** [comment]
Merged changes. Thank you.
