### ISSUE TITLE
Definition of "Users synced and homed online" is not accurate in User statistics and organization information

### ISSUE THREAD

**Issue by naminakao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#33]
Based on [ICM 43772294](https://icm.ad.msft.net/imp/v3/incidents/details/43772294/home) , the provisioning (OCDM) team says the definition of “Users synced and homed online” is hybrid users (customers that have an on-prem SfB deployment; some users are on-prem and some online, but this filter only shows online users).
However currently  ["How to change Skype for Business Online user statistics" ](https://docs.microsoft.com/en-us/skypeforbusiness/set-up-skype-for-business-online/user-statistics-and-organization-information) page says  “This is the number of Skype for Business Online users who are synchronized from an on-premises Active Directory.”

**Comment by tonysmit** [comment]
I have fixed it. Thanks for the feedback. In the future, you can click the Edit button and it will submit a pull request. I do appreciate the details though. Thanks.
