### ISSUE TITLE
Microsoft Phone System direct routing in GCC High

### ISSUE THREAD

**Issue by steverlabs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3306]
As per the M365 Roadmap, Microsoft Phone System direct routing is available now in GCC High. https://www.microsoft.com/en-us/microsoft-365/roadmap?featureid=54236

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eab6a21-5773-fdba-1cad-c282e66556d7
* Version Independent ID: 9b19ed7d-85f1-9f5e-b320-1749b414cd1b
* Content: [Plan for Microsoft 365 Government - GCC High deployments - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/plan-for-government-gcc-high#feedback)
* Content Source: [Teams/plan-for-government-gcc-high.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-for-government-gcc-high.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@steverlabs Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@steverlabs Thank you for raising this issue. I will be looking into it.

**Comment by scanum** [comment]
@steverlabs Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
