### ISSUE TITLE
Provisioning logic and example

### ISSUE THREAD

**Issue by hsbsandrecv** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3308]
May I suggest the following changes to the Provisioning logic and example:

Carriers only need to set up and manage a single trunk (carrier trunk in the carrier domain), using the Set-CSOnlinePSTNGateway command. In the example above it is customers.adatum.biz;
In the customer tenant, the carrier need only to add the derived trunk FQDN to the voice routing policies of the users. There is no need to run New-CSOnlinePSTNGateway for a trunk.
The derived trunk, as the name suggests, inherits or derives all the configuration parameters from the carrier trunk. Examples:
Customers.adatum.biz – the carrier trunk which needs to be created in the carrier tenant.
Sbc1.customers.adatum.biz – the derived trunk in a customer tenant that does not need to be created in PowerShell. You can simply add the name of the derived trunk in the customer tenant in the online voice route, after enabling at least one user with that customer carrier subdomain, without having to create a PSTNGateway on customer Tenant
for example: (on customer Tenant)
Set-CsUser -Identity "sbc@sbc1.customers.adatum.biz" -EnterpriseVoiceEnabled $true -HostedVoiceMail $true -OnPremLineURI tel:&lt;E.164 phone number&gt;
Set-CsOnlinePstnUsage -Identity Global -Usage @{Add="Example"}
New-CsOnlineVoiceRoute -Identity "Voice Route" -NumberPattern ".*" -OnlinePstnGatewayList sbc1.customers.adatum.biz -Priority 1 -OnlinePstnUsages "Example"
Carrier will need to setup DNS record resolving derived trunk FQDN to carrier SBC ip address.
Any changes made on a carrier trunk (on carrier tenant) is automatically applied to derived trunks. For example, carriers can change an SIP port on the carrier trunk, and this change applies to all derived trunks. New logic to configure the trunks simplifies the management as you don’t need to go to every tenant and change the parameter on every trunk.
The options are sent only to the carrier trunk FQDN. The health status of the carrier trunk is applied to all derived trunks and is used for routing decisions. Find out more about Direct Routing options.
The carrier can drain the carrier trunk, and all derived trunks will be drained as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure a Session Border Controller for multiple tenants](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants#feedback)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@hsbsandrecv Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@hsbsandrecv Thank you for raising this issue. I will be looking into it.

**Comment by TokyoScarab** [comment]
@CarolynRowe What are your opinions on these suggested changes? After comparing the differences, there are some smaller changes they suggest, but I'm not 100% sure if they would mandate a change in the documentation. I would appreciate your more experienced view on this. Thank you!

**Comment by scanum** [comment]
@CarolynRowe Could you please help us on this issue? thanks!

**Comment by scanum** [comment]
@CarolynRowe Could you please help us on this issue? thanks!

**Comment by CarolynRowe** [comment]
It is difficult for me to view what all the suggested changes are given how the changes were submitted.  I'm going to close this issue.  If the submitter would like to follow up with me, please contact crowe@microsoft.com.
