### ISSUE TITLE
MS Teams Channel folders not automatically connected anymore on non-English SP sites

### ISSUE THREAD

**Issue by advdberg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3310]
Copy of/Reference to [SP DEV Issue 4839](https://github.com/SharePoint/sp-dev-docs/issues/4839) while it probably has more to do with MS Teams than SharePoint, but in the end it affects both.

Summary: previously Channels were automagically connected to folders with the same name in the Shared Documents library. Since last monday (28th of october) this is no longer working in non-enlish, MS Team connected, Team sites. This causes the issue that you cannot provision channels and providing default folder structures in a fully automated and unattended scenario. This is a real show-stopper for us and our provisioning solutions.

@Jthake-msft any idea? Maybe changes are pushed to MS Teams since last monday causing this?

**Comment by advdberg** [comment]
@yannickre I saw you did a lot with MS Teams governance and provisioning, do you have an advice on how to get the right persons informed about this issue?

**Comment by YannickRe** [comment]
Replied on the other thread, pretty sure it makes more sense over there.

**Comment by advdberg** [comment]
Will close this issue while we still have a discussion about the use case in the original one.
