### ISSUE TITLE
CQD - Network Insert Statements Missing NetworkRange

### ISSUE THREAD

**Issue by kevincallanan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3312]
Can you please update the Network Insert Steps to include setting the Network Range. 

Many of the networks I use are not /24, the documentation was limited online on how to account for this. I've been setting this value to a int of 22, 24, 25 depending on the subnet mask

**Comment by scanum** [comment]
@kevincallanan Please link the document you are referring to.

**Comment by kevincallanan** [comment]
https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/call-quality-dashboard/deploy-0

Section is called Import Subnets - this does not show how to add or what format is needed if you want to include the netmask. The table has a column called NetworkRange.

Thanks.

Kevin
845.222.7045
kevin.callanan@outlook.com
________________________________

**Comment by TokyoScarab** [comment]
@kevincallanan Thank you for raising this issue. I will be looking into it.

**Comment by TokyoScarab** [comment]
@kevincallanan I don't know if you had looked into [this](https://docs.microsoft.com/skypeforbusiness/management-tools/call-quality-dashboard/use) page, but I believe it should have the information you are looking for. If it does, please follow up and I can make clearer changes to the documentation directing to this information, thanks!

**Comment by kevincallanan** [comment]
thanks @TokyoScarab  - this seems to provide the detail I was looking for.

**Comment by kevincallanan** [comment]
Looks like I closed this by accident. This has the detail if this can be pointed to in the main doc or if the SQL example can be adjusted to include subnet as an option that would help.

**Comment by LanaChin** [comment]
Change merged. Thanks.

**Comment by kevincallanan** [comment]
Shouldn't the example SQL update have the subnet set to 24 not 32? 
This is the example given:
VALUES ('172.16.254.0',32,0,1,'2015-11-11')

but it should be VALUES ('172.16.254.0'**_,24_**,0,1,'2015-11-11') as 32 would mean only a single Host not the full class C
