### ISSUE TITLE
Translation from EN to PT

### ISSUE THREAD

**Issue by ddaanniieell9** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3313]
Islands mode was translated as McDonald instead of Ilhas.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 49921e8a-55ac-f547-d4e2-d329f5089c2e
* Version Independent ID: 91c3433a-3684-95cd-3426-4a5877b33106
* Content: [Orientações de migração e interoperabilidade para organizações que usam o Teams em conjunto com o Skype for Business](https://docs.microsoft.com/pt-br/microsoftteams/migration-interop-guidance-for-teams-with-skype#feedback)
* Content Source: [Teams/migration-interop-guidance-for-teams-with-skype.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/migration-interop-guidance-for-teams-with-skype.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ddaanniieell9 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@ddaanniieell9 Thank you for raising this issue. I will be looking into it.

**Comment by TokyoScarab** [comment]
@scanum  @LanaChin Their issue does check out and "McDonald" is in multiple places in the link they provided. Sadly, I do not have the appropriate permissions to make edits for non-English pages. I also feel those changes should be made by the Doc group that handles the Portuguese section of the Docs. I would appreciate any help in bringing this issue to their attention.

**Comment by scanum** [comment]
@LanaChin Could you please help out with this issue? Thanks!

**Comment by LanaChin** [comment]
Reached out to localization contact.

**Comment by TinaMcN** [comment]
@OfficeGlobal please uplift this topic to human translation for Portuguese.

**Comment by OfficeGlobal** [comment]
@TinaMcN working on a fix (Bug 3817004)

**Comment by OfficeGlobal** [comment]
@ddaanniieell9 , @TinaMcN the article has been HumanTranslated and published live

**Comment by LanaChin** [comment]
Thank you @OfficeGlobal. Closing this issue.
