### ISSUE TITLE
Translation error from EN to ES

### ISSUE THREAD

**Issue by ddaanniieell9** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3314]
Islands mode was translated as Logra (Achieve in EN) instead of Islas.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ vinculación de problemas de GitHub.*

* ID: 49921e8a-55ac-f547-d4e2-d329f5089c2e
* Version Independent ID: 91c3433a-3684-95cd-3426-4a5877b33106
* Content: [Guía de migración e interoperabilidad para organizaciones que usan Teams y Skype Empresarial](https://docs.microsoft.com/es-mx/microsoftteams/migration-interop-guidance-for-teams-with-skype)
* Content Source: [Teams/migration-interop-guidance-for-teams-with-skype.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/migration-interop-guidance-for-teams-with-skype.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ddaanniieell9 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@ddaanniieell9 Thank you for raising this issue. I will be looking into it.

**Comment by TokyoScarab** [comment]
@scanum @LanaChin This issue is similar to another issue I have looked. This is the same page but a different language (Spanish instead of Portuguese). As said, I don't seem to have the appropriate permissions to edit the non-English pages. Any way of contacting the appropriate language team on this would be best.

**Comment by scanum** [comment]
@LanaChin Hi Lana, could you please help with this? Thanks

**Comment by TinaMcN** [comment]
@OfficeGlobal please uplift this topic to human translation for Spanish.

**Comment by OfficeGlobal** [comment]
@TinaMcN working on a fix (Bug 3817004)

**Comment by OfficeGlobal** [comment]
@ddaanniieell9 , @scanum  the article was HumanTranslated for PTB , ENS and published live

**Comment by LanaChin** [comment]
Thank you @OfficeGlobal. Closing this issue.
