### ISSUE TITLE
Translation error from EN to PT and SP

### ISSUE THREAD

**Issue by ddaanniieell9** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3315]
PT - Islands mode was translated as McDonald instead of Ilhas.
ES - Islands mode was translated as Logra instead of Islas.

EN - Islands
PT - Ilhas
SP - Islas

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 006dc464-2228-0d91-8726-223770c91411
* Version Independent ID: 28877a22-b558-4da6-551b-9bcd9bac96c4
* Content: [Atualização do Microsoft Teams do Skype for Business](https://docs.microsoft.com/pt-br/microsoftteams/upgrade-and-coexistence-of-skypeforbusiness-and-teams#feedback)
* Content Source: [Teams/upgrade-and-coexistence-of-skypeforbusiness-and-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-and-coexistence-of-skypeforbusiness-and-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ddaanniieell9 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@ddaanniieell9 Thank you for raising this issue. I will be looking into it.

**Comment by TokyoScarab** [comment]
@scanum @LanaChin This issue from the other 2 I have examined is the same here just a different page. Hopefully we can get this all sorted out and get a hold of the appropriate language groups to fix this.

**Comment by scanum** [comment]
@LanaChin could you please help with this? Thanks

**Comment by LanaChin** [comment]
Reached out to localization contact.

**Comment by LanaChin** [comment]
Reached out to localization contact.

**Comment by TinaMcN** [comment]
@OfficeGlobal please uplift this topic to human translation for Spanish + Portuguese.

**Comment by OfficeGlobal** [comment]
@TinaMcN working on a fix (Bug 3817004)

**Comment by OfficeGlobal** [comment]
@ddaanniieell9 , @TinaMcN the article was HumanTranslated for PTB, ESN and published live

**Comment by LanaChin** [comment]
Thank you @OfficeGlobal. Closing this issue.
