### ISSUE TITLE
Typo PSNT

### ISSUE THREAD

**Issue by AlSmithAU** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3316]
Second last Paragraph ends "select PSNT Usage.", should be PSTN Usage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12597063-548f-8e0c-dcdc-11b98ea1601e
* Version Independent ID: 3c864a67-3a57-c810-7c75-cfddefc84bc7
* Content: [Phone System Direct Routing](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-call-notifications#feedback)
* Content Source: [Teams/direct-routing-call-notifications.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-call-notifications.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@AlSmithAU Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@AlSmithAU Thank you for raising this issue. I will be looking into it.

**Comment by CarolynRowe** [comment]
This was fixed.  Closing this issue.
