### ISSUE TITLE
Need help connecting contacts between Skype and SfB.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#332]
Facing problem with connecting contact from normal Skype to Skype for business. Its not searching by normal Skype ID. Appreciate your support if you suggest some solution. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3e9b04c-e93b-7ea5-4ac7-39276428241e
* Version Independent ID: a715ee2f-c518-ffd7-1d2f-3faf264877e9
* Content: [Deploy hybrid connectivity between Skype for Business Server and Skype for Business Online](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-hybrid-solutions/deploy-hybrid-connectivity/deploy-hybrid-connectivity)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/deploy-hybrid-connectivity/deploy-hybrid-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/deploy-hybrid-connectivity/deploy-hybrid-connectivity.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by jambirk** [comment]
https://support.skype.com/en/faq/FA12315/can-i-contact-skype-for-business-users-from-skype may be helpful.

**Comment by nsshommo** [comment]
This is helpful. Thanks.
