### ISSUE TITLE
No IPV6?

### ISSUE THREAD

**Issue by dbeyzad** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3320]
Why no IPV6?

**Comment by scanum** [comment]
@dbeyzad Could you please state the documentation you are referring to?

**Comment by TokyoScarab** [comment]
@dbeyzad Thank you for raising this issue. I will be looking into it.

**Comment by TokyoScarab** [comment]
@dbeyzad Yea, could you please mention the page of documentation you are referring to as well as the specific issue you are referring to, thank you.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
