### ISSUE TITLE
unable to do Group chat with external users

### ISSUE THREAD

**Issue by sudheerpsg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3323]
Issue description: When we click on "New Chat" and type in external email id, it's starting the chat right away and not allowing to add another email id for Group chat. This is observed only with External users in both web client, and desktop client.

**Comment by scanum** [comment]
@sudheerpsg thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
