### ISSUE TITLE
Assign Licenses step appears to need updating

### ISSUE THREAD

**Issue by troyphil** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3326]
Step 5 of the final list of steps includes "In Assign licenses, select Skype for Business (Plan 2) or Skype for Business (Plan 3)...You'll have to use a Plan 3 license if you want to use Enterprise Voice on Microsoft Teams Rooms", but we had difficulty trying to acquire these licenses. 

Based on https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/skype-room-systems-v2 it seems that the license required is 'Microsoft Room SKU'. The CSP pricelist includes 'Meeting Room' and 'Meeting Room without Audio Conferencing' - not sure if these are equivalent to Plan 3 and Plan 2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee417633-3d52-646b-2ef0-94f71535db75
* Version Independent ID: 527bb7f0-b4a7-108c-6f86-8fadced63b86
* Content: [Deploy Microsoft Teams Rooms with Exchange Online](https://docs.microsoft.com/en-us/microsoftteams/room-systems/with-exchange-online#feedback)
* Content Source: [Teams/room-systems/with-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/with-exchange-online.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@troyphil Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@troyphil "Meeting Room SKU" referes to Skype for Business online, not Skype for Business Server.

Step 5 from [the article you mentioned](https://docs.microsoft.com/en-us/microsoftteams/room-systems/with-exchange-online#feedback) refers to Skype for Business Server - "**Assign a Skype for Business Server license** to your Microsoft Teams Rooms account", so the corresponding license from the [second article](https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/skype-room-systems-v2) would be one of these:

![image](https://user-images.githubusercontent.com/41186174/72069516-fd82c600-32ef-11ea-898a-6e68204609a5.png)

**Comment by scanum** [comment]
@troyphil Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by troyphil** [comment]
So shouldn't step 5 of this article be updated with the appropriate license
names from the other article?

**Comment by VLG17** [comment]
@troyphil you are right. I've added a note pointing to the article you mentioned, where the newer licenses are described. This way, people who have "older" licenses still can relate to the information about Plan 2 and 3.
