### ISSUE TITLE
The Script Does not delete Files from Teams folder when Run in system context as Current user may not have Admin permissions to Uninstall / Install MSI.

### ISSUE THREAD

**Issue by SarveshDongare** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3333]
I had a few scenarios, where this script does not work when pushed from SCCM under System Context. They could not run it from Current / user context as the users do not have Admin permissions.

Can we generalize this script for all purposes like below:

try
{
    Stop-Process -Name Teams -Force 

    Start-Process  msiexec.exe '/x {731F6BAA-A986-45A4-8936-7C3AAAAA760B} /passive /norestart'-wait

    $users = Get-ChildItem C:\Users
    foreach ($user in $users){
    $folder = "$($user.fullname)\AppData\Local\Microsoft\Teams"

       If (Test-Path $folder) {
 
       Remove-Item -Path $folder -Recurse
   }
}
catch
{
    Write-Error -ErrorRecord $_
    exit /b 1
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c642df17-1656-7c29-9fc3-04f70689f902
* Version Independent ID: 63bef712-cfb2-9efc-0b62-f68b0968b84c
* Content: [PowerShell Script Sample - Assists with Microsoft Teams Deployment Clean Up](https://docs.microsoft.com/en-us/microsoftteams/scripts/powershell-script-teams-deployment-clean-up#feedback)
* Content Source: [Teams/scripts/Powershell-script-teams-deployment-clean-up.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/scripts/Powershell-script-teams-deployment-clean-up.md)
* Service: **msteams**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@SarveshDongare Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by ChrisKibble** [comment]
I think @SarveshDongare is on the right path.  I tweaked that script a bit so that a failure in one profile doesn't stop it from going through the rest, to not make assumptions on where the user profiles are stored, and to also remove the Teams shortcut from the Start Menu.

```powershell
$returnError = $false

If(Get-Process Teams -ErrorAction SilentlyContinue) {
    Try {
        Stop-Process -Name Teams -Force -ErrorAction Stop
    } Catch {
        Write-Error -ErrorRecord $_
        exit 1   
    }   
}

Try {
    Start-Process msiexec.exe '/x {731F6BAA-A986-45A4-8936-7C3AAAAA760B} /passive /norestart' -Wait
} Catch {
    Write-Error -ErrorRecord $_
    exit 1
}

$profilePath = Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList" -Name ProfilesDirectory | Select-Object -ExpandProperty ProfilesDirectory

foreach ($user in (Get-ChildItem $profilePath -Directory)) {
    
    ## Remove Teams Folder
    $teamsFolder = Join-Path $user.FullName -ChildPath "AppData\Local\Microsoft\Teams"
    If (Test-Path $teamsFolder -ErrorAction SilentlyContinue) {
        Try {
            Remove-Item -Path $teamsFolder -Recurse -Force -ErrorAction Stop
        } Catch {
            Write-Error -ErrorRecord $_
            $returnError = $true
        }
    }

    ## Remove Teams Shortcut
    $teamsShortcut = Join-Path $user.FullName -ChildPath "\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Microsoft Corporation\Microsoft Teams.lnk"
    If(Get-ChildItem $teamsShortcut -ErrorAction SilentlyContinue) {
        Try {
            Remove-Item -Path $teamsShortcut -Force -ErrorAction Stop
        } Catch {
            Write-Error -ErrorRecord $_
            $returnError = $true
        }
    }



}

If($returnError) {
    exit 1
}

```

**Comment by rdoloto** [comment]
This is great we are also seeing that corruption or incomplete date in HKCU keys for Teams will prevent individual users not be able to install the applications. Deleting following HKEY_CURRENT_USER\Software\Microsoft\Office\Teams\fixes this issue

**Comment by scanum** [comment]
@SarveshDongare Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by SarveshDongare** [comment]
Is this fixed? I don’t see the script modified on Docs?

**Comment by kenwith** [comment]
Let's check if @ninadara updated based on feedback above. I agree that based on the history I don't see an update either. I will shoot an email so he is aware too.

**Comment by scanum** [comment]
@ninadara Any updates on the following issue? Thanks!

**Comment by LolaJacobsen** [comment]
I'm going to delete this script. The owner has moved to a different role.
