### ISSUE TITLE
Chrome NOT "fully" supported

### ISSUE THREAD

**Issue by mtnsec** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3340]
If I try to place a voice call using Teams in Chrome 78 to a single user, I get the error "This feature isn't available yet for your browser. Try the web app with Microsoft Edge or Google Chrome, or switch to the desktop app."

However, if I place a voice call to a group of users it works fine.

When will calls to single users be supported too?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#feedback)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@mtnsec  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @mtnsec, thank you for your feedback.

I have been testing and I can make calls from Chrome 79 to a single user chat. Also with Edge Chromium.
With Firefox I get the message you experienced.

**Comment by scanum** [comment]
@mtnsec Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
