### ISSUE TITLE
Update article request

### ISSUE THREAD

**Issue by aeb5005** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3344]
"Currently, users can't play video or share their screen in a Teams meeting if they're using Google Chrome."

This is no longer an accurate statement, see https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#browsers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams#feedback)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@aeb5005  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @aeb5005, thank you for your feedback.

The article was updated on November 12 and now this information is in place.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
