### ISSUE TITLE
Screen control

### ISSUE THREAD

**Issue by aeb5005** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3345]
Hi, is it possible to give or request control when screen sharing using any combination of browsers and app? This would be for external users, re: external customer screen sharing and giving control to me. The external customer would not have a Teams account or office 365. 

Screen sharing using chrome external customer to me is confirmed working. I believe an admin could enable the right policy so the external customer would have the give / request control buttons but I am not 100% on that. Please let me know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#browsers)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@aeb5005  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by J-Fedor** [comment]
Yes, it doesn't appear to be "fully supported" as noted above - there isn't screen control capability when using the browser.  Might need to change the wording or provide a definition of "fully supported".  thanks.

**Comment by aeb5005** [comment]
Following up on this. I had an internal MS incident to try and determine if my inability to give/take control when myself or the user on the other end was using any browser was determined by someone (I could dig up the team) to be a feature gap NOT a bug. 

Thanks for the follow up! I submitted a feature request, having this would be amazing.

**Comment by J-Fedor** [comment]
Thanks - would be good to have the docs above note that "fully supported" doesn't mean "fully featured" then, and maybe note what the known gaps are so expectations can be set.

**Comment by dariomws306** [comment]
Hi @aeb5005 and @J-Fedor, thank you for your feedback.

@LolaJacobsen What do you think? Screen sharing when browsers are involved isn't supported, even with Chromium browsers.

**Comment by scanum** [comment]
@LolaJacobsen Following up on this issue. Please let us know if you can help us with next steps. Thanks!

**Comment by LolaJacobsen** [comment]
@vinbelms starting with you - since the Q involves granting/taking control during sharing with external users.

**Comment by LolaJacobsen** [comment]
Ping'd PM @vinbelms this morning.

**Comment by LolaJacobsen** [comment]
Ping'd PMs (vinbelms & Surbhi Lohia)

**Comment by LolaJacobsen** [comment]
Checking with PM Rajiv Ramaiah.

**Comment by LolaJacobsen** [comment]
@aeb5005 we've updated our documentation to note the limitation around giving/taking control when participants are on Teams in the browser. See the note at the bottom of this section:
https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#browsers

1 To give and take control of shared content during sharing, both parties must be using the Teams desktop client. Control isn't supported when either party is running Teams in a browser. This is due to a technical limitation that we're planning to fix. To learn more, read Allow a participant to give or request control.
