### ISSUE TITLE
Incorrect Endpoint sample 

### ISSUE THREAD

**Issue by bilginbaldji** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3346]
Endpoint file instructions define 7 columns, yet the field order and example are with 6 fields which is incorrect:
"There must be seven columns for each row and the columns must be in the following order:

Field order:
EndpointName, EndpointModel, EndpointType, EndpointLabel1, EndpointLabel2, EndpointLabel3"

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb8d8b48-561b-6817-1ce0-4b2aedc261a8
* Version Independent ID: dfd5cf4a-509a-3ed1-0267-6281c251fbef
* Content: [Turn on and use Call Quality Dashboard](https://docs.microsoft.com/en-gb/microsoftteams/turning-on-and-using-call-quality-dashboard#feedback)
* Content Source: [Teams/turning-on-and-using-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/turning-on-and-using-call-quality-dashboard.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@bilginbaldji  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @bilginbaldji, thank you for your feedback.

I'm adding a column (Endpoint Make).

**Comment by scanum** [comment]
@bilginbaldji Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
