### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by kaosaxis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3349]
This information should also exist here: https://docs.microsoft.com/en-us/microsoftteams/what-is-phone-system-in-office-365

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6891495-01c6-117b-c28b-28232782ba74
* Version Independent ID: 1c23b35a-e9ba-ffdd-9baa-a3f83f4ed9ca
* Content: [Phone System–Virtual User licenses ](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/virtual-user#feedback)
* Content Source: [Teams/teams-add-on-licensing/virtual-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/virtual-user.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@kaosaxis  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @kaosaxis, thank you for your feedback.

Sorry to say but I'm not agree with you. Where would you add that information in this article?

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
