### ISSUE TITLE
Need help regarding "Check Call Quality" option.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#335]
The help page keeps telling to click "check call quality" . But there is no option to click "check call quality."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0add074-81ef-9f49-d931-070de0ec54b3
* Version Independent ID: 99e62214-9fed-40ee-e549-03711fc142e0
* Content: [Enable users for Enterprise Voice in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-enterprise-voice/enable-users-for-enterprise-voice)
* Content Source: [Skype/SfbServer/deploy/deploy-enterprise-voice/enable-users-for-enterprise-voice.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-enterprise-voice/enable-users-for-enterprise-voice.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.
