### ISSUE TITLE
Non enterprise customers

### ISSUE THREAD

**Issue by marculos** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3350]
A specific version of Windows 10 is required, and this version is only available to volume licensing customers. You can get a copy from the Volume Licensing Service Center.

Hi - we run standalone Windows 10 Pro licenses in our business so we cannot use Teams Meeting Rooms ?

**Comment by scanum** [comment]
@marculos thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
