### ISSUE TITLE
Spelling error in the license name (Phone System)

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3351]
In the 1st table in this article, it says "Phone Systems" (with "s"), but it should be "Phone System" (without "s")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses](https://docs.microsoft.com/en-us/microsoftteams/room-systems/skype-room-systems-v2)
* Content Source: [Teams/room-systems/skype-room-systems-v2.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/skype-room-systems-v2.md)
* Service: **skype-for-business-online**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@shivtorov Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LanaChin** [comment]
Merged change and closed. Thank you.
