### ISSUE TITLE
Broken list formatting in the Requirements section

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3354]
Broken list formatting in the Requirements section

>- Enable the device account with Skype for Business Server. To enable the device account your environment will need to meet the following prerequisites:
>
>  - You'll need to have Skype for Business Online (Plan 2) or higher in your Office 365 plan. The plan needs to support conferencing capability.
>  
>  - - If you need Enterprise Voice (PSTN telephony) using telephony service providers for Microsoft Teams Rooms you need Skype for Business Online (Plan 3).
>  
>  - - Your tenant users must have Exchange mailboxes.
>  
>  - - Your Microsoft Teams Rooms account does require a Skype for Business Online (Plan 2) or Skype for Business Online (Plan 3) license, but it does not require an Exchange Online license.
>
>- Assign a Skype for Business Server license to your Microsoft Teams Rooms account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91cd0219-b3b0-da60-6416-c6b5a67623e3
* Version Independent ID: 983d08b5-4a2c-838a-52eb-821045d2c9df
* Content: [Deploy Microsoft Teams Rooms with Exchange on premises](https://docs.microsoft.com/en-us/microsoftteams/room-systems/with-exchange-on-premises)
* Content Source: [Teams/room-systems/with-exchange-on-premises.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/with-exchange-on-premises.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@shivtorov Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LanaChin** [comment]
@shivtorov, thank you for your input. @dariomws306, thanks for the fix, I've merged the changes.
