### ISSUE TITLE
[Teams - Tab]:- Video continues to play after clicking Tab's back button on Ipad

### ISSUE THREAD

**Issue by LalitAgrawala004** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3355]
Hi
This issue is happening only on Ipad Teams App. I created Tab on my Team which configured to loaded one of our application video page. On a Ipad, the video is loading and playing fine. but there is  back (<) button and after clicking that button to come out tab, the video continues to play. 

I checked the same thing in Microsoft Stream app (I have account there). If I create a tab using Stream App and play a Video, it continues to play even after clicking on back arrow, Seems like tab instance not getting cleaned up properly. I am not sure. I have attached a screen shot and highlighted back button for more clarity. can you please look into it?

![image](https://user-images.githubusercontent.com/17126892/68330808-e03c3c00-00a1-11ea-92ed-31ac9748da28.png)

**Comment by scanum** [comment]
@LalitAgrawala004 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
