### ISSUE TITLE
Contact Info

### ISSUE THREAD

**Issue by CosmoDenger** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3356]
Please remove my contact information from this page for closed feedback.  This information should never make it into a ticket to be posted publicly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 451b44cf-961a-5bf5-e4b3-16b96e008dd7
* Version Independent ID: 54e706e1-aaa2-3a03-b8c6-5e96244b85ac
* Content: [Create and manage dial plans](https://docs.microsoft.com/en-us/microsoftteams/create-and-manage-dial-plans)
* Content Source: [Teams/create-and-manage-dial-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-and-manage-dial-plans.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by shivtorov** [comment]
@CosmoDenger, I see what has happened - you replied a message in that conversation by email. And have not removed your email signature from the email. Thus it became a part of your comment. Next time you should ensure to strip your contact details if you reply by email. Alternatively, you can reply via web page. I don't think Microsoft can automatically strip your personal data if you send it in your email reply. 

You should be able to edit your comments in that thread on GitHub to remove your data.

Microsoft - you should implement automatic removal of email addresses that accidentally appear in the replies submitted by email
