### ISSUE TITLE
Unclear licensing requirements

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3358]
Section "Phone System with on-premises environments" does not clearly explain licensing requirements.

What are the licensing options to use Cloud Voicemail after February 2020 for a user with:

* on-premises SFB Enterprise Voice account (PSTN calling with Skype for Business Server)
* cloud mailbox (Exchange Online)

Do we need:

1) Phone System + Exchange Online Plan 1
2) Phone System + Exchange Online Plan 2
3) just Exchange Online Plan 1
4) just Exchange Online Plan 2

or maybe something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8228f9b2-a7de-abb4-6f41-70db0b3af155
* Version Independent ID: 8fd9fafb-dd76-59a8-e609-56f06d539a31
* Content: [Set up Cloud Voicemail](https://docs.microsoft.com/en-us/microsoftteams/set-up-phone-system-voicemail)
* Content Source: [Teams/set-up-phone-system-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-phone-system-voicemail.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@shivtorov Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by shivtorov** [comment]
Just wanted to add additional scenario to this question.

What are the licensing requirements for Cloud Voicemail for an account enabled for Skype for Business Server Enterprise voice when this account is:
scenario 1: an employee account with licensed Exchange Online mailbox
scenario 2: a resource account with shared mailbox in Exchange Online

**Comment by dariomws306** [comment]
Hi @shivtorov, thank you for your feedback.

I'll try to get this information. I understand that you need Phone System + Exchange Online Plan 2, but I'll try to confirm.

**Comment by dariomws306** [comment]
The article you are looking for:
https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-cloud-voicemail

I understand that you don't need the Phone System license or add-on but I'll try to confirm, as you have an Exchange Mailbox and it's licensed for EXO.

**Comment by scanum** [comment]
@shivtorov Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
