### ISSUE TITLE
Members dont have access to files in private channels

### ISSUE THREAD

**Issue by sudheerpsg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3359]
We created a Private Channel with 2 members and the members are getting "You dont have access to these files".
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/19826518/68347368-8c365500-00ab-11ea-85fd-6d6eb352a257.png)

**Comment by scanum** [comment]
@sudheerpsg thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
