### ISSUE TITLE
Can I convert an existing channel?

### ISSUE THREAD

**Issue by kelemvor33** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3360]
I'm not fining any way to convert an existing channel to a private channel, or to convert an existing private channel to a regular channel.  Is either of those possible or planned for the future?

Also, up until now we've had to create separate teams to have private information.  I'd love to move the channels from those teams back into our main team and make them private so I can then get rid of the extra team.  Is there any way to do that or is it planned for the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels#feedback)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by tophee** [comment]
The article above states that channel cannot be converted from private to standard or vice versa. But I would also like to know whether this will change in the future.

**Comment by tophee** [comment]
I don't understand the last row in the first table (when to create a private channel) which states "Create a new team or create a new private channel in an existing team" even though there is no team that includes all members of the intended private group. Shouldn't the recommendation for this last scenario be "Create a new team"? If that is too simplistic, I guess it would be "Add missing users as guests to the most relevant team and create a private channel or create a new team".

**Comment by Anmolgan81** [comment]
We need the capability to change the exisiting channel type to public or private. Is this possible.

**Comment by alepiresv** [comment]
Very good comment. I also look forward being able to move existing channels created in a team intended to be private to a common team and then make those channels private. This will be great to clean-up unnecessary teams and make daily work way more productive.

**Comment by Anmolgan81** [comment]
This will also narrow down the number of members that we have to look in case of a disaster (that can be accidental deletion of the resource group etc, when multiple members are using same Login ID). Much needed feature.

**Comment by karenday16** [comment]
MUCH needed feature!!!!

**Comment by cfrench007** [comment]
I'm not clear why Microsoft would introduce this feature without the ability to blend what everyone has done as a work around because of the lack of the feature.  This should have been a no-brainer.  At the very minimum, there should have been a way to switch a current channel to private (one way street).  Now, all of us are going to waste more time and resources creating NEW teams or new channels and manually recreating those WIKIs and moving files.  Seems counter productive.  I sure hope Microsoft is on top of this one.

**Comment by haroldvandekamp** [comment]
Also looking for the option to convert public channel into a private channel and vice versa. Take a look at the UserVoice topics: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/38535709-convert-private-channel-to-public-channel / https://microsoftteams.uservoice.com/forums/555103-public/suggestions/38974249-make-public-channel-private

**Comment by GabK** [comment]
I'm also looking for this feature. Right now, our only option would be to move all the contents from the public channel into the newly created private channel... 

It would be a pain to go through all of them, plus you'd lose the thread history!

**Comment by scanum** [comment]
@kelemvor33 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by vladchor** [comment]
@scanum, you pointed that the issues has been resolved but I don't see the possibility to convert existing channels into private and vice versa. Would you please reopen the issue or please point out to the article stating it has been implemented! 

> @kelemvor33 Thank you for submitting feedback. We understand that this issue has been resolved.
> Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
