### ISSUE TITLE
Sitecollections not visible in SharePoint admin center? 

### ISSUE THREAD

**Issue by markgort86** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3361]
The newly created sitecollections for a private channel are not visible in the SharePoint Admin center. With the following PowerShell command "get-sposite" they are still visible. Is this working by design?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels#feedback)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@markgort86 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by kefujino** [comment]
If it isn't visible in the SharePoint admin center, many admins will not notice and they will report as a bug for service.

If this is expected behavior, please update the below public document.

https://docs.microsoft.com/en-us/microsoftteams/private-channels#private-channel-sharepoint-sites

Thank you!

**Comment by dariomws306** [comment]
Hi @markgort86 and @kefujino, thank you for your feedback.

@LanaChin Could you kindly help with this? Could we confirm this information?

Reading next information I think it has sense but I want to confirm:

"Membership to the site collection owner and member groups are kept in sync with the membership of the private channel within Teams. Any changes to the membership of Owner or Member groups in SharePoint Online will be reverted to private channel membership within four hours automatically. In scenarios where certain users need to access documents without needing to access private channel messages, add them to the Visitors group on the site or to a new group that's separate from Owners and Members.

Teams manages the life cycle of the private channel SharePoint site collection. If the site collection is deleted outside of Teams, a background job restores the site within four hours as long as the private channel is still active. If the site is deleted and hard-deleted, a new site collection is provisioned for the private channel.

If a private channel or a team containing a private channel is restored, the site collections are restored with it. If a private channel site collection is restored and it's beyond the 30-day soft delete window for the private channel, the site collection operates as a standalone site collection."

**Comment by scanum** [comment]
@LanaChin could you please help us with next steps? Thanks!

**Comment by LanaChin** [comment]
@markgort86, @kefujino, @dariomws306 - thanks for your input and feedback.  By design, private channel site collections aren't visible in the SharePoint admin center.  The private channels article, https://docs.microsoft.com/en-us/microsoftteams/private-channels#private-channel-sharepoint-sites, has been updated to clarify this.  Thank you.

**Comment by SinghHarveer** [comment]
I guess this needs to be changed again now, private channel site collections are visible in sharepoint admin center now. There is a small delay though post creating a private channel.
