### ISSUE TITLE
If all private channel owners/members leave?

### ISSUE THREAD

**Issue by Purple-Hayes** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3363]
Hi,
Hopefully I am not missing something obvious, If all the owners or members of a private channel leave, how does the Team get access to the content of the private channel?
Thank you.

**Comment by scanum** [comment]
@Purple-Hayes thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
