### ISSUE TITLE
If all private channel owners/members leave the organisation

### ISSUE THREAD

**Issue by Purple-Hayes** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3364]
Hi,
perhaps I have missed this, but can we access the content of a private channel if the owners/members os a private channel have left the organisation or Team?
Thanks for any pointers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels#feedback)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Purple-Hayes thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by M-Oberg** [comment]
This is a blocking our organization to release Private Channels. How can a Teams administrator get access to a Private channel and assign a new channel Owner if the last person in the Private Channel have left the organization?
