### ISSUE TITLE
Should Private Channels Sync automatically into Windows Explorer?

### ISSUE THREAD

**Issue by kelemvor33** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3366]
Howdy,

I use the Sync feature so that I can view my Teams files within Windows Explorer.  I created a private channel and added a file to it to see if it would show up.  It did not.  I don't know if it's supposed to or not to know if this is a bug.

I can go into the private channel's Files area and choose Open in Sharepoint and then click Sync, but I didn't do that yet because I didn't want to somehow create a double sync if it's supposed to be working.
Anyone know how this is supposed to work by chance?  My Onedrive client is showing "Processing Changes" but hasn't added the new channel...

I'll give it a bit and then try to sync just that channel manually and see what happens but I'd prefer it show up in the list by all the other channels.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by kelemvor33** [comment]
So I'm guessing they are not supposed to sync.  When I open a private channel in Sharepoint, it does not seem to be linked to the master team in any way.  If I create two private channels, they all seem to be their own separate area within Sharepoint and not associated with the others.  So to sync them, I'll have to manually add it to my sync setup.

**Comment by scanum** [comment]
@kelemvor33 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by kelemvor33** [comment]
I don't know if this is something that's Working as Intended or if it's something that needs to be resolved.  I'm kind of thinking that these private channels are not fully linked to the Team itself within Sharepoint so the desktop syncing isn't supposed to work.  I was hoping someone that knows would be able to tell me if I need to open a ticket or not...

**Comment by CITGIT** [comment]
It seems to be by design, that files from a private channel does not sync into Windows Explorer. 

Take a look at this article from Microsoft Docs:
https://docs.microsoft.com/en-us/microsoftteams/sharepoint-onedrive-interact 

where Microsoft notes this:
The architecture for private channels is different from standard channels. Each private channel has its own SharePoint site collection that's separate from the parent team site. To learn more, see Private channels in Microsoft Teams.

So you have to establish a new SharePoint sync connection from the private channel.
