### ISSUE TITLE
Statment in Step2 is not clear

### ISSUE THREAD

**Issue by moegitree** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3368]
The statments for "Admins and users in the guest inviter role can invite" and "Members can invite" are not clear. Are these two setting related or not? 
If I set "Admins and users in the guest inviter role can invite" to No and "Members can invite" to Yes, does it mean general user can invite guests while admins cannot?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams のゲスト アクセスのチェックリスト](https://docs.microsoft.com/ja-jp/microsoftteams/guest-access-checklist#feedback)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@moegitree Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @moegitree, thank you for your feedback.

They are not strictly related. If you set "Admins and users in the guest inviter role can invite" to No and "Members can invite" to Yes, I think that admin can only invite if they are members. I'll test it to confirm.

**Comment by dariomws306** [comment]
Hi @moegitree,

I have tried this and I can confirm that with this configuration a Global Admin cannot invite guest accounts. Member can do.

Thanks!

**Comment by scanum** [comment]
@moegitree Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by heymybru** [comment]
Can you clarify the following statement in Step 2 - point 4

"For guest access to work at all in Teams, you must set Members can invite to Yes."

Does this mean that Guests accessing teams will not have a full experience unless Members can invite is set to Yes.
