### ISSUE TITLE
Adding a Planner inside private channel

### ISSUE THREAD

**Issue by djlordee** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3374]
Why can't we add a Planner within a private channel?

**Comment by scanum** [comment]
@djlordee thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
