### ISSUE TITLE
Documentation missing for pinning Messaging Extensions

### ISSUE THREAD

**Issue by butchmarshall** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3376]
This documentation shows how to pin org wide Tabs but nothing about how to pin org wide Messaging Extensions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 143108bb-d6e6-48a8-a7cb-d11b89ebeaab
* Version Independent ID: 145773e2-149e-1c1c-5797-433c13f13b22
* Content: [Admin settings for apps in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/admin-settings)
* Content Source: [Teams/admin-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/admin-settings.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@butchmarshall Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @butchmarshall, thank you for your feedback.

I think it's not possible yet. You can pin apps but not messages or messaging extensions. Please, vote it here or create a new idea specific to Messaging Extensions:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/16911532-ability-to-pin-message-files-articles-shared-withi

**Comment by butchmarshall** [comment]
Thanks for the response.

FYI for anyone who just wants to force a messaging extensions installation you can do so via the graph API.

1) Use the [delta API](https://docs.microsoft.com/en-us/graph/delta-query-overview) to sync users
2) Check users have the [app installed](https://docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta) 
3) If they don't, you can [force install the app](https://docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-beta&tabs=http) using the graph API

**Comment by scanum** [comment]
@butchmarshall Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
