### ISSUE TITLE
Where the messages in private channel are saved need to be clarified 

### ISSUE THREAD

**Issue by moegitree** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3377]
For normal team channel, the messages posted are saved in the team's O365 mailbox. Since files uploaded in private channel are saved in a separated SharePoint Online site, is it the same for messages in private channel? This point is needed to be clarified in the document.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Microsoft Teams のプライベートチャネル](https://docs.microsoft.com/ja-jp/MicrosoftTeams/private-channels#feedback)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@moegitree Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@moegitree Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
