### ISSUE TITLE
When you use a Teams with a private channel as template, the private channel is not in the new Teams

### ISSUE THREAD

**Issue by Fru-LCF** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3378]
Is that a function there will come?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels#feedback)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Fru-LCF Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @Fru-LCF, thank you for your feedback.

As you noticed is not yet available and I cannot provide more information:
https://docs.microsoft.com/en-us/microsoftteams/get-started-with-teams-templates

**Comment by scanum** [comment]
@Fru-LCF Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
