### ISSUE TITLE
Dial-Out”/“Call Me At - how to disable this?

### ISSUE THREAD

**Issue by szymonslipek** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3380]
We have just enabled Teams Audioconferencing addon and now wondering how to disable this Dial-Out”/“Call Me At feature. Is there any policy? Is there maybe some GPO?

**Comment by scanum** [comment]
@szymonslipek thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
