### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3385]
OFfice 365 Business Premium

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b05e642-c4e5-f1b5-5315-d3ef1690a0cd
* Version Independent ID: 01b7e0b5-3e50-3de0-e3e9-aeeeda43da12
* Content: [Authorize guest access in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-au/MicrosoftTeams/teams-dependencies)
* Content Source: [Teams/Teams-dependencies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-dependencies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@SvenBell Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@SvenBell Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
