### ISSUE TITLE
Does give/take control work on any platform?

### ISSUE THREAD

**Issue by aeb5005** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3387]
Hello, I've been told that give/take control does NOT work on any browser and will ONLY work if a desktop applications (windows/mac/linux?/android?/ios?) is being used on both ends (client A / Client B). 

Are there any plans to extend this feature to any browsers? That's a highly desired feature.

**Comment by scanum** [comment]
@aeb5005 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@aeb5005 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by aeb5005** [comment]
@scanum I have contacted MS Core Services Engineering and they've told me that give/take control is not available through any browser. One of the Teams applications has to be used on each end for that functionality. I didn't see this reflected anywhere in the docs. I was hoping you could confirm/deny and if true update the docs as appropriate. 

I was also wondering if this was a feature is to be added in the future.

**Comment by aeb5005** [comment]
@scanum It was confirmed through a MS internal incident I raised that this was a feature gap and not a bug.
