### ISSUE TITLE
SBC Media Bypass Features

### ISSUE THREAD

**Issue by sgtdonny** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3388]
Hello at all,
I discovered problems with media bypass and using teams applications like attendants.
There is one way audio till the transfer with external users.
I investigate it with the MS Support and the conclusion was, no media bypass when you will use Applications. Bad solution and in your list it is not clear with whitch vendor it works. In my case it was AudioCodes.
Please update the SBC list with this informations or better, fix it.
Media Bypass make sense for bigger installations. Workaround is for this applications exeptions and transcoding at the moment.

**Comment by scanum** [comment]
@sgtdonny Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@sgtdonny thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
