### ISSUE TITLE
Should I be able to schedule a meeting in a private channel?

### ISSUE THREAD

**Issue by sapg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3389]
I used to have regular channels under my team and I could schedule meetings in this channels.  I've used the new private channel feature for some sensitive conversations but it doesn't seem that I can schedule meetings in these new private channels, is that intentional or is it a bug?

In my regular channels I schedule a meeting by hitting the 'meet now' icon (the little movie camera) and then select the schedule icon (calendar +).  In a private channel I don't get the schedule icon.

**Comment by scanum** [comment]
@sapg Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@sapg thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
