### ISSUE TITLE
Details for customizing the meeting invitation

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3390]
It would be helpful if documentation could provide more details about the effects of invite customization - what size of image is expected, how the invite will look like (screenshot that points out where specific items of customization go) as well as information if the image is embedded to the invite or needs to be a public, anonymous resource to work properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Manage meeting settings - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/meeting-settings-in-teams?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by JohnE2** [comment]
+1 for details on recommended size and pixels of logo. The preview function within the Teams Admin Console is nice but additional info would be greatly appreciated.

**Comment by dariomws306** [comment]
Hi @Larryngolog and @JohnE2, thank you for your feedback.

In the article you can say the next sentence:
"Create an image that's no more than 188 pixels wide by 30 pixels tall (it's quite small)."
Also:
"Store the image in a central location that everyone in your organization can access, such as a network share."

Do you think more information should be added?

Thanks!

**Comment by JohnE2** [comment]
The info about the pixel size is great.

The info about storing on a network share is something to reconsider. If the meeting invite is sent external to the organization, the image file will not be accessible if it is stored internally. In this scenario, the image file would need to be stored in a location that can be accessed anonymously and from the internet. Recommending to store this on an internal network share would not be advisable from a security standpoint.

**Comment by dariomws306** [comment]
With "Store the image in a central location that everyone in your organization can access, such as a network share." I understand that when a user in your organization send a meeting invite the image will be added to the invite from the network location and recipients don't need access the network share.

**Comment by JohnE2** [comment]
@dacowan even better! I thought it sent as a link.

**Comment by Larryngolog** [comment]
@dariomws306  the text about pixel size is helpful. 

As for the image location I have tested and the image is linked, not embeded. I have tried it on my tenant and used image hosted on SPO. Internal users can see the image only after they sign it to SPO and external users cannot, as they do not have access to the image. We also state on the Teams admin page that we need to have public site to host files used in this section.

I also suggested adding a screenshot how the invite will look like and where the parts we configure will go, something like this:
![image](https://user-images.githubusercontent.com/18740551/70698900-99f18280-1cc8-11ea-8ad2-6972d6ab97e8.png)

**Comment by dariomws306** [comment]
Ok, I will check if I can add an image to provide more information.

**Comment by scanum** [comment]
@LanaChin Hi Lana, could you please help with this issue? Thanks!

**Comment by scanum** [comment]
@@LanaChin Hi Lana, could you please help with this issue? Thanks!

**Comment by scanum** [comment]
@LanaChin Hi Lana, could you please help with this issue? Thanks!

**Comment by gobmh** [comment]
Hi everyone. The information on the images' source is clear. It shouldn't be a problem to host an image file reachable in the web. ;-) 

But have a question corresponding to this issue. Why do the settings need one hour to take effect of any changes? That is quite uncomfortable to check, if the design corresponds to our managers. Is it possible to test it different and faster?

Thanks :-)

**Comment by shashank1320** [comment]
Is it possible to customize the Teams meeting invite to display the conference ID similar to Skype invite as 
Join by Phone-
Toll Number
Conference ID

Current invite is as below
Teams Meeting URL
Toll Number
Conference ID

**Comment by shashank1320** [comment]
Is it possible to customize the Teams meeting invite to display the conference ID similar to Skype invite (with Join by Phone Text) as-
Join by Phone-
Toll Number
Conference ID

![image](https://user-images.githubusercontent.com/15531481/74523960-28da7f80-4f44-11ea-8e8d-df5f6be3a0ba.png)


Current invite is as below
Teams Meeting URL
Toll Number
Conference ID

![image](https://user-images.githubusercontent.com/15531481/74523995-3b54b900-4f44-11ea-84b3-6c9ac7791b76.png)

**Comment by shashank1320** [comment]
> Hi everyone. The information on the images' source is clear. It shouldn't be a problem to host an image file reachable in the web. ;-)
> 
> But have a question corresponding to this issue. Why do the settings need one hour to take effect of any changes? That is quite uncomfortable to check, if the design corresponds to our managers. Is it possible to test it different and faster?
> 
> Thanks :-)

Probably not that I am aware of. This is due to the Sync delays for O365 services which may take upto 24 hours sometime.

**Comment by LanaChin** [comment]
Looking into this, thank you.

**Comment by JannJJG** [comment]
Hi can we create a fixed default meeting link that can be copy and pasted in any calendar invite or pasted in an email to a client ? Or it has to be specific to "New MS Teams Meeting" when we click on our calendar only then the unique meeting link will be created.

**Comment by LanaChin** [comment]
@Larryngolog - You can use the **Preview invite** button to see a preview of your meeting invite. The article has been updated to reflect this feature.

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Larryngolog** [comment]
Thank you for your help.

**Comment by shashank1320** [comment]
> Is it possible to customize the Teams meeting invite to display the conference ID similar to Skype invite (with Join by Phone Text) as-
> Join by Phone-
> Toll Number
> Conference ID
> 
> ![image](https://user-images.githubusercontent.com/15531481/74523960-28da7f80-4f44-11ea-8e8d-df5f6be3a0ba.png)
> 
> Current invite is as below
> Teams Meeting URL
> Toll Number
> Conference ID
> 
> ![image](https://user-images.githubusercontent.com/15531481/74523995-3b54b900-4f44-11ea-84b3-6c9ac7791b76.png)

Yet to ant any response on this customization requirement.
