### ISSUE TITLE
Unprivate private channels

### ISSUE THREAD

**Issue by bmannetje** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3391]
I would like to see the option to make private channels open to everyone like a normal channel.
This way if a certain project is rounded up and everyone can have acces I don't need to add everyone.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels#feedback)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@bmannetje Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @bmannetje, thank you for your feedback.

Considering the nature of the issue, it is advised that please this feature request here:
https://microsoftteams.uservoice.com/

**Comment by scanum** [comment]
@bmannetje Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
