### ISSUE TITLE
SQL Server support for CQD

### ISSUE THREAD

**Issue by thomasbinder** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3392]
The article unclear which version of CQD supports which version of SQL server. 

https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/call-quality-dashboard/plan#call-quality-dashboard-components 

- CQD 2015 lists SQL Server 2012, SQL Server 2014, SQL Server 2016
- CQD 2019 lists SQL Server 2017, SQL Server 2019

Towards the end of the article it says:

_The following versions of SQL Server are supported:
SQL Server 2012
SQL Server 2014
SQL Server 2016
SQL Server 2017
SQL Server 2019 (Skype for Business Server 2019 CQD only)_

Can you clarify if e.g. CQD 2016 works on SQL 2016?

**Comment by scanum** [comment]
@thomasbinder Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@LanaChin Hi Lana, is this an issue that you can help us with? Thanks!

**Comment by LanaChin** [comment]
Looking into this, thanks.

**Comment by LanaChin** [comment]
Hi @thomasbinder, I've updated the article to clarify the version support for CQD and SQL Server. Thank you.
