### ISSUE TITLE
Unable to access admin center on developer license

### ISSUE THREAD

**Issue by JonasDewit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3396]
Hi,

I've got a couple of 'fake' users with Teams on an E5 Developer (without Windows and Audio Conferencing) license.

I'm able to access the 'old' admin center through the 365 admin center (Settings - Services & add-ins - Microsoft Teams). From there, when I click the link to the new Microsoft Teams & Skype for Business admin center, I'm asked to log in again and then redirected to this error page:

https://admin.teams.microsoft.com/error?code=FAILED_TO_AUTO_DISCOVER_DOMAIN

The error says : 

_Sorry, we can't sign you in._

_The domain you are trying to sign in to doesn't have any users that have a Microsoft Teams or Skype for Business Online license assigned to them. Learn more._

_Error code.: FAILED_TO_AUTO_DISCOVER_DOMAIN_

Any idea about what's wrong?

Thank you,
Kind regards,
Jonas

**Comment by scanum** [comment]
@JonasDewit thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
