### ISSUE TITLE
Create 30 private channels > delete 5 private channels > try to 5 new private channel.

### ISSUE THREAD

**Issue by abbodh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3398]
Create 30 private channels > delete 5 private channels > try to 5 new private channel.

This doesn't work? What is the time period for creating private channels once it reaches threshold limit of 30?

**Comment by scanum** [comment]
@abbodh thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
