### ISSUE TITLE
Meeting Invites do not include Conference number and conference ID

### ISSUE THREAD

**Issue by bsofd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3399]
We are running into an issue with a user whose meeting invites do not include Conference number and conference ID.

The user received an email with his conference number and pin. I have also assigned a new conference bridge number, but the invites still do not include the information.

I have tested using my assigned conference bridge number (which was the same as initially assigned to the user with the issue) and my meeting invites send the information with no issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dc173c-0c98-1b94-a2f7-0a34781c985a
* Version Independent ID: a1c44ccb-67f3-f98e-6569-f938e88ddc63
* Content: [Set the phone numbers included on invites in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-the-phone-numbers-included-on-invites-in-teams#feedback)
* Content Source: [Teams/set-the-phone-numbers-included-on-invites-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-the-phone-numbers-included-on-invites-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by bsofd** [comment]
This can be closed. It appears it was delay related and is now working as it should!

**Comment by scanum** [comment]
@bsofd Thank you for letting us know :)

**Comment by scanum** [comment]
@bsofd Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
