### ISSUE TITLE
Need info about DNS

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#340]
Please explicitly state what to do with domain.onmicrosoft.com in DNS, internally and externally. 
Do I create additional records to my on prem deployment? Does that count under what is stated as all domains?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ce52f6-cec3-8572-2a78-2f4c3419dc28
* Version Independent ID: 44e7910e-d955-1bb1-0f9c-e8047c994bdc
* Content: [Plan hybrid connectivity between Skype for Business Server and Skype for Business Online](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-hybrid-solutions/plan-hybrid-connectivity)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/plan-hybrid-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-hybrid-connectivity.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.
