### ISSUE TITLE
How to get correct details for "Devices" on SkypeConfiguration.xml

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3402]
Hi,
When testing your PowerShell command that list the audio devices perfectly. The problem is, no matter what do I write into SkypeConfiguration.xml the configuration on the settings says:
"Internal Microphone"
"Internal Speaker"

When I go to settings I could select e.g.
"Echo Cancelling Speakerphone (...."

Is the output from the PowerShell really correct for audio devices?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd52fe62-457b-c9e1-ad13-a9b1f24c9c38
* Version Independent ID: 6a8c3285-30e1-15a8-6472-f0cfe5b30e20
* Content: [Microsoft Teams Rooms maintenance and operations - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/room-systems/room-systems-v2-operations#RemotePS)
* Content Source: [Teams/room-systems/room-systems-v2-operations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/room-systems-v2-operations.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Petri-X** [comment]
I tested this with Jabra device and the device name on the PowerShell was: "Jabra SPEAK 410 USB". But it did not work on the XML until I added extra. Here is how one of the line looks when it started to work:
< MicrophoneForCommunication >Echo Cancelling Speakerphone (Jabra SPEAK 410 USB)< /MicrophoneForCommunication >
There are extra spaces added surround: "MicrophoneForCommunication" to make them visible.

But this of course gets a bit more complicated as on one of our older device I could see the current configuration is: "(**2-** Logi Group...."
How should I be able to found if there is an extra index on the name?

**Comment by dariomws306** [comment]
Hi @Petri-X, thank you for your feedback.

Could you please let me know what is the section of the document you are referencing?

**Comment by Petri-X** [comment]
This part:

invoke-command {Write-Host "VIDEO DEVICES:"....

**Comment by dariomws306** [comment]
Thanks @Petri-X.

We are here to receive feedback to improve documentation. I think that considering the nature of the issue, is a good idea to open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Petri-X** [comment]
@dariomws306 
Strange, I already told what is wrong on your documentation and the workaround for this as well. Not sure why I need to also open support ticket for this. In my mind, the correct way is to contact to original writer and ask her/him to verify this.

**Comment by dariomws306** [comment]
@LanaChin could you kindly help me with this issue?
