### ISSUE TITLE
No recurrence?

### ISSUE THREAD

**Issue by Patrick959** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3404]
Why are all features released half-baked.  Put this back in the oven and add a generous helping of recurrence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9908d77-78bc-ce88-ba84-4f1bd9fea504
* Version Independent ID: 37118dd4-d036-8da7-d750-4c9f503a370a
* Content: [Set up holidays in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/set-up-holidays-in-teams?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/set-up-holidays-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-holidays-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@Patrick959 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @Patrick959, thank you for your feedback.

This section is to improve documentation, to request new features please go to:
https://microsoftteams.uservoice.com/

Thank you!

**Comment by jacobjohnk** [comment]
Why don't I see the Holidays under Org-wide settings?

**Comment by scanum** [comment]
@Patrick959 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
