### ISSUE TITLE
Uploaded Custom App Gone Missing

### ISSUE THREAD

**Issue by NWH-SAmin5** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3405]
We have custom apps uploaded for our organization on Teams app store. It was working fine until yesterday. Now I have two custom apps which is not available anymore. End users who installed these app, are also impacted. They don't see it anymore.

I used o365 cli commands to list the uploaded apps.
I was able to see the app yesterday - 11/12/2019
But I am not able to see starting today - 11/13/2019

**Comment by scanum** [comment]
@NWH-SAmin5 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
