### ISSUE TITLE
I have Teams orphan custom app - which I am not able Delete

### ISSUE THREAD

**Issue by NWH-SAmin5** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3406]
A custom app was uploaded to org Teams store. It was working fine. All of a sudden App disappeared from left nav. I am able to see the app in "Built for...." section. Now I am trying to delete this orphaned app. I get error message "Something went wrong. Please try again later"

I tried using o365 cli commands to remove the app:
> o365 teams app remove --id "{generated app id}"
> Are you sure you want to remove the Teams app "{generated app id}" from the app catalog? Yes
>Error: App doesn't exist in the tenant. UserId: '{user id}', TenantId: '{tenant id}', AppId: '{generated app id}'

I get similar error in browser console as well

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbcabee-fa96-2878-e983-3c966f84ee15
* Version Independent ID: 02fa4fd8-77e0-5cb2-a4af-576cbb68322f
* Content: [Publish apps in the Microsoft Teams Tenant Apps Catalog - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/tenant-apps-catalog-teams#feedback)
* Content Source: [Teams/tenant-apps-catalog-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tenant-apps-catalog-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**``

**Comment by scanum** [comment]
@NWH-SAmin5 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
