### ISSUE TITLE
Creating a Private channel using Graph Api doesn't create sharepoint site for the channel.

### ISSUE THREAD

**Issue by akashSharma2505** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3407]
I am creating a private channel using graph api. I managed to create it successfully but when doing a GET request to get details of channel using, https://graph.microsoft.com/beta/teams/e4f39e73-4d01-46f7-9d55-ea45681f6e92/channels/<channel ID>/filesFolder, the response is as below 

{
  "error": {
    "code": "ItemNotFound",
    "message": "Sharepoint folder not found.",
    "innerError": {
      "request-id": "23197842-0839-4e70-b198-a8f077cea8c2",
      "date": "2019-11-14T07:34:27"
    }
  }
}

please help on this.

**Comment by scanum** [comment]
@akashSharma2505 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
