### ISSUE TITLE
Unable to add new guest teammembers to private channels

### ISSUE THREAD

**Issue by Naures1981** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3409]
We are facing an issue where we're unable to add freshly new team members to a private channel.  The newly added teammember does not popup.

**Comment by Naures1981** [comment]
![image](https://user-images.githubusercontent.com/36915680/68850902-26fae900-06d5-11ea-9f8c-d54e37bf37e3.png)

**Comment by Naures1981** [comment]
We can add the user to the "Group" used within Sharepoint for that specific channel. That does not automatically add the user to the channel within teams.

**Comment by scanum** [comment]
@Naures1981 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
