### ISSUE TITLE
Need Clarification.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#341]
What does "FE, SBA, etc. are configured in the network configuration settings" mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d599b313-b8cd-e436-827e-7520157e8b89
* Version Independent ID: aa303fbf-a860-0eb9-056a-554dd22c23cc
* Content: [Call admission control deployment final checklist for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-enterprise-voice/final-checklist)
* Content Source: [Skype/SfbServer/deploy/deploy-enterprise-voice/final-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-enterprise-voice/final-checklist.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.
