### ISSUE TITLE
[LOC] Possible typo in an article

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3410]
There is a possible typo in an article please see more info below:

**Repro steps**:
1. Go to https://docs.microsoft.com/en-us/microsoftteams/teams-overview
2 Search for "Drive company-wide initiatives, share best practices, and build communities around common topics of interest or areas or practice."
3. See the end of the sentence "areas or practice."

There seems to be a typo where insted of "of" there is "or" in the "areas or practice." part of the sentence

**GH article**:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-overview.md

![image](https://user-images.githubusercontent.com/47977325/68868237-79e59800-06f7-11ea-8ece-de7f07d5f4f1.png)

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
