### ISSUE TITLE
Links are dead

### ISSUE THREAD

**Issue by khanh245** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3411]
The sample tabs and detailed instructions under Develop custom tabs are dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d33f55c-db55-923e-544f-fccb97f3c7a3
* Version Independent ID: 9cb02e00-311e-ec7d-c422-ae1cb9e6d31e
* Content: [Use built-in and custom tabs in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/built-in-custom-tabs#feedback)
* Content Source: [Teams/built-in-custom-tabs.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/built-in-custom-tabs.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@khanh245 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@khanh245 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
