### ISSUE TITLE
Old info on Surfaces ?

### ISSUE THREAD

**Issue by ccygan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3412]
Who would still configure Surfaces as Microsoft Teams Rooms in the end of 2019? This information is obsolete ? We have dedicated devices from OEMs to fulfill this role wchich are cheaper and best designed for the purpose.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf01435-a73b-4bf2-5845-e4cf50c4c3a2
* Version Independent ID: 166e1800-80b1-2496-7160-3040c5b23c3d
* Content: [Microsoft Teams Rooms requirements - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/room-systems/requirements#feedback)
* Content Source: [Teams/room-systems/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/requirements.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ccygan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@ccygan Hi there, thank you for reaching out. I work on the editing side of the Microsoft Documents to help users, are you suggesting we remove the table completely?

**Comment by floydmendes** [comment]
@ccygan, 
Can you please confirm and/update the tablet list to include Surface Pro 7?
Any reason we need i5 CPU, can we not go any lower say SP7 i3 with 4gb ram ?
I'm not sure if it's already specified already, do we need Windows 10 Ent IOT edition?

**Comment by ccygan** [comment]
Hi Guys, from my understanding the table "Supported Surface Pro tablets for dock-style systems" on this page and also the https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/console are obsolete. We recommend Enterprises to purchase Microsoft Teams Rooms devices from our 5 certified partners: HP, Lenovo, Logitech, Crestron and Yealink. Who would endure the pain of setup and configuration on Surface to end up with more expensive and less convenient system than one of those sold by OEMs ? Maybe I am misunderstanding the whole thing ?

**Comment by scanum** [comment]
@Reeced40

**Comment by mileee6** [comment]
It is easier to allow us to setup MS Teams with a Windows 10 as kiosk and reuse old hardware. Why it has to be that expensive?

**Comment by ccygan** [comment]
You may use old hardware for testing purposes but not for production deployment with dozens or hundreds of meeting rooms to deal with. The price of MTR device is comparable to a high end PC and comes with all the necessary configuration and guarantee Enterprises need. Do you want your users endure challenges with old repurposed hardware when there is 10 people in the room waiting for the meeting to start ?

**Comment by scanum** [comment]
@Reeced40 Hi Reece, following up on this.

**Comment by scanum** [comment]
@Reeced40 Hi Reece, following up on this.

**Comment by Reeced40** [comment]
@scanum Looking into it, thanks Manuela.

**Comment by Reeced40** [comment]
@LanaChin

**Comment by Arcass** [comment]
Hi,
Just been investigating the option of re-using Surface Pros. 
Apparently the Logitech Smart Dock is now EoL. The suggested replacement device (Logitech Tap) is only available as a complete unit, so can't be used as a dock for the Surface Pro.

**Comment by Reeced40** [comment]
@LanaChin

**Comment by scanum** [comment]
@LanaChin could you please help in this issue? Thanks!

**Comment by LanaChin** [comment]
Looking into this.

**Comment by franklesniak** [comment]
One person's opinion, but: if Microsoft supports Surface Pro hardware, then it's supported and should stay listed as such.

**Comment by scanum** [comment]
@LanaChin Any update? Thanks!

**Comment by LanaChin** [comment]
Over to you @dstrome.

**Comment by ccygan** [comment]
@franklesniak respectfully, this has nothing to do with Surface Pro hardware support. Surface Pro is of course supported as a Windows 10 PC, but no more in the situation when you create DIY Teams Rooms appliance based on it.

**Comment by franklesniak** [comment]
To clarify: I meant that if Microsoft supports Surface Pro hardware for Teams Room Systems, then it should remain listed on the page. Are you implying that Surface Pros are no longer supported for this purpose?

**Comment by ccygan** [comment]
Yep this is what I heard from engineering. Teams Rooms are OEM made appliances only, no more repurposing of old hardware. We want our customers to have excellent user experience with those devices. No more DIY.

**Comment by scanum** [comment]
@dstrome Hi David, any updates on this issue? Thanks!

**Comment by dstrome** [comment]
@franklesniak @ccygan thanks for your feedback. I'm following up with the product team to determine the support status of these products and will update the pages accordingly.
