### ISSUE TITLE
Microsoft Room license - "Microsoft Teams Rooms license"?

### ISSUE THREAD

**Issue by NeilPetersen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3413]
Under the Important section - "In order to enable your meeting room for Microsoft Teams meetings, we recommend you purchase the Microsoft Room license."

I'm assuming this is a 'Meeting Room' license available through the portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/room-systems/skype-room-systems-v2#feedback)
* Content Source: [Teams/room-systems/skype-room-systems-v2.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/skype-room-systems-v2.md)
* Service: **skype-for-business-online**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@NeilPetersen Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@NeilPetersen Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
