### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by JohnE2** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3414]
Hello. Both links located at the beginning of the article regarding the supported phones are broken. Please update the link. Thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a627b5d-3edc-1add-b921-1dcd49c38653
* Version Independent ID: a2e2bd3a-31c0-471a-05fb-fd64bd942c4a
* Content: [Manage your devices in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/device-management?source=docs#feedback)
* Content Source: [Teams/device-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/device-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@JohnE2 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@JohnE2 Thank you for reaching out, I have fixed the link. It should be working once the authors approve, which could take a couple of days.

**Comment by JohnE2** [comment]
Great, thanks.

JOHN LESSARD
Chief Information Officer
E2 Consulting Engineers, Inc.
510.722.6020 direct | 415.613.5274 mobile

**Comment by scanum** [comment]
@JohnE2 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
