### ISSUE TITLE
Permissions Needed

### ISSUE THREAD

**Issue by c9777777** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3423]
Can you verify what admin permissions are required in order to access this area? 

https://docs.microsoft.com/en-US/microsoftteams/teams-app-setup-policies?WT.mc_id=TeamsAdminCenterCSH

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
