### ISSUE TITLE
Delete Files capability not documented

### ISSUE THREAD

**Issue by jgwinner** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3432]
We've found, catastrophically, that Guests can delete files.

We need them to be able to upload files to a channel, but not delete files once uploaded.

I can't find this in the above chart, so it's a doc bug. I'm also finding it difficult to find out where to change that setting, which may be a feature bug. It starts with the documentation though :)

It's horrible, horrible, and a data loss and compliance issue that Guests can delete files. Please tell me there's a setting somewhere to change that, and please document it somewhere easily findable. 

        == John ==

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [What the guest experience is like - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-experience#comparison-of-team-member-and-guest-capabilities)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@jgwinner thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jgwinner** [comment]
I already did that. Support said you can't prevent Guests from deleting files.

This is a LARGE security hole and really needs to be documented.
