### ISSUE TITLE
Site Collection for a Channel?

### ISSUE THREAD

**Issue by Suheilkarkera** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3434]
Why is a a new "hidden" SharePoint site collection created for a private channel? A secured folder within the Shared Documents library or a secured library within the site collection for that Team should have served the purpose for segregating the channel content from rest of the Team. Also, as a SharePoint admin, I cannot find the site collection in the admin center. Considering hierarchy, a Team owner should be able to override permissions on any private channel. Was this done to segregate private channels from team owners? Scary idea when it comes to data protection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels#feedback)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by Panoone** [comment]
I couldn't agree more. The notion behind this was that team members can create private channels that the team owners group do not have access to. This is a frightening implementation for so many reasons.

**Comment by xNiklasJern** [comment]
I'm also confused about this. How come the site collection isn't available in the admin center? How should you be able to manage this from an admin perspective

**Comment by Panoone** [comment]
Apparently you don’t. You just need to trust the almost opaque process.
Read the fine-print surrounding the deletion and recovery.

I’m reluctant to start down the path now knowing that it’s new,
unsustainable and prone to change in a way that my leave early-adopters
crying in the wings.

IMHO all channels should have been libraries and private channels. And a
common sense union with existing SharePoint groups employed.

**Comment by scanum** [comment]
@Suheilkarkera Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lsweeney2018** [comment]
I can see the private channel sites listed using powershell: Get-sposite

**Comment by scanum** [comment]
@Suheilkarkera Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Panoone** [comment]
What was the resolution?? Before closing an issue it’d be nice to know what
the resolution is.

**Comment by xNiklasJern** [comment]
> @Suheilkarkera Thank you for submitting feedback. We understand that this issue has been resolved.
> Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

What is actually resolved? none of the questions above was answered

**Comment by Panoone** [comment]
Before ANYONE begins to implement this solution in our environments - which
is the LARGEST asked for to convert Slack users to Teams - we need to know
it’s going to be robust.

The current implementation is simply not, which is why it’s not being
lauded and embraced.

Please advise a long term solution!
