### ISSUE TITLE
Timeframe >12 months?

### ISSUE THREAD

**Issue by BhaskinsWR** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3436]
My PSTN usage reports are exactly 12 months old - we've been using SfB and Teams for much longer. Is this a limitation, or is there a way to access older PSTN usage reports?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ade1a4-092c-1132-44df-ee2c683fdd33
* Version Independent ID: 396b1aee-2f40-9895-9b00-07e38d11d31b
* Content: [Microsoft Teams analytics and reporting - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-reporting-reference#feedback)
* Content Source: [Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@BhaskinsWR Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @BhaskinsWR, thank you for your feedback.

@LanaChin could you kindly help with this information? Thanks!

**Comment by scanum** [comment]
@LanaChin Following up on this issue. Could you please help us on this? thanks!

**Comment by BhaskinsWR** [comment]
Any update? Need anything from me?

Bill Haskins
Wainhouse Research, LLC | Boulder, CO | USA
+1 303 902 6861
email: bhaskins@wainhouse.com<mailto:bhaskins@wainhouse.com> | web: www.wainhouse.com<http://www.wainhouse.com/>

[image001]<https://insight.wainhouse.com/>

**Comment by dariomws306** [comment]
@BhaskinsWR no thank you. We are trying to get this information from Product Group.

**Comment by BhaskinsWR** [comment]
Thanks!

Bill Haskins
Wainhouse Research, LLC | Boulder, CO | USA
+1 303 902 6861
email: bhaskins@wainhouse.com<mailto:bhaskins@wainhouse.com> | web: www.wainhouse.com<http://www.wainhouse.com/>

[image001]<https://insight.wainhouse.com/>

**Comment by NMuravlyannikov** [comment]
@BhaskinsWR  we don't store the data for more than 12 month. The reports also scrubbed (phone number obfuscated) after 30 days. This is to comply with regulations. If you need the reports for longer time, please download the reports. Sorry for inconvenience but this is the only way to comply with multiple regulations around the globe.

**Comment by BhaskinsWR** [comment]
Thanks for the follow-up. Honestly the response is a little weird – I’d think this data should be managed by my O365 security and compliance settings, not system-level global regulatory requirements. Not your issue, and I appreciate the clarity.

Bill Haskins
Wainhouse Research, LLC | Boulder, CO | USA
desk: +1 720 336 4966<tel:+17203364966> | mobile: +1 303 902 6861<tel:+13039026861>
email: bhaskins@wainhouse.com<mailto:bhaskins@wainhouse.com> | web: www.wainhouse.com<http://www.wainhouse.com/>

[WROI]<https://insight.wainhouse.com/Home/NewReports>

**Comment by LanaChin** [comment]
Thank you @NMuravlyannikov. Closing this issue.

**Comment by johnbam21** [comment]
So just to be clear, we are able to check PSTN Usage reports for upto 12 months? Is there anyway to manage this retention period i.e. reduce it or is 12 months by default?

Many Thanks
John
