### ISSUE TITLE
UK minutes

### ISSUE THREAD

**Issue by thetechguy86** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3437]
At the bottom of https://products.office.com/en-us/microsoft-teams/voice-calling it states "Domestic: 3000 domestic minutes in the US and Puerto Rico, and 1200 domestic minutes in the UK." I don't see any reference to UK minutes here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2b2f00a-d4ee-28ab-8c9f-fdc858eb30a4
* Version Independent ID: 07d9aa8b-7e6c-a340-bc75-f0c8159f6c57
* Content: [Availability in the United States (U.S.) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-states-u-s#feedback)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-states-u-s.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-states-u-s.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@thetechguy86 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @thetechguy86, thank you for your feedback.

Referece to UK minutes is here:
https://docs.microsoft.com/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-kingdom-u-k
