### ISSUE TITLE
Private Channel not showing up on Android Teams Mobile Client

### ISSUE THREAD

**Issue by Harry-at-G** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3438]
I have created a private channel in Teams.
It showed up on Windows client and Web-based version for Teams, but it doesnt show up in Android Client.

**Comment by scanum** [comment]
@harry-at-G thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
