### ISSUE TITLE
Unified groups?

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3439]
" private channel site collection syncs data classification and inherits guest access permissions from the site collection of the parent team. "
Does this mean that any private channel site collection inherit the unified group that has been applies to parent team? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@xNiklasJern Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @xNiklasJern 

Thank you for reaching out! 

Yes, private channel site collection inherits the permissions from the parent team site collection.

Hope this clarifies your query. Thank you!

**Comment by scanum** [comment]
@xNiklasJern Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
