### ISSUE TITLE
Need update and more information.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#344]
This documentation is old and have limited information. Need to know more information like:
Is DFS supported ?  What rights are needed on the share etc.?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 927e07a9-dff9-78a7-a351-90c694ea2537
* Version Independent ID: ec207175-a445-4f22-9c79-d02d83c59db4
* Content: [Add File Store](https://docs.microsoft.com/en-us/skypeforbusiness/help-topics/help-topobld/add-file-store)
* Content Source: [Skype/SfbServer/help-topics/help-topobld/add-file-store.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/help-topics/help-topobld/add-file-store.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi! Thanks for your feedback.
You can find information on DFS and permissions here https://docs.microsoft.com/en-us/skypeforbusiness/deploy/install/create-a-file-share
