### ISSUE TITLE
Private channel in Microsoft Teams, record meeting

### ISSUE THREAD

**Issue by Purple-Hayes** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3441]
Hi, 
I am trying to record a meeting in a private channel in Microsoft Teams, but that I do not see teh option to record the meeting.

I can record a meeting in a channel within the same Team that is not marked as a private Channel.

I have looked at the settings and I do not see anything obvious as to why I cannot record a meeting within the private channel.

Best, Tom.

**Comment by scanum** [comment]
@Purple-Hayes thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
