### ISSUE TITLE
Static conference IDs are not available for Teams

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3442]
The PowerShell command does not set a conference ID, nor does the GUI control produce the outcome documented in the article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2167d5b2-c4c4-3164-2ed2-9582c8a0f95b
* Version Independent ID: cbbf9c78-5708-a0a9-31c3-d2cb4b31f6d3
* Content: [See, change, and reset a conference ID assigned to a user in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/see-change-and-reset-a-conference-id-assigned-to-a-user-in-teams)
* Content Source: [Teams/see-change-and-reset-a-conference-id-assigned-to-a-user-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/see-change-and-reset-a-conference-id-assigned-to-a-user-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@TheBluLion Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @TheBluLion 

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let us know if it is something that can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Thank you!

**Comment by scanum** [comment]
@TheBluLion Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by TheBluLion** [comment]
Static conference IDS are never available for Skype for Business Online- the document needs to be updated to indicate this.


﻿ -﻿ --
Eu Nice Loh
Premier Field Engineer
Office: (314) 872 5916
EuNice.Loh@microsoft.com<mailto:EuNice.Loh@microsoft.com>
IM:euloh@microsoft.com
8AM-5PM CT
[Microsoft]
﻿
If you have any feedback about my work, please let either me or my manager Annele Richards know at Annele.Richards@microsoft.com<mailto:Annele.Richards@microsoft.com>
