### ISSUE TITLE
Typo on this page

### ISSUE THREAD

**Issue by MSFTEfeedback** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3447]
In the "Important" box directly under "Manage via Powershell", the word "include" is typo'd as "inlcude".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cccdd91a-7f05-abd5-ed94-e82152b86914
* Version Independent ID: 3532d0a8-119c-f7d0-0d4f-a865ad32570f
* Content: [Manage user access to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/user-access#feedback)
* Content Source: [Teams/user-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/user-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@MSFTEfeedback Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
