### ISSUE TITLE
Guest access to files in a private chat

### ISSUE THREAD

**Issue by bebobebo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3449]
It is not clear how guests can receive files from members in a private chat. Our experience is that guests cannot see any files shared by members other than pasted images (which are not stored as files).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [What the guest experience is like - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-experience)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@bebobebo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @bebobebo 

Thank you for reaching out! This feedback system is to update/correct the documentation if there is something missing or incorrect.

 I think the best way forward is if you open a service ticket in your tenant so this can get addressed ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

Thank you!

**Comment by scanum** [comment]
@bebobebo Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by bebobebo** [comment]
@sowjanya365 I am not clear about the point of your comment. It appears that my point that the documentation was incorrect is right as it has been updated to support that.  I cannot open a service ticket to address a feature that doesn't exist i.e. guest access to chat files.
