### ISSUE TITLE
Need help regarding call admission control deployment.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#345]
"After you have configured your network settings for call admission control deployment," - not defined. What does that mean? Could you link me to that page? Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2c15279-792b-5f53-4371-b6754a835947
* Version Independent ID: 2f683b53-b57b-f9f1-4256-b710f57f8f6b
* Content: [Enable call admission control in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-enterprise-voice/enable-call-admission-control)
* Content Source: [Skype/SfbServer/deploy/deploy-enterprise-voice/enable-call-admission-control.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-enterprise-voice/enable-call-admission-control.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi
The article is created as a part of a guide that starts at Deploy advanced Enterprise Voice Features, if you follow the steps, you will came up configuring the network settings, you can find it at the left of the page in the navigation links.

Thank you
