### ISSUE TITLE
Linked video is private

### ISSUE THREAD

**Issue by white-tim** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3450]
https://www.youtube.com/watch?v=wEc9u4S3GIA is a private video. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169a20a6-ebf7-1093-3cb1-fb438b9b7e13
* Version Independent ID: b2074fd8-724e-75fa-bafb-a0f7966bf593
* Content: [Coexistence with Skype for Business - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/coexistence-chat-calls-presence%C2%A0#feedback)
* Content Source: [Teams/coexistence-chat-calls-presence.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/coexistence-chat-calls-presence.md)
* Service: **msteams**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@white-tim Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by stefandoh** [comment]
@scanum, @white-tim Video is public available. Issue can be closed.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
