### ISSUE TITLE
Unusual results

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3454]
After following the instructions above, when I use Get-Module -Name MicrosoftTeams i don't get any results, but if i use Get-Module -ListAvailable, i see that I have Binary     1.0.18     MicrosoftTeams .  What would cause this ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e0ac38-cfff-8d8f-5345-2ae93a9fae2e
* Version Independent ID: bec44289-e9fa-4464-1601-0ca86d61e6ca
* Content: [Manage the life cycle of private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels-life-cycle-management#install-the-latest-teams-powershell-module-from-the-powershell-test-gallery)
* Content Source: [Teams/private-channels-life-cycle-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels-life-cycle-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@DeanGross Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by yvesrosius** [comment]
Hi, that would be because the module is not imported yet.

"Import-Module MicrosoftTeams" should do the trick. Or the -ListAvailable parameter should work also.

**Comment by sowjanya365** [comment]
> Hi, that would be because the module is not imported yet.
> 
> "Import-Module MicrosoftTeams" should do the trick. Or the -ListAvailable parameter should work also.

Hi @DeanGross 

Hope you are doing well! 

Are you still facing this issue? Did you try importing the module? Kindly let us know. Thank you!

**Comment by scanum** [comment]
@DeanGross We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
