### ISSUE TITLE
Microsoft teams - userv in organization but without license

### ISSUE THREAD

**Issue by AdrianMurariu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3456]
I understand that Microsoft teams it is free to use. We are a start-up with 20 employees but I have license Office365 only for 10 (because they work at office.
For another 10 I want to use Teams but without license because they work on the field and use only Teams on mobile. 

My ask is: I can create in Admin page the users without license and use the credential to use Teams (if it is free).

thx

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
