### ISSUE TITLE
Calling Plans other than UK and Canada

### ISSUE THREAD

**Issue by 1068mark** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3458]
Guidance should include link to what are the available calling plans and associated pool of minutes available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7546fc-fc37-14ac-94bb-ffbe4c6e16d6
* Version Independent ID: 61a44a8e-f55a-5bf5-a22b-2995f7efe79d
* Content: [What do I need to purchase to use Microsoft 365 Business Voice? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/business-voice/what-to-buy#feedback)
* Content Source: [Teams/business-voice/what-to-buy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/business-voice/what-to-buy.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@1068mark Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @1068mark 

Thank you for reaching out!

At the moment, it has been launched in the UK and Canada markets only. Over time, Business Voice will be rolled out to additional countries.

Hope this clarifies your query. Thank you!

**Comment by scanum** [comment]
@1068mark Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
