### ISSUE TITLE
Lifecycle management - really?

### ISSUE THREAD

**Issue by Michael-Sampson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3462]
Hi team ... just a query on the title of this page. Lifecycle is generally used to refer to the whole process of creation, utilisation, archival and deletion, not just creation rights for users and reporting for admins. Can you downplay your wording to scope this page more accurately?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e0ac38-cfff-8d8f-5345-2ae93a9fae2e
* Version Independent ID: bec44289-e9fa-4464-1601-0ca86d61e6ca
* Content: [Manage the life cycle of private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels-life-cycle-management)
* Content Source: [Teams/private-channels-life-cycle-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels-life-cycle-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Michael-Sampson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @Michael-Sampson 

Thank you for the feedback! Much appreciated!

This document explains the most of the operations surrounding the teams private channels, like creating private channels, who can create the channels, getting the list of private channels, retrieving and updating the role of owners and members in a private channels. 

Considering the above operations, we feel that this document has it's justifying title. But we will definitely convey your feedback with the document owners, if there is really a need to change the document title we will proceed and update it. 

Hope this helps! Thank you!

**Comment by scanum** [comment]
@Michael-Sampson Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
