### ISSUE TITLE
Do guests see all channels within a team?

### ISSUE THREAD

**Issue by kevinmenigo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3465]
Does a guest see all open channels within i team or is it possible to restrict with channels they are able to see? Or must all channels be private to achieve that? Or is it possible to invite a guest to only one channel and not the team?

**Comment by scanum** [comment]
@kevinmenigo thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
