### ISSUE TITLE
Add Office 365 security group in a Team

### ISSUE THREAD

**Issue by mateustav21** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3468]
I recently received a request to create new teams in Microsoft Teams. I performed the procedure of creating a new team through the desktop application on my computer and in the step of adding new team members, I typed in the name of a security group that contains all users who will be part of the team. To my surprise, the security group was found but when clicking on the group name or icon, simply the group is not added in the box. It is as if I have not been selecting any information. I reproduced the same behavior with other security groups and also on a test tenant.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 20423b44-629b-1bee-280c-fb55680cd33e
* Version Independent ID: a60f6a48-89d7-98b6-4245-4be171fd06fd
* Content: [Atribuir proprietários de equipe e membros no Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/pt-br/microsoftteams/assign-roles-permissions#feedback)
* Content Source: [Teams/assign-roles-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-roles-permissions.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@mateustav21 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
