### ISSUE TITLE
Need information about DFS-share and replication

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#347]
Can you add a section about putting the DFS-Share and replication on the front-end itself ?  Is it possible, allowed, supported or not supported ?

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by yogkumgit** [comment]
As it an internal trasfer from one system to other so can be closed
