### ISSUE TITLE
MFA for Team Rooms accounts

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3470]
Is it supported to have MFA enabled for Team Rooms Accounts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 834f564b-d32a-25ba-437b-1cb74adbf485
* Version Independent ID: 9bdb6864-caa0-d0fa-ce06-eaaa1fd18fe3
* Content: [Configure accounts for Microsoft Teams Rooms - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/room-systems-v2-configure-accounts)
* Content Source: [Teams/room-systems/room-systems-v2-configure-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/room-systems-v2-configure-accounts.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TB-93** [comment]
Any updates regarding this question?

**Comment by alemas7** [comment]
are there any update about the Teams Room autenthication?
In my environment the Exchange online doesn't work

**Comment by sowjanya365** [comment]
Hi @Larryngolog 

Thank you for reaching out! I think the best way forward is if you open a service ticket in your tenant so this can get addressed ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Thank you!

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
