### ISSUE TITLE
error when adding Teams Channel owner

### ISSUE THREAD

**Issue by jimcantor** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3473]
I am using the latest Teams PowerShell module from the PowerShell Test Gallery.

PS C:\WINDOWS\system32&gt; add-TeamChanneluser -GroupId 0b910d5d-d1b6-463e-b705-a6377229a5d3 -user jason@xxxbanana.com.au -displayname xxxxS

PS C:\WINDOWS\system32&gt; add-TeamChanneluser -GroupId 0b910d5d-d1b6-463e-b705-a6377229a5d3 -user jason@xxxbanana.com.au -role Owner -displayname xxxxS
add-TeamChanneluser : Error occurred while executing
Code: GeneralException
Message: Failed to execute Skype backend request BulkMembershipS2SRequest.PUT.
InnerError:
  RequestId: 5f607439-51cc-40e3-b9f6-21740cff6de2
  DateTimeStamp: 2019-11-20T23:49:20
HttpStatusCode: GeneralException
At line:1 char:1
+ add-TeamChanneluser -GroupId 0b910d5d-d1b6-463e-b705-a6377229a5d3 -us ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-TeamChannelUser], ApiException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdle
   ts.PowerShell.Custom.AddTeamChannelUser

also, -membershiptype is not a parameter for add-TeamChannelUser

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e0ac38-cfff-8d8f-5345-2ae93a9fae2e
* Version Independent ID: bec44289-e9fa-4464-1601-0ca86d61e6ca
* Content: [Manage the life cycle of private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels-life-cycle-management#install-the-latest-teams-powershell-module-from-the-powershell-test-gallery)
* Content Source: [Teams/private-channels-life-cycle-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels-life-cycle-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by jimcantor** [comment]
I have found that this error occurred because I was not an owner of the private channel.  Still, a better message would be useful

**Comment by scanum** [comment]
@jimcantor thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by fredericklin** [comment]
I'm getting an error as well. Would be nice if the group owner automatically has access to all private channels. Can see private channels being ownerless after a while from users leaving/offboarding.
