### ISSUE TITLE
Settings detail

### ISSUE THREAD

**Issue by white-tim** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3474]
It would be good to have a list of all settings in the configuration profile and what they do

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a627b5d-3edc-1add-b921-1dcd49c38653
* Version Independent ID: a2e2bd3a-31c0-471a-05fb-fd64bd942c4a
* Content: [Manage your devices in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/device-management)
* Content Source: [Teams/device-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/device-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@white-tim Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @white-tim 

Thank you for reaching out! 

Please refer to the following link for more details on the device configuration profile settings. 

https://techcommunity.microsoft.com/t5/microsoft-teams-events-blog/how-to-choose-deploy-and-manage-the-right-teams-devices-brk3410/ba-p/267552

Hope this helps. Thank you!

**Comment by white-tim** [comment]
Thanks @sowjanya365   but this doesn't really give me what I am looking for.  Documentation for other policies and settings has detail of each setting, the options, and the impact of these settings.  I'm yet to find something like that for the device settings

**Comment by scanum** [comment]
@sowjanya365

**Comment by sowjanya365** [comment]
Hi @white-tim 

Thank you for your feedback! 

At the moment, we do not have the field level description for all the settings. We will definitely consider to include the suggested settings in the upcoming documentation upgrade.

In the meantime, would you be so kind as to open a service ticket in your tenant and let the team know if you are looking for any specific field description. The team will certainly assist you!

Thank you so much for your contribution! :)

**Comment by sowjanya365** [comment]
@scanum Please close this issue. Thank you!

**Comment by scanum** [comment]
@white-tim Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
