### ISSUE TITLE
The table is not displayed correctly in Japanese.

### ISSUE THREAD

**Issue by REDS0255** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3475]
In paragraph "When to create a private channel", the table is not displayed correctly in Japanese.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Microsoft Teams のプライベートチャネル - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/private-channels#feedback)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officeglobal Hi Could you please help with this Issue? Thanks!

**Comment by OfficeGlobal** [comment]
Investigating the issue

**Comment by OfficeGlobal** [comment]
The article was HumanTranslated and published live. But we're not able to edit columns width in the tables

**Comment by sowjanya365** [comment]
Hi @scanum 

There is no issue with the content. It is a translation issue. Kindly assign it to the appropriate team/member. Thank you!

**Comment by scanum** [comment]
@REDS0255 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
