### ISSUE TITLE
SKU's supported

### ISSUE THREAD

**Issue by dgordonb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3476]
Teams and M365 Business Voice with guest access is also supported on Essentials.  

Guest is a user type in Microsoft Teams that is included with all Office 365 Business Premium, Office 365 Enterprise, and Office 365 Education subscriptions. No additional Office 365 license is necessary. Read more about guest access licensing below.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f1d577c-1360-c2c1-a850-9ac6a941ec2f
* Version Independent ID: 346e43d4-22e0-2800-b80d-9fbdac324f75
* Content: [Manage guest access in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-guests#feedback)
* Content Source: [Teams/manage-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-guests.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@dgordonb Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @dgordonb 

Thank you for reaching out to us! 

Would you be so kind as to elaborate more on this? Are you suggesting us to update the current content? If yes, could you please let us know the content that you want us to update. 

Looking forward to your response. Thank you!

**Comment by dgordonb** [comment]
Business Voice is also supported on O365 Business Essentials.  Effectively any SKU that includes Teams.
my MS email is dobro@microsoft.com and I work on Business Voice in the Teams engineering team.

**Comment by sowjanya365** [comment]
Sure, @dgordonb 

Thank you for your feedback! We will verify and update the content.

**Comment by scanum** [comment]
@dgordonb 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
