### ISSUE TITLE
Do settings for devices apply to teams meetings or SFB online only?

### ISSUE THREAD

**Issue by white-tim** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3477]
The documentation for the powershell configuration (https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsclientconfiguration?view=skype-ps) seems to indicate the content PIN and other device settings are only for SFB Online meetings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9b7f77-061d-a224-ff1c-8d3e15d21221
* Version Independent ID: 00fa9550-c4c4-3398-ffbb-271cc724048f
* Content: [Manage Microsoft Teams settings for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/enable-features-office-365)
* Content Source: [Teams/enable-features-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enable-features-office-365.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@white-tim Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @white-tim 

Thank you for reaching out!

All the cmdlet reference documents(Teams and Skype for Business) are created under the root index node i.e., Skype. As specified in the following root overview document, the cmdlet references are for Skype for Business and Microsoft Teams.

https://docs.microsoft.com/powershell/module/skype/?view=skype-ps

Hope this clarifies your query. Kindly let us know if that helps. Thank you!

**Comment by scanum** [comment]
@white-tim Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
