### ISSUE TITLE
How to recognise dialin user with PIN

### ISSUE THREAD

**Issue by szymonslipek** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3478]
Hi,
Under Teams Admin Trainig page https://docs.microsoft.com/en-US/MicrosoftTeams/tutorial-audio-conferencing?tutorial-step=2

there is scenario where user A is organiser and user B is joining the meeting via phone and IS ASKED for PIN to be recognised as user B.

"Garth works at Contoso, a company that has multiple offices. Garth frequently needs to connect with people in other office locations, and because he often works from home or goes out on the road, he’s a huge fan of Teams meetings. When Garth sends out a meeting invitation, it automatically adds information for Audio Conferencing. This makes the following scenarios possible:

Alice wants to attend Garth’s meeting but she’s on the road and has no access to a reliable network. Therefore, she joins the meeting by using the dial-in coordinates from the meeting invitation. **During the dial-in process, she uses her PIN to authenticate, so she’s recognized by the system as “Alice.”**"

How to achieve this? I am not able to set configuration to reflect this.

**Comment by scanum** [comment]
@szymonslipek thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
