### ISSUE TITLE
Error while trying to access the /filesFolder GraphApi endpoint as a global admin for a private channel

### ISSUE THREAD

**Issue by josipGrgic11235** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3479]
Right, so I followed the steps described in this article describing the way to find the SharePoint URL for a given private channel. Basically, I made the following call as a global admin, but having no membership or ownership to the team and/or private channel in question:

`GET https://graph.microsoft.com/beta/teams/<group_id>/channels/<channel_id>/filesFolder`

But, it seems that the call returns an error (sometimes 500, other times 404 with an "Unknown error" message) while supplying a `<channel-id>` of a private channel. The same thing happens from time to time for a private channel owner account as well which for me doesn't make much sense.

The article does briefly point out that we have to have an admin role but does not delve into more details around the needed permissions. The admin user making the request is, besides GA, additionally a Teams Service Admin as well as a Skype Admin.

Also, I seem to recall that I was able to make the described request last week successfully. Are there any changes, permission-wise, we should be aware of or is there just a bug on your side of things?  Any insight is greatly appreciated.

Regards,
Josip

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e0ac38-cfff-8d8f-5345-2ae93a9fae2e
* Version Independent ID: bec44289-e9fa-4464-1601-0ca86d61e6ca
* Content: [Manage the life cycle of private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels-life-cycle-management#feedback)
* Content Source: [Teams/private-channels-life-cycle-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels-life-cycle-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@josipGrgic11235 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
