### ISSUE TITLE
Need help regarding attendance list.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#348]
Need to find out how I can provide meeting arrangers with attendance lists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10fb912b-03c2-c982-1ebf-f4c81ad9a06b
* Version Independent ID: 14117ead-4613-66c8-8c66-8d52c0c162d7
* Content: [Conference Detail Report in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/manage/health-and-monitoring/detail-report)
* Content Source: [Skype/SfbServer/manage/health-and-monitoring/detail-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/health-and-monitoring/detail-report.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Review the raw Participation or Modalities reports for a conference and manually create a list of attendees.
