### ISSUE TITLE
Scenario - Audioconferencing - Unable to being authenticated with PIN as atendee

### ISSUE THREAD

**Issue by szymonslipek** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3480]
Hi,

There is scenario for Audioconferencing where user **who is not organiser** of the meeting is dialling-in and is later on authenticated with PIN to be recognised as herself by name.

https://docs.microsoft.com/en-US/MicrosoftTeams/tutorial-audio-conferencing?tutorial-step=2

How to achieve this? Only meeting organiser need to insert PIN, when he/she is first person on the meeting. I would like to have this feature for all dialled-in attendees - not to see their phone number, but their names insted as in Your example.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6e83731-a025-39e5-85e8-c7fcbfd4794e
* Version Independent ID: 44b128ed-b63b-f703-adc9-90eb2737d824
* Content: [Audio Conferencing in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-US/MicrosoftTeams/tutorial-audio-conferencing?tutorial-step=8#feedback)
* Content Source: [Teams/Tutorial-Audio-Conferencing.yml](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/blob/live/Teams/Tutorial-Audio-Conferencing.yml)
* Service: **msteams**
* GitHub Login: @thomasbinder
* Microsoft Alias: **tbinder**

**Comment by scanum** [comment]
@szymonslipek Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @szymonslipek 

Thank you for submitting feedback. I think the best way forward is if you open a service ticket in your tenant so this can get addressed ASAP. Based on the outcome let me know if it is something that can 
be called out in the docs. 

Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@szymonslipek Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
