### ISSUE TITLE
Unable to delete teams with private channels

### ISSUE THREAD

**Issue by bflanaganesri** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3482]
once we have added a private channel, we are unable to delete the channel of the team. We get these errors:

- 2019-11-21T14:03:50.636Z ChannelService: Team id undefined was not found
- DELETE https://teams.microsoft.com/api/mt/emea/beta/teams/19:cbcd8be37d384ca0aa1b0f353af32cc5@thread.skype/delete 500
- 2019-11-21T14:03:53.939Z [deleteTeam] Failed to delete team "19:cbcd8be37d384ca0aa1b0f353af32cc5@thread.skype".
- 2019-11-21T14:03:53.940Z ChannelService: Cannot delete team 19:cbcd8be37d384ca0aa1b0f353af32cc5@thread.skype : {"response":null,"status":500,"_codeEnum":0,"_code":"Unknown","_message":"One or more errors occurred."}
- 2019-11-21T14:03:53.942Z TeamActionDialogUtilityService: Error occured while deleting team{"response":null,"status":500,"_codeEnum":0,"_code":"Unknown","_message":"One or more errors occurred."}

**Comment by scanum** [comment]
@bflanaganesri thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
