### ISSUE TITLE
CreateSrsMedia.ps1 - Is It Deprecated?

### ISSUE THREAD

**Issue by JREID96** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3483]
I'm using the CreateSrsMedia.ps1 script v1.5.0 with the latest Windows 10 Enterprise ISO (10.10.18362.418). The script has not been updated to support this latest version, so I modified it to bypass the version mismatch between the $img.Version and $KitOsRequired variables. 

The installation media creation completes successfully, but the Surface Pro 5 I am testing SRSv2 is completing the installation with the error "Windows could not apply unattend settings during pass [offlineServicing]".

**Comment by JREID96** [comment]
I have managed to get the system working by configuring the attend.xml, but I had to use WICD to create my own provisioned package since the console is not working the same as it did on Win10 build 1709

**Comment by scanum** [comment]
@JREID96 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
