### ISSUE TITLE
Creating users for activating services

### ISSUE THREAD

**Issue by donlassini** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3484]
"After you have registered a domain name, you need to activate it by adding at least one E1, E3, or E5 licensed user and assigning a SIP address with the FQDN portion of the SIP address matching the created base domain."
* Exactly which apps of E1/E3/E5 license are required? It shouldn't be necessary to enable e.g. SharePoint and Yammer for the user.
* After activation, can this user be removed?

"Activate the subdomain name
After you register a domain name, you need to activate it by adding at least one user and assign a SIP address with the FQDN portion of the SIP address matching the created subdomain in the customer tenant."
* I assume that it's activated just as in the above example, e.g. by adding an E1/E3/E5 license? Which apps are required?
* Also, after activation, can the user be removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure a Session Border Controller for multiple tenants - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@donlassini Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by donlassini** [comment]
There's no need to investigate if the user can be removed - that proves not to be the case.
But knowing about the required apps would be great :-)

**Comment by scanum** [comment]
@sowjanya365 Could you please aid with this issue? Thanks

**Comment by vnewbaker-bw** [comment]
An Office 365 E1 license and a Phone System license is all that is required on the user.

**Comment by scanum** [comment]
@sowjanya365 Could you please aid with this issue? Thanks

**Comment by scanum** [comment]
@donlassini Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
