### ISSUE TITLE
Teams Add-in for Outlook causes Outlook to crash

### ISSUE THREAD

**Issue by Jason542** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3486]
I have a new laptop with a new click to run install of Office (from O365), I have 2 Exchange mailboxes, a gmail and a live account mailbox.  When I click on a folder in the second (non-Teams connected) Exchange mailbox, Outlook crashes.  The only way to keep it from crashing to disable the Teams Add-in (which I use constantly). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Use the Microsoft Teams Meeting add-in in Outlook - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook#feedback)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
