### ISSUE TITLE
Cloud Voicemail prerequsites

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3487]
A paragraph at the end of this article says:
"* Voicemail. When you get a Phone System license for a user, that user is able to get voicemail that has been left by callers. Cloud Voicemail is automatically set up and provisioned for users after you assign a Phone System license and a phone number to them."
It suggests that we must 1) to assign Phone System license and 2) to assign a phone number in order to get Cloud Voicemail functionality.
As far as I'm aware, phone number is not required for Cloud Voicemail to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d45becfa-69d7-b956-cf97-4b14c97ad92c
* Version Independent ID: 81d5bad1-fc63-26dc-5c08-31c8d07c828d
* Content: [What is Phone System in Office 365? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/what-is-phone-system-in-office-365)
* Content Source: [Teams/what-is-phone-system-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-is-phone-system-in-office-365.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@shivtorov Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @shivtorov 

Thank you for the feedback. Could you please confirm that you have set up the Cloud Voicemail with out assigning a phone number to the phone system?

Looking forward to your response. Thank you!

**Comment by scanum** [comment]
@shivtorov We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
