### ISSUE TITLE
Need help to understand NAT enabled.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#349]
Looking for the meaning of "A/V Edge Service is NAT enabled" - what does it do when checked? Require when not checked? We're NATted, but this is unchecked and seems to work fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 123997ca-14c6-3b33-5a01-5b2032f20af7
* Version Independent ID: dc2bd137-c08e-38e9-7a44-869f7b5d472c
* Content: [Edge Settings Expander](https://docs.microsoft.com/en-us/skypeforbusiness/help-topics/help-topobld/edge-settings-expander)
* Content Source: [Skype/SfbServer/help-topics/help-topobld/edge-settings-expander.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/help-topics/help-topobld/edge-settings-expander.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi, thanks for your feedback.
You can find information about NAT in Edge of SfB here https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-determine-external-a-v-firewall-and-port-requirements#nat-requirements-for-external-user-access
Thank you
