### ISSUE TITLE
sending email

### ISSUE THREAD

**Issue by tmaheshwar** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3490]
Is it possible to send via email these reports,what will be the best way to send via emails; Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ade1a4-092c-1132-44df-ee2c683fdd33
* Version Independent ID: 396b1aee-2f40-9895-9b00-07e38d11d31b
* Content: [Microsoft Teams analytics and reporting - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/teams-analytics-and-reports/teams-reporting-reference?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@tmaheshwar Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @tmaheshwar 

Thank you for reaching out! 

Currently, we do not have an option to export these reports.

You can make a suggestion in [Teams User Voice](https://microsoftteams.uservoice.com/)

Hope this information helps you. Thank you!

**Comment by scanum** [comment]
@tmaheshwar 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
