### ISSUE TITLE
Update Important note

### ISSUE THREAD

**Issue by ingd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3491]
You should update Important information below:

"If you uninstall the Skype for Business client after you move a user to Teams Only mode, presence stops working in Outlook and other Office apps. Presence works fine in Teams. Workaround: To see presence in Outlook (and other Office apps), Skype for Business must be installed, even if you're running Teams in Teams Only mode. Microsoft is aware of this problem and is working on a fix."

Register Teams as chat application communication fixed this problem to me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@ingd Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dstrome** [comment]
hi @ingd and @scanum - I confirmed the behavior and will update the important note. thanks!
