### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by weq** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3494]
https://go.microsoft.com/fwlink/?linkid=855800 it is referenced as the place to find documentation for the network assessment tool

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e8b2651-40bb-0d26-6126-d88689047f23
* Version Independent ID: 5be83c7d-ef7f-5582-4a6c-f0709fb2ec7b
* Content: [Prepare your network for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/upgrade-prepare-environment-prepare-network#feedback)
* Content Source: [Teams/upgrade-prepare-environment-prepare-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-prepare-environment-prepare-network.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@weq Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @weq 

Thank you for your feedback. 

When we check in the document now, the links are mapped to the correct URL. Kindly verify and let us know if you still see the same issue. Thank you!

**Comment by scanum** [comment]
@weq We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
