### ISSUE TITLE
Prompt to record a message is strange

### ISSUE THREAD

**Issue by cschafft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3495]
When the voicemail is setup, some instructions are played, but the message is very odd for the caller. It says "Please record a message after the tone. *Brief pause* Please leave a message after the tone."

Are there any possibilities to override these instructions?

EDIT: there was a misconfiguration on our end.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8228f9b2-a7de-abb4-6f41-70db0b3af155
* Version Independent ID: 8fd9fafb-dd76-59a8-e609-56f06d539a31
* Content: [Set up Cloud Voicemail - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-phone-system-voicemail?source=docs)
* Content Source: [Teams/set-up-phone-system-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-phone-system-voicemail.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@cschafft  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by cschafft** [comment]
@scanum : thank you for your reply. We noticed a misconfiguration on our end.

**Comment by gobmh** [comment]
@cschafft Hi, maybe we are facing a similar problem. We moved all users from SfB on prem to Teams a few weeks ago. Now, if a user records his personal VM greeting or uses the TTS option, the given greeting is played properly. But afterwards the standard voicemail greeting is played, too.

Does anyone have an idea how to fix this behavior?
