### ISSUE TITLE
supported countries

### ISSUE THREAD

**Issue by tmaheshwar** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3496]
Which all Countries, LBR is supported, is this supported for India

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e427e0b-ef18-6947-27a6-eb75ddbdead7
* Version Independent ID: baf34a47-7d43-8291-7792-dd0b5dac1931
* Content: [Plan Location-Based Routing for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/location-based-routing-plan)
* Content Source: [Teams/location-based-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/location-based-routing-plan.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@tmaheshwar  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by msbemba** [comment]
@tmaheshwar Thank you for the feedback. As far as Microsoft is concerned you will be able to use this article and LBR is supported. But regulations are different for different countries and you need to check that with the local telecom provider. 

JFYI.. Telecom regulation authority of India has mentioned in 2017 that if PSTN gateway is located in India, this remains strictly restricted. If the PSTN is in another country and a VoIP phone is in India and if connection results in revenue loss to Indian telecom service providers, the connection gets considered restricted. 

Hope this helps!

Thanks
Sri

**Comment by sowjanya365** [comment]
Hi @scanum 

This can be closed now. Thank you!

**Comment by scanum** [comment]
@tmaheshwar Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
