### ISSUE TITLE
Tracking Information

### ISSUE THREAD

**Issue by joshrpg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3497]
The document should also state what folder and registry keys need to be tracked for nonpersistent desktops so that user settings are tracked from session to session. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-for-vdi#feedback)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@joshrpg  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by pendoza** [comment]
Hi any updates on this? I just installed in on our 2016 Citrix VDA and want to include the right registry and folders but I cannot find it anywhere on the internet.

**Comment by sowjanya365** [comment]
Hi @joshrpg 

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Hope this helps. Thank you!

**Comment by scanum** [comment]
@joshrpg Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
