### ISSUE TITLE
Please add private channels limit (currently 30)

### ISSUE THREAD

**Issue by SjoerdV** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3499]
Please add private channels limit (currently 30...) to the document.

On a personal note: I really hope this limit will change soon, as this is not practical at all...
Vote here:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/38464753-remove-the-limit-for-the-number-of-channels-in-a-t
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/38976634-increase-private-channel-limit-from-30-to-at-least
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/18635230-channel-limit-increase-beyond-200-limit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@SjoerdV  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by msbemba** [comment]
@SjoerdV Thank you for the feedback. We have added the information about private channels limit via PR # https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/3538

Thanks
Sri

**Comment by sowjanya365** [comment]
Hi @scanum 

This can be closed now. Thank you!

**Comment by scanum** [comment]
@SjoerdV Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
