### ISSUE TITLE
unable to utilize the -MembershipType switch

### ISSUE THREAD

**Issue by TimShegrud** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3503]
I am trying to get a list of the 'Standard' team channels.  The process documented is failing:

Get-TeamChannel -GroupId $GroupID -MembershipType Private
Get-TeamChannel : Error occurred while executing
Code: BadRequest
Message: The query specified in the URI is not valid. The string 'Microsoft.Teams.GraphSvc.channelMembershipType'private'' is not a valid enumeration type constant.
InnerError:
  RequestId: f8d3db34-31fe-4edd-a8b0-2363656b1817
  DateTimeStamp: 2019-11-25T22:29:59
HttpStatusCode: BadRequest
At line:1 char:1
+ Get-TeamChannel -GroupId $GroupID -Member ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-TeamChannel], ApiException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdlets.PowerShell.Custom.GetTeamChannel

PS C:\WINDOWS\system32> Get-Module -Name MicrosoftTeams -ListAvailable

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     1.0.18     MicrosoftTeams                      {Add-TeamChannelUser, Add-TeamUser, Set-TeamArchivedState, Get-CsPolicyPackage...}

**Comment by scanum** [comment]
@TimShegrud 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
