### ISSUE TITLE
Installing Bot for Testing

### ISSUE THREAD

**Issue by nitishr06** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3504]
Hi Team,
After uploading the app package, when I tried to install bot for the testing from Test and Distribute section, it's giving me an error "You don't have permissions to add #bot_name to this team." when i clicked on intall button. kindly guide me what permisson i require to install the bot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1257b9b-73ca-8a97-3f65-a7c8d5937e8c
* Version Independent ID: 5f9b5fad-dceb-3f9e-192c-a31ca05e0b83
* Content: [Add bots for private chats and channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/add-bots)
* Content Source: [Teams/add-bots.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/add-bots.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
