### ISSUE TITLE
SfB* mode with onpremise PSTN

### ISSUE THREAD

**Issue by szymonslipek** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3505]
Hi,
We are currently with S4B onprem with PSTN. We would like to start using Direct Routing in Teams.
I am not exactly sure which modes I can use during transition
Steps:
1. We need to setup hybrid and configure all policies in onprem and online
2. "Direct Routing" users need to be in Teams Only mode
3. What about rest of the users - Should we stay in Island mode or it's possible to shift them to one of SfB* modes and keep onpremise PSTN system?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49921e8a-55ac-f547-d4e2-d329f5089c2e
* Version Independent ID: 91c3433a-3684-95cd-3426-4a5877b33106
* Content: [Migration and interoperability guidance for organizations using Teams together with Skype for Business - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/migration-interop-guidance-for-teams-with-skype#feedback)
* Content Source: [Teams/migration-interop-guidance-for-teams-with-skype.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/migration-interop-guidance-for-teams-with-skype.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@szymonslipek  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by msbemba** [comment]
@szymonslipek Thank you for the feedback. This is more of a service request and we will have to find out more about your environment and help you out with a smooth migration. It would be best to contact the support team so that a dedicated engineer can work with you to transition.

@scanum  Can you provide @szymonslipek  with the support contact information?

Thanks
Sri

**Comment by scanum** [comment]
@szymonslipek thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
