### ISSUE TITLE
Step 1 prequisites.

### ISSUE THREAD

**Issue by dave-007** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3506]
How does one access 'Microsoft Teams admin center', what roles grant access?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams guest access checklist - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist#feedback)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by dave-007** [comment]
Access url is  https://admin.teams.microsoft.com

What roles or reole permissions have rights to enable Guest Access? Must I be AD Global Admin

**Comment by scanum** [comment]
@dave-007  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by msbemba** [comment]
@dave-007 Thank you for your feedback. We have added the information to the article via PR # https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/3537

You need to be a Global administrator or a Team's administrator to make these changes.

Thanks
Sri

**Comment by sowjanya365** [comment]
Hi @scanum 

This can be closed now. Thank you!

**Comment by scanum** [comment]
@dave-007 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
