### ISSUE TITLE
Step 5, Sharepoint/Settings/Sharing UI changed

### ISSUE THREAD

**Issue by dave-007** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3507]
Sliders for Sharepoint & OneDrive sharing, 
Some additional/advanced settings, how do they affect teams?

'Allow guests to share items they don't own'
'Limit external sharing to specific security groups'
'Shorten links or change their default permission'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams guest access checklist - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist#feedback)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by dave-007** [comment]
![2019-11-26 06_50_17-SharePoint admin center](https://user-images.githubusercontent.com/240789/69628935-efb40280-1019-11ea-908e-96a5bddb6dcd.png)

Help should reflect the additional UI options that have been added. What else affects Teams functionality here?

**Comment by scanum** [comment]
@dave-007  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by msbemba** [comment]
@dave-007 Thank you for your feedback. We have modified the screenshot via PR # https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/3536

Thanks
Sri

**Comment by scanum** [comment]
@dave-007 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
