### ISSUE TITLE
Meetings in private channels

### ISSUE THREAD

**Issue by ljr55555** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3509]
It appears that private channels are filtered out of the Teams/channel listing when scheduling a meeting. While "Meet now" can be used to initiate a meeting in a private channel, "Schedule a meeting" is not an option. It would be helpful to add documentation around this restriction.

**Comment by scanum** [comment]
@ljr55555 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
