### ISSUE TITLE
Suggested pages cannot be added as tabs

### ISSUE THREAD

**Issue by momoski** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3510]
In the instructions you say create a web tab to the Teams Documentation https://aka.ms/SuccessWithTeams which points to a page in https://docs.microsoft.com.

However, none of the web tabs to pages in docs.microsoft.com work. In Edge an error is displayed saying the content can't be shown in a frame. This is cumbersome especially since these tabs are suggested as starting points for users to drive adoption.

In Teams client this problem does not occur.

**Comment by scanum** [comment]
@momoski Please link the documentation you are referring to. Thanks!

**Comment by msbemba** [comment]
@momoski  Thank you for your feedback. Can you provide us the document that you are referring to? 

Are you referring to the instructions mentioned on the Teams on web Client?

Thanks
Sri

**Comment by scanum** [comment]
@momoski We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
