### ISSUE TITLE
Feature Differences for Meeting Modes

### ISSUE THREAD

**Issue by adagioajanes** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3511]
When selecting a meeting mode (Skype for Business (default) with Microsoft Teams, Skype for Business with Microsoft Teams (default), and Skype for Business), different features are hidden based on what you select. For example, the dial pad is not present when you set Teams as the default, whereas the dial pad is present when Skype for business is set as the default. I'd like to see a table that outlines those feature differences.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/console#feedback)
* Content Source: [Teams/room-systems/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/console.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@adagioajanes  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @adagioajanes 

Thank you for reaching out!

Please refer to the following link for the requested details. 

https://docs.microsoft.com/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability

Hope this helps. Thank you!

**Comment by scanum** [comment]
@adagioajanes Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
