### ISSUE TITLE
Changes to policies take a while to come through

### ISSUE THREAD

**Issue by PaulBullivant** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3512]
It seems that changes to policies take a while to come through.  Could you add a note to this article warning of the same.  I kept changing policies and couldn't work out why I was not able to install my hello world app.  A note here would have been helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d51bb7b1-801e-6801-dcaf-afa3e38e6941
* Version Independent ID: d8e726a1-cbf2-53c7-da4d-cc155b48612b
* Content: [Manage custom app policies and settings in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-custom-app-policies-and-settings#feedback)
* Content Source: [Teams/teams-custom-app-policies-and-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-custom-app-policies-and-settings.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@PaulBullivant  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by msbemba** [comment]
@paulbrittain  Thank you for your feedback. We have modified the document to reflect the delay that policy takes after editing. This can be tracked via PR # https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/3534

Thanks
Sri

**Comment by sowjanya365** [comment]
Hi @scanum 

This can be closed now. Thank you!

**Comment by scanum** [comment]
@PaulBullivant Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
