### ISSUE TITLE
How to get to admin center

### ISSUE THREAD

**Issue by PaulBullivant** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3513]
On the org settings, can you make the reference to Microsoft Teams admin center a hyperlink?  I was unable to find the admin centerand had to google it to work out how to get to the admin center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d51bb7b1-801e-6801-dcaf-afa3e38e6941
* Version Independent ID: d8e726a1-cbf2-53c7-da4d-cc155b48612b
* Content: [Manage custom app policies and settings in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-custom-app-policies-and-settings#feedback)
* Content Source: [Teams/teams-custom-app-policies-and-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-custom-app-policies-and-settings.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@PaulBullivant  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by msbemba** [comment]
@PaulBullivant Thank you for the feedback. We have added a hyperlink to the doc via PR# https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/3533

Thanks
Sri

**Comment by sowjanya365** [comment]
Hi @scanum 

This can be closed now. Thank you!

**Comment by scanum** [comment]
@PaulBullivant Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
