### ISSUE TITLE
What does the solid gray (gray/blue) dot mean?

### ISSUE THREAD

**Issue by ASloaneBLKB** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3514]
I see the outlined gray circle is Status Unknown, but I see 3 of my coworkers with solid gray dots, and I am not sure what that means

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a162ef5c-3099-7f58-4178-d29e3ec2b5a7
* Version Independent ID: 6ca31e56-052d-6c62-1323-b5aaaae1f04a
* Content: [User presence in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/presence-admins#feedback)
* Content Source: [Teams/presence-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/presence-admins.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@ASloaneBLKB  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by daurkin** [comment]
Is this related to the Note that "Skype must be installed" to see presence when in Teams Only Mode?  If so, I would love to hear if there is an update.  Our company just recently removed Skype from majority of our users during the Office 365 upgrade and told people to use Teams.  They really don't want to push out Skype back to the users especially when it won't allow them to use it.  I'm trying to provide a idea of when will be be fixed.

**Comment by sowjanya365** [comment]
Hi @ASloaneBLKB 

Thank you for submitting feedback. I think the best way forward is if you open a service ticket in your tenant so this can get addressed ASAP. Based on the outcome let me know if it is something that can 
be called out in the docs. 

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

Thank you!

**Comment by scanum** [comment]
@ASloaneBLKB Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
