### ISSUE TITLE
Private channel site collection provisioning takes very long time. 

### ISSUE THREAD

**Issue by akashSharma2505** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3515]
I am provisioning private channel and a power point tab using MS Graph api. There are two issues.

1. The site provisioning take randomly a lot of time. 4-7 minutes. I have to wait in my azure functions to let the site get provisioned. Is there a way to check the status when site get's provisionined ?

2. The library folder doesn't get provisioned untill I click on the Files tab in private channel.

**Comment by scanum** [comment]
@akashSharma2505 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
