### ISSUE TITLE
Is AudioConferencing Available in India?

### ISSUE THREAD

**Issue by RamlingaReddy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3517]
The content is confusing :
Is Audio Conferencing available for purchase?
No
Are phone numbers automatically assigned for Audio Conferencing?
Yes, for:
Chennai
Mumbai
Could you please clarify how we could purchase/use audio conferencing and phone system in India?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: add0081a-1bc7-51fa-845b-7ed394f16bb6
* Version Independent ID: 111b52ae-0b89-6cca-372c-549f4a7055b5
* Content: [Availability in India - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-india)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-india.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-india.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@RamlingaReddy  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by msbemba** [comment]
@RamlingaReddy  Thank you for the feedback. Yes, Audio conferencing is available in India and I have made the correction in the document via PR# https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/3532


Pricing for Audio Conferencing
If you have Office 365 E5, Audio Conferencing is included. 
 If you have Office 365 E1 or E3, Audio Conferencing is available for a ₹ 265/month add-on fee.

You can check below link for more information

https://products.office.com/en-in/microsoft-teams/online-meeting-solutions

**Comment by kenwith** [comment]
@RamlingaReddy we got word from the PM that owns this area, @ruizoscar  that he is not ready to update the doc with PR #3532  yet. Looking at the link that @msbemba provided it seems like it is saying audio conferencing is available but the PM is telling me it is not yet. So, we are tracking this down and will get this figured out. I apologize it is so confusing. We will keep this issue open and update this thread once we reconcile the information. @RamlingaReddy  also, I just wanted to say thank you for taking the time to bring this up. I know it takes time and I appreciate it so that it gets on our radar where we need to improve the messaging and docs.

**Comment by neerajsaran** [comment]
@kenwith @msbemba 
Is there any update on this? We need this feature. Can we go ahead and buy this add-on?

**Comment by kenwith** [comment]
@ruizoscar - any update?

**Comment by scanum** [comment]
@ruizoscar Hi Oscar! Any update on this? Thanks!

**Comment by scanum** [comment]
@ruizoscar Hi Oscar! Any update on this? Thanks!

**Comment by scanum** [comment]
@ruizoscar Hi Oscar! Any update on this? Thanks!

**Comment by rjagiewich** [comment]
@RamlingaReddy and @scanum  - Per @ruizoscar, we updated the page you referenced to state that audio conferencing isn't available in India. The content should be live shortly. I'm closing this issue now. Thank you for bringing this to our attention!
