### ISSUE TITLE
What about everyone having to wait in the lobby?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3518]
The article states, "These settings control which meeting participants wait in the lobby before they are admitted..." but the settings seem to only apply to anon users while everyone in the organization automatically gets admitted.  What if the meeting hosts wants everyone--including people in the organization--to wait in the lobby until he/she starts the meeting?  I don't see an option for that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams#automatically-admit-people)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@Canis-Lupis  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@Canis-Lupis although [this option](https://support.office.com/en-us/article/decide-who-has-to-wait-in-the-lobby-to-get-in-to-a-skype-for-business-meeting-c6f26fc7-1f22-41b5-a775-33141e44d7f4) exists for Skype for Business, it does not for Teams, at the moment. There is a request on [UserVoice](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/38309602--no-one-choice-in-the-lobby) to implement this. I recomment commenting there and following-up to get this implemented.

https://microsoftteams.uservoice.com/forums/555103-public/suggestions/38309602--no-one-choice-in-the-lobby

**Comment by sowjanya365** [comment]
Hi @scanum 

This can be closed now. Thank you!

**Comment by scanum** [comment]
@Canis-Lupis Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
