### ISSUE TITLE
Need external firewall details.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#352]
Can you please include external firewall details? Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5164207-7822-cf54-717e-6216e0627ebd
* Version Independent ID: 786f5413-3660-06eb-484f-8d5758d3ec59
* Content: [Port and protocol requirements for servers](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/network-requirements/ports-and-protocols)
* Content Source: [Skype/SfbServer/plan-your-deployment/network-requirements/ports-and-protocols.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/network-requirements/ports-and-protocols.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
We don't prescribe what sort of firewall you have to use. It could be either a server filling that role or an appliance. What matters is what ports are whitelisted so various protocols can use them.
