### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MySkypeLab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3520]
There are two countries listed as using AL which is not correct:

Albania: AL
Anguilla: AL

I assume that Albania is the correct country for AL. There's probably not a lot of deployments on the island of Anguilla but does another designation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a420204-479f-d8c9-ea30-9f07431b4b42
* Version Independent ID: a67787ef-c6ac-74bb-baef-5835391b5949
* Content: [Direct Routing country codes - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-country-codes)
* Content Source: [Teams/direct-routing-country-codes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-country-codes.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@MySkypeLab  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by CarolynRowe** [comment]
This has been fixed and will go live soon.  Thank you for the feedback.
