### ISSUE TITLE
Licencing Update

### ISSUE THREAD

**Issue by MySkypeLab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3521]
This page currently only lists:

Required licenses:
Office 365 Enterprise E3 (including SfB Plan2, Exchange Plan2, and Teams) + Phone System
Office 365 Enterprise E5 (including SfB Plan2, Exchange Plan2, Teams, and Phone System)

This should also include "Office 365 Enterprise E1 + Phone System" as a supported licence configuration for Direct Routing (Nikolay Muravlyannikov confirmed for me that there wasn't any limitations with this licence configuration). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df318fdb-6d58-86f8-de31-6eca533a9746
* Version Independent ID: a2248abf-bdf0-2c22-2604-74b482156684
* Content: [Configure Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-configure)
* Content Source: [Teams/direct-routing-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-configure.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@MySkypeLab  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@MySkypeLab Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
