### ISSUE TITLE
Incorrect Text

### ISSUE THREAD

**Issue by NeilPetersen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3522]
Hi,
'"Unauthenticated callers can be the first person in a meeting' should now read 'Dial-in callers can be the first person in a meeting'

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b4d417-8a1f-daca-381a-b1beed2dbdac
* Version Independent ID: d3e59d94-b0b7-fdfc-3a04-00dc4188e63d
* Content: [Start an Audio Conference over the phone without a PIN in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/start-an-audio-conference-over-the-phone-without-a-pin-in-teams)
* Content Source: [Teams/start-an-audio-conference-over-the-phone-without-a-pin-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/start-an-audio-conference-over-the-phone-without-a-pin-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@NeilPetersen  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@NeilPetersen Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
