### ISSUE TITLE
Not clear information

### ISSUE THREAD

**Issue by sho74** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3523]
Hi, gents. In your article it is mentioned many times about OPEN PORTS like in "For media bypass, Microsoft uses a version of Transport Relays that requires opening ports 50 000 to 59 999 between the Teams Transport Relays and the SBC (in the future we plan to move to the version which requires only 3478 and 3479 ports)". BUT it is not clear is it TCP or UDP ports, especially for 50000 - 59999. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10b198f4-9576-a14d-4359-1e8cc0319cda
* Version Independent ID: ba7c3252-21d4-9be1-2a84-de2d51646f7b
* Content: [Plan for media bypass with Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan-media-bypass)
* Content Source: [Teams/direct-routing-plan-media-bypass.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan-media-bypass.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@sho74  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@sho74 Ports 3478, 3479, 3480, 3481 are UDP. You can find [here](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252fen-us%252farticle%252fOffice-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2#skype-for-business-online-and-microsoft-teams) the list of needed ports.

50000-59999 is needed if you are in a hybrid scenario, with On-premises Skype for Business and Teams. And that's TCP/UDP:

https://docs.microsoft.com/en-us/microsoftteams/qos-in-teams

![image](https://user-images.githubusercontent.com/41186174/71805036-d1581280-306d-11ea-9738-d03dfff281e5.png)

More details on this topic here:

https://techcommunity.microsoft.com/t5/microsoft-teams/ports-needed-for-microsoft-teams/m-p/28417

https://julianfrank.wordpress.com/2017/10/03/understanding-media-flows-in-microsoft-teams-my-notes/

https://techcommunity.microsoft.com/t5/microsoft-teams/meetings-high-ports-network-planning-for-microsoft-teams/m-p/344490#U344490

**Comment by sowjanya365** [comment]
Hi @scanum 

This can be closed now. Thank you!

**Comment by scanum** [comment]
@sho74 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
