### ISSUE TITLE
Clarity on Prerequisites 

### ISSUE THREAD

**Issue by Gweffs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3525]
In the below statement you are excluding M365 Enterprise plans? Does this mean it is not supported?

"User has an Office 365 E1, E3, E5, A1, A3, A5, M365 Business, Business Premium or Business Essentials"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording#feedback)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@Gweffs Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Anooprayas** [comment]
Greetings,
Is there a option to make setting as below?
"If anybody of the meeting participant/Organizer starts the meeting recording, it should disable to other participants."

**Comment by Reeced40** [comment]
@Gweffs thank you for reaching out and helping improve MS Docs.  Anything that is not directly mentioned in the article is usually not supported.  Let me double check with the team and get back to you soonest.

**Comment by sowjanya365** [comment]
Hi @scanum 

This can be closed now. Thank you!

**Comment by scanum** [comment]
@Gweffs Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
