### ISSUE TITLE
Open in Shareppoint Link for General Channel goes to wrong location

### ISSUE THREAD

**Issue by jordonedavidson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3526]
On a new Teams Site, created from either the Teams admin for from a Team enabled SharePoint site, Clicking on the ellipsis menu beside the General title in the main area links to the first teams enabled SharePoint site on the tenant.

Clicking on the Files tab of the channel then the Open in SharePoint link in the horizontal menu goes to the correct location. From then on the main Open in SharePoint link (as above) links to the correct location.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
