### ISSUE TITLE
Teams for Outlook

### ISSUE THREAD

**Issue by diegarchovilla** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3527]
hi.

hi guys.

i have a problem when a try to create a meeting with Teams.

throw me a notificacion about it: try later etc

im reinstall office, complements and teams but still problem

somebody help me please?

PD: my english is rusty

![image](https://user-images.githubusercontent.com/58338480/69880020-ad9ff080-12a7-11ea-9db0-d327a6880931.png)

**Comment by scanum** [comment]
@diegarchovilla Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by diegarchovilla** [comment]
after formatting teams works perfectly but is not a rational option.

so i open a service ticket. bb2

tks
