### ISSUE TITLE
Follow this channel

### ISSUE THREAD

**Issue by osmayqc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3528]
Hello,

I want the new posts in a specific channel can be seeing in Activity label, I configured All new posts Banner and feed in Channel notification settings, but when I send a email to the channel I have anything, the channel is not bold and the new post is not in activity.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
