### ISSUE TITLE
Can add download link.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#353]
Link to download would be very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ce7a531-5b1f-f404-50a3-58eb285a0a1a
* Version Independent ID: 61d27af3-cfd6-ed7f-102c-072721db0209
* Content: [Plan for Meetings clients (Web App and Meetings App)](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/meetings-clients)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/meetings-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/meetings-clients.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Actually, that's not how it works. "You can't pre-install either the Skype for Business Web App or Skype Meetings App" The apps are downloaded as part of meeting join if an SfB client is not detected. So it's not really possible to give a link to an installer package.
