### ISSUE TITLE
Adding multiple users as owner while creating Private Channel

### ISSUE THREAD

**Issue by akashSharma2505** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3530]
When I am creating private channel with multiple users as owner, the channel get's created with all users as owners but corresponding sharepoint site doesn't get provisioned.

As a workarround I had to add first users as owner and rest with empty array of roles attribute as shown below. 
  "roles":[]

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
