### ISSUE TITLE
Microsoft 365 Licensing

### ISSUE THREAD

**Issue by adrianwells** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3539]
Please update the licensing table &lt;https://docs.microsoft.com/MicrosoftTeams/security-compliance-overview#licensing&gt; to include Microsoft 365 licensing (such as Microsoft 365 Business, E3, and E5) and the features that are included in each. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca579d63-182b-d6f5-8777-79248fa27ed9
* Version Independent ID: b4c27d1b-b2f1-41ac-b15c-d12b448a539e
* Content: [Overview of security and compliance in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/security-compliance-overview)
* Content Source: [Teams/security-compliance-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/security-compliance-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@adrianwells Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@adrianwells Thank you, I will revert soonest.

**Comment by Reeced40** [comment]
Hi @LolaJacobsen just checking if this update is in the pipeline and if you'd like me to do a PR to include certain information.

**Comment by scanum** [comment]
@LolaJacobsen Hi Lola, could you help us validating that the info should be added? Thanks!

**Comment by LolaJacobsen** [comment]
Assigning to @tonysmit who owns licensing documentation.

**Comment by scanum** [comment]
@tonysmit Hi Tony! Any updates on this? Thanks!

**Comment by scanum** [comment]
@tonysmit Hi Tony! Any updates on this? Thanks!

**Comment by tonysmit** [comment]
@Scanum For information on determining the licensing needs to implement features for security and compliance, please review Licensing for Office 365 or Microsoft 365.  Here is the link for the Microsoft 365 link text: http://download.microsoft.com/download/8/7/7/877B1713-671E-43AA-BB79-AF8478C64AFF/Licensing-Microsoft-365.pdf  Thanks. Tony

**Comment by scanum** [comment]
@Reeced40 @lindspea
