### ISSUE TITLE
Can't found Teams PSTN Pools

### ISSUE THREAD

**Issue by bastienczl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3541]
Hi,

I can't found this dashboard in the Teams administration. I have tested on many tenants but I can have only the Skype version of it (in Legacy Portal). It's not deployed on all tenants yet ?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8107d4a3-a55e-4891-ee72-27f79f647a1e
* Version Independent ID: b71f24c6-b54d-8a0f-ea0e-8839ff5481a4
* Content: [Microsoft Teams PSTN minute pools report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/pstn-minute-pools-report#feedback)
* Content Source: [Teams/teams-analytics-and-reports/pstn-minute-pools-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/pstn-minute-pools-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by Rapthor80** [comment]
Same here.

**Comment by scanum** [comment]
@bastienczl thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
