### ISSUE TITLE
CreateSRSMedia.ps1 error

### ISSUE THREAD

**Issue by richeklund** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3542]
When I run CreateSRSMedia.ps1 under an Administrator PowerShell console, I get an error: “Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Version". At line:1 char:1” (Running it from C:\MTR\CreateSRSMedia.ps1).  No useful information on what went wrong provided. Any idea what could be wrong???

I opened a Premier Performance Support ticket, but haven't been able to get a tech who knows what that script is so far. :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/room-systems/console#feedback)
* Content Source: [Teams/room-systems/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/console.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by chrism0n** [comment]
I am getting the same error above as well.  Will update my version of PS and see if that fixes it.

**Comment by richeklund** [comment]
I finally figured it out. I have a profile.ps1 in my WindowsPowerShell directory in my documents folder. I didn't use it anymore, but had a "Write-Host" line in there, which I didn't comment out from when I did.

I was able to replicate it by deleting the contents of profile.ps1 and putting write-host "Test" in the file. Launching powershell then gives the error. If I delete, or delete the contents of profile.ps1 so there is no write-host entries, it works fine. Write-Output also gives the error when launching this script. I tried a few other commands, such as changing directories, and it worked fine, but write-host or write-output in the profile.ps1 broke the script.

Weird? Absolutely. But

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@richeklund thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by richeklund** [comment]
@scanum I have opened a service ticket, but they did not have any interest in fixing it. Hopefully the feedback here can help others with a similar issue in the future.
