### ISSUE TITLE
Document change request

### ISSUE THREAD

**Issue by MahendarReddyGujjula** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3543]
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md 

Skype for Business Server works with the following Microsoft .NET Framework versions:
• .NET 3.5
• .NET 4.5
• .NET 4.6.x
• .NET 4.7.1 (for Skype for Business Server CU 5 or later releases)

Skype for business also supports 4.7.2 and 4.8 as well.

This is confirmed by João Loureiro

Please make change to this Document

**Comment by scanum** [comment]
@MahendarReddyGujjula Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@MahendarReddyGujjula Thank you for pointing this out, I will investigate further and will have this document updated.

**Comment by scanum** [comment]
@MahendarReddyGujjula We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
