### ISSUE TITLE
Unable to use an app-password for MS Teams

### ISSUE THREAD

**Issue by picklesrein** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3544]
I enabled two-factor on my Office365 account with a nearly-impossible-to-type passphrase. I prefer to use easier-to-type app-specific passwords to authenticate for other apps but the login attempt in Teams continues to fail. Are app-specific passwords not allowed for authentication within MS Teams?

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
