### ISSUE TITLE
"If users aren't assigned and enabled with SharePoint Online licenses, they don't have OneDrive for Business storage in Office 365."

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3545]
This is not true.  We have dozens of users using OneDrive for Business with their E3 licenses but without SharePoint online being enabled for them (we don't want SharePoint enabled for them yet until they are trained).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60fd4eb7-6f1a-2dfa-27db-01c3a0d00f30
* Version Independent ID: c1688075-18bf-534d-f402-ee062840d83f
* Content: [How SharePoint Online and OneDrive for Business interact with Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sharepoint-onedrive-interact)
* Content Source: [Teams/SharePoint-OneDrive-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/SharePoint-OneDrive-interact.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Canis-Lupis Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@Canis-Lupis Thank you for reaching out, I will investigate further and come back with an answer.

**Comment by scanum** [comment]
@Canis-Lupis We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
