### ISSUE TITLE
Documentation needs updated to correct conflicting documentation pieces and updated supportability guidelines for LS2013 and SfB2015

### ISSUE THREAD

**Issue by NicholasBurkhammer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3546]
The line, "Cloud Voicemail only works with Skype for Business Server and Exchange Server 2019 or Exchange Online," is present in the document.  However, immediately after that there is a table showing both Lync Server 2013 and Skype for Business Server 2015 support Cloud VM.  Additionally, Exchange's blog at https://techcommunity.microsoft.com/t5/Exchange-Team-Blog/Retiring-Unified-Messaging-in-Exchange-Online/ba-p/608991 fully indicates support for migration of 2013/2015 On-Premise customers.  Need the documentation shored up to be clear and concise.  For example, the line, "Cloud Voicemail only works with Skype for Business Server and Exchange Server 2019 or Exchange Online," should be changed to, "Cloud Voicemail only works with Lync Server 2013, Skype for Business Server 2015, or Skype for Business Server 2019, and Exchange Server 2019 or Exchange Online."  Additionally, the migration paths do not cover Lync Server 2013 or Skype for Business Server 2015 customers going to Cloud VM directly after the deprecation of Exchange Online UM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 469ac0c8-5c06-7f7f-fe1d-8cadb205572a
* Version Independent ID: 5c9987d5-4c98-8115-55c8-f629dbd25799
* Content: [Plan Cloud Voicemail service for on-premises users - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-cloud-voicemail)
* Content Source: [Skype/SfbHybrid/hybrid/plan-cloud-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/plan-cloud-voicemail.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@NicholasBurkhammer Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by gi1995** [comment]
Further to this, while this documentation says "Cloud Voicemail only works with Skype for Business Server and Exchange Server 2019 or Exchange Online.", the documentation on Skype for Business Server 2015 to Skype for Business Server 2019 with Exchange 2013/Exchange 2016 suggests in step 4: "Set the hosted voicemail policy for each user moved to Skype for Business Server 2019 to use Cloud Voicemail." - suggesting that Cloud VM also works with SfB2019 and Exchange 2013/2016.
https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-um-migration#skype-for-business-server-2015-to-skype-for-business-server-2019-with-exchange-2013exchange-2016

**Comment by Reeced40** [comment]
@NicholasBurkhammer Thank you for reaching out, I am investigating with the team for further answers on how to solve this problem.

**Comment by scanum** [comment]
@dstrome  Hi David, wondering if you could aid with the following issue? thanks!

**Comment by scanum** [comment]
@dstrome Hi David, wondering if you could aid with the following issue? thanks!

**Comment by dstrome** [comment]
hi all, thanks for your messages. This will take some research so it may take me a few days to get an answer.

**Comment by TheITRx** [comment]
Hi Guys. Just checking in to see if anyone has any update on this. I"m currently working a project where we need a clarification regarding this certain topic. Thanks!

**Comment by dstrome** [comment]
I've sent a question to one of our PMs and I hope to have an answer soon.

**Comment by scanum** [comment]
@dstrome Any updates on this? Thanks!

**Comment by dstrome** [comment]
yup, I heard back from the PM a couple days ago and I'm asking more follow-up questions to make sure I understand the answer.

**Comment by dstrome** [comment]
Thank you for your patience. I've updated the topic and the changes will be published later this afternoon.
