### ISSUE TITLE
Private channel sharepoint link

### ISSUE THREAD

**Issue by jedimaster1974** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3547]
If I open the private channel in sharepoint, it looks like anyone with the link can open that document folder even if they are not a member of that private channel, will this be locked down?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels#feedback)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@jedimaster1974 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jedimaster1974** [comment]
Thanks for the update, any further details you need let me know.

**Comment by Reeced40** [comment]
@jedimaster1974 Thank you for reaching out, I will investigate further and will have an answer for you in no time.

**Comment by scanum** [comment]
@jedimaster1974 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
