### ISSUE TITLE
Planner tool doesn't work on Private Channels

### ISSUE THREAD

**Issue by MrHaanMan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3549]
Is this an intentional restriction? We'd like to be able to assign tasks to users who have been added to Private channels but the planner tool doesn't come up as an optional tab.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels#feedback)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@MrHaanMan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by hrr** [comment]
@MrHaanMan Was looking for the same feature just now. Seems like they are working on it:
"Currently, private channels support connectors and tabs (except Stream, Planner, and Forms). We're working on full apps support for private channels, including messaging extensions and bots."
https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels#what-you-need-to-know-about-private-channels

**Comment by Reeced40** [comment]
@MrHaanMan Hi there, please let me know if @hrr has answered your question. If not, feel free to reach out. Thank you.

**Comment by scanum** [comment]
@MrHaanMan We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by MrHaanMan** [comment]
Hi @scanum 
Sorry, I didn't see the notifications from this until now. 
Is there an ETA on implementing the private channel - planner functionality?

**Comment by TorstHH** [comment]
Hi,
I would also be interested to use the Planner App in private Channels.
Has anyone heared of a date by when this will be implemented?

**Comment by Kweck** [comment]
+1 here. Any ETA for this?
Currently the missing Planner in private channels are preventing us from using them at all.

**Comment by reharta** [comment]
Same issue, I really want this functionality. I am a teacher and it will be perfect for tracking individual student data in breakout tutoring.
