### ISSUE TITLE
What capacity of HDD is needed?

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#355]
HDD capacity for different servers is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82fab248-4cf6-bbca-f42a-271b7b80fdd8
* Version Independent ID: 83e6aecb-347c-dde0-156f-0e03da5c7447
* Content: [Capacity planning user model usage for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/capacity/user-model)
* Content Source: [Skype/SfbServer/plan-your-deployment/capacity/user-model.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/capacity/user-model.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by jyGwx4RwQJ** [comment]
>HDD capacity for different servers is missing.

The formatting for Memory and Disk for Tested Hardware Platform is wrong.  Three are two HHD disk specs listed under Memory.

**Comment by AndreaBarr** [comment]
@jamesrhea Could you please investigate this issue?
