### ISSUE TITLE
Response needs update for channels/<channelId>/filesfolder 

### ISSUE THREAD

**Issue by vinodupss** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3552]
https://graph.microsoft.com/beta/teams/<group_id>/channels/<channel_id>/filesFolder
Response of the above endpoint needs to be updated to 

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#teams('6affa1b3-d856-435f-8481-fd6781fe9335')/channels('19%3A7cbbb34773a846f694c0dd5a78f4509a%40thread.skype')/filesFolder/$entity",
    "id": "01SSNAZ7JX6XKLOUVI5JFJUHPXMPGT7VVU",
    "createdDateTime": "0001-01-01T00:00:00Z",
    "lastModifiedDateTime": "2019-12-05T08:59:08Z",
    "name": "PrivateChannel",
    "webUrl": "https://test.sharepoint.com/sites/TestTeam-PrivateChannel/Shared%20Documents/PrivateChannel",
    "size": 0,
    "parentReference": {
        "driveId": "b!21KVXSMAR0u_jTXVm221CL3hgU8WUmVImd2HJO17_5OLRR4vZTwgS7YUEbfzqTBp",
        "driveType": "documentLibrary"
    },
    "fileSystemInfo": {
        "createdDateTime": "2019-12-05T08:59:08Z",
        "lastModifiedDateTime": "2019-12-05T08:59:08Z"
    },
    "folder": {
        "childCount": 0
    }
}

**Comment by scanum** [comment]
@thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
