### ISSUE TITLE
Teams Chat Retention Policy

### ISSUE THREAD

**Issue by microsoftsearch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3553]
I created a retention policy to delete Team's chats for users that is set to 14 days, but the documentation says that duration's shorter than 30 days aren't yet supported. It seems to have worked for one of the users I applied it to, but not the other. Am I understanding this documentation correctly? Is the policy not supposed to work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb40cf43-557e-d443-578b-49edca4a3179
* Version Independent ID: f78c9566-767f-bfae-7ba0-4e81d313034e
* Content: [Retention policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/retention-policies#feedback)
* Content Source: [Teams/retention-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/retention-policies.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@microsoftsearch Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@microsoftsearch Thank you for raising this issue! I'll be looking into it!

**Comment by TokyoScarab** [comment]
@LolaJacobsen Everything I can find points to 30 days still being the minimum retention policy for Teams. Can you confirm this or confirm a lower retention value that I can update in the documentation? Thanks!

**Comment by scanum** [comment]
@LolaJacobsen Could you please help with this issue? Thanks!

**Comment by LolaJacobsen** [comment]
Checking with PM Praveen Vijayraghavan

**Comment by LolaJacobsen** [comment]
@anwara-ms please review and let us know whether we need to make any documentation updates.

**Comment by scanum** [comment]
@anwara-ms Hi! Any update on this issue? Thanks

**Comment by anwara-ms** [comment]
Hi. The update is that around Nov-Dec'19 time, we updated the retention policy settings and now we allow users to set up to 1 day retention-delete or retention-hold policy.

**Comment by scanum** [comment]
@anwara-ms Thank you!

**Comment by scanum** [comment]
@microsoftsearch Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
