### ISSUE TITLE
Microsoft Teams stores data

### ISSUE THREAD

**Issue by labanex** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3554]
There is some good information about how Microsoft Teams stores chats and channels. I wish this was somewhere in the Microsoft Teams docs site.
https://www.recordpoint.com/microsoft-teams-compliance-features/ 
Please add some or all this information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e1b8fbb-3047-dd3a-6a9c-ae6b1d5a0222
* Version Independent ID: 42c418d1-8473-2243-81bc-558e0a0688aa
* Content: [Welcome to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-overview#feedback)
* Content Source: [Teams/Teams-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@labanex Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@labanex Thank you for raising this issue! I'll be looking into it!

**Comment by TokyoScarab** [comment]
@labanex There is a section of the Teams documentation that covers [security and data compliance](https://docs.microsoft.com/microsoftteams/security-compliance-overview). It appears to cover what is mentioned in the link shared. Is there anything in this section you thought was overlooked? Look forward to hearing back from you!

**Comment by scanum** [comment]
@labanex  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
