### ISSUE TITLE
Need clarification regarding local firewall rules

### ISSUE THREAD

**Issue by baardhermansen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3557]
In Notes that starts with "Windows Firewall configuration will be altered even when the prompt is dismissed by selecting “Cancel”", it states that two blocking rules are created. 
Does this mean that if a user cancels the dialog box, two inbound Public Blocking rules are created and if the user accepts, two incoming Domain Allow rules are created?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients#windows)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by GiantCrocodile** [comment]
I think this is what it means. I never approved the Windows Firewall dialog and never had connection issues so I can approve by experience that most likely it doesn't matter what you choose.

**Comment by scanum** [comment]
@baardhermansen Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by baardhermansen** [comment]
@scanum I work for an ISP, without access to the customers tenant. Nor do i have access rights in our company's tenant to open a service ticket. Therefore i'd appreciate if this issue could stay open and be answered.

**Comment by jaegerschnitzel** [comment]
upvote this user request https://microsoftteams.uservoice.com/forums/555103-public/suggestions/33697582-microsoft-teams-windows-firewall-pop-up
