### ISSUE TITLE
TE-SYSTEMS anynode version should be updated to 3.20.7

### ISSUE THREAD

**Issue by smpettit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3558]
Unless you are on anynode version 3.20.7 then call hold is broken since music on hold was released.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1a1c01-10a9-7f69-1c7b-1a566b0f5112
* Version Independent ID: 329ee759-40fc-98fb-b91e-87786c63024b
* Content: [List of Session Border Controllers certified for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-border-controllers#feedback)
* Content Source: [Teams/direct-routing-border-controllers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-border-controllers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@smpettit Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@smpettit Thank you for raising this issue! I'll be looking into it!

**Comment by CarolynRowe** [comment]
We have followed up with the product team, but their approval is required before we make a change to this document.  I am closing this issue.
