### ISSUE TITLE
Wrong version available 1.2.00.27559 instead of 1.2.00.31357 

### ISSUE THREAD

**Issue by JulienP78hk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3559]
Hello,
I Have tried to download the 1.2.00.31357 version using the provided links, unfortunately, I get the 1.2.00.27559 with them. How can I get the good one ?
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi#feedback)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by rbodeloche** [comment]
same issue. when the new msi package will be available ?

**Comment by scanum** [comment]
@thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by JulienP78hk** [comment]
Hello,
I am a Microsoft employee, i cannot open a service request on behalf of my customer.
Is there another way to handle it please?
Thanks
Julien

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Manuela Scanu <notifications@github.com>
Envoyé : Monday, December 9, 2019 8:00:11 AM
À : MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com>
Cc : Julien Pouget <Julien.Pouget@microsoft.com>; Author <author@noreply.github.com>
Objet : Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Wrong version available 1.2.00.27559 instead of 1.2.00.31357 (#3559)


@thank<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthank&data=02%7C01%7CJulien.Pouget%40microsoft.com%7Cc6c16395d9ff43a46a0a08d77c756f71%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637114716127532804&sdata=cirx%2FT2ojddVtTfA0OD%2FkwvRNkUQgRp4JZWvzzZh6gs%3D&reserved=0> you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Foffice365%2Fadmin%2Fcontact-support-for-business-products&data=02%7C01%7CJulien.Pouget%40microsoft.com%7Cc6c16395d9ff43a46a0a08d77c756f71%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637114716127532804&sdata=J%2F5InhX9eeXCUURWpGsxLVVAiJcwwQyxdiejC5wbf3Q%3D&reserved=0>
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by bf80** [comment]
I just found this by editing links manually, seems the current one:
https://statics.teams.cdn.office.net/production-windows-x64/1.3.00.362/Teams_windows_x64.msi
