### ISSUE TITLE
Teams cached content exclusion list for non-persistent setup

### ISSUE THREAD

**Issue by KZebergs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3561]
How do you exclude .txt files and files in general from FSLogix containers? I thought you can only exclude folders.. Please add a link to the instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi?source=docs#feedback)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@KZebergs Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@KZebergs Thank you for raising this issue! I'll be looking into it!

**Comment by TokyoScarab** [comment]
@KZebergs FSLogix only supports a folder exclusion system. If you need to exclude individual files, you would have to manage them in such a way that would support a folder only system or, if possible, use a different manager solution to fit your needs.
