### ISSUE TITLE
FOC entry doesn't make sense for column "Can you edit the order"

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3568]
The column "Can you edit the order" has "Firm Order Commitment (FOC)" in the row "transfer approved". 

Saying "FOC" doesn't answer the question of whether or not I can edit the order. This cell should just say "No".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07fd02a2-78ae-519f-ec11-f337debcaf9a
* Version Independent ID: a2a489c3-9204-2b63-85fa-ba9e535fdc94
* Content: [What's the status of your port orders? - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/phone-number-calling-plans/port-order-status#feedback)
* Content Source: [Teams/phone-number-calling-plans/port-order-status.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phone-number-calling-plans/port-order-status.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@TorrenManson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@TorrenManson Thank you for raising this issue! I'll be looking into it!

**Comment by scanum** [comment]
@TorrenManson Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
