### ISSUE TITLE
Need examples and figures.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#357]
Screenshots and working examples would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93a5dbaa-9d07-6432-271b-260b46c967ee
* Version Independent ID: 7009790c-b09f-06cd-3b06-26df67579bf7
* Content: [Network settings for the advanced Enterprise Voice features in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/enterprise-voice-solution/network-settings-for-advanced-features)
* Content Source: [Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/network-settings-for-advanced-features.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/network-settings-for-advanced-features.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by AndreaBarr** [comment]
@kellipav Please investigate this issue.

**Comment by get-itips** [comment]
Hi, thanks for your feedback.
Written information is prefered in documents so it favours the indexation of the document.
But you can find working examples in Example: Gathering Requirements.
Thank You.
