### ISSUE TITLE
Issue with license assignment in script SkypeRoomProvisioningScript.ps1

### ISSUE THREAD

**Issue by neilmallon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3570]
Hi team,
I have noticed an issue where the SkypeRoomProvisioningScript.ps1 script linked to at the top of the page is not able to assign a license from the list where there are single digits. Eg for my tenant the 'meeting room' sku is #8 in the list. No single digit skus work. They only way for the script to proceed is to enter a double digit sku from 10 upwards, then go and manually add the license in the O365 portal. Also tried double digit '08' but no joy.
Thanks
Neil

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/room-systems/with-office-365#feedback)
* Content Source: [Teams/room-systems/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/with-office-365.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@neilmallon Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@neilmallon thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by neilmallon** [comment]
> @neilmallon thank you for submitting feedback.
> I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
> Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
> Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

Thanks - do doc needs updating (rather it is the script that needs updating) to allow single digit SKUs to be selected.  I am happy to manually resolve inside the tenant (which I have as per my original note).  Can you open / request somebody amends the PS script to work?

Thanks
