### ISSUE TITLE
Teams Fatclient not supported on Server OS

### ISSUE THREAD

**Issue by mobernberger** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3571]
In this article you are talking about Server OS requirements but Support and other sources told me, that the Teams Fatclient isn't supported on Server OS. So could you please clarify this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@mobernberger Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@mobernberger Thank you for raising this issue! I'll be looking into it!

**Comment by mobernberger** [comment]
Do we have any news on this one? Thanks

**Comment by TokyoScarab** [comment]
@LanaChin Would you be able to offer some insight on this question?

**Comment by LanaChin** [comment]
Looking into this.

**Comment by LanaChin** [comment]
Hi @mobernberger. The client isn't running on the server. It's running on a VM that's running on the server. Hope that helps to clarify. Thanks!
