### ISSUE TITLE
Where's the PowerShell commands for these GUI actions?

### ISSUE THREAD

**Issue by Coldry** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3572]
Hi,
When I find a page in the docs looking for help on how to set things up, I expect to see the PowerShell commands that have the same effect as the GUI steps you detail on the page.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a627b5d-3edc-1add-b921-1dcd49c38653
* Version Independent ID: a2e2bd3a-31c0-471a-05fb-fd64bd942c4a
* Content: [Manage your devices in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/device-management#feedback)
* Content Source: [Teams/device-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/device-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Coldry Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@Coldry  Thank you for raising this issue! I'll be looking into it!

**Comment by TokyoScarab** [comment]
@LanaChin After looking into the list of PS cmdlets for Teams, I don't see any commands that reference things on this page. I do know that another doc [page](https://docs.microsoft.com/microsoftteams/teams-powershell-overview) talks about Teams actions being split between the Teams module and the SFB module but wasn't able to find anything there either. Do you know if these cmdlets exist for the options on the page in question? Look forward to hearing back from you!

**Comment by LanaChin** [comment]
Looking into this.

**Comment by LanaChin** [comment]
Hi @Coldry - Thanks for your inquiry. I received info that currently, PowerShell cmdlets are not supported for actions on this page.
