### ISSUE TITLE
Add SSL.com to Public trusted certificate for the SBC

### ISSUE THREAD

**Issue by codelux** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3576]
SSL.com CA is currently a participant of the Microsoft Trusted Root Certificate Program. 

Can we add the SSL.com Roots listed in: 

https://gallery.technet.microsoft.com/Trusted-Root-Certificate-2696b664/file/180283/1/Trusted%20Root%20Program%20Participants%20As%20of%20Sept%2026%202017.xlsx 

to trusted CA listing at https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan#public-trusted-certificate-for-the-sbc ?

**Comment by weq** [comment]
What about using the current list instead?
https://ccadb-public.secure.force.com/microsoft/IncludedCACertificateReportForMSFT

ref: https://docs.microsoft.com/en-us/security/trusted-root/participants-list

**Comment by codelux** [comment]
Yes CCADB is an active and dynamic list so that is also a good source.

**Comment by scanum** [comment]
@codelux Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by codelux** [comment]
any update on this?

**Comment by TokyoScarab** [comment]
@codelux  Thank you for raising this issue! I'll be looking into it!

**Comment by codelux** [comment]
Hello @TokyoScarab are you able to move forward with the merge?

**Comment by codelux** [comment]
Hello @TokyoScarab any updates on this?

**Comment by codelux** [comment]
Hello I raised this over 2 months ago. Should we loop in members of the Microsoft Root CA Program to confirm this merge?

**Comment by TokyoScarab** [comment]
@CarolynRowe It appears what they have pointed out is correct. Are you aware of what processes are required to include SSL on the root list mentioned in the original post?

**Comment by CarolynRowe** [comment]
We need to get clarification from the PMs: @NMuravlyannikov or @FilippSe.  I will contact them.

**Comment by NMuravlyannikov** [comment]
Nope we first need to change code to support it. Please use drsbccertification@microsoft.com to submit the request

**Comment by CarolynRowe** [comment]
Thanks, Nikolay.  I am closing this issue,

**Comment by codelux** [comment]
Hello @CarolynRowe ,

SSL.com will be included in the March 20 sprint per the email below:

```
Hello Christopher,

This task is in our current sprint, meaning it should be released to production before Mar 20.

Thanks,
Vadim
```
Can we reopen this and do the merge after March 20?

**Comment by CarolynRowe** [comment]
I will check with Nikolay.

**Comment by NMuravlyannikov** [comment]
@CarolynRowe @FilippSe will add once we have the support of SSL,com in production

**Comment by codelux** [comment]
great, thank you!

**Comment by codelux** [comment]
Hello has SSL.com been added into production? Can we proceed with merging this commit?

**Comment by codelux** [comment]
Can we also add SSL.com ( https://www.ssl.com/certificates/ucc/ ) to this list as well?

https://docs.microsoft.com/en-us/skypeforbusiness/certification/services-ssl

**Comment by codelux** [comment]
I received an email from Vadim Genkin on April 7, 2020 that SSL.com Roots were rolled out into production. See the email below:

Hello Leo,

 

It was released to PROD.

 

Thanks,

Vadim
