### ISSUE TITLE
MSTeams Unable to assign phone number to Resource Account

### ISSUE THREAD

**Issue by milevmartin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3579]
I have created a new Resource account from MS Teams admin Center -> Org-Wide settings - Resource accounts - Add :

ExtensionData                          : System.Runtime.Serialization.ExtensionDataObject
AlternateEmailAddresses                : {}
AlternateMobilePhones                  : {}
AlternativeSecurityIds                 : {}
BlockCredential                        : True
City                                   :
CloudExchangeRecipientDisplayType      : 1073741824
Country                                :
Department                             : Microsoft Communication Application Instance
DirSyncProvisioningErrors              : {}
DisplayName                            : SupportRecreate
Errors                                 :
Fax                                    :
FirstName                              :
ImmutableId                            :
IndirectLicenseErrors                  : {}
IsBlackberryUser                       : False
IsLicensed                             : True
LastDirSyncTime                        :
LastName                               :
LastPasswordChangeTimestamp            : 09/12/2019 15:49:58
LicenseAssignmentDetails               : {Microsoft.Online.Administration.LicenseAssignmentDetail, Microsoft.Online.Administration.LicenseAssignmentDetail,
                                         Microsoft.Online.Administration.LicenseAssignmentDetail, Microsoft.Online.Administration.LicenseAssignmentDetail...}
LicenseReconciliationNeeded            : False
Licenses                               : {***:MCOEV, ***:MCOPSTN2, ****:ENTERPRISEPACK, ****:MCOPSTNC...}
LiveId                                 : 10032000901F28D6
MSExchRecipientTypeDetails             :
MSRtcSipDeploymentLocator              :
MSRtcSipPrimaryUserAddress             :
MobilePhone                            :
ObjectId                               : 1305231e-5d00-47eb-8710-e83a98537b3b
Office                                 :
OverallProvisioningStatus              : Success
PasswordNeverExpires                   :
PasswordResetNotRequiredDuringActivate :
PhoneNumber                            :
PortalSettings                         :
PostalCode                             :
PreferredDataLocation                  :
PreferredLanguage                      :
ProxyAddresses                         : {SMTP:*****@***.onmicrosoft.com}
ReleaseTrack                           :
ServiceInformation                     : {}
SignInName                             : ****@****.onmicrosoft.com
SoftDeletionTimestamp                  :
State                                  :
StreetAddress                          :
StrongAuthenticationMethods            : {}
StrongAuthenticationPhoneAppDetails    : {}
StrongAuthenticationProofupTime        :
StrongAuthenticationRequirements       : {}
StrongAuthenticationUserDetails        :
StrongPasswordRequired                 :
StsRefreshTokensValidFrom              : 09/12/2019 15:49:58
Title                                  :
UsageLocation                          : GB
UserLandingPageIdentifierForO365Shell  :
UserPrincipalName                      : ******@****.onmicrosoft.com
UserThemeIdentifierForO365Shell        :
UserType                               : Member
ValidationStatus                       : Healthy
WhenCreated                            : 09/12/2019 15:49:59

The account has Licenses:
Communication Credits, Audio Conferencing, Domestic and International Calling Plan, Phone System, Office 365 E3 

I also have Unassigned Service phone number that i need to assign to this Resource account.

But when i try to assign a phone number I have No results were found. 
Previously i was able to assign Licenses from SfB Portal. But now it is not possible.

So now the Questions is How to assign my Resource account a phone number...

**Comment by scanum** [comment]
@milevmartin 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
