### ISSUE TITLE
Need to find logfiles.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#358]
Where do SfB 2015 on-prem drop logfiles?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888fcfa7-e18a-f60d-734c-a38293e2baf0
* Version Independent ID: c85ef7a6-9323-5828-4544-c284f821c242
* Content: [Centralized Logging Service in Skype for Business 2015](https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/centralized-logging-service/centralized-logging-service)
* Content Source: [Skype/SfbServer/management-tools/centralized-logging-service/centralized-logging-service.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/management-tools/centralized-logging-service/centralized-logging-service.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi, thanks for your feedback.
You can find that information in attribute ETLFileFolder that is showed in Get-CsCLSConfiguration, cmdlet described in the referenced article.
Thank you
