### ISSUE TITLE
What could be the reason that Holidays do not appear under Org-wide settings?

### ISSUE THREAD

**Issue by jacobjohnk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3583]

**Comment by scanum** [comment]
@jacobjohnk 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
