### ISSUE TITLE
Please add .NET 4.8 (for Skype for Business Server CU 9 or later releases)

### ISSUE THREAD

**Issue by joaolloureiro** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3589]
Please add .NET 4.8 (for Skype for Business Server CU 9 or later releases) since .net framework 4.8 is supported starting with CU9

For further questions please contact me or check internal IcM 145317002

**Comment by scanum** [comment]
@joaolloureiro Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@joaolloureiro  Thank you for raising this issue! I'll be looking into it!

**Comment by TokyoScarab** [comment]
@joaolloureiro Is this a documentation related issue or a general request? I can help in any capacity on documentation issues only. Hope to hear back from you, thanks!

**Comment by joaolloureiro** [comment]
This is a documentation related issue. Please feel free to reach me directly.

**Comment by TokyoScarab** [comment]
@joaolloureiro What page of the documentation does this pertain to?

**Comment by joaolloureiro** [comment]
Basically this should be changed in https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/server-requirements 

Original text:

(...)
• .NET 4.7.1 (for Skype for Business Server CU 5 or later releases)
• .NET 4.7.2 (for Skype for Business Server CU 6 or later releases)
(...)

Should be changed to:

(...)
• .NET 4.7.1 (for Skype for Business Server CU 5 or later releases)
• .NET 4.7.2 (for Skype for Business Server CU 6 or later releases)
• .NET 4.8 (for Skype for Business Server CU 9 or later releases)
(...)

**Comment by LanaChin** [comment]
Update merged, thank you @joaolloureiro and @TokyoScarab .
