### ISSUE TITLE
Need detailed security information for SfB or link to that.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#359]
Need security information for SfB. Link to good source will be also helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96ceafbb-d3ce-6e1f-4a90-f54de0053a86
* Version Independent ID: e18a9aa7-c86e-1c69-0bff-daf5a56e77f6
* Content: [Common security threats in modern day computing](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/security/common-threats)
* Content Source: [Skype/SfbServer/plan-your-deployment/security/common-threats.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/security/common-threats.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi! thanks for your feedback
There is a whole section dedicated to security here https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/security/security
Thank you
