### ISSUE TITLE
Add information how to set the proxy for teams on Linux

### ISSUE THREAD

**Issue by graugans** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3592]
Thanks for porting Microsoft Teams to Linux. While playing with this behind a cooperate firewall and a proxy set-up I could not login. It seems you are using somehow a chromium backend and one could easily pass the proxy to the executable:

```
teams --proxy-server=http://localhost:3128
```

Maybe a link to the Microsoft Code network settings page is an option: https://code.visualstudio.com/docs/setup/network#_proxy-server-support

**Comment by scanum** [comment]
@graugans Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@graugans  Thank you for raising this issue! I'll be looking into it!

**Comment by TokyoScarab** [comment]
@graugans Would you be able to link the documentation page you were referring to when you made this post? Without that, I won't be able to help in your issue, thank you!

**Comment by graugans** [comment]
@TokyoScarab The link is already included in the initial issue. https://code.visualstudio.com/docs/setup/network#_proxy-server-support

**Comment by TokyoScarab** [comment]
@graugans I did see the link. I was referring to the microsoft docs page where you would want this change to be made.

**Comment by scanum** [comment]
@graugans  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by graugans** [comment]
@scanum unfortunatly I can not reopen the issue. Only _organisation-members/contributors/people-with-write-access-to-repo/something-similar_ have the ability to reopen issues. The best place to put this information I do see at the moment is: https://docs.microsoft.com/en-us/microsoftteams/get-clients#linux Or: https://docs.microsoft.com/en-us/microsoftteams/known-issues#linux

It seems it is my fault that I have expected that the document team at Microsoft does know where the best place to put information about the Network configuration.
