### ISSUE TITLE
Hyperlink on Note about Linux

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3593]
[Under Linux section:](https://docs.microsoft.com/en-us/microsoftteams/get-clients#linux)

![image](https://user-images.githubusercontent.com/14079228/70644569-46702d80-1c11-11ea-8ef9-5175bbc9de7c.png)

I suspect the intent was that too be a hyperlink but the **notes feature doesn't support it**? 🤔

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients#linux)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@spottedmahn Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@spottedmahn  Thank you for raising this issue! I'll be looking into it!

**Comment by TokyoScarab** [comment]
@spottedmahn Following up saying the issue has been resolved.

**Comment by spottedmahn** [comment]
Look at that, nice!

![image](https://user-images.githubusercontent.com/14079228/75448284-eac45f00-5938-11ea-90d3-d7e1ebf5aeb4.png)

**Comment by spottedmahn** [comment]
Wonder where the PR or commit link is? 🤔
