### ISSUE TITLE
Redirect to voicemail

### ISSUE THREAD

**Issue by callen-42** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3594]
Auto attendants in our tenant now show Voicemail as a 3rd option for 'redirect to'. This isn't covered in this article, would like to know more about this feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a42f9e2c-aeee-76c4-620a-668cce21ba10
* Version Independent ID: 6ff06eab-9c80-9c30-95ef-c17e157fbea1
* Content: [Set up a Cloud auto attendant - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-auto-attendant#feedback)
* Content Source: [Teams/create-a-phone-system-auto-attendant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-auto-attendant.md)
* Service: **msteams**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@callen-42 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by douglee57** [comment]
I have found that if you enter a distribution list as the destination then the voicemail will be emailed to the members of that list.

**Comment by TokyoScarab** [comment]
@callen-42  Thank you for raising this issue! I'll be looking into it!

**Comment by mozilla0** [comment]
It's also working for O365 groups so you could distribute Voicemails to many users

**Comment by KYTurp** [comment]
For me it worked on some O365 groups but not all

**Comment by SvenBell** [comment]
When will this feature be availble on all tenants? i have checked 2 different tenants and redirect to voicemail does not appear.

**Comment by TokyoScarab** [comment]
@callen-42 I see the "redirect to voicemail option" is included in the documentation page linked. Was there something specific you thought was missing in the documentation about it? Any info that could better help the documentation is welcome, thanks!

@SvenBell You are saying that the option to include a "redirect to voicemail" option is not available in some of your tenants, correct?

**Comment by SvenBell** [comment]
> @callen-42 I see the "redirect to voicemail option" is included in the documentation page linked. Was there something specific you thought was missing in the documentation about it? Any info that could better help the documentation is welcome, thanks!
> 
> @SvenBell You are saying that the option to include a "redirect to voicemail" option is not available in some of your tenants, correct?

It is all good now, the feature is finally showing up after 6 weeks.

**Comment by callen-42** [comment]
> @callen-42 I see the "redirect to voicemail option" is included in the documentation page linked. Was there something specific you thought was missing in the documentation about it? Any info that could better help the documentation is welcome, thanks!
> 
> @SvenBell You are saying that the option to include a "redirect to voicemail" option is not available in some of your tenants, correct?

Yes, I believe the page has been updated to include info on the feature. Thanks

**Comment by scanum** [comment]
@callen-42 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
