### ISSUE TITLE
Analytics and Reports in Teams Calling

### ISSUE THREAD

**Issue by KYTurp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3595]
when I look at the PSTN usage report, both the Caller and Callee phone numbers are the same for all calls.  whatever number initiated the call, (Caller) has their number in both the caller and callee fields.

We have configured Direct Routing and are trying to figure out why we do not see individual Caller and Callee numbers.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
