### ISSUE TITLE
Unregister command doesnt work

### ISSUE THREAD

**Issue by AndrewFrants** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3596]
The last step

Unregister-CsOnlineDialInConferencingServiceNumber -BridgeName “Conference Bridge” -RemoveDefaultServiceNumber 8005551234

Doesn't work, could it be due to quotes? 

Another alternative is to use:

Unregister-CsOnlineDialInConferencingServiceNumber -BridgeId <> -Identity 8005551234

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 485c3bcb-41f9-6873-bd04-2f4110d07655
* Version Independent ID: df1cd65a-1636-73b7-3245-674dfb6b86cf
* Content: [Change the phone numbers on your Audio Conferencing bridge - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/change-the-phone-numbers-on-your-audio-conferencing-bridge)
* Content Source: [Teams/change-the-phone-numbers-on-your-audio-conferencing-bridge.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/change-the-phone-numbers-on-your-audio-conferencing-bridge.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@AndrewFrants Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@AndrewFrants  Thank you for raising this issue! I'll be looking into it!

**Comment by TokyoScarab** [comment]
@AndrewFrants If you are referring to the quotes in “Conference Bridge”, those are needed because that parameter is a string. I presume you have the proper access requirements for using these commands. I cannot see anything wrong in the syntax of what is posted. Could you go into some more detail on your user case for this? Look forward to hearing back from you, thanks!

**Comment by scanum** [comment]
@AndrewFrants Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
