### ISSUE TITLE
Need clarification to understand better.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#360]
First, the very first sentence here.  What do you mean by , "to join a dial-in conference as an authenticated user"? By authenticated user, do you mean all meeting participants or is this specific to the meeting organizer? This needs to be clarified in the initial paragraph. Second, if this is specific to the meeting organizer, does the meeting organizer have to enter the pin when joining a call? What are the benefits of entering the pin?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff9c5d8a-d8e8-c774-3807-a43dc9595281
* Version Independent ID: d90bb974-9d00-2e44-b35d-2e44e0e3a3f2
* Content: [Set a user's dial-in conferencing PIN in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/manage/authentication/set-a-user-s-dial-in-conferencing-pin)
* Content Source: [Skype/SfbServer/manage/authentication/set-a-user-s-dial-in-conferencing-pin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/authentication/set-a-user-s-dial-in-conferencing-pin.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi! The document states is referring to a user: "To join a dial-in conference as an authenticated user, a Skype for Business Server user with Active Directory Domain Services (AD DS) credentials " Thank you
