### ISSUE TITLE
RegEx invalid

### ISSUE THREAD

**Issue by JensTrier** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3600]
This regex is invalid For example, ^+?911. It needs to be  ^\+?911

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0a230ba-f141-3a40-12de-03b05a316a52
* Version Independent ID: 402a7d5f-4736-0f8e-7bba-8af03484085e
* Content: [Manage emergency call routing policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/manage-emergency-call-routing-policies)
* Content Source: [Teams/manage-emergency-call-routing-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-emergency-call-routing-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by LanaChin** [comment]
Thanks @JensTrier. This is fixed in #3601
