### ISSUE TITLE
Private and Public - extra info

### ISSUE THREAD

**Issue by evandimsby** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3602]
It may be worth noting that another difference, particulary on the Sharepoint Online side, is that the "Everyone except external users" Group will be added when a Team is set to Public, and that group will have Edit permissions. 

Even though the team itself will NOT show in a non-member's Team app, the non-members CAN access the content on the Sharepoint Team Site if they type in the URL with the team name https://TenantID.sharepoint.com/teams/SomePublicTeam. It is an important item to note. In the event that an actual member is removed from the Team, if that former member had bookmarked any URLs, they will still be able to access all the team content and lead to confusion to the owner and other members.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c9902e8-a0b7-b6af-4656-2024849a5e8b
* Version Independent ID: 85beb9a7-2682-b52e-210b-20e598e3dab3
* Content: [Create your first teams and channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-started-with-teams-create-your-first-teams-and-channels)
* Content Source: [Teams/get-started-with-teams-create-your-first-teams-and-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-started-with-teams-create-your-first-teams-and-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@evandimsby Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@evandimsby  Thank you for raising this issue! I'll be looking into it!

**Comment by TokyoScarab** [comment]
Thank you for providing this extra information. I'll make sure to pass this information along to the Sharepoint Online team. 

@LanaChin do you have anything you could add onto this?

**Comment by scanum** [comment]
@LanaChin Could you please help on this issue? Thanks!

**Comment by LanaChin** [comment]
Looking into this

**Comment by TokyoScarab** [comment]
@LanaChin Were you able to find anything out?

**Comment by scanum** [comment]
@LanaChin Were you able to find anything out?

**Comment by scanum** [comment]
@LanaChin Any update on this issue? Thanks!

**Comment by LanaChin** [comment]
Yes, I'm following up with the PM on this. Thanks.

**Comment by TokyoScarab** [comment]
@LanaChin Any follow up information on this?

**Comment by scanum** [comment]
@LanaChin Any follow up information on this?

**Comment by scanum** [comment]
@LanaChin Any follow up information on this?

**Comment by TokyoScarab** [comment]
@LanaChin Just following up to see if there was any additional information on this. Thanks!

**Comment by LanaChin** [comment]
@TokyoScarab - confirmed with the PMs and the doc has been updated to reflect this. Thanks following up.
