### ISSUE TITLE
Missing embedded screenshot 'Deploy-Azure-Monitor-1.png'

### ISSUE THREAD

**Issue by neilmallon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3604]
After the first few lines in this doc there is some text showing "![Screen shot of sample Log Analytics view for Microsoft Teams Rooms](../media/Deploy-Azure-Monitor-1.png "Sample Log Analytics view for Microsoft Teams Rooms")" where it should show the screenshot. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c813d7c-1789-d0c9-c833-cbdd3f60e2b8
* Version Independent ID: e5b7e6a7-2f78-dd58-b450-0d173935e26c
* Content: [Deploy Microsoft Teams Rooms management with Azure Monitor - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/azure-monitor-deploy)
* Content Source: [Teams/room-systems/azure-monitor-deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/azure-monitor-deploy.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@neilmallon Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@neilmallon  Thank you for raising this issue! I'll be looking into it!

**Comment by LanaChin** [comment]
Merged the PR. Thanks @TokyoScarab and @neilmallon.

**Comment by scanum** [comment]
@neilmallon Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
