### ISSUE TITLE
Re: Issue with license assignment in script SkypeRoomProvisioningScript.ps1

### ISSUE THREAD

**Issue by neilmallon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3605]
Opening a new issue as the old one was closed unresolved/misunderstood and I cannot reopen.

*The script at the top of this doc is wrong and needs updating to allow single digit SKUs to be selected.

Ref: previous close notes; I can manually resolve inside my tenant (which I have as per my original note). Can you open / request somebody amends the PS script to work?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/with-office-365)
* Content Source: [Teams/room-systems/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/with-office-365.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@neilmallon Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@neilmallon Thank you for raising this issue! I'll be looking into it!
