### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#361]
Sql server 2014 and sql server 2012 sp2 and cu2 do not have sql server failover clustering.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8c5958a-c5e5-5aba-211a-2886c86ba831
* Version Independent ID: e53ed9d2-4ee4-346a-054b-6cf44b6a189b
* Content: [Back End Server high availability in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/high-availability-and-disaster-recovery/back-end-server)
* Content Source: [Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/back-end-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/back-end-server.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi! Thanks for your feedback
You can see here support for the versions you mentioned

https://docs.microsoft.com/en-us/sql/sql-server/failover-clusters/windows/windows-server-failover-clustering-wsfc-with-sql-server?view=sql-server-2014

https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2012/hh270278(v=sql.110)


Thanks
