### ISSUE TITLE
Groups in Microsoft 365

### ISSUE THREAD

**Issue by JohanssonMarkus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3612]
Time to update the poster I guess. There is not mention that O365 groups can be created from Power BI or Stream for instance. Please review and update accordingly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ad624-9792-91b7-c85f-09b839b1ea44
* Version Independent ID: e8288f91-11bd-599b-8a88-074917b315a4
* Content: [Microsoft Teams IT architecture and telephony solutions posters - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-architecture-solutions-posters)
* Content Source: [Teams/teams-architecture-solutions-posters.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-architecture-solutions-posters.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@JohanssonMarkus Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@JohanssonMarkus Thank you for raising this issue! I'll be looking into it!

**Comment by TokyoScarab** [comment]
@LolaJacobsen Do you think that the changes made above would necessitate any changes to the poster in question?

**Comment by LolaJacobsen** [comment]
@BrendaCarter this is about the O365 groups poster. Can you respond please?

**Comment by MikePlumleyMSFT** [comment]
@JohanssonMarkus, thanks for the feedback. This poster is on our list to update in the near term.

**Comment by scanum** [comment]
@MikePlumleyMSFT Hi Mike, wondering if there are any updates on this issue? Thanks.

**Comment by MikePlumleyMSFT** [comment]
@JohanssonMarkus updated poster is now live.

**Comment by JohanssonMarkus** [comment]
@MikePlumleyMSFT  awesome thanks
