### ISSUE TITLE
Typo in text

### ISSUE THREAD

**Issue by chilme** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3613]
Scope directory search in Teams using an Exchange address book policy (APB).

Should be (ABP) not (APB)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84066c98-38a4-e59a-893f-da38a4a11bf3
* Version Independent ID: 890a4978-0e9b-2691-a2ab-8b5512e5e76f
* Content: [Use Microsoft Teams scoped directory search - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-scoped-directory-search#feedback)
* Content Source: [Teams/teams-scoped-directory-search.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-scoped-directory-search.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@chilme Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@chilme Thank you for raising this issue! I'll be looking into it!

**Comment by CarolynRowe** [comment]
This is fixed and will publish soon. Closing this issue.
