### ISSUE TITLE
Powershell

### ISSUE THREAD

**Issue by CallMeByMyName** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3614]
Hello, Where is powershell version of Make an archived team active function ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 5bf689b7-a7c1-121f-578e-029e8a89c4f0
* Version Independent ID: 7e6b449e-bd77-2fc4-2c3d-1f2e364e1b76
* Content: [Archiver ou supprimer une équipe dans Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/fr-fr/microsoftteams/archive-or-delete-a-team)
* Content Source: [Teams/archive-or-delete-a-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/archive-or-delete-a-team.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@CallMeByMyName Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@CallMeByMyName Thank you for raising this issue! I'll be looking into it!

**Comment by TokyoScarab** [comment]
@scanum Can we get the French language team to help on this? Thanks!

**Comment by scanum** [comment]
@officeglobal Hi! Could you please help on this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@scanum The article was HumanTranslated, text follows the source

**Comment by scanum** [comment]
@CallMeByMyName Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
