### ISSUE TITLE
Ability to assign Configuration Profile as default for all new devices

### ISSUE THREAD

**Issue by TiggBloomz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3615]
As per title - would be useful rather than adding each device manually.

**Comment by scanum** [comment]
@TiggBloomz Please link the issue you are referring to. Thanks!

**Comment by TiggBloomz** [comment]
> 
> 
> @TiggBloomz Please link the issue you are referring to. Thanks!

Apologies: https://docs.microsoft.com/en-us/microsoftteams/device-management#use-configuration-profiles-in-teams

**Comment by TokyoScarab** [comment]
@TiggBloomz Thank you for raising this issue! I'll be looking into it!

**Comment by TokyoScarab** [comment]
@TiggBloomz If I am understanding this correctly, you are suggesting a feature / improvement. Is that correct? If that is the case, Microsoft has a platform called UserVoice where your feedback can be seen and taken into consideration to help better Microsoft products and services! Here is the link for the [Microsoft Teams UserVoice](https://microsoftteams.uservoice.com/). If you were suggesting an issue with the documentation, then feel free to comment back to elaborate on that concern, thanks!

**Comment by scanum** [comment]
@TiggBloomz We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
