### ISSUE TITLE
Flow should be updated to Power Automate

### ISSUE THREAD

**Issue by benstegink** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3616]
With the recent name change from Flow -&gt; Power Automate, the services included dont' reflect this recent name change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f897ae9b-852a-b617-7de0-d76dbd9f1820
* Version Independent ID: 161b1845-53fd-8912-a5f9-737d3bcdaadc
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-exploratory#feedback)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@benstegink Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @benstegink, thank you for your feedback.

In the Admin Center, Flow has not changed its name to Power Automate yet. So, the article shouldn't be updated until it's renamed.

**Comment by scanum** [comment]
@benstegink Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
