### ISSUE TITLE
[LOC]"諸島" needs to be replaced with "アイランド"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3618]
https://docs.microsoft.com/ja-jp/microsoftteams/setting-your-coexistence-and-upgrade-settings

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: ffbf0bfd-c15e-b10b-0cc9-6a27ac1e6634
* Version Independent ID: 58575371-9e09-fadb-76f6-7491df8580a3
* Content: [共存およびアップグレードを設定する - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/setting-your-coexistence-and-upgrade-settings)
* Content Source: [Teams/setting-your-coexistence-and-upgrade-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/setting-your-coexistence-and-upgrade-settings.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officeglobal Could you please take a look at this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by scanum** [comment]
@OfficeGlobal Any updates on this? Thanks!

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 the article has been HumanTranslated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal - Corrected.
Closed #3618.
Thanks.
