### ISSUE TITLE
Screenshot as example would be helpful.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#362]
Lack of graphics or screenshot as an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6c67ec-85ad-694e-30f1-64b4652cbb60
* Version Independent ID: 70a451da-4dab-adca-218f-54f3ec185de4
* Content: [Conference Summary Report in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/manage/health-and-monitoring/conference-summary-report)
* Content Source: [Skype/SfbServer/manage/health-and-monitoring/conference-summary-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/health-and-monitoring/conference-summary-report.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi, thanks for your feedback.
Written information is prefered in documents so it favours the indexation of the document.
Thank You.

**Comment by jambirk** [comment]
@AndreaBarr  @yogkumgit  The examples requested are there, they're presented as tables. Let's consider this closed.
