### ISSUE TITLE
[LOC]"諸島" or "孤島" needs to be replaced with "アイランド"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3622]
https://docs.microsoft.com/ja-jp/microsoftteams/coexistence-chat-calls-presence

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 169a20a6-ebf7-1093-3cb1-fb438b9b7e13
* Version Independent ID: b2074fd8-724e-75fa-bafb-a0f7966bf593
* Content: [Skype for Business と共存する - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/coexistence-chat-calls-presence)
* Content Source: [Teams/coexistence-chat-calls-presence.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/coexistence-chat-calls-presence.md)
* Service: **msteams**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@officeglobal Could you please take a look at this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by scanum** [comment]
@OfficeGlobal Any updates on this? Thanks!

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum the article was updated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal - Corrected.
Closed #3622.
Thanks.
