### ISSUE TITLE
[LOC]"諸島" or "孤島" needs to be replaced with "アイランド"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3626]
https://docs.microsoft.com/ja-jp/microsoftteams/migration-interop-guidance-for-teams-with-skype

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 49921e8a-55ac-f547-d4e2-d329f5089c2e
* Version Independent ID: 91c3433a-3684-95cd-3426-4a5877b33106
* Content: [Teams を Skype for Business と一緒に使用する組織向けの移行と相互運用に関するガイダンス - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/migration-interop-guidance-for-teams-with-skype)
* Content Source: [Teams/migration-interop-guidance-for-teams-with-skype.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/migration-interop-guidance-for-teams-with-skype.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officeglobal Could you please take a look at this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by scanum** [comment]
@OfficeGlobal Any updates on this? Thanks!

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum the article was updated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal - Corrected.
Closed #3626.
Thanks.
