### ISSUE TITLE
Need to know about storage planning for long duration.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#363]
No mention of storage planning (i.e. archiving) for long duration - how many KB of data per user per day is required for P-Chat storage and P-Chat compliance storage?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162cb11b-9eba-17f4-a409-e93b5ed4097c
* Version Independent ID: 7e1d0cf3-394e-9587-a84d-5d23f7b0477c
* Content: [Capacity planning for Persistent Chat Server in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/persistent-chat-server/capacity-planning)
* Content Source: [Skype/SfbServer/plan-your-deployment/persistent-chat-server/capacity-planning.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/persistent-chat-server/capacity-planning.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
You can find information on how many users are supported per Persistant Chat Servers pools here https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/persistent-chat-server/persistent-chat-server
thank you
