### ISSUE TITLE
[LOC]"諸島" needs to be replaced with "アイランド"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3630]
https://docs.microsoft.com/ja-jp/microsoftteams/expand-teams-across-your-org/healthcare/hc-delegates

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 699deaf5-878a-b7e5-f118-54ea9277502a
* Version Independent ID: c8ed4f78-ee6c-0b2c-a4f9-ba3fdd873a3d
* Content: [メッセージの委任 - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/expand-teams-across-your-org/healthcare/hc-delegates)
* Content Source: [Teams/expand-teams-across-your-org/healthcare/hc-delegates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/expand-teams-across-your-org/healthcare/hc-delegates.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@officeglobal Could you please take a look at this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by scanum** [comment]
@OfficeGlobal Any updates on this? Thanks!

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum the article was updated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal - Corrected.
Closed  #3630.
Thanks.
