### ISSUE TITLE
[LOC]"孤島" needs to be replaced with "アイランド"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3633]
https://docs.microsoft.com/ja-jp/microsoftteams/expand-teams-across-your-org/shifts/move-staffhub-teams-to-shifts-in-teams

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8f64dee1-c968-9d64-757e-7ca3263a4fc4
* Version Independent ID: a3157a8b-a127-0726-2ee4-8972e773a785
* Content: [StaffHub teams を Microsoft Teams の Shifts に移動する  - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/expand-teams-across-your-org/shifts/move-staffhub-teams-to-shifts-in-teams)
* Content Source: [Teams/expand-teams-across-your-org/shifts/move-staffhub-teams-to-shifts-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/expand-teams-across-your-org/shifts/move-staffhub-teams-to-shifts-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officeglobal Could you please take a look at this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by scanum** [comment]
@OfficeGlobal Any updates on this? Thanks!

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum the article has been updated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal  - Corrected.
Closed #3633.
Thanks.
