### ISSUE TITLE
[LOC]"孤島" needs to be replaced with "アイランド"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3634]
https://docs.microsoft.com/ja-jp/microsoftteams/manage-external-access

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Microsoft Teams での外部アクセス (フェデレーション) の管理 - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/manage-external-access)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officeglobal Could you please take a look at this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by scanum** [comment]
@OfficeGlobal Any updates on this? Thanks!

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum the article has been updated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal - Corrected.
Closed #3634.
Thanks.
