### ISSUE TITLE
[LOC]"島" needs to be replaced with "アイランド" 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3635]
https://docs.microsoft.com/ja-jp/skypeforbusiness/hybrid/cloud-consolidation

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4c621a9c-ce55-e3a6-4220-3f9f1192efee
* Version Independent ID: 5e79fabf-8aa3-96b1-3e94-23904e9fd375
* Content: [Teams と Skype for Business のクラウド統合 - Skype for Business Hybrid](https://docs.microsoft.com/ja-jp/skypeforbusiness/hybrid/cloud-consolidation)
* Content Source: [Skype/SfbHybrid/hybrid/cloud-consolidation.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/cloud-consolidation.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@officeglobal Could you please take a look at this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by scanum** [comment]
@OfficeGlobal Any updates on this? Thanks!

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum the text was updated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal - Corrected.
Closed #3635.
Thanks.
