### ISSUE TITLE
Multi-Geo aware

### ISSUE THREAD

**Issue by tmaheshwar** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3636]
This statement is confusing :"Note that conversations in chats and meeting IM notes within the Teams experience are not Multi-Geo aware and are all kept only inside the central location of the tenant. Typically, chat conversations aren’t applied to data residency needs." 

What exactly we are saying:
Is 1-1 chats are not Multi-Geo aware, what about Channels Chats and Teams Chat
is WiKi (Meeting notes) are not Multi-Geo aware, what about Channels Meeting notes and Teams Meeting Notes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c65240c7-8a9e-cf39-008d-2c8b12534b0d
* Version Independent ID: 9a1e12a6-f020-7782-e749-8e4909fa8d0c
* Content: [Teams experience in an Office 365 OneDrive and SharePoint Online Multi-Geo-enabled tenancy - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-experience-o365odb-spo-multi-geo)
* Content Source: [Teams/teams-experience-o365odb-spo-multi-geo.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-experience-o365odb-spo-multi-geo.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officeglobal Could you please take a look at this issue? Thanks!

**Comment by scanum** [comment]
@tmaheshwar Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@tmaheshwar Thank you for raising this issue! I'll be looking into it!

**Comment by TokyoScarab** [comment]
@tmaheshwar To clarify, that section of the documentation is saying that files shared will be Multi-Geo whereas any Chats or conversations won't be Multi-Geo and instead be localized to their respective tenancy. I hope this clears up any confusion you might have had. If you have more questions about this, feel free to follow up and comment, thanks!

**Comment by scanum** [comment]
@TokyoScarab

**Comment by scanum** [comment]
@TokyoScarab

**Comment by scanum** [comment]
@TokyoScarab Any updates here? Thanks!

**Comment by dariomws** [comment]
Hi @tmaheshwar, thank you for your feedback.

I Updated the article to include OneNote, Wiki and channel messages. To see where your chats, channels messages and meeting IM notes/chats data is located please check this:
https://docs.microsoft.com/microsoftteams/location-of-data-in-teams

**Comment by scanum** [comment]
@tmaheshwar  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
