### ISSUE TITLE
Private channel creation issue in PowerShell

### ISSUE THREAD

**Issue by JimmyHang** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3637]
I'm trying to create a private channel in PowerShell:

New-TeamChannel -GroupId $team.GroupId -DisplayName "100 Internal" -MembershipType Private

****** Error output from PS ****
New-TeamChannel : A parameter cannot be found that matches parameter name 'MembershipType'.
At line:1 char:76
+ ... pId $team.GroupId -DisplayName "100 Internal" -MembershipType Private ...
+                                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-TeamChannel], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.TeamsCmdlets.PowerShell.Custom.NewTeamChannel

********** Teams module 1.0.3 ***

![image](https://user-images.githubusercontent.com/18226765/70868925-dac9ef80-1f85-11ea-88f0-51fff07af412.png)

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
