### ISSUE TITLE
Clarity around Security of Recordings?

### ISSUE THREAD

**Issue by gbollardgit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3638]
We have teams that discuss very secure matters. We need to be able to assure them that their meetings are protected. I think this article could include at least a link to a means of determining (and changing) the access on a given stream resource. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording#feedback)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@gbollardgit Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@gbollardgit Thank you for raising this issue! I'll be looking into it!

**Comment by diegoriera** [comment]
The record doesn't work well with PPT animations, when you look on the recorded video you can't see the PPT transition.

**Comment by scanum** [comment]
@gbollardgit 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you
