### ISSUE TITLE
Need description of configuring announcement.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#364]
Looking for description on configuring announcement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23680488-ddfe-6f27-da45-e46392a014ed
* Version Independent ID: 265c61c6-2e9e-0e61-a716-040cbb51e594
* Content: [Response Groups Group](https://docs.microsoft.com/en-us/skypeforbusiness/help-topics/help-lscp/response-groups-group)
* Content Source: [Skype/SfbServer/help-topics/help-lscp/response-groups-group.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/help-topics/help-lscp/response-groups-group.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi
You can find that information here https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-enterprise-voice/create-an-announcement Thanks
