### ISSUE TITLE
Video contains dated information

### ISSUE THREAD

**Issue by bartvermeersch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3640]
The video on this page contains dated and incorrect information. Guests don't have to belong to another O365 tenant but can also be MSA or Google accounts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042d7ce6-ee22-690f-8188-ff8a4a585847
* Version Independent ID: 3e5bc99c-e08e-44e0-cda3-687ed3633175
* Content: [Turn on or turn off guest access to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/set-up-guests)
* Content Source: [Teams/set-up-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-guests.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@bartvermeersch Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@bartvermeersch Thank you for raising this issue! I'll be looking into it!

**Comment by TokyoScarab** [comment]
@LanaChin The video linked does indeed contain outdated information. The video linked is of a non-Microsoft YouTube channel. What would be the best course of action to take for this, remove the link or update the link? Is there a more up to date version of this from a Microsoft source? Appreciate any guidance on this, thanks!

**Comment by LanaChin** [comment]
Looking into this.

**Comment by LanaChin** [comment]
Thanks @bartvermeersch for your feedback! We'll be updating the video soon.
