### ISSUE TITLE
Please mention that User phone number types cannot be assigned to resource accounts

### ISSUE THREAD

**Issue by jameslear** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3643]
If a phone number previously was used directly by a user, it must be first converted to a service number type before this procedure can be completed.  The phone number will not appear in the assignment page, otherwise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts#feedback)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@jameslear Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @jameslear, thank you for your feedback.

In this article I can read that a "service phone number" is a requieremet no assign a phone number to a Resource Account. User phone number aren't supported.

"Before you assign a phone number to a resource account, you need to get or port your existing toll or toll-free service numbers. After you get the toll or toll-free service phone numbers, they show up in Microsoft Teams admin center > Voice > Phone numbers, and the Number type will be listed as Service - Toll-Free. To get your service numbers, see Getting service phone numbers or if you want to transfer an existing service number, see Transfer phone numbers to Teams."

**Comment by scanum** [comment]
@jameslear 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you
