### ISSUE TITLE
Update DNS info is incorrect for two items

### ISSUE THREAD

**Issue by grtaylo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3647]
This article states that CNAMEs for meet.domain.com and dialin.domain.com should be added, pointing to webdir.online.lync.com.  That is not required and will not work.  These items should instead be deleted entirely, since post-migration, meetings and the dialin URL will be hosted by Microsoft.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ce37c7f-6f13-8442-bfdb-47065a7339b3
* Version Independent ID: 9a2b5082-369d-7c04-4fa8-81c1440ea119
* Content: [Disable hybrid to complete migration to the cloud - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/cloud-consolidation-disabling-hybrid#feedback)
* Content Source: [Skype/SfbHybrid/hybrid/cloud-consolidation-disabling-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/cloud-consolidation-disabling-hybrid.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@grtaylo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@grtaylo thank you for reaching out and helping improve MS Docs. The article was updated this month and there are a few notes added which should provide more clarity. Please let me know if this helps.

**Comment by grtaylo** [comment]
> 
> 
> @grtaylo thank you for reaching out and helping improve MS Docs. The article was updated this month and there are a few notes added which should provide more clarity. Please let me know if this helps.

It looks like the content I described as incorrect is still there.  See here: 
![Wrong Info](https://user-images.githubusercontent.com/48136412/72434963-f1bd5680-376a-11ea-9aba-c7f984cf6985.PNG)

**Comment by lindspea** [comment]
@CarolynRowe please could you assist. Should I remove the two report types in a PR?

**Comment by CarolynRowe** [comment]
No, please do not remove them yet. According to the hybrid PM who I checked with, those two record types are required for hybrid with SfBO, but not Teams.   I am following up with the PM about whether we need to add some explanatory text.

**Comment by grtaylo** [comment]
Interesting.  I haven't seen it used in Skype for Business Online hybrid deployments.  Maybe it's worth adding an explanation of why it's required?

**Comment by lindspea** [comment]
@CarolynRowe any update yet?

**Comment by CarolynRowe** [comment]
Please do not remove until we hear back from the PM.

**Comment by scanum** [comment]
@CarolynRowe Any update on this issue? Thanks!

**Comment by scanum** [comment]
@CarolynRowe Any update on this issue? Thanks!

**Comment by scanum** [comment]
@CarolynRowe Any update on this issue? Thanks!

**Comment by scanum** [comment]
@CarolynRowe Any update on this issue? Thanks!

**Comment by lindspea** [comment]
@CarolynRowe any update yet?

**Comment by lindspea** [comment]
@CarolynRowe
