### ISSUE TITLE
screenshot clipping out of date

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3649]
The screenshot for creating a new resource account is out of date, the GUI current asks you to also specify if this is for a CQ or AA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts#create-a-resource-account-in-microsoft-teams-admin-center)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@TorrenManson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@TorrenManson thank you for pointing this out and helping improve MS Docs.  I'll investigate and have the screenshot fixed soonest.

**Comment by dstrome** [comment]
hi @TorrenManson The topic shows AA/CQ image updates. Please let us know if you still see discrepancies. thanks!
