### ISSUE TITLE
Need archive capacity planning.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#365]
Where is the archive capacity planning?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0cbf9bd-307c-e55d-348d-fca47678378c
* Version Independent ID: 69b7b6f0-41f4-2cd0-d845-b4af51109b45
* Content: [Hardware and software requirements for archiving in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/archiving/hardware-and-software-requirements)
* Content Source: [Skype/SfbServer/plan-your-deployment/archiving/hardware-and-software-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/archiving/hardware-and-software-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by yogkumgit** [comment]
As this is an internal transfer can be closed
