### ISSUE TITLE
Powershell onprem required for hybrid

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3650]
Consider moving the purple box explaining that hybrid requires onprem powershell New-CsHybridApplicationEndpoint out of the powershell section, and up in to the overview section. People are missing it, because they want instructions for the gui, and aren't reading the powershell section. Perhaps there are also some who want to use the GUI, and are reading the powershell section, but aren't understanding that the on-prem New-CsHybridApplicationEndpoint applies to them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts#create-a-resource-account-in-powershell)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by TorrenManson** [comment]
And on re-reading, I see there's one there... but it's not clear from either of these two callouts that you need to use the on-prem powershell command if you're in a hybrid. 

The fact that SfB 2019 is specified is also confusing, as this also applies to Lync 2013 and SfB 2015.

**Comment by scanum** [comment]
@TorrenManson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@TorrenManson Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
