### ISSUE TITLE
Retention policies blocking private channel deletion

### ISSUE THREAD

**Issue by SinghGurd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3651]
Please include the limitation that a Private Channel can't be deleted if corresponding SharePoint site collection is added in a retention policy. 

Essentially, if tenant has a retention policy defined that applies to all SharePoint sites then all private channel site collections automatically get included in retention policy. Hence, none of these private channels can be deleted unless site is manually removed from retention.

Would be good to include this point in documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels#feedback)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@SinghGurd Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@SinghGurd thank you for pointing this out.  I'll look into adding a note to the article soonest pending approval from the team.

**Comment by lindspea** [comment]
@SinghGurd thank you for reaching out and helping improve MS Docs. Please have a look at this article. There are updates coming soon to this section.  Let me know if this helps. https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels#what-you-need-to-know-about-private-channels

**Comment by scanum** [comment]
@SinghGurd 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
