### ISSUE TITLE
Channel names limitation

### ISSUE THREAD

**Issue by chenhua2000** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3653]
The article mentioned the characters in the ranges of 0 to 1F and 80 to 9F are not allowed in channel name. But doesn't give any explanation. It's quite confusing to customers. Can you provide explanation of what're these characters?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#feedback)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@chenhua2000 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by chenhua2000** [comment]
Any updates?

**Comment by lindspea** [comment]
@chenhua2000 thank you for reaching out and helping improve MS Docs. I see there have been some changes and PR's added to this article since you first mentioned it. Please let me know if your issue has been solved in the interim, otherwise I'll investigate further.

**Comment by scanum** [comment]
@chenhua2000 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@chenhua2000 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
