### ISSUE TITLE
Max number of owners per team

### ISSUE THREAD

**Issue by GaelleLeC** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3655]
The current page mentions "There can be as many as 10 team owners per team." 
However here (https://docs.microsoft.com/en-us/MicrosoftTeams/assign-roles-permissions) it says: "A team can have up to 100 owners."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c807f882-de3c-9c30-f92f-43769356f015
* Version Independent ID: 7658a338-51a0-196a-ce53-2a213a5f0dc6
* Content: [Plan for lifecycle management in Teams - Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/plan-teams-lifecycle#feedback)
* Content Source: [Teams/plan-teams-lifecycle.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-teams-lifecycle.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@GaelleLeC Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by taylorbouman** [comment]
https://support.office.com/en-us/article/assign-a-new-owner-to-an-orphaned-group-86bb3db6-8857-45d1-95c8-f6d540e45732    This one says 100 Owners

**Comment by lindspea** [comment]
@LanaChin

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@GaelleLeC Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
