### ISSUE TITLE
Office hours -15 or 30 minute intervals?

### ISSUE THREAD

**Issue by bartvermeersch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3657]
According to this page business hours can be defined using a 15 minute interval, but we currently see 30 minute interval in the admin center?

 "To customize start or end time for a day of the week, click on Start at or End at time you wish to reset and select the new time from the list that appears. The list allows you to select business hours in 15-minute intervals, and the business hours you select here are based on the time zone that you set on the General info page."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a42f9e2c-aeee-76c4-620a-668cce21ba10
* Version Independent ID: 6ff06eab-9c80-9c30-95ef-c17e157fbea1
* Content: [Set up a Cloud auto attendant - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-auto-attendant)
* Content Source: [Teams/create-a-phone-system-auto-attendant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-auto-attendant.md)
* Service: **msteams**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by sischanz** [comment]
The 30 minute intervall seems to be the correct one, based on our documentation for the corresponding powershell cmdlet:
A time range must be aligned with 30/60-minutes boundaries.
https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlinetimerange?view=skype-ps

**Comment by scanum** [comment]
@bartvermeersch Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @bartvermeersch, thank you for your feedback.

I have verified this on my tenant and it seems that 15 minutes is ok:
![image](https://user-images.githubusercontent.com/33589238/75991408-33e65700-5ed5-11ea-9654-0285a571baaf.png)

**Comment by bartvermeersch** [comment]
Cool, they changed the app to align with the documentation (in my tenant as well)!
