### ISSUE TITLE
How to export a list of active users.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#366]
Need to know how I can export a list of active users. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac567b2-9614-05a3-e90c-bcab8e8eff29
* Version Independent ID: 1d46e019-1214-4868-a876-236f4ecd505d
* Content: [Control Panel - updated User Search](https://docs.microsoft.com/en-us/skypeforbusiness/help-topics/help-lscp/control-panelupdated-user-search)
* Content Source: [Skype/SfbServer/help-topics/help-lscp/control-panelupdated-user-search.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/help-topics/help-lscp/control-panelupdated-user-search.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi!
That is not possible to do with SfB Control Panel. But you can search for the list of enabled users with the find filter.
Thank you
