### ISSUE TITLE
Who can be an agent

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3663]
I'm a MSFT partner, and have had a number of customers ask if CAPs or Meeting Rooms can be agents in a queue. It would be helpful to explicitly state that only user accounts can be agents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b755d9ae-13ac-019f-f5f4-a95b1eee2989
* Version Independent ID: f7afd8ad-e6e0-6c79-aed1-4ee87d48ba12
* Content: [Create a call queue - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue)
* Content Source: [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-call-queue.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@TorrenManson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@TorrenManson thank you for pointing this out and helping improve MS Docs. I'll have a note added to the article soonest.

**Comment by Coldry** [comment]
Not sure if this is the right place to ask this, but I would like to know if there's a way to see who of the listed agents are currently opted in and who's not to a particular call queue.

**Comment by lindspea** [comment]
@TorrenManson I think this was possibly added to the article in the interim which will provide more clarity on agents:
Call agents selected must be one of the following:
Online users with a Phone System license and Enterprise Voice enabled
Online users with a Calling Plan
On-premises Skype for Business Server users
Hope this helps.

**Comment by scanum** [comment]
@TorrenManson 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
