### ISSUE TITLE
Add script to find users who need meetings migrated

### ISSUE THREAD

**Issue by StainlessSteele** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3665]
For a tenant who's moved to TeamsOnly or SFBWithCollabandMeetings globally, not per-user, we should suggest to customers how to find all the folks who yet need meetings migrated. Or, we can suggest simply running a command on the entire tenant except for users who are manually in TeamsOnly or SFBwithCollabandMeetings, for only SFB meetings to be updated. https://docs.microsoft.com/en-us/SkypeForBusiness/audio-conferencing-in-office-365/setting-up-the-meeting-migration-service-mms is the doc in question. 
Suggestions are:
Validate tenant is in TeamsOnly or SFBWithColalbandMeetings via Get-CsTenant|ft TeamsUpgradeEffectiveMode; If Mode returns UpgradeToTeams or SfBWithTeamsCollabAndMeetings or SfBWithTeamsCollabAndMeetingsWithNotify, then, you could run variations of : 
This command will list out all users who are NOT manually in a mode where we wouldn't want to upgrade their meetings:
get-csonlineuser -filter {(TeamsUpgradePolicy -ne "Tag:UpgradeToTeams")-and (TeamsUpgradePolicy -ne "Tag:SfBWithTeamsCollabAndMeetings") -and (TeamsUpgradePolicy -ne "Tag:SfBWithTeamsCollabAndMeetingsWithNotify") -and (TeamsUpgradePolicy -ne "Tag:Islands")-and (TeamsUpgradePolicy -ne "Tag:SfBOnly")  } |ft UserPrincipalName, TeamsUpgradePolicy, TeamsUpgradeEffectiveMode
If the tenant is a mode of UpgradeToTeams, or one of the Meetings modes, then you can pipe the results of that command : 
get-csonlineuser -filter {(TeamsUpgradePolicy -ne "Tag:UpgradeToTeams")-and (TeamsUpgradePolicy -ne "Tag:SfBWithTeamsCollabAndMeetings") -and (TeamsUpgradePolicy -ne "Tag:SfBWithTeamsCollabAndMeetingsWithNotify") -and (TeamsUpgradePolicy -ne "Tag:Islands")-and (TeamsUpgradePolicy -ne "Tag:SfBOnly")  } 
Into the Start-CsExMeetingMigration for SourceMeetingType SFB and TargetMeetingType Teams as exampled here:
get-csonlineuser -filter {(TeamsUpgradePolicy -ne "Tag:UpgradeToTeams")-and (TeamsUpgradePolicy -ne "Tag:SfBWithTeamsCollabAndMeetings") -and (TeamsUpgradePolicy -ne "Tag:SfBWithTeamsCollabAndMeetingsWithNotify") -and (TeamsUpgradePolicy -ne "Tag:Islands")-and (TeamsUpgradePolicy -ne "Tag:SfBOnly")  } | Start-CsExMeetingMigration -SourceMeetingType SFB -TargetMeetingType Teams

**Comment by scanum** [comment]
@StainlessSteele Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by StainlessSteele** [comment]
Chatted with a colleague, and he suggested something as well :
Get-CsOnlineUser -Filter {TeamsUpgradePolicy -eq $null} | where TeamsUpgradeEffectiveMode -in "TeamsOnly","SfBWithTeamsCollabAndMeetings" | Start-CsExMeetingMigration -SourceMeetingType SfB -TargetMeetingType Teams. 
This will do the following:
Find all users who don't have a manual upgrade policy assigned. And, after they are returned, use the effective mode they re in, and if in TeamsOnly or SFBWithTeamsCollabandMeetings, will start the migration. If the tenant isn't in UpgradeToTeams, or in SFBwithTeamsCollabAndMeetings, the meeting migration won't run for anyone.

**Comment by lindspea** [comment]
@StainlessSteele thank you for reaching out. I'm looking into this with the team and will revert soonest.

**Comment by lindspea** [comment]
@StainlessSteele thank you once again for this. The team is currently doing a rewrite of these topics, so it should be updated in the near future, but unfortunately I cannot give you a timeframe for completion at the moment.

**Comment by scanum** [comment]
@StainlessSteele 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
