### ISSUE TITLE
Übersetzungsfehler

### ISSUE THREAD

**Issue by Nyffe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3666]
"Wichtig: Archivierte Teams können wieder aktiviert werden, aber Sie können ein gelöschtes Team nicht direkt löschen." -&gt; anstatt direkt löschen sollte "wiederherstellen" verwendet werden 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 5bf689b7-a7c1-121f-578e-029e8a89c4f0
* Version Independent ID: 7e6b449e-bd77-2fc4-2c3d-1f2e364e1b76
* Content: [Archivieren oder Löschen eines Teams in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/archive-or-delete-a-team#feedback)
* Content Source: [Teams/archive-or-delete-a-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/archive-or-delete-a-team.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Nyffe Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Nyffe 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
