### ISSUE TITLE
Add more features that are not supported on VDI

### ISSUE THREAD

**Issue by aalejandroaraujo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3667]
We have identified also these features not being currently available, so they should be added into the list.
These calling and meeting features are not currently supported:
- Enhanced emergency services
- HID buttons and LED controls between the Teams app and devices
- Background blur and effects
- Broadcast/live events
- Location-Based Routing (LBR)
- Call park
- Call queue

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi?source=docs#feedback)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@aalejandroaraujo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@LanaChin @dariomws Hi Lana, Dario is working on this issue. He might need some help. Dario could you please elaborate on what you need? thanks!

**Comment by aalejandroaraujo** [comment]
Happy to assist in Teams if you wish. My corporate account is aaraujo@microsoft.com

Cheers,

Alejandro.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by LanaChin** [comment]
@aalejandroaraujo, I've reached out to you in a chat with the PM in Teams. :-)

**Comment by dariomws** [comment]
Hi @LanaChin and @aalejandroaraujo, sorry but I think I don't understand. This list was added by Lana 5 months ago in the article.

How I can help you?

**Comment by LanaChin** [comment]
Thanks for the follow up, @dariomws. We sorted it out in a Teams chat with the PM and I've added an item to the Known issues and limitations list in the article.
