### ISSUE TITLE
Attendee Experience options switched?

### ISSUE THREAD

**Issue by DavidMtbg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3669]
Under Attendee Experience (https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/what-are-teams-live-events#attendee-experience), it reads "The attendee experience uses Azure Media Player (for events produced in Teams) and Stream Player (for events produced in an external app or device)", but I believe this should be "The attendee experience uses Azure Media Player (for events produced in an external app or device) and Stream Player (for events produced in Teams)".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: becbf3ca-b88c-b033-a145-9a1af201ced3
* Version Independent ID: 41a6a9b5-d3dd-d8c9-9e97-920ff2fd1a24
* Content: [What are Microsoft Teams live events? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/what-are-teams-live-events#feedback)
* Content Source: [Teams/teams-live-events/what-are-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/what-are-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@DavidMtbg Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@DavidMtbg 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
