### ISSUE TITLE
Looking for desktop sharing bandwidth requirements.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#367]
Looking for desktop sharing bandwidth requirements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7786c895-2dc2-d1c1-2117-39b757b3a754
* Version Independent ID: 82716965-3a36-6d94-d237-c7d4269ab033
* Content: [Plan network requirements for Skype for Business 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/network-requirements/network-requirements)
* Content Source: [Skype/SfbServer/plan-your-deployment/network-requirements/network-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/network-requirements/network-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Desktop Sharing is referenced in the article as Application Sharing.
Hope this information helps you.
Thanks

**Comment by jambirk** [comment]
@AndreaBarr  @yogkumgit Let's consider this closed.
