### ISSUE TITLE
Typo on page: on premise

### ISSUE THREAD

**Issue by JetzeMellema** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3672]
"on premise MDM"

Should be:

"on-premises MDM"

For reference, see https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/cloud-computing-terms

**Comment by scanum** [comment]
@JetzeMellema Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @JetzeMellema, thank you for your feedback.

Could you please kindly let me know in what article do you see this typo?

**Comment by scanum** [comment]
@JetzeMellema 
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
