### ISSUE TITLE
Member updates with Guests

### ISSUE THREAD

**Issue by RayPering** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3673]
Does the dynamic membership work with Guest users? My group updates with the B2B guests but the Team doesn't seem to add the new guests.

**Comment by scanum** [comment]
@RayPering Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
