### ISSUE TITLE
B2B Users Created via AADC not receiving invite email

### ISSUE THREAD

**Issue by franciso** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3674]
We create our guest users via AADC (as explained here: https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-sync-change-the-configuration#enable-synchronization-of-usertype) to allow our partners access to both on-premises and cloud applications. All of them are Guest Mail Users in Exchange Online and have valid (external) email addresses and can access resources as "typical" B2B users can do. When we invite a guest user (created via AADC) to a Team they do not receive an invite email (as the guest experience in this documents explains) as the "typical" B2B does. Is this the expected behaviour or a known limitation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [What the guest experience is like - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/guest-experience?source=docs#feedback)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@franciso Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
