### ISSUE TITLE
Teams 1.2.00.34161 installer not recognizing Horizon View installation

### ISSUE THREAD

**Issue by jl242** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3675]
Getting "Cannot install for all users when a VDI environment is not detected" message even though Horizon Agent is installed and running.

Using Process Monitor, it looks like Teams.exe is trying to look for: 
HKLM\SOFTWARE\VMware, Inc.\VMware VDM\Agent\AgentInstallPath

However AgentInstallPath is located in:
HKLM\SOFTWARE\VMware, Inc.\VMware VDM\AgentInstallPath

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi#feedback)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@jl242 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
