### ISSUE TITLE
New video replaces the one on this page

### ISSUE THREAD

**Issue by bybytaren** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3679]
I believe the new video at https://www.youtube.com/watch?v=WkAVgNKn0hs replaces the top one on this page and I would appreciate if this page is updated because I am referring my powerusers to visit here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06059d07-6687-2924-7d0a-3c03220a1650
* Version Independent ID: bb293f92-9394-b156-2e08-0baead5c3bbe
* Content: [Overview of teams and channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-channels-overview)
* Content Source: [Teams/teams-channels-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-channels-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@bybytaren Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@bybytaren Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
