### ISSUE TITLE
Team to Group

### ISSUE THREAD

**Issue by mymebenha** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3680]
It's easy to create a Team from an existing group but if we have a Team and we want to Group enable it, where is the powershell command as mentioned above?

**Comment by scanum** [comment]
@mymebenha Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
