### ISSUE TITLE
What about assigning meeting policies to a group?

### ISSUE THREAD

**Issue by NelsonR3** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3681]
Hi! I saw that it's possible to assign teams policies to Office 365 groups, but not the same with meeting policies. 
For example, my customer wants to turn off IP Video and Cloud Recording for a certain group of users (an Office 365 Group would be the most reasonable choice).
It takes a big load of work to assign the "AllOff" meeting policy to 35 users which are in a 365 Group selecting one by one through the "manage users" option.
Will this group policy mode will be available in the Teams admin center, is it possible only via Powershell or is not possible? 
Regards.

**Comment by scanum** [comment]
@NelsonR3 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
