### ISSUE TITLE
Out of Date, need update for Teams Users

### ISSUE THREAD

**Issue by CharlesYeomans** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3687]
Very confusing.
Just want to subscribe to a calling plan to make calls out from Teams (Domestic and International).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b07cfcf-8f31-91ed-b1de-c7826a1ab91d
* Version Independent ID: dfbc4212-8f47-326a-f872-8186a915ae1e
* Content: [Country and region availability for Audio Conferencing and Calling Plans - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans#feedback)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@CharlesYeomans Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @CharlesYeomans, thank you for your feedback.

Maybe what you are looking for is:
https://docs.microsoft.com/MicrosoftTeams/configuring-teams-calling-quickstartguide
https://docs.microsoft.com/MicrosoftTeams/calling-plans-for-office-365
https://docs.microsoft.com/MicrosoftTeams/set-up-calling-plans

**Comment by scanum** [comment]
@CharlesYeomans Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
