### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by imailink** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3688]
[Enter feedback here]

when I click the link in this page, "Details can be found in the Compliance Framework for Industry Standards and Regulations. ", it leads to "404 - File or directory not found."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca579d63-182b-d6f5-8777-79248fa27ed9
* Version Independent ID: b4c27d1b-b2f1-41ac-b15c-d12b448a539e
* Content: [Overview of security and compliance in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/security-compliance-overview)
* Content Source: [Teams/security-compliance-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/security-compliance-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@imailink Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @imailink, thank you for your feedback.

It's duplicated:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3677

**Comment by scanum** [comment]
@imailink Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by pagejustin** [comment]
This link is still broken.
