### ISSUE TITLE
Finding report that monitors user inactivity time.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#369]
Trying to locate a report that monitors user inactivity time while SfB is running. A link to that page will also help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2209aab2-38e0-a948-52fc-d5da3cca0dfa
* Version Independent ID: 2fe17cfb-9e86-846e-2832-cb8c72312f33
* Content: [Using Monitoring Reports in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/manage/health-and-monitoring/monitoring-reports)
* Content Source: [Skype/SfbServer/manage/health-and-monitoring/monitoring-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/health-and-monitoring/monitoring-reports.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
SfB doesn't include such report, the closest report could be this one. https://docs.microsoft.com/en-us/skypeforbusiness/manage/health-and-monitoring/user-activity-report
Hope this information helps you.

Thanks!

**Comment by jambirk** [comment]
@AndreaBarr  @yogkumgit Let's consider this closed.
