### ISSUE TITLE
SQL Server 2019 Cluster is supported or Not?

### ISSUE THREAD

**Issue by darwincr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3690]
In the below documentation it says it is supported:
https://docs.microsoft.com/en-us/SkypeForBusiness/plan/system-requirements#DBs

In the below documentation it says it isn't
https://docs.microsoft.com/en-us/SkypeForBusiness/plan-your-deployment/high-availability-and-disaster-recovery/back-end-server

**Comment by scanum** [comment]
@darwincr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LanaChin** [comment]
@darwincr, thanks for your feedback. @dariomws306, thanks for updating the article. I've merged your updates.
