### ISSUE TITLE
please add a note to "Actions supported:" table

### ISSUE THREAD

**Issue by ikukoyoneda** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3695]
From Teams client, you can access contacts in Outlook contact folder. But this functionality is limited to top-level contact folder. (If you create a contact in a subfolder of Outlook contact folder, you cannot access to the contact from Teams client.)

Outlook
  |--Top-level contact folder   <- you can access contacts in this folder
    |--sub folder   <- you cannot access contacts in this folder from Teams

Can you add this limitation to the "Actions supported:" table?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/exchange-teams-interact?source=docs#feedback)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@ikukoyoneda  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@ikukoyoneda Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
