### ISSUE TITLE
Will SMS Sign-In be a workaround for users in org with standalone subscriptions?

### ISSUE THREAD

**Issue by DavidMtbg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3697]
This document mentions that "Users in your organization who have standalone Office 365 subscription plans only, such as Exchange Online Plan 2, cannot be invited as guests to your organization because Teams considers these users to belong to the same organization. For these users to use Teams, they must be assigned an Office 365 Business Premium, Office 365 Enterprise, or Office 365 Education subscription."

For those users, will the coming SMS Sign-In feature be a workaround for them to access Teams without requiring an upgrade in their Office 365 license?

Announcement of the SMS Sign-In feature for reference:
https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/What-s-New-in-Microsoft-Teams-Microsoft-Ignite-2019/ba-p/937025

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2492e210-08f9-a476-97ec-008926def961
* Version Independent ID: adcb0dd9-4a3c-b665-6e34-ce3276c89b4d
* Content: [Guest access in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/guest-access#licensing-for-guest-access)
* Content Source: [Teams/guest-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@DavidMtbg  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @DavidMtbg, thank you for your feedback.

It will be in public preview next year, so I can't provide this information, but I think you'll still need the license.

**Comment by scanum** [comment]
@DavidMtbg Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
