### ISSUE TITLE
How up2date are these issues?

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3698]
Hello,

are all of these known issues, even those from 2017, still valid? Please review this list and remove outdated information.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues#feedback)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@GiantCrocodile  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @GiantCrocodile, thank you for your feedback.

@LolaJacobsen Please could you confirm if you are agree to update this article? Or if you know that there is some update in process? I can do it but want to confirm with you first.

**Comment by scanum** [comment]
@LolaJacobsen Please could you confirm if you are agree to update this article? Or if you know that there is some update in process? I can do it but want to confirm with you first.

**Comment by kkazala** [comment]
Regarding https://docs.microsoft.com/en-us/microsoftteams/known-issues#apps: "Assignments" can be hidden in EDU using Teams admin, Teams apps > Permission Policies > Org-wide app settings > Blocked apps

**Comment by GiantCrocodile** [comment]
Microsoft support confirmed in service request #‎18296425‎ that they have no clue about a specific Microsoft Teams issue listed on the known issue page I talk about: They are not able to provide information if it's actively being worked on, what the current status is nor what a possible ETA for a fix could be. Seems like the page is quite useless because it's not linked to the proper internal bug tracker entries.

@dariomws306 @scanum @LolaJacobsen

**Comment by LolaJacobsen** [comment]
@marclauinger please respond.

**Comment by marclauinger** [comment]
This article is reviewed periodically and issues added/removed as needed.  Another thorough review is underway.
