### ISSUE TITLE
Não estou em nenhum dos 3 perfis

### ISSUE THREAD

**Issue by emerzuc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3699]
Não uso Skype e nem PSTN, o que acho que seria um caminho natural de adoção - do zero. Não há caminho sugerido neste caso?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: b131c7fd-ec71-6b6f-4443-ddaf5cb44bf6
* Version Independent ID: 0c1fb61b-a6cc-e856-d969-54bc13ec699c
* Content: [Como implementar o Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/pt-br/MicrosoftTeams/how-to-roll-out-teams#recommended-path-to-teams)
* Content Source: [Teams/How-to-roll-out-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/How-to-roll-out-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
