### ISSUE TITLE
menu option instructions need updating

### ISSUE THREAD

**Issue by dgordonb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3703]
My test tenant shows Devices and then phones.  
All Devices and Configuration profiles are tabs in the main window.

Using the Microsoft Teams admin center
In the left navigation, go to Devices &gt; Manage Devices.
Select All devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5d65acb-f012-b05d-c871-69b8f187e537
* Version Independent ID: 06710d00-f076-11c4-3f69-cfd979c5554a
* Content: [Manage devices - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/business-voice/manage-devices)
* Content Source: [Teams/business-voice/manage-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/business-voice/manage-devices.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@dgordonb Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@dgordonb Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
