### ISSUE TITLE
One more limitation to add

### ISSUE THREAD

**Issue by shurick81** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3704]
Hi, I guess what might be worth adding on this page is mentioning that it is impossible to make a guest account an owner of a team. For example, as an employee, I use my native account in Teams and I can create new team and I can make some my colleagues co-owners of this team. But when I invite external people, I cannot make them owners of the same team, so I cannot delegate them such functions as managing team members, creating new tabs, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [What the guest experience is like - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-experience#feedback)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@shurick81 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LanaChin** [comment]
Thank you @shurick81  and @dariomws306 - I've merged the changes.
