### ISSUE TITLE
one tenant, multiple SBC configs

### ISSUE THREAD

**Issue by JGezels** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3705]
Is it possible to connect multiple SBC's hosted by different third party vendors and have groups of users being routed through specific SBC's ? In essence: configure multiple SBC (different third parties) for single Tenant and manage usage per user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure a Session Border Controller for multiple tenants - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-sbc-multiple-tenants)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@JGezels Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @JGezels, thank you for your comments.

Yes, it's possible. You should add all these gateways and configure Voice Routing Policies, PSTN Usages and Voice Routes in some way to achieve this.
Docs.microsoft.com feedback is available to improve documentation. To get more help about this configuration, please try with:
https://techcommunity.microsoft.com/

**Comment by scanum** [comment]
@JGezels Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
