### ISSUE TITLE
How does a user access or change his/her PIN?

### ISSUE THREAD

**Issue by bilginbaldji** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3706]
The section needs updating with the relevant ways for a user to reset PIN. The following articles have some information, I believe there are more ways, e.g. when creating a Skype for Business/Teams meeting in Outlook, there is a link "Forgot your dial-in PIN?" in the Audio Conference section of the meeting.

https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/reset-the-audio-conferencing-pin#have-a-user-reset-his-or-her-own-pin
https://docs.microsoft.com/en-us/microsoftteams/reset-the-audio-conferencing-pin-in-teams#have-a-user-reset-his-or-her-own-pin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad892c60-f7e4-0790-66f7-219d28f44ee6
* Version Independent ID: 36e86cca-c5a3-eb4d-477e-1fb7b0b5d7f1
* Content: [Audio Conferencing common questions - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-common-questions#feedback)
* Content Source: [Teams/audio-conferencing-common-questions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-common-questions.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@bilginbaldji Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@bilginbaldji 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you
