### ISSUE TITLE
Microsoft Surface Pro Support

### ISSUE THREAD

**Issue by kennybilko** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3709]
Any update on Microsoft Surface Pro Support? This page says it would be added in calendar year 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b06af4b9-8034-c287-b30c-ca009b8549c1
* Version Independent ID: bf2e1bd9-9b86-68a9-42dd-89001bedf0cd
* Content: [Manage a Microsoft Teams Rooms console settings remotely with an XML configuration file - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/room-systems/content-camera#feedback)
* Content Source: [Teams/room-systems/content-camera.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/content-camera.md)
* Service: **msteams**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by ndambrosio** [comment]
@kennybilko This will work with Surface Pro as of [MTR version 4.3.23.0 (released 12/13/2019)](https://docs.microsoft.com/en-us/microsoftteams/room-systems/srs2-release-note#microsoft-teams-rooms-feature-introduction-and-issue-resolution)
Features introduced in this update:

- Auto-answer proximity based calls and admin setting to control this
- Device Admin Settings UI refresh with addition of device configuration under About tab
- Room control back to main screen
- Meeting Room SKU available in GCC
**- Content camera support for Surface Pro-based system (Minimum required app build: 4.2.4.0)**

**Comment by scanum** [comment]
@kennybilko Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@kennybilko Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
