### ISSUE TITLE
Traduction en français / translate in french -> number format

### ISSUE THREAD

**Issue by prbond** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3711]
Vidéo	50,020 – 50039
Partage d’écran ou d’application	50,040 – 50059

Traduction en français 

Vidéo	50020 – 50039
Partage d’écran ou d’application	50040 – 50059

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Gérer les paramètres de réunion - Microsoft Teams](https://docs.microsoft.com/fr-fr/microsoftteams/meeting-settings-in-teams#feedback)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@prbond Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@officeglobal Hi! Could you please aid with this issue? Thanks

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@prbond , @scanum the article has been HumanTranslated and published live

**Comment by scanum** [comment]
@prbond Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
