### ISSUE TITLE
Document support (or lack of) for On-pemise Trusted Apps with SIP IDs in Hybrid Mode

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3716]
Documentation is lacking for support or lack of support for communication between Teams-only users and Skype Trusted Apps on-premise in the hybrid mode.

(We find that while SfB Online users are able to interact/chat with an on-premise Trusted Application using the trusted apps SIP address, Teams users are unable to search for the on-premise Trusted App SIP ID either by name, or by SIP ID (both internal and external search fails).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40129d20-5ce3-8f23-90a3-490e4d3498bb
* Version Independent ID: 6104ec9f-c48a-f6a2-6d78-af6f58fe493e
* Content: [Move users from on premises to Skype for Business Online - Skype for Business Hybrid](https://docs.microsoft.com/en-us/SkypeForBusiness/hybrid/move-users-from-on-premises-to-skype-for-business-online)
* Content Source: [Skype/SfbHybrid/hybrid/move-users-from-on-premises-to-skype-for-business-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/move-users-from-on-premises-to-skype-for-business-online.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@GauravES  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@GuarevES thank you for reaching out. This documentation is in the process of being updated and might be reflecting correctly now.  Here is another link that could possibly help clarify - https://docs.microsoft.com/SkypeForBusiness/hybrid/configure-hybrid-connectivity.

**Comment by scanum** [comment]
@GauravES Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by GauravES** [comment]
How do I reopen this issue?   I cant see anywhere in the docs that this issue has been addressed.
