### ISSUE TITLE
get-csonlinesipdomain affected by -ErrorAction parameter

### ISSUE THREAD

**Issue by donlassini** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3719]
I establish a connection to my Skype Online configuration by running New-CsOnlineSession and Import-PsSession.
When running the Get-CsOnlineSipDomain command, the status of the $? variable is affected if I use the -ErrorAction parameter. See the example below.

The $? variable should always be $False if there was an error, no matter if it was hidden or not.
Using the $ErrorActionPreference variable to set the desired action works correctly - EXCEPT if also specifying the -ErrorAction parameter.

PS C:\> $ErrorActionPreference
Continue
PS C:\> Get-CsOnlineSipDomain -domain "x.y.z"
The domain x.y.z is not in the tenant's verified domains list. Verify the domain has been added to the tenant in the Office 365 admin center.
    + CategoryInfo          : NotSpecified: (:) [Get-CsOnlineSipDomain], ArgumentException
    + FullyQualifiedErrorId : The domain x.y.z is not in the tenant's verified domains list. Verify the domain has been added to the tenant in the Office 365 admin center.,Microsoft.Rtc.Management.Hosted.Provision.OSD.GetCsOnlineSip
  DomainCmdlet
    + PSComputerName        : admin2e.online.lync.com

PS C:\> $?
False
PS C:\> Get-CsOnlineSipDomain -domain "x.y.z" -ErrorAction SilentlyContinue
PS C:\> $?
True
PS C:\> $ErrorActionPreference = "SilentlyContinue"
PS C:\> Get-CsOnlineSipDomain -domain "x.y.z"
PS C:\> $?
False
PS C:\> Get-CsOnlineSipDomain -domain "x.y.z" -ErrorAction SilentlyContinue
PS C:\> $?
True
PS C:\>

**Comment by scanum** [comment]
@donlassini thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
