### ISSUE TITLE
Need clarification understanding.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#372]
This article is not clear if I am installing the Lync tools or the Skype tools.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a279530-e333-d1ad-4626-4a4872560594
* Version Independent ID: 9c015bec-b047-986c-d986-ea5fd12b543e
* Content: [Skype for Business Server 2015 Resource Kit Tools Documentation](https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/resource-kit-tools)
* Content Source: [Skype/SfbServer/management-tools/resource-kit-tools.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/management-tools/resource-kit-tools.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi
This article is under "Skype For Business 2015" section and also the title states "Skype for Business Server 2015 Resource Kit Tools"
Thank you

**Comment by jambirk** [comment]
@AndreaBarr  @yogkumgit It looks like whatever ambiguity was there was fixed. Let's consider this closed.
