### ISSUE TITLE
GoDaddy Hosted Office 365 Business Premium Subscription - Admin Access Limits

### ISSUE THREAD

**Issue by BeachDayCorp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3721]
I am attempting to enable Guest access to TEAMS and related resources using this guide: 

[https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist](url)

I'm unable to carry out steps 3-5 because GoDaddy says Microsoft doesn't allow them access to these options. 

Any suggestions?

**Comment by scanum** [comment]
@BeachDayCorp thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
