### ISSUE TITLE
Presence States

### ISSUE THREAD

**Issue by DraakUSA** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3722]
It would be nice as to have definitions for the Presence States.  In particular, some of our team members are showing up as 'In a call' and others as 'In a meeting'.  How do these work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a162ef5c-3099-7f58-4178-d29e3ec2b5a7
* Version Independent ID: 6ca31e56-052d-6c62-1323-b5aaaae1f04a
* Content: [User presence in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/presence-admins)
* Content Source: [Teams/presence-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/presence-admins.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@DraakUSA  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@DraakUSA Hi, thank you for reaching out and helping improve MS Docs. I have changed the wording to sound a bit better from 'In a call' to 'On a call'. You can also change your presence accordingly on the top right hand side by clicking on your profile picture and choosing from the options.

**Comment by scanum** [comment]
@DraakUSA Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
