### ISSUE TITLE
Find person who signed up for existing Teams free subscription

### ISSUE THREAD

**Issue by PabReg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3723]
We are planing to upgrade to full version of Microsoft teams. And it is written in documentation that you can do that if you are the person who signed up for existing Teams free subscription but we don't know which person started this trial so how can I find out?

**Comment by scanum** [comment]
@PabReg thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
