### ISSUE TITLE
License allocation example

### ISSUE THREAD

**Issue by darrmitchell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3725]
Contoso, Inc. purchased 600 licenses that included Phone System (one for each employee). Contoso is allotted an initial 25 plus 60 Phone System–Virtual User licenses, 85 in total. Their organization has 90 call queues and auto attendants that have phone numbers. **They need to assign all the Phone System–Virtual User licenses and obtain five regular-priced Phone System licenses.**

Is this actually true or is this scenario dated from before Phone System-Virtual User licenses were actually available? It seems they'd be able to just increase their count of Phone System-Virtual User licenses by 5 via the free add-on, no?

**Comment by scanum** [comment]
@darrmitchell Could you please link the documentation you are referring to? Thanks.

**Comment by Reeced40** [comment]
@darrmitchell Hi Darr, thank you for reaching out to improve MS Docs. Could you please add the link, so that I can investigate. Thanks.

**Comment by scanum** [comment]
@darrmitchell We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
