### ISSUE TITLE
API

### ISSUE THREAD

**Issue by sglogovic** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3726]
Hi,

Is there any way to get this data through an API, Graph API doesn't have these reports and Teams PS is not very broad.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ade1a4-092c-1132-44df-ee2c683fdd33
* Version Independent ID: 396b1aee-2f40-9895-9b00-07e38d11d31b
* Content: [Microsoft Teams analytics and reporting - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-reporting-reference#feedback)
* Content Source: [Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@sglogovic  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@sglogovic Thank you for reaching out. Please have a look at these links to see if they help at all. https://docs.microsoft.com/graph/reportroot-concept-overview & https://docs.microsoft.com/microsoftteams/teams-activity-reports

**Comment by kevmaitland** [comment]
The Graph API reports contain different data from the reports run via the web console (both fields returned and data included), and this is not helpful.

E.g. the Graph API returns 335 records (but no users added within the past 7 days) with these fields: Report Refresh Date, User Principal Name, Last Activity Date, Is Deleted, Deleted Date, Assigned Products, Team Chat Message Count, Private Chat Message Count, Call Count, Meeting Count, Has Other Action, Report Period.

The Teams management console report returns 290 records (but weirdly includes users added in the past 7 days, even though the record count is lower) with these fields: Id, DisplayName, LastActivity (UTC Time), ChannelMessages, ChatMessages, 1:1 Calls

**Comment by Reeced40** [comment]
@LanaChin could you perhaps assist please.

**Comment by Reeced40** [comment]
@LanaChin

**Comment by LanaChin** [comment]
Looking into this, thanks.

**Comment by scanum** [comment]
@LanaChin Any update on this issue? Thanks

**Comment by LanaChin** [comment]
Thanks for your input @sglogovic and @kevmaitland. Your feedback and comments have been forwarded to the product team. Currently, https://docs.microsoft.com/en-us/graph/api/resources/microsoft-teams-user-activity-reports?view=graph-rest-1.0 is available for user activity reports. There's a known limitation between the data from it and the admin center reports.
