### ISSUE TITLE
Clarify more detail about the SBC domain name conventions

### ISSUE THREAD

**Issue by tangx007** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3729]
In the SBC domain name session, suggest to clarify more detail of the SBC domain name's convention, since Underscore [ _ ] and other special characters are not allowed in either the local SBC domain name because it is not valid for SIP URI and TCP/IP host naming.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d964547-6b38-cc5f-6b2b-7a50a1c7dae9
* Version Independent ID: fa5850f9-1b92-9727-c344-bcffc227cbd6
* Content: [Phone System Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-landing-page)
* Content Source: [Teams/direct-routing-landing-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-landing-page.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@tangx007  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@tangx007 Thanks for reaching out. I will investigate further with the team.

**Comment by scanum** [comment]
@CarolynRowe Hi Carolyn, wondering if there are any updates on this.

**Comment by CarolynRowe** [comment]
This issue is referring to the Direct Routing landing page?  For information on SBC domain names, see https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-plan#sbc-domain-names
