### ISSUE TITLE
Need help understanding.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#373]
It is not clear to me. Should this be done on one server from one pool or on one front-end from each pool from the environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bdac066-c436-4abb-c828-1d4850a53307
* Version Independent ID: 92628bcb-a500-c9c0-51d2-99296b3856a4
* Content: [Install Monitoring Reports in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-monitoring/install-monitoring-reports)
* Content Source: [Skype/SfbServer/deploy/deploy-monitoring/install-monitoring-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-monitoring/install-monitoring-reports.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi.
That information is covered in the same section, at the "Associate a monitoring store"document.
Thank you
