### ISSUE TITLE
-MembershipType doesn't appear to be a valid parameter on Get-TeamChannelUser

### ISSUE THREAD

**Issue by HandyAndyOnGitHub** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3733]
-MembershipType doesn't appear to be a valid parameter on Get-TeamChannelUser

In the section "List and update roles of owners and members in a private channel" there is an issue with the PowerShell command under "Using PowerShell &gt; Request".

This results in an error "Get-TeamChannelUser : A parameter cannot be found that matches parameter name 'MembershipType'":
Get-TeamChannelUser -GroupId &lt;group_id&gt; -MembershipType Private -DisplayName "&lt;channel_name&gt;" 

This works ok:
Get-TeamChannelUser -GroupId &lt;group_id&gt; -DisplayName "&lt;channel_name&gt;" 

Am I missing something or is -MembershipType incorrect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e0ac38-cfff-8d8f-5345-2ae93a9fae2e
* Version Independent ID: bec44289-e9fa-4464-1601-0ca86d61e6ca
* Content: [Manage the life cycle of private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels-life-cycle-management#feedback)
* Content Source: [Teams/private-channels-life-cycle-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels-life-cycle-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by HandyAndyOnGitHub** [comment]
... same issue in "3. Promote a member to an owner."

**Comment by scanum** [comment]
@HandyAndyOnGitHub Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by HandyAndyOnGitHub** [comment]
Just noticed this issue was raised (but not resolved) in closed ticket titled: "error when adding Teams Channel owner"

**Comment by LanaChin** [comment]
Hi @HandyAndyOnGitHub - can you let us know what version of the Teams PowerShell module that you're using? Do you have the pre-release version from the PowerShell Test Gallery installed?  Thanks.

**Comment by HandyAndyOnGitHub** [comment]
Hi @LanaChin yes I followed the instructions to install the pre-release version from the Test Gallery.

PS C:\WINDOWS\system32> Get-Module -Name MicrosoftTeams

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     1.0.18     MicrosoftTeams                      {Add-TeamChannelUser, Add-TeamUser, Connect-MicrosoftTeams, Disconnect-MicrosoftTeams...}

**Comment by LanaChin** [comment]
Thanks @HandyAndyOnGitHub. We're currently looking into this.

**Comment by LanaChin** [comment]
@HandyAndyOnGitHub, thanks for bringing this to our attention. You are correct. Confirmed that the -MembershipType Private parameter isn't needed for Get-TeamChannelUser and Add-TeamChannelUser. The doc has been updated: https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels-life-cycle-management#list-and-update-roles-of-owners-and-members-in-a-private-channel.
