### ISSUE TITLE
Issue with Requirements

### ISSUE THREAD

**Issue by JasonLinTW12** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3734]
1.Skype for Business Online (Plan 2, or an Enterprise-based plan) or higher in your Office 365 plan. The plan needs to allow dial-in conferencing capabilities.

suggest adding To enable "Teams" description

2.If you need dial-in capabilities from a meeting, you will need an audio conferencing and Phone System license. If you need dial-out capabilities from a meeting, you will need a domestic or domestic and International Calling Plan.

I think it only needs audio conferencing for dial-out capabilities from a meeting, no need Phone System license and domestic or domestic and International Calling Plan.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/room-systems/with-office-365#feedback)
* Content Source: [Teams/room-systems/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/with-office-365.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@JasonLinTW12 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LanaChin** [comment]
Merged, thank you.
