### ISSUE TITLE
On-Prem only Exchange

### ISSUE THREAD

**Issue by skywalkerisnull** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3735]
The table above indicates that we can setup Teams and On-Prem exchange (without a hybrid deployment) if the we are using Exchange 2016 CU3 or higher. However all of the linked support documents only describe how to deploy in a hybrid environment with Exchange Online. 

Are there any documents describing how to setup Teams with an On-Prem only environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact#feedback)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@skywalkerisnull Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by cleik59** [comment]
I am interested in the same documentation.

**Comment by skywalkerisnull** [comment]
Ok, so what I have gathered so far you need:

- AD Sync working
- The domain that the users are using on-prem to authenticate has to match the email domain, so no .local as the sign-in domain
- Autodiscover setup and working, check it is working with this site: https://testconnectivity.microsoft.com/
- Autodiscover has to work with both the user name and email address being the same

This is as far as I have got, we can send teams meeting invites from within outlook on a computer that has Teams installed. Still wanting to know how we can get it to have the meetings tab from within Teams so it is more seamless as the table above seems to indicate is possible.

**Comment by skywalkerisnull** [comment]
And a few more steps, you can setup the OAuth, however a number of the powershell commands will throw errors because you are not licenses in the cloud for exchange online.

**Comment by dariomws306** [comment]
Hi @skywalkerisnull, thank you for your feedback.

@dstrome could you kindly help? I don't have this information.

**Comment by dstrome** [comment]
hi all. Thanks for the question. I'm following up with one of our PMs to get an answer for you.

**Comment by scanum** [comment]
@dstrome Hi David! Thank you. Any update on this?

**Comment by GitHokie** [comment]
@dstrome @scanum I'm also interested in this if you have any more documentation. Thanks

**Comment by i-windows** [comment]
@dstrome @scanum also interested, I've also discussed it with a fastrack engineer and they are unclear as to why we don't see the calendar in Teams.

**Comment by kashifexchange** [comment]
We are also facing this issue as the calendar icon is missing from teams since our all mailboxes are on exchange on-premises 2016 CU14 and we have AD connect in place to sync users to office 365. But no exchange attributes are syncing to cloud. we needed to know if we have to tick hybrid option in Ad connect or we need to sync all the exchange attributes or setup OAuth to see the calendar icon on teams. Any inputs will be appreciated.

**Comment by larsdemo123** [comment]
I have the same questions its totaly not clear if a hybrid is needed to get this calendar app work in the teams mobile app

**Comment by tobvil** [comment]
Same question. Will it work with on-prem Exchange without Hybrid deployment?

**Comment by i-windows** [comment]
as an update, Oauth is required between on prem and o365.

**Comment by cm1984** [comment]
is there a clear documentation how to sync users calendar exchange 2016 onpremise to teams. we do not have hyprid. is there an intraorganizationconnector needed? this article is about onpremise and exchange online: https://docs.microsoft.com/en-us/exchange/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help

**Comment by larsdemo123** [comment]
https://www.youtube.com/watch?v=V6B4KraD-FM
54:00
All the information is here.
For calendar in Teams there is a hybrid needed because the calendar of the user is in the mailbox hosted on-premise.
Beside that Teams and Exchange on-premise without hybrid is not supported.

**Comment by Karspi** [comment]
@larsdemo123 please provide us the article were states that Teams and Exchange on-premise without hybrid is not supported. Allow me to add my two cents regarding that, you can have the calendar in MS Teams with Exchange on-premises and without any hybrid configuration, this is not needed therefore not stated in this article. The following steps are needed to get that work : 

What here truly is needed are the following steps:

Azure AD Connect with Exchange Hybrid attributes sync
1.1 From that point, the Exchange Online is aware of the on-premises mailbox
Exchange on-premises 2016 CU3+
Exchange on-premises must be accessible from MS Teams IP
3.1 Autodiscover will be used from MS Teams backend services to discover and access the Exchange on-premises
3.2 Firewall rule to allow traffic may be required - MS Teams backend services IPs - http://aka.ms/ipurlws
3.2 Create Autodiscover DNS entry in your public DNS and point to your Exchange Server if it is not set
3.3 Exchange on-premises should answer to requests over 443 with a public certificate which covers autodiscover and the external hostname of the server
OAUTH has to be configured
4.1 https://docs.microsoft.com/en-us/exchange/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help
4.2 Step 1-5 should be enough, test if OAUTH is working with the steps at the bottom of the article.
Please message me if you face any issue and I would be happy to assist you

Spikar

**Comment by larsdemo123** [comment]
like i write before 
If you watch this video from 54:00
https://www.youtube.com/watch?v=V6B4KraD-FM
You see that Teams and Exchange on-premise without hybrid is not supported according to Microsoft 
It is the last line in the picture in 54:00

**Comment by dariomws** [comment]
From the video:
![image](https://user-images.githubusercontent.com/33589238/79054538-013e2580-7c1c-11ea-9410-990ddad46496.png)

@dstrome could you kindly help us? Thanks!

**Comment by Pineapple87** [comment]
@Karspi Thank you for your concise explanation.  We run Exchange 2016 on Prem and want the Calendar button in Teams.  I have gone through the steps of enabling Exchange Hybrid Deployment and running through steps 1-5 in the referenced Oauth article and am still not seeing any Calendar button appear.  Not quite sure what to make of it.  I do see you note that Exchange on-premises must be accessible from MS Teams IP...could you elaborate a bit on that?  Would that be creating a new inbound rule on our firewall that's different than the OWA access rule we already have?  Thanks again for your contributions here!

**Comment by Karspi** [comment]
@Pineapple87 your Exchange infrastructure has to be accessible over port TCP443 from the Microsoft Teams IP addresses, if you have a firewall rule any -> public IP exchange -> TCP443 -> exchange on-premises, that should be ok. Check if your public DNS has an entry for autodiscover.contoso.org and that points to your exchange public IP address. Don't forget to check for the calendar button over a browser where you can clear the cache. In Microsoft Teams client on Windows 10 you have to logout and login back to see the button, in some cases, you have to clear the Microsoft Teams' cache to be able to see it.

**Comment by Pineapple87** [comment]
@Karspi I've checked our firewall and autodiscover DNS records and all looks good.  I've also tried logging in and out of the Win 10 client, as well as logging in on the web from a PC I don't normally use.  Any chance MFA for OWA could be coming into play?  I'm assuming there's no need to restart any Exchange services?  Thanks again.

**Comment by dstrome** [comment]
An Exchange hybrid deployment is required when integrating Teams with an on-premises Exchange deployment. This is in addition to version-specific requirements for some features. The article has been updated to reflect this requirement.

**Comment by Pineapple87** [comment]
@dstrome Does a "Exchange hybrid deployment" consist of merely enabling "Exchange Hybrid Deployment" in the Azure AD Connect utility or is there more to it?  Still struggling getting the calendar button to appear in Teams.

**Comment by causeway74** [comment]
Would it be possible to add more detail on exactly what the user experience would be like where certain features aren't supported? What about a table that includes feature support by Exchange on-prem version?
