### ISSUE TITLE
Need update or adding link.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#374]
This page could be improved by linking to "The 11 predefined roles that cover many common administrative tasks".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca8a34ff-3787-e1e7-10ef-a76d4cecf684
* Version Independent ID: 9efbad5a-a3f8-6c8a-480d-864f24adcefa
* Content: [Role-based access control (RBAC) for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/security/role-based-access-control-rbac)
* Content Source: [Skype/SfbServer/plan-your-deployment/security/role-based-access-control-rbac.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/security/role-based-access-control-rbac.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Details of the roles of RBAC had been already added to the document. Thank you!
