### ISSUE TITLE
incorrect Concurrent live events limit in an Office 365 tenant

### ISSUE THREAD

**Issue by tonys2020** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3740]
I assume the limit should be 15 instead of 1.5

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limites et spécifications de Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/fr-fr/microsoftteams/limits-specifications-teams#teams-live-events)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@tonys2020 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@tonys2020 thanks for reaching out, but it seems like this has been updated in the interim. Please double check and let me know. @OfficeGlobal

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@tonys2020 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you
