### ISSUE TITLE
listing private channels is not working anymore

### ISSUE THREAD

**Issue by SjoerdV** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3741]
Seems the cmdlet to list private channels is not working anymore in the 1.0.18 release, can somebody concur?

When running:
```powershell
Get-TeamChannel -GroupId $groupid -MembershipType Private
```

This is the error returned:
```
Get-TeamChannel : Error occurred while executing
Code: BadRequest
Message: The query specified in the URI is not valid. The string 'Microsoft.Teams.GraphSvc.channelMembershipType'private'' is not a valid enumeration type constant.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e0ac38-cfff-8d8f-5345-2ae93a9fae2e
* Version Independent ID: bec44289-e9fa-4464-1601-0ca86d61e6ca
* Content: [Manage the life cycle of private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels-life-cycle-management)
* Content Source: [Teams/private-channels-life-cycle-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels-life-cycle-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@SjoerdV Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by SjoerdV** [comment]
Seems to be working again, temporary issue as it seems. Thanks for finding out and your effort on this!
