### ISSUE TITLE
Incorrect powershell cmdlt in example

### ISSUE THREAD

**Issue by d1bjo0** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3742]
See above on the example poweshell string: 
 "$members | ForEach-Object { Grant-CsTeamsChannelsPolicy -PolicyName "Operations Emergency Calling Policy" -Identity $_.UserPrincipalName}"      The Grant-CsTeamChannelsPolicy should be Grant-CsTeamsEmergencyCallingPolicy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66544770-c56b-ad8a-5b67-9e20cbc945f1
* Version Independent ID: d69667d5-d486-4b99-5e07-edb2fda7f5c7
* Content: [Manage emergency calling policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/manage-emergency-calling-policies?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/manage-emergency-calling-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-emergency-calling-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@d1bjo0 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LanaChin** [comment]
@db1bj0, @dariomws306 - thank you! The change is merged.
