### ISSUE TITLE
Calling Plans

### ISSUE THREAD

**Issue by CharlesYeomans** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3743]
This all seems confusing.  So now it seems to say you can get Phone System one business premium but you cannot get calling plans, but you can get communications credits ?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4526bb5-3b0b-87c9-0ed1-daac9280f81e
* Version Independent ID: e1bddd5e-8087-19d8-7cec-5ea958345665
* Content: [Availability in Hong Kong - Microsoft Teams](https://docs.microsoft.com/en-gb/MicrosoftTeams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-hong-kong)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-hong-kong.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-hong-kong.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@CharlesYeomans  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by a113n** [comment]
We recently bought the domestic calling plan but we failed to make outbound calls using teams app. There isn’t an option to assign numbers to users as well. The call queue and auto attendant functions work fine though.

How can I enable the outbound calling function in Teams?

**Comment by CharlesYeomans** [comment]
A113N
It would be great if you could share getting the calling plan info and what and how you use Call Queue and Auto Attendant (i.e. a bit about your set up).  
Did you have Enterprise E series ? to subscribe to phone system first ?

**Comment by dariomws306** [comment]
Hi @CharlesYeomans, thank you for your feedback.

This article is for Hong Kong. You can get Phone System there, but not Calling Plans. In this case you will get a Phone System license to configure Direct Routing. More information:
https://docs.microsoft.com/microsoftteams/direct-routing-landing-page

**Comment by scanum** [comment]
@CharlesYeomans Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
