### ISSUE TITLE
Need link of plug in that needs to be installed.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#375]
Where can I find the link to the plug in that needs to be installed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ce7a531-5b1f-f404-50a3-58eb285a0a1a
* Version Independent ID: 61d27af3-cfd6-ed7f-102c-072721db0209
* Content: [Plan for Meetings clients (Web App and Meetings App)](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/meetings-clients#feedback)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/meetings-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/meetings-clients.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi thanks for your feedback!
The plugin is mentioned early in the document as Skype for Business Web App browser plug-in
Hope this information has helped you!

**Comment by jambirk** [comment]
A more detailed answer: the browser plugin self-installs when an external user without a regular client tries to access a meeting via the web. You can't preinstall the plugin, the only way to get it is to try to join a meeting. Most questions of this nature stem from wanting to have the client preinstalled, which isn't a supported scenario.

**Comment by get-itips** [comment]
Thanks for expanding my answer @jambirk
