### ISSUE TITLE
New-TeamChannel : Error occurred while executing Code: BadGateway

### ISSUE THREAD

**Issue by GaelBSB** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3751]
Hi
I ran a script to create 140 channels. 10 of them are created without any problem and then nothing more. I can't create a channel anymore. 

New-TeamChannel : Error occurred while executing 
Code: BadGateway
Message: Failed to execute backend request.
InnerError:
  RequestId: d64aa648-680f-464a-a9b9-8f4a4f6e8215
  DateTimeStamp: 2020-01-09T18:54:16
HttpStatusCode: BadGateway
Au caractère C:\Users\gmillier\Documents\Sans titre2.ps1:13 : 1
+ New-TeamChannel –GroupId e480e4cb-c1b3-47f7-b92e-a22698f97c1c –Member ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-TeamChannel], ApiException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdlets.PowerShell.Custom.NewTeamChannel

**Comment by GaelBSB** [comment]
We have reached the size limit, which is 30 private channels. Is it possible to set the same limit as for the public channels (200)?

**Comment by scanum** [comment]
@GaelBSB  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@GaelBSB thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
