### ISSUE TITLE
BadGateway error when attempting to promote Member to Owner when I'm not an existing Owner on the Private Channel

### ISSUE THREAD

**Issue by HandyAndyOnGitHub** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3753]
I'm getting a BadGateway error when attempting to promote a Member to Owner.  I have Global Admin permissions but I'm not existing Owner on the Private Channel.  

PS C:\WINDOWS\system32&gt; Add-TeamChannelUser -GroupId $GroupID -DisplayName $ChannelName -User $UserUPN -Role Owner
Add-TeamChannelUser : Error occurred while executing
Code: BadGateway
Message: Failed to execute backend request.
InnerError:
  RequestId: 66b210ef-4db9-4788-a661-c0f79b42304f
  DateTimeStamp: 2020-01-10T00:56:31
HttpStatusCode: BadGateway
At line:1 char:1
+ Add-TeamChannelUser -GroupId $GroupID -DisplayName $ChannelName -User ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-TeamChannelUser], ApiException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdlets.PowerShell.Custom.AddTeamChannelUser

Also raised this as a Support Ticket.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e0ac38-cfff-8d8f-5345-2ae93a9fae2e
* Version Independent ID: bec44289-e9fa-4464-1601-0ca86d61e6ca
* Content: [Manage the life cycle of private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels-life-cycle-management#install-the-latest-teams-powershell-module-from-the-powershell-test-gallery)
* Content Source: [Teams/private-channels-life-cycle-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels-life-cycle-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@HandyAndyOnGitHub  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@HandyAndyOnGitHub thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by HandyAndyOnGitHub** [comment]
I've already raised a Service Ticket and they won't look at it because the
feature is in Beta and told me to raise it here so the Product Team could
address the issue.

**Comment by rlodev67** [comment]
Hey
I have the same issue at the moment.
Did you find a workarround ?

thanks

**Comment by Reddzman** [comment]
I am currently having this issue in my dev tenant with the New-Team PS command.  Please let me know if there are any resolutions.

New-Team : Error occurred while executing
Code: BadGateway
Message: Failed to execute backend request.
InnerError:
  RequestId: 85a8c302-6fcc-426e-9409-fed94ccc613b
  DateTimeStamp: 2020-03-25T14:00:50
HttpStatusCode: BadGateway
At C:\VisualStudio\Cat.Scripts\Offering\Cat.MT-DeployCrisisTeam.ps1:140 char:10
+     $team = New-Team -DisplayName $workspace.DisplayName `
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-Team], ApiException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdlets.PowerShell.Custom.NewTeam

**Comment by BWMerlin** [comment]
I am likewise getting this error message.

Here is my code
`$channelowners = @(
 "person1@email.com"
 "person2@email.com"
 "person3@email.com"
)

$teamname = "The team"

$team = Get-Team -DisplayName $teamname

$channelnames = Get-TeamChannel -GroupId $team.GroupId

foreach ($channel in $channelnames) {
    
    foreach ($owner in $channelowners) {
    Add-TeamChannelUser -GroupId $team.GroupId -DisplayName $channel.DisplayName -User $owner -Role Owner}}`

And the error information is

`Add-TeamChannelUser : Error occurred while executing 
Code: BadGateway
Message: Failed to execute backend request.
InnerError:
  RequestId: a4bf556f-4db2-4fc4-a6ec-18edf06833d7
  DateTimeStamp: 2020-04-16T23:40:03
HttpStatusCode: BadGateway
At line:4 char:5
+     Add-TeamChannelUser -GroupId $team.GroupId -DisplayName $channel. ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-TeamChannelUser], ApiException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdlets.PowerShell.Custom.AddTeamChannelUser`
