### ISSUE TITLE
No longer applicable

### ISSUE THREAD

**Issue by CharlesYeomans** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3754]
It still references Skype for Business in Admin, but that has disappeared. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cad07c2d-dc0c-faa4-9fde-0377c413dc0f
* Version Independent ID: e5a76596-eb09-88eb-46ca-4353061bd631
* Content: [Setting up Phone System in your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/setting-up-your-phone-system)
* Content Source: [Teams/setting-up-your-phone-system.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/setting-up-your-phone-system.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@CharlesYeomans  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@CharlesYeomans Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
