### ISSUE TITLE
Dark theme considerations

### ISSUE THREAD

**Issue by Dottn** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3755]
The tick marks in the comparison table are very dark and hard to see when reading in dark mode or with high contrast.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [What the guest experience is like - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/guest-experience)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Dottn  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LanaChin** [comment]
Thanks for your feedback, @Dottn. The doc has been updated. Thanks for making the changes, @dariomws306.
