### ISSUE TITLE
How to find a list of service providers?

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#376]
How to find a list of service providers? This page tells to choose one, but does not point in the right direction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31112937-132f-f79c-5fd2-94d05886655b
* Version Independent ID: 37f13716-f027-97e5-27e7-73a4e9f44553
* Content: [Choose an E9-1-1 service provider for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/enterprise-voice-solution/choose-a-service-provider)
* Content Source: [Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/choose-a-service-provider.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/choose-a-service-provider.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Created a PR to include a link to the information.
