### ISSUE TITLE
Dial by extension Skype for Business on-premises support

### ISSUE THREAD

**Issue by paulch7780** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3760]
Cloud AA dial-by-extension requires transfer destination users to be in Teamsonly mode. Please re-work the article to reflect the correct configuration support as per https://docs.microsoft.com/en-us/microsoftteams/migration-interop-guidance-for-teams-with-skype
...
Dial by extension If you enable this option, callers can connect with users in your organization by entering their phone extension. You can select which users are listed as available or not available for Dial by extension in the optional Dial Scope page. Any online user with a Phone System license, or any user hosted on-premises using Skype for Business Server, is an eligible user and can be found with Dial by extension.

**Comment by scanum** [comment]
@paulch7780 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @paulch7780, thank you for your feedback.

My apologies, maybe I am misunderstanding you but in the article you posted I cannot find any mention to auto attendants or dial by extension.

**Comment by scanum** [comment]
@paulch7780 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
