### ISSUE TITLE
Over-translation again #2927 "チームの追加ユーザー"→"Add-TeamUser"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3763]
ja-jp:
![teams-powershell-overview_j](https://user-images.githubusercontent.com/40815708/72212250-d577aa80-351b-11ea-916e-b8e9807e3c15.png)

en-us:
![image](https://user-images.githubusercontent.com/40815708/72212197-f390db00-351a-11ea-8fc2-2921b89e1baf.png)

related: #2927 "[LOC] Back-Translation "チームの追加ユーザー"→"Add-TeamUser"" 

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 26362d70-cfce-2eea-077b-4aaa50f92e8b
* Version Independent ID: f52dcd4d-4f58-05c4-11b0-f1e3c95f4d89
* Content: [Teams での PowerShell の概要 - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/teams-powershell-overview)
* Content Source: [Teams/teams-powershell-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@officeglobal Could you please help on this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum the article has been HumanTranslated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal  - Corrected.
Closed #3763.
Thanks.
