### ISSUE TITLE
Incorrectly spelt attribute

### ISSUE THREAD

**Issue by PaulMaggs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3764]
From Powershell, when running 'Set-Get-CsOnlinePSTNGateway' (or related get/new powershell commands)  returns an incorrectly spelt attribute:

OutbundTeamsNumberTranslationRules

It should be

OutboundTeamsNumberTranslationRules

**Comment by scanum** [comment]
@PaulMaggs Thank you for submitting feedback and contributing to the docs. We are currently investigating this. Could you please link the document you are referring to?

**Comment by scanum** [comment]
@PaulMaggs We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
