### ISSUE TITLE
Attribute spelling issue

### ISSUE THREAD

**Issue by PaulMaggs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3765]
From Powershell, when running 'Set-Get-CsOnlinePSTNGateway' (or related get/new powershell commands)  returns an incorrectly spelt attribute:

OutbundTeamsNumberTranslationRules

It should be

OutboundTeamsNumberTranslationRules

**Comment by scanum** [comment]
@PaulMaggs Could you please link the document you are referring to?

**Comment by PaulMaggs** [comment]
Here's the reference - https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-configure

The attribute is correct in the documentation, however, the Powershell cmdlet has a misspelt attribute.  

Hope that helps.

**Comment by lindspea** [comment]
@PaulMaggs thank you for reaching out and helping improve MS Docs. I work on the writing side to correct issues in the actual content of the article. Can you confirm if the spelling error is in the actual article or in which link inside the article?

**Comment by scanum** [comment]
@PaulMaggs We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
