### ISSUE TITLE
Symantics on Assigning app setup policies to users 'in a group'

### ISSUE THREAD

**Issue by jadesolis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3766]
"Assign the FirstlineWorker app setup policy to users in a group" should be "Assign the FirstlineWorker app setup policy to users OF a group" 
The members being assigned the policy does not need to be IN the group, as the policy is assigned only the individual members, and not the actual group itself.
This may send the wrong impression that the policy can actually be assigned to a group in itself, and that subsequent new members assigned to that group will be have the policy automatically assigned to them; at least make that clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58ea9573-59b1-1499-fb83-517d0ee0f034
* Version Independent ID: bf98f739-ff51-0b90-dbc5-c594d3dacecd
* Content: [Manage the Shifts app for your organization in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams#feedback)
* Content Source: [Teams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams.md)
* Service: **msteams**
* GitHub Login: @kenwith
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@jadesolis Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@jadesolis Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
