### ISSUE TITLE
Access to data through an API

### ISSUE THREAD

**Issue by bastienczl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3769]
Hello,

Is it possible to access the data through an API ? Or at least, a CSV export ?

If not, is it a part of the roadmap ?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8107d4a3-a55e-4891-ee72-27f79f647a1e
* Version Independent ID: b71f24c6-b54d-8a0f-ea0e-8839ff5481a4
* Content: [Microsoft Teams PSTN minute pools report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/pstn-minute-pools-report#)
* Content Source: [Teams/teams-analytics-and-reports/pstn-minute-pools-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/pstn-minute-pools-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@bastienczl Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@bastienczl thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by SanderSade** [comment]
Beta version of PSTN usage report in Graph is now available - see https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta
