### ISSUE TITLE
How to run the report?

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#377]
Trying to find how to run the report and can't find it anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93cfab41-183d-0dc0-a247-68c47a8cc576
* Version Independent ID: f5a72790-15a6-c0ef-0a7a-2a4313b4fa2e
* Content: [Response Group Usage Report in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/manage/health-and-monitoring/response-group-usage-report)
* Content Source: [Skype/SfbServer/manage/health-and-monitoring/response-group-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/health-and-monitoring/response-group-usage-report.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi,
As this document is under "Monitoring Reports" section, you have to look for instructions there to see how to run and view this report.
Thank you
