### ISSUE TITLE
Direct Routing is only supported with Microsoft Teams. 

### ISSUE THREAD

**Issue by rickleye** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3770]
Is this statement correct ? I have seen a couple of tickets were in the client had Island coexistence mode. Which means that calls land on both Skype and Teams - And it appears to be a working solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d964547-6b38-cc5f-6b2b-7a50a1c7dae9
* Version Independent ID: fa5850f9-1b92-9727-c344-bcffc227cbd6
* Content: [Phone System Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-landing-page)
* Content Source: [Teams/direct-routing-landing-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-landing-page.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@rickleye Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by BryanNyce** [comment]
This statement is correct. Phone System is only supported in Microsoft Teams (Teams Only mode). Working does not mean supported; Islands is not a supported mode with Teams Direct Routing (and Phone System in general).

**Comment by rickleye** [comment]
Understood. Thanks for the clarification.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by scanum** [comment]
@rickleye Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
