### ISSUE TITLE
Access user presence in Teams via an API

### ISSUE THREAD

**Issue by ryanbuening** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3772]
Is it possible to access a users Teams presence state (Online/Offline/etc.) from a custom web app via an API/Microsoft Graph?

**Comment by scanum** [comment]
@ryanbuening Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@ryanbuening thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
