### ISSUE TITLE
Kollective pointing to broken URL

### ISSUE THREAD

**Issue by arianasexton** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3774]
Hello - When you click on 'Kollective' under Enterprise Content Delivery Network (eCDN), the link is broken. Can you change the link to: https://portal.kollective.app/ 

Thank you so much!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: becbf3ca-b88c-b033-a145-9a1af201ced3
* Version Independent ID: 41a6a9b5-d3dd-d8c9-9e97-920ff2fd1a24
* Content: [What are Microsoft Teams live events? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/what-are-teams-live-events#feedback)
* Content Source: [Teams/teams-live-events/what-are-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/what-are-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@arianasexton Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by arianasexton** [comment]
Hello - Manuela  
Can you provide an update on changing the Kollective link in this post to a non-broken url? The correct link is https://portal.kollective.app/
Thank you so much for your help.
