### ISSUE TITLE
There is an incomplete sentence

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3775]
![image](https://user-images.githubusercontent.com/13634805/72320390-ec1d2d80-36e4-11ea-857b-8877016eb48d.png)

https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report#definitions

The continuation of this appears as described in the Note at the bottom of the same article.

![image](https://user-images.githubusercontent.com/13634805/72320651-7796be80-36e5-11ea-832f-bb45f26682cf.png)

Thank you!

**Comment by scanum** [comment]
@kefujino Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@kefujino thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
