### ISSUE TITLE
Is there any API to know whether a specific user is a guest or not, or some way can try?

### ISSUE THREAD

**Issue by JemmyWong** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3776]
We are developing a Teams App which needs to know another participant's phone number in a chat, but the guest user's token doesn't have such privilege, so we're going to restrict the usage of our app for guests. 

But don't find any API to know the current user's role.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2492e210-08f9-a476-97ec-008926def961
* Version Independent ID: adcb0dd9-4a3c-b665-6e34-ce3276c89b4d
* Content: [Guest access in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-access#feedback)
* Content Source: [Teams/guest-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@JemmyWong Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by JemmyWong** [comment]
Hi @scanum Is there any update?

**Comment by scanum** [comment]
@JemmyWong thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
