### ISSUE TITLE
Org Chart documentation missing

### ISSUE THREAD

**Issue by Kentrepid** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3779]
There is no documentation anywhere mentioning where Org Chart configuration resides, maintaining Org Charts, who has access to configure this and why this feature is unavailable for some organisations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9b7f77-061d-a224-ff1c-8d3e15d21221
* Version Independent ID: 00fa9550-c4c4-3398-ffbb-271cc724048f
* Content: [Manage Microsoft Teams settings for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/enable-features-office-365#feedback)
* Content Source: [Teams/enable-features-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enable-features-office-365.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Kentrepid  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @Kentrepid, thank you for your feedback.

Manager configuration is outside of the Teams scope. This information resides in Azure AD and the easier way to configure it is using Exchange tools. For example, for cloud only organizations:
https://docs.microsoft.com/exchange/recipients-in-exchange-online/manage-mail-users#organization

I don't have the information about in which organizations this tab is not available. @LolaJacobsen could you kindly help with this?

**Comment by scanum** [comment]
@Kentrepid  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
