### ISSUE TITLE
Page should be updated, Skype for Business is no more.

### ISSUE THREAD

**Issue by CharlesYeomans** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3782]
Obviously the rush to move to teams from SfB has meant a lot of documentation is not really going to make sense.
It is critical that SMEs can get a method for calling out from teams, rather than having to go to ordinary Skype.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0b2993f-74b2-a59a-fee1-0a5ddcf9e9ff
* Version Independent ID: 01a02c95-cd74-9c82-f5a4-a6bc9adb52a9
* Content: [Set up Calling Plans - Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/set-up-calling-plans)
* Content Source: [Teams/set-up-calling-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-calling-plans.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@CharlesYeomans  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @CharlesYeomans, thank you for your feedback.

Maybe I don't understand you but Phone System with Calling Plans or Direct Routing enables users to call out directly from Teams client.

**Comment by CharlesYeomans** [comment]
It seems you can only get Phone System with Enterprise versions.
With Office 365 Business Premium you cannot get Phone System, and that will affect a lot of SMEs
I am not sure why it is not just a paid service of some amount plus the telephone company charges for usage.

**Comment by dariomws306** [comment]
That is true. You need an Enterprise license/plan to enable Phone System.

docs.microsoft.com feedback is available to improve documentation. The best place to request features is https://microsoftteams.uservoice.com/. There, your suggestion will reach the product team.
I see there is an idea and I think you voted:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/36534148-need-phone-system-licenses-from-office-365-busines

**Comment by scanum** [comment]
@CharlesYeomans Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
