### ISSUE TITLE
Search shows results to Teams I'm not in

### ISSUE THREAD

**Issue by KatrinW** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3784]
I created many Teams with my account prior to the rollout of the Teams admin center. I would create a Team, add the owners and members, and then "leave" the Team. I am noticing that search is showing results to Teams I am not a part of (but I did create initially). When I click, I cannot view the channel conversation, but I feel like search should not even show results to conversations where I have no permissions. Why is this happening? Is it a known bug or a new bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues#feedback)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@KatrinW  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@KatrinW thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
