### ISSUE TITLE
Retiral of ediscovery tools

### ISSUE THREAD

**Issue by thewrabbit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3789]
Can article be reviewed please in light of https://docs.microsoft.com/en-us/microsoft-365/compliance/legacy-ediscovery-retirement to ensure reflects correct information.  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca579d63-182b-d6f5-8777-79248fa27ed9
* Version Independent ID: b4c27d1b-b2f1-41ac-b15c-d12b448a539e
* Content: [Overview of security and compliance in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/security-compliance-overview#feedback)
* Content Source: [Teams/security-compliance-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/security-compliance-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by dariomws306** [comment]
Hi @thewrabbit, thank you for your feedback.

I have done a quick review of this article and I see that it only has a brief description about eDiscovery and some links for more information. I couldn't find any outdated information.

**Comment by scanum** [comment]
@thewrabbit Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
