### ISSUE TITLE
Incorrect command in Powershell to assign a custom emergency call routing policy to users in a group

### ISSUE THREAD

**Issue by s1satya** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3792]
$members | ForEach-Object { Grant-CsTeamsChannelsPolicy -PolicyName "HR Emergency Call Routing Policy" -Identity $_.UserPrincipalName}

Needs to be like below:

$members | ForEach-Object { Grant-CsTeamsEmergencyCallRoutingPolicy -PolicyName "HR Emergency Call Routing Policy" -Identity $_.UserPrincipalName}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0a230ba-f141-3a40-12de-03b05a316a52
* Version Independent ID: 402a7d5f-4736-0f8e-7bba-8af03484085e
* Content: [Manage emergency call routing policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-emergency-call-routing-policies?source=docs#feedback)
* Content Source: [Teams/manage-emergency-call-routing-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-emergency-call-routing-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@s1satya Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
