### ISSUE TITLE
There is no auto-favorites feature (replaced with show for members)

### ISSUE THREAD

**Issue by narismadz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3793]
I think they are get rid of "Favorites" and rename as "show" (for members)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team#feedback)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by get-itips** [comment]
Hello @narismadz 
Thanks for noticing 👍 Created a pull request to update the article with this latest change.
Thank you for your contribution.
