### ISSUE TITLE
None of the videos work

### ISSUE THREAD

**Issue by davidbenjaminnz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3794]
Currently none of the videos on this page are working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e640245-6d25-2165-3792-9bb386a73184
* Version Independent ID: 28951938-7e00-16fd-c216-a569ba94b041
* Content: [Videos - Audio Conferencing in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-videos#feedback)
* Content Source: [Teams/audio-conferencing-videos.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-videos.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by get-itips** [comment]
Hello @LolaJacobsen 
It seems the videos are marked as "private", can you please assist to make them public so they can be playable ?
Thank you

**Comment by get-itips** [comment]
@LolaJacobsen 👍 Lola, can you help? Thanks

**Comment by LolaJacobsen** [comment]
I'm killing that article.
