### ISSUE TITLE
[LOC]"Microsoft Teams のルーム" needs to be replaced with "Microsoft Teams Rooms"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3797]
ja-jp:"https://docs.microsoft.com/ja-jp/MicrosoftTeams/room-systems/skype-room-systems-v2-0"
![skype-room-systems-v2-0_j](https://user-images.githubusercontent.com/40815708/72581213-e3656b00-3921-11ea-8d52-008fbacd66cb.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1c25c286-2a25-19d1-6847-f2324b3deb73
* Version Independent ID: 0c82ef28-f9c8-1845-c167-ce2756478d9c
* Content: [Microsoft Teams のルームを計画する - Microsoft Teams](https://docs.microsoft.com/ja-jp/MicrosoftTeams/room-systems/skype-room-systems-v2-0)
* Content Source: [Teams/room-systems/skype-room-systems-v2-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/skype-room-systems-v2-0.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by hyoshioka0128** [comment]
en-us:"https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/skype-room-systems-v2-0"
![skype-room-systems-v2-0_e](https://user-images.githubusercontent.com/40815708/72597065-55ed3f80-3950-11ea-8197-0a7b9e02187e.png)

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@OfficeGlobal Please check, English version is reading correctly.

**Comment by OfficeGlobal** [comment]
Working on a fix
Note: article redirected to https://docs.microsoft.com/ja-jp/MicrosoftTeams/rooms/rooms-plan

**Comment by scanum** [comment]
@OfficeGlobal Any update on this? Thanks!

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum 

Approved translation (by MS) for _Microsoft Teams Rooms_ is _Microsoft Teams ミーティング_
The article was HumanTranslated and published live
![image](https://user-images.githubusercontent.com/47977325/77745448-94bc0780-701b-11ea-8fec-f0bf6b31105a.png)

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
