### ISSUE TITLE
[LOC]"Microsoft Teams の会議室" needs to be replaced with "Microsoft Teams Rooms"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3798]
ja-jp:"https://docs.microsoft.com/ja-jp/MicrosoftTeams/room-systems/skype-room-systems-v2-0"
![skype-room-systems-v2-0_j2](https://user-images.githubusercontent.com/40815708/72581415-a057c780-3922-11ea-8d6e-f0e6f9fd7cb4.png)

em-us:
![skype-room-systems-v2-0_e2](https://user-images.githubusercontent.com/40815708/72581404-9766f600-3922-11ea-8086-2846c433b6db.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1c25c286-2a25-19d1-6847-f2324b3deb73
* Version Independent ID: 0c82ef28-f9c8-1845-c167-ce2756478d9c
* Content: [Microsoft Teams のルームを計画する - Microsoft Teams](https://docs.microsoft.com/ja-jp/MicrosoftTeams/room-systems/skype-room-systems-v2-0)
* Content Source: [Teams/room-systems/skype-room-systems-v2-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/skype-room-systems-v2-0.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@OfficeGlobal Please check, English version is reading correctly.

**Comment by OfficeGlobal** [comment]
Working on a fix
Note: article redirected to https://docs.microsoft.com/ja-jp/MicrosoftTeams/rooms/rooms-plan

**Comment by scanum** [comment]
@OfficeGlobal Any update on this Thanks!!!

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum

Approved translation (by MS) for _Microsoft Teams Rooms_ is _Microsoft Teams ミーティング_
The article was HumanTranslated and published live

(related to #3797 )

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
