### ISSUE TITLE
[LOC]"Microsoft Teams 室" needs to be replaced with "Microsoft Teams Rooms"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3799]
ja-jp:"https://docs.microsoft.com/ja-jp/MicrosoftTeams/room-systems/srs2-lifecycle-support"
![srs2-lifecycle-support_j](https://user-images.githubusercontent.com/40815708/72583028-14489e80-3928-11ea-9097-e984ca6bc1cc.png)

en-us:
![srs2-lifecycle-support_e](https://user-images.githubusercontent.com/40815708/72583083-478b2d80-3928-11ea-847e-71758f1eb679.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7ecd6ee6-8850-f346-5684-9c5d2444789f
* Version Independent ID: a55a7a01-211d-147a-5332-b68e1051a2a1
* Content: [バージョンのサポート - Microsoft Teams](https://docs.microsoft.com/ja-jp/MicrosoftTeams/room-systems/srs2-lifecycle-support)
* Content Source: [Teams/room-systems/srs2-lifecycle-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/srs2-lifecycle-support.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@OfficeGlobal Please check, English version is reading correctly.

**Comment by OfficeGlobal** [comment]
Working on a fix
Note: article redirected to https://docs.microsoft.com/cs-cz/MicrosoftTeams/rooms/rooms-lifecycle-support

**Comment by scanum** [comment]
@OfficeGlobal Any update on this? Thanks!

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum

Approved translation (by MS) for _Microsoft Teams Rooms_ is _Microsoft Teams ミーティング_
The article was HumanTranslated and published live

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by hyoshioka0128** [comment]
@OfficeGlobal, "Microsoft Teams ミーティング" needs to be replaced with "Microsoft Teams Rooms"
