### ISSUE TITLE
[LOC]"Microsoft Teams 室" needs to be replaced with "Microsoft Teams Rooms"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3800]
ja-jp:"https://docs.microsoft.com/ja-jp/MicrosoftTeams/room-systems/srs2-release-note"
![srs2-release-note_j](https://user-images.githubusercontent.com/40815708/72597878-0740a500-3952-11ea-9373-1f98a0651035.png)

en-us:
![srs2-release-note_e](https://user-images.githubusercontent.com/40815708/72598110-7b7b4880-3952-11ea-9ef1-6e1f9cb6b83a.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1365f9b8-001c-daa7-592e-d88b9bb3a10e
* Version Independent ID: ffba1b4d-1f19-4dac-0b55-053d98fe26b7
* Content: [リリース ノート - Microsoft Teams](https://docs.microsoft.com/ja-jp/MicrosoftTeams/room-systems/srs2-release-note)
* Content Source: [Teams/room-systems/srs2-release-note.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/srs2-release-note.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@OfficeGlobal Please check, English version is reading correctly.

**Comment by OfficeGlobal** [comment]
Working on a fix
Note: article redirected to https://docs.microsoft.com/ja-jp/MicrosoftTeams/rooms/rooms-release-note

**Comment by scanum** [comment]
@OfficeGlobal Any update on this? THanks!

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum

Approved translation (by MS) for _Microsoft Teams Rooms_ is _Microsoft Teams ミーティング_
The article was HumanTranslated and published live

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by hyoshioka0128** [comment]
@OfficeGlobal, Back-Translation "Microsoft Teams ミーティング"→"Microsoft Teams Rooms"

related:"https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4490"
