### ISSUE TITLE
[LOC]"Microsoft Teams のルーム" needs to be replaced with "Microsoft Teams Rooms"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3801]
ja-jp:"https://docs.microsoft.com/ja-jp/MicrosoftTeams/room-systems/srs-v2-prep"
![srs-v2-prep_j](https://user-images.githubusercontent.com/40815708/72598478-386da500-3953-11ea-8983-0af6dd169005.png)

en-us:
![srs-v2-prep_e](https://user-images.githubusercontent.com/40815708/72598484-3acfff00-3953-11ea-9a72-1e0f760c6952.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a711c07e-10b3-baf0-b92c-9dbcf6ab9474
* Version Independent ID: 2038cd48-44b1-1ed1-6e50-48290eef5605
* Content: [環境を準備する - Microsoft Teams](https://docs.microsoft.com/ja-jp/MicrosoftTeams/room-systems/srs-v2-prep)
* Content Source: [Teams/room-systems/srs-v2-prep.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/srs-v2-prep.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@OfficeGlobal Please check, English version is reading correctly.

**Comment by scanum** [comment]
@OfficeGlobal Can you please help with this? Thanks

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by scanum** [comment]
@OfficeGlobal Any update on this? Thanks!

**Comment by OfficeGlobal** [comment]
@scanum , @hyoshioka0128  correct and approved translation for Microsoft Teams Rooms is Microsoft Teams ミーティング. The article was updated and published live

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
