### ISSUE TITLE
Looking for Power shell commands to manage Org-Wide Holidays

### ISSUE THREAD

**Issue by cgskreddy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3804]
I could not find any Microsoft K.B. Article about power-shell commands to manage Org-Wide holidays in Teams admin center for Auto-Attendants. Appreciate to share if any

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9908d77-78bc-ce88-ba84-4f1bd9fea504
* Version Independent ID: 37118dd4-d036-8da7-d750-4c9f503a370a
* Content: [Set up holidays in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-holidays-in-teams#feedback)
* Content Source: [Teams/set-up-holidays-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-holidays-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@cgskreddy Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by DimitriBD** [comment]
@cgskreddy Same, as far as I can tell they are non-existent...

**Comment by get-itips** [comment]
Hello @cgskreddy 
How are you?
Can you kindly share your idea to [Microsoft Teams UserVoice](https://microsoftteams.uservoice.com/), Product Group is constantly watching this resource to evaluate the addition of new requested features.
Thank you

**Comment by get-itips** [comment]
@scanum please close this thread. thanks

**Comment by scanum** [comment]
@cgskreddy Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
