### ISSUE TITLE
SipTesterClient Script gives me an error

### ISSUE THREAD

**Issue by aacostab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3805]
I see this error when I try to runn the SipTesterClient.ps1 script:

**C:\Users\IDN CENTRAL\Downloads\TEAMS\SipTesterClient.ps1 : Parameter set cannot be resolved using the specified named 
parameters.
    + CategoryInfo          : InvalidArgument: (:) [SipTesterClient.ps1], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmbiguousParameterSet,SipTesterClient.ps1**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99036b5e-f358-fda3-d9b1-1279952b59a5
* Version Independent ID: 9ea42c59-7db5-9c66-ef58-98b4909ccd10
* Content: [PowerShell script to test Direct Routing Session Border Controller connections - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sip-tester-powershell-script#feedback)
* Content Source: [Teams/sip-tester-powershell-script.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sip-tester-powershell-script.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@aacostab Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@aacostab thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
