### ISSUE TITLE
SkypeRoomProvisioningScript.ps1 skripts fails on ExO using MFA'protected Global admin

### ISSUE THREAD

**Issue by nivdolgin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3806]
tried using the script for a cloud-only environment (with ADConnect/ADDS on prem) but couldn't get past the mailbox provisioning ("#########" reaplce real data below):

*************************************
Provision O365 Exchange Room Mailbox
*************************************
Is the Exchange Online admin account different than the Global Administrator account?
Enter 1 for Yes and 2 for No: 2
Waiting for Exchange Online Mailbox to be provisioned
........................................................................................................................Password    UserPrincipalName                 DisplayName           isLicensed
--------    -----------------                 -----------           ----------
######### PHX-ConferenceRoom@#########.com PHX - Conference Room False     
New-PSSession : [outlook.office365.com] Connecting to remote server outlook.office365.com failed with the following error message : Access is denied. For more information, see the about_Remote_Troubleshooting 
Help topic.
At C:\Users\nivdo\OneDrive - TestEquity LLC (2)\Scripts\SkypeRoomProvisioningScript.ps1:762 char:16
+ ...  $sessEXO = New-PSSession -ConfigurationName microsoft.exchange -Cred ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : AccessDenied,PSSessionOpenFailed
Failed to connect to Exchange Online. Please check your credentials and try again. Error message: Cannot validate argument on parameter 'Session'. The argument is null. Provide a valid value for the argument, a
nd then try running the command again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/with-office-365)
* Content Source: [Teams/room-systems/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/with-office-365.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@nivdolgin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@nivdolgin thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
