### ISSUE TITLE
The first sentence is very confusing

### ISSUE THREAD

**Issue by chtartMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3808]
The first sentence is very confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ddf1c3c-7fb9-ff3c-e8cd-af75999c78cb
* Version Independent ID: 6178c672-003f-8f99-f4ab-cf9b06cf5ede
* Content: [Contact the PSTN service desk - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk#feedback)
* Content Source: [Teams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@chtartMSFT Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by CarolynRowe** [comment]
Edited the wording.  Will publish today.  Closing this issue.
