### ISSUE TITLE
There is no Windows Server 2019 Domain Functional Level

### ISSUE THREAD

**Issue by maspange** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3809]
Hi,

The article mentions Windows Server 2019 Domain Functional level as compatible with Skype for Business Server 2019 but there is no such level available at present. The highest Domain and Forest functional level you can set in a Windows Server 2019 Active Directory environment is 2016.

Thank you

**Comment by scanum** [comment]
@maspange Could you please link the article you are referring to? Thanks!

**Comment by maspange** [comment]
Hi Manuala,

https://docs.microsoft.com/en-us/skypeforbusiness/plan/system-requirements

Section I'm referring to:

The domain functional level of any domain you deploy Skype for Business Server 2019 into, and the forest functional level of any forest you deploy Skype for Business Server 2019 into, must be one of the following:

Windows Server 2019

Windows Server 2016

Windows Server 2012 R2

Windows Server 2012

Thank you

**Comment by get-itips** [comment]
Hello @maspange Thanks for noticing, created a pull request to correct the article.

**Comment by maspange** [comment]
No worries Andres, thank you!

**Comment by get-itips** [comment]
@scanum please close this thread

**Comment by scanum** [comment]
@maspange Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
