### ISSUE TITLE
NHS Action on FHIR compliance

### ISSUE THREAD

**Issue by uberseehandel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3810]
Is there any information about NHS Hospitals' involvement in this project? I continuously run into problems with information being stored in local silos, even when there are partnerships in place.

For example, it isn't very helpful to be able to access a scan image, without the accompanying report.

To quote an expert on these matters, "I'm undead, I'm not unreasonable".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f591551-f29c-9255-9846-42557b0b8484
* Version Independent ID: 3f1634eb-ed4d-e146-cf72-2fa01587682f
* Content: [Patients app overview - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/expand-teams-across-your-org/healthcare/patients-app#feedback)
* Content Source: [Teams/expand-teams-across-your-org/healthcare/patients-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/expand-teams-across-your-org/healthcare/patients-app.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@uberseehandel Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @jambirk James, can you shed some light here? Thanks

**Comment by uberseehandel** [comment]
@get-itips Unless there are multiple James Birkinshaws in the Seattle region, I think he started at Oracle in January, so may not be directly involved for the present. I'd like to know which MS person to talk to in the UK, as I know there is a lot of interest in this project from within No 10. Whether the appropriate MS person is in Cambridge(MS Research Lab / Healthcare Intelligence), London or Leeds (NHS HQ). The UK is a good place to drive this forward - political interest and NHS is the biggest developed healthcare system in the world (1.5 Million staff).

**Comment by get-itips** [comment]
Hello @scanum can you help finding the right person to ask here? Thanks

**Comment by scanum** [comment]
@rjagiewich Could you please help with this issue in finding the right person to direct this to? Thanks!

**Comment by scanum** [comment]
@rjagiewich Could you please help with this issue in finding the right person to direct this to? Thanks!

**Comment by dstrome** [comment]
hi @uberseehandel - Please have the NHS or UK government reach out to their respective Microsoft technical account managers to discuss these questions. We cannot discuss customer involvement of any nature on public forums. 

thanks.
