### ISSUE TITLE
Step 3 Not Correct

### ISSUE THREAD

**Issue by Jason-ACESGroup** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3811]
Step 3 #1 States: In the Microsoft 365 admin center, go to Settings &gt; Services & add-ins; 
There is no longer a Services & add-ins link at this location.  Can't find where to go for this step now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams guest access checklist - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/guest-access-checklist#feedback)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Jason-ACESGroup Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Jason-ACESGroup 
Document has already been updated :) https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/bae9ca1e471638df851982b87059c1f539d4868e
Thank you!

**Comment by get-itips** [comment]
@scanum please close this thread.

**Comment by scanum** [comment]
@Jason-ACESGroup Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
