### ISSUE TITLE
Step 4 Not Correct

### ISSUE THREAD

**Issue by Jason-ACESGroup** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3812]
There is no more Security and Compliance link in the Office 365 admin section. The initial treasure hunt for this in the new Security and Compliance section came up empty.  Please update this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams guest access checklist - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/guest-access-checklist#feedback)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Jason-ACESGroup Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by nikmanzotti** [comment]
@scanum to help your investigation, I suggested the same for a different doc (see [here](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/issues/686)), and now the proper steps are aligned with the new navigation (see [here](https://docs.microsoft.com/en-us/office365/enterprise/microsoft-365-guest-settings#microsoft-365)).

**Comment by dariomws** [comment]
@Jason-ACESGroup, thank you for your feedback.

The article was updated the last 2 months and there is no reference to the Security and Compliance Admin Center, so looks that the issue was fixed. I have verified the instructions under Step 4 and they look good.

**Comment by ChrisB-CS** [comment]
I couldn't find the Settings anywhere on my M365 Admin home page.  Finally, after about 20 minutes of searching, I clicked on my Tenant name towards the top of the page to the left of the page's search bar and then the settings appeared.  Step #4 just needs to be updated to show this is how to access the Settings to get to the Security & Privacy tab where Sharing is located.

**Comment by dariomws** [comment]
@ChrisB-CS I verified once more and it's there:
![image](https://user-images.githubusercontent.com/33589238/76416848-9e3a4400-637a-11ea-87ca-d73b1b055e27.png)

**Comment by ChrisB-CS** [comment]
@dariomws  - I am a Global Admin and my menu is missing the Settings as shown in your menu.  The Settings option is supposed to be between the Support and Setup on the menu, but it is missing in mine.  To get to it, I have to click on the company name (e.g. Contoso) just below where it says "Microsoft 365 admin center".  That's what I was saying.  I think this is the issue that others are having as well.

![image](https://user-images.githubusercontent.com/47863344/76432918-ff1d4880-6389-11ea-82f3-6e5316803376.png)

**Comment by dariomws** [comment]
I have verified in another tenant and it's there. It should be there at least in Enterprise and Business tenants.

Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ChrisB-CS** [comment]
@dariomws I will try to open a ticket on this.  We are a Microsoft 365 E5 setup.  Not sure why it is missing in the menu.  Like I said, I can get to it, but you have to click on our Tenant name to open the settings.

**Comment by scanum** [comment]
@Jason-ACESGroup Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
