### ISSUE TITLE
Missing latest release

### ISSUE THREAD

**Issue by yankeedoodlegandy83** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3813]
Missing 4.3.33.0 which has been pushed out to all clients now

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1365f9b8-001c-daa7-592e-d88b9bb3a10e
* Version Independent ID: ffba1b4d-1f19-4dac-0b55-053d98fe26b7
* Content: [Release notes - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/room-systems/srs2-release-note#feedback)
* Content Source: [Teams/room-systems/srs2-release-note.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/srs2-release-note.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@yankeedoodlegandy83 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @yankeedoodlegandy83 
Thanks for noticing, document has already been updated, see https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/52e6d98cab137cd9588705d236afccd7f4fee0d0

**Comment by get-itips** [comment]
@scanum please close this thread

**Comment by scanum** [comment]
@yankeedoodlegandy83 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
