### ISSUE TITLE
Read receipts features in Teams Client?

### ISSUE THREAD

**Issue by EvgenyArtemyev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3815]
Does the status of reading is available in MS Teams Client?
We see it on admin site only.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34f3188-0af5-f972-9d28-959f5f7866a2
* Version Independent ID: fab26e11-a729-92a4-3ea6-8668dca55dd0
* Content: [Manage messaging policies in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/messaging-policies-in-teams#feedback)
* Content Source: [Teams/messaging-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/messaging-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@EvgenyArtemyev thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
