### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by hubbardw** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3816]
This documentation seems to be outdated. When you go to the Teams Admin Center (at least under a Microsoft 365 license), the Users tab does not provide an "Edit" option. There is an Edit Settings button but that seems to take you to a different location than what's expressed above. Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dc173c-0c98-1b94-a2f7-0a34781c985a
* Version Independent ID: a1c44ccb-67f3-f98e-6569-f938e88ddc63
* Content: [Set the phone numbers included on invites in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-the-phone-numbers-included-on-invites-in-teams#feedback)
* Content Source: [Teams/set-the-phone-numbers-included-on-invites-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-the-phone-numbers-included-on-invites-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@hubbardw  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @hubbardw 
Thanks for noticing, created a pull request to update the article.

**Comment by get-itips** [comment]
@scanum please close this thread, PR was merged.

**Comment by scanum** [comment]
@hubbardw Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
