### ISSUE TITLE
No support for other issues with numbers

### ISSUE THREAD

**Issue by AnnaValo2020** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3817]
There is no possibility to log a ticket/ask for help for any issue with numbers. My company has an issue with assignment of toll-free number on the resource. We see "We can't get any phone numbers right now. Please try again. If you continue to have problems, contact Microsoft support." It redirects on this page and the only info I see is "If you need help with getting or transferring numbers..". So, no visibility on how we can receive a help here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ddf1c3c-7fb9-ff3c-e8cd-af75999c78cb
* Version Independent ID: 6178c672-003f-8f99-f4ab-cf9b06cf5ede
* Content: [Contact the PSTN service desk - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@AnnaValo2020 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
