### ISSUE TITLE
Confusing Statement in Step 2

### ISSUE THREAD

**Issue by Christian-e-S** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3818]
In step 2, there is a note: "For guest access to work at all in Teams, you must set Members can invite to Yes."

Does this mean, that guest access in Teams would not even work if admins are adding the guest to the group? 
If this is really the case, then I could never have (i) guest access in teams, and a (ii) strictly controlled management (i.e., exclusively by the admin) of the AD at the ssame time.

Is my understanding correct? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams guest access checklist - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Christian-e-S  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Christian-e-S 
How are you?
Document has been updated after you added your inquiry, please see 
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/9c5009b241a37498e1f033913cff12a4ae57fdd0

**Comment by get-itips** [comment]
@scanum please close this thread

**Comment by scanum** [comment]
@Christian-e-S Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
