### ISSUE TITLE
Emergency Calling via Direct Routing

### ISSUE THREAD

**Issue by Sezotove** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3819]
This entire section needs a revision and further steps on how to properly set this up. The article is lacking links to commands mentioned and any kind of viable setup notes. I've attempted and am now a month into support trying to resolve this as well. They too have been confused by this and admit there is a lack of useful information on this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634810fc-7a47-f794-7803-9f3941d664dd
* Version Independent ID: 52587955-5054-a003-6d03-948ce02838dd
* Content: [Plan emergency calling, emergency addresses, emergency call routing, dynamic emergency calling - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/what-are-emergency-locations-addresses-and-call-routing#feedback)
* Content Source: [Teams/what-are-emergency-locations-addresses-and-call-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-emergency-locations-addresses-and-call-routing.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Sezotove  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Sezotove, thank you for your feedback.

This article was updated the last two months and it will be improved continuously. Also, there is a link in the article to the cmdlets reference:
[Manage emergency call routing policies](https://docs.microsoft.com/microsoftteams/manage-emergency-call-routing-policies)

**Comment by scanum** [comment]
@Sezotove Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
