### ISSUE TITLE
Is WINSAT-tool available on windows 10?

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#382]
Is WINSAT-tool available on windows 10? Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6629ab7-4007-d19b-170f-c217715bcc68
* Version Independent ID: a15660da-5c85-bc15-8ce9-eda52e17757e
* Content: [Skype for Business client video resolutions](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/video-resolutions)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/video-resolutions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/video-resolutions.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Yes, it's available. https://docs.microsoft.com/en-us/windows/desktop/winsat/windows-system-assessment-tool-portal
