### ISSUE TITLE
Deleted Message Inconsistent Across Devices / Software

### ISSUE THREAD

**Issue by marcolsh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3822]
We tested across several devices and software for deleted message.

If user having a laptop always logged in with Apps-Microsoft Team, their message won't be deleted even the messages found deleted in MobileApps-Teams / Web Based Teams.

It just like keeping a local copy won't be deleted / sync deleted until user physically Logout / Re-Login.

It caused potential risk that user keep referencing those message in their laptop.
Is there any chance the Microsoft could provide an update that Force Mobile-App-Teams and Software App-Teams always keep SYNC with server and clean up local cached / message history?

Thank you.

**Comment by scanum** [comment]
@marcolsh thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
