### ISSUE TITLE
No documentation on in-room controls for MTR.

### ISSUE THREAD

**Issue by jamesbayliss** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3826]
It'd be cool if you documented on how we go about adding or developing in-room controls on a MTR system. We'd like to add features for controlling lighting, HVAC, etc. I really hope that is available and open rather than being locked down to vendor's hardware. Where can I find it if it exists?

**Comment by scanum** [comment]
@MOctopuso Hi, thanks for your feedback. Could you please link the document you are referring to? Thanks.

**Comment by MOctopuso** [comment]
@scanum - We have seen images and documentation, such as this [blog post](https://techcommunity.microsoft.com/t5/microsoft-teams-blog/microsoft-teams-rooms-december-update/ba-p/1069456) - Where you mention, **_Get to Room Controls / OEM extension with ease_** - But we cannot find any documentation on how we add our own room controls? We'd love to develop our own room controls, but cannot find any documentation on how to do so :(

**Comment by get-itips** [comment]
Hello @LanaChin can you help us here to understand if there will be such a documentation ?

**Comment by get-itips** [comment]
Hello @LanaChin Lana 👍 can you help us here ? Thanks

**Comment by LanaChin** [comment]
Looking into this, thanks.

**Comment by LanaChin** [comment]
Hi @jamesbayliss. The extensions are only available through OEMs.  If you'd like this feature, you can submit a feature request on User Voice at https://microsoftteams.uservoice.com/forums/555103-public?category_id=324151.
