### ISSUE TITLE
User for activating Domain

### ISSUE THREAD

**Issue by thomas414** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3829]
After the release of the phonesystem - virtual user licenses, is it still needed to license the activation users with E1 / E3 / E5 or can they be licensed with the new licenses, both for the carrier domain and the customer domain?

I tried it with one of our customer domains a few weeks ago and it is still working, so i assume it works for customer domain, maybe the documentation should be updated accordingly, if it is officially supported by microsoft, but what about the carrier domain?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure a Session Border Controller for multiple tenants - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants#feedback)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@thomas414 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by thomas414** [comment]
@scanum thank you for the suggestion.
Answer from the ms support team is following: "based on the documentation the virtual phone system license is only to be used for a resource account for auto attendants and call queues. Please review the documentation https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/virtual-user . Also cannot be assigned to a user because would not replace the paid license"
So i guess it doesn't work (yet)
