### ISSUE TITLE
Need help to understand failures.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#383]
No diagnostic errors to help me understand failures.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c507e4c8-cba0-8e39-17ad-80a09aea95e2
* Version Independent ID: d45d7e7c-63de-9c16-ea7a-1694346fa76f
* Content: [Call Diagnostic Summary Report in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/manage/health-and-monitoring/summary-report)
* Content Source: [Skype/SfbServer/manage/health-and-monitoring/summary-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/health-and-monitoring/summary-report.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by yogkumgit** [comment]
As this is an internal transfer so can be closed
