### ISSUE TITLE
When we get more logs available?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3830]
Hi,
What are the current plans to get the following limitation:

> To see this information for a user in the Microsoft Teams admin center, click the Call History tab for that user in the user detail page to see all calls and meetings for that user **in the last 30 days**.

To get higher than 30 days?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dedf646c-c5dc-5645-54a2-1bca0d406f45
* Version Independent ID: 9a52f0b1-2970-559e-2d18-8e565662ca26
* Content: [Call Analytics and Call Quality Dashboard - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/difference-between-call-analytics-and-call-quality-dashboard)
* Content Source: [Teams/difference-between-call-analytics-and-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/difference-between-call-analytics-and-call-quality-dashboard.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Petri-X thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
