### ISSUE TITLE
Wrong Version / links

### ISSUE THREAD

**Issue by bf80** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3831]
On the webpage for VDI the downloadlink for the MSI is:
https://statics.teams.cdn.office.net/production-windows-x64/1.2.00.32462/Teams_windows_x64.msi
(Version 1.2.00.32462)
Bute while searching for Version numbers and release Notes I found this:
https://statics.teams.cdn.office.net/production-windows-x64/1.3.00.362/Teams_windows_x64.msi
(Version 1.3.00.362)

On the Teams Webpage it is this link for the *.exe :
https://go.microsoft.com/fwlink/p/?linkid=869426&lm=deeplink&lmsrc=groupchatmarketingpageweb&cmpid=directdownloadwin64
(Version 1.2.00.34161, will online Update to 1.3.0.362 after install)

So could you please consider updating this links everytime a new version gets released.
As there are no Releasenotes with Versionnumbers it is a mess to get the latest release for VDI.

**Comment by scanum** [comment]
@bf80 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@bf80 Hi there. Thank you for reaching out to improve MS Docs. Could you please point out which article you're referring to, as there is no article in the body?

**Comment by bf80** [comment]
@Reeced40 The article was https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi#install-or-update-the-teams-desktop-app-on-vdi, but the links at "Deploy the Teams desktop app to the VM" has been changed and now pointing to https://statics.teams.cdn.office.net/production-windows-x64/1.3.00.4461/Teams_windows_x64.msi

**Comment by scanum** [comment]
@Reeced40

**Comment by Reeced40** [comment]
@bf80 Thanks for reaching out. It looks like the link was fixed in the interim. Could you please confirm it on your side? Thanks.

**Comment by scanum** [comment]
@bf80 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
