### ISSUE TITLE
hello everyone 

### ISSUE THREAD

**Issue by julie174** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3832]
just wanted to let you all know that i have a lot of fun working here with you guys keep up the good work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a795a46e-52eb-c338-8bd2-fd0133cfcfd0
* Version Independent ID: 1d64ea4b-376b-4845-c5e0-ce90f8ed6089
* Content: [Welcome to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-overview#teams-content-updates)
* Content Source: [Teams/Teams-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@julie174 Hi Julie, thanks for the message!

**Comment by tecdisol** [comment]
@julie174 we really have fun too.
