### ISSUE TITLE
Software Updates section

### ISSUE THREAD

**Issue by grahammw** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3834]
The PowerShell command under https://docs.microsoft.com/en-us/microsoftteams/room-systems/room-systems-v2-operations#software-updates does not work.  Please can it be corrected

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd52fe62-457b-c9e1-ad13-a9b1f24c9c38
* Version Independent ID: 6a8c3285-30e1-15a8-6472-f0cfe5b30e20
* Content: [Microsoft Teams Rooms maintenance and operations - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/room-systems/room-systems-v2-operations#feedback)
* Content Source: [Teams/room-systems/room-systems-v2-operations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/room-systems/room-systems-v2-operations.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@grahammw Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @grahammw Graham, how are you?
What is the error message -if any- you are receiving when running the Ps command?
Thanks

**Comment by get-itips** [comment]
Hello @grahammw 👍 how are you? hope you are doing good.
I wonder if you could see my last message, where I ask, if you can kindly share the error message received, thanks

**Comment by scanum** [comment]
@grahammw We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by grahammw** [comment]
Here is the correct PS command to update the software.  Just need to remove the -Update from the script.  Correct script is

Add-AppxPackage -ForceApplicationShutdown -Path '\\<share>\$oem$\$1\Rigel\x64\Ship\AppPackages\*\*.appx' -DependencyPath (Get-ChildItem '\\<share>\$oem$\$1\Rigel\x64\Ship\AppPackages\*\Dependencies\x64\*.appx' | Foreach-Object {$_.FullName})

**Comment by get-itips** [comment]
> Here is the correct PS command to update the software. Just need to remove the -Update from the script. Correct script is
> 
> Add-AppxPackage -ForceApplicationShutdown -Path '\$oem$$1\Rigel\x64\Ship\AppPackages**.appx' -DependencyPath (Get-ChildItem '\$oem$$1\Rigel\x64\Ship\AppPackages*\Dependencies\x64*.appx' | Foreach-Object {$_.FullName})

Thanks for this feedback @grahammw 
@LanaChin Lana, can you please confirm so I can impact the article? Sadly I do not have a Teams Rooms System to test this myself. I appreciate.

**Comment by grahammw** [comment]
For some reason, it dropped out the <share>

Add-AppxPackage -ForceApplicationShutdown -Path '\\<share>\$oem$\$1\Rigel\x64\Ship\AppPackages\*\*.appx' -DependencyPath (Get-ChildItem '\\<share>\$oem$\$1\Rigel\x64\Ship\AppPackages\*\Dependencies\x64\*.appx' | Foreach-Object {$_.FullName})
