### ISSUE TITLE
Opt out Section

### ISSUE THREAD

**Issue by Chad-Campus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3837]
Says to go into your Skype Desktop Business Client, click Options - Call Forwarding.

There is no Edit Settings Online.  We have an On Prem-Server in Hybrid Mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b755d9ae-13ac-019f-f5f4-a95b1eee2989
* Version Independent ID: f7afd8ad-e6e0-6c79-aed1-4ee87d48ba12
* Content: [Create a call queue - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue#feedback)
* Content Source: [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-call-queue.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by Chad-Campus** [comment]
![optout](https://user-images.githubusercontent.com/52751067/72926106-d8477c00-3d21-11ea-9c50-9d41a445d1e4.PNG)

**Comment by scanum** [comment]
@Chad-Campus thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
