### ISSUE TITLE
Microsoft 365 E5

### ISSUE THREAD

**Issue by robhardman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3839]
Microsoft 365 E5 is missing from the subscription list on this page. If a tenant has 300 or fewer people, but at least one is licensed for Microsoft 365 E5, is that tenant excluded from the product?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35057f71-792b-a4e2-a2ee-a4908c11f3a4
* Version Independent ID: 7e23f067-1dcd-16f0-3f9a-ff8d13c1f659
* Content: [What is Microsoft 365 Business Voice? - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/business-voice/whats-business-voice#feedback)
* Content Source: [Teams/business-voice/whats-business-voice.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/business-voice/whats-business-voice.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@robhardman Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dstrome** [comment]
hi @robhardman - E5 licenses already include Phone System and Audio Conferencing so there's no need to buy additional Business Voice licenses for users with that license. That doesn't, however, prevent you from adding E3 licenses, for example, and adding Business Voice licenses to those users.
