### ISSUE TITLE
Need help on SfB subscription version.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#384]
Doesn't explain how to do it for Skype for Business Subscription version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66ad8b3a-aac0-7eba-29e3-2d621fa46a54
* Version Independent ID: bba6f915-d50e-08c2-cd54-a56d2c25198e
* Content: [Configure the use of high-resolution photos in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/integrate-with-exchange-server/high-resolution-photos)
* Content Source: [Skype/SfbServer/deploy/integrate-with-exchange-server/high-resolution-photos.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/integrate-with-exchange-server/high-resolution-photos.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi, this article scope (and also section) is about integration of SFB On-Premises to Exchange On-Premises so it won't include SFB Office 365 Subscription-based information.
Thanks
