### ISSUE TITLE
Change of URLs to the MTR section

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3840]
Hi! Looks like overnight url to the MTR section of docs has changed from /microsoftteams/room-systems/ to /microsoftteams/rooms/ leading to broken URLs. Is it possible to deploy redirections to the old urls so we would have some time to get all the indexers to notice the new URL?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15006a6a-d58e-5c43-7b57-2ec925990883
* Version Independent ID: 19c6e539-15e7-e2b1-ed92-19ed1b1af48d
* Content: [Manage a Microsoft Teams Rooms console settings remotely with an XML configuration file - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/xml-config-file#Themes)
* Content Source: [Teams/rooms/xml-config-file.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/xml-config-file.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dstrome** [comment]
hi @Larryngolog - We performed a large number of file renames in addition to the URL change from /room-systems/ to /rooms/. Links to original file names should automatically redirect to the new /rooms/ URL with new file names. Please let us know if you are still receiving errors when trying to get to the old URL with old file names.

**Comment by Larryngolog** [comment]
Hello. This link https://docs.microsoft.com/en-us/microsoftteams/room-systems/xml-config-file does not redirect to https://docs.microsoft.com/en-us/microsoftteams/rooms/xml-config-file

**Comment by dstrome** [comment]
Are you saying you have a bookmark that points to https://docs.microsoft.com/en-us/microsoftteams/room-systems/xml-config-file? The original file name was https://docs.microsoft.com/en-us/microsoftteams/room-systems/with-xml-config-file

**Comment by Larryngolog** [comment]
Yes, I had sent a partner an e-mail with that link on Jan 22nd when it was working and on Jan 23rd it was not working anymore.

You can see that it existed - it's in on the Web Archive  sitehttps://web.archive.org/web/20191218114150/https://docs.microsoft.com/en-us/microsoftteams/room-systems/xml-config-file

**Comment by dstrome** [comment]
ok thanks. We'll get a redirect put in place for that file. thanks for the feedback!
