### ISSUE TITLE
Include Business Voice in the content.

### ISSUE THREAD

**Issue by dgordonb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3841]
my MS email address is dobro@microsoft.com.   MS has recently released the Microsoft Business Voice product which has all the functionality of the enterprise phone system bundled together for the SMB customers and applicable to the "B" O365 SKUs.  .   
Please update the documentation to include details on Business Voice to help reduce customer confusion. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afdd6102-e72f-63bb-77fc-8cfd4373e8db
* Version Independent ID: 4f073d07-8c3a-9ca9-7f16-5892953543dc
* Content: [Small business example — Set up an Auto Attendant - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/tutorial-org-aa?tutorial-step=4#feedback)
* Content Source: [Teams/tutorial-org-aa.yml](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/blob/live/Teams/tutorial-org-aa.yml)
* Service: **msteams**
* GitHub Login: @SharS
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@dgordonb Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dstrome** [comment]
Hi @dgordonb - we do have BV content available on Docs. You can access it here - http://docs.microsoft.com/en-us/microsoftteams/business-voice.

Please feel free to ping me (email alias is the same as my GH account) if you want to discuss further.
