### ISSUE TITLE
Has the Outlook Presence been fixed yet when in Teams Only mode and no Skype installed?

### ISSUE THREAD

**Issue by daurkin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3842]
I want to roll out Teams Only mode and I'm getting push back because it breaks the Outlook Presence Icon when Skype is uninstalled.  Is this fixed or still outstanding?  Is it still an issue if I upgrade the Tenant Wide setting to Teams Only?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a162ef5c-3099-7f58-4178-d29e3ec2b5a7
* Version Independent ID: 6ca31e56-052d-6c62-1323-b5aaaae1f04a
* Content: [User presence in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/presence-admins#feedback)
* Content Source: [Teams/presence-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/presence-admins.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by scanum** [comment]
@daurkin thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
