### ISSUE TITLE
Serial routing not working as described in the docs

### ISSUE THREAD

**Issue by AlexanderSaad** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3847]
Hi,
In the docs it's written that:
"Serial routing will skip agents who are Offline, have set their presence to Do not Disturb, or have opted out of getting calls from this queue."
**NB! This is not correct. Agents that are Offline or Do Not Disturbe are not skipped and the caller does have to wait a specific number of seconds (30 by default) until the call is transferred to the next agent.**
This means that currently  If a user is Offline or Do Not Disturb, calls will route to the user, but won't be able to reach the user. In case of Serial or Round Robin routing, the next agent in the call will be **rung after attempting to reach an unavailable user fails to connect**. This can cause slightly longer ring times. Setting Agent Alert time to smallest value of 15 seconds will reduce time interval between calls to the next agent in line.
Please correct the information as many customers have wrong expectations set and these are reported as product quality issues

**Comment by scanum** [comment]
@AlexanderSaad Hi! Thanks for the feedback, could you please link the documentation you are reffering to? Thanks!

**Comment by AlexanderSaad** [comment]
Hi @scanum, the document is the following:
https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue
There is a pull request also open about the same issue:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/3846#issue-366761193
Thank you for having a look at it, as there are multiple Microsoft customers complaining about the issue.

**Comment by sowjanya365** [comment]
Hi @AlexanderSaad 

Thank you for reaching out! 

I see that the PR(#3846) status as merged now. Hope this helps. Thank you!

**Comment by scanum** [comment]
@AlexanderSaad Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
