### ISSUE TITLE
Need link of software mentioned.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#385]
Can the link of software mentioned in the article attached with this document? Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7cb8ab6-b365-b15e-41e0-851761d2c565
* Version Independent ID: 53583afd-6e55-da91-73c6-72ae4e1dacc4
* Content: [Install the Planning Tool in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/planning-tool/install)
* Content Source: [Skype/SfbServer/management-tools/planning-tool/install.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/management-tools/planning-tool/install.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi, Link for the planning tool is one level up in the document called "Planning tool" https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/planning-tool/planning-tool
