### ISSUE TITLE
and what about the SSAE 18? Does this post need to be updated?

### ISSUE THREAD

**Issue by nicolasmounition** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3851]
The SSAE 16 seems to be replaced by the SSAE 18 for any report published after may the 1rst of  2017...
Is Microsoft late on this?
Moreover I would like to know wich protocols are used for the videoconference (Teams or SKype)? SIP? H323? which videos and audios codecs are used within?

Thanks.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: ca579d63-182b-d6f5-8777-79248fa27ed9
* Version Independent ID: b4c27d1b-b2f1-41ac-b15c-d12b448a539e
* Content: [Présentation de la sécurité et de la conformité dans Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/fr-fr/microsoftteams/security-compliance-overview#feedback)
* Content Source: [Teams/security-compliance-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/security-compliance-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@nicolasmounition Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @nicolasmounition How are you ? Hope you are doing good.

About information about protocols and call flow please see https://docs.microsoft.com/en-us/microsoftteams/microsoft-teams-online-call-flows

@LolaJacobsen Can we confirm Microsoft is working on getting SSAE 18? Thank you

**Comment by get-itips** [comment]
@LolaJacobsen Lola, can you please step in? :) thanks

**Comment by scanum** [comment]
@MicrosoftHeidi Any updates on this? Thanks!

**Comment by MicrosoftHeidi** [comment]
No update at this time.

**Comment by scanum** [comment]
@MicrosoftHeidi Hi! any updates on the issue? Thanks!

**Comment by scanum** [comment]
@MicrosoftHeidi Hi! any updates on the issue? Thanks!

**Comment by MicrosoftHeidi** [comment]
I still need to make time to research this, I don't have the answer at hand right now.

**Comment by scanum** [comment]
@MicrosoftHeidi Hi! Wondering if there is an update on this issue? Thanks.

**Comment by MicrosoftHeidi** [comment]
I have no update yet, I'm checking with a resource on this now.

**Comment by MicrosoftHeidi** [comment]
Yes, this should be changed to SSAE 18.

**Comment by scanum** [comment]
@get-itips

**Comment by MicrosoftHeidi** [comment]
I've approved 5750.
