### ISSUE TITLE
Invalid folder names

### ISSUE THREAD

**Issue by viperscape** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3852]
The documentation mentions channel name requirements but the same requirements should be stated for folder names. It's currently possible to sync a folder with OneDrive to SharePoint that includes an invalid character, Teams app cannot handle such folder names and files inside will be inaccessible.

**Comment by GiantCrocodile** [comment]
Hi @viperscape! Can you provide a link to the docs you are talking to improve about? I'm curious about this as I wasn't aware of this issue. Thank you!

**Comment by scanum** [comment]
@viperscape Thank you for submitting feedback and contributing to the docs. We will investigate this once you provide the documentation. Thanks!

**Comment by get-itips** [comment]
Hello @viperscape as @GiantCrocodile said here, can you please link to the article you are talking about? I do not want to assume, thank you! 👍

**Comment by viperscape** [comment]
Maybe it was fixed in a recent Teams update? Previously I could not do this but it looks resolved! Sorry for any confusion :-D
![Creating folder in Teams limits](https://user-images.githubusercontent.com/3178836/74044500-281c7900-4999-11ea-816f-b56f1fcb8f70.png)
