### ISSUE TITLE
Misleading

### ISSUE THREAD

**Issue by tpmeredith** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3853]
It is highly misleading to say this:

Will you support third-party development opportunities in Teams?
Yes, app integration is one of the key benefits of adopting Teams. We currently support third-party bots, connectors, and extensions in Teams. In addition, we have a large ecosystem of add-ins available in the Microsoft Teams app store.

Years later there are still major functionality gaps with teams calling API and teams still has not even come close to integration parity of SfB and lync. Not even close.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbeb59c4-349f-944c-5183-4fb26a34c22b
* Version Independent ID: 2beb18af-35a6-de0a-d90f-89c94533b8da
* Content: [FAQ — Upgrading from Skype for Business to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/faq-journey)
* Content Source: [Teams/FAQ-journey.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/FAQ-journey.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@tpmeredith Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tpmeredith** [comment]
> @tpmeredith Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

Thanks, there really should be a disclaimer for companies using voice so they don't fall into the same trap we have fallen into. We jumped on teams only 1-2 years ago since virtually no documents at microsoft care to mention there is not a working voice API (even the one release to GA still has major gaps in functionality making a simple CTI call popup integration almost impossible). There are hundreds of these plugins for SfB/Lync however.

**Comment by get-itips** [comment]
Hello @tpmeredith how are you? Hope you are doing good. 👍 
Here, we can only limit to documentation improvements or corrections, I understand that you see positive to add some notes regarding the current state of the voice API.
 @LanaChin could you please step in to help us understand if you agree and how we could update this article to improve it? I appreciate.

**Comment by tpmeredith** [comment]
> Hello @tpmeredith how are you? Hope you are doing good. 👍
> Here, we can only limit to documentation improvements or corrections, I understand that you see positive to add some notes regarding the current state of the voice API.
> @LanaChin could you please step in to help us understand if you agree and how we could update this article to improve it? I appreciate.

I'm doing well thanks. I understand it's not exactly thrilling for MS to detail real world limitations in an article that is supposed to cite all the advantages to switching... I just think Microsoft really should have some page, somewhere, that details Microsoft Teams shortcomings with voice compared to SfB/Lync. Like many orgs we literally fell into a microsoft "Trap" by adopting teams over a year ago (and assumed we would actually be able to integrate with voice apps based on articles like this), since then have effectively been blackboxed out of integrating with any other voice service. We just now are painfully able to integrate only by paying a fortune and adopting direct dialing and using a vendors SfB server as a roundabout way to actually have a somewhat working calling solution directly in Teams.

I would say just release a functional API, but partners have been told it is coming for years now and still have no way to integrate with teams voice with anywhere close to the same functionality as SfB/Lync. Unfortunately if MS had just simply supported lync/SfB plugins with Teams until a functional API existed this would be avoided.

**Comment by get-itips** [comment]
Hello @LanaChin Lana, can you help us here? thanks

**Comment by LanaChin** [comment]
Hi @tpmeredith - Thanks for taking the time to comment here to share your concerns about voice integration and suggestions for improving our documentation based on your adoption experiences. Your feedback is important to us. Want to let you know that we've forwarded your comments, concerns, and suggestions over to the product team.

**Comment by tpmeredith** [comment]
@LanaChin  ok thanks.. may also want to let the product team know they're losing teams customers over this. We were on teams for 2+ years and got tired of waiting for a functional API so we have already begun moving our users away from teams calling.
