### ISSUE TITLE
Prepare the installation media out of date?

### ISSUE THREAD

**Issue by richeklund** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3854]
The "Prepare the installation media" section is out of date as our new Logitech Tap device is not listed in the CreateSRSMedia.ps1 script when ran. No one can seem to tell me how to "image" this device in the event we can no longer boot into Windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/console)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@richeklund Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @richeklund 

Thank you for reaching out! 

I would suggest you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content. Thank you!

**Comment by richeklund** [comment]
Hello, I did reach out to support for the Logitech Tap and was told it is currently not supported by the script. So if one of these systems require re-imaging there is no proper fix. Logitech provided a workaround, but the end result is not identical to the OEM image and they won’t support the issues with their workaround.

**Comment by scanum** [comment]
@richeklund thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
