### ISSUE TITLE
Where to find "Microsoft Teams admin center"?

### ISSUE THREAD

**Issue by agibsen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3855]
/eom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce30163-6327-899b-281d-d4ef982fce5e
* Version Independent ID: e61dcbb8-4877-ef6f-1987-981cdd7fc82f
* Content: [Configure desktop sharing in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/configure-desktop-sharing#feedback)
* Content Source: [Teams/configure-desktop-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/configure-desktop-sharing.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **Lolaj**

**Comment by GiantCrocodile** [comment]
I did create a pull request to improve the docs regarding your suggestion of adding a link to the Microsoft Teams admin center.

You can find the Microsoft Teams admin center here: https://admin.teams.microsoft.com/
