### ISSUE TITLE
Conditional Access issue

### ISSUE THREAD

**Issue by Jerx88** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3856]
Regarding the issue: "Conditional Access may not work when using the "Website" tab in the desktop app". Are there any plans in getting this fixed? I was wondering if the new Edge client could be used as the "browser" in Teams? Since this seems to support Conditional Access out of the box without the use of plugin (like Chrome does require).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Jerx88 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by blyakhmanv** [comment]
Any updates regarding the fix?

**Comment by toddjohnson39** [comment]
Please provide an update

**Comment by blyakhmanv** [comment]
Please provide an update on this issue.Because of this issue we can't use apps in the Teams desktop which is very disappointing and prevent us to extensively use Teams.

**Comment by Jerx88** [comment]
This issue is going to be a struggle for us, we don't want to use "Location" based CA policies. Is there a way for us to assist in this issue?

**Comment by blyakhmanv** [comment]
Looks like MS is not going to provide an answer ((((

**Comment by dariomws** [comment]
Hi @Jerx88, thank you for your feedback.

@LolaJacobsen could you kindly help with this to provide more information? Thanks!

**Comment by blyakhmanv** [comment]
@dariomws  Could you please provide an update?

**Comment by blyakhmanv** [comment]
@dariomws @scanum  Could you please provide an update?

**Comment by SC-N** [comment]
This is incredibly critical for my organization as well.  It didn't come up during our testing of Conditional Access policies, but now that we've implemented it we have a number of teams that are unable to cleanly use an application in a web tab.  It's a horrible user experience.  Not to mention the workaround described is absurd. @scanum @dariomws

**Comment by dariomws** [comment]
@LolaJacobsen could you kindly help with this to provide more information? Thanks!

**Comment by SC-N** [comment]
Got this back from my premier incident.  Hopefully that means there will be a solution by May.

"Please be advised that while there is no available work around at this point in time, there is a fix in the works that should be deployed over the course of the next few weeks or month. "

**Comment by LolaJacobsen** [comment]
@marclauinger can you review this issue and let me know what documentation updates might be needed?

**Comment by scanum** [comment]
@marclauinger Any updates on this issue? Thanks.

**Comment by LolaJacobsen** [comment]
A better place to request this change to Teams functionality is Teams UserVoice:
https://microsoftteams.uservoice.com/

The Teams product group monitors issues logged in UserVoice. Requests that get high votes are weighted heavily in prioritization for upcoming feature work.
