### ISSUE TITLE
Need to also mention Canada when telling where to send request

### ISSUE THREAD

**Issue by krkutser** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3859]
This should look something like this:

For help with phone numbers **inside** the U.S. or Canada, send your request.
For help with phone numbers **outside** the U.S. or Canada, send your request.

Both, US and CA are handled by the team behind PTN@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ddf1c3c-7fb9-ff3c-e8cd-af75999c78cb
* Version Independent ID: 6178c672-003f-8f99-f4ab-cf9b06cf5ede
* Content: [Contact the PSTN service desk - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk?source=docs#feedback)
* Content Source: [Teams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@krkutser Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by ErsancMS** [comment]
This is now fixed and wording has change to include other contact emails as well

**Comment by scanum** [comment]
@krkutser Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
