### ISSUE TITLE
Need help to check my pin.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#386]
Can not find any information on how to check my pin. Please help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff48c3fb-d44b-1e58-ae5e-ead31e365f6b
* Version Independent ID: 2f42ab25-e052-347a-101e-b6f5b0eb0472
* Content: [View user PIN information in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/manage/authentication/view-user-pin-information)
* Content Source: [Skype/SfbServer/manage/authentication/view-user-pin-information.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/authentication/view-user-pin-information.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi! Could you please describe what you mean with checking your pin?
Thank You

**Comment by yogkumgit** [comment]
As it is an internal transfer of issues, we can close it.
