### ISSUE TITLE
Teams s4b interop

### ISSUE THREAD

**Issue by i-windows** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3860]
in the office roadmap Featured ID: 53934, the following is stated, however it doesnt seem to be reflected in the documentation above, please can you clarify?

Microsoft Teams - Screen sharing in Teams/Skype for Business interop

Enables a Teams user to share their screen in chat or VoIP call with a Skype for Business user

Featured ID: 53934
Added to Roadmap: 7/30/2019
Last Modified: 11/27/2019
Tags: O365, Worldwide (Standard Multi-Tenant), Microsoft Teams, General Availability

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d53d0cb0-90a6-5932-f78e-7de6fcc4d481
* Version Independent ID: 3d468027-cc37-5199-32ec-819bf62b2caa
* Content: [Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability#feedback)
* Content Source: [Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@i-windows Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @i-windows, thank you for your feedback.

It isn't supported natively, it's achieved through interop escalation. This was added to the article when this feature was launched, so it's up to date.

In the same article you found the definition of "interop escalation" and "native interop":
https://docs.microsoft.com/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability#native-interop-and-interop-escalation

**Comment by scanum** [comment]
@i-windows Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
