### ISSUE TITLE
Clarification on Bit Rate

### ISSUE THREAD

**Issue by Mlavieri** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3863]
What is the unit for Bit Rate when input into the Teams Admin Center. Both the documentation and the Admin center show KBs which conflicts with the guidance that shows a minimum of 30 Kbps. Additionally, when trying to input 30 KBs into the Teams admin center I am unable to save the Policy, it appears that 50 KBs, which would equate to 400 Kbps, is the actual minimum allowed in the Teams Admin center. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/meeting-policies-in-teams?WT.mc_id=TeamsAdminCenterCSH#media-bit-rate-kbs)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@Mlavieri  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Mlavieri** [comment]
Hello, any update on this? Thank you

**Comment by dariomws** [comment]
Hi @Mlavieri, thank you for your feeback.

@tonysmit could you kindly help me confirm this? I think it should be kbps and the minimum value is 50:
![image](https://user-images.githubusercontent.com/33589238/75821370-dfc85f00-5d7c-11ea-865b-b066d7f7b8df.png)

**Comment by tonysmit** [comment]
@Mlavieri @dariomws - I'm checking with the PM. I will need to fix the strings and the documentation.  I will try to come back to this, but ping me if I don't. :) Tony

**Comment by tonysmit** [comment]
@Mlavieri @dariomws - I just fixed this in the UX string. It will be updated next week. We are releasing updates then. Thanks.

**Comment by dariomws** [comment]
Thank you @tonysmit!!
