### ISSUE TITLE
Wrong reference for powershell variable

### ISSUE THREAD

**Issue by SimonSkotheimsvik** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3866]
In the first powershell script there is a variable named $sess.
This is wrongly reffered in the following line of code:
Import-PSSession $Session -DisableNameChecking
This should be changed to
Import-PSSession $sess -DisableNameChecking

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: ee417633-3d52-646b-2ef0-94f71535db75
* Version Independent ID: 527bb7f0-b4a7-108c-6f86-8fadced63b86
* Content: [Deploy Microsoft Teams Rooms with Exchange Online - Microsoft Teams](https://docs.microsoft.com/nb-no/MicrosoftTeams/rooms/with-exchange-online#feedback)
* Content Source: [Teams/rooms/with-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-exchange-online.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@SimonSkotheimsvik  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LanaChin** [comment]
Thanks @SimonSkotheimsvik. The doc has been updated (thanks @dariomws).
