### ISSUE TITLE
What about Data collection practices in Microsoft Teams?

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3867]
Hello,

according to my understanding this page is written for Microsoft Teams and Skype for Business. Yet I miss information for Microsoft Teams. I need some clarifications:

1. How can usage data and error reporting data be disabled/controlled for Microsoft Teams? Right now the doc just states Skype for Business .
2. Please add step by step explanations not just for Skype clients but also for Microsoft Teams clients.
3. What does an `UserID` looks like for error reporting in Microsoft Teams? The example given is just for Skype.

Thank you!

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0e0f68-d088-d0b7-cbb7-56bb16e4026f
* Version Independent ID: 8a107028-31a6-6821-a150-1ebdd7a7d440
* Content: [Data collection practices - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/data-collection-practices#feedback)
* Content Source: [Teams/data-collection-practices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/data-collection-practices.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@GiantCrocodile  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @GiantCrocodile, thank you for your feedback.

@tonysmit could you kindly help us to get this information? Thanks!

**Comment by scanum** [comment]
@tonysmit could you kindly help us to get this information? Thanks!

**Comment by tonysmit** [comment]
@nomorephones - Do you have anything to help with this? They have a great point, but I need your assistance. Thanks, Tony

**Comment by nomorephones** [comment]
@scanum I'm not aware of any changes to data collection practices in Teams vs. Skype for Business.  Suggest reaching out to the client team for details here.

**Comment by scanum** [comment]
@nomorephones Thank you! Will do.

**Comment by MicrosoftHeidi** [comment]
I'm engaging with a resource on this.

**Comment by scanum** [comment]
@MicrosoftHeidi Any update on this issue? Thanks.

**Comment by MicrosoftHeidi** [comment]
We have two existing articles that may be of some help, https://docs.microsoft.com/microsoftteams/location-of-data-in-teams and https://docs.microsoft.com/MicrosoftTeams/teams-privacy, but I concur that there's confusion in the article as it stands. I have looped in several people to have a discussion about this article and its contents. I hope to update here once that conversation's complete with further action planned.

**Comment by scanum** [comment]
@GiantCrocodile  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
