### ISSUE TITLE
Can not find where are the logs stored.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#387]
Don't know where are the logs stored. It's like the most crucial thing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e78dee-d473-c49c-62e5-783c7b4b11c4
* Version Independent ID: 0b4eb6a1-d9ae-0106-6e10-eea47f3a47cb
* Content: [Start or stop CLS log capture in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/centralized-logging-service/start-or-stop-log-capture)
* Content Source: [Skype/SfbServer/management-tools/centralized-logging-service/start-or-stop-log-capture.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/management-tools/centralized-logging-service/start-or-stop-log-capture.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by jdubyaeber** [comment]
c:\windows\serviceprofiles\networkservice\appdata\local\temp\tracing

see get-csclsconfiguration and
set-csclsconfiguration if you want to change this locaiton

**Comment by jambirk** [comment]
resolved this in a recent commit, so closing
