### ISSUE TITLE
Improve readability by using a table

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3871]
It would be nicer if the long sentences of 'To learn more about ...' and 'More information ...' etc. are replaced by a proper table for easier and quicker reading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84f319aa-94de-bed1-2e5d-c6fe24436dac
* Version Independent ID: ee6daf32-7e03-801c-dd1b-50bf35e4635e
* Content: [Location of data in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/location-of-data-in-teams#feedback)
* Content Source: [Teams/location-of-data-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/location-of-data-in-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@GiantCrocodile  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@GiantCrocodile Thank you for reaching out to improve MS Docs. I'm currently investigating this.

**Comment by Reeced40** [comment]
@GiantCrocodile Thank you for your recommendation of having tables added to the article. The team is always looking for ways to improve the articles. Please also note that the article was updated in February.

**Comment by scanum** [comment]
@GiantCrocodile Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
