### ISSUE TITLE
So what's the use case/valid scenario for emergency calling in Teams?

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3872]
Is there any? The doc just states non-use cases/scenarios when you shouldn't use emergency calling in Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f27be4a4-b19d-d7b7-f277-7e0c6f7a05d3
* Version Independent ID: 5101bb44-e48b-a125-353e-5783f8b69cb4
* Content: [Emergency calling terms and conditions - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/emergency-calling-terms-and-conditions#feedback)
* Content Source: [Teams/emergency-calling-terms-and-conditions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/emergency-calling-terms-and-conditions.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@GiantCrocodile  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @GiantCrocodile, thank you for your feedback.

For more information about Emergency service, please go to:
https://docs.microsoft.com/microsoftteams/what-are-emergency-locations-addresses-and-call-routing
