### ISSUE TITLE
Picture at the bottom is useless

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3873]
The picture at the bottom of the article is nice but useless: It doesn't show every existing location nor is it valid for any or most customers. The image should be replaced by a more detailed picture or by a list of data locations and regions available or something like this. Right now it is easy to be misunderstood.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84f319aa-94de-bed1-2e5d-c6fe24436dac
* Version Independent ID: ee6daf32-7e03-801c-dd1b-50bf35e4635e
* Content: [Location of data in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/location-of-data-in-teams#feedback)
* Content Source: [Teams/location-of-data-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/location-of-data-in-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@GiantCrocodile  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @GiantCrocodile, thank you for your feedback.

Could you please paste the image here?

Are you talking about this image:
![image](https://user-images.githubusercontent.com/33589238/75462316-d4cb9400-5962-11ea-894c-57902246d579.png)

**Comment by GiantCrocodile** [comment]
I talk about this picture @dariomws: https://docs.microsoft.com/en-us/microsoftteams/media/overview_of_security_and_compliance_in_microsoft_teams_image5.png

**Comment by scanum** [comment]
@GiantCrocodile Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by GiantCrocodile** [comment]
It would be great if you actually check if issues are solved @scanum. As you can see, the article isn't updated and the pull request/changes by @dariomws weren't implemented. This is not resolved. Please reopen.
