### ISSUE TITLE
Guidance for modes

### ISSUE THREAD

**Issue by ivanja81** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3875]
"This is one of the reasons why Microsoft’s prescriptive guidance to on-prem/hybrid customers is to use a mode other than Islands (typically SfBWithTeamsCollab) as the starting point of their upgrade journey to Teams"

As per my understanding our guidance is that Island mode is preferred. Above shows SfbWithTeamscollab as preferred. Can you verify with PG and cycle back?

**Comment by scanum** [comment]
@ivanja81 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by ivanja81** [comment]
'm a MSFT employee. Mail me at ivanja@microsoft.com
