### ISSUE TITLE
External Dialing Prefix a "Required" field

### ISSUE THREAD

**Issue by dschuette01** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3876]
When editing dial plans in the Teams admin portal, in order to test (or even to save), the "External Dialing Prefix" is marked as a required field. We do not want to use an external dialing prefix and this should not be a required field as far as I can tell. Our dial plan was originally set up in PowerShell and does not have this requirement, but to edit in the Teams Admin portal, I would need to add this and confuse our users. Please make this field optional. It should only be REQUIRED if Optimized Device Dialing is turned on (and vice versa, optimized device dialing should be turned on if there is a value in the External Dialing Prefix field).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 451b44cf-961a-5bf5-e4b3-16b96e008dd7
* Version Independent ID: 54e706e1-aaa2-3a03-b8c6-5e96244b85ac
* Content: [Create and manage dial plans - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-and-manage-dial-plans#feedback)
* Content Source: [Teams/create-and-manage-dial-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-and-manage-dial-plans.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@dschuette01 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by robhardman** [comment]
Yeah I've been able to replicate this in my tenant. To workaround, open a Skype for Business Online Powershell session and run the cmdlet:

Set-CsTenantDialPlan -Identity "<Dial Plan Identity>" -ExternalAccessPrefix $null

This will remove the External Access Prefix from the tenant dial plan, and you'll even be able to run tests from a refreshed webpage in the Teams Admin Portal.
