### ISSUE TITLE
Deleting Zero Width Character With Backspace

### ISSUE THREAD

**Issue by phonemyatt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3878]
When you paste this 

> Please ​‌‌‌‌‌‌‌‌‌‍‍‍‌‌‍‍​‌‌‌‌‌‌‌‌‌‍‍‍‌‍‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‍‍​‌‌‌‌‌‌‌‌‌‍‍‍‌‌‌‌​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‍‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‌‌‍​‌‌‌‌‌‌‌‌‌‍‍‍‍‌‌‍​‌‌‌‌‌‌‌‌‌‍‍‌‍‌‌‍​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‍‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‍‍‍​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‌‌‍​‌‌‌‌‌‌‌‌‌‍‍‍‌‌‍‌​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‍‍​‌‌‌‌‌‌‌‌‌‍‍‍‌‍‌‍​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‍‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‍‌‌​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‍‍‌‌‍​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‍‍​‌‌‌‌‌‌‌‌‌‍‍‍‌‍‌‍​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‍‌‌‍‍​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‌‌‍​‌‌‌‌‌‌‌‌‌‍‍‌‌‌‍‍​‌‌‌‌‌‌‌‌‌‍‍‌‍‌‍‍​‌‌‌‌‌‌‌‌‌‍‍‌‌‍‌‍​‌‌‌‌‌‌‌‌‌‍‍‍‌‌‍‌​‌‌‌‌‌‌‌‌‌‌‍‌‍‍‌‌​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‌‌‍​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‍‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‍‌‌​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‍‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‍‍​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‍‌‌‍‍​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‍‍​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‌‍​‌‌‌‌‌‌‌‌‌‍‍‌‌‍‌‍​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‍‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‍‌‌‍‌​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‍‍​‌‌‌‌‌‌‌‌‌‍‍‍‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‍‌‍​‌‌‌‌‌‌‌‌‌‍‍‍‌‌‍‌​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‍‌‍‍‍​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‍‍​‌‌‌‌‌‌‌‌‌‍‍‍‌‌‍‌​‌‌‌‌‌‌‌‌‌‍‍‌‍‌‍‍​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‍​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‌‍‍‍‌‍‌​‌‌‌‌‌‌‌‌‌‌‍‌‍‌‌‍​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‌‌‍‍‍‍​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‍‌​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‌‌​‌‌‌‌‌‌‌‌‌‍‍‍‍‌‌‍​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‌‌‍​‌‌‌‌‌‌‌‌‌‍‍‌‌‍‍‌​‌‌‌‌‌‌‌‌‌‍‍‍‌‍‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‍‌‍​‌‌‌‌‌‌‌‌‌‍‍‍‌‌‍‌​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‍‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‍‍​‌‌‌‌‌‌‌‌‌‍‍‌‍‌‌‍​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‍‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‍‍‍​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‌‌‍​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‍‍‍​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‍‍​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‍‍​‌‌‌‌‌‌‌‌‌‍‍‌‌‍‌‌​‌‌‌‌‌‌‌‌‌‌‍‌‍‍‌‌​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‍‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‌‌‍​‌‌‌‌‌‌‌‌‌‍‍‍‌‌‍‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‍‌‌​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‍‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‌‌‍​‌‌‌‌‌‌‌‌‌‍‍‍‍‌‌‍​‌‌‌‌‌‌‌‌‌‌‍‌‌‍‍‍​‌‌‌‌‌‌‌‌‌‍‍‍‌‌‍‍​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‍‌‍‍‍​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‍‍​‌‌‌‌‌‌‌‌‌‍‍‍‌‌‍‌​‌‌‌‌‌‌‌‌‌‍‍‌‍‌‍‍​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‌‍‍​‌‌‌‌‌‌‌‌‌‍‍‌‌‌‌‍​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‍‌​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‍‍‌‌‍​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‍‍​‌‌‌‌‌‌‌‌‌‍‍‍‌‍‌‍​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‍‌‍‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‍‌‌‌​‌‌‌‌‌‌‌‌‌‍‍‌‌‍‌‍​‌‌‌‌‌‌‌‌‌‍‍‌‍‍‍‌​‌‌‌‌‌‌‌‌‌‌‍‌‌‌‌‌​go home and enjoy the rest of the day.

 and hold down backspace to delete, will hang microsoft team. 
The sentence is encrypted with hidden words between zero width character, full sentence is

> Please stop playing around you slacker, and do some proper work! :) Only after doing a good, hard day's work can you then go home and enjoy the rest of the day.

**Comment by phonemyatt** [comment]
the website to encrypt and decrypt https://love-letter.netlify.com/

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
