### ISSUE TITLE
Need to know compatible hardware list.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#388]
Where can I find list compatible hardware?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2369c8dd-2f4d-e2c2-e7fa-745466cb3455
* Version Independent ID: 90e0764d-de05-254c-d32d-a9522df6b49a
* Content: [Skype for Business compatibility with Office apps](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/compatibility-with-office)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/compatibility-with-office.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/compatibility-with-office.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
https://technet.microsoft.com/en-us/office/dn947482.aspx

**Comment by nsshommo** [comment]
Thanks for your help. Please let me know when you add the link to the page.
