### ISSUE TITLE
Continued mention of "Skype for Business"

### ISSUE THREAD

**Issue by dooleydo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3881]
In a teamsonly org the setup instructions are not helpful as there will be no Skype sign-in address or FQDN for a Skype server.  There should be more striaghtforward instructions related to Teams only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/console#Initial)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@dooleydo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@dooleydo Thank you for reaching out and helping improve MS Docs. Please have a look at this article and let me know if it helps at all. https://docs.microsoft.com/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability

**Comment by scanum** [comment]
@dooleydo We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
