### ISSUE TITLE
unclear instructions

### ISSUE THREAD

**Issue by school4schools** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3883]
This document is unclear, both to me and to numerous MS engineers: 

"Your tenant dial-out minute pool size is based on assigned licenses and not purchased licenses."

Needs context and clearer explanation, as I have no idea what that means.
Also, that the dial-out minutes will be billed after using the allotted 60 minutes is also unclear (to me and numerous MS engineers I have spoke to about this).

You may wish to clarfity that dial-out minutes exceeding alloted 60 min / month will be billed to communications credit license according to set limits in that license.  Then link to communication credits to clarify how that works.

Please fix so others won't have to waste as much time as I did on this rather simple issue.  

Hint: write to an UNINFORMED AUDIENCE. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 037fe22c-ba09-e381-231d-c37f6bb2a774
* Version Independent ID: e8046130-d407-3155-53c5-9043110cd793
* Content: [Audio Conferencing subscription “Dial-Out”/“Call Me At” benefit - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-subscription-dial-out#feedback)
* Content Source: [Teams/audio-conferencing-subscription-dial-out.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-subscription-dial-out.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@school4schools Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@school4schools Thank you for reaching out.  I'm looking through this document to see what I can change for more clarity. If you have any further suggestions in the meantime please let me know.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@school4schools Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
