### ISSUE TITLE
The content of this article is SCOM agent configuration. But the link/title is Watcher Node.

### ISSUE THREAD

**Issue by neilcalgary** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3884]
The content of this article is SCOM agent configuration. But the link is Watcher Node.
The link to this article is : https://docs.microsoft.com/en-us/skypeforbusiness/tools/watcher-nodes-2019
The content should be something like this article: 
https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/use-scom-management-pack/watcher-nodes

**Comment by scanum** [comment]
@neilcalgary Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@neilcalgary Thanks for reaching out. Which article is the article in question? Please let me know soonest and I can investigate further.

**Comment by neilcalgary** [comment]
The article in question is 🙂https://docs.microsoft.com/en-us/skypeforbusiness/tools/watcher-nodes-2019
The content of this article is as same as this one: https://docs.microsoft.com/en-us/skypeforbusiness/tools/configure-computers-to-monitor-2019

However, it should be something like this: https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/use-scom-management-pack/watcher-nodes

Thanks.

Neil
[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/use-scom-management-pack/watcher-nodes>
Install and configure watcher nodes - Skype for Business Server 2015 | Microsoft Docs<https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/use-scom-management-pack/watcher-nodes>
Install and configure watcher nodes. 11/20/2015; 14 minutes to read +5; In this article. Summary: Install and configure watcher nodes for Skype for Business Server synthetic transactions. Watcher nodes are computers that periodically run Skype for Business Server synthetic transactions.
docs.microsoft.com

[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/skypeforbusiness/tools/configure-computers-to-monitor-2019>
Configure the Skype for Business Server computers that will be monitored - Skype for Business Server 2019 | Microsoft Docs<https://docs.microsoft.com/en-us/skypeforbusiness/tools/configure-computers-to-monitor-2019>
Configure the Skype for Business Server computers that will be monitored. 2/1/2018; 3 minutes to read +2; In this article. Summary: Install the Operations Manager agent files on the Skype for Business Server 2019 computer to be monitored, and configure the computer to act as a System Center proxy. Each Skype for Business Server 2019 computer that you want to monitor must be able to self-report ...
docs.microsoft.com

[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/skypeforbusiness/tools/watcher-nodes-2019>
Configure the Skype for Business Server computers that will be monitored - Skype for Business Server 2019 | Microsoft Docs<https://docs.microsoft.com/en-us/skypeforbusiness/tools/watcher-nodes-2019>
Configure the Skype for Business Server computers that will be monitored. 11/7/2018; 3 minutes to read +2; In this article. Summary: Install the Operations Manager agent files on the Skype for Business Server 2019 computer to be monitored, and configure the computer to act as a System Center proxy. Each Skype for Business Server 2019 computer that you want to monitor must be able to self ...
docs.microsoft.com


________________________________

**Comment by lindspea** [comment]
@LanaChin please could you have a look at this issue and let me know if there is anything I can do to help from my side. The team mentioned that there could be work going on with this doc set.

**Comment by LanaChin** [comment]
Looking into this.

**Comment by lindspea** [comment]
@LanaChin any update yet?

**Comment by scanum** [comment]
@LanaChin any update yet?

**Comment by scanum** [comment]
@LanaChin any update yet?

**Comment by scanum** [comment]
@LanaChin any update yet?

**Comment by scanum** [comment]
@LanaChin any update yet?

**Comment by scanum** [comment]
@LanaChin any update yet?

**Comment by lindspea** [comment]
@LanaChin any update yet?

**Comment by LanaChin** [comment]
Thanks so much for raising this issue. The content in https://docs.microsoft.com/skypeforbusiness/management-tools/use-scom-management-pack/watcher-nodes applies and we're working to update the watcher-nodes-2019 article to reflect that.
