### ISSUE TITLE
Outdated content

### ISSUE THREAD

**Issue by maisiekocher** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3885]
Hello, I believe this outdated. When you go to the Security and compliance center, you are directed to Exchange auditing.

**Comment by scanum** [comment]
@maisiekocher Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@maisiekocher Please link the documentation you are referring to.

**Comment by lindspea** [comment]
@maisiekocher thank you for reaching out. I'd like to have a look at this issue but I'm not sure what article you are referring to.  Please send me the link so I can help you soonest.

**Comment by scanum** [comment]
@maisiekocher We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
