### ISSUE TITLE
Type: GCC is wrong

### ISSUE THREAD

**Issue by klstclair** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3886]
In the section: "The use of Microsoft 365 for Government - GCC (government certificate of competency) is appropriate to meet the requirements of IT pros who are driving deployments of Office 365 in US federal, state, local, tribal, or territorial government entities or other entities that handle data that’s subject to government regulations and requirements." GCC stands for "Government Community Cloud" - see the service description at: https://www.microsoft.com/en-us/microsoft-365/government/eligibility-validation?rtc=1 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c73be3fd-282d-8e5a-02f8-37d2f27c95ab
* Version Independent ID: 0baeeca3-237f-31dc-d3da-35140b9ebb9a
* Content: [Chat, teams, channels, & apps in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/deploy-chat-teams-channels-microsoft-teams-landing-page#feedback)
* Content Source: [Teams/deploy-chat-teams-channels-microsoft-teams-landing-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/deploy-chat-teams-channels-microsoft-teams-landing-page.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@klstclair Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@klstclair Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you
