### ISSUE TITLE
SipSignallingPort flag spelling change

### ISSUE THREAD

**Issue by jamescussen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3888]
The New/Set/Get-CSOnlinePSTNGateway commands SipSignallingPort flag has now been changed to be spelt with only one 'L' (ie. SipSignalingPort). All of the documentation here needs to be updated to reflect this. You will see this change reflected in the PowerShell command docs here: https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinepstngateway?view=skype-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df318fdb-6d58-86f8-de31-6eca533a9746
* Version Independent ID: a2248abf-bdf0-2c22-2604-74b482156684
* Content: [Configure Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-configure#feedback)
* Content Source: [Teams/direct-routing-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-configure.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@jamescussen Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@jamescussen Thank you for reaching out and helping improve MS Docs. It looks like the typo has been fixed in the interim. Please confirm from your side.

**Comment by scanum** [comment]
@jamescussen Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you
