### ISSUE TITLE
How to configure a SIP trunk in SfB.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#389]
Looking for simple step by step instructions on how to configure a SIP trunk in Skype for Business.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d3393d2-8de2-873c-f35b-05c1d13b6cbd
* Version Independent ID: c4ed8ac6-f813-f268-e1ea-715a900bdee8
* Content: [SIP trunking in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/enterprise-voice-solution/sip-trunking)
* Content Source: [Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/sip-trunking.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/sip-trunking.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi @nsshommo you will find information about steps required in this section https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-enterprise-voice/configure-trunks
Hope this information has helped you
