### ISSUE TITLE
Tiny error on Interoperability

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3894]
While running different modes I have found that following statement:
"These interop experiences are available to and between users who have one of the following coexistence modes assigned: Skype for Business with Teams Collaboration, Skype for Business with Teams Collaboration and meetings, Skype for Business Only, or Teams Only. **There is no interoperability to users in Islands mode.**"

Actually there is interoperability from Skype user who is having "island" mode with user "Teams Only". User from Skype with island mode can send message to user with Teams Only and they can communicate with each other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d53d0cb0-90a6-5932-f78e-7de6fcc4d481
* Version Independent ID: 3d468027-cc37-5199-32ec-819bf62b2caa
* Content: [Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability)
* Content Source: [Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Petri-X  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Petri-X thank you for reaching out and helping improve MS Docs. Would you suggest adding that in a note in the article for clarity to help other users?

**Comment by scanum** [comment]
@Petri-X  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
