### ISSUE TITLE
There is no more CodecPriority parameter

### ISSUE THREAD

**Issue by dinocaputo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3897]
https://docs.microsoft.com/en-us/microsoftteams/direct-routing-configure
The parameter -CodecPriority no longer works nor is returned when you issue a get-CsOnlinePstnGateway cmdlet.  Docs should be updated if parameter has been removed.

**Comment by scanum** [comment]
@dinocaputo  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@dinocaputo thank you for reaching out and helping improve MS Docs.  I see the doc has been updated today, so please let me know if the section you mentioned has been updated. It's quite a lengthy article so I'll go through it shortly to check as well.

**Comment by scanum** [comment]
@dinocaputo Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
