### ISSUE TITLE
confusing terminology

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3899]
Virtually every paragraph in this article using different terminology:

* "prompt language"
* "system language"
* "default language"
* "greeting language"
* "preferred language"

If all these terms refer to the same thing, you should not use different words

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5586a3f7-0a24-3720-1ad5-336737c44275
* Version Independent ID: c5800980-2d9f-ee75-4193-bc5e8e9a68b9
* Content: [Change the default language for greetings and emails - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/change-the-default-language-for-greetings-and-emails)
* Content Source: [Teams/change-the-default-language-for-greetings-and-emails.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/change-the-default-language-for-greetings-and-emails.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@shivtorov  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@shivtorov thank you for reaching out and helping improve MS Docs. I've just had a look at the article and the language seems to read correctly regarding relevance. Please let me know if you need any further information or assistance.

**Comment by scanum** [comment]
@shivtorov Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
