### ISSUE TITLE
Need to know which plug-in is needed.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#390]
The instructions say a plug-in is needed but doesn't tell which one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ce7a531-5b1f-f404-50a3-58eb285a0a1a
* Version Independent ID: 61d27af3-cfd6-ed7f-102c-072721db0209
* Content: [Plan for Meetings clients (Web App and Meetings App)](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/meetings-clients)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/meetings-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/meetings-clients.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi thanks for your feedback!
The plugin is mentioned early in the document as Skype for Business Web App browser plug-in
Hope this information has helped you!
