### ISSUE TITLE
Please make the statement clear, it is ambigious

### ISSUE THREAD

**Issue by mwe-microsoft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3901]
What is the main difference between using the Group mailbox location row and Teams channel messages location row in retention policies?
If you use the Group mailbox and User mailbox location rows for Exchange Online, Teams data will be deleted from the specified mailboxes. However, this only removes data from the mailbox. It doesn’t delete other Teams data, such as chats service. We recommend that you use Teams retention policies to properly manage all Teams data. A Teams retention policy removes teams data from all storage locations – Mailboxes, Chat service, Teams clients.

Note: Launch of the retention policies feature for Teams makes sure that only Teams policies delete Teams items stored inside Exchange mailbox locations (user or group). Other policies setup on mailboxes cannot affect Teams items. This was true in the past, but has been fixed with the launch of retention policies feature.

The basic text states that Group Mailbox retention policies delete Teams data from the mailbox, the note states that this is updated after Launch of retention policies. This is ambiguous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f55c52a5-5841-b9c9-1607-2013dc3f2e20
* Version Independent ID: 16d93458-5e01-646f-dac5-31306cc7f3fb
* Content: [Microsoft Teams retention policies FAQ - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/retention-policies-faq#feedback)
* Content Source: [Teams/retention-policies-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/retention-policies-faq.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@mwe-microsoft  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@mwe-microsoft thank you for reaching out and helping improve MS Docs. @LolaJacobsen please can you assist - related issue https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2803

**Comment by LolaJacobsen** [comment]
@prvijay Can you review this issue and let us know how to respond please?

**Comment by scanum** [comment]
@LolaJacobsen @prvijay any updat on this? Thanks!

**Comment by LolaJacobsen** [comment]
@anwara-ms please review this issue, let me know what documentation updates are needed.

**Comment by anwara-ms** [comment]
The article was updated on around Feb 14th, that is after the feedback was received. Is the statement still ambiguous? @mwe-microsoft ?
