### ISSUE TITLE
Licensing Requirements

### ISSUE THREAD

**Issue by jpalarchio** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3909]
The line "Give the room a phone number and make or receive a calls from the room or join an audio conference using a phone number" is a bit misleading when it states that the license required is "Meeting Room SKU".  You also need either Direct Routing configured or a Calling Plan license; this should be noted as a footnote at a minimum.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-licensing#feedback)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-licensing.md)
* Service: **skype-for-business-online**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@jpalarchio  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by pyoungberg** [comment]
Is there any way to use Calling Credits instead of buying an entire calling plan for each and every Teams Room System?

**Comment by lindspea** [comment]
@jpalarchio thank you for reaching out and helping improve MS Docs. It seems this documentation might have been updated in the interim. Please have a look and let me know, as I'm not finding the wording you mentioned above.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@jpalarchio Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by pyoungberg** [comment]
@scanum I'm not seeing a push to the article with the changes, is it pending approval?
