### ISSUE TITLE
Another limitation to add

### ISSUE THREAD

**Issue by advancedpartnerships** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3913]
One more limitation to add is that guests cannot login with their guest account username/password to the Android App. I am not sure if a guest with the same setup can login and use the iOS teams app, but for now, Android accessibility is not functional. If anyone has a workaround, I would love to hear it.  An issue that I've found is that trying to access Teams from an android device through a browser window will automatically recognize the platform and force users into the mobile app if it's downloaded on that device. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [What the guest experience is like - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-experience#feedback)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@advancedpartnerships  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@advancedpartnerships thank you for reaching out and helping improve MS Docs. I work on the writing side of the documentation, but I have an Android device and I use the Teams App with my login. Just to clarify - are you wanting to access it through a browser. If you are, it will automatically send you to the app.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@advancedpartnerships Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
