### ISSUE TITLE
Is this actually available in Nigeria?

### ISSUE THREAD

**Issue by SDkempf94** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3916]
It says that we can get toll numbers, but there is no option in the teams admin or legacy portal - you can't even select Nigeria from the list, it's not even there? Does the article need to be amended or is there a prerequisite? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2695858-2551-817d-fae4-c7311e0585a6
* Version Independent ID: bc7aa126-964f-5305-b685-5fd2d7f36b0f
* Content: [Availability in Nigeria - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-nigeria?source=docs#feedback)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-nigeria.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-nigeria.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@SDkempf94  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@LanaChin please could you assist?

**Comment by scanum** [comment]
@LanaChin Hi Lana, could you please help with this issue? Thanks

**Comment by LanaChin** [comment]
Looking into this.

**Comment by LanaChin** [comment]
Hi @SDkempf94 - Currently, you can't get service numbers through the Teams admin center for Nigeria. Please contact the PSTN service desk who will be able to help you out. See this article for contact info: https://docs.microsoft.com/microsoftteams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk.  Thank you.
