### ISSUE TITLE
Emergency Location

### ISSUE THREAD

**Issue by rickleye** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3917]
Under emergency address, Could you include how to validate a location with Suite Numbers. For Example  " Suite A & B 12345 North Main Street, Redmond, WA 98052"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634810fc-7a47-f794-7803-9f3941d664dd
* Version Independent ID: 52587955-5054-a003-6d03-948ce02838dd
* Content: [Plan emergency calling, emergency addresses, emergency call routing, dynamic emergency calling - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/what-are-emergency-locations-addresses-and-call-routing?toc=/skypeforbusiness/toc.json&bc=/skypeforbusiness/breadcrumb/toc.json)
* Content Source: [Teams/what-are-emergency-locations-addresses-and-call-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-emergency-locations-addresses-and-call-routing.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@rickleye  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@rickleye thank you for reaching out and helping improve MS Docs. It seems the article has been updated recently so please let me know if you need further assistance.

**Comment by scanum** [comment]
@rickleye Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
