### ISSUE TITLE
Sign SkypeRoomProvisioningScript.ps1

### ISSUE THREAD

**Issue by Scott-som** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3918]
Please sign the SkypeRoomProvisioningScript.ps1 file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-office-365#feedback)
* Content Source: [Teams/rooms/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-office-365.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Scott-som  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Scott-som thank you for reaching out and helping improve MS Docs. Please clarify what your request is?

**Comment by scanum** [comment]
@Scott-som  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Scott-som** [comment]
On the page https://docs.microsoft.com/en-us/microsoftteams/rooms/with-office-365 is a link to a powershell script SkypeRoomProvisioningScript.ps1 which is not signed can causes some run issues.
