### ISSUE TITLE
Migrating Skype on-prem CAP's to Skype online/Teams

### ISSUE THREAD

**Issue by phifdd4305** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3919]
I have a hybrid Skype (2015 server) environment with on-prem CAP's that I want to move to Skype online but to Teams ultimately. I've found posts that show how to move CAP's from on-prem pool to on-prem pool but nothing around moving them to online. I was able to create a new CAP in Teams with a dial plan and CAP license but is there a way to migrate from on-prem to online? We have hundreds on CAP's across multiple sites so creating new ones really isn't an option for us.

**Comment by scanum** [comment]
@phifdd4305 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
