### ISSUE TITLE
Call agents selected must be:

### ISSUE THREAD

**Issue by rickleye** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3921]
3. On-premises Skype for Business Server users  - Is this valid, If the user is homed on premises how do they connect to Azure unless is Hybrid set up is involved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b755d9ae-13ac-019f-f5f4-a95b1eee2989
* Version Independent ID: f7afd8ad-e6e0-6c79-aed1-4ee87d48ba12
* Content: [Create a call queue - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue)
* Content Source: [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-call-queue.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@rickleye  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@CarolynRowe please can you have a look at this.

**Comment by scanum** [comment]
@CarolynRowe Could you please help on this issue? Thanks!

**Comment by scanum** [comment]
@CarolynRowe Could you please help on this issue? Thanks!

**Comment by scanum** [comment]
@CarolynRowe Could you please help on this issue? Thanks!

**Comment by scanum** [comment]
@CarolynRowe Could you please help on this issue? Thanks!

**Comment by CarolynRowe** [comment]
For Skype for Business Server users, hybrid connectivity is a requirement.  Please see:  https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-call-queue.  I'm going to close this issue, but please let us know if we did not answer your question.
