### ISSUE TITLE
Is this GA?

### ISSUE THREAD

**Issue by briandahlincoyne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3922]
Confusion on if this is GA or not, The roadmap says Q4 2019 with no new updates, and user voice has not been updated since 2019. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b41d63bc-26f4-fd50-adc4-f665c1a4cd88
* Version Independent ID: 24248b2d-79a1-98a7-86dd-f6dbcf9e2ab3
* Content: [Team expiration and renewal in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/team-expiration-renewal)
* Content Source: [Teams/team-expiration-renewal.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/team-expiration-renewal.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@briandahlincoyne  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@briandahlincoyne Thank you for reaching out. Just to clarify, are you asking whether the option of MS Teams renewal or expiration is available yet? Please note the document has also been updated at the beginning of February so there might be updated information in the article. Please let me know if I can help further.

**Comment by briandahlincoyne** [comment]
I am looking for clarification on if the group expiration policies takes
into consideration active teams, this is on the roadmap, and mentioned in
this document, but when i test it in my tenant it does not appear to be
available for us yet.

**Comment by lindspea** [comment]
@briandahlincoyne - https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/groups-lifecycle - looks like it may be GA.

**Comment by lindspea** [comment]
@briandahlincoyne - https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/groups-lifecycle - looks like it may be GA.

**Comment by scanum** [comment]
@briandahlincoyne Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
