### ISSUE TITLE
Doesn't cover how guests use Teams

### ISSUE THREAD

**Issue by SJL-369** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3925]
This article needs to go over:
- what guests see when they first open Teams.
- the experience if guests have an existing Office365 account.
- the experience if guests don't have an existing Office365 account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [What the guest experience is like - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-experience#feedback)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@SJL-369  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by rito2k** [comment]
Maybe you want to have a look at: https://docs.microsoft.com/en-us/microsoftteams/guest-experience

**Comment by scanum** [comment]
@SJL-369 Thank you for submitting feedback. We understand that the information is included in the linked article above.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
