### ISSUE TITLE
Browser Meeting Video Capabilities Not Documented

### ISSUE THREAD

**Issue by Ovyone** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3928]
Start Video with Blur and Live Captions are missing from the browser. Documentation does not reflect this information. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients?source=docs)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Ovyone Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @Ovyone, thank you for your feedback.

Live captions are a preview feature in Microsoft Teams, and they're only available in English (US) and on the Teams desktop app for now. I think we cannot add some information here as it's not in GA yet.

I will add some information about blur background to see if it's approved.

**Comment by scanum** [comment]
@Ovyone Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
