### ISSUE TITLE
Update Network considerations for better Cloud VM Support

### ISSUE THREAD

**Issue by jstrong013** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3935]
The [Network Considerations](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-hybrid-connectivity#network-considerations) section should be updated to include additional clarification on the subsection [Firewall considerations](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-hybrid-connectivity#firewall-considerations) to include Geo-Locations.

This is because this [documentation](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/configure-cloud-voicemail) references this page in step 2 of overview. The edge server needs access to six geographic sites (e.g. Hong Kong in China [APAC Region]) in order for Cloud Voicemail to work fully. 

Thus, if China is blocked, full functionality of Cloud Voicemail does not occur. Thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c0ab608-c57e-0e72-6071-5fc02cf6217c
* Version Independent ID: 73c13bf0-4247-ad87-e3be-7d9a59ab457e
* Content: [Plan hybrid connect - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-hybrid-connectivity#network-considerations)
* Content Source: [Skype/SfbHybrid/hybrid/plan-hybrid-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/plan-hybrid-connectivity.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@jstrong013 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@jstrong013  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @jstrong013, thank you for your feedback.

I really need more detail to try to help with this issue. For example, where did you find next sentence?

"The edge server needs access to six geographic sites (e.g. Hong Kong in China [APAC Region]) in order for Cloud Voicemail to work fully."

**Comment by jstrong013** [comment]
Hello @dariomws306, thanks for looking into. 

That line was an example. It would probably read better like this, "For Example, the edge server for cloud voicemail to operate appropriately needs access to six geographic sites (e.g. Honk Kong in China [APAC Region]) in order for Cloud Voicemail to work fully. This was discovered by testing."

Maybe to simply the request and to word a different way, what are the Geo-Locations that if blocked would cause Cloud Voicemail to not have full functionality (since those directions reference this page)? The **Firewall Considerations** section should be updated to include this information. 

Hope that helps.

**Comment by dariomws306** [comment]
Ok, thank you, I need to confirm this information first.

@CarolynRowe could you kindly help me to confirm this information?

**Comment by scanum** [comment]
@CarolynRowe Any updates on this? Thanks!

**Comment by CarolynRowe** [comment]
Please check with @dstrome  or @MicrosoftHeidi

**Comment by scanum** [comment]
@dstrome @MicrosoftHeidi Wondering if you can help with this issue? Thanks!

**Comment by scanum** [comment]
@dstrome @MicrosoftHeidi Wondering if you can help with this issue? Thanks!

**Comment by dstrome** [comment]
hi @jstrong013 Thanks for the feedback. The required network ports, protocols, and IP address ranges can be found by following this link in the Firewall considerations section

For more information, including details about ports and protocol requirements, see [Office 365 URLs and IP address ranges](https://go.microsoft.com/fwlink/p/?LinkId=252942).
