### ISSUE TITLE
Small error

### ISSUE THREAD

**Issue by threecatsdigital** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3936]
Toward the start of the process, the directions state to "click Voice then select Auto Attendants, then click + New." Instead of "+ New" the text actually reads "+ Add".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afdd6102-e72f-63bb-77fc-8cfd4373e8db
* Version Independent ID: 4f073d07-8c3a-9ca9-7f16-5892953543dc
* Content: [Small business example — Set up an Auto Attendant - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/tutorial-org-aa?tutorial-step=4#feedback)
* Content Source: [Teams/tutorial-org-aa.yml](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/blob/live/Teams/tutorial-org-aa.yml)
* Service: **msteams**
* GitHub Login: @SharS
* Microsoft Alias: **jambirk**

**Comment by jstrong013** [comment]
Content Source: [Teams/tutorial-org-aa.yml](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tutorial-org-aa.yml)

**Comment by scanum** [comment]
@threecatsdigital Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
