### ISSUE TITLE
HP slice g2 fail on deployment at oobe

### ISSUE THREAD

**Issue by StefanW86** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3940]
Hello,
we try since three weeks to deploy our HP Slice G2 device with teams room system. We created with the actual version of CreateSRSMedia.ps1 the installation medium successfully. Then boot the device from the stick. After the first phase of the windows installation we setup breaks with the error message "windows could not complete the installation. To install windows on this device, restart..."

We have no idea what goes wrong. Something with the oobe or autounattend.xml file ?

**Comment by scanum** [comment]
@StefanW86 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
