### ISSUE TITLE
Need PowerShell Commands

### ISSUE THREAD

**Issue by cgskreddy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3941]
Need PowerShell commands to export "list of phone numbers in your organization". Why there are no K.B.Articles on powershell commands?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 224b0537-e144-f5ed-6974-6e34733bceb2
* Version Independent ID: 4f1875c6-77ef-f636-669e-5f3af9691f7d
* Content: [See a list of phone numbers in your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/see-a-list-of-phone-numbers-in-your-organization)
* Content Source: [Teams/see-a-list-of-phone-numbers-in-your-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/see-a-list-of-phone-numbers-in-your-organization.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@cgskreddy Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@cgskreddy Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
