### ISSUE TITLE
What happens if there is no supported Exchange

### ISSUE THREAD

**Issue by colbyMS** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3942]
I am looking at a scenario where Exchange is on-premises and will not be set up for Hybrid until later.  The table in the article does not mention this scenario.  Can we get it verified what will happen?  Is there a shadow mailbox created which may affect hybrid migrations in the future?

**Comment by colbyMS** [comment]
I just noticed that this is very similar to $3735.  Sorry for opening up a new issue

**Comment by scanum** [comment]
@colbyMS thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
