### ISSUE TITLE
Page hasn't been updated in a month

### ISSUE THREAD

**Issue by BSiefferman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3944]
This page hasn't been update in a full month. Can we please get the past month's worth of updates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3081f70c-d927-ce5d-d957-ca7ba7e07a55
* Version Independent ID: 17704162-7ff9-015c-30a1-1cbc078f0782
* Content: [Microsoft Teams content updates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-updates#feedback)
* Content Source: [Teams/teams-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-updates.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@BSiefferman Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @BSiefferman, thank you for your feedback.

There is a system that processes all the data to generate this topic in real time as changes are published live.

@dstrome @LolaJacobsen could you kindly confirm that this process is still working?

**Comment by dstrome** [comment]
Yes, this is a known issue. I'm working on getting this resolved.

**Comment by dstrome** [comment]
This issue has been resolved.
