### ISSUE TITLE
filter guests

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3947]
Is it possible to filter out guest users in a private channel members list using filter on roles?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e0ac38-cfff-8d8f-5345-2ae93a9fae2e
* Version Independent ID: bec44289-e9fa-4464-1601-0ca86d61e6ca
* Content: [Manage the life cycle of private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels-life-cycle-management)
* Content Source: [Teams/private-channels-life-cycle-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels-life-cycle-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@prashant1380 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @prashant1380, thank you for your feedback.

When you go to "Manage Team" or "Manage Channel" you will see the list of members and each role (Owner, Member or Guest):
![image](https://user-images.githubusercontent.com/33589238/74683668-70614580-51a8-11ea-85af-88bc58e7de00.png)

**Comment by prashant1380** [comment]
Sorry I missed to mention graph API. So I am looking for a solution to filter guests using graph API

**Comment by dariomws306** [comment]
@prashant1380 docs.microsoft.com feedback is available to help us improve documentation. I think you can filter guests using graph API since Teams PowerShell is based on Graph, but I kindly ask you to go to following place for these type of questions:
https://techcommunity.microsoft.com/

**Comment by scanum** [comment]
@prashant1380 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
