### ISSUE TITLE
Microsoft Teams - macOS Search Issue

### ISSUE THREAD

**Issue by dbelling** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3949]
When using search on macOS for a particular term, initial search functions as expected. However - when using the search bar and navigating to a prior search term, the term is submitted as `object [Object]`. I've attached a screenshot for clarity:

<img width="826" alt="Screen Shot 2020-02-11 at 8 51 07 AM" src="https://user-images.githubusercontent.com/8824740/74247924-7210a200-4cac-11ea-9b5e-36d1f9de8880.png">

I am using Catalaina (10.15.3) and Team (1.3.00.2164)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues#feedback)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@dbelling thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
