### ISSUE TITLE
Add required SQL permission.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#395]
Add required SQL permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3de48a6d-4cce-eaee-d9e8-7e001d890fea
* Version Independent ID: 3e2ad9ee-3b50-58a9-b78e-8db14387cf29
* Content: [Patch or update a Back End Server or Standard Edition server in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/manage/topology/patch-or-update-a-back-end-or-standard-edition-server)
* Content Source: [Skype/SfbServer/manage/topology/patch-or-update-a-back-end-or-standard-edition-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/topology/patch-or-update-a-back-end-or-standard-edition-server.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization."

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi @nsshommo thanks for your feedback, we really appreciate it.
Document specifies you to log in using a user member of CSAdministrator role, and as that role will have the SQL permissions described here https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-deployment-permissions-for-sql-server

Hope this information has helped you

thanks!
