### ISSUE TITLE
Must or something else?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3950]
Hi,

You are writing:
"_There must be 14 columns for each row,..._"
But on your example you have 15 columns as the last one (VPN) is the optional. So might be better if you write "14 or 15", or you totally skip "optional" and having VPN also as a mandatory. Then you could write "must have 15 columns in all cases".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb8d8b48-561b-6817-1ce0-4b2aedc261a8
* Version Independent ID: dfd5cf4a-509a-3ed1-0267-6281c251fbef
* Content: [Turn on and use Call Quality Dashboard - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/turning-on-and-using-call-quality-dashboard)
* Content Source: [Teams/turning-on-and-using-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/turning-on-and-using-call-quality-dashboard.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Petri-X  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
