### ISSUE TITLE
Guest Users

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3951]
Article should mention if this apply also for external guest users or not, or how to change policy for them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f91604a-35b0-dfbb-55b2-b601cb0841b0
* Version Independent ID: 84bcd0d7-b4ed-f13e-c84b-2ec6a7661ae9
* Content: [Manage app setup policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-app-setup-policies)
* Content Source: [Teams/teams-app-setup-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-setup-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Kazzan  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @Kazzan, thank you for your feedback.

Policies like App Setup or Meeting cannot be assigned to guest users. So, they don't apply to guest users.

**Comment by dariomws306** [comment]
Hi @Kazzan, thank you for your feedback.

@LanaChin could you kindly help with this? I have verified and "Global (Org-wide default)" apply to guest users. But you can apply other policies to Guests. Could you confirm this behavior?

Thanks!

**Comment by Kazzan** [comment]
Thanks @dariomws306. This should be definitely need to be mentioned in article, and probable also ways how to solve that for externals (I see like Dynamic AAD Group with different Teams policy maybe).

**Comment by dariomws306** [comment]
> Hi @Kazzan, thank you for your feedback.
> 
> @LanaChin could you kindly help with this? I have verified and "Global (Org-wide default)" apply to guest users. But you can apply other policies to Guests. Could you confirm this behavior?
> 
> Thanks!

Typo:
"But you CANNOT apply other policies to Guests"

**Comment by LanaChin** [comment]
Looing into this, thank you.

**Comment by scanum** [comment]
@LanaChin Any updates on this? Thanks!

**Comment by scanum** [comment]
@LanaChin Any updates on this? Thanks!

**Comment by scanum** [comment]
@LanaChin Any updates on this? Thanks!

**Comment by scanum** [comment]
@LanaChin Any updates on this? Thanks!

**Comment by scanum** [comment]
@LanaChin any update yet?

**Comment by LanaChin** [comment]
Thanks very much for your input, @Kazzan. I've passed your feedback to the product team and they are aware of your ask.
