### ISSUE TITLE
Remove a deleted group

### ISSUE THREAD

**Issue by adagioajanes** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3952]
This page goes over how to restore a deleted group. What if I want to permanently delete a deleted group?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf689b7-a7c1-121f-578e-029e8a89c4f0
* Version Independent ID: 7e6b449e-bd77-2fc4-2c3d-1f2e364e1b76
* Content: [Archive or delete a team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/archive-or-delete-a-team#feedback)
* Content Source: [Teams/archive-or-delete-a-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/archive-or-delete-a-team.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@adagioajanes  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @adagioajanes, thank you for your feedback.

These are Office 365 groups tasks, please check:
https://docs.microsoft.com/office365/admin/create-groups/restore-deleted-group#permanently-delete-an-office-365-group

**Comment by scanum** [comment]
@adagioajanes Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
