### ISSUE TITLE
Is this a complete solution???

### ISSUE THREAD

**Issue by mniccum** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3955]
Why does Teams need inbound ports open?

What if another user on the machine launches Teams after the script is executed?

What if a new user logs on?

What if it were deployed through ConfigMgr as part of a TS running as SYSTEM?

If ran as part of a logon script, then a user would have to launch Teams and the first call will fail.  The rules are placed after the exe is discovered which would be the next logon.

All the solutions seem like a bandaid.

This is why Microsoft should stop designing apps to install into the user profile.  If Teams installed into Program Files, this would not be an issue.  We asked for an MSI but it only puts the stub setup into Program Files.  This is not what people meant when they asked for an MSI.

WHY IS THIS NOT FIXED?????

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients#feedback)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@mniccum  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@mniccum thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
