### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by cvoigt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3958]
Factory restore link is broken and leads to a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13376c1b-df70-83de-8e6a-8ddc940774b5
* Version Independent ID: 6a2531ee-ac88-ee83-b858-1928d6cb4c65
* Content: [Use the Microsoft Teams Rooms recovery tool - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/recovery-tool#feedback)
* Content Source: [Teams/rooms/recovery-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/recovery-tool.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@cvoigt  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LanaChin** [comment]
Thanks @cvoigt  for bringing this to our attention.  @dariomws306, I've merged your updates. Thanks!
