### ISSUE TITLE
Need information setting up two factor ID for phone.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#396]
How to set up two factor ID for phone?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fb2d20b-cfbf-58e8-f593-ac8dff076cd9
* Version Independent ID: d613df0f-bbb7-b1ae-1b76-6c1355009ebe
* Content: [Configure two-factor authentication in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/manage/authentication/configure)
* Content Source: [Skype/SfbServer/manage/authentication/configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/authentication/configure.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi  @nsshommo thanks for your comments.
Referenced document doesn't exists anymore. Here is another document that specifies which clients are supported for MFA https://docs.microsoft.com/en-us/skypeforbusiness/manage/authentication/two-factor-authentication

hope this information has helped you.

Thanks
