### ISSUE TITLE
Pricing links to 404

### ISSUE THREAD

**Issue by Weishaupt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3960]
The Link to https://products.office.com/skype-for-business/audio-conferencing#Requirements doesn't seem to be valid anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dc121be-72fc-e1c7-628b-b0b293520be2
* Version Independent ID: 678ed844-653d-6ad3-c0f4-341b2f56de9d
* Content: [Audio Conferencing in Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-in-office-365#what-does-it-cost)
* Content Source: [Teams/audio-conferencing-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-in-office-365.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@Weishaupt  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Weishaupt Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
