### ISSUE TITLE
Port status of "manual"

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3961]
Missing from the list of possible port statuses is "manual", I've had this on a couple of ports now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07fd02a2-78ae-519f-ec11-f337debcaf9a
* Version Independent ID: a2a489c3-9204-2b63-85fa-ba9e535fdc94
* Content: [What's the status of your port orders? - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/phone-number-calling-plans/port-order-status)
* Content Source: [Teams/phone-number-calling-plans/port-order-status.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phone-number-calling-plans/port-order-status.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@TorrenManson  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @TorrenManson, thank you for your feedback.

@tonysmit, could you kindly help me te confirm and get more information about this status?

**Comment by tonysmit** [comment]
@TorrenManson - what status?

**Comment by dariomws** [comment]
@tonysmit In the table, I think he says that we should add a new row with the value "manual" in the the first column (Status).

**Comment by TorrenManson** [comment]
The status of “manual” shows up from time to time, and it normally indicates that manual intervention is needed on MSFTs end, I think… but there’s no explanation of this status or what to do if your port ends up in “manual” unexpectedly.

**Comment by dariomws** [comment]
Thank you. Should we close this issue?

**Comment by tonysmit** [comment]
@dariomws - I'm checking with the dev and the PMs. This list is from SFBO and hasn't been validated for Teams. I will get it updated so it includes "Manual". I would suspect, you're right in your assumption that it means the PSTN service desk is needing to get with the carrier, but it's a manual submission or something like that. I created a task so I will follow up on this. For now, let's close this and give me sometime to hear back from them. Cool?

**Comment by dariomws** [comment]
Thank you!

**Comment by Azexl** [comment]
having the ability to cancel the port order when stuck in "Manual Review" would be nice. We have a client porting 3 numbers and the port order has been stuck in "Manual Review" for over a month now. No response from PSTN support team either for the course of that month. 
Adding the Status "Manual Review" to this KB is definitely required as it would allow engineers to point management to some information instead of "Waiting on Microsoft for response"
