### ISSUE TITLE
OneNote Tab is now available in GCC tenants

### ISSUE THREAD

**Issue by jmillerFLND** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3962]
I believe the roll out of Microsoft Apps for Teams, including the OneNote tab is in-process. https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=OneNote%2Cintegration%2Cin%2CTeams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7faee29-6d56-f3bf-766c-6deaefe92e34
* Version Independent ID: 6029b6f8-7d49-6474-fa40-2793000c74a4
* Content: [Plan for Microsoft 365 Government - GCC deployments - Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/plan-for-government-gcc#feedback)
* Content Source: [Teams/plan-for-government-gcc.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-for-government-gcc.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@jmillerFLND  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @jmillerFLND, thank you for your feedback.

Yes, it's not available yet. In the table I can see "On the Government backlog".

**Comment by scanum** [comment]
@jmillerFLND Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
