### ISSUE TITLE
What is coming later in 2018?  Does doc needs to be updated?  Thank you!

### ISSUE THREAD

**Issue by Smartboss88** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3963]
On-premises UM migration scenarios
We support the following scenarios that will enable you to migrate users both to Exchange 2019 and to Cloud Voicemail. Later in 2018 we'll support additional scenarios that will let you migrate from additional versions of Exchange and Skype for Business server. We'll also provide additional features such as Organizational Auto Attendant.

Exchange 2013/Exchange 2016 and Skype for Business Server 2015 to Exchange 2019 and Skype for Business Server 2019
Skype for Business Server 2015 to Skype for Business Server 2019 with Exchange 2013/Exchange 2016

**Comment by scanum** [comment]
@Smartboss88 Could you please link the documentation you are referring to. Thanks!

**Comment by Smartboss88** [comment]
https://docs.microsoft.com/en-us/SkypeForBusiness/hybrid/plan-um-migration

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dariomws306** [comment]
Hi @Smartboss88, thank you for your feedback.

@dstrome could you kindly provide more information about this article? I remove all the reference about features coming later on 2018 as Cloud Auto Attendant is in GA.
Maybe we can add more information about Exchange 2010 or Lync Server 2013?
Thanks!

**Comment by scanum** [comment]
@dstrome Following up on this request. Thanks!

**Comment by dstrome** [comment]
Thanks all for your feedback. We don't have any plans to add Exchange 2010 or Lync 2013-specific content.
