### ISSUE TITLE
6th message

### ISSUE THREAD

**Issue by kisnardonline** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3964]
What happens with the 6th message for E1?  Is it blocked?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca3f7a45-e892-fbb3-baf1-c556fa8e3720
* Version Independent ID: 9c8b63e8-7320-ed8f-e560-ed478009dd57
* Content: [Priority Notifications in Teams Messaging  - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/pri-message#feedback)
* Content Source: [Teams/teams-add-on-licensing/pri-message.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/pri-message.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@kisnardonline thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
