### ISSUE TITLE
Conditional Access - Device Compliance | Add Azure DevOps 

### ISSUE THREAD

**Issue by Don-Fuego2** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3966]
In the section : Issue title	

Behavior / Symptom	
Conditional Access may not work when using the "Website" tab in the desktop app
If a website, such as an intranet portal, has conditional access policies (such as browser or IP address restrictions) then that website may not render as a tab inside of Teams in the desktop app

Please add:
"(such as browser or IP address restrictions **or Device Compliance**)"

Also,for the apps:
Conditional Access may not work when using the "Website" **and Azure DevOps** 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues#feedback)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Don-Fuego2  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Don-Fuego2 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
