### ISSUE TITLE
"Manage availability for a user with a license that includes Teams" is confusing

### ISSUE THREAD

**Issue by ccasas87** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3968]
It's not clear for me this part: 
"When the Teams service plan is turned on, the user can sign in and use Teams. If the service plan is disabled, the user can't sign in and the Teams Exploratory experience isn't available."

Shouldn't it be "... the user can't sign in and the Teams Exploratory experience IS available"? If not it doesn't make sense you provide the instructions below that paragraph to turn off the Teams service plan.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f897ae9b-852a-b617-7de0-d76dbd9f1820
* Version Independent ID: 161b1845-53fd-8912-a5f9-737d3bcdaadc
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-exploratory#feedback)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@ccasas87  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @ccasas87, thank you for your feedback.

I think this sentence is ok as they are not eligible for the Teams Exploratory experience, and this make sense. Why you will enable Teams Exploratory experience if you have a paid Teams license.

Check here:
https://docs.microsoft.com/microsoftteams/teams-exploratory#whos-eligible
"Users who don't have an Office 365 license that includes Teams can initiate the Teams Exploratory experience. For example, if a user has Office 365 Business (which doesn't include Teams), they're eligible for the Teams Exploratory experience."

**Comment by scanum** [comment]
@ccasas87 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
