### ISSUE TITLE
Whats the url for Teams Admin center ?!

### ISSUE THREAD

**Issue by andyjballgit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3973]
cant see it !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b51b67a-d89c-723f-3520-87cb2dc93b90
* Version Independent ID: 78d10cbc-d75b-2b02-d49c-2c3fe1579807
* Content: [Manage teams in the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-teams-in-modern-portal)
* Content Source: [Teams/manage-teams-in-modern-portal.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-teams-in-modern-portal.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@andyjballgit  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@andyjballgit thank you for reaching out and helping improve MS Docs. Please have a look here - https://answers.microsoft.com/msoffice/forum/all/teams-admin-center/35f61cd0-d69e-4db0-a94f-1489b5807f43

**Comment by andyjballgit** [comment]
Hi, 

I get page not found for that link - my point really was , it should be on the page where i logged this issue , i spent a while faffing around trying to find the url and it made me mildly grumpy 

cheers
Andy

**Comment by lindspea** [comment]
@andyjballgit are you on the free version or paid version?  The free version has limitations and does not have access to the Admin Center. Guest access is disabled by default. Here are some articles for reference.https://support.office.com/article/add-guests-to-a-team-in-teams-fccb4fa6-f864-4508-bdde-256e7384a14f?ui=en-US&rs=en-US&ad=US, https://support.office.com/article/differences-between-microsoft-teams-and-microsoft-teams-free-0b69cf39-eb52-49af-b255-60d46fdf8a9c?ui=en-US&rs=en-US&ad=US, https://docs.microsoft.com/en-us/microsoftteams/set-up-guests

**Comment by scanum** [comment]
@andyjballgit Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by ArrowRaider** [comment]
https://admin.teams.microsoft.com/dashboard
