### ISSUE TITLE
No links to the required PS module?

### ISSUE THREAD

**Issue by norman-v** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3975]
The 2 links in this doc and this doc itself does not indicate which module contains Grant-CsTeamsMessagingPolicy. There is a link to the Azure Powershell modules which are not related to Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dfe01e2-b14d-226d-de27-40cb2733a65d
* Version Independent ID: 09477e15-46e1-1a9a-def6-93ef73f24e24
* Content: [PowerShell script sample - Create and assign a messaging policy - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/scripts/powershell-script-teams-messaging-policy-edu#feedback)
* Content Source: [Teams/scripts/powershell-script-teams-messaging-policy-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/scripts/powershell-script-teams-messaging-policy-edu.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@norman-v  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@norman-v Thank you for your feedback. I'm currently investigating this.

**Comment by MarcoCarampanta** [comment]
@scanum I believe this issue can be closed as I just added the requested info to the article.

**Comment by norman-v** [comment]
Not really. The command you are featuring in the sample (Grant-CsTeamsMessagingPolicy) is currently not in the module you are referring to. You should import it to see. I have previously seen this module but did not see the cmdlet then. Also your "more info" links (in 1 hop) to another PS module called LyncOnlineConnector which may be an old version of the SkypeOnlineConnector (Is it one or the other?). I hope you see that it is very hard for us to understand the automation story for Teams. And, unfortunately, the Teams admin portal does not support assigning messaging policies in bulk. It currently doesn't even tell you which groups/users are assigned to a policy.

**Comment by Reeced40** [comment]
@LanaChin Could you please assist

**Comment by bamslib** [comment]
The module to use is Skype: https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-skype-for-business-online-policies-with-office-365-powershell
The Grant-CsTeamsMessagingPolicy is in the skype module: https://docs.microsoft.com/en-us/powershell/module/skype/?view=skype-ps

I have tested this and it worked, however this document should be updated

**Comment by LanaChin** [comment]
@norman-v, @bamslib. Thanks so much for your feedback and helping to improve our docs. The article has been updated to provide more clarity around the cmdlet and the PowerShell module that's needed.  Thank you.
