### ISSUE TITLE
CQD-Power-BI-query-templates - "call queues" and "Auto attendants"?

### ISSUE THREAD

**Issue by markuslosco** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3976]
Very nice idea and good Dashboards. But one questions about the microsoft teams "call queues" with "Auto attendants". I want to create a separate report with filters "second upn" and "total call count" as example for one month but all i get is the error message "index was outside the array. Is querying the "call queues" with "Auto attendants" not supported?

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
