### ISSUE TITLE
Need help installing plug-in for 64 bit Firefox.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#398]
Skype for Business will join meetings if your Firefox browser is 32 bit.  But the web-app installer does not install a plugin for 64 bit Firefox (version 51.01). Please help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ce7a531-5b1f-f404-50a3-58eb285a0a1a
* Version Independent ID: 61d27af3-cfd6-ed7f-102c-072721db0209
* Content: [Plan for Meetings clients (Web App and Meetings App)](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/meetings-clients)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/meetings-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/meetings-clients.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi @nsshommo thanks for your feedback, @yogkumgit can you please redirect him to Support services?

**Comment by kenwith** [comment]
@nsshommo helped me move a bunch of these issues from the old proprietary TechNet feedback system so he wasn't actually the one with the issue. I just wanted to get them in here in case we could capture any knowledge. The original person that opened this long ago solved their problem so will go ahead and close this one out.
