### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by DanBaumgartner** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3980]
Under "Required licenses and permissions" - the link for Licensing Guidance returns a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85a288bc-9192-8c65-4ce9-b5abb260206e
* Version Independent ID: 1f953ea6-e6e5-5e71-d541-3962637f25f9
* Content: [Information barriers in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/information-barriers-in-teams#feedback)
* Content Source: [Teams/information-barriers-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/information-barriers-in-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@DanBaumgartner  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by anwara-ms** [comment]
HI. Any update on this?

**Comment by SerdarSoysal** [comment]
@scanum the correct link should be: https://docs.microsoft.com/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance

**Comment by anwara-ms** [comment]
Hi. This is still not fixed. Could you please tell me what is causing the delay?

**Comment by Reeced40** [comment]
@anwara-ms Hi, we are just waiting for the author to merge the PR and then it will go live.

**Comment by Reeced40** [comment]
@MicrosoftHeidi @scanum Could you please assist.

**Comment by scanum** [comment]
@MicrosoftHeidi @scanum Could you please assist.

**Comment by MicrosoftHeidi** [comment]
This was fixed and has been working for some time now.
