### ISSUE TITLE
Intune enrollment

### ISSUE THREAD

**Issue by mymebenha** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3991]
"If you have Microsoft Intune, devices are automatically enrolled in Intune. After a device is enrolled, device compliance is confirmed and conditional access policies are applied to the device."

Need more information around this because my device did not enroll in Intune automatically like it says.  The device only appears in Teams.  It probably has something to do with existing Intune Conditional Access rules but how do we resolve?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a627b5d-3edc-1add-b921-1dcd49c38653
* Version Independent ID: a2e2bd3a-31c0-471a-05fb-fd64bd942c4a
* Content: [Manage your devices in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/device-management#feedback)
* Content Source: [Teams/device-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/device-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@mymebenha  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@mymebenha thank you for reaching out and helping improve MS Docs. Please have a look at this link and let me know if it helps at all - https://techcommunity.microsoft.com/t5/microsoft-teams-blog/microsoft-teams-ip-phones-and-intune-enrollment/ba-p/330432

**Comment by mymebenha** [comment]
It was my enrollment restrictions causing the problem.  I basically need to allow android device admin enrollment but first add the corporate identifier so I can continue to keep personal devices blocked.  The article should at least be updated to say ....devices are automatically enrolled in Intune depending on your enrollment restrictions and conditional access policies.  Also, if enrollment fails, the device seems to work perfectly fine anyway and can still be managed in Teams so it would be good to list the advantages of having desk phones enrolled in intune.

**Comment by scanum** [comment]
@mymebenha Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
