### ISSUE TITLE
Turn Teams on or off for your entire organization

### ISSUE THREAD

**Issue by Ganym3de** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3995]
It's stated that this is no longer an option for any tenant other than for ones with EDU licensing SKUs. But it's not, it's still available for Worldwide licensing SKU's We recently (needlessly) opened a Microsoft Premier case for an error "You're missing out ask your admin to enable Microsoft teams for &lt;orgname&gt;" where we omited this as a troubleshooting step due to this article and the fix was to revert to the old admin center per the instructions for EDU licensing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5473bf0-ba2d-6c42-d57d-b61af64452d3
* Version Independent ID: 7195478d-3ef4-be8c-2920-3fdba3e70c7e
* Content: [Turn on Microsoft Teams in your Office 365 organization - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/office-365-set-up?source=docs#feedback)
* Content Source: [Teams/Office-365-set-up.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-set-up.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Ganym3de  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Ganym3de thank you for reaching out and helping improve MS Docs. Are you suggesting removing the note at the bottom of the article about tenant-level control?

**Comment by scanum** [comment]
@Ganym3de We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by awf** [comment]
You do not need the original poster's interaction in order to fix this.  The original message is sufficient.  This line needs expanding to include Worldwide Sku: "
The exception to this change is Microsoft Teams for Education (EDU)"
