### ISSUE TITLE
Required for EOL UM?

### ISSUE THREAD

**Issue by jackvdbuk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3996]
HI There,

Can you confirm if these steps are required for on-prem skype 2015 but EOL mailbox users unified messaging/cloud voicemail setup?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4dedc2e-175c-f7df-89d8-db07869c0619
* Version Independent ID: 089ffad2-e85e-3653-fa29-20fc565406ed
* Content: [Configure hybrid connectivity - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/configure-hybrid-connectivity)
* Content Source: [Skype/SfbHybrid/hybrid/configure-hybrid-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-hybrid-connectivity.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by Parroman** [comment]
Hi There, this appears to have nothing to do with CloudVM which this URL is linked to from:

https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-cloud-voicemail

Please confirm the correct information for CloudUM and Skype for Business 2019 configuration with cloudUM. Currently my users can't set their own voicemails since moving to 2019

**Comment by CarolynRowe** [comment]
Are you looking for this topic:  https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/integrate-with-exchange/deployment-overview?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json

**Comment by scanum** [comment]
@jackvdbuk  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jackvdbuk** [comment]
just managed to get this working, requires federation setup as per the guide. all good.
