### ISSUE TITLE
AD FS for authentication

### ISSUE THREAD

**Issue by bfnewman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3997]
The language in this article seems to preclude the use of AD FS or other identity providers for hybrid environments.

"In hybrid environments the account used for Microsoft Teams Rooms must have password [hash] sync enabled in AAD Sync because Microsoft Teams Rooms authentication requires Office 365 authentication."

However, in testing and in discussion my MS TAM/PFE resources, AD FS and at least one other IDP (Ping Federate), seem to function. Could it be clarified here if use of alternate IDPs such as AD FS is supported with Microsoft Teams Rooms accounts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 834f564b-d32a-25ba-437b-1cb74adbf485
* Version Independent ID: 9bdb6864-caa0-d0fa-ce06-eaaa1fd18fe3
* Content: [Configure accounts for Microsoft Teams Rooms - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-configure-accounts#feedback)
* Content Source: [Teams/rooms/rooms-configure-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-configure-accounts.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@bfnewman  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@LanaChin please could you assist.

**Comment by scanum** [comment]
@LanaChin following up on this.

**Comment by LanaChin** [comment]
@sohailita - can you help?  thank you.

**Comment by LanaChin** [comment]
Looking into this

**Comment by LanaChin** [comment]
Hi @bfnewman, thanks for your feedback. I've reached out to the product team and they tell me that there are plans for documentation around AD FS and Microsoft Teams Rooms coming soon.
