### ISSUE TITLE
Need help checking everything is working correctly.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#400]
Would be nice to have ideas on what to check if it does not deploy correctly and does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef2c1711-2096-d9ad-4960-d40004651da1
* Version Independent ID: e3f3154f-7e43-bcc6-3099-65d1ab9ee946
* Content: [(Optional) Verify Response Group deployment in Skype for Business 2015](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-enterprise-voice/optional-verify-response-group-deployment)
* Content Source: [Skype/SfbServer/deploy/deploy-enterprise-voice/optional-verify-response-group-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-enterprise-voice/optional-verify-response-group-deployment.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi @nsshommo thanks for your feedback.
Information on what to do if doesn't work as expected has been added after your comment
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/79cb6c9214f13800c7f024782b22624d87b010ec#diff-f83f910d6fdfc6a621193a0b09afc0f9

Thanks!
