### ISSUE TITLE
Future configuration change

### ISSUE THREAD

**Issue by SergePoint** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4001]
On the top of the page the following text is marked as important: 
"In the future, we're making a configuration change in which the Teams meeting recording feature will be turned on for customers whose Teams data is stored in-country even if Microsoft Stream isn't available in the in-country data residency region"
My understanding is that if this is enabled, if Stream is not available in your country, your tenant will use a location in another country-region, and your data will be stuck in that country and you will not be able to move it back to your country once available, is this the case?

Later in the Important message you say "If your Teams data is stored in-country and you prefer to store meeting recordings in-country, we recommend that you turn off meeting recordings and then turn it on after Microsoft Stream is deployed to your in-country region."  But if someone uses Stream to store a video other than Teams recording, the Stream data will be stored in other country-region anyway, and we will not be able to move it in-Country.  If it's the case, should we completely disable Stream until Stream becomes available in-country?  Not allowing cloud recording would become irrelevent if Stream is open and the Stream content is locked anyway in another country?  Can you pleas confirm?  Sorry for long message:)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording?source=docs#feedback)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@SergePoint Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@tonysmit could you please help clarify?

**Comment by scanum** [comment]
@tonysmit Following up on this. Thanks!

**Comment by tonysmit** [comment]
@sonu-arora - Can you take a look at this and see what we need to do to fix this issue? Thanks!

**Comment by scanum** [comment]
@sonu-arora Any update on this issue? Thanks

**Comment by nomorephones** [comment]
Tony - I think Sonu needs to address this issue.  I don't have any details on how this feature is managed.

**Comment by tonysmit** [comment]
Sent email to @sonu-arora for her to respond.

**Comment by tonysmit** [comment]
@SergePoint - I'm still investigating this issue. I did find the new PM owner and I'm asking him offline about this. Please hold. :) I will report back.

**Comment by tonysmit** [comment]
@ashwinma14 - this is the item that I pinged you about that we need your help on. Thanks!

**Comment by tonysmit** [comment]
Ping @ashwinma14 - this is another one we need help on.

**Comment by tonysmit** [comment]
Update: I'm meeting with the PMs to discuss this.

**Comment by tonysmit** [comment]
@SamChung-MS - Here is one of the issues that I spoke to you about.

**Comment by tonysmit** [comment]
I pinged the PM = @SamChung-MS  in chat.

**Comment by SamChung-MS** [comment]
My understanding is that if this is enabled, if Stream is not available in your country, your tenant will use a location in another country-region, and your data will be stuck in that country and you will not be able to move it back to your country once available, is this the case?
- This is correct.

But if someone uses Stream to store a video other than Teams recording, the Stream data will be stored in other country-region anyway, and we will not be able to move it in-Country. If it's the case, should we completely disable Stream until Stream becomes available in-country? Not allowing cloud recording would become irrelevent if Stream is open and the Stream content is locked anyway in another country? Can you pleas confirm? Sorry for long message:)
- In general, irrespective of what type of data you're trying to store. If all your company's data must be stored in-region, and Stream is not available in your region, you should not send any data to Stream. If you only store Meeting Recordings, then just turn off Teams Meeting Recordings. If you store other data, then you may need to disable stream for the affected users.

**Comment by scanum** [comment]
@SergePoint  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
