### ISSUE TITLE
So... are holds now in place automatically or do I still need to hold mailboxes?

### ISSUE THREAD

**Issue by ii-batman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4004]
This part:
 Note

In Feb 2020, we turned on legal hold or case hold on private channels (private channel chats are stored in user mailboxes, normal channel chats are stored in that Teams’ group mailboxes). If there is already a legal hold in place for a user mailbox, the hold policy will now automatically apply to private channel messages stored in that mailbox. There is no further action needed for an admin to turn this on. Legal hold of files shared in private channels is also supported.

Makes me think that holds are already in place... and it says "There is no further action needed for an admin to turn this on." 

So what is the deal here, can someone confirm please?
Thanks, ii

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0c70e2a-c370-01ae-c46a-3a1d0b95fd61
* Version Independent ID: a3d2b15f-8900-491a-c71a-ab16db108376
* Content: [Place a Microsoft Teams user or team on legal hold - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/legal-hold#feedback)
* Content Source: [Teams/legal-hold.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/legal-hold.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@ii-batman Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by ii-batman** [comment]
@scanum 
Hi - Do you have an update on this one? :)
Thanks, II

**Comment by lindspea** [comment]
@ii-batman thank you for reaching out and helping improve MS Docs. From what I've investigated it seems like no further action is needed. I see the article was also just updated this week, but will ask @MicrosoftHeidi to confirm as well that no further action is needed for putting mailboxes on hold.

**Comment by ii-batman** [comment]
How's it @lindspea ?
Thanks for looking into this, I am eager to enable my users to be able to edit/delete posts but I need to be sure that all posting is hold for compliance. Looking forward to your confirmation.

**Comment by lindspea** [comment]
@MicrosoftHeidi

**Comment by markjjo** [comment]
@ii-batman The note you cite in the article states that content in private channels will be preserved if the corresponding mailbox is placed on eDiscovery hold. So, if a mailbox/site was on legal hold prior to Feb 2020, the private channel content will be preserved after this new capability was deployed. But if you have mailboxes/sites that are not currently on eDiscovery hold, you would have to place them on hold to preserve content in private channels. In other words the "no further action" bit applies to mailboxes/sites currently on eDiscovery hold. Does that help to answer your question?

**Comment by scanum** [comment]
@ii-batman We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by ii-batman** [comment]
@scanum Hi Manuella, does not make sense to close the call if I dont reply within 3 days if you guys don't reply within the same time.
I hope you address the text on the document and its proper confusing!
Stay safe
Regards
