### ISSUE TITLE
Pls validate this statement

### ISSUE THREAD

**Issue by rickleye** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4005]
To use Microsoft Phone System with Teams, users must be in TeamsOnly mode. 
I have 2 user on 2 different tenants - set for Island mode in which i can place phone calls from both Teams/Skype for Business. Now when I get a call, It appears that the Skype End point gets the call. Is this what you mean that to use MS Phone System users must be in TeamsOnly mode ?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49921e8a-55ac-f547-d4e2-d329f5089c2e
* Version Independent ID: 91c3433a-3684-95cd-3426-4a5877b33106
* Content: [Migration and interoperability guidance for organizations using Teams together with Skype for Business - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/migration-interop-guidance-for-teams-with-skype#feedback)
* Content Source: [Teams/migration-interop-guidance-for-teams-with-skype.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/migration-interop-guidance-for-teams-with-skype.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@rickleye Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@rickleye Thank you for your feedback. Please let me know if this link helps at all. - https://docs.microsoft.com/powershell/module/skype/get-csteamsupgradepolicy?view=skype-ps

**Comment by scanum** [comment]
@rickleye We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
