### ISSUE TITLE
Allow Pin apps - not working

### ISSUE THREAD

**Issue by Patel1984** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4006]
The Team apps setup policy has 'Allow user pinning' set to ON, which is a presumption that users are allowed to pin apps. 

However we have had a few issues around this where users pin an app e.g. Planner or OneNote and it successfully pins the app in the pane but after a few minutes the user receives the following message - "Your admin has updated your settings. Some of your pinned apps may have moved." and the app unpins from the pane. 

This is quite frustrating as the policy do as it reads. 

Is this a bug or is there something that is overwriting the setting..? Do we have to add OneNote to the Pinned apps section below this setting in the policy..?

**Comment by scanum** [comment]
@Patel1984 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
