### ISSUE TITLE
Please update to reflect new Teams Meeting Room License SKU

### ISSUE THREAD

**Issue by annerajb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4009]
There is a new Teams Meeting Room SKU
The documents make no mention of it and makes reference to old versions of the licenses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-office-365)
* Content Source: [Teams/rooms/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-office-365.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@annerajb Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@annerajb Thank you for reaching out and helping improve MS Docs. Are you referring to this link - https://docs.microsoft.com/MicrosoftTeams/rooms/rooms-licensing ?

**Comment by annerajb** [comment]
Correct it's mentioned in the first paragraph roughly bullet 3.

But throught the document / page it keeps mentioning the old skype for
business licenses.
Could it be updated to also mention the Rooms License in addition to the
Legacy licenses.

**Comment by lindspea** [comment]
@LanaChin can this information be added to the article?

**Comment by lindspea** [comment]
@annerajb thank you for clearing that up? Do you have the relevant links for the licenses you are referring to?  I see the Rooms License is already in the article.

**Comment by scanum** [comment]
@annerajb We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
