### ISSUE TITLE
Need more detailed information.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#401]
Looking for something that actually tells where to get the local configuration store or how to make the connection to the SQL server would be helpful. Maybe even some common error type scenarios or similar would be more helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c502e60c-2f7b-e90a-4d73-02962f08d4b2
* Version Independent ID: afff1bfb-eb35-b861-146a-0deb2d4d8927
* Content: [Install Local Configuration Store](https://docs.microsoft.com/en-us/skypeforbusiness/help-topics/help-depwiz/install-local-configuration-store)
* Content Source: [Skype/SfbServer/help-topics/help-depwiz/install-local-configuration-store.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/help-topics/help-depwiz/install-local-configuration-store.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi @nsshommo thanks for your feedback.
The LCS or Local Configuration Store it's a read only copy of the CMS or Central Management Store that is hosted in another server or pool.
Skype For Business Deployment Wizard will automatically retrieve this information from AD and CMS.
The goal of this specific document is not to show common errors or how the connection is performed, but to mention the specific procedure you must follow when you install LCS through Deployment Wizard.
For more information there are other documents in docs that might respond to your questions.
Thanks!
