### ISSUE TITLE
Setting up Surface but can't get a Windows 10 Enterprise license

### ISSUE THREAD

**Issue by thomsenhub** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4010]
I have talked to what seems like every department at Microsoft about getting a Windows 10 Enterprise license in order to configure the Surface per the instructions, but cannot get a standalone license. The minimum purchase is 5 licenses via the volume licensing. 

It appears small businesses cannot set up a console device piece by piece but must purchase it all together through a third party vendor. Can anyone confirm that?

**Comment by scanum** [comment]
@thomsenhub thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by thomsenhub** [comment]
@scanum yep tried that on all fronts. Called, entered tickets etc. Just very surprised SMB's potentially cannot take advantage of something like the console without having volume licensing.
