### ISSUE TITLE
Puerto Rico

### ISSUE THREAD

**Issue by ryanruark** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4011]
Hello - Puerto Rico is part of the United States and is not a separate sovereignty. I recommend you update this document to use the phrase 'United States (including Puerto Rico)' instead of 'United States (and Puerto Rico).'

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1778d5e3-1cd3-9323-d7f0-6ee14aa69f24
* Version Independent ID: 66402fb0-4a46-65af-91ac-caa9a3d60a1f
* Content: [Phone number management for the U.S. - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/manage-phone-numbers-for-your-organization/phone-number-management-for-the-u-s?source=docs#feedback)
* Content Source: [Teams/manage-phone-numbers-for-your-organization/phone-number-management-for-the-u-s.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-phone-numbers-for-your-organization/phone-number-management-for-the-u-s.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@ryanruark Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@scanum this can be close thank you.

**Comment by scanum** [comment]
@ryanruark 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
