### ISSUE TITLE
Manage Apps is missing

### ISSUE THREAD

**Issue by Craig-Humphrey** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4012]
I'm a global admin (and a Teams Service Admin), but I don't get the Manage Apps menu item in the Team Admin Centre.
I have Permission policies and Setup policies, but no Manage Apps.
Am I missing something somewhere?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbcabee-fa96-2878-e983-3c966f84ee15
* Version Independent ID: 02fa4fd8-77e0-5cb2-a4af-576cbb68322f
* Content: [Manage your apps in the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-nz/MicrosoftTeams/manage-apps#feedback)
* Content Source: [Teams/manage-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-apps.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Craig-Humphrey Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Craig-Humphrey thank you for reaching out. Please have a look at this article and let me know if it helps - https://docs.microsoft.com/microsoftteams/teams-app-permission-policies

**Comment by Craig-Humphrey** [comment]
Thanks @lindspea, no, that relates to Teams apps -> Permission Policies menu item, in Teams Admin.

I was after the Teams apps -> Manage apps.

However, it has now appeared on the menu for both the tenants I admin.
I wonder if it just took longer to roll out to the Australian O365 tenants...

You can close this ticket and check with the other two similar tickets...
