### ISSUE TITLE
Manage Apps is missing

### ISSUE THREAD

**Issue by flcev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4013]
Manage Apps is missing. 
Where can you manage what apps are deployed automatically? Setup policies mention pinned apps, but does a pinned app also mean that it is automatically installed for all users that have the policy, or does it just state the order?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbcabee-fa96-2878-e983-3c966f84ee15
* Version Independent ID: 02fa4fd8-77e0-5cb2-a4af-576cbb68322f
* Content: [Manage your apps in the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-apps#feedback)
* Content Source: [Teams/manage-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-apps.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@flcev  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @flcev, thank you for your feedback.

When you pin an app using a Setup Policy, they are installed automatically. In this way, it forces the appearance in Teams clients.

**Comment by scanum** [comment]
@flcev We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
