### ISSUE TITLE
Microsoft Teams - React-icons missing in WebView

### ISSUE THREAD

**Issue by KaaNee** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4014]
Since a few days, the "react" icons are missing in the webview of microsoft teams, and "reaction" can't be used - the link to react is also missing.
Many of my colleagues have this issue with different OS/Browsers.

<img width="242" alt="grafik" src="https://user-images.githubusercontent.com/3414703/75139407-d5f38b80-56ec-11ea-8538-aaf27d49927d.png">

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
