### ISSUE TITLE
Hybrid communication flows

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4015]
It would be great to have some communication flows for Hybrid scenarios.
e.g. Teams client uses EWS to gather data from Exchange OnPrem mailbox

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact#feedback)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@trudolf-msft  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @trudolf-msft, thank you for your feedback.

@dstrome could you kindly help with this issue? Does the Calendar Tab use EWS? Thanks!

**Comment by dstrome** [comment]
hi @trudolf-msft - Thanks for the feedback. We don't document developer scenarios in this content. Please see https://docs.microsoft.com/en-us/microsoftteams/platform/ for developer content. thanks.

**Comment by trudolf-msft** [comment]
Thanks for your response. It's not a question for devs but network admin which ports are needed (ExO Hybrid scenario).
