### ISSUE TITLE
Name of step 7 

### ISSUE THREAD

**Issue by paul-lange** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4016]
The name of step 7 is misleading in my opinion. It should be something like "Create a voice route for an analog device" 
A voice route is not assigned to an analog device. There is no object in Teams for the analog device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea0bc170-d9d9-c17a-adc8-d37cb5fe3df5
* Version Independent ID: 3c761043-bea5-0cfb-d85e-13671ed0fe9a
* Content: [Direct Routing - Connecting analog devices - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-analog-devices#feedback)
* Content Source: [Teams/direct-routing-analog-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-analog-devices.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@paul-lange  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by CarolynRowe** [comment]
Thanks for the feedback. I've made the change, which will go live today. Closing this issue.
