### ISSUE TITLE
Tenant Dial Plans

### ISSUE THREAD

**Issue by Sezotove** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4018]
I've been working with Support for close to 6+months now on deploying this correctly and I'm now being told that we must use Tenant Dial Plans. Is this the case? Can we get clarification on this and perhaps some extra info on using those? I've checked the Translate Phone Numbers page and I don't believe this answers my questions or confirms for me what support is saying.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d277994f-f0bb-ed3b-a94c-460c7f033abf
* Version Independent ID: 7a2b1511-a35a-18e4-611a-db0093d034b4
* Content: [Configure voice routing for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-voice-routing)
* Content Source: [Teams/direct-routing-voice-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-voice-routing.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by Sezotove** [comment]
Maybe I should elaborate, perhaps they're not needed but as I'm trying to setup 911 and international calling, I'm being instructed to do so via TenantDialPlans and support seems to believe this is the only way to do it.

**Comment by scanum** [comment]
@Sezotove  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by RobMac-really** [comment]
@Sezotove, are you talking direct routing or Calling plans?  Basically nothing in the GUI of teams admin center has anything to do with Direct Routing.  Everything is configured from a powershell session.

Calling plans will utilize the same routes defined in this guide if you apply them to the user, but the dial plans in the gui seem to only apply to calling plans.

hope this helps, reach out if you need direct routing help as I'm mid deployment

**Comment by CarolynRowe** [comment]
So, just to clarify, you can use the Teams admin center to specify emergency call routing policies for Direct Routing,  See https://docs.microsoft.com/en-us/MicrosoftTeams/manage-emergency-call-routing-policies and https://docs.microsoft.com/en-us/MicrosoftTeams/what-are-emergency-locations-addresses-and-call-routing

**Comment by scanum** [comment]
@Sezotove We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
