### ISSUE TITLE
Update Installer Links

### ISSUE THREAD

**Issue by JAK1047** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4019]
I see Machine Wide Installer Teams is already up to version 1.3.00.4155 and can be downloaded from https://statics.teams.cdn.office.net/production-windows-x64/1.3.00.4155/Teams_windows_x64.msi but the links here still point to https://statics.teams.cdn.office.net/production-windows-x64/1.2.00.32462/Teams_windows_x64.msi which was the November version. Can we get the links updated or point to an active CDN with the latest?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi#feedback)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@JAK1047  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by JAK1047** [comment]
I've noticed that all the installers above 1.2.00.32462 give an install error of "Cannot install for all users when a VDI environment is not detected" which used to occur from ”HKEY_LOCAL_MACHINE\SOFTWARE\VMware, Inc.\VMware VDM\Agent” not existing, but this seems to have changed. There's also the URL to download from the main Teams page by specifying managedInstaller=true if that's perhaps a better link.

https://teams.microsoft.com/downloads/desktopurl?env=production&plat=windows&download=true&managedInstaller=true&arch=x64

**Comment by kpropell** [comment]
JAK1047: I also experienced this with the new versions on VDI image with Horizon Agent installed. I tried to add the Citrix registry key entry, and now it installs, so they probably changed the MSI installer to requrie this key also:
HKEY_LOCAL_MACHINE\SOFTWARE\Citrix\PortICA

**Comment by dariomws** [comment]
Hi @JAK1047, thank you for your feedback.

@LanaChin Could you help me to confirm this? What URL should we put in the article?

https://statics.teams.cdn.office.net/production-windows-x64/1.3.00.3564/Teams_windows_x64.msi
or
https://teams.microsoft.com/downloads/desktopurl?env=production&plat=windows&arch=x64&managedInstaller=true&download=true

(same for 32 bits)

I think the second URL is a better option so you always download the latest version.

**Comment by LanaChin** [comment]
Looking into this.

**Comment by LanaChin** [comment]
Hi @JAK1047  - Thanks for your feedback and helping us improve our docs.  Both the installer links are now updated (to 1.300.4461).  FYI @dariomws .
