### ISSUE TITLE
Need help on MAC OS.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#402]
Skype meetings app running on MAC OS, unable to see the desktop the meeting starter is sharing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ce7a531-5b1f-f404-50a3-58eb285a0a1a
* Version Independent ID: 61d27af3-cfd6-ed7f-102c-072721db0209
* Content: [Plan for Meetings clients (Web App and Meetings App)](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/meetings-clients)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/meetings-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/meetings-clients.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@nsshommo I have consulted with the PM for this and it's advised that if you are still having this desktop issue with Mac OS then to contact your helpdesk for assistance.
