### ISSUE TITLE
[Microsoft teams] visitor couldn't see teams message in iphone 13.3.1

### ISSUE THREAD

**Issue by Lijiaoa** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4020]
I'm a visitor in teams. Manager put me to a XXX teams. I could see messages in windows but couldn't see anything in my Iphone. my phone's system is 13.3.1. It's a bug?

**Comment by scanum** [comment]
@Lijiaoa thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
