### ISSUE TITLE
search is not content search

### ISSUE THREAD

**Issue by DanStevensonMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4021]
For most Teams users and admins, when they talk about "search" in Teams, they mean searching for chat messages and files inside the Teams client. That is not the same as "Content Search", which is a compliance feature.  They often get confused about the Exchange dependency because in the old Skype for Business world, message search was based on a folder on Exchange.  That is 100% false for Teams, but sometimes people are confused about Exchange dependency and message search.

It would be helpful to clarify the part in this doc (very last bullet above) that discusses searching for messages - to clarify that search for messages in Teams has no Exchange dependency, never ever, and that content search is different. When the doc says "content from chat messages" it is unclear as to whether that means message search or compliance content search.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/exchange-teams-interact#feedback)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@DanStevensonMSFT  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @DanStevensonMSFT, thank you for your feedback.

I have added the word "compliance" to let the reader knows that this bullet is related to compliance search. According to the link provided, I understand this.

**Comment by scanum** [comment]
@DanStevensonMSFT Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
