### ISSUE TITLE
Is 1080p 30fps really supported?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4022]
Hi,
You wrote:
"

> But where bandwidth is not a concern, experiences can be optimized for quality, including up to 1080p video resolution, up to 30fps for video and 15fps for content, and high-fidelity audio

"
Correct me if I'm wrong, but I have not heard yet that Teams supports Full HD (1080p) on video meetings, except on screen/application sharing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e8b2651-40bb-0d26-6126-d88689047f23
* Version Independent ID: 5be83c7d-ef7f-5582-4a6c-f0709fb2ec7b
* Content: [Prepare your network for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/upgrade-prepare-environment-prepare-network)
* Content Source: [Teams/upgrade-prepare-environment-prepare-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-prepare-environment-prepare-network.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Petri-X  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Petri-X, thank you for your feedback.

I understand it's supported. There are more articles which mention 1080p:
https://docs.microsoft.com/microsoftteams/prepare-network#bandwidth-requirements
https://docs.microsoft.com/microsoftteams/platform/bots/calls-and-meetings/real-time-media-concepts#video-format

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
