### ISSUE TITLE
New-CsBatchPolicyAssignmentOperation not available yet?

### ISSUE THREAD

**Issue by thomasbinder** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4024]
I just installed the latest "Skype for Business Online PowerShell module" but it seems the cmdlet "New-CsBatchPolicyAssignmentOperation" is not included yet. Any idea how I can use the new cmdlet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e53b353e-fe89-00f1-e0c9-7c597dd38eb7
* Version Independent ID: 5a4c9e41-a0f4-f523-83c0-c612499a02fb
* Content: [Assign policies to your users in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/assign-policies?source=docs)
* Content Source: [Teams/assign-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@thomasbinder thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by MichaelLaMontagne** [comment]
The Invoke-CsBatchPolicyAssignment is showing in the MicrosoftTeams PowerShell module but documentation is lacking.

**Comment by dinocaputo** [comment]
As of today the docs define the New-CsBatchPolicyAssignmentOperation Teams cmdlet but its missing from multiple tenants I have access to.  I do see Get-CsBatchPolicyAssignmentOperation and Invoke-CsBatchPolicyAssignment.  The Invoke-CsBatchPolicyAssignment is not defined anywhere in docs.
