### ISSUE TITLE
But is there an option for External Dialing prefix?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4025]
Hi,

You are writing:

> You can specify an external access prefix of up to four characters (#, *, and 0-9) **if users need** to dial one or more additional leading digits (for example, 9) to get an external line.

But on the Admin portal the External Access Prefix is a mandatory, so in my mind you cannot say "if user..." as it seems to be a mandatory, which is a bit strange.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 847c0505-3441-b5db-1f81-c7759bffd1e3
* Version Independent ID: 3c6b3820-349f-caf5-c510-a771a3b7a770
* Content: [What are dial plans? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/what-are-dial-plans?source=docs)
* Content Source: [Teams/what-are-dial-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-dial-plans.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Petri-X  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Petri-X, thank you for your feedback.

I tried to create a Dial Plan just adding the name ("Test") and I could save it. I understand that External Access Prefix is not mandatory.

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
