### ISSUE TITLE
Error while running the SkypeRoomProvisioningScript.ps1

### ISSUE THREAD

**Issue by BurgerhoutJ** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4026]
When I run this script and choose for option 4, I'm getting the following error.

CaptureSkypeCreds : The term 'CaptureSkypeCreds' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Temp\TeamsRoomProvisioningScript.ps1:940 char:7
+       CaptureSkypeCreds
+       ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (CaptureSkypeCreds:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Please help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee417633-3d52-646b-2ef0-94f71535db75
* Version Independent ID: 527bb7f0-b4a7-108c-6f86-8fadced63b86
* Content: [Deploy Microsoft Teams Rooms with Exchange Online - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-exchange-online)
* Content Source: [Teams/rooms/with-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-exchange-online.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@BurgerhoutJ thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
