### ISSUE TITLE
Link to 'Pricing for Audio Conferencing' returns a 404

### ISSUE THREAD

**Issue by netresults-scott** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4027]
The link for Pricing (https://products.office.com/skype-for-business/audio-conferencing#Requirements ) dead-ends at a 404. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c6c2e6-a1c7-dd0c-dbe3-0072497282d5
* Version Independent ID: 1b09ca3d-f45e-5540-40b4-8c3b7176fc81
* Content: [Try or purchase Audio Conferencing in Office 365 for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/try-or-purchase-audio-conferencing-in-office-365-for-teams)
* Content Source: [Teams/try-or-purchase-audio-conferencing-in-office-365-for-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/try-or-purchase-audio-conferencing-in-office-365-for-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@netresults-scott  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @netresults-scott, thank you for your feedback.

It's working for me, could you try it again? Thanks!

**Comment by netresults-scott** [comment]
@dariomws The link no longer ends in a 404 for me, however I'm not sure if the 'current' page it links too is the most appropriate.

The link on the docs page is titled: Pricing for Audio Conferencing.

The link then takes you thru to a fairly unclear 'Transform online meetings with Microsoft Teams' page (https://products.office.com/en-ca/microsoft-teams/online-meeting-solutions?rtc=1#customerstoryregion2)

The issue is that the first obvious link (See Plans and Pricing) doesn't really provide the requested into - its actually much further down the page under the 'Pricing for Audio Conferencing' section. Is there some way to direct link to that section instead?

**Comment by dariomws** [comment]
@netresults-scott I understand your concern but unfortunately, there is no direct link to get this section.

**Comment by scanum** [comment]
@netresults-scott Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
