### ISSUE TITLE
Private Teams channel SharePoint Site - SharingPolicy

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4028]
In my dev tenant, I disabled Guest Access for group-connected SharePoint Sites by default via PowerShell, i.e. for Microsoft Teams and its SharePoint TeamSites as well:
```powershell
$settings = Get-AzureADDirectorySetting | where-object {$_.displayname -eq “Group.Unified”}
$settings.Values

Name                          Value                               
----                          -----                                                  
AllowGuestsToBeGroupOwner     False                               
AllowGuestsToAccessGroups     True                                
AllowToAddGuests              False                               
```

Furthermore, I created a alert policy to send alerts if the SharingPolicy settings of a SharePoint site have been changed. An excerpt of the alert policy information are stated below:

> Activity:Changed a sharing policy
> Detail:
> More information
> EventSource:SharePoint
> ItemType:Site
> ModifiedProperties:
> ```json
> [
>   {
>     "Name": "AllowGuestUserSignIn",
>     "NewValue": "Enabled",
>     "OldValue": "Disabled"
>   }
> ]
> ```
> Operation:SharingPolicyChanged
Workload:SharePoint

When I create a new private Teams channel, the created SharePoint Site with template ID "**TEAMCHANNEL#0**" changes the SharingPolicy settings. 
It **does not inherit the Teams / group-connected Site SharingPolicy settings**, but **inherits the tenant default sharing settings**, where allowed guest access.

This is not the intended behavior.

How can I prevent this behavior?
How can I inherit the group-connected SharePoint site's (Teams group) SharingPolicy settings for any private Teams channel as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Markus-Hanisch thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
