### ISSUE TITLE
Save meeting recordings to a channel

### ISSUE THREAD

**Issue by LotusPainter** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4032]
By default, meeting recordings are not put in any channel. Is it possible to change the default channel the recording is put into at creation? I don't want to have to manually move the location after the fact.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams#feedback)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@LotusPainter  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @LotusPainter, thank you for your feedback.

I understand there is no way to change meeting recording location. There are your options:
https://support.office.com/article/play-and-share-a-meeting-recording-in-teams-7d7e5dc5-9ae4-4b94-8589-27496037e8fa

**Comment by scanum** [comment]
@LotusPainter Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
