### ISSUE TITLE
confusing points

### ISSUE THREAD

**Issue by DanStevensonMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4033]
1) It is unclear if a user needs a Teams license to attend (view) a Live Event if the event is set to company only or specific people/groups. The text talks about license requirements for "participate" which is not the same as "produce" or "attend"

2) the doc uses the Microsoft internal jargon term GoLocal. there are standard ways of describing Microsoft data centers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-live-events/plan-for-teams-live-events#feedback)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@DanStevensonMSFT  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @DanStevensonMSFT, thank you for your feedback.

@chuckedmonson could you kindly help me to confirm the license requierements to watch/attend live events? Should we also remove any mention to "Go Local"?

Thanks!

**Comment by chuckedmonson** [comment]
@dariomws - Please contact the PM Ashwin Appiah for answers to your questions. Thank you.

**Comment by cichur** [comment]
@darionws I've fixed the mentions of Go Local and published the revision. Cindy

**Comment by dariomws** [comment]
Thank you @cichur!

What about the license requirements? Could you double-check it?

**Comment by cichur** [comment]
Hi @darionws I added this notation in the section Who can attend, create, and schedule live events.
Anyone can attend a live event without a license. Read Admin quick start - Meetings and live events.
The Admin quick start guide has a table that lists the licenses.

**Comment by Giraffaman** [comment]
Hi everyone - we are still confused about who needs to be assigned a Teams-license if we want to let authenticated guest users to join our live event as presenter/producer (production will be in Teams only). Does the external company need to assign a Teams license to the users presenting at our event, or do we have to assign one of our licenses to them since we invite the guest user?
Both this document and the admin quick start guide mention that a Teams license is needed for producers/presenter - however, it is not clear which side needs to provide that license.

Thank you very much in advance.

**Comment by dariomws** [comment]
Hi @Giraffaman,

I think you need a license in the Tenant where the live event will be located.

@cichur could you kindly confirm? Thanks!

**Comment by cichur** [comment]
Hi @dariomws and @Giraffaman :
I received this explanation from a fellow writer.:
This is a bit complicated. So Guest users aren't authenticated other than with their email alias. So, they can't use the internal company to authenticate the external credentials to "sign in", so they won't be able to "sign in" to the internal org. This means that to fit one of those roles for Live Events, they would have to have an account in the internal org. There different ways to do this: 1 - Sign them up for a full account in the internal org and have them login with those creds and assign them a Teams license. 2 -   Set up ADFS (Federation) for setting up a trust between the internal org and the external org and then the external org would assign a Teams license.

**Comment by Giraffaman** [comment]
@cichur  thank you for the quick and detailed explanation. This would confirm what @dariomws  said and what we were expecting. Makes sense.
What confuses me is that we were just in the middle of setting up an internal account for a guest presenter at our live event and, before we sent them the credentials to their new account, they were able to join a test event as presenter with their own (presumably licensed) Teams-account. There is also no federation trust between our organizations at the time.

Therefore, can I assume that an external user with their own Teams-license already qualifies as "authenticated user" and can therefore be invited via the menu "invite presenters" when creating a live event?

**Comment by scanum** [comment]
@Giraffaman thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
