### ISSUE TITLE
Route calls out from tenant possible?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4035]
Hi,
On here: "**When the maximum number of calls is reached**" there is only two options:
- Disconnect
- Redirect to a) Person in your company b) Voice application

Is it really so, it is not possible to route call out from the tenant? That would be helpful when other customer management services are in use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b755d9ae-13ac-019f-f5f4-a95b1eee2989
* Version Independent ID: f7afd8ad-e6e0-6c79-aed1-4ee87d48ba12
* Content: [Create a call queue - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue)
* Content Source: [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-call-queue.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Petri-X  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Petri-X, thank you for your feedback.

I confirm that these are the options in the Admin Center when you create or modify call queues. If you want to suggest this feature please go to:
https://microsoftteams.uservoice.com/

Thanks again!

**Comment by Petri-X** [comment]
Hi Dariomws,
Thank you for confirming this. I could then send DCR to get change for that.

User voice is waste of time and energy. Especially in cases like this.
