### ISSUE TITLE
Allow dial-in users to bypass the lobby does not work

### ISSUE THREAD

**Issue by StephanGee** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4036]
I activated this setting in the global policy to smooth our migration from Skype for Business last week.
But it does not work as expected. If "true" all dial in participants are still in the lobby.

Also the description seems to be wrong - on "false" - everyone can join directly?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Verwalten von Besprechungsrichtlinien - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/meeting-policies-in-teams#feedback)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@StephanGee  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by bendoty** [comment]
I can confirm these same issues.  The only way to modify this is on a meeting-by-meeting basis through Meeting Options.

**Comment by fpdean-github** [comment]
Same issue and the meeting-by-meeting workaround mentioned by bendoty worked. Less than ideal though, hopefully this can be fixed soon

**Comment by dariomws** [comment]
@StephanGee Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by StephanGee** [comment]
My company decided to change autoadmit to "Everyone" so this issue is solved for me
