### ISSUE TITLE
Conditional Access may not work when using the "Website" or "Azure DevOps" tab in the desktop app - timeline to fix

### ISSUE THREAD

**Issue by blyakhmanv** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4037]
When this issue which was reported 7/1/18 is going to be fixed? because of this issue we can't use apps in the Teams. 
Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues?source=docs#feedback)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@blyakhmanv  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by blyakhmanv** [comment]
Please provide an update. Looks like a lot of people waiting for resolution of this issue.
Thank you,

**Comment by dariomws** [comment]
Hi @blyakhmanv, thank you for your feedback.

It's the same as https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3856, please follow up this issue, hope we have a answer soon.

**Comment by scanum** [comment]
@blyakhmanv A better place to request this change to Teams functionality is Teams UserVoice:
https://microsoftteams.uservoice.com/

The Teams product group monitors issues logged in UserVoice. Requests that get high votes are weighted heavily in prioritization for upcoming feature work.
