### ISSUE TITLE
Restricted Team Creation

### ISSUE THREAD

**Issue by dotnick365** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4038]
Can we clarify in this article how creation of private channels will interact where organizations have restricted creation of Team/O365-Groups/SP-Sites? Will that also impact creation of private channels?

It is clear that you can restrict creation of private channels using the above methods, but not clear if the private channel creation policy also inherits from the Group/Team/Site creation policy options in the tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e0ac38-cfff-8d8f-5345-2ae93a9fae2e
* Version Independent ID: bec44289-e9fa-4464-1601-0ca86d61e6ca
* Content: [Manage the life cycle of private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels-life-cycle-management#feedback)
* Content Source: [Teams/private-channels-life-cycle-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels-life-cycle-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@dotnick365  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @dotnick365, thank you for your feedback.

They are two different things. If you prevent users to create Teams using this process:
https://docs.microsoft.com/microsoft-365/admin/create-groups/manage-creation-of-groups
They can create Private Channels if you don't prevent it using this process:
https://docs.microsoft.com/microsoftteams/private-channels-life-cycle-management#set-whether-team-members-can-create-private-channels

About SharePoint there is a note here:
https://docs.microsoft.com/sharepoint/manage-site-creation

**Comment by scanum** [comment]
@dotnick365 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
