### ISSUE TITLE
Need updated information about "Identity Spoofing."

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#404]
While the section entitled "Identity spoofing (IP address spoofing)" specifically outlines IP based spoofing, a note should be included for "non-savvy" readers that Skype for business does not have any protections in place to prevent/protect against identity spoofing that merely involves traditional caller ID spoofing. I've been able to verify that placing a call to an SfB number with a spoofed caller ID consisting of another SfB number (from the same organization) will successfully result in the spoofed number's SfB contact info being displayed on the recipient's device (desk phone, SfB desktop client and SfB mobile app).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96ceafbb-d3ce-6e1f-4a90-f54de0053a86
* Version Independent ID: e18a9aa7-c86e-1c69-0bff-daf5a56e77f6
* Content: [Common security threats in modern day computing](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/security/common-threats)
* Content Source: [Skype/SfbServer/plan-your-deployment/security/common-threats.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/security/common-threats.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by nsshommo** [comment]
Thanks for your reply. Please let me know if there is any update regarding this issue.

**Comment by dariomws306** [comment]
Hi @nsshommo,

What I think is that the test you did was through a SIP Trunk configured in Skype for Business, am I right?

Thank you!

**Comment by AndreaBarr** [comment]
@nsshommo We have had the Spoofing information investigated and updated. Please let us know if this resolves the spoofing issue you were seeing. I am going to close this issue. If the update to the article doesn't resolve this issue please re-open this issue.
