### ISSUE TITLE
Release notes for the Teams device app

### ISSUE THREAD

**Issue by rgsteele** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4042]
I'd like to see release notes for the Android app that runs on the Teams devices, so we know what the latest version is, when each version was released, what has changed, and if there are any known issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a627b5d-3edc-1add-b921-1dcd49c38653
* Version Independent ID: a2e2bd3a-31c0-471a-05fb-fd64bd942c4a
* Content: [Manage your devices in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/device-management)
* Content Source: [Teams/device-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/device-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@rgsteele Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by rgsteele** [comment]
Thanks @scanum. I've found some release notes [here](https://support.office.com/en-us/article/what-s-new-in-microsoft-teams-d7092a6d-c896-424c-b362-a472d5f105de?ns=MSFTTEAMS&version=16&ui=en-US&rs=en-US&ad=US#PickTab=Desk_phones), but only the most recent version is listed (1449/1.0.94.2020020601). I currently have one Teams device (a Poly CCX 500) running 1449/1.0.94.2019110802, but the admin console shows the device status is "Up to date". I don't know whether this is a bug or if the update is being intentionally held back, so more details about the release process would be helpful.

**Comment by scanum** [comment]
@rgsteele thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
