### ISSUE TITLE
Partners certified for Teams doesn't include Azure?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4043]
So, only Citrix can support Teams on VDI?  What about Azure with Windows Virtual Desktop? I would think that Microsoft would 'certify' its own products.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi#known-issues-and-limitations)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Canis-Lupis Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@Canis-Lupis Since Teams [is included](https://docs.microsoft.com/en-us/deployoffice/teams-install) in Office ProPlus, and [Office Pro Plus is supported on Windows Virtual Desktop](https://www.microsoft.com/en-us/microsoft-365/blog/2019/09/30/windows-virtual-desktop-generally-available-worldwide/), i would say that Teams is supported on Windows Virtual Desktop.

> In the past, Microsoft Teams was a separate installation from Office 365 ProPlus. But starting with Version 1902, Teams is included as part of new installations of Office 365 ProPlus.

**Comment by scanum** [comment]
@Canis-Lupis Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
