### ISSUE TITLE
Maximum number of Teams a user can be a member of?

### ISSUE THREAD

**Issue by DanBaumgartner** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4044]
I haven't found anything about a maximum number of O365 Groups a single user can be an owner of. Would this be the same as the maximum number a single user can create or is there no actual limit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@DanBaumgartner Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@DanBaumgartner In the title you ask about the maximum number of Teams a user can be a member of. That's 1000 acording to [this article](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams).

There is no public limit specified about the maximum number of Office 365 groups a single user can be an owner of. Keeping in mind that a user can be promoted to owner if he's a member of a Team and that there is a limit of 500,000 Teams in an Office 365 tenant, i would assume that's the limit, but then again it should not be something anybody should reach anytime soon.

Are you in a scenario where this limitation could play a role? You could also [reach out to Team support](https://support.office.com/en-us/home/contact?contactUsExperienceEntryPointAssetId=S.HP.teams) and ask this question.

**Comment by scanum** [comment]
@DanBaumgartner Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
