### ISSUE TITLE
Conference Bridges no longer exist

### ISSUE THREAD

**Issue by ucgeek** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4047]
Meetings &gt; Conference Bridges doesn't appear to exist anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07eca314-7a40-c7ee-1d31-7a858adff741
* Version Independent ID: dede6892-d7e3-d44d-f8f6-eb4bd50c07f0
* Content: [Turn on or off entry and exit announcements for meetings in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/turn-on-or-off-entry-and-exit-announcements-for-meetings-in-teams#feedback)
* Content Source: [Teams/turn-on-or-off-entry-and-exit-announcements-for-meetings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/turn-on-or-off-entry-and-exit-announcements-for-meetings-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@ucgeek Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@ucgeek I checked in my tenant and the settings are still there. Are you seeing something different?

![image](https://user-images.githubusercontent.com/41186174/76688327-69f1ac80-6634-11ea-8cb4-c008e3709cd5.png)

**Comment by ucgeek** [comment]
I don't have access to the customer tenant I was originally looking for it in. However, I do see it in another tenant. Not sure how I could have missed it!! Consider it closed, thanks for taking a look.

**Comment by mmrvelj** [comment]
I don't see Conference Bridges as well. Like most of the instructions, this one is outdated at least for some users. 

![image](https://user-images.githubusercontent.com/4729588/135858321-bcc379d9-cb57-4e22-b26a-4751f773b381.png)
