### ISSUE TITLE
Microsoft Teams - unable to send invitation to gmx email accounts

### ISSUE THREAD

**Issue by 7gegenTheben** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4049]
I was trying to create a small Team in teams. One of the members I wanted to add as guests was having a gmx.net email account. She didn't receive an invitation email. I opened an email account at gmx.de to test whether this is actually true. Then I tried to send my new email address an invitation. This did not work either.

I'd wish for a possibility to send invitations to gmx users. If that is not possible, then I would like to see some sort of warning in teams that gmx email addresses do not work.

**Comment by scanum** [comment]
@7gegenTheben Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@7gegenTheben thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
