### ISSUE TITLE
Need clarification about command.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#405]
The following command needs clarification:

New-CsTrustedApplicationPool -id <Pool FQDN> -Registrar <Pool Registrar FQDN> -site Site:<Pool Site>   

Here, pool fqdn - can this be any name, is it supposed to be the SfB f/e pool? or Registrar?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e97f81b-dfc0-6b20-fb06-4addeface54b
* Version Independent ID: 830ab805-b0a2-41a4-42a6-ee248ae1bacb
* Content: [Deploy the SEFAUtil tool in Skype for Business 2015](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-enterprise-voice/deploy-the-sefautil-tool)
* Content Source: [Skype/SfbServer/deploy/deploy-enterprise-voice/deploy-the-sefautil-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-enterprise-voice/deploy-the-sefautil-tool.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by SharS** [comment]
Thank you for this feedback and for contributing to the wellness of the content! This is a good idea and we have added it into our backlog for triage and prioritization.

**Comment by AndreaBarr** [comment]
@tseward Is investigating this.

**Comment by get-itips** [comment]
Hi @nsshommo thank you for your feedback.
Clarifications about Pool FQDN had been added after you wrote this comment https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/920a35b7fcf12ee97d6dd68f89e284ca45e74168#diff-df6a3e33f95194a3833afb87b6c29867

Thank You
