### ISSUE TITLE
tables are corrupted in localized version of this page

### ISSUE THREAD

**Issue by ikukoyoneda** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4050]
[フィードバックをこちらに入力してください]
all tables in this page (JPN version) are corrupted. Please see the attached PDFs (Japanese version and English version). 
[Microsoft Teams の制限事項と仕様.pdf](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/files/4260185/Microsoft.Teams.pdf)
[Limits and specifications for Microsoft Teams - Microsoft Teams _ Microsoft Docs.pdf](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/files/4260188/Limits.and.specifications.for.Microsoft.Teams.-.Microsoft.Teams._.Microsoft.Docs.pdf)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Microsoft Teams の制限事項と仕様 - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/limits-specifications-teams?source=docs)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**
[Microsoft Teams の制限事項と仕様.pdf](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/files/4260189/Microsoft.Teams.pdf)
[Limits and specifications for Microsoft Teams - Microsoft Teams _ Microsoft Docs.pdf](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/files/4260190/Limits.and.specifications.for.Microsoft.Teams.-.Microsoft.Teams._.Microsoft.Docs.pdf)

**Comment by scanum** [comment]
@officeglobal Could you please help on this issue? Thanks!

**Comment by scanum** [comment]
@ikukoyoneda Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by OfficeGlobal** [comment]
@ikukoyoneda , @scanum the article was re-published, tables are displayed with scrollbar

![image](https://user-images.githubusercontent.com/47977325/75779866-bd254e80-5d5a-11ea-9d87-ae4995e43898.png)

**Comment by scanum** [comment]
@ikukoyoneda Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
