### ISSUE TITLE
Some browser can't do screen sharing, camera

### ISSUE THREAD

**Issue by narismadz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4052]
https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#browsers 

I've tested on my chrome

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99361a9a-edf3-c477-9bba-82a1462d60d8
* Version Independent ID: 407bf24e-e7a0-f2e7-d80f-ea609f80a040
* Content: [Microsoft Teams meetings on unsupported browsers - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/unsupported-browsers#feedback)
* Content Source: [Teams/unsupported-browsers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/unsupported-browsers.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by narismadz** [comment]
My typo " Some browsers CAN do screen sharing, camera "

**Comment by scanum** [comment]
@narismadz Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LanaChin** [comment]
Merged. Closing issue. Thank you.
