### ISSUE TITLE
Basic architecture looks not so clear

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4057]
Hi,
When looking for the "Basic Architecture" diagram that confuse a bit. Where on that picture is O365/Teams? Citrix had a picture on here:
[Call establishment and media flow paths](https://docs.citrix.com/en-us/citrix-virtual-apps-desktops/multimedia/opt-ms-teams.html#call-establishment-and-media-flow-paths) (see architecture a bit later)
But they have also replaced Teams components by "Azure.."

So it would be great if you could share a bit more details architecture picture which components contacts into which Teams components.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hello @Petri-X 

Thank you for reaching out.

For more details on this topic, please refer to the following documentation. 

https://docs.citrix.com/citrix-virtual-apps-desktops/multimedia/opt-ms-teams.html

Hope this helps. Thank you!

**Comment by scanum** [comment]
@Petri-X thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
