### ISSUE TITLE
Link to Pricing for Audioconferencing is broken

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4058]
This link https://products.office.com/skype-for-business/audio-conferencing#Requirements redirects to https://products.office.com/en-us/404-error-page?aspxerrorpath=/skype-for-business/audio-conferencing#Requirements

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fac515b-9c6b-c70c-330e-53557dc23fd2
* Version Independent ID: d515841e-f412-286d-1a97-30507bb50040
* Content: [Audio Conferencing pay-per-minute - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-pay-per-minute)
* Content Source: [Teams/audio-conferencing-pay-per-minute.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-pay-per-minute.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @Larryngolog 

Thank you for reaching out!

We see that the links are working fine on our end. Could you please recheck and let us know if you still see this issue on your end. 

Thank you so much for your patience. Looking forward to your response. Thank you!

**Comment by v-chwebb** [comment]
Could someone please clarify the statement about 'pay-per-minute' licenses and Communication Credits licensing? The 1st reference mentions having licensing assigned for each user, and the 2nd reference mentions 'no CommCredit' licenses need be assigned for Pay-per-min'  (possibly, meaning only the 'pay-per-min' licenses need assigned for each user, thus a restructure of the sentence should end with info about 'CommCredits for org')?  
Thank you.

**Comment by v-chwebb** [comment]
"…Pay-per-minute requires a license assigned to each user, and for your organization to have Communications Credits enabled, in order for Audio Conferencing to work…"

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
