### ISSUE TITLE
Bad Link for Pricing for Audio Conferencing

### ISSUE THREAD

**Issue by aamillerMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4059]
Pricing for Audio Conferencing points to https://products.office.com/skype-for-business/audio-conferencing#Requirements which results in a 404 response.

The new URL is here. https://products.office.com/en-us/microsoft-teams/online-meeting-solutions#customerstoryregion2 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b07cfcf-8f31-91ed-b1de-c7826a1ab91d
* Version Independent ID: dfbc4212-8f47-326a-f872-8186a915ae1e
* Content: [Country and region availability for Audio Conferencing and Calling Plans - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans?toc=/skypeforbusiness/toc.json&bc=/skypeforbusiness/breadcrumb/toc.json)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@aamillerMSFT Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @aamillerMSFT 

Thank you for reaching out!

We see that the links are working fine on our end. Could you please recheck and let us know if you still see this issue on your end.

Thank you so much for your patience. Looking forward to your response. Thank you!

**Comment by aamillerMSFT** [comment]
they look good now. thanks.
