### ISSUE TITLE
Manage Apps is missing

### ISSUE THREAD

**Issue by techmastermike** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4063]
Manage Apps is missing in the Teams Dashboard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbcabee-fa96-2878-e983-3c966f84ee15
* Version Independent ID: 02fa4fd8-77e0-5cb2-a4af-576cbb68322f
* Content: [Manage your apps in the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-apps)
* Content Source: [Teams/manage-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-apps.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@techmastermike Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @MaxiPigna 

Thank you for reaching out!

As per the following roadmap document, we should be able to see this feature by now. Could you please recheck and let us know your feedback. 

https://www.microsoft.com/microsoft-365/roadmap?filters=Microsoft%20Teams&searchterms=manage%2Capps

Looking forward to your response. Thank you!

**Comment by scanum** [comment]
@techmastermike thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
