### ISSUE TITLE
Can we add the excluded list for Mac OS

### ISSUE THREAD

**Issue by rickleye** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4066]
Could we include the excluded list for Mac OS systems. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3021fe9-1d0a-71ce-0748-41b9630c2bd7
* Version Independent ID: f8ac6ebb-a648-f364-73cb-5d69c8b19eef
* Content: [Teams files and folders to exclude from antivirus scanning - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-files-folders-antivirus-perf)
* Content Source: [Teams/teams-files-folders-antivirus-perf.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-files-folders-antivirus-perf.md)
* Service: **msteams**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@rickleye Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @rickleye 

Thank you for reaching out!

This doesn't apply to the Mac OS systems. 

Hope this clarifies. Thank you!

**Comment by rickleye** [comment]
Okay. Noted. Could a Note be included on the article as such.

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by scanum** [comment]
@rickleye thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
