### ISSUE TITLE
Staffhub has been replaced by Shifts

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4067]
https://support.office.com/en-us/article/Getting-started-with-Microsoft-StaffHub-92e9480f-0a37-47d2-ac96-2d11ee5f0656

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f897ae9b-852a-b617-7de0-d76dbd9f1820
* Version Independent ID: 161b1845-53fd-8912-a5f9-737d3bcdaadc
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-exploratory)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@teomonda thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by teomonda** [comment]
Hello Manuela,
my point is the product was retired so it is not accurate to have it in the documentation of a product launched recently. Basically I think Staffhub should be renamed to Shifts or removed whatsoever.

**Comment by ichkoj** [comment]
@scanum honestly whats your purpose here? Do you actually get paid to do that?
