### ISSUE TITLE
Cannot re-install Teams with the system-wide msi after uninstalling

### ISSUE THREAD

**Issue by rejohnson76** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4068]
If a user uninstalls Teams after it was installed with the MSI and we then uninstall for each profile as well as delete all the %localappdata%\Microsoft\Teams\ folders, a re-install of the MSI does not do anything.  There is no desktop icon, no references to Teams in Start, no way to run Teams.  So far the only way to recover is to install the standalone executable (via SCCM or Teams website).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Microsoft Teams using MSI via Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/msi-deployment#clean-up-and-redeployment-procedure)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@rejohnson76 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by rejohnson76** [comment]
Thanks.  I’ve opened case:  ‎Cannot get Teams re-installed after uninstalling MSI version‎ (#‎19001411‎)

-Russell

**Comment by Redguytoo** [comment]
From my own experience, if you install the MSI, you should uninstall the MSI first, this will place the uninstall command "Update.exe --uninstall --msiUninstall --source=default" from %localappdata% in the HKLM Run key, so after a restart this uninstall command will clean up the application itself. Running "Update --uninstall --source=default" only, will most likely place this key: [HKEY_CURRENT_USER\Software\Microsoft\Office\Teams] "PreventInstallationFromMsi"="1", causing a rerun of the MSI to not actually installing the application anymore.

**Comment by rejohnson76** [comment]
Marvin,

You are a genius!  The key was to uninstall the machine-wide msi, restart the computer and let the HKLM Run key remove the app.  I still need work out a method in SCCM to delete that pesky HKCU key that might be there.  I tried changing it to “0” but that didn’t work; it must be deleted, it seems.  Maybe someone at MS knows another value that would disable the prevent function?  We could easily use group policy or ActiveSetup to change the key to allow re-installation.

Thanks,
russell johnson
IT System Administrator
phone 503-537-2880
[1A-dec_email_logo]
[cid:image002.png@01D5F3B6.6D0FB100]<https://www.facebook.com/pages/A-dec-Inc/140726736103468>   [cid:image003.png@01D5F3B6.6D0FB100] <https://twitter.com/AdecDental>    [cid:image004.png@01D5F3B6.6D0FB100] <https://www.youtube.com/user/AdecDentalEquip>    [cid:image005.png@01D5F3B6.6D0FB100] <https://www.linkedin.com/company/a-dec>    [cid:image006.png@01D5F3B6.6D0FB100] <https://www.pinterest.com/adecdental/>
