### ISSUE TITLE
Why can't we hide Org-Wide member changes from General?

### ISSUE THREAD

**Issue by cradixus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4069]
Certainly, we aren't the only company who doesn't want the name & date of every person we terminate being disseminated to the entire company?  In our industry it's equally important that names of people we're in the process of rush onboarding be kept confidential until it's a 100% done deal.  That being said, how/why is there not an option after all this time to disable broadcasting this information in an Org-Wide team?  It makes sense for small, private Teams, but none whatsoever for very large teams.  Does anyone else have this problem?  I found a couple UserVoice's but they are dormant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team#feedback)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@cradixus thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
