### ISSUE TITLE
Phonetic spelling for User Names

### ISSUE THREAD

**Issue by DanBremner** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4070]
This article recommends phonetic spelling for text entered for the text-to-speech engine to read. My question is for the confirmation prompt on dial-by-name or other places, either "I think you said John Smith, is that right?" or "Transferring to John Smith." For our users, obviously we can't spell their names phonetically in the First & Last name fields. Can we spell them phonetically in some hidden field that will be used to pronounce the name correctly? Or are some users just destined to have their names mispronounced by our phone system forevermore?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74845604-00ca-b195-4781-80efa6be29a3
* Version Independent ID: bd22e545-c3ec-f7c6-ccfa-76c16c14ecc6
* Content: [Use the Getting Started wizard to set up Business Voice - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/business-voice/use-getting-started-wizard#feedback)
* Content Source: [Teams/business-voice/use-getting-started-wizard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/business-voice/use-getting-started-wizard.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dstrome** [comment]
hi @DanBremner - I'm fairly certain the answer is no. However, I'm double checking with the product team to see if there's a user property that might allow phonetic spelling and whether Teams uses it.

**Comment by dstrome** [comment]
hi @DanBremner - unfortunately the answer to this appears to be no, we don't have a way to specify phonetic spelling of names in this way. You may want to post a suggestion to the Teams UserVoice site here - https://microsoftteams.uservoice.com/
