### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by Eillirand** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4071]
Does this send any kind of notification to the end user when setup? We are in process of rolling out Teams and would like this as part of the rollout but do not want any type of notifications sent to the end user at this point? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team#feedback)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by HenrikDamslund** [comment]
I have tested this, and no notifications are send. Nice :-)

**Comment by scanum** [comment]
@Eillirand thank you for submitting feedback. Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
