### ISSUE TITLE
Clarify how to use Union Function in CQD

### ISSUE THREAD

**Issue by StainlessSteele** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4072]
The method to use the "Union function" described here https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/call-quality-dashboard/use#what-does-union-do is not clear. By putting 1 piece of common text into multiple filter fields, thereby you force an "or" to happen on those sets vs the default of each filter in the list being an "and" type. 
For example, if I want to have a filter for classified poor, or rated poor, I would put 1 piece of matching text in both of those filters in the Union field of the filter.

**Comment by scanum** [comment]
@StainlessSteele Hi! Thanks for submitting feedback. Could you please link the article you would like this content to be included on? Thanks.

**Comment by StainlessSteele** [comment]
This page https://docs.microsoft.com/en-us/skypeforbusiness/management-tools/call-quality-dashboard/use#what-does-union-do However, the content there should also be merged and updated here https://docs.microsoft.com/en-us/microsoftteams/turning-on-and-using-call-quality-dashboard

**Comment by Reeced40** [comment]
@StainlessSteele Thank for reaching out. The second article was updated in the interim recently, please confirm.

**Comment by scanum** [comment]
@StainlessSteele We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by ChocoMilkWithoutSugar** [comment]
here you will find more information

https://youtu.be/2CiBBmnnEaQ?t=1309

Minute 21:49
