### ISSUE TITLE
Can't change existing public team to org-wide

### ISSUE THREAD

**Issue by MellowYellow85** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4073]
This implies I can change my public team to an org-wide (and stop folks from leaving it) but there doesn't seem to be the option in the Edit Team page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team#feedback)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by MellowYellow85** [comment]
or add a new org-wide one. It's just an option yet, I guess.

**Comment by MellowYellow85** [comment]
nm, it's a permissions thing

**Comment by scanum** [comment]
@MellowYellow85 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by timmernet** [comment]
@MellowYellow85, could you elaborate on the required permissions? We seem to run into the same issue. Account is Global Admin, but no option to create a new Org-wide Team or upgrade an existing Public Team.

**Comment by MellowYellow85** [comment]
Oh, that's a bummer. I was under the impression that this would be available under global admin rights, which is the only role/permission I don't have. 

Bummed to hear that your global admin can't see it either.

**Comment by timmernet** [comment]
Quick update on my personal issue, I got it working. It took 24h to sync
new global admin role to my account. After that the option to create
org-wide team was available

Op za 14 mrt. 2020 04:07 schreef MellowYellow85 <notifications@github.com>:

**Comment by MellowYellow85** [comment]
Thanks, I guess that answers that. I need to get global admin rights... which I'm not sure I want. Seems excessive. If you're a Teams admin, you should have this.
