### ISSUE TITLE
Incorrect statement

### ISSUE THREAD

**Issue by ivanja81** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4077]
"There's no way to change the system language for only one person in your organization. You can only change the greeting language for everyone on your organization."

You can change it via  Set-CsOnlineVoicemailUserSettings  just fine.

**Comment by scanum** [comment]
@ivanja81 Could you please link the article you are referring to? Thanks!

**Comment by scanum** [comment]
@ivanja81 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
