### ISSUE TITLE
Clarification on Teams Auto Attendant support with Lync server

### ISSUE THREAD

**Issue by rajkumardas2701** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4078]
Hello Team,

Could you please confirm if Teams Auto Attendant is supported with Lync server as mentioned in the article or just with SFB 2015/2019.

Article states below,
 "Cloud auto attendants can be configured with Skype for Business Server 2019, 2015, and 2013."

**Comment by scanum** [comment]
@rajkumardas2701 Could you please link the article you are referring to? Thanks!

**Comment by rajkumardas2701** [comment]
https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-cloud-auto-attendant

**Comment by sowjanya365** [comment]
Hi @rajkumardas2701 

Thank you for reaching out!

Yes, as mentioned in the article cloud auto attendants can be configured with Skype for Business Server 2019, 2015, and 2013.

Hope this clarifies your query. Thank you!

**Comment by scanum** [comment]
@rajkumardas2701 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
