### ISSUE TITLE
Need Clarification on Cloud AA support with Lync server deployment

### ISSUE THREAD

**Issue by rajkumardas2701** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4079]
Hello Team,

Could you please confirm if Cloud AA is supported with Lync server 2013 as per the requirement statement mentioned in the article. If not, please update the article accordingly.

"Cloud auto attendants can be configured with Skype for Business Server 2019, 2015, and 2013."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d3bc9d7-fd9e-be9f-1c46-1cc16a5c0789
* Version Independent ID: a6a46add-33de-d3b9-0169-64b642562191
* Content: [Plan a Cloud auto attendant - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-cloud-auto-attendant#feedback)
* Content Source: [Skype/SfbHybrid/hybrid/plan-cloud-auto-attendant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/plan-cloud-auto-attendant.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@rajkumardas2701 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by gautam0107** [comment]
@scanum, Please help us to confirm whether Cloud AA is supported with Lync server 2013 or not. Waiting for your response.

**Comment by dariomws** [comment]
Hi @rajkumardas2701, thank you for your feedback.

@CarolynRowe @jambirk could you kindly help to confirm? Thanks!

**Comment by dstrome** [comment]
Yes, Lync 2013 is supported.
