### ISSUE TITLE
Plugin vdi

### ISSUE THREAD

**Issue by Snec1990** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#408]
Добрый день! При установленном плагине пропадает возможность записи презентации (Просто отсутствует кнопка "Начать запись"). При удаленном плагине кнопка появляется, но пропадает доступ к вебкамере. Как решить данную проблему? Заранее благодарю!

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 515a2310-9d3d-d056-0996-dea9c9427d12
* Version Independent ID: eb81761a-d223-7849-855e-2b8ec9140f9a
* Content: [Развертывание подключаемого модуля VDI для Lync в Skype для бизнеса Server 2015](https://docs.microsoft.com/ru-ru/skypeforbusiness/deploy/deploy-clients/deploy-the-lync-vdi-plug-in#feedback)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/deploy-the-lync-vdi-plug-in.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.ru-RU/blob/live-sxs/Skype/SfbServer/deploy/deploy-clients/deploy-the-lync-vdi-plug-in.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Translates to : 

Good afternoon! When the plugin is installed, the ability to record the presentation disappears (simply there is no "start recording " button). When the plugin is removed, the button appears, but the access to the webcam disappears. How do I solve this problem? Thank you in advance!

**Comment by krishra85** [comment]
Hi Snec1990,

Recording is not available while using the VDI plug-in for Skype for Business - this is a known limitation.

However, I am not sure why the access to the webcam disappears after the plugin is removed. Does Skype for Business recognize if the webcam is plugged in again?

Thanks,

Krishnan

**Comment by jambirk** [comment]
Known Issues for VDI are listed in https://docs.microsoft.com/en-us/SkypeForBusiness/plan-your-deployment/clients-and-devices/vdi-environments#known-feature-limitations
