### ISSUE TITLE
Teams Exploratory Licence

### ISSUE THREAD

**Issue by munkiemanUK** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4080]
This appears to be only for 100 users but the Commercial Cloud it is replacing was unlimited, how to i add the remaining users who don't have a licence and the company cannot afford to pay for.  Can the 100 be extended to be unlimited?

**Comment by scanum** [comment]
@munkiemanUK thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
