### ISSUE TITLE
Missing Browser List

### ISSUE THREAD

**Issue by AlexSchwerzmann** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4085]
Hi
I'm not sure, but the list of mentioned browser does not seem to be complete. In our tests, Edge did not work either...

Could you please create a list of supported browser instead of an incomplete one of non-supported? Would be easier for us to give clear recomendations to customers.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce30163-6327-899b-281d-d4ef982fce5e
* Version Independent ID: e61dcbb8-4877-ef6f-1987-981cdd7fc82f
* Content: [Configure desktop sharing in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/configure-desktop-sharing)
* Content Source: [Teams/configure-desktop-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/configure-desktop-sharing.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **Lolaj**

**Comment by scanum** [comment]
@AlexSchwerzmann Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @AlexSchwerzmann 

Thank you for reaching out!

Kindly refer to the following article for the supported browsers. 

https://support.microsoft.com/en-us/office/use-teams-on-the-web-33f84aa9-2e8b-47ac-8676-02033454e385?ui=en-us&rs=en-us&ad=us

Thank you!

**Comment by scanum** [comment]
@AlexSchwerzmann thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
