### ISSUE TITLE
Change request on the article

### ISSUE THREAD

**Issue by v-45venk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#409]
Enable-CsMeetingRoom -Identity $rm -RegistrarPool "sippoolbl20a04.infra.lync.com" -SipAddressType EmailAddress
Run The above mentioned CMDlet after you have licensed the account for SfB Plan 2. 
I think that the product behavior has changed because we are not able to run Enable-CsMeetingRoom on an unlicensed account. 
Also on the workflow presented on the diagram in this article needs to change. The step "Enable account in SfB Pool" should be after "Assign SfB online license via control panel". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d310a567-17ea-3581-2d0c-88f5ad7e9233
* Version Independent ID: 0af94ec5-fa79-5e7d-c931-13adb192ac4d
* Content: [Provisioning Skype Room System accounts in Office 365](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/provisioning-skype-room-system-accounts-in-office-365)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/provisioning-skype-room-system-accounts-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/provisioning-skype-room-system-accounts-in-office-365.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Just to clarify: are you provisioning an SRS v1 or SRS v2 device? If SRS v2 you are looking at the wrong procedure.

**Comment by v-45venk** [comment]
Hi there!

It is in general. You cannot run enable-csmeetingroom on an account that is not licensed for SfB Online. I saw that the article changed accordingly. So, thank you!


Kind regards,

Ventsislav Karaivanov

Microsoft Office 365 Skype for Business Online Subject Matter Expert
Email: v-45venk@microsoft.com<mailto:v-45venk@microsoft.com>

[MSFT_logo_png][4150_Ofc365_Orng166_D_rgb]

Office main: https://www.office.com/
Office support: https://support.office.com/
Interested in joining an Office 365 Support Webcast? -: https://blogs.technet.microsoft.com/o365support/

Manager:
Orsolya Antal
v-45orsa2@microsoft.com<mailto:v-45orsa2@microsoft.com>

Note: This email may contain confidential information. If you are not named on the addressee list, please take no action in relation to this email, do not open any attachment and please contact the sender (details above) immediately
