### ISSUE TITLE
Cloud voicemail runs only in split domain configuration but there is a line in this doc that might bring confusion.

### ISSUE THREAD

**Issue by Emsabare** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4091]
Line "**If you have an on-premises only deployment—that is, only Exchange and Skype for Business on-premises servers—but you want to take advantage of Cloud Voicemail, you will not need additional licenses.**" might create confusion as in customer might think that you don't need to run a split domain / hybrid deployment. It is mentioned 3 paragraphs above that hybrid is required, but when you say "on-premises only deployment" it tends to create the fake idea that you can have CVM also without hybrid when in fact you need to configure a split domain infrastructure and at least one tenant user (maybe Global admin) to be licensed for phone system in order to provision Business Voice Directory for the tenant.

I would see after "on-premises only deployment" a mention similar to: "while having a split domain configured".
Thank you.

**Comment by scanum** [comment]
@Emsabare thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Emsabare** [comment]
Hi,

Thank you for your suggestion, indeed this would have been a right thing to do, if I would have been a customer “confused” about he documentation.
Thing is, I am MSFT employee, Support Escalation Engineer in Teams and Skype for Business team and this ambiguous requirement has been noticed in the specific doc without actually being impacted in any production environment.

Thank you,
Emanuel
