### ISSUE TITLE
ATA

### ISSUE THREAD

**Issue by tmaheshwar** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4092]
This page mentions ATA-1 certification, what does that mean, can we register directly ATA-1 to Microsoft cloud without Audiocodes SBC in between; please confirm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1a1c01-10a9-7f69-1c7b-1a566b0f5112
* Version Independent ID: 329ee759-40fc-98fb-b91e-87786c63024b
* Content: [List of Session Border Controllers certified for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-US/MicrosoftTeams/direct-routing-border-controllers?source=docs#feedback)
* Content Source: [Teams/direct-routing-border-controllers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-border-controllers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@tmaheshwar Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by ndambrosio** [comment]
@tmaheshwar The ATA would be connected via SBC, see the following article for more detail:
**[How to use analog devices with Phone System Direct Routing](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-analog-devices)**

**Comment by scanum** [comment]
@tmaheshwar Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
