### ISSUE TITLE
Incorrect PowerShell cmdlets

### ISSUE THREAD

**Issue by gabsto-ms** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4094]
In the section https://docs.microsoft.com/en-gb/MicrosoftTeams/retention-policies#using-powershell, all the PowerShell cmdlets are incorrect.
You need to remove the string  &lt;Teams&gt; for all the referenced cmdlets.
Example:
"New-TeamsRetentionCompliancePolicy" should be "New-RetentionCompliancePolicy"

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f55c52a5-5841-b9c9-1607-2013dc3f2e20
* Version Independent ID: 16d93458-5e01-646f-dac5-31306cc7f3fb
* Content: [Retention policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-gb/MicrosoftTeams/retention-policies#using-powershell)
* Content Source: [Teams/retention-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/retention-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@gabsto-ms Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by markjjo** [comment]
@gabsto-ms Thanks for the heads up. We have updated these cmdlets per your feedback.
