### ISSUE TITLE
About active user

### ISSUE THREAD

**Issue by moegitree** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4099]
I have a team with over 1400 members and analytics tab shows the activity user count in last day is 1000+.
I am the owner of the team and I'm sure the number of user who has ever performed "intentional action" in this team is far less than 1000. So I have 2 questions:
    1. Is reading message (with no reply) counted as "Intentional action"?
    When viewing a team's Analytics tab, the number showed in "activity user"
   2. is determined only by its users' action in this specific team, is that correct?
Need to be clarified in the article.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3c93d512-6e5a-09c7-1c9f-c7eeb94555da
* Version Independent ID: f289f914-6b58-6c29-8997-a2fbd017ffe7
* Content: [Teams でチーム間およびチーム別分析を表示する - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/teams-analytics-and-reports/cross-team-per-team-analytics)
* Content Source: [Teams/teams-analytics-and-reports/cross-team-per-team-analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/cross-team-per-team-analytics.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@moegitree thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
