### ISSUE TITLE
Unable to give user Montreal area phone number

### ISSUE THREAD

**Issue by chrisingraham00** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4101]
We have a remote user and we are unable to use their address as it says there is not an area code available.  This is the Greater Montreal area.  Any idea why this is happening?

**Comment by scanum** [comment]
@chrisingraham00 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
