### ISSUE TITLE
Unable to get area codes from the following locations

### ISSUE THREAD

**Issue by chrisingraham00** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4102]
Saskatoon
Montreal
St John's Newfoundland
Port Stanley Ontario (London area)

All of these remote users we have are unable to get an area code in teams.  Please advise this is a real problem for our organisation.

**Comment by scanum** [comment]
@chrisingraham00 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
