### ISSUE TITLE
Trial and 30 day grace period over - we can still use the service

### ISSUE THREAD

**Issue by Pa8dy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4104]
We received notification that the trial would end more than one month ago however our users can still log in and there appear to be no ill effects from the end of of the trial period? 

Also am I right in assuming that once the 12 months is up we cannot move on to the new Exploratory trial experience?

**Comment by scanum** [comment]
@Pa8dy thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
