### ISSUE TITLE
Link to 'Network Readiness Assessment' is pointing to the old SoF portal

### ISSUE THREAD

**Issue by DrLippert** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4107]
Link to 'Network Readiness Assessment' is pointing to the old SoF portal, should be updated to live documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e8b2651-40bb-0d26-6126-d88689047f23
* Version Independent ID: 5be83c7d-ef7f-5582-4a6c-f0709fb2ec7b
* Content: [Prepare your network for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/upgrade-prepare-environment-prepare-network#feedback)
* Content Source: [Teams/upgrade-prepare-environment-prepare-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-prepare-environment-prepare-network.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@DrLippert Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @scanum 

Good Day!

Could you please let the document owner know that the link to "Network Readiness Assessment"(https://go.microsoft.com/fwlink/?linkid=855800) doesn't work. 

Thank you!

**Comment by algalakt** [comment]
hello colleagues, same query here - the link to Network Readiness Assessment does not work (https://www.skypeoperationsframework.com/Offers?pageState=NetworkReadiness). I have seen that it was under the investigation a month ago, is there any ETA yet? Thank you

**Comment by scanum** [comment]
@LanaChin Hi Lana! The link to "Network Readiness Assessment"(https://go.microsoft.com/fwlink/?linkid=855800) doesn't work. Could you please aid with next steps? Thanks!

**Comment by LanaChin** [comment]
Hi @DrLippert, @sowjanya365, and @algalakt  - The topic is deprecated and replaced by https://docs.microsoft.com/microsoftteams/prepare-network. Thank you.
