### ISSUE TITLE
Manage Team

### ISSUE THREAD

**Issue by dailywake** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4111]
Hi, We are school have Teachers and Students, i try found permission option to not let the students or teachers to create team . can please assisst.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20423b44-629b-1bee-280c-fb55680cd33e
* Version Independent ID: a60f6a48-89d7-98b6-4245-4be171fd06fd
* Content: [Assign team owners and members in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/assign-roles-permissions#feedback)
* Content Source: [Teams/assign-roles-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-roles-permissions.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@dailywake thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
