### ISSUE TITLE
Download still goes to previous version

### ISSUE THREAD

**Issue by patrichard** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4112]
I'm still getting 4.3.33.0 when downloading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1365f9b8-001c-daa7-592e-d88b9bb3a10e
* Version Independent ID: ffba1b4d-1f19-4dac-0b55-053d98fe26b7
* Content: [Release notes - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-release-note#43420-03022020)
* Content Source: [Teams/rooms/rooms-release-note.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-release-note.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@patrichard Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @patrichard, thank you for your feedback.

Are you still experiencing this issue? Could you provide the link?

Thanks!

**Comment by scanum** [comment]
@patrichard We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by goretz2** [comment]
@patichard hello. how to download 4.4.41? I have an issue with two Teams Rooms devices: HP Elite Slice G2 and Lenovo smarthub 500. Thank you

**Comment by dariomws** [comment]
Hi @goretz2, please check this article:
https://docs.microsoft.com/microsoftteams/rooms/console

**Comment by goretz2** [comment]
hi, @dariomws . Yes I saw this article. What precisely I have to do? create usb stick and perform full installation? Is it the only way to update MTR verision? When I have versions before 4.3. I just downloaded SRS deployment kit, installed it and run a script in repair mode. after it MTR was updated.
P.S. I am looking for update because I have a problem with black screen at the second monitor which appears when I start to call to someone.

**Comment by dariomws** [comment]
@goretz2 I have verified the script and it download the MSI from this URL:
https://go.microsoft.com/fwlink/?linkid=851168
But you will get 4.3.42.0 version. Give me some time I will try to get more information. In the meantime, if you have some urgency, please open a support ticket.
If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products

**Comment by goretz2** [comment]
thank you @dariomws I will wait for your answer here because I haven't rights to create support ticket.

**Comment by goretz2** [comment]
hi, @dariomws also I found that my colleagues from Germany used MTR 4.2.4.0 at the same equipment and they haven't any problems. they shared me the srsdeploymenttoolkit 4.2.4.0 but I don't know how to downgrade. is it possible? I tried to run the script at repair mode but this doesn't help.

**Comment by dariomws** [comment]
Hi @goretz2,

I think the only option to downgrade is Factory Reset:
https://docs.microsoft.com/MicrosoftTeams/rooms/rooms-operations#microsoft-teams-rooms-reset-factory-restore

**Comment by dariomws** [comment]
@dstrome could you kindly help with this issue? Thanks!
