### ISSUE TITLE
Wrong deb/rpm Download-Link for german page version

### ISSUE THREAD

**Issue by guija** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4113]
Hi. In the german version of this page the links for rpm and deb are e.g. https://aka.ms/getteamsvon . The trailing "von" has to be separated by a space from the link.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Beziehen von Clients für Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/get-clients#feedback)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@guija Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @guija, thank you for your feedback.

@OfficeGlobal could you kindly help? This link shouldn't be translated. Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by scanum** [comment]
@OfficeGlobal Any update? Thanks

**Comment by OfficeGlobal** [comment]
@guija , @scanum  article was HumanTranslated and published live. The link is fixed

**Comment by scanum** [comment]
@guija Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
