### ISSUE TITLE
Message size limit - Error message  

### ISSUE THREAD

**Issue by Vaaceph** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4114]
I have configured Teams webhook to display my messages when my code breaks.
There was an exception and the trace was big enough to show me the following message:
"This message is too long to display here. Please visit the link to read the content."

It's okay to see this message, As I have read that I can not send a message greater than approx. 28 KB, [Limits and specifications for Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#chat).

But the problem is that I can not see the link, either the message is misleading or there is a bug.
Please let me know in either case.

**Comment by scanum** [comment]
@Vaaceph thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Vaaceph** [comment]
> @Vaaceph thank you for submitting feedback.
> I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
> Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
> Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

Okay, thanks for replying.
I will keep you up to date here about this.
