### ISSUE TITLE
Wrong path to the option to turn on Teams on the old admin center

### ISSUE THREAD

**Issue by gezakukoda** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4115]
The path to the option on the old Admin center is: Microsoft 365 admin center &gt; ! Settings ! &gt; Services and add-ins &gt; Microsoft Teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5473bf0-ba2d-6c42-d57d-b61af64452d3
* Version Independent ID: 7195478d-3ef4-be8c-2920-3fdba3e70c7e
* Content: [Turn on Microsoft Teams in your Office 365 organization - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/office-365-set-up#feedback)
* Content Source: [Teams/Office-365-set-up.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-set-up.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@gezakukoda Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by EliasKaplan** [comment]
Please update with correct instructions for old and new admin center.
Also teams instructions are incorrect, only expereinced users can find it

**Comment by scanum** [comment]
@gezakukoda Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
