### ISSUE TITLE
Not setting Department to “Microsoft Communication Application Instance” will not provision the on-prem phone number in online

### ISSUE THREAD

**Issue by matudose** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4117]
Step 4 should be added before the existing step 4 (Start-ADSyncSyncCycle -PolicyType Delta)
4. Set the Department to “Microsoft Communication Application Instance” by running
Get-ADUser -Filter {UserPrincipalName -eq 'testcq@contoso.com'} | Set-AdUser -Department “Microsoft Communication Application Instance”
https://docs.microsoft.com/en-us/microsoftteams/known-issues#phone-system
For now, this step is necessary for the phone number to not be provisioned correctly. Otherwise, you won't be able to call the associated CQ/AA
!Note!
This cmdlet only works in Skype for Business Server 2019. For earlier version, please use ADSI Edit or Active Directory User Attribute Editor to set the correct value for Department

**Comment by scanum** [comment]
@matudose Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @matudose, thank you for your feedback.

Could you kindly elaborate your suggestion in more detail? Thanks!

**Comment by matudose** [comment]
https://docs.microsoft.com/en-us/microsoftteams/known-issues

Resource Account misconfigured Department | On premise resource Accounts associated with an auto attendant or call queue created before January 2019 might not have the Department parameter set properly, which might cause a phone number assignment to fail. A fix is underway to resolve this issue.Resource Accounts configured using New-CsHybridApplicationEndpoint with Skype for Business Server may not have the Department parameter set properly which will cause the resource account creation in Teams admin center to fail. In this case, you need to configure the department name in Active Directory on premise before synchronizing to online. | To mitigate this issue, you can run the following Cmdlet to set the department parameter. Set-MsolUser -ObjectId  -Department "Microsoft Communication Application Instance"Also see the Auto Attendant and Call Queues Service Update. | 5/8/19
-- | -- | -- | --

This also needs to be mentioned on this article because the clients are not aware of this and they open support cases. Resource Accounts are not properly provisioned in BVD because clients are not aware that they need to configure Department for hybrid resource accounts.

**Comment by dariomws** [comment]
Hi @matudose, my apologies I think still don't understand. It's in the article now:
![image](https://user-images.githubusercontent.com/33589238/77116511-11912500-6a0f-11ea-800b-f94910fa6ee3.png)

Are you talking about a hybrid environment? And in this case, instead of run:
Set-MsolUser -ObjectId <id> -Department "Microsoft Communication Application Instance"
They must run:
Set-AdUser -Identity "testcq" -Department “Microsoft Communication Application Instance”
And then on Azure AD Connect server:
Start-ADSyncSyncCycle -PolicyType Delta

**Comment by dariomws** [comment]
@matudose Are you a Microsoft support engineer? Thanks.

**Comment by matudose** [comment]
Hi Dario,

You are right, even that article needs to be corrected, I mentioned it hastily and forgot in fact to specify:
Instead of set-msoluser they must run
Get-ADUser -Filter {UserPrincipalName -eq 'testaa@contoso.com'} | Set-AdUser -Department “Microsoft Communication Application Instance”
Get-ADUser -Filter {UserPrincipalName -eq 'testcq@contoso.com'} | Set-AdUser -Department “Microsoft Communication Application Instance”
(skype for business 2019)
Or
edit it via attribute editor or ADSI Edit
(skype for business server 2015)
And then on Azure AD Connect server:
Start-ADSyncSyncCycle -PolicyType Delta
https://dev.azure.com/Supportability/UC/_wiki/wikis/UC.wiki/3277/Teams-Resource-Accounts-for-AA-and-CQ?anchor=on-premise-resource-account

With kind regards / Cordialement,
Matei Tudose
Support Escalation Eng
Unified Communications
Customer Services and Support Working hours: 9-18
Office: +40 (0)311 331 574
Mobile: +40 (0)749 268 982

matei.tudose@microsoft.com<mailto:matei.tudose@microsoft.com>
[cid:image001.jpg@01D5FE47.9191EB10]
Team Manager | Mirela Oprisan (Mirela.Oprisan@microsoft.com<mailto:Mirela.Oprisan@microsoft.com>) +40 (31) 1330733

**Comment by matudose** [comment]
Hello Dario,

I am Support Escalation Engineer in the Skype/Teams premier team.

With kind regards / Cordialement,
Matei Tudose
Support Escalation Eng
Unified Communications
Customer Services and Support Working hours: 9-18
Office: +40 (0)311 331 574
Mobile: +40 (0)749 268 982

matei.tudose@microsoft.com<mailto:matei.tudose@microsoft.com>
[cid:image001.jpg@01D5FE48.1FE724C0]
Team Manager | Mirela Oprisan (Mirela.Oprisan@microsoft.com<mailto:Mirela.Oprisan@microsoft.com>) +40 (31) 1330733

**Comment by dariomws** [comment]
Understood now, applying an update.

**Comment by dariomws** [comment]
@matudose Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=matudose

And if you have a Microsoft alias you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

**Comment by scanum** [comment]
@matudose Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
