### ISSUE TITLE
Hybrid resource accounts which sync their attributes from AD cannot be modified using Set-MsolUser

### ISSUE THREAD

**Issue by matudose** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4118]
Under the issue
Resource Account misconfigured Department 
the fix is specified as follows
To mitigate this issue, you can run the following Cmdlet to set the department parameter. Set-MsolUser -ObjectId  -Department "Microsoft Communication Application Instance" 
This cannot be done for Hybrid resource accounts which sync their attributes from AD
Instead, one of the following can be done:
1.	If the deployment is SfB2019, the administrator can run the following on a SfB2019 Server:
Get-ADUser -Filter {UserPrincipalName -eq 'testcq@contoso.com'} | Set-AdUser -Department “Microsoft Communication Application Instance”
2.	If the deployment does not have SfB2019 servers, this needs to be done using ADSI Edit or AD Attribute Editor

**Comment by scanum** [comment]
@matudose thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
