### ISSUE TITLE
article in the future ?

### ISSUE THREAD

**Issue by tofkamp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#412]
The article was written on 4th of june in the comming year 2019 ? :-)

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 27364aed-dc10-dcaf-8446-bc93e39bd4ca
* Version Independent ID: 907a29a6-6ff3-5c91-5c74-cf98cf71ad88
* Content: [De connectormodule van Skype voor Bedrijven Online downloaden en installeren](https://docs.microsoft.com/nl-nl/SkypeForBusiness/set-up-your-computer-for-windows-powershell/download-and-install-the-skype-for-business-online-connector)
* Content Source: [Skype/SfbOnline/set-up-your-computer-for-windows-powershell/download-and-install-the-skype-for-business-online-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.nl-NL/blob/live-sxs/Skype/SfbOnline/set-up-your-computer-for-windows-powershell/download-and-install-the-skype-for-business-online-connector.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@tofkamp - I am not seeing that part for some reason.. which part of the article does that show? On my browser it is showing updated date like this: 18-4-2018


I want to get to the bottom of it though and can loop in our localization team. Can you help me where you are seeing that?

**Comment by tofkamp** [comment]
![image](https://user-images.githubusercontent.com/11454484/41394052-b7acbc14-6fa8-11e8-89f0-63fb3f366939.png)
edge on windows 10.0.16299 Build 16299
The article is automaticly translated to dutch :-( When I enable the english version, it is still in the future.

**Comment by kenwith** [comment]
Hmm this is really interesting and I have to get to the bottom of this one. Here is screenshot of what I see below. What date do you see if you go to [en-us version](https://docs.microsoft.com/en-us/SkypeForBusiness/set-up-your-computer-for-windows-powershell/download-and-install-the-skype-for-business-online-connector)?
<br /><br />
As far as I know the date is pulled directly from [GitHub source](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-your-computer-for-windows-powershell/download-and-install-the-skype-for-business-online-connector.md) on last commit date.
<br /><br />
But I know there is a translation process to that I am not super familiar with yet so I want to check into that with the localization team too.
<br /><br />
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/27743960/41423916-73b4069e-6fb1-11e8-86ce-bc2a9ebb2500.png">

**Comment by tofkamp** [comment]
No, I don't know why it is in the future.
I have searched for an other doc-page, also on github, and found:	   
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-your-computer-for-windows-powershell/download-and-install-the-skype-for-business-online-connector.md
converted the url to https://docs.microsoft.com/nl-nl/SkypeForBusiness/skype-for-business-and-microsoft-teams-add-on-licensing/calling-plans-for-office-365
And this also has the same kind of problem.
If you look at the edit date on github, it is the 26 april 2018, but if I read it in my browser, it says the 5th of august 2018 which it two months in the future.
![image](https://user-images.githubusercontent.com/11454484/41453363-bedf8bb0-7075-11e8-8cf4-746253dcea08.png)
If I go the direct document link provided by Ken Withee, to the en-us document version, it works fine. If I change the en-us to nl-nl (in the url) it also works good. I do NOT have "Lezen in het Engels" selection button on the right side, even with the dutch version of the document.
Other documents on docs.microsoft.com of other products seems to work ok. Only when I get "Lezen in het Engels" on the right side, it messes things up with the date. My guess is that somewhere the month-number is exchanged with the day-number. Because in the USA the month-number is before the day-number. Mostly in the rest of the world, it is the other way around.
The translation is not good. There are still dutch words on the page, when I flip the setting to read-in-english:
![image](https://user-images.githubusercontent.com/11454484/41453687-facd9030-7076-11e8-9f29-646c20446f1d.png)
So I guess the text is english, but the style-sheet (??) is still dutch. This makes it a weird document.
Could the stylesheet also be the cause of the "translated" date (???)

**Comment by kenwith** [comment]
Let's ask Samantha who works on the localization team. @samanro - any thoughts?

**Comment by samanthaw** [comment]
@tofkamp The first one doesn't repro for me either, I see the same @kenwith notes above. The last one repros though, we'll investigate this bug further to get the date to render in the correct format.

**Comment by kenwith** [comment]
@samanthaw - is this one resolved with the fix for the other issue as well?

**Comment by kenwith** [comment]
@samanthaw - this one looks like it is still affecting the German translation.. any update?

**Comment by samanthaw** [comment]
@tofkamp @kenwith - confirming this is still an active issue that's being investigated, I don't have an ETA though

**Comment by kenwith** [comment]
@samanthaw - just a ping if there is any update. :)

**Comment by kenwith** [comment]
@tofkamp - this should be fixed now and the date should be correct. Thank you @samanthaw!!

If you still experience any issue please feel free to re-open. We really appreciate you taking the time to report!
