### ISSUE TITLE
Exchange backend.

### ISSUE THREAD

**Issue by 12Knocksinna** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4120]
Teams chat works on a Microsoft Exchange backend, so Exchange messaging limits apply to the chat function within Teams.
------------------
The only way Teams uses EXO is to store compliance records for the chat as items in the Team Chat folder of the participants' mailboxes. The actual chat data is stored in Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@12Knocksinna thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by 12Knocksinna** [comment]
Sorry, but how will opening a service ticket for my tenant resolve a documentation error that I have pointed out? The text is incorrect and needs to be fixed. Teams chat items are not stored in Exchange Online mailboxes. Teams compliance records are created in mailboxes by the Office 365 substrate to make sure that chats can be found by eDiscovery. Those compliance records are also used for retention processing.

**Comment by 12Knocksinna** [comment]
See https://www.petri.com/teams-compliance-story. I have noted this problem on the Teams team for MVPs in the Microsoft tenant for the Teams PG to follow up.
