### ISSUE TITLE
Call Park for Teams Phone Devices

### ISSUE THREAD

**Issue by MySkypeLab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4121]
This page says that Call Park is Coming Soon for Teams IP phones. This feature is now available in Teams Phones. Please update the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e03ef3d-81d8-c98f-8427-fe7c008ea30f
* Version Independent ID: 17af3418-b94d-f233-60c0-778b2e8dc02b
* Content: [Call park and retrieve in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/call-park-and-retrieve)
* Content Source: [Teams/call-park-and-retrieve.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/call-park-and-retrieve.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@MySkypeLab Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@MySkypeLab Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
