### ISSUE TITLE
Enable-CsMeetingRoom not included in skype module/connector

### ISSUE THREAD

**Issue by davmin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4122]
It does not seem that Enable-CsMeetingRoom or related cmdlets are included in the skype online connector. Is that the case?

Is this step unnecessary for a teams-only Tenant? If so the documentation should reflect that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-office-365#feedback)
* Content Source: [Teams/rooms/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-office-365.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@davmin  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @davmin, thank you for your feedback.

I have verified and *-CsMeetingRoom cmdlets are available in the Skype for Business Online PowerShell module.

You need to run these steps for a Teams only tenant too.

**Comment by scanum** [comment]
@davmin Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
