### ISSUE TITLE
How to install Teams with Office 365 for Windows 10 (Endpoint Manager)

### ISSUE THREAD

**Issue by htu-mark** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4125]
Installing Teams as part of the Office 365 for Windows 10 deployment using XML configuration in Endpoint Manager. I have a group of devices set to required for install.

As per Microsoft's article, it is recommended to use the GPO method. The MSI install (separate) requires administrative install which we obviously can't do during white glove process. So how can I do the GPO method if it doesn't even exist in Intune yet?

> **Use Group Policy (recommended)**
> Enable the Prevent Microsoft Teams from starting automatically after installation Group Policy setting. You can find this policy setting in User Configuration\Policies\Administrative Templates\Microsoft Teams. This is the recommended method because you can turn off or turn on the policy setting according to your organization's needs.

> If you run the MSI manually, be sure to run it with elevated permissions. Even if you run it as an administrator, without running it with elevated permissions, the installer won't be able to configure the option to disable auto start.

https://docs.microsoft.com/en-us/microsoftteams/msi-deployment

**Comment by scanum** [comment]
@htu-mark thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by htu-mark** [comment]
Issue was related to UAC prompt being enabled in Intune Device Configuration. For some reason, Microsoft has Teams running in admin mode during install unlike when installing Office apps, Visio, Project, Adobe Reader, or any other app we have being installed.
