### ISSUE TITLE
Is HostedMigrationOverrideUrl still valid comment?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4126]
Your document says:
" _determine the prefix - XXXXXXX.online.lync.com_". Currently when going to legacy portal I get the following URL: https://webdir0e.online.lync.com/LSCP and I feel that is not the correct URL.

But isn't hosting provider URL better to get at begin?

```
PS C:\> $s = New-CsOnlineSession -OverrideAdminDomain company.onmicrosoft.com
PS C:\> $s.computername
admin0e.online.lync.com
```

Or even use the variable on the command itself?

```
$cred=Get-Credential
$url="https://$($s.computername)/HostedMigration/hostedmigrationService.svc"

Move-CsUser -Identity username@contoso.com -Targ....
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40129d20-5ce3-8f23-90a3-490e4d3498bb
* Version Independent ID: 6104ec9f-c48a-f6a2-6d78-af6f58fe493e
* Content: [Move users from on premises to Skype for Business Online - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/move-users-from-on-premises-to-skype-for-business-online)
* Content Source: [Skype/SfbHybrid/hybrid/move-users-from-on-premises-to-skype-for-business-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/move-users-from-on-premises-to-skype-for-business-online.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Petri-X  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Petri-X, thank you for your feedback.

I removed the NOTE, you must follow these instructions:
"with the correct value as described in [Required administrative credentials](https://docs.microsoft.com/skypeforbusiness/hybrid/move-users-between-on-premises-and-cloud#required-administrative-credentials)"

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
