### ISSUE TITLE
Auto Attendant dial by extension

### ISSUE THREAD

**Issue by dewaltk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4127]
Any update on when the auto attendants will be able to dial by extension matching the lineuri attribute? The workaround provided works for regular users but not for analog devices and common area phone contacts created in a Skype for Business on prem environment. Is there any other recommended workaround for these endpoints other than creating regular user accounts and forwarding the calls to the analog or CAP numbers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a42f9e2c-aeee-76c4-620a-668cce21ba10
* Version Independent ID: 6ff06eab-9c80-9c30-95ef-c17e157fbea1
* Content: [Set up a Cloud auto attendant - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-auto-attendant)
* Content Source: [Teams/create-a-phone-system-auto-attendant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-auto-attendant.md)
* Service: **msteams**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@dewaltk thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
