### ISSUE TITLE
" Our commitment to customers during COVID-19" link does not work

### ISSUE THREAD

**Issue by oksanaMS** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4128]
" Our commitment to customers during COVID-19" link does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4faeeb9b-7cf7-64db-1c0b-17fc4a21f422
* Version Independent ID: ee0660a9-3902-5ce2-c9ea-82e23bd99dcd
* Content: [FAQ - Support your remote workforce - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/faq-support-remote-workforce#feedback)
* Content Source: [Teams/FAQ-support-remote-workforce.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/FAQ-support-remote-workforce.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@oksanaMS  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dotwhat** [comment]
the link should be: https://www.microsoft.com/en-us/microsoft-365/blog/2020/03/05/our-commitment-to-customers-during-covid-19/

**Comment by oksanaMS** [comment]
The link is still broken, it was working yesterday. What’s happening? Customers are using this page, this is very important.

**Comment by dotwhat** [comment]
#4154

**Comment by jamie999x** [comment]
Will the EOL for 1709 be extended due to the outbreak?
