### ISSUE TITLE
Certifying SBC's

### ISSUE THREAD

**Issue by GymTheGeek** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4129]
Could someone please point us in the direction of who we need to make contact with in order to certify our SBC technology for use with Microsoft Teams, have looked online but so far have been unsuccessful.

**Comment by scanum** [comment]
@GymTheGeek thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
