### ISSUE TITLE
public preview

### ISSUE THREAD

**Issue by jacqle331** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4135]
is it possible to update the document to include public preview, rather than just preview?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c1b9711-5502-6194-98ed-ff17c4c4ec16
* Version Independent ID: bda458a2-8763-41d8-549d-65afc813e85a
* Content: [Use Advisor for Teams (preview) to help you roll out Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/use-advisor-teams-roll-out#feedback)
* Content Source: [Teams/use-advisor-teams-roll-out.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/use-advisor-teams-roll-out.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@jacqle331  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@jacqle331 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
