### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by giterdn** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4137]
New March 9, 2020: Work remotely with Microsoft Teams … this takes you nowhere

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cdf3243-40dc-708c-cefc-8be68491a3be
* Version Independent ID: 0fc81593-de9a-c453-4a1c-ec1ebbfe2ecf
* Content: [Support remote workers using Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/support-remote-work-with-teams)
* Content Source: [Teams/support-remote-work-with-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/support-remote-work-with-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@4135  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @giterdn, thank you for your feedback.

That was updated/fixed on March 10.

**Comment by scanum** [comment]
@giterdn Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
