### ISSUE TITLE
게스트 엑세스 기본 설정 값

### ISSUE THREAD

**Issue by AnnTaeYoun** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4138]
기본적으로 게스트 액세스가 꺼져 있습니다. 문구를 다음으로 변경 요청 합니다.
기본적으로 게스트 액세스가 켜져 있습니다. 

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 042d7ce6-ee22-690f-8188-ff8a4a585847
* Version Independent ID: 3e5bc99c-e08e-44e0-cda3-687ed3633175
* Content: [Microsoft 팀에 대 한 게스트 액세스 설정 또는 해제 - Microsoft Teams](https://docs.microsoft.com/ko-kr/microsoftteams/set-up-guests#feedback)
* Content Source: [Teams/set-up-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-guests.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officeglobal Hi! Could you please help us out on this issue? Thanks!!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@scanum The article was HumanTranslated, text follows the source

**Comment by scanum** [comment]
@AnnTaeYoun Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
