### ISSUE TITLE
Manage channel moderation

### ISSUE THREAD

**Issue by akpasha** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4139]
hi my organization is using Office 365 A1 licenses. our teams version does not show channel moderation feature is it discontinued or I need to make some changes to the setting ?

Regards
AK

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097ecd40-1157-98ae-f438-96f9208afc03
* Version Independent ID: ea36ff93-46dc-920d-8d52-9b3b81420958
* Content: [Set up and manage channel moderation in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-channel-moderation-in-teams#feedback)
* Content Source: [Teams/manage-channel-moderation-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-channel-moderation-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@akpasha thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
