### ISSUE TITLE
Teams Crashes on iOS 12 Beta

### ISSUE THREAD

**Issue by mattbell89** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#414]
I was signed into Teams before installing they beta, and afterwards I was able to still receive push notifications, but when opening the app, it would crash after about 1 second.

I then deleted and reinstalled Teams, and it did not crash on open, but it did crash as soon as I signed in.

iOS 12 is obviously new and high-risk for bugs with apps, but I wanted to at least call attention to this one.

**Comment by gknowd** [comment]
I have noticed the same behavior with iOS 12

**Comment by kenwith** [comment]
@mattbell89 and @gknowd - product teams and support are tracking this now. Thank you for reporting! Here is a related PR: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/420 regarding beta.
