### ISSUE TITLE
Very confusing

### ISSUE THREAD

**Issue by neilwithdata** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4140]
I'm still finding the description of permissions and how they interact quite confusing. For example, the "Org-wide custom app setting" is described as "This setting overrides the user and team custom app policy and setting" but when you look at the summary table that's clearly not the case. This setting does not _override_ the other settings. When it's On there are still situations where the user cannot upload custom apps - it hasn't overridden the other settings.

Also, what are the defaults set to for a new Teams installation? Would be useful to have that documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d51bb7b1-801e-6801-dcaf-afa3e38e6941
* Version Independent ID: d8e726a1-cbf2-53c7-da4d-cc155b48612b
* Content: [Manage custom app policies and settings in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-custom-app-policies-and-settings#feedback)
* Content Source: [Teams/teams-custom-app-policies-and-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-custom-app-policies-and-settings.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@neilwithdata Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
Hi @neilwithdata  Thanks for raising this issue! I will be looking into it!

**Comment by TokyoScarab** [comment]
@neilwithdata The setting is an override of sorts. When it is on, it enables the other 2 settings (Team custom app setting and User custom app policy) to be active. If Org-Wide isn't enabled, then those settings will not work even if enabled.  It's probably easier to think of the Org-Wide setting as a big on/off switch for those policy settings. I hope this description helps to clarify things.

**Comment by scanum** [comment]
@neilwithdata Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
