### ISSUE TITLE
MS teams live events: switch from attendee to presenter

### ISSUE THREAD

**Issue by suoko** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4141]
I recently used a live event in teams and, in order to let an attendee speak to raise a question, I invited him as a presenter.
The problem was that the user didn't stop the stream he was watching, causing an echo effect.
It would be nice to have teams manage natively the switch, like, select the attendee and make him temporarly a presenter

**Comment by scanum** [comment]
@suoko thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
