### ISSUE TITLE
Clarity on 'how long does it last' for non-EA customers

### ISSUE THREAD

**Issue by N8dog021** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4142]
So if a customer does not have an EA, rather CSP or direct subscriptions, what exactly determines "or renewal on or after January 2021" because they could have multiple renewal dates for various products... is it the earliest renewal for product that contains paid Teams?  Or furthest out renewal date? or something else that determines when the Team Exploratory ends?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f897ae9b-852a-b617-7de0-d76dbd9f1820
* Version Independent ID: 161b1845-53fd-8912-a5f9-737d3bcdaadc
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-exploratory#feedback)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by jfranki** [comment]
Yes, please, we need to know where can we find the expiration date as our migration to Office 365 will not be completed until months from now.

**Comment by scanum** [comment]
@N8dog021 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by ichkoj** [comment]
open ticket with support..?! Seriously, what makes you think he will get reply in the next 3 weeks? Lets try your resources instead!
