### ISSUE TITLE
What does the "allow anonymous users" switch really do?

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4143]
Based on description the "Allow anonymous users to join meetings" switch just disables unauthorized users to join. But based on my experience it also disables signed in users that are not part of organizers AAD. What is the expected behavior of this switch? Will it allow blocking access of external users as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Manage meeting settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams#allow-anonymous-users-to-join-meetings)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by tonysmit** [comment]
It is simply based on whether or not a user is logged into Teams/SFBO or a PIN if a PIN is enabled on the meeting for everyone, not just the organizer. Because it's Audio Conferencing, it one or the other. If a user isn't logged on to Teams/SBO, then they will be prompted for a PIN for the meeting (thus authenticating them). Hope that helps. Let me know. Tony

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by rachoksh** [comment]
Can this documentation be improved? 

We could improve this line that reads "2. Under Participants, turn on Anonymous users can join a meeting."

It could say something like anonymous is not actually anyone without authentication but invited users outside the tenant like gmail.com, outlook.com email addresses.

**Comment by Larryngolog** [comment]
Anonnymous according to this documentation https://docs.microsoft.com/en-us/microsoftteams/teams-security-guide means - "The term anonymous users means users that are not authenticated to the organizations tenant. In this context all external users are considered anonymous. Authenticated users include tenant users and Guest users of the tenant." - we should include this statement in this document as well. For example users with gmail or outlook accounts who are invited as guests will be able to join meetings when annonymous is unchecked.
