### ISSUE TITLE
Please info on how Microsoft Teams MSI package works for "Existing User Profiles"?

### ISSUE THREAD

**Issue by SunManMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4146]
The doc doesn't talk about how it works for existing user profiles under "PC installation" section for topic "How the Microsoft Teams MSI package works". Request to add that information as well

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Microsoft Teams using MSI via Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment#feedback)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@SunManMSFT Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@SunManMSFT thank you for reaching out and helping improve MS Docs. The article has recently been updated. Please have a look and let me know if your issue has been solved with the update.

**Comment by scanum** [comment]
@SunManMSFT Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by SunManMSFT** [comment]
I am not able to locate the information added. Can you point where it talks about it?
