### ISSUE TITLE
It would be great if your team knew anything about this 

### ISSUE THREAD

**Issue by kea-ven** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4148]
I have spoken to around 12 people over the past 3 days from Microsoft and partners trying to get this offer. NOBODY has heard of it and keep getting passed off to someone else. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779619a7-95a8-c775-0538-4f07abb7067e
* Version Independent ID: cf930116-3d9d-2075-5291-f819cb17a234
* Content: [Manage the free Office 365 E1 Trial - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/e1-trial-license#feedback)
* Content Source: [Teams/e1-trial-license.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/e1-trial-license.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@kea-ven thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jasonwmartin** [comment]
We (Partners) need more info on this!  Same as @kea-ven, I've spoke now with multiple different people including my supplier Ingram Micro whom I'm setup as a CSP and they said it's not available for partners/CSP.  I opened a ticket through the admin.microsoft.com and they're just copying/pasting this article as reference...at this point, I don't any has clue.  It's a noble gesture from Microsoft but at this point, it's just a gesture!

**Comment by Shridharkanchagar** [comment]
Hello @kea-ven , you need to have one or the other contacts in the Microsoft, then only you can get Promo Codes. and more info can be available through the Respective MS Account Managers. whom you can reach out to.

**Comment by jasonwmartin** [comment]
FYI, Microsoft Partners/CSP are not able to provide this to customers directly.  The end-user, or a partner acting on behalf of customer (i.e., logged into admin.microsoft.com as the customer tenant), must open a support ticket.  Typically, Microsoft Office 365 Support (outsourced support, only has @microsoft365support.com e-mail/Microsoft account) will be initially assigned the ticket - they can't provide the promo code either.  However, they are supposed to know (as of 3/18/2020) how to escalate to their SME (Subject Matter Expert) who does have an @microsoft.com account and can submit the request for the promo code.  Once everyone actually knew how/what to do...took about 6 hrs. after opening the ticket (which I did, MS Partner, on my customer/tenant's behalf) to get the promo code.  Hope this helps someone...
