### ISSUE TITLE
Teams Admin Center - Devices not Showing

### ISSUE THREAD

**Issue by coco6969** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4151]
"As an admin, you can manage devices used with Teams in your organization from the Microsoft Teams admin center. You can view and manage the device inventory for your organization and do tasks such as update, restart, and monitor diagnostics for devices."

"You can manage any device that's certified for, and enrolled in, Teams. A device is automatically enrolled the first time a user signs in to Teams on the device"

However, certified phones does not show up in devices in Teams Admin Center. Yealink T58 and Polycom 500 CCX does not show up, but it shows in Intune Device Management. Is there anyone seeing this issue as well even after updating firmware? https://techcommunity.microsoft.com/t5/microsoft-teams/yealink-t56a-missing-in-the-teams-admin-center/m-p/838913

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a627b5d-3edc-1add-b921-1dcd49c38653
* Version Independent ID: a2e2bd3a-31c0-471a-05fb-fd64bd942c4a
* Content: [Manage your devices in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/device-management#feedback)
* Content Source: [Teams/device-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/device-management.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@coco6969 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by coco6969** [comment]
Do you think there's something on the back end causing this? Any updates? Appreciate it, thanks.

**Comment by lindspea** [comment]
@coco6969 thank you for reaching out and helping improve MS Docs. I've done a bit of research so far and will check with the team as well if this doesn't solve your problem. Have you updated the firmware from your phone's web interface? Also try delete your phone from the Teams Admin Center and add it again. Have you tried using Teams Only mode? Please let me know and I'll investigate further.

**Comment by scanum** [comment]
@coco6969 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
