### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by MrHinsh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4153]
It would be very useful to have the links to the features described in the content. I cant find the Teams Admin URL without going through the Office 365 admin portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9f904e5-d015-70b0-b809-9b0b62931ab5
* Version Independent ID: aa59fcc6-0a6d-c82f-6b5e-ffb85e08ea8a
* Content: [Manage Teams during the transition to the new Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-teams-skypeforbusiness-admin-center#feedback)
* Content Source: [Teams/manage-teams-skypeforbusiness-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-teams-skypeforbusiness-admin-center.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@MrHinsh Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@MrHinsh thank you for reaching out and helping improve MS Docs. Just to keep you updated, the  product team is recommending to use the O365 portal for now. are you on the free version or paid version? The free version also has limitations and does not have access to the Admin Center. Guest access is disabled by default. Here are some articles for reference.https://support.office.com/article/add-guests-to-a-team-in-teams-fccb4fa6-f864-4508-bdde-256e7384a14f?ui=en-US&rs=en-US&ad=US, https://support.office.com/article/differences-between-microsoft-teams-and-microsoft-teams-free-0b69cf39-eb52-49af-b255-60d46fdf8a9c?ui=en-US&rs=en-US&ad=US, https://docs.microsoft.com/en-us/microsoftteams/set-up-guests

**Comment by scanum** [comment]
@MrHinsh Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
