### ISSUE TITLE
Channel Moderation Options Like Who Are Moderators Missing

### ISSUE THREAD

**Issue by ashmsport** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4155]
The only option in Channel Settings is:
Permissions
Set channel moderation preferences
General Channel:
Anyone can post messages
Anyone can post; show alert that posting will notify everyone (recommended for large teams)
Only owners can post messages
_______________________________________________________________________________________________________________________________________
I'm seeing this behavior in 3 tenants with G3, A3 and E3 Developer Subscription.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097ecd40-1157-98ae-f438-96f9208afc03
* Version Independent ID: ea36ff93-46dc-920d-8d52-9b3b81420958
* Content: [Set up and manage channel moderation in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-channel-moderation-in-teams)
* Content Source: [Teams/manage-channel-moderation-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-channel-moderation-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by smnbldwn** [comment]
I don't see these options just:

"Permissions
Set channel moderation preferences
General Channel:
Anyone can post messages
Anyone can post; show alert that posting will notify everyone (recommended for large teams)
Only owners can post messages"

Why can't I enable moderation, this is a tool for schools for goodness sake! Why is it so hard. This should be enabled by default in Teams for education, as it isn't how do I enable it?

**Comment by scanum** [comment]
@ashmsport Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by JohnHarach** [comment]
This is due to you attempting to change this setting on the General channel. This unfortunately does not work. 

Please try on any other manually created channel.

**Comment by moat-tdawson** [comment]
Hi
I have a class Team for All Students with private channels for Year 07, Year 08 etc.
The moderation options do not appear in settings for either the General channel or the private (manually created) channels.
This function would be particularly useful with the school shutdown.

**Comment by scanum** [comment]
@ashmsport thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
