### ISSUE TITLE
Issue with SRS processing XML

### ISSUE THREAD

**Issue by David-COP** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4156]
Hello, I am working on creating a PS script for changing the password to our rooms remotely. I have created a script that is able to build the XML and write it to the correct location on the Room PC, on reboot it is however not changing the password. Is there anywhere you can check the logs to see why this was not processed?

Here is the SkypeSettings.xml that was used:
&lt;SkypeSettings&gt;
    &lt;UserAccount&gt;
        &lt;Password&gt;Password123&lt;/Password&gt;
    &lt;/UserAccount&gt;
&lt;/SkypeSettings&gt;

Location saved:
C:\Users\Skype\AppData\Local\Packages\Microsoft.SkypeRoomSystem_8wekyb3d8bbwe\LocalState\SkypeSettings.xml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25a70665-5bf1-14f7-1df0-7596effcaf48
* Version Independent ID: 813cf005-2777-9419-d1ce-3f9401ac267c
* Content: [Manage a Microsoft Teams Rooms console settings remotely with an XML configuration file - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/xml-config-file#feedback)
* Content Source: [Teams/rooms/xml-config-file.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/xml-config-file.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@David-COP Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@LanaChin please could you help here or should this be directed to support?

**Comment by seiferic** [comment]
I am having the same issue.  Able to change all other settings except those within <useraccount>

**Comment by scanum** [comment]
@David-COP thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
