### ISSUE TITLE
Page is OUTDATED

### ISSUE THREAD

**Issue by AlexHill90** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4157]
Hi, the page has not been changed in 6 months. E.g. some features are evidenced as 'coming soon'. . . well they arrived e.g. guest/federated according to UV: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/36613579-guest-presenter-in-team-live-event-meeting

please update the table

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Pianificare eventi dinamici in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/it-it/microsoftteams/teams-live-events/plan-for-teams-live-events#feedback)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@AlexHill90 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@office global

**Comment by scanum** [comment]
@officeglobal Could you please help with this issue? Thanks

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by invirtuteDei** [comment]
Please list correct licenses that work.  M365 licenses work for live events (M365 E5) for example.

**Comment by scanum** [comment]
@officeglobal Any update on this? Thanks

**Comment by OfficeGlobal** [comment]
@AlexHill90 , @scanum we have HumanTranslated the latest received update and publish it live

**Comment by scanum** [comment]
@AlexHill90 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
