### ISSUE TITLE
bad urls

### ISSUE THREAD

**Issue by mgcharumilind** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4161]
There is a bad urls in the customer success kit in the end user communication folder, in Countdown template at the second (youtube) video link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cdf3243-40dc-708c-cefc-8be68491a3be
* Version Independent ID: 0fc81593-de9a-c453-4a1c-ec1ebbfe2ecf
* Content: [Support remote workers using Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/support-remote-work-with-teams#feedback)
* Content Source: [Teams/support-remote-work-with-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/support-remote-work-with-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@mgcharumilind Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@mgcharumilind thank you for reaching out. Just to clarify are you talking about the Customer service kit that you download from this article? I've just had a look there and I can't see any videos. Please can you double-check and confirm. It could have been fixed in the interim with the article update today.

**Comment by mgcharumilind** [comment]
I believe the broken link has since been removed from the email template in question

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@mgcharumilind Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
