### ISSUE TITLE
Reference doesn't exist

### ISSUE THREAD

**Issue by mgcharumilind** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4162]
The page references a Your First Day in Teams email in the Customer Success Kit, but there isn't any such email template included in those files

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cdf3243-40dc-708c-cefc-8be68491a3be
* Version Independent ID: 0fc81593-de9a-c453-4a1c-ec1ebbfe2ecf
* Content: [Support remote workers using Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/support-remote-work-with-teams#feedback)
* Content Source: [Teams/support-remote-work-with-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/support-remote-work-with-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@mgcharumilind Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@mgcharumilind thank you for reaching out and helping improve MS Docs. I've just had a look through the article and see it's been updated this week and there are quite a few templates in the kit.  Please could you confirm all in order.

**Comment by mgcharumilind** [comment]
No, the text on that page still does not match what's in the email templates in the customer success kit. 
![image](https://user-images.githubusercontent.com/39596904/77944862-a86ea480-728d-11ea-8e61-4956ae7da692.png)

![image](https://user-images.githubusercontent.com/39596904/77944790-8bd26c80-728d-11ea-8a6a-466283e58114.png)

**Comment by scanum** [comment]
@mgcharumilind Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
