### ISSUE TITLE
Non-English Language setting will not be set in Stream side for Stream Auto Caption future

### ISSUE THREAD

**Issue by HiroTsukamoto** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4163]
When Teams web conference is recorded, Stream always gives "English auto caption".
I will not setup any language setting for the video, now user manually needs to setup non-English language
on Video edit page on Stream web.
If Spanish user records the web conference, the stream should show Spanish auto-caption as default without any manual operation.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams のクラウド会議のレコーディング - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/cloud-recording#feedback)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@HiroTsukamoto Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@OfficeGlobal

**Comment by scanum** [comment]
@HiroTsukamoto thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
