### ISSUE TITLE
Additional Information Required

### ISSUE THREAD

**Issue by MurtazK** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4168]
How do you contact a Microsoft Account Representative and how long does it take to receive the promo code? Thank you! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779619a7-95a8-c775-0538-4f07abb7067e
* Version Independent ID: cf930116-3d9d-2075-5291-f819cb17a234
* Content: [Manage the free Office 365 E1 Trial - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/e1-trial-license#feedback)
* Content Source: [Teams/e1-trial-license.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/e1-trial-license.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@MurtazK thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by metroman976** [comment]
> How do you contact a Microsoft Account Representative and how long does it take to receive the promo code? Thank you!
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 779619a7-95a8-c775-0538-4f07abb7067e
> * Version Independent ID: cf930116-3d9d-2075-5291-f819cb17a234
> * Content: [Manage the free Office 365 E1 Trial - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/e1-trial-license#feedback)
> * Content Source: [Teams/e1-trial-license.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/e1-trial-license.md)
> * Service: **msteams**
> * GitHub Login: @LolaJacobsen
> * Microsoft Alias: **lolaj**

You'd have to contact your 'Microsoft solution provider' to get the promo code. Let me know if you need any help.
