### ISSUE TITLE
The commands do not work

### ISSUE THREAD

**Issue by ComputerHabit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4171]
I cannot get the commands for changing dial out restrictions to work.  

Grant-CsDialoutPolicy -PolicyName 'tag:DialoutCPCandPSTNDomestic' -Identity 'user.identity@domain.com'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 305a21ef-6e99-3f0d-99a0-990489a93715
* Version Independent ID: 5edc67ee-0d68-50a3-fafd-f764d8762fa5
* Content: [Outbound calling restriction policies for Audio Conferencing and user PSTN calls - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/outbound-calling-restriction-policies)
* Content Source: [Teams/outbound-calling-restriction-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/outbound-calling-restriction-policies.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@ComputerHabit thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by ComputerHabit** [comment]
Maybe in the docs mention that changes are not reflected for hours after running the command?

________________________________
