### ISSUE TITLE
Profile picture mismatch, missing metadata

### ISSUE THREAD

**Issue by Adithya-copart** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4172]
**Environment:**

`You have Microsoft Teams Version 1.3.00.362.` in a Mac.

**Issues:**
- Profile photo mismatch when viewing the tile of another user.
- No name/picture in a message thread. _(In a colleague's system with a similar setup.)_

**Resolution:**

A reboot of the application did not help.  The issue is fixed after running `rm -rf ~/Library/Application\ Support/Microsoft/Teams` and then booting up the application.

The local cache/storage strategy could be the root-cause and it could be strengthened by some additional checks for integrity.

**Comment by scanum** [comment]
@Adithya-copart thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
