### ISSUE TITLE
Using both guest accounts and O365 accounts

### ISSUE THREAD

**Issue by bhughesPND** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4173]
A client sent me a guest invitation, which I can access as a guest. From the guest account, there's a drop-down menu to return to my company's O365 Teams. There's no similar menu in the internal one to return to the guest. Since I used the same email address, logging in to teams always takes me to my company account. So the only way I can seem to return to the guest account is to find the email and follow the link & not use the desktop app.
Is this how it's supposed to work? Why can't the app integrate the two better?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 754022e3-49eb-dbd5-e4f5-891c8ebeb491
* Version Independent ID: b73a6f64-d36f-298f-d9ac-34860abad42b
* Content: [How a guest joins a team - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-joins#feedback)
* Content Source: [Teams/guest-joins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-joins.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@bhughesPND thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
