### ISSUE TITLE
Access of Microsoft to data 

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4174]
Is this statement "Microsoft doesn’t have access to uploaded content" accurate? Microsoft engineers under very specific and regulated conditions can get access to uploaded content in order to provide uninterupted service - troubleshooting, etc + to address subpoemas. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca579d63-182b-d6f5-8777-79248fa27ed9
* Version Independent ID: b4c27d1b-b2f1-41ac-b15c-d12b448a539e
* Content: [Overview of security and compliance in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/security-compliance-overview)
* Content Source: [Teams/security-compliance-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/security-compliance-overview.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@Larryngolog Thanks for reaching out. Please see the document has been updated a few days ago. If there is anything you can recommend adding to the article, please let me know.

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
