### ISSUE TITLE
Link to "Compliance Framework for Industry Standards and Regulations" in section "Compliance standards" leads to a 404. 

### ISSUE THREAD

**Issue by jackhammer84** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4175]
As per title above. Here is the mentioned section: https://docs.microsoft.com/en-us/microsoftteams/security-compliance-overview#compliance-standards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca579d63-182b-d6f5-8777-79248fa27ed9
* Version Independent ID: b4c27d1b-b2f1-41ac-b15c-d12b448a539e
* Content: [Overview of security and compliance in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/security-compliance-overview#compliance-standards)
* Content Source: [Teams/security-compliance-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/security-compliance-overview.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@jackhammer84 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by pauljohnstone** [comment]
Hi was there any update to this link / PDF?

https://download.microsoft.com/download/1/4/3/1434ABAB-B8E9-412D-8C3A-187B5FCB7A2F/Compliance%20Framework%20document.pdf

**Comment by scanum** [comment]
@jackhammer84 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
