### ISSUE TITLE
Reporting on call queues 

### ISSUE THREAD

**Issue by kailashkalyani** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4177]
There seems to to almost no information on this topic. Would you please include links to resources or articles covering this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b755d9ae-13ac-019f-f5f4-a95b1eee2989
* Version Independent ID: f7afd8ad-e6e0-6c79-aed1-4ee87d48ba12
* Content: [Create a call queue - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue#feedback)
* Content Source: [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-call-queue.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@kailashkalyani Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@kailashkalyani Thanks for reaching out. It looks like the article was updated two weeks ago. Please let me know if there is anything that you think still needs to be added to the article.

**Comment by scanum** [comment]
@kailashkalyani Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
