### ISSUE TITLE
How to avail PROMO CODES?

### ISSUE THREAD

**Issue by coco6969** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4178]
Who are the "Microsoft account rep" or "Microsoft Partners" mentioned here? The partners themselves don't know how to get the promo code for their clients. Please provide clearance and guidance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779619a7-95a8-c775-0538-4f07abb7067e
* Version Independent ID: cf930116-3d9d-2075-5291-f819cb17a234
* Content: [Manage the free Office 365 E1 Trial - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/e1-trial-license#feedback)
* Content Source: [Teams/e1-trial-license.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/e1-trial-license.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by LAPSTEC** [comment]
Aqui no Brasil também estamos tendo esse dilema, não sabemos como prosseguir.

**Comment by scanum** [comment]
@coco6969 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by vseven** [comment]
Would love to sign up for this but I contacted a rep at Microsoft.  They said I needed to contact my reseller (CDW).  Contacted CDW and they have no idea how to get any codes.  Can someone provide some guidance?

**Comment by Shridharkanchagar** [comment]
Hi, you need to reach out to your Microsoft contact if at all you have any.

**Comment by deep-water-planet-one** [comment]
We tried reaching out to our Microsoft contact. They knew nothing either and suggested reaching out to you.

**Comment by scanum** [comment]
@coco6969 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
