### ISSUE TITLE
Uninstallation Procedure Incomplete 

### ISSUE THREAD

**Issue by G0B1IN5486** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4179]
The uninstall procedure recommends uninstalling using a PowerShell script but does not go into more detail or even include a link to the script. Where is the script?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi#feedback)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@G0B1IN5486 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@LanaChin Could you possibly assist with this please?

**Comment by LanaChin** [comment]
Followed up with PM.

**Comment by scanum** [comment]
@LanaChin Any update on this issue? Thanks.

**Comment by LanaChin** [comment]
@G0B1IN5486 - thanks for your feedback. The PowerShell script was removed and the doc has been updated to reflect this.
