### ISSUE TITLE
Links in introduction are broken

### ISSUE THREAD

**Issue by mikepowell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#418]
They should be:
https://download.microsoft.com/download/2/E/E/2EE5C4DE-7F12-475C-A507-37870020F0D3/Plan%20Voice%20Solution%20poster%20-%20Final.vsdx
and
https://download.microsoft.com/download/2/E/E/2EE5C4DE-7F12-475C-A507-37870020F0D3/Plan%20Voice%20Solution%20poster%20-%20Final.pdf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6bbbb4-413c-75e1-39f1-fb99362bfaf4
* Version Independent ID: 00a7a85c-0e4d-40c6-e496-fb89c86df85e
* Content: [Plan your Phone System in Office 365 (Cloud PBX) solution](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/plan-your-phone-system-cloud-pbx-solution)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/plan-your-phone-system-cloud-pbx-solution.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/plan-your-phone-system-cloud-pbx-solution.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by kenwith** [comment]
@mikepowell - thank you for reporting. I created a PR with the new links: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/421 

Appreciated!

FYI - these are open source now so you can make edits as a PR when you would like.

**Comment by mikepowell** [comment]
No problem! I'll do a PR next time. :)
