### ISSUE TITLE
How to convert a Team group to Office 365 group?

### ISSUE THREAD

**Issue by 24mu13** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4180]
Is possible to convert an existing team group to a more extended Office 365 group?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a2187e-570d-f235-3536-69df8eaa906a
* Version Independent ID: da949f22-1617-c737-d5a4-5c51704443e8
* Content: [Enhance existing Office 365 groups with Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/enhance-office-365-groups#feedback)
* Content Source: [Teams/enhance-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enhance-office-365-groups.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by sgtdonny** [comment]
Your question is confusing. A Team is based on an Office 365 group. Only the other way around is possible, a standalone Office365 group.

**Comment by scanum** [comment]
@24mu13 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
