### ISSUE TITLE
Script doesn't work

### ISSUE THREAD

**Issue by sgtdonny** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4182]
This script could not connect the users that are prepared on the auxiliary script.

AADSTS90002: Tenant 'authorize' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 99036b5e-f358-fda3-d9b1-1279952b59a5
* Version Independent ID: 9ea42c59-7db5-9c66-ef58-98b4909ccd10
* Content: [PowerShell-Skript zum Testen der Verbindungen des direkten Routing Sitzung-Grenz Controllers - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/sip-tester-powershell-script)
* Content Source: [Teams/sip-tester-powershell-script.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sip-tester-powershell-script.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@sgtdonny Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sgtdonny** [comment]
Any news?
I would use it on the MS-700 course. COuld be a nice debbuging feature.

**Comment by Reeced40** [comment]
@LanaChin

**Comment by DavidMcGrathUnionStreet** [comment]
I am also getting the same error, is there any idea of when this may be fixed?

Regards and stay safe!

**Comment by DavidMcGrathUnionStreet** [comment]
I have found a work around to the issue. I uninstalled the latest version of adal.ps and installed the previous version. After that the script ran as expected. I used the following PowerShell command to achieve this from and admin PowerShell window.

Uninstall-Package -Name adal.ps
Install-Module -Name ADAL.PS -RequiredVersion 3.19.8.1

**Comment by scanum** [comment]
@sgtdonny thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by sgtdonny** [comment]
Sorry, i had a service ticket and MS support said, it has to be solved on Github.
