### ISSUE TITLE
Measuring User Engagement within 1 Single Team in an Enterprise

### ISSUE THREAD

**Issue by haleyhackendale** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4183]
Hi,

I am managing 1 Team within my global enterprise of 30,000 users and *many* separate Microsoft Teams. I need to measure user engagement with my 1 single team, to report on "community activity."

Whether I look at the Analytics tab in the Teams application, or get my IT team to look at the Reports in Admin Center, either way it is still vague. It will tell me the number of Active Users in my Team during a range - but I KNOW that does not mean that all those users are performing "intentional actions" (as per Microsoft's definition) within my 1 single Team, because there simple aren't that many new messages / likes / replies, etc. It must be that it's reporting that they are active on the application overall, enterprise wide.

Looking at the number of messages posted doesn't help me either given that a) it doesn't show likes/reactions to messages, and b) it doesn't show whether those total number of messages are from unique users or the same users.

How can I get some clear direction on whether we can dial down to this level... and if so, how to do it? 

Thanks in advance!
Haley

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81440b2f-391b-5856-a216-15866f37082a
* Version Independent ID: cdd15cd4-d4ed-c413-e2b9-ebf6dad8b33b
* Content: [Use activity reports for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-activity-reports)
* Content Source: [Teams/teams-activity-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-activity-reports.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@haleyhackendale thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
