### ISSUE TITLE
Related Powershell Commands

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4184]
As the Teams Web GUI is not working at the moment, I am missing the related PowerShell commands in this documentation.
* Enable and Disable External Access (not Guest Access)
* Editing Allow or Blocked Domains

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external access (federation) in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access#feedback)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@weyCC81 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by weyCC81** [comment]
Part 1:
Enable and Disable External Access (not Guest Access)
= Get-CsTenantFederationConfiguration

**Comment by rz7k9k** [comment]
i checked my organisations with = Get-CsTenantFederationConfiguration
result
Identity                            : Global
AllowedDomains                      : AllowAllKnownDomains
BlockedDomains                      : {}
AllowFederatedUsers                 : True
AllowPublicUsers                    : True
TreatDiscoveredPartnersAsUnverified : False
SharedSipAddressSpace               : False

but in teams app i cannot find any external users ?

**Comment by weyCC81** [comment]
Hi @rz7k9k 

**Here some explanation:**
There is a difference between Guest-User and External-User on both types it is possible enable/disable the general use and further more possible to add restrictions on different domains.

Guest-User: Can be invited to teams (group) and share files with internal user
External-User: Can only chat with internal user

https://docs.microsoft.com/en-us/microsoftteams/guest-access-powershell#guest-access-vs-external-access


_Part 1 Enable/Disable External User_
I think this can be solved with an of the following parameters:
`Get-CsTenantFederationConfiguration | fl AllowFederatedUsers, AllowPublicUsers`

_Part 2 Allow/Block Domain for External User_
I think this can be solved with a combination if the following parameters
`Get-CsTenantFederationConfiguration | fl AllowedDomains, BlockedDomains, AllowedDomainsAsAList`


_Part 3 Enable/Disable for Guest User_
Could that be the following command?
`Get-CsTeamsClientConfiguration | fl AllowGuestUser`

_Part 4 Allow/Block Domain for Guest User_
Could that be the following article?
https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-group-access-to-office-365-groups?redirectedfrom=MSDN
Is there a Get for `Set-GuestAllowBlockDomainPolicy.ps1`?

**Comment by rz7k9k** [comment]
Hi weyCC81,
thanks for your reaction.
i checked all the settings on my domain and 'External users' is enabled.
But i cannot connect to users in a different domain with TEAMS
i checked it with powershell and also on Office.com Teams settings.

**Comment by Reeced40** [comment]
@weyCC81 Thank you for reaching out. The document was updated recently. Please let me know if you can't find what you're looking for.

**Comment by rz7k9k** [comment]
@weyCC81 just to let you know that the problem was that some of my on premise users that are synced to Azure AD had old attributes of an on premise lync server. I removed everything and problem solved.

**Comment by scanum** [comment]
@rz7k9k @weyCC81 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by weyCC81** [comment]
@Reeced40 Which commit are you talking about? I can not find any changes which relate to new powershell scripts/commands.
