### ISSUE TITLE
Commercial MSI files

### ISSUE THREAD

**Issue by brazilianthunder** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4185]
The link to both commercial MSI files download files that end with .msi.exe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Microsoft Teams using MSI via Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment#feedback)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@brazilianthunder Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@brazilianthunder Thank you for reaching out to improve MS Docs. I've checked the links, and they ends in .msi Please confirm if this is correct, as the article has recently been updated.

**Comment by scanum** [comment]
@brazilianthunder Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
