### ISSUE TITLE
Mac Teams App won't display new chat messages on Chat tab

### ISSUE THREAD

**Issue by viksd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4186]
If a message is received from a sender that you have not previously conversed with, a notification is received but a new conversation is not created in the Chat's tab. 

The web application does create a new chat conversation and works as expected. See the screenshot for the same account signed into the Mac app as well as the web app. The web app shows newers chats that aren't displayed on the Mac app.

![Screen Shot 2020-03-17 at 9 50 38 AM](https://user-images.githubusercontent.com/9911592/76880479-f4a0fa00-6834-11ea-823b-d9ef3faba08d.png)

**Comment by scanum** [comment]
@viksd thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
