### ISSUE TITLE
The Powershell command to get users based on skuid is mistyped.

### ISSUE THREAD

**Issue by banesend** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4187]
$faculty = Get-AzureADUser -All $true | Where-Object (($_.assignedLicenses).SkuId -contains "e97c048c-37a4-45fb-ab50-922fbf07a370")
should be
$faculty = Get-AzureADUser -All $true | Where-Object {($_.assignedLicenses).SkuId -contains "e97c048c-37a4-45fb-ab50-922fbf07a370"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe8cc5e-0f33-d33a-6765-a3f3a33f1522
* Version Independent ID: 13cc4718-4967-695d-cd07-13c3021d8682
* Content: [Assign policies to large sets of users in your school - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/batch-policy-assignment-edu#feedback)
* Content Source: [Teams/batch-policy-assignment-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/batch-policy-assignment-edu.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@banesend Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@banesend Thank you for reaching out. It looks like the powershell has been fixed in the interim. Can you please confirm.

**Comment by banesend** [comment]
Confirmed. The command has been fixed.

**Comment by asantiag** [comment]
I having this difficulty.  I've about 300 students with License SKU ID: c32f9321-a627-406d-a114-1f9c81aaafac
What could be wrong?

First command:
OperationId    : 13258179-7786-4684-8707-6eb33d79e3fd
OperationName  : 
OverallStatus  : Completed
CreatedTime    : 4/6/2020 2:01:11 PM
CreatedBy      : d0605793-6ecd-4e07-81a9-cf3d66c97492
CompletedTime  : 4/6/2020 2:01:13 PM
CompletedCount : 36
ErrorCount     : 36
PendingCount   : 0
UserState      : {8f2e9d3e-d9b6-4ed1-9a33-adb26062c09e, 
                 46968960-6b1d-4ccf-a689-966f6a247c3a, 
                 6cc0ad52-97a7-463e-8b01-31e1e4b39fd4, 
                 75bc0be3-8016-4b12-ae21-4dddbc503146...}

Second command:

Id                                   Result                                    State    
--                                   ------                                    -----    
8f2e9d3e-d9b6-4ed1-9a33-adb26062c09e Please contact your system administrator. Completed
46968960-6b1d-4ccf-a689-966f6a247c3a Please contact your system administrator. Completed
6cc0ad52-97a7-463e-8b01-31e1e4b39fd4 Please contact your system administrator. Completed
75bc0be3-8016-4b12-ae21-4dddbc503146 Please contact your system administrator. Completed
3f16bbad-5f9c-4a49-b9c3-8981de0f1525 Please contact your system administrator. Completed
7fe4cc48-a80a-444b-b181-8e9ddbba7aba Please contact your system administrator. Completed
fafbd2d5-119c-4523-a463-4b08d1c08fa1 Please contact your system administrator. Completed
91f49d44-a82a-4d2a-9c3b-36093353d95a Please contact your system administrator. Completed
26eec24f-b6f4-47eb-b280-d351190eb1c8 Please contact your system administrator. Completed
c419e30a-bf4f-4a11-84fe-0128fa9cc0fd Please contact your system administrator. Completed
43ce0a10-8da7-4047-9386-2ff44441bbc9 Please contact your system administrator. Completed
5d9bf36c-2fbe-4939-a532-360a4b9bc078 Please contact your system administrator. Completed
1975fd72-ac44-4a08-a865-13985bae8b21 Please contact your system administrator. Completed
957f9b2b-1c81-4e1a-9115-ef9799329ae8 Please contact your system administrator. Completed
be64c474-ea0f-4d4a-a6e8-d79e9d3f7b5a Please contact your system administrator. Completed
76e9a20a-f5b0-4d7c-afca-4e801515f5f2 Please contact your system administrator. Completed
401a7609-5bca-4296-b0c2-5c4425ec6a4f Please contact your system administrator. Completed
3f3574f8-a384-4970-966e-77f2e907efca Please contact your system administrator. Completed
f81a32cd-ba30-4035-8f65-5efc03c53f23 Please contact your system administrator. Completed
87fc2f70-a35d-434c-9b92-f644ade5d9c3 Please contact your system administrator. Completed
2a0181b8-a951-49dc-a80d-ef3d7adba5a1 Please contact your system administrator. Completed
8b3b6d24-8160-4fd4-ba3f-c7e393bb9eac Please contact your system administrator. Completed
6a0e9309-0b54-4b01-ad4d-ecb4b73144a7 Please contact your system administrator. Completed
04854e4f-2bea-423e-987c-bf7b36172323 Please contact your system administrator. Completed
da9fa43a-a142-4752-878a-1f3e585f3c27 Please contact your system administrator. Completed
78dbeb4a-6d65-4a70-b2c4-a5cfab3f8e91 Please contact your system administrator. Completed
023bae83-bf27-42cd-a703-69a0a88ef663 Please contact your system administrator. Completed
b46c94e1-9b19-458c-be59-47273370b233 Please contact your system administrator. Completed
4da95804-4e33-4993-95ed-ae2ceea422c7 Please contact your system administrator. Completed
f7d60201-6454-4c89-9ff6-541d010fd043 Please contact your system administrator. Completed
d52a55bc-c1d3-47e7-ab68-c4a85598ae1e Please contact your system administrator. Completed
c3b6627b-a2c3-4de0-a7e0-6ee104c58fb7 Please contact your system administrator. Completed
9390746d-d5fe-4a59-935e-f00ee56050d7 Please contact your system administrator. Completed
e60f11c2-88c2-4bd3-ac71-204372f0e5cb Please contact your system administrator. Completed
1c3d124c-f740-4d26-9511-eaa30f2bdcb0 Please contact your system administrator. Completed
d0763e30-8134-4221-88b3-1c7598c4af5a Please contact your system administrator. Completed

**Comment by scanum** [comment]
@banesend Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
