### ISSUE TITLE
Powershell or Graph API available?

### ISSUE THREAD

**Issue by Elecktrus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4188]
Is it possible to get this information about Call Quality using powershell or programmatically with Graph?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9374347d-42cb-4955-6eac-3efd04eef66d
* Version Independent ID: 985dbd00-b456-13c3-5928-b423084d3a87
* Content: [Monitor and troubleshoot Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-monitor-and-troubleshoot#feedback)
* Content Source: [Teams/direct-routing-monitor-and-troubleshoot.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-monitor-and-troubleshoot.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Elecktrus thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
