### ISSUE TITLE
How does one set the TeamsMeetingPolicy back to default using this?

### ISSUE THREAD

**Issue by banesend** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4189]
I attemtped to pass -PolicyName $null and it throws an invalid policyname error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe8cc5e-0f33-d33a-6765-a3f3a33f1522
* Version Independent ID: 13cc4718-4967-695d-cd07-13c3021d8682
* Content: [Assign policies to large sets of users in your school - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/batch-policy-assignment-edu#feedback)
* Content Source: [Teams/batch-policy-assignment-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/batch-policy-assignment-edu.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by banesend** [comment]
Global also shows Invalid PolicyName

**Comment by scanum** [comment]
@banesend thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
