### ISSUE TITLE
Limits for tags not explicitly called out

### ISSUE THREAD

**Issue by adyst** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4194]
Can limits for tags (not default tags, which is called out) be explicitly called out? Trying to figure out if it's limitless or not.  I see a limit of 25 under default tags, but it's unclear if this extends to all tags.

It may belong in this document, as well: https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b16e659e-cf07-268a-e224-fa444749ac29
* Version Independent ID: ee822a8d-b331-998f-e336-b1fa510f35c0
* Content: [Manage tags in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-tags#feedback)
* Content Source: [Teams/manage-tags.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-tags.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@adyst Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@adyst Thank you for reaching out. I've investigated further and found out that Teams can have up to 100 tags, but only 25 characters per tag. Please can you confirm this @LanaChin and I can have it added it to the articles.

**Comment by LanaChin** [comment]
Followed up with PM.

**Comment by LanaChin** [comment]
Thanks for your feedback and helping to improve our docs, @adyst.  @Reeced40, thanks for your research into this.  Both articles have been updated to reflect limits for tags:

- https://docs.microsoft.com/microsoftteams/limits-specifications-teams#tags
- https://docs.microsoft.com/microsoftteams/manage-tags
