### ISSUE TITLE
Teams Exploratory- Failed to upload file attachment

### ISSUE THREAD

**Issue by Yoeeee** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4195]
It is confusing that based on the licensing there is a default 2gb personal storage for file attachment but then every time we try to attach a file we receive an error.

Based on my understanding for you to attach a file you should have a onedrive or any cloud related storage. Correct me if im wrong.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f897ae9b-852a-b617-7de0-d76dbd9f1820
* Version Independent ID: 161b1845-53fd-8912-a5f9-737d3bcdaadc
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-exploratory#feedback)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Yoeeee thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
