### ISSUE TITLE
Teams Machine Installer with ALLUSER=1 is not installing TeamsPresence status for ALL users in Outlook

### ISSUE THREAD

**Issue by skest3qc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4199]
Hi,
we are using Teams Machine Installer with parameter ALLUSER=1 to perform a VDI installation.
Everything is working except Outlook presence status. After troubleshooting this i can see that the installer is creating several keys for the account which is running the setup for Microsoft Teams. These keys are going to HKEY_CURRENT_USER key and are only working for the logged on user, they should go to HKLM. If another user logs on these keys are not present and Outlook presence status is not working.
Example keys:
HKCU\Software\Classes\Interface
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a162ef5c-3099-7f58-4178-d29e3ec2b5a7
* Version Independent ID: 6ca31e56-052d-6c62-1323-b5aaaae1f04a
* Content: [User presence in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/presence-admins)
* Content Source: [Teams/presence-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/presence-admins.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@skest3qc thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
