### ISSUE TITLE
Collaboration Bars?

### ISSUE THREAD

**Issue by adagioajanes** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4200]
What on earth is a Collaboration Bar? I did a web search for it, and can't find anything describing what it is...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5d65acb-f012-b05d-c871-69b8f187e537
* Version Independent ID: 06710d00-f076-11c4-3f69-cfd979c5554a
* Content: [Manage devices - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/business-voice/manage-devices)
* Content Source: [Teams/business-voice/manage-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/business-voice/manage-devices.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by AlvagP** [comment]
I was also wondering about the Collaboration Bars, and after a web search I found some information from Microsoft Ignite. It says:
Your Microsoft Teams Meeting rooms are set for a major upgrade. As part of this year’s Ignite Event, Microsoft announced the arrival of “collaboration bars”, a new selection of devices from Microsoft partners intended to convert huddle spaces into environments for online meetings and collaboration.

Follow this link and there is a bit more information about it under number 4:
https://www.uctoday.com/collaboration/team-collaboration/exciting-teams-updates-from-microsoft-ignite/

**Comment by adagioajanes** [comment]
Very interesting. Excited to see what whats in store for these devices...

**Comment by scanum** [comment]
@adagioajanes  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@adagioajanes Thank you for your feedback. Please let me know if there's anything else you want to know.

**Comment by adagioajanes** [comment]
I think it would be useful if there was a link to collaboration bars, like their is for desk phones and conference phones. There still isn't any info in the documentation itself as to what this is.

**Comment by Reeced40** [comment]
@adagioajanes Please let me know if this link helps -  https://techcommunity.microsoft.com/t5/microsoft-teams-blog/the-first-collaboration-bar-for-microsoft-teams-is-now-available/ba-p/1231706

**Comment by scanum** [comment]
@adagioajanes We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
