### ISSUE TITLE
Skype for Business PowerShell module is required

### ISSUE THREAD

**Issue by adrianwells** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4201]
Please add notes that the Skype for Business PowerShell module is required for these cmdlets. Suggest referencing a URL link https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cb395f1-fce4-2d64-c66e-36a6cd818ca6
* Version Independent ID: 79bf1d7e-8cbc-5146-dfda-a6ae38d49be7
* Content: [Use PowerShell to set live events policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/set-teams-live-events-policies-using-powershell)
* Content Source: [Teams/teams-live-events/set-teams-live-events-policies-using-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/set-teams-live-events-policies-using-powershell.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@adrianwells  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LanaChin** [comment]
The doc has been updated. Thank you.
