### ISSUE TITLE
What's new in the Help section of the Teams app points to a page that cannot be found

### ISSUE THREAD

**Issue by Mlavieri** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4202]
When navigating to What's new in Teams the page shows an error that the page cannot be found. 

![image](https://user-images.githubusercontent.com/1187519/76980895-c5a78880-6907-11ea-99db-b9a7d2f8bb00.png)

I believe the page should point here: https://support.office.com/en-us/article/what-s-new-in-microsoft-teams-d7092a6d-c896-424c-b362-a472d5f105de 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Mlavieri thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
