### ISSUE TITLE
Is 1:1 or 1:N Guest eDiscovery possible and how is it done?

### ISSUE THREAD

**Issue by itbland** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4207]
At the end of closed issue #1846, @jgoakley asked:

> The section titled "eDiscovery of guest-to-guest chats" is self contradicting because it states:
> 
> "Presently, for a scenario where only guests are participating in 1:1 or 1:N chat, **_we don't support eDiscovery of those chat messages_**. Without a mailbox, guest-to-guest chats (1xN chats in which there are no home tenant users) would not be indexed, and as a result, would not be included in eDiscovery."
> 
> And then immediately following states:
> 
> **_To facilitate eDiscovery for guest-to-guest chats_**, a cloud-based mailbox (or phantom mailbox) is created to store the 1xN data. After the Teams chat data is stored in the cloud-based mailbox, it is indexed for eDiscovery and compliance content search."
>**_From the text it is unclear what steps, if any, can or need to be taken to enable eDiscovery of guest-to-guest chats._**
> Thanks!
> 

Please answer! Thx!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 840dd36b-8c29-9738-4adc-ea9a7d277fd0
* Version Independent ID: b12c43c3-ed81-ace5-dfeb-77cac0f97fe9
* Content: [Conduct an eDiscovery investigation of content in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/ediscovery-investigation#feedback)
* Content Source: [Teams/eDiscovery-investigation.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/eDiscovery-investigation.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@itbland  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @itbland, thank you for your feedback.

This article was updated 3 days ago and now we only have this note about "guest-to-guest chats":
"At this time, we don't support eDiscovery of chat messages in scenarios where guest users are the only participants in a 1:1 or 1:N chat. These types of chats are also called guest-to-guest chats because they don't include home tenant users."

**Comment by itbland** [comment]
Thanks for the clarification!
