### ISSUE TITLE
Reports Not Showing for Teams Communications Admin

### ISSUE THREAD

**Issue by geektbee** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4208]
This article states that a "Teams Communications Admin" should be able to see Reports. We have a user with this role, but is unable to see reports. I'm assuming that's because the article is providing data that once was true, but is no longer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ade1a4-092c-1132-44df-ee2c683fdd33
* Version Independent ID: 396b1aee-2f40-9895-9b00-07e38d11d31b
* Content: [Microsoft Teams analytics and reporting - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-reporting-reference#feedback)
* Content Source: [Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@geektbee  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LanaChin** [comment]
@geektbee - thanks so much for your feedback and helping us to improve our docs. These articles have been updated to clarify which reporting access for admin roles:

- https://docs.microsoft.com/microsoftteams/teams-analytics-and-reports/teams-reporting-reference
- https://docs.microsoft.com/MicrosoftTeams/using-admin-roles
