### ISSUE TITLE
Incorrect menu option for Billing

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4210]
The following path is not valid under the New Admin Center experience
"You can also see information about pricing by signing in to the Microsoft 365 admin center and going to Billing &gt; Subscriptions &gt; Add subscriptions."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d52a9779-b72d-dea0-eac2-6c04a8c282eb
* Version Independent ID: d3c3d968-9e54-ec42-3438-9320e23d68b9
* Content: [What are Communications Credits? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/what-are-communications-credits?toc=/skypeforbusiness/toc.json&bc=/skypeforbusiness/breadcrumb/toc.json)
* Content Source: [Teams/what-are-communications-credits.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-communications-credits.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by jantoney** [comment]
It should be 

Billing > Purchase Services

**Comment by scanum** [comment]
@jantoney  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@jantoney Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
