### ISSUE TITLE
250 meeting limit - please define

### ISSUE THREAD

**Issue by StPhil** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4213]
What’s missing here: what is included in the 250? If a Teams user is logged in with one identity on two devices, it counts as one. If a user is logged in to the Teams meeting and dials in, that’s two. This information should be defined on this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#feedback)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@StPhil  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @StPhil, thank you for your feedback.

It's hard for me to test a 250 people meeting. But... I think your meeting can have a list of 250 people. If you join with the same identity to a meeting it counts as 1. If you join using dial-in number you join as guest, so different identity.

**Comment by jgonzalezbgc** [comment]
Is there a chance to increase this limit to 500 or 1000? My company is just below 500 and Live Events doesn't cut it as it is too much of a formal meeting with delay streaming. Zoom and others offer at least 500, so we resorted to using yet another meeting tool to satisfy this need. Odd times require creative ideas and answers to problems.

**Comment by dariomws** [comment]
Hi @jgonzalezbgc, the place to request features is User Voice. Please vote it:
https://microsoftteams.uservoice.com/forums/599053-schools-and-universities/suggestions/36681970-increase-maximum-meeting-participants-to-500

**Comment by scanum** [comment]
@StPhil Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
