### ISSUE TITLE
Бесплатная версия (Free version)

### ISSUE THREAD

**Issue by Akackk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4214]
Можно ли получить полный список ограничений и возможностей бесплатной версии?
Сколько человек может принимать участие в одной видеоконференции, какова продолжительность конференций в часах за один раз и в целом в месяц и т.д. 
Can I get a complete list of limitations and features of the free version?
How many people can take part in one videoconference, what is the duration of conferences in hours at a time, and in general per month, etc.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Ограничения и спецификации для Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/ru-ru/microsoftteams/limits-specifications-teams#feedback)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Akackk  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@officeglobal could you please help on this issue? Thanks!

**Comment by OfficeGlobal** [comment]
@scanum article is being HumanTranslated, but it seems the question is related to an author of the article. Could you please check it one more time?

_Akackk's Question:_
Can I get a complete list of limitations and features of the free version?
How many people can take part in one videoconference, what is the duration of conferences in hours at a time, and in general per month, etc.

**Comment by scanum** [comment]
@OfficeGlobal Thanks for letting us know! Appreciate your help.

**Comment by LolaJacobsen** [comment]
@Balu-msft can you confirm that the free versions of Teams have all the capabilities/limitations of the paid version?

**Comment by LolaJacobsen** [comment]
@Akackk  thanks for your inquiry. For Teams Exploratory and the recent free E1 Teams trial, all capabilities are the same. For Teams Free, there are differences. Check out the comparison in this article:

https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/compare-microsoft-teams-options
