### ISSUE TITLE
Question&Answer app development using MS Teams

### ISSUE THREAD

**Issue by Rani86** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4217]
Hi Team,

As MS Teams is a community feature provided by Office 365 for a closed circle of 5000 members . Can we develop Question and Answer application similar to Quora using MS Teams ?

Thanks,
Rani

**Comment by scanum** [comment]
@Rani86 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
