### ISSUE TITLE
does Teams coexistence mode for the user matter? Do they need to be in TeamsOnly mode?

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4221]
specifying one way or another could be helpful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events#who-can-create-and-schedule-live-events)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@anwarmahmood1  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LanaChin** [comment]
Followed up with PM.

**Comment by scanum** [comment]
@anwarmahmood1 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by anwarmahmood1** [comment]
How? Nothing in these comments addresses my question; the page hasn't been updated in any way either.  Manuela, please clarify what you mean.

**Comment by anwarmahmood1** [comment]
Apologies Manuela. I can see now that draft changes are in progress.  Feel free to close this feedback item.
