### ISSUE TITLE
Seat Count Confirmation

### ISSUE THREAD

**Issue by v-mihwan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4223]
Hi, I'm wondering if I could get clarification on the seat count for this offer. It's defaulted to 100 but it states it's available to anyone with an AAD domain. If they buy additional Azure Active Directory Plan 1 licenses will they be able to activate the offer for each of these users?

**Comment by scanum** [comment]
@v-mihwan thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
