### ISSUE TITLE
"Teams Discovery" not there?

### ISSUE THREAD

**Issue by kelemvor33** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4224]
Howdy, When I go to: "On the Settings tab, expand Team discovery", I don't have a Team Discovery section for any of the teams that I'm an owner of.  Is there something else I need to turn on to get that setting to show up?
When I go to my Teams Policies, the Discover Private Teams option is ON for our Global policy.
Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5920152-5fee-41ed-56df-ad7b51b25cc2
* Version Independent ID: 88cfc850-5e36-48ee-ba99-088b2b653f1e
* Content: [Manage discovery of private teams in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-discovery-of-private-teams)
* Content Source: [Teams/manage-discovery-of-private-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-discovery-of-private-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@kelemvor33 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
