### ISSUE TITLE
Clarify recommended licensing/config for Intune device management

### ISSUE THREAD

**Issue by testad** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4228]
Hi, I would appreciate if the documentation could include a recommendation on how the room device is expected to be licensed for Intune. This article from the Intune team recommends using a DEM account to AAD join Windows on the MTR for Intune management: https://techcommunity.microsoft.com/t5/intune-customer-success/managing-teams-meeting-rooms-with-intune/ba-p/1069230

This DEM account can be configured as a separate account, which requires an extra Intune license, or it could be the same as the meeting room account licensed with the Meeting Room SKU (which is suggested by Scott Duffy in the article's comments from 12-18-2019). But I am missing a documented best practice. I would assume the meeting room account should also be used for AAD joining Windows as it has Intune included new the new Room SKU? But I want to make sure that I am not missing something as I cannot find anything about DEM or Intune management here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing#feedback)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-licensing.md)
* Service: **skype-for-business-online**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@testad  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @testad, thank you for your feedback.

In the article by Scott Duffey you have your answer:
"DEM accounts are used for shared devices in Intune. When shared devices are enrolled with DEM accounts, Intune knows they are shared instead of a single-user device. DEM accounts can also enroll more than 15 devices (A limit that exists for normal accounts). You could possibly make the MTR room account a DEM account."

@LanaChin could you kindly help? I want to confirm this and I want to add some information about DEM account in the article.

**Comment by LanaChin** [comment]
Followed up with PM.

**Comment by LanaChin** [comment]
@testad  - thanks for your feedback. The blog has been updated to clarify that the Meeting Room resource account can be used for Intune enrollment but not for Windows logon on the device.
