### ISSUE TITLE
Missing Option

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4229]
This section says there is an option to manage users.  This does not exist in the UI
https://docs.microsoft.com/en-US/microsoftteams/create-and-manage-dial-plans#add-users-to-a-dial-plan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 451b44cf-961a-5bf5-e4b3-16b96e008dd7
* Version Independent ID: 54e706e1-aaa2-3a03-b8c6-5e96244b85ac
* Content: [Create and manage dial plans - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/create-and-manage-dial-plans#add-users-to-a-dial-plan)
* Content Source: [Teams/create-and-manage-dial-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-and-manage-dial-plans.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@danmyhre  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by danmyhre** [comment]
I did find that the option to assign a user to a dial plan is available under:
Users -> User -> Policies -> Edit -> Dial plan

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
