### ISSUE TITLE
"Clean up and redeployment procedure" is incomplete

### ISSUE THREAD

**Issue by andshrew** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4231]
The current procedure for this seems to be a bit confusing and is missing steps.

From what I have tested the procedure to enable a re-installation of Teams for a user who has uninstalled it should be:- as the user...

- Delete ` %localappdata%\Microsoft\Teams\`
- Delete `HKEY_CURRENT_USER\Software\Microsoft\Office\Teams\PreventInstallationFromMsi`
- Log off and back on, and the system wide installation will re-install Teams for the user

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Microsoft Teams using MSI via Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment#feedback)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by wayneforrester** [comment]
Agree with this, ended up having to use to ProcMon to figure out why Teams was not re-installing. Cause was this user key: HKEY_CURRENT_USER\Software\Microsoft\Office\Teams\PreventInstallationFromMsi

After removing this key, re-installation was fine.

**Comment by scanum** [comment]
@andshrew  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @andshrew, thank you for your feedback.

Same as https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4068.

**Comment by D-Jeffrey** [comment]
Maybe this is not the place for PG feedback, but why would there not be a installation feature/option for doing a clean installation by doing a removal of existing per user installations with the full install?

**Comment by dariomws** [comment]
Hi @D-Jeffrey, for product feedback you can go to:
https://microsoftteams.uservoice.com/

Thank you!

**Comment by scanum** [comment]
@andshrew Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
