### ISSUE TITLE
Limits for calling from Chat

### ISSUE THREAD

**Issue by thomasbinder** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4232]
According to https://support.office.com/en-us/article/Start-a-call-from-a-chat-in-Teams-f5138c9d-df4c-43d8-9cf6-53400c1a7798#ID0EAABAAA=Desktop there is a limit on 50 users for calls from chat: "Up to 50 people can be on the same video call."

Is this information correct? If so, would you mind to add it on this page as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by thomasbinder** [comment]
Just found the footnote: "If you have more than 20 people in a chat, the following chat features are turned off: Outlook automatic replies and Teams status messages; typing indicator; video and audio calling; sharing; read receipts."

Can you get the support office article updated?

**Comment by scanum** [comment]
@thomasbinder  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @thomasbinder, thank you for your feedback.

@LolaJacobsen could you kindly help? How we can update support.office.com article?

**Comment by CDCB0** [comment]
Similar to this, we had an issue last Friday through Teams meeting - some participants lost the ability of 'chat' function in Teams meeting. Does Teams meeting have any limitation on chat function when it goes over certain number of participants? We had about 50+ participants in the meeting.

**Comment by LolaJacobsen** [comment]
I'm checking with PM Nakul Madaan.

**Comment by LolaJacobsen** [comment]
Working with PM Alan Xie (referred by NakulM).

**Comment by LolaJacobsen** [comment]
Hi, @thomasbinder. Thanks for pointing this out. I've updated our limits-specifications-teams.md file. Changes should go live later this afternoon. Cheers!
