### ISSUE TITLE
FAQ is incorrect 

### ISSUE THREAD

**Issue by Padavid** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4233]
I think this should be polices vs license.
Current FAQ - I want to make sure that all users that are students, staff, and educators automatically get licenses assigned.
Should be - Current FAQ - I want to make sure that all users that are students, staff, and educators automatically get policies assigned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe8cc5e-0f33-d33a-6765-a3f3a33f1522
* Version Independent ID: 13cc4718-4967-695d-cd07-13c3021d8682
* Content: [Assign policies to large sets of users in your school - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/batch-policy-assignment-edu#get-the-status-of-a-bulk-assignment)
* Content Source: [Teams/batch-policy-assignment-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/batch-policy-assignment-edu.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Padavid  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Padavid Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
