### ISSUE TITLE
Guests Tenant change inconvenience

### ISSUE THREAD

**Issue by pablovera100** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4234]
As far as I experimented, whenever you are invited to an organization as a guest, and you already have an organization, yo need to change the Tenant organization, that is not convenient, notifications are not showing as they normally do, and having to change your Tentant EVERY time you need to interact at different organizations is time consuming and pretty annoying. Is there any plan to completely integrate one Team for more than one organization? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [What the guest experience is like - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/guest-experience#feedback)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@pablovera100  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @pablovera100, thank you for your feedback.

This is all the information I have:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/17750851-i-want-to-use-multiple-teams-accounts-at-the-same

If you want some else, you can add a new user voice item.

**Comment by scanum** [comment]
@pablovera100 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
