### ISSUE TITLE
Account Requirements

### ISSUE THREAD

**Issue by KennyLogin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4237]
We just went through this process, and found out that if you have restricted group creation (in our case, an on-prem AD group, synced to AzureAD/Office 365), the account used to create/convert the org-wide Team needs to be *both* a global admin *and* be a member of the AD group that has group creation rights. We opened a case with MS and this is how we resolved it, when a regular global admin tried to create org-wide Team, but was not able to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team?source=docs)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@KennyLogin  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @KennyLogin, thank you for your feedback.

Did you see the FAQ section? Are you trying to create this team using the Teams client?

"Is there a way to create an org-wide team other than using the Teams client?

Global admins can only create an org-wide team by using the Teams client. If your organization limits creating teams to using PowerShell, the recommended workaround is to add your global admins to the security group of users who can create a team. For more information, see Manage who can create Office 365 Groups.

If this isn't an option, you can use PowerShell to create a public team and add a global admin as the team owner. Then, have the global admin click More options next to the team name, click Edit team, and then change the privacy to Org-wide - Everyone in your organization will be automatically added. Note that only team owners can access the Edit team option and only global admins can see the Org-wide option."

**Comment by KennyLogin** [comment]
Yes, I was trying to created via the Teams client. Re-reading the first section makes sense. We had to rule that out (in the beginning), for reasons I'll explain further down. In addition, the second part "if this isn't an option", doesn't appear to work, or is unclear? We had to open a case with Microsoft, because creating a public team, and adding a global admin as the owner, isn't enough. They have to be a global admin *and* be in the restricted group to see the option to change the privacy to org-wide. Which is essentially the same as the first section, where the global admin needs to be in the AD group that's allowed to create groups.

In addition, this isn't a great security practice. We have non-privileged accounts, which are on prem, synced to O365 via AD Connect, along with the AD group that's allowed to create groups. Also, we have privileged accounts for O365, which are .onmicrosoft accounts and only exist in O365 (not synced from on-prem). I essentially had to elevate the permissions for my non-privileged account, as my privileged account doesn't exist on-prem (it's an onmicrosoft account for O365 admin), so I'm unable to add it to the restricted security group that was setup on-prem and synced via AD Connect.

Maybe we're a fringe case, or maybe I just didn't read it clearly, but the Microsoft support rep was unclear on it too.

**Comment by dariomws** [comment]
@KennyLogin thank you for this clarification.

Docs.microsoft.com feedback section is there to help us to improve documentation. If there is something specific that you think we can improve here we are welcome to hear from you. If not, I think we are ready to close this issue.

Thank you again!

**Comment by scanum** [comment]
@KennyLogin Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
