### ISSUE TITLE
Unclear policy setting in Messaging Policy

### ISSUE THREAD

**Issue by ykuijs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4238]
The first item in the Messaging policy says:
Change set to 'off'

What is meant here? It looks like some text is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 700c34b6-87de-19e2-9821-bc35e290948e
* Version Independent ID: 86be2050-e149-7f03-d2a8-d64f6f912012
* Content: [Microsoft Teams resources for Education admins - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/remote-learning-edu)
* Content Source: [Teams/remote-learning-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/remote-learning-edu.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@ykuijs  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@ykuijs Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mel-flcoe** [comment]
I don't think this is solved. I'm also not seeing an option in messaging policies labeled "Change"
