### ISSUE TITLE
Allow users to receive, but not place calls

### ISSUE THREAD

**Issue by kcsportal** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4239]
I would like my teachers to be able to initiate calls to students, but I do not want students to be able to place calls on their own. Is this possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410fc30b-f530-8443-0602-9150c9cba115
* Version Independent ID: c5b33b25-147b-f7d4-056a-987088950e7c
* Content: [Calling policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-calling-policy#feedback)
* Content Source: [Teams/teams-calling-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-calling-policy.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@kcsportal  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @kcsportal, thank you for your feedback.

I understand there is no practical way to do it. Disable calling using Calling policies prevent inbound/outbound calling. You can try blocking their phone number:
https://docs.microsoft.com/powershell/module/skype/new-csinboundblockednumberpattern

**Comment by kcsportal** [comment]
Ok, in this case, we are not using Teams for calling people with phone numbers just for internal calls to other Teams users in our tenant. 

Another alternative would be for students to be denied access to their web cam for "calls" but allowed web cams in meetings. It seems that currently, the "allow IP video" option in the Meeting policy controls video for both meetings and calls.

**Comment by dariomws** [comment]
Also, you can suggest this feature here:
https://microsoftteams.uservoice.com/

**Comment by scanum** [comment]
@kcsportal Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
