### ISSUE TITLE
Lock Meeting?

### ISSUE THREAD

**Issue by derricksmith** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4240]
The documentation indicates a user can lock a meeting.  Where is this configuration setting located in Teams?  Is this only a SfB setting?

**Comment by scanum** [comment]
@derricksmith Hi! Thanks for submitting feedback, could you please link the issue you are referring to? Thanks.

**Comment by dariomws** [comment]
Hi @derricksmith, thank you for your feedback.

Could you kindly provide the link to the article? Thanks!

**Comment by scanum** [comment]
@derricksmith We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
