### ISSUE TITLE
Teams meeting OWA exchange on-prem

### ISSUE THREAD

**Issue by Heafou** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4241]
Hello,
Is there any way to get the Teams meeting add-in for exchange 2016 OWA without using O365 Outlook ? 
Thank you for your help

**Comment by scanum** [comment]
@Heafou thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
