### ISSUE TITLE
Guest authentication behavior

### ISSUE THREAD

**Issue by glenrmag** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4243]
On the video above starting 5:03, it shows that guests that clicks the "Open Microsoft Teams" link will only be required to sign in using the code that will be sent to the same email address. In my tests, adding either Microsoft Account registered or non-registered guests does NOT ask for a code, but rather asks for the MSA password (for MSA registered guest) and it asks to register non-registered guests. If this is the current behavior, please update the video and documentation.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams guest access checklist - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@glenrmag Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @glenrmag, thank you for your feedback.

Do you have enabled one-time passcode authentication in your tenant? In this article you can find:
"Enable email one-time passcode for guests (Preview): For more information about the one-time passcode feature, see [Email one-time passcode authentication (preview)](https://docs.microsoft.com/azure/active-directory/b2b/one-time-passcode)."

**Comment by scanum** [comment]
@glenrmag Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
