### ISSUE TITLE
Can Edit guest information in M365 Admin Center

### ISSUE THREAD

**Issue by glenrmag** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4244]
As opposed to documentation "Currently, you can't edit guest information from the Microsoft Teams admin center, the Microsoft 365 admin center, or the Exchange admin center."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 941e0612-7854-9538-405c-8a8794b4cc04
* Version Independent ID: 9460ce27-6f84-ac04-cdf4-176faa1bb4bb
* Content: [Edit guest user information - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/edit-guests-information)
* Content Source: [Teams/edit-guests-information.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/edit-guests-information.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@glenrmag Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @glenrmag, thank you for your feedback.

I verified in my lab and I cannot see the option to edit Guest users. I think it's a view-only section.

Could you kindly share a screenshot with me?

**Comment by scanum** [comment]
@glenrmag We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
