### ISSUE TITLE
Class Team from existing group

### ISSUE THREAD

**Issue by alanbmhs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4247]
I don't appear to be able to create a Class Team from an existing group. Can I convert a staff or 'other' team to a class team as I can use an existing group with these 2 options?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a2187e-570d-f235-3536-69df8eaa906a
* Version Independent ID: da949f22-1617-c737-d5a4-5c51704443e8
* Content: [Enhance existing Office 365 groups with Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/enhance-office-365-groups#feedback)
* Content Source: [Teams/enhance-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enhance-office-365-groups.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@alanbmhs thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
