### ISSUE TITLE
Analytics too far behind

### ISSUE THREAD

**Issue by NatPascual** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4248]
Hi,

Says here that reports usually reflect a 24 to 48 hour latency from time of activity. However, checking our reports available today (March 23, 2020), analytics show up to March 17, 2020 only. That's four days a bit too long. Any remedy on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b138331-2f10-a05d-7e88-68e62e0b3e4f
* Version Independent ID: f923b648-ffe4-8a8a-c189-6e31f1032c10
* Content: [Microsoft Teams usage report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-usage-report)
* Content Source: [Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@NatPascual thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by edster** [comment]
I am getting the same, will also reach out to support.

**Comment by NatPascual** [comment]
I raised a support request. It was an existing issue said the support. ETA is today. I checked. its 25th today, latest in my analytics is 23rd. I guess its back to normal.
