### ISSUE TITLE
Data privacy in teams

### ISSUE THREAD

**Issue by lpalliyaguru** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#425]
Is the communication encrypted with client key (like whatsapp or any other messenger platform)  in Teams ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca579d63-182b-d6f5-8777-79248fa27ed9
* Version Independent ID: b4c27d1b-b2f1-41ac-b15c-d12b448a539e
* Content: [Overview of security and compliance in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/security-compliance-overview)
* Content Source: [Teams/security-compliance-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/security-compliance-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by chuckedmonson** [comment]
Thank you for your inquiry. We are investigating and will be back with a response. Thank you.

**Comment by chuckedmonson** [comment]
No, it is not encrypted with a client key. Thank you.
