### ISSUE TITLE
Raspberry Pi support

### ISSUE THREAD

**Issue by polmdm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4253]
Hi everyone,
in Italy, due to Coronavirus emergency, my university has decided to adopt your platform to smart teaching and that's fine since it's really powerful and very complete.
But at the same time this kind of solution is really expensive for laptop's hardware (high battery drain and cpu usage).

For this reason I've bought a Raspberry Pi 4 to connect to my TV and stream lesson on it, leaving my pc available for taking notes etc. Furthermore thanks to bluetooth I though to connect my earphones to raspberry and get higher sound quality.

Unfortunately I've soon discovered that there are no way to make Teams working on Raspberry Pi.
Neither is possible to install Teams app neither any browser (chromium & firefox) suppor the video streaming. I've also tried different OS but there's no way to make it working.

Maybe is not in Microsoft plan's to release an app version for this kind of devices but since everybody should have the opportunity to study and Microsoft today controls the learning of many schools/university it should make available for everyone/every platform the opportunity to follow lessons.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#browsers)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@polmdm thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
