### ISSUE TITLE
Exchange Online, on or off?

### ISSUE THREAD

**Issue by flcev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4254]
You should clarify if it requires the customer to migrate local Exchange to Exchange online for it to work flawlessly, and what effect it has when a customer have an on-premise Exchange. 

The text here is not true, as Exchange is assigned automatically when the end user is assigned a Teams Exploratory license. This leads to confusion, af the new mailbox in Office 365 will not automatically work. 

The Teams Exploratory experience comes with an Exchange Online license but it won't be assigned to the user until the admin assigns it. If the user doesn't have an Exchange license already and the admin has yet to assign the Exchange Online license, the user won't be able to schedule meetings in Teams and may be missing other Teams functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f897ae9b-852a-b617-7de0-d76dbd9f1820
* Version Independent ID: 161b1845-53fd-8912-a5f9-737d3bcdaadc
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-exploratory)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@flcev Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @flcev, thank you for your feedback.

About Exchange on-premises, move/migration recommendations are the same:
https://docs.microsoft.com/exchange/exchange-hybrid
If you want a full Teams service for this user, a mailbox is required. You can move the mailbox to EXO or if you don't:
https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact

About:
"The Teams Exploratory experience comes with an Exchange Online license but it won't be assigned to the user until the admin assigns it. If the user doesn't have an Exchange license already and the admin has yet to assign the Exchange Online license, the user won't be able to schedule meetings in Teams and may be missing other Teams functionality."
Tested it and was true in my lab:
![image](https://user-images.githubusercontent.com/33589238/77466366-eb8dcb00-6de8-11ea-8b64-5ed5fb43acb3.png)

![image](https://user-images.githubusercontent.com/33589238/77466388-f5afc980-6de8-11ea-832d-c846dbc43ac3.png)

**Comment by flcev** [comment]
Hi Dario,

I just added a user from admin portal and the Exchange Online is ticked automatically:
I’ll just make a template without the checkmark in Exchange Online.

[cid:image001.png@01D602AD.B5728F70]

Med venlig hilsen - Kind regards - Mit freundlichen Grüssen
Esben Vidstid
Kunderådgiver
[cid:image002.png@01D602AD.B5728F70]

FLC Danmark ApS
Brendstrupgårdsvej 21G
DK8200 Aarhus N
www.flc.dk<http://www.flc.dk>

Tlf
Helpdesk
Mobil
Direkte
Email


+45 70 25 09 55
+45 70 20 92 96
+45 28 19 81 84
+45 36 98 35 74
ev@flc.dk<mailto:ev@flc.dk>





Fra: Dario Woitasen <notifications@github.com>
Sendt: Tuesday, 24 March 2020 20.04
Til: MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com>
Cc: Esben Vidstid <ev@flc.dk>; Mention <mention@noreply.github.com>
Emne: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Exchange Online, on or off? (#4254)


Hi @flcev<https://url12.mailanyone.net/v1/?m=1jGops-0004p4-4R&i=57e1b682&c=d4m524yBy7Bc1t83OreC3Uzow8GnvLhspBYWwV1lQBMShRoBlKhOut2sNSWJ7EnOSl2Yakm4YPl5WnZ7-MwIag1BNlV_JyoTthtRWCGFZWfFuddFBYY0PtwYQ_zrzgzFx0NrLfILI7H3tPHS_X32IXM21eEmgszvgow7GQu7AS4UGJYaZ3FnDKuU_PK1TaZJ8c_ibWhxY99_38Wn5KaFb1yLjpIBqmeqRn4qfzMi6Vg>, thank you for your feedback.

About Exchange on-premises, move/migration recommendations are the same:
https://docs.microsoft.com/exchange/exchange-hybrid<https://url12.mailanyone.net/v1/?m=1jGops-0004p4-4R&i=57e1b682&c=5cX6l-Oj1zFXTBQ_ecWbuJamjt_ji4KCwcjOFMkBScyeEURMsEk_-5riugbJDXj0UvLJxYlxPVkgCIqBtDkN76tcuMUCFCLQI6qo63vbrvfhkFtfBckJD2VQlDTdxHkdA6n9ZFgQ_dKsThiR8IdCAqMzYJO8af2sN_FjTAws_fXqZwvQaMSazw50DpCKryXP9F831aJZzi87V-nas6v3pT9FHpeOgPATl2wTdFgSpWTvmYm708uWNHldmysXzDJH>
If you want a full Teams service for this user, a mailbox is required. You can move the mailbox to EXO or if you don't:
https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact<https://url12.mailanyone.net/v1/?m=1jGops-0004p4-4R&i=57e1b682&c=1WITkrD5jVISmrwbhDZqREHg8TwlzmDTEizgd65CN03OqoviaqPr1Rc0t0t0tCeK3xmRpXUSnAn505Sxdx-enp-6jec_lPeUTbzthLV4P5KB8CU4H-6RAmuIwqqvRxwN_jpRlMA804WoxR3ithS8VA6Ppj2r7dUP6u2QFeUNCD6odHqEJd4U46fg62JMDpWzVRTVmnPFFDEcXdsmz2zfzx93JxsmFuJJT63CYSVZ_eMY5MliORP9A7iK4msQITlbhxePOvG91sWgDkrH8CWwSLUPODUT0oqdjoQFzeuv4nc>

About:
"The Teams Exploratory experience comes with an Exchange Online license but it won't be assigned to the user until the admin assigns it. If the user doesn't have an Exchange license already and the admin has yet to assign the Exchange Online license, the user won't be able to schedule meetings in Teams and may be missing other Teams functionality."
Tested it and was true in my lab:
[image]<https://url12.mailanyone.net/v1/?m=1jGops-0004p4-4R&i=57e1b682&c=d8V_Ou3HBf0e4sn6brl4E-n8dS8c8ZGIzjF1MWyqLDaNr6Ot9NqrydTOutuR8pQO0F_88Fcuy2jL3eCDNHmtod0RFzOzdTTAfjgbl4-zKjBswKgtlReMIhjyd7p5LQVz43FDMbgz61A2Rg4jCuxB9qyyk0R8fbv3koSIaqY8NfIT72kp_bPLSSLX323vZQEGiVaEffU3Shs3kZSc3Nkw5S-F1F9fwPAE-ODA-4aYYMS0ddL4KogQAhmopeN2kMihdGDe87ZcFQ9RBoiS0Q3HUc8gqRT7rvNVajyvyD3NXy4Ljwgx0IZiEtw5N2XZk-lv>

[image]<https://url12.mailanyone.net/v1/?m=1jGops-0004p4-4R&i=57e1b682&c=SuclV99I4iCQofv6PgEnpb6_Aq8U2dHnVyX7NvfR6CooYS1x19RG6HInumsnjewSKFcp3xHKf-JHkU6xcK9eO7cA2g0GaByZFISP65AjxexvgSGjtJDZcTxxMWkzgqfJm3RMfIxaWcYfKxcXp04NpTxD2bJ3oLPwNrXO3ySGL18_AHlDvuTjHPNVs9ZWMU3l09d8oUHlKxvyrVZvfntzuYrXDzTYSecz-jWG9UMw2doiKiJ87RBD_dabY5ErCr-15jZhK7wDLkocfJ29QLy4BZ55fsS3w44nD93WH21VnTxFHMt58sn8ief-nDJ1Vhad>

**Comment by dariomws** [comment]
How I can help you? Docs.microsoft.com feedback is available to improve documentation, I can help if you think there is something to update/fix in the article.

Thanks!

**Comment by Biobobski** [comment]
is this the same as than the 6 months E1 trial with teams just with less licences? I have been trying to get it for 5 days but this one went straight on

**Comment by dariomws** [comment]
Hi @Biobobski, It could be similar but not the same and they have different purposes.

**Comment by scanum** [comment]
@flcev Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
