### ISSUE TITLE
Is there a limit on number of producers on a Teams Live event?

### ISSUE THREAD

**Issue by tbogle** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4255]
Is there a limit on number of producers on a Teams Live event?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events#teams-live-events-and-skype-meeting-broadcast)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@tbogle Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @tbogle, thank you for your feedback.

The limits in this article are all I know. In addition, they can be found there:
https://docs.microsoft.com/microsoftteams/limits-specifications-teams#teams-live-events

**Comment by scanum** [comment]
@tbogle Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
