### ISSUE TITLE
Exchange Foundation

### ISSUE THREAD

**Issue by warleygr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4256]
There's nothing telling abount this "Exchange Foundation" feature.
What is it about?
Could't find anything about it on any Microsoft page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the Microsoft Teams Commercial Cloud Trial offer - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/iw-trial-teams)
* Content Source: [Teams/iw-trial-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/iw-trial-teams.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@warleygr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @warleygr, thank you for your feedback.

@chuckedmonson could you kindly help with this question?

**Comment by SerdarSoysal** [comment]
@Balu-msft can you answer this question?

**Comment by chuckedmonson** [comment]
@warleygr -- Thank you for your patience. Microsoft Teams depends on the Exchange Online infrastructure for some services to work. My understanding is that Foundations is added for that. There is no mail functionality to speak of or real Exchange Online that organizations can use, but it indicates that the Exchange Online back-end services are used for it. Thank you.
