### ISSUE TITLE
Teams not launch after installation

### ISSUE THREAD

**Issue by Dong-SCCM** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4257]
I have done two Teams testing groups and the team is not launching and icon is not shown in Start Menu after reboot.

Testing group 1: run install command mannually.
I have manually ran the command "msiexec /i Teams_windows_x64.msi ALLUSERS=1" as local admin on my laptop. After it is finished running, the team icon did not show up Start Menu. I reboot the computer and then the Teams launch automatically. Also note that this 64bit install file location is located in the 32 bit Program Files folder.

Testing group 2: MSI SCCM deployment
I created and deploy the MSI file via SCCM. Two users installed the app from the Software Center and reboot the computer. Teams app icon is not found in Start Menu and it is not launching.

I am going to try the 32 bit files to see it works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Microsoft Teams using MSI via Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by Dong-SCCM** [comment]
For the 32 bit installation, I deployed to my computer running x1909. The app is installed and did not show up in Start Menu, so i have to sign out and sign back in to have Teams launch automatically. I have another two computers running x1709 with app installed. I tried to have the test users to sign out/sign in and reboot, Teams just won't launch and it's not located in start menu either. I also tried to deploy to a third 1709 machine and the app shows up in start menu right away once the installation is complete. The behavior is very inconsistent.

**Comment by scanum** [comment]
@Dong-SCCM thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
