### ISSUE TITLE
Mention Tags not showing up on desktop app

### ISSUE THREAD

**Issue by GaryCoopATL** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4262]
I see we have mention tags enabled and I have created a few and added my team members.  However, I cannot do any @ mention of them from within the desktop app and my general team channel.  I understand these don't work for private channels at the moment, but the general channel should still work correct?  We are able to make this work over the mobile app, just not the desktop app.

**Comment by scanum** [comment]
@GaryCoopATL thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
