### ISSUE TITLE
Article date and weekly date order is wonky

### ISSUE THREAD

**Issue by ndambrosio** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4263]
The article's date is showing 5/19/2019, but it was updated a few days ago.  The listing of updates by week is also showing some inconsistencies. See order of updates by week below:
Week of March 02, 2020
Week of March 09, 2020
Week of March 16, 2020
-- Then it skips to --
Week of February 17, 2020
Week of February 24, 2020

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3081f70c-d927-ce5d-d957-ca7ba7e07a55
* Version Independent ID: 17704162-7ff9-015c-30a1-1cbc078f0782
* Content: [Microsoft Teams content updates - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-updates)
* Content Source: [Teams/teams-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-updates.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@ndambrosio  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@ndambrosio thanks for reaching out. Unfortunately, these updates are generated automatically each week and I don't have the permissions to update in the correct order. This is however on the teams radar to be fixed in the near future.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@ndambrosio Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
