### ISSUE TITLE
Translation problem English to french

### ISSUE THREAD

**Issue by eudaele** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4267]
In English , you write : « Teams user », you have to translate it by « Utilisateur Teams », that is better than : « l’utilisateur d’équipes »

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: c59eff85-a7f1-764b-4716-b79d70c18d18
* Version Independent ID: 49ecb4f7-3e80-c81a-32b6-4f3fda8826dd
* Content: [Licence Office 365 pour Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/fr-fr/microsoftteams/office-365-licensing?source=docs#feedback)
* Content Source: [Teams/Office-365-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-licensing.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officeglobal Hi! Could you please help with this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by scanum** [comment]
@OfficeGlobal  Any update on this issue? Thanks

**Comment by OfficeGlobal** [comment]
@eudaele , @scanum the affected text was updated by "Utilisateur Teams"

**Comment by scanum** [comment]
@eudaele Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
