### ISSUE TITLE
Maximum number of Microsoft Teams Exploratory licenses

### ISSUE THREAD

**Issue by mipopa** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4268]
I have used one single unlicensed user to sign in to teams.microsoft.com.
Once this first user signed successfully there, the Microsoft Teams Exploratory license appeared in the M365 Admin Center. No other user signed in afterwards to teams.microsoft.com.
I have noticed that after this one-time signin to teams.microsoft.com my tenant received 100 Microsoft Teams Exploratory licenses.

Is this the maximum number of licenses? Or does it "inflate" automatically once additional unlicensed users sign in to teams.microsoft.com ?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f897ae9b-852a-b617-7de0-d76dbd9f1820
* Version Independent ID: 161b1845-53fd-8912-a5f9-737d3bcdaadc
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/teams-exploratory#feedback)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by zhinog** [comment]
Espero respuesta que tengo la misma pregunta. que determina la asignación de las 100 licencias disponibles?

Saludos.

**Comment by scanum** [comment]
@mipopa  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by aleksandr-kk** [comment]
I have same issue. After activating Microsoft Teams Exploratory licenses - i have got only 100 licenses, instead unlimited amount. How can i convert this to unlimited amount?

**Comment by lindspea** [comment]
@mipopa thank you for reaching out and helping to improve MS Docs. I'll check with the team and revert soonest.

**Comment by nadsurf** [comment]
Hi there.
I also have the same issue.
On my tenant, I see 100 Microsoft Teams Exploratory licenses but 500000 Microsoft Teams Commercial Cloud licenses (the latter expires in May 2020).
As per the documentation, the commercial cloud licenses should be converted to exploratory licenses before they expire.
But how many will be converted and is 100 the limit for exploratory licenses?
This is a big issue for me. My company is interested in getting our people to use Teams but there will be a lot more than 100...

**Comment by Biobobski** [comment]
is this the same as the 6 month E1 teams trial https://docs.microsoft.com/en-us/MicrosoftTeams/e1-trial-license with only 100 licences instead of 1000 or is it a cut down version? the 6 month team trial has been a total pain to get setup, nothing after 6 days that works. this was just there in the account

**Comment by lindspea** [comment]
@mipopa thank you for reaching out and helping improve MS Docs. As far as I understand the limit is 100. If you do not currently have a Teams license assigned to you, you are able to access this for six months. See here - https://docs.microsoft.com/MicrosoftTeams/e1-trial-license you can only. See also https://answers.microsoft.com/msoffice/forum/all/microsoft-teams-exploratory-sharepoint-and/560b3de7-83e6-43d3-9f99-95ea4795c8b9

**Comment by scanum** [comment]
@mipopa Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
