### ISSUE TITLE
Team notifications settings not saving

### ISSUE THREAD

**Issue by matthew-mcginty** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4269]
Within a Team channel, enabling notifications and saving the setting does not apply/save

Steps:
Within a team, select "Channel Notifications"
Select any option (other than "Off") for "All new posts"
Click Save
Return to "Channel Notifications"
The previously selected option for "All new posts" is not saved

Impact:
No notifications for Team channels

*All members of the team experience this issue
System: Windows 10 Pro Build 18363.720
Teams Version: 1.3.00.4461 (64-bit)

**Comment by scanum** [comment]
@matthew-mcginty thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
