### ISSUE TITLE
Possible formatting issue

### ISSUE THREAD

**Issue by ndambrosio** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#427]
There may be a formatting issue in the passage below:  
"network administrators of organizations who don't use nm-office-365-short should whitelist or otherwise make available the FQDNs, IPs, and ports mentioned below."

Should  "nm-office-365-short" be substituted with "Office 365"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2b4ce6-d23b-2320-3064-f4537f2736b8
* Version Independent ID: e504bb96-92c3-fde7-3535-1409db82d477
* Content: [Skype Meetings App minimum network requirements](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/minimum-network-requirements)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/minimum-network-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/minimum-network-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
You are correct! That represents a translation glitch: I'll save you the details but recently we've move from one publishing platform to another, and there are a dwindling number of errors like that we're cleaning up as we find them. Thanks for pointing it out. We should have it fixed very shortly.

**Comment by jambirk** [comment]
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/pull/1115 resolves this issue.
