### ISSUE TITLE
Mobile IOS app doesn't allow to chat with a "Tag" group

### ISSUE THREAD

**Issue by nphadro** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4272]
In the desktop you can Chat with a group (TAG) my going to manage tags. Then clicking "Chat with group". You can't seem to do this on the app. When will this be available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b16e659e-cf07-268a-e224-fa444749ac29
* Version Independent ID: ee822a8d-b331-998f-e336-b1fa510f35c0
* Content: [Manage tags in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-tags#feedback)
* Content Source: [Teams/manage-tags.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-tags.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@nphadro thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by anniecolonna** [comment]
Hi @nphadro, we don't support this yet, but we will in the future with an update to the tag experience on mobile. It's in early builds so you should expect it in the next few months.
