### ISSUE TITLE
Incorrect/imcomplete information entered

### ISSUE THREAD

**Issue by rutrac** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4274]
The information contained in the first Important note on this article is not accurate. The scenario described is only valid for a Teams-only mode and not for the Island mode where the SfB user can be homed Onprem and Federation will still work.
Please correct the article so we can avoid customer confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external access (federation) in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access#feedback)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@rutrac  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Petri-X** [comment]
Also, how does this affects to the document?
[Microsoft Teams - Native Federation for 1:1 Chats](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=Launched&searchterms=federation)

**Comment by lindspea** [comment]
It seems the article has recently been updated. "As of February 25, 2019, Teams doesn't support native federation without the user of the SIP profile being homed in Skype for Business Online. For more on setting up your account for hybrid and then moving to Teams, see Upgrade Skype for Business hybrid deployment to Teams."Please have a look and let me know.  See also - https://docs.microsoft.com/MicrosoftTeams/coexistence-chat-calls-presence

**Comment by scanum** [comment]
@rutrac Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
