### ISSUE TITLE
Inaccurate documentation about unsupported browser support.

### ISSUE THREAD

**Issue by bruceburge** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4280]
The below information does not seem accurate, teams (as shown in the attached graphic) doesn't allow users to join at all, in unsupported browsers (in this case Firefox 74.0 (64-bit)), and requires them to join in Edge or download the app.

Either this should be corrected, or the documentation updated.

> Some browsers, such as Internet Explorer 11, Safari, and Firefox, support the Microsoft Teams web app but don't support some of the Teams calling and meeting features. To work around this limitation, the Teams web app lets users receive audio through a PSTN connection and lets them view presented content (screen share) at a reduced display rate.

>When Teams detects an unsupported browser, it automatically displays a message explaining the issue and the session limitations. The message provides further instructions for accessing the meeting audio, such as advising the user to leave a call back number so that Teams can call the user, or instructing the user to call the conference number included in the meeting invitation. The message also encourages the user to download and use the Teams desktop client for the full Teams experience.

>If PSTN is unavailable, the user won't see the instructions for accessing the meeting and won't be able to join the meeting.

![image](https://user-images.githubusercontent.com/6773890/77479118-31e52900-6ded-11ea-8b52-2916df33ea3e.png)

**Comment by scanum** [comment]
@bruceburge  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@bruceburge thank you for reaching out and helping improve MS Docs. Please can you send me the link to the document you are referring to so I can investigate further.

**Comment by scanum** [comment]
@bruceburge We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by bruceburge** [comment]
> 
> 
> @bruceburge We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
> 
> Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

https://docs.microsoft.com/en-us/microsoftteams/unsupported-browsers

Not sure why the comment on github, from that page, wouldn't allow you to find that page, but the link above should work.
