### ISSUE TITLE
Teams Meeting icon is missed in outlook for Mac if mailbox is in Onprem

### ISSUE THREAD

**Issue by XixiHuang333** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4282]
Hi Team,
Teams Meeting icon is missed in outlook for Mac if mailbox is located in onprem Exchagne Server.
Please kindly help to verify this and help to release approraiate statement in offical document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact#feedback)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@XixiHuang333  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by nhsy** [comment]
+1 also having this issue across our entire organization on macbooks.

**Comment by lindspea** [comment]
@XixiHuang333 thank you for reaching out and helping improve MS Docs. Please have a look at this link and see if it helps - https://answers.microsoft.com/msoffice/forum/all/microsoft-teams-meeting-icon-not-appearing/5693f05c-3d3f-4eef-88c7-34b43bec3b48?auth=1

**Comment by drzui** [comment]
+1 same here

**Comment by lindspea** [comment]
@XixiHuang333 please see this information from the article - "Users' Exchange mailboxes can be hosted online or on-premises. However, some features require a hybrid deployment to be in place with your Office 365 tenant."

**Comment by scanum** [comment]
@XixiHuang333 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
