### ISSUE TITLE
Get-csautoattendant wrong URL

### ISSUE THREAD

**Issue by VladimirGluten47** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4283]
The Get-CsAutoAttendant hyperlink incorrectly points to the New-CsAutoAttendant page. Should instead point to: https://docs.microsoft.com/en-gb/powershell/module/skype/get-csautoattendant?view=skype-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a42f9e2c-aeee-76c4-620a-668cce21ba10
* Version Independent ID: 6ff06eab-9c80-9c30-95ef-c17e157fbea1
* Content: [Set up a Cloud auto attendant - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-auto-attendant)
* Content Source: [Teams/create-a-phone-system-auto-attendant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-auto-attendant.md)
* Service: **msteams**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@VladimirGluten47  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@VladimirGluten47 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
