### ISSUE TITLE
Endpoint Manager vs Endpoint Configuration Manager

### ISSUE THREAD

**Issue by D-Jeffrey** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4284]
I was expecting to see deployment using Endpoint Manager (via InTune), but this seems to be deployment via SCCM.  Will there be additions to the Administrative Template or Full O365 app policy settings added to Endpoint Manager?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Microsoft Teams using MSI via Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@D-Jeffrey thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by D-Jeffrey** [comment]
I will do that, and it was good to have the documentation and functionality for the Windows 10 Cloud Microsoft is telling enterprise customers to move too.
