### ISSUE TITLE
What is happening if VPN have interrupts?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4286]
Hi,

Could you please add a note to the scenario:
"**VPN user to internal user (media relayed by Teams Transport Relay)**"

What is happening if the VPN stop working (signaling stop working). How long time it is expected, that media is still able to work using path 3 ? We already know it continues working (chat does not etc..). But as there is no documentation about that, I thought it might be good idea to share it.

Here is link to the picture: [Dataflow for VPN user to internal user (media relayed by Teams Transport Relay)](https://docs.microsoft.com/en-us/microsoftteams/media/microsoft-teams-online-call-flows-figure05.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c84773-337e-9df7-7fbd-fc9d94280711
* Version Independent ID: 223a78a0-67fd-8b96-be3f-153bb400101b
* Content: [Microsoft Teams call flows - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/microsoft-teams-online-call-flows#feedback)
* Content Source: [Teams/microsoft-teams-online-call-flows.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/microsoft-teams-online-call-flows.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Petri-X thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Petri-X** [comment]
Hi @scanum 
Unfortunately I cannot agree you :) As I do not have an actual problem with this at the moment. I was hoping you have close co-operate with people who knows, and this kind information could be pullet out from them easily :D 
But I'll try to find the answer.
