### ISSUE TITLE
Step 1 part 2, no such option in the legacy portal

### ISSUE THREAD

**Issue by benmiller86** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4288]
&gt; Go to `Microsoft 365 admin center &gt; Admin centers &gt; Teams & Skype &gt; Legacy portal &gt; Voice &gt; Phone numbers.`

There is no `Voice` option in the legacy portal. I am now completely stuck having purchases the audio conferencing license which I can't use!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 485c3bcb-41f9-6873-bd04-2f4110d07655
* Version Independent ID: df1cd65a-1636-73b7-3245-674dfb6b86cf
* Content: [Change the phone numbers on your Audio Conferencing bridge - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/change-the-phone-numbers-on-your-audio-conferencing-bridge)
* Content Source: [Teams/change-the-phone-numbers-on-your-audio-conferencing-bridge.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/change-the-phone-numbers-on-your-audio-conferencing-bridge.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@benmiller86 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
