### ISSUE TITLE
Any Linux client details?

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4293]
Are there any details on how the Linux client does QoS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76c2487c-044d-1349-708a-5841fcb21ab8
* Version Independent ID: b7033454-1a9c-48d4-8004-78415c5feb89
* Content: [Implement Quality of Service in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/qos-in-teams)
* Content Source: [Teams/QoS-in-Teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/QoS-in-Teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@TorrenManson  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TorrenManson** [comment]
Hi,

Apologies for the confusion. My feedback wasn’t “what about Linux support for Teams”, but rather “what about Linux support for QoS”.

Cheers,
Torren

**Comment by lindspea** [comment]
@LanaChin

**Comment by kenwith** [comment]
@TorrenManson thank you for taking the time to open an issue. The docs get better when experts like you share your knowledge and feedback. I appreciate it. I have added Linux to the list of scenarios where Mac and mobile are called out as those environments don't use group policy. Here is a link to the PR: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/4519 Thanks again and let me know if you find any other areas the docs can be improved. Also, the docs are open source now and if you are interested to make an edit yourself you can do so following guidance similar to the video here: https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md note that this is a different GitHub repository but the concept is the same for all content on docs.microsoft.com. Thanks again!
