### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by MIBadran** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4296]
on Steps when you are unassigning a service phone number for a conferencing bridge Step 3 point 4 (Fre)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 485c3bcb-41f9-6873-bd04-2f4110d07655
* Version Independent ID: df1cd65a-1636-73b7-3245-674dfb6b86cf
* Content: [Change the phone numbers on your Audio Conferencing bridge - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/change-the-phone-numbers-on-your-audio-conferencing-bridge?source=docs#steps-when-you-are-unassigning-a-service-phone-number-for-a-conferencing-bridge)
* Content Source: [Teams/change-the-phone-numbers-on-your-audio-conferencing-bridge.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/change-the-phone-numbers-on-your-audio-conferencing-bridge.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@MIBadran  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@MIBadran Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
