### ISSUE TITLE
Hundreds, even thousands of users...

### ISSUE THREAD

**Issue by markburland** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4297]
So, how do we bulk apply policy packages to let's say for example "all staff" and "all students?" Please don't say 20 at a time! Can we not have dynamic policy membership? Like, "apply this policy package to all users who are members of this security group?"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcfef917-dc74-3fd7-eef8-5af66583a04d
* Version Independent ID: 9d1958bc-e321-06b8-91d6-a0ec291190eb
* Content: [Microsoft Teams policy packages for EDU admins - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/policy-packages-edu#feedback)
* Content Source: [Teams/policy-packages-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/policy-packages-edu.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by pmoussier** [comment]
I agree with this. I need to apply a ploicy tu many users (1000+), and 20 at time...

how could we do ?

**Comment by scanum** [comment]
@markburland  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by m8ttysmith** [comment]
I would like to be able to create multiple custom policy packages to be honest... We have 35 schools on one tenant and one Student policy package is no good for all the students... I dont want to have to create seperate messaging / video / meeing policies and assign them I want to create a custom Policy Package per school ideally.. is this going to be possible ?

**Comment by Cdenby** [comment]
https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-overview
This shows how to use powershell to assign to users, but I still need to research about leveraging something in the users (especially new incoming users) to differentiate assigned policy packages.

**Comment by lindspea** [comment]
@markburland thank you for reaching out and helping improve MS Docs. Has @Cdenby helped answer your question?

**Comment by Cdenby** [comment]
I need to have policy packages that are not aligned with the naming. 
DefaultUnassigned
ElementaryStudent
SecondaryStudent
Teachers
Staff

But even after I assign a policy package to a user, I'm still unable to edit the name of the policy. So then I'll end up with my School Staff group getting a policy called "Public safety officer" -- that makes no sense.  Also - the policies themselves have locked names. 

Is it possible to change the name of a policy package and the policies associated with the package? Even through powershell?

**Comment by Cdenby** [comment]
Actually - I need School Admin as a separate policy package as well.

If I were to create several policies, instead of using the policy packages, I'm able to name them my own way and have any number of them in each category. But then, of course, I need to script the assignment of a lot more users-to-policies than I would need to do if I were doing users-to-packages.

I'm hearing that the assignment of policies and packages to GROUPS is coming - perhaps in May? - that makes all of this effort distressing. As well, the management of packages and policies themselves inside the Admin Center seems not-quite-ready-for-primetime, IMO. Unless I'm missing some area that opens up more editing capabilities.

**Comment by lindspea** [comment]
@dstrome could you please assist?

**Comment by jvolp** [comment]
Definite need this.  It's bizarre how often MS is releasing new stuff without proper management tools behind it these days.  Need to be able to assign policies to Groups so all that we need to manage is Group Membership.  Having to run powershell scripts vs thousands and accounts and do it constant to account for onboarding is incredibly annoying.

**Comment by dstrome** [comment]
You can use PowerShell to grant a policy package to multiple users. See https://docs.microsoft.com/en-us/powershell/module/teams/grant-csuserpolicypackage?view=teams-ps

Policy packages can't be renamed, and new packages can't be created. You can change the configuration of policies added to a policy package by first assigning to a user and then going to Policy packages > (package name) > (policy name)
