### ISSUE TITLE
Tenant level control on/off switch shows it will be removed by May 2018, but it's still there. 

### ISSUE THREAD

**Issue by soyalejolopez** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#430]
Is there an updated date for when the tenant level control on/off switch will be removed? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cccdd91a-7f05-abd5-ed94-e82152b86914
* Version Independent ID: 3532d0a8-119c-f7d0-0d4f-a865ad32570f
* Content: [Manage user access to Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/user-access)
* Content Source: [Teams/user-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/user-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by kenwith** [comment]
@islubin - this doc states the below as @soyalejolopez  noted. Should I update this document?

**Note**
Tenant-level control of the on/off status for Teams is temporary and **will be removed by May 2018.** At that time, access to Teams will be controlled via user-level licensing only. To learn more, see Manage user access to Microsoft Teams.

**Comment by kenwith** [comment]
@soyalejolopez - confirmed the date is moved to through July. I updated article to say it will be removed beginning of August. It should be live shortly. Thanks for catch and the feedback on this!
