### ISSUE TITLE
チャネルの投稿の宛先にタグが表示されません

### ISSUE THREAD

**Issue by marco-05** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4301]
Teamsのデスクトップアプリを使っています。
チームに所属するメンバーを加えてタグを作成しましたが、チーム内のチャネルの投稿画面でポストする際に宛先に作成済のタグが表示されません。
新しいチャットグループを作成する際にはタグは機能するので、タグとしては認識されているようですが。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b16e659e-cf07-268a-e224-fa444749ac29
* Version Independent ID: ee822a8d-b331-998f-e336-b1fa510f35c0
* Content: [Microsoft Teams でタグを管理する - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/manage-tags#feedback)
* Content Source: [Teams/manage-tags.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-tags.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by marco-05** [comment]
モバイルアプリ (Android)からはチーム内のチャネルの投稿画面でも問題なくタグをメンションできることは確認しました。
なので、デスクトップアプリのみ動作していない状態です。

**Comment by scanum** [comment]
@officeglobal Hi! Could you please help with this issue? Thanks!

**Comment by marco-05** [comment]
It's resolved! I defined the tag name "@xxx" without intention, in that case you have to type "@@xxx" to see autocomplete. 
Sorry for taking your time.

**Comment by scanum** [comment]
@marco-05
