### ISSUE TITLE
Additional requirement, enable "Microsoft VBA for Outlook Addin"

### ISSUE THREAD

**Issue by Edocsyl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4302]
The "Microsoft VBA for Outlook Addin" must be activated so that the team invitations are displayed correctly in the Outlook appointment.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Use the Microsoft Teams Meeting add-in in Outlook - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@Edocsyl Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
Hi @Edocsyl  Thanks for raising this issue! I will be looking into it!

**Comment by scanum** [comment]
@TokyoScarab Any updates here? Thanks!

**Comment by LanaChin** [comment]
Hi @Edocsyl - Is this still an issue for you? Can you send us more information about the display or formatting issues you were experiencing? Thanks.

**Comment by LanaChin** [comment]
Closing for now.  @Edocsyl, if this is still an issue for you, please resubmit with details of the display or formatting issues. Thank you!

**Comment by tdalon** [comment]
The meeting invitation is displayed as plain text. No HTML formatting of links.
