### ISSUE TITLE
Manage Users missing

### ISSUE THREAD

**Issue by bozford** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4306]
IN the following text, the "manage users" instruction is no longer valid.  The option is not present.

An icon showing the Microsoft Teams logo Using the Microsoft Teams admin center

Go to Meetings &gt; Live events policies.
Select the policy by clicking to the left of the policy name.
Select Manage users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9aa4676-855a-fddb-bb0b-96b7095c695e
* Version Independent ID: 7c39f08c-0d56-6d29-1356-879d9d6ff51c
* Content: [Set up for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/teams-live-events/set-up-for-teams-live-events#feedback)
* Content Source: [Teams/teams-live-events/set-up-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/set-up-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@bozford Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by klishb** [comment]
FYI the option to Manage Users is still available to me when I go to Meetings > Live Events Policies.  The option is grayed out until you select a Policy to manage.

**Comment by Reeced40** [comment]
@bozford Thank you for reaching out. Please confirm if @klishb has answered your question.

**Comment by scanum** [comment]
@klishb @bozford We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
