### ISSUE TITLE
Conference toll numbers

### ISSUE THREAD

**Issue by xponentia** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4308]
What about calling credits/rates for conference dial in toll numbers, can't find anything about that but getting emails that the credits are almost up. How many credits come with each user license in the pool? How should these be assigned?  This is terrible documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d8f6008-136f-52a1-70c8-f721f1be0491
* Version Independent ID: efaeb679-a1c9-ab98-9f0b-f253a19cecec
* Content: [Add funds and manage Communications Credits - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/add-funds-and-manage-communications-credits)
* Content Source: [Teams/add-funds-and-manage-communications-credits.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/add-funds-and-manage-communications-credits.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@xponentia Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @xponentia, thank you for your feedback.

There is a note that sends you to the rates page:
"If you're wondering how much it is and the rates, see the rates table on the [Calling Plans](https://go.microsoft.com/fwlink/p/?LinkId=799523) page."
There you can download an Excel file with the rates for dial-in and out.

About how many minutes are included and how to assign them, you should check Calling Plans sections:
https://docs.microsoft.com/microsoftteams/calling-plan-landing-page

**Comment by xponentia** [comment]
I ended up finding the 14 different documents and pages I needed to gather all this information, among all kind of bad and incorrect information since it's been changed 4 times in 2 years. 

I did end up finding that excel file but still couldn't find the answer to one part...

What's the difference in rates between having a local area code like 415-xxx-xxxx meeting dial in number vs having a toll free 888-xxx-xxxx number? I can't find that anywhere, maybe it's the same rate? Maybe it depends on whether it's dial out or in on toll free vs toll?

Also good luck figuring out how many minutes are included of dial out for each user with an audio conferencing license on that calling plans section page.  It's actually this link:  https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-subscription-dial-out

Setting up communications credits with auto-top up isn't too bad but it's also not easy to find.

This should be much easier to figure out for people who just want to add audio conferencing for dial in for teams and not be confused by the rabbit hole of 18 links you have to open and ignore all the phone system related stuff except when you can't ignore it.


> Hi @xponentia, thank you for your feedback.
> 
> There is a note that sends you to the rates page:
> "If you're wondering how much it is and the rates, see the rates table on the [Calling Plans](https://go.microsoft.com/fwlink/p/?LinkId=799523) page."
> There you can download an Excel file with the rates for dial-in and out.
> 
> About how many minutes are included and how to assign them, you should check Calling Plans sections:
> https://docs.microsoft.com/microsoftteams/calling-plan-landing-page

**Comment by scanum** [comment]
@xponentia Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
