### ISSUE TITLE
VbSS and the MediaLineLabel

### ISSUE THREAD

**Issue by philsilva** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#431]
Provided that Jens Trier Rasmussen's blog post still holds true in regards to QoE data from Skype for Business server, a MediaLineLabel of '16' indicates that the stream utilizes Video based Screen Sharing (VbSS).  

Jens' blog post can be found at the link below...
https://blogs.technet.microsoft.com/jenstr/2016/01/06/looking-at-vbss-video-streams-in-qoe/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56c850c1-0967-055e-9ac5-b6910a80c4e7
* Version Independent ID: bae33f47-e277-becf-c2f0-3527668e9cdc
* Content: [AppSharingStream table](https://docs.microsoft.com/en-us/skypeforbusiness/schema-reference/quality-of-experience-qoe-database-schema/appsharingstream#feedback)
* Content Source: [Skype/SfbServer/schema-reference/quality-of-experience-qoe-database-schema/appsharingstream.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/schema-reference/quality-of-experience-qoe-database-schema/appsharingstream.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by kenwith** [comment]
I was in touch with the product team and added a cross link to MediaLine table. That way source is in one place. I also contact with Jens and he recommended to refer the docs.microsoft.com docs as he hasn't updated the blog post in some time. Thanks for reporting. Here is PR: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/441/files
