### ISSUE TITLE
Feedback regarding bulk adds and deletes

### ISSUE THREAD

**Issue by Camelonian** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4310]
It would be helpful if we could apply these settings to groups also.  Adding each user is far too tedious.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888fe05b-1160-452f-90ba-deb19adb740f
* Version Independent ID: 4091c5e4-7a90-7fe4-2741-16bbb1f297c1
* Content: [Edit Microsoft Teams users settings in bulk - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/edit-user-settings-in-bulk#feedback)
* Content Source: [Teams/edit-user-settings-in-bulk.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/edit-user-settings-in-bulk.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Camelonian Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by viperfx** [comment]
The current limit is 20k. This article says 20. So there must be mistake?

**Comment by jvolp** [comment]
@scanum 10K+ accounts.  20 at a time not logistically possible.  Need another solution yesterday.  Why can't these be applied dynamically to Groups?

**Comment by Reeced40** [comment]
@Camelonian Thank you for reaching out. It looks like it has been updated in the interim. Please can you confirm.

**Comment by scanum** [comment]
@viperfx We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
