### ISSUE TITLE
Teams features without hybrid

### ISSUE THREAD

**Issue by felgar73** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4311]
It's a bit unclear to me what Teams features are still available if Exchange hybrid is not present. According to the matrix above, Teams seems to be able to connect to on-prem Outlook calendars as long as they're Exch is 2016 CU3+, but I'm not sure I'm interpreting that correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact#feedback)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@felgar73 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tobvil** [comment]
I have exactly the same question as felgar73.

**Comment by teodordeaconescu** [comment]
Without exchange hybrid in place, so with user mailboxes in on premise, the Teams (Azure AD) user will see the Calendar tab on the left rail in Teams, but won't be able to use it. They will have no way of managing meetings - they will be able to join a meeting organized by someone else only if they are explicitly sent the join link. If you enable the users for EXO, still no Ex. hybrid, then they will have 2 mailboxes - one for Teams meetings and the other for their regular email in on premise. There will be no sync between the 2 mailboxes. Once we go hybrid, we'll need to consolidate the mailboxes, so I don't recommend this. If you have Ex. on premise, run the Hybrid Configuration Wizard and all will be fine - no need to actually move mailboxes to EXO (yet).

If you have no Exchange whatsoever, i.e. you use Lotus Domino Server, then I suggest enabling EXO anyway, have 2 mailboxes, but be in M365 very quickly with the ability to manage meetings in Teams. Maybe forward content from your Lotus mailbox to EXO, to keep the two in sync (manual process tho, no out of the box sync).

**Comment by felgar73** [comment]
Thanks for the response! I'll submit an edit for this info as it's not clear from the text. It makes it seem like only AD sync is needed for all the features to work, but it's clear to me that OAuth (configured via hybrid) are also needed.

**Comment by felgar73** [comment]
Follow up question: can users create Teams meetings via Outlook without hybrid configured or is that also not possible?

**Comment by teodordeaconescu** [comment]
Not possible. The addin needs the services behind to run, so in our case, exchange hybrid.

You get the addin because you install the Teams desktop client. That doesn't necessarily mean that all dependant backend services have also been purchased, licensed and configured correctly. :)

Hope this makes sense, let me know :)

Thanks,
Teodor

Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by felgar73** [comment]
Works for me – thanks again for the info, Teodor!

-Felix G.

**Comment by Karspi** [comment]
Please let me add my 2 cents here as I had a customer request regarding Microsoft Teams calendar with Exchange on-premises. I was able to access the user's calendar, create edit delete or join a meeting through Microsoft Teams with the mailbox on Exchange on-premises and no Exchange Full or Minimal hybrid configuration. 
Many articles or colleagues pointing to implement Exchange hybrid to get the calendar in Microsoft Teams to work with Exchange on-premises mailboxes.

This is not true, neither a requirement from Microsoft, it is just a "good" recommendation. 

What here truly is needed are the following steps:

1. Azure AD Connect with Exchange Hybrid attributes sync
1.1 From that point, the Exchange Online is aware of the on-premises mailbox
2. Exchange on-premises 2016 CU3+
3. Exchange on-premises must be accessible from MS Teams IP
3.1 Autodiscover will be used from MS Teams backend services to discover and access the Exchange on-premises
3.2 Firewall rule to allow traffic may be required - MS Teams backend services IPs - http://aka.ms/ipurlws
3.2 Create Autodiscover DNS entry in your public DNS and point to your Exchange Server if it is not set
3.3 Exchange on-premises should answer to requests over 443 with a public certificate which covers autodiscover and the external hostname of the server
4. OAUTH has to be configured
4.1 https://docs.microsoft.com/en-us/exchange/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help
4.2 Step 1-5 should be enough, test if OAUTH is working with the steps at the bottom of the article. 

Please message me if you face any issue and I would be happy to assist you

Spikar

**Comment by felgar73** [comment]
Thanks for the input Spikar!
My lab is showing strange results because I don’t have OAuth configured, but I do have hybrid and it works with Teams fine. That is just adding to my confusion.

-Felix G.

**Comment by teodordeaconescu** [comment]
I might me wrong, but isn't this hybrid without running the HCW?
Anyway, imho it's easier to just run HCW :)

**Comment by Karspi** [comment]
@felgar73 this is normal because when you configure Exchange Hybrid OAUTH is going to be automatically configured in the background. The main question here is if the implementation of Exchange minimal or full Hybrid is required to get that work, and with that I mean, being able to see your calendar over MS Teams client when your mailbox resides on-premises. 

@teodordeaconescu yes and no, with those steps we configure few things that are going to be configured from the Exchange Hybrid wizard. The difference here is that we configure the minimum required settings to get calendar from on-premises mailboxes to show up in MS Teams. 

Out there we have companies or customers that are working with the following motto, everyone, for his reasons: 

"As much as necessary, as little as possible!"

In that situation, we should not configure Exchange full hybrid as it is not necessary, and therefore this guide here exists.

An "issue" that you are going to face without full hybrid is when you will try to create a calendar event with adding a MS Teams channel then the invitation is going to be sent from the cloud to your on-premises mailbox, without the proper mailflow configured in place, your on-premises mailbox may never receive that e-mail, therefore the event is not going to be created and after few minutes the event will even disappear from the MS Teams client.

**Comment by felgar73** [comment]
I have mixed Exch with 2010, so OAuth was not configured. I confirmed this by checking intraorg connector settings (blank) and checking for Auth server (‘get-authserver’ also blank).

I don’t get the calendar tab in Teams client as expected, but I can create meetings via Outlook Proplus.

-Felix G.

**Comment by larsdemo123** [comment]
![image](https://user-images.githubusercontent.com/62933188/79050730-42d6cc80-7c2c-11ea-8888-e3169ad77dbf.png)

**Comment by dstrome** [comment]
An Exchange hybrid deployment is required when integrating Teams with an on-premises Exchange deployment. This is in addition to version-specific requirements for some features. The article has been updated to reflect this requirement.

**Comment by causeway74** [comment]
Footnote 1 (Exchange 2016 CU3 and above supported.) in the table in this article isn't referenced anywhere. Does the table need an update? It's unclear what happens if we have hybrid, but something other than 2016. What about 2013 mode for example?

**Comment by cloudsafeer** [comment]
> Please let me add my 2 cents here as I had a customer request regarding Microsoft Teams calendar with Exchange on-premises. I was able to access the user's calendar, create edit delete or join a meeting through Microsoft Teams with the mailbox on Exchange on-premises and no Exchange Full or Minimal hybrid configuration.
> Many articles or colleagues pointing to implement Exchange hybrid to get the calendar in Microsoft Teams to work with Exchange on-premises mailboxes.
> 
> This is not true, neither a requirement from Microsoft, it is just a "good" recommendation.
> 
> What here truly is needed are the following steps:
> 
> 1. Azure AD Connect with Exchange Hybrid attributes sync
>    1.1 From that point, the Exchange Online is aware of the on-premises mailbox
> 2. Exchange on-premises 2016 CU3+
> 3. Exchange on-premises must be accessible from MS Teams IP
>    3.1 Autodiscover will be used from MS Teams backend services to discover and access the Exchange on-premises
>    3.2 Firewall rule to allow traffic may be required - MS Teams backend services IPs - http://aka.ms/ipurlws
>    3.2 Create Autodiscover DNS entry in your public DNS and point to your Exchange Server if it is not set
>    3.3 Exchange on-premises should answer to requests over 443 with a public certificate which covers autodiscover and the external hostname of the server
> 4. OAUTH has to be configured
>    4.1 https://docs.microsoft.com/en-us/exchange/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help
>    4.2 Step 1-5 should be enough, test if OAUTH is working with the steps at the bottom of the article.
> 
> Please message me if you face any issue and I would be happy to assist you
> 
> Spikar

Thanks for the detailed insight,  We have a Hybrid- Exchange 2013 SP1 CU21 and  we are able to create Team meetings from Outlook & Teams client without any issues.  We can see the meetings in each clients as well and the mailboxes are all onpremise.  

As Microsoft says only 2016 CU3 is supported, is this undocumented feature, have you seen this scenario before. 

it would be good to see your view if i am missing any major risk here.  This is also a large environment, hence need some guidance.
