### ISSUE TITLE
Resouce account not only need to E5 lic.

### ISSUE THREAD

**Issue by tangx007** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4316]
"If you're assigning a phone number to to your auto attendant, you will need an Office 365 Enterprise E5 license."

for this part, I think the resouce account just not only need to E5 lic, but also other phone system lic is ok, would you pls clarify on this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d3bc9d7-fd9e-be9f-1c46-1cc16a5c0789
* Version Independent ID: a6a46add-33de-d3b9-0169-64b642562191
* Content: [Plan a Cloud auto attendant - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-cloud-auto-attendant#requirements)
* Content Source: [Skype/SfbHybrid/hybrid/plan-cloud-auto-attendant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/plan-cloud-auto-attendant.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@tangx007 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by BSiefferman** [comment]
@tangx007 E5 comes with Phone System license, it just doesn't include the Calling Plan license which would be an add-on. If you had E3 licensing you would need the Phone System add-on though.

**Comment by tangx007** [comment]
@BSiefferman I agree with you that E5 include Phone System Lic.

But this item (" you will need an Office 365 Enterprise E5 license") is under cloud auto attendant Requirements part, and it may make a misunderstand to the reader that Cloud-AA MUST need a E5 lic, but actually just only a Phone system Add on lic is also ok.

So, I suppose to modify the discribsion : "If you're assigning a phone number to to your auto attendant, you will need an Office 365 Enterprise E5 license." to "If you're assigning a phone number to to your auto attendant, you will need a free Phone System - Virtual User license or a paid Phone System license."

**Comment by BSiefferman** [comment]
@tangx007 ah understood, sorry I misunderstood your ask. I would agree then with the change in language on the document :)

**Comment by tangx007** [comment]
Thanks your understand.

**Comment by tangx007** [comment]
any update?

**Comment by scanum** [comment]
Hi @tangx007 we thank you for submitting feedback! 
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
