### ISSUE TITLE
Clarify about the online resource account creation

### ISSUE THREAD

**Issue by tangx007** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4317]
At  step 3 of "Create a resource account with a phone number", it just only mention the onpremise resource account creation, but not mention how to create a online RA. That seems sfb not support online RA, would you please clarify or update it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0703860-c3db-c723-317f-7fab164c006d
* Version Independent ID: c6384e2b-ac37-265d-8c33-f004eca97673
* Content: [Configure a resource account in Skype for Business Server 2019 - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/configure-onprem-ra#feedback)
* Content Source: [Skype/SfbHybrid/hybrid/configure-onprem-ra.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-onprem-ra.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@tangx007 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tangx007** [comment]
any update?

**Comment by scanum** [comment]
Hi @tangx007 we thank you for submitting feedback!
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
