### ISSUE TITLE
I am confuse below two sentence Under Requirements

### ISSUE THREAD

**Issue by tangx007** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4319]
I am confuse below two sentence Under Requirements:
1)"You will need to create resource accounts either online or in Skype for Business Server 2019"
2) "Create an on-premises resource account for each call queue, and assign a license and phone number if required."

So, what resource account I can use when using SFB2019 onpremise? Online or onprem resouce account? Or both ?

Would you pls update or clarify it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93dbb0a3-3d1e-d38e-55cd-dd6a25e58f72
* Version Independent ID: 83c500fa-54cd-1c2e-9882-bd1566322fa1
* Content: [Plan a Cloud call queue - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-call-queue)
* Content Source: [Skype/SfbHybrid/hybrid/plan-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/plan-call-queue.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by tangx007** [comment]
I just test on my SFB2019 hybrid enviroment, it seems not working when I call to a online resouce account which is associated a AA, but onpremise resouce account is work.

So  "You will need to create resource accounts either online or in Skype for Business Server 2019" need to be updated ?

**Comment by scanum** [comment]
@tangx007 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tangx007** [comment]
any update ?

**Comment by scanum** [comment]
Hi @tangx007 we thank you for submitting feedback!
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
