### ISSUE TITLE
E' possibile rendere aperto un canale privato?

### ISSUE THREAD

**Issue by carloreggiani** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4320]
Ho creato un canale privato, vorrei ora renderlo aperto al team: è possibile?

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Canali privati in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/it-it/microsoftteams/private-channels)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@carloreggiani Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by pabloemmanueldeleo** [comment]
When you think that option is done? Is very important.

**Comment by scanum** [comment]
@officeglobal Could you aid with this issue? Thanks!

**Comment by OfficeGlobal** [comment]
@scanum original question via Bing translator "I have created a private channel, I would now like to make it open to the team: is it possible?"

The current version of the article is HumantTranslated, in case there will be an updated based on the  question, we will pick it up for loc.

**Comment by scanum** [comment]
@carloreggiani thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
