### ISSUE TITLE
Number of Private channels per team

### ISSUE THREAD

**Issue by Michel-NL** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4321]
The limit for private channels 30, includes deleted channels?
Maybe add #3 to the end of the line?

³ Deleted channels can be restored within 30 days. During these 30 days, a deleted channel continues to be counted towards the 200 channel per team limit. After 30 days, a deleted channel and its content are permanently deleted and the channel no longer counts towards the 200 channels per team limit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#feedback)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Michel-NL Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LolaJacobsen** [comment]
Checking with PM Arun Das.

**Comment by mrahhali** [comment]
How many channel meetings can run at the same time?

**Comment by KashyapPatel-nbcuni** [comment]
Is there an open request to increase the max of private channels that is currently set at 30 per team?

**Comment by powertumbling** [comment]
Maybe the number of channels and private channels could come from the same limit. I need more than 30 private channels, because we use the student groups when the hand in group assignments. This could be solved if the assignment modul would allow teams/group assignments and not only single person assignments. Much of our work in school is based on collaboration in teams... Maybe a feature request

**Comment by scanum** [comment]
@LolaJacobsen Hi Lola, any updates here? Thanks!

**Comment by scanum** [comment]
@LolaJacobsen Hi Lola, any updates here? Thanks!

**Comment by LolaJacobsen** [comment]
@powertumbling @Michel-NL @KashyapPatel-nbcuni Here's the documentation for private channelsl:
https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels#what-you-need-to-know-about-private-channels

Each team can have a maximum of 30 private channels and each private channel can have a maximum of 250 members. The 30 private channel limit is in addition to the 200 standard channel limit per team.
