### ISSUE TITLE
New IP range added

### ISSUE THREAD

**Issue by joturans** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4322]
This new range was added - 52.120.0.0/14

It's documented on the Office 365 URLs and IP address ranges page
https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#skype-for-business-online-and-microsoft-teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceccc034-cabb-8c7b-0a09-bae2f6dea85f
* Version Independent ID: 272f36de-c12e-26b3-0378-8549a3ea70ca
* Content: [Prepare your organization's network for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/prepare-network#feedback)
* Content Source: [Teams/prepare-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/prepare-network.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by ndambrosio** [comment]
@joturans FYI - I opened a PR for this yesterday: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/4315

**Comment by scanum** [comment]
@joturans Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@joturans Thank you for reaching out. It looks like it was fixed in the interim. Please confirm. Thanks.

**Comment by scanum** [comment]
@ndambrosio We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
