### ISSUE TITLE
CLI teams access?

### ISSUE THREAD

**Issue by symcbean** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4323]
(got here from a link about MS-Teams)

Is there a chat client or API I can use to attach a bot to Teams? (POSIX compliant)

**Comment by scanum** [comment]
@symcbean thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
