### ISSUE TITLE
Expected policy processing timeframe

### ISSUE THREAD

**Issue by strausy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4326]
Please provide guidance on expected timelines for processing of app permission policies. Is it 8 hours, 24 hours, 72 hours?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b51eda6c-168c-7d99-7cc1-992b3d8feef2
* Version Independent ID: 118a1b8f-f4b7-a778-70b1-d3161fc548ab
* Content: [Manage app permission policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/teams-app-permission-policies#feedback)
* Content Source: [Teams/teams-app-permission-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-permission-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@strausy Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by viperfx** [comment]
Yea I don't think the policy is applied immediately.  This is causing a lot of confusing when IT admins are adding apps to the allowed list.

**Comment by strausy** [comment]
I've been waiting for a Teams app policy to apply for over 48 hours. Microsoft 365 Admin Center support KB article says if Teams Policies do not appear in 48 hours to open a support ticket. I understand things may be under heavy load right now, but at minimum, document expected timeframes under normal circumstances.

**Comment by Reeced40** [comment]
@strausy Thank you for reaching out. It looks like the time frame for change effect is 24 hours. Please let me know if that answers your question.

**Comment by strausy** [comment]
> @strausy Thank you for reaching out. It looks like the time frame for change effect is 24 hours. Please let me know if that answers your question.

The "looks like" is the issue and the reason for this post. The documentation on this page doesn't specify any time frame and the admin managing policies has no guidelines for getting an app policy refreshed. When you search for this issue in the Microsoft admin portal it will tell you to open a ticket if it has been longer than 48 hours. When I first had this issue, it was taking 6+ days to refresh due to high demand. Admins need to know expected time frames based on Microsoft documentation.

**Comment by Reeced40** [comment]
@LanaChin Please can confirm the exact time-frame.

**Comment by LanaChin** [comment]
Thanks for your feedback. @strausy, @Reeced40, the article was updated recently to reflect that after you edit or assign a policy, the changes can take a few hours to take effect. Hope this helps!
