### ISSUE TITLE
Documentation Incorrect!

### ISSUE THREAD

**Issue by Krytical13** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4329]
We have found that with all of the settings entered as shown above, we still don't have the three buttons in the upper right side of the screen that allows for screen sharing and other features in normal chat.
The instructions above only seem to pertain to screen sharing from within an actual meeting, not during chat.

After much time spent trying to figure out why our policies were failing to apply.
It turns out in addition to the above instructions,
You also need to enable the "Calling Policy" for the three buttons to appear in the upper right hand corner of the screen and allow screen sharing during regular chat sessions.

/OffTopicFrustration
It costs our IT department way too much time having to go back and correct mistakes we made because we followed MS documentation. 
People go to Microsoft's official documentation to find instructions to help them.
Why do the users have to tell MS all the time that their own documents are wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce30163-6327-899b-281d-d4ef982fce5e
* Version Independent ID: e61dcbb8-4877-ef6f-1987-981cdd7fc82f
* Content: [Configure desktop sharing in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/configure-desktop-sharing#feedback)
* Content Source: [Teams/configure-desktop-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/configure-desktop-sharing.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **Lolaj**

**Comment by scanum** [comment]
@Krytical13 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by cichur** [comment]
The link is fixed and the doc has been republished. The issue is fixed.
