### ISSUE TITLE
Browsers, mobile browsers

### ISSUE THREAD

**Issue by fitzgeezy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4330]
In the Browsers section it is stated "Note: As long as an operating system can run the supported browser, Teams is supported."

This is not true. On Android/IOS versions of Chrome, you get "unsupported browser" errors when visiting teams.microsoft.com. Same with Edge Chromium on Android. Yes you can switch your mobile browser to "request desktop site".

Also, on Edge Chromium on iOS, even "request desktop site" doesn't work.

So the statement in the Note: is simply not true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#feedback)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@fitzgeezy Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LolaJacobsen** [comment]
Checking with PM Neeraj Jain.

**Comment by LolaJacobsen** [comment]
Checking with PM Luis Carrasco.

**Comment by LolaJacobsen** [comment]
I updated our guidance in the Limits & Specifications article:

As long as an operating system can run the supported browser, Teams is supported on desktop computers. For example, running Firefox on the Linux operating system is an option for using Teams.

For mobile operating systems, we recommend that you run the Teams app, available from the Android and iOS stores. Running Teams in a mobile operating system is supported, but many features are unavailable.
