### ISSUE TITLE
Calendar/Meeting is availbale ?

### ISSUE THREAD

**Issue by Ra4z1k** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4331]
Is a calendar for meetings available under the "Microsoft Teams Commercial Cloud Trial" version? Exchange Foundation  provides it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the Microsoft Teams Commercial Cloud Trial offer - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/iw-trial-teams#feedback)
* Content Source: [Teams/iw-trial-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/iw-trial-teams.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@Ra4z1k thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
