### ISSUE TITLE
Audio can be shared while sharing content

### ISSUE THREAD

**Issue by bartvermeersch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4338]
The page states: 
"No audio while sharing content during a broadcast meeting
When sharing content during a broadcast meeting, audio from the shared content (YouTube link or a saved video file) cannot be hear by participants.
None as this is by design. Teams does not currently support audio from content sharing
10/9/18"

When sharing content, system audio can (now) also be shared: see https://support.office.com/en-us/article/share-system-audio-in-a-teams-meeting-dddede9f-e3d0-4330-873a-fa061a0d8e3b

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues#feedback)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@bartvermeersch Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by KingDrewcifer** [comment]
This is correct, the text is talking about a Broadcast Meeting, not a normal Teams Meetings. This feature is in the pipeline according to the Roadmap. https://www.microsoft.com/en-us/microsoft-365/roadmap?featureid=63276

**Comment by scanum** [comment]
@bartvermeersch Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
