### ISSUE TITLE
Limitation of group chats apply on online meeting chats?

### ISSUE THREAD

**Issue by ulflunqvist** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4339]
The limitation of 100 says "group chat" and not chat in meetings. Would be great if we could verify the same rules apply for meetings, and if the site could be updated with this information. There is alot of the same question in a set of forums out there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@ulflunqvist Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by rboeykens** [comment]
Dear, do you already have an answer to this question? We also experience issues with a meeting larger then 100 people and chat.

**Comment by LolaJacobsen** [comment]
Checking with PM Alan Xie

**Comment by LolaJacobsen** [comment]
@najacobo @Nakulm - Alan asked me to check with you on this.

**Comment by LolaJacobsen** [comment]
I updated the article to clarify that, from a meeting (250-person limit), 250 people can chat and 250 people can call in.
