### ISSUE TITLE
Availability timeline please

### ISSUE THREAD

**Issue by Joon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#434]
This private teams app store is awesome, I have a project in flight that desperately needs it.
Some questions:
What is the timeline of this preview hitting early release tenants?
What is the timeline of this preview hitting normal tenants?
Would it be possible to get this enabled on a specific tenant by opening a support case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c4b732f-12f2-f398-870e-66e4da9844d3
* Version Independent ID: e4fefbfa-c47d-28fc-dc9a-d0a1592fa961
* Content: [Manage the Microsoft Teams Private App Store](https://docs.microsoft.com/en-us/microsoftteams/private-app-store-teams)
* Content Source: [Teams/private-app-store-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-app-store-teams.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by chuckedmonson** [comment]
Please see updated topic at https://docs.microsoft.com/en-us/MicrosoftTeams/tenant-apps-catalog-teams. Thank you.
