### ISSUE TITLE
Recording Teams meetings: Recording failed to upload to Stream

### ISSUE THREAD

**Issue by kleucht** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4341]
This may be just operator error, but since Stream is capitalized in the above error message, was I supposed to create a Microsoft Stream and attach it to my MS-Team before I tried to record any of my Teams meetings?  Every Teams meeting that I've recorded has given me this same error.  And I have definitely NOT created any MS-Streams nor attached any to any of my Teams.  None of my organizational training has told me anything about MS-Streams, nor has any of the documentation that I've been given to read by my organization mentioned MS-Streams.  So I will educate my entire organization if we are doing something wrong.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@kleucht thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
