### ISSUE TITLE
Funcionalidade

### ISSUE THREAD

**Issue by vieiradiego** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4342]
Haveria a funcionalidade de efetuar a geração do EVENTO e esse evento ficar disponível para TODOS acessarem. No mesmo modelo de uma reunião para um GRUPO do Teams. Caso tenha algum material para indicar agradeço.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: b9aa4676-855a-fddb-bb0b-96b7095c695e
* Version Independent ID: 7c39f08c-0d56-6d29-1356-879d9d6ff51c
* Content: [Configurar eventos ao vivo no Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/pt-br/microsoftteams/teams-live-events/set-up-for-teams-live-events#feedback)
* Content Source: [Teams/teams-live-events/set-up-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/set-up-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@vieiradiego  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @vieiradiego, thank you for your feedback.

Sorry, I don´t understand you. Could you please detail your request in English?

More information about Live Events:
https://docs.microsoft.com/microsoftteams/teams-live-events/what-are-teams-live-events
https://support.office.com/article/get-started-with-microsoft-teams-live-events-d077fec2-a058-483e-9ab5-1494afda578a

**Comment by scanum** [comment]
@vieiradiego  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
