### ISSUE TITLE
Requirement is incorrect ( you will not need additional licenses)

### ISSUE THREAD

**Issue by Sagamare** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4343]
I was working on CVM issue and with SFB on-premise we discovered user requires PhoneSystem plan.

Refer : https://docs.microsoft.com/en-us/microsoftteams/set-up-phone-system-voicemail#phone-system-with-on-premises-environments 

This is unclear, but seems I found some users CVM is working without PhoneSystem, please update the documents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 469ac0c8-5c06-7f7f-fe1d-8cadb205572a
* Version Independent ID: 5c9987d5-4c98-8115-55c8-f629dbd25799
* Content: [Plan Cloud Voicemail service for on-premises users - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-cloud-voicemail#feedback)
* Content Source: [Skype/SfbHybrid/hybrid/plan-cloud-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/plan-cloud-voicemail.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@Sagamare  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Sagamare thank you for reaching out and helping improve MS Docs.  Just for clarity, are you suggesting adding a note to these two articles mentioned that additional phone licenses are not needed? If that's not correct, please could you elaborate a bit more.

**Comment by Sagamare** [comment]
Hello Lindsay,

If you check below two docs, the information is very confusing, one says Phone System required and one Says Phone System is not required.

https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-cloud-voicemail#requirements
If you have an on-premises only deployment—that is, only Exchange and Skype for Business on-premises servers—but you want to take advantage of Cloud Voicemail, you will not need additional licenses.

https://docs.microsoft.com/en-us/microsoftteams/set-up-phone-system-voicemail
If the Phone System feature isn't included in your plan, you may need to purchase Phone System add-on licenses. You also need to purchase an Exchange Online license. See Microsoft Teams add-on licensing<https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing>.

Best regards,
Sameer Gamare | Teams & SfB
Working Hours : Mon-Fri | 09:00-06:00pm EST
[cid:image001.gif@01D60C41.E930B7E0]

**Comment by lindspea** [comment]
@dstrome please could you assist with this issue to clarify whether phone system licenses are required.

**Comment by scanum** [comment]
@dstrome Wondering if there are any updates on this issue? thanks

**Comment by dstrome** [comment]
@tonysmit Can you confirm whether a pure on-prem deployment of Exchange and SfB requires Phone System licenses if they want to make use of cloud voice mail?

**Comment by tonysmit** [comment]
Yes, they need a Phone System license for "cloud voicemail".

**Comment by dstrome** [comment]
Thanks Tony for the confirmation and Lindsay for updating the topic. I've merged the update and am closing this issue.

**Comment by carolynblanding** [comment]
@tonysmit @dstrome3 @roykuntz @lindspea 

This is not correct. Phone System license is not required. Previously it was required for one user to have a Phone System license so that the Business Voice Directory would be created for the SfB Online Tenant. My understanding is that all tenants have been synchronized to BVD and newly provisioned tenants will be sync'd automatically.

**Comment by lindspea** [comment]
@carolynblanding would you like me to do another PR to revert back to original info?
