### ISSUE TITLE
How to change the storage limit of the private channel SharePoint site?

### ISSUE THREAD

**Issue by daniRocker** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4350]
I noticed that the private channel SharePoint site was created using the organisation storage limits for new sites, but as I need to change the storage size of a private channel SharePoint site, I am unable to do it. I tried to use the "Set-SPOSite -Identity Tenant/sites/SiteName -StorageQuota 20480 -StorageQuotaWarningLevel 17000" but it shows the following message "Set-SPOSite : The managed path sites/SiteName is not a managed path in this tenant." Any help will be appreciate it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels#feedback)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@daniRocker thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by rachoksh** [comment]
I was able to use this command and it worked correctly to set quota on the private channel site collection . Set-SPOSite -Identity https://abc123.sharepoint.com/sites/My_Cool_SoftwareDev_Team-TeamRoster -StorageQuota 20480 -StorageQuotaWarningLevel 17000
