### ISSUE TITLE
Eavesdropping - Oauth section missing

### ISSUE THREAD

**Issue by ankurms** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4352]
There's a note left at the end of the second paragraph of Eavesdropping that says, 'Add OAuth section/lines.' Does this need to be fixed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33613b2d-d607-ec47-1254-ae540d07ad59
* Version Independent ID: aba728f0-0d3c-73fd-c7fe-68e69b6a753f
* Content: [Security guide for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-security-guide#feedback)
* Content Source: [Teams/teams-security-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-security-guide.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@ankurms thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
