### ISSUE TITLE
MS teams meetings DO WORK in Firefox

### ISSUE THREAD

**Issue by Arusekk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4353]
MS teams meetings *DO WORK* in Firefox. When user agent is pretending to be Chrome. But normal Gecko UA `Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0` gets a pop-up message that it is necessary to install an app (while it clearly is not).

This is really humiliating to disguise the browser in such a way. Please add Firefox (I use unmodified 68.6.0 ESR on Gentoo Linux if this matters) to the list of supported browsers. Or at least add a button to try **connecting despite having an unsupported browser**. This is quite the case also for other MS solutions for audio transmission (e.g. web skype https://go.skype.com/sfw keeps rejecting Firefox, but in fact supports it very well if disguised as Chrome or even Edge).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Arusekk thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
