### ISSUE TITLE
What if both subnet and WAP are defined an conflict?

### ISSUE THREAD

**Issue by vnewbaker-bw** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4354]
As the subject states.  What wins if there is a conflict?  Is there a way to prioritize one over the other based on my deployment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 358dfc73-9414-13e2-4682-c3e82603692f
* Version Independent ID: 3faae1d9-efbe-c20c-6598-a5073c2306e2
* Content: [Configure dynamic emergency calling - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/configure-dynamic-emergency-calling#configure-location-information-service)
* Content Source: [Teams/configure-dynamic-emergency-calling.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/configure-dynamic-emergency-calling.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@vnewbaker-bw  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by vnewbaker-bw** [comment]
I tested this out in my test environment, it seems like WAP is high priority, but an official note in the doc by MS would be appreciated.

**Comment by lindspea** [comment]
@vnewbaker-bw thank you for reaching out and helping improve MS Docs. I will add a note to the article. Would you suggest adding a note saying - "WAP takes priority over subnet" under the heading Configure Location Information Service?

**Comment by vnewbaker-bw** [comment]
So far WAP has consistently had priority over subnet, but I think official word from the Teams developers would be preferred so I know it won't change in future releases.

**Comment by lindspea** [comment]
@CarolynRowe can you please confirm if this is correct - WAP has priority over subnet - and if it's okay that I add a note to the article.

**Comment by vnewbaker-bw** [comment]
Tested with the Android client and iOS client.  Both get address information based on subnet and not WAP so far.

**Comment by scanum** [comment]
@CarolynRowe Any updates here? Thanks!

**Comment by CarolynRowe** [comment]
Sorry for the delay.  I'm following up with the PM.

**Comment by CarolynRowe** [comment]
Thanks for the feedback.  I'll  add a note that WAP takes precedence over subnet.  Closing this Issue.

**Comment by oradcliffe** [comment]
vnewbaker-bw said: Tested with the Android client and iOS client. Both get address information based on subnet and not WAP so far.

So does this mean WAP is prioritized over subnet for PC clients, and mobile clients prioritize subnet?  Can we get official confirmation?
