### ISSUE TITLE
Installed App

### ISSUE THREAD

**Issue by sohailmerchant** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4355]
I think there should be a FAQ included about what happen to the user if allowed app was subsequently blocked by the policy?  Does it get block for the user or since it was installed there will be no implication?  

For example, Jira application was allowed installed by 10 users in the organisation and it was subsequently blocked

https://docs.microsoft.com/en-us/microsoftteams/teams-app-setup-policies

Thanks

**Comment by scanum** [comment]
@sohailmerchant  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@sohailmerchant thank you for reaching out and helping improve MS Docs. The team is continuously adding to articles in this doc set. Please see here for more information in the meantime - https://docs.microsoft.com/en-us/microsoftteams/manage-apps

**Comment by scanum** [comment]
@sohailmerchant Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
