### ISSUE TITLE
Not Authenticating with credentials in Microsoft Teams utilization in Power BI using CQD data

### ISSUE THREAD

**Issue by haugabrook** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4356]
I am not able to get pass the authentication in Power Bi for the CQD data.

![authentication pic](https://user-images.githubusercontent.com/38219862/78057561-ec78ac80-7354-11ea-9b0f-d7f4a81dde74.png)

**Comment by scanum** [comment]
@haugabrook thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by haugabrook** [comment]
I did submit this on our tenant and they told me to submit this on GitHub. If I resubmit this on our tenant, what product team should be added? Should it be Power BI, Teams, authentication, etc.?

Kevin Haugabrook
Application Support and Development, TIS
(727) 588-5051
“Innovation is always uncomfortable.”
“Data is the new oil and will be responsible for the largest transfer of wealth since the industrial revolution.
Organizations that master data will lead the world. Those who don't will wane into irrelevancy.”  ~ James Whittaker

[3colorpcslogo]
                                                                                                                                                                                 Gal. 2:20
