### ISSUE TITLE
REST API Access to Teams Profiles Assignment

### ISSUE THREAD

**Issue by suffieldacademy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4358]
We're not crazy about PowerShell, but have been automating a lot of O365 and Teams through the REST API.  Can you perform policy assignment in Teams using REST?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888fe05b-1160-452f-90ba-deb19adb740f
* Version Independent ID: 4091c5e4-7a90-7fe4-2741-16bbb1f297c1
* Content: [Edit Microsoft Teams users settings in bulk - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/edit-user-settings-in-bulk?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/edit-user-settings-in-bulk.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/edit-user-settings-in-bulk.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@suffieldacademy thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
