### ISSUE TITLE
Scheduling assistant limitation

### ISSUE THREAD

**Issue by davisdre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4359]
It was just noted that there is a limitation using the 'Scheduling Assistant' in teams. Error from Teams desktop app, "We can't provide availability for more than 15 people". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#feedback)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@davisdre  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by davisdre** [comment]
@scanum I've confirmed with a few other people on this. Note, we are seeing this in GCC environment. I haven't confirmed if the limitation is in the commercial environment.

**Comment by lindspea** [comment]
@davisdre that you for reaching out and helping improve MS Docs. Please can you elaborate on this. Where in this article are you suggesting adding a note?

**Comment by davisdre** [comment]
@lindspea I would think maybe somewhere under 'Meetings and Calls'. Since the 'Scheduling assistant' is a scheduling meeting tool when scheduling meetings within Teams.

**Comment by lindspea** [comment]
@davisdre thanks for that. Just to confirm, are you suggesting a note stipulating that there is a limitation where the scheduling assistant can only provide availability for up to 15 people?

**Comment by davisdre** [comment]
@lindspea Yes.

**Comment by LolaJacobsen** [comment]
We updated the content. Thanks everyone!
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/4446
