### ISSUE TITLE
External Access

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4360]
This article should call out External Access is limited to Chat/Calls and calendar invites, and does not allow users to access the full Guest features of Teams channels or SharePoint. The article makes External Access just sound like an older way of Guest Access, but they are very different features as mentioned in this article https://docs.microsoft.com/en-us/microsoftteams/communicate-with-users-from-other-organizations#compare-external-and-guest-access
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c73be3fd-282d-8e5a-02f8-37d2f27c95ab
* Version Independent ID: 0baeeca3-237f-31dc-d3da-35140b9ebb9a
* Content: [Chat, teams, channels, & apps in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/deploy-chat-teams-channels-microsoft-teams-landing-page#guest-access)
* Content Source: [Teams/deploy-chat-teams-channels-microsoft-teams-landing-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/deploy-chat-teams-channels-microsoft-teams-landing-page.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@eschrader  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@eschrader thank you for reaching out and helping improve MS Docs. I'll have the relevant link added to the article for clarity, thank you.

**Comment by scanum** [comment]
@eschrader Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
