### ISSUE TITLE
Private Channel

### ISSUE THREAD

**Issue by tang1397** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4361]
I do not get the option to create a private channel.  The privacy channel option is not shown on the Add Channel dialog.   The Admin Center Team Policy has the Global policy to allow creating private channel though.  It is so weird.  Anyone can help me please?

**Comment by scanum** [comment]
@tang1397 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by tang1397** [comment]
I created a ticket with Microsoft and they checked our system then told me that GCC license does not have private Channel.
