### ISSUE TITLE
Where do tags get saved?

### ISSUE THREAD

**Issue by aledoy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4363]
Is this in AD, on a database? accessible via graph API? where do we see all the tags and manage them as admins (similar to groups)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b16e659e-cf07-268a-e224-fa444749ac29
* Version Independent ID: ee822a8d-b331-998f-e336-b1fa510f35c0
* Content: [Manage tags in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-tags#feedback)
* Content Source: [Teams/manage-tags.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-tags.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@aledoy thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by aledoy** [comment]
How is this a ticket? it's a simple question and it's a technical question. I'm not reporting any bug nor would need a support. Don;t just close a ticket because you don;t know the answer.

**Comment by anniecolonna** [comment]
Hi @aledoy, we are working on surfacing these via Graph API but it's not available yet. You can see the selection of suggested tags in the IT Admin Settings under Org-wide settings --> Team Settings --> Tagging.

**Comment by aledoy** [comment]
> Hi @aledoy, we are working on surfacing these via Graph API but it's not available yet. You can see the selection of suggested tags in the IT Admin Settings under Org-wide settings --> Team Settings --> Tagging.

good to hear, when will it become available? thanks!
