### ISSUE TITLE
Sample Powershell is not a sample its a solution

### ISSUE THREAD

**Issue by markszili** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4368]
The "Sample Powershell Script" heading and section is misleading, because it is actually a solution to the firewall popup issue highlighted further up this page for Desktop clients. It should be highlighted and addressed as a solution in the Security and Compliance section and troubleshooting section. I'm also surprised there is not a option for this popup suppression fix via the the Teams/Office ADMX GPO template?   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients#feedback)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@markszili Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@LolaJacobsen please can you assist. Should this be changed in the article?

**Comment by LolaJacobsen** [comment]
Thanks for the heads up. I clarified the title and added a link from the Windows section of the article.
