### ISSUE TITLE
Add OAuth section/lines.

### ISSUE THREAD

**Issue by smearp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4369]
The last sentence in the second paragraph of the Eavesdropping section says "Add OAuth section/lines."  I'm guessing this was a note from the author to him/herself to add a section on OAuth.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33613b2d-d607-ec47-1254-ae540d07ad59
* Version Independent ID: aba728f0-0d3c-73fd-c7fe-68e69b6a753f
* Content: [Security guide for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-security-guide#feedback)
* Content Source: [Teams/teams-security-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-security-guide.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@smearp Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by MSFTTracyP** [comment]
Thank you so much @smearp! The author, herself, logged in and fixed it. That OAuth information wound up threaded across the document. Thank you for your sharp eyes and that catch!
