### ISSUE TITLE
From vs RURI/To , it is not clear

### ISSUE THREAD

**Issue by antman2001** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4372]
hi, can you please make this doc more clear as to which parameters effect the actual SIP headers: RURI/To and From. Also please an example where only the From is translated and one where only the RURI/To is translated, not only all(RURI/To,From) in same examples please

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6981866f-a685-d802-d64f-98685a5c658d
* Version Independent ID: a1f83744-abb7-4c33-6f60-19ff2732871c
* Content: [Translate phone numbers for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-translate-numbers#feedback)
* Content Source: [Teams/direct-routing-translate-numbers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-translate-numbers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@antman2001 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@CarolynRowe please could you assist?

**Comment by scanum** [comment]
@CarolynRowe Wondering if there are any updates on the issue? Thanks.

**Comment by scanum** [comment]
@CarolynRowe Wondering if there are any updates on the issue? Thanks.

**Comment by scanum** [comment]
@CarolynRowe Wondering if there are any updates on the issue? Thanks.

**Comment by tiburd** [comment]
@antman2001 
Thanks again for your submission.
The article has been updated several times since your submission, so we're closing this issue.
