### ISSUE TITLE
Documentation on if Teams Mutes entrants after X amount of people enter a meeting?

### ISSUE THREAD

**Issue by dreeves14** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4374]
I know I've read this before where after a certain number of attendees enter they enter "muted". Is this true or where is the documentation referencing that mechanic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07eca314-7a40-c7ee-1d31-7a858adff741
* Version Independent ID: dede6892-d7e3-d44d-f8f6-eb4bd50c07f0
* Content: [Turn on or off entry and exit announcements for meetings in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/turn-on-or-off-entry-and-exit-announcements-for-meetings-in-teams)
* Content Source: [Teams/turn-on-or-off-entry-and-exit-announcements-for-meetings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/turn-on-or-off-entry-and-exit-announcements-for-meetings-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@dreeves14 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@dreeves14 thank you for reaching out and helping improve MS Docs. I know the meeting organizer has the ability to "mute" meeting attendees if they don't want to hear them. Users' microphones are also usually muted by default when joining a meeting. The Team is continuously updating how features are managed, but please have another look at the article, I see it's been updated a few days ago. Let me know if you need further information.

**Comment by dreeves14** [comment]
I’m aware of that, but it was a requested feature back in 2018 and on the Teams feature request site it was noted in March of 2018 that this feature was active and after 4 people additional users would arrive with mic’s muted.
    
    
    
    Dalton Reeves    
    Senior Systems Administrator + Technology    
    P (314) 655-5523 | F (314) 309-3103    
    dreeves@anderscpa.com | anderscpa.com    
    800 Market Street, Suite 500 | St. Louis, MO 63101   

    ANDERS CPAs + ADVISORS

**Comment by lindspea** [comment]
@tonysmit please could you assist.

**Comment by scanum** [comment]
@tonysmit Wondering if there are any updates on this issue? Thanks

**Comment by dreeves14** [comment]
Yes please advise. We had a 250 person event and they all came in unmuted, very chaotic.

-DR
    
    
    
    Dalton Reeves    
    Senior Systems Administrator + Technology    
    P (314) 655-5523 | F (314) 309-3103    
    dreeves@anderscpa.com | anderscpa.com    
    800 Market Street, Suite 500 | St. Louis, MO 63101   

    ANDERS CPAs + ADVISORS

**Comment by tonysmit** [comment]
@dreeves14 - I'm checking with the PM. I will report back once I hear.

**Comment by tonysmit** [comment]
Getting back here. It doesn't seem that I can find the right people. This is currently not an admin setting as you can see, however, there is logic in the client that will determine this setting. I've created a feature request for the PG and I'm reaching out to a Client PM to see what the logic is. Please hold. :)

**Comment by tonysmit** [comment]
This is most likely more information that you asked for but......

- So the client determines this setting currently for Teams Meetings. So for <4 users in a meeting they are joined unmuted after 4, they are muted when joined. There isn't an admin control to override this. I've created a feature request for this to be added.
- For dial in Team meetings, there currently isn't a setting to control this from the admin side. However, this once again is controlled by the client setting.
- For Teams admin there isn't a threshold setting for admins so I created a feature request to get this added to Audio Conferencing bridge settings. 
- For SFBO, there isn't an admin setting, but there is a **Mute Audience** setting in the SFB client.

**Comment by tonysmit** [comment]
@dreeves14 - can you send me some specifics on the type of meeting being held and client used? What's the scenario basically?

**Comment by dreeves14** [comment]
Live Events and we had a 250 person Teams call with internal and external clients. I was told by our Marketing Exec that everyone came in unmuted.

Typically it would be a large call anywhere between 15-200 employees doing a remote lunch and learn or some sort of webinar.

-DR

Get Outlook for Android<https://aka.ms/ghei36>
    
    
    
    Dalton Reeves    
    Senior Systems Administrator + Technology    
    P (314) 655-5523 | F (314) 309-3103    
    dreeves@anderscpa.com | anderscpa.com    
    800 Market Street, Suite 500 | St. Louis, MO 63101   

    ANDERS CPAs + ADVISORS
________________________________

**Comment by tonysmit** [comment]
@ashwinma14 - Can you help out here please? Thanks, Tony

**Comment by dreeves14** [comment]
I did notice the other day the feature occurred. It told me 102 people were on the call and it turned my Mic to off with the tool tip advising why.

So now its just a matter of knowing at what head count does that tool tip and action become active for people joining.

[cid:image001.jpg@01D64327.F2E7C770]
    
    
    
    Dalton Reeves    
    Senior Systems Administrator + Technology    
    P (314) 655-5523 | F (314) 309-3103    
    dreeves@anderscpa.com | anderscpa.com    
    800 Market Street, Suite 500 | St. Louis, MO 63101   

    ANDERS CPAs + ADVISORS

**Comment by tonysmit** [comment]
@ashwinma14 - can you assist here please? 

My understanding is that everyone that enters a Live Event will enter muted.

**Comment by dreeves14** [comment]
I will say recently I’ve noticed this feature working.

Again I just don’t know the threshold. I believe yesterday when I joined a group call and I was the 5th or 6th person I may have been auto muted and didn’t notice it – so again maybe this is finally in motion at after 4 ot 5 people.

-DR
    
    
    
    Dalton Reeves    
    IT Infrastructure Support Analyst    
    P (314) 655-5523 | F (314) 309-3103    
    dreeves@anderscpa.com | anderscpa.com    
    800 Market Street, Suite 500 | St. Louis, MO 63101   

    ANDERS CPAs + ADVISORS

**Comment by scanum** [comment]
@ashwinma14 Any updates here? Thank you!

**Comment by tonysmit** [comment]
I'm pinging a different PM.

**Comment by tonysmit** [comment]
Just got a response. He said the threshold is 5 then they are muted for Teams Meetings and for Live events.
