### ISSUE TITLE
Describe how to remove an app from the catalog

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4375]
The page says how to upload and update an app, but not how to remove it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbcabee-fa96-2878-e983-3c966f84ee15
* Version Independent ID: 02fa4fd8-77e0-5cb2-a4af-576cbb68322f
* Content: [Manage your apps in the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/manage-apps#upload-a-new-app)
* Content Source: [Teams/manage-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-apps.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@aosolis Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@aosolis thank you for reaching out and helping improve MS Docs. You should be able to right-click on the App and then "Uninstall". It should also be possible from the "More apps" menu on the lefthand side. Please let me know if you don't come right.

**Comment by aosolis** [comment]
@lindspea, thanks, can we update the documentation with that information?

**Comment by scanum** [comment]
@aosolis Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by aosolis** [comment]
I re-read the documentation and I was actually asking about removing an app from the tenant catalog, not uninstalling an app from Teams. This section: https://docs.microsoft.com/en-us/MicrosoftTeams/manage-apps#upload-a-new-app describes how to
- upload an app "To upload a new custom app to your tenant app catalog..."
- update an app "To update an app after it's uploaded..."
but not how to remove it.
