### ISSUE TITLE
New-CsBatchPolicyAssignmentOperation - Not found

### ISSUE THREAD

**Issue by Cdenby** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4377]
What particular powershell addin is required to run this? It's not specified on this page and it's not recognized.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe8cc5e-0f33-d33a-6765-a3f3a33f1522
* Version Independent ID: 13cc4718-4967-695d-cd07-13c3021d8682
* Content: [Assign policies to large sets of users in your school - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/batch-policy-assignment-edu)
* Content Source: [Teams/batch-policy-assignment-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/batch-policy-assignment-edu.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Cdenby Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Cdenby** [comment]
I found it - it's the azureAdPreview and you have to totally remove AzureAD in order to run it.
uninstall-module -name azuread
Install-Module -Name AzureADPreview

**Comment by lindspea** [comment]
@Cdenby thank you for pointing this out and helping improve MS Docs. Do you recommend adding anything to the article to help other users?

**Comment by scanum** [comment]
@Cdenby We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
