### ISSUE TITLE
Guest w gmail is prompted for password

### ISSUE THREAD

**Issue by kaeferc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#438]
As an organization, we invite guests with various email extensions including gmail. During tests etc. the recipient is prompted for a password before being "allowed" access to Teams. Once the password is created, the next time the guest tries to access Teams, they are again prompted for a password, user uses password that was created and receives prompt that password is invalid and is required to create a new one. When using a hotmail.com email, still prompted for password but in subsequent access, the same password still works. Wondering if this is a one-off or if others are experiencing that also.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2492e210-08f9-a476-97ec-008926def961
* Version Independent ID: adcb0dd9-4a3c-b665-6e34-ce3276c89b4d
* Content: [Guest access in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-access)
* Content Source: [Teams/guest-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access.md)
* Service: **msteams**
* GitHub Login: @laithalshamri
* Microsoft Alias: **laal**

**Comment by kenwith** [comment]
@kaeferc - I am not sure if this is a one-off or something else. I want to make sure you get this figured out. Would you please open a service ticket, instructions here: https://www.youtube.com/watch?v=puuOy0sEg1Y

It would be great to get the knowledge learned on this back into the document. I will keep an eye on support channel too and take any findings to put back into document. Thank you for taking time to provide feedback.
