### ISSUE TITLE
Teams Chat not working at all users

### ISSUE THREAD

**Issue by srudin74** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4380]
We have set Chat for everyone but some user still unable to chat. Does anyone know something about this behaviour?

**Comment by scanum** [comment]
@srudin74 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
