### ISSUE TITLE
Embedded youtube video error

### ISSUE THREAD

**Issue by fvanrijt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4381]
The embedded youtube video is not working. Looking in the page source code it links to: https://youtu.be/XAowXcmQ-kA  which is also a video that is not linked to this topic

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b779004c-92cd-e28c-7672-9a8d9d39103a
* Version Independent ID: 13dc2677-19e3-c5b5-5b17-11febf414e26
* Content: [Best practices for organizing teams in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/best-practices-organizing#feedback)
* Content Source: [Teams/best-practices-organizing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/best-practices-organizing.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@fvanrijt Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@fvanrijt Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
