### ISSUE TITLE
「Electron」の日本語訳について

### ISSUE THREAD

**Issue by takeman-k** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4382]
「Electron」の日本語訳について
「電子」と翻訳されていますが、「Electron」はプロダクト名（固有名詞）なので「Electron」のままでいいのではないでしょうか。（Chromiumと同様の扱い）

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: fc21902c-d522-3851-8587-177f01bc085c
* Version Independent ID: 590bcc64-a86d-b61e-7d94-4e4322c4e71d
* Content: [Microsoft Teams のメモリ使用方法 - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/teams-memory-usage-perf#feedback)
* Content Source: [Teams/teams-memory-usage-perf.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-memory-usage-perf.md)
* Service: **msteams**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@takeman-k Thank you for the feedback. If Bing Translator translated your comment correctly, the proper noun (organization name) Electron is translated to the noun electron (as in atoms). But I agree with your conclusion that they are proper names and there shouldn't be much confusion here. Thanks.
