### ISSUE TITLE
Path to setting needs to be updated

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4383]
Need to update
In the Microsoft 365 admin center, choose Settings &gt; Organization profile.
to 
In the Microsoft 365 admin center, choose Settings &gt; Settings &gt; Organization profile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5586a3f7-0a24-3720-1ad5-336737c44275
* Version Independent ID: c5800980-2d9f-ee75-4193-bc5e8e9a68b9
* Content: [Change the default language for greetings and emails - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/change-the-default-language-for-greetings-and-emails)
* Content Source: [Teams/change-the-default-language-for-greetings-and-emails.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/change-the-default-language-for-greetings-and-emails.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@jantoney Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@jantoney Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
