### ISSUE TITLE
Unclear that moderation is only available for public channels

### ISSUE THREAD

**Issue by kevinpartington-tr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4388]
It would be great to mention that channel moderation is only available for public channels. I had created a private channel to try to play around with this, and the feature was not present-- and this documentation does not mention that it is only available for public channels.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097ecd40-1157-98ae-f438-96f9208afc03
* Version Independent ID: ea36ff93-46dc-920d-8d52-9b3b81420958
* Content: [Set up and manage channel moderation in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-channel-moderation-in-teams#feedback)
* Content Source: [Teams/manage-channel-moderation-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-channel-moderation-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@kevinpartington-tr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@kevinpartington-tr Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
