### ISSUE TITLE
Removing Detailed Feature Support?

### ISSUE THREAD

**Issue by patrickabel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4396]
Until 03/31/20, this page provided a breakdown at a feature level of all the features that were either supported, on the backlog, or unsupported in GCC High. Where did these go?!? This feature comparison and roadmap comprised 90% of this documentation's value. Please point me to where this has gone. The service description for Teams doesn't include near the granularity needed. For instance, details on Intra-cloud (GCCH to GCCH) Federated Meetings, Guest Access, Live Events, Meeting Recordings, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b131c7fd-ec71-6b6f-4443-ddaf5cb44bf6
* Version Independent ID: 0c1fb61b-a6cc-e856-d969-54bc13ec699c
* Content: [How to roll out Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/how-to-roll-out-teams)
* Content Source: [Teams/How-to-roll-out-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/How-to-roll-out-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by patrickabel** [comment]
here's the page URL: https://docs.microsoft.com/en-us/MicrosoftTeams/plan-for-government-gcc-high

**Comment by scanum** [comment]
Duplicate
