### ISSUE TITLE
Link not working 

### ISSUE THREAD

**Issue by MIBadran** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4397]
https://docs.microsoft.com/en-us/microsoftteams/security-compliance-overview#compliance-standards
"Details can be found in the Compliance Framework for Industry Standards and Regulations."
 This link doesnt work 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca579d63-182b-d6f5-8777-79248fa27ed9
* Version Independent ID: b4c27d1b-b2f1-41ac-b15c-d12b448a539e
* Content: [Overview of security and compliance in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/security-compliance-overview#compliance-standards)
* Content Source: [Teams/security-compliance-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/security-compliance-overview.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@MIBadran Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @MIBadran, thank you for your feedback.

Same as:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4175
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3688
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3677

The article was updated 13 days ago and the link was replaced. Really, the entire sentence was replaced.

**Comment by scanum** [comment]
@MIBadran Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
