### ISSUE TITLE
What regions is this available?

### ISSUE THREAD

**Issue by kenwith** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#440]
Do we know what regions this is available for?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the Microsoft Teams Commercial Cloud Trial offer](https://docs.microsoft.com/en-us/microsoftteams/iw-trial-teams#manage-the-iw-trial)
* Content Source: [Teams/iw-trial-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/iw-trial-teams.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by chuckedmonson** [comment]
The regional availability for this offer is shown here: https://commoffertool.catalog.cp.microsoft.com/Prod/Office365/offer/details/3ed11a8a-20e6-4e45-80a0-4d2293c14c88#t-availabilities. You must be authenticated to access the list. The list is periodically updated. Thank you.
