### ISSUE TITLE
Service Agreement 

### ISSUE THREAD

**Issue by dipinn26592** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4400]
Users on Teams desktop clients that are more than three months old will see a blocking page that gives the options to update now, reach out to their IT admin, or continue to Teams on the web.

Desktop client versions that are more than three months old upon first install and/or first run of Teams have a 28-day grace period before encountering the above-mentioned servicing information.

Above lines are confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6da28da-eb7b-d3ae-4c2f-8f87803b1830
* Version Independent ID: 8c42d7a2-80c6-86dd-347a-ed6d8d909c41
* Content: [Teams updates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-client-update#feedback)
* Content Source: [Teams/teams-client-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-client-update.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@dipinn26592 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @dipinn26592, thank you for your feedback.

I have read this sentence several times and it seems to be very accurate to me.

If client is more than 3 months old AND NO new installation = blocking page

If client is more than 3 months old AND new installation = 28-day grace period

I don't know how I can improve it, please let me know if you have some good ideas.

Thanks!

**Comment by dipinn26592** [comment]
Hello Dario,

Thank you for checking on this. The part that I am confused is what does “New installation” mean.  Are we referring to freshly installed client which has not been launched or we are referring to update.

Below are couple of scenarios where I would like to know what will be the behavior.


  1.  If the Teams client was installed on my computer last year ( more than 3 months old ) but it was never launched or never automatically updated.
  2.  If the Teams client was installed on my computer last year ( more than 3 months old ) I used it for couple of weeks then I never used it. ( turned off auto launch due to which the client was never updated )

Regards,
Dipin Nair

**Comment by dariomws** [comment]
Hi @dipinn26592,

In these scenarios I understand:

1. You have a 28-day grace period. Based on this information: "more than three months old upon **first install and/or first run** of Teams have a 28-day grace period"
2. You will see the blocking page, as it was installed and used.
