### ISSUE TITLE
How do we set prompt language default English (United Kingdom)?

### ISSUE THREAD

**Issue by robhardman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4401]
We're a UK entity and so we're only able to set "English" as the preferred language for the organisation. However, this is setting the default "Prompt Language" property of "Get-CsOnlineVoicemailUserSettings" to en-US. How do we set the default to en-GB please?

(Also, we appear to be able to change the individual user properties via Set-CsOnlineVoicemailUserSettings - this appears to contradict the statement on this page that individual user settings can't be altered by an administrator?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5586a3f7-0a24-3720-1ad5-336737c44275
* Version Independent ID: c5800980-2d9f-ee75-4193-bc5e8e9a68b9
* Content: [Change the default language for greetings and emails - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/change-the-default-language-for-greetings-and-emails)
* Content Source: [Teams/change-the-default-language-for-greetings-and-emails.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/change-the-default-language-for-greetings-and-emails.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@robhardman thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
