### ISSUE TITLE
License options based on your plan for Microsoft 365 plans

### ISSUE THREAD

**Issue by YuriHerman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4402]
Hi,
Could the license add-on options for the Microsoft 365 plans also be added ?
Which add-on license are for example possible with Microsoft 365 Business or Microsoft 365 E1 , etc ... ? 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abae7324-861d-7ca7-7239-a5df8fd927d5
* Version Independent ID: 8a30bd2f-9bc3-a0a8-8b31-d53836ead4d0
* Content: [Microsoft Teams add-on licensing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing#feedback)
* Content Source: [Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@YuriHerman Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @YuriHerman, thank you for your feedback.

You can find this information in the article, please go to:
https://docs.microsoft.com/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing#license-options-based-on-your-plan
And select a link for more detail.

**Comment by YuriHerman** [comment]
Hi @diaromws , 
The subscriptions in the link are only the Office365 subscriptions.
My suggestion was that this document would also explain what add-on licenses are possible for Microsoft365 subscriptions.

**Comment by dariomws** [comment]
@YuriHerman Thank you.

Microsoft 365 Ex includes Office Ex. For example, O365 E3 is included on M365 E3:
https://www.microsoft.com/en-us/microsoft-365/compare-microsoft-365-e3-and-office-365-e3-enterprise

The same add-ons you can add on O365 you can add on M365.

**Comment by scanum** [comment]
@YuriHerman Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
