### ISSUE TITLE
Downloaded reports do not contain the same data as what is displayed

### ISSUE THREAD

**Issue by FlorianRD** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4404]
The data provided in the csv files that we generate for download is not consistent with what is displayed on the report side.
I tried to create my own report from those downloaded files but can not 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b138331-2f10-a05d-7e88-68e62e0b3e4f
* Version Independent ID: f923b648-ffe4-8a8a-c189-6e31f1032c10
* Content: [Microsoft Teams usage report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-usage-report#feedback)
* Content Source: [Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@FlorianRD Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @FlorianRD, thank you for your feedback.

I have verified in my demo tenant and for example **Teams user activity report** exported file is consistent with what is displayed on the web report.

Could you kindly specify what report are you downloading?

Anyway, considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by FlorianRD** [comment]
thanks @dariomws, I doubled check and you are right the downloaded reports are in fact consistent BUT you do not get the data as presented in the graphs: you get some data that aggregates all chats, calls... for the requested period but not a a day by day basis and thus you can not reproduce the same graph as those provided and / or create new ones based on this data.
I was for instance looking to get the graph for a specific time frame and was hoping to be able to build this from the exported data...

**Comment by dariomws** [comment]
Thank you @FlorianRD. Docs.microsoft.com feedback is available to get feedback to improve documentation. If you think we need to update/improve this document please let me know.

For feature requests, I need to kindly redirect you to this resource https://microsoftteams.uservoice.com/
There, your suggestion will reach the product team.

**Comment by scanum** [comment]
@FlorianRD Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
