### ISSUE TITLE
Region fields and custom Graphics

### ISSUE THREAD

**Issue by TheResearcher-Hub** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4405]
Some of the graphics are coming up with errors that they will be deprecated. As well some fields are empty such as the Region field, how do i populate the region field? 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e657b86-072e-1dff-0e96-1ec0efa8e4d7
* Version Independent ID: 81d2ec45-8c85-220c-760a-443971fd27f9
* Content: [View Microsoft Teams utilization in Power BI using CQD data - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cqd-teams-utilization-report)
* Content Source: [Teams/CQD-teams-utilization-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-teams-utilization-report.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@TheResearcher-Hub Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @TheResearcher-Hub, thank you for your feedback.

Could you kindly provide us with more detail?

**Comment by scanum** [comment]
@TheResearcher-Hub We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
