### ISSUE TITLE
Create restrictions by user profile in teams

### ISSUE THREAD

**Issue by Leninmv2020** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4408]
we need restrictions by user profile in microsoft teams like:

Meetings.
prevent students from silencing the organizer on class equipment.
prevent students from controlling presentations.

Channels.
Allow scheduling meetings for private channels.

We hope you can help us, thank you very much.

**Comment by scanum** [comment]
@Leninmv2020 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
