### ISSUE TITLE
Pricing for Audio Conferencing

### ISSUE THREAD

**Issue by callit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4411]
This "Pricing for Audio Conferencing" link is useless. It takes you to a Marketing page with another link that says "See Plans & Pricing" and when you click THAT link, all you get is Office 365 plans and pricing - Nothing about audio conferencing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abae7324-861d-7ca7-7239-a5df8fd927d5
* Version Independent ID: 8a30bd2f-9bc3-a0a8-8b31-d53836ead4d0
* Content: [Microsoft Teams add-on licensing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing)
* Content Source: [Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@callit Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @callit, thank you for your feedback.

In that link I can see the following information:
"Pricing for Audio Conferencing
If you have Office 365 E5, Audio Conferencing is included.
If you have Office 365 E1 or E3, Audio Conferencing is available for a $4.00/month add-on fee."

**Comment by scanum** [comment]
@callit Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
