### ISSUE TITLE
Adding users with powershell

### ISSUE THREAD

**Issue by sifiak** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4419]
If I add users with powershell by a admin account which is not member of the team it will still produce a message that "Jack added Hans to the team"... But Jack has not made any changes. In some cases it will tell only "hans joined the team" but currently we dont see any logic... any ideas ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d86301b-ce9c-388c-e563-9e5e5c27132e
* Version Independent ID: 07e4ae23-0966-e8f3-9b7c-4f6c02569eb0
* Content: [Office 365 Groups and Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/office-365-groups#feedback)
* Content Source: [Teams/Office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-groups.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@sifiak thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by sifiak** [comment]
@scanum, case #19460228, no fix, works as desgined. If you add user by a global admin into such team, you will get a message that the user was added by an owner of this team (owner and the global admin are different users, system does not care...). will you guys handle this somehow?
