### ISSUE TITLE
Unable to Use Teams Exploratory Experience

### ISSUE THREAD

**Issue by qhdevon43** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4420]
We have multiple unlicensed users in our office 365 tenant. When the user goes to https://teams.microft.com they are asked to sign in and when they do they are presented with a message that says "Your missing out! Ask your admin to enable Microsoft Teams for (our organization). 

I was told that any unlicensed user when signing into teams would get assigned a license. I even have support from office 365 Support looking into this Ticket #18839814. Its been over 2 months and no one has gotten back to me on this issue. Keep in mind we only have about 20+ users in our organization so perhaps this is the reason why? And yes I have followed the document exactly to enable Microsoft Teams Exploratory Service. Our users who are working from home could use teams during this tough time in the world. 
![teams_exploratory](https://user-images.githubusercontent.com/18177556/78463651-aac16c00-769c-11ea-8972-0f9378af9185.png)

**Comment by scanum** [comment]
@qhdevon43 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
