### ISSUE TITLE
Admin access to private Teams channels

### ISSUE THREAD

**Issue by AndreaKenton** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4421]
Hi, the IT admin can access to a private channel in a Microsoft Teams Team?
Can he red posts?
Can he access to an istant meeting?
Thanks you!

**Comment by scanum** [comment]
@AndreaKenton thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
