### ISSUE TITLE
Screenshots outdated

### ISSUE THREAD

**Issue by joturans** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4424]
Screenshots of the portal need review. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dc173c-0c98-1b94-a2f7-0a34781c985a
* Version Independent ID: a1c44ccb-67f3-f98e-6569-f938e88ddc63
* Content: [Set the phone numbers included on invites - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/set-the-phone-numbers-included-on-invites-in-teams)
* Content Source: [Teams/set-the-phone-numbers-included-on-invites-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-the-phone-numbers-included-on-invites-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@joturans Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@joturans thank you for reaching out and helping improve MS Docs. Are you referring to a screenshot in the article that needs updating, or are you recommending a new screenshot to be added to the article?

**Comment by scanum** [comment]
@joturans  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by joturans** [comment]
The existing screenshots are outdated. They show the old Blue themed Teams admin portal, it's now purple.
