### ISSUE TITLE
Browser supportability on different platforms.

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4428]
If the browser is mentioned as supported  - Edge and Chrome - is it supported on any platform? If not can you please add information what platforms are supported - Windows, MacOS, iOS, Android, Linux. In the document I can read "As long as an operating system can run the supported browser, Teams is supported. For example, running Firefox on the Linux operating system is an option for using Teams." but when I try to run Chrome or Edge on iOS I get information "this browser version is not supported". Forcing Chrome into PC mode on iOS gives me ability to conenct and see shared content but not join with audio or see video.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Larryngolog thank you for reaching out and helping improve MS Docs. The official list of supported browsers is here - https://docs.microsoft.com/MicrosoftTeams/get-clients

**Comment by Larryngolog** [comment]
Hi Lindsay. The same information is provided on the "get-clients" page as on the limits page. It states on both articles that chrome and edge on chromium is supported on iOS and Addroid  (as these browsers are officially supported), which based on my tests is not correct. I think that both documents need correction and more details about supportabilit of the web app on mobile. If the document "get clients" is the official source, then please remove entirely the section about browsers from limits article and redirect to the clients article.

**Comment by lindspea** [comment]
@LolaJacobsen please could you have a look at this issue.

**Comment by lindspea** [comment]
@LolaJacobsen please could you have a look at this issue?

**Comment by LolaJacobsen** [comment]
Checking with PM Neeraj Jain.

**Comment by LolaJacobsen** [comment]
Checking with PM Luis Carrasco.

**Comment by LolaJacobsen** [comment]
I updated our guidance in the Limits & Specifications article:

As long as an operating system can run the supported browser, Teams is supported on desktop computers. For example, running Firefox on the Linux operating system is an option for using Teams.

For mobile operating systems, we recommend that you run the Teams app, available from the Android and iOS stores. Running Teams in a mobile operating system is supported, but many features are unavailable.

**Comment by Larryngolog** [comment]
Thanks Lola


Do you think it will be possible in the future to further elaborate on the “many features are unavailable.” Part? For example add browsers on mobile section the the “Browsers” table and mention what is supported and what not in given browser on iOS and Android? Just like we have it now for IE, Edge, Chrome and other browsers? It would be great to have mention for each browser that on mobile this and that is not supported.

It would also be great if we could have on-par documentation and web-app behavior – if browser is supported then app should not display that it’s not supported and require you to manually change the mode to desktop. Maybe it’s a feedback you can provide to the PG?


Best regards

Paweł Wróbel
Teams Technical Specialist
Modern Workplace
Tel: +48 (22) 594 1256
Mob: +48 505 19 1580

[MSFT_logo]
Microsoft Sp. z o.o. | Al. Jerozolimskie 195A | 02-222 Warszawa | Polska | NIP: 527-010-33-91 | KRS: 0000056838
Sąd Rejonowy dla m. st. Warszawy, XIII Wydział Gospodarczy Krajowego Rejestru Sądowego | Kapitał zakładowy: 2.774.023 zł
