### ISSUE TITLE
Office 365 Groups generated as a result of Microsoft Teams not always hidden in Outlook

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4430]
Hi,

The article states 'Based on customer feedback, new Office 365 Groups generated as a result of creating a team in Microsoft Teams will no longer show in Outlook by default. For customers that want to continue with the existing behavior of showing these groups in Outlook, an Exchange Online PowerShell cmdlet will be provided which can enable the group for the Outlook experience.'

However, in our testing this is not always the case. If a user creates a new Team via the official Teams client, then this behaviour is correct. However, if a new Team is created via by an admin via the Teams Admin Centre, or via PowerShell, the Team is *not* hidden from the GAL or Microsoft Outlook by default, and the PowerShell command 'HiddenFromExchangeClientsEnabled' must be run for this to hide the Team from the Global Address List and Outlook clients - see https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/set-unifiedgroup?view=exchange-ps

Please update the documentation to reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d86301b-ce9c-388c-e563-9e5e5c27132e
* Version Independent ID: 07e4ae23-0966-e8f3-9b7c-4f6c02569eb0
* Content: [Office 365 Groups and Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/office-365-groups)
* Content Source: [Teams/Office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-groups.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@ChrisAtMAF Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by abgupta** [comment]
@ChrisAtMAF , I tried to repro the problem but could not see the issue. I created a Team using powershell cmdlet New-Team and did not see the team listed in my Outlook client. Can you confirm perhaps with pictures on what you are seeing?
Thanks!

**Comment by ChrisAtMAF** [comment]
Hi @abgupta 

My apologies - I did not test this sufficiently.

Teams created via the Teams client, or via New-Team in PowerShell, **do** have HiddenFromExchangeClientsEnabled is enabled, as documented.

However, teams created via the Teams admin console (https://admin.teams.microsoft.com/teams/manage) ***do not* have HiddenFromExchangeClientsEnabled enabled - see below:

![image](https://user-images.githubusercontent.com/53898223/80696106-d7677880-8ace-11ea-8f7c-25c0c011f359.png)

![image](https://user-images.githubusercontent.com/53898223/80696195-f6660a80-8ace-11ea-850b-15634ffe4a55.png)

This occurs whether the Team is set to Public or Private.

If the Teams Admin Centre could be changed so it behaves the same as the other routes, that would be fantastic.

**Comment by lindspea** [comment]
@scanum this can be closed thank you as documentation changes are coming up.

**Comment by scanum** [comment]
@abgupta Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by ChrisAtMAF** [comment]
Hi,

I'm afraid this hasn't resolved the issue -  if a new Team is created via by an admin via the Teams Admin Centre, the Team is not hidden from the GAL or Microsoft Outlook by default. The documentation still needs to be updated to reflect this; Set-UnifiedGrop -Identity <groupname> -HiddenFromExchangeClientsEnabled needs to be run in order to hide the group in these scenarios.
