### ISSUE TITLE
Known issue: Timeline - Outlook 365 - Presence not showing with Teams

### ISSUE THREAD

**Issue by Peanutsmasher** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4431]
Hi Teams,

you state that the following issue is known:

Important
If you uninstall the Skype for Business client after you move a user to Teams Only mode, presence stops working in Outlook and other Office apps. Presence works fine in Teams. Workaround: To see presence in Outlook (and other Office apps), Skype for Business must be installed, even if you're running Teams in Teams Only mode. Microsoft is aware of this problem and is working on a fix.

May I ask if there is a timeline for the fix?

Best regards
Henrik

**Comment by scanum** [comment]
@Peanutsmasher thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
