### ISSUE TITLE
FERPA

### ISSUE THREAD

**Issue by lysmyers** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4432]
Please update page to include comment on Microsoft Teams support of FERPA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca579d63-182b-d6f5-8777-79248fa27ed9
* Version Independent ID: b4c27d1b-b2f1-41ac-b15c-d12b448a539e
* Content: [Overview of security and compliance - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/security-compliance-overview#feedback)
* Content Source: [Teams/security-compliance-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/security-compliance-overview.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@lysmyers Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@lysmyers thank you for reaching out and helping improve MS Docs. Are you referring to the Family Educational Rights and Privacy Act (FERPA).  Please let me know where you see the comment reflecting this for MS Teams.

**Comment by scanum** [comment]
@lysmyers  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
