### ISSUE TITLE
Setting for Anonymous users?

### ISSUE THREAD

**Issue by StephenY-Titian** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4434]
The page introduction says "You can also configure whether anonymous or external users can request control", but the rest of the page doesn't say which specific setting controls this for anonymous users, and only mentions participants and external users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce30163-6327-899b-281d-d4ef982fce5e
* Version Independent ID: e61dcbb8-4877-ef6f-1987-981cdd7fc82f
* Content: [Configure desktop sharing in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/configure-desktop-sharing#feedback)
* Content Source: [Teams/configure-desktop-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/configure-desktop-sharing.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **Lolaj**

**Comment by scanum** [comment]
@StephenY-Titian Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@LolaJacobsen please could you assist? Do the settings for participants and external users also apply to anonymous users?

**Comment by cichur** [comment]
@StephenY-Titian Thank you for your question. External participants in Teams meetings can be categorized as follows:
Anonymous user
Guest users
B2B user
Federated user
Therefore, settings that reference External participants can mean any of the users in the list.

**Comment by StephenY-Titian** [comment]
@cichur Thank you for the explanation.  Is there a Teams documentation page which contains that definition / categorization of external users?  Given your explanation that anonymous users are a subset of external users, the introduction to this page which says "anonymous or external users" is a bit misleading (at least to me), and might be worth changing.

**Comment by cichur** [comment]
Hi @StephenY-Titian Please see this article https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams for additional information. You are correct--that introduction is a bit contradictory. I will edit that. Thank you. Cindy

**Comment by scanum** [comment]
@StephenY-Titian Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
