### ISSUE TITLE
Group ID does not display in full

### ISSUE THREAD

**Issue by rossjeremy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4435]
When using MS Teams admin to find out the group ID of a team, the group ID column does not display the ID in full and is abbreviated with ...

**Comment by scanum** [comment]
@rossjeremy thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
