### ISSUE TITLE
Missing setting for Modern Auth

### ISSUE THREAD

**Issue by JankeSkanke** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4439]
As I am configuring my TeamsMTRs with a skysettings.xml during deployment, and I know finally can block basic authentication for my MTR accounts, it fails of course on first boot and a local admin has to actually logon to the device to enable Modern Auth. I have not found a setting for setting this initially within the XML. Is that possibly something that exists but is not yet documented? If not, that should be added very soon.

**Comment by scanum** [comment]
@JankeSkanke thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
