### ISSUE TITLE
Remove the latest version numbers in documentation

### ISSUE THREAD

**Issue by cycloidmike** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4440]
For https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels-life-cycle-management#install-the-latest-teams-powershell-module-from-the-powershell-test-gallery

It lists the current version of MicrosoftTeams to be 1.0.3 but it's actually 1.0.5 and will be updated again soon. The same issue applies to the test gallery, 1.0.18 but the current version is 1.0.21

Could you please remove the version number so that we don't have to update this document every time there's an update?

**Comment by scanum** [comment]
@cycloidmike Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@cycloidmike Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
