### ISSUE TITLE
Hybrid not required

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4444]
Under Prerequisites, it says: "A Skype for Business hybrid topology is not required, but it is recommended." This seems to contradict this page: https://docs.microsoft.com/en-us/MicrosoftTeams/upgrade-to-teams-execute-skypeforbusinesshybridonprem. Can you clarify what it means?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12d73609-83a4-cdd4-8461-59fc1a9152fc
* Version Independent ID: b72ffa6e-f060-c296-e42d-eb3815a932ea
* Content: [Meeting First - Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/meetings-first)
* Content Source: [Teams/meetings-first.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meetings-first.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Air-Git Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Air-Git** [comment]
I've now been told by a Microsoft specialist in Teams that this is correct. Hybrid is not a technical prerequisite for Meetings First. I will leave a comment on the other co-existence pages, which imply that it is.

**Comment by scanum** [comment]
@Air-Git Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
