### ISSUE TITLE
Direct Routing Phone numbers

### ISSUE THREAD

**Issue by vnewbaker-bw** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4449]
Phone numbers in my Direct Routing teams tenant do not show up in the Phone Numbers section of the Teams admin portal.  Is that expected behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6666c222-ded8-739c-bde0-c1c0d6b5c50e
* Version Independent ID: ac46f065-480d-626e-15a9-eab52ff60fc6
* Content: [Manage phone numbers for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization/manage-phone-numbers-for-your-organization)
* Content Source: [Teams/manage-phone-numbers-for-your-organization/manage-phone-numbers-for-your-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-phone-numbers-for-your-organization/manage-phone-numbers-for-your-organization.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@vnewbaker-bw Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by vphimmasone** [comment]
Hi,
I have the same issue too -please advise

**Comment by lindspea** [comment]
@vnewbaker-bw thank you for reaching out and helping to improve MS Docs. The article was updated 2 days ago. Please let me know if you need any more assistance.

**Comment by vnewbaker-bw** [comment]
I looked over the docs and I still don't see any mention of direct routing phone numbers and where to find them in the teams admin portal.

**Comment by scanum** [comment]
@vnewbaker-bw Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by vnewbaker-bw** [comment]
If you could quote the specific section that describes managing direct routing phone numbers from the admin portal, or a note indicating that this is not an option that would be sufficient.  Thanks.

**Comment by lindspea** [comment]
@vnewbaker-bw please have a  look at this article - https://docs.microsoft.com/microsoftteams/direct-routing-plan
