### ISSUE TITLE
RFC1918 addresses should not be used as example IP addresses, use example ranges in RFC5737

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4450]
This article shows RFC1918 private, non-routable IP addresses as the Trusted IPs (172.16.x.x in this diagram). By definition, these addresses will NEVER be routed over the internet, they are for private, internal use only.

Please use RFC 5737 https://tools.ietf.org/html/rfc5737 address ranges instead.
   The blocks 192.0.2.0/24 (TEST-NET-1), 198.51.100.0/24 (TEST-NET-2),
   and 203.0.113.0/24 (TEST-NET-3) are provided for use in
   documentation.

This will help eliminate confusion as people see the RFC1918 ranges of 10.0.0.0 to 10.255.255.255, 172.16.0.0 to 172.31.255.255, and 192.168.0.0 to 192.168.255.255 and understand those to mean private, internal addresses and not example external addresses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbab466f-88f8-302a-7cda-d53bc743e831
* Version Independent ID: b5634fb3-6627-3fcd-101c-0ebc419d7b19
* Content: [Direct Routing Local Media Optimization - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-media-optimization)
* Content Source: [Teams/direct-routing-media-optimization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-media-optimization.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@TorrenManson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@TorrenManson thank you for reaching out and helping improve MS Docs.  I work on the editing/writing side of the articles. Please can you clarify which part of the article needs to be updated.

**Comment by CarolynRowe** [comment]
I will follow up with the PM about the IP addresses.

**Comment by scanum** [comment]
@CarolynRowe Hi Carolyn, any update on this issue? Thanks!

**Comment by FilippSe** [comment]
Will be fixed within a week

**Comment by TorrenManson** [comment]
Hi - are the fixes going to be published anytime soon?

**Comment by lindspea** [comment]
@CarolynRowe @FilippSe

**Comment by scanum** [comment]
@CarolynRowe @FilippSe Following up on this, thank you!

**Comment by tiburd** [comment]
@TorrenManson - it looks like the [updated article](https://docs.microsoft.com/MicrosoftTeams/direct-routing-media-optimization) no longer includes the private IP addresses, so I'm closing this issue.

If the issue still exists, please open a new issue.

Thank you!

**Comment by TorrenManson** [comment]
Reopened at #7804 as the updated article does not address the issue.

**Comment by CarolynRowe** [comment]
Looping in @FilippSe.
