### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by greganth1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4454]
The documentation needs to be updated that the requirement to have Skype for Business installed has been fixed with the latest Teams build. This GA'd back in the first week of March.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a162ef5c-3099-7f58-4178-d29e3ec2b5a7
* Version Independent ID: 6ca31e56-052d-6c62-1323-b5aaaae1f04a
* Content: [User presence in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/presence-admins)
* Content Source: [Teams/presence-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/presence-admins.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@greganth1 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by aalejandroaraujo** [comment]
Greganth is right, please fix this ASAP. Thanks!

**Comment by lindspea** [comment]
@greganth1 @aalejandroaraujo thank you for pointing this out and helping improve MS Docs. Just to clarify, should I remove the "Important" note at the top of the article?

**Comment by greganth1** [comment]
@lindspea Yes. The fix recently rolled out no longer has the requirement to have Skype for Business installed.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@greganth1 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
