### ISSUE TITLE
Teams Room Management topic should cover the Teams Admin Center portal experience 

### ISSUE THREAD

**Issue by tomlaciano** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4456]
This page speaks about managing Microsoft Teams Rooms with logs of other tools, can this page be updated to include what is capable from Teams Admin Center under Devices and Teams Rooms? 
If content for Teams Admin Center does exist and I missed it, please add a url to this page for that content. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ad37b23-8b85-a502-f176-d90586c0a1c1
* Version Independent ID: dcc4aba8-e341-4f19-cd0a-4c99cd5ef3bf
* Content: [Management overview for Microsoft Teams Rooms - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-manage#feedback)
* Content Source: [Teams/rooms/rooms-manage.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-manage.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@tomlaciano Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@tomlaciano thank you for reaching out and helping improve MS Docs. Please have a look at these two articles and let me know if you need further help - https://docs.microsoft.com/microsoftteams/manage-teams-skypeforbusiness-admin-center and https://docs.microsoft.com/MicrosoftTeams/using-admin-roles

**Comment by tomlaciano** [comment]
Hi Lindspea, 
Sorry but the content you offered is not relevant to my comment. Your content focuses on permissions where this article was describing how to use Azure to monitor equipment. At Ignite 2019, there was a session - MTG30 https://youtu.be/rL9fXZJSnog?t=2158 starting at 35:58 that shows the new Teams Admin Center capabilities to manage and monitor Teams Rooms which should make this Azure content a secondary alternative for customers.

**Comment by lindspea** [comment]
@dstrome please could you assist?

**Comment by dstrome** [comment]
@tomlaciano - thanks for you feedback. This new UI has not yet been released widely and so the current management experience for the majority of customers is reflected in the documentation. As soon as the new management experience is broadly released, the documentation will be updated.
