### ISSUE TITLE
Known-issues.md lacking proper workaround for Teams voicemail SPF issue

### ISSUE THREAD

**Issue by jspcstl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4457]
![image](https://user-images.githubusercontent.com/17784483/78718901-0dab4100-78f1-11ea-9540-c5b484d90b30.png)

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md

- Problem is applicable to non PSTN calls as well, whether the user is cloud pbx enabled or not.

- What is an etr? "Exchange Transport Rule" Would definitely help people understand this if they aren't exchange administrators.

- "adding a exception in the etr" Could you provide some more information regarding the elements that could be used to guarantee the email is indeed coming from the TEAMS voice mail system that could be used in such ETR? 

Lastly, we have implemented this SPF transport rule because of MS allowing Cross-tenant spoofing, now it breaks delivery of TEAMS voicemail... I would be much simpler to actually use the infrastructure you are having your customers include in their SPF records or simply provide an SPF record to be included for TEAMS.

**Comment by scanum** [comment]
@jspcstl Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@jspcstl thank you for pointing this out and helping improve MS Docs. Please have a look at these links and let me know if they help at all - https://techcommunity.microsoft.com/t5/microsoft-teams/ms-team-voicemail/m-p/328596 and https://docs.microsoft.com/SkypeForBusiness/troubleshoot/hybrid-phone-system/voicemails-not-delivered

**Comment by jspcstl** [comment]
unfortunately those articles do not provide any information pertaining to what elements should be used to exception CVM mails from our spf fail transport rule.

for now we are using the following exception, but no way to tell its enough or too much...

sender ip addresses belong to one of these ranges: '52.112.0.0/14'

**Comment by lindspea** [comment]
@LolaJacobsen could you please assist?

**Comment by scanum** [comment]
@LolaJacobsen Any update here? Thanks!

**Comment by LolaJacobsen** [comment]
We've been doing a massive update on the Known Issues page and process. Check out the new topic:
https://docs.microsoft.com/en-us/microsoftteams/known-issues
