### ISSUE TITLE
Teams Meeting on Web

### ISSUE THREAD

**Issue by thx1200** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4458]
Instructions are missing for how to disable Teams Meeting button in web appointments.  We don't use Teams and it's confusing our end users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Use the Microsoft Teams Meeting add-in in Outlook - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook#feedback)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@thx1200 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@thx1200 thank you for reaching out and helping improve MS Docs. Please hae a look at this link and let me know if it helps at all. https://techcommunity.microsoft.com/t5/microsoft-teams-blog/why-can-t-i-see-the-microsoft-teams-meeting-add-in-for-outlook/ba-p/174630

**Comment by mdhare** [comment]
Since Teams is not compatible with a remote desktop environment, there does not seem to be a way to install the Teams Addin on Outlook for Remote Desktop. Please fix.

**Comment by lindspea** [comment]
@mdhare this article was updated yesterday. "Under some circumstances, the Teams add-in is not available in Outlook. See Upgrade from Skype for Business to Teams for details - https://docs.microsoft.com/microsoftteams/upgrade-to-teams-on-prem-overview#meetings."Please let me know if you still need assistance.

**Comment by scanum** [comment]
@thx1200 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
