### ISSUE TITLE
SRSDeploymentKit-4.4.25.0 is for what OS build?

### ISSUE THREAD

**Issue by tangx007** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4459]
From CreateSrsMedia.ps1 now only download MTR version is SRSDeploymentKit-4.4.25.0, but this version is not listed under this page, pls clarify which os build can support with this MTR version?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7ecd6ee6-8850-f346-5684-9c5d2444789f
* Version Independent ID: a55a7a01-211d-147a-5332-b68e1051a2a1
* Content: [版本支持 - Microsoft Teams](https://docs.microsoft.com/zh-cn/MicrosoftTeams/rooms/rooms-lifecycle-support)
* Content Source: [Teams/rooms/rooms-lifecycle-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-lifecycle-support.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@tangx007 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by tangx007** [comment]
Would you pls reopen this issue? My concern is : this page is not list the latest MTR version (4.4.25.0) for the reader to reference, they would confuse what OS build they should use to create the MTR imgae.

Under that page, the latest MTR version showed is 4.2.4.0, but from CreateSrsMedia.ps1 now only can download MTR version is 4.4.25.0

**Comment by tangx007** [comment]
Would you pls reopen this issue? Under that page, the latest MTR version showed is 4.2.4.0, but from CreateSrsMedia.ps1 now only can download MTR version is 4.4.25.0

I checked this page again, still not update the latest MTR version 4.4.25.0 to that article
