### ISSUE TITLE
No available interop options

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#446]
It looks like there are only two options now for Teams interop: Islands and SfB only. Is this intentional? Is there still a way to maintain interop?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d53d0cb0-90a6-5932-f78e-7de6fcc4d481
* Version Independent ID: 3d468027-cc37-5199-32ec-819bf62b2caa
* Content: [Microsoft Teams and Skype for Business coexistence and interoperability](https://docs.microsoft.com/en-us/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability)
* Content Source: [Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md)
* Service: **msteams**
* GitHub Login: @arachmanGitHub
* Microsoft Alias: **MyAdvisor**

**Comment by arachmanGitHub** [comment]
hi @thedrum808, there's a reference to https://docs.microsoft.com/en-us/microsoftteams/migration-interop-guidance-for-teams-with-skype in the article that talks more into the details of what's available now and the future. Aside from Islands and SfB only modes, the other modes will be available soon.

**Comment by kenwith** [comment]
Closing this out but if there is still an issue with any article please re-open. Thanks.
