### ISSUE TITLE
Teams notifications do not respect macOS ‘do not disturb’

### ISSUE THREAD

**Issue by robinwhittleton** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4464]
Teams has decided on a custom notification format on macOS: that‘s fine, but it needs to respect macOS’s ’do not disturb’ setting in the notifications centre. At the moment, flipping that switch will mute all native notifications, but Teams notifications still keep on popping up over the top of presentations, etc.

Is this functionality planned?

**Comment by scanum** [comment]
@robinwhittleton thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by robinwhittleton** [comment]
Found that this feature request was on UserVoice and is currently in development (and has been in development for 24 months): https://microsoftteams.uservoice.com/forums/555103-public/suggestions/16941685-use-built-in-notifications-for-macos
