### ISSUE TITLE
Existing meetings

### ISSUE THREAD

**Issue by LoremanReturns** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4467]
Does this configuration will work for already created meetings or just for the newly created ones after the policy configuration on the user?

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 9ce30163-6327-899b-281d-d4ef982fce5e
* Version Independent ID: e61dcbb8-4877-ef6f-1987-981cdd7fc82f
* Content: [Configurare la condivisione desktop in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/it-it/microsoftteams/configure-desktop-sharing#feedback)
* Content Source: [Teams/configure-desktop-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/configure-desktop-sharing.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **Lolaj**

**Comment by scanum** [comment]
@LoremanReturns  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LoremanReturns** [comment]
@scanum thanks for your response, in the meanwhile i investigated the configuration. Different from Skype for Business, these settings are applied per-user. This means that the setting, such as "allow an external participant to give or request control", is applied to the Teams User for any internal or external meeting. I solved my doubt, thanks!

**Comment by VLG17** [comment]
@LoremanReturns These policies and configurations control the type of meetings that users can create or the features that they can access while in a meeting. It also helps determine how meetings deal with anonymous or external users.

I'm happy to hear you solved your doubt.

**Comment by scanum** [comment]
@LoremanReturns Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
