### ISSUE TITLE
64-bit installer should not install on 32-bit systems

### ISSUE THREAD

**Issue by andocromn** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4471]
The machine wide 64-bit installer actually installs itself onto 32-bit systems, then the second stage fails to install because DUH - such bad code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Teams using Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@andocromn thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by andocromn** [comment]
@scanum I do not require "**service**" and **"I"** do not have an issue, the issue is Microsoft's and I was merely trying to help.  This is also the 3rd time I've made attempts in this manor and every response I've received I would categorize as **Denial of Responsibility**.

_Quite frankly if you don't want to drink the water there is also the glue factory_
