### ISSUE TITLE
Partner eCDN Support for Teams Live Events not present

### ISSUE THREAD

**Issue by c016smith** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4472]
I have a RAMP eCDN installed and it does not work with Teams Live Events, purportedly because that endpoint is still using older Skype Meeting Broadcast backend. Can someone confirm if that is old information, because it isn't working for me with Ramp, and Ramp has told me it's a known issue with Microsoft and work that's in progress but not completed yet.   
We are working out logistics right now for a large event hosted by our CEO and trying to figure out ways around this, but the Teams Live Event method (with eCDN support) is exactly what we need, but it's not functioning right now. 
Support call would be great if this is truly supported, but if it's not quite ready yet then might need to update this page.  Thanks!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events#feedback)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@c016smith thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
