### ISSUE TITLE
Add info for Chromebook use

### ISSUE THREAD

**Issue by rburte-isp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4473]
Hi there, 
given quarantine measures for the SAR-CoV-2/Coronovirus 2020 pandemic driving the use of Chromebooks, can you add official guidance on how to use Teams on them? Even if it's "Use the Android app" or "Use the web app".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients#feedback)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@rburte-isp  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@rburte-isp The Teams app is available on Chromebooks for a while now - [more details here](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/31380832-chromebook-support-in-the-android-app-please?page=2&per_page=20#{toggle_previous_statuses}). I'll add a note about that.

For the Web client, i think it's already covered. The Teams Web client is supported on all operating systems that can run the supported browsers stated in the article:

> As long as an operating system can run the supported browser, Teams is supported

So as long as you use a supported web browser on your Chromebook, Teams will work as it should.

**Comment by scanum** [comment]
@rburte-isp Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
