### ISSUE TITLE
The PowerShell command to update MTR software is not work

### ISSUE THREAD

**Issue by tangx007** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4475]
https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-operations#to-update-using-powershell

## wrong powershell:
Add-AppxPackage -Update -ForceApplicationShutdown -Path '\\<share>\$oem$\$1\Rigel\x64\Ship\AppPackages\*\*.appx' -DependencyPath (Get-ChildItem '\\<share>\$oem$\$1\Rigel\x64\Ship\AppPackages\*\Dependencies\x64\*.appx' | Foreach-Object {$_.FullName})

after I run this command on MTR's admin account, it will prompt me that the previous version is not installed, then I do some investegate and found that the SkypeRoomSystem app is installed under Skype account but not the admin account, so it prompt that error is make sense.

Then, I suggest to do more update on the powershell, and below I have tested works on my hub500

## 2) Create a PS script as below, and named: C:\InstallSkype.ps1
$temp = 'C:\Program Files (x86)\Skype Room System Deployment Kit\$oem$\$1'
Add-AppxPackage -Update -ForceApplicationShutdown -Path $temp\Rigel\x64\Ship\AppPackages\*\*.appx -DependencyPath (Get-ChildItem $temp\Rigel\x64\Ship\AppPackages\*\Dependencies\x64\*.appx | Foreach-Object {$_.FullName})

## 3) Run below script to install Rigel App for Skype user under admin user
$creds = New-Object System.Management.Automation.PSCredential ("Skype", (new-object System.Security.SecureString))
reg.exe add "HKLM\System\CurrentControlSet\Control\Lsa" /f /v "LimitBlankPasswordUse" /t REG_DWORD /d 0
start-process -FilePath powershell.exe -wait -Credential $creds -ArgumentList @("-executionpolicy","Unrestricted","C:\InstallSkype.ps1")
reg.exe add "HKLM\System\CurrentControlSet\Control\Lsa" /f /v "LimitBlankPasswordUse" /t REG_DWORD /d 1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd52fe62-457b-c9e1-ad13-a9b1f24c9c38
* Version Independent ID: 6a8c3285-30e1-15a8-6472-f0cfe5b30e20
* Content: [Microsoft Teams Rooms maintenance and operations - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-operations#to-update-using-powershell)
* Content Source: [Teams/rooms/rooms-operations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-operations.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@tangx007 duplicate

**Comment by scanum** [comment]
@tangx007  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tangx007** [comment]
Thanks to reopen it.

**Comment by scanum** [comment]
@tangx007 Hi @tangx007 we thank you for submitting feedback!
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by BenHagueLucidity** [comment]
This script worked for me, thanks.
