### ISSUE TITLE
Add note on "Manage via PowerShell" script that it enables other plans previously disabled

### ISSUE THREAD

**Issue by BrianTJackett** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4477]
The sample script for disabling Teams for all users has the inadvertent side effect of re-enabling any other plans that were previously disabled since they are not in the new list for -DisabledPlans.  I would recommend adding / expanding a note to call out this point.

For ref: https://docs.microsoft.com/en-us/microsoftteams/user-access#manage-via-powershell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cccdd91a-7f05-abd5-ed94-e82152b86914
* Version Independent ID: 3532d0a8-119c-f7d0-0d4f-a865ad32570f
* Content: [Manage user access to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/user-access)
* Content Source: [Teams/user-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/user-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@BrianTJackett  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@BrianBlanchard Thank you for providing this feedback. Are you saying the note at the top of the paragraph is not enough and would like another note added after the last line of the script?

![image](https://user-images.githubusercontent.com/41186174/79371660-61570380-7f5d-11ea-9d2a-28de3daa87f6.png)

> New-MsolLicenseOptions will enable all services that were previously disabled unless explicitly identified in your customized script

**Comment by BrianTJackett** [comment]
Sorry, I missed the note at the top of Manage via PowerShell section.  For some reason the blue box didn't pop out as a "must read this before continuing on".  Closing issue, thanks.
