### ISSUE TITLE
Hybrid confusion.

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4479]
The documentation is extremely confusing about whether you need to implement a SfB hybrid or not.
Co-existence modes only apply to chat and calls. In every co-existence mode except "Teams Only", chat and calls go to the SfB client. Hybrid implementation is not required for this (see page on [Meetings First](https://docs.microsoft.com/en-us/microsoftteams/meetings-first)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d53d0cb0-90a6-5932-f78e-7de6fcc4d481
* Version Independent ID: 3d468027-cc37-5199-32ec-819bf62b2caa
* Content: [Interoperability between Skype for business and Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability)
* Content Source: [Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Air-Git  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@Air-Git I guess you are refering to this statement, right?

> Interop experiences with an on-premises deployment of Skype for Business require that the on-premises environment is in hybrid mode with Office 365 Skype for Business. For details, see [Migration and interoperability guidance](https://docs.microsoft.com/en-us/MicrosoftTeams/migration-interop-guidance-for-teams-with-skype).

If you go to the [mentioned link](https://docs.microsoft.com/en-us/MicrosoftTeams/migration-interop-guidance-for-teams-with-skype), the hybrid requirement is explained in detail:

> If you have an on-premises deployment of either Skype for Business or Lync, and you want those users to be Teams users, **you must at a minimum ensure that Azure AD Connect is syncing the msRTCSIP-DeploymentLocator attribute into AAD, so that Teams/Skype for Business Online properly detects your on-premises environment**. Furthermore, to move any users to Teams-only mode (i.e., upgrade a user), you must first configure Skype for Business hybrid mode. For more details, see Configure Azure AD Connect for Skype for Business and Teams.

> **Interop between Teams and Skype for Business users is only possible if the Teams user is homed online in Skype for Business. _The recipient Skype for Business user can be homed either on-premises (and requires configuring Skype for Business Hybrid)_** or online. Users who are homed in Skype for Business on-premises can use Teams in Islands mode (defined later in this doc), but they cannot use Teams to interop or federate with other users who are using Skype for Business.

**Comment by Air-Git** [comment]
I think the issue is that you might assume that a hybrid is in some way a requirement to begin to migrate from SfB on-premise to Teams. Only a very close reading of the documents would tell you that this is not the case.
The second sentence of [this page](https://docs.microsoft.com/en-us/SkypeForBusiness/hybrid/plan-hybrid-connectivity?toc=/SkypeForBusiness/sfbhybridtoc/toc.json) is: "Setting up hybrid connectivity is the first step in moving your on-premises environment to the cloud." In fact it is one of the last steps, and only required to maintain interoperability when people move to Teams Only.
In a lot of cases this may not matter. If a business has open federation in SfB, then the step to create a hybrid is very small. If, however, a business has no federation and no external access, then setting up the hybrid is quite a big step. It is not required to implement SfB with Teams Collaboration and Meetings. It is only required later, when users migrate to Teams Only. At least, that's my understanding of it.

**Comment by VLG17** [comment]
@Air-Git I think the confussion comes from not making a distinction between coexistence and interoperability, which are covered in the article you mentioned when oppening this issue, and federation, which is mentioned in other articles, in relation to Skype for Busines and transitioning to Teams.

![image](https://user-images.githubusercontent.com/41186174/79744301-c5d3e300-830e-11ea-9736-8a9c189b3d7b.png)

I think this statement from the [video linked](https://www.youtube.com/watch?v=2eQ6s547fF0&feature=youtu.be) in the article sums it up well:

![image](https://user-images.githubusercontent.com/41186174/79859467-bc637d00-83d9-11ea-9cd6-f76d5a12bf9a.png)

So as you correctly said, hybrid is not a must but it becomes a must if you want Teams users to talk to your onpremises SfB people or you want to migrate from onpremises SfB Server to SfBO/Teams.

To be honest, i don't know what to add to the article to make it better. In my opinion, the article containes all the useful information and links, it's just a matter of going through it all, which i have to admit will involve a lot of hours.

**Comment by Air-Git** [comment]
I agree. If you go through the documents carefully, then you can work out that hybrid is not required until the final step of migrating to Teams Only; and only if you don't just move everyone at once, when again you don't need it.
I'd suggest perhaps amending this statement: "Read this topic to learn how to plan hybrid connectivity between Skype for Business Server and Teams or Skype for Business Online. Setting up hybrid connectivity is the first step in moving your on-premises environment to the cloud." from [this page](https://docs.microsoft.com/en-gb/skypeforbusiness/hybrid/plan-hybrid-connectivity?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json). 
If you read the documents with that assumption, then only a very close reading will indicate it is not accurate.
I am assuming that the majority of organisations will have an edge server and public DNS, in which case setting up the hybrid is trivial. But if you have no SfB internet presence at all, then the overall impression is that you need to create it in order to migrate, which is not really the case.

**Comment by VLG17** [comment]
@Air-Git Thank you for this feedback. We can definitely amend that, but i would have one ask: 

Since [the article](https://docs.microsoft.com/en-us/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability) referenced when you opened this issue is a diferent one, could you please create a new issue for [that specific article](https://docs.microsoft.com/en-gb/skypeforbusiness/hybrid/plan-hybrid-connectivity?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json), which we should amend?

**Comment by Air-Git** [comment]
Done

**Comment by scanum** [comment]
@Air-Git Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
