### ISSUE TITLE
Correction on pin order

### ISSUE THREAD

**Issue by mcantin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4480]
https://docs.microsoft.com/en-us/microsoftteams/teams-app-setup-policies#can-users-change-the-order-of-apps-pinned-through-a-policy

I can reorder any app using drag and drop, regardless of if it's in a app setup policy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f91604a-35b0-dfbb-55b2-b601cb0841b0
* Version Independent ID: 84bcd0d7-b4ed-f13e-c84b-2ec6a7661ae9
* Content: [Manage app setup policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-app-setup-policies#can-users-change-the-order-of-apps-pinned-through-a-policy)
* Content Source: [Teams/teams-app-setup-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-setup-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@mcantin  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@mcantin thank you for pointing this out. I've tested it and indeed on mobile and desktop it works. On web it still doesn't.

**Comment by VLG17** [comment]
@mcantin Actually, i think i spoke too soon. The fact that you can controll the pinning order comes from a parameter which was added a while back:

![image](https://user-images.githubusercontent.com/41186174/79378751-8d2ab700-7f66-11ea-9543-a03b7d5bdbcc.png)

I assume for the tenant where i tested the web client this is set to Off. So i'll change the PR to include web client also.

**Comment by scanum** [comment]
@mcantin Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
