### ISSUE TITLE
Presedence on user pinning

### ISSUE THREAD

**Issue by mcantin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4481]
This documentation doesn't specify what can take precedence if users have personally pinned/unpinned apps before and after a new app setup policy is pushed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f91604a-35b0-dfbb-55b2-b601cb0841b0
* Version Independent ID: 84bcd0d7-b4ed-f13e-c84b-2ec6a7661ae9
* Content: [Manage app setup policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-app-setup-policies#can-users-change-the-order-of-apps-pinned-through-a-policy)
* Content Source: [Teams/teams-app-setup-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-setup-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@mcantin  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@mcantin Although not an official Microsoft doc, i think [this article](https://office365itpros.com/2020/02/04/teams-adds-control-over-user-pinning-of-apps/) describes the behavior quite well.

If the Teams App Setup policy assigned to an account is updated to block user app pinning, Teams removes any apps pinned to the left-hand navigation bar. If the policy is then updated to allow user app pinning, users mist re-pin their pinned apps.

**Comment by mcantin** [comment]
If that's true, it solidifies the expected functionality if documentation is from Microsoft. Please consider incorporating that information here.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by VLG17** [comment]
@mcantin I'll create a request to get that info added.

**Comment by scanum** [comment]
@mcantin Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
