### ISSUE TITLE
eDiscovery Table is incorrect

### ISSUE THREAD

**Issue by EricaToelle** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4482]
Hello, in the eDiscovery table, there are two products listed: in-place eDiscovery and Advanced eDiscovery. There is no product called in-place eDiscovery - I think you mean Core eDiscovery (E3). Both Core and Advanced eDiscovery use in-place eDiscovery, so this is very confusing as it implies Advanced eDiscovery is not in-place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca579d63-182b-d6f5-8777-79248fa27ed9
* Version Independent ID: b4c27d1b-b2f1-41ac-b15c-d12b448a539e
* Content: [Overview of security and compliance - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/security-compliance-overview#ediscovery)
* Content Source: [Teams/security-compliance-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/security-compliance-overview.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@EricaToelle  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@EricaToelle Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
