### ISSUE TITLE
Unclear what "Directory Tasks" mean on Statement 2

### ISSUE THREAD

**Issue by glenrmag** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4483]
"Guest users permissions are limited: This policy determines permissions for guests in your directory. Select Yes to block guests from certain directory tasks, like enumerating users, groups, or other directory resources. Select No to give guests the same access to directory data as regular users in your directory."
Q: What does "enumerating users, groups, or other directory resources." exactly do in Teams?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams guest access checklist - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@glenrmag  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@glenrmag It means that guests (external users) added to Teams will not be able to search/find other users, groups (and implicitely teams) within Teams. They will be limited to the team that you added them to in Teams and everything related to only that team and people involved.

**Comment by scanum** [comment]
@glenrmag Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
