### ISSUE TITLE
Header display is wrong in Japanese

### ISSUE THREAD

**Issue by TakumaNakagame** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4485]
## About
The following header is not displayed correctly.
It also occurred in the secret mode of the browser.

En: `Using the Microsoft Teams admin center`
Ja: `Microsoft teams 管理センターを使用した microsoft teams ロゴを示すアイコン`

![image](https://user-images.githubusercontent.com/5129906/78861972-27739200-7a71-11ea-890d-bd845e08d792.png)

## Envirouments
- Windows10 1909
- Chrome 80.0.3987.163

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b9aa4676-855a-fddb-bb0b-96b7095c695e
* Version Independent ID: 7c39f08c-0d56-6d29-1356-879d9d6ff51c
* Content: [Microsoft Teams でのライブ イベントのセットアップ - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/teams-live-events/set-up-for-teams-live-events#feedback)
* Content Source: [Teams/teams-live-events/set-up-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/set-up-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officeglobal Could you please help with this issue? Thanks.

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by scanum** [comment]
@OfficeGlobal - Any updates on this issue? Thanks!

**Comment by scanum** [comment]
@OfficeGlobal - Any updates on this issue? Thanks!

**Comment by scanum** [comment]
@OfficeGlobal - Any updates on this issue? Thanks!

**Comment by scanum** [comment]
@OfficeGlobal - Any updates on this issue? Thanks!

**Comment by scanum** [comment]
@OfficeGlobal - Any updates on this issue? Thanks!

**Comment by OfficeGlobal** [comment]
@TakumaNakagame , @scanum article was HumanTranslated and published live
