### ISSUE TITLE
Manage external IP mask

### ISSUE THREAD

**Issue by waelschakaki** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4486]
Hello,
in all 3 examples you have used mask 32, and in the article it is stated 
For IPv4, use mask 32. For IPv6, use mask 128
so i am not really sure if it is supported to use different bitmask to add ip range ? or must we use bitmask 32 for IPv4?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad0130c8-4343-ba04-cd55-0c3305a14347
* Version Independent ID: 24db6f00-bfdc-ea9c-6922-e9f09e5cef27
* Content: [Direct Routing Local Media Optimization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-media-optimization-configure#manage-external-trusted-ip-addresses)
* Content Source: [Teams/direct-routing-media-optimization-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-media-optimization-configure.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@waelschakaki thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
