### ISSUE TITLE
日本語誤記の修正依頼

### ISSUE THREAD

**Issue by keijikomatsu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4488]
以下の誤記を修正お願いいたします。日本語トランスレートで誤記が発生しております。
誤記）この度の特別な E1 試用"板"ライセンスをご用意しています。
正) この度の特別な E1 試用版ライセンスをご用意しています。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 779619a7-95a8-c775-0538-4f07abb7067e
* Version Independent ID: cf930116-3d9d-2075-5291-f819cb17a234
* Content: [無料の Office 365 E1 試用版を管理する - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/e1-trial-license#feedback)
* Content Source: [Teams/e1-trial-license.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/e1-trial-license.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officeglobal Could you please help with this issue? thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@keijikomatsu I was not able to find a mentioned error, could you please check the article and share the screen if the typo is still repro? Thank you

**Comment by scanum** [comment]
@keijikomatsu  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by keijikomatsu** [comment]
ja-jp https://docs.microsoft.com/ja-jp/microsoftteams/e1-trial-license

![キャプチャ](https://user-images.githubusercontent.com/29809532/79977630-8d343500-84d9-11ea-84cd-88bd5ea8a394.PNG)

en-us https://docs.microsoft.com/en-us/microsoftteams/e1-trial-license
![en-us](https://user-images.githubusercontent.com/29809532/79978036-3418d100-84da-11ea-9a55-cc6131c2ef5f.PNG)
