### ISSUE TITLE
Update storage section to include private channels

### ISSUE THREAD

**Issue by jordi-j** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4491]
Each private channel has its own separate SharePoint site collection, so the following assumption in the storage section is incorrect: "Each team in Microsoft Teams has a team site in SharePoint Online, and each channel in a team gets a folder within the default team site document library".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#feedback)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@jordi-j  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LolaJacobsen** [comment]
Checking with PM Suparno Chakrabarti

**Comment by scanum** [comment]
@LolaJacobsen Wondering if there is an update on this issue? Thanks!

**Comment by LolaJacobsen** [comment]
If this update is approved by PM Arun Das, the issue will be resolved by merging PR https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/4623. So I'm closing this one.
