### ISSUE TITLE
"Try it" button doesn't launch Teams app or website

### ISSUE THREAD

**Issue by c016smith** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4492]
Error message is...
Skype for Business
Cannot perform the action because the related web page was not available from your Internet browser. If you have not selected a default web browser, please specify one in the Control Panel. Otherwise, if the problem continues, please contact your support team. 
&lt;OK&gt; 

I have enabled the notification policy for this particular user using a new so the notification banner is there, but when I click the Try It button I get that message. I do have a default browser defined (windows 10 fresh machine, running latest Microsoft Edge (chromium edition)). I did swap to IE manually just to see if that fixed it but no luck. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca38b93a-773e-3864-45b6-128dd3163f37
* Version Independent ID: 7c32e933-94f2-196e-1163-3881df3aaf5a
* Content: [Move users from Skype for Business Server 2019 to Teams - Skype for Business Hybrid](https://docs.microsoft.com/en-us/SkypeForBusiness/hybrid/move-users-from-on-premises-to-teams)
* Content Source: [Skype/SfbHybrid/hybrid/move-users-from-on-premises-to-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/move-users-from-on-premises-to-teams.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@c016smith thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
