### ISSUE TITLE
Add a prerequisite - assign Microsoft as the audio conferencing provider

### ISSUE THREAD

**Issue by estiller** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4494]
I followed the steps on this guide; however, it resulted in various issues causing the assigned license not to work. After a lot of troubleshooting with Microsoft support, it turns out that the problem originated from the fact that the affected users had another audio conferencing provider set several years ago. This page should list setting Microsoft as an audio conferencing provider as a prerequisite (https://docs.microsoft.com/en-us/SkypeForBusiness/audio-conferencing-in-office-365/assign-microsoft-as-the-audio-conferencing-provider).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed33488-1a24-f443-dd56-c5327188b5a4
* Version Independent ID: 8da32180-396d-c7a8-6410-472beabff9ce
* Content: [Set up Audio Conferencing for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/set-up-audio-conferencing-in-teams#feedback)
* Content Source: [Teams/set-up-audio-conferencing-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-audio-conferencing-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@estiller  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
Hi @estiller Thank you for raising this issue. I'll be looking into it!

**Comment by scanum** [comment]
@estiller  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
