### ISSUE TITLE
When will Cisco SBCs be Certified for Direct Routing

### ISSUE THREAD

**Issue by uhcel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4496]
Hello Team,
Do you know when Cisco SBCs will finally be certified for Direct Routing with MsTeams?
As per this doc, the certification has started but I'm interested to know when it will be on the list above?

https://techcommunity.microsoft.com/t5/microsoft-teams-blog/microsoft-amp-cisco-partner-to-simplify-meetings-and-calling-for/ba-p/971835

Leszek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1a1c01-10a9-7f69-1c7b-1a566b0f5112
* Version Independent ID: 329ee759-40fc-98fb-b91e-87786c63024b
* Content: [Session Border Controllers certified for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-border-controllers#feedback)
* Content Source: [Teams/direct-routing-border-controllers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-border-controllers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@uhcel thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
