### ISSUE TITLE
How to update the purchase order in auto-recharge scenarios for EA customers?

### ISSUE THREAD

**Issue by olamer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4497]
The documentation says for EA customers, "you will also be given an opportunity to specify a purchase order number to associate with the enterprise agreement number (if applicable)". But in scenario where there is "auto-recharge" enabled and over years the specified purchase order is no more valid, it seems it cannot be updated. What is the process in that case to ensure it can be invoiced on correct new purchase order? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 277cf140-5c6c-82c7-cc56-490ef2188754
* Version Independent ID: 72e7de29-fd71-23bf-15a7-172634c2a5fd
* Content: [Set up Communications Credits for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-communications-credits-for-your-organization)
* Content Source: [Teams/set-up-communications-credits-for-your-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-communications-credits-for-your-organization.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@olamer thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
