### ISSUE TITLE
Set-CsOnlineVoiceApplicationInstance: command not found

### ISSUE THREAD

**Issue by krisztian-andre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4498]
I am connected to Teams and can execute get-team, but 

PS C:\WINDOWS\system32&gt; Set-CsOnlineVoiceApplicationInstance
Set-CsOnlineVoiceApplicationInstance : The term 'Set-CsOnlineVoiceApplicationInstance' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Set-CsOnlineVoiceApplicationInstance
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-CsOnlineVoiceApplicationInstance:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts?source=docs)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by krisztian-andre** [comment]
You can mark this as closed now. The cause was that voice functions are still in the Skype module not in the Teams module.

To configure a call queue you need to:

1. Create a Resource Account of Call Queue type
2. Create a service number
3. Purchase a Phone System - Virtual User license in Purchase service ->bottom of the page -> addons
4. Assign the license to the Resource Account 
5. Set the location of the service account in Active Users -> Licenses and apps  to the same country as the service number
6. Assign Phone System licenses to the users of the agents
7. Create a call queue and add the agents to it
8. Associate the call queue and associate it with the resource account
9. Assign the number to the resource account
10. If you don't want to assign calling plans to the agents then enable enterprise voice for them
11. Connect to the Skype for Business Online shell:
12. $sfbSession = New-CsOnlineSession 
13. Import-PSSession $sfbSession
14. Set-CsUser -identity "username@contoso.com" -EnterpriseVoiceEnabled $true
15. remove-PSSession $sfbSession

Br,
Kris

**Comment by scanum** [comment]
@krisztian-andre thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
