### ISSUE TITLE
What about a bot? Is it possible to make the bot built-in?

### ISSUE THREAD

**Issue by Dmitresky** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4499]
Is it possible to create a bot that is a member of each chat inside of the tenant? Group chat or private, it doesn't matter. I need a possibility to type to the bot from any channel and bot should answer me on that channel. What is more, I shouldn't install the bot myself. It should be built-in or should be added automatically when a channel is created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d33f55c-db55-923e-544f-fccb97f3c7a3
* Version Independent ID: 9cb02e00-311e-ec7d-c422-ae1cb9e6d31e
* Content: [Use built-in and custom tabs in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/built-in-custom-tabs)
* Content Source: [Teams/built-in-custom-tabs.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/built-in-custom-tabs.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Dmitresky thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
