### ISSUE TITLE
172.16.x.x as sample for a public IP is misleading 

### ISSUE THREAD

**Issue by FrankCarius** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4503]
You should not use private ip addresses in samples like

New-CsTenantTrustedIPAddress -IPAddress 172.16.240.110 -MaskBits 32 -Description "Vietnam site trusted IP"
New-CsTenantTrustedIPAddress -IPAddress 172.16.240.120 -MaskBits 32 -Description "Indonesia site trusted IP"
New-CsTenantTrustedIPAddress -IPAddress 172.16.240.130 -MaskBits 32 -Description "Singapore site trusted IP"

You should use "sample IPs", which tell the readers about the public IPs
You should choose some from 203.0.113.0/24 (TEST-NET-3)  (RFC 5737 https://tools.ietf.org/html/rfc5737)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad0130c8-4343-ba04-cd55-0c3305a14347
* Version Independent ID: 24db6f00-bfdc-ea9c-6922-e9f09e5cef27
* Content: [Direct Routing Local Media Optimization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-media-optimization-configure)
* Content Source: [Teams/direct-routing-media-optimization-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-media-optimization-configure.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@ Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@FrankCarius Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by carvalhorui** [comment]
Hello @scanum. I understand the issue hasn't been resolved yet because the configuration examples keep using private IPs (172.16.0.0/12) as public IPs and this can create a confusion during the configuration. If you refer to public IPs when configuring Trusted IPs, you shouldn't use private ones! I would say that here but I've found this post explaining the same thing. It may not be clear to many users.

**Comment by CarolynRowe** [comment]
We will be updating the IP addresses.
