### ISSUE TITLE
Issue of "User Profile Photos" is resolved now

### ISSUE THREAD

**Issue by mitanabe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4506]
In the following UserVoice, it was announced that the issue of "User Profile Photos" was resolved.
Uploading user profile photo can be controlled with OWA Mailbox Policy setting now.

https://microsoftteams.uservoice.com/forums/555103-public/suggestions/18600505-disable-user-ability-to-change-profile-photos

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues#feedback)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@mitanabe thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by mitanabe** [comment]
Hi Manuela

Thank you for your response. Excuse me for contacting you after the ticket
was closed.

I don't mean I have problem in my tenant.

There was a design change related to changing user profile picture within
teams.
As MS dev team mentioned in User Voice, we can control the user operation
of changing picture within teams with OWA mailbox policy setting
"-SetPhotoEnabled" now.

This design change was not announced in M365 roadmap or Message Center.
Therefore I requested that it would be better to announce that the issue
was resolved in this docs page.

Mitsuhiro Tanabe

**Comment by mitanabe** [comment]
This design change was reflected in the following page.

How Exchange and Microsoft Teams interact
https://docs.microsoft.com/en-us/MicrosoftTeams/exchange-teams-interact

******
8 Teams honors the Outlook on the web mailbox policy setting that's configured by tenant admins to control whether users can change their profile picture. If the -SetPhotoEnabled setting is turned off in the policy, users can't add, change, or remove their profile picture. For example, if a user uploads a profile picture that's approved by your organization's IT or HR department, no action is needed. However, if a user uploads a picture that's inappropriate, change the picture according to your organization's internal policies.
