### ISSUE TITLE
Typos in blue 'important' box under "Configure user experiences using policies"

### ISSUE THREAD

**Issue by lsmorgan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4507]
1) "Automatically admin people" should be "Automatically admit people"
2) ."...non-authenticated users are must..." should just be "must"
3) For EDU, the student scenario should also be addressed here, not just non-authenticated users

Current text: For meeting policies assigned to any users, we recommend setting the "Automatically admin people" setting to "Everyone in your organization". This setting will ensure that non-authenticated users are must be admitted from the lobby before they can join Teams meetings. For more information,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 700c34b6-87de-19e2-9821-bc35e290948e
* Version Independent ID: 86be2050-e149-7f03-d2a8-d64f6f912012
* Content: [Microsoft Teams resources for Education admins - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/remote-learning-edu#feedback)
* Content Source: [Teams/remote-learning-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/remote-learning-edu.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by MicrosoftHeidi** [comment]
I've updated this.
