### ISSUE TITLE
Guest User Teams Licences...

### ISSUE THREAD

**Issue by arsham84** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4509]
I need to invite about 30 people to my team as guests. Do I need to buy licences for them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [What the guest experience is like - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/guest-experience#feedback)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@arsham84 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
