### ISSUE TITLE
link is not working for he Netherlands (non-geographic numbers)

### ISSUE THREAD

**Issue by BTaino** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4510]
this link is not working for the Netherlands (non-geographic numbers) 
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/downloads/LOA-forms/letter-of-authorization-(loa)-for-the-netherlands-(non-geographic-numbers)-(v.2.0)-(nl-nl).pdf?raw=true

Is there another way to get it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4540703e-0e4b-a0a8-7075-fcc540e59eda
* Version Independent ID: a2acdd04-15ad-58db-0b9c-25dd52721adf
* Content: [Phone number management for the Netherlands - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization/phone-number-management-for-the-netherlands)
* Content Source: [Teams/manage-phone-numbers-for-your-organization/phone-number-management-for-the-netherlands.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-phone-numbers-for-your-organization/phone-number-management-for-the-netherlands.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@BTaino Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@BTaino Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
