### ISSUE TITLE
Dial pad

### ISSUE THREAD

**Issue by giterdn** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4511]
This article should describe what to do if the number you call, to add a participant, requires you to open the dial pad to navigate through an IVR menu in order to get to the individual’s line. I find that once I’ve entered the 10-digit phone number and am connected to the IVR the dial pad is available to me but pressing and of the dial pad buttons does nothing and I don’t understand why

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cf7bbd2-ebf4-48e6-c157-8035f976259e
* Version Independent ID: a6897ddf-473b-0109-9f4e-72c59981b631
* Content: [Dialing out from a meeting so other people can join - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/dialing-out-from-a-teams-meeting-so-other-people-can-join-it#feedback)
* Content Source: [Teams/dialing-out-from-a-teams-meeting-so-other-people-can-join-it.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/dialing-out-from-a-teams-meeting-so-other-people-can-join-it.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@giterdn Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @giterdn, thank you for your feedback.

I cannot test it. Could you please share some screenshot to understand the behaviour you are experiencing? I'll appreciate that.

**Comment by giterdn** [comment]
Sure, here are some screenshots

Here you can see I'm in a meeting with someone and now I want to add Microsoft Store support by phone
![image](https://user-images.githubusercontent.com/21087549/81338351-588bb600-9061-11ea-99b7-3a1fb765e04d.png)

Here you can see the call is being connected
![image](https://user-images.githubusercontent.com/21087549/81338405-70633a00-9061-11ea-9902-0ee66100c15f.png)

Here you can see the call is connected and the Microsoft Store is asking me to choose from options on my phone, so I am opening the PIN pad from ... menu
![image](https://user-images.githubusercontent.com/21087549/81338476-8c66db80-9061-11ea-8a3e-cb0e92a57477.png)

Here you can see the PIN pad is open, but no matter what buttons I press the auto-attendant on the phone keeps saying "I didn't get your response, please try again"
![image](https://user-images.githubusercontent.com/21087549/81338544-ab656d80-9061-11ea-9585-46b70d6d585c.png)

I also have a recording of this meeting.  However I am unable to attach it here.  If you could hear the video, at 1:27 you'll hear a prompt asking if I am ok with the call being recorded.  I respond 1 for yes but it is not registered so I'm told the call will not be recorded.  At 1:44 I'm asked for what I want to do with multiple options and I choose 1, but at 2:00 I am told my response was not heard.  I end the call and meeting shortly after that.

**Comment by giterdn** [comment]
Seems to me this is a bug or it by design, and if by design your article could mention that the PIN pad is currently only for entering a phone number to dial, or for entering a passcode to join a secure meeting, but not for interacting with IVRs that you've connected via phone.

**Comment by dariomws** [comment]
Thank you so much @giterdn! Now I understand it, very helpful screenshots.

I will try to confirm if it´s supported. In the meantime, could you please open a support ticket so we can try to get this information from two different channels?
If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products

@tonysmit could you kindly help to confirm if it´s supported? Thanks!

**Comment by tonysmit** [comment]
@fafan - can you assist here please?

**Comment by fafan** [comment]
Hi @tonysmit, this is most likely a DTMF issue. You probably need to file a ticket to get help from Service Desk.

**Comment by tonysmit** [comment]
@giterdn - I'm checking with the client PMs on this. Did you open a support ticket? Thanks, Tony

**Comment by giterdn** [comment]
Hi - I did open a ticket and was told this is a known bug that is under development with no ETA

**Comment by tonysmit** [comment]
@giterdn - Great! According to the PM there are two bugs against this that hopefully will be fixed in the next month or so. Thanks for calling this to our attention. Would you mind just editing the doc in GH and I will see it and Merge. Thanks! Tony
