### ISSUE TITLE
[LOC]Back-Translation "ごみ箱"→"Yealink"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4514]
ja-jp:https://docs.microsoft.com/ja-jp/MicrosoftTeams/rooms/requirements
![requirements_j](https://user-images.githubusercontent.com/40815708/79061967-b9c5a100-7cd0-11ea-8f0b-0ef4f7daa62d.png)

en-us:https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/requirements
![requirements_e](https://user-images.githubusercontent.com/40815708/79061970-c0541880-7cd0-11ea-8d84-d3f9783a4734.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5bf01435-a73b-4bf2-5845-e4cf50c4c3a2
* Version Independent ID: 166e1800-80b1-2496-7160-3040c5b23c3d
* Content: [Microsoft Teams の会議室の要件 - Microsoft Teams](https://docs.microsoft.com/ja-jp/MicrosoftTeams/rooms/requirements)
* Content Source: [Teams/rooms/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/requirements.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officeglobal Could you please help on this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by hyoshioka0128** [comment]
related #4540

**Comment by OfficeGlobal** [comment]
Yealink fixed at live page
#4540 is being fixed

**Comment by scanum** [comment]
@0loeiz0 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
