### ISSUE TITLE
Instructions to enable Teams en Microsoft 365 admin center are incorrect, also incorrect for Teams admin

### ISSUE THREAD

**Issue by EliasKaplan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4515]
The new experience in Admin Center is quite different, 
Need to
1) Expand
2) Settings
3) Setting again (Not  in Add-Ins?)

Experience is very very hard for users

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5473bf0-ba2d-6c42-d57d-b61af64452d3
* Version Independent ID: 7195478d-3ef4-be8c-2920-3fdba3e70c7e
* Content: [Turn on Teams in your Office 365 organization - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/office-365-set-up#feedback)
* Content Source: [Teams/Office-365-set-up.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-set-up.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by EliasKaplan** [comment]
In teams admin center there is no way to turn on Teams for all users, there is no "services and add-ins", mixed with instyructions fro M365

**Comment by scanum** [comment]
@EliasKaplan thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
