### ISSUE TITLE
Cannot use Planner with Private Channel

### ISSUE THREAD

**Issue by seanyb88** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4516]
Re-posting this question as it seems no official response from Microsoft on an ETA.

It has been over 9months since Private Channel functionality was brought in, but still no Support for Planner.

On MS Teams UserVoice, there is over 1600 Votes for this feature and nearly 300 Comments, yet still no official acceptance by Microsoft if this is currently being worked on and any potential ETA.

https://microsoftteams.uservoice.com/forums/555103-public/suggestions/38063230-create-planner-tabs-within-private-channels?page=1&per_page=20

Please help to introduce this functionality ASAP, as it is really holding back the Collaboration/Planning aspect of Sub Teams within larger Teams/Orgs.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels#feedback)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@seanyb88 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by simonjpearson** [comment]
This is also a problem for me.  I am considering using Trello now instead, which does support private channels (subject to investigation). This ultimately will cost more money, but might be my only option.
