### ISSUE TITLE
Licensing for Guest presenters in a live event

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4518]
Please add information regarding Guest presenter capabilities and licensing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events#teams-live-events-and-skype-meeting-broadcast)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by GASPowered** [comment]
I also need this information on this. We experienced login issues with our guest presenters. They described a "login loop" on their end.

**Comment by GASPowered** [comment]
I found a workaround. I created a Team just to invite the guest presenters. Once they connected to the Team, their guest accounts were added to our tenant. They were then able to join the Live Event as presenters.

I would love to see the recommended procedure for ensuring that guest presenters are able to join Live Events without this step.

**Comment by scanum** [comment]
@teomonda Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by pepecheyenne** [comment]
I also found that, at this moment, the only client allowing Guest presenters is Teams over Windows. Teams in MacOS and iOS doesn't work for this, and any web browser (tested Edge based in Chromium, Chrome, Firefox & Safari) works either.

**Comment by SerdarSoysal** [comment]
Thanks everybody for your feedback on this. @GASPowered your workaround is actually pretty cool. I just tested this with another customer and it worked very well. It also allows the guest presenters to collaborate leading up to and after the event. 

@pepecheyenne currently you need to use desktop Teams app to present or produce a live event. Web browser and mobile apps currently only work for attendees. This is called out in the system requirements section of this article: https://support.office.com/en-us/article/get-started-with-microsoft-teams-live-events-d077fec2-a058-483e-9ab5-1494afda578a#bkmk_systemreq

**Comment by teomonda** [comment]
Any ideas on Guest presenter licensing?

**Comment by scanum** [comment]
@teomonda Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by teomonda** [comment]
Hello Manuela, I am afraid the article is still unclear on the licensing for Guest presenters.
We say:
"It's important to know that an Office 365 license is required to participate in a live event as an authenticated user, but this requirement depends on the production method used:
For events produced in Teams The user must be assigned a Teams license.

[...]

Important
Non-authenticated anonymous users can't be invited as producers or presenters in Teams live events."

I would deduct from here that a licenses should be required for this guest however this might be counter-intuitive for a Guest that will only participate in an event in 1 day.
Not to mention of course that as per my tests it is working without any issue even not having a license, however that may not be very relevant from the compliance perspective :).

Also the article looks to be updated in August when we did not even have the possibility to add Guest users as presenters.

Do not hesitate to reach out to me in case you might need additional clarifications from my end.

**Comment by Kazzan** [comment]
Agree. This issue around content clarification need to be solved. Current wording does not describe it correctly.
