### ISSUE TITLE
¿es 4, 5 ó 4.5? (is it 4, 5 or 4.5?)

### ISSUE THREAD

**Issue by j0rt3g4** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4521]
Cantidad máxima de eventos simultáneos en vivo por cada inquilino de Office 365 4,5
Maximum live event in parallel with O365, is it 4, 5 or 4,5 ?

How do we get this limit if it's 4 or 5, and in case that is required, how can this be increased?
(since it has been increased the demand of Ms Teams worldwide with the Coronavirus).

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan para eventos en directo en Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/es-es/microsoftteams/teams-live-events/plan-for-teams-live-events#feedback)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@j0rt3g4 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Hello @scanum 
I think it was already cleared part of the issue
https://www.microsoft.com/en-us/microsoft-365/roadmap?featureid=63341

Now what is missing is if it's 4, 5 (or 4.5?) and how would you determine this?

**Comment by VLG17** [comment]
@j0rt3g4 Just to confirm, are you interested in details about simultaneous live events hosted across a tenant or simultaneous videos within a live event?

The roadmap item you shared above talks about simultaneous videos within a teams meeting/live event. It was raised from 4 to 9 (a 3x3 screen). The user experience is described [here](https://support.office.com/en-us/article/using-video-in-microsoft-teams-3647fc29-7b92-4c26-8c2d-8a596904cdae?ui=en-US&rs=en-US&ad=US).

The limit of concurrent live events has been temporarely raised to 50, as described [here](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events#feedback):

![image](https://user-images.githubusercontent.com/41186174/83493735-dfe01400-a4bd-11ea-83e3-1200d2c084af.png)

**Comment by j0rt3g4** [comment]
Simultaneous events across tenant.
50 it's a good number.
Thank you.

Previously it was 4,5 so I didn't quite understand if it was 4 or 5 .
I'd go ahead and close this one .. thank you  both
