### ISSUE TITLE
Teams Roadmap link doesn't filter.

### ISSUE THREAD

**Issue by ronaldborman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4523]
The 'Teams Roadmap' link calls the Microsoft 365 Roadmap page, but the value of the query string parameter 'filters' is empty so no filtering is applied. When you manually append the value in the browser address bar, filtering is happening. BTW the 'searchterms' parameter is omitted completely, but is not necessary IMHO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e1b8fbb-3047-dd3a-6a9c-ae6b1d5a0222
* Version Independent ID: 42c418d1-8473-2243-81bc-558e0a0688aa
* Content: [Welcome to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-overview)
* Content Source: [Teams/Teams-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@ronaldborman Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@ronaldborman Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
