### ISSUE TITLE
Link to "Office 365 License Reporting and Management Tool -Assign Remove Licenses in Bulk" is not working any more.

### ISSUE THREAD

**Issue by almacho** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4524]
Refers to https://gallery.technet.microsoft.com/Office365-License-cfd9489c which is not available any more. Couldn't find the "new" target.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cccdd91a-7f05-abd5-ed94-e82152b86914
* Version Independent ID: 3532d0a8-119c-f7d0-0d4f-a865ad32570f
* Content: [Manage user access to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/user-access#feedback)
* Content Source: [Teams/user-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/user-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@almacho Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @almacho, thank you for your feedback.

This tool/script is not available anymore. You can use the Admin Center to manage license in bulk now.

**Comment by LolaJacobsen** [comment]
I merged the article update. Thanks!
