### ISSUE TITLE
Meet Now

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4528]
There are two ways to arrange a Teams meeting: Meet Now, and New Meeting. 
Is the Meet Now part of the Meetings functionality available in Meetings First mode, or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12d73609-83a4-cdd4-8461-59fc1a9152fc
* Version Independent ID: b72ffa6e-f060-c296-e42d-eb3815a932ea
* Content: [Meeting First - Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meetings-first)
* Content Source: [Teams/meetings-first.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meetings-first.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Air-Git 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
