### ISSUE TITLE
Need setting to disable start on login by default

### ISSUE THREAD

**Issue by absentspace** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#453]
I need to distribute this throughout my enterprise (4,000 clients), but I must disable start on login. How can I do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b13006b-d1de-8bc7-e0c6-b7022af0e731
* Version Independent ID: d29dae65-bb28-8767-cfd7-07d2ed5fd460
* Content: [Install Microsoft Teams using MSI](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @ninadara
* Microsoft Alias: **ninadara**

**Comment by kenwith** [comment]
@absentspace - 4000 clients is a really large workload and I want to make sure this is taken care of ASAP and properly.  Would you please open a service ticket, instructions here: https://www.youtube.com/watch?v=puuOy0sEg1Y  This will make sure this is escalated right away.

It would be great to get the knowledge learned on this back into the documents. Thank you for taking time to provide feedback and I will look to get resolution from support back into docs.

**Comment by AndreaBarr** [comment]
@ravioli1720 Thank you for this feedback. 

As Ken instructed above we think it's best to get this over to Support so it is addressed quickly and to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
