### ISSUE TITLE
Restore "Global" application Policy for the whole Group Members.

### ISSUE THREAD

**Issue by Bernard-Vesy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4531]
Hello, I have execute the following command successfully   : 

Grant-CsTeamsAppPermissionPolicy -Global -PolicyName "LEMO - Standard" 

But Now i will come back to the standard and it's does't work 

Grant-CsTeamsAppPermissionPolicy -Global -PolicyName "Global"

Any idears ? 

Thanks in advance.
Bernard Vésy

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 6f91604a-35b0-dfbb-55b2-b601cb0841b0
* Version Independent ID: 84bcd0d7-b4ed-f13e-c84b-2ec6a7661ae9
* Content: [Gérer les stratégies de mise en application dans Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/fr-fr/MicrosoftTeams/teams-app-setup-policies#feedback)
* Content Source: [Teams/teams-app-setup-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-setup-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Bernard-Vesy 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
