### ISSUE TITLE
Supported Cameras

### ISSUE THREAD

**Issue by randyhchapman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4532]
Hi.  The supported cameras section links back to the main page with all supported cameras for MTR.  There isn't a specific list of supported content cameras on the list.  However, I know that there are currently only 3 certified cameras that support content camera.  The Huddly IQ, Logitech C930e and Brio on specific firmware.

When I saw that the page had been updated to point at the full list I got excited and tried a ConferenceCam Connect with the latest firmware and it displayed the error that it was not a certified device. 

Can you update the page please to make it more clear which devices are specifically certified for content camera?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b06af4b9-8034-c287-b30c-ca009b8549c1
* Version Independent ID: bf2e1bd9-9b86-68a9-42dd-89001bedf0cd
* Content: [Learn how to setup content cameras - Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/content-camera#feedback)
* Content Source: [Teams/rooms/content-camera.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/content-camera.md)
* Service: **msteams**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@randyhchapman Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @randyhchapman, thank you for your feedback.

If I go to the link in the article I can see what cameras support content camera use:
![image](https://user-images.githubusercontent.com/33589238/79915078-b29f4100-83fc-11ea-8c12-9ca9ce4c971a.png)

Maybe I don't understand you. Please, let me know. Thanks!

**Comment by randyhchapman** [comment]
Okay. I now see the ticks in the content camera support column. Thanks
