### ISSUE TITLE
invite select people in private channel

### ISSUE THREAD

**Issue by reharta** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4533]
Hi, I would like to be able to invite a subgroup of people only from a team into a private channel. I this functionality in the works?

**Comment by scanum** [comment]
@reharta 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
