### ISSUE TITLE
Running MTR as a standalone system

### ISSUE THREAD

**Issue by kjanaprik** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4536]
Hello,

Is it possible to run an MTR system on a All-in-One system without a dock or control panel?
I would just like to use the built-in touchscreen or a mouse and keyboard.

**Comment by scanum** [comment]
@kjanaprik 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
