### ISSUE TITLE
Images broken

### ISSUE THREAD

**Issue by MySkypeLab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4538]
There are a couple of images in this document that appear to be broken. They are being displayed as:

![Screenshot showing the Add a domain page](media/direct-routing-2-sbc-add-domain.png)
![Screenshot showing domains with status of Setup complete](media/direct-routing-14-sbc-setup-complete.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure Session Border Controller - Multiple tenants - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@MySkypeLab Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@MySkypeLab Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
