### ISSUE TITLE
[LOC]Back-Translation "Logitech タップ"→"Logitech Tap"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4540]
ja-jp:https://docs.microsoft.com/ja-jp/MicrosoftTeams/rooms/requirements

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5bf01435-a73b-4bf2-5845-e4cf50c4c3a2
* Version Independent ID: 166e1800-80b1-2496-7160-3040c5b23c3d
* Content: [Microsoft Teams の会議室の要件 - Microsoft Teams](https://docs.microsoft.com/ja-jp/MicrosoftTeams/rooms/requirements)
* Content Source: [Teams/rooms/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/requirements.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officeglobal Could you please help with this issue? Thanks!

**Comment by scanum** [comment]
@OfficeGlobal Wondering if you are able to help with this issue? Thanks!

**Comment by hyoshioka0128** [comment]
reference:
[Logicool Tap](https://www.logicool.co.jp/ja-jp/product/tap)
 Logicool(ロジクール) is Logitech International's Japanese subsidiary.

[Logitech Tap](https://www.logitech.com/en-us/product/microsoft-rooms)

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by scanum** [comment]
@OfficeGlobal Any update here? Thanks!

**Comment by scanum** [comment]
@OfficeGlobal Any update here? Thanks!

**Comment by scanum** [comment]
@OfficeGlobal Can you please help with this? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix. (ETA 8/10/2020)

**Comment by scanum** [comment]
@officeglobal Any updates on this issue?

**Comment by hyoshioka0128** [comment]
Ref:
[Microsoft Teams Rooms用 Logicool Tap - Logitech](https://www.logitech.com/assets/65652/22/tap-datasheet.pdf)

**Comment by OfficeGlobal** [comment]
@scanum MT engine reprocessed the file with wrong translation. I'm on update and re-HandBack

**Comment by OfficeGlobal** [comment]
@scanum , @hyoshioka0128 the translation for "Logitech" was reverted to ENG and published live

**Comment by hyoshioka0128** [comment]
@scanum  @OfficeGlobal  - "Logitech Tap" has been Fixed.
Closed #4540.
