### ISSUE TITLE
SipSignalingPort cannot be 0

### ISSUE THREAD

**Issue by davemidd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4541]
According to this page, SipSignalingPort can be "0 to 65535".
If I try and enter the value 0, I get the error:
"SipSignalingPort must be greater than or equal to 1."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad7d5051-1177-c5cf-bf28-8639d7b6fbd1
* Version Independent ID: 2a9aa4e1-3767-cd46-50fe-f9dd8b0997be
* Content: [Connect your Session Border Controller (SBC) to Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-connect-the-sbc#feedback)
* Content Source: [Teams/direct-routing-connect-the-sbc.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-connect-the-sbc.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by Zairians** [comment]
Hey Dave, it means the port needs to be between 0 to 65535. Standard practice is 5067 or 5061, but really as long as it matches what port the SBC is using to communicate with Teams it shouldn't cause any issues.

**Comment by davemidd** [comment]
Thanks for the quick response, Zairians.
I wasn't very clear.
The documentation says that the port can be any value between 0 and 65535.
if I try and set the value to to 0 ( a valid number according to the documentation) powershell gives the error I mentioned.  So either the documentation is incorrect or there's a technical issue with configuring the gateway.  I'm not sure which one of the two it is.

There is another point here, which is why I'm trying to set the port to 0.  I don't want to hard configure Teams to use a specific port, but instead use the port that is in the DNS SRV records for the FQDN that's been configured. (This gives is the flexibility of changing the port without having to reconfigure the Teams gateway).  Typically (with many SIP devices) this is achieved by setting the port to 0.  Please could you advise that if this can't be achieved by setting the gateway port to 0, how do we configure the gateway to use DNS SRV records.

Thanks again,
David

**Comment by Zairians** [comment]
Hey David,

I think the documentation is a bit misleading. The SipSignalingPort as far as I'm aware needs to be static as it sits idle and listening for inbound traffic, this is why its common for SIP to use 5060 (or 5061 for SIPS). It seems Teams/SFB are using 5067/5061 for TLS communication.

The only static port you would be using is for the SIP signalling. During the SIP signalling the call would negotiate the RTP ports to use for voice. The RTP port range which is dynamic as the media pool will usually have a range (0-65535) and the call will select a port from this range to use. 

To my knowledge you can't change the SIP signalling port as any SIP Trunk/SBC would be looking to communicate on the configured port when they've been configured.

SIP Devices may have their port set to 0 although once they are configured to a platform/PBX the configuration will most likely contain the SBC address and port so the device knows where to route outbound traffic. 

Hope this helps.

Thanks,
Adam

**Comment by scanum** [comment]
@davemidd 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by davemidd** [comment]
Thanks. I've checked the documentation on this page:
https://docs.microsoft.com/en-us/microsoftteams/direct-routing-connect-the-sbc
and it's still incorrect. Will it take a while for the corrected version to show up?

![image](https://user-images.githubusercontent.com/1181083/79442775-e4657180-7fd0-11ea-96c0-b0ec487f7f9b.png)

David
