### ISSUE TITLE
Incorrect link text on the French version of this article "Permettez à votre petite entreprise d’utiliser des à distance"

### ISSUE THREAD

**Issue by virginij** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4542]
The link text "Permettez à votre petite entreprise d’utiliser des à distance" is incorrect, there is a word missing after "des". Globally, the wording is not correct, the best is to use the title of the linked article which is, in French "Dynamisez votre petite entreprise avec le télétravail"
Thanks

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 3cdf3243-40dc-708c-cefc-8be68491a3be
* Version Independent ID: 0fc81593-de9a-c453-4a1c-ec1ebbfe2ecf
* Content: [Prise en charge des travailleurs à distance avec Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/fr-fr/MicrosoftTeams/support-remote-work-with-teams?source=docs#feedback)
* Content Source: [Teams/support-remote-work-with-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/support-remote-work-with-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officeglobal Could you please help with this issue? Thanks!

**Comment by scanum** [comment]
@OfficeGlobal Could you please help with this issue? Thanks!

**Comment by scanum** [comment]
@OfficeGlobal Could you please help with this issue? Thanks!

**Comment by virginij** [comment]
What do you mean ? Tell me if my initial request is not clear ?

**Comment by scanum** [comment]
> What do you mean ? Tell me if my initial request is not clear ?

Your request is clear - I am referencing this issue to someone that can help. Thanks.

**Comment by OfficeGlobal** [comment]
@virginij the link text was updated at live page. Thank you

**Comment by scanum** [comment]
@virginij  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
