### ISSUE TITLE
URL for non English versions is giving a 404

### ISSUE THREAD

**Issue by virginij** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4543]
In a non English version of this article, the link to https://www.microsoft.com/microsoft-365/blog/2020/03/12/top-9-ways-microsoft-it-enabling-remote-work-employees/ (link text = "Les 9 principaux moyens que Microsoft IT utilise pour activer le travail à distance de ses employés" in the French article) is giving a 404 :-(.
The language ID en-us should be added in the URL to point explicitely to : https://www.microsoft.com/en-us/microsoft-365/blog/2020/03/12/top-9-ways-microsoft-it-enabling-remote-work-employees/.
If you don't do this, for French customers for instance, the URL will be interpreted as :
https://www.microsoft.com/fr-fr/microsoft-365/blog/2020/03/12/top-9-ways-microsoft-it-enabling-remote-work-employees/ ... (see the FR-FR added automatically) which doesn't exist.
Thanks

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 3cdf3243-40dc-708c-cefc-8be68491a3be
* Version Independent ID: 0fc81593-de9a-c453-4a1c-ec1ebbfe2ecf
* Content: [Prise en charge des travailleurs à distance avec Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/fr-fr/MicrosoftTeams/support-remote-work-with-teams?source=docs#feedback)
* Content Source: [Teams/support-remote-work-with-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/support-remote-work-with-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@virginij Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@virginij Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by virginij** [comment]
the issue is exactly the same. Are you sure that the one who processed it understood what I meant ? Perhaps he has an English settings and doesn't understand what I mean. If this is the case can you please ask him to contact me instead of closing the issue without doing any fix ?
Thanks

**Comment by virginij** [comment]
I don't see how to reopen it. I see it merged with another issue not closed, so please keep it opened and once the issue is fixed, send me again the automatic email to mention "closed please check".
Thanks
