### ISSUE TITLE
Message Type Clarificiation

### ISSUE THREAD

**Issue by KazuyDarklight** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4545]
There is a lack of clarity regarding the difference between a channel message and a post message.  At first I thought perhaps channel messages was a combined count of post and reply, but that does not add up when looking at the totals shown in my environment. (If it IS a combined count and there is just an issue with my reporting, I think that should be clarified since so many other metrics are stand alone and since there would then obvious be an opportunity for the numbers not to add up, leading to confusion.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2758a3d6-c646-dcb0-2a31-c7b9b84e780b
* Version Independent ID: 8704c9fe-f8b0-82d2-bd83-3fd1a9ad638d
* Content: [Microsoft Teams user activity report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report#feedback)
* Content Source: [Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@KazuyDarklight Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Stocktradingview** [comment]
**Real traders best chatroom since 2017, It’s turned $1.1M in the last 5 Months, Join with 7k+ active traders & Improve your trading performance. Join our trading chatroom today [https://discord.gg/sC3sw4s](https://discord.gg/sC3sw4s)**

![www](https://user-images.githubusercontent.com/63863580/79582986-246c4780-80ea-11ea-9334-5f9fed41a578.JPG)

**Comment by boxdoy94** [comment]
Is there already an explanation about this question? 
we have the same one.

**Comment by dariomws** [comment]
Hi @KazuyDarklight, thank you for your feedback.

I experienced the same behaviour:
![image](https://user-images.githubusercontent.com/33589238/80119200-c3b49300-855f-11ea-8532-865fc6e03384.png)

@LanaChin Could you kindly help us to find an explanation for this? Thanks!

**Comment by scanum** [comment]
@LanaChin Hi Lana could you please help on this issue?

**Comment by LanaChin** [comment]
Looking into this

**Comment by scanum** [comment]
@LanaChin Wondering if there is an update here? Thanks!

**Comment by nullablr** [comment]
Btw: What exactly means if the Display Name shows as - -?

**Comment by boxdoy94** [comment]
> Btw: What exactly means if the Display Name shows as - -?

It's an user that's removed from ur tenant

**Comment by nullablr** [comment]
Thanks boyday94. But (at least from the view I have on different tenants) there are too many such entries for small time periods (e.g. 30 days), that I believe, that this is the only reason. How do you think about?

For example, I have here my Dev-Tenant with Contoso installed. Never changed User Accounts but still see, the most active user is the "--". For this case, it could be, that the activities were triggered via Microsoft Graph API.

![image](https://user-images.githubusercontent.com/65314088/81904551-b705e680-95c3-11ea-8a8f-957d916bfd33.png)

**Comment by LanaChin** [comment]
I've pinged the PM for guidance on channel/reply/post messages.

**Comment by quentinhurdazure** [comment]
@LanaChin  @KazuyDarklight Channel messages does include post and reply message types.  In the definition of Post messages it qualifies as "unique **post** messages", whereas, the Channel Message definition says only "unique messages" and this **_implies it includes all of the messages_**, both **the posts** and also **the replies**.  Similarly, for Reply Messages, it is qualified as "unique reply messages". 

As per definition
•	**Channel messages** is the number of 

> unique messages

 that the user posted in a team chat during the specified time period.

•	**Reply messages** is the number of 

> unique **reply** messages

 that the user posted in a team channel during the specified time period.

•	**Post messages** is the number of 

> unique **post** messages

 that the user posted in a team channel during the specified time period.

It's helpful to include the "Reply Message" definition above.  Now, from these definitions we can derive that Channel Messages will include the unique count of all the messages, including the Post  and Reply Messages.  If you are not seeing that and have a specific example, please share back here in this thread.  In meantime, we appreciate the question and will consider this question as we work to enhance our docs.

**Comment by LanaChin** [comment]
Thank you @quentinhurdazure! Closing this issue.
