### ISSUE TITLE
Microsoft Teams issue in Android

### ISSUE THREAD

**Issue by nunesric** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4546]
Most of the schools now are starting to use Microsoft Teams to interact with the students. There's an issue with Android App as it doesn't show the files for a team. Desktop app and IOS app works and shows the files. Can this be fixed a.s.a.p.? Thanks

**Comment by scanum** [comment]
@nunesric 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
