### ISSUE TITLE
Licensing requirements

### ISSUE THREAD

**Issue by Korbyn72** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#455]
Maybe update the licensing terms and get rid of the Cloud PBX and PSTN Conferencing.  Maybe also include an Skype Room System functionality table based on licensing.  I calculate full functionality with minimal licensing with SFBO Plan2, Phone System, Audio Conferencing and Calling Plan.  Or is there some additional benefit to having an E1, E3 or E5 license instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d310a567-17ea-3581-2d0c-88f5ad7e9233
* Version Independent ID: 0af94ec5-fa79-5e7d-c931-13adb192ac4d
* Content: [Provisioning Skype Room System accounts in Office 365](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/provisioning-skype-room-system-accounts-in-office-365)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/provisioning-skype-room-system-accounts-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/provisioning-skype-room-system-accounts-in-office-365.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Thanks for the suggestions, I'll bring them to the product group. However, SRS v1  is in maintenance mode and I doubt there will be much enthusiasm for devoting resources to it.

**Comment by Korbyn72** [comment]
Maybe fix them both.  https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/with-office-365 is also out of date.

The SRSv2 account and licensing appears to be the same, and both sites are using outdated licensing terms.  I’m also on a customer site, and there is no such product for SFBO Plan 3, just Plan 1 and Plan 2.

As far as I can tell, the backend setup for v2 is the same as v1, you’ve just added a script.  It’s the device endpoint that changed, but what we have to do as Online or Onprem admins is still the same, or am I missing something?

Korbyn

**Comment by jambirk** [comment]
Adding @tonysmit as this involves SfB OL. Do you agree there are issues with the way licensing is described in these articles?

**Comment by jambirk** [comment]
Korbyn, not having done a comparison of the server or service side steps used in v1 vs v2, I'm not entirely sure. I am pretty sure the device imaging and subsequent management has got to be very different.

**Comment by kenwith** [comment]
@Korbyn72 - I was able to get this into the backlog for the Skype Room Systems team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by jambirk** [comment]
@Korbyn72  I'm working on this ask this week. One thing I notice is that the sections that mention the SfBO plans doesn't have a link to the tables mentioning feature support in https://technet.microsoft.com/en-us/library/skype-for-business-online-service-description.aspx 

Rather than rehash tables that already exist, I'd like to link to them. I am also going to review the discussions of OL plans with our SfBO experts te see what else they suggest.

**Comment by jambirk** [comment]
The terminology for the licensing is updated, we've added links to the service descriptions. This is done for both SRS v1 and SRS v2. Please Let us know if there's any other update needed.
