### ISSUE TITLE
Teams - Skype Consumer interop

### ISSUE THREAD

**Issue by SwissChoko** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4550]
Despite having turned on the "Users can communicate with Skype users" option for several weeks, it is still not possible to communicate with a Skype user based on its live account email (@hotmail.com)

is there any specific tricks to solve the issue or any logs to identify the problem ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3de87096-6253-ba71-f27a-0b161a36f0e2
* Version Independent ID: 8b61b40d-496c-6069-8a60-38a6282e072a
* Content: [Teams and Skype interoperability - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-skype-interop#feedback)
* Content Source: [Teams/teams-skype-interop.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-skype-interop.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@SwissChoko 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
