### ISSUE TITLE
Cannot use Wiki on Private Channels in Teams

### ISSUE THREAD

**Issue by nicknnator** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4551]
I created a private channel in Teams and was not able to add a Wiki tab. I added additional public channels and Wiki was available. I tried deleting and re-adding the private channel and still no luck. Is there maybe a Powershell cmd I can run to add it? I know in the past that Powershell had to be used to add features in SharePoint.
Thanks,
Nick

**Comment by scanum** [comment]
@nicknnator 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
