### ISSUE TITLE
Support tags in private channels.

### ISSUE THREAD

**Issue by clcpolevaulter** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4555]
&gt;Tags are not yet supported in private channels.

This is honestly one of the biggest features. We like to keep channels to a minimum and organize public (enterprise wide) and teams specific communication into few channels. We want to summon a subset of those people to certain message. Thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b16e659e-cf07-268a-e224-fa444749ac29
* Version Independent ID: ee822a8d-b331-998f-e336-b1fa510f35c0
* Content: [Manage tags in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-tags#feedback)
* Content Source: [Teams/manage-tags.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-tags.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@clcpolevaulter 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by anniecolonna** [comment]
Hi @clcpolevaulter, thanks for your feedback! We have this on our backlog and will eventually support tags in Private Channels. One follow-up question - would you expect Private Channels to have their own set of tags or to use the tags set up within the team?

**Comment by clcpolevaulter** [comment]
@anniecolonna ::

I'd be fine with using the tags from the team and tagging anyone that was in that tag and private channel. I don't think it is worth the overhead to manage tags per channel.

**Comment by nistre** [comment]
It's been a couple years.  What is the status of this feature?  My organization would also heavily benefit from this feature
