### ISSUE TITLE
Unable to retrieve Private Channel SharePoint URL

### ISSUE THREAD

**Issue by Alexp2019** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4558]
Hi,

I'm unable to retrieve the SharePoint URL of a private channel through any of the methods listed (PowerShell or Graph API)
Graph Example:

![image](https://user-images.githubusercontent.com/38928645/79400469-a9137480-7fc9-11ea-8d0f-c204fb0c3673.png)

![image](https://user-images.githubusercontent.com/38928645/79400537-d3653200-7fc9-11ea-8a75-011848a17535.png)

[Enter feedback here]
![image](https://user-images.githubusercontent.com/38928645/79400550-e0822100-7fc9-11ea-9eab-a626500e8486.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e0ac38-cfff-8d8f-5345-2ae93a9fae2e
* Version Independent ID: bec44289-e9fa-4464-1601-0ca86d61e6ca
* Content: [Manage the life cycle of private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels-life-cycle-management)
* Content Source: [Teams/private-channels-life-cycle-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels-life-cycle-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Alexp2019 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
