### ISSUE TITLE
[LOC]Back-Translation "Microsoft Teams のルーム"→"Microsoft Teams Rooms"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4560]
ja-jp:https://docs.microsoft.com/ja-jp/MicrosoftTeams/rooms/azure-monitor-plan
![azure-monitor-plan_j](https://user-images.githubusercontent.com/40815708/79411312-88edb080-7fdd-11ea-88ce-d10fe43026af.png)

en-us:https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/azure-monitor-plan
![azure-monitor-plan_e](https://user-images.githubusercontent.com/40815708/79411322-8db26480-7fdd-11ea-8bd7-5f015a2bac60.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b772a934-069f-fd16-88c9-9969e2142f20
* Version Independent ID: 0dc7fcb9-eaaf-81f3-9461-1327b1232844
* Content: [Azure モニターを使用して Microsoft Teams の会議室の管理を計画する - Microsoft Teams](https://docs.microsoft.com/ja-jp/MicrosoftTeams/rooms/azure-monitor-plan)
* Content Source: [Teams/rooms/azure-monitor-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/azure-monitor-plan.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@Officeglobal - Hi! Could you please help with this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by scanum** [comment]
@OfficeGlobal Any updates here? Thanks!

**Comment by scanum** [comment]
@OfficeGlobal Any updates here? Thanks!

**Comment by scanum** [comment]
@OfficeGlobal Any updates here? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix. (ETA 8/10/2020)

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum  , @TinaMcN The article was HumanTranslated and published live.
However I can't change translation from "Microsoft Teams ミーティング" to "Microsoft Teams Rooms"
This is an approved translation by Microsoft

![image](https://user-images.githubusercontent.com/47977325/89503864-720ade00-d7c7-11ea-975d-ad2bbbd2e6be.png)

**Comment by TinaMcN** [comment]
@OfficeGlobal please open a request for the linguistic experts to review the feedback from hyoshioka0128  + @ykasugai (https://github.com/MicrosoftDocs/feedback/issues/2865) . The approved term may need to be revised.

**Comment by hyoshioka0128** [comment]
@TinaMcN - "Microsoft Teams Rooms" is one-word as our service name.
"ミーティング" is incorrect as Japanese translation of Rooms. Thanks.

Ref:
(1) [【Japan Partner Conference 2019】チャットだけじゃない! Microsoft Teams Rooms で小会議室から役員会議室まで会議を徹底的に変革する方法](https://www.slideshare.net/microsoftjp/japan-partner-conference-2019-microsoft-teams-rooms)
(2) [Thinksmart hub 500 - Smart Support - Lenovo](https://download.lenovo.com/mobilesjp/thinksmart-hub-500-for-microsoft-teams-deployment-guide-v5.1.pdf)
(3) [Microsoft Teams Rooms用 Logicool Tap - Logitech](https://www.logitech.com/assets/65652/22/tap-datasheet.pdf)

**Comment by TinaMcN** [comment]
@hyoshioka0128 thank you for the references.   I shared them with the linguistic experts who will review the feedback and make a decision.

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 we received a feedback from linguistic expert. The "Microsoft Teams Rooms" was reverted back to ENG and republished at live page

**Comment by hyoshioka0128** [comment]
@OfficeGlobal  @TinaMcN  - "Microsoft Teams Rooms" has been Fixed.
Closed #4560.
