### ISSUE TITLE
Unable to access Teams/Groups during Live Event

### ISSUE THREAD

**Issue by omerahm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4562]
Hi there! After enabling it works for us in a good way but the drawback we are facing is in configuring Live Events. Before enabling it groups/teams were visible and we were adding them and after enabling all are gone.
The scenario, we are using it in Education and due to some reason we have to use the Live Event feature for almost every class and it is not possible to add individuals one after another.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84066c98-38a4-e59a-893f-da38a4a11bf3
* Version Independent ID: 890a4978-0e9b-2691-a2ab-8b5512e5e76f
* Content: [Use Microsoft Teams scoped directory search - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-scoped-directory-search#feedback)
* Content Source: [Teams/teams-scoped-directory-search.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-scoped-directory-search.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@omerahm thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
