### ISSUE TITLE
Conference ID Length Incorrect

### ISSUE THREAD

**Issue by adamvdb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4563]
Conference ID contains 9 digits - not 7 digits as mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f63c7ec-b784-d302-51e9-f359b2c8f89b
* Version Independent ID: 0442ca74-d4f0-e00f-714c-bcd5ad4161f1
* Content: [Reset a conference ID for a user in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/reset-a-conference-id-for-a-user-in-teams#feedback)
* Content Source: [Teams/reset-a-conference-id-for-a-user-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/reset-a-conference-id-for-a-user-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@adamvdb  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @adamvdb, thank you for your feedback.

I think it´s 8 digits with the following format:
xxx xx xx#

Could you please double-check? Thanks!

**Comment by scanum** [comment]
@dariomws Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
