### ISSUE TITLE
Unable to access Whiteboard in MS Teams

### ISSUE THREAD

**Issue by TomasAEVI** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4564]
Hi,

i am a bit strugling with seting up MS Whiteboard in MS Teams. I got it allowed for whole organization but still when trying to share whiteboard in call i got this message:
Error
An error occurred while processing your request
Something went wrong retrieving your board

Did someone solved it and can share their solution?
Thank you

**Comment by scanum** [comment]
@TomasAEVI thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
