### ISSUE TITLE
Is it really possible to limiti the capability to create Teams only to administrators withouth the requirement of Azure AD Premium license?

### ISSUE THREAD

**Issue by rrgonzalezz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4565]
In the table under the section "Group and team creation, naming, classification, and guest access", it is listed that the capability of "Team creation" can be limited to administrators without the requirement of Azure AD Premium license. To my understanding, this is incorrect, as it is not possible to lockdown Teams creation without Azure AD Premium. Could you please clarify and / or correct this point?

Thanks and best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c43928-84c0-0a75-9354-66aef3b83e46
* Version Independent ID: f95298ae-de58-02eb-0b49-8390ab161d4c
* Content: [Plan for governance in Teams - Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/plan-teams-governance#feedback)
* Content Source: [Teams/plan-teams-governance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-teams-governance.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@rrgonzalezz thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by rrgonzalezz** [comment]
Hi,

thanks for the update. No worries, I do not have the need to open a support ticket, I know the answer to my own question, I was just surprised to find this incorrect and misleading information in this documentation.

From licensing perspective, the only possible way to limit the capability to create Teams only to administrators is with Azure AD Premium licenses. But anyhow you can check this internally. It would be good if the statement in the table of this documentation is corrected.

Thanks and best regards,
Rogelio

________________________________
