### ISSUE TITLE
What licensing will be required after the promotion period ends?

### ISSUE THREAD

**Issue by DevJonBirkett** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4566]
Hi, 
Can details be added to this page to clarify what licensing will be needed after the promotional period ends please?
Lack of this information is making future planning regarding the priority notifications feature difficult. Don't want to include a feature into LoB processes only to find out we aren't licensed for it. 
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca3f7a45-e892-fbb3-baf1-c556fa8e3720
* Version Independent ID: 9c8b63e8-7320-ed8f-e560-ed478009dd57
* Content: [Priority notifications in Teams Messaging  - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/teams-add-on-licensing/pri-message#feedback)
* Content Source: [Teams/teams-add-on-licensing/pri-message.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/pri-message.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by cnb2412** [comment]
I second this request. We also need the information.

**Comment by scanum** [comment]
@DevJonBirkett  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by oradcliffe** [comment]
So this doc says priority notifications will require special licensing, but no one knows what that licensing is?  Can we get someone looking at this please?

**Comment by dariomws** [comment]
Hi @DevJonBirkett @cnb2412 @oradcliffe, thank you for your feedback.

"After the promotion period ends, licensed users will be able to send priority notifications according to the terms of their subscription".

You should check terms of their subscription when this period ends because it could change, but I´ll give you an idea:
- E1, F1, F2, and A1 and Business plans will get 5 urgent messages per month
- E3, A3, E5, and A5 will get unlimited urgent messages

**Comment by DevJonBirkett** [comment]
@dariomws 
Appreciate the update. It gives us a starting point for planning, thanks.

**Comment by scanum** [comment]
@oradcliffe Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
