### ISSUE TITLE
Conditional Access support

### ISSUE THREAD

**Issue by KapilaMunaweera** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4568]
No other conditional access policies are supported - is this limitation is only for now or never?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f7e3603-9bec-acfc-1854-2c1275950cde
* Version Independent ID: 2aed2376-277a-3e93-5000-e509ff53434d
* Content: [Authentication in Microsoft Teams Rooms - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-authentication)
* Content Source: [Teams/rooms/rooms-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-authentication.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@KapilaMunaweera thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
