### ISSUE TITLE
Where is the Live Event recording stored?

### ISSUE THREAD

**Issue by v-olduch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4570]
When a live event has concluded, the producers can download the recording and reports from the Teams Calendar item for that live event. The recording and reports are not attached to the Outlook calendar item, nor are they on Stream. Where is the actual location of that data? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: becbf3ca-b88c-b033-a145-9a1af201ced3
* Version Independent ID: 41a6a9b5-d3dd-d8c9-9e97-920ff2fd1a24
* Content: [What are Microsoft Teams live events? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/what-are-teams-live-events#streaming-platform)
* Content Source: [Teams/teams-live-events/what-are-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/what-are-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@v-olduch thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by v-olduch** [comment]
Hi!

Actually, this is not a situation that I am facing myself. Rather, I am assisting customers onboarding to Office 365 and Teams and that is a question that some of them are having concerning Live Events and is not actually a concern for support in the sense that the Live Event recordings and reports are located in Teams, and you can download them as the documentation mentions. The actual ask is about the residency of that data, in the sense, where is it located in the customer tenant:
-Is it in Stream? If so, is it located in the same region as the rest of the customer's Stream data?
-The documentation mentions an Azure Media Service, and Azure Content Delivery Network, are these components located in the same data centers as the customer's Azure tenant? Or are they located elsewhere?
-Is the data located in Teams? If so, is it located in the same region as the rest of the customer's Teams data?
-Can the customer manage this storage? How much storage is available? Should the customer be concerned if they roll out Live Events daily because of Covid, that some of the data might be lost?

Does this help you scope my request better?
