### ISSUE TITLE
The regional availability is incorrect.

### ISSUE THREAD

**Issue by ZugBug** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4572]
Live Events are not available in Germany, I have received confirmation of this from engineering.

Based on my testing it appears that live events are also not available in South Africa or France.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ZugBug  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by teomonda** [comment]
From what i know this is related to Azure Media Services not being yet available in these new datacenters.
However as per this list, it is there in South Africa and France, while it is not in Germany and Switzerland:
https://azure.microsoft.com/en-us/global-infrastructure/services/?products=media-services&regions=france-central,france-south,switzerland-north,switzerland-west,south-africa-north,south-africa-west,germany-non-regional,germany-central,germany-north,germany-northeast,germany-west-central

**Comment by dariomws** [comment]
Hi @ZugBug, thank you for your feedback.

@teomonda thank you for your comment.

Are you suggesting that we add a note or comment that it´s not available for example in Germany? Because we can say that it´s available in Europe in almost all datacenters.

**Comment by ZugBug** [comment]
Hi Dario,

Thanks for reaching out.

I think it’s a good idea to mention specifically which European countries it is not supported in, any vagueness here will generate support volume around “we are in Europe why don’t we have this”.

Kind regards,

Sam

**Comment by zlorgz** [comment]
hi i confirm it's not available in france

**Comment by scanum** [comment]
@dariomws Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
