### ISSUE TITLE
Site Storage allocation and management

### ISSUE THREAD

**Issue by rachoksh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4575]
Can we update this private channels page to specify the default site collection size for a private channel is 25 TB and how to change that allocation using the UI or PowerShell? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels#feedback)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@rachoksh  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @rachoksh,

Thank you for your feedback.

All default site collection size in SharePoint Online is 25 TB and you can change it:
https://docs.microsoft.com/sharepoint/manage-site-collection-storage-limits

**Comment by TokyoScarab** [comment]
@rachoksh  Thanks for raising this issue! I will be looking into it and updating the page accordingly!

**Comment by scanum** [comment]
@rachoksh Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
