### ISSUE TITLE
missing permission for custom app uploading

### ISSUE THREAD

**Issue by AnanyaNataraj** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4576]
not able to upload custom app due to some permission missing. facing issue finding the permission to be given because of old documentation and change in ui.

**Comment by scanum** [comment]
@AnanyaNataraj thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
