### ISSUE TITLE
No Discovery Settings in Teams

### ISSUE THREAD

**Issue by kstario** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4577]
Oddly, everything under "Set whether existing private teams are discoverable" is not true. The PS script does not make a team appear in search, and there is no "Team Discovery" section under the Team settings tab. Did something change since this was written?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5920152-5fee-41ed-56df-ad7b51b25cc2
* Version Independent ID: 88cfc850-5e36-48ee-ba99-088b2b653f1e
* Content: [Manage discovery of private teams in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-discovery-of-private-teams)
* Content Source: [Teams/manage-discovery-of-private-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-discovery-of-private-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by kstario** [comment]
We can probably put a pin in this for now. I opened a ticket with support, they are "researching". They said the following: That Preview features are rolled out by Datacenter, so if the Preview hasn't reached my tenant's DC yet then they won't see it. They also said that they can "turn on" Preview for my tenant, but they wanted to see what it will do to the tenant. So...?
I thought I had Preview on, based upon my tenant's organization settings. All I know for sure is that MS support doesn't know what Preview is or how it works, so this entire article, which appears to have been published for 2 months (!), should probably go away until this feature is *actually* rolled out.

**Comment by scanum** [comment]
@kstario  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @kstario, thank you for your feedback.

I found the ShowInTeamsSearchAndSuggestions parameter in the latest Teams PowerShell module (1.0.6). But I cannot find "Turn on discoverability check box" in the Admin Center.

Do you have more information from support?

Thanks!

**Comment by kstario** [comment]
I have a ticket open with support. They’ve escalated. Nothing from them yet… I will post back when they have something for me.

**Comment by dariomws** [comment]
Thank you @kstario!

**Comment by scanum** [comment]
@kstario Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by kstario** [comment]
The issue has not been resolved...
________________________________

**Comment by dariomws** [comment]
Hi @kstario,

As you wrote in your second comment, it is a preview feature. It may not be available to all tenants worldwide.
Please share the support information, if there is anything to update in this article we can reopen it.

**Comment by Teimoon** [comment]
I have the same Issue. 
I opened a ticket, but the microsoft support did not help me. they did not understand the issue and gave me to do's without any sense.

**Comment by dariomws** [comment]
Hi @Teimoon, thank you for your comment.

This is a preview feature and that's why you probably don't have this option in the Admin Center yet.

**Comment by kstario** [comment]
Dario- The issue here is that MSFT uses the word “preview” in other circumstances to mean a features that can be enabled or disabled by the customer. Insider builds, admin centers, etc. all have used preview. Thus, it seems many of us Admins are expecting the Teams “preview” to also be something that we can enable/disable. Thus you can see why it’s confusing to respond stating that preview status is the reason for why it’s not available.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by kstario** [comment]
Hi All-

I finally received an update from Microsoft regarding Discovery:

“I (MS Support) was informed by the product team that new requests for Preview Release are no longer being responded to.

They also informed me that the discovery feature will be made available by the end of September.”

Hopefully we see the feature in September!

**Comment by dariomws** [comment]
@kstario Thank you for this information!

In September when this feature reach GA, we can remove the preview sentence.
