### ISSUE TITLE
Personalizzazione inviti email

### ISSUE THREAD

**Issue by gabrielepardo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4578]
Sarebbe molto utile poter personalizzare la parte superiore dell'invito che viene mandato per email. 
In questo momento si possono inserire dei testi soltanto all'interno dell'invito alla singola riunione (dal calendario) ma sarebbe utile avere uno spazio personalizzabile nell'interfaccia amministratore e che venisse prima della riga e dell'invito a partecipare.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Gestire le impostazioni delle riunioni - Microsoft Teams](https://docs.microsoft.com/it-it/microsoftteams/meeting-settings-in-teams#feedback)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@gabrielepardo thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
