### ISSUE TITLE
Usage of the word anonymous is misleading and confusing for who can join the meeting.

### ISSUE THREAD

**Issue by rachoksh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4580]
Can this documentation be improved? 

We could improve this line that reads "2. Under Participants, turn on Anonymous users can join a meeting."

It could say something like anonymous is not actually anyone without authentication but invited users outside the tenant like gmail.com, outlook.com email addresses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Manage meeting settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@rachoksh  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @rachoksh, thank you for your feedback.

"Anonymous users can join a meeting" is an option in the Teams Admin Center and I cannot change it. Anyway, anonymous users can join Teams meeting without an account, just writing their name:
https://support.microsoft.com/office/join-a-meeting-without-a-teams-account-c6efc38f-4e03-4e79-b28f-e65a4c039508?ui=en-us&rs=en-us&ad=us

**Comment by scanum** [comment]
@rachoksh Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by rachoksh** [comment]
The link posted is not working. Thanks

**Comment by dariomws** [comment]
Sorry about that:
https://support.microsoft.com/en-us/office/join-a-meeting-without-a-teams-account-c6efc38f-4e03-4e79-b28f-e65a4c039508

**Comment by rachoksh** [comment]
The customer turned on anonymous join and it works now for users outside the tenant invited with personal email addresses. I understand the documentation is based on the UI and you cannot change the UI. Thanks

**Comment by dariomws** [comment]
Hi @rachoksh,

If the anonymous join is enabled, you can join the meeting without authentication or email, just writing your name.
Why do you think that the UI must be updated?

**Comment by suresh-solomon** [comment]
Hi @dariomws,

I suggest there is an information button on the participant option that states who anonymous users are, it is quite confusing to differentiate guests and anonymous users. Maybe they are the same!?
When I add a @yahoo.com account as a team member, the word guest is in brackets. Not clear how anonymous is defined. If there is a link do let me know.

thank you
Suresh

Suresh

**Comment by dariomws** [comment]
Hi @suresh-solomon,

Anonymous don´t have an email or account, they just can join the meeting without using credentials:
https://docs.microsoft.com/microsoftteams/meeting-settings-in-teams#allow-anonymous-users-to-join-meetings
https://support.office.com/article/join-a-meeting-without-a-teams-account-c6efc38f-4e03-4e79-b28f-e65a4c039508

Guests are external users that you add to your organization to participate in teams and channels, they are authenticated/identified:
https://docs.microsoft.com/microsoftteams/guest-access
And they can also join meetings.

There are also external users from other companies:
https://docs.microsoft.com/microsoftteams/communicate-with-users-from-other-organizations

**Comment by suresh-solomon** [comment]
Thank you @dariomws ,  this definitely helped, I could not figure out how to join a teams meeting anonymously, now I understand. 
Suresh
