### ISSUE TITLE
Max number of people that can be set to "Notify when available" is 15

### ISSUE THREAD

**Issue by TheresASnakeInMyBoots** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4582]
One of our users is new to Teams and was setting people in their contact list to show a notification to the user when their status was switched to available. In Skype the setting did not appear to have a limit. Once you get to 15 people in your chat/contact list with this setting on, you see an error message pop up in the bottom right corner of Windows saying that the action can't be performed, with no additional details. 
I've been unable to find any reference to the limit or mention of this at all. Anyone else seeing this? Am I looking in the wrong place to try to adjust that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#feedback)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@TheresASnakeInMyBoots thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
