### ISSUE TITLE
Incorrect username identified as initiator when someone has been removed from a Team

### ISSUE THREAD

**Issue by ibillwilson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4584]
Teams, in the "General" channel feed for a particular Team, is showing that I deleted two people from a Team yesterday. I know that I did no such thing... unless I am doing this in my sleep or have become the Manchurian Admin.

I wonder if it's related to this previously known issue that was cleared in December (via https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/3686)?

<img width="580" alt="Screen Shot 2020-04-17 at 12 38 44 PM" src="https://user-images.githubusercontent.com/43509512/79594898-e5b79c80-80ab-11ea-8b03-3c66112c11ca.png">

Edit: new info...

One person was likely removed through AAD as part of some HR process (because the dude retired a couple days ago). The other accidentally removed himself using the Teams app...

> It was within the teams app itself - I right clicked the "team" on the left hand menu and select leave team. I thought this would mute notifications because everyday I get about 15 of these notifications. I have figured out now how to mute the team now. 

Both removals appeared in the same channel notification.
![image](https://user-images.githubusercontent.com/43509512/79598372-d5a2bb80-80b1-11ea-815f-ebfc7bc6ecbf.png)

Edit: even more info...

It's not just removals, but additions too. The first instance was on March 18th. I know there is no way I did this because I can think of no circumstance under which I would add HR people to this team (unless I know them outside of their HR role or I'm under duress). Since then, there are MANY instances in the channel feed showing that I added or removed members.

This is all weird because I didn't create the Team, don't really do anything to administer or manage the Team, and have never (to my conscious recollection) purposely added or removed anyone. I was apparently made an owner of the Team out of spite or just for yuks.

**Comment by scanum** [comment]
@ibillwilson thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
