### ISSUE TITLE
Uninstall example using powershell

### ISSUE THREAD

**Issue by brucesp1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4585]
This page says there are 2 ways to uninstall the VDI MSI for Teams, PowerShell, and MSIEXEC command line.  You give an example for the MSIEXEC but not for PowerShell.  Please provide a PowerShell Script like you did MSIEXEC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi#feedback)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@brucesp1  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @brucesp1, thank you for your feedback.

The script is not available anymore, please use the MSIEXEC method. I am updating the article, thank you for pointing it out.

**Comment by scanum** [comment]
@brucesp1 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
