### ISSUE TITLE
Where do we find them?

### ISSUE THREAD

**Issue by heaths** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4586]
This article reads,
&gt; The debug logs are automatically downloaded to the following folders.
&gt; * Windows: %userprofile%\Downloads

Okay, but how do we "download" them? Normally, logs are produced when some setting is configured or trace performed and put somewhere. Not sure what you mean by "downloaded" here. As written, this page does not help me troubleshoot calling issues at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d5e6d3-b7e0-d79f-0dea-ed423186a157
* Version Independent ID: ec6e68aa-552f-ab45-3c8e-92eff526b173
* Content: [Use log files in troubleshooting Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/log-files#feedback)
* Content Source: [Teams/log-files.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/log-files.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@heaths  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @heaths, thank you for your feedback.

The debug logs are produced/downloaded using the following OS-specific methods:
- Windows: Keyboard shortcut: Ctrl + Alt + Shift + 1
- Mac OSX: Keyboard shortcut: Option + Command + Shift+1

When you use this keyboard shortcut, you will see a "1 file downloaded" notification. Then you should go to the specified location to get the file.

**Comment by heaths** [comment]
Thank you. Can you add that to the page as well?

**Comment by dariomws** [comment]
It´s in the article actually :)

**Comment by heaths** [comment]
Ugh 🤦‍♂️, you're right. I somehow missed that. Thank you for pointing that out.
