### ISSUE TITLE
MS teams limitations per licence

### ISSUE THREAD

**Issue by tomashpetr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4587]
Multiple microsoft official help pages reffer to this page as description of MS teams service limitations per specific licence.. I see no such information here. Only the mention that "CORE teams features are available across all licences". No specification what are the CORE features and what the other..

Especially cooperation via scheduled meetings, audio conferences, etc. are of the question. AS TRUSTWORTHY INTERNET REVIEWS SAY NOT ALL FEATURES ALL AVAILABLE FOR ALL ENTERPRISE LICENCES. I would like to understand the price per required features before I start the movement in our company to move to Teams

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: c59eff85-a7f1-764b-4716-b79d70c18d18
* Version Independent ID: 49ecb4f7-3e80-c81a-32b6-4f3fda8826dd
* Content: [Office 365 licensing for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/cs-cz/microsoftteams/office-365-licensing)
* Content Source: [Teams/Office-365-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-licensing.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@tomashpetr  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @tomashpetr, thank you for your feedback.

I think all is in the article:
"In terms of Teams core functionalities, there are no differences between the subscriptions. The availability of the compliance capabilities does rely on the correct subscription level. To learn more, read Overview of security and compliance in Teams. For a detailed list of features available in each subscription, see the Office 365 Platform Service Description.

Cloud voice features: For Audio Conferencing, your organization will need to buy and assign an Audio Conferencing license to each user who will be setting up dial-in meetings. For Calling Plans, each user will need a Phone System plus a Domestic or Domestic and International Calling Plan. To learn more, see Microsoft Teams add-on licensing.

All supported subscription plans are eligible for access to the Teams web client, desktop clients, and mobile apps."

So, all is included in all plans with some exceptions:
- Compliance capabilities, read more here: https://docs.microsoft.com/microsoftteams/security-compliance-overview
- Voice: read the paragraph in the article for more information.

**Comment by scanum** [comment]
@tomashpetr Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
