### ISSUE TITLE
Grant-CsTeamsChannelsPolicy' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by desarrollocdb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4592]
I get this error when executing

The term 'Grant-CsTeamsChannelsPolicy' is not recognized as the name of a cmdlet, function, script file or program
executable. Please check if you spelled the name correctly or if you included a path, check that the path is correct and try again.

My script

$GroupName = "Permitir_crear_grupos"
$PolicyName = "Docentes"

$credential = Get-Credential
Connect-AzureAD -Credential $credential
Import-Module MicrosoftTeams
Connect-MicrosoftTeams -Credential $credential

$group = Get-AzureADGroup -SearchString $GroupName
$members = Get-AzureADGroupMember -ObjectId $group.ObjectId -All $true | Where-Object {$_.ObjectType -eq "User"}
$members | ForEach-Object { Grant-CsTeamsChannelsPolicy -PolicyName $PolicyName -Identity $_.UserPrincipalName}

**Comment by scanum** [comment]
@desarrollocdb thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
