### ISSUE TITLE
Why don't you update the article to tell people how to track who added it?

### ISSUE THREAD

**Issue by techlogik** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4596]
MIght want to update the article to tell people where to find who signed up.

**Comment by scanum** [comment]
@techlogik thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
