### ISSUE TITLE
Link to [Steering Committee Template – Link to sample PPT template] is missing

### ISSUE THREAD

**Issue by pamelamontes01** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4597]
The link to the  [Steering Committee Template – Link to sample PPT template] is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb4be65-f72b-54ae-0168-a2c721f4d88e
* Version Independent ID: cbf0ca70-508f-9f10-7f50-3a4d3a20366b
* Content: [Steering committee for cloud voice deployment - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/envision-steering-committee-complete-guide#feedback)
* Content Source: [Teams/envision-steering-committee-complete-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/envision-steering-committee-complete-guide.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@pamelamontes01 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
Hi @pamelamontes01  Thanks for raising this issue! I will be looking into it!

**Comment by TokyoScarab** [comment]
@LanaChin I've searched around the github trying to find the template this is referring to and it doesn't seem to exist. Do you know if there is an official Microsoft template or what this link might have originally pointed to? Any help would be very much appreciated, thanks!

**Comment by LanaChin** [comment]
The article has been updated as the PowerPoint presentation template is no longer available.  Thanks for your feedback!
