### ISSUE TITLE
Requirement for Phone System addon

### ISSUE THREAD

**Issue by naminakao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#46]
One of our customers told us that they were able to apply phone system addon to SfB Online Plan2.
If users having SfB Online Plan2 do not need to switch Enterprise subscription, would you update the content?

**Comment by tonysmit** [comment]
Yes, technically it possible to add them to a SP2. However, for more features they recommend upgrading to an E-based plan.

**Comment by tonysmit** [comment]
@naminakao - Can you send me a link please?

**Comment by naminakao** [comment]
https://support.office.com/en-us/article/3ed752b1-5983-43f9-bcfd-760619ab40a7

**Comment by tonysmit** [comment]
@naminakao - Can you copy the exact text of what you feel needs changed? Thanks, Tony

**Comment by naminakao** [comment]
pasted screenshot. 

![image](https://user-images.githubusercontent.com/34467132/36703501-405de3b6-1b9f-11e8-8626-e57c45045327.png)

**Comment by tonysmit** [comment]
@naminakao - ok, I've updated the text and added a couple notes to make it more clear. See if they work. I just published it live on DMC.
