### ISSUE TITLE
Guest access restricted when only part of the email domain is assigned to Office 365 

### ISSUE THREAD

**Issue by gravescj2018** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#460]
Step 3 says "The guest receives a welcome email from the team owner, with information about the team and what to expect now that they're a member. Guest users who have an email address that belongs to an Azure Active Directory or Office 365 work or school account can accept the invitation directly."  

There is a serious problem when the organisation has only part adopted Office 365.  This is happening with some UK universities where students have an Office 365 email account and ID but staff have an "on premise" exchange email account.

Trying to add these staff members as guests to a "Teams" set-up at another institution which has fully adopted Office 365 - is very difficult.  Currently the advice from Microsoft Partners seems to be go and create a Gmail account - use that as your guest access method and get the gmail account to forward all your email from teams to your institutional account.  Current GDPR ethos makes using a consumer account problematic in various instances.

Microsoft needs to find a way round disenfranchising potential guests that operate in an environment which is completely Microsoft licensed but which blocks them from being a guest because their exchange email address is blocked from becoming a "Microsoft account"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 754022e3-49eb-dbd5-e4f5-891c8ebeb491
* Version Independent ID: b73a6f64-d36f-298f-d9ac-34860abad42b
* Content: [How a guest joins a team](https://docs.microsoft.com/en-us/microsoftteams/guest-joins)
* Content Source: [Teams/guest-joins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-joins.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **rramesan**

**Comment by kenwith** [comment]
@gravescj2018 - This is a really good idea and I was looking through User Voice and noticed a number of similar ideas too. I am up voting this one: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/33826501-rethink-guest-access

You can also find other ideas to up vote or post additional ideas or comments. Thank you for your involvement and feedback!

If you don't mind I would like to also post your comment in the comments section of the User Voice but I wanted to get your permission first or if you wouldn't mind posting it and up-voting.

**Comment by gravescj2018** [comment]
Hi Ken

Yes that is fine – you can post my comment

Chris

**Comment by kenwith** [comment]
Awesome, posted it. Thanks.
