### ISSUE TITLE
[LOC]Inappropriate japanese "た microsoft teams ロゴを示すアイコン"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4601]
ja-jp:https://docs.microsoft.com/ja-jp/microsoftteams/teams-live-events/set-up-for-teams-live-events
![set-up-for-teams-live-events_j](https://user-images.githubusercontent.com/40815708/79710546-43442700-8300-11ea-95b5-bdb7f61ff825.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b9aa4676-855a-fddb-bb0b-96b7095c695e
* Version Independent ID: 7c39f08c-0d56-6d29-1356-879d9d6ff51c
* Content: [Microsoft Teams でのライブ イベントのセットアップ - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/teams-live-events/set-up-for-teams-live-events)
* Content Source: [Teams/teams-live-events/set-up-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/set-up-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@OfficeGlobal Hi! Could you please support the following issue? Thanks

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 article was HumanTranslated and published live

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
