### ISSUE TITLE
List of known issues lost

### ISSUE THREAD

**Issue by sare-MS** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4602]
Hi team, This page used to host a list of known issues and their workarounds. I no longer see that. Was this removed or moved elsewhere? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues#feedback)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by todmccoy** [comment]
These were broken up into smaller pages and can be found here:
https://docs.microsoft.com/MicrosoftTeams/troubleshoot/teams

**Comment by scanum** [comment]
@sare-MS Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sare-MS** [comment]
Thank you Tod. Much appreciate your quick response on this.

Best Regards
Sashi
