### ISSUE TITLE
Diable group chat

### ISSUE THREAD

**Issue by NathanJohnNelson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4603]
Hello,
I would like to disable the ability for a user to create group chats with multiple users.
I wish them to be able to use 1 to 1 private chats but not a private group chat. Reading through the documentation and on the teams admin platform I have not been able to locate a policy which will allow me to limit this kind of interaction. Does it exist or is it's creation pending?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34f3188-0af5-f972-9d28-959f5f7866a2
* Version Independent ID: fab26e11-a729-92a4-3ea6-8668dca55dd0
* Content: [Manage messaging policies in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/messaging-policies-in-teams#feedback)
* Content Source: [Teams/messaging-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/messaging-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@NathanJohnNelson thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by navjotghai** [comment]
looks like this feature only works when your single group chat window contains up to 20 users, if your group chat is over 20 users, the (! Urgent) option disappears.
Any ideas? i cant see any restrictions on the webpage if this feature only works for upto 20 users in a single group chat window.

**Comment by NathanJohnNelson** [comment]
> @NathanJohnNelson thank you for submitting feedback.
> I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
> Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
> Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

The final answer from support:
"Microsoft Office 365 is an evolving service and we continuously develop features and services based on current technology trends and the feedback we receive from our valued customers. We can understand the need for availability of this feature to meet the needs of your business, what you can do is to submit an entry via Teams UserVoice (https://microsoftteams.uservoice.com/) so our developers can weigh the merits of our suggestion and act on it accordingly."
