### ISSUE TITLE
Teams live events and Skype Meeting Broadcast (On YouTube Live / Facebook Live)

### ISSUE THREAD

**Issue by alexbreadcrumb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4605]
I've a question more than an issue...
anyone know if is possible host a live event from Microsoft Teams to YouTube or Facebook like Zoom does?
Here a capture of the options that give you Zoom:
![Zoom Streaming Options](https://user-images.githubusercontent.com/47953802/79758053-df633380-82ea-11ea-9c35-18ad2792bd41.png)

**Comment by scanum** [comment]
@alexbreadcrumb thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
