### ISSUE TITLE
I noticed that 

### ISSUE THREAD

**Issue by Tricia911** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4606]
Can you clarify "Conferenced in but are muted" notification format? The description implies that the Notification is a chat, but says recipients "can listen (but not participate)."  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66544770-c56b-ad8a-5b67-9e20cbc945f1
* Version Independent ID: d69667d5-d486-4b99-5e07-edb2fda7f5c7
* Content: [Manage emergency calling policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-emergency-calling-policies#feedback)
* Content Source: [Teams/manage-emergency-calling-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-emergency-calling-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Tricia911 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by MaratMussabekov** [comment]
Hello @Tricia911 ,
when  "Conferenced in but are muted" is chosen:
1. someone make an emergency call
2. the people you specified will receive a notification about this call via Teams chat
3. Notification contains the link to the call, so they can join the call, but their microphones will be muted during the call (so they can only listen).
Thank you

**Comment by scanum** [comment]
@Tricia911 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
