### ISSUE TITLE
Public vs Private IP

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4608]
Does this take into account both the private IP address of the client and the public internet egress IP that the Teams service sees?  If not, this should note that there can be overlaps and reports will not be accurate on where the client is.  For example, the clients internal IP address at a starbucks might be the same as one of the IP subnets that is used at an internal branch office.  Same with a user at home.  In those scenarios, the network connectivity is drastically different, but the reports would show it as being from a corporate location.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f8119c9-61af-b469-af98-ddd37764c0ca
* Version Independent ID: 7d829a74-9df7-5b6f-8e1c-44d3e5d38f75
* Content: [Add and update reporting labels - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/learn-more-about-site-upload?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/learn-more-about-site-upload.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/learn-more-about-site-upload.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @danmyhre, thank you for your feedback.

@tonysmit could you kindly help with this issue? Thanks!

**Comment by tonysmit** [comment]
@nomorephones - Can you assist here please?

**Comment by nomorephones** [comment]
Great question.  @williamlooney would need to provide commentary here, as this is really a question around the manner in which the data is being handled.  I don't think that we're using the external IP address (similar to what's configured for dynamic emergency calling support) but there can be other ways this is managed internally.

**Comment by williamlooney** [comment]
@nomorephones - The comment above is correct. The network address is based on the local/internal IP address. There is an issue if a customer's subnets overlap a home users, or if they are using multiple overlapping subnets within their enterprise. The right solution would to also use their external IP address to disambiguate the overlaps

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by danmyhre** [comment]
The comments above should be incorporated into the content
