### ISSUE TITLE
Can we see live call data?

### ISSUE THREAD

**Issue by leedsteam** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4611]
Can I see what calls are happening on teams live?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dedf646c-c5dc-5645-54a2-1bca0d406f45
* Version Independent ID: 9a52f0b1-2970-559e-2d18-8e565662ca26
* Content: [Call Analytics and Call Quality Dashboard - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/difference-between-call-analytics-and-call-quality-dashboard)
* Content Source: [Teams/difference-between-call-analytics-and-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/difference-between-call-analytics-and-call-quality-dashboard.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@leedsteam thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
