### ISSUE TITLE
First item is inaccurate

### ISSUE THREAD

**Issue by jvolp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4614]
Every single issue we've encountered where a user cannot log on to Teams has been when they are already logged into O365 and are able to successfully launch every other app.  Teams is absolutely doing something ELSE not shared with the rest of the O365 suite and we desperately need accurate documentation indicating what that is.  We've had several users that simply cannot log into Teams via web or app on a particular device and nothing we've been able to do has fixed it (browser cache, windows credential manager, teams app cache/reinstall, new windows user profile).  Our only success thus far has simply been getting the user onto another physical device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf54bf5d-1748-46bf-a503-5e978f56126c
* Version Independent ID: 5976a1df-52e9-eb19-fd41-c7b04fce74f8
* Content: [Sign in to Teams using modern authentication - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sign-in-teams)
* Content Source: [Teams/sign-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sign-in-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@jvolp Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @jvolp 
How are you? Hope you are doing good.
First of all, **thanks for your feedback.** 
I do not know exactly what is happening in your scenario, to be able to fix or add information to the documentation, is this related to Modern Auth?, for example.

Did you already checked this resource ? https://docs.microsoft.com/en-us/MicrosoftTeams/troubleshoot/teams

In case you do not find the answer on that resource, I think in this case, the best thing to do would be contact support directly in your tenant, as they will be able to help you in your exact scenario. 

Hope I could help you.

**Comment by jvolp** [comment]
Thanks for your follow-up.  What we have discovered via trial and error is that Teams logins will not work if the users Time Zone is incorrect on their device.  This is a simple fox, but it's not documented anywhere and our Azure portal reports the logins as "successful" even though they are not.  Again, this is not something we should need to discover on our own. The documentation regarding Teams authentication is inaccurate and states it is the same as all other O365 apps.  It is not.  This needs to be documented, especially with MS support staff.

**Comment by get-itips** [comment]
> Thanks for your follow-up.  What we have discovered via trial and error is that Teams logins will not work if the users Time Zone is incorrect on their device.  This is a simple fox, but it's not documented anywhere and our Azure portal reports the logins as "successful" even though they are not.  Again, this is not something we should need to discover on our own. The documentation regarding Teams authentication is inaccurate and states it is the same as all other O365 apps.  It is not.  This needs to be documented, especially with MS support staff.

Thanks for getting back and sharing that valuable feedback.
I will try to pass that message along as Teams Troubleshooting information is located on another repository where I am not currently a collaborator.
In case anyone else faces the same issue as you, they will be able to find your feedback here.
Thank you again

**Comment by scanum** [comment]
@jvolp  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
