### ISSUE TITLE
remote team

### ISSUE THREAD

**Issue by cesquivel1990** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4617]
Hello.
I have problem with the desktop remote. because when an user shared me desktop and I run .exe with admin privilege the screen freeze.
note: I need run with admin privilege because the user has not permission of install

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 9ce30163-6327-899b-281d-d4ef982fce5e
* Version Independent ID: e61dcbb8-4877-ef6f-1987-981cdd7fc82f
* Content: [Configure el uso compartido del escritorio en Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/es-es/microsoftteams/configure-desktop-sharing#feedback)
* Content Source: [Teams/configure-desktop-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/configure-desktop-sharing.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **Lolaj**

**Comment by scanum** [comment]
@cesquivel1990 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
