### ISSUE TITLE
Confirm Exchange Online requirement

### ISSUE THREAD

**Issue by bedwell84** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4619]
This page says an Exchange Online mailbox is required to schedule a Live Event. I have tested with an Exchange 2016 on-premises mailbox with the required OAuth integration configured, and I was successfully able to schedule and produce a Live Event in Teams through the integrated Calendar.
Can it please be confirmed if this is a supported feature where the required integration is configured with on-premises Exchange, and the documentation updated to reflect this?
https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact

**Comment by dstrome** [comment]
This article was updated this afternoon to reflect the Exchange hybrid deployment requirement needed to enable Teams and Exchange integration.
