### ISSUE TITLE
Minimum funding amount increased to $50

### ISSUE THREAD

**Issue by wsato** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#462]
We received email notification titled "Warning! Your Skype for Business Online PSTN calling service pre-paid account is out of funds." We checked the balance and the usage report. It was still above our auto-recharge threshold of the $20 minimum. We tried to update the auto-recharge settings when the balance falls below $40, but it showed an error: "Please enter a whole number greater than or equal to 50." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8a7310d-8732-1d60-1d85-7731a7c5a7b8
* Version Independent ID: cc4c6f27-d870-f40d-586b-a15230500e97
* Content: [What are Communications Credits?](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-and-microsoft-teams-add-on-licensing/what-are-communications-credits#recommended-funding-amounts)
* Content Source: [Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/what-are-communications-credits.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/what-are-communications-credits.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@wsato - sorry for the delay on a response. If you haven't already resolved I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by guillaumecouture** [comment]
The 50$ minimum credit balance was confirmed by engineers in service request https://microsoft.visualstudio.com/OSGS/_workitems/edit/17345558

Sri Harsha Suripeddi (Infosys Ltd)commented 4 weeks ago
@Guillaume Couture (Sherweb Inc) Please ask the people to modify the doc/link accordingly. In case they have any questions please ask them to reach out to Tim Eshelman(timesh@microsoft.com).

**Comment by guillaumecouture** [comment]
The 50$ minimum credit balance was confirmed by engineers in service request https://microsoft.visualstudio.com/OSGS/_workitems/edit/17345558

Sri Harsha Suripeddi (Infosys Ltd)commented 4 weeks ago
Please ask the people to modify the doc/link accordingly. In case they have any questions please ask them to reach out to Tim Eshelman(timesh@microsoft.com).

**Comment by guillaumecouture** [comment]
The 50$ minimum credit balance was confirmed by engineers in service request https://microsoft.visualstudio.com/OSGS/_workitems/edit/17345558

Sri Harsha Suripeddi commented 4 weeks ago
Please ask the people to modify the doc/link accordingly. In case they have any questions please ask them to reach out to Tim Eshelman(timesh@microsoft.com).

**Comment by kenwith** [comment]
@wsato and @guillaumecouture - thank you for the details and the link. Updated this to $50 with this Pull Request: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/545

Also, these docs are now open source so anyone can make a Pull Request if you are up for it. This would be a perfect use case. To make an edit you navigate to the source document (Content Source) at top of this thread. I have some basic instructions and a video in the README that shows up at the bottom of the repo here: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness

It is just an option if you are open to it. Otherwise opening an issue here is great too. Thank you for taking the time to nail this down and make the docs accurate. This Pull Request should go live shortly.
