### ISSUE TITLE
Teams Live Events

### ISSUE THREAD

**Issue by JBernklev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4625]
We want to have multiple live video displayed of our presenters in Teams live events. So if we have 6 presenters we can see them all at the same time. Similar to that of Got To Webinar. Is that available?

**Comment by scanum** [comment]
@JBernklev thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
