### ISSUE TITLE
how "Users can override the caller ID policy"?

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4626]
The article says:
"Users can override the caller ID policy: Turn on this setting to let users override the settings in the policy regarding displaying their number to callees or not. This means that users can choose whether to display their caller ID."

Please add a note explaining HOW users can choose whether to display their caller ID.
It is natural to assume that this setting can be changed somewhere within Teams client.
But the only place I found it is https://mysettings.lync.com/lscp/usp/pstncalling

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2b8aefb-f373-fa6e-dd79-e97cded117e8
* Version Independent ID: 2c73f49c-d34f-c1da-648d-8675f10c0183
* Content: [Manage caller ID policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/caller-id-policies)
* Content Source: [Teams/caller-id-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/caller-id-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@shivtorov Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by get-itips** [comment]
Hello @shivtorov thanks for your feedback. Created a pull request to add this information and also update the article based on the current UI.

**Comment by dinocaputo** [comment]
It should be noted that the documentation says "Users can override the CallerID Policy" however the Teams Admin Center has the option labelled as "Override the CallerID Policy" which is very confusing at best.  It makes it sound like its an Administrative override of the User's policy..  Needs to be addressed please.

**Comment by get-itips** [comment]
@scanum PR has been merged and it reflects current UI, we can close this issue now.

**Comment by scanum** [comment]
@dinocaputo Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
