### ISSUE TITLE
MS teams add-in for outlook

### ISSUE THREAD

**Issue by Dippie-WP** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4632]
I read many articles in the community forum none seems to help. 

I cant find the teams add-in for outlook. its not even in the registry. 

MS office 2019- has the latest updates. 
Windows 10- has latest updates
Teams-updated today as well

can you please assist

**Comment by scanum** [comment]
@Dippie-WP thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
