### ISSUE TITLE
Table should be updated to include Local Media Optimization support

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4636]
The table should be updated to include Local Media Optimization support as detailed here https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-media-optimization-configure

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1a1c01-10a9-7f69-1c7b-1a566b0f5112
* Version Independent ID: 329ee759-40fc-98fb-b91e-87786c63024b
* Content: [Session Border Controllers certified for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-border-controllers)
* Content Source: [Teams/direct-routing-border-controllers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-border-controllers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@TorrenManson Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by get-itips** [comment]
Hello @TorrenManson How are you? @CarolynRowe will check with the PM to see if Local Media Optimization information will be included in that table or be kept on the article you included here.
Thank you

**Comment by tiburd** [comment]
@TorrenManson - It looks like a [Local Media Optimization table ](https://docs.microsoft.com/MicrosoftTeams/direct-routing-border-controllers#support-for-local-media-optimization)has been added to the article, so I'm closing this issue.

If your concern still exists, please open a new issue.

Thank you!
