### ISSUE TITLE
Assign a custom app permission policy to users in a group

### ISSUE THREAD

**Issue by mnp3** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4639]
I have tried with both AzureAD and AzureADPreview to assign a custom app permission policy to users in a group (yes I have uninstalled the one I am not using & yes each module has a different connection command-let). So I am able to connect.
I am able to get my requested group with $group = Get-AzureADGroup -SearchString "&lt;"My Group Name"&gt;". I am able to get members of the group with $members = Get-AzureADGroupMember -ObjectId $group.ObjectId -All $true | Where-Object {$_.ObjectType -eq "User"}. However when I try to apply the policy to the group members with $members | ForEach-Object { Grant-CsTeamsAppPermissionPolicy -PolicyName "HR App Permission Policy" -Identity $_.UserPrincipalName}
I get the error:
Grant-CsTeamsAppPermissionPolicy : The term 'Grant-CsTeamsAppPermissionPolicy' is not recognized as 
the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:1 char:29
+ $members | ForEach-Object { Grant-CsTeamsAppPermissionPolicy -PolicyN ...
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Grant-CsTeamsAppPermissionPolicy:String) [], CommandNot 
   FoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Any ideas what I am doing wrong?
Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b51eda6c-168c-7d99-7cc1-992b3d8feef2
* Version Independent ID: 118a1b8f-f4b7-a778-70b1-d3161fc548ab
* Content: [Manage app permission policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-app-permission-policies#feedback)
* Content Source: [Teams/teams-app-permission-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-permission-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by mnp3** [comment]
OK I see that running get-command -module AzureAD does not list Grant-CsTeamsAppPermissionPolicy. So where is it?

**Comment by mnp3** [comment]
Grant-CsTeamsAppPermissionPolicy is part of SkypeForBusiness.
I have downloaded and installed https://www.microsoft.com/en-us/download/details.aspx?id=39366
Import-Module SkypeOnlineConnector
Grant-CsTeamsAppPermissionPolicy is not in this module.
What module do I need to import?

**Comment by scanum** [comment]
@mnp3 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
