### ISSUE TITLE
Mispelled Command

### ISSUE THREAD

**Issue by davidprzywara** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#464]
Under the "Migrating from Office 365 Phone System with on-premises PSTN connectivity via Cloud Connector Edition" section, the "-AllowInternationCalls" is mispelled. It should be "-AllowInternationalCalls"

Grant-CsVoiceRoutingPolicy -PolicyName $NULL -Identity &lt;UPN&gt; 
Set-CsUserPstnSettings -Identity &lt;UPN&gt; -AllowInternationCalls $false -HybridPSTNSite $null

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96b28b6f-66f1-64a1-32ed-f9d6919edb61
* Version Independent ID: 5cc90a72-104d-b4d9-1e82-491a99042162
* Content: [Migrating to Direct Routing](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/migrating-to-direct-routing#feedback)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/migrating-to-direct-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/migrating-to-direct-routing.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by kenwith** [comment]
@davidprzywara - sorry for the delay on this one. This has been fixed and also just a note that the article has moved and is not located here: https://docs.microsoft.com/en-us/microsoftteams/direct-routing-migrating 

Thank you for the feedback. It is greatly appreciated. If you would be interested to submit a Pull Request for any typo or issues you find and get credit in the Contributors for the docs you can find instructions in the README at the bottom of the main repo here: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness  

Or you can just open an Issue and we can fix as well. Whatever you prefer. Thanks again, it is appreciated!
