### ISSUE TITLE
Org-Wide app policies vs Custom permission policies

### ISSUE THREAD

**Issue by AlexanderSaad** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4640]
I find some information on the article contradictory.
On one hand you say that "Org-wide app settings override the global policy and any custom policies that you create and assign to users." and on the other "If you want to control the apps that are available for different groups of users in your organization, create and assign one or more custom app permission policies."
How can the custom policy work if it's overridden by the Org-Wide one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b51eda6c-168c-7d99-7cc1-992b3d8feef2
* Version Independent ID: 118a1b8f-f4b7-a778-70b1-d3161fc548ab
* Content: [Manage app permission policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-app-permission-policies#feedback)
* Content Source: [Teams/teams-app-permission-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-permission-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@AlexanderSaad Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by get-itips** [comment]
Hello @AlexanderSaad How are you?
Hope you are doing good.

I read both sentences and to my understanding and tests in lab, that means that, if for example, in org-wide settings I disable "Allow third-party apps" there will be no posibility to create a custom permission policy with Third party apps:

![image](https://user-images.githubusercontent.com/36666927/80602473-90618080-8a05-11ea-94c7-204dc5b68661.png)

However, if I enable  "Allow third-party apps" I can have a custom app perm policy that can have either allow, allow specific, block specific or blocked, like this:

![image](https://user-images.githubusercontent.com/36666927/80602623-bb4bd480-8a05-11ea-8ed4-1d196e4908a9.png)

Hope this helps you clarify this concept.

**Comment by scanum** [comment]
@get-itips Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
