### ISSUE TITLE
Page is outdated pertaining to limits

### ISSUE THREAD

**Issue by AlexHill90** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4643]
Hi, the limit of 4 hours has been raised to 8. Can this be amended? https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#teams-live-events

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#teams-live-events)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by LolaJacobsen** [comment]
Checking with PM Ashwin Appiah

**Comment by scanum** [comment]
@AlexHill90 Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by joshbrown-wsna** [comment]
Hi  the message we are seeing is that teamlive events can be 16 hours.  Can you please confirm?  Next week we will be using Live Events for an all day conference and want to make sure this is accurate.


<img width="2011" alt="length_TL_Event" src="https://user-images.githubusercontent.com/64213088/80115522-b1276300-8539-11ea-9510-908c1ed8f031.png">

**Comment by get-itips** [comment]
Hello @LolaJacobsen Lola how are you? Were you be able to get feedback from the PM on this? Thanks

**Comment by LolaJacobsen** [comment]
I updated this article with a note about fluctuations in live event limits:
https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams?source=docs#teams-live-events
