### ISSUE TITLE
Clarification over domain for Resource Account

### ISSUE THREAD

**Issue by nick-cloud-maker-ai** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4645]
Hey team,

Under "Create a resource account in Microsoft Teams admin center" where it says under step 1: "To create a new resource account click + Add. In the pop-up, fill out the Display name, Username (the domain name should populate automatically)" it should be specified that the resource account *must* use the &lt;domain&gt;.onmicrosoft.com domain name. It is not possible to use another domain for a resource account as this appears to throw an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts#feedback)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@nick-cloud-maker-ai Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by get-itips** [comment]
Hello @nick-cloud-maker-ai 
I could not reproduce what you are telling me here, to see if we have to impact the documentation.
So I would need to kindly recommend opening a support ticket in your tenant.
Thank you

**Comment by scanum** [comment]
@nick-cloud-maker-ai Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
