### ISSUE TITLE
confusing information

### ISSUE THREAD

**Issue by MohammedAlrozzi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4646]
it is mentioned somewhere that anyone with non-microsoft account can join Teams but then in point 4 it says that they should have a Microsoft account or create a new one. This is confusing and I hope you can change the wording. cheers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 754022e3-49eb-dbd5-e4f5-891c8ebeb491
* Version Independent ID: b73a6f64-d36f-298f-d9ac-34860abad42b
* Content: [How a guest joins a team - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-joins#feedback)
* Content Source: [Teams/guest-joins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-joins.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@MohammedAlrozzi Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by get-itips** [comment]
Hello @MohammedAlrozzi 👍 
How are you? Hope you are doing good.

The first sentence, which is an introduction, says

> Anyone with a business or consumer email account, such as Outlook, Gmail, or others, can participate as a guest in Teams

and then it expands that information saying

> Guest users who have an email address that belongs to an Azure Active Directory or Office 365 work or school account can accept the invitation directly. **If the guest doesn't yet have a Microsoft account associated with their email address, they'll be directed to create one for free.**

The second, more detailed procedure expands the explanation, you will be able to use, for example, your gmail address, you just need to create and associate a Microsoft account with it:

![image](https://user-images.githubusercontent.com/36666927/80741574-3db0c300-8af0-11ea-825a-a583d0944a6e.png)

Hope this helps you.

**Comment by scanum** [comment]
@MohammedAlrozzi Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
