### ISSUE TITLE
Guest name change in AAD not reflected in Teams

### ISSUE THREAD

**Issue by EliWallic** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4648]
Having the issue that after adding an guest to an Team its displayed with the email first part and after editing the guests information in AAD its not updates in Teams.

**Comment by scanum** [comment]
@EliWallic thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
