### ISSUE TITLE
Link loop

### ISSUE THREAD

**Issue by gitralf** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4649]
in paragraph "Compliance Standards", the link in "Details can be found in the ..." in the very last sentence points to the current document, but not to more details. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: ca579d63-182b-d6f5-8777-79248fa27ed9
* Version Independent ID: b4c27d1b-b2f1-41ac-b15c-d12b448a539e
* Content: [Übersicht über Sicherheit und Compliance - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/security-compliance-overview#feedback)
* Content Source: [Teams/security-compliance-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/security-compliance-overview.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@gitralf Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by get-itips** [comment]
Hello @gitralf Ralf,
The link has been updated on this [commit](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/7e93923b31e8b8d38ab97394c0708d45b2ef1757#diff-cc8cbb1c62ab5c36f4e1c8d70551cc68) and it is already on the published version.
Thank for your feedback.

**Comment by scanum** [comment]
@gitralf Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
