### ISSUE TITLE
Clarification about "Who can join scheduled live events"

### ISSUE THREAD

**Issue by AlexanderSaad** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4650]
Could you please clarify what do you mean by "Org-wide permission" in the following sentence: 
"This setting enables the Org-wide permission type in Teams when a user schedules a live event."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9aa4676-855a-fddb-bb0b-96b7095c695e
* Version Independent ID: 7c39f08c-0d56-6d29-1356-879d9d6ff51c
* Content: [Set up for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-live-events/set-up-for-teams-live-events)
* Content Source: [Teams/teams-live-events/set-up-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/set-up-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@AlexanderSaad Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by get-itips** [comment]
Hello @AlexanderSaad How are you ? 👍 

**Org Wide:** _Everyone in your org can watch the live event, including guests._

[Source](https://support.microsoft.com/en-ie/office/schedule-a-teams-live-event-7a9ce97c-e1cd-470f-acaf-e6dfc179a0e2)

Thanks.

**Comment by scanum** [comment]
@AlexanderSaad Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
