### ISSUE TITLE
日本語誤記の修正依頼 E1 試用版ライセンス → E1 Trial license

### ISSUE THREAD

**Issue by keijikomatsu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4651]
以下の誤記を修正お願いいたします。日本語トランスレートで誤記が発生しております。
誤記）この度の特別な E1 試用"板"ライセンスをご用意しています。
正) この度の特別な E1 試用版ライセンスをご用意しています。

ja-jp https://docs.microsoft.com/ja-jp/microsoftteams/e1-trial-license

![キャプチャ](https://user-images.githubusercontent.com/29809532/79977630-8d343500-84d9-11ea-84cd-88bd5ea8a394.PNG)

en-us https://docs.microsoft.com/en-us/microsoftteams/e1-trial-license
![en-us](https://user-images.githubusercontent.com/29809532/79978036-3418d100-84da-11ea-9a55-cc6131c2ef5f.PNG)

_Originally posted by @keijikomatsu in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4488#issuecomment-617727390_

**Comment by scanum** [comment]
@officeglobal Hi! Could you please help with this issue? Thanks

**Comment by scanum** [comment]
@OfficeGlobal Hi! Could you please help with this issue? Thanks

**Comment by scanum** [comment]
@OfficeGlobal Hi! Could you please help with this issue? Thanks

**Comment by OfficeGlobal** [comment]
@keijikomatsu the article was several times updated. Could you please let us know if you see any other error?
Thank you

**Comment by scanum** [comment]
@keijikomatsu We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
