### ISSUE TITLE
Event organiser has "Allow IP Video" set to "off"

### ISSUE THREAD

**Issue by AlexanderSaad** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4652]
Can an event oraniser that has a "Messaging policy" with "Allow IP Video" set to "OFF" still record a live event, if the "Live event policy" setting "Who can record an event" is set to "Always record" or "Oganizer can record"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: becbf3ca-b88c-b033-a145-9a1af201ced3
* Version Independent ID: 41a6a9b5-d3dd-d8c9-9e97-920ff2fd1a24
* Content: [What are Microsoft Teams live events? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/what-are-teams-live-events)
* Content Source: [Teams/teams-live-events/what-are-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/what-are-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@AlexanderSaad thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
