### ISSUE TITLE
The cmdlet is not available

### ISSUE THREAD

**Issue by arifC** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4653]
The cmdlets mentioned in this article are not part of the SfBO Powershell Module. Could you help me finding it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bf3bc26-4cac-56c0-8669-6540adf3c502
* Version Independent ID: bd7cd483-e40e-88c2-b9ee-b21a9ea73005
* Content: [Manage feedback policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-feedback-policies-in-teams)
* Content Source: [Teams/manage-feedback-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-feedback-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@arifC thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
