### ISSUE TITLE
Transfer phone numbers back to local carrier

### ISSUE THREAD

**Issue by c016smith** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4655]
Where would a Microsoft subscriber find all the pertinent billing information to manage a migration of phone number(s) to another carrier? We don't get a traditional "phone bill" from Microsoft in the same way, so who would we talk to if a number needs to be moved back to customer's carrier (or a new carrier), such as when moving from Calling Plan methods to a Direct Routing situation and need to move those numbers to a carrier other than Microsoft?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1829a37-a7a1-4dd1-fde8-82125c593ff1
* Version Independent ID: dfedc4c5-eec4-2137-e975-399866aaafad
* Content: [Transfer phone numbers to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/phone-number-calling-plans/transfer-phone-numbers-to-teams)
* Content Source: [Teams/phone-number-calling-plans/transfer-phone-numbers-to-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phone-number-calling-plans/transfer-phone-numbers-to-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@c016smith thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
