### ISSUE TITLE
What's the difference between two "Office 365 Education for Faculty" SKUs?

### ISSUE THREAD

**Issue by rsoakford** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4656]
The table on https://docs.microsoft.com/en-us/MicrosoftTeams/sku-reference-edu lists:

Plan name 	SkuPartNumber 	SkuID
Office 365 Education for Faculty 	STANDARDWOFFPACK_FACULTY 	94763226-9b3c-4e75-a931-5c89701abe66
Office 365 Education for Faculty 	STANDARDWOFFPACK_IW_FACULTY 	78e66a63-337a-4a9a-8959-41c6654dfb56

SKU 94763226-9b3c-4e75-a931-5c89701abe66 appears as "Office 365 A1 for faculty" in the admin center.
SKU 78e66a63-337a-4a9a-8959-41c6654dfb56 appears as "Office 365 A1 Plus for faculty" in the admin center.

What's the difference between these two SKUs?  Both seem to be free but how can you check eligibility?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae22e4df-3f88-8c54-c55e-a3cd4f720cbc
* Version Independent ID: 3be05aac-9860-e78c-aca7-c62de044c48b
* Content: [Education SKU reference - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/sku-reference-edu)
* Content Source: [Teams/sku-reference-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sku-reference-edu.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@rsoakford thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
