### ISSUE TITLE
SKU e82ae690-a2d5-4d76-8d30-7c6e01e6022e missing from page?

### ISSUE THREAD

**Issue by rsoakford** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4657]
The table on https://docs.microsoft.com/en-us/MicrosoftTeams/sku-reference-edu lists:
314c4481-f395-4525-be8b-2ec4bb1e9d91 which appears in the admin center as "Office 365 A1 for students" and via Get-MsolAccountSku as "STANDARDWOFFPACK_STUDENT".

However, the same page does not list:
e82ae690-a2d5-4d76-8d30-7c6e01e6022e which appears in the admin center as "Office 365 A1 Plus for students" and via Get-MsolAccountSku as "STANDARDWOFFPACK_IW_STUDENT".

Is there a reason the latter SKU is not listed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae22e4df-3f88-8c54-c55e-a3cd4f720cbc
* Version Independent ID: 3be05aac-9860-e78c-aca7-c62de044c48b
* Content: [Education SKU reference - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/sku-reference-edu)
* Content Source: [Teams/sku-reference-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sku-reference-edu.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@rsoakford  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
Hi @rsoakford  Thanks for raising this issue! I will be looking into it!

**Comment by TokyoScarab** [comment]
@LanaChin Would you be able to provide some more detailed insight as to why the SKU mentioned above is omitted in the documentation? I wasn't able to turn up any information on it. So I'm not sure if it was just not included or if there is a specific reason for why it isn't there. Thanks!

**Comment by LanaChin** [comment]
Hi @rsoakford. Thanks for your feedback. the SKU has been added in the linked PR.  Thanks @TokyoScarab.

**Comment by rsoakford** [comment]
I believe the two SKUs are distinct - now it looks as though the page incorrectly refers to 
SkuPartNumber: STANDARDWOFFPACK_IW_STUDENT
SkuID: 314c4481-f395-4525-be8b-2ec4bb1e9d91

However, when I run the Get-MsolAccountSku PowerShell cmdlet on my tenant I see the following:

`SkuId                                SkuPartNumber              
-----                                -------------              
94763226-9b3c-4e75-a931-5c89701abe66 STANDARDWOFFPACK_FACULTY   
78e66a63-337a-4a9a-8959-41c6654dfb56 STANDARDWOFFPACK_IW_FACULTY
e82ae690-a2d5-4d76-8d30-7c6e01e6022e STANDARDWOFFPACK_IW_STUDENT
314c4481-f395-4525-be8b-2ec4bb1e9d91 STANDARDWOFFPACK_STUDENT   
`

As far as I can tell, all four of the above SKUs include the Microsoft Teams servicePlan (see https://docs.microsoft.com/en-us/office365/enterprise/powershell/view-account-license-and-service-details-with-office-365-powershell).

**Comment by benjaminselby** [comment]
Anybody had a chance to track this down? We have a bunch of users in our tennant with licenses having SkuId='e82ae690-a2d5-4d76-8d30-7c6e01e6022e'. I'm probably just going to remove them and replace with the new one but it would be nice to have some explanation as to why this ID has simply disappeared from the internet...
