### ISSUE TITLE
Incomplete Documentation

### ISSUE THREAD

**Issue by dlovitt1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#466]
Spent over 2 full days trying to get this to work.  Once I NOTICED that the CAP provisioning site says it will reset the CAP account's password to a random password, it dawned on me:  From what I can tell, you MUST create the user account in Azure AD (online) ONLY. You can not use an on premise AD user account that is synced to Azure AD.  Tested this theory, and sure enough, I can provision a cloud only CAP account. THIS WOULD BE THE FIRST TIME WE EVER CREATED/USED AN ACCOUNT LIKE THIS (cloud only) and it would have never dawned on me at least, that you could not use a "normal" account that is on prem/synced.  If my assumption is correct,  why wouldn't this article POINT THIS OUT?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81748f38-6f1b-d709-6762-c596950727d4
* Version Independent ID: 440a0a5c-7750-3d84-b358-66d6c116882e
* Content: [Set up Common Area Phones](https://docs.microsoft.com/en-us/skypeforbusiness/what-is-phone-system-in-office-365/getting-phones-for-skype-for-business-online/setting-up-common-area-phones)
* Content Source: [Skype/SfbOnline/what-is-phone-system-in-office-365/getting-phones-for-skype-for-business-online/setting-up-common-area-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/what-is-phone-system-in-office-365/getting-phones-for-skype-for-business-online/setting-up-common-area-phones.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@dlovitt1 - sorry for the long delay on this. Thank you for taking the time to post this information. It is greatly appreciated and I am sorry it stagnated here in the Issues. This is exactly the valuable information that would be ideal to add to the article.

The documents are open source now and if you are open to it you can submit a Pull Request to make updates. You will then show up as a contributor. Or you can open an issue like you did and we can do it as well. Whatever you prefer.

I took a stab at this and added an important note in the article. Here is the Pull Request: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/533

If you decide you would like to submit a Pull Request you can learn how in the README on the main repo here: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness

I will get this Pull Request I submitted reviewed and then merged into the documentation. Thank you very much for sharing your experience!
