### ISSUE TITLE
Where is the list of known issues?

### ISSUE THREAD

**Issue by ddub555** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4660]
Per one of the closed items, it's now being broken up here:
https://docs.microsoft.com/en-us/MicrosoftTeams/troubleshoot/teams

but that link doesn't have any content in the body. yes there are links down the left side, but this is poorly designed. This current page: https://docs.microsoft.com/en-us/MicrosoftTeams/known-issues is labeled "known issues" but contains 'helpful items' and the new page - is it troubleshooting or known issues? there's a difference.

It makes it almost impossible to research a potential issue before submitting to support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/known-issues#feedback)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@ddub555 Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by soleroitsolutionsltd** [comment]
I will have to agree - this is almost comical if it wasn't sold as enterprise-grade

**Comment by get-itips** [comment]
Hello @ddub555 how are you? Hope you are doing great
The article has been improved after you created this issue, did you review it currently?
Thank you

**Comment by scanum** [comment]
@ddub555 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
