### ISSUE TITLE
Microsoft Teams calling plan for Thailand

### ISSUE THREAD

**Issue by voravut77** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4664]
Hello,

I am from Thailand and using MS. Teams. Suppose that the company I am working with is US based, and they assign the Microsoft Teams calling plan to my account in Thailand. They found the error that "Microsoft does not offer end user phone numbers for Thailand. The numbers offered are: Call queue (Toll) & Auto attendant (Toll) for phone systems and Dedicated conference bridge (Toll) numbers." however, when I go to MS. Teams on my mobile > go to dial pad > it shows that your number is "+66 2 657 5911" but it cannot be used to pick up and dial in anymore.

My question is will Microsoft implement this calling plan function for Thailand in the near future ? If so, do you know when should we get it in Thailand ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b07cfcf-8f31-91ed-b1de-c7826a1ab91d
* Version Independent ID: dfbc4212-8f47-326a-f872-8186a915ae1e
* Content: [Country/region availability - Audio Conferencing, Calling Plans - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans#feedback)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@voravut77 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
