### ISSUE TITLE
If 64 bit Windows but 32 bit Office (because that was the longstanding advice), then 32 bit or 64 bit Teams

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4665]
If I have 64 bit Windows, then I suppose I should install 64 bit Teams.
But I have 32 bit Office 365 ProPlus, because up until last year this was the recommended option and the default.  Let's assume I didn't install Teams with Office.
Should I use 32 bit Teams or 64 bit Teams?  Teams adds extensions to Office, so I don't know.  This page doesn't offer any guidance either.  

What should I do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Teams using Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by anwarmahmood1** [comment]
It seems that 64 bit Teams integrates fine with 32 bit Office (maybe 64 bit Teams contains both 32 bit and 64 bit addins for Teams?)

Anyway, would be helpful to clarify here.

**Comment by scanum** [comment]
@anwarmahmood1 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by anwarmahmood1** [comment]
I just *GAVE* you the resolution! You can add "Use Teams 64-bit with Windows 64-bit. If you have Microsoft Office 365 ProPlus installed as well, Teams 64-bit will integrate with both 32-bit or 64-bit editions of Microsoft Office 365 ProPlus."
________________________________
