### ISSUE TITLE
Porting out from Teams is missing

### ISSUE THREAD

**Issue by KristofferCF** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4666]
That section seems to have been removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a17293e0-4c49-0e97-d5da-b48322f10928
* Version Independent ID: c38c0726-5dec-d374-6948-2188d43025ef
* Content: [What's a port order? - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/phone-number-calling-plans/port-order-overview#feedback)
* Content Source: [Teams/phone-number-calling-plans/port-order-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phone-number-calling-plans/port-order-overview.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@KristofferCF Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @KristofferCF How are you? I could review the history of the article and you are right, there was in the past a section about it, if it was removed, probably that is not offered anymore but I am not sure, I suggest you contact the [PSTN Service Desk](https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk)

**Comment by scanum** [comment]
@KristofferCF  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
