### ISSUE TITLE
 Microsoft Teams Activity Reports API

### ISSUE THREAD

**Issue by wouterfovel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4667]
Hi,

concerning Microsoft Teams Activity Reports (like user activity report, ...).
Currently, in the Teams Admin center, you can generate these - and export to csv.
However, we would like to interpret this data - make an analysis what teams do over time .... .
Are there plans to put this team analytics data behind an API ?
If not, would it somehow be possible to get this data in an automated way?

many thanks,
bye,
Wouter
CTO HumanReef

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b138331-2f10-a05d-7e88-68e62e0b3e4f
* Version Independent ID: f923b648-ffe4-8a8a-c189-6e31f1032c10
* Content: [Microsoft Teams usage report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-usage-report#related-topics)
* Content Source: [Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@wouterfovel thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
