### ISSUE TITLE
No Procedure for Finding **Select Exchange UM Auto Attendant** Dialog Box

### ISSUE THREAD

**Issue by durffy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#467]
in OfficeDocs-SkypeForBusiness/Skype/SfbServer/help-topics/help-lscp/select-exchange-um-auto-attendant.md it is unclear how to access the **Select Exchange UM Auto Attendant** dialog box. It assumes the reader knows where to look.

**Comment by kenwith** [comment]
@durffy - thank you for providing feedback and sorry for the delay. These topics in the help-topics folder appear in the product. So normally the way people will get to them is when they are on the dialog there will be a little ? mark and clicking that icon will open the help page for the dialog the person is on. Hope that answers your question. Please re-open if necessary.
