### ISSUE TITLE
PS Variables

### ISSUE THREAD

**Issue by R4D10Active** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4677]
So many undefined variables in the examples makes it hard to copy paste examples. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Microsoft 365 or Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/with-office-365#feedback)
* Content Source: [Teams/rooms/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-office-365.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@R4D10Active Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by danmyhre** [comment]
This is one example:
Enable-CsMeetingRoom -Identity $rm -RegistrarPool "sippoolbl20a04.infra.lync.com" -SipAddressType EmailAddress

There is no $rm variable defined.

**Comment by get-itips** [comment]
Thanks for reporting @R4D10Active @danmyhre a fix is on the way.

**Comment by scanum** [comment]
@danmyhre We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
