### ISSUE TITLE
Teams Rooms in GCC-High

### ISSUE THREAD

**Issue by Difladrmaus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4682]
"Microsoft Teams Rooms is not supported in Office 365 operated by 21Vianet, or in GCC-High, or DoD environments."

Any update on if/when?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf01435-a73b-4bf2-5845-e4cf50c4c3a2
* Version Independent ID: 166e1800-80b1-2496-7160-3040c5b23c3d
* Content: [Microsoft Teams Rooms requirements - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/requirements)
* Content Source: [Teams/rooms/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/requirements.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Difladrmaus Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Difladrmaus We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
