### ISSUE TITLE
Teams: Error when attempting to show a channel

### ISSUE THREAD

**Issue by goldengun** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4683]
Hello, 

We are having an issue with Microsoft Teams where we get an error when we attempt to show a channel in a Team. 
The channels are set as Hidden, clicking the link opens a list of channels where I can click 'Show' on one of them:
![image](https://user-images.githubusercontent.com/36398292/80149810-1f851900-856c-11ea-8397-f6563f9b91b0.png)

However when 'Show' is clicked, Teams throws the following error: "Couldn't show [channel name]. Try again."
![image](https://user-images.githubusercontent.com/36398292/80149864-3af02400-856c-11ea-94f4-3980822b853b.png)

I have 'Owner' permission for this team, and yet even when the "Automatically show this channel in everyone's channel list' is checked during channel creation (or anytime thereafter), it still shows as 'Hidden'
![image](https://user-images.githubusercontent.com/36398292/80149957-607d2d80-856c-11ea-8727-f4bbcce45db7.png)

The channel is also set to 'Show for all members', and yet when I attempt to click the box under 'Show for me', the checkmark is immediately removed and I get the same "Couldn't show [channel]. Try again." error. As you can also see, this is NOT a Private Channel either. 
![image](https://user-images.githubusercontent.com/36398292/80150461-4e4fbf00-856d-11ea-8f8d-037c7eb48ba4.png)

For background, we're using Microsoft 365 and Sharepoint Online on the Microsoft Government Cloud on Windows 10 (1909). Rebooting and Signing out/in of Teams does not help, and all our members are experiencing this issue.

**Comment by goldengun** [comment]
Whoops. Looks Like I need to find the github for Teams. Issue closed.

**Comment by scanum** [comment]
@goldengun thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
