### ISSUE TITLE
Contact address for SBC certification does not work

### ISSUE THREAD

**Issue by henningw** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4688]
Hello, 
the mentioned contact address for the SBC certification programm "drsbccertification@microsoft.com" does not work. Error: "550 5.4.1 Recipient address rejected: Access denied."
Please review and update the page with a working address.
Thanks and Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1a1c01-10a9-7f69-1c7b-1a566b0f5112
* Version Independent ID: 329ee759-40fc-98fb-b91e-87786c63024b
* Content: [Session Border Controllers certified for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-border-controllers#feedback)
* Content Source: [Teams/direct-routing-border-controllers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-border-controllers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@henningw Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @henningw, thank you for your feedback.

Seems to be working for me. Could you double-check it with your Mail Server administrator and/or try to send a new email?

Thanks!

**Comment by scanum** [comment]
@henningw We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
