### ISSUE TITLE
Starting a Screen Share slows downs machine into an unusable state

### ISSUE THREAD

**Issue by ctkjose** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4694]
MacOS Catalina 10.15.3
Model Name:	MacBook Pro
Processor Name:	Quad-Core Intel Core i7
Processor Speed:	2.6 GHz
Memory:	16 GB

Using teams on browser with Chrome Version 81.0.4044.122.

I started participating on meetings with TEAM as required by a job.

When I share my screen interacting with chrome becomes extremely sluggish with "spinning beach balls", the longer the screen share is active the worst the situation gets and then other apps including the finder soon start to crawl and become fairly unusable.

After stopping the screen share situation improves a little but still too sluggish to the point that I have to quit chrome.

As long as i dont share a screen things are fine.

Never had this experience in Google Meet with many more participants.

**Comment by ctkjose** [comment]
noticed today that network was bit slower than usual (usual bottlenecks of the provider due to covid19 usage spikes), but still over had over 20mbs from the regular avg of 70mbs, yet I was able to continue with other meetings in google meet without issues during the whole day.

**Comment by scanum** [comment]
@ctkjose thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
