### ISSUE TITLE
two different success kits

### ISSUE THREAD

**Issue by khilker15** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4697]
The Teams Customer success kit on this page, and the one found on the link below don't match.  
https://www.microsoft.com/en-us/download/details.aspx?id=54244

These two sites should point to the same ZIP file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 377ed460-94ef-6528-63de-87360156b71e
* Version Independent ID: 56e32c63-dadb-fb81-c04e-6cf396963f2d
* Content: [Tools & workshops - Plan, deliver, & adopt Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/planning-workshop-practical-guide#feedback)
* Content Source: [Teams/planning-workshop-practical-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/planning-workshop-practical-guide.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@khilker15 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by MaratMussabekov** [comment]
Hello @khilker15 ,
The file from this article should be used, as it is the latest one.
There is no update required for the article.
The file on the download center should be updated, however, it is out of the scope of this forum.
Dear @scanum, could you please advise, is there a way we can communicate someone from [Download center](https://www.microsoft.com/en-us/download/default.aspx)?

Thank you

**Comment by scanum** [comment]
@LolaJacobsen Hi Lola, wondering if you could guide us on the right direction to contact someone from the download center? Thanks.

**Comment by LolaJacobsen** [comment]
@karuanag can you confirm which link is the latest? I'll update content to make sure we're no longer referencing the old one.

**Comment by LolaJacobsen** [comment]
@karuanag  I updated all links to the download center (outdated) success kit to https://aka.ms/TeamsCustomerSuccess (changes going live tomorrow morning).

**Comment by khilker15** [comment]
Thanks for closing this out!

Ken Hilker - Microsoft
Sr. Customer Success Manager – FSI Modern Workplace

[See the source image]<https://teams.microsoft.com/l/chat/0/0?users=Kehilker@microsoft.com> Chat with me<https://teams.microsoft.com/l/chat/0/0?users=kehilker@microsoft.com> on Microsoft Teams!
