### ISSUE TITLE
Conflicting Information

### ISSUE THREAD

**Issue by JeffBrownTech** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4698]
Two statement on this page seem to be in conflict. After initial configuration, can the device have a static IP address? Under item 2 in "Preparing Your Environment":

It must be able to receive an IP address using DHCP. (Microsoft Teams Rooms cannot be configured with a static IP address at the first unit startup, but afterwards static IP for the device could be configured on the device or on the upstream switch or router.)

But then under "Check Network Availability":

Access to a server that can provide an IP address using DHCP. Microsoft Teams Rooms cannot be configured with a static IP address.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a711c07e-10b3-baf0-b92c-9dbcf6ab9474
* Version Independent ID: 2038cd48-44b1-1ed1-6e50-48290eef5605
* Content: [Prepare your Environment - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-prep)
* Content Source: [Teams/rooms/rooms-prep.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-prep.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@JeffBrownTech Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@JeffBrownTech  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
