### ISSUE TITLE
Add link to how to see what policies are applied to a user

### ISSUE THREAD

**Issue by karuanag** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4699]
To complete this scenario ITPro's need to know how to validate what settings have been applied to individual or groups of users.  If we have a page we should link it here and if we don't we should add it. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d51bb7b1-801e-6801-dcaf-afa3e38e6941
* Version Independent ID: d8e726a1-cbf2-53c7-da4d-cc155b48612b
* Content: [Manage custom app policies and settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-custom-app-policies-and-settings#feedback)
* Content Source: [Teams/teams-custom-app-policies-and-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-custom-app-policies-and-settings.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@karuanag Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@jdmartinez36  Thanks for raising this issue! I will be looking into it!

**Comment by scanum** [comment]
@TokyoScarab Any updates here? Thanks!

**Comment by TokyoScarab** [comment]
@karuanag Does [this page](https://docs.microsoft.com/microsoftteams/assign-policies) help with what you're looking for?

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
