### ISSUE TITLE
Inaccurate statement re. hybrid

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4702]
Ref. this issue: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4479.
Hybrid is not strictly required except to provide interoperability for calls and chat when migrating to Teams Only mode. In every other mode there is no interoperability.
In cases where an Edge service already exists, it is trivial to create a hybrid. But in cases where no Edge service exists (e.g. no SfB edge server, no dmz domain controller) it is not necessary to build one unless this interoperability is required.
For example, if you start with everyone in Meetings First mode, then switch everyone to Teams Only, there is no need to implement a hybrid. It is not, therefore, the necessary first step (second sentence).

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c0ab608-c57e-0e72-6071-5fc02cf6217c
* Version Independent ID: 73c13bf0-4247-ad87-e3be-7d9a59ab457e
* Content: [Plan hybrid connect - Skype for Business Hybrid](https://docs.microsoft.com/en-gb/skypeforbusiness/hybrid/plan-hybrid-connectivity?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json)
* Content Source: [Skype/SfbHybrid/hybrid/plan-hybrid-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/plan-hybrid-connectivity.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Air-Git thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Air-Git** [comment]
@VLG17 Ref [this issue](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4479).
I suggest amending the second sentence of the article.
