### ISSUE TITLE
Please add information about requirements to get "Show background effects"

### ISSUE THREAD

**Issue by stefanseeger** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4705]
My PC is having enough ram and is supporting AVX2 but still I cannot get the "show background effects". While blur background is still working.
I'm on version 1.3.00.9267 (64-bit).

So I guess there are other requirements which are not mentioned.

Best regards,
Stefan

**Comment by scanum** [comment]
@stefanseeger thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
