### ISSUE TITLE
Porting numbers to Teams

### ISSUE THREAD

**Issue by jndbpm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4706]
What are the costs associated with using Teams for conference calling? We currently have AT&T conference calling and use it for international toll-free dial-in as well. We'd like to port the conference calling numbers to Teams to make it easier to set up conference calls and if it is more cost effective.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1829a37-a7a1-4dd1-fde8-82125c593ff1
* Version Independent ID: dfedc4c5-eec4-2137-e975-399866aaafad
* Content: [Transfer phone numbers to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/phone-number-calling-plans/transfer-phone-numbers-to-teams)
* Content Source: [Teams/phone-number-calling-plans/transfer-phone-numbers-to-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phone-number-calling-plans/transfer-phone-numbers-to-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@jndbpm thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
