### ISSUE TITLE
Where is Live Event?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4707]
Hi,

I came to this page from page:
[Set up for live events in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/set-up-for-teams-live-events)
But on this page have nothing about Live Event. As those bandwidth scenarios does not fits to Live Event. So would be nice to see some guidelines for Live Events as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d996cf7-9f48-2b30-7759-afaf3fe82caa
* Version Independent ID: 24dd6cdf-d35f-53b2-06c2-0a27891825d4
* Content: [Prepare your organization's network for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/prepare-network)
* Content Source: [Teams/prepare-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/prepare-network.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Petri-X  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LolaJacobsen** [comment]
@BryanNyce what should we add WRT live event bandwidth?

**Comment by LolaJacobsen** [comment]
Pinged both Ashwin Appiah and Bryan Nyce today.

**Comment by tiburd** [comment]
Hi, @Petri-X ,

[This article](https://docs.microsoft.com/microsoftteams/teams-live-events/set-up-for-teams-live-events) has been updated and appears to now include bandwidth information for live events, so I'm closing this issue. 

If your concern isn't addressed in the updated article, please open a new issue.

Thank you!
