### ISSUE TITLE
Base license requirement

### ISSUE THREAD

**Issue by dumblerod** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4708]
I see you have Microsoft 365 Business listed as a requirement.  Should this be Microsoft 365 Business Premium instead?  This link: https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-business-voice-service-description references MS365 Business Premium.  I think maybe this didn't get updated after recent license naming change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35057f71-792b-a4e2-a2ee-a4908c11f3a4
* Version Independent ID: 7e23f067-1dcd-16f0-3f9a-ff8d13c1f659
* Content: [What is Microsoft 365 Business Voice? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/business-voice/whats-business-voice)
* Content Source: [Teams/business-voice/whats-business-voice.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/business-voice/whats-business-voice.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@dumblerod thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
