### ISSUE TITLE
Current available MSIs install to Program Files (x86) on 64bit OS

### ISSUE THREAD

**Issue by beskurrd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#471]
Both the x86 and x64 installs target "Program Files (x86)" on 64 bit Windows 7 and 10 and the registry run always winds up in "HKLM\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Run" with a value of "%ProgramFiles%\Teams Installer\Teams.exe --checkInstall --source=default" resulting in nothing happening on user logons.

**Comment by kenwith** [comment]
@beskurrd -  I am not sure on this one but want to make sure this gets resolved for you ASAP. Would you please open a service request in your tenant admin? Here is a quick video: https://www.youtube.com/watch?v=puuOy0sEg1Y

They will be able to escalate this to make sure this is resolved. Thank you for reporting!
