### ISSUE TITLE
Information regarding auto-update is unclear

### ISSUE THREAD

**Issue by JBHorne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4712]
The description above states, "Do not use the MSI to deploy updates, because the client will auto update when it detects a new version is available from the service. To re-deploy the latest installer use the process of redeploying MSI described below. If you deploy an older version of the MSI package, the client will auto-update (except in VDI environments) when possible for the user. If a very old version gets deployed, the MSI will trigger an app update before the user is able to use Teams."

This is confusing as the first sentence implies that Teams will auto-update after using the MSI. However, the third sentence states "except in VDI environments" which implies that the auto-update feature will not work within VDI.

I personally have not found auto-update to work in our environment and receive the error "Sorry, updating has been disabled for this version of Microsoft Teams".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Teams using Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment#feedback)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@JBHorne  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @JBHorne, thank you for your feedback.

Please, provide more detail as it´s not clear for me how you think we can improve this paragraph. Summary: "You shouldn´t use the MSI to update the client as It will be auto-updated, except in VDI environments".

More information about VDI environments:
https://docs.microsoft.com/microsoftteams/teams-for-vdi
If you are using VDI, you should check the update section in this article.

**Comment by JBHorne** [comment]
> Hi @JBHorne, thank you for your feedback.
> 
> Please, provide more detail as it´s not clear for me how you think we can improve this paragraph. Summary: "You shouldn´t use the MSI to update the client as It will be auto-updated, except in VDI environments".
> 
> More information about VDI environments:
> https://docs.microsoft.com/microsoftteams/teams-for-vdi
> If you are using VDI, you should check the update section in this article.

Hi @dariomws, my experience has been the MSI does not auto-update at all. You can click Update and it will say it completed, but it does nothing. The only way to update the MSI is to go back and download a new MSI, which is hopefully a later version, but you don't know this until after you install as there is no version numbers provided with the MSI. Whether this is an issue with the documentation or product, it's not at all streamlined to update VDI environments to the latest versions, especially considering the MSIs are not kept current.

**Comment by dariomws** [comment]
Hi @JBHorne, this article send you to the following article to install or update Teams in VDI environments:
https://docs.microsoft.com/microsoftteams/teams-for-vdi#install-or-update-the-teams-desktop-app-on-vdi
Here you can see this sentence:
"With per-machine installation, automatic updates is disabled. This means that to update the Teams app, you must uninstall the current version to update to a newer version. With per-user installation, automatic updates is enabled. For most VDI deployments, we recommend you deploy Teams using per-machine installation."

**Comment by stormlights** [comment]
@dariomws 

"https://docs.microsoft.com/microsoftteams/teams-for-vdi
If you are using VDI, you should check the update section in this article"

That would be correct if the VDI article actually updated its download link to the latest version of the MSI.  However, they don't and they are about 3 versions behind on what you can download manually. However, you wouldn't know that because they don't put the version numbers on the download link.

**Comment by scanum** [comment]
@JBHorne  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
