### ISSUE TITLE
MSI Update is Behind

### ISSUE THREAD

**Issue by JBHorne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4713]
Teams has already released 1.3.00.9267, however the latest MSI is only 1.3.00.8663. It would be appreciated if the MSI was kept up-to-date and released alongside the standard auto-update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@JBHorne  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by stormlights** [comment]
Its actually worse then that. If you look above in the VDI section it still has the link to download point to 1.3.00.4461.  However, you would now that because there is no version number next to it. Please keep your versions up to date in your links and please put version numbers in plain site.

**Comment by stormlights** [comment]
Eidt above: However, you would NOT  that because there is no version number next to it. Please keep your versions up to date in your links and please put version numbers in plain site.

**Comment by associa0** [comment]
Can a list of new features, fixed issues and known issues be provided for each version?

**Comment by stormlights** [comment]
Still an issue.  were up to 1.3.0.12508 while the link on this page is outdated

**Comment by scanum** [comment]
@JBHorne  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
