### ISSUE TITLE
MSI version isn't kept up-to-date

### ISSUE THREAD

**Issue by JBHorne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4714]
Teams has already released 1.3.00.9267, however the latest MSI is only 1.3.00.8663. It would be appreciated if the MSI was kept up-to-date and released alongside the standard auto-update. Cross posting as I'm not sure which article would be best to cover this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6da28da-eb7b-d3ae-4c2f-8f87803b1830
* Version Independent ID: 8c42d7a2-80c6-86dd-347a-ed6d8d909c41
* Content: [Teams updates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-client-update)
* Content Source: [Teams/teams-client-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-client-update.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
Duplicate
