### ISSUE TITLE
Invited GMail B2B Guests are unable to log-in using welcome email message link

### ISSUE THREAD

**Issue by jhernandez212** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4716]
When a GMail user is invited to join a Team in a tenant that has Google as an identity provider for b2b (https://docs.microsoft.com/en-us/azure/active-directory/b2b/google-federation) they are unable to login via the link provided in the invitation email or via https://teams.microsoft.com.  The login behavior before was to redirect the login to Google.  Now it just prompts the guest for logon.live.com password.  The only work around is using the url with the tenant id specified ex: `https://teams.microsoft.com/l/team/?<tenantid>`  Is there anyway to correct this behavior or modify the invitation emails so that it includes the tenantid?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [What the guest experience is like - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-experience#feedback)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@jhernandez212 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
