### ISSUE TITLE
The $4/mo Fee for Audio Conferencing Covers all Toll-Based Dial-In Calls to Microsoft Teams Meetings

### ISSUE THREAD

**Issue by SuperMJT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4718]
When participants use a toll number to dial-in to a Microsoft Teams meeting, is it correct that there is no additional per-minute fee applied in most cases?  Can you clarify when per-minute charges apply?  Perhaps a statement like, "Audio Conferencing in Microsoft 365 includes unlimited dial-in minutes for your participants to connect to Microsoft Teams meetings using toll numbers, except in the following cases . . ."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e640245-6d25-2165-3792-9bb386a73184
* Version Independent ID: 28951938-7e00-16fd-c216-a569ba94b041
* Content: [Audio Conferencing in Microsoft 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-in-office-365#feedback)
* Content Source: [Teams/audio-conferencing-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-in-office-365.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@SuperMJT thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
