### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by deontaljard** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#472]
Are all of these Upgrade modes available yet?  We only have Island Mode and Skype only Mode available in our Tenant.  Ideally I'd like to test "Teams only" mode as we seem to missing messages sent via Skype to Teams - they arrive as missed Skype messages via mail.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 006dc464-2228-0d91-8726-223770c91411
* Version Independent ID: 28877a22-b558-4da6-551b-9bcd9bac96c4
* Content: [Understand coexistence and upgrade journey for Skype for Business and Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/upgrade-and-coexistence-of-skypeforbusiness-and-teams)
* Content Source: [Teams/upgrade-and-coexistence-of-skypeforbusiness-and-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-and-coexistence-of-skypeforbusiness-and-teams.md)
* Service: **msteams**
* GitHub Login: @arachmanGitHub
* Microsoft Alias: **MyAdvisor**

**Comment by arachmanGitHub** [comment]
hi @deontaljard, the Teams only mode is currently only available to TAP customers. While you can configure TeamsUpgradePolicy and TeamsInteropPolicy via PowerShell to simulate Teams only mode, there are other dependencies to make the experience that you're looking for. Once Teams only mode is available in the new admin portal, that's when everything should work as expected.
