### ISSUE TITLE
Question of the "First Person"

### ISSUE THREAD

**Issue by motorokr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4722]
Someone from my organization has signed up the Teams Free. We do not who did that.

1. How or who from Microsoft can tells me how to contact my is my organization "Frist Pesrson"

2. Can we reclaim the Admin rights from the "First Person"? He/She is not the authorize personnel to manage the Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9cf9c6a-ae69-3bf6-9123-0d5b24c63c8c
* Version Independent ID: 3becb7ac-cddf-01f8-cf48-114b4771dc3f
* Content: [Manage the free version of Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-freemium#feedback)
* Content Source: [Teams/manage-freemium.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-freemium.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@motorokr thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
