### ISSUE TITLE
Microsoft Teams: sending `text <data>` and i got only `text`, `<data>` stripped

### ISSUE THREAD

**Issue by v-shant** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4723]
when I am sending data something like `text <data>` i received only `text ` (test only in chat not in the channel because it's working when you will run `@Bot text <data>`) 

context activity without mentioning bot

```
"_activity": {
    "text": "text <data>",
    "textFormat": "plain",
    "type": "message",
```

context activity when mentioning bot

```
"_activity": {
    "text": "<at>vishant-bot</at> C<data>\n",
    "textFormat": "plain",
    "attachments": [
      {
        "contentType": "text/html",
        "content": "<div><div><span itemscope=\"\" itemtype=\"http://schema.skype.com/Mention\" itemid=\"0\">vishant-bot</span>&nbsp;text &lt;data&gt;</div>\n</div>"
      }
    ],
    "type": "message",
```

**Comment by scanum** [comment]
@v-shant thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
