### ISSUE TITLE
SfB* modes Presence

### ISSUE THREAD

**Issue by microsoftsearch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4725]
I have opened a support ticket and this segment appears to be inaccurate. "If a user is in any of the SfB* modes (SfbOnly, SfbWithTeamsCollab, SfbWithTeamsCollabAndMeetings), then any other user (whether in Teams or Skype for Business) will see that SfB* user's Skype for Business presence." This does not appear to be the case for the presence of user's who are in SFB Collab modes but are hosted on-prem Skype. The only user's who see a Teams presence for these users appears to be Teams Only users. Can this be updated to reflect that fact?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169a20a6-ebf7-1093-3cb1-fb438b9b7e13
* Version Independent ID: b2074fd8-724e-75fa-bafb-a0f7966bf593
* Content: [Coexistence with Skype for Business - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/coexistence-chat-calls-presence#feedback)
* Content Source: [Teams/coexistence-chat-calls-presence.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/coexistence-chat-calls-presence.md)
* Service: **msteams**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@microsoftsearch Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by microsoftsearch** [comment]
Is there any update regarding this feature?

**Comment by lindspea** [comment]
@microsoftsearch thank you for pointing this out and helping improve MS Docs. Please have a look at this article and let me know if it helps at all or if there is a statement that still needs to be changed in this article as per your suggestion.https://docs.microsoft.com/microsoftteams/teams-skype-interop

**Comment by scanum** [comment]
@microsoftsearch We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you
