### ISSUE TITLE
Cannot copy Private Channels when copying a Team

### ISSUE THREAD

**Issue by jolleymd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4726]
It appears that when I copy a team that includes private channels, only the public ones copy over to the new team. Allowing Team owners to copy private channels would aid with setting up teams for virtual instructor led training where there are prebuilt privte student channels so we can then just add one student to each channel for conversations and meetings with individual students. 

Assuming this is a true limitation, this document should reflect this limitation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels?source=docs#feedback)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@jolleymd Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@jolleymd  Thanks for raising this issue! I will be looking into it!

**Comment by TokyoScarab** [comment]
@jolleymd At the moment,  copying a team does not carry over private channels within that team. If you want, you can put in a suggestion for this in the UserVoice for Microsoft Teams located [here](https://microsoftteams.uservoice.com/). I will make a note of this in the documentation.

**Comment by LanaChin** [comment]
Thanks @jolleymd. The documentation has been updated to reflect this.
