### ISSUE TITLE
Missing definition for "Total Audio Steam Duration (Minutes)"

### ISSUE THREAD

**Issue by aamillerMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4727]
Missing definition for "Total Audio Steam Duration (Minutes)"

**Comment by scanum** [comment]
@aamillerMSFT Thank you for your feedback, it is much appreciated. Could you please link the documentation you are referring to? Thanks!

**Comment by aamillerMSFT** [comment]
https://docs.microsoft.com/en-us/microsoftteams/dimensions-and-measures-available-in-call-quality-dashboard

odd that it didn't add it.

**Comment by get-itips** [comment]
Thanks for your feedback @aamillerMSFT

**Comment by scanum** [comment]
@aamillerMSFT Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
