### ISSUE TITLE
Guest user shown with role Member instead Guest

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4728]
# Invite Guest User via Azure AD vs. Teams admin center
## Invite Guest User via Azure AD admin center
I added a new Guest User in the Azure AD admin center and added a group membership in a Teams-enabled Office 365 group in my invitation.

In Microsoft Teams, when I click on **Manage Team** the Guest User is shown with Role **Guest**
The **Manage Team** section **shows notification** "This team has guests."
**_This is the intended behavior_**

## Invite Guest User via Teams admin center
I added a new Guest User in the Azure AD admin center. After the guest user redeemed the invitation, I added this guest user to another Teams via the Microsoft Teams admin center.
 
In Microsoft Teams, when I click on **Manage Team** the Guest User is shown with Role **Member**
The **Manage Team** section **shows _no_ notification**.

# Error investigation
So I went along and double-checked the role of the Guest User in both Teams. The role is stated as "Guest" in both Teams:
```powershell
PS C:\Users> Get-TeamUser -GroupId <GroupId1> -Role Guest # CRM Task Force

Get-TeamUser -GroupId <GroupId2> -Role Guest # O_DAS_DE_DRS_PRO_Dyn365-Cases

UserId                               User                                          Name                                            Role 
------                               ----                                          ----                                            ---- 
<UserId> <User> <Name> guest
<UserId> <User> <Name> guest
```
Any idea how to resolve this issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93906e31-cd28-702d-bb7e-fcc2529df363
* Version Independent ID: afe4d6ed-cdcb-77e0-0951-f3c69e2463e1
* Content: [Add a guest to a team - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/add-guests)
* Content Source: [Teams/add-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/add-guests.md)
* Service: **msteams**
* GitHub Login: @somakbhattacharyya
* Microsoft Alias: **sbhatta**

**Comment by scanum** [comment]
@Markus-Hanisch thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
