### ISSUE TITLE
What is the standard terms?

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#473]
The caution box says:
"Beginning July 1, 2018, all Office 365 Audio Conferencing subscriptions will revert to the standard service terms for dial out from meetings organized by users with Office 365 Audio Conferencing licenses assigned"
Considering this is only a week away it would be good to understand what the standard service terms for dial-out are!
Can you add a link please as the "related topic" link doesn't really clarify what will happen to "Audio Conferencing" users once the promo period ends

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f88e0003-7ac5-280c-838a-4a5d25e84d7b
* Version Independent ID: ec424409-5993-5505-3452-aad407c22118
* Content: [Complimentary dial-out period](https://docs.microsoft.com/en-us/skypeforbusiness/legal-and-regulatory/complimentary-dial-out-period)
* Content Source: [Skype/SfbOnline/legal-and-regulatory/complimentary-dial-out-period.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/legal-and-regulatory/complimentary-dial-out-period.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@thommck - thank you for this feedback. I will try to get this tracked down. @tonysmit do you know what the note is referring? It is the last note in the article above. Thanks.

**Comment by uc2goDIK** [comment]
Hi 
Any update on this? - What the standard service terms for dial-out are since July 1, 2018?

**Comment by tonysmit** [comment]
Let me check i to this.

**Comment by uc2goDIK** [comment]
Hi Tony, Could you get any further information? BR Dietmar

**Comment by tonysmit** [comment]
@allancar - do we need to update this? Thanks, Tony

**Comment by bedwell84** [comment]
Yes please update the terms, thanks

**Comment by kenwith** [comment]
I was able to get this into the backlog for the Teams/Skype team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.
