### ISSUE TITLE
How to run this script?

### ISSUE THREAD

**Issue by M365-DenzilFernandes** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4730]
Is this script run at every user's login? Or Is this a one time set it and forget it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d253abb0-bf14-6ea1-a6b2-dc3896b44547
* Version Independent ID: d687eed7-6b46-67a7-b47e-fecbb6adf292
* Content: [PowerShell script sample - Reset the autostart setting in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/scripts/powershell-script-teams-reset-autostart#feedback)
* Content Source: [Teams/scripts/powershell-script-teams-reset-autostart.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/scripts/powershell-script-teams-reset-autostart.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@M365-DenzilFernandes thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by GrindeHval** [comment]
Did you get an answer?
My guess is you could leave this in place because it only resets the settings related to auto start.

**Comment by M365-DenzilFernandes** [comment]
> Did you get an answer?
> My guess is you could leave this in place because it only resets the settings related to auto start.
> 
> edit; i did some testing and it looks like it is required to run every time the user logs in.
> In my test (Server 2019) I had it running 1 min after logon.
> Result; Teams didn't autostart.
> If I removed the script teams would auto start again.
> 
> Note that this script remove the link for creating Teams Meetings in outlook. If you uncomment nomber 5. "...Outlook\Addins\TeamsAddin...." The addin stays in place and Teams won't auto start.

I havent yet deployed this. We went down the desktop-json file route
