### ISSUE TITLE
Teams Gifs Vulnerability 2020

### ISSUE THREAD

**Issue by jose-lima2011** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4731]
Hello guys, I would like to take a question, I realized that the document is recent, on several sites Teams' vulnerability was reported regarding malicious gifs, I didn't find any official statement from microsoft regarding there is any public channel with this disclosure, solution, mitigation?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: f34f3188-0af5-f972-9d28-959f5f7866a2
* Version Independent ID: fab26e11-a729-92a4-3ea6-8668dca55dd0
* Content: [Gerenciar políticas de mensagens no Teams - Microsoft Teams](https://docs.microsoft.com/pt-br/microsoftteams/messaging-policies-in-teams)
* Content Source: [Teams/messaging-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/messaging-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@jose-lima2011 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jose-lima2011** [comment]
thanks but that was not the answer I was looking for I will have to rely on third party information that the problem has been solved.
