### ISSUE TITLE
Device buttons stopped working in latest Teams release

### ISSUE THREAD

**Issue by Bug-10** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4732]
Previous behavior: Buttons on device could answer calls, end calls, mute/unmute both from Teams and device (status was synched between app and device)
Post release behavior: Device only works as microphone/camera, no interaction between buttons and app.

Logitech BCC950
Jabra PHS002W
Upgraded firmware on devices, no improvement.

**Comment by scanum** [comment]
@Bug-10 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
