### ISSUE TITLE
Non Funziona

### ISSUE THREAD

**Issue by LeoCSV** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4733]
Ho seguito tutta la procedura indicata su https://docs.microsoft.com/it-it/microsoftteams/batch-policy-assignment-edu ma mi compare questo errore:
New-CsBatchPolicyAssignmentOperation : Provided policy name is not valid
In riga:1 car:1
+ New-CsBatchPolicyAssignmentOperation -PolicyType TeamsMeetingPolicy - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ OperationName...tchAssignBody }:<>f__AnonymousType7`2) [New-CsBatch
   Poli...ion_NewExpanded], Exception
    + FullyQualifiedErrorId : ClientError,Microsoft.Teams.Config.Cmdlets.Cmdlets.NewCsBatchPolicyAssignmentOperation_N
   ewExpanded

**Comment by scanum** [comment]
@LeoCSV thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
