### ISSUE TITLE
Exporting the report to CSV, exports the table data, NOT the graph data

### ISSUE THREAD

**Issue by Craig-Humphrey** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4736]
You can't actually re-create the graph from the data that is exported.

Side note: where can I get this data, it's not available from the M365 Admin center (different fields) or from the M365 Usage Analytics App for Power BI (summarized by month, not day).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2758a3d6-c646-dcb0-2a31-c7b9b84e780b
* Version Independent ID: 8704c9fe-f8b0-82d2-bd83-3fd1a9ad638d
* Content: [Microsoft Teams user activity report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report)
* Content Source: [Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@scanum Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by diecamtab** [comment]
Hi guys,

i have the same question, is there a way to get the same data, including the graph?

Regards!

Diego Campos

**Comment by hrfmjp** [comment]
I also want to get graph data by csv and REST APIs.

**Comment by get-itips** [comment]
Hello @Craig-Humphrey 
I could verify what you are telling here, however as here we are limited to documentation fixes, I need to kindly suggest informing this to [Microsoft Teams UserVoice](https://microsoftteams.uservoice.com/), and also, wanted to tell you that I tried the report that is available from the `Admin center -> Reports -> Usage -> Microsoft Teams User Activity -> Export` and I could succesfully re-build the graph data from the exported csv file, maybe that works for you in the meantime.

![image](https://user-images.githubusercontent.com/36666927/84391478-6936cb00-abcf-11ea-9234-d51b5cb1e2b0.png)
![image](https://user-images.githubusercontent.com/36666927/84391519-7b186e00-abcf-11ea-94f2-ea0d25d8c2d4.png)

**Comment by Craig-Humphrey** [comment]
Hey @get-itips,
thanks for that, yeah that's close, but it's different columns.

Teams Admin:
Channel messages, Reply messages, Post messages, Chat messages, Meetings organized, Meetings participated, 1:1 calls, Group calls.

O365 Admin:
Team Chats, Private Chats, Calls, Meetings

Ideally I'd like to pull through all the fields that are available in the (Teams Admin) table under the graph (Urgent messages, Audio time, Video time and Screen sharing time), but by date, not by user.

I've already posted to [UserVoice](https://microsoftteams.uservoice.com/forums/908686-bug-reports/suggestions/40294192-teams-user-activity-report-does-not-include-data-t).

Thanks
Craig

**Comment by scanum** [comment]
@hrfmjp  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
