### ISSUE TITLE
Add in for iOS and Android

### ISSUE THREAD

**Issue by WilliamDShiell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#474]
Is there a timeline for allowing users the ability to create teams meetings on mobile platforms (iOS and Android)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Use the Microsoft Teams Meeting add-in in Outlook](https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by chuckedmonson** [comment]
For information about features in upcoming releases of Microsoft Teams, see the [Teams Roadmap](http://aka.ms/TeamsRoadmap). Thank you.
