### ISSUE TITLE
What does Live Events 10 000 attendees means?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4742]
On the page you have statement:

> Feature:			Audience size	
> Maximum limit:	**10,000 attendees**

Could you clarify what this is meaning in a real world scenario? Is this concurrent attendees? If so, then is this during the Live Event or is the 10k limitation also for viewing the recording?

What is happening when 10001 attendee viewer is joining to the meeting? What about if someone start looking for Live Event in 10 minutes late, and not looking for Live session at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@LolaJacobsen Lola, Can you kindly help us here? Can we get that information? I appreciate.

**Comment by LolaJacobsen** [comment]
Checking with PM Ashwin Appiah.

**Comment by tiburd** [comment]
Hi, @Petri-X 

[This article](https://docs.microsoft.com/microsoftteams/limits-specifications-teams) has been updated with more specific information, so I'm closing this issue.

If your concern still applies, please open a new issue.

Thank you!
