### ISSUE TITLE
Certificate CN must be SBC FQDN

### ISSUE THREAD

**Issue by tomdewing** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4743]
This page states "The certificate needs to have the SBC FQDN in the subject, common name, or subject alternate name fields." but the SBC FQDN must be in the CN; it is not sufficient to only have the FQDN in the SAN as the service will respond with:
SIP/2.0 403 Forbidden
REASON: Q.850;cause=63;text="&lt;redacted&gt;;Provided Trunk FQDN '&lt;SBC FQDN&gt;' is not allowed. Connection allows following fqdns: &lt;Certificate CN&gt;, &lt;Certificate CN&gt;."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e26faf8c-529e-b317-5934-cd41cfe8fa24
* Version Independent ID: 3ddd5d0a-6dbb-4940-1814-8346e293701b
* Content: [Plan Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan#feedback)
* Content Source: [Teams/direct-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@tomdewing Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by MaratMussabekov** [comment]
Hello, @tomdewing ,
yes, you are right, and also wording **subject, common name, or subject alternate name fields** doesn't make any sense since there is no such field as **common name**. Common name is the part of the subject field.
I will create a PR to add this info to the article.
Thank you

**Comment by scanum** [comment]
@tomdewing Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
