### ISSUE TITLE
Policy application latency

### ISSUE THREAD

**Issue by dotnick365** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4744]
Can we add some clarification to this article regarded expectations for policy replication time? For example, in some scenarios it seems to take 24-hours for a policy to apply. Can we clarify what policy scenarios require 24-hour replication, vs which ones should happen more quickly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b51eda6c-168c-7d99-7cc1-992b3d8feef2
* Version Independent ID: 118a1b8f-f4b7-a778-70b1-d3161fc548ab
* Content: [Manage app permission policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-app-permission-policies#app-permission-policies-for-gcc)
* Content Source: [Teams/teams-app-permission-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-permission-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by mdanielcristian** [comment]
I was also looking for this, I was testing the 'Block specific apps and allow all others" policy (for only one user) and I ended up thinking that it wasn't working, only to see it applied for that user two days after. Would be great if we can clarify how long it would take for certain policies to be applied.

**Comment by scanum** [comment]
@mdanielcristian Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @LanaChin Lana, are we able to get that information, maybe to put a sentence in the _faq_ section of the article, for the expected times for the policy to apply to users?

**Comment by LanaChin** [comment]
Thanks for your feedback and helping to improve our documentation. The article has been updated to reflect the latency for policy changes.
