### ISSUE TITLE
Outlook Presence dependency on SfB has been fixed in the latest Teams Update

### ISSUE THREAD

**Issue by dilip-2201** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4747]
Outlook Presence dependency on SfB has been fixed in the latest Teams Update:

"If you uninstall the Skype for Business client after you move a user to Teams Only mode, presence stops working in Outlook and other Office apps. Presence works fine in Teams. Workaround: To see presence in Outlook (and other Office apps), Skype for Business must be installed, even if you're running Teams in Teams Only mode. Microsoft is aware of this problem and is working on a fix."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d53d0cb0-90a6-5932-f78e-7de6fcc4d481
* Version Independent ID: 3d468027-cc37-5199-32ec-819bf62b2caa
* Content: [Interoperability between Skype for business and Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability#feedback)
* Content Source: [Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@dilip-2201 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by joeljanke** [comment]
Any update on the above?   Was the Outlook presence issue fixed or not?   This is a very important item to have accurate in this document.

**Comment by LanaChin** [comment]
Hi @joeljanke - thanks for your input. We've removed the note and replaced it with the following:

If you uninstall the Skype for Business client after you move a user to Teams Only mode, you may need to restart Outlook and Teams if presence stops working.
