### ISSUE TITLE
Non premium numbers and Call me feature

### ISSUE THREAD

**Issue by ceejey01** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4749]
My first question is what are non premium numbers?

Secondly, I understand that Audio Conferencing subscription provides 60 minutes per user per month that can be used to dial out to non-premium numbers in ANY of the Zone A countries as described in this document. I also understand that when an organizer has dial out enabled, attendees can use the call me feature to connect to the audio of their phones. How are the attendees charged for using this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 037fe22c-ba09-e381-231d-c37f6bb2a774
* Version Independent ID: e8046130-d407-3155-53c5-9043110cd793
* Content: [Audio Conferencing Dial-Out/Call Me At minutes - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-subscription-dial-out)
* Content Source: [Teams/audio-conferencing-subscription-dial-out.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-subscription-dial-out.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@ceejey01 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
