### ISSUE TITLE
Direct Routing only for Teams?

### ISSUE THREAD

**Issue by gregmilligan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#475]
This documentation implies that Direct Routing can be used either for Teams *or* for Skype for Business Online, yet Paul Cannon's blog post on the Tech Community site says that Teams is the only supported application:

https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/Direct-Routing-enables-new-enterprise-voice-options-in-Microsoft/ba-p/170450

Can you clarify?

Thanks,
Greg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0853cc6-9088-41e3-17f8-2fac2baecb8a
* Version Independent ID: 1e62ee34-a122-8152-a75f-e2a2c8e35aa0
* Content: [Configure Direct Routing](https://docs.microsoft.com/en-us/SkypeForBusiness/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/configure-direct-routing#feedback)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/configure-direct-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/configure-direct-routing.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by kenwith** [comment]
@gregmilligan - thank you for reporting and I will get this to the right person to get this straightened out. Will leave open until resolved.

**Comment by CarolynRowe** [comment]
Hi Greg, As of now, it can only be used with Teams.  The user must, however, first be homed in Skype for Business Online. We are moving the content to the Teams TOC to lessen the confusion.
