### ISSUE TITLE
"arrow_right:" should be "➡️ "

### ISSUE THREAD

**Issue by bsdmad** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4750]
2 "arrow_right" exists on the section "Teams とチャネルの構造", https://docs.microsoft.com/ja-jp/microsoftteams/migrate-slack-to-teams#team-and-channel-structure, but they should be "➡️". 

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7a81e1e5-3fd5-ff19-4f13-30bc2dd4389e
* Version Independent ID: e90e3618-95e7-7dc6-d020-2d0f75fcb6ff
* Content: [Slack から Microsoft Teams に移行する - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/migrate-slack-to-teams#feedback)
* Content Source: [Teams/migrate-slack-to-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/migrate-slack-to-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@bsdmad Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @bsdmad, thank you for your feedback.

Could you kindly let me know if it´s happening in the English version too, or only in the Japanese version?

Thanks!

**Comment by bsdmad** [comment]
> Could you kindly let me know if it´s happening in the English version too, or only in the Japanese version?

Oh, it seems to happen ONLY in the Japanese version! I confirmed this issue does not happen with  "英語で読む" toggle switch as on, placed on the top right.

**Comment by dariomws** [comment]
Hi @OfficeGlobal,

Could you kindly help with this issue? Thanks!

**Comment by OfficeGlobal** [comment]
@bsdmad arrows fixed and displayed properly

**Comment by bsdmad** [comment]
I've confirmed they are correct. Thanks!
