### ISSUE TITLE
Tags and notifications

### ISSUE THREAD

**Issue by sandramcg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4752]
Could you please add a section in this page to describe how tag notifications work? I don't know which notification setting will be applied to a tag.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b16e659e-cf07-268a-e224-fa444749ac29
* Version Independent ID: ee822a8d-b331-998f-e336-b1fa510f35c0
* Content: [Manage tags in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-tags#feedback)
* Content Source: [Teams/manage-tags.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-tags.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@LanaChin Hi Lana! Wondering if you can help me with this? Thanks!

**Comment by LanaChin** [comment]
FYI @anniecolonna

**Comment by anniecolonna** [comment]
Thanks @scanum, we will update this.

**Comment by LanaChin** [comment]
Thanks for your feedback @sandramcg. We've updated this article to include information about notifications. Also check out the following end-user documentation, https://support.microsoft.com/office/using-tags-in-teams-667bd56f-32b8-4118-9a0b-56807c96d91e and https://support.microsoft.com/en-us/office/manage-notifications-in-teams-1cc31834-5fe5-412b-8edb-43fecc78413d.
