### ISSUE TITLE
Public Event

### ISSUE THREAD

**Issue by maggiori-git** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4753]
I think that it's important to write that "Anyone can attend a Teams meeting or live event for free - no license is required" is true only for PUBLIC live event. If we schedule a live event in the organization the attendee users need to have not only a generic Office365 license but almost a specific Teams license applied ( if live event is scheduled in Teams )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92fcb1f6-5cc2-f6bd-cfa9-11d811f1dbf1
* Version Independent ID: 9a571e6d-8cb3-9ff8-a5c2-62deab146264
* Content: [Admin quick start - Meetings and live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/quick-start-meetings-live-events)
* Content Source: [Teams/quick-start-meetings-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/quick-start-meetings-live-events.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@scanum  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @maggiori-git 
Thanks for your feedback. I will propose clarifying this article based on it, if it gets approval by the author, it will be published.

**Comment by scanum** [comment]
@maggiori-git  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
