### ISSUE TITLE
Lies

### ISSUE THREAD

**Issue by mad-b** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4761]
ON my PC running windows 10 64, Skype allows to blur background or custom background. And it works fine. On same computer same environment, same session, Teams does not. So this processor requirement IMHO is, sorry, an excuse for lack of competence in doing the same software code that works on skype to work also on teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29a61ff5-b3a5-158d-149a-dec344060e05
* Version Independent ID: 97fac351-a283-aaa8-cde1-fbd9cf4e8504
* Content: [Hardware requirements for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/hardware-requirements-for-the-teams-app#feedback)
* Content Source: [Teams/hardware-requirements-for-the-teams-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hardware-requirements-for-the-teams-app.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by technonath** [comment]
mad-b makes a very good point. if skype can do it, then teams should be able to do it.

**Comment by grahamperrin** [comment]
@mad-b did Teams previously allow blur on the same computer?

**Comment by mad-b** [comment]
> @mad-b did Teams previously allow blur on the same computer?

Herllo. I really don't know, I just found out about this feature some weeks ago then tried to use it. Then as it did not work, I checked in Skype and it works on the same computer same session. Just closed Teams and opened skype and it works. I don't think this to be a company policy since some coleagues using notebook or other on same department has it working.

**Comment by mad-b** [comment]
> thank you for submitting feedback.
> I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
> Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
> Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

Hello, Manuela. Thanks for the information on support. If was this a "breaking" issue - like preventing me from using the program to some impacting extent, I would follow your advice. However this is just a bit frustrating as I just would like to be able to use the feature. So I will wait for MS to fix this in the future. Since you are in the midle, please eventually seed this thought ("it works on skype on same system without advanced processor requirements, why doesn't it on Teams?") Best regards.

**Comment by grahamperrin** [comment]
@mad-b please consider changing the title of this issue to something that is both descriptive and distinctive. Thanks
