### ISSUE TITLE
Does it work in teams only mode ?

### ISSUE THREAD

**Issue by technonath** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4766]
if the tenant is in teams only mode does consumer skype interop work ?

according to what I have just read here: https://docs.microsoft.com/en-us/microsoftteams/teams-only-mode-considerations

Users who are upgraded to Teams Only cannot communicate with users who are using Skype for Consumer!

Please clarify it here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3de87096-6253-ba71-f27a-0b161a36f0e2
* Version Independent ID: 8b61b40d-496c-6069-8a60-38a6282e072a
* Content: [Teams and Skype interoperability - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-skype-interop)
* Content Source: [Teams/teams-skype-interop.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-skype-interop.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@technonath thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by technonath** [comment]
@scanum
That response was a total waste of time - you are responsible for the documentation being accurate - you should provide the answer before closing this issue, the last 2 people to ask questions here have been fobbed off with the same answer. The best way forward is not to contact support - that team is useless and they have no answers - they just read the same articles as written here. Please re-open this case until you have a proper answer.
