### ISSUE TITLE
Small correction on Teams First doc

### ISSUE THREAD

**Issue by LaszloSomi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4768]
https://docs.microsoft.com/en-us/microsoftteams/teams-first-overview

We need to remove premier support from the site and change it to just support. 

Corrected text bellow 

**1**
 Important

If you have Skype for Business Server deployed, and your tenant was provisioned AFTER September 1, 2019, please contact support to enable coexistence capabilities for Teams. Make sure your 'Organization wide upgrade policy' is set to 'Island mode' before you assign any Teams licenses to a user.

2
Enablement steps for organizations with Skype for Business Server
Meet pre-requisites detailed in the Start Here section above.

Switch tenant into Islands mode (for tenants provisioned AFTER 9/1/2019, please contact support to make this change)
Setting your coexistence and upgrade settings

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
