### ISSUE TITLE
Clarification about limit of 20 for video/audio calls

### ISSUE THREAD

**Issue by ryanhelmer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4770]
Under Meetings and calls, it shows the following limits:

- Number of people in a meeting: 250
- Number of people in a video or audio call from chat: 20

Does this mean that only 20 people can join by call-in (PSTN or computer) for any Teams meeting? Or is the 20 limit specific to when a meeting is begun *from chat*, and if the meeting is scheduled (either from Teams or from Outlook), the audio (PSTN or computer)/video limit is 250?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#feedback)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by ryanhelmer** [comment]
I'm sorry, I don't understand the response to contact Support. My question is specific to the documentation itself.

**Comment by technonath** [comment]
I see a pattern here scanum seems to post this same response to every question I have read and then closes it. Not at all helpful.

**Comment by Sidewinder53** [comment]
The 20 person limit only applies to calls started from a chat. Meetings from Teams and Calendar should not be limited by this number. Not sure about the "Meet now"-Button.

**Comment by ryanhelmer** [comment]
Thank you, @Sidewinder53 !

@scanum , Could the documentation be updated to reflect this info, and to clarify about behavior when using the Meet Now button? Please note this is a documentation question.
