### ISSUE TITLE
Is it possible to hide this Icon?

### ISSUE THREAD

**Issue by NWH-SAmin5** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4771]
As our organization has several features on and off and custom as well. We have our own guide and help site. We would like direct user to that. Is this possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e853a70-3794-7f23-2dba-da09abf822e0
* Version Independent ID: d3dc0161-e075-df4d-d82c-a8f87c58da89
* Content: [Get help in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-help-in-microsoft-teams)
* Content Source: [Teams/get-help-in-microsoft-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-help-in-microsoft-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
