### ISSUE TITLE
Cannot purchase phone system

### ISSUE THREAD

**Issue by carolineholte** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4772]
@mattpennathe3rd @get-itips 
I am trying to purchase a phone system by following the instructions on this link: https://docs.microsoft.com/en-us/microsoftteams/calling-plans-for-office-365

I do not see the following option:  

![image](https://user-images.githubusercontent.com/64658362/80829777-9f2e6b80-8b9c-11ea-8bed-193944ac6f9a.png)

Here is a screenshot of the screen that I do see: 

![image](https://user-images.githubusercontent.com/64658362/80829828-b8cfb300-8b9c-11ea-81d3-08726689917d.png)

![image](https://user-images.githubusercontent.com/64658362/80829832-bcfbd080-8b9c-11ea-9ca3-69350fc4049a.png)

Can someone please tell me why I do not have the option to purchase the Phone System??

Thanks,

Caroline

**Comment by mattpennathe3rd** [comment]
@carolineholte Thanks for opening this issue. There have been many recent changes with the Microsoft 365 product offerings, so it's possible that some of these screenshots are out of date, but we'll look into that right away.

@CarolynRowe I believe this article is in your wheelhouse, so would you like to investigate?

**Comment by carolineholte** [comment]
Okay great thanks Michael. And if it helps: here are the licenses I currently have:

1. Office 365 E5
2. Microsoft power apps plan 2 for trial 
3. dynamics 365 P1 trail for information workers

**Comment by CarolynRowe** [comment]
Thank you for contacting us.  Please see the following docs:

https://docs.microsoft.com/en-us/MicrosoftTeams/setting-up-your-phone-system
https://docs.microsoft.com/en-us/MicrosoftTeams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=small-business

If these do not answer your question, then I would suggest contacting Microsoft technical support.

I will also review the calling plan doc to see if updates are required.  Closing this issue.

**Comment by carolineholte** [comment]
Thanks Carolyn!

Best Regards,
Caroline

--

Caroline Holte

Operations Manager

Bridge Diagnostics LLC

Mobile: 949.616.6609

Email: Caroline@BridgeDiagnostics.com<mailto:Jason@BridgeDiagnostics.com>

LinkedIn profile<https://outlook.office365.com/mail/options/mail/messageContent/www.linkedin.com/in/carolineholte>



[cid:image001.png@01D6220A.F69D0030]

________________________________
