### ISSUE TITLE
External vs Guest SELECTION

### ISSUE THREAD

**Issue by Ranger-Z** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4773]
Unclear if there is a way to set a given use as External or Guest.  There are 2 sections in Teams admin, one for each.  Relationship is not defined.  I know I have used\enabled External in the past.  Now have BOTH enabled.  Do not know if this is advisable or not. No discussion in docs.
SITUATION: Only External was enabled.  Had used for a partner.  Added a new partner and their title bar showed in Black with a Skype icon, but communications fails.  MS Support has me enable GUEST, really more FN than I want.  Unable to find similar issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f1d577c-1360-c2c1-a850-9ac6a941ec2f
* Version Independent ID: 346e43d4-22e0-2800-b80d-9fbdac324f75
* Content: [Manage guest access in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-guests#feedback)
* Content Source: [Teams/manage-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-guests.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Ranger-Z thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Ranger-Z** [comment]
I have a ticket open for over a week now.  They have avoided answering this specific question and basically say I should use a guest.  

I am asking you specifically to identify in the docs that it is (External OR Guest) or (External and Guest).  

- If the former indicate that only one of External or Guest should be enabled.
- If the later indicate that both MAY be enabled and HOW to define a specific contact as one or the other.

Support is not clear on this no matter how many times I ask.  They had me enable Guest and convert the External to Guest (delete the External, sent an Azure invite, and re-add the contact as a Guest).  Does not work.  Contact keeps coming back as External.

PLEASE CLARIFY HOW IT IS SUPPOSE TO WORK.
