### ISSUE TITLE
HostedVoiceMail - setting overwritten by Azure AD Connect based on ExchangeUM status

### ISSUE THREAD

**Issue by J-Fedor** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4774]
Now the ExchangeUM is "dead" and we're all on Cloud Voicemail, something doesn't seem right with this setup. In a hybrid configuration, we perform the HostedVoiceMail, and test, works fine - have voicemail. Then less than 30 minutes later....the setting is blank. This is because of Azure AD connect. It is synchronizing the UM status of the user back on-prem. So, we need to go to 365, enable UM, assign it a policy and extension that is irrelevant now. Then once that is done, the setting rolls back down onto the on-prem user setting. Don't recall seeing anything about needing to perform those steps still, or setting up filtering of the attribute, etc. Something seems missed in the steps that are provided (or hidden and I haven't found it). Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec8b8afb-b9ca-8136-b907-5bbff4c9dcf1
* Version Independent ID: d4f68818-6fe6-5bb7-f108-e26a643f2cc7
* Content: [Configure Cloud Voicemail service for on-premises users - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/configure-cloud-voicemail)
* Content Source: [Skype/SfbHybrid/hybrid/configure-cloud-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-cloud-voicemail.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@J-Fedor Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@J-Fedor Thank you reaching out. Please let me know if these links work - https://answers.microsoft.com/msoffice/forum/all/azure-ad-connect-settings-to-stop-lync/74ad9361-6632-4707-b944-c8a8ff3c9696 & https://docs.microsoft.com/exchange/voice-mail-unified-messaging/voice-mail-unified-messaging

**Comment by J-Fedor** [comment]
The first link doesn't work at all - "Page Not Found - We are sorry we weren't able to find what you are looking for."
The second link "works" but doesn't help with the issue.  Been working with support on this for nearly 2 weeks as well.  Not sure they quite understand the issue yet, but seems pretty clear/obvious what the problem is.

**Comment by Reeced40** [comment]
@dstrome Please assist.

**Comment by Reeced40** [comment]
@dstrome do you have any update yet on this please?

**Comment by J-Fedor** [comment]
FYI:  Problem should be resolved by upgrading Azure AD Connect - the 1.2.65.0 version has a fix related to the issue.
https://docs.microsoft.com/en-us/azure/active-directory/hybrid/reference-connect-version-history

**Comment by Reeced40** [comment]
@J-Fedor thank you for the information. Let me know if it's okay to close this issue.

**Comment by J-Fedor** [comment]
Yep, that’s fine.  Not sure if worth adding a footnote on there regarding that issue or not, but you can close.
Thanks.


John Fedor
Principal Architect
Direct:
Support Desk
630.592.6240
630.592.6260
visit peters.com today!
​Stay up-to-date and follow us on social media!
0.5% of Office 365 accounts are compromised monthly, are you protected? Find out HERE.
The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and privileged material
​Unauthorized review, use, disclosure, or distribution is prohibited.
​If you receive this material/information in error, please contact the sender and destroy the material/information.

**Comment by Reeced40** [comment]
@scanum this can be closed thank you.
