### ISSUE TITLE
Communications Credits not showing

### ISSUE THREAD

**Issue by EmiTanako** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4777]
We use audio conferencing as a service and the provided pool for audio conferencing is being used up by some users who prefer the dial-out option. We then assigned communications credits to these users to reactivate the dial-out option for them. Usage shows in the Main admin center &gt; Billing &gt; subscriptions and in the PSTN usage report. But the pool for communications credits does not show in the minutes pools report which goes against what we expected because of this article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8107d4a3-a55e-4891-ee72-27f79f647a1e
* Version Independent ID: b71f24c6-b54d-8a0f-ea0e-8839ff5481a4
* Content: [Microsoft Teams PSTN minute pools report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/pstn-minute-pools-report#feedback)
* Content Source: [Teams/teams-analytics-and-reports/pstn-minute-pools-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/pstn-minute-pools-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by EmiTanako** [comment]
I'm not sure if this is because this report is showing as "Preview" on our end. If that would be the case, then maybe updating the article and indicating something about the report being "Preview" would be helpful.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by EmiTanako** [comment]
We opened a service ticket and support was claiming that this is because the PSTN minute pools report in MS Teams is still in preview, which sort of makes sense since the PSTN minute pool report for SFB does not contain anything about communications credits. https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-online-reporting/pstn-minute-pools-report
