### ISSUE TITLE
cross linked articles

### ISSUE THREAD

**Issue by MSTejas** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4778]
Looks like these two articles are interchanged.
https://docs.microsoft.com/en-us/microsoftteams/known-issues
https://docs.microsoft.com/en-us/microsoftteams/rooms/known-issues

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Support Microsoft Teams in your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues#feedback)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocspr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@officedocspr Thank you for reaching out. I work on the editing/writing side for MS Docs. Please can you clarify what you are asking? Are there any amendments needed in this article? Thank you.

**Comment by scanum** [comment]
@officedocspr We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
