### ISSUE TITLE
AAD Connect Merge Rules

### ISSUE THREAD

**Issue by Pher0ah** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4782]
Please can you include what attributes need to be merged and which ones will come from the user and which from the resource forest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff5e7611-a75b-f6f5-896e-6c2decd2d6b4
* Version Independent ID: 0b9c74fc-d01c-5292-a669-a130be3d5741
* Content: [Deploy a resource forest topology - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/configure-a-multi-forest-environment-for-hybrid)
* Content Source: [Skype/SfbHybrid/hybrid/configure-a-multi-forest-environment-for-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-a-multi-forest-environment-for-hybrid.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Pher0ah Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@CarolynRowe Could you please assist?

**Comment by Reeced40** [comment]
@CarolynRowe any update yet?

**Comment by Reeced40** [comment]
@CarolynRowe Hi Carolyn, any possible updates available?

**Comment by scanum** [comment]
@CarolynRowe Hi Carolyn, any possible updates available?

**Comment by tiburd** [comment]
@Pher0ah 

The article has been updated since you submitted this issue, so we're closing this issue.
