### ISSUE TITLE
Links to PKG not available on https://teams.microsoft.com/downloads page

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4783]
Hello. When I go to this page https://teams.microsoft.com/downloads there is only to download Teams for WIndows but not Mac. Where can we get binaries for Mac?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Larryngolog** [comment]
Hi! The same goes for Linux - the https://teams.microsoft.com/downloads site shows only Windows client when using Windows OS. Admins need to be able to dowload the binaries for Mac and Linux from any platform they use to be then able to prepare the deployment packages for organization. Maybe You could include download links on the "Install Teams using MSI" article for Mac and Linux platforms as well?

**Comment by Reeced40** [comment]
@Larryngolog The download link for Linux is a little below the top of the landing page: https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/download-app #desktopAppDownloadregion

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
