### ISSUE TITLE
error in code block on download-and-install-the-skype-for-business-online-connector.md

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4786]
Escape characters are not needed inside of code blocks, extra `\`s should be removed.

**Comment by scanum** [comment]
@ITBlandMCT thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
