### ISSUE TITLE
"Make changes to the email messages that are sent to them"

### ISSUE THREAD

**Issue by savusca** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4789]
hi team,
Most likely this statement needs to be adjusted.
If we try to run:
Set-CsOnlineDialInConferencingTenantSettings -SendEmailFromOverride $true -SendEmailFromAddress DoNotReply@contoscom -SendEmailFromDisplayName "Contoso - Audio Conferencing Settings" -AutomaticallySendEmailsToUsers $false
We get:
WARNING: The property "SendEmailFromOverride" has been deprecated and may be removed in future versions.
WARNING: The property "SendEmailFromAddress" has been deprecated and may be removed in future versions.
WARNING: The property "SendEmailFromDisplayName" has been deprecated and may be removed in future versions.

Already opened Issue https://github.com/MicrosoftDocs/office-docs-powershell/issues/5465 to have the Set-CsOnlineDialInConferencingTenantSettings article adjusted.

Can we also make a statement here informing that this option is being decommissioned?

**Comment by scanum** [comment]
@savusca  Thank you for submitting feedback and contributing to the docs. We are currently investigating this. Please link documentation you are referring to.

**Comment by savusca** [comment]
Hi,
Appologies :)
I am referring to this article:
https://docs.microsoft.com/en-us/microsoftteams/emails-sent-to-users-when-their-settings-change-in-teams#what-if-you-dont-want-email-to-be-sent-to-them
Which states:
"Want to know more about Windows PowerShell?

By default, the sender of the emails will be from Office 365, but you can change the email address and display name using Windows PowerShell."

As i have indicated before, seems that we are deprecating the "SendEmailFrom" functionalities for the Set-CsOnlineDialInConferencingTenantSettings cmdlet, hence also the base article should be adjusted.

**Comment by Reeced40** [comment]
@savusca Thank you for reaching out and helping improve MS Docs. Please note this article was updated a few days ago. Please also note  that MS are frequently updating how features are managed, so the steps here might be a little different from what you see.

**Comment by scanum** [comment]
@savusca Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
