### ISSUE TITLE
SQL backend requirement list incomplete?!

### ISSUE THREAD

**Issue by 3k09** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#479]
Hey, I've noticed that the SQL backend requirement part "Back end databases that will work with Skype for Business Server 2015" was changed. Now it seems to be incomplete and not display all versions which are supported. Could you please update and complete this list as it was on technet before? Thanks. Best Regards Erik 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7c475b5d-09ed-7f58-86d4-27f28e33ef7a
* Version Independent ID: f0ad50f3-ea93-9424-6de8-a0b778e90b23
* Content: [Serveranforderungen für Skype for Business Server 2015](https://docs.microsoft.com/de-de/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/server-requirements#DBs)
* Content Source: [Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.de-DE/blob/live-sxs/Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by kenwith** [comment]
@3k09 - I will get this over to the right person and get this resolved asap. Thank you very much for taking the time to report. It is appreciated!

**Comment by kenwith** [comment]
@3k09 - this appears to be an issue with how the en-us article is translated. The localization team, @samanthaw , is looking into this. There is also a related issue with German https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/412 that is also being resolved and these should be resolved together.

**Comment by kenwith** [comment]
Here is direct link to the en-us version where the table is not getting truncated: https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/server-requirements  Let's keep this open until resolved. Thank you very much for reporting!

**Comment by 3k09** [comment]
@kenwith Thank you!

**Comment by samanthaw** [comment]
@3k09 this is now fixed

**Comment by kenwith** [comment]
Thank you @samanthaw !  Closing this one but if you still see issues feel free to re-open.
