### ISSUE TITLE
Calling Plan License also required to make or receive calls using the Room. The article makes it sound like that you only need the Meeting Room license.

### ISSUE THREAD

**Issue by liitimellison** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4790]
Please put another foot note into this article to clarify if the tenant requires a calling plan also to use the phone system portion of the meeting room license.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing#feedback)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-licensing.md)
* Service: **skype-for-business-online**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@liitimellison  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@liitimellison Thank you for reaching out. The article was updated yesterday. If there's anything else, please let me know. Thanks.

**Comment by danmyhre** [comment]
The table still shows that all you need is the meeting room license to make calls.  Can you please clarify?

**Comment by Reeced40** [comment]
@LanaChin Hi Lana, please can you confirm if a Calling Plan License is also required to make or receive calls using the Room? Thanks.

**Comment by LanaChin** [comment]
Reassigning to @dstrome as this is a Microsoft Teams Rooms article.

**Comment by dstrome** [comment]
hi @liitimellison - we're rewriting the Teams Rooms content in its entirety.  We should have the updates, including changes to licensing, published within the next few weeks.
