### ISSUE TITLE
Precision On non Enterprise voice user and UM-enabled User support

### ISSUE THREAD

**Issue by ThomasBIDAULT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4794]
Could you precize the case when there is no Enterprise Voice user and no UM-enabled user in the Skype/Exchange Org. In that specific case, is it supported to have user hosted on Skype for Business 2015 and mailbox on Exchange 2019 ?

Thanks for clarification

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 29e6436f-d73b-6ccb-c7ca-2d9e42648b6e
* Version Independent ID: 8ac96788-c9e6-9f4b-0d9f-0966bb6a012f
* Content: [Planification de la migration de Skype entreprise Server et d’Exchange Server - Skype for Business Hybrid](https://docs.microsoft.com/fr-fr/skypeforbusiness/hybrid/plan-um-migration?source=docs#feedback)
* Content Source: [Skype/SfbHybrid/hybrid/plan-um-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/plan-um-migration.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@ThomasBIDAULT Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @ThomasBIDAULT, thank you for your feedback.

@dstrome could you kindly help me to confirm that it´s supported? I understand that if you move a UM enabled mailbox to Exchange 2019 it will be disabled automatically. You need to implement Cloud Voicemail.
So I think Exchange 2019 and Skype for Business with UM enabled users is supported.

**Comment by ThomasBIDAULT** [comment]
Hi David,
My Question is on the support of NON UM enabled user with Exchange 2019 and SFB 2015. Feel free to reach out to me for additional infos.

Regards,

Thomas BIDAULT

De : Dario Woitasen <notifications@github.com>
Envoyé : jeudi 7 mai 2020 21:30
À : MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com>
Cc : Thomas Bidault <Thomas.Bidault@microsoft.com>; Mention <mention@noreply.github.com>
Objet : Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Precision On non Enterprise voice user and UM-enabled User support (#4794)


Hi @ThomasBIDAULT<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FThomasBIDAULT&data=02%7C01%7CThomas.Bidault%40microsoft.com%7Ca669f81c480144db536a08d7f2bcf971%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637244765774796173&sdata=5Qq2OlwedQ%2BwURwiD%2BOX3xRuL%2B%2BKV7mXsTyQRlqu5wY%3D&reserved=0>, thank you for your feedback.

@dstrome<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdstrome&data=02%7C01%7CThomas.Bidault%40microsoft.com%7Ca669f81c480144db536a08d7f2bcf971%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637244765774806162&sdata=w4codcPE6jEBF7ASOUtzKQtZstXd5ykryRarUU9DnIQ%3D&reserved=0> could you kindly help me to confirm that it´s supported? I understand that if you move a UM enabled mailbox to Exchange 2019 it will be disabled automatically. You need to implement Cloud Voicemail.
So I think Exchange 2019 and Skype for Business with UM enabled users is supported.

**Comment by dstrome** [comment]
Hi @ThomasBIDAULT. We can only respond to product documentation feedback. Please contact Microsoft support for help with this specific question.
