### ISSUE TITLE
Downloading link is not there

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4795]
Downloading of Microsoft Teams link is  not available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ad624-9792-91b7-c85f-09b839b1ea44
* Version Independent ID: e8288f91-11bd-599b-8a88-074917b315a4
* Content: [Microsoft Teams IT architecture and telephony solutions posters - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-architecture-solutions-posters?source=docs)
* Content Source: [Teams/teams-architecture-solutions-posters.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-architecture-solutions-posters.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by LolaJacobsen** [comment]
Merged @RAJU2529 PR
