### ISSUE TITLE
Powershell Deployment

### ISSUE THREAD

**Issue by goldmuskhex** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4797]
Hello,

Is there a way to assign tags to users in Microsoft Teams using the Powershell module for Teams?

Thanks

**Comment by scanum** [comment]
@goldmuskhex thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
