### ISSUE TITLE
Microsoft Teams Report

### ISSUE THREAD

**Issue by diecamtab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4802]
Hello Guys,

i need to generate reports with in the date range of 90 days. Currently, i am only able to see date ranges of 7 and 28 days. 

Could you please help me with this?

Regards!

Diego Campos
[2020-05-05_16-46-38.pdf](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/files/4583553/2020-05-05_16-46-38.pdf)

**Comment by scanum** [comment]
@diecamtab thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
