### ISSUE TITLE
can't see team expiration section

### ISSUE THREAD

**Issue by FlorianRD** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4805]
I do not see the teams expiration section in the teams settings page even though I received a mail warning me of expiration in 30 days (so policy is applied)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b41d63bc-26f4-fd50-adc4-f665c1a4cd88
* Version Independent ID: 24248b2d-79a1-98a7-86dd-f6dbcf9e2ab3
* Content: [Team expiration and renewal in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/team-expiration-renewal)
* Content Source: [Teams/team-expiration-renewal.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/team-expiration-renewal.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@FlorianRD thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
