### ISSUE TITLE
Microsoft 365 Groups created via Teams Admin Console not always hidden in Outlook

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4806]
Further to issue #4430

The article states 'Based on customer feedback, new Microsoft 365 Groups generated as a result of creating a team in Microsoft Teams will no longer show in Outlook by default. For customers that want to continue with the existing behavior of showing these groups in Outlook, an Exchange Online PowerShell cmdlet will be provided which can enable the group for the Outlook experience.'

However, in our testing this is not always the case - if a new Team is created via by an admin via the Teams Admin Centre, the Team is not hidden from the GAL or Microsoft Outlook by default. The documentation still needs to be updated to reflect this; Set-UnifiedGrop -Identity -HiddenFromExchangeClientsEnabled needs to be run in order to hide the group in these scenarios.

In the original issue #4430 I stated this was also the case for groups created via the Teams Powershell - however I was incorrect, but the documentation was never updated for the remaining issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d86301b-ce9c-388c-e563-9e5e5c27132e
* Version Independent ID: 07e4ae23-0966-e8f3-9b7c-4f6c02569eb0
* Content: [Microsoft 365 Groups and Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/office-365-groups)
* Content Source: [Teams/Office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-groups.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@ChrisAtMAF  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by MaratMussabekov** [comment]
Hello @ChrisAtMAF, please have a look at the PR #4917 I have created.
Thank you

**Comment by ibawwad** [comment]
I have seen the same behavior, on the contrary they are hidden from Teams not Outlook

**Comment by scanum** [comment]
@ChrisAtMAF  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
