### ISSUE TITLE
Chat e conversazioni di canale in Outlook?

### ISSUE THREAD

**Issue by carloreggiani** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4807]
Non e' chiaro se è possibile avere, come per Skype for Business, lo storico delle conversazioni di Teams (sia chat che di canale) registrate in Outlook: permetterebbe di avere sempre un unico repository per eseguire ricerche di contenuti.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [Interazione tra Exchange e Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/it-it/microsoftteams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@carloreggiani thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
