### ISSUE TITLE
For pricing info, see Pricing for Phone System.

### ISSUE THREAD

**Issue by adrienmaugard** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4808]
The link is broken and send us to a 404 (was a video about SQL, but it's no longuer here)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abae7324-861d-7ca7-7239-a5df8fd927d5
* Version Independent ID: 8a30bd2f-9bc3-a0a8-8b31-d53836ead4d0
* Content: [Microsoft Teams add-on licenses - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=small-business#feedback)
* Content Source: [Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@adrienmaugard  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @adrienmaugard, thank you for your feedback.

It´s working for me now, could you please double-check it?

**Comment by adrienmaugard** [comment]
It work now, thanks.
