### ISSUE TITLE
too much cpu in video call

### ISSUE THREAD

**Issue by ilLongo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4809]
in video call with the webcam, the system is slow down with the Kernel process over 120% constantly.
My MacBook Pro 13 Early 2015 i7 16GB RAM macOS Catalina 10.15.4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29a61ff5-b3a5-158d-149a-dec344060e05
* Version Independent ID: 97fac351-a283-aaa8-cde1-fbd9cf4e8504
* Content: [Hardware requirements for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/hardware-requirements-for-the-teams-app#feedback)
* Content Source: [Teams/hardware-requirements-for-the-teams-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hardware-requirements-for-the-teams-app.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@ilLongo thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
