### ISSUE TITLE
Porting process

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4810]
Is there any scheduling of porting or does it just happen during the 7-30 day time period?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a17293e0-4c49-0e97-d5da-b48322f10928
* Version Independent ID: c38c0726-5dec-d374-6948-2188d43025ef
* Content: [What's a port order? - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/phone-number-calling-plans/port-order-overview)
* Content Source: [Teams/phone-number-calling-plans/port-order-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phone-number-calling-plans/port-order-overview.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@StuBeck32 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by StuBeck32** [comment]
Unfortunately your support has taken a vacation. I have a massive Intune issue which isn’t being looked at for the last week. As you’ve closed this, I’ll just look at other solutions.

Stuart
________________________________

**Comment by StuBeck32** [comment]
There is scheduling of ports, the documentation should reflect this is a user actionable item.
