### ISSUE TITLE
good information

### ISSUE THREAD

**Issue by dstruve** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4811]
i was initially concerned about the high memory usuage but turned out it was no big deal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc21902c-d522-3851-8587-177f01bc085c
* Version Independent ID: 590bcc64-a86d-b61e-7d94-4e4322c4e71d
* Content: [How Microsoft Teams uses memory - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-memory-usage-perf#feedback)
* Content Source: [Teams/teams-memory-usage-perf.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-memory-usage-perf.md)
* Service: **msteams**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@dstruve Thank you for the feedback. This article was written specifically because multiple customers expressed similar concern, so we tried to explain why people are seeing what they're seeing.
