### ISSUE TITLE
I create a Group using Graph API, and then added a team to that group. My team gets created but not those members are in Team.

### ISSUE THREAD

**Issue by ashoksubedi1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4814]
So I go to Azure portal and look at the members of that group and I see all the members I added over there. So definitely my code is working good. Why can not I see all the azure ad group members in Team right away. I heard it takes about 48 hours for those members to get access to that team. Owners of the group have access to the team right way but members have no clue that there is a new team that they are part of. Any suggestions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a795a46e-52eb-c338-8bd2-fd0133cfcfd0
* Version Independent ID: 1d64ea4b-376b-4845-c5e0-ce90f8ed6089
* Content: [Welcome to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-overview?redirectSourcePath=%252fen-us%252farticle%252fFrequently-asked-questions-about-Microsoft-Teams-%2525E2%252580%252593-Admin-Help-05cbe533-2181-4e95-a4b0-52cd7695fafc)
* Content Source: [Teams/Teams-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@ashoksubedi1 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
