### ISSUE TITLE
Exchange Onprem's OWA

### ISSUE THREAD

**Issue by JoseLampreia** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4815]
Hi Team,
Can you please clarify if this feature is support with Exchange Onprem's OWA? 
Thanks in advanced. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Use the Microsoft Teams Meeting add-in in Outlook - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook#feedback)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@scanum  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
Hi @JoseLampreia  Thanks for raising this issue! I will be looking into it!

**Comment by TokyoScarab** [comment]
@JoseLampreia Yes, this is supported in On-Premises OWA

**Comment by scanum** [comment]
@JoseLampreia Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
