### ISSUE TITLE
SquirrelSetup.log localization

### ISSUE THREAD

**Issue by RomanNG** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4817]
It's written "When Teams is successfully installed, the log location switches from %LocalAppData%\SquirrelTemp to %AppData%\Microsoft\Teams. At this location, there are two log files of interest, SquirrelSetup.log and logs.txt."
I've checked and SquirrelSetup.log is in %LocalAppData%\Microsoft\Teams not %AppData%\Microsoft\Teams (where logs.txt is indeed).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae7c99af-b026-c0d1-f2ac-468578a14c2a
* Version Independent ID: 8f4904e2-3925-b1ec-73f8-1bd473d4810a
* Content: [Troubleshoot Microsoft Teams installation and update issues on Windows - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot-installation)
* Content Source: [Teams/troubleshoot-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/troubleshoot-installation.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@RomanNG  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
Hi @RomanNG   Thanks for raising this issue! I will be looking into it!

**Comment by TokyoScarab** [comment]
@LanaChin After looking into this I have noticed on my machine and others that what is pointed out here is also true on the machines I've looked at. The log.txt and SquirrelSetup.log are split up between local and roaming appdata folders as mentioned above. Do you know more about why this would be? Has there been a change in where these files are kept? If so, I will update the documentation to reflect this. Or is there a more detailed reason where the documentation could be true for some users and different for others?  Look forward to hearing back on this, thanks!

**Comment by LanaChin** [comment]
Reached out to PM.

**Comment by TokyoScarab** [comment]
@LanaChin Was wondering if there was any new info on this issue from the PM, thanks!

**Comment by LanaChin** [comment]
Waiting to hear back from the PM, thanks.

**Comment by LanaChin** [comment]
@TokyoScarab - please update the log location in the "When Teams is successfully installed,...." sentence from %AppData%\Microsoft\Teams to %LocalAppData%\Microsoft\Teams.  Thanks.

**Comment by TokyoScarab** [comment]
@LanaChin Thank you very much!

**Comment by LanaChin** [comment]
Article is updated. Thanks for your feedback!
