### ISSUE TITLE
Teams Usage Report

### ISSUE THREAD

**Issue by diecamtab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4818]
Hello guys,

I'm trying to get a report on equipment usage, but the data I download doesn't have much to do with what can be seen on the Web.

I would like to be able to download the same data that appears in the Teams admin center chart.

Regards!

Diego Campos

**Comment by scanum** [comment]
@diecamtab thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
