### ISSUE TITLE
traffic flow steps are incorrect

### ISSUE THREAD

**Issue by wilfriedvanoosterhout** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4819]
The steps in the flows for the scenarios are incorrect.

First scenario: 
Teams to the number in Germany.
The user’s Teams client communicates with Phone System directly through the REST API.
The media generated during the call flows to the local SBC’s internal IP address.
The local SBC redirects the flow to the proxy SBC in Amsterdam and to the connected local PSTN network.
-&gt; incorrect, the flow will not hit the proxy SBC in Amsterdam but traffic goes out to PSTN via Germany SBC

Second scenario:
 -&gt; same as first scenario

Third scenario:

In the following diagram, a user assigned to the local branch office in Vietnam, while on premises, makes a Direct Routing phone call through Teams.
The user’s Teams client communicates with Phone System directly through the REST API.
Media generated during the call flows to the local SBC’s internal IP address.
The local SBC redirects the flow to the proxy SBC in Singapore and to the connected local PSTN network.
-&gt; Proxy SBC in Singapore is not used, traffic goes via SBC in Vietnam to PSTN

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbab466f-88f8-302a-7cda-d53bc743e831
* Version Independent ID: b5634fb3-6627-3fcd-101c-0ebc419d7b19
* Content: [Direct Routing Local Media Optimization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-media-optimization#feedback)
* Content Source: [Teams/direct-routing-media-optimization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-media-optimization.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@wilfriedvanoosterhout  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @CarolynRowe can you kindly step in to clarify if we need to correct the article? Thank you

**Comment by CarolynRowe** [comment]
I will follow up with the PM.

**Comment by CarolynRowe** [comment]
The PM says the flows in the published doc are correct and have been validated by multiple people.  I'm going to close this issue.   If there are still concerns, I suggest contacting technical support.
