### ISSUE TITLE
SfB contact groups moved to Teams

### ISSUE THREAD

**Issue by voutit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4822]
Will first logon to Teams client after changing the users TeamsUpgradePolicy to TeamsOnly also move over Skype for Business Online users self-created contact groups? Are there any limitations on that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef367a6e-23ef-0d9c-fbd1-4c2f58fe0a90
* Version Independent ID: 790f1258-f581-09d0-3e77-f7e0d1668633
* Content: [Upgrade to Teams from a Skype for Business on-premises deployment - Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/upgrade-to-teams-on-prem-overview#feedback)
* Content Source: [Teams/upgrade-to-Teams-on-prem-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-to-Teams-on-prem-overview.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@voutit thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
