### ISSUE TITLE
Needs updating for license requirements

### ISSUE THREAD

**Issue by calmco** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4824]
Given that all licenses are now Microsoft 365 and have been renamed to Standard, Premium etc... it's needed to update the doc to the correct subscriptions needed for live events.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events#feedback)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@calmco  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jonwbstr** [comment]
This. Please update the article I had to do extra digging to see if it is included in "Microsoft 365 Business Basic	" (Yes it is)

**Comment by jonwbstr** [comment]
This is the section I wanted to see "M365 Business Basic" in.

```
Here are the licenses that must be assigned:

An Office 365 Enterprise E1, E3, or E5 license or an Office 365 A3 or A5 license
A Microsoft Teams license
A Microsoft Stream license
```

**Comment by lindspea** [comment]
@calmco @jonwbstr thank you for reaching out and helping improve MS Docs. This doc set is being updated, but in the meantime here is a link that might be helpful. I can have it added to this article if you think it will be helpful to other users - https://docs.microsoft.com/stream/license-overview. Please let me know.

**Comment by jonwbstr** [comment]
Nope, it also doesn't mention business basic. Good article otherwise ;)

**Comment by lindspea** [comment]
@jonwbstr @calmco Would it be helpful to add this link to the article? https://www.microsoft.com/microsoft-365/microsoft-teams/compare-microsoft-teams-options

**Comment by calmco** [comment]
If you could change that page for the part where it says “Host online and video conferencing meetings for up to 250 people5<https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/compare-microsoft-teams-options?rtc=1#coreui-contentrichblock-7wgyjux> and online events for up to 10,000”  to “Hold Teams Live Events” (and then the explanation), then it would be helpful. The commercial / marketing talk that always seems to talk around what something actually is instead of naming it is always confusing.

I had to manually change the URL because it redirects for us (Belgium) to https://www.microsoft.com/nl-be/microsoft-365/microsoft-teams/compare-microsoft-teams-options?rtc=1

So I switch it to this: https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/compare-microsoft-teams-options?rtc=1

The page itself is conflicting with other pages however. In my region according to that page I should have teams live events because we have Microsoft 365 Business Standard.

The other pages you previously linked to say that I need Office E3.

Technically, I think the other pages are right and the one you linked to is incorrect, as with my Microsoft 365 Business Standard subscription we are unable to host live events. Or maybe it’s not available in my region?

**Comment by lindspea** [comment]
@LanaChin please can you clarify?

**Comment by LanaChin** [comment]
Hi @calmco - thanks for your input. To schedule or produce a live event, a Microsoft 365 or Office 365 Enterprise or Education license is needed (as reflected in the article).  With a Microsoft 365 Business plan (such as  Microsoft 365 Business Basic), you can watch live events but not schedule or produce them.
