### ISSUE TITLE
Tell your technical writers that "for more information " links are soul crushing

### ISSUE THREAD

**Issue by heschelpop** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4826]
isnt it possible to have them use thier brains and actually provide the subject matter context ANSWER to whatever it is they think they need to redirect you to a completely huge other document that has no context to the reason why you were directed there so you can waste more time and click on an endless loop of for more informaiton links - heres a thought - create documentation that has actual answerrs and actionable procedures on the page instead of using links that propel you to another galaxy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59426612-8da4-be3e-f0c8-8c23e9178d7d
* Version Independent ID: bd2d7426-06d6-5c18-7776-a50fc05c9ce9
* Content: [Configure Audio Conferencing settings - Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/deploy-audio-conferencing-teams-landing-page#feedback)
* Content Source: [Teams/deploy-audio-conferencing-teams-landing-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/deploy-audio-conferencing-teams-landing-page.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@heschelpop thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
