### ISSUE TITLE
this has to be one of the all time most confusing things MSFT has ever done

### ISSUE THREAD

**Issue by heschelpop** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4827]
its laughable the maze of gibberish I am going through to set this up.  Have you ever used ZOOM, WebEx, Join.Me, GoToMeeting?  How can Satya think with a straight face this is going to scale - its Skype For Business 2.0 in terms of people saying forget it, I will just use ZOOM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f74116db-b4a0-8a58-7e52-0d961e35ed99
* Version Independent ID: 2334f49e-54fb-4d2b-ed4a-dab8b399b45e
* Content: [Getting service phone numbers - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/getting-service-phone-numbers#get-new-service-numbers)
* Content Source: [Teams/getting-service-phone-numbers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/getting-service-phone-numbers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@heschelpop thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
