### ISSUE TITLE
Set up delegation on Teams Phone

### ISSUE THREAD

**Issue by sperantia** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4828]
Teams phone support "Set up delegation "
https://techcommunity.microsoft.com/t5/microsoft-teams-blog/a-refreshing-new-look-for-teams-phones/ba-p/1351532

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8d3dd879-564e-62ca-2095-3ef6ae4fab2d
* Version Independent ID: 8ed3dff3-b2b8-b3db-6db9-6bbecdb6cf5c
* Content: [Microsoft Teams での回線共有機能 - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/shared-line-appearance#feedback)
* Content Source: [Teams/shared-line-appearance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/shared-line-appearance.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@sperantia thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
