### ISSUE TITLE
Does Ribbon SWElite also support Local Media Optimization?

### ISSUE THREAD

**Issue by tangx007** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4829]
Does Ribbon SWElite also support Local Media Optimization? I get a Ribbon SBC SWe Lite Release 8.1 that highlight this FW version supports this technology 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad0130c8-4343-ba04-cd55-0c3305a14347
* Version Independent ID: 24db6f00-bfdc-ea9c-6922-e9f09e5cef27
* Content: [Direct Routing Local Media Optimization - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-media-optimization-configure#configure-sbcs-for-local-media-optimization-according-to-the-sbc-vendor-specification)
* Content Source: [Teams/direct-routing-media-optimization-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-media-optimization-configure.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@tangx007 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
