### ISSUE TITLE
It is not "Accecpted domain"

### ISSUE THREAD

**Issue by hishikitetsuya** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#483]
Accepted domain is a special term which means a domain owned by the organization. In spam filter setting, "**Allowed domain**" is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43bc0cae-682a-7227-35d6-d3c37545a3a4
* Version Independent ID: fbcd00ac-8899-fb95-28aa-dfc523b81c65
* Content: [Add the Microsoft Teams SMTP domain as an accepted domain in Exchange Online](https://docs.microsoft.com/en-us/microsoftteams/smtp-accepted-domain)
* Content Source: [Teams/SMTP-accepted-domain.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/SMTP-accepted-domain.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by kenwith** [comment]
@hishikitetsuya - thank you for this information. Would you be willing to open a Pull Request so you can get credit for fixing this one? Instructions for making edits can be found in the README in the bottom of the main repo here: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness

Please @ tag me and I will merge it right away. If you would rather I just go ahead and do it just re-open this one and let me know and I can do it too. Thanks!
