### ISSUE TITLE
outlook does not show teams group

### ISSUE THREAD

**Issue by hzareipour** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4830]
RE: new Microsoft 365 Groups generated as a result of creating a team in Microsoft Teams will no longer show in Outlook by default. 

I use MS Outlook for Mac 365. How can I show the group that in my desktop outlook?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d86301b-ce9c-388c-e563-9e5e5c27132e
* Version Independent ID: 07e4ae23-0966-e8f3-9b7c-4f6c02569eb0
* Content: [Microsoft 365 Groups and Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/office-365-groups#feedback)
* Content Source: [Teams/Office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-groups.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@hzareipour thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
