### ISSUE TITLE
Need an accessible guide to connecting to Teams with PowerShell.

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4831]
Especially if the account has MFA enabled. The reference is deep in this article, https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26362d70-cfce-2eea-077b-4aaa50f92e8b
* Version Independent ID: f52dcd4d-4f58-05c4-11b0-f1e3c95f4d89
* Content: [Teams PowerShell Overview - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-overview)
* Content Source: [Teams/teams-powershell-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Jmartinez589 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Jmartinez589 thank you for reaching out and helping improve MS Docs. Just for clarity are you suggesting adding this link to the article?

**Comment by Jmartinez589** [comment]
I think Joe has now taken care of this.

See, @Jmartinez589<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJmartinez589&data=02%7C01%7C%7C558f1773274a43884d2d08d7f69ddc34%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637249030163995149&sdata=fk%2BA5rpQvFwvKSaaYjXdAVBW7jLNH8Hjw9O1BueBiQ8%3D&reserved=0> A new page like this one has been created at https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-microsoft-teams-with-office-365-powershell<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Foffice365%2Fenterprise%2Fpowershell%2Fmanage-microsoft-teams-with-office-365-powershell&data=02%7C01%7C%7C558f1773274a43884d2d08d7f69ddc34%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637249030163995149&sdata=JTGrSd49TDKYC7MNmYTyN7bcHIN%2FcxqOhxi5F0ncRdc%3D&reserved=0>.


________________________________

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@Jmartinez589 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
