### ISSUE TITLE
Common scenario to be added

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4832]
hello, i see somebody else opened this issue in the past but did not have a definitive answer.
The scenario where an organization is on Teams only and the other on Skype for Business on-premises is not listed. Could you please add this?

Plus, the scenario "Let your Skype for Business Online users communicate with Skype for Business users from an on-premises organization." has an inconsistent suggestion, implying that the second organization is a Teams/Skype online one rather than Skype on-premises... please correct that!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external access (federation) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by teomonda** [comment]
![skypeonprem](https://user-images.githubusercontent.com/43137999/81413159-a54cbb00-914d-11ea-8689-d6cbb382b237.jpg)

**Comment by scanum** [comment]
@teomonda thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by teomonda** [comment]
Thanks, Manuela, for your reply. It makes sense for adding the new scenario.
Still the current one presented is incorrect, in my opinion. The scenario depicts collaboration between a Skype for business Online and a Skype for Business from an on-premises organization and then on the second column we talk about an two Skype online/Teams organizations. Can you please correct that? (it is the scenario that i included the screenshot about)
