### ISSUE TITLE
Not clear information

### ISSUE THREAD

**Issue by ivanja81** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4833]
We don't have transport relays as IP's described in this document which causes confusion if to open ports form 13.107.x.x or not please adjust.

**Comment by scanum** [comment]
@ivanja81 Hi, please link the documentation you are referring to. Thanks.

**Comment by lindspea** [comment]
@ivanja81 thank you for reaching out. For me to help you further please could you send me the link to the article you are referring to. Thanks.

**Comment by scanum** [comment]
@officedocspr   We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by ivanja81** [comment]
Hi Manuela,

I think something went wrong. I never got an mail around this.

What was the question?

Ivan
