### ISSUE TITLE
Ability to enable Team Members to add tags to themselves

### ISSUE THREAD

**Issue by reallyely** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4834]
In my team, I want team members to be able to self-serve in adding tags to themselves without being an owner or allowing them to _add new_ tags.  This will minimize what could be a labor intensive team moderation and empower users to focus the conversations more easily.

Is this a feature on the roadmap? I've looked for bots as well and I can't find any bots that help manage this.

**Comment by scanum** [comment]
@reallyely thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
