### ISSUE TITLE
Confusion over setup with hybrid configuration

### ISSUE THREAD

**Issue by embj** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4838]
I'm in the process of testing out Phone System and setting up call queues. There was a lot of confusion on how we set it up because we're in a hybrid configuration with SfB.

I discovered that in order to assign a phone number that's hosted purely online (no Direct Routing in our environment) to a call queue, we had to use our @tenant.onmicrosoft.com domain when creating the resource account. If we used any of our personalized domains, it wouldn't let us assign the resource account to the call queue. Can this be more clearly explained?

Also, can the steps to assign the resource account to the call queue via PowerShell be added? I had a hard time figuring this out until I stumbled across this cmdlet: https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlineapplicationinstanceassociation?view=skype-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@embj  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@embj 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
