### ISSUE TITLE
Cant find the GatewaySiteLbrEnabled parameter under cmdlet example? 

### ISSUE THREAD

**Issue by tangx007** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4839]
Under the "Define the virtual network topology" part, it says that "downstream SBCs must be enabled for LBR by setting the GatewaySiteLbrEnabled parameter to $true", but I can't see any cmdlet relevant to that parameter under the downstrean SBCs (such as VNsbc or IDsbc), then my confuse is that should we still need to add GatewaySiteLbrEnabled to the powershell CMD or this doc need to be updated ?

Refer:
https://docs.microsoft.com/en-us/microsoftteams/direct-routing-media-optimization-configure#define-the-virtual-network-topology

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad0130c8-4343-ba04-cd55-0c3305a14347
* Version Independent ID: 24db6f00-bfdc-ea9c-6922-e9f09e5cef27
* Content: [Direct Routing Local Media Optimization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-media-optimization-configure#define-the-virtual-network-topology)
* Content Source: [Teams/direct-routing-media-optimization-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-media-optimization-configure.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@tangx007 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by tangx007** [comment]
I think this is a description issue of this topic. 
Under the "Define the virtual network topology" part, it says that "downstream SBCs must be enabled for LBR by setting the GatewaySiteLbrEnabled parameter to $true"

but since it says "MUST BE", then the GatewaySiteLbrEnabled parameter should be shown in the example cmdlet to let the reader know.

I know that if no GatewaySiteLbrEnabled parameter under the set-csonlinepstngateway is also ok, but why this article says "MUST", can you clarify it?
