### ISSUE TITLE
Is allowed domain setting related to automatic picture download? 

### ISSUE THREAD

**Issue by hishikitetsuya** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#484]
I checked automatic picture download behavior in my tenant in the following step:

1. Add a user to a Teams group, and the user receive the notification from "noreply@email.teams.microsoft.com."
2. The notification is delivered to user's Inbox, and automatic picture download is disabled.
3. Add the domain "email.teams.microsoft.com" to "Allowed domain" of my default spam filter.
4. After few hours, automatic picture download is still disabled.
5. When I add the sender to safe sender list, automatic picture download is enabled.

As a result, it looks like automatic picture download is disabled by default even if the domain is listed on spam filter's allowed domain. If my understanding is correct, description about automatic download in this page is really confusing and I recommend to remove it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43bc0cae-682a-7227-35d6-d3c37545a3a4
* Version Independent ID: fbcd00ac-8899-fb95-28aa-dfc523b81c65
* Content: [Add the Microsoft Teams SMTP domain as an accepted domain in Exchange Online](https://docs.microsoft.com/en-us/microsoftteams/smtp-accepted-domain)
* Content Source: [Teams/SMTP-accepted-domain.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/SMTP-accepted-domain.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by kenwith** [comment]
@hishikitetsuya - thank you for taking the time to research and provide your results. I am not a SME in this area and I think you know much more than I do on this one. Would you be willing to open a Pull Request to add your valuable knowledge into the article? You would then get contributor credit and show up here: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/graphs/contributors

If you are willing to submit a Pull Request you can find out how to do it in the README that shows up at the bottom of the main repo here: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness

If you would rather not submit a Pull Request it is very much appreciated that you submitted the information through the issue list here. I will look for a subject matter expert that can submit a Pull Request and get this merged to make the article less confusing.

**Comment by kenwith** [comment]
Thanks for PR @hishikitetsuya and sorry for taking so long to close this out. Much appreciated!
