### ISSUE TITLE
Missing user in teams Actvity report

### ISSUE THREAD

**Issue by xongor** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4841]
I need create a user activity report, but several users are missing in the report. When I check the user details I can see the s/he participated in meeting, but s/he does not appear any report. Can you help me to fix this report?

---
#### A dokumentum adatai

⚠ *Ezt a szakaszt ne szerkessze. A szakasz a docs.microsoft.com ➟ GitHub-problémák hivatkozásaihoz szükséges.*

* ID: 5b138331-2f10-a05d-7e88-68e62e0b3e4f
* Version Independent ID: f923b648-ffe4-8a8a-c189-6e31f1032c10
* Content: [Microsoft Teams usage report - Microsoft Teams](https://docs.microsoft.com/hu-HU/microsoftteams/teams-analytics-and-reports/teams-usage-report?source=docs#feedback)
* Content Source: [Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@xongor thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
