### ISSUE TITLE
User list with no User ID shown

### ISSUE THREAD

**Issue by NicolasVelasco** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4843]
Hello, I've used the Power BI reports for Teams and yesterday we had a meeting with a conference ID which is shown and on the report it say we had 12 users (as it was) but on the report User list for I only see my mail and then empty user ID's with the same conference ID. I guess thay are the other participants, but can't see the names.
When clicking on USERs filter... I can only see around 20 out of 150 in the teams groups.... Is there anything to be configured on the server so I can have all users available?????
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfbb1a90-d5f1-217e-1880-59afe121d979
* Version Independent ID: 7f6c85ae-f2c6-4b0b-6c8a-9bfcbe394328
* Content: [Use Power BI to analyze CQD data for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cqd-power-bi-query-templates#feedback)
* Content Source: [Teams/CQD-Power-BI-query-templates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-Power-BI-query-templates.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@NicolasVelasco thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by NicolasVelasco** [comment]
Ok, i'll do irt. thanks you
