### ISSUE TITLE
Guests statistic in the Teams Usage report

### ISSUE THREAD

**Issue by SylvM1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4844]
I do not really understand the "guest users" statistic in the Teams usage report in the Teams admin center. In the current explanation on the website it says "Guests is the number of guests in the team in the specified time period.". However, in our company we do not have any Teams yet (we do not collaborate in Microsoft Teams teams yet, we only use chat and meetings features). So the definition does not make sense in our case, as it shows 36 guest users. 

I can see daily guests statistics in the past 7 days, ranging from 4 to 21 each day. The statistic underneath the graph however shows "Guests: 36" which isn't the sum of the daily guest users. My question, what does this then mean? My only logical explanation is that it means that we had 36 unique? guest users in Teams meetings the past seven days, as we do not chat with external users either. Can you confirm this? 

Hopefully you can clarify.

Kind regards,

Sylvester

**Comment by scanum** [comment]
@SylvM1 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by SylvM1** [comment]
Hi scanum,

I can do that, but what I want to point out is that the explanation of what the Teams user statistics are on this website (https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report) of Microsoft is outdated or inaccurate.

From your comment I derive that you are saying that the user statistics I see (specifically "Guests") is not correctly shown in my user statistics report?

Kind regards,

Sylvester
