### ISSUE TITLE
Global policy is set to Discover Private Teams but we cannot search for them

### ISSUE THREAD

**Issue by daveak01** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4845]
Hi there, we can't see any of our private teams when searching for them in the client even though we have this feature enabled in the global policy, any ideas ?

**Comment by scanum** [comment]
@daveak01 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
