### ISSUE TITLE
Blocking Teams app in browser block access to all App policies pages in Teams admin portal

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4848]
Hi! Please add notification that people who manage apps, app permissions policies and app setup policies need to be able to have access Teams in browser. Having a defined conditional policy in AAD that blocks Teams in browser will block also access to these 3 pages. Since there is no supported PS cmdlet to manage app permissions policies then such policy will disable ability to manage the policies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b51eda6c-168c-7d99-7cc1-992b3d8feef2
* Version Independent ID: 118a1b8f-f4b7-a778-70b1-d3161fc548ab
* Content: [Manage app permission policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-app-permission-policies)
* Content Source: [Teams/teams-app-permission-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-permission-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Larryngolog thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Larryngolog** [comment]
Hello. This is an efect of opened service ticket - we noticed the issue, opened the ticket and got information from support that the issue was result of blocking access to Teams from browser with conditional access. And the outcome is what I mentioned in my original post - please call out in the docs that admins who want to manage these settings need to have browser access to Teams enabled in conditional access.
