### ISSUE TITLE
3PIP phones?

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#485]
There's no mention here of support for 3Pip phones. Can they do pickup?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b0d958a-9d50-5320-5601-2479ad501515
* Version Independent ID: 95968d67-8b43-0725-bb8c-b1fbf9a3f277
* Content: [Plan for Group Call Pickup in Skype for Business 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/enterprise-voice-solution/group-call-pickup#clients-supported-for-group-call-pickup)
* Content Source: [Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/group-call-pickup.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/group-call-pickup.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
Hi Torren - I would recommend opening a service ticket regarding 3PIP phones. Please feel free to open a Pull Request to update docs or you can also open an issue to get docs updated too.
