### ISSUE TITLE
Reporting via API or Powershell

### ISSUE THREAD

**Issue by vinayshekhar-github** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4850]
My customer is wanting to get the updated Teams User Activity report from the Teams Admin Center as they're building a custom dashboard using this data. We have API's available for the O365 Admin Center reports, however is there a way we can get this for the reports in Teams Admin center? Any API or Powershell cmdlet??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b138331-2f10-a05d-7e88-68e62e0b3e4f
* Version Independent ID: f923b648-ffe4-8a8a-c189-6e31f1032c10
* Content: [Microsoft Teams usage report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-usage-report#feedback)
* Content Source: [Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@vinayshekhar-github thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
