### ISSUE TITLE
MS Teams Admin audit log

### ISSUE THREAD

**Issue by TomasAEVI** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4856]
Hi,

i hope this wasn't already solved or an issue somewhere else but i can't find it.
I have trouble with getting correct audit results for changes in org-wide setting in MS Teams Admin centre.

I have used "Audit search" from " O365 Security & Compliance" and powershell.
We made some changes in org-wide settings but the result of audit search is same: nothing.
![image](https://user-images.githubusercontent.com/63779931/81662793-6022d480-943e-11ea-8c2f-fb43364f760a.png)

Do anyone know what i am doing wrong or is there any other solution?
Thank you

**Comment by scanum** [comment]
@TomasAEVI thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by TomasAEVI** [comment]
Hi,

i will share this - at this moment MS Auditing is not able to look for "changes in organization settings" for MS Teams. Instead it is shown as either "Grant-CsTeamsUpgradePolicy" or "Get-CsTeamsUpgradePolicy" which is pretty unclear and users has to look for **all activities** instead narrowing the filter.

I hope this will be patched soon. Can it be somehow called to docs?
Thank you
