### ISSUE TITLE
Multiple Camera Setup

### ISSUE THREAD

**Issue by mauriceweber96** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4857]
Dear Teams Support,
could you please give a brief recommendation on how to connect and use multiple cameras with Microsoft Teams? What additional software/ hardware is necessary and what would you recommend? We would like to connect multiple external professional cameras. 

Thank you for taking the time to respond.  

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 5bf01435-a73b-4bf2-5845-e4cf50c4c3a2
* Version Independent ID: 166e1800-80b1-2496-7160-3040c5b23c3d
* Content: [Voraussetzungen für Microsoft Teams-Räume - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/rooms/requirements#feedback)
* Content Source: [Teams/rooms/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/requirements.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@mauriceweber96 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
