### ISSUE TITLE
Can we have some instructions for adding Guest presenters to a Teams Live Event? 

### ISSUE THREAD

**Issue by deevincentday** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4858]
I have tried several times and the presenters were unable to join.  There is a distinct lack of clarity in the documentation you have provided so far.  I have seen mention of federated users but have no idea how to federate a user.  

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/teams-live-events/plan-for-teams-live-events#feedback)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by deevincentday** [comment]
To clarify, the guest presenters were unable to join as presenters.  They got into the event but as participants.  Also there are no instructions regarding whether to select anonymous login or whether they need to create an account.  

If users need to be federated why can this not happen automatically when you add them to the Teams Live Event?

**Comment by analugama** [comment]
To add Guest as presenters to a live event on Teams you should:
- Configure on the tenant the option the Guests can share screen
Go to: https://admin.teams.microsoft.com
Org-wide settings > Guest access > Meeting > Screen sharing mode > ON
- Add the user as a Guest in the Organization (from the admin portal)

**Comment by scanum** [comment]
@deevincentday Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@deevincentday thank you for reaching out. Please let me know if @analugama answered your question or if you need further assistance.

**Comment by v-edserr** [comment]
I am currently with a user that has the exact same problems as OP has. Clear concise information would be immensely helpful.

**Comment by CosmeSilva** [comment]
I read instructions sent by @analugama and on "Screen sharing mode" I don't have the option "ON".
In my case, the value of the field is "Full screen".
Even though, I don't manage to have guest users as presenters.
Clear guidance on how to do that would be greatly appreciated.

**Comment by lindspea** [comment]
@deevincentday please let me know if this article helps at all. I see it's been updated recently. https://docs.microsoft.com/microsoftteams/manage-external-access. Please also note the info in this article - "Non-authenticated anonymous users can't be invited as producers or presenters in Teams live events." Let me know if you need anything further.

**Comment by deevincentday** [comment]
Not really.  I do not have admin access to add domains to teams or active directory.  I simply want to federate individuals who will have email addresses on various domains like Gmail, Hotmail, outlook and others.

I need to set up speaking events featuring different speakers each month.

Regards

Dee

Sent from my Windows 10 device

**Comment by lindspea** [comment]
@deevincentday as far as I understand only people with admin access can do this. @LanaChin please could you assist?

**Comment by LanaChin** [comment]
Hi @deevincentday  - thanks for your feedback and helping us to improve our docs. This article has been updated with steps for how to set up a guest as a presenter in a live event.
