### ISSUE TITLE
You can't send messages because you are not a member of the chat.

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4860]
A lot is to be found on the internet about this message, except no clear explanation nor a solution.
What is going on in this case, and how can it be solved? Organization A organizes a meeting, members of organization B attend (they have no account and are not guests in A's tenant). Some users of B can participate in the meeting chat, others can't and receive the above message. Clearing the Teams cache (C:\Users\...\Appdata\Roaming\Microsoft\Teams\Cache), restarting Teams (including explicit sign out) does not help. User voice entry exists: https://microsoftteams.uservoice.com/forums/908686-bug-reports/suggestions/38262412-unable-to-rejoin-meeting-chat but I would also like a little explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [What the guest experience is like - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-experience)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@andrePKI thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
