### ISSUE TITLE
Can't filter rows by Start Date

### ISSUE THREAD

**Issue by Zloy51Geniy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4861]
Hello, tell me please, is it possible to filter the resulting table using the "Start Date" column by the date range, if so, how? I have already tried all possible options and everywhere I get errors of the form:
  "OLE DB or ODBC error: [Expression.Error] We couldn't fold the expression to the data source. Please try a simpler expression .."
An example of one of the queries:
  "NewTable = FILTER (Query1; Query1 [Start Time]> DATE (2020; 4; 17))"

I really hope for your help, thanks in advance!
---

* ID: 067e8376-df94-9a44-5263-cd1fc84879bf
* Version Independent ID: 924240c8-52c5-42db-36b8-28751f838784
* Content: [Установка соединителя Power BI для использования шаблонов запросов CQD - Microsoft Teams](https://docs.microsoft.com/ru-ru/microsoftteams/cqd-power-bi-connector#feedback)
* Content Source: [Teams/CQD-Power-BI-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-Power-BI-connector.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Zloy51Geniy thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
