### ISSUE TITLE
Bluetooth beaconing on XML?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4864]
New versions of MTR has make "Bluetooth beaconing" available the devices. But how this is covered by the XML? You have the following attribute:
**BluetoothAdvertisementEnabled**
Is this for bluetooth beacoming or something else? If tha is, then how we could control the checbox?
![image](https://user-images.githubusercontent.com/43988151/81694984-b0179080-946a-11ea-9c72-11cadf7aa08c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25a70665-5bf1-14f7-1df0-7596effcaf48
* Version Independent ID: 813cf005-2777-9419-d1ce-3f9401ac267c
* Content: [Remotely manage Microsoft Teams Rooms device settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/xml-config-file)
* Content Source: [Teams/rooms/xml-config-file.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/xml-config-file.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Petri-X thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Petri-X** [comment]
Sorry @scanum, cannot agree you. There is no issue on the product. This was simple question of which one of the XMLs control the bluetooth beaconing.

I'm a bit confused, if you do not know how the product is working, but you are still writing these documents?

Correct me if I'm wrong, you are asking me to pay money for support requests about something which then I'm giving the results to you as free of charge?
