### ISSUE TITLE
Browser/OS support

### ISSUE THREAD

**Issue by thomasbinder** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#487]
Currently the article reads like the listed browsers are supported across operation systems. My understanding is that certain browsers are only supported on certain operation systems -- otherwise people will assume that the web client would be supported on mobile browsers or Linux.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients#feedback)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by chuckedmonson** [comment]
@thomasbinder -- Thank you for your feedback. Can you provide specific wording for how you think the article should be updated? Thank you

**Comment by thomasbinder** [comment]
@kenwith unfortunately I don't have the correct information. Can you find the PM?

**Comment by kenwith** [comment]
I added this to the backlog so we can prioritize and get a PM for this. Will report back here. Closing for now since it is in the backlog system. Commenting here will re-open though.

**Comment by Nosferatu-Dk** [comment]
Firefox - Add Blocker Plus
Disable on Teams, and it will work.
If not a death loop will keep reloading the site, with a comment below a teams icon, stating Ups, something went wrong
