### ISSUE TITLE
Is Number of people in a meeting (can chat and call in) : 350?

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4870]
That's what this page (
https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#meetings-and-calls ) shows (2020-05-12 17:15 GMT; UK).  But I can find no mention of this increase to 350 anywhere; it's not mentioned in the roadmap (https://www.microsoft.com/en-in/microsoft-365/roadmap?filters=Microsoft%20Teams)

It's good news if it's correct! But is it a typo...?

Number of people in a meeting (can chat and call in) : 350

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#meetings-and-calls)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@anwarmahmood1 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by michaelkellyfrombelfast** [comment]
This would be great. Many of our University classes are larger than 250. The 350 increase is desperately needed.

**Comment by lindspea** [comment]
@LolaJacobsen please confirm if typo and I'll change it in PR. Roadmap says 250?

**Comment by Icemanvw14** [comment]
Was this 350 a typo or did the increase apply to the Teams platform which could cause issues? Really need to get to 300 limit increase

**Comment by iamalexmang** [comment]
An additional article mentions the limit to be 350, rather than the 250: https://docs.microsoft.com/en-us/microsoftteams/quick-start-meetings-live-events.

**Comment by LolaJacobsen** [comment]
Current limit is 250, but we expect the 350-person limit to release any day now. I'm standing by with documentation updates as soon as this change hits the outer rings.

**Comment by Icemanvw14** [comment]
Are there any estimate timelines when the increase to 350 will be implemented?
