### ISSUE TITLE
Remove M365 Apps from Base Plan lists 

### ISSUE THREAD

**Issue by MarkBratton** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4871]
None of the tables under https://docs.microsoft.com/en-us/MicrosoftTeams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=small-business#what-voice-features-are-available-with-my-plan should include M365 Apps for enterprise as a qualifying base plan. Only plans that include Teams qualify for the add-ons. Although the M365 Apps install package includes bits for installing the Teams client, it does not include a license for the Teams service itself. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abae7324-861d-7ca7-7239-a5df8fd927d5
* Version Independent ID: 8a30bd2f-9bc3-a0a8-8b31-d53836ead4d0
* Content: [Microsoft Teams add-on licenses - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=small-business#feedback)
* Content Source: [Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@MarkBratton Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@MarkBratton thank you for reaching out and helping improve MS Docs. Just for clarity, which part of the article are you suggesting needs to be updated?

**Comment by MarkBratton** [comment]
In the "What voice features are available with my plan?" each tab has a table image and in each of those tables under "Base plan" all references to "Microsoft Apps for business", "Microsoft 365 Apps for business", "Microsoft Apps for enterprise" and "Microsoft 365 Apps for enterprise" should be removed. Thanks

**Comment by lindspea** [comment]
@LanaChin please can you have a look at this and let me know if you can provide the updated screenshots so I can do the PR (if this is applicable)?

**Comment by LanaChin** [comment]
I've updated the screenshots to remove the references to Microsoft 365 Apps for enterprise and Microsoft 365 Apps for business.
