### ISSUE TITLE
Phone Merging

### ISSUE THREAD

**Issue by davidmaddocks** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4872]
When I use the phone audio option and have Teams call me, it announces me as "unknown caller" even though I input my number while I am logged in. Why announce me? Can I merge audio and video as I do on Zoom?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b759f354-bf74-3cff-0c96-3b28a27ee997
* Version Independent ID: fb2d8a68-f35a-bbee-a306-72ee20a450a3
* Content: [Set up the Call me feature for your users - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-the-call-me-feature-for-your-users#feedback)
* Content Source: [Teams/set-up-the-call-me-feature-for-your-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-the-call-me-feature-for-your-users.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@davidmaddocks thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
