### ISSUE TITLE
"This team has guests" 

### ISSUE THREAD

**Issue by microsoftsearch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4873]
Hello, 

The feature described above appears to be out of date. This no longer appears to show when a guest is added to a team. Instead a guest tag with with the number of guests is added to the header. Can the article be updated to reflect this change? Thank you in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [What the guest experience is like - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-experience#feedback)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@microsoftsearch Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@LanaChin please could you assist with the screenshot and I'll have the PR done.

**Comment by LanaChin** [comment]
Reached out to PMs.

**Comment by LanaChin** [comment]
Thanks so much @microsoftsearch for your input and helping to improve our docs.  The doc is being updated to reflect this change.
