### ISSUE TITLE
Auto Delete for Messages in Microsoft Teams

### ISSUE THREAD

**Issue by JamieFHP** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4874]
Is there a way to set up auto delete of older messages in teams? For instance, can messages older than 14 days be automatically be deleted from all chat groups in Teams?

**Comment by scanum** [comment]
@JamieFHP thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
