### ISSUE TITLE
Need to specify which countries have a 100 minute/month minimum usage requirement

### ISSUE THREAD

**Issue by pschneidermsft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4876]
This page states:  "In many countries/regions, the regulator/telecommunication agency in the country/region requires each toll free phone number to maintain at least 100 minutes of usage per month in order to retain the number."  But none of the country pages note whether or not this requirement applies.  This is creating confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d4bb5c7-dcc3-60bb-dd4a-88a9dc5cfa3d
* Version Independent ID: 5eb5f2d4-7d27-1b14-da1f-98a25512fb29
* Content: [Toll-free dialing limitations and restrictions - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/toll-free-dialing-limitations-and-restrictions#feedback)
* Content Source: [Teams/toll-free-dialing-limitations-and-restrictions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/toll-free-dialing-limitations-and-restrictions.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by lindspea** [comment]
@pschneidermsft thank you for reaching out. As far as I understand it applies to all countries. @tonysmit please could you confirm.

**Comment by pschneidermsft** [comment]
But that doesn’t make sense.  For example, in the US toll-free numbers are regulated by the FCC under 47 FCR Part 52 Subpart D, which prohibits warehousing and hoarding, but does not mandate a minimum monthly usage rates.

**Comment by tonysmit** [comment]
I've contacted the PMs to get a confirmed response to this. Please hold and I will report back.

**Comment by tonysmit** [comment]
Checking back. Getting in touch with another PM/dev. I need to add a list of those countries that require 100 minutes for toll free. Please hold again.

**Comment by tonysmit** [comment]
Checking back in. Still waiting on the PM. According to the first PM, they don't have a list and it was specific to a carrier. However, the next PM is working on creating a list. I will update the topic (I have other updates to do as well) and put a note on the parent article saying that some countries require a TF minimum. Then add a row for each country/region that will require this once I get the list from them. Does that work? I should be able to get the updates done in a week or so to address this issue. I have a tracking bug for myself as well. Thanks, Tony

**Comment by pschneidermsft** [comment]
Yes, I think that would work!




Patrick Schneider | Microsoft | Enterprise Search Group | Escalation Engineer | d: +47 2301 1339 | http://www.microsoft.com/enterprisesearch<https://emea.mail.microsoft.com/owa/redir.aspx?C=4085a32bcb274c738ef3359503168033&URL=http%3a%2f%2fwww.microsoft.com%2fenterprisesearch>
________________________________
