### ISSUE TITLE
IT

### ISSUE THREAD

**Issue by Plymothian** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4878]
Why doesn't the page show the definitions for all fourteen columns? Also, the example row doesn't align to the column structure. I linked back to this page when attempting to provide feedback on the tenant data file format and building data file structure page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f8119c9-61af-b469-af98-ddd37764c0ca
* Version Independent ID: 7d829a74-9df7-5b6f-8e1c-44d3e5d38f75
* Content: [Add and update reporting labels - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/learn-more-about-site-upload#feedback)
* Content Source: [Teams/learn-more-about-site-upload.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/learn-more-about-site-upload.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@scanum Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Plymothian thank you for reaching out and helping to improve MS Docs. Please could you provide a bit more clarity on what you recommend needs to be changed in the article so I can assist further.

**Comment by scanum** [comment]
@Plymothian We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
