### ISSUE TITLE
Improve documentation on Exchange Hybrid and Version requirements

### ISSUE THREAD

**Issue by gabsto-ms** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4879]
Hello,

I suggest adding some clarifications for the Exchange on premises hybrid requirements. 

Please include that an Exchange "full" hybrid is required.  Only full hybrid configures OAuth (minimal hybrid does not)
Also, regarding the dependency in version, it would be much clearer if we mention that the mailbox also needs to be on an &gt; Exchange 2016 CU3 server.
As it is now written, the information in the article could be misinterpreted - that only the hybrid server needs to be on version &gt; Exchange 2016 CU3. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact#feedback)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@scanum Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@gabsto-ms thank you for reaching out and helping improve MS Docs. I see the article was updated this week with important information. Please let me know if you still need assistance.

**Comment by scanum** [comment]
@gabsto-ms Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
