### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4882]
Can you clarify what this statement means: "Federation must be enabled for the external communications for the online tenant."?
I am unable to understand it at the level of basic English.
"Federation must be enabled" is a concept from Skype for Business. The equivalent in Teams in "External access".  "For external communication" presumable means to communicate with an external partner. What does "for the online tenant" mean? Should it read "with the online tenant"? If it means that, does that mean that the Skype for Business service must enable federation WITH the online tenant? If that is the case, and assuming they both use the same domain name, then how do they federate, if the federation is closed? Does it mean that the domain must be allowed to federate with itself? Or does it use the onmicrosoft.com domain suffix?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c0ab608-c57e-0e72-6071-5fc02cf6217c
* Version Independent ID: 73c13bf0-4247-ad87-e3be-7d9a59ab457e
* Content: [Plan hybrid connect - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-hybrid-connectivity)
* Content Source: [Skype/SfbHybrid/hybrid/plan-hybrid-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/plan-hybrid-connectivity.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Air-Git Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Air-Git thank you for reaching out and helping improve MS Docs. I found this in another article. Would this provide more clarity? "Federation must be enabled for the external communications for the online tenant, which is configured by using the Skype for Business Online Control Panel."

**Comment by Air-Git** [comment]
My point is that the sentence does not work, in English. It is simply incomprehensible. What does it mean?

**Comment by lindspea** [comment]
@Air-Git can you possibly recommend how you would change the sentence to make it more comprehensible?

**Comment by Air-Git** [comment]
That's my point. I don't know what it is supposed to mean. I think it can be deleted.
The list of points above it specify that federation needs to be enabled. The confusing point is whether you need also to "federate" with the online tenant.
This page says explicitly that you need to federate with the Office 365 tenant: [Configure Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/configure-federation-with-skype-for-business-online#configure-your-on-premises-edge-service-to-federate-with-microsoft-365-or-office-365). But how is unexplained. The on-premises service is already @mydomain.com, so who would I federate with? Isit  the onmicrosoft.com domain? 
If it is one of these, then the sentence in this issue might be referring to that. It might mean "Federation with the online tenant needs to be enabled".
But I don't think this is the case. In which case the additional sentence is both redundant and misleading.

**Comment by lindspea** [comment]
@CarolynRowe Could you please confirm?

**Comment by CarolynRowe** [comment]
This issue is two years old.  We've received no other comments about the wording so I do not think it meets the bar for adding to our backlog.  I'm going to close this issue.
