### ISSUE TITLE
Need Clarification - Chatting with an external account

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4885]
This document doesn't include the scenario or reference to how to chat 1:1 with an external contact. Can you create a new document or edit this one with more clarity.

Scenario - tenant 1 with a Teams license, wants to 1:1 chat with another contact in Teams tenant 2. Assumption, both have external access enabled. Search by e-mail address in Teams doesn't find the other contact. Something must be missing. This document may be technically correct, but it doesn't answer why you cannot find the other contact.

Still investigating, but found this UserVoice post, https://microsoftteams.uservoice.com/forums/555103-public/suggestions/39232003-i-want-to-be-able-to-chat-with-an-external-member

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f080a5c-4268-1db4-566f-f1edc27920b5
* Version Independent ID: ac556a92-58af-3e05-f53b-0fc00afc96c0
* Content: [Communicate with users from other organizations in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/communicate-with-users-from-other-organizations#feedback)
* Content Source: [Teams/communicate-with-users-from-other-organizations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/communicate-with-users-from-other-organizations.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by LolaJacobsen** [comment]
@vinbelms can you weigh in here please?

**Comment by Jmartinez589** [comment]
Alright, it may seem basic but it just is no where to be found and one simply and clearly written article would be great.

There are several complimentary articles but none is very clear. They all have technical information that may be accurate but for a lay person, the guidance is not very straight forward.

Here is one thread that I found. https://techcommunity.microsoft.com/t5/microsoft-teams/getting-started-creating-a-team-accross-two-tenants/m-p/304576
It has a nice title "Getting started creating a team across two tenants"

I think I figured it out. Here are the steps.
1.	You basically have to have guest access turned on. From at least one of the tenants.
2.	Once you do that from the tenant that can accept guests, you can then invite the other person. There is an article about that. https://support.office.com/en-us/article/Add-guests-to-a-team-in-Teams-fccb4fa6-f864-4508-bdde-256e7384a14f
3.	They will receive a notification in e-mail, and once they click on it, basically they are accepting the invitation. They key here is that they have to accept the invitation. It goes through a series of checks (magical configuration that only the wizard knows)(We can revisit this later, especially when it comes to troubleshooting)
4.	Once that step 3 is complete and seemingly only then can the two chat one another.

Once you write it up, you can the add cross-references to 
https://docs.microsoft.com/en-us/microsoftteams/native-chat-for-external-users
https://docs.microsoft.com/en-us/MicrosoftTeams/guest-joins (this one does provide the information that once a guest joins then they can chat, but if I were searching for "chat in Teams across two tenants" I wouldn't find it.

**Comment by LolaJacobsen** [comment]
@vinbelms what content updates should we make, based on Jmartinez589's suggestions?

**Comment by LolaJacobsen** [comment]
@Jmartinez589 @vinbelms 
WRT 1:1 chat with an external access user: Check out our external access article: https://docs.microsoft.com/en-us/MicrosoftTeams/manage-external-access

See this note, which explains why you may not be able to start a 1:1 chat with an external user:
Currently, to federate within the Microsoft Teams app to an external user outside of your organization who's not currently a guest of your Azure Active Directory (Azure AD) or tenant, you must be correctly set up for hybrid and moved to Skype for Business Online. As of February 25, 2019, Teams doesn't support native federation without the user of the SIP profile being homed in Skype for Business Online. For more on setting up your account for hybrid and then moving to Teams, see Upgrade Skype for Business hybrid deployment to Teams.
