### ISSUE TITLE
Details on how private channels files are implemented in Sharepoint

### ISSUE THREAD

**Issue by skywalkerisnull** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4886]
The setup of a private channel in teams seems to not create a folder in SharePoint that can be viewed at the top level (i.e. .../sites/Team1/Shared Documents) it can be access by directly going to the corresponding URL, but if you have the permission to see the folder and contents, it does not appear in the Shared Documents. Is this to do with permissions on the channel and folder being different to the parent folder? Or is this a bug? What is the intended/designed behaviour of files for private channels in a team?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60fd4eb7-6f1a-2dfa-27db-01c3a0d00f30
* Version Independent ID: c1688075-18bf-534d-f402-ee062840d83f
* Content: [How SharePoint Online and OneDrive for Business interact with Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/sharepoint-onedrive-interact#feedback)
* Content Source: [Teams/SharePoint-OneDrive-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/SharePoint-OneDrive-interact.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@skywalkerisnull Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@skywalkerisnull Thank you for reaching out and helping improve MS Docs.  This article applies to standard channels. File permissions for members and guests reflect whatever your admin has set in your SharePoint settings. These can only be changed by your admin. 
See also https://docs.microsoft.com/MicrosoftTeams/private-channels
Let me know if you need further assistance.

**Comment by scanum** [comment]
@skywalkerisnull Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
