### ISSUE TITLE
Linux Client Missing

### ISSUE THREAD

**Issue by solter** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4887]
This page is missing all the information about the Linux Client, despite the https://docs.microsoft.com/en-us/microsoftteams/get-clients discussing the Linux Client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d5e6d3-b7e0-d79f-0dea-ed423186a157
* Version Independent ID: ec6e68aa-552f-ab45-3c8e-92eff526b173
* Content: [Use log files in troubleshooting Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/log-files#feedback)
* Content Source: [Teams/log-files.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/log-files.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by solter** [comment]
the browser debug logs use the same shortcut on Ubuntu 20.04 as on windows (CTRL + Shift + Alt + 1)

**Comment by scanum** [comment]
@solter Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@solter thank you for reaching out and helping improve MS Docs. This article links to the article you mentioned above. Please could you provide a bit more clarity as to what you recommend changing in this article.

**Comment by solter** [comment]
The following information would have been helpful as I was working with teams on linux:
* which logs are generated by the teams client (by adding a new "linux" row to the table indicating which logs are created
* for the debug logs
** the keyboard shortcut to cause the linux client to dump out logs
** the directory into which the debug logs get dumped when created from the linux client
* similar information for the media/desktop logs would be nice, but less important

**Comment by lindspea** [comment]
@LolaJacobsen please could you assist. Is this perhaps in the pipeline for an update to the article?

**Comment by LolaJacobsen** [comment]
Checking with PMs Bill Weidenborner and Jatin Patel

**Comment by LolaJacobsen** [comment]
PM Bill Weidenborner is adding Linux info to log-files.md. Thanks for the input.
