### ISSUE TITLE
Problems applying license changes in Microsoft Teams A5

### ISSUE THREAD

**Issue by aperezcortes** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4888]
when I apply a change for example assign an A5 license which is the one that has the Phone system function enabled and thus be able to walk the extension on the cell phone call external numbers all through Microsoft Teams it is pending and it has been 2 or 3 days waiting for the license and policies to apply but it remained there "pending" someone happened to him in the administration of Office 365 and teams.

A legend appears where it indicates that due to the Covid 19 the platform is saturated and that the changes can last up to 24 hours, but it has already been 3 days and nothing has forced the synchronization of AD Connect thinking that it could be that and it has not been 3 days and the users are pending

**Comment by aperezcortes** [comment]
![Captura de pantalla 2020-05-13 a la(s) 18 49 46](https://user-images.githubusercontent.com/57973166/81880828-aa45ac00-954b-11ea-8d82-bbd28c802546.png)

**Comment by scanum** [comment]
@aperezcortes thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
