### ISSUE TITLE
Teams Outlook plugin not visible after machinewide install 

### ISSUE THREAD

**Issue by Bart-Hoofd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4889]
The machine wide installer (v1.3.0.12058) with parameters ALLUSER=1 does not appear to create the Office plugin registry key:

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\Outlook\Addins\TeamsAddin.FastConnect]
"FriendlyName"="Microsoft Teams Meeting Add-in or Microsoft Office"
"Description"="Microsoft Teams Meeting Add-in or Microsoft Office"
"LoadBehavior"=dword:00000000
"CommandLineSafe"=dword:00000000

Creating the registry key manually will show the plugin in Outlook, and it seems to be working OK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi#non-persistent-setup)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Bart-Hoofd thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
