### ISSUE TITLE
Desktop client updates - Linux

### ISSUE THREAD

**Issue by 3vi1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4891]
&gt; "Teams desktop client updates are released every two weeks..."

This does not appear to be the case for the Linux desktop client, which has not been updated for nearly two months now - putting it 6 releases and many features behind the Windows/Web clients.  Is there a release schedule for Linux, or is it just packaged ad-hoc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6da28da-eb7b-d3ae-4c2f-8f87803b1830
* Version Independent ID: 8c42d7a2-80c6-86dd-347a-ed6d8d909c41
* Content: [Teams updates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-client-update#feedback)
* Content Source: [Teams/teams-client-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-client-update.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@3vi1 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@3vi1 thank you for reaching out and helping improve MS Docs. Please see this link - https://support.microsoft.com/office/update-microsoft-teams-535a8e4b-45f0-4f6c-8b3d-91bca7a51db1

**Comment by rkaravia** [comment]
> Please see this link - https://support.microsoft.com/office/update-microsoft-teams-535a8e4b-45f0-4f6c-8b3d-91bca7a51db1

@lindspea This link is not working for me ("Sorry, the page you’re looking for can’t be found.")

**Comment by scanum** [comment]
@3vi1 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
