### ISSUE TITLE
Record for tenant hosted in France

### ISSUE THREAD

**Issue by RuelleJoelleSmartView** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4894]
When will it be possible to record meeting for tenant hosted in France ? 

Thank you in advance :)

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
