### ISSUE TITLE
Comment about active users

### ISSUE THREAD

**Issue by Darrelo365** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4895]
Hi, we're an EDU tenant where students have Teams licences but it's not enabled at the tenant level for them. They are showing up in the active user report with 0 activity in all fields. We had around 800 of them so I emailed a sample to ask how they were using Teams. Replies where in two camps, those that could see the tile in the launcher and clicked it, and those who had a device with it preinstalled and it loaded on start up. All reported the same splash screen with words to the effect 'contact your administrator'. I did raised a ticket with premier support and they advised raising a user voice. I just wanted to share this information with you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ade1a4-092c-1132-44df-ee2c683fdd33
* Version Independent ID: 396b1aee-2f40-9895-9b00-07e38d11d31b
* Content: [Microsoft Teams analytics and reporting - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-reporting-reference#feedback)
* Content Source: [Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Darrelo365** [comment]
Hi, I've done that already. Microsoft Premier Support advice (via a ticket) was to raise a Uservoice. And here's the link https://microsoftteams.uservoice.com/forums/555103-public/suggestions/39250318-teams-usage-report-shouldn-t-include-active-user
