### ISSUE TITLE
Upload Assigments

### ISSUE THREAD

**Issue by droopycr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4898]
Hello, i have a problem when a student need to upload the assigment work, there's an error message to upload a file,  - Ther's an error to upload a file, please remove and try again-. This error show on PC Teams App, Web Browser, and Iphone app.

I remove the user on the Azure AD, and create it again, and same problem,

[Escriba sus comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Soporte para Microsoft Teams en la organización - Microsoft Teams](https://docs.microsoft.com/es-es/microsoftteams/known-issues)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by lindspea** [comment]
@Office Global

**Comment by scanum** [comment]
@droopycr thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
