### ISSUE TITLE
Microsoft 365 Apps are not eligible plans to get this add-on 

### ISSUE THREAD

**Issue by miguelvidex** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4899]
Microsoft 365 Apps for Enterprise and Business do not include Teams service, so you cannot add this SKU to that licenses, so it should not appear in the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35057f71-792b-a4e2-a2ee-a4908c11f3a4
* Version Independent ID: 7e23f067-1dcd-16f0-3f9a-ff8d13c1f659
* Content: [What is Microsoft 365 Business Voice? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/business-voice/whats-business-voice#feedback)
* Content Source: [Teams/business-voice/whats-business-voice.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/business-voice/whats-business-voice.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@miguelvidex Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@dstrome please can you confirm and I'll do a PR to fix.

**Comment by dstrome** [comment]
Supported SKUs have been updated.
