### ISSUE TITLE
Toll-free for Philippines

### ISSUE THREAD

**Issue by abrahamdsl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4900]
Hi, as per

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blame/live/Teams/toll-free-dialing-limitations-and-restrictions/toll-free-dialing-restrictions-in-the-philippines.md#L36

there should be a toll-free number.

But I think, you only meant toll-free if within the Manila Area/National Capital Region ----same area code----. I have an expectation that it should be toll-free **anywhere in the country**, for landlines at least, for example your competitor Cisco WebEx with their 1-800-1-110-2530 hotline for PLDT subscibers.

The only number provided at https://dialin.teams.microsoft.com/e5b24bd5-8a9d-490f-a988-5cde224ea698?id=718741352 , is for Metro Manila area only (area code 02). This means, I will have to be charged toll since I am dialing-in from Laguna province (area code 049).

Perhaps you do really have a nationwide toll-free number for dial-in, hidden somwehere? I did try 1800 82313413 using PLDT Landline, but it's an invalid number.

**Comment by scanum** [comment]
@abrahamdsl Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@abrahamdsl thank you for reaching out and helping improve MS Docs. Please can you send me the link to the Microsoft article you are referring to so I can assist further.

**Comment by abrahamdsl** [comment]
> @abrahamdsl thank you for reaching out and helping improve MS Docs. Please can you send me the link to the Microsoft article you are referring to so I can assist further.

Hi it's https://dialin.teams.microsoft.com/e5b24bd5-8a9d-490f-a988-5cde224ea698?id=718741352 , as mentioned in first comment.

**Comment by lindspea** [comment]
@tonysmit who would be able to help with this article?

**Comment by tonysmit** [comment]
Can you send me your email address that's not GH please. I will put you in contact with the PM. She's not yet on GH (I don't think).

**Comment by tonysmit** [comment]
@fafan - can you assist here please? Thanks, Tony

**Comment by abrahamdsl** [comment]
Hello fellows. Any update on this. Specifically, do we now have categorical answer if there is indeed a country-wide toll-free number [which might be subject to certain subscription level(s)], or only Manila-area one?

**Comment by lindspea** [comment]
@tonysmit @fafan any update yet please?

**Comment by tonysmit** [comment]
@ruizoscar and @fafan  - Can you help with this issue please?

**Comment by ruizoscar** [comment]
Hi, 
- By default, Microsoft assigns a toll number from the Manila region. Given number is the number specified as assigned to the tenant referenced in the original question.
- In addition to the support of toll numbers from Manila, Microsoft also supports toll-free numbers from the Philippines. The toll-free numbers are different from the toll numbers from Manila that were assigned to the customer.
- The customer can request acquire a toll-free number from the Philippines via the following instructions. Please note that toll-free numbers require communication credits (as outlined in the link): https://docs.microsoft.com/en-us/microsoftteams/getting-service-phone-numbers

**Comment by scanum** [comment]
@abrahamdsl Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
