### ISSUE TITLE
Chat options for Guests

### ISSUE THREAD

**Issue by MichelleLanguages** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4904]
I have done all of the steps mentioned. I have also gone through all the settings in Teams. I have created Teams with some people who have free accounts, but they cannot chat with me. Why is this? Also, with a B2B major corporation, some of my clients within that corporation can chat with me, some can't. I am able to share documents and use apps with some, but why is it that on two paid accounts I cannot share with some users. Also - Why can't my invited guests in teams I have created not chat with me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aacf04b6-87d3-d832-0996-489df1e68407
* Version Independent ID: 072a5553-7e46-9f23-c0fa-c3e9a1037723
* Content: [Troubleshoot problems with guest access in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/troubleshoot-guest-access)
* Content Source: [Teams/troubleshoot-guest-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/troubleshoot-guest-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@MichelleLanguages thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
