### ISSUE TITLE
Disable hybrid and decommissioning on-prem

### ISSUE THREAD

**Issue by Michal-Witwicki** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4905]
This article does not show the entire procedure of hybrid completion / server removal. I am sorry to say but it is useless. 

> Do not run Disable-CsUser in the on-premises environment

You must use Disable-CsUser if you finish the hybrid and remove the on-prem environment.

> Clearing the on-premises msRTCSIP attributes after you have migrated from on-premises could result in loss of service for users!

If you do not remove the msRTCSIP attributes, it causes a problem after synchronizing to Azure AD

Disable-CsUser is required but generates two problems, the first is that it removes the SIP address from the proxyAddresses attribute. The second problem is to leave sipfed.online.lync.com in the msRTCSip-attributes attribute.

If you do not clear the msRTCSip-attributes attribute, your online user status will be HybridOnlineSfbUser. After clearing the attribute and synchronization, the status will change to DirSyncSfBUser.

**Comment by scanum** [comment]
@scanum Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Michal-Witwicki** [comment]
@scanum My topic concerns the article https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/cloud-consolidation-disabling-hybrid. Can it be attached to this article?

**Comment by lindspea** [comment]
@Michal-Witwicki thank you for reaching out and helping improve MS Docs. It looks like the article was updated shortly after your message with some important notes. Please have a look and let me know.

**Comment by scanum** [comment]
@Michal-Witwicki  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
