### ISSUE TITLE
 Share screen and present a video with audio using Teams via iOS 13.4.1

### ISSUE THREAD

**Issue by AndresLopez1982** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4906]
Good afternoon.

I would like to know if I can share a screen and present a video with audio using Teams via iOS 13.4.1. I tested it in several ways but I haven't found a solution so far.

**Comment by scanum** [comment]
@AndresLopez1982 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
