### ISSUE TITLE
Licensing information is out of date

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4909]
This section needs to be updated:

In the Assign licenses section, you need to select Skype for Business Online (Plan 2) or Skype for Business Online (Plan 3), depending on your licensing and what you've decided in terms of needing Enterprise Voice. You'll have to use a Plan 3 license if you want to use Cloud PBX on Microsoft Teams Rooms. Minimally you will need CloudPBX for voice connectivity. Then configure hybrid voice or PSTN calling based on the PSTN connectivity method. See Microsoft Teams Rooms licenses for more details.

Should be using the room system license now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Microsoft 365 or Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/with-office-365)
* Content Source: [Teams/rooms/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-office-365.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@danmyhre thank you for reaching out and helping improve MS Docs. Just to confirm, are you suggesting removing the 4 bullet points under Microsoft Team Room requirements and replacing with your suggestions?

**Comment by danmyhre** [comment]
Hi - no, I am saying the licensing section needs to be re-written.   There is a room system SKU now.  You can't buy SfB Plan 2 or 3 anymore for this purpose.

**Comment by lindspea** [comment]
@LanaChin please could you help.

**Comment by LanaChin** [comment]
Reassigning to @dstrome as this is a Microsoft Teams Rooms article.

**Comment by dstrome** [comment]
hi @danmyhre - we're rewriting the Teams Rooms content in its entirety.  We should have the updates, including changes to licensing, published within the next few weeks.
