### ISSUE TITLE
Step 6 and Licensing

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4910]
In order to enable a CSMeetingRoom, you need to have enabled licensing.  You also have to wait.  In my case, it was about 15 minutes.

In the steps above, step 6 adds licensing.  That is fine.  But then below it has another section on adding licensing.  Licensing can't come after the room setup, it has to happen during the account setup.  So this statement at the end need to be updated:

After you've completed the preceding steps to enable your Microsoft Teams Rooms account in Microsoft Teams or Skype for Business Online, you need to assign a license to Microsoft Teams Rooms device. Using the Office 365 administrative portal, assign either a Skype for Business Online (Plan 2) or a Skype for Business Online (Plan 3) license to the device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Microsoft 365 or Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/with-office-365)
* Content Source: [Teams/rooms/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-office-365.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@danmyhre thanks again for your help improve MS docs. Would you recommend changing the statement to read as follows:  "You need to assign a license to Microsoft Teams Rooms device before completing the preceding steps to enable your Microsoft Teams Rooms account in Microsoft Teams or Skype for Business Online. Using the Office 365 administrative portal, assign either a Skype for Business Online (Plan 2) or a Skype for Business Online (Plan 3) license to the device."?

**Comment by danmyhre** [comment]
Yes, but instead of SfBO P2 or P3, I think you should reference the new SKU for a Teams Room:
https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-licensing

**Comment by lindspea** [comment]
@danmyhre I have updated the wording. I see your suggested link is showing in step 5 under "Assign a license to your account".

**Comment by scanum** [comment]
@danmyhre  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
