### ISSUE TITLE
Can't seem to add a Favorites in Contacts when you are a Guest

### ISSUE THREAD

**Issue by HenrikHL** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4915]
I am a guest in another tennant. I know there are limitations to guest privileges. It would be nice if it is possible to save a contact as Favorite in order to quickly access them. The option does not seem to exist:
![image](https://user-images.githubusercontent.com/3489388/82190715-c0f45600-98f1-11ea-92c7-04d6181401de.png)

**Comment by scanum** [comment]
@HenrikHL thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
