### ISSUE TITLE
Footnote numbering in table - incorrect

### ISSUE THREAD

**Issue by causeway74** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4916]
Can you please update the footnote numbers in the table on this page. No1 is referenced below, but it doesn't appear in the table.
No3 is listed in footnote but doesn't appear in table.
No4 says retention is supported for the shadow mailbox but the article that is linked to says that holds nor retention is supported for shadow mailbox. 

Additionally, can you please list for each column if OAuth is needed or not? This would add welcome clarity. OAuth isn't needed for private chat journaling for example. Having OAuth and AADConnect sync listed on the row header makes it look like OAuth is needed for all columns which it isn't. 

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/exchange-teams-interact#feedback)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@causeway74  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@causeway74 thank you for reaching out and helping improve MS Docs. It looks like the article has been updated in the interim. Please let me know if you need further assistance.

**Comment by causeway74** [comment]
@lindspea Hi, I don't see this reflected in the current article. The footnote numbering is still incorrect.

**Comment by lindspea** [comment]
@dstrome please could you assist regarding footnotes.

**Comment by dstrome** [comment]
Thanks for your feedback. I've updated the footnote ordering and removed the link to the outdated blog article. I will need to investigate the OAuth issue so this will take longer.
