### ISSUE TITLE
Diagram-Skype for Business Server 2015

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4918]
Looking at supported version, Shouldn't diagram mention Skype for Business Server 2019/2015? Right now, It mentions only Skype for Business Server 2019. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 469ac0c8-5c06-7f7f-fe1d-8cadb205572a
* Version Independent ID: 5c9987d5-4c98-8115-55c8-f629dbd25799
* Content: [Plan Cloud Voicemail service for on-premises users - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-cloud-voicemail)
* Content Source: [Skype/SfbHybrid/hybrid/plan-cloud-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/plan-cloud-voicemail.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@3novsan thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
