### ISSUE TITLE
Links have errors

### ISSUE THREAD

**Issue by kevinchai76** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#492]
When you download the PDF, the links are pointing to the wrong location, giving errors ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e26faf8c-529e-b317-5934-cd41cfe8fa24
* Version Independent ID: 3ddd5d0a-6dbb-4940-1814-8346e293701b
* Content: [Plan Direct Routing](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan)
* Content Source: [Teams/direct-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by MichaelLaMontagne** [comment]
Also broken links for Direct Routing in the site enablement playbook for voice (Excel): [site-enablement-playbook-for-voice-(playbook).xlsx](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/downloads/site-enablement-playbook-for-voice-(playbook).xlsx)

**Comment by MichaelLaMontagne** [comment]
Submitted Pull requests: 

- [Environmental-discovery-for-Microsoft-Teams-rollout.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/507)
- [1-onboard-prepare-my-service.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/506)
- [2-envision-make-my-service-decisions-direct-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/505)
- [onboarding-checklist-configure-direct-routing-in-Microsoft-Teams](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/504)
- [cloud-voice-deployment.md ](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/496)

**Comment by CarolynRowe** [comment]
Thank you for the feedback.  I've asked our vendor to check the links.
