### ISSUE TITLE
Additional Licensing Requirements

### ISSUE THREAD

**Issue by JeffBrownTech** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4924]
Under the "Using a Resource Account" section, it mentions that if you want to make or to receive calls to or from an external phone number that you'll need a phone system or business voice license. However, the Meeting Room license already has a phone system license associated with it. I believe this should be changed to needing a Calling Plan license instead, which would enable external calling. Can you verify this?

Meeting Room License Components:
https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-licensing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df34eea9-3e9e-acbf-3dde-ecf8e66956d1
* Version Independent ID: bab87875-e7a1-f109-f9cb-4dbe940908f3
* Content: [Deploy collaboration bars for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/devices/collab-bar-deploy)
* Content Source: [Teams/devices/collab-bar-deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/collab-bar-deploy.md)
* Service: **msteams**
* GitHub Login: @flinchbot
* Microsoft Alias: **mitressl**

**Comment by scanum** [comment]
@JeffBrownTech thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by JeffBrownTech** [comment]
This isn't a support issue, I opened this issue on the docs page to have the documentation verified if it is correct or not as it seems to be in conflict with what is already included in the Meeting Room license. Can we have someone verify it?
