### ISSUE TITLE
Network Testing Companion is no longer available

### ISSUE THREAD

**Issue by sagy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4925]
"You can use the Network Testing Companion to confirm that your network locations are ready for the voice and video traffic that will support your meetings experience."
https://www.powershellgallery.com/packages/NetworkTestingCompanion/1.5.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8485ffe7-52ea-ef91-4983-2f02d6e3bb96
* Version Independent ID: 2bb5e8af-2c5b-ab1f-f69b-be8668b181b4
* Content: [Meetings and conferencing in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/deploy-meetings-microsoft-teams-landing-page#feedback)
* Content Source: [Teams/deploy-meetings-microsoft-teams-landing-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/deploy-meetings-microsoft-teams-landing-page.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@sagy  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@sagy  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
