### ISSUE TITLE
Autodiscover

### ISSUE THREAD

**Issue by steveapples** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4930]
If you use the http redirect method of Autodiscover, Teams cannot find your On-premises Calendar.
If you have many domains, or do not want to buy an expensive SAN-SSL just use SRV-records for Autodiscover instead. I struggled with this for many days. Microsoft Support was useless. However as soon as I switched to SRV-records for Autodiscover it worked in a few minutes. Http redirect passes Remote Connectivity Analyzer, but doesnt work in Teams, probably a bug. Could be worth having a note about this, so other people doesnt have to struggle with this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact#feedback)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@steveapples  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@steveapples thank you for reaching out and helping improve MS Docs. Just for clarity where in this article would you suggest adding a note regarding this?

**Comment by steveapples** [comment]
Hello, as long as it is available under Feedback, that should probably do it. I believe very few will have this problem. But best would be if the Teams programming teams could check if this is an actual bug and if so, fix it. Thanks!
