### ISSUE TITLE
PSTN Usage report should refer to the report in the Teams Admin Center

### ISSUE THREAD

**Issue by NickElniff** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4932]
This section should be update to remove reference to Skype for Business Admin Center and instead reference the Teams Admin Center

"Organizations already using Skype for Business Online already as their service provider can get usage data by reviewing it in the Skype for Business admin center &gt; Reports &gt; PSTN usage details report.

When you are setting up Communications Credits, you will need to investigate call usage for your organization to determine the amounts you need. You can get call usage information by reviewing the PSTN usage details report. This report lets you export the call data records to Excel if you need to store the data or create custom reports. To learn how to see usage, read Skype for Business PSTN usage report."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 277cf140-5c6c-82c7-cc56-490ef2188754
* Version Independent ID: 72e7de29-fd71-23bf-15a7-172634c2a5fd
* Content: [Set up Communications Credits for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-communications-credits-for-your-organization)
* Content Source: [Teams/set-up-communications-credits-for-your-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-communications-credits-for-your-organization.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@NickElniff  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@NickElniff  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
