### ISSUE TITLE
What about the most common profile for a startup?

### ISSUE THREAD

**Issue by DixonJones** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4933]
Most businesses start with one person becoming two people. We used Skype personal before this and my version of office was friends and family... so I ended up with a new profile for the business. But now I have two onedrives. WHAT? So I assume I need to migrate... but apparently I cannot according to the help. I want an organization profile that says "I have a new business, but all the team has all the baggage of individual bits of software, files and apps". I am none of these profiles and no startup would be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b131c7fd-ec71-6b6f-4443-ddaf5cb44bf6
* Version Independent ID: 0c1fb61b-a6cc-e856-d969-54bc13ec699c
* Content: [How to roll out Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/how-to-roll-out-teams#feedback)
* Content Source: [Teams/How-to-roll-out-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/How-to-roll-out-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@DixonJones thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
