### ISSUE TITLE
Shifts data location is missing

### ISSUE THREAD

**Issue by ahamin01** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4934]
As Shifts is part of Teams, this article is not mentioning anything about Shifts and where it's stored.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84f319aa-94de-bed1-2e5d-c6fe24436dac
* Version Independent ID: ee6daf32-7e03-801c-dd1b-50bf35e4635e
* Content: [Location of data in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/location-of-data-in-teams)
* Content Source: [Teams/location-of-data-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/location-of-data-in-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@ahamin01  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@ahamin01 thank you for reaching out and helping improve MS Docs. I'm not too sure that Shifts should be part of this article, but here is a link that relates. Let me know if it helps. https://docs.microsoft.com/microsoftteams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams

**Comment by scanum** [comment]
@ahamin01  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
