### ISSUE TITLE
The PSTN department is non-existent!

### ISSUE THREAD

**Issue by mratner2000** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4935]
I got an email with an issue regarding 2 of my 3 port orders.  I send an email to the ptn@microsoft.com address and I have received NO CORRESPONDENCE from them.  I've opened a ticket with general support who has no clue and all they did was forward the ticket to the PTN email address.  Every other phone service on earth has a tech support department you can communicate with via phone or trouble ticket but Microsoft's PTN department has a dead-end email address with NO RESPONSE, TROUBLE TICKET or way to get resolution on a time sensitive transaction (moving live business phone numbers.)

Does anyone at Microsoft care?????  i don't think so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ddf1c3c-7fb9-ff3c-e8cd-af75999c78cb
* Version Independent ID: 6178c672-003f-8f99-f4ab-cf9b06cf5ede
* Content: [Contact the PSTN service desk - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk#feedback)
* Content Source: [Teams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@mratner2000 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
