### ISSUE TITLE
Support PIN not visible

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4936]
Hello,

I can't see a support pin as described on this page. In which cases is it hidden/not available? What does a customer have to do to have/view a support pin?

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510eda3b-90cf-4c84-4f15-2c2b3ae841f3
* Version Independent ID: 5fd1abf8-ec5d-3f82-afe3-78b57eb3e8fd
* Content: [How do I look up my support PIN? - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/support-pin#feedback)
* Content Source: [Teams/support-pin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/support-pin.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@GiantCrocodile  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by GiantCrocodile** [comment]
Now I can see the field but the support pin is unknown and a new one can't be generated.

**Comment by GiantCrocodile** [comment]
According to support engineer in service request 20209024:

- the tenant has to have direct paid licenses (not CSP-only or free licenses)
- the support pin is for emergencies like calling Microsoft to reset access to a Global Admin account
- the support pin is NOT relevant/used for regular cases at Microsoft's phone hotline or service requests and it isn't mandatory
- if you don't have a support pin, Microsoft will ask you other questions to verify you are the owner of the tenant

According to him, this Office 365 documentation article is wrong and it's unclear to him why it's stated that you need a support pin for regular customer support by Microsoft.

**Comment by lindspea** [comment]
@CarolynRowe please confirm if article needs to be changed according to above comments.

**Comment by GiantCrocodile** [comment]
Hi @lindspea @scanum @CarolynRowe! It would be great if we could get this basic problem about unclear support instructions getting solved after a month.

**Comment by lindspea** [comment]
@CarolynRowe any news yet?

**Comment by lindspea** [comment]
@GiantCrocodile this article has been updated with the requested information. Thanks again for reaching out. @scanum this can be closed thank you.
