### ISSUE TITLE
Dial-Out permission change requires 'Skype for Business Admin' Role, not Teams Service Admin

### ISSUE THREAD

**Issue by johnhClarkWa** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4937]
Documentation needs to be more specific about what role is required to change settings, specifically the 'dial-out' policy setting.
At this time 'Dial-out' policy changes currently require 'Skype for Business Administrator' role, NOT the Teams Service Administrator role or any of the other Teams oriented roles.  Spent almost a month going back and forth with Microsoft support only to figure this out today.  
Alternatively to a documentation update if Teams Admin portal the error message had at least said, "You do not have permission to make this change" instead of a generic "Error:  we couldn't change the policy" that would have also helped save a TON of time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28bbd6d3-a2ef-c308-42ec-90ba27588821
* Version Independent ID: d7ad4fbd-d816-91a7-58e7-7a153eecd8ec
* Content: [Manage Audio Conferencing settings for users - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-the-audio-conferencing-settings-for-a-user-in-teams#feedback)
* Content Source: [Teams/manage-the-audio-conferencing-settings-for-a-user-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-the-audio-conferencing-settings-for-a-user-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@johnhClarkWa  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@johnhClarkWa thank you for pointing this out and helping improve MS Docs. This doc set is being updated frequently so the steps in the articles might look a little different from what you see.  Sorry for the inconvenience caused. I'll make a note for any further queries regarding this to help other users.

**Comment by johnhClarkWa** [comment]
Thanks for making an update to the doc and notes.

**Comment by scanum** [comment]
@johnhClarkWa  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
