### ISSUE TITLE
Unable to move a user from SfB on-prem to Teams 

### ISSUE THREAD

**Issue by SfBEngineer13** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4944]
Hi, I was unable to move only 1 user using Move-CSUser -Identity user@company.com -Target sipfed.online.lync.com -MoveToTeams -BypassAudioConferencingCheck -BypassEnterpriseVoiceCheck A workaround I found was first move user to SfBO and then Teams... why does that happened if I verified all SfB 2015 CU8 requirements?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca38b93a-773e-3864-45b6-128dd3163f37
* Version Independent ID: 7c32e933-94f2-196e-1163-3881df3aaf5a
* Content: [Move users from Skype for Business Server 2019 to Teams - Skype for Business Hybrid](https://docs.microsoft.com/en-us/SkypeForBusiness/hybrid/move-users-from-on-premises-to-teams#feedback)
* Content Source: [Skype/SfbHybrid/hybrid/move-users-from-on-premises-to-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/move-users-from-on-premises-to-teams.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@SfBEngineer13 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
