### ISSUE TITLE
What exactly is Federated in Teams?

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4947]
This article assumes someone understands or has set up Federation. What exactly does that mean in Teams today?
"must be correctly set up for hybrid and moved to Skype for Business Online." Ok, so, if some is in Teams only then they are not in Hybrid and they didn't move to SfB then how can they make this work?

Then with this sentence "If you can only exchange text in your chat with an external user, then you're in a standard external-access (federated) chat" Ok. it may be true but this article makes a lot of assumptions. How did you get there "external-access (federated)? It'd be helpful to have a link from this page to another page that explains federation in Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ac8f101-bdb5-2b55-d5f4-e070b70768d4
* Version Independent ID: 964d836e-d00b-b585-8f02-e03c5ec8dab9
* Content: [Native chat experience for external (federated) users in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/native-chat-for-external-users#feedback)
* Content Source: [Teams/native-chat-for-external-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/native-chat-for-external-users.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Jmartinez589 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Jmartinez589 thank you for reaching out and helping improve MS Docs. Please have a look at these articles and let me know if they help at all. https://docs.microsoft.com/microsoftteams/communicate-with-users-from-other-organizations and https://docs.microsoft.com/microsoftteams/manage-external-access  I see this article has also been updated in the interim.

**Comment by scanum** [comment]
@Jmartinez589 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
