### ISSUE TITLE
Can download but data is empty

### ISSUE THREAD

**Issue by thowa1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4948]
I have tried this feature today as meeting organizer. I find the option to download and did receive a csv file. That file, however, was empty except for the header line.
Is that an error?
It may be that we do not yet have the appropriate meeting policy in place for me to download attendance reports - but in that case I would expect a different behavious (greyed out button and not downloading an empty "hoax" file).
The meeting was almost entirely "outside my organisation" participants - does that impact ability to generate attendance reeport?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a8b1087-ae40-6813-16bc-a69c90e50d19
* Version Independent ID: b808e843-80d8-4a96-c6ed-e8175968eb73
* Content: [Microsoft Teams meeting attendance report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/meeting-attendance-report#feedback)
* Content Source: [Teams/teams-analytics-and-reports/meeting-attendance-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/meeting-attendance-report.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@thowa1 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
