### ISSUE TITLE
Presenters and organizers

### ISSUE THREAD

**Issue by JorgeALeitao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4957]
When describing Presenters and Organizer roles this articles states: 
....
"Presenters from other organizations (Live Events restriction) - this includes anonymous and external participants"

This statement is not clear and contradicts - https://docs.microsoft.com/en-us/MicrosoftTeams/teams-live-events/plan-for-teams-live-events - that states
Non-authenticated anonymous users can't be invited as producers or presenters in Teams live events.
Thus, anonymous users can't be Presenters or Organizers.

Hence, I suggest removing this section from the aforementioned part "- this includes anonymous and external participants"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb468480-f733-9ee9-6ff8-cd45e2861869
* Version Independent ID: 714ec3f7-3fbe-c550-6733-ff5f52408985
* Content: [Presenter and participant capabilities in a Teams live event - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/roles-in-live-events#feedback)
* Content Source: [Teams/roles-in-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/roles-in-live-events.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@JorgeALeitao Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@JorgeALeitao thank you for reaching out and helping improve MS Docs. The one mentions non-authenticated anonymous users and the other mentions anonymous so I think there is a difference. Please let me know if I'm misunderstanding.

**Comment by JorgeALeitao** [comment]
Sorry but the link above is broken.

**Comment by cichur** [comment]
Hi @JorgeALeitao Thank you for your comments. You're correct. An anonymous user can't present or organize a live event. I'll correct the document. - Cindy

**Comment by cichur** [comment]
I've unpublished the article and am working with an SME to update the comment. I've removed the reference to anonymous users presenting a live event. Thank you. Cindy
