### ISSUE TITLE
Japanese translation of "Direct Routing" is not correct

### ISSUE THREAD

**Issue by ikukoyoneda** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4959]
currently "Direct Routing" is translated as "直接ルーティング" in Japanese, but it must be "ダイレクト ルーティング".

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: fb24d873-4507-3a2f-1d0f-a38a305b8ff5
* Version Independent ID: 6a927fb3-5cc9-91de-b9ce-d057156d3523
* Content: [Teams の連絡先センター - Microsoft Teams](https://docs.microsoft.com/ja-jp/MicrosoftTeams/teams-contact-center?source=docs#feedback)
* Content Source: [Teams/teams-contact-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-contact-center.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@ikukoyoneda Thanks for submitting feedback. We are working on this issue.

**Comment by scanum** [comment]
@officeglobal Hi! Could you please help with this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@ikukoyoneda , @scanum article was HumanTranslated and published live. The string "Direct Routing" was updated as requested

**Comment by scanum** [comment]
@ikukoyoneda  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
