### ISSUE TITLE
Call count in report

### ISSUE THREAD

**Issue by NamuHong** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4960]
When a 1:1 call turns into a group call after inviting another user, does this call count as a 1:1 call or a group call in usage report?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2758a3d6-c646-dcb0-2a31-c7b9b84e780b
* Version Independent ID: 8704c9fe-f8b0-82d2-bd83-3fd1a9ad638d
* Content: [Microsoft Teams user activity report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report#feedback)
* Content Source: [Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@NamuHong thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
