### ISSUE TITLE
please add NAT port preservation under network optimization

### ISSUE THREAD

**Issue by DanStevensonMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4961]
[comment from dansteve@microsoft.com] In the table describing network optimizations, can you please add a note that any firewalls must be sure to persist the address/port assignment for client connections, to avoid dropped calls. This is an occasionally common problem and helpful to document in order to guide admins. 

The task title could be "Maintain session persistence" and the detail text could be "Ensure your firewall does not change the mapped NAT addresses/ports for UDP."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d996cf7-9f48-2b30-7759-afaf3fe82caa
* Version Independent ID: 24dd6cdf-d35f-53b2-06c2-0a27891825d4
* Content: [Prepare your organization's network for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/prepare-network#feedback)
* Content Source: [Teams/prepare-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/prepare-network.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@DanStevensonMSFT Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LolaJacobsen** [comment]
I updated the article with the suggested new line item. It'll go live tomorrow late morning. Thanks so much, @DanStevensonMSFT
