### ISSUE TITLE
Customize Shifts with new request type

### ISSUE THREAD

**Issue by Daleyon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4963]
Hello, 
As you are aware only Time off, Swap, Offer are the only available request types.
Within settings, I added Overtime as a custom request type reason, but I need the possibility to add as a main request type.
Is it possible or will it be possible to customize Shifts with a new request type?

Use case: internal customer wants to include Overtime requests within the Shifts process. 

![image](https://user-images.githubusercontent.com/17080282/82551000-69422e80-9b2d-11ea-98eb-d08d544bca8b.png)

![image](https://user-images.githubusercontent.com/17080282/82551148-aefef700-9b2d-11ea-998c-df7429ad9bbe.png)

**Comment by Daleyon** [comment]
Is my original question not valid to apply here?

**Comment by scanum** [comment]
@Daleyon thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
