### ISSUE TITLE
Basic Conceptual Problem

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4965]
There is a basic conceptual problem with teams and channels in an organisation, which these pages do not attempt to answer.
What is a "team"? If members of a team are in another team (e.g. Accounts Payable are in Finance), then what is the "team"?
The illustration works in an organisation of about 100 people. What are the "teams" in an organisation of 100,000 people? Are there a) none, or b) random or c) teams within teams?
Since each team is also a mail enabled group, how many mail enabled groups does an organisation have? One for each of 20,000 teams??
If a "team" finishes work on a project - say, a product launch - where does the data go? Is it part of Marketing? But it can't be, because it is a separate team. So does that mean the product launch should be a channel in Marketing?
There is something missing in the basic concept of information management in an enterprise organisation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06059d07-6687-2924-7d0a-3c03220a1650
* Version Independent ID: bb293f92-9394-b156-2e08-0baead5c3bbe
* Content: [Overview of teams and channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-channels-overview)
* Content Source: [Teams/teams-channels-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-channels-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Air-Git thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
