### ISSUE TITLE
Nice idea

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4966]
This sounds like a good idea, but:
a) we can't create templates for our business, and 
b) the templates don't exist except for a few cases in Education and Healthcare.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d884cb-c126-b5dc-ff90-1a31aa61bf5b
* Version Independent ID: ed5054d7-d679-7fad-fd5d-9cd393644b9d
* Content: [Get started with Teams templates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-started-with-teams-templates)
* Content Source: [Teams/get-started-with-teams-templates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-started-with-teams-templates.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Air-Git thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
