### ISSUE TITLE
Links in page are outdated

### ISSUE THREAD

**Issue by ibawwad** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4967]
The links in the page for Creating Teams from O365 is outdated and doesn't show the recent Teams application change
The Apply dynamic membership to an existing Team, has nothing to do with Teams at all!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a578ddb-6494-9bda-529e-0156e5ab7c30
* Version Independent ID: 57d519c9-90f0-873d-ffef-589f0b3b3ac9
* Content: [Overview of dynamic membership for teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/dynamic-memberships)
* Content Source: [Teams/dynamic-memberships.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/dynamic-memberships.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@ibawwad Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@ibawwad thank you for reaching out and helping improve MS Docs. I found these two links. Let me know if you think they would suffice and I'll do a PR to replace the current links - https://docs.microsoft.com/microsoftteams/dynamic-memberships and https://docs.microsoft.com/microsoftteams/teams-overview

**Comment by ibawwad** [comment]
@lindspea Thank you for working on this, yes now the links reflect the proper relevant information.

**Comment by scanum** [comment]
@ibawwad  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
