### ISSUE TITLE
Link to LERR is broken?

### ISSUE THREAD

**Issue by makonig** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4972]
Current Document links to https://www.microsoft.com/about/corporate-responsibility/lerr/ which appears to be a 404.

Link should be to https://www.microsoft.com/en-us/corporate-responsibility/law-enforcement-requests-report

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e34f35bb-7d9c-0c7f-a1a1-6fd9fbe93dfa
* Version Independent ID: d123210a-ed20-4b97-3706-33d7887b4c27
* Content: [Microsoft Teams Privacy - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-privacy)
* Content Source: [Teams/teams-privacy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-privacy.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@makonig Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @makonig, thank you for your feedback and help us to improve docs.microsoft.com.

The link was fixed/updated 28 days ago and it's working now:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/5192
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5191
Sorry for the delay.

**Comment by scanum** [comment]
@makonig Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
