### ISSUE TITLE
Private channel owners not set correctly?

### ISSUE THREAD

**Issue by heinrich-ulbricht** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4973]
Looking at `CreateTeamsChannels.ps1` it seems that the private channel owner (as set in _teamsChannels.csv_) is being ignored:

The owner given here:

https://github.com/microsoft/MTC_FLWTeamsScale/blob/40d3d27dc60ba0af0c51e1c331d3979fe457acae/scripts/CreateTeamsChannels.ps1#L96

Should be used with an `-Owner` parameter here, which is currently missing:

https://github.com/microsoft/MTC_FLWTeamsScale/blob/40d3d27dc60ba0af0c51e1c331d3979fe457acae/scripts/CreateTeamsChannels.ps1#L101

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24a751a1-5a56-0b59-4d85-a243d1954e51
* Version Independent ID: 0a7b0526-5fda-554b-9481-7a75c6fb5dce
* Content: [Provisioning Microsoft Teams at scale for Firstline Workers - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/flw-scripted-deployment?source=docs#feedback)
* Content Source: [Teams/flw-scripted-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/flw-scripted-deployment.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@bratsche Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@heinrich-ulbricht thank you for reaching out and helping improve MS Docs. I work on the editing/writing side of MS Docs. Please could you clarify what needs to be changed in this article?

**Comment by heinrich-ulbricht** [comment]
The article actually is fine but the PowerShell the article is referring to needs to be fixed.
This link points to the PowerShell that needs fixing:
![image](https://user-images.githubusercontent.com/3469970/83036875-679bcd80-a03b-11ea-92cc-3dd7cf7b7d55.png)

Those scripts fail to set the private channel owner correctly.

**Comment by lindspea** [comment]
@MicrosoftHeidi please could you assist?

**Comment by lindspea** [comment]
@heinrich-ulbricht it seems the article has been updates and it's showing correctly now. Please confirm.

**Comment by scanum** [comment]
@heinrich-ulbricht We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by heinrich-ulbricht** [comment]
Looking at the script I see no difference. The script still contains the error of not setting the channel owner correctly.
![image](https://user-images.githubusercontent.com/3469970/91021230-c6012980-e5f3-11ea-88c1-7dab34f026b2.png)
