### ISSUE TITLE
Version Numbers

### ISSUE THREAD

**Issue by Nasherx** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4974]
It would be useful to see a list of the version numbers with the latest being bold or highlighted similar to what we have for Office versions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6da28da-eb7b-d3ae-4c2f-8f87803b1830
* Version Independent ID: 8c42d7a2-80c6-86dd-347a-ed6d8d909c41
* Content: [Teams updates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-client-update)
* Content Source: [Teams/teams-client-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-client-update.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Nasherx thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Nasherx** [comment]
@scanum I don't have a service issue. It would just be beneficial to see something similar to this for Teams: [](https://docs.microsoft.com/en-us/officeupdates/update-history-microsoft365-apps-by-date)
