### ISSUE TITLE
Peer to Peer versus connection to Microsoft Servers

### ISSUE THREAD

**Issue by Botts85** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4980]
The article speaks to peer-to-peer bandwidth requirements, but also speaks to optimizing the connection to Microsoft's servers.

Is there a KBase article on how/when Teams connects peer-to-peer versus through a Microsoft server?  That would help to optimize limited connectivity from sites to Microsoft.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d996cf7-9f48-2b30-7759-afaf3fe82caa
* Version Independent ID: 24dd6cdf-d35f-53b2-06c2-0a27891825d4
* Content: [Prepare your organization's network for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/prepare-network)
* Content Source: [Teams/prepare-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/prepare-network.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Botts85 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
