### ISSUE TITLE
Please clarify requried PhoneSystem licenses (does E5 count?)

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4981]
Hello,

do Microsoft E5 or Office 365 E5 licenses count towards a PhoneSystem license?
If so, would they follow the same 1:10 ratio or is it different?
Could you please add a second excaple breaking this down please?

Thanks,
David
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6891495-01c6-117b-c28b-28232782ba74
* Version Independent ID: 1c23b35a-e9ba-ffdd-9baa-a3f83f4ed9ca
* Content: [Microsoft 365 Phone System – Virtual User licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/virtual-user)
* Content Source: [Teams/teams-add-on-licensing/virtual-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/virtual-user.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@bratsche Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@DEberhardt thank you for reaching out. The article mentions this in a note - "Phone System is an add-on license available with Microsoft 365 and Office 365 E1 and E3. Phone System is also included as part of Microsoft 365 E5, Office 365 E5, and Microsoft 365 Business Voice licenses." Let me know if you need further assistance.

**Comment by DEberhardt** [comment]
Hello,
thank you for clarifying this. I still have to read between the lines on the ratio though, which means it could be worded more clearly :)
This is the reason why I was asking for an example mentioning a mixture of add-on and included licenses to better understand this.

**Comment by scanum** [comment]
@DEberhardt  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
