### ISSUE TITLE
Can the documentation be updated to address Alphanumeric outbound caller ID

### ISSUE THREAD

**Issue by paulypoteat** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4983]
Outbound caller ID being labeled with Alphanumeric for the tenant.  Either if it's possible, or not, it's not mentioned either way.

**Comment by scanum** [comment]
@paulypoteat Thanks for submitting feedback on the documentation. Could you please link the issue you are referring to? Thanks!

**Comment by paulypoteat** [comment]
https://docs.microsoft.com/en-us/microsoftteams/set-the-caller-id-for-a-user

I was hoping the article could mention alphanumeric Outbound caller ID (not just numeric outbound caller ID).  Either that it's possible, or even if it's not.

**Comment by lindspea** [comment]
@paulypoteat thank you for reaching out and helping improve MS Docs. I've done some research and found the following:  From a web browser on another device or computer go to https://microsoft.com/devicelogin and then enter the alphanumeric code displayed in the Enter Code field and then click Next. (the code is not case-sensitive.)  If the Pick an account window appears and the desired account appears in the list then select that account.  If not, then select the Use another account option. If prompted to sign in then enter the username for the desired Teams user account and select Next.  Then enter the password and select Sign In.

**Comment by scanum** [comment]
@paulypoteat  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
