### ISSUE TITLE
Enabling Shared mode

### ISSUE THREAD

**Issue by DCri** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4984]
The option to choose between Shared and Personal mode is not displayed when signing in to Teams on a certified IP phone (in this case Polycom Trio s/w version 5.9.3.7982 Teams 1499/1.0.94.2020020601).  Now required to be configured in IP Phone Policy: https://knowledgebase-iframe.polycom.com/kb/viewContent.do?externalId=39722

Article from Polycom implies it is a change dependent on their software version, but I would have though the behaviour would be driven by Teams client?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae4c265a-8df4-647d-fc42-5054e3340c20
* Version Independent ID: 249c7301-9c82-b1c4-8401-54553370302b
* Content: [Phones for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/phones-for-teams)
* Content Source: [Teams/devices/phones-for-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/phones-for-teams.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@DCri thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
