### ISSUE TITLE
Bus Voice not available for Apps for Bus or Apps for Ent

### ISSUE THREAD

**Issue by jokruege** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4989]
This pages states that you can add M365 Bus Voice to Apps for Business or Apps for Enterprise,but i do not believe that to be correct. 

On the Service Description page of M365 Bus Voice those 2 licenses are not listed as compatible plans. https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-business-voice-service-description

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35057f71-792b-a4e2-a2ee-a4908c11f3a4
* Version Independent ID: 7e23f067-1dcd-16f0-3f9a-ff8d13c1f659
* Content: [What is Microsoft 365 Business Voice? - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/business-voice/whats-business-voice)
* Content Source: [Teams/business-voice/whats-business-voice.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/business-voice/whats-business-voice.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@jokruege  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@dstrome please can you confirm which article is correct regarding business voice.

**Comment by dstrome** [comment]
Thanks for your feedback. We recently updated the supported SKU list and the unsupported SKUs are no longer listed.
