### ISSUE TITLE
Data collection practices - can we control them for Teams?

### ISSUE THREAD

**Issue by StainlessSteele** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4992]
Teams/data-collection-practices.md - It mentions Teams, but really just talks about controlling them for Skype for Business on-premises. Are there controls for Teams?

**Comment by scanum** [comment]
@StainlessSteele thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
