### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by LouisLouis3** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4993]
It is very confusing that you have an incomplete list of known issues in the middle of the page (pasted below).  And then have another list of more complete known issues in the known issues section at the very bottom of the article.  This section pasted below needs to be removed from the middle of the article and added to the rest of the known issues list at the bottom.  You can reference the full known issues list in it's place.

Others have left this same feedback however rather than combining the lists you just referenced them to the rest of the known issues list at the bottom which ignores the feedback that we are trying to give.

Kevin

-------------------------------------------------------------------------------------

These calling and meeting features are not supported:

Enhanced emergency services
HID buttons and LED controls between the Teams app and devices
Background blur and effects
Broadcast/live events
Location-Based Routing (LBR)
Call park
Call queue
 Important

If you currently run Teams without AV optimization in VDI and you use features that are not supported yet for optimization (such as Give and take control when app sharing), you have to set Citrix policies to turn off Teams redirection. This means that Teams media sessions won't be optimized. For steps on how to set policies to turn off Teams redirection, see this Citrix website.

We're working on adding calling and meeting features that are currently only available in non-VDI environments. These may include more admin control over quality, additional screen sharing scenarios, and advanced features recently added to Teams. Contact your Teams representative to learn more about upcoming features.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@LouisLouis3  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@LanaChin should these "calling and meeting" known issues and image be incorporated with the known issues at the bottom of the article?

**Comment by LanaChin** [comment]
Thanks for your input to help us improve our docs, @LouisLouis3. We're updating the article to move the list of calling and meeting features that aren't supported to the Known Issues section.
