### ISSUE TITLE
O/M365 F3

### ISSUE THREAD

**Issue by JelmerBarhorst** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4995]
[Voer hier feedback in]
Office 365 and M365 **F3** are not listed, while Office 365 F1 is. Please update

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 35057f71-792b-a4e2-a2ee-a4908c11f3a4
* Version Independent ID: 7e23f067-1dcd-16f0-3f9a-ff8d13c1f659
* Content: [What is Microsoft 365 Business Voice? - Microsoft Teams](https://docs.microsoft.com/nl-nl/MicrosoftTeams/business-voice/whats-business-voice)
* Content Source: [Teams/business-voice/whats-business-voice.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/business-voice/whats-business-voice.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@JelmerBarhorst Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@LanaChin Hello Lana, Can you kindly confirm if we have to add _Office 365 F3_ as this article states? https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-business-voice-service-description
Thank you

**Comment by LanaChin** [comment]
Reassigning to @dstrome.

**Comment by dstrome** [comment]
article updated
