### ISSUE TITLE
Definition of authenticated user

### ISSUE THREAD

**Issue by tomko80** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4996]
Is "having O365 license" and "authenticated" user as mentioned in this article the same as "signed in" user mentioned in the live event create dialog? E.g. for org-wide restricted live events it says "sign-in required".

Would be nice if the terminology was consistent as these things are tricky to test.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@tomko80 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@LanaChin Lana, how are you? Can you kindly help us here ? I appreciate.

**Comment by LanaChin** [comment]
Hi @tomko80, have a look at the "Who can attend live events" section in this article, https://support.office.com/en-us/article/get-started-with-microsoft-teams-live-events-d077fec2-a058-483e-9ab5-1494afda578a, which discusses licensing.
