### ISSUE TITLE
Filter for Audio conferencing doesn't work.

### ISSUE THREAD

**Issue by techlearner9** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5003]
[Enter feedback here]
It will only show first user with Audio conferencing enabled. The sort feature doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63999e48-1168-b6c6-cba2-d722e3d7a0da
* Version Independent ID: 4e34b210-1f46-c136-1238-7a3218c6d90b
* Content: [See a list of users enabled for Audio Conferencing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/see-a-list-of-users-that-are-enabled-for-audio-conferencing-in-teams)
* Content Source: [Teams/see-a-list-of-users-that-are-enabled-for-audio-conferencing-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/see-a-list-of-users-that-are-enabled-for-audio-conferencing-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@techlearner9 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
