### ISSUE TITLE
Error in admin url

### ISSUE THREAD

**Issue by jeffmparker** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5005]
Hi, where it says: 
"Using the Microsoft Teams admin center
"Go to the admin center at https://admin.microsoft.com."
The URL should be https://admin.teams.microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Manage meeting settings - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/meeting-settings-in-teams?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@jeffmparker Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @jeffmparker

**Comment by scanum** [comment]
@jeffmparker  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
