### ISSUE TITLE
Hang-up anonymous guests

### ISSUE THREAD

**Issue by jeffmparker** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5006]
Can the meeting owner force a guest user to be removed from a meeting, e.g. in the situation where an unwanted person joins by clicking on the meeting invitation? This should be documented.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Manage meeting settings - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/meeting-settings-in-teams?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@jeffmparker thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jeffmparker** [comment]
Hi, I'm not experiencing this problem in my tenant, so no need to raise a ticket. I raised it because it might be a consequence of enabling anonymous guest access (someone joins who shouldn't be there) and this management function should be available.
