### ISSUE TITLE
Still confusion about guest vs external vs anonymous 

### ISSUE THREAD

**Issue by jeffmparker** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5007]
It is still very confusing about how these various settings interact with each other. In my tenant, I have external and guest access enabled, and anonymous disabled. That should be all ok, as I want to be able to identify meeting participants. But I still have some guest invitees unable to join meetings, and I'm unsure if that is due to some issue with their account and/or having anonymous access disabled? It's very confusing as to why some can enter and others can't, and I haven't yet seen a pattern. Better diagnostic information for both the invitee and organiser is needed, along with effective troubleshooting tools.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Manage meeting settings - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/meeting-settings-in-teams?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@jeffmparker Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @jeffmparker How are you?

As I do not know the error exactly faced by your guests users to join to try to reproduce and see if we have a documentation issue:

You can find troubleshooting guest access information [here](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot-guest-access)

And probably you already started [here](https://docs.microsoft.com/en-us/microsoftteams/guest-access)

If that information does not resolve your issue, I would recommend opening a support ticket directly in your tenant, they will be able to help you further.

**Comment by scanum** [comment]
@jeffmparker Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
