### ISSUE TITLE
Wrong information

### ISSUE THREAD

**Issue by lcansby** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5009]
Most of the information in this document is wrong, you don't have chat for viewers/participants in a Live Event. I think this document have only been copied from Teams meetings and not changed to reflect Live Events.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb468480-f733-9ee9-6ff8-cd45e2861869
* Version Independent ID: 714ec3f7-3fbe-c550-6733-ff5f52408985
* Content: [Presenter and participant capabilities in a Teams live event - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/roles-in-live-events)
* Content Source: [Teams/roles-in-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/roles-in-live-events.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@lcansby  Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by Reeced40** [comment]
@lcansby Thank you for reaching out to improve MS Docs. Please let me know if this link helps - https://support.microsoft.com/office/get-started-with-microsoft-teams-live-events-d077fec2-a058-483e-9ab5-1494afda578a?ui=en-us&rs=en-us&ad=us

**Comment by cichur** [comment]
@lcansby Thank you for your feedback. I'll be revising the article.

**Comment by scanum** [comment]
@lcansby  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
