### ISSUE TITLE
Assigning number needs a better example

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5010]
I've been trying to setup a resource account for our autoattendent, and have run into a number of issues. The current biggest one is that the example given for assigning a number isn't very complete. It blurs out the number, so we don't see the formatting necessary, and documentation doesn't indicate the form required either. 

There also appears to be a timeframe where you can't assign a number no matter what that should be mentioned.

Finally, it'd be nice if we could condense down the pages required to do anything in Teams. Specifically for creating an auto attendant with a resource account, if one has zero knowledge, it requires at least 4 different pages to order the phone number, create a resource account, assign a license to the resource account, and then create the auto attendant. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts#create-a-resource-account-in-microsoft-teams-admin-center)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@StuBeck32 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by StuBeck32** [comment]
Documentation for assigning a number per support is inaccurate. To enter the number in the US, you must enter 1 XXX-XXX-XXXX, not +1 and then have numbers show up. 

Timeframe for not being able to assign a number seems to be half an hour.

**Comment by StuBeck32** [comment]
This issue is incorrectly closed. It needs to be reopened as the documentation is still incorrect.
