### ISSUE TITLE
Microsoft Teams Update Process

### ISSUE THREAD

**Issue by joeljanke** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5011]
This page does not cover at all how features are released.   We have a single tenant...all MS Teams clients running the exact same version and yet individuals within our tenant have different features exposed at the same time.   Some have the popout window feature, some do not.  Some have custom backgrounds, some do not.  Some have the raise hand feature, some do not.

We have no means as an organization to properly support our user community as we have no idea who will have what feature.  We want to announce new features and make sure users are aware of them, however, we cannot as it just leads to a bevy of phone calls about how they don't have the feature we announced (although some do).  

It seems we have no means to control whatsoever when these features appear or do not appear for individuals within our organization.   It is very strange that an entire tenant does not get the same updates at the same time.  At the very least, however, this should be documented.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6da28da-eb7b-d3ae-4c2f-8f87803b1830
* Version Independent ID: 8c42d7a2-80c6-86dd-347a-ed6d8d909c41
* Content: [Teams updates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-client-update?ranMID=24542&ranEAID=msYS1Nvjv4c&ranSiteID=msYS1Nvjv4c-yanv02hPnNM8d2_.L7M.lQ&epi=msYS1Nvjv4c-yanv02hPnNM8d2_.L7M.lQ&irgwc=1&OCID=AID2000142_aff_7593_1243925&tduid=%28ir__vh02chjdeskftxnnkk0sohzg2m2xntilqogl33ka00%29%287593%29%281243925%29%28msYS1Nvjv4c-yanv02hPnNM8d2_.L7M.lQ%29%28%29&irclickid=_vh02chjdeskftxnnkk0sohzg2m2xntilqogl33ka00)
* Content Source: [Teams/teams-client-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-client-update.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@joeljanke  Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by Reeced40** [comment]
@joeljanke Thank you for reaching out to improve MS Docs. Please let me know this link helps - https://docs.microsoft.com/microsoftteams/troubleshoot-installation

**Comment by scanum** [comment]
@joeljanke We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by KeithPell** [comment]
Curious how "Can admins deploy updates instead of Teams auto-updating?
Teams does not give admins the ability to deploy updates through any delivery mechanism." is acceptable to the product group? This currently has my customer highly upset that there is no way for them to control the version of Teams on their network. Because of this they just found out that they have 17 versions of the Teams client installed. Curious how the product group thinks that is acceptable from a company like Microsoft?
