### ISSUE TITLE
Include cmdlets directly on this page for Teams/SkypeForBuiness module install

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5012]
Commands for installing Microsoft Teams and Skype for Business cmdlets should be on this page. They don't need to have a separate page to get to this. It took me 4 pages to get the right cmdlet necessary to install the Teams cmdlets, which is a bit ridiculous. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26362d70-cfce-2eea-077b-4aaa50f92e8b
* Version Independent ID: f52dcd4d-4f58-05c4-11b0-f1e3c95f4d89
* Content: [Teams PowerShell Overview - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-overview)
* Content Source: [Teams/teams-powershell-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@StuBeck32 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by StuBeck32** [comment]
This seems to be a copy pasta from my other comment. Support can't help with this as I'm asking for commands to be included here, or at minimum a direct link to the page showing how to install it versus requiring 4 links.

**Comment by StuBeck32** [comment]
No update from you, but to be clear, support can't resolve this issue.
