### ISSUE TITLE
Update current low-res picture with better

### ISSUE THREAD

**Issue by SergGu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5015]
Hello Microsoft Team,

The first picture on the page is hard to read. This is the picture just under 
https://docs.microsoft.com/en-us/microsoftteams/microsoft-teams-online-call-flows#teams-topology

Would it be possible to replace with better quality? All other pictures are fine.

Best regards,
Serg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c84773-337e-9df7-7fbd-fc9d94280711
* Version Independent ID: 223a78a0-67fd-8b96-be3f-153bb400101b
* Content: [Microsoft Teams call flows - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/microsoft-teams-online-call-flows#teams-topology)
* Content Source: [Teams/microsoft-teams-online-call-flows.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/microsoft-teams-online-call-flows.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@SergGu Thank you for the feedback. We have reviewed the image and we might update in the future.
