### ISSUE TITLE
Misleading reference

### ISSUE THREAD

**Issue by JorgeALeitao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5017]
[Enter feedback here]

Under the Web Client section the footnote 1 states:
..... This is due to a technical limitation that we're planning to fix. To learn more, read https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams#allow-a-participant-to-give-or-request-control.

This is misleading as the article referred actually describes the Give and Request Control settings under Meetings policy, not the technical limitation it seemed to.

Perhaps it should read - To learn more about controlling when users can Give and Request Control under a meeting, read ...

Furthermore the referred article contains the exact same portion - minus reference - but offer zero information on the underpining technical limitation or its fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients?source=docs#web-client)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@JorgeALeitao  Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by Reeced40** [comment]
@LolaJacobsen Hi Lola, please could you assist. All the information that appears in the document doesn't appear in the editing section.

**Comment by LolaJacobsen** [comment]
The last sentence in the footnote, "To learn more, read...", isn't about the limitation. It's about giving & requesting control in general. We don't have any reference material about the technical limitation. I changed the footnote so the xref doesn't appear to be related to the limitation. Thanks for pointing this out!
