### ISSUE TITLE
Where is WVD?

### ISSUE THREAD

**Issue by aamillerMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5020]
[Enter feedback here]
This doc only talks about Citrix.  Teams is supported on Windows Virtual Desktop as well.  Please add a reference to this fact and documentation found here: [https://docs.microsoft.com/en-us/azure/virtual-desktop/teams-on-wvd](https://docs.microsoft.com/en-us/azure/virtual-desktop/teams-on-wvd)

Alternatively, you could rebrand this doc to "Teams for Citrix", and make separate pages for WVD and eventually VMWare.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@aamillerMSFT  Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by scanum** [comment]
@aamillerMSFT  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
