### ISSUE TITLE
"Allow" not "Block"

### ISSUE THREAD

**Issue by bahnjee** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5021]
In the following note, it says that **Block** rules will be created.  However, the Powershell script lower down the page creates **Allow** rules.

_Windows Firewall configuration will be altered even when the prompt is dismissed by selecting “Cancel”. Two inbound rules for teams.exe will be created with Block action for both TCP and UDP protocols._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@bahnjee  Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by Reeced40** [comment]
@bahnjee Thank you for reaching out. Just for clarification, would you suggest that I replace "Block" with "Allow in the Note?

**Comment by bahnjee** [comment]
Yes, unless there’s something I’m misunderstanding in the note I referenced.  I can’t replicate the Firewall prompt so I can’t hit Cancel and see the type of rule created (Allow or Block), but the logic of it tells me that it should be creating an Allow rule (else, how could the user make a call?).  Add to this that the provided Powershell script adds Allow rules and I’m fairly sure that yes, the note should say that Allow rules will be added.

Greg Bond
Client Manager | Information Technologies
Spartanburg Community College
Mailing Address: P.O. Box 4386 Spartanburg, SC 29305
Physical Address: 107 Community College Dr.
(864) 592-4974
bondg@sccsc.edu<mailto:bondg@sccsc.edu>
www.sccsc.edu<http://www.sccsc.edu/>

**Comment by scanum** [comment]
@Reeced40

**Comment by Reeced40** [comment]
@LolaJacobsen Please can you confirm related issue - https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5088

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
