### ISSUE TITLE
"Set Business hours" image & text is out of date

### ISSUE THREAD

**Issue by greiginsydney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5022]
Under "Call flow for after hours", the "set business hours" image and its descriptive text is out of date.

The default is 24x7, with all days starting and ending at 12am. (I see in the code that someone's already made note of this, but it's commented-out.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a42f9e2c-aeee-76c4-620a-668cce21ba10
* Version Independent ID: 6ff06eab-9c80-9c30-95ef-c17e157fbea1
* Content: [Set up a Cloud auto attendant - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-auto-attendant)
* Content Source: [Teams/create-a-phone-system-auto-attendant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-auto-attendant.md)
* Service: **msteams**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by scanum** [comment]
@greiginsydney  Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by lindspea** [comment]
@greiginsydney thank you for reaching out and helping improve MS Docs. The default is 9am to 5pm as per the article?  Please clarify what you think needs to be changed in the article. Thanks so much.

**Comment by Reeced40** [comment]
@greiginsydney Thank you for reaching out. The default is reading correctly as stipulated in point number 2 of the article. Perhaps it was updated in the interim. Please advise.

**Comment by greiginsydney** [comment]
My experience here in Australia differs to the one documented in the article. THIS is the default view when I create a new AA at "https://admin.teams.microsoft.com/auto-attendants/v2/add".

![image](https://user-images.githubusercontent.com/11004787/84895247-65320e00-b0e5-11ea-9d6f-8be4221caaa2.png)


Is it possible there's some rogue code running and my region is defaulting to 24x7 and the US is 9-5?

\- G.

**Comment by leeford** [comment]
IIRC it used to be 9x5 when creating a new Auto Attendant, but from experience it has been 12AM-12AM (24x7) for a while now.

**Comment by romanf01** [comment]
Checked in Admin Center and it defaults to 24x7, and noting that it's in the UX itself as a callout, see screenshot by @greiginsydney above.  @alan-xie-microsoft has prepared a PR addressing the doc issue that Greig called out (thanks!!):  https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/5165

fyi - @Reeced40 @scanum

**Comment by Reeced40** [comment]
Thanks @romanf01. @scanum this can be closed thank you.

**Comment by scanum** [comment]
@leeford Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
