### ISSUE TITLE
Incorrect PSTN Information

### ISSUE THREAD

**Issue by NickStillings** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5023]
This page has inaccurate information that's currently a huge customer sat issue for Live Events - the table implies that attendees can attend a Teams Live Event via dial-in.  Not possible, as it's streamed over Azure Media Services.  A **Presenter** can dial in, but not an attendee. Row 3 in the graphic needs edited ASAP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92fcb1f6-5cc2-f6bd-cfa9-11d811f1dbf1
* Version Independent ID: 9a571e6d-8cb3-9ff8-a5c2-62deab146264
* Content: [Admin quick start - Meetings and live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/quick-start-meetings-live-events?source=docs)
* Content Source: [Teams/quick-start-meetings-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/quick-start-meetings-live-events.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@NickStillings  Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by Reeced40** [comment]
@LolaJacobsen Please assist.

**Comment by LolaJacobsen** [comment]
Checking with PM Ashwin Appiah.

**Comment by LolaJacobsen** [comment]
I merged the change updating the graphic today. Thanks!
