### ISSUE TITLE
Factors which influence presence

### ISSUE THREAD

**Issue by Ranger-Z** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5026]
The document discusses how to set status and meaning of these it does not discuss the factors which may influence status.  Specifically I am suffering from always available status even when the lid of my laptop is closed.  I also have Teams installed on IOS (phone) but generally not "ON".  

I am of the opinion that there are items like sleep on the PC and background processing on the IOS that is leading me to be available when I expect the lack of activity will show me yellow and the closed lid will show me not logged in.  This information does not seem available
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a162ef5c-3099-7f58-4178-d29e3ec2b5a7
* Version Independent ID: 6ca31e56-052d-6c62-1323-b5aaaae1f04a
* Content: [User presence in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/presence-admins)
* Content Source: [Teams/presence-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/presence-admins.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Ranger-Z thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
