### ISSUE TITLE
SPO settings for guest access in Teams

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5030]
Hi! Article mentions that SPO sharing needs to be set to "Everyone" or "New and existing guest". Can this also be "Existing guests only"? Since when user invites guest to Teams this will cause adding the external user to AAD as guest and to M365 group, so SPO will not need ability to add new guests from SPO interface. Is my thinking correct and any of the 3 settings will be sufficient?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams guest access checklist - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/guest-access-checklist)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Larryngolog, thank you for your feedback and help us to improve docs.microsoft.com.

Existing guests is not a recommended setting, that's why you can't see it in this type of articles.

**Comment by Larryngolog** [comment]
Hello @dariomws . Thanks for your reply. Multiple customers I work with have strickt data sharing policies and require approval of the guests that are invited to the environment. I understand that "Existing guests" is not recommended, but I think it should be also listed as a supported option.

**Comment by dariomws** [comment]
Hi @Larryngolog, thank you for your comment.

@MikePlumleyMSFT what do you think? Thanks!

**Comment by MikePlumleyMSFT** [comment]
"Existing guests" is certainly a supported feature if that works for your scenario. We don't list it as a mainstream setup option because guests can be invited to the tenant through a wide variety of means beyond a given SharePoint site, including Teams, groups, other SharePoint sites, and Azure AD.

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
