### ISSUE TITLE
Issue shows closed but changed still not reflected in the documentation.

### ISSUE THREAD

**Issue by greganth1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5031]
This issue that was raised here in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4454 has been closed yet the documentation still has this now erroneous note under the Teams only section.

 Important

If you uninstall the Skype for Business client after you move a user to Teams Only mode, presence stops working in Outlook and other Office apps. Presence works fine in Teams. Workaround: To see presence in Outlook (and other Office apps), Skype for Business must be installed, even if you're running Teams in Teams Only mode. Microsoft is aware of this problem and is working on a fix.

The important note needs to be removed as it no longer is applicable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d53d0cb0-90a6-5932-f78e-7de6fcc4d481
* Version Independent ID: 3d468027-cc37-5199-32ec-819bf62b2caa
* Content: [Interoperability between Skype for business and Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability#teams-only)
* Content Source: [Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@lindspea Hi Lindsay! Wondering if you can help here. Thanks!

**Comment by lindspea** [comment]
@greganth1 @scanum Thanks for reaching out. The PR was done and merged to have the note removed, but it might take a few days for the change to show. I'll check in a few days time again to make sure.

**Comment by scanum** [comment]
@greganth1  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
