### ISSUE TITLE
Use of -UseOAuth should be mentioned

### ISSUE THREAD

**Issue by cypheredout** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5034]
Can there be a refer to the move-csuser doc showing that you may need to use -UseOAuth flag?

"If you are using Skype for Business Server 2015 with CU8 or later, we recommend you pass the `-UseOAuth` switch, which ensures the on-premises code authenticates using OAuth, instead of Legacy LiveID authentication. In Skype for Business Server 2019 and later versions, OAuth is always used hence the switch is not relevant on those versions."

Doc noting that: https://docs.microsoft.com/en-us/powershell/module/skype/move-csuser?view=skype-ps

Seeing quite a few folks running into that.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca38b93a-773e-3864-45b6-128dd3163f37
* Version Independent ID: 7c32e933-94f2-196e-1163-3881df3aaf5a
* Content: [Move users from Skype for Business Server 2019 to Teams - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/move-users-from-on-premises-to-teams)
* Content Source: [Skype/SfbHybrid/hybrid/move-users-from-on-premises-to-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/move-users-from-on-premises-to-teams.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@cypheredout Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@cypheredout thank you for reaching out and helping improve MS Docs. Just for clarity, are you suggesting adding that note and link to this article?

**Comment by scanum** [comment]
@cypheredout We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
