### ISSUE TITLE
Changing from PhoneSystem to PhoneSystem_VirtualUser

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5044]
Hello again,
still struggling with License assignment for Resource Accounts.
Please answer the following questions and update the documentation if you deem necessary:

a) What is a "Full Phone System license"?
I thought these were add-on licenses (for E1, S2 or E3) or part of a bigger license (like E5)?
When swapping from PhoneSystem to PhoneSystemVirtualUser - using  Powershell - I face a dependency issue: to paraphrase: "Cannot be removed because of dependency to MCOSTANDARD"

b) Can I swap in either direction? I.E. PSVU > E3+PS and E3+PS > PSVU?
c) (I guess this is a yes) Do I have to apply a full E3 license if I do not have any spare PSVU licenses?

Background: I am working on PowerShell Scripts to facilitate this, though I need to clarify boundaries before spending development time :)

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@DEberhardt thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
