### ISSUE TITLE
Needs updating

### ISSUE THREAD

**Issue by hlbcode** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5045]
[Needs updating as new features are not displaying - specifically the new ability to add Skype for consumer comms in Teams]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a2fc46c-d6fb-fd8b-e2aa-fdee7c742230
* Version Independent ID: e0d36a99-2823-68a2-7e97-0c1ba66efd51
* Content: [Teams Only mode considerations - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/teams-only-mode-considerations?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/teams-only-mode-considerations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-only-mode-considerations.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hlbcode Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@hlbcode Thank you for reaching out. I found this recently updated document. Is this link helpful at all?  https://docs.microsoft.com/microsoftteams/teams-skype-interop. Would you suggest having this link added to the article?

**Comment by hlbcode** [comment]
@lindspea thank you for the reply, think it would be helpful to have that link in there with something like - for Teams to Skype for Consumer please check *link*. That should let people know that Skype for Consumer is now supported in Teams. Hope that helps.

**Comment by LanaChin** [comment]
@hlbcode - Thanks for your feedback. The article has been updated with that link to the Teams and Skype interop article.
