### ISSUE TITLE
SRS App freezing Daily

### ISSUE THREAD

**Issue by seiferic** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5046]
I am having an issue with an MTR freezing every day following the update to 4.4.41.

The configuration is as follows:
Lenovo Hub 500
Logi Rally Plus
Dual screens

Checking the Application logs I see the following:
"The program Microsoft.SkypeRoomSystem.exe version 4.4.41.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 22bc
 Start Time: 01d637f7a14abe37
 Termination Time: 4294967295
 Application Path: C:\Program Files\WindowsApps\Microsoft.SkypeRoomSystem_4.4.41.0_x64__8wekyb3d8bbwe\Microsoft.SkypeRoomSystem.exe
 Report Id: 509f1dd3-a51c-4bea-bb94-a3b421823378
 Faulting package full name: Microsoft.SkypeRoomSystem_4.4.41.0_x64__8wekyb3d8bbwe
 Faulting package-relative application ID: App
 Hang type: Navigation
"

While frozen, I am still able to remote in and initiate a restart, which usually fixes.  So it seems to be the App, not the hardware, causing the issue.  Any ideas about this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bef5b5fd-5a4e-7957-f23c-724764a7cb4c
* Version Independent ID: 5fe6c3ab-774b-db2f-5b55-9170bdfe5faf
* Content: [Known issues - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/known-issues)
* Content Source: [Teams/rooms/known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/known-issues.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@seiferic thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
