### ISSUE TITLE
Messaging limits for groups chats larger than 20 people

### ISSUE THREAD

**Issue by fitzgeezy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5047]
It appears that the "Set Delivery Options" button (the !) is removed when private group chats contain mor than 20 members. Please update the Messaging section to reflect this fact.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@fitzgeezy thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by fitzgeezy** [comment]
Hello, I contacted O365 Premier Support (Case #20335108) and they confirmed that this is expected behavior.  Please update the doc.

**Comment by lindspea** [comment]
@fitzgeezy thank you for pointing this out. Just for clarity are you suggesting having a note mentioning "The "Set Delivery Options" button (the !) is removed when private group chats contain more than 20 members" under the Messaging section under footnote 1?

**Comment by fitzgeezy** [comment]
Yes, in the Messaging > Chat section, footnote 1 should also include a statement about the "The "Set Delivery Options" button (the !) being removed

**Comment by scanum** [comment]
@fitzgeezy Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
