### ISSUE TITLE
1 videostream in Teams VDI?

### ISSUE THREAD

**Issue by jvondermans** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5048]
Hi All,

May the 22nd I've seen a change in the known issues and limitations. One of the limitations in particular wondered me. With Teams expending from 2x2 to 3x3 simultaneous streams, the VDI version is reducing the streams to 1.
Is this just a temporary setting or does it stay this way?
We are struggling with users to keep using Teams instead of alternatives and this doesn't help us.

Kind regards,
Jordy

**Comment by scanum** [comment]
@jvondermans thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
