### ISSUE TITLE
Overview disappeared

### ISSUE THREAD

**Issue by J-a-k-o-b** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5050]
Hi, 
in the past there was a big list off known limitations and issues here. This list has now disappeared, please make it viewable again.

It was similar to this rooms specific overview: https://docs.microsoft.com/en-us/microsoftteams/rooms/known-issues

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Unterstützung von Microsoft Teams in Ihrer Organisation - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/known-issues)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@J-a-k-o-b Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @J-a-k-o-b, thank you for your feedback.

Yes, as you perfectly noted, this article was updated and now only contains a list of the top known issues of Teams.
If you want to see all the known issues, you will see that there is an extensive list divided into categories in the left panel:
![image](https://user-images.githubusercontent.com/33589238/88098751-a6985c00-cb70-11ea-9123-52ca644209aa.png)

Hope it helps.

**Comment by scanum** [comment]
@J-a-k-o-b Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
