### ISSUE TITLE
Delegate and EWS

### ISSUE THREAD

**Issue by RomanNG** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5052]
[Enter feedback here]
After contacting Microsoft support has given us the solution. Adding the user agent : **"SchedulingService"** in the EWSAllowList solve the problem for delegation.
It should be prefix and sufix with the "*" symbol.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Use the Microsoft Teams Meeting add-in in Outlook - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by RomanNG** [comment]
must be added like this : *SchedulingService*

**Comment by RomanNG** [comment]
should be prefix and sufix with the "*" symbol

**Comment by RomanNG** [comment]
"*SchedulingService*"

**Comment by scanum** [comment]
@RomanNG Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@RomanNG thank you for pointing this out and helping improve MS Docs. It seems the doc has been updated/fixed in the interim. Please can you confirm.

**Comment by scanum** [comment]
@RomanNG  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
