### ISSUE TITLE
Ik keep getting an error although I did everythng step-by-step: "Grant-CsTeamsChannelsPolicy : The term 'Grant-CsTeamsChannelsPolicy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:29 + $members | ForEach-Object { Grant-CsTeamsChannelsPolicy -PolicyName " ... +                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~     + CategoryInfo          : ObjectNotFound: (Grant-CsTeamsChannelsPolicy:String) [], CommandNotFoundException     + FullyQualifiedErrorId : CommandNotFoundException"

### ISSUE THREAD

**Issue by Bozzl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5060]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd13cd2b-3dca-1b7c-9970-c0f8c2348712
* Version Independent ID: 318c6208-531a-3600-e45b-c43ea845db86
* Content: [Manage teams policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-policies)
* Content Source: [Teams/teams-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Bozzl 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
