### ISSUE TITLE
delay

### ISSUE THREAD

**Issue by AmahaShadow** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5062]
Since, from experience, some of those settings (in particular app permission policy settings) might take quite a while to propagate, It might be worth to mention it as some new users might expect this to be effective immediately. Some other pages on the docs have a banner (such as the invite guest to teams page) indicating that changes might take a few hours before being active. I suggest this banner should be added on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 143108bb-d6e6-48a8-a7cb-d11b89ebeaab
* Version Independent ID: 145773e2-149e-1c1c-5797-433c13f13b22
* Content: [Admin settings for apps in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/admin-settings)
* Content Source: [Teams/admin-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/admin-settings.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AmahaShadow** [comment]
also (nitpicking here) the link in the third paragraph is to the admin portal (https://admin.microsoft.com/) instead of the teams admin site (https://admin.teams.microsoft.com/)

**Comment by scanum** [comment]
@AmahaShadow Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@AmahaShadow thank you for pointing that out and helping improve MS Docs. I'll have a look and have the article updated. It will take a few days for the change to reflect. Thanks again.

**Comment by scanum** [comment]
@AmahaShadow Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
