### ISSUE TITLE
Wrong description of Teams Chat and Conversation Data

### ISSUE THREAD

**Issue by 12Knocksinna** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5067]
[Enter feedback here]

This information is wrong. 
Teams compliance records are stored in the TeamChat subfolder of the user mailbox (for chats) or group mailbox (for channel conversations). SubstrateHolds is used for held copies. The compliance records are not perfect copies of the Teams message data stored in Azure and should not be represented as if the version in Exchange is the master. The EXO data is very definitely a subset of the real information held in Azure.

Teams chats are stored in a hidden SubstrateHolds folder in the mailbox of each user in the chat, and Teams channel messages are stored in a hidden SubstratesHolds folder in the group mailbox for a team. Teams uses an Azure-powered chat service that also stores this data, and by default this service stores the data forever.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f55c52a5-5841-b9c9-1607-2013dc3f2e20
* Version Independent ID: 16d93458-5e01-646f-dac5-31306cc7f3fb
* Content: [Retention policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/retention-policies)
* Content Source: [Teams/retention-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/retention-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **anwara**

**Comment by scanum** [comment]
@12Knocksinna Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@12Knocksinna thank you for reaching out and helping improve MS Docs. Just for clarity are you suggesting this wording to replace the original wording. "Teams chats are stored in a hidden SubstrateHolds folder in the mailbox of each user in the chat, and Teams channel messages are stored in a hidden SubstratesHolds folder in the group mailbox for a team. Teams uses an Azure-powered chat service that also stores this data, and by default this service stores the data forever."

**Comment by 12Knocksinna** [comment]
Hi Lindsay,

Yes. The description is not accurate. Teams chats are always stored in Azure Cosmos DB. The items held in Exchange Online are compliance records (copies) intended for eDiscovery.

See https://office365itpros.com/2020/05/19/understanding-capture-teams-compliance-data/

I’ve been through this topic many times with Praveen and the Teams compliance folks…

TR

**Comment by lindspea** [comment]
@12Knocksinna Hi Tony. It seems the article was recently updated and they changed some information. Please double check and let me know.

**Comment by 12Knocksinna** [comment]
Unhappily the text is still wrong.

How Teams retention policies work
**Teams chats are stored in a hidden folder-**Teamschat- in the mailbox of each user in the chat, and Teams channel messages are stored in a hidden folder-Teamschat- in the group mailbox for a team. Teams uses an Azure-powered chat service that also stores this data, and by default this service stores the data forever. With a Teams retention policy, when you delete data, the data is permanently deleted from both the Exchange mailboxes and the underlying chat service.

This should describe Teams compliance records instead of Teams chats. As written. it implies that the actual Teams data is stored instead of compliance records created for eDiscovery purposes.

**Comment by lindspea** [comment]
@LanaChin please can you have a look at this issue?

**Comment by LanaChin** [comment]
Reached out to PMs.

**Comment by anwara-ms** [comment]
@12Knocksinna - Tony, it is true that primary data store is Chat service, and data is also stored in mailboxes for compliance purposes i.e. eDiscovery, retention etc. But the main point is that we have two copies of data.

Could you please re-word the part that you feel is not accurate and I can include that in our documentation.

**Comment by 12Knocksinna** [comment]
Hi,

I fully understand that the data is stored in EXO for compliance purposes and have written extensively on the topic after discussing it with the compliance PMs (see https://office365itpros.com/2020/05/19/understanding-capture-teams-compliance-data/ as an example). However, the assertion that EXO is a secondary data store or that two copies of data exist is incorrect simply because the data held in EXO is incomplete. If a copy is incomplete, it’s not a replica and it can’t be used in the same way as the original.

There are a bunch of places in Teams documentation where the implication is that the data in EXO is real chat/message data instead of clearing stating that it is a copy taken for a specific purpose and intended only for that purpose. This then creates the problem that some backup vendors use the documentation to justify their stance that backing up the compliance records from EXO equates to backing up Teams… which is rubbish, because you can’t restore the compliance records into chats or channel conversations.

TR

**Comment by anwara-ms** [comment]
currently OOF. I will update the document when I am back from the break.

**Comment by scanum** [comment]
@anwara-ms Hi Anwara, any updates here? Thanks!

**Comment by anwara-ms** [comment]
I have another PR, you can close this case

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/6726
