### ISSUE TITLE
App permission policies will not help to organisations in longer run

### ISSUE THREAD

**Issue by rahulraj40** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5071]
We looked through article and understood how App permission policies are working, but these policies will not help organisations in long run.

Let’s say we have 100 users in Organization, out of which 10 users(Grp1) need one third party app and other 10 users(Grp2) need different third party app.
Here, 
This could be managed by creating 2 separate custom policies for 2 groups and leaving remaining 80 users(Grp3) in the global policy.

Challenges:
1.	If there would be similar requests keeps coming for third party apps then we will end up creating multiple custom policies.
2.	In case there comes a situation where lets say 5 users from Grp1 and 5 users from Grp2 and 5 users from Grp3 required different third party apps. If there are few such instance this could be still handled through custom policies. But if such request keeps coming, how such scenarios can be handled?

If same restrictions (license limitation or availability of app for set of users only) has to be applied for Microsoft apps or custom apps also, then we will just end up creating multiple custom policies it's useless.

These policy settings are like creating mess around without much benefits. Why can't Microsoft give similar options that we have to manage add-ins in Microsoft 365 admin center to manage apps in teams.

**Comment by scanum** [comment]
@rahulraj40 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
