### ISSUE TITLE
Assign a custom app setup policy to users in a group

### ISSUE THREAD

**Issue by rahulraj40** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5072]
This feature makes no sense actually, I would rather use below script
$userobjects = Import-CSV "C:\Appl\Test.csv"
foreach ($UO in $userobjects) {
    Grant-CsTeamsMeetingPolicy -Identity $UO.WindowsEmailAddress -PolicyName 'custom policy name'
 }

Why can't Microsoft provide options to **_apply policy on groups(security groups, O365 groups or DL)_**, so that addition or removal of users from group will inherit the policy settings applied on the groups. This is a lot easier than assigning policy to users in a group.

**Comment by scanum** [comment]
@rahulraj40 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by rahulraj40** [comment]
The is not the issue that I have reported, this is the product limitations or call it feature limitations.
