### ISSUE TITLE
Typo (Phone Systems)

### ISSUE THREAD

**Issue by JetzeMellema** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5082]
The document contains a table that lists "Phone Systems" as one of the licenses. This should be singular, Phone System without the s.

https://docs.microsoft.com/en-us/microsoftteams/set-up-common-area-phones?source=docs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ab5215-f24f-75cf-bb92-16ac0ff5e5ca
* Version Independent ID: 701cc58f-d2ea-cbb6-f5fc-47b9fbfb1119
* Content: [Set up the Common Area Phone license - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-common-area-phones?source=docs)
* Content Source: [Teams/set-up-common-area-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-common-area-phones.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@JetzeMellema Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@JetzeMellema Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
