### ISSUE TITLE
Can you please add cmdlet to run Microsoft Azure Popup silently - SIPTesterclient Script

### ISSUE THREAD

**Issue by rkashinath** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5083]
Can you please add cmdlet to run Microsoft Azure Popup run silently in this portion of script below? I want to schedule this hourly and it keeps asking this popup to enter the credentials.

if ($UseUserCredentials) {
            $pwd = ConvertTo-SecureString -AsPlainText $TeamsOutPassword -Force
            $authContext = New-Object "Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext" -ArgumentList $authority
            $AADcredential = New-object -typename System.Management.Automation.PSCredential -ArgumentList $TeamsOutUsername,$pwd
            $req = [Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContextIntegratedAuthExtensions]::AcquireTokenAsync($authContext,$resourceUrl,$clientId,$AADcredential)
            $response = $req.Result
        } else {
            $response = Get-ADALToken -Resource $resourceUrl -ClientId $clientId -Authority $authority

**Comment by scanum** [comment]
@rkashinath Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@rkashinath thank you for reaching out. Please can you link the article related to your request so that I can help further.

**Comment by rkashinath** [comment]
Hey Lindsay, I am not sure if you understood my request.. Just to explain you again, the siptester script which I downloaded from technet, I am using it run the validation test for Direct routing. So script works absolutely fine, but everytime I run the script it asks for Azure credentials popup to enter creds. I want to use this script to run everyone hour auto schedule as a synthetic transaction but because of this challenge I cannot use this script. This will be really great usecase as part of Monitoring Teams phone system and our SBC's. If you would like to connect and get on a call, happy to do that.

**Comment by lindspea** [comment]
@rkashinath thank you for clarifying, however I work on the editing/writing side of MS Docs so I can only help to make changes requested to an article in question.

**Comment by scanum** [comment]
@lindspea @rkashinath Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
