### ISSUE TITLE
"account preparation is started two to three weeks before installation"

### ISSUE THREAD

**Issue by voutit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5084]
Why do you recommend 2-3 weeks for the account creation here? What are the actual technical sync times between Azure AD and Teams?

_"It is highly recommended that account creation be done well in advance of actual hardware installation. Ideally, account preparation is started two to three weeks before installation."_ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 834f564b-d32a-25ba-437b-1cb74adbf485
* Version Independent ID: 9bdb6864-caa0-d0fa-ce06-eaaa1fd18fe3
* Content: [Configure accounts for Microsoft Teams Rooms - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-configure-accounts?source=docs)
* Content Source: [Teams/rooms/rooms-configure-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-configure-accounts.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@voutit Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
