### ISSUE TITLE
'Set-CsUser' is no longer recognised as a command

### ISSUE THREAD

**Issue by iborghoff** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5085]
The command doesn't appear to be valid anymore in this module. I've not been able to find a replacement or alternative yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb2a9717-6565-8443-8833-f7fdce562781
* Version Independent ID: db88c4d6-5864-a481-86cf-465feb452d75
* Content: [Enable users for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-enable-users)
* Content Source: [Teams/direct-routing-enable-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-enable-users.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@iborghoff Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by iborghoff** [comment]
Thanks for the reply @scanum. In the end I figured out that the issue was my end; my account had been removed from the enterprise application "Microsoft Intune PowerShell". Adding my account back to this application made the command available again.
