### ISSUE TITLE
Desktop icon is not created

### ISSUE THREAD

**Issue by syntetic81** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5086]
Hi,

you write that msiexec /i Teams_windows_x64.msi OPTIONS="noAutoStart=true" ALLUSERS=1
When a user logs in to Windows, Teams is installed with the MSI and a shortcut to start Teams is added to the user's desktop.

I use SCCM to rollout Teams exactly with the command above. Teams will be installed in c:\Program Files (x86)\Teams Installer - but no Link is created on Users Desktop.

Sincly
Frank 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Installieren von Teams mit Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/msi-deployment#disable-auto-launch-for-the-msi-installer)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@syntetic81 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
