### ISSUE TITLE
Clarification or Correction

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5087]
External Access Allowed Domains seems to restrict chat and calls (as expected) but not meetings (as documented here).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external access (federation) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Air-Git Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Air-Git** [comment]
The solution is: the list of Allowed Domains or Blocked Domains is not evaluated for meetings if Anonymous access is allowed. To block authenticated users by domain when anonymous access is allowed would be nonsensical.

**Comment by lindspea** [comment]
@Air-Git thank you for reaching out and helping improve MS Docs. Just for clarity are you suggesting changing the wording in the article as per your above comment?

**Comment by Air-Git** [comment]
Yes. The document describes Allowed or Blocked domains for external access in chat, calls and meetings. This is incorrect. The allowed or blocked domains only apply to meetings if Anonymous access to meetings is Off. By default, it is On.

**Comment by lindspea** [comment]
@Air-Git thank you for clearing that up. Please could you let me know exactly where in the article it mentions the content that needs to be corrected. Apologies, I'm battling to find it.

**Comment by Air-Git** [comment]
First para says that the scope includes meetings.
Fourth para says that if you add allowed domains, all other domains will be blocked. This is not true for meetings, if anonymous participants are allowed.

**Comment by scanum** [comment]
@Air-Git  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
