### ISSUE TITLE
Note Tells me it's creating an Block Rule / not an Allow Rule

### ISSUE THREAD

**Issue by chwilfing** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5088]
The Text in the Note below the screenshot tells me - to create block rules not allow. but the powershell script correctly creates an allow rule. 

BG Christoph

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients#sample-powershell-script)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@chwilfing Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@LolaJacobsen please could you confirm what it should be - allow or block?

**Comment by LolaJacobsen** [comment]
@juturu @voltarone - can you check the note under the screen shot and let me know whether I should change the article from "Block" to "Allow?"

**Comment by LolaJacobsen** [comment]
@juturu @voltarone - ping. Which is correct - allow or block?

**Comment by SerdarSoysal** [comment]
@scanum @lindspea yes the note should say "allow" that's an error. Please have the topic updated, assign the PR to me and I'll merge. We can then close this one and 5021.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
