### ISSUE TITLE
You also need to enable users to add guests to Office 365 Groups in order for this to work

### ISSUE THREAD

**Issue by mikenri** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5090]
This process does not work unless you also enable users to add guests to Office 365 Groups.

This should be referenced in this document that you also need to follow this process before users can add guests to Microsoft Teams:

https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-guest-access-in-groups?view=o365-worldwide#manage-groups-guest-access

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042d7ce6-ee22-690f-8188-ff8a4a585847
* Version Independent ID: 3e5bc99c-e08e-44e0-cda3-687ed3633175
* Content: [Turn on or turn off guest access to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-guests)
* Content Source: [Teams/set-up-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-guests.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@mikenri Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@mikenri Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
