### ISSUE TITLE
Firewall Proxy Host Name/Port Examples

### ISSUE THREAD

**Issue by JeffBrownTech** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5091]
[Enter feedback here]
Can someone review the **Firewall Proxy Host Name/Port Examples** table? The note at the bottom says that the wildcard for contoso.com represents nodes in Office 365, but this is a domain that is typically used as an example company. I find it surprising that this domain would be used for production systems in O365.

Also, the destination ports for Video and Desktop sharing make no mention of other ports used by Skype for Business Online and Teams like 3479-3481. And is the 50K range of ports still required? I thought these were now optional due to transport relays being deployed.

I feel the table needs a technical review to ensure all this information is accurate and is in line with the Docs article that the Destination IP column refers to:

https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#skype-for-business-online-and-microsoft-teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a711c07e-10b3-baf0-b92c-9dbcf6ab9474
* Version Independent ID: 2038cd48-44b1-1ed1-6e50-48290eef5605
* Content: [Prepare your Environment - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-prep)
* Content Source: [Teams/rooms/rooms-prep.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-prep.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@JeffBrownTech Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@JeffBrownTech Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by LanaChin** [comment]
Reassigning to @dstrome

**Comment by scanum** [comment]
@dstrome Hi David! Any updates here? Thanks!

**Comment by dstrome** [comment]
hi all - I'm researching this.

**Comment by lindspea** [comment]
@dstrome

**Comment by dstrome** [comment]
Closing old issues.
