### ISSUE TITLE
The RelatedGroupId property does not exist when using SPO Powershell

### ISSUE THREAD

**Issue by RomanNG** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5094]
[Tapez vos commentaires ici]
After several tries, the  **Get-SpoSite -Identity "<private channel spo url>" -Detail** does not return any property  named RelatedGroupId. I'm using sharepoint online management shell version 16.0.20122.12000. Are there any change with the module or is the documentation not up to date ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 33e0ac38-cfff-8d8f-5345-2ae93a9fae2e
* Version Independent ID: bec44289-e9fa-4464-1601-0ca86d61e6ca
* Content: [Gérer le cycle de vie des canaux privés dans Microsoft teams - Microsoft Teams](https://docs.microsoft.com/fr-fr/MicrosoftTeams/private-channels-life-cycle-management)
* Content Source: [Teams/private-channels-life-cycle-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels-life-cycle-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@RomanNG Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
