### ISSUE TITLE
Behavior when selecting BlurandDefaultBackgrounds is not clear 

### ISSUE THREAD

**Issue by JorgeALeitao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5095]
[Enter feedback here]
Article states that:
.....
BlurandDefaultBackgrounds | User has the option to blur their video background or choose from a **set of images** to use as their background.

However the actual effect is that users have only the to blur the background or select from the **default set** of images. 

that would leave no room for doubts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams?source=docs#meeting-policy-settings---video-filters-mode)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by LanaChin** [comment]
Thanks for your feedback and helping to improve our docs, @JorgeALeitao. I've updated the BlurAndDefaultBackgrounds and AllFilters options to say "...from the default set of images."
