### ISSUE TITLE
Presence

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5102]
In Skype consumer, I able to see the presence of a Teams user.  This statement may be incorrect:

Limitations:
Teams users and Skype users can't see each other's presence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3de87096-6253-ba71-f27a-0b161a36f0e2
* Version Independent ID: 8b61b40d-496c-6069-8a60-38a6282e072a
* Content: [Teams and Skype interoperability - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-skype-interop)
* Content Source: [Teams/teams-skype-interop.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-skype-interop.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
Hi @danmyhre As per PM, the statement is correct as is. Team users and Skype users can't see each other's presence. This is not supported. Thanks again for reaching out. @scanum this can be closed thank you.

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by danmyhre** [comment]
@scanum might want to have the PM re-check.  In Skype consumer, you can definitely see a Teams user's presence.
