### ISSUE TITLE
Missing features not called out for Web Clients

### ISSUE THREAD

**Issue by lachew** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5104]
[Enter feedback here]

There is a discrepancy in the documentation where it says that google chrome is fully supported with no call out of a missing feature. You can use the call me at function within Meeting details on Edge Chromium, but that feature is missing on Google Chrome. This is the ability to Enter phone number when you are in a meeting to call me by going through the ellipsis -> Meeting details. 

Is that supposed to be called out in our documentation? I had some trouble explaining to a customer what does it mean when it says fully supported if its not feature parity. 

Picture is from edge chromium where the feature is there. 
![teams](https://user-images.githubusercontent.com/66705753/84213970-e7cc2500-aa76-11ea-94fb-4e2a16fbbc97.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients#web-client)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@lachew Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@lachew thank you for reaching out and helping improve MS Docs. Just checking if the footnotes under the table have been taking into consideration and could be an issue with what's missing. "To give and take control of shared content during sharing, both parties must be using the Teams desktop client. Control isn't supported when either party is running Teams in a browser. This is due to a technical limitation that we're planning to fix."

**Comment by lachew** [comment]
Hello Lindsay,

I did read that, but the specific issue that my customer called out is not related to taking control. They were confused because Google Chrome says fully supported, but they couldn’t use call me at functionality on Google Chrome, could do it on Microsoft Edge.


-


Larry Chew
Technical Specialist – MW Teams
Financial Services Industry
Larry.Chew@microsoft.com<mailto:Larry.Chew@microsoft.com>
+1 (415) 869-3839
[Microsoft]

**Comment by lindspea** [comment]
@lachew thank you, the team is working on a fix.

**Comment by lindspea** [comment]
@scanum this can be closed thanks.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
