### ISSUE TITLE
Personal Account vs. Business Account

### ISSUE THREAD

**Issue by phanley10** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5106]
I'm looking to determine the trade-off between submitting a Teams app from a personal account vs. a business account. And if it is already up and running as a personal account, what the trade-offs would be converting it to a business account. Based on the documentation, this seems like the right spot for that information to be included.

Can you help me better understand a few questions:
- What would happen to the customers that are currently on this version of the Teams integration?
- Would we be able to turn the other version on first so we would know it is up and functional before shutting down the original version?
- Do current customers need to switch then? If so, how do they do this?

Thanks,

Patrick Hanley
Director of Strategic Alliances
m: 414.737.4534
e: phanley@dynamicsignal.com
Dynamic Signal 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 143108bb-d6e6-48a8-a7cb-d11b89ebeaab
* Version Independent ID: 145773e2-149e-1c1c-5797-433c13f13b22
* Content: [Admin settings for apps in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/admin-settings)
* Content Source: [Teams/admin-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/admin-settings.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@phanley10 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
