### ISSUE TITLE
Missing information about mailbox on Exchange Online

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5107]
Hello

We are missing an information that user needs to have mailbox hosted online in order to be able to schedule a live event.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events#teams-live-events-and-skype-meeting-broadcast)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Larryngolog  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Larryngolog thank you for pointing this out. I'm not sure that this is a requirement, but I'm checking with the team. In the meantime here is a recently updated article. Let me know if it helps - https://docs.microsoft.com/microsoftteams/exchange-teams-interact

**Comment by scanum** [comment]
@LarryngologThank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
