### ISSUE TITLE
typo 

### ISSUE THREAD

**Issue by edavel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5112]
IS this a typo? Current example says, "For example, if you have two domain names, contoso.com and contoso.on.microsoft.com, use sbc.contoso.com as the SBC name."

shouldn't it be, contoso.onmicrosoft.com, not contoso.on.microsoft.com? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad7d5051-1177-c5cf-bf28-8639d7b6fbd1
* Version Independent ID: 2a9aa4e1-3767-cd46-50fe-f9dd8b0997be
* Content: [Connect your Session Border Controller (SBC) to Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-connect-the-sbc#feedback)
* Content Source: [Teams/direct-routing-connect-the-sbc.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-connect-the-sbc.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@edavel  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@edavel Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
