### ISSUE TITLE
Section about deploying Teams, contains no technical details about deploying Teams.

### ISSUE THREAD

**Issue by ccsjnw** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5116]
Under the Deploy section of the Teams site, there are a few funky slides about approaches to integrating Teams within a business, but there is no technical information about the best way to deploy the Teams App in a managed environment. Indeed this subject is very sparsely covered across the whole Microsoft site.

Currently, Teams is a per user App (!). It installs and runs from every users' AppData folder. Every user that logs into the computer has a separate Teams installation. It means that end users can install Teams, without needing Administrations rights to the computer they are using - it's horrendous.

System Admins need to be able to control and deploy Teams reliably via GPO (or other supported mechanisms) to shared computer environments, and want it to install just **once**, into the Program Files folder. SysAdmins also need to prevent end users being able to install Teams in an unmanaged way.

If Teams was previously installed via the Office 365 installer, then any updates or installs using the MSI file don't work (nothing happens).  The machine wide deployment agent from Teams 1.2, seems to stop version 1.3 working. Teams version management is completely missing and the Teams App doesn't follow the 'Semi-Annual' channel update schedule like the rest of office 365 does. How are we supposed to control the Teams client update cadence in a corporate environment?

Put bluntly, in a managed computer environment (AD), Teams is such a mess. This really needs to be addressed by Microsoft urgently, so Teams can be deployed reliably in computer estates managed centrally. It's a nightmare for SysAdmins & technicians trying to fix problems. End users just want it to work consistently on every computer they use within the organisation.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b131c7fd-ec71-6b6f-4443-ddaf5cb44bf6
* Version Independent ID: 0c1fb61b-a6cc-e856-d969-54bc13ec699c
* Content: [How to roll out Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/how-to-roll-out-teams)
* Content Source: [Teams/How-to-roll-out-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/How-to-roll-out-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@ccsjnw Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
