### ISSUE TITLE
Audio Conferencing can be added to Business Basic

### ISSUE THREAD

**Issue by jokruege** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5117]
Business Basic is not listed on the page as a qualifying plan for Audio Conferencing. However, you can add the Audio Conferencing plan to a Business Basic plan.

Please add Business Basic to the list of prereq plans.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59426612-8da4-be3e-f0c8-8c23e9178d7d
* Version Independent ID: bd2d7426-06d6-5c18-7776-a50fc05c9ce9
* Content: [Configure Audio Conferencing settings - Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/deploy-audio-conferencing-teams-landing-page#audio-conferencing-prerequisites)
* Content Source: [Teams/deploy-audio-conferencing-teams-landing-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/deploy-audio-conferencing-teams-landing-page.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@jokruege Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@jokruege thank you for reaching out and helping improve MS Docs. Please could you be a bit more specific. I see Microsoft 365 Standard Business is reflecting there or am I misunderstanding something?

**Comment by jokruege** [comment]
@lindspea Yes, M365 Business Standard is listed. However, the plan M365 Business Basic is not listed and Audio Conferencing can be added to that type of license.

https://docs.microsoft.com/en-us/microsoftteams/deploy-audio-conferencing-teams-landing-page#audio-conferencing-prerequisites

**Comment by lindspea** [comment]
@LolaJacobsen please could you help confirm?

**Comment by LolaJacobsen** [comment]
Checking with PMs.

**Comment by LolaJacobsen** [comment]
We recently updated our licensing content. The current authoritative resource is this article:

https://docs.microsoft.com/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing

We'll be updating all of our documentation to point to this new article.
