### ISSUE TITLE
Policy assignment to groups

### ISSUE THREAD

**Issue by RobFullerGBHS** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5118]
When will policy assignment to groups by GA? Still getting Access Denied on our tenant.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888fe05b-1160-452f-90ba-deb19adb740f
* Version Independent ID: 4091c5e4-7a90-7fe4-2741-16bbb1f297c1
* Content: [Assign policies to your users in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/assign-policies)
* Content Source: [Teams/assign-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@RobFullerGBHS Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by songngu1** [comment]
The Feature  used to assign a policy package to a group and  powershell script "Grant-CsGroupPolicyPackageAssignment"  Microsoft Article describing the purpose, requirement and how to use the script however today when i checked it seems like the script has been removed. Anyone know the  timing of this feature rolling out and/or is there an opt-in for it
