### ISSUE TITLE
Confusing Number Type options

### ISSUE THREAD

**Issue by aamillerMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5119]
Confusing statement needs rewritten.  It occurs in 2 locations on the document.
> What types of phone numbers you need assistance with (User/Subscriber or Service/Toll/Toll-Free).

Based on our explanation of Phone Number types [here](https://docs.microsoft.com/en-us/microsoftteams/different-kinds-of-phone-numbers-used-for-calling-plans):
There are only 2 types, User and Service, Subscription is not an option.

This should read:
> What types of phone numbers you need assistance with (User, Service Toll, or Service Toll-Free).

Also, I would reference the Number Type explanation link closer to these 2 lines instead of the relevant line, instead of as an "Additional Resource"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ddf1c3c-7fb9-ff3c-e8cd-af75999c78cb
* Version Independent ID: 6178c672-003f-8f99-f4ab-cf9b06cf5ede
* Content: [Contact the PSTN service desk - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk)
* Content Source: [Teams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by tonysmit** [comment]
Updated and merged. Thanks for the feedback!
