### ISSUE TITLE
"Turn on or turn off recording transcription" section innacuracies

### ISSUE THREAD

**Issue by NickElniff** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5122]
[Enter feedback here]
The 'Turn on or turn off recording transcription' section is confusing and the wording of the feature is not accurate. A user that records a meeting does not have a choice whether transcripts or generated or not.

Suggestion would be that the section reads like the "Allow Transcription" section in the Meeting Policy Settings page - https://docs.microsoft.com/en-US/microsoftteams/meeting-policies-in-teams?WT.mc_id=TeamsAdminCenterCSH#allow-transcription

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by tonysmit** [comment]
Suggested change merged.
