### ISSUE TITLE
Control guest access in Microsoft 365 Groups

### ISSUE THREAD

**Issue by ma7mgte** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5123]
Control guest access in Microsoft 365 Groups section needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b05e642-c4e5-f1b5-5315-d3ef1690a0cd
* Version Independent ID: 01b7e0b5-3e50-3de0-e3e9-aeeeda43da12
* Content: [Authorize guest access in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-dependencies)
* Content Source: [Teams/Teams-dependencies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-dependencies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ma7mgte Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@ma7mgte Thank you for reaching out and helping improve MS Docs. I see the article was recently updated. Please confirm if you need further assistance, or if there is anything specific you think is missing.

**Comment by scanum** [comment]
@ma7mgte Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
