### ISSUE TITLE
Schedule a tag

### ISSUE THREAD

**Issue by Saml43** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5125]
Is there a way to schedule using a tag? So under person's instead of having to list out each person we could use the @ tag mention and it would pull in all person's in that team with that tag.

**Comment by scanum** [comment]
Hi @LanaChin could you please help out with this one as well? Thanks!

**Comment by LanaChin** [comment]
FYI @anniecolonna

**Comment by anniecolonna** [comment]
Hi @Saml43, thanks for your feedback! Are you asking about scheduling a meeting or setting up a calendar invite in Teams then adding tags into the attendee section? Or is this another experience?

**Comment by LanaChin** [comment]
Closing this for now. @Saml43, please open another issue if you need help with your question. Thank you!
