### ISSUE TITLE
Lync Server 2013 compatiblity

### ISSUE THREAD

**Issue by bamsazizi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#513]
I am trying to enable ADAL for Lync Server 2013. Is it compatible with ADAL at all?
I am stuck in this command: 
New-CsOAuthServer -Identity sts.contosoIn.com -Type ADFS -MetadataURL https://sts.contosoIn.com/FederationMetadata/2007-06/FederationMetadata.xml
It expects to read a json file not xml. Any feedback and comment would be appreciated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcc8ce50-2000-041a-9489-0acea7b2e24a
* Version Independent ID: 0839378b-1455-b5b5-f315-29e55c25cee8
* Content: [How to use Modern Authentication (ADAL) with Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/manage/authentication/use-adal)
* Content Source: [Skype/SfbServer/manage/authentication/use-adal.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/authentication/use-adal.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by kenwith** [comment]
@bamsazizi  - thank you for submitting feedback. I am not a SME in this area and want to make sure this is resolved for you ASAP. I think the best way forward is if you can open a service ticket so this can be routed correctly and solved right away. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs. Let's keep this open until resolved.
