### ISSUE TITLE
Issue with wording - FRONT END SERVER not EDGE SERVER

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5130]
This line should read FRONT END SERVER not EDGE SERVER
Configure Cloud Voicemail as the hosting provider on the **Edge Server** as described in this article

The first line in the paragraph it links to correctly shows Front End Server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec8b8afb-b9ca-8136-b907-5bbff4c9dcf1
* Version Independent ID: d4f68818-6fe6-5bb7-f108-e26a643f2cc7
* Content: [Configure Cloud Voicemail service for on-premises users - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/configure-cloud-voicemail#configure-cloud-voicemail-as-the-hosting-provider)
* Content Source: [Skype/SfbHybrid/hybrid/configure-cloud-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-cloud-voicemail.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@jantoney Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dstrome** [comment]
updated
