### ISSUE TITLE
Cómo conectar PowerShell con Teams

### ISSUE THREAD

**Issue by WilliamGarzonM** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5131]
Para personalizar o modificar las directivas de reunión de Teams, se requiere hacerlo desde PowerShell. Instalé SkypeOnlinePowerShell, reinicié el equipo, introduje las credenciales desde Powershell (Ver 5.1) y después sólo salen errores. De que forma se pueden ejecutar los cmdlets si no existe el modo de ejecutar powershell en Teams?
---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 26362d70-cfce-2eea-077b-4aaa50f92e8b
* Version Independent ID: f52dcd4d-4f58-05c4-11b0-f1e3c95f4d89
* Content: [Información general de Teams PowerShell - Microsoft Teams](https://docs.microsoft.com/es-es/microsoftteams/teams-powershell-overview)
* Content Source: [Teams/teams-powershell-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@WilliamGarzonM Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
