### ISSUE TITLE
Teams phone support the delegation feature?

### ISSUE THREAD

**Issue by sperantia** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5134]
I confirmed Teams IP phone support the delegation by the latest firmware.
Could you confirm this docs please

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8d3dd879-564e-62ca-2095-3ef6ae4fab2d
* Version Independent ID: 8ed3dff3-b2b8-b3db-6db9-6bbecdb6cf5c
* Content: [Microsoft Teams での回線共有機能 - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/shared-line-appearance)
* Content Source: [Teams/shared-line-appearance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/shared-line-appearance.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@OfficeGlobal Could you please help with this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by scanum** [comment]
@sperantia Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
