### ISSUE TITLE
Live Event dial-in

### ISSUE THREAD

**Issue by mgcharumilind** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5135]
The image of the license info table at https://docs.microsoft.com/en-us/microsoftteams/quick-start-meetings-live-events#get-licenses-for-meetings-and-live-events
 on this page says "Any phone number can dial in to a Teams Live Event," however that does not seem to be accurate. See UserVoice status here https://microsoftteams.uservoice.com/forums/555103-public/suggestions/38277844-pstn-for-live-event-audio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92fcb1f6-5cc2-f6bd-cfa9-11d811f1dbf1
* Version Independent ID: 9a571e6d-8cb3-9ff8-a5c2-62deab146264
* Content: [Admin quick start - Meetings and live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/quick-start-meetings-live-events)
* Content Source: [Teams/quick-start-meetings-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/quick-start-meetings-live-events.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@mgcharumilind Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@mgcharumilind Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
