### ISSUE TITLE
Misleading statement regarding B2B access

### ISSUE THREAD

**Issue by owenmpls** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5143]
"To communicate with a guest, the guest has to be signed in to Teams using their guest account. This means that a guest may have to sign out of their own Teams account to sign in to your Teams account."

This statement is somewhat misleading. The principal use case for B2B collaboration is to allow guests to access other tenants using their primary Azure AD account (i.e. the account that's most likely licensed for Teams). Is this meant to refer to tenant switching in the app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f080a5c-4268-1db4-566f-f1edc27920b5
* Version Independent ID: ac556a92-58af-3e05-f53b-0fc00afc96c0
* Content: [Communicate with users from other organizations in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/communicate-with-users-from-other-organizations)
* Content Source: [Teams/communicate-with-users-from-other-organizations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/communicate-with-users-from-other-organizations.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@owenmpls Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @owenmpls, thank you for your feedback and help us to improve docs.microsoft.com.

I think the key of the sentence is the "may have" words. Anyway, I´m adding a little detail. What do you think?

**Comment by scanum** [comment]
@owenmpls We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
