### ISSUE TITLE
How to delete a team I created with a personal account? 

### ISSUE THREAD

**Issue by gaurav-nelson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5145]
This page doesn't answer How to delete a team I created with a personal account? 

When I use the provided steps I get:
>You can't sign in here with a personal account. Use your work or school account instead.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf689b7-a7c1-121f-578e-029e8a89c4f0
* Version Independent ID: 7e6b449e-bd77-2fc4-2c3d-1f2e364e1b76
* Content: [Archive or delete a team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/archive-or-delete-a-team)
* Content Source: [Teams/archive-or-delete-a-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/archive-or-delete-a-team.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@gaurav-nelson Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by gaurav-nelson** [comment]
@scanum Thank you for looking into this. However, that page doesn't help either. 

The problem is that I've signed up for teams using my personal email address and the support link you've shared doesn't work, I receive the same error message `You can't sign in here with a personal account. Use your work or school account instead.`

So it seems I can't open a service ticket. I see no option of creating a support ticket from the Teams app either. This is a product issue rather than a docs issue. I'll see if I get it done with phone support. 🤦‍♂️
