### ISSUE TITLE
Comodo CA is no longer issuing certificates signed by Comodo Secure Root CA.

### ISSUE THREAD

**Issue by Dragonsong3k** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5148]
Comodo CA is no longer issuing certificates signed by Comodo Secure Root CA.
They are being issued by Sectigo, UserTRUST or AAA. 

Are these root CAs supported as a result of Comodo CA being changed to Sectigo?
Or is Comodo CA certs no longer supported?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e26faf8c-529e-b317-5934-cd41cfe8fa24
* Version Independent ID: 3ddd5d0a-6dbb-4940-1814-8346e293701b
* Content: [Plan Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan)
* Content Source: [Teams/direct-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Dragonsong3k Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Dragonsong3k** [comment]
UPDATE - I asked Sectigo / Comodo about this. Apparently they can still issue certificates signed by Comodo Secure Root CA UPON REQUEST. 
But I don't think that will always be the case. Eventually they will phase it out.

**Comment by dariomws** [comment]
Hi @Dragonsong3k, thank you for your feedback and help us to improve docs.microsoft.com.

I think it is a good idea to leave this root certificate listed longer.

**Comment by FilippSe** [comment]
Sectigo can be added to the list of certified authorities, they need to contact Microsoft to do this.

**Comment by scanum** [comment]
@Dragonsong3k Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
