### ISSUE TITLE
Requirements for one certificate for 2 SBCs would be useful

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5150]
A common deployment scenario is to have two SBCs for redundancy. It would be useful to have details on how one certificate can have the SN be the FQDN of one SBC, with the FQDNs for both SANs listed. I've seen a couple of people stuck with this issue, because they didn't know how to build the CSR for the cert for this scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e26faf8c-529e-b317-5934-cd41cfe8fa24
* Version Independent ID: 3ddd5d0a-6dbb-4940-1814-8346e293701b
* Content: [Plan Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-plan)
* Content Source: [Teams/direct-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@TorrenManson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @TorrenManson, thank you for your feedback and help us to improve docs.microsoft.com.

You can use a wildcard in the SAN to cover more than 1 SBC:

"Alternatively, Direct Routing supports a wildcard in SAN, and the wildcard needs to conform to standard RFC HTTP Over TLS. An example would be using *.contoso.com in the SAN, which would match the SBC FQDN sbc.contoso.com, but wouldn't match with sbc.test.contoso.com."

**Comment by TorrenManson** [comment]
That is true, however a number of organizations have very explicit policies against wildcard certificates. Further, a wildcard often costs more than a 2 SAN cert does.

2 (or more) SAN certs work, but the article has no practical guidance on this.

**Comment by dariomws** [comment]
Thanks @TorrenManson, I know that SAN works, I'm trying to get the approval from the product manager to add some information here.

**Comment by dariomws** [comment]
Hi @TorrenManson, sorry for the delay. SAN support was added 3 months ago in the following Pull Request:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/6537

@scanum please close this issue.
