### ISSUE TITLE
Private Channel article update

### ISSUE THREAD

**Issue by I353620** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5153]
https://docs.microsoft.com/en-us/microsoftteams/private-channels

With respect to the MS Case#20384465, I was asked to provide this feedback to update the below topic on this article for the end user information.

Private channel guest email lookup will not work due to security design reason, only able to search using the guest display name. (Not: Guests are already added in the main team)

It would be great if you add this content to the official MS page.

Thanks,
Mani.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@I353620 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @I353620, thank you for your feedback and help us to improve docs.microsoft.com.

I'm not sure if it's the best article to add this information to. This is a Private Channels article for Administrators, and I think what is discussed is better for a user article.

**Comment by I353620** [comment]
Hi @dariomws , Thanks for the comment.

Correct, that was the intention to Administrator aware of this and add this info to their end user articles. If you don't add it here then how come the admins get to know about this behavior.

**Comment by dariomws** [comment]
Hi @I353620,

I tested it and I can find guest users by email address:
![image](https://user-images.githubusercontent.com/33589238/86166757-ad8cfb00-baeb-11ea-984c-5d4eaa29c931.png)
domain.com.ar is an external domain.

**Comment by scanum** [comment]
@I353620 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
