### ISSUE TITLE
Network Testing Companion, links and connectivity test no longer working

### ISSUE THREAD

**Issue by Jax-Ur** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5154]
I ran the Network Testing Companion tool (https://www.powershellgallery.com/packages/NetworkTestingCompanion/1.5.4) in order to troubleshoot networking issues and noticed that the page and tool itself links to pages (http://myadvisor.fasttrack.microsoft.com/) that no longer work and the connectivity test uses entries that no longer resolve (below).

DNS resolution failed for host in trouter2-cus-c.trouter.teams.microsoft.com
DNS resolution failed for host in trouter2-cus-d.trouter.teams.microsoft.com
DNS resolution failed for host in trouter2-easia-c.trouter.teams.microsoft.com
DNS resolution failed for host in trouter2-easia-d.trouter.teams.microsoft.com
DNS resolution failed for host in trouter2-eus2-c.trouter.teams.microsoft.com
DNS resolution failed for host in trouter2-eus2-d.trouter.teams.microsoft.com
DNS resolution failed for host in trouter2-weu-c.trouter.teams.microsoft.com
DNS resolution failed for host in trouter2-weu-d.trouter.teams.microsoft.com

**Comment by scanum** [comment]
@Jax-Ur Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
