### ISSUE TITLE
Edge does not support sending RTC traffic through HTTP Proxy

### ISSUE THREAD

**Issue by naminakao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5156]
According to ICM 178261920, Edge does not support sending RTC traffic through HTTP Proxy.
https://portal.microsofticm.com/imp/v3/incidents/details/178261920/home

Please update the description of Microsoft Edge in Browsers section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#browsers)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@naminakao Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @naminakao, thank you for your feedback and help us to improve docs.microsoft.com.

My apologies but I cannot access the link you are providing.

@LolaJacobsen could you kindly help to confirm this information? Thanks!

**Comment by naminakao** [comment]
Following ICM link (ICM 178261920) is a bug that users unable to join Team Meeting by Edge Browser via Proxy. In this bug, another ICM bug, ICM 159892512 which is reporting same issue is mentioned. In ICM 159892512, Engineering says Spartan edge does not support sending RTC traffic Through HTTP proxy.

ICM 178261920: Online: Unable to join Teams Meeting by Edge Browser via Proxy.
https://portal.microsofticm.com/imp/v3/incidents/details/178261920/home 

ICM 159892512: [S400] Online: No audio on calls/meetings when joining Teams meetings using edge
https://portal.microsofticm.com/imp/v3/incidents/details/159892512/home
![image](https://user-images.githubusercontent.com/34467132/86300303-66168400-bc3d-11ea-821f-0f9c7d724cfb.png)

**Comment by dariomws** [comment]
@naminakao, thanks for this information.

Are you Microsoft employee?

**Comment by scanum** [comment]
@naminakao We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
