### ISSUE TITLE
AllowCloudRecording disabled by default

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5160]
In my and customer tenant this statement is NOT true:
AllowCloudRecording disabled by default

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by tonysmit** [comment]
@ashwinma14 - I think he's right here. Just need to confirm it's set to True by default. Thanks!

**Comment by tonysmit** [comment]
@trudolf-msft - I will make this change. You are correct. I checked in a default build. Thanks for the feedback.
