### ISSUE TITLE
 Microsoft 365 Business Voice link broken

### ISSUE THREAD

**Issue by devlead** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5161]
"Microsoft 365 Business Voice". link on the page is broken
https://www.microsoft.com/microsoft-365/business/business-voice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abae7324-861d-7ca7-7239-a5df8fd927d5
* Version Independent ID: 8a30bd2f-9bc3-a0a8-8b31-d53836ead4d0
* Content: [Microsoft Teams add-on licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=small-business)
* Content Source: [Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@devlead Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @devlead, thank you for your feedback.

All the links in this article are working for me. Could you kindly check the link again?

**Comment by devlead** [comment]
@dariomws still seems broken for me
![image](https://user-images.githubusercontent.com/1647294/86063765-dff71380-ba6b-11ea-8c44-fb339ae244e0.png)
![image](https://user-images.githubusercontent.com/1647294/86063779-e71e2180-ba6b-11ea-90c5-86bb88ec91a5.png)

**Comment by dariomws** [comment]
It's working here:
![image](https://user-images.githubusercontent.com/33589238/86124736-f9bb4980-bab1-11ea-89d0-affa4234772c.png)

I see that you are not being redirected to your language correctly. Maybe you can try clear your browser data.

**Comment by devlead** [comment]
Tried with in-private browser too both FireFox
![BusinessVoice](https://user-images.githubusercontent.com/1647294/86125877-afe85880-badd-11ea-9423-517080bbf764.gif)
and Edge
![BusinessVoiceEdge](https://user-images.githubusercontent.com/1647294/86126064-fd64c580-badd-11ea-9fbf-dde7294ea1f8.gif)

**Comment by dariomws** [comment]
It's true, tried on different browsers and it´s not working. What is not working is language redirection, if you try to access the following URL it works:
https://www.microsoft.com/en-us/microsoft-365/business/business-voice
