### ISSUE TITLE
Audio Conferencing PIN reset URL doesn't work 

### ISSUE THREAD

**Issue by c016smith** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5164]
When going to this URL, we have two options:
1) provided in the meeting invite template, to "Reset PIN" goes to https://mysettings.lync.com/pstnconferencing and this is a bad/dead DNS entry
2) from the documentation here, it says to go to https://admin0m.online.lync.com/lscp/usp/pstnconferencing
which brings me to a blank webpage... I see the Skype for Business favicon, a blue header bar, and at the top-right corner see my first name, "Sign Out" and "Help" but the body/rest of the page is all blank. 

I was able to open the link #2 in a Firefox browser, but blank (as described above) in Microsoft Edge (I'm on Version 83.0.478.45 (Official build) (64-bit) fyi)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401f39f3-f614-6d63-adbd-1ed78ed804f0
* Version Independent ID: 26b45c86-8f6f-8704-d95a-f8c341e569ad
* Content: [Reset the Audio Conferencing PIN in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/reset-the-audio-conferencing-pin-in-teams)
* Content Source: [Teams/reset-the-audio-conferencing-pin-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/reset-the-audio-conferencing-pin-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by tonysmit** [comment]
@ruizoscar - Can you see if Fan can take a look at this issue and offer some feedback to them. Thanks, Tony

**Comment by tonysmit** [comment]
@fafan - Can you take a look at this issue and offer some feedback to them. Thanks, Tony

**Comment by tonysmit** [comment]
Pinged the PM again so we can get the right URL to update this with.

**Comment by tonysmit** [comment]
@c016smith - I myself tested both of the links and both worked. I had other people confirm and it worked for them as well. Clear your browser cache or try Chrome and see what the result is. This is definitely a browser issue. Thanks.
