### ISSUE TITLE
「重要」セクションに追記をお願いします

### ISSUE THREAD

**Issue by shikanem** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5167]
[フィードバックをこちらに入力してください]
重要の記載に下記「　」内に書いた部分を追記いただけますようお願いします。

重要
Microsoft Teams と Business Voiceは、ユーザーのメールボックスがMicrosoft 365にある場合にのみ機能します。オンプレミスのExchange Serverにあるメールボックスはサポートしていません。
「Microsoft365管理センター上では、ユーザーのライセンス割り当てで上述のサブスクリプション以外にもBusiness Voiceを割りあてて機能しますが、これはサポートされないシナリオです。」

＜リクエスト理由＞
Microsoft 365管理センター上では、ユーザーのライセンス割り当てで本来組み合わせとして想定されない組み合わせで割り当てが可能となり、利用できてしまいます。ユーザーのライセンス割り当てには組み合わせをバリデーションをかける実装がありません。
CSPではパートナーがライセンスの再販売をしており、販売時とは異なる、想定しない組み合わせで利用をされてしまい、公式な説明がなされていないので、顧客への説明に困っています。
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 35057f71-792b-a4e2-a2ee-a4908c11f3a4
* Version Independent ID: 7e23f067-1dcd-16f0-3f9a-ff8d13c1f659
* Content: [Microsoft 365 Business Voice とは - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/business-voice/whats-business-voice)
* Content Source: [Teams/business-voice/whats-business-voice.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/business-voice/whats-business-voice.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dstrome** [comment]
hi @shikanem Thanks for your feedback. We're unfortunately not able to implement this suggestion. We do not discuss unsupported scenarios in product documentation as it can have the unintended result of leading customers to try the scenario anyways. Please refer partners and customers to the supported list of subscriptions if there's any question about whether a certain subscription is or isn't supported.

**Comment by shikanem** [comment]
Hi David,
Thank you for your prompt reply.

I’m sorry, this Docs already mentions that it is not supported.
Is there a scenario in which the description below does not support it?
[cid:image001.png@01D64573.55D97AC0]
It is impossible to change the implementation to correctly limit the combinations on the current management portal.
Please note that this document should only be used in supported combinations.

Best regards,
Shinya Kanematsu.
