### ISSUE TITLE
Incorrect Information

### ISSUE THREAD

**Issue by mattb1969** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5168]
HI,
The document doesn’t correctly reflect the icons on the page.

My screen is showing me a green circle with a tick on a black background - similar but not the same.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a162ef5c-3099-7f58-4178-d29e3ec2b5a7
* Version Independent ID: 6ca31e56-052d-6c62-1323-b5aaaae1f04a
* Content: [User presence in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/presence-admins)
* Content Source: [Teams/presence-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/presence-admins.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@mattb1969 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @mattb1969, thank you for your feedback and help us to improve docs.microsoft.com.

I think you see a white or black tick depending on if you are using dark mode or note:
- If you are using dark mode, you will see a black tick on Teams client
- If you are using the white mode, you will see a white tick on Teams client

**Comment by scanum** [comment]
@mattb1969 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
