### ISSUE TITLE
Supported Session Border Controllers - 404 Error

### ISSUE THREAD

**Issue by J0hn-Doe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#517]
When I click on this link, I get a "404 not found" error: 
https://docs.microsoft.com/de-de/SkypeForBusiness/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/plan-direct-routing#supported-session-border-controllers-sbcs
Can you please fix?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d964547-6b38-cc5f-6b2b-7a50a1c7dae9
* Version Independent ID: fa5850f9-1b92-9727-c344-bcffc227cbd6
* Content: [Make Phone System Direct Routing service decisions - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/2-envision-make-my-service-decisions-direct-routing#feedback)
* Content Source: [Teams/2-envision-make-my-service-decisions-direct-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/2-envision-make-my-service-decisions-direct-routing.md)
* Service: **msteams**
* GitHub Login: @rmw2890
* Microsoft Alias: **MyAdvisor**

**Comment by kenwith** [comment]
@J0hn-Doe - thank you for reporting. It is greatly appreciated. This should be fixed now. Please refresh your browser. If you are stilling experiencing the broken link please re-open. Thanks again.
