### ISSUE TITLE
Org-wide teams

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5170]
Furthermore, when office365 automatically adds a new unlicensed mailbox to the org-wide team it will say that a random owner of the team added the user causing much confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@jonwbstr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @jonwbstr, thank you for your feedback and help us to improve docs.microsoft.com.

Could you kindly explain this issue in more detail? What section in the article do you think we should improve?

Thanks!

**Comment by jonwbstr** [comment]
Hello,

The section below talks about the messages appearing in general and should
mention they will appear from a random admin.

Or, the product could be improved to not do that...

**Comment by dariomws** [comment]
@jonwbstr thank you for your feedback.

In the article, I only found this related to unlicensed users:
"When an org-wide team is created, all global admins are added as team owners and all active users are added as team members. Unlicensed users are also added to the team. The first time an unlicensed user signs in to Teams, the user is assigned a Microsoft Teams Commercial Cloud Trial license. To learn more about the trial license, check out Manage the Teams Commercial Cloud Trial offer."

We are here to improve docs.microsoft.com, to request new features or update existing ones please check:
https://microsoftteams.uservoice.com/

**Comment by jonwbstr** [comment]
This has nothing to do with unlicensed users.

When YOU add someone to a team, a log entry appears in the general channel
saying "YOU added new user acme user to the team"

When the system adds a user to an org wide group it also says "YOU added
new user" when YOU did not add the user, the system did. If there are
multiple admins the person attributed to adding the user could be anyone
that is an owner.

Do you understand what I mean now?

**Comment by dariomws** [comment]
> Furthermore, when office365 automatically adds a new unlicensed mailbox to the org-wide team it will say that a random owner of the team added the user causing much confusion.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
> * Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
> * Content: [Create an org-wide team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team)
> * Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
> * Service: **msteams**
> * GitHub Login: @LanaChin
> * Microsoft Alias: **v-lanac**

Ok, yes, understand now, I was confused because you mentioned unlicensed mailboxes in the first comment. Sorry about that. I'll test it.

Remember that to request new features or update existing ones you need to go to:
https://microsoftteams.uservoice.com/

**Comment by dariomws** [comment]
I created a new org-wide team and then created two new users with an E3 license. Then, I can see the message "Admin has added User to the team."

I think that the admin who created the user will appear as the one who added the user to the team. I think it's not relevant information to add to the article, but I'm open to hear you if you insist.

**Comment by scanum** [comment]
@jonwbstr Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
