### ISSUE TITLE
CreateSrsMedia No Support for LTSC

### ISSUE THREAD

**Issue by SOM-Scott** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5171]
CreateSrsMedia.ps1 1.5.1 no longer support Windows 10 Enterprise LTSC even though it is supported https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-lifecycle-support#windows-10-release-support

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/console)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@SOM-Scott Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @SOM-Scott, thank you for your feedback and help us to improve docs.microsoft.com. Sorry for the delay.

@dstrome could you kindly help with this issue? Thanks!

**Comment by dstrome** [comment]
@SOM-Scott I'm afraid I don't understand your issue. Can you restate your concern? Thanks.

Note: If this is feedback about product supportability and not an issue with documentation, please submit feedback at https://microsoftteams.uservoice.com/.

**Comment by SOM-Scott** [comment]
Per https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-lifecycle-support#windows-10-release-support Windows 10 Enterprise LTSB is supported. The script from Step 1 CreateSrsMedia.ps1 https://docs.microsoft.com/en-us/microsoftteams/rooms/console#prepare-the-installation-media no longer supports LTSC media as of version 1.5. Prior versions of the script did support LTSC.

**Comment by dariomws** [comment]
@dstrome could you kindly help with this issue? Thanks!

**Comment by dariomws** [comment]
@dstrome could you kindly help with this issue? Thanks!

**Comment by dariomws** [comment]
@dstrome could you kindly help with this issue? Thanks!

**Comment by dariomws** [comment]
Hi @SOM-Scott, sorry for the delay.

From the article that you are referencing, LTSC is not supported. The following sentence was added 2 years ago:
"Microsoft Teams Rooms requires the  Windows 10 IoT Enterprise or Windows 10 Enterprise SKUs under Semi-Annual Channel servicing options. These other Windows 10 editions aren't supported:

- Windows 10 Enterprise Long-term Servicing Branch (LTSB) / Long Term Servicing Channel (LTSC) editions
- Windows 10 Internet of Things (IoT) Enterprise LTSB / LTSC editions
- any other edition of Windows such as Windows 10 Pro or Home edition"

**Comment by dariomws** [comment]
@scanum I think we can close this issue.
