### ISSUE TITLE
Wrong remark 

### ISSUE THREAD

**Issue by ccoordt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5174]
Hi, 
in this page https://docs.microsoft.com/da-dk/microsoftteams/see-a-list-of-audio-conferencing-numbers-in-teams it says 

Domestic dial-in numbers are dedicated to your organization and are the only ones that can be set as a default phone number. However, international dial-in numbers may be shared across multiple organizations.

that is miss leading and needs to be removed or changed. customers think that if they purchase(new or Port)  an international service number it will be shared with other tenants.

[Angiv feedback her]

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: da255c7a-42a3-32be-25f6-c54a45ff7903
* Version Independent ID: ccb6f5f7-b939-b7ee-2808-cf471d748eab
* Content: [See a list of Audio Conferencing numbers - Microsoft Teams](https://docs.microsoft.com/da-dk/microsoftteams/see-a-list-of-audio-conferencing-numbers-in-teams)
* Content Source: [Teams/see-a-list-of-audio-conferencing-numbers-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/see-a-list-of-audio-conferencing-numbers-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@ccoordt Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@ccoordt Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
