### ISSUE TITLE
Missing explanation for * character

### ISSUE THREAD

**Issue by JustinBarker77** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5175]
Users with Team calling under Connect and Extend has Formal with an asterix, but no explanation of the asterix. Could one be added please explaining the consideration of this feature

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb24d873-4507-3a2f-1d0f-a38a305b8ff5
* Version Independent ID: 6a927fb3-5cc9-91de-b9ce-d057156d3523
* Content: [Teams Contact Center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-contact-center)
* Content Source: [Teams/teams-contact-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-contact-center.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@JustinBarker77 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @JustinBarker77, thank you for your feedback.

@MicrosoftHeidi Could you kindly help with this issue? Thanks!

**Comment by MicrosoftHeidi** [comment]
I've emailed the PM responsible for this area (I hope), and I'm waiting on a response now.

**Comment by MicrosoftHeidi** [comment]
I have a response, the asterisk should be removed.
