### ISSUE TITLE
Clarity around Team archiving

### ISSUE THREAD

**Issue by rick-brown-slalom** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5177]
I would like more clarity around what happens if I archive a team, but do not check the "Make the SharePoint site read-only for team members." Does it delete the site? Leave it as is? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf689b7-a7c1-121f-578e-029e8a89c4f0
* Version Independent ID: 7e6b449e-bd77-2fc4-2c3d-1f2e364e1b76
* Content: [Archive or delete a team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/archive-or-delete-a-team)
* Content Source: [Teams/archive-or-delete-a-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/archive-or-delete-a-team.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@rick-brown-slalom Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
