### ISSUE TITLE
Guest limitation unclear

### ISSUE THREAD

**Issue by StefanPlizga** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5179]
Hello,

On this page, it is stated for guest licensing that "However, the total number of guests that can be added to your tenant is based on what your Azure AD licensing allows - usually 5 guests per licensed user. For more information, see Azure AD B2B collaboration licensing."

However, when looking at the link [Azure AD B2B collaboration licensing](https://docs.microsoft.com/en-us/azure/active-directory/b2b/licensing-guidance), there is actually no restriction nor relationship of the number of guests in the tenant based on the number of licensed users. Azure AD guest licensing is needed when we need to enforce Azure AD paid licenses on the guests, such as MFA. My understanding is that basically, even in a tenant of 1000 users, there could be 250 000 guests with no additonal cost as long as I don't configure MFA or conditional access (or any other paid feature of Azure AD P1 or P2) for these guests.

If my understanding is correct, you might probably delete this sentence as it is creating confusion: "However, the total number of guests that can be added to your tenant is based on what your Azure AD licensing allows - usually 5 guests per licensed user".

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2492e210-08f9-a476-97ec-008926def961
* Version Independent ID: adcb0dd9-4a3c-b665-6e34-ce3276c89b4d
* Content: [Guest access in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/guest-access)
* Content Source: [Teams/guest-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@StefanPlizga Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
