### ISSUE TITLE
This documentation is out of date

### ISSUE THREAD

**Issue by technonath** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5181]
This documentation is out of date, it says "Users who are upgraded to Teams Only cannot communicate with users who are using Skype for Consumer."
I am in teams only mode and I can now communicate with consumer skype users since the rollout.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a2fc46c-d6fb-fd8b-e2aa-fdee7c742230
* Version Independent ID: e0d36a99-2823-68a2-7e97-0c1ba66efd51
* Content: [Teams Only mode considerations - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-only-mode-considerations)
* Content Source: [Teams/teams-only-mode-considerations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-only-mode-considerations.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@technonath Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by technonath** [comment]
you have published my changes now removing the incorrect information.
