### ISSUE TITLE
Tradução pt-br

### ISSUE THREAD

**Issue by walterax** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5182]
A tradução em https://docs.microsoft.com/pt-br/microsoftteams/hardware-requirements-for-the-teams-app, para pt-br não ficou legal: "Requisitos de hardware para o Teams no **Lixus**"

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 29a61ff5-b3a5-158d-149a-dec344060e05
* Version Independent ID: 97fac351-a283-aaa8-cde1-fbd9cf4e8504
* Content: [Requisitos de hardware para o Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/pt-br/microsoftteams/hardware-requirements-for-the-teams-app#feedback)
* Content Source: [Teams/hardware-requirements-for-the-teams-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hardware-requirements-for-the-teams-app.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officeglobal can you help here please? Thanks!

**Comment by PerryWerneck** [comment]
Concordo! O "estagiário" que traduziu pode até ter sua opinião própria mas isso pega mal pra empresa como um todo.

**Comment by OfficeGlobal** [comment]
Working on an update

**Comment by OfficeGlobal** [comment]
@walterax , @scanum the article was HumanTranslated and published live

**Comment by scanum** [comment]
@PerryWerneck Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
