### ISSUE TITLE
Export option for Teams live Event is not available

### ISSUE THREAD

**Issue by abdulrehmanbinaltaf** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5186]
[Export option for Teams live Event is not available ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5372edb-6ffe-34a3-0839-587e48f66f6b
* Version Independent ID: 43903b13-37de-7dde-5b8c-739586cc2d87
* Content: [Microsoft Teams live event usage report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-live-event-usage-report)
* Content Source: [Teams/teams-analytics-and-reports/teams-live-event-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-live-event-usage-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by abdulrehmanbinaltaf** [comment]
@scanum  thanks for the update.
this is not tenant issue, its feature that is not available, Teams admin centre > Analytics & reports > Usage reports > Teams live event usage > Export option is not available for live event, but export option is Available for other report..
![02 (1) JPG](https://user-images.githubusercontent.com/11478250/85261423-cf93d700-b474-11ea-879a-f71cb38ac01b.jpg)
