### ISSUE TITLE
"Create and view meetings in Teams" not possible with Exchange on-premises

### ISSUE THREAD

**Issue by Maxnor** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5189]
We have a current Exchange 2016 environment with O-Auth and all the requirements; the Calendar Button is missing inside the Teams App. 
After working with Microsoft Support  we've received the statment, that it's no longer possible to create meetings inside the Teams App if the mailbox is stored in an on-premises environment. 

So could you please check that and update the table "Actions supported:"
"Create and view meetings in Teams" <> "Exchange On-premises": "NO"

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [Interaktion von Exchange und Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Maxnor** [comment]
@scanum We've had a support ticket for this issue and the outcome was: It doesn't work anymore with on-premises mailboxes. I've asked multiple times and the answer from support remained the same.
