### ISSUE TITLE
example still incorrect

### ISSUE THREAD

**Issue by bigred3142** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#519]
why is issue #278 closed if the example code has not been updated ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbb586e8-9c5d-c4da-a3ac-db93ea727e09
* Version Independent ID: 64df6b50-ba8a-5d6f-2c40-eb2b5307817c
* Content: [Stage AV and OAuth certificates in Skype for Business Server 2015 using -Roll in Set-CsCertificate](https://docs.microsoft.com/en-us/skypeforbusiness/manage/authentication/stage-av-and-oauth-certificates)
* Content Source: [Skype/SfbServer/manage/authentication/stage-av-and-oauth-certificates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/authentication/stage-av-and-oauth-certificates.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by kenwith** [comment]
This issue has been added to the teams backlog internally. We can also leave this open if you prefer and close once the issue is closed on internal backlog system.

**Comment by kenwith** [comment]
This is coming up in sprint plan. When I move the issue into the teams backlog I close it here for housekeeping and a note that they will respond to this thread. Responding re-opens an issue and it is OK to respond anytime to any issue whether it is closed or open. This is in backlog and will be fixed soon.

**Comment by kenwith** [comment]
This should be resolved. If not please re-open.
