### ISSUE TITLE
URL / Hyperlinks are not working in Microsoft Teams Live event

### ISSUE THREAD

**Issue by abdulrehmanbinaltaf** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5190]
i want to highlight one issue
**URL / Hyperlinks are not working in Microsoft Teams Live event**
In Microsoft Teams Live event, if you join the live event from mobile device ie android / iphone.
URL / Hyperlinks are not working
once you click on any URL/link nothing is happening.
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/40621831-url-hyperlinks-are-not-working-in-microsoft-team

![hyperlink are not working](https://user-images.githubusercontent.com/11478250/85261846-7d9f8100-b475-11ea-9514-2764aab55b4e.jpg)

this not related to 1 tenant you can check from your side. i already raise a  [Case #:19935031]

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by abdulrehmanbinaltaf** [comment]
dear this is not the tenant issue, this is app behaviour issue... as i mentioned earlier case is open for more than 2m [Case #:19935031]. have you check from your side functionality, url/links shared during live event is working on mobile device ?
