### ISSUE TITLE
Link to  Law Enforcement Requests Report is not working

### ISSUE THREAD

**Issue by Florian-Mayer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5191]
In Chapter "What third parties have access to personal data?" the link to  Law Enforcement Requests Report is not working

https://www.microsoft.com/about/corporate-responsibility/lerr/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e34f35bb-7d9c-0c7f-a1a1-6fd9fbe93dfa
* Version Independent ID: d123210a-ed20-4b97-3706-33d7887b4c27
* Content: [Microsoft Teams Privacy - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-privacy)
* Content Source: [Teams/teams-privacy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-privacy.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by ndambrosio** [comment]
I've updated the URL, it should be merged once it's approved. https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/5192

**Comment by scanum** [comment]
@Florian-Mayer Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
