### ISSUE TITLE
Additional Technical Details

### ISSUE THREAD

**Issue by vshakyaver** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5194]
[Enter feedback here]
1. Is this available across all clients (iOS, Android, Windows, MacOS)?
2. Does the user need to be authenticated for it to be present?
3. Are there administrative controls to control if this feature is made available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86d4ed41-8d7e-9caa-d6f9-dea2ba149ade
* Version Independent ID: 5dff4476-cde0-ebcf-f831-255905fde53a
* Content: [Raise hand in Teams meetings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/raise-hand-meetings)
* Content Source: [Teams/raise-hand-meetings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/raise-hand-meetings.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Hello @vshakyaver 
1 Yes. Raise your hand is always available in any meeting you join and is supported on all clients except meeting room devices (at the moment).
2. No.
3. A Teams admin doesn't have to create a policy for the feature to appear in a meeting.

**Comment by scanum** [comment]
@vshakyaver  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
