### ISSUE TITLE
Setting Missing in Documentation

### ISSUE THREAD

**Issue by csgithub** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5195]
The setting to enable Dial out from Teams Admin is missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 305a21ef-6e99-3f0d-99a0-990489a93715
* Version Independent ID: 5edc67ee-0d68-50a3-fafd-f764d8762fa5
* Content: [Outbound call restrictions - Audio Conferencing & PSTN calls - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/outbound-calling-restriction-policies)
* Content Source: [Teams/outbound-calling-restriction-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/outbound-calling-restriction-policies.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@csgithub  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @csgithub, thank you for your feedback and help us to improve docs.microsoft.com.

Dial-out is enabled by default when you assign an Audio Conferencing license to the user, and you can restrict it using the steps in this article.

**Comment by scanum** [comment]
@csgithub Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
