### ISSUE TITLE
Add Version number

### ISSUE THREAD

**Issue by hedegaardDK** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5200]
Hi,
Please write version number on the MSI download link, and also please add version number in the details tab of the MSI properties.
Thanks, in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Teams using Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hedegaardDK  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @hedegaardDK, thank you for your feedback.

There are more similar issues. I'll check your feedback internally.

**Comment by dariomws** [comment]
Hi @cichur, could you kindly help here? This is a fairly repeated request. Thank you!

**Comment by dariomws** [comment]
Hi @cichur, could you kindly help here? This is a fairly repeated request. Thank you!

**Comment by hedegaardDK** [comment]
Skype for Business is very soon history...

**Comment by cichur** [comment]
Hi @dariomws and @hedegaardDK ,
I'll foward your request to our installation team.
Thank you, Cindy

**Comment by dariomws** [comment]
Hi @cichur, any update on this? Thanks!

**Comment by cichur** [comment]
...asking again. :-)

**Comment by cichur** [comment]
I received this response from the SME:

**This work in not in plan for this quarter.**
