### ISSUE TITLE
O365 group created in Teams not appearing in Outlook after enabling it to do so

### ISSUE THREAD

**Issue by cclevert** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5202]
I have created a team from the admin center and have successfully run a tenant to tenant document migration. I'd like to import the .pst from the other tenant but it has failed with the error.

![image](https://user-images.githubusercontent.com/55512173/85606728-10c4ec00-b619-11ea-922d-6eae935a4006.png)

I then went to add the mailbox in my Outlook client and in OWA by using the command:
Set-UnifiedGroup -Identity "group" -HiddenFromExchangeClientsEnabled:$false 

That returned:
WARNING: The command completed successfully but no settings of 'group' have been modified

I still dont see the group in either Outlook or Exchange. I also verified that the properties were enabled

get-UnifiedGroup -Identity "group" | Select -Property Name, HiddenFromExchangeClientsEnabled, HiddenFromAddressListsEnabled

Name                                                   HiddenFromExchangeClientsEnabled HiddenFromAddressListsEnabled
----                                                   -------------------------------- -----------------------------
group                            False                         False
---

What else do I need to do in order to view the group and verify that the mailbox exists? 

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d86301b-ce9c-388c-e563-9e5e5c27132e
* Version Independent ID: 07e4ae23-0966-e8f3-9b7c-4f6c02569eb0
* Content: [Microsoft 365 Groups and Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/office-365-groups)
* Content Source: [Teams/Office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-groups.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@cclevert Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
