### ISSUE TITLE
It may be worth mentioning that the '#' (back) key will only go back as far as the most recent auto attendant, once the boundary into a new auto attendant is "crossed" the '#' key will only take you as far back as the newest auto attendant.  Can provide evidence of my conversation with the engineers if you would like more info.

### ISSUE THREAD

**Issue by ZugBug** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5206]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a42f9e2c-aeee-76c4-620a-668cce21ba10
* Version Independent ID: 6ff06eab-9c80-9c30-95ef-c17e157fbea1
* Content: [Set up a Cloud auto attendant - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-auto-attendant)
* Content Source: [Teams/create-a-phone-system-auto-attendant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-auto-attendant.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@ZugBug Thanks for your feedback, we will consider adding this in future editions.
