### ISSUE TITLE
How to View your Outside Guest Access in Desktop App when working from Different Organization

### ISSUE THREAD

**Issue by aheff01** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5207]
I was invited to a different organizations teams page as a guest. In the web portal i can easily change between my organization and the outside organization. However, I can't figure out how to view the outside guest access from my desktop app. Is this possible?

**Comment by scanum** [comment]
@aheff01 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
