### ISSUE TITLE
Example .onmicrosoft.com domain typo

### ISSUE THREAD

**Issue by stefandoh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5211]
Referring to paragraph "Using the "Microsoft Teams admin center"

> In the left navigation, go to Voice > Direct Routing, and then click the SBCs tab.
>  Click Add.
>  Enter a FQDN for the SBC.
>   Make sure the domain name portion of the FQDN matches a domain that's registered in your tenant and keep in mind that the *.onmicrosoft.com domain name isn't supported for the SBC FQDN domain name. For example, if you have two domain names, contoso.com and **contoso.**on.microsoft.com**,** use sbc.contoso.com as the SBC name."

Please update the document to proper "*.onmicrosoft.com" instead of "*.on.microsoft.com" domain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad7d5051-1177-c5cf-bf28-8639d7b6fbd1
* Version Independent ID: 2a9aa4e1-3767-cd46-50fe-f9dd8b0997be
* Content: [Connect your Session Border Controller (SBC) to Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-connect-the-sbc)
* Content Source: [Teams/direct-routing-connect-the-sbc.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-connect-the-sbc.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@stefandoh Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @stefandoh, It was updated/fixed 19 days ago.

Thanks for taking out some time to open the issue. I appreciate and encourage you to do the same in the future also.

**Comment by scanum** [comment]
@stefandoh Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
