### ISSUE TITLE
"Network Testing Companion"

### ISSUE THREAD

**Issue by NickElniff** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5212]
When I search for documentation for the "Network Testing Companion" tool, it returns this page - but there is absolutely no mention of it on this page anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8837c1c-ea62-4ac9-5187-3da28ff2086c
* Version Independent ID: 1ae9e143-9895-521f-a3e4-42c9dd8436c0
* Content: [Use Advisor for Teams (public preview) to help you roll out Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/use-advisor-teams-roll-out)
* Content Source: [Teams/use-advisor-teams-roll-out.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/use-advisor-teams-roll-out.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@NickElniff Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @NickElniff, thank you for your feedback and help us to improve docs.microsoft.com.

Where are you searching for "Network Testing Companion"? Anyway, this tool is being replaced by Microsoft 365 Network Onboarding tool:
https://connectivity.office.com/
This tool uses Network Testing Companion to test SfB/Teams connectivity.

But you can still download it:
https://www.powershellgallery.com/packages/NetworkTestingCompanion/1.5.4

**Comment by scanum** [comment]
@NickElniff Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
