### ISSUE TITLE
Typo/Error

### ISSUE THREAD

**Issue by copywritepaste** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5215]
https://docs.microsoft.com/en-us/microsoftteams/cloud-recording#prerequisites-for-teams-cloud-meeting-recording

The last item in this bulleted list has an error. 

 "To enable transcription for user's meeting, the Teams meeting policy they are assigned to must have Allow Transcription setting must be set to true." should read "To enable transcription for a user's meeting, the Teams meeting policy they are assigned to must have the Allow Transcription setting set to true."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@copywritepaste  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tonysmit** [comment]
@scanum - I made the required changes here and committed them to Live by mistake. They should have been made in master or a working branch. Apologies. You can see my changes. Can you please verify that my changes get published please? Thanks, Tony
