### ISSUE TITLE
Update Page for new 4.4 version of Rooms

### ISSUE THREAD

**Issue by trecee13** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5216]
1909 | 2019-11-12 | Validation complete,No known issues. | Coming soon | 18363.418
-- | -- | -- | -- | --

Windows IOT Teams Rooms is already updatnig to 1909, the version should be listed as it breaks if you are not on 4.4, please update page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ecd6ee6-8850-f346-5684-9c5d2444789f
* Version Independent ID: a55a7a01-211d-147a-5332-b68e1051a2a1
* Content: [Version Support - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-lifecycle-support)
* Content Source: [Teams/rooms/rooms-lifecycle-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-lifecycle-support.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@trecee13  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @trecee13, this article was updated yesterday:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/5380

Thanks for taking out some time to open the issue. I appreciate and encourage you to do the same in the future also.

**Comment by scanum** [comment]
@trecee13 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
