### ISSUE TITLE
Skype Online Connection Module requires newer Version

### ISSUE THREAD

**Issue by bnicho02** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#522]
The newest version of Skype Online Connection Module now requires PowerShell 5.1 to be installed in order to run.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3117c408-39c5-df82-7238-3e842e953a64
* Version Independent ID: 80a85e4e-a1b3-68a7-bb9c-544925bcb3ef
* Content: [Set up your computer for Windows PowerShell](https://docs.microsoft.com/en-us/SkypeForBusiness/set-up-your-computer-for-windows-powershell/set-up-your-computer-for-windows-powershell)
* Content Source: [Skype/SfbOnline/set-up-your-computer-for-windows-powershell/set-up-your-computer-for-windows-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-your-computer-for-windows-powershell/set-up-your-computer-for-windows-powershell.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@bnicho02 - thank you for taking the time to provide feedback. I am getting this confirmed and updated. Thanks again, appreciated!

**Comment by kenwith** [comment]
Sorry for long delay. I was able to get this into the backlog for the Skype team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by c016smith** [comment]
Will this be supported through the Azure Cloudshell powershell module?

**Comment by kenwith** [comment]
@c016smith - I found a User Voice with this idea too and upvoted it: https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/32344114-add-cloudshell-like-azure-portal-has-with-all-of

**Comment by kenwith** [comment]
@bnicho02 - I am confirming with support as there might even be new requirements now. Not sure how this slipped through the cracks but I am following up on it now. Sorry for the delay and will keep this open until I get that page mentioned updated.

**Comment by scanum** [comment]
@kenwith Any updates on this issue? Thanks!

**Comment by kenwith** [comment]
@scanum - yes, the article now has download to PowerShell 5.1. This can be closed now. Thanks for follow up!

**Comment by scanum** [comment]
@bnicho02  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

@officedocsbot close
