### ISSUE TITLE
Billing of unused phone numbers MS Teams Admin

### ISSUE THREAD

**Issue by TomasAEVI** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5220]
Hi,
since i can't find good answer on the internet i'll try ask here.
How is it with billing of unused numbers in MS Teams under Voice section?
We have a few numbers unused and we wonder if it's billed as ordinary as someone is using it OR it is not billed or half billed?
Thank you

Best regards,
Tomas

**Comment by scanum** [comment]
@TomasAEVI Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
