### ISSUE TITLE
Dial-out behavior of organizer vs participant

### ISSUE THREAD

**Issue by mcantin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5222]
Let's be more specific here. It has been confirmed by MSFT Support that disabling "dial-out" on an individual user (let's say Jake) will disable the meeting pane for everyone in a meeting Jake hosts. Whenever Jake clicks 'Phone Audio' before a meeting, he will receive an error saying 'Phone Audio isn't available. Unmute your mic for meeting audio'. Jake will be able to dial-out as a participant for meetings, hosted by individuals with dial-out enabled, through the meeting pane once inside the meeting, but not before.

This article doesn't clarify that, but in my opinion, it should.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b759f354-bf74-3cff-0c96-3b28a27ee997
* Version Independent ID: fb2d8a68-f35a-bbee-a306-72ee20a450a3
* Content: [Set up the Call me feature for your users - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/set-up-the-call-me-feature-for-your-users)
* Content Source: [Teams/set-up-the-call-me-feature-for-your-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-the-call-me-feature-for-your-users.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@mcantin  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @mcantin, thank you for your feedback and help us to improve docs.microsoft.com.

I'm currently investigating this, I'll give you more information in the next couple of days.

**Comment by dariomws** [comment]
Hi @mcantin, sorry for the delay.

I've verified, and if the meeting organizer is not enabled for dial-out, the **Phone audio** option won't be available for everyone in the "Choose your video and audio options" screen. So you won't be able even to get the **Call me** option.

If the meeting organizer is enabled for dial-out, the **Phone audio** option will be available for everyone in the "Choose your video and audio options" screen. So you can get the **Call me** option.

I'll update the article based on this information.

Thank you!
