### ISSUE TITLE
Documented features are incorrect. 

### ISSUE THREAD

**Issue by Eric2XU** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5223]
Discovery options are not deployed and support tells me its not even starting till Q4 of 2020. This created tickets for users asking where the feature was. This document needs to be updated to reflect that this is an upcoming feature that is not yet released. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5920152-5fee-41ed-56df-ad7b51b25cc2
* Version Independent ID: 88cfc850-5e36-48ee-ba99-088b2b653f1e
* Content: [Manage discovery of private teams in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-discovery-of-private-teams)
* Content Source: [Teams/manage-discovery-of-private-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-discovery-of-private-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Eric2XU  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Eric2XU, thank you for your feedback.

At the top of the article, the following note was added 13 months ago: "This is a preview or early release feature". But maybe I'm missing something, please let me know if I'm wrong.

Thanks!

**Comment by Eric2XU** [comment]
That is the smallest text ever. While I am thankful its bold I can tell you that I the Teams Admin, others on my team, and two of my end users didnt see it. It failed to do what was there for which was inform the reader. I would suggest you make that one of those purple note boxes to grab the attention required. 

Also I know its a doc side issue but shame on MS DEV Teams Team for having a preview feature that never rolled out in over a year. This page honestly should be taken down as to my knowledge no one has this preview. Teams doesnt have an opt in preview ability so no one has this. Its just misleading and found by google for those looking to set this. But sidebaring that, simply making that a big purple note box would be enough.

**Comment by dariomws** [comment]
Thanks for your comment @Eric2XU, if you give me your consent again I'll create a pull request with your suggestion to see if it's approved, but to be honest, I'm not fully convinced about this update as I think the preview message is clearly stated:
![image](https://user-images.githubusercontent.com/33589238/88690829-730a8400-d0d2-11ea-91a4-f40e673734a4.png)

**Comment by Eric2XU** [comment]
Sure, consent granted. Yeah I guess it comes down to opinion then. I find "**This is a preview or early release feature**" to be misleading as its not. No one actually has these features and preview/ER features don't take over a year to progress. Now if you said "this is an unreleased upcoming feature" that might be a little more specific. Also its simply not prominent enough. I didn't catch nor did another IT person and two end users. Big purple notes box wont hurt anything and might save some people from having to open support tickets just to find out its not released yet. Oh actually, Microsoft support also missed the preview statement it was so small. Also everything these days is in preview, its just something people say, it doesn't have the same brevity it used to.

**Comment by LanaChin** [comment]
@Eric2XU - thanks for your input. Effective August 31, 2020, this feature will be disabled. We're updating the article with a blue "Important" note at the top to reflect this.  After August 31, 2020, private teams can longer be set to be discoverable and all existing and new private teams will no longer be discoverable.

**Comment by Eric2XU** [comment]
Wow thats a big move for MS. I hope in this upcoming change they will figure out how to discover private channels (so they can ask for access). Hopefully while they are not moving in this direction they are moving in another direction. Having so many moving from Slack right now people are looking for the channel (Team) directory. Its one of the largest design concepts about teams that isn't mature yet given how useless left side navigation is with too many teams. Once your in a team all is well but there is still more work to getting into a team and listing them all. Hopefully what you have said isnt exactly right and there is simply another method for channel directory upcoming. I thought the ideas listed in this doc were a right step I wonder what destroyed it.
