### ISSUE TITLE
Clarification on "chats retained forever" 

### ISSUE THREAD

**Issue by CarissaB117** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5224]
In only this one paragraph it mentions that if a user deletes their sent messages and then most of the article is about what happens when there are retention policies: "By default, Teams chat, channel, and files data are retained indefinitely, unless there is an attempt to delete the content via retention policies, user deletes, admin deletes etc."

If there aren't retention policies, can someone confirm that if messages are deleted they are actually deleted? Do they go to the "substrates" folder like other messages for a period of time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f55c52a5-5841-b9c9-1607-2013dc3f2e20
* Version Independent ID: 16d93458-5e01-646f-dac5-31306cc7f3fb
* Content: [Retention policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/retention-policies)
* Content Source: [Teams/retention-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/retention-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **anwara**

**Comment by scanum** [comment]
@CarissaB117  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @CarissaB117, thank you for your feedback and help us to improve docs.microsoft.com.

In Microsoft Teams, if a user deletes either a message in a channel or in a chat, it can be undone if you regret it immediately:
![image](https://user-images.githubusercontent.com/33589238/88460055-d5b01580-ce6f-11ea-87d9-d4d4b27b6722.png)

After the Undo action disappears, you cannot recover it in/to Teams but it's stored/retained in the Team's Exchange Online mailbox (Office 365 Substrate).

For Teams chat and channel messages, a copy (that the Teams clients work off of) is stored in the Azure powered chat service and a separate copy is stored (archived) in Exchange online mailboxes (both user and group). 
' A chat message or IM in a 1x1 chat or a group chat is ingested into a hidden folder (TeamChat) into the EXO mailbox of each user who is a participant in the 1xN chat (n= 1,2,3 … )
' A channel message in a Team\channel is ingested into a hidden folder (TeamChat) into the EXO mailbox of the Office 365 Group representing the Team.

More information:
https://techcommunity.microsoft.com/t5/microsoft-teams-blog/retention-policies-for-microsoft-teams/ba-p/178011
https://techcommunity.microsoft.com/t5/microsoft-teams-blog/top-features-of-microsoft-teams-amp-information-protection-in/ba-p/63046

**Comment by scanum** [comment]
@CarissaB117 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
