### ISSUE TITLE
small business has option to add license individually as add-on 

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5225]
We can add Audio conferencing, Phone system and calling plan for Microsoft small business.  I have seen lot of customer adding it individually with  small business plan.

They have option to purchase subscription as standalone . Please update this article it is not mandate we have to go for business voice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abae7324-861d-7ca7-7239-a5df8fd927d5
* Version Independent ID: 8a30bd2f-9bc3-a0a8-8b31-d53836ead4d0
* Content: [Microsoft Teams add-on licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=small-business)
* Content Source: [Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@robinpoulose1  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @robinpoulose1, thank you for your feedback and help us to improve docs.microsoft.com.

I have a tenant with only Business licenses, and these are the add-ons I have available:
![image](https://user-images.githubusercontent.com/33589238/88459075-d3968880-ce68-11ea-95a7-2691d6778678.png)
![image](https://user-images.githubusercontent.com/33589238/88459079-dabd9680-ce68-11ea-993d-23e6ad945511.png)

As you can see, Audio Conferencing is available but no Phone System or Calling Plans. And you can see the following note in the article:
"If you're a small or medium-sized business who has a Microsoft 365 Enterprise plan, you can still buy add-on licenses for these voice features, however, we recommend that you consider a Microsoft 365 Business plan and Business Voice."

I'll update Audio Conferencing row accordingly.
