### ISSUE TITLE
information not updated

### ISSUE THREAD

**Issue by iamnirajpandey** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5231]
Hello Team,

As per this [article](https://techcommunity.microsoft.com/t5/microsoft-teams/microsoft-increases-teams-membership-to-10-000-users/m-p/1263810) the team member limitation is raised to 10K but it seems it is not updated over here.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@iamnirajpandey  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @iamnirajpandey, thank you for your feedback and help us to improve docs.microsoft.com.

The value in the table about the number of members in a team was updated on May 14:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/b758b83cfc331f33affd91171ebeb908b31a666c

**Comment by scanum** [comment]
@iamnirajpandey Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
