### ISSUE TITLE
Prerequisites for Teams cloud meeting recording

### ISSUE THREAD

**Issue by Gary620** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5232]
For the prerequisites part, please check the "!important" part.
![image](https://user-images.githubusercontent.com/67570164/85970701-d46d0380-b9fd-11ea-9061-f24034a23cf6.png)
It is saying that:
"Users won't need a Microsoft Stream license assigned if you want users to only record and download the recordings. This will mean that the recordings aren't stored in Microsoft Stream but are instead stored in Azure Media Services (AMS) with a 21-day limit before it's deleted."

We were doing recording successfully without enabling Stream license in the past. However, currently we cannot record it. We opened a case and the tech support said it is a must to enable Stream license for the Teams meeting recording.

If this is true, would you please modify the document to avoid customer's misunderstanding?

In addition, there's another sentence in the same article, which says:
![image](https://user-images.githubusercontent.com/67570164/85971022-afc55b80-b9fe-11ea-8102-af30b5d8bacd.png)

“Currently, the meeting recording feature is turned off for customers whose Teams data is stored in-country if Microsoft Stream isn't available in the in-country data residency region where the data is stored.”
The support engineer said that it means we have to enable Stream license so that we can record Teams meeting. But I really don't think it is saying the same thing. This statement is confusing, would you please check it and make it more clear?

Thank you so much.

**Comment by scanum** [comment]
@Gary620  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Gary620** [comment]
@scanum  Thank you Manuela, may I know the current status now?

**Comment by Gary620** [comment]
@scanum Good day. Would you please let me know if there's any update? it's been more than a week. Thank you

**Comment by Gary620** [comment]
Is there anybody who can help on this? It's been 2 weeks.

Thank you.

**Comment by dariomws** [comment]
Hi @Gary620, thank you for your feedback and help us to improve docs.microsoft.com.

@tonysmit @garycentric could you kindly help to confirm this information? If you don't have a Stream license, where are the recordings stored?

Besides, about the second paragraph, I understand that recording is turned off if the Stream data is not available in the same region where the Teams data is stored:
https://docs.microsoft.com/stream/faq#which-regions-does-microsoft-stream-host-my-data-in
What do you think?

Thank you!

**Comment by Gary620** [comment]
@dariomws Thank you Dario.

I agreed about the explanation about the second part.
For the first part, would you please let me know when it will be modified?

Thank you

**Comment by dariomws** [comment]
@tonysmit @garycentric could you kindly help to confirm this information? If you don't have a Stream license, where are the recordings stored?

**Comment by tonysmit** [comment]
The recording are stored in AMS like it says. Adding @SamChung-MS to clarify.

**Comment by SamChung-MS** [comment]
I believe I responded in a different thread. Stream is not required. If recording isn't working for you, then it's most likely disabled by your admin.

**Comment by scanum** [comment]
@Gary620  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
