### ISSUE TITLE
Pay per min 

### ISSUE THREAD

**Issue by jdanner89** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5238]
[Enter feedback here]

There needs to be a note that states pay per min comm credits work the same way as the subscription.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad4b757-bff7-5fbc-9490-2eeadb9f7039
* Version Independent ID: e1b15411-ce16-41da-aec5-fc06844673c2
* Content: [How many phone numbers can you get? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/how-many-phone-numbers-can-you-get)
* Content Source: [Teams/how-many-phone-numbers-can-you-get.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/how-many-phone-numbers-can-you-get.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@jdanner89  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @jdanner89, thank you for your feedback and help us to improve docs.microsoft.com.

Sorry but I don't understand. This article is related to the number of phone numbers that you can have available in your tenant, it's not related to minutes available.

**Comment by scanum** [comment]
@jdanner89 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
