### ISSUE TITLE
Calendar Delegation Exchange Server

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5240]
[Section 2](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact#requirements-to-get-the-most-out-of-microsoft-teams), para 1, bullet 4: "To let Microsoft Teams work with Exchange on-premises...".

It is not clear from this whether the OAuth configuration is all that is required, or whether this assumes that external client access to EWS is already enabled. When building a hybrid, the "modern" hybrid with the hybrid agent seems to be not sufficient to allow Teams access to the on-premises calendar. If that is the case, is it also true that it is not sufficient to allow delegate access? 

Obviously the delegate access in Outlook for Exchange on-premises is already working. The only bit they can't do is to add the Teams meeting URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@Air-Git  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Air-Git, thank you again for your valuable feedback.

I'm working on the "How Exchange and Microsoft Teams interact" article with some colleagues as I commented on the following issues:
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2132
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5399

**Comment by dariomws** [comment]
@scanum this issue can be closed, it was addressed in the following PR:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/5645

@Air-Git thank you again for your feedback and contributing to docs.microsoft.com.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
