### ISSUE TITLE
Need more than just Teams license for planner to be visible

### ISSUE THREAD

**Issue by J-Fedor** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5242]
"If Teams Advisor is missing under Planning in the Teams admin center, it means the user isn't licensed for Teams. This behavior will change in the future."

However, we had the user licensed for Teams, but only Teams.  However, that wasn't sufficient.  Waited several days to see if it just took time, never worked.

Ended up assigning the full Office 365 E3 license vs just the Teams component of it, then it worked fine.  So, you need more than just "Teams" in order for it to show up.  Would be good to know what the real minimum is.

Thanks.

[sorry, I say "planner' in subject, but it is 'advisor', but it won't let me edit the subject]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8837c1c-ea62-4ac9-5187-3da28ff2086c
* Version Independent ID: 1ae9e143-9895-521f-a3e4-42c9dd8436c0
* Content: [Use Advisor for Teams (public preview) to help you roll out Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/use-advisor-teams-roll-out)
* Content Source: [Teams/use-advisor-teams-roll-out.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/use-advisor-teams-roll-out.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@J-Fedor  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@J-Fedor Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by J-Fedor** [comment]
I’m not going to be opening a ticket and wasting my time, but you should fix the documentation to be accurate as to the actual minimum requirement.


John Fedor
Principal Architect
Direct:
Support Desk
630.592.6240
630.592.6260
visit peters.com today!
​Stay up-to-date and follow us on social media!
Protect your employees and devices as they return to work wherever they are, learn how to HERE.
The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and privileged material
​Unauthorized review, use, disclosure, or distribution is prohibited.
​If you receive this material/information in error, please contact the sender and destroy the material/information.
