### ISSUE TITLE
3 plans, not 2

### ISSUE THREAD

**Issue by J-Fedor** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5243]
"While Advisor for Teams is in public preview, we're providing the following two plans:"
then you have 3 items listed below it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8837c1c-ea62-4ac9-5187-3da28ff2086c
* Version Independent ID: 1ae9e143-9895-521f-a3e4-42c9dd8436c0
* Content: [Use Advisor for Teams (public preview) to help you roll out Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/use-advisor-teams-roll-out)
* Content Source: [Teams/use-advisor-teams-roll-out.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/use-advisor-teams-roll-out.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@J-Fedor  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@J-Fedor Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
