### ISSUE TITLE
Anonymous Participants DO NOT have access to chat - error in Chat line of table

### ISSUE THREAD

**Issue by SimonJHudson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5244]
The section on Anonymous participants states:
"The anonymous participant is like an external user, but their identity is not projected into the meeting. At join time, they manually enter a nickname." then goes on to show a table where the Chat capability |In-Meeting shows as Yes.

This is incorrect. Currently Anonymous Participants _do not_ have access to chat.

Please confirm whether this is on the roadmap and correct this page pending anonymous chat becoming available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 796af7ec-c373-ee61-d23b-90d86fccef3a
* Version Independent ID: 9c2a27ed-62ad-9407-63ba-a4d33514e430
* Content: [Presenter and participant capabilities in a Teams meeting - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/roles-in-meetings)
* Content Source: [Teams/roles-in-meetings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/roles-in-meetings.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@SimonJHudson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by cichur** [comment]
Hi,
Thank you for your feedback. We have temporarily removed the article pending more edits. Cindy

**Comment by scanum** [comment]
@SimonJHudson Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
