### ISSUE TITLE
Assign Teams meeting policies to AD groups

### ISSUE THREAD

**Issue by gmercyutech** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5246]
Want to assign Teams meeting policies to AD groups. Need tenant enabled for private preview. https://docs.microsoft.com/en-us/powershell/module/teams/new-csgrouppolicyassignment?view=teams-ps

Is this correct?

Mike Siravo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5720e37-e8dd-1e3e-ccfa-cf4db31e8cff
* Version Independent ID: 93a36eb2-3554-0e86-e787-759eaaafe5e1
* Content: [Install the pre-release version of the Teams PowerShell module - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/install-prerelease-teams-powershell-module)
* Content Source: [Teams/install-prerelease-teams-powershell-module.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/install-prerelease-teams-powershell-module.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by gmercyutech** [comment]
![new-cs error](https://user-images.githubusercontent.com/3801028/86159265-0c487980-bad8-11ea-8d9d-e3206a9930c8.JPG)

**Comment by scanum** [comment]
@gmercyutech Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by gmercyutech** [comment]
![image](https://user-images.githubusercontent.com/3801028/86936569-2dc6e800-c10c-11ea-9f49-0a4e6bbd84f5.png)

**Comment by brandber** [comment]
Hi @gmercyutech! 

Thanks for your feedback! 

The Group Policy Assignment cmdlets are now part of the GA build (preview not required). However, the error you are showing is because you are using PowerShell 5.1 and a newer version of PowerShellGet is required to support the AllowPrerelease flag, which is covered on the[ Teams PowerShell installation](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-install) page.

Thanks again and please keep the feedback coming!
