### ISSUE TITLE
User cannot answer an inbound call on iPhone, if phone is locked.

### ISSUE THREAD

**Issue by MSTejas** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5252]
This is a known issue and is being worked upon under VSO 914860.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bef5b5fd-5a4e-7957-f23c-724764a7cb4c
* Version Independent ID: 5fe6c3ab-774b-db2f-5b55-9170bdfe5faf
* Content: [Known issues - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/known-issues)
* Content Source: [Teams/rooms/known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/known-issues.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officedocspr Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by MSTejas** [comment]
There is no need to open ticket from tenant This is a known issue and is being worked upon by Teams PG. This issue needs to be added to this article.

**Comment by MSTejas** [comment]
Please reopen this. This is a known issue, and is worked upon by Teams PG. we need this issue to be added to the known issues article.


Thank you,
Tejas Haria
