### ISSUE TITLE
Is this page the only documentation on Managed meeting rooms?

### ISSUE THREAD

**Issue by white-tim** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5254]
Or are there additional documents i should be looking at?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f76bc0c-a899-b572-588a-b86acae1b740
* Version Independent ID: 3c5b6414-c796-7e50-9e03-b578c7995071
* Content: [Managed Meeting Rooms in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/managed-meeting-rooms)
* Content Source: [Teams/rooms/managed-meeting-rooms.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/managed-meeting-rooms.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@white-tim Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
