### ISSUE TITLE
Requirements for Mac need update or clarification

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5256]
Hello

We could not get the add-in to work on Mac. After working with Premier Support we got information that for Mac Add in to work there is a need to have OAuth configured between local Exchange and Office 365 as well as there are requirements regarding matching the UPN, user sign-ing info to Teams and Office apps and e-mail address of the user. Can you please verify this information with the product owners and update the documentaiton if needed to make sure all prerequisites are included?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Use the Microsoft Teams Meeting add-in in Outlook - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Larryngolog** [comment]
Hello @scanum as I mentioned I have already opened the ticket with Microsoft's premier support and I have provided information what was the outcome - there is a need to have OAuth configured between local Exchange and Office 365 as well as there are requirements regarding matching the UPN, user sign-ing info to Teams and Office apps and e-mail address of the user.
