### ISSUE TITLE
MembershipType switch does not seem to be a valid option

### ISSUE THREAD

**Issue by harp365** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5257]
Hi,

The MembershipType switch does not seem to be a valid parameter. I have ensured that I have the latest released version of the MicrosoftTeams module installed, 1.0.7 however every time I just get:

Get-TeamChannel : A parameter cannot be found that matches parameter name 'MembershipType'

Interestingly the parameter does show in the examples section of help against the Get-TeamChannel cmdlet.

So not sure if this could ultimately do with being raised with the team that look after the PowerShell module, could only find a repo for the documentation side of it.

However in the meantime, where the documentation mentions ensuring the latest version of the module is installed, if it could either confirm a version where this parameter does work or until such a time that it works, provide an alternative or remove.

Thanks

Henry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5346de0f-d09a-86ce-8390-5a33d8139bfb
* Version Independent ID: 5052193b-fd71-d1fe-e64c-f2c47218531c
* Content: [Use Content Search in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/content-search#content-search-of-private-channels)
* Content Source: [Teams/content-search.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/content-search.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by SerdarSoysal** [comment]
@anwara-ms can you pls take a look at this and comment?

**Comment by anwara-ms** [comment]
sorry for the delay, this got lost in my mailbox. This is not related to compliance. Can you please check with Raja Mohan?

**Comment by rajamohan-msft** [comment]
Folks,

Can you please give me context of what is this thread and what is the action expected ?
