### ISSUE TITLE
This page could use more details

### ISSUE THREAD

**Issue by swallbridge** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5260]
Providing an estimate of how much time it takes for guest information to be updated would be valuable. Even a range, such as 2-24 hours to set expectations as these changes are definitely not instantaneous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 941e0612-7854-9538-405c-8a8794b4cc04
* Version Independent ID: 9460ce27-6f84-ac04-cdf4-176faa1bb4bb
* Content: [Edit guest user information - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/edit-guests-information)
* Content Source: [Teams/edit-guests-information.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/edit-guests-information.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@swallbridge Thanks for the suggestion, we will consider adding this in the next update. Thanks.
