### ISSUE TITLE
Promotion ended

### ISSUE THREAD

**Issue by drbree82** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5261]
Rhipe International https://www.rhipe.com/ told me this promo is now ended. If so, the article should be unpublished. Referring to promo at https://docs.microsoft.com/en-us/microsoftteams/e1-trial-license

**Comment by scanum** [comment]
@drbree82  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@drbree82 thank you for pointing this out and helping improve MS Docs. I see the article has been updated in the interim and updated the information.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@drbree82 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
