### ISSUE TITLE
CSP and M365 customers

### ISSUE THREAD

**Issue by OffColour** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5264]
Why isn't this availble to CSP customers with M365 licences? You've effectively stopped us being able to give you money and forced us to to use something other than teams for audio conferencing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fac515b-9c6b-c70c-330e-53557dc23fd2
* Version Independent ID: d515841e-f412-286d-1a97-30507bb50040
* Content: [Audio Conferencing pay-per-minute - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-pay-per-minute)
* Content Source: [Teams/audio-conferencing-pay-per-minute.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-pay-per-minute.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@OffColour Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by OffColour** [comment]
Hi,
It would be useful to explicitly state that this licence is not available for M365 customer who have bought via a CSP. I wasted a lot of time with both our CSP and Microsoft to get to this.
