### ISSUE TITLE
RenderLoopbackSignalLevel and RenderNoiseLevel missing 

### ISSUE THREAD

**Issue by jadoming** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#527]
RenderLoopbackSignalLevel and RenderNoiseLevel objects missing in this table

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c987cbc-12b5-9fcf-8639-368d5c0ad8f2
* Version Independent ID: 16413349-77b6-953e-1486-f935f077df4d
* Content: [AudioSignal table](https://docs.microsoft.com/en-us/skypeforbusiness/schema-reference/quality-of-experience-qoe-database-schema/audiosignal)
* Content Source: [Skype/SfbServer/schema-reference/quality-of-experience-qoe-database-schema/audiosignal.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/schema-reference/quality-of-experience-qoe-database-schema/audiosignal.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by kenwith** [comment]
@jadoming - thank you for taking the time to report the missing objects. Would you be willing to submit a Pull Request with these objects and then I can hunt down someone that can approve it? Instructions for making edits and submitting a Pull Request can be found in the README that shows up at the bottom of the main repo here: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness

**Comment by kenwith** [comment]
@srsriniv can help with this one. Thanks @jadoming for reporting and sorry for the long delay!

**Comment by kenwith** [comment]
@srsriniv - thanks! Merged the PR that adds these. Much appreciated all! https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/630
