### ISSUE TITLE
Could we help with the translation?

### ISSUE THREAD

**Issue by rafagranado** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5273]
The automatic translation for this page is not very good. Could we help translate it?

[Insira comentários aqui]

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Criar uma equipe englobando toda a organização no Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/pt-br/microsoftteams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officeglobal Could you please aid with this issue? Thanks!

**Comment by scanum** [comment]
@rafagranado  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by OfficeGlobal** [comment]
Working on an update

**Comment by OfficeGlobal** [comment]
@rafagranado , @scanum the article was HumanTranslated and published live

**Comment by scanum** [comment]
@rafagranado Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
