### ISSUE TITLE
Which version?!?!?!?!!

### ISSUE THREAD

**Issue by bradrush** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5275]
The documentation states: A specific version of Windows 10 is required, and this version is only available to volume licensing customers. You can get a copy from the Volume Licensing Service Center.

Which version!?!?!?!!?!?!?!!?!!?!!?!!?!?!!!?!!?!?!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/console)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@bradrush  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @bradrush, thanks for your feedback.

You can find the required version here:
https://docs.microsoft.com/microsoftteams/rooms/requirements#required-software-downloads
This link is mentioned in the first lines of this article. Please, read it in detail before start installing Windows 10 and the Microsoft Teams Rooms console app.

Thank you again!

**Comment by scanum** [comment]
@bradrush Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
