### ISSUE TITLE
Presence settings when migrating to Teams only

### ISSUE THREAD

**Issue by RaviSyntax** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5278]
Hi,

I recently changed from Islands to Teams mode.
My users have stopped using Skype for Business and as such the SfB desktop app is no longer used.
As expected, presence info no longer shows in Outlook.

Is the Teams setting below not meant to be ticked automatically once the tenant is in Teams mode only?

Register Teams as the chat app for Office (requires restarting Office applications)

Thanks
Ravi

**Comment by scanum** [comment]
@RaviSyntax Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
