### ISSUE TITLE
SharePoint designer does not work on SharePoint site that comes with a new MS Team.

### ISSUE THREAD

**Issue by EloquentData** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#528]
See title; is this by design, or a known issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by kenwith** [comment]
@EloquentData - I am not sure on this but I want to make sure you get this answered ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by Turismon** [comment]
Make sure you explicitly add yourself as a site collection admin to the site created by teams via powershell using 
Set-SPOUser
   -IsSiteCollectionAdmin <Boolean>
   -LoginName <String>
   -Site <SpoSitePipeBind>. 
If this doesn't work, it might be related to having to reverse the "HiddenFromExchangeClientsEnabled" to false. But usually having explicit site collection admin will allow you to edit those sites.

**Comment by cyrusmileyy** [comment]
It is an extraordinary activity and chance to work for a pioneer in the field, pick up involvement, all around regarded looks great on continue, decent offices, free drinks, cafeteria, notwithstanding, it is extended periods, legislative issues (likewise with most organizations), difficult to get advanced except if you have somebody higher up at https://writemyessayguru.com in the organization,

**Comment by kenwith** [comment]
@Turismon - thanks for info. Closing this out but if something still needs addressed please re-open.
