### ISSUE TITLE
Please correct the team limit

### ISSUE THREAD

**Issue by Sanjeev017** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5283]
[Enter feedback here]

Please correct the teams limit which seems to be 5k for now, the document shows a team can have 10 k members
Number of members in a team | 10,000
Number of members in an org-wide team | 5,000

In case a regular team can have 10k members then Org-wide team should also support 10k members

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Sanjeev017  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Sanjeev017 thank you for reaching out and helping improve MS Docs. The article is reading correctly and has been recently updated to 10,000 which is correct. See https://techcommunity.microsoft.com/t5/microsoft-teams-blog/what-s-new-in-microsoft-teams-3rd-anniversary-edition/ba-p/1234871

**Comment by scanum** [comment]
@Sanjeev017 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
