### ISSUE TITLE
Formatting or sample row

### ISSUE THREAD

**Issue by bubbletroubles** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5284]
Under the heading "Endpoint data file" the document the "Sample Row" isn't formatted as a table or code

Sample row:

`1409W3534, 123 manufacturer, Fabrikam Model 123, Laptop, IT designated 2018 Laptop, Asset Tag 5678, Purchase 2018

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb8d8b48-561b-6817-1ce0-4b2aedc261a8
* Version Independent ID: dfd5cf4a-509a-3ed1-0267-6281c251fbef
* Content: [Turn on and use Call Quality Dashboard - Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/turning-on-and-using-call-quality-dashboard#upload-tenant-data-information)
* Content Source: [Teams/turning-on-and-using-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/turning-on-and-using-call-quality-dashboard.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@bubbletroubles  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@bubbletroubles thank you for reaching out and helping improve MS Docs. I think the document has been updated in the interim as I'm not seeing that. Please could you check and let me know. Thanks.

**Comment by scanum** [comment]
@bubbletroubles Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
