### ISSUE TITLE
MTR Manual App update command incorrect

### ISSUE THREAD

**Issue by nachapman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5285]
The powershell command for updating the MTR app does not work.

Add-AppxPackage -Update -ForceApplicationShutdown -Path '\\<share>\$oem$\$1\Rigel\x64\Ship\AppPackages\*\*.appx' -DependencyPath (Get-ChildItem '\\<share>\$oem$\$1\Rigel\x64\Ship\AppPackages\*\Dependencies\x64\*.appx' | Foreach-Object {$_.FullName})

the"-Update" switch should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd52fe62-457b-c9e1-ad13-a9b1f24c9c38
* Version Independent ID: 6a8c3285-30e1-15a8-6472-f0cfe5b30e20
* Content: [Microsoft Teams Rooms maintenance and operations - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-operations#to-update-using-powershell)
* Content Source: [Teams/rooms/rooms-operations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-operations.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@nachapman Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by nachapman** [comment]
This is not a support issue. It's a documentation issue.
The documentation is not correct.

Others have found the same problem with the documentation. 
https://www.graham-walsh.com/manual-update-of-the-microsoft-teams-room-system-app/
"The difference from the Microsoft docs and to the actual correct command is that you don’t use -Update in the script."
