### ISSUE TITLE
Absatz "Symptome von Problemen mit dem Systemspeicher" - schwerwiegender "Systemspeicher"

### ISSUE THREAD

**Issue by moormaster** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5286]
Im Absatz "Symptome von Problemen mit dem Systemspeicher" heisst es:

"Wenn ein oder mehrere der folgenden Symptome auf Ihrem Computer angezeigt wird, kann ein schwerwiegender Systemspeicher auftreten:"

Sollte es nicht statt Systemspeicher Systemfehler heissen?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: fc21902c-d522-3851-8587-177f01bc085c
* Version Independent ID: 590bcc64-a86d-b61e-7d94-4e4322c4e71d
* Content: [Verwendung des Arbeitsspeichers durch Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/teams-memory-usage-perf)
* Content Source: [Teams/teams-memory-usage-perf.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-memory-usage-perf.md)
* Service: **msteams**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
