### ISSUE TITLE
Does Teams Service Number supports more than 2000 concurrent calls?

### ISSUE THREAD

**Issue by bijaykush** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5287]
I am working to build a calling bot where more than 2000 concurrent call can happen from our customers. I have a plan to assign the Teams Service Number to the calling Bot in our implementation. As per the the document it has been mentioned that 100s of concurrent call is supported by service number which does not give the exact number of concurrent calls.

Hence I was wondering if it supports more than 2000 concurrent calls at a time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f74116db-b4a0-8a58-7e52-0d961e35ed99
* Version Independent ID: 2334f49e-54fb-4d2b-ed4a-dab8b399b45e
* Content: [Getting service phone numbers - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/getting-service-phone-numbers)
* Content Source: [Teams/getting-service-phone-numbers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/getting-service-phone-numbers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@bijaykush Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
