### ISSUE TITLE
Some roles don't have the described rights in teams

### ISSUE THREAD

**Issue by adrienmaugard** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5288]
Hello,

I'm toying with RBAC in teams in a Direct Routing configurations and we had an issue with the described roles:
**Teams Service Administrator** and **Teams Communications Administrator** 
Cannot do the described "Manage voice, including calling policies and phone number inventory and assignment.1" 

Reason: Assignement of a the phone number under Direct Routing configuration requires the usage of Set-CSUser.
From our tests Set-CSUsers is only available to Global Admin (the cmdlet don't show up until you have this role when you import the skypeonline PSSession)

Do we have to wait for the GUI update for this roles to work as expected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b434530-6bf2-6e00-6eae-6fa043d022ce
* Version Independent ID: caab785f-e3a4-831a-87d8-26934a9f834f
* Content: [Use Microsoft Teams administrator roles to manage Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/using-admin-roles)
* Content Source: [Teams/using-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/using-admin-roles.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@adrienmaugard Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
