### ISSUE TITLE
How to tell which version of powershell?

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5295]
At the top of the page, there is an indicator of an issue between Powershell 7 and Teams. As Teams is built in to most OS's now, its difficult to know off the top of your head which version you are using. There should be a command here to indicate how to see which version you have. The comment about having to install Powershell in your system is also a bit depreciated as its been built in for a while now. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5720e37-e8dd-1e3e-ccfa-cf4db31e8cff
* Version Independent ID: 93a36eb2-3554-0e86-e787-759eaaafe5e1
* Content: [Microsoft Teams PowerShell Overview - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-overview)
* Content Source: [Teams/teams-powershell-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-overview.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
@StuBeck32 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by StuBeck32** [comment]
I'm not having an issue. I'm attempting to help you update your documentation so its not confusing.

**Comment by brandber** [comment]
Hi @StuBeck32!

Thanks for the feedback! I'll update the Teams PowerShell installation page with how to identify PowerShell version. For your information, it can be identified by running the following in a PowerShell session:

$PSVersionTable

The output of above contains a property called "PSVersion", which is your PowerShell version.

Thanks again for raising and keep the feedback coming!

**Comment by StuBeck32** [comment]
Great, thanks!
________________________________
