### ISSUE TITLE
No MFA instructions

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5296]
There are no instructions on how to add the Skype addon when using MFA. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5720e37-e8dd-1e3e-ccfa-cf4db31e8cff
* Version Independent ID: 93a36eb2-3554-0e86-e787-759eaaafe5e1
* Content: [Microsoft Teams PowerShell Overview - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-overview)
* Content Source: [Teams/teams-powershell-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-overview.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
@StuBeck32  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by brandber** [comment]
Hi @StuBeck32!

Will add this in, but for reference it behaves the same way as Skype for Business Online Connector stand alone without Teams PowerShell. In the example below, when no credentials are entered you will be prompted which supports MFA authentication.

$session = New-CsOnlineSession

Thanks again for taking the time to help us improve our docs!

**Comment by Petri-X** [comment]
@brandber  that is actually not true.

That was the Skype online CMDLet.

For Teams you do just regular
Connect-MicrosoftTeams
It ask your credentials and then ask also MFA.

**Comment by lindspea** [comment]
@brandber could you please assist?

**Comment by lindspea** [comment]
@StuBeck32 please confirm if @Petri-X solution has resolved the issue, so we can close it. Thanks so much.

**Comment by StuBeck32** [comment]
They did not, but its been two years and the document is completely different, so it isn't relevant anymore. Hopefully @brandber is OK as they dropped the ball here.
