### ISSUE TITLE
Retention for private channel messages

### ISSUE THREAD

**Issue by d1bjo0** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5305]
[According to the doc "Private channel messages aren't supported."  I don't believe this is true, private channel chat is supported with retention according to: https://docs.microsoft.com/en-us/microsoft-365/compliance/create-retention-policies?view=o365-worldwide]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f55c52a5-5841-b9c9-1607-2013dc3f2e20
* Version Independent ID: 16d93458-5e01-646f-dac5-31306cc7f3fb
* Content: [Retention policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/retention-policies)
* Content Source: [Teams/retention-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/retention-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **anwara**

**Comment by scanum** [comment]
@d1bjo0 I know the product teams are always looking for user feedback and how to make SharePoint better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice 
Skype for Business: https://www.skypefeedback.com.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.
Thank you for your contribution to make the docs better! Much appreciated!

**Comment by d1bjo0** [comment]
Thanks, Manuela.  Are you saying the feedback response on the Teams documentation site is not valid?   The page incorrectly states that there is no retention for private channel messages.  I was updating the comments to have this corrected so our customers are not mislead.

Thanks,


Bruce Ostrowski
UC Technical Solutions Professional
Financial Services US | Microsoft Corporation
(Work) 781.487.6654|(Cell) 508.523.8231|bostrows@microsoft.com<mailto:bostrows@microsoft.com>
 [FSI LOGO for Sharepoint]
