### ISSUE TITLE
What does it mean for a meeting to expire?

### ISSUE THREAD

**Issue by Craig-Humphrey** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5308]
Hi,

What does an "expired" meeting look like?  Is it still archived? What's kept/archived/logged?
Does it just mean you can't join?  
Or does it disappear from your Activity/Chat history? 
What if it's pinned? 
Do the files go into the recycle bin?
What about other content?

Thanks
Craig

We just found today that 8 days after a reoccurring meeting ended, we are no longer able to join it, though we can still see the chat, etc.  I've since extended it, but still can't join - I'll wait a bit and see if it comes right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Craig-Humphrey Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Craig-Humphrey** [comment]
Can you please re-open this ticket, as you haven't addressed my questions:
What does an "expired" meeting look like? Is it still archived? What's kept/archived/logged?
Does it just mean you can't join?
Or does it disappear from your Activity/Chat history?
What if it's pinned?
Do the files go into the recycle bin?
What about other content?


I'm happy to log a service ticket about the particular issue I experienced, but that doesn't impact my questions.

Thanks
Craig
