### ISSUE TITLE
this page links to a 404

### ISSUE THREAD

**Issue by jake9000** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5309]
This page leads to https://go.microsoft.com/fwlink/?linkid=854389, which does not seem to exist. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c0a619-c505-73a3-d815-58b384dc9a61
* Version Independent ID: 78b91880-6d1e-a9dc-6099-7a0a15b96a4a
* Content: [Configure an Exchange hybrid organization - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/exchange-hybrid-organization)
* Content Source: [Teams/Exchange-hybrid-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-hybrid-organization.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@jake9000 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@jake9000 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
