### ISSUE TITLE
Teams Auto Update for VDI

### ISSUE THREAD

**Issue by gopal787** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5310]
The 'Install Teams using MSI' section of the documentation states both per-user and per-machine installation is supported and automatic updates are also enabled.

The 'Teams for Virtualized Desktop Infrastructure (VDI)' section of the documentation for a dedicated persistent VDI states both per-user and per-machine installation is supported, however with per-machine installation the Automatic updates is disabled.

Does this mean Auto updates are only available when teams is deployed to a physical device using either per-user or per-machine installation and Auto updates are not available in a VDI environment at all? If yes what is the recommended method to install updates to a VDI environment that is dedicated persistent setup?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@gopal787 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
