### ISSUE TITLE
The following sentece is written in the ending of the text

### ISSUE THREAD

**Issue by rafagranado** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5313]
See also

Watch a video **about** **about** creating...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@rafagranado Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@rafagranado thank you for pointing this out  and helping improve MS Docs. It seems it has been fixed in the interim. Please confirm if there is anything else I can help you with.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@rafagranado Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
