### ISSUE TITLE
Total Call Count definition

### ISSUE THREAD

**Issue by expatmarcos** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5314]
[Enter feedback here]
Please add the definition for Total Call Count measurement and state that this includes calls were setup succeeded but there is no media type associated with the call.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a455280-ea8e-2ddf-2965-60d9dcc0e21d
* Version Independent ID: 7fb320d3-fa69-23fa-113c-53e9d2e11ada
* Content: [Dimensions and measurements - Call Quality Dashboard - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/dimensions-and-measures-available-in-call-quality-dashboard)
* Content Source: [Teams/dimensions-and-measures-available-in-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/dimensions-and-measures-available-in-call-quality-dashboard.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@expatmarcos Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@expatmarcos thank you for reaching out and helping improve MS Docs. At a quick glance I see the article has recently been updated. Please let me know if you still need assistance.

**Comment by scanum** [comment]
@expatmarcos Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
