### ISSUE TITLE
Pay Per Minute Clarification

### ISSUE THREAD

**Issue by syfyfs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5317]
Contradicting statement:

1)
https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-pay-per-minute#need-some-details
Pay-per-minute requires your organization to have Communications Credits set up. 
**_It also requires that a Pay-per-minute license and a Communications Credits license must both be assigned to each user for Audio Conferencing to work._** 
If you want more details, see Set up Communications Credits for your organization and/or Microsoft Teams add-on licensing.

2)
https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-pay-per-minute#why-is-it-best-for-you
**_If you have Audio Conferencing pay-per-minute licenses, you don't have to assign Communications Credits licenses separately to each user specifically for Audio Conferencing usage (you might still need to assign them for other services)._**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fac515b-9c6b-c70c-330e-53557dc23fd2
* Version Independent ID: d515841e-f412-286d-1a97-30507bb50040
* Content: [Audio Conferencing pay-per-minute - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-pay-per-minute)
* Content Source: [Teams/audio-conferencing-pay-per-minute.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-pay-per-minute.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@syfyfs Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@syfyfs thank you for reaching out and helping improve MS Docs. It looks like this information has been updated. Please confirm from your side.

**Comment by scanum** [comment]
@syfyfs Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
