### ISSUE TITLE
Clarify whether Guests can sync files to their desktop

### ISSUE THREAD

**Issue by SimonJHudson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5318]
There is no mention of Guest ability to sync files (using the OneDrive client). This is a key requirement for many Guests to be able to collaborate on files in a way they are familiar with. Documentation on this; how to set it up etc. are sadly lacking

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [What the guest experience is like - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-experience#comparison-of-team-member-and-guest-capabilities)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@SimonJHudson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@SimonJHudson thank you for reaching out and helping improve MS Docs. I'll discuss with the team and see what can be added. In the meantime do you have any suggestions for links that would help if added to the article?

**Comment by scanum** [comment]
@SimonJHudson We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
