### ISSUE TITLE
Teams Guest Access Checklist is missing a key componant

### ISSUE THREAD

**Issue by vseven** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5319]
Went through this checklist multiple times and could not get Teams to work with external/anonymous users.  After some back and forth with Microsoft Support we found that a setting not listed in the checklist needs to be turned on.  Under Teams Admin -> Meetings -> Meeting settings the now very obvious "Anonymous users can join a meeting" needs to be turned on which by default is off.  Until this is done nothing will work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams guest access checklist - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by myxfinance223** [comment]
Yeah I currently encounter the same problem at my company. Anyone has any suggestions ?

**Comment by lindspea** [comment]
@vseven thank you for reaching out and helping improve MS Docs. Are you suggesting adding this note -  "To get Teams to work with external/anonymous users the 'Anonymous users can join a meeting' setting must be turned on, which by default is off."

**Comment by vseven** [comment]
Yes, it needs to be on but it's not in the checklist on how to enable guest access.  I had to put in a support request and even your technician had some trouble figuring it out.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
