### ISSUE TITLE
Clarification on ELC and Teams relationship and time to delete messages.

### ISSUE THREAD

**Issue by cadasi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5322]
Can we please make sure to clarify how Exchange relates to Teams regarding Retention policies in the text highlighted below? For Microsoft Employees and advanced IT people, it might be obvious but there are several customers that will question how the Exchange Life Cycle Assistant will relate to Microsoft Teams. That is super confusing when we don't explain how ELC has to do with Teams.

"Exchange Life Cycle assistant (ELC) runs daily, but it has an SLA of 7 days. As a result, it's possible that, if you have a Teams retention policy to delete items older than 60 days, these items could persist for up to 67 days. This isn't a new situation - it follows the Exchange model. Of course, in most cases, there's no delay."

Also, another piece of feedback. Above, we give an example of 60 days + 7 to delete content, but previously we explain about the 1 day + 7 to delete - I think the 1 day example is more important - but the 60 days is also helpful, but if we don't relate them also, in some way, it feels confusing.

"A Teams retention policy will trigger a process to delete chat and channel messages when those messages expire (based on message creation date). However, depending on service load, it may take up-to seven days to permanently delete these messages from backend storage and Teams app. Also, these messages will be searchable with compliance tools (eDiscovery, end user search) till they are permanently deleted from backend storage."

Final piece of feedback, more direct to PM owner: A 1 day retention day policy should delete messages in 1 day. We have feedback from customers that if we have an SLA of 7 days, this is a bug and not a truly one day retention policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f55c52a5-5841-b9c9-1607-2013dc3f2e20
* Version Independent ID: 16d93458-5e01-646f-dac5-31306cc7f3fb
* Content: [Retention policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/retention-policies#considerations-and-limitations)
* Content Source: [Teams/retention-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/retention-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **anwara**

**Comment by scanum** [comment]
@officedocspr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@cadasi thank you for reaching out and helping improve MS Docs. At a quick glace I see that this article was updated 2 days ago. Please have a look and let me know.

**Comment by scanum** [comment]
@cadasi Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
