### ISSUE TITLE
This article needs to be updated with New Audio (IPAudioMode) and Video Policies (IPVideoMode)

### ISSUE THREAD

**Issue by aalejandroaraujo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5324]
[Enter feedback here]

The article is missing the latest update on the new audio and video policies explained in https://admin.microsoft.com/Adminportal/Home?source=applauncher#MessageCenter?id=MC217887 about bandwidth usage.

![image](https://user-images.githubusercontent.com/36446421/87133249-57604a80-c297-11ea-8fce-02f64ebbfe9c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@aalejandroaraujo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@aalejandroaraujo thank you for reaching out and helping improve MS Docs. Do you have the actual link to the document in mention?

**Comment by scanum** [comment]
@aalejandroaraujo We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
