### ISSUE TITLE
Do meeting organizer and recording initiator need a Stream license to record (but not upload) the meeting? 

### ISSUE THREAD

**Issue by sophiasysun** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5327]
Hi,

I have a couple questions about the "Prerequisites for Teams cloud meeting recording" section.

- Do the requirements for recording a meeting apply to recording an ad hoc call (1 on 1 or group)?

- The doc says "For a Teams user's meetings to be recorded, Microsoft Stream must be enabled for the tenant. In addition, the following prerequisites are required for **both the meeting organizer and the person who is initiating** the recording." Then, in the footnote 1, it says "User needs to be licensed to upload/download meetings to/from Microsoft Stream, however they do not need the license to record a meeting." These 2 statements seem to contradict each other. Do you mean to say that a person initiating the recording needs a Stream license to record AND UPLOAD it to Stream, but does not need a Stream license to simply record the meeting and save it in Teams? In other words, should the first statement be "For a Teams user's meetings to be recorded AND UPLOADED TO STREAM, Microsoft Stream must be enabled for the tenant."

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by Gary620** [comment]
I have the same concern in this document. I opened a case to technical support and got the answer that it is a must to enable Stream license if users want to record Teams meeting. Therefore, the message in the document is wrong. And I also mentioned some vague part of the official document. 

I raised the feedback 2 weeks ago, still no action was taken and no reply about the question. Really don't know any other channel we can find to get this fixed?

Thank you.

**Comment by scanum** [comment]
@sophiasysun Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by sophiasysun** [comment]
Hi scanum, I'm not an admin, so I am unfortunately unable to use the link you suggested to ask for support. @Gary620, thanks for asking the same question. @scanum, I believe Gary620 has the outcome we're looking for, and docs should be updated to reflect the fact that a Stream license is needed to both record the Teams meeting (and call, I assume) AND upload it to Stream.

**Comment by Gary620** [comment]
@scanum Morning. As Sophia mentioned, we are giving feedback on the same issue. And my customer had already opened a case about this problem and got the answer that the document is wrong. The case ID is 20536912, please check it. It's been nearly 1 month, the document is still not modified for the wrong information.

**Comment by sophiasysun** [comment]
Hi all - really appreciate the update in the docs! Much more clear! 
https://docs.microsoft.com/en-us/microsoftteams/cloud-recording

**Comment by Gary620** [comment]
@sophiasysun it has been modified? I still cannot see any difference. Still wrong information there.

**Comment by sophiasysun** [comment]
@Gary620 yes, see the blue box that says "important."

**Comment by Gary620** [comment]
Really? I see no difference from the one 2 month ago. Can you clarify?

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Sophia Sun <notifications@github.com>
发送时间: Thursday, August 13, 2020 3:57:07 AM
收件人: MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com>
抄送: Gary Zhang (bei jing di mei ce fang shi) <v-guazh@microsoft.com>; Mention <mention@noreply.github.com>
主题: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Do meeting organizer and recording initiator need a Stream license to record (but not upload) the meeting? (#5327)


@Gary620<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGary620&data=02%7C01%7Cv-guazh%40microsoft.com%7C5c1cd4e4231345c9af4b08d83ef9e4f6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637328590299732616&sdata=Ka3fW2cO2cxL4ZzRjhcmc5SNLd6FIucmZAThNICV2fA%3D&reserved=0> yes, see the blue box that says "important."

―
