### ISSUE TITLE
Parantesis missing

### ISSUE THREAD

**Issue by FreekPols** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5330]
A parenthesis is missing
New-Team -Name "Contoso Marketing" -Description "Collaboration space for Contoso's Marketing department

Should be:
New-Team -Name "Contoso Marketing" -Description "Collaboration space for Contoso's Marketing department"

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 6a60f957-8007-280c-4081-aa1930771767
* Version Independent ID: d6e71a44-d4ba-b82c-c2fc-ea667f7a889a
* Content: [Manage Teams with Microsoft Teams PowerShell - Microsoft Teams](https://docs.microsoft.com/nl-nl/microsoftteams/teams-powershell-managing-teams)
* Content Source: [Teams/teams-powershell-managing-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-managing-teams.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
@FreekPols Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@brandber

**Comment by scanum** [comment]
@lindspea Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
