### ISSUE TITLE
Restrictions

### ISSUE THREAD

**Issue by Pixie7** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5331]
[Enter feedback here]
Please advise if there are any country-level restrictions on using MS Teams outside the UK?
Will my students face issues if they travel to certain countries? If so, will it please be OK to advise which countries current block meetings via MS Teams. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca7f5d7b-fdf3-f9a7-46e7-689258f33cf9
* Version Independent ID: 86f27884-7c71-ee17-aa4e-5b3e12125814
* Content: [Meetings in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/tutorial-meetings-in-teams?tutorial-step=8)
* Content Source: [Teams/Tutorial-Meetings-in-Teams.yml](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/blob/live/Teams/Tutorial-Meetings-in-Teams.yml)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Pixie7 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
