### ISSUE TITLE
Unable to access a 'live-event' as a presenter from the Teams Webapp

### ISSUE THREAD

**Issue by syedsohaibuddin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5332]
[Enter feedback here]

When I use Microsoft teams on the web-app to access a live event as a presenter, I always end up being an attendee. I need to access the meeting via the Team app for desktop in order to present. I accepted an invitation to be a presenter from the organizer as well.

Please, Look into it.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bef5b5fd-5a4e-7957-f23c-724764a7cb4c
* Version Independent ID: 5fe6c3ab-774b-db2f-5b55-9170bdfe5faf
* Content: [Known issues - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/known-issues)
* Content Source: [Teams/rooms/known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/known-issues.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@syedsohaibuddin  Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.




Following up on this issue. Please let me know if there are any updates. Thanks!
