### ISSUE TITLE
Brio firmware version incorrect

### ISSUE THREAD

**Issue by ikeras** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5333]
This page says that the Logitech Brio supported firmware version is:

Logitech Brio | V2.2.50
-- | --

However, there is no V2.2.50 version of the firmware. The current version of the firmware appears to be 2.0.28, at least for the video. The 2.2.50 is the software version of the firmware update that includes 2.0.28.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf01435-a73b-4bf2-5845-e4cf50c4c3a2
* Version Independent ID: 166e1800-80b1-2496-7160-3040c5b23c3d
* Content: [Microsoft Teams Rooms requirements - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/requirements)
* Content Source: [Teams/rooms/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/requirements.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ikeras Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@ikeras thank you for reaching out and helping improve MS Docs. It seems the article is reading correctly. However, here is an article where some issues were resolved with settings - https://techcommunity.microsoft.com/t5/microsoft-teams/skype-teams-room-system-and-logitech-brio-problem/m-p/965758

**Comment by ikeras** [comment]
@lindspea - the issue is that the doc mentions that the firmware version is 2.2.5; however, that's the version of the *software* that installs the firmware. The firmware version itself is different. See the screenshot below for what I'm referring to.

![image](https://user-images.githubusercontent.com/8271585/94286051-57bcc900-ff09-11ea-8b62-5192ea787e9a.png)

**Comment by scanum** [comment]
@ikeras Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by ikeras** [comment]
Hmm, not sure I understand. This doesn't have anything to do with the tenant or setup of Office 365 or Teams. It's just a docs bug - the docs ask users to upgrade the firmware of their device to a version that doesn't exist.
