### ISSUE TITLE
Teams Meeting add-in in Outlook using incorrect account

### ISSUE THREAD

**Issue by hilari0n** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5335]
I haven't found any other document on the topic of MS Teams add-in for Outlook, so I'm posting here.

My issue is on Windows 10. According to this document, the add-in should automatically use the same account I'm using with the MS Teams desktop application. For me it does not. I have access to more than one organization with both Outlook e-mail accounts and MS Teams. When I had 1, everything was fine. When I added the second account to Outlook, everything still worked OK. When I switched MS Teams to use the second account (there seems to be no way to set up 2 accounts in MS Teams, which is a separate PITA), I thought everything is fine too, but it was not.
The MS Teams add-in seems to still be using the first account: when used to add a Teams meeting to a calendar entry, it creates the meetings in the context of the first account. It does so even if I switched the default account in Outlook to the second one.
The meetings are created in the Outlook calendar of the second account (and don't appear in the calendar of the first account), but can only be managed by my first account, and - as I have it set up to use a waiting room - I have to use my first account to accept people to the meeting, so I actually have to use the first account (e.g. by opening Teams in a browser) to accept myself (the second account) to the meeting (although my second account is the meeting organizer).

Has anyone experienced such an issue?
Any resolution?

I'm afraid what will happen, when I'll have to use the MS Teams from other accounts/organizations? Outlook in general seems to be working relatively fine in such scenarios (although I'd really like it to show me from which account is the reminder/alert or a particular open item window). MS Teams (the desktop app and web app) offers absolutely no support for such scenarios, but works, and the add-in does not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Use the Microsoft Teams Meeting add-in in Outlook - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hilari0n Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
