### ISSUE TITLE
XML values must not be escaped?

### ISSUE THREAD

**Issue by danielniccoli** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5337]
Today I noticed that when you [`SecurityElement.Escape`](https://docs.microsoft.com/en-us/dotnet/api/system.security.securityelement.escape?view=dotnet-plat-ext-3.1) your XML values, then they won't work.

For example, I had a Teams account with a `<` in the password. After passing the password to `SecurityElement.Escape()` and then storing it in the XML file as `<Password>*****&lt;******</Password>` the Teams Rooms app was unable to sign into the account. When I changed `<Password>*****&lt;******</Password>` back to `<Password>*****<******</Password>` and reloaded the XML file, the Teams Rooms app was able to sign into the account.

It should be mentioned, because anybody who is used to create or edit XML files would naturally stumble over that, because the SkypeSettings.xml basically requires invalid XML.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25a70665-5bf1-14f7-1df0-7596effcaf48
* Version Independent ID: 813cf005-2777-9419-d1ce-3f9401ac267c
* Content: [Remotely manage Microsoft Teams Rooms device settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/xml-config-file)
* Content Source: [Teams/rooms/xml-config-file.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/xml-config-file.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Borkason  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Borkason thank you for pointing this out and helping improve MS Docs. Could you possibly give a suggestion for a note explaining this and I can add it to the article?

**Comment by Borkason** [comment]
> Could you possibly give a suggestion for a note explaining this and I can add it to the article?

I think you must ask your developers how they treat this XML file. I can only make assumptions and that should not go into a documentation.

**Comment by lindspea** [comment]
@LanaChin please could you assist?

**Comment by LanaChin** [comment]
Microsoft Teams Rooms article. Reassigning to @dstrome.

**Comment by dstrome** [comment]
Thanks for your feedback. I'm discussing this with the product team and will update when I know more.

**Comment by lindspea** [comment]
@dstrome any update perhaps.

**Comment by dstrome** [comment]
Closing old issues.
