### ISSUE TITLE
A new Section or Page with links to this resource should be added that documents the process to fully decommission SfB Server on prem

### ISSUE THREAD

**Issue by dinocaputo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5338]
A new Section or Page with links to this resource should be added that documents the process to fully decommission SfB Server on prem.  

For example, Removing SfB Server from an on prem environment by using Topology Builder to remove your deployment will cause users Skype related attributes to be set to $NULL and propagated to the cloud.  This has been reported in the MVP community.  In one instance the TelURI attribute was set to $NULL.  

I don't believe this should happen so the PG should weigh in as to how SfB Server should be removed from the Topology and uninstalled in a manner that does not cause an outage for the customer.

**Comment by scanum** [comment]
@dinocaputo Hi we will evaluate adding this to the future documentation updates. Thanks!
