### ISSUE TITLE
are customer subdomains required to be sbcX or can we use free-form text

### ISSUE THREAD

**Issue by anthonysomerset** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5340]
The documentation is unclear whether any freeform test is valid as a customer subdomain for Teams Direct Routing or whether it *must* be in the form sbcX.sbc.carrier.domain

we would prefer to use the customers subdomain portion from their onmicrosoft domain as then we guarantee things are unique and its easier to automate provisioning

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure Session Border Controller - Multiple tenants - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@anthonysomerset  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by anthonysomerset** [comment]
So i had a conversation with our local MSFT Partner Technical Architect on this he confirmed to me that the customer subdomain can be anything we like as long as it is a valid subdomain of the carrier trunk base domain and we have tested this as working

it would be great if the documentation could advise more clearly that sbcX is a placeholder and any valid alphanumeric string is acceptable here

**Comment by lindspea** [comment]
@anthonysomerset thank you for reaching out and helping improve MS Docs.  I'll add the note. Could you please just clarify where it should be inserted in the doc? Under the "Register a subdomain name in a customer tenant" section?

**Comment by anthonysomerset** [comment]
Hi i think the Note:

```
Use sbcX.customers.adatum.biz to enable voice in the carrier tenant.
```

should be updated  to something like

``` 
Use sbcX.customers.adatum.biz to enable voice in the carrier tenant. sbcX can be any unique and valid alphanumeric hostname preferred.
```

**Comment by lindspea** [comment]
@scanum this can be closed thanks.

**Comment by scanum** [comment]
@anthonysomerset Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
