### ISSUE TITLE
wildcard in CN and SAN for Teams DR

### ISSUE THREAD

**Issue by anthonysomerset** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5341]
we have created an SSL cert with a supported root, both the CN and the SAN fields of the SSL come out as

*.sbc02.domain.com

https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan#public-trusted-certificate-for-the-sbc - states that the CN must be the SBC FQDN - e.g. sbc02.domain.com but for multi-tenant we need a wildcard and our SSL provider puts the wildcard fqdn in the CN and the SAN is this actually supported or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure Session Border Controller - Multiple tenants - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@anthonysomerset Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
