### ISSUE TITLE
Latest Version of MSI

### ISSUE THREAD

**Issue by Brennanm625** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5342]
The download links here point to an 'older' version of the MSI. Can you please refresh the links to point to the latest MSIs.

**Comment by scanum** [comment]
@Brennanm625 thanks for the feedback. Could you please link to the documentation you are referring to? Thanks

**Comment by RAJU2529** [comment]
@Brennanm625 . You can download latest .msi  for chromium-based edge browser for the enterprise. But you can use for personal use.

**https://www.microsoft.com/en-us/edge/business/download**

**Comment by Brennanm625** [comment]
> @Brennanm625 thanks for the feedback. Could you please link to the documentation you are referring to? Thanks

Hi. This relates to the TEAMS MSI needed for the VDI related environments. The link for the download is here:
https://docs.microsoft.com/en-us/microsoftteams/msi-deployment

**Comment by lindspea** [comment]
@Brennanm625 Thank you for reaching out. Please could you let me know which article you are referring to that has the old version of the MSI so that I can have the correct download link added to it.

**Comment by Brennanm625** [comment]
> Thank you for reaching out. Please could you let me know which article you are referring to that has the old version of the MSI so that I can have the correct download link added to it.

https://docs.microsoft.com/en-us/microsoftteams/msi-deployment

1.3.00.13565 has been the version linked under the Commercial Links embedded within the above landing page.

![Teams](https://user-images.githubusercontent.com/18462900/88145028-bb690400-cbf1-11ea-8b08-3f84f77b4bc9.PNG)

Regards, Mike

**Comment by lindspea** [comment]
@LolaJacobsen can you assist please? Do we have updated links for the latest MSI's?

**Comment by RAJU2529** [comment]
I am thing like below.
downloading latest version in .exe file
by uisng conversion software, convert .exe  to .msi 
then installing .msi file

**Comment by RAJU2529** [comment]
Just now i downloaded .exe file, and i converted that file into .msi file, then I installed successfully.

**Comment by Brennanm625** [comment]
> Just now i downloaded .exe file, and i converted that file into .msi file, then I installed successfully.

Really just looking to follow the official process of getting the MSI through the MS documented method.

If the document is changed to state, download the exe and extract/convert to an MSI, fine, we can follow that route. As it stands the MS instruction is to download the MSI through that link, I don't want to start a conversion process and then roll that out to a large VDI environment and find it isn't supported.

**Comment by RAJU2529** [comment]
@Brennanm625 .Then wait for the updated version link in this article.

**Comment by Brennanm625** [comment]
The link has updated to the latest version now.
