### ISSUE TITLE
Can't find report containg meeting attendance data

### ISSUE THREAD

**Issue by lrandall-gillsch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5343]
On this page it says "Teams admins can view additional meeting attendance data in the Teams admin center, under Analytics & reports > Usage reports. See Related topics below to learn more." Looking at the related topics, I cannot find additional information on attendance data, searching for the word attendance on the 2 pages in the related topic section, brings up no results.

I'm looking to make a report on a meeting in the last week, which contains attendance data and times etc., like what you can see under the users "Call History", but would like a way to actually export this data if possible.

Many thanks,

Luke

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a8b1087-ae40-6813-16bc-a69c90e50d19
* Version Independent ID: b808e843-80d8-4a96-c6ed-e8175968eb73
* Content: [Microsoft Teams meeting attendance report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/meeting-attendance-report#related-topics)
* Content Source: [Teams/teams-analytics-and-reports/meeting-attendance-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/meeting-attendance-report.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@lrandall-gillsch Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by lrandall-gillsch** [comment]
Hi @scanum 

Thank you for your response, I'll contact O365 Support to see if they can help me further, the confusion I had was that the documentation on this page says that there is more information on attendance data in the "Related Topic" section, but upon looking at those pages I couldn't find what it was referring to.

Many thanks and take care,

Luke
