### ISSUE TITLE
Navigation on Steps 3 & 4 is not accurate

### ISSUE THREAD

**Issue by GrantErickson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5345]
Current: In the Microsoft 365 admin center, go to Settings > Settings, ...
Correct: In the Microsoft 365 admin center, go to Settings > Org settings, ...
Same is true for both steps 3 and 4
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams guest access checklist - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@GrantErickson  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@GrantErickson Thank you for reaching out. Just to clarify, are you suggesting changing the first point in step 3 and step 4 to read as follows: In the Microsoft 365 admin center, go to Settings > Org Settings, click Services, and then select Microsoft 365 Groups. per your "correct" information above.

**Comment by GrantErickson** [comment]
Yes, that was what I experienced on the admin site.
Grant

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@GrantErickson Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by GrantErickson** [comment]
I didn't see the change in the PR, but the docs site is now correct. Thanks.
