### ISSUE TITLE
Incorrect translation of "Reaction" in Japanese article

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5347]
- Suggestion
"反応" => "リアクション"

https://docs.microsoft.com/ja-jp/microsoftteams/teams-analytics-and-reports/teams-usage-report

![image](https://user-images.githubusercontent.com/13634805/87505661-5d459980-c6a4-11ea-8258-f3a7eb980efa.png)

"Reaction" translates "リアクション" in the actual service.
![image](https://user-images.githubusercontent.com/13634805/87505739-9a119080-c6a4-11ea-99f0-af91bb1b265b.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5b138331-2f10-a05d-7e88-68e62e0b3e4f
* Version Independent ID: f923b648-ffe4-8a8a-c189-6e31f1032c10
* Content: [Microsoft Teams の使用状況レポート - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/teams-analytics-and-reports/teams-usage-report)
* Content Source: [Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officeglobal Could you kindly help with this request? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@kefujino , @scanum  String "Reaction" updated to リアクション

**Comment by kefujino** [comment]
> @kefujino , @scanum String "Reaction" updated to リアクション
Perfect! Thank you for your quick work!! Very helpful for us,

**Comment by scanum** [comment]
@kefujino Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
