### ISSUE TITLE
Missing paragraph about Basic Auth

### ISSUE THREAD

**Issue by epcodijk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5348]
[Enter feedback here]

Hi, I followed this page and it works, however maybe it's good to add an article or paragraph about the fact the account is still needing BasicAuth.

So you have to create a separate AuthenticationPolicy where the TeamsRoom account can still use BasicAuth to login.

Please add that.

Best regards,

Epco Dijk

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Microsoft 365 or Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-office-365)
* Content Source: [Teams/rooms/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-office-365.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@epcodijk Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@epcodijk Hi there. Thank you for reaching out. Would you suggest adding a note to the article as follows - "You have to create a separate AuthenticationPolicy for TeamsRoom account can still use BasicAuth to login" - under Requirements?

**Comment by dstrome** [comment]
Teams Rooms support modern authentication - https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-authentication
