### ISSUE TITLE
Capability Types missing

### ISSUE THREAD

**Issue by kannanramesh26** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5349]
Three capability types listed below for inbound calls are missing in this document but are seen in customer PSTN usage reports.
MCOEV
MCOEV_VIRTUALUSER
FREECALL

Can these be added please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ad0c889-56d5-35fe-de15-177b6d922d07
* Version Independent ID: e4363647-33e1-b665-5881-169fb619a5b3
* Content: [Microsoft Teams PSTN usage report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/pstn-usage-report)
* Content Source: [Teams/teams-analytics-and-reports/pstn-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/pstn-usage-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@kannanramesh26 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@LanaChin Hi Lana. Should these capabilities be added to the list in the document?

**Comment by SanderSade** [comment]
These also need to be added to https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-online-reporting/pstn-usage-report, https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/pstn-minute-pools-report and https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-online-reporting/pstn-minute-pools-report

**Comment by Reeced40** [comment]
@LanaChin please see message above as well regarding capability types missing.

**Comment by LanaChin** [comment]
Followed up with PM.

**Comment by quentinhurdazure** [comment]
hi @SanderSade  and @LanaChin  I'll get update the docs and create a requirement item in ADO to track this in our backlog.  We will not have a solution to report on this for this at least for a week.

**Comment by LanaChin** [comment]
Thanks for your input. We've updated https://docs.microsoft.com/microsoftteams/teams-analytics-and-reports/pstn-usage-report with the capability types.
