### ISSUE TITLE
About MS Teams recording prerequisite

### ISSUE THREAD

**Issue by Gary620** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5355]
First of all, I'd like to say I have opened a case to technical support regarding this issue. The case number is **20536912**. 

In the document:
https://docs.microsoft.com/en-us/microsoftteams/cloud-recording#prerequisites-for-teams-cloud-meeting-recording

We found there’s an error about the “Prerequisites for Teams cloud meeting recording”, I submitted an issue in Github, but there’s no progress during the past 1 month, and I don't know why it was closed without doing anything.
The problem details is like below:
For the prerequisites part, please check the "!important" part.
 
It is saying that:
"Users won't need a Microsoft Stream license assigned if you want users to only record and download the recordings. This will mean that the recordings aren't stored in Microsoft Stream but are instead stored in Azure Media Services (AMS) with a 21-day limit before it's deleted."
We were doing recording successfully without enabling Stream license in the past. However, currently we cannot record it. We opened a case and the tech support said it is a must to enable Stream license for the Teams meeting recording.
If this is true, would you please modify the document to avoid customer's misunderstanding?
In addition, there's another sentence in the same article, which says:
 
“Currently, the meeting recording feature is turned off for customers whose Teams data is stored in-country if Microsoft Stream isn't available in the in-country data residency region where the data is stored.”
The support engineer said that it means we have to enable Stream license so that we can record Teams meeting. But I really don't think it is saying the same thing. This statement is confusing, would you please check it and make it more clear?

Thanks.

**Comment by scanum** [comment]
@Gary620 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Gary620** [comment]
@scanum Morning. It's been 4 days, is there any update?

Thank you.

**Comment by Reeced40** [comment]
@Gary620 Apologies for the delay, I'm busy investigating with the team to confirm which is correct. In the meantime could you perhaps suggest what you would have changed in the article to make it clearer?

**Comment by Gary620** [comment]
@Reeced40 Thank you Reece for the responding. As I mentioned in the first post, we confirmed with the tech support engineer that if the user wants to record Teams meeting, they have to enable their Stream license. But the information in the document is on the contrary.
https://docs.microsoft.com/en-us/microsoftteams/cloud-recording#prerequisites-for-teams-cloud-meeting-recording

It is saying that:
"Users won't need a Microsoft Stream license assigned if you want users to only record and download the recordings. This will mean that the recordings aren't stored in Microsoft Stream but are instead stored in Azure Media Services (AMS) with a 21-day limit before it's deleted."

In addition, the statement below in the article is also confusing, would you please clarify it or make it easier to understand?

“Currently, the meeting recording feature is turned off for customers whose Teams data is stored in-country if Microsoft Stream isn't available in the in-country data residency region where the data is stored.”

Thank you.

**Comment by Reeced40** [comment]
@tonysmit please could you provide some clarity with this issue regarding Microsoft Stream, meeting recording and downloading, if Microsoft Stream is not available in the region etc.

**Comment by tonysmit** [comment]
@ashwinma14 - I know we have another thread about this. Can you add some notes here to explain? Also, can you do a PR to update this doc (since I'm not the content owner) and I will merge your changes. Thanks.

**Comment by Gary620** [comment]
@tonysmit Tony, good day to you. Is there any update? Thanks。

**Comment by Gary620** [comment]
@Reeced40 Morning. Is there any progress on it? It's been 1 week. Thank you.

**Comment by Reeced40** [comment]
@ashwinma14 any update yet please?

**Comment by Gary620** [comment]
@ashwinma14 Hi, how are you doing? May I know is there anything new on this thread? The problem has been 2 month since I raised the first issue.
@Reeced40 Reece, can you also help on this?

**Comment by tonysmit** [comment]
Update: I'm meeting with the PMs to discuss this.

**Comment by Gary620** [comment]
@tonysmit Thank you Tony. Is there any update from the discussion with PMs?

Thank you.

**Comment by tonysmit** [comment]
@Gary620 - hey. I'm trying to get someone to answer me on this. Starting with a different PM this time.

**Comment by tonysmit** [comment]
@SamChung-MS - Here is one of the issues that I spoke to you about.

**Comment by Gary620** [comment]
@tonysmit Hi Tony, really appreciate your kind help. What do you mean by "the PR that I submitted?" I just found the issue and gave the feedback. And it's been over 2 month....

**Comment by Gary620** [comment]
@tonysmit @SamChung-MS , Hi Tony and Sam, is there any update? Thank you.

**Comment by Gary620** [comment]
@tonysmit Hi Tony, good day. I'm sending this message to follow up. Is there any response from Sam Chung? It's been another 10 days without any response and update..... Really appreciate if you could find the right person and speed it up.
@Reeced40 FYI.

**Comment by SamChung-MS** [comment]
Hi @Gary620, sorry for jumping on late here. Are you basically asking if recording will work without Stream?

**Comment by Gary620** [comment]
@SamChung-MS Hi, Sam. Absolutely right. I was able to record without enabling Stream license. But then I cannot. I opened a case, the tech support said "it is a must" to enable Stream license if you wanna record Teams meeting. This is exactly different from the saying in the official document. To avoid misleading customers, I raised a problem 3 month ago, and it has been delayed till today. Would you pls help?

**Comment by SamChung-MS** [comment]
So it should work. My understanding is the same as yours, in that you don't need to have to Stream. The recordings will not be saved forever, but instead will only last for a few weeks before they're wiped. But the button should still be there. Have you checked with your tenant Admin to make sure that the recording policy is enabled?

**Comment by Gary620** [comment]
@SamChung-MS Thank you Sam, finally I got the answer after 3 months. However, this is just on the opposite of what the technical support engineer from CSS stated. They said “it is a must to enable Stream if you want to record Teams meetings". They 100% confirmed this and refused to do further troubleshooting for my case. 

Would you please sync with the team from Microsoft? I think it'll be more efficient that doing this back and forth.

Thank you so much Sam.

**Comment by SamChung-MS** [comment]
I don't know what team at MS you're referring to. If it's the support engineer you spoke with, I won't have any idea who that is or access to your case. I'm on the product engineering team, and don't really have access to support cases. You can let the support engineer know though that the product team has said that Stream is not needed.

**Comment by Gary620** [comment]
@SamChung-MS That support engineer raised a bug to PG and got the answer from PG that we should give a feedback in the official article. That's why I raised the issue here and it's been over 2 months. No progress. Please see the screen shot with the PG's comment. This article has to be modified.

![image](https://user-images.githubusercontent.com/67570164/91965021-7a145a00-ed42-11ea-8fdb-33c7117a77ad.png)

**Comment by SamChung-MS** [comment]
The highlighted part says we need to update the article to say you need to enable recording. It already says that. It's the 6th bullet point on the page: https://docs.microsoft.com/en-us/microsoftteams/cloud-recording#prerequisites-for-teams-cloud-meeting-recording
We will be making some additional changes to that page anyways soon. So when we do I'll also look at updating the language around Stream requirements.
