### ISSUE TITLE
Stilted English language use throughout Teams installation documentation

### ISSUE THREAD

**Issue by yukon-cornelius** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5356]
Hello!  On the "Get clients for Teams" page, there (at least) 2 examples of highly-technical-yet-unapproachable language ...

> Windows
> The Microsoft Teams installation for Windows provides downloadable installers **in 32-bit and 64-bit architecture**.
> 
> Note
> The **architecture** (32-bit vs. 64-bit) of Microsoft Teams is **agnostic to the architecture** of Windows and Office that is installed.

On the "Install Teams using MSI" page, there are whole sentences within parentheses, or referring a PC as a "the computer" or "that machine" ...
> When deployed, Teams will auto launch for all users who sign in on that machine. **(You can disable auto launch after installing the app. See below.)** We recommend that you deploy the package to the computer, so all new users of the machine will also benefit from this deployment.

... and also on that MSI page, use of long run-on sentences using 1-2 syllable words like ...
> PC installation
> The Teams MSI will place an installer in Program Files. **Whenever a user signs into a new Windows User Profile, the installer will be launched and a copy of the Teams app will be installed in that user's AppData folder.**

Other pages within the Teams documentation flow like conversational language, but the Teams (and SkypeBiz?) install pages suggest the original author is uncertain about MS enterprise app installers OR has lifted straight from a technical doc, and used "agnostic" when other words are more-appropriate (like "indifferent" or "irrelevant").  I'd suggest a passthrough to align Teams (and SkypeBiz) with Office's C2R docs to match their content & terminology.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@yukon-cornelius Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@yukon-cornelius thank you for reaching out and helping improve MS Docs. I see this article was updated yesterday. Please let me know if you still need assistance.

**Comment by scanum** [comment]
@yukon-cornelius Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
