### ISSUE TITLE
Comodo has re-branded as Sectigo

### ISSUE THREAD

**Issue by imamadi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5357]
Since Comodo has re-branded as Sectigo (https://sectigo.com/resource-library/comodo-ca-rebrands-as-sectigo), will certificate from Sectigo CA also supported to be used as SBC certificate? If yes, please update the docs to include Sectigo CA on these docs. If not, please also mention that Sectigo CA is not supported.

Thanks & regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e26faf8c-529e-b317-5934-cd41cfe8fa24
* Version Independent ID: 3ddd5d0a-6dbb-4940-1814-8346e293701b
* Content: [Plan Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan)
* Content Source: [Teams/direct-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by erwinbierens** [comment]
Sectigo is working with Direct Routing, should indeed be good to update if this is also officially supported by Microsoft.

**Comment by scanum** [comment]
@erwinbierens Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@imamadi Hi. Thank you for reaching out to improve MS Docs. Please let me know if this helps - https://techcommunity.microsoft.com/t5/microsoft-teams/comodo-sectigo-certificate-for-ms-teams-direct-routing/m-p/1267664 and see related issue - https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5148

**Comment by scanum** [comment]
@erwinbierens Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
