### ISSUE TITLE
Clarity on .NET Framework 4.7.x support

### ISSUE THREAD

**Issue by gtimread** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#536]
Please update this document to clarify that .NET Framework 4.7.2 and 4.7.1 are not currently supported (assuming that this is still the case)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c475b5d-09ed-7f58-86d4-27f28e33ef7a
* Version Independent ID: f0ad50f3-ea93-9424-6de8-a0b778e90b23
* Content: [Server requirements for Skype for Business Server 2015](https://docs.microsoft.com/en-gb/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/server-requirements)
* Content Source: [Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by kenwith** [comment]
@gtimread - on this article it looks like .net 4.7 is supported, 

_• .NET 4.7 (for Skype for Business Server CU 5 or later releases)_ 



I am not a SME on this one but can get this updated if there is a gap. Did you find information somewhere that .net 4.7.1 and 4.7.2 are not supported?

Thanks for providing feedback and taking the time to make the docs accurate!

**Comment by kenwith** [comment]
@gtimread - Please let us know any details on 4.7.1 and 4.7.2 not being supported. From the feedback we have received internally the article should be correct and those should be supported. But we could definitely be having a missed communication and we want to make sure everything is completely accurate. Appreciate the feedback!
