### ISSUE TITLE
Create meeting and invite attendees using tags

### ISSUE THREAD

**Issue by Saml43** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5360]
In Microsoft teams I would like to be able to create a meeting and include all attendees attached to a tag.  For example: 

![image](https://user-images.githubusercontent.com/17888254/87702038-e02f2880-c766-11ea-8cb9-624864456a0c.png)

This would be similar to distribution groups in office, where you can add the group to a scheduled meeting and then expand the list of members of that group so you can use the scheduling assistant.

**Comment by scanum** [comment]
@Saml43 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
