### ISSUE TITLE
Incorrect phone number on email

### ISSUE THREAD

**Issue by srandom** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5361]
Just received email titled 
You now have Audio Conferencing for Microsoft Teams or Skype for Business Online – Here is your dial-in information and PIN
from Microsoft Audio Conferencing <maccount@microsoft.com>
(Probably wrong place to submit this. Only place could find).

Email states
"Conference phone number:  +44 (20) 3787xxxx"
That number makes no sense. This is not a UK format number. It implies I should remove the 20 which I don't think is the intent. 

Internal UK phone numbers are formatted like: 020 1234 5678
So when dialling in form outside UK, it becomes: +44 20 1234 5678 
The international format is to put the zero in parenthesis so they can decide to either start the dialing with +44 or 0: 
+44 (0) 20 1234 5678 

(or if you're using some funky system that means I'm supposed to use 20 in a weird way, you'll have to explain that because I don't know how to use that).

**Comment by scanum** [comment]
@srandom Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by srandom** [comment]
I am not an admin. I am an end-user. 
This is not something I intend to follow-up. I was just hoping to inform Microsoft so this is the end of the matter as far as I'm concerned. 
Looking at [screenshots online](https://www.google.com/search?q=You+now+have+Audio+Conferencing+for+Microsoft+Teams+or+Skype+for+Business+Online+%E2%80%93+Here+is+your+dial-in+information+and+PIN&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiW_cSnitTqAhVHURUIHX8bCEEQ_AUoA3oECA0QBQ#imgrc=DQZau9v4VIDZxM), you seem to be using the American practice of using parenthesis on geographic areas when in fact when formatting international numbers, you're supposed to only using them around the initial zero or country code.:
https://howtophoneto.com/glossary/brackets/
