### ISSUE TITLE
Communication Credit is not an option to buy under billing

### ISSUE THREAD

**Issue by alanburchill** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5362]
Step 2 Item 2 is not accurate. There is no Communication Credit option to purchase... We want to by additional dial-out minutes for audio conferencing what option should we activate?

https://docs.microsoft.com/en-gb/microsoftteams/set-up-communications-credits-for-your-organization#step-3-assign-a-communications-credits-license-to-users
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 277cf140-5c6c-82c7-cc56-490ef2188754
* Version Independent ID: 72e7de29-fd71-23bf-15a7-172634c2a5fd
* Content: [Set up Communications Credits for your organization - Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/set-up-communications-credits-for-your-organization)
* Content Source: [Teams/set-up-communications-credits-for-your-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-communications-credits-for-your-organization.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@alanburchill  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @alanburchill, thank you for your feedback and help us to improve docs.microsoft.com.

Where is your tenant located?

I can see this option in my demo/test tenant:
![image](https://user-images.githubusercontent.com/33589238/87956326-4973ac00-ca85-11ea-9cc7-32e7cd8656e8.png)

Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. I appreciate and encourage you to do the same in the future also.

**Comment by scanum** [comment]
@alanburchill We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
