### ISSUE TITLE
Teams communications admin does not have access to the reoports

### ISSUE THREAD

**Issue by MarkusDP** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5365]
We have a user who should only read the reports. According to the documentation, the role of the "Team communications admin" should suffice for this. However, the user does not have access to Analytics & reports.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 78ade1a4-092c-1132-44df-ee2c683fdd33
* Version Independent ID: 396b1aee-2f40-9895-9b00-07e38d11d31b
* Content: [Microsoft Teams – Analyse und Berichterstellung - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/teams-analytics-and-reports/teams-reporting-reference#feedback)
* Content Source: [Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@MarkusDP Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
