### ISSUE TITLE
Should there be a caveat here?

### ISSUE THREAD

**Issue by gwynt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5366]
Hi,

In this page there is a section named "Interop Escalation Experiences" found [here](https://docs.microsoft.com/en-us/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability#interop-escalation-experiences).

The final statement in this section reads as follows:-
"Once the parties have joined the meeting, they can conduct any activity supported in meetings, such as desktop or content sharing, file sharing or transfer, adding other participants, and so on."

I believe this should be caveated as the ability to perform the activities described will depend on the user initialising the meeting's Skype for Business or Microsoft Teams Meeting Policies and Settings. Users may not be allowed to conduct screen or desktop sharing or be allowed to transfer and share files.

I just thought that the statement is a little misleading as unsuspecting administrators may try and sell the upgrade path and not get what they were expecting.

Cheers, G.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d53d0cb0-90a6-5932-f78e-7de6fcc4d481
* Version Independent ID: 3d468027-cc37-5199-32ec-819bf62b2caa
* Content: [Interoperability between Skype for business and Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability)
* Content Source: [Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@gwynt Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
