### ISSUE TITLE
Can access MS Teams admin center even if the link is not available

### ISSUE THREAD

**Issue by binish23** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#537]
Even if the MS Teams new admin center link is not rolled out to the Office 365 tenant, the administrators can still access it by navigating to "https://admin.teams.microsoft.com/dashboard".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9f904e5-d015-70b0-b809-9b0b62931ab5
* Version Independent ID: aa59fcc6-0a6d-c82f-6b5e-ffb85e08ea8a
* Content: [Manage Teams during the transition to the new Microsoft Teams and Skype for Business Admin Center](https://docs.microsoft.com/en-us/microsoftteams/manage-teams-skypeforbusiness-admin-center)
* Content Source: [Teams/manage-teams-skypeforbusiness-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-teams-skypeforbusiness-admin-center.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by kenwith** [comment]
@binish23 - thank you for taking the time to submit feedback and for making the docs better. This is good info and I will coordinate with the owner of this doc, @LolaJacobsen , to see how it can be integrated. Thanks again for giving your knowledge back to the Teams community!

**Comment by kenwith** [comment]
I was able to get this into the backlog for the Teams/Skype team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by SharS** [comment]
Ran this by the PM who responded "Suggest not to include this as customers should continue to access through the admin center's drop-down link in the O365 admin portal."

**Comment by kenwith** [comment]
@SharS - thanks! We can close the internal item then. @binish23 - just FYI the product team is recommending to use the O365 portal.
