### ISSUE TITLE
Error in sign in example

### ISSUE THREAD

**Issue by mtoldfield** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5375]
Hello,

In your sign in example, you have used "Credentials" instead of "Credential".

> Get-Credentials : The term 'Get-Credentials' is not recognized as the name of a cmdlet, function, script file, or operable program

This should be Get-Credential.

>Connect-MicrosoftTeams : A parameter cannot be found that matches parameter name 'Credentials'

This should be -Credential

I have not tested, but spotted the same error in the Skype Connector part of the example as well.

Fixed version below:

`$credential = Get-Credential

#Connect to Microsoft Teams
Connect-MicrosoftTeams -Credential $credential

#Connection to Skype for Business Online and import into Ps session
$session = New-CsOnlineSession -Credential $credential
Import-PsSession $session
`

Thanks,
Mike Oldfield

**Comment by mtoldfield** [comment]
Apologies, realised I missed the link to the offending document.

https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install

**Comment by scanum** [comment]
@mtoldfield Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@mtoldfield thank you for pointing this out. It looks like the article has been fixed in the interim. Please check and let me know. Thanks again.

**Comment by mtoldfield** [comment]
@lindspea Thank you for letting me know. I have taken a look and it all looks good. Thanks to all involved, keep up the great work you all do 👍
