### ISSUE TITLE
Firmware update release notes?

### ISSUE THREAD

**Issue by jschadow** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5386]
Is there an official firmware release page for Desk phones? Poly CCX 500 has 5.9.13.0374 dropped without anything known about it. As far as I can tell, it corrects the serial number in Intune to use the MAC address as Poly defines on the box of the phone - instead of some internal ID number. All of which would have been nice to know beforehand, so I could have uploaded a new Corporate Identifier CSV list to Intune.

Seems Microsoft is a bit hit or miss in regards to updates to Teams IP Phone firmware updates. Even a link to what it does on the Teams Admin center page would be immensely useful - just not nothing!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae4c265a-8df4-647d-fc42-5054e3340c20
* Version Independent ID: 249c7301-9c82-b1c4-8401-54553370302b
* Content: [Phones for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/phones-for-teams)
* Content Source: [Teams/devices/phones-for-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/phones-for-teams.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
