### ISSUE TITLE
Update installer link

### ISSUE THREAD

**Issue by JAK1047** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5389]
The latest update for the Machine Wide Installer is 1.3.00.18160. This fixes the noted UTC issue.

https://docs.microsoft.com/en-us/azure/virtual-desktop/teams-on-wvd#known-issues-and-limitations

Known issues and limitations
Client deployment, installation, and setup

Teams currently only shows the UTC time zone in chat, channels, and calendar

Is this considered GA and can the installer links on this page be updated to the below?:

https://statics.teams.cdn.office.net/production-windows-x64/1.3.00.18160/Teams_windows_x64.msi
https://statics.teams.cdn.office.net/production-windows/1.3.00.18160/Teams_windows.msi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@JAK1047 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by JAK1047** [comment]
Any update towards this?

**Comment by lindspea** [comment]
@JAK1047 thank you for reaching out and helping improve MS Docs. Apologies for the late reply, but it looks like the document has been updated with new information in the interim. Please can you have another look and let me know if it still needs any updating.

**Comment by scanum** [comment]
@JAK1047 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
