### ISSUE TITLE
detection method?

### ISSUE THREAD

**Issue by ps959** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5391]
Should the package be per user or per machine? What should the detection method be? If it's the GUID than that won't work for per user? Is that right? 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Teams using Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ps959 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by ps959** [comment]
So you provide incomplete documentation and you want me to open a ticket? Ok. got it.
________________________________

**Comment by bahnjee** [comment]
@scanum is correct.  Improving the documentation is the point of these pages.  

This doc clearly states the Teams installer is copied to Program Files.  So there's your detection.  Does that file exist or not?  (You could also add date/version checking if you like.)  Deploying this MSI will not install Teams; it will copy an installer to Program Files.  This installer will be kicked off later when users log on, but that's not going to be something your deployment package will be detecting.
