### ISSUE TITLE
Linux teams

### ISSUE THREAD

**Issue by patrickhwood** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5392]
The command to run Teams on Linux is "teams" not "Teams" (lower case "t", not upper case -- Linux commands are case sensitive).
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@patrickhwood Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@patrickhwood Thank you for reaching out. Are you referring to the PowerShell right at the bottom of the document? I checked under Linux and I can't seem to find the command.

**Comment by patrickhwood** [comment]
This sentence appears twice under the "Linux" heading:

"You can launch Teams via Activities or via Terminal by typing Teams."

However, the correct command is "teams".  Note that file and therefore command names on linux are case-sensitive, so "Teams" is not the correct command.

**Comment by LolaJacobsen** [comment]
fixed: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/5449
