### ISSUE TITLE
Policy setting in doc does not match label in Teams Admin Center

### ISSUE THREAD

**Issue by schumatt-msft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5393]
In the _Use the Microsoft Teams admin center to turn on inline message translation_ section of the document, the label, the policy setting for _Allow users to translate messages_ actually appears in the Teams Admin Center as _Translate messages_.  

![image](https://user-images.githubusercontent.com/52325421/88079981-4b944400-cb33-11ea-8593-4488ea62f6b0.png)

Please consider updating the text to match what users see in the Teams Admin Center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19e91f77-0c01-5d38-0bd4-65ee44aab5cb
* Version Independent ID: 08ea83b3-c241-979c-3afb-3355ab322489
* Content: [Turn on inline message translation - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/inline-message-translation-teams)
* Content Source: [Teams/inline-message-translation-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/inline-message-translation-teams.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@officedocspr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@scanum this can be closed please.

**Comment by scanum** [comment]
@officedocspr Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
