### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by jesegher** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5398]
[Enter feedback here]
_Teams admins can view additional meeting attendance data in the Teams admin center, under Analytics & reports > Usage reports._

This part is incorrect. In the usage reports, there no reference to an attendance report. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a8b1087-ae40-6813-16bc-a69c90e50d19
* Version Independent ID: b808e843-80d8-4a96-c6ed-e8175968eb73
* Content: [Microsoft Teams meeting attendance report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/meeting-attendance-report)
* Content Source: [Teams/teams-analytics-and-reports/meeting-attendance-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/meeting-attendance-report.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@jesegher Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@jesegher Thank you for reaching out. Please see if this link answers your question - https://support.microsoft.com/office/download-attendance-reports-in-teams-ae7cf170-530c-47d3-84c1-3aedac74d310

**Comment by jakefirman** [comment]
I would echo the issue reported by @jesegher. The documentation suggests that an admin can access meeting attendance data (when a user joined and exited the meeting) through the admin "Analytics and Reports" page, which appears to be false. As a tech administrator for a school district facilitating distance learning through Microsoft teams during the COVID epademic, the ability for an admin to pull this data for all meetings, or better, the ability to extract this data through the Graph API (or another automated method) would be a total game-changer for the systems we could provide for our teachers and school administrators.

@Reeced40 The article you referenced shows how a meeting organizer can download the attendance via the Teams Application, but the documentation suggests that an admin can access the same data through the Teams Admin "Usage Report", which appears to be false.

**Comment by Reeced40** [comment]
@LolaJacobsen please could you assist with this issue?

**Comment by Reeced40** [comment]
@LolaJacobsen Hi Lola, any updates on this?

**Comment by Reeced40** [comment]
@jesegher it looks like this article has been update in the interim with more information. Please let me know if this issue can be closed. Thanks again.

**Comment by scanum** [comment]
@jakefirman  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by LanaChin** [comment]
Updated article to remove the reference to meeting attendance reports in usage reports. Thank you.
