### ISSUE TITLE
Not sufficient

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5399]
This document states what is required to enable the Teams calendar function to work with Exchange Server on-premises mailboxes. However, what it states is not sufficient. The Teams Calendar also requires that the Teams Scheduling Service has access to the Autodiscover and EWS endpoints of the on-premises mailboxes. This requires public IP, DNS and certificates for the endpoints. It is similar to the requirements for a classic full hybrid.

This Exchange Team Blog [Configuring Teams calendar access for Exchange on-premises mailboxes](https://techcommunity.microsoft.com/t5/exchange-team-blog/configuring-teams-calendar-access-for-exchange-on-premises/ba-p/1484009) is the only Microsoft document I know of that explains the requirement accurately.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@Air-Git Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
@scanum this issue can be closed, it was addressed in the following PR:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/5645

@Air-Git thank you again for your feedback and contributing to docs.microsoft.com.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
