### ISSUE TITLE
MTR creation on admin portal

### ISSUE THREAD

**Issue by c016smith** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5400]
[Enter feedback here]
Will we be able to create MTR accounts in the admin console soon? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ad37b23-8b85-a502-f176-d90586c0a1c1
* Version Independent ID: dcc4aba8-e341-4f19-cd0a-4c99cd5ef3bf
* Content: [Manage Microsoft Teams Rooms - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-manage)
* Content Source: [Teams/rooms/rooms-manage.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-manage.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@c016smith Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
