### ISSUE TITLE
Mentioned licenses (Phone system and Calling Plan) do not correspond to any licenses that I can see in the "Licenses" dashboard in the admin

### ISSUE THREAD

**Issue by ptav** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5402]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7992544-c8a5-c58f-390f-b42061f68992
* Version Independent ID: 3054f911-36b6-3360-2290-02310688dc0a
* Content: [Manage Audio Conferencing settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-the-audio-conferencing-settings-for-my-organization-in-teams)
* Content Source: [Teams/manage-the-audio-conferencing-settings-for-my-organization-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-the-audio-conferencing-settings-for-my-organization-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@ptav Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
