### ISSUE TITLE
Get-Credential not Get-Credentials

### ISSUE THREAD

**Issue by sohailmerchant** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5404]
On the sample code provided there is a typo
$credential = Get-Credentials.

It should be ``Get-Credential`` (without s)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd283f6e-3865-ed70-d663-cc461ee8ba57
* Version Independent ID: 2450d311-fc04-d8b6-b4a2-b1890ec6fc3e
* Content: [Install Microsoft Teams PowerShell - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install)
* Content Source: [Teams/teams-powershell-install.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-install.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
@sohailmerchant Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@brandber please can you check and merge when you get a chance.

**Comment by Reeced40** [comment]
@brandber Hi Brandon, could you please merge the PR if correct. Thanks.

**Comment by Reeced40** [comment]
@brandber

**Comment by scanum** [comment]
@sohailmerchant Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
