### ISSUE TITLE
Missing instructions on how to add Microsoft Teams Room device in Teams Admin Center

### ISSUE THREAD

**Issue by maheshau1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5409]
Can you please also add instructions on how to Add a Microsoft Teams Room device in Teams Admin Center? Do they automatically appear if they have Meeting Room license assigned? 

We have few Microsoft Teams Room and none of them appear in Teams Admin Center.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ad37b23-8b85-a502-f176-d90586c0a1c1
* Version Independent ID: dcc4aba8-e341-4f19-cd0a-4c99cd5ef3bf
* Content: [Manage Microsoft Teams Rooms - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-manage)
* Content Source: [Teams/rooms/rooms-manage.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-manage.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@maheshau1 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@maheshau1 thank you for reaching out and helping improve MS Docs. Please have a look at this link and let me know if it helps at all. - https://docs.microsoft.com/microsoftteams/devices/device-management

**Comment by maheshau1** [comment]
Hello @lindspea, Sorry to be a pain but it would really help others if you can please specify minumum version that MTR should be on for auto-enrollment. All of our MTR endpoints can now be seen on Teams Admin Center after an upgrade which wasn't the case when I opened this issue. Screenshot below for one of the device that shows version of OS and Teams Room App.

![image](https://user-images.githubusercontent.com/56521175/94353007-8b395800-00af-11eb-8b1f-e398053a6e1f.png)

**Comment by scanum** [comment]
@maheshau1 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
