### ISSUE TITLE
Missing: Descriptions for Mode for IP audio, Mode for IP video

### ISSUE THREAD

**Issue by SteveBurkettNZ** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5410]
Seeing a couple of settings under the **Audio & video** section of a meeting policy that aren't documented here:

- Mode for IP audio
- Mode for IP video

Options are Outgoing and incoming audio enabled / Outgoing and incoming video enabled or Disabled. How does the **Mode for IP video** setting differ from the **Allow IP video** (on/off) setting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/meeting-policies-in-teams#meeting-policy-settings---audio--video)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@bratsche Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@SteveBurkettNZ thank you for reaching out. At a quick glace I see the article was updated a few days ago. Please let me know if this information is still missing and I'll look into it further.

**Comment by scanum** [comment]
@SteveBurkettNZ  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
