### ISSUE TITLE
Change the licensing details, please. from Business Essential to Business Basics

### ISSUE THREAD

**Issue by EvgenyArtemyev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5412]
User has an Office 365 E1, E3, E5, A1, A3, A5, M365 Business, Business Premium or Business Essentials
to User has an Office 365 E1, E3, E5, A1, A3, A5, M365 Business, Business Premium or Business Basics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@EvgenyArtemyev Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@EvgenyArtemyev thank you for reaching out and helping improve MS Docs.  It looks like this has been updated in the interim. Please check and confirm from your side.

**Comment by scanum** [comment]
@EvgenyArtemyev  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
