### ISSUE TITLE
CmdLet Get-CsOnlineUser doesn't shows Teams Policies assigned to groups

### ISSUE THREAD

**Issue by etellier** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5413]
The CmdLet Get-CsOnlineUser doesn't show any Teams effectives Policies Names if they're apply/effective by groups membership ( New-CsGroupPolicyAssignment ). 
Policies names are empty.

If policies are applied by "New-CsBatchPolicyAssignmentOperation" or "Grant-CsTeamsMeetingPolicy", they are show by Get-CsOnlineUser
User's policies names applied by groups membership are show in Teams admin center 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 888fe05b-1160-452f-90ba-deb19adb740f
* Version Independent ID: 4091c5e4-7a90-7fe4-2741-16bbb1f297c1
* Content: [Attribuer des stratégies à vos utilisateurs dans Microsoft Teams. - Microsoft Teams](https://docs.microsoft.com/fr-fr/microsoftteams/assign-policies?source=docs)
* Content Source: [Teams/assign-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@etellier Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
