### ISSUE TITLE
Step 3 Not working with Direct Dial Numbers

### ISSUE THREAD

**Issue by scbates930** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5414]
[Enter feedback here]

The document refers to some differences around Direct Routing - eg no calling plan needed. 
However Step 3 does not work with direct routing as the Direct Routing numbers are not shown in the screen for Assigning the number.

I think this page needs to show how to make cap phones work for Direct Dial.

The  document is referenced from  https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan  so It would appear that Direct Routing is supported for CAP Phones. 

Many thanks
Steve

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ab5215-f24f-75cf-bb92-16ac0ff5e5ca
* Version Independent ID: 701cc58f-d2ea-cbb6-f5fc-47b9fbfb1119
* Content: [Set up the Common Area Phone license - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-common-area-phones)
* Content Source: [Teams/set-up-common-area-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-common-area-phones.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@scbates930 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
