### ISSUE TITLE
Sensitivity labels in the Microsoft Teams admin center

### ISSUE THREAD

**Issue by pratikdedhia1987** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5415]
Can we verify if the below statement is still true ? I do not see any option to set or even edit sensitivity labels from Microsoft Teams admin center. 

Sensitivity labels in the Microsoft Teams admin center
You can set sensitivity labels when you create or edit a team in the Microsoft Teams admin center. Sensitivity labels are also visible in team properties and in the Classification column on the Manage teams page of the Microsoft Teams admin center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ede6de99-ead2-fdb1-22f4-8b8240829732
* Version Independent ID: ed36687a-c091-44e3-1d8e-1025d1209fec
* Content: [Sensitivity labels for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sensitivity-labels?source=docs)
* Content Source: [Teams/sensitivity-labels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sensitivity-labels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officedocspr Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
