### ISSUE TITLE
Update on switch port functionality ETA?

### ISSUE THREAD

**Issue by oradcliffe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5418]
"Subnet and WiFi AP are supported; support for Ethernet switch/port is pending"

Do we have an idea when switch ports will be available to use for E911 location?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 358dfc73-9414-13e2-4682-c3e82603692f
* Version Independent ID: 3faae1d9-efbe-c20c-6598-a5073c2306e2
* Content: [Configure dynamic emergency calling - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/configure-dynamic-emergency-calling)
* Content Source: [Teams/configure-dynamic-emergency-calling.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/configure-dynamic-emergency-calling.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@oradcliffe Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by oradcliffe** [comment]
Just curious why you think I should open a ticket?  I am only asking on ETA for when switchport functionality will be available for E911.  I don't think a ticket will help me.

**Comment by oradcliffe** [comment]
Hi, I am still wondering if we can get some information as to when this will be supported.
