### ISSUE TITLE
Missing first steps

### ISSUE THREAD

**Issue by mwilliams7247** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5419]
While this is great information I understand to fix my issue I need to run the power shell commands. I believe the initial steps are missing to load up these tools. A link to the document on how to install these would be very helpful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@mwilliams7247 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by mwilliams7247** [comment]
Thank you. I am also on Teams only and dont see a reason to need powershell.

How to fix that would even be better!

My tenant is a test one if it helps to see the issue

________________________________

**Comment by lindspea** [comment]
@mwilliams7247 thank you for reaching out. At a quick glance I see this article has been updated in the interim. Please let me know if it's still missing something and I'll look into it further.

**Comment by scanum** [comment]
@mwilliams7247  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
