### ISSUE TITLE
Sample Normalization Rule

### ISSUE THREAD

**Issue by s1satya** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#542]
The translated number for 5digitRange example should be +14257054567

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7fd3d1-140a-0703-28f6-cc568e06e66e
* Version Independent ID: 96193258-5fb4-896a-6015-170d5cb2f35d
* Content: [What are dial plans?](https://docs.microsoft.com/en-us/SkypeForBusiness/what-are-calling-plans-in-office-365/what-are-dial-plans?redirectSourcePath=%252fen-US%252farticle%252fWhat-are-PSTN-Calling-dial-plans-2f0cfb59-1ca1-4e31-84ce-09d0b1a7ce1b)
* Content Source: [Skype/SfbOnline/what-are-calling-plans-in-office-365/what-are-dial-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/what-are-calling-plans-in-office-365/what-are-dial-plans.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@s1satya - thanks for this feedback. We will get this resolved. By the way, would you be open to submitting a Pull Request with the fix? You would then show up in the contributors list here: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/graphs/contributors

If you are open to submit a Pull Request you can find instructions in the README that shows up at the bottom of the main repo here: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness

If you are open to it I can guide you if you have any questions. Then we just get the product team to approve it and it merges into the docs with you as the contributor.

Or opening an issue like you did is always greatly appreciated too. Thanks for taking the time on this!

**Comment by kenwith** [comment]
This was resolved in PR: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/581
