### ISSUE TITLE
Missing SIP signalling IPs

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5421]
In this section
https://docs.microsoft.com/en-au/microsoftteams/direct-routing-plan-media-bypass#sip-signaling-fqdns
we have 6 public IPs listed

But in https://docs.microsoft.com/en-au/microsoftteams/direct-routing-plan#sip-signaling-fqdns
we have 8 public IPs listed.

DNS query "Resolve-DnsName sip-all.pstnhub.microsoft.com" returns 8 public IPs

This article needs updating

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10b198f4-9576-a14d-4359-1e8cc0319cda
* Version Independent ID: ba7c3252-21d4-9be1-2a84-de2d51646f7b
* Content: [Plan for media bypass with Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-au/microsoftteams/direct-routing-plan-media-bypass)
* Content Source: [Teams/direct-routing-plan-media-bypass.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan-media-bypass.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@shivtorov Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@shivtorov thank you for pointing this out and helping improve MS Docs. Please could you let me know what you would suggest adding/changing to the article and I'll check with the team for confirmation.

**Comment by shivtorov** [comment]
@lindspea, "SIP Signaling: FQDNs" section lists 6 public IPs

- 52.114.148.0
- 52.114.132.46
- 52.114.75.24
- 52.114.76.76
- 52.114.7.24
- 52.114.14.70

but it should list 8 IPs:

* 52.114.7.24
* 52.114.14.70
* 52.114.16.74
* 52.114.20.29
* 52.114.75.24
* 52.114.76.76
* 52.114.132.46
* 52.114.148.0

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
