### ISSUE TITLE
Media IP ranges

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5422]
Hi
there are 3 issues in this article:

**1) It appears in some parts of this article, newer media IP subnets are missing.** 

"Use of Media Processors and Transport Relays" section (https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan-media-bypass#use-of-media-processors-and-transport-relays) lists two subnets:
52.112.0.0/14 (IP addresses from 52.112.0.1 to 52.115.255.254)
52.120.0.0/14 (IP addresses from 52.120.0.1 to 52.123.255.254)

But in "Media traffic: IP and Port ranges" (https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan-media-bypass#media-traffic-ip-and-port-ranges) we only have one subnet listed in both "medai processors" and "transport relay" subsections:
52.112.0.0 /14 (IP addresses from 52.112.0.1 to 52.115.255.254)

**2) inconsistent use of "Microsoft 365" and "Office 365" in headers**
compare:
https://docs.microsoft.com/en-au/microsoftteams/direct-routing-plan-media-bypass#microsoft-365-office-365-and-office-365-gcc-environments-1
and
https://docs.microsoft.com/en-au/microsoftteams/direct-routing-plan-media-bypass#office-365-and-office-365-gcc-environments

**3) headers structure**
inconsistent use of level 2 and level 3 headers make structure very confusing.

just one example (second header shall be level 3 instead of level 2):
(check raw form of the below extract)

`
The IP range for media traffic is 

### Office 365 and Office 365 GCC environments

- 52.112.0.0 /14 (IP addresses from 52.112.0.1 to 52.115.255.254)

## Office 365 GCC DoD environment

- 52.127.64.0/21

### Office 365 GCC High environment

- 52.127.88.0/21
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10b198f4-9576-a14d-4359-1e8cc0319cda
* Version Independent ID: ba7c3252-21d4-9be1-2a84-de2d51646f7b
* Content: [Plan for media bypass with Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan-media-bypass)
* Content Source: [Teams/direct-routing-plan-media-bypass.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan-media-bypass.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@shivtorov Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@CarolynRowe please can you help with this one?
