### ISSUE TITLE
Incorrect Documentation related to multiple subnets example in Network Settings

### ISSUE THREAD

**Issue by nithinmulley** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5424]
*Supposed CSV file contents are shown as below with the Subnet field as Identity.
Identity, Mask, SiteID
172.11.12.0, 24, Redmond
172.11.13.0, 24, Chicago
172.11.14.0, 25, Vancouver
172.11.15.0, 28, Paris

But the Powershell code for the multiple subnets is referencing to "SubnetID" field. This either needs to be changed in the CSV file example with "Identity" replaced with "SubnetID" or in the Powershell code with "$_.SubnetID" replaced with "$_.Identity"

Also, Powershell code for multiple subnets should include a space between $_.SubnetID and -MaskBits.

Current Powershell:
`Import-CSV C:\subnet.csv | foreach {New-CsTenantNetworkSubnet –SubnetID $_.SubnetID-MaskBits $_.Mask -NetworkSiteID $_.SiteID}  `

**Change proposal:**

CSV File field updated to SubnetID:

SubnetID, Mask, SiteID
172.11.12.0, 24, Redmond
172.11.13.0, 24, Chicago
172.11.14.0, 25, Vancouver
172.11.15.0, 28, Paris

PowerShell with added space:

`Import-CSV C:\subnet.csv | foreach {New-CsTenantNetworkSubnet –SubnetID $_.SubnetID -MaskBits $_.Mask -NetworkSiteID $_.SiteID}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef19426-f330-e8ea-dd48-571954b23176
* Version Independent ID: d4357caa-b5c6-a034-3b81-f409678f5ee3
* Content: [Manage your network topology for cloud voice features in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-your-network-topology)
* Content Source: [Teams/manage-your-network-topology.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-your-network-topology.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@nithinmulley Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@LanaChin please can you have a look at this one?

**Comment by LanaChin** [comment]
Hi @nithinmulley - Thanks so much for your feedback and helping to improve our documentation. We've updated the PowerShell command in the article.
