### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5425]
FYI, this page's link doesn't work anymore.  It lands here - https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-office-365-groups?redirectedfrom=MSDN - and gives this error:

> 404 - Page not found
> Hmm, we couldn't find this link, but here are some related search results that may be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c0a619-c505-73a3-d815-58b384dc9a61
* Version Independent ID: 78b91880-6d1e-a9dc-6099-7a0a15b96a4a
* Content: [Configure an Exchange hybrid organization - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/exchange-hybrid-organization)
* Content Source: [Teams/Exchange-hybrid-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-hybrid-organization.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@JeremyTBradshaw Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@JeremyTBradshaw thank you for pointing this out and helping improve MS docs. It seems like this article has been updated in the interim and the link is working from my side. Please confirm from your side. Thanks.

**Comment by JeremyTBradshaw** [comment]
@lindspea I just checked and agree it's working now.  Thanks for checking into it.
