### ISSUE TITLE
'Team Discovery' setting does not exist

### ISSUE THREAD

**Issue by TracyGH** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5428]
According to [this article](https://docs.microsoft.com/en-us/microsoftteams/manage-discovery-of-private-teams), a 'Team discovery' section should exist under the Teams settings (see 1st screenshot).  However, the section is missing from both my developer tenant and production tenant (see 2nd screenshot).  Please advise on the UI location where I can toggle the Discoverability of Teams.  My dev tenant is set to targeted release, and production is standard.

![image](https://user-images.githubusercontent.com/38665906/88418218-13416f80-cd98-11ea-8818-a2292bc255e3.png)
![image](https://user-images.githubusercontent.com/38665906/88418272-2b18f380-cd98-11ea-8273-94b4a60776d4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5920152-5fee-41ed-56df-ad7b51b25cc2
* Version Independent ID: 88cfc850-5e36-48ee-ba99-088b2b653f1e
* Content: [Manage discovery of private teams in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-discovery-of-private-teams)
* Content Source: [Teams/manage-discovery-of-private-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-discovery-of-private-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@TracyGH Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by TracyGH** [comment]
@scanum - Thank you for the prompt response!  I can appreciate your perspective that this is a support issue.  But please be aware that I'm seeing this behavior in two separate, completely unrelated tenants.  I would technically have to open two different support requests, one for each tenant.

**Comment by TracyGH** [comment]
@scanum - Per the Microsoft support rep, the feature described in the article above was cancelled:  https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=44370.  So, the article is no longer accurate/relevant.
