### ISSUE TITLE
Update for .Net 4.7.1

### ISSUE THREAD

**Issue by CorbinMeek** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#543]
We should update this doc to explicitly call out .Net 4.7.1 - ping Terry Adams (OCS) and corbinm for validation.  We might be able to say 4.7.x (and higher) which would save us future explicit version updates.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c475b5d-09ed-7f58-86d4-27f28e33ef7a
* Version Independent ID: f0ad50f3-ea93-9424-6de8-a0b778e90b23
* Content: [Server requirements for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/server-requirements#Software)
* Content Source: [Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by kenwith** [comment]
Updated with this PR: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/546

Just to make it super clear I did what you said and put in 4.7.1 and higher.

Should be live shortly. Let us know if anything else.

**Comment by TobieFysh** [comment]
Not to be a pain but are we taking 4.7.1 and higher to mean *Any* number larger that 4.7.1 (4.8, 5 (when it arrives)).

Or to mean 4.7.x and higher?
