### ISSUE TITLE
Creating Teams enabled events from Exchange on-prem OWA

### ISSUE THREAD

**Issue by EvgenyArtemyev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5433]
AFAIK it is impossible to plan Microsoft Teams events from OWA of any version exchange servers for users with on-prem mailboxes. It would be great to add the information about it in the article.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@EvgenyArtemyev Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@EvgenyArtemyev thank you for reaching out and helping improve MS Docs. I see the article has been updated recently and there is an important note - " Important - For integration with on-premises, it's highly recommended that you have an Exchange full Classic Hybrid deployment with Exchange Server 2016 or later. Modern Hybrid support is limited to Free/Busy and will not provide calendar integration from Teams to mailboxes on-premises, for example. For more information about setting up a hybrid deployment, see Exchange Server hybrid deployments." Please let me know if this clears it up or if any other notes should be added to the article.

**Comment by EvgenyArtemyev** [comment]
Hello Lindspea.
Thanks for the update.
This phrase is great but I mentioned another important point and the update did not cover it.
I mean if an organization set up full classic hybrid the users still won't be able to plan teams events via OWA when users mailboxes are on premises 

Thank you

**Comment by lindspea** [comment]
@EvgenyArtemyev does this article help at all - https://docs.microsoft.com/exchange/exchange-hybrid

**Comment by scanum** [comment]
@EvgenyArtemyev We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by EvgenyArtemyev** [comment]
Hi there.
I think the point is quite a peculiar. Nonetheless, it is worth to add. I've got some questions about it from Microsoft Partners.
So, there is a limitation. It is impossible to plan a Teams Meeting event from Outlook on the Web on on-premises Exchange Server.
In the article above and the article https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook
we tell about some considerations. It'd be great to add the limitation to one of the article.
