### ISSUE TITLE
Remote or Local Mailbox

### ISSUE THREAD

**Issue by EvgenyArtemyev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5434]
Dear team,
Would you please clarify which type of Mailbox is required to set up.
The name of the section is "Enable the remote mailbox and set properties"
Meanwhile the cmdlet is about creating on-prem mailbox NOT remote.
Enable-Mailbox PROJECTRIGEL01@contoso.com -Room

Should it be Enable-remotemailbox?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91cd0219-b3b0-da60-6416-c6b5a67623e3
* Version Independent ID: 983d08b5-4a2c-838a-52eb-821045d2c9df
* Content: [Deploy Microsoft Teams Rooms with Exchange on-premises - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-exchange-on-premises)
* Content Source: [Teams/rooms/with-exchange-on-premises.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-exchange-on-premises.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@EvgenyArtemyev Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@LanaChin please can you help with this issue?

**Comment by LanaChin** [comment]
Microsoft Teams Rooms article. Reassigning to dstrome.

**Comment by JeremyTBradshaw** [comment]
@dstrome @LanaChin @lindspea @EvgenyArtemyev This issue is still open but no answer in here and the article remains unfixed.  Anyone know the answer - does the mailbox need to be created in Exchange Online (i.e., should it be Enable-RemoteMailbox?), or can the mailbox in fact be created and remain in on-premises Exchange?

**Comment by lindspea** [comment]
@tiburd please can you assist here?

**Comment by dstrome** [comment]
Closing old issues.
