### ISSUE TITLE
Add non powershell manual to the article

### ISSUE THREAD

**Issue by bitflusher** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5435]
It took me a while to set up an account especcially with basic auth requrements for exchange powershell modules and i was having mixed results. Only after one day I found a clear tutorial on youtube on how to do this in the office portal and exchange admin center. https://www.youtube.com/watch?v=E45VgcYweJc

My suggestion is to incorporate this in the article. This is great for initial testing of a first room or small deployments < 10 rooms. For larger deployments The current article using powershell is the way to go.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Microsoft 365 or Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-office-365)
* Content Source: [Teams/rooms/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-office-365.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@bitflusher Thanks for the feedback, we will consider adding this in documentation updates.
