### ISSUE TITLE
Technet article correction - https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events

### ISSUE THREAD

**Issue by TomasCrha** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5438]
Hello,
I wanted to comment on following article on Technet :
https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events
Section Exclusions and considerations in particular:
"China: Event team members and attendees will not be able to use Teams live events because Azure CDN is not accessible in China. A workaround is to use a company VPN connection, which gets the client connected to CDN via the customer's corporate network"

We have a documented case where it was possible for user connecting from CN geoIP without any kind of VPN tunnel, and LiveEvent service/feed was accessible for him. Although the experience was not stable, it is still technically possible for Chinese users to join the Event.

Official statement from MS:
"regarding the CN user able to join the Live Event without connecting to VPN there is a possibility that Verizon provide some media endpoints via DNS which might allow CN users to join the Live Event.

However, what we recommend is that it is not possible to join until they are connected to VPN.
"
Thanks,
Tomas
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events#related-topics)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@TomasCrha Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@TomasCrha thank you for pointing this out and helping improve MS Docs. Please could you clarify what I should put in the note that must be added to the article to help other users regarding the issue above.

**Comment by scanum** [comment]
@TomasCrha We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
