### ISSUE TITLE
Include link to preventing Teams autostart

### ISSUE THREAD

**Issue by pnwnightowl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5440]
With the instructions of doing a per-machine install for WVD, please include a note on preventing Teams from auto launching after installation with the link to : https://docs.microsoft.com/en-us/microsoftteams/msi-deployment#prevent-teams-from-starting-automatically-after-installation

I believe a lot of folks will want to do this in a WVD environment, furthermore, it solves the issue with Teams installing and running along side remote apps in WVD if Teams hasn't been installed yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi#deploy-the-teams-desktop-app-to-the-vm/)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@pnwnightowl Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@pnwnightowl thank you for reaching out. I see the article was updated a few days ago. Please have a look and let me know if you still think the link needs to be added, and where?

**Comment by pnwnightowl** [comment]
I don’t see it…  Personally, I would add reference to preventing auto launch<https://docs.microsoft.com/en-us/microsoftteams/msi-deployment#prevent-teams-from-starting-automatically-after-installation> as a NOTE at the end or beginning of this section:
https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi#deploy-the-teams-desktop-app-to-the-vm

Jeff
