### ISSUE TITLE
Network Requirements ports 80,443 

### ISSUE THREAD

**Issue by shanehoey** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5442]
I think that ports  80 & 443  should be added to the table under prepare network section,  the description does mention that the "at a minimum, in addition to normal web traffic" and while this would should be obvious to most people that 80,443 is required,  however I do think it could get missed, and table would read better if they where added to table.

I can do a pull request if you want. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d996cf7-9f48-2b30-7759-afaf3fe82caa
* Version Independent ID: 24dd6cdf-d35f-53b2-06c2-0a27891825d4
* Content: [Prepare your organization's network for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/prepare-network)
* Content Source: [Teams/prepare-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/prepare-network.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@shanehoey  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@shanehoey thank you for reaching out and helping improve MS Docs. I see this article was updated a few days ago. Please let me know if you still recommend adding your information.

**Comment by scanum** [comment]
@shanehoey Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
