### ISSUE TITLE
Skype for Business CU update KB number same for CU10, CU10HF1, CU11

### ISSUE THREAD

**Issue by suresh-solomon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5443]
Hi I noted the CU updates CU10, CU10HF1 and CU11 are marked with the same KB 3061064

https://docs.microsoft.com/en-us/skypeforbusiness/sfb-server-updates#skype-for-business-server-2015-update-history

Suresh

**Comment by scanum** [comment]
@suresh-solomon  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@suresh-solomon thank you for reaching out. Please see the note above stipulating "KB 3061064 contains all Cumulative Updates that have been released." Let me know if you need further assistance.

**Comment by scanum** [comment]
@suresh-solomon Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
