### ISSUE TITLE
GA, preview, test, do we have mess...? And support?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5444]
Hi,

On the page you say:

> Teams PowerShell is available on PowerShell Gallery in two release types.
> **General Availability (GA)**
> **Public Preview**

How do I know what version is GA? Currently it looks that 1.1.4 GA and 1.1.3 is in preview?? Which sounds strange. How previous version could be in preview? :)

Then you do have tests available as well? Current test version is 1.0.25.

How shall we understood the differences on these versions?

GA is obviously which is supported to be run on production tenant, but how about preview versions? So far, I have understood that "test versions" should not be used in production?

Is there differences between EULA on GA and public previews versions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5720e37-e8dd-1e3e-ccfa-cf4db31e8cff
* Version Independent ID: 93a36eb2-3554-0e86-e787-759eaaafe5e1
* Content: [Microsoft Teams PowerShell Overview - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-overview)
* Content Source: [Teams/teams-powershell-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-overview.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Petri-X** [comment]
@scanum 
That is a bit unexpected answer  :)
So basically you are asking me to pay money to Microsoft to get answer for these fundamental questions, and then ask me to give the answer back to Microsoft so that you could use the answer for improving Microsoft's own documentation.

I'm not sure why I must pay on this?

In my mind, it would be much more fair if Microsoft pays all of us who are doing reviews (by free) for these documents.

**Comment by brandber** [comment]
Hi @Petri-X ,

Thanks for taking the time to submit your feedback regarding several aspects of our updated PowerShell documentation. As the author of this content, I understand your points and will work on updates to address.

Thanks again for taking the time to share your feedback with us!!
