### ISSUE TITLE
Troubleshooting section would be helpful

### ISSUE THREAD

**Issue by m-wo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5445]
A troubleshooting section would be helpful for this page - e.g. we have the Teams Rooms management feature now in our Tenant in the admin panel, however none of our (Logitech) MTR devices appear, even if we reset and re-enroll them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ad37b23-8b85-a502-f176-d90586c0a1c1
* Version Independent ID: dcc4aba8-e341-4f19-cd0a-4c99cd5ef3bf
* Content: [Manage Microsoft Teams Rooms - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-manage)
* Content Source: [Teams/rooms/rooms-manage.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-manage.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@m-wo Thanks for the feedback. We will consider adding in the new documentation updates.
