### ISSUE TITLE
Specify port ranges also requires Insert Quality of Service Markers to be enabled to work properly

### ISSUE THREAD

**Issue by greganth1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5451]
Need clarification that in order for Specify Port ranges to work that Insert Quality of Service Markers also need to be enabled as they are interdependent.

To specify port ranges, next to Select a port range for each type of real-time media traffic, select Specify port ranges, and then enter the starting and ending ports for audio, video, and screen sharing. Selecting this option is required to implement QoS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Manage meeting settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@greganth1  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@greganth1 thank you for pointing this out. Are you suggesting adding a note in this article to clarify this?

**Comment by greganth1** [comment]
Yes that is correct.  A note would be great.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
