### ISSUE TITLE
Provisioning Script Link Doesn't work

### ISSUE THREAD

**Issue by nthoman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5452]
The link to download the powershell script doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Microsoft 365 or Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-office-365)
* Content Source: [Teams/rooms/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-office-365.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@nthoman  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@nthoman thank you for reaching out. Are you referring to the link in the first paragraph? I've just checked it and it works from my side. Please confirm if it's now working on your side too.

**Comment by scanum** [comment]
@nthoman We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by nthoman** [comment]
Sorry, I missed your reply. Yes I was but then realized our firewall might have been blocking it. Sorry for the wild goose chase.

Nick Thoman
Senior Systems Engineer | Information Services
Brethren Mutual Insurance Company

w: 301-739-0950; 1390<tel:301-739-0950;%201390>
m: 301-512-4554<tel:301-512-4554>
e: nthoman@bmic.com<mailto:nthoman@bmic.com>

For support requests please email: helpdesk@bmic.com<mailto:helpdesk@bmic.com>
