### ISSUE TITLE
CreateSrsMedia.ps1 cannot process if Microsoft.PowerShell_profile.ps1 is present and contains actionable content

### ISSUE THREAD

**Issue by SteveZerrSourced** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5455]
CreateSrsMedia.ps1 (1.5.1 and 1.6.0 tested) as provided here: https://docs.microsoft.com/en-us/microsoftteams/rooms/console#prepare-the-installation-media produces the following error if the user executing the script has Microsoft.PowerShell_profile.ps1 present in Documents\WindowsPowerShell and it contains actionable commands:

```
PS C:\Users\*****\Teams Rooms CreateSrsMedia> powershell.exe -noprofile -executionpolicy unrestricted -file .\CreateSrsMedia.ps1 -verbose
Transcript started, output file is C:\Users\*****\OneDrive - *****\Documents\PowerShell_transcript.S*****.EZGbDWYz.20200728163731.txt
Host OS version 10.0.19041.330
Script version 1.6.0
Downloading CreateSrsMedia... done
Validating signature for update.ps1... success.
Transcript stopped, output file is C:\Users\*****\OneDrive - *****\Documents\PowerShell_transcript.S*****.EZGbDWYz.20200728163731.txt
C:\Users\*****\Teams Rooms CreateSrsMedia\CreateSrsMedia.ps1 : Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Version".
    + CategoryInfo          : MetadataError: (:) [CreateSrsMedia.ps1], ArgumentTransformationMetadataException
    + FullyQualifiedErrorId : RuntimeException,CreateSrsMedia.ps1
```

Full transcript:
```
**********************
Windows PowerShell transcript start
Start time: 20200728161726
Username: AzureAD\*****
RunAs User: AzureAD\*****
Configuration Name: 
Machine: S***** (Microsoft Windows NT 10.0.19041.0)
Host Application: powershell.exe
Process ID: 36272
PSVersion: 5.1.19041.1
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.1
BuildVersion: 10.0.19041.1
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\*****\OneDrive - *****\Documents\PowerShell_transcript.S*****.bt01OfaZ.20200728161726.txt
Host OS version 10.0.19041.330
Script version 1.6.0
Downloading CreateSrsMedia...
done
Validating signature for update.ps1...
success.
**********************
Windows PowerShell transcript end
End time: 20200728161730
**********************
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/console)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@SteveZerrSourced Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
