### ISSUE TITLE
Please change the size limit of org-wide teams to 10K from current 5K

### ISSUE THREAD

**Issue by cyberzhu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5457]
[The up limit had been changed, please help change the Notes to avoid confusing]

![image](https://user-images.githubusercontent.com/64758362/88764122-fbf2ef80-d1a6-11ea-8db5-4f285025af26.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@cyberzhu Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@cyberzhu thank you for reaching out. Please see related issue - https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4820.  The membership limit increase to 10,000 applies only to standard teams.

**Comment by lindspea** [comment]
@scanum this can be closed thanks.

**Comment by scanum** [comment]
@cyberzhu Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
