### ISSUE TITLE
Clarify prerequisites for guest participation in a Live Event

### ISSUE THREAD

**Issue by macna** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5458]
Hello, I think that the prerequisites for guest participation in a Live Event need further clarification. I think there are two pertinent bits of information:

"It's important to know that a Microsoft 365 or Office 365 license is required to participate in a live event as an authenticated user [...] For events produced in Teams The user must be assigned a Teams license."

Presumably that means guests as well, and does that mean licensed in their own tenant and/or in the tenant hosting the event, and how does that relate to a person using a B2C Microsoft account as a guest?

Also

"For a guest to present in a live event, do the following:
- Add the user as a guest to a team.
- Have the user accept the guest invitation and join the team.
- Schedule the live event and add the guest to your event group."

Again, how/does that work for B2C Microsoft Accounts? I'm presuming not because of the license requirements?

I know a number of enterprise customers who have had the same difficulty understanding what the expected behaviour is supposed to be and in-turn getting it working properly. Clarified docs would resole that in my view.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-live-events/plan-for-teams-live-events)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@macna Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@macna thank you for reaching out. Please have a look at this link and let me know if it helps at all. - https://answers.microsoft.com/msteams/forum/all/external-presenters-in-teams-live-events/a40251d0-dc01-4d48-8332-875cc3a9c6d5?auth=1

**Comment by macna** [comment]
Hey @lindspea, that link generates a 404 unfortunately. I can see that @LanaChin has [already updated the page](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/189a07e090de14064bdc30992d3219f3fe7318b6), which does help to clarify.

I think further clarification about how (or if) this works for guests using B2C accounts is still needed. Again, I'm presuming it doesn't work because the license requirements won't be met? If that's the case it would help to say that it only works for guests who are 365 subscribers in their own tenants with appropriate licenses.

**Comment by lindspea** [comment]
@macna thank you for letting me know. @LanaChin could you help with information about B2C accounts please.

**Comment by LanaChin** [comment]
Hi @macna - thanks for reaching out. Just want to make sure I understand your questions correctly. Are you looking for clarification for whether guests who have B2C accounts can present at live events? Thanks!

**Comment by scanum** [comment]
@macna  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by macna** [comment]
Hey @scanum, apologies for the late reply. @LanaChin - that's correct. I think further clarification about how (or if) this works for guests using B2C accounts is still needed. Again, I'm presuming it doesn't work because the license requirements won't be met? If that's the case it would help to say that it only works for guests who are 365 subscribers in their own tenants with appropriate licenses.

I hear a lot of queries from orgs trying to get guest presenters into Live Events using Microsoft accounts and not being certain if it's _supposed_ to work or not.

**Comment by macna** [comment]
Hey @scanum, seems I can't reopen the issue either.
