### ISSUE TITLE
Why is the 4 hour limit of a recording segment not documented/ published?

### ISSUE THREAD

**Issue by Matt-Mueller-MSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5460]
I had an ask from my customer about what the time limit for recording meetings was. I could not find a solid answer anywhere in the docs. I reached out to other Customer Engineers, and several tell me from experience there is a 4 hour per segment recording limit. Once the 4 hours is reached the recording stops, and a new one automatically starts. this will occur 6 times total for the 24 hour meeting limit, with a few seconds of recordings lost during each transition. This should be documented on the Teams Docs so customers do no question why the recording stops and a new one starts.

**Comment by scanum** [comment]
@Matt-Mueller-MSFT Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
