### ISSUE TITLE
Change SfB numbers and location for multiple users using Set-CsOnlineVoiceUser

### ISSUE THREAD

**Issue by AlexR888AMD** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5461]
Hi, is it possible to change the SfB number and location for multiple users using the Set-CsOnlineVoiceUser powershell cmdlet ?
users moving from one location to another, so existing number and location require to be changed.

Using - Set-CsOnlineVoiceUser -Identity user@user.com -TelephoneNumber +123456789  -LocationID abcdefg123456789
sets the user with their number at a location defined by the emergency location id taken from the tenant. 
This works correctly for an individual.

I have the user names, telephone numbers assigned to users and the location id. I would guess a .csv with user and number details could work, I've hunted for a script but haven't found any to do this particular function
Many thanks in advance

**Comment by scanum** [comment]
@AlexR888AMD Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
