### ISSUE TITLE
O365 group creation not consistent across all environments

### ISSUE THREAD

**Issue by ClassANetwork** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5464]
Not sure if this is an issue in GCC High at the moment or maybe I am misunderstanding the difference between SharePoint site/Document Library, but it does not appear that creating an O365 group in GCC High will also create the associated SharePoint Online document libraries. 

For example, the documentation states:
https://docs.microsoft.com/en-us/microsoftteams/office-365-groups#how-microsoft-365-groups-work

"When you create a team, on the backend, you're creating a Microsoft 365 Group and the associated SharePoint document library and OneNote notebook, along with ties into other Office 365 cloud applications. "

I do not see these when viewing the active sites in the SharePoint Admin Center, even after 24 hours.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d86301b-ce9c-388c-e563-9e5e5c27132e
* Version Independent ID: 07e4ae23-0966-e8f3-9b7c-4f6c02569eb0
* Content: [Microsoft 365 Groups and Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/office-365-groups)
* Content Source: [Teams/Office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-groups.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@ClassANetwork Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
