### ISSUE TITLE
MTR Version for 1909 not listed in Release Notes

### ISSUE THREAD

**Issue by Jrich1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5466]
MTR version highlighted as being the minimum required for 1909, is not a version that MS have provided any release notes for. How do you obtain MTR 4.5.33.0?

Another thing to point out is that some Lenovo Hub 500 devices have been reported as having 2004 as an available update for them, yet it is not recommended to use due to issues.

Why is 2004 showing as an available update if it is not supported on MTR devices?

Cheers
Jrich1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ecd6ee6-8850-f346-5684-9c5d2444789f
* Version Independent ID: a55a7a01-211d-147a-5332-b68e1051a2a1
* Content: [Version Support - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-lifecycle-support)
* Content Source: [Teams/rooms/rooms-lifecycle-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-lifecycle-support.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Jrich1 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
