### ISSUE TITLE
Link Broken in section "Step 4: Disable hybrid to complete your migration to the cloud"

### ISSUE THREAD

**Issue by J-Fedor** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5467]
Disable hybrid to complete migration to the cloud.
https://docs.microsoft.com/en-us/MicrosoftTeams/upgrade-to-teams-execute-skypeforbusinesshybridonprem
Which is the page it is on, doesn't provide any additional information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9d75e7-638b-1738-e102-b87d95b5b51d
* Version Independent ID: d7a64df1-2d66-1ab2-9aa3-afab785bf69a
* Content: [Upgrade Skype for Business on-premises to Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/upgrade-to-teams-execute-skypeforbusinesshybridonprem)
* Content Source: [Teams/upgrade-to-Teams-execute-SkypeforBusinessHybridOnPrem.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-to-Teams-execute-SkypeforBusinessHybridOnPrem.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@J-Fedor  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@J-Fedor thank you for pointing this out. I have done a PR correcting this and it should reflect in a few days. In the meantime here is the correct link - https://docs.microsoft.com/skypeforbusiness/hybrid/cloud-consolidation-disabling-hybrid

**Comment by scanum** [comment]
@J-Fedor Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
