### ISSUE TITLE
Step 4 has a link to loops back to the same page

### ISSUE THREAD

**Issue by aamillerMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5468]
Step for has a link for "Disable hybrid to complete migration to the cloud."  It should point to this URL, it current goes back to the top of the current document which provides no relevant details.
https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/cloud-consolidation-disabling-hybrid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9d75e7-638b-1738-e102-b87d95b5b51d
* Version Independent ID: d7a64df1-2d66-1ab2-9aa3-afab785bf69a
* Content: [Upgrade Skype for Business on-premises to Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/upgrade-to-teams-execute-skypeforbusinesshybridonprem)
* Content Source: [Teams/upgrade-to-Teams-execute-SkypeforBusinessHybridOnPrem.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-to-Teams-execute-SkypeforBusinessHybridOnPrem.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@aamillerMSFT  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@aamillerMSFT Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
