### ISSUE TITLE
Page is broken

### ISSUE THREAD

**Issue by TobieFysh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#547]
The HTML on this page is broken at the moment (verified on Edge and Chrome).

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3e9b04c-e93b-7ea5-4ac7-39276428241e
* Version Independent ID: a715ee2f-c518-ffd7-1d2f-3faf264877e9
* Content: [Deploy hybrid connectivity between Skype for Business Server and Skype for Business Online](https://docs.microsoft.com/en-gb/skypeforbusiness/skype-for-business-hybrid-solutions/deploy-hybrid-connectivity/deploy-hybrid-connectivity)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/deploy-hybrid-connectivity/deploy-hybrid-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/deploy-hybrid-connectivity/deploy-hybrid-connectivity.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by kenwith** [comment]
@TobieFysh - thank you very much for taking the time to report this. We recently migrated all the content from TechNet to this open source system on GitHub and surfaced on docs.microsoft.com. This must have been a result of that migration. We are working to get this resolved. Thanks again for taking the time to report and make the docs better for the community!

**Comment by jambirk** [comment]
I just had a look at the page, and the problem seems to be resolved now. Please reopen if this isn't the case.
