### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by wru69** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5470]
[Enter feedback here]
Link under this name is not working Browse devices certified for Microsoft Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b118e0a7-1fef-feae-6c6d-e24c4485a5b9
* Version Independent ID: ae18e2db-fbbf-f30c-3c56-17dd0d2b85d1
* Content: [Phones and Devices for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/usb-devices)
* Content Source: [Teams/devices/usb-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/usb-devices.md)
* Service: **msteams**
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@wru69 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@wru69 thank you for reaching out. I've just checked the link and it works from my side. Please confirm if it's working for you now.

**Comment by wru69** [comment]
Hello,
Does not work for me.
When I’m here
https://docs.microsoft.com/en-us/microsoftteams/devices/usb-devices

And I click on the link here
[cid:image005.jpg@01D66B4F.24847FE0]

Or here
[cid:image006.jpg@01D66B4F.24847FE0]


I get this error
https://www.microsoft.com/library/errorpages/smarterror.aspx?correlationId=oNyQ/x2zPUmRL3Do.0.4.0
[cid:image007.jpg@01D66B4F.24847FE0]




Best regards,
Rytis Majauskas

**Comment by lindspea** [comment]
@wru69 thank you for coming back to me. Are you referring to the link in the document where it says - "Browse devices certified for Microsoft Teams."? The links you gave me below your explanation are JPEG images, so I'm a little confused. Please could you clarify.

**Comment by wru69** [comment]
Hello,
I thought it’s easy to understand…

Please head to
https://docs.microsoft.com/en-us/microsoftteams/devices/usb-devices

On that page please find and I click on the link here where the red arrow points in my screenshot, i.e. Teams store

[cid:image001.jpg@01D66C2B.E3D44060]

Or on the same page please find and I click on the link here where the red arrow points in my screenshot bellow, i.e. Browse devices certified for Microsoft Teams

[cid:image002.jpg@01D66C2B.E3D44060]

**Comment by lindspea** [comment]
@wru69 Sorry for the confusion but the reason why I can't see the error is I can't see the screenshots you're sending. Are you able to open this link - https://www.microsoft.com/microsoft-365/microsoft-teams/across-devices/devices?rtc=1 for the devices?

**Comment by wru69** [comment]
No, I get the error
We are sorry, the page you requested cannot be found.
The URL may be misspelled or the page you're looking for is no longer available.

**Comment by lindspea** [comment]
@wru69 Apologies, please try this one, https://products.office.com/microsoft-teams/across-devices/devices - otherwise I'll have to investigate further.

**Comment by wru69** [comment]
Does not work. The same error message

Rytis
From Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by wru69** [comment]
P.S. Tried from iPhone this time.

Rytis
From Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by lindspea** [comment]
@mattpennathe3rd please could you assist with this issue. I've checked the link from my side and all works okay, but it's not working for @wru69

**Comment by dstrome** [comment]
All links work on the page. Closing issue.
