### ISSUE TITLE
Incorrect 'Number of members in a team' information for GCC

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5472]
The "Number of members in a team" section is incorrect for non-Commercial clouds where it is still only 5,000. Can you add a caveat to the entry similar to what was done elsewhere like with "Number of people in a private chat" and "Number of people in a meeting (can chat and call in)"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by npherson** [comment]
To pile on to this, I think the limits in GCC were increased to match commercial with "Number of people in a private chat" and "Number of people in a meeting (can chat and call in)"...  Not sure about GCCH/DOD though. Might be worth confirming with the PG at the same time.

**Comment by scanum** [comment]
@npherson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@npherson thank you for reaching out and helping improve MS Docs. The article is reading correctly and has been recently updated to 10,000 which is correct. See https://techcommunity.microsoft.com/t5/microsoft-teams-blog/what-s-new-in-microsoft-teams-3rd-anniversary-edition/ba-p/1234871

**Comment by npherson** [comment]
Did you confirm that with the O365 GCC/GCC-H/DOD teams? We were told again just a few days ago from the GCC product group that the limit is still 5,000 in GCC.

**Comment by lindspea** [comment]
@LolaJacobsen please can you confirm?

**Comment by npherson** [comment]
Bringing this back up. Did we get confirmation on the current "Number of members in a team" in GCC? I haven't seen any PG announcements on my side of the field roles.

I think it would be a good to have the GCC folks do a complete review of this document... I'm also worried that maybe some of the spot that had GCC callouts with lower limits might no longer be true.

**Comment by lindspea** [comment]
@npherson I'm still waiting for confirmation from the team. Please look at this recent article as well - https://docs.microsoft.com/microsoftteams/quick-start-meetings-live-events
