### ISSUE TITLE
Assign Resource Account to AA / Call Queue via PowerShell

### ISSUE THREAD

**Issue by VladimirGluten47** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5481]
Hi,

I'm creating a script which runs through the distribution list / resource account / auto-attendant creation and configuration process. I need to assign a resource account to an existing Auto Attendant via PowerShell but don't see any documentation on this or any other page for the required commands. Could you please update this page or advise me where this can be found?

Thanks very much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by VladimirGluten47** [comment]
Hi,

Update: I have found the following page which I believe documents what I need. 
https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlineapplicationinstanceassociation?view=skype-ps
Could you please add a link to this page under "Related Information" or provide an example of this process on the Manage Resource Accounts in Teams documentation page?

Thanks!

**Comment by scanum** [comment]
@VladimirGluten47 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@VladimirGluten47 thank you for reaching out and helping improve MS Docs. I see that link is showing under Related Information so it might have been updated in the interim. Please let me know if you have any further questions.

**Comment by scanum** [comment]
@VladimirGluten47 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
