### ISSUE TITLE
Private Channel - no owner

### ISSUE THREAD

**Issue by imanboukly** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5482]
I tested what you said in the article " If a private channel owner leaves your organization or if they are removed from the Microsoft 365 group associated with the team, a member of the private channel is automatically promoted to be the private channel owner." This doesn't seems to work.

**Comment by imanboukly** [comment]
Link to article is : https://docs.microsoft.com/en-us/microsoftteams/private-channels

**Comment by scanum** [comment]
@imanboukly Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
