### ISSUE TITLE
Reference to static conference IDs needs to be removed

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5483]
Teams does not allow for static conference IDs
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f63c7ec-b784-d302-51e9-f359b2c8f89b
* Version Independent ID: 0442ca74-d4f0-e00f-714c-bcd5ad4161f1
* Content: [Reset a conference ID for a user in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/reset-a-conference-id-for-a-user-in-teams)
* Content Source: [Teams/reset-a-conference-id-for-a-user-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/reset-a-conference-id-for-a-user-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@TheBluLion Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@TheBluLion thank you for reaching out and helping improve MS Docs. I see in the note section it does mention that it is unsupported. Please let me know if you need further help.

**Comment by TheBluLion** [comment]
The entire page is inaccurate since you cannot change the conference id in teams.
The instructions published on the page can’t be completed.

﻿ -﻿ --
Eu Nice Loh
Premier Field Engineer
Office: (314) 872 5916
EuNice.Loh@microsoft.com<mailto:EuNice.Loh@microsoft.com>
IM:euloh@microsoft.com
8AM-5PM CT
[Microsoft]
﻿
If you have any feedback about my work, please let either me or my manager Annele Richards know at Annele.Richards@microsoft.com<mailto:Annele.Richards@microsoft.com>

**Comment by lindspea** [comment]
@tonysmit please can you help?

**Comment by tonysmit** [comment]
Rewrote it and removed the static ID issue.

**Comment by TheBluLion** [comment]
Thanks Tony, would it be possible to remove the entire section that begins with the heading below? It does not apply to teams and does not exist in the teams admin center, and is not on the roadmap.

Resetting the conference ID for a user



﻿ -﻿ --
Eu Nice Loh
Technical Program Manager
Office: (314) 872 5916
EuNice.Loh@microsoft.com<mailto:EuNice.Loh@microsoft.com>
IM:euloh@microsoft.com
8AM-5PM CT
[Microsoft]
﻿

**Comment by tonysmit** [comment]
@TheBluLion - The page is correct. Users > the user's Account tab > Reset Conference ID.
