### ISSUE TITLE
Voice Route has no associated PSTN Usage

### ISSUE THREAD

**Issue by dinocaputo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5485]
In step 3 we are creating a voice route but the cmdlet is incomplete.  

`PS C:\> New-CsOnlineVoiceRoute -Identity analog-interop -NumberPattern "^\+1(425)(\d{7}])$" -OnlinePstnGatewayList sbc.contoso.com -Priority 1 -OnlinePstnUsages "`

We are missing a OnlinePstnUsages as show above.  I'm not even sure step 3 is required as Step 7 defines the specific analog range and assigns it to the PSTN usage Interop

`PS C:\> New-CsOnlineVoiceRoute -Identity analog-interop -NumberPattern "^\+1(4254)(\d{6}])$"  -OnlinePstnGatewayList sbc.contoso.com -Priority 1 -OnlinePstnUsages "Interop"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea0bc170-d9d9-c17a-adc8-d37cb5fe3df5
* Version Independent ID: 3c761043-bea5-0cfb-d85e-13671ed0fe9a
* Content: [Direct Routing - Connecting analog devices - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-analog-devices)
* Content Source: [Teams/direct-routing-analog-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-analog-devices.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@dinocaputo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
