### ISSUE TITLE
Unable to obtain Windows 10 Enterprise 18362.418

### ISSUE THREAD

**Issue by Pikkon06** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5487]
Hello,

I'm working on setting up some Surface devices for our teams room consoles and we're having difficulties finding the versions of Windows the CreateSrsMedia.ps1 script is requiring. I was able to get a Surface Pro 4 image created but we are now working with a Surface Pro (2017) and the version it requires is 10.0.18362.418. I have downloaded the predecessor and successor builds in hopes that one of them worked and neither one satisfied the requirements for the teams room image. Logs are below, please advise.

Edit: CreateSrsMedia.ps1 is from the teams room console setup website provided by Microsoft (Link Below).
https://docs.microsoft.com/en-us/microsoftteams/rooms/console

Thanks

Script version 1.6.0
Downloading CreateSrsMedia...
done
Validating signature for update.ps1...
success.

D17C72A691D49A186B9F3F63645F5350F12AD90128FB037DCB693DAE010756B13C27599207AFDD9EAE34DEBE886AB36D77A0D6B6061763CDABE70D82816E6121
73191

What type of customer are you?
Please make sure you have all of the following available:

1. A USB drive with sufficient space (16GB+).
   The contents of this drive WILL BE LOST!
2. Windows 10 Enterprise media that matches your SRSv2 deployment kit.
   Enterprise customers can access Windows 10 Enterprise media from the Volume Licensing Service Center:
   http://www.microsoft.com/licensing/servicecenter
3. Any language pack (LP and/or LIP) files to be included.
   MPSA customers:         http://go.microsoft.com/fwlink/?LinkId=125893
   Other volume licensees: http://www.microsoft.com/licensing/servicecenter

Please do not continue until you have all these items in order.

Found deployment kit already downloaded.
Validating signature for SRSDeploymentKit-4.5.35.0.msi...
success.
Extracting the deployment kit...
done.
This deployment kit is built for Windows build 10.0.18362.418.
This deployment kit draws its drivers from %configsetroot%\AutoUnattend_Files\DistShare\Out-of-Box Drivers.

Please indicate what drivers you wish to use with this installation.
[ 0] Logitech SmartDock
[ 1] Crestron SR
[ 2] Polycom MSR
[ 3] Lenovo Hub 500
[ 4] LRS
[ 5] HP Slice 2.0
[ 6] Crestron Flex
[ 7] None
Selected option 0.
[ 0] Surface Pro 4
[ 1] Surface Pro (2017)
[ 2] Surface Pro 6
Selected option 1.
Downloading driver...
done
Validating signature for SurfacePro_Win10_16299_1806007_3.msi...
success.
Extracting SurfacePro_Win10_16299_1806007_3.msi...
done.
Identifying language packs...
... done identifying language packs.

Reminder: all data on the drive you select will be lost!

[ 0] Samsung Flash Drive
Selected option 0.
Your Windows installation media is version 10.0.18362.356. Your SRSv2 kit requires version 10.0.18362.418.
Your Windows installation media is version 10.0.18362.778. Your SRSv2 kit requires version 10.0.18362.418.

**Comment by scanum** [comment]
@Pikkon06 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by rizzon** [comment]
hi
did you find any solution ? I have the same prob. Unable to obtain the required version of the media.
modifying the script result on an error on installing: "window could not... [offline servicing]"

**Comment by Pikkon06** [comment]
I ended up never finding a solution for this. I tried installing the surface pro 4 version on a pro 5 and it worked fine. There was some minor firmware differences but the surface would self-install the firmware that was needed.
