### ISSUE TITLE
KDDIの「Cloud Calling for Microsoft Teams」が記載されていない

### ISSUE THREAD

**Issue by kik0220** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5488]
2020/7/28より提供開始されたKDDIの「Cloud Calling for Microsoft Teams」が記載されていません。
https://biz.kddi.com/service/cloud-data-center/cloud-calling/

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a26806ae-7525-7416-4b49-5ba49f563192
* Version Independent ID: eab3a3ee-deb6-3761-008b-cdd22e586176
* Content: [日本での利用可能性 - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-japan)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-japan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-japan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@officeglobal Could you kindly help on this issue. Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
**Bing Translate:** KDDI's Cloud Calling for Microsoft Teams, launched on July 28, 2020, is not listed.
___
@scanum it seems to be a request for an article update. I was not able to find information about KKDI's in English version

**Comment by lindspea** [comment]
@OfficeGlobal are you working on this fix?

**Comment by scanum** [comment]
Hi @lindspea There is also a request for an article update besides the language translation. Please let us know if there are any questions.

**Comment by lindspea** [comment]
@OfficeGlobal @kik0220 I can't seem to find the English version to be updated. Please can someone assist @CarolynRowe

**Comment by CarolynRowe** [comment]
What is the requested update?  I can't tell from this thread.  Depending on the request, these articles are usually only updated on PM approval.

**Comment by CarolynRowe** [comment]
Please note:  If the request is to change availability info, we can only do that on Microsoft PM approval.
