### ISSUE TITLE
Great Definitions of Product Interaction

### ISSUE THREAD

**Issue by Blessedcjc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#549]
The content helped me to understand the intricacies of using the products together and how using them stand-alone is not as efficient.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60fd4eb7-6f1a-2dfa-27db-01c3a0d00f30
* Version Independent ID: c1688075-18bf-534d-f402-ee062840d83f
* Content: [How SharePoint Online and OneDrive for Business interact with Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sharepoint-onedrive-interact)
* Content Source: [Teams/SharePoint-OneDrive-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/SharePoint-OneDrive-interact.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by kenwith** [comment]
@Blessedcjc - thanks for taking the time to provide feedback!
