### ISSUE TITLE
Mistake in French translation

### ISSUE THREAD

**Issue by delahondes** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5493]
The mistake is quite misleading because it is in the main table headers:

The English headers are "User configured/App configured" which meaning is very clear. The current French translation is "L'utilisateur est configuré/L'application est configurée"  which means "the user is configured/the app is configured" which is meaningless in this context (this mistake occurs very often alas). A proper translation would be "Configuré par l'utilisateur/Configuré par l'application" (which means "Configured by the user/Configured by the app", which is what the English title means).

**Comment by scanum** [comment]
@delahondes Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
