### ISSUE TITLE
Need updated/improved requirements to include Teams workloads

### ISSUE THREAD

**Issue by pnwnightowl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5498]
Since WVD supports Teams with the websocket client for A/V redirection and WVD pooled desktops is considered non-persistent, we need better guidance on number of users per vCPU for Teams workload.  From my own testing and from customer feedback, it appears you need 1-2 vCPU per user and 500MB to 1GB of memory to run Teams on a W10 multi-session VM when in a meeting with A/V going.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@pnwnightowl Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@pnwnightowl thank you for reaching out. I will have to ask the team about this, but in the meantime let me know if this article helps at all - https://docs.microsoft.com/windows-server/remote/remote-desktop-services/virtual-machine-recs

**Comment by scanum** [comment]
@pnwnightowl Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
