### ISSUE TITLE
Hybrid

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5499]
Please add details on how this impacts (if any) hybrid connectivity with Skype for Business server.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cea1cc-731d-bfba-3ed5-63a6339ecf88
* Version Independent ID: 7681956e-e442-07a3-7f7b-f086a0aff173
* Content: [Skype for Business Online retirement - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/skype-for-business-online-retirement)
* Content Source: [Teams/skype-for-business-online-retirement.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/skype-for-business-online-retirement.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@LanaChin please could you assist and let us know how this impacts hybrid connectivity with Skype for Business server.

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
