### ISSUE TITLE
Teams Support 1000 participants 

### ISSUE THREAD

**Issue by zubisultan79** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5500]
[the article shows 300 participants can join the audio/video calls in teams meetings, now it is changed to 1000 Participants]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by ndambrosio** [comment]
Technically it's still 300.  With the Advanced Communications add-on license you can have up to 1000 interactive participants and 20k view-only participants in overflow.

**Comment by scanum** [comment]
@zubisultan79 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
