### ISSUE TITLE
Bahrain Phone System License

### ISSUE THREAD

**Issue by twilkin4** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5507]
Could I get clarification on the availability of Dial-In numbers/audio conference license availability for Bahrain? One part of the page says it is available while another section says that it is not. The option for Bahrain dial-in is no longer available as well.

**Comment by scanum** [comment]
@twilkin4 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
