### ISSUE TITLE
yah, sure, make it complicated

### ISSUE THREAD

**Issue by copenhaus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5510]
[Enter feedback here]

I haven't begun to read all the links, but it got me thinking:  Microsoft is asking all the mom-and-pop shops to read through all of the articles (and UNDERSTAND them) they can be forced to transition to Teams one year from now.

OK, understood.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 771de21a-2a47-b204-8904-cea84d64e6ed
* Version Independent ID: d3d57584-d218-7ef2-996c-93a26f3a0f76
* Content: [Getting started with your Microsoft Teams upgrade - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/upgrade-start-here)
* Content Source: [Teams/upgrade-start-here.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-start-here.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@copenhaus Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
