### ISSUE TITLE
What numbers are valid?

### ISSUE THREAD

**Issue by mymebenha** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5512]
The docs make it sound like we can use any phone number for the caller ID but doesn't it have to be a phone number that's already in Teams such as a service number?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91203832-1661-291d-16ff-22ddf312b68b
* Version Independent ID: 03c3b60e-dbfd-e59d-8161-7485b49b1db3
* Content: [Set the Caller ID for a user - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-the-caller-id-for-a-user)
* Content Source: [Teams/set-the-caller-id-for-a-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-the-caller-id-for-a-user.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@mymebenha Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
