### ISSUE TITLE
Need to add a section to require Teams subnets inbound access to port 443 to Exchange on prem servers

### ISSUE THREAD

**Issue by Smartboss88** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5517]
To get this feature to work Exchange on prem servers need to be accessible by the Teams services.  For customer that limit inbound connection from Internet to Exchange servers, they need to open firewall port 443 from Teams services to Exchange on prem.  There is no mention in the article that this is a requirement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@Smartboss88 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Smartboss88 thank you for reaching out and helping improve MS Docs. I see this article was recently updated but I'm not sure I see anything addressing your issue. Please have another look and confirm if I should add this note : "If there are limits to inbound connection from Internet to Exchange servers, you need to open firewall port 443 from Teams services to Exchange on prem." Please confirm where this note should be added.

**Comment by scanum** [comment]
@Smartboss88  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
