### ISSUE TITLE
Modify user profile picture

### ISSUE THREAD

**Issue by Satake-0099** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5522]
Modify user profile picture
---
There is described in contradiction. In the middle of this page, it is said that "Users with mailboxes hosted on-premises <cut> can also change the user profile picture (if the Outlook on the web mailbox policy allows them to do so), ". But in the following table , "Modify user profile picture" is described as "No" for on-premise MBX. Which is correct? 

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@Satake-0099 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tiagoroxo** [comment]
@scanum I have the same question, seems we have a contradiction in the documentation.

**Comment by lindspea** [comment]
@Satake-0099 thank you for pointing this out. Please see the footnote 7- "7 Teams honors the Outlook on the web mailbox policy setting that's configured by tenant admins to control whether users can change their profile picture. If the -SetPhotoEnabled setting is turned off in the policy, users cannot add, change, or remove their profile picture. For example, if a user uploads a profile picture that's approved by your organization's IT or HR department, no action is needed. However, if a user uploads an inappropriate picture, change it according to your organization's internal policies." Let me know if you still need assistance or if something still needs to be changed in the document.

**Comment by scanum** [comment]
@Satake-0099  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
