### ISSUE TITLE
Teams Telephony Solutions posters differ between PDF/Visio

### ISSUE THREAD

**Issue by JSHooper** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5523]
Hi,

Reading through the documentation on OfficeDocs-SkypeForBusiness/Teams/teams-architecture-solutions-posters.md and I have noticed that the PDF file differs to the Visio file.

There are 5 options in the PDF:
![image](https://user-images.githubusercontent.com/66498163/89523710-3974ff80-d7db-11ea-85a4-6f9ffc6fe312.png)

There are only 4 options in Visio:
![image](https://user-images.githubusercontent.com/66498163/89523771-5a3d5500-d7db-11ea-92dd-96dd58e4973d.png)

Is it possible to get the more up to date Visio file added please?

Thanks in advance :)
James

**Comment by scanum** [comment]
@JSHooper Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@JSHooper Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
