### ISSUE TITLE
Multi-layered inaccuracies and confusion

### ISSUE THREAD

**Issue by laughey** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5525]
This page needs updating...

**_Tenant-level control for Teams was removed effective August 2018. Control access to Teams in your organization with user-level licensing. To learn more, see Manage user access to Teams._**

This is not at all accurate (to me anyways). I still have a slider to turn Teams on/off at the tenant level...in every one of our tenants. Perhaps this setting no longer accomplishes anything, but...I would argue otherwise. I have followed this guide, along with other associated links/docs, that advise how one goes about enabling Teams for each user within a tenant and yet, here we are 5 days later (just over the suggested 24-hour waiting period), and I still get the ole "You're missing out! Enable Microsoft Teams for your organization." error each time I attempt to open it. The only thing left is to change the tenant level slider from off to on, but, given the inaccuracies throughout the Microsoft cloud documentation, I question what might happen by attempting such non-existent changes. Shame on me for turning something on that doesn't exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cccdd91a-7f05-abd5-ed94-e82152b86914
* Version Independent ID: 3532d0a8-119c-f7d0-0d4f-a865ad32570f
* Content: [Manage user access to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/user-access)
* Content Source: [Teams/user-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/user-access.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@laughey Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@laughey thank you for pointing this out and helping improve MS Docs. Is this still available to you or does it look any different from your side?

**Comment by scanum** [comment]
@laughey We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by laughey** [comment]
@scanum @lindspea My apologies for not getting back sooner (clearly I have too way many things on my plate).

@lindspea Yes, the "options" are different...no more on/off slider.
