### ISSUE TITLE
Number of users in Org wide Team

### ISSUE THREAD

**Issue by Lolu8080** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5526]
The Teams training page https://docs.microsoft.com/en-us/learn/modules/m365-teams-collab-manage-teams/organization-wide-team states the number of users in an org wide team is up to 10000 this page states 5000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Lolu8080 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Lolu8080 thank you for reaching out and helping improve MS Docs. The membership limit increase to 10,000 applies only to standard teams.

**Comment by scanum** [comment]
@Lolu8080  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
