### ISSUE TITLE
Voice TSP Microsoft

### ISSUE THREAD

**Issue by ghshar** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#553]
Looks like there is a documentation error. As per the article we need to open 52.114.148.0 IP address. But what is the subnet mask for IP address 52.114.148.0. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e26faf8c-529e-b317-5934-cd41cfe8fa24
* Version Independent ID: 3ddd5d0a-6dbb-4940-1814-8346e293701b
* Content: [Plan Direct Routing](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan#infrastructure-requirements)
* Content Source: [Teams/direct-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Thank you for your feedback.  We are checking with the product team, and we'll update the doc accordingly.

**Comment by csweet89** [comment]
It's a /32 subnet. IPs ending in x.x.x.0 are still valid.
