### ISSUE TITLE
Teams Meeting Add-Ins for On-premises Exchange User

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5531]
This Article doesn't provide calrity if HWA (Hybrid Exchange Wizard) is a must for Teams users with On-premises mailboxes to use "Teams Meeting Add-ins" in outlook to setup Teams Meeting. In Note it is mentioned "The Outlook Teams add-in can be used to schedule a Teams meeting for mailboxes hosted in Exchange on-premises." which means we don't need Exchage Hybrid But later in the article it talks about setting up HMA or Exchange Hybrid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@3novsan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@3novsan thank you for reaching out and helping improve MS Docs. This article was updated this week with new information. Please have a look and let me know if you still need assistance or additional information.

**Comment by scanum** [comment]
@3novsan  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
