### ISSUE TITLE
The deleted column description remains in document.

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5532]
The Columns Highlighted in the Image Does Not Exist in the Current Environment. They are not included in both the reports on the UI and the exported CSV. Could you please update, if this document is not up to date.

![image](https://user-images.githubusercontent.com/13634805/89736890-cbb12800-daa7-11ea-8409-3ce340c96df5.png)
![image](https://user-images.githubusercontent.com/13634805/89736893-d10e7280-daa7-11ea-91d0-889b51eb968d.png)

// in actual environment
![image](https://user-images.githubusercontent.com/13634805/89736909-0024e400-daa8-11ea-9954-de4c74e0daa6.png)

Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2758a3d6-c646-dcb0-2a31-c7b9b84e780b
* Version Independent ID: 8704c9fe-f8b0-82d2-bd83-3fd1a9ad638d
* Content: [Microsoft Teams user activity report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report)
* Content Source: [Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@kefujino Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by kefujino** [comment]
I found out a commit that added these columns from commit history. These have added recently to this article. According to commit message, there are still in preview. 

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/e19a76174bea95c253cf65675a10cd64bbc03be3?short_path=fe0b52b#diff-fe0b52bf99168c1e149ec434a8c46e20

Reports in Microsoft 365 are essential for administrators to understand organizational trends. And this article is well viewed. To avoid confusion, could you please provide an additional explanation?

**Comment by lindspea** [comment]
@kefujino thank you for pointing this out. I see this article has been updated a few days ago. Please let me know if all the information in this article is reflecting the same as what you are seeing in the current environment or if there are updates that still need to be made to the document.

**Comment by scanum** [comment]
@kefujino  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
