### ISSUE TITLE
How to certify a device

### ISSUE THREAD

**Issue by ntziolis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5535]
Not sure where to ask this. How do we certify our device for Microsoft teams? Is there a specific SDK to be used to interact with the teams client? Could you point us to where we can find out more abut integration options / requirements?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b118e0a7-1fef-feae-6c6d-e24c4485a5b9
* Version Independent ID: ae18e2db-fbbf-f30c-3c56-17dd0d2b85d1
* Content: [Phones and Devices for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/usb-devices)
* Content Source: [Teams/devices/usb-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/usb-devices.md)
* Service: **msteams**
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@ntziolis Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by ntziolis** [comment]
We are not a customer, we are a dev shop that want to build for the Microsoft UC platform, but could not find any point of contact to get information. We were hoping that you could reach out internally to find out what the best point of contact is.
