### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by thomphi2** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5536]
The team template for "https://graph.microsoft.com/beta/teamsTemplates('retailManagerCollaboration')" is listed as generating the channels "Shift handoff" and "Learning"

When applying the template it create the channels "learning" and "operations"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d884cb-c126-b5dc-ff90-1a31aa61bf5b
* Version Independent ID: ed5054d7-d679-7fad-fd5d-9cd393644b9d
* Content: [Get started with Teams templates using Microsoft Graph - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-started-with-teams-templates)
* Content Source: [Teams/get-started-with-teams-templates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-started-with-teams-templates.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@thomphi2 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
