### ISSUE TITLE
Missing Scenario: AD Group Based TeamsMeetingBroadcastPolicy

### ISSUE THREAD

**Issue by Jaredsfs1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5539]
The article: https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/set-teams-live-events-policies-using-powershell 
Should be updated to include a new scenario under the first three scenarios, probably titled: “You want to disable live event scheduling for a large number of the users and allow a group of users to schedule them”
With a link to the Teams New-CsGroupPolicyAssignment Support document (https://docs.microsoft.com/en-us/powershell/module/teams/new-csgrouppolicyassignment?view=teams-ps) or an example like the below:
“
New-CSTeamsMeetingBroadcastPolicy -identity EnableBroadcastSchedulingPolicy
Set-CsTeamsMeetingBroadcastPolicy -identity EnableBroadcastSchedulingPolicy -AllowBroadcastScheduling $true
New-CsGroupPolicyAssignment -GroupId <GROUPID/UPN> -PolicyType TeamsMeetingBroadcastPolicy -PolicyName EnableBroadcastSchedulingPolicy -Rank 1 -Verbose
“

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cb395f1-fce4-2d64-c66e-36a6cd818ca6
* Version Independent ID: 79bf1d7e-8cbc-5146-dfda-a6ae38d49be7
* Content: [Use PowerShell to set live events policies - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/set-teams-live-events-policies-using-powershell)
* Content Source: [Teams/teams-live-events/set-teams-live-events-policies-using-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/set-teams-live-events-policies-using-powershell.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Jaredsfs1 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
