### ISSUE TITLE
Missing certfied headset(Jabra Evolve2 65 Mono)

### ISSUE THREAD

**Issue by lamich1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5540]
Reviewing documentation , found that there is a missing device from this list. According to the Microsoft store https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/across-devices/devices/product?deviceid=545

The Jabra Evolve2 65 Mono is Teams certified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b118e0a7-1fef-feae-6c6d-e24c4485a5b9
* Version Independent ID: ae18e2db-fbbf-f30c-3c56-17dd0d2b85d1
* Content: [Phones and Devices for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/usb-devices#certified-devices)
* Content Source: [Teams/devices/usb-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/usb-devices.md)
* Service: **msteams**
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@lamich1 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@lamich1 thank you for pointing this out and helping improve MS Docs. @mattpennathe3rd can we add this to the list please? If you send me all the details I can do the PR.

**Comment by mattpennathe3rd** [comment]
@lindspea I no longer work in this repo, so please reach out to @msdmaguire or @scanum for next steps.
