### ISSUE TITLE
In the real deployment we had, the event ID 2000 is 3000 and event ID 3001 is 2001

### ISSUE THREAD

**Issue by ray-suncor** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5541]
[In the real deployment we had, the event ID 2000 is 3000 and event ID 3001 is 2001.]

![2020-08-10_20-54-40](https://user-images.githubusercontent.com/62112707/89852321-d3c2a380-db4b-11ea-8312-7ee8b08a8aac.png)
---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c813d7c-1789-d0c9-c833-cbdd3f60e2b8
* Version Independent ID: e5b7e6a7-2f78-dd58-b450-0d173935e26c
* Content: [Deploy Microsoft Teams Rooms management with Azure Monitor - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/azure-monitor-deploy)
* Content Source: [Teams/rooms/azure-monitor-deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/azure-monitor-deploy.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ray-suncor Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by ray-suncor** [comment]
I did get 3001 event after force hardware failure, but I never got 2000 event. Is there a place to be configured on the client side?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
