### ISSUE TITLE
Documentation fault

### ISSUE THREAD

**Issue by matthewalkr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5542]
> Reduce channel noise by having only team owners post to the General channel. Go to the team and click ˙˙˙ More options > Manage Team. On the Settings tab, click Member permissions > select Only owners can post messages.

That setting is not team-wide: it is channel-specific. Instructions should be ...

> Reduce channel noise by having only team owners post to the General channel. Go to the team next to the General channel click ˙˙˙ More options > Manage channel. On the Channel settings tab under permissions > select Only owners can post messages.

**Comment by scanum** [comment]
@matthewalkr Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
