### ISSUE TITLE
[LOC]Back-Translation "Lenovo 思考センター M920 Tiny"→"Lenovo Think Center M920 Tiny"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5549]
ja-jp:https://docs.microsoft.com/ja-jp/MicrosoftTeams/rooms/requirements
![requirements_j2](https://user-images.githubusercontent.com/40815708/89983055-da6b2b00-dcb1-11ea-9186-c9a4930c8a8d.png)

en-us:https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/requirements
![requirements_e2](https://user-images.githubusercontent.com/40815708/89983041-d2ab8680-dcb1-11ea-8b88-ae1fd46d2b17.png)

Ref: [Lenovo Think Center M920 Tiny - Lenovo](https://static.lenovo.com/shop/emea/content/pdf/ThinkCentre/MSeries/2018/M920q/ThinkCentre%20M920_Tiny_DS_DE.pdf)
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5bf01435-a73b-4bf2-5845-e4cf50c4c3a2
* Version Independent ID: 166e1800-80b1-2496-7160-3040c5b23c3d
* Content: [Microsoft Teams ミーティングの要件 - Microsoft Teams](https://docs.microsoft.com/ja-jp/MicrosoftTeams/rooms/requirements)
* Content Source: [Teams/rooms/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/requirements.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officeglobal could you kindly help with this issue? Thanks!

**Comment by hyoshioka0128** [comment]
@scanum  @OfficeGlobal  - "Lenovo 思考センター M920 Tiny" is Fixed. Thanks.
Closed #5549.
