### ISSUE TITLE
[LOC]Back-Translation "ごみ箱"→"Yealink" (re-open:#4514)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5551]
re-open:#4514

ja-jp:https://docs.microsoft.com/ja-jp/MicrosoftTeams/rooms/requirements
![requirements_j2](https://user-images.githubusercontent.com/40815708/89983571-b9570a00-dcb2-11ea-9e22-530ac048956c.png)

en-us:https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/requirements
![requirements_e2](https://user-images.githubusercontent.com/40815708/89983614-ca078000-dcb2-11ea-854d-6b6e70d4c468.png)

Ref
[Yealink MVC300](https://www.yealink.com/product/microsoft-teams-room-system-mvc300II)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5bf01435-a73b-4bf2-5845-e4cf50c4c3a2
* Version Independent ID: 166e1800-80b1-2496-7160-3040c5b23c3d
* Content: [Microsoft Teams ミーティングの要件 - Microsoft Teams](https://docs.microsoft.com/ja-jp/MicrosoftTeams/rooms/requirements)
* Content Source: [Teams/rooms/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/requirements.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officeglobal could you kindly help with this issue? Thanks!

**Comment by hyoshioka0128** [comment]
@scanum  @OfficeGlobal  - "Yealink" is Fixed. Thanks.
Closed #5551.
