### ISSUE TITLE
Change in the screens / titles

### ISSUE THREAD

**Issue by magonzalezm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5553]
Right now the screenshot is misleading, in "Step 3: Configure Microsoft 365 Groups", it should say Microsoft 365‎ Groups.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams guest access checklist - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/guest-access-checklist?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@magonzalezm  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by lindspea** [comment]
@magonzalezm thank you for reaching out. Please let me know if this issue is resolved or if any changes still need to be made.

**Comment by scanum** [comment]
@magonzalezm  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
