### ISSUE TITLE
Installer Links are Continually Wrong

### ISSUE THREAD

**Issue by ekkonomix** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5558]
The download links to the installer on this page are wrong again.  Build 13565 is linked, but the latest build available elsewhere is 19173.  It's really tough on us admins when we're having to crosscheck links to see if what we're clicking on is really the latest build...or if other builds are available elsewhere.  This is the second time in recent months this has happened so it seems like this page might be forgotten in the standard process?  Perhaps consider just changing the links to point to a page where the latest builds are maintained?  Thanks so much-  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ekkonomix  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
