### ISSUE TITLE
Possible missing close squiggle brace

### ISSUE THREAD

**Issue by WillMartin58** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5564]
I believe the code for adding a private channel on behalf of a team owner using Graph may be missing a close } at the end.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e0ac38-cfff-8d8f-5345-2ae93a9fae2e
* Version Independent ID: bec44289-e9fa-4464-1601-0ca86d61e6ca
* Content: [Manage the life cycle of private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels-life-cycle-management)
* Content Source: [Teams/private-channels-life-cycle-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels-life-cycle-management.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@WillMartin58  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by lindspea** [comment]
@WillMartin58 thank you for reaching out and helping improve MS Docs. I've had a quick look through the article, but I can't see where it's missing. Could you please be a bit more specific about the location if possible.

**Comment by WillMartin58** [comment]
I received an email shortly after I submitted my note saying that the issue had been resolved.  So I assume someone fixed it …

**Comment by lindspea** [comment]
@scanum this can be closed thanks.

**Comment by scanum** [comment]
@WillMartin58 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
