### ISSUE TITLE
Spell check

### ISSUE THREAD

**Issue by NimaOghanian** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5567]
[Enter feedback here]
On third paragraph Teams spelled as Teans.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a162ef5c-3099-7f58-4178-d29e3ec2b5a7
* Version Independent ID: 6ca31e56-052d-6c62-1323-b5aaaae1f04a
* Content: [User presence in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/presence-admins)
* Content Source: [Teams/presence-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/presence-admins.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@NimaOghanian  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by RAJU2529** [comment]
@scanum . still  I can same typo error in this article

**Comment by lindspea** [comment]
@NimaOghanian thank you for reaching out and helping improve MS Docs. I've just looked through the article and can't find the typo. Perhaps it was fixed in the interim. Please can you check and let me know. Thank you.

**Comment by RAJU2529** [comment]
@SerdarSoysal . Typo error already fixed after analyzing this article. So you can close this issue.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@RAJU2529 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
