### ISSUE TITLE
Teams MSI download version in VDI environment

### ISSUE THREAD

**Issue by XixiHuang333** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5569]
[Enter feedback here]

Hi Team,
Could you please check if the MSI version in this document is latest or right version here in VDI environment?
In below link, the MSI version is 1.3.0.13565 and i am worrying about if this is latest version for VDI  environment.
https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi#install-or-update-the-teams-desktop-app-on-vdi

But i found MSI version in below link is 1.3.0.19173
https://docs.microsoft.com/en-us/microsoftteams/msi-deployment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@XixiHuang333  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by lindspea** [comment]
@XixiHuang333 thank you for reaching out and helping improve MS Docs. I see the article was updated a few days ago. Please can you check and let me know if the issue is resolved and the version is reflecting correctly.

**Comment by scanum** [comment]
@XixiHuang333 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
