### ISSUE TITLE
Requires that the Surface Hub be enrolled in the Windows Insider Program 

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#557]
When I attempted to install Microsoft Teams for Surface Hub from the Microsoft Store, I noticed a message indicating that it requires the device ben enrolled in the Windows Insider Program.  Is that correct?
The only mention of WIP that I see in this documentation is in the note at the bottom of the page regarding telemetry settings required to enroll in WIP.  
If WIP enrollment is required, the documentation should be updated to include that as a requirement, right at the top of the page.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f256cd5b-3ec8-2d55-9ae4-ff9849d52eae
* Version Independent ID: 52c2271b-df38-5dc9-c2a1-553cdf3b5496
* Content: [Deploy Microsoft Teams for Surface Hub](https://docs.microsoft.com/en-us/microsoftteams/teams-surface-hub)
* Content Source: [Teams/teams-surface-hub.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-surface-hub.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by chuckedmonson** [comment]
For clarification pertaining to the Windows Insider Programs, a note has been added in the "Install Teams for Surface Hub from the Microsoft Store" section. Thank you.
