### ISSUE TITLE
"These countries/regions and clouds aren't supported"

### ISSUE THREAD

**Issue by MacKender** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5571]
Under the section ”Regional availability" you are stating that "These countries/regions and clouds aren't supported" ==> What do you mean by "aren’t supported"? Are you saying that one will not be able to set up and hold a live event if one’s tenant is located in one of the unsupported countries/regions? Some clarification would have been nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events#regional-availability)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@MacKender  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by lindspea** [comment]
@MacKender thank you for reaching out and helping improve MS Docs. As far as I know, yes, that is what is meant by the statement in the article. Let me know if you have any suggestions to add a note for clarification for other users.

**Comment by scanum** [comment]
@MacKender Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
