### ISSUE TITLE
Current limitation with private channel tags not working

### ISSUE THREAD

**Issue by nidelius** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5572]
Full team tags are not available to use as @ mentions in private channel.
And tags in the private channel is not available:

https://microsoftteams.uservoice.com/forums/555103-public/suggestions/39895411-tagging-in-private-channels

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@nidelius  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by lindspea** [comment]
@nidelius thank you for reaching out and helping improve MS Docs. Please have a look at this link and let me know if it helps at all  - https://docs.microsoft.com/microsoftteams/manage-tags

**Comment by scanum** [comment]
@nidelius Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
