### ISSUE TITLE
Useful tip

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5573]
I'm facing this issue when attempting to help clients where Teams recording is not available in their region.

One useful command to consider adding to this article is,

Get-CsTeamsMeetingPolicy -Identity Global | FT AllowRecordingStorageOutsideRegion 

and

Set-CsTeamsMeetingPolicy -Identity Global -AllowRecordingStorageOutsideRegion $true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 896e3ed7-aaf5-ad40-9a5f-1374d85c3e82
* Version Independent ID: 253d2a6b-9225-723a-cbc1-c296c3cfd36c
* Content: [Introduction to Teams Policy-based Recording for Calling & Meetings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-recording-policy)
* Content Source: [Teams/teams-recording-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-recording-policy.md)
* Service: **msteams**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by scanum** [comment]
@Jmartinez589 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
