### ISSUE TITLE
clarification regarding this setting ' Anonymous users can join a meeting'

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5576]
Hi,

Anonymous users in this context is referred to as a non-guest users within tenant, right? Which means even if you send a teams meeting invite directly to a users, (and if they aren't added as guest) they are seen as a anonymous user?

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Manage meeting settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@xNiklasJern Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by xNiklasJern** [comment]
Hi @scanum ,
This isn't an issue more of general concern or question on the documentation? please reopen
