### ISSUE TITLE
How to achieve this using PowerShell?

### ISSUE THREAD

**Issue by M365-DenzilFernandes** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5577]
Is there a cmdlet that can export the total minutes available and used via PowerShell?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8107d4a3-a55e-4891-ee72-27f79f647a1e
* Version Independent ID: b71f24c6-b54d-8a0f-ea0e-8839ff5481a4
* Content: [Microsoft Teams PSTN minute pools report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/pstn-minute-pools-report)
* Content Source: [Teams/teams-analytics-and-reports/pstn-minute-pools-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/pstn-minute-pools-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@M365-DenzilFernandes Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
