### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by dndmann** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5580]
This is great but the direct reports do not show up in the output file. I can run the Get-AzureADUserDirectReport -ObjectId by itself and get the direct reports for the individual id. Looks like there is a user class that is being listed for the $direct or $directs values, listing all the reports for the given $user... line 55 through 65.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df365fdb-34fc-eac1-22c8-69569d0ba5ed
* Version Independent ID: dfa56cb8-6be5-9aaa-be92-a9f69ccd0507
* Content: [PowerShell script sample - Export managers and their directs - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/scripts/powershell-script-create-teams-from-managers-export-managers#export-managers-script)
* Content Source: [Teams/scripts/powershell-script-create-teams-from-managers-export-managers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/scripts/powershell-script-create-teams-from-managers-export-managers.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@dndmann  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by dndmann** [comment]
What is there a new post with the resolution?

**Comment by dndmann** [comment]
I do not see where this was resolved. Has new code example been posted somewhere else? 
This is great but the direct reports do not show up in the output file. I can run the Get-AzureADUserDirectReport -ObjectId by itself and get the direct reports for the individual id. Looks like there is a user class that is being listed for the $direct or $directs values, listing all the reports for the given $user... line 55 through 65.

**Comment by lindspea** [comment]
@SerdarSoysal can you help with this one please?

**Comment by scanum** [comment]
Hi @dndmann again, thanks for your feedback. Per Microsoft, this is something that is not supported.
