### ISSUE TITLE
Documentation should highlight that it can take up to 24h the ApplicationInstance to show up online

### ISSUE THREAD

**Issue by chrisbardon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5581]
The instructions for DR AA work, but if you create the HybridApplicationEndpoint, it seems that it can take several hours for the application to show up as a valid instance (returned from Get-CsOnlineApplicationInstance).  I just spent a couple of hours trying to get this to work (trying to figure out why the application instance wasn't appearing), only to find out that it was because the instance was still provisioning.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0703860-c3db-c723-317f-7fab164c006d
* Version Independent ID: c6384e2b-ac37-265d-8c33-f004eca97673
* Content: [Configure a resource account in Skype for Business Server 2019 - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/configure-onprem-ra)
* Content Source: [Skype/SfbHybrid/hybrid/configure-onprem-ra.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-onprem-ra.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@chrisbardon  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by chrisbardon** [comment]
The issue did resolve, but I'd suggest some changes to the docs that clarify that provisioning can be delayed.  I just submitted a PR to suggest a change.
