### ISSUE TITLE
Background video effects not allowed on old CPU without AVX2 running Windows 10

### ISSUE THREAD

**Issue by petepig** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5583]
In you paper you stated:
"The optional Background video effects are not supported on processors without an AVX2 instruction set **running on Windows 8.1 or below**."

I have an old laptop with 
- Intel(R) Core(TM) i7-3610QM CPU @ 2.30GH CPU which does not have AVX2.  
- Windows 10 Home installed

I still find I cannot use Background Video effects when using teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29a61ff5-b3a5-158d-149a-dec344060e05
* Version Independent ID: 97fac351-a283-aaa8-cde1-fbd9cf4e8504
* Content: [Hardware requirements for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/hardware-requirements-for-the-teams-app#feedback)
* Content Source: [Teams/hardware-requirements-for-the-teams-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hardware-requirements-for-the-teams-app.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by RAJU2529** [comment]
@petepig . Since  You said , your ptocessor does not support AVX2, so you cannot use , still you can't find,

**Comment by scanum** [comment]
@petepig Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
