### ISSUE TITLE
Supportability of "New Meeting Experience" on VDI

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5584]
Hello,

Microsoft Teams has released a variety of views (New Meeting Experience) to help communicate in remote work. 

New Meeting and Calling Experience in Microsoft Teams!
https://techcommunity.microsoft.com/t5/microsoft-teams-blog/new-meeting-and-calling-experience-in-microsoft-teams/ba-p/1537581

AFAIK, this feature is not compatible with Virtual Desktop Infrastructure (VDI) environments. However, I looked for various public documents, but there was no description that it doesn't apply to the VDI environment. This feature is the most attention due to the recent COVID-19 situation.  Without public documents, VDI users would spend a lot of effort searching for general information that doesn't exist just like I did.

Would you please add it to the limitation for visibility?

<Feature>
![image](https://user-images.githubusercontent.com/13634805/90349367-917df280-e074-11ea-976b-75fa550dd58e.png)

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi#known-issues-and-limitations)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@kefujino We will consider adding this to the documentation. Thank you!
