### ISSUE TITLE
List of possible "Blocked reason" 

### ISSUE THREAD

**Issue by DevJonBirkett** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5586]
[Enter feedback here]
Hi, 
Would be useful to have a list of all the possible the blocked reasons. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d203675-1231-e284-acb3-1191058f651a
* Version Independent ID: 9a41d6e8-0f65-1823-6146-c08e7967ce1a
* Content: [Microsoft Teams PSTN blocked users report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/pstn-blocked-users-report)
* Content Source: [Teams/teams-analytics-and-reports/pstn-blocked-users-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/pstn-blocked-users-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@DevJonBirkett Thanks for the feedback, we are currently investigating this issue.

**Comment by lindspea** [comment]
@LanaChin please can you let me know if this is possible?

**Comment by msmikedavis** [comment]
It's not possible as we usually block users to prevent fraud/abuse. Providing a list of reasons why we blocked the user would tip our hand to fraudsters on which things we watch/monitor to stop fraud/abuse.

**Comment by LanaChin** [comment]
Closing issue.
