### ISSUE TITLE
MEM Endpoint Security - Defender Firewall - Allow Microsoft Teams ?

### ISSUE THREAD

**Issue by TechTrooper** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5589]
Please update article with instructions on how to add Teams exception to Windows Defender Firewall with MEM (Intune) Windows 10 management.

It's counter intuitive that admins have to run powershell scripts to create firewall exceptions for Microsoft's own products.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients#sample-powershell-script---inbound-firewall-rule)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@TechTrooper  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@TechTrooper Thank you for reaching out and helping improve MS Docs. Please have a look at this link and let me know if it helps 
 - https://docs.microsoft.com/windows/security/threat-protection/windows-firewall/create-windows-firewall-rules-in-intune

**Comment by scanum** [comment]
@TechTrooper Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
