### ISSUE TITLE
Shifts Activities - Typo for RequestCanceled?

### ISSUE THREAD

**Issue by buildbod** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5590]
The Office 365 Audit is returning activities for Microsoft Teams > Shifts > Request Cancelled as "RequestCancelled" yet the Docs page lists the activity as "RequestCanceled"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e51e97-ff97-c5eb-6517-21ce9a563ca4
* Version Independent ID: d3dc21b2-d90a-fbe7-8473-fff0b55feafb
* Content: [Search the audit log for events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audit-log-events#shifts-in-teams-activities)
* Content Source: [Teams/audit-log-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audit-log-events.md)
* Service: **msteams**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@buildbod Thanks for heads up. I'll fix the documentation.

**Comment by buildbod** [comment]
Fab. Thank you.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
