### ISSUE TITLE
URL linking to cmdlet help for New-CSOnlineSession is invalid

### ISSUE THREAD

**Issue by cimares** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5591]
The link to new-csonlinesession points to https://docs.microsoft.com/en-us/powershell/module/teams/new-csonlinesession?view=teams-ps which returns a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 173b5929-529b-938b-b6ab-59f05a5d69a8
* Version Independent ID: 0a3dfe5e-938f-933d-637e-b7449e3b8aa5
* Content: [Microsoft Teams PowerShell Release Notes - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes)
* Content Source: [Teams/teams-powershell-release-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-release-notes.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
@cimares  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@cimares thank you for pointing this out. Is this the correct link that should be there ? https://docs.microsoft.com/powershell/module/skype/new-csonlinesession?view=skype-ps

**Comment by lindspea** [comment]
> That's from the old Skype Module document.. looking at the link, it's correct and in keeping with every other cmdlet listed on this page, but there's no Teams specific content available at it, hence the 404 error.
> 
> Whilst the skype content is valid, it should really be created as a new page under the Teams modules URL.

Thanks @cimares, I will follow up and get back to you soonest.

**Comment by lindspea** [comment]
@brandber please can you have a look at this issue? I can only find the link that applies to the Skype Module document not Teams.

**Comment by lindspea** [comment]
@cimares it seems like the article has been updated with the information. Please confirm so we can close the issue. Thanks again.
