### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jzablin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5594]
There is a typo under the chart that shows different statuses. It says Teans instead of Teams 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a162ef5c-3099-7f58-4178-d29e3ec2b5a7
* Version Independent ID: 6ca31e56-052d-6c62-1323-b5aaaae1f04a
* Content: [User presence in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/presence-admins)
* Content Source: [Teams/presence-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/presence-admins.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@jzablin  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by cichur** [comment]
Fixed and published. https://docs.microsoft.com/en-us/microsoftteams/presence-admins
