### ISSUE TITLE
Question about auto-assignment

### ISSUE THREAD

**Issue by oradcliffe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5595]
Is there any auto-assignment functionality built in?  If I have a user in one city, will MS attempt to give them the closest bridge?  I haven't seen any documentation to confirm this behavior but testing seems to indicate there is something going on behind the scenes for assignment.

**Comment by scanum** [comment]
@oradcliffe Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
