### ISSUE TITLE
Unable to obtain Windows 10 Enterprise version 10.0.18362.418

### ISSUE THREAD

**Issue by sillysampiper** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5596]
Piggy packing off an issue that was originally raised for Windows 10 Ent 10.0.18362.356 that has not been resolved:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4181

Hi @dstrome 

Hoping for some clarity / a solution for deploying a MTR console from the latest CreateSrsMedia.ps1 script.

- What version of Windows 10 Enterprise is required for both the the Windows 10 machine used to create the Microsoft Teams Rooms installation media, and the Windows 10 media that will be used to deploy the MTR console onto the required 32GB USB / storage? 

As of today [the current script](https://go.microsoft.com/fwlink/?linkid=867842) (listed as Version 1.6.0) bounces back with this message: **_This deployment kit is built for Windows Build 10.0.18362.418_**.

I'm using **_SW_DVD9_Win_Pro_10_1909.4_64BIT_English_Pro_Ent_EDU_N_MLF_X22-28609_** from **VLSC** on both the  **Windows 10 machine used to create the Microsoft Teams Rooms installation media** and the **Windows 10 media that will be used to deploy the MTR console**.

On the Configure a [Microsoft Teams Rooms console](https://docs.microsoft.com/en-us/microsoftteams/rooms/console#prepare-the-installation-media) page it shows:

_The Windows 10 machine used to create the Microsoft Teams Rooms installation media must be on the same or later version of Windows as the target installation media._

**SW_DVD9_Win_Pro_10_1909.4_64BIT_English_Pro_Ent_EDU_N_MLF_X22-28609** is Windows Build 10.0.18362.778 (latest version of 1909 on Microsoft Volume Licensing).

**Comment by scanum** [comment]
@sillysampiper Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by sillysampiper** [comment]
Damn.
