### ISSUE TITLE
What is the new diagnostic logging information?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5597]
Hi team,

Looks like you have no description of the new logging configuration on Teams:

![image](https://user-images.githubusercontent.com/43988151/90503613-653ba200-e158-11ea-80ae-a17236b05bc4.png)

Can you please explain, what does this means

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d5e6d3-b7e0-d79f-0dea-ed423186a157
* Version Independent ID: ec6e68aa-552f-ab45-3c8e-92eff526b173
* Content: [Use log files in troubleshooting Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/log-files)
* Content Source: [Teams/log-files.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/log-files.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Petri-X** [comment]
@scanum 
Unfortunately I need to say: I disagree your response. 

This is a clear documentation issue. You have new configuration feature on Teams, which impacting directly to the topic of this page, which you are controlling.

So may I ask you to explain, why I need to pay money to Microsoft to get answer of missing documentation. And then I give the same answer back to Microsoft, so that they can improve their documentation. Don't you see a problem on this?

**Comment by SerdarSoysal** [comment]
@Petri-X thanks again for pointing this out. The setting controls what logs are captured for diagnosing meeting experiences. I need to validate a few things on our end (specifically exactly which logs this setting affects), and then we will revise this topic accordingly. 

@scanum I'm going to reopen and assign this one to myself. Will respond back here and close once we have the PR to update the topic.

**Comment by Petri-X** [comment]
@SerdarSoysal 
Is it possible to ask at the same time, if we could also convert the .blog files to text files? For example the *.blog files under "Teams\Media-Stack". So far I have understood those are ULOG2 format, but not success to make them readable again.

**Comment by Petri-X** [comment]
Hi @SerdarSoysal ,
Thank you for your effort, looks like you have find the way to get that page updated. Huge thanks for that.

But, I'm still wishing that you could publishing a tool to convert those logs files to readable format. That would be great announcement on MSIgnite! Of course not too many people are interested to that, but would be great news for those who are crying today, because we had Snooper for doing a real troubleshooting with Skype calls. Now we have nothing.

**Comment by scanum** [comment]
@Petri-X  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
