### ISSUE TITLE
Teams Room license doesn't give an option to dial out from a meeting

### ISSUE THREAD

**Issue by NikitaSkitsko** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5598]
The documentation says it's possible to “Initiate an ad hoc meeting and dial out from a meeting to phone numbers”. It's possible to initiate an ad hoc meeting using "Join Now" buttton, but it's not possible to invite someone to the meeting that is initiated by the organizer, who doesn't have an Audio Conferencing license.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-licensing.md)
* Service: **skype-for-business-online**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@NikitaSkitsko Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@NikitaSkitsko Thank you for pointing this out. What would you suggest or change in the article? Thanks.

**Comment by scanum** [comment]
@NikitaSkitsko We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by NikitaSkitsko** [comment]
This is the scenario which is not valid: 

Initiate an ad hoc meeting and dial out from a meeting to phone numbers | Meeting Room SKU | Skype for Business Standard CALSkype for Business Server Enterprise CAL
-- | -- | --

I would replace it like this:

Dial out from a meeting to phone numbers | Meeting Room SKU, **Audio Conferencing license for the meeting organizer** | Skype for Business Standard CAL Skype for Business Server Enterprise CAL
-- | -- | --
