### ISSUE TITLE
Misleading instructions

### ISSUE THREAD

**Issue by DavidSchrag** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5600]
The article suggests that you can either e-mail the PSTN service desk directly or create a support ticket through the M365 admin center. I chose to create a support ticket, and I received the following response:

CASE: 
•	Request to port all of our existing numbers from Mitel to Teams.
 
PROPOSED SOLUTION:
•	For any Port order related issue, we highly recommend you to contact directly with our MS PSTN Service desk at ptn@microsoft.com (United States and Canada) for further assistance. 
•	Reference articles you may also check.
o	Transfer phone numbers to Microsoft Teams https://docs.microsoft.com/en-us/microsoftteams/phone-number-calling-plans/transfer-phone-numbers-to-teams
o	Manually submit a port order https://docs.microsoft.com/en-us/microsoftteams/phone-number-calling-plans/manually-submit-port-order
o	Phone number management for the U.S. https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization/phone-number-management-for-the-u-s
o	What's the status of your port orders? https://docs.microsoft.com/en-us/microsoftteams/phone-number-calling-plans/port-order-status
o	PSTN Service Desk contact information https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk

So there seems to be no benefit to opening a case through the admin center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca4cd82c-d4e0-fd46-a9d6-19c46e217b7a
* Version Independent ID: d4a536ae-1f0d-fab5-4617-a414b829374a
* Content: [Manually submit a port order - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/phone-number-calling-plans/manually-submit-port-order)
* Content Source: [Teams/phone-number-calling-plans/manually-submit-port-order.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phone-number-calling-plans/manually-submit-port-order.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@DavidSchrag Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@DavidSchrag thank you for reaching out and helping improve MS Docs. I see the article was updated a few days ago. Does it help at all or is the same issue occurring?

**Comment by DavidSchrag** [comment]
The article still suggests that you can submit a service request through the Office 365 Admin Center. If my experience is typical, and the O365 support staff is simply going to reply by directing you back to the same documentation and advising you to e-mail the PSTN Service Desk, then I don't see what the benefit is of creating the service request. If there's no benefit, then the instruction should be removed.

**Comment by lindspea** [comment]
@LanaChin please can you assist here?

**Comment by LanaChin** [comment]
Thank you @DavidSchrag for your feedback and helping to improve our documenation. We've updated the article to remove that section.
