### ISSUE TITLE
AudioCodes Analogue Device names

### ISSUE THREAD

**Issue by joelulrich** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5602]
Should the Audiocodes Analogue device names closer reflect the product name?

i.e 
ATA-1 could be MP-1XX, 
ATA-2 could be MP-20X

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1a1c01-10a9-7f69-1c7b-1a566b0f5112
* Version Independent ID: 329ee759-40fc-98fb-b91e-87786c63024b
* Content: [Session Border Controllers certified for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-border-controllers)
* Content Source: [Teams/direct-routing-border-controllers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-border-controllers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@joelulrich Thanks for the suggestion to the documentations. We will cosnider adding this.
