### ISSUE TITLE
Shifts activities - lists SchedulingGroupEdited but audit returns ScheduleGroupEdited

### ISSUE THREAD

**Issue by buildbod** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5603]
There might be a typo in the Shifts activities list. It lists SchedulingGroupEdited but the Office Management Audit api returns ScheduleGroupEdited e.g. 

![image](https://user-images.githubusercontent.com/13903544/90578843-33f4bd80-e1bc-11ea-825f-c503c212363e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e51e97-ff97-c5eb-6517-21ce9a563ca4
* Version Independent ID: d3dc21b2-d90a-fbe7-8473-fff0b55feafb
* Content: [Search the audit log for events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audit-log-events#shifts-in-teams-activities)
* Content Source: [Teams/audit-log-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audit-log-events.md)
* Service: **msteams**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@buildbod Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by markjjo** [comment]
@buildbod Fixed. I also did a quick pass on all operation names for shift activities and made a few more updates. Please submit a pull request if you find any more errors in auditing operation names. Thanks in advance.

**Comment by markjjo** [comment]
Updated topic should be published by this afternoon.
