### ISSUE TITLE
Clean up and redeployment procedure: impossible for deployments

### ISSUE THREAD

**Issue by denisrennes** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5604]
https://docs.microsoft.com/en-us/microsoftteams/msi-deployment#clean-up-and-redeployment-procedure
"
Clean up and **redeployment** procedure
1.     Uninstall the Teams app installed for every user profile. For more information, see Uninstall Microsoft Teams.
2.     Delete the directory recursively under %localappdata%\Microsoft\Teams\.
3.     Delete the HKEY_CURRENT_USER\Software\Microsoft\Office\Teams\PreventInstallationFromMsi registry value.
4.     Redeploy the MSI package to that particular computer.
"

"Deployment" or "redeployment" of a software application means automatic installation **to many machines**, for example using SCCM.
This procedure is impossible to **deploy** because step 4. is a per-machine installation and step 1. is a per-user uninstallation to do for every user of the machine and, as far as I know, this cannot be done in a per-machine installation script. (Steps 2. and 3. could be done in a per-machine installation but only after step 1. is done for every user of the machine.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Teams using Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment#feedback)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@denisrennes Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
