### ISSUE TITLE
Microsoft Teams Intranet Portal app - Links in page is opening in separate browser instead of opening in Teams app

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5605]
Created intranet portal app using the documentation: https://docs.microsoft.com/en-us/microsoftteams/teams-standalone-static-tabs-using-spo-sites . But some of the links(Site pages in same site collection) are opening in separate browser instead of opening in Teams app. Any known issue or solution for this case?

**Comment by scanum** [comment]
@SubbaReddi Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
