### ISSUE TITLE
close session from cmd in teams

### ISSUE THREAD

**Issue by ortiga88** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5608]
How can I close the session with cmd with a command I have seen that it can be started ?

`  "% USERPROFILE% \ AppData \ Local \ Microsoft \ Teams \ Update.exe" --processStart "Teams.exe"`

**Comment by scanum** [comment]
@ortiga88 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
