### ISSUE TITLE
No updated

### ISSUE THREAD

**Issue by spiddeer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#561]
Missing version 4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47e1d48a-bd57-205c-d4b4-4fbd0940623a
* Version Independent ID: ec8ea898-ee36-f3ac-b5be-e272d3273430
* Content: [Release notes](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/srs2-release-note)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/srs2-release-note.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/srs2-release-note.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by davgroom** [comment]
Hi, Are you referring to update version 4.0.8.0?

**Comment by spiddeer** [comment]
Yes that's correct

**Comment by davgroom** [comment]
We published a new SRSCreateMedia script that will automatically pull down 3.1.115.0.msi when executed.  I expect that we'll have a 4.0.x.0.msi version posted in the next few weeks.

**Comment by jambirk** [comment]
So I think that addresses the concern: version 4 isn't missing as much as it has yet to be officially released.
