### ISSUE TITLE
Incorrect Command in code snippet

### ISSUE THREAD

**Issue by tgskiman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5610]
In the https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-install#sign-in section the first line of code references "Get-Credentials" as opposed to the proper "Get-Credential" command.

Is: $credential = Get-Credentials
Should be: $credential = Get-Credential

Also, the subsequent commands reference the parameter "-Credentials" and it should be "-Credential".

Thanks!
Tim

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd283f6e-3865-ed70-d663-cc461ee8ba57
* Version Independent ID: 2450d311-fc04-d8b6-b4a2-b1890ec6fc3e
* Content: [Install Microsoft Teams PowerShell - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-install)
* Content Source: [Teams/teams-powershell-install.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-install.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
@tgskiman Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@tgskiman thank you for reaching out and helping improve MS Docs. It looks like the error has been fixed in the interim. Please can you check and let me know from your side. Thanks again!

**Comment by scanum** [comment]
@tgskiman Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
