### ISSUE TITLE
Headset Pro 930 MS Duo is a device certified for Teams

### ISSUE THREAD

**Issue by tiagoroxo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5615]
Can you please confirm if the Headset Pro 930 MS Duo is a device certified for Teams?

Arcoding to the list below it's not certified:
https://docs.microsoft.com/en-us/microsoftteams/devices/usb-devices
Acording to the list below it's certified:
https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/across-devices/devices/product?deviceid=69
https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/across-devices/devices/category?devicetype=36&filterIds=27&page=1&sortBy=3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b118e0a7-1fef-feae-6c6d-e24c4485a5b9
* Version Independent ID: ae18e2db-fbbf-f30c-3c56-17dd0d2b85d1
* Content: [Phones and Devices for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/usb-devices)
* Content Source: [Teams/devices/usb-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/usb-devices.md)
* Service: **msteams**
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@tiagoroxo Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
