### ISSUE TITLE
How to verify success

### ISSUE THREAD

**Issue by angiurgiu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#562]
With regards to "Verify your success" - how can we be sure that OAuth was used, and not Basic authentication? The Skype for Business client has the user's credentials, which can be used for Autodiscover.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19d818da-830e-c813-08af-6192eb403ccc
* Version Independent ID: 575c0a11-f6e1-c571-4ad4-d490915faa15
* Content: [Configure OAuth between Skype for Business Online and Exchange on premises](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/integrate-with-exchange-server/oauth-with-online-and-on-premises)
* Content Source: [Skype/SfbServer/deploy/integrate-with-exchange-server/oauth-with-online-and-on-premises.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/integrate-with-exchange-server/oauth-with-online-and-on-premises.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by rgsteele** [comment]
The procedure in this article is for configuring server-to-server OAuth between SfB Online and Exchange on-premises. It has no bearing on client-to-server communications.
