### ISSUE TITLE
Phone System not supported in Teams Island mode?

### ISSUE THREAD

**Issue by HandyAndyOnGitHub** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5621]
Hi guys, I don't believe the line;"Phone System is not supported in Teams in Islands mode; in this mode, the only Enterprise Voice client is Skype for Business" is correct.  We are successfully running Microsoft 365 Phone System with users in "Island" mode with calls being answered in the Teams client.  We do use direct routing for our external lines, through a hosted SIP gateway - perhaps that's why it's working for us?

Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d53d0cb0-90a6-5932-f78e-7de6fcc4d481
* Version Independent ID: 3d468027-cc37-5199-32ec-819bf62b2caa
* Content: [Interoperability between Skype for business and Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability)
* Content Source: [Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@HandyAndyOnGitHub Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@HandyAndyOnGitHub thank you for pointing this out and helping improve MS Docs. @LanaChin please can you help answer this question. Should I change the wording in the doc? Is this capability only available in the instance for direct routing?

**Comment by LanaChin** [comment]
@HandyAndyOnGitHub - I've confirmed with the product team that Phone System isn't supported in Teams in Islands mode.  Thanks for reaching out.
