### ISSUE TITLE
[LOC]Back-Translation "Microsoft Teams の会議室"→"Microsoft Teams Rooms"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5623]
ja-jp: https://docs.microsoft.com/ja-jp/microsoftteams/rooms/microsoft-teams-rooms-premium
![microsoft-teams-rooms-premium_j](https://user-images.githubusercontent.com/40815708/90845458-1765aa80-e3a1-11ea-9413-f9a0cf200f4e.png)

en-us: https://docs.microsoft.com/en-us/microsoftteams/rooms/microsoft-teams-rooms-premium
![microsoft-teams-rooms-premium_e](https://user-images.githubusercontent.com/40815708/90845472-1d5b8b80-e3a1-11ea-9a1d-333d3e3f2ee8.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8f76bc0c-a899-b572-588a-b86acae1b740
* Version Independent ID: 3c5b6414-c796-7e50-9e03-b578c7995071
* Content: [Microsoft Teams の会議室管理サービス - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/rooms/microsoft-teams-rooms-premium)
* Content Source: [Teams/rooms/microsoft-teams-rooms-premium.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/microsoft-teams-rooms-premium.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@OfficeGlobal Could you please assist with this issue? Thanks!

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum the article was HumanTranslated. "Microsoft Teams Rooms" reverted to English

**Comment by hyoshioka0128** [comment]
@OfficeGlobal @scanum - "Microsoft Teams Rooms" has been Fixed. Thanks.
Closed #5623.
