### ISSUE TITLE
[LOC]Back-Translation "Microsoft Teams の会議室"→"Microsoft Teams Rooms"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5624]
ja-jp: https://docs.microsoft.com/ja-jp/microsoftteams/rooms/microsoft-teams-rooms-premium-rbac
![microsoft-teams-rooms-premium-rbac_j](https://user-images.githubusercontent.com/40815708/90845731-a1157800-e3a1-11ea-9e98-f1185d60ba2a.png)

en-us: https://docs.microsoft.com/en-us/microsoftteams/rooms/microsoft-teams-rooms-premium-rbac
![microsoft-teams-rooms-premium-rbac_e](https://user-images.githubusercontent.com/40815708/90845752-a96db300-e3a1-11ea-9898-5de72cb3b1e5.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 550c980f-74b4-0657-4732-03fe02f27a1e
* Version Independent ID: e2bc6fe7-0b93-10f5-5c0a-e89d5af541d0
* Content: [Microsoft Teams Room Premium サービスによる役割ベースのアクセス制御 - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/rooms/microsoft-teams-rooms-premium-rbac)
* Content Source: [Teams/rooms/microsoft-teams-rooms-premium-rbac.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/microsoft-teams-rooms-premium-rbac.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@OfficeGlobal Could you please assist with this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @scanum the article was HumanTranslated. "Microsoft Teams Rooms" reverted to English

**Comment by hyoshioka0128** [comment]
@OfficeGlobal @scanum - "Microsoft Teams Rooms" has been Fixed. Thanks.
Closed #5624.
