### ISSUE TITLE
Please add support stance for SIP and UPN mismatch scenario 

### ISSUE THREAD

**Issue by howardzhangmsft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5625]
Please add a statement under this section <Prerequisites specific to Microsoft Teams Rooms> to mention that Microsoft Teams Room doesn't support SIP and UPN mismatch 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f7e3603-9bec-acfc-1854-2c1275950cde
* Version Independent ID: 2aed2376-277a-3e93-5000-e509ff53434d
* Content: [Authentication in Microsoft Teams Rooms - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-authentication)
* Content Source: [Teams/rooms/rooms-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-authentication.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@howardzhangmsft Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by howardzhangmsft** [comment]
Hi team,

per below DCR, SIP and UPN mismatch is not supported for Microsoft Teams Room

https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/898091<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdomoreexp.visualstudio.com%2FMSTeams%2F_workitems%2Fedit%2F898091&data=02%7C01%7Chowzhang%40microsoft.com%7Cb458dae815c4491c588408d845b23363%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637335978969902553&sdata=RJDm5h%2FHcdW7r783wX7BcOt6VB3qctpJvnimRS01uBA%3D&reserved=0>


Best regards,

Huayong Zhang
Support Escalation Engineer - Skype for Business & Microsoft Teams
+86 (21) 52637942
howzhang@microsoft.com<mailto:howzhang@microsoft.com>
Working Hours: M-F 9:00am – 6:00pm UTC+08:00

[cid:image001.png@01D67A67.4546B410]

Nothing can stop a team.
Work remotely with Microsoft Teams<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fproducts.office.com%2Fen-us%2Fmicrosoft-teams%2Fgroup-chat-software%3Fms.url%3Dmicrosoftcomteams%26rtc%3D1&data=02%7C01%7Chowzhang%40microsoft.com%7Ca62348b8296d4332005208d7e07a9875%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637224694511372229&sdata=4q1lYPtS8IyC8MlSCDW6m8NsAx1gKSzuAd45wdMhqGA%3D&reserved=0>.

**Comment by lindspea** [comment]
@howardzhangmsft thank you for reaching out and helping improve MS Docs. That link you provided seems broken. Please can you resend and also let me know under which heading you suggest adding the note.

**Comment by howardzhangmsft** [comment]
@lindspea Please add this to the prerequisites section below:

https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-authentication#prerequisites-specific-to-microsoft-teams-rooms

The DCR link is as follows:
https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/898091

I have just double checked with engineering team who confirms that for MTR devices, we will not support different SIP and UPN.
Customer should create room account with same UPN and SIP for it to work.

**Comment by lindspea** [comment]
@LanaChin

**Comment by lindspea** [comment]
@scanum this can be closed thanks.
