### ISSUE TITLE
Procedure for Adding Teams Does Not Work

### ISSUE THREAD

**Issue by michaelbunney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5629]
The "Add" section says you can add a team by:

(1) going to the Teams admin center;
(2) navigating to **Teams** > **Manage teams**; and
(3) clicking **Add**.

But there is no **Add** button or link.  I am a Global Administrator so I have the necessary permissions, but all I see on the Manage Teams page is some user counts and the message "No teams are available in this organization."

The toolbar shown in your illustration does not exist.  Nor is there a list of teams--not even an empty one.  There is not a single actionable or clickable control on the whole Manage Teams panel of the Manage Teams page (https://admin.teams.microsoft.com/teams/manage).

Screen shot:

<img width="887" alt="temp" src="https://user-images.githubusercontent.com/26583301/90935208-98c83780-e3b7-11ea-8eeb-94ad0a497f7f.png">

Thanks,
Mike

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b51b67a-d89c-723f-3520-87cb2dc93b90
* Version Independent ID: 78d10cbc-d75b-2b02-d49c-2c3fe1579807
* Content: [Manage teams in the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-teams-in-modern-portal)
* Content Source: [Teams/manage-teams-in-modern-portal.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-teams-in-modern-portal.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@michaelbunney Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by michaelbunney** [comment]
Or you could document how to create a team in a tenant that does not yet have a team.
