### ISSUE TITLE
Put the latest updates at the beginning of the document

### ISSUE THREAD

**Issue by rbalsleyMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5631]
Having the latest updates at the bottom of the document means having to scroll quite a bit to see what's changed. It'd be more helpful to put the latest updates at the top of the document. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3081f70c-d927-ce5d-d957-ca7ba7e07a55
* Version Independent ID: 17704162-7ff9-015c-30a1-1cbc078f0782
* Content: [Microsoft Teams content updates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-updates)
* Content Source: [Teams/teams-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-updates.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@rbalsleyMSFT Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@rbalsleyMSFT thank you for reaching out. Unfortunately, these updates are generated automatically each week and I don't have the permissions to update in the correct order. This is however on the teams radar to be fixed in the near future.

**Comment by scanum** [comment]
@rbalsleyMSFT Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
