### ISSUE TITLE
"Workload" Prerequisites Are Ambiguous

### ISSUE THREAD

**Issue by michaelbunney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5632]
This page implies—but does not clearly state—that deploying Microsoft 365 "workloads" is a prerequisite for deploying Teams, but the page it directs us to for details ("Getting Started") does not explain.  In fact, it doesn't even mention the word "workload".

Several things are unclear here:

1. Are M365 workloads, in fact, a prerequisite for Teams?  This page is ambiguous.  It says if you haven't deployed M365 workloads, see "Get Started".  But it doesn't actually say they are required.

2. What is a Microsoft 365 "workload"?  I can't find a definition online.

3. Which specific workload(s) are required prerequisite(s) for Teams?  I found a page online that uses the term "workloads" in reference to Exchange Online, SharePoint Online, and Teams.  Presumably Teams can't be a prerequisite for itself.  Are the other two required?  (Can you not use Teams if you have a different mail system?)  What other M365 workloads are there?  Which are required by Teams?

Thanks,
Mike

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36c8eb24-9ef2-da1f-50fd-a881ed72a7bb
* Version Independent ID: 04542574-e4af-d2d3-eeb0-61fd4a07e481
* Content: [Microsoft Teams Prerequisites - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/upgrade-plan-journey-prerequisites)
* Content Source: [Teams/upgrade-plan-journey-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-plan-journey-prerequisites.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@michaelbunney Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@michaelbunney thanks again for reaching out and for the positive feedback. I'm not sure if this link helps at all regarding workloads, but I have asked the team for assistance as well. Please let me know - https://docs.microsoft.com/en-us/microsoftteams/use-advisor-teams-roll-out
@LanaChin please can you help here.

**Comment by LanaChin** [comment]
Hi @michaelbunney - thanks for reaching out.  Workload is a term that's used to describe a collection of features/services toward a set of capabilities/functionality.  For example, SharePoint, OneDrive and Team are examples of Microsoft 365 workloads.  And, "chats, teams,  channels, & apps" is an example of a Teams workload.  The intent of the first bullet, "If your organization hasn't deployed any Microsoft 365 or Office 365 workloads, see Get started.", is to help those who haven't yet deployed Microsoft 365 get familiar with the services and features that it offers by pointing to the Get Started page (which includes training resources for admins).
