### ISSUE TITLE
Ambiguous: Is a Custom Domain Mandatory for Teams?

### ISSUE THREAD

**Issue by michaelbunney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5633]
The list of Teams "prerequisites" on this page is ambiguous about domains.  it says:

"If your organization hasn't added or configured a verified domain for Microsoft 365 or Office 365, see Domains FAQ."

This raises a number of questions:

1. What is a "verified domain"?  There is no other reference to this term either on this page or on the "Domains FAQ" page you link to.

2. Is a verified domain a custom domain (e.g., foo.com) or can an onmicrosoft.com be used as a verified domain?

3. How does one turn a domain into a "verified domain"?

4. Is a "verified domain" actually required for Teams?  The verbiage on this page doesn't actually say it is a prerequisite.  It says if you don't have one, see an article—which in turn says nothing about "verified domains", Teams, prerequisites, or dependencies.

5. Does Teams require a CUSTOM domain, or can it be used with an onmicrosoft.com domain?  I am looking to the prerequisites page, but it does not make this clear.

MY SCENARIO:
I am setting up an M365 instance for an organization that has an existing (non-Microsoft) mail system bound to their custom domain.  I want to set up M365 users and groups, SharePoint, Exchange, and Teams all without using the custom domain (just using their @xxx.onmicrosoft.com domain).  Later, when M365 is fully set up and tested, I will migrate the legacy mailboxes and the custom domain to M365.  But I can only do this if Teams can work without a custom domain during the interim.

Thus if a "verified domain" is a custom domain, and if a verified domain is a prerequisite, that would mean we cannot set up Teams until AFTER we've migrated our e-mail system and custom domain, which means we couldn't unveil the new system to users all at once.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36c8eb24-9ef2-da1f-50fd-a881ed72a7bb
* Version Independent ID: 04542574-e4af-d2d3-eeb0-61fd4a07e481
* Content: [Microsoft Teams Prerequisites - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/upgrade-plan-journey-prerequisites)
* Content Source: [Teams/upgrade-plan-journey-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-plan-journey-prerequisites.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@michaelbunney Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@michaelbunney thank you for reaching out and helping improve MS Docs.  Please let me know if the information in this article helps at all - https://docs.microsoft.com/microsoft-365/admin/get-help-with-domains/find-and-fix-issues?view=o365-worldwide

**Comment by michaelbunney** [comment]
Hi, Lindsay.

Unfortunately the article you reference has no information about whether a “verified domain” must be a custom domain or can be a <tenant>.onmicrosoft.com domain, nor does it define what it means by “verified domain” (verified by whom? how?) in either case.  It does contain a “Verify your Microsoft 365 domain” link, but this just leads to the “Domains FAQ” page, which does not, in fact, have any information on how to verify a domain, nor what Teams means by a “verified domain”.

The page you reference also doesn’t answer the question of whether a “verified domain” is actually a prerequisite for teams, a point on which the wording of the original page is rather ambiguous.

Thanks,
Mike

**Comment by lindspea** [comment]
@LanaChin could you please assist.

> Hi, Lindsay. Unfortunately the article you reference has no information about whether a “verified domain” must be a custom domain or can be a <tenant>.onmicrosoft.com domain, nor does it define what it means by “verified domain” (verified by whom? how?) in either case. It does contain a “Verify your Microsoft 365 domain” link, but this just leads to the “Domains FAQ” page, which does not, in fact, have any information on how to verify a domain, nor what Teams means by a “verified domain”. The page you reference also doesn’t answer the question of whether a “verified domain” is actually a prerequisite for teams, a point on which the wording of the original page is rather ambiguous. Thanks, Mike From: Lindsay <notifications@github.com> Sent: Monday, August 31, 2020 2:16 a.m. To: MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com> Cc: michaelbunney <michael.bunney@outlook.com>; Mention <mention@noreply.github.com> Subject: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Ambiguous: Is a Custom Domain Mandatory for Teams? (#5633) @michaelbunney<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmichaelbunney&data=02%7C01%7C%7Cab37b796f2bf4232ce6808d84d8e8c37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637344621910516510&sdata=JYk1TuT%2BJyJe8k2fj21Y6lULYkSSOVjLn%2BkH%2BDEzz%2Fc%3D&reserved=0> thank you for reaching out and helping improve MS Docs. Please let me know if the information in this article helps at all - https://docs.microsoft.com/microsoft-365/admin/get-help-with-domains/find-and-fix-issues?view=o365-worldwide<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fmicrosoft-365%2Fadmin%2Fget-help-with-domains%2Ffind-and-fix-issues%3Fview%3Do365-worldwide&data=02%7C01%7C%7Cab37b796f2bf4232ce6808d84d8e8c37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637344621910516510&sdata=rDlr3X1kjI7dfwHcvZo8cJQH4Ok73V8ov%2F%2FbERCWQjA%3D&reserved=0> — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SkypeForBusiness%2Fissues%2F5633%23issuecomment-683665484&data=02%7C01%7C%7Cab37b796f2bf4232ce6808d84d8e8c37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637344621910516510&sdata=pF3Sp6S7Gd8GjWMinHoyoO9e40yw2mmCFf0c8a52aQE%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGK2CBMDVVSGFABZPJYAUPLSDNS63ANCNFSM4QHZHWIQ&data=02%7C01%7C%7Cab37b796f2bf4232ce6808d84d8e8c37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637344621910526504&sdata=MpxuoDWHDT4hy4lqm%2FkpTgVSsnoNmuph1RCinuVHq2E%3D&reserved=0>.

@michaelbunney thanks for letting me know. I have asked the team for help on this. In the meantime here is an article added yesterday - https://docs.microsoft.com/microsoft-365/admin/setup/add-domain?view=o365-worldwide

**Comment by LanaChin** [comment]
Hi @michaelbunney - A custom domain isn't mandatory for Teams. If you want to add a custom domain, you have to add the domain to Microsoft 365 and verify that you own it. For more info, see [What is a domain?](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/what-is-a-domain?view=o365-worldwide) and [Add a domain in Microsoft 365](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/add-domain?view=o365-worldwide).  Thanks.

**Comment by JeremyTBradshaw** [comment]
Just adding here that there are also MS Learn learning paths/modules which have this same misinformation in them.  They mention that you need to ensure you have a custom domain added, but then nowhere else in Teams' documentation otherwise is there anything about the topic.  I assume it has to do with meeting invitation links, but I believe all Teams links/URLs are using teams.microsoft.com.  Back in the day of Skype for Business in Lync, I think this was a thing.  Oh well...
