### ISSUE TITLE
Link 404

### ISSUE THREAD

**Issue by lennarthoefer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5635]
The link for one slide deck linked on this page does not exist.
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/downloads/rooms/module-4-deployment.pdf?raw=true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 752a6dc8-4018-88aa-faa4-c07c1c0a1719
* Version Independent ID: 7d6d29c5-f699-2abd-71c2-7c49061dd068
* Content: [Admin training resources - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/itadmin-readiness)
* Content Source: [Teams/ITAdmin-readiness.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/ITAdmin-readiness.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@lennarthoefer Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@lennarthoefer thanks once again for helping to improve MS Docs. For me to better help you, please can you specify which deck you are referring to?

**Comment by scanum** [comment]
@lennarthoefer We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
