### ISSUE TITLE
no reference to the new license naming "Microsoft Teams Rooms Standard" implies there is a standard and maybe a premium

### ISSUE THREAD

**Issue by liitimellison** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5637]
Would like to see reference to the updated license naming...

no reference to the new license naming "Microsoft Teams Rooms Standard" implies there is a standard and maybe a premium but the only clue is that the name changed in my office admin portal.  What is coming or changing regarding this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-licensing.md)
* Service: **skype-for-business-online**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@liitimellison Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by Reeced40** [comment]
@liitimellison Thank you for reaching out. Does this link help answer your question? https://www.microsoft.com/microsoft-365/blog/2020/07/21/microsoft-teams-meetings-hybrid-workplace-options/

**Comment by scanum** [comment]
@liitimellison Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
