### ISSUE TITLE
Document which web browsers are not supported

### ISSUE THREAD

**Issue by MrJadaml** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5639]
The unsupported-browsers should document which browsers are not supported, like Brave browser for instance. If there is a list of unsupported web clients it will be more clear to users which client they should use, when their preferred client may be supported, or stats on if there are plans to eventually provide support for a particular client.

**Comment by scanum** [comment]
@MrJadaml Could you please link the documentation you are referring to? Thanks!

**Comment by get-itips** [comment]
Hello @MrJadaml Adam, how are you?
Please link here the article you are talking about. Thanks!

**Comment by scanum** [comment]
@MrJadaml We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
