### ISSUE TITLE
It's not clear to me

### ISSUE THREAD

**Issue by ruffzy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#564]
For Switzerland most of the communication features are available but the point "Calling Plans are available to purchase" is not available/set to no. What does that mean? I am able to get phone numbers for Switzerland but can't use them because I can not buy this calling plan?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 61078d61-bd8c-8689-f1b2-8c500461d3f0
* Version Independent ID: aba33dc3-f625-4f44-a2e3-e408f5b18886
* Content: [Verfügbarkeit in der Schweiz](https://docs.microsoft.com/de-de/SkypeForBusiness/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-switzerland)
* Content Source: [Skype/SfbOnline/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-switzerland.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.de-DE/blob/live-sxs/Skype/SfbOnline/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-switzerland.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
I was able to get this into the backlog for the Teams/Skype team so the team can provide clarification around Switzerland and the calling plans and available features. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by kenwith** [comment]
@ruffzy - sorry for the long delay. I am working to figure this out and will keep this open.

**Comment by kenwith** [comment]
@ruffzy - I was able to get in touch with the PM that owns this area @msmikedavis. 

You can get **SERVICE** numbers in Switzerland for use with conferencing, auto-attendant and call queues, but you cannot get **USER** numbers in Switzerland as calling plans are not available.

I am going to add this info into the article with a Pull Request. Thank you for taking the time to submit feedback.
