### ISSUE TITLE
Broken Link - One Touch Join

### ISSUE THREAD

**Issue by dooleydo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5641]
This link is broken (404)

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/downloads/rooms/module-8b-one-touch-join-instructions.pdf?raw=true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 752a6dc8-4018-88aa-faa4-c07c1c0a1719
* Version Independent ID: 7d6d29c5-f699-2abd-71c2-7c49061dd068
* Content: [Admin training resources - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/itadmin-readiness)
* Content Source: [Teams/ITAdmin-readiness.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/ITAdmin-readiness.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@dooleydo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@dooleydo thank you for reaching out and helping improve MS Docs. I've just checked and the link is working. Please check from your side and let me know.

**Comment by scanum** [comment]
@dooleydo Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
