### ISSUE TITLE
Remove / update privacy shield reference

### ISSUE THREAD

**Issue by willyyr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5642]
Change reference to obsolete Privacy Shield certification after SCHREMS II. Location: https://docs.microsoft.com/en-us/microsoftteams/teams-privacy#where-does-teams-transfer-and-store-personal-data

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e34f35bb-7d9c-0c7f-a1a1-6fd9fbe93dfa
* Version Independent ID: d123210a-ed20-4b97-3706-33d7887b4c27
* Content: [Microsoft Teams Privacy - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-privacy)
* Content Source: [Teams/teams-privacy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-privacy.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@willyyr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @willyyr,

An update will be published with further information in the coming days.

@scanum please close it.

**Comment by dariomws** [comment]
@scanum please close it.
