### ISSUE TITLE
Is Microsoft Teams ICE endpoint or not?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5643]
Hi,
You are actively using a term "ICE Candidates" when speaking about call flows with Teams. But we have been told that Microsoft Teams client is **not** ICE endpoint. So, is this term correct or not on your text? Or has we been informed incorrectly and Teams is ICE endpoint?

Skype for Business was ICE endpoint and this was very clear on there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c84773-337e-9df7-7fbd-fc9d94280711
* Version Independent ID: 223a78a0-67fd-8b96-be3f-153bb400101b
* Content: [Microsoft Teams call flows - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/microsoft-teams-online-call-flows)
* Content Source: [Teams/microsoft-teams-online-call-flows.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/microsoft-teams-online-call-flows.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Petri-X, thank you for your feedback and help us to improve docs.microsoft.com.

Do you have a document or video where Microsoft says that Teams is not ICE?

I understand the same that this article states clearly:
"Teams media flows connectivity is implemented using standard IETF Interactive Connectivity Establishment (ICE) procedures."

**Comment by scanum** [comment]
@Petri-X We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
