### ISSUE TITLE
[LOC]Back-Translation "Microsoft Teams のルーム"→"Microsoft Teams Rooms"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5646]
ja-jp:https://docs.microsoft.com/ja-jp/microsoftteams/rooms/rooms-scale
![rooms-scale_j](https://user-images.githubusercontent.com/40815708/91254423-59c22980-e79d-11ea-8f60-b1864a674b0b.png)

en-us:https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-scale
![rooms-scale_e](https://user-images.githubusercontent.com/40815708/91254426-5c248380-e79d-11ea-9eb6-3d5f89d809a1.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f4fb7681-f8cb-3723-9783-9b63563177ff
* Version Independent ID: 86c78ee0-19b0-91a1-16fc-70ee70edc0d8
* Content: [Microsoft Endpoint Configuration Manager を使用して Microsoft Teams ルームを展開する - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/rooms/rooms-scale)
* Content Source: [Teams/rooms/rooms-scale.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-scale.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@OfficeGlobal Please assist.

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by Reeced40** [comment]
@OfficeGlobal any update yet?

**Comment by TinaMcN** [comment]
@hyoshioka0128 this issue appears to be fixed.  Please close if it's ok now.  Thanks again for reporting this issue.

**Comment by hyoshioka0128** [comment]
@TinaMcN - "Microsoft Teams Rooms" has been Fixed. Thanks!
Closed #5646 .
