### ISSUE TITLE
Allow Transcription - only affects recording?

### ISSUE THREAD

**Issue by khilker15** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5647]
In the Teams Admin Console, the Allow Transcription policy description says: "You can turn on or off transcription for a meeting."
In this document, it states this policy applies to meetings recordings.  

Does this policy affect whether Live Captioning can be enabled/disabled by attendees during a meeting?  Or does it only affect whether captions are available to those watching a recording later?  The two different descriptions make this unclear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/meeting-policies-in-teams?WT.mc_id=TeamsAdminCenterCSH#bkaudioandvideo)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@khilker15 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@khilker15 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
