### ISSUE TITLE
Recording settings vs reality

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5648]
Hello! From my tests of the recording settings to "never" does not disable recording. Even when this setting is set to "Never record" then meeting organizer can check "recording available to attendees" and even if it is not checked then after starting an event there is a notification in Teams client that recording has started and there is possibility to check the checkbox to make the recording available after the meeting has ended.

What is the designed functionality of the "recording setting" attribute?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9aa4676-855a-fddb-bb0b-96b7095c695e
* Version Independent ID: 7c39f08c-0d56-6d29-1356-879d9d6ff51c
* Content: [Set up for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-live-events/set-up-for-teams-live-events)
* Content Source: [Teams/teams-live-events/set-up-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/set-up-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
