### ISSUE TITLE
Reference to PowerShell Module.

### ISSUE THREAD

**Issue by thecathcart** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#565]
Under the "Enable live event scheduling for the user" section it is mentioned that you should use the Teams PowerShell module to configure the AllowBroadcastScheduling parameter using the Set-CsTeamsMeetingBroadcastPolicy cmdlet.  However, this cmdlet is found in the Skype for Business Online PowerShell module currently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: becbf3ca-b88c-b033-a145-9a1af201ced3
* Version Independent ID: 41a6a9b5-d3dd-d8c9-9e97-920ff2fd1a24
* Content: [What are Teams live events?](https://docs.microsoft.com/en-us/microsoftteams/what-are-teams-live-events#planning--setup)
* Content Source: [Teams/what-are-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @tonysmith
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@thecathcart - that is a good catch. Right now the cmdlets for Teams are in both Teams module and also Skype for Business module. I know there are plans to converge at some point but for now we will make this clear in the doc and say Teams / Skype for Business module and provide a link to the specific cmdlet. Thanks for catching this and for submitting the feedback!

**Comment by kenwith** [comment]
This is actively being worked on. Closing this one out as it is high on the radar for the product and also writing team. Work is being done to clarify all around since this is a real confusion.
