### ISSUE TITLE
Imagens da Página de visão geral de classe em Insights, não estão aparecendo

### ISSUE THREAD

**Issue by psazevedo1970** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5650]
As imagens da página abaixo e todas as suas subjacentes, não estão aparecendo  :
https://support.microsoft.com/pt-br/office/p%C3%A1gina-de-vis%C3%A3o-geral-de-classe-em-insights-1386d1b4-3641-4a23-9b9c-0c6c774c2b6c

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 3501fde1-69ef-1908-876c-4f50e90649f5
* Version Independent ID: e9c673d9-6c18-7440-da5d-cdeff4dd9b8b
* Content: [Guia para o Administrador de TI sobre o Insights no Teams para Educação - Microsoft Teams](https://docs.microsoft.com/pt-br/microsoftteams/class-insights)
* Content Source: [Teams/class-insights.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/class-insights.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@psazevedo1970 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@OfficeGlobal Please assist.

**Comment by Reeced40** [comment]
@OfficeGlobal any update?

**Comment by TinaMcN** [comment]
This issue is for the support.microsoft.com/office content.  I logged a bug for that team to fix it.

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
