### ISSUE TITLE
The RoadMap Link in the first "Important" Box is not working as expected

### ISSUE THREAD

**Issue by J-a-k-o-b** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5652]
Hi,

The Roadmap link:
https://www.microsoft.com/en-us/microsoft-365/roadmap?featureid=44370
mentioned in the first "important" Box at the top of the page is not right. 
The ID 44370 which the link filters isn´t available anymore. Whats the right Roadmap ID?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5920152-5fee-41ed-56df-ad7b51b25cc2
* Version Independent ID: 88cfc850-5e36-48ee-ba99-088b2b653f1e
* Content: [Manage discovery of private teams in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-discovery-of-private-teams#non-discoverable-private-teams)
* Content Source: [Teams/manage-discovery-of-private-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-discovery-of-private-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@J-a-k-o-b Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by J-a-k-o-b** [comment]
Hi @scanum,
i don´t think that a support case will help here. It´s more a kind ot typo. It has nothing to do with our tenant. The link in the docs is just wrong.
Regards
