### ISSUE TITLE
License info

### ISSUE THREAD

**Issue by bartvermeersch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5653]
According to this page, the licensing requirements for cloud teams recording are
- User has Office 365 E1, E3, E5, A1, A3, A5, M365 Business Premium, M365 Business Standard, or M365 Business Basic.
- User needs to be licensed for Microsoft Stream1

But according to https://docs.microsoft.com/en-us/stream/portal-upload-teams-meeting-recording at least A3/E3 is needed.

Info in the link above was communicated overnight (a month ago) during holiday period in the Office365 and it is not conform the info on this page. This is turning into a real mess, we can't change our internal working in one month.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@bartvermeersch Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @bartvermeersch, thank you for your feedback and help us to improve docs.microsoft.com.

The link you share is related to A1 license, not E1. I'll add this information to the reference article.
