### ISSUE TITLE
Error in directions for limiting posts to members

### ISSUE THREAD

**Issue by DaveO365** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5654]
The directions for limiting posts to members in the General channel are incorrect. They direct to the Team Settings, but should direct to the Channel Settings.

Now the text reads: "Reduce channel noise by having only team owners post to the General channel. Go to the team and click ˙˙˙ More options > Manage Team. On the Settings tab, click Member permissions > select Only owners can post messages.

It should read: Go to the team, locate the General channel, and click ˙˙˙ More options > **Manage Channel.** On the **Channel Settings** tab, under Permissions > select Only owners can post messages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@DaveO365 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LanaChin** [comment]
@DaveO365 Thanks for your feedback! We've updated the doc.
