### ISSUE TITLE
Reference to an older preview version

### ISSUE THREAD

**Issue by winderickxeli** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5657]
Hi

There seems to be a reference to a preview version 1.1.3. The most current version is 1.1.4 which is newer than the 1.1.3 preview. This should be omitted or altered to a newer preview version. This will confuse users who aren't familiar with powershell gallery.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd283f6e-3865-ed70-d663-cc461ee8ba57
* Version Independent ID: 2450d311-fc04-d8b6-b4a2-b1890ec6fc3e
* Content: [Install Microsoft Teams PowerShell - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-install)
* Content Source: [Teams/teams-powershell-install.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-install.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
@winderickxeli Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by winderickxeli** [comment]
Hi, Thanks

It seems to be double confusing. The 1.3 is really the 'preview' version with extra functionality. The 1.4 does not contain these new functionalities. This is really confusing... :confused:

**Comment by dariomws** [comment]
Hi @winderickxeli, thank you for your feedback and help us to improve docs.microsoft.com.

It's true, 1.3 is the latest public preview version and 1.4 is the latest stable version. This is why you need to run the command with "-RequiredVersion "1.1.3-preview"" to install the public preview version.

**Comment by scanum** [comment]
@winderickxeli  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
