### ISSUE TITLE
Duplicate Paragraph

### ISSUE THREAD

**Issue by EgoManiac** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5659]
You have a duplicate paragraph in the advisor section

- However, you don't have to be a Teams admin to use Advisor for Teams - anybody in your organization can use it. We've set up special permissions so non-admin users can get to Advisor for Teams, even though it's in the Teams admin center. You DO have to be a Teams admin, Teams Service Administrator, or Global Administrator to open the tenant readiness assessments (this is because the special non-admin roles don't have access to the Microsoft Graph APIs underlying the assessments).-

This paragraph is repeated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8837c1c-ea62-4ac9-5187-3da28ff2086c
* Version Independent ID: 1ae9e143-9895-521f-a3e4-42c9dd8436c0
* Content: [Use Advisor for Teams to help you roll out Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/use-advisor-teams-roll-out)
* Content Source: [Teams/use-advisor-teams-roll-out.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/use-advisor-teams-roll-out.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@EgoManiac Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@EgoManiac  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
