### ISSUE TITLE
Impact on Teams Meetings

### ISSUE THREAD

**Issue by DavidSchrag** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5660]
From my understanding of this article, even if external access is disabled there is no impact on external parties' ability to join Teams Meetings (the kind you arrange via an Outlook invitation). It would be helpful to clarify that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external access (federation) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@DavidSchrag Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @DavidSchrag, thank you for your feedback and help us to improve docs.microsoft.com.

I'm adding a note to the article:
> [!NOTE]
> If external access is disabled in your organization, external users would still be able to join your meetings through the anonymous join. For more information, see [Manage meeting settings in Microsoft Teams](https://docs.microsoft.com/microsoftteams/meeting-settings-in-teams).

Also, if anonymous is disabled and external access is enabled, external users can join meetings if they sign in with their Teams accounts.
