### ISSUE TITLE
Where are meeting transcripts stored?

### ISSUE THREAD

**Issue by scheblein** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5661]
Need to understand where meeting transcripts are stored (for legal purposes). Are they hosted in stream storage, or on the organizer's personal onedrive, or etc? The article mentions recordings but not transcripts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@scheblein Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tonysmit** [comment]
@SamChung-MS - Can you help us out here please?

**Comment by SamChung-MS** [comment]
Is this question in regards to the transcripts you see when you play back the recording on Stream? If so, those transcripts are created by Stream, so they're on Stream.

**Comment by scheblein** [comment]
> Is this question in regards to the transcripts you see when you play back the recording on Stream? If so, those transcripts are created by Stream, so they're on Stream.

Great. Two final questions:

1. Is it Microsoft that does the transcribing (and not a third party)?

2. Can this be info be updated in the article so that I can have something to refer people to?

**Comment by dariomws** [comment]
@scheblein, thanks for your feedback. About your questions:

1. Microsoft (with Azure Media Services I think)
2. I think so

@tonysmit @SamChung-MS if you agree I can add this information to the article. Thanks!

**Comment by SamChung-MS** [comment]
I agree and good with it being updated.  Just make it clear that it's Stream Transcript we're talking about.
