### ISSUE TITLE
Typos in command

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5665]
This example:

New-CSOnlinePSTNGateway -Identity sbc1.contoso.com -SipSignalingPort 5061 –InboundTeamsNumberTranslationRulesList ‘AddPlus1’, ‘AddE164SeattleAreaCode’ -InboundPSTNNumberTranslationRulesList ‘AddPlus1’ -OnboundPSTNNumberTranslationRulesList ‘AddSeattleAreaCode’,  -OutboundTeamsNumberTranslationRulesList ‘StripPlus1’

Has typos.
"onbound..." instead of "outbound...".  
The "list" at the end of the 4 parameter names shouldn't be there.

**Comment by scanum** [comment]
@TorrenManson Please list the article you are referring to.

**Comment by TorrenManson** [comment]
Hi - my bad, I clicked on the wrong link and so it's not tied to the article. It's this one https://docs.microsoft.com/en-us/microsoftteams/direct-routing-translate-numbers

**Comment by scanum** [comment]
Thanks!

**Comment by Reeced40** [comment]
@TorrenManson Hi there. Thank you for pointing this out. I've created the PR for the PowerShell correction. Please clarify under which Example "list" must be removed. Thanks.

**Comment by TorrenManson** [comment]
Hi - I count 20 instance of "...ruleslist" on the page, they should all just be "...rules"
