### ISSUE TITLE
Exchange 2013 CU19+ also compatible with AutodiscoverV2

### ISSUE THREAD

**Issue by agallego-css** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5668]
[Enter feedback here]
Isn't Exchange 2013 CU19+ also compatible with AutodiscoverV2? I believe so based on: https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/known-issues/teams-exchange-interaction-issue
"Exchange Autodiscover V2 is required to allow the Teams service to perform an unauthenticated discovery against the user's mailbox that's located in Exchange Server. Autodiscover V2 is fully supported in Exchange Server 2013 Cumulative Update 19 or later. "
So I think this article should be updated to also mention exchange 2013 CU19+

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact?source=docs)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@agallego-css Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@agallego-css thank you for helping improve MS Docs. It looks like this article has been updated with that information. Please confirm from your side. Thank you.
