### ISSUE TITLE
Delay on status of contacts

### ISSUE THREAD

**Issue by Brumaz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5673]
While in Teams, a colleague user I want to contact has a Green status. So I type my message and hit Enter. Then immediately the status changes to the actual status and thus implied that the green status was not correct. Skype did this always correct, Teams is nearly always wrong!

**Comment by scanum** [comment]
@Brumaz Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
