### ISSUE TITLE
Download link does not work.  https://1drv.ms/f/s!ArcnbnREun0Vnp9Wps9MlWB-UJZw3g

### ISSUE THREAD

**Issue by cnbjacobsbd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5674]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f256cd5b-3ec8-2d55-9ae4-ff9849d52eae
* Version Independent ID: 52c2271b-df38-5dc9-c2a1-553cdf3b5496
* Content: [Deploy Microsoft Teams for Surface Hub - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-surface-hub)
* Content Source: [Teams/teams-surface-hub.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-surface-hub.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@cnbjacobsbd Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@cnbjacobsbd Thank you for reaching out. I just checked to see and the link seems to working fine. Could you please confirm it your side. Thanks.

**Comment by cnbjacobsbd** [comment]
Yes it is working.
I got my copies over a week ago

Thank you

**Comment by Reeced40** [comment]
@cnbjacobsbd Thank you for confirming. @scanum Could you please close this issue.
