### ISSUE TITLE
default values for user/locale

### ISSUE THREAD

**Issue by philliplyle** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5676]
The last section describes defaults for different user types (e.g. anonymous, Guest) and says "Default", but doesn't describe how these defaults can be changed.  The term Default suggests they can be changed, but no documentation exists on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2465e854-e3b1-6bd0-c834-c696121e857a
* Version Independent ID: 6b225ed2-0cd3-b3c3-0e3a-d7ce98031e16
* Content: [Use NDI in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/use-ndi-in-meetings)
* Content Source: [Teams/use-NDI-in-meetings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/use-NDI-in-meetings.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
I removed the mention of defaults for user types. The article is now live. Thank you for your help.

**Comment by philliplyle** [comment]
Thanks.  So I am guessing you are confirming they can't be changed?  Too bad.  This becomes another half baked feature, then, if you can't use it with external participants.
