### ISSUE TITLE
Step 4 needs to be updated now that Teams is rolling out to GCC tenants.

### ISSUE THREAD

**Issue by mhunsberger** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#568]
You can probably completely remove "Step 4: Apply for Microsoft 365 Government - GCC"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7faee29-6d56-f3bf-766c-6deaefe92e34
* Version Independent ID: 6029b6f8-7d49-6474-fa40-2793000c74a4
* Content: [Plan for Microsoft 365 Government - GCC deployments - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/plan-for-government-gcc)
* Content Source: [Teams/plan-for-government-gcc.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-for-government-gcc.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lehewe**

**Comment by kenwith** [comment]
@mhunsberger - that is a good catch. Right now the cmdlets for Teams are in both Teams module and also Skype for Business module. I know there are plans to converge at some point but for now we will make this clear in the doc and say Teams / Skype for Business module and provide a link to the specific cmdlet. Thanks for catching this and for submitting the feedback!

**Comment by kenwith** [comment]
Sorry! I replied to https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/565 in this one. I will get this checked too. Thanks for reporting!

**Comment by kenwith** [comment]
I was able to get this into the backlog for the Teams/Skype team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.
