### ISSUE TITLE
Can the $4 audio conferencing be added to Teams within Microsoft 365 Business Standard? I'm finding conflicting information. This will only be used for a conference bridge. 

### ISSUE THREAD

**Issue by S2AMC** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5681]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59426612-8da4-be3e-f0c8-8c23e9178d7d
* Version Independent ID: bd2d7426-06d6-5c18-7776-a50fc05c9ce9
* Content: [Configure Audio Conferencing settings - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/deploy-audio-conferencing-teams-landing-page)
* Content Source: [Teams/deploy-audio-conferencing-teams-landing-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/deploy-audio-conferencing-teams-landing-page.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by tonysmit** [comment]
Yes, it can be added to each Small Business Plan.
