### ISSUE TITLE
add a NOTE

### ISSUE THREAD

**Issue by Strick1969** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5686]
[Enter feedback here]
shouldn't we update this with a NOTE saying something like "we now have a restriction that only allows the dial pad to appear if the user is set to Teams only, We do not support he usage of enterprise voice (MS Hosted phone Service) on 2 different application, such Skype for business Online and Teams at the same time"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e994851c-2be6-6a89-fce5-f9238ce4796b
* Version Independent ID: e4e6be9d-1128-31b8-be3e-adfd9817b4d8
* Content: [Teams dial pad configuration - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/dial-pad-configuration)
* Content Source: [Teams/dial-pad-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/dial-pad-configuration.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@officedocspr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
