### ISSUE TITLE
Possible update to licensing information

### ISSUE THREAD

**Issue by SotoDucani** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5687]
The licensing information might need to be pointed at this link ([Teams Meeting Room Licensing Update](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing)), or added as a reference indicating that there is a new licensing model that should be moved to. Just got into a comparison between this page and the one I linked above attempting to figure out which was accurate before confirming it with the Note and Important on the Licensing Update page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Microsoft 365 or Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-office-365)
* Content Source: [Teams/rooms/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-office-365.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@SotoDucani Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@SotoDucani thank you for pointing this out. This article has been updated in the interim with your recommendations. Thanks again for your help.

**Comment by scanum** [comment]
@SotoDucani We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
