### ISSUE TITLE
This seems to be an excuse not a resolution

### ISSUE THREAD

**Issue by PhilLeitch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5688]
Telling us why memory usage is unacceptably high doesn't address the fundamental problem that the memory is unacceptably high.  

Can you please add a link to means to lobby/request for Microsoft to address this issue?  Can I suggest linking to the link below, that is hitting the 4-year anniversary and gets dozens of votes and comments a week?
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/17219609-teams-uses-600mb-and-is-super-slow

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc21902c-d522-3851-8587-177f01bc085c
* Version Independent ID: 590bcc64-a86d-b61e-7d94-4e4322c4e71d
* Content: [How Microsoft Teams uses memory - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-memory-usage-perf)
* Content Source: [Teams/teams-memory-usage-perf.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-memory-usage-perf.md)
* Service: **msteams**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@PhilLeitch Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@PhilLeitch thank you for reaching out. Just for clarification, are you suggesting adding a link to uservoice in this article?

**Comment by PhilLeitch** [comment]
Yes, but to be honest I don’t understand even creating an article explaining why resource use is unacceptably high.

What is the purpose of the article?  What was it attempting to achieve?  What did you expect someone who searched for and found this article would leave with?

Is it designed to explain that Microsoft is aware that the resource footprint is unacceptably high and explain why it can’t do anything about it?  It’s almost as though the article explains the mistakes Microsoft has made that lead to the situation I’m in when I use teams.

Can you please re-read the article to see what I mean – it offers no usable information to IT professionals.  We either add more ram to devices or upgrade devices, right?

The article doesn’t provide any actions I can do to reduce the excess usage, like a setting or option to minimise the massive footprint.

This frustration comes from money and time we are burning on teams.  We’ve just had to retire 20 still new Microsoft Surface because 8GB is simply insufficient to run teams.

By insufficient, I mean that if teams is quit the surfaces operate normally, but with Teams running the surface is all but unusable.

And the flood of messages sharing this sentiment that appear on uservoice are simply going unanswered….

**Comment by msdmaguire** [comment]
@PhilLeitch The intention of the article was to reduce the great many calls and questions Microsoft was receiving by admins and customers who saw how resource-intensive Teams can be in some environments. It was meant to explain that Teams uses whatever resources are available to it, but not at the expense of other apps and services running in the same environment. Teams "gives back" when there is a demand for resources elsewhere. Certainly we will pass along your feedback that current memory usage is unacceptably high. We appreciate the feedback.

**Comment by PhilLeitch** [comment]
Sorry, but for clarity, can you confirm that the purpose of this article is to reduce the calls Microsoft was receiving by admins and customers when Teams is excessively resource intensive?

Can you confirm that this knowledge base article does not providing admins and any ability to address or take any action on Teams actually being so resource intensive that customers would otherwise contact Microsoft?

Also, I can repeatedly demonstrate that Teams does not “return” sufficient resources to Microsoft Surface and other environments in order to be used in an office environment, as also shown by many others over about 5 years on the community thread. Am I able to provide you telemetry to demonstrate this article is in fact wrong or misleading (as insufficient resources are returned by teams)?

Thank you for your patience on this
