### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5690]
This page is out of date. Can we please ensure we have latest firmware version numbers on this page at same time they are released. Also can we please have access to release note to compliment the versions. These are being posted on vendor sites a week after they are already rolling out via Team admin portal.

i.e.
Yealink T55/T56/T58 | 58.15.0.107! latest available is 58.15.0.110

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaaef9e1-8f1c-ebf0-7856-4c007342a2c3
* Version Independent ID: 3eaf671f-375e-8787-9c66-3947c3606559
* Content: [Phones and Devices for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/teams-ip-phones)
* Content Source: [Teams/devices/teams-ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/teams-ip-phones.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@SvenBell Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@SvenBell thank you for helping improve MS Docs. It looks like the Yealink correct version is reflecting with the recent update to this article. Please confirm if all okay from your side or if anything else needs to be changed. Thanks.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
