### ISSUE TITLE
Old directions

### ISSUE THREAD

**Issue by tabbysp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5692]
There are links/directions for the admin page. Those appear to be for the old admin center view. Would you please update those. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d52a9779-b72d-dea0-eac2-6c04a8c282eb
* Version Independent ID: d3c3d968-9e54-ec42-3438-9320e23d68b9
* Content: [What are Communications Credits? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/what-are-communications-credits)
* Content Source: [Teams/what-are-communications-credits.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-communications-credits.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@tabbysp Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@tabbysp thank you for pointing this out. Is this the correct link for the admin centre you are referring to - https://www.microsoft.com/microsoft-365/business/office-365-administration

**Comment by scanum** [comment]
@tabbysp Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
