### ISSUE TITLE
EDU templates are not fully deployed in Commercial tenants

### ISSUE THREAD

**Issue by Melina2414** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5693]
EDU templates do not get fully deployed in Commercial tenants. Looks like documentation is lacking to advertise that these templates should work only in EDU tenants. https://docs.microsoft.com/en-us/MicrosoftTeams/get-started-with-teams-templates

**Comment by scanum** [comment]
@officedocspr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Melina2414** [comment]
Any news on this?

**Comment by Reeced40** [comment]
@Melina2414 thank you for helping improve MS Docs. This article has recently been updated. Please also see note - "Custom templates are not yet supported for EDU customers."

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
