### ISSUE TITLE
Whiteboard for Teams

### ISSUE THREAD

**Issue by BHGoodwin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5694]
[Please specify which cloud instances that Whiteboard is currently available in. Gov cloud customers reading this need to know whether the information applies to them. Thanks.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26085815-da9c-b727-5323-b0d7dc840fb8
* Version Independent ID: 105b742d-a730-fb7b-b0fd-7cb67919880a
* Content: [Manage the Whiteboard in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-whiteboard)
* Content Source: [Teams/manage-whiteboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-whiteboard.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by BHGoodwin** [comment]
I’m a Microsoft CSAM supporting government market (SLG) customers; and as such I don’t have a tenant. I submitted the feedback as a result of our customers experiences. They need to know if product guidance applies to them as GCC cloud customers. When this is not plainly stated at the top of a DOC, it leads to confusion and negatively impacts the customer experience.

Sent via Outlook<https://aka.ms/qtex0l> for iOS
________________________________
