### ISSUE TITLE
Allow chat in meetings -> per user setting

### ISSUE THREAD

**Issue by jesegher** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5695]
Allow chat in meetings
This is a per-organizer policy. This setting controls whether meeting chat is allowed in the user's meeting.

-> This is incorrect. This is per user setting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams#allow-chat-in-meetings)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by maxafritz** [comment]
Also verified. This setting is per user.

**Comment by scanum** [comment]
@maxafritz Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@jesegher thank you for pointing this out. It looks like this has been fixed in the interim. Please confirm from your side. Thanks.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
