### ISSUE TITLE
Forwarding to Toll-Free numbers is not supported

### ISSUE THREAD

**Issue by ZugBug** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5698]
Forwarding calls to a toll-free number from an auto attendant is not supported but this is not documented anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a42f9e2c-aeee-76c4-620a-668cce21ba10
* Version Independent ID: 6ff06eab-9c80-9c30-95ef-c17e157fbea1
* Content: [Set up a Cloud auto attendant - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-auto-attendant)
* Content Source: [Teams/create-a-phone-system-auto-attendant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-auto-attendant.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@ZugBug Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi, @MikeBazMSFT 

Would you recommend me to add this suggestion as a "Note" in the document?

**Comment by MikeBazMSFT** [comment]
@sowjanya365 wrong person.

**Comment by scanum** [comment]
@MikePlumleyMSFT Would you recommend me to add this suggestion as a "Note" in the document?

**Comment by MikePlumleyMSFT** [comment]
@CLYVR can you confirm that forwarding to a toll-free number isn't supported?

**Comment by CLYVR** [comment]
Checking... will let you know

**Comment by CLYVR** [comment]
@MikePlumleyMSFT  There shouldn't be any issue provided the right licenses are in place.  The toll free number may have geographic restrictions on it (only accepts calls from certain areas).  What's the toll free number being transferred to?  What was the error?  Was it a message "The number you are calling can't be reached from your area?" or something similar?  What is the CLID that was being sent with the call?  Lastly, if you try again and it still fails, please provide the CallID.

**Comment by scanum** [comment]
@ZugBug  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
