### ISSUE TITLE
Planen von Onlinebesprechungen über Outlook Kalender

### ISSUE THREAD

**Issue by bastianhandel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#570]
Hier in der Dokumentation steht zum Punkt
"Planen von und Teilnehmen an Onlinebesprechungen über Outlook" widersprüchlige Aussagen.
Für "Exchange 2016/2013(on premises) + Skype für Business Online" ist ein J und ein N in der Tabelle zu sehen.
Welche Aussage ist korrekt?

gruß
bastian

Planen von und Teilnehmen an Onlinebesprechungen über Outlook

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: f91868fa-0a46-a7e7-eaae-388fc90e195d
* Version Independent ID: 193c6ccc-3fc0-5146-ed08-55f9d8871341
* Content: [Plan zur Integration von Skype for Business mit Exchange Server](https://docs.microsoft.com/de-de/skypeforbusiness/plan-your-deployment/integrate-with-exchange/integrate-with-exchange#feedback)
* Content Source: [Skype/SfbServer/plan-your-deployment/integrate-with-exchange/integrate-with-exchange.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.de-DE/blob/live-sxs/Skype/SfbServer/plan-your-deployment/integrate-with-exchange/integrate-with-exchange.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Hi, thanks for bringing this to our attention, I'm currently looking into it.

**Comment by jambirk** [comment]
Bastian, I'm looking at the English and German tables and in both cases the feature row "Planen von und Teilnehmen an Onlinebesprechungen über Outlook" or "Schedule and join online meetings through Outlook"  shows support in all the combinations of server or online. Can you please clarify what the contradiction is you're seeing?

**Comment by jambirk** [comment]
Bastian, This appears to be a translation error. There are two similar rows, one of them refers to the full Outlook client and the other refers to the OWA client. Both rows are correct, but the second row was mistranslated to refer to the Outlook client when the OWA client was intended.

I'll contact the localization team and get this corrected.

**Comment by jambirk** [comment]
The correction should be completed by now. Please let us know if there's anything else.
