### ISSUE TITLE
Teams Admin Center Toll-free port capability

### ISSUE THREAD

**Issue by jmeddy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5700]
It looks like you can now port toll-free numbers in the Teams Admin Center. Is this document out of date? The excerpt I am referring to is bolded below:

Toll-free numbers with area codes such as: 800, 844, 855, 866, 877 and 888 can't be included in a number porting request with other types of numbers. **To port these toll-free numbers, you must manually submit a port order. You can't port these numbers in the Microsoft Teams admin center. For more information, see Manage phone numbers for your organization.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a17293e0-4c49-0e97-d5da-b48322f10928
* Version Independent ID: c38c0726-5dec-d374-6948-2188d43025ef
* Content: [What's a port order? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/phone-number-calling-plans/port-order-overview)
* Content Source: [Teams/phone-number-calling-plans/port-order-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phone-number-calling-plans/port-order-overview.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@jmeddy Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @jmeddy, thank you for your feedback and help us to improve docs.microsoft.com.

I'll try to confirm this information internally.

**Comment by dariomws** [comment]
@cichur could you kindly help here? Thank you!

**Comment by dariomws** [comment]
@cichur could you kindly help here? Thank you!

**Comment by cichur** [comment]
@dariomws I sent a message to the PMs to get an answer.

**Comment by dariomws** [comment]
@cichur any update here? Thank you!

**Comment by scanum** [comment]
@HowlinWolf-92 - Hi Mark, hope you are well. Could you kindly help here? Thanks!

**Comment by dariomws** [comment]
@HowlinWolf-92 - Hi Mark, hope you are well. Could you kindly help here? Thanks!
