### ISSUE TITLE
Description of Teams update process appears to be completely false

### ISSUE THREAD

**Issue by tcobbs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5701]
As far as I can tell, Teams has some kind of multiple week long process of when it allows people to update. It somehow (based on IP address?) holds off on updates to some team members while happily providing updates to other team members for weeks at a time. This delay also affects the official download page, where if a team member tries to reinstall from scratch, the download page still gives them the old version, even if everybody else on their team already got a new version via auto-update. Manually using the generated download link that another team member is given for a fresh install does work, but the entire situation is incredibly antagonistic to your users, and the _completely_ wrong information on this page makes things all the more frustrating.

Note: I verified that the other team member (who got an update last week) is in the same update ring as I am for Teams (general).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6da28da-eb7b-d3ae-4c2f-8f87803b1830
* Version Independent ID: 8c42d7a2-80c6-86dd-347a-ed6d8d909c41
* Content: [Teams updates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-client-update)
* Content Source: [Teams/teams-client-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-client-update.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@tcobbs Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @tcobbs 

Thanks for your comments and suggestion, we really appreciate them. From my understanding, these updates are also dependant on the system settings. And also users need to be signed in for updates to be downloaded.
