### ISSUE TITLE
External Phone Number Syntax

### ISSUE THREAD

**Issue by cpajr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5704]
Under Redirect Call -> External Phone Number, in addition to the criteria listed there, it should also be noted the syntax of how the phone number should be inputted.  For example, the US phone number (555) 555-5555 should be entered as +1 555 555 5555.  Any other form of it will result in the redirect to not work correctly.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a42f9e2c-aeee-76c4-620a-668cce21ba10
* Version Independent ID: 6ff06eab-9c80-9c30-95ef-c17e157fbea1
* Content: [Set up a Cloud auto attendant - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/create-a-phone-system-auto-attendant?WT.mc_id=TeamsAdminCenterCSH#redirectcalls)
* Content Source: [Teams/create-a-phone-system-auto-attendant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-auto-attendant.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@cpajr  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @cpajr 

Thank you for reporting and making the docs better. Much appreciated. 

Would you be so kind as to elaborate more on this issue? It would help us to understand it better and take appropriate steps to resolve or clarify. It would be great if you can point out the exact paragraph and the sentence. Looking forward to your response. Thank you!

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
