### ISSUE TITLE
Clarify Policy Assignment For Groups Containing Nested Groups

### ISSUE THREAD

**Issue by packman83** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5705]
The documentation states policies can be assigned to security or distribution groups, which will then be applied to the group members. It does not clarify, however, that the policy will only apply to members that are **users**. For groups with nested groups, the policy assignment does not propagate to the members of the nested group.

Please add this clarification to the documentation, or indicate if the policy _should_ apply to nested groups as well. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888fe05b-1160-452f-90ba-deb19adb740f
* Version Independent ID: 4091c5e4-7a90-7fe4-2741-16bbb1f297c1
* Content: [Assign policies to your users in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/assign-policies#assign-a-policy-to-a-group)
* Content Source: [Teams/assign-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@packman83 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @packman83 Marcus how are you?
That is described in the New-CsGroupPolicyAssignment article but I'll propose adding that also to this article and we'll see if it gets approval.
Thanks for your feedback.
