### ISSUE TITLE
guest inviter role still not supported in Teams?

### ISSUE THREAD

**Issue by alexjeitler** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5706]
Is it still correct that the guest inviter role is not supported in Teams?
Because if I disable "Members can invite" in the External collaboration settings in Azure AD and I give an non-admin user the guest inviter role he can add guests form Teams Client. If I remove the guest inviter role he can't. So it seems to work for me. Or am I understanding anything wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93906e31-cd28-702d-bb7e-fcc2529df363
* Version Independent ID: afe4d6ed-cdcb-77e0-0951-f3c69e2463e1
* Content: [Add a guest to a team - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/add-guests?source=docs#feedback)
* Content Source: [Teams/add-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/add-guests.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@alexjeitler Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by alexjeitler** [comment]
Hi Manuela,

I saw there was a change recently and now the mention of the limitation is gone.
Can you conform that my observation was right?

Thanks and br,
Alex

Von: Manuela Scanu <notifications@github.com>
Gesendet: Dienstag, 8. September 2020 06:15
An: MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com>
Cc: Alexander Jeitler <Alexander.Jeitler@itsdone.at>; Mention <mention@noreply.github.com>
Betreff: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] guest inviter role still not supported in Teams? (#5706)


@alexjeitler<https://github.com/alexjeitler> Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
