### ISSUE TITLE
BTN Field Required or NOT????

### ISSUE THREAD

**Issue by jdipaola7** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5707]
[Enter feedback here]
Document states the following...  
Partial-port This is when you're only transferring some of your phone numbers from your current service provider to Teams. When you want to port some of the phone numbers tied to the same BTN, you  **must not include**  the BTN along with all of the other phone numbers on your account.

For example, let's say your BTN is +1 425-555-1234 and you want to port only 5 of your 25 phone numbers (+1 425-555-1235 through 1259). When you follow the instructions below to transfer your numbers, you would enter: +1 425 555 1235 - +1 425 555 1239.

Here is the problem.....
This is not clear.  If you follow the instructions, you have to enter a number in the BTN field.  Above it says **not to enter the BTN for a partial move**.  So, what do you enter in the BTN field, a fictitious number?  It is not clear.  
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a17293e0-4c49-0e97-d5da-b48322f10928
* Version Independent ID: c38c0726-5dec-d374-6948-2188d43025ef
* Content: [What's a port order? - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/phone-number-calling-plans/port-order-overview)
* Content Source: [Teams/phone-number-calling-plans/port-order-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phone-number-calling-plans/port-order-overview.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@jdipaola7  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @jdipaola7 how are you?
I think that phrase is not referring to the BTN field itself

![image](https://user-images.githubusercontent.com/36666927/98845467-60af1e80-2413-11eb-8a90-ff29c9ce530e.png)

but to the _Add numbers_ page described in step 5 here https://docs.microsoft.com/en-us/MicrosoftTeams/phone-number-calling-plans/transfer-phone-numbers-to-teams

So you won't include your BTN number on the actual list of numbers to port.

@LanaChin can you kindly confirm?
Thanks

**Comment by get-itips** [comment]
@cichur I understand you are taking over Lana's.
Can you kindly review and confirm my conclusions here? I appreciate!

**Comment by jdipaola7** [comment]
@cichur @get-itips   I now understand, ticket closed. Thanks.
