### ISSUE TITLE
No instructions for US

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5708]
There should be instructions for how to handle this from the United States. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d4bb5c7-dcc3-60bb-dd4a-88a9dc5cfa3d
* Version Independent ID: 5eb5f2d4-7d27-1b14-da1f-98a25512fb29
* Content: [Toll-free dialing limitations and restrictions - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/toll-free-dialing-limitations-and-restrictions)
* Content Source: [Teams/toll-free-dialing-limitations-and-restrictions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/toll-free-dialing-limitations-and-restrictions.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@StuBeck32  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@tonysmit Hi Tony, could you please assist.

**Comment by scanum** [comment]
Hi @tonysmit Hope you are well. Wanted to follow up here to see if there is an update? Please let us know if there is anything we can do to help. Thanks.

**Comment by StuBeck32** [comment]
This is almost 2 years old, maybe we can re-assign it to someone else?

**Comment by Reeced40** [comment]
@StuBeck32 thanks for reaching out. It seems the article was updated a while ago with USA details. Please have a look and let me know. Thanks again.

**Comment by StuBeck32** [comment]
The sidebar wasn’t updated to include this, just the drop down list

**Comment by CarolynRowe** [comment]
The sidebar means the TOC.  However instructions are available for the United States.  It's in the drop-down list which links to the article:  https://learn.microsoft.com/en-us/microsoftteams/toll-free-dialing-limitations-and-restrictions/toll-free-dialing-restrictions-in-the-united-states-u-s .  Closing this issue.
