### ISSUE TITLE
Power Automate link is not working

### ISSUE THREAD

**Issue by hroderick** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5709]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac12129f-4d94-cbbd-4c34-03666617c889
* Version Independent ID: 015463d6-8fb9-7240-a3f1-8ae288dd9e90
* Content: [Manage the Lists app for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-lists-app)
* Content Source: [Teams/manage-lists-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-lists-app.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hroderick  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@hroderick Thank you for reaching out. Please see if this is the right link - https://flow.microsoft.com
