### ISSUE TITLE
This PowerShell snippet only configures 1 mailbox, it does not change the default domain in Microsoft 365

### ISSUE THREAD

**Issue by yvesrosius** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5712]
https://docs.microsoft.com/en-us/microsoftteams/bookings-app-admin#changing-your-default-domain-when-setting-up-bookings-mailboxes

This PowerShell snippet only configures 1 mailbox, it does not change the default domain in Microsoft 365

> If you need to change the default domain after your Bookings mailbox has already been created, you can do so with PowerShell:
> Set-Mailbox -identity business@domain.onmicrosoft.com -WindowsEmailAddress business@domain.com -EmailAddresses business@domain.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1cf44b6-0499-9a1f-aa73-48e777fbe4a0
* Version Independent ID: b9af859f-9ff2-8975-b900-33fc8c087cae
* Content: [Bookings app and virtual visits in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/bookings-app-admin)
* Content Source: [Teams/bookings-app-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/bookings-app-admin.md)
* Service: **msteams**
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@yvesrosius  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@yvesrosius Thank you for your feedback. Do you have any suggestion for me to add to the PowerShell?

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
