### ISSUE TITLE
What on earth do the different colors mean?

### ISSUE THREAD

**Issue by mathananya** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5713]
Hi Microsoft Official,
I have often seen different colours (e.g. white, purple etc.) on the left-side outline of meetings in the teams calendar. What is the difference between them? I haven’t seen any documentation on it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca7f5d7b-fdf3-f9a7-46e7-689258f33cf9
* Version Independent ID: 86f27884-7c71-ee17-aa4e-5b3e12125814
* Content: [Meetings in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/tutorial-meetings-in-teams?tutorial-step=1)
* Content Source: [Teams/Tutorial-Meetings-in-Teams.yml](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/blob/live/Teams/Tutorial-Meetings-in-Teams.yml)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@mathananya Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
