### ISSUE TITLE
Default Option - Teams Only mode

### ISSUE THREAD

**Issue by BillWeidenborner** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5714]
It is unclear if there is a default for the upgrade policy (if this is a required setting). Is it possible to have no upgrade policy at all? Is there default? Most importantly for us, is Teams Only the default?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffbf0bfd-c15e-b10b-0cc9-6a27ac1e6634
* Version Independent ID: 58575371-9e09-fadb-76f6-7491df8580a3
* Content: [Setting your coexistence and upgrade settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/setting-your-coexistence-and-upgrade-settings)
* Content Source: [Teams/setting-your-coexistence-and-upgrade-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/setting-your-coexistence-and-upgrade-settings.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocspr  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@BillWeidenborner Thank you for reaching out. Please see related issue #1302 and comment - You can use the following cmdlet to set your users to "Teams-only"
Grant-CsTeamsUpgradePolicy -PolicyName tag:UpgradeToTeams
(see also: https://docs.microsoft.com/powershell/module/skype/grant-csteamsupgradepolicy?view=skype-ps)
Please let me know if this helps at all.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
