### ISSUE TITLE
ScheduleWithdrawn operation type missing from Shifts audit events

### ISSUE THREAD

**Issue by buildbod** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5715]
I have spotted ScheduleWithdrawn listed as an Operation in our audit logs. It is missing from the audit log activities list.

It appears as Operation":"ScheduleWithdrawn" in the logs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e51e97-ff97-c5eb-6517-21ce9a563ca4
* Version Independent ID: d3dc21b2-d90a-fbe7-8473-fff0b55feafb
* Content: [Search the audit log for events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audit-log-events#shifts-in-teams-activities)
* Content Source: [Teams/audit-log-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audit-log-events.md)
* Service: **msteams**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@buildbod  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@buildbod Thank you for pointing this out. Please could you supply me with the "Friendly Name" and "Description" for ScheduleWithdrawn, so I can add it? Thanks.

**Comment by buildbod** [comment]
How about:

Friendly name

Schedule withdrawn

Operation

ScheduleWithdrawn

Description

A user successfully withdraws a published schedule
________________________________

**Comment by Reeced40** [comment]
@markjjo please check for merge. Thanks.

**Comment by markjjo** [comment]
@Reeced40 @buildbod Please note that **most all** friendly names for auditing activities used the past tense verb. For example, Edited, Modified, Viewed, Deleted, Updated, Created, Moved etc. So to snap to that standard, we should use "Withdrew schedule" in this case. Note also that  we have a "Withdrew sharing invitation" for a SharePoint activity. I will make the change for the friendly name in #5866 - "Withdrew schedule"
