### ISSUE TITLE
could you add the location and dureation (21days) of Storage of Azure Media Service for customers that disables Stream ? Thanks

### ISSUE THREAD

**Issue by mamrouni** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5720]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84f319aa-94de-bed1-2e5d-c6fe24436dac
* Version Independent ID: ee6daf32-7e03-801c-dd1b-50bf35e4635e
* Content: [Location of data in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/location-of-data-in-teams)
* Content Source: [Teams/location-of-data-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/location-of-data-in-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@mamrouni Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
