### ISSUE TITLE
Crucial Info missing..

### ISSUE THREAD

**Issue by M365GitHubCloud** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5723]
[This page talks about starting with first "Chat, teams, channels, & apps in Microsoft Teams" for the phased options, but it does not even talk about how to set it up for these features/workload only and other options Meetings and voice features are turned off.  please update the articles with step by steps guidance so people can turn on only "Chat, teams, channels, & apps in Microsoft Teams" and other things are turned off. thanks ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c73be3fd-282d-8e5a-02f8-37d2f27c95ab
* Version Independent ID: 0baeeca3-237f-31dc-d3da-35140b9ebb9a
* Content: [Chat, teams, channels, & apps in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/deploy-chat-teams-channels-microsoft-teams-landing-page#core-deployment-decisions)
* Content Source: [Teams/deploy-chat-teams-channels-microsoft-teams-landing-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/deploy-chat-teams-channels-microsoft-teams-landing-page.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@M365GitHubCloud  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@M365GitHubCloud Thank you for reaching out. At a quick glance, I see that this article was updated a few days ago with new information. Please check and confirm if it's still missing crucial information. Thank you.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
