### ISSUE TITLE
Question on ordering new service toll free numbers in this KB

### ISSUE THREAD

**Issue by jiaqin107** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5745]
Hi team, 

I found the process related ordering new toll free service numbers for Switzerland might be not clear enough in this KB.

According to the other document (https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk) user needs to send separate email to PSTN service desk if they want to order new toll free service numbers for Switzerland.

Would you please help to check and possibly update this document so that we might be redirected to the right team directly?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07228d0f-eff0-4c78-b675-f43c14c241ab
* Version Independent ID: a9e2e70b-2e5f-62d7-5290-c734f4ac2f0c
* Content: [Availability in Switzerland - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-switzerland#toll-and-toll-free-numbers-for-services)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-switzerland.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-switzerland.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@jiaqin107  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
