### ISSUE TITLE
default conferencing toll number

### ISSUE THREAD

**Issue by mike-yam** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5747]
About below information:

`For a new user, the default conferencing toll numbers is assigned based on the Usage Location that is set in the Microsoft 365 administration center of the user when the user is enabled for the Audio Conferencing service. If there is a toll number in the conference bridge that matches the country of the user, that number will be automatically assigned as the default toll number of the user. `

If we have multiple toll numbers in a country, for example Leeds and London in UK. When we have new user whose usage location is UK, the system always assign Leeds's number as the default. Is it possible to set the auto assignment with other specific numbers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dc173c-0c98-1b94-a2f7-0a34781c985a
* Version Independent ID: a1c44ccb-67f3-f98e-6569-f938e88ddc63
* Content: [Set the phone numbers included on invites - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-the-phone-numbers-included-on-invites-in-teams)
* Content Source: [Teams/set-the-phone-numbers-included-on-invites-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-the-phone-numbers-included-on-invites-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@mike-yam Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by tonysmit** [comment]
Once the user is enabled for the Audio Conferencing service, the default toll and toll-free phone numbers of the user can be changed by the tenant administrator from their initial values at any moment.
