### ISSUE TITLE
Live Events - recording limits

### ISSUE THREAD

**Issue by khilker15** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5748]
In the Live Events section of this Teams Limits doc, please include the limits of recording availability as documented here:
https://support.microsoft.com/en-ie/office/schedule-a-teams-live-event-7a9ce97c-e1cd-470f-acaf-e6dfc179a0e2?ui=en-us&rs=en-ie&ad=ie

and here:
https://docs.microsoft.com/en-us/MicrosoftTeams/teams-live-events/plan-for-teams-live-events

One doc mentions 180 days, the other mentioned 30 days.  The differences aren't always clear to customers, and putting them side by side with an explanation, in a single doc, would help clarify things.

Thanks,
Ken Hilker

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#teams-live-events)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@khilker15  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by cichur** [comment]
Hi, I'm researching this issue. Cindy

**Comment by cichur** [comment]
I've made the change and it's published. https://docs.microsoft.com/en-us/MicrosoftTeams/teams-live-events/plan-for-teams-live-events
