### ISSUE TITLE
Recursive reference doesn't lead to correct entry.

### ISSUE THREAD

**Issue by SQuintin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5749]
[Enter feedback here]

The line "Learn how to use the team templates in the admin console." contains a hyperlink to the same page you're already on. This page does not contain instructions for using team templates in the admin console.

Additionally, the link to this page (the github feedback form) contains a unicode emoji that needs to be edited before this feedback form loads.

---
#### Document Details

 *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d884cb-c126-b5dc-ff90-1a31aa61bf5b
* Version Independent ID: ed5054d7-d679-7fad-fd5d-9cd393644b9d
* Content: [Get started with Teams templates using Microsoft Graph - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-started-with-teams-templates)
* Content Source: [Teams/get-started-with-teams-templates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-started-with-teams-templates.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@SQuintin  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@SQuintin thank you for reaching out. I've just checked the article and it looks like it could have been updated in the interim. Please confirm from your side. Thanks.

**Comment by SQuintin** [comment]
It's been updated, but it's still recursive and possibly more confusing
than ever.
This page (
https://docs.microsoft.com/en-us/microsoftteams/get-started-with-teams-templates)
says "You can create your own template in the admin console" and links you
here:
https://docs.microsoft.com/en-us/microsoftteams/get-started-with-teams-templates-in-the-admin-console
This page (
https://docs.microsoft.com/en-us/microsoftteams/get-started-with-teams-templates-in-the-admin-console)
says "Currently you can create a team from a template in Teams or using
Microsoft Graph." and then links you back to the previous page.
Further, both pages contain the same content below the top section, so
they're duplicative, adding to the confusion.

Since the graph page points to the admin center page for "create your own
template in the admin console", one would expect the linked page to
describe the process. That content is nowhere to be found.

**Comment by Reeced40** [comment]
@SQuintin thank you for clarifying. I found these articles. Please let me know if I should add the links to this document to help other users - https://techcommunity.microsoft.com/t5/microsoft-teams-blog/create-teams-quickly-with-templates-in-microsoft-teams/ba-p/1394163 and https://docs.microsoft.com/microsoftteams/get-started-with-retail-teams-templates

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
