### ISSUE TITLE
Inappropriate translation: "Walkie Talkie" - "トランシーバーie" in Japanese

### ISSUE THREAD

**Issue by git188** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5751]
"Walkie Talkie" is translated as "トランシーバーie" in Japanese page, but it must be "トランシーバー".
https://docs.microsoft.com/ja-jp/MicrosoftTeams/walkie-talkie

Also, when its URL is pasted in Teams, its title is translated "internet explorerのトランシーバー アプリケーション" as below.
![image](https://user-images.githubusercontent.com/70936396/92839860-64c2be00-f41b-11ea-9722-a149a430f07b.png)
It is a mistranslation of "ie".

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: d91ddefc-3722-8bc2-bd9b-4a90ede28944
* Version Independent ID: 35e56a9d-a01c-4126-3750-aae1ed984f55
* Content: [Microsoft Teams での internet explorer のトランシーバーアプリケーション - Microsoft Teams](https://docs.microsoft.com/ja-jp/MicrosoftTeams/walkie-talkie)
* Content Source: [Teams/walkie-talkie.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/walkie-talkie.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@git188 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@officeglobal Could you please help with this issue? Thanks!

**Comment by TinaMcN** [comment]
@git188 Thank you for reporting this issue. It appears to be a problem with our machine translation tool. I sent the article to be human translated.
@officeglobal, please let us know when the updated article is published.

**Comment by OfficeGlobal** [comment]
@git188 , @TinaMcN the article was HumantTranslated and published live

**Comment by scanum** [comment]
@TinaMcN  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
