### ISSUE TITLE
Cross tenant url teams personal tab

### ISSUE THREAD

**Issue by jonathanhotono** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5752]
I tried to add a cross tenant url into the `staticTabs` , it works on MS Teams web, but not on MS Teams Desktop. 
Sample manifest below:
![image](https://user-images.githubusercontent.com/6864547/92842935-845fe380-f427-11ea-93ce-d6f56a3046d0.png)
Valid domains are set to support *.sharepoint.com
![image](https://user-images.githubusercontent.com/6864547/92842982-92156900-f427-11ea-8380-2790d168f7bc.png)

This [article]( https://docs.microsoft.com/en-us/MicrosoftTeams/teams-standalone-static-tabs-using-spo-sites) doesn't explicitly mention it supports cross tenancy. Is there any reason why it supports cross tenant url on web version but not on desktop version? Both tenants have full trust as one is child company that requires access to one of sharepoint page in parent company tenant. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611ed1ac-09a9-3491-7fa8-d282b4558fbe
* Version Independent ID: b5a1dba5-beab-7188-fe18-0a045814dde0
* Content: [Create a Teams 'Intranet Portal app' from a SharePoint Online site or page - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-standalone-static-tabs-using-spo-sites)
* Content Source: [Teams/teams-standalone-static-tabs-using-spo-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-standalone-static-tabs-using-spo-sites.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@jonathanhotono Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jonathanhotono** [comment]
Hi @scanum I was inquiring based on the article provided whether the cross tenancy link is actually **supported** on desktop app, and if not is there any plan ongoing forward to support links from **tenant1**.sharepoint.com to **tenant2**.sharepoint.com? Because on both mobile app & web app it works just fine.
