### ISSUE TITLE
Pay-Per-Minute Audio Conferencing SKU not supported

### ISSUE THREAD

**Issue by NickElniff** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5753]
There needs to be an additional note that states that this feature is not available for users with the "Pay Per Minute Audio Conferencing" license.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d4b1670-ab39-621e-025e-17d7d747cc09
* Version Independent ID: dcdd8284-ad29-4e46-4731-63fbbce08fb0
* Content: [On-network Conferencing for Audio Conferencing - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/audio-conferencing-on-network#enable-the-routing-of-dial-in-calls-to-microsoft-audio-conferencing-through-direct-routing)
* Content Source: [Teams/audio-conferencing-on-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-on-network.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@NickElniff Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@NickElniff  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
