### ISSUE TITLE
 Audio Conferencing Pay per Minute sku cannot be used 

### ISSUE THREAD

**Issue by BSwagger** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5754]
[Enter feedback here]
Please include that meetings organized with Audio Conferencing Pay per Minute sku cannot use Direct VOIP/On-Net Conferencing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c621a9c-ce55-e3a6-4220-3f9f1192efee
* Version Independent ID: 5e79fabf-8aa3-96b1-3e94-23904e9fd375
* Content: [Cloud Consolidation for Teams and Skype for Business - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/cloud-consolidation)
* Content Source: [Skype/SfbHybrid/hybrid/cloud-consolidation.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/cloud-consolidation.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@BSwagger Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@BSwagger thank you for reaching out and helping improve MS Docs. Please can you suggest under which heading in this article the note should be added?

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
