### ISSUE TITLE
Inappropriate translation : "Number of people in a video or audio call from chat" in Japanese

### ISSUE THREAD

**Issue by MitsuhiroTakemoto** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5755]
"Number of people in a video or audio call from chat" should be translated as "チャットから開始されるビデオまたは音声通話に参加できるユーザー数".
Current description looks like a mistranslation.

![image](https://user-images.githubusercontent.com/38097959/92942043-14377900-f48c-11ea-9c33-43b7d757f5ce.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Microsoft Teams の制限事項と仕様 - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@officeglobal Could you kindly help with this issue? Thanks!

**Comment by Reeced40** [comment]
@OfficeGlobal

**Comment by Reeced40** [comment]
@OfficeGlobal any update yet?

**Comment by OfficeGlobal** [comment]
@MitsuhiroTakemoto , @Reeced40  the article was updated with proposed translation and published live

**Comment by scanum** [comment]
@MitsuhiroTakemoto  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by MitsuhiroTakemoto** [comment]
Thank you very much!

Best regards,
Mitsuhiro
