### ISSUE TITLE
Everyone in the Organization

### ISSUE THREAD

**Issue by JoVa99** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5759]
The section 

"Everyone in the organization Users can create live events that people in your organization, including guest users added to your organization" 

is confusing, since on lots of other places, the 'Organization' indicates only users in the company, excluding Guests. I would expect 'Everyone' to include the Guests, and 'Everyone in the organization' would exclude Guests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9aa4676-855a-fddb-bb0b-96b7095c695e
* Version Independent ID: 7c39f08c-0d56-6d29-1356-879d9d6ff51c
* Content: [Set up for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-live-events/set-up-for-teams-live-events)
* Content Source: [Teams/teams-live-events/set-up-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/set-up-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@JoVa99 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@LanaChin please can you give some clarification on this issue and the wording in the article.

**Comment by LanaChin** [comment]
Hi @JoVa99, the article outlines the distinction between **Everyone** and **Everyone in your organization**, where **Everyone** includes external people, and **Everyone in your organization** includes internal people _and_  guest users that were added.  For more info about adding guest users, see https://docs.microsoft.com/microsoftteams/add-guests.  Thank you.
