### ISSUE TITLE
This page is linked from the "add a location" section of Microsoft Teams Phone Number setup

### ISSUE THREAD

**Issue by missilelaunchr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5761]
[Enter feedback here]

This content is linked from this field:
"Emergency Location Identification Number (ELIN)"

However the content is overly long and does not explain the field or what to put in it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ede6de99-ead2-fdb1-22f4-8b8240829732
* Version Independent ID: ed36687a-c091-44e3-1d8e-1025d1209fec
* Content: [Sensitivity labels for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/sensitivity-labels?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/sensitivity-labels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sensitivity-labels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@missilelaunchr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@missilelaunchr thank you for reaching out and helping improve MS Docs. Please can you provide some clarity on what is needed to be amended in which article to make it clearer as per the document referenced here.

**Comment by missilelaunchr** [comment]
This document does not help you "add a location" in Microsoft Teams Phone
Number Setup, so that is the content you'd need to add.  This document was
linked frmo that section of Microsoft Teams implying the document will help
with that section of the product. If you want to improve your products,
please go through the "add location" portion of Microsoft Teams Phone
Number setup and observe that area links to this document which is of no
help.  I find that many Microsoft products link to documents that have no
content pertaining to the linking section of the product and are not
helpful, or articles that link to other articles that do not have relevant
information.  This is frequently complained about online and in
communities.  It's likely difficult to fix, because you are not on the team
that linked to this document, and probably have no say over that team or
the product in which they linked this document.  But this is Microsoft
problem to solve, if I was to solve it, I think each document which is
linked to from a product should have some internal metadata record so you
know which products have linked to a document and why, that way you can
ensure the documents are not deleted or relevant information from the
linking product is not removed.

Best Regards

**Comment by lindspea** [comment]
@missilelaunchr sorry for the inconvenience this has caused. The team is working on a fix at the moment. In the meantime please have a look at this techcommunity article - https://techcommunity.microsoft.com/t5/microsoft-teams/cannot-add-number-in-teams-location-not-found/m-p/1009611.
