### ISSUE TITLE
Use public IP for Trusted IP ?

### ISSUE THREAD

**Issue by nkv75** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5762]
Hi,

Correct me if I'm wrong but Trusted IPs are public IPs, so why using private IPs range in this documentation that could lead to some misunderstanding at first read ? There is RFC 5737 proposing to use demo address ranges 192.0.2.0/24 (TEST-NET-1), 198.51.100.0/24 (TEST-NET-2), and 203.0.113.0/24 (TEST-NET-3) for such documentation usages, https://tools.ietf.org/html/rfc5737
Thanks !
Eric
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad0130c8-4343-ba04-cd55-0c3305a14347
* Version Independent ID: 24db6f00-bfdc-ea9c-6922-e9f09e5cef27
* Content: [Direct Routing Local Media Optimization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-media-optimization-configure)
* Content Source: [Teams/direct-routing-media-optimization-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-media-optimization-configure.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@nkv75 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by nkv75** [comment]
I don't have issue that would need me to open a ticket to solve anything, I was just giving advice to change the documentation as already asked in these comments by someone else, as you documented trusted IPs with private IPs sample, while it should be public IPs. I leave it with you to decide to move it internally to MS.
