### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mjwhirly** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5764]
The following page has a typo on the Interpret the report section. 

Callout #3 says :

Each report has a date for when this report was generated. The reports usually reflect a 24 latency from time of activity.

When it should be the following:

Each report has a date for when this report was generated. The reports usually reflects a 24 hour latency from time of activity.

![Screen Shot 2020-09-14 at 8 01 36 AM](https://user-images.githubusercontent.com/5760010/93083882-40f0b980-f661-11ea-8dda-c3fa5b8c8b38.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2758a3d6-c646-dcb0-2a31-c7b9b84e780b
* Version Independent ID: 8704c9fe-f8b0-82d2-bd83-3fd1a9ad638d
* Content: [Microsoft Teams user activity report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report)
* Content Source: [Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by lindspea** [comment]
@mjwhirly thank you for reaching out. I see the PR has been done to apply the change and should reflect in a few days after merging. Thanks for helping improve MS Docs.
