### ISSUE TITLE
No troubleshooting for Outlook for Mobile or Webmail

### ISSUE THREAD

**Issue by SQuintin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5765]
[Enter feedback here]
This page to in-depth in troubleshooting missing Teams-add-in for Outlook for Windows, but doesn't touch on troubleshooting the missing add-in for Outlook for Mobile (iOS or Android), Webmail, or Outlook for Mac.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Use the Microsoft Teams Meeting add-in in Outlook - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook#teams-meeting-add-in-in-outlook-for-windows-does-not-show)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@SQuintin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@SQuintin thank you for reaching out and helping improve MS Docs. Does this link help at all - https://docs.microsoft.com/office/dev/add-ins/outlook/outlook-mobile-addins

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by SQuintin** [comment]
No. The add-in in question is a Microsoft add-in, an official Teams add-in
that is auto-added when certain conditions are met.
The linked article is not about the Microsoft add-in at all.
