### ISSUE TITLE
do not have access to edit the page

### ISSUE THREAD

**Issue by Ariantor** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5767]
I am SfB Server Release Management, I used to have access to edit the page. The edit (pencil) is now grayed out, can somebody help me asap?  Thank you!   Here is the page https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/07fe40c3352c83d0ed1da077afe787f55df41627/Skype/SfbServer/sfb-server-updates.md

**Comment by get-itips** [comment]
Hello @Ariantor probably because that url references another branch, try this

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/sfb-server-updates.md

**Comment by Ariantor** [comment]
Thank you! That works.

**Comment by get-itips** [comment]
> Thank you! That works.

Glad to hear!

**Comment by Ariantor** [comment]
Hi Andres = could you approve the changes I just made?

Thanks,
Ari.=

**Comment by get-itips** [comment]
> Hi Andres = could you approve the changes I just made? Thanks, Ari

for me they are ok! but do not have permissions to merge, let's ask @scanum

**Comment by Ariantor** [comment]
Thanks Andres, this has been taken care. Thanks again!

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
