### ISSUE TITLE
herop

### ISSUE THREAD

**Issue by timscharfenort** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#577]
[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: f7b32af2-59db-a872-6ed4-fc7b4cd910b3
* Version Independent ID: 38fd3a1a-ee6d-dd63-0de9-5f726d7419cf
* Content: [Reise von Skype for Business zu Teams](https://docs.microsoft.com/de-de/microsoftteams/journey-skypeforbusiness-teams)
* Content Source: [Teams/Journey-SkypeforBusiness-Teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.de-DE/blob/live-sxs/Teams/Journey-SkypeforBusiness-Teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by LolaJacobsen** [comment]
Hi, @timscharfenort. What are you looking for in this article?  Thanks!
