### ISSUE TITLE
in-built connector +  CallRecords

### ISSUE THREAD

**Issue by MAGROULX** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5771]
Based on the release of an in-built connector to connect Microsoft Teams logs to Sentinel, is this all still relevant?  Would it be possible to get additional detail on what's not captured using the in-built connector?  Is CallRecords Activity captured automatically if selecting to monitor Teams with Sentinel?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0157c71c-b57d-ecdf-d2de-1d6f02eaf238
* Version Independent ID: 25eae9c1-9730-a88b-066d-75e9116f389c
* Content: [Azure Sentinel and Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-sentinel-guide)
* Content Source: [Teams/teams-sentinel-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-sentinel-guide.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@MAGROULX Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
