### ISSUE TITLE
Edu SKUs is supported or not?

### ISSUE THREAD

**Issue by hsantan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5772]
Currently on my tenant Edu I enabled the sensitivity labels and 'm using to my users. 

This page mentioned that isn't supported yet for Edu SKUs 

I want to know if is supported or not? 

line on the document
_Support for sensitivity labels in Teams EDU SKUs

_Sensitivity labels are currently unsupported for customers using Teams Education SKUs.__

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ede6de99-ead2-fdb1-22f4-8b8240829732
* Version Independent ID: ed36687a-c091-44e3-1d8e-1025d1209fec
* Content: [Sensitivity labels for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sensitivity-labels)
* Content Source: [Teams/sensitivity-labels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sensitivity-labels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hsantan Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
