### ISSUE TITLE
Document scenarios for "Call Me" feature

### ISSUE THREAD

**Issue by dotnick365** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5774]
Can we please document the scenarios where "Call Me" will or won't be available?

Can we please explicitly document the following scenarios or questions related to the Call Me feature. Either on this page or a new page.

1) Does using Call Me require the user to be licensed for Audio Conferencing, or only the meeting organizer?
2) How does Call Me function for "federated" meeting attendees? Can it be used? Does it depend on the policy/license in the users home tenant or the configuration of the tenant where the meeting is being hosted?
3) For B2B guest users can Call Me be used? 
4) For anonymous participants can call me be used or enabled?

There seem to be many scenarios where Call Me will/won't be available for a meeting participant and it's often not clear if these are a result of configuration, or design limitations. Would be great to have the above clarifications so that there can be clarity regarding the scenarios where Call Me will/won't be available to an end-user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b759f354-bf74-3cff-0c96-3b28a27ee997
* Version Independent ID: fb2d8a68-f35a-bbee-a306-72ee20a450a3
* Content: [Set up the Call me feature for your users - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-the-call-me-feature-for-your-users)
* Content Source: [Teams/set-up-the-call-me-feature-for-your-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-the-call-me-feature-for-your-users.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@dotnick365 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
