### ISSUE TITLE
Landline and mobiles

### ISSUE THREAD

**Issue by Richard-Barr3tt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5775]
On this page I think we should state if this is landline calls to these 196 countries or mobiles in the 196 countries as well

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 844ea2d4-1b0a-8e37-4085-0a2ec2138887
* Version Independent ID: 0fee359f-49e9-4b7b-ad22-1a566529de9f
* Content: [Make outbound calls to these countries/regions - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/users-can-make-outbound-calls-to-these-countries-and-regions)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/users-can-make-outbound-calls-to-these-countries-and-regions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/users-can-make-outbound-calls-to-these-countries-and-regions.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Richard-Barr3tt Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Richard-Barr3tt thank you for reaching out and helping improve MS Docs. As far as I know it refers to mobile and landlines. Please confirm @CarolynRowe

**Comment by tiburd** [comment]
@Richard-Barr3tt - [This article](https://docs.microsoft.com/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/users-can-make-outbound-calls-to-these-countries-and-regions) refers to phone calls made **from** Microsoft Teams or Skype for Business **to** both landline and mobile phone numbers.

For more information, see [this article about calling plans](https://docs.microsoft.com/microsoftteams/calling-plans-for-office-365).

Closing this issue.

Thank you!
