### ISSUE TITLE
Supported Clients

### ISSUE THREAD

**Issue by dotnick365** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5776]
Call Me seems to work with the Windows Desktop, and iOS Teams client. It does not seem to be an option on the Web Client.

Can we update the article, or is there a different article which covers which client version do/don't support the call me feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b759f354-bf74-3cff-0c96-3b28a27ee997
* Version Independent ID: fb2d8a68-f35a-bbee-a306-72ee20a450a3
* Content: [Set up the Call me feature for your users - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-the-call-me-feature-for-your-users)
* Content Source: [Teams/set-up-the-call-me-feature-for-your-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-the-call-me-feature-for-your-users.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@dotnick365 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
