### ISSUE TITLE
New SIP Proxy IP Addresses in Australia

### ISSUE THREAD

**Issue by jamescussen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5779]
Two new IP Addresses have been added to the SIP Proxy list that reside in Sydney and Melbourne Australia:

- 52.114.16.74
- 52.114.20.29

There is nothing in this document that talks about these new Proxy servers, for example in this section there is no mention of the new Australian based SIP Proxies:

"For example, we do not have a SIP proxy component now in Australia (SIP flows via Singapore or Hong Kong) but we do have the media processor locally in Australia."

"Locations where both SIP proxy and media processor components deployed:

US (two in US West and US East datacenters)
Europe (Amsterdam and Dublin datacenters)
Asia (Singapore and Hong Kong datacenters)"

This text all needs to be updated to mention these new SIP Proxies. Some information also needs to be added as to when sip.pstnhub.microsoft in Australia will start resolving to these new Proxy addresses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e26faf8c-529e-b317-5934-cd41cfe8fa24
* Version Independent ID: 3ddd5d0a-6dbb-4940-1814-8346e293701b
* Content: [Plan Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan)
* Content Source: [Teams/direct-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@jamescussen  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@jamescussen thank you for pointing this out and helping improve MS Docs. I see this information has been updated in the interim. Please check from your side and let me know. Thanks.

**Comment by scanum** [comment]
@jamescussen  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
