### ISSUE TITLE
Default calling and meetings application policy via InTune?

### ISSUE THREAD

**Issue by legwind** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#578]
Not sure where to find this policy.  Have deployed Teams (preview) to our Hub but its not visible in the Start menu. Also, successfully enrolled the Hub in Intune without needing to be in the Windows Insider Program.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f256cd5b-3ec8-2d55-9ae4-ff9849d52eae
* Version Independent ID: 52c2271b-df38-5dc9-c2a1-553cdf3b5496
* Content: [Deploy Microsoft Teams for Surface Hub](https://docs.microsoft.com/en-us/microsoftteams/teams-surface-hub)
* Content Source: [Teams/teams-surface-hub.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-surface-hub.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by SharS** [comment]
Jatin, can you review and respond?

**Comment by pateljatin** [comment]
Microsoft Teams app launcher is not available in the Start menu similar to Skype for Business. It is available as part of the Core launchers both on the Welcome screen and Start screen.  The icon is labeled as "Call" button.  Here's the [User documentation](https://support.office.com/en-us/article/join-a-private-meeting-in-teams-77aa209c-fc98-48c8-b356-c168d911f66a?ui=en-US&rs=en-US&ad=US#ID0EAABAAA=Surface_Hub).

Note: Enrollment in Windows Insider program is required or else Teams will not be able to join meetings and/or make calls.

**Comment by kenwith** [comment]
Thanks!
