### ISSUE TITLE
teams クラスについて

### ISSUE THREAD

**Issue by wataru-jaaw** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5780]
クラスの人数に制限があるのは理解しました。下記の様に有りますが、フォームスで作成した課題配信、返却管理等は1000人以上の規模でも可能でしょうか。

クラスチームは、200を超えるメンバーをサポートできます。 ただし、チーム内でアサインメントアプリまたはクラスノートブックアプリのいずれかを使用する場合は、メンバー数を上記の上限未満に保つ必要があります。
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Microsoft Teams の制限事項と仕様 - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@wataru-jaaw  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
@officeglobal Could you kindly help with this? Thanks!

**Comment by TinaMcN** [comment]
@scanum, this appears to be a question about Teams functionality.   Roughly translated to English the comment is: 
"I understand that there is a limit to the number of people in the class. As shown below, is it possible to distribute issues created with forms, manage returns, etc. even on a scale of 1000 or more people?
Class teams can support over 200 members. However, if you want to use either the Assignments app or the Class Notebook app within your team, you must keep the number of members below the above limit."

Can you help answer this?

**Comment by lindspea** [comment]
@SerdarSoysal would you be able to provide clarity please?

**Comment by lindspea** [comment]
@SerdarSoysal

**Comment by tiburd** [comment]
@wataru-jaaw 
Thank you for your question. We apologize for our delayed response. The article has been updated several times, so we are closing this issue. If your questions remain, you are welcome to submit new feedback.
