### ISSUE TITLE
Please update the SfB Network Assessment Tool

### ISSUE THREAD

**Issue by tripdes** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5781]
Hi,

The Skype for Business Network Assessment Tool appears to require an update, as myself and many others online (see comment section: https://ucstatus.com/2019/05/10/hands-on-with-the-skype-for-business-microsoft-teams-network-testing-companion/ as an example) are encountering inconsistent results and errors when attempting to run the NetworkAssessmentTool.exe with the /connectivitycheck switch.

We are in the midst of a Microsoft Teams deployment exercise where I work, and this is holding us back somewhat as we cannot easily determine whether all of the necessary Firewall work has been completed.

Many thanks,

Sam

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65be82b6-b7a1-9f74-c847-6e769add0801
* Version Independent ID: 45eb422b-5c3a-1623-def8-553e88027995
* Content: [Evaluate your environment for cloud voice workloads - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/3-envision-evaluate-my-environment)
* Content Source: [Teams/3-envision-evaluate-my-environment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/3-envision-evaluate-my-environment.md)
* Service: **msteams**
* GitHub Login: @rmw2890
* Microsoft Alias: **Rowille**

**Comment by scanum** [comment]
@tripdes  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@tripdes thank you for reaching out and helping improve MS Docs. @rmw2890 please could you assist here

**Comment by scanum** [comment]
@tripdes Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
