### ISSUE TITLE
Link on Second Note is broken

### ISSUE THREAD

**Issue by AndreaLuisa** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5783]
The link on the second note for this page: https://docs.microsoft.com/en-us/microsoftteams/teams-dependencies
is broken. 

ie. "Allow/Block guest access to Microsoft 365 Groups"  points to https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-group-access-to-office-365-groups

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b05e642-c4e5-f1b5-5315-d3ef1690a0cd
* Version Independent ID: 01b7e0b5-3e50-3de0-e3e9-aeeeda43da12
* Content: [Authorize guest access in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-dependencies)
* Content Source: [Teams/Teams-dependencies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-dependencies.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@AndreaLuisa  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@AndreaLuisa thank you for pointing this our and helping improve MS Docs. Would this be the correct link to have added there - https://docs.microsoft.com/microsoft-365/admin/create-groups/manage-guest-access-in-groups
