### ISSUE TITLE
Typo in the End user experience section

### ISSUE THREAD

**Issue by salakhani** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5785]
[Enter feedback here]
There is a typo in this statement "messaged" should be replaced by "messages"
"We've deleted older messaged due to your org's retention policy"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f55c52a5-5841-b9c9-1607-2013dc3f2e20
* Version Independent ID: 16d93458-5e01-646f-dac5-31306cc7f3fb
* Content: [Retention policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/retention-policies)
* Content Source: [Teams/retention-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/retention-policies.md)
* Service: **msteams**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by scanum** [comment]
@salakhani Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Many thanks for your feedback @salakhani
