### ISSUE TITLE
Allow chat in meetings - 

### ISSUE THREAD

**Issue by bec064** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5786]
"**Allow chat in meetings**
This is a per-organizer policy. This setting controls whether meeting chat is allowed in the user's meeting."

Would you mind updating this very brief topic and add if it's the -MeetingChatEnabledType parameter.

It says "per-organizer" but it's not. A per-organizer policy definition is "When you implement a per-organizer policy, all meeting participants inherit the policy of the organizer."

This is not the case. If using the -MeetingChatEnabledType it only affect the individuals being assigned the policy. No inheritance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@bec064 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @bec064 
Looks like that sentence was updated [recently](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/3db67946e0f8553fbebcba015e9bb33861acf6fc)
Thank you for your feedback!

**Comment by get-itips** [comment]
@scanum please close

**Comment by scanum** [comment]
@bec064 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
