### ISSUE TITLE
Clarify that this feature is not available anymore - 

### ISSUE THREAD

**Issue by cadasi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5789]
We need to make clear that the feature is not available anymore. The banner at the top is not enough, it's easy for someone to miss it, scroll down and think the feature is still available. We should edit the content and just make a summary of what the feature **was**. The language right now and all the explanation doesn't help to make it clear this feature is not available anymore. I have a customer that didn't read the banner, and by opening the article it took me a few minutes to find out that it is disabled. 
Also, the link for the M365 Roadmap is broken.

Also, can we check with the PM/Engineering owner for this feature and check why we decided to remove this feature completely? There was a policy (screenshot) below, so if customers didn't like this feature, they could just disable it for all the users in their company using policies. I have a customer that liked this feature, so it would be good if we could give some type of reasoning behind the decision to just cut out it.

![image](https://user-images.githubusercontent.com/38797563/93494514-f7eb7000-f8c1-11ea-96af-71041bee0f59.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5920152-5fee-41ed-56df-ad7b51b25cc2
* Version Independent ID: 88cfc850-5e36-48ee-ba99-088b2b653f1e
* Content: [Manage discovery of private teams in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-discovery-of-private-teams)
* Content Source: [Teams/manage-discovery-of-private-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-discovery-of-private-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officedocspr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @cadasi Carlos, how are you?
Looks like the article was removed.
Thanks

**Comment by get-itips** [comment]
@scanum please close

**Comment by scanum** [comment]
@cadasi Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
