### ISSUE TITLE
Limit guest invititations

### ISSUE THREAD

**Issue by Dominik-D** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#579]
The text states "Members can invite must be set to Yes."
With that setting all tenant users are eligible to invite guests to the tenant. How can we achieve to limit the guest invitation functionality to certain users?
We previously had configured the following:
Members can invite must be set to: No
Admins and users in the guest inviter role can invite: Yes

This resulted in being unable to add any guests to Teams even if the user was holding the guest inviter role. Inviting guests to Office 365 groups however was possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b05e642-c4e5-f1b5-5315-d3ef1690a0cd
* Version Independent ID: 01b7e0b5-3e50-3de0-e3e9-aeeeda43da12
* Content: [Authorize guest access in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-dependencies)
* Content Source: [Teams/Teams-dependencies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-dependencies.md)
* Service: **msteams**
* GitHub Login: @laithalshamri
* Microsoft Alias: **laal**

**Comment by kenwith** [comment]
@Dominik-D - Thank you for submitting this feedback.

This is a good catch and sorry it has taken so long to get this in the backlog.

I was now able to get this into the backlog for the Teams/Skype team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by Dominik-D** [comment]
Hello, is there any way to follow the progress on this issue?

**Comment by CrystalThomasMS** [comment]
Thank you again for your feedback! We have reached out to the product team for this area, and your request has been recorded for consideration. This item is not yet on a product sprint plan, so we cannot provide an implementation estimate at this time. Thank you again for your contribution.

**Comment by jonathaneckman** [comment]
Is there a UserVoice submission for this we can vote on? I cant find one.

**Comment by Dominik-D** [comment]
Hi Jonathan, I created one here: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/34903765-limit-guest-invitation-functionality-to-specified
Did not get much traction yet. I was hoping Microsoft would fix this without UserVoice since the feature already existed up until some months ago.
