### ISSUE TITLE
Check the requirement Teams Only

### ISSUE THREAD

**Issue by EvgenyArtemyev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5790]
[Enter feedback here]
Hello Team
What about the requirement:
Ensure that all users in your organization who are enabled, or will be enabled, for Audio Conferencing are in Teams Only mode. The routing of inbound and outboud Audio Conferencing calls through On-network Conferencing is only supported for Teams meetings.

I suppose it is redundant. Since on-network AC can work even for Island users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d4b1670-ab39-621e-025e-17d7d747cc09
* Version Independent ID: dcdd8284-ad29-4e46-4731-63fbbce08fb0
* Content: [On-network Conferencing for Audio Conferencing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-on-network)
* Content Source: [Teams/audio-conferencing-on-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-on-network.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@EvgenyArtemyev Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @EvgenyArtemyev 
Thanks for your feedback, looks like that sentence was updated recently. https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/00536104799be69a1b92c8f7c061c4c24e49022d
Thanks

**Comment by get-itips** [comment]
@scanum please close.

**Comment by scanum** [comment]
@bratsche Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
