### ISSUE TITLE
RSS link is wrong

### ISSUE THREAD

**Issue by williamlooney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5791]
[Enter feedback here]
The RSS link for the updates for the IP addresses on this page is wrong. This site has the correct RSS link: https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#skype-for-business-online-and-microsoft-teams. I've had one customer complain about this link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96088236-4cde-fe10-9023-67f3d339bdbe
* Version Independent ID: 2f4cb807-2a4d-1165-836d-7c2c688b1a2c
* Content: [Microsoft 365 and Office 365 URLs and IP address ranges - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/office-365-urls-ip-address-ranges)
* Content Source: [Teams/Office-365-URLs-IP-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-URLs-IP-address-ranges.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@williamlooney Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@williamlooney thank you for pointing this out. Just for clarification, are you suggesting replacing the link to "Subscribe via RSS" with the link you provided above?
