### ISSUE TITLE
.Net framework requirement of Teams client

### ISSUE THREAD

**Issue by naminakao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#58]
Cx reported us that they were asked .Net Framework 4.5 during installing Teams desktop client.
We confirmed it happens when trying to install the teams client on OS having .Net framework 3.5. It didn't occur when installing the client on OS having .Net Framework 4.5 or 4.7.

There is no public information about .net framework requirement. So I wonder if we could add the note in the section of Desktop Client of https://docs.microsoft.com/en-us/microsoftteams/get-clients.

**Comment by LolaJacobsen** [comment]
Thanks for reporting this! Yes, the Teams installer requires .Net framework 4.5.  I'm updating the article now (change should go live later today).
