### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by gkumra** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5803]
Please see link for  https://admin.teams.microsoft.com

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da3d209-eb82-1a62-9bd5-81ba18792cd4
* Version Independent ID: 94dca200-ab33-7a57-1504-e3ee7e5c610a
* Content: [Create a custom team template in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-gb/MicrosoftTeams/create-a-team-template)
* Content Source: [Teams/create-a-team-template.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-team-template.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@gkumra Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by cichur** [comment]
Thank you for the feedback. I've removed the link and republished the article.
