### ISSUE TITLE
Wrong Translation for FIFO

### ISSUE THREAD

**Issue by gbeaudoin78** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5807]
La traduction pour « First In, First Out (FIFO) » est erronée et rend la lecture du document confus. J'ai dû consulter l'acronyme FIFO en anglais pour comprendre le sens de la phrase.

Au lieu de  « L’appelant entend lire de la musique pendant qu’il est en attente et l’appel se connecte à la première fois, première sortie (FIFO). » on devrait lire quelque chose similaire à « L’appelant entend de la musique pendant qu’il est en attente et l’appel est connecté en fonction de l'ordre d'arrivé des appels à l'aide de la méthode premier arrivé, premier servi (First In, First Out). »

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: b755d9ae-13ac-019f-f5f4-a95b1eee2989
* Version Independent ID: f7afd8ad-e6e0-6c79-aed1-4ee87d48ba12
* Content: [Créer une file d’attente d’appel - Microsoft Teams](https://docs.microsoft.com/fr-fr/MicrosoftTeams/create-a-phone-system-call-queue)
* Content Source: [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-call-queue.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@gbeaudoin78 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officeglobal Could you kindly help with this issue? Thanks!

**Comment by TinaMcN** [comment]
@gbeaudoin78 Merci d’avoir signalé ce problème. Il semble être un problème avec notre outil de traduction automatique. J’ai envoyé l’article pour être traduit par l’homme.
@officeglobal, veuillez nous faire savoir quand l’article mis à jour est publié.

(Thank you for reporting this issue. It appears to be a problem with our machine translation tool. I sent the article to be human translated. @officeglobal, please let us know when the updated article is published.)

**Comment by TinaMcN** [comment]
@gbeaudoin78 L’article a maintenant été traduit par un humain.  Pouvez-vous s’il vous plaît vérifier si le problème est résolu maintenant?  Merci de nous avoir parlé de ce problème.

**Comment by gbeaudoin78** [comment]
@TinaMcN J'ai vérifier et le problème est résolu. L'utilisation du terme français est apprécié. Merci à vous et toute l'équipe pour la résolution du problème.
