### ISSUE TITLE
Duplicate section

### ISSUE THREAD

**Issue by HarryEmil** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5808]
These 2 sections look like one was meant to replace the other during an edit:

When you do see opportunities to enhance your service, take the time to do it right. Revisit Deploy chat, teams, channels, and apps in Microsoft Teams and apply the same guidance end to end. When making small, incremental changes, it's unlikely that you'll need to complete all activities and tasks in full, but you should be sure to evaluate each activity and task along the way to give yourself the best chance at a successful outcome.

When you do see opportunities to enhance your service, take the time to do it right. Revisit our implementation phases and apply the same guidance end to end. When making small, incremental changes, it's unlikely that you'll need to complete all activities and tasks in full, but you should be sure to evaluate each activity and task along the way to give yourself the best chance at a successful outcome.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd65cd56-d79c-4c08-d45c-281edab1e9fa
* Version Independent ID: 82def203-8f05-d8d3-2feb-30abbb18d000
* Content: [Microsoft Teams requirements - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/upgrade-enhance-my-service?source=docs)
* Content Source: [Teams/upgrade-enhance-my-service.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-enhance-my-service.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@HarryEmil Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
