### ISSUE TITLE
Copy feedback

### ISSUE THREAD

**Issue by anachetrarims** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5811]
[Enter feedback here]
@cichur this sentence is wrong
"Prior to and during a Microsoft Teams meeting or phone call, the meeting organizer has several options for choosing the bridge settings."

All these settings can only be set by the tenant admin not by the organizer. Also they apply only to meetings not to 1:1 and group calls.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4746560-0390-ea94-73bf-ad57f5926199
* Version Independent ID: 84db6582-cf8f-9a5a-eac1-09461db4c798
* Content: [Manage bridge settings in Teams - Microsoft Teams](https://review.docs.microsoft.com/en-us/MicrosoftTeams/manage-bridge-settings?branch=v-cichur-ptsn-mask-numbers)
* Content Source: [Teams/manage-bridge-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-bridge-settings.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@officedocspr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@cichur I can't seem to find this article. It give a 404 error. Please could you assist?

**Comment by cichur** [comment]
Hi,
Ana commented on a doc that was in review, so there's no action required here. Will close this ticket.
