### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by lachew** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5817]
In the documentation, it states this under How to access reports. 
"To access the reports, you must be a global admin in Microsoft 365 or Office 365, Teams service admin, **Teams communications admin**, or Skype for Business admin. " 

The Teams communication admin does not give you access to the Analytics and reports. I tested it in my demo environment and it is inconsistent with this page that is a hyperlinked. 
https://docs.microsoft.com/en-us/microsoftteams/using-admin-roles
The above link has the right information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ade1a4-092c-1132-44df-ee2c683fdd33
* Version Independent ID: 396b1aee-2f40-9895-9b00-07e38d11d31b
* Content: [Microsoft Teams analytics and reporting - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-reporting-reference)
* Content Source: [Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@lachew Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
