### ISSUE TITLE
Cuando estará disponible esta funcionalidad para organizaciones empresariales en España?

### ISSUE THREAD

**Issue by edmar-nyc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5818]
A mi no me sale ni por tareas, ni por tasks, ni to do. He consultado con el soporte técnico de Microsoft y me han informado que de momento solo esta disponible para licencias educativas. ;(
[Escriba sus comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 27c4aab7-6115-ff27-5538-0a0bf73755de
* Version Independent ID: 3ff038fc-da4d-fdf4-7b5b-071bd25e3047
* Content: [Administrar la aplicación tareas de su organización en Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/es-es/microsoftteams/manage-tasks-app)
* Content Source: [Teams/manage-tasks-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-tasks-app.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@edmar-nyc Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
