### ISSUE TITLE
Live events limits

### ISSUE THREAD

**Issue by bartvermeersch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5820]
"Difference between overflow meetings and live events
[...]
Additionally, we're increasing the length of the live events from 4 hours to 16 hours and enabling up to 50 concurrent live events per tenant."

Do you mean after acquiring this Advanced Communications add-on?

The note below the paragraph states it is only a temporarily increase till October 1st?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09168b55-8244-974e-8bb3-6ec16429a650
* Version Independent ID: c17f4f8d-a8bb-3c81-368f-07b932f52ebc
* Content: [Advanced Communications add-on for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/advanced-communications)
* Content Source: [Teams/teams-add-on-licensing/advanced-communications.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/advanced-communications.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@bartvermeersch Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
