### ISSUE TITLE
Partner logo and names needs to be updated

### ISSUE THREAD

**Issue by ccoordt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5821]
Hi,

The CVI page needs to be updated

Polycom is now Poly
Pexip logo is Old
Cisco is missing the bridge.

Kind regards

Carsten

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 046dec87-2354-a9db-ae19-3bfaa2626bef
* Version Independent ID: 23e7d18f-bbab-75e1-7c85-9b0d0e8f4382
* Content: [Cloud Video Interop for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-video-interop)
* Content Source: [Teams/cloud-video-interop.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-video-interop.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@ccoordt  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @ccoordt, thank you for your feedback and help us to improve docs.microsoft.com.

My comments:
- I'm renaming Polycom to Poly, it'll live in the next couple of days
- Pexip logo was updated on September 24
- Cisco was added on September 21
