### ISSUE TITLE
Office Audit log entries for Shifts - Clock in / clock out

### ISSUE THREAD

**Issue by buildbod** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5822]
The unified audit log includes activities for:
 	

- Clocked in using Time clock
- Clock out using Time clock

 
I can see _Clocked out_ entries in the audit but not _Clock in_. 
However the audit record for _Clocked out_ includes the _Clocked in_ data... For example:

![image](https://user-images.githubusercontent.com/13903544/93872627-53ee3400-fcc8-11ea-914f-8989fff39733.png)

Is there a bug whereby the _Clock in_ audit entries are not being recorded against the _Clock in_ audit activity. For example, searching purely on _Clocked in using Time clock_ yields no results:
 
![image](https://user-images.githubusercontent.com/13903544/93872677-69fbf480-fcc8-11ea-9276-9c4722e5e954.png)

Is it the case that _Clock in_ entries are being captured against the _Added Time_ clock entry ? For example, for the clock out activity at the top of the post there is a corresponding activity for _Added Time clock_ entry:

![image](https://user-images.githubusercontent.com/13903544/93872738-8009b500-fcc8-11ea-9ca0-639a956afb8a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e51e97-ff97-c5eb-6517-21ce9a563ca4
* Version Independent ID: d3dc21b2-d90a-fbe7-8473-fff0b55feafb
* Content: [Search the audit log for events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audit-log-events#shifts-in-teams-activities)
* Content Source: [Teams/audit-log-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audit-log-events.md)
* Service: **msteams**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@buildbod Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by markjjo** [comment]
@buildbod @scanum Also note that I have forwarded this issue to the engineering team. I'll try to follow up on this issue if there is more info or a resolution.

**Comment by buildbod** [comment]
Thank you for forwarding the issue to the engineering team. I have opened a Unified Support ticket as well.
________________________________

**Comment by markjjo** [comment]
@buildbod Can you please either post or send me the number/link for unified support ticket that you opened so that I can route to appropriate folks? Thanks.

**Comment by buildbod** [comment]
The support ticket is  #‎22104325
________________________________

**Comment by markjjo** [comment]
Thanks for ticket number. I'll pass it on to engineering.
