### ISSUE TITLE
Guests are not able to see sharepoint lists from Teams desktop client

### ISSUE THREAD

**Issue by koen-vissers** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5823]
> Guests in private channels can't create or delete a list or start a new conversation about a list item. They can add list items to existing lists and reply to an existing conversations about a list item. Keep in mind that these limitations apply only to private channels.

When logging into the webapp of Microsoft Teams guests are able to interact with the Sharepoint list setup on a tab within a team. When doing this from the desktop client the tab remains empty. It does not matter whether the tab is added to a list in a private or non-private channel.

Looking at the trace in Fiddler: I see a 403 on https://mycompany.sharepoint.com/_api/SP.OAuth.NativeClient/Authenticate:
Exception of type 'Microsoft.SharePoint.Client.ClientServiceException' was thrown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac12129f-4d94-cbbd-4c34-03666617c889
* Version Independent ID: 015463d6-8fb9-7240-a3f1-8ae288dd9e90
* Content: [Manage the Lists app for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-lists-app)
* Content Source: [Teams/manage-lists-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-lists-app.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@koen-vissers Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
