### ISSUE TITLE
Grammatical error 

### ISSUE THREAD

**Issue by ashmsport** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5826]
There's a grammatical error in the second line of this article: "you can be able to extract them". Should be either "you can extract them" or "you are able to extract them".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eb2244d-b82d-0559-0255-ac0cb7ce05e3
* Version Independent ID: e3a7a842-7efe-40db-e3c7-da56d7b24c02
* Content: [Export content with the Microsoft Teams Export APIs - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/export-teams-content)
* Content Source: [Teams/export-teams-content.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/export-teams-content.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@ashmsport  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
