### ISSUE TITLE
Team - Manage Team - Channels - List of chanels - add screen and explanation to page

### ISSUE THREAD

**Issue by MarcGab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5829]
To better understand channels and how a private channel looks like it would be helpfull to add a screenshot and explain the possible values of each colmun - especially the column Type.

<img width="976" alt="Team_Manage_Channels_Overview" src="https://user-images.githubusercontent.com/43538425/94010964-eebd4000-fda6-11ea-8527-95c04727c3a4.png">
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@MarcGab Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by MarcGab** [comment]
May be i misunderstood your reply. I am aware that i have to talk to my Admin to enable private channels. This issue here is meant to update the documentation so that it is clear that Teams does support private Channels and how to create them. 

Currently you have these headlines (among others)

 1. What you need to know about private channels
 1. When to create a private channel

Please add a headline "How to create a private channel"
