### ISSUE TITLE
Supported Database Technologies

### ISSUE THREAD

**Issue by JeffBrownTech** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#583]
The above lists Database Mirroring as being supported for back-end high availability, but the "What's deprecated" mentions that mirroring is no longer supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3631c9ea-ab9d-bf7f-8c1b-66f050d31949
* Version Independent ID: 5b6a6a2a-0275-73e9-089c-fa8a5c4daace
* Content: [Topology Basics for Skype for Business Server](https://docs.microsoft.com/en-us/SkypeForBusiness/plan-your-deployment/topology-basics/topology-basics?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json)
* Content Source: [Skype/SfbServer/plan-your-deployment/topology-basics/topology-basics.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/topology-basics/topology-basics.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by jambirk** [comment]
Hi Jeff, 
Thanks for bringing this to our attention. I'm updating the page now to make this clearer. Please let me know if this resolves the issue.
