### ISSUE TITLE
Is this now GA?

### ISSUE THREAD

**Issue by DevJonBirkett** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5831]
[Enter feedback here]
Hi, 

MS ignite 2020 have said this feature is now GA. Does this article need to be updated?
https://techcommunity.microsoft.com/t5/microsoft-teams-blog/what-s-new-in-microsoft-teams-microsoft-ignite-2020/ba-p/1665600

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef94e9a3-a0a5-11da-f27b-627ac4fa6186
* Version Independent ID: e49db873-ed77-de53-e4dd-be4fc571d734
* Content: [Use Teams templates to create a new team - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/get-started-with-teams-templates-in-the-admin-console)
* Content Source: [Teams/get-started-with-teams-templates-in-the-admin-console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-started-with-teams-templates-in-the-admin-console.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@DevJonBirkett Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by cichur** [comment]
The template feature is pushed live today.

**Comment by DevJonBirkett** [comment]
Thanks Cichur 
Templates have literally just appear in my tenant \o/

**Comment by cichur** [comment]
@DevJonBirkett I'm glad that you have the templates. Please tell us how they work out for you.
