### ISSUE TITLE
Adding Native ARM64 for Windows 10 on ARM to this Page

### ISSUE THREAD

**Issue by BillWeidenborner** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5832]
We will need to add the new native ARM64 MSI for Commercial through DoD. I can provide links to the appropriate CDN when it's ready for GA. If the doc owner of this page could reach out in the next week or so to align on the approach (if what I'm proposing makes sense), then that would be great as this should go live by mid-October.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Teams using Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment?source=docs#feedback)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officedocspr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @BillWeidenborner, thank you for your feedback. Sorry for the delay.

@scanum I think this issue can be closed, the ARM64 links were added 27 days ago.

**Comment by scanum** [comment]
@BillWeidenborner Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
