### ISSUE TITLE
Typo of "won't be"

### ISSUE THREAD

**Issue by jjsguo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5833]
Hello, I believe the "**won't be**" is a typo. It should be "**will be**". Can you please confirm?

Thanks,
Jason

If anonymous access, or not requiring a PIN to start a meeting, is enabled:

If the meeting hasn't started (there's no one in the meeting yet): A caller **won't be** prompted if she's the organizer, and she'll never be prompted for the PIN. Because the setting of the organizer is set to off, the meeting will start and the anonymous callers will join the meeting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b4d417-8a1f-daca-381a-b1beed2dbdac
* Version Independent ID: d3e59d94-b0b7-fdfc-3a04-00dc4188e63d
* Content: [Start Audio Conference over the phone without a PIN in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/start-an-audio-conference-over-the-phone-without-a-pin-in-teams)
* Content Source: [Teams/start-an-audio-conference-over-the-phone-without-a-pin-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/start-an-audio-conference-over-the-phone-without-a-pin-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@jjsguo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@jjsguo thank you for reaching out and helping improve MS Docs. It looks like the article is reading correctly as 'not requiring a pin' is enabled.
