### ISSUE TITLE
Define difference between dedicated and shared conferencing numbers

### ISSUE THREAD

**Issue by kyleharwood** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5834]
Define difference between dedicated and shared conferencing numbers. Detailed explanation of why you would have one vs the other. What is actual difference? What does mean to be able to be shared within organization or outside organization? What does it mean to share a number outside of organization? 

Thanks 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c6e2b61-656c-a4f8-94a7-ec3c14e4d65e
* Version Independent ID: 77932de0-0312-95c5-f356-89ece9b3aabd
* Content: [Phone numbers for Audio Conferencing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/phone-numbers-for-audio-conferencing-in-teams)
* Content Source: [Teams/phone-numbers-for-audio-conferencing-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phone-numbers-for-audio-conferencing-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@kyleharwood Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @kyleharwood, thank you for your feedback and help us to improve docs.microsoft.com.

The following information is currently in the article and I think it's all that we can have about Dedicated and Shared phone numbers:
- **Dedicated phone numbers** are those phone numbers that are only available to users within your organization. You can change the languages that are used when someone calls in to one of these numbers.
  
- **Shared phone numbers** are those phone numbers that can be shared with other Microsoft 365 or Office 365. You can't change the languages that are used when someone calls in to one of these numbers.

**Comment by scanum** [comment]
@kyleharwood Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
