### ISSUE TITLE
Translation rule to convert blank number to a specific number

### ISSUE THREAD

**Issue by shashank1320** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5835]
[For Teams Direct Routing, if a user has a dial pad (no DID/Line URI assigned), how shall I convert a blank outgoing number to a board number or an auto-attendant or a fixed number via translation rule or any other method from Teams end (do not want to modify anything on SBC level). Please help.
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6981866f-a685-d802-d64f-98685a5c658d
* Version Independent ID: a1f83744-abb7-4c33-6f60-19ff2732871c
* Content: [Translate phone numbers for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-translate-numbers)
* Content Source: [Teams/direct-routing-translate-numbers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-translate-numbers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@shashank1320 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
