### ISSUE TITLE
Headset call control in MS Teams no longer possible

### ISSUE THREAD

**Issue by csjn** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5839]
I am using a Jabra Headset with MS Teams for years. All over sudden I could no longer control teams with it (mute, accept or end calls). Jabra told me, that MS Teams changed the call control and Jabra and non of its competitors can do anything about it.

I considere the feature "call control with 3rd party devices" at non-existent for the time beeing and request to alter the documentation accordingly.

Quote Jabra Support:
> Jabra R&D recently discovered the loss of headset call control when using MS Teams. After the investigation, all indications are that this is a behavior of MS Teams and unfortunately there is not much we can do on our part. The problem affects not only Jabra users, but also our competitors. We advise you to regularly check for latest MS Teams-Updates, as a solution could appear at any time.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b118e0a7-1fef-feae-6c6d-e24c4485a5b9
* Version Independent ID: ae18e2db-fbbf-f30c-3c56-17dd0d2b85d1
* Content: [Telefone und Geräte für Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/devices/usb-devices)
* Content Source: [Teams/devices/usb-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/usb-devices.md)
* Service: **msteams**
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@csjn Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
