### ISSUE TITLE
Missing decision in when to create a private channel

### ISSUE THREAD

**Issue by yosmanovich** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5840]
The When to create a private channel is missing the decision as to what to do When a team exists with these people as team members, the work doesn't need to be private, and there are multiple distinct topics to discuss. This has led to us debating if we need a new Team w/ channels or to create private channels.
(Yes No Yes) -> ?

![image](https://user-images.githubusercontent.com/14120239/94153879-4f05bd80-fe4b-11ea-81e5-5965b729690d.png)

**Comment by scanum** [comment]
@yosmanovich Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
