### ISSUE TITLE
Away since indicator 

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5841]
The page currently states:
> The Last seen or Away since indicator is always enabled for users in Teams if the organization also uses Skype for Business.

What does "uses Skype for Business mean"? Does this correspond to the setting of  Coexistence mode (Islands, Teams Only?)
What happens if the organization does not use Skype for Business? Is the Away since indicator enabled or not? Can I be disabled in this case?
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a162ef5c-3099-7f58-4178-d29e3ec2b5a7
* Version Independent ID: 6ca31e56-052d-6c62-1323-b5aaaae1f04a
* Content: [User presence in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/presence-admins#admin-settings-in-teams-compared-to-skype-for-business)
* Content Source: [Teams/presence-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/presence-admins.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@joergrenn Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by joergrenn** [comment]
@scanum what exactly should I get resolved via service ticket?
I have raised this issue because I am missing documentation about the last seen indicator in case the organisation does not use Skype for Business. And have asked in addition to explain in more detail what it means to "use skype for business".
This is an issue with the documentation, not with my tenant.
Also in my opinion the documentation is part of the product, so the developers and the writers of the documentation should be the same people or at least talk to each other. I as a customer do not have a communication channel to the engineering team.
