### ISSUE TITLE
Phone System with or without calling plan

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5843]
The page says,
> The license type determines whether you can set up Business Voice on your own, if you need help from a Microsoft partner or reseller, who manages your phone numbers, and so on.

And,
> Business Voice without Calling Plan You need to buy Business Voice from a Microsoft partner or reseller who will help you set up Business Voice. **Your existing phone numbers remain with your current third-party telephone provider.**

However, M365 E5 comes with Phone system without a calling plan. And in that situation, you add the domestic or domestic and enterprise calling plan as an add-on.

Isn't that the same as buying without calling plan, then adding a calling plan add-on? As written, the article gives the impression the "without calling plan" product can only be used with Direct Routing.

This is interesting because if a client has O365 E3 and wants to add phone system with international calling what should they do:
* Buy Business Voice( with calling plan), and add the Domestic and International add-on. Or, 
* Buy Business Voice (without calling plan), and add the Domestic and International add-on?

If they get the product with a calling plan, then purchase the add-on aren't they paying for two domestic plans and only using one of them? From our research that appears to be the case, and not the best approach.

Thanks!
-jon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7546fc-fc37-14ac-94bb-ffbe4c6e16d6
* Version Independent ID: 61a44a8e-f55a-5bf5-a22b-2995f7efe79d
* Content: [What do I need to buy to use Microsoft 365 Business Voice with Calling Plan? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/business-voice/what-to-buy)
* Content Source: [Teams/business-voice/what-to-buy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/business-voice/what-to-buy.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@jonwbstr Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jonwbstr** [comment]
Well, that's a bit of an interesting issue. Support says it's working as intended. But, at the moment we can add "Business voice without calling plan, and then add "domestic" add-on. 
However, we cannot add "Business Voice without calling plan, and add "international calling plan"

At the very least, my feedback is true for Domestic according to support at the moment.
