### ISSUE TITLE
Requirements to create and view meetings for mailboxes hosted on-premises

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5845]
This Section "Requirements to create and view meetings for mailboxes hosted on-premises", doesn't mention assigning EXO license as one of the requirements, while https://docs.microsoft.com/en-us/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users?view=o365-worldwide mentions that "The user whose primary mailbox is located in the on-premises organization must be assigned a Microsoft Teams license and a minimum of an Exchange Online Plan 1 license." 
So does an user with On-prem Exchange mailbox would need EXO license for Teams integration, If Yes, Please update the documentation accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/exchange-teams-interact#requirements-for-mailboxes-hosted-on-premises)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@3novsan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
