### ISSUE TITLE
Do policy controls work for Teams as well?

### ISSUE THREAD

**Issue by andrasg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5846]
This article mentions policy controls for Microsoft Teams apps. The linked articles though (policy controls in Office apps) do not mention Teams (desktop or mobile) as a clients those controls would apply to.

Either the Teams documentation or the Office policy controls documentation is not correct. Clarification would be required on how to set Teams policy controls for diagnostic data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4898302-208e-0d21-a17f-53e2a9506e21
* Version Independent ID: 17d47df2-074b-071a-5179-9ebcc21b709e
* Content: [Policy control overview for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/policy-control-overview)
* Content Source: [Teams/policy-control-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/policy-control-overview.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@andrasg Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
