### ISSUE TITLE
No link to learn about 'team templates in the admin console'

### ISSUE THREAD

**Issue by lfinman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5850]
In section **What are base template types**, the link 'Learn how to use the _team templates in the admin console_ links back to this document, does not take you to information about team templates in the admin console.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d884cb-c126-b5dc-ff90-1a31aa61bf5b
* Version Independent ID: ed5054d7-d679-7fad-fd5d-9cd393644b9d
* Content: [Get started with Teams templates using Microsoft Graph - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-started-with-teams-templates)
* Content Source: [Teams/get-started-with-teams-templates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-started-with-teams-templates.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@lfinman Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@lfinman thank you for reaching out and helping improve MS Docs. The two documents are similar but if you scroll down there is extra information in the linked document. Please confirm from your side.

**Comment by lfinman** [comment]
Sorry, I think my subject line was misleading.  I believe it is a circular link (the doc is linking back to itself).  When I am viewing this page:
https://docs.microsoft.com/en-us/microsoftteams/get-started-with-teams-templates

The link indicated below takes me to this same doc: (https://docs.microsoft.com/en-us/microsoftteams/get-started-with-teams-templates)

[cid:image001.png@01D69640.948732D0]

**Comment by Reeced40** [comment]
@lfinman thank you for clarifying. I found these articles. Please let me know if I should add the links to this document to help other users - https://techcommunity.microsoft.com/t5/microsoft-teams-blog/create-teams-quickly-with-templates-in-microsoft-teams/ba-p/1394163 and https://docs.microsoft.com/microsoftteams/get-started-with-retail-teams-templates
