### ISSUE TITLE
Question to add: what is the lag time for data to begin showing up in CQD reports? And is it the same for all data or does it vary depending on which data?

### ISSUE THREAD

**Issue by Jason6311** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5851]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de72ba4-417f-b90d-6cf4-1af9fbbce5f1
* Version Independent ID: 94abea2e-541a-3d3c-c9da-f8544bbc98d1
* Content: [Call Quality Dashboard (CQD) Frequently asked questions (FAQ) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cqd-frequently-asked-questions)
* Content Source: [Teams/CQD-frequently-asked-questions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-frequently-asked-questions.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@Jason6311 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Jason6311** [comment]
·       Admin Center: 24-48 hours
·       Note that this data is also the source for the PBI M365 Usage Analytics I mentioned (formerly the O365 Adoption Pack—which is what I called it on the call): https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/usage-analytics?view=o365-worldwide
·       CQD: 30 mins (after end of call): https://docs.microsoft.com/en-us/microsoftteams/cqd-data-and-reports
·       Call Analytics: 15-30 mins (after the end of the call/meeting/desktop share). Note that data only resides here for 30 days: https://docs.microsoft.com/en-us/MicrosoftTeams/use-call-analytics-to-troubleshoot-poor-call-quality


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
