### ISSUE TITLE
Change "his or her" to "their"

### ISSUE THREAD

**Issue by UltraKeelan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5852]
Please update this document to use the gender neutral and inclusive "their" instead of "his or her". Note that "they" and "their" are both proper for use as a singular pronoun: https://en.wikipedia.org/wiki/Singular_they

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401f39f3-f614-6d63-adbd-1ed78ed804f0
* Version Independent ID: 26b45c86-8f6f-8704-d95a-f8c341e569ad
* Content: [Reset the Audio Conferencing PIN in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/reset-the-audio-conferencing-pin-in-teams)
* Content Source: [Teams/reset-the-audio-conferencing-pin-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/reset-the-audio-conferencing-pin-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@UltraKeelan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@tonysmit please could you check to merge.
