### ISSUE TITLE
Feature not available in government clouds

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5855]
Please include a callout about this feature not being available in government clouds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bf3bc26-4cac-56c0-8669-6540adf3c502
* Version Independent ID: bd7cd483-e40e-88c2-b9ee-b21a9ea73005
* Content: [Manage feedback policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-feedback-policies-in-teams)
* Content Source: [Teams/manage-feedback-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-feedback-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@npherson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @npherson, thank you for your feedback.

A note at the top of the article indicates that this feature is a preview or early release feature, so it's not in GA yet. I think it is not available to everyone.

**Comment by npherson** [comment]
The "preview" callout at the top is meant to indicate that the feature may change significantly in the future, not that it isn't available to customers yet. This functionality does not exist in GCC tenants today and there is no public roadmap date for when it will. The article needs to indicate that it isn't available in those tenants so we stop getting questions from our customers about why it doesn't show up there. Thanks!

**Comment by dariomws** [comment]
Hi @npherson, are you a Microsoft employee?

If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=npherson

I'll double-check internally if we can add a note here. Thanks!

**Comment by npherson** [comment]
Hi @dariomws. Yes, I'm a Microsoft employee and believe I have linked my github account a long while back. When I view this page, it shows the Microsoft Submitter badge for me: 
![image](https://user-images.githubusercontent.com/22797301/95766897-924c9280-0c79-11eb-90ad-8287d4464377.png)

**Comment by dariomws** [comment]
@npherson forget it, I missed the label but it was always there.

As you are a Microsoft employee, I understand that you have access to a GCC tenant and you can confirm this information. So I'll create a PR to add a note about it, then it also needs approval.

Thanks!

**Comment by npherson** [comment]
Thanks much!!!

**Comment by dariomws** [comment]
@npherson sorry about the label.

I'm assigned to other issues that you opened related to GCC features. If you have more concerns about them let's have an internal conversation in Teams. Thanks!

**Comment by npherson** [comment]
No worries! I don't see you in the GAL - can you send me a Teams message?

**Comment by LanaChin** [comment]
@npherson - article has been updated. Thanks for your input.
