### ISSUE TITLE
This feature not available in GCC

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5856]
Can this article be updated to include a callout that the features are not available in the US Govt clouds today?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 238a2222-3d53-dfa2-6d06-e69bc16daaa0
* Version Independent ID: 65bc6c34-447b-72dc-2155-eaa44a4aba00
* Content: [Purchase services for Teams third-party apps in the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/purchase-third-party-apps)
* Content Source: [Teams/purchase-third-party-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/purchase-third-party-apps.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by npherson** [comment]
Can this please be reopened? This is not a support issue. O365 GCC does not support this feature today. Please contact the engineering team for confirmation and update the page to call out that this functionality does not apply to Office 365 for US Govt  today.
