### ISSUE TITLE
Connectors are disabled by default in GCC

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5858]
Can this article be updated to include steps for enabling connectors for M365 for US Government customers? It is disabled by default, and custom connectors won't work without it being first enabled. I don't see anywhere that has the steps documented publicly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5eb6a35-32fa-6703-8ed2-0855e602b7d5
* Version Independent ID: 7890ca09-d505-35a9-071a-8662a4b19275
* Content: [Use Microsoft 365 and custom connectors - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/office-365-custom-connectors)
* Content Source: [Teams/Office-365-custom-connectors.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-custom-connectors.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@npherson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @npherson, thank you for your feedback.

I think it's more related to apps if you don't enable apps you won't have the ability to add connectors to Channels. More information:
https://techcommunity.microsoft.com/t5/public-sector-blog/microsoft-teams-third-party-apps-now-available-in-government/ba-p/1132197
https://docs.microsoft.com/microsoftteams/teams-app-permission-policies#manage-org-wide-app-settings-for-microsoft-365-government

There are also more settings that could impact the availability of connectors:
https://docs.microsoft.com/powershell/module/exchange/set-unifiedgroup (ConnectorsEnabled parameter)
https://support.microsoft.com/en-us/office/manage-team-settings-and-permissions-in-teams-ce053b04-1b8e-4796-baa8-90dc427b3acc (allow members to create update and remove connectors under member permissions)

**Comment by npherson** [comment]
This is about the default state of the tenant. If you were to follow all the steps from that blog post and the app permission policies docs page, you still would not be able to use connectors in GCC since they are disabled by default (where they are enabled by default in commercial and those steps would work). Yes, you could also end up turning them off per group or team... but turning them on per group or team still wouldn't work because they are disabled in GCC tenants by default.

This is a known issue from the Teams GCC engineering folks ("You can enable them using the ExchangePowerShell module with: Set-OrganizationConfig -ConnectorsEnabled $true"), but it isn't publicly documented (thus the feedback).

**Comment by npherson** [comment]
Had another GCC customer run into 'issues' getting connectors to work and open a support case where the resolution was "You need to enable connectors with Set-OrganizationConfig -ConnectorsEnabled $true first."  Any progress getting this called out in the documentation?

**Comment by dariomws** [comment]
Hi @npherson, I'm still waiting for the approval to add this information.

**Comment by dariomws** [comment]
@npherson, sorry for the delay. I'm proposing a note:
![image](https://user-images.githubusercontent.com/33589238/113840658-329af400-9791-11eb-91de-fc1ee256aa48.png)

Could you kindly let me know your thoughts?

@cichur, maybe you can also kindly help here to confirm this information. 

Thank you everyone!

**Comment by cichur** [comment]
Hello @npherson 
The team updated the article. Does this give you the correct information?
https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating#disable-or-enable-connectors-in-teams

**Comment by npherson** [comment]
Could "Connectors are disabled by default for GCC tenants." just be a separate paragraph at the end of that section (after the "The tenant-level setting..." paragraph)?

Also, I liked @dariomws's note on the other article. Are we able to get that published to the live documentation?
