### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by rajkumardas2701** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5860]
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/downloads/LOA-forms/Letter-of-authorization-(loa)-for-the-u.s.-(toll-free-numbers)-(v.3.3)-(en-us).pdf?raw=true

The Link to **Letter of Authorization (LOA) for the U.S. (toll free numbers) (v.3.3)(en-us)** is not working under **Get phone numbers transferred to us.**

![image](https://user-images.githubusercontent.com/41339878/94478603-20903580-01f1-11eb-933d-77735a0fdd18.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1778d5e3-1cd3-9323-d7f0-6ee14aa69f24
* Version Independent ID: 66402fb0-4a46-65af-91ac-caa9a3d60a1f
* Content: [Phone number management for the U.S. - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/manage-phone-numbers-for-your-organization/phone-number-management-for-the-u-s)
* Content Source: [Teams/manage-phone-numbers-for-your-organization/phone-number-management-for-the-u-s.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-phone-numbers-for-your-organization/phone-number-management-for-the-u-s.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by rajkumardas2701** [comment]
This is the original link, https://docs.microsoft.com/en-us/MicrosoftTeams/manage-phone-numbers-for-your-organization/phone-number-management-for-the-u-s

**Comment by scanum** [comment]
@rajkumardas2701 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @rajkumardas2701, thank you for your feedback.

It's working for me, could you kindly try again? Thanks!

**Comment by rajkumardas2701** [comment]
Thanks @dariomws . seems to be working fine now.
