### ISSUE TITLE
Please be more clear on what version of windows and exactly how to download it

### ISSUE THREAD

**Issue by mschardt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5861]
Nothing seems to match up. let me explain...
The page indicates Teams Rooms version 4.5.33.0 requires 18363.418
however, I am running the powershell script in the below guide to create a USB deployment, which indicates it's using version 4.5.37.0 (scripted so I cannot control this). yet it also claims to want 18363.418
https://docs.microsoft.com/en-us/microsoftteams/rooms/console

What's worse though, the script advises you to retrieve media from volume license portal (inconvenient, but OK). There are hundreds of versions of windows 10 there and none of them are listed by the versioning scheme you use here. 

The whole process here is so needlessly disjointed, poorly documented and complex, I honestly think microsoft  is playing a prank. 

Simple ask: can you just tell me exactly what version of windows to download from the volume portal (not in numbers, but exactly the way its listed on the volume site), so I can finish this evaluations.

**Comment by scanum** [comment]
@mschardt Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dstrome** [comment]
Closing old issues.
