### ISSUE TITLE
Microsoft GCC High cloud - has DDTC at State Dept said it's good for ITAR-controlled tech data?

### ISSUE THREAD

**Issue by sbailey14** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5864]
Microsoft re: GCC High cloud;

We want to find, if it exists, any positive statement from DDTC in Dept of State that clearly says they regard Microsoft GCC High cloud as acceptable for storage of technical data that's subject to ITAR export control. It seems reasonable that MS would've gotten some definite validation from DDTC before offering the service for sale. May we please have a copy of that?
ref:  https://docs.microsoft.com/en-us/microsoftteams/plan-for-government-gcc-high.    
If I'm asking the wrong part of MS, then would you please direct me to the person who can help us? Thank you. 
Scott Bailey, Goleta, CA (for Kristine A. Fritz, Corporate Director of Security, Toyon Research Corporation, 6800 Cortona Dr., Goleta, CA 93117-3021)
please reply to: sbailey.consultant@toyon.com, cell 805-968-7006 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eab6a21-5773-fdba-1cad-c282e66556d7
* Version Independent ID: 9b19ed7d-85f1-9f5e-b320-1749b414cd1b
* Content: [Microsoft 365 Government - GCC High deployments - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/plan-for-government-gcc-high#feedback)
* Content Source: [Teams/plan-for-government-gcc-high.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-for-government-gcc-high.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by sbailey14** [comment]
Manuela,

Thank you for referring me to the right place in Microsoft to ask the question.  I appreciate your help.
Scott Bailey, Goleta, Calif
