### ISSUE TITLE
Meaning "This setting is disabled by default." for Busy on busy puzzles me regarding meaning.

### ISSUE THREAD

**Issue by monty241** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5865]
Regarding "This setting is disabled by default." on Busy on busy: for me as a reader it is unclear what disabled means.

When busy on busy slider is ON on the calling policy, will the caller receive a busy signal? So that disabled means that the person being called receives an additional incoming call? Or the reverse applies?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 410fc30b-f530-8443-0602-9150c9cba115
* Version Independent ID: c5b33b25-147b-f7d4-056a-987088950e7c
* Content: [Calling policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/nl-nl/microsoftteams/teams-calling-policy)
* Content Source: [Teams/teams-calling-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-calling-policy.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
