### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by SNFHI360** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#587]
Can you update this document to reflect the OMS portal through Azure?  The counters are not available in the Azure OMS portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0549300-a7dd-8325-65a0-fbd27f92d2e8
* Version Independent ID: ddaf2e7b-5f5c-82d0-9d46-df8ad699cb93
* Content: [Monitor Cloud Connector using Operations Management Suite (OMS)](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/monitor-cloud-connector-using-operations-management-suite-oms)
* Content Source: [Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/monitor-cloud-connector-using-operations-management-suite-oms.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/monitor-cloud-connector-using-operations-management-suite-oms.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Thank you for your feedback.  Your request has been forwarded to the product team.
