### ISSUE TITLE
Call Queue and Auto Attendant Dimensions not documented

### ISSUE THREAD

**Issue by tiagoroxo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5870]
Call Queue and Auto Attendant Dimensions not documented in the article and they are available in CQD portal (https://cqd.teams.microsoft.com/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a455280-ea8e-2ddf-2965-60d9dcc0e21d
* Version Independent ID: 7fb320d3-fa69-23fa-113c-53e9d2e11ada
* Content: [Dimensions and measurements - Call Quality Dashboard (CQD) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/dimensions-and-measures-available-in-call-quality-dashboard)
* Content Source: [Teams/dimensions-and-measures-available-in-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/dimensions-and-measures-available-in-call-quality-dashboard.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@tiagoroxo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @tiagoroxo I am looking into this. Thanks

**Comment by get-itips** [comment]
I could get information that the article will be updated with the missing dimensions.
thank you!

**Comment by ParkesJ** [comment]
Hi there @get-itips, we're just processing a major update to the dimensions listing for this document, they should be available shortly. There are a few CQ/AA dimensions outstanding that require input from the owning team, but they'll be updated once I have the information needed to complete it.

**Comment by get-itips** [comment]
Thanks @ParkesJ James!

**Comment by get-itips** [comment]
@scanum please close
