### ISSUE TITLE
Distinction betweeen Service Account and regular account

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5876]
Hello,
on the page a bunch of account types are listed which are not added to an org-wide team:

> These types of accounts won't be added to your org-wide team:
    Accounts that are blocked from sign in
    Guest users
    Service accounts
    Room or equipment accounts
    Accounts backed by a shared mailbox

Can you describe or refer to a definition what exactly differentiates a "Service Account" from a regular account?
For Guest users, room and equipment accounts its clear.
But as far as I am aware there is no such account type as a service account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@joergrenn Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @joergrenn I am looking into this, thanks.

**Comment by LanaChin** [comment]
Hi @joergrenn - thanks for your input. We've updated the topic for clarity. Service accounts refers to resource accounts, for example, accounts that are associated with an auto attendant or call queue).
