### ISSUE TITLE
Short is broken

### ISSUE THREAD

**Issue by scapero** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5879]
Enabling Teamwork with Microsoft Teams shortcut https://aka.ms/edx-cld267x-about recv's 404 at edX site

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 752a6dc8-4018-88aa-faa4-c07c1c0a1719
* Version Independent ID: 7d6d29c5-f699-2abd-71c2-7c49061dd068
* Content: [Admin training resources - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/itadmin-readiness)
* Content Source: [Teams/ITAdmin-readiness.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/ITAdmin-readiness.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officedocspr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @scapero

**Comment by LanaChin** [comment]
Thanks @scapero. The link has been updated to point to https://docs.microsoft.com/learn/paths/m365-manage-team-collaboration.
