### ISSUE TITLE
Channel Membership

### ISSUE THREAD

**Issue by kakaroto1234** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#588]
channel membership
If a person fav a channel so by default it will show the count how many has fav it.
so even though there are 100 members in a team, a channel when you @mention will show only few who has fav it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06059d07-6687-2924-7d0a-3c03220a1650
* Version Independent ID: bb293f92-9394-b156-2e08-0baead5c3bbe
* Content: [Overview of teams and channels in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-channels-overview)
* Content Source: [Teams/teams-channels-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-channels-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by kenwith** [comment]
@kakaroto1234 - I am not 100% following this one. I am not sure if you are experiencing an issue in the product or if there might be something in the documentation.

If this seems to be an issue in the product I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
