### ISSUE TITLE
No description of how or if possible to get a copy of a meeting recording from your local drive

### ISSUE THREAD

**Issue by greggwon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5881]
Loosing Teams meeting recordings should not be possible.  If a recording can't be uploaded to whatever the designated location is, the user requesting the recording to start should have a copy of the recording on their own computer and the user interface should provide a way to retry the upload or seek admin help in getting the recording into a file which can be shared through some other means.  When a recording is requested, that means that there is something very important about allowing non-attendees to participate in the exchange, or that there are words being said that need to be preserved in some other sense.  Having software fail and there be no control of that event at the moment it's going to happen is very poor system design!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@greggwon  I know the product teams are always looking for user feedback and how to make SharePoint better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice 
Skype for Business: https://www.skypefeedback.com.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.
Thank you for your contribution to make the docs better! Much appreciated!
