### ISSUE TITLE
Set up PIN links incorrect?

### ISSUE THREAD

**Issue by tosweet** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5892]
[Enter feedback here]
There is a link (in 2 places I see) to set up a support PIN but it takes to a page that does not have any info on setting up a PIN.
Link currently there: https://docs.microsoft.com/en-us/skypeforbusiness/what-are-calling-plans-in-office-365/set-your-pin-for-transferring-numbers-to-a-new-service-provider 
Redirects to https://docs.microsoft.com/en-us/MicrosoftTeams/manage-phone-numbers-for-your-organization/manage-phone-numbers-for-your-organization which has no info on PINs

Did find this info on PINs regarding support and Teams, not sure if this is what they are referring to:
https://docs.microsoft.com/en-us/MicrosoftTeams/support-pin 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1778d5e3-1cd3-9323-d7f0-6ee14aa69f24
* Version Independent ID: 66402fb0-4a46-65af-91ac-caa9a3d60a1f
* Content: [Phone number management for the United States - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization/phone-number-management-for-the-u-s?source=docs)
* Content Source: [Teams/manage-phone-numbers-for-your-organization/phone-number-management-for-the-u-s.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-phone-numbers-for-your-organization/phone-number-management-for-the-u-s.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@tosweet Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
