### ISSUE TITLE
GPU usage

### ISSUE THREAD

**Issue by oleomachado** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5895]
Can you explain why Teams uses GPU? I noticed a great impact on the performance of some WebGL projects. I know I can disable it, but I believe that it is still using GPU during a session with someone. As soon as I close Teams, WebGL will run smoothly again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc21902c-d522-3851-8587-177f01bc085c
* Version Independent ID: 590bcc64-a86d-b61e-7d94-4e4322c4e71d
* Content: [How Microsoft Teams uses memory - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-memory-usage-perf)
* Content Source: [Teams/teams-memory-usage-perf.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-memory-usage-perf.md)
* Service: **msteams**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by lindspea** [comment]
@oleomachado thank you for reaching out. I have done some research and found that when you disable GPU you have to restart Teams for it to take effect. Please let me know if you have already tried this.

**Comment by scanum** [comment]
@oleomachado Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
