### ISSUE TITLE
The Note for GCC provides conflicting information

### ISSUE THREAD

**Issue by pagejustin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5897]
Has the GCC limit been increased from 250 to 300? The second sentence indicates to refer to the "Limits and Specifications" at https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams

Note in page reads: "Note: For Teams for Government (GCC, GCC High, DoD), the limit is still 250. We'll update this article when the government cloud limit increases from 250 to 300. See [Limits and Specifications](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams) for the latest information about Teams meeting limits."

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @pagejustin, thank you for your feedback and help us to improve docs.microsoft.com.

I think you are talking about the following article:
https://docs.microsoft.com/microsoftteams/quick-start-meetings-live-events

I removed this note 29 days ago:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/649c41e488dae17b63907d1db75e04476aad0b01#diff-51e104b175a160e3b7b6d511b226681add56c277426a5d0437e8c75156a94790

**Comment by scanum** [comment]
@pagejustin Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
