### ISSUE TITLE
Real time support in browsers

### ISSUE THREAD

**Issue by doulouz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#59]
"At this point, the web client does not support real-time communications" is outdated.

As of 2nd Feb, A/V is supported on Edge, and Audio is supported on Chrome.

**Comment by LolaJacobsen** [comment]
Thanks for your comment. We've updated our browser support documentation. Check it out:

https://docs.microsoft.com/microsoftteams/get-clients
