### ISSUE TITLE
Query on "Make Sure your users have a valid licence"

### ISSUE THREAD

**Issue by martinboam** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#590]
With the below statement when migrating user to Teams

_If the user is configured to use on-premises Enterprise Voice, they must have an online voice license when moving._
There's different options for Voice in Office 365 with Calling Plans, Direct Routing for Teams which is mentioned further down but here we are saying online voice licence is that meaning "Phone System" ?

also

_If the user is configured for on-premises dial-in conferencing, they must have a license for Phone System (Cloud PBX)._
For dial in conferencing wouldn't the user required Audio Conferencing licence instead of Phone System ?

> Make sure your users have a valid license
> Before migration, the on-premises user must be given a valid license, as follows:
> 
> User must have a Teams license.
> If the user is configured to use on-premises Enterprise Voice, they must have an online voice license when moving.
> If the user is configured for on-premises dial-in conferencing, they must have a license for Phone System (Cloud PBX).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a60f70-fa4d-d45c-b3b6-fad3e0ee446e
* Version Independent ID: 7c32e933-94f2-196e-1163-3881df3aaf5a
* Content: [Move users from on-premises to Teams](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/move-users-from-on-premises-to-teams)
* Content Source: [Skype/SfBServer2019/hybrid/move-users-from-on-premises-to-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/hybrid/move-users-from-on-premises-to-teams.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Thank you for your feedback.  I have forwarded your questions to the product team.  We will update the when we receive an answer.
