### ISSUE TITLE
Conflicting info on call queue agent licensing requirements

### ISSUE THREAD

**Issue by dwhitney7** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5902]
Hello team!

Seems our docs pages have conflicting info regarding the licensing requirements for call queue agents. This page says in the Prerequisites:

**A calling plan for each person who will be receiving call queue calls**

However, both in testing and as documented on the call queue-specific docs page, only Phone System licensing is required. From https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue#call-agents:

Call agents selected must be one of the following:

* **Online users with a Phone System license and Enterprise Voice enabled**
* Online users with a Calling Plan
* On-premises Skype for Business Server users
* If your agents are using the Microsoft Teams app for call queue calls, they need to be in TeamsOnly mode.

Can we please verify that and update this page to be accurate with the call queue-specific docs page? Or if there is a scenario where calling plans are required, to call that out in addition to the minimum Phone System requirements?

Thanks!
David 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62fca5a0-5e22-578c-98c8-6b331ae1017f
* Version Independent ID: e1307146-d481-d39c-6227-4c001e044eb1
* Content: [Plan for Teams auto attendants and call queues - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/plan-auto-attendant-call-queue)
* Content Source: [Teams/plan-auto-attendant-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-auto-attendant-call-queue.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
Yes, I don't think a calling plan is required. @CLYVR can you confirm?

**Comment by CLYVR** [comment]
@dwhitney7 @MikePlumleyMSFT @Kateyanne  Sorry for the delay.  A Microsoft Calling Plan is not required for an agent to receive a call from the call queue.   A Calling Plan, or Direct Routing, is required in order to make external calls or transfer externally.   I'll be submitting some documentation updates shortly to consolidate the licence requirements that are spread across a few pages into the planning page.

**Comment by scanum** [comment]
@dwhitney7  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
