### ISSUE TITLE
Meeting policy settings - Designated presenter role mode 

### ISSUE THREAD

**Issue by collabwithbeti** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5905]
**Currently, you can only use PowerShell to configure this policy setting.** - I believe this can now be updated in the Teams Admin center within Meetings Policies?

You can edit an existing Teams meeting policy by using the Set-CsTeamsMeetingPolicy cmdlet. Or, create a new Teams meeting policy by using the New-CsTeamsMeetingPolicy cmdlet and assign it to users.

To specify the default value of the Who can present? setting in Teams, set the DesignatedPresenterRoleMode parameter to one of the following:

EveryoneUserOverride: All meeting participants can be presenters. This is the default value. This parameter corresponds to the Everyone setting in Teams.
EveryoneInCompanyUserOverride: Authenticated users in the organization, including guest users, can be presenters. This parameter corresponds to the People in my organization setting in Teams.
OrganizerOnlyUserOverride: Only the meeting organizer can be a presenter and all meeting participants are designated as attendees. This parameter corresponds to the Only me setting in Teams.
Keep in mind that after you set the default value, meeting organizers can still change this setting in Teams and choose who can present in the meetings that they schedule.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
