### ISSUE TITLE
Persistent Chat Listed under SfB Server Sites and SQL Mirroring still listed

### ISSUE THREAD

**Issue by martinboam** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#591]
As Persistent Chat and SQL Mirroring have been deprecated should they still be listed ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3631c9ea-ab9d-bf7f-8c1b-66f050d31949
* Version Independent ID: 5b6a6a2a-0275-73e9-089c-fa8a5c4daace
* Content: [Topology Basics for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/topology-basics/topology-basics?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json)
* Content Source: [Skype/SfbServer/plan-your-deployment/topology-basics/topology-basics.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/topology-basics/topology-basics.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by jambirk** [comment]
Yes, they should. Server 2015 and 2019 have a common set of files, but two mostly parallel tables of contents (the left-hand navigation tree on Docs). Where a certain feature applies to both, we try to leave the server version unspecified. Where there's a new feature, we specify 2019. Where there's a deprecation, we make notes, leave the file 2015 specific, and deliberately omit it from the 2019 TOC.
