### ISSUE TITLE
Opt out of OneDrive for Business and SharePoint to continue using Stream

### ISSUE THREAD

**Issue by bec064** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5911]
Hello, consider a rephrasing of this part?

"Even if a policy says it’s already set to Stream, it might not be set. If it's set to nothing, then the default is Stream. If you want to opt-out, you must reset the policy to Stream to ensure that Stream is the default."

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8935e913-806f-a92c-d09e-e67df4ffd1b4
* Version Independent ID: c7a41cde-66dd-d7cd-1316-42d20ed4841a
* Content: [Use OneDrive and SharePoint for meeting recordings - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/tmr-meeting-recording-change)
* Content Source: [Teams/tmr-meeting-recording-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tmr-meeting-recording-change.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@bec064 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by cichur** [comment]
Thank you for the suggestion. I rephrased that section and published it.
