### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by salakhani** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5914]
[Enter feedback here]
There is a typo here
This should be type and not value.
"chatId": "19:0de69e5e-2da8-4cf2-821f-5e6585b2c65b_5c64e248-3269-4268-a36e-0f80314e9c39@unq.gbl.spaces"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eb2244d-b82d-0559-0255-ac0cb7ce05e3
* Version Independent ID: e3a7a842-7efe-40db-e3c7-da56d7b24c02
* Content: [Export content with the Microsoft Teams Export APIs - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/export-teams-content)
* Content Source: [Teams/export-teams-content.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/export-teams-content.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by salakhani** [comment]
Same thing for "user": {
                    "id": "0de69e5e-2da8-4cf2-821f-5e6585b2c65b",

**Comment by scanum** [comment]
@salakhani Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
