### ISSUE TITLE
Need to update limitation, call forwarding settings does not get migrated when moving from SfB to Teams

### ISSUE THREAD

**Issue by ashgupt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5915]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca38b93a-773e-3864-45b6-128dd3163f37
* Version Independent ID: 7c32e933-94f2-196e-1163-3881df3aaf5a
* Content: [Move users from Skype for Business Server 2019 to Teams - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/move-users-from-on-premises-to-teams)
* Content Source: [Skype/SfbHybrid/hybrid/move-users-from-on-premises-to-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/move-users-from-on-premises-to-teams.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@ashgupt Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @ashgupt, thank you for your feedback and help us to improve docs.microsoft.com.

The article detail the 2 following points at the beginning:
- The user’s pre-existing meetings scheduled for the future will be migrated from on-premises to Teams.
- Contacts that existed on-premises are available in Teams shortly after the user logs on for the first time.

This is what it's migrated to Teams, no more data or settings.

**Comment by scanum** [comment]
@ashgupt Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
