### ISSUE TITLE
Skype having a problem with screen sharing

### ISSUE THREAD

**Issue by daniloaleixo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5916]
I've had one problem several times when screen sharing: someone could not see your screen or vice verse.

The bug happens on Skype application both on linux and mac. 
When I choose to share my screen sometimes other people in the room can't see the screen shared, although some folks also in the same room can. We've found a solution that either the user who is sharing or the users who can't see quit the application and come back in.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
