### ISSUE TITLE
Back End servers are mirrored

### ISSUE THREAD

**Issue by martinboam** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#592]
This is referencing Mirroring and could imply SQL Mirroring but this has been removed in SfB Server 2019. Could lead to confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8833bcab-c38d-60b2-40c0-50f7e5fe2dc2
* Version Independent ID: 8d7d3a8d-f626-15b4-d1ff-dabe33de228a
* Content: [Reference topologies for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/topology-basics/reference-topologies?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json)
* Content Source: [Skype/SfbServer/plan-your-deployment/topology-basics/reference-topologies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/topology-basics/reference-topologies.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by jambirk** [comment]
I've added the deprecation note, and a link to the back-end server planning topic where it also appears.
