### ISSUE TITLE
Calling plan + Meeting Room SKU option to Give the room a phone number and make or receive a calls from the room or join an audio conference using a phone number

### ISSUE THREAD

**Issue by miguelvidex** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5920]
In the table 
![image](https://user-images.githubusercontent.com/26462830/95214883-41a3e800-07e8-11eb-9bd6-4deb21d71149.png)

The option **Without Direct Routing**  should also have the option of :
_Meeting Room SKU + Domestic or International Calling Plan_
Instead of:
_Microsoft 365 Business Voice+ Domestic or International Calling Plan_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-licensing)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-licensing.md)
* Service: **skype-for-business-online**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@miguelvidex Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dstrome** [comment]
The article is correct. If you don't have Direct Routing, you must have one of the following for the meeting room to receive or make calls from or to an external number:

Domestic or International Calling Plan
Microsoft 365 Business Voice

**Comment by akkawamu** [comment]
I can agree without DR, the user needs CallingPlan. and I think the user also needs Meeting room SKU, when the user want outbound call via PSTN. This part of the article don't point out the need of Meeting room SKU.
