### ISSUE TITLE
RSS Feed seems out of date

### ISSUE THREAD

**Issue by limp15000** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5925]
[Enter feedback here]
The RSS Feed has not been updated since 2018. Not sure it is still maintained and we should possibly not reference it anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96088236-4cde-fe10-9023-67f3d339bdbe
* Version Independent ID: 2f4cb807-2a4d-1165-836d-7c2c688b1a2c
* Content: [Microsoft 365 and Office 365 URLs and IP address ranges - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/office-365-urls-ip-address-ranges)
* Content Source: [Teams/Office-365-URLs-IP-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-URLs-IP-address-ranges.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@limp15000 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.




Following up on this issue. Please let me know if there are any updates. Thanks!
