### ISSUE TITLE
Enable or Disable Tasks in your organisations

### ISSUE THREAD

**Issue by gunterda** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5926]
Section: Enable or Disable Tasks in your organisations
Searching for "Tasks" under Manage app show only 3rd party vendors tasks apps. So currently I still need to search for Planner, to disable/enable it. This is a little confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27c4aab7-6115-ff27-5538-0a0bf73755de
* Version Independent ID: 3ff038fc-da4d-fdf4-7b5b-071bd25e3047
* Content: [Manage the Tasks app for your organization in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-tasks-app)
* Content Source: [Teams/manage-tasks-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-tasks-app.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@gunterda Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
