### ISSUE TITLE
Issues with CQD Teams Usage Power BI report

### ISSUE THREAD

**Issue by Rahul-Oza** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5927]
While using CQD Teams Usage report with Power BI, I am not seeing any data or statistics against Internal Audio, Video or Screen Share calls. Here is the example, I am can see statistics for external call but not for internal. Any assistance with this would be much appreciated.

![image](https://user-images.githubusercontent.com/72500867/95324873-0247cb00-08be-11eb-9b76-84e640704bf4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfbb1a90-d5f1-217e-1880-59afe121d979
* Version Independent ID: 7f6c85ae-f2c6-4b0b-6c8a-9bfcbe394328
* Content: [Use Power BI to analyze CQD data for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cqd-power-bi-query-templates)
* Content Source: [Teams/CQD-Power-BI-query-templates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-Power-BI-query-templates.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@Rahul-Oza Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.




Following up on this issue. Please let me know if there are any updates. Thanks!
