### ISSUE TITLE
Local Media Optimization Support

### ISSUE THREAD

**Issue by carolynblanding** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5929]
[Please add column for Local Media Optimization Support as support for this feature is limited to specific SBC vendors and versions. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1a1c01-10a9-7f69-1c7b-1a566b0f5112
* Version Independent ID: 329ee759-40fc-98fb-b91e-87786c63024b
* Content: [Session Border Controllers certified for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-border-controllers?source=docs#feedback)
* Content Source: [Teams/direct-routing-border-controllers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-border-controllers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Please note that this information already appears in the following doc:  https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-media-optimization-configure.  We do not want to duplicate information.  @carolynblanding @nmurav @FilippSe...  which topic do you want this info to appear in?   If local media optimization does not apply to all customers, then I recommend leaving it in the local media op doc.

**Comment by CarolynRowe** [comment]
We could always provide a link from the SBC cert doc to local media op...  Let us know which you prefer.

**Comment by carolynblanding** [comment]
Good point; sorry I missed the SBC vendor support list. I would suggest linking from SBC cert documentation to the LMO documentation. Thanks Carolyn.


Carolyn Blanding

**Comment by CarolynRowe** [comment]
Thanks, @carolynb. I will make this change today.  Closing this issue.
