### ISSUE TITLE
Blocking dial-in users

### ISSUE THREAD

**Issue by ahunkins** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5930]
In light of COVID and especially schools using MS Teams, please explain options to block or manage "hackers" or "bombers" dialing in to meetings to disrupt them. This would also apply to guest users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad892c60-f7e4-0790-66f7-219d28f44ee6
* Version Independent ID: 36e86cca-c5a3-eb4d-477e-1fb7b0b5d7f1
* Content: [Audio Conferencing common questions - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-common-questions)
* Content Source: [Teams/audio-conferencing-common-questions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-common-questions.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@ahunkins Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @ahunkins, thank you for your feedback.

I think you can find the information you are looking for in the following article:
https://docs.microsoft.com/microsoftteams/teams-security-guide#addressing-threats-to-teams-meetings

**Comment by scanum** [comment]
@ahunkins  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
