### ISSUE TITLE
Dial-out (Call me) charges

### ISSUE THREAD

**Issue by ahunkins** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5931]
Please include an answer/explanation for how to view the report for calls that are charged to comm credits when the pool of 60 mins credits for dial-out (call me) minutes has been depleted for the month. It would also be helpful to explain how to find out the cost of such calls.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad892c60-f7e4-0790-66f7-219d28f44ee6
* Version Independent ID: 36e86cca-c5a3-eb4d-477e-1fb7b0b5d7f1
* Content: [Audio Conferencing common questions - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-common-questions)
* Content Source: [Teams/audio-conferencing-common-questions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-common-questions.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@ahunkins Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @ahunkins, thank you for your feedback and help us to improve docs.microsoft.com.

There are full articles about what you are asking for:
https://docs.microsoft.com/microsoftteams/teams-analytics-and-reports/pstn-minute-pools-report
https://docs.microsoft.com/microsoftteams/teams-analytics-and-reports/pstn-usage-report

I think they'll help you.

**Comment by scanum** [comment]
@ahunkins  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
