### ISSUE TITLE
"Share to Teams" button in Outlook desktop?

### ISSUE THREAD

**Issue by cmcapellan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5934]
The "Share to Teams" button in the Outlook desktop client was announced at Ignite 2019, and was listed in the M365 Roadmap under Feature ID 57389 "Teams-Outlook Email Integrations" as "Launched" as of March 2020. The roadmap item includes the "Share to Teams" button as well as the actionable activity emails which _are_ documented on this page.

Given that this roadmap item is launched, shouldn't the documentation for the "Share to Teams" button be on this page too?

Ignite announcement blog post: https://techcommunity.microsoft.com/t5/microsoft-teams-blog/what-s-new-in-microsoft-teams-microsoft-ignite-2019/ba-p/937025#m365

M365 Roadmap item: https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=57389

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f34a4f9-bb6f-03e9-9c11-bb2f43dd9aeb
* Version Independent ID: a6e1ee45-8ce4-96b4-21ad-90ca8af646c4
* Content: [Teams and Outlook email integration - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-outlook-email-integration)
* Content Source: [Teams/teams-outlook-email-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-outlook-email-integration.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@cmcapellan Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.




Following up on this issue. Please let me know if there are any updates. Thanks!
