### ISSUE TITLE
Content sharing

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5935]
The description of the content sharing policies is rather obscure. It would benefit from a table showing who can share with whom.

Under "Allow a participant to give or request control", it does not refer to whether the participant is internal or external.

Under "Allow an external participant to give or request control", the second sentence is garbled. The third sentence refers to "whether external participants can be given control" but the title is "give control", not "be given".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@Air-Git Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Air-Git, thank you for your feedback and help us to improve docs.microsoft.com.

I'm working on it, doing some testing and getting more information internally.

Same as:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6129
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4324

**Comment by scanum** [comment]
@Air-Git  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
