### ISSUE TITLE
AppData folder, Local and/or Roaming?

### ISSUE THREAD

**Issue by lrandall-gillsch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5937]
Hi,

Just wondering which AppData folder you are talking about when you refer to the AppData folder, a user profile since Windows Vista has 2 sub-folders in AppData named Local and Roaming, ones designed for "Local" app data and settings that are specific to the machine you're using that stay on that computer and then the other "Roaming" folder is for app data and settings that follow you and your profile around (If you use Roaming user profiles like us), which AppData folder(s) does Teams in this instance use?

Many thanks and take care,

Luke
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Teams using Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@lrandall-gillsch Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.




Following up on this issue. Please let me know if there are any updates. Thanks!

**Comment by lrandall-gillsch** [comment]
Good afternoon, thank you for your response @scanum but this isn't a technical issue I'm afraid, the Teams app is working fine (As far as we know anyway aha!), it's a documentation one, it doesn't specify whether Teams is installed to the Local or Roaming AppData folder as in C:\Users\<Username>\AppData\Local or C:\Users\<Username>\AppData\Roaming, please could this be updated?
