### ISSUE TITLE
This walkthrough is unusable

### ISSUE THREAD

**Issue by ccraigieTM** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5941]
I have tried to use all of these walkthroughs and have not been able to get through a single one as they are written.  There a lot of dependencies required that are not mentioned, and some things steps I have not been able to resolve at all.  When watching the video https://youtu.be/In-SzWX1Gtw from Microsoft on how to setup a Teams Room, this guide is mentioned, but a completely different process is shown from any of the walkthroughs.

What benefit does the $15/month Teams Rooms license have over an account configured through these guides?

Is there a different way to obtain the registrarpool info?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99951587-c6ee-feb3-ab39-8d6b6969e939
* Version Independent ID: 1cb9d2e6-d4c1-628a-79bf-6ae405263f1d
* Content: [Deploy Microsoft Teams Rooms - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-deploy)
* Content Source: [Teams/rooms/rooms-deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-deploy.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ccraigieTM Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.




Following up on this issue. Please let me know if there are any updates. Thanks!
