### ISSUE TITLE
Page is missing module features

### ISSUE THREAD

**Issue by SQuintin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5942]
Running Get-CsOnlineVoicemailPolicy on my tenant results in the following:
Identity                            : Global
EnableTranscription                 : True
ShareData                           : Defer
EnableTranscriptionProfanityMasking : False
EnableEditingCallAnswerRulesSetting : True
MaximumRecordingLength              : 00:05:00
EnableTranscriptionTranslation      : True

Of these, only these are mentioned in this article:
Identity, EnableTranscription, ShareData, and EnableTranscriptionProfanityMasking

These are missing:
EnableEditingCallAnswerRulesSetting, MaximumRecordingLength, and EnableTranscriptionTranslation
These settings have no documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8228f9b2-a7de-abb4-6f41-70db0b3af155
* Version Independent ID: 8fd9fafb-dd76-59a8-e609-56f06d539a31
* Content: [Set up Cloud Voicemail - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-phone-system-voicemail)
* Content Source: [Teams/set-up-phone-system-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-phone-system-voicemail.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@SQuintin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@SQuintin Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
