### ISSUE TITLE
Inappropriate translation: product name "Teams" to "チーム" in Japanese

### ISSUE THREAD

**Issue by git188** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5944]
https://docs.microsoft.com/ja-jp/microsoftteams/teams-memory-usage-perf
"Teams" is translated as "チーム" on the Japanese page, but it must be "Teams" because it is a product name.

All "チーム" below should be "Teams".

- 電子版のチームでは、より迅速な開発が可能になり、さまざまなオペレーティングシステム (Windows、Mac、Linux) 間で Teams バージョン間のパリティも維持されます。
- システムメモリに含まれているチームの予期される動作を理解し、システムメモリの問題が本当に発生したときの症状を把握することが重要です。
- Chromium は、現在実行されている内容に影響を与えることなくチームのパフォーマンスを最適化するために、チームのメモリ使用量を継続的に調整します。
- 次の図は、4つの異なるシステム上のチームによるメモリ使用量を示しています。
- すべてのアプリで、90% 以上の全体的なシステムメモリ使用量が維持されます。 この量のメモリ使用量によって、チームは、他のアプリやワークロードにメモリを戻す必要があります。 90% のメモリ使用量が継続すると、チームはメモリをシステムに戻さないということになります。これは、問題を示します。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: fc21902c-d522-3851-8587-177f01bc085c
* Version Independent ID: 590bcc64-a86d-b61e-7d94-4e4322c4e71d
* Content: [Microsoft Teams のメモリ使用方法 - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/teams-memory-usage-perf)
* Content Source: [Teams/teams-memory-usage-perf.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-memory-usage-perf.md)
* Service: **msteams**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@git188 Thanks for submitting feedback! We appreciate your inputs and are currently investigating this.

@officeglobal Could you kindly help with this issue? Thanks!

**Comment by TinaMcN** [comment]
@git188 この問題を報告していただきありがとうございます。機械翻訳ツールの問題のようです。  私は人間の翻訳のために記事を送った。 @officeglobal 更新された記事が公開された際にお知らせください  (Thank you for reporting this issue. It appears to be a problem with our machine translation tool. I sent the article to be human translated.
@officeglobal, please let us know when the updated article is published.)

**Comment by TinaMcN** [comment]
@git188 this issue appears to be fixed now.  Please let us know if you notice the issue still.  Thanks again for letting us know about the problem.

**Comment by scanum** [comment]
@git188 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
