### ISSUE TITLE
Review Required DNS Records

### ISSUE THREAD

**Issue by JeffBrownTech** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5945]
I have a concern that the "Important" note about DNS records for federation is incorrect. Lyncdiscover is for client sign-in and locating services. I'm unaware of how it would be used for federation.

This Docs article lists more DNS records that are required for Skype for Business Online but specifies that they are also required for Teams. The only one used for federation is the SRV record:
https://docs.microsoft.com/en-us/microsoft-365/enterprise/external-domain-name-system-records?view=o365-worldwide#external-dns-records-required-for-skype-for-business-online

Maybe it should be specified a bit more that these are required for Skype for Business Online, these are required for Microsoft Teams, and these are required in hybrid scenarios.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d996cf7-9f48-2b30-7759-afaf3fe82caa
* Version Independent ID: 24dd6cdf-d35f-53b2-06c2-0a27891825d4
* Content: [Prepare your organization's network for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/prepare-network)
* Content Source: [Teams/prepare-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/prepare-network.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@JeffBrownTech Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
