### ISSUE TITLE
I cannot create a new mailbox

### ISSUE THREAD

**Issue by onlize** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5946]
Hello,

I cannot create a new mailbox. I have a Skype for Business hybrid and Exchange Online. Exchange was never on-premises.

When I try to run New-mailbox command, I receive the following error:

> The parameters passed to the cmdlet represent a managed account, which doesn't match the namespace state, which is
federated.
    + CategoryInfo          : NotSpecified: (0:Int32) [New-Mailbox], UserInputInvalidException
    + FullyQualifiedErrorId : [Server=SJ0PR03MB5518,RequestId=5d11d13c-0b7e-4cb6-84e1-dea2bd945634,TimeStamp=10/9/2020
    7:09:59 PM] [FailureCategory=Cmdlet-UserInputInvalidException] C2A2F91F,Microsoft.Exchange.Management.RecipientTa
  sks.NewMailbox
    + PSComputerName        : outlook.office365.com

What can I do?

![image](https://user-images.githubusercontent.com/28982031/95623308-a6568100-0a3a-11eb-9128-0f5a630478e4.png)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.




Following up on this issue. Please let me know if there are any updates. Thanks!
