### ISSUE TITLE
Sample code appears to be incorrect

### ISSUE THREAD

**Issue by redmondChris** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5948]
The sample code near the top of this article appears to wrong, as it results in an error.

`New-Team -Name "Contoso Marketing" -Description "Collaboration space for Contoso's Marketing department`

Based on the syntax at https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps#syntax and the subsequent successful team creation, I believe the string below should be used as the sample code. I changed -Name to -DisplayName and added a quotation mark at the end of the -Description string.

`New-Team -DisplayName "Contoso Marketing" -Description "Collaboration space for Contoso's Marketing department"`

With these changes, the command successfully runs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a60f957-8007-280c-4081-aa1930771767
* Version Independent ID: d6e71a44-d4ba-b82c-c2fc-ea667f7a889a
* Content: [Manage Teams with Microsoft Teams PowerShell - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-managing-teams)
* Content Source: [Teams/teams-powershell-managing-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-managing-teams.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
@redmondChris Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
