### ISSUE TITLE
Storage of non-channel meetings in a random chat member's onedrive is a terrible idea

### ISSUE THREAD

**Issue by SHAGGAR** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5953]
The majority of the teams recorded meetings in our org are in ad-hoc, non-channel chats.  This change to store the meeting recording based on whoever manages to click record first is a disaster waiting to happen.  Most users do not have the mental capacity to understand file permissions, let alone the incredibly convoluted permissions in sharepoint/onedrive.  Forcing users to now manage these recording files manually in their personal onedrive instead of having them managed org wide by stream will be a massive downgrade in user experience and an increase in administrative overhead.  

Personal onedrives are not good places for long term content of any type, so we generally tell users not to store stuff there if its intended to be accessed by other people.  This prevents the management headache of going through their files when they get deleted.  This change to force the storage of recordings in their personal one drive will add more administrative overhead.  

Instead of using personal user onedrives, you should instead create a OneDrive/Sharepoint Site that acts as the default storage location for all org wide non-channel meeting recordings.  This would eliminate all the hassles of dealing with personal onedrives (permissions, file retention, accidental user deletion, etc...), and give us something closer to the existing stream experience.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
