### ISSUE TITLE
This feature is released to GCC, but docs not updated

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5954]
I believe the rollout to GCC has completed for this feature. Please confirm with PG and update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca3f7a45-e892-fbb3-baf1-c556fa8e3720
* Version Independent ID: 9c8b63e8-7320-ed8f-e560-ed478009dd57
* Content: [Priority notifications in Teams messaging - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/pri-message)
* Content Source: [Teams/teams-add-on-licensing/pri-message.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/pri-message.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@npherson thank you for reaching out. I just had a look at this article and I see that you commented 17 days ago - the article was updated two days ago. Is there still something missing from this article or has the update clarified all?

**Comment by scanum** [comment]
@npherson  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
