### ISSUE TITLE
Updates to the scripts

### ISSUE THREAD

**Issue by agallego-css** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5957]
I understand the script shared is a draft, and is not mandatory to work (or we are not mandatory to officially support it).
But today I got a CSS customer opening a case, saying the "scripts we published are giving errors".

I made some updates(tweaks) and tested in EDU test tenant, and it seems to work fine.

```Powershell

#Version 2.0, 10/12/2020 - Second Draft
#1) replace line 36 to use only 'AzureAD' module and not 'msonline' anymore:
if ( !(Get-Module AzureAD -ListAvailable) -and !(Get-Module AzureAD) ) 
    {
        Install-Module AzureAD -Force -ErrorAction Stop
    }
Connect-AzureAD

#2) replace lines 42, 43 to:
$Group = New-azureADGroup -DisplayName $teachergroupname -Description $teachergroupdesc -MailEnabled $false -MailNickName $teachergroupname.Replace(" ","") -SecurityEnabled $True

replace lines 59, 62 to:
$Group = New-azureADGroup -DisplayName $studentgroupname -Description $studentgroupdesc -MailEnabled $false -MailNickName $studentgroupname.Replace(" ","") -SecurityEnabled $True

#3) replace line 97 to:
Write-Host -ForegroundColor Green "Getting Assigned Licenses for $($user.DisplayName)"

#replace lines 98 and 99 to:
$AssignedLicenses = ($User | select -ExpandProperty assignedlicenses).skuid

#4) replace line 126 to:
try{
	Add-AzureADGroupMember -ObjectId $teachergroupid -RefObjectId $OBJ -ErrorAction Stop
    Write-Verbose "Successfully Added user $OBJ to $teachergroupname"
}
catch
{
    if ( $_.Exception.ErrorContent.Message.Value -match 'One or more added object references already exist' ) {
        Write-Host "User $DN already exists in group $teachergroupname"
    } 
    else {
        Write-Host "An error Occurred: $_"
    }
}


# replace line 141 to:
try{
	Add-AzureADGroupMember -ObjectId $studentgroupid -RefObjectId $OBJ -ErrorAction Stop
    Write-Verbose "Successfully Added user $OBJ to $studentgroupname"
}
catch
{
    if ( $_.Exception.ErrorContent.Message.Value -match 'One or more added object references already exist' ) {
        Write-Host "User $DN already exists in group $studentgroupname"
    } 
    else {
        Write-Host "An error Occurred: $_"
    }
}

#5) replace line 150 to:
$teacherGrpMembers = Get-AzureADGroupMember -ObjectId $facultyid

# replace line 175 to:
$teacherGrpMembers = Get-AzureADGroupMember -ObjectId $studentid

#6) replace line 159 to:
Add-AzureADGroupMember -ObjectId $facultyid -RefObjectId $id

# replace line 184 to:
Add-AzureADGroupMember -ObjectId $studentid -RefObjectId $id

#7) replace line 168 to:
Remove-AzureADGroupMember -ObjectId $facultyid -MemberId $id

#replace line 193 to:
Remove-AzureADGroupMember -ObjectId $studentid -MemberId $id
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f60bf2b-97f5-81ef-c675-aeec1cce2979
* Version Independent ID: 0a7ec412-71c5-0b67-e02b-7b211009d622
* Content: [PowerShell script sample - Create security groups for educators and students in your school - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/scripts/powershell-script-security-groups-edu)
* Content Source: [Teams/scripts/powershell-script-security-groups-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/scripts/powershell-script-security-groups-edu.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
