### ISSUE TITLE
Page outdated

### ISSUE THREAD

**Issue by Tsirke** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5958]
Hi All, could you please update this page? There have been new countries included on the 1st October 2020 (namely: Austria, Denmark, Italy, Portugal, Sweden, and Switzerland) which can now avail of Calling Plans but the site does not reflect these changes just yet. 

Thanks for the help in advance!
Viktor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 444ef719-3f33-539e-24d7-87fb38580a17
* Version Independent ID: fccc5dd3-1538-8dd7-bb7d-2cb5d59a93f3
* Content: [Country and region availability for Business Voice - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/business-voice/country-region-availability#feedback)
* Content Source: [Teams/business-voice/country-region-availability.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/business-voice/country-region-availability.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Tsirke** [comment]
Thanks Manuela, do you have any news by any chance or need any further information on my side?

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
