### ISSUE TITLE
Pricing not available

### ISSUE THREAD

**Issue by hazymat** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#596]
The link in this doc (anchor text: "You can find pricing information here.") leads to Microsoft Teams pricing, however that page does not provide call pricing information. That page has a section "See rates for where you want to call" however this links to a document that applies only to toll free numbers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01a8b6d4-e6fe-0ebb-f7a6-07593b11d453
* Version Independent ID: f9885afa-497b-2b66-0cc0-253242ab36ca
* Content: [What are Calling Plans in Office 365?](https://docs.microsoft.com/en-us/skypeforbusiness/what-are-calling-plans-in-office-365/what-are-calling-plans-in-office-365)
* Content Source: [Skype/SfbOnline/what-are-calling-plans-in-office-365/what-are-calling-plans-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/what-are-calling-plans-in-office-365/what-are-calling-plans-in-office-365.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@hazymat - Thank you for submitting this feedback.

This is a good catch about the pricing information and where to find it. Here is a link that shows the pricing for O365 and which plan includes Teams. https://products.office.com/en-us/compare-all-microsoft-office-products?tab=2 

I was able to get this into the backlog for the Teams/Skype team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.
