### ISSUE TITLE
Labels and Guest Access

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5962]
Can this section either be expanded to include more about 'how' to do this, or include a link to relevant information? Thanks!
https://docs.microsoft.com/en-us/microsoftteams/sensitivity-labels#guest-access-to-teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ede6de99-ead2-fdb1-22f4-8b8240829732
* Version Independent ID: ed36687a-c091-44e3-1d8e-1025d1209fec
* Content: [Sensitivity labels for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sensitivity-labels)
* Content Source: [Teams/sensitivity-labels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sensitivity-labels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@npherson thanks again for reaching out and helping improve MS Docs. I see this article has also been updated in the interim, but please let me know if something is still missing. Please also see here - https://docs.microsoft.com/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide

**Comment by scanum** [comment]
@npherson  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by npherson** [comment]
The section has not been updated with any information about how to actually do this or links to more information: https://docs.microsoft.com/en-us/microsoftteams/sensitivity-labels#guest-access-to-teams

**Comment by npherson** [comment]
It doesn't look like I have permission to reopen the issue, @scanum.
