### ISSUE TITLE
Enable Teams Room devices to join third-party meetings

### ISSUE THREAD

**Issue by alewindows** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5963]
Hello,

At this moment, this functionality is available in Team Room App version 4.6.20.0

I've been able to join a Zoom meeting (in preview mode but it works fine), but when trying to join to a webex meeting I receive this error message:

(translated from spanish, it may be different)
"Apparently, this is not an online meeting.

We were unable to find any valid Union link in the invitation to the meetiing. Ask the organizer for ..."

I followed all the instructions included in this docs' document.

Any help?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 9c62081e-2421-80b9-8ba9-aaf8fd55e432
* Version Independent ID: 5df3c5e5-978f-cfa7-9e5c-3cd7f65fa8ff
* Content: [Habilitar los dispositivos de salas de equipos para unirse a reuniones de terceros - Microsoft Teams](https://docs.microsoft.com/es-es/microsoftteams/rooms/third-party-join)
* Content Source: [Teams/rooms/third-party-join.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/third-party-join.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@alewindows Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
