### ISSUE TITLE
is the release status still preview / early release ?

### ISSUE THREAD

**Issue by takawazo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5965]
Based on below road map, the status of this feature 64162 is [Launched], not rolling out.
Is this feature's status still early release ? 
https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=microsoft%2Clists

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac12129f-4d94-cbbd-4c34-03666617c889
* Version Independent ID: 015463d6-8fb9-7240-a3f1-8ae288dd9e90
* Content: [Manage the Lists app for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/manage-lists-app)
* Content Source: [Teams/manage-lists-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-lists-app.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@takawazo Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
