### ISSUE TITLE
CQD Connector Limitation - GCC support with the connector in the Power BI service

### ISSUE THREAD

**Issue by greganth1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5966]
My understanding is the connector is now supported in GCC, but not GCCH or DOD.

The documented limitation should reflect that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 067e8376-df94-9a44-5263-cd1fc84879bf
* Version Independent ID: 924240c8-52c5-42db-36b8-28751f838784
* Content: [Install Power BI Connector to use CQD query templates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cqd-power-bi-connector#limitations)
* Content Source: [Teams/CQD-Power-BI-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-Power-BI-connector.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@greganth1  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@SerdarSoysal

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
