### ISSUE TITLE
Working with PowerShell

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5972]
Please include information about how to manage phone numbers also using powershell - for example get list of the available phone numbers in org.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 224b0537-e144-f5ed-6974-6e34733bceb2
* Version Independent ID: 4f1875c6-77ef-f636-669e-5f3af9691f7d
* Content: [See a list of phone numbers in your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/see-a-list-of-phone-numbers-in-your-organization)
* Content Source: [Teams/see-a-list-of-phone-numbers-in-your-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/see-a-list-of-phone-numbers-in-your-organization.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
