### ISSUE TITLE
Add note for GCC limits

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5976]
The limits for the maximum number of members in a team for GCC cloud is 5000 but this is not noted in the document. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#teams-and-channels)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by rimazima** [comment]
Can we please update the limits for all US Gov Clouds in this article? GCC right now has a 5k Team Member Limit while GCCH and DOD still have 2,500 Team Member Limit. (This is Rima Reyes from Teams Engineering.)

**Comment by scanum** [comment]
@TheBluLion Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @TheBluLion and @rimazima, thank you for your feedback and help us to improve docs.microsoft.com.

The article was updated 3 days ago with this information:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/5989

This should be reflected in docs in the next few hours.
