### ISSUE TITLE
Downloads Links aren't being updated again

### ISSUE THREAD

**Issue by ekkonomix** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5977]
The download links are pointing to an old binary again.  Please consider redirecting to the official download source instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ekkonomix Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @ekkonomix, thank you for your feedback and help us to improve docs.microsoft.com.

@LanaChin @sarossma could you kindly help here? Thanks!

**Comment by NathalieBotteldoorn** [comment]
Please update the links of the msi download. Version is more then 2 months old!!!

**Comment by NathalieBotteldoorn** [comment]
There is a more recent download version on https://docs.microsoft.com/en-us/microsoftteams/msi-deployment#vdi-installation

**Comment by LanaChin** [comment]
Hi @ekkonomix. Thanks for your feedback. We've updated the MSI links in the article.
