### ISSUE TITLE
Teams Service Administrator role seems to be all sufficient for a Teams Admin except for assigning a service number to a resource account

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5978]
Teams Service Administrator role seems to be all sufficient for a Teams Admin except for assigning a service number to a resource account. Could you please fix (add ability to this role) or advise what additional role is required to avoid needing Global Administrator role to perform this task?
Many Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b434530-6bf2-6e00-6eae-6fa043d022ce
* Version Independent ID: caab785f-e3a4-831a-87d8-26934a9f834f
* Content: [Use Microsoft Teams administrator roles to manage Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/using-admin-roles)
* Content Source: [Teams/using-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/using-admin-roles.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@SvenBell Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @SvenBell, thank you for your feedback.

Teams Service Administrator should be enough to assign a service number to a resource account. Are you using Direct Routing?

**Comment by scanum** [comment]
@SvenBell  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by SvenBell** [comment]
We are not using direct routing (we are using call plans). Still no update on doco page with what roles are required to achieve assigning number to resource account. You cannot do it from CSP (DAP) TAC portal. Please resolve,
