### ISSUE TITLE
Support Lync & SFB Servers

### ISSUE THREAD

**Issue by d1bjo0** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#598]
Please update to show what on-premise Servers are supported for interoperability. For instance- what capability is supported if a customer have Lync 2010, Lync 2013, or SFB 2015. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49921e8a-55ac-f547-d4e2-d329f5089c2e
* Version Independent ID: 91c3433a-3684-95cd-3426-4a5877b33106
* Content: [Migration and interoperability guidance for organizations using Teams together with Skype for Business](https://docs.microsoft.com/en-us/microsoftteams/migration-interop-guidance-for-teams-with-skype)
* Content Source: [Teams/migration-interop-guidance-for-teams-with-skype.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/migration-interop-guidance-for-teams-with-skype.md)
* Service: **msteams**
* GitHub Login: @arachmanGitHub
* Microsoft Alias: **MyAdvisor**

**Comment by arachmanGitHub** [comment]
Thank you @d1bjo0 for the feedback. Interop is mainly driven from Skype for Business Online, so on-prem version has no bearings with the capabilities supported for Teams interop. We'll update the article to include the supported on-prem server versions for interoperability with Teams for clarity.

**Comment by kenwith** [comment]
@arachmanGitHub - thanks!
