### ISSUE TITLE
Please add what role(s) are required to perform the task

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5980]
Please add what role(s) are required to perform the task of assigning a number to a resource account. 
Teams Service Admin can do most Teams Admin tasks but not assign number to resource account, that seems to require Global Administrator or an additional role (please specify)

Many Thanks :)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@SvenBell Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @SvenBell, thank you for your feedback.

Similar to https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5978.

Are you using Direct Routing or Calling Plans?

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by SvenBell** [comment]
Using Calling Plans

**Comment by SvenBell** [comment]
> Hi @SvenBell, thank you for your feedback.
> 
> Similar to #5978.
> 
> Are you using Direct Routing or Calling Plans?

Using Calling plans

**Comment by dariomws** [comment]
Hi, you should be able to do this assignment with a "Teams Service Administrator". I think it is not a documentation issue as you clearly should be able to do it.

For your inquiry, I need to kindly suggest opening a support ticket directly from your tenant's administration. They will be able to help you as here we are limited to documentation issues and improvements.

Support URL: https://docs.microsoft.com/microsoft-365/admin/contact-support-for-business-products.

Thank you!

**Comment by SvenBell** [comment]
We are MS gold partner and have deployed nearly 100 tenants, never been able to assign resource accounts a number with just Teams Service Admin role, so clearly can't without elevating Global Admin role.
I will log this with support but would request you test this and add note to documentation that this is an issue. I have seen other post on internet by others to confirm this.

**Comment by dariomws** [comment]
Hi @MikePlumleyMSFT,

Could you kindly help me to confirm this information? Thanks!

**Comment by dariomws** [comment]
@SvenBell could you kindly share the other post on the Internet? Thanks!

**Comment by MikePlumleyMSFT** [comment]
@CLYVR do you know what role is required in order to assign a number to a resource account?

**Comment by SvenBell** [comment]
> @SvenBell could you kindly share the other post on the Internet? Thanks!

https://www.reddit.com/r/sysadmin/comments/gvvgcr/unable_to_assign_a_number_to_resource_account_in/

**Comment by dariomws** [comment]
@CLYVR do you know what role is required to assign a number to a resource account? It seems that Teams Service Admin is not enough. Thanks!
