### ISSUE TITLE
Microsoft Stream retention period for Teams meeting records

### ISSUE THREAD

**Issue by mheptinstall** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5981]
Under _Prerequisites for Teams cloud meeting recording_ it notes:

> 1 As of August 20, 2020, access to the meeting recording file will expire after 21 days for users with A1

I read the 21 day period as only applying to users who start a recording who are licensed with A1. 

Later in the article _Where your meeting recordings are stored_ it states:

> Meeting recordings are stored in Microsoft Stream cloud storage. Recordings are retained and available for viewing and download for 21 days

So the 21 day period is not specific to A1 licensed and users and is for anyone who meets the pre-requisites?

There is no mention of the 21 day retention period in the [Teams meeting recording end user documentation](https://aka.ms/recordmeeting).

It is unclear how long a Teams meeting recording is being kept for in Microsoft Stream and whether users need to act to retain them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@mheptinstall Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
