### ISSUE TITLE
pooling in calling plans

### ISSUE THREAD

**Issue by EvgenyArtemyev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5983]
Hello

Please, clarify in the article the key feature of calling plans - pooling. based on the information in the article most of readers may understand it as there is no pooling minutes between users with calling plans.
Although, it works by accumulating all minutes for all users based on type (domestic and international) and based on country of the users. 
Besides, there is a clear message about pooling in the article about Audio Conferencing.
https://docs.microsoft.com/en-us/microsoftteams/complimentary-dial-out-period

thank you in advance

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 243fa83d-b7bf-323a-a14a-026915d3d058
* Version Independent ID: fd4a310b-3144-4a8b-1bde-c2efd0c87377
* Content: [Calling Plans for Microsoft 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/calling-plans-for-office-365)
* Content Source: [Teams/calling-plans-for-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/calling-plans-for-office-365.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@EvgenyArtemyev Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by EvgenyArtemyev** [comment]
Hi @dariomws , thanks for reply!

I mentioned the article to draw the attention on the part How are minute pools calculated? https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-subscription-dial-out#how-are-minute-pools-calculated
The article contains a very brief and clear message about how it calculates ".... All 115 users share a pool of (115 users x 60 min = 6,900 conferencing dial-out out...."

Such a message is much more clear than merely "Visit Country and region availability to find out about monthly minutes available for each organization in each country/region", is not it?

When a customer or a Partner goes there, e.g. to description of UK. There is not info about pooling here as well, just list of calling plans with minutes.
![image](https://user-images.githubusercontent.com/42608460/96752566-529f4c80-13d7-11eb-9830-f06b2d17c059.png)

Based on my experience of with communicating with MS Partners they are often a bit confused about pooling for Calling plans and I've never faced a Partner confusing about pooling for Audio Conferencing.

it would be amazing to have a similar description about pooling on the tenant level between Calling Plans domestic/international and communication credits.

**Comment by dariomws** [comment]
It's true @EvgenyArtemyev, I was mixing things up. I'm considering an update on this article, give me some time I'll be working on it.

**Comment by EvgenyArtemyev** [comment]
Brilliant. Thank you so much

**Comment by dariomws** [comment]
@EvgenyArtemyev done. Please if you have some minutes, access the following link to check the sentence and let me know if you have any suggestion:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/6059/files

**Comment by EvgenyArtemyev** [comment]
Hi @dariomws
You caught the point. it is exactly what I was looking for. just nothing to add 👍 

Thank you so much

**Comment by dariomws** [comment]
You're welcome!

Thanks again, for taking out some time to open the issue. I appreciate and encourage you to do the same in the future also.
