### ISSUE TITLE
Page for New-CsOnlineSession is not published

### ISSUE THREAD

**Issue by TobiasAT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5985]
The link for New-CsOnlineSession is a deadlink, or the page at https://docs.microsoft.com/en-us/powershell/module/teams/new-csonlinesession has not been published yet.
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 173b5929-529b-938b-b6ab-59f05a5d69a8
* Version Independent ID: 0a3dfe5e-938f-933d-637e-b7449e3b8aa5
* Content: [Microsoft Teams PowerShell Release Notes - Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/teams-powershell-release-notes)
* Content Source: [Teams/teams-powershell-release-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-release-notes.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
@TobiasAT Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
