### ISSUE TITLE
Almost there!

### ISSUE THREAD

**Issue by jrose1982** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5986]
This page _almost_ answered all my questions about Teams Presence States:
https://docs.microsoft.com/en-us/microsoftteams/presence-admins

What I was hoping to find, for each of the App configured Presence States, is an explanation for how it is determined. To be more specific:

- I know that Available means the app is active on at least one device. But what is Available, Out of Office?
- I understand that Busy and In a meeting come from the user's Outlook calendar, and On a Call means they're on a Teams call. What is On a call, out of office?
- I often see my coworkers status as Offline; I take this to mean they are logged out of Teams on all their devices. Under what circumstances does it show "Out of Office" instead?

By understanding how the system interprets various variables, I can better understand what my colleagues see.
My presence state is a passive message I send to my whole company, much like body language when they see me in person. So it's a little frustrating when I don't know what I'm saying.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a162ef5c-3099-7f58-4178-d29e3ec2b5a7
* Version Independent ID: 6ca31e56-052d-6c62-1323-b5aaaae1f04a
* Content: [User presence in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/presence-admins)
* Content Source: [Teams/presence-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/presence-admins.md)
* Service: **msteams**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by cichur** [comment]
I'll look into your questions.

**Comment by cichur** [comment]
Hi @jrose1982 
I worked with the PM and made several changes to this article. I believe we've answered all of your questions. Thank you for your feedback. 
https://docs.microsoft.com/en-us/microsoftteams/presence-admins

**Comment by jrose1982** [comment]
It's perfect. Thank you very much!
