### ISSUE TITLE
Missing an L in Capabilities

### ISSUE THREAD

**Issue by SapiensID** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5987]
[Enter feedback here]
https://docs.microsoft.com/en-us/microsoftteams/faq-journey#calling-capabiities

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbeb59c4-349f-944c-5183-4fb26a34c22b
* Version Independent ID: 2beb18af-35a6-de0a-d90f-89c94533b8da
* Content: [Upgrading from Skype for Business to Teams FAQ - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/faq-journey#calling-capabiities)
* Content Source: [Teams/FAQ-journey.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/FAQ-journey.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@SapiensID Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
