### ISSUE TITLE
Endpoint Data File Section Correction.

### ISSUE THREAD

**Issue by greganth1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5988]
It should reflect that there are seven columns and not six in the endpoint data file.  

Here's a corrected version of the text to use for this section.  Replace six with seven. Put a comma after Fabricam in the sample row and remove the comma at the end of the sample row. Add EndpointMake after EndpointName in the Field row.
------------------------------------
The other type of CQD tenant data file is the Endpoint data file. The column values are used in the call record’s First Client Endpoint Name or Second Client Endpoint Name column to show Endpoint Make, Model, or Type information. The format of the data file you upload must meet the following criteria to pass the validation check before upload:

The file must be either a .tsv file (columns are separated by a TAB) or a .csv file (columns are separated by a comma).

The content of the data file doesn't include table headers. The first line of the data file is expected to be real data, not a header label like "EndpointName".

All **seven** columns use the String data type only. The maximum allowed length is 64 characters.

A data field can be empty but must still be separated by a tab or comma. An empty data field just assigns an empty String value.

EndpointName must be unique, otherwise the upload fails. If there is a duplicate row or two rows that use the same EndpointName the conflict will cause incorrect joining.

EndpointLabel1, EndpointLabel2, and EndpointLabel3 are customizable labels. They can be empty Strings or values such as “IT Department designated 2018 Laptop” or “Asset Tag 5678”.

There must be **seven** columns for each row and the columns must be in the following order:

Field order:

EndpointName, **EndpointMake,** EndpointModel, EndpointType, EndpointLabel1, EndpointLabel2, EndpointLabel3

Sample row:

1409W3534, Fabrikam, Model 123, Laptop, IT designated 2018 Laptop, Asset Tag 5678, Purchase 2018

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200d8054-efa7-bdd3-8b13-d7d73924ecbd
* Version Independent ID: 9972bece-abf2-8f48-ba07-b8a6097602e6
* Content: [Upload tenant and building data in Call Quality Dashboard (CQD) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cqd-upload-tenant-building-data)
* Content Source: [Teams/CQD-upload-tenant-building-data.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-upload-tenant-building-data.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@greganth1 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
