### ISSUE TITLE
Typo/missing

### ISSUE THREAD

**Issue by mike-yam** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5996]
I guess there is typo and a missing word:

> Member who clicked on Record has full rights - Other members from the same tenant have Read rights - Other members **(from)** different **(tenant)** have no rights to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8935e913-806f-a92c-d09e-e67df4ffd1b4
* Version Independent ID: c7a41cde-66dd-d7cd-1316-42d20ed4841a
* Content: [Use OneDrive and SharePoint for meeting recordings - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/tmr-meeting-recording-change)
* Content Source: [Teams/tmr-meeting-recording-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tmr-meeting-recording-change.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Thank you. I'll make the change and publish it today.
