### ISSUE TITLE
Support of Windows 10 LTSB/LTSC variants

### ISSUE THREAD

**Issue by Weishaupt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5997]
The article does not explicitly mention Windows 10 LTSB / LTSC variants. As far as I'm aware those are supported by the Teams client, but I'm not 100% sure.

As Microsoft Apps for Enterprise are not supported by any version of Windows 10 LTSC it is also interesting to know what happens if MS Teams is deployed using the Click-to-run installer on the LTSC variant.

Can you please clarify wheter the MS Teams Client is supported on those Windows 10 variants and also if a deployment using the Click-to-run installer is supported on Windows 10 LTSC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29a61ff5-b3a5-158d-149a-dec344060e05
* Version Independent ID: 97fac351-a283-aaa8-cde1-fbd9cf4e8504
* Content: [Hardware requirements for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/hardware-requirements-for-the-teams-app)
* Content Source: [Teams/hardware-requirements-for-the-teams-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hardware-requirements-for-the-teams-app.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@Weishaupt  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Weishaupt** [comment]
Hey @lindspea 

The Microsoft Teams rooms app and the Microsoft Teams client are not the same thing, thus the release support of the app does not neccessarily reflect the support of the MS Teams client.
The second link has absolutely nothing to to with the mentioned issue at all.

So these links do not help, sorry.

**Comment by Weishaupt** [comment]
@scanum @lindspea any update regarding this topic?

**Comment by lindspea** [comment]
@SerdarSoysal please could you assist?

**Comment by lindspea** [comment]
@Weishaupt https://techcommunity.microsoft.com/t5/windows-it-pro-blog/changes-to-office-and-windows-servicing-and-support/ba-p/151509 please let me know if you find any answers here.

**Comment by Weishaupt** [comment]
> please let me know if you find any answers here.

No, this content is not any help. Maybe someone from the product group can shed some light on the question whether MS Teams is supported by Win 10 LTSB/LTSC?

**Comment by lindspea** [comment]
@dstrome please can you confirm if MS Teams is supported by Win 10 LTSB/LTSC?

**Comment by dstrome** [comment]
Teams is not supported on Windows 10 LTSC. I'll update the topic.

**Comment by BigEaseGueldi** [comment]
Hi @dstrome 
Could you provide us with a link to the official article stating "MS Teams is not supported on Windows LTSC"?

Btw I would suggest that you stop taking about LTSB/C (it's only LTSC now) and start using versions like "Windows 10 Enterprise LTSC 2019". As the upcoming version of Office LTSC will include MS Teams, I would "assume" that the next LTSC version of Windows will do the same.
