### ISSUE TITLE
Inconsistent port adjacency requirement

### ISSUE THREAD

**Issue by tomdewing** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6000]
The sentence "* The port ranges you assign cannot overlap and **must** be next to each other." conflicts with the information on https://docs.microsoft.com/en-us/microsoftteams/qos-in-teams#choose-initial-port-ranges-for-each-media-type which suggests: "If you later need to adjust the port ranges to improve user experience, the port ranges can not overlap and **should** be adjacent to each other." There does not appear to be any restriction that it **must** be but understand they **should** be adjacent to simplify firewall requirements. Please can you clarify and update one of these docs accordingly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Manage meeting settings - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/meeting-settings-in-teams?WT.mc_id=TeamsAdminCenterCSH#bknetwork)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@tomdewing  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@tomdewing  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
