### ISSUE TITLE
Find-Module MicrosoftTeams -AllowPrerelease does not list preview versions of Microsoft Teams module

### ISSUE THREAD

**Issue by dbird03** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6006]
According to the linked documentation page, the following command should show the latest preview version of the MicrosoftTeams module on the PowerShell Gallery:
`Find-Module MicrosoftTeams -AllowPrerelease`

When I run the command, I get the same results as running it without the `-AllowPrerelease` switch. I even tried the `-AllVersions` switch, but the results still do not include the 1.1.5 preview or 1.1.3 preview version. Am I doing something wrong, or could there possibly be an issue with the module manifest file not properly tagging these versions as prerelease?

![image](https://user-images.githubusercontent.com/42259193/96509074-85a3dd80-1229-11eb-980a-cc17fa4570e8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd283f6e-3865-ed70-d663-cc461ee8ba57
* Version Independent ID: 2450d311-fc04-d8b6-b4a2-b1890ec6fc3e
* Content: [Install Microsoft Teams PowerShell - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install)
* Content Source: [Teams/teams-powershell-install.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-install.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
@dbird03 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by dbird03** [comment]
Hello, @scanum. I don't believe technical support would be able to resolve this issue. I just tested the `-AllowPrerelease` switch with the ExchangeOnlineManagement module from the PowerShell Gallery, and it returned the expected results (see screenshot below). This leads me to believe the issue is with the MicrosoftTeams module and should be escalated to the team who manages this module. Is that a different team than the team who manages this documentation?

![image](https://user-images.githubusercontent.com/42259193/96728394-1261af00-1382-11eb-8856-bb2eeaedb413.png)
