### ISSUE TITLE
License expiration date

### ISSUE THREAD

**Issue by JuliaMitrofan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6012]
Hello, 

The following phrasing is confusing and unclear to partners and to us as well, especially the deadline included: on or after Jan 2021. Can examples be added so it would be more clear how the license works during that timeframe? 

_**How long does the Teams Exploratory experience last**
The Microsoft Teams Exploratory experience is available at no additional cost until your next agreement anniversary or renewal on or after January 2021. At that time, end users on a Microsoft Exploratory experience license will need to move to a paid license that includes Teams. Any Microsoft Exploratory experience licenses initiated after that will remain available at no additional cost until your next anniversary or renewal cycle.

Thank you!

**Comment by scanum** [comment]
@JuliaMitrofan Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
