### ISSUE TITLE
Manage team creation errors section - the Teams sensitivity labels functionality is no longer in preview

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6013]
In section Manage team creation errors the Teams sensitivity labels functionality is no longer in preview but is now GA. This section needs updating

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ede6de99-ead2-fdb1-22f4-8b8240829732
* Version Independent ID: ed36687a-c091-44e3-1d8e-1025d1209fec
* Content: [Sensitivity labels for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sensitivity-labels)
* Content Source: [Teams/sensitivity-labels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sensitivity-labels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@nikki-c  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
Hi @nikki-c. Thanks again for reaching out. Just for clarity are you referring to this section:
"Manage team creation errors
If team creation begins to fail at any point during the public preview, you have two options:
Ensure that sensitivity labels are not mandatory for any user during team creation.
Turn off sensitivity labels using the scripts in Enable this preview."
What are you suggesting needs to be amended?

**Comment by nikki-c** [comment]
Lindsay
Hi I have reread the page and it must have been updated already as there is no mention about the sensitivity labels being in private preview.
Thanks, This can be closed.

Nikki Chapple
Organisational Change Manager
United Kingdom | Cloud Communications
NTT

T:
+442080800656
M:
+447500766185
E:
n.chapple@arkadin.com<mailto:n.chapple@arkadin.com>

NTT Cloud Communications UK Ltd. is an entity of NTT Ltd.

[cid:image001.jpg@01D6AE07.04E79BE0]<https://arkadin.com/> [cid:image002.jpg@01D6AE07.04E79BE0] <https://twitter.com/arkadinservices#xd_co_f=MDgwMzM4NzQtY2Y5Mi00YTEyLWIxMGQtODQwNWIxMzhiZDgz~>  [cid:image003.jpg@01D6AE07.04E79BE0] <https://www.linkedin.com/company/arkadin/>  [cid:image004.jpg@01D6AE07.04E79BE0] <https://www.facebook.com/ArkadinCloudComm>  [cid:image005.jpg@01D6AE07.04E79BE0] <https://www.instagram.com/globalntt/>  [cid:image006.jpg@01D6AE07.04E79BE0] <https://www.youtube.com/user/ArkadinConference>
[cid:image007.jpg@01D6AE07.04E79BE0]<http://www.arkadin.com/>

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@nikki-c  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
