### ISSUE TITLE
Teams meeting capacity is wrong

### ISSUE THREAD

**Issue by MercMeier** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6014]
The doc says that a Teams meeting limit is 300.  We are having a meeting with 323 today.

Dave

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@MercMeier  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@MercMeier thank you for reaching out and helping improve MS Docs. Please see the Important note above the limits mentioning that limits will be increased up to January 2021.

**Comment by scanum** [comment]
@MercMeier  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
