### ISSUE TITLE
Skype Decommissioning Guidance Needed

### ISSUE THREAD

**Issue by dinocaputo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6018]
This article is advising users NOT to run the disable-csUser once migration to Teams has been completed.  However, customers are wondering how they can decommission Skype for Business Server without running the disable-csUser cmdlet.  More clarity is needed here.  Perhaps a link to a new page on how to decommission Skype for Business Server once all active users have been moved to Microsoft Teams.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ce37c7f-6f13-8442-bfdb-47065a7339b3
* Version Independent ID: 9a2b5082-369d-7c04-4fa8-81c1440ea119
* Content: [Disable hybrid to complete migration to the cloud - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/cloud-consolidation-disabling-hybrid)
* Content Source: [Skype/SfbHybrid/hybrid/cloud-consolidation-disabling-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/cloud-consolidation-disabling-hybrid.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@dinocaputo  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@dinocaputo thank you for reaching out. Please have a look at this community article and let me know if it helps at all. https://techcommunity.microsoft.com/t5/upgrade-skype-for-business-to/decommissioning-the-on-premise-lync-server/m-p/1256884

**Comment by dinocaputo** [comment]
Have you read step1?   It says to do a get-csuser | disable-csuser which is what the article says NOT to do.

**Comment by scanum** [comment]
@dinocaputo Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
