### ISSUE TITLE
typo in powershell command

### ISSUE THREAD

**Issue by guillaumecouture** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#602]
Good morning, 

There seems to be a slight error in a powershell command listed in the article, as seen on the below screenshot : 

![image](https://user-images.githubusercontent.com/41156116/43406543-6e05b32a-93ea-11e8-96da-3f05f42fcf6a.png)

The command should read Set-CsOnlineDialInConferencingTenantSettings 

Typing the command without setting being plural results in the following error : 

![image](https://user-images.githubusercontent.com/41156116/43406640-b0e1a654-93ea-11e8-92ba-a65303e29c25.png)

Thank you ! 

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f93a7606-45b2-2032-c7b0-d79b07e65399
* Version Independent ID: 39c20b9e-713f-bf2b-9c41-3945d64d07b1
* Content: [Manage the Audio Conferencing settings for my organization](https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/manage-the-audio-conferencing-settings-for-my-organization)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/manage-the-audio-conferencing-settings-for-my-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/manage-the-audio-conferencing-settings-for-my-organization.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@guillaumecouture I have fixed the type for the scrip so that it runs properly. Thank you again for catching this.
