### ISSUE TITLE
Page should include information on connection to Teams PowerShell with MFA enabled

### ISSUE THREAD

**Issue by esparks-ipl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6021]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd283f6e-3865-ed70-d663-cc461ee8ba57
* Version Independent ID: 2450d311-fc04-d8b6-b4a2-b1890ec6fc3e
* Content: [Install Microsoft Teams PowerShell - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-install)
* Content Source: [Teams/teams-powershell-install.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-install.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
@esparks-ipl  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@esparks-ipl thank you for reaching out and helping improve MS Docs.  It behaves the same way as Skype for Business Online Connector stand alone without Teams PowerShell. In the example below, when no credentials are entered you will be prompted which supports MFA authentication.
$session = New-CsOnlineSession

Please let me know if you need further assistance.

**Comment by scanum** [comment]
@esparks-ipl  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
