### ISSUE TITLE
Add in information about eDiscovery and users with online only (shard) mailboxes

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6025]
A section should be added about how eDiscovery works when you have users still on Exchange on prem/ hybrid and their mail boxes are still on premise. There chats are not retained. Unless you ask Microsoft to switch the feature on to keep compliance records in an online (shard) mailbox.

Another section should be added about how eDiscovery works when you have chats with external users such as guests and external federated users. Their data is captured in the online (shard) mailbox

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 840dd36b-8c29-9738-4adc-ea9a7d277fd0
* Version Independent ID: b12c43c3-ed81-ace5-dfeb-77cac0f97fe9
* Content: [Conduct an eDiscovery investigation of content - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/ediscovery-investigation)
* Content Source: [Teams/eDiscovery-investigation.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/eDiscovery-investigation.md)
* Service: **msteams**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@nikki-c Thanks for feedback. eDiscovery of chat messages for on-premises users in a hybrid deployment is discussed in this topic: https://docs.microsoft.com/en-us/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users?view=o365-worldwide

I'll look into adding a link to this topic from the Microsoft Teams eDiscovery topic.
