### ISSUE TITLE
Insert Quality of Service (QoS) markers for real-time media traffic

### ISSUE THREAD

**Issue by moj02090** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6026]
Hello, 

I am confused about your Teams QoS Documentation:

The first thing written in the article is:
If you enable QoS or change settings in the Microsoft Teams admin center for the Teams service, you'll also need to apply matching settings to all user devices and all internal network devices to fully implement the changes to QoS in Teams.

With a link to a tutorial that describes how to set DSCP values via GPO.

But further down it is written:
To allow DSCP markings to be used for QoS, turn on Insert Quality of Service (QoS) markers for real-time media traffic. You only have the option of using markers or not; you can't set custom markers for each traffic type. See Select a QoS implementation method for more on DSCP markers.

What does the option "Insert QoS marks (Quality of Service) for real-time media traffic" do if you still have to distribute the DSCP values to the clients via GPO?

I have found in the Internet in some forums questioning users who also do not understand what this option is good for and it would be nice if you could create clarity here.

Thanks in advance.

Moritz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Manage meeting settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@moj02090 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by sasikaperera** [comment]
I dont think this transpired to have updated the document accurately and is still a grey area for many including me. 

We raised a ticket with support and they suggested that its either the Teams setting or the GPO update. If you enable the QoS Teams setting then you cannot go granular and specify the DSCP values (but just the port numbers), on the other hand, if GPO is updated, then you could specify the DSCP values to set as well, when traffic is leaving the client. Great if you could update the doc to reflect the accurate meaning of this setting. Thank  you !
![Untitled](https://user-images.githubusercontent.com/115146507/194272008-aafae0b7-5e9d-4d8e-83c0-0cdcf215c880.png)
