### ISSUE TITLE
Page mentions "Skype meeting room devices" in the 2nd sentence

### ISSUE THREAD

**Issue by arifC** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6029]
"You can configure Azure Monitor to provide basic telemetry to help you manage **Skype meeting room devices.**"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3de2dce0-681a-8237-62d5-bd45b00e47c0
* Version Independent ID: 3d1cafce-6c64-452c-e596-ff5ee4d39bde
* Content: [Manage Microsoft Teams Rooms devices with Azure Monitor - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/azure-monitor-manage)
* Content Source: [Teams/rooms/azure-monitor-manage.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/azure-monitor-manage.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@arifC  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@arifC Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
