### ISSUE TITLE
Confusing licensing around Phone System and Calling Plans

### ISSUE THREAD

**Issue by semenko** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#603]
This page says "Phone System and Calling Plans can be purchased with Skype for Business Online Plan 2 to enable voice calling features," but others suggest that Phone System & Calling plan can *not* be added to Office 365 / Microsoft 365 Business plans (and instead require enterprise plans). Can you please clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 390e7a34-ce99-5641-3007-9ab2afd3b2b8
* Version Independent ID: 5e2a796d-6377-a40b-7dbe-c75d40f73ab1
* Content: [Office 365 Premium, Office 365 ProPlus, or Skype for Business Online Plan 2](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/office-365-premium-pro-plus-or-business-online-plan#feedback)
* Content Source: [Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/office-365-premium-pro-plus-or-business-online-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/office-365-premium-pro-plus-or-business-online-plan.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@semenko - Thank you for submitting this feedback.

This is a good catch on how to make the article clearer and what needs adjustment so this article and the other article you reference don't cause confusion.

I was able to get this into the backlog for the Skype team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @semenko , it was updated. If you have Skype for Business Online Standalone Plan 2 you should move to different business plan. You can move to E3 and use add-ons but your best option would be move to E5.

Thank you for your feedback!
