### ISSUE TITLE
Where can i find new version of Microsoft Teams room?

### ISSUE THREAD

**Issue by tness** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6031]
It says in the article that the new version of Microsoft Teams room is pushed out to Microsoft Store, where can i find them, Windows IoT dont have microsoft store included

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1365f9b8-001c-daa7-592e-d88b9bb3a10e
* Version Independent ID: ffba1b4d-1f19-4dac-0b55-053d98fe26b7
* Content: [Release notes - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-release-note)
* Content Source: [Teams/rooms/rooms-release-note.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-release-note.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@tness Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
