### ISSUE TITLE
Need examples of user extension formatting

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6032]
Its not clear from the document what the formating for extensions should be. An example would be useful. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a42f9e2c-aeee-76c4-620a-668cce21ba10
* Version Independent ID: 6ff06eab-9c80-9c30-95ef-c17e157fbea1
* Content: [Set up an auto attendant for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-auto-attendant)
* Content Source: [Teams/create-a-phone-system-auto-attendant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-auto-attendant.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@StuBeck32  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@StuBeck32 thank you for reaching out. Please have a look at these article and let me know if they help at all - https://docs.microsoft.com/microsoftteams/plan-auto-attendant-call-queue and https://docs.microsoft.com/microsoftteams/business-voice/set-up-auto-attendants

**Comment by StuBeck32** [comment]
They do not. I am asking about an example of what an extension looks like when setup in a user account on active directory on prem or azure ad.

Stuart
________________________________

**Comment by lindspea** [comment]
@StuBeck32 I found another link here with a few examples in between. Please let me know if it helps at all - https://techcommunity.microsoft.com/t5/microsoft-teams/extension-calling/m-p/170960

**Comment by StuBeck32** [comment]
It doesn't as I believe its using cloud users. All I'm looking for is an example the Microsoft official documentation on how to set this up, if this isn't the right area to ask for that please let me know.
________________________________

**Comment by lindspea** [comment]
> It doesn't as I believe its using cloud users. All I'm looking for is an example the Microsoft official documentation on how to set this up, if this isn't the right area to ask for that please let me know.
> […](#)
> ________________________________ From: Lindsay <notifications@github.com> Sent: Tuesday, October 27, 2020 5:56 AM To: MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com> Cc: StuBeck32 <stuartbecktell@outlook.com>; Mention <mention@noreply.github.com> Subject: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Need examples of user extension formatting (#6032) @StuBeck32<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FStuBeck32&data=04%7C01%7C%7C11cf11a438904bc5f71b08d87a5e929e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637393893882295516%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vXoSF5EkS%2BatBpwtORdkIkENuV3dPhDn2mPiuNmgdTk%3D&reserved=0> I found another link here with a few examples in between. Please let me know if it helps at all - https://techcommunity.microsoft.com/t5/microsoft-teams/extension-calling/m-p/170960<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftechcommunity.microsoft.com%2Ft5%2Fmicrosoft-teams%2Fextension-calling%2Fm-p%2F170960&data=04%7C01%7C%7C11cf11a438904bc5f71b08d87a5e929e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637393893882305512%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ptuj15pgsYwLZ4IQ3c%2B%2BHMNj30Jm7WZoA90pXAXLrCM%3D&reserved=0> — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SkypeForBusiness%2Fissues%2F6032%23issuecomment-717124226&data=04%7C01%7C%7C11cf11a438904bc5f71b08d87a5e929e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637393893882305512%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=n5I%2BtalobEKeoELFjsyOGTpWTZSuM4ICBIto46ko36U%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAK5FPN42UP2VLTBOFFU7AOLSM2KMXANCNFSM4S3HVMFA&data=04%7C01%7C%7C11cf11a438904bc5f71b08d87a5e929e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637393893882315512%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vYrTrfKaaBbjXtQ%2BTUQ8SXkC4UWv%2Be8DDHLRytMrgnE%3D&reserved=0>.

@StuBeck32 I'm checking with the team and hopefully I'll have an answer for you soonest.

**Comment by lindspea** [comment]
@StuBeck32 I spoke to the team and they sent two more links - https://docs.microsoft.com/microsoftteams/tutorial-org-aa and https://docs.microsoft.com/microsoftteams/create-a-phone-system-auto-attendant. Please let me know ,but if these don't help I suggest you open a support ticket perhaps.

**Comment by StuBeck32** [comment]
The first one isn't relevant as its referring to dial by name. The second one has the same poor example which doesn't show what the extension dialing should look like. 

I can create a ticket to get this answered and update when I get an answer, but would this thread then be used to update the main document? I'm trying to help with your documentation for your product. If that won't happen, then I'll stop creating threads trying to help with the documentation.

**Comment by lindspea** [comment]
@StuBeck32 apologies for the delay and inconvenience. Sometimes it take a bit longer to research the issues.  Your help in improving the documentation is very much appreciated. Thanks again. I'll continue to investigate some more to find the correct information, but if you manage to get the answer in the meantime please let me know and I'll update this article accordingly with this thread.

**Comment by scanum** [comment]
@StuBeck32 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
