### ISSUE TITLE
Path doesn't exist

### ISSUE THREAD

**Issue by sysadmin-scs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6033]
You can monitor the usage against dial-out minute pool in the Skype for Business Admin Center. In the Microsoft Teams & Skype Admin Center, go to Legacy portal > Reports > PSTN Minute Pools. This complimentary minute pool will be labeled in the report as "Outbound Calls to Zone A countries and regions."

There is no "Reports" section in the legacy portal of my tenant. How can I find this information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be7b92a3-be5b-fd38-fb9e-7811212386fa
* Version Independent ID: da10315a-a190-4433-1e82-d22aef8ef1a0
* Content: [Complimentary dial-out period - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/complimentary-dial-out-period)
* Content Source: [Teams/complimentary-dial-out-period.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/complimentary-dial-out-period.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@sysadmin-scs Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Bmumpower2929** [comment]
Still an issue, path does not exist. And the reports under the new path is inaccurate(doesn't show pooled)
