### ISSUE TITLE
Please fix references to Call Analytics, no one knows what this is.

### ISSUE THREAD

**Issue by lukecarroll** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6035]
Please update the documentation to indicate what Call Analytics refers to - the Call history shown under Users in Teams Admin Center.

Also need to find a better place in the documentation tree for this. Call routing has nothing to do with this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f8119c9-61af-b469-af98-ddd37764c0ca
* Version Independent ID: 7d829a74-9df7-5b6f-8e1c-44d3e5d38f75
* Content: [Add and update reporting labels - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/learn-more-about-site-upload)
* Content Source: [Teams/learn-more-about-site-upload.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/learn-more-about-site-upload.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@lukecarroll  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@lukecarroll thank you for reaching out. Are you suggesting adding a note to the article to clarify what call analytics is? I found that call analytics refers to detailed information about devices, networks, and connectivity related to specific calls and meetings for each user in Teams. Teams admin and helpdesk agents will use this information to troubleshoot call quality and connection problems in a specific call. If you have any suggestions please let me know as well. Thanks.

**Comment by lukecarroll** [comment]
@lindspea I raised this issue because a customer couldn't figure out where reporting labels were used in Teams Admin Center.

I think the sentence `This file is used by Call Analytics for generating reports` needs to be expanded to indicate where the reporting labels show up. I provided this example of a screenshot:
![image](https://user-images.githubusercontent.com/3445900/97636307-2ba7d280-19f6-11eb-840b-c774432de8ff.png)

[Set up call analytics](https://docs.microsoft.com/en-us/microsoftteams/set-up-call-analytics) is linked at the bottom, is has an outdated section ([Upload a .tsv or .csv file to add building, site, and tenant information](https://docs.microsoft.com/en-us/microsoftteams/set-up-call-analytics#upload-a-tsv-or-csv-file-to-add-building-site-and-tenant-information)) which should be replaced with a link to this Reporting Labels document. 

Maybe adding a link to [Use call analytics to troubleshoot poor call quality](https://docs.microsoft.com/en-us/microsoftteams/use-call-analytics-to-troubleshoot-poor-call-quality) would help clear up what Call Analytics is too.

As far as placing this document in the document tree, this looks like a more relevant location:
![image](https://user-images.githubusercontent.com/3445900/97635405-8d673d00-19f4-11eb-810f-3c3e7b2e2283.png)

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
