### ISSUE TITLE
Why "disable private meetings if organizer has Exch on-prem"?

### ISSUE THREAD

**Issue by dsayer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6036]
Regarding this bullet:
"If your organization has compliance requirements to ensure all meeting discussions are discoverable, you should disable private meetings if the organizer has an Exchange on-premises mailbox. For more information, see Allow scheduling private meetings."

The availability of the cloud-based "shadow" mailboxes for on-prem EX users (described in the bullet below the one cited) says that all chat messages **_can_** be discoverable.  So what is the discoverability limitation, specifically for Teams meetings organized by an EX on-prem user?  Might guest / anonymous chat not be captured?  Or maybe when the EX on-prem user does not have an Exch Online Plan 1 license?

Clarification of the warning/bullet would be appreciated.  Especially since "private meetings" are really the default, customary meeting experience, not Teams/channel-based meetings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@dsayer Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
