### ISSUE TITLE
Command to install public preview version doesn't work

### ISSUE THREAD

**Issue by lrandall-gillsch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6040]
Hi,

Just tried to run the command to install the Teams public preview module and get the following error regarding the -RequiredVersion parameter.

Install-Module : Cannot process argument transformation on parameter 'RequiredVersion'. Cannot convert value "1.1.3-preview" to type "System.Version". Error: "Input string was not in a 
correct format."
At line:1 char:65
+ ... rosoftTeams -AllowPrerelease -RequiredVersion '1.1.3-preview' -Proxy  ...
+                                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Install-Module], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Install-Module

This is the full command I'm trying to run: 
Install-Module MicrosoftTeams -AllowPrerelease -RequiredVersion 1.1.3-preview -Proxy http://notarealproxy.com:8080 -ProxyCredential $(Get-Credential)

If I omit the -Proxy and -ProxyCredential parameters or change the -RequiredVersion parameter then it makes no difference I'm afraid and still fails with the above error :-(

I've even gone to the PSGallery page and copied the command there too and it still brings up the same message, happens in ISE and a normal PowerShell window.

How can we rectify this as I can't seem to use the Install-Module to install required versions?

Many thanks and take care,

Luke

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd283f6e-3865-ed70-d663-cc461ee8ba57
* Version Independent ID: 2450d311-fc04-d8b6-b4a2-b1890ec6fc3e
* Content: [Install Microsoft Teams PowerShell - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install)
* Content Source: [Teams/teams-powershell-install.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-install.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
@lrandall-gillsch Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
