### ISSUE TITLE
I'am missing information that was already on this docs article

### ISSUE THREAD

**Issue by paul-lange** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6041]
What happened to this article? I'm missing a lot of information here that was already there (e.g. options for timeout routing?)

According to the github-history, it was Mike Plumley who deleted a lot of content from this site. Is this by mistake?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b755d9ae-13ac-019f-f5f4-a95b1eee2989
* Version Independent ID: f7afd8ad-e6e0-6c79-aed1-4ee87d48ba12
* Content: [Create a call queue - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue)
* Content Source: [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-call-queue.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@paul-lange, the article had a lot of repetition which made it longer and more complicated than necessary. Call routing options were moved to [the planning article](https://docs.microsoft.com/microsoftteams/plan-auto-attendant-call-queue). I can add a direct link to that section for clarity.

**Comment by paul-lange** [comment]
@MikePlumleyMSFT thanks for the feedback. A reference would be helpful. At the end the information I was looking for (Transfer external for a Call Queue) is distributed in two articles (Planning and AA) and the last piece is found in "External phone number transfers - technical details" which is located "setup AA" But it can't be in "setup CQ"?

**Comment by scanum** [comment]
@paul-lange Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
