### ISSUE TITLE
How far the chats are delivered when translating?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6042]
Hi there,

On this page you do not describe how the translate is handled. E.g. if we are in EU and want to keep our data in EU only. Does this means that out chats are translated within EU?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19e91f77-0c01-5d38-0bd4-65ee44aab5cb
* Version Independent ID: 08ea83b3-c241-979c-3afb-3355ab322489
* Content: [Turn on inline message translation - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/inline-message-translation-teams)
* Content Source: [Teams/inline-message-translation-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/inline-message-translation-teams.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Petri-X** [comment]
Again it is odd, that I need to open support case and paid on that to get Microsoft's own documentation improved. I still believe you have all available connections to get this clarified better. But looks like I need to continue my investigation :)
