### ISSUE TITLE
Creating private channels not supported?

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6043]
With Business Standard and Teams Exploratory licenses applied, users are not able to create private meetings. This article should say that somewhere.

Why would the Exploratory license disable features that should be enabled due to the Business Standard license. Seems broken to me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-exploratory)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@jonwbstr Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jonwbstr** [comment]
I have no desire to look at this further. We removed the exploratory license and resolved the issue. if you choose to leave the documentation confusing in this area maybe people will look at the issue tracker and see this post. The exploratory license and the full license can exist for the same user and the admin interface does a terrible job of indicating which license the teams feature is being applied from, or indicate that the features for "Teams" is different depending on which license the feature is enabled by.
