### ISSUE TITLE
Information on Patient data.

### ISSUE THREAD

**Issue by Dusted1969** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6045]
This app was removed from our tenancy with no access method provided to the underlying data - exactly how are we supposed to get that this important patient information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c44662c-1a84-5ebb-d36d-24881e99cd4d
* Version Independent ID: 26cea960-25e4-65a5-1e0f-afe076c26ad6
* Content: [Patients app for Teams admins  - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/expand-teams-across-your-org/healthcare/patients-app-overview)
* Content Source: [Teams/expand-teams-across-your-org/healthcare/patients-app-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/expand-teams-across-your-org/healthcare/patients-app-overview.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@Dusted1969 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
