### ISSUE TITLE
Can you create and manage tags via PowerShell

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6048]
Please an you specify in the document whether you can create, update and delete tags via PowerShell or whether it has to be managed via the Teams admin centre

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b16e659e-cf07-268a-e224-fa444749ac29
* Version Independent ID: ee822a8d-b331-998f-e336-b1fa510f35c0
* Content: [Manage tags in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-tags)
* Content Source: [Teams/manage-tags.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-tags.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@nikki-c  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@nikki-c thank you for reaching out. Please have a look at this link and let me know if it helps - https://docs.microsoft.com/MicrosoftTeams/teams-powershell-overview%20

**Comment by nikki-c** [comment]
Lindsay. The links adds no value it point to the PowerShell home page.

I am trying to find which is cmdlet can asset up the organisation wide tags. I can add Tags direct in the Teams Admin Centre but can find no reference to it in PowerShell. I had looked through all New-csTeams… cmdlets and can’t seem to find any mention of tags. If you cant manage  tags for your organisation via PowerShell it should be stated on the page. If you can manage via PowerShell the page to link to the correct PowerShell page

Nikki Chapple
Organisational Change Manager
United Kingdom | Cloud Communications
NTT

T:
+442080800656
M:
+447500766185
E:
n.chapple@arkadin.com<mailto:n.chapple@arkadin.com>

NTT Cloud Communications UK Ltd. is an entity of NTT Ltd.

[cid:image001.jpg@01D6AB9C.79BBB180]<https://arkadin.com/> [cid:image003.jpg@01D6AB9C.79BBB180] <https://twitter.com/arkadinservices#xd_co_f=MDgwMzM4NzQtY2Y5Mi00YTEyLWIxMGQtODQwNWIxMzhiZDgz~>  [cid:image005.jpg@01D6AB9C.79BBB180] <https://www.linkedin.com/company/arkadin/>  [cid:image007.jpg@01D6AB9C.79BBB180] <https://www.facebook.com/ArkadinCloudComm>  [cid:image009.jpg@01D6AB9C.79BBB180] <https://www.instagram.com/globalntt/>  [cid:image011.jpg@01D6AB9C.79BBB180] <https://www.youtube.com/user/ArkadinConference>
[cid:image013.jpg@01D6AB9C.79BBB180]<http://www.arkadin.com/>

**Comment by lindspea** [comment]
Hi @nikki-c I have researched a bit more and it doesn't seem to be available yet. Please see the list of cmdlets here - https://docs.microsoft.com/powershell/teams/ Please also see Uservoice to add your voice/vote - https://microsoftteams.uservoice.com/forums/555103-public/suggestions/41561500-create-and-assign-tags-using-powershell

**Comment by nikki-c** [comment]
Lindsay Please can you add a note on the page in the section about tags to state that they cannot be managed via PowerShell. It will save ither people time going though all the PowerShell commands trying to find something that is not there.
Thanks
Nikki

Nikki Chapple
Organisational Change Manager
United Kingdom | Cloud Communications
NTT

T:
+442080800656
M:
+447500766185
E:
n.chapple@arkadin.com<mailto:n.chapple@arkadin.com>

NTT Cloud Communications UK Ltd. is an entity of NTT Ltd.

[cid:image001.jpg@01D6ADD8.9C4224D0]<https://arkadin.com/> [cid:image002.jpg@01D6ADD8.9C4224D0] <https://twitter.com/arkadinservices#xd_co_f=MDgwMzM4NzQtY2Y5Mi00YTEyLWIxMGQtODQwNWIxMzhiZDgz~>  [cid:image003.jpg@01D6ADD8.9C4224D0] <https://www.linkedin.com/company/arkadin/>  [cid:image004.jpg@01D6ADD8.9C4224D0] <https://www.facebook.com/ArkadinCloudComm>  [cid:image005.jpg@01D6ADD8.9C4224D0] <https://www.instagram.com/globalntt/>  [cid:image006.jpg@01D6ADD8.9C4224D0] <https://www.youtube.com/user/ArkadinConference>
[cid:image007.jpg@01D6ADD8.9C4224D0]<http://www.arkadin.com/>

**Comment by lindspea** [comment]
> Lindsay Please can you add a note on the page in the section about tags to state that they cannot be managed via PowerShell. It will save ither people time going though all the PowerShell commands trying to find something that is not there. Thanks Nikki Nikki Chapple Organisational Change Manager United Kingdom | Cloud Communications NTT T: +442080800656 M: +447500766185 E: n.chapple@arkadin.com<mailto:n.chapple@arkadin.com> NTT Cloud Communications UK Ltd. is an entity of NTT Ltd. [cid:image001.jpg@01D6ADD8.9C4224D0]<https://arkadin.com/> [cid:image002.jpg@01D6ADD8.9C4224D0] <https://twitter.com/arkadinservices#xd_co_f=MDgwMzM4NzQtY2Y5Mi00YTEyLWIxMGQtODQwNWIxMzhiZDgz~> [cid:image003.jpg@01D6ADD8.9C4224D0] <https://www.linkedin.com/company/arkadin/> [cid:image004.jpg@01D6ADD8.9C4224D0] <https://www.facebook.com/ArkadinCloudComm> [cid:image005.jpg@01D6ADD8.9C4224D0] <https://www.instagram.com/globalntt/> [cid:image006.jpg@01D6ADD8.9C4224D0] <https://www.youtube.com/user/ArkadinConference> [cid:image007.jpg@01D6ADD8.9C4224D0]<http://www.arkadin.com/> From: Lindsay <notifications@github.com> Sent: 29 October 2020 07:29 To: MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com> Cc: Nikki Chapple <n.chapple@arkadin.com>; Mention <mention@noreply.github.com> Subject: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Can you create and manage tags via PowerShell (#6048) Hi @nikki-c<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_nikki-2Dc&d=DwMCaQ&c=aj9Ha5yMZahcf_BRtDCWCQ&r=4X2LVoiHgkiOrp6R0STYhhu-lNwIEFUDxBQBmnoeGu4&m=5JPW34_SqcrmI03eX8o93UF915OOSODBymhOjQUX-jg&s=o7GQlEI6ORShY7w_1TdBjrx6SmIZIUIJw-ha-2LrkzQ&e=> I have researched a bit more and it doesn't seem to be available yet. Please see the list of cmdlets here - https://docs.microsoft.com/powershell/teams/<https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.microsoft.com_powershell_teams_&d=DwMCaQ&c=aj9Ha5yMZahcf_BRtDCWCQ&r=4X2LVoiHgkiOrp6R0STYhhu-lNwIEFUDxBQBmnoeGu4&m=5JPW34_SqcrmI03eX8o93UF915OOSODBymhOjQUX-jg&s=1LYY6_kg2BL_TgpJyx2sC6onuwESg8GFUX2uLQOpgXI&e=> Please also see Uservoice to add your voice/vote - https://microsoftteams.uservoice.com/forums/555103-public/suggestions/41561500-create-and-assign-tags-using-powershell<https://urldefense.proofpoint.com/v2/url?u=https-3A__microsoftteams.uservoice.com_forums_555103-2Dpublic_suggestions_41561500-2Dcreate-2Dand-2Dassign-2Dtags-2Dusing-2Dpowershell&d=DwMCaQ&c=aj9Ha5yMZahcf_BRtDCWCQ&r=4X2LVoiHgkiOrp6R0STYhhu-lNwIEFUDxBQBmnoeGu4&m=5JPW34_SqcrmI03eX8o93UF915OOSODBymhOjQUX-jg&s=0WkJ0D3_S_RnCxChO-1jXJXASKL5jcYXWos2s8hTYWw&e=> — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_MicrosoftDocs_OfficeDocs-2DSkypeForBusiness_issues_6048-23issuecomment-2D718421218&d=DwMCaQ&c=aj9Ha5yMZahcf_BRtDCWCQ&r=4X2LVoiHgkiOrp6R0STYhhu-lNwIEFUDxBQBmnoeGu4&m=5JPW34_SqcrmI03eX8o93UF915OOSODBymhOjQUX-jg&s=V5d-DxlI8A9UqDsPoBTnxwgNtXTQ1_2nxk2LMzCER5Y&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AQRY4GVDJMG7SSIVRMP6RMTSNEKS3ANCNFSM4S45CFNQ&d=DwMCaQ&c=aj9Ha5yMZahcf_BRtDCWCQ&r=4X2LVoiHgkiOrp6R0STYhhu-lNwIEFUDxBQBmnoeGu4&m=5JPW34_SqcrmI03eX8o93UF915OOSODBymhOjQUX-jg&s=nINcKKsMo_YV1F3JF2_BttsD65jr9W1H5Rd90Rx6Xgw&e=>.

Thanks @nikki-c I have done a PR to add this note. It should reflect in a few days. Thanks again for your help.

**Comment by LanaChin** [comment]
@nikki-c, thanks for your feedback. We've updated the article to reflect that currently, you can't use PowerShell to manage tags.
