### ISSUE TITLE
Remove Desktop-Experience

### ISSUE THREAD

**Issue by martinboam** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#605]
Remove Desktop-Experience from PowerShell for Add-WindowsFeature for SfB Server 2019 prereq's as this doesn't work for Windows Server 2016 for SfB Server 2019.
Or is this trying to be used for both SfB Server 2015 and 2019 ? If so need to mention that desktop-experience isnt needed for Windows Server 2016 and SfB Server 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd40e9bf-6fb5-b597-5494-b9ccc17e4660
* Version Independent ID: 46d0d0a0-2ea9-efbd-1ef8-63686f7fef62
* Content: [System requirements for Skype for Business Server 2019](https://docs.microsoft.com/en-us/skypeforbusiness/plan/system-requirements)
* Content Source: [Skype/SfBServer2019/plan/system-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/plan/system-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by kenwith** [comment]
This is being tracked here too: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/601

@martinboam - I have added this to backlog. Thank you for testing the 2019 docs in this preview period! Much appreciated!

**Comment by dariomws306** [comment]
@martinboam it was removed.
