### ISSUE TITLE
Meeting policy settings - Video filters mode

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6054]
Under the 'Meeting policy settings - Video filters mode is applied' mention that not all platforms support video filters and refer to 
Teams Feature by Platform page for meetings and Live events https://support.microsoft.com/en-us/office/meetings-and-live-events-5c3e0646-dc37-45ad-84a4-1666fac62d4e?ui=en-US&rs=en-US&ad=US

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@nikki-c  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @nikki-c, thank you for your feedback and help us to improve docs.microsoft.com.

Sorry, but I cannot see the sentence you are referring:
![image](https://user-images.githubusercontent.com/33589238/97726917-84d33d00-1aae-11eb-866b-b39534691369.png)

Could you kindly provide more detail? Thanks!

**Comment by nikki-c** [comment]
Underneath the section you have sent me I would like to add a New note to state that not all video filters are available in all platforms. The link to Teams Feature by Platform page for meetings and Live events https://support.microsoft.com/en-us/office/meetings-and-live-events-5c3e0646-dc37-45ad-84a4-1666fac62d4e?ui=en-US&rs=en-US&ad=US for more details

**Comment by dariomws** [comment]
@nikki-c understand now, thank you! I'm applying your suggestion.
