### ISSUE TITLE
Private Channel Meeting caveats

### ISSUE THREAD

**Issue by felizondojr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6055]
To save users some headaches the docs should mention the caveats to Private channels. For instance, you cannot create meetings directly in Private channels. Instead, you need to create the meeting directly from the General channel and select the Private channel.

Another caveat is turning a Private channel Public. Once it is public, it apparently cannot be converted back to Private. I haven't found this anywhere in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92fcb1f6-5cc2-f6bd-cfa9-11d811f1dbf1
* Version Independent ID: 9a571e6d-8cb3-9ff8-a5c2-62deab146264
* Content: [Admin quick start - Meetings and live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/quick-start-meetings-live-events)
* Content Source: [Teams/quick-start-meetings-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/quick-start-meetings-live-events.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@felizondojr  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @felizondojr, thank you for your feedback and help us to improve docs.microsoft.com.

I've verified, and I can see the option to create meetings from a private channel:
![image](https://user-images.githubusercontent.com/33589238/97759484-eb248380-1adf-11eb-9ab6-7e169efa3368.png)

I think the ability to convert channels between private and public is not yet available, but the product group is working on it:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/38974249-make-public-channel-private
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/38535709-convert-private-channel-to-public-channel
You can also vote for this feature.

**Comment by scanum** [comment]
@felizondojr  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
