### ISSUE TITLE
 CreateSrsMedia.ps1 script link fails

### ISSUE THREAD

**Issue by kevincallanan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6056]
The link for the CreateSrsMedia.ps1 link is currently broken.

Can be corrected/updated? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/console#Prep_Media)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@kevincallanan  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @kevincallanan, thank you for your feedback.

I tried 1 minute ago, and it worked for me. Could you kindly try again?

**Comment by kevincallanan** [comment]
This is working now, the link now downloads the version 1.6.0 Thanks!

**Comment by nathanhamblin** [comment]
Trying to download the script is giving:
404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

**Comment by JamesGutherson** [comment]
Still getting 404 error today.

**Comment by dariomws** [comment]
@dstrome could you kindly help here? Thanks!

**Comment by maxpeet** [comment]
Came here to report on the link and the script itself getting http 404 errors, however just now I've tested both and they are working.
Thanks for you and your teams' work on this

**Comment by dariomws** [comment]
@maxpeet thanks!

**Comment by cubspsycho85** [comment]
Same issues again, getting a 404 when trying to access the link to the script from the MS documentation...any help @dariomws

**Comment by NotepadExpert** [comment]
This is still an issue. How is it possible that you can't successfully and permanently host one powershell script?

**Comment by dariomws** [comment]
@dstrome could you kindly help here? Thanks!

**Comment by dstrome** [comment]
The script should be available again. I apologize for the inconvenience. Unfortunately, when the script is updated, there's an interval where it's unavailable as the backend system goes through various compliance, security, and other checks.
