### ISSUE TITLE
Dial by Extension Documentation Issue

### ISSUE THREAD

**Issue by PMcGown** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6057]
For configuring Dial by Extension, the documentation says must be "+ext=", but in reality it is a semicolon so it should be ";ext=".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a42f9e2c-aeee-76c4-620a-668cce21ba10
* Version Independent ID: 6ff06eab-9c80-9c30-95ef-c17e157fbea1
* Content: [Set up an auto attendant for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-auto-attendant)
* Content Source: [Teams/create-a-phone-system-auto-attendant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-auto-attendant.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@PMcGown  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
