### ISSUE TITLE
link is broken 

### ISSUE THREAD

**Issue by Strick1969** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6058]
link is broken to script

https://go.microsoft.com/fwlink/?linkid=870105

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 834f564b-d32a-25ba-437b-1cb74adbf485
* Version Independent ID: 9bdb6864-caa0-d0fa-ce06-eaaa1fd18fe3
* Content: [Configure accounts for Microsoft Teams Rooms - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-configure-accounts)
* Content Source: [Teams/rooms/rooms-configure-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-configure-accounts.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Strick1969  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
@Strick1969 thank you for your feedback.

I think it's working now, could you kindly try again?

**Comment by scanum** [comment]
@Strick1969  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
