### ISSUE TITLE
Presence in Teams

### ISSUE THREAD

**Issue by lalles67** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6063]
[Enter feedback here]
Dear Team,

I think we are missing some information about the Busy status. For example in the text below, where do the Busy status fit?

App-configured presence states are based on user activity (Available, Away), Outlook calendar states (In a meeting), or Teams app states (In a call, Presenting). When you're in focus mode based on your calendar, Focusing will be the state people see in Teams. Focus mode will display as Do not disturb in other products.

Also, there are no information about what triggers the Busy state when we let the App configured settings apply.

There are a not of open discussion out there on forums regarding the Busy state and how it's actually App managed.

Some additional inputs would be useful

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a162ef5c-3099-7f58-4178-d29e3ec2b5a7
* Version Independent ID: 6ca31e56-052d-6c62-1323-b5aaaae1f04a
* Content: [User presence in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/presence-admins#feedback)
* Content Source: [Teams/presence-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/presence-admins.md)
* Service: **msteams**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@lalles67  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @lalles67, thank you for your feedback.

Based on the information in this article I think we can understand that when you have a meeting in the Outlook calendar, and you take a call or do a presentation in the Teams app your presence will be updated to Busy.
These are the action that triggers the Busy state.

If I misunderstand you, please provide more detail. Thank you again!

**Comment by scanum** [comment]
@lalles67  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
