### ISSUE TITLE
Guest Inviter Role has already been shipped 

### ISSUE THREAD

**Issue by sabrinahota** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6064]
The guest inviter role is already available for Teams. The docs would need to be updated. 
Thanks and best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b05e642-c4e5-f1b5-5315-d3ef1690a0cd
* Version Independent ID: 01b7e0b5-3e50-3de0-e3e9-aeeeda43da12
* Content: [Authorize guest access in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-dependencies)
* Content Source: [Teams/Teams-dependencies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-dependencies.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@sabrinahota  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @sabrinahota, thank you for your feedback and help us to improve docs.microsoft.com.

This note was updated 1 year ago when the guest inviter role support was added.

Before:
```
> [!NOTE
> Currently, Teams doesn't support the guest inviter role. At a minimum, the **Members can invite** toggle must be set to **Yes** for guest access to work in Teams.
```

Now:
```
> [!IMPORTANT]
> Currently, Teams doesn't support the guest inviter role, so even if you set **Guests can invite** to **Yes**, guests can't invite other guests in Teams.
```

Could you as a guest invite another guest to a Team?

**Comment by dariomws** [comment]
@SharS maybe you can kindly confirm that guest inviter role is still not supported for guest users. Thanks!

**Comment by dariomws** [comment]
@sabrinahota guest inviter role is supported even for guests, you'll see the update in the article in a couple of days.

@scanum this issue can be closed.

**Comment by scanum** [comment]
@sabrinahota  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by sabrinahota** [comment]
Just wanted to quickly thank you for updating it!
