### ISSUE TITLE
Managing Quality of Service link broken

### ISSUE THREAD

**Issue by githubsteveb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6065]
Bottom link "Managing Quality of Service" is broken.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1203c89-f67c-c792-c0a5-aabfa7d80904
* Version Independent ID: 69c15041-6ad8-5eb0-f578-c657b29fda44
* Content: [Skype Room System domain joining considerations - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/domain-joining-considerations)
* Content Source: [Teams/rooms/domain-joining-considerations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/domain-joining-considerations.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@githubsteveb  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
