### ISSUE TITLE
Add note for CONF_IN and CONF_OUT call types

### ISSUE THREAD

**Issue by BSwagger** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6066]
[Enter feedback here]
It may be helpful to have a note for audio conferencing call types as CONF_IN and CONF_OUT call types show the display name and username of the person that organized the meeting, not the individual participant that performed the call in/out action.  This is not clear from current documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ad0c889-56d5-35fe-de15-177b6d922d07
* Version Independent ID: e4363647-33e1-b665-5881-169fb619a5b3
* Content: [Microsoft Teams PSTN usage report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/pstn-usage-report#calling-plans)
* Content Source: [Teams/teams-analytics-and-reports/pstn-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/pstn-usage-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
Thanks for the feedback! We will consider adding this in our future updates.
