### ISSUE TITLE
Live Events limits

### ISSUE THREAD

**Issue by Richard-Barr3tt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6067]
The section of this page which says about temporary live events limits increases needs changing as it is now out of date. 

All customers can now have these extend limits to 1st Jan 2021 as per - https://docs.microsoft.com/en-us/stream/live-event-m365

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09168b55-8244-974e-8bb3-6ec16429a650
* Version Independent ID: c17f4f8d-a8bb-3c81-368f-07b932f52ebc
* Content: [Advanced Communications add-on for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/advanced-communications)
* Content Source: [Teams/teams-add-on-licensing/advanced-communications.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/advanced-communications.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Richard-Barr3tt  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Richard-Barr3tt, thank you for your feedback and help us to improve docs.microsoft.com.

The following information was added 3 months ago to the article:
```
At release on August 1, 2020, the following features are available:

- Live events support for up to 20,000 participants, 50 concurrent events, event duration of 16 hours per broadcast
```

This article says that these limits were released on August 1, 2020, and the article you provide says that these limits are available until January 1, 2021.

**Comment by scanum** [comment]
@Richard-Barr3tt  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Richard-Barr3tt** [comment]
This does not look like it has been resolved to me. The page still shows the out of date information on live events limits

**Comment by dariomws** [comment]
Hi @Richard-Barr3tt, sorry but I don't understand your point.

This article says that these limits were released on August 1, 2020, I'm not sure how this could be outdated.

**Comment by Richard-Barr3tt** [comment]
Hi there, 

On the page  https://docs.microsoft.com/en-us/stream/live-event-m365 we show that our limits are increasing until 1st Jan 2021. 

However on this page in the note at the bottom section (https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/advanced-communications#difference-between-overflow-meetings-and-live-events) it says these limits are only raised until Oct 1st. This note needs changing to say 'until 1st Jan 2021'

thanks
