### ISSUE TITLE
Can we have a concise description of Teams limits?

### ISSUE THREAD

**Issue by ThomasSaintThomas** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6071]
This document is so confusing. Can we please have some concise, direct answers about Teams limits?
How many people can be on a video call? Is it 20 or 300?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@ThomasSaintThomas  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @ThomasSaintThomas, thank you for your feedback and help us to improve docs.microsoft.com.

I've updated the information, hope it's better to understand now:
![image](https://user-images.githubusercontent.com/33589238/97918307-b0ffef80-1d34-11eb-8322-2259161c970a.png)

It'll be live in some days.

**Comment by dariomws** [comment]
The difference is when you start a/v from a meeting or the chat app/tab.

**Comment by scanum** [comment]
@ThomasSaintThomas  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
