### ISSUE TITLE
Update links?

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6074]
"Known Isssues List" doesn't go to a known issues list. Rename the link to "Teams troubleshooting"?

Also, the "ThisIsTeams" link goes to the EventBuider site, but there are no future classes scheduled and the 'on demand' link doesn't actually have a recording of the session.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b8c056b-fea4-db8e-e965-ca120f8c9b7f
* Version Independent ID: d1e69c8b-5cfe-5fa7-3611-89d14e3e036a
* Content: [Onboard support for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-adoption-onboard-support)
* Content Source: [Teams/teams-adoption-onboard-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-adoption-onboard-support.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@npherson  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Thanks, @npherson as always for your feedback.

I removed "ThisIsTeams" link and updated the others. I'm missing the Ignite 2019 version of the "Troubleshooting Microsoft Teams" session. I know that Carolyn and Bryan presented the same session last year, but I cannot find it.
