### ISSUE TITLE
Files hard to get if signed into other MS services.

### ISSUE THREAD

**Issue by oddhair** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6079]
Files for Hub Teams provisioning are in a OneDrive library. I had to try every browser to get them to download, could they instead be a typical web download? This was prompting me to log in with whatever credentials I had a session under, which included Hotmail, my work domain, a (very large) client's domain on which I'm a guest, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f256cd5b-3ec8-2d55-9ae4-ff9849d52eae
* Version Independent ID: 52c2271b-df38-5dc9-c2a1-553cdf3b5496
* Content: [Deploy Microsoft Teams for Surface Hub - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-surface-hub)
* Content Source: [Teams/teams-surface-hub.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-surface-hub.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
