### ISSUE TITLE
Global admins can only create an org-wide team by using the Teams client

### ISSUE THREAD

**Issue by JAPainter** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6080]
This sentence: "Global admins can only create an org-wide team by using the Teams client" is buried near the bottom of the page.  In reality, I think it should be the very first sentence on the page.  As a Teams admin, I would assume I'm going to be doing admin tasks inside the admin console.  It seems that we are expected to infer based on the screenshot that this action must be done inside the Teams client but it would be really helpful if it was called out earlier in the document.  Also of note, it appears that if your organization locks down group creation, the admin account must be explicitly allowed group creation permissions for this to work, even though Global Admins have group creation permissions by default, they do not appear to apply inside the Teams client and must be explicitly granted. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@JAPainter  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@JAPainter thank you for pointing this out. I see it has been added at the top of the document.
