### ISSUE TITLE
Add details on how these features are enabled.  

### ISSUE THREAD

**Issue by dgordonb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6082]
Howdy,  
I'm an MS PM working on Microsoft Business Voice, the SMB focused version of Teams Calling.  
We have received feedback from customers via our proactive support program that they find the documentation on the Dial by Name feature but don't know how to turn it on.  

Please add details for where they go to configure this setting.  (Add/Edit Auto Attendant in the Call Flow section)
There are 8 articles that include "Dial by name".  I'd recommend updating those also. 

thanx, gord   dobro@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 016be911-545f-28e4-97d2-549f1078a196
* Version Independent ID: 9021aad0-83c0-1173-01ae-6cc68217e8d4
* Content: [Auto attendant and call queue dialing and voice recognition reference - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/dial-voice-reference)
* Content Source: [Teams/dial-voice-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/dial-voice-reference.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@dgordonb  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
Hi @dgordonb. Thank you for reaching out. I've just had a look at the article and I see it's been updated with quite a lot of information under 'dial by name'. Please have a look and let me know if you still need assistance.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
