### ISSUE TITLE
Needs the word "Active"

### ISSUE THREAD

**Issue by Michael-Sampson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6083]
[Enter feedback here]
The phrase in the opening line - "or the Azure Directory portal" - should say "or the Azure Active Directory portal"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 941e0612-7854-9538-405c-8a8794b4cc04
* Version Independent ID: 9460ce27-6f84-ac04-cdf4-176faa1bb4bb
* Content: [Edit guest user information - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/edit-guests-information)
* Content Source: [Teams/edit-guests-information.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/edit-guests-information.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@Michael-Sampson  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
