### ISSUE TITLE
Why is the inline translation blocked for teams guests ? 

### ISSUE THREAD

**Issue by m-hunsicker** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6084]
Hi, 

The page mentioned below indicates that guests of a Teams team do not have access to the translation of messsages. This is particularly damaging because I can't have my colleagues from foreign subsidiaries of my company to read messages that are not in their language. 

1. Could I please as you if there is a particular reason for this parameter choice ? 

2. Could I please ask you if there is any way to change this parameters ? 

Thank you very much
MH

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [Interface utilisateur pour les invités dans Microsoft teams - Microsoft Teams](https://docs.microsoft.com/fr-fr/microsoftteams/guest-experience)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
