### ISSUE TITLE
Multiple SIP/SMTP domains

### ISSUE THREAD

**Issue by rgsteele** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#609]
It's not clear what, if anything needs to be done if you have multiple primary SIP/SMTP domains on the same Exchange server. I'm guessing you have to repeat ~~Step 1~~, Step 3 (with a different account name), Step 4, and Step 7 for each domain, but it would be great to get confirmation.

Edit: Looking at this again, Step 1 wouldn't need to be repeated as the primary SIP domain for **cloud-based** accounts would be the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19d818da-830e-c813-08af-6192eb403ccc
* Version Independent ID: 575c0a11-f6e1-c571-4ad4-d490915faa15
* Content: [Configure OAuth between Skype for Business Online and Exchange on premises](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/integrate-with-exchange-server/oauth-with-online-and-on-premises)
* Content Source: [Skype/SfbServer/deploy/integrate-with-exchange-server/oauth-with-online-and-on-premises.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/integrate-with-exchange-server/oauth-with-online-and-on-premises.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by csando** [comment]
I would also like more into on this

**Comment by kenwith** [comment]
@rgsteele and @csando - Thank you for submitting this feedback.

This is a good catch with the steps and how the article flows.

I was able to get this into the backlog for the Skype team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by jambirk** [comment]
A Senior support person has verified that no further config is needed in this situation.
