### ISSUE TITLE
Channel Moderation

### ISSUE THREAD

**Issue by Richard-Barr3tt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6092]
The channel moderation screenshot is old and some of this functionality has now been removed from the service. We should update this really. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097ecd40-1157-98ae-f438-96f9208afc03
* Version Independent ID: ea36ff93-46dc-920d-8d52-9b3b81420958
* Content: [Set up and manage channel moderation - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-channel-moderation-in-teams)
* Content Source: [Teams/manage-channel-moderation-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-channel-moderation-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
Hi @Richard-Barr3tt We will consider adding this in a future update. Thanks!
