### ISSUE TITLE
Clarify units for time measures on Activity Report

### ISSUE THREAD

**Issue by schumatt-msft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6098]
Based on customer feedback, we should clarify the units used for these measures on the usage report:

- **Audio time** is the total audio time that the user participated in during the specified time period.
- **Video time** is the total video time that the user participated in during the specified time period.
- **Screen sharing** time is the total screen share time that the user participated in during the specified time period.

We specify that this is the "total time" but don't clarify whether this is in hours, minutes, or seconds.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2758a3d6-c646-dcb0-2a31-c7b9b84e780b
* Version Independent ID: 8704c9fe-f8b0-82d2-bd83-3fd1a9ad638d
* Content: [Microsoft Teams user activity report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report)
* Content Source: [Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@schumatt-msft Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@schumatt-msft thank you for reaching out and helping improve MS Docs. After some research I found that it is measured in minutes. Please let me know if you found it to be something else and I can add a note for clarity.

**Comment by schumatt-msft** [comment]
@lindspea Excellent, I think it would be helpful to include that. Can you make the edit or should I submit a PR with the edits?

**Comment by scanum** [comment]
@lindspea

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
