### ISSUE TITLE
Missing new phone system features

### ISSUE THREAD

**Issue by rdekramer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6102]
Hi,

I'm missing the new recently released phone system features: Safe transfer + Call Merge + P2P&PSTN call captioning.

Could we add these to the docs page?
Thanks,
Remco

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cfead3c-b0d8-c22a-aa22-63e79fe53ed3
* Version Independent ID: 10745875-3d3e-42bb-e324-ff4c83968ccf
* Content: [Here's what you get with Phone System - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/here-s-what-you-get-with-phone-system?source=docs)
* Content Source: [Teams/here-s-what-you-get-with-phone-system.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/here-s-what-you-get-with-phone-system.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@rdekramer Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by rdekramer** [comment]
Hi Manuela,

I think I could have phrased in a more clear way. The features work perfectly in our and customer tenants.

However this doc’s site doesn’t describe the features yet. Can the docs site text be updated? Partners frequently use this site to refer to customers what features are available in phone system.

Regards,

Remco de Kramer
Product Marketing Manager
Modern Work
Mobile +31625238483<callto:+31625238483>
Office   +31205001858<callto:+31205001858>
Contact me via Teams<sip:redekram@microsoft.com>
[See the source image]

Van: Manuela Scanu <notifications@github.com>
Verzonden: zaterdag 31 oktober 2020 01:49
Aan: MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com>
CC: Remco de Kramer <Remco.deKramer@microsoft.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Missing new phone system features (#6102)


@rdekramer<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frdekramer&data=04%7C01%7CRemco.deKramer%40microsoft.com%7C8f9b94b5e09146072a3708d87d36b76a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637397021252308650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BQI8U7ug2fiVXXvvdjaDqWBMa9YXQ4zeHdinQ4P%2BF4A%3D&reserved=0> Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Foffice365%2Fadmin%2Fcontact-support-for-business-products&data=04%7C01%7CRemco.deKramer%40microsoft.com%7C8f9b94b5e09146072a3708d87d36b76a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637397021252318600%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=D47Qd3%2BU5GUBx8eOm5we9mt4JL%2FsgTSHMLqxm%2F1jiZ8%3D&reserved=0>
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
