### ISSUE TITLE
WHICH IS IT!  - is Teams part of Skype for Business Online?  - is Skype for Business Online part of Teams PowerShell module?

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6103]
the page says...

The latest Teams PowerShell public release is integrated with Skype for Business Online Connector, providing a single module for Teams PowerShell management.

Skype for Business PowerShell Connector: The Skype for Business PowerShell connector is now a part of Teams PowerShell module.

WHICH IS IT!
 - is Teams part of Skype for Business Online?
 - is Skype for Business Online part of Teams PowerShell module?
 - do they _both_ have functionality across both Skype for Business _and_ Teams?

This is terribly ambiguous!

**Comment by scanum** [comment]
@anwarmahmood1 Thanks for the feedback, could you kindly link the document you are referring to? Thanks!

**Comment by scanum** [comment]
@anwarmahmood1 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
