### ISSUE TITLE
Incorrect/incomplete information on meeting expiry

### ISSUE THREAD

**Issue by thewrabbit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6104]
The section https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#meeting-expiration contains incomplete/incorrect information.  It states meetings 'expire' with no clarification on what this expiry means.

I've had it confirmed through support engagement that a meeting URL will never stop working.
That the expiry only relates to any PSTN dial in number and 'underlying meeting policies and settings' - I'm still awaiting clarification on what this means.

This section needs considerable clarification as it misleads users into thinking a meeting will stop working at some point, when it will not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#meeting-expiration)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@thewrabbit Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@thewrabbit thank you for reaching out and helping improve MS Docs. Do you think it will help add clarity for other users if I add a note stating - "A meeting URL will never stop working. The expiry only relates to any PSTN dial in number and underlying meeting policies and settings"? As far as I know the underlying policy and settings relates to any specific settings regarding meeting expiry when the meeting is originally set up. Let me know if this helps at all.

**Comment by thewrabbit** [comment]
Thanks Lindsay – I think that would help.  It clarifies that the meeting can still be used and what could possibly change in re-use eg the policies will apply afresh.

Nadine Killiard | Technical Product Manager | Education Scotland | Foghlam Alba
M: +44 (0)7920 088 115
Optima, 58 Robertson Street, Glasgow G2 8DU
An Optima, 58 Sràid Robastan, Glaschu, G2 8DU
www.education.gov.scot<http://www.education.gov.scot>

**Comment by lindspea** [comment]
@SerdarSoysal

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
