### ISSUE TITLE
Missing feature as described in the Teams admin portal

### ISSUE THREAD

**Issue by lynnroe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6106]
This feature is not shown in the TAC>
See:  https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams#meeting-policy-settings---meeting-attendance-report
++
Currently, you can only use PowerShell to configure this policy setting. You can edit an existing Teams meeting policy by using the Set-CsTeamsMeetingPolicy cmdlet. Or, create a new Teams meeting policy by using the New-CsTeamsMeetingPolicy cmdlet and assign it to users.
And we named the flag differently; so its not obvious to an admin in PS:
Allow**Engagement**Report

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a8b1087-ae40-6813-16bc-a69c90e50d19
* Version Independent ID: b808e843-80d8-4a96-c6ed-e8175968eb73
* Content: [Microsoft Teams meeting attendance report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/meeting-attendance-report)
* Content Source: [Teams/teams-analytics-and-reports/meeting-attendance-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/meeting-attendance-report.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@lynnroe Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
