### ISSUE TITLE
Where do you make these changes

### ISSUE THREAD

**Issue by kevincrossman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6107]
it doesn't say anywhere on this page where to make these changes. Kind of an important detail...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfaea5f2-b19c-6170-8f7c-a20712358b46
* Version Independent ID: 974ed15e-e9a3-1559-1a5c-9636f09240b2
* Content: [Custom apps store - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/customize-your-app-store)
* Content Source: [Teams/customize-your-app-store.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/customize-your-app-store.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Hi @kevincrossman Thank you for your comment. I've updated the article. https://docs.microsoft.com/en-us/MicrosoftTeams/customize-your-app-store
-Cindy
