### ISSUE TITLE
Image issue

### ISSUE THREAD

**Issue by Jared-Harrington-Gibbs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6116]
An image seems to be have included as a code block instead of being rendered properly.
See link below.

https://imgur.com/a/qbFfbfb

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 305a21ef-6e99-3f0d-99a0-990489a93715
* Version Independent ID: 5edc67ee-0d68-50a3-fafd-f764d8762fa5
* Content: [Outbound call restrictions - Audio Conferencing & PSTN calls - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/outbound-calling-restriction-policies)
* Content Source: [Teams/outbound-calling-restriction-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/outbound-calling-restriction-policies.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@Jared-Harrington-Gibbs Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @Jared-Harrington-Gibbs  , this appear to have been fixed [yesterday](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/120b45c3ae287c832862f77c8ec14a8579afc920).

**Comment by get-itips** [comment]
@scanum please close

**Comment by scanum** [comment]
@Jared-Harrington-Gibbs Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
