### ISSUE TITLE
Release not up to date with the blog

### ISSUE THREAD

**Issue by greganth1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#612]
This blog https://techcommunity.microsoft.com/t5/Skype-for-Business-Blog/Teams-meetings-enabled-on-Skype-Room-Systems-v2-starting-with/ba-p/213151 mentions 4.0.8.0 is the latest but it's not reflected here in the main doc section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47e1d48a-bd57-205c-d4b4-4fbd0940623a
* Version Independent ID: ec8ea898-ee36-f3ac-b5be-e272d3273430
* Content: [Release notes](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/srs2-release-note)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/srs2-release-note.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/srs2-release-note.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @davgroom
* Microsoft Alias: **jambirk**

**Comment by kenwith** [comment]
@davgroom - would you want me to submit a Pull Request for you to get the article updated?

**Comment by kenwith** [comment]
@greganth1 - Thank you for submitting this feedback.

@davgroom is the PM for this area and we will get this tracked down. It is a very good catch on the blog entry.

I was able to get this into the backlog for the Skype Room Systems writing team. The team will work with @davgroom and get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@greganth1 Thank you for this feedback. 

From my understanding Ken has this in the backlog to be worked on. I am going to close this issue untill they have a reply about this issue.

**Comment by JetzeMellema** [comment]
The article is still/again outdated. Latest version is 4.0.51.0 (https://techcommunity.microsoft.com/t5/Skype-for-Business-Blog/SRSv2-4-0-51-0-Update-Starts-Going-Live-November-14th/ba-p/286780)

@davgroom It would be good to add include updating the Release Notes when releasing new versions. Currently it looks like there's a gap between announcements on the blog and the release notes on docs.

**Comment by kenwith** [comment]
@jambirk - FYI - looks like article needs updating.

**Comment by scanum** [comment]
@jambirk Any updates on this issue? Thanks!

**Comment by jambirk** [comment]
Update tempo by @sohailta  seems to have addressed this. all previously mentioned lags are included in current version.
