### ISSUE TITLE
No alternatives to the legacy portal

### ISSUE THREAD

**Issue by Jared-Harrington-Gibbs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6122]
In many places the user is guided through the management steps using the skype legacy portal which is slated for complete retirement in less than 1 month. Could you assign someone to update all the instructions to include the equivalent steps using the Teams Admin portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 485c3bcb-41f9-6873-bd04-2f4110d07655
* Version Independent ID: df1cd65a-1636-73b7-3245-674dfb6b86cf
* Content: [Change phone numbers on Audio Conferencing bridge - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/change-the-phone-numbers-on-your-audio-conferencing-bridge)
* Content Source: [Teams/change-the-phone-numbers-on-your-audio-conferencing-bridge.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/change-the-phone-numbers-on-your-audio-conferencing-bridge.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by Jared-Harrington-Gibbs** [comment]
I also want to be clear that this includes many of the linked documentation pages but I don't want to open a bunch of duplicate requests.

**Comment by scanum** [comment]
@Jared-Harrington-Gibbs Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
