### ISSUE TITLE
The supported Linux architecture isn't specified

### ISSUE THREAD

**Issue by jimbobbennett** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6126]
According to this doc, the Teams desktop app supports linux. I've tried installing it on a Raspberry Pi and get an error, which I'm assuming is because it doesn't support linux on ARM. The doc doesn't specify which architectures are supported on linux, so can this be clarified to indicate if it supports x86, x64, ARM, ARM64 etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@jimbobbennett Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by HolgerJeromin** [comment]
Just had the same problem with a small 32bit netbook. 
Please adjust documentation that you do not have a 32bit desktop application:

Looks like amd64 only:

https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/
https://packages.microsoft.com/yumrepos/ms-teams/

**Comment by lindspea** [comment]
@jimbobbennett @HolgerJeromin thank you for reaching out and helping improve MS Docs. I see the article has recently been updated with more information. Please could you have a look and let me know if you still need assistance. There is also a link for Linux support.

**Comment by HolgerJeromin** [comment]
IMO no real change regarding to this issue.
The CPU for linux support (amd64 only) is still not mentioned.

**Comment by jimbobbennett** [comment]
@lindspea - Nope, still nothing under linux saying the supported architectures. Lots of details for Windows, but not for Linux.

**Comment by lindspea** [comment]
@HolgerJeromin @jimbobbennett thank you for your replies. Let me investigate further and I'll let you know as soon as I know.

**Comment by lindspea** [comment]
@SerdarSoysal please could you assist.

**Comment by lindspea** [comment]
@SerdarSoysal

**Comment by scanum** [comment]
Hi @jimbobbennett we recommend you post this to the Q/A Channel. We appreciate you submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
