### ISSUE TITLE
Broken links in the Excel file

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6132]
The attached playbook contains links that are mostly broken - they lead to the skypeforbusiness path and not microsoftteams path

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 243b9f9c-de59-d1b3-42be-5367526059e0
* Version Independent ID: d1435070-4b51-b487-dddc-2d8dc16798f9
* Content: [Onboarding checklist - Configure cloud voice workloads - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/onboarding-checklist-configure-cloud-voice-workloads-in-Microsoft-Teams)
* Content Source: [Teams/onboarding-checklist-configure-cloud-voice-workloads-in-Microsoft-Teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/onboarding-checklist-configure-cloud-voice-workloads-in-Microsoft-Teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Larryngolog thank you for reaching out and helping improve MS Docs. Are you referring to the Excel spreadsheet with the links?

**Comment by Larryngolog** [comment]
Hi, yes, I'm referring to this excel file https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/downloads/site-enablement-playbook-for-voice-(playbook).xlsx?raw=true

**Comment by lindspea** [comment]
@LanaChin please could you assist.

**Comment by lindspea** [comment]
@LanaChin

**Comment by cichur** [comment]
Hi @Larryngolog 
I've filed a task for myself to update this spreadsheet. Thank you for your information. Cindy
