### ISSUE TITLE
Clarification about the availability of "Update policies"

### ISSUE THREAD

**Issue by rpodric** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6136]
It doesn't exist in the tenant I'm looking at right now. Apparently it's still rolling out, but when?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5f1cdd1-09ff-f95d-6d50-e7880d34020f
* Version Independent ID: 59219640-305b-30c1-bc10-87e2633d95db
* Content: [Public preview in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/public-preview-doc-updates)
* Content Source: [Teams/public-preview-doc-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/public-preview-doc-updates.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by teamsplayer** [comment]
Yes both policy and client side UI is still in flight. ETA is Nov or early Dec. Thank you!

**Comment by IanYates** [comment]
I too was trying to follow the steps in the docs: https://docs.microsoft.com/en-us/MicrosoftTeams/public-preview-doc-updates and even enabled the custom apps as disucssed https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant

It would be handy if the docs for a brand new - still in preview - feature clarified that the described functionality may take some time to appear.  I was refreshing all sorts of things trying to get the page to update before realising I was on a fool's errand.

Anyway, I'm looking forward to joining the preview when it's possible  :)

Thanks

**Comment by nam31** [comment]
@rpodric Thank you for your feedback
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Teams UserVoice](https://microsoftteams.uservoice.com/forums/555103-public). You might find others have made a similar request that you can add to, or you can open a new one.
Thank you for your contribution to make the docs better! Much appreciated!
