### ISSUE TITLE
Crashes when I click on General Channel of the some Teams in Microsoft Teams Desktop ever since yesterday's update. Every time I go to that channel it crashes again... 

### ISSUE THREAD

**Issue by ashoksubedi1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6139]
[Is it just me or others too that the Teams Desktop version has been crashing ever since yesterday's update. Basically if I go to any General Channel it just crashes the whole App and restarts the app...but when it is back; it is back to the same channel so it crashes again.....until teams actually signs me out....once I sign in it is back on different channel so it stays turn on.....it is happening only to some teams General Channel not all........the same channel in the web version of teams is fine.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6da28da-eb7b-d3ae-4c2f-8f87803b1830
* Version Independent ID: 8c42d7a2-80c6-86dd-347a-ed6d8d909c41
* Content: [Teams updates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-client-update)
* Content Source: [Teams/teams-client-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-client-update.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by nam31** [comment]
@ashoksubedi1 Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.https://docs.microsoft.com/office365/admin/contact-support-for-business-products
