### ISSUE TITLE
Link to download the PowerBI reports are incorrect

### ISSUE THREAD

**Issue by Richard-Barr3tt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6141]
In the sentence 

Download the CQD Teams Auto Attendant & Call Queue Historical Report Template and save it to a directory on your computer.

The aka.ms link under 'CQD Teams Auto Attendant & Call Queue' goes to microsoft.com and not the download
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cff4fb5a-c48b-4864-1bd7-3f933e2983ed
* Version Independent ID: f7e81551-61c6-3595-db92-59dfb1da5506
* Content: [Using CQD Power BI report to view Auto Attendant & Call Queue Historical Report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cqd-teams-aa-cq-historical-report)
* Content Source: [Teams/CQD-teams-aa-cq-historical-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-teams-aa-cq-historical-report.md)
* Service: **msteams**
* GitHub Login: @CLYVR
* Microsoft Alias: **colongma**

**Comment by CLYVR** [comment]
Hi Richard - thanks for your message.  I've verified the link and it should be working and I've heard that others have downloaded the file.  Would you please try again and if it doens't work I can provide you with an alternate link.  Thanks.

**Comment by Richard-Barr3tt** [comment]
Hey Colin,

Seems to be working now, there were a fair few other people in Teams reporting this as well it looks like Jens has fixed it.

Ta
Rich

**Comment by CLYVR** [comment]
Yes, he has - thanks to him and my mistake for not telling him I needed the link to stay active.  Sorry for any inconvenience.  The reports may also say "Preview" or "TAP" on them - they are the GA reports and that wording will be removed when the file has a new permanent home - I'll let you know.

**Comment by nam31** [comment]
@Richard-Barr3tt Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
