### ISSUE TITLE
Report Template download link does not work

### ISSUE THREAD

**Issue by gtimread** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6142]
The download link for the "CQD Teams Auto Attendant & Call Queue Historical Report Template" in this doc does not work (https://aka.ms/TAPAACQAnalytics). It redirects to https://www.microsoft.com/en-gb/?ref=aka.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cff4fb5a-c48b-4864-1bd7-3f933e2983ed
* Version Independent ID: f7e81551-61c6-3595-db92-59dfb1da5506
* Content: [Using CQD Power BI report to view Auto Attendant & Call Queue Historical Report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cqd-teams-aa-cq-historical-report)
* Content Source: [Teams/CQD-teams-aa-cq-historical-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-teams-aa-cq-historical-report.md)
* Service: **msteams**
* GitHub Login: @CLYVR
* Microsoft Alias: **colongma**

**Comment by CLYVR** [comment]
Hi Tim - thanks for your message.  I've verified the link and it does resolve to the correct location and the power bi file downloads.   Please try again and let me know and if it doesn't work for you I can provide you with another link.

**Comment by CLYVR** [comment]
Hi Tim.  I just found out there was a problem with the link earlier and one of my team members has fixed that.  Apologies for any inconvenience.  Please try again and let me know if you encounter a problem.

**Comment by gtimread** [comment]
Hi Colin. Thanks for the update. I am able to access the download link now
and can confirm that it works. I had tried from 2 machines on different
networks earlier, so I was pretty sure the link wasn't working.

All the best,
Tim Read

**Comment by CLYVR** [comment]
Appreciate the response.  If the reports in the template have "Preview" or "TAP" in the titles that is being addressed.  It is the GA template.

**Comment by nam31** [comment]
@gtimread The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks
