### ISSUE TITLE
download link to "CQD Teams Auto Attendant & Call Queue Historical Report Template" is broken

### ISSUE THREAD

**Issue by IngoWestner** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6143]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cff4fb5a-c48b-4864-1bd7-3f933e2983ed
* Version Independent ID: f7e81551-61c6-3595-db92-59dfb1da5506
* Content: [Using CQD Power BI report to view Auto Attendant & Call Queue Historical Report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cqd-teams-aa-cq-historical-report)
* Content Source: [Teams/CQD-teams-aa-cq-historical-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-teams-aa-cq-historical-report.md)
* Service: **msteams**
* GitHub Login: @CLYVR
* Microsoft Alias: **colongma**

**Comment by CLYVR** [comment]
Hi Ingo - thanks for your message.

I've verified that the link is valid and working for some people at least.  What error are you getting?

**Comment by CLYVR** [comment]
Hi Ingo - sorry, I just found out there was a problem with the link earlier but it should be working now thanks to the efforts of one of my team members.  Sorry for any inconvience.  Please try again and let me know.

**Comment by nam31** [comment]
@IngoWestner Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
