### ISSUE TITLE
Link to template is broken

### ISSUE THREAD

**Issue by dinocaputo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6144]
https://aka.ms/TAPAACQAnalytics needs to be updated to actual download that is GA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cff4fb5a-c48b-4864-1bd7-3f933e2983ed
* Version Independent ID: f7e81551-61c6-3595-db92-59dfb1da5506
* Content: [Using CQD Power BI report to view Auto Attendant & Call Queue Historical Report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cqd-teams-aa-cq-historical-report)
* Content Source: [Teams/CQD-teams-aa-cq-historical-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-teams-aa-cq-historical-report.md)
* Service: **msteams**
* GitHub Login: @CLYVR
* Microsoft Alias: **colongma**

**Comment by CLYVR** [comment]
Thanks for your message.  The file that is linked to is the GA Power BI template file.  I'm waiting on the final storage location for the file and will then be able to update the article however all that will change is the link, the file will be identical.  I'll let you know when this occurs.

**Comment by CLYVR** [comment]
Just wanted to follow up on something with you - assuming you have downloaded the template, do the reports say "TAP" or "Preview" or similar somewhere?  Is this what you are referring to when you say needs to be the "GA" version?  Thanks!

**Comment by dinocaputo** [comment]
I have not been able to download the template yet due to the link not working but did get a copy from someone that had downloaded them when you made the announcement.
My reports all say Preview

**Comment by CLYVR** [comment]
Thanks for the confirmation on the reports saying "Preview".  I'm working to address that and will let you know when it's resolved.  It's only a title issue, the reports are exactly them same.

**Comment by scanum** [comment]
@dinocaputo https://docs.google.com/document/d/1kYGU_Wuhk6QX554tp_U9GOmuOevjCyFcowD6AiGdgwE/edit
