### ISSUE TITLE
Is that the only step?

### ISSUE THREAD

**Issue by GwynThomas** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#615]
When first installing the databases on an AlwaysOn Availability Group we have to fail over to the Replica in the Group and Update to add the necessary entries in Security and Permissions to the second node.

If we are applying an update to the Skype for Business Back End are there no changes to these Security and Permissions settings or should we be failing over to the replica node and running the update again just in case?

Some clarification would be great :)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c35b1bb6-8e84-1112-1d95-3d8afb887dd0
* Version Independent ID: 88b604fd-46f7-ab82-c6d3-4538568ab6c2
* Content: [Patch or update a SQL Server in an AlwaysOn Availability Group in Skype for Business Server](https://docs.microsoft.com/en-gb/skypeforbusiness/manage/topology/patch-or-update-sql-server)
* Content Source: [Skype/SfbServer/manage/topology/patch-or-update-sql-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/topology/patch-or-update-sql-server.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@GwynThomas  - thank you for submitting feedback. 

This is a good question that should be escalated through engineering to get clarification for your environment.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
