### ISSUE TITLE
Please add another key to the Proxy Config

### ISSUE THREAD

**Issue by DennisLanger** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6153]
[Enter feedback here]
Hi,
many customer are using automated proxy.pac files for their proxy configuration and not a fixed IP/FQDN. You might want to add the following key to the Registry:
AutoConfigURL = http://contoso.com/proxy.pac

Best Regards
Dennis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a711c07e-10b3-baf0-b92c-9dbcf6ab9474
* Version Independent ID: 2038cd48-44b1-1ed1-6e50-48290eef5605
* Content: [Prepare your Environment - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-prep)
* Content Source: [Teams/rooms/rooms-prep.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-prep.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@DennisLanger Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @DennisLanger How are you?
I was able to reach the team and asked about this, it was decided to leave the document as is for now, when the `AutoConfigURL` is officially supported on this scenario I will be glad to update it.
Thanks

**Comment by scanum** [comment]
@DennisLanger  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
