### ISSUE TITLE
Teams through explicit proxy - calling and screen sharing are failing

### ISSUE THREAD

**Issue by uttampcu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6154]
[Enter feedback here]
This page implies that while not recommended, it is possible to fully use Teams behind a proxy.  The wording claims a negative experience, not a failure.  However we're not finding that to be true for all Teams features.  We believe we meet the proxy requirements above but find features like screen sharing and calling are still attempting to connect directly to the following from the O365 URLs and IP service:
{
    "id": 11,
    "serviceArea": "Skype",
    "serviceAreaDisplayName": "Skype for Business Online and Microsoft Teams",
    "ips": [
      "13.107.64.0/18",
      "52.112.0.0/14",
      "52.120.0.0/14"
    ],
    "udpPorts": "3478,3479,3480,3481",
    "expressRoute": true,
    "category": "Optimize",
    "required": true
  }

Is there a way to force all Teams traffic including this UDP traffic through the proxy?  We have already configured netsh winhttp proxy and a system-wide proxypac to use an explicit proxy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 826084d1-06f7-e837-bcfc-d86d427288f6
* Version Independent ID: 9b36168e-d398-0188-c510-4dc5dd5f9563
* Content: [Proxy servers for Teams or Skype for Business Online - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/proxy-servers-for-skype-for-business-online)
* Content Source: [Teams/proxy-servers-for-skype-for-business-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/proxy-servers-for-skype-for-business-online.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@uttampcu Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @uttampcu how are you? Hope you are doing good.
Some time has passed since you opened the issue, and, to understand if any documentation changed is needed I would like to check if you still have this issue.
I myself have an environment thru a proxy and I do not face those issues, however, all the recommendations included in the article are being applied.
