### ISSUE TITLE
Mistake for the location of the Network planner should be Planning > Network planner

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6156]
I have found a mistake for the location of the Network planner. 

_Network Planner is a new tool that is available in the Teams admin center. It can be found by going to Planner > Network planner. In just a few steps, the Network Planner can help you determine and organize network_

Change 'Planner > Network planner' to 'Planning > Network planner' as this is how it is displayed in the Teams Admin centre

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18f0a6ad-85d4-1d26-2e7c-496f0699e418
* Version Independent ID: c1283d82-a691-19aa-9fb9-be51031f0f39
* Content: [Use the Network planner for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/network-planner)
* Content Source: [Teams/network-planner.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/network-planner.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@nikki-c Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for noticing and reporting @nikki-c
