### ISSUE TITLE
Update to some outdated information

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6157]
The first bullet point on the page mentions Teams support 5,000 users. This is out of date. Teams currently support 10,000 users per team. This is being increased to 25,000 users Dec 2020 to Jan 20201 see Roadmap id 68723.

Also the Teams respecting the Microsoft Group naming policy is in GA and not private preview.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c310bab-f8d8-b173-0bff-9f93fe1f7abf
* Version Independent ID: 1f983e68-65e3-aa7d-aaaa-d62912f37e4c
* Content: [Plan for Microsoft 365 Groups when creating teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/plan-office-365-groups)
* Content Source: [Teams/plan-Office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-Office-365-groups.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@nikki-c Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @nikki-c
