### ISSUE TITLE
Teams Admin roles information is not aligned to the Microsoft Teams administrator roles to manage Teams page

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6158]
Thea Teams admin data is not the same as on the page 'Use Microsoft Teams administrator roles to manage Teams' https://docs.microsoft.com/en-us/MicrosoftTeams/using-admin-roles#:~:text=Use%20Microsoft%20Teams%20administrator%20roles%20to%20manage%20Teams,...%203%20Cmdlets%20available%20for%20each%20role.%20

I would just list the 4 administrator roles and there refer to the Microsoft Teams administrator roles to manage Teams page
****

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18f0a6ad-85d4-1d26-2e7c-496f0699e418
* Version Independent ID: c1283d82-a691-19aa-9fb9-be51031f0f39
* Content: [Use the Network planner for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/network-planner)
* Content Source: [Teams/network-planner.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/network-planner.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@nikki-c Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @nikki-c thanks for your feedback.

Excuse me, do you refer to this extract?

> To use Network planner, you must be a Global Administrator, Teams Service Administrator, or Teams Communications Administrator.

Which role are you not seeing listed in the link you shared?

Thanks

**Comment by get-itips** [comment]
Hello @nikki-c could you see my comment? Thank you

**Comment by scanum** [comment]
@get-itips  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
