### ISSUE TITLE
M365 Report Usage Out of date page

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6159]
This page is showing an outdated view of the user reports in the Admin centre. This is the the web link that is referred to in the M365 Admin centre > Report > Usage. https://docs.microsoft.com/en-US/microsoft-365/admin/activity-reports/activity-reports?WT.mc_id=365AdminCSH&view=o365-worldwide.

I suggest that this page is replaced with the up to date page
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81440b2f-391b-5856-a216-15866f37082a
* Version Independent ID: cdd15cd4-d4ed-c413-e2b9-ebf6dad8b33b
* Content: [Use activity reports for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-activity-reports)
* Content Source: [Teams/teams-activity-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-activity-reports.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@nikki-c Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by CarolynRowe** [comment]
Hello,  Thank you for the feedback.  We are planning an update to the article to eliminate redundant information between the two articles--scheduling in progress.
