### ISSUE TITLE
Lack of requirement information regarding on-prem REST API endpoint 

### ISSUE THREAD

**Issue by aikensam** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6160]
[Enter feedback here]

Teams backend needs access to Exchange on-prem REST API https://xxxx.xxxx.xxxx/API/* for presences of on-prem mailboxes. It is mentioned in https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/known-issues/teams-exchange-interaction-issue for troubleshooting but is not included in this general Teams and Exchange interact article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@aikensam Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks @aikensam for your feedback.
I analyzed the issue you submitted and decided to propose an update to the article, if it gets approval, it will be reflected online.
Thank you again
