### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by rramoscabral** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6163]
Acording to SharePoint Limits at https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits.

The term site collection is now single site "The storage limit for a single site (previously called "site collection"), not the amount of storage provided for each site."

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/pt-pt/microsoftteams/limits-specifications-teams#storage)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@rramoscabral  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
