### ISSUE TITLE
Revise ATP Safe links recommended exceptions

### ISSUE THREAD

**Issue by DCri** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6165]
Hi,

The article recommends ATP Safe links exceptions for Zoom:
\*zoom.us\*, \*zoom.com\*, \*zoomgov.com\*

This is a bad recommendation, creating exceptions for a wide range of potentially malicious domains.

Presumably \*.zoom.us/\*, \*.zoom.com/\*, \*.zoomgov.com/\* would include the common URLs without unnecessary additional risk.  Similarly the webex one would be improved by changing \*.webex.com\* to \*.webex.com/\*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c62081e-2421-80b9-8ba9-aaf8fd55e432
* Version Independent ID: 5df3c5e5-978f-cfa7-9e5c-3cd7f65fa8ff
* Content: [Enable Teams Rooms devices to join third-party meetings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/third-party-join)
* Content Source: [Teams/rooms/third-party-join.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/third-party-join.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@DCri  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @DCri, thank you for your feedback and help us to improve docs.microsoft.com.

I applied your suggestions but have in mind they are only examples, you don't have to use them. In the article you can find the following sentence:
"For a complete list of URLs to add to your ATP Safe Links "do not rewrite" list or third-party URL rewrite exception list, contact the third-party meeting service provider you want to accept meeting invites from."
