### ISSUE TITLE
Does Microsoft Graph API is available for MS Team Admin Create/Update App permission policies and assigned it to users or group

### ISSUE THREAD

**Issue by anomepani** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6167]
For different groups of users like IT, End User, HR, Developer Group, etc in organizations have different types of apps in their Microsoft team.

Does Microsoft Graph API is available for Create/Update [App permission policies](https://admin.teams.microsoft.com/policies/app-permission) and assigned it to users or groups?
I am exploring a programmatic way to manage the app permission policy which is available in the Microsoft team admin center.

`MS Teams`, `MS Teams Admin API`, `MS Teams App Permission API `.

I am looking for a programmable approach for Whatever available in [MS Team Admin UI App Permission](https://docs.microsoft.com/en-us/microsoftteams/teams-app-permission-policies)

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbcabee-fa96-2878-e983-3c966f84ee15
* Version Independent ID: 02fa4fd8-77e0-5cb2-a4af-576cbb68322f
* Content: [Manage your apps in the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-apps)
* Content Source: [Teams/manage-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-apps.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@anomepani Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
