### ISSUE TITLE
Common Area Phone

### ISSUE THREAD

**Issue by kestyu8** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6168]
Hi all

Some people recommend customer to use "common area phone" license for Microsoft 365 Business users, to enable teams calling features. Whereas in real life it's working, the idea from MS is most probably to use Microsoft 365 Business Voice license.

Can you clarify in this page that CAP licenses are not allowed for users? Or better block the assignment of CAP licenses to users which already have other licenses (Business or Enterrprise) assigned.

Thanks
Stefan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abae7324-861d-7ca7-7239-a5df8fd927d5
* Version Independent ID: 8a30bd2f-9bc3-a0a8-8b31-d53836ead4d0
* Content: [Microsoft Teams add-on licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=small-business)
* Content Source: [Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@kestyu8  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @kestyu8, thank you for your feedback and help us to improve docs.microsoft.com.

In this article, there is a description of the purpose of each license. If you use it in some other way, it could work, but it won't be supported.

For feature requests like block license assignment, I need to kindly redirect you to this resource https://office365.uservoice.com/. There, your suggestion will reach the product team.

Thank you again!

**Comment by scanum** [comment]
@kestyu8  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
