### ISSUE TITLE
TAP for Zoom or GA?

### ISSUE THREAD

**Issue by githubsteveb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6169]
I noticed at the bottom the article says,

 _"Zoom meetings join is currently only available to select Microsoft Teams Rooms customers through Technology Access Program (TAP)."_

Then comparing to the Roadmap which says it's "rolling out": https://www.microsoft.com/en-us/microsoft-365/roadmap?featureid=68736

Is TAP still needed for Zoom at the moment?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c62081e-2421-80b9-8ba9-aaf8fd55e432
* Version Independent ID: 5df3c5e5-978f-cfa7-9e5c-3cd7f65fa8ff
* Content: [Enable Teams Rooms devices to join third-party meetings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/third-party-join)
* Content Source: [Teams/rooms/third-party-join.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/third-party-join.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@githubsteveb Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
