### ISSUE TITLE
Need server version requirements

### ISSUE THREAD

**Issue by oddhair** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#617]
I am familiar enough with the roadmap from OCS through to Skype for Business that I know when your docs say "works with Skype for Business server" in so many words that you mean 2015 only, but I have clients still using Exchange 2010 in multi-forest and they couldn't use the older LRS, let alone the newer SRS V2 systems. Somehow they still think the SRS v2 should be capable of working with Lync server 2013. It would be invaluable to me if one of the SRS V2 pages could explicitly state it's not compatible with Lync server 2013 as lots of people think the Skype for Business umbrella includes 2013 server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 515e5db8-20be-f979-5de9-3998713518dd
* Version Independent ID: a284fee3-f324-2984-431e-df14d3c4bd2d
* Content: [Skype Room Systems v2 requirements](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/requirements)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
See aka.ms/SRSDocs where that is explicitly noted. we can also add that to this page too, if you're asking.

… and since the preview of Server 2019 went live, "works with Skype for Business Server" is a blanket statement referring to Server 2015 and Server 2019. Where one or the other is specifically meant, the server version is called out.
