### ISSUE TITLE
Release notes are missing build/version numbers

### ISSUE THREAD

**Issue by anthonynz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6171]
For MS Teams desktop application can you please provide the build numbers along with the dates.

Or at least a link to a list of build numbers and release dates.

Just noticed this is listed under the SkypeForBusiness github project, my feedback is related to this URL:
https://docs.microsoft.com/en-us/microsoftteams/release-notes/release-notes

I wish Teams was as awesome as Skype for Business! (bring back DOS ;) )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5eedcae-036a-4e99-e47f-9e2503b667b2
* Version Independent ID: 3914f6ac-352c-8654-0d84-77bc066a734c
* Content: [Release notes for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/release-notes/release-notes)
* Content Source: [Teams/release-notes/release-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/release-notes/release-notes.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@anthonynz Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
