### ISSUE TITLE
No instructions for how to assign Teams templates to a user or group

### ISSUE THREAD

**Issue by baylosb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6172]
The first image on this page shows text stating that templates can be assigned to a user or group using Teams policy, this doesn't seem possible.
![image](https://user-images.githubusercontent.com/50537055/98738165-66006f00-23fb-11eb-928c-5dd775223c59.png)
  When viewing Teams policy page there's only the option to allow/block creation of private channels.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da3d209-eb82-1a62-9bd5-81ba18792cd4
* Version Independent ID: 94dca200-ab33-7a57-1504-e3ee7e5c610a
* Content: [Create a custom team template in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-team-template)
* Content Source: [Teams/create-a-team-template.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-team-template.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Hi @baylosb,
Thank you for your question. I'll do some research and get back to you. Cindy

**Comment by cichur** [comment]
Hi, I spoke with the developer. We don't have that policy yet...it's in the works. We appreciate your comments. --Cindy
