### ISSUE TITLE
License requirements

### ISSUE THREAD

**Issue by ashwanikumar04** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6174]
Hello Team:

The license requirements for the Export API (https://docs.microsoft.com/en-us/microsoftteams/export-teams-content) are not clear.

Suppose I create a multi-tenant application to fetch data from multiple customers, who should have the required licenses. 
The account which is hosting the multi-tenant application or the customer whose data will be fetched?

Thanks,
Ashwani

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eb2244d-b82d-0559-0255-ac0cb7ce05e3
* Version Independent ID: e3a7a842-7efe-40db-e3c7-da56d7b24c02
* Content: [Export content with the Microsoft Teams Export APIs - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/export-teams-content)
* Content Source: [Teams/export-teams-content.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/export-teams-content.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@ashwanikumar04 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@ashwanikumar04 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
