### ISSUE TITLE
test

### ISSUE THREAD

**Issue by echo4tech** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6182]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92fcb1f6-5cc2-f6bd-cfa9-11d811f1dbf1
* Version Independent ID: 9a571e6d-8cb3-9ff8-a5c2-62deab146264
* Content: [Admin quick start - Meetings and live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/quick-start-meetings-live-events)
* Content Source: [Teams/quick-start-meetings-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/quick-start-meetings-live-events.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@echo4tech Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
