### ISSUE TITLE
Title needs changing

### ISSUE THREAD

**Issue by BSiefferman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#619]
"Remove the Enterprise Edition Front End Pool or Standard Edition Front End Server" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a20af1f3-a543-abb0-2b95-3d058dc4bf0d
* Version Independent ID: b255d635-7ad7-bee1-8913-483a54f98966
* Content: [Remove the Enterprise Edition Front End Server or Standard Edition Front End Server](https://docs.microsoft.com/en-us/skypeforbusiness/migration/remove-the-front-end-server)
* Content Source: [Skype/SfBServer2019/migration/remove-the-front-end-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/migration/remove-the-front-end-server.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@BSiefferman - thank you for the feedback. I updated the title in this Pull Request: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/620

Also, if you are interested the docs are open source now and you can submit a Pull Request with ideas and changes. You will then show up in the contributor list here: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/graphs/contributors

Let me know if you have other ideas or questions about creating a Pull Request. Much appreciated for making the content better!
