### ISSUE TITLE
Link to or explain the Microsoft Teams admin center

### ISSUE THREAD

**Issue by lukepuplett** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6190]
Hello - These docs keep talking about the **Microsoft Teams admin center** but I don't know what that is and Googling for it returns SERPs that just point back to these docs.

My story is: I'm looking around Teams as a new user to see if I can use it to talk to other people on Teams, especially make video and voice calls, i.e. to replace Skype since none of my friends use it anymore and WhatsApp desktop has no voice calling. Zoom is too conference-call-y, I don't use Facetime/Apple and I don't want to use my phone given that I have a webcam and condenser mic.

So I've setup Teams to check it out. I've always used and recommended Slack for my clients, since it was first to market. I work alone, so I am on the free tier; I don't want to pay monthly to explore, or to make occasional calls (given alternatives).

I want to search for someone (ironically today, an MS sales exec!) and add him and be able to video call him, ad-hoc. It seems I can't. Searching for him in various search boxes, yields no results.

It feels like Skype was thrown under a bus and no product was there to replace it, or at least the UX/docs aren't guiding me into the pit of success with Teams as a noob.

What am I missing? Should this be simple? Is this a paid feature? Do I need to enable something in the admin center?

Anyway, sorry I've turned this into a product support issue: my main point is that I've clicked around in Teams and searched the web and I don't know where the "admin center" is that you're talking about. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external access (federation) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@lukepuplett Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@lukepuplett Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by lukepuplett** [comment]
@scanum Thanks but...

"You must be an admin for a business subscription to use these support methods"

(at least these docs are clear that I need to be a paid subscriber)

I did say above that I work alone and I'm on the free-tier so I don't have a business subscription; I'm just looking around with my personal account. So perhaps the docs aren't explaining that chatting or calling external users is not allowed for free-tier users.

Perhaps I'm missing something but it really looks to me that Microsoft bought leading web video calling app Skype and all its users at great expense, then effectively obsoleted that app for a whole class of business workers, but forgot to build Skype's primary feature in the replacement Teams app, clearing the way for competitors to fill the space.
