### ISSUE TITLE
The instructions for installing the MicrosoftTeams pre-release module is inaccurate.  -AllowPrerelease and -RequiredVersion triggers result in errors.

### ISSUE THREAD

**Issue by jajensen34** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6192]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd283f6e-3865-ed70-d663-cc461ee8ba57
* Version Independent ID: 2450d311-fc04-d8b6-b4a2-b1890ec6fc3e
* Content: [Install Microsoft Teams PowerShell - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install#install-teams-powershell-public-preview)
* Content Source: [Teams/teams-powershell-install.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-install.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
@jajensen34 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jajensen34** [comment]
Manuela,

Once I restarted my machine, the -AllowPreRelease and -RequiredVersion triggers worked.  I’ll assume, then, that I had to restart Powershell after installing PowerShellGet in order for that command to work.

Thanks,

Jason J. Jensen
O: +1 (817) 601-0939  M: +1 (570) 242-5297
