### ISSUE TITLE
Legacy Portal Retired

### ISSUE THREAD

**Issue by auger282** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6193]
For Step 4 the Legacy Portal has been retired. Is PowerShell the only way to activate users for Microsoft Audio Conferencing now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed33488-1a24-f443-dd56-c5327188b5a4
* Version Independent ID: 8da32180-396d-c7a8-6410-472beabff9ce
* Content: [Set up Audio Conferencing for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-audio-conferencing-in-teams)
* Content Source: [Teams/set-up-audio-conferencing-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-audio-conferencing-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@auger282 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
