### ISSUE TITLE
Teams Meeting Info

### ISSUE THREAD

**Issue by junaidhaqqijd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6199]
Hello,

The Meeting section references "Number of people in a video or audio call from chat" and it mentions 20.  The same is also mentioned under the Chat section.  I think the mention under the Meeting section is a little confusing.  The item that people are mostly asking me is what is the maximum number of people you can have on video, which I think would have most likely been mentioned here under the Meeting section, but what the Meeting section really references is something completely different.  I would recommend revising this section to answer the maximum number of people that can be in a video call in a meeting, and not referencing the maximum number of people that can be elevated into a pseudo meeting type scenario from a chat, which is what is being referenced under the Chat section.

Please let me know if you have any questions.  I would be happy to meet, if needed.

Thanks.

Junaid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@junaidhaqqijd Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@junaidhaqqijd thank you for reaching out and helping improve MS Docs. Please have another look at the article as I see it was updated yesterday with more information. Please let me know if you still need assistance.

**Comment by scanum** [comment]
@junaidhaqqijd  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
