### ISSUE TITLE
Add a capability

### ISSUE THREAD

**Issue by rfcomp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6200]
Could not find this feature in UserVoice so I am commenting here. Sorry about that. Would like to add a capability for text as well, a short message from our IT Department.

Got here from https://www.microsoft.com/en-in/microsoft-365/roadmap?searchterms=67111&filters=&searchterms=67111

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfaea5f2-b19c-6170-8f7c-a20712358b46
* Version Independent ID: 974ed15e-e9a3-1559-1a5c-9636f09240b2
* Content: [Custom apps store - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/customize-your-app-store?branch=v-cichur-customize-the-app-store)
* Content Source: [Teams/customize-your-app-store.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/customize-your-app-store.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@rfcomp Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by rfcomp** [comment]
Got it. Went ahead and added it to uservoice: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/41961574-custom-message-in-the-app-catalog

Thank you!
