### ISSUE TITLE
quicktips.skypeforbusiness.com 

### ISSUE THREAD

**Issue by DevJonBirkett** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6203]
[Enter feedback here]
Hi, 

"quicktips.skypeforbusiness.com" has been removed from the SfB and Teams URl & IP list page (https://docs.microsoft.com/en-gb/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide). 

Does it need to be removed from Firewall Proxy Host Name/Port Examples table as well? 

Kind regards
Jon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a711c07e-10b3-baf0-b92c-9dbcf6ab9474
* Version Independent ID: 2038cd48-44b1-1ed1-6e50-48290eef5605
* Content: [Prepare your Environment - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-prep)
* Content Source: [Teams/rooms/rooms-prep.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-prep.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@DevJonBirkett Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by DevJonBirkett** [comment]
Disagree. 
It's Microsoft documentation. It's their job to insure it is up-to-date, consistent and correct.
