### ISSUE TITLE
Entry in Admin panel not available

### ISSUE THREAD

**Issue by klatvo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6206]
In the article it is written, to go to the teams admin center. The mentioned entry point does not show up in my admin center. When will it be available?

Best, Fritz

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e5f1cdd1-09ff-f95d-6d50-e7880d34020f
* Version Independent ID: 59219640-305b-30c1-bc10-87e2633d95db
* Content: [Öffentliche Vorschau in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/public-preview-doc-updates)
* Content Source: [Teams/public-preview-doc-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/public-preview-doc-updates.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Hello @klatvo 
Do you see the **Update Policies** option in the Teams Admin Center?

**Comment by scanum** [comment]
@klatvo We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
