### ISSUE TITLE
Confirm what Regex Syntax is Supported

### ISSUE THREAD

**Issue by richardjgreen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6207]
The documentation for blocking inbound calls states that it uses Regex but there is no confirmation of what types of statement are supported.

For example, I set-up an expression that uses \d* which should act as a greedy wildcard. I tested the pattern using various example numbers at Regex 101 to validate the syntax and it performs as expected there, however, calls are still being allowed through from the numbers. When I set-up a pattern that targets a specific number it works so it's obviously not accepting \d* as a pattern.

I've had similar issues in the past with Skype for Business Server on-premises where certain aspects of Regex didn't work in patterns for Dial Plans. The documentation needs to be more explicit about what will work and what will not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91c40ca3-c19e-eac3-3adb-815e45ce2388
* Version Independent ID: 1193b36e-8870-aca9-cb9c-59c5fb1f5412
* Content: [Block inbound calls in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/block-inbound-calls)
* Content Source: [Teams/block-inbound-calls.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/block-inbound-calls.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by richardjgreen** [comment]
After testing further, it appears that \d* does work but the rule took much longer to come into force than another rule that I created at the same time. Perhaps the statement about how long the rules take to propagate could be highlighted or reinforced?

**Comment by scanum** [comment]
@richardjgreen Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@richardjgreen thank you for reaching out and helping improve MS Docs. Please could you recommend what should be added in a note for clarity?

**Comment by scanum** [comment]
@richardjgreen We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you
