### ISSUE TITLE
Permissions or role-based access

### ISSUE THREAD

**Issue by jrummer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6209]
[Enter feedback here]
The diagram that shows Permissions or role-based access needs to be updated and grammar/punctuation corrected.  That diagram is a pretty clunky way to show the access levels and the wording is a bit confusing at times.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8935e913-806f-a92c-d09e-e67df4ffd1b4
* Version Independent ID: c7a41cde-66dd-d7cd-1316-42d20ed4841a
* Content: [Use OneDrive for Business and SharePoint for meeting recordings - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/tmr-meeting-recording-change)
* Content Source: [Teams/tmr-meeting-recording-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tmr-meeting-recording-change.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Hello @jrummer, Thank you for your comments. I've made some changes and will publish it this afternoon.

**Comment by jrummer** [comment]
That’s awesome.  Wasn’t sure anyone would actually see this.  Can it be something downloadable?

**Comment by cichur** [comment]
You can download a PDF of the admin guide. Go to this page. The PDF link is at the bottom left of the page. https://docs.microsoft.com/en-us/MicrosoftTeams/how-to-roll-out-teams
