### ISSUE TITLE
Missing / incomplete information about the features of this add-on

### ISSUE THREAD

**Issue by fhoro** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6214]
It is not mentioned in this document if
Compliance Recording integration (ISV)
Contact Center solution integration (ISV)
are also included in this add-on or not.

The announcement made in aug 2020 was mentioning it.
https://docs.microsoft.com/en-us/partner-center/announcements/2020-august#4

It leaves the situation in a grey zone : do we need this add-on to record Teams meetings through ISV or not?

Thank you to clarify that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09168b55-8244-974e-8bb3-6ec16429a650
* Version Independent ID: c17f4f8d-a8bb-3c81-368f-07b932f52ebc
* Content: [Advanced Communications add-on for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/advanced-communications?ranMID=24542&ranEAID=kXQk6*ivFEQ&ranSiteID=kXQk6.ivFEQ-C5Y_yUBCAIUmPvC4VbQK1A&epi=kXQk6.ivFEQ-C5Y_yUBCAIUmPvC4VbQK1A&irgwc=1&OCID=AID2000142_aff_7593_1243925&tduid=%28ir__tpknpv63l0kfq2uy0ctiwv3kfm2xslny16msj22300%29%287593%29%281243925%29%28kXQk6.ivFEQ-C5Y_yUBCAIUmPvC4VbQK1A%29%28%29&irclickid=_tpknpv63l0kfq2uy0ctiwv3kfm2xslny16msj22300)
* Content Source: [Teams/teams-add-on-licensing/advanced-communications.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/advanced-communications.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@fhoro Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LanaChin** [comment]
Hi @fhoro, thanks for your feedback. I've confirmed with the product team that Compliance Recording integration (ISV) and
Contact Center solution integration (ISV) are not in the add-on. We've updated this article, https://docs.microsoft.com/en-us/partner-center/announcements/2020-august#4.
