### ISSUE TITLE
Topology SfB 2015 with Exchange 2019 Support's cloud voice mail.

### ISSUE THREAD

**Issue by Sagamare** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6215]
Hi Team,

In this article under Section : Exchange 2013/Exchange 2016 and Skype for Business 2015 to Exchange 2019 and Skype for Business 2019

You have mention the Topology SfB 2015 + Exchange 2019 is not supported, but it supports CVM, please go thru article : https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-cloud-voicemail#migration-and-interoperability and make this changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29e6436f-d73b-6ccb-c7ca-2d9e42648b6e
* Version Independent ID: 8ac96788-c9e6-9f4b-0d9f-0966bb6a012f
* Content: [Plan for Skype for Business Server and Exchange Server migration - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-um-migration)
* Content Source: [Skype/SfbHybrid/hybrid/plan-um-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/plan-um-migration.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@Sagamare Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Sagamare thank you for helping improve MS Docs. Please can you clarify what changes you are suggesting. The one mentions Skype for Business and the other article mentions Exchange.

**Comment by Sagamare** [comment]
Thank you for reaching out.

If you see the below screenshot from article<https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-cloud-voicemail#migration-and-interoperability>, it says SfB 2015 is supported for Cloud Voice Mail with Exchange server 2019 :

[cid:image004.jpg@01D6BD55.7D48A130]
If you see this article<https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-um-migration>, it shows it’s not supported, I believe this is correct :

[cid:image005.jpg@01D6BD55.7D48A130]

Best regards,
Sameer Gamare
Support Engineer, Skype/Teams
Empowering, Helping, and Advising Customers

Customer Service & Support
•+1 (866) 4257701 x 8983357
•Sameer.gamare@microsoft.com
Working Hours: M-F 08:00am to 05:00pm EST
[cid:image001.gif@01D6BD54.C5D4ABC0]

**Comment by Sagamare** [comment]
Thank you for reaching out.

If you see the below screenshot from [article](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-cloud-voicemail#migration-and-interoperability), it says SfB 2015 is supported for Cloud Voice Mail with Exchange server 2019 :
 
![image](https://user-images.githubusercontent.com/62913867/99452006-03eac100-2949-11eb-9a03-e86c027ccc5d.png)

If you see this [article,](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-um-migration) it shows it’s not supported, I believe this is correct :

 
![image](https://user-images.githubusercontent.com/62913867/99451984-fc2b1c80-2948-11eb-9904-b7ef3b58deca.png)

**Comment by scanum** [comment]
@Sagamare Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
