### ISSUE TITLE
Unable to see comments in Lists

### ISSUE THREAD

**Issue by BinaryEcho** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6216]
There is no option next to an issue (as several of the ‘lists’ product videos and screenshots) to add comments

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
