### ISSUE TITLE
"How can I monitor minute my pool usage?" is a weird sentence

### ISSUE THREAD

**Issue by bradvido** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6219]
As seen here: https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-subscription-dial-out#how-can-i-monitor-minute-my-pool-usage

Seems to be a typo.

**Comment by scanum** [comment]
@bradvido Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
