### ISSUE TITLE
Change associated location details

### ISSUE THREAD

**Issue by armazing** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#622]
unable to change emergency location address, not able to see option Change associated location details stated in this document

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800d0cd9-8964-f27c-49f3-0bf4fdaa1b6f
* Version Independent ID: d6b5f936-f920-d289-41c2-00e76bc1b2c3
* Content: [Add, change, or remove an emergency location for your organization](https://docs.microsoft.com/en-us/skypeforbusiness/what-are-calling-plans-in-office-365/add-change-or-remove-an-emergency-location-for-your-organization)
* Content Source: [Skype/SfbOnline/what-are-calling-plans-in-office-365/add-change-or-remove-an-emergency-location-for-your-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/what-are-calling-plans-in-office-365/add-change-or-remove-an-emergency-location-for-your-organization.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@armazing - thank you for submitting feedback. 

This is really important regarding the emergency locations and I want to make sure this gets resolved for you right away. As far as I know the steps in the article are correct so I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. It will be escalated to a support service engineer. 

Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
