### ISSUE TITLE
3rd party teams

### ISSUE THREAD

**Issue by vojinle** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6222]
Would this restriction affect collaboration with 3rd party teams?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf54bf5d-1748-46bf-a503-5e978f56126c
* Version Independent ID: 5976a1df-52e9-eb19-fd41-c7b04fce74f8
* Content: [Sign in to Teams using modern authentication - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sign-in-teams#how-to-restrict-sign-in-on-desktop-devices)
* Content Source: [Teams/sign-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sign-in-teams.md)
* Service: **msteams**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@vojinle Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
