### ISSUE TITLE
Nonexistent hyperlink

### ISSUE THREAD

**Issue by madnata** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6223]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/4979990/99342231-82127d80-28df-11eb-9a9b-afe71781a141.png)

As the Teams admin, you **control which features guests can (and can't) use in Team**s. Guests in Teams are covered by the same compliance and auditing protection as the rest of Microsoft 365, and can be managed within Azure AD. Guest access is subject to Azure AD and Microsoft 365 or Office 365 service limits.

Hyperlink for bold section above doesn't work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2492e210-08f9-a476-97ec-008926def961
* Version Independent ID: adcb0dd9-4a3c-b665-6e34-ce3276c89b4d
* Content: [Guest access in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/guest-access)
* Content Source: [Teams/guest-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@madnata  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@madnata thank you for pointing this out. Would this link suffice - https://docs.microsoft.com/microsoft-365/solutions/collaborate-as-team?view=o365-worldwide

**Comment by madnata** [comment]
Yes I think this section in particular of the first article linked to works
best:
https://docs.microsoft.com/en-us/microsoft-365/solutions/collaborate-as-team?view=o365-worldwide#teams-guest-access-settings.
Thanks!

**Comment by scanum** [comment]
@madnata Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
