### ISSUE TITLE
Sip Datacenter Failover matrix does not include US as primary

### ISSUE THREAD

**Issue by tylerwb15** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6228]
The section for SIP failover includes a table matrix of secondary ant tertiary datacenters.  However US datacenter as primary is not in that matrix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e26faf8c-529e-b317-5934-cd41cfe8fa24
* Version Independent ID: 3ddd5d0a-6dbb-4940-1814-8346e293701b
* Content: [Plan Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan)
* Content Source: [Teams/direct-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @tylerwb15 Tyler, how are you? I think that is covered by "NOAM", does that makes sense to you?
Thanks

**Comment by tylerwb15** [comment]
Thank you. My mistake.
