### ISSUE TITLE
excel file available to capture the data

### ISSUE THREAD

**Issue by petermccrindle** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6231]
Has anyone ported the questionaire into excel?  If so please advise wher I can download from thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a91395-2df9-c611-9a82-e25889f97387
* Version Independent ID: c59d6141-1dc1-8e9b-3663-796d31dc6f39
* Content: [Microsoft Teams Upgrade - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/upgrade-plan-journey-discovery-questionnaire)
* Content Source: [Teams/upgrade-plan-journey-discovery-questionnaire.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-plan-journey-discovery-questionnaire.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
