### ISSUE TITLE
What features are i Public Preview

### ISSUE THREAD

**Issue by JohanssonMarkus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6233]
Hey, I want to use this for a subset of users to test public preview features. 
But I can't see a list of features in Public Preview status. 

There is a list for the Public developer preview. 
https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features

Would be good with something similar for Public Preview...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5f1cdd1-09ff-f95d-6d50-e7880d34020f
* Version Independent ID: 59219640-305b-30c1-bc10-87e2633d95db
* Content: [Public preview in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/public-preview-doc-updates?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/public-preview-doc-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/public-preview-doc-updates.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Hi @JohanssonMarkus  Thank you for your comments. I shared your feedback with our project manager. Cindy

**Comment by teamsplayer** [comment]
we will be sharing the features here https://docs.microsoft.com/en-us/officeupdates/current-channel-preview

We are still working on building the first set of feature/s that will be available with Preview launch. There is a chance that we will announce Preview but first set of features are announced in Jan 2021. Please stay tuned!

**Comment by JohanssonMarkus** [comment]
@teamsplayer thanks, do I understand it correct if I say to enable TeamsUpdateManagementPolicy (Update policies) today will have no affect at all as there is no Public Preview features surfaces today? So assign the policy will not have any effect? 
I did assign the policy yesterday but there is still no option under "About" in the teams client to enable it.

**Comment by nam31** [comment]
@JohanssonMarkus Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by JohanssonMarkus** [comment]
@nam31 seems odd to open a ticket for a new feature. I will await further public information from Microsoft.

**Comment by JohanssonMarkus** [comment]
I found this on tech community that will be my way forward.
https://techcommunity.microsoft.com/t5/microsoft-teams-public-preview/teams-public-preview-update/m-p/1903784
