### ISSUE TITLE
Number of columns required in the csv file

### ISSUE THREAD

**Issue by toffendask** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6234]
There are 15 columns listed, not 14

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200d8054-efa7-bdd3-8b13-d7d73924ecbd
* Version Independent ID: 9972bece-abf2-8f48-ba07-b8a6097602e6
* Content: [Upload tenant and building data in Call Quality Dashboard (CQD) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cqd-upload-tenant-building-data)
* Content Source: [Teams/CQD-upload-tenant-building-data.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-upload-tenant-building-data.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@toffendask  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
