### ISSUE TITLE
Confusing directions regarding cmdlets...

### ISSUE THREAD

**Issue by aamillerMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6235]
{Configure the Ringback bot](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-ringback-bot#configure-the-ringback-bot)

> Use the Set-CsOnlinePSTNGateway and New-CsOnlinePSTNGateway cmdlets together with the GenerateRingingWhileLocatingUser parameter to configure the Ringback bot.

This is confusing.  It shouldn't say to use them together.  Use the Set-* to modify an existing gateway and use New-* to create a new gateway.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a3a97bf-5eff-61a0-9bb0-f69f712fa834
* Version Independent ID: 0fbf3b06-383b-54a3-ca13-92208ed9b4bc
* Content: [Set up the Ringback bot for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-ringback-bot)
* Content Source: [Teams/direct-routing-ringback-bot.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-ringback-bot.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by dariomws** [comment]
Hi @aamillerMSFT, thank you for your feedback and help us to improve docs.microsoft.com.

The idea of that sentence is that you can use those cmdlets together with the parameter to set ringback bot. Anyway, I'm applying an improvement to the article.
