### ISSUE TITLE
Missing detail for source version information.

### ISSUE THREAD

**Issue by MatthewCKelly** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6237]
When you download the script, it is specific for only a single version..

If you update the source WIM to a more recent version it will fail. however you need the specific version to download and install.

The step it will fail on : "Your Windows installation media is version 10.0.18362.**1171**. Your SRSv2 kit requires version 10.0.18362.**418**."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/console)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by dariomws** [comment]
Hi @MatthewCKelly, thank you for your feedback.

Actually, the script does not require a specific version. It downloads the latest Teams Room System Deployment Kit and checks which media version is compatible with it. The Deployment Kit requires a specific version.

In the article, you can find the following information:
The CreateSrsMedia.ps1 script automates the following tasks:

1. Download the latest MSI installer for Microsoft Teams Rooms.
2. **Determine the build of Windows that the user must supply. The most recently released versions may or may not be tested and supported for use with Microsoft Teams Rooms devices.**
3. Download the necessary supporting components.
4. Assemble the needed components on the installation media.

**A specific version of Windows 10 is required, and this version is only available to volume licensing customers.**  You can get a copy from the [Volume Licensing Service Center](https://www.microsoft.com/Licensing/servicecenter/).

There were similar issues if you want to read more information, for example:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/1398

**Comment by nam31** [comment]
@MatthewCKelly Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
