### ISSUE TITLE
How do you export the list of numbers so you can import them into Active Directory or any other third party system?

### ISSUE THREAD

**Issue by JamesHeathcote** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6239]
There is no mechanism to export the numbers to csv so customers can import Teams Voice numbers into third party systems, such as Microsoft Active Directory!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 224b0537-e144-f5ed-6974-6e34733bceb2
* Version Independent ID: 4f1875c6-77ef-f636-669e-5f3af9691f7d
* Content: [See a list of phone numbers in your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/see-a-list-of-phone-numbers-in-your-organization)
* Content Source: [Teams/see-a-list-of-phone-numbers-in-your-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/see-a-list-of-phone-numbers-in-your-organization.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
