### ISSUE TITLE
Clarification on unit for audio time and video time

### ISSUE THREAD

**Issue by paul-lange** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6243]
Hi,

can you please clarify what unit the values "audio time" and "video time" have?
![image](https://user-images.githubusercontent.com/47522147/99682863-fe43c700-2a7f-11eb-8ae5-73077c6f896a.png)

At the top you say "We share details about screen, video, and audio minutes" but I have my doubts that these are minutes when I compare those numbers with the Power BI report for "CQD Teams Usage Report"

Regards,

Paul

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2758a3d6-c646-dcb0-2a31-c7b9b84e780b
* Version Independent ID: 8704c9fe-f8b0-82d2-bd83-3fd1a9ad638d
* Content: [Microsoft Teams user activity report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report)
* Content Source: [Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@paul-lange Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@paul-lange Hi there. Thank you for reaching out to improve MS Docs. I have investigated and found that the time is measured in minutes. Could you let me know what's reflecting on your side or if you have any other thoughts. Thanks.

**Comment by scanum** [comment]
@paul-lange We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
