### ISSUE TITLE
MTR account migration SFB onprem -> Teams

### ISSUE THREAD

**Issue by paulch7780** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6244]
[Enter feedback here]
Our documentation misses the guidance on:
1. how to move an MTR account from SFB onprem to Teams
2. how SFB onprem and Teams meetings can be accomplished on MTR at the same time
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99951587-c6ee-feb3-ab39-8d6b6969e939
* Version Independent ID: 1cb9d2e6-d4c1-628a-79bf-6ae405263f1d
* Content: [Deploy Microsoft Teams Rooms - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-deploy)
* Content Source: [Teams/rooms/rooms-deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-deploy.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@paulch7780 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@paulch7780 Thanks for reaching out. Do any of these links fit the script at all? https://docs.microsoft.com/skypeforbusiness/hybrid/move-users-from-on-premises-to-teams OR https://docs.microsoft.com/MicrosoftTeams/upgrade-to-teams-execute-skypeforbusinessonpremises OR https://docs.microsoft.com/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability

**Comment by paulch7780** [comment]
Hi Reece, the links you have pasted are applicable for normal SFB/Teams users.
MTR accounts are resource accounts, and special rules apply.
I have added the features PMs @Greg Baribault<mailto:Greg.Baribault@microsoft.com> and @Kyle Spiess<mailto:kspiess@microsoft.com> to chime in if they have such a write-up ready.
Some of my colleagues are cc, in case we need to crowdsource such additional documentation.

**Comment by scanum** [comment]
@paulch7780 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by paulch7780** [comment]
Please do not close!
What is the resolution of the 6244???
The comment I have sent before clearly say the SFB-Teams user migration is NOT the resolution.
I have attached the latest comment.
[cid:image003.jpg@01D6D1EC.1E6DAEC0]
