### ISSUE TITLE
Update to indicate disabling this feature will block guests from attending meetings

### ISSUE THREAD

**Issue by spsanders** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6246]
We noticed that the default setting for Teams meetings in our tenant was to allow anonymous join.  A review with our legal & IT security governance team all interpreted this as blocking someone from attending a meeting without any identification.  This interpretation was based on how Microsoft used the term anonymous with Teams Public Live Events where someone can select an option to join anonymously where no name, email, or phone number is required to join.

We disabled anonymous join which caused a company wide 13 hr outage where guests outside our tenant could not join Teams meetings to which they were invited.  This is was not expected because no where in the documentation does it state that external people invited to the meeting would be blocked.

Please update the documentation so others don't make this same mistake.  Add some text stating that disabling anonymous join will block invited external people from attending meetings.  Also consider a warning message in the meeting settings admin UI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Manage meeting settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@spsanders Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@spsanders thank you for reaching out and helping improve MS Docs. Suggestion for note - "If you disable anonymous (which is the default setting for Teams meetings in a tenant) it will block invited external people from attending meetings" Do you think this covers it?

**Comment by spsanders** [comment]
Hi,
Yes, thank you.

Regards,

Steve


[cid:1140cace-c1b4-4949-91bc-e135e7859667]


Steve Sanders | Advanced IT Specialist
End User Productivity

Transformation, Technologies, and Services
3M | St. Paul, MN 55144-1000 | United States
Office: +1 651 283 6265 | Mobile: +1 651 283 6265
spsanders@mmm.com<mailto:spsanders@mmm.com>



________________________________

**Comment by lindspea** [comment]
@LanaChin

**Comment by lindspea** [comment]
@nam31

**Comment by lindspea** [comment]
@nam31 please can you ask @LanaChin for check and merge
