### ISSUE TITLE
Tenant Confusion

### ISSUE THREAD

**Issue by strangepl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6247]
This article is misleading and suggests that the base URL (carrier URL) should be in a base tenant and the other subdomains can be in other client tenants THIS IS NOT THE CASE. The Base URL and the subdomain for the individual client has to be on the same tenant for you to add a 'direct route' trunk in. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure Session Border Controller - Multiple tenants - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@strangepl Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by nam31** [comment]
Closing via #6369 
Thank you
