### ISSUE TITLE
Impact of creating this policy is not clear

### ISSUE THREAD

**Issue by turnma** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6248]
Unclear if creating this policy automatically overrides the global/default policy, or if users must then be assigned to the policy.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5f1cdd1-09ff-f95d-6d50-e7880d34020f
* Version Independent ID: 59219640-305b-30c1-bc10-87e2633d95db
* Content: [Public preview in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-gb/MicrosoftTeams/public-preview-doc-updates)
* Content Source: [Teams/public-preview-doc-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/public-preview-doc-updates.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by teamsplayer** [comment]
yes policy needs to be assigned to specific users - it doesn't over-write the global

**Comment by turnma** [comment]
Thanks, that's consistent with other policies, but would be good to clarify on this docs page.

**Comment by cichur** [comment]
We updated the article by clarifying that the policy change doesn't over-write the global policy. Thank you for your feedback.
