### ISSUE TITLE
Try this

### ISSUE THREAD

**Issue by Danieloperez15** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#625]
$TeamsUpdateExePath =  "%userprofile%\AppData\Local\Microsoft\Teams"
$OSArchitecture = (Get-WmiObject Win32_OperatingSystem).OSArchitecture 
$localprofiles = Get-ChildItem -Path "C:\Users" 
Try 
{ 
    If ([System.IO.File]::Exists($TeamsUpdateExePath)) { 
        Write-Host "Uninstalling Teams process"

        # Uninstall app 
        $proc = Start-Process $TeamsUpdateExePath "-uninstall -s" -PassThru 
        $proc.WaitForExit() 
    } 
    Write-Host "Deleting Teams directory for all user profiles" 
    Get-ChildItem ‘HKLM:\Software\Microsoft\Windows NT\CurrentVersion\ProfileList’ | ForEach-Object {$profilePath = $_.GetValue(‘ProfileImagePath’) 
    Remove-Item –path "$profilePath\AppData\Local\Microsoft\Teams" -recurse} 
    
    If ($OSArchitecture -eq "64-bit") 
    { 
        msiexec /passive /x Teams_windows_x64_1.1.00.18052.msi 
     } 
    Else 
    { 
        msiexec /passive /x Teams_windows_x86_1.1.00.18052.msi 
    } 
} 
Catch 
{ 
    Write-Output "Uninstall failed with exception $_.exception.message" 
    exit /b 1 
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c642df17-1656-7c29-9fc3-04f70689f902
* Version Independent ID: 63bef712-cfb2-9efc-0b62-f68b0968b84c
* Content: [PowerShell Script Sample - Assists with Microsoft Teams Deployment Clean Up](https://docs.microsoft.com/en-us/microsoftteams/scripts/powershell-script-teams-deployment-clean-up)
* Content Source: [Teams/scripts/Powershell-script-teams-deployment-clean-up.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/scripts/Powershell-script-teams-deployment-clean-up.md)
* Service: **msteams**
* GitHub Login: @ninadara
* Microsoft Alias: **ninadara**

**Comment by kenwith** [comment]
@Danieloperez15 - thank you for engaging in the community for this! Much appreciated. I will also make note to the writer of your feedback. I will add a cross link to so anyone that lands on the issue through search sees these are related. Thanks again.

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/172
