### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by perkopperdal** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6250]
Hi.
I think ther emight be a typo in this article.
In the chapter"Permissions and role based access" it states that when a Callee initiates a 1:1 recording "Callee must share it to the Callee." 
I believe this should be "Callee must share it to the Caller."

![image](https://user-images.githubusercontent.com/48256438/99938068-5cfe8e80-2d67-11eb-907a-69edbdb970a9.png)

Best regards,
Per Kopperdal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8935e913-806f-a92c-d09e-e67df4ffd1b4
* Version Independent ID: c7a41cde-66dd-d7cd-1316-42d20ed4841a
* Content: [Use OneDrive for Business and SharePoint for meeting recordings - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/tmr-meeting-recording-change)
* Content Source: [Teams/tmr-meeting-recording-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tmr-meeting-recording-change.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Thank you @perkopperdal I made the change.
