### ISSUE TITLE
Add a note that global policy might not really be global

### ISSUE THREAD

**Issue by CoMMyCZ** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6255]
Hi,

please add a note that even though you configure a policy "Set-CsTeamsMeetingPolicy -Identity Global" your users might be using a different one. 
It is super important because MS was applying "RestrictedAnonymousAccess" in the past and changed it somehow to Global without switching the old users... See https://www.reddit.com/r/Office365/comments/gac5r6/assign_teams_orgwide_default_policy_to_all_users/ and everyone is dealing with this problem now.

A simple link to this: https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-restricted-anonymous-access
would be enough.
Also, I just spend a whole **month** with O365 support, getting diagnostics data, even network capture after someone finally figured this out...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8935e913-806f-a92c-d09e-e67df4ffd1b4
* Version Independent ID: c7a41cde-66dd-d7cd-1316-42d20ed4841a
* Content: [Use OneDrive for Business and SharePoint for meeting recordings - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/tmr-meeting-recording-change)
* Content Source: [Teams/tmr-meeting-recording-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tmr-meeting-recording-change.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
