### ISSUE TITLE
A Ajuda da MICROSOFT é a mesma coisa que ver um cachorro correndo atrás do rabo. Um loop eterno sem solução

### ISSUE THREAD

**Issue by marcosdsdba** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6256]
[Insira comentários aqui]

#A Ajuda da MICROSOFT é a mesma coisa que ver um cachorro correndo atrás do rabo. Um loop eterno sem solução
---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 143108bb-d6e6-48a8-a7cb-d11b89ebeaab
* Version Independent ID: 145773e2-149e-1c1c-5797-433c13f13b22
* Content: [Configurações de administração para aplicativos no Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/pt-br/microsoftteams/admin-settings)
* Content Source: [Teams/admin-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/admin-settings.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@marcosdsdba Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
