### ISSUE TITLE
createsrsmedia.ps1 script giving error after creating the media

### ISSUE THREAD

**Issue by ajoyrajan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6257]
I created the media and ran on the laptop which we want to use but when installing the windows, it gives an error: windows could not apply unattend settings during pass [offlineServicing].

I have tried to use it with the latest windows version and one before that. I cannot get the exact version 10.0.18362.418 from VLC portal also. happy for any advice.

**Comment by scanum** [comment]
@ajoyrajan Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
