### ISSUE TITLE
Code snippets incomplete

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6258]
I noticed that in this part
```
$acctUpn="Rigel1@contoso.onmicrosoft.com"
Set-MsolUser -UserPrincipalName $acctUpn -UsageLocation "US"
Get-MsolAccountSku
Set-MsolUserLicense -UserPrincipalName $acctUpn -AddLicenses $strLicense
```
$strLicense is not set. Maybe that was the intention at the one but last line?

Another code snippet is syntactically not correct and shows as text instead of colored code
```
``` Powershell
$rm="Rigel1@contoso.onmicrosoft.com"
Get-CsOnlineUser -Identity $rm | Select -Expand RegistrarPool

> [!NOTE]
> New user accounts might not be created on the same registrar pool as existing user accounts in the tenant. The command above will prevent errors in account setup due to this situation.
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Microsoft 365 or Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-office-365)
* Content Source: [Teams/rooms/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-office-365.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@andrePKI Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
