### ISSUE TITLE
Update Note

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6260]
In the note section:

 Note

In rare cases, changing DNS from pointing on premises to Office 365 for your organization may cause federation with some other organizations to stop working until that other organization updates their federation configuration:

Guidance should be added that the DNS update is required to update an Office 365 tenant to TeamsOnly mode on the tenant level .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ce37c7f-6f13-8442-bfdb-47065a7339b3
* Version Independent ID: 9a2b5082-369d-7c04-4fa8-81c1440ea119
* Content: [Disable hybrid to complete migration to the cloud - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/cloud-consolidation-disabling-hybrid)
* Content Source: [Skype/SfbHybrid/hybrid/cloud-consolidation-disabling-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/cloud-consolidation-disabling-hybrid.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@TheBluLion Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @TheBluLion, thank you for your feedback.

Could you kindly provide more detail? The step 1 here includes the DNS records you need to update once you move all your users to Microsoft 365.
The note is specific to companies that you are federated with.

**Comment by TheBluLion** [comment]
The Microsoft teams service now has a dependency on these DNS records being configured to point to the cloud service (in step 1) for _all_ enabled sip domains before TeamsOnly mode can be configured on a tenant level.

May we add a note or link to this article:
https://docs.microsoft.com/en-us/microsoftteams/upgrade-to-teams-on-prem-considerations

Specifically- this text should be referenced: 

Grant-CsTeamsUpgradePolicy -PolicyName UpgradeToTeams will not work at the tenant level if a lyncdiscover DNS record is detected that points to a location other than Office 365.

**Comment by dariomws** [comment]
Sorry but I'm not fully convinced to add that note in this article. I think it's a good idea in the articles that have steps to set TeamsOnly at the tenant level, as the example you referenced.

This article is about the steps to disable hybrid and the note about federation was added because these steps have an impact over it.

**Comment by scanum** [comment]
@TheBluLion Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
