### ISSUE TITLE
Latency between sending a message in Teams and it being available for export via this API

### ISSUE THREAD

**Issue by akudhingra** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6262]
Are there any guarantees that once a message is sent using a Teams client, it will be available for export through this API within x hours?

The [Security and compliance in Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/security-compliance-overview#information-protection-architecture) page has a note that says:

```
There can be up to a 24-hour delay to discover Teams content.
```

Does that imply that x in my question above is 24 hours?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eb2244d-b82d-0559-0255-ac0cb7ce05e3
* Version Independent ID: e3a7a842-7efe-40db-e3c7-da56d7b24c02
* Content: [Export content with the Microsoft Teams Export APIs - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/export-teams-content)
* Content Source: [Teams/export-teams-content.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/export-teams-content.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@akudhingra Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
