### ISSUE TITLE
Teams Trial licenses

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6264]
This article includes this sentence {"All legacy Teams Commercial Cloud Trial licenses will be automatically converted to the new offer before their trial expires." But it is not clear on the number. In my case, the client has more than 100 and when the Microsoft Teams Exploratory Trial is active it is only indicating 100 licenses are available. The article needs to be updated to stated that 'up to 100' licenses will be converted. If they have more than 100 they may have to purchase.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-exploratory)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@Jmartinez589 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
