### ISSUE TITLE
2 broken links 

### ISSUE THREAD

**Issue by Hazemrajab** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6265]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf01435-a73b-4bf2-5845-e4cf50c4c3a2
* Version Independent ID: 166e1800-80b1-2496-7160-3040c5b23c3d
* Content: [Microsoft Teams Rooms requirements - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/requirements)
* Content Source: [Teams/rooms/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/requirements.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Hazemrajab Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Hazemrajab, thank you for your feedback.

I verified all the links in the article, and it seems that all of them are working. Could you kindly detail what links are not working for you please?

**Comment by Hazemrajab** [comment]
Hi Team

Please refer to  the attached snapshots for specific details about the broked links
https://docs.microsoft.com/en-us/microsoftteams/rooms/requirements

Hope this will help

Regards


Hazem Rajab
+965 66285584

**Comment by dariomws** [comment]
Hi @Hazemrajab,

Sorry, I don't understand. What snapshots? I cannot see one.

**Comment by Hazemrajab** [comment]
Hi Dario

The screenshots showing the Specific broken links

Regards

[cid:B8E8CC3F-03EE-4989-A1A3-00D8029417D9][cid:B7A114F4-6073-4DC4-A3DC-E52E6AC2CFC1]



Hazem Rajab
+965 66285584

On Dec 3, 2020, at 7:06 PM, Dario Woitasen <notifications@github.com> wrote:

﻿

Hi @Hazemrajab<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHazemrajab&data=04%7C01%7C%7C606232f31ff34207a56908d897a56c44%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637426084019834300%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=d6pjWqUyICOgwhKZBag%2FgAS2XShZwTmebO1DqbRfpfc%3D&reserved=0>,

Sorry, I don't understand. What snapshots? I cannot see one.

**Comment by dariomws** [comment]
Sorry @Hazemrajab, I cannot see the screenshots. This is what I see:
![image](https://user-images.githubusercontent.com/33589238/101147790-95ba2580-35fb-11eb-8a88-41c31c7db5c6.png)

Could you kindly share the screenshot using GitHub? Please avoid replying the email. Thanks!

**Comment by Hazemrajab** [comment]
![image](https://user-images.githubusercontent.com/60846620/101153110-092c5900-3635-11eb-9526-83709ae69452.jpeg)

**Comment by Hazemrajab** [comment]
![image](https://user-images.githubusercontent.com/60846620/101153148-147f8480-3635-11eb-9db4-ec082bcaf730.jpeg)

**Comment by Hazemrajab** [comment]
Hi Dario

I have just uploaded them to Github , not quite sure why you wasn’t getting my attachments maybe your exchange security filtered those
Regards
Hope this will help



Hazem Rajab
+965 66285584

On Dec 4, 2020, at 12:41 PM, Dario Woitasen <notifications@github.com> wrote:

﻿

Sorry @Hazemrajab<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHazemrajab&data=04%7C01%7C%7Cdba338421369438a756908d89838ca31%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637426716954923883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dp8uxerlPqBzhXRhg4K2kF%2Fy4PeWC3HpXx0r998bc2A%3D&reserved=0>, I cannot see the screenshots. This is what I see:
[image]<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F33589238%2F101147790-95ba2580-35fb-11eb-8a88-41c31c7db5c6.png&data=04%7C01%7C%7Cdba338421369438a756908d89838ca31%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637426716954933880%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=C2xD7OTS463sEqvweexkCeI%2BmhFsck2cZr92zA04mOA%3D&reserved=0>

Could you kindly share the screenshot using GitHub? Please avoid replying the email. Thanks!

**Comment by dariomws** [comment]
Thanks @Hazemrajab! I could identify the links easily. Anyway, I tested both and they are working fine for me.

What do you get? 404?

**Comment by Hazemrajab** [comment]
![image](https://user-images.githubusercontent.com/60846620/101160750-9aed9380-3640-11eb-9e10-78371f4502e3.jpeg)


This is what I get when o clicked both , further your inputs that you. Was able to browse normally I have investigated further to discover that behavior  only happens when  I m not VPN from my both phone and laptop seems CDN issue related to kuwait or some countries (not quite sure how many other locations impacted but kuwait is for sure ) 
Since it's working from UK and us I believe you can ignore the flag then

**Comment by dariomws** [comment]
Thanks!

@scanum we can close it.

**Comment by scanum** [comment]
@Hazemrajab Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
