### ISSUE TITLE
[LOC]Back-Translation "[新規]-CsInboundBlockedNumberPattern"→"New-CsInboundBlockedNumberPattern"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6271]
Back-Translation 
　"[新規]-CsInboundBlockedNumberPattern"
　　↓　
　"New-CsInboundBlockedNumberPattern"

ja-jp:https://docs.microsoft.com/ja-jp/microsoftteams/block-inbound-calls
![block-inbound-calls_j](https://user-images.githubusercontent.com/40815708/100439161-83655680-30e6-11eb-9644-00b40446b0b6.png)

en-us:https://docs.microsoft.com/en-us/microsoftteams/block-inbound-calls
![block-inbound-calls_e](https://user-images.githubusercontent.com/40815708/100439155-806a6600-30e6-11eb-8c12-41b5426be684.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 91c40ca3-c19e-eac3-3adb-815e45ce2388
* Version Independent ID: 1193b36e-8870-aca9-cb9c-59c5fb1f5412
* Content: [Microsoft Teams で着信通話をブロックする - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/block-inbound-calls)
* Content Source: [Teams/block-inbound-calls.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/block-inbound-calls.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hyoshioka0128  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officeglobal - Could you kindly help on this issue?

**Comment by TinaMcN** [comment]
@hyoshioka0128 この問題を報告していただきありがとうございます。機械翻訳ツールの問題のようです。  私は人間の翻訳のために記事を送った。 @officeglobal 更新された記事が公開された際にお知らせください (Thank you for reporting this issue. It appears to be a problem with our machine translation tool. I sent the article to be human translated.
@officeglobal, please let us know when the updated article is published.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 this issue appears to be fixed now. Can you please verify and close if it's ok. Thanks for reporting this.

**Comment by hyoshioka0128** [comment]
@TinaMcN - Fixed. Thanks!
Closed #6271 .
