### ISSUE TITLE
Call Queue Resource Account is displayed to the agents not Call Queue's name

### ISSUE THREAD

**Issue by s-fordham** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6274]
One of the first comments for creating a call queue states:

"Type a name for the call queue. Agents will see this name when they receive an incoming call from the queue."
https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue#resource-account-and-language

In all the tests we have completed on multiple tenants the Call Queue Name is not displayed to the Agents, rather the name of the Resource Account that is linked to the call queue. So in the example of the screenshot, the name displayed to the user is **cq-sales** not the Call Queue **Contoso Sales**

![image](https://user-images.githubusercontent.com/45593412/100456720-c3154980-30b8-11eb-84ab-7857203c3789.png)

This is either a typo in the document or it is a current bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b755d9ae-13ac-019f-f5f4-a95b1eee2989
* Version Independent ID: f7afd8ad-e6e0-6c79-aed1-4ee87d48ba12
* Content: [Create a call queue in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue)
* Content Source: [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-call-queue.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
That seems strange. @CLYVR can you confirm?

**Comment by CLYVR** [comment]
Typo in the doc - seeing the RA name is the correct experience.

**Comment by MikePlumleyMSFT** [comment]
@scanum can you have someone make the update?

**Comment by scanum** [comment]
@get-itips Andres, could you help us make this update? Thanks.
