### ISSUE TITLE
COPY/PASTE Command Fails - Line Return

### ISSUE THREAD

**Issue by tictag** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6279]
On page: https://docs.microsoft.com/en-us/microsoftteams/qos-in-teams#implement-qos-in-teams-on-windows-using-powershell the COPY feature copies the text WITH a line return, which makes the command when pasted into a PowerShell terminal window fail. As a workaround, the copied command can be pasted into Notepad and the line return deleted, but this is a faff. Recommendation: delete the line return so that copy/paste works properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76c2487c-044d-1349-708a-5841fcb21ab8
* Version Independent ID: b7033454-1a9c-48d4-8004-78415c5feb89
* Content: [Implement Quality of Service in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/qos-in-teams)
* Content Source: [Teams/QoS-in-Teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/QoS-in-Teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@tictag  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
