### ISSUE TITLE
Unclear article about Scoped Directory Search in Teams

### ISSUE THREAD

**Issue by cpjopp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6284]
This Teams Scoped Directory Search article is a bit confusing and misleading.
In one section it mentions (in the “important” info box) that Address Book Policies (ABPs) in combination with Scoped Directory Search provide a logical separation of users, by limiting the search to only the scope that is defined in the ABP of a user.
However, in all other parts of the document, the article mentions that Scoped Directory Search only works with Information Barriers (IBs). 
With this it is not clear if Scoped Directory Search works with both, ABPs (if a soft/virtual segregation is required) and with IBs (if a hard segregation is required), or if it really only works with IBs.
It is clear that both, IBs and ABPs cannot be used at the same time because ABPs must be removed before IBs can be created. 
In the Teams UI the “Scoped Directory Search” switch even includes the hint to Exchange Address Book Policy, but after reading this article most people would think that Scoped Directory Search only works with IBs.
Even support cases about scoped directory search with ABPs get closed as not supported based on this article with the note that this only works with IBs.
Summary: 
If “Scoped Directory Search” really only works with IBs, we need to update the Teams UI and replace the Address Book Policy with Information Barriers, or if “Scoped Directory Search” works with both ABPs and IBs, we need to update this article and clearly state that it works with both options and explain the difference:
-	IBs hard segregation (not allowed to communicate with members of other segments)
-	ABPs soft segregation (not able to find name in Directory, but still able to communicate, if the complete user address is known)
Thanks
Claus-Peter
 ---#### Document Details⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.** ID: 84066c98-38a4-e59a-893f-da38a4a11bf3* Version Independent ID: 890a4978-0e9b-2691-a2ab-8b5512e5e76f* Content: [Use Microsoft Teams scoped directory search - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-scoped-directory-search)* Content Source: [Teams/teams-scoped-directory-search.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-scoped-directory-search.md)* Service: **msteams*** GitHub Login: @SerdarSoysal* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
