### ISSUE TITLE
Add in the ability to manage by PowerShell

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6286]
Can you mention that the update policy can also be enabled via PowerShell using the CsTeamsUpdateManagementPolicy cmdlet.

I would then recommend linking to the PowerShell reference page. but I do not think one exists yet as I cant find it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5f1cdd1-09ff-f95d-6d50-e7880d34020f
* Version Independent ID: 59219640-305b-30c1-bc10-87e2633d95db
* Content: [Public preview in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/public-preview-doc-updates?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/public-preview-doc-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/public-preview-doc-updates.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Thank you for your suggestion. I don't have the link to the PowerShell documentation, but I did add the cmdlet to the article. Cindy
