### ISSUE TITLE
Change to wording

### ISSUE THREAD

**Issue by blue-ken** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6293]
I created a call with O365 support about Meetings organized field, as Meetings organized scheduled and Meetings organized adhoc values were not adding up in the Meetings organized field. They have said that "Count of Meeting organized by all users. This is not same as meeting scheduled. If a meeting is scheduled and no body attended then that will not be counted." can this be made clearer in this page please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2758a3d6-c646-dcb0-2a31-c7b9b84e780b
* Version Independent ID: 8704c9fe-f8b0-82d2-bd83-3fd1a9ad638d
* Content: [Microsoft Teams user activity report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report)
* Content Source: [Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@blue-ken thank you for reaching out. I see the article was updated this week. Please let me know if more clarity is needed and a possible suggestion from your side. Thanks again.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
