### ISSUE TITLE
A bug in text? x64 software into (program files (x86)"?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6294]
Hi,

This text says:
"_This process installs Teams to the Program Files (x86) folder on a 64-bit operating system and to the Program Files folder on a 32-bit operating system._ "

But if I'm downloading the 64 bit version as it is possible:
![image](https://user-images.githubusercontent.com/43988151/100881290-6c43b180-34b6-11eb-91ce-6f2b7c4813ec.png)
Then isn't the correct location for 64bit software on 64bit OS on "program files" instead of "program files (x86)"?

Or have I understood again something very wrong from Windows :D

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi?fbclid=IwAR1OwrBmJgnGn5ZNr8qc4ixn8DWfKOuenkFEzXZUxomc2VFquVfuBhz5sq0#install-or-update-the-teams-desktop-app-on-vdi)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Petri-X** [comment]
I'm still unsure why I need to pay money to Microsoft to get Microsoft documentation verified/corrected? As someone of your team has been written these, so I though on the same time have connections to verify it.
