### ISSUE TITLE
Timeline expectations

### ISSUE THREAD

**Issue by BrettF-ALES** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6298]
I I didn't see a time value?
I assume 24 hours or at least overnight? 
Additionally, is there a need for the clients to completely exit & restart their desktop applications?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5f1cdd1-09ff-f95d-6d50-e7880d34020f
* Version Independent ID: 59219640-305b-30c1-bc10-87e2633d95db
* Content: [Public preview in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/public-preview-doc-updates?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/public-preview-doc-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/public-preview-doc-updates.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Thank you for your comment. I've reached out to the SME for an answer. Cindy

**Comment by teamsplayer** [comment]
hope this answers https://techcommunity.microsoft.com/t5/microsoft-teams-blog/launch-of-microsoft-teams-preview-experience-and-alignment-with/ba-p/1964899

**Comment by scanum** [comment]
@BrettF-ALES Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
