### ISSUE TITLE
Incorrect statement about Audio Conferencing licenses for India

### ISSUE THREAD

**Issue by paulbellacera** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6299]
From the doc: 
Feature | Details
-- | --
Is Audio Conferencing available for purchase? | **Microsoft doesn’t sell Audio Conferencing in India. TATA Communications offers a dial-in and dial-out service that is compatible with Microsoft Teams Meetings. For more information, please visit TATA Communications' website.**

The statement in bold is incorrect. We now offer a SKU specifically for India-based users (as of February 2020).

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: add0081a-1bc7-51fa-845b-7ed394f16bb6
* Version Independent ID: 111b52ae-0b89-6cca-372c-549f4a7055b5
* Content: [Availability in India - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-india?source=docs#feedback)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-india.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-india.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Please note:  Any changes to this article must be approved by Oscar Ruiz Garcia. There were reasons we kept the note above in the document.  Please check with Oscar before removing the note.  Copying @cichur .

**Comment by cichur** [comment]
Thank you @CarolynRowe and @paulbellacera I'll follow up with Oscar.
Cindy

**Comment by scanum** [comment]
@paulbellacera Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
Thanks @cichur @CarolynRowe. Please let me know if you have feedback from Oscar and I can do the PR.

**Comment by cichur** [comment]
Hi @lindspea and @CarolynRowe,
I've reached out to Oscar again. He is still on break. I'll follow up once I hear from him. Cindy

**Comment by lindspea** [comment]
@cichur any update yet? @CarolynRowe

**Comment by cichur** [comment]
Hi, 
I received this response from the SME:

**The existing language has been approved by CELA and it is accurate to Microsoft’s position on selling the Audio Conf. service in the country.**
