### ISSUE TITLE
Add link to troubleshooting script to docs page

### ISSUE THREAD

**Issue by m-wo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6300]
It would be great to link to the script https://github.com/OfficeDev/O365-EDU-Tools/blob/master/Teams%20Scripts/Sync-GroupMembership-To-Team.ps1 here which helped us overcome sync issues of Teams backend and client. This would have saved a lot of time searching on our own to solve this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a578ddb-6494-9bda-529e-0156e5ab7c30
* Version Independent ID: 57d519c9-90f0-873d-ffef-589f0b3b3ac9
* Content: [Overview of dynamic membership for teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/dynamic-memberships)
* Content Source: [Teams/dynamic-memberships.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/dynamic-memberships.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@m-wo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by SerdarSoysal** [comment]
@MicrosoftHeidi @MikePlumleyMSFT can you two pls review this change and advise? Not sure if directly pointing to a PS script this way is appropriate. Seems like it needs more context.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
