### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by FranNev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6301]
Hello,
I think there is a capitalization issue here:

"Attackers looking to elevate their privileges may assign themselves Owner privileges of a large number of diverse **Teams**, when, usually, users create and own a small number of **Teams** around specific topics."

It should be "Attackers looking to elevate their privileges may assign themselves Owner privileges of a large number of diverse **teams**, when, usually, users create and own a small number of **teams** around specific topics."

Because it's not about the MS product "Teams" (proper noun), but about several teams (common noun) managed through the MS Teams application.

Best regards,
François

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0157c71c-b57d-ecdf-d2de-1d6f02eaf238
* Version Independent ID: 25eae9c1-9730-a88b-066d-75e9116f389c
* Content: [Azure Sentinel and Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-sentinel-guide)
* Content Source: [Teams/teams-sentinel-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-sentinel-guide.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@FranNev Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
