### ISSUE TITLE
Complete the Proxy configuration for MTR part with Proxy PAC file usage

### ISSUE THREAD

**Issue by ccygan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6302]
Please complete the part https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-prep#proxy wchich states at #8 that Proxy PAC file could also be referenced in this registry hive.

ex.: the part Lance has written in his doc for MMR:

NOTE: If customer is using a PAC file the configuration would look like the example below
[HKEY_USERS\Skype\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings]
"MigrateProxy"=dword:00000001
"ProxyEnable"=dword:00000001
"AutoConfigURL"=http://contosoproxy.corp.net/proxy.pac

Many customers still use Proxy.PAC and the support of Proxy PAC file is lacking from our documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a711c07e-10b3-baf0-b92c-9dbcf6ab9474
* Version Independent ID: 2038cd48-44b1-1ed1-6e50-48290eef5605
* Content: [Prepare your Environment - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-prep#proxy)
* Content Source: [Teams/rooms/rooms-prep.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-prep.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ccygan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@ccygan thank you for pointing this out and helping improve MS Docs. Just for clarity are you suggesting adding the above example as the second example for number 8?

**Comment by ccygan** [comment]
Hello,
I wanted to add the part which explains the Proxy.PAC file configuration in the registry. This is to add on existing content, which is correct, but incomplete.
Chris

De : Lindsay <notifications@github.com>
Envoyé : mardi 5 janvier 2021 14:38
À : MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com>
Cc : Christophe Cygan <Christophe.Cygan@microsoft.com>; Mention <mention@noreply.github.com>
Objet : Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Complete the Proxy configuration for MTR part with Proxy PAC file usage (#6302)


@ccygan<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fccygan&data=04%7C01%7CChristophe.Cygan%40microsoft.com%7Ca932e0fbb9f54f8cfe9108d8b17f1237%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637454506624983198%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dXsoL9zmiroc0wyNNPV%2FBVxEWA9%2BJPMoE5RoDy4pBe8%3D&reserved=0> thank you for pointing this out and helping improve MS Docs. Just for clarity are you suggesting adding the above example as the second example for number 8?

-

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
