### ISSUE TITLE
Unclear settings for the room mailbox Calendar Processing

### ISSUE THREAD

**Issue by laflema** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6303]
Hi,

It should be clearly stated in the steps for configuring the CalendarProcessing settings that the -DeleteComments and -DeleteSubject parameters should be set to $false otherwise users will not be able to join Teams meetings from Surface Hubs.  Without this configured the join button does not appear on the meeting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Microsoft 365 or Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-office-365#feedback)
* Content Source: [Teams/rooms/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-office-365.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@laflema Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @laflema, thank you for your feedback and help us to improve docs.microsoft.com.

Step 3 includes all the calendar processing settings that you need to set in the room mailbox. -DeleteComments and -DeleteSubject parameters to $false are also detailed there.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
