### ISSUE TITLE
Update - Teams limit has been increased to 10,000 members

### ISSUE THREAD

**Issue by ryanmck-msft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6304]
Some of the documentation on this page still references the 5,000 member limit and needs to be updated to the 10,000 member limit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ryanmck-msft Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @ryanmck-msft, thank you for your feedback and help us to improve docs.microsoft.com.

The maximum number of members in an org-wide team is still 5,000. The maximum number of members in a team was updated from 5,000 to 10,000 on June. For more information:
https://docs.microsoft.com/microsoftteams/limits-specifications-teams
https://www.microsoft.com/en-ie/microsoft-365/roadmap?filters=&searchterms=62549

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
