### ISSUE TITLE
The Teams upload limits should be 100GB now per the SharePoint Site Limitations 

### ISSUE THREAD

**Issue by jluce512** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6306]
Per the article from the SharePoint Online Service Description [https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#file-size-and-file-path-length](url) The new online limits for SharePoint is 100gb.  This article still has it showing as 2GB?  Which is right?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by jluce512** [comment]
Why is this closed?  The Storage Limit is still wrong on the site:

This is the table from the site that needs to be changed:

[cid:image001.png@01D6D2CB.099CE6C0]


This is the SharePoint limits that have been updated for months for 100gb uploads.



Jamie Luce

Gensler
1011 South Congress
Building 1, Suite 200
Austin, Texas 78704

**Comment by dariomws** [comment]
@jluce512 the 100GB update was approved. You'll see it in docs.microsoft.com in a couple of hours. Thank you for your patience!

**Comment by jluce512** [comment]
Thanks.  I was under the impression it was fixed already.

Jamie Luce

Gensler
1011 South Congress
Building 1, Suite 200
Austin, Texas 78704
