### ISSUE TITLE
Please add a Note with (Subnet and WiFi AP are supported. Ethernet switch/port is supported on Windows 8.1 and later at this time).

### ISSUE THREAD

**Issue by salalzmo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6307]
This is KEY information when setting up direct routing and misleading when the above shows supported devices.  but only one is supported for the most common configuration. This is HUGE when an org would choose if DE911 is a fit or deploying Teams Phones. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 358dfc73-9414-13e2-4682-c3e82603692f
* Version Independent ID: 3faae1d9-efbe-c20c-6598-a5073c2306e2
* Content: [Configure dynamic emergency calling - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/configure-dynamic-emergency-calling)
* Content Source: [Teams/configure-dynamic-emergency-calling.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/configure-dynamic-emergency-calling.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @salalzmo, thank you for your feedback.

Sorry but I don't understand. Could you kindly provide more detail?

"(Subnet and WiFi AP are supported. Ethernet switch/port is supported on Windows 8.1 and later at this time)": This sentence was added 13 months ago and update 4 months ago.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
