### ISSUE TITLE
Public Preview not yet available client side

### ISSUE THREAD

**Issue by laflema** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6308]
Although the admin settings are available to create a custom update policy that allows preview features, the client does not yet provide the ability to turn on preview mode as mentioned in this blog post.

https://techcommunity.microsoft.com/t5/microsoft-teams-public-preview/teams-public-preview-update/m-p/1903784

It would be a good idea to note this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5f1cdd1-09ff-f95d-6d50-e7880d34020f
* Version Independent ID: 59219640-305b-30c1-bc10-87e2633d95db
* Content: [Public preview in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/public-preview-doc-updates)
* Content Source: [Teams/public-preview-doc-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/public-preview-doc-updates.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by teamsplayer** [comment]
hope this answers https://techcommunity.microsoft.com/t5/microsoft-teams-blog/launch-of-microsoft-teams-preview-experience-and-alignment-with/ba-p/1964899

**Comment by dariomws** [comment]
Hi @laflema and @teamsplayer, thank you for your feedback.

@laflema In the same link you shared, there is an update to let readers know that the client-side experience has been available since last Tuesday.
The official announcement was shared by @teamsplayer.

**Comment by dariomws** [comment]
@nam31 I think we can close this issue.

**Comment by laflema** [comment]
Ok great thanks.
