### ISSUE TITLE
Access to data in private channels

### ISSUE THREAD

**Issue by CarissaB117** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6309]
Regarding the use of Private channels the only comments regarding access include: 
- "Only the users on the team who are owners or members of the private channel can access the channel." and, 
- Using a power shell script to find the SharePoint sites of the private channels and channel messages. 

I cannot find any information about who has access to the list of private channel SharePoint sites. Also, is there no admin role that can view private channels at all? If only the people who have the rights to create private channels can see the channels how is a central technology service provider able to support them? Find the data? It appears to be impossible to find if you do not have the "global reader admin" role. 

Please advise on who can get access to the use of private channels within their organization.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by get-itips** [comment]
Hello @CarissaB117 

How are you? hope you are doing good.

> I cannot find any information about who has access to the list of private channel SharePoint sites.

I was able to list the private channel's sites using [Get-SPOSite](https://docs.microsoft.com/powershell/module/sharepoint-online/get-sposite?view=sharepoint-ps), as a Global Admin that hasn't access to the actual site, does that answers your question?

**Comment by get-itips** [comment]
Hello @CarissaB117 checking back to understand if you could see my last message, thanks

**Comment by CarissaB117** [comment]
Yes I received your message, thank you!

Carissa Bourdon
Records and Information Management Officer
(P) 360-706-3385 ***NEW NUMBER

“Perfection is not possible, but improvement is within everyone’s reach.”  - Edie Hedlin

**Comment by nam31** [comment]
@CarissaB117 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Comment by FixBugsFor** [comment]
I am not able to download file from private channel by Graph API following https://docs.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=http
So in post the attachment has Reference content type, but i cannot download by drive id and item id or by drive id and item path from private site

Does anyone see the same ?
