### ISSUE TITLE
No GPO settings

### ISSUE THREAD

**Issue by zebulun78** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6310]
This documentation suggests the linked ADMX template has this setting available to set as a GPO, but does not explain what that GPO setting is.  I have been unable to find the GPO setting in this ADMX template.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf54bf5d-1748-46bf-a503-5e978f56126c
* Version Independent ID: 5976a1df-52e9-eb19-fd41-c7b04fce74f8
* Content: [Sign in to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sign-in-teams#how-to-restrict-sign-in-on-desktop-devices)
* Content Source: [Teams/sign-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sign-in-teams.md)
* Service: **msteams**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by get-itips** [comment]
Hello @zebulun78 Curtis, how are you? Hope you are doing good.

I opened the admx and adml file and it seems the policy display name is

"Restrict sign in to Teams to accounts in specific tenants"

Does that helps you to find it?

Thanks

**Comment by get-itips** [comment]
Hello @zebulun78 Curis, did you see my last message? Thanks

**Comment by zebulun78** [comment]
Just saw this, thanks!  I did wind up finding it, but it would be great if the documentation named it and the path to it.

Thanks again

**Comment by get-itips** [comment]
> Just saw this, thanks! I did wind up finding it, but it would be great if the documentation named it and the path to it.
> 
> Thanks again

I am going to propose it, if it gets approval, it will be on the online version of the article. Thanks
