### ISSUE TITLE
Remove SFB Admin center from this page

### ISSUE THREAD

**Issue by StainlessSteele** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6311]
This section is in need of update https://docs.microsoft.com/en-us/MicrosoftTeams/change-the-settings-for-an-audio-conferencing-bridge#an-icon-showing-the-skype-for-business-logo--using-the-skype-for-business-admin-center as there is no "Skype for Business Admin Center" anymore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95ca1eb6-710d-5b82-e5e3-13eb1e29c28f
* Version Independent ID: 62ac8be2-18a6-b13a-4cb9-60727e05c0e7
* Content: [Change the settings for an Audio Conferencing bridge - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/change-the-settings-for-an-audio-conferencing-bridge)
* Content Source: [Teams/change-the-settings-for-an-audio-conferencing-bridge.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/change-the-settings-for-an-audio-conferencing-bridge.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by get-itips** [comment]
Thanks for your feedback @StainlessSteele Aaron.
