### ISSUE TITLE
Page not up to date in line with current menu structure

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6314]
The current help page doesn't reflect the current version of teams.  There is no 'auto-attendant' menus item under the telephone icon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afdd6102-e72f-63bb-77fc-8cfd4373e8db
* Version Independent ID: 4f073d07-8c3a-9ca9-7f16-5892953543dc
* Content: [Small business example — Set up an Auto Attendant - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/tutorial-org-aa)
* Content Source: [Teams/tutorial-org-aa.yml](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tutorial-org-aa.yml)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @chris7777au, thank you for your feedback.

Are you talking about the following option in the Admin Center?
"In the Microsoft Teams admin center, click Voice then select Auto Attendants, then click + Add"

This option is currently there in the admin center. Please let me know if I misunderstood you.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
