### ISSUE TITLE
Destination supported OS conflict

### ISSUE THREAD

**Issue by cypheredout** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6315]
This part of the page:
Target computer requirements
.NET framework 4.5 or later
Windows 8.1 or later
Windows Server 2012 R2 or later
3 GB of disk space for each user profile (recommended)

Per our Hardware requirements for Teams Page: https://docs.microsoft.com/en-us/microsoftteams/hardware-requirements-for-the-teams-app

These are the support OS's: 

Operating system | Windows 10, Windows 10 on ARM, Windows 8.1, Windows Server 2019, Windows Server 2016

In the dock it states 2012 R2 or later not 2016 or later as per the hardware dock.

can we get clarity please 💯 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Teams using Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@cypheredout Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by cichur** [comment]
Hi @dariomws 
I've followed up with the SME. One of the other SMEs is out on holiday, so I won't have an answer until January.
Cindy

**Comment by dariomws** [comment]
@cichur thanks!

**Comment by cypheredout** [comment]
Just seeing if there was any update :) 

Do you need me to reach out to anyone on it as well?

**Comment by dariomws** [comment]
@cichur

**Comment by cichur** [comment]
Hi @dariomws and @cypheredout 
I've reached out to our SMEs, and as of yesterday, they are discussing this issue. - Cindy

**Comment by cypheredout** [comment]
Hello :) Just following up!  Need me to reach out internally to anyone?
