### ISSUE TITLE
Feedback for the "How Microsoft Teams uses memory" article

### ISSUE THREAD

**Issue by YoichiroOkada** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6318]
Hi,
I think this is a great article explaining how Teams uses system memory so that user/IT Administrator/partner (e.g. OEM) are able to understand good behavior, which they don't need to worry about, and bad behavior, which they need to take care of. I would like to share some feedback to make the document more actionable.
 
- It is not clear how they need to fix an issue if they found a serious system memory issue.
>> Do we want to guide them to check memory with OEM? 

- The description "high memory use when multiple large apps are running simultaneously" is not a sign for a serious memory issue.
>> It is natural to see high memory usage if user run multiple large apps. And it is not clear what is "large apps".

- I am not sure the purpose of the screenshots, showing Windows Update process taking a lot of CPU power. Additionally, showing old Edge (not the new Edge based on Chromium) as high memory usage, 4G/5G task manager, etc. Can you replace the image?

Based on the points above, I think we might want to delete the "Symptoms of system memory issues" section so that user won't be confused by that.

- The chart in "Expected memory usage by Teams" is not clear on y-axis. And the legend is too blur to read. 

- In the "How teams works" section, we are showing the screenshot which shows Google Chrome and Teams memory usage. What is the message we want to deliver? Does this mean Chrome and Teams share memory usage? 

- If we have a link to an external website, I understand we need to make it very clear the link is not a MS site, but a 3rd party site. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc21902c-d522-3851-8587-177f01bc085c
* Version Independent ID: 590bcc64-a86d-b61e-7d94-4e4322c4e71d
* Content: [How Microsoft Teams uses memory - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-memory-usage-perf?source=docs)
* Content Source: [Teams/teams-memory-usage-perf.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-memory-usage-perf.md)
* Service: **msteams**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@YoichiroOkada Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Petri-X** [comment]
Just a regular administrator comment to this. This is good clarification for the topic, **but are these numbers still valid**? When we should start worry when Teams's memory is high. In your pictures you show that max memory for Teams is 500 MB (with 12 GB system RAM). But at the moment when looking for the Teams memory it says 1,5GB.

Also, can I read this article that Teams.exe does not care if it needs or not the RAM, it is still reserving the memory if there are available?

And have you thought about VDI users? Above "let me steal all memory even I do not need" is not the best option for VDI users.

17k votes on user voice for better code: [Teams uses 600MB and is super slow!](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/17219609-teams-uses-600mb-and-is-super-slow)

Could it be so, that Chromium is not the most optimal platform for Teams?

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
