### ISSUE TITLE
AU Availability time frame 

### ISSUE THREAD

**Issue by naylormat** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#632]
We use Skype extensively throughout our company, and relay want to bring our AU colleagues into the party on this too. 

Unfortunately Telstra will not provide us with any Call plans or Direct dials as suggested. How and when can we get hold of such though S4B Online? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f359a64f-fa0e-0a52-4470-2a279dd52f4c
* Version Independent ID: 928c9516-cfe7-0a14-4934-8ff437e29ee5
* Content: [Availability in Australia](https://docs.microsoft.com/en-us/skypeforbusiness/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-australia#feedback)
* Content Source: [Skype/SfbOnline/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-australia.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-australia.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@naylormat - thank you for submitting feedback. 

This is great to hear about Skype in your company and bringing AU on board too. I am not sure on this and want to make sure you get an answer. You might also look into upgrading to Microsoft Teams as I did just see this: https://news.microsoft.com/en-au/features/microsoft-teams-now-available-in-australia/ and how it is available in AU.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by naylormat** [comment]
Cheers ken. We are also makeing the slow transition over to teams, so good
to know.

We have an open support ticket,  but have only been provided with more
contact numbers for Telstra.. They are proving a very elusive partner to
contact.

Mat

On 3 Aug 2018 17:24, "Ken Withee" <notifications@github.com> wrote:

@naylormat <https://github.com/naylormat> - thank you for submitting
feedback.

This is great to hear about Skype in your company and bringing AU on board
too. I am not sure on this and want to make sure you get an answer. You
might also look into upgrading to Microsoft Teams as I did just see this:
https://news.microsoft.com/en-au/features/microsoft-teams-now-available-in-australia/
and how it is available in AU.

I think the best way forward is if you can open a service ticket in your
tenant so this can get resolved ASAP. Based on outcome let me know if it is
something that can be called out in the docs.

Here is a quick video on opening a ticket:
https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really
want to get this information you are discovering back into the docs.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/632#issuecomment-410305383>,
or mute the thread

**Comment by kenwith** [comment]
Thanks for feedback and I hope the support can get it resolved. If you want to email me a contact, kenwith at Microsoft.com in support I can try to help push to escalate for you too.
