### ISSUE TITLE
Teams Reports Download option

### ISSUE THREAD

**Issue by jrummer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6320]
[Enter feedback here]
Under Usage reports there's a View Reports and a Download button.  The download Button takes me to a report area that's always blank.  Can this page be updated to address that Download button and how to use it and why its blank by default.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ade1a4-092c-1132-44df-ee2c683fdd33
* Version Independent ID: 396b1aee-2f40-9895-9b00-07e38d11d31b
* Content: [Microsoft Teams analytics and reporting - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/teams-analytics-and-reports/teams-reporting-reference?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@jrummer Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @jrummer, thank you for your feedback and help us to improve docs.microsoft.com.

If you look for more detail about each report you'll find information about the download tab. For example:
https://docs.microsoft.com/microsoftteams/teams-analytics-and-reports/teams-usage-report

"You can export the report to a CSV file for offline analysis. Click **Export to Excel**, and then on the **Downloads** tab, click **Download** to download the report when it's ready."

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
