### ISSUE TITLE
Teams w/Exchange On-Premises - Outlook Contact Access

### ISSUE THREAD

**Issue by painyc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6321]
Hi,
What is the roadmap for MSFT Teams to have Outlook Contact Access within Exchange On Premises environments. This is severely limited usability factor. Imagine setting up a meeting within Teams and being required to enter every attendees email address that is outside your organization. Not very smooth, from a user experience standpoint. Please let us know.

Thank you

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
