### ISSUE TITLE
Teams capturing logs

### ISSUE THREAD

**Issue by junaidhaqqijd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6323]
The ETL files and the Skylib folder, as named, does not exist anymore in Teams.  This page needs to be updated on what files are needed to capture for logs.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d5e6d3-b7e0-d79f-0dea-ed423186a157
* Version Independent ID: ec6e68aa-552f-ab45-3c8e-92eff526b173
* Content: [Use log files in troubleshooting Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/log-files)
* Content Source: [Teams/log-files.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/log-files.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@junaidhaqqijd Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @junaidhaqqijd, thank you for your feedback and help us to improve docs.microsoft.com.

I verified this folder and files on my Windows 10 machine, and they are there:
![image](https://user-images.githubusercontent.com/33589238/102395931-87381a80-3fba-11eb-944a-70681e606231.png)
![image](https://user-images.githubusercontent.com/33589238/102396037-a767d980-3fba-11eb-94e9-2ac9fbd83024.png)

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
