### ISSUE TITLE
Keep up the great work!

### ISSUE THREAD

**Issue by andypbrowne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6326]
These documentation pages are terrific. I'm really impressed that a variety (video, and text) of content is included. Keep up the good work!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b779004c-92cd-e28c-7672-9a8d9d39103a
* Version Independent ID: 13dc2677-19e3-c5b5-5b17-11febf414e26
* Content: [Best practices for organizing teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/best-practices-organizing)
* Content Source: [Teams/best-practices-organizing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/best-practices-organizing.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback !!!
