### ISSUE TITLE
Admin mode and device management - unclear

### ISSUE THREAD

**Issue by Playajay** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6328]
Hi
Please elaborate on this section. Specifically all the types of "admin" accounts that I need. I know there is a Win10 "admin" account with default password "sfb", but what about the device admin account to access advanced settings from the MTR touch screen? Is that the same as "admin"? It's unclear. Please provide screenshots.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd52fe62-457b-c9e1-ad13-a9b1f24c9c38
* Version Independent ID: 6a8c3285-30e1-15a8-6472-f0cfe5b30e20
* Content: [Microsoft Teams Rooms maintenance and operations - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-operations)
* Content Source: [Teams/rooms/rooms-operations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-operations.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Playajay, thank you for your feedback and help us to improve docs.microsoft.com.

MTR devices are based on Windows 10. When the articles mention admin or administrator account, it could be the same account as they are referring to a local admin on the Windows 10.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
