### ISSUE TITLE
File upload limitations are out of date

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6330]
Hello,

For this article, the upload size limit per unit file in SharePoint Online remains 2 GB. 
![image](https://user-images.githubusercontent.com/13634805/101738841-14d2c080-3b0a-11eb-9eb4-02d609a47499.png)

But now it has been increased to 100GB per file in SharePoint Online side.

https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#file-size-and-file-path-length

![image](https://user-images.githubusercontent.com/13634805/101738690-db9a5080-3b09-11eb-81dd-1d68a74e6903.png)

Teams and SharePoint administrators may be different, so it would be helpful if you could update them in each article.

Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by kefujino** [comment]
This is announcement to increase file limitation for SPO/ODfB/Teams.

https://www.microsoft.com/ja-jp/microsoft-365/roadmap?filters=&searchterms=49368

> OneDrive: SharePoint/SharePoint/Teams - file upload limit up to 100GB
> 
> As requirements grow, so, too, must the content service that you depend on for your day to day content and files use. We are increasing the file upload limit in Office 365 to 100GB (up from 15GB). That means you can bring bigger files into SharePoint document libraries, OneDrive and Teams files - all based on the same, robust content store.
>

**Comment by scanum** [comment]
@kefujino Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by kefujino** [comment]
The same content as my feedback is in the list of Pull Requests.
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/6331

**Comment by get-itips** [comment]
Hello @kefujino I am into this.
Yes, that PR by @dariomws is changing it to 100 GB but I am trying to find out, as this was recently changed back to 2 GB.
Thanks

**Comment by get-itips** [comment]
PR with updated values was merged.
@kefujino Thanks
@scanum please close

**Comment by scanum** [comment]
@kefujino Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
