### ISSUE TITLE
Lack of guidance on how to assign a Direct Routing number

### ISSUE THREAD

**Issue by paulch7780** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6334]
[Enter feedback here]
This documentation and the script do not provide guidance on how to assign a PSTN Direct Routing number to the MTR account. It is unfortunate the lineuri assignment to a room is not fixed since CCE times. https://www.realtimeuc.com/2017/12/set-csmeetingroom-lineuri-error-cce/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 834f564b-d32a-25ba-437b-1cb74adbf485
* Version Independent ID: 9bdb6864-caa0-d0fa-ce06-eaaa1fd18fe3
* Content: [Configure accounts for Microsoft Teams Rooms - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-configure-accounts)
* Content Source: [Teams/rooms/rooms-configure-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-configure-accounts.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@paulch7780 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by cichur** [comment]
Hello @paulch7780, according to the SME: direct routing should work the same for room accounts as for user accounts, there is no difference between user and room at account level for voice.

**Comment by paulch7780** [comment]
This is simply not true. I have added the product owners to this thread.
Who is the SME?
As per comment here<https://social.technet.microsoft.com/Forums/en-US/556b0847-0c4e-4118-99c0-aa9981d21762/is-it-possible-to-set-a-did-pstn-number-for-a-teams-meeting-room?forum=msteams> - set-csmeetingroom does not accept onpremlineuri parameter.
You need to convert the meeting room account to a normal user (disable-csmeetingroom, assign the number and convert back).
The procedure to move the MTR account is high-level like this:

Re: Skype for Business to Teams (with phone system) on a Surface Hub - Microsoft Tech Community<https://techcommunity.microsoft.com/t5/microsoft-teams/skype-for-business-to-teams-with-phone-system-on-a-surface-hub/m-p/1538466/highlight/true#M66209>

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
