### ISSUE TITLE
How do I give explicit permissions to Faculty leaders?

### ISSUE THREAD

**Issue by zircuitz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6335]
While the documentation says that IT needs to give explicit permissions for leaders to view the insights in the Insights-app: It does not say how, or where to actually do so. This should be added to a documentation written specifically for IT-admins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3501fde1-69ef-1908-876c-4f50e90649f5
* Version Independent ID: e9c673d9-6c18-7440-da5d-cdeff4dd9b8b
* Content: [IT Admin Guide to Insights in Teams for Education - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/class-insights)
* Content Source: [Teams/class-insights.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/class-insights.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@zircuitz Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
