### ISSUE TITLE
Coming in early 2020... (Please update)

### ISSUE THREAD

**Issue by Erithano** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6336]
"Coming in early 2020" needs to be removed or updated. Especially since article was updated in nov 2020...
Thanks!

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 5f080a5c-4268-1db4-566f-f1edc27920b5
* Version Independent ID: ac556a92-58af-3e05-f53b-0fc00afc96c0
* Content: [Call and chat with users from other organizations - Microsoft Teams](https://docs.microsoft.com/sv-se/microsoftteams/communicate-with-users-from-other-organizations)
* Content Source: [Teams/communicate-with-users-from-other-organizations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/communicate-with-users-from-other-organizations.md)
* Service: **msteams**
* GitHub Login: @serdars
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@Erithano Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
