### ISSUE TITLE
[LOC]Back-Translation "航海者"→"Voyager"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6338]
Back-Translation "航海者"→"Voyager"

ja-jp: https://docs.microsoft.com/ja-jp/microsoftteams/devices/usb-devices
![usb-devices_j](https://user-images.githubusercontent.com/40815708/101979958-eccb9480-3ca4-11eb-9d8c-2caa1b81cc7e.png)

en-us: https://docs.microsoft.com/en-us/microsoftteams/devices/usb-devices
![usb-devices_e](https://user-images.githubusercontent.com/40815708/101979961-f48b3900-3ca4-11eb-8bde-61abddef05c1.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b118e0a7-1fef-feae-6c6d-e24c4485a5b9
* Version Independent ID: ae18e2db-fbbf-f30c-3c56-17dd0d2b85d1
* Content: [Microsoft Teams 用の電話とデバイス - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/devices/usb-devices)
* Content Source: [Teams/devices/usb-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/usb-devices.md)
* Service: **msteams**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@officeglobal Could you kindly help here? Thanks!

**Comment by TinaMcN** [comment]
@hyoshioka0128 this issue appears to be fixed now.  Can you please verify and close if it's ok.  Thanks for reporting this.

**Comment by hyoshioka0128** [comment]
@TinaMcN - Fixed. Thanks!
Closed #6338 .
