### ISSUE TITLE
Please Add List Of -PolicyType Names

### ISSUE THREAD

**Issue by tictag** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6339]
I recently wanted to assign a Teams App Setup Policy to a Group. I understand from this article that this can only currently be achieved via PowerShell, that's fine. The PowerShell applet (New-CsGroupPolicyAssignment) requires a -PolicyType parameter. Examples of -PolicyType are provided, such as "-Policy Type TeamsMeetingPolicy" and from https://docs.microsoft.com/en-us/powershell/module/teams/get-csgrouppolicyassignment, "-PolicyType TeamsMeetingBroadcastPolicy", but I cannot find a list of these policy types anywhere.

I wanted to assign a Teams App Setup Policy, so I tried the following at the command line:
"-PolicyType TeamsAppPolicy"
"-PolicyType TeamsAppSetup"
"-PolicyType AppSetupPolicy"
"-PolicyType TeamsApp"
"-PolicyType AppSetup"

... eventually I tried ""-PolicyType TeamsAppSetupPolicy" and this worked.

In hindsight, the policy name is reasonably intuitive but I shouldn't have to guess, I shouldn't have to trial'n'error at the command line to get something done. These policy types should be listed somewhere, and not just in the odd example scattered throughout the docs.

Please add a list of policy types, at the very least to the Get... and New... applet pages:
https://docs.microsoft.com/en-us/powershell/module/teams/get-csgrouppolicyassignment
https://docs.microsoft.com/en-us/powershell/module/teams/new-csgrouppolicyassignment

... but preferably a link too when the "-PolicyType" parameter is first mentioned in this doc.

If they are listed somewhere then you need to investigate why they are not easily accessible (_I browsed through the doc navigation and searched the docs but found nothing_), and this is feedback in an of itself.

I hope this helps.

David
mail@daveadams.me.uk

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888fe05b-1160-452f-90ba-deb19adb740f
* Version Independent ID: 4091c5e4-7a90-7fe4-2741-16bbb1f297c1
* Content: [Assign policies to your users in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/assign-policies)
* Content Source: [Teams/assign-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@tictag Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @tictag 
How are you? Hope you are doing great.

You can find different Policy Types and its corresponding PolicyType (Parameter name) in the article for [New-CsGroupPolicyAssignment](https://docs.microsoft.com/en-us/powershell/module/teams/new-csgrouppolicyassignment)
(added it myself not so long ago)

The article you opened the issue for has a note linking to that article:

> Currently, policy assignment to groups using PowerShell isn't available for all Teams policy types. See New-CsGroupPolicyAssignment for the list of supported policy types.

I can understand that, it can't be so obvious so I will propose adding the list of valid -PolicyType values to the New- cmdlet article, under the PolicyType parameter, but that is in another repository.

Thanks

**Comment by tictag** [comment]
Andres,

If you are referring to this:

[cid:image005.jpg@01D6D25C.095C81D0]

Then the second part of my feedback becomes relevant: I completely missed this and I must have visited that article at least three times. May I suggest that instead of this list of Policy Type names being in paragraph format, it might be better in a table format, maybe something like this:

-PolicyType parameter
Policy Type Name
Implemented (Y/N)
CallingLineIdentity
Caller ID policies
Yes
OnlineVoiceRoutingPolicy
Voice Routing policies
Yes
…etc
…etc


You rarely expect to see code reference material in paragraph format, I certainly didn’t see it.

Regards,
David.


[cid:image006.png@01D6D25C.095C81D0]

**Comment by get-itips** [comment]
Hello @tictag 
(can't see the image you tried to attach)
I will use a bulleted list, tables can't be used on cmdlet's article like the one for `New-CsGroupPolicyAssignment` because it will not render ok on get-help output.
Thanks

**Comment by tictag** [comment]
Andres,

I have formatted my previous email as PDF and attached. Does this work?

Regards,
David.


[cid:image002.png@01D6D262.68DE85D0]
