### ISSUE TITLE
This page has a git conflict

### ISSUE THREAD

**Issue by altwohill** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#634]
Part of the page is duplicated with &lt;&lt;&lt; HEAD and &lt;&lt;&lt; 0a230b0...
Looks like a git merge gone wrong

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d310a567-17ea-3581-2d0c-88f5ad7e9233
* Version Independent ID: 0af94ec5-fa79-5e7d-c931-13adb192ac4d
* Content: [Provisioning Skype Room System accounts in Office 365](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/provisioning-skype-room-system-accounts-in-office-365)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/provisioning-skype-room-system-accounts-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/provisioning-skype-room-system-accounts-in-office-365.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
I'm fixing the source file right now, should go live later today.
