### ISSUE TITLE
AA Report is not included in the download package

### ISSUE THREAD

**Issue by KennethMLdk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6340]
The CQD Teams Auto Attendant & Call Queue Historical Report is not included in the downloadable package from GitHub https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/downloads/CQD-Power-BI-query-templates.zip.

/Kenneth ML

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 628345c6-f5f9-fe8e-bfff-faea00a8a25c
* Version Independent ID: 30f2d051-5af5-0063-7099-38b5b08ec1e4
* Content: [Auto Attendant & Call Queue Historical Report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/aa-cq-cqd-historical-reports)
* Content Source: [Teams/aa-cq-cqd-historical-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/aa-cq-cqd-historical-reports.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@KennethMLdk Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
