### ISSUE TITLE
Sign-in tenant vs switch-to tenant?

### ISSUE THREAD

**Issue by HanzOhlo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6341]
The document describes how to prevent "sign-in" to another tenant, but also states it does not prevent "switching" to another tenant.  It's unclear what is the difference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf54bf5d-1748-46bf-a503-5e978f56126c
* Version Independent ID: 5976a1df-52e9-eb19-fd41-c7b04fce74f8
* Content: [Sign in to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sign-in-teams#how-to-restrict-sign-in-on-desktop-devices)
* Content Source: [Teams/sign-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sign-in-teams.md)
* Service: **msteams**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@HanzOhlo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @HanzOhlo 
I tested this on my lab.

Essentially, it will allow you to sign-in into the tenant you specified in the key/gpo and also switch to a tenant you have been invited as a guest (with your tenant's identity).

I won't allow you to sign-in to another tenant not specified in the registry/gpo.

Will propose improve that description.

Thanks
