### ISSUE TITLE
Markdown syntax issue

### ISSUE THREAD

**Issue by niiigoo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6342]
The link `Microsoft Teams add-on licensing` is not well formatted (missing open bracket).
Location:
 - Step 1
 - To buy and assign user Audio Conferencing licenses
 - 2. Get your Audio Conferencing licenses. If you want to:
 - Buy it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c6c2e6-a1c7-dd0c-dbe3-0072497282d5
* Version Independent ID: 1b09ca3d-f45e-5540-40b4-8c3b7176fc81
* Content: [Try or purchase Audio Conferencing in Microsoft 365 for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/try-or-purchase-audio-conferencing-in-office-365-for-teams)
* Content Source: [Teams/try-or-purchase-audio-conferencing-in-office-365-for-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/try-or-purchase-audio-conferencing-in-office-365-for-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@niiigoo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
