### ISSUE TITLE
[LOC]Fixed inappropriate japanese "才"→"18"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6344]
Fixed inappropriate japanese "才"→"18"

ja-jp: https://docs.microsoft.com/ja-jp/microsoftteams/meeting-settings-in-teams
![meeting-settings-in-teams_j](https://user-images.githubusercontent.com/40815708/102070270-3bfafc00-3e42-11eb-9c0d-087acc3c3087.png)

en-us: https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams
![meeting-settings-in-teams_e](https://user-images.githubusercontent.com/40815708/102070282-41f0dd00-3e42-11eb-900f-f9218134447e.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [会議の設定を管理する - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/meeting-settings-in-teams)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@hyoshioka0128  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@OfficeGlobal Can you kindly take a look? Thanks

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @get-itips article was HumanTranslated and published live. 
Table content is fixed now:
![image](https://user-images.githubusercontent.com/47977325/103990205-2357da80-5191-11eb-8ca2-f93ccd93dfdb.png)

**Comment by hyoshioka0128** [comment]
@OfficeGlobal  | @get-itips  - Fixed. Thanks!
Closed #6344 .
