### ISSUE TITLE
Missing info about calling rates

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6348]
Hi!

This document links to page https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/online-meetings?rtc=1#Rates from the Rates for Calling Plans section. Unfortunately looks like the destination page has changed and it no longer contains the section about calling rates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d52a9779-b72d-dea0-eac2-6c04a8c282eb
* Version Independent ID: d3c3d968-9e54-ec42-3438-9320e23d68b9
* Content: [What are Communications Credits? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/what-are-communications-credits)
* Content Source: [Teams/what-are-communications-credits.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-communications-credits.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by Larryngolog** [comment]
I think the article should link to this page https://www.microsoft.com/en-gb/microsoft-365/microsoft-teams/audio-conferencing

**Comment by scanum** [comment]
@Larryngolog  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @Larryngolog
