### ISSUE TITLE
there is not the holidays button

### ISSUE THREAD

**Issue by ysmae** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6355]
[Enter feedback here]
i cannot find the "Holidays" button in my Teams admin center.
please let me know how to find the "Holidays" button.
![Holidays](https://user-images.githubusercontent.com/76032897/102181717-b462cb00-3edd-11eb-86cc-bec53fc15376.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9908d77-78bc-ce88-ba84-4f1bd9fea504
* Version Independent ID: 37118dd4-d036-8da7-d750-4c9f503a370a
* Content: [Set up holidays in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-holidays-in-teams)
* Content Source: [Teams/set-up-holidays-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-holidays-in-teams.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@ysmae Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
