### ISSUE TITLE
I don't think the last prarghraph is acurate anymore 

### ISSUE THREAD

**Issue by basseldamra** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6358]
_The exception to this change is Microsoft Teams for Education (EDU). You can still manage Teams at the organization level if you have an EDU license. To do this, go to the Microsoft 365 admin center > Settings > Services and add-ins > Microsoft Teams. If you're using the new Teams admin center, you'll have to turn off Try the new admin center to find Services and add-ins._

The ability to turn off the new admin center is not available anymore!!

**Comment by scanum** [comment]
@basseldamra Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
