### ISSUE TITLE
not compatible with office365

### ISSUE THREAD

**Issue by kumters** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#636]
This guide is not working for office365. There is still not working federation for TEAMS...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Communicate with Teams users in another organization](https://docs.microsoft.com/en-US/MicrosoftTeams/let-your-teams-users-communicate-with-other-people?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/let-your-teams-users-communicate-with-other-people.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/let-your-teams-users-communicate-with-other-people.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
Hi @kumters - I am not fully following you on this one. From what I can understand the article is explaining how to let your Teams users in one organization communicate with Teams users in another organization or with a Skype for Business Online organization.

I am taking a guess here but maybe you are referring something different? What we can do is put our voice into User Voice to get the product team to add the feature. The place the product team monitors is called User Voice. Here is a query: https://microsoftteams.uservoice.com/forums/555103-public?query=federation

Let me know if one of these existing User Voice matches what you mean and I will up vote and provide a link here too so others can add their voice. Thanks for taking the time to provide feedback. Much appreciated.

**Comment by kumters** [comment]
Hi Ken, this documentation is saying that I can/have to add other external
partners (domains) I want to communicate to list of allowed domains.

But this option is missing for me.

__

**Comment by kenwith** [comment]
@kumters - Ok I got you now. There is same discussion here: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/461

And Jamie, who responded in there and is the PM, let us know it should be showing up as per the article. They know that people are not seeing the UI as per the article and they are checking it and last I heard they are planning to resolve today 8/8. Please let me know if it is still not showing up by today.

Also, you can open a service request ticket and they can add you to the list of people it is not showing correctly and keep you updated properly. I am just adding whatever information I happen to hear on the GitHub Issues here. I am doing the best I can but it might be better if you add your tenant to the support ticket so they can make sure you are resolved ASAP.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

**Comment by kumters** [comment]
Hi Ken, i can confirm it's working as you described.

Thank you very much.

**Comment by AndreaBarr** [comment]
@kumters  Thank you for submitting this Feedback.

From my understanding the issue of not being compatible with O365 has been resolved. If the issue is not resolved please re-open this issue.
