### ISSUE TITLE
This article needs an update ASAP! It doesn't clarify potential privacy concerns

### ISSUE THREAD

**Issue by aalejandroaraujo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6360]
[Enter feedback here]

It does not clearly differentiate between the data that is regularly collected by the Teams client versus the one that is collected in the log manual collection process.
This is, in fact, an ask from at least one of our MS main customers, whose VIPs are concerned about collecting PII info when collecting logs that could identify them or the content they share (IM messages /file names, etc...)

On the other hand, there are lots of references to Skype for Business yet (even screenshots) and not to Teams... We need Teams explicit info here, more than ever that we moved from 13M MAU to around 150M in one year!

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0e0f68-d088-d0b7-cbb7-56bb16e4026f
* Version Independent ID: 8a107028-31a6-6821-a150-1ebdd7a7d440
* Content: [Data collection practices - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/data-collection-practices)
* Content Source: [Teams/data-collection-practices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/data-collection-practices.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@aalejandroaraujo  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @aalejandroaraujo Alejandro, how are you?

The article you opened the issue for has been retired.

A new resource exists now as a starting point for this topic and users are encouraged to start with it, you can find it here https://privacy.microsoft.com/en-us/data-collection-teams

Thanks!

**Comment by tiburd** [comment]
Thank you, all!
Closing this issue.
