### ISSUE TITLE
Documentation Update - Service Accounts After Port Sometimes Can't be Assigned to Auto Attendant

### ISSUE THREAD

**Issue by amattas** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6362]
When a number is ported over and converted to a Service number it can't always be properly assigned to the auto attendant using the portal. This community post describes how to fix it and these instructions should be included in the documentation. https://answers.microsoft.com/en-us/msoffice/forum/msoffice_o365admin-mso_teams-mso_o365b/trouble-assigning-a-service-phone-number-to-a/e4dd8d50-fca7-4def-88cc-55a9af2ea61d

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a42f9e2c-aeee-76c4-620a-668cce21ba10
* Version Independent ID: 6ff06eab-9c80-9c30-95ef-c17e157fbea1
* Content: [Set up an auto attendant for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-auto-attendant)
* Content Source: [Teams/create-a-phone-system-auto-attendant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-auto-attendant.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@amattas Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting, I'll propose it and if it gets approval it will be on the published version of the article.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
