### ISSUE TITLE
Teams cloud recording says incorrect details it is Teams Async Media Services not Azure Media Services

### ISSUE THREAD

**Issue by descapa** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6366]
On this page: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md

It says in the middle of the page:

> Users won't need a Microsoft Stream license assigned if you want users to only record and download the recordings. This will mean that the recordings aren't stored in Microsoft Stream but are instead stored in Azure Media Services (AMS) with a 21-day limit before it's deleted. It's not something at this point that an admin can control or manage including the ability to delete it.

It is not stored on Azured Media Services but Teams Async Media Services.  Can we please correct this?  Thank you!

**Comment by scanum** [comment]
@descapa Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@nam please can you ask for checking and merge as PR was done 14 Jan. Thanks so much.

**Comment by nam31** [comment]
Closing via #6493 
Thank you
