### ISSUE TITLE
Incorrect information regarding PSTN usage processing

### ISSUE THREAD

**Issue by sho74** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6368]
Hi, guys
In this article it is written "The order of PSTN usages in voice routing policies is critical. The usages are applied in order, and if a match is found in the first usage, then other usages are never evaluated."
I our case we have the configuration like 
1 Calling Policy with 2 PSTN Usage records (PSTN1 and PSTN2). Each PSTN Usage record has one route ONLY:
PSTN1 -> "+1..." -> SBC1
PSTN2 -> "+...." -> SBC2
BUT we have the situation, when SBC1 is not operate by some reason and all calls to "+1... " start going through SBC2, though it shouldn't according to the article.

Is it mistake in the article or the bug in the Teams?!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d277994f-f0bb-ed3b-a94c-460c7f033abf
* Version Independent ID: 7a2b1511-a35a-18e4-611a-db0093d034b4
* Content: [Configure voice routing for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-voice-routing)
* Content Source: [Teams/direct-routing-voice-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-voice-routing.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by sho74** [comment]
Hi, Manuela
I have risen the ticket.

Waiting for resolving the issue.

Sincerely yours, Andrii
------------------------------------
Solution Architect
Microsoft Certified Trainer


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
