### ISSUE TITLE
Article contains merge information.

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#637]
This page looks like there was an unsuccessful merge in github. maybe someone could fix the contents of this translation.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2c9b7f77-061d-a224-ff1c-8d3e15d21221
* Version Independent ID: 00fa9550-c4c4-3398-ffbb-271cc724048f
* Content: [ms.lasthandoff: 03/05/2018](https://docs.microsoft.com/de-de/MicrosoftTeams/enable-features-office-365?redirectSourcePath=%252fen-us%252farticle%252fAdministrator-settings-for-Microsoft-Teams-3966a3f5-7e0f-4ea9-a402-41888f455ba2)
* Content Source: [Teams/enable-features-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.de-DE/blob/live-sxs/Teams/enable-features-office-365.md)
* GitHub Login: @olprod

**Comment by LolaJacobsen** [comment]
Thanks for the heads up, @andikrueger. This appears to be a problem in the localized version of the article, not the English-language version, so I'll contact our Localization person @samanthaw to get it fixed pronto.  Thanks again!

In the meantime, maybe the English-language version of the article will be easier for you to consume:

https://docs.microsoft.com/en-us/microsoftteams/enable-features-office-365

**Comment by kenwith** [comment]
Yes, should auto fix at next localization. Thanks all!
