### ISSUE TITLE
Teams Health

### ISSUE THREAD

**Issue by ilyongChoi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6376]
https://docs.microsoft.com/en-us/microsoftteams/sip-tester-powershell-script

I've used MicrosoftTeams sip-tester-powershell script. 
It has been working fine almost one year.
from last night, all of sudden it returned error
(Run-SIPTest : Enqueueing test...FAILED: The remote server returned an error: (429).).

have you seen this issue before? any advise?

VERBOSE: Acquiring AAD token...
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\ADAL.PS\3.19.8.1\ADAL.PS.psd1'
.
VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\ADAL.PS\3.19.8.1\Microsoft
.IdentityModel.Clients.ActiveDirectory.3.19.8\Microsoft.IdentityModel.Clients.ActiveDirectory.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\ADAL.PS\3.19.8.1\Microsoft
.IdentityModel.Clients.ActiveDirectory.3.19.8\Microsoft.IdentityModel.Clients.ActiveDirectory.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\ADAL.PS\3.19.8.1\Microsoft
.IdentityModel.Clients.ActiveDirectory.3.19.8\Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\ADAL.PS\3.19.8.1\Microsoft
.IdentityModel.Clients.ActiveDirectory.3.19.8\Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll'.
VERBOSE: Populating RepositorySourceLocation property for module ADAL.PS.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\ADAL.PS\3.19.8.1\ADAL.PS.psm1'
.
VERBOSE: Exporting function 'Get-ADALAuthenticationContext'.
VERBOSE: Exporting function 'New-ADALUserIdentifier'.
VERBOSE: Exporting function 'New-ADALClientCredential'.
VERBOSE: Exporting function 'Get-ADALToken'.
VERBOSE: Exporting function 'Clear-ADALTokenCache'.
VERBOSE: Importing function 'Clear-ADALTokenCache'.
VERBOSE: Importing function 'Get-ADALAuthenticationContext'.
VERBOSE: Importing function 'Get-ADALToken'.
VERBOSE: Importing function 'New-ADALClientCredential'.
VERBOSE: Importing function 'New-ADALUserIdentifier'.
VERBOSE: Acquiring AAD token...DONE
VERBOSE: Enqueueing test...
VERBOSE: POST https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites with -1-byte payload
**Run-SIPTest : Enqueueing test...FAILED: The remote server returned an error: (429).**
At C:\AudioCodes\TeamsTestCall\SipTesterClient.ps1:382 char:17
+ ... statusResult = Run-SIPTest $EndpointUrl $testBody $CertificateContent
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Run-SIPTest

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
