### ISSUE TITLE
https://docs.microsoft.com/ja-jp/microsoftteams/limits-specifications-teams#storage ファイル アップロードの上限 (ファイルあたり) は、2GBではなく、100GBが正しいと思料いたします

### ISSUE THREAD

**Issue by aksugiyams** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6378]
[フィードバックをこちらに入力してください]

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Microsoft Teams の制限事項と仕様 - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/limits-specifications-teams#feedback)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@aksugiyams Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@OfficeGlobal

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
