### ISSUE TITLE
Teams for Education Policy Wizard

### ISSUE THREAD

**Issue by tlstock** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6379]
[Enter feedback here]
I am following this guide but the Teams for Education Policy Wizard is not yet available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ebe30d6-2b8f-b8fd-3a22-0cbb1f7fabcb
* Version Independent ID: 99e96c91-d183-f794-0825-db150fefa7aa
* Content: [Teams for Education Policy Wizard to easily apply policies for safe learning - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/easy-policy-setup-edu?tabs=students%2Cstudent-settings)
* Content Source: [Teams/easy-policy-setup-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/easy-policy-setup-edu.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Hi @tlstock,
I've shared your comments with our SME. -Cindy

**Comment by tlstock** [comment]
Thanks so much @cichur

**Comment by cichur** [comment]
Hi @tlstock,
Thanks. 
Currently the feature is in TAP and only selected tenants have the access. The feature will be available in Jan. 
But if any tenant wants to be a part of TAP, then they can share their tenant id with us and we will enable the feature for them. 

Thanks 
Shashank

**Comment by tlstock** [comment]
Hi Shashank

We would like to be part of TAP our tenant id is 59459c4b-e3c3-452a-a12e-d99164b2de43

Thanks
Theresa
