### ISSUE TITLE
Powershell availability

### ISSUE THREAD

**Issue by ryandweaver** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#638]
Is this report or it's details available via PowerShell?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 433c52a1-5721-a082-ab60-62e49d4bf330
* Version Independent ID: b961db7c-77b3-31c8-30f7-7f984c5805c0
* Content: [PSTN usage report](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-online-reporting/pstn-usage-report)
* Content Source: [Skype/SfbOnline/skype-for-business-online-reporting/pstn-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/skype-for-business-online-reporting/pstn-usage-report.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@ryandweaver - I believe the cmdlet is: https://docs.microsoft.com/en-us/powershell/module/skype/get-cspstnusage?view=skype-ps

Also, just a note that we recently open sourced the cmdlet references and if you have guidance or ideas it would be awesome to get your knowledge back into the references. You can find out how to make edits and submit a Pull Request in the README that shows up at the bottom of the main repo: https://github.com/MicrosoftDocs/office-docs-powershell 

Also, here is the 'source' for the cmdlet above: https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsPstnUsage.md

Also, when you are in the Skype section you can filter the cmdlets that show up in 'reference' in the navigation. I did a filter for 'pstn' and there are some other cmdlets as well.

Hope that helps and thanks for feedback. Let me know if that is the correct cmdlet and I will add a reference from this article to the cmdlet (unless you want to submit a Pull Request and do it and then show up as a contributor on the article). :)

**Comment by dobby10** [comment]
The referenced get-cspstnusage powershell doesn't provide the usage report discussed in this article.  Any news on getting this?  Uservoice also has this request because the method that had existed was deprecated... https://www.skypefeedback.com/forums/299913-generally-available/suggestions/20304058-ability-to-pull-pstn-usage-report-data-from-powers
