### ISSUE TITLE
– AllowCloudRecording

### ISSUE THREAD

**Issue by O365scripts** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6383]
I wanted to point out the typo in the command to enable storage outside your expected region where an in-country stream datacenter is not present.

Before:
To enable recordings in region the Global policy, use the following cmdlet:
Set-CsTeamsMeetingPolicy -Identity Global – AllowCloudRecording $true -AllowRecordingStorageOutsideRegion $true

After:
To enable recordings in-region on the Global policy, use the following cmdlet:
Set-CsTeamsMeetingPolicy -Identity Global -AllowCloudRecording $true -AllowRecordingStorageOutsideRegion $true

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@O365scripts Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
