### ISSUE TITLE
Limitations for Guest accounts to access Live events

### ISSUE THREAD

**Issue by Bart-Hoofd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6384]
The documentation states Guest users can attend Live events; however there seems to be a limitation to this: they can only access Public live events. This is arguably non-intuitive, since guest users should be able to authenticate. 
For additional details please refer to https://microsoftteams.uservoice.com/forums/555103-public/suggestions/42253702-allow-guest-accounts-to-access-non-public-live-eve and Microsoft support ticket [Case #:22987419].

I would like to request that the documentation be updated to reflect the actual requirements for Guest users to be able to access a Live event.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-live-events/plan-for-teams-live-events#who-can-watch-live-events)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@Bart-Hoofd Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Bart-Hoofd, thank you for your feedback.

I tested it, and I think you are right. I got the following message:
"This event is in Contoso. To join, you'll need to be in that org, too."
