### ISSUE TITLE
Multi Factor Authentication and integrated Connection

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6385]
Hello,

Parameter `Credential` cannot be used when trying to connect with MFA.

I propose to change as follows:
```
#Connection to Skype for Business Online and import into Ps session
$session = New-CsOnlineSession
Import-PsSession $session

#This will also connect to Microsoft Teams
```
Reference: Tested with Module MicrosoftTeams v1.1.10-preview

I am trying to get the Username Parameter to be re-added to the Command or be able to pass the Username on like `Connect-AzureAd -AccountId $UserPrincipalName` does.

https://github.com/MicrosoftDocs/office-docs-powershell/issues/6997

Thanks,
David

PS: I am working to integrate this in my Command Connect-SkypeOnline (and Connect-Me) that establishes multiple connections in one go (with only one Authentication prompt :))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd283f6e-3865-ed70-d663-cc461ee8ba57
* Version Independent ID: 2450d311-fc04-d8b6-b4a2-b1890ec6fc3e
* Content: [Install Microsoft Teams PowerShell - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install)
* Content Source: [Teams/teams-powershell-install.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-install.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by DEberhardt** [comment]
This is a documentation issue, not a service issue.
I think the best way forward is to harmonize all documentation so that they are in sync.
Other articles are already being updated, changes being made.
https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3759
https://github.com/MicrosoftDocs/office-docs-powershell/pull/7005
