### ISSUE TITLE
Metrics for troubleshooting quality of calls for individual users.

### ISSUE THREAD

**Issue by IoannisGianko** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6386]
It would be best if there was a bit of a more detailed explanation of a good quality call standard in covering various scenarios of calls. WiFi calls, Working at home calls, one to one or conference calls.
And what are the thresholds of a good quality call?
Should I be looking at the below metrics?
 
Metric
--
Latency (one way)
Latency (RTT or Round-trip Time)
Burst packet loss
Packet loss
Packet inter-arrival Jitter
Packet reorder

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8e804b9-4194-26d7-59db-92a57ce33ee7
* Version Independent ID: 82951bb2-df67-c1f2-7153-f207357ef077
* Content: [Set up call analytics for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-call-analytics)
* Content Source: [Teams/set-up-call-analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-call-analytics.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
