### ISSUE TITLE
the 'Refer to the following blog post' link does not work

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6388]
The link in the following sentence does not work 

 Using this tool gives you access to the status of your subscribed services, active and resolved service incidents, and your Message Center communications (upcoming changes). For more information, refer to the following blog post.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d740bef-f87f-3120-a11b-8b0a9f54ebc6
* Version Independent ID: b7baaf84-dfac-cfd2-d3fa-1c130e97e926
* Content: [Operations for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/upgrade-operate-my-service)
* Content Source: [Teams/upgrade-operate-my-service.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-operate-my-service.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@nikki-c  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
