### ISSUE TITLE
Exchange 2013/2016 and UM support on Skype for Business Server 2019

### ISSUE THREAD

**Issue by MichaelLaMontagne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#639]
If a user's mailbox is homed to Exchange 2013/2016 and the UM role is installed, Voicemail will still be processed by the UM role not Cloud Voicemail when the user is moved to Skype for Business Server 2019.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72274eeb-0514-b092-55b7-dedd39e9a9c8
* Version Independent ID: 8ac96788-c9e6-9f4b-0d9f-0966bb6a012f
* Content: [Plan for Skype for Business Server and Exchange Server migration](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-um-migration#exchange-2013exchange-2016-and-skype-for-business-2015-to-exchange-2019-and-skype-for-business-2019)
* Content Source: [Skype/SfBServer2019/hybrid/plan-um-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/hybrid/plan-um-migration.md)
* Product: **skypeforbusiness-server-itpro**
* GitHub Login: @dstrome

**Comment by kenwith** [comment]
@MichaelLaMontagne - thank you for the feedback. If I am understanding correctly you are providing some guidance that can be added to the article for clarity. 

I was able to get this into the backlog for the Skype team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by cdn224** [comment]
Even Microsoft's Documentation is UNCLEAR, under this page section "What's New", there is a point made.. "...Exchange UM remains available in Skype for Business Server 2019 when you integrate Skype for Business 2019 with Exchange 2013 or Exchange 2016. Due to changes in support in Exchange 2019, Exchange UM integration is being de-emphasised in favor of Cloud Voicemail and Cloud Auto Attendant features..." and now this section of the page > "...Unified Messaging (UM) has been deprecated in Exchange 2019.." - so which is it??

**Comment by dariomws306** [comment]
Hi @MichaelLaMontagne , I understand that based on the table:

Mailbox located on Exchange 2013/Exchange 2016 - User located on Skype for Business Server 2019 - Exchange UM will process it.

Here I think it's wrong:
https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-um-migration#skype-for-business-server-2015-to-skype-for-business-server-2019-with-exchange-2013exchange-2016

Could you test it?

**Comment by dariomws306** [comment]
Hi @MichaelLaMontagne , I think if you are in SfB 2015 and Exch 2013/16 and you want to remain onprem, you can migrate to SfB 2019 and the Exchange UM service will process voicemail messages.

But if you don't need to remain onprem in the same scenario, you can migrate to SfB 2019, configure a hybrid environment and enable a hosted voicemail policy. In this case, Cloud Voicemail will process voicemail messages.

What do you think? Could you test/deploy a similar scenario?

**Comment by MichaelLaMontagne** [comment]
The original issue with this article was correct October 16, 2018: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/da5ee58d6c85f1dab645619b81fcd582774c83b2#diff-fe951518a0ab02e0503717b2d7c41245

**Comment by dariomws306** [comment]
Thank you!
