### ISSUE TITLE
which time zone is this based on?

### ISSUE THREAD

**Issue by jackvdbuk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6391]
Can you please add information on which time zone the clock is based on - i.e is this NZT or PDT or some other time zone default?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9908d77-78bc-ce88-ba84-4f1bd9fea504
* Version Independent ID: 37118dd4-d036-8da7-d750-4c9f503a370a
* Content: [Set up holidays in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-holidays-in-teams)
* Content Source: [Teams/set-up-holidays-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-holidays-in-teams.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by VladimirGluten47** [comment]
Hi Jack

My _understanding_ is that the org-wide holiday sets are time-zone agnostic. When assigned to an Auto Attendant, the holiday set is executed against the time zone configured for the Auto Attendant. So if you have a GMT +0 AA, and a GMT+10 AA, and you assign the same holiday set to both, the GMT+10 AA will close for holidays 10 hours prior to the GMT+0 AA.

Hope that helps.

**Comment by scanum** [comment]
@jackvdbuk  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @jackvdbuk, thank you for your feedback.

@VladimirGluten47 thank you for your comment. You clearly explained how it works. 

Please let us know if you have more questions.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
