### ISSUE TITLE
"How long does the Teams Exploratory experience last" section has been updated and the next 2 sections also need update

### ISSUE THREAD

**Issue by UKayo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6393]
As the updated section no longer mentions anniversary or renewal dates, the next 2 sections no longer make sense. Please update (maybe delete?) the next 2 sections.

**What happens if an end user initiates the Microsoft Teams Exploratory experience just before the anniversary or renewal date**
Microsoft Teams Exploratory experience licenses initiated within 90 days of your agreement anniversary or renewal won't be required to move to a paid license until the subsequent anniversary or renewal cycle.

**What if my agreement doesn’t have an anniversary or yearly renewal date (for example, month-to-month agreements)**
For agreements without an anniversary or yearly renewal date, the subsequent year after the first end user activates the Microsoft Teams Exploratory experience licenses will be treated as the anniversary or renewal date. Users on the Microsoft Teams Exploratory license must be converted to a paid license by that date each year, according to the policies outlined in this article.

For example, if the first end user activates Microsoft Teams Exploratory on June 19, 2020, then they and all other eligible users in the customer tenant must convert to a paid license with Teams by June 19, 2021.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-exploratory#how-long-does-the-teams-exploratory-experience-last)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
