### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by ivanja81** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6394]
Can we add our supportability statement for proxy as per our internal case 212598478. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c983a00-881a-eb3d-f047-13eda713f1a7
* Version Independent ID: f878669f-924b-0f6d-beb7-f983a1fdaeec
* Content: [Configure hybrid connectivity - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/configure-hybrid-connectivity)
* Content Source: [Skype/SfbHybrid/hybrid/configure-hybrid-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-hybrid-connectivity.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by ivanja81** [comment]
Hi

I'm a msft employee. I can give you the internal thread so you can adjust the page.

Ivan

________________________________
