### ISSUE TITLE
How in advance the features are showing when using Teams public preview ? 

### ISSUE THREAD

**Issue by jeffangama** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6396]
How in advance the features are showing when using Teams public preview ? 
Is it 30 days before general availability ?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5f1cdd1-09ff-f95d-6d50-e7880d34020f
* Version Independent ID: 59219640-305b-30c1-bc10-87e2633d95db
* Content: [Public preview in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/public-preview-doc-updates)
* Content Source: [Teams/public-preview-doc-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/public-preview-doc-updates.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Hi @jeffangama ,
I believe that features are available for preview at various durations, depending on the development cycles. 
Cindy

**Comment by jeffangama** [comment]
Thank you
