### ISSUE TITLE
Confused or even wrong description of the media flow

### ISSUE THREAD

**Issue by sho74** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6398]
Hi, Guys.
I think in the article is wrong description of media flows in the following sections:

Proxy SBC with connected downstream SBCs -> Internal user -> "The local SBC redirects the flow to the proxy SBC in Singapore and to the connected local PSTN network" (I think traffic should go From the user to Local SBC and than to the PSTN, as represented in the diagram)

The same situation in the: 
Local Media Optimization modes -> Mode 1: Always bypass -> Scenario 1. The user is in the same location as the SBC defined in the Online Voice Routing Policy (https://docs.microsoft.com/en-us/microsoftteams/direct-routing-media-optimization#scenario-1-the-user-is-in-the-same-location-as-the-sbc-defined-in-the-online-voice-routing-policy) -> "The local SBC redirects the flow to the proxy SBC in Amsterdam and to the connected local PSTN network." . I think it is also wrong like in previous example. What for Local SBC should route MEDIA traffic to the Proxy SBC and to the Phone System?! Local SBC should route Media traffic directly to the PSTN (based on this article).

Later in the "Scenario 2: The user and gateways are in different sites" (The local SBC redirects the flow to the proxy SBC in Amsterdam and to the connected local PSTN network.) it is written "The SBC in Germany redirects the flow to the proxy SBC in Amsterdam and to the connected local PSTN network." Are you sure media traffic from user will be redirected to the Proxy? In the Diagram it is not represented!

And sure please check the:
Mode 2: Only for local users -> Scenario 1. The user is in the same location as the SBC defined in Online Voice Routing Policy (https://docs.microsoft.com/en-us/microsoftteams/direct-routing-media-optimization#scenario-1-the-user-is-in-the-same-location-as-the-sbc-defined-in-online-voice-routing-policy) -> "The local SBC redirects the flow to the proxy SBC in Singapore and to the connected local PSTN network." Are you sure media traffic from local SBC will flow to the Proxy? (in diagram it is not represented)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbab466f-88f8-302a-7cda-d53bc743e831
* Version Independent ID: b5634fb3-6627-3fcd-101c-0ebc419d7b19
* Content: [Direct Routing Local Media Optimization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-media-optimization)
* Content Source: [Teams/direct-routing-media-optimization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-media-optimization.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
