### ISSUE TITLE
Monitoring Reports with SQL Always On

### ISSUE THREAD

**Issue by Lagrik** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#640]
There hasn't been an update to this note: "You're also going to need to install SQL Server Reporting Services for the Monitoring Server role, but we need you to know this isn't going to be supported with SQL Always on until post-RTM."

It's been several years since post-RTM.  Can this be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c475b5d-09ed-7f58-86d4-27f28e33ef7a
* Version Independent ID: f0ad50f3-ea93-9424-6de8-a0b778e90b23
* Content: [Server requirements for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/server-requirements)
* Content Source: [Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by kenwith** [comment]
@Lagrik - yes, good catch and thank you for taking the time to provide feedback!

I was able to get this into the backlog for the Skype team. They are currently working on the Skype for Business Server 2019 content and I will add this item you caught into the backlog. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

Also, if you would be interested to take a look at the [2019 preview docs](https://docs.microsoft.com/en-us/SkypeForBusiness/skype-for-business-server-2019) and provide feedback or make edits as Pull Request (docs are open source now) it would be greatly appreciated. If you submit a PR you will show up as a contributor but even taking time to submit feedback as an issue is greatly appreciated too.

**Comment by Lagrik** [comment]
@kenwith Do you know if it's supported yet to put the Monitoring Reports in SSRS in a SQL Always-On Availability Group and the docs just haven't been updated yet?  Or did the feature never get worked on and still not supported?

**Comment by kenwith** [comment]
@Lagrik - I wish I knew but I am not positive. What you could do to get an immediate response is to open a service request and they probably have an answer and then we could shortcut having the writing team get this on their sprint plan.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

I realize you are referring Skype for Business On Prem and if you have another way to open a service ticket and don't have O365 you could do that too.

PS - I will close this out since it is on the backlog but I just close for housekeeping. I made a note to respond here once the article gets addressed. You can also always just reply and it will auto re-open this issue.

**Comment by dariomws306** [comment]
@AndreaBarr, Ken have fixed it on Oct 3.

**Comment by NebulaMillennium** [comment]
@kenwith Sorry for opening a long closed issue - but does Skype for Business Server 2019 support SQL Server Always On Availability Groups for its monitoring reports? I see a note here from three years ago that says you will "respond here once the article gets addressed" but no further notes. And the documentation doesn't seem to have an answer for me.

**Comment by dariomws** [comment]
AlwaysOn Availability Groups is supported in Skype for Business Server 2019 including monitoring:
https://docs.microsoft.com/skypeforbusiness/plan-your-deployment/high-availability-and-disaster-recovery/back-end-server

**Comment by NebulaMillennium** [comment]
@dariomws Sorry, I know this isn't your problem, but the link you included doesn't mention the word "monitoring" anywhere. Also, this link (https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-high-availability-and-disaster-recovery/alwayson-availability-group), explicitly says this:

> Do not include the ReportServer, ReportServerTempDB, or Persistent Chat databases in the AlwaysOn Availability Group, as these are not supported in this scenario. You can include all other Skype for Business Server databases in the AlwaysOn Availability Group.

So I don't understand. From what I can see, Skype for Business Server 2019 doesn't seem to support Always On Availability Groups as an HA option for the SFB Monitoring role.

**Comment by dariomws** [comment]
@NebulaMillennium Monitoring databases are LcsCdr and QoEMetrics. So I think that only reporting services and Persistent Chat DBs are not supported.
Let me see if I can double-check this information with someone else.

**Comment by dariomws** [comment]
@cichur Do you think you can help here? Thank you!
