### ISSUE TITLE
Add Manual

### ISSUE THREAD

**Issue by brianmangan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6402]
As per support desk correspondence, there is another status called 'Manual' add it. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07fd02a2-78ae-519f-ec11-f337debcaf9a
* Version Independent ID: a2a489c3-9204-2b63-85fa-ba9e535fdc94
* Content: [What's the status of your port orders? - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/phone-number-calling-plans/port-order-status)
* Content Source: [Teams/phone-number-calling-plans/port-order-status.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phone-number-calling-plans/port-order-status.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@brianmangan  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @brianmangan, thank you for your feedback.

@tonysmit could you kindly help here? Thanks!

**Comment by dariomws** [comment]
Same as https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3961.

**Comment by dariomws** [comment]
@tonysmit could you kindly help here? Thanks!

**Comment by tonysmit** [comment]
@dariomws - I'm talking to the service guys about them updating this table. I will keep this open until I hear back from them.

**Comment by dariomws** [comment]
Hi @tonysmit, no updates here, right? Thank you!

**Comment by dariomws** [comment]
Hi @tonysmit, no updates here, right? Thank you!

**Comment by tonysmit** [comment]
I pinged the new PM on this to push him to get this updated.

**Comment by dariomws** [comment]
Hi @tonysmit, any update here? Thanks!

**Comment by scanum** [comment]
Hi @tonysmit Hope you are well. Wanted to follow up here to see if there is an update? Please let us know if there is anything we can do to help. Thanks.

**Comment by scanum** [comment]
Hi @tonysmit Hope you are well. Wanted to follow up here to see if there is an update? Please let us know if there is anything we can do to help. Thanks.

**Comment by scanum** [comment]
Hi @tonysmit Hope you are well. Wanted to follow up here to see if there is an update? Please let us know if there is anything we can do to help. Thanks.

**Comment by CarolynRowe** [comment]
There may be some confusion with manually submitting a port order:  https://learn.microsoft.com/en-us/microsoftteams/phone-number-calling-plans/manually-submit-port-order?source=recommendations.    This link is already added to the topic.  If there's still confusion, please contact the service desk.  Closing this issue.
