### ISSUE TITLE
SkypeForBusiness Powershell is being consolidated in a Teams Powershell how does this impact Teams Admin roles 

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6407]
Now that SkypeForBusiness Powershell is being consolidated in a Teams Powershell  please can you update the footers underneath the Teams Admin roles to confirm whether the roles that current have a footer of 2 will be able to run the SkypeForBusiness cmdlets from the new Teams Powershell

1 PowerShell - Skype for Business module
2 PowerShell - Microsoft Teams module
3 Microsoft Teams admin center
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b434530-6bf2-6e00-6eae-6fa043d022ce
* Version Independent ID: caab785f-e3a4-831a-87d8-26934a9f834f
* Content: [Use Microsoft Teams administrator roles to manage Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/using-admin-roles)
* Content Source: [Teams/using-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/using-admin-roles.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@nikki-c  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
