### ISSUE TITLE
Certified Device List does not line up with the devices shown in Browse devices certified for Microsoft Teams.

### ISSUE THREAD

**Issue by dw20155** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6408]
On this page it mentioned you can Browse devices certified for Microsoft Teams. and that links here: https://www.microsoft.com/en-nz/microsoft-365/microsoft-teams/across-devices/devices?rtc=1 From that link, if you click headsets then not all of the headsets listed show in the certified device list on this page. For example, the Jabra Engage 75 headset shows in that list here https://www.microsoft.com/en-nz/microsoft-365/microsoft-teams/across-devices/devices/product?deviceid=301 but is not shown on the Teams certified device list. This leads to customer confusion and lack of clarity around what is certified and what is not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b118e0a7-1fef-feae-6c6d-e24c4485a5b9
* Version Independent ID: ae18e2db-fbbf-f30c-3c56-17dd0d2b85d1
* Content: [Phones and Devices for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/usb-devices)
* Content Source: [Teams/devices/usb-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/usb-devices.md)
* Service: **msteams**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@dw20155  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @dw20155, thank you for your feedback and help us to improve docs.microsoft.com.

@dmitrykirilov @Bhavani-Ganta could you kindly help here? What are your thoughts? Thank you very much!

**Comment by dariomws** [comment]
@dmitrykirilov @Bhavani-Ganta could you kindly help here? What are your thoughts? Thank you very much!

**Comment by dmitrykirilov** [comment]
Some devices were certified earlier for Skype for Business and Lync, link of these devices is here https://docs.microsoft.com/en-us/skypeforbusiness/certification/devices-usb-devices. Jabra Engage 75 is in that list. I think both pages (Teams certified devices and SfB/Lync certified devices) point to the same Teams store https://www.microsoft.com/en-us/microsoft-teams/across-devices/devices?rtc=1 @dariomws @Bhavani-Ganta

**Comment by dariomws** [comment]
Thank you @dmitrykirilov.

@dw20155 I hope this comment answers your question. Thanks!

**Comment by dw20155** [comment]
Thanks - yes that answers the question however I still think that the Teams Store link is misleading:
https://www.microsoft.com/en-us/microsoft-teams/across-devices/devices?rtc=1

We have had a number of customers using headsets that show on the store thinking they are certified for Teams when in actual fact they are only certified for SFB. Some of these headsets had issues and the customer complained that they were certified citing that store link.

Surely it is not unreasonable to expect that the devices listed in the **Teams** Store are certified for Teams?

Perhaps the Teams Store link should either show a certified for SFB or Teams badge to make it more clear or apply a filter that only shows headsets that are actually certified for Teams.

**Comment by dariomws** [comment]
@dw20155 Even thinking it's a good idea, I don't have access to update that URL. My apologies.

@dmitrykirilov @Bhavani-Ganta I don't know if you can take this feedback or send it to another colleague. Thanks!

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
