### ISSUE TITLE
No mention of holiday overlap limitations

### ISSUE THREAD

**Issue by VladimirGluten47** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6409]
Hi,

Through trial and error today I have discovered that an Auto Attendant may not have two holiday sets assigned where the holiday sets overlap for any period of time. When this is attempted, a generic error message occurs _not_ when adding the new holiday set to the Auto Attendant, but when trying to submit final changes. Ideally a specific error message would be provided to the user, but in the meantime could you please highlight this with a warning on this page? Also on the [Set Up An Auto Attendant](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-auto-attendant#call-flows-during-holidays) page also.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9908d77-78bc-ce88-ba84-4f1bd9fea504
* Version Independent ID: 37118dd4-d036-8da7-d750-4c9f503a370a
* Content: [Set up holidays in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-holidays-in-teams)
* Content Source: [Teams/set-up-holidays-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-holidays-in-teams.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
