### ISSUE TITLE
Incomprehensible

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6410]
This article is incomprehensible on several levels. The diagrams don't match the text. The icons don't represent the devices. The IP address ranges and ports are not consistent with [Plan for Direct Routing](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan). The PSTN is missing from several diagrams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10b198f4-9576-a14d-4359-1e8cc0319cda
* Version Independent ID: ba7c3252-21d4-9be1-2a84-de2d51646f7b
* Content: [Plan for media bypass with Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan-media-bypass)
* Content Source: [Teams/direct-routing-plan-media-bypass.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan-media-bypass.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Air-Git  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Air-Git, thank you for your feedback and help us to improve docs.microsoft.com.

I've verified both articles, and this is what I conclude:

- SIP Signaling FQDNs and IP ranges appear to be the same in both articles. 
- Media IPs and ports are not the same for both scenarios, and that is represented in the articles. 
- The way the articles are is how I understand it should be.

I'll try to contact the owner of the diagrams to see if we can improve them.

Thank you again!

**Comment by dariomws** [comment]
@CarolynRowe Do you think we can improve the images here? Thanks!

**Comment by dariomws** [comment]
@CarolynRowe Do you think we can improve the images here? Thanks!

**Comment by dariomws** [comment]
@CarolynRowe Do you think we can improve the images here? Thanks!

**Comment by dariomws** [comment]
@CarolynRowe Do you think we can improve the images here? Thanks!

**Comment by dariomws** [comment]
@CarolynRowe Do you think we can improve the images here? Thanks!

**Comment by CarolynRowe** [comment]
I will add this to the backlog, but it will depend on priorities.  Closing this issue.
