### ISSUE TITLE
oppo find x2 teams have no notification, no message

### ISSUE THREAD

**Issue by carlushuang** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6412]
On my oppo find x2 phone, teams always have no notification. And now have no message update even I open teams and manually scroll down to let refresh

Teams downloaded from original oppo market ap

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0c86f401-cff4-93b3-ff69-b9787a87e644
* Version Independent ID: c0808bd3-cf63-0625-4c3c-65469c26fb3e
* Content: [在中国获取 Microsoft Teams for Android - Microsoft Teams](https://docs.microsoft.com/zh-cn/microsoftteams/get-teams-android-in-china)
* Content Source: [Teams/get-teams-android-in-china.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-teams-android-in-china.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by carlushuang** [comment]
OK, thanks
