### ISSUE TITLE
This document requies to be corrected

### ISSUE THREAD

**Issue by gautam2009live** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6413]
This document is not applicable because CreateSrsMedia.ps1 is looking for only  Windows 10 version 10.0.18362.418 In our volume licencing page the mentioned version of Windows 10 is not available for download

refering closed thread 
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4181

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/console#prepare-the-installation-media)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
