### ISSUE TITLE
This page should change to reflect the new built in Sentinel/Teams integration

### ISSUE THREAD

**Issue by oshezaf** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6414]
Azure Sentinel now has built-in Teams connector, so that the Logic App described here is not needed anymore. The built-in connector is documtned here: https://docs.microsoft.com/en-us/azure/sentinel/connect-office-365

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0157c71c-b57d-ecdf-d2de-1d6f02eaf238
* Version Independent ID: 25eae9c1-9730-a88b-066d-75e9116f389c
* Content: [Azure Sentinel and Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-sentinel-guide)
* Content Source: [Teams/teams-sentinel-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-sentinel-guide.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
