### ISSUE TITLE
Will members receive welcome emails?

### ISSUE THREAD

**Issue by dogfrog1970** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6415]
It would be good to understand whether users will receive welcome emails to the Team as they are added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a578ddb-6494-9bda-529e-0156e5ab7c30
* Version Independent ID: 57d519c9-90f0-873d-ffef-589f0b3b3ac9
* Content: [Overview of dynamic membership for teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/dynamic-memberships)
* Content Source: [Teams/dynamic-memberships.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/dynamic-memberships.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
