### ISSUE TITLE
Incorrect Audio Conferencing Dial-Out Minutes, we get 60mins per Audio conferencing and we have mention 900 mins.

### ISSUE THREAD

**Issue by Sagamare** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6416]
We have mention in below article : "All 115 users share a pool of (115 users X **900 min**)"
https://docs.microsoft.com/en-us/microsoftteams/complimentary-dial-out-period#complimentary-dial-out-period-details 

If we refer the article https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-subscription-dial-out#how-are-minute-pools-calculated we give 60min for DialOut. 

Kindly correct the changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be7b92a3-be5b-fd38-fb9e-7811212386fa
* Version Independent ID: da10315a-a190-4433-1e82-d22aef8ef1a0
* Content: [Complimentary dial-out period - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/complimentary-dial-out-period#complimentary-dial-out-period-details)
* Content Source: [Teams/complimentary-dial-out-period.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/complimentary-dial-out-period.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
