### ISSUE TITLE
Tasks in Teams missing in Outlook

### ISSUE THREAD

**Issue by cil96tm3** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6418]
Hi, 

Before when i created a task in Teams the task appeared in outlook. 
Now the task can´t be found in Outlook but is only found in Microsoft-To-Do. 
I´m missing this alot!

BR Michel

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27c4aab7-6115-ff27-5538-0a0bf73755de
* Version Independent ID: 3ff038fc-da4d-fdf4-7b5b-071bd25e3047
* Content: [Manage the Tasks app for your organization in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-tasks-app)
* Content Source: [Teams/manage-tasks-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-tasks-app.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
