### ISSUE TITLE
#6416 was closed.

### ISSUE THREAD

**Issue by Sagamare** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6419]
I see my previous feedback request was closed with following statement :

"Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content."

Please note, I am FTE with Microsoft and this is not an issue with my tenant, the article has incorrect information which needs to be updated.

**Comment by scanum** [comment]
@Sagamare Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Sagamare, thank you for your feedback and help us to improve docs.microsoft.com.

These two articles contain different topis but related:

- One of them is related to the complimentary dial-out period. It ended on November 30, 2019, and included 900 minutes per user per month.
- The other is related to the "Dial-Out/Call Me At" minutes benefit. It began on December 1, 2019, and includes 60 minutes per user per month.

**Comment by dariomws** [comment]
@scanum I think we can close this issue. Thank you!

**Comment by dariomws** [comment]
If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=Sagamare

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
