### ISSUE TITLE
Add version numbers

### ISSUE THREAD

**Issue by jascox19** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6421]
While the dates are great for the updates, many people would appreciate the version number attached to each update. The release notes are not fully helpful if the version that correlates with the release are not also published.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5eedcae-036a-4e99-e47f-9e2503b667b2
* Version Independent ID: 3914f6ac-352c-8654-0d84-77bc066a734c
* Content: [Release notes for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/release-notes/release-notes)
* Content Source: [Teams/release-notes/release-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/release-notes/release-notes.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@jascox19 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by earthsound** [comment]
It would be nice to see versions, feature introductions, and issue resolution in Teams similar to what is provided for [Teams Rooms](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-release-note).

**Comment by earthsound** [comment]
The [most recent support article about what's new in Teams](https://support.microsoft.com/en-us/office/what-s-new-in-microsoft-teams-d7092a6d-c896-424c-b362-a472d5f105de) doesn't have version numbers for Desktop/Web, iOS, or Android but does for Desk phones and Teams Rooms on Android.

**Comment by dariomws** [comment]
Hi @jascox19 @earthsound, thank you for your feedback and help us to improve docs.microsoft.com.

These are admin features, and I'm not sure if there are public version numbers assigned to them. Anyway, I'll pass your feedback to the product team because it's not the first time we receive a request to add version numbers to the client features article.

Thank you again!

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
