### ISSUE TITLE
reopen issue 3576

### ISSUE THREAD

**Issue by codelux** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6422]
Can someone please take a look at this issue? It was closed with no action taken:

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3576

**Comment by scanum** [comment]
@codelux Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @codelux, thank you for your feedback and help us to improve docs.microsoft.com.

SSL.com was added on Mar 25, 2020, to the list:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/29bce22fcbdafaa356e9e55371bf0a7b91ab5ecf

Please let me know if I misunderstood you.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
