### ISSUE TITLE
Phone System is also supported in islands mode

### ISSUE THREAD

**Issue by IoannisGianko** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6428]
[Enter feedback here]
So quoting the below from this page.

_"Phone System and PSTN connectivity options
Phone System with Teams is supported after the user is in TeamsOnly mode. (If the user is in Islands mode, Phone System is only supported with Skype for Business.)"_

I'd like to clarify that if the user is in islands mode then the phone system is also supported on the Teams client as well. At least that's what we've got in our enterprise setup.

Hope that makes sense, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e763c267-2c3a-190d-29e2-b5c81448fc10
* Version Independent ID: 98b73595-54ea-503c-ac3c-9df176543e9e
* Content: [Upgrade from Skype for Business Online to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/upgrade-to-teams-execute-skypeforbusinessonline)
* Content Source: [Teams/upgrade-to-Teams-execute-SkypeforBusinessOnline.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-to-Teams-execute-SkypeforBusinessOnline.md)
* Service: **msteams**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@IoannisGianko Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @IoannisGianko, thank you for your feedback.

I think the article is accurate. When a user is in islands mode, calls and instant messages from federated accounts are routed to Skype for Business. For more information, see:
https://docs.microsoft.com/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability#islands-mode

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
