### ISSUE TITLE
Is the version of 10.0.18363.418 a typo for the MTR OS build requirement?

### ISSUE THREAD

**Issue by kristofftan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6429]
During my installation of MTR: SRSDeploymentKit-4.7.15.0, it always prompt a warning my OS version (10.0.18363.418) is not meet the MTR requirement.

Then I found that The latest Teams Room System MSI: SRSDeploymentKit-4.7.15.0 actually require OS Build is 10.0.18362.418, and this should be limited through below JSON:
 
C:\temp\Skype Room System Deployment Kit\$oem$\$1\Rigel\x64\Scripts\Provisioning\config.json
"MediaVersion":"10.0.18362.418"

Then, my question is that below page is always not mention this OS build(10.0.18362.418), but a 10.0.18363.418, is this a typo?

URL:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-lifecycle-support.md

**Comment by scanum** [comment]
@kristofftan Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
