### ISSUE TITLE
Secure by default

### ISSUE THREAD

**Issue by paulch7780** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6431]
[Enter feedback here]
I suggest to change the wording. Security is a definition in a given environment. For example, some companies may choose to add MTR to a domain, not change the default user password, connect the device straight to the internet without security auditing/additional pre-caution. Security is the responsibility of the customer. Maybe stating: MTR device has security preparations built-in or similar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa81c0c7-1f2d-09ed-da2d-298aba689e56
* Version Independent ID: 73fd96c0-2b94-d7ea-f900-e88b84344bdd
* Content: [Microsoft Teams Rooms Security - Microsoft Teams](https://review.docs.microsoft.com/en-us/microsoftteams/rooms/security?branch=dstrome-mtr-security)
* Content Source: [Teams/rooms/security.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/security.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @paulch7780, thank you for your feedback and help us to improve docs.microsoft.com.

@dstrome, could you kindly help me here? I think this article is not yet public. Thanks!

**Comment by dariomws** [comment]
@paulch7780 are you suggesting to change the wording in all the article or a specific section?

**Comment by dariomws** [comment]
@paulch7780 are you suggesting to change the wording in all the article or a specific section? Thanks!

**Comment by paulch7780** [comment]
It's alright, you can close

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
