### ISSUE TITLE
endpoint security software

### ISSUE THREAD

**Issue by paulch7780** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6432]
Comment on this statement:
_Even though end users can't put files on a Teams Rooms hard drive, Microsoft Defender is still enabled. Teams Rooms performance is tested with Microsoft Defender. Disabling this or adding additional endpoint security software can lead to unpredictable results and potential system degradation._

Some customers have Microsoft Endpoint Manager and central configuration they would like to push to those devices.
Some customers have competing Anti-Virus products - do we say those are unsupported?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
