### ISSUE TITLE
HW/Chipset Security

### ISSUE THREAD

**Issue by paulch7780** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6433]
Given the recent news around Intel chipset security flaw it might be worth mentioning how MTR is protected from [such ](https://techxplore.com/news/2020-03-unfixable-flaw-intel-chipset.html#:~:text=The%20bad%20news%3A%20A%20security,install%20malware%20such%20as%20keyloggers.)incidents.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by paulch7780** [comment]
Hi Manuela, not sure if 6432 and 6433 were associated with the right section of the documentation<https://review.docs.microsoft.com/en-us/microsoftteams/rooms/security?branch=dstrome-mtr-security>, I actually provided this feedback based upon the feature PM (Kyle Spiess MTR PM who created the doc) ask.
6432 and 6433 should be treated as 6434&6435 and are relevant.
Please let me know if I have to recreate them.
Paul
