### ISSUE TITLE
MTR and Microsoft 365 network connectivity principles

### ISSUE THREAD

**Issue by paulch7780** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6434]
[Enter feedback here]
Feedback on this statement:

_Generally, Teams Rooms has the same network requirements as any Microsoft Teams client. Access through firewalls and other security devices is the same for Teams Rooms as for any other Microsoft Teams client. Specific to Teams Rooms, the categories listed as "required" for Teams must be open on your firewall. Teams Rooms also needs access to Windows Update and Microsoft Store. For the full list of IPs and URLs required for Microsoft Teams Rooms, see:_

This does not completely match our O365 URL/IP category guidance published [here](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-network-connectivity-principles?view=o365-worldwide).

And specifically:

In our previous guidance for managing Microsoft 365 traffic, endpoints were organized into two categories, Required and Optional. Endpoints within each category required different optimizations depending on the criticality of the service, and many customers faced challenges in justifying the application of the same network optimizations to the full list of Office 365 URLs and IP addresses.

In the new model, endpoints are segregated into three categories, Optimize, Allow, and Default, providing a priority-based pivot on where to focus network optimization efforts to realize the best performance improvements and return on investment. The endpoints are consolidated in the above categories based on the sensitivity of the effective user experience to network quality, volume, and performance envelope of scenarios and ease of implementation. Recommended optimizations can be applied the same way to all endpoints in a given category.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa81c0c7-1f2d-09ed-da2d-298aba689e56
* Version Independent ID: 73fd96c0-2b94-d7ea-f900-e88b84344bdd
* Content: [Microsoft Teams Rooms Security - Microsoft Teams](https://review.docs.microsoft.com/en-us/microsoftteams/rooms/security?branch=dstrome-mtr-security)
* Content Source: [Teams/rooms/security.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/security.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by kdspiess** [comment]
Thanks for the feedback Paul.  My understanding is that these new categories are defined where customers can focus their efforts to optimize traffic on between the services and the different endpoints.  I still think our statement of all the "required" addresses should be open to the firewall, but within each of these "required" addresses, there are the new categories on where admins have more flexibility to optimize the network performance for the scenarios.

**Comment by dariomws** [comment]
@paulch7780 If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=npherson

@kdspiess It seems that the article does not exist or I don't have access. If you need help with it, please let me know. Thanks!

**Comment by paulch7780** [comment]
Converted my account, thanks for the hint.
Dario, are you saying you cannot access: https://review.docs.microsoft.com/en-us/microsoftteams/rooms/security?branch=dstrome-mtr-security#network-security ?

**Comment by paulch7780** [comment]
Thank you, Kyle. Required may indeed be a good "tag".
Are we sure we only need Teams required, do we also need EXO?

Specific to Teams Rooms, the categories listed as "required" for Teams must be open on your firewall.

**Comment by dariomws** [comment]
Hi @paulch7780,

I don't have access because I don't have a Microsoft account. I'm a member of a team of freelancers technical writers helping to improve docs.microsoft.com.

I think @dstrome can help you.

Thanks!

**Comment by dariomws** [comment]
@paulch7780 now this article is public, and I can see it.

It seems that this issue can be closed and the other you opened as all of them were fixed or answered. Are you agree?

**Comment by dariomws** [comment]
@scanum I think we can close this issue. Thank you!

**Comment by paulch7780** [comment]
Hi Dario, please do not close the issue. We have customer feedback on this specific point and a side conversation with Kyle + Paul.

**Comment by dariomws** [comment]
Ok, don't worry @paulch7780, we can keep it open. Please keep us posted on the resolution to feed whatever information you discover into the content.

Thank you!

**Comment by dariomws** [comment]
@scanum please keep it open. Thank you!

**Comment by dstrome** [comment]
Stale issue. Closing.
