### ISSUE TITLE
Intune URLs/IPs

### ISSUE THREAD

**Issue by paulch7780** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6435]
[Enter feedback here]
Feedback on the following sentence:

_Teams Rooms also needs access to Windows Update and Microsoft Store. For the full list of IPs and URLs required for Microsoft Teams Rooms, see:_

Do the [URLs/IPs for Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/intune-endpoints) need to be mentioned as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa81c0c7-1f2d-09ed-da2d-298aba689e56
* Version Independent ID: 73fd96c0-2b94-d7ea-f900-e88b84344bdd
* Content: [Microsoft Teams Rooms Security - Microsoft Teams](https://review.docs.microsoft.com/en-us/microsoftteams/rooms/security?branch=dstrome-mtr-security)
* Content Source: [Teams/rooms/security.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/security.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @paulch7780, thank you for your feedback and help us to improve docs.microsoft.com.

@dstrome, could you kindly help me here? I think this article is not yet public. Thanks!

**Comment by dariomws** [comment]
Hi @paulch7780, thank you for your feedback.

Intune was added 1 month ago.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
