### ISSUE TITLE
Teams Meeting Numbers incorrect

### ISSUE THREAD

**Issue by thewrabbit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6438]
https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#meetings-and-calls

Feature | Maximum limit
-- | --
Number of people in a meeting (can chat and call in) | 350

This is incorrect.  It was announced it was increasing to 350 from 250 but this was changed and meetings were only increased to 300.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#meetings-and-calls)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by SerdarSoysal** [comment]
Thank you for the feedback. Fixed. https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/6449
