### ISSUE TITLE
Conflicting docs

### ISSUE THREAD

**Issue by roberts2727** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6441]
This blog post last July announced support for 1000 users in a teams meeting. Your documentation still reflects 350.

https://www.microsoft.com/en-us/microsoft-365/blog/2020/07/08/reimagining-virtual-collaboration-future-work-learning/?ranMID=24542&ranEAID=kXQk6*ivFEQ&ranSiteID=kXQk6.ivFEQ-ln6wYqqomhYHDXazgOFpTg&epi=kXQk6.ivFEQ-ln6wYqqomhYHDXazgOFpTg&irgwc=1&OCID=AID2000142_aff_7593_1243925&tduid=%28ir__gswxu0nr1ckftwbpkk0sohzgcu2xsfofruqx0jld00%29%287593%29%281243925%29%28kXQk6.ivFEQ-ln6wYqqomhYHDXazgOFpTg%29%28%29&irclickid=_gswxu0nr1ckftwbpkk0sohzgcu2xsfofruqx0jld00

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by SerdarSoysal** [comment]
Thank you for your feedback. The 1000 users in a Teams meeting has not yet shipped. It is coming soon. When it's publicly available, we will update this page.
