### ISSUE TITLE
Minimum permissions to access these reports?

### ISSUE THREAD

**Issue by dotnick365** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6446]
This article states that Global Admin or Teams Service Admin are required to access these reports.

However, the page here: https://docs.microsoft.com/en-us/microsoftteams/teams-activity-reports#who-can-access-the-teams-activity-reports

Seems to indicate that Reports Reader role will also allow access to these reports. Can we clarify which is correct? Or what the distinction between Reports Reader can access vs what Teams Service Admin can access from a usage and reporting perspective?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ade1a4-092c-1132-44df-ee2c683fdd33
* Version Independent ID: 396b1aee-2f40-9895-9b00-07e38d11d31b
* Content: [Microsoft Teams analytics and reporting - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-reporting-reference)
* Content Source: [Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@dotnick365 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @dotnick365, thank you for your feedback.

Reports Reader role has access to the reports in the Microsoft 365 admin center. This role doesn't have access to reports in the Teams admin center.

In the Microsoft 365 admin center you only have the user and devices activity reports. In the Teams admin center, you have the user and device activity reports and more reports like PSTN. This information is included in both articles.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
