### ISSUE TITLE
Scheduling meetings in private channels

### ISSUE THREAD

**Issue by itishnitsa** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6450]
Hello,

I see the wording has been removed about private channels lack of support for scheduling meetings...and there is now a 'schedule meeting' button available in the private channels...BUT, the feature doesn't work. Private channels still do not appear in the Channel list on the meeting scheduling page. Is this a bug or documentation issue?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by itishnitsa** [comment]
Hi,

A Microsoft engineer found another article stating that meeting scheduling is still not supported in Private channels. It would be great to have this information on the private channel documentation under limitations again (it used to be stated).
“This feature isn't available in private channels.”

https://support.microsoft.com/en-us/office/schedule-a-meeting-in-teams-943507a9-8583-4c58-b5d2-8ec8265e04e5

Thanks,
Tanya
