### ISSUE TITLE
Version history is old

### ISSUE THREAD

**Issue by cchambers-cap** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6452]
This documentation only includes versions up to 1.1.7 (preview) the latest version is 1.1.10 (preview). There is no documentation on the changes made after 1.1.7.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 173b5929-529b-938b-b6ab-59f05a5d69a8
* Version Independent ID: 0a3dfe5e-938f-933d-637e-b7449e3b8aa5
* Content: [Microsoft Teams PowerShell Release Notes - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes)
* Content Source: [Teams/teams-powershell-release-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-release-notes.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
@cchambers-cap Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @cchambers-cap, thank you for your feedback.

I'll try to get more information about the latest 3 preview versions.

@brandber @rajgodwin @pupara could you kindly help? Thanks!

**Comment by dariomws** [comment]
@brandber @rajgodwin @pupara could you kindly help? Thanks!

**Comment by dariomws** [comment]
@cchambers-cap this article is now up to date. Thank you for your feedback.

@scanum could you kindly close it? Thanks!

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
