### ISSUE TITLE
Shifts app - Deep link to open specific team shift

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6455]
We are able to open Shift app using following deeplink:
microsoftTeams.executeDeepLink('" https://teams.microsoft.com/l/entity/" + shiftsAppId + "/schedule');

Is it possible to open specific team shift using deep link by passing subEntityId? I tried by passing Team id/group id and not working.

**Comment by scanum** [comment]
@SubbaReddi Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
