### ISSUE TITLE
Add optional step to create a Contact Object

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6456]
Hello,

Following from https://github.com/MicrosoftDocs/office-docs-powershell/issues/7016, I propose to add a step to create a contact object to capture a name for the Analog device as well as a potential Extension.
Instructions to creating an object, assigning PhoneNumber and making it visible in the Address book

As far as I know this can be achieved by doing this:
```
$Name = "Analog Contact Object"
$Number = "+15551234567"
$LineUri= "tel:" + $Number + ";ext=567"
$EmailAddress = $Number + "@domain.com"
New-MailContact -Name "$Name" -ExternalEmailAddress $EmailAddress
Set-Contact -Identity "$EmailAddress" -Phone $LineUri
#or Set-Contact -Name $Name -Phone $LineUri # don't know 100% and cannot try right now, but will verify
```
Unknown to me are the required steps (if any) to make it visible in the Address book.
A note needs to be added that this requires a connection to the Exchange Management PowerShell

If there is any other way to achieve this, please let me know, I have a requirement currently to do this in a scalable fashion for multiple hundred Analog devices.

Thank you,
David
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea0bc170-d9d9-c17a-adc8-d37cb5fe3df5
* Version Independent ID: 3c761043-bea5-0cfb-d85e-13671ed0fe9a
* Content: [Direct Routing - Connecting analog devices - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-analog-devices)
* Content Source: [Teams/direct-routing-analog-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-analog-devices.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by lindspea** [comment]
@DEberhardt thank you for reaching out. I see the article was updated yesterday. Please let me know if you have any more questions that need clarification.

**Comment by DEberhardt** [comment]
Hello, 
I checked the online article as well as the github entry, but I cannot find a change that would pertain to the issue raised...
Can you elaborate on this or point me to the diff?
Thanks,
David

**Comment by DEberhardt** [comment]
Information on how to create an Analog Device for use in Teams is still appreciated.

**Comment by lindspea** [comment]
@DEberhardt I see there is another related issue that you opened- https://github.com/MicrosoftDocs/office-docs-powershell/issues/7016 and that you have reached out to user voice which I think is the best thing for now. I'm still doing some investigating with the team but I'm still unable to find more information at the moment, but please let me know if your issue gets resolved. Chat soon.

**Comment by scanum** [comment]
@DEberhardt Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
