### ISSUE TITLE
Teams Setup for Surface Hub S2

### ISSUE THREAD

**Issue by Unknown-Mich** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6465]
[Hello,

I am having trouble setting up the Teams
I am stuck at this part:
"Make Teams the default calling and meetings application
There are two options for configuring the default calling and meetings application policy:

Option 1: Configure via USB key.
Option 2: Configure via MDM such as Intune."

I chose Option 1 as it is easier to do, but i do not have a USB Key. I have an external HDD/SSD and i put the necessary TeamsRTMMode*.ppkg file into it. However, the Surface Hub does not recognize it.
Any way i can solve this?

Thanks.
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f256cd5b-3ec8-2d55-9ae4-ff9849d52eae
* Version Independent ID: 52c2271b-df38-5dc9-c2a1-553cdf3b5496
* Content: [Deploy Microsoft Teams for Surface Hub - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-surface-hub)
* Content Source: [Teams/teams-surface-hub.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-surface-hub.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
