### ISSUE TITLE
Conflicting info on licenses needed for pay-per-minute

### ISSUE THREAD

**Issue by ahunkins** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6466]
These two sentences seem to conflict:

- Under "Need some Details": It also requires that a Pay-per-minute license and a Communications Credits license **must both** be assigned to each user for Audio Conferencing to work.
- Under "Why is it best for you?": If you have Audio Conferencing pay-per-minute licenses, you **don't have to** assign Communications Credits licenses separately to each user specifically for Audio Conferencing usage (you might still need to assign them for other services).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fac515b-9c6b-c70c-330e-53557dc23fd2
* Version Independent ID: d515841e-f412-286d-1a97-30507bb50040
* Content: [Audio Conferencing pay-per-minute - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-pay-per-minute)
* Content Source: [Teams/audio-conferencing-pay-per-minute.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-pay-per-minute.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by lindspea** [comment]
@nam31 please can this be checked for merge.

**Comment by nam31** [comment]
Closing via #6492 
Thank you
