### ISSUE TITLE
Screen sharing mode per user or per organizer?

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6467]
The documentation states

> Screen sharing mode is a per-participant policy.

But the paragraph describing the effect of the policy

> Meetings hosted by Daniela allow meeting participants to share their entire screen or a specific application. If Amanda joins Daniela's meeting, Amanda can't share her screen or a specific application as her policy setting is disabled. In meetings hosted by Amanda, no one is allowed to share their screen or a single application, regardless of the screen sharing mode policy assigned to them. This means that Daniela can't share her screen or a single application in Amanda's meetings.

indicates that it is actually a **combination of a per-organizer and per-user policy**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams#allow-scheduling-private-meetings)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by get-itips** [comment]
Thanks for your feedback @ITBlandMCT Eric, will propose to clarify the note.

**Comment by ITBlandMCT** [comment]
Thanks for the fast response!
