### ISSUE TITLE
Unable to use Microsoft Teams WalkieTalkie using custom PTT button on Bartec IS910.1

### ISSUE THREAD

**Issue by shianpoon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6472]
I'm unable to use Microsoft Teams WalkieTalkie using custom PTT button on Bartec IS910.1 Android tablet.

Is there any developer API available so that I can program the PTT button to work with Microsoft Teams?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d91ddefc-3722-8bc2-bd9b-4a90ede28944
* Version Independent ID: 35e56a9d-a01c-4126-3750-aae1ed984f55
* Content: [Walkie Talkie application in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/walkie-talkie)
* Content Source: [Teams/walkie-talkie.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/walkie-talkie.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
