### ISSUE TITLE
Need more information here

### ISSUE THREAD

**Issue by andrewjohnporter** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6473]
Hi,

I think this page requires a lot more information, which I am currently trying to find. Things such as:

1. What is the URL that is used to update which needs to be allowed through your network?
2. How to troubleshoot or monitor the update process to check if it's working or getting blocked
3. Can the update process be controlled via group policy settings or Intune and links to these
4. Where to find a version history so you can know if you have the latest version or not (and confirm if auto-updating is working)
5. Confirmation that SCCM can not be used to manage Teams updates
6. Clarification on whether or not Teams gets updated when  you update Office

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6da28da-eb7b-d3ae-4c2f-8f87803b1830
* Version Independent ID: 8c42d7a2-80c6-86dd-347a-ed6d8d909c41
* Content: [Teams updates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-client-update)
* Content Source: [Teams/teams-client-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-client-update.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by nam31** [comment]
@SerdarSoysal can you please help?
Thanks

**Comment by dariomws** [comment]
Hi @andrewjohnporter, thank you for your feedback.

Sorry for the delay.

1.  All the URLs that Teams needs to work properly are included here: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/microsoft-365/enterprise/urls-and-ip-address-ranges).
3. 5.  The desktop client updates itself automatically. You cannot control the update process via GPO, Intune or Endpoint Manager.
4. This is the closest article to the one you are requesting: [What's new in Microsoft Teams](https://support.microsoft.com/office/what-s-new-in-microsoft-teams-d7092a6d-c896-424c-b362-a472d5f105de).
6. Now included in the article:

## What about updates to Microsoft 365 Apps for enterprise?

Teams is installed by default with new installations of Microsoft 365 Apps for enterprise as described in [Deploy Microsoft Teams with Microsoft 365 Apps for enterprise](/DeployOffice/teams-install).

Teams follows its own update process as outlined above. Teams doesn't follow the update process for the other Offices apps, such as Word and Excel. To learn more, read [Overview of update channels for Microsoft 365 Apps](/DeployOffice/overview-update-channels).

**Comment by andrewjohnporter** [comment]
Thanks. Any details on logs or event viewer to check on the update process or for any update errors?

**Comment by dariomws** [comment]
You're welcome @andrewjohnporter. There is a dedicated article for that:
https://docs.microsoft.com/microsoftteams/troubleshoot-installation
