### ISSUE TITLE
Document "msft-m365-groups" content under "Groups in Microsoft 365" not entirely correct

### ISSUE THREAD

**Issue by sahilPrashar90** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6474]
Under the section, "Groups in Microsoft 365" the document states that from Azure AD admin center you can "Manage all group types, except shared mailbox groups"  but that's not true, currently there is no possibility to manage Distribution and Mail enabled security groups from Azure AD admin center except deletion. Can you please check! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ad624-9792-91b7-c85f-09b839b1ea44
* Version Independent ID: e8288f91-11bd-599b-8a88-074917b315a4
* Content: [Microsoft Teams IT architecture and telephony solutions posters - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-architecture-solutions-posters)
* Content Source: [Teams/teams-architecture-solutions-posters.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-architecture-solutions-posters.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by nam31** [comment]
@SerdarSoysal , can you please help?
Thanks

**Comment by get-itips** [comment]
@sahilPrashar90 
Thank you for bringing this to our attention. We've forwarded the information to the documentation team. They will assess the information and update the posters, if needed.
