### ISSUE TITLE
Paragraph is in wrong place

### ISSUE THREAD

**Issue by benAugust** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6477]
The paragraph in bold is out of place and should be moved to just prior to the Network Planner header. See below.

App preferences
Here you can choose the app that users will use to join Skype for Business meetings (Skype for Business or the Skype Meetings App). This setting isn't dependent on the coexistence mode setting.

_Should go here_

Network Planner
Network Planner helps you determine and organize network requirements for connecting Teams users across your organization. Learn how to Use the Network Planner for Microsoft Teams.

**You can also select the "Download the Teams app in the background for Skype for Business users" option as well. By default this setting is set to On. With this setting enabled it will download the Teams app in the background for users running the Skype for Business app on Windows PCs. This happens if the Coexistence mode for the user is Teams Only, or if a pending upgrade notification is enabled in the Skype for Business app.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9b7f77-061d-a224-ff1c-8d3e15d21221
* Version Independent ID: 00fa9550-c4c4-3398-ffbb-271cc724048f
* Content: [Manage settings for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/enable-features-office-365)
* Content Source: [Teams/enable-features-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enable-features-office-365.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@benAugust thank you for reaching out and helping improve MS Docs. It looks like the paragraph is in the correct place now. I see the article was updated this week. Please confirm from your side. Thanks.

**Comment by scanum** [comment]
@benAugust Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
