### ISSUE TITLE
Need more information On-network Conferencing V/s deploying in India.

### ISSUE THREAD

**Issue by sunilgi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6479]
Hello Team, 

Customer reached out to me asking for clarification on "On-network Conferencing must NOT be deployed with any telephony equipment in India" ,  My understanding here is,  we say it because of Toll By Pass which is not allowed for example, Pstn egress as to be local to the user to avoid toll bypass.  Do you have any addional insight ?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
