### ISSUE TITLE
Teams Users reset their PIN

### ISSUE THREAD

**Issue by labonster** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6482]
The note panel "A Skype for Business or Microsoft Teams user won't be able to reset their PIN. The PIN can only be reset by you, the admin. When a PIN is reset, an email is sent to the user." is incorrect.

Teams users can change their pin now. There is a link at the bottom of the meeting invite that says to reset pin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad892c60-f7e4-0790-66f7-219d28f44ee6
* Version Independent ID: 36e86cca-c5a3-eb4d-477e-1fb7b0b5d7f1
* Content: [Audio Conferencing common questions - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/audio-conferencing-common-questions#what-in-meeting-dial-pad-commands-are-supported)
* Content Source: [Teams/audio-conferencing-common-questions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-common-questions.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@labonster Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
