### ISSUE TITLE
Document dosent seems to be updated.

### ISSUE THREAD

**Issue by ashutoshvighne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6484]
I am reaching out to you regarding the article "https://docs.microsoft.com/en-us/microsoftteams/office-365-set-up#turn-teams-on-or-off-for-your-entire-organization" to "Turn Teams on or off for your entire organization". However, the documents doesn't seems to be updated.

Turn Teams on or off for your entire organization
_**Tenant-level control for Teams was removed effective August 2018.**_ Control access to Teams in your organization with user-level licensing. To learn more, see Manage user access to Teams.

_**The exception to this change is Microsoft Teams for Education (EDU).**_ You can still manage Teams at the organization level if you have an EDU license. To do this, go to the Microsoft 365 admin center > Settings > Services and add-ins > Microsoft Teams. If you're using the new Teams admin center, you'll have to turn off Try the new admin center to find Services and add-ins.

Documentation states that the ability to disable teams for an entire tenant was removed in August 2018 with the exception of EDU users. However, Enabling/Disabling Teams option is still available for non EDU tenants.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5473bf0-ba2d-6c42-d57d-b61af64452d3
* Version Independent ID: 7195478d-3ef4-be8c-2920-3fdba3e70c7e
* Content: [Turn on Teams in your Microsoft 365 or Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/office-365-set-up#turn-teams-on-or-off-for-your-entire-organization%22)
* Content Source: [Teams/Office-365-set-up.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-set-up.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@ashutoshvighne thank you for pointing this out and helping improve MS Docs. Should I add this article link - https://docs.microsoft.com/microsoftteams/user-access to this document?

**Comment by ashutoshvighne** [comment]
Hello Lindsey,

Thank you so much for your response. I do see that the document is updated, however, In the documentation, its mentioned that "Tenant-level control for Teams was removed effective August 2018." but we still do see an option in our Admin centre to Turn on/off teams for all users.

Reference Article : https://docs.microsoft.com/en-us/microsoftteams/office-365-set-up#turn-teams-on-or-off-for-your-entire-organization%22

[cid:image003.png@01D6F037.B588FE90]

Below is the Screenshot from my Non EDU test tenant by navigating to Office Admin Centre > Settings > Org Settings > Microsoft Teams.

[cid:image004.png@01D6F037.B588FE90]

Thanks & Regards,
Ashutosh Vighne

**Comment by lindspea** [comment]
@ashutoshvighne thank you for clearing this up. I've done more research and found that it will be enabled either way by default. You basically have to make sure your users don’t have the license turned on. Does this make sense?

**Comment by scanum** [comment]
@ashutoshvighne Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
