### ISSUE TITLE
Clarify how to create derived trunk

### ISSUE THREAD

**Issue by davemidd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6489]
This statement is unclear:

> In the customer tenant, the carrier need only to add the derived trunk FQDN to the voice routing policies of the users. There is no need to run New-CSOnlinePSTNGateway for a trunk.

In the voice routing policy, the only attribute that can be configured are 'PSTN usage records'.  There's nowhere to configure FQDNs. Where should they be configured?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure Session Border Controller - Multiple tenants - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@davemidd thank you for reaching out. Please see this tech community article and let me know if it helps at all - https://techcommunity.microsoft.com/t5/microsoft-teams/derived-trunk-for-teams-direct-routing-hosting-model/m-p/862643/page/2

**Comment by davemidd** [comment]
Hi @lindspea Thanks for the link. That definitely helped and I now have a derived trunk working. There's quite a few things that I think should be added to the documentation that would make it much clearer. e.g.

1. An FQDN (that doesn't exist as an SBC) can only be added with Powershell and not the Teams Admin Portal (as the GUI only allows you select with checkboxes which existing SBCs you want to use with the route). Do you know if there's a plan to update the Portal to allow manually entering FQDNs in voice routes?
2. The FQDN needs to exist in the 365 org. That may sound obvious but it's not the case when creating SBCs. e.g. if your org has mydomain.com you can freely create SBCs as subdomains (sbc1.mydomain.org, sbc2.mydomain.org) without needing to explicitly add them to the org. Here however, you cannot create a voice route with an FQDN that isn't explicitly added to the org.
3. The documentation suggests that to migrate from the 'old' setup (with SBCs) to the 'new' method (with derived trunks) you can simply delete the SBC. You can't actually delete the SBC (portal or Powershell) if there is a voice route that references it. You have to first delete the voice route, then wait (half an hour or so for me) before you can then delete the SBC. You can then recreate the voice route with the FQDN. (I didn't actually check if it's possible to just remove the FQDN from the voice route, without deleting the route, then add it back later.)

There's quite a bit here that can and will trip people up.
What's the best way to get the documentation updated?

Thanks again for the reference.
David

**Comment by lindspea** [comment]
@CarolynRowe please can you assist here?

**Comment by lindspea** [comment]
@CarolynRowe

**Comment by jlon125** [comment]
Any update on this? It is still an outstanding issue, in particular creating the derived trunk in TAC is not possible as the documentation suggests, you have to do it in powershell.

**Comment by davemidd** [comment]
Hi,
I'm not sure why this has been closed? There's no commits against and I don't see any changes in the documentation.
Please advise.
Thanks.
David
