### ISSUE TITLE
Remove UM 2007 integration with Skype for business

### ISSUE THREAD

**Issue by SarveshDongare** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#649]
In this article though initially it mentions the Um versions that are supported , under the phase for "Configure Skype for Business Server dial plans. " it talks about UM 2007 SP1. We need to remove this as SFB Mediation server does not support ICE V6 and calls from PSTN to UM 2007 Fail

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1f3ac30-3f43-0200-73c1-415a6db08213
* Version Independent ID: 606be1b3-245a-1dda-6cfd-d260e11041e7
* Content: [Deployment process overview for integrating on-premises Unified Messaging and Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/integrate-with-exchange/deployment-overview#feedback)
* Content Source: [Skype/SfbServer/plan-your-deployment/integrate-with-exchange/deployment-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/integrate-with-exchange/deployment-overview.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
I've removed the reference, this should go live later today.
