### ISSUE TITLE
Approvals App for Teams

### ISSUE THREAD

**Issue by pr1malc0de** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6497]
Feedback for the new approvals app in team brought me here. Line breaks are ignored in approvals, you just get a wall of text. Even following the markdown guide on the page says to use forced line breaks. These just dont work!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 055b01ff-ee6c-7d5a-74bd-0e8eed7ee6b5
* Version Independent ID: 13c4174f-2a2a-2ef9-14c5-2f10817cc66a
* Content: [Approvals application availability in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/approval-admin)
* Content Source: [Teams/approval-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/approval-admin.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Hi @pr1malc0de 
I'm sorry that you're having problems. I'll forward your comments to our SME. Cindy

**Comment by pr1malc0de** [comment]
Thanks @cichur much appreciated!

**Comment by pr1malc0de** [comment]
@cichur in case this is useful I have some more information around this problem. Authoring an approval inside teams on the fly, you have to use x3 spaces and then return to force a line break (not the 2 spaces as described in the documentation here https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support). Generating an approval from inside power automate using x2 or x3 spaces and return does not work.

**Comment by lindspea** [comment]
@pr1malc0de thank you for reaching out. I see the article was updated yesterday. Please let me know if there are any changes still needed for clarity.

**Comment by pr1malc0de** [comment]
Hi @lindspea  if your referring to the article in my previous message https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support it shows a last updated date of 29/09/2020?  but i assume you mean this article https://docs.microsoft.com/en-us/microsoftteams/approval-admin which has been updated on the 19th but i dont see any reference to line breaks? My issue is that i cant create line breaks in teams approvals sent from flow and the guide for markdown support (my previous article is wrong). Cheers

**Comment by pr1malc0de** [comment]
@cichurHi is there any update? We are midway through a project to roll out approvals across our company and no formatting in approvals is holding us back and we have no idea what is happening. I cannot find any other way to officially raise this issue, the link on the documentation for support goes to an access denied page.

**Comment by cichur** [comment]
Hi @pr1malc0de,
I'm still waiting to hear back from the SME. I pinged him again this morning. Thank you. Cindy

**Comment by pr1malc0de** [comment]
@cichur Thanks for all your help appreciate it!
@farhazkmsft Great news! Looking forward to trying it out!

**Comment by scanum** [comment]
@pr1malc0de Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by vinnyng** [comment]
@scanum I've tested the Approval Apps on Teams and it's still now working properly with Markdown formatting for the Approvals. Has the fix have been rolled out live yet?

**Comment by pr1malc0de** [comment]
@scanum @cichur The Doesn't appear to be resolved yet but appreciate this GitHub page may not be the correct place for this as it's for documentation. Although technically the documentation is wrong because the products behaviour is different to the documentation ;-) but obviously that's not the point here. Is there a GitHub page or some kind of issue tracker for this product so we know when the issue is resolved? Cheers

**Comment by cichur** [comment]
Hello @pr1malc0de 
The SME replied:

**@pr1malc0de hey there thanks for reporting, we're fixing this issue in our current sprint, formatting fixes for markdown should be available this month, will be fast tracking asap**

It looks like you're dealing with a product bug. We believe that the documentation is correct once the bug is fixed. -Cindy

**Comment by pr1malc0de** [comment]
thanks @cichur

Is there anywhere else that people can go to track this problem until it's resolved. I struggled to find any place to even report this problem until I stumbled here, if there is a more appropriate place it would be a great help to know where to go. Thanks

**Comment by pr1malc0de** [comment]
> @pr1malc0de hey there thanks for reporting, we're fixing this issue in our current sprint, formatting fixes for markdown should be available this month, will be fast tracking asap

@farhazkmsft any news on when this fix will be available? Thanks

**Comment by pr1malc0de** [comment]
In case anyone else comes across this I managed to raise it through our support plan with power automate team. After 3 weeks of back and forth they finally got someone who is familiar with the problem and said it is now planned for mid march, they are treating the issue as by design until that fix comes out. I wish I worked for MS, I could just declare all bugs in my code as by design until they are fixed! I find this more and more with MS recently, so many bugs that are just neglected in the constant push for more features.

Email I received (names and email removed)

 Greetings!   This is an   follow-up email a just wanted to check that if you get a chance to check my   previous email. Please reply to this email to proceed further on this case.   I have received an update   from the internal Team. Work already tracked on our end. The feature will be   generally available in mid-march.   This is not fixed. We treat   it as by design at this point.   We have a markdown feature   pending rolling out. So this issue will be addressed with the new markdown   support. we are further investigating the same. Once we get any update we   will share the same with you. Your patience is highly appreciated.   Thank you for your time and   collaboration with Microsoft       Regards,  BLANK Ambassador \| Microsoft Office 365 support   Mon-Fri: 9:30 AM – 7:00 PM UTC   My Technical Advisor:BLANK
--

**Comment by farhazkmsft** [comment]
We just started rolling this out in our internal rings, hoping to reach GA in about 2/3 weeks assuming no major issues occur during rollout. Sorry about the delay, we just wanted to ensure high quality before we rolled it out

**Comment by pr1malc0de** [comment]
@farhazkmsft that's really good to hear i look forward to release! I have another issue with Adaptive cards that in the last few weeks no longer formats correctly (even though the MS designer shows them rendering with teams template fine V1.2). Appreciate this isn't the correct place to raise this but support keep telling me to vote on fixing a bug! is there a github page to raise this and follow progress on teams issues? Thanks

**Comment by vinnyng** [comment]
It looks like the markdown fix was rolled out for the Approval Apps on Teams and looks mostly good. The bold and new line markdown is working properly. My only issue is that a field that holds multiple lines of text with hard return in it are not showing correctly. It shows correctly on Outlook and Approval Center though. Can you take a look and verify?
![Screenshot 2021-03-10 141332](https://user-images.githubusercontent.com/78559215/110705536-6511fb00-81ab-11eb-9fd7-5bec44aedd90.png)

**Comment by pr1malc0de** [comment]
@vinnyng Hi, yes it appears that line breaks are now working! If you want to get a line break in normal text you need to use x2 spaces first then a hard line break. I have confirmed this on my tenant. Have a look here in the "Paragraphs and Line Breaks" section https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support
