### ISSUE TITLE
Approvals App for Teams - API and callbacks

### ISSUE THREAD

**Issue by mjisaak** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6500]
Hi 👋,

this is just a question, not an issue. 

The approval app sounds like a really nice extension and I wonder whether it is possible to create approval requests programmatically using the Graph? API? 

Also is it possible that an approved request triggers a webhook, e. g. an Azure Function? 
Cheers,
Martin

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 055b01ff-ee6c-7d5a-74bd-0e8eed7ee6b5
* Version Independent ID: 13c4174f-2a2a-2ef9-14c5-2f10817cc66a
* Content: [Approvals application availability in Teams - Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/approval-admin)
* Content Source: [Teams/approval-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/approval-admin.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
