### ISSUE TITLE
MS Teams support on ChromeBook OS

### ISSUE THREAD

**Issue by rajkumardas2701** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6502]
[Enter feedback here]
Hello Team,

Can you confirm if MS Teams is completely supported on Chromebook. If yes, can we update this document accordingly?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29a61ff5-b3a5-158d-149a-dec344060e05
* Version Independent ID: 97fac351-a283-aaa8-cde1-fbd9cf4e8504
* Content: [Hardware requirements for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/hardware-requirements-for-the-teams-app)
* Content Source: [Teams/hardware-requirements-for-the-teams-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hardware-requirements-for-the-teams-app.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@rajkumardas2701 thank you for reaching out. I've done some research and found that MS Teams is supported on Chromebook. @SerdarSoysal please can you confirm?

**Comment by lindspea** [comment]
@dstrome please can you assist. Is MS Teams supported on Chromebook and will this article be updated to add the details?

**Comment by dstrome** [comment]
Teams can be run as a web app on Chrome OS but there is no specific Chrome OS app available.
