### ISSUE TITLE
Password expiration

### ISSUE THREAD

**Issue by Strick1969** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6503]
Step 5 should tell the customer to make sure the password does not expire OR tell them what happens when it does expire and let them decide. It is very vague. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Microsoft 365 or Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-office-365)
* Content Source: [Teams/rooms/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-office-365.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Strick1969 thank you for reaching out. Please see excerpt from this doc - https://docs.microsoft.com/MicrosoftTeams/rooms/rooms-operations - "Failure to do this will eventually cause the Skype account to fail logon complaining about an expired password. Note that this impacts all local accounts on the machine, and thus failure to set this will also cause the administrative account on the box to eventually expire as well."

**Comment by kdspiess** [comment]
Hello all,  for the above concern, we could add a Note under Step 5 in docs page noted. 
_Note:  If the password is not set to Never Expire, then upon the account reaching the expiry period, the account will no longer sign-in on the device.  The password will then need to be changed for the account and also updated locally on the MTR device._

This password expiry policy is different from the mentioned policy from @lindspea.  The policy noted in https://docs.microsoft.com/MicrosoftTeams/rooms/rooms-operations pertains to the Windows 10 local user accounts and not the device/room account.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
