### ISSUE TITLE
Clarify Lenovo ThinkSmart View appearing multiple times on page.

### ISSUE THREAD

**Issue by dinsdaler** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6504]
Hello.
The Lenovo ThinkSmart View appears in two separate sections of this page - under Teams Phones and Team displays - and it is not clear why it is listed in both places.  Is this due to model or firmware?

See https://docs.microsoft.com/en-us/microsoftteams/devices/teams-ip-phones?source=docs#firmware-versions-2 and https://docs.microsoft.com/en-us/microsoftteams/devices/teams-ip-phones?source=docs#firmware-versions

For each listing, the same device and model number appears but with different firmware versions.  It would be useful to clarify the differences.

(Background - we are currently evaluating one and the firmware of the device does not match some of the listed versions, e.g. here: https://docs.microsoft.com/en-us/microsoftteams/devices/teams-ip-phones?source=docs#app-versions-2 )

Thank you,
R

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaaef9e1-8f1c-ebf0-7856-4c007342a2c3
* Version Independent ID: 3eaf671f-375e-8787-9c66-3947c3606559
* Content: [Phones and Devices for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/devices/teams-ip-phones)
* Content Source: [Teams/devices/teams-ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/teams-ip-phones.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@dinsdaler thank you for pointing this out. Please let me know if this article helps - https://techcommunity.microsoft.com/t5/microsoft-teams/teams-ip-phone-display-lenovo-thinksmart-view-no-version-info/m-p/2012661

**Comment by dinsdaler** [comment]
Hello @lindspea - thank you for that link, the linked article in that helped explain what the difference was, and we've been able to update our test devices to 'display' devices now.

Some suggestions for the original page (https://docs.microsoft.com/en-us/microsoftteams/devices/teams-ip-phones):

1. Move the sentence "See Microsoft Teams phones feature set for information on features supported by these devices." and the link from underneath "Firmware versions" to _above_ "Product release information for Collaboration Bars" (https://docs.microsoft.com/en-us/microsoftteams/devices/teams-ip-phones#product-release-information-for-collaboration-bars) as this sentence relates to phones, not devices.
2. Underneath the versions table in the section https://docs.microsoft.com/en-us/microsoftteams/devices/teams-ip-phones#firmware-versions-2 add a new sentence "See Microsoft Teams display feature set for information on features supported by these devices." with a link to https://docs.microsoft.com/en-us/microsoftteams/devices/teams-displays instead as this section is talking about displays.
3. Underneath https://docs.microsoft.com/en-us/microsoftteams/devices/teams-ip-phones#product-release-information-for-teams-display add a sentence to the effect "Teams displays is the evolution of Teams phones. You can upgrade Teams phones in your organization to Teams displays using the Microsoft Teams admin center. This option is available only to phones that support upgrading to Teams displays. To learn more, see Upgrade Teams phones to Teams displays." to clarify that an upgrade activity is required to move from 'phone' to 'display' feature set when using the Lenovo device.  Optionally you could include the page hyperlink https://docs.microsoft.com/en-us/microsoftteams/devices/upgrade-phones-to-displays in this sentence although it would be linked via the page in step 2 above.

Thank you,
Richard.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
