### ISSUE TITLE
Update for MFA / 2FA Login

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6505]
Please add notes to MFA / 2FA Login as what is listed in this page fails for MOST who are doing what security experts and Microsoft is pushing for.... MFA / 2FA on all important accounts.  This article should FOCUS on that type of login.  Also, I also feel the commands are out dated as they don't reflect the new Azure Commands.  But, I may be wrong with that.  Please update this important page as I need to deal with Teams Conference Bridge commands.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd283f6e-3865-ed70-d663-cc461ee8ba57
* Version Independent ID: 2450d311-fc04-d8b6-b4a2-b1890ec6fc3e
* Content: [Install Microsoft Teams PowerShell - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install)
* Content Source: [Teams/teams-powershell-install.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-install.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Karr thank you for reaching out. Please have a look at these two articles and let me know if they help at all - https://docs.microsoft.com/powershell/module/teams/ and https://docs.microsoft.com/microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window

**Comment by scanum** [comment]
@Karr Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
