### ISSUE TITLE
Where is the documentation for the individual configuration items in the policy

### ISSUE THREAD

**Issue by Clam-** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6507]
As title says, where's the documentation for the configuration items, e.g. what does "Screen capture" on/off setting do? What does the Office Hours setting do/affect? What does Power Saving do?
Most of these settings are self explanatory but some of these items could do with more description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a627b5d-3edc-1add-b921-1dcd49c38653
* Version Independent ID: a2e2bd3a-31c0-471a-05fb-fd64bd942c4a
* Content: [Manage your devices in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/devices/device-management?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/devices/device-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/device-management.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@Clam- Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Clam- thank you for reaching out. Please have a look at this article and let me know if it helps at all and if I should add a link to it in this doc -  https://techcommunity.microsoft.com/t5/microsoft-teams-events-blog/how-to-choose-deploy-and-manage-the-right-teams-devices-brk3410/ba-p/267552

**Comment by Clam-** [comment]
@lindspea That article is interesting and should probably be linked somewhere in the Teams documentation.
However, what I'm looking for specifically is information regarding the options in the Teams Admin portal: Devices -> IP Phones -> Configuration profiles tab -> Add/Edit
![image](https://user-images.githubusercontent.com/985835/105339264-99981a80-5c30-11eb-90a6-19e044ed2638.png)

As I mentioned, some of those are quite self explanatory but some of them I am unsure of. For example, I get the feeling that Office Hours may be related to when firmware updates can occur, but I'm not certain. Knowing what exactly power saving does would be useful, too.

Thanks.

**Comment by Clam-** [comment]
Sorry, I also just re-looked at your linked article and it has a similar screenshot to mine, but without explanation of the actual items shown in the screenshot! Those entries/items are what I'm looking for detail on. Thanks again.

**Comment by lindspea** [comment]
@dstrome could you perhaps provide some clarity please?

**Comment by lindspea** [comment]
@dstrome

**Comment by dstrome** [comment]
@cazawideh - I don't think we need a topic but possibly some hover text for some entries would be helpful. Can you discuss the possibility with the UI team about selectively adding hover text in the various device config pages?

**Comment by cazawideh** [comment]
@dstrome Yeah, I agree this information should be in the UI itself. I'll investigate adding tooltips to this page with more details on these settings.
