### ISSUE TITLE
Update required: Permissions pertaining to accessing device capabilities not present

### ISSUE THREAD

**Issue by shuchauh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6509]
Feedback:
1. As this page appears to be an aggregate of all permissions an app could ask for in Teams, I believe that documentation around device permissions too should be added here. For now having a redirection link would also work.
Link to detailed documentation: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?view=msteams-client-js-latest&tabs=desktop
2. Page structure is very confusing. The headings and sub-headings don't look very apparent. Clear definition of sections would help in readability.
3. Hyperlinking items to respective sections at the introductory para would be helpful: 
![image](https://user-images.githubusercontent.com/71272183/104894450-c16e5080-599a-11eb-8a74-3ae2ada06417.png)
4. Possibly checking if any other sections also need an update since the documentation was last updated in 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0f81b0-eb71-1c7c-aa8c-25f114e57fd0
* Version Independent ID: 9103c060-c536-b3cc-170a-10c2fbfbc834
* Content: [Microsoft Teams apps permissions and considerations - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/app-permissions)
* Content Source: [Teams/app-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/app-permissions.md)
* Service: **msteams**
* GitHub Login: @rmw2890
* Microsoft Alias: **rowille**

**Comment by scanum** [comment]
@shuchauh Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
