### ISSUE TITLE
SfB Mac client device support clarification

### ISSUE THREAD

**Issue by simon-modality** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#651]
The February 2017 version of the SfB for Mac client called out 5 devices as having certified support. The accompanying blog post ( https://techcommunity.microsoft.com/t5/Skype-for-Business-Blog/Skype-for-Business-on-Mac-February-Update-now-available/ba-p/44581 ) said you "will continue to add devices going forward". There has been no mention of new device support since. This article implies devices must be in the solutions catalog but then caveats that some may not be supported. The link to the system requirements does not contain any more info. Please could you clarify the current state of device support - is it still the same 5 devices, or are there more now certified for use with the SfB Mac client?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cefef40d-dff0-d08b-07c0-9854a92ce8fc
* Version Independent ID: d712a3e1-5a1c-5289-e341-fcf7f4eb18d4
* Content: [Skype for Business on Mac client requirements](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/mac-requirements)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/mac-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/mac-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by PhillipGarding** [comment]
From the time of that blog post, Skype for Business on Mac has continued to add support for device functionality in general, which enables functionality in many devices.  We have not called out devices specifically in our release notes, however.
