### ISSUE TITLE
Missing dot at the end of not allowed characters

### ISSUE THREAD

**Issue by ParaGlideRocks** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6512]
In Channel names you should enter two sequential dots rather than one

Characters | ~ # % & * { } + / \ : < > ? \| ' " , .
-- | --

Characters | ~ # % & * { } + / \ : < > ? \| ' " , ..
-- | --

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams?source=docs)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@ParaGlideRocks Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by cichur** [comment]
Hi @ParaGlideRocks 
Thank you for your comments. I made the correction. Cindy

**Comment by ParaGlideRocks** [comment]
Hi Cindy,
I cannot see it reflected here (https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams) yet.

**Comment by cichur** [comment]
Hi @ParaGlideRocks The change will happen around 10:45 this morning. -Cindy
