### ISSUE TITLE
Custom badge title name requirements

### ISSUE THREAD

**Issue by strausy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6513]
It is odd that when I add my own custom badge I cannot use a one-word name or in some cases, three words. 

If I enter "Test" it gives a red warning banner with no error text.
If I enter "[Company]", same error where Company is my one word company name
If I enter "Contoso Award" it will save
If I enter "Contoso Values Award" it will not save

This page needs clearly defined rules on what a custom badge name can be called since it appears there definitely are rules.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2033a3-a651-78f3-90c2-ad582e182731
* Version Independent ID: 057e7da2-4e65-7f8d-5843-b15d92ffff02
* Content: [Manage the Praise app in the Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-praise-app?WT.mc_id=TeamsAdminCenterCSH#create-your-own-badges)
* Content Source: [Teams/manage-praise-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-praise-app.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Hi @strausy, I've reached out to the SME with your questions.

**Comment by cichur** [comment]
Hi @strausy 
I reached out to the SME. This issue was a bug that has not been fixed. Thank you for your question.
Cindy

**Comment by strausy** [comment]
@cichur to clarify did you mean to say "a bug that has **now** been fixed" or do you really mean it is a bug that is **not** currently fixed?
