### ISSUE TITLE
Has the "Repair" (menu option 1) removed by purposely?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6514]
Hi,

I have used multiple times "**RecoveryTool.ps1**" tool but with option 1 on the menu:
```
[1] Repair
[2] Reset
Please choose an option: 1
```

But by some reasons option 1 has not been available unless the .ps1 file is modified.

Could you clarify why is that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13376c1b-df70-83de-8e6a-8ddc940774b5
* Version Independent ID: 6a2531ee-ac88-ee83-b858-1928d6cb4c65
* Content: [Use the Microsoft Teams Rooms recovery tool - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/recovery-tool)
* Content Source: [Teams/rooms/recovery-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/recovery-tool.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
