### ISSUE TITLE
Team Client release note?

### ISSUE THREAD

**Issue by D-Jeffrey** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6517]
Can we get a page which explains the features and the release numbers in each of the releases of Teams Clients?  If you have one, we can not find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6da28da-eb7b-d3ae-4c2f-8f87803b1830
* Version Independent ID: 8c42d7a2-80c6-86dd-347a-ed6d8d909c41
* Content: [Teams updates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-client-update)
* Content Source: [Teams/teams-client-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-client-update.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by D-Jeffrey** [comment]
Why is it in other docs areas we can find release numbers and release notes about what is in the release but not for Teams Client?  
I can get it for Windows - https://docs.microsoft.com/en-us/windows-insider/Active-Dev-Branch
I can get it for Office (which does not include Teams) both https://docs.microsoft.com/en-us/officeupdates/
Server https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info
or SQL https://docs.microsoft.com/en-us/troubleshoot/sql/general/determine-version-edition-update-level

I don't understand why it is so hard to just capture the release versions and what is in it.  How are we suppose to support our users?
