### ISSUE TITLE
direct-routing-sbc-multiple-tenants -- derived tenant configuration ambiguity

### ISSUE THREAD

**Issue by pekkaar** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6519]
The direct-routing-sbc-multiple-tenants document says 

`sbc1.customers.adatum.biz - the derived trunk in a customer tenant that does not need to be created in PowerShell. You can simply add the name of the derived trunk in the customer tenant in the online voice routing policy without creating it.`

This is fairly ambigious. What does this mean exactly? Assuming the derived trunk FQDN is sbc1.customers.adatum.biz, where shall I put this in the customer's Voice Routing Policy config?? Must I rename a voice routing policy there to this FQDN? Or shall I simply add a PSTN Usage with this FQDN?

Please make it more clear.

Regards,
Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure Session Border Controller - Multiple tenants - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@pekkaar Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@pekkaar thank you for reaching out. Please see this tech community article and let me know if it helps at all - https://techcommunity.microsoft.com/t5/microsoft-teams/derived-trunk-for-teams-direct-routing-hosting-model/m-p/862643/page/2

**Comment by pekkaar** [comment]
Hello Lindsay,

not, not at all unfortunately. My confusion is caused by the total lack of
precise definition as to where should I enter this information: "You can
simply add the name of the derived trunk in the customer tenant in the
online voice routing policy without creating it"

The techcommunity forum starts intriguing but then goes totally in a
different direction.

All I need is the name of the Direct Routing field in the derived
(customer) tenant's Teams Admin Center, where I need to enter
that information.

Thanks,
Peter

**Comment by lindspea** [comment]
@CarolynRowe please can you assist.

**Comment by tiburd** [comment]
@pekkaar - Can you please let us know whether your question is now answered in [this updated article](https://docs.microsoft.com/microsoftteams/direct-routing-sbc-multiple-tenants)? (I didn't find it, but I want to double check...)

Please @ mention me in your reply.

Thank you!

**Comment by pekkaar** [comment]
@tiburd - I also don't see any more clarity on the ambigious part I raised this ticket for... 2.5 years ago. I have not read through the entire updated article, but the 2 sentences I complained about remained confusing.

thanks

**Comment by tiburd** [comment]
@pekkaar - Thank you for replying. I'm new in this role, and I'll do my best to get your issue addressed as soon as possible.

**Comment by CarolynRowe** [comment]
Looping in @FilippSe. He is the best person to answer this question.

**Comment by tiburd** [comment]
@CarolynRowe @FilippSe - thank you!!

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by jlon125** [comment]
@FilippSe "Use derived trunk FQDN when setting up voice routing policy in TAC under Teams-Voice-Direct Routing-Voice Routes field SBCs enrolled." is not possible, as when creating a voice route you have to select from already existing SBCs, you cannot enter anything manually. In a derived trunk scenario, there is no SBC created, so the SBCs list will always be empty, thus making this step impossible to do with TAC.

**Comment by CarolynRowe** [comment]
I'm going to reopen this issue for now.  i've started a separate thread with the PMs.

**Comment by jlon125** [comment]
Any update on this? Will the functionality to specify an SBC when creating a voice route manually be added? (so we can create this in TAC vs Powershell)

Thank you!

**Comment by CarolynRowe** [comment]
@FilippSe:  Can you comment on this please?
