### ISSUE TITLE
Script access through the proxy services..

### ISSUE THREAD

**Issue by MatthewCKelly** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6522]
In the script, it uses [System.Net.WebClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient?view=net-5.0) class. 
This class allows use of the system proxies...
* It also will download and use an updated script should one exist.

In order to use this script ( as we work with [Zero Trust](https://www.microsoft.com/en-nz/security/business/zero-trust)) I need to change the following.

```powershell        
        # Download to the temp file, then rename when the download is complete
        (New-Object System.Net.WebClient).DownloadFile($res, $TmpFile)
```
to 
```powershell       
        $proxyUri = [Uri]$null;
        $proxy = [System.Net.WebRequest]::GetSystemWebProxy();

        # if a proxy is required for this url, use Credintials..
        if ($proxy) {
            $proxy.Credentials = [System.Net.CredentialCache]::DefaultCredentials;
            $proxyUri = $proxy.GetProxy($res);
        }


        $WebClient = New-Object System.Net.webclient;

        # check if it is going to use external site..
        if ("$proxyUri" -ne "$res") {
            write-host "`tUsing proxy: [$proxyUri]";
            $WebClient.Proxy = New-Object System.Net.WebProxy( $proxyUri,$true );
            $WebClient.Proxy.Credentials =[System.Net.CredentialCache]::DefaultNetworkCredentials;
        }

        # Download to the temp file, then rename when the download is complete
        $WebClient.DownloadFile($res, $TmpFile);
```

of course if there is an updated script this modification is removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/console)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
