### ISSUE TITLE
Upgrade Journey after Skype for Business Online Retirement

### ISSUE THREAD

**Issue by Weishaupt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6525]
The announcement does not make it clear, if a Skype hybrid deployment is required to be implemented prior to the retirement to be able to perform a migration using the coexistence modes. 

The FAQ only lists information for existing hybrid deployments.
> **How does the Skype for Business Online retirement announcement affect organizations with hybrid configurations (Skype for Business Online and Skype for Business Server)?**

I'd like a clarification whether it will still be possible to create a hybrid setup to benefit from the [coexistence migration path](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-and-skypeforbusiness-coexistence-and-interoperability) after Skype for Business Online has been retired. We currently advise our customers to create a hybrid setup before the retirement date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cea1cc-731d-bfba-3ed5-63a6339ecf88
* Version Independent ID: 7681956e-e442-07a3-7f7b-f086a0aff173
* Content: [Skype for Business Online retirement - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/skype-for-business-online-retirement)
* Content Source: [Teams/skype-for-business-online-retirement.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/skype-for-business-online-retirement.md)
* Service: **msteams**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Weishaupt Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Weishaupt thank you for reaching out. Please have a look at this article and let me know if it helps at all and if I should link it in this article to help other users too - https://docs.microsoft.com/microsoftteams/faq-journey

**Comment by scanum** [comment]
@Weishaupt Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Weishaupt** [comment]
@scanum I was under the impression that I commented that the referenced article does not answer my question but this was obviously not the case.

My question has not been answered, so please reopen as I am apparently unable to do so.

**Comment by Weishaupt** [comment]
@scanum Once again: Please reopen.

**Comment by Weishaupt** [comment]
@scanum Friendly reminder to reopen the issue please.
