### ISSUE TITLE
License requirement question

### ISSUE THREAD

**Issue by GitRomney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6527]
Does the meeting organizer need the Advanced Comms license applied at the time the meeting/Live Event is created or at the time it is held or both?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09168b55-8244-974e-8bb3-6ec16429a650
* Version Independent ID: c17f4f8d-a8bb-3c81-368f-07b932f52ebc
* Content: [Advanced Communications add-on for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/advanced-communications)
* Content Source: [Teams/teams-add-on-licensing/advanced-communications.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/advanced-communications.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
