### ISSUE TITLE
Meeting Room Standard licensing

### ISSUE THREAD

**Issue by NickElniff** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6528]
This article should update the Meeting Room license to "Meeting Room Standard" license - as there was a name change to the SKU in recent months. There may also be a need to include the "Meeting Room Premium" license which is the Standard license with additional Managed Services for the room devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing#feedback)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-licensing.md)
* Service: **skype-for-business-online**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@NickElniff Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@NickElniff thank you for pointing this out and helping improve Microsoft Docs. Please can you clarify which section of the article needs to be updated and I'll look into it.

**Comment by NickElniff** [comment]
The Meeting Room license has been renamed and we now have 2 flavors of the Teams Room License (Standard and Premium)
As seen in this blog post from this past summer - Great meeting room experiences: Meet the new Microsoft Teams Rooms Standard and Premium - Microsoft 365 Blog<https://www.microsoft.com/en-us/microsoft-365/blog/2020/07/21/microsoft-teams-meetings-hybrid-workplace-options/>

Nick Elniff
Teams TS
nielniff@microsoft.com<mailto:nielniff@microsoft.com>
Teams: (913) 953-3822
My Calendar Availability<https://outlook.office365.com/calendar/published/2cfdd833c3c747aab2ac9a908c2b1103@microsoft.com/28584ead00ca4c86aaafe23eb6186b5112736639079537581362/calendar.html>

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
