### ISSUE TITLE
The tab in browser says "polcies" instead of policies

### ISSUE THREAD

**Issue by VeronicaGeek** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#653]
Just a little typo in the tab of the browser saying "Meeting polcies" instead of "policies"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Meeting polcies in Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by CrystalThomasMS** [comment]
Fixed.
