### ISSUE TITLE
Invalid regular expressions in voice routes

### ISSUE THREAD

**Issue by moorereason** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6533]
In [Step 3](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/def7dc429ad4b443294c594b378d4096164f0f75/Teams/direct-routing-analog-devices.md#step-3--create-a-voice-route-and-associate-it-with-the-pstn-usage) and [Step 7](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/def7dc429ad4b443294c594b378d4096164f0f75/Teams/direct-routing-analog-devices.md#step-7--create-a-voice-route-for-an-analog-device) of [Teams/direct-routing-analog-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/def7dc429ad4b443294c594b378d4096164f0f75/Teams/direct-routing-analog-devices.md), invalid regular expressions are given in the example commands:

```powershell
PS C:\> New-CsOnlineVoiceRoute -Identity analog-interop -NumberPattern "^\+1(425)(\d{7}])$" -OnlinePstnGatewayList sbc.contoso.com -Priority 1 -OnlinePstnUsages "Interop"
PS C:\> New-CsOnlineVoiceRoute -Identity analog-interop -NumberPattern "^\+1(4254)(\d{6}])$"  -OnlinePstnGatewayList sbc.contoso.com -Priority 1 -OnlinePstnUsages "Interop"
```
The square bracket should be removed from both patterns:

```powershell
PS C:\> New-CsOnlineVoiceRoute -Identity analog-interop -NumberPattern "^\+1(425)(\d{7})$" -OnlinePstnGatewayList sbc.contoso.com -Priority 1 -OnlinePstnUsages "Interop"
PS C:\> New-CsOnlineVoiceRoute -Identity analog-interop -NumberPattern "^\+1(4254)(\d{6})$"  -OnlinePstnGatewayList sbc.contoso.com -Priority 1 -OnlinePstnUsages "Interop"
```

Additionally, the grouping is unnecessary, so the patterns could be simplified to:
```powershell
PS C:\> New-CsOnlineVoiceRoute -Identity analog-interop -NumberPattern "^\+1425\d{7}$" -OnlinePstnGatewayList sbc.contoso.com -Priority 1 -OnlinePstnUsages "Interop"
PS C:\> New-CsOnlineVoiceRoute -Identity analog-interop -NumberPattern "^\+14254\d{6}$"  -OnlinePstnGatewayList sbc.contoso.com -Priority 1 -OnlinePstnUsages "Interop"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea0bc170-d9d9-c17a-adc8-d37cb5fe3df5
* Version Independent ID: 3c761043-bea5-0cfb-d85e-13671ed0fe9a
* Content: [Direct Routing - Connecting analog devices - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-analog-devices)
* Content Source: [Teams/direct-routing-analog-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-analog-devices.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@moorereason  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @moorereason, thank you for your feedback.

I'm removing the square bracket as it's clearly a typo. About the grouping, it's not required but usually used in our documentation to provide easier visibility.
