### ISSUE TITLE
Details of App-usage-report ActiveUsers and ActiveTeams

### ISSUE THREAD

**Issue by REMY31470** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6534]
Hello !!

How to get the details of :
- "ActiveUsers" (The Name of the Accounts That Uses It) 
and
- "ActiveTeams" (Name of the Teams that use it)
?

Thanks in advance for your return
Rémy (French)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed4904e2-a072-56fc-bc54-4e7d2582d8fd
* Version Independent ID: c70894ac-67e3-be36-4fa6-a95c78fa736a
* Content: [Microsoft Teams app usage report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/app-usage-report)
* Content Source: [Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
