### ISSUE TITLE
Microsoft Teams Delegation

### ISSUE THREAD

**Issue by Strick1969** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6535]
When discussing Teams Meeting scheduling and delegation we need to specifically state that the delegation is still governed by Exchange (EXO or On-Prem) as there is a setting for "call delegation" in the Microsoft Teams UI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@Strick1969  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Strick1969, thank you for your feedback.

The information included in this article is to support the Outlook Teams Add-In in an Exchange delegation scenario.
