### ISSUE TITLE
All these metrics but not ability to report on Teams Version?

### ISSUE THREAD

**Issue by samuelleung83** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6540]
Is there ever going to be the capability of reporting on what Teams Client version is installed on each of the users devices?
It's starting to get quite difficult to troubleshoot problems, given:
- Microsoft don't have a way of tracking which Tenants receive the latest version of Teams.
- Even once a Tenant has received the latest version, it is only progressively released to clients with no ability to track the timeframe of when and if they'll get the latest release.
Given the above situation, we have a mixed-bag of clients on various versions of teams. 
Clicking "Check for Updates" MAY install a "newer" version of teams, but not-necessarily/rarely the latest version.
We need mechanisms to control this, or at the very least, to track Version numbers on client machines.
The way Teams is installed, means this can't be done easily using SCCM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ade1a4-092c-1132-44df-ee2c683fdd33
* Version Independent ID: 396b1aee-2f40-9895-9b00-07e38d11d31b
* Content: [Microsoft Teams analytics and reporting - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-reporting-reference)
* Content Source: [Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
@samuelleung83 
Thank you for your question. I've given your question to our SME. - Cindy

**Comment by Darrelo365** [comment]
I agree. Can anyone help with a workaround? The values of client version and the UPN of the user can be seen in the older CQD dashboard. If you follow the instructions to connect the CQD data to Power BI the data might be in there but I cannot easily surface it - can anyone help? I'm happy to email users to ask them to update their clients if I can easily get a list. Thanks

**Comment by cichur** [comment]
Hi @Kateyanne 
I've not heard back from the SME. You might suggest that the user file a ticket, since this sounds like a request for an enhancement. Thank you, Cindy

**Comment by scanum** [comment]
@samuelleung83 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
