### ISSUE TITLE
PowerShell Command for BreakOutRooms

### ISSUE THREAD

**Issue by LaPhi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6543]
A information for Admins would be nice how they can activate/deactivate Teams BreakOutRooms at the following site:
https://docs.microsoft.com/en-us/microsoftteams/using-breakout-rooms

Set-CsTeamsMeetingPolicy -AllowBreakoutRooms 
https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
