### ISSUE TITLE
Skype api for business to send message to owner

### ISSUE THREAD

**Issue by faizananwerali** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6552]
I'm a developer. 

Recently, one of my clients requested that he should be notified on skype message personally and also in one of his skype groups on certain actions in the application I'm developing for him.

I'm developing the application PHP. Is there any API for that?

Message only needs to send to him and one of his skype group. Is it possible?

Is there any payment for that? my client might be willing for that as well.

Can you please confirm and respond it as quickly and possible.

Thank You,

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
