### ISSUE TITLE
Replace text "Replace locations data" with "Upload data"

### ISSUE THREAD

**Issue by lukecarroll** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6553]
Customer support has pointed out that the UI doesn't match the documentation. This is the relevant section:

To edit the table of subnets and locations

In the left navigation of the Microsoft Teams admin center, click Locations > Reporting labels.
Click **Replace locations data**.
In the **Replace locations data** pane, click Select a file, and then browse to and upload your edited .csv or .tsv file.
Click Upload.

Needs to be replaced with

In the left navigation of the Microsoft Teams admin center, click Locations > Reporting labels.
Click **Upload data**.
In the **Upload data** pane, click Select a file, and then browse to and upload your edited .csv or .tsv file.
Click Upload.

![image](https://user-images.githubusercontent.com/3445900/105751050-596bbd00-5efa-11eb-9c8b-d6e6cc58fa57.png)

![image](https://user-images.githubusercontent.com/3445900/105751302-ac457480-5efa-11eb-8761-4062f6943e9e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f8119c9-61af-b469-af98-ddd37764c0ca
* Version Independent ID: 7d829a74-9df7-5b6f-8e1c-44d3e5d38f75
* Content: [Add and update reporting labels - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/learn-more-about-site-upload)
* Content Source: [Teams/learn-more-about-site-upload.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/learn-more-about-site-upload.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
