### ISSUE TITLE
Getting Started Wizard not working

### ISSUE THREAD

**Issue by BryanAdvisicon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6564]
The getting started wizard is no longer launching for business voice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74845604-00ca-b195-4781-80efa6be29a3
* Version Independent ID: bd22e545-c3ec-f7c6-ccfa-76c16c14ecc6
* Content: [Use the Getting Started wizard to set up Business Voice - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/business-voice/use-getting-started-wizard)
* Content Source: [Teams/business-voice/use-getting-started-wizard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/business-voice/use-getting-started-wizard.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@BryanAdvisicon Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
