### ISSUE TITLE
Skype Mac File Share

### ISSUE THREAD

**Issue by JeffBrownTech** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#657]
Wasn't file sharing for Skype Mac client made available in the December 2017 CU?
https://support.microsoft.com/en-us/help/4036625/enable-peer-to-peer-file-transfer-for-skype-for-business-on-mac-client

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b4299e6-ae5f-6776-9b6a-ff7cba8b2550
* Version Independent ID: 757f4282-c94d-e60b-4523-87663199abd6
* Content: [Desktop client feature comparison for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/desktop-feature-comparison)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/desktop-feature-comparison.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/desktop-feature-comparison.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by PhillipGarding** [comment]
File sharing in **peer-to-peer** conversations was added with CU6 update to Skype for Business Server 2015.  Sharing files in meetings is not currently supported in Skype for Business on Mac.

**Comment by PhillipGarding** [comment]
If you have enabled the appropriate policies (as described in the KB article you reference) and file transfer is not working in P2P conversations, please work with your support team to open a case so we can look into it.

Phil Garding

**Comment by JeffBrownTech** [comment]
Ah, I see. I saw "Upload files to share with others" but did not see it was under "Meeting Support". Maybe a separate line item under "IM Support" to show that in P2P sessions file sharing is available? Just to distinguish between the two.

**Comment by PhillipGarding** [comment]
Thanks for the suggestion, Jeff.  As I was looking at this topic, I was surprised to see that it wasn’t called out in the IM section.  I’ll update that.

Phil.
