### ISSUE TITLE
Impossible to delete after 1 day Tchat conversations in Teams Rooms

### ISSUE THREAD

**Issue by lyonelf** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6572]
[Tapez vos commentaires ici]

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: f55c52a5-5841-b9c9-1607-2013dc3f2e20
* Version Independent ID: 16d93458-5e01-646f-dac5-31306cc7f3fb
* Content: [Stratégies de conservation dans Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/fr-fr/microsoftteams/retention-policies#:~:text=%20To%20create%20a%20retention%20policy%20for%20Teams,want%20to%20retain%20data,%20delete%20it,...%20More)
* Content Source: [Teams/retention-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/retention-policies.md)
* Service: **msteams**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by lyonelf** [comment]
In 365 security and compliance, there is nothing to delete conversations in a resource account like Rooms Teams.

After a call opened in the support, it is confirmed.

So, to respect RGPD is it possible to dev' this option as soon as possible?

**Comment by cabailey** [comment]
Hi @lyonelf  Thank you for this feedback.  I have some information to add to the documentation that I think will cover this, so you can leave this update with me.  However, for your request to change the product, please post this to UserVoice (https://microsoftteams.uservoice.com/) or raise this with your standard support channels.

**Comment by cabailey** [comment]
The mailbox types supported are now documented here, which we link to for more technical information: https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-teams#whats-included-for-retention-and-deletion

**Comment by lyonelf** [comment]
Thanks for this link but room mail box are not supported by the retention.

**Comment by cabailey** [comment]
Yes, "RoomMailbox" is not one of the RecipientTypeDetails listed as supported for retention policies for Teams - which explains the issue you reported.

**Comment by lyonelf** [comment]
So can't delete chat in room account cause a problem with GPRD rules in Europe.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
