### ISSUE TITLE
update minimum CPU requirement for Teams to share clock speed. 

### ISSUE THREAD

**Issue by luriep** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6574]
[Enter feedback here] 
On page https://docs.microsoft.com/en-us/microsoftteams/hardware-requirements-for-the-teams-app#hardware-requirements-for-teams-on-a-windows-pc 
**Please edit the minimum "Computer and processor" requirement to make it clear that it's the Turbo frequency of a CPU that matters and not the base frequency .** 

It's causing confusion from our customers who look at the Surface Laptop 3 i5/16/256, the Intel i5-1035G7 CPU has 4 cores at  3.70 GHz turbo frequency. (The base frequency is only 1.2ghz).  It needs to be clear that these types of device exceed the minimum for Teams (2 cores at 1.6 GHz).  

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29a61ff5-b3a5-158d-149a-dec344060e05
* Version Independent ID: 97fac351-a283-aaa8-cde1-fbd9cf4e8504
* Content: [Hardware requirements for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/hardware-requirements-for-the-teams-app)
* Content Source: [Teams/hardware-requirements-for-the-teams-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hardware-requirements-for-the-teams-app.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@luriep Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @luriep, thank you for your feedback and help us to improve docs.microsoft.com.

I'm applying your suggestion. This is how it will look:
![image](https://user-images.githubusercontent.com/33589238/106602865-54cb8800-653c-11eb-8607-4c34f041cd0a.png)
Please let me know if you think it's better something different.

Thank you again!

**Comment by luriep** [comment]
looks great. Thank you!


pete
