### ISSUE TITLE
Suggestion: update first Note on page

### ISSUE THREAD

**Issue by redmondChris** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6575]
Some of the content in the first Note is time-specific to late 2020. Suggestion: update the Note using the timing information added on https://aka.ms/tmrodsp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@redmondChris Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @redmondChris, thank you for your feedback.

I'm suggesting this note:
>[!Note]
> The change from using Microsoft Stream to OneDrive for Business and SharePoint for meeting recordings will be a phased approach. For detailed information on each phase, see [Use OneDrive for Business and SharePoint or Stream for meeting recordings](tmr-meeting-recording-change.md).

Please let me know if you think it's important to add the timing information to this article too.

@cichur please kindly let me know your thoughts too. Thanks!

**Comment by cichur** [comment]
Hi @dariomws 

I like your note. If you add it, I'll commit your changes.
Cindy

**Comment by dariomws** [comment]
Thanks @cichur. It's the following PR:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/6590

**Comment by dariomws** [comment]
Hi @cichur, will you merge it? Thanks!
