### ISSUE TITLE
Wrong powershell command to install pre-release version

### ISSUE THREAD

**Issue by knlp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6576]
The command to install the pre-release version does not work.

![image](https://user-images.githubusercontent.com/27350379/106167834-eda18280-618d-11eb-8692-4acd09584549.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd283f6e-3865-ed70-d663-cc461ee8ba57
* Version Independent ID: 2450d311-fc04-d8b6-b4a2-b1890ec6fc3e
* Content: [Install Microsoft Teams PowerShell - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install)
* Content Source: [Teams/teams-powershell-install.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-install.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by RAJU2529** [comment]
@knlp . thanks for pointingout, yes command is wrong,  i checked other command in article , that also wrong. 
afternoon i will test on my windows 10

**Comment by EILI309** [comment]
This only seems to work on on Powershell 7. Once installed you can import the module to Powershell 5 / ISE.
![image](https://user-images.githubusercontent.com/78208184/106265532-791b2200-6227-11eb-9ca8-eea59fbf7b2e.png)

The module should be installed here: C:\Users\USERNAME\Documents\WindowsPowerShell\Modules\MicrosoftTeams
(If you cannot install PowerShell 7 on the computer that needs the MicrosoftTeams module, download it on a computer that can run PS7 and file transfer it to the same folder on the second computer)

**Comment by knlp** [comment]
Hello

Updating the PowerShellGet module also helped. Thank you for the feedback, this case can be closed.

Pozdrawiam, Piotr Zmudziński
________________________________
Od: EILI309 <notifications@github.com>
Wysłane: piątek, 29 stycznia 2021 11:50
Do: MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com>
DW: knlp <piotr.zmudzinski@outlook.com>; Mention <mention@noreply.github.com>
Temat: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Wrong powershell command to install pre-release version (#6576)


This only seems to work on on Powershell 7. Once installed you can import the module to Powershell 5 / ISE.
[image]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F78208184%2F106265532-791b2200-6227-11eb-9ca8-eea59fbf7b2e.png&data=04%7C01%7C%7Ccd0c15a6ea2f40fe4b8408d8c443c314%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637475142593739842%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dr4rbr027Hpub5cjHqVwxdrZbMfk2i0Y9BVJz%2FRU2PQ%3D&reserved=0>

The module should be installed here: C:\Users\USERNAME\Documents\WindowsPowerShell\Modules\MicrosoftTeams
(If you cannot install PowerShell 7 on the computer that needs the MicrosoftTeams module, download it on a computer that can run PS7 and file transfer it to the same folder on the second computer)

**Comment by RAJU2529** [comment]
@EILI309  @knlp  Small Note must be added in this article,this is my opinion.
@EILI309 What's your opinion in this issue?

**Comment by scanum** [comment]
@RAJU2529 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @knlp @EILI309 @RAJU2529, thank you for your feedback and comments.

I think this information is present in the article:
"If you're using PowerShell 5.1, you must update the **PowerShellGet** module beforehand. After you update **PowerShellGet**, close and reopen an elevated PowerShell session to ensure that the latest **PowerShellGet** is loaded."

Please let me know if you agree so we can close the issue. Thanks!

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
