### ISSUE TITLE
Add note for GCC experience

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6577]
Can we add a note that the approve app widget is not available in GCC tenants?
A Teams service admin must upload apps (no approvals) directly from the app catalog.
Currently it is possible to submit an update using app studio which causes the pending approval to be stuck/hidden from an admin. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1869cfc3-db39-95c3-1509-141224197bf3
* Version Independent ID: 7e6b4267-b1c3-4616-d44d-2b0def64b65b
* Content: [Use the Teams App Submission API to submit and approve your custom apps - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/submit-approve-custom-apps)
* Content Source: [Teams/submit-approve-custom-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/submit-approve-custom-apps.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@TheBluLion Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
