### ISSUE TITLE
MicrosoftTeams PS module logs in to previously logged in tenant

### ISSUE THREAD

**Issue by EILI309** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6578]
Using the latest preview version of MicrosoftTeams 1.1.9

Logging in to Teams for Tenant A, disconnecting (Disconnect-MicrosoftTeams) and logging in to Teams for Tenant B will log in to Tenant A. Cmdlets will provide output from Tenant A, even though the provided credentials were for Tenant B.

This happens with using -Credentials and Interactive login. It also happens if you use -TenantId. Using interactive login and picking "Forget and remove" also does nothing.

Adding to this, attempting to log in to Skype for Business using New-CsOnlineSession while logged in as "Tenant B" will throw an error saying:

"New-CsOnlineSession : Processing data from remote server api.interfaces.records.teams.microsoft.com failed with the following error message: The user '**Tenant A User**' does not have permission to manage this tenant."

I've confirmed that this happens on different machines on different networks, and in Azure Functions (although AZ Function was running locally)

This does not happen in the legacy module 'SkypeOnlineConnector', removing the MicrosoftTeams module and adding it again does not solve the problem. So far the only way I've found around it is to terminate Powershell and start a new window.

Is this the expected behavior? I work for an CSP and we were hoping to upgrade from using 'SkypeOnlineConnector' to 'MicrosoftTeams ' in our automated tasks running in Azure Functions, but due to this problem we cannot make the change.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
