### ISSUE TITLE
Menu drop down on usage reports section missing documentation for call diagnostics reporting

### ISSUE THREAD

**Issue by Erikvg24** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6580]
In Teams Admin Center under Usage Reports there is a Call Diagnostics report that is not represented in our documentation.
![Usage Reports - Call Diagnotics](https://user-images.githubusercontent.com/78224686/106302111-24bf7480-621e-11eb-9070-eca339cb0551.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ade1a4-092c-1132-44df-ee2c683fdd33
* Version Independent ID: 396b1aee-2f40-9895-9b00-07e38d11d31b
* Content: [Microsoft Teams analytics and reporting - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-reporting-reference)
* Content Source: [Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Hi @Erikvg24 
I'll look into this issue. Cindy

**Comment by cichur** [comment]
Hi,
From our expert: 
No, Scheduled report functionality is not there yet for our usage reports. 

However – Customers can get few of the critical reports (Like user activity report ) through graph API. We are also working with MAC team to get additional graph APIs for other reports. 

Hope this helps.

**Comment by scanum** [comment]
@Erikvg24  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
