### ISSUE TITLE
Global Admin is unable to upload custom app

### ISSUE THREAD

**Issue by ivanmaria** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6581]
When I login to teams admin portal, I see the following error:
![image](https://user-images.githubusercontent.com/26500608/106424971-1de86a00-6489-11eb-80a4-5e004e3f25e3.png)

and when I try to upload a custom app, I get the following error:
![image](https://user-images.githubusercontent.com/26500608/106425061-407a8300-6489-11eb-8440-a7d33c794470.png)

In debugger console, I see the following error with status code: 403 Forbidden

`{
  "error": {
    "code": "Forbidden",
    "message": "Failed to execute AuthService backend request GetSkypeTokenRequest. Workload Unknown. Request Url: https://authsvc-server.teams.microsoft.com/v1.0/authz, Request Method: POST, Response Status Code: Forbidden, Response Headers: Strict-Transport-Security: max-age=31536000; includeSubDomains\r\nDate: Mon, 01 Feb 2021 07:00:54 GMT\r\nServer: Kestrel\r\n, Reason Phrase: Forbidden",
    "innerError": {
      "date": "2021-02-01T07:00:54",
      "request-id": "881393dd-e6b6-4831-bda1-6332b2aabe76",
      "client-request-id": "881393dd-e6b6-4831-bda1-6332b2aabe76"
    }
  }
}`

However, If I assign standard license or teams exploratory license to the global admin, then I am able to upload the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 632a367f-0c30-fc21-5040-d2d80f184bdb
* Version Independent ID: 6cab37af-6dcf-d2c1-3d68-14fc7375f1f5
* Content: [Upload your custom apps in the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/upload-custom-apps)
* Content Source: [Teams/upload-custom-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upload-custom-apps.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
