### ISSUE TITLE
SRSDeploymentKit-4.7.15.0 should be updated

### ISSUE THREAD

**Issue by SteffenAssenmacher** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6582]
SRSDeploymentKit-4.7.15.0.msi should be updated, it only supports Windows Version 10.0.18362.418 which is Windows 10 1903 with end of life december 8th 2020. Furthermore it's not available to download in the Volume Licensing Service Center.
This is relevant for:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md
and
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-scale.md
Both use the Same SRSDeploymentKit.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
