### ISSUE TITLE
Credits expiration?

### ISSUE THREAD

**Issue by jgdolph** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#659]
If you do a bulk purchase in January, are the credits good for the whole year?  Might be good to add that to this content whether or not the credits expire.  

Please let us know.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8a7310d-8732-1d60-1d85-7731a7c5a7b8
* Version Independent ID: cc4c6f27-d870-f40d-586b-a15230500e97
* Content: [What are Communications Credits?](https://docs.microsoft.com/en-us/SkypeForBusiness/skype-for-business-and-microsoft-teams-add-on-licensing/what-are-communications-credits)
* Content Source: [Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/what-are-communications-credits.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/what-are-communications-credits.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@jgdolph  Thank you for your feedback

I want to make sure this is addresed in our doccuments. I am going to send this to our Teams/Skype for bunisness team so they can investigate this and get this updated.

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @jgdolph thanks for your feedback! information regarding expiration is on the same section, "Manage Communications Credits" under "Add funds and manage Communications Credits" 

https://docs.microsoft.com/en-us/microsoftteams/add-funds-and-manage-communications-credits

Hope this information has helped you!

Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @jgdolph 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
