### ISSUE TITLE
Update Descriptions of each Metric

### ISSUE THREAD

**Issue by EthanRodz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6594]
[Microsoft Customer has approached me (Customer Engineer in Modern Work working with Teams) with the following questions:
1.	What is the difference between a Channel Message, Reply Message and Post Message?
2.	What is the difference between Meetings Organized, Meetings Participated and Total Meetings?
3.	What metric is Audio Time, Video Time, and Screen Share Time (assuming minutes?)   
4.	Does Audio Time, Video Time, and Screen Share time include 1:1 calls and meetings, or just meetings?

The documentation does not clearly give context to the difference between post messages and channel messages. As well as what total meetings entails or whether Audio Time, Video Time, and Screen Share time includes 1:1 calls and meetings, or just meetings.

Thank you for your consideration.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b138331-2f10-a05d-7e88-68e62e0b3e4f
* Version Independent ID: f923b648-ffe4-8a8a-c189-6e31f1032c10
* Content: [Microsoft Teams usage report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-usage-report)
* Content Source: [Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@EthanRodz  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @EthanRodz 
I tested this on my lab tenant.

Submitted 2 conversations and replied to one of it, and waited for the report to be generated, that resulted in:

2 Post Messages
1 Reply Message
3 Channel Messages

So _Post Messages_ seems to be New Conversations and _Channel Messages_ seems to be the sum of Post + Replies.

The definition of Total meetings is in [this article](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report)

> Total meetings is the total number of scheduled and ad hoc meetings a user participated in during the specified time period.

Will make further tests to understand the question that you asked about audio and video time and get back to you. In case an improvement can be made to the article, will propose it thru a pr.

Thanks

**Comment by EthanRodz** [comment]
Thanks for getting back to me I really appreciate it. Thank you getting the audio and screen share answers for #3 and 4 would be so helpful! 

1.	What is the difference between a Channel Message, Reply Message and Post Message?
2.	What is the difference between Meetings Organized, Meetings Participated and Total Meetings?
3.	What metric is Audio Time, Video Time, and Screen Share Time (assuming minutes?)   
4.	Does Audio Time, Video Time, and Screen Share time include 1:1 calls and meetings, or just meetings?

Also for #2 your explanation on the support doc makes sense until I see my customers numbers. Any idea what is contributing to total meetings so that it goes so high? 
![image](https://user-images.githubusercontent.com/78437857/107091783-eef33080-67c7-11eb-92ad-d1bccafe20db.png)
![chads metting metrics](https://user-images.githubusercontent.com/78437857/107091871-14803a00-67c8-11eb-97ac-ce9edeb67375.jpg)

**Comment by get-itips** [comment]
Hello @EthanRodz how are you?
Made further tests as promised.
Audio Time, Video Time and Screen Share time was measured in minutes in my tests.
Also, it seems, those times are including both meetings and 1:1

![image](https://user-images.githubusercontent.com/36666927/107223455-d5c2cd80-69db-11eb-8da8-5e951dabf4d6.png)

Does this answer your inquiries?

**Comment by EthanRodz** [comment]
Yes, this just about does it. One last comment though, any thoughts on why in the screen shot above, the total meetings is so high at 612,639? Meetings organized is only 429,947. What else may be contributing to the 612,639?

Thank you so much for all the information, this is a big help.

**Comment by get-itips** [comment]
> Yes, this just about does it. One last comment though, any thoughts on why in the screen shot above, the total meetings is so high at 612,639? Meetings organized is only 429,947. What else may be contributing to the 612,639?
> 
> Thank you so much for all the information, this is a big help.

The definition of total meetings says

> Total meetings is the total number of scheduled **and ad hoc meetings** a user participated in during the specified time period.

So probably Ad hoc Meetings?

**Comment by EthanRodz** [comment]
I believe so. Thank you!

After relaying this info to my customer they gave some interesting feedback about the support page that would be very helpful, in their view. 

"To make this page better, it would really help admins to have a little tool tip that describes what each of these means and what they include on mouse over and to list the graph units (minutes, seconds, etc. where applicable), or at a minimum, to have the Microsoft Doc page updated with this info so it is easily referenced."

I thought I would pass off the feedback in case it is relevant to you. Thanks again!

**Comment by get-itips** [comment]
Thanks for the feedback @EthanRodz

**Comment by get-itips** [comment]
@nam31 Please kindly close this issue. Thanks
