### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by mikemorrison111** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6595]
" Fronttline worker | Creates a set of policies and applies those settings to Fronttline workers in your organization."
There's a double 't' in 2 cases

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3f54e11-f5b6-1ab9-6148-f053c66dd79b
* Version Independent ID: 27b514bf-1500-ef6d-ac11-e1860416ec04
* Content: [Manage policy packages in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/manage-policy-packages)
* Content Source: [Teams/manage-policy-packages.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-policy-packages.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Thank you, @mikemorrison111. I made the corrections and pushed the changes.
