### ISSUE TITLE
what is the order in which these polcies are applied ?

### ISSUE THREAD

**Issue by nadeemkhan64** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#660]
i have a default policy that prohibits messaging then i have a user level policy that is applied to select users to allow them to message. however, users with policy to allow message are unable to message as well. it may be that default policy takes precedence. 
am i missing something ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34f3188-0af5-f972-9d28-959f5f7866a2
* Version Independent ID: fab26e11-a729-92a4-3ea6-8668dca55dd0
* Content: [What are Messaging policies in Teams?](https://docs.microsoft.com/en-us/microsoftteams/messaging-policies-in-teams)
* Content Source: [Teams/messaging-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/messaging-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@nadeemkhan64 Thank you for this feedback

I want to make sure you get this answered ASAP. Support will be the quickest way to get your messaging permissions issue resolved. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
