### ISSUE TITLE
A few guiding screenshots would be much helpful:)

### ISSUE THREAD

**Issue by YvetteL11** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6600]
I like MS Office Products and currently trying to use TEAMS.
However, there are some things might make users lives easier:

1. The introduction/user manual on your website contains too much words and it's hard for readers to read and to look for the exact info we need.

2. The web page includes tons of word guidance yet few pictures for us to know how should we do practically.

I'm not expecting this message would be seen or found immediately. But it would be great to have some visual adds in the future.

Thank you in advance.
- Yvette

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 2167d5b2-c4c4-3164-2ed2-9582c8a0f95b
* Version Independent ID: cbbf9c78-5708-a0a9-31c3-d2cb4b31f6d3
* Content: [查看、變更及重設使用者的會議 ID - Microsoft Teams](https://docs.microsoft.com/zh-tw/microsoftteams/see-change-and-reset-a-conference-id-assigned-to-a-user-in-teams#view-and-reset-conference-ids)
* Content Source: [Teams/see-change-and-reset-a-conference-id-assigned-to-a-user-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/see-change-and-reset-a-conference-id-assigned-to-a-user-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@YvetteL11 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
