### ISSUE TITLE
When will France be supported for live events 

### ISSUE THREAD

**Issue by vltt-iarc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6601]
Hi, 

It would be good to have a clear roadmap on when regions (eg France, Germany, etc) will be supported.
It would also a good idea to give people workarounds so they can take full benefits of their licences.
Finally, at least give us the information why some regions are not supported and some other are.

Best 
R.

**Comment by scanum** [comment]
@vltt-iarc Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
