### ISSUE TITLE
Options are not there

### ISSUE THREAD

**Issue by CerbStarraiser** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6602]
These instructions seem to be wrong or for an older version--there is no audio conferencing options for our users, despite them having the audio conferencing license assigned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28bbd6d3-a2ef-c308-42ec-90ba27588821
* Version Independent ID: d7ad4fbd-d816-91a7-58e7-7a153eecd8ec
* Content: [Manage Audio Conferencing settings for users - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/manage-the-audio-conferencing-settings-for-a-user-in-teams)
* Content Source: [Teams/manage-the-audio-conferencing-settings-for-a-user-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-the-audio-conferencing-settings-for-a-user-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@CerbStarraiser  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @CerbStarraiser how are you?
I could follow these instructions in my lab tenant.
If you are still having issues besides having the required licenses, I would recommend opening a support request directly from your tenant.
I hope this information helps you.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
