### ISSUE TITLE
Bad security advice on Microsoft webpage

### ISSUE THREAD

**Issue by wdeguara** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6607]
[Enter feedback here]
Some pretty bad security advice in step 2 of the below Microsoft web page where the author recommends organisations exempt *.webex.com*, *.zoom.us*, *.zoom.com*, *.zoomgov.com* from Defender ATP safe link re-write.   If a Microsoft customer was to follow that advice they would introduce a significant risk by making it relatively easy for a malicious party to send them email with crafted urls that can easily bypass any ATP protection (ie. an email containing a web link http://attack.zoom.us.malware.com would not be re-written.   ref: 
https://docs.microsoft.com/en-us/microsoftteams/rooms/third-party-join#step-2-configure-office-365-threat-protection-and-link-rewrite

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c62081e-2421-80b9-8ba9-aaf8fd55e432
* Version Independent ID: 5df3c5e5-978f-cfa7-9e5c-3cd7f65fa8ff
* Content: [Enable Teams Rooms devices to join third-party meetings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/third-party-join#step-2-configure-office-365-threat-protection-and-link-rewrite)
* Content Source: [Teams/rooms/third-party-join.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/third-party-join.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@wdeguara Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
