### ISSUE TITLE
Meeting expiration for Meet now Meetings

### ISSUE THREAD

**Issue by sewagner** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6609]
[Enter feedback here]

Why is the expiration "not applicable" for ad-hoc (Meet now) meetings? You can extract the link during the meeting and share or put the Link in an meeting invite (such as Lotus Notes). I'am a Teams Technical Specialist at Microsoft and my customer asks about the expiration of the meeting link. Please give some more information's on this page. I assume its 60 days as well?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#meetings-and-calls)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@sewagner Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by sewagner** [comment]
Why I should open a service ticket? This is nothing related to a Tenant. Its just about a unlogical documentation.

Viele Grüße / Best regards,

Sebastian Wagner<https://aka.ms/sewagner>
MW Teams Technical Specialist | O: +49 30 39097459<tel:+49%2030%2039097459> | M: +49 151 4406 3712<tel:+49%20151%204406%203712> | Chat with me<https://teams.microsoft.com/l/chat/0/0?users=sewagner@microsoft.com> [cid:image001.png@01D6FAFD.AC181E60]

Von: Manuela Scanu <notifications@github.com>
Gesendet: Donnerstag, 4. Februar 2021 13:56
An: MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com>
Cc: Sebastian Wagner <Sebastian.Wagner@microsoft.com>; Mention <mention@noreply.github.com>
Betreff: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Meeting expiration for Meet now Meetings (#6609)


@sewagner<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsewagner&data=04%7C01%7Csebastian.wagner%40microsoft.com%7Cf445550369ef467f09e808d8c90c2e77%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637480401477447060%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OiEOT%2BdVukqxHhQ4ustKDFAKsGQn4FET2uwxSseDI0w%3D&reserved=0> Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Foffice365%2Fadmin%2Fcontact-support-for-business-products&data=04%7C01%7Csebastian.wagner%40microsoft.com%7Cf445550369ef467f09e808d8c90c2e77%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637480401477447060%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DWYugtghmXdS%2Bpb9%2FyNLAW%2FCFgeZ02KHWmIAUG2wbU4%3D&reserved=0>
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

-
