### ISSUE TITLE
GCC Footnote

### ISSUE THREAD

**Issue by expatmarcos** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6615]
Footnote 5 is missing the number of members a team in GCC can have.

5 Teams in GCC can only accommodate ? members and teams in GCCH/DoD can only accommodate 2,500 members.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@expatmarcos Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@expatmarcos thank you for pointing this out and helping improve MS Docs. The article has been updated mentioning 5,000 members. Please confirm from your side (footnote 6)

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
