### ISSUE TITLE
Sync between Teams and Outlook Calendar with notifications?

### ISSUE THREAD

**Issue by 214866f** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#662]
Hi
I returned back to work today after being on leave last Friday.
This was set as an Out Of Office in my Office 365 Calendar.
On Friday a colleague sent me a conversation using Teams.
I did not reply as I was on Leave and Teams did not say anything.
How can we get Teams to check with Office 365 and then notify the conversation sender that I was OOO?
Cheers
Gordon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9b7f77-061d-a224-ff1c-8d3e15d21221
* Version Independent ID: 00fa9550-c4c4-3398-ffbb-271cc724048f
* Content: [Manage Microsoft Teams features in your Office 365 organization](https://docs.microsoft.com/en-us/microsoftteams/enable-features-office-365)
* Content Source: [Teams/enable-features-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enable-features-office-365.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@214866f Thank you for this feedback

I want to make sure that this OOO issue gets worked on as soon as possible. Support will be able to work this issue to resolution.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
