### ISSUE TITLE
Registry Start Key points to wrong location

### ISSUE THREAD

**Issue by ajscott** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6622]
When "ALLUSERS=1" flag is used, the 64 bit installer puts files in the "Program Files (x86)" path but the auto run entry in the registry points to "Program Files" instead. This causes the application to never install for users.

Actual Install path:
%ProgramFiles(x86)%\Teams Installer\Teams.exe

Reg startup entry:
%ProgramFiles%\Teams Installer\Teams.exe --checkInstall --source=default

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Teams using Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Hi @ajscott 
 Is it possible that you're mismatching the Teams and OS bitness, are trying to use the 32-bit version of teams on a 64-bit OS (instead of 64bit teams with 64bit os)?

**Comment by lindspea** [comment]
@ajscott please let me know if @cichur suggestion has helped at all to solve this issue.

**Comment by ajscott** [comment]
@lindspea It does not. 

Both the Teams_windows.msi and Teams_windows_x64.msi use "[ProgramFilesFolder]" as the installation destination property. On a 64 bit system this directs to %ProgramFiles(x86)%. 

The Teams_Windows_x64.msi file needs to be changed to use [ProgramFiles64Folder] to direct to %ProgramFiles% on a 64 bit system.

MSI documentation stating this:
https://docs.microsoft.com/en-us/windows/win32/msi/programfiles64folder

**Comment by lindspea** [comment]
@cichur can you assist please.

**Comment by cichur** [comment]
@lindspea Yes, I'll contact the SME. Cindy

**Comment by lindspea** [comment]
@ajscott at a quick glance I see the article has been updated this week. Please have a look and let me know if all is in order from your side.

**Comment by ajscott** [comment]
Installer appears to work correctly now. Thank you.
