### ISSUE TITLE
Microsoft Teams meeting add-on for Google Workspace. for free accounts

### ISSUE THREAD

**Issue by hsynkrtl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6625]
Is that procedure also applieable for free microsoft accounts? I am not able to find that app also not able to activate it as mentioned i a tutorial over the powershell because ps isn't available on free accounts!

But Teams works fine with the free account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c3be94-d640-a20c-ac06-2653f443b74e
* Version Independent ID: 4760af98-c4e9-ab6a-6745-1381ffc068cc
* Content: [Set up Microsoft Teams meeting add-on for Google Workspace - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/google-workspace-addon-teams)
* Content Source: [Teams/google-workspace-addon-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/google-workspace-addon-teams.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Hello @hsynkrtl ,
Thank you for your question. This plug in works only with org or school account. Not free accounts. - Cindy
