### ISSUE TITLE
Missing latest release notes for 1.1.8, 1.1.9, and 1.1.10-preview releases

### ISSUE THREAD

**Issue by miketheitguy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6626]
It seems we're up to 1.1.10-preview on the PowerShell Gallery yet this page is missing release notes :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 173b5929-529b-938b-b6ab-59f05a5d69a8
* Version Independent ID: 0a3dfe5e-938f-933d-637e-b7449e3b8aa5
* Content: [Microsoft Teams PowerShell Release Notes - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-release-notes)
* Content Source: [Teams/teams-powershell-release-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-release-notes.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
@miketheitguy Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@brandber @dstrome

**Comment by dstrome** [comment]
resolved
