### ISSUE TITLE
Jargon

### ISSUE THREAD

**Issue by drewjames1234** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6629]
With all due respect, do you expect people to know what you are referring to here?
_Transmission Control Protocol (TCP) is considered a failback transport and not the primary transport you want for real-time media. The reason it's a failback transport is due to the stateful nature of TCP._

My suggestion -  create context and explain what you mean before stating pure jargon.  This does not tell me what TCP is, because I have no idea what 'failback transport' is, or what 'stateful nature' means.  I am talking as someone who has known English for over 50 years and generally go out my way to educate myself

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a04f5de-2679-37c7-7d00-607471ea516d
* Version Independent ID: c96ec0af-910a-d9f8-9d3b-95564b39d7fa
* Content: [Use CQD to manage call and meeting quality in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/quality-of-experience-review-guide#quality-investigations)
* Content Source: [Teams/quality-of-experience-review-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/quality-of-experience-review-guide.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@drewjames1234 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@drewjames1234 thank you for reaching out and helping improve MS Docs.  Please have a look at these two articles and let me know if it helps at all and I'll add a link to this document to help other users. https://docs.microsoft.com/MicrosoftTeams/rooms/rooms-prep and https://techcommunity.microsoft.com/t5/microsoft-teams/ports-needed-for-microsoft-teams/m-p/28417

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
