### ISSUE TITLE
Article Does Not Say If SQL 2016 SP1 And SP2 Also Supported

### ISSUE THREAD

**Issue by TheDarkLord123** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#663]
- the article contradicts this article at the time: 
https://support.microsoft.com/en-us/help/4100776/sql-server-2016-sp1-is-available-for-the-back-end-servers-of-skype

- also SQL Server SP2 has been released in April - not clear if supported as Skype Server backend.

Thank you!
- the dark lord

**Comment by AndreaBarr** [comment]
@TheDarkLord123 Thank you for this feedback. 

I am getting this information over to the Teams team so we can get it investigated and updated properly. 

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @TheDarkLord123 thanks for your comments and feedback, we appreciate them.
Your issue description does not reference a specific document, but I found one that might be the one https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/server-requirements#DBs is this the correct document?

Document has been updated after you created this issue, now including SQL Server 2016 SP1 and SP2 support.

Hope this information helps you.

Thank you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @TheDarkLord123  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
