### ISSUE TITLE
Circular definition

### ISSUE THREAD

**Issue by drewjames1234** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6630]
_Common subnets are specific private subnets that are used by hotels, home networks, hotspots, and similar areas. These subnets are difficult to triage due to their widespread use. 
[Enter feedback here]_

I couldn't see any previous reference to 'subnets' on this page, so this appears to be a circular definition and not helpful to the learner. What is a subnet?  Needs context

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a04f5de-2679-37c7-7d00-607471ea516d
* Version Independent ID: c96ec0af-910a-d9f8-9d3b-95564b39d7fa
* Content: [Use CQD to manage call and meeting quality in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/quality-of-experience-review-guide)
* Content Source: [Teams/quality-of-experience-review-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/quality-of-experience-review-guide.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@drewjames1234 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@drewjames1234 thanks for reaching out again. Please have a look at this article and let me know if it helps at all. https://docs.microsoft.com/troubleshoot/windows-client/networking/tcpip-addressing-and-subnetting

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
