### ISSUE TITLE
NO definition -  UDP

### ISSUE THREAD

**Issue by drewjames1234** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6631]
_This report identifies the volume of TCP versus UDP usage reporting on the latest month for audio, video, and video-based screen sharing (VBSS)._

I can't find any previous reference to UDP on this page.  How is the learner supposed to know what is meant here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a04f5de-2679-37c7-7d00-607471ea516d
* Version Independent ID: c96ec0af-910a-d9f8-9d3b-95564b39d7fa
* Content: [Use CQD to manage call and meeting quality in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/quality-of-experience-review-guide)
* Content Source: [Teams/quality-of-experience-review-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/quality-of-experience-review-guide.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@drewjames1234 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@drewjames1234 thank you for reaching out. This part of the article mentions UDP - https://docs.microsoft.com/en-us/MicrosoftTeams/quality-of-experience-review-guide#tcp. Is there any other specific information you are looking for?

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
