### ISSUE TITLE
PowerShell script with AAD joined profiles and AutoPilot

### ISSUE THREAD

**Issue by AndrewStalkerAU** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6632]
Hi, I have tried implementing the supplied PowerShell script through Intune and I have had to make a modification to accommodate devices that are AAD joined as they do not use the Domain network profile as they are not AD domain joined and therefore this script needed to be changed on line 20 to read '-Profile Any' instead of '-Profile Domain'.

Also, this script does not work when deployed to a device during Autopilot as the script is triggered before the user profile exists so therefore no rules are created. The script then never re-runs after the user logon unless I setup a scheduled task triggered by user logon.

The third issue is that unless I setup the scheduled task method the script does not accommodate for users who logon to the device after the script has ran. This is more of an Intune issue, but still a problem with this method of creating firewall rules.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients#sample-powershell-script)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@AndrewStalkerAU Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
