### ISSUE TITLE
conflicts

### ISSUE THREAD

**Issue by howardzhangmsft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#664]
The following statement "The installation of additional NICs to support the PSTN IP address configuration on stand-alone Mediation Servers is not supported." conflicts with statement "On standalone Mediation Servers the installation of additional network interface cards (NICs) to allow the configuration of a specific PSTN IP address is supported. " from below article:
https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/server-requirements 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a8b25c0-a81d-44e1-e0fb-b5f2ac6e1f66
* Version Independent ID: 202330a0-4da0-c1c2-8241-c85ebc6d7b52
* Content: [Configure IP address types in Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/network-requirements/ip-address-types)
* Content Source: [Skype/SfbServer/plan-your-deployment/network-requirements/ip-address-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/network-requirements/ip-address-types.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Looking into this revealed that the server requirements article was incorrect, I've passed this to the other article's owner.

**Comment by AndreaBarr** [comment]
@howardzhangmsft Thank you for this feedback

I want to make sure these article issue get the proper attention. I am sending this to the Teams/Skype team so they can investigate it and get these updated.

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by scanum** [comment]
@MicrosoftHeidi Any updates on this issue? Thanks!

**Comment by msbemba** [comment]
@howardzhangmsft Thank you for your feedback. We have made changes to the service requirements documents via PR https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/2334

**Comment by scanum** [comment]
@howardzhangmsft - Dual NIC on Standalone Mediation Servers is supported since OCS 2007:
https://docs.microsoft.com/en-us/previous-versions/office/communications-server/ff518437(v=ocs.14)

Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
