### ISSUE TITLE
Missing known issues on this page - Use OneDrive for Business and SharePoint or Stream for meeting recordings

### ISSUE THREAD

**Issue by AllanNordea** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6640]
Hi, we've just started to test out OneDrive and SharePoint for Teams meeting recordings and we miss info on known issues and what to do about them on [this page](https://docs.microsoft.com/en-us/microsoftteams/tmr-meeting-recording-change#permissions-or-role-based-access). 
E.g.
1. When meeting attendees in a "standard" meeting click on the recording, in the meeting chat in the desktop app, they get a prompt when the browser opens to enter their email address. This does not happen for channel recordings or (of course) when using the web app.
![image](https://user-images.githubusercontent.com/78824505/107429298-0dd52800-6b24-11eb-8f3c-a71e546723ef.png)

2. When the recording is saved then there suddenly are three versions saved?
![image](https://user-images.githubusercontent.com/78824505/107429660-72908280-6b24-11eb-80ae-72fe091044df.png)

Looking forward to feedback.

Regards,
Allan
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8935e913-806f-a92c-d09e-e67df4ffd1b4
* Version Independent ID: c7a41cde-66dd-d7cd-1316-42d20ed4841a
* Content: [Use OneDrive for Business and SharePoint for meeting recordings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/tmr-meeting-recording-change#feedback)
* Content Source: [Teams/tmr-meeting-recording-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tmr-meeting-recording-change.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by naridi** [comment]
Hi Allen, I'm taking a look into your questions. Appreciate you sharing these observations with us. 

Regarding #1, may you clarify the frequency of how often a unique user sees this login message:

- only once (and never again for any new videos opened)
- only once (and every time they open a new video)
- every time they open the same or new video

Best,
Nibal

**Comment by scanum** [comment]
@AllanNordea Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
