### ISSUE TITLE
QoS scripts on https://docs.microsoft.com/en-us/microsoftteams/qos-in-teams

### ISSUE THREAD

**Issue by oliver27b** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6643]
the scripts are great, thank you.

they are not compatible with gpedit.msc 

when you load gp editor and go to QoS sections you get an error. this should be fixed, please.

the error is 
Title Bar: QoS Policy
Message box: "Errors while reading policies from this GPO, not all policies are displayed."

the QoS policies are empty.

it would be helpful to view the policies in the Local Group Policy Editor as well as in Powershell
![image](https://user-images.githubusercontent.com/36059138/107528946-61795d00-6b88-11eb-8797-b25161efa6e0.png)

ALSO:  the copy links on the page... they copy the script into two lines (should be single line of text for pasting into Powershell, not two lines. this produces an annoyance error.   by pasting into notepad, then combining the two lines into one, then pasting into powershell the scripts work perfectly.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76c2487c-044d-1349-708a-5841fcb21ab8
* Version Independent ID: b7033454-1a9c-48d4-8004-78415c5feb89
* Content: [Implement Quality of Service in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/qos-in-teams)
* Content Source: [Teams/QoS-in-Teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/QoS-in-Teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by RAJU2529** [comment]
@oliver27b , try to install the latest  group policy templates  
**https://www.microsoft.com/download/details.aspx?id=102157**

**Comment by dariomws** [comment]
Hi @oliver27b, thank you for your feedback.

My apologies but I don't understand. What scripts are you talking about?

I've verified the GPO settings on Windows 10 and Windows Servers 2016 and no issues:
![image](https://user-images.githubusercontent.com/33589238/108251294-fb677980-7135-11eb-87a5-e18f9245280e.png)

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
