### ISSUE TITLE
Inaccurate information

### ISSUE THREAD

**Issue by neilslater123** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6645]
In the section "Install the Skype for Business Online Connector"

There is a note "Skype for Business Online Connector is currently part of the latest Teams PowerShell module. If you're using the latest Teams PowerShell public release, you don't need to install the Skype for Business Online Connector."

That's not accurate.

There is a link to the latest public release (1.1.6) and it does not include the Skype for Business Online Connector.

It needs to say PREVIEW release (or better, give a version number).

There is a second note on the page and that *does* have the correct PREVIEW wording.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd283f6e-3865-ed70-d663-cc461ee8ba57
* Version Independent ID: 2450d311-fc04-d8b6-b4a2-b1890ec6fc3e
* Content: [Install Microsoft Teams PowerShell - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install)
* Content Source: [Teams/teams-powershell-install.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-install.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by dariomws** [comment]
Hi @neilslater123, thank you for your feedback.

I confirm that the latest public version (1.1.6) includes the Skype for Business Online Connector:
![image](https://user-images.githubusercontent.com/33589238/108252272-3ae29580-7137-11eb-9df1-74a810492196.png)

If you are having problems, please verify with the following command that 1.1.6 is the only version installed on your machine:
Get-Module MicrosoftTeams -ListAvailable

If you still have problems, I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by neilslater123** [comment]
Thanks for your response.
You are (of course!) absolutely correct: the latest public version (1.1.6) includes the Skype for Business Online Connector.

I think the documentation could be improved as follows:
1. Remove the entire section "Install the Skype for Business Online Connector"
     These instructions are not required.
2. Move the section "Install Teams PowerShell public preview" to the end of the article
     Then the flow of the article is easy to follow: "Install the Teams PowerShell module" and "Sign In"
