### ISSUE TITLE
Typo - duplicate word

### ISSUE THREAD

**Issue by azha23** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6647]
To park and retrieve calls, a user must be an Enterprise Voice user **and and** must be included in a call park policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e03ef3d-81d8-c98f-8427-fe7c008ea30f
* Version Independent ID: 17af3418-b94d-f233-60c0-778b2e8dc02b
* Content: [Call park and retrieve in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/call-park-and-retrieve)
* Content Source: [Teams/call-park-and-retrieve.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/call-park-and-retrieve.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by RAJU2529** [comment]
@scanum , assign a user to verify this PR #6650

**Comment by nam31** [comment]
Closing via #6650 
Thanks
