### ISSUE TITLE
Contents don't clearly reflect new MTR licenses

### ISSUE THREAD

**Issue by dinocaputo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6649]
The contents listed here are confusing.  The new Teams Rooms SKU's are clearly listed here --> https://rooms.microsoft.com/
I feel this page needs some updating to reflect the two new SKUs that capture all the requirements.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-licensing.md)
* Service: **skype-for-business-online**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @dinocaputo, thank you for your valuable feedback.

I'm applying and update; I appreciate any feedback:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/6684
