### ISSUE TITLE
Simple text cleanup

### ISSUE THREAD

**Issue by germanmikrowave** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6654]
The text for the line item "See the out-of-office message of" is cut off and added to the below line. Just needs a little cleanup. See jump link below.

https://docs.microsoft.com/en-us/microsoftteams/communicate-with-users-from-other-organizations#things-your-users-can-do

See the out-of-office message of | No | Yes
Block someone in another organization someone in another organization | No | Yes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f080a5c-4268-1db4-566f-f1edc27920b5
* Version Independent ID: ac556a92-58af-3e05-f53b-0fc00afc96c0
* Content: [Call and chat with users from other organizations - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/communicate-with-users-from-other-organizations)
* Content Source: [Teams/communicate-with-users-from-other-organizations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/communicate-with-users-from-other-organizations.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by nam31** [comment]
Closing via #6733
