### ISSUE TITLE
table doesn't specify that 'Enable-CsOnlineSessionForReconnection' isn't in the MicrosoftTeams module

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6655]
lost hours trying to understand why enable-csonlinesessionforreconnection wasn't working correctly.

I had both the Skype for Business Online module *and* the MicrosoftTeams module.  Connecting using the MicrosoftTeams module, then using the enable-csonlinesessionforreconnection [which I assumed was part of MicrosoftTeams module as well, but which was actually only in the SkypeOnlineConnector module], it kept failing.

When I removed SkypeOnlineConnector, Powershell tells me 'The term 'Enable-CsOnlineSessionForReconnection' is not recognized as the name of a cmdlet...'

This page - and *ALL* Microsoft documentation I've seen on this topic - encourages us to use MicrosoftTeams module, but  *NEGLECTS* to specify that enable-csonlinesessionforreconnection is missing.  Gross negligence.

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 173b5929-529b-938b-b6ab-59f05a5d69a8
* Version Independent ID: 0a3dfe5e-938f-933d-637e-b7449e3b8aa5
* Content: [Microsoft Teams PowerShell Release Notes - Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/teams-powershell-release-notes)
* Content Source: [Teams/teams-powershell-release-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-release-notes.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by anwarmahmood1** [comment]
Andrés Gorzelany discovered this; he fixed it himself;
https://get-itips.capazero.net/posts/s4b-reconnect-teams

If he can do it, you can, too.  This functionality is DEEPLY needed, especially for very large tenancies.  If it wasn't, Microsoft wouldn't have introduced it in the first place.

**Comment by VLG17** [comment]
@anwarmahmood1 The article you linked containes the list of cmdlets that are natively part of the Teams PowerShell module. Enable-CsOnlineSessionForReconnection is not part of this list, so it should be clear that it's not included in the Teams PowerShell module.

The article also states that 

> The Teams cmdlets in the Skype for Business Online Connector module are not displayed. However, as those cmdlets are migrated natively into Teams PowerShell, we'll add them to this table.

so if Enable-CsOnlineSessionForReconnection will ever be added to the Teams PowerShell module, this change will be reflected in the documentation.

What we could do is add a explicit note somewhere in the article about the fact that Enable-CsOnlineSessionForReconnection is not in the Teams PowerShell module. Do you think that would help?

**Comment by anwarmahmood1** [comment]
Yes, definitely.

(it's most relevant to large organisations with lots of users; batch jobs processing tens/hundreds of thousands of users - such as at Universities - take a long time.)

It's an important limitation.

**Comment by anwarmahmood1** [comment]
The best resolution would be adding the command but putting "no" under 'Available in Public Preview' and 'Available in GA' columns.  That way it's crystal clear you're aware of this, but this, but it isn't yet available. 

or, if it's coming soon, you could say 'coming soon', or if there's a UserVoice, a please upvote comment, etc.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
