### ISSUE TITLE
Teams creation limit for Azure AD app registration

### ISSUE THREAD

**Issue by SashaSidorenko** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6656]
Hi there!

I'm planning to set up the Graph API application that would create teams using Azure AD APP Registration for authentication in the tenant.
What limit on teams creation is for Azure AD App Registration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by VLG17** [comment]
@SashaSidorenko From the article you linked we see that:

> In Microsoft Graph, Microsoft Teams is represented by a [group resource](https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0)

And the limit of groups an admin can create is 500k per tenant, as described [here](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups?view=o365-worldwide#group-limits).

**Comment by nam31** [comment]
@SashaSidorenko  Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
