### ISSUE TITLE
What if end user dont have OneDrive site? Where will the Recordings then go?

### ISSUE THREAD

**Issue by stche** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6657]
[Enter feedback here]

Hi there,
sicne the announcement of Streams storing new meetings after march into SPO and ODB, we received a couple customer requests where they do have TEAMS enabled, means a SharePoint site in the back exists but End Users still dont have a OneDrive site yet provisioned/or ODB is yet not deployed for them.

Question is:  what will happen after march with a recording that would go to ODB but ODB site is not there?
DO we have any error handling for that?
How will it display to the End User (recorder)?
Will a recording even be possible without ODB behind?

We would appreciate this to be documented soonest due to many request hitting us in Fasttrack as well as Support.

Thanks and kr
Steve

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8935e913-806f-a92c-d09e-e67df4ffd1b4
* Version Independent ID: c7a41cde-66dd-d7cd-1316-42d20ed4841a
* Content: [Use OneDrive for Business and SharePoint for meeting recordings - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/tmr-meeting-recording-change)
* Content Source: [Teams/tmr-meeting-recording-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tmr-meeting-recording-change.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by ZygomaticArch** [comment]
Hi, as a Teams user, I can say that with no access to OneDrive or SharePoint, my Teams recording appeared in the chat portion with the option to download. Once selected, the download defaulted (it did not allow me to choose) to the 'Downloads' folder within physical space of the computer I use.

**Comment by nam31** [comment]
@cichur , can you please help?
Thanks

**Comment by cichur** [comment]
Hi @stche

I added this FAQ to the article yesterday. Thank you for your question. 

Where does the recording go if the user doesn't have OneDrive for Business or SharePoint?

The recording will land in our temporary storage location where it will be held for 21 days. During that time, the organizer must download the recording. If not downloaded within 21 days, the recording is deleted.
