### ISSUE TITLE
Auto attendant - not adequately defined

### ISSUE THREAD

**Issue by drewjames1234** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6659]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23ff8713-7e33-ad8e-99df-9308a7c006d7
* Version Independent ID: c9263eba-599b-831b-37fb-837046df9d6a
* Content: [What are Cloud auto attendants? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/what-are-phone-system-auto-attendants#getting-started)
* Content Source: [Teams/what-are-phone-system-auto-attendants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-phone-system-auto-attendants.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @drewjames1234 how are you? I see you edited your post removing your question, do you still have this inquiry? Thanks

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
