### ISSUE TITLE
instead on "on-administrator", it should be "non-administrator"

### ISSUE THREAD

**Issue by JosephSaad** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6660]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81440b2f-391b-5856-a216-15866f37082a
* Version Independent ID: cdd15cd4-d4ed-c413-e2b9-ebf6dad8b33b
* Content: [Use activity reports for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-activity-reports)
* Content Source: [Teams/teams-activity-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-activity-reports.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
