### ISSUE TITLE
Clarifications

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6661]
A couple of things:

1. In the first note, it says: "In the scenario where no dial plan normalization rules apply to a dialed number, the dialed string is still normalized". It is not clear whether this means that the Service Plan normalization rules are always applied, or something else. 
2. Under the heading "Creating your new tenant dial plan", the text refers to any dial plan, not tenant dial plans.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 847c0505-3441-b5db-1f81-c7759bffd1e3
* Version Independent ID: 3c6b3820-349f-caf5-c510-a771a3b7a770
* Content: [What are dial plans? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/what-are-dial-plans)
* Content Source: [Teams/what-are-dial-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-dial-plans.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by Reeced40** [comment]
@Air-Git thank you for reaching out. Regarding the dial plans for tenants, do you think this link will be helpful to other users if it had to be added to this article? https://docs.microsoft.com/microsoftteams/create-and-manage-dial-plans

**Comment by Air-Git** [comment]
I think it is just a mistake in the heading. Instead of "Create your new tenant dial plan", it should just read "Create your new dial plan".

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
