### ISSUE TITLE
The point of reporting labels not clear

### ISSUE THREAD

**Issue by drewjames1234** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6662]
Having read this, it is not clear to me what the point is of a reporting label. It says they are 'used in your organization to indicate the physical locations of offices, buildings, or organizational sites.'  But for what end?  I gather this has something to do with Call Quality, as one of the Teams administrator exam questions points to this, but again, this is not clear. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f8119c9-61af-b469-af98-ddd37764c0ca
* Version Independent ID: 7d829a74-9df7-5b6f-8e1c-44d3e5d38f75
* Content: [Add and update reporting labels - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/learn-more-about-site-upload)
* Content Source: [Teams/learn-more-about-site-upload.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/learn-more-about-site-upload.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by Reeced40** [comment]
@drewjames1234 thank you for reaching out. Please see information in the article - "Reporting labels are used in your organization to indicate the physical locations of offices, buildings, or organizational sites. The Reporting labels page in the Microsoft Teams admin center lets you provide a text file (.csv or .tsv) containing a list of physical locations and their associated network subnets. This file is used by Call Analytics for generating reports. When you upload your subnet mapping, the reports provided by these services will contain the location names as well, making the reports easier to understand and use for remediating any potential issues." It helps keep track of all calls and where they were directed to for company reporting purposes, should there be any discrepencies in any of the reports. It gives detailed information of call locations, etc. Hope this helps answer your question. Let me know if you need anything further.

**Comment by Reeced40** [comment]
@nam31 please can this be checked for merge.

**Comment by Reeced40** [comment]
@drewjames1234 has my reply helped at all and can we close this issue or do you require further assistance?
