### ISSUE TITLE
Point of location names not clear.

### ISSUE THREAD

**Issue by drewjames1234** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6663]
Having read this, it is not clear to me what the point is a reporting label and location name. It says they are 'used in your organization to indicate the physical locations of offices, buildings, or organizational sites.'  It then reads 'When you upload your subnet mapping, the reports provided by these services will contain the location names as well, making the reports easier to understand and use for remediating any potential issues.

But how?  How does 'including the location name make reports easier to understand / use for remediating any potential issues'?  I'm thinking of a situation in which members of a team are working remotely and not in one centralised space.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f8119c9-61af-b469-af98-ddd37764c0ca
* Version Independent ID: 7d829a74-9df7-5b6f-8e1c-44d3e5d38f75
* Content: [Add and update reporting labels - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/learn-more-about-site-upload)
* Content Source: [Teams/learn-more-about-site-upload.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/learn-more-about-site-upload.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by Reeced40** [comment]
@drewjames1234 related issue https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6662
