### ISSUE TITLE
The form to request numbers is not sufficient.

### ISSUE THREAD

**Issue by hmank** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6666]
In looking at the form and only having the ability to request 1 number at a time is very limiting. Most customer in the enterprise space do not just have a single location, they have multiple locations and thousands of numbers required. 

It would be good to have the ability to request a single form for all Emergency locations along with the RegionalGroup (area codes), CountryOrRegion that are tied to those emergency locations. If I have 50 addresses, having to submit 50 forms and keep track of those is very complicated.

Thanks
Habib

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84a7ee3d-20b1-5989-b793-10fecef045fa
* Version Independent ID: af8057dd-5766-db72-e98b-d2e3947691d6
* Content: [Phone number management for Canada - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/manage-phone-numbers-for-your-organization/phone-number-management-for-canada)
* Content Source: [Teams/manage-phone-numbers-for-your-organization/phone-number-management-for-canada.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-phone-numbers-for-your-organization/phone-number-management-for-canada.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by nam31** [comment]
@hmank, Thank you for your feedback
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the Microsoft Teams UserVoice. You might find others have made a similar request that you can add to, or you can open a new one.
Thank you for your contribution to make the docs better! Much appreciated!
