### ISSUE TITLE
Change of TeamsUserActivity report column names

### ISSUE THREAD

**Issue by jagobrown** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6667]
Dear MS Docs,
I noticed  TeamsUserActivity report column names have changed today.  How likely are they to change again?
This change broke a  workflow we have
:-(
Because I'm pretty busy & don't have time to look deeply into this I've assumed the `old` to -->  `new` mappings are as follows.  Is this correct?

1. "MeetingsOrganized" | MeetingsOrganizedScheduledOneTime
2. "MeetingsOrganizedScheduled" | MeetingsOrganizedScheduledRecurring
3. "MeetingsOrganizedAdhoc" | MeetingsOrganizedAdhoc
4. "TotalMeetings" | TotalMeetingsOrganized
5.          **  new field  | MeetingsParticipatedScheduledOneTime
6. "MeetingsParticipatedScheduled" | MeetingsParticipatedScheduledRecurring
7. "MeetingsParticipatedAdhoc" | MeetingsParticipatedAdhoc
8. MeetingsParticipated? | TotalMeetingsParticipated

?
Jago

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2758a3d6-c646-dcb0-2a31-c7b9b84e780b
* Version Independent ID: 8704c9fe-f8b0-82d2-bd83-3fd1a9ad638d
* Content: [Microsoft Teams user activity report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report)
* Content Source: [Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by VLG17** [comment]
Hi @jagobrown, I confirm your mappings are correct. Regarding the cadence of updating the report, I recommend providing this feedback via the [UserVoice channel](https://microsoftteams.uservoice.com/forums/555103-public), which is actively monitored by the Product Group.

If we get an official statement on this topic, we can add it to the article you referenced.

**Comment by nam31** [comment]
@jagobrown @ Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Comment by jagobrown** [comment]
Thanks for response VLG17.  It was useful to have mappings confirmed
It is a really useful/rich report  - so hopefully there will mostly be additional cols added rather than changes to existing in future
Jago
