### ISSUE TITLE
AudioCodes link is to marketing, not technical docs

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6669]
The AudioCodes link takes you to a marketing section, not the technical documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 183fc921-e9b1-cc74-2bcb-26d32b994919
* Version Independent ID: 1765bda3-dd62-76d7-1e2d-9f5496ac9094
* Content: [Direct Routing SBA - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-survivable-branch-appliance)
* Content Source: [Teams/direct-routing-survivable-branch-appliance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-survivable-branch-appliance.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by RAJU2529** [comment]
@TorrenManson  I also checked link, I conformed that link belongs to technical specifications of audio code product .
You can see at the bottom of the Page

**Comment by TorrenManson** [comment]
Hi,

I agree that the link provided is to technical specs, however the preamble to the 4 links promises “…step-by-step guidance on how to configure your Session Border Controller with the embedded Survivable Branch Appliance, see the documentation provided by your SBC vendor:”

Which the AudioCodes link does not bring us to. The AudioCodes link could be adjusted to be this link Technical Documents (audiocodes.com)<https://www.audiocodes.com/library/technical-documents?query=sba> https://www.audiocodes.com/library/technical-documents?query=sba

Which does take you to step-by-step configuration docs.

Cheers,
Torren

**Comment by CarolynRowe** [comment]
The links are agreed upon by Microsoft and the SBC vendor.  Before changing the links in this document, please get approval from Filipp Seljanko.

**Comment by nam31** [comment]
@CarolynRowe, can you please tag in Filipp Seljanko.
Thank you

**Comment by CarolynRowe** [comment]
@FilippSe Can you comment on this issue?  thanks.

**Comment by FilippSe** [comment]
Let me sync with Audicodes this week and come back with the final link

**Comment by tiburd** [comment]
@FilippSe 
Hi, have you confirmed whether the AudioCodes link should be updated?
Thanks!
