### ISSUE TITLE
Dead link on this page

### ISSUE THREAD

**Issue by Richard-Barr3tt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6671]
In the section titled 'Manage configurations via PowerShell' there is a dead link. 

The link titled ' Skype for Business cmdlet module' goes to a 404 page. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a60f957-8007-280c-4081-aa1930771767
* Version Independent ID: d6e71a44-d4ba-b82c-c2fc-ea667f7a889a
* Content: [Manage Teams with Microsoft Teams PowerShell - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-managing-teams#manage-configurations-via-powershell)
* Content Source: [Teams/teams-powershell-managing-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-managing-teams.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by RAJU2529** [comment]
@Richard-Barr3tt .  Thanks for reporting to us . I am fixing the link.

**Comment by nam31** [comment]
Closing via #6672 
Thank you
