### ISSUE TITLE
Missing changelist notes for 1.18 - 1.1.11 previews.

### ISSUE THREAD

**Issue by darrenmonahan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6676]
Missing changelist notes for 1.1.8 - 1.1.11.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 173b5929-529b-938b-b6ab-59f05a5d69a8
* Version Independent ID: 0a3dfe5e-938f-933d-637e-b7449e3b8aa5
* Content: [Microsoft Teams PowerShell Release Notes - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-release-notes)
* Content Source: [Teams/teams-powershell-release-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-release-notes.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
@darrenmonahan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by darrenmonahan** [comment]
Fixed in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/7fe6ba064d89f5e9d66b2345e1175a839427266f. Thanks!
