### ISSUE TITLE
Encoding bug with the teamslogon.aspx redirection service

### ISSUE THREAD

**Issue by odrouin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6679]
Hi, since last week, there seems to be a new bug with the teamslogon.aspx redirection service.
It seems to double encode the provided url, redirecting to an invalid url and resulting in a 404.

Exemple:
```
https://contoso.sharepoint.com/sites/ContosoNet/_layouts/15/teamslogon.aspx?SPFX=true&dest=/sites/ContosoNet/Home%20page.aspx
```
will redirect to 
```
https://contoso.sharepoint.com/sites/ContosoNet/Home%2520page.aspx
```
See the double encoding with the "Home%2520page" above.

The impact is that you can no longer provide to the teamslogon.aspx an url containing a space or any special character.
This will result in a redirect to an invalid url and a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611ed1ac-09a9-3491-7fa8-d282b4558fbe
* Version Independent ID: b5a1dba5-beab-7188-fe18-0a045814dde0
* Content: [Create a Teams 'Intranet Portal app' from a SharePoint Online site or page - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-standalone-static-tabs-using-spo-sites)
* Content Source: [Teams/teams-standalone-static-tabs-using-spo-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-standalone-static-tabs-using-spo-sites.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@odrouin Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
