### ISSUE TITLE
page still referring to privacy shield

### ISSUE THREAD

**Issue by gitralf** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6680]
The page still refers to Privacy Shield. Since July 16th, Privacy Shield is invalid as a legal base for transfer of personal data to countries outside EU. Please consult your privacy team and update the text.

Ralf Wigand, MS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e34f35bb-7d9c-0c7f-a1a1-6fd9fbe93dfa
* Version Independent ID: d123210a-ed20-4b97-3706-33d7887b4c27
* Content: [Microsoft Teams Privacy - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-privacy)
* Content Source: [Teams/teams-privacy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-privacy.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@gitralf Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@gitralf Thank you for pointing this out and helping improve MS Docs. Would you recommend removing that entire sentence?

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
