### ISSUE TITLE
Minimal permissions required to setup Direct Routing

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6681]
I'm missing information what roles should admin have to be able to configure direct routing. According to this document https://docs.microsoft.com/en-us/MicrosoftTeams/using-admin-roles "Teams Communications Administrator" role should be sufficient but when trying to run the Set-CsUser cmdlet returns an error that can be fixed when user has also S4BO admin role  - https://techcommunity.microsoft.com/t5/microsoft-teams/teams-direct-routing-set-csuser-not-available/m-p/1656200

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df318fdb-6d58-86f8-de31-6eca533a9746
* Version Independent ID: a2248abf-bdf0-2c22-2604-74b482156684
* Content: [Configure Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-configure)
* Content Source: [Teams/direct-routing-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-configure.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Larryngolog thank you for pointing this out. I looked through those articles and the one mentions that you need to have the Skype for Business Administrator role within Azure AD to have the commands brought in and that having Teams Service Administrator isn't enough. Does this help and should I add a note to this article?

**Comment by Larryngolog** [comment]
Hi @lindspea I'm not sure which article and which portion of it you have in mind? The document about configuring DR does not mention any permissions. The other article with definition of admin roles states the following "The Skype for Business admin role also has access to all the cmdlets" - note is says "ALSO" which in my opinion implies that Teams admins have the required permissions and S4B admin also has these permissions. It would be great if the DR config document would state what minimal permisisons are needed to perform the tasks mentioned in the article. Also the admin roles article should mention that the Communication admin role is not sufficient to configure DR. It would be optimal if only Teams Admin role would be sufficient to perform these tasks.

**Comment by scanum** [comment]
@lindspea

**Comment by lindspea** [comment]
@Larryngolog thank you. I'm still researching but I found this new article with quite a few links in it for direct routing. Let me know if it helps. I'll keep investigating...https://docs.microsoft.com/microsoftteams/direct-routing-enable-users

**Comment by Larryngolog** [comment]
Hi I know this document as well, but it also does not mention permissions required to perform these actions. What we need is a clear statement on these config documents or on the admin role documents (preferably in both places) what permissions you need. A lot of organizations follow strict RBAC and minimum permissions rules (like advised by Microsoft) and lack of this information is causing issues during deployment - accounts used to configure DR do not have sufficient permissions and configuration fails. This happens despite following MS documentation which in my opinion is misleading.

**Comment by Larryngolog** [comment]
@scanum  please reopen this case as I do not think it's solved.
