### ISSUE TITLE
Instructions for Move-CsUser are very unclear

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6686]
The instructions for Move-CsUser are unclear and misleading.

The problem is that there are different circumstances requiring different parameters, and it is not clear what circumstance required what parameter. As far as I can tell:

1. Anyone migrating now is likely to be using Modern Authentication. This requires the -UseOAuth switch. The $cred parameter will not work as, by design, it is legacy auth.
2. By MS recommendation, most people will have a separate admin account for online and on-prem. That's fine; the -UseOAuth switch will cause a prompt for the account to use.
3. Some people may have an admin account that is not @tenant.onmicrosoft.com. In a Skype for Business Online session, the parameter is -OverrideAdminDomain. The equivalent in SfB on-prem is -HostedMigrationOverrideUrl.
4. MFA is the default for admin accounts in Office 365. But this page does not mention it. The -UseOAuth switch may or may not support MFA. 
5. In the [Move-CsUser reference](https://docs.microsoft.com/en-us/powershell/module/skype/move-csuser?view=skype-ps) it says that the -HostedMigrationOverrideUrl parameter is also required if the hosting provider AutoDiscover URL is not properly configured.

Taking it all together, the default command for most cases is probably ```Move-CsUser -Identity username@contoso.com -Target sipfed.online.lync.com -MoveToTeams -UseOAuth -HostedMigrationOverrideUrl $url```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca38b93a-773e-3864-45b6-128dd3163f37
* Version Independent ID: 7c32e933-94f2-196e-1163-3881df3aaf5a
* Content: [Move users from Skype for Business Server 2019 to Teams - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/move-users-from-on-premises-to-teams)
* Content Source: [Skype/SfbHybrid/hybrid/move-users-from-on-premises-to-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/move-users-from-on-premises-to-teams.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Air-Git Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Air-Git thank you for pointing this out. Should I add that default command in a note in the document to help other users?

**Comment by Air-Git** [comment]
Yes, I think so. Otherwise it takes a lot of digging to find what is needed.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
