### ISSUE TITLE
Pricing links partially broken and all point to Skype for Business URLs

### ISSUE THREAD

**Issue by dwhitney7** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6687]
Three pricing links at the bottom all point to Skype for Business marketing URLs, and I would expect should point to the current Teams versions of these links. In particular, the Audio Conferencing link does not correctly redirect right now and goes to an error page.

Pricing for Audio Conferencing -> Should probably point to https://www.microsoft.com/en-us/microsoft-teams/audio-conferencing, does not correctly redirect here correctly with current link

Pricing for Phone System -> Should probably point to https://www.microsoft.com/en-us/microsoft-teams/voice-calling, and that is what the current link redirects to

Pricing for Calling Plans -> Should probably also point to https://www.microsoft.com/en-us/microsoft-teams/voice-calling, the same link as for Phone System, and that is what the current link redirects to

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fac515b-9c6b-c70c-330e-53557dc23fd2
* Version Independent ID: d515841e-f412-286d-1a97-30507bb50040
* Content: [Audio Conferencing pay-per-minute - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-pay-per-minute#want-to-find-out-more-about-pricing)
* Content Source: [Teams/audio-conferencing-pay-per-minute.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-pay-per-minute.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by RAJU2529** [comment]
@dwhitney7 . Thanks for pointing out. I added correct links.

**Comment by tonysmit** [comment]
@scanum - I'm talking to marketing to find the correct links for pricing information. I see there are several issues with the Audio Conferencing link that people are bringing up. Go ahead and assign them all to me so I can fix all of them at the same time if you would. Thanks, Tony

**Comment by tonysmit** [comment]
@scanum - you might not being seeing updates yet. Our publishing system had an issue so it's currently down but predicted to be online later today or tomorrow. Thanks, Tony
