### ISSUE TITLE
Whats the story with 2008 R2?

### ISSUE THREAD

**Issue by JoshJ-MSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#669]
We need to speak plainly.  Is Windows Server 2008 R2 a supported operating system to install Skype for Business Server 2015 on or not?  Real world scenario:  Customer has a SfB 2015 pool that was inplace upgraded from 2013.  Fe's are running Windows2008 R2.  One FE has gone down and needs replaced.  Our doc says to use 2012 R2 as the OS so the pool would then have a mix of operating systems.

If 2008 R2 is supported with the product, say so.  If we have additional guidance about it we can provided it next.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c475b5d-09ed-7f58-86d4-27f28e33ef7a
* Version Independent ID: f0ad50f3-ea93-9424-6de8-a0b778e90b23
* Content: [Server requirements for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/server-requirements)
* Content Source: [Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by AndreaBarr** [comment]
@JoshJ-MSFT Thank you for this feedback.

I want to make sure this server 2008 R2 clarification gets addressed properly so I am sending it over to the Teams team.

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by scanum** [comment]
@MicrosoftHeidi Any updates on this issue? Thanks!

**Comment by scanum** [comment]
@MicrosoftHeidi Hi Heidi, could you please refer us to the product team? Thanks!

**Comment by scanum** [comment]
@JoshJ-MSFT Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
