### ISSUE TITLE
incorrect number for GCC - GCC allows 300 users, not 250

### ISSUE THREAD

**Issue by ricardo-msft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6690]
incorrect number for GCC - GCC allows 300 users, not 250

https://docs.microsoft.com/en-us/microsoftteams/view-only-meeting-experience

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bf705c2-1f24-bdb5-e712-e8408b941aca
* Version Independent ID: ddedd7e0-7d85-06e0-7f20-8b83b3dccec7
* Content: [View-only meeting experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/view-only-meeting-experience?source=docs#feedback)
* Content Source: [Teams/view-only-meeting-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/view-only-meeting-experience.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@ricardo-msft Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@ricardo-msft According to the [Teams limits documentation](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams), it's indeed 250. Has there been an update? Can you share a link where this is specified?

![image](https://user-images.githubusercontent.com/41186174/110617195-101bb800-819e-11eb-9e66-74a36b2ff423.png)

**Comment by lindspea** [comment]
@cichur please could you confirm if article should read 250 or 300. Another related issue - https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6721

**Comment by cichur** [comment]
We updated the article so they're have the same information. Thank you. Cindy
