### ISSUE TITLE
Documentation does not have any reference to hybrid scenarios

### ISSUE THREAD

**Issue by dehulme** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6694]
Customer tried to create call queues - they have call queues with Teams agents and Skype for Business on-premises agents.

This public documentation does not have any reference to Hybrid scenarios, this only describes the steps that should be followed for Microsoft Teams, even though at the beginning of the page it's mentioned: "Applies to: Skype for Business, Microsoft Teams"

Customer requested to be added a reference in this article where it is stated that the resource account in hybrid scenario needs to be created on-premises, and a reference to this article as well: https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-call-queue (maybe in Pre-requisites section?)

Thank you,

Delia

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62fca5a0-5e22-578c-98c8-6b331ae1017f
* Version Independent ID: e1307146-d481-d39c-6227-4c001e044eb1
* Content: [Plan for Teams auto attendants and call queues - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/plan-auto-attendant-call-queue#prerequisites)
* Content Source: [Teams/plan-auto-attendant-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-auto-attendant-call-queue.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@dehulme Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dehulme** [comment]
Hi @scanum please do you have an update for us on this? Thanks
