### ISSUE TITLE
Documentation does not have any reference to hybrid scenarios

### ISSUE THREAD

**Issue by dehulme** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6695]
Customer tried to create call queues - they have call queues with Teams agents and Skype for Business on-premises agents.

This public documentation does not have any reference to Hybrid scenarios, this only describes the steps that should be followed for Microsoft Teams, even though at the beginning of the page it's mentioned: "Applies to: Skype for Business, Microsoft Teams"

Customer requested to be added a reference in this article where it is stated that the resource account in hybrid scenario needs to be created on-premises, and a reference to this article as well: https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-call-queue.

Thank you,

Delia

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b755d9ae-13ac-019f-f5f4-a95b1eee2989
* Version Independent ID: f7afd8ad-e6e0-6c79-aed1-4ee87d48ba12
* Content: [Create a call queue in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue)
* Content Source: [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-call-queue.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@dehulme Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dehulme** [comment]
Hi @scanum please do you have an update for us on this? Thanks

**Comment by lindspea** [comment]
@dehulme thank you for reaching out and helping improve MS Docs. Are you suggesting adding the link to this article as well as a note stipulating that the resource account in hybrid scenario needs to be created on-premises?

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
