### ISSUE TITLE
Skype number 

### ISSUE THREAD

**Issue by lexhoncito3** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6696]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c0ab608-c57e-0e72-6071-5fc02cf6217c
* Version Independent ID: 73c13bf0-4247-ad87-e3be-7d9a59ab457e
* Content: [Plan hybrid connect - Skype for Business Hybrid](https://docs.microsoft.com/en-us/SkypeForBusiness/hybrid/plan-hybrid-connectivity?toc=/SkypeForBusiness/sfbhybridtoc/toc.json)
* Content Source: [Skype/SfbHybrid/hybrid/plan-hybrid-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/plan-hybrid-connectivity.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@lexhoncito3 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
