### ISSUE TITLE
The link for pricing on this page is dead and no longer works.

### ISSUE THREAD

**Issue by Billabongodysee** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6699]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e640245-6d25-2165-3792-9bb386a73184
* Version Independent ID: 28951938-7e00-16fd-c216-a569ba94b041
* Content: [Audio Conferencing in Microsoft 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-in-office-365)
* Content Source: [Teams/audio-conferencing-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-in-office-365.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by RAJU2529** [comment]
@Billabongodysee , I already  sent a request to author to approve link new link, once approved means, a new link will be dispalyed

**Comment by tonysmit** [comment]
@scanum - I fixed this correctly. It has an fwlink and I confirmed with marketing about the pricing link. Thanks, Tony
