### ISSUE TITLE
Recommendation:  Add a segment that outlines the ability to test your Skype Room System V2 account once it is created.

### ISSUE THREAD

**Issue by snoebel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#670]
There's a lot of great documentation on the creation of the account, but how does one "proof" the account once it is created. If the account is created 3-4 weeks before hardware installation, as recommended, then where can one go to use the account and account credentials to fully verify is works as required?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41965bc8-45c0-e4eb-aa36-5ef5adbe460a
* Version Independent ID: 97de65ad-04fc-5b62-c7c7-fba8d0aeb1de
* Content: [Deploy Skype Room Systems v2 with Office 365](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/with-office-365)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/with-office-365.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
I've added an initial section to the file, the essence is you should be able to test a device account with any of the standard clients (that's also the case with Skype for Business on Surface Hub) as the SRS v2 is essentially a specialized SfB client. 


If this doesn't satisfy your issue, please let us know.
