### ISSUE TITLE
Account Provisioning Script Needs Updating

### ISSUE THREAD

**Issue by jpalarchio** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6700]
We really need to update this content.  That provisioning script has all kinds of issues around the new PS modules and when the account being used has MFA.

Also, can we get rid of all these Skype Room references and have the script include "Microsoft Teams Rooms"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 834f564b-d32a-25ba-437b-1cb74adbf485
* Version Independent ID: 9bdb6864-caa0-d0fa-ce06-eaaa1fd18fe3
* Content: [Configure accounts for Microsoft Teams Rooms - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-configure-accounts)
* Content Source: [Teams/rooms/rooms-configure-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-configure-accounts.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@jpalarchio Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@jpalarchio thank you for reaching out. Are you suggesting that the Skype room provisioning script needs to be updated. Please can you let me know where else in the article it refers to Skype rooms and I'll have that fixed. It might have been rectified in the interim.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
