### ISSUE TITLE
Need more information on "Missed Activity Emails" in Teams

### ISSUE THREAD

**Issue by atrainSaaS** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6703]
Documentation currently does not describe:

1. What triggers the "missed activity emails"
2. What emails can be replied to from Outlook

On point 1, these emails do not come "As soon as possible" as configured in my Teams notification settings.  I've read [here ](https://techcommunity.microsoft.com/t5/microsoft-teams/microsoft-teams-email-notifications/m-p/313616) that the trigger may be based on whether you're "away" in Teams for a period of time, but this documentation does not confirm nor deny this.

On point 2, not all emails from Teams can be replied to.  What mechanism determines this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f34a4f9-bb6f-03e9-9c11-bb2f43dd9aeb
* Version Independent ID: a6e1ee45-8ce4-96b4-21ad-90ca8af646c4
* Content: [Teams and Outlook email integration - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-outlook-email-integration)
* Content Source: [Teams/teams-outlook-email-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-outlook-email-integration.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@atrainSaaS Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@atrainSaaS thank you for reaching out. As far as I know you get 'missed activity' emails if you are away in Microsoft Teams or signed out, usually after a few minutes, but you should be able to configure this as well and change it in settings.  You should also be able to respond to it via Outlook. Please see here for versions that this function applies to -  https://docs.microsoft.com/outlook/actionable-messages/

**Comment by atrainSaaS** [comment]
Thanks @lindspea 

As best as I can tell, there's no way to configure the email settings beyond "ASAP/EVERY 10 HOURS/8 HOURS/DAILY/ETC".  If the condition to receive these emails is that my status must be set to "Away" or signed-out, could that be added to the documentation? 

My initial assumption was that I could get email notifications from channel activity immediately regardless.  However it seems that only some messages make it through.  Is that because the connector only sends the messages that are created _while_ I'm away?

The only other part I'm confused about is when some "actionable" emails include the "Reply" button while others don't.

**Comment by lindspea** [comment]
@atrainSaaS I will have a note added to this article. Regarding email notifications, as far as I know you will only get notifications when you are 'away' and not active on Teams? @cichur please can you confirm this.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by cristianoag** [comment]
Can I have a bot message triggering the missed activity email? I'm using a bot to send messages to a user that is logged off from teams with the missed activity emails option configured but she is not getting messages on her Outlook.
