### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by sdel85** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6704]
[Enter feedback here]
The link on this page (https://docs.microsoft.com/en-US/microsoftteams/audio-conferencing-in-office-365?WT.mc_id=365AdminCSH_inproduct) for pricing info, see Pricing for Audio Conferencing (https://products.office.com/microsoft-teams/online-meeting-solutions#customerstoryregion2), doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e640245-6d25-2165-3792-9bb386a73184
* Version Independent ID: 28951938-7e00-16fd-c216-a569ba94b041
* Content: [Audio Conferencing in Microsoft 365 - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/audio-conferencing-in-office-365?WT.mc_id=365AdminCSH_inproduct)
* Content Source: [Teams/audio-conferencing-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-in-office-365.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by RAJU2529** [comment]
@sdel85  . I already added updated linksa in this article and is in under verification, so please wait for some days to show the correct link .
@e0i, look in this issue #6691
@e0i, please  close this issue

**Comment by tonysmit** [comment]
@scanum - this is another bad link. I fixed this when I did it for one of the other issues. Confirmed with marketing and added the correct fwlink. Thanks, Tony
