### ISSUE TITLE
Update 120 & 240 mn

### ISSUE THREAD

**Issue by rdekramer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6705]
120 minute plan is only available via lead status in the US. It is not available in NL. Could you verify and update the doc?

Thanks in advance

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 212fbc79-5ef4-c8d2-39bf-4f314e539518
* Version Independent ID: f5ae631f-f3dc-a362-40a4-7e4150d6fb11
* Content: [Availability in the Netherlands - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-netherlands?source=docs)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-netherlands.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-netherlands.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@rdekramer Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@CarolynRowe please can you confirm if the 120 minute plan is available in NL.

**Comment by rdekramer** [comment]
Hi all, I just received confirmation the 120 plan is available in NL. We have to update internal licensing documentation as it states otherwise. Our external docs site is up to date. Sorry for the inconvenience...

Remco de Kramer
Product Marketing Manager
Modern Work

Need a quick response?
Want to meet me?
Mobile +316 25 23 84 83<callto:+31625238483>
Fixed    +3120 500 18 58<callto:+31205001858>

Chat with me via Teams<sip:redekram@microsoft.com>
Book your meeting now <https://outlook.office365.com/owa/calendar/Microsoft2635385@microsoft.onmicrosoft.com/bookings/>
[See the source image]

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
