### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by BCockrell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6706]
The Audio Conferencing Pricing link is broken on: https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-in-office-365

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e640245-6d25-2165-3792-9bb386a73184
* Version Independent ID: 28951938-7e00-16fd-c216-a569ba94b041
* Content: [Audio Conferencing in Microsoft 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-in-office-365#feedback)
* Content Source: [Teams/audio-conferencing-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-in-office-365.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by RAJU2529** [comment]
@BCockrell . I already  added  updated linksa in this article and is in under verification, so please wait for some days  to  show the correct link .
@e0i,  look in this issue  **https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/6691**

**Comment by tonysmit** [comment]
@scanum - here is yet another one. Closing because I fixed this with the correct fwlink and it should be live already. Thanks, Tony
