### ISSUE TITLE
Newer links for download?

### ISSUE THREAD

**Issue by BZanten** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6708]
I have the impression the links to the download point to older versions of Teams.
i'm getting v1.3  while others have much newer versions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Teams using Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by RAJU2529** [comment]
@BZanten . Thanks for pointing out, in this article, the .msi format   team application direct link is  updated and it for  deployment purpose.
If you really required  v1.4 means then download  teams app from below site  in .exe  format
**https://www.microsoft.com/microsoft-teams/download-app**

I hope i answered your query.
