### ISSUE TITLE
Massive Memory leak present in teams

### ISSUE THREAD

**Issue by MaxSimpson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6709]
A couple of months ago I started using Microsoft Teams for my classes as my school went online. I first noticed this issue a week or two into an online school. I had left my PC on for a couple of days straight and had closed teams in between only using the x in the top right. I noticed after having been away from my computer for a  couple of hours teams was using 1.5gb+ of memory. I used CMD and taskkill to close it and watched my RAM usage drop. This happened again to me a couple more times but I used CMD to remedy this issue. Until last night, my friend was trying to play minecraft with us. His memory usage was at 96% of his 16Gb and nothing in taskmanager or resouce monitor showed a lot of memory usage which rose some red flags for me. I had him go through and start closing programs to pinpoint the issue. We used taskkill and cmd to do this. We closed steam, chrome, other possible programs but to no avail. I noticed teams and had him close it. It instantly dropped his memory usage from 94% to 88% even when teams wasn't open and being used. After restarting his PC his memory usage was back to normal and teams was nowhere in sight. I suspect that there is some sort of bug in Microsoft Teams's memory allocation or deletion that removes it from the standby pool and keeps it allocated but where it is no longer in use. Please look into this if you aren't already. I am not sure if I can recreate it by hand but I can try. Let me know if you have any more questions that I can help with. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc21902c-d522-3851-8587-177f01bc085c
* Version Independent ID: 590bcc64-a86d-b61e-7d94-4e4322c4e71d
* Content: [How Microsoft Teams uses memory - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-memory-usage-perf)
* Content Source: [Teams/teams-memory-usage-perf.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-memory-usage-perf.md)
* Service: **msteams**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
