### ISSUE TITLE
Misleading wording

### ISSUE THREAD

**Issue by NickElniff** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#671]
This article is causing a lot of confusion for my customers that are looking to move from 3rd-Party Audio Conferencing Provider to Microsoft's Audio Conferencing.

The line "Using a third-party audio conferencing provider" in the 'Common scenarios where you can't use MMS' section. There needs to be clarification on what that actually means. Ideally it should read something like "When configuring a user to use a 3rd-party Audio Conferencing Provider."

Also, the section 'Primary Scenarios' should include wording to include the specific scenario "When changing a user from 3rd-Party ACP to Microsoft Audio Conferencing"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 990ca74b-6bba-a14b-071a-d13adb723a4c
* Version Independent ID: 52f55a58-30ce-c140-3ee7-8042b1d105f0
* Content: [Setting up the Meeting Migration Service (MMS)](https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/setting-up-the-meeting-migration-service-mms)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/setting-up-the-meeting-migration-service-mms.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/setting-up-the-meeting-migration-service-mms.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by NickElniff** [comment]
Any update on this? This continues to confuse customers

**Comment by AndreaBarr** [comment]
@NickElniff Thank you for this feedback. 

I want to make sure these clerifications get addressed properly and the document gets updated. I am going to get this over to the Teams team so they can address it and update the doccument. 

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @NickElniff thanks for your feedback!
Document has been updated since you opened this issue and notes about third party conference services has been added to clarify this situation, please review it now.

Hope this information has helped you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @NickElniff 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
