### ISSUE TITLE
Incorrect E1\E3 add-ons mentioned in this article. 

### ISSUE THREAD

**Issue by MSTejas** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6710]
This article talks about add-ons with Office 365 E1\E3 subscriptions and it says, audio conferencing and phone system licenses are included, whereas we have to buy them as add-on licenses. This needs correction.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abae7324-861d-7ca7-7239-a5df8fd927d5
* Version Independent ID: 8a30bd2f-9bc3-a0a8-8b31-d53836ead4d0
* Content: [Microsoft Teams add-on licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=enterprise)
* Content Source: [Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Hi @MSTejas 
Will you please highlight the section that you're discussing? Thank you, Cindy

**Comment by MSTejas** [comment]
This is regarding the image in https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=enterprise#what-voice-features-are-available-with-my-plan.

**Comment by MSTejas** [comment]
<img src="../media/licensing-enterprise-options.png" alt="Enterprise-based plan options" data-linktype="relative-path">

This web element.

**Comment by cichur** [comment]
We've recently converted the images to tables. I believe the information is correct. Thank you, Cindy
