### ISSUE TITLE
Send outlook emails from within Teams: HOW??!!

### ISSUE THREAD

**Issue by Elijah977** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6712]
HELP!
How do I integrate Outlook into Teams to be able to email every member of my Team (University students)? It should be simple, but Microsoft makes a simple thing so complex! AGAIN: I want to email all the members of my team in Teams. I do NOT have an Outlook Group in Outlook. I have created a "Students" team in teams (130 students). How do I email them all at once?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f34a4f9-bb6f-03e9-9c11-bb2f43dd9aeb
* Version Independent ID: a6e1ee45-8ce4-96b4-21ad-90ca8af646c4
* Content: [Teams and Outlook email integration - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-outlook-email-integration)
* Content Source: [Teams/teams-outlook-email-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-outlook-email-integration.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
