### ISSUE TITLE
Integrate Outlook inside Teams

### ISSUE THREAD

**Issue by Elijah977** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6713]
I'm a University professor and adviser. My program educates 130 majors and 50 minors. I created a "Students" team and **want to email my students all at once from within Teams.** I do not have an Outlook Group, I have a team inside MS Teams. HELP, please! Make the integration happen. Email communication is the eOfficial signature on a document in online education, nothing else. Allowing access to Outlook inside Teams is a great feature that Microsoft is missing. Looking forward to hearing from someone! THANKS!

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
