### ISSUE TITLE
What is up with the CA requirement, no intermediates? Why no Let's Encrypt/ZeroSSL? SSL Automation?

### ISSUE THREAD

**Issue by massar** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6714]
Hi Carolyn & Team,

The document states:
"The certificate should be issued directly from a certification authority, not from an intermediate provider."

But, it is impossible to get one directly from the CA, as there will always be an intermediate cert.

For instance:  https://crt.sh/?q=teamsip.ch works fine, but as the graph shows it has an intermediary "GeoTrust RSA CA 2018" but the actual CA is "Digicert Global Root CA".

Hence, I think the wording in the document is a bit ambiguous, can it be updated, possibly showing an example certificate that works?

As currently, when one loads up a 'valid' certificate it will be loaded, but things magically "do not work" (the people working on it unfortunately are unable to produce any error message..... very useful, I know). They do know that with the teamsip.ch one it works.

Can you please clarify the requirements in the document?

Another question is: why no Let's Encrypt or ZeroSSL?

Especially considering Let's Encrypt being 71% of world-wide certificates (See https://ct.cloudflare.com) it is a wee bit of an omission to not allow certificates from them.

And that brings to the last question: is there an API or other automated mechanism that allows automatically replacing + reloading the certificate, so that we can automatically deploy it?

Greets,
 Jeroen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e26faf8c-529e-b317-5934-cd41cfe8fa24
* Version Independent ID: 3ddd5d0a-6dbb-4940-1814-8346e293701b
* Content: [Plan Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan#public-trusted-certificate-for-the-sbc)
* Content Source: [Teams/direct-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
