### ISSUE TITLE
License assignment policy

### ISSUE THREAD

**Issue by Torbjorn-S** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6718]
What exactly is a "license assignment policy" and why will that prevent exploratory licensing?
Is it rather "Group based licensing" (https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/licensing-groups-assign) that this refers to? 
If it does refer to Group Based Licensing, will removal of the group based licensing logic introduce the possibility to use exploratory licenses?

Also, the documentation fails to highlight what happens after the first user has generated the pool of 100 exploratory licenses. What happens when person number 101 tries to logon to Teams without a license?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-exploratory)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Torbjorn-S** [comment]
Good evening Manuela.

I´m not sure what you want me to open a service ticket about?
I´m trying to understand the bullet points that must be fulfilled in order to be eligible:

Who's eligible
Users fit the criteria for a Teams Exploratory experience if they:
·         Have a managed Azure AD domain email address.
·         Belong to a tenant with a paid subscription.
·         Do not have an active Teams license.
·         Are not in a tenant where a license assignment policy was created.


The documentation calls out the requirement that a "license assignment policy" has not been created within the tenant.
I´m questioning this wording because neither I, nor any of the experts that I work closely with can find a reference to what that is supposed to mean.

The other part about the pool of 100 licenses is more of an practical thing that I think is lacking from the documentation and I really don´t know what the support are supposed to comment upon regarding that either.



[cid:image001.jpg@01D70AD6.85413040]

Torbjörn Sjölund
Solution Architect
Collaboration

Direct: +46 8 633 67 31
torbjorn.sjolund@atea.se<mailto:torbjorn.sjolund@atea.se>


Sensitivity: Internal
