### ISSUE TITLE
SFBO Plan 2 Requirement for Direct Routing - licensing guidance needs to be updated

### ISSUE THREAD

**Issue by 3017mark** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6719]
SFBO Plan 2 has been eliminated from purchasing.  Guidance needs to be updated and be more clear 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e26faf8c-529e-b317-5934-cd41cfe8fa24
* Version Independent ID: 3ddd5d0a-6dbb-4940-1814-8346e293701b
* Content: [Plan Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan#licensing-and-other-requirements)
* Content Source: [Teams/direct-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@3017mark Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@3017mark thank you for reaching out and helping improve MS Docs. I see the note stipulates "Skype for Business Plan should not be removed from any licensing agreement where it is included." What would you suggest changing in this article?

**Comment by 3017mark** [comment]
It should be providing further clarification for customers to acknowledge that SFB plan 2 is bundled with the E/G5 SKU's and standalone phone system.  The details are missing as to the specific reasons it is required which causes confusion for customers.

Mark A. Brownell
Teams Techical Specialist
Microsoft
US State & Local Government
Office: +1-425-538-2012
Mobile: +1-774-280-9182
mabrowne@microsoft.com<mailto:mabrowne@microsoft.com>
[cid:image002.jpg@01D713F6.1BE69DA0]

**Comment by scanum** [comment]
@lindspea

**Comment by lindspea** [comment]
@3017mark I see the article has been updated and also mentions that SFB will retire in July 2021. Please have a look and let me know if there is anything else you recommend adding to the article.

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
