### ISSUE TITLE
BI doesn't work

### ISSUE THREAD

**Issue by LB-PM-VS** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6720]
I downloaded the "CQD Power BI Query", connected it, and no matter how I change the data (dates, AA) the data doesn't change. I need to know how many calls are coming into each office so we can properly allocate resources. 

"Call quality" is more for technicians and MS and is not useful. We need to know the volume for resources. 

![image](https://user-images.githubusercontent.com/62301346/109040383-10d72900-768b-11eb-9a9f-c0553785a4cc.png)
![image](https://user-images.githubusercontent.com/62301346/109040449-264c5300-768b-11eb-9d50-8859a271346c.png)

![image](https://user-images.githubusercontent.com/62301346/109040590-4f6ce380-768b-11eb-890c-5ded247785a2.png)
![image](https://user-images.githubusercontent.com/62301346/109040650-60b5f000-768b-11eb-8d2b-47c09e817ba4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb8d8b48-561b-6817-1ce0-4b2aedc261a8
* Version Independent ID: dfd5cf4a-509a-3ed1-0267-6281c251fbef
* Content: [Set up Call Quality Dashboard (CQD) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/turning-on-and-using-call-quality-dashboard#assign-roles-for-accessing-cqd)
* Content Source: [Teams/turning-on-and-using-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/turning-on-and-using-call-quality-dashboard.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@LB-PM-VS Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
