### ISSUE TITLE
Meeting Limits - Footnote says GCC is 250, but product group says 300

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6721]
I know other folks have sent this feedback in before, but the docs are still saying that GCC's meeting participant limit is 250 instead of 300. 

https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#meetings-and-calls

While I don't know what GCC-H or DOD have, our Teams GCC Engineering CPM has **repeatedly** confirmed that 300 is the limit in GCC and said that they are working to get the docs updated. We really need help getting the docs fixed as this is causing significant customer confusion. Thank you for your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@npherson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@npherson thank you for reaching out. Please see the article has been updated and the note reads "Note: For Teams for Government (GCC, GCC High, DoD), the limit is still 250. We'll update this article when the government cloud limit increases from 250 to 300 and supports meeting overflow."

**Comment by VLG17** [comment]
This topic came up in [another issue](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6690) as well.

**Comment by npherson** [comment]
@lindspea - That updated text says that GCC's limit is 250, when our engineering CPM contacts have repeatedly confirmed that the limit is 300 and the docs are wrong. While there are lots of places that the docs are flat out wrong for GCC, this is the one causing the most customer confidence issues in my territory. Is there anything we can do to escalate this request?

**Comment by lindspea** [comment]
@SerdarSoysal please can you confirm what the correct number is?

**Comment by npherson** [comment]
Is there any way to escalate this? This is causing significant customer confusion/dissatisfaction. @lindspea @SerdarSoysal

**Comment by lindspea** [comment]
@npherson @cichur updated this article a few days ago so it should be live soon.

**Comment by npherson** [comment]
Can you help me find the pull request?  I'm not seeing it in the list of open PRs.

**Comment by npherson** [comment]
"For Teams for Government (GCC, GCC High, DoD), the limit is still 250"

According to our Teams Engineering CPM, the limit in GCC went to 300 months ago and the docs are wrong. He has confirmed this for us multiple times.

If you aren't getting the information needed to update the article from the PG, please let us know what the appropriate path for executive escalation is for this.

**Comment by lindspea** [comment]
@cichur please can you clafiry?

**Comment by cichur** [comment]
Hi @npherson and @lindspea 
I just confirmed with our product managers that the limit for GCC is 300. I'm updating the View-only article, as well as the Limits and Specs article. Thank you, Cindy

**Comment by npherson** [comment]
Thanks, @cichur.

![image](https://user-images.githubusercontent.com/22797301/114458766-3ec5ed80-9ba5-11eb-8064-16185f71e3db.png)

Any suggestions for how we can get issues like this addressed by the product group proactively in the future?

**Comment by lindspea** [comment]
Thanks @cichur let me know if I can help with any PR's.

**Comment by npherson** [comment]
URGENT - I see that the callout for 250 meetings was remove for **all** gov customers, **not just GCC**. Did you actually receive confirmation from the GCC-H and DOD product groups that they increased the limit to 300?

**Comment by scanum** [comment]
@lindspea

**Comment by lindspea** [comment]
@cichur can you help here please?

**Comment by cichur** [comment]
HI @npherson and @lindspea,

Yes, the 300 limit is for GCC, GCC-H, and DOD. I received that confirmation from the PMs. 
Cindy
