### ISSUE TITLE
Could you please list where the Praise data are stored for security sensitive people?

### ISSUE THREAD

**Issue by alan-hu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6722]
In many security sensitive organizations first question the security team is going to ask is where the data is stored and how secure they are stored.

Praise is a nice feature we'd like to consider but without much information about the data sovereign and data security it is a hard fight. Could you please include details such as where the data is stored and how they are stored? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2033a3-a651-78f3-90c2-ad582e182731
* Version Independent ID: 057e7da2-4e65-7f8d-5843-b15d92ffff02
* Content: [Manage the Praise app in the Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-praise-app)
* Content Source: [Teams/manage-praise-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-praise-app.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@alan-hu Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
