### ISSUE TITLE
Multi-Geo for chats statement?

### ISSUE THREAD

**Issue by IngoWestner** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6724]
[Enter feedback here]
I am not entirely sure if the following statement in the article is correct: "Conversations in chats, channels messages, and meeting IM notes/chats within the Teams experience aren't Multi-Geo-aware and are all kept only inside the central location of the tenant."
Our documentation https://docs.microsoft.com/en-us/microsoftteams/retention-policies says that "Teams chat messages are stored in a hidden folder in the mailbox of each user included in the chat, and Teams channel messages are stored in a similar hidden folder in the group mailbox for the team." That means, in a multi-geo environment, the chats would go to the participants' geo / to the location of the SharePoint. Or am I mistaking that article? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c65240c7-8a9e-cf39-008d-2c8b12534b0d
* Version Independent ID: 9a1e12a6-f020-7782-e749-8e4909fa8d0c
* Content: [Teams experience in a Microsoft 365 Multi-Geo-enabled environment - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-experience-o365odb-spo-multi-geo)
* Content Source: [Teams/teams-experience-o365odb-spo-multi-geo.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-experience-o365odb-spo-multi-geo.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@IngoWestner Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by IngoWestner** [comment]
Hi,
why should i create a support ticket? For the Microsoft tenant? (I am an FTE and saw the discrepancy of the two statements). I already described the issue and kindly ask that you please correct the statement in either of these two articles because they are contradicting.
Best,
ingo
