### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by arkayenro** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6725]
remote powershell download link is no longer valid and needs to be replaced

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d7fa7af-e864-84fe-68d4-b9f5e2ed0114
* Version Independent ID: 3bbc6d87-c3dd-4208-cec2-f574a997d329
* Content: [Configure Skype for Business hybrid - Skype for Business Hybrid](https://docs.microsoft.com/en-au/skypeforbusiness/hybrid/configure-federation-with-skype-for-business-online)
* Content Source: [Skype/SfbHybrid/hybrid/configure-federation-with-skype-for-business-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-federation-with-skype-for-business-online.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@arkayenro Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by arkayenro** [comment]
sorry, one of the links on that page wasnt working but they all are now.  i should have taken a screenshot of it as i dont remember where in the article it was any more.
