### ISSUE TITLE
Error in the example 3

### ISSUE THREAD

**Issue by Elecktrus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6728]
I think the example 3 is wrong.

This the Powershell command that you use:

New-CSOnlinePSTNGateway -Identity sbc1.contoso.com -SipSignalingPort 5061 –InboundTeamsNumberTranslationRules ‘AddPlus1’, ‘AddE164SeattleAreaCode’ -InboundPSTNNumberTranslationRules ‘AddPlus1’ -OutboundPSTNNumberTranslationRules ‘AddSeattleAreaCode’,  -OutboundTeamsNumberTranslationRules ‘StripPlus1’

In this command, the OutboundPSTNNumberTranslationRules has only 1 rule (‘AddSeattleAreaCode’),
so in the example 3, when you dial out from Teams number +1 206 555 0100 to PSTN number +14255550100 the rule can't be triggered (the pattern don't match), and because is the only rule defined, the translated header can't be INVITE 4255550100

This translated header would need use the rule 'StripPlus1' to obtain this number, but thie rule ‘StripPlus1’ is only defined for OutboundTeamsNumberTranslationRules.

So, i think that the powershell command have a mistake, and must be like this:

New-CSOnlinePSTNGateway -Identity sbc1.contoso.com -SipSignalingPort 5061 –InboundTeamsNumberTranslationRules ‘AddPlus1’, ‘AddE164SeattleAreaCode’ -InboundPSTNNumberTranslationRules ‘AddPlus1’ -OutboundPSTNNumberTranslationRules ‘AddSeattleAreaCode’,‘**StripPlus1**’  -OutboundTeamsNumberTranslationRules ‘StripPlus1’

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6981866f-a685-d802-d64f-98685a5c658d
* Version Independent ID: a1f83744-abb7-4c33-6f60-19ff2732871c
* Content: [Translate phone numbers for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-translate-numbers?source=docs)
* Content Source: [Teams/direct-routing-translate-numbers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-translate-numbers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@Elecktrus Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
