### ISSUE TITLE
Support Case : 23870888

### ISSUE THREAD

**Issue by mamoelle** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6730]
[Enter feedback here]
In the support case 23870888 the engineer stated that in SfBWithTeamsCollabAndMeetings the meeting chat history is not supported. Chat from users participating in a meet-now meeting is not accessible after the meeting since its only accessible through the chat conversation button which is hidden. 

On the other hand a scheduled meeting history is still accessible via the calendar.

Please add this limitation to the public docs to avoid further confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49921e8a-55ac-f547-d4e2-d329f5089c2e
* Version Independent ID: 91c3433a-3684-95cd-3426-4a5877b33106
* Content: [Migration and interoperability - Skype for Business - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/migration-interop-guidance-for-teams-with-skype)
* Content Source: [Teams/migration-interop-guidance-for-teams-with-skype.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/migration-interop-guidance-for-teams-with-skype.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@mamoelle Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@mamoelle thank you for reaching out and helping improve MS Docs. Would you suggest adding the following note to this article? - "Meeting chat history is not supported for users participating in a meet-now meeting as it is only accessible through the chat conversation button which is hidden, but a scheduled meeting history is accessible via the calendar."

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
