### ISSUE TITLE
Android support 

### ISSUE THREAD

**Issue by mamrouni** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6732]
[Enter feedback here]

- The article stated 2 contradictory facts : 

We have full Android and iOS mobile support for an attendee to join.
the view-only attendee won't be able to experience the following options in meetings: Join the Overflow Room via the Teams Android mobile app.

- The article stated that "The view-only experience is enabled by default for any organizer who has E3/E5/A3/A5 SKU" but in the message center Office 365 MC240169 Microsoft communicated that it's OFF by default
- Is the Q&A feature available in the overflow room ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bf705c2-1f24-bdb5-e712-e8408b941aca
* Version Independent ID: ddedd7e0-7d85-06e0-7f20-8b83b3dccec7
* Content: [View-only meeting experience - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/view-only-meeting-experience#feedback)
* Content Source: [Teams/view-only-meeting-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/view-only-meeting-experience.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Hi @mamrouni, 
Thank you for your comments.
We'll fix the information about Android support. Both Android and iOS are supported.  
View-only is OFF by default. We'll correct the article.
Q & A isn't available for View-only participants. 
Thank you,
Cindy
