### ISSUE TITLE
Typo Microsof in stead of Microsoft

### ISSUE THREAD

**Issue by petertjeee** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6736]
Page "Direct Routing - SIP protocol" at section "Use of Request-URI parameter user=phone" the last line says:
"Microsof recommends always applying the user=phone parameter to simplify the call setup process."
And it should be "Microsoft recommends always applying the user=phone parameter to simplify the call setup process."

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
