### ISSUE TITLE
A permission policy does not allow to hide the Teams App

### ISSUE THREAD

**Issue by paul-lange** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6738]
Hi,

to hide the Teams application on the app bar a setup policy is required and not a permission policy.
I think it should also be mentioned clearly that users can still choose the Teams from the menu since it is "just hidden" and not deleted.

"Optionally, should you want to hide the Teams and Channels application from the left navigation of your users' Teams client to further focus their experience on meetings, that can be achieved by using the App" Setup policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12d73609-83a4-cdd4-8461-59fc1a9152fc
* Version Independent ID: b72ffa6e-f060-c296-e42d-eb3815a932ea
* Content: [Meeting First - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meetings-first)
* Content Source: [Teams/meetings-first.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meetings-first.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@paul-lange Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
