### ISSUE TITLE
two possible issues in view-only-meeting-experience.md

### ISSUE THREAD

**Issue by AndreasExner** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6739]
Hi,

The first paragraph contains "We have full Android and iOS mobile support for an attendee to join." The "Experience for view-only attendees" section says: "Join the Overflow Room via the Teams Android mobile app." 

The doc describes opt-out for the feature (The view-only experience is enabled by default for any organizer who has E3/E5/A3/A5 SKU.) But the internal mail from Christi Balaki points out the opt-in: View-Only Attendee experience will be rolling out as Default OFF for E3/E5/A3/A5 tenants.

Thank you :)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
