### ISSUE TITLE
View-Only Mode release confirmation

### ISSUE THREAD

**Issue by netzoft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6740]
[Enter feedback here]
Hi Cindy,
Not an issue just clarification required.
When view-only meeting experience is definitely available and how do I check?
Its March 01 today :)

Your article starts off with this note:
 **_Note
View-only meeting experience will be available in early March 2021._**

Thanks Mark

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bf705c2-1f24-bdb5-e712-e8408b941aca
* Version Independent ID: ddedd7e0-7d85-06e0-7f20-8b83b3dccec7
* Content: [View-only meeting experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/view-only-meeting-experience)
* Content Source: [Teams/view-only-meeting-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/view-only-meeting-experience.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
