### ISSUE TITLE
Reference to Export APIs for attachments

### ISSUE THREAD

**Issue by vistnesr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6741]
> Message Attachments: Export APIs include the links to the attachments that are sent as part of messages. Using Export APIs you can retrieve the files attached in the messages.

What Export APIs do you reference to?

As far as I can see, the links in the attachments are links to OneDrive and SharePoint. The links can be rewritten to Graph API links. If the attachments are stored in an external tenant, regular Graph API retrieval does not work unless explicit access has been granted in the external tenant, too. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eb2244d-b82d-0559-0255-ac0cb7ce05e3
* Version Independent ID: e3a7a842-7efe-40db-e3c7-da56d7b24c02
* Content: [Export content with the Microsoft Teams Export APIs - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/export-teams-content)
* Content Source: [Teams/export-teams-content.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/export-teams-content.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
