### ISSUE TITLE
broken AKA.MS URL

### ISSUE THREAD

**Issue by nicolasblank** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6742]
The video mentions a AKA URL, specifically http://aka.ms/teamsmoodle which resolves to a page not found error via https://education.microsoft.com/courses-and-resources/resources/microsoft-teams-moodle

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66c68e6d-936e-68f0-7405-d1e0fec62670
* Version Independent ID: f954014f-8c01-08fa-9afb-476feeb346b2
* Content: [Install Moodle integration with Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/install-moodle-integration)
* Content Source: [Teams/install-moodle-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/install-moodle-integration.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@nicolasblank  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
