### ISSUE TITLE
The attendance report is usually gathered after the meeting is completed, not during the meeting.   Is there a way to attach the csv file to meetings so that I can get the attendance after giving the call?

### ISSUE THREAD

**Issue by patrick-ryan1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6743]
https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/meeting-attendance-report  This page shows how to download Teams Meeting attendance during the call. Not after...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a8b1087-ae40-6813-16bc-a69c90e50d19
* Version Independent ID: b808e843-80d8-4a96-c6ed-e8175968eb73
* Content: [Microsoft Teams meeting attendance report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/meeting-attendance-report)
* Content Source: [Teams/teams-analytics-and-reports/meeting-attendance-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/meeting-attendance-report.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
