### ISSUE TITLE
I think the information about the default configuration is wrong

### ISSUE THREAD

**Issue by TobiasAT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6747]
The information in the post says the configuration for StreamingAttendeeMode is enabled by default. Your message center post MC240169 says the configuration is off by default. In my tenant I can confirm the configuration is Disabled by default. Please review the information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bf705c2-1f24-bdb5-e712-e8408b941aca
* Version Independent ID: ddedd7e0-7d85-06e0-7f20-8b83b3dccec7
* Content: [View-only meeting experience - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/view-only-meeting-experience#impact-to-users)
* Content Source: [Teams/view-only-meeting-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/view-only-meeting-experience.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@TobiasAT  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @TobiasAT 

Good Day! Thank you for reaching out! 

Could you please let us know on what paragraph or sentence do you see this information. Could you please highlight the sentence or let us know the exact wordings. We will verify and update it if required. 

We are looking forward to your response! Thank you!

**Comment by TobiasAT** [comment]
Hi @sowjanya365,

I see the unclear sentence was modified in commit a8840ebddf5b2918afc871885533e56d1a635bfe (line 40). I think I created the issue short before the modified text was committed. So I closing the issue. Thanks.
