### ISSUE TITLE
Errors on page..

### ISSUE THREAD

**Issue by MatthewCKelly** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6749]
in the section [Create Surface Pro device drive packages](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-scale#create-surface-pro-device-driver-packages)
 has double slashes in the target dir
`msiexec /a C:\SurfacePro_Win10.msi /passive TARGETDIR="C:\_Sources\\Drivers\Surface Pro"`
`msiexec /a C:\SurfacePro4_Win10.msi /passive TARGETDIR="C:\_Sources\\Drivers\Surface Pro 4"`

should be
`msiexec /a C:\SurfacePro_Win10.msi /passive TARGETDIR="C:\_Sources\Drivers\Surface Pro"`
`msiexec /a C:\SurfacePro4_Win10.msi /passive TARGETDIR="C:\_Sources\Drivers\Surface Pro 4"`

in the last section
[Validate and troubleshoot the solution](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-scale#validate-and-troubleshoot-the-solution)

- the tip says you can select F8 at any time..  this is only avalable when you have "Enable command support (testing only)" enabled. [customization](https://docs.microsoft.com/en-us/mem/configmgr/osd/get-started/manage-boot-images#customization)
- the smspxe.log no longer records boot information from what I have seen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4fb7681-f8cb-3723-9783-9b63563177ff
* Version Independent ID: 86c78ee0-19b0-91a1-16fc-70ee70edc0d8
* Content: [Deploy Microsoft Teams Rooms using Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-scale)
* Content Source: [Teams/rooms/rooms-scale.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-scale.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by MatthewCKelly** [comment]
Also the setup pages no longer look like that..

![First run setup page...](https://user-images.githubusercontent.com/16784124/109599919-02a07580-7b81-11eb-89b2-f4996c4e2618.png)

**Comment by scanum** [comment]
@MatthewCKelly  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
