### ISSUE TITLE
The Table - Firewall Proxy Host Name/Port Examples seems to be outdated - covering just SfB

### ISSUE THREAD

**Issue by JorgeALeitao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6752]
The Table - Firewall Proxy Host Name/Port Examples seems to be outdated - covering just SfB

I've specifically noticed that ports associated with Audio and Video seemed to be duplicate and the line covering Desktop Sharing misses de UPD ports.

If possible, a full review would be great!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a711c07e-10b3-baf0-b92c-9dbcf6ab9474
* Version Independent ID: 2038cd48-44b1-1ed1-6e50-48290eef5605
* Content: [Prepare your Environment - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-prep)
* Content Source: [Teams/rooms/rooms-prep.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-prep.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@JorgeALeitao  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@JorgeALeitao Thanks for the feedback. We will consider this when we update the article.
