### ISSUE TITLE
Enable or Disable

### ISSUE THREAD

**Issue by ingepepe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6756]
> View-only meeting experience will be available in early March 2021. This feature will be enabled on March 1,2021 as default OFF. You must change the default policy after that date if you want to have the feature be default ON. Use PowerShell to enable the policy Set-CsTeamsMeetingPolicy -Identity Global -StreamingAttendeeMode Disabled.

It is not clear if to _enable_ the feature one must _disable_ streaming attendee mode

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bf705c2-1f24-bdb5-e712-e8408b941aca
* Version Independent ID: ddedd7e0-7d85-06e0-7f20-8b83b3dccec7
* Content: [View-only meeting experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/view-only-meeting-experience)
* Content Source: [Teams/view-only-meeting-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/view-only-meeting-experience.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@ingepepe  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @ingepepe 

Thank you for reaching out! 

As per the article, the feature is disabled by default. If you would like to enable it by default, please use PowerShell to enable the policy Set-CsTeamsMeetingPolicy -Identity Global -StreamingAttendeeMode Enabled.

Hope this helps. Thank you!
