### ISSUE TITLE
Retention and automatic deletion

### ISSUE THREAD

**Issue by jrummer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6759]
This page is a little confusing in terms of the retention of recordings.  The 21 day limit says its for A1 licensed users.  I thought the retention of meetings was indefinite for enterprise tenants using E3 and E5 licensing.  Can this be clarified?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@jrummer  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tonysmit** [comment]
@CarolynRowe - do you own this article, or do you know who would? For some reason I ended up being listed as the owner/writer. Thanks, Tony

**Comment by tiburd** [comment]
@jrummer - Hi, it looks like this article has been updated since the time that you opened this issue, so I'm closing this issue. If your concern still exists in the updated article, please open a new issue. 

Thank you!
