### ISSUE TITLE
DSPC acronym not defined

### ISSUE THREAD

**Issue by drewjames1234** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6761]
I cannot find an explanation for this acronym on this page.  
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76c2487c-044d-1349-708a-5841fcb21ab8
* Version Independent ID: b7033454-1a9c-48d4-8004-78415c5feb89
* Content: [Implement Quality of Service in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/qos-in-teams#validate-the-qos-implementation)
* Content Source: [Teams/QoS-in-Teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/QoS-in-Teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@drewjames1234  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@drewjames1234 DSCP comes from differentiated services code point. More details [here](https://en.wikipedia.org/wiki/Differentiated_services)

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
