### ISSUE TITLE
pstn acronym not explained

### ISSUE THREAD

**Issue by drewjames1234** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6765]
[Enter feedback here]
As above - needs decoding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ad0c889-56d5-35fe-de15-177b6d922d07
* Version Independent ID: e4363647-33e1-b665-5881-169fb619a5b3
* Content: [Microsoft Teams PSTN usage report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/pstn-usage-report)
* Content Source: [Teams/teams-analytics-and-reports/pstn-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/pstn-usage-report.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@drewjames1234  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@drewjames1234 PSTN stands for public switched telephone network.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
