### ISSUE TITLE
What about the RC4 Cipher Suite?

### ISSUE THREAD

**Issue by eragon921** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#678]
So I've been running into this a lot in my Skype deployments. I go to my servers and disable TLS 1.0, 1.1, SSL2 and SSL3. I also disable all the week ciphers (i.e. everything below AES 128). Magically my mediation and edge servers start throwing fits! Media no longer flows. So I go back in and enable RC4 128/128 and it all starts working again.

I can find ZERO documentation on the required cipher suites for Skype for Business. I can only fine "we support TLS 1.2 now" etc. Has anyone else run into this? The security folks at my various clients are going nuts about us leaving any RC4 cipher open on servers that (even if they're in the DMZ) have to be exposed to the internet. I've gotten no word from MS on potential patches to SFB 2015 or if RC4 use is actually deprecated in 2019.

**Comment by AndreaBarr** [comment]
@eragon921 Thank you for this feedback

I want to make sure this gets addressed the best way possible so I am sending this to the Teams team and I would also like you to oppen up a support ticket for it as well so we can tackel this from both sides. 

I have put a not for the Teams team to reply to you with information once they have any word on this issue as well. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by eragon921** [comment]
So I asked my Microsoft PFE and this is what he got back,

Officially Microsoft does *not* support disabling individual ciphers in a
Skype for Business environment.  We do support disabling TLS 1.0/1.1, with
the proper CU and following documented procedures.  However, the product
group has not tested disabling individual ciphers and will *not* support an
environment that does disable them individually.  From the product group
the reason RC4 is most definitely required is that the initial connection
header appears to CryptoAPI as an RC4 request.  While it is not an RC4
request, if RC4 is disabled CryptoAPI won’t even process the request to
find an acceptable cipher.  According to the product group they are *not*
using RC4, but the connection header utilizes the same format as RC4.  The
product group currently has no plans to change this aspect of the product
due to the high costs involved in changing all of the initial connection
portions of the product.
 Seth Schumacher

**Comment by AndreaBarr** [comment]
@eragon921 Thank you for this feedback

I will make sure this is sincluded in the backlog. I appricate the extra bit of information so we can get this updated.

**Comment by scanum** [comment]
@MicrosoftHeidi Any updates on this issue? Thanks!

**Comment by sritodi** [comment]
https://support.microsoft.com/en-us/help/2868725/microsoft-security-advisory-update-for-disabling-rc4

Audiocodes uses RC4 by default and this can be changed to other Cipher suites like AES128-SHA256

**Comment by MSFTTracyP** [comment]
Hi all, sorry for the delay. I've  been ill. Please take a look at the answer from @eragon921 and PFE. Disabling individual ciphers isn't supported by the Product Group with good reason. Please see the answer above and also, thank you, Seth!

**Comment by sritodi** [comment]
The challenge is that Audio Codes uses it by default, and due to some regulations, RC4 is considered to be less secure. So chances are that in such environments, we would experience this issue.

Some public documentation, along with partnering with AudioCodes to change the default to a different CIPHER would be a great start.

**Comment by scanum** [comment]
@eragon921 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
