### ISSUE TITLE
[Guc@microsoft.com] the usage location of the resource account need to match the service number location, it's not documented. 

### ISSUE THREAD

**Issue by chenguyuan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6789]
[Guc@microsoft.com] the usage location of the resource account need to match the service number location, it's not documented. 

Please review and add it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@chenguyuan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @chenguyuan 

Thank you for your valuable feedback! Very helpful! 

This is noted! Our team will review your suggestion during the next review of the documentation and include the necessary information based on the requirement and validation. 

Thank you!
