### ISSUE TITLE
No Notifications on Mac

### ISSUE THREAD

**Issue by manseuk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#679]
I use teams a lot - and its worked fine since I started using it - but with the latest release im not getting any sound / screen notifications when a message arrives - all I get is a little (1) appear above the icon on the dock. Please help !! its very annoying

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e1b8fbb-3047-dd3a-6a9c-ae6b1d5a0222
* Version Independent ID: 42c418d1-8473-2243-81bc-558e0a0688aa
* Content: [Overview of Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/Teams-overview#teams-client-release-noteshttpssupportofficecomarticlerelease-notes-for-microsoft-teams-d7092a6d-c896-424c-b362-a472d5f105de)
* Content Source: [Teams/Teams-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@manseuk Thank you for this feedback.

I want to make sure we get this notification issue taken care of. Support will be able to handle this issue to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
