### ISSUE TITLE
Teams Engineering CPM is telling us 25k Teams already shipped to GCC

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6794]
The documentation still lists 10k as the limit for members in a team, and then has a callout below that says the limit in GCC is only 5k. Our Teams Engineering CPM is telling us that the limit was increased to 25k in GCC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@npherson  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@npherson The article has been updated to reflect that:

![image](https://user-images.githubusercontent.com/41186174/110621591-11031880-81a3-11eb-89fa-2d8fbff9fbf7.png)

![image](https://user-images.githubusercontent.com/41186174/110621618-182a2680-81a3-11eb-9eaf-820bc204bd8c.png)

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
