### ISSUE TITLE
Dead links on the test-spec page

### ISSUE THREAD

**Issue by mrtkz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6797]
The links for "Skype Certification Video Analyzer" and "Video TMT for Skype" on the test-spec page are invalid.
These need to be replaced with the correct links.

https://docs.microsoft.com/en-us/skypeforbusiness/certification/test-spec
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbPartnerCertification/certification/test-spec.md

**Comment by scanum** [comment]
@mrtkz Please link the documentation you are referring to. Thanks!

**Comment by mrtkz** [comment]
@scanum I'm sorry, please tell me how to link you want.
