### ISSUE TITLE
Disabling the Teams SKU needs about 24 hours to take effect

### ISSUE THREAD

**Issue by Jeremy919** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6799]
It takes about 24 hours for disabling a Teams SKU to take effect...this document needs to make readers aware of that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cccdd91a-7f05-abd5-ed94-e82152b86914
* Version Independent ID: 3532d0a8-119c-f7d0-0d4f-a865ad32570f
* Content: [Manage user access to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/user-access)
* Content Source: [Teams/user-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/user-access.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@Jeremy919  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @Jeremy919 

Thank you for your valuable feedback! Very helpful!

This is noted! Our team will review your suggestion during the next review of the documentation and include the necessary information based on the requirement and validation.

Thank you!
