### ISSUE TITLE
How about Pass Through Authentication?

### ISSUE THREAD

**Issue by JBWCowling** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#68]
The notes for synchronized identity say that password hash sync must be enabled, but I suspect that PTA would work as well - can you clarify the doc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6383162-7bcd-70cc-f7dd-b818d236bfdf
* Version Independent ID: 34c9897a-29ae-0048-30ce-da5abaffb76a
* Content: [Identity models and authentication in Microsoft Teams | Microsoft Docs](https://docs.microsoft.com/en-us/MicrosoftTeams/identify-models-authentication)
* Content Source: [Teams/identify-models-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/identify-models-authentication.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by LolaJacobsen** [comment]
Thanks for your comment. I'm checking now with the PM for this feature. Stay tuned.

**Comment by Ansuman777** [comment]
Hello Lola, I am here. Do you see me? @LolaJacobsen

**Comment by Ansuman777** [comment]
Actually, Roshin Ramesan is the right PM for this :)

**Comment by LolaJacobsen** [comment]
Thanks, @Ansuman777. I'll assign this to Roshin now.

**Comment by LolaJacobsen** [comment]
@JBWCowling:  According to the PM for this feature, @somakbhattacharyya, we're investigating support for Pass Through Authentication (PTA), but currently it's not supported. Please check the Teams Roadmap to see what's coming next in Teams. https://aka.ms/TeamsRoadmap.
