### ISSUE TITLE
Please update the list to keep track on all known bugs 

### ISSUE THREAD

**Issue by JohanssonMarkus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6802]
I doubt there are only 6 known bugs for Teams. 
Please update the list with all known issue.
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/35871766-keep-the-known-issues-list-updated

On (https://microsoftteams.uservoice.com/) page there are 6972 bugs reported. 
I'm tired of spending lots of hours with fault analysis and then come to the conclusion that it was a known bug after several days with a ms premier ticket. Please share all known bugs so we can work more efficient with this.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bef5b5fd-5a4e-7957-f23c-724764a7cb4c
* Version Independent ID: 5fe6c3ab-774b-db2f-5b55-9170bdfe5faf
* Content: [Known issues - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/known-issues)
* Content Source: [Teams/rooms/known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/known-issues.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
