### ISSUE TITLE
Questions about the info in the Doc

### ISSUE THREAD

**Issue by chad-at-rsm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6804]
How do you tell where the SharePoint site that backs a Team is located? How do you tell which satellite Geo a team was created in? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c65240c7-8a9e-cf39-008d-2c8b12534b0d
* Version Independent ID: 9a1e12a6-f020-7782-e749-8e4909fa8d0c
* Content: [Teams experience in a Microsoft 365 Multi-Geo-enabled environment - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-experience-o365odb-spo-multi-geo)
* Content Source: [Teams/teams-experience-o365odb-spo-multi-geo.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-experience-o365odb-spo-multi-geo.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
