### ISSUE TITLE
Support client information should be consolidated

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6806]
While there is a "supported clients" section, there is also information about client support in at least two other locations, that should be consolidated into the "supported clients" section. 

These are 
" (Subnet and WiFi AP are supported. Ethernet switch/port is supported on Windows 8.1 and later at this time)." in the "Assign emergency addresses" section right below it, and

"Both subnets and wireless access points (WAPs) are supported. Ethernet switch/port is supported on Windows 8.1 and later at this time." in the "Configure Location Information Service" section below.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 358dfc73-9414-13e2-4682-c3e82603692f
* Version Independent ID: 3faae1d9-efbe-c20c-6598-a5073c2306e2
* Content: [Configure dynamic emergency calling - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/configure-dynamic-emergency-calling#assign-emergency-addresses)
* Content Source: [Teams/configure-dynamic-emergency-calling.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/configure-dynamic-emergency-calling.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by lindspea** [comment]
@CarolynRowe

**Comment by scanum** [comment]
@TorrenManson Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
