### ISSUE TITLE
Windows Installation Media

### ISSUE THREAD

**Issue by kort3x** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6808]
To use SRS 4.7.19.0 we need a Windows image 10.0.18362.418 but this is not available for download fom MS.
We checked VLSC, MSDN and MPN - there is no image of this version anywhere.

How are we supposed to use SRS?

**Comment by RAJU2529** [comment]
@kort3x , you can download from below site  build np 18363.418 
https://tb.rg-adguard.net/public.php
![Capture](https://user-images.githubusercontent.com/3296790/110352842-67b20a80-805c-11eb-8b30-8f57f81dfa0b.JPG)
