### ISSUE TITLE
Walkie Talkie Platform Availability

### ISSUE THREAD

**Issue by O365scripts** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6809]
Hello again!

I was wondering if could have have mention of the limitations of this feature as it is not clearly stated that it currently works **only** on Android devices?

This is the currently the closest sentence that hints it works for Android only:
"Once enabled, Walkie Talkie will become available on the Android app within 48 hours."

There should be a more explicit mention that iOS devices as well as Teams desktop/web are not supported.

Not part of the OfficeDocs repo but the https://support.microsoft.com/en-us/office/get-started-with-teams-walkie-talkie-25bdc3d5-bbb2-41b7-89bf-650fae0c8e0c page should have a similar mention as well.

Thanks as always!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d91ddefc-3722-8bc2-bd9b-4a90ede28944
* Version Independent ID: 35e56a9d-a01c-4126-3750-aae1ed984f55
* Content: [Walkie Talkie application in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/walkie-talkie)
* Content Source: [Teams/walkie-talkie.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/walkie-talkie.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by ndambrosio** [comment]
The first line in the document states **_ The Walkie Talkie app in Teams provides instant push-to-talk (PTT) communication for your team and is now available on Android. _**

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
