### ISSUE TITLE
Incorrect instructions in 'Enable the device account' section, bullet 2

### ISSUE THREAD

**Issue by TexTown** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6812]
In the 'Enable the device account' section, 
At step 2. we need to obtain the UPN (or another Identity property) of the account (not the SIP address, that doesn't' exist yet)
At step 3, the SIP address is configured (by setting it to match the EmailAddress 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91cd0219-b3b0-da60-6416-c6b5a67623e3
* Version Independent ID: 983d08b5-4a2c-838a-52eb-821045d2c9df
* Content: [Deploy Microsoft Teams Rooms with Exchange on-premises - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-exchange-on-premises)
* Content Source: [Teams/rooms/with-exchange-on-premises.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-exchange-on-premises.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@TexTown Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@dstrome please can you assist here?

**Comment by lindspea** [comment]
@dstrome please can you help here?

**Comment by dstrome** [comment]
article replaced
