### ISSUE TITLE
Add PowerShell steps too please

### ISSUE THREAD

**Issue by DanScottExpo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6813]
[Can we also have the PowerShell steps included so we can to automate holiday creation?  its an onerous and long winded task when we are doing this for new auto attendants on new tenants, so a PS script could easily populate the local regions default holidays]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9908d77-78bc-ce88-ba84-4f1bd9fea504
* Version Independent ID: 37118dd4-d036-8da7-d750-4c9f503a370a
* Content: [Set up holidays in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-holidays-in-teams)
* Content Source: [Teams/set-up-holidays-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-holidays-in-teams.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@DanScottExpo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@MikePlumleyMSFT is this possible?

**Comment by MikePlumleyMSFT** [comment]
@CLYVR do you know if scripting holidays is possible?

**Comment by CLYVR** [comment]
The existing cmdlet documentation has examples of how to script for holidays.  Please see example 3 here which sets a Christmas holiday: https://docs.microsoft.com/en-us/powershell/module/skype/new-csautoattendant?view=skype-ps
