### ISSUE TITLE
The release notes site is obsolete.

### ISSUE THREAD

**Issue by rezabj** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6814]
The release notes site is obsolete.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 173b5929-529b-938b-b6ab-59f05a5d69a8
* Version Independent ID: 0a3dfe5e-938f-933d-637e-b7449e3b8aa5
* Content: [Microsoft Teams PowerShell Release Notes - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-release-notes#feedback)
* Content Source: [Teams/teams-powershell-release-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-release-notes.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by Joey40** [comment]
Can we please get this updated?  There's a new major version out as of last week, but there hasn't been an update to the change log in months.

**Comment by scanum** [comment]
@rezabj Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@rezabj thank you for helping improve MS Docs. I see the current version is 2.1.0 (April 2021) and the release notes are reading correctly. Apologies if I'm missing something, but please can you clarify.

**Comment by rezabj** [comment]
It looks good. Thanks for update.
