### ISSUE TITLE
CalendarProcessing Subject

### ISSUE THREAD

**Issue by PChipVIA** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#682]
Hi, Why does the Set-CalendarProcessing command in step 3 removes the Organizer from subject and keeps the original meeting subject?  Is this a requirement for SRS to work?  
If yes, can a warning be provided that it does that?  There are security implications (say the meeting subject is "Process to fire user X", now that user X could see it just browsing the calendar in Outlook) and user implications (Train them to have generic subjects so above does not happen).
If no, then can that part be adjusted to *just* AutoAccept meetings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8289b8af-2562-69bc-7d7e-a47845bf4ebe
* Version Independent ID: 4097b196-fdca-df05-4c78-27e5cc03abfc
* Content: [Skype Room System single forest on-premises deployments](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/single-forest-on-premises-deployments)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/single-forest-on-premises-deployments.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/single-forest-on-premises-deployments.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by PChipVIA** [comment]
Thing is, when you do this command, users in Outlook cannot see the Organizer when attempting to create a meeting in the future (in order to adjust internally any conflicts).  Just keep in mind

**Comment by PChipVIA** [comment]
@AndreaBarr

This is a Skype issue not a SharePoint/OneDrive issue so adding it to the SharePoint uservoice would be pointless 😊



Salutations / Regards / Cordial Saludo

Pascal Verdieu
Windows Systems intermediate Administrator / Information Technology
Administrateur intermédiare Systèmes Windows / Technologie de l'information

VIA Rail Canada
3 Place Ville Marie, Suite 500, Montréal, Québec, H3B 2C9
T : 514.871.6989 / C : 514.709.7290 / E : Pascal_Verdieu@viarail.ca

[cid:image008.png@01D389FA.FFAD67A0]

Thank you for being on board! / Merci d’être partant !

**Comment by AndreaBarr** [comment]
@PChipVIA sorry about that I didn't grab the right user voice link. Here is the right link.

https://microsoftteams.uservoice.com/forums/555103-public
