### ISSUE TITLE
Script Error - TeamsIn did not receive media renegotiation for holding call

### ISSUE THREAD

**Issue by mod-matt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6820]
Hi,

Receiving the following error using the script "TeamsIn did not receive media renegotiation for holding call".

Same error with 3 different Teams account in different tenants and changing around the inbound/outbound caller.

Any ideas please? 

VERBOSE: Populating RepositorySourceLocation property for module PackageManagement.
VERBOSE: Loading module from path 'C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.4.4\PackageManagement.psm1'.
VERBOSE: Loading module from path 'C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.4.4\PackageManagement.psd1'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.4.4\PackageManagement.format.ps1xml'.
VERBOSE: Populating RepositorySourceLocation property for module PackageManagement.
VERBOSE: Loading module from path 'C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.4.4\PackageManagement.psm1'.
VERBOSE: Exporting cmdlet 'Find-Package'.
VERBOSE: Exporting cmdlet 'Find-PackageProvider'.
VERBOSE: Exporting cmdlet 'Get-Package'.
VERBOSE: Exporting cmdlet 'Get-PackageProvider'.
VERBOSE: Exporting cmdlet 'Get-PackageSource'.
VERBOSE: Exporting cmdlet 'Import-PackageProvider'.
VERBOSE: Exporting cmdlet 'Install-Package'.
VERBOSE: Exporting cmdlet 'Install-PackageProvider'.
VERBOSE: Exporting cmdlet 'Register-PackageSource'.
VERBOSE: Exporting cmdlet 'Save-Package'.                                                                               VERBOSE: Exporting cmdlet 'Set-PackageSource'.                                                                          VERBOSE: Exporting cmdlet 'Uninstall-Package'.                                                                          VERBOSE: Exporting cmdlet 'Unregister-PackageSource'.                                                                   VERBOSE: Importing cmdlet 'Find-Package'.
VERBOSE: Importing cmdlet 'Find-PackageProvider'.
VERBOSE: Importing cmdlet 'Get-Package'.
VERBOSE: Importing cmdlet 'Get-PackageProvider'.                                                                        VERBOSE: Importing cmdlet 'Get-PackageSource'.                                                                          VERBOSE: Importing cmdlet 'Import-PackageProvider'.                                                                     VERBOSE: Importing cmdlet 'Install-Package'.                                                                            VERBOSE: Importing cmdlet 'Install-PackageProvider'.                                                                    VERBOSE: Importing cmdlet 'Register-PackageSource'.                                                                     VERBOSE: Importing cmdlet 'Save-Package'.                                                                               VERBOSE: Importing cmdlet 'Set-PackageSource'.                                                                          VERBOSE: Importing cmdlet 'Uninstall-Package'.                                                                          VERBOSE: Importing cmdlet 'Unregister-PackageSource'.                                                                   VERBOSE: Acquiring AAD token...                                                                                         VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\ADAL.PS\3.19.8.1\ADAL.PS.psd1'.           VERBOSE: Loading 'Assembly' from path 'C:\Program                                                                       Files\WindowsPowerShell\Modules\ADAL.PS\3.19.8.1\Microsoft.IdentityModel.Clients.ActiveDirectory.3.19.8\Microsoft.Ident ityModel.Clients.ActiveDirectory.dll'.                                                                                  VERBOSE: Loading 'Assembly' from path 'C:\Program                                                                       Files\WindowsPowerShell\Modules\ADAL.PS\3.19.8.1\Microsoft.IdentityModel.Clients.ActiveDirectory.3.19.8\Microsoft.Ident ityModel.Clients.ActiveDirectory.dll'.                                                                                  VERBOSE: Loading 'Assembly' from path 'C:\Program                                                                       Files\WindowsPowerShell\Modules\ADAL.PS\3.19.8.1\Microsoft.IdentityModel.Clients.ActiveDirectory.3.19.8\Microsoft.Ident ityModel.Clients.ActiveDirectory.Platform.dll'.                                                                         VERBOSE: Loading 'Assembly' from path 'C:\Program                                                                       Files\WindowsPowerShell\Modules\ADAL.PS\3.19.8.1\Microsoft.IdentityModel.Clients.ActiveDirectory.3.19.8\Microsoft.Ident ityModel.Clients.ActiveDirectory.Platform.dll'.                                                                         VERBOSE: Populating RepositorySourceLocation property for module ADAL.PS.                                               VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\ADAL.PS\3.19.8.1\ADAL.PS.psm1'.           VERBOSE: Exporting function 'Get-ADALAuthenticationContext'.                                                            VERBOSE: Exporting function 'New-ADALUserIdentifier'.                                                                   VERBOSE: Exporting function 'New-ADALClientCredential'.                                                                 VERBOSE: Exporting function 'Get-ADALToken'.                                                                            VERBOSE: Exporting function 'Clear-ADALTokenCache'.                                                                     VERBOSE: Importing function 'Clear-ADALTokenCache'.                                                                     VERBOSE: Importing function 'Get-ADALAuthenticationContext'.                                                            VERBOSE: Importing function 'Get-ADALToken'.                                                                            VERBOSE: Importing function 'New-ADALClientCredential'.                                                                 VERBOSE: Importing function 'New-ADALUserIdentifier'.                                                                   VERBOSE: Acquiring AAD token...DONE                                                                                     VERBOSE: Enqueueing test...                                                                                             VERBOSE: POST https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites with -1-byte payload                       VERBOSE: received 407-byte response of content type application/json; charset=utf-8                                     VERBOSE: Enqueueing test...DONE                                                                                         VERBOSE: Test status link:                                                                                              https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/2cc3beef-8d89-406d-8471-730eaec88bc2                     VERBOSE: Checking test status...                                                                                        VERBOSE: GET https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/2cc3beef-8d89-406d-8471-730eaec88bc2 with   0-byte payload                                                                                                          VERBOSE: received 1042-byte response of content type application/json; charset=utf-8                                    VERBOSE: Test in 'scheduled' state; Checking again in 10 seconds...                                                     VERBOSE: GET https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/2cc3beef-8d89-406d-8471-730eaec88bc2 with   0-byte payload                                                                                                          VERBOSE: received 1279-byte response of content type application/json; charset=utf-8                                    VERBOSE: Test in 'dialing' state; Checking again in 10 seconds...                                                       VERBOSE: GET https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/2cc3beef-8d89-406d-8471-730eaec88bc2 with   0-byte payload                                                                                                          VERBOSE: received 1379-byte response of content type application/json; charset=utf-8                                    VERBOSE: Test in 'playingAudio' state; Checking again in 10 seconds...                                                  VERBOSE: GET https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/2cc3beef-8d89-406d-8471-730eaec88bc2 with   0-byte payload                                                                                                          VERBOSE: received 1379-byte response of content type application/json; charset=utf-8                                    VERBOSE: Test in 'playingAudio' state; Checking again in 10 seconds...                                                  VERBOSE: GET https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/2cc3beef-8d89-406d-8471-730eaec88bc2 with   0-byte payload                                                                                                          VERBOSE: received 1368-byte response of content type application/json; charset=utf-8                                    VERBOSE: Test in 'heldCall' state; Checking again in 10 seconds...                                                      VERBOSE: GET https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/2cc3beef-8d89-406d-8471-730eaec88bc2 with
0-byte payload
VERBOSE: received 1368-byte response of content type application/json; charset=utf-8
VERBOSE: Test in 'heldCall' state; Checking again in 10 seconds...
VERBOSE: GET https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/2cc3beef-8d89-406d-8471-730eaec88bc2 with
0-byte payload
VERBOSE: received 1368-byte response of content type application/json; charset=utf-8
VERBOSE: Test in 'heldCall' state; Checking again in 10 seconds...
VERBOSE: GET https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/2cc3beef-8d89-406d-8471-730eaec88bc2 with
0-byte payload
VERBOSE: received 1640-byte response of content type application/json; charset=utf-8
VERBOSE: Test in 'retrievingCallDataFromCdr' state; Checking again in 10 seconds...
VERBOSE: GET https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/2cc3beef-8d89-406d-8471-730eaec88bc2 with
0-byte payload
VERBOSE: received 1640-byte response of content type application/json; charset=utf-8
VERBOSE: Test in 'retrievingCallDataFromCdr' state; Checking again in 10 seconds...
VERBOSE: GET https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/2cc3beef-8d89-406d-8471-730eaec88bc2 with
0-byte payload
VERBOSE: received 1640-byte response of content type application/json; charset=utf-8
VERBOSE: Test in 'retrievingCallDataFromCdr' state; Checking again in 10 seconds...
VERBOSE: GET https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/2cc3beef-8d89-406d-8471-730eaec88bc2 with
0-byte payload
VERBOSE: received 1640-byte response of content type application/json; charset=utf-8
VERBOSE: Test in 'retrievingCallDataFromCdr' state; Checking again in 10 seconds...
VERBOSE: GET https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/2cc3beef-8d89-406d-8471-730eaec88bc2 with
0-byte payload
VERBOSE: received 1640-byte response of content type application/json; charset=utf-8
VERBOSE: Test in 'retrievingCallDataFromCdr' state; Checking again in 10 seconds...
VERBOSE: GET https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/2cc3beef-8d89-406d-8471-730eaec88bc2 with
0-byte payload
VERBOSE: received 1640-byte response of content type application/json; charset=utf-8
VERBOSE: Test in 'retrievingCallDataFromCdr' state; Checking again in 10 seconds...
VERBOSE: GET https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/2cc3beef-8d89-406d-8471-730eaec88bc2 with
0-byte payload
VERBOSE: received 1640-byte response of content type application/json; charset=utf-8
VERBOSE: Test in 'retrievingCallDataFromCdr' state; Checking again in 10 seconds...
VERBOSE: GET https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/2cc3beef-8d89-406d-8471-730eaec88bc2 with
0-byte payload
VERBOSE: received 1640-byte response of content type application/json; charset=utf-8
VERBOSE: Test in 'retrievingCallDataFromCdr' state; Checking again in 10 seconds...
VERBOSE: GET https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites/2cc3beef-8d89-406d-8471-730eaec88bc2 with
0-byte payload
VERBOSE: received 1598-byte response of content type application/json; charset=utf-8
VERBOSE: Test in 'failed' state

Test: Outbound to Inbound

result.state result.code result.phrase
------------ ----------- -------------
failed              1511 TeamsIn did not receive media renegotiation for holding call

teamsOut.chainId                     teamsOut.sipCallId               teamsOut.trunkFqdn teamsOut.callEndReasonPhrase teamsOut.callEndReason teamsOut.callEndSubReason teamsOut.state teamsOut.code teamsOut.callSetupTimeMs teamsOut.callStartTime
----------------                     ------------------               ------------------ ---------------------------- ---------------------- ------------------------- -------------- ------------- ------------------------ ----------------------
2fe56a55-fd2e-481b-b31e-8ed5e1312169 c498675ac9345f61bb34204f869dcd57 SBCNAME.XXX.COM   LocalUserInitiated                                0                         0 signedOut                                        5582 2021-03-09T11:23:11.2557654Z

teamsIn.chainId                      teamsIn.lastAction teamsIn.state teamsIn.code teamsIn.phrase                                               teamsIn.callSetupTimeMs teamsIn.callStartTime       teamsIn.flow
---------------                      ------------------ ------------- ------------ --------------                                               ----------------------- ---------------------       ------------
bdfdac73-680f-48e1-a073-78776a989c36 holdingCall        failed                1511 TeamsIn did not receive media renegotiation for holding call                    5098 2021-03-09T11:23:11.255722Z inbound

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
