### ISSUE TITLE
Add note that this command is not available for use in direct routing scenarios

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6823]
MediaRelayRoutingLocationOverride is reserved for use with managed carriers as noted in incident 226934920. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a420204-479f-d8c9-ea30-9f07431b4b42
* Version Independent ID: a67787ef-c6ac-74bb-baef-5835391b5949
* Content: [Direct Routing country codes - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-country-codes)
* Content Source: [Teams/direct-routing-country-codes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-country-codes.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@TheBluLion Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
