### ISSUE TITLE
Is a bot the only way for an app to send a message?

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6825]
Is a bot the only way for an app to send a message, or is it possible for a Teams app to send a message to a conversation without being connected to a bot? Perhaps this doc could be updated to explain that

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2081f0e-cc69-8c64-2fe9-5ba8a9e36ed3
* Version Independent ID: 629041e6-01c5-f78c-84c6-8ede02ee0ade
* Content: [Apps, bots, & connectors in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/deploy-apps-microsoft-teams-landing-page)
* Content Source: [Teams/deploy-apps-microsoft-teams-landing-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/deploy-apps-microsoft-teams-landing-page.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
