### ISSUE TITLE
Microsoft - how many times do we have to tell you: if you have a feature (such as 'forward email from Outlook to a Teams Chat') and then you take that feature away - PLEASE DOCUMENT CLEARLY THE FACT THAT THE FEATURE HAS BEEN REMOVED - it is really bloody annoying finding old documentation saying it can be done, and new documentation that simply says NOTHING, but nothing that clearly says DON'T WASTE YOUR TIME TRYING, WE BROKE IT ITS GONE!

### ISSUE THREAD

**Issue by sarahmcm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6827]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f34a4f9-bb6f-03e9-9c11-bb2f43dd9aeb
* Version Independent ID: a6e1ee45-8ce4-96b4-21ad-90ca8af646c4
* Content: [Teams and Outlook email integration - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-outlook-email-integration)
* Content Source: [Teams/teams-outlook-email-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-outlook-email-integration.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @sarahmcm how are you? hope you are doing good.
Do you mean [this feature](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=Outlook&searchterms=71265)?
Thanks for clarifying, so I can investigate this.
Thanks again

**Comment by nam31** [comment]
@sarahmcm We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
