### ISSUE TITLE
No thresholds/reference values for "other telemetry data" 

### ISSUE THREAD

**Issue by stasfeelin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6828]
Hi
I'd like to ask if there are any defined normal values for telemetry's stats of items listed in the article like [other things to check](https://docs.microsoft.com/en-us/microsoftteams/cqd-frequently-asked-questions#why-does-cqd-mark-a-call-as-good-if-one-or-more-meeting-participants-had-a-poor-experience) (related to CPU and peripheral performance)? Could you please share it and add to the documentation?

> If network metrics look good in the averages and max values, then look to other telemetry data:
> 
> - Check **_CPU Insufficient Event Ratio_** to see if the detected CPU resources available were insufficient and caused poor quality.
> - Was the audio device in Half Duplex mode to prevent feedback due to microphones that are to close to speakers?
> - Check the **_Device Half Duplex AEC Event Ratio_**. Was the device glitching or the microphone glitching introducing noise or static due to USB Audio Drop outs when plugged into a Hub or Docking Station:
> - Check the **_Device Glitches and Microphone glitches event ratios_**. Was the device itself functioning properly?
> - Check the **_Capture and Render Device Not Functioning Event Ratios_**.

What are the normal values and what are the thresholds for dimensions highlighted above? 
Microsoft definitely have them because in TAC we can see sessions with highlighted "Poor call quality caused by an audio device." but I haven't found any thresholds within the documentation except "look to other telemetry data" with high level description of fields that could be potentially useful, which is good, but with no reference values, which makes this information irrelevant for analysis because we don't have a clear marker (call marked as good) and thresholds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de72ba4-417f-b90d-6cf4-1af9fbbce5f1
* Version Independent ID: 94abea2e-541a-3d3c-c9da-f8544bbc98d1
* Content: [Call Quality Dashboard (CQD) Frequently asked questions (FAQ) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cqd-frequently-asked-questions)
* Content Source: [Teams/CQD-frequently-asked-questions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-frequently-asked-questions.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by stasfeelin** [comment]
With Microsoft help we found some portion of information on another page (related to TAC) about call quality impacted by someone's device:
https://docs.microsoft.com/en-us/microsoftteams/use-call-analytics-to-troubleshoot-poor-call-quality

| Device not functioning | Device | A device isn't functioning correctly.<br>Device not functioning ratios are:<br>DeviceRenderNotFunctioningEventRatio >= 0.005<br>DeviceCaptureNotFunctioningEventRatio >= 0.005 |
|-|-|-|
