### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by aamillerMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6834]
The "Pricing for Audio Conferencing" link on this page is broken.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b07cfcf-8f31-91ed-b1de-c7826a1ab91d
* Version Independent ID: dfbc4212-8f47-326a-f872-8186a915ae1e
* Content: [Country/region availability - Audio Conferencing, Calling Plans - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans?toc=/skypeforbusiness/toc.json&bc=/skypeforbusiness/breadcrumb/toc.json)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by RAJU2529** [comment]
@aamillerMSFT , is  below link is  suitable or not ?
https://www.microsoft.com/en-in/microsoft-teams/compare-microsoft-teams-options

**Comment by aamillerMSFT** [comment]
It should be pointed to here.  https://go.microsoft.com/fwlink/?linkid=799762


Similar to this this section of this site: What are Communications Credits? - Microsoft Teams | Microsoft Docs<https://docs.microsoft.com/en-us/microsoftteams/what-are-communications-credits#want-to-know-about-plans-and-pricing>
Want to know about plans and pricing?
You can see the plans and pricing by visiting one of the following links:
*        Calling Plans<https://go.microsoft.com/fwlink/?linkid=799761>
*        Audio Conferencing<https://go.microsoft.com/fwlink/?linkid=799762>
*        Phone System<https://go.microsoft.com/fwlink/?linkid=799763>
