### ISSUE TITLE
Example Efficiency 

### ISSUE THREAD

**Issue by hsbsandrecv** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6835]
In the Section: "Use the New-CsBatchPolicyAssignmentOperation cmdlet"
The command "$restrictedAnonymousUsers = @(Get-CsOnlineUser |? TeamsMeetingPolicy -eq "RestrictedAnonymousAccess" | %{ $_.ObjectId })"  take too long and times out when there is thousands of users, my suggestion would be

$restrictedAnonymousUsers  = @(Invoke-Command  -scriptblock {Get-CsOnlineUser -ResultSize 5000 -Filter "TeamsMeetingPolicy -eq 'RestrictedAnonymousAccess'" | select-object -property ObjectId}).ObjectId

ps. Using the newer version of Teams Powershell module

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a55f6ae5-c345-452e-ccdc-0debc3c02dbd
* Version Independent ID: 8625a20c-852c-c2f1-a708-0c2926c8dc9c
* Content: [Remove the RestrictedAnonymousAccess Teams meeting policy from users - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-restricted-anonymous-access)
* Content Source: [Teams/meeting-policies-restricted-anonymous-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-restricted-anonymous-access.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by hsbsandrecv** [comment]
"With batch policy assignment, the maximum number of users for which you can remove or update policies is 5,000 at a time. For example, if you have more than 5,000 users, you'll need to submit multiple batches"

I was able to run a Batch with more than 5,000 so what is the REAL limit?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by hsbsandrecv** [comment]
a ticket was opened to deal with the specific issue. My post here was to outline a BETTER way to accomplish the result of the Example in a MORE EFFICIENT way. Please disregard, if this kind of input is NOT the intent of this feedback page.

BTW, the example on this DOC does not work for large tenats. (Just to let you know).  I DO NOT WANT Support here.
