### ISSUE TITLE
Error on startup after fresh OS image.

### ISSUE THREAD

**Issue by glenlewisdd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#684]
The startup gets stuck on "Windows cannot complete the installation", restart to try again.  It restarts and just cycles on that screen.
I have a surface pro 4(2017) using the steup option for Logitech smartdock.
I booted the surface up for the first time after the image was applied while in the case (Attached to the SmartDock dock).  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51d42140-9f7b-a6f3-7a3e-76cc7331cf22
* Version Independent ID: a7dacc56-c2df-55fb-76a3-ecb194564fae
* Content: [Configure a Skype Room Systems v2 console](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/console)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/console.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @Travis-Snoozy
* Microsoft Alias: **jambirk**

**Comment by Travis-Snoozy** [comment]
Please attach the transcript that the CreateSrsMedia.ps1 script generated.

Disconnect the Surface Pro from everything except power (not a dock, just a power cable), the USB boot media, and (optionally) a keyboard. Reboot to the USB boot media again, and let the system continue through until it shuts itself down. Once the shutdown occurs, you can then connect the device to the dock.

**Comment by Travis-Snoozy** [comment]
@glenlewisdd -- please indicate if your issue is persisting with the clarified instructions.

**Comment by glenlewisdd** [comment]
Yes that resolved it sorry, thank you for the help
