### ISSUE TITLE
Private channel site management is scoped to PowerShell

### ISSUE THREAD

**Issue by JorgeALeitao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6840]
Under the section Private channel SharePoint sites
https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels#private-channel-sharepoint-sites

We should add a note stating - that, currently Private channel site management is scoped to PowerShell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels?source=docs#private-channel-sharepoint-sites)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @JorgeALeitao
