### ISSUE TITLE
Formatting errors in the sample manifest.json

### ISSUE THREAD

**Issue by Lee-Myhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6844]
There are several typos/formatting conversion errors, including in parameter names, in the sample manifest.json; also it would be a good chance update to the current schema (https://developer.microsoft.com/en-us/json-schemas/teams/v1.9/MicrosoftTeams.schema.json).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611ed1ac-09a9-3491-7fa8-d282b4558fbe
* Version Independent ID: b5a1dba5-beab-7188-fe18-0a045814dde0
* Content: [Create a Teams 'Intranet Portal app' from a SharePoint Online site or page - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-standalone-static-tabs-using-spo-sites)
* Content Source: [Teams/teams-standalone-static-tabs-using-spo-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-standalone-static-tabs-using-spo-sites.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
