### ISSUE TITLE
5 digit extension is incorrect

### ISSUE THREAD

**Issue by shanekennedy-microsoft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6845]
https://docs.microsoft.com/en-us/microsoftteams/what-are-dial-plans#sample-normalization-rules

the regex number pattern in the table on this doc is incorrect under the sample normalization rules. the second rule "5digitExtension"

shows ^5(\d{4})$ and should display -

^(\d{5})$

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
