### ISSUE TITLE
Abbreviations used are unknown

### ISSUE THREAD

**Issue by saurabhkumarrao2000** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6849]
"Note

The current limit for the number of people who can chat and call in to a meeting is 300 in WW and 250 in GCC, GCC High, and DoD."

IN THIS STATEMENT WHAT DOES 'WW', 'GCC', 'GCC High' and 'DoD' STANDS FOR ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bf705c2-1f24-bdb5-e712-e8408b941aca
* Version Independent ID: ddedd7e0-7d85-06e0-7f20-8b83b3dccec7
* Content: [View-only meeting experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/view-only-meeting-experience)
* Content Source: [Teams/view-only-meeting-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/view-only-meeting-experience.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by RAJU2529** [comment]
@saurabhkumarrao2000 . I will add abbreviations today

**Comment by RAJU2529** [comment]
@e0i  @nam31, please look into this PR #6861.
