### ISSUE TITLE
Teams update process issues.

### ISSUE THREAD

**Issue by pvickers-TOA** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6850]
[Enter feedback here]
Thanks for describing the Teams update process. For my users, it's fundamentally flawed.
Users are expected to sign out whenever they aren't using their devices, for security reasons. When they are signed in, they are using Teams because they are meeting people who are working remotely. So Teams never has any idle time when the user is logged in.
If they try to download and install the update themselves, as they aren't elevated users the .exe won't run because guess what, our security policy doesn't allow users to run random executables they've downloaded to their Downloads folder - and they don't get a choice of where to save it. If I come along and run the update as the administrator whilst they are logged on, it solves the problem for them, but guess what, it doesn't update the Teams Machine-wide Installer, so next time they or someone else logs in, the old version is re-installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6da28da-eb7b-d3ae-4c2f-8f87803b1830
* Version Independent ID: 8c42d7a2-80c6-86dd-347a-ed6d8d909c41
* Content: [Teams updates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-client-update)
* Content Source: [Teams/teams-client-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-client-update.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
@pvickers-TOA - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.
