### ISSUE TITLE
Page does not mention that remote organisation needs to be in TeamsOnly mode to receive messages in Teams client

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6851]
We have experienced a number of situations where external organisations complain that they are not receiving federated messages via their Teams clients from us, and it has turned out that while our Teams Upgrade setting is set to 'TeamsOnly', they are in Island or another Teams mode that does not support receiving those messages.

The article makes it clear how TeamsOnly mode will affect incoming messages, but it might help if the article made it very clear that for outgoing messages, if the receiving organisation doesn't want their messages in Skype for Business Online but Teams, they must *also* be in TeamsOnly mode.

Many thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external access (federation) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
