### ISSUE TITLE
What's new in Microsoft Teams: version numbers and other relevant details are missing for most platforms

### ISSUE THREAD

**Issue by grahamperrin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6855]
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6421#issuecomment-755633949 @earthsound wrote: 

> The [most recent support article about what's new in Teams](https://support.microsoft.com/en-us/office/what-s-new-in-microsoft-teams-d7092a6d-c896-424c-b362-a472d5f105de) doesn't have version numbers for Desktop/Web, iOS, or Android but does for Desk phones and Teams Rooms on Android.

True: 

1. https://support.microsoft.com/en-us/office/what-s-new-in-microsoft-teams-d7092a6d-c896-424c-b362-a472d5f105de#PickTab=Desktop_and_web
2. https://support.microsoft.com/en-us/office/what-s-new-in-microsoft-teams-d7092a6d-c896-424c-b362-a472d5f105de#PickTab=iOS
3. https://support.microsoft.com/en-us/office/what-s-new-in-microsoft-teams-d7092a6d-c896-424c-b362-a472d5f105de#PickTab=Android

The requirement to know versions is not esoteric. 

I am, for example, troubleshooting a customer problem that was reported yesterday for a new user of desktop version `1.3.00.21759` (64-bit). 

I need _release notes_ to include (at least) fixes between `1.3.00.21759` and `1.4.00.4167`, which was installed on 2020-03-04. Knowing whether there was a fix for what's reported by the customer will help me to decide whether – beyond an update – additional investigation will be required. I don't want to waste my time, or the customer's time. 

I am, additionally, puzzled by the new feature (without a version number) that became available  on 2020-03-05 because explicit checks for updates find nothing more recent than 2020-03-04.

**Comment by grahamperrin** [comment]
> need release notes

Misleading page titles don't help – #6856 #6857

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @grahamperrin, thank you for your feedback.

I don't have permissions to edit support.microsoft.com, only docs.microsoft.com articles. I'll pass your feedback to the product team, but I'm sure they are aware of this. I personally sent them similar requests.

About #6856 #6857, you can see that I'm applying and update to change the titles.

Thank you again!
