### ISSUE TITLE
HTML title 'Release notes for Microsoft Teams - Microsoft Teams' is misleading

### ISSUE THREAD

**Issue by grahamperrin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6856]
The page is: 

* for _Microsoft Teams admin features_
* **not** for _Microsoft Teams_

![image](https://user-images.githubusercontent.com/192271/111029134-dd1e3200-83f2-11eb-8c68-84c9624d8e2d.png)

Please make the title of the page meaningful. Thank you. 

#6857 is similarly problematic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5eedcae-036a-4e99-e47f-9e2503b667b2
* Version Independent ID: 3914f6ac-352c-8654-0d84-77bc066a734c
* Content: [Release notes for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/release-notes/release-notes)
* Content Source: [Teams/release-notes/release-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/release-notes/release-notes.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by grahamperrin** [comment]
Many thanks, and please note that #6857 is for a different document. 

Maybe some confusion as a result of the current titles, for both documents, lacking distinction.
