### ISSUE TITLE
HTML title 'Release notes - Microsoft Teams' is misleading

### ISSUE THREAD

**Issue by grahamperrin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6857]
The page is: 

* for _Microsoft Teams Rooms_, which I never heard of
* **not** for _Microsoft Teams_

![image](https://user-images.githubusercontent.com/192271/111029215-63d30f00-83f3-11eb-8732-270b7681fade.png)

Please make the title of the page meaningful. Thank you. 

#6856 is similarly problematic. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1365f9b8-001c-daa7-592e-d88b9bb3a10e
* Version Independent ID: ffba1b4d-1f19-4dac-0b55-053d98fe26b7
* Content: [Release notes - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-release-note)
* Content Source: [Teams/rooms/rooms-release-note.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-release-note.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Duplicate

**Comment by grahamperrin** [comment]
Please, a duplicate of what? 

Note that #6856 is for a different document.
