### ISSUE TITLE
Please do not mix non-reverse chronological order with reverse chronological order

### ISSUE THREAD

**Issue by grahamperrin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6859]
Disorder causes disorientation. 

For example, reading from top to bottom (normal order): 

1. 15th February
2. 16th February
3. 17th February
4. 8th February
5. …

Please be consistent. 

Either reverse, or do not reverse. 

This is particularly important from the point of view of British and other readers, to whom `2/1/2021` means 2nd of January. 

![Screen Shot 2021-03-13 at 12 17 12-fullpage](https://user-images.githubusercontent.com/192271/111029780-6be07e00-83f6-11eb-9696-dd113d53cddf.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3081f70c-d927-ce5d-d957-ca7ba7e07a55
* Version Independent ID: 17704162-7ff9-015c-30a1-1cbc078f0782
* Content: [Microsoft Teams content updates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-updates)
* Content Source: [Teams/teams-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-updates.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by RAJU2529** [comment]
@grahamperrin  @SerdarSoysal . I am going to edit this article  and I make the entered features as alphabetical order. 
I will do it before today night.

**Comment by RAJU2529** [comment]
@e0i @nam31, i have completed 1/4th of the article and i  want to save it and then I want to continue afterwards. How i do that, please help me

**Comment by grahamperrin** [comment]
https://docs.microsoft.com/en-us/microsoftteams/teams-updates is still a mixture of reverse and non-reverse. 

Please, was my report misunderstood?
