### ISSUE TITLE
PowerShell examples

### ISSUE THREAD

**Issue by VladimirGluten47** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6862]
Under the "Want to use Windows PowerShell" heading, it would be helpful to include PowerShell examples for updating the conferencing bridge for an individual user, and for all Audio Conferencing enabled users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dc173c-0c98-1b94-a2f7-0a34781c985a
* Version Independent ID: a1c44ccb-67f3-f98e-6569-f938e88ddc63
* Content: [Set the phone numbers included on invites - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-the-phone-numbers-included-on-invites-in-teams)
* Content Source: [Teams/set-the-phone-numbers-included-on-invites-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-the-phone-numbers-included-on-invites-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @VladimirGluten47, thank you for your feedback and help us to improve docs.microsoft.com.

In the following article, which you can also find in the related topics section, you can find some good examples:
[Change the phone numbers on your Audio Conferencing bridge](https://docs.microsoft.com/microsoftteams/change-the-phone-numbers-on-your-audio-conferencing-bridge)
