### ISSUE TITLE
error on document

### ISSUE THREAD

**Issue by Elgwada01** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6864]
There is an error there. The media bypass settings are inversed on the picture. the first should be set to false and the other to true.
<img width="490" alt="Media bypass" src="https://user-images.githubusercontent.com/37817098/111233607-3e0d5c00-85e5-11eb-9e78-e7f4cd67f243.PNG">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10b198f4-9576-a14d-4359-1e8cc0319cda
* Version Independent ID: ba7c3252-21d4-9be1-2a84-de2d51646f7b
* Content: [Plan for media bypass with Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan-media-bypass)
* Content Source: [Teams/direct-routing-plan-media-bypass.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan-media-bypass.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
