### ISSUE TITLE
Can we Pair SBC using Microsoft Graph API

### ISSUE THREAD

**Issue by Sa3d94** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6867]

**Comment by Sa3d94** [comment]
https://answers.microsoft.com/en-us/msteams/forum/msteams_tfb-msteams_topother/using-the-token-generated-by-aad-using-msaljs-with/8e2eac58-a8a1-462f-8499-6f1deea76fcf?tm=1615729456970&auth=1&page=2

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
