### ISSUE TITLE
Update pre-requisites for agents in call queues, receiving calls.

### ISSUE THREAD

**Issue by devops-leyeoyelami** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6868]
Under pre-requisites for agents receiving calls.
The requirements are not very clear. 
Please include the following, any agent or agent within a group that is added to a call-queue, needs to have a Phone system/business voices/enterprise voice license applied to their account before Enterprise Voice can be enabled. If they do not have a license applied to their account, they will not be able to receive calls or be able to have Enterprise Voice online enabled on their account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62fca5a0-5e22-578c-98c8-6b331ae1017f
* Version Independent ID: e1307146-d481-d39c-6227-4c001e044eb1
* Content: [Plan for Teams auto attendants and call queues - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/plan-auto-attendant-call-queue#prerequisites)
* Content Source: [Teams/plan-auto-attendant-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-auto-attendant-call-queue.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@devops-leyeoyelami Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@devops-leyeoyelami thank you for reaching out and helping improve MS Docs. I see the article was recently updated and mentions some of what you suggested. Please have another look and let me know if you think anything else should be added.
