### ISSUE TITLE
Corrections with SBC Names in Multi-Tenant Failover section

### ISSUE THREAD

**Issue by thecathcart** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6869]
The the last section, regarding multi-tenant failover, the following naming conventions are given that do not match the article above:

customer1.sbc1.contoso.com
customer1.sbc2.contoso.com

To match the naming convention in the rest of the article, these could read:

customer1-sbc1.customers.contoso.com
customer1-sbc2.customers.contoso.com

Also the section has a type and currently says "muti-tenant" instead of "Multi-tenant"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure Session Border Controller - Multiple tenants - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@thecathcart Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by RAJU2529** [comment]
@thecathcart . Thanks for pointing out. I wille fix these today
