### ISSUE TITLE
If a Teams meeting recording fails to successfully upload to OneDrive/SharePoint

### ISSUE THREAD

**Issue by sara-barbosa** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6870]
Team, could you please add a note to this article: https://docs.microsoft.com/en-us/microsoftteams/tmr-meeting-recording-change, regarding how we are handling upload failures? 

Suggestion:

```
Upload failure handling
If a Teams meeting recording fails to successfully upload to OneDrive/SharePoint, the recording will instead be temporarily saved to Azure Media Services (AMS). Once stored in AMS, no retry attempts are made to automatically upload the recording to OneDrive/SharePoint or Stream.

Meeting recordings stored in AMS are available for 21 days before being automatically deleted. Users can download the video from AMS if they need to keep a copy.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8935e913-806f-a92c-d09e-e67df4ffd1b4
* Version Independent ID: c7a41cde-66dd-d7cd-1316-42d20ed4841a
* Content: [Use OneDrive for Business and SharePoint for meeting recordings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/tmr-meeting-recording-change?source=docs)
* Content Source: [Teams/tmr-meeting-recording-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tmr-meeting-recording-change.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@sara-barbosa Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sara-barbosa** [comment]
Thanks. :)
