### ISSUE TITLE
Spelling issue

### ISSUE THREAD

**Issue by digitalmess031** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6871]
Spelling issue

a call part policy to

Should be
a call park policy to

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e03ef3d-81d8-c98f-8427-fe7c008ea30f
* Version Independent ID: 17af3418-b94d-f233-60c0-778b2e8dc02b
* Content: [Call park and retrieve in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/call-park-and-retrieve)
* Content Source: [Teams/call-park-and-retrieve.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/call-park-and-retrieve.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@digitalmess031 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
