### ISSUE TITLE
Audio Conferencing Number Availability in Indonesia

### ISSUE THREAD

**Issue by RyanBHernandez** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6874]
Hello Team!

I'm looking for more details on the **phone numbers automatically assigned for Audio Conferencing**

https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-indonesia

1.  Why is this not available? 
2. Would it be available in the future?
3. Do we have an ETA?
4. How do we make it available?  Will it be available thru a local partner? 

Thanks!
~Ryan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b64d6227-5da0-7567-13e9-f83a5755edaf
* Version Independent ID: 26a04052-3345-66fc-6451-842940011ac9
* Content: [Availability in Indonesia - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-indonesia)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-indonesia.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-indonesia.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
