### ISSUE TITLE
Incorrect license requirement?

### ISSUE THREAD

**Issue by steven-de-bruyne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6875]
In the first paragraph it is stated that a **Microsoft 365 E3** license is required for retention policies in Microsoft Teams:
> The minimum licensing requirement for retention policies for Teams is **Microsoft 365 E3**. To learn more about licensing, see Microsoft Teams service description.

However, I found the following statement in the article [Microsoft 365 licensing guidance for security & compliance](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service-9):
> Microsoft 365 E5/A5/G5/E3/A3 and **Office 365** E5/A5/G5/**E3**/A3 provide the rights for a user to benefit from a Teams retention policy.

To me, it looks like this should be **Office 365 E3** instead of Microsoft 365 E3. If not, it is very confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f55c52a5-5841-b9c9-1607-2013dc3f2e20
* Version Independent ID: 16d93458-5e01-646f-dac5-31306cc7f3fb
* Content: [Manage retention policies for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/retention-policies)
* Content Source: [Teams/retention-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/retention-policies.md)
* Service: **msteams**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by scanum** [comment]
@steven-de-bruyne Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@steven-de-bruyne thank you for reaching out and helping improve MS Docs. @cabailey please can you confirm if the article needs to be changed or if it stays as is?

**Comment by cabailey** [comment]
Yes, I'll take care of this. The authoritative source for this licensing is of course, the quoted "Microsoft 365 licensing guidance for security & compliance".  I'll fix the "minimum" statement and add a link so people can find the current licensing options.

**Comment by cabailey** [comment]
Updated now, closing.  Thanks for flagging this!
