### ISSUE TITLE
confusingly worded, some inconsistencies

### ISSUE THREAD

**Issue by DanStevensonMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6876]
Is view-only disabled or enabled? The docs say it is default OFF, enable via PowerShell. Yet the docs also say the view-only experience is "disabled by default for any organizer who has E3/E5/A3/A5 SKU". So is it thus enabled by default for those with an E1 or F1/F3 license?

The docs have a link to adv comms SKU docs, but there's no specific requirement called out around that SKU. This is standard for E3 and above, right?

There are several confusing mentions of lobby bypass and a few different overlapping lists of pre-reqs to join. I'm a native English speaker with professional writing experience, and it took me 10 minutes to parse. Would be great to take an edit pass / clean up the lists and requirements a bit. There are also lots of jargony or inconsistently used terms e.g. a list of licensing plans referred to as SKUs, odd MS-internal abbreviations for clouds like WW and GCC, the term "Overflow Room" used in some parts of the doc but not other parts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bf705c2-1f24-bdb5-e712-e8408b941aca
* Version Independent ID: ddedd7e0-7d85-06e0-7f20-8b83b3dccec7
* Content: [View-only meeting experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/view-only-meeting-experience?source=docs)
* Content Source: [Teams/view-only-meeting-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/view-only-meeting-experience.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@DanStevensonMSFT Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by cichur** [comment]
Hi @DanStevensonMSFT 
We've just published an update to the article that answers your questions. Thank you. Cindy
