### ISSUE TITLE
Update to Page

### ISSUE THREAD

**Issue by dgrider21** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6877]
Could the following section be updated with a description of the commands available under *1?
https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-common-questions#what-in-meeting-dial-pad-commands-are-supported
On the page today- *1 (Plays the descriptions of dial-pad commands that are available)
Additions- These are Lobby and Entry notifications 
*21
*22
*2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad892c60-f7e4-0790-66f7-219d28f44ee6
* Version Independent ID: 36e86cca-c5a3-eb4d-477e-1fb7b0b5d7f1
* Content: [Audio Conferencing common questions - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-common-questions)
* Content Source: [Teams/audio-conferencing-common-questions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-common-questions.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@dgrider21 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@dgrider21 thank you for reaching out and helping improve MS Docs. I see the article is reading correctly under *1 as stipulated. Just for clarity are you suggesting adding the following *21 *22 and *2 under that section with this (lobby and entry notifications) for each.

**Comment by dgrider21** [comment]
Yes that is request.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
