### ISSUE TITLE
When admin pre-install apps using the app setup policy, they get installed only after users logs into teams app

### ISSUE THREAD

**Issue by chronustdd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6878]
[Enter feedback here]
When admin pre-install apps using the app setup policy, they get installed only after users log into Teams. Users who have already logged into Teams, have to log out and log in again for the app to get installed. Is this expected behavior?

If yes, I want to know how often users get automatically logout from Teams. And what is the maximum time users stay logged in? And is there any option for users to stay logged in all the time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f91604a-35b0-dfbb-55b2-b601cb0841b0
* Version Independent ID: 84bcd0d7-b4ed-f13e-c84b-2ec6a7661ae9
* Content: [Manage app setup policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-app-setup-policies)
* Content Source: [Teams/teams-app-setup-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-setup-policies.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by chronustdd** [comment]
Hii,

I got the reply to my service ticket ([](https://docs.microsoft.com/en-us/answers/questions/320074/when-tenant-admin-pre-install-teams-app-using-the.html)).

They suggested _"The next best thing for your scenario is to inform users to manually sign out and re-sign in Teams client."_

It would be great if we add this point to the docs.
