### ISSUE TITLE
Improvement needed 

### ISSUE THREAD

**Issue by osvalver** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6879]
Hi Team, 

Im a Customer Success Account Manager and my customer has recently gone over the porting process. Customer would like to see more clear instructions into how to put in the request. A step by step of the information that has to be put in the Teams Admin Center with screenshots. Instead of Common mistakes to watch out for. 

Also a clarification of what each status means in teams admin center. From autoprocessing to manual review. 

Any questions, please let me know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a17293e0-4c49-0e97-d5da-b48322f10928
* Version Independent ID: c38c0726-5dec-d374-6948-2188d43025ef
* Content: [What's a port order? - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/phone-number-calling-plans/port-order-overview)
* Content Source: [Teams/phone-number-calling-plans/port-order-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phone-number-calling-plans/port-order-overview.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
