### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by mesdjian** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6880]
Hi,
Within this location, https://docs.microsoft.com/microsoftteams/meeting-policies-in-teams#allow-transcription, the "View live transcription in a Teams meeting" link is going to a page that does not exist.

Please fix.

Ara

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams#allow-transcription)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@mesdjian Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by RAJU2529** [comment]
Dead link is confirmed.

**Comment by mesdjian** [comment]
Please let me know when it has been fixed.

Thanks,
Ara

**Comment by RAJU2529** [comment]
@mesdjian . I already added new link to this article, review will be forwarded to editors and to authors,  link will be available to public after the content merging

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
