### ISSUE TITLE
MTR join Webex meeting Note

### ISSUE THREAD

**Issue by howardzhangmsft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6885]
Please add below note to the bottom of the article 

ThirdParty join is not supported by WebEx for the Personal Conference option because of encryption. 
Customers will have to use the WebEx Meetings Pro option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c62081e-2421-80b9-8ba9-aaf8fd55e432
* Version Independent ID: 5df3c5e5-978f-cfa7-9e5c-3cd7f65fa8ff
* Content: [Enable Teams Rooms devices to join third-party meetings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/third-party-join)
* Content Source: [Teams/rooms/third-party-join.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/third-party-join.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by RAJU2529** [comment]
@howardzhangmsft . Thanks for pointout. i  sent support site of  isco webex , and i conformed , what you said is correct. So thanks for found out.

**Comment by lindspea** [comment]
@dstrome

**Comment by scanum** [comment]
@howardzhangmsft Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
