### ISSUE TITLE
SessionOption disappeared with New-CsOnlineSession

### ISSUE THREAD

**Issue by Lerritier** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6894]
Thanks for this login procedure.

Would it be possible to have a little more information on the options that disappeared ?
I mean with the New-CsOnlineSession we were able to provide SessionOption and others parameters.
How can we login with the v2.0 module if we need to use some SessionOption and/or OverrideAdminDomain ?

Thanks a lot in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09f27c0e-15db-920c-dee9-824bcab166cc
* Version Independent ID: c0bd47ae-da8c-b466-4e05-5c97b055ee9b
* Content: [Move from Skype for Business Online Connector to the Teams PowerShell module - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-move-from-sfbo)
* Content Source: [Teams/teams-powershell-move-from-sfbo.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-move-from-sfbo.md)
* Service: **msteams**
* GitHub Login: @pupara
* Microsoft Alias: **pupara**

**Comment by scanum** [comment]
@Lerritier  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Lerritier thank you for reaching out and helping improve MS Docs. I see the article was recently updated. Please have a look and let me know if you have further questions.

**Comment by Lerritier** [comment]
Hello,
I am sorry but I don't understand. Are the modifications in the "Recommended content" ?

How can we manage the lost options ? In v1.1.6 I used the following to connect
![image](https://user-images.githubusercontent.com/77000705/113864782-99c5a200-97ab-11eb-87ef-655c18bd68e7.png)

Thanks a lot in advance

**Comment by lindspea** [comment]
@pupara please could you assist here?

**Comment by lindspea** [comment]
@Lerritier I see the article was updated recently. Please have a look and let me know if you're still having this issue.
