### ISSUE TITLE
The attribute "GenerateRingingWhileLocatingUser" doesn't work

### ISSUE THREAD

**Issue by vincentkurmi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6901]
Hello, 

We receive an error when we try to set the attribute "GenerateRingingWhileLocatingUser". 

`New-CsOnlinePSTNGateway -FQDN sbcvlt.blabla.onmicrosoft.com -GenerateRingingWhileLocatingUser $true

A parameter cannot be found that matches parameter name 'GenerateRingingWhileLocatingUser'.
    + CategoryInfo          : InvalidArgument: (:) [New-CsOnlinePSTNGateway], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Rtc.Management.Internal.NewOnlinePSTNGatewayCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com`

Could you help us please?

Regards, 

Vincent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a3a97bf-5eff-61a0-9bb0-f69f712fa834
* Version Independent ID: 0fbf3b06-383b-54a3-ca13-92208ed9b4bc
* Content: [Set up the Ringback bot for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-ringback-bot)
* Content Source: [Teams/direct-routing-ringback-bot.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-ringback-bot.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by smohk1** [comment]
I opened a ticket on this and the official answer I got form Microshaft was 

As per the concern, we would like to inform you that this functionality doesn't exist anymore and  we apologize.

Thank you for choosing Microsoft.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
