### ISSUE TITLE
Meeting expiration section has major problems

### ISSUE THREAD

**Issue by benjaminwchau** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6908]
There are a few problems with this list:
1. There is no such thing as a "Regular" meeting. Would be better just to call it a Scheduled Meeting;
2. When you schedule a meeting, you can't create one with no end time. 
3. Recurring meeting still have start and end TIME for each occurrence;
4. Recurring meeting can have no end "DATE"
5. On the extends of expiration, "each time you start" means you actually instantiate the meeting?
6. What is the meaning of "update a meeting" add/remove participants? Change meeting option? Change title/description?

There should be only three categories.
1. Scheduled meeting
2. Recurring meeting with no end date
3. Recurring meeting with end date

"Start time" on expiration should be anyone instantiate the meeting, i.e. the meeting is "STARTED"

I hope someone can clarify it if my understanding is wrong. But so far no one can create a "Regular with no end time" meeting.

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@benjaminwchau Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@benjaminwchau thank you for reaching out. I see the article was updated yesterday with a few changes. I'm not seeing the instance of "update a meeting". Please can you provide clarity there.

**Comment by benjaminwchau** [comment]
I work for Microsoft, my office email is also bchau.
Do you want to talk about it? This is depressing to see one of our major document has so many problems. The relay section is still not changed at all. What is worse than giving customer bad information and doing in writing? Even worse, on the internet?

Regards,
Ben.

________________________________

**Comment by lindspea** [comment]
@benjaminwchau thank you. The team is continuously working to improve the Docs and we value your input.  I'm working through the article to see your recommendations for changing content and to see if anything has been changed so far to provide more clarity for users. The article was updated a few days ago. Please can you have a look again when you get a chance and let me know what you think and where more clarity can be provided.

**Comment by benjaminwchau** [comment]
A meeting URL will never stop working. The expiry only relates to any PSTN dial-in numbers and/or underlying meeting policies and settings.
This is a nice touch, not perfect, but at least pointing the right direction.

What is "Regular with no end time"? If you are a Teams user, I challenge you to create a "Regular with no end time". What is regular, what is no end time?

Regular means what? Single occurrence meeting? Contrast to Recurring meeting?

Regards
Ben.

________________________________

**Comment by lindspea** [comment]
@benjaminwchau Regular and recurring meetings with NO end time expire 60 days after the start time. Regular meetings with end time expire 60 days after the end time.  Recurring meetings with end time expire 60 days starting from the last occurrence. Hope this provides more clarity. Please let me know if you require further assistance or perhaps I should add this in a note in the article?  Let me know what you think.

**Comment by benjaminwchau** [comment]
The bottom line is there is no such thing as "Regular Meeting"! What is a Regular Meeting? Just a normal Teams Meeting created in Outlook or In Teams?

Try it yourself, can you create a meeting with no end time?

Why send me any email when you don't expect the return to get back? All these Noreply.github.com?

Regards,
Ben.

________________________________

**Comment by lindspea** [comment]
@SerdarSoysal please can you help provide clarity. Thanks so much.

**Comment by benjaminwchau** [comment]
[cid:de0a3356-45c4-4321-ab4f-7a806eb5106e]

  1.  The top note is a good touch. My suggestion should be "A meeting URL will never stop working. The expiry only related to any PSTN dial-in Number, CVI joining, and/or underlying meeting policies, settings, files uploaded to the meeting.
  2.  On Regular Meeting Type
     *   Can someone clarify what on Regular Meeting? A simple meeting? There is no definition of "Regular Meeting" within Teams.
     *   I can see the document have Regular with no end time and with end time. How can any (Regular or Recurring) meeting have no end time? The recurring can have no end time, but each occurence have to have Start time and End time.
  3.  I can only see the meeting type has
     *   Meet Now
     *   Single occurrence Meeting
     *   Recurring meeting with no end time
     *   Recurring meeting with end time

Please include my Microsoft email address too. And I am more than happy to join a call to discuss the detail. This is a very confusing section in our communication with the customer.

Regards
Ben.

________________________________

**Comment by lindspea** [comment]
@benjaminwchau thanks for the response. I'm discussing with the team. Regarding the email addresses, all messages/comments here go directly to your email address by default, as well as anyone else who comments here, so the comments will appear here as well as in you Inbox.

**Comment by scanum** [comment]
@benjaminwchau Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
