### ISSUE TITLE
How can I tell who is NOT using Teams?

### ISSUE THREAD

**Issue by cfizz34** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6912]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd6683c0-a685-d279-538f-f0df86113911
* Version Independent ID: efe3afd1-f9c2-9db4-509f-8caaad6f0be0
* Content: [Monitor usage and feedback in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-started-with-teams-monitor-usage-and-feedback)
* Content Source: [Teams/get-started-with-teams-monitor-usage-and-feedback.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-started-with-teams-monitor-usage-and-feedback.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@cfizz34 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
