### ISSUE TITLE
Questioning the Section titled "Configuring Group Policy"

### ISSUE THREAD

**Issue by snoebel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#692]
The section states: HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon AdminAutoLogon = (dword) 1 
Are you sure this isn't supposed to be: HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon AdminAutoLogon = STRING Value 1 ?  ie String and not DWord?

I ask because when I visited the registery on the Surface Pro that is docked in my Logitech Smartdoc, I see a Reg entry of AutoAdminLogon Type=REG_SZ.  i.e. Type does not equal REG_DWORD. Thus my question here. Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68cba21-b43e-ed44-449c-da752f5a0f53
* Version Independent ID: 5a2a2c5e-ad0e-833d-6ab7-74ed26f63d4a
* Content: [Skype Room Systems v2 maintenance and operations](https://docs.microsoft.com/en-us/skypeforbusiness/manage/skype-room-systems-v2/room-systems-v2-operations)
* Content Source: [Skype/SfbServer/manage/skype-room-systems-v2/room-systems-v2-operations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/skype-room-systems-v2/room-systems-v2-operations.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by Travis-Snoozy** [comment]
That should definitely be a REG_SZ.

**Comment by Travis-Snoozy** [comment]
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/712
