### ISSUE TITLE
Inline translation functionality missing from what users can / cannot do table

### ISSUE THREAD

**Issue by TristanBa** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6922]
Please add to the table of things users can do the translate inline messages functionality

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f080a5c-4268-1db4-566f-f1edc27920b5
* Version Independent ID: ac556a92-58af-3e05-f53b-0fc00afc96c0
* Content: [Use guest access and external access to collaborate with people outside your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/communicate-with-users-from-other-organizations)
* Content Source: [Teams/communicate-with-users-from-other-organizations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/communicate-with-users-from-other-organizations.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@TristanBa thank you for reaching out and helping improve MS Docs. Just for clarity should that go under the "things your users can do" table and is the functionality available for external access users and guests?

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
