### ISSUE TITLE
Documentation modification - listed reg key does not seem to be functional

### ISSUE THREAD

**Issue by DanPaquetteKK** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6929]
In the section 'How to restrict sign in on desktop devices,' there are 3 registry keys listed:

Computer\HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Cloud\Office\16.0\Teams Computer\HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Office\16.0\Teams Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\Teams

In implementing this, we've come to the conclusion that the 3rd key does not, in fact, control any particular behavior of the software.  That it seems to not be functioning at all.  The first two keys do, indeed, control the sign in behavior.

I can see why one would want to restrict the locality of this key to the \Policies\ hive to enforce sign in restrictions.  But the documentation appears to incorrectly include the HKCU\Software\Microsoft... hive which did not work for us.

Thanks!
-Dan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf54bf5d-1748-46bf-a503-5e978f56126c
* Version Independent ID: 5976a1df-52e9-eb19-fd41-c7b04fce74f8
* Content: [Sign in to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sign-in-teams#feedback)
* Content Source: [Teams/sign-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sign-in-teams.md)
* Service: **msteams**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
