### ISSUE TITLE
New meeting attendance functionality

### ISSUE THREAD

**Issue by nickp85** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6931]
There seems to be new functionality recently where the meeting attendance report is automatically added to the meeting chat at the conclusion of the meeting and also if viewing the meeting in the Calendar tab the report is shown there too. This documentation appears to be out of date with the most recent functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a8b1087-ae40-6813-16bc-a69c90e50d19
* Version Independent ID: b808e843-80d8-4a96-c6ed-e8175968eb73
* Content: [Microsoft Teams meeting attendance report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/meeting-attendance-report)
* Content Source: [Teams/teams-analytics-and-reports/meeting-attendance-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/meeting-attendance-report.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@nickp85 thank you for pointing this out. I'm working on updating the article. Just a quick question. Is the report still downloadable according to the article. So just a note adding that the report is shown when in meeting, on chat, etc?

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
