### ISSUE TITLE
document outbound calls

### ISSUE THREAD

**Issue by lazedo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6933]
[Enter feedback here]

would like to get details of outbound calls (initiated by teams client) in general and particularly of the Contact header.
We're trying to identify the user who made the call (if possible)

example of received Contact
```
CONTACT:  <sip:api-du-b-euwe.pstnhub.microsoft.com:443;x-i=fe6e8bf9-5260-4121-abd7-0ca70f38d144;x-c=59c924d8e22f5c65850429ef77c8eea4/d/8/c036ff49311e4abb825beae9ba9f87b7>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8acd94b0-411b-357f-2d22-668fd3be3e5d
* Version Independent ID: 4b16f706-3809-c9b2-4b34-307d76988502
* Content: [Phone System Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-protocols-sip)
* Content Source: [Teams/direct-routing-protocols-sip.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-protocols-sip.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
