### ISSUE TITLE
"Users that do not belong to the tenant"

### ISSUE THREAD

**Issue by bec064** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6936]
Hi, https://docs.microsoft.com/en-us/microsoftteams/teams-security-guide#participant-types section 2.

"2. Users that do not belong to the tenant. These users do not have credentials in Azure AD for the tenant. a. Federated Users - Federated users have valid credentials with federated partners and are therefore treated as authenticated by Teams, but are still Anonymous to the meeting organizer tenant."

This is misleading/unclear as Anonymous users differs from Federated users when it comes to the meeting lobby settings. For example. 'People in my organization and trusted organizations' puts Anonymous users in the lobby. But if Federated users "are still Anonymous" (as described above) this lobby option would also put Federated users in the lobby together with the Anonymous users. Hence the meeting lobby option would be obsolete.

Another example is "Anonymous users can join a meeting". If that would be off, federated users would not be able to join meetings (according to the above).

Please update and make it more understandable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33613b2d-d607-ec47-1254-ae540d07ad59
* Version Independent ID: aba728f0-0d3c-73fd-c7fe-68e69b6a753f
* Content: [Security guide for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-security-guide#participant-types)
* Content Source: [Teams/teams-security-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-security-guide.md)
* Service: **msteams**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@bec064  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@bec064 thank you for pointing this out and helping improve MS Docs. Could you perhaps suggest the changes you would recommend to the wording and I'll look into it.

**Comment by bec064** [comment]
> @bec064 thank you for pointing this out and helping improve MS Docs. Could you perhaps suggest the changes you would recommend to the wording and I'll look into it.

Hello, no worries. It's really not the wording I'm concerned about but rather the fact that the article says that "federated users are treated as anonymous users" as that can't be the case, referring to my initial post. So please look into rephrasing that part and also verify with an engineer so there's no misunderstanding going on here. Thanks!

**Comment by lindspea** [comment]
@MSFTTracyP please can you help here.

**Comment by bec064** [comment]
> @MSFTTracyP please can you help here.

Any update to share?

**Comment by MSFTTracyP** [comment]
@bec064 and @lindspea Thanks for pinging me. Federated users _are not_ the same as Anonymous. A federated trust relationship exists. I'm looking in to this now, to determine the behaviour fed users will see. Thanks!

**Comment by MSFTTracyP** [comment]
Should be sorted and published within the day. Good catch @bec064. Thank you so much to you and @lindspea!

**Comment by lindspea** [comment]
Thanks @MSFTTracyP @bec064 or @scanum please can you close. I'm unable to.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
