### ISSUE TITLE
"Number of teams" now unlimited

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6938]
Our Teams Engineering CPM announced last week that commercial and GCC had removed the 500,000 limit, and that this is now unlimited in production environments.

However, the documentation still says "Number of teams a Microsoft 365 or Office 365 organization can have" is 500,000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@npherson  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Reeced40

**Comment by Reeced40** [comment]
@SerdarSoysal please can you confirm if the 500,000 limit has been removed and is now unlimited?

**Comment by Reeced40** [comment]
@SerdarSoysal

**Comment by Reeced40** [comment]
@npherson the document was updated to have a footnote added. Thanks again for your help.  @scanum this can be closed thank you.
