### ISSUE TITLE
feature update

### ISSUE THREAD

**Issue by jrummer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6944]
this feature has updated since this page.  the attendance report shows during the meeting, in the chat afterwards and also in the meeting information.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a8b1087-ae40-6813-16bc-a69c90e50d19
* Version Independent ID: b808e843-80d8-4a96-c6ed-e8175968eb73
* Content: [Microsoft Teams meeting attendance report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/meeting-attendance-report)
* Content Source: [Teams/teams-analytics-and-reports/meeting-attendance-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/meeting-attendance-report.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@jrummer  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@jrummer thank you for pointing this out and helping improve MS Docs. I will add that information. Just a quick question - is the downloadable report still available? So this would be an extra note to add to the article that it shows during the meeting and in the chat after, etc...

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
