### ISSUE TITLE
Phone System isn't supported in Teams in Islands mode? 

### ISSUE THREAD

**Issue by HandyAndyOnGitHub** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6947]
Phone System isn't supported in Teams in Islands mode?  I've just successfully deployed another 75 users with Teams Phone System in Islands mode.  You may want to update the documentation :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d53d0cb0-90a6-5932-f78e-7de6fcc4d481
* Version Independent ID: 3d468027-cc37-5199-32ec-819bf62b2caa
* Content: [Understand Microsoft Teams and Skype for Business coexistence and interoperability - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability)
* Content Source: [Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md)
* Service: **msteams**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@HandyAndyOnGitHub  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@HandyAndyOnGitHub thank you for pointing this out and helping improve MS Docs.  Should the information be changed to 'is supported'?

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
