### ISSUE TITLE
Exchange Teams Interact - Footnote 8 is missing

### ISSUE THREAD

**Issue by J-a-k-o-b** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6948]
Hi,
the table "Actions supported" contains a reference to Footnote 8. 
The reference is mentioned in the combination Exchange On-premises &  Create and view meetings in Teams
The Footnote 8 is not listed in the Footnote part, so the information is missing. 

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@J-a-k-o-b Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @J-a-k-o-b Jakob, how are you?
Footnote 8 is there, it's just that it is in the same paragraph as footnote 7, will correct it now.
Thank you!
