### ISSUE TITLE
Requirements clarification - AAD Connect Exchange Hybrid Deployment checkbox

### ISSUE THREAD

**Issue by J-a-k-o-b** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6949]
Hi,
in the requirements section:
https://docs.microsoft.com/de-de/microsoftteams/exchange-teams-interact#requirements-to-create-and-view-meetings-for-mailboxes-hosted-on-premises
is the following requirement listed:

> The checkbox for the Exchange Hybrid Deployment feature in Azure AD Connect is set.

Why do i have to use this checkbox. I would expect a more precise description like: This attributes have to be synced:
https://docs.microsoft.com/en-us/azure/active-directory/hybrid/reference-connect-sync-attributes-synchronized#exchange-online
https://docs.microsoft.com/en-us/azure/active-directory/hybrid/reference-connect-sync-attributes-synchronized#exchange-hybrid-writeback

If other requirements where fulfilled by this checkbox, they should be described separately to allow and detailed consideration in more complex environments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact?source=docs#requirements-to-create-and-view-meetings-for-mailboxes-hosted-on-premises)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@J-a-k-o-b Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @J-a-k-o-b, thank you for your feedback and help us to improve docs.microsoft.com.

I'm applying an update to the article, and It should be live in the next few hours. The following attributes are required and have to be written back to AD DS:
https://docs.microsoft.com/en-us/azure/active-directory/hybrid/reference-connect-sync-attributes-synchronized#exchange-hybrid-writeback

**Comment by J-a-k-o-b** [comment]
Hi @dariomws,
thank you for updating this article. Can you explain the reason why writeback of the attributes is needed.
While msExchBlockedSendersHash etc has no relation to teams meetings in any way, i could imagine that publicDelegates is used somehow for a delegated meeting planning.

**Comment by dariomws** [comment]
Hi @J-a-k-o-b,

My apologies, but I cannot provide that level of analysis and detail.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
