### ISSUE TITLE
distinct level of feauters for F plans and others

### ISSUE THREAD

**Issue by EvgenyArtemyev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#695]
After reading the article fall under impression that there is no differences between plans. AFAIK Microsoft/Office 365 Frontline licensed users can't organize conference or commence desktop sharing etc. It has the same limitation as former SfB plan 1.
If it's so would you update the article accordingly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c59eff85-a7f1-764b-4716-b79d70c18d18
* Version Independent ID: 49ecb4f7-3e80-c81a-32b6-4f3fda8826dd
* Content: [Office 365 licensing for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/office-365-licensing)
* Content Source: [Teams/Office-365-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-licensing.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@EvgenyArtemyev Thank you for this feedback

I will get this over to the Teams team so we can verify and make sure that this document reflects the correct information. Thank you for taking the time to help make the docs better. 

I was able to get this into the backlog for the Teams team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @EvgenyArtemyev Thanks for your comments!
Document intention isn't to specify features in each subscription, but list the ones that enable Teams.

You can see here https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-plan-options that Office 365 Enterprise F1  Includes Skype for Business Online Plan 1.

Hope this information has helped you! Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @EvgenyArtemyev 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
