### ISSUE TITLE
teams meeting for android not showing up

### ISSUE THREAD

**Issue by jwilliams45-aug** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6951]
please specify what build/release date includes teams link in android app. It is not in my app today and the app is up to date according to google play.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Use the Microsoft Teams Meeting add-in in Outlook - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@jwilliams45-aug Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @jwilliams45-aug how are you?
Do you refer to the _Teams join link_ or the _The Teams Meeting button_ shown in the screenshot included in the article?
Thanks for your clarification

**Comment by jwilliams45-aug** [comment]
Yes. I don't have this button. I have a skype meeting button only.

**Comment by get-itips** [comment]
> Yes. I don't have this button. I have a skype meeting button only.

I was able to reproduce that when using an Outlook/Hotmail account. Be sure to be using an Office/Microsoft 365 account.

**Comment by jwilliams45-aug** [comment]
> I was able to reproduce that when using an Outlook/Hotmail account. Be sure to be using an Office/Microsoft 365 account.

I am using O365. the domain is augusta.edu here is a snip from NSLOOKUP to prove it:

`\> set type=mx`
`\> augusta.edu`
`Server:  hitronhub.home`
`Address:  192.168.0.1`
` `
`Non-authoritative answer:`
`augusta.edu     MX preference = 10, mail exchanger = augusta-edu.mail.protection.outlook.com`

**Comment by get-itips** [comment]
@jwilliams45-aug 
If you are using multiple accounts with the Outlook app be sure to select the 365 account by selecting the dropdown under "New event"

![image](https://user-images.githubusercontent.com/36666927/115042554-d7ec5100-9e90-11eb-94ef-b046ab2231c1.png)

in case you still do not see the Teams meeting button I suggest open a support ticket in your tenant, as here we are limited to Documentation changes as if you are running the latest version you should see it.

Hope this information helps you

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
