### ISSUE TITLE
SBA support for Teams to Teams (VoIP) calls?

### ISSUE THREAD

**Issue by ahunkins** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6953]
Can you add a clarification to page to say if Teams to Teams (VoIP) calls are supported by the SBA? Scenario: Internet connection goes down. Can users call each other using Teams without it being a PSTN call? In other words, can an SBA be used to maintain intrasite calling in general, or only those users with Phone System making a hairpin call off the PSTN?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 183fc921-e9b1-cc74-2bcb-26d32b994919
* Version Independent ID: 1765bda3-dd62-76d7-1e2d-9f5496ac9094
* Content: [Direct Routing SBA - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-survivable-branch-appliance)
* Content Source: [Teams/direct-routing-survivable-branch-appliance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-survivable-branch-appliance.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@ahunkins Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @ahunkins, thank you for your feedback.

I think the article is pretty clear that the SBA is to continue making PSTN calls in case of an Internet outage. For example:

"This article describes how to use a Survivable Branch Appliance (SBA) to enable Microsoft Phone System to continue to make and receive Public Switched Telephone Network (PSTN) calls in the case of an outage."

"When the Microsoft Teams client is in offline mode, the following calling-related functionality is available: 

- Making PSTN calls via local SBA/SBC with media flowing through the SBC.

- Receiving PSTN calls via local SBA/SBC with media flowing through the SBC. 

- Hold and Resume of PSTN calls."

**Comment by ahunkins** [comment]
Correct. But I don’t mean PSTN calls. I mean VoIP calls. Forget the PSTN. Does an SBA allow Teams to Teams audio calls between users on the same LAN when the internet connection to O365 goes down?

If the answer is no, then that means a working PSTN connection is needed just to maintain INTERNAL calling during a PSTN outage, correct? Or no?

Think of a hospital. Can Nurse A talk to Doctor B using Teams (with an SBA) in the event of internet failure?

Andrew



Andrew Hunkins
Field Solution Architect | Microsoft Collaboration | CDW
Phone: 847.371.2950<tel:+18473712950> – Central Time Zone

**Comment by dariomws** [comment]
@ahunkins peer-to-peer Teams calls between two Teams desktop clients in the same network are not available in offline mode, only PSTN calls.

**Comment by dariomws** [comment]
Have in mind the following requirement:
"The SBC needs to be configured for Media Bypass to ensure that the Microsoft Teams client in the branch site can have media flowing directly with the SBC"

**Comment by ahunkins** [comment]
Thanks. I think this explanation will improve the documentation.

When customers look at the SBA solution, they are trying to duplicate the survivability of a distributed PBX environment. If a hospital has a PBX and the internet goes down, they can still call each other internally. This is not the case with Teams. If the PSTN is required to do so, then the user experience will be critical. If Nurse A normally calls Doctor B by clicking the phone icon for a peer-to-peer call, what happens when the internet goes down? Does Nurse A somehow have to know to use the drop down to select Doctor B’s DID (or mobile number), or find Doctor B’s DID in his contact card? In fact, the article/documentation could be improved with a description of the UX differences in the event of internet failure / survivability mode.

I would also suggest you heavily emphasize the fact that hard phones are not currently supported for survivability with an SBA. Such a use case is assumed for an old school PBX. Any organization expecting “survivability” from an SBA must understand this point.

Thanks for listening!

Andrew



Andrew Hunkins
Distinguished Field Solution Architect | Microsoft Collaboration | CDW
Phone: 847.371.2950<tel:+18473712950> – Central Time Zone

**Comment by dariomws** [comment]
I'm not sure if I fully understand you and can apply the updates you are suggesting.

Maybe @CarolynRowe you can kindly help here. Thanks!

**Comment by dariomws** [comment]
@ahunkins another important information. There are plans to add peer-to-peer calls support for this scenario.

**Comment by ahunkins** [comment]
Okay. Well, maybe just stating that fact in the documentation is enough.

Make clear hard phones are not (yet) supported. Make clear peer-to-peer calls are not (yet) supported. That should help a perspective customer (who’s knows how a PBX works when the internet goes down) understand what an SBA can and can’t do (today).

Andrew



Andrew Hunkins
Field Solution Architect | Microsoft Collaboration | CDW
Phone: 847.371.2950<tel:+18473712950> – Central Time Zone

**Comment by dariomws** [comment]
@ahunkins to be honest, I'm not convinced to add that.

About desk phones, I think the article clearly states that this feature only works with **Teams Windows desktop** and **Teams macOS desktop**.

About peer-to-peer calls, I think the article clearly states that the only supported scenarios are:

- Making PSTN calls via local SBA/SBC with media flowing through the SBC.

- Receiving PSTN calls via local SBA/SBC with media flowing through the SBC. 

- Hold and Resume PSTN calls.

If we add something not supported, it can lead to list all the unsupported features. Maybe I could be wrong, but that's my thinking on this.

**Comment by ahunkins** [comment]
Roger that. Thank you!!



Andrew Hunkins
Field Solution Architect | Microsoft Collaboration | CDW
Phone: 847.371.2950<tel:+18473712950> – Central Time Zone

**Comment by dariomws** [comment]
Thank you very much for your comprehension. Although we disagreed on this topic, I encourage you to continue contributing to docs.microsoft.com. Any feedback is very valuable for us.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
