### ISSUE TITLE
Provide the "Share to Teams" Application ID

### ISSUE THREAD

**Issue by BSwagger** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6954]
This article suggests that the "share to teams" outlook add-in can be disabled and refers to the disable-app, but does not provide the application ID

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 311beaec-73aa-da96-6793-c8750597b1fa
* Version Independent ID: c730e71d-45e8-d912-85b8-0556daa3a57c
* Content: [Share to Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-outlook-share-teams#enabling-or-disabling-share-to-teams)
* Content Source: [Teams/teams-outlook-share-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-outlook-share-teams.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@BSwagger Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback
