### ISSUE TITLE
PowerShell script error 

### ISSUE THREAD

**Issue by m365protips** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6959]
[
Assign a setup policy to a batch of users - in this section the powershell script which has been displayed does not work. 

$user_ids = Get-Content .\users_ids.txt
New-CsBatchPolicyAssignmentOperation -PolicyType TeamsAppSetupPolicy -PolicyName "HR App Setup Policy" -Identity $users_ids -OperationName "Example 1 batch"

There is a typo on line 1 of this - everywhere else in the script  it uses $users_ids however in line 1 it states $user_ids

This script did not run until this was resolved. 

Furthermore, it does not state in this document what needs to be added into the txt/csv file, nor does it give any examples. 

]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888fe05b-1160-452f-90ba-deb19adb740f
* Version Independent ID: 4091c5e4-7a90-7fe4-2741-16bbb1f297c1
* Content: [Assign policies to your users in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/assign-policies#assign-a-policy-to-individual-users)
* Content Source: [Teams/assign-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-policies.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@m365protips Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
@m365protips thank you for your feedback.

I'm applying an update to fix the example. You can have a look over the following article for more information and examples:
https://docs.microsoft.com/powershell/module/teams/new-csbatchpolicyassignmentoperation

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
