### ISSUE TITLE
Mismatch between articles

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#696]
This page says "The external web FQDN must only resolve to, and be accessible from, the internet." and https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/network-requirements/dns lists that FQDN as being defined in internal DNS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4abd4a50-49e3-80be-bed5-1d052b1dc193
* Version Independent ID: 43c6d5b1-c8ad-a29e-5e04-e336fd498a3b
* Content: [Plan for Mobility for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/mobility)
* Content Source: [Skype/SfbServer/plan-your-deployment/mobility.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/mobility.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by AndreaBarr** [comment]
@TorrenManson Thank you for your feedback.

I want to make sure these get checked and clarified so we don't have conflicting documents. I am sending this to our Teams team so they can investigate and handle it appropriatly. 

I was able to get this into the backlog for the Teams team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by jinlianhanzi** [comment]
Hi Jambirk， sorry to interrupt but I have a strange issue when configurating our Lync server. Our SfB mobile (iOS and Android) end users are seamlessly auto switched when from internal WiFi to external 4G, IM function works pretty well, but they will drop if they were in a conference and never auto reconnected.  
Any suggestion on troubleshooting? Thanks a lot.

**Comment by scanum** [comment]
@jambirk @MicrosoftHeidi Any updates on this issue? Thanks!

**Comment by scanum** [comment]
@jinlianhanzi thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
