### ISSUE TITLE
Issue with the command presented for enabling the mailbox as a room

### ISSUE THREAD

**Issue by cypheredout** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6963]
at this section part 2:  https://docs.microsoft.com/en-us/microsoftteams/rooms/with-exchange-on-premises#enable-the-remote-mailbox-and-set-properties

It says to run: Enable-Mailbox PROJECTRIGEL01@contoso.com -Room

When running with a customer the output from Exchange 2016 we get in return "the users AD account must be logon-disabled for linked,....".  Obviously this will not work with a MTR account.

In the provisioning script provided at the top of the doc:  "Microsoft provides SkypeRoomProvisioningScript.ps1" the code refers to an additional flag that is not in the example in the doc:  -EnableRoomMailboxAccount $true.

Complete code line:

Set-Mailbox $credNewAccount.UserName -Type Room -EnableRoomMailboxAccount $true -RoomMailboxPassword $credNewAccount.Password

Can we have the extra flag "-EnableRoomMailboxAccount $true" validated and added to the doc / update the script as needed please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91cd0219-b3b0-da60-6416-c6b5a67623e3
* Version Independent ID: 983d08b5-4a2c-838a-52eb-821045d2c9df
* Content: [Deploy Microsoft Teams Rooms with Exchange on-premises - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-exchange-on-premises?ranMID=24542&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-NC_nTEgHUJCR2KCfHz9beg&epi=je6NUbpObpQ-NC_nTEgHUJCR2KCfHz9beg&irgwc=1&OCID=AID2000142_aff_7593_1243925&tduid=%28ir__qdsg1r9rwgkfqyvqkk0sohzgku2xpbxplh2z2sip00%29%287593%29%281243925%29%28je6NUbpObpQ-NC_nTEgHUJCR2KCfHz9beg%29%28%29&irclickid=_qdsg1r9rwgkfqyvqkk0sohzgku2xpbxplh2z2sip00)
* Content Source: [Teams/rooms/with-exchange-on-premises.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-exchange-on-premises.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Reithy28** [comment]
Sorry to comment on a closed ticket but I do not believe this should be closed.

I am also experiencing the same issue with attempting to setup the MTR mailbox following the instructions.

Why should a customer submit a ticket for obviously incorrect documentation that MS has provided?  What is the point of the feedback or GitHub interaction if the outcome is to close the ticket and get individual customers to open a ticket?
