### ISSUE TITLE
Article is about MTR-W

### ISSUE THREAD

**Issue by sewagner** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6965]
[Enter feedback here]
Please make clear that this article refers to MTR for Windows. Most of the things in this article do NOT apply to MTR for Android (Collaboration Bar).
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa81c0c7-1f2d-09ed-da2d-298aba689e56
* Version Independent ID: 73fd96c0-2b94-d7ea-f900-e88b84344bdd
* Content: [Microsoft Teams Rooms Security - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/security?source=docs)
* Content Source: [Teams/rooms/security.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/security.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@sewagner Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
