### ISSUE TITLE
Unclear if applicable to Education SKUs

### ISSUE THREAD

**Issue by greg2k** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6970]
I can't see any information regarding the licensing required for using Microsoft Teams Rooms within an org using Microsoft 365 Education A3 for Faculty and Office 365 Education A1 for Faculty. I'm assuming the licensing requirements would be similar to the equivalent Enterprise SKUs but I'd like to see it confirmed. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-licensing)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-licensing.md)
* Service: **skype-for-business-online**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@greg2k Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @greg2k, thank you for your feedback.

I understand that you need a Microsoft Teams Rooms Standard or Premium in the same way you need them on Enterprise tenants.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
