### ISSUE TITLE
[Doc-enhancement] Troubleshooting guide - SharePoint site as Personal Tab

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6976]
There are certain issues that can arise to add SharePoint site/pages as Personal tab. Adding below mentioned points as trouble shooting steps will help to resolve the issues.

Possible issues:

1. Personal tab with SharePoint site/page is loading sometimes and showing blank screen intermittently. 
2. Working fine in Teams webclient(https://teams.microsoft.com) and not working in Desktop teams client. Showing blank screen.

Possible reasons and solution:
1. contentURL and Website URL might have given wrong.:

contentUrl in manifest must be in following format: {{siteUrl}}/_layouts/15/teamslogon.aspx?SPFX=true&dest={{sitePath}}
ex: https://contoso.sharepoint.com/_layouts/15/teamslogon.aspx?SPFX=true&dest=/sites/ContosoHub
ex2: https://orgtenantname.sharepoint.com/_layouts/15/teamslogon.aspx?SPFX=true&dest=/teams/site2

websiteUrl must be in following format: {{siteUrl}}
ex: https://contoso.sharepoint.com/sites/ContosoHub
ex2: https://orgtenantname.sharepoint.com/teams/site2

2. SSO(single sign-on) properties missing in manifest 
    Make sure you added following properties in [manifest](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#webapplicationinfo):
   AAD application ID: 00000003-0000-0ff1-ce00-000000000000
   Resource Url: {{subdomain}}.sharepoint.com
                  Ex:   https://contoso.sharepoint.com
                  Ex2: https://orgtenantname.sharepoint.com

Final generated manifest should be similar as shown [here](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-standalone-static-tabs-using-spo-sites#a-sample-manifestjson-file)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611ed1ac-09a9-3491-7fa8-d282b4558fbe
* Version Independent ID: b5a1dba5-beab-7188-fe18-0a045814dde0
* Content: [Create a Teams 'Intranet Portal app' from a SharePoint Online site or page - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-standalone-static-tabs-using-spo-sites)
* Content Source: [Teams/teams-standalone-static-tabs-using-spo-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-standalone-static-tabs-using-spo-sites.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@SubbaReddi Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
