### ISSUE TITLE
Clarify the requirement for local technician

### ISSUE THREAD

**Issue by Jason6311** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6985]
I assume the need for a local technician to enter the admin-generated code is only required once during the initial provisioning of the device? It would defeat the point of this feature otherwise to require that every time the device needed to be remotely logged in or out. Please clarify this ambiguity. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 344ac314-e98e-ab21-ef47-fb0da80ec884
* Version Independent ID: 8f3d2fe8-5d96-4298-f875-fb3e64688afc
* Content: [Remote provisioning and sign in for Teams Android devices - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/remote-provision-remote-login)
* Content Source: [Teams/devices/remote-provision-remote-login.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/remote-provision-remote-login.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
