### ISSUE TITLE
Typo at article section "Required administrative credentials"

### ISSUE THREAD

**Issue by rito2k** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6990]
Typo at article section "Required administrative credentials", first bullet point (missing "i" in CSServerAdministrator role name): 
In the on-premises environment, the user performing the move must have the CSServerAdmin**i**strator role in Skype for Business Server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9144d9e4-1894-e4a3-212b-7e765a8d6079
* Version Independent ID: bb9c62be-58b3-31d5-4933-fe1b0374351a
* Content: [Move users between on-premises and cloud - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/move-users-between-on-premises-and-cloud?source=docs)
* Content Source: [Skype/SfbHybrid/hybrid/move-users-between-on-premises-and-cloud.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/move-users-between-on-premises-and-cloud.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@rito2k Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Reeced40
