### ISSUE TITLE
How to convert the user back to a federated user

### ISSUE THREAD

**Issue by TAMSHUI** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6993]
[Enter feedback here]
In this section:
If you deployed Active Directory Federation Services (AD FS), you may have to convert the user account to a managed user before you follow these steps, and then convert the user back to a federated user after you complete these steps.

But how? 
I just find federated ->standard. (Convert-MsolFederatedUser)
But How to convert the user back to a federated user

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee417633-3d52-646b-2ef0-94f71535db75
* Version Independent ID: 527bb7f0-b4a7-108c-6f86-8fadced63b86
* Content: [Deploy Microsoft Teams Rooms with Exchange Online - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-exchange-online?source=docs)
* Content Source: [Teams/rooms/with-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-exchange-online.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
