### ISSUE TITLE
External Access users can be added into group chats since long now - Update article

### ISSUE THREAD

**Issue by aalejandroaraujo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6996]
[Enter feedback here]
External Access users can be added into group chats since long now - Update article

![image](https://user-images.githubusercontent.com/36446421/113862138-50c01e80-97a8-11eb-880c-f2fe768488a6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f080a5c-4268-1db4-566f-f1edc27920b5
* Version Independent ID: ac556a92-58af-3e05-f53b-0fc00afc96c0
* Content: [Use guest access and external access to collaborate with people outside your organization - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/communicate-with-users-from-other-organizations#compare-external-and-guest-access)
* Content Source: [Teams/communicate-with-users-from-other-organizations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/communicate-with-users-from-other-organizations.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@aalejandroaraujo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @aalejandroaraujo, thank you for your feedback.

Could you kindly share the article? Thanks!

**Comment by aalejandroaraujo** [comment]
Hi, no article found, it’s basically something that is available. Easy to test by yourself 😅

Alejandro Araujo Rajzner

El 19.04.2021, a las 18:31, Dario Woitasen ***@***.***> escribió:

﻿

Hi @aalejandroaraujo<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faalejandroaraujo&data=04%7C01%7C%7Cf9a48011087d45d3ea5608d903509b1d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637544466993726855%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=URP%2BdZ0Xl83HQtqfBNabxHJf6y0tlcrku1xd4qOKxjM%3D&reserved=0>, thank you for your feedback.

Could you kindly share the article? Thanks!

**Comment by dariomws** [comment]
@aalejandroaraujo I'm asking about the article because it's not supported, and I cannot reproduce it. You can add guest users to a group chat but not external (federated) users.
It's a highly requested feature, you can vote it here:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/38322514-allow-external-users-to-access-group-chat

**Comment by aalejandroaraujo** [comment]
You are right. Please disregard.

Alejandro Araujo Rajzner

El 21.04.2021, a las 10:48, Dario Woitasen ***@***.***> escribió:

﻿

@aalejandroaraujo<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faalejandroaraujo&data=04%7C01%7C%7C220d7283003a4e60be4108d904a23c5f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637545917104902303%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f4p%2Bk9ESqKAIK3L2J9xb1j2P%2BdMSiCK2FfZesgOwu%2BI%3D&reserved=0> I'm asking about the article because it's not supported, and I cannot reproduce it. You can add guest users to a group chat but not external (federated) users.
It's a highly requested feature, you can vote it here:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/38322514-allow-external-users-to-access-group-chat<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoftteams.uservoice.com%2Fforums%2F555103-public%2Fsuggestions%2F38322514-allow-external-users-to-access-group-chat&data=04%7C01%7C%7C220d7283003a4e60be4108d904a23c5f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637545917104912304%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=a76ebC%2BTf8vVGh1ZX0fvWDI4nDzTrMmAwnSDOPCGLSU%3D&reserved=0>
