### ISSUE TITLE
MS Teams storage limits

### ISSUE THREAD

**Issue by GamalielCorona** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6999]
Hi There,

On this document states that MS Teams storage is 25TB per site or group, but if you see the link in the context about the SharePoint and OneDrive limits doesn't match this number, please can you provide more information about how was calculated this 25 TB?

Thanks
Gamaliel Corona

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@GamalielCorona Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by GamalielCorona** [comment]
Hi Manuela,

I have no issue with it, I think it is more in regards Microsoft reputation of giving accurate information, I'm only a MS Technical Architect whose just found a poor information in a technical article.

Thanks
Gamaliel Corona
MS Technical Solutions Architect
Auckland Council

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
