### ISSUE TITLE
Client Preference Keys

### ISSUE THREAD

**Issue by smwk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#700]
I assume AutoDetectAutoDicoveryURLs  should be AutoDetectAutoDiScoveryURLs ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02176a36-dbd7-13ba-49cb-577333dfa9cf
* Version Independent ID: 89b24c28-4485-69e7-498d-9709efb0048b
* Content: [Customize the Mac client experience in Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/customize-the-mac-client-experience?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/customize-the-mac-client-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/customize-the-mac-client-experience.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
probably! thanks for pointing that out!
