### ISSUE TITLE
IB Policy - Screen Sharing

### ISSUE THREAD

**Issue by asampson68** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7003]
[If I'm blocked from another user by an IB policy, how can I even be in a situation such as a meeting, where screen sharing would even be an option? Wouldn't the IB policy prevent the meeting in the first place?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85a288bc-9192-8c65-4ce9-b5abb260206e
* Version Independent ID: 1f953ea6-e6e5-5e71-d541-3962637f25f9
* Content: [Information barriers in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/information-barriers-in-teams#information-barrier-triggers)
* Content Source: [Teams/information-barriers-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/information-barriers-in-teams.md)
* Service: **msteams**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
