### ISSUE TITLE
Error in page data

### ISSUE THREAD

**Issue by RyanVeerhuis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7005]
this page incorrectly asserts that 'Transferred From Call Queue Identity' is an available field in CQD. 

This field is not available in CQD data exported to PowerBI.

CQ
Transferred From Call Queue Identity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 628345c6-f5f9-fe8e-bfff-faea00a8a25c
* Version Independent ID: 30f2d051-5af5-0063-7099-38b5b08ec1e4
* Content: [Auto Attendant & Call Queue Historical Report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/aa-cq-cqd-historical-reports)
* Content Source: [Teams/aa-cq-cqd-historical-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/aa-cq-cqd-historical-reports.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@CLYVR can you verify?

**Comment by scanum** [comment]
Hi @CLYVR and @MikePlumleyMSFT Hope you are well. Wanted to follow up here to see if there is an update? Please let us know if there is anything we can do to help. Thanks.

**Comment by MikePlumleyMSFT** [comment]
@DaniEASmith fyi

**Comment by CLYVR** [comment]
@MikePlumleyMSFT @scanum @DaniEASmith Sorry - missed this one.  Will take a look.  There is a new version of the reports coming soon and I'll make sure to update the documentation to address this.
