### ISSUE TITLE
Additional information should be added

### ISSUE THREAD

**Issue by GitRomney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7009]
[Enter feedback here]
MS Roadmap feature [68880](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=Worldwide%20(Standard%20Multi-Tenant)%2CAll%20environments&searchterms=68880) is now showing as "Launched," as of yesterday. This feature suggests that it allows admins to enable the ability for users submitting feedback to include an email address. This page should include information about how an admin can do this. From doing some digging, I found [this page](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsfeedbackpolicy?view=skype-ps), which seems to suggest a command like this would work:

Set-CsTeamsFeedbackPolicy -Identity Global -AllowEmailCollection $True

Unfortunately, a Get-CsTeamsFeedbackPolicy command doesn't expose the setting on the AllowEmailCollection parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bf3bc26-4cac-56c0-8669-6540adf3c502
* Version Independent ID: bd7cd483-e40e-88c2-b9ee-b21a9ea73005
* Content: [Manage feedback policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-feedback-policies-in-teams)
* Content Source: [Teams/manage-feedback-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-feedback-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
@GitRomney Thank you for your feedback. We published an update to the Manage feedback page this morning. It should be visible around 12pm PST.
