### ISSUE TITLE
Missing instructions on how to enable Notifications and Alerts to be visible in Teams Admin Center

### ISSUE THREAD

**Issue by tomlaciano** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7015]
[Enter feedback here]
This page speaks about the Notification and Alerts capability but it fails to address what to do if an admin does not see that feature in the Teams Admin Center navigation. 

Screen shot of my Teams Admin Center navigation which does not include Notification and Alerts. 
![image](https://user-images.githubusercontent.com/40183096/114450762-65cfef80-9ba4-11eb-8427-58a9560215d2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad4aa355-090d-7315-aaf1-ed31a654e942
* Version Independent ID: 6bf8a83b-2bb6-6932-2e0d-6ccc742d1777
* Content: [Microsoft Teams Devices Monitoring and Alerting - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/alerts/device-health-status)
* Content Source: [Teams/alerts/device-health-status.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/alerts/device-health-status.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
