### ISSUE TITLE
Add Sip Proxy Address 

### ISSUE THREAD

**Issue by Norafify89** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7017]
Hi, 

Refer to below image, What do you mean by interoperability issues that rely on this attribute? 
If we migrate user to Teams only mode, do we still need to add their sip proxy address? 

![image](https://user-images.githubusercontent.com/81559366/114521779-5371b680-9c75-11eb-832b-e0f881cd533c.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ce37c7f-6f13-8442-bfdb-47065a7339b3
* Version Independent ID: 9a2b5082-369d-7c04-4fa8-81c1440ea119
* Content: [Disable hybrid to complete migration to the cloud - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/cloud-consolidation-disabling-hybrid)
* Content Source: [Skype/SfbHybrid/hybrid/cloud-consolidation-disabling-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/cloud-consolidation-disabling-hybrid.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Norafify89** [comment]
Hi @scanum, 

There must be reason why you put adding sip proxy address back on Active Directory, I just want to know what happen if we didn't add this attribute to the user. assuming all the users in cloud and Teams Only Mode.
