### ISSUE TITLE
Helpful But I'm Running Into Error Code 574

### ISSUE THREAD

**Issue by kismetgerald** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#702]
I have followed this article and successfully created an OAuth partnership between my SfB 2015 and Exchange 2016 servers.  However, upon running the Test-CsExStorageConnectivity on the SfB server, I immediately get a failure with error code 574 - stating that the "Client found response content type of '', but expected 'text/xml'."  How do I get past this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d458976f-b1c2-7a2d-a41a-f6219e65e691
* Version Independent ID: 7617f7d2-1e8d-99c4-82b8-ff84a7fe0818
* Content: [Configure partner applications in Skype for Business Server 2015 and Exchange Server](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/integrate-with-exchange-server/configure-partner-applications)
* Content Source: [Skype/SfbServer/deploy/integrate-with-exchange-server/configure-partner-applications.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/integrate-with-exchange-server/configure-partner-applications.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Hi @kismetgerald this feedback system is for documentation corrections, not break/fix support issues. For support try here: https://support.office.com/en-us/home/chat?ContactUsExperienceEntryPointAssetId=S.HP.skype-for-business&referrer=https%3A%2F%2Fsupport.office.com%2Fen-us%2Fskype-for-business. Hope this helps!
