### ISSUE TITLE
Make unsupported features in chat with external users evident

### ISSUE THREAD

**Issue by fpiecka** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7020]
The following wording seems misleading:

> if both your Teams user and the person in another organization is in the TeamsOnly upgrade mode, you can have a "native-Teams chat experience," which includes rich formatting, @mentions, and other chat features. In other words, you can have the same rich 1:1 Teams chat experience with eligible people in other organizations as you'd have with users in your organization

In the [parent page](https://docs.microsoft.com/en-us/microsoftteams/communicate-with-users-from-other-organizations) you can see that e.g. file sharing is unsupported in chat with external access users. File sharing seems a crucial part of chat experience and a part of "other chat features" and "rich 1:1 Teams chat experience".

Please change the wording so that it is evident that multiple features are still not supported in communication with external users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ac8f101-bdb5-2b55-d5f4-e070b70768d4
* Version Independent ID: 964d836e-d00b-b585-8f02-e03c5ec8dab9
* Content: [Native chat experience for external (federated) users in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/native-chat-for-external-users)
* Content Source: [Teams/native-chat-for-external-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/native-chat-for-external-users.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@fpiecka  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
