### ISSUE TITLE
Scary definition needs clarity

### ISSUE THREAD

**Issue by aamillerMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7022]
The wording of this definition is scary and vague.  Please add an explanation of how the telemetry information can be tampered.   The current wording brings up questions such as:
Is the tampering done on the customer of service side?
Why\How is telemetry date tampered and by whom?
Is it an indicator of a network intrusion on the customer or service?

> - **Unclassified meetings** are the ones that can't be classified as schedule or recurring or unplanned. These are short in number and mostly _can't be identified because of tampered telemetry information_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2758a3d6-c646-dcb0-2a31-c7b9b84e780b
* Version Independent ID: 8704c9fe-f8b0-82d2-bd83-3fd1a9ad638d
* Content: [Microsoft Teams user activity report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report)
* Content Source: [Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@aamillerMSFT  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @ivlists how are you? Can you kindly help us clarify here? I appreciate it.

**Comment by get-itips** [comment]
@cichur Can you help me clarify that definition? thank you!

**Comment by tiburd** [comment]
@HowlinWolf-92 
Hi Mark!
Can you please help clarify the definition of unclassified meetings?
Thanks!

**Comment by HowlinWolf-92** [comment]
How about this:

- **Unclassified meetings** are those that can't be classified as scheduled, recurring, or unplanned. These are few in number and often can't be identified because of imperfect telemetry information.

**Comment by HowlinWolf-92** [comment]
Here's an improved version:

- **Unclassified meetings** are those that can't be identified as scheduled, recurring, or unplanned. These are few in number and often can't be identified because of imperfect telemetry

**Comment by get-itips** [comment]
Thanks @HowlinWolf-92 Mark
