### ISSUE TITLE
Comparison of team member and guest capabilities definition/wording

### ISSUE THREAD

**Issue by FlynnLives** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7025]
The choice of wording for "Comparison of team member and guest capabilities" specifically for the "Attach files" line which states "Team chats only" is very poor due to lack of definition of chat types anywhere on Microsoft's documentation website.

Many users assume this would allow guests to attach a file in a Team channel which is untrue. It would be really helpful for novice users to have a clear definition of what this means as the only use of this phrase is on the guest experience page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [Guest experience in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-experience)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@FlynnLives  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @FlynnLives, thank you for your feedback.

The table states that "attach files" for guest users is only available in Team/Channel chats, not for one-on-one or group chats.

**Comment by FlynnLives** [comment]
@dariomws it says "team chats only". The way you worded it here as 
"Team/Channel chats not one-on-one or group chats", makes this a lot more clear and leaves no room for misunderstanding like I did in the OP

**Comment by dariomws** [comment]
@FlynnLives Do you think that "Channel posts only" could be enough? "Team/Channel chats not one-on-one or group chats" is too long for the table.

Thanks!

**Comment by FlynnLives** [comment]
@dariomws excellent, thank you!
