### ISSUE TITLE
Not available yet

### ISSUE THREAD

**Issue by Strick1969** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7047]
This setting isnt available yet, why is this document out? Its very confusing for our customers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff254bd5-0d45-79c1-db9e-77768bbf1292
* Version Independent ID: ad980209-879d-5ca1-03b4-178cdc6e3548
* Content: [Microsoft Teams Monitoring and Alerting - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/alerts/teams-admin-alerts)
* Content Source: [Teams/alerts/teams-admin-alerts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/alerts/teams-admin-alerts.md)
* Service: **msteams**
* GitHub Login: @Vaibhav
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@Strick1969 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@Strick1969 
Looking into this, thanks

**Comment by cichur** [comment]
Hello @Strick1969, You are correct. This feature isn't available yet. We've removed the articles for now. Thank you, Cindy
