### ISSUE TITLE
Who has the permissions to view the meeting recording doesn't seem to match throughout the document

### ISSUE THREAD

**Issue by ACarlockAKA** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7051]
In the Permissions or role-based access section it seems like only actual attendees of meetings have access to the recordings (this has been our experience).  However in the FAQ: Who has the permissions to view the meeting recording? section it looks like meeting Invitees have access to the recordings (implying that even if they didn't join the meeting, the recording is automatically shared with them).  I think this FAQ section should be updated to match the previous section and say that meeting attendees instead of invitees have access to the recordings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8935e913-806f-a92c-d09e-e67df4ffd1b4
* Version Independent ID: c7a41cde-66dd-d7cd-1316-42d20ed4841a
* Content: [Use OneDrive for Business and SharePoint for meeting recordings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/tmr-meeting-recording-change)
* Content Source: [Teams/tmr-meeting-recording-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tmr-meeting-recording-change.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
