### ISSUE TITLE
Update docs to details changes in MicrosoftTeams 2.2.0-preview

### ISSUE THREAD

**Issue by robinmalik** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7054]
This page requires updating to reflect changes in https://www.powershellgallery.com/packages/MicrosoftTeams/2.2.0-preview

Thank you :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 173b5929-529b-938b-b6ab-59f05a5d69a8
* Version Independent ID: 0a3dfe5e-938f-933d-637e-b7449e3b8aa5
* Content: [Microsoft Teams PowerShell Release Notes - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes)
* Content Source: [Teams/teams-powershell-release-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-release-notes.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
@robinmalik Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @robinmalik, thank you for your feedback.

The article was updated with that information the same day you reported it or the next day.

**Comment by robinmalik** [comment]
@dariomws Thanks!
