### ISSUE TITLE
GCC limit of 250 meeting

### ISSUE THREAD

**Issue by desmay** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7058]
I believe correct limit of GCC meeting attendance is 300 users not 250 as stated on this page. 

300 user limit in GCC - https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#meetings-and-calls
250 user limit in GCC - https://docs.microsoft.com/en-us/microsoftteams/view-only-meeting-experience#view-only-feature-limitations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bf705c2-1f24-bdb5-e712-e8408b941aca
* Version Independent ID: ddedd7e0-7d85-06e0-7f20-8b83b3dccec7
* Content: [View-only meeting experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/view-only-meeting-experience?source=docs#view-only-feature-limitations)
* Content Source: [Teams/view-only-meeting-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/view-only-meeting-experience.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@desmay Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Reeced40

**Comment by Reeced40** [comment]
@desmay thank you for helping improve MS Docs. It looks like the article has been updated in the interim. Please confirm from your side. Thanks.
