### ISSUE TITLE
Teams as part of Microsoft 365 Posters - Wrong Document Linked

### ISSUE THREAD

**Issue by Sdean1234** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7060]
On the first two links on this page for poster of "Teams as part of Microsoft 365", both the PDF link and the Visio link resolve to the Microsoft Voice poster and not the one mentioned above. Could you please fix? Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ad624-9792-91b7-c85f-09b839b1ea44
* Version Independent ID: e8288f91-11bd-599b-8a88-074917b315a4
* Content: [Microsoft Teams IT architecture and voice solutions posters - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-architecture-solutions-posters#teams-as-part-of-microsoft-365)
* Content Source: [Teams/teams-architecture-solutions-posters.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-architecture-solutions-posters.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@Sdean1234 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Reeced40

**Comment by Reeced40** [comment]
@Sdean1234 thank you for pointing this out and helping improve MS Docs. This was resolved in another issue and should be live soon.
