### ISSUE TITLE
Meeting Recording retention unclear

### ISSUE THREAD

**Issue by schumatt-msft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7063]
In the **Meetings & Calls** section, one row of the table shows

> Teams keeps meeting recordings that don't get uploaded to Microsoft Stream, available for local download = 20 days

Two questions here:

1. Is that referring to a completed recording that failed to upload to Stream? The phrasing in unclear if the "recordings that don't get uploaded" is because the upload failed or because the user somehow chose not to upload.
2. With the move to save recordings in OneDrive/SharePoint instead of Stream, is there any change to this behavior or the length of time the local copy is stored?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by schumatt-msft** [comment]
> I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

@scanum - I'm reporting this issue as a Microsoft employee and following up on these questions from one of my M365 customers. Request that you reopen this issue pending clarity on the questions. Feel free to ping me internally if necessary.
