### ISSUE TITLE
SipTesterClient Script gives me an error on powershell core 7.1.3

### ISSUE THREAD

**Issue by michaelm-devel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7065]
Does the SipTesterClient run on PowerShell Core 7.1.3. I Get this error when executing script

Line |
 409 |  â¦ statusResult = Run-SIPTest $EndpointUrl $testBody $CertificateContent
     |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Enqueueing test...FAILED: Unspecified Failure

False

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
