### ISSUE TITLE
Spelling erorr

### ISSUE THREAD

**Issue by grahammw** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7071]
In this section for 4.8.19.0, there is a spelling error.  It says Microsoft Defender Advanced Thread Protection and it should say Microsoft Defender Advanced Threa**t** Protection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1365f9b8-001c-daa7-592e-d88b9bb3a10e
* Version Independent ID: ffba1b4d-1f19-4dac-0b55-053d98fe26b7
* Content: [Release notes - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-release-note)
* Content Source: [Teams/rooms/rooms-release-note.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-release-note.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@grahammw Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Reeced40
