### ISSUE TITLE
Incorrect File Link

### ISSUE THREAD

**Issue by SelvaKP** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7072]
First PDF file hyperlink is pointing to the wrong file.
Link under "Teams as part of Microsoft 365" is same as link under "Microsoft voice solutions"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ad624-9792-91b7-c85f-09b839b1ea44
* Version Independent ID: e8288f91-11bd-599b-8a88-074917b315a4
* Content: [Microsoft Teams IT architecture and voice solutions posters - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-architecture-solutions-posters)
* Content Source: [Teams/teams-architecture-solutions-posters.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-architecture-solutions-posters.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@SelvaKP Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Reeced40

**Comment by Reeced40** [comment]
@SelvaKP thank you for pointing this out and helping improve MS Docs. This issue was resolved with another PR and should be live soon.
