### ISSUE TITLE
Has this feature even rolled out yet?

### ISSUE THREAD

**Issue by dinocaputo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7075]
None of the tenants I have checked (R4, R3 and R1.5) have this capability.  Have docs been prematurely released?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff254bd5-0d45-79c1-db9e-77768bbf1292
* Version Independent ID: ad980209-879d-5ca1-03b4-178cdc6e3548
* Content: [Microsoft Teams Monitoring and Alerting - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/alerts/teams-admin-alerts)
* Content Source: [Teams/alerts/teams-admin-alerts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/alerts/teams-admin-alerts.md)
* Service: **msteams**
* GitHub Login: @Vaibhav
* Microsoft Alias: **v-cichur**

**Comment by Vaibhav** [comment]
Same issue as #7047

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
