### ISSUE TITLE
Out of date information as Teams do respect the Microsoft 365 Groups naming policy 

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7078]
There are a couple of paragraphs that mention  that statement that Teams respects Microsoft 365 Groups naming policy is in private preview. this functionality has been in GA for a long time
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c310bab-f8d8-b173-0bff-9f93fe1f7abf
* Version Independent ID: 1f983e68-65e3-aa7d-aaaa-d62912f37e4c
* Content: [Plan for Microsoft 365 Groups when creating teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/plan-office-365-groups)
* Content Source: [Teams/plan-Office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-Office-365-groups.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@nikki-c Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Thank you for your feedback @nikki-c!
