### ISSUE TITLE
Article Needs Update

### ISSUE THREAD

**Issue by richardojel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7079]
[Enter feedback here]
Hello All,

It is my experience that there are actually 3 kinds of chats.
1. Native experience with teams. This is very rich and it shows between TeamsOnly 2 TeamsOnly within the tenant.
2.  Native Experience as it applies to federated chats - This is not as rich as Internal Teams 2 teams.
3.  Interop Chat more text based. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ac8f101-bdb5-2b55-d5f4-e070b70768d4
* Version Independent ID: 964d836e-d00b-b585-8f02-e03c5ec8dab9
* Content: [Native chat experience for external (federated) users in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/native-chat-for-external-users)
* Content Source: [Teams/native-chat-for-external-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/native-chat-for-external-users.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@richardojel Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @richardojel how are you? Hope you are doing good!

The interop experience is described in the article under the one you created the issue

https://docs.microsoft.com/en-us/microsoftteams/teams-skype-interop

> Conversations are text-only. This means that there's no rich formatting, @mentions, emojis, or other any of the other chat features that are available in a native Teams chat experience.

Hope this information clarifies it,

**Comment by richardojel** [comment]
Hello Andres,

This is what I mean.

Pic A – Is a Conversation between 2 users on the same tenant. Both users are TeamsOnly. You can see the Rich format includes  ( Font,Important, file attachment, Giphy, emoji etc)

***@***.***D73691.CA08C850]


Now see how it looks between federated partners who are on TeamsOnly

Pic B

***@***.***D73692.B6B37BA0]

No File attachment, Urgency etc. It’s a fraction of what is showed above.

And the 3rd Pic - Between TeamsOnly user and an Island User ( where information lands in Skype)

***@***.***D73693.5064BA70]

Just pure Text based only.

The article does not clarify the differences between in Rich text format between Internal users and federated TeamsOnly users.

Regards
Richard O.

**Comment by get-itips** [comment]
Richard, @richardojel  the screenshots were not included in your message

**Comment by richardojel** [comment]
Hi Andres,

They appear empty but if you double click on the seemingly empty space they should appear.
If you still do not see it. I will send the pictures over to you via v-dash.

Regards
Richard O.
________________________________

**Comment by richardojel** [comment]
Hello Andres,

Have you received the pictures ?

Regards

**Comment by get-itips** [comment]
> Hello Andres, Have you received the pictures ? Regards

Hello Richard, I am sorry but no, if you send them replying by email they won't be available here to see.
But I think that I understand what you mean

> No File attachment, Urgency etc. It’s a fraction of what is showed above.

The article here does not mention that File Attachment or Urgency will be available explicitly:

> If you've got all of the other chat functionality, including formatting, @mentions, emojis, etc., then you're in a native Teams chat.

Image from my lab tenant:

![image](https://user-images.githubusercontent.com/36666927/115786241-c5d14d80-a37d-11eb-937d-0bf29a7d740d.png)

Let me know if I understood you well.

**Comment by richardojel** [comment]
Yes, you have. Thanks
