### ISSUE TITLE
mistype in sipinternal. <sipdomain> record

### ISSUE THREAD

**Issue by h-david-a** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#708]
sipinternal. &lt;sipdomain&gt;  -&gt; according to table "internal DNS mappings" is an SRV record, but value doesn't specify protocol & port. According to "Walkthrough of Skype for Business clients locating services" article  (https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/edge-server-deployments/advanced-edge-server-dns#WalkthroughOfSkype)
it is an A record:
sipinternal.&lt;domain&gt;
This is an A host record for the Front End pool or Director, resolvable only on the internal network.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94881ba-6f06-a946-47a3-c9c683ddd303
* Version Independent ID: 081684f7-3570-fdfd-c32d-90b6e07d81b4
* Content: [DNS requirements for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/network-requirements/dns#dns-by-server-role)
* Content Source: [Skype/SfbServer/plan-your-deployment/network-requirements/dns.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/network-requirements/dns.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
I've corrected the listing in the table.
