### ISSUE TITLE
Approvals: Says available to all users, but isn't

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7082]
"The Approvals app is available as a personal app for all Microsoft Teams users." This feature has not been released to GCC/GCCH/DOD users yet. GCC won't get it until mid-May according to MC249776.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 055b01ff-ee6c-7d5a-74bd-0e8eed7ee6b5
* Version Independent ID: 13c4174f-2a2a-2ef9-14c5-2f10817cc66a
* Content: [Approvals application availability in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/approval-admin)
* Content Source: [Teams/approval-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/approval-admin.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@npherson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by cichur** [comment]
Hi @npherson,
Thank you for your comments. I've updated the article by adding a note that mentions the feature's limited availability.
