### ISSUE TITLE
"Enable federation between users in your organization and consumer users of Skype"

### ISSUE THREAD

**Issue by bec064** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7084]
Hello!

This is still something in preview https://docs.microsoft.com/en-us/microsoftteams/manage-external-access#enable-federation-between-users-in-your-organization-and-consumer-users-of-skype but the information needs to be updated.

The Docs mention that you can enable Skype consumer with the Teams admin center. But I've never heard of anyone succeeding in doing that so that's why we use PowerShell. The steps required though are not complete. As far as I know you have to use this process (the bold parts are only for attention).

Set-CsExternalAccessPolicy
-EnablePublicCloudAccess
"**Indicates whether the user is allowed to communicate** with people who have SIP accounts with a public Internet connectivity provider such as MSN. The default value is False."

Set-CsTenantFederationConfiguration
-AllowPublicUsers
"When set to True (the default value) users will be **potentially allowed to communicate** with users who have accounts on public IM and presence providers such as Windows Live, Yahoo, and AOL. The collection of public providers that users can **actually communicate with** is managed by using the Set-CsTenantPublicProvider cmdlet."

Set-CsTenantPublicProvider
-Provider
"Indicates the public provider (or providers) that users will be allowed to communicate with. Valid values are:"

AOL
WindowsLive
Yahoo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external access (federation) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access#enable-federation-between-users-in-your-organization-and-consumer-users-of-skype)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by bec064** [comment]
Hello, this has nothing to do with my tenant. I opened the issue because the necessary steps provided in the article to get it working are not complete. Hence the attached parameters.
