### ISSUE TITLE
This will prevent interoperability issues that rely on this attribute.

### ISSUE THREAD

**Issue by paulch7780** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7086]
[Enter feedback here]
Step 5 in the documentation to remove all onprem attributes does instruct the opposite, the users need to be assigned a proxyaddress attribute. Please explain under which circumstances it is required, if it is required, what is the impact of not doing that, does the attribute need to be set on the future online Teamsonly accounts (presumably not). What is meant by the interoperability issues. "Run the following on-premise Active Directory Module for Windows PowerShell cmdlet to add sip address value back to the on-premises Active Directory proxyAddresses. This will prevent interoperability issues that rely on this attribute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ce37c7f-6f13-8442-bfdb-47065a7339b3
* Version Independent ID: 9a2b5082-369d-7c04-4fa8-81c1440ea119
* Content: [Disable hybrid to complete migration to the cloud - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/cloud-consolidation-disabling-hybrid)
* Content Source: [Skype/SfbHybrid/hybrid/cloud-consolidation-disabling-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/cloud-consolidation-disabling-hybrid.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@paulch7780 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Reeced40

**Comment by Reeced40** [comment]
@CarolynRowe please can you help here?

**Comment by Reeced40** [comment]
@CarolynRowe

**Comment by tiburd** [comment]
@paulch7780 - Hi Paul, it looks like this article has been updated since the time you opened this issue, so I'm closing this issue. If your concerns still exist in the updated article(s), please open a new issue. 

Thank you!
