### ISSUE TITLE
Why are there files in the customer success kit showing corrupted.

### ISSUE THREAD

**Issue by HeatherWaterman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7088]
When I download the success kit there are files in the End user Communication that show as corrupt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 377ed460-94ef-6528-63de-87360156b71e
* Version Independent ID: 56e32c63-dadb-fb81-c04e-6cf396963f2d
* Content: [Tools & workshops - Plan, deliver, & adopt Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/planning-workshop-practical-guide)
* Content Source: [Teams/planning-workshop-practical-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/planning-workshop-practical-guide.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
