### ISSUE TITLE
Shall you be a transparent and share features which are not yet available?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7097]
Hi,

When reading the admin center message MC222640, it is having the following list:

*** Feature gaps**
**The following gaps exist today:**

- Ability to block download of the video by meeting participants
- Ability to view and edit the transcript in the player.
- Non-English language transcripts/captions
- Variable playback speed in video player
Transcript timeframe search (e.g., to find a specific point in time when something was discussed)

For regular user it would be super bad if they are not able to trim the recordings anymore as easily they were doing on Stream service. So it would be nice if you could share these as well to readers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8935e913-806f-a92c-d09e-e67df4ffd1b4
* Version Independent ID: c7a41cde-66dd-d7cd-1316-42d20ed4841a
* Content: [Use OneDrive for Business and SharePoint for meeting recordings - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/tmr-meeting-recording-change)
* Content Source: [Teams/tmr-meeting-recording-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tmr-meeting-recording-change.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Petri-X thank you for reaching out and helping improve MS Docs. Just for clarity are you saying there is important information missing from this article as per your suggestion above? Are these features readily available?
