### ISSUE TITLE
Data residency and Access control.

### ISSUE THREAD

**Issue by t6c4u2c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#71]
Few questions regarding to data residency privacy and access control for Canadian organizations. 

1. Is it possible to redirect all data explicitly to Microsoft's Canadian DCs as a whole? Assuming there'd be costs associate to it.

2. Does Microsoft segregate file storage, per user in an organization?    
3. Possible to place restrictions per file like SharePoint?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca579d63-182b-d6f5-8777-79248fa27ed9
* Version Independent ID: b4c27d1b-b2f1-41ac-b15c-d12b448a539e
* Content: [Overview of security and compliance in Microsoft Teams | Microsoft Docs](https://docs.microsoft.com/en-us/microsoftteams/security-compliance-overview#feedback)
* Content Source: [Teams/security-compliance-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/security-compliance-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by LolaJacobsen** [comment]
1. We don't yet support Canada DCs. Canada GoLocal is on the roadmap for this year. When this is launched, all new tenants will be deployed in Canada. Roadmap: https://products.office.com/en-US/business/office-365-roadmap?filters=microsoft%20teams%26freeformsearch=canada%20datacenter

2. Our files are stored in SharePoint and OneDrive for Business. OneDrive for business is per-user and the SharePoint storage is per team.

3. The file storage for Teams is SharePoint, so Teams offers the same per-file restrictions as SharePoint.

Thanks for your questions! Let me know if you need more information.

**Comment by t6c4u2c** [comment]
Hello - thank you so much with your response.  Will certainly follow-up should I need anything more.
