### ISSUE TITLE
Download Link for MTR Update is Broken

### ISSUE THREAD

**Issue by shwo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7105]
Hey guys. The link to download the latest file for manual updates of MTRs is broken:
![image](https://user-images.githubusercontent.com/83062198/115839846-fb744600-a412-11eb-83d7-93114e225381.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4fa80cf-0319-c006-e886-4929a508b04c
* Version Independent ID: 9d598765-fc30-17f0-6594-57de81d8aa39
* Content: [Manually update a Microsoft Teams Rooms device - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/manual-update)
* Content Source: [Teams/rooms/manual-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/manual-update.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by Travis-Snoozy** [comment]
More than just that file was failing to be served, but the issue should be resolved now. Please try the relevant links again.

**Comment by dstrome** [comment]
@Travis-Snoozy thanks - you're right. DMC outage caused the error. Thanks @shwo for reporting.
