### ISSUE TITLE
Feedback: User Availability Shows Status “Unknown” in Teams Scheduling Assistant

### ISSUE THREAD

**Issue by XixiHuang333** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7106]
[Enter feedback here]

Issue
An user is trying to create new Microsoft Teams meeting using 'Scheduling Assistant' tab. Some users listed as attendees have their status showing as "Unknown", despite those users not having any events scheduled for the day of the meeting.

This is the issue that Teams product engineering is still working on it. Customer asks MS to document this feature limitation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a162ef5c-3099-7f58-4178-d29e3ec2b5a7
* Version Independent ID: 6ca31e56-052d-6c62-1323-b5aaaae1f04a
* Content: [User presence in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/presence-admins)
* Content Source: [Teams/presence-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/presence-admins.md)
* Service: **msteams**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by XixiHuang333** [comment]
@scanum   Hi Scanum,
I noticed you pasted link of contacting support. I am MS Teams technical support and this is customer request: "We just need a link or KB from Microsoft mentioned that this is the currently behaviour." 
Could you please help on this further?

**Comment by XixiHuang333** [comment]
@scanum  you may contact me at xixih@microsoft.com

**Comment by XixiHuang333** [comment]
Hi OfficeDocs team,

Could you please reopen this?

Thanks,
Xixi
