### ISSUE TITLE
Set-TeamTargetingHierarchy - missing from 2.0.0 version but available in 1.1.9-preview version

### ISSUE THREAD

**Issue by narulasrinivas** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7107]
Thanks for documenting the steps to set up Team Targeting Hierarchy. But I don't find `Set-TeamTargetingHierarchy` in `2.0.0 `version. I did an further analysis and found this command in `1.1.9-preview` version. 

Please let us know whether `Set-TeamTargetingHierarchy` command was renamed or removed.

Please refer below screenshot of both 2.0.0 and 1.1.9-preview.

1.1.9 Version - `Set-TeamTargetingHierarchy` **available**
![image](https://user-images.githubusercontent.com/2491903/115871819-f3c79800-a438-11eb-815f-68295d41a424.png)

2.0.0 version - `Set-TeamTargetingHierarchy` **missing**
![image](https://user-images.githubusercontent.com/2491903/115871904-0f32a300-a439-11eb-8c66-c4239ee621a8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c03584a-ee6c-2594-1601-07dc2ae32371
* Version Independent ID: f8dc6040-5495-ef0b-bb78-0b3b1a7a14bd
* Content: [Set up your team targeting hierarchy - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-your-team-hierarchy)
* Content Source: [Teams/set-up-your-team-hierarchy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-your-team-hierarchy.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Hi @narulasrinivas 
The Set-TeamTargetingHierarchy cmdlet and related cmdlets are only available in the preview cmdlets. Please see this article. https://docs.microsoft.com/en-us/powershell/scripting/gallery/getting-started?view=powershell-7.1
Thank you for your question. Cindy

**Comment by narulasrinivas** [comment]
@cichur  - Thanks for your input. After going through document, I'm not sure what you're pointing in the given link.

Whether preview cmdlets will become available in stable version at one stage or will that be deprecated?

Please guide me on this.

**Comment by cichur** [comment]
Hi @narulasrinivas,

From the SME:

The Set-TeamTargetingHierarchy cmdlet is only available in the preview cmdlets for Teams. It is not available in the production version of the module. If the version number does not say -preview at the end, then we do not expect the cmdlet to be available.

-Cindy

**Comment by narulasrinivas** [comment]
Hi @cichur,

Thanks for clarifying my query. 

Then this raises few more questions

1.  If cmdlet is only available at preview, then setting up team hierarchy is not recommended or do we need to find other approach to achieve it?
2.  If this is an preview version, then why is it missing from the documentation of Team Hierarchy documentation?

We thought to enable Team Hierarchy across organization and it has impact of more than 70,000+ users. Can you please guide on the right approach?
