### ISSUE TITLE
CreateSrsMedia.ps1 script link is failing

### ISSUE THREAD

**Issue by nathanhamblin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7108]
Getting the error when trying to download:
404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/console#Prep_Media)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by Travis-Snoozy** [comment]
More than just that file was failing to be served, but the issue should be resolved now. Please try again.

**Comment by dstrome** [comment]
@Travis-Snoozy thanks - you're right. DMC outage caused the error. Thanks @nathanhamblin for reporting.

**Comment by digant124** [comment]
Not able to access the document.
 CreateSrsMedia.ps1 script
Clicked on a link and got 404.
