### ISSUE TITLE
New file sharing not in GCC

### ISSUE THREAD

**Issue by ricardo-msft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7112]
This feature still hasn't reached GCC cloud, and there doesn't seem to be any place where we are tracking its future rollout to GCC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9509576b-a655-f058-3d97-c0cd88393a57
* Version Independent ID: 73af3756-ecd8-6265-c1ca-ddd9fc1b0993
* Content: [Sharing files and folders in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/sharing-files-in-teams)
* Content Source: [Teams/sharing-files-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sharing-files-in-teams.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@ricardo-msft Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@MikePlumleyMSFT do you have an idea when this will rollout?

**Comment by MikePlumleyMSFT** [comment]
I don't have any information. @ricardo-msft if it's not on the [Microsoft 365 roadmap](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=), you'll have to ask around internally.
