### ISSUE TITLE
Missing mention to SharePoint files storage

### ISSUE THREAD

**Issue by aengelen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7114]
In the per-team analytics, there is no mention on storage used by SharePoint files while this is a metrics showed.

Kind regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c93d512-6e5a-09c7-1c9f-c7eeb94555da
* Version Independent ID: f289f914-6b58-6c29-8997-a2fbd017ffe7
* Content: [View analytics in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/view-analytics)
* Content Source: [Teams/teams-analytics-and-reports/view-analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/view-analytics.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@aengelen  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@aengelen thank you for reaching out and helping improve MS Docs. Is there a specific link with information that you would suggest adding here?

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
