### ISSUE TITLE
Storage and persistence behavior table - incorrect row titles

### ISSUE THREAD

**Issue by dwhitney7** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7115]
Hello, the table in the **Storage and persistence behavior** section has two parts, as laid out by the two checkboxes, "Recording available for attendees" and "Recording available for producers and presenters". However, the table labels both sections as "Recording available for producers and presenters" - the first table part should be labeled "Recording available for attendees".

I would also suggest flipping the order of the table (both rows and corresponding filled out columns), to align with the order of the options in the Teams client UI and as written earlier in the docs page.

Thanks!
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae14299b-94b7-6dcd-5560-c1dbee13918f
* Version Independent ID: 8e145920-8a41-ed84-e366-797081ea162c
* Content: [Live events recording policies - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/teams-live-events/live-events-recording-policies)
* Content Source: [Teams/teams-live-events/live-events-recording-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/live-events-recording-policies.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@dwhitney7  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@cichur

**Comment by scanum** [comment]
@dwhitney7 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
