### ISSUE TITLE
Hybrid voice connectivity with Microsoft Teams supported/unsupported scenarios

### ISSUE THREAD

**Issue by kulbirjandoria** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7119]
[Enter feedback here]
Can we use SFB on-premise server Hybrid Voice Connectivity with Microsoft Teams for cloud auto-attendant & call queues for on-premise SFB client users as agents, is this scenario is supported?

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b8da7c-87fe-fde4-ca1f-c36e062ab309
* Version Independent ID: bbfd16f1-7b78-5335-7dc5-4f6a39a4f81d
* Content: [User accounts in hybrid environment with PSTN - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-user-accounts-in-a-hybrid-environment)
* Content Source: [Teams/direct-routing-user-accounts-in-a-hybrid-environment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-user-accounts-in-a-hybrid-environment.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
