### ISSUE TITLE
Microsoft Teams auto attendant/call queue in Hybrid voice connectivity

### ISSUE THREAD

**Issue by kulbirjandoria** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7120]
Can we use SFB on-premise server Hybrid Voice Connectivity with Microsoft Teams for cloud auto-attendant & call queues for on-premise SFB client users as agents, is this scenario is supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1fa33a8-d910-caee-89ad-62f449a6072f
* Version Independent ID: 2b33ed7d-da28-f5d0-d5ff-d2e72effa3d7
* Content: [Teams voice Contoso case study - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/voice-case-study-call-queues)
* Content Source: [Teams/voice-case-study-call-queues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/voice-case-study-call-queues.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
