### ISSUE TITLE
Meeting Expiration talks about blocking Scheduling

### ISSUE THREAD

**Issue by dipinn26592** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7121]
The Meeting Expiration table talks about blocking scheduling. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee6d4c1c-6f16-b1a4-c4a9-be4e6d1f95b7
* Version Independent ID: 50ad835d-ed7f-18c6-34ba-322c1574f9c2
* Content: [Meeting policies and meeting expiration in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/meeting-expiration)
* Content Source: [Teams/meeting-expiration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-expiration.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@dipinn26592  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@dipinn26592 thank you for reaching out. Please can you clarify what is needed to be changed in the article?

**Comment by dipinn26592** [comment]
When we say meeting expiry, the customers are looking for a way to expire their existing\old meeting. ( without breaking any functionality ).

What this article calls out is if you want to expire old meeting, turn off scheduling option. So while the existing meeting will expired, the user will not be able to schedule a new meetings . This will break the scheduling for the user. 

Please correct me if i have misunderstood anything.

We might want to add a statement which lands the messgae, we cannot expire meeting on per instance basis. The only to expire is to turn off scheduling feature , which will restrict the user from schedule old meeting and also existing meeting will expire.

**Comment by lindspea** [comment]
@cichur please can you provide clarity here?

**Comment by lindspea** [comment]
@cichur

**Comment by dwhitney7** [comment]
Hey team, bringing this one back up - the language on this page is definitely throwing off some customers seeking information about how to expire specific meetings or expire all meetings after a certain time based on policy or settings. This is not possible today as dipinn26592 mentioned, and instead we have specific timeframes documented for *some* parts of a meeting to expire after a set time: https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#meeting-expiration. I would recommend adding a note mentioning and pointing to this other information.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
