### ISSUE TITLE
Meeting expiration information update request

### ISSUE THREAD

**Issue by darren-pex** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7122]
The information regarding meeting expiration currently states;

>A meeting URL will never stop working. The expiry only relates to any PSTN dial-in numbers and/or underlying meeting policies and settings.

As per #6345, can I request that this is updated to also call out CVI numbers, something like;

>A meeting URL will never stop working. The expiry only relates to any CVI coordinate and PSTN dial-in numbers and/or underlying meeting policies and settings.

From #6345;

>The reason it works is because when you access an expired meeting with Teams, Teams service will spin up a new meeting, link the old URL/GUID to the next meeting. So the meeting will launch. Even better, other participants accessing the old URL, they will be redirected to the new meeting, so they can meet. But it will have problems:
>
> - Dial in conference ID will be difference, anyone trying to dial in using the old conference ID will fail. You will see a new conference ID on the meeting detail that is different from the original meeting invite.
> - CVI connect to this expired meeting will not work, as the CVI coordinate is still pointing to the original Teams Meeting GUID.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#meeting-expiration)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@darren-pex  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@SerdarSoysal please can you help confirm this.

**Comment by lindspea** [comment]
@SerdarSoysal

**Comment by scanum** [comment]
Hello @darren-pex, per Microsoft, the CVI matter has already been addressed. No action needed at this point. They are not inclined to add the additional details about why it continues to work.
