### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by asampson68** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7123]
[Under the "Add favorite channels" section, the documentation indicates that you can enable the option to show for members "In the Channels pane of the **admin center**, check the channels under the Show for members column" This feature is not in the Teams Admin Center, it's in the Teams client app. It states the same error again in the "Regulate applications and bots section, again, this feature is in the Teams client, not the Admin Center ]

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e151c005-3dc7-763f-9811-7bb1fac2162c
* Version Independent ID: 2718d9eb-25f5-2f93-aacc-427060f1016f
* Content: [Manage large teams in Microsoft Teams - best practices - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/best-practices-large-groups)
* Content Source: [Teams/best-practices-large-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/best-practices-large-groups.md)
* Service: **msteams**
* GitHub Login: @lolaj
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
