### ISSUE TITLE
Office 365 F1 with Phone System

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7124]
Hello

Small Business tab has Office 365 F1 as a base plan and then lists Phone system as a possible add-on. 
The Enterprise tab has Office 365 F3 and Microsoft 365 F3 plans but not Microsoft 365 F1 plan as base plan. 

Can you please put Microsoft 365 F1 as a base plan on the Enterprise tab ?
Also can you please change Office 365 F1 to Microsoft 365 F1 as there is no Office 365 F1 plan anymore?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abae7324-861d-7ca7-7239-a5df8fd927d5
* Version Independent ID: 8a30bd2f-9bc3-a0a8-8b31-d53836ead4d0
* Content: [Microsoft Teams add-on licenses - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=small-business)
* Content Source: [Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@Larryngolog  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Larryngolog thank you for pointing this out and helping improve MS Docs. Do you have official documentation confirming this?

**Comment by Larryngolog** [comment]
Hi @lindspea - here is info about licensing prerequisites for Phone System: https://www.microsoft.com/licensing/terms/productoffering/AudioServices/EAEAS 
<html>
<body>


Phone System | Office 365 F3/E1/E3; Microsoft 365 Business Basic/Business Standard/Business Premium/F1/F3/E3
-- | --



</body>
</html>

As for the change of Office 365 F1 to F3 it's mentioned here: https://www.microsoft.com/en-us/licensing/news/m365-frontline-workers Existing Microsoft 365 F1 (and Office 365 F1) plans will be rebranded to Microsoft 365 F3 (and Office 365 F3)

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by Larryngolog** [comment]
Thanks for this update. One more remark - there is no Microsoft 365 E1 plan (Only Office 365 E1) so I think it woudl be good to remove the "E1" from this "Microsoft 365 Enterprise E1/E3" text in both tables.
