### ISSUE TITLE
Broken hyperlink in Teams/rooms/manual-update.md

### ISSUE THREAD

**Issue by digitalviper** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7126]
[OfficeDocs-SkypeForBusiness/Teams/rooms/manual-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/1ee9b1857f472a5b95352f7471c0cf21be6ea0c3/Teams/rooms/manual-update.md)

"Step 1: Download the offline app update script" (image1)

The hyperlink to download the current app update script is broken. The hyperlink still points to the previous version (4.8.19.0) the newest version is (4.8.25.0). (image2)

[Broken Link](https://go.microsoft.com/fwlink/?linkid=2151817)

![image1](https://user-images.githubusercontent.com/83303770/116290143-c6405e80-a758-11eb-93f7-2df559d11d46.png)

![image2](https://user-images.githubusercontent.com/83303770/116290441-13bccb80-a759-11eb-8a42-9ceef4068af3.png)

**Comment by dstrome** [comment]
Thanks for the feedback. We're tracking this in #7135
