### ISSUE TITLE
Clarify that the 4GB memory requirement for the teams client is for teams itself and is not a system level requirement

### ISSUE THREAD

**Issue by SHAGGAR** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7127]
The hardware requirements state that teams requires 4GB of ram.  This is technically correct, but its for teams alone, and not a system wide level.  The documentation should clarify that Teams requires a dedicated 4GB or ram ON TOP of any other system requirements.  With the current wording someone may be confused and think a computer with 4GB of total system ram is capable of running Teams, which is not possible.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29a61ff5-b3a5-158d-149a-dec344060e05
* Version Independent ID: 97fac351-a283-aaa8-cde1-fbd9cf4e8504
* Content: [Hardware requirements for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/hardware-requirements-for-the-teams-app)
* Content Source: [Teams/hardware-requirements-for-the-teams-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hardware-requirements-for-the-teams-app.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@SHAGGAR  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@SHAGGAR Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
