### ISSUE TITLE
Need additional information added

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7128]
https://docs.microsoft.com/en-us/MicrosoftTeams/teams-add-on-licensing/assign-teams-add-on-licenses#using-the-microsoft-365-admin-center

In the article it is acknowledged the limit of 20 for the "Licenses" page:
You assign licenses on the Licenses page (for up to 20 users at a time) or the Active users page

It should also be acknowledged that the "Active users page" has a limit of 40 users at a time

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed46e6b1-48c5-5302-2f38-89c315d4bff7
* Version Independent ID: 81053999-79ca-888d-38fa-8978276b6228
* Content: [Assign Teams add-on licenses to users - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-add-on-licensing/assign-teams-add-on-licenses#using-the-microsoft-365-admin-center)
* Content Source: [Teams/teams-add-on-licensing/assign-teams-add-on-licenses.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/assign-teams-add-on-licenses.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@ssmiller60  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
