### ISSUE TITLE
Unsupported Configuration Items

### ISSUE THREAD

**Issue by greganth1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#713]
The Configuring Accounts documentation does not mention that Multi-Factor Authentication (MFA) is not supported on the Skype for Business or Exchange account.
Conditional Access Policies are also not supported on the Skype for Business account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d495057-36be-b228-0483-aae89fd01666
* Version Independent ID: f02fa875-b84b-5501-5879-17ea3d017142
* Content: [Configure accounts for Skype Room Systems v2](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/room-systems-v2-configure-accounts)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/room-systems-v2-configure-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/room-systems-v2-configure-accounts.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
Honestly I'm not sure that MFA is a good idea on an SRSv2 device. @davgroom Can you comment further?

**Comment by greganth1** [comment]
I say that we don't mention that it's not supported as it is not supported.  Documentation should call that out.

**Comment by AndreaBarr** [comment]
@greganth1 Thank you for this feedback

The MFA not being supported should be included in this doccument. I am sending this over to the Teams team so we can get this addressed appropriatly. 

I was able to get this into the backlog for the Teams team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by jambirk** [comment]
The Teams team won't necessarily have the background to address this.  @davgroom Please respond.

**Comment by kenwith** [comment]
@jambirk - we can assign the item in the backlog to Dave Groom. The GitHub item is tracked in the VSO product backlog so it can be prioritized with other work and doesn't get lost on GitHub Issues like the above one did for a couple of weeks. 

Totally fine to respond and communicate here too. Just wanted to let everyone know the work is prioritized and tracked in the official product backlog.
