### ISSUE TITLE
Clarifying Landline Versus Mobile Call Completion Capability

### ISSUE THREAD

**Issue by dschuette01** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7130]
It has been our experience that call completion with an International and Domestic Calling Plan (MCOPSTN2) is generally successful to *landline* phone numbers for the countries listed on this page, but our experience reaching mobile numbers in the countries listed on this page is very inconsistent. I suspect that the routing tables being used for the MCOPSTN2 calling capability may differentiate between landline and mobile carriers, and most carrier rate tables do make this distinction. Could you please clarify whether the expected behavior is that users with the MCOPSTN2 license should in fact be able to reach *mobile* numbers in the "supported countries" list? And, if not, please indicate that caveat somewhere in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 844ea2d4-1b0a-8e37-4085-0a2ec2138887
* Version Independent ID: 0fee359f-49e9-4b7b-ad22-1a566529de9f
* Content: [Make outbound calls to these countries/regions - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/users-can-make-outbound-calls-to-these-countries-and-regions)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/users-can-make-outbound-calls-to-these-countries-and-regions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/users-can-make-outbound-calls-to-these-countries-and-regions.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
