### ISSUE TITLE
Broken links !

### ISSUE THREAD

**Issue by sgrienen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7131]
[Enter feedback here]

Link to https://go.microsoft.com/fwlink/?linkid=851168 is just dead, 404... where can I download those recovery tools please ??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13376c1b-df70-83de-8e6a-8ddc940774b5
* Version Independent ID: 6a2531ee-ac88-ee83-b858-1928d6cb4c65
* Content: [Use the Microsoft Teams Rooms recovery tool - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/recovery-tool)
* Content Source: [Teams/rooms/recovery-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/recovery-tool.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dstrome** [comment]
Thanks for the feedback. We're tracking this in #7135
