### ISSUE TITLE
SkypeRoomProvisioningScript.ps1 link is broken  

### ISSUE THREAD

**Issue by mamembrado** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7132]
Broken link referred to on [Deploy Microsoft Teams Rooms with Exchange on premises](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-exchange-on-premises)

Link in question [SkypeRoomProvisioningScript.ps1](https://go.microsoft.com/fwlink/?linkid=870105)

![image](https://user-images.githubusercontent.com/2118976/116390681-9c516f80-a81e-11eb-917a-0e9ec2845e38.png)

Many thanks

**Comment by dstrome** [comment]
Thanks for the feedback. We're tracking this in #7135
