### ISSUE TITLE
Broken link 404 Not Found

### ISSUE THREAD

**Issue by ddaanniieell9** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7135]
Issue found on the following URL - https://docs.microsoft.com/en-us/microsoftteams/rooms/manual-update contains
This is the link that results in 404 - https://go.microsoft.com/fwlink/?linkid=2151817
Customers have reported through customer support incidents being unable to download the scripts referenced in thr documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4fa80cf-0319-c006-e886-4929a508b04c
* Version Independent ID: 9d598765-fc30-17f0-6594-57de81d8aa39
* Content: [Manually update a Microsoft Teams Rooms device - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/manual-update)
* Content Source: [Teams/rooms/manual-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/manual-update.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dstrome** [comment]
Thanks @ddaanniieell9 - I've reached out to the download owner and they're working to fix the problem.

**Comment by dstrome** [comment]
This issue is resolved and the links are working again. Thanks again for reporting.
