### ISSUE TITLE
Teams Rooms Install Script

### ISSUE THREAD

**Issue by stephenregisterTJT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7136]
Link to setup script "CreateSrsMedia.ps1" is unavailable. (404)
An old copy of the script was unusable due to the required Windows 10 version being unsupported and unavailable.

While I assume it may have been removed for tweaking -- I open this Issue to bring light on the problem and seek remediation.
Thanks,
-Stephen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/console)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dstrome** [comment]
Thanks for the feedback. We're tracking this in #7135
