### ISSUE TITLE
Top Get-CsOnlineVoicemailPolicy copy link includes output as well

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7137]
The copy button brings over everything in the example text for Get-CsOnlineVoicemailPolicy, not just the actual cmdlet. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8228f9b2-a7de-abb4-6f41-70db0b3af155
* Version Independent ID: 8fd9fafb-dd76-59a8-e609-56f06d539a31
* Content: [Set up Cloud Voicemail - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-phone-system-voicemail#setting-voicemail-policies-in-your-organization)
* Content Source: [Teams/set-up-phone-system-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-phone-system-voicemail.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@StuBeck32  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@StuBeck32 thank you for reaching out. Are you suggesting adding a note to the article stipulating this?

**Comment by StuBeck32** [comment]
Nope. If there is a copy button for a cmdlet, it should only copy the cmdlet and not example text. Copying the example text makes the cmdlet not run properly. Also including PS C:\> causes issues too.

This is what is copied now by pressing the copy button

PS C:\> Get-CsOnlineVoicemailPolicy


Identity                            : Global
EnableTranscription                 : True
ShareData                           : Defer
EnableTranscriptionProfanityMasking : False
EnableEditingCallAnswerRulesSetting : True
MaximumRecordingLength              : 00:05:00
EnableTranscriptionTranslation      : True

Identity                            : Tag:Default
EnableTranscription                 : True
ShareData                           : Defer
EnableTranscriptionProfanityMasking : False
EnableEditingCallAnswerRulesSetting : True
MaximumRecordingLength              : 00:05:00
EnableTranscriptionTranslation      : True

Identity                            : Tag:TranscriptionProfanityMaskingEnabled
EnableTranscription                 : True
ShareData                           : Defer
EnableTranscriptionProfanityMasking : True
EnableEditingCallAnswerRulesSetting : True
MaximumRecordingLength              : 00:05:00
EnableTranscriptionTranslation      : True

Identity                            : Tag:TranscriptionDisabled
EnableTranscription                 : False
ShareData                           : Defer
EnableTranscriptionProfanityMasking : False
EnableEditingCallAnswerRulesSetting : True
MaximumRecordingLength              : 00:05:00
EnableTranscriptionTranslation      : True

This is what should be copied

Get-CsOnlineVoicemailPolicy

**Comment by lindspea** [comment]
@StuBeck32 thank you for clearing this up. @scanum I think we might need to direct this to support.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by StuBeck32** [comment]
There isn’t anything to create a support ticket about. Copying a power shell cmdlet is something I am fully capable of doing.

**Comment by dstrome** [comment]
@StuBeck32 - In addition to providing code snippets, we use code blocks to display text that must be formatted exactly as outputted by the command. In this case, we're showing the output after the cmdlet is run. We unfortunately are unable to control whether the copy button is visible for code blocks Having separate code blocks for the cmdlet and then the example text would make the article more difficult to read. The workaround, as you mentioned, is to copy the cmdlet name itself.

**Comment by StuBeck32** [comment]
Fair enough, so its a limitation of the website. I'm hoping that @scannum can see why creating a ticket for this would be not useful now at least.
