### ISSUE TITLE
No information about how to submit feedback on the Public Preview

### ISSUE THREAD

**Issue by rgsteele** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7138]
The article says "We also welcome feedback on any feature in public previews" but doesn't explain how to provide it. Should it just be submitted through **Help > Give Feedback** in the Teams client, or is there a specific feedback channel for Preview users? 

What about bug reports? For example, now that I have enabled the Public preview, I am seeing a pile of notifications like "Microsoft Teams AadSync has added John Smith to the team." in the General channel of our Org-wide team. These aren't supposed to appear in an Org-wide team, and when I disable the Public preview, they disappear. Is this something I should be reporting, and how?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by rgsteele** [comment]
Hi Manuela,

If you have a moment, can you let me know why this was closed without any change having been made to the document? It still doesn't explain how to provide feedback on the Public Preview of Teams.

Since the information about which article this issue is about was removed, I'll just provide the link below:

https://docs.microsoft.com/en-us/MicrosoftTeams/public-preview-doc-updates

Thanks!
