### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7143]
https://docs.microsoft.com/en-us/MicrosoftTeams/teams-add-on-licensing/assign-teams-add-on-licenses#example-script

Step 1 download link is a dead link

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed46e6b1-48c5-5302-2f38-89c315d4bff7
* Version Independent ID: 81053999-79ca-888d-38fa-8978276b6228
* Content: [Assign Teams add-on licenses to users - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-add-on-licensing/assign-teams-add-on-licenses)
* Content Source: [Teams/teams-add-on-licensing/assign-teams-add-on-licenses.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/assign-teams-add-on-licenses.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@ssmiller60 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Reeced40

**Comment by Reeced40** [comment]
@ssmiller60 thank you for reaching out and helping improve MS Docs. All the links on that page seem to be working from my side. Please can you check again and let me know which one is not working from your side.

**Comment by RAJU2529** [comment]
@scanum . link is working

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
