### ISSUE TITLE
Please include in the comparison table a column to Teams (regular) meeting capabilities

### ISSUE THREAD

**Issue by Rodrigo30Horas** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7144]
Dear all,

Lots of customers struggle to get the main differences between a Live Event and Teams meeting. It may sound too obvious for the rest of us, but I still see myself suffering to explain that a Teams meeting has Lobby/admission option, while a Live Event doesn't. Or that Live Events can have Q&A, but not a regular chat (as Teams meeting owns) between presenters and attendees.

A new column comparing this capabilities between LE and regular meetings would solve it in many ways.
For example, take a look on this university wiki explaining the differences. Something like this on an official page would solve all the questions and misunderstandings: http://www.icts.uct.ac.za/microsoft-teams-meetings-vs-live-events

Regards,
Rodrigo30Horas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@Rodrigo30Horas We will consider adding this in our next updates. Thanks
