### ISSUE TITLE
Registry Autorun Entry Incorrect for Teams Machine-Wide Installer 64-bit Version 1.4.0.8872

### ISSUE THREAD

**Issue by jnorrisatminesdotedu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7148]
Hello, we are attempting to deploy the latest Teams Machine-Wide Installer, 64-bit version 1.4.0.8872.   Our installation command is msiexec.exe /i "Teams_windows_x64.msi" /qn which is run by MECM in the SYSTEM context.

The application files successfully install at the locations:

C:\Program Files (x86)\Teams Installer\setup.json
C:\Program Files (x86)\Teams Installer\Teams.exe

However, upon a new user logging in, nothing happens.  Teams does not install into their user profile. 

Using Sysinternals Autoruns, we see the following:

HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Run
TeamsMachineInstaller    Microsoft Teams    File not found: C:\Program Files\Teams Installer\Teams.exe

Using Regedit, we browse to HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Run and see the following key/value/data:
TeamsMachineInstaller
REG_EXPAND_SZ
%ProgramFiles%\Teams Installer\Teams.exe --checkInstall --source=default

Therefore, it appears that the 64-bit MSI version 1.4.0.8872 needs to either be changed to install the Teams Installer into the location:
C:\Program Files\Teams Installer\setup.json
C:\Program Files\Teams Installer\Teams.exe

Or the autorun registry key needs to be changed to:
TeamsMachineInstaller
REG_EXPAND_SZ
%ProgramFiles(x86)%\Teams Installer\Teams.exe --checkInstall --source=default

How should we proceed?

Thank you for your help!

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
