### ISSUE TITLE
Wrong Image

### ISSUE THREAD

**Issue by marcus-ecoatm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7149]
The "Teams as part of Microsoft 365" mage link points to the wrong image.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ad624-9792-91b7-c85f-09b839b1ea44
* Version Independent ID: e8288f91-11bd-599b-8a88-074917b315a4
* Content: [Microsoft Teams IT architecture and voice solutions posters - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-architecture-solutions-posters#teams-as-part-of-microsoft-365)
* Content Source: [Teams/teams-architecture-solutions-posters.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-architecture-solutions-posters.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@marcus-ecoatm Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
