### ISSUE TITLE
Was not able to sign-in using the 64-bit version of Power BI Desktop

### ISSUE THREAD

**Issue by LycheeYum** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7151]
Just a heads-up.  I was only able to get the connection to work when using the 32-bit version of Power BI Desktop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 067e8376-df94-9a44-5263-cd1fc84879bf
* Version Independent ID: 924240c8-52c5-42db-36b8-28751f838784
* Content: [Install Power BI Connector to use CQD query templates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cqd-power-bi-connector)
* Content Source: [Teams/CQD-Power-BI-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-Power-BI-connector.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by LycheeYum** [comment]
Thank you for the response.  

I should have specified that I was referring to the Power BI Call Quality Dashboard and not the desktop client.

[https://docs.microsoft.com/en-us/microsoftteams/cqd-power-bi-connector](https://docs.microsoft.com/en-us/microsoftteams/cqd-power-bi-connector)
