### ISSUE TITLE
Link to "Pricing for audio conferencing" not working 

### ISSUE THREAD

**Issue by l-barbosa** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7152]
"Pricing for audio conferencing" leads to a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da255c7a-42a3-32be-25f6-c54a45ff7903
* Version Independent ID: ccb6f5f7-b939-b7ee-2808-cf471d748eab
* Content: [See a list of Audio Conferencing numbers - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/see-a-list-of-audio-conferencing-numbers-in-teams)
* Content Source: [Teams/see-a-list-of-audio-conferencing-numbers-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/see-a-list-of-audio-conferencing-numbers-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@l-barbosa Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@Reeced40

**Comment by Reeced40** [comment]
@l-barbosa thank you for reaching out. Would one of these links suffice? https://www.microsoft.com/microsoft-teams/audio-conferencing or https://docs.microsoft.com/MicrosoftTeams/try-or-purchase-audio-conferencing-in-office-365-for-teams

**Comment by l-barbosa** [comment]
The second link points to the page where I found the broken link.
The first link seems to contain the information I was looking for.

**Comment by Reeced40** [comment]
@scanum please can you arrange approval and merge.
