### ISSUE TITLE
Clarification for MicrosoftTeams PowerShell module

### ISSUE THREAD

**Issue by bieberium** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7155]
The documentation states to use the cmdlet below to enable a user for Direct Route:
`Set-CsUser -Identity "<User name>" -EnterpriseVoiceEnabled $true -HostedVoiceMail $true -OnPremLineURI tel:<phone number>`

Running this (adapted for my environment), it gives a string of errors. I have Global Admin permissions enabled for the account running the cmdlets. The PIM enablement was approximately 2 hours before running the commands. No obviously relevant entries in the M365 Service Health Dashboard are visible.

Screenshot of the result: 

![image](https://user-images.githubusercontent.com/10420196/116848004-fd48c100-abeb-11eb-979e-3937641aa012.png)

For better readability, a cleaned and redacted transcript is attached.
[PowerShell_transcript..ixQZ_xYJ.20210503084815.txt](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/files/6413231/PowerShell_transcript.ixQZ_xYJ.20210503084815.txt)

Can you please align the PowerShell usage / guides to the current MicrosoftTeams PowerShell module? 

Thanks a lot!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb2a9717-6565-8443-8833-f7fdce562781
* Version Independent ID: db88c4d6-5864-a481-86cf-465feb452d75
* Content: [Enable users for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-enable-users)
* Content Source: [Teams/direct-routing-enable-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-enable-users.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
