### ISSUE TITLE
Which licensing is required?

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7159]
Could you give some more information about the licensing required to be able to use the view only meeting experience?
Who needs to have the license, the view-only user or the meeting organizer?
What about O365 E3 / E5 licenses (in contrast to Microsoft 365 E3 / E5 lienses)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bf705c2-1f24-bdb5-e712-e8408b941aca
* Version Independent ID: ddedd7e0-7d85-06e0-7f20-8b83b3dccec7
* Content: [View-only meeting experience - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/view-only-meeting-experience?WT.mc_id=M365-MVP-5003326)
* Content Source: [Teams/view-only-meeting-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/view-only-meeting-experience.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by joergrenn** [comment]
Thank you for immediately closing this issue and replying with an automatic text. :(
I thought this is about providing documentation for Microsoft products. 
And licensing is in my opinion also part of a documentation. And you already mention licensing in the current document, but it is incomplete.
A service ticket is not helpful in this case.
