### ISSUE TITLE
Incorrect EventID

### ISSUE THREAD

**Issue by troeh9** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7161]
Event ID 3001 should actually be Event ID 3000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c813d7c-1789-d0c9-c833-cbdd3f60e2b8
* Version Independent ID: e5b7e6a7-2f78-dd58-b450-0d173935e26c
* Content: [Deploy Microsoft Teams Rooms management with Azure Monitor - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/azure-monitor-deploy#Alerts)
* Content Source: [Teams/rooms/azure-monitor-deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/azure-monitor-deploy.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@troeh9 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@Reeced40

**Comment by Reeced40** [comment]
@troeh9 thank you for reaching out. Are you referring to each instance in this article that should be changed to 3000?

**Comment by troeh9** [comment]
@Reeced40 correct.  example would be the query in section "https://docs.microsoft.com/en-us/microsoftteams/rooms/azure-monitor-deploy#map-custom-fields"  

Event | where Source == "SRS-App" and EventID == 3001
no data is returned when using 3001.  If you use 3000, the correct data is returned.  Any reference to 3001 should be changed to 3000
