### ISSUE TITLE
Commandline options for Preparing AD and schema updates

### ISSUE THREAD

**Issue by BrittBrian** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#717]
Please provide commandline or PowerShell instruction for performing AD Schema, Domain, and Forest Prep. S4B Administrators may not have rights to perform schema and preps in an AD environment. The Domain Admins may need to perform some of the steps to prepare the environment and hand off to S4B admins.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9131450-3053-fff6-0e01-36c7b3fd076f
* Version Independent ID: 0ad5a095-cbfd-5bcb-6f75-6f696b8215e7
* Content: [Prepare Active Directory for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/install/prepare-active-directory?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json)
* Content Source: [Skype/SfbServer/deploy/install/prepare-active-directory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/install/prepare-active-directory.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment]
@BrittBrian Thank you for this feedback

I agree we should have those instructions here. I am sending this to the Teams team so we can get this documented. 

I was able to get this into the backlog for the Teams team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.
