### ISSUE TITLE
Note is not clear

### ISSUE THREAD

**Issue by gsromeo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7176]
The note says "-MediaRelayRoutingLocationOverride - this command is not available for use in direct routing scenarios." however this page is for Direct Routing only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a420204-479f-d8c9-ea30-9f07431b4b42
* Version Independent ID: a67787ef-c6ac-74bb-baef-5835391b5949
* Content: [Direct Routing country codes - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-country-codes)
* Content Source: [Teams/direct-routing-country-codes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-country-codes.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @gsromeo, thank you for your feedback.

There is a pending update to change that note for this one:
> [!NOTE]
> MediaRelayRoutingLocationOverride parameter is reserved for use with managed carriers.

You'll see it in the next couple of days.

Related to https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/7042.

**Comment by scanum** [comment]
@gsromeo Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
