### ISSUE TITLE
this command is not available for use in direct routing scenarios.

### ISSUE THREAD

**Issue by lcansby** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7178]
About the note _"-MediaRelayRoutingLocationOverride - this command is not available for use in direct routing scenarios."_ Is this really correct? In what other scenarios should this be used, Direct Routing scenarios should be the only scenarios when you want to use this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a420204-479f-d8c9-ea30-9f07431b4b42
* Version Independent ID: a67787ef-c6ac-74bb-baef-5835391b5949
* Content: [Direct Routing country codes - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-country-codes)
* Content Source: [Teams/direct-routing-country-codes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-country-codes.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @lcansby, thank you for your feedback.

That note was incorrectly added. There is a pending update to change it for this one:
[!NOTE]
MediaRelayRoutingLocationOverride parameter is reserved for use with managed carriers.

You'll see it in the next couple of days.

Related to #7042.

**Comment by scanum** [comment]
@lcansby Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
