### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by gregmilligan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7182]
https://support.microsoft.com/office/view-live-transcription-in-a-teams-meeting-dc1a8f23-2e20-4684-885e-2152e06a4a8b (under the Allow Transcription heading) returns a Bad Request:

![image](https://user-images.githubusercontent.com/11168807/117455431-2c757000-af15-11eb-80c9-26884a220758.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@Reeced40

**Comment by Reeced40** [comment]
@gregmilligan thank you for reaching out. I've just checked the link and it seems it's been fixed in the interim. Please confirm from your side.

**Comment by Reeced40** [comment]
@scanum this can be closed thank you.
