### ISSUE TITLE
Question regarding "Supported Microsoft Teams Room systems"

### ISSUE THREAD

**Issue by Keyboard243** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7183]
Hello, I am struggling to understand the exact meaning of the "Supported Microsoft Teams Room systems" section.

From my understanding, are those devices that already have the Microsoft Teams Rooms solution installed on them. When trying to create a MS Teams Rooms Console, wouldnt the NUC be the only piece of hardware required?

I thought, that I could create a MS Teams Room Console with only the Intel NUC by installing the image from the "[Configure a MS Teams Rooms Console](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/console)" site, because I have no need for the touchscreen Interface like a "Logitech TAP". 

My question is, could I configure a MS Teams Room Console with only a Intel NUC, or do I need one of the listed touchscreen interfaces as well?

Thank you in advance and best wishes
Keyboard243

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf01435-a73b-4bf2-5845-e4cf50c4c3a2
* Version Independent ID: 166e1800-80b1-2496-7160-3040c5b23c3d
* Content: [Microsoft Teams Rooms requirements - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/requirements#feedback)
* Content Source: [Teams/rooms/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/requirements.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Keyboard243** [comment]
The answer I got, was that it is not recommended to use just the NUC instead of the bundle. It was not directly denied, that it could or may work but just that it is not recommended.
