### ISSUE TITLE
Incorrect view-only limits?

### ISSUE THREAD

**Issue by Erithano** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7196]
This seems incorrect.

After July 1st 10K overflow limit will be in effect, right? 

This text states that the temporary 20K limit will last "through the end of this year". Meaning Dec 31st 2021

Please double check this:

> If your meeting or webinar hits capacity, Teams will seamlessly scale to accommodate a 10,000-person view-only broadcast experience. Plus, during this time of increased remote work, take advantage of even larger 20,000-person broadcasts **through the end of this year**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bf705c2-1f24-bdb5-e712-e8408b941aca
* Version Independent ID: ddedd7e0-7d85-06e0-7f20-8b83b3dccec7
* Content: [View-only meeting experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/view-only-meeting-experience)
* Content Source: [Teams/view-only-meeting-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/view-only-meeting-experience.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by dariomws** [comment]
Hi @Erithano, thank you for your feedback.

It was extended until Dec 31st 2021 because the date limit was updated 3 months ago from June 30, 2021 to end of this year.

**Comment by thewrabbit** [comment]
Then the message center post about this feature hasn't been updated.

MC250956 · Published 16 Apr 2021

Up to 20,000 view-only attendees may join a meeting from late February through the end of June in order to accommodate heightened remote work scenarios. After July 1, 2021 we will support only 10,000 view only attendees.
