### ISSUE TITLE
Grammatically incorrect sentence, difficult to understand

### ISSUE THREAD

**Issue by tremeur29** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7199]
The following sentence is included in one of the "note" boxes on this page: 

> For users that there mailbox is hosted onprem it is expected to have presence delays with a maximun of an hour.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a162ef5c-3099-7f58-4178-d29e3ec2b5a7
* Version Independent ID: 6ca31e56-052d-6c62-1323-b5aaaae1f04a
* Content: [User presence in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/presence-admins)
* Content Source: [Teams/presence-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/presence-admins.md)
* Service: **msteams**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Reeced40

**Comment by scanum** [comment]
@tremeur29 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
