### ISSUE TITLE
Newest feature release

### ISSUE THREAD

**Issue by laschultz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#72]
Since Teams announced the new Guest Access feature last week, it seems this page should be updated to include the new functionality. https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/Collaborate-securely-with-anyone-in-Microsoft-Teams/ba-p/165941 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2492e210-08f9-a476-97ec-008926def961
* Version Independent ID: adcb0dd9-4a3c-b665-6e34-ce3276c89b4d
* Content: [Guest access in Microsoft Teams | Microsoft Docs](https://docs.microsoft.com/en-us/MicrosoftTeams/guest-access)
* Content Source: [Teams/guest-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access.md)
* Service: **msteams**
* GitHub Login: @laithalshamri
* Microsoft Alias: **laal**

**Comment by LolaJacobsen** [comment]
Hi, laschultz: Thanks for catching this. 

We don't generally try to keep blog posts up-to-date, but we're dedicated to  keeping our documentation up-to-date:

https://docs.microsoft.com/en-us/microsoftteams/guest-experience

The product team has been actively updating the Guest Access docset actively the past couple of months.
