### ISSUE TITLE
Excel file not updated with new calling plan countries

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7200]
Hello! Can you please update the Excel file https://www.microsoft.com/en-us/download/details.aspx?id=102271 to include new countries where Calling Plans were introduced recently?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba3ea0ca-4483-ddbf-232f-11fd5a9929e0
* Version Independent ID: d49dbcec-1614-89e9-783d-e37a86c40de8
* Content: [Availability in the Czech Republic - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-czech-republic)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-czech-republic.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-czech-republic.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @Larryngolog, thank you for your feedback.

@CarolynRowe could you kindly help here? I don't have access to https://www.microsoft.com/download/ content. Thanks!

**Comment by CarolynRowe** [comment]
I have asked @v-cichur to review.

**Comment by cichur** [comment]
Hi @Larryngolog 
I'm currently updating the spreadsheet. It takes about a week to get the updated file uploaded. I'll keep you posted once it's done.
Cindy

**Comment by dariomws** [comment]
@CarolynRowe thanks!!

**Comment by dariomws** [comment]
@cichur thank you!

**Comment by Larryngolog** [comment]
Thank you :)

Pobierz aplikację Outlook dla systemu Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Larryngolog** [comment]
Hello, where are we with the update? It has been almost a month from our conversation but no new countries are listed in the excel file.

**Comment by cichur** [comment]
@Larryngolog Thank you for your comments. I'll try to get it updated within the next week. Cindy

**Comment by dariomws** [comment]
@cichur do you have any updates here? Thanks!

**Comment by CarolynRowe** [comment]
This request is over 1 year old.  If there is still an issue, the submitter should resubmit.  Closing this issue.
