### ISSUE TITLE
Meeting Limits - DOD Cloud

### ISSUE THREAD

**Issue by caellen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7204]
Please update the Teams Meeting attendee limit specific to the DOD cloud. The previous limit was 250 users, but there is no longer clear guidance. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @caellen, thank you for your feedback.

Are you talking about "Number of people in a meeting"? I think it's still 300.

**Comment by caellen** [comment]
Yes - the number of people in a Teams meeting within the DOD O365 environment. I've included the screen capture I'm referencing below, because it only calls out a Meeting Limit for Commercial/GCC, but doesn't specify for GCCH/DOD:

***@***.***D74BC2.D5F46020]

Thanks!
Chris

Cloud Program Manager - US Navy | Customer Success | 703.334.1480 | ***@***.******@***.***>
12012 Sunset Hills Rd, Reston, VA 20190

[Microsoft Logo]

**Comment by dariomws** [comment]
@caellen thank you. It's 300. I'm applying an update to the article to include it.
