### ISSUE TITLE
Set-CsTeamsMeetingPolicy -AllowMeetingRegistration True is incorrect

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7207]
In the section allow users to create webinars I think the Powershell command is wrong. Currestly is shows
Set-CsTeamsMeetingPolicy -AllowMeetingRegistration True  (boolean)

According to the Set-CsTeamsMeetingPolicy page https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps

it should be Set-CsTeamsMeetingPolicy -AllowMeetingRegistration Everyone  or EveryoneinCompany  (string)

-AllowMeetingRegistration
Possible values:

Everyone
EveryoneInCompany
TABLE 11
Type:	String
Position:	Named
Default value:	Everyone
Accept pipeline input:	False
Accept wildcard characters:	False
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2fe730-a95d-d12d-adb8-49d1397c77c7
* Version Independent ID: 1f6077c3-6114-cb5e-8b1a-7587188f2cdf
* Content: [Set up for webinars in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-webinars)
* Content Source: [Teams/set-up-webinars.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-webinars.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by get-itips** [comment]
Hello @nikki-c Nikki, how are you?
Actually, in `2.3.1` version of the Teams Powershell module, AllowMeetingRegistration accepts a boolean value, there is a PR _soon to be merged_ updating the article for the Set-CsTeamsMeetingPolicy cmdlet here https://github.com/MicrosoftDocs/office-docs-powershell/pull/7752
Thank you
