### ISSUE TITLE
Version Française imprécise 

### ISSUE THREAD

**Issue by ThomasBIDAULT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#721]
Dans la version française l'emploi du terme "antérieur à" laisse à penser qu'une compatibilité avec Lync 2013 est possible alors que la version anglaise stipule que ce n'est pas le cas

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 515e5db8-20be-f979-5de9-3998713518dd
* Version Independent ID: a284fee3-f324-2984-431e-df14d3c4bd2d
* Content: [Configuration requise pour Skype Room Systems v2](https://docs.microsoft.com/fr-fr/skypeforbusiness/plan-your-deployment/clients-and-devices/requirements)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.fr-FR/blob/live-sxs/Skype/SfbServer/plan-your-deployment/clients-and-devices/requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @davgroom
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
@samanthaw Please look into this.

**Comment by samanthaw** [comment]
@ThomasBIDAULT @jambirk we've updated the topic for French
