### ISSUE TITLE
Recording retention period if not using Stream or OneDrive

### ISSUE THREAD

**Issue by nickp85** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7214]
This document mentions 20 days however the recording article says 21 days. Which is correct?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by nickp85** [comment]
Why is this a support ticket? Is the recording held in the Teams service for 20 or 21 days? Should be a simple answer
