### ISSUE TITLE
Incorrect Meeting Limits for A1

### ISSUE THREAD

**Issue by thewrabbit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7217]
<html>
<body>

Feature | Maximum limit
-- | --
Number of people in a meeting (can chat and call in) | 1000, includes GCC but not yet for GCCH or DoD. View-only allows for up to 20,000 listen-only participants to join a meeting in which the organizer has a license for E3/E5/A3/A5 SKU, as well as, Government (GCC, GCC High, DoD). Learn more about the View-only experience.

</body>
</html>

Please note EDU blog announcements.  This increase does not apply to A1 licenses.  The interactive participant limit remains at 300 for this license and this should be specified.

View only is only 20000 up to July when it reverts to 10000.

View only is usually only available for those SKUs listed, but will be available to all SKUs until 31 December as per MC250956

https://techcommunity.microsoft.com/t5/education-blog/what-s-new-in-microsoft-teams-for-education-february-2021/ba-p/2150231

1,000-person interactive meetings and webinars with moderation control
Beginning this month, Microsoft Teams supports interactive meetings and webinars for up to 1,000 attendees, including rich presentation options, live reactions, and moderation controls to disable chat, audio, and video for the attendees of the event.

**This will be available this month for Microsoft Education A3 and A5 customers.**

https://techcommunity.microsoft.com/t5/education-blog/35-new-features-in-teams-to-get-excited-about-now-through-august/ba-p/2318238

One thousand person interactive meetings and webinars
Soon Microsoft Teams will support interactive meetings and webinars for up to 1,000 attendees, including rich presentation options, live reactions, and moderation controls to disable chat, audio, and video for the attendees of the event. **This will be available for Microsoft Education A3 and A5 customers.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@thewrabbit Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
