### ISSUE TITLE
ConferenceID Reset is no longer available

### ISSUE THREAD

**Issue by armazing** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#722]
I do not see a Reset option under ConferenceID

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 029e94a5-7bd8-5880-c736-9dda41199cd6
* Version Independent ID: 1f992ff2-d0ca-aac7-cc43-01bb705280fa
* Content: [Reset a conference ID for a user in Skype for Business Online](https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/reset-a-conference-id-for-a-user)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/reset-a-conference-id-for-a-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/reset-a-conference-id-for-a-user.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@armazing Thank you for this feedback

I want to make sure you have the correct reset abilities. Support can help get this to resolution.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
