### ISSUE TITLE
Why are we publishing this if it isn't available yet? 

### ISSUE THREAD

**Issue by Strick1969** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7222]
Why are we publishing this if it isn't available yet? 

Feature | Maximum limit
-- | --
Number of people in a meeting (can chat and call in) | 1000, includes GCC but not yet for GCCH or DoD. View-only allows for up to 20,000 listen-only participants to join a meeting in which the organizer has a license for E3/E5/A3/A5 SKU, as well as, Government (GCC, GCC High, DoD). Learn more about the View-only experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Strick1969 
how are you? Hope you are doing good.
As far as I know, this has been already rolled out to Commercial, EDU and GCC.
Hope this information helps you,

**Comment by cichur** [comment]
Hello @Strick1969,
The feature rolled out on May 10, 2021. 
Cindy
