### ISSUE TITLE
What happens when a team is archived/unarchived?

### ISSUE THREAD

**Issue by DmitryVorobyov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7224]
This article should contain (or refer to) an official description of everything that happens in the background when a team is archived or un-archived (e.g. Team is removed from "active" navigation in Teams, Owner has an option to make the underlying site read-only, etc.) .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf689b7-a7c1-121f-578e-029e8a89c4f0
* Version Independent ID: 7e6b449e-bd77-2fc4-2c3d-1f2e364e1b76
* Content: [Archive or delete a team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/archive-or-delete-a-team?source=docs)
* Content Source: [Teams/archive-or-delete-a-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/archive-or-delete-a-team.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@DmitryVorobyov Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
