### ISSUE TITLE
No information about how to submit feedback on the Public Preview

### ISSUE THREAD

**Issue by rgsteele** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7228]
The article says "We also welcome feedback on any feature in public previews" but _doesn't explain how to provide it_. 

Should it just be submitted through **Help > Give Feedback** in the Teams client, or is there a specific feedback channel for Preview users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5f1cdd1-09ff-f95d-6d50-e7880d34020f
* Version Independent ID: 59219640-305b-30c1-bc10-87e2633d95db
* Content: [Public preview in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/public-preview-doc-updates)
* Content Source: [Teams/public-preview-doc-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/public-preview-doc-updates.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by rgsteele** [comment]
Hi @scanum, can you please explain why this issue was closed without the documentation having been updated? I am very confused. Thanks!
