### ISSUE TITLE
Install Apps in Meetings

### ISSUE THREAD

**Issue by TobiasAT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7229]
I reference to message center post MC252940 "Admins can install Apps in Meetings", or roadmap ID 81086.
I don't understand the benefit of this behaviour. 

1. Why is this limited to admins, and which admin roles? Global Admin, sure, Teams Service Admin is not longer valid. Is it Teams Administrator, or another of the Teams admin roles? 
2.  You noted this option is limited to admins, but users can open an app and select "Add to a meeting". Then the app was added without an admin interaction. 

What do I miss to understand the message center post in a correct way?

Thanks Tobias 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f91604a-35b0-dfbb-55b2-b601cb0841b0
* Version Independent ID: 84bcd0d7-b4ed-f13e-c84b-2ec6a7661ae9
* Content: [Manage app setup policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/teams-app-setup-policies)
* Content Source: [Teams/teams-app-setup-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-setup-policies.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by TobiasAT** [comment]
I disagree. These questions are not related to support. These questions are missing information in your documentation about app setup policies and should be updated. Also, it's not very customer focused to just copy & paste a predefined text for the majority of questions like in a call center.
