### ISSUE TITLE
Set-CsOnlineDialInConferencingUser 

### ISSUE THREAD

**Issue by armazing** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#723]
I was able to run Set-CsOnlineDialInConferencingUser cmdlet for a user to set conferenceID however, when I tested it, it still shows conferenceID as Dynamic and it did not apply the conferenceID I set in powershell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04f02841-8def-d3af-f4bf-cd92654b6364
* Version Independent ID: bf92954c-cc85-d5a7-f190-0636467a2490
* Content: [See, change, and reset a conference ID assigned to a user in Skype for Business Online](https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/see-change-and-reset-a-conference-id-assigned-to-a-user)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/see-change-and-reset-a-conference-id-assigned-to-a-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/see-change-and-reset-a-conference-id-assigned-to-a-user.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@armazing Thank you for your feedback. 

I want to make sure we get this script working for you. Support will be able to handle this issue to resolution.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
