### ISSUE TITLE
Teams Machine-Wide Installer Uninstalling Teams

### ISSUE THREAD

**Issue by dkattan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7231]
# Overview

The Teams Machine-Wide installer hangs when attempting to install a new version without first removing the old one

To mitigate this, you must first uninstall the existing machine-wide installer before installing the new one
- This places 2 values in the registry that will perform an uninstall the next time the user logs in
  - HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run TeamsMachineUninstallerLocalAppData
  - HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run TeamsMachineUninstallerProgramData

Installing the new version of the MSI DOESN'T REMOVE THE PREVIOUSLY CREATED UNINSTALL VALUES and simply adds a third value that will perform the install as the user.
  - HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run TeamsMachineInstaller
  - 
At logon, Windows processes these values in alphabetical order, meaning they get processed in this order:

1. TeamsMachineInstaller
2. TeamsMachineUninstallerLocalAppData
3. TeamsMachineUninstallerProgramData

# Suggested Fix
Have the MSI remove TeamsMachineUninstallerLocalAppData and TeamsMachineUninstallerProgramData during installation to prevent this from happening.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by rwllr** [comment]
Can confirm have seen this affect us as well.
