### ISSUE TITLE
powershell instructions have minor typo -> which makes them fail (True should be $true)

### ISSUE THREAD

**Issue by TheBigBear** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7232]
The powershell instructions on this page have a minor Typo twice that makes them FAIL. They use 'True' when they should use '$true' instead. Which results in powershell errors in red color on the cmd line. 

The listed cmd:
```
Set-CsTeamsMeetingPolicy -AllowMeetingRegistration True
```
results in 
```
Cannot convert 'System.String' to the type 'System.Boolean' required by parameter 'AllowMeetingRegistration'.
    + CategoryInfo          : InvalidArgument: (:) [Set-CsTeamsMeetingPolicy], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Microsoft.Rtc.Management.Internal.SetTeamsMeetingPolicyCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com
```

And the cmd given 
```
Set-CsTeamsMeetingPolicy -AllowPrivateMeetingScheduling True
```
results in:
```
Cannot convert 'System.String' to the type 'System.Boolean' required by parameter 'AllowPrivateMeetingScheduling'.
    + CategoryInfo          : InvalidArgument: (:) [Set-CsTeamsMeetingPolicy], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Microsoft.Rtc.Management.Internal.SetTeamsMeetingPolicyCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com
```

But if 'True' is replaced with '$true' in those two cmd they work as intended.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2fe730-a95d-d12d-adb8-49d1397c77c7
* Version Independent ID: 1f6077c3-6114-cb5e-8b1a-7587188f2cdf
* Content: [Set up for webinars in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-webinars)
* Content Source: [Teams/set-up-webinars.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-webinars.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by scanum** [comment]
@TheBigBear Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@scanum the article has been already fixed. please close. thanks
