### ISSUE TITLE
404 error while running creatersrs script

### ISSUE THREAD

**Issue by donisboon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7235]
I get the following when running the script.  THe link its going to is not working

[ 0] Surface Pro 4
[ 1] Surface Pro (2017)
[ 2] Surface Pro 6
Selected option 2.
PS>TerminatingError(Resolve-Url): "Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found.""

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/console#Prep_Media)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by jhochwald** [comment]
@donisboon I do have the same issue with the Surface Surface Pro 4 (0) and Surface Pro 6 (2) :(

**Comment by jhochwald** [comment]
Here is what the Log says:
`
VERBOSE: Redirecting to Surface Pro Dock
VERBOSE: Processing nested menu entry.
[ 0] Surface Pro 4
[ 1] Surface Pro (2017)
[ 2] Surface Pro 6
Selected option 0.
VERBOSE: Processing download menu entry.
PS>TerminatingError(Resolve-Url): "Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found.""
>> TerminatingError(Resolve-Url): "Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found.""
>> TerminatingError(Resolve-Url): "Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found.""
>> TerminatingError(Resolve-Url): "Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found.""
>> TerminatingError(Resolve-Url): "Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found.""
>> TerminatingError(Resolve-Url): "Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found.""
**********************
Windows PowerShell transcript end
End time: 20210518182622
**********************
`
Not much, the URL isn't shown :(

**Comment by donisboon** [comment]
I get the same as well.  It seemes there's a download with either an outdated link or download issue.  I've tried at different locations to confirm its not network issue

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by falccc** [comment]
This is still an issue.  Please don't just close issues without resolving them!

**Comment by hkystar35** [comment]
Seeing the same in my org, too
```
Please indicate what drivers you wish to use with this installation.
[ 0] Logitech SmartDock
..

[ 1] Surface Pro (2017)
```

Running with `-Verbose` and `-debug` still does not indicate which URL is non-responsive. Transcript log file also does not indicate the failed URL, either.
