### ISSUE TITLE
Missing vendor name for UC-Pxx Teams Phones

### ISSUE THREAD

**Issue by grahammw** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7238]
The **Currently certified Teams phones** starts off with UC-Pxx devices.  These should be as below including the vendor.

**Crestron** UC-P10-T (with and without handset)
**Crestron** UC-P10-C-T (with and without handset)
**Crestron** UC-P8-C-T (with and without handset)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaaef9e1-8f1c-ebf0-7856-4c007342a2c3
* Version Independent ID: 3eaf671f-375e-8787-9c66-3947c3606559
* Content: [Devices for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/devices/teams-ip-phones)
* Content Source: [Teams/devices/teams-ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/teams-ip-phones.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Thanks for reporting @grahammw
