### ISSUE TITLE
Mac Teams client is now supported for GCCH

### ISSUE THREAD

**Issue by aandrew129** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7244]
I believe the note on this page stating that Teams for Mac is unsupported is incorrect. Teams for Mac has worked for several months in GCCH, so the note can probably safely be removed.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by aandrew129** [comment]
Sorry for the misunderstanding - it DOES work in our testing in a GCCH environment, so no need for a ticket. :)
