### ISSUE TITLE
[Doc-Bug] Teams app store for Guest users 

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7251]
Hi Team,
Following was mentioned in the documentation:
![image](https://user-images.githubusercontent.com/69682598/118810218-3c079800-b8c9-11eb-88cf-8862f8e734d5.png)

But if Guest user try to access the URL with below, able to see the app store and able to install the apps.
https://teams.microsoft.com/_#/apps?intent=2&category=16&autoNavigationOnDone=true&skipInstalledSuccess=false&filterByPersonal=false&storeLaunchFromChat=false

So, documentation change required to indicate App store is hidden for Guest users but still can access using direct URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0735d322-f6f5-7cc8-9994-1420e3fb7baa
* Version Independent ID: f9b25b51-eb9c-63fa-b30e-e1490c8d31b6
* Content: [Teams apps behavior for non-standard users - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/non-standard-users)
* Content Source: [Teams/non-standard-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/non-standard-users.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by SubbaReddi** [comment]
I see the documentation is updated:
![image](https://user-images.githubusercontent.com/69682598/119624533-e3834e00-be26-11eb-899f-67b20d1238b8.png)
