### ISSUE TITLE
[Doc-Bug] App setup policy for Guest users

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7252]
Hi,
Following was mentioned in documentation:
![image](https://user-images.githubusercontent.com/69682598/118810850-f7c8c780-b8c9-11eb-9e14-e99bfd0bd724.png)

But if we add app to app setup policy under installed apps, then app is installing for Guest users. So, the statement in documentation is outdated: **Setup policies don't apply to guest users.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0735d322-f6f5-7cc8-9994-1420e3fb7baa
* Version Independent ID: f9b25b51-eb9c-63fa-b30e-e1490c8d31b6
* Content: [Teams apps behavior for non-standard users - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/non-standard-users)
* Content Source: [Teams/non-standard-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/non-standard-users.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by SubbaReddi** [comment]
I see the documentation is updated:
![image](https://user-images.githubusercontent.com/69682598/119624733-11689280-be27-11eb-886a-00334673f26a.png)
