### ISSUE TITLE
Missing a step (Set EnterpriseVoiceEnabled = true)?

### ISSUE THREAD

**Issue by jasonshave** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7258]
Isn't it necessary to set the account's `EnterpriseVoiceEnabled` property to `True`? Without this, the account is unable to use the "dialpad" feature and results in an error on the IP phone.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ab5215-f24f-75cf-bb92-16ac0ff5e5ca
* Version Independent ID: 701cc58f-d2ea-cbb6-f5fc-47b9fbfb1119
* Content: [Set up the Common Area Phone license - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-common-area-phones)
* Content Source: [Teams/set-up-common-area-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-common-area-phones.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
