### ISSUE TITLE
Broken Link in Teams Rooms Install Documentation

### ISSUE THREAD

**Issue by PvilleStang** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7267]
The PS1 script download link is broken, goes to a 404 page.  Kinda throws a wrench in my day...

https://download.microsoft.com/download/9/0/D/90D4826A-9FD2-47D2-B911-97BF1737F4F7/CreateSrsMedia.ps1

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/console)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by lindspea** [comment]
@PvilleStang thank you for reaching out and helping improve MS Docs. It seems like it's working now as I managed to download the script. Please check from your side and let me know.

**Comment by RAJU2529** [comment]
@PvilleStang . The link is working, i downloaded the script.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
