### ISSUE TITLE
Codec

### ISSUE THREAD

**Issue by dschuette01** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7268]
I have tried to look everywhere I can think of to find the CodecPriority attribute and the ExcludedCodec attribute as described in the documentation on this page, but I am not seeing this anywhere. To the extent that this attribute may exist at all, it seems it is not a mutable attribute. 

Could this be addressed in the documentation? Our SBC provider is telling us to change the codec Teams is sending, but this mysterious "CodecPriority" attribute is not mentioned in any other place I can find on MicrosoftDocs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad7d5051-1177-c5cf-bf28-8639d7b6fbd1
* Version Independent ID: 2a9aa4e1-3767-cd46-50fe-f9dd8b0997be
* Content: [Connect your Session Border Controller (SBC) to Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-connect-the-sbc)
* Content Source: [Teams/direct-routing-connect-the-sbc.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-connect-the-sbc.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
