### ISSUE TITLE
Assign Voice Routing Policy to more than one user (but not Global)

### ISSUE THREAD

**Issue by dschuette01** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7269]
Could the documentation please be updated to reflect that as far as I am aware, it is currently impossible to assign a voice routing policy to more than one user at a time? This cannot be accomplished either by PowerShell nor by in the Teams Admin Center. The documentation for the policy packages does specifically call out that Voice Routing policies cannot be assigned this way.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d277994f-f0bb-ed3b-a94c-460c7f033abf
* Version Independent ID: 7a2b1511-a35a-18e4-611a-db0093d034b4
* Content: [Configure voice routing for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-voice-routing)
* Content Source: [Teams/direct-routing-voice-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-voice-routing.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @dschuette01 how are you?

I was able to assign a Voice Routing Policy piping the output of `Get-CsOnlineUser`, so if for example, you use a `-filter`, you can assign to more than one user and not globally, an example similar to this is [this one](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csonlinevoiceroutingpolicy?view=skype-ps#---------------------------example-3---------------------------).

Please let me know if I understood well your inquiry,

Hope this information helps you

**Comment by scanum** [comment]
@dschuette01 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
