### ISSUE TITLE
Clarification of Messages Meanings

### ISSUE THREAD

**Issue by hoggm2** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7273]
In the document:
"Channel messages is the number of unique messages that the user posted in a Team channel during the specified time period.
Post messages is the number of unique post messages that the user posted in a team channel during the specified time period."

I do not believe the text is clear enough to explain the distinction.

And is there a distinction between Team (with a capital) and team? Both are used above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2758a3d6-c646-dcb0-2a31-c7b9b84e780b
* Version Independent ID: 8704c9fe-f8b0-82d2-bd83-3fd1a9ad638d
* Content: [Microsoft Teams user activity report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report)
* Content Source: [Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by get-itips** [comment]
Hello @hoggm2 how are you? Hope you are doing good 👍 
Please see [here](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4545), hope this clarifies better for you.
About the capitalization, will propose an edit to clarify.
Thank you
