### ISSUE TITLE
The Automatically admit people section needs an update

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7276]
The Automatically admit people section needs an update as there are two a new settings:
Invited Users only - only people who have been directly invited to the meeting
People in my organization - internal user that excluded Guests & Azure ADB2B users. Screenshot of Teams admin centre included.

![image](https://user-images.githubusercontent.com/69439002/119146537-a1cb5f80-ba42-11eb-8f44-a202de05890d.png)

Also it may be worth adding in how the names are shown on the meeting option page to the end user are they are different from what is seen in the Teams Admin centre. See screenshot
![image](https://user-images.githubusercontent.com/69439002/119147043-21592e80-ba43-11eb-96c5-149fa715baf7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by dariomws** [comment]
Hi @nikki-c, thank you for your feedback.

I'm applying an update, and this is how the table probably will look in a couple of days once approval:

|Setting value  |Join behavior |
|---------|---------|
|**Everyone**   |All meeting participants join the meeting directly without waiting in the lobby. This includes authenticated users, external users from trusted organizations (federated), guests, and anonymous users.     |
|**People in my organization and guests**    |Authenticated users from within the organization, including guest users, join the meeting directly without waiting in the lobby. Users from trusted organizations and anonymous users wait in the lobby. This is the default setting.           |
|**People in my organization, trusted organizations, and guests**     |Authenticated users within the organization, including guest users and the users from trusted organizations, join the meeting directly without waiting in the lobby. Anonymous users wait in the lobby.   |
|**People in my organization**  |Authenticated users from within the organization, excluding guest users, join the meeting directly without waiting in the lobby. Guests and users from trusted organizations and anonymous users wait in the lobby.|
|**Organizer only**    |Only meeting organizers can join the meeting directly without waiting in the lobby. Everyone else, including authenticated users within the organization, guest users, users from trusted organizations and anonymous users must wait in the lobby. On the Teams client meeting options page, it appears as "Only me".            |
|**Invited users only**    |Only the participants invited by the organizer in the meeting invite join the meeting directly without waiting in the lobby. Everyone else must wait in the lobby. On the Teams client meeting options page, it appears as "People I invite".         |
