### ISSUE TITLE
Mistake concerning Autoattendant

### ISSUE THREAD

**Issue by boombasstic** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7278]
In the article it says 

Cloud auto attendants | Lets you create a menu system that enables external and internal callers to locate and place or transfer calls to company users or departments in your organization.Note that users&nbsp;do not&nbsp;need to be voice enabled to receive calls from the auto attendant.
-- | --
Cloud call queues | Lets you configure how call queues are managed for your organization: for example, set up greetings and music on hold, search for the next available call agent to handle the call, and so on.Note that users&nbsp;do&nbsp;need to be voice enabled to receive calls from a call queue.

But i cannot receive call from auto attendant if user is not voice enabled, i get an error message 
"You are trying to link user but they aren't enterprise voice-enabled."

I created a support ticket. They told me that i need actually to have voice enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cfead3c-b0d8-c22a-aa22-63e79fe53ed3
* Version Independent ID: 10745875-3d3e-42bb-e324-ff4c83968ccf
* Content: [Here's what you get with Phone System - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/here-s-what-you-get-with-phone-system)
* Content Source: [Teams/here-s-what-you-get-with-phone-system.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/here-s-what-you-get-with-phone-system.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
