### ISSUE TITLE
Traduction du nom du vendeur Ribbon en Ruban 

### ISSUE THREAD

**Issue by dgricourt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#729]
Bonjour,
Il semble y avoir une traduction automatique du nom du vendeur Ribbon (Ribbon Communications http://www.rbbn.com) en "Ruban" dans la liste des équipements supports par Teams. Vous est-il possible d'éviter la traduction automatique pour cet element.

Cordialement,

David GRICOURT
Ribbon France

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 1b1a1c01-10a9-7f69-1c7b-1a566b0f5112
* Version Independent ID: 329ee759-40fc-98fb-b91e-87786c63024b
* Content: [Liste de contrôleurs de frontière de Session certifié pour le routage Direct](https://docs.microsoft.com/fr-fr/microsoftteams/direct-routing-border-controllers)
* Content Source: [Teams/direct-routing-border-controllers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.fr-FR/blob/live-sxs/Teams/direct-routing-border-controllers.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
@samanthaw  -- can you please look into this? Machine translation is mistranslating a vendor company's name on this page. The correct vendor name Ribbon Communications is being mistranslated as Ruban Communications.

**Comment by samanthaw** [comment]
@dgricourt @jambirk the vendor name is now fixed in the French topic
