### ISSUE TITLE
Incorrect value for True

### ISSUE THREAD

**Issue by sdbyrd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7292]
Need to use the value $true rather than True for this to take effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2fe730-a95d-d12d-adb8-49d1397c77c7
* Version Independent ID: 1f6077c3-6114-cb5e-8b1a-7587188f2cdf
* Content: [Set up for webinars in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-webinars)
* Content Source: [Teams/set-up-webinars.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-webinars.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by dariomws** [comment]
@sdbyrd thank you for your feedback.

I've been managing other issues with the same feedback, and it'll be fixed once the following pull request is merged:
#7303

(really a couple of hours after it's merged)
