### ISSUE TITLE
Fix typo for Giphy content rating

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7296]
It says "**Gipsy** content rating" instead of "**Giphy** content rating"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34f3188-0af5-f972-9d28-959f5f7866a2
* Version Independent ID: fab26e11-a729-92a4-3ea6-8668dca55dd0
* Content: [Manage messaging policies in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/messaging-policies-in-teams)
* Content Source: [Teams/messaging-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/messaging-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@npherson Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
