### ISSUE TITLE
TeamsIn did not receive media renegotiation for holding call

### ISSUE THREAD

**Issue by mozziemozz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7299]
Hello @FilippSe 
We have been using this script to monitor our Direct Routing Infrastructure (SBCs) for the past few months. Oddly, since two or three weeks the script stopped working and it's showing the following error message on every test call:

```
Test: Outbound to Inbound

result.state result.code result.phrase
------------ ----------- -------------
failed              1511 TeamsIn did not receive media renegotiation for holding call


teamsOut.chainId                     teamsOut.sipCallId               teamsOut.trunkFqdn      teamsOut.callEndReasonPhrase teamsOut.callEndReason teamsOut.callEndSubReason teamsOut.state teamsOut.code teamsOut.callSetupTimeMs teamsOut.callStartTime
----------------                     ------------------               ------------------      ---------------------------- ---------------------- ------------------------- -------------- ------------- ------------------------ ----------------------
323cb595-a8dc-4a53-affd-8325afc65932 7ef38bd7476d5c1e8545ab3a624c0501 tc001.connect.domore.ch LocalUserInitiated                                0                         0 signedOut                                        2431 2021-05-25T06:07:53.9614183Z


teamsIn.chainId                      teamsIn.lastAction teamsIn.state teamsIn.code teamsIn.phrase                                               teamsIn.callSetupTimeMs teamsIn.callStartTime        teamsIn.flow
---------------                      ------------------ ------------- ------------ --------------                                               ----------------------- ---------------------        ------------
e4a7ce98-2cc2-4ee7-bbeb-fcf39cb38cea holdingCall        failed                1511 TeamsIn did not receive media renegotiation for holding call                    2285 2021-05-25T06:07:53.9613834Z inbound
```

We use 2 dedicated tenants which are only used for monitoring our calls / the SIPTester Script. Logging in with the test users from the script manually and placing calls (even with call hold/resume) through the Teams Client works without any issues. A Trace on the SBC didn't show any errors as well.

I also checked the Teams Admin Center Logs and they show no issues as well. Both the incoming and outgoing calls are marked with Final SIP Code 200 (OK). The Correlation IDs match the ones from the example above. We also tested different DCs like Amsterdam and Dublin. (EMEA-AM) and (EMEA-DB)

Since placing calls manually works fine and also TAC and SBC Trace show no issues, we suspect that something might have changed on the SIP Tester API / Endpoint.  From the script: (https://api.pstnmonitoring.skype.com/v1/sip-tester/test-suites or https://calltester.pstnhub.microsoft.com)

Could you please take a look and try to reproduce the issue? Feel free to contact me if you need any more information or want to take a look at our own script, which calls the SIPTester Script with the required parameters.

Thank you and best regards,
Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99036b5e-f358-fda3-d9b1-1279952b59a5
* Version Independent ID: 9ea42c59-7db5-9c66-ef58-98b4909ccd10
* Content: [PowerShell script to test Direct Routing Session Border Controller connections - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sip-tester-powershell-script)
* Content Source: [Teams/sip-tester-powershell-script.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sip-tester-powershell-script.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by pentp** [comment]
I checked the call and it seems like the SBC does not propagate hold (re-INVITE with a=inacitve) to the other leg. That's why the test is failing at the hold/resume step.
You should check your SBC configuration to see if it can be fixed, but if this is not possible then there's a workaround to disable hold/resume validation by modifying SipTesterClient.ps1:
```diff
-$teamsOut = @{username = $teamsOutUsername; password = $teamsOutPassword; dataCenter = $TeamsOutDataCenter}
+$teamsOut = @{username = $teamsOutUsername; password = $teamsOutPassword; dataCenter = $TeamsOutDataCenter; holdCount=0}
```
This allows you to validate the rest of the call flow, but this is not a supported scenario.
