### ISSUE TITLE
Ignite aka.ms links appear to be broken on this page

### ISSUE THREAD

**Issue by scapero** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7307]
Ignite aka links appear to be broken on this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 026656ef-3309-f381-532c-51b3b443f206
* Version Independent ID: 8fb11047-1cb5-68de-b8cc-3e6a882ab3c0
* Content: [Teams sessions at Ignite 2020 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/ignite-2020-landing-page?source=docs)
* Content Source: [Teams/ignite-2020-landing-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/ignite-2020-landing-page.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@scapero Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@cichur None of the .ms links are working in the first section 'Key Segments'. Please can you assist as to which links are correct and I can do the PR.

**Comment by cichur** [comment]
Hi @lindspea 
Will you look at the Ignite Archives? I believe you can find the links there. I appreciate your help. https://myignite.microsoft.com/archives

**Comment by lindspea** [comment]
@scanum this can be closed thanks.
