### ISSUE TITLE
Typo in commands.

### ISSUE THREAD

**Issue by JoakimOfficial** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7309]
[Enter feedback here]
True should be $true.

/Joakim

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2fe730-a95d-d12d-adb8-49d1397c77c7
* Version Independent ID: 1f6077c3-6114-cb5e-8b1a-7587188f2cdf
* Content: [Set up for webinars in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-webinars?fbclid=IwAR0D4cfOZ0_nrYkuu_pvpo0IlNE1ihpwSAXqYywy0RrrcftpCNh4t-1oPpM)
* Content Source: [Teams/set-up-webinars.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-webinars.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by scanum** [comment]
@JoakimOfficial Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
@JoakimOfficial thank you for your feedback.

I've been managing other issues with the same feedback, and it'll be fixed once the following pull request is merged:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/7303

(really a couple of hours after it's merged)

**Comment by scanum** [comment]
@JoakimOfficial Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
