### ISSUE TITLE
WhoCanRegister default value

### ISSUE THREAD

**Issue by shtakeda** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7312]
Webinar has been rolled out to my tenant. WhoCanRegister value was set EveryoneInCompany by default. But, docs says "By default, WhoCanRegister is enabled and set to Everyone". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2fe730-a95d-d12d-adb8-49d1397c77c7
* Version Independent ID: 1f6077c3-6114-cb5e-8b1a-7587188f2cdf
* Content: [Set up for webinars in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-webinars#configure-who-can-register-for-webinars)
* Content Source: [Teams/set-up-webinars.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-webinars.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by scanum** [comment]
@shtakeda Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@shtakeda thank you for reaching out. Who can register for a webinar By default anyone can register, but the IT admin can restrict registration to people in your org. You can also choose to restrict registration when you schedule the webinar. If you want to schedule a public webinar but can’t, contact your IT admin.

**Comment by dariomws** [comment]
Hi @shtakeda, thank you for your feedback.

New sentence:
"**WhoCanRegister** is enabled and set to **Everyone in the organization** for the **Global (Org-wide default)** policy."

I'm applying an update to the article, for more information, see:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7393

**Comment by dariomws** [comment]
@shtakeda sorry I made a mistake. The default value is Everyone for the Global policy.

If you reset it you will see Everyone for WhoCanRegister:
![image](https://user-images.githubusercontent.com/33589238/122555684-e4c92480-d03a-11eb-9491-176887d532ad.png)

Please test it in a demo or lab tenant.

I'm applying an update to the article:
"By default, **WhoCanRegister** is enabled and set to **Everyone** for the **Global (Org-wide default)** policy."

**Comment by shtakeda** [comment]
@dariomws I checked the same on the other tenant, and confirmed the default value was set to Everyone. Thanks for your support. Please close the case.
