### ISSUE TITLE
Article references the SkypeOnlineConnector module - Should be updated to reflect the Teams module

### ISSUE THREAD

**Issue by MacKender** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7318]
[Enter feedback here]
From the article: 
"Note
Before you can run these cmdlets you must be connected to Skype for Business Online PowerShell. For more information, see Manage Skype for Business Online with Microsoft 365 or Office 365 PowerShell."

I don't see any commands or arguments not supported by the Teams PowerShell module so why not reference that module, given that Skype Online is soon-to-be dead in the water? Also, "[The Teams PowerShell public release version 2.0 or higher includes all Skype for Business Online Connector cmdlets, providing a single module for Teams PowerShell management.](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-overview)" 

Reference: https://techcommunity.microsoft.com/t5/microsoft-teams/skype-for-business-online-connector-retires-in-february-2021/m-p/2005963
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2fe730-a95d-d12d-adb8-49d1397c77c7
* Version Independent ID: 1f6077c3-6114-cb5e-8b1a-7587188f2cdf
* Content: [Set up for webinars in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-webinars)
* Content Source: [Teams/set-up-webinars.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-webinars.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by MacKender** [comment]
I'm merely pointing out that the doc in question is using deprecated technology (the Skype PS module) and should be updated to reflect what's current, the Teams Online 'MicrosoftTeams' PS module. No need for support ;-)
