### ISSUE TITLE
PowerShell commands should use Booleans not Strings

### ISSUE THREAD

**Issue by ShadowCyclist** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7322]
The PowerShell command on this page use the strings "True" when they should be Boolean variables $true

For example:
Set-CsTeamsMeetingPolicy -AllowPrivateMeetingScheduling True

Should be:
Set-CsTeamsMeetingPolicy -AllowPrivateMeetingScheduling $true

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2fe730-a95d-d12d-adb8-49d1397c77c7
* Version Independent ID: 1f6077c3-6114-cb5e-8b1a-7587188f2cdf
* Content: [Set up for webinars in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-webinars)
* Content Source: [Teams/set-up-webinars.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-webinars.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by scanum** [comment]
@ShadowCyclist Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
@ShadowCyclist thank you for your feedback.

I've been managing other issues with the same feedback, and it'll be fixed once the following pull request is merged:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/7303

(really a couple of hours after it's merged)
