### ISSUE TITLE
See rates for where you want to call, doesn't actually display rates

### ISSUE THREAD

**Issue by ThomasSaintThomas** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7325]
[Enter feedback here]
The phrase "See rates for where you want to call" only occurs one time on this page, in the following sentence; 
"If you're wondering what the cost of the calls are for Calling Plans, see Cloud-Based Phone System for Voice Calling (scroll down to "See rates for where you want to call")."

So obviously that's broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d52a9779-b72d-dea0-eac2-6c04a8c282eb
* Version Independent ID: d3c3d968-9e54-ec42-3438-9320e23d68b9
* Content: [What are Communications Credits? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/what-are-communications-credits)
* Content Source: [Teams/what-are-communications-credits.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-communications-credits.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by RAJU2529** [comment]
@ThomasSaintThomas . this **Cloud-Based Phone System for Voice Calling** is  working fine .

![Capture](https://user-images.githubusercontent.com/3296790/119991777-71a63280-bfe7-11eb-9701-46770f877ba2.JPG)

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
