### ISSUE TITLE
CreateSRSMedia.ps1 script driver 404 failure

### ISSUE THREAD

**Issue by jaypg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7327]
Error: The script is unable to download Surface tablet drivers. Error message -
>Resolve-Url : Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
>At C:\Temp\MeetingRoomTool\CreateSrsMedia.ps1:724 char:13
>      $res = (Resolve-Url $url)
>              ~~~~~~~~~~~~~~~~
>      CategoryInfo          : NotSpecified: (:) [Resolve-Url], MethodInvocationException
>      FullyQualifiedErrorId : WebException,Resolve-Url

To reproduce:
1. OEM or Enterprise: - Enterprise
2. Please indicate what drivers you wish to use with this installation. - [ 0] Logitech SmartDock, [ 1] Surface Pro (2017)

Confirmed returned 404 of "https://download.microsoft.com/download/4/C/7/4C7DA85D-03DE-4B89-B8E0-386437331C46/SurfacePro_Win10_16299_1806007_3.msi" in browser.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
