### ISSUE TITLE
Missing details on the "Automatically Admit people" setting 

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7333]
Missing options - need to add to table
- People in my organization, trusted organizations, and guests
- Invited Users Only

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4521de2b-1aae-93de-ee1a-222146194700
* Version Independent ID: b4f9087c-e1a3-8b47-917c-7c294d46fcca
* Content: [Manage meeting policies for participants and guests - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/meeting-policies-participants-and-guests?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/meeting-policies-participants-and-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-participants-and-guests.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @danmyhre
