### ISSUE TITLE
Text to boolean in example strings

### ISSUE THREAD

**Issue by FrankSchuurman68** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7334]
When copy paste content from page into Powershell, the boolean does not compute the text string.

PS C:\WINDOWS\system32> Set-CsTeamsMeetingPolicy -AllowPrivateMeetingScheduling True
Cannot convert 'System.String' to the type 'System.Boolean' required by parameter 'AllowPrivateMeetingScheduling'.
    + CategoryInfo          : InvalidArgument: (:) [Set-CsTeamsMeetingPolicy], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Microsoft.Rtc.Management.Internal.SetTeamsMeetingPolicyCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com

PS C:\WINDOWS\system32> Set-CsTeamsMeetingPolicy -AllowPrivateMeetingScheduling $True
PS C:\WINDOWS\system32>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2fe730-a95d-d12d-adb8-49d1397c77c7
* Version Independent ID: 1f6077c3-6114-cb5e-8b1a-7587188f2cdf
* Content: [Set up for webinars in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-webinars)
* Content Source: [Teams/set-up-webinars.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-webinars.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by RAJU2529** [comment]
@FrankSchuurman68 .  Boolean text has been modified by the contributor, and it will be available once approved by the author and new page will be visible to public.

**Comment by RAJU2529** [comment]
@KarliStites . Look at this article **https://docs.microsoft.com//microsoftteams/set-up-webinars** ,  this article is  already been edited but  **$**  symbol is  not yet visible to the public,  so only  @FrankSchuurman68  created issue #7334,  
so please merge the edited article and make it visible to the public
