### ISSUE TITLE
Article doesn't reflect steps needed for MFA

### ISSUE THREAD

**Issue by valorx-git** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7337]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8935e913-806f-a92c-d09e-e67df4ffd1b4
* Version Independent ID: c7a41cde-66dd-d7cd-1316-42d20ed4841a
* Content: [Use OneDrive for Business and SharePoint for meeting recordings - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/tmr-meeting-recording-change)
* Content Source: [Teams/tmr-meeting-recording-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tmr-meeting-recording-change.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by valorx-git** [comment]
I am an admin of 2 different Office tenants and have access to 5 to 6 customer office/teams as a user. Every single one of them have **multi-factor authentication turned on**. The issue with this article is that this command won't work for any of these environments. 

> Import-Module MicrosoftTeams
> $credential = Get-Credential
> Connect-MicrosoftTeams -Credential $credential

The 3rd line should simply be **Connect-MicrosoftTeams** which will work in the interactive mode and users can use multi-factor authentication rather the credentials captured through Get-Credential.

Hope all the articles have MFA in mind and would save time for admins and not have to figure out the way I did.

**Comment by scanum** [comment]
@valorx-git hank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @valorx-git thanks for reporting.
