### ISSUE TITLE
404 error while running creatersrs script - FIXIT

### ISSUE THREAD

**Issue by falccc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7338]
As per the previous thread, this issue still exists.  Just closing the thread without resolving it is not acceptable, Microsoft.

Please fix this issue.  There is no other solution available and these devices tend to be in Boardroom's and other important locations used by senior management.

**Comment by RAJU2529** [comment]
@falccc . Which article are you referring to?

**Comment by falccc** [comment]
https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/console

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by falccc** [comment]
This is NOT a tenant problem.  Appalling service Microsoft, we will be raising this back through the partner channel.
