### ISSUE TITLE
Wrong translation of vendor name Ribbon

### ISSUE THREAD

**Issue by dgricourt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#734]
There seems to be an automatic translation for the Ribbon vendor name.Can you please update the vendor name "Cinta de opciones" to Ribbon. 
Thanks,

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 1b1a1c01-10a9-7f69-1c7b-1a566b0f5112
* Version Independent ID: 329ee759-40fc-98fb-b91e-87786c63024b
* Content: [Lista de controladores de borde de sesión de certificados para el enrutamiento directo](https://docs.microsoft.com/es-es/microsoftteams/direct-routing-border-controllers)
* Content Source: [Teams/direct-routing-border-controllers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.es-ES/blob/live-sxs/Teams/direct-routing-border-controllers.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
@samanthaw  -- please look into this
