### ISSUE TITLE
suggest CMD to check/get current value

### ISSUE THREAD

**Issue by TiloGit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7342]
suggest to add this to check current status: 
``` powershell
Get-CsTeamsMeetingPolicy | select Identity, WhoCanRegister, AllowMeetingRegistration, AllowPrivateMeetingScheduling 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2fe730-a95d-d12d-adb8-49d1397c77c7
* Version Independent ID: 1f6077c3-6114-cb5e-8b1a-7587188f2cdf
* Content: [Set up for webinars in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-webinars)
* Content Source: [Teams/set-up-webinars.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-webinars.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by scanum** [comment]
@TiloGit Thanks for your feedback, we will consider adding this to the documentation
