### ISSUE TITLE
Teams Webinars - Lists in SharePoint?

### ISSUE THREAD

**Issue by fs366e2spm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7346]
What is "Microsoft Lists needs to be set up in SharePoint." exactly?
Is it the requirement to ALLOW the creation of personal lists?

So when personal list creation is disabled then no webinars are possible?

Is a special list template required?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2fe730-a95d-d12d-adb8-49d1397c77c7
* Version Independent ID: 1f6077c3-6114-cb5e-8b1a-7587188f2cdf
* Content: [Set up for webinars in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-webinars#configure-who-can-register-for-webinars)
* Content Source: [Teams/set-up-webinars.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-webinars.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by TiloGit** [comment]
@scanum instead of suggest service tickets can someone at MS please update the document to reflect missing details.

**Comment by fs366e2spm** [comment]
Hmm, why is this case closed already?

We created a case and it's confirmed that Personal Lists need to be ACTIVE to use webinars. There are 3 lists createad (??) for each webinar.

Would be good, that it's highlighted in the documentation that personal lists need to be active and not just mentioning "Microsoft Lists needs to be set up in SharePoint."

Please update the documentation.

**Comment by fs366e2spm** [comment]
@scanum - creating a case with MS support and getting the answer is not always possible within 7 days... so too fast to close this case.

**Comment by TiloGit** [comment]
agree the page need more details on this. 

ran this PS to check: 

```powershell
Get-SPOTenant | select DisablePersonalListCreation, DisabledModernListTemplateIds
```
