### ISSUE TITLE
Incorrect Statement

### ISSUE THREAD

**Issue by dinocaputo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7349]
[Enter feedback here]
This statement is incorrect.  I have tenant in Islands Mode and can get Operator Connect to work.  User must be in Teams Only mode.  

_"Make sure you're in TeamsOnly mode. To check, in the Teams admin center, go to Org-wide settings > Teams upgrade. The coexistence mode should be set to Teams only."_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 709c5bb1-843a-c243-16b6-86bd9f114d37
* Version Independent ID: e5e9415f-bd40-4084-e280-59be5cc186a6
* Content: [Configure Operator Connect - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/operator-connect-configure)
* Content Source: [Teams/operator-connect-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/operator-connect-configure.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by scanum** [comment]
@dinocaputo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @dinocaputo, thank you for your feedback.

Are you assigning new numbers acquired from the operator?

**Comment by dinocaputo** [comment]
Yes I am assigning numbers acquired from the Operator.

**Comment by dariomws** [comment]
@dinocaputo thanks, I'm applying updates based on that information.

**Comment by dariomws** [comment]
Thank you for your feedback @dinocaputo, It was fixed here:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/7395

@scanum please close it. Thank you!

**Comment by dariomws** [comment]
@scanum please close it. Thank you!
