### ISSUE TITLE
Support versions of Domain Controllers for Lync 2015

### ISSUE THREAD

**Issue by skipatrol1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#735]
Can you please document what DC versions and forest functional modes are currently supported and which CU allows the support.  I know that Windows 2016 was not supported for Lync Servers but what about DCs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c475b5d-09ed-7f58-86d4-27f28e33ef7a
* Version Independent ID: f0ad50f3-ea93-9424-6de8-a0b778e90b23
* Content: [Server requirements for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/server-requirements)
* Content Source: [Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by AndreaBarr** [comment]
@skipatrol1 Thank you for this feedback

I want to make sure this gets doccumented for you so I am getting this over to our Teams team so we can properly handle this.

I was able to get this into the backlog for the Teams team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
@skipatrol1, I have added a reference to the article which talk about AD support for SfB 2015. It should be online in a few days.

AD 2016 is not officially supported with Lync Server 2013 because I think that Microsoft didn't test it, but I am pretty sure that it works. Anyway I should recommend that you don't upgrade your AD to 2016 if you have Lync Server 2013.

**Comment by dariomws306** [comment]
Hi @skipatrol1 , this update is public now. Thank you for your feedback.
