### ISSUE TITLE
Busy on Busy options

### ISSUE THREAD

**Issue by Korbyn72** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7350]
Another way to connect this for people is to use the term "Call Waiting", at least that is what I tell North American customers what Busy-on-Busy options are.  Just a thot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410fc30b-f530-8443-0602-9150c9cba115
* Version Independent ID: c5b33b25-147b-f7d4-056a-987088950e7c
* Content: [Calling policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-calling-policy)
* Content Source: [Teams/teams-calling-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-calling-policy.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@Korbyn72 Thanks for the suggestion. We appreciate your feedback.
