### ISSUE TITLE
Microsoft 365 live event limit increases

### ISSUE THREAD

**Issue by mamrouni** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7352]
Hello,
The "Microsoft 365 live event limit" increases until 31 December 2021 and not 30 June 2021
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#teams-live-events)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@mamrouni Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
