### ISSUE TITLE
AA and CQ Field Descriptions Require Clarification / AA_CQ PBI Template Require Field Descriptions

### ISSUE THREAD

**Issue by 3017mark** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7354]
Numerous customers have complained about not being able to correlate the information for CQD to the field descriptions.  The AA_CQ PBI template has numerous fields that due not match what is published in the docs page.  No documentation exists to explain what a customer is viewing and how it correlates with their reports.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 628345c6-f5f9-fe8e-bfff-faea00a8a25c
* Version Independent ID: 30f2d051-5af5-0063-7099-38b5b08ec1e4
* Content: [Auto Attendant & Call Queue Historical Report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/aa-cq-cqd-historical-reports)
* Content Source: [Teams/aa-cq-cqd-historical-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/aa-cq-cqd-historical-reports.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@3017mark Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by MikePlumleyMSFT** [comment]
@CLYVR can you help?

**Comment by CLYVR** [comment]
@MikePlumleyMSFT @3017mark  Plan is to re-write this page within the next couple of weeks.  If you have some specific feedback/examples from customers that you want to be sure I address please let me know.

**Comment by CLYVR** [comment]
@MikePlumleyMSFT @3017mark Updated documentation is now available and hopefully this helps clarify things.  While I still have a few pending updates to do for that page, the bulk is done.
