### ISSUE TITLE
Sizes of the preview images

### ISSUE THREAD

**Issue by i3v** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7355]
The "limits" page does not specify "image preview generation" limits (image size, image dimensions?)

That is:

1. although I am able to attach a 11000x5000 pixel ".png" image to my post/comment, it is treated as a file attachment, and no small preview image is generated. The exact limit (above that no preview would be generated) seem to be undocumented.
2. when I upload a smaller image (e.g. 2253x1532), the preview is generated. I am also able to click on the image, and see a larger preview. This "full-screen preview" turns out to be a ".jpg" image, auto-generated from my original image. Its resolution is still lower than the resolution of the original image (e.g. 2253x1532 -> 2048x1393). (Btw, that's below the adequate resolution for modern 4K displays.) The exact resolution of this preview image seem to be undocumented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@i3v Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @i3v how are you?
Thanks for the feedback, I passed this along and your suggestion will be taken under advisement. Also please consider opening a [uservoice](https://microsoftteams.uservoice.com/) entry so your request to support bigger image previews is taken into account.

**Comment by scanum** [comment]
@i3v Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by i3v** [comment]
OK, thanks. 
As you've suggested, I've created a uservoice suggestion. Two actually:
* https://microsoftteams.uservoice.com/forums/555103-public/suggestions/43583481-increase-quality-of-images-in-posts-and-comments
* https://microsoftteams.uservoice.com/forums/555103-public/suggestions/43583514-generate-preview-images-even-for-larger-images
