### ISSUE TITLE
how to manage conf settings via PowerShell

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7358]
"Using Windows PowerShell" section does not include any usable info.
At the very minimum, I expect to see PowerShell cmdlets name.

The same problem is on the following pages:

- https://docs.microsoft.com/en-us/microsoftteams/send-an-email-to-a-user-with-their-dial-in-information-in-teams
- https://docs.microsoft.com/en-us/microsoftteams/emails-sent-to-users-when-their-settings-change-in-teams

Please add PowerShell cmdlets names into PowerShell sections of these help articles

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aebda07-e7a4-163c-bf2e-255fe77f975d
* Version Independent ID: e25ce13d-3b29-53ef-1bd2-eb11d20fbc36
* Content: [Email options when Audio Conferencing settings change - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/enable-or-disable-sending-emails-when-their-settings-change-in-teams)
* Content Source: [Teams/enable-or-disable-sending-emails-when-their-settings-change-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enable-or-disable-sending-emails-when-their-settings-change-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@shivtorov Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
