### ISSUE TITLE
Enabling Guest Access in Microsoft Teams no longer works

### ISSUE THREAD

**Issue by spalmstr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#736]
The instructions in Enabling Guest Access in Microsoft Teams are obsolete.  Going to Services and Add-ins -&gt; Microsoft Teams -&gt; Settings by User/License Type yields greyed out controls, so you can't turn on Guest Access.  Going to Home -&gt; Active Users does not allow you to manage guest licensing for Teams.  Hence, guest access in MS Teams seems now to have been disabled!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2492e210-08f9-a476-97ec-008926def961
* Version Independent ID: adcb0dd9-4a3c-b665-6e34-ce3276c89b4d
* Content: [Guest access in Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/guest-access?redirectSourcePath=%252fen-us%252farticle%252fGuest-access-in-Microsoft-Teams-bd4cdeec-4044-4b4b-9df1-beb139013a3f)
* Content Source: [Teams/guest-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access.md)
* Service: **msteams**
* GitHub Login: @laithalshamri
* Microsoft Alias: **laal**

**Comment by cyberyann41** [comment]
Same problem here, no way to enable guest access...Anyone have a solution ?

**Comment by RHarrold-Cornerstone** [comment]
We have encountered the same problem and have been unable to find a solution as of this time.  I suspect that Microsoft depreciated the function prior to the replacement being functional/published.

**Comment by kenwith** [comment]
@cdebbo - this is really great info to add into the docs. Andrea will create an item for us to get in our backlog. On your specific case the best option would be to open a service ticket in your tenant so they can get this resolved for you and escalated if needed.

@AndreaBarr - let's create a backlog item to make sure the instructions @cdebbo provided are captured in the docs and we can leave this open until we get the docs accurate.

**Comment by AndreaBarr** [comment]
@spalmstr Thank you for these instructions. 

I have gotten this added to the backlog so we can get these instructions added to the article.

**Comment by spalmstr** [comment]
@AndreaBarr - will you be creating instructions on how to access Teams & Skype via MS Edge?  I get [https://admin.teams.microsoft.com/error?code=SECURITY_ZONE_ERROR](https://admin.teams.microsoft.com/error?code=SECURITY_ZONE_ERROR) when trying to do so, and there doesn't seem to be a way to add the trusted sites.  I tried with IE and inetcpl.cpl, but Edge doesn't seem to have picked them up, even after restarting the browser.

**Comment by AndreaBarr** [comment]
@spalmstr I can add a note to the backlog item for it so that accessing Teams & Skype for Business via MS Edge is also included in this article update. If I'm not the one to do the update then one of the members of the Teams/Skype for Business team will.

**Comment by spalmstr** [comment]
@AndreaBarr - sounds good, as it wouldn't work for me.

**Comment by db0mz** [comment]
I don't have access to this either. Critical!

**Comment by AndreaBarr** [comment]
@db0mz Thank you for this feedback. 

If you need this issue expedited please contact Support. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

**Comment by jmzwiv** [comment]
Any news on this? We've been having problems enabling Guest access and came across this discussion.

**Comment by AndreaBarr** [comment]
@jmzwiv We are still working on this. If you need an expedited answer please open a support ticket. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

**Comment by SharS** [comment]
@jmzwiv  
Just want to confirm that you've followed the instructions in "Turn on or off guest access" (https://docs.microsoft.com/en-us/microsoftteams/set-up-guests).
