### ISSUE TITLE
Powershell 7.x fails with Teams module

### ISSUE THREAD

**Issue by SeaGT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7362]
I wasted 3 hrs trying to get the Team Powershell module working with MFA to get logged in.  Instead of a recommendation to use Powershell 5.1 - this page should include the Warning from: https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-overview
Don't use Powershell 7 with the Microsoft Teams module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd283f6e-3865-ed70-d663-cc461ee8ba57
* Version Independent ID: 2450d311-fc04-d8b6-b4a2-b1890ec6fc3e
* Content: [Install Microsoft Teams PowerShell - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install)
* Content Source: [Teams/teams-powershell-install.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-install.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by RAJU2529** [comment]
@SeaGT , Just i installed micrsosoft teams v 2.3.1   through powershell v 7.1.3 x64 .msi   application

Here is the proof 
![addpowershell](https://user-images.githubusercontent.com/3296790/120894010-d1c65580-c633-11eb-8afc-2baadfc85b55.JPG)

**Comment by RAJU2529** [comment]
@e0i. Will you comment on this issue #7362

**Comment by SeaGT** [comment]
Hi there,

Never said I wasted 3 hrs trying to install the module. 

Try connecting to it using an MFA account so you can actually do anything with it…….  I couldn’t get any of the connection options working with an MFA account and neither could MSFT tech support. 

Greg                                      

***@***.***   

Desk: 206.576.6012 | IT Support: 206.576.6013

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by SeaGT** [comment]
Hi Manuela,

The solution is to not install Powershell 7.x (which I only installed because your docs recommended it) and just use Powershell 5.  Change your documents to tell people NOT to install Powershell 7.x if they are using MFA on their accounts and there shouldn’t be an issue. 

I already opened a ticket with MFST tech support and the solution was to roll back to Powershell 5. 

Greg                                      

***@***.***   

Desk: 206.576.6012 | IT Support: 206.576.6013
