### ISSUE TITLE
Powershell 7.1.3 is working

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7365]
Just now i  installed  microsoftteams v2.3.1  through PowerShell v7.1.3 64bit, so i think below line must be removed from this article.
**There are known issues with PowerShell 7 and Teams PowerShell. We recommend using PowerShell 5.1 until the issues are resolved.**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5720e37-e8dd-1e3e-ccfa-cf4db31e8cff
* Version Independent ID: 93a36eb2-3554-0e86-e787-759eaaafe5e1
* Content: [Microsoft Teams PowerShell Overview - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-overview)
* Content Source: [Teams/teams-powershell-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-overview.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by RAJU2529** [comment]
@brandber , Whats your opinion sir?
here is the proof 
![addpowershell](https://user-images.githubusercontent.com/3296790/120894096-5913c900-c634-11eb-9d75-4fc9a7551a90.JPG)

**Comment by RAJU2529** [comment]
@e0i. Will you comment on this issue #7365

**Comment by scanum** [comment]
@bratsche Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @rajgodwin Even though the install is possible (and I myself also tested this in the past) not all the functionality is ready, that is why the statement is there. Thank you
@scanum please close.
