### ISSUE TITLE
SkypeRoomProvisioningScript.ps1 needs to update to use Connect-MicrosoftTeams

### ISSUE THREAD

**Issue by dwhitney7** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7377]
Hello!

The [room provisioning script](https://go.microsoft.com/fwlink/?linkid=870105) linked at the top of the page is still using the New-CsOnlineSession command to establish a remote PowerShell connection, which has been deprecated and should be replaced with Connect-MicrosoftTeams.

Minimal change starting line 1113, replace these two lines:

```powershell
    $sessSkype = New-CsOnlineSession -Credential $credSkype
    Import-PSSession -Session $sessSkype -AllowClobber -WarningAction SilentlyContinue
```

With this single line:

```powershell
    Connect-MicrosoftTeams -Credential $credSkype
```

Consider also updating it to use modern auth rather than pass creds inline.

Thanks!
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Microsoft 365 or Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-office-365)
* Content Source: [Teams/rooms/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-office-365.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by dwhitney7** [comment]
While not an issue per se, I would additionally suggest an overall branding update for this script to Teams and MTR.

**Comment by get-itips** [comment]
Hello @dwhitney7 David, how are you? Thanks for reporting, @cichur Cindy, can we pass this information on?, as the script is not hosted in docs I can't update it.
Thank you!

**Comment by dstrome** [comment]
hi @dwhitney7 - thanks for the feedback. I'll pass it on to the product team for review. Since the content team doesn't own this script, I'm going to close this issue as there's no further action.
