### ISSUE TITLE
emails to phone system users

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7378]
How to control whether to send an email to the user with their phone number information when I assign numbers using Set-CsOnlineVoiceUser?

To control emails sent to users when they were enabled for Audio Conferencing, we use `Set-CsOnlineDialInConferencingTenantSettings -AutomaticallySendEmailsToUsers $true|$false`

How to control emails sent when Phone System number is assigned using PowerShell (Set-CsOnlineVoiceUser)?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c67496-cace-f833-7cfc-dca7722fef3e
* Version Independent ID: 5a14f81c-529c-4971-5ce8-39633834d4d3
* Content: [Assign, change, or remove a phone number for a user - Microsoft Teams](https://docs.microsoft.com/en-au/microsoftteams/assign-change-or-remove-a-phone-number-for-a-user)
* Content Source: [Teams/assign-change-or-remove-a-phone-number-for-a-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-change-or-remove-a-phone-number-for-a-user.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
