### ISSUE TITLE
Missing quotes from example

### ISSUE THREAD

**Issue by bodanesc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7383]
Hello team!

In the documentation there's a missing double quote, that renders the code invalid.
The piece that i am referring to is: 
"Set-CsUser -Identity "spencer.low@contoso.com" -OnPremLineURI tel:+14255388701;ext=1001 -EnterpriseVoiceEnabled $true -HostedVoiceMail $true"

The correct syntax for OnPremLineURI should be between double quotes, as multiple parameters are sent out and ";" is breaking the code.

Could you please review multiple parameters in this documentation page?

Thank you very much,
Bogdan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb2a9717-6565-8443-8833-f7fdce562781
* Version Independent ID: db88c4d6-5864-a481-86cf-465feb452d75
* Content: [Enable users for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-enable-users)
* Content Source: [Teams/direct-routing-enable-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-enable-users.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@bodanesc Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by get-itips** [comment]
Thanks for reporting @bodanesc  !

**Comment by bodanesc** [comment]
No worries @get-itips, thank you very much as well!
