### ISSUE TITLE
File upload limit shows old value

### ISSUE THREAD

**Issue by gdukevt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7384]
I believe the "File upload limit (per file)" value was increased in January 2021 from 100 GB to 250 GB. I found several sources (TheVerge, ZDNet) confirming this, but haven't found official MS documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@gdukevt Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by lindspea** [comment]
@gdukevt thank you for pointing this out. Do you have any official documentation confirming this?

**Comment by gdukevt** [comment]
I was coming to this doc which seems like the official reference, no? :)

A little Goo^h^h^hBing searching located this:
https://techcommunity.microsoft.com/t5/microsoft-onedrive-blog/gain-more-flexibility-with-250-gb-file-size-support-in-microsoft/ba-p/1847728

**Comment by lindspea** [comment]
@gdukevt thank you again for your valuable input. The document has been updated to show the correct value. @scanum this can be closed thank you.
