### ISSUE TITLE
Discrepancy in Teams Live Events limit increases date

### ISSUE THREAD

**Issue by ddaanniieell9** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7385]
The following discrepancy in dates is generating support tickets to Microsoft.

https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams
- This document reports "To continue supporting our customers' needs, through June 30, 2021"

https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events
- This document reports "To continue supporting our customers' needs, through January 2022"

Please confirm which is the correct date and fix the documentation to avoid confusion.

Thanks,
Daniel Portal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@ddaanniieell9 Thank you for submitting feedback and contributing to the docs. We are currently investigating this
