### ISSUE TITLE
Team Settings via Team Templates

### ISSUE THREAD

**Issue by InspireCloudTech** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7388]
The document references that Settings (member permissions, mentions etc.) are possible via Team Templates, however from my testing I have been unable to set those Settings through the Team Templates function in the admin centre. I had raised an MS Support ticket, but they were confused and unable to confirm if that feature did work.

Therefore can this either be removed or expanded on, in the document please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef94e9a3-a0a5-11da-f27b-627ac4fa6186
* Version Independent ID: e49db873-ed77-de53-e4dd-be4fc571d734
* Content: [Use team templates in the admin center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-started-with-teams-templates-in-the-admin-console)
* Content Source: [Teams/get-started-with-teams-templates-in-the-admin-console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-started-with-teams-templates-in-the-admin-console.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@InspireCloudTech  Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by get-itips** [comment]
Hello @InspireCloudTech how are you? Hope you are doing good.
I analyzed the issue you created and I think that, that section is only mentioning what is supported currently in general by Teams templates, not specifically what you can do with the Teams admin center.

> The following table provides a quick summary of what's included and what's not included in team templates.

Then later in the same document, a reference to Template's cmdlets is provided to be able to specify those settings in a template.
Hope this information helps you.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
