### ISSUE TITLE
the default value for "WhoCanRegister" is not correct

### ISSUE THREAD

**Issue by ikukoyoneda** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7393]
In "Configure who can register for webinars" section, we have the following sentence.
>By default, WhoCanRegister is enabled and set to Everyone.
But actual default setting is "EveryoneInCompany", not "Everyone".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2fe730-a95d-d12d-adb8-49d1397c77c7
* Version Independent ID: 1f6077c3-6114-cb5e-8b1a-7587188f2cdf
* Content: [Set up for webinars in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-webinars#feedback)
* Content Source: [Teams/set-up-webinars.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-webinars.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by scanum** [comment]
@ikukoyoneda Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by dariomws** [comment]
Hi @ikukoyoneda, thank you for your feedback.

I'm applying an update here. It's set to "Everyone in the organization" for the Global policy and new policies created from the Admin Center by default.
For new policies created using PowerShell, Everyone is the default value.

**Comment by dariomws** [comment]
Related to:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/7846

**Comment by dariomws** [comment]
@ikukoyoneda sorry I made a mistake. The default value is Everyone for the Global policy.

**Comment by dariomws** [comment]
@scanum I think we can close this issue.
