### ISSUE TITLE
Change needed under section "Remove your on-premises Skype for Business deployment"

### ISSUE THREAD

**Issue by NicholasBurkhammer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7396]
Updated Verbiage:

a. Update your Skype for Business Server topology to have a single front-end pool:

•	In Topology Builder, download a new copy and navigate to the Front End pool where CMS is homed.
•	Right-click the pool, and then click Edit Properties.
•	In Associations, uncheck Associate Edge Pool (for media components) and click OK.
o	Note:  If the SQL backend store for the Front End pool hosting CMS has a SQL witness configured, uncheck the witness association.
•	If there is more than one Frontend Pool, Edit Properties for each additional pool, and remove any associations for all remaining Front End pools.
•	Select Action > Remove Deployment.
•	Select Action > Publish Topology.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 809826d2-e82d-0b31-0c8b-c475db0efbb8
* Version Independent ID: b4e15a5f-8096-21db-c120-63e99d601328
* Content: [Decommission Skype for Business Server - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/decommission-remove-on-prem#remove-your-on-premises-skype-for-business-deployment-1)
* Content Source: [Skype/SfbHybrid/hybrid/decommission-remove-on-prem.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/decommission-remove-on-prem.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by joaolloureiro** [comment]
@CarolynRowe  Please proceed with these changes since this have been previously reviewed in scope of an IcM. I have coauthored this particular article in strict collaboration with BJ Whalen

**Comment by scanum** [comment]
@joaolloureiro Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by CarolynRowe** [comment]
@joaolloureiro.  In cases like this, it's probably best to create a PR to the existing topic.  Do you need information on how to do that?

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
