### ISSUE TITLE
Set-CsTenantFederationConfiguration

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7397]
[Enter feedback here]

Need support for Set-CsTenantFederationConfiguration in Teams Module
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09f27c0e-15db-920c-dee9-824bcab166cc
* Version Independent ID: c0bd47ae-da8c-b466-4e05-5c97b055ee9b
* Content: [Migrating from Skype for Business Online Connector to the Teams PowerShell module - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-move-from-sfbo)
* Content Source: [Teams/teams-powershell-move-from-sfbo.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-move-from-sfbo.md)
* Service: **msteams**
* GitHub Login: @pupara
* Microsoft Alias: **pupara**

**Comment by scanum** [comment]
@GitWesDone Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
