### ISSUE TITLE
This still accurate?

### ISSUE THREAD

**Issue by joeljanke** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7398]
Is this line still accurate?

"Retention policies are not supported for messages in private channels."

This link seems to suggest that retention policies can exist on private channels...
https://docs.microsoft.com/en-us/microsoftteams/retention-policies#when-to-use-retention-policies-for-teams

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@joeljanke Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by joeljanke** [comment]
It looks like maybe I just got confused by the use of the word "private" with regards to "Chats" vs "Channel Conversations (i.e. Posts)".    While Chanel Conversations have a concept of public/private...Chats have no such concept...they are simply chats.   Calling them private is kind of confusing...particularly when anyone in the chat can add someone to it and let them see history.   Perhaps the only relevant change here is to remove the 2 instances of "private" from this paragraph...

Manage retention policies for Microsoft Teams - Microsoft Teams | Microsoft Docs<https://docs.microsoft.com/en-us/microsoftteams/retention-policies#when-to-use-retention-policies-for-teams>

It would help folks like me from confusing it with Private Teams Conversations (i.e. Posts).

From: Manuela Scanu ***@***.***>
Sent: Tuesday, June 15, 2021 19:48
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Janke, Joel <JJanke@WBMI.com>; Mention ***@***.***>
Subject: [External]Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] This still accurate? (#7398)


@joeljanke<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjoeljanke&data=04%7C01%7C%7C454bda923f03484386d108d930606049%7C48b0431c82f64ad2a023ac96dbf5614e%7C0%7C0%7C637595363970606666%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2F2jgEWHOpsuXiO4FzrzW2MeGrnDcTVyUQGbRrEsb9kE%3D&reserved=0> Thank you for submitting feedback and contributing to the docs. We are currently investigating this

-
