### ISSUE TITLE
Link for the Meeting Migration Tool needs an update

### ISSUE THREAD

**Issue by matwer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#74]
Hi - the link for the Meeting Migration should point to <https://support.office.com/en-us/article/Meeting-Update-Tool-for-Skype-for-Business-and-Lync-2b525fe6-ed0f-4331-b533-c31546fcf4d4> - the current link is pointing to <https://go.microsoft.com/fwlink/p/?linkid=626047> and just takes you to the Microsoft store

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 990ca74b-6bba-a14b-071a-d13adb723a4c
* Version Independent ID: 52f55a58-30ce-c140-3ee7-8042b1d105f0
* Content: [Setting up the Meeting Migration Service (MMS) | Microsoft Docs](https://docs.microsoft.com/en-us/SkypeForBusiness/audio-conferencing-in-office-365/setting-up-the-meeting-migration-service-mms?ui=en-US&rs=en-US&ad=US#feedback)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/setting-up-the-meeting-migration-service-mms.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/setting-up-the-meeting-migration-service-mms.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by tonysmit** [comment]
@matwer I reviewed the link and it does like to the 64-bit migration tool. https://www.microsoft.com/en-us/download/details.aspx?id=51659 at the Ms Download Center. Can you try this again and see if you think it's still broken? Thanks, Tony

**Comment by matwer** [comment]
Looks good - it was an id10t error...I hadn't scrolled down the page past the gigantic Microsoft Store ad that popped up for me..

Apologies,
Matthew

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tonysmit** [comment]
Awesome. Glad to help. Let me know if you have any other issues. Tony
