### ISSUE TITLE
Option to enable Guest access to teams has been depreciated

### ISSUE THREAD

**Issue by RHarrold-Cornerstone** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#740]
The link in this documentation points to instructions that no longer work.  There is no apparent way currently to enable guest access to teams (Even with help from Microsoft Support) due to the control being depreciated as of August.

**Comment by AndreaBarr** [comment]
@RHarrold-Cornerstone Thank you for your feedback. 

A few others reported having this issue and There is a resolution in this linked post below. 
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/739#issuecomment-419564176
This should resolve the issue. If it doesn't please let me know.
