### ISSUE TITLE
Integração O365

### ISSUE THREAD

**Issue by Ostars-eye** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7400]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c9902e8-a0b7-b6af-4656-2024849a5e8b
* Version Independent ID: 85beb9a7-2682-b52e-210b-20e598e3dab3
* Content: [Create your first teams and channels - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-started-with-teams-create-your-first-teams-and-channels)
* Content Source: [Teams/get-started-with-teams-create-your-first-teams-and-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-started-with-teams-create-your-first-teams-and-channels.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@Ostars-eye Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
