### ISSUE TITLE
"Additionally, Microsoft Lists needs to be set up in SharePoint. To learn more, see Control settings for Microsoft Lists."

### ISSUE THREAD

**Issue by cwhitek3** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7407]
[Enter feedback here]

This is not clear, what, specifically, is needed to be setup with Microsoft Lists?  You follow the link and all you get is a how to on how to disable personal lists.  

Do we allow private lists, do we disable them, what do we do here?  Is anything else required on the sharepoint side?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2fe730-a95d-d12d-adb8-49d1397c77c7
* Version Independent ID: 1f6077c3-6114-cb5e-8b1a-7587188f2cdf
* Content: [Set up for webinars in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-webinars)
* Content Source: [Teams/set-up-webinars.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-webinars.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by scanum** [comment]
@cwhitek3 Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by cwhitek3** [comment]
I have already reached out to Microsoft support about Webinars and they were not even able to give me the information that you DID document.  I respectfully ask that you escalate this as I see I am not the only user that has reached out about the unclear documentation.

From: Manuela Scanu ***@***.***>
Sent: Wednesday, June 16, 2021 10:49 PM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Chris White ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] "Additionally, Microsoft Lists needs to be set up in SharePoint. To learn more, see Control settings for Microsoft Lists." (#7407)

CAUTION - EXTERNAL EMAIL - Please verify sender before opening attachments or links and never share your password.


Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products<https://docs.microsoft.com/office365/admin/contact-support-for-business-products>
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

-
