### ISSUE TITLE
Real MachineWide Installer

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7408]
Are we ever going to get a real MachineWide Installer that behaves like all other Microsoft Apps.  i.e. Runs out of Program Files and only puts the bare minimum required into Users AppData folders?  On Shared PC's Teams wastes around 600-900MB per profile of disk space. On Shared Presentation PC's we have literally 150GB of the 256GB SSD is just per-user Teams installs.  It is crazy that a MS product requires a scripted delprof setup for the sole-purpose of cleaning up Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Teams using Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@mattsmacblog Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
