### ISSUE TITLE
Document out of date

### ISSUE THREAD

**Issue by cparker4486** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#741]
The Org-wide coexistence settings have only two options (for my tenant): Islands and Skype for Business Only. There is not Teams Only option.

When I loaded the coexistence settings page, for the first time today, my setting was on Legacy (Deprecated). I changed it to Islands and, after the page reloaded, Legacy (Deprecated) was no longer available in the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffbf0bfd-c15e-b10b-0cc9-6a27ac1e6634
* Version Independent ID: 58575371-9e09-fadb-76f6-7491df8580a3
* Content: [Setting your coexistence and upgrade settings](https://docs.microsoft.com/en-us/microsoftteams/setting-your-coexistence-and-upgrade-settings)
* Content Source: [Teams/setting-your-coexistence-and-upgrade-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/setting-your-coexistence-and-upgrade-settings.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by brbandre** [comment]
Hello,
I'm having the same issue. I want to have Teams Only, there there is no option.

Thank you.

**Comment by AndreaBarr** [comment]
@cparker4486 Thank you for this feedback.

I want to make sure this gets addressed and you can have Teams only. Support will be able to take this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by cparker4486** [comment]
@AndreaBarr Did you also update the docs?

**Comment by AndreaBarr** [comment]
@cparker4486 No not yet I sent it to the backlog for Teams/Skype so that we can get it updated.

**Comment by brbandre** [comment]
I just opened a ticket with support to investigate that.

**Comment by AndreaBarr** [comment]
@brbandre Great we will get this tacked from both ends then.

**Comment by NafzigerA** [comment]
What was the resolution?  I'm experiencing the same issue.

**Comment by AndreaBarr** [comment]
@NafzigerA There is not resolution quite yet. We are still working on this. If you need expedited help please feel free to open a Support Ticket. 


Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

**Comment by Mangego** [comment]
Where is Set "Notify Skype for Business users that Teams is available for upgrade" setting. And Set whether to Download the Teams app in the background for Skype for Business users. IT is not available under "Teams upgrade page" And it is not available under powershell either.

**Comment by charlesrg** [comment]
We have the same problem just like all the other people. There is definitely something wrong.

@AndreaBarr instead of just asking everybody to create a ticket, can you look why the documentation does not match and when will this feature be available?

**Comment by AndreaBarr** [comment]
@cparker4486 I had the original person who opened this issue open a ticket as well as me creating a backlog item and getting it to the Teams team for investigation so we can have it worked on from both ends. The ticket creating was for some extra data collection that we can't do here at the docs team.

**Comment by mltytskr** [comment]
Is there any update to the release of this feature? I too don't have a teams only option in my admin center or any of the other settings mentioned above. My tenant is set for targeted release for everyone if that makes any difference.

**Comment by NafzigerA** [comment]
I resolved this by using powershell directly on the individual users I wanted to test.  This code worked for me - just change the email address:
`$LiveCred = Get-Credential
# Connect to Skype Online
Import-Module SkypeOnlineConnector
$sfboSession = New-CsOnlineSession -Credential $LiveCred
Import-PSSession $sfboSession

$SipAddress = "xxxx@yyyy.zzz"
Grant-CsTeamsUpgradePolicy -PolicyName UpgradeToTeams -Identity $SipAddress
Grant-CsTeamsInteropPolicy -PolicyName DisallowOverrideCallingTeamsChatTeams -Identity $SipAddress
`

**Comment by Absoblogginlutely** [comment]
We got an email some time ago saying that our tenant was scheduled for upgrade today.
However when I go to the instructions for the upgrade, I also only have islands or Skype For Business. My initial thought was that we were already upgraded but I checked another client that is scheduled for upgrade next week and they also have Islands/Skype only.
I've had no notifications in the skype app that we will be upgraded, no notification to the end users that it will be upgraded.

**Comment by jonwbstr** [comment]
Just opened a separate issue not realizing the one titled "Document out of date" was addressing the issue I experienced also.

The command shared by NafzigerA sets the policies for a specific user while the admin interface is intended to configure the policy for all users in the organization. To set the global configuration to be applied to all users moving forward, use the following commands:

Grant-CsTeamsUpgradePolicy -PolicyName tag:UpgradeToTeams
Grant-CsTeamsInteropPolicy -PolicyName tag:DisallowOverrideCallingTeamsChatTeams

See the current global policy using the commands:
Get-CsTeamsUpgradePolicy -Identity Global
Get-CsTeamsInteropPolicy -Identity Global

**Comment by get-itips** [comment]
Hi @cparker4486 hope you are doing well.
Document was updated after you created this issue, including a note saying that TeamsOnly option will only be present on some organizations. As this is the original issue with the document. I also checked the Teams Admin Portal instructions and they currently match what you see in Teams Admin Portal.

Hope this information has helped you!

Thank you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @cparker4486 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
