### ISSUE TITLE
What is the Call Flow on 8/1/21

### ISSUE THREAD

**Issue by RABurnettMCSE** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7411]
What happens to users that are not complete in the migration of Skype for Business on 8/1 what will the end-user experience be for Non-Teams phones, SIP Call Routing? I suspect everything will stop working however customers don't believe me when I tell them because they say the Microsoft documentation is not clear.  We need clear documentation on call flows when all Federation is removed and clear statements that hybrid will then be broken.

**Comment by scanum** [comment]
@RABurnettMCSE Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
