### ISSUE TITLE
Guidance on subnets for signaling

### ISSUE THREAD

**Issue by thomasbinder** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7414]
[Enter feedback here]
In https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-plan#sip-signaling-fqdns the IP ranges for signaling are also documented but with a larger range of:
52.112.0.0/14
52.120.0.0/14

The documentation should be consistent across the pages. I would recommend to document in both places the broader range, as it will not require customers to update their firewall rules when new smaller subnets are added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10b198f4-9576-a14d-4359-1e8cc0319cda
* Version Independent ID: ba7c3252-21d4-9be1-2a84-de2d51646f7b
* Content: [Plan for media bypass with Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan-media-bypass)
* Content Source: [Teams/direct-routing-plan-media-bypass.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan-media-bypass.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting Thomas!
