### ISSUE TITLE
Meeting limitation

### ISSUE THREAD

**Issue by MelissaApiou** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7416]
[Is it possible to update the meeting limitation in order to mention that, as of today, meeting is capped at 1000 if the registration page is enabled for the meeting,  when breakout rooms are enabled in the meeting the limit is 300. 
The view only extension to 20K is until end of CY2021]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#meetings-and-calls)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@MelissaApiou thank you for reaching out and helping improve MS Docs. Can you please confirm if you have seen any official documentation confirming this. I'll investigate in the meantime.

**Comment by MelissaApiou** [comment]
Hello Lindsay,

Thanks for reaching out to me.

The blog doesn't mention the view-only as part of the webinar experience : Introducing Webinars in Microsoft Teams: Easy, professional webinars to engage customers | Microsoft 365 Blog<https://www.microsoft.com/en-us/microsoft-365/blog/2021/05/11/introducing-webinars-in-microsoft-teams-easy-professional-webinars-to-engage-customers/>
About the date this article mentions that view-only up to 20K is extended to end of the year : View-only meeting experience - Microsoft Teams | Microsoft Docs<https://docs.microsoft.com/en-us/microsoftteams/view-only-meeting-experience>

For the Large meeting (1K) feature not being supported when Breakout rooms are enabled, this is described in Best practices for a large Teams meeting - Office Support (microsoft.com)<https://support.microsoft.com/en-us/office/best-practices-for-a-large-teams-meeting-ce2cdb9a-0546-43a4-bb55-34ab98ab6b16>

The Principal PM has also mentioned the following limitations in a chat room :
***@***.***D76393.34756490]
I'll send over any further material on these topics.

Thanks !

Kind regards,

Melissa Apiou
Technical Customer Success Manager - Meeting Ranger
'+33 1 57 75 10 59 |È+33 6 7 64 49 04 71 | * ***@***.******@***.***>

***@***.***D76396.09A7E000]

De : Lindsay ***@***.***>
Envoyé : jeudi 17 juin 2021 09:13
À : MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc : Melissa Apiou ***@***.***>; Mention ***@***.***>
Objet : Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Meeting limitation (#7416)


@MelissaApiou<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMelissaApiou&data=04%7C01%7Cmelissaapiou%40microsoft.com%7Cdc011bde189a46727c9a08d9315f5d50%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637595107955307604%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KH4mHt%2FP%2F24gp8hFnkzKEYRJyd41kmUDH7IuFyVWLRM%3D&reserved=0> thank you for reaching out and helping improve MS Docs. Can you please confirm if you have seen any official documentation confirming this. I'll investigate in the meantime.

-

**Comment by lindspea** [comment]
@MelissaApiou thanks for the links you added. I'll look into it.

**Comment by lindspea** [comment]
@MelissaApiou thanks again for your valuable input. The article has been updated. Please let me know if you have any other questions or recommendations.

**Comment by MelissaApiou** [comment]
Thanks a bunch for letting me know !

Have a great day ahead !

Cheers,

Melissa

De : Lindsay ***@***.***>
Envoyé : lundi 5 juillet 2021 10:08
À : MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc : Melissa Apiou ***@***.***>; Mention ***@***.***>
Objet : Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Meeting limitation (#7416)


@MelissaApiou<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMelissaApiou&data=04%7C01%7Cmelissaapiou%40microsoft.com%7Cf82ccd73f8cb48f34b2f08d93f8bfc78%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637610692761949852%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9aJiHqPIVdFnCCWp751YAdbqn0o6qeWFFl%2FkJL1%2F9Es%3D&reserved=0> thanks again for your valuable input. The article has been updated. Please let me know if you have any other questions or recommendations.

-

**Comment by lindspea** [comment]
@scanum this can be closed now thank you.
