### ISSUE TITLE
Max voice mail duration?

### ISSUE THREAD

**Issue by JasonSmith-MS** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7418]
[Enter feedback here]
Please clarify the maximum possible voice mail duration, and also whether there are any impacts to performance for setting it longer than 5 minutes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85634d87-7729-6449-9663-556097e75504
* Version Independent ID: b75446bd-07af-a7f2-d346-fe7634634548
* Content: [Manage Voicemail Policies - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-voicemail-policies)
* Content Source: [Teams/manage-voicemail-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-voicemail-policies.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @JasonSmith-MS, thank you for your feedback.

I'm almost sure that there is no hard limit. Exchange Online limits apply here:
https://docs.microsoft.com/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits

For example, the voicemail message cannot be higher than 150 MB.

@dstrome, maybe you can add something else. Thanks!

**Comment by dariomws** [comment]
@scanum I think we can close this issue. Thanks!
