### ISSUE TITLE
Ubuntu and other OS supports

### ISSUE THREAD

**Issue by RobinDadswell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7427]
Currently only certain commands work on non windows operating systems - when I try and do Get-CSOnlineUser I get the following: 

```
Get-CsOnlineSession: /home/robin/.local/share/powershell/Modules/MicrosoftTeams/2.3.1/netcoreapp3.1/SfBORemotePowershellModule.psm1:63
Line |
  63 |      $remoteSession = & (Get-CsOnlineSessionCommand)
     |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either
     | not installed or unavailable for this system.

Invoke-Command: /home/robin/.local/share/powershell/Modules/MicrosoftTeams/2.3.1/netcoreapp3.1/SfBORemotePowershellModule.psm1:9490
Line |
9490 |  …    -Session (Get-PSImplicitRemotingSession -CommandName 'Get-CsOnline …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'Session'. The argument is null or empty. Provide an argument
     | that is not null or empty, and then try the command again.
```

The document should mention more openly that the module doesn't work fully on non windows OS's and also it would be great if internally support can be improved for these operating systems as it would open a world of possibility around automation through Azure runbooks and also would allow for a more diverse administration platform (e.g. Ubunutu/MacOs etc.) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd283f6e-3865-ed70-d663-cc461ee8ba57
* Version Independent ID: 2450d311-fc04-d8b6-b4a2-b1890ec6fc3e
* Content: [Install Microsoft Teams PowerShell - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-install)
* Content Source: [Teams/teams-powershell-install.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-install.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
