### ISSUE TITLE
PowerShell: Passing Credentials to CQD

### ISSUE THREAD

**Issue by hdsouza** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7430]
Hi,
In Most cases like O365, Teams, Azure, one can connect seamlessly by passing credentials as variables. I am trying to do the same with CQD although whatever I try, it still prompts for credentials. 

Is this even doable? If so what would I need to change in my code so that it does not prompt for Credentials:

`
function Get-CQDToken ([string]$client_id)
{
  Add-Type -AssemblyName System.Web
  $resourceUrl = $WebResource
  $redirectUrl = "https://cqd.teams.microsoft.com/spd/"
  $nonce = [guid]::NewGuid().GUID
  $url = "https://login.microsoftonline.com/common/oauth2/authorize?response_type=token&redirect_uri=" +
  [System.Web.HttpUtility]::UrlEncode($redirectUrl) +
  "&client_id=$client_id" +
  "&prompt=login" + "&nonce=$nonce" + "&resource=" + [System.Web.HttpUtility]::UrlEncode($WebResource)

  Add-Type -AssemblyName System.Windows.Forms

  $form = New-Object -TypeName System.Windows.Forms.Form -Property @{ Width = 440; Height = 640 }
  $web = New-Object -TypeName System.Windows.Forms.WebBrowser -Property @{ Width = 420; Height = 600; Url = ($url) }
  $DocComp = {
    $Global:uri = $web.Url.AbsoluteUri
    if ($Global:Uri -match "error=[^&]*|access_token=[^&]*") {$form.Close()}
  }

  $web.ScriptErrorsSuppressed = $true
  $web.Add_DocumentCompleted($DocComp)
  $form.Controls.Add($web)
  $form.Add_Shown({$form.Activate()})
  $form.ShowDialog() | Out-Null

  $Script:TokenLifeTime = [Web.HttpUtility]::ParseQueryString(($web.Url -replace '^.*?(expires_in.+)$','$1'))['expires_in']
  $Script:Token = [Web.HttpUtility]::ParseQueryString(($web.Url -replace '^.*?(access_token.+)$','$1'))['access_token']
  
  return ('Bearer {0}' -f $Script:Token)
}

$userName = "aaron"
$password = "Password_1234" 
$configRest = Invoke-RestMethod -Uri "https://cqd.teams.microsoft.com/repository/clientconfiguration" -Method Get -SessionVariable WebSession -UserAgent "CQDPowerShell V2.0"
$WebResource = $configRest.AuthLoginResource
$AADBearerToken = Get-CQDToken $configRest.AuthWebAppClientId
$WebSession.headers.Add('Authorization',$AADBearerToken)
`

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by OsniNeto** [comment]
Hi @hdsouza 

I have the same necessity...
Can you share the resolution if you find?

Thanks

**Comment by hdsouza** [comment]
> 
> 
> Hi @hdsouza
> 
> I have the same necessity...
> Can you share the resolution if you find?
> 
> Thanks

I ended up opening a Microsoft case, but they asked for Business impact statement which ended up being a MS word doc running into several fields. If something constructive happens will update here.
