### ISSUE TITLE
Missing Information on "Setup Policy" setting for "Installed Apps"

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7432]
This page has no information on the **Installed apps**  setting ( See below) 

the only documentation seems to be in the admin portal, where developers will not be able to find this.
from the TaC https://admin.teams.microsoft.com/policies/app-setup/....
```
Installed apps
Choose which apps you want installed for your users. They can still install other apps that they want by setting up those apps in permission policies.
```
possible good to add a cross-ref to : https://docs.microsoft.com/en-us/MicrosoftTeams/teams-app-setup-policies

![image](https://user-images.githubusercontent.com/981654/122549996-6d43c700-d033-11eb-9f9b-f882ef379409.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f91604a-35b0-dfbb-55b2-b601cb0841b0
* Version Independent ID: 84bcd0d7-b4ed-f13e-c84b-2ec6a7661ae9
* Content: [Manage app setup policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-app-setup-policies)
* Content Source: [Teams/teams-app-setup-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-setup-policies.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by get-itips** [comment]
Hello @Josverl Jos, how are you?

Please let me know if I understood you well, however, I am seeing references to installed apps in the article you opened the issue for:

> To install apps for users, do the following tasks:
**Under Installed apps, select Add apps.**
In the Add installed apps pane, search for the apps you want to automatically install for users when they start Teams. You can also filter apps by app permission policy. When you've chosen your list of apps, select Add.

Thanks

**Comment by Josverl** [comment]
hmm, you are correct.
somehow I did not see that when I was looking for the information. 
seems like this is moot then 🤐
