### ISSUE TITLE
Does E1+PS add-on includes voicemail?

### ISSUE THREAD

**Issue by dariomws** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7438]
@dstrome @CLYVR could you kindly help me confirm if E1 plus Phone System add-on is enough to have cloud voicemail?

The following link says EXO Plan 2 for "hosted" voicemail:
https://www.microsoft.com/microsoft-365/exchange/compare-microsoft-exchange-online-plans
Hosted is for SfB on-prem accounts?

The following link says EXO Plan 2 for cloud voicemail:
https://docs.microsoft.com/skypeforbusiness/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/office-365-enterprise-e1-e3-e4

E1 includes EXO Plan 1.

I discussed this with some MVPs. Some of them say that it's working with E1. But the articles above are confusing.

Thank you so much!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8228f9b2-a7de-abb4-6f41-70db0b3af155
* Version Independent ID: 8fd9fafb-dd76-59a8-e609-56f06d539a31
* Content: [Set up Cloud Voicemail - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-phone-system-voicemail)
* Content Source: [Teams/set-up-phone-system-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-phone-system-voicemail.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by CLYVR** [comment]
Hi @dariomws.  E1 does not include cloud voicemail - need to add EXO2 or switch to E3.  It shouldn't be working for E1 unless they have some other licenses for those users.

**Comment by dariomws** [comment]
Thank you so much @CLYVR!

I think we should add this information to this article and others related, shouldn't we?

**Comment by CLYVR** [comment]
Hi @dariomws 

Not opposed to adding more information however I think it's fairly well documented right now.  

The first link shows that EXO Plan 2 is required for hosted voicemail and the second link shows that if E1 has been purchased then EXO2 or E3 is required for cloud voicemail.

**Comment by dariomws** [comment]
Thank you @CLYVR. I'm talking about this article, for example:
https://docs.microsoft.com/microsoftteams/set-up-phone-system-voicemail

It says:
"For Online Phone System users, Cloud Voicemail is automatically set up and provisioned for users after you assign a Phone System license to the users."

But it should work adding a Phone System license to an E1 account.

**Comment by CLYVR** [comment]
Hi @dariomws - your most recent comment made me go back and re-read your original question and my apologies, I see that I never really addressed the main question of E1+Phone System giving cloud voicemail.

E1, which includes EXO1 does not include voicemail and you need to add EX02 to get hosted voicemail or move to E3 which includes EXO2.

I'm double checking on E1 + Phone system (Office 365 Phone System).  On the surface this should give voicemail (and a lot of other functionality) but I just want to confirm with someone else first - will let you know.

**Comment by dariomws** [comment]
Thank you @CLYVR!

**Comment by CLYVR** [comment]
@dariomws Confirmed - E1+Phone System is valid combo and this should give voicemail.

**Comment by dariomws** [comment]
Thank you so much @CLYVR!

I think now I understand the logic. Phone System includes cloud voicemail (https://docs.microsoft.com/microsoftteams/what-is-phone-system-in-office-365#phone-system-with-services) and also EXO Plan 2. The last one is when you have an on-premises SfB user (so you don't buy a Phone System license) and want to provide him with cloud voicemail.

That's what is represented here, but it could be not very clear:
https://docs.microsoft.com/skypeforbusiness/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/office-365-enterprise-e1-e3-e4

Are you agree to apply the following update?
|||
|:-----|:-----|
|**To add this feature** <br/> |**Here's what you need to buy** <br/> |
|**Cloud Voicemail** (for on-premises users) <br/> |For E1 and E4 plans, buy Exchange Online Plan 2. <br/>Or, switch to an Office Suite that comes with Exchange Online Plan 2, such as Office 365 E3. |

Concluding that the Phone System license includes voicemail, I think you get it with F3+PS also. Not with F1 because it has a mailbox only for the calendar.

**Comment by dariomws** [comment]
I also think that we can add some note here:
https://docs.microsoft.com/skypeforbusiness/hybrid/plan-cloud-voicemail
Like a bullet in the requirements section:
- If the Skype for Business 2019 voice user has a mailbox on Exchange Online, an Exchange Online Plan 2 is required.

**Comment by dariomws** [comment]
@CLYVR, I've created the PRs to see if they are approved. Thanks!
