### ISSUE TITLE
Microsoft Teams live events Language cannot be translated

### ISSUE THREAD

**Issue by adong2838** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7440]
I have office E3 license. and I want to create a new live event.
 I set  the source language is english ,and translate to chinase.
![image](https://user-images.githubusercontent.com/26515794/122641837-4a500a80-d13a-11eb-8311-6c8cab74b129.png)

But in the live event, the translation was not successful.
I donot know why ,and I am very thanks if you can help me .

![image](https://user-images.githubusercontent.com/26515794/122642035-0f020b80-d13b-11eb-9bcc-13ce1be56051.png)
![image](https://user-images.githubusercontent.com/26515794/122642149-7e77fb00-d13b-11eb-8bed-d5d9ba60416e.png)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
