### ISSUE TITLE
Deprecated Content - View Designer

### ISSUE THREAD

**Issue by PDubDeluxe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7443]
This document is specifically for the View Designer configuration. With that now having been deprecated and unavailable, are you able to provide a Workbook equivalent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c813d7c-1789-d0c9-c833-cbdd3f60e2b8
* Version Independent ID: e5b7e6a7-2f78-dd58-b450-0d173935e26c
* Content: [Deploy Microsoft Teams Rooms management with Azure Monitor - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/azure-monitor-deploy)
* Content Source: [Teams/rooms/azure-monitor-deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/azure-monitor-deploy.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
