### ISSUE TITLE
Confusing explanation

### ISSUE THREAD

**Issue by LordBlackaddder** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7448]
A bit confusing explanation in next sentence 

"_These people cannot be added to teams unless they are invited as guests._"

I am under the impression that chat and meeting is also part of teams so this is why I would suggest to change it like next:

These people cannot be added to **a teams team** unless they are invited as guests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f080a5c-4268-1db4-566f-f1edc27920b5
* Version Independent ID: ac556a92-58af-3e05-f53b-0fc00afc96c0
* Content: [Use guest access and external access to collaborate with people outside your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/communicate-with-users-from-other-organizations)
* Content Source: [Teams/communicate-with-users-from-other-organizations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/communicate-with-users-from-other-organizations.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@LordBlackaddder Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @LordBlackaddder how are you? Hope you are doing great.

To my understanding, in that sentence, it is not referring to Microsoft Teams but actual teams, as it is not using a capital letter.

Look for the different use of the word further in the document, an example:

> Note that **Teams** allows you to invite people outside your organization to meetings. This does not require external or guest access to be configured.

hope this information helps you,

Thank you!

**Comment by LordBlackaddder** [comment]
In understand what you mean but i tend to disagree. We are talking about a tool which supports business here. I believe if you define a team in real world with internal and external members this has nothing to do with Microsoft Teams. I understand these people can be added to one-on-one and group chats and share screens but not exchange files. The chat and screen sharing is also functionality of Microsoft Teams isn't it? It's just limited since they can't share files (and perhaps some other functions). Bottom line: I believe it is a bit confusing :)

**Comment by get-itips** [comment]
Hello, how are you? Hope you are doing great! I understand your point of view @LordBlackaddder however, this is not only present in this document but in multiple Teams articles where it is understood that _teams_ refers to actual teams inside Teams.
Thanks for your feedback! 👍

**Comment by get-itips** [comment]
@scanum please kindly close.
