### ISSUE TITLE
Need PowerShell commands

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7449]
Hi.  For all the steps listed, please also provide the PowerShell commands.  Thanks
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e763c267-2c3a-190d-29e2-b5c81448fc10
* Version Independent ID: 98b73595-54ea-503c-ac3c-9df176543e9e
* Content: [Upgrade from Skype for Business Online to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/upgrade-to-teams-execute-skypeforbusinessonline#upgrade-users-in-stages)
* Content Source: [Teams/upgrade-to-Teams-execute-SkypeforBusinessOnline.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-to-Teams-execute-SkypeforBusinessOnline.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@ssmiller60 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
