### ISSUE TITLE
MS Teams public SBCs (for direct routing) are not a complete list

### ISSUE THREAD

**Issue by officialh1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7454]
sip.pstnhub.microsoft.com
sip2.pstnhub.microsoft.com
sip3.pstnhub.microsoft.com

Are the listed SIP providers from MS Teams to trust for this connection, there is a problem.  There is another and I have not be able to guess the DNS name for **52.114.148.0**

It actively sends invites to our SBCs and its not on the list here by name or IP.  If that is not in the SBC list, depending how one's system works (I am using Avaya SBC 8.1.1 hotfix 5), it will not trust that IP until you tell it to.  What this means is that periodically calls outbound from Teams will fail until it round robins to one of the other 3, giving about 25% outbound call failure rate.

-Walt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e26faf8c-529e-b317-5934-cd41cfe8fa24
* Version Independent ID: 3ddd5d0a-6dbb-4940-1814-8346e293701b
* Content: [Plan Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan)
* Content Source: [Teams/direct-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@officialh1 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
