### ISSUE TITLE
CreateSrsMedia.ps1 requires a windows version that is skipped/not recommended in MTR documentation

### ISSUE THREAD

**Issue by Mtbred** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7455]
Current version of the CreateSrsMedia.ps1 uses SRS deployment kit 4.8.31.1 which calls for the 10.0.19041.631 windows installation media (which appears to be a 2004 release).  https://docs.microsoft.com/en-us/microsoftteams/rooms/console#Prep_Media

The Teams Lifecycle documentation suggests skipping/ does not recommend 2004 releases due to compatibility issues: https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-lifecycle-support

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
