### ISSUE TITLE
Instructions are incorrect or don't work.

### ISSUE THREAD

**Issue by JeffsRealm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7457]
So I have been trying for 2 days to figure out how to enable shifts for my organization.  I am about to submit a support ticket but these instructions just simply are wrong.  

First it tells you  go to  Team Apps > Manage Apps  Which is not a valid menu choice, Teams Apps is there, Manage Apps is not. Under the other options I can not find anything remotely like the instructions are describing.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58ea9573-59b1-1499-fb83-517d0ee0f034
* Version Independent ID: bf98f739-ff51-0b90-dbc5-c594d3dacecd
* Content: [Manage the Shifts app for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams)
* Content Source: [Teams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@JeffsRealm Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @JeffsRealm, thank you for your feedback.

I've verified and it seems that the instructions are correct:
![image](https://user-images.githubusercontent.com/33589238/123634252-7fcfb480-d81a-11eb-9358-203a07698006.png)

**Comment by JeffsRealm** [comment]
If you are absolutely sure they are correct and this is how it is supposed to look then it would appear I have other issues,  this is what I see. I think I need to reach out to support.

![Capture](https://user-images.githubusercontent.com/25747811/123661991-04163d80-d803-11eb-81e4-1086b447c7de.JPG)

**Comment by dariomws** [comment]
@JeffsRealm yes please work with the support I think you need to check several things. For example:

- If you are a Teams Administrator or Global Administrator
- Licenses

**Comment by JeffsRealm** [comment]
Thanks, I will, going to close this, I am one of 2 Global Admins in the AAD DC Administrators role. I pretty much have access to everything. And everyone in the org is an E5 license.
