### ISSUE TITLE
Calling app in Teams for Education

### ISSUE THREAD

**Issue by johnkberry** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7459]
This document states that "The Calling app isn't available in Teams for Education."  While it is not pinned by default, it is in fact available, though it is called "Calls" and not "Calling" now.

![image](https://user-images.githubusercontent.com/31191773/123293541-12eab080-d4e2-11eb-8945-d45ead765aeb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f91604a-35b0-dfbb-55b2-b601cb0841b0
* Version Independent ID: 84bcd0d7-b4ed-f13e-c84b-2ec6a7661ae9
* Content: [Manage app setup policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-app-setup-policies)
* Content Source: [Teams/teams-app-setup-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-setup-policies.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by johnkberry** [comment]
Hi, there is no issue with my tenant -- the documentation is just out of date.
