### ISSUE TITLE
CsTeamsUpdateManagementPolicy is not documented

### ISSUE THREAD

**Issue by aizatharis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7467]
The CsTeamsUpdateManagementPolicy cmdlet is not documented. I do not know what parameter to turn off AllowPublicPreview. Plus, the result for Preview features in Teams Admin portal (it shows OFF) is not similar to the PowerShell result (it shows FollowOfficePreview).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5f1cdd1-09ff-f95d-6d50-e7880d34020f
* Version Independent ID: 59219640-305b-30c1-bc10-87e2633d95db
* Content: [Public preview in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/public-preview-doc-updates?source=docs)
* Content Source: [Teams/public-preview-doc-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/public-preview-doc-updates.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@aizatharis Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @aizatharis thanks for your feedback, you are right, cmdlet articles are currently missing, will ask for the creation of those articles, in the meantime, will propose an improvement to the article you opened the issue for.
