### ISSUE TITLE
Dead link for Microsoft telephony solutions

### ISSUE THREAD

**Issue by seeker** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7469]
The link for [Microsoft telephony solutions](https://docs.microsoft.com/en-us/SkypeForBusiness/hybrid/msft-telephony-solutions) in the section [Connect to the Public Switched Telephone Network (PSTN)](https://docs.microsoft.com/en-us/microsoftteams/what-is-phone-system-in-office-365#connect-to-the-public-switched-telephone-network-pstn) results in a 404 - page not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d45becfa-69d7-b956-cf97-4b14c97ad92c
* Version Independent ID: 81d5bad1-fc63-26dc-5c08-31c8d07c828d
* Content: [What is Phone System? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/what-is-phone-system-in-office-365)
* Content Source: [Teams/what-is-phone-system-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-is-phone-system-in-office-365.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@seeker Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@seeker thanks for reaching out and helping improve MS Docs. I found these two articles relating to the topic. Do they cover the topic and would you recommend replacing the dead link with one of them. - https://docs.microsoft.com/microsoftteams/cloud-voice-landing-page or https://docs.microsoft.com/skypeforbusiness/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/plan-phone-system-with-on-premises-pstn-connectivity

**Comment by seeker** [comment]
@lindspea   [https://docs.microsoft.com/microsoftteams/cloud-voice-landing-page](https://docs.microsoft.com/microsoftteams/cloud-voice-landing-page) would be a better fit at describing the possible telephony solutions.

**Comment by lindspea** [comment]
@scanum this can be closed, thank you.
