### ISSUE TITLE
Teams Migration: Unable to migrate Skype/Lync onpremise users to the cloud 

### ISSUE THREAD

**Issue by Madushka** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7470]
on-prem permission required is given only this permission CSServerAdministrator in the article 
 https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/move-users-between-on-premises-and-cloud#required-administrative-credentials

This was given an errors and required following permission addition it CSServerAdministrator was my experience 

- RTCUniversalServerAdmins
- RTCUniversalUserAdmins
- CSAdministrator

**Comment by scanum** [comment]
hank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
