### ISSUE TITLE
Missing mention about Set-CsTeamsTargetingPolicy for first-time setups

### ISSUE THREAD

**Issue by markuspelto** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7471]
I was struggling because the MicrosoftTeams PowerShell module (2.3.1) didn´t give me the Set-TeamTargetingHierarcy command. Then by accident, found this undocumented command called  Set-CsTeamsTargetingPolicy. Ran that and then I had the Set-TeamTargetingHierarcy command available. 

Not sure if this is intended, but it could be in the troubleshoot section, if not even in the main guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c03584a-ee6c-2594-1601-07dc2ae32371
* Version Independent ID: f8dc6040-5495-ef0b-bb78-0b3b1a7a14bd
* Content: [Set up your team targeting hierarchy - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-your-team-hierarchy)
* Content Source: [Teams/set-up-your-team-hierarchy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-your-team-hierarchy.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
hank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
