### ISSUE TITLE
Table statement about external users group chat

### ISSUE THREAD

**Issue by marcoszanre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7477]
The table "Things people outside your organization can do" states that "Be added to a group chat" action for "External access users" as not available, however, according to the "Chat and collaboration Group chat with external users" blog post, it is - https://techcommunity.microsoft.com/t5/microsoft-teams-blog/what-s-new-in-microsoft-teams-may-2021/ba-p/2391927

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f080a5c-4268-1db4-566f-f1edc27920b5
* Version Independent ID: ac556a92-58af-3e05-f53b-0fc00afc96c0
* Content: [Use guest access and external access to collaborate with people outside your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/communicate-with-users-from-other-organizations#feedback)
* Content Source: [Teams/communicate-with-users-from-other-organizations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/communicate-with-users-from-other-organizations.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for reporting @marcoszanre
