### ISSUE TITLE
This application is not in the Azure applications list

### ISSUE THREAD

**Issue by EliotWalker** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7480]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c3be94-d640-a20c-ac06-2653f443b74e
* Version Independent ID: 4760af98-c4e9-ab6a-6745-1381ffc068cc
* Content: [Set up Microsoft Teams meeting add-on for Google Workspace - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/google-workspace-addon-teams)
* Content Source: [Teams/google-workspace-addon-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/google-workspace-addon-teams.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@EliotWalker Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @EliotWalker thanks for reporting, looking into this.

**Comment by MicrosoftHeidi** [comment]
The author is not the technical reviewer, and may have no insight into technical changes to the product. The alias of the technical reviewer, which is listed in the article, is aravin.
