### ISSUE TITLE
Update URL Button Doesn't Work for Webhook connections

### ISSUE THREAD

**Issue by alittlesliceoftom** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7483]
Instructions suggest you press the button 'Update URL', but when you do, nothing happens, you can't then copy the (old url), nor press save. 

So you can't update webhook connections. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5eb6a35-32fa-6703-8ed2-0855e602b7d5
* Version Independent ID: 7890ca09-d505-35a9-071a-8662a4b19275
* Content: [Use Microsoft 365 and custom connectors - Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/office-365-custom-connectors)
* Content Source: [Teams/Office-365-custom-connectors.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-custom-connectors.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
