### ISSUE TITLE
Suggest additional clarity as to which HW the document applies to.

### ISSUE THREAD

**Issue by davidjfriedman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7487]
Team,

I'm confused as to which hardware the document refers to in several respects.  The title of the document implies that you are imaging the console, although it's unclear as to whether you're actually imaging a console or a compute module.  It would also be beneficial to point out whether it's supported to image non-certified NUCs (and other certified compute modules).  In addition, it would be beneficial to point out whether NUCs need to be sourced as part of a package or whether it's ok to buy your own NUC (or other certified compute modules).  For example, other documentation refers to a TPM chip in the NUC.  Is the TPM chip present in all NUCs by default, or only those that are purchased as part of a certified Teams Room package?  Is this document applicable to only current Teams Rooms, also to previous dock-based setups, or both?  (There is a dock reference in this document that confused me in this regard).

There are various forum posts on the web where people are asking these questions and referring to this particular document, so this would be a good place to add this clarification.

Thank you!

David
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/console#Prep_Media)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@davidjfriedman Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @davidjfriedman, thank you for engaging with the community here for the docs.

Non-certified NUCs/PCs are not supported. You can check the list of supported devices at the following link:
https://docs.microsoft.com/microsoftteams/rooms/requirements
This is an important document to check when you are deploying MTR devices. The console article is not enough.

The Teams Rooms app will not start until it verifies that you are using certified hardware. So no matter what, you must purchase an approved, certified hardware solution.

The ability to make your own image is only intended for large corporations to customize the image on certified hardware. It is definitely not a roll-your-own, ad-hoc solution.

**Comment by davidjfriedman** [comment]
@dariomws, thanks for your reply and clarification--much appreciated.  My concern is that the console article as it is written leaves this open to interpretation.  I understand that we may not be looking to turn the console document into another redundant requirements article, although there may be room to sprinkle several disclaimers and warnings to more clearly spell this out, possibly with additional references to the requirements document.

David

**Comment by dariomws** [comment]
@davidjfriedman rechecking the article I found there is an important note about that:
> [!IMPORTANT]
> Microsoft Teams Rooms relies on the presence of certified console hardware. Even a correctly created image containing the Microsoft Teams Rooms console app will not boot past the initial setup procedure unless the console hardware is detected. For Surface Pro based solutions, the Surface Pro must be connected to its accompanying dock hardware to pass this check.

I'll add a link to the requirements article.
