### ISSUE TITLE
please update number of video calls per meeting under Meetings and Calls section.

### ISSUE THREAD

**Issue by goodwoodrevival** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7489]
please update number of video calls per meeting under Meetings and Calls section.  The topic is about Meetings and Calls so there should be no chat information in this section for clarity.

This should state that the number of people in a video call is 9 per meeting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@goodwoodrevival Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @goodwoodrevival how are you?
I think the limit that you are mentioning (9) is for active speakers (3x3 gallery view), this is different from the article that is talking about the ability to start a video call from a group chat with 20 participants as a maximum. (Tested this and it's the current limit).
Hope this information helps you,

**Comment by goodwoodrevival** [comment]
Yes, that is what I am referring to which should be included in the "Meetings and Calls" section instead of the "video call from a group chat" the topic being discussed is about "Meetings and Calls" NOT group chat which was in the previous section.   I hope that is clear.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
