### ISSUE TITLE
Upload configuration profiles - Teams Phones

### ISSUE THREAD

**Issue by sl14a** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7491]
The following page has a section "Use configuration profiles in Teams" where it talks about being able to "upload configuration profiles". I cannot see this option in the Teams Admin portal. Can you provide additional details as to how this profile can be uploaded and what the file format should be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a627b5d-3edc-1add-b921-1dcd49c38653
* Version Independent ID: a2e2bd3a-31c0-471a-05fb-fd64bd942c4a
* Content: [Manage your devices in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/device-management)
* Content Source: [Teams/devices/device-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/device-management.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@sl14a Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @sl14a, thank you for your feedback and help us to improve docs.microsoft.com.

The article includes instructions to create configuration profiles and assign them. Each device types in the Teams Admin Center have a Configuration profiles tab, except for Teams Rooms. For example:
![image](https://user-images.githubusercontent.com/33589238/124673967-24589300-deba-11eb-8dbe-ba33b48827f5.png)
I'll add some more detail to the article.

**Comment by tiburd** [comment]
The article has been updated.

cc: @scanum
