### ISSUE TITLE
Articles needs to be update and Clarity

### ISSUE THREAD

**Issue by SanguptaMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7496]
[Enter feedback here]

The article doesn't contain information about the Android based devices where only 'CAP' licenses are assigned. under the Configure Intune to enroll Teams Android-based devices section. Clarity needs to be added that Step 1 and step 2 needs to be followed also for the devices where only 'CAP' licenses are assigned.
We had multiple tenants impacted due to this. 

ICM : 245590300 and 241818509 

These are engineering escalations which were raised to confirm. This Github request is raised after agreement with TEAMS Devices PM - Kruthika

please reach out if needs more clarification

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 407c4f68-9737-d86c-2a08-cbbeaef6da00
* Version Independent ID: 3324088c-b0b2-dec3-575d-c1fb76bfb730
* Content: [Deploy Teams phones and Teams displays using Intune - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/phones-displays-deploy#configure-intune-to-enroll-teams-android-based-devices)
* Content Source: [Teams/devices/phones-displays-deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/phones-displays-deploy.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by ndambrosio** [comment]
Probably not a good idea to share internal URLs and aliases in a public forum.

**Comment by SanguptaMSFT** [comment]
Edited it. @ndambrosio

**Comment by scanum** [comment]
@SanguptaMSFT Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by cichur** [comment]
We updated the article with the additional information. The changes are now live https://docs.microsoft.com/en-us/microsoftteams/devices/phones-displays-deploy#configure-intune-to-enroll-teams-android-based-devices
