### ISSUE TITLE
Updating JDA to Blue Yonder

### ISSUE THREAD

**Issue by makurtz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7497]
JDA has been rebranded "Blue Yonder". Could we please get this updated in the documentation on this page in the following paragraph:

Workforce management integrations If you're using third-party workforce management systems, such as Kronos and **_JDA_**, for scheduling, time, and attendance, you can integrate directly with Shifts through Shifts Graph APIs and SDK with open source integrations.

Also, is there a way to do this site wide?  Thanks - mark
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d798fd2-201d-9ab8-406e-c84985344959
* Version Independent ID: 05b27b16-ec74-5064-fd8d-9c29b967a66e
* Content: [Shifts for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/expand-teams-across-your-org/shifts-for-teams-landing-page)
* Content Source: [Teams/expand-teams-across-your-org/shifts-for-teams-landing-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/expand-teams-across-your-org/shifts-for-teams-landing-page.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by RAJU2529** [comment]
@cichur , can i rename JDA to Blue Yonder in this article ,I  conformed name changed from below article
**https://en.wikipedia.org/wiki/Blue_Yonder**
