### ISSUE TITLE
Insufficient data in UserActivityDetail

### ISSUE THREAD

**Issue by mtif1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7498]
The current UserActivityDetail reports (and graph) for Teams, only list the summary totals of activity per user. This fine to monitor delivery volumes but insufficient for my needs. 

Our service is delivered by video conference between specific participants. I want to measure completion of those meetings. Therefore I want to be abe to view individual meetings, their participants and date/time specifics. 

At the moment I can only access these by labouriously going thru users in the UserActivityDetail list, going into each user in turn, and then each Meeting ID within each user .... or I could rely on manual records ! 

Frustratingly all the data I need is within Teams but not in a readily accessible format.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81440b2f-391b-5856-a216-15866f37082a
* Version Independent ID: cdd15cd4-d4ed-c413-e2b9-ebf6dad8b33b
* Content: [Use activity reports for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-activity-reports)
* Content Source: [Teams/teams-activity-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-activity-reports.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
