### ISSUE TITLE
Add-Ons to M365 Business Plans

### ISSUE THREAD

**Issue by SilviaEid** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7502]
Hi,

this page seems to indicate that Phone System and Calling Plans may not be added as standalone Add-Ons to M365 Business Plans and the customers have to order Business Voice. However, according to the Commercial Licensing Terms you can add Phone System and the Calling Plan:

License Prerequisites 
License	License Prerequisites
Phone System	Office 365 F3/E1/E3/A3; Microsoft 365 Business Basic/Business Standard/Business Premium/F1/F3/E3/A3
Calling Plan	Office 365 E5/A5; Microsoft 365 E5/A5; Phone System

(from https://www.microsoft.com/licensing/terms/productoffering/AudioServices/MCA)

Best regards,

Silvia Eid
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abae7324-861d-7ca7-7239-a5df8fd927d5
* Version Independent ID: 8a30bd2f-9bc3-a0a8-8b31-d53836ead4d0
* Content: [Microsoft Teams add-on licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=small-business)
* Content Source: [Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by SilviaEid** [comment]
Hi,

I work for the Microsoft LicenseQ Team and a submitter from Microsoft made me aware of the difference in the information on the page and in the Commercial Licensing Terms. I don't need support, I just thought it might be better if the information on the page and in the Commercial Licensing Terms is aligned.

Best regards,

Silvia
