### ISSUE TITLE
MTR on Android Release Names

### ISSUE THREAD

**Issue by Nyffe-Noob** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7503]
The MTR on android versions are not named identical in the M365 message center and on this webpage.
The latest announcements in the M365 message center are named **Microsoft Teams Rooms Update (July Edition)** and **Microsoft Teams Rooms Update (June Edition)**. On this page, they are named with a product release name like **2021 Update #2**. It is very hard to identify the release versions with this inconsistent naming. For instance, im not sure if the July Edition is the Update 2021 #2 (which is released on june 28th) or if this is a new update, which is not yet listed on your webpage. Could you please aligne the naming on the M365 message center and this webpage?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaaef9e1-8f1c-ebf0-7856-4c007342a2c3
* Version Independent ID: 3eaf671f-375e-8787-9c66-3947c3606559
* Content: [Devices for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/teams-ip-phones#currently-certified-teams-rooms-on-android)
* Content Source: [Teams/devices/teams-ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/teams-ip-phones.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@Nyffe-Noob  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Nyffe-Noob how are you?
Can you share here this "_The latest announcements in the M365 message centers_" because I tried to find them in the 365 Message Center but couldn't. So I can compare with the information in this article you opened the issue for.
Thank you

**Comment by Nyffe-Noob** [comment]
New Microsoft Teams Rooms Update (July Edition)
MC266240 · Published Jul 1, 2021

Message Summary
Our next update for Microsoft Teams Rooms on Android contains the following updates:

Calling and meeting video optimizations for frozen and no video instances
Connectivity improvements between touch console, meeting room bar, and mobile room remote
Access to the dial pad from a remote controller during calls and meetings
Ability to send feedback and report a problem from touch console
When this will happen:

This update is available beginning today, July 1, 2021.

How this will affect your organization:

The update will be available for users accessing Microsoft Teams Rooms on Android

What you need to do to prepare:

Please plan on updating all Microsoft Teams Rooms on Android in your tenant to the latest version. You might want to notify your users about these new features and update your training and documentation as appropriate.

**Comment by Nyffe-Noob** [comment]
New Microsoft Teams Rooms Update (June Edition)
MC264359 · Published Jun 24, 2021

Message Summary
Our next update for Microsoft Teams Rooms on Android will contain the following updates:

Simpler sign in screen: A new, simpler sign in user interface has been introduced.
Remote provisioning & Remote sign in of Teams Rooms from Teams Admin Center: Users can provision their device from the Teams Admin Center and remotely login too. NOTE: An added step to pair a touch console with the Teams Room system may be needed. This step must still be done locally on the device.
Room Remote: Users have a new way to control the Teams Rooms. When a user is in a same meeting on a Teams device such as a mobile phone and a nearby room system, they can invoke a room remote which allows users to control room functionality including mic, camera, volume, live captions, and layouts. IT admins can disable this functionality from Teams settings.
HDMI Ingest: Select Teams Rooms devices will support sharing content through an HDMI input port. Users can plug in a sharing-capable device (e.g., laptop) to an HDMI port on the device and project content to the front of the room display when not in the meeting or share content during the meeting. Although sharing will start automatically, users can control projection functionality through a new home screen button.
Live Captions for 1:1 calls: This feature extends live captions to calls. Microsoft Teams Rooms on Android can now detect what's said in a call and present real-time captions in 1:1 calls.
Lock Meeting: Users that are assigned presenter or organizer roles can select the “Lock meeting” function from the “More” menu and effectively prevent any additional participants from joining a meeting.
Hide Meeting titles in the calendar: You can now have the flexibility to hide meeting titles in the calendar. NOTE: Work with your OEM manufacturers to see when this feature will be available on your devices
Auto- Answer for meet now: Teams admins on MTR-A can now enable a setting to auto answer a call from a Teams device, which will pull the room device into the ad hoc meeting with just one click. This will be especially useful in settings like telehealth for rounds and patient check-ins.
1080p resolution on outgoing video: With this latest update, MTR-A now supports 1080p resolution for outgoing video.
When this will happen:

This rollout began on June 23.

How this will affect your organization:

The update will be available for users accessing Microsoft Teams Rooms on Android

What you need to do to prepare:

Please plan on updating all Microsoft Teams Rooms on Android in your tenant to the latest version. You might want to notify your users about these new features and update your training and documentation as appropriate.

**Comment by get-itips** [comment]
Hello @Nyffe-Noob I confirm I passed the feedback. Thanks
@scanum please close.
