### ISSUE TITLE
The documentation needs to be clear on *what* needs to be enabled in Lists

### ISSUE THREAD

**Issue by DeanCron** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7504]
There's currently a note in this article that states:

"Additionally, Microsoft Lists needs to be set up in SharePoint. "

This needs clarification, that **personal** lists in Microsoft Lists need to be enabled. It would also be helpful to note why this is necessary so customers understand what personal lists are being used for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2fe730-a95d-d12d-adb8-49d1397c77c7
* Version Independent ID: 1f6077c3-6114-cb5e-8b1a-7587188f2cdf
* Content: [Set up for webinars in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-webinars)
* Content Source: [Teams/set-up-webinars.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-webinars.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by scanum** [comment]
@DeanCron  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
