### ISSUE TITLE
Please add hint in documentation: Configurable properties only available in Store Apps

### ISSUE THREAD

**Issue by serverless-me** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7506]
Schema version 1.10 with configurable properties cannot be used for sideloading. The feature is only working with apps published to the store ([Link](https://docs.microsoft.com/en-us/answers/questions/408427/unable-to-sideload-custom-app-with-teams-manifest.html)). This should be a hint on the page, so that developers do not try and fail and wonder and loose time. 

Please add this information on both pages to reduce confusion for developers:

- https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/customize-apps.md
- https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema

**Comment by scanum** [comment]
@serverless-me Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @serverless-me Michael, how are you? Hope you are doing good.
I reviewed the issue you created, I will propose an improvement to the customize apps article, however, the schema one is in another Docs repo that is handled by another team.
Thanks for your feedback.
