### ISSUE TITLE
User authentication proxy is not supported for Teams Add-in

### ISSUE THREAD

**Issue by pandawelch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7510]
[Enter feedback here]

For the Teams desktop application when using the Teams Outlook Addin, use of a user authentication session forward proxy is not supported. A standard non-authenticating proxy is supported however.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 826084d1-06f7-e837-bcfc-d86d427288f6
* Version Independent ID: 9b36168e-d398-0188-c510-4dc5dd5f9563
* Content: [Proxy servers for Teams or Skype for Business Online - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/proxy-servers-for-skype-for-business-online)
* Content Source: [Teams/proxy-servers-for-skype-for-business-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/proxy-servers-for-skype-for-business-online.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @pandawelch how are you?
I could **not** reproduce it, do you have more information so I can dig in?
Thanks

**Comment by get-itips** [comment]
@scanum please close.

**Comment by pandawelch** [comment]
Hi, sorry for delay - no need to reproduce its referenced here: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md

So there are features that do not work behind a proxy. Over to you if it is worth referencing features that are know to not work at all. Cheers, Andrew
