### ISSUE TITLE
Any plans for support for ARM64 platform?

### ISSUE THREAD

**Issue by chraaroe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7512]
With the recent addition of an ARM64 Teams client are there any plans of making the Teams Rooms deployment kit compatible with ARM64 - e.g. Windows 10 IoT Enterprise?

It looks like it isn't currently supported.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
