### ISSUE TITLE
Description for Domain and Forest changes

### ISSUE THREAD

**Issue by thomasbinder** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7513]
Hi,
the article says:
"Undo Skype for Business Server Active Directory Domain forest-level changes by running the following Skype for Business Server PowerShell cmdlet: Disable-CsAdDomain"

However, my understanding this command will not undo the forest-level. Instead it will undo Skype for Business Server Active Directory Domain level change

Also:

"Undo Skype for Business Server Active Directory Domain schema changes by running the following Skype for Business Server PowerShell cmdlet: Disable-CsAdForest"

However, my understanding is that the Schema itself will not be changed. Instead it will undo Skype for Business Server Active Directory forest-level change

Thanks,
Thomas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 809826d2-e82d-0b31-0c8b-c475db0efbb8
* Version Independent ID: b4e15a5f-8096-21db-c120-63e99d601328
* Content: [Decommission Skype for Business Server - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/decommission-remove-on-prem)
* Content Source: [Skype/SfbHybrid/hybrid/decommission-remove-on-prem.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/decommission-remove-on-prem.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
