### ISSUE TITLE
Translation issue Portability being translated as Pornography

### ISSUE THREAD

**Issue by ddaanniieell9** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7515]
Hello:

The following document has the following entry
https://docs.microsoft.com/en-us/microsoftteams/phone-number-calling-plans/manually-submit-port-order
"What else should you know about number porting"

This same document in Spanish ES-ES or ES-MX, etc will translate porting as pornography (pornografía)
https://docs.microsoft.com/es-mx/microsoftteams/phone-number-calling-plans/manually-submit-port-order
"¿Qué más debería saber sobre la pornografía de números?"

Please check and correct.

Thank you,
Daniel Portal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca4cd82c-d4e0-fd46-a9d6-19c46e217b7a
* Version Independent ID: d4a536ae-1f0d-fab5-4617-a414b829374a
* Content: [Manually submit a port order - Microsoft Teams](https://docs.microsoft.com/EN-US/microsoftteams/phone-number-calling-plans/manually-submit-port-order)
* Content Source: [Teams/phone-number-calling-plans/manually-submit-port-order.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phone-number-calling-plans/manually-submit-port-order.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by dariomws** [comment]
Hi @ddaanniieell9, thank you for your feedback and help us to improve docs.microsoft.com.

@OfficeGlobal could you kindly help? Thanks!

**Comment by dariomws** [comment]
@OfficeGlobal could you kindly help? Thanks!

**Comment by TinaMcN** [comment]
@ddaanniieell9 I'm so sorry about this issue.  I sent it to our translators to fix asap.

**Comment by TinaMcN** [comment]
@ddaanniieell9 the article has been fixed now.  Our machine translation team are also investigating why it happened to avoid it recurring.  Thanks so much for reporting this issue.
Regards,
Tina

**Comment by tiburd** [comment]
@scanum
