### ISSUE TITLE
Update docs to details changes in MicrosoftTeams 2.4.0-preview

### ISSUE THREAD

**Issue by robinmalik** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7516]
This page requires updating to reflect changes in https://www.powershellgallery.com/packages/MicrosoftTeams/2.4.0-preview (released 21 days ago). 

Thank you :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 173b5929-529b-938b-b6ab-59f05a5d69a8
* Version Independent ID: 0a3dfe5e-938f-933d-637e-b7449e3b8aa5
* Content: [Microsoft Teams PowerShell Release Notes - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes)
* Content Source: [Teams/teams-powershell-release-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-release-notes.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @robinmalik Robin

**Comment by robinmalik** [comment]
Version 2.4.1 was released 13 days ago, and unfortunately there are still no notes on what changed in 2.4.0 or the latest 2.4.1.

**Comment by get-itips** [comment]
Release notes article has been updated.
@scanum please close.
