### ISSUE TITLE
Please review CC purchase method as this is not reflecting current customer experience 

### ISSUE THREAD

**Issue by anapereiCRMSE** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7517]
https://docs.microsoft.com/en-us/microsoftteams/set-up-communications-credits-for-your-organization#step-2-set-up-communications-credits-for-your-organization
Step 2: Set up Communications Credits for your organization

1. Sign in to the Microsoft 365 admin center with your work or school account.

2. In the left navigation of the Microsoft 365 admin center, go to Billing > Purchase Services. Scroll down and select Add-Ons.
**Select Details** Communications Credits.

3. **On the Communications Credits subscription page, select payment method and on the items in this order select Apply auto- recharge to see Auto-recharge settings.** 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 277cf140-5c6c-82c7-cc56-490ef2188754
* Version Independent ID: 72e7de29-fd71-23bf-15a7-172634c2a5fd
* Content: [Set up Communications Credits for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-communications-credits-for-your-organization)
* Content Source: [Teams/set-up-communications-credits-for-your-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-communications-credits-for-your-organization.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@anapereiCRMSE I am looking into this. Thanks
