### ISSUE TITLE
Uncovered scenario

### ISSUE THREAD

**Issue by robertpp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7523]
The script doesn't cover the situation where Teams gets installed in the ProgramData path. The script should offer the option to check the alternative path.

$TeamsPath = [System.IO.Path]::Combine($env:PROGRAMDATA, [Environment]::UserName, 'Microsoft', 'Teams')

Reference:
[Case #:26078717]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a316aa8-e3c9-c6d3-2509-6b4601ad3e8a
* Version Independent ID: 1e90dd88-4afd-ef8c-2f16-0263416ce5bb
* Content: [PowerShell script sample - Teams deployment cleanup - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/scripts/powershell-script-deployment-cleanup?source=docs)
* Content Source: [Teams/scripts/powershell-script-deployment-cleanup.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/scripts/powershell-script-deployment-cleanup.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @robertpp, thank you for your feedback.

This script uninstalls the Teams app and removes the Teams directory for a user. It doesn't cover the Teams Machine-Wide Installation as described in the description of the article.

**Comment by robertpp** [comment]
I suspect that Teams would install in ProgramData path regardless, if AppData is blocked. Since I don't hold it for a fact at this time, we can leave it like this. Thank you for your attention.

**Comment by dariomws** [comment]
@robertpp thank you for your comment.

@scanum could you kindly close this issue? Thanks!
