### ISSUE TITLE
Page is OLD - not aware of Teams multi-geo

### ISSUE THREAD

**Issue by JAndre7** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7524]
Teams multi-geo has gone GA for chats and channel conversations yet this page still says Teams does not support that. Please update the page to reflect the correct status. The latest public content is on this page (https://docs.microsoft.com/en-us/microsoft-365/enterprise/multi-geo-capabilities-in-teams-in-microsoft-365?view=o365-worldwide) to which this one should refer. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c65240c7-8a9e-cf39-008d-2c8b12534b0d
* Version Independent ID: 9a1e12a6-f020-7782-e749-8e4909fa8d0c
* Content: [Teams experience in a Microsoft 365 Multi-Geo-enabled environment - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-experience-o365odb-spo-multi-geo)
* Content Source: [Teams/teams-experience-o365odb-spo-multi-geo.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-experience-o365odb-spo-multi-geo.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
Thanks, @JAndre7. This page is in the process of being retired and should redirect to the link you mention within the next few days.

**Comment by get-itips** [comment]
@scanum The redirect is in place now, this can be closed.

**Comment by get-itips** [comment]
@scanum please close
