### ISSUE TITLE
conflicting statements

### ISSUE THREAD

**Issue by fariajohnc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#753]
For PSTN direct routing, does the user have to be in TeamsOnly Mode or can they be in Island Mode?  This page has 2 statements that seem to conflict:

“To use Teams Phone System features, users must be in TeamsOnly mode (i.e., homed in Skype for Business Online and upgraded to Teams),”

Which seems to conflict with:

“Islands 
◦If the user is homed online, the user has Phone System, in which case the user:◦Initiates and receives PSTN calls in Teams if the user is configured for Direct Routing”

so these are at odds - can a user in islands mode on Teams use Teams Direct Routing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49921e8a-55ac-f547-d4e2-d329f5089c2e
* Version Independent ID: 91c3433a-3684-95cd-3426-4a5877b33106
* Content: [Migration and interoperability guidance for organizations using Teams together with Skype for Business](https://docs.microsoft.com/en-us/MicrosoftTeams/migration-interop-guidance-for-teams-with-skype#federation-considerations)
* Content Source: [Teams/migration-interop-guidance-for-teams-with-skype.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/migration-interop-guidance-for-teams-with-skype.md)
* Service: **msteams**
* GitHub Login: @arachmanGitHub
* Microsoft Alias: **MyAdvisor**

**Comment by AndreaBarr** [comment]
@fariajohnc Thank you for this feedback. 

I want to make sure you get the clarification that is needed here. Support will be able to answer these questions about the Teams direct routing. 

I know the product teams are always looking for user feedback and how to make the OneDrive / SharePoint better. They keep a close tab on User Voice [https://sharepoint.uservoice.com](https://sharepoint.uservoice.com) and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too.

Thank you for your contribution to make the docs better! Much appreciated!
