### ISSUE TITLE
MTR Machine OU Creation 

### ISSUE THREAD

**Issue by Norafify89** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7531]
Hi, 

https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-operations#configuring-group-policy-for-microsoft-teams-rooms 

May i know the location of each setting GPO for MTR OU? 
Example below : 
![image](https://user-images.githubusercontent.com/81559366/125387217-2053d600-e3d0-11eb-85ce-32265b527506.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd52fe62-457b-c9e1-ad13-a9b1f24c9c38
* Version Independent ID: 6a8c3285-30e1-15a8-6472-f0cfe5b30e20
* Content: [Microsoft Teams Rooms maintenance and operations - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-operations#configuring-group-policy-for-microsoft-teams-rooms)
* Content Source: [Teams/rooms/rooms-operations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-operations.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
