### ISSUE TITLE
Nice documentation...

### ISSUE THREAD

**Issue by ivo-yosifov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7532]
Dear Microsoft. Your documentation is beyond useless. If you had paper copy of it, I'd use it as toilet paper
or kindling wood. I've spent 30 minutes to search how to enable the selection for teams meeting in google calendar to come across the solution in a third party website. Neither the steps that you provided in this (and many other articles) are relevant, nor the articles have links to the administration portals that one needs to use. The documentation is interlinked with other random articles that are totally not relevant to the issue.

Think about it. I need to use the google search engine to find another 3rd party site with community articles to solve my MS related issue. Is the goal of this execise to sell more windows/azure administration courses because literally noone can deal with your products if they follow the atrocious scribblers just like a corrupt univesity professor writes and sells the textbooks he authored which have obscure content just to make the students come for private tutoring

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

don't tell me what to do
* ID: 00c3be94-d640-a20c-ac06-2653f443b74e
* Version Independent ID: 4760af98-c4e9-ab6a-6745-1381ffc068cc
* Content: [Set up Microsoft Teams meeting add-on for Google Workspace - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/google-workspace-addon-teams)
* Content Source: [Teams/google-workspace-addon-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/google-workspace-addon-teams.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
