### ISSUE TITLE
Incorrect info about WhoCanRegister default

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7533]
"By default, WhoCanRegister is enabled and set to Everyone."

According to the Message Center post, this was released with EveryoneInCompany instead of Everyone as the default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2fe730-a95d-d12d-adb8-49d1397c77c7
* Version Independent ID: 1f6077c3-6114-cb5e-8b1a-7587188f2cdf
* Content: [Set up for webinars in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-webinars)
* Content Source: [Teams/set-up-webinars.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-webinars.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by scanum** [comment]
@npherson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @npherson Nash, how are you?
Can you kindly share the message center post that mentions that? I could not find it.
I got information from the team and I was informed that the default would be "Everyone" for any new tenant and that this was rolling out.
Thank you

**Comment by get-itips** [comment]
@scanum please close.
