### ISSUE TITLE
This page is not being updated to reflect the changes made to Teams Microsoft Doc pages

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7534]
This page is not being updated to reflect the changes made to Teams Microsoft Doc pages
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3081f70c-d927-ce5d-d957-ca7ba7e07a55
* Version Independent ID: 17704162-7ff9-015c-30a1-1cbc078f0782
* Content: [Microsoft Teams content updates - Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/teams-updates)
* Content Source: [Teams/teams-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-updates.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@nikki-c Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @nikki-c, thank you for your feedback.

An automatic task runs each week to processes all the data to generate this topic in real-time as changes are published live.

@dstrome @LolaJacobsen could you kindly confirm that this process is still working? Thank you!

**Comment by dariomws** [comment]
@dstrome @LolaJacobsen could you kindly confirm that this process is still working? Thank you!

**Comment by dstrome** [comment]
resolved.
