### ISSUE TITLE
Update Operator Connect public documentation to include PowerShell step to EV enable user after unassigning calling plan.

### ISSUE THREAD

**Issue by greganth1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7538]
Update Operator Connect public documentation to include PowerShell step to EV enable user after unassigning calling plan.
See VSO work item 2487762

This would be for the section "Move numbers from Calling Plans to Operator Connect"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 709c5bb1-843a-c243-16b6-86bd9f114d37
* Version Independent ID: e5e9415f-bd40-4084-e280-59be5cc186a6
* Content: [Configure Operator Connect - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/operator-connect-configure)
* Content Source: [Teams/operator-connect-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/operator-connect-configure.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by scanum** [comment]
@greganth1 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @greganth1, thank you for your feedback.

If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=greganth1

**Comment by dariomws** [comment]
@greganth1 I don't have access to the VSO work item 2487762.

Why is it only related to "Move calling plan numbers to Operator Connect"? Shouldn't all Operator Connect users be EV-enabled?

**Comment by dariomws** [comment]
@CarolynRowe @cazawideh maybe you can help here. Thanks!

**Comment by greganth1** [comment]
The reason is that that a Calling Plan user (Managed Carrier) is already EV enabled but currently when removing the calling plan license the EnterpriseVoiceEnabled parameter gets set to False and needs to be changed back to True before you can assign an Operator Connect number.

For the "Aquire numbers for new Teams users" section.  The user is EV enabled automatically when the Phone System license is assigned so no additional step is required.

For Direct Routing to Operation Connect the user is already EV enabled and there is no calling plan to remove that would result in EV enabled being set to false.

But, Yes a user needs to be EV enabled to assign a phone number if you want to call that out if the admin is not finding the user in the Team Admin Center to assign the phone number.

**Comment by dariomws** [comment]
Thanks @greganth1 for the detailed explanation.

I'm testing it in my lab to understand better, but I still have some comments:
- I've 4 users with a domestic calling plan. I removed the CP for one of them, but it appeared as EV disabled after a couple of minutes. This looks good.
- I have a lot of users with E5, and they have assigned the Phone System App. But they are not EV enabled. I also tried to add a Phone System license to another account, but it does not appear yet as EV enabled. Maybe there are other steps in the "Aquire numbers for new Teams users" section that automatically enables the user for EV?

**Comment by greganth1** [comment]
For that second if they are not appearing as EV enabled something may have changed or I may be wrong.  Either way it looks like a step to EV enabled the user needs to be added or at least a check of whether there are.  Can't assign a phone number without being EV enabled.

**Comment by CarolynRowe** [comment]
@mattiatocco   Can you help with this Mattia?

**Comment by mattiatocco** [comment]
Thanks for looking into this. With Operator Connect, the EV flag is set automatically during number assignment, there isn't the need for an additional step to se it to true. Thanks.

**Comment by greganth1** [comment]
Without the EV flag set to true they user is not found to assign to the number in the TAC.

**Comment by mattiatocco** [comment]
This shouldn't be the case, the user (assuming PS and TeamsOnly are there) should show up - This is true as well for a brand new user, even if not removing CP. Do you have a repro that we can look into?

**Comment by greganth1** [comment]
I was unable to repro the original behavior.  It's not required for the user to be EV enabled before assigning a phone number from the OC partner.
Closing this request.
