### ISSUE TITLE
Need Enterprise-class configurability

### ISSUE THREAD

**Issue by KyleSchroeder** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#755]
If Teams is really supposed to supplant Skype in the near future, then some effort needs to be put into making it Enterprise-ready!  I can't have users getting popups from Windows firewall and just tell them to click Cancel!  How is that possibly acceptable.  GPO-based configuration for the client (along with an enterprise-deployable package) is needed, and at least documentation on how to configure the client-side firewall rules.  Telling users to "click Cancel" just sets a bad precedent for user behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@KyleSchroeder Thank you for your feedback.

 I want to get this to support and our Teams team so it can be tackled on both ends. I am getting this sent over to the SharePoint teams backlog. 

I also need you to send this in as a request to the support team. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by kenwith** [comment]
@KyleSchroeder - I know the issues you brought up are on the radar of the Teams product team. There is an active Enterprise community discussing and up-voting these items on teams.uservoice.com and the product team uses that input as they work on their feature plan. I also know some of the Teams product teams and will bring these points up to them in person and if you can up-vote items you agree with on teams.uservoice.com that will be super helpful too. Thanks for taking the time to submit this feedback and make the product better for Enterprise. All the feedback I can provide to the Teams product team is beneficial and they listen to all of it I know for a fact. Thanks, Ken

**Comment by cbujak** [comment]
@kenwith - I attempted to access teams.uservoice.com and it is reported as no longer available.  Where can we go to make our needs known?  I'm looking to deploy Teams in a non-persistent virtual desktop. There is no way I can expect my users to download and install this every day. I need an installer for the master image, and GPOs to help with configuration.

**Comment by AndreaBarr** [comment]
@cbujak Here is the url I use and I just checked that it works for me. https://microsoftteams.uservoice.com/forums/555103-public

**Comment by scanum** [comment]
@KyleSchroeder  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
