### ISSUE TITLE
Participant list disappears (MS Teams UI bug in Windows 10)

### ISSUE THREAD

**Issue by Manu1ND** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7558]
### Behavior / Symptom
The list of participants (presenters and attendees) disappears frequently

### Known workaround
Switching back to some other application temporarily fixes the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bef5b5fd-5a4e-7957-f23c-724764a7cb4c
* Version Independent ID: 5fe6c3ab-774b-db2f-5b55-9170bdfe5faf
* Content: [Known issues - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/known-issues?WT.mc_id=365AdminCSH_SocContactUs)
* Content Source: [Teams/rooms/known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/known-issues.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
