### ISSUE TITLE
Broken Link "Automatic team creation using SDS" section

### ISSUE THREAD

**Issue by nmball** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7559]
The link below from the **Automatic team creation using SDS** section is broken.

https://docs.microsoft.com/en-us/schooldatasync/what-sis-and-mis-vendors-does-school-data-sync-support

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcfef917-dc74-3fd7-eef8-5af66583a04d
* Version Independent ID: 9d1958bc-e321-06b8-91d6-a0ec291190eb
* Content: [Microsoft Teams policies and policy packages for EDU admins - Microsoft Teams](https://docs.microsoft.com/en-gb/MicrosoftTeams/policy-packages-edu)
* Content Source: [Teams/policy-packages-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/policy-packages-edu.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@nmball Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@nmball thank you for reaching out and helping improve MS Docs. I've just had a look at the article but can't find the link you are referring to. Please can you check and let me know.

**Comment by nmball** [comment]
Apologies, I raised the feedback on the wrong page.  I will re raise on the relevant page
