### ISSUE TITLE
Online Licensing link under plan is broke

### ISSUE THREAD

**Issue by Scottmca** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#756]
The "Online Licensing" link is bad.  Not sure what it is supposed to point to:)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 515e5db8-20be-f979-5de9-3998713518dd
* Version Independent ID: a284fee3-f324-2984-431e-df14d3c4bd2d
* Content: [Skype Room Systems v2 requirements](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/requirements#feedback)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @davgroom
* Microsoft Alias: **jambirk**

**Comment by AndreaBarr** [comment]
@Scottmca Thank you for this feedback

I am going to get this to the Skype teams back log so we can get this link updated.

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.
