### ISSUE TITLE
This script throws an error

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7560]
As you can see in the comments section on this article: 

https://tomtalks.blog/2019/10/microsoft-teams-direct-routing-sip-tester-powershell-script/

this script throws an error when run. If you open it up, you'll see the function isn't properly defined.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99036b5e-f358-fda3-d9b1-1279952b59a5
* Version Independent ID: 9ea42c59-7db5-9c66-ef58-98b4909ccd10
* Content: [PowerShell script to test Direct Routing Session Border Controller connections - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sip-tester-powershell-script)
* Content Source: [Teams/sip-tester-powershell-script.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sip-tester-powershell-script.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by dariomws** [comment]
Hi @Mike-Crowley, thank you for your feedback and help us to improve docs.microsoft.com.

The last comment in that blog is from August 31, 2020. Did you test the script recently, and are you getting the same error? Thanks!

**Comment by dariomws** [comment]
@mozziemozz, maybe you can share valuable information here. I see your comment with a different error:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7299

Thanks!

**Comment by Mike-Crowley** [comment]
Yes, just tried. The blog has comment moderation enabled. It looks like recent comments (such as one from me) haven't been approved.





________________________________

**Comment by dariomws** [comment]
@Mike-Crowley thank you. Could you kindly provide more detail about the error here?

**Comment by mozziemozz** [comment]
@dariomws in our case we were able to start the script without issue. (we have a seperate script which calls the sip tester script using our parameters like user credentials and so on). This issue is not described very well (no details, just that it throws an error...)

**Comment by dariomws** [comment]
@Mike-Crowley thank you. Could you kindly provide more detail about the error here?

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
