### ISSUE TITLE
Missing Teams under WindowsTeamSettings

### ISSUE THREAD

**Issue by rhusted** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7561]
[Enter feedback here]

The instructions on this page indicate to navigate within Windows Configuration Designer to WindowsTeamSettings -> Teams and select Configurations.  I installed Windows Configuration Designer and there is no longer an option for Teams under the group WindowsTeamSettings.  I'd like to create this provisioning package to setup coordinated meetings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6056049-5981-858a-a82b-9e814181cfe6
* Version Independent ID: 0719e1ec-e9b4-0004-030b-f8158e2898a6
* Content: [Manage Microsoft Teams configuration on Surface Hub - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/surface-hub-manage-config)
* Content Source: [Teams/rooms/surface-hub-manage-config.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/surface-hub-manage-config.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@rhusted Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @rhusted how are you? hope you are doing good.
I am investigating this, I think the configuration was moved to 

`Runtime settings -> SurfaceHub -> Teams -> Configurations`

, but I am trying to confirm.
Thanks

**Comment by rhusted** [comment]
Thank you for looking into it.  I don't see that path in config designer either. It would be nice to have this working for quick changes.  In the meantime however I was able to use intoned to get my immediate needs taken care of.

Rob


-------- Original message --------
From: Andres Mariano Gorzelany ***@***.***>
Date: 7/19/21 1:23 PM (GMT-08:00)
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: rhusted ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Missing Teams under WindowsTeamSettings (#7561)


Hello @rhusted<https://github.com/rhusted> how are you? hope you are doing good.
I am investigating this, I think the configuration was moved to

Runtime settings -> SurfaceHub -> Teams -> Configurations

, but I am trying to confirm.
Thanks

**Comment by get-itips** [comment]
> Thank you for looking into it. I don't see that path in config designer either. It would be nice to have this working for quick changes. In the meantime however I was able to use intoned to get my immediate needs taken care of. Rob

Thanks for returning and sharing that feedback!

**Comment by get-itips** [comment]
@scanum please close.
