### ISSUE TITLE
Incorrect information regarding View-only capabilities for Webinars

### ISSUE THREAD

**Issue by JorgeALeitao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7562]
Please remove the line that says
-Participants over 1,000 up to 20,000 have View-only capabilities

As currently this is not yet possible.

Thanks

Jorge
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92fcb1f6-5cc2-f6bd-cfa9-11d811f1dbf1
* Version Independent ID: 9a571e6d-8cb3-9ff8-a5c2-62deab146264
* Content: [Quick start - Meetings, webinars, and live events - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/quick-start-meetings-live-events)
* Content Source: [Teams/quick-start-meetings-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/quick-start-meetings-live-events.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@JorgeALeitao Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by CarolynRowe** [comment]
@dariomws @scanum  Please do not make any changes to this article.  The limits were approved and signed off by several PMs.  I will follow up with those PMs regarding this issue.

**Comment by JorgeALeitao** [comment]
> @dariomws @scanum Please do not make any changes to this article. The limits were approved and signed off by several PMs. I will follow up with those PMs regarding this issue.

@CarolynRowe , given that Siunie agreed to my suggestion will you give green light to update the doc article? Thanks!

**Comment by CarolynRowe** [comment]
The article update is already live:  https://docs.microsoft.com/en-us/microsoftteams/quick-start-meetings-live-events

**Comment by CarolynRowe** [comment]
Closing this issue.  Thank you, Jorge, for the feedback.
