### ISSUE TITLE
Can specify presenters - Missing within meetings' capabilities.

### ISSUE THREAD

**Issue by JorgeALeitao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7563]
It is possible to specify roles among meetings attendees

Thus, for fully describing capabilities, please add "-Can specify presenters" to the Interaction Column associated with meetings  

Thanks
Jorge 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92fcb1f6-5cc2-f6bd-cfa9-11d811f1dbf1
* Version Independent ID: 9a571e6d-8cb3-9ff8-a5c2-62deab146264
* Content: [Quick start - Meetings, webinars, and live events - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/quick-start-meetings-live-events)
* Content Source: [Teams/quick-start-meetings-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/quick-start-meetings-live-events.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@JorgeALeitao Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks @JorgeALeitao for the feedback

**Comment by get-itips** [comment]
@scanum please close, as per https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/7568#issuecomment-886953074

**Comment by get-itips** [comment]
@scanum please close.
