### ISSUE TITLE
Update needed for recording storage

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7565]
With Teams now storing recordings in OneDrive/SharePoint it would be good to have the diagrams updated to reflect this change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ad624-9792-91b7-c85f-09b839b1ea44
* Version Independent ID: e8288f91-11bd-599b-8a88-074917b315a4
* Content: [Microsoft Teams IT architecture and voice solutions posters - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-architecture-solutions-posters)
* Content Source: [Teams/teams-architecture-solutions-posters.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-architecture-solutions-posters.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Larryngolog, thank you for your feedback and help us to improve docs.microsoft.com.

@cichur @LolaJacobsen do you think we can update this poster? Thanks!

**Comment by dariomws** [comment]
@cichur @LolaJacobsen do you think we can update this poster? Thanks!
