### ISSUE TITLE
Define a domain for external sharing

### ISSUE THREAD

**Issue by alnelsonau** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7569]
The article needs to explain what defines a domain.

We have a requirement for one tenant to have a different UPN and SMTP. 
The external sharing does not seem to work based on the SMTP domain, which is a problem for us because we cannot easily change the UPN.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external access (federation) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @alnelsonau, thank you for your feedback.

The SIP address must match the primary email address, especially if you plan to communicate with federated partners/external users.
In Microsoft 365, the UPN is the default SIP address. You can update it using the Exchange Admin Center (on-premises if you have Azure AD Connect).

**Comment by dariomws** [comment]
@scanum I think we can close this issue.

**Comment by alnelsonau** [comment]
Thanks for your help, I see we need to adjust SIP domains for this
migration to succeed.
