### ISSUE TITLE
SIS Vendors link broken URL 404

### ISSUE THREAD

**Issue by nmball** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7570]
Hiya, 

In the Automatic team creation section found> https://docs.microsoft.com/en-gb/microsoftteams/remote-learning-edu#automatic-team-creation-using-sds

The SIS Vendors link is broken

Broken URL > https://docs.microsoft.com/en-us/schooldatasync/what-sis-and-mis-vendors-does-school-data-sync-support

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a9f575-7a67-4d52-a2d7-41fca96d42d7
* Version Independent ID: 1638ffdb-fd56-48b8-33a9-ad79c901b0c0
* Content: [Microsoft Teams resources for Education admins - Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/remote-learning-edu)
* Content Source: [Teams/remote-learning-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/remote-learning-edu.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting! @nmball

**Comment by lindspea** [comment]
@nmball thanks for posting the correct doc linked to the issue. I see @get-itips has done the fix. Thanks again for pointing this out.
