### ISSUE TITLE
2.4.0-preview - New-Team and Get-Team : No longer accept special characters

### ISSUE THREAD

**Issue by GaelBSB** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7571]
Hi,

I just upgraded from version 1.1.8-preview to version 2.4.0-preview and I notice that "get-team" & "new-team" do not accept special characters anymore (#, &,...)

Get-Team : Error occurred while executing 
Code: BadRequest
Message: There is an unterminated string literal at position 25 in '"displayName:M1 - Product'.
InnerError:
  RequestId: c19ae828-5fa4-4527-abd8-6c2ef91a5deb
  DateTimeStamp: 2021-07-14T19:48:32
HttpStatusCode: BadRequest
Au caractère D:\PS_Teams\2020 - Teams - 2021\TEST_2021.ps1:56 : 3
+   Get-Team -DisplayName "M1 - Product  `& Branding Strategy Level2 -  ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Team], ApiException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdlets.PowerShell.Custom.GetTe 
   am

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
