### ISSUE TITLE
No mention that credits expire.

### ISSUE THREAD

**Issue by epbccorey** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7572]
[Enter feedback here]
No mention that credits expire after 12 months. That's an important "feature".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d52a9779-b72d-dea0-eac2-6c04a8c282eb
* Version Independent ID: d3c3d968-9e54-ec42-3438-9320e23d68b9
* Content: [What are Communications Credits? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/what-are-communications-credits)
* Content Source: [Teams/what-are-communications-credits.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-communications-credits.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @epbccorey how are you? hope you are doing good 👍 

That is mentioned [in the next article](https://docs.microsoft.com/en-us/microsoftteams/set-up-communications-credits-for-your-organization) of the section

> Any funds not used within 12 months of the purchase date will expire and be forfeited.

Thanks for your feedback

**Comment by epbccorey** [comment]
I am doing good. Hope you are too.

On that page it’s buried in a minor note, in the second sentence of a paragraph.
There’s no “Do Credits Expire” heading.
It looks like you’re trying to hide it.

We just spent two months in back and forth emails with Microsoft Support because my boss didn’t know that credits expire. That’s a lot of wasted time.

I recommend adding it to the first page.

Corey

**Comment by get-itips** [comment]
Thanks for your feedback @epbccorey

**Comment by get-itips** [comment]
@scanum please close.
