### ISSUE TITLE
Audio Time / Video Time better definition

### ISSUE THREAD

**Issue by JF-SR** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7576]
Hi,

Please can you elaborate on the specification of "audio time" and "video time" here https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report 

Is audio time by default a proxy for time spent in a meeting? Is it possible to be a participant in a meeting without registering audio time?

Looking at our data we have one or two outliers that have more video time than audio time in a week. This is related to the precious question - is it possible to participate in a meeting as video time only? Or if someone is registering video time, should audio time be registered for the same amount of time?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2758a3d6-c646-dcb0-2a31-c7b9b84e780b
* Version Independent ID: 8704c9fe-f8b0-82d2-bd83-3fd1a9ad638d
* Content: [Microsoft Teams user activity report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report)
* Content Source: [Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@JF-SR Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by JF-SR** [comment]
Hi. Thanks for taking this further. I wonder if you have the answer to the question already about the definition itself so we don't have to wait for the actual update to the documentation before understanding the defintion of Audio time (e.g. does muting affect the measurement?).

Thanks!

**Comment by dariomws** [comment]
Hi @JF-SR, thank you for your feedback.

I tested it and can confirm that the time is registered for both if you enable video in a meeting and you keep audio enabled. In addition, you can join a meeting without audio or mute audio during the call (even if the video is enabled), and that time won't be registered as audio time.
