### ISSUE TITLE
Cannot install Teams on Surface Hub2

### ISSUE THREAD

**Issue by Joachim-Otahal** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7577]
Please update this doc. When I try to install teams via the store it asks for a user and password. But the same account, which works on my normal Laptop does not work there.
How does it work then?

The surface hub2 ist updated, it has the latest OS version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f256cd5b-3ec8-2d55-9ae4-ff9849d52eae
* Version Independent ID: 52c2271b-df38-5dc9-c2a1-553cdf3b5496
* Content: [Deploy Microsoft Teams for Surface Hub - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-surface-hub)
* Content Source: [Teams/teams-surface-hub.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-surface-hub.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@Joachim-Otahal Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Joachim-Otahal** [comment]
Teams is finally working on that thing. But this is not a good experience - Ist did install "Teams for Surface hub" even though it never was able to check the login, and on top it never showed anywhere the installer running. Usually, if you install software which does not require a license, you can see the installer running after skipping authentication on Windows 10. But not on Surface Hub2, not showing anywhere anything. It simply was suddenly installed and selectable as default communication app in the settings besides Skype.
