### ISSUE TITLE
Review eiligibility criteria teams exploratory experience

### ISSUE THREAD

**Issue by MartaRosaGomes** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7578]
Hi Team, 

can you please check and review the eligibility criteria for the teams exploratory experience? 

From our experience in support (M365 Subscription and Licensing), the tenant needs to have a subscription (paid or trial) that contains the service plan "Teams" and the subscription needs to be in active status in order for a user (with no license assigned) to be able to start the teams exploratory experience. 
If a tenant contains only a paid license like Exchange Online plan 1 (which does not contain Teams), a user is not able to start the teams exploratory experience. 

If you need more clarity on this please let me know. 

Thanks,
Marta 

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://docs.microsoft.com/pt-pt/microsoftteams/teams-exploratory)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@MartaRosaGomes Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @MartaRosaGomes, thank you for your feedback.

A Product Manager confirms to us that you **don't** need a Teams service plan to enable a Teams exploratory license.
