### ISSUE TITLE
Update Ramp description in Step 4

### ISSUE THREAD

**Issue by kquantum** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7582]
[Enter feedback here]
Hello - the description for Ramp (in Step 4: Set up a video distribution solution for live events in Teams) is out of date.  Please update to the following description:

Ramp for Microsoft Teams helps organizations securely deliver streaming and on-demand video in high quality, while reducing bandwidth consumption by up to 99.9%.  Ramp’s Universal eCDN can run in the cloud for convenience, inside the firewall for complete control over security protocols, or in mixed cloud environments.  Ramp is the only Microsoft eCDN partner that provides all three eCDN technologies: multicast, caching, and P2P in a single solution to fit your network.  All three are included in our predictable pricing model with no surprises or overage charges.  Learn more [link to www.rampecdn.com]

Please let me know if you have any questions. kquan[at]rampecdn.com

Thank you,
Kevin 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9aa4676-855a-fddb-bb0b-96b7095c695e
* Version Independent ID: 7c39f08c-0d56-6d29-1356-879d9d6ff51c
* Content: [Set up for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/set-up-for-teams-live-events)
* Content Source: [Teams/teams-live-events/set-up-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/set-up-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@kquantum Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback
@scanum

**Comment by kquantum** [comment]
The page hasn't been updated and continues to be incorrect.

Ramp has multicast, caching, and P2P technologies in one eCDN
