### ISSUE TITLE
Needed clarity, screen shoots and further disparities to note.

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7583]
Is the Shared line appearance feature availability Matrix still up to date?

Could you please explain these feature in the matrix or provide a hyperlink:
1. See the admin view of shared lines
2. See the admin view of manager's call activities
3. See the manager view of delegates
Does Admin in this context mean Administrative Assist? or Delegate? or System Admin or?
Does Manager in this context mean: manager is someone who authorizes a delegate to make or receive calls on their behalf

Also, it should be noted that currently a delegate with Teams IP Phone can place a call on hold with just Receive Call permission but cannot resume the same call without Make call permission. The same Delegate on Teams Desktop App can both Hold and resume same call with just Receive Call permission. This is a disparity between Teams Desktop and Teams IP Phone that needs to be noted until addressed. Ref. MS Case #:26579877

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3dd879-564e-62ca-2095-3ef6ae4fab2d
* Version Independent ID: 8ed3dff3-b2b8-b3db-6db9-6bbecdb6cf5c
* Content: [Shared line appearance in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/shared-line-appearance)
* Content Source: [Teams/shared-line-appearance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/shared-line-appearance.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@SvenBell Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @SvenBell how are you? Hope you are doing good.

To my understanding, _admin view_ is _administrative assistant view_ said that:

_See the admin view of shared lines_
![image](https://user-images.githubusercontent.com/36666927/127705681-ec61c426-44d0-4362-9a9f-bc801425de88.png)

_See the admin view of manager's call activities_
![image](https://user-images.githubusercontent.com/36666927/127699541-c544683d-17af-4f3f-8b82-f8493eaf41e1.png)

_See the manager view of delegates_
![image](https://user-images.githubusercontent.com/36666927/127699706-5e7cbadc-5239-419b-96e1-b3155a20891d.png)

I can see that this could be improved in the article so I'll propose thru a PR.

Thanks for your feedback.
