### ISSUE TITLE
Park timeout

### ISSUE THREAD

**Issue by mymebenha** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7585]
It doesn't say anything about the Park timeout.  It should said that it cannot be changed as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e03ef3d-81d8-c98f-8427-fe7c008ea30f
* Version Independent ID: 17af3418-b94d-f233-60c0-778b2e8dc02b
* Content: [Call park and retrieve in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/call-park-and-retrieve)
* Content Source: [Teams/call-park-and-retrieve.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/call-park-and-retrieve.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@bratsche Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @mymebenha
