### ISSUE TITLE
Assign a service number to a resource account in the GUI

### ISSUE THREAD

**Issue by wxpaul11** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7587]
[That part of the article is not working in the Teams admin center. To add the service number to the resource account you have to use PowerShell. Please update this article, 
https://user-images.githubusercontent.com/87786530/126695770-65f104aa-fd65-4ed1-9cfa-601c1230a63e, to let the admins know to use PowerShell or fix the GUI to do what the article says it would do.
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @wxpaul11, thank you for your feedback and help to improve docs.microsoft.com.

If you have Calling Plans, you can assign a phone number to a resource account using the Teams Admin Center. If you have deployed Direct Routing or want to assign a hybrid number, you need to use the Team PowerShell module. It's documented in the article:
![image](https://user-images.githubusercontent.com/33589238/126861583-70578cca-b3a5-49f2-85d3-83a763c2e6f0.png)

Sorry, but I cannot see your image.

**Comment by dariomws** [comment]
@scanum I think we can close this issue.
