### ISSUE TITLE
Worthless Page - Don't try this with Windows Server 2016  - Every command is a failure.

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7591]
Are you all serious to post the SECOND COPY COMMAND?  What is that?  A joke?

Please REVIEW this entire page and correct it to work with current systems.  If there is something more that we need to know and do, please post it.  All requirement s were met yet failures from start to finish.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd283f6e-3865-ed70-d663-cc461ee8ba57
* Version Independent ID: 2450d311-fc04-d8b6-b4a2-b1890ec6fc3e
* Content: [Install Microsoft Teams PowerShell - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install)
* Content Source: [Teams/teams-powershell-install.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-install.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by scanum** [comment]
@Karr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
