### ISSUE TITLE
Can this page be updated to show Teams now follows Office preview

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7595]
Related to Message Center change MC264092 and Microsoft 365 Roadmap ID: 81704.
We are rolling out a new Teams Update policy that will allow users to automatically be in the Public Preview channel of Teams if they are in Current Channel Preview for the Office 365 Client.

IT admins can modify this policy for end users such that if Office is getting updates from Current Channel (Preview), Teams will receive updates via Public Preview.

This feature will be ON by default for all tenants with users in the Teams Current Channel.

This is the updated image of the Teams Admin Teams Update Policy

![image](https://user-images.githubusercontent.com/69439002/126901704-d02a1114-20d0-41f3-990f-07c5ab5c2e47.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5f1cdd1-09ff-f95d-6d50-e7880d34020f
* Version Independent ID: 59219640-305b-30c1-bc10-87e2633d95db
* Content: [Public preview in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/public-preview-doc-updates)
* Content Source: [Teams/public-preview-doc-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/public-preview-doc-updates.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@nikki-c Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @nikki-c

**Comment by get-itips** [comment]
The article has been updated.
@scanum please close
