### ISSUE TITLE
"small business" tab is not clickable. 

### ISSUE THREAD

**Issue by jackchenwork** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7596]
[Enter feedback here]

https://docs.microsoft.com/en-us/microsoftteams/deploy-overview mentioned users can choose "small business" or "medium/large business" for deferent size companies, but the "small business" tab is not clickable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b131c7fd-ec71-6b6f-4443-ddaf5cb44bf6
* Version Independent ID: 0c1fb61b-a6cc-e856-d969-54bc13ec699c
* Content: [Microsoft Teams deployment overview - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/deploy-overview)
* Content Source: [Teams/deploy-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/deploy-overview.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
