### ISSUE TITLE
More information needed about hybrid application endpoints.

### ISSUE THREAD

**Issue by dabaco** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7597]
"If you have configured on-premises hybrid application endpoints for Auto Attendants or Call Queues, be sure to move these endpoints to Microsoft 365 before decommissioning Skype for Business Server."

More information needs to be created about the details for this step.  How is this done, what cmdlets, what are the steps to accomplish this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5566de7d-1d1e-ba92-743b-dc772b49752a
* Version Independent ID: c15342ff-eb3a-5f14-4bba-217c31aa1299
* Content: [Decide how to manage attributes after decommissioning - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/cloud-consolidation-managing-attributes)
* Content Source: [Skype/SfbHybrid/hybrid/cloud-consolidation-managing-attributes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/cloud-consolidation-managing-attributes.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@dabaco Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @dabaco, thank you for your feedback and help us to improve docs.microsoft.com.

@CarolynRowe could you kindly let me know if you think we can add more information here? My thought is that we should remove the resource account from on-premises with Remove-CsHybridApplicationEndpoint and then recreate it in the cloud. Thanks!

**Comment by CarolynRowe** [comment]
I suggest contacting @bjwhalen. We should get his approval before making this change.

**Comment by bjwhalen** [comment]
the process for this is described in another article in this section: https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/decommission-move-on-prem-endpoints.

it is already linked to at the bottom of this page. but i also just put in a PR to add that link in the note itself

**Comment by CarolynRowe** [comment]
Thanks, BJ.  We do not want to duplicate content between the articles, so closing this issue.

**Comment by dariomws** [comment]
Thanks everyone!
