### ISSUE TITLE
incorrect sentence

### ISSUE THREAD

**Issue by Strick1969** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7600]
Users in **Teams Only** mode will not be able to initiate chats or calls or schedule meetings in Skype for Business Online. Teams Only users will still be able to join Skype for Business meetings scheduled by users still using Skype for Business Server.

**I think that should say "Islands Mode"**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cea1cc-731d-bfba-3ed5-63a6339ecf88
* Version Independent ID: 7681956e-e442-07a3-7f7b-f086a0aff173
* Content: [Skype for Business Online retirement - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/skype-for-business-online-retirement)
* Content Source: [Teams/skype-for-business-online-retirement.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/skype-for-business-online-retirement.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
