### ISSUE TITLE
Webinar limits need updating

### ISSUE THREAD

**Issue by bytemybitz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7602]
This page says "The view-only experience will soon be available for webinars as well." whereas this document https://teamworktools.azurewebsites.net/assets/TeamsWebinarsGetStartedGuide.pdf?culture=en-us&country=US says it will extend to view-only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by dariomws** [comment]
Hi @bytemybitz, thank you for your feedback.

The "The view-only experience will soon be available for webinars as well" sentence was added 15 days ago. So I understand that this statement is correct.

@CarolynRowe could you kindly confirm it? Thanks!

**Comment by bytemybitz** [comment]
Thank you for the information. Is there an expected roll out date? We have
a 1000+ webinar we're planning for mid Sept; should we switch to a Teams
meeting with registration instead?

Cheers,
;^b en

**Comment by CarolynRowe** [comment]
I'm sorry, but I can't answer that question.  This forum is for content updates.  Please go through your regular support channels.  Thank you.
