### ISSUE TITLE
Necessary License for Voice Mail

### ISSUE THREAD

**Issue by HiroTsukamoto** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7603]
Could you describe necessary license for Voice Mail on MS Docs?
I understand it can work with basic Teams feature without any phone system user license.
But MS doc looks like it is saying Phone user license is necessary.
Please follow up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8228f9b2-a7de-abb4-6f41-70db0b3af155
* Version Independent ID: 8fd9fafb-dd76-59a8-e609-56f06d539a31
* Content: [Set up Cloud Voicemail - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-phone-system-voicemail)
* Content Source: [Teams/set-up-phone-system-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-phone-system-voicemail.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @HiroTsukamoto how are you?
The article states

> Cloud Voicemail is automatically set up and provisioned for users after you assign a Phone System license to the users.

You can also read what you get with Phone System here https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=small-business

Hope this information helps you!

**Comment by HiroTsukamoto** [comment]
Andres

Thank you for your Email.

This statement "Cloud Voicemail is automatically set up and provisioned for users after you assign a Phone System license to the users."
is telling you need Phone System license to enable Voice Mail.
However, actually cloud Voice Mail can work without Phone System license.
As long as Teams is working, it can work.

This is why I want to revise this statement of MS Doc.
Could you follow up???



Hiro Tsukamoto



Andres Mariano Gorzelany ***@***.***>
Sent: Saturday, July 31, 2021 1:58 AM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Hironori Tsukamoto ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Necessary License for Voice Mail (#7603)


Hello @HiroTsukamoto<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHiroTsukamoto&data=04%7C01%7CHironori.Tsukamoto%40microsoft.com%7C75ff44beb425466906ed08d9537b2be3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637632610774771644%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SMTe9aQjES7fP2ESBMANSX8WQexX9uJcENvqiVh4V2U%3D&reserved=0> how are you?
The article states

Cloud Voicemail is automatically set up and provisioned for users after you assign a Phone System license to the users.

You can also read what you get with Phone System here https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=small-business<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoftteams%2Fteams-add-on-licensing%2Fmicrosoft-teams-add-on-licensing%3Ftabs%3Dsmall-business&data=04%7C01%7CHironori.Tsukamoto%40microsoft.com%7C75ff44beb425466906ed08d9537b2be3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637632610774771644%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BXtQOYF2ikYlIg4xX3MmeX3E%2BpdYPID2FnSKVx3pCRQ%3D&reserved=0>

Hope this information helps you!

-

**Comment by get-itips** [comment]
Hello @HiroTsukamoto  
How are you? Hope you are doing good. I understand what you say, however, a license is also the right to use something. 
I am not a licensing specialist but I think the article is clear about what you need, from a license point of view, to take advantage of cvm. Thank you

**Comment by HiroTsukamoto** [comment]
If you start O365 tenant as default without phone system license, MS Teams can work with voicemail.
How would you tell this by this article?

Hiro

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by get-itips** [comment]
Hello,
The article was updated recently with this sentence and I thought you might be interested

> For Teams users, Cloud Voicemail is automatically set up and provisioned. Note that a Phone System license is not required for Cloud Voicemail.

**Comment by HiroTsukamoto** [comment]
Andres

Thank you very much for the feedback.
Appreciate your following up!!

Q. Which page of MS Doc did you update and add "below sentence"?

"For Teams users, Cloud Voicemail is automatically set up and provisioned. Note that a Phone System license is not required for Cloud Voicemail."


Best Regardrs
Hiro

**Comment by get-itips** [comment]
@HiroTsukamoto 
the sentence is in https://docs.microsoft.com/en-us/microsoftteams/set-up-phone-system-voicemail
(not added by me, but article author)
