### ISSUE TITLE
Add a note regarding supported channel types for Call Queues

### ISSUE THREAD

**Issue by limp15000** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7605]
[Enter feedback here]
Customer has asked why private channels don't appear in the dropdown. As far as I know only standard channels are supported. 
Maybe we should add a note ? 
[!NOTE] Only Standard channels can be linked to a call queue with initial release.
https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue#teams-channel
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b755d9ae-13ac-019f-f5f4-a95b1eee2989
* Version Independent ID: f7afd8ad-e6e0-6c79-aed1-4ee87d48ba12
* Content: [Create a call queue in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue)
* Content Source: [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-call-queue.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@CLYVR can you confirm that private channels aren't supported for call queues?

**Comment by CLYVR** [comment]
@MikePlumleyMSFT Confirmed - private channels are not currently supported.

**Comment by MikePlumleyMSFT** [comment]
Thanks, @CLYVR. @limp15000 I submitted a change to call this out. Should be live later today.

**Comment by limp15000** [comment]
Awesome thanks I see the update :)
