### ISSUE TITLE
Microsoft Auto Update (MAU) for Mac lists Teams but does not actually update it

### ISSUE THREAD

**Issue by brunerd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7607]
Despite Teams showing up in MAU on the Mac, it doesn't seem to actually update the app! I've gone back as far as I could to a copy from 2019 and MAU always says it is up-to-date. If MAU doesn't actually update Teams it should not say it is up-to-date. Ideally though MAU should be the one updater to rule them all - why is Teams doing its own updating? (Was Teams app acquired by MS but still hasn't been totally assimilated? Get on it!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6da28da-eb7b-d3ae-4c2f-8f87803b1830
* Version Independent ID: 8c42d7a2-80c6-86dd-347a-ed6d8d909c41
* Content: [Teams updates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-client-update)
* Content Source: [Teams/teams-client-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-client-update.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @brunerd, thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/answers/products/m365).

**Comment by brunerd** [comment]
What's really funny is that at the Portal these are the categories for Teams
*  Teams for Windows
* Teams for Linux
* Teams App development

There's no "Teams for Mac" ha, good one!
