### ISSUE TITLE
Meeting Attendance Report

### ISSUE THREAD

**Issue by adilyoosuf** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7610]
Two issues to be rectified in https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams-general#meeting-attendance-report

1. During the meeting the .csv file which can be downloaded from the participants section is the "Meeting Attendance **List**". The "Meeting Attendance **Report**" is posted in the meeting chat after the meeting ends.

2. In **Set-CsTeamsMeetingPolicy** the **AllowEngagementReport** parameter has been **Enabled** and not **Disabled** by default in two tenants which I have used so far.

Clarification appreciated.

**Comment by dariomws** [comment]
Hi @adilyoosuf, thank you for your feedback and help us to improve docs.microsoft.com.

I've verified that the default value for AllowEngagementReport is enabled and I'm applying an update to the article.

About the first question I'm not sure if I understand, but you can download the report during and after the meeting:
https://support.microsoft.com/office/view-and-download-meeting-attendance-reports-in-teams-ae7cf170-530c-47d3-84c1-3aedac74d310

**Comment by adilyoosuf** [comment]
Hi @dariomws , thank you for the update.

Regarding the first issue. Meeting Attendance **List** and Meeting Attendance **Report** are not the same. Meeting Attendance Report is more detailed and is only available in the meeting chat after the meeting ends. Meeting Attendance List appears in the Participants pane only during the meeting.

Hence, the statement "When enabled, the option to download the report is displayed in the Participants pane." is incorrect.

**Comment by dariomws** [comment]
@adilyoosuf I understand your point now. When you download the report or list during the meeting, the button says "Download attendance list", and the file name contains the word list. When you download it after the meeting, it says just "Attendance", the file name contains the word report and some more information about the meeting.

Anyway, I understand that the attendance list and report are synonymous in this case and are used in several articles. For example:
https://docs.microsoft.com/microsoftteams/teams-analytics-and-reports/meeting-attendance-report
https://support.microsoft.com/office/view-and-download-meeting-attendance-reports-in-teams-ae7cf170-530c-47d3-84c1-3aedac74d310?ui=en-US&rs=en-US&ad=US

**Comment by adilyoosuf** [comment]
@dariomws Thank you for the clarification.
