### ISSUE TITLE
I think title name should change

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7611]
i read the article from below site 
**https://www.microsoft.com/microsoft-365/microsoft-365-and-office-resources?ms.office**
When I click on the link **Hardware decoder and encoder driver recommendations** for a list of unsupported decoders and encoders.
page is redirected to the below page
**https://docs.microsoft.com/microsoftteams/hardware-decoders-and-encoders**
in the above article  page, the Title  name should be like below

**Unsupported Hardware decoder and encoder drivers**

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e7f4e46-0e6a-3d42-022d-b07fd17792b3
* Version Independent ID: 5217778e-130d-6bed-beb7-f3834331f8ed
* Content: [Hardware decoder and encoder driver recommendations - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/hardware-decoders-and-encoders)
* Content Source: [Teams/hardware-decoders-and-encoders.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hardware-decoders-and-encoders.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @RAJU2529 how are you?
I am not sure if I follow your inquiry correctly, the links always use the title of the destination page.
Let me know if I understood you well,
Thanks

**Comment by RAJU2529** [comment]
@get-itips . I am fine sir .How  are you sir. 
in this article.below points is indicated 
**Microsoft supports all decoders and encoders except those listed in this article**.
 I understood like this, unsupported list of encoder and decoder only.
these means list of supported hardwares are not mentioned.

**Comment by get-itips** [comment]
Hello @RAJU2529 I understand better now, thanks for that.
I read the article, however, there is a section that says _only the following Device_ids are enabled for hardware acceleration._ So changing the title I think it will lead to some confusion.
Thank you

**Comment by RAJU2529** [comment]
@get-itips . Thanks for the information. So  I am closing this issue from my side.
