### ISSUE TITLE
Clarification on Emergency Call Enablement and Configuration

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7615]
Hello,

I have just clarified something with Microsoft Support that stumped me when reading the following paragraph:
> If an emergency call routing policy is associated with the site, then the site policy is used to configure emergency calling.
> 
> If there is no emergency call routing policy associated with the site, or if the client is connected at an undefined site, then the emergency call routing policy associated with the user account is used to configure emergency calling.
> 
> If the Teams client is unable to obtain an emergency call routing policy, then the user is not enabled for emergency calling.

Specifically, we have validated the following Scenario:
- If the Site Emergency Call Routing Policy is found, but no match is found for the Emergency Number Dial Mask or Dial String, will the ECRP of the User (if assigned) queried for a match?
- Is the order of Emergency numbers in an ECRP of relevance? (There is no ID as far as I can see on the PS Object...)
- Assuming Direct Routing and that both Site and User policy are queried: If no match is found, the call is routed via the Online Voice Routing Policy, correct? 

I proposed the following questions:
Am I correct in validating the effective ECRP by doing the following:
- Matching the dialled Emergency Number against Site ECRP, Emergency Numbers, EmergencyDialString and EmergencyDialMask
- If not found, matching the dialled Emergency Number against User ECRP, Emergency Numbers, EmergencyDialString and EmergencyDialMask
- If not found, validating that the dialled number is matched by a Voice Route in the Online Voice Routing Policy assigned to the User?

The answers to the above are:
- Yes, both Dial Mask and Dial String are validated/matched against
- Yes, if no match in the Sites’ ECRP are found, the Users’ ECRP is checked
- Yes, if no match is found, call will be routed via OVP
The OVP will be invoked, but success of the call depends on a OVR matching the Dialled Number

As I feel not qualified enough to propose a phrasing for this sensitive topic, may I ask that this paragraph is changed in a way to cover the above?
My proposal:
> If an emergency call routing policy is associated with the site, then the site policy is used to configure emergency calling.
> 
> If there is no emergency call routing policy associated with the site, or if the client is connected at an undefined site, **or if the dialed number does not match any of the defined emergency numbers in the emergency call routing policy associated with the site** then the emergency call routing policy associated with the user account is used to configure emergency calling.
> 
> If the Teams client is unable to obtain an emergency call routing policy, then the user is not enabled for emergency calling.

Thank you,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634810fc-7a47-f794-7803-9f3941d664dd
* Version Independent ID: 52587955-5054-a003-6d03-948ce02838dd
* Content: [Plan and manage emergency calling - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/what-are-emergency-locations-addresses-and-call-routing)
* Content Source: [Teams/what-are-emergency-locations-addresses-and-call-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-emergency-locations-addresses-and-call-routing.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@DEberhardt Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
