### ISSUE TITLE
WNS

### ISSUE THREAD

**Issue by bozenektoja** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7616]
Why don't we list the WNS traffic here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d996cf7-9f48-2b30-7759-afaf3fe82caa
* Version Independent ID: 24dd6cdf-d35f-53b2-06c2-0a27891825d4
* Content: [Prepare your organization's network for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/prepare-network)
* Content Source: [Teams/prepare-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/prepare-network.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@bozenektoja Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
hello @bozenektoja how are you?
Do you refer to Teams Push notifications maybe?
Thanks

**Comment by bozenektoja** [comment]
Hi!
Thanks for replying, I'm talking about this:
https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/firewall-allowlist-config
https://www.microsoft.com/en-us/download/confirmation.aspx?id=44238
We don't mention it in this document, but my customer is observing traffic from this servers on his VDI machines.
Shouldn't it be added there?

Best regards,
Bożena Szlachta-Hutyra

**Comment by bozenektoja** [comment]
May I know why this was closed?
Can you please tell me why WNS is not mentioned in the documentation for Teams VDI?
https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi
https://docs.microsoft.com/en-us/microsoftteams/prepare-network
