### ISSUE TITLE
Need to add section on how to capture WebRTC logs for Browser

### ISSUE THREAD

**Issue by greganth1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7618]
Accessing and capturing WebRTC logs

WebRTC logs help developers and support in case of issues with audio or video connections.

Edge (Chromium) web browser
The browser tracks and logs all WebRTC connections, so close all tabs and restart the browser.
Open a new tab and point it to the "edge://webrtc-internals/" URL.
Open the Teams Web application and reproduce the problem.
Go back to the "edge://webrtc-internals/" tab, there will be at least two tabs: 
GetUserMedia Requests and https://teams.microsoft.com/url. You'll see logs along with stats graphs.
Choose the tab with the name of the Teams application and save the page content as Web Page, Complete.
Important: Stats graphs are not available in the saved file! We recommend either to analyze graphs while being on the edge://webrtc-internals/ tab, or make screenshots for further analysis.

Chrome web browser
Edge (Chromium) web browser
The browser tracks and logs all WebRTC connections, so close all tabs and restart the browser.
Open a new tab and point it to the "chrome://webrtc-internals/" URL.
Open the Teams Web application and reproduce the problem.
Go back to the "chrome://webrtc-internals/" tab, there will be at least two tabs: 
GetUserMedia Requests and https://teams.microsoft.com/url. You'll see logs along with stats graphs.
Choose the tab with the name of the Teams application and save the page content as Web Page, Complete.
Important: Stats graphs are not available in the saved file! We recommend either to analyze graphs while being on the chrome://webrtc-internals/ tab, or make screenshots for further analysis.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d5e6d3-b7e0-d79f-0dea-ed423186a157
* Version Independent ID: ec6e68aa-552f-ab45-3c8e-92eff526b173
* Content: [Use log files in troubleshooting Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/log-files#debug-logs)
* Content Source: [Teams/log-files.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/log-files.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@greganth1 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @greganth1, thank you for your feedback.

Do you think we should add these instructions to the media logs sections?

**Comment by greganth1** [comment]
That would be the logical choice as it appears to be the appropriate section.
