### ISSUE TITLE
Dupulicate Teams Rooms update  procedure

### ISSUE THREAD

**Issue by Takashi26** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7622]
Different steps are posted on the following site.　Please post it in one place.

Deploy --> Manually update a device
https://docs.microsoft.com/en-us/microsoftteams/rooms/manual-update

Manage  -->Maintenance and Operations
https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-operations#software-updates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4fa80cf-0319-c006-e886-4929a508b04c
* Version Independent ID: 9d598765-fc30-17f0-6594-57de81d8aa39
* Content: [Manually update a Microsoft Teams Rooms device - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/manual-update#feedback)
* Content Source: [Teams/rooms/manual-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/manual-update.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@Takashi26 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Takashi26 
I dug into this, in reality, there are two methods available, and in the newer (https://docs.microsoft.com/en-us/microsoftteams/rooms/manual-update) you have the option of using PowerShell remoting to update the MTR.
Hope this clarifies it to you,
Thanks

**Comment by get-itips** [comment]
@scanum please close. thanks

**Comment by Takashi26** [comment]
In the section https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-operations#software-updates, the appx-package update procedure from deployment kit is mentioned.   For this section, I think the newer update procedure should be mentioned.
