### ISSUE TITLE
Wrong IP range for Office 365 GCC High environment?

### ISSUE THREAD

**Issue by IT2Day** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7623]
[Enter feedback here]
under sip-signaling-fqdns
Office 365 GCC High environment is listed with the same range as
Office 365 GCCH and DoD environment : 52.127.64.0/21

while for media-traffic-port-ranges
It's listed with 52.127.88.0/21

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e26faf8c-529e-b317-5934-cd41cfe8fa24
* Version Independent ID: 3ddd5d0a-6dbb-4940-1814-8346e293701b
* Content: [Plan Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-plan#microsoft-365-office-365-and-office-365-gcc-environments)
* Content Source: [Teams/direct-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@IT2Day Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
