### ISSUE TITLE
Conference Mode setting

### ISSUE THREAD

**Issue by jrummer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7625]
Conference mode has changed, its no longer Auto, its now On or Off.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b755d9ae-13ac-019f-f5f4-a95b1eee2989
* Version Independent ID: f7afd8ad-e6e0-6c79-aed1-4ee87d48ba12
* Content: [Create a call queue in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/create-a-phone-system-call-queue?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-call-queue.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@jrummer Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
