### ISSUE TITLE
Direct Routing and LBR for Conferencing

### ISSUE THREAD

**Issue by greganth1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7626]
Document needs update to add expected behavior of Location-Based Routing for Conferencing in Teams Direct Routing.

Scenario to address.

Customer has Direct Routing enabled. He organized a meeting and invited external participant into the meeting.
	
This external participant has LBR enabled in her/his home tenant. 
	
Now if anyone in the meeting use the Dial Out option by adding PSTN number, then the Dial Out does not work and it gives the message in Teams "Call not allowed due to organization's settings"
	
However, if the external LBR enabled participant leaves the meeting and then all user rejoins the meeting again except external participant, then the Dial Out to PSTN number would work fine.

The tenant who organized the Teams meeting, they have no LBR enabled. Issue only arises when external participant who has LBR enabled joins the meeting.

Expected as LBR enabled participant can't speak over the phone with someone on PSTN without bypassing PSTN tolls (regardless of who tries to invite the PSTN user).

This is addressed in the LBR for Conferencing for Skype for Business Server documentation here https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/enterprise-voice-solution/lbr-for-conferencing but not the Direct Routing documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e427e0b-ef18-6947-27a6-eb75ddbdead7
* Version Independent ID: baf34a47-7d43-8291-7792-dd0b5dac1931
* Content: [Plan Location-Based Routing for Direct Routing - Microsoft Teams](https://review.docs.microsoft.com/en-us/microsoftteams/location-based-routing-plan)
* Content Source: [Teams/location-based-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/location-based-routing-plan.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@greganth1 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by HowlinWolf-92** [comment]
@greganth1 Did the user join via VOIP or PSTN?
