### ISSUE TITLE
Live Caption Options in wrong section

### ISSUE THREAD

**Issue by rnlgreen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7628]
I don't understand why "Enable Live Captions" is in the "Participants and Guests" section, when this option appears to be specific to the authenticated user to which this policy is applied.  Guest Live Caption options appear to be dictated by the options their accounts are subject to in their own tenant's meeting policies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4521de2b-1aae-93de-ee1a-222146194700
* Version Independent ID: b4f9087c-e1a3-8b47-917c-7c294d46fcca
* Content: [Manage meeting policies for participants and guests - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/meeting-policies-participants-and-guests?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/meeting-policies-participants-and-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-participants-and-guests.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@rnlgreen Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @rnlgreen, thank you for your feedback.

An authenticated user is also a participant in a meeting. What section do you recommend to locate this setting?
