### ISSUE TITLE
Documentation and Skype Broadcast

### ISSUE THREAD

**Issue by greganth1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#763]
The documentation is confusing.  The modern portal is a combined Teams and Skype for Business settings.  Not mentioning Skype for Business in the "Let your Teams users chat and communicate with users in another Teams organization" gives customers a false sense of security that changes they make won't affect their existing Federation settings if they have been running Skype for Business and have open Federation already.  
The documentation does not warn that if they have Skype Broadcast and are open Federation that they need to add the broadcast domains if they add a domain with the Allowed status and save the changes as now their Federation will be closed and break Skype Broadcast.  
The portal needs a warning or needs to be more intuitive like the old portal and the documentation needs to be updated to reflect that changes in either affect each other.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Communicate with Teams users in another organization](https://docs.microsoft.com/en-US/MicrosoftTeams/let-your-teams-users-communicate-with-other-people?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/let-your-teams-users-communicate-with-other-people.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/let-your-teams-users-communicate-with-other-people.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@greganth1 Thank you for this feedback

I want to make sure this article gets clarified. I am making sure the Teams/Skype for Business team gets this for review and update. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @greganth1 thanks for taking the time to submit feedback, we really appreciate it.
I did a test in lab and domains added to Skype legacy portal were instantly viewed in Teams Admin portal, maybe at the time you created this issue this wasn't working as expected.
Hope this information helps you.
Thanks.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @greganth1 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
