### ISSUE TITLE
You are not permitted to invoke Set-CsTeamsMeetingPolicy with the following parameters:  MeetingRecordingExpirationDays

### ISSUE THREAD

**Issue by beanfeast** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7630]
This page contains an example of the command that can be used to change the expiration period.
<pre>Set-CsTeamsMeetingPolicy -Identity Global -MeetingRecordingExpirationDays 50</pre>

When I tried to change the expiration period I was notified that "You are not permitted to invoke Set-CsTeamsMeetingPolicy with the following parameters: MeetingRecordingExpirationDays" as can be seen below.

<pre>Set-CsTeamsMeetingPolicy -Identity Global -MeetingRecordingExpirationDays 120

You are not permitted to invoke Set-CsTeamsMeetingPolicy with the following parameters:
 MeetingRecordingExpirationDays
    + CategoryInfo          : NotSpecified: (:) [Set-CsTeamsMeetingPolicy], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.Rtc.Management.Internal.SetTeamsMeetingPolicyCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com</pre>

Is this command currently available for use?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/cloud-recording#auto-expiration)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@beanfeast Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by rhodson-bakonw** [comment]
Hi, we are also getting the exact same error when running the command.

**Comment by etellier** [comment]
Same issue/error with all other meetings policies, not only Global policy .....
Tried with the last MicrosoftTeams module release 2.3.1 and the preview module 2.4.1.

**Comment by kevin-campbell** [comment]
I was also able to replicate this issue when attempting to adjust the Teams meeting recordings

Just as a consideration, this will start having a larger impact as users receive and react to Microsoft 365 Roadmap ID: 84580. 

To change the default expiration days at the tenant level, there will be two methods available. 
1.	You can use PowerShell to modify “MeetingRecordingExpirationDays.” This can be done at any time, as the setting is present in PowerShell today even though the feature is not yet enabled. An example command is: "Set-CsTeamsMeetingPolicy -Identity Global -MeetingRecordingExpirationDays 50” 
2.	As this feature is rolled out, a new setting will be available in the Teams admin center. 

Additional Documentation: 
https://www.microsoft.com/en-us/microsoft-365/roadmap?searchterms=82057&searchterms=84580&filters=&searchterms=84580
https://docs.microsoft.com/en-us/microsoftteams/cloud-recording#auto-expiration

**Comment by soholingo** [comment]
I can't find this command anywhere and I am unable to load any of the older Skype for Business modules to confirm.  I have installed the updated Teams Module 2.3.1.  I have also checked the Teams Admin page, again no options available to configure the MeetingRecordingExpirationDays. 

We received the same notice.  Can't believe the command isn't available.

**Comment by Briggidy** [comment]
They just updated the announcement

Note: The cmd to preemptively change the MeetingExpirationDays setting in Teams is not available yet, we apologize for the inconvenience. It will be available for all tenants to set by September 1st before the expiration feature is enabled.

**Comment by soholingo** [comment]
Roadmap has this as being in development...  
[Roadmap 84580](https://www.microsoft.com/en-us/microsoft-365/roadmap?searchterms=82057&searchterms=84580&filters=&searchterms=84580)

**Comment by get-itips** [comment]
@scanum please close as the article has been updated clarifying this.

**Comment by beanfeast** [comment]
It is now September 2nd. The functionality to allow the "-MeetingRecordingExpirationDays" parameter to work was meant to be enabled yesterday but when I try using it I am still informed that I am "not permitted to invoke Set-CsTeamsMeetingPolicy with the following parameters: MeetingRecordingExpirationDays"

When should I expect to be able to use this command successfully?

Set-CsTeamsMeetingPolicy -Identity Global -MeetingRecordingExpirationDays 120
You are not permitted to invoke Set-CsTeamsMeetingPolicy with the following parameters:
 MeetingRecordingExpirationDays
    + CategoryInfo          : NotSpecified: (:) [Set-CsTeamsMeetingPolicy], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.Rtc.Management.Internal.SetTeamsMeetingPolicyCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com

**Comment by get-itips** [comment]
@beanfeast please refer to Message Center ID MC274188 as the ETA for the functionality has been updated.
