### ISSUE TITLE
Update the document

### ISSUE THREAD

**Issue by rajeevlpk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7631]
Please update the typo in below sentence.

'You can only assign TeamsOnly mode to the entire tenant after both of the following steps **ahve** been completed:'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffbf0bfd-c15e-b10b-0cc9-6a27ac1e6634
* Version Independent ID: 58575371-9e09-fadb-76f6-7491df8580a3
* Content: [Set your coexistence and upgrade settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/setting-your-coexistence-and-upgrade-settings)
* Content Source: [Teams/setting-your-coexistence-and-upgrade-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/setting-your-coexistence-and-upgrade-settings.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@rajeevlpk Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
