### ISSUE TITLE
A couple minor editing notes

### ISSUE THREAD

**Issue by LastThird** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7637]
A couple minor editing notes:

>The upcoming retirement of Skype for Business Online has no impact on the existing support lifecycle of Skype for Business Server or Lync Server 2013. However, the upcoming retirement of Skype for Business Online will impact certain **apsects** of how customers with on-premises Skype for Business Server or Lync Server 2013, including existing hybrid organizations, transition to the cloud. What will not change after retirement is that the use of hybrid as the means to transition from on-premises to the cloud remains unchanged.

"apsects" --> "aspects"

----
>After the retirement of Skype for Business Online, however, hybrid organizations can only consist of two basic types of users:
>- On-premises users (Who **may or may use** Teams, but not in TeamsOnly mode)

I assume this is supposed to say "may or may **not** use"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c0ab608-c57e-0e72-6071-5fc02cf6217c
* Version Independent ID: 73c13bf0-4247-ad87-e3be-7d9a59ab457e
* Content: [Plan hybrid connectivity - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-hybrid-connectivity#feedback)
* Content Source: [Skype/SfbHybrid/hybrid/plan-hybrid-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/plan-hybrid-connectivity.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@LastThird Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
