### ISSUE TITLE
How users knows if the upload is failed?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7644]
Hi,

On the page you wrote:
_If a Teams meeting recording fails to successfully upload to OneDrive/SharePoint Online, the recording will instead be temporarily saved to Azure Media Services (AMS)._ 

But you do not clarify if this noticed somehow by user? How users could know if there as some actions required still from them?

Could you please add a comment of that to the page as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8935e913-806f-a92c-d09e-e67df4ffd1b4
* Version Independent ID: c7a41cde-66dd-d7cd-1316-42d20ed4841a
* Content: [Use OneDrive for Business and SharePoint Online for meeting recordings - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/tmr-meeting-recording-change)
* Content Source: [Teams/tmr-meeting-recording-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tmr-meeting-recording-change.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Petri-X I tested that scenario, will propose an improvement to the article, thanks for your feedback

![image](https://user-images.githubusercontent.com/36666927/129074275-1a6392ab-e49d-4a7c-af11-c0fe14841869.png)

**Comment by Petri-X** [comment]
That is great news. Big thanks for your effort !
