### ISSUE TITLE
Pin Apps for External / Guest Users using Policy in Teams

### ISSUE THREAD

**Issue by arjunumenon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7647]
Hello Team,

I am not sure I am posting the issue on the right channel. 

We are trying to pin the Apps to the Teams for the external users via policy. The policy is getting applied to the internal users, but is not getting applied to external users? All the external users see are the same apps. 

Attaching screenshot for more information.

### Internal / AD User Interface
![image](https://user-images.githubusercontent.com/10369964/128349192-fd42ffe2-d4f4-4cfc-9ddd-ef298867b432.png)

### External User Interface
![image](https://user-images.githubusercontent.com/10369964/128349236-79dbaced-27d4-48a3-bc1e-0fcbfc06a302.png)

Is that an intended behavior of the Teams Platform? If Yes, then I guess it is good to have that added in the documentation so that it will be beneficial for others who are trying to achieve the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0735d322-f6f5-7cc8-9994-1420e3fb7baa
* Version Independent ID: f9b25b51-eb9c-63fa-b30e-e1490c8d31b6
* Content: [Teams apps behavior for non-standard users - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/non-standard-users#install-update-and-delete-for-external-users)
* Content Source: [Teams/non-standard-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/non-standard-users.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
