### ISSUE TITLE
Does it require live events enabled?

### ISSUE THREAD

**Issue by billcruze** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7653]
Teams meeting policies are already enabled but the webinar is still not available. When we enabled live events policy, it shows up on the dropdown in the team's client.

Need to confirm if Live Events is required or are we missing something.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
