### ISSUE TITLE
Incorrect instructions

### ISSUE THREAD

**Issue by VladimirGluten47** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7659]
https://docs.microsoft.com/en-us/microsoftteams/rooms/manual-update links to this page for instructions on how to switch to the Admin account _without_ logging out the Skype user, keeping the Teams app running. The instructions given in this page state that the actions will log the Skype user out and close the Teams app (which is the case). Missing are instructions for switching from the Skype user to the Admin user while keeping the Skype user logged in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd52fe62-457b-c9e1-ad13-a9b1f24c9c38
* Version Independent ID: 6a8c3285-30e1-15a8-6472-f0cfe5b30e20
* Content: [Microsoft Teams Rooms maintenance and operations - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-operations#switching-to-admin-mode-and-back-when-the-microsoft-teams-rooms-app-is-running)
* Content Source: [Teams/rooms/rooms-operations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-operations.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@VladimirGluten47 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @VladimirGluten47, thank you for your feedback and help us to improve docs.microsoft.com.

I understand you are talking about step 7: "Enter the Administrator Password. This will gracefully log off the app and take you to the Windows login screen."

Really what the articles are saying is that you need to log on to the administrator account without logging off the sfb user. Did you try these steps and they didn't work? Did you get an error similar to "Prerequisite: The Skype user must be logged in for this script to work correctly. Please reboot the system, and run this script without signing the Skype user out."?

**Comment by VladimirGluten47** [comment]
Hi Dario,

That's correct, I'm referring to step 7. I followed the instructions to log into the Admin user (same steps as for any troubleshooting within Windows), however when running the script I did receive an error similar to "Prerequisite: The Skype user must be logged in for this script to work correctly. Please reboot the system, and run this script without signing the Skype user out."

So I am wondering if there is an alternate method for logging into the Admin user which meets these requirements, or perhaps I'm just doing something wrong and the instructions are unclear?

Thanks.

**Comment by dariomws** [comment]
@VladimirGluten47 let's try this:

1. When you are logged with the sfb user, press Windows Key 5 times. It should redirect you to the home/login screen.
2. Login with the admin user.
3. Run the script.
4. Press Windows Key 5 times again to return to the sfb user.

Please let me know if it works for you.
