### ISSUE TITLE
Hyperlink to apply does not work 

### ISSUE THREAD

**Issue by Siby22071989** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7660]
[Enter feedback here]

**Step 2. Apply for Microsoft 365 Government - GCC**

The hyperlink to Apply does not work. It takes to a blank page with error
**We are sorry, the page you requested cannot be found.**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7faee29-6d56-f3bf-766c-6deaefe92e34
* Version Independent ID: 6029b6f8-7d49-6474-fa40-2793000c74a4
* Content: [Microsoft 365 Government - GCC deployments - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/plan-for-government-gcc#step-2-apply-for-microsoft-365-government---gcc)
* Content Source: [Teams/plan-for-government-gcc.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-for-government-gcc.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@Siby22071989 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Siby22071989** [comment]
Unfortunately it does not. This is what it shows. Is there a environment restriction? 
 

We are sorry, the page you requested cannot be found.
The URL may be misspelled or the page you're looking for is no longer available.

**Comment by lindspea** [comment]
Please try this one. https://www.microsoft.com/en-us/microsoft-365/government/eligibility-validation?rtc=2

**Comment by Siby22071989** [comment]
Thank you. This works

**Comment by lindspea** [comment]
@Siby22071989 thank you for confirming. I see the link is working now too.
