### ISSUE TITLE
Microsoft 365 Enterprise E1 ?

### ISSUE THREAD

**Issue by mikelabca** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7661]
Hello,

This doc says that Microsoft Business Voice can be added to Microsoft 365 Enterprise E1/E3 but as far as I know, Microsoft 365 E1 doesn't exist or at least, I can't find that SKU. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abae7324-861d-7ca7-7239-a5df8fd927d5
* Version Independent ID: 8a30bd2f-9bc3-a0a8-8b31-d53836ead4d0
* Content: [Microsoft Teams add-on licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=small-business)
* Content Source: [Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by mikelabca** [comment]
This SKU GUID (18181a46-0d4e-45cd-891e-60aabd171b4e) is for Office 365 E1, not Microsoft 365 E1. 

The doc lists both Microsoft 365 E1/E3 and Office 365 E1/E3 on two lines if you scroll down on that page where the **Small business (<300 people)** table is located.

**Comment by M0rfic** [comment]
Hmm, you're right, there is some confusion here, sorry if I contributed even more to it. I just assumed those were the only ones remaining after [this change](https://www.microsoft.com/en-in/microsoft-365/office-365)

![image](https://user-images.githubusercontent.com/909971/128909392-5b02bc22-e350-4157-9d8a-7eefd6f6f65e.png)

![image](https://user-images.githubusercontent.com/909971/128909562-176cf197-5496-46ba-9519-deb30893bee1.png)

But then again, perhaps I was wrong or the not all the docs were yet updated...

**Comment by mikelabca** [comment]
Its ok, don't worry ;)

Office 365 E1 and Office 365 E3 still exists and as far as I know its not supposed to disappear.

Microsoft 365 E3 and Microsoft 365 E5 was introduced as a new SKU, I believe, in the same period of the products rename.

As far as I know, Microsoft 365 E1 has never been a thing.
