### ISSUE TITLE
Error Running CreateSrsMedia

### ISSUE THREAD

**Issue by Su7ech** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7662]
I cant seem to get the createsrsmedia to run. I get the following in the log below:

Host OS version 10.0.19043.1110
Script version 1.6.1
Downloading CreateSrsMedia...
done
Validating signature for update.ps1...
success.

AC403E566D17C0D78E767CC57544D767000724D9055A51AF6F9ACF4A31A3D5081FAE8F864D9D577633B273C6D5A0C344D74BB47A6DB6B016D57F735FD06216C9
73835

What type of customer are you?
Please make sure you have all of the following available:

1. A USB drive with sufficient space (16GB+).
   The contents of this drive WILL BE LOST!
2. Windows 10 Enterprise media that matches your SRSv2 deployment kit.
   Enterprise customers can access Windows 10 Enterprise media from the Volume Licensing Service Center:
   http://www.microsoft.com/licensing/servicecenter
3. Any language pack (LP and/or LIP) files to be included.
   MPSA customers:         http://go.microsoft.com/fwlink/?LinkId=125893
   Other volume licensees: http://www.microsoft.com/licensing/servicecenter

Please do not continue until you have all these items in order.

Downloading deployment kit...
PS>TerminatingError(Save-Url): "Exception calling "DownloadFile" with "2" argument(s): "The operation has timed out""
**********************
Windows PowerShell transcript end
End time: 20210810071707
**********************

It fails pretty early on so I'm not sure what I'm missing.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
