### ISSUE TITLE
Microsoft Business Voice GUIDs

### ISSUE THREAD

**Issue by M0rfic** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7663]
Hi,

Would it be possible to also include the SKU GUID besides the SKU part name, similar to how it's done in the [licensing service plan reference](https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/licensing-service-plan-reference)? In my particular case I'd like to assign some of the  "_Microsoft Business Voice *_" products using Microsoft Graph (which requires GUIDs as per [the docs](https://docs.microsoft.com/en-us/graph/api/resources/assignedlicense?view=graph-rest-1.0)) as I do with the rest of the products in the aforementioned link (E1, E3, etc), and I was not able to find them anywhere. Alternatively if there is a link I missed or any other source providing the GUIDs , I'd be grateful if you would share it.

Kind regards
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed46e6b1-48c5-5302-2f38-89c315d4bff7
* Version Independent ID: 81053999-79ca-888d-38fa-8978276b6228
* Content: [Assign Teams add-on licenses to users - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/assign-teams-add-on-licenses#product-names-and-sku-identifiers-for-licensing)
* Content Source: [Teams/teams-add-on-licensing/assign-teams-add-on-licenses.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/assign-teams-add-on-licenses.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@bratsche Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @M0rfic 
How are you? Sorry for the late reply.
I see that some Business Voice GUIDs were added [in the article](https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/licensing-service-plan-reference) you included after you created this issue.

Did you have a chance to look at them?
Thank you

**Comment by M0rfic** [comment]
Hi @get-itips 

Thank you, much appreciated! They will probably come in handy very soon, for the time being we resorted to checking the service plans included with each subscription, eg MCOEV, TEAMS1 etc, for which we already knew the GUIDs.

Kind regards
