### ISSUE TITLE
Participants & guests clarification

### ISSUE THREAD

**Issue by DarlishaCampbell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7665]
The docs page does not clearly say which of the bypass options are available to guests, anonymous users, and authenticated users within an organization. It would be beneficial to have an area that shows how guests and anonymous users are handled with each bypass option. This feedback comes from a customer question where it is stated in the support docs that if a user does not have a Teams account they will be considered a guest and forced into a lobby regardless of the meeting option selected for that meeting. It would be beneficial to have a disclaimer similar to this on the main page or a table giving more clarity on how each bypass option is handled. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4521de2b-1aae-93de-ee1a-222146194700
* Version Independent ID: b4f9087c-e1a3-8b47-917c-7c294d46fcca
* Content: [Manage meeting policies for participants and guests - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-participants-and-guests)
* Content Source: [Teams/meeting-policies-participants-and-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-participants-and-guests.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @DarlishaCampbell, thank you for your feedback and help us to improve docs.microsoft.com.

I'm adding some missing information to the table to clearly states the information you're asking for. It should be live in a couple of days, and I hope it helps.

**Comment by DarlishaCampbell** [comment]
Thank you so much for your help in this matter.

Thank you,

Darlisha Campbell
Escalation Engineer | Teams
***@***.******@***.***>
