### ISSUE TITLE
Broken links - MS Teams for Linux page and repo are inaccessible

### ISSUE THREAD

**Issue by chrispalaskas** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7666]
[Enter feedback here]
I was following the documentation of this page a few days ago and I installed Teams on an Ubuntu machine, but I couldn't login from the App, only from the web browser.
Today I decided to unistall and start over, but https://packages.microsoft.com/repos/ms-teams is down,
and from the main Teams page, there is 404 Not found when I click the both Deb and Rpm releases for 64bit.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@chrispalaskas thank you for reaching out. Just for clarity, is there a link in this article that you are referring to that is giving the error 404? Please also see the information in this link and let me know if it helps - https://techcommunity.microsoft.com/t5/microsoft-teams-blog/microsoft-teams-is-now-available-on-linux/ba-p/1056267

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
