### ISSUE TITLE
Modify cmdlets that need to be run to check in item 1 for decom and then cmdlet for item 2 for decom.

### ISSUE THREAD

**Issue by NicholasBurkhammer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7668]
Under section https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/decommission-remove-on-prem#prepare-to-remove-the-skype-for-business-deployment, add the following.

Under item 1:

Add line of cmdlet for Get-CsUnassignedNumber

Under item 2:

Add line of cmdlet for Get-CsUnassignedNumber | Remove-CsUnassignedNumber -Force

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 809826d2-e82d-0b31-0c8b-c475db0efbb8
* Version Independent ID: b4e15a5f-8096-21db-c120-63e99d601328
* Content: [Decommission Skype for Business Server - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/decommission-remove-on-prem?source=docs#remove-your-on-premises-skype-for-business-deployment-1)
* Content Source: [Skype/SfbHybrid/hybrid/decommission-remove-on-prem.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/decommission-remove-on-prem.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
