### ISSUE TITLE
Error in New Front End Pool Step 6 and 7 (cannot be done in SQL 2017)

### ISSUE THREAD

**Issue by youseeadam** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#767]
In the section Deploy an Always On Availability Group on an existing pool that does not use database mirroring Step 6 Create the availability group. The instructions say to create the AG.  However with SQL 2017 you cannot create an AG on a server with no databases.
In step 7: Use Topology Builder to create the Front End pool, as explained in Create and publish new topology in Skype for Business Server. When you do, specify the AG as the SQL store for the pool.  The AG is not an object in AD (I.E. no FQDN for an AG since an AG has not IP address).
So what I think you have to do is first create the database using no availability group setting, and using the primary server for the SQL server, then Build the database, then build the listener and then build then set the availability group setting in topology builder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c3f0aa8-8192-73c1-0b5d-acafc7bc0860
* Version Independent ID: 39eeb704-22ec-0945-b02e-08d1ca5aee5a
* Content: [Deploy an Always On Availability Group on a Back End Server in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-high-availability-and-disaster-recovery/alwayson-availability-group)
* Content Source: [Skype/SfbServer/deploy/deploy-high-availability-and-disaster-recovery/alwayson-availability-group.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-high-availability-and-disaster-recovery/alwayson-availability-group.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by AndreaBarr** [comment]
@youseeadam Thank you for this feedback

We appreciate you pointing this out to us and taking the time to help make the docs better. I will get this over to the Teams/Skype for Business team for investigation and updating. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by DriveHeart** [comment]
@AndreaBarr Yeah~,I also found the issue said by @youseeadam .When  I gone to the end of step 8, the command "**Install-CsDatabase -Update**"could not work perfectly.Error message is "**Install-CsDatabase : Parameter set cannot be resolved using the specified named parameters.**" Thanks

**Comment by get-itips** [comment]
Hello @DriveHeart thanks for your feedback.
As I could not reproduce it, it will be better if you direct your inquiry to support resources https://support.microsoft.com/en-us/supportforbusiness/productselection 
Thank you

**Comment by scanum** [comment]
@DriveHeart  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
