### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by Torxsmind** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7676]
The document section "Change a user's number to a service number or a service number to a user's number" has a link to  "Send  US your PIN" which is a link to an email address.  However, I get an auto email response stating"

"Please note that we are not accepting any new requests over email. If you have a new request, please log into the Teams Admin Center, go to the "Phone Numbers" page and click on the "Get phone number support" button. For your existing requests, we will continue to respond here until the request is resolved."

This doc needs updated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1778d5e3-1cd3-9323-d7f0-6ee14aa69f24
* Version Independent ID: 66402fb0-4a46-65af-91ac-caa9a3d60a1f
* Content: [Phone number management for the United States - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization/phone-number-management-for-the-u-s?WT.mc_id=365AdminCSH_TeamsAdminCenter)
* Content Source: [Teams/manage-phone-numbers-for-your-organization/phone-number-management-for-the-u-s.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-phone-numbers-for-your-organization/phone-number-management-for-the-u-s.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Torxsmind Keith, thanks for the feedback!
