### ISSUE TITLE
correct documentation

### ISSUE THREAD

**Issue by Strick1969** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7678]
federated chat where one domain initiates federated chat to two domains, but those two are not federated with each other

this is not documented but does work, as a matter of fact we specifically say on this page that it doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ac8f101-bdb5-2b55-d5f4-e070b70768d4
* Version Independent ID: 964d836e-d00b-b585-8f02-e03c5ec8dab9
* Content: [Native chat experience for external (federated) users in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/native-chat-for-external-users?source=docs:report)
* Content Source: [Teams/native-chat-for-external-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/native-chat-for-external-users.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Strick1969, thank you for your feedback and help us to improve docs.microsoft.com.

This article is about the native chat experience for external users. I cannot find where it states that group chat doesn't work.

Support for group chat with external users was added here:
https://docs.microsoft.com/microsoftteams/communicate-with-users-from-other-organizations#compare-external-and-guest-access
