### ISSUE TITLE
Kilo Bytes or Kilo bits?

### ISSUE THREAD

**Issue by trevorherrmann** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7685]
[Enter feedback here]
Hello,

The bandwidth requirements show the bitrate in "KB/s" which represents Kilo Bytes and not Kilo Bits. Are we to assume that these numbers are 1/8 the size needed for the circuit? So for instance the 4,000KBps (4MBps) would need a circuit of 32,000Kbps (32Mbps)? 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d996cf7-9f48-2b30-7759-afaf3fe82caa
* Version Independent ID: 24dd6cdf-d35f-53b2-06c2-0a27891825d4
* Content: [Prepare your organization's network for Teams - Microsoft Teams](https://docs.microsoft.com/en-gb/MicrosoftTeams/prepare-network)
* Content Source: [Teams/prepare-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/prepare-network.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by VitalyMCT** [comment]
I am 99% certain Microsoft meant to say Kb/s instead of KB/s on this page - i.e. the documentation has an error. It was thus strange to see this ticket closed without any follow up action.
