### ISSUE TITLE
Typo "Window and Mac desktop clients"

### ISSUE THREAD

**Issue by TestValleySchool** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#769]
"Debug logs are produced by the **Window** and Mac desktop clients," should read "...**Windows** and Mac desktop clients".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d5e6d3-b7e0-d79f-0dea-ed423186a157
* Version Independent ID: ec6e68aa-552f-ab45-3c8e-92eff526b173
* Content: [Use log files in troubleshooting Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/log-files)
* Content Source: [Teams/log-files.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/log-files.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@TestValleySchool I have fixed the typo you pointed out. Thank you again for finding this typo.
