### ISSUE TITLE
statement duplicated

### ISSUE THREAD

**Issue by mariolonghi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#77]
The statement below seems to be duplicated in the article:
Allow users to send emails to channels: When turned on, mail hooks are enabled, and users can post messages to a channel by sending an email to the email address of Teams channel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9b7f77-061d-a224-ff1c-8d3e15d21221
* Version Independent ID: 00fa9550-c4c4-3398-ffbb-271cc724048f
* Content: [Manage Microsoft Teams features in your Office 365 organization | Microsoft Docs](https://docs.microsoft.com/en-us/MicrosoftTeams/enable-features-office-365)
* Content Source: [Teams/enable-features-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enable-features-office-365.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by LolaJacobsen** [comment]
Good catch - thanks for the heads up. I removed the dupe. Fix will go live later today.  Thanks again!
