### ISSUE TITLE
Prevent user groups creation

### ISSUE THREAD

**Issue by rboterenbrood** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#770]
"In our experience, user education helps ensure responsible Teams usage".
Yeah. I'm managing Office 365 and Teams on a secondary school. It's not even possible to get the teachers educated on correct usage, let alone the students.
Teams Education will be a lot more adoptable once Microsoft acknowledges that.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 815d1ce1-cb68-25b5-6a59-435461559495
* Version Independent ID: 1f6ac386-4ca4-1cde-bae0-ed6df8c94d61
* Content: [Microsoft Education governance Veelgestelde vragen voor IT-professionals - Microsoft-Teams](https://docs.microsoft.com/nl-nl/MicrosoftTeams/plan-teams-governance-edu)
* Content Source: [Teams/plan-teams-governance-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.nl-NL/blob/live-sxs/Teams/plan-teams-governance-edu.md)
* Service: **msteams**
* GitHub Login: @rmw2890
* Microsoft Alias: **MyAdvisor**

**Comment by AndreaBarr** [comment]
@rboterenbrood Thank you for this feedback

I will get this informaiton over to the Teams/Skype for Business team for investigation and update. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by kenwith** [comment]
Thank you for this feedback and sorry for the delay in response. This was passed to the team handling education and I heard this discussed in meeting back when it was brought up. If you are stilling seeing issues that can be addressed in the content please go ahead and re-open.
