### ISSUE TITLE
broken download link for USB provisioning

### ISSUE THREAD

**Issue by Brtrnd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7700]
[Enter feedback here]
Configure via USB key > download link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f256cd5b-3ec8-2d55-9ae4-ff9849d52eae
* Version Independent ID: 52c2271b-df38-5dc9-c2a1-553cdf3b5496
* Content: [Deploy Microsoft Teams for Surface Hub - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-surface-hub)
* Content Source: [Teams/teams-surface-hub.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-surface-hub.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by chuckedmonson** [comment]
@SerdarSoysal -- Would you please have someone look into this link issue and fix? Thank you.

**Comment by lindspea** [comment]
@Brtrnd thank you for reaching out. I've just checked the article and I'm not seeing a link to configure via USB key. Please can you have another look and let me know. Perhaps the article was updated in the interim.
