### ISSUE TITLE
Incomplete instructions

### ISSUE THREAD

**Issue by pheb92** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7703]
[Enter feedback here]
https://docs.microsoft.com/en-us/microsoftteams/rooms/with-exchange-online

Following the instructions:
If you edit an existing room mailbox in a hybrid environment, where the mailboxes are stored in EXO, you will not be able to login at all. The instructions are missing, that changes need to be made to the AD user object on-prem. By default an existing room mailbox is connected to a disabled user object in AD and the password you set for the room mailbox in the cloud is not set for the user object in AD. 

So after following the instructions for editing the existing room mailbox, the AD user object needs to be:
* enabled
* the password needs to be set (same as for the room mailbox)
* the password should not expire

Start AD Connect sync. Now you will be able to login with the room mailbox.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by pheb92** [comment]
> Thank you for submitting feedback.
> I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
> Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
> Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

Thanks for the quick feedback. I don't need support, i already solved the issue. 
The documentation describes the necessary steps to create a **new room mailbox** (including instructions for the local AD), but is lacking a few essentials steps on-prem, if you want to edit an **existing room mailbox**. I described these briefly above and i believe this should be added to the docs (without them, the instructions are basically incomplete and will not work).
