### ISSUE TITLE
Out of date content

### ISSUE THREAD

**Issue by grahammw** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7704]
There are new features in the latest version of the Teams Panel app which are not documented on this page.  Please can it be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aba0f31-c5ad-5e3d-d630-ea2a7966fc3a
* Version Independent ID: fd7573c5-a9ba-5dea-3375-691548d1c971
* Content: [How to use Microsoft Teams panels devices - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/use-teams-panels)
* Content Source: [Teams/devices/use-teams-panels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/use-teams-panels.md)
* Service: **msteams**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @grahammw, thank you for your feedback.

There were several updates in the article since you opened this issue. I'm expecting that all the new features are documented now.
