### ISSUE TITLE
No external links work on this page

### ISSUE THREAD

**Issue by grahammw** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7709]
Nothing is working to any of the links on docs.  Gives a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 558d6f47-4ed9-9667-14cb-9aa038f0ebb5
* Version Independent ID: 626710b8-543b-2bf9-47a5-c1d368fab5c0
* Content: [Microsoft Teams apps/Line of Business (LOB) app support on Teams panels - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/app-support-on-teams-panels)
* Content Source: [Teams/app-support-on-Teams-panels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/app-support-on-Teams-panels.md)
* Service: **msteams**
* GitHub Login: @amandafrechinjackson
* Microsoft Alias: **v-amandaf**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @grahammw, thank you for your feedback and help us to improve docs.microsoft.com.

I've verified all the links and all of them are working. Could you kindly test them again? Thanks!

**Comment by grahammw** [comment]
Yes, all working now thank you
