### ISSUE TITLE
Teams Hardware RECOMMENDATIONS

### ISSUE THREAD

**Issue by StPhil** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#771]
Knowing the minimum is definitely helpful, but what are the recommended hardware specs for users who are consistently active in Teams, SfBO, Outlook, OneDrive, and a browser? Those who are working in massive Excel spreadsheets alongside the beforementioned? Those running VMs for other processes? That is what customers are asking for because that is the majority of use cases we are seeing. If Microsoft has these recommendations, will you please share them publicly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29a61ff5-b3a5-158d-149a-dec344060e05
* Version Independent ID: 97fac351-a283-aaa8-cde1-fbd9cf4e8504
* Content: [Hardware requirements for the Microsoft Teams app](https://docs.microsoft.com/en-us/microsoftteams/hardware-requirements-for-the-teams-app)
* Content Source: [Teams/hardware-requirements-for-the-teams-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hardware-requirements-for-the-teams-app.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@StPhil Thank you for the feedback

We apricate you catching this. I want to make sure I get this over to the Teams/Skype for business team so we can have the recommended specs listed. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @StPhil Thanks for taking the time to make suggestions.

This information isn't present in the documentation as hardware requirements are always specified with minimum needed. (Server software might be a exception) I suggest you add this feedback to Microsoft Teams User Voice https://microsoftteams.uservoice.com/forums/555103-public

Thank you!
