### ISSUE TITLE
Measurement of RGS Incoming Calls per Second, Concurrent Calls, Concurrent Sessions, etc.

### ISSUE THREAD

**Issue by rhmclean** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#772]
This page provides capacity planning but should have a reference to where/how the system is performing against those limits.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4146039-6a62-7a47-9f02-5600cb026c6c
* Version Independent ID: ab460f03-0253-4cdc-df42-4268f8987be2
* Content: [Plan for the Response Group application in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/enterprise-voice-solution/response-group)
* Content Source: [Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/response-group.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/response-group.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment]
@rhmclean Thank you for this feedback

We appriciate the sugesstion and I will get this to the Teams/Skype for Business team so they can investigate and update properly. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @rhmclean can you please explain with more detail what do you want to see in this document? What do you mean how the system performs against those limits? 
Thank you

**Comment by rhmclean** [comment]
There should be something in the system (e.g. reports server) that can be used to compare against the design. So, what report and how do we do convert the report information to do a comparison?

**Comment by get-itips** [comment]
Hi @rhmclean thanks for your answer, due to the nature of your inquiry, it would be more suitable for another kind of resource, please @yogkumgit can you help here? thanks

**Comment by yogkumgit** [comment]
@rhmclean  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
