### ISSUE TITLE
Duplicate lines in PowerShell script

### ISSUE THREAD

**Issue by JetzeMellema** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7723]
The first PowerShell script on this page contains two lines that are repeated:

$output | Export-Csv -Path .\SlackToAzureADIdentityMapping.csv -NoTypeInformation
Write-Host "`n $(Get-Timestamp) Generated SlackToAzureADIdentityMapping.csv. Exiting..."

$output | Export-Csv -Path .\SlackToAzureADIdentityMapping.csv -NoTypeInformation
Write-Host "`n $(Get-Timestamp) Generated SlackToAzureADIdentityMapping.csv. Exiting..."

I believe this is a script error and should be corrected. Should be:

$output | Export-Csv -Path .\SlackToAzureADIdentityMapping.csv -NoTypeInformation
Write-Host "`n $(Get-Timestamp) Generated SlackToAzureADIdentityMapping.csv. Exiting..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a81e1e5-3fd5-ff19-4f13-30bc2dd4389e
* Version Independent ID: e90e3618-95e7-7dc6-d020-2d0f75fcb6ff
* Content: [Migrate from Slack to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/migrate-slack-to-teams)
* Content Source: [Teams/migrate-slack-to-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/migrate-slack-to-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
