### ISSUE TITLE
Incorrect SkuPartNumber

### ISSUE THREAD

**Issue by marcgoff** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7724]
On this page, license guid e578b273-6db4-4691-bba0-8d691f4da603 lists a SkuPartNumber of M365EDU_A5_NOPSTNCONF_FACULTY, but in my tenant it is listed as ENTERPRISEPACKPLUS_FACULTY. In the Azure portal, it is listed as "Office 365 A3 for faculty".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae22e4df-3f88-8c54-c55e-a3cd4f720cbc
* Version Independent ID: 3be05aac-9860-e78c-aca7-c62de044c48b
* Content: [Education SKU reference - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/sku-reference-edu)
* Content Source: [Teams/sku-reference-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sku-reference-edu.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
