### ISSUE TITLE
Please update the part that says that Phone System licenses are required

### ISSUE THREAD

**Issue by JorgeALeitao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7728]
Please update the part that says that Phone System licenses are required
It's been more than two years since voicemail service has been enabled to all Teams users. 

Still this doc states that Phone System licenses are required for voicemail services, and this is confusing customers. 

Please fix it.

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8228f9b2-a7de-abb4-6f41-70db0b3af155
* Version Independent ID: 8fd9fafb-dd76-59a8-e609-56f06d539a31
* Content: [Set up Cloud Voicemail - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-phone-system-voicemail)
* Content Source: [Teams/set-up-phone-system-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-phone-system-voicemail.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @JorgeALeitao, thank you for your feedback.

I understand what you say, and I agree that the voicemail feature works without a Phone System license. But I understand that when you get Phone System (Microsoft Teams telephony solution), you also get the rights to use Cloud Voicemail.
You can also see similar information here:
https://docs.microsoft.com/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing
https://docs.microsoft.com/microsoftteams/what-is-phone-system-in-office-365

**Comment by JorgeALeitao** [comment]
Thanks Dario, the point in question is the one that says Phone System **is required**. This leads customers to believe that they have PS because they have v-mail and others to freak-out because think that Microsoft will charge them for PS licenses because they got v-mail enabled.

**Comment by dariomws** [comment]
My apologies @JorgeALeitao, but I cannot update the article. I want to add that when you get a Phone System license and you configure it as needed, the "Calls" icon will appear in the Teams client. There, you'll have a Voicemail tab to check the available voicemails.
Despite that even you can get voicemails with any Teams license, to get the rights to use it and fully enable the feature you need the Phone System license.

**Comment by JorgeALeitao** [comment]
That's OK Dario, I'm part of Teams Engineering and I get you can't make by yourself the decision to update the article. Please bring this up with Roy Kuntz or Carolyn Rowe.

However, I beg to disagree from the last part of your comment above, v-mail services are fully enabled with or without Phone System.

Thanks

**Comment by dariomws** [comment]
@JorgeALeitao, what I'm trying to say is that if you don't have a Phone System license, you won't get the "Calls" icon in the Teams client. If you don't have that icon, I understand that you won't be able to retrieve the voicemail using the Teams client. (you can with Outlook)

If you are part of Teams Engineering, could you kindly get the approval to change these sentences? I'll appreciate it.

@CarolynRowe could you kindly help here to confirm if we can update these sentences?

I cannot find Roy Kuntz's user name on GitHub.

Thanks to everyone!

**Comment by dariomws** [comment]
@JorgeALeitao you're right. I've verified in one tenant, and even if you don't have the phone system license, the "Calls" icon/app and the voicemail tab are available. So, now I understand that you need the Phone System license to get the dial pad inside the "Calls" icon or app. But the voicemail feature is fully enabled as you said.

I agree with you, but as you clearly understand, I cannot make the decision to apply this type of update.

Thanks!

**Comment by CarolynRowe** [comment]
@JorgeALeitao.  I'm meeting with @roykuntz tomorrow.  I'll follow up.

**Comment by dariomws** [comment]
Hi @scanum, this issue can be closed and this was confirmed and the article was updated by @CarolynRowe.
