### ISSUE TITLE
Skype for Business Server & Windows Server 2022 Support

### ISSUE THREAD

**Issue by micoolpaul** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7731]
Hi,

Can the system requirements page please be updated to clearly state whether any existing versions of Skype for Business Server will support Windows Server 2022 or if we’ll have to wait for Skype for Business Server 2022 to use Windows Server 2022.

Thanks!

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by micoolpaul** [comment]
Hi,

This isn’t a support issue, I’m enquiring about the lack of clarity within the Microsoft documentation if Skype for Business Server 2015 or 2019 will be supported on Windows Server 2022 now it has been released.

Thanks,
Michael
