### ISSUE TITLE
SBC Vendor Support

### ISSUE THREAD

**Issue by carolynblanding** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7733]
[Can we provide more details on how SBC vendors engage with Microsoft engineering for support?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1a1c01-10a9-7f69-1c7b-1a566b0f5112
* Version Independent ID: 329ee759-40fc-98fb-b91e-87786c63024b
* Content: [Session Border Controllers certified for Direct Routing - Microsoft Teams](https://review.docs.microsoft.com/en-us/microsoftteams/direct-routing-border-controllers?branch=main)
* Content Source: [Teams/direct-routing-border-controllers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-border-controllers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by FilippSe** [comment]
Sure, SBC vendors have direct channel to our internal SRE team and engineering

**Comment by tiburd** [comment]
Reviewer resolved issue in PR #8176 .
