### ISSUE TITLE
Engagement report not "off" by default

### ISSUE THREAD

**Issue by KaiserAlex** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7735]
[Enter feedback here]
In [docs.microsoft.com](https://docs.microsoft.com/en-US/microsoftteams/meeting-policies-in-teams-general?WT.mc_id=TeamsAdminCenterCSH) it says, that engagement report is off by default.
This was correct as the policy was set via PowerShellonly in the past.
Now it is available in Teams Admin Center to be set there the setting is ON by default.
So for me it looks like the documentation is not up-to-date any more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80cf0306-57b6-2b96-f105-651bf0dbb768
* Version Independent ID: 63c5a0be-28ee-3c7a-6520-12abce276e80
* Content: [Manage general meeting policies - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/meeting-policies-in-teams-general?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/meeting-policies-in-teams-general.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams-general.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @KaiserAlex 
How are you?
Actually, the default of a new policy will depend on the current value of the Global policy at the moment you create the new policy.
If you have "Not Enabled" engagement report, it will be not enabled in your new policy.

**Comment by KaiserAlex** [comment]
Hi Andres
thank you for your fast reply on this.

Actually, a customer who got a brand-new Tenant asked me as he wanted to change the Global (default) meeting policy and it (Engagement Reports) was activated.
In my Demo Tenants this setting was not present in the Admin Center a few weeks ago. Now it is present and activated in the Global Policy. Neither me nor my customer did activate Engagement Reports via PowerShell.
That´s why I wanted to give the feedback.

I mean if it is like it is, that is fine for me, but then please allow me the feedback, that the public documentation does not clearly state when it is activated and when deactivated.

This is an important thing in Germany as a workers council needs to be involved before doing things like Engagement Reports. This would bring some of my customers in discussion-trouble if they can´t clearly answer when it is activated and when not.

Best regards
Alex



 ***@***.***
Alexander Kaiser
CONSULTANT ▪ MODERN WORKPLACE ▪ MICROSOFT SERVICES
***@***.***> ▪ ***@***.***> ▪ CALL<tel:+49%20(89)%2031764388>

Microsoft Deutschland GmbH ▪ Walter-Gropius-Straße 5 ▪ 80807 München
Geschäftsführer*in: Dr. Marianne Janik (Vorsitzende), Thorsten Herrmann, Benjamin O. Orndorff, Keith Dolliver. Amtsgericht München, HRB 70438
﻿** Want to book an online Teams meeting with me? Please schedule it by using M365 Bookings with this link: https://aka.ms/meetAlexanderKaiser **

Upcoming Holidays: August 30th until September 10th


Von: Andres Mariano Gorzelany ***@***.***>
Gesendet: Dienstag, 24. August 2021 01:43
An: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Alexander Kaiser ***@***.***>; Mention ***@***.***>
Betreff: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Engagement report not "off" by default (#7735)


Hello @KaiserAlex<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKaiserAlex&data=04%7C01%7Calexander.kaiser%40microsoft.com%7C563222605378470c435408d9668faf3a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637653589598029644%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SmQLWJaTj79gXDhLUomSJDU1vDhYL8e5YNs4wF8rX6k%3D&reserved=0>
How are you?
Actually, the default of a new policy will depend on the current value of the Global policy at the moment you create the new policy.
If you have "Not Enabled" engagement report, it will be not enabled in your new policy.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SkypeForBusiness%2Fissues%2F7735%23issuecomment-904208995&data=04%7C01%7Calexander.kaiser%40microsoft.com%7C563222605378470c435408d9668faf3a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637653589598039602%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZV%2F0aCbZmqVoe85YVWrMrsGXIN4josYwXIWEe4JcWYY%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVKCGZ6YH5AO3B5PDZKC7DLT6LMGXANCNFSM5CUVUQWQ&data=04%7C01%7Calexander.kaiser%40microsoft.com%7C563222605378470c435408d9668faf3a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637653589598039602%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bVTdM%2BFlDdy39D2Ifb0bHfEBfDXUXxBJpkyM%2Fv1P%2BiM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Calexander.kaiser%40microsoft.com%7C563222605378470c435408d9668faf3a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637653589598049558%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gbJIlLUokXJlYRzxoURTtJAXJCdFapXZXU%2F7hrIlVtc%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Calexander.kaiser%40microsoft.com%7C563222605378470c435408d9668faf3a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637653589598049558%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pulSdnQHsNolYIcPdMIhqNGpFxw%2FzDuS4R1i7HeqKTQ%3D&reserved=0>.
