### ISSUE TITLE
How to follow the documentation

### ISSUE THREAD

**Issue by JohanssonMarkus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7736]
Hey, great feature but to be honest the documentation is not good enough to be able to follow for an implementation. 
Would it be possible to elaborate how to actually implement this? In Admin units I can only see those roles today

![image](https://user-images.githubusercontent.com/32453241/130462746-5a270d42-348e-42b3-8f91-69adc80c9701.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9a93a3-9abf-814a-909e-c6ab2575496b
* Version Independent ID: 3a1fcd15-d9d5-370b-9658-f95563c2d6f7
* Content: [Use administrative unit functionality in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/administrative-unit)
* Content Source: [Teams/administrative-unit.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/administrative-unit.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @JohanssonMarkus, thank you for your feedback.

You won't be able to see the Teams Device Administrator role when you create the Administrative Unit. As the article states, you have to use the [Add-AzureADMSScopedRoleMembership](https://docs.microsoft.com/powershell/module/azuread/add-azureadmsscopedrolemembership) cmdlet.

**Comment by JohanssonMarkus** [comment]
@dariomws The page your reference needs some attention. 
Works to assign $user, $Role and $Unit 
But below line fails (I'm using AzureAd 2.0.2.130)
$RoleMember = New-Object -TypeName Microsoft.Open.MSGraph.Model.MsRolememberinfo.RoleMemberInfo

![image](https://user-images.githubusercontent.com/32453241/131353904-f5cac1dc-f38e-448c-98a4-774a6a8b50a2.png)

**Comment by dariomws** [comment]
@JohanssonMarkus please try:
$RoleMember = New-Object -TypeName Microsoft.Open.MSGraph.Model.MsRolememberinfo

**Comment by JohanssonMarkus** [comment]
@dariomws 
Thanks that was better ;)

Found another issue in the docs though
This line give an error
$RoleMember.ObjectId = $user.ObjectId 

I do believe someone need to update the docs to
$RoleMember.Id = $user.ObjectId

As the $RoleMember doesn't have a ObjectID property at all. I assume it should be only "ID" 
![image](https://user-images.githubusercontent.com/32453241/131410653-35c7b3d1-b09c-419d-a187-e3ddfcaafac8.png)

**Comment by dariomws** [comment]
Hi @JohanssonMarkus, currently it's in that way:
![image](https://user-images.githubusercontent.com/33589238/131472451-4181f73e-c431-4bff-b7f2-0207a5af5516.png)

**Comment by JohanssonMarkus** [comment]
@dariomws Thanks for the update, however, When following the instruction still it will not work. When signing in to one of the users Teams admin center redirect to https://admin.teams.microsoft.com/invalidpath and you can't see any devices. 
Have you noticed this as well?

**Comment by dariomws** [comment]
@JohanssonMarkus my apologies but I cannot test that.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.
