### ISSUE TITLE
Barre d'application

### ISSUE THREAD

**Issue by tocri** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#774]
La barre d'application (ou system tray) est celle où est indiquée l'heure. 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 97d5e6d3-b7e0-d79f-0dea-ed423186a157
* Version Independent ID: ec6e68aa-552f-ab45-3c8e-92eff526b173
* Content: [Utiliser des fichiers journaux pour le dépannage de Microsoft Teams](https://docs.microsoft.com/fr-fr/microsoftteams/log-files)
* Content Source: [Teams/log-files.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.fr-FR/blob/live-sxs/Teams/log-files.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
Merci pour ce feedback

Je vais poser cette question à l'équipe Teams / Skype for Business pour enquête.

J'ai été en mesure de l'insérer dans le carnet de commandes de l'équipe Teams / Skype for Business. L'équipe aura cette priorité dans un plan de sprint. Merci d'avoir signalé et amélioré les documents. Très appréciée.
 
J'ai fait une note pour demander à l'équipe de le mettre à jour une fois le travail terminé.

**Comment by kenwith** [comment]
@tocri - sorry for the long delay. I am looking into this issue. Can you help me understand if this is a localization / translation issue or is it a problem with the source article? Here is the link to the source english article: https://docs.microsoft.com/en-us/microsoftteams/log-files

**Comment by get-itips** [comment]
Hi @tocri thanks for your comments, could yo please explain in more detail what is wrong with the documentation, thank you!

**Comment by tocri** [comment]
Hi,

Nothing wrong with the documentation. It’s only the french translation who is not perfect.

Anthony LEDUC-PASQUIER
Formateur Admin Rx & Systèmes
Responsable des certifications Microsoft AFPA Bretagne<http://certif22.maformationenligne.bzh/mod/page/view.php?id=54&forceview=1>
Formateur Microsoft Innovative Expert<https://education.microsoft.com/Status/Public?token=Kn1QSXx7>
www.linkedin.com/in/anthonyleduc<http://www.linkedin.com/in/anthonyleduc>

Centre de St-Brieuc | Côte d’Émeraude
Portable : 06.31.02.98.00
[cid:image005.png@01D3EC63.B5186A70][cid:image001.jpg@01D48122.D64CB710][cid:image007.png@01D3EC63.B5186A70]<http://www.linkedin.com/in/anthonyleduc>[cid:image008.png@01D3EC63.B5186A70]<http://www.linkedin.com/in/anthonyleduc>[cid:image009.png@01D3EC63.B5186A70]<http://www.linkedin.com/in/anthonyleduc>

________________________________
De : Andres Mariano Gorzelany <notifications@github.com>
Envoyé : Tuesday, February 26, 2019 5:26:22 PM
À : MicrosoftDocs/OfficeDocs-SkypeForBusiness
Cc : tocri; Mention
Objet : Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Barre d'application (#774)


Hi @tocri<https://github.com/tocri> thanks for your comments, could yo please explain in more detail what is wrong with the documentation, thank you!

**Comment by get-itips** [comment]
so it should say barre d'application instead of barre d'applications? thank you!

**Comment by tocri** [comment]
Section Desktop logs

In English, it says Right-click the Microsoft Teams icon in your application tray, select Get Logs

And in french it says

Cliquez-droit sur l’icône Microsoft équipes dans votre panneau d’applications, sélectionnez Get Logs

You should translate application tray by barre des tâches or zone de notification.

Anthony LEDUC-PASQUIER
Formateur Admin Rx & Systèmes
Responsable des certifications Microsoft AFPA Bretagne<http://certif22.maformationenligne.bzh/mod/page/view.php?id=54&forceview=1>
Formateur Microsoft Innovative Expert<https://education.microsoft.com/Status/Public?token=Kn1QSXx7>
www.linkedin.com/in/anthonyleduc<http://www.linkedin.com/in/anthonyleduc>

Centre de St-Brieuc | Côte d’Émeraude
Portable : 06.31.02.98.00
[cid:image005.png@01D3EC63.B5186A70][cid:image001.jpg@01D48122.D64CB710][cid:image007.png@01D3EC63.B5186A70]<http://www.linkedin.com/in/anthonyleduc>[cid:image008.png@01D3EC63.B5186A70]<http://www.linkedin.com/in/anthonyleduc>[cid:image009.png@01D3EC63.B5186A70]<http://www.linkedin.com/in/anthonyleduc>

________________________________
De : Andres Mariano Gorzelany <notifications@github.com>
Envoyé : Tuesday, February 26, 2019 10:26:19 PM
À : MicrosoftDocs/OfficeDocs-SkypeForBusiness
Cc : tocri; Mention
Objet : Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Barre d'application (#774)


so it should say barre d'application instead of barre d'applications? thank you!

**Comment by get-itips** [comment]
Thanks for the detailed explanation @tocri we'll take care and correct the translation.

**Comment by get-itips** [comment]
Please @OfficeGlobal I understand you handle the localization version of this article, can you correct it? Thank you!

**Comment by OfficeGlobal** [comment]
@samanthaw Working on a fix (BUG 3193674)

**Comment by OfficeGlobal** [comment]
@get-itips , @samanthaw The article has been HumanTranslated and published live

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and @samanthaw thanks for the translation. @tocri Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
