### ISSUE TITLE
Document update required

### ISSUE THREAD

**Issue by triniKMS** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7741]
The "Meeting Policy settings - General" section needs to be updated with;

- Allow engagement report
- Allow meeting registration
- Who can register

Regards,
triniKMS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Teams: Manage meeting policies - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams#feedback)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @triniKMS 

You can find those policies in the Set up Webinar article

https://docs.microsoft.com/en-us/microsoftteams/set-up-webinars

Will propose adding a link to it to the article.
