### ISSUE TITLE
Consider a clearer title

### ISSUE THREAD

**Issue by JasonSmith-MS** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7744]
Perhaps this title could be changed to "Geographic location of data in Microsoft Teams". I keep getting this mistaken result when searching for the storage applications for Teams data, as in SPO, EXO, OneDrive, Azure blob, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84f319aa-94de-bed1-2e5d-c6fe24436dac
* Version Independent ID: ee6daf32-7e03-801c-dd1b-50bf35e4635e
* Content: [Location of data in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/location-of-data-in-teams)
* Content Source: [Teams/location-of-data-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/location-of-data-in-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by lindspea** [comment]
@JasonSmith-MS thank you for reaching out and helping to improve MS Docs. For now the document title will remain as is but I will let the team know to consider changing the title in the near future for better clarity.
