### ISSUE TITLE
Calling Plan versus Direct Routing

### ISSUE THREAD

**Issue by johnkberry** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7745]
Does OnlineDialOutPolicy apply to both Calling Plans and Direct Routing?  Can the answer to this question be included in the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 305a21ef-6e99-3f0d-99a0-990489a93715
* Version Independent ID: 5edc67ee-0d68-50a3-fafd-f764d8762fa5
* Content: [Outbound call restrictions - Audio Conferencing & PSTN calls - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/outbound-calling-restriction-policies)
* Content Source: [Teams/outbound-calling-restriction-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/outbound-calling-restriction-policies.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by lindspea** [comment]
@johnkberry thank you for reaching out and helping improve MS Docs. Would it help if I add one of these articles to the document - https://docs.microsoft.com/MicrosoftTeams/direct-routing-plan, https://docs.microsoft.com/MicrosoftTeams/direct-routing-migrating or https://techcommunity.microsoft.com/t5/skype-for-business-it-pro/calling-plans-and-direct-routing-in-the-same-office-365-tenancy/m-p/281515

**Comment by johnkberry** [comment]
Hi @lindspea, I'm afraid that those links do not address the question of whether OnlineDialOutPolicy applies to Calling Plans, Direct Routing, or both.

**Comment by lindspea** [comment]
@tiburd please can you help?

**Comment by tiburd** [comment]
@tonysmit - Can you please let us know whether the **OnlineDialOutPolicy** applies to Calling Plans, Direct Routing, or both?

Thank you!

**Comment by scanum** [comment]
hi @tonysmit Hope you are well. Wanted to follow up here to see if there is an update? Please let us know if there is anything we can do to help. Thanks.

**Comment by scanum** [comment]
hi @tonysmit Hope you are well. Wanted to follow up here to see if there is an update? Please let us know if there is anything we can do to help. Thanks.

**Comment by scanum** [comment]
hi @tonysmit Hope you are well. Wanted to follow up here to see if there is an update? Please let us know if there is anything we can do to help. Thanks.

**Comment by scanum** [comment]
hi @tonysmit Hope you are well. Wanted to follow up here to see if there is an update? Please let us know if there is anything we can do to help. Thanks.

**Comment by scanum** [comment]
@CarolynRowe  Hope you are well. Wanted to follow up here to see if there is an update? Please let us know if there is anything we can do to help. Thanks.

**Comment by CarolynRowe** [comment]
The article listed is specific to Audio Conferencing, which does not require a Phone System license with either Calling Plan or Direct Routing as the PSTN option.
