### ISSUE TITLE
Update Native Chat Among Federated Orgs

### ISSUE THREAD

**Issue by BrianMcNeese** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7747]
Native chat with people in other orgs hasn't been limited to 1:1 chat for some time now. Need to update to reflect multi-party chat and expectations among multi-org chats as it relates to federation allow/block list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ac8f101-bdb5-2b55-d5f4-e070b70768d4
* Version Independent ID: 964d836e-d00b-b585-8f02-e03c5ec8dab9
* Content: [Native chat experience for external (federated) users in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/native-chat-for-external-users)
* Content Source: [Teams/native-chat-for-external-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/native-chat-for-external-users.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by lindspea** [comment]
@BrianMcNeese have you found any official document to confirm this that I could add to this article? Does this article help at all - https://docs.microsoft.com/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability? Do you recommend removing that sentence completely about 1:1 chats, or changing it?

**Comment by BrianMcNeese** [comment]
Hi @lindspea the only thing published by us that I have seen is the public roadmap item https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=51126 (Microsoft Teams: Chat with External Users in Group Chats). As for the additional context about how that works in mutli-org chats (think 3+ orgs), I think we need a feature PM or whoever owns this to provide official comment.

**Comment by lindspea** [comment]
@tiburd please can you assist?

**Comment by tiburd** [comment]
@MikePlumleyMSFT - Hi, you're listed as the author of [this article](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/native-chat-for-external-users.md) - are you able to help resolve this issue?

**Comment by MikePlumleyMSFT** [comment]
@lindspea @tiburd @BrianMcNeese  Given the high level scope of the article, I don't think we need to go into details around multi-org chats. If the 1:1 limitation is not longer true, let's just remove the reference.

**Comment by tiburd** [comment]
@BrianMcNeese - are you comfortable submitting a pull request that removes the reference?

**Comment by BrianMcNeese** [comment]
I could agree with @MikePlumleyMSFT given the context of the article; perhaps the details of multi-org chats belong elsewhere. @tiburd - yes I'll create a pull request removing the 1:1 chat reference.

**Comment by tiburd** [comment]
@BrianMcNeese - thank you! ...closing this issue.
