### ISSUE TITLE
Cannot toggle guest access

### ISSUE THREAD

**Issue by Kettenhund** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#775]
When attempting to toggle guest access for Teams "on", the toggle switch is grayed out. Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042d7ce6-ee22-690f-8188-ff8a4a585847
* Version Independent ID: 3e5bc99c-e08e-44e0-cda3-687ed3633175
* Content: [Turn on or off guest access to Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-guests)
* Content Source: [Teams/set-up-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-guests.md)
* Service: **msteams**
* GitHub Login: @laithalshamri
* Microsoft Alias: **laal**

**Comment by AndreaBarr** [comment]
@Kettenhund Thank you for this feedback

I want to make sure this guest access swiths gets addressed quickly for you. Support will be able to handle this issue to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by sweikelt** [comment]
same problem here - i opened a ticket (#: 11521432) and we are currently searching.
i also ran following script:
Import-Module SkypeOnlineConnector
$Cred = Get-Credential
$CSSession = New-CsOnlineSession -Credential $Cred
Import-PSSession -Session $CSSession
Set-CsTeamsClientConfiguration -AllowGuestUser $True -Identity Global

but this doesn't help - i'm not able to toggle the slider nor to invite guests

**Comment by Proxio** [comment]
I also have this problem. Can it be because it takes time before enabling guest access is provisioned?

**Comment by aflores29** [comment]
Same issue. I have enabled guest access everywhere else but this toggle still won't budge. I am running a hybrid environment should it work the same way?

**Comment by DarkwingDucker** [comment]
Same issue. Cannot toggle button the Guest button.

**Comment by loveunicom** [comment]
I can add guest.  So, would you pls give more detail steps?

**Comment by sweikelt** [comment]
> 
> 
> I can add guest. So, would you pls give more detail steps?

@loveunicom - sorry but i don't know what you mean - we can't toggle the switch to allow guest-access - that's the problem - and i think that's the reason why we can't invite guests, although i ran the powershell-script above.

i didn't receive a possible solutions from microsoft yet - when i get answer, i'll let you know

**Comment by loveunicom** [comment]
@sweikelt  I mean that there are three places that control the guest access, so which toggle  you can not switch?

**Comment by sweikelt** [comment]
edit: in the https://admin.teams.microsoft.com - portal the guest-access is activated, but i'm not able to  invite any external user
![grafik](https://user-images.githubusercontent.com/2639000/45999434-f2c60280-c0a5-11e8-97e0-8df78f201b6f.png)

**Comment by loveunicom** [comment]
@sweikelt How can I insert a pic here?

**Comment by loveunicom** [comment]
<img width="889" alt="screen shot 2018-09-25 at 16 34 16" src="https://user-images.githubusercontent.com/4775675/46002879-c62fdc00-c0e1-11e8-8c73-1929f5a30f38.png">
<img width="581" alt="screen shot 2018-09-25 at 16 34 41" src="https://user-images.githubusercontent.com/4775675/46002881-c62fdc00-c0e1-11e8-9bbf-60f07a4ba99a.png">
@sweikelt Please confirm the above two places setting first.

**Comment by sweikelt** [comment]
@loveunicom - that's pretty simple - in case that you have it in your clipbord, just use ctr+v.
if you have it on your drive, drag and drop or select them 
![grafik](https://user-images.githubusercontent.com/2639000/46003004-c9aa6f80-c0af-11e8-9180-f2e959717a15.png)

**Comment by sweikelt** [comment]
@loveunicom - roger - this permission is set to yes - i switch it now

**Comment by loveunicom** [comment]
@sweikelt  Addition:
The sharepoint setting:
<img width="1088" alt="screen shot 2018-09-25 at 13 39 56" src="https://user-images.githubusercontent.com/4775675/46003011-160ea300-c0e2-11e8-95b6-b568c974fe2f.png">

**Comment by sweikelt** [comment]
settings are set like yours, but i can't toggle the switch on.
let's wait some time, maybe it takes some time to be active.

PS: i don't like the setting in AzureAD ->Guest permissions are limited = set to "no" - it must work without setting this to "no" :-(

**Comment by loveunicom** [comment]
> settings are set like yours, but i can't toggle the switch on.
> let's wait some time, maybe it takes some time to be active.
> 
> PS: i don't like the setting in AzureAD ->Guest permissions are limited = set to "no" - it must work without setting this to "no" :-(

Yes, you're right.  Me too.

**Comment by loveunicom** [comment]
> settings are set like yours, but i can't toggle the switch on.
> let's wait some time, maybe it takes some time to be active.
> 
> PS: i don't like the setting in AzureAD ->Guest permissions are limited = set to "no" - it must work without setting this to "no" :-(

<img width="1161" alt="screen shot 2018-09-25 at 16 56 01" src="https://user-images.githubusercontent.com/4775675/46003819-f5474d00-c0e3-11e8-8188-478c98b0b404.png">
Please check this to see whether your powershell takes effect.

**Comment by loveunicom** [comment]
> @loveunicom - jep this is set to "on" too

Did you upgrade teams?
<img width="1191" alt="screen shot 2018-09-25 at 17 26 52" src="https://user-images.githubusercontent.com/4775675/46005619-3d686e80-c0e8-11e8-872e-264aa6a9d06f.png">

**Comment by loveunicom** [comment]
> @loveunicom - jep this is set to "on" too

<img width="1236" alt="screen shot 2018-09-25 at 17 28 12" src="https://user-images.githubusercontent.com/4775675/46005712-76a0de80-c0e8-11e8-8d9d-d8d5bcc4a8cb.png">

**Comment by sweikelt** [comment]
@loveunicom , this settings are also enabled. Microsoft is just working on it - but the last info i got yesterday - with the same questtions you asked :-P

**Comment by loveunicom** [comment]
> @loveunicom , this settings are also enabled. Microsoft is just working on it - but the last info i got yesterday - with the same questtions you asked :-P

My sub is OK.
<img width="961" alt="screen shot 2018-09-25 at 17 39 30" src="https://user-images.githubusercontent.com/4775675/46006446-2460bd00-c0ea-11e8-819a-eff783e715a5.png">
<img width="1087" alt="screen shot 2018-09-25 at 17 40 01" src="https://user-images.githubusercontent.com/4775675/46006448-24f95380-c0ea-11e8-83f0-e4b31cada83c.png">

**Comment by sweikelt** [comment]
another colleague of mine can toggle the switch on (he works in another company on an different o365-tenant).
i suspect, that he can toggle it on, because he bought o365 directly - we bought it through ingram.

**Comment by KarimEZ** [comment]
Same problem than @sweikelt, tried everything that @loveunicom mentioned (even if unlikely related), and still unable to toggle guest access for MS Teams :(

**Comment by sweikelt** [comment]
@KarimEZ - we now managed to toggle it on - but on a very suspicious way. 
i've informed microsoft about the way we did it and now exspect an answer if i may publish the workaround here.
pls stay tuned  👍

**Comment by sweikelt** [comment]
Update: Microsoft says, that this switch should not be used anymore *lol* and that's why, in some tenants it is deactivated - because they are already migrated to "teams and skype for business portal".
My workaround (scripting via browser - not kidding!) is not supported (of course - would be a shame if it would be supported). 
and again - we still don't got a working solution - maybe tomorrow with the help of the remote-help-god ^^

**Comment by KarimEZ** [comment]
Um, ok, thanks... so I currently don't have a solution to add guests to Teams:(

**Comment by AndreaBarr** [comment]
@KarimEZ Thank you for this feedback. 

I want to make sure this issue is documented and troubleshooted promptly. Please open a ticket with support so we can start figuring out what is going on with some of the rings for Teams. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by DarkwingDucker** [comment]
@sweikelt do you mind publishing your unsupported workaround? That would be more than what Microsoft is giving us. I have had a ticket open with them and all they do is keep sending me documents that I have already seen. I love that they are attempting to merge everything together but they should keep the old stuff working until the new stuff has been thoroughly tested.

**Comment by sweikelt** [comment]
@DarkwingDucker - yeah for sure - i wanted to wait till microsoft gives me the correct solution, but i think now, this will take some time o_O

so here is what we did (i used firefox):
Open office 365-admin-center and go to Settings -> Services and Add-Ins -> Microsoft Teams -> settings by user/license type 

-> now switch to Guest

here the funny-part beginns ^^
open the page inspector (https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector)
-> click on "Console" and fire this up:

`document.getElementById("EnableForSkypeTeams").disabled = false;`

than press save, reload the page to be sure, that the insertion was successful.
after the switch is on, wait some mins and than invite some guests in your team.

i thought - "this will never work" and after the trick was done - i fell off the chair because i could not believe it

**Comment by DarkwingDucker** [comment]
@sweikelt wow. I was like you. No way is this going to work, but Bam! It did, big kudos on this. Thanks!

**Comment by AndreaBarr** [comment]
Thank you all for the information and good discussion. Please let us know the resolution so that we can make sure to update the docs for it.

**Comment by KarimEZ** [comment]
Lol, thanks @sweikelt.
Saved my day.

**Comment by aflores29** [comment]
Thank you so much. Fixed a two day problem for me. For anyone that that types in the command and then presses save make sure you toggle the switch lol. The command, in my case, only enabled the switch to be toggled it does not change the setting. Thank you so much for this fix!

**Comment by AndreaBarr** [comment]
I'm glad you all have found a workaround while Support is working on this. I am closing again until we have word from support.

**Comment by Davidomir** [comment]
Any updates on this one here? 

I have the same issue :(

**Comment by KarimEZ** [comment]
Follow [sweikelt's answer](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/775#issuecomment-424409893). It's an improbable workaround, but it's working.

**Comment by Davidomir** [comment]
Okay, so, you click inspect- console and then just type his line and press enter? 

I did that in chrome and nothing happened, it just returned "false".. :/

**Comment by KarimEZ** [comment]
So use Firefox, as he suggested... 😑

**Comment by Davidomir** [comment]
> So use Firefox, as he suggested... 😑

![image](https://user-images.githubusercontent.com/29430789/48200232-c832bf00-e35e-11e8-9b41-d6dc53dc80fe.png)


Doesn't change a thing... :/

**Comment by sweikelt** [comment]
@Davidomir 
i just tried it again - works like a charm for me.
maybe your Syntax-Error causes this

**Comment by Davidomir** [comment]
Hmm okay... just to make sure.

I just copy paste it and press enter, right?

**Comment by sweikelt** [comment]
@Davidomir 
jep - just c&p and hit enter - maybe hit it a little bit harder ^^
in your posted screenshoot, i can see, that the command was correctly fired.
just be save and test all other suggested settings by microsoft

good luck!
viel erfolg!

**Comment by scanum** [comment]
@Kettenhund   - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
