### ISSUE TITLE
Not available in all tenants?

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#776]
How it is possible, or how we can be sure when this menu will be available in Teams Admin Center? In a lot of organizations, it is there, in most cases, it is not here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e412595-1a6e-8f12-dd7b-d268513632d3
* Version Independent ID: b7f1f24e-f21d-3258-ced9-67590fef9b45
* Content: [Configure the Skype Meetings App to work with Teams](https://docs.microsoft.com/en-us/microsoftteams/configure-skype-meetings-app-to-work-with-teams)
* Content Source: [Teams/configure-skype-meetings-app-to-work-with-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/configure-skype-meetings-app-to-work-with-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **Lolaj**

**Comment by AndreaBarr** [comment]
@Kazzan Thank you for this feedback

I agree we should be able to see if something is available to all tenants or not. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by kenwith** [comment]
@Kazzan - I was able to get in touch with product team and service engineers and there isn't a way right now to know which features have rolled out to which tenants. They let me know it is a known issue and they are working to figure out a better way to know if a feature has rolled out to a tenant that seeing it or not seeing it in the tenant.
