### ISSUE TITLE
Poor practise

### ISSUE THREAD

**Issue by jumpinf00l** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7761]
Please add instructions to manually download and install the pre-requisite Windows Updates. End users attempt this procedure without the pre-requisite Windows Updates and then have a terrible experience when it doesn't work because pre-requisites are missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4fa80cf-0319-c006-e886-4929a508b04c
* Version Independent ID: 9d598765-fc30-17f0-6594-57de81d8aa39
* Content: [Manually update a Microsoft Teams Rooms device - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/manual-update)
* Content Source: [Teams/rooms/manual-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/manual-update.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@jumpinf00l thank you for letting us know. Will adding this link to the article help at all - https://docs.microsoft.com/mem/configmgr/sum/plan-design/prerequisites-for-software-updates or is there a specific document with instructions you have in mind?

**Comment by jumpinf00l** [comment]
Hey @lindspea, I don't think that link will help since that article is more oriented toward WSUS, which isn't always applicable to these IOT devices. The article needs a step or a section marked as important which instructs to run Windows Update via the admin account between step 2 and step 3. For example:

**Step 3: Run Windows Updates**
[!NOTE] It's essential that Windows Updates are run after manually updating the Microsoft Teams Room app since the Microsoft Teams Room app might fail to launch if the required Windows Updates are not installed.

1. Switch to Admin Mode
2. Click the Start icon, type Windows Update, and click Open
3. Click Check for updates
4. If updates are found, click Install now

Ideally though, the script would run the Windows Updates without any user interaction to ensure that the essential updates are installed

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
