### ISSUE TITLE
please add license for Teams user, when user use voicemail

### ISSUE THREAD

**Issue by akkawamu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7763]
following the docs writes phone system include voicemail feature.

https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=small-business#what-features-can-i-get-with-add-on-licenses

but this docs writes "Note that a Phone System license is not required for Cloud Voicemail."

then Please add the license for Teams User, when the user uses voicemail service.
ex. O365 E1 user don't need the phone system license.

Thank you for your help
Best 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8228f9b2-a7de-abb4-6f41-70db0b3af155
* Version Independent ID: 8fd9fafb-dd76-59a8-e609-56f06d539a31
* Content: [Set up Cloud Voicemail - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-phone-system-voicemail)
* Content Source: [Teams/set-up-phone-system-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-phone-system-voicemail.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by lindspea** [comment]
@akkawamu thank you for reaching out. Please can you provide more clarification. Which document are you suggesting needs to be changed. Please have a look at this article and let me know if it provides more clarity regarding Cloud voicemail - https://docs.microsoft.com/skypeforbusiness/hybrid/plan-cloud-voicemail

**Comment by CarolynRowe** [comment]
This is the doc in question:  https://docs.microsoft.com/en-us/microsoftteams/set-up-phone-system-voicemail
Specifically, this wording:  "For Teams users, Cloud Voicemail is automatically set up and provisioned. Note that a Phone System license is not required for Cloud Voicemail."  This is accurate.  I believe the ask is to update the licensing doc to indicate that a Phone System license is not required for Cloud Voicemail.  This doc:  https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=small-business#what-features-can-i-get-with-add-on-licenses.

**Comment by akkawamu** [comment]
Hi Carolyn-san

Thank you for kind explanation. Our Partner ask us if the users have E1 and Phone system license and wants to use voicemail, they should buy Exchange online P2 or not. I can understand the user who has Phone system license don't need additional license. I know the common area phone user needs ExOP2 now, in future it doesn't need it. Is my understanding correct?

I really appreciate for your help.
Akihiro Kawamura
