### ISSUE TITLE
Whole article is wrong - written for S4B module which is deprecated

### ISSUE THREAD

**Issue by SB-MikeHalsey** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7768]
The whole Teams Direct Routing set of documentation is written for use with the Skype 4 Business module which has been deprecated.

We need this re-written using the MicrosoftTeams module and also need the cmdlet reference for the MicrosoftTeams module to be updated to list the replacements for such modules as   Set-CSUser    and  Set-CSOnlineVoiceUser  as these all seem to be missing from the cmdlets list.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb2a9717-6565-8443-8833-f7fdce562781
* Version Independent ID: db88c4d6-5864-a481-86cf-465feb452d75
* Content: [Enable users for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-enable-users)
* Content Source: [Teams/direct-routing-enable-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-enable-users.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@SB-MikeHalsey thank you for pointing this out and helping improve MS Docs. I'll contact the author to make sure the necessary updates are done.

**Comment by lindspea** [comment]
@SB-MikeHalsey I see the article has been updated. Please let me know if you need further assistance. Thanks again.
