### ISSUE TITLE
Meeting Transcription is available on menu

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7769]
Hi,

On the page: [Turn on or turn off recording transcription](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording#turn-on-or-turn-off-recording-transcription) you are writing:
"_This setting controls whether captions and transcription features are available during playback of meeting recordings._ "

Isn't that incorrectly? As this setting also defines if the "start transcription" is available on the meeting menu. So if this is disabled from the policy, then that disable also the menu option.

It would be so much better option if:
 Set-CsTeamsMeetingPolicy -AllowTranscription
Have options [**Enabled, Disabled, StartwithRecording**] instead just $true or $false.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording#turn-on-or-turn-off-recording-transcription)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Petri-X Thank you for reaching out and helping improve MS Docs. Are you suggesting having the wording changed in this article to be more user friendly. Please also see the note regarding transcription - That transcription for recorded meetings is currently only supported for users who have the language in Teams set to English and when English is spoken in the meeting. They are stored together with the meeting recordings in OneDrive for Business and SharePoint Online cloud storage.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
