### ISSUE TITLE
Invalid Set-UserPhoto command

### ISSUE THREAD

**Issue by janis-veinbergs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#777]
Parameters messed up a little bit. 

&gt; Set-UserPhoto -Identity "Ken Myer" -PictureData -Preview $photo -Confirm:$False
Must be 
&gt; Set-UserPhoto -Identity "Ken Myer" -PictureData $photo -Preview -Confirm:$False

---
#### Detalizēta informācija par dokumentu

⚠ *Nerediģējiet šo sadaļu. Tas ir nepieciešams vietnei docs.microsoft.com ➟ GitHub problēmu saistīšana.*

* ID: 66ad8b3a-aac0-7eba-29e3-2d621fa46a54
* Version Independent ID: bba6f915-d50e-08c2-cd54-a56d2c25198e
* Content: [Configure the use of high-resolution photos in Skype for Business Server](https://docs.microsoft.com/lv-lv/skypeforbusiness/deploy/integrate-with-exchange-server/high-resolution-photos)
* Content Source: [Skype/SfbServer/deploy/integrate-with-exchange-server/high-resolution-photos.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/integrate-with-exchange-server/high-resolution-photos.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by AndreaBarr** [comment]
@janis-veinbergs Thank you for this feedback

I will make sure this gets updated. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @janis-veinbergs we appreciate your comments and feedback, thanks.
example cmdlet has been corrected after you created this issue, thank you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @janis-veinbergs  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
