### ISSUE TITLE
Please reconcile both articles - A Calling Plan is required when a virtual; phone system license is assigned.

### ISSUE THREAD

**Issue by richardojel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7772]
[Enter feedback here]
Hello, Wondering how we can reconcile the fact that a calling Plan is not required when a Virtual Phone System license is assigned. yet in this article under pre-requisites on transferring a phone number to an external number, It is required
https://docs.microsoft.com/en-us/microsoftteams/plan-auto-attendant-call-queue#prerequisites.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6891495-01c6-117b-c28b-28232782ba74
* Version Independent ID: 1c23b35a-e9ba-ffdd-9baa-a3f83f4ed9ca
* Content: [Microsoft 365 Phone System – Virtual User licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/virtual-user)
* Content Source: [Teams/teams-add-on-licensing/virtual-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/virtual-user.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@scanum PR merged, please closed.
