### ISSUE TITLE
Is the "downstream SBC" mandatory for Local Media Optimization

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7775]
Hi,

On the page: [Local Media Optimization modes](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-media-optimization#local-media-optimization-modes) you are saying on the mode 1:
"_...the media will flow through the local **downstream SBC**’s internal IP address..._"

On the same page, just earlier is described the [Central SBC](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-media-optimization#central-sbc-with-centralized-trunks).

Question; Because the "**mode 1**" speaks only about **downstream SBC**, then is this not supported on **Central SBC** solution? Or should the text be:
"_...the media will flow through the local **downstream SBC**’s **or central SBC's** internal IP address..._"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbab466f-88f8-302a-7cda-d53bc743e831
* Version Independent ID: b5634fb3-6627-3fcd-101c-0ebc419d7b19
* Content: [Local Media Optimization for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-media-optimization)
* Content Source: [Teams/direct-routing-media-optimization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-media-optimization.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Petri-X, thank you for your feedback.

It seems ok for me. Modes apply only when you are using the Central SBC with Proxy SBCs. If you have a Central SBC only topology with local media optimization, media will flow always between the client and the internal IP of the Central SBC, since it is the only one.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Petri-X** [comment]
Sorry about the delay, but the problem is the line: "_Local Media Optimization supports two modes:_" and under that there are no comments about the centralized SBC, only "local downstream SBC". 

I know, it is pretty much philosopher discussion, as earlier on the same page [Central SBC with centralized trunksCentral SBC with centralized trunks](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-media-optimization#central-sbc-with-centralized-trunks) you have a statement;
"_When a user is in the internal network of the company, the SBC provides the internal IP of the SBC for media._"
which support your statement very well.

As I end up to discussing around this topic on the technical table, and when the centralizes SBC is not mentioned on the LMO's supported model list it lets some doors open. That is the reason asking small addon to it:
"...the media will flow through the local downstream SBC’s **or central SBC's** internal IP address..."

CU  _o/

**Comment by dariomws** [comment]
Modes (`Always bypass` and `Only for local users`) apply only when you are using the Central SBC with Proxy SBCs. If you have a Central SBC only topology with local media optimization, media will flow always between the client and the internal IP of the Central SBC, since it is the only one.
