### ISSUE TITLE
Planner not automatically created

### ISSUE THREAD

**Issue by LaurieKamp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7777]
This page - wording and diagram seems to indicate that when a group is created, a Planner is also created.  I don’t believe that is true.  Creating a Planner for a Group is optional.  You have to manually go in and create it - either manually in Planner and attach it to the group - or by clicking Planner next to the group in the web version of Outlook. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d86301b-ce9c-388c-e563-9e5e5c27132e
* Version Independent ID: 07e4ae23-0966-e8f3-9b7c-4f6c02569eb0
* Content: [Microsoft 365 Groups and Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/office-365-groups)
* Content Source: [Teams/Office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-groups.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @LaurieKamp Laurie, how are you? Hope you are doing good.
I could verify what you say here, I'll propose an improvement to the article.
Thank you

**Comment by get-itips** [comment]
@scanum please close. thanks
