### ISSUE TITLE
Cannot build Teams Room PC, disk is formatted for GPT

### ISSUE THREAD

**Issue by CTNAGZ** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7778]
1st off, in regards to which version of Windows 10 ISO to use, the documentation for this build is horrible. We use OEM versions of Windows. I am trying to build a Teams Room PC. referencing this link, https://docs.microsoft.com/en-us/microsoftteams/rooms/console . I ran the PS script, I choose OEM and could never get an ISO to work, so I re-ran the PS script and choose Enterprise, the script was able to finish using this ISO, SW_DVD9_Win_Pro_10_20H2.1_64BIT_English_Pro_Ent_EDU_N_MLF_-2_X22-43918. When I boot from the freshly created USB stick, I keep getting an error that my HDD is formatted for GPT. I have tried booting both UEFI and Legacy. I have tried using DISKPART to reformat the internal HDD to MBR. I have loaded Windows 7 and booted the PC, then tried to boot the USB installer again, same error. I think it relates to the ISO that was used. Any help would be approeciated.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by CTNAGZ** [comment]
Thanks. I ended up copying setup.exe from my known good Win 10 Pro USB (Win 10 Pro, 20H2) stick and overwrote setup.exe on the stick that the script built.
