### ISSUE TITLE
Teams Rooms media Creation Failure

### ISSUE THREAD

**Issue by ckapsiak** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7779]
This appears to be a common issue, but again Teams room createsrsmedia.ps1 script is asking for a version of Windows that is unable to be downloaded from VLSC. The version it is asking for is 19041.631, please update this

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by ckapsiak** [comment]
Microsoft support wasn't any help they just advised to get that specific version and that they don't control the script to update it. I just manually edited the script to accept the version I was supplying to proceed.
