### ISSUE TITLE
Common Area Phone document is outdated

### ISSUE THREAD

**Issue by lmon1103** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7784]
[The article about CAP is quite poor as it doesn't explain most of the things you need to setup to control the device, like the IP Phone Policy, there are some external articles that explain everything quite well, like this one from Jeff Schertz or this one from Jeff Brown.
If you want to use Direct Routing with the CAP, you need to assign a telephone number to the CAP user as described on the section Enable Users of the Configure Direct Routing article, with the exception of the Voicemail as CAP don't use Voicemail (do not include "-HostedVoiceMail $true"). Also you need to assign a Voice Routing Policy to the user as described on the Configure voice routing section of the previous article. In this external article you can also see an example.
 
I think we should create an Insight requesting a detailed article about how to set up CAP devices and the configuration to use them with Direct Routing]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ab5215-f24f-75cf-bb92-16ac0ff5e5ca
* Version Independent ID: 701cc58f-d2ea-cbb6-f5fc-47b9fbfb1119
* Content: [Set up the Common Area Phone license - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-common-area-phones)
* Content Source: [Teams/set-up-common-area-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-common-area-phones.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@lmon1103 thank you for pointing this out. I found a document relating to this. Please let me know if it helps at all and I can have a link added to this article to help other users - https://docs.microsoft.com/microsoftteams/direct-routing-plan#supported-end-points

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
