### ISSUE TITLE
Log files location on Windows

### ISSUE THREAD

**Issue by francisco-lafe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7788]
Hello, it may be obvious for some people, but for me it isn't, I see that you gave the path for "Linux" logfiles, but there's no information for windows, in any of the three categories.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d5e6d3-b7e0-d79f-0dea-ed423186a157
* Version Independent ID: ec6e68aa-552f-ab45-3c8e-92eff526b173
* Content: [Use log files in troubleshooting Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/log-files?WT.mc_id=365AdminCSH_SupportCentral#debug-logs)
* Content Source: [Teams/log-files.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/log-files.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback, created a PR to propose clarifying that.

**Comment by francisco-lafe** [comment]
Just a picture like this:
![image](https://user-images.githubusercontent.com/90066435/134051947-da626a68-0e68-42ab-ab39-f91d65edf61f.png)
Would suffice.
It's a non-traditional way of looking for logs when you have been working with text-files for so long.
