### ISSUE TITLE
Link to "Check Stream classic migration for more information" is broken

### ISSUE THREAD

**Issue by JamesGMorrison** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7790]
[Enter feedback here]
 Link to https://docs.microsoft.com/en-us/stream/streamnew/classic-migration is broken in the FAQs paragraph: _"If you plan on deprecating adding to Stream, will existing videos stay as is and for how long?
Stream as a platform won't be deprecated in the near future. The videos that currently live in Stream will stay there until we start migrating. Upon migration, those videos will be migrated to OneDrive for Business or SharePoint as well. Check Stream classic migration for more information"_ 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8935e913-806f-a92c-d09e-e67df4ffd1b4
* Version Independent ID: c7a41cde-66dd-d7cd-1316-42d20ed4841a
* Content: [Use OneDrive for Business and SharePoint for meeting recordings - Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/tmr-meeting-recording-change#frequently-asked-questions)
* Content Source: [Teams/tmr-meeting-recording-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tmr-meeting-recording-change.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@JamesGMorrison thank you for pointing this out. Would this be the correct article to link here - https://docs.microsoft.com/stream/streamnew/migration-details
