### ISSUE TITLE
Possible issue on this DOC

### ISSUE THREAD

**Issue by ancru** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7791]
Hi TEAM. It's my first contribution. Hope I can help.

I think there's an issue with this DOC. In pt-br is different from en-us
![image](https://user-images.githubusercontent.com/84449540/132248616-193f216a-819f-4c03-a789-abc70202df8b.png)

In pt-br says:
https://docs.microsoft.com/pt-br/microsoftteams/cloud-recording
<html>
<body>

Cenário | Etapas
-- | --
Quero que todos os usuários da empresa possam transcrever ao iniciar a gravação de uma reunião. | Confirme que CsTeamsMeetingPolicy global tem AllowTranscription = verdadeiro.Todos os usuários têm as CsTeamsMeetingPolicy globais ou uma das políticas de CsTeamsMeetingPolicy com **AllowCloudTranscription** = verdadeiro.

</body>
</html>

And in en-us says:
https://docs.microsoft.com/en-us/microsoftteams/cloud-recording
<html>
<body>

Scenario | Steps
-- | --
I want all users in my company to be able to transcribe when initiating recording of a meeting. | Confirm Global CsTeamsMeetingPolicy has AllowTranscription = True.All users have the Global csTeamsMeetingPolicy OR one of the CsTeamsMeetingPolicy policies with **AllowTranscription** = True.

</body>
</html>

And also I think in both cases they want to say: **AllowCloudRecording = True**
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@OfficeGlobal Could you kindly help with this issue?

**Comment by cdowling1971** [comment]
@ancru Thanks for reporting this problem, we have logged a case/ticket to follow up internally.

**Comment by tiburd** [comment]
@scanum
