### ISSUE TITLE
Misspelling in the Set up Microsoft 365 Business Voice video reference

### ISSUE THREAD

**Issue by GoCloudTeam** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7796]
[Enter feedback here]

At time stamp 00:34 the word Auto-Attendant is spelled incorrectly as Auto-attendent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb7f510-e38e-af0b-af91-af953322e8bb
* Version Independent ID: faaee029-081e-038e-c3ca-2544e3368378
* Content: [Set up Microsoft 365 Business Voice - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/business-voice/set-up-overview)
* Content Source: [Teams/business-voice/set-up-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/business-voice/set-up-overview.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@GoCloudTeam thank you for pointing this out and helping improve MS Docs. @tiburd please can you direct this to the author as this typo is in the actual video content and we don't have those editing permissions. Thank you.

**Comment by tiburd** [comment]
@dstrome - Hi, this issue is regarding a typo in the video included in [this article](https://docs.microsoft.com/en-us/microsoftteams/business-voice/set-up-overview). Can you please help resolve and close this issue?

**Comment by tiburd** [comment]
@GoCloudTeam - thank you for bringing this to our attention - it has been corrected, so we're closing this issue.
