### ISSUE TITLE
"Share a chat file" - mark as possible

### ISSUE THREAD

**Issue by ChristianJBergstrom** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7799]
[Hi, as an example. If your org. only has federation (external access) enabled but another org. add you as a guest the table says that you cannot share a chat file as a guest user. You can actually. If you in a chat select the attachment icon BEFORE entering the other org. user in the to: field and set the attachment permission to "Specific user" the ad-hoc external sharing OneDrive/SharePoint file process with OTP will take over and the user in the chat in the org. with guest access enabled will be able to see the attachment (after providing the verification code). If the sending part would change their config and enable guest access and SharePoint and OneDrive AAD B2B integration (instead of legacy ad-hoc external SharePoint sharing) then the process would be similar with the main difference that when entering the OTP the receiving user would end up as a guest user in the sending org. AAD, hence both now being guest users in each others org.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [Guest experience in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-experience)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @ChristianJBergstrom, thank you for your feedback.

I've tested it and I cannot attach a file as guest user.

The following picture shows the user inside my organization, he/she has the button to attach a file:
![image](https://user-images.githubusercontent.com/33589238/132496148-4c7cfa4a-9c45-4615-85e4-92cf3b8e62b0.png)

The following picture shows the guest user, he/she doesn't have the button to attach a file:
![image](https://user-images.githubusercontent.com/33589238/132496243-3a5b40ed-06f1-4fb6-aa11-30f3327c8a73.png)

**Comment by ChristianJBergstrom** [comment]
I know, that's why you have to (as mentioned in my first post) use the attach icon - before - adding the other part.

**Comment by dariomws** [comment]
In that case, you are sharing the files as an external user, not as a guest user.

**Comment by ChristianJBergstrom** [comment]
While that is true you can still share from the chat perspective so it becomes sort of a technicality then. Either way, I had a look at this table too https://docs.microsoft.com/en-us/microsoftteams/communicate-with-users-from-other-organizations#things-your-users-can-do and that should at least be updated then. I.e. If using the ad-hoc external SharePoint sharing (or AADB2B integration) it will work. You decide, thanks for the very quick replies!

**Comment by dariomws** [comment]
That other table is not talking about the chat. I'm not convinced to add some clarification as the table is talking about the native share file experience in a chat window.

**Comment by ChristianJBergstrom** [comment]
OK, then we'll leave the "share file as guest" part. You say the other table is not talking about the chat, I know :) You can still use ad-hoc external sharing or AADB2B sharing files as an external user/federated user so that table is at least incorrect from my point of view.

**Comment by dariomws** [comment]
I can propose an update saying that I do not agree and need a second opinion. The update will be reviewed for approval before posting.
Does it work for you?
Are you suggesting adding a checkmark on "Share a chat file" for the guest column?

**Comment by ChristianJBergstrom** [comment]
No, I'm not suggesting that. I'm actually fine with leaving the "Share a chat file" for guests (even though it can be done). What I instead now suggest is that this table [https://docs.microsoft.com/en-us/microsoftteams/communicate-with-users-from-other-organizations#things-your-users-can-do](url) is changed for "Share files" under External access users to Yes.

**Comment by dariomws** [comment]
Sorry but it's confusing. I'm double-checking and I don't have the Attach icon/button/clip beneath the box you type a message to share files when I'm chatting with an external account neither guest.

**Comment by ChristianJBergstrom** [comment]
I know, file collaboration is a mess :) That's correct, you have to attach the file before adding the other user in the To: field. That's the only way it can be done in a chat. Also, Teams is buggy so the sent file will only open properly when selecting ... "Open in browser".

When it comes to external sharing in general you're always good to go using the "secure link" meaning "Specific people" so that's why I suggest that the info in the attached link needs to be changed for external access users. https://docs.microsoft.com/en-us/microsoftteams/communicate-with-users-from-other-organizations#things-your-users-can-do

**Comment by dariomws** [comment]
> I know, file collaboration is a mess :) That's correct, you have to attach the file before adding the other user in the To: field. That's the only way it can be done in a chat. Also, Teams is buggy so the sent file will only open properly when selecting ... "Open in browser".

Ok, I've verified and you have the attachment icon when you select "new chat". It's some kind of workaround but I cannot add yes to the table. My apologies.

**Comment by ChristianJBergstrom** [comment]
No worries, but again, I'm not suggesting that. We are not discussing share a file as guest anymore. As you can share files as an external access user this table is incorrect https://docs.microsoft.com/en-us/microsoftteams/communicate-with-users-from-other-organizations#things-your-users-can-do

**Comment by dariomws** [comment]
But if you are chatting with an external user the attach icon is not there. You can share a link to a file maybe, or use this workaround you found. But there is no icon or native way to share a file.

**Comment by ChristianJBergstrom** [comment]
True, but think outside of the chat now. That's why the table is incorrect.

**Comment by dariomws** [comment]
I have to apologize but I can't agree with what you suggest so I can't create a pull request to apply this change. As an MVP I see that you contribute to docs.microsoft.com frequently, and if you are very sure of this you can apply the change directly to see if it is approved.

**Comment by ChristianJBergstrom** [comment]
No worries again, it's nice to elaborate and hear how others see things. I agree that the information needs to be correct with native sharing in a chat window. But I do think that the article/s should be updated so they are very clear of what is possible or not. So while leaving the "Share a file as guest" untouched (as it is). The "Share a file" (as an external user) really should be updated as it's not clear now saying "Things your users can do". From where? It should say, "Share a file in a chat".

**Comment by dariomws** [comment]
Again my apologies, but the table looks good for me.

**Comment by ChristianJBergstrom** [comment]
Just add ”Share a file in a chat” or ”Share a file in Teams” instead of simply ”Share a file” for the external users.
