### ISSUE TITLE
Deploying Android-based Teams Phones without enrolling in Intune

### ISSUE THREAD

**Issue by ronaldsanjoseLDC** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7803]
Is there are supported way to deploy Android-based Teams Phone without forcing it to enroll in Intune?
We tested a few Native Teams Phone and are getting different results.

We were able to get 2 AudioCodes Teams IP Phone Models and 1 Polycom Teams IP Phone Model to work by using something similar to the Microsoft EMS MAM WE that we use for our BYOD Android devies.

We were only able to get 1 AudioCodes Teams IP  Phone Model to work if they are enrolled in Intune (MDM) as described in the article.

Thank you.

Ron

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 407c4f68-9737-d86c-2a08-cbbeaef6da00
* Version Independent ID: 3324088c-b0b2-dec3-575d-c1fb76bfb730
* Content: [Deploy Teams phones, Teams displays, and Microsoft Teams Rooms on Android using Intune - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/phones-displays-deploy)
* Content Source: [Teams/devices/phones-displays-deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/phones-displays-deploy.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
