### ISSUE TITLE
RFC1918 addresses should not be used as example IP addresses, use example ranges in RFC5737

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7804]
This is a re-open of #4450, and the updated articled does not address the mis-use of the private IP addresses.

This article shows RFC1918 private, non-routable IP addresses as the Trusted IPs (172.16.x.x in this diagram). By definition, these addresses will NEVER be routed over the internet, they are for private, internal use only. 

Please use RFC 5737 https://tools.ietf.org/html/rfc5737 address ranges instead.
The blocks 192.0.2.0/24 (TEST-NET-1), 198.51.100.0/24 (TEST-NET-2),
and 203.0.113.0/24 (TEST-NET-3) are provided for use in
documentation.

This will help eliminate confusion as people see the RFC1918 ranges of 10.0.0.0 to 10.255.255.255, 172.16.0.0 to 172.31.255.255, and 192.168.0.0 to 192.168.255.255 and understand those to mean private, internal addresses and not example external addresses.

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
