### ISSUE TITLE
This page needs a refresh. The OST no longer exists.

### ISSUE THREAD

**Issue by stbyer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7805]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0e0f68-d088-d0b7-cbb7-56bb16e4026f
* Version Independent ID: 8a107028-31a6-6821-a150-1ebdd7a7d440
* Content: [Microsoft Teams Privacy - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-privacy)
* Content Source: [Teams/teams-privacy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-privacy.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@stbyer thank you for pointing this out and helping improve MS Docs. I see the article was just updated 2-3 days ago, and the OST link redirects to the Licensing resources and documents page. Please let me know if you need further assistance.
