### ISSUE TITLE
Unable to promote user in private channel to owner

### ISSUE THREAD

**Issue by d3spwn** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7807]
version 2.4.1-preview

1. adding a user to a private channel works:
Add-TeamChannelUser -GroupId $groupid -DisplayName $Channels.DisplayName -User username

Get-TeamChannelUser -GroupId $groupid -DisplayName $Channels.DisplayName
UserId                               User                                       Name            Role  
c4ffdb3c-06f3-4350-a627-b7b456175a9d username Member

2. promoting the newly added user to owner doesn't work:
Add-TeamChannelUser -GroupId $groupid -DisplayName $Channels.DisplayName -User username -Role Owner
Add-TeamChannelUser : Error occurred while executing 
Code: BadRequest
Message: Invalid OData type specified: "Microsoft.Teams.Core.aadUserConversationMember"
InnerError:
  RequestId: b7e56d76-92b3-444a-8d46-45c3cd55ae71
  DateTimeStamp: 2021-09-10T09:00:46
HttpStatusCode: BadRequest
At line:1 char:2
+  Add-TeamChannelUser -GroupId $groupid -DisplayName $Channels[0].Disp ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-TeamChannelUser], ApiException
    + FullyQualifiedErrorId : Microsoft.Teams.PowerShell.TeamsCmdlets.ErrorHandling.ApiException,Microsoft.Teams.PowerShell.TeamsCmdlets.AddTeamChannelUser

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
