### ISSUE TITLE
Outdated connection Stream recording storage -> OD4B

### ISSUE THREAD

**Issue by impact0815** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7808]
The architecture presentation is amazing - but slightly outdated right now. (the pdf has a modified time stamp from 4/12/2019)

Esp. the connection between Microsoft Stream and the storage of the recordings is incorrect today and should be updated to the current status and point to OneDrive for Business.

Thanks!

Cheers
Stephanus (sschulte@microsoft.com) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ad624-9792-91b7-c85f-09b839b1ea44
* Version Independent ID: e8288f91-11bd-599b-8a88-074917b315a4
* Content: [Microsoft Teams IT architecture and voice solutions posters - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-architecture-solutions-posters?source=docs#feedback)
* Content Source: [Teams/teams-architecture-solutions-posters.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-architecture-solutions-posters.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @impact0815, thank you for your feedback.

This issue is similar to:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7565

@cichur @LolaJacobsen @CarolynRowe, Do you think we can update this poster? Thanks!

**Comment by impact0815** [comment]
Hi,

maybe you can make use of the attached slides.
If you have questions feel free to reach out to me!

Cheers

Stephanus

**Comment by dariomws** [comment]
@impact0815, sorry, What did you mean? I cannot edit the posters.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
