### ISSUE TITLE
10,000 or 11,000?

### ISSUE THREAD

**Issue by GitRomney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7810]
The wording on this page is unclear. Is the total number of attendees 10,000 (20,000 during COVID), **including** the initial 1,000, or is the total number 11,000, with 1,000 full experience attendees and an additional 10,000 view-only attendees?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bf705c2-1f24-bdb5-e712-e8408b941aca
* Version Independent ID: ddedd7e0-7d85-06e0-7f20-8b83b3dccec7
* Content: [View-only meeting experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/view-only-meeting-experience)
* Content Source: [Teams/view-only-meeting-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/view-only-meeting-experience.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@GitRomney good question. Thank you for reaching out. I'm checking with the team and will let you know asap.

**Comment by lindspea** [comment]
@GitRomney I see the article has been updated with more information. Please let me know if you need help with anything else. Thanks again.

**Comment by GitRomney** [comment]
Good morning. The language on the page is now contradictory.

First it says, "If your meeting hits capacity, Teams will seamlessly scale to accommodate a 10,000-person view-only broadcast experience." This seems to indicate that the view-only broadcast accomodates 10,000 people above the 1,000 full participation people, for a total of 11,000.

However the very next section says, "Microsoft Teams allows up to 10,000 attendees to join a Teams meeting." This seems to indicate that the total number of people who can join is 10,000, meaning 1,000 full participants plus 9,000 view only.

I'm sorry to be a pain but I think this article still needs to be clarified.

Thanks again,
Joel

**Comment by lindspea** [comment]
@scanum please can you check with the author? Thanks.

**Comment by lindspea** [comment]
@GitRomney it seems the wording might have been updated in the interim. Please can you confirm so we can close the issue. Thanks so much.

**Comment by GitRomney** [comment]
I don't think the language has been updated. The confusion is whether the total meeting attendance is 10,000 (including 1,000 with full experience and 9,000 with view-only) or 11,000 (with 1,000 with full experience and 10,000 with view-only).

In one section of the page it says, "Microsoft Teams allows up to 10,000 attendees to join a Teams meeting." This sounds like 1,000 full and 9,000 view-only, since 10,000 is the limit. But above this in the Note, it says "...Teams will seamlessly scale to accommodate a 10,000-person **view-only** broadcast experience." (my emphasis added) So that part sounds like the view-only participant limit is 10,000 after the 1,000 full experience attendees are joined.
