### ISSUE TITLE
Missing role

### ISSUE THREAD

**Issue by RascoPK** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7812]
There is a role missing called Teams Device Administrator, in the table

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c807f882-de3c-9c30-f92f-43769356f015
* Version Independent ID: 7658a338-51a0-196a-ce53-2a213a5f0dc6
* Content: [Plan for lifecycle management - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/plan-teams-lifecycle)
* Content Source: [Teams/plan-teams-lifecycle.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-teams-lifecycle.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
