### ISSUE TITLE
Baisse de qualité des traductions

### ISSUE THREAD

**Issue by SabRom** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7814]
Bonjour,

Ce retour ne concerne pas uniquement cette page, mais l'ensemble des dernières docs Microsoft.

Qu'est-ce qu'il se passe avec vos traductions Françaises ?

Il y a encore quelques années, les traductions étaient de bonne qualité. Maintenant ? C'est juste honteux ! c'est mauvais, indigne de Microsoft. Est-ce que vous traduisez tout ça à l'aide de Bing ? par pitié, embauchez des traducteurs !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09168b55-8244-974e-8bb3-6ec16429a650
* Version Independent ID: c17f4f8d-a8bb-3c81-368f-07b932f52ebc
* Content: [Advanced Communications add-on for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/advanced-communications#feedback)
* Content Source: [Teams/teams-add-on-licensing/advanced-communications.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/advanced-communications.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@SabRom Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
@Officeglobal @TinaMcN Hope you are well. Could you please help with this issue? Thanks.

**Comment by TinaMcN** [comment]
Bonjour @SabRom 

Je suis désolé d’apprendre que la qualité de traduction de la documentation vous pose des problèmes.  Nous effectuons un mélange de traduction humaine et automatique pour le contenu docs.microsoft.com.   Pouvez-vous fournir des exemples spécifiques d’articles comportant des exemples problématiques ?  Je peux organiser la traduction humaine de certains d’entre eux.   Si vous avez des exemples de texte spécifique traduit correctement, cela sera également utile.

Cordialement,
Tina
(I'm sorry to hear that the translation quality of the documentation is causing you problems.  We do a mixture of human and machine translation for the docs.microsoft.com content.   Can you provide specific examples of articles that have problematic examples?  I can arrange for some of them to be human translated.   If you have any examples of specific text that is translated correctly that will be helpful also.)
