### ISSUE TITLE
Wrong room images?

### ISSUE THREAD

**Issue by nachapman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7816]
[Enter feedback here]
The medium and large size room images are the same??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e16a13-c655-a78d-cdf5-8395bcfe54d6
* Version Independent ID: f06b064f-a9f2-8ed7-48f7-8d4e21934e6a
* Content: [Meeting room guidance for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-meeting-room-guidance)
* Content Source: [Teams/teams-meeting-room-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-meeting-room-guidance.md)
* Service: **msteams**
* GitHub Login: @amandafrechinjackson
* Microsoft Alias: **v-amandaf**

**Comment by amandafrechinjackson** [comment]
We don't have another room render available, which is why that one is duplicated. However, the room look/function is essentially exactly the same for both; there would just be a difference in size.

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
@scanum this issue was answered by @amandafrechinjackson.
