### ISSUE TITLE
Supported Linux distributions lists "Fedora 30 Workstation" in supported linux distributions.  F30 is EOL

### ISSUE THREAD

**Issue by kevenwyld** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7818]
As the title states, Fedora 30 Workstation is listed under supported Linux distributions on [this page](https://docs.microsoft.com/en-us/microsoftteams/hardware-requirements-for-the-teams-app#hardware-requirements-for-teams-on-linux) .  Unfortunately Fedora's release schedule moves very quickly and this version is now quite old.  It was EOL on 2020-05-26 .  The current version is F34 .  The page should be updated to reflect a supported version of Fedora.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29a61ff5-b3a5-158d-149a-dec344060e05
* Version Independent ID: 97fac351-a283-aaa8-cde1-fbd9cf4e8504
* Content: [Hardware requirements for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/hardware-requirements-for-the-teams-app#hardware-requirements-for-teams-on-linux)
* Content Source: [Teams/hardware-requirements-for-the-teams-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hardware-requirements-for-the-teams-app.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by kevenwyld** [comment]
Our org received clarification from MS Teams support on this.  Apparently teams is "not tested" on releases later than 30 so they are "not supported".  This is very bad practice.  EOL versions of any OS are unsafe and insecure.  It would be equivalent to asking someone to continue using Windows 7 without support because an application has not been updated to work on Windows 10.  See [here](https://fedoraproject.org/wiki/End_of_life) for the Fedora release schedule and EOL information.

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
I have been notified that Linux documentation will be refreshed soon.
