### ISSUE TITLE
Manage org-wide app settings for Microsoft 365 Government

### ISSUE THREAD

**Issue by RascoPK** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7819]
Manage org-wide app settings for Microsoft 365 Government

please review this steps
There is no "Org-wide app settings" in "Permissions policy"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b51eda6c-168c-7d99-7cc1-992b3d8feef2
* Version Independent ID: 118a1b8f-f4b7-a778-70b1-d3161fc548ab
* Content: [Manage app permission policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-app-permission-policies)
* Content Source: [Teams/teams-app-permission-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-permission-policies.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @RascoPK how are you?
Can you kindly confirm if you instead find `Org-wide app settings` going to `Teams Apps` - `Manage Apps` in your tenant?
Thanks

**Comment by RascoPK** [comment]
Sorry, I cant find it now. When I was looking at this in the first time I was able to see this bug.
Sorry for confusion.
