### ISSUE TITLE
Intune app configurations

### ISSUE THREAD

**Issue by nickp85** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7820]
Does the Microsoft Lists iOS app support Intune App Protection and the Intune App Configuration keys for connected experiences and required UPN to properly identify/segregate work/personal accounts? Can you update this article to mention managing Lists for iOS through Intune?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac12129f-4d94-cbbd-4c34-03666617c889
* Version Independent ID: 015463d6-8fb9-7240-a3f1-8ae288dd9e90
* Content: [Manage the Lists app for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-lists-app)
* Content Source: [Teams/manage-lists-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-lists-app.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @nickp85, thank you for your feedback.

You can find this information here:
https://techcommunity.microsoft.com/t5/intune-customer-success/support-tip-how-to-enable-intune-app-protection-policies-app/ba-p/2100061
