### ISSUE TITLE
License requirements for webinars.

### ISSUE THREAD

**Issue by dipinn26592** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7821]
We should call out license requirements to use the webinars. 

Specifically we should call out SharePoint license is needed for a user to schedule webinars. While there is a mention about "Microsoft Lists need to be set up in SharePoint". Most customers wont link it to the SharePoint license.

We have a lot of customers who do not use OSDP and use teams for chat and calling. and unable to schedule a webinar will be a big NoNo for them 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2fe730-a95d-d12d-adb8-49d1397c77c7
* Version Independent ID: 1f6077c3-6114-cb5e-8b1a-7587188f2cdf
* Content: [Set up for webinars in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-webinars)
* Content Source: [Teams/set-up-webinars.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-webinars.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @dipinn26592, thank you for your feedback.

While we appreciate your feedback and encourage you to do the same in the future, I understand that "Microsoft Lists needs to be set up in SharePoint" should be enough. If you don't have SharePoint, you don't have Microsoft lists.

Thank you again.

**Comment by dipinn26592** [comment]
Thanks @dariomws , Thank you for looking into this.  We have license requirement for webinar as well. As per

https://www.microsoft.com/en-us/microsoft-365/blog/2021/05/11/introducing-webinars-in-microsoft-teams-easy-professional-webinars-to-engage-customers/

 " 1These new capabilities will be available in Microsoft 365 E3/E5, Microsoft 365 A3/A5, and Microsoft 365 Government G3/G5 plans. Microsoft 365 Business Standard and Microsoft 365 Business Premium plans will include all the features above for up to 300 attendees. And for the rest of 2021, we are offering a promotional period where all Teams users can try the features with their existing subscription. Please visit the Microsoft 365 roadmap and Microsoft Docs for additional feature details and availability " 
 
 My suggestion would be to call out all the prerequisites in the beginning of the doc itself clearly. There are many customers who are new to office 365 and would sign up to Teams just to try out Webinar ( comparing it with compete products ).
 
Now as pre our document customer would start setting up the policy and PowerShell command and later they figure out Sharepoint, List is needed. For someone who is new to Office365 wont know about Sharepoint and list and would step into a maze of Sharepoint documents and settings. Later ultimately figuring our its a different service which also needs a license. 
 
if we can just call out clearly the prerequisites, it will help a lot of customers.

**Comment by dariomws** [comment]
If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=dipinn26592

**Comment by dariomws** [comment]
> " 1These new capabilities will be available in Microsoft 365 E3/E5, Microsoft 365 A3/A5, and Microsoft 365 Government G3/G5 plans. Microsoft 365 Business Standard and Microsoft 365 Business Premium plans will include all the features above for up to 300 attendees. And for the rest of 2021, we are offering a promotional period where all Teams users can try the features with their existing subscription. Please visit the Microsoft 365 roadmap and Microsoft Docs for additional feature details and availability "

I understand that these license requirements are for the Microsoft Teams and Microsoft Dynamics 365 Marketing integration. I agree that we can move up this note.
