### ISSUE TITLE
Windows 10 21H1

### ISSUE THREAD

**Issue by sbenzch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7822]
Please add in the section "Windows 10 release support" a statement for 21H1.

Thank you
Simon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ecd6ee6-8850-f346-5684-9c5d2444789f
* Version Independent ID: a55a7a01-211d-147a-5332-b68e1051a2a1
* Content: [Microsoft Teams Rooms app version support - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-lifecycle-support)
* Content Source: [Teams/rooms/rooms-lifecycle-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-lifecycle-support.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
