### ISSUE TITLE
Billing granuality

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7824]
Hello

What is the granuality in which calling plans and communications credits are being billed? Is it per every started minute or second or 6 seconds or some other period?

Document states that "All calls exceeding these minutes are billed per minute." but it does not say what about the minutes from the calling plan pool and if the per minute billing from communication credits also has minute granuality.

Thanks
PAwel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 243fa83d-b7bf-323a-a14a-026915d3d058
* Version Independent ID: fd4a310b-3144-4a8b-1bde-c2efd0c87377
* Content: [Calling Plans for Microsoft 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/calling-plans-for-office-365)
* Content Source: [Teams/calling-plans-for-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/calling-plans-for-office-365.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Larryngolog, thank you for your feedback.

In all cases, the unit used is the minute. For calling plans pool, you'll be billed by minutes from the pool. The same for communications credits. Some more information here:
https://docs.microsoft.com/microsoftteams/what-are-communications-credits

**Comment by Larryngolog** [comment]
Thanks for clarification.
