### ISSUE TITLE
Is Assign a policy package to a group still in private preview?

### ISSUE THREAD

**Issue by iainwyatt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7825]
Under **Ways to assign policies** it indicates that "Assign a policy package to a group"  is in private preview. Is this still the case? I couldn't see a reference to this on the page it links to (https://docs.microsoft.com/en-us/microsoftteams/assign-policy-packages). This functionality appears to be available in the UI without a private preview indicator.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a541409b-0495-5ea6-46dd-78f44efe95b4
* Version Independent ID: a968f419-1d73-6d04-b01c-a505e1263cf3
* Content: [Assign policies in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/policy-assignment-overview)
* Content Source: [Teams/policy-assignment-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/policy-assignment-overview.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
