### ISSUE TITLE
Hold Music Size Limitation

### ISSUE THREAD

**Issue by jstrong013** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7827]
To the best of my knowledge, the largest size for custom hold music file is 5mb. We should add this to the documentation. Thoughts? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 416f3cdb-ca75-8224-bc04-985e5f7ea9dd
* Version Independent ID: 6e8c6f33-8043-e367-b44b-74b5f5ee96f2
* Content: [Music on Hold - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/music-on-hold?WT.mc_id=linkedin)
* Content Source: [Teams/music-on-hold.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/music-on-hold.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@jstrong013 thank you for reaching out and helping improve MS Docs. Do you have any official documentation confirming this? Please advise and I'll add the info to the article. I'm also doing some research to see if I can find any article confirming this.

**Comment by jstrong013** [comment]
@lindspea nothing to reference from official public channels. Thanks for considering

**Comment by CarolynRowe** [comment]
Please ask @JensTrier.

**Comment by JensTrier** [comment]
It is already documented including supported file types under Import-CsOnlineAudioFile, which is the cmd that actually uploads the audio file

**Comment by CarolynRowe** [comment]
Thanks @JensTrier.  Because it's already documented, let's not add it to the topic in question.  Duplicated information often gets out of sync.  I'm closing this issue.
