### ISSUE TITLE
Default TeamsUpgradeMode should be "TeamsOnly" with the automatic enforcement 

### ISSUE THREAD

**Issue by FrankCarius** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7829]
This page need a correction?
I think the "Default" TeamsUpgradeMode will be **TeamsOnly** instead of **Island** with the delivery of the automatic enforcement of Teams and Channels in Auf/Sep 2021.

> Any given user will always be assigned a TeamsUpgrade mode, either by default or explicitly by the administrator. The default  > value is **Islands**. Users upgraded to Teams have the mode of TeamsOnly. SfBOnly, SfBWithTeamsCollab, and 
> SfBWithTeamsCollabAndMeetings are also possible modes.

Frank

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169a20a6-ebf7-1093-3cb1-fb438b9b7e13
* Version Independent ID: b2074fd8-724e-75fa-bafb-a0f7966bf593
* Content: [Coexistence with Skype for Business - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/coexistence-chat-calls-presence)
* Content Source: [Teams/coexistence-chat-calls-presence.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/coexistence-chat-calls-presence.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @FrankCarius Frank, how are you?
I checked different tenants, the tenants that had SkypeFB Online indeed now only have TeamsOnly, however, in tenants with SfB On-Premises, it is still Islands mode. As this article applies to both. Do you agree?
Maybe a clarification to the sentence is needed.

> TeamsOnly
Only possible if the user does not have an on-premises account in Skype for Business Server

https://docs.microsoft.com/en-US/microsoftteams/migration-interop-guidance-for-teams-with-skype

Let me know if I understood you well,

**Comment by FrankCarius** [comment]
I agree with your. A Tenant without local SfBClients will be on "teams only".
And you are right,  i missed the Headline "Coexistence with Skype for Business" on the page "https://docs.microsoft.com/en-us/microsoftteams/coexistence-chat-calls-presence" 
The statement  **The default value is Islands** is correct here. My fault/misunderstanding. The most of my customers are now teams only and the default there is teams only.  everything fine.
