### ISSUE TITLE
bitrate KB/s

### ISSUE THREAD

**Issue by akkawamu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7831]
[Enter feedback here]
Bandwidth requirements (bitrate KB/s up/down)
->Suggention: Bandwidth requirements (bitrate kb/s up/down)

 If you use capital letters, they will be misinterpreted as bytes. For this reason, please consider using lowercase letters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d996cf7-9f48-2b30-7759-afaf3fe82caa
* Version Independent ID: 24dd6cdf-d35f-53b2-06c2-0a27891825d4
* Content: [Prepare your organization's network for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/prepare-network)
* Content Source: [Teams/prepare-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/prepare-network.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by shadenMSFT** [comment]
Hello, In the French translation of the page we have the same error. "vitesse de transmission en **Ko**/s vers le haut/bas".
 It should be "vitesse de transmission en **Kb**/s vers le haut/bas"
o in French means octet which the translation of Byte
b is bit which is the same than english ..

**Comment by TinaMcN** [comment]
@shadenMSFT thanks for the feedback about the French page.   After the English page is fixed it will be sent for retranslation and we can check then to see if it's been fixed also for French.

**Comment by TinaMcN** [comment]
@scanum the English content still says Kb
![image](https://user-images.githubusercontent.com/53281468/138192641-bb41884b-ced8-46f6-aeaa-27c3bb6e82bb.png).
According to wikipedia "The internationally recommended unit symbol for the kilobyte is kB."
https://en.wikipedia.org/wiki/Kilobyte
Can you please fix the English article?

**Comment by lindspea** [comment]
> @scanum the English content still says Kb ![image](https://user-images.githubusercontent.com/53281468/138192641-bb41884b-ced8-46f6-aeaa-27c3bb6e82bb.png). According to wikipedia "The internationally recommended unit symbol for the kilobyte is kB." https://en.wikipedia.org/wiki/Kilobyte Can you please fix the English article?

Fixed, thanks @TinaMcN
