### ISSUE TITLE
The Teams Collaboration bars's link is broken in the doc

### ISSUE THREAD

**Issue by kristofftan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7835]
The Collaboration bars's link is broken in the below doc: 
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/edit/live/Teams/devices/device-management.md

The broken link is:
https://www.microsoft.com/microsoft-365/microsoft-teams/across-devices/devices/category?devicetype=16

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@kristofftan thank you for pointing this out and helping improve MS Docs. Do you think this link will help if I add it to the article - https://techcommunity.microsoft.com/t5/microsoft-teams-blog/the-first-collaboration-bar-for-microsoft-teams-is-now-available/ba-p/1231706

**Comment by kristofftan** [comment]
Yes, I think so.

BTW, but, there isn't a Collaboration bar Category on the certify device page.
