### ISSUE TITLE
Description of the unsupported feature, "PSTN call ringback tone

### ISSUE THREAD

**Issue by takataka365** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7836]
One of the unsupported features in Teams calling and meeting on VDI is the
"PSTN call ringback tone".
is listed.
This is due to the fact that SIP early media is not supported, but this expression may not allow the reader to correctly recognize the scope of impact caused by the lack of early media support.

**In the Japanese telephony environment, there are many telecommunication carrier services that use early media.** 
The following are some examples.

- Contact centers often use toll-free numbers, and many of the voice announcements played at the beginning of toll-free numbers use early media. Usually, a voice announcement such as "Thank you for calling, this is xxx contact center..." is heard, and then the IVR works. However, in the case of non-supported early media, the caller does not hear such voice announcements and thus cannot recognize that the IVR is working.

- If you call a cell phone that is out of range or turned off, you will hear the following announcement: "The phone you are calling is either out of range or turned off." This announcement also uses early media. Therefore, if early media is not supported, the caller will not hear this announcement and will not know why the call is not being answered.

As you can see, there are many cases where early media is used in the Japanese phone environment, so we would like you to **clearly state that early media is unsupported**. Also, as the scope of the impact, could you please include the fact that the ringback tone of PSTN calls cannot be heard and some voice announcements cannot be heard?

Please Improve the instructions so that customers are aware that early media is not supported and does not become a blocker in phone deployment projects.

Thank you very much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
