### ISSUE TITLE
Licensing Requirements Update Requried?

### ISSUE THREAD

**Issue by Dusted1969** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7839]
[Enter feedback here]
This link:
https://docs.microsoft.com/en-us/MicrosoftTeams/bookings-app-admin#prerequisites-for-using-the-bookings-app-in-teams

States that:

"Users must have an appropriate license. Office 365 A3, A5, E3, E5, F1, F3, Microsoft 365 A3, A5, E3, and E5, Business Standard are supported."

As per MC266481 all F1 and F3 SKU's get access including M365 F1 & F3.  This is also noted at this link:

https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-faq?view=o365-worldwide#how-do-i-get-microsoft-bookings

This may cause confusion for end users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1cf44b6-0499-9a1f-aa73-48e777fbe4a0
* Version Independent ID: b9af859f-9ff2-8975-b900-33fc8c087cae
* Content: [Manage the Bookings app in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/bookings-app-admin)
* Content Source: [Teams/bookings-app-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/bookings-app-admin.md)
* Service: **msteams**
* GitHub Login: @dmaguire
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @Dusted1969
