### ISSUE TITLE
Misleading wording on Disable P2P file transfers for your organization

### ISSUE THREAD

**Issue by BSiefferman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#784]
The section for Disabling P2P File Transfer for your Organization is misleading as it states: 
To allow P2P transfers for inside your organization but block external file transfers to another organization, you just need to change it at a global level. 
Earlier in the article it states running: 
Set-CsExternalUserCommunicationPolicy -EnableP2PFileTransfer $False will only disable P2P File Transfer for federated users. However this does not state that it would cover external non-federated users. Can you please provide clarification around this? I want to know if it is possible to block external File Transfer for non-federated users without having to disable FileTransfer all together. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eae5979d-76b0-bff5-f655-1cd37be5af8b
* Version Independent ID: 3fe66025-3925-ca53-e948-c9fb3d0ddb81
* Content: [Block Point-to-Point file transfers](https://docs.microsoft.com/en-us/skypeforbusiness/set-up-policies-in-your-organization/block-point-to-point-file-transfers)
* Content Source: [Skype/SfbOnline/set-up-policies-in-your-organization/block-point-to-point-file-transfers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-policies-in-your-organization/block-point-to-point-file-transfers.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@BSiefferman Thank you for this feedback

I want to make sure that you get your answers promptly. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
