### ISSUE TITLE
Add note: Outlook desktop voicemail player experience. 

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7840]
Add information for Outlook registry key to display the player experience for voicemail in Outlook when protected voicemail is enabled. 

https://docs.microsoft.com/en-us/officeupdates/current-channel-preview#version-2107-july-06

We added a registry key to allow for the Voicemail form to be displayed in the UI in Outlook Desktop, due to the retirement of Unified messaging in Exchange Online (https://techcommunity.microsoft.com/t5/exchange-team-blog/retiring-unified-messaging-in-exchange-online/ba-p/608991). For users, enterprises, and organizations that want the Voicemail form to appear, the following registry key needs to be set: [HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\Outlook\Addins] "AllowVoicemailForm"=dword:00000001

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8228f9b2-a7de-abb4-6f41-70db0b3af155
* Version Independent ID: 8fd9fafb-dd76-59a8-e609-56f06d539a31
* Content: [Set up Cloud Voicemail - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-phone-system-voicemail)
* Content Source: [Teams/set-up-phone-system-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-phone-system-voicemail.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@TheBluLion thank you for reaching out and helping improve MS Docs. At a quick glance I see you have referenced two MS Doc articles. The issue has been opened under the "Set up Cloud Voicemail - Microsoft Teams" document. Are you suggesting adding the key registry information to this article?

**Comment by TheBluLion** [comment]
Yes as a note.
When the transport rule for protected voicemail is configured, the default behavior for voicemail messages in the Outlook desktop client changes for new mailboxes and no longer presents the player button. The registry key is required to continue presenting the player UI for Outlook desktop.
