### ISSUE TITLE
Teams admin center is not reflecting the documentation

### ISSUE THREAD

**Issue by TheITguy666** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7843]
It makes sense to include the video filters on the group Audio/Video on this page
https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-audio-and-video#video-filters-mode

But if you go to the Teams Admin center, it appears on the meeting policies group 'Content Sharing'
https://admin.teams.microsoft.com/policies/meetings/edit/R2xvYmFs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5d3a28c-7a66-831f-e610-9bf7d4edf9eb
* Version Independent ID: 0bc4a251-816e-0d77-efb2-53b7ffccb0f5
* Content: [Manage meeting policies for audio and video - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-audio-and-video)
* Content Source: [Teams/meeting-policies-audio-and-video.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-audio-and-video.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@TheITguy666 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @TheITguy666 created a PR to address this.
