### ISSUE TITLE
Outdated information

### ISSUE THREAD

**Issue by TheITguy666** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7844]
About the "Allow  Meet now in private meetings"
https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams-general#allow-meet-now-in-private-meetings

It's not Powershell only setting now. It appears now on the group 'Participants & guests'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80cf0306-57b6-2b96-f105-651bf0dbb768
* Version Independent ID: 63c5a0be-28ee-3c7a-6520-12abce276e80
* Content: [Manage general meeting policies - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams-general)
* Content Source: [Teams/meeting-policies-in-teams-general.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams-general.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
