### ISSUE TITLE
Text predictions setting exists?

### ISSUE THREAD

**Issue by TheITguy666** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7845]
the reference to "Text predictions Turn on this setting to let a user get text predictions for chat messages."

doesn't appear on the Teams admin center

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34f3188-0af5-f972-9d28-959f5f7866a2
* Version Independent ID: fab26e11-a729-92a4-3ea6-8668dca55dd0
* Content: [Manage messaging policies in Teams - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/messaging-policies-in-teams)
* Content Source: [Teams/messaging-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/messaging-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@TheITguy666 thank you for pointing this out. Perhaps this is where the note applies - "Note
Some of these settings, such using Giphys, can also be configured at the team level by team owners and at the private channel level by private channel owners."
I'll find out from the team and advise soonest.

**Comment by lindspea** [comment]
@TheITguy666 just following up on this. Is this feature showing on your side now?
