### ISSUE TITLE
Ambiguous wording for MTR joining external Teams meetings

### ISSUE THREAD

**Issue by JasonSmith-MS** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7846]
The article is ambiguously worded and structured when trying to discover if this applies to whether an MTR can join a Teams meeting hosted in another tenant. Through our own testing we validated it could once the mailbox for the resource account was configured to accept external invitations (step 1). Step 2 did not apply in our particular test. And Step 3 seems to be only for Zoom/WebEx (or perhaps tenants that do not allow anonymous meeting joins). I recommended cleaning up the language to be clearer for MTR joins to external Teams meetings. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c62081e-2421-80b9-8ba9-aaf8fd55e432
* Version Independent ID: 5df3c5e5-978f-cfa7-9e5c-3cd7f65fa8ff
* Content: [Enable Teams Rooms devices to join third-party meetings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/third-party-join)
* Content Source: [Teams/rooms/third-party-join.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/third-party-join.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @JasonSmith-MS how are you?
Just to confirm, you want to know exactly if the article was intended only to join third-party services OR another Teams tenant? Please correct me if I misunderstood you, to my understanding, in the introduction of the article that is clearly stated:

> Microsoft Teams Rooms devices support a one-touch experience for joining third-party online meetings, also referred to as Direct guest join. When enabled, you can use a Teams Rooms device **to join meetings hosted on Cisco WebEx and Zoom** just as easily as you can join meetings hosted in Microsoft Teams.
