### ISSUE TITLE
Mbps vs KB/s

### ISSUE THREAD

**Issue by guillaume-dube** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7847]
Good afternoon,

In your bandwidth requirement you list as KB/s (kiloBytes/sec) but in the section just above you mention "can deliver HD video quality in under 1.5Mbps" (Megabit per sec).

Then, in the table you list all the values in Kb/s (kilobit/sec) like Video One-to-One 1500/1500 which is 1.5Mbps

You did a typo in the KB/s, it should be Kb/s

"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d996cf7-9f48-2b30-7759-afaf3fe82caa
* Version Independent ID: 24dd6cdf-d35f-53b2-06c2-0a27891825d4
* Content: [Prepare your organization's network for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/prepare-network)
* Content Source: [Teams/prepare-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/prepare-network.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @guillaume-dube thanks for reporting, apparently was fixed in this PR https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/7693 and it could take a while to reflect in the published version.

**Comment by get-itips** [comment]
@scanum please close

**Comment by get-itips** [comment]
@scanum please close
