### ISSUE TITLE
Additional best practice suggestions

### ISSUE THREAD

**Issue by jburns-wipfli** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7849]
[Enter feedback here]

- Remove channel email addresses as these email addresses allow people to bypass the “Only moderators can post” settings. 
- Remove write access for non-owners to the underlying SharePoint library 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an organization-wide team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team#best-practices)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@jburns-wipfli thank you for helping improve MS Docs. I think the section about channels is covered in the linked article https://docs.microsoft.com/microsoftteams/manage-channel-moderation-in-teams. Let me know if you agree? Please can you clarify the information about SharePoint library and under which section you recommend this to be added?

**Comment by jburns-wipfli** [comment]
Thanks @lindspea! I don't think this article covers the idea that email sent to the channel email address still bypasses the channel moderation settings currently. This is probably something Microsoft needs to fix but thought it's worth a mention here. The example in our case was that the channel was locked down so only moderators could post and I sent an email to the channel's email address and was able to post anyway.

Regarding the SharePoint permissions, the underlying Files tabs aren't locked down and anyone in an org-wide team can upload to that document library. This boils down to changing member permissions in SharePoint for the Team to be Read-Only.

**Comment by lindspea** [comment]
@tiburd please can you assist here?

**Comment by tiburd** [comment]
@jburns-wipfli - Thank you for your suggestions for improving this article! I've forwarded them to the documentation team.
