### ISSUE TITLE
Teams Guest Access is on by default, not off?

### ISSUE THREAD

**Issue by yllekz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7853]
Hello, according to this article, Guest Access in Teams is on by default as of 2/8/21:

https://www.msn.com/en-us/news/technology/guest-access-is-now-on-by-default-in-microsoft-teams/ar-BB1dx9r0

The [doc states](https://docs.microsoft.com/en-us/MicrosoftTeams/guest-access): "Guest access in Teams is an organization-wide setting and is turned off by default."

Is the documentation right or wrong then?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2492e210-08f9-a476-97ec-008926def961
* Version Independent ID: adcb0dd9-4a3c-b665-6e34-ce3276c89b4d
* Content: [Guest access in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/guest-access)
* Content Source: [Teams/guest-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
