### ISSUE TITLE
Requested updates for documentation

### ISSUE THREAD

**Issue by drewbishop25** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#786]
Hello,

Couple notes I think could help:

-Remove the link to the video, or, reshoot it. It no longer reflects the method listed in the documentation. It is located in Deploy>Deployment Overview>Device Software Installation

-Update the logic for version checking on the Windows 10 ISOs to support 1803 (unless that version isn't supported by SRS, in which case, that should be noted in the documentation)

Otherwise, script seems to work great. Much better than the old method. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51d42140-9f7b-a6f3-7a3e-76cc7331cf22
* Version Independent ID: a7dacc56-c2df-55fb-76a3-ecb194564fae
* Content: [Configure a Skype Room Systems v2 console](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/console#prepare-the-installation-image)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/console.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by AndreaBarr** [comment]
@drewbishop25 Thank you for this feedback

I agree those are great updates. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by jambirk** [comment]
All verifications and downloads of windows versions, Client installers and drivers should rely on the script for SRS media creation. We are purposefully not calling out supported combinations. Let the script do that part of the chore!
