### ISSUE TITLE
Bookings App no longer available for Teams Desktop?

### ISSUE THREAD

**Issue by dsghi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7866]
Is the Bookings app for Teams no longer available? The link provided only opens if using the Teams web app, the desktop version shows not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1cf44b6-0499-9a1f-aa73-48e777fbe4a0
* Version Independent ID: b9af859f-9ff2-8975-b900-33fc8c087cae
* Content: [Manage the Bookings app in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/bookings-app-admin)
* Content Source: [Teams/bookings-app-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/bookings-app-admin.md)
* Service: **msteams**
* GitHub Login: @dmaguire
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
