### ISSUE TITLE
Provisioning Package example or link

### ISSUE THREAD

**Issue by DarlishaCampbell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7878]
[Enter feedback here]
Under "Create provisioning package" it would be useful to have either a .pkg example of what would be useful to configure for MTR or a link to one of the provisioning package documents

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a711c07e-10b3-baf0-b92c-9dbcf6ab9474
* Version Independent ID: 2038cd48-44b1-1ed1-6e50-48290eef5605
* Content: [Prepare your Environment - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-prep)
* Content Source: [Teams/rooms/rooms-prep.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-prep.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@DarlishaCampbell Thanks for your feedback, we will consider adding this in the future.
