### ISSUE TITLE
How can we limit the Alloff setting

### ISSUE THREAD

**Issue by silentreproach** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7879]
[Enter feedback here]
What if we want to limit Teams to collaboration and chat functionality, but only on our RDS server? That is, we don't want to limit Teams when people use it on their local computer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80cf547a-2220-53ac-4da6-50a654158eb7
* Version Independent ID: 6c12b7eb-7c37-907b-80b7-2ad102018556
* Content: [Use Teams with remote desktop services - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-on-rdp)
* Content Source: [Teams/teams-on-rdp.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-on-rdp.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
