### ISSUE TITLE
Pricing for Audio Conferencing

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7880]
This is kind of piggy backing on a ticket from 2020 "Pricing for Audio Conferencing #4411"  The link for pricing for audio conferencing takes you to a Microsoft marketing page, that says the cost of a license or can do pay per minute.  There is only a purchase or contact sales options.  What I am having a hard time finding is what do you get with the $4.00 a month.  I found an article about minutes from 150 to 3000, but think that was just for standard PTSN phone, and not audio conferencing.

Not really finding anything about cost for toll free numbers, just mention in one article about needing communications credit.

I ended up having to contact the sales group about this, which I don't really like to do, because they end up trying to push the product, and I am just gathering information.  Is there an article that breaks down what you get for the $4.00 per month?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by rconiv** [comment]
Why would I need to open a support ticket to have an entry put in the document that shows what the price gets you?
