### ISSUE TITLE
Deploy Microsoft Teams Rooms with Exchange on Premise

### ISSUE THREAD

**Issue by ihntremmel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7884]
https://docs.microsoft.com/en-us/microsoftteams/rooms/with-exchange-on-premises

On this page under Create an account and synchronize with Active Directory or Enable the remote mailbox and set properties, it does not indicate that the user must be disabled in order to enable a room mailbox.  When you run the command
`Enable-Mailbox PROJECTRIGEL01@contoso.com -Room`
when you have not disabled the account, Powershell for Exchange 2016 will return the error code
`The user's Active Directory account must be logon-disabled for linked, shared, or resource mailbox.`

Additional comment/issue:
according to https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-licensing the only license required is Teams Rooms Standard or Premium.  These pages indicate Skype for Business (Plan 1) or Plan 2.  It does not indicate how to create a Teams Rooms PSTN phone number while using Teams Rooms Standard or Premium Licensing.  I may be incorrectly interpreting this, so apologies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91cd0219-b3b0-da60-6416-c6b5a67623e3
* Version Independent ID: 983d08b5-4a2c-838a-52eb-821045d2c9df
* Content: [Deploy Microsoft Teams Rooms with Exchange on-premises - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-exchange-on-premises)
* Content Source: [Teams/rooms/with-exchange-on-premises.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-exchange-on-premises.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@ihntremmel thank you for pointing this out. Just for clarity, are you suggesting adding a note with regards to the room mailbox?

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
