### ISSUE TITLE
Out of date locations for former company-wide settings

### ISSUE THREAD

**Issue by justinkobel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7890]
Instructions on this page still refer to the "Org-wide" settings interface, which has recently been removed.  E.g. External Users (federated chat) has moved to underneath Users (as of 2021-09-23 across approximately a half-dozen tenants I have been able to confirm). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9b7f77-061d-a224-ff1c-8d3e15d21221
* Version Independent ID: 00fa9550-c4c4-3398-ffbb-271cc724048f
* Content: [Manage settings for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/enable-features-office-365)
* Content Source: [Teams/enable-features-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enable-features-office-365.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @justinkobel, thank you for your feedback.

The new Teams Admin Center navigation was released 2 days ago. There is an internal work in progress to updates these articles.
