### ISSUE TITLE
Retention of recording for producers and presenters

### ISSUE THREAD

**Issue by bartvermeersch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7892]
The recording for the attendees is kept for 180 days, but there is no info on how long the mp4 recording for producers and presenters remains available.

The table in https://docs.microsoft.com/en-US/microsoftteams/teams-live-events/live-events-recording-policies#storage-and-persistence-behavior

Just states: "An MP4 is created and stored"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae14299b-94b7-6dcd-5560-c1dbee13918f
* Version Independent ID: 8e145920-8a41-ed84-e366-797081ea162c
* Content: [Live events recording policies - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/teams-live-events/live-events-recording-policies)
* Content Source: [Teams/teams-live-events/live-events-recording-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/live-events-recording-policies.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@bartvermeersch thank you for reaching out. As far as I know the recordings are always saved in the Microsoft Stream Platform. If I'm not mistaken the recording will be kept in the meeting chat for 21 days after the event and can be downloaded, but will no longer be accessible for download from the chat after 21 days. Please let me know if you have any other information regarding this that needs clarity.

**Comment by bartvermeersch** [comment]
@lindspea the 21 days is/was for regular teams meeting recordings, not live events as far as I know.

I did found in the MS end user documentation that the presenters and organizers have the same 180 days to download the recording (see [https://support.microsoft.com/en-us/office/schedule-a-teams-live-event-7a9ce97c-e1cd-470f-acaf-e6dfc179a0e2](https://support.microsoft.com/en-us/office/schedule-a-teams-live-event-7a9ce97c-e1cd-470f-acaf-e6dfc179a0e2)

- A recording is available to producers for download for 180 days after the event is over.
- Attendees can watch the event on demand using DVR options for 180 days.

**Comment by bartvermeersch** [comment]
Sorry if I'm not cross referencing correctly with a pull request:
[https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/7914](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/7914)
