### ISSUE TITLE
A1 SKU Auto-expiration clarification

### ISSUE THREAD

**Issue by solarfusionuk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7895]
``
This page states "A1 users will be defaulted to a 30-day expiration period" and according to MC274188 "A1 users will receive a 30-day expiration default that can be reduced but not increased"

Which service plan needs to be on the A3 / A5 SKU for users to be able to increase the expiration period? Is it the Teams, Stream, or SharePoint (OneDrive) service plan?

For example, we have uses that have the "Microsoft Teams" service plan enabled under The A1 Plus SKU, but "SharePoint (Plan 2)" enabled under an A3 SKU - would they be able the increase the expiration period?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/cloud-recording#auto-expiration)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by lindspea** [comment]
@solarfusionuk thank you for reaching out and helping to improve MS Docs. I'm checking with the team and will let you know soonest.

**Comment by lindspea** [comment]
@solarfusionuk The article has been updated to mention that the auto-expiration feature is not yet launched. Please see the roadmap in the article for more information. Thanks again for reaching out to help improve Microsoft Docs.
