### ISSUE TITLE
Images appear missing

### ISSUE THREAD

**Issue by mschmidtwest** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7896]
Hi.  Images on this page appear to be missing or link is broken. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ad0c889-56d5-35fe-de15-177b6d922d07
* Version Independent ID: e4363647-33e1-b665-5881-169fb619a5b3
* Content: [Microsoft Teams PSTN usage report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/pstn-usage-report)
* Content Source: [Teams/teams-analytics-and-reports/pstn-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/pstn-usage-report.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@mschmidtwest thank you for pointing this out. I'm looking into having this rectified soonest.
