### ISSUE TITLE
MFA not supported for CX 600 or any other Aries phones.

### ISSUE THREAD

**Issue by greganth1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#79]
Need to add the following Note: CX 600 or any other Aries phones doesn't support MFA. If MFA is enforced for Skype for Business then devices will fail to sign-in 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8473d3c9-66e3-0b24-e614-ddc454ea9554
* Version Independent ID: b14dcf01-eb59-cb18-013c-1bc2f33ca46a
* Content: [Deploying Skype for Business Online phones](https://docs.microsoft.com/en-us/skypeforbusiness/what-is-phone-system-in-office-365/getting-phones-for-skype-for-business-online/deploying-skype-for-business-online-phones)
* Content Source: [Skype/SfbOnline/what-is-phone-system-in-office-365/getting-phones-for-skype-for-business-online/deploying-skype-for-business-online-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/what-is-phone-system-in-office-365/getting-phones-for-skype-for-business-online/deploying-skype-for-business-online-phones.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by tonysmit** [comment]
Fixed. Thanks for the feedback!!
