### ISSUE TITLE
The org-wide settings on TAC is gone

### ISSUE THREAD

**Issue by TheITguy666** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7900]
since two days ago the Org Wide settings on Teams Admin Center is gone and the sub-menus distributed across the Users and Teams Menu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9b7f77-061d-a224-ff1c-8d3e15d21221
* Version Independent ID: 00fa9550-c4c4-3398-ffbb-271cc724048f
* Content: [Manage settings for your organization - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/enable-features-office-365?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/enable-features-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enable-features-office-365.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @TheITguy666 Luis, you are right, as you noted, this happened soon, there is an internal process to update those articles.
Thanks
