### ISSUE TITLE
Media traffic: Media processors geography - Out of date information

### ISSUE THREAD

**Issue by tylerstosic** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7901]
The information in the "Media traffic: Media processors geography" is out of date and contradictory.

In this section, it is stated:
_For example, we do not have a SIP proxy component now in Australia (SIP flows via Singapore or Hong Kong) but we do have the media processor locally in Australia._

However further down the section it is highlighted that there is infact media processors AND SIP proxies in Australia (as of November 2020) 

_Locations where both SIP proxy and media processor components deployed:
Australia (AU East and Southeast datacenters)_

As each region now has a media processor and SIP proxy deployed side by side, this section of the documentation may no longer be required, or could be simplified. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e26faf8c-529e-b317-5934-cd41cfe8fa24
* Version Independent ID: 3ddd5d0a-6dbb-4940-1814-8346e293701b
* Content: [Plan Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan)
* Content Source: [Teams/direct-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by lindspea** [comment]
@tylerstosic thank you for pointing this out. I'll be researching this shortly, but in the meantime do you have any suggestions for change in the article?

**Comment by tylerstosic** [comment]
@lindspea thanks for getting back to me. 
Upon reviewing the article for my suggestions it has already been updated.
