### ISSUE TITLE
direct routing license requirements

### ISSUE THREAD

**Issue by SRE93** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7903]
Is direct routing not applicable with a business voice without calling plan subscription?
Because here https://docs.microsoft.com/en-us/MicrosoftTeams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=small-business#what-voice-features-are-available-with-my-plan you can find that direct routing is possible with business voice.

On this page here the requirements are only mention the phone system license.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e26faf8c-529e-b317-5934-cd41cfe8fa24
* Version Independent ID: 3ddd5d0a-6dbb-4940-1814-8346e293701b
* Content: [Plan Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan#licensing-and-other-requirements)
* Content Source: [Teams/direct-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by SRE93** [comment]
Hi scanum, any updates on this? We need a clear statement on this for a custome project

**Comment by dariomws** [comment]
Hi @SRE93, thank you for your feedback.

Business voice includes Phone System. Please check it here:
https://docs.microsoft.com/microsoftteams/business-voice/whats-business-voice
