### ISSUE TITLE
information update

### ISSUE THREAD

**Issue by TheITguy666** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7904]
1. On TAC calling policies it appears now an option "Cloud recording for calling' that it's not documented here

2. https://docs.microsoft.com/en-US/microsoftteams/teams-calling-policy#allow-music-on-hold
It's now possible also on TAC: Allow music on hold for PSTN callers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410fc30b-f530-8443-0602-9150c9cba115
* Version Independent ID: c5b33b25-147b-f7d4-056a-987088950e7c
* Content: [Calling policies in Microsoft Teams: Calling and call-forwarding features - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/teams-calling-policy)
* Content Source: [Teams/teams-calling-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-calling-policy.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
