### ISSUE TITLE
Guest access location moved on TAC

### ISSUE THREAD

**Issue by TheITguy666** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7906]
There is no 'org-wide' menu o TAC.
The guest access is now on the 'Users' menu group

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042d7ce6-ee22-690f-8188-ff8a4a585847
* Version Independent ID: 3e5bc99c-e08e-44e0-cda3-687ed3633175
* Content: [Turn on or turn off guest access to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-guests)
* Content Source: [Teams/set-up-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-guests.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback, created a pull request to update the article.
