### ISSUE TITLE
Outdated information: section 4 is no longer valid as the legacy admin center for Skype for Business is no longer available.

### ISSUE THREAD

**Issue by martinagrom** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7913]
[section 4 is no longer valid as the legacy admin center for Skype for Business is no longer available.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed33488-1a24-f443-dd56-c5327188b5a4
* Version Independent ID: 8da32180-396d-c7a8-6410-472beabff9ce
* Content: [Set up Audio Conferencing for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-audio-conferencing-in-teams)
* Content Source: [Teams/set-up-audio-conferencing-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-audio-conferencing-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@martinagrom thank you for pointing this out and helping to improve Microsoft Docs. The The Microsoft Teams admin center has replaced the Skype for Business Admin center. Do you recommend changing the heading from "Using the Skype for Business admin center:" to "The Microsoft Teams admin center? Or should step 4 be removed completely?
