### ISSUE TITLE
App name is not visible in the report

### ISSUE THREAD

**Issue by JohanssonMarkus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7915]
Hey, 
In the Teams report I can only see APP ID/GUID and not the app name. 
How can I find out the app it self. I have searched for the app ID in Teams and in Azure for Enterprise apps and app registrations but can't find it anywhere. Any guidance on that?

![image](https://user-images.githubusercontent.com/32453241/135092077-ff71922b-c0fe-4b91-83aa-f968c8d46bdb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48493968-9715-1d4b-c712-72b9eb5bc834
* Version Independent ID: 958f2076-17b4-eb8d-49a3-86d5acb50055
* Content: [Microsoft Teams information protection license report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/information-protection-license-report)
* Content Source: [Teams/teams-analytics-and-reports/information-protection-license-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/information-protection-license-report.md)
* Service: **msteams**
* GitHub Login: @anandab-msft
* Microsoft Alias: **anandab**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by anandab-msft** [comment]
@JohanssonMarkus - ack this, we are looking into this and will keep you updated.

**Comment by anandab-msft** [comment]
@JohanssonMarkus - since you are not able to search these app IDs then these are the apps which were using these API but they are deleted now.  I think deleted apps older than 30 days are not shown in enterprise app so you are not able to view these app details. can you check the report for 30 days and let us know if you see any case where app is showing instead of app name.

**Comment by JohanssonMarkus** [comment]
@anandab-msft 
Make sense. Checking 30 days and 7 days back give me nothing.
![image](https://user-images.githubusercontent.com/32453241/135823716-6a14bbfe-8479-49dc-9e0e-91db46493c2d.png)
