### ISSUE TITLE
Teams now supports External user group chat.

### ISSUE THREAD

**Issue by thecathcart** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7916]
This statement:
"Native Teams chats with people in other organizations are limited to 1:1 chats only."
is no longer accurate.  Inviting external users to Group Chat was released back in May 2021.

https://www.microsoft.com/en-ca/microsoft-365/roadmap?filters=Microsoft%20Teams&searchterms=external%2Caccess

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ac8f101-bdb5-2b55-d5f4-e070b70768d4
* Version Independent ID: 964d836e-d00b-b585-8f02-e03c5ec8dab9
* Content: [Native chat experience for external (federated) users in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/native-chat-for-external-users)
* Content Source: [Teams/native-chat-for-external-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/native-chat-for-external-users.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
