### ISSUE TITLE
Section: 'Configure the team custom app setting' - required option missing 

### ISSUE THREAD

**Issue by karezza** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7917]
The screenshot does not match, and the option I'm supposed to enable does not exist as an available option to turn on or off.  It must exist in a different location?

Attempted to follow the directions as best as possible to enable globally & via policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d51bb7b1-801e-6801-dcaf-afa3e38e6941
* Version Independent ID: d8e726a1-cbf2-53c7-da4d-cc155b48612b
* Content: [Manage custom app policies and settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-custom-app-policies-and-settings#org-wide-custom-app-setting)
* Content Source: [Teams/teams-custom-app-policies-and-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-custom-app-policies-and-settings.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by karezza** [comment]
I think I may have found the correct procedure Teams apps -> Setup policies -> click on the policy -> click manage users -> add users

If this works this will be good enough for my use case.  Testing ...

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
