### ISSUE TITLE
Emergency Call Routing doesn't mention a number of countries

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7927]
The section for emergency call handling does not mention a number of countries. It looks like it covers the first group of countries to be supported by calling plans, but offers no details for any of the follow on countries.

Can this information be added?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634810fc-7a47-f794-7803-9f3941d664dd
* Version Independent ID: 52587955-5054-a003-6d03-948ce02838dd
* Content: [Plan and manage emergency calling - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/what-are-emergency-locations-addresses-and-call-routing)
* Content Source: [Teams/what-are-emergency-locations-addresses-and-call-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-emergency-locations-addresses-and-call-routing.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@TorrenManson thank you for reaching out and helping improve Microsoft Docs. There is a link in this article to another article that shows a list of all the countries that currently have this option. "To find out whether Calling Plans is available in your area, see Country and region availability for Calling Plans." Please let me know if you need further assistance.

**Comment by TorrenManson** [comment]
Hi,

The issue isnt support for Calling Plans, it's support for Emergency Calling through Calling Plans. I could not find a link to another article that included this information, and this article only addresses the first few countries (US, Canada, UK, Japan, for example).
________________________________

**Comment by lindspea** [comment]
@TorrenManson thank you for clearing this up. This article will be improved continuously but in the meantime please see this document - https://docs.microsoft.com/MicrosoftTeams/configure-dynamic-emergency-calling
