### ISSUE TITLE
Settings from Templates were not applied

### ISSUE THREAD

**Issue by J-a-k-o-b** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7928]
Hi, 
using the Templates from the Admin Center should support the "cloning" of Settings from the template. This does not work at all.
Either you choose a pre build template, or creating a new template using an existing Team, or creating a new template and define the settings via JSON (using new-csteamtemplate), the settings were not applied to the new team wich was deployed with template.
I'm aware of the issue https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7388 . But there is mentioned that it is supported in general, but maybe not in the template GUI. As stated before, this is not all. It's not possible to apply the settings via a Team Template using any native method which allowes the user to choose a template.

The only way I know, which works is using the graph clone teams method (https://docs.microsoft.com/en-us/graph/api/team-clone?view=graph-rest-1.0&tabs=http). 

This can not be the way it should be and should be stated out here, or it should be fixed, which would be better.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef94e9a3-a0a5-11da-f27b-627ac4fa6186
* Version Independent ID: e49db873-ed77-de53-e4dd-be4fc571d734
* Content: [Get started with team templates in the Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-started-with-teams-templates-in-the-admin-console)
* Content Source: [Teams/get-started-with-teams-templates-in-the-admin-console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-started-with-teams-templates-in-the-admin-console.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanachin**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@J-a-k-o-b thank you for reaching out and helping to improve Microsoft Docs. I see the article has just been updated today with some more information. Please could you have a look and let me know if any more information still needs to be updated. Also, would you recommend adding the link you referenced to this article?

**Comment by J-a-k-o-b** [comment]
Hi @lindspea,
no, the last updates are just corrections of links. I don't see any relevant updates in the article
