### ISSUE TITLE
Update of the usage reports references

### ISSUE THREAD

**Issue by JensTrier** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7930]
In Step 2 in the note box, last paragraph: the reference should be to the PSTN and SMS (preview) usage report
In Step 2, paragraphs below the Note box the reference to the pstn usage report should be via Teams admin center -> Analytics & reports -> Usage reports -> PSTN and SMS (preview) usage
In Step 2 last paragraph the link to the doc page for pstn usage report should point to https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/pstn-usage-report

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 277cf140-5c6c-82c7-cc56-490ef2188754
* Version Independent ID: 72e7de29-fd71-23bf-15a7-172634c2a5fd
* Content: [Set up Communications Credits for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-communications-credits-for-your-organization?source=docs#feedback)
* Content Source: [Teams/set-up-communications-credits-for-your-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-communications-credits-for-your-organization.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
