### ISSUE TITLE
The screenshots don't render for me

### ISSUE THREAD

**Issue by JensTrier** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7931]
There are screenshots on the page, but they don't render for me. I only see below
![image](https://user-images.githubusercontent.com/40833221/135449884-35a0e766-bb2e-42de-a81f-1535c2ca6bea.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ad0c889-56d5-35fe-de15-177b6d922d07
* Version Independent ID: e4363647-33e1-b665-5881-169fb619a5b3
* Content: [Microsoft Teams PSTN usage report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/pstn-usage-report)
* Content Source: [Teams/teams-analytics-and-reports/pstn-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/pstn-usage-report.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
