### ISSUE TITLE
please describe wich trial

### ISSUE THREAD

**Issue by anapereiCRMSE** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7933]
https://docs.microsoft.com/en-us/microsoftteams/teams-exploratory#who-isnt-eligible
Currently have Teams from a paid license or trial licens**e, or **previously had trial license****
Are in a tenant that used/received at least one special COVID 

Can you please specify if is a Teams trial license and not any other trial license?
We had several misunderstandings around this topic. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-exploratory)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @anapereiCRMSE, thank you for your feedback.

Could you kindly provide more detail about your question? My apologies but I don't understand. Thanks!
