### ISSUE TITLE
CreateSrsMedia.ps1 script not working

### ISSUE THREAD

**Issue by MarceloSAS** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7940]
**********************
Windows PowerShell transcript start
Start time: 20211001113445
Username: *********
RunAs User: ********
Configuration Name: 
Machine: ******** (Microsoft Windows NT 10.0.19042.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command if((Get-ExecutionPolicy ) -ne 'AllSigned') { Set-ExecutionPolicy -Scope Process Bypass }; & 'C:\Users\******
Process ID: 23320
PSVersion: 5.1.19041.1237
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.1237
BuildVersion: 10.0.19041.1237
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\********
WARNING: This version of Windows may not be new enough to run this script.
WARNING: If you encounter problems, please update to the latest widely-available version of Windows.
Host OS version 10.0.19042.1237
Script version 1.6.1
Downloading CreateSrsMedia...
done
Validating signature for update.ps1...
success.

DBCA96FE120BA5E07E8CB43304B6976C1CE188002BADDBAB31A35EDB1D4D2B04A3A670D5DB80048D867080C373CC680E98B6CDB22DC649FA71EE8163BE2C08AC
73839

What type of customer are you?
Please make sure you have all of the following available:

1. A USB drive with sufficient space (16GB+).
   The contents of this drive WILL BE LOST!
2. Windows 10 Enterprise media that matches your SRSv2 deployment kit.
   Enterprise customers can access Windows 10 Enterprise media from the Volume Licensing Service Center:
   http://www.microsoft.com/licensing/servicecenter
3. Any language pack (LP and/or LIP) files to be included.
   MPSA customers:         http://go.microsoft.com/fwlink/?LinkId=125893
   Other volume licensees: http://www.microsoft.com/licensing/servicecenter

Please do not continue until you have all these items in order.

Downloading deployment kit...
done
Validating signature for SRSDeploymentKit-4.9.12.1.msi...
success.
Extracting the deployment kit...
done.
This deployment kit is built for Windows build 10.0.19041.631.
This deployment kit draws its drivers from %configsetroot%\AutoUnattend_Files\DistShare\Out-of-Box Drivers.

Please indicate what drivers you wish to use with this installation.
[ 0] Logitech SmartDock
[ 1] Crestron SR
[ 2] Polycom MSR
[ 3] Lenovo Hub 500
[ 4] LRS
[ 5] HP Slice 2.0
[ 6] Crestron Flex
[ 7] None
Selected option 0.
[ 0] Surface Pro 4
[ 1] Surface Pro (2017)
[ 2] Surface Pro 6
Selected option 0.
Downloading driver...
PS>TerminatingError(Save-Url): "Exception calling "DownloadFile" with "2" argument(s): "The operation has timed out""
>> TerminatingError(Save-Url): "Exception calling "DownloadFile" with "2" argument(s): "The operation has timed out""
>> TerminatingError(Save-Url): "Exception calling "DownloadFile" with "2" argument(s): "The operation has timed out""
>> TerminatingError(Save-Url): "Exception calling "DownloadFile" with "2" argument(s): "The operation has timed out""
>> TerminatingError(Save-Url): "Exception calling "DownloadFile" with "2" argument(s): "The operation has timed out""
**********************
Windows PowerShell transcript end
End time: 20211001113659
**********************

**Comment by MarceloSAS** [comment]
What is wrong here? Anyone has a clue?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
