### ISSUE TITLE
Missing Information or link to reason why no names show on Reports

### ISSUE THREAD

**Issue by devman2k** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7947]
Running Usage Activity reports such as USER Activity no longer show user names. There is no indication on this page that is the expected behavior. Please update with additional information or link to reason why and how to display the names of the users on the report

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2758a3d6-c646-dcb0-2a31-c7b9b84e780b
* Version Independent ID: 8704c9fe-f8b0-82d2-bd83-3fd1a9ad638d
* Content: [Microsoft Teams user activity report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report)
* Content Source: [Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@devman2k thank you for reaching out. Please have a look at the roadmap here for upcoming improvements - https://www.microsoft.com/microsoft-365/roadmap?filters=Microsoft%20Teams&searchterms=63351

**Comment by devman2k** [comment]
Hi Lindsay,

The reports do in fact show the names but there is a process to change the settings in a non-report location within Office.
This is not an upcoming feature but rather a point of confusion that could easily be remedied with update doc.

The Roadmap page you referenced with a default value of 63351 in the search field shows no results

***@***.***
