### ISSUE TITLE
AudioCodes Supported Version 7.2?

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7952]
Hello,

we are really concerned that a huge chunk of our managed devices are now no longer be supported, because they are still on v7.2 and may so for a while due to a restriction with the version of the OVOC platform we have installed and the change control we employ.

Working with AudioCodes Support and their Microsoft contacts, we have verbal agreement that Microsoft will support 7.2, but given that this document is the one Engineers will reference for this, I want to make sure that

a) Microsoft truly supports v7.2 (Recommended v7.4 is fine)
b) Documentation could be updated to reflect this.

Thank you,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1a1c01-10a9-7f69-1c7b-1a566b0f5112
* Version Independent ID: 329ee759-40fc-98fb-b91e-87786c63024b
* Content: [Session Border Controllers certified for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-border-controllers)
* Content Source: [Teams/direct-routing-border-controllers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-border-controllers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Looping in @FilippSe . Filipp:  Can you comment, please?

**Comment by FilippSe** [comment]
Hi, this change to firmware version was specifically requested by Audiocodes. Audiocodes performed all the required verification and testing and asked to change firmware version accordingly. This change is not Microsoft driven

**Comment by CarolynRowe** [comment]
Thank you, @FilippSe. @DEberhardt: Based on Filipp's response, I am closing this issue so that the docs are not updated erroneously.  Please follow up with AudioCodes support.
