### ISSUE TITLE
Can take up to 48 hours for the new app to be available

### ISSUE THREAD

**Issue by jochilds-ms** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7955]
Hello, from my understanding when a new custom app is uploaded in the Teams admin centre it can take up to 48 hours for the new app to be available to the global endpoint that the app setup policy references. It would be useful to mention this propagation time in the documentation so admins are aware of the wait time needed before they can apply an app setup policy. 

Would be supportive to add to the guidance below that is currently added:
"How long does it take for policy changes to take effect
After you edit or assign a policy, it can take a few hours for changes to take effect."   

Many thanks,
John

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f91604a-35b0-dfbb-55b2-b601cb0841b0
* Version Independent ID: 84bcd0d7-b4ed-f13e-c84b-2ec6a7661ae9
* Content: [Manage app setup policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-app-setup-policies)
* Content Source: [Teams/teams-app-setup-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-setup-policies.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
