### ISSUE TITLE
MOH File Size allowed

### ISSUE THREAD

**Issue by techlogik** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7956]
Always helps if you tell people the file size and formats that are allowed for MOH.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 416f3cdb-ca75-8224-bc04-985e5f7ea9dd
* Version Independent ID: 6e8c6f33-8043-e367-b44b-74b5f5ee96f2
* Content: [Music on Hold - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/music-on-hold)
* Content Source: [Teams/music-on-hold.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/music-on-hold.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@techlogik thank you for reaching out. Please see related issue https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7827. "It is already documented including supported file types under Import-CsOnlineAudioFile, which is the cmd that actually uploads the audio file."
