### ISSUE TITLE
Add Requirement for 'Microsoft Visual C++' on Windows Server

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7965]
Teams Client on Windows Server 2019:
- Add Install "Microsoft Visual C++"!
- https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-160
- (Login/Authentication doesn't work otherwise)

errorCode: caa70004, 
errorDescription: There's a more permanent way to sign in to Microsoft Teams. If you're having trouble completing the process, talk to your IT admin.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by lindspea** [comment]
@weyCC81 thank you for reaching out and helping to improve Microsoft Docs. For clarity, please can you elaborate on what you are suggesting to have added/changed to the article in question. Thanks in advance.

**Comment by weyCC81** [comment]
"Microsoft Visual C++" is a requirement for running Teams on Windows Server otherwise you get an undefined error message. Please add this hint in the documentation, i searched for hours...

#please-reopen
