### ISSUE TITLE
Issue with ProvisionCloudSkype function

### ISSUE THREAD

**Issue by drewbishop25** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#797]
Hello,

It seems there may be an issue with the error catching in the portion of the function that gets the the registry pool and enables the meeting room. I am unsure what exactly is wrong, but when I remove the error handling it seems to work fine. For example this works:

&lt;code&gt;
$strRegPool = $null
$strRegPool = (Get-CsTenant).TenantPoolExtension
$strRegPool = $strRegPool[0].Substring($strRegPool[0].IndexOf(':') + 1)
Enable-CsMeetingRoom -Identity test -RegistrarPool $strRegPool -SipAddressType EmailAddress
&lt;/code&gt;

However in the context of the original script it just fails and ends the script. I tried removing some of the error handling to get some more details but I was only able to find the following:

Cannot bind parameter 'RegistrarPool'. Cannot convert value "" to type "Microsoft.Rtc.Management.Deploy.Fqdn". Error: "Invalid fully qualified domain name (FQDN).

That tells me that the script is dropping in to the if function and clearing the value of $strRegPool like below:

&lt;code&gt;
  if ($Error)
    {
        print $Error

        $strRegPool = ''

        Write-Host 'We failed to lookup your Skype for Business Registrar Pool, but you can still enter it manually'
    }
	
    else
    {
        $strRegPool = $strRegPool[0].Substring($strRegPool[0].IndexOf(':') + 1)
    }
&lt;/code&gt;

What I haven't been able to figure out is why it drops in to that if function. I've tried to replicate the issue with varying levels of success. Hopefully you can figure out what the problem is because other than this the script works great!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d495057-36be-b228-0483-aae89fd01666
* Version Independent ID: f02fa875-b84b-5501-5879-17ea3d017142
* Content: [Configure accounts for Skype Room Systems v2](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/room-systems-v2-configure-accounts)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/room-systems-v2-configure-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/room-systems-v2-configure-accounts.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by AndreaBarr** [comment]
@drewbishop25 Thank you for this feedback. 

I want to make sure we properly figure our and document what is gong on with your script. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by drewbishop25** [comment]
I don't think this is actually an issue with my tenant as when I run the commands outside the script they seem to work fine. I was able to get my Skype for Business Meeting Room working without issue. I was just leaving a comment so the script can be investigated so others do not have this issue.

**Comment by AndreaBarr** [comment]
@drewbishop25 okay thank you clarifying that for me. I'll make sure this gets investigated.

**Comment by SharS** [comment]
The script will be replaced soon. In the meantime, you can use the FastTrack iteration of the script available at https://myadvisor.fasttrack.microsoft.com/CloudVoice/Downloads?SelectedIDs=5_2_0_4,5_2_0_5

**Comment by jaserNo1** [comment]
I checked the script, since I faced the same issue.

Looks like $error has never been cleared before the if statement.

Just alter the script as follows:

```
# Getting registrar pool
	
    try
      {
       PrintAction -strMsg 'We have now connected to Skype for Business, please wait while we attempt to set up the meeting room' 
       Countdown -timeSpan 300
	Clear-Host 
        $strRegPool = $null
	$Error.Clear()
        $strRegPool = (Get-CsTenant).TenantPoolExtension
    }
```

Than it works as expected.

regards
jeremias
