### ISSUE TITLE
RecordingStorageMode "Stream" parameter no longer works

### ISSUE THREAD

**Issue by DaanvanBeek1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7970]
Hi, in this document it is correctly stated that after the final stage of the rollout of Stream (SharePoint) for meeting recordings you can no longer revert to the old method: "No new meeting recordings can be saved to Microsoft Stream (Classic)".
However there is still a paragraph in the document describing how to change the Teams Meeting Policy to store recordings in Stream (Classic): "Opt out of OneDrive for Business and SharePoint to continue using Stream"
This paragraph does not seem to be updated after the finalization of the rollout, as the described functionality no longer works, which is in line with the rest of the communication regarding the subject.

Can someone please verify/update/elaborate on this?

Thanks in advance,
Daan
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8935e913-806f-a92c-d09e-e67df4ffd1b4
* Version Independent ID: c7a41cde-66dd-d7cd-1316-42d20ed4841a
* Content: [Use OneDrive for Business and SharePoint for meeting recordings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/tmr-meeting-recording-change#opt-out-of-onedrive-for-business-and-sharepoint-to-continue-using-stream)
* Content Source: [Teams/tmr-meeting-recording-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tmr-meeting-recording-change.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @DaanvanBeek1, thank you for your feedback and help us to improve docs.microsoft.com.

I think there is no rush to remove that information as we can understand it as history information. There is a note at the beginning of the article that states:
"[!NOTE] The change of storing Teams meeting recordings from Classic Stream to OneDrive and SharePoint (ODSP) has been completed as of August 30th, 2021. All recordings are now stored in ODSP. This change overrides the RecordingStorageMode policy, and modifying the setting in PowerShell no longer has any impact."

I'll change it to an important note. What this note means is that the following sections doesn't apply anymore:
- Set up the meeting recording option for OneDrive for Business and SharePoint
- Opt-out of OneDrive for Business and SharePoint to continue using Stream
