### ISSUE TITLE
Calling Plan Pooling

### ISSUE THREAD

**Issue by SpudIT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7974]
I would highly recommend changing the terminology for the pooling of calling plans, to avoid confusion.

Pooling is only available on identical calling plans, capped minutes plans like "Domestic Calling Plan (120 Minutes)" cannot be pooled with "Domestic calling plan"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 243fa83d-b7bf-323a-a14a-026915d3d058
* Version Independent ID: fd4a310b-3144-4a8b-1bde-c2efd0c87377
* Content: [Calling Plans for Microsoft 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/calling-plans-for-office-365)
* Content Source: [Teams/calling-plans-for-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/calling-plans-for-office-365.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by SpudIT** [comment]
Hi there,
I would recommend either a purple note explaining the calling plans have to be identical to be pooled together. I would place this just above the blue important section,

Or provide a full breakdown of the available calling plans as there aren't just "2" as categorised in the documentation, see below full list available for the UK for example:

There are four plan options available per calendar month:
120 minute Domestic Calling Plan
240 minute Domestic Calling Plan
1200 minute Domestic Calling Plan
Domestic and International Calling Plan: 1200 minutes of domestic -OR- 600 minutes of international calling (whichever is reached first in the calendar month)

After testing - although the "Domestic calling" plans are named the same, and to anyone they work in the same way but they are simply capped minutes, they are in fact completely seperate plans. so pooling the minutes between each "Domestic Plans" is not possible. I think this is to stop confusion for people (like myself) that intended on using a mixture of plans based on usage, but the ability pool still.

I hope that makes sense.
