### ISSUE TITLE
Store recordings outside you country

### ISSUE THREAD

**Issue by janetslei** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7976]
Can we get an explanation behind the setting "Store recordings outside of your country or region"? What is the purpose of that? why would we turn this setting on?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5a373db-4ab5-91ad-660a-9e3b0ee854f9
* Version Independent ID: fb83f07e-3523-ed1f-1666-ecd9742477ea
* Content: [Manage meeting policies for recording and transcription - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meetings-policies-recording-and-transcription#store-recordings-outside-of-your-country-or-region)
* Content Source: [Teams/meetings-policies-recording-and-transcription.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meetings-policies-recording-and-transcription.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by KarliStites** [comment]
@janetslei You can use this policy for different purposes. For example, you might use it if your company is in one region, but operated or owned in another.
