### ISSUE TITLE
Mistranslation ”Kollective" on Japanese site

### ISSUE THREAD

**Issue by tasukuhisaki** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7977]
Hi, there is a mistranslation on Japanese translated the page. 
https://docs.microsoft.com/ja-jp/microsoftteams/teams-live-events/what-are-teams-live-events

It should be "Kollective" instead of "集合", it is in the picture on that site.

Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: becbf3ca-b88c-b033-a145-9a1af201ced3
* Version Independent ID: 41a6a9b5-d3dd-d8c9-9e97-920ff2fd1a24
* Content: [What are Microsoft Teams live events? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/what-are-teams-live-events)
* Content Source: [Teams/teams-live-events/what-are-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/what-are-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by tasukuhisaki** [comment]
Any update on this?

**Comment by cdowling1971** [comment]
@tasukuhisaki @scanum @tiburd 
This looks to me like this is the same reported issue as https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8000

This has been logged using the service **Hub** website: https://globalservices.powerappsportals.com/Global/ - see the "**Report a translation bug**" link. You can use the "**Follow**" feature in ADO to see how this request is progressing.

**Bug:** https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/172397

Going forward can we ask you to please log a bug from the **Hub** website to achieve quicker time to mitigate, thanks in advance.
FYI @TinaMcN
