### ISSUE TITLE
404 Links

### ISSUE THREAD

**Issue by iehlers** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7983]
Hello
It seems that the direct Links to the Project Planning etc. not working (404 Error)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e8b47aa-e7a9-7744-4344-23830ca3178a
* Version Independent ID: ddfc4477-255f-dbff-cae2-ff01b74f969c
* Content: [Tools and Downloads for Adoption - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/adopt-tools-and-downloads)
* Content Source: [Teams/adopt-tools-and-downloads.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/adopt-tools-and-downloads.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by lindspea** [comment]
@iehlers thank you for pointing this out and helping to improve Microsoft Docs. I see most of those links at the top of the article are not working. I'll investigate to fix the links. Does this article help at all for more clarity - https://docs.microsoft.com/MicrosoftTeams/adopt-microsoft-teams-landing-page.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
