### ISSUE TITLE
Cloud Voicemail for Teams users for Exo license

### ISSUE THREAD

**Issue by akkawamu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7984]
Please add the explaining about Exo license on Cloud Voicemail for Teams users page.
some people says the users must have ExoP2, other people says the users can use only Exo license.
actually all users can use voicemail including F3, E1. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8228f9b2-a7de-abb4-6f41-70db0b3af155
* Version Independent ID: 8fd9fafb-dd76-59a8-e609-56f06d539a31
* Content: [Set up Cloud Voicemail - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-phone-system-voicemail#cloud-voicemail-for-teams-users)
* Content Source: [Teams/set-up-phone-system-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-phone-system-voicemail.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by akkawamu** [comment]
Hi @Dario ***@***.***>, I really appreciate for quick response.
When the user have any Exchange online license (Exo Plan1, Plan2 and Kiosk), can they use voicemail? Customers ask us ExO license type. So Please please add them.
https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description#feature-availability-across-exchange-online-standalone-plans

**Comment by akkawamu** [comment]
@Dario ***@***.***>-san
Thank you for your quick and kind answer! It become very clear!
Yes, Yes, CSS and BG members also confuse it. Some people say users need ExoP2, others say they must have only Exo license. So it is the reason I ask you to write about Exchange license for Teams Users.

Akihiro Kawamura

**Comment by dariomws** [comment]
Some more context:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7438
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4343

And I see that you opened more issues:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7763
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7751

@CarolynRowe confirmed it internally. Carolyn, could you kindly confirm that EXO Plan 2 is still required for Cloud Voicemail when you have on-prem SfB users? In that case, I think we should add the information to the related article, I've created a PR a few weeks ago:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/7462

**Comment by CarolynRowe** [comment]
The article linked to in this issue is for Teams online users.  Is the real confusion about this article instead:  https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-cloud-voicemail  which is about cloud voicemail for on-prem users?

**Comment by dariomws** [comment]
@CarolynRowe, yes, my PR adds the information about the EXO P2 requirement for SfB on-prem users.

I think the article linked to in this issue has all the information about licenses:
- "Cloud Voicemail requires Exchange mailboxes for users where it deposits voicemail messages": I understand any license with an Exchange mailbox.
- "For Teams users, Cloud Voicemail is automatically set up and provisioned. A Microsoft Teams Phone license is not required for Cloud Voicemail.": I understand any license with Teams.
