### ISSUE TITLE
Missing info on TreatDiscoveredPartnersAsUnverified

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7988]
This page is missing details on the "TreatDiscoveredPartnersAsUnverified" property on the Get-CsTenantFederationConfiguration information.

Does Teams ignore this? Was this only for Skype for Business?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external access (federation) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by danmyhre** [comment]
hi @lindspea , I think we need msft to confirm the intended behavior and then add the response to this article. Thanks!

**Comment by tiburd** [comment]
@danmyhre @lindspea 

Here's what I heard back from a few members of the team:

> From Set-CsTenantFederationConfiguration, 
> 
> -TreatDiscoveredPartnersAsUnverified
> When set to True, messages sent from discovered partners are considered unverified. That means that those messages will be delivered only if they were sent from a person who is on the recipient's Contacts list. The default value is False ($False).
> I would not expect Teams itself to care about this, but SFBO of course does. And federated interop between onprem and Teams goes thru SFBO, at least for now. So for any Teams org that is doing federation with pure onprem SfB orgs or onprem users in hybrid orgs, this setting would be honored specifically in those cases, if the Teams org sets it.  In those scenarios it would provide the behavior above. Of course, for federation between Teams to Teams, as well as when we complete federation via Teams Hybrid Edge without any dependency on GFS, then I assume this setting would no longer be honored, unless Teams went out of its way to honor it.  If I recall, you own federation, so I’m hoping you can clarify whether Teams honors it.  Btw, if Teams does not and is not planning to honor this, I would probably not recommend talking up this setting otherwise you might have a perceived take back once GFS-less federation lands.

> I think Teams ignores this option even though the communication goes via SfBO infrastructure.  The enforcement of this is on the pool and it is using the contact list and I don’t think it is applied for Teams-only users or won’t be applied in the very near future as we make them pool-less.

> Ah, so if it’s enforced on pool, rather than GFS edge, this would go away earlier. Currently about 40% of all users already bypass user pools for routing so they would not honor this. Eventually, all users will bypass user pools. 

Thanks!

**Comment by tiburd** [comment]
@lindspea - do you think we can close this issue now? I don't expect more feedback from the team.....
Thanks!

**Comment by danmyhre** [comment]
@tiburd Hi, I think the documentation still needs updating. If this is a SFB only setting, that definitely needs to be called out that it does nothing for Teams which is where we are all headed.
