### ISSUE TITLE
the uri should be http not https

### ISSUE THREAD

**Issue by waelschakaki** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#799]
Hello Team,
someone updated the document and the command now is 
New-CsServerApplication -Identity 'Service:Registrar:%FQDN%/BusyOptions' -Uri https://www.microsoft.com/LCS/BusyOptions -Critical $False -Enabled $True -Priority (Get-CsServerApplication -Identity 'Service:Registrar:%FQDN%/UserServices').Priority

which is not working at all, the uri should be http not https, I have tested it , and the old command was already http
Regards,
Wael

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2862dbfc-0165-c9f3-9328-e916019bf5a6
* Version Independent ID: 406b1238-0a8e-c7ee-ed19-e47d073a97dd
* Content: [Install and configure Busy Options for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-enterprise-voice/install-and-configure-busy-options)
* Content Source: [Skype/SfbServer/deploy/deploy-enterprise-voice/install-and-configure-busy-options.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-enterprise-voice/install-and-configure-busy-options.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by AndreaBarr** [comment]
@waelschakaki Thank you for this feedback

I'll make sure that command gets updated so it works correctly. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by DenisPapes** [comment]
Hi Team,
document is still incorrect, Uri should be http not https.

**Comment by get-itips** [comment]
Hi @waelschakaki thank you for your suggestion, document has been updated after your comment.
Thanks again

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @waelschakaki 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
