### ISSUE TITLE
broken link for helpdesk guide

### ISSUE THREAD

**Issue by valiantloong** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7992]
Hi, please fix the helpdesk guide link. and also the links into the doc is also not working?
https://docs.microsoft.com/en-us/OfficeDocs-SkypeForBusiness/blob/live/Teams/downloads/teams-adopt-helpdesk-guide.pdf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e8b47aa-e7a9-7744-4344-23830ca3178a
* Version Independent ID: ddfc4477-255f-dbff-cae2-ff01b74f969c
* Content: [Tools and Downloads for Adoption - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/adopt-tools-and-downloads)
* Content Source: [Teams/adopt-tools-and-downloads.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/adopt-tools-and-downloads.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
@valiantloong, please check the links again. Thank you!
