### ISSUE TITLE
HDMI Ingest missing from comparison table?

### ISSUE THREAD

**Issue by davepj-purify** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7997]
[Enter feedback here]
Hi - there doesn't seem to be any mention of HDMI ingest in the comparison table for MTRoA or MTRoW. Is HDMI ingest available for MTRoA?

Thanks,

Dave

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64cc650b-b313-cfab-9f45-190b94c128f4
* Version Independent ID: 9e93ac07-3f1b-9fd4-1907-17f0075bd837
* Content: [Teams devices for Shared Spaces feature comparison between Windows and Android - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/teams-devices-feature-comparison)
* Content Source: [Teams/rooms/teams-devices-feature-comparison.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/teams-devices-feature-comparison.md)
* Service: **msteams**
* GitHub Login: @amandafrechinjackson
* Microsoft Alias: **v-amandaf**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@davepj-purify thank you for reaching out and helping to improve Microsoft Docs. @tiburd please can you help. This feature was on the Microsoft 365 Roadmap for June 2021?

**Comment by tiburd** [comment]
Hello - The documentation team has acknowledged that **HDMI Ingest** isn't included in the table. The intro to the table states: 

> Not all Teams Rooms features will be included on this list, so please continue to consult the [Microsoft 365 roadmap](https://www.microsoft.com/en-us/microsoft-365/roadmap) and Microsoft sales representatives for additional details.

Thanks!
