### ISSUE TITLE
UAE has toll-numbers, page shows only toll-free is available.

### ISSUE THREAD

**Issue by rcalache** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7999]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a570df73-ffc3-73cd-a5aa-0fc1cd8b9fae
* Version Independent ID: 796b055c-3952-ecde-a8dd-873ad1c0a73d
* Content: [Availability in the United Arab Emirates (UAE) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-arab-emirates-uae)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-arab-emirates-uae.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-arab-emirates-uae.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
@lindspea @scanum:  Please note:  none of the availability topics can be updated without approval by a Microsoft PM.  I will forward this request to a PM, but please do not make any changes to this article until we get that approval.
