### ISSUE TITLE
Skype for Business Admin Center no longer exists

### ISSUE THREAD

**Issue by hazymat** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#800]
Although this doc was updated 4 days ago (21 Sep 2018), the Skype for Business Admin Center was rolled into Teams & Skype back in March. Please update this doc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac16b3b5-de8f-af59-9127-6edeb9f89a36
* Version Independent ID: df452aa6-873b-5a6b-b642-0eff6d3db919
* Content: [Getting phone numbers for your users](https://docs.microsoft.com/en-us/skypeforbusiness/what-are-calling-plans-in-office-365/getting-phone-numbers-for-your-users)
* Content Source: [Skype/SfbOnline/what-are-calling-plans-in-office-365/getting-phone-numbers-for-your-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/what-are-calling-plans-in-office-365/getting-phone-numbers-for-your-users.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@hazymat Thank you for this feedback

I'll make sure this article gets updated again. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by centretechnologies** [comment]
So...this still hasn't been updated........

**Comment by bernardw1** [comment]
You can still get to the Skype for Business Admin center through the Teams admin center (https://admin.teams.microsoft.com/dashboard). 

![capture](https://user-images.githubusercontent.com/23319226/53422402-03f0a380-39a5-11e9-903b-b7baa594b560.PNG)

**Comment by TokyoScarab** [comment]
@CarolynRowe  I would love to get your opinion on what would be the best way to go about updating this page and to what degree.  Thanks!

**Comment by CarolynRowe** [comment]
Please follow up with @tonysmit .  He's the expert on the Teams and SfB Admin centers.

**Comment by TokyoScarab** [comment]
@tonysmit Yes, I would love your thoughts on this.

**Comment by tonysmit** [comment]
The SFBO admin center wasn't 'rolled' into the Teams Admin Center. However, currently they need to use the Legacy portal link in the Teams Admin Center to get and port phone numbers. This will be changing in the future.
