### ISSUE TITLE
mistranslate parner's name in Japanese web

### ISSUE THREAD

**Issue by akkawamu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8000]
In Japanese Page, Kollective's name is mistranslate. then please correct following point from "集合" to Kollective. 
https://docs.microsoft.com/ja-jp/microsoftteams/teams-live-events/what-are-teams-live-events?source=docs

![image](https://user-images.githubusercontent.com/40044580/137044499-7b3d92ad-6898-4c2d-8d09-b69d26eca692.png)

Thank you for support

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: becbf3ca-b88c-b033-a145-9a1af201ced3
* Version Independent ID: 41a6a9b5-d3dd-d8c9-9e97-920ff2fd1a24
* Content: [What are Microsoft Teams live events? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/what-are-teams-live-events?source=docs)
* Content Source: [Teams/teams-live-events/what-are-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/what-are-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officeglobal - Could you please assist with this issue? Thanks!

**Comment by cdowling1971** [comment]
@akkawamu this issue you reported is now closed - thanks so much for reporting this to us.
