### ISSUE TITLE
Music on hold link

### ISSUE THREAD

**Issue by akkawamu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8001]
please add link  "music on hold " with follwoing URL
 https://docs.microsoft.com/en-us/microsoftteams/music-on-hold
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cfead3c-b0d8-c22a-aa22-63e79fe53ed3
* Version Independent ID: 10745875-3d3e-42bb-e324-ff4c83968ccf
* Content: [Here's what you get with Phone System - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/here-s-what-you-get-with-phone-system)
* Content Source: [Teams/here-s-what-you-get-with-phone-system.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/here-s-what-you-get-with-phone-system.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
