### ISSUE TITLE
Out of date firmware versions

### ISSUE THREAD

**Issue by adamfowlerit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8002]
Hi,
It looks like this page isn't being maintained for the latest supported firmwares - for example, Poly CCX600 will get 7.0.3.0515 via the Teams Admin Center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaaef9e1-8f1c-ebf0-7856-4c007342a2c3
* Version Independent ID: 3eaf671f-375e-8787-9c66-3947c3606559
* Content: [Devices for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/teams-ip-phones)
* Content Source: [Teams/devices/teams-ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/teams-ip-phones.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by adamfowlerit** [comment]
Ah I see, OK that new article is still out of date then as it lists 7.0.2.1072 for CCX600 where it should be 7.0.3.0515
