### ISSUE TITLE
CreateSrsMedia.ps1 timeout

### ISSUE THREAD

**Issue by Lars-KP** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8006]
I have tried for 2 days now and I allways get timeout when I Choose Logitech SmartDock and Surface Pro 6?
Please fix ASAP!

PowerScrript Error:
Save-Url : Exception calling "DownloadFile" with "2" argument(s): "Handlingen blev afbrudt pga. timeout"
At C:\kp\CreateSrsMedia.ps1:886 char:26

Log:
Please indicate what drivers you wish to use with this installation.
[ 0] Logitech SmartDock
[ 1] Crestron SR
[ 2] Polycom MSR
[ 3] Lenovo Hub 500
[ 4] LRS
[ 5] HP Slice 2.0
[ 6] Crestron Flex
[ 7] None
Selected option 0.
[ 0] Surface Pro 4
[ 1] Surface Pro (2017)
[ 2] Surface Pro 6
Selected option 2.
Downloading driver...
PS>TerminatingError(Save-Url): "Exception calling "DownloadFile" with "2" argument(s): "Handlingen blev afbrudt pga. timeout""
>> TerminatingError(Save-Url): "Exception calling "DownloadFile" with "2" argument(s): "Handlingen blev afbrudt pga. timeout""
>> TerminatingError(Save-Url): "Exception calling "DownloadFile" with "2" argument(s): "Handlingen blev afbrudt pga. timeout""
>> TerminatingError(Save-Url): "Exception calling "DownloadFile" with "2" argument(s): "Handlingen blev afbrudt pga. timeout""
>> TerminatingError(Save-Url): "Exception calling "DownloadFile" with "2" argument(s): "Handlingen blev afbrudt pga. timeout""

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/console#Prep_Media)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
