### ISSUE TITLE
live event limit increases extended?

### ISSUE THREAD

**Issue by shtakeda** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8018]
Have the live event limit increases been extended by Jan 31 2022?
Other pages say by Dec 31 2021.
https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#teams-live-events
https://resources.techcommunity.microsoft.com/live-events/assistance/

Microsoft 365 live event limit increases

To continue supporting our customers' needs, through **January 31, 2022**, we will extend temporary limit increases for live events, including:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events#teams-live-events-and-skype-meeting-broadcast)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by shtakeda** [comment]
Should be corrected, if the date is incorrect. Only this page says that the end date is Jan 31 2022.
https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events#teams-live-events-and-skype-meeting-broadcast
