### ISSUE TITLE
Feature not working

### ISSUE THREAD

**Issue by danielategan1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8020]
[Im Soirry by this feature i tge Teams Admin centre is not working - please remove it untill it does...]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad4aa355-090d-7315-aaf1-ed31a654e942
* Version Independent ID: 6bf8a83b-2bb6-6932-2e0d-6ccc742d1777
* Content: [Microsoft Teams Devices Monitoring and Alerting - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/alerts/device-health-status)
* Content Source: [Teams/alerts/device-health-status.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/alerts/device-health-status.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @danielategan1 
I can see the feature working, want to detail what do you see?
Thanks
