### ISSUE TITLE
Licensing compliance of using user licenses on devices

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8023]
Product licensing terms mention the E licenses as user licences https://www.microsoft.com/licensing/terms/productoffering/Office365Suites/EAEAS.

In such case, these licenses should not be used to license device accounts. If so, can we get clarity in this document to inform that using E1/E3/E5 etc (user) licenses is not compliant from licensing perspective and should be changed to TR license as soon as possible?

Something like:
If you are currently using E1, E3, E4, E5 SKUs with Skype for Business Plan 2 with Audio Conferencing or with Office 365 Phone System and a Calling Plan, these will continue to work. However, using user licenses (for example E1/E3 or E5 license) is not compliant from licensing perspective, therefore you should consider moving to Team Room license as soon as possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-licensing)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-licensing.md)
* Service: **skype-for-business-online**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Larryngolog** [comment]
Hi! My customers do not read it as "you are non-compliant from licensing perspective and NEED to change once your licenses expire". They understand the message as "you can continue using and you can consider to TR license but you do not have to. It will be just simpler for you, but if it's cheaper to use E1, you can continue". In other words, current wording is soft and does not clearly state that this is not compliant to use the E user licenses with MTR devices.

**Comment by Larryngolog** [comment]
If needed I can share answer from LicenseQ regarding licensing requirements

**Comment by dariomws** [comment]
@Larryngolog, I cannot say or confirm that we can use the word non-compliant here. I've forwarded this to another team and I'm waiting for confirmation.

**Comment by Larryngolog** [comment]
Hello, this issue was closed but was not resolved. What was the answer of the other team?
