### ISSUE TITLE
Update to Excel file for new CEE countries

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8025]
There were  5 new markets added in Sept to calling plans - Croatia, Estonia, Latvia, Lithuania, and Slovenia.

It is reflected on a per-country page but not in the excel file listing all countries.

Can we please get it updated as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b07cfcf-8f31-91ed-b1de-c7826a1ab91d
* Version Independent ID: dfbc4212-8f47-326a-f872-8186a915ae1e
* Content: [Country/region availability - Audio Conferencing, Calling Plans - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by lindspea** [comment]
@Larryngolog thank you for reaching out. I've just checked and the information is reflecting on the spreadsheet. Please let me know if you think something else is missing. Thanks again for your help in improving Microsoft Docs.

**Comment by Larryngolog** [comment]
Thanks a lot :)

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
