### ISSUE TITLE
Add in section for monitor Teams lifecycle management best practice 

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8027]
I would also add in a section for monitor Teams lifecycle management best practice so they you can identify potential issues and implement recommendations

- Number of Teams 
- Number of inactive teams
- Number of teams with guest users
- Ownerless groups
- Teams with duplicate names

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21628f34-dd1b-12ae-7d65-2fe20013b2e1
* Version Independent ID: 324ec037-70d9-a568-68fb-316a610e0b50
* Content: [Schedule service health reviews for your Microsoft Teams adoption - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-adoption-schedule-service-health-reviews)
* Content Source: [Teams/teams-adoption-schedule-service-health-reviews.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-adoption-schedule-service-health-reviews.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by get-itips** [comment]
Thanks for your feedback @nikki-c
