### ISSUE TITLE
Wrong Commands for MSI options

### ISSUE THREAD

**Issue by rtawney13** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#803]
The below is listed for the options for the "Teams Machine-Wide" MSI installer, but you have it pointing to an exe? Do you have the options to open application in background so its less intrusive to the user? Popping up on the screen is not very user friendly.

"Disable auto launch for the MSI installer
If you want to disable auto launch, enter the following command prompt:
msiexec /i Teams_windows.exe OPTIONS="noAutoStart=false"
"

**Comment by AndreaBarr** [comment]
@rtawney13 Thank you for this feedback

I agree this should be updated and corrected. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by rtawney13** [comment]
Is there an ETA on the fix?

Thanks,

**Comment by AndreaBarr** [comment]
@rtawney13 I have this in the backlog. We don't have an update at the moment but as soon as we do we will reply to this issue and let you know.

**Comment by get-itips** [comment]
Hi @rtawney13 thanks for the comments and feedback, we really appreciate them,  information was corrected after you opened this issue, (https://docs.microsoft.com/en-us/microsoftteams/msi-deployment#disable-auto-launch-for-the-msi-installer) hope this information helps you out.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @rtawney13  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
