### ISSUE TITLE
Routing calls to unassigned numbers - Disconnect after playing announcement 

### ISSUE THREAD

**Issue by ryderi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8046]
[Enter feedback here]

Hi,
The documentation states if routing calls to unassigned numbers through to an announcement, the audio file will be played once to the caller.  This is correct, however I'm surprised the call is then not disconnected, is it possible to play the call once then hang up?  Otherwise callers could be tying up the lines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed4beab-bb0d-fba4-814e-147d22fd97e5
* Version Independent ID: 8ed4beab-bb0d-fba4-814e-147d22fd97e5
* Content: [Routing calls to unassigned numbers - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/routing-calls-to-unassigned-numbers)
* Content Source: [Teams/routing-calls-to-unassigned-numbers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/routing-calls-to-unassigned-numbers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by JensTrier** [comment]
@scanum feel free to assign this to me, so I can keep track of it
