### ISSUE TITLE
Please could this be made clearer? User can change expiry.

### ISSUE THREAD

**Issue by Darrelo365** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8048]
Hi, in the FAQ, the questions reads: Can the expiration date be changed for each TMR, such as data A expiration date is 30 days and data B expiration date is 60 days?
The answer reads: Yes, the expiration date is set per file. Users can modify the expiration date in the details pane of a selected file in OneDrive or SharePoint.

Suggestion. This reads as if the feature is available now, should this be after the [dependant roadmap item has been rolled out](https://www.microsoft.com/en-gb/microsoft-365/roadmap?searchterms=82057&searchterms=84580&filters=&searchterms=84580)?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording#frequently-asked-questions)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
