### ISSUE TITLE
Information loop & dead links

### ISSUE THREAD

**Issue by wybesmits** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8049]
[Enter feedback here]

Information about "Phone System" doesn't seem to be relevant anymore because licensing is no longer available? 

URL DEAD = Pricing for Phone System. (https://go.microsoft.com/fwlink/?linkid=799763)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abae7324-861d-7ca7-7239-a5df8fd927d5
* Version Independent ID: 8a30bd2f-9bc3-a0a8-8b31-d53836ead4d0
* Content: [Microsoft Teams add-on licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=small-business)
* Content Source: [Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by get-itips** [comment]
Hello @wybesmits 
thanks for your feedback
The link is back online.
