### ISSUE TITLE
Lost pics

### ISSUE THREAD

**Issue by loveunicom** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#805]
There are two pics lost at the end of this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042d7ce6-ee22-690f-8188-ff8a4a585847
* Version Independent ID: 3e5bc99c-e08e-44e0-cda3-687ed3633175
* Content: [Turn on or off guest access to Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/set-up-guests)
* Content Source: [Teams/set-up-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-guests.md)
* Service: **msteams**
* GitHub Login: @laithalshamri
* Microsoft Alias: **laal**

**Comment by AndreaBarr** [comment]
@loveunicom Thank you for catching this.

I will make sure this gets corrected. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by lindspea** [comment]
@loveunicom thank you for pointing this out and for your contribution in helping improve MS docs. I will investigate the issue.

**Comment by lindspea** [comment]
@loveunicom Please confirm which two pics are lost at the end of the article? I'm unable to see what is missing.  Perhaps it has been updated since you opened the issue.  Please confirm soonest.

**Comment by loveunicom** [comment]
It works now.

Thanks!

Best regards，
Eric Chen
[signature_865912945]MVP

**Comment by lindspea** [comment]
@AndreaBarr @yogkumgit This can be closed thank you.

**Comment by yogkumgit** [comment]
@lindspea  Thank you very much for the contribution and sharing this explanation. @loveunicom  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
