### ISSUE TITLE
Missing command line arguments for Teams MSI deployment

### ISSUE THREAD

**Issue by ryanprosser** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8050]
There is not instruction about what msi command line to use when installing. 
Only a command line example under heading on how to prevent autostart

when installing the MSI linked on this page, is it a requirement to explicitly specify ALLUSERS=1
Is the MSI link on this page for the "machine wide installer" or is it generic, both per users and machine wide, depending on the command line?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Teams using Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @ryanprosser 

>  Is the MSI link on this page for the "machine wide installer" or is it generic, both per users and machine wide, depending on the command line?

When you run the msi it confirms that it is the machine-wide installer

![image](https://user-images.githubusercontent.com/36666927/142285540-3d043b97-21be-47e4-af12-ca4a7a904cdf.png)

I understand what you say about ALLUSERS being mentioned only in that section however the ALLUSERS setting is general to [windows installer packages](https://docs.microsoft.com/en-us/windows/win32/msi/allusers) (more info on how this switch works in the link)

> There is not instruction about what msi command line to use when installing. Only a command line example under heading on how to prevent autostart
> 
> when installing the MSI linked on this page, is it a requirement to explicitly specify ALLUSERS=1

It is not a requirement but the note in that section clarifies what happens when you use it so it is up to the user

>Note that these examples also use the ALLUSERS=1 parameter. When you set this parameter, **Teams Machine-Wide Installer appears in Programs and Features in Control Panel and in Apps & features in Windows Settings for all users of the computer. All users can then uninstall Teams if they have admin credentials on the computer.**

(Not to be confused with ALLUSER)

Hope this information helps you,

**Comment by ryanprosser** [comment]
@get-itips 
Thanks for the helpful comments
I still have the following issues with the MS Docs article

1. the nav sidebar titles the page "Install Teams using MSI"
![image](https://user-images.githubusercontent.com/50686991/142294542-87d30c4a-4460-4a10-a743-f69ec1b9a446.png)
but the page heading / title is "Install Microsoft Teams using Microsoft Endpoint Configuration Manager"

2. I do not find the page content particularly well focussed on the how to "Install Teams using MSI"
other related topics are presented, not the goal of follow these steps to deploys Teams from MSI

3. If the page heading / title of "Install Microsoft Teams using Microsoft Endpoint Configuration Manager" is the correct, then the content has zero reference or relevance to deploying Teams with MECM or Intune for that matter

RE Intune, am I to assume that a win32 app with the contentpreptool and uploading .intunewin file should then use this deployment command line?  since I don't want users to remove the program (ALLUSERS=1)
msiexec /i Teams_windows_x64.msi OPTIONS="noAutoStart=true"

Regards,
Ryan

**Comment by get-itips** [comment]
@ryanprosser Ryan, how are you?

About your question, I tested ALLUSERS with and without =1 for you in a lab vm and I experienced what [this other article](https://docs.microsoft.com/en-us/windows/win32/msi/installation-context) says:

![image](https://user-images.githubusercontent.com/36666927/142425785-d9f8eb7c-9480-40da-9e56-c8c4abefa316.png)

I would suggest you do some tests in your environment and see what works best for you.

The article in the past had the title that you can see in the TOC, and then was renamed, that's probably the reason why it still shows with the past title in there. I'll check to see how we can update the title there.

I think the article uses that title but then in the introduction is explained its broader use:

>To use Microsoft Endpoint Configuration Manager, or Group Policy, or any third-party distribution mechanisms for broad deployment[..]
