### ISSUE TITLE
Missing description for newer parameters

### ISSUE THREAD

**Issue by TheITguy666** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8060]
On Teams Admin Center there are now 2 new additional parameters
- Real-time captions in Teams calls
- SIP devices can be used to for calls

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410fc30b-f530-8443-0602-9150c9cba115
* Version Independent ID: c5b33b25-147b-f7d4-056a-987088950e7c
* Content: [Calling policies in Microsoft Teams: Calling and call-forwarding features - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/teams-calling-policy?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/teams-calling-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-calling-policy.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **tonysmit**

**Comment by lindspea** [comment]
Related PR https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8127

**Comment by haneef95** [comment]
Any updates on this?

**Comment by lindspea** [comment]
@haneef95 thanks for reaching out. When the PR is merged and goes live, the update will reflect.

**Comment by haneef95** [comment]
Thanks. Is there a PR I could read up on? I could only see issues, no linked PRs.

**Comment by lindspea** [comment]
@haneef95 Related PR - https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/8136
