### ISSUE TITLE
Set up holidays in Microsoft Teams

### ISSUE THREAD

**Issue by MJ-Webber** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8062]
After recent changes, need to alter the "Set up holidays in Microsoft Teams" Create and Change steps from:

In the Microsoft Teams admin center, go to Org-wide settings > Holidays.

to...

In the Microsoft Teams admin center, go to Voice > Holidays.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9908d77-78bc-ce88-ba84-4f1bd9fea504
* Version Independent ID: 37118dd4-d036-8da7-d750-4c9f503a370a
* Content: [Set up holidays in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/set-up-holidays-in-teams?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/set-up-holidays-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-holidays-in-teams.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Thanks for your feedback, a community member created a pr to edit the article, linked here.

**Comment by get-itips** [comment]
@scanum PR merged, please close

**Comment by get-itips** [comment]
@scanum
