### ISSUE TITLE
"Org-Wide settings" where are you ?

### ISSUE THREAD

**Issue by Lerritier** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8074]
Hello,

Everything is in the tille. In the webpage, you propose "To edit org-wide settings, go to the Microsoft Teams admin center, and then select Org-wide settings. You can configure the following settings."

In the version of the Teams Admin Console I use, there is no Org-Wide Settings section anymore... so how do I access "External Access" settings for example ?

Thanks a lot in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9b7f77-061d-a224-ff1c-8d3e15d21221
* Version Independent ID: 00fa9550-c4c4-3398-ffbb-271cc724048f
* Content: [Manage settings for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/enable-features-office-365)
* Content Source: [Teams/enable-features-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enable-features-office-365.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
@scanum please close as the PR has been merged.
