### ISSUE TITLE
The button is not always where you describe

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#808]
The interface is different than posted above. I'm using (16.0.10730.20127) and enabled for PSTN dialing, which changes the UX a little, but for anyone else looking, I have to click the 2 little people under the magnifying glass and then select "contacts not in my organization". Then another pop-out appears letting me select skype or skype for business. Unfortunately these comments don't let me include a screenshot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10e0a910-2870-5e87-fb52-b656bf26d0e4
* Version Independent ID: 9ffe82f7-58fb-d0a6-caa1-66818c4db0f0
* Content: [Let Skype for Business users add Skype contacts](https://docs.microsoft.com/en-us/skypeforbusiness/set-up-skype-for-business-online/let-skype-for-business-users-add-skype-contacts)
* Content Source: [Skype/SfbOnline/set-up-skype-for-business-online/let-skype-for-business-users-add-skype-contacts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-skype-for-business-online/let-skype-for-business-users-add-skype-contacts.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@Mike-Crowley Thank you for this feedback

You can attach images by dragging and dropping them into the comment box. I do want to make sure this issue gets doccumented appropriatly and I think we will get a quicker solution and doccumentatio through Support so I'm going to have to you go over there for this. 


I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by Mike-Crowley** [comment]
Thanks, but I don't have a technical issue. I am stating that the documentation is wrong. Thanks for the info on adding an image:
![untitled](https://user-images.githubusercontent.com/6467813/46112401-969fd300-c1b8-11e8-8480-131d9a57cdbc.png)

**Comment by AndreaBarr** [comment]
@Mike-Crowley Your welcome for the information. 

I am sorry I misunderstood you. I will get this investigated and the document updated. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by nenonix** [comment]
@Mike-Crowley  Thank you for contributing to MS docs. I need to investigate this issue and then I will work with you to improve the content.

**Comment by dariomws306** [comment]
Hi @Mike-Crowley , but if you click on "Find someone or dial a number" and write something, you should get the Skype directory tab, shouldn't you?
And I think it's the screenshot in the article. What do you think?
Thank you!

**Comment by scanum** [comment]
@dariomws306  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@Officedocsbot close
