### ISSUE TITLE
Does this work with Exchange On-Premises as well?

### ISSUE THREAD

**Issue by gojo119** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8086]
Hi,

I couldn't find any official statement, so I wonder if "Share to Teams" is working when the user's mailbox is hosted on Exchange On-Premises? 
As the article states "_Share to Teams uses the same transport mechanism as when a user emails a channel._" I would assume yes because emailing to a channel works for users with an on-premises mailbox as well.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
