### ISSUE TITLE
Missing some important information from the page

### ISSUE THREAD

**Issue by dsgnethu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8088]
Dear Microsoft,

I'm missing 3 important pieces of the documentation:

1. Does the "Attendance Report" setting work retroactively (meetings already happened in the past)?
2. Does the "Attendance Report" setting work for meetings that are already created / scheduled, but they will happen in the future? In other words, do we need to re-create existing meetings to be able to get the "Attendance Report" or not?
3. How the above 2 questions work in the case of recurring meetings?

Thanks if you will extend the documentation with the answer of the above questions.

Levente Luksa
Caresyntax
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a8b1087-ae40-6813-16bc-a69c90e50d19
* Version Independent ID: b808e843-80d8-4a96-c6ed-e8175968eb73
* Content: [Microsoft Teams meeting attendance report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/meeting-attendance-report)
* Content Source: [Teams/teams-analytics-and-reports/meeting-attendance-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/meeting-attendance-report.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @dsgnethu, thank you for your feedback.

An attendance report is generated for all meetings. The only thing you can change is if the organizer can download them or not.
To answer your questions, once you enable engagement report for an organizer/user:

1. Yes.
2. Yes. No, the user/organizer doesn't need to recreate meetings
3. The user/organizer will be able to download engagement reports for any occurrence with some details:
https://support.microsoft.com/office/view-and-download-meeting-attendance-reports-in-teams-ae7cf170-530c-47d3-84c1-3aedac74d310

**Comment by dsgnethu** [comment]
Hi Dario,

Thanks for your answers. Also this article is very useful.

Levente

Dario Woitasen ***@***.***> ezt írta (időpont: 2021. nov. 3.,
Sze, 10:48):
