### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jason-nyc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8089]
This is backward:

> The default location is C:\Program Files (x86)\Teams Installer on 64-bit operating systems and C:\Program Files\Teams Installer on 32-bit operating systems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Teams using Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@jason-nyc thank you for reaching out and helping to improve Microsoft Docs. Please can you clarify where the typo is and I'll have it fixed.

**Comment by jason-nyc** [comment]
I believe it should say

The default location is C:\Program Files (x86)\Teams Installer on 32-bit operating systems and C:\Program Files\Teams Installer on 63-bit operating systems.
