### ISSUE TITLE
"Known Issues for Teams" does not include link previews sometimes not showing

### ISSUE THREAD

**Issue by aaron-ni** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#809]
"Known Issues for Teams" (under Manage > Troubleshoot and Support) does not include the fact that previews for hyperlinks sometimes do not show. This appears to be site-based or page-based rather than an intermittent issue in Teams itself. For instance, https://blazor.net/ does not show a preview in Teams.

**Comment by AndreaBarr** [comment]
@aaron-ni Thank you for this feedback

I want to make sure this gets investigated and the document updated. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by aaron-ni** [comment]
Thanks for the update!

**Comment by get-itips** [comment]
Hi @aaron-ni Thanks for your comment!
That known issue has been added to the article https://docs.microsoft.com/en-us/microsoftteams/known-issues under the title "URL preview may not show for all URL's "
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @aaron-ni 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
