### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by severrol-msft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8090]
Hello,

The cmdlet on line 12 is not good !

powershell -executionpolicy unrestricted c:\Rigel\x64\scripts\provisioning\**scriptlaunch.ps1** **ApplyCurrentRegionAndLanguage.ps1**.

**ApplyCurrentRegionAndLanguage.ps1** do not exist in folder.

Could you please correct, please ?

KR
Seb

.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/console?source=docs)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @severrol-msft 
How are you?
Is your MTR console created using Creators update as the article says?

>The following instructions work only for consoles created using Windows Creator's Update. Legacy/in-market systems that have not been set up using media with the new provisioning system will not be able to use these instructions, but should also not suffer from the initial issue that requires this manual intervention (Anniversary Edition let you pick your app language explicitly as part of setup).

Thanks for clarifying,
