### ISSUE TITLE
Incorrect maximum value for TMR expiration period in days

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8092]
The documentation states 9,999 as max value whereas the `Set-CsTeamsMeetingPolicy` cmdlet documentation of attribute `NewMeetingRecordingExpirationDays` states 99,999 as max value.

[Teams cloud meeting recording > Frequently asked questions](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording#frequently-asked-questions)
> #### How can an admin change the expiration date?
> Admins can change the default expiration setting in PowerShell or the Teams admin center before the feature is released. 
> [...] 
>
> The expiration days value can be set as follows:
> - Value can be from 1 to **_9,999_**.
> - Value can also be -1 to set TMR to never expire.

[Set-CsTeamsMeetingPolicy > Parameters: NewMeetingRecordingExpirationDays](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps#parameters)
-NewMeetingRecordingExpirationDays
Specifies the number of days before meeting recordings will expire and move to the recycle bin. Value can be from 1 to 99,999 days. Value can also be -1 to set meeting recordings to never expire.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
