### ISSUE TITLE
Outdated information

### ISSUE THREAD

**Issue by ficzagergo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8094]
Hi!

There is no "Org-wide settings" in Microsoft Teams admin center. Please review this article.
The mentioned external access now is under the Users menu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9b7f77-061d-a224-ff1c-8d3e15d21221
* Version Independent ID: 00fa9550-c4c4-3398-ffbb-271cc724048f
* Content: [Manage settings for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/enable-features-office-365)
* Content Source: [Teams/enable-features-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enable-features-office-365.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
The article has already been updated to reflect the changes. Thanks for your feedback
@scanum please close
