### ISSUE TITLE
PowerShell no longer valid

### ISSUE THREAD

**Issue by rmichalskinw** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8095]
Attempting to run PS as stated in the document results in the following error: 

```
Exception calling "GetSteppablePipeline" with "1" argument(s): "The expression after '&' in a pipeline element produced an object that was not valid. It must result 
in a command name, a script block, or a CommandInfo object."
At C:\Users\RyanMichalski\OneDrive - Nuwave Communications, 
Inc\Documents\WindowsPowerShell\Modules\MicrosoftTeams\2.6.0\net472\exports\ProxyCmdletDefinitions.ps1:75556 char:9
+         $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvoc ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RuntimeException
```
PS pulled from article: 

```
C:\> $content = Get-Content "C:\tmp\customMoH1.mp3" -Encoding byte -ReadCount 0
C:\> $AudioFile = Import-CsOnlineAudioFile -FileName "customMoH1.mp3" -Content $content
C:\> $AudioFile
```

**Comment by rmichalskinw** [comment]
```
Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.6.0                MicrosoftTeams                      PSGallery            Microsoft Teams cmdlets module for Win...
```

**Comment by rmichalskinw** [comment]
Issue appears to be only with Version 2.6.0 - downgraded to 2.2.5 and ps ran properly. 

`2.2.5                PowerShellGet                       PSGallery            PowerShell module with commands for di`

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @rmichalskinw, thank you for your feedback.

Could you kindly share the article you are referencing? Thanks!

**Comment by rmichalskinw** [comment]
https://docs.microsoft.com/en-us/microsoftteams/music-on-hold

**Comment by dariomws** [comment]
@rmichalskinw, I tested it and worked for me:
![image](https://user-images.githubusercontent.com/33589238/140276565-2fb74a79-186b-4d7a-80ed-015e60e289f9.png)

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by rmichalskinw** [comment]
@dariomws it appears to be an issue with how PowerShell was running - OneDrive was settings itself to the default application instance causing an issue when trying to upload the file. Once I killed off OneDrive everything worked without issue. I have a ticket open with MS regarding how PS chooses it's pathing when there are modules installed in two places. 

This can now be closed - thank you.
