### ISSUE TITLE
Forwarding to a calling group from a resource account supported? Unclear from documentation...

### ISSUE THREAD

**Issue by dsp76** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8096]
Its unclear from the documentation, if "resource accounts" can also have forwarding to calling groups and how its set up for them? (Use Case: Having the main number assigned to a "resource account" and forward them to a group of teams users)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a82f953e-22d5-e4af-71e2-4ed4e9d0550a
* Version Independent ID: f6a80581-d145-f2d4-5ae2-95f7faac4aaa
* Content: [Call sharing and group call pickup - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/call-sharing-and-group-call-pickup)
* Content Source: [Teams/call-sharing-and-group-call-pickup.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/call-sharing-and-group-call-pickup.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@dsp76 thank you for reaching out and helping to improve Microsoft Docs. I'm investigating this, but in the meantime I found this information in the tech community chat https://techcommunity.microsoft.com/t5/teams-developer/resource-account-do-not-show-in-forwarding-rules-in-teams/m-p/1308492
