### ISSUE TITLE
No need to add presenter as guests in the tenant, if the setting "anonymus presenter ist active

### ISSUE THREAD

**Issue by ediordna** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8097]
[Enter feedback here]
Feedback for:  https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events#guest-to-present
No need to add presenter as guests in the tenant, if the relatively new setting "anonymus presenter" ist active.
![grafik](https://user-images.githubusercontent.com/37675274/140037763-37c612e0-4ad1-4526-a8b0-43f31f9d2f19.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@ediordna thank you for reaching out and helping to improve Microsoft Docs. I see this article was updated yesterday. Please can you let me know if there is still something that needs to be amended in the article and I'll look into having it changed.

**Comment by ediordna** [comment]
Hi @lindspea , sorry i oversaw your com,ment. I just looked into the article and the info-box: "Important
Non-authenticated anonymous users can't be invited as producers or presenters in Teams live events." is wrong. This is possible with the anonymous presenter option. Thus the above explanations have to be changed as well.
Best regards
