### ISSUE TITLE
Clarify metrics / How to identify inactive Teams? 

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8098]
I'm trying to identify inactive Teams in my tenant, but a couple of the metrics on this report are confusing.  Can you help clarify these? 

The way 'Active Users' is defined, am I understanding correctly that if a user is active in the Teams app at all, they will be counted as an active user of every team that they are a member of?  So just because a team has 'active users' it doesn't mean that anyone actually interacted with the team in any way, is that right? 

What is the Last Activity date based on?  I ask because I have teams with Active Users and Active Channels listed, but zeroes listed in every other metric on the report, yet they show a last activity date within 24 hours. What sort of activity would be occurring that isn't shown in this report? 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b138331-2f10-a05d-7e88-68e62e0b3e4f
* Version Independent ID: f923b648-ffe4-8a8a-c189-6e31f1032c10
* Content: [Microsoft Teams usage report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-usage-report)
* Content Source: [Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @NeighborGeek Steve, how are you?
I could get this information

About last activity date and what is based on

> Other activity tracks when the user is considered active but has a value of zero for chat messages, 1:1 calls, channel messages, total meetings, and meetings organized. Examples actions are when a user opens a channel message post but doesn't reply to it or when a user receives a private message and reads it but doesn't respond to it.

About active user

> Active user	Measures the number of unique users who perform an action in Teams during the specified date range.

Source https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report

Hope this answers your question

**Comment by get-itips** [comment]
@scanum
