### ISSUE TITLE
How to see what Interop policy is currently assigned to someone?

### ISSUE THREAD

**Issue by webash** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#81]
There doesn't appear to be a way to pull the InteropPolicy for a user who already has one set... where do we see this?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8354e80d-02da-7f51-a713-e698322e8ec1
* Version Independent ID: ef42d9af-336a-e014-de0a-b7bf7bb1f87d
* Content: [Quick start guide - Configuring Calling Plans in Microsoft Teams](https://docs.microsoft.com/en-gb/MicrosoftTeams/configuring-teams-calling-quickstartguide)
* Content Source: [Teams/configuring-teams-calling-quickstartguide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/configuring-teams-calling-quickstartguide.md)
* Service: **msteams**
* GitHub Login: @arachmanGitHub
* Microsoft Alias: **MyAdvisor**

**Comment by LolaJacobsen** [comment]
@arachmanGitHub Can you respond to this comment please?

**Comment by arachmanGitHub** [comment]
hi @webash, you can grant $null policy for the intended user to remove the interop policy applied to a user. Example: Grant-CsTeamsInteropPolicy -Identity user@contoso.com -PolicyName $null

**Comment by webash** [comment]
Maybe it's worth adding that as an example?

Also, it's not clear that you need to use Get-CsOnlineUser to see the existing Interop Policy, so can I recommend adding that as a related command?

**Comment by arachmanGitHub** [comment]
Great feedback @webash, I'll make sure the suggestions are accommodated in the next update of the article.

**Comment by rrgonzalezz** [comment]
Has the cmdlet New-CsTeamsInteropPolicy been removed from the SfB Online module? What is then the alternative to create new custome Teams Interop policies?

I cannot create a new custom Teams Interop Policy as described in the guide. Whenever I try to create a new Teams Interop Policy I get the following error message: "New-CsTeamsInteropPolicy : The term 'New-CsTeamsInteropPolicy' is not recognized as the name of a cmdlet, function, script file or operation program."

Additionally, I do not see the cmdlet listed under the Skype PowerShell reference: https://docs.microsoft.com/en-us/powershell/module/skype/?view=skype-ps

However, the cmdlets Get-CsTeamsInteropPolicy and Grant-CsTeamsInteropPolicy are available and work.

**Comment by arachmanGitHub** [comment]
@rrgonzalezz I believe your question has been answered in the different thread. To sum up, we're in the process of retiring TeamsInteropPolicy and you need to use the pre-canned instances moving forward:

• DisallowOverrideCallingDefaultChatDefault
• DisallowOverrideCallingSfbChatSfb
• DisallowOverrideCallingTeamsChatTeams
