### ISSUE TITLE
Anonymous access not well defined

### ISSUE THREAD

**Issue by jmitrofan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8100]
Hello,

I noticed during testing that if I disable anonymous access in the Teams Admin Center, both external and guest users will not be able to join Teams meetings. I suggest this would be updated to reflect this.

If we check the documentation - https://docs.microsoft.com/en-us/microsoftteams/non-standard-users#:~:text=An%20anonymous%20user%20is%20a%20concept%20in%20Teams,users%20Install%2C%20update%2C%20and%20delete%20for%20guest%20users - it is specified an anonymous user is considered to be someone hasn't logged in with their Microsoft or organization’s account, which would not be the case in the case of guests from another O365 tenant.

Thank you,
Julia 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Manage meeting settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-mahoffman**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @jmitrofan Julia,

I tried to reproduce on my lab tenant and I couldn't, when I disabled anonymous access as the article says, only anonymous people could not enter the meetings.

Thank you

**Comment by get-itips** [comment]
@scanum please close
