### ISSUE TITLE
Cannot connect to YouTube

### ISSUE THREAD

**Issue by leciadillard** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8101]
[Link to YouTube - says "Cannot connect to YouTube"]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eba12367-7fe2-b316-3049-48aec995e112
* Version Independent ID: acca35eb-c728-a728-b731-eada916c43a2
* Content: [Understand teams and channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-adoption-understand-teams-and-channels#feedback)
* Content Source: [Teams/teams-adoption-understand-teams-and-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-adoption-understand-teams-and-channels.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-mahoffman**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback! @leciadillard
