### ISSUE TITLE
No list of operators on "Plan Operator Connect" page.

### ISSUE THREAD

**Issue by tfuto** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8103]
[Enter feedback here]

Arrived from: [this page](https://docs.microsoft.com/en-us/microsoftteams/cloud-voice-landing-page)

Says:
> "For information on the benefits and requirements of Operator Connect, and for a list of operators participating in this program, see Plan Operator Connect."

Click through arrived at: [this page](https://docs.microsoft.com/en-us/microsoftteams/operator-connect-plan)

Error: **Has no list of operators.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30fbee95-7a4d-7e50-efb2-52726553229c
* Version Independent ID: 60136744-9919-50a1-c371-d3e467700922
* Content: [Operator Connect - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/operator-connect-plan)
* Content Source: [Teams/operator-connect-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/operator-connect-plan.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by cazawideh** [comment]
There's a link to the list of operators in the Plan for Operator Connect topic. Plan your Teams voice solution will be updated to reflect this.
