### ISSUE TITLE
Incorrect contact method for PTN Team

### ISSUE THREAD

**Issue by jaredburnett** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8104]
Article still has the email listed for PTN but that has been retired per https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization/contact-tns-service-desk

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a66b7b69-64a8-b3c1-e36f-a6546581ce0d
* Version Independent ID: dbc63349-f0d3-31e1-2d49-b2fb86150e74
* Content: [Port phone numbers to Business Voice - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/business-voice/port-phone-numbers)
* Content Source: [Teams/business-voice/port-phone-numbers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/business-voice/port-phone-numbers.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @jaredburnett thanks for your feedback!
