### ISSUE TITLE
The Windos Mobile app mentioned in the article is not found in the store

### ISSUE THREAD

**Issue by Aniel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#811]
>The Microsoft Teams mobile apps are available for Android, iOS, and Windows Phones, and are geared for on-the-go users participating in chat-based conversations and allow peer-to-peer audio calls. For mobile apps, go to the relevant mobile store for Google Play, Apple App Store, and Microsoft Store.

Searching the Windows Store on my Lumia 950XL for Microsoft Teams returned only third-party apps that have nothing to do with Microsoft Teams. Is the App for Windows Mobile abandoned? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients#mobile-clients)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@Aniel I use an android and I had to search for just Teams for it to pull up. Try this link I found on the microsoft store for it. I found It on a pc so no garuntee that it's the right one but might help point to the correct link for you.  https://www.microsoft.com/en-us/p/microsoft-teams-for-surface-hub/9pczm4lgf8s6#activetab=pivot:overviewtab

**Comment by Aniel** [comment]
@AndreaBarr unfortunately the link points to the app vor the Surface Hub. 

I found an support [article](https://support.office.com/en-us/article/Microsoft-Teams-on-mobile-devices-2ACBCF73-8FD4-4929-9B31-AE403B88C2D3) that states that it is available.

Over a Windows Central [article](https://www.windowscentral.com/microsoft-teams-app-now-available-windows-10-mobile) I found the [link](https://www.microsoft.com/en-us/p/microsoft-teams/9nblggh4n9tw?ocid=AID681541_aff_7593_159229&tduid=%28ir_5667e1b2N3a2cf6a86f45b49b0040c888%29%287593%29%28159229%29%28%29%28UUwpUdUnU44670%29&irgwc=1&irclickid=5667e1b2N3a2cf6a86f45b49b0040c888#activetab=pivot:overviewtab) to the mobile app in the store. The problem I cant install it and it says: `Microsoft Teams is currently not available.`

So either the support article and documentation is outdated and the app is abandoned or there is a problem with the store distribution. 

@AndreaBarr  do you know to whom I need to reach out to get a clear message if I can use my **Microsoft** phone to use **Microsoft** Teams or if I need to go with a competitor to Teams that has a mobile app for Windows Mobile like [Slack](https://www.microsoft.com/en-us/p/slack-beta/9nblggh1jj9h#activetab=pivot:overviewtab).

**Comment by AndreaBarr** [comment]
@Aniel If it says Teams is currently not available contact support. It should be available from everything I know. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by Aniel** [comment]
Hello @AndreaBarr 

as i feared the Windows Mobile App is abandoned. I made a pull request ([827](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/827))  to the article mentioned to make it more clear for customers.

I received the following information from the service ticket:
https://support.microsoft.com/en-us/help/4230833/windows-phone-app-for-microsoft-teams-is-retiring

**Comment by AndreaBarr** [comment]
@Aniel Thank you for keeping us updated on this and also submitting a pull request.
