### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8112]
This section needs clarification on the definition of what an account is that isn't managed by an organization.

https://docs.microsoft.com/en-us/microsoftteams/manage-external-access#block-unsolicited-contact-with-external-unmanaged-teams-users

Is this specifically and only referring to Teams consumer (personal) accounts? Does this include work accounts that signed up for Teams without their organizations consent and management of the tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external access (federation) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @danmyhre, thank you for your feedback.

External Teams users whose accounts are not managed by your organization are user accounts that are not added to your Azure AD directory. You can have only two types of users in your Azure AD directory: members or guests. Others are external users whose accounts are not managed by your organization.

Hope it helps.

**Comment by danmyhre** [comment]
It doesn't say "your" organization. It says "an" organization. Also, I am testing having this setting "People in my organization can communicate with Teams users whose accounts aren't managed by an organization." set of OFF, and I can still send messages to external Teams users who are not in my AAD.

**Comment by dariomws** [comment]
@HowlinWolf-92, could you kindly help here? Does this refer to Teams for personal use? Thanks!

**Comment by HowlinWolf-92** [comment]
These are what's called "Teams for Life" account. The product managers told me not to use that term, though, and they didn't use it in the UI. See the attached
![Feature_screenshot](https://user-images.githubusercontent.com/91981398/141521942-55f92d77-3a67-440a-800e-e398b3fd2272.png)
.

**Comment by HowlinWolf-92** [comment]
@SerdarSoysal, the reviewers here are confused by this feature. What should we do here to simplify this?

**Comment by danmyhre** [comment]
So it sounds like this is specifically referring to Teams personal - meaning connected to an MSA, not a work account. Is that right?

Is this feature getting ready for this?
https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=teams%2Cpersonal%2C88381

**Comment by HowlinWolf-92** [comment]
@Sivaprakash Saripalli should know the answer to that.
sivsarip@microsoft.com

**Comment by HowlinWolf-92** [comment]
@danmyhre Please take a look at this preview article and tell me if it's clearer:

- [https://review.docs.microsoft.com/en-us/MicrosoftTeams/manage-external-access?branch=hoffman-manage-external-access](https://review.docs.microsoft.com/en-us/MicrosoftTeams/manage-external-access?branch=hoffman-manage-external-access)

**Comment by danmyhre** [comment]
I don't have access to that

**Comment by JeremyTBradshaw** [comment]
@scanum how is this closed and why is there no explanation.  There have been other issues for the same concern which have been closed because this issue is already here about the topic.  It's still perfectly unclear what this means.  Please re-open.
