### ISSUE TITLE
Limitations?

### ISSUE THREAD

**Issue by cchambers-cap** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8119]
Are there limitations that are not listed in this article? For example, does this only work on Windows based Teams Rooms and not Android based room systems? I've followed the instructions but do not see the options in the settings in Step Three to enable Zoom or WebEx meetings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c62081e-2421-80b9-8ba9-aaf8fd55e432
* Version Independent ID: 5df3c5e5-978f-cfa7-9e5c-3cd7f65fa8ff
* Content: [Enable Teams Rooms devices to join third-party meetings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/third-party-join)
* Content Source: [Teams/rooms/third-party-join.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/third-party-join.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @cchambers-cap that feature is called Direct guest join as the article says, and you can see here https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/teams-devices-feature-comparison the status of that feature for MTR Android
Hope this helps you,

**Comment by cchambers-cap** [comment]
Thanks! do you know if theres a roadmap number for that feature on Andriod so I can track the release?
________________________________

**Comment by get-itips** [comment]
> Thanks! do you know if theres a roadmap number for that feature on Andriod so I can track the release?

you can find it with these search terms

https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=direct%2Cguest

**Comment by get-itips** [comment]
@scanum please close
