### ISSUE TITLE
New location for Teams Scoped Directory Search

### ISSUE THREAD

**Issue by tylerwb15** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8120]
Now that the Org-Wide settings are gone, can you please update this page with the location to find the setting for Teams Scoped Directory Search in the Teams Admin Center, if applicable, or the current approved method.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84066c98-38a4-e59a-893f-da38a4a11bf3
* Version Independent ID: 890a4978-0e9b-2691-a2ab-8b5512e5e76f
* Content: [Use Microsoft Teams scoped directory search - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-scoped-directory-search)
* Content Source: [Teams/teams-scoped-directory-search.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-scoped-directory-search.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Thanks for your feedback!
