### ISSUE TITLE
Automatic Conversion of mode

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8122]
https://docs.microsoft.com/en-us/MicrosoftTeams/information-barriers-in-teams#information--barrier-modes-and-teams

It should be added that if a Team is currently in Open mode (only contains users that are unsegmented), if any segmented users are added, the team group is automaticlly converted to implicit mode. All unsegmented users will lose access to all files for the Team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85a288bc-9192-8c65-4ce9-b5abb260206e
* Version Independent ID: 1f953ea6-e6e5-5e71-d541-3962637f25f9
* Content: [Information barriers in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/information-barriers-in-teams)
* Content Source: [Teams/information-barriers-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/information-barriers-in-teams.md)
* Service: **msteams**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by get-itips** [comment]
Hello @danmyhre Dan, I am looking into this. Thanks for your feedback.

**Comment by get-itips** [comment]
@danmyhre Dan, please see https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/8389#issuecomment-1025961587
Closing @scanum
