### ISSUE TITLE
Manage porting PIN is no longer part of TAC

### ISSUE THREAD

**Issue by scdaugherty** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8134]
Manage porting PIN is no longer part of TAC.  It is now required to open a case to prepare for porting numbers out of Teams.  Please update documentation to reflect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a17293e0-4c49-0e97-d5da-b48322f10928
* Version Independent ID: c38c0726-5dec-d374-6948-2188d43025ef
* Content: [What's a port order? - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/phone-number-calling-plans/port-order-overview)
* Content Source: [Teams/phone-number-calling-plans/port-order-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phone-number-calling-plans/port-order-overview.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
