### ISSUE TITLE
Why removed "License can be revoked after the domain activation (it can take up to 24 hours)"?

### ISSUE THREAD

**Issue by shtakeda** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8135]
Why removed "License can be revoked after the domain activation (it can take up to 24 hours)" under "Active the subdomain"?
My customers have already revoked the license from the user. They worry whether they have to reassign the license to the user, or  any issues happen if they keep revoking the license.  
Can you write it back, if there are no technical or license issues? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure Session Border Controller - Multiple tenants - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants#activate-the-subdomain-name)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @shtakeda 
How are you?
Digging into the commit that made that change, there is this description for the update:

>remove note about it being ok to remove user license. this was not sanctioned by provisioning team and is not supported going forward.

Ref commit: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/135f832428f76e6dd77ee536399ef5169b3dde46#diff-b2c0715675b60bd58a04cfa4c550ee165b2a5eaffad457f0a154cce34fae1301

Hope this information helps you,
