### ISSUE TITLE
Global policies vs Guest users

### ISSUE THREAD

**Issue by jflek** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8138]
Please update the article how Global policies affect Guest users.
Thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888fe05b-1160-452f-90ba-deb19adb740f
* Version Independent ID: 4091c5e4-7a90-7fe4-2741-16bbb1f297c1
* Content: [Assign policies to your users in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/assign-policies#feedback)
* Content Source: [Teams/assign-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-policies.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@jflek thank you for reaching out. I'll do some research to have the correct information added. In the meantime is there any article link in particular that you are referring to that could be added to this document?
