### ISSUE TITLE
Clarify difference between Auto Attendant system commands * & #

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8139]
> 

Auto-Attendant (AA) menu commands. Please clarify difference between * and #, as they both seem to just repeat the current menu. i.e. # does not got back to the previous AA menu as current doco suggests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a42f9e2c-aeee-76c4-620a-668cce21ba10
* Version Independent ID: 6ff06eab-9c80-9c30-95ef-c17e157fbea1
* Content: [Set up an auto attendant for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/create-a-phone-system-auto-attendant?WT.mc_id=TeamsAdminCenterCSH#greetingsandrouting)
* Content Source: [Teams/create-a-phone-system-auto-attendant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-auto-attendant.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
