### ISSUE TITLE
AlternateSecurityIDs should be AlternativeSecurityIds. 

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#814]
In the referenced troubleshooting guide, Tushar Pathak writes about the AlternateSecurityIDs attribute, but this is a typo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams Guest Access checklist](https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @romanma
* Microsoft Alias: **romanma**

**Comment by AndreaBarr** [comment]
@Mike-Crowley Thank you for catching this. I will make sure this gets updated. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by lindspea** [comment]
@Mike-Crowley Thanks for pointing this out and for your contribution.  I will investigate the issue to correct the typo.

**Comment by lindspea** [comment]
@David-Rosenthal please can you have a look at the troubleshooting guide in the blog from Tushar Pathak. @Mike-Crowley mentions a typo in there in his message above.

**Comment by David-Rosenthal** [comment]
I only cover Teams in Gov :) The PM for Guest Access is @somakbhattacharyya

**Comment by lindspea** [comment]
@somakbhattacharyya could you please assist with above issue.

**Comment by yogkumgit** [comment]
@lindspea  Thank you very much for the contribution and following with bog owner. @Mike-Crowley  Blog owner has confirmed that he will update this typo. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
