### ISSUE TITLE
Dutch content is out-of-date compared to English content

### ISSUE THREAD

**Issue by rdekramer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8140]
Could the contents of this Dutch page https://docs.microsoft.com/nl-nl/microsoftteams/limits-specifications-teams be updated to bring it in line with the English version of the same page https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams ?

Thanks in advance,
Remco

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@rdekramer Thank you for the feedback!

@OfficeGlobal Could you kindly help with this issue? Thanks!

**Comment by cdowling1971** [comment]
@rdekramer Thanks for reporting this problem, I have logged an internal case/ticket, and we will continue to follow up internally.

**Comment by cdowling1971** [comment]
@rdekramer Dutch content was accidentally published this has been rectified now to show the English page, thanks again for reporting this issue. FYI @TinaMcN

**Comment by tiburd** [comment]
@scanum
