### ISSUE TITLE
Please make Shifts available for guests

### ISSUE THREAD

**Issue by jasonwalks** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8141]
Please make shifts available for shifts as well. The current policy of making it available to members of an organization is way too limited, considering how basic and necessary the feature is. Part-timers, for example, is not officially affiliated with an organization who nevertheless need to work in shifts in collaboration with other members of an organization. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58ea9573-59b1-1499-fb83-517d0ee0f034
* Version Independent ID: bf98f739-ff51-0b90-dbc5-c594d3dacecd
* Content: [Manage the Shifts app for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams)
* Content Source: [Teams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
