### ISSUE TITLE
Microsoft Teams Disable Auto Launch

### ISSUE THREAD

**Issue by randemhero** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#815]
Hello,
I need to deploy teams to over 800 computers without it Auto deploying
I am looking at https://docs.microsoft.com/en-us/microsoftteams/msi-deployment#disable-auto-launch-for-the-msi-installer
and the documentation shows to use the following command
msiexec /i Teams_windows.exe OPTIONS="noAutoStart=false"
I have tried this and it does not work
First thing that points out to me is that its a .exe so I tried using the .msi and I reboot and it will still Auto launch
I have tried multiple installs and uninstalls but am unable to figure out why this setting does not work
Are you able to let me know?

Regards

**Comment by AndreaBarr** [comment]
@randemhero Thank you for this feedback

I an unsure why this is not working, it should. I want to make sure this gets addressed and investigated properly. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
