### ISSUE TITLE
Exchange connection method references basic authentication

### ISSUE THREAD

**Issue by yllekz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8152]
The method documented in this article to connect to Exchange Online is using a method that utilizes Basic Authentication which is going away soon.

It should be updated to utilize the new [Exchange Online PowerShell Module](https://docs.microsoft.com/en-us/powershell/module/exchange/connect-exchangeonline?view=exchange-ps) method of connecting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee417633-3d52-646b-2ef0-94f71535db75
* Version Independent ID: 527bb7f0-b4a7-108c-6f86-8fadced63b86
* Content: [Deploy Microsoft Teams Rooms with Exchange Online - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-exchange-online)
* Content Source: [Teams/rooms/with-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-exchange-online.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
@yllekz, the article was replaced by another one:
https://docs.microsoft.com/microsoftteams/rooms/with-office-365

@scanum, this issue can be closed.
