### ISSUE TITLE
Activity Log is not appearing as an option

### ISSUE THREAD

**Issue by evilsizorm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8153]
[Enter feedback here]

---
#### Document Details
The instructions on this page say
1. In the Teams Admin center
2. Click on Home
3. You will see Activity Log
4. Click on Detail to see recent policy assignments

Earlier today I edited our Global Default policy for Teams Meetings.
But I do not see Activity Log on my Teams Dashboard/Home.  The closest I see is Team user activity, and when I click View Detail, it does not appear to have a report of policy changes.

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22995067-f8fb-45d1-f68b-7e66fc155ec4
* Version Independent ID: 341abea2-00c5-e037-72de-dab0f73d9726
* Content: [View your policy assignments in the Activity log in the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/activity-log)
* Content Source: [Teams/activity-log.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/activity-log.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by HowlinWolf-92** [comment]
Activity log is there, but you have to scroll down on the right to see it. See the attached screenshot.

**Comment by evilsizorm** [comment]
Here is what my Teams admin Dashboard looks like, there is no widget for Activity Log
![Screenshot 2021-11-17 105703](https://user-images.githubusercontent.com/5598657/142246161-f6e05435-c5d5-454b-a2f5-e08b52770b3a.png)

**Comment by HowlinWolf-92** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
