### ISSUE TITLE
Tag change notifications

### ISSUE THREAD

**Issue by GitRomney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8154]
(See full explanation of the issue here: https://techcommunity.microsoft.com/t5/microsoft-teams/teams-tags-ms-roadmap-feature-81803-more-information/m-p/2810747)

This page doesn't include any information about how to receive notifications for tag membership changes. According to the Microsoft Roadmap, Feature [81803](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters&filters=General%20Availability%2CWorldwide%20(Standard%20Multi-Tenant)&searchterms=81803), the feature to receive notifications for tag membership changes is launched. This is a great article with a lot of information about tags, so hopefully you can get specifics about notifications to add here.

Thank you!
Joel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b16e659e-cf07-268a-e224-fa444749ac29
* Version Independent ID: ee822a8d-b331-998f-e336-b1fa510f35c0
* Content: [Manage tags in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-tags)
* Content Source: [Teams/manage-tags.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-tags.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by get-itips** [comment]
Hello @GitRomney I am looking into this.

**Comment by tiburd** [comment]
@anniecolonna 
Hi, Annie,

Can you please help resolve this?

Thank you!

**Comment by get-itips** [comment]
Hello @GitRomney 
We could dig into this, the notification feature of tag changes is still rolling out per regions, so that is probably the reason why you still do not see it in your tenant.
I was told that the roadmap item will be updated.
Hope this information helps you,
Thank you

**Comment by GitRomney** [comment]
To clarify, are you saying that the status of “Launched” is not accurate and is going to be changed back to “Rolling Out” on the Roadmap? Will information about that feature be added to the support document after launch?

Thank you!

**Comment by get-itips** [comment]
@GitRomney I am sorry, I am afraid I do not have exact details about the roadmap item changes however if, from the roadmap item a change is needed in the document, I'll propose it thru a PR. Thank you
