### ISSUE TITLE
Inbound Call Caller ID and Call Queues

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8156]
Inbound caller ID lookup seems to work for direct inbound calls by correctly displaying a Teams Speed Dial contact, yet same caller calling in via a Call Queue does not work, it just displays the PSTN number (Tested on latest Windows Teams app, Web Teams and Yealink VP59. It does work on Android Teams Appthough). 
Is this design or bug? please specify in doco to set correct expectations in the inbound Call ID section as it is not specific

Many Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2b8aefb-f373-fa6e-dd79-e97cded117e8
* Version Independent ID: 2c73f49c-d34f-c1da-648d-8675f10c0183
* Content: [Manage caller ID policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/caller-id-policies)
* Content Source: [Teams/caller-id-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/caller-id-policies.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
@SvenBell, thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by SvenBell** [comment]
Thank you for update. I have logged a call via Microsoft Premier Support and will advise outcome...
