### ISSUE TITLE
Are you sure if the page contains valid information?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8158]
Hi,

The logging on Teams is one of the biggest challenge. And in my mind this page is not up to date.

Steps:
1. On Teams client "Enable logging for meeting diagnostics (requires restarting Teams)" was market as unchecked.
2. Four fingers pray: Shit + Ctrl + Alt + 1 (this is much better sequence for your fingers than what you have on the page)
3. I'm getting a folder under downloads:
![image](https://user-images.githubusercontent.com/43988151/142211838-8eeab679-6757-4061-ad67-037694338901.png)

4. Then I go to the settings, mark this "Enable logging for meeting diagnostics (requires restarting Teams)" as checked.
5. Quit for Teams client (as sign-out clears the setting).
6. Start Teams client, and verify the setting is still there.
7. Four fingers pray: Shit + Ctrl + Alt + 1 
8. I'm getting a new folder under downloads:
![image](https://user-images.githubusercontent.com/43988151/142211016-dd123922-3773-4527-a8f9-0ddf3042644a.png)

Both of these folders have the *.blog files under Meeting\Media-Stack

So could you clarify what are the facts today?

thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d5e6d3-b7e0-d79f-0dea-ed423186a157
* Version Independent ID: ec6e68aa-552f-ab45-3c8e-92eff526b173
* Content: [Use log files in troubleshooting Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/log-files)
* Content Source: [Teams/log-files.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/log-files.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by lindspea** [comment]
@Petri-X thank you for reaching out and helping to improve Microsoft Docs. I'm looking into this and will get back to you soonest.

**Comment by lindspea** [comment]
@Petri-X I'm still looking into this, but I see this article has been updated two days ago. Please can you have a look and see if anything still needs amending.

**Comment by Petri-X** [comment]
Hi @lindspea 
Yes, I noticed, but when I was testing I still could not see any differences if this was enabled or not. Same amount of files and folders.

**Comment by Petri-X** [comment]
:(
