### ISSUE TITLE
We need to include on this doc that "Open application in background" is not supported

### ISSUE THREAD

**Issue by rafatecoy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8170]
Hello!

I worked recently in a support case with a customer which he was facing issues with "Open application in background option" was not working at Teams. Neither openAsHidden = True was working.
After to engage Teams support team, we received a feedback that "Open application in background" and "Disabling launch at startup" are not supported for machine-wide installer on VDI environments.
This must be included on this document, because we don't have this information available on any Teams public documentation.
I found this one https://james-rankin.com/articles/microsoft-teams-on-citrix-virtual-apps-and-desktops-part-1-installing-the-damned-thing/#:~:text=Teams%20does%2C%20both%20in%20the%20user%20and%20Machine-Wide,full-screen.%20I%20think%20this%20is%20an%20important%20feature. which the user complains about same problem and suggest a non official workaround for this issue.

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @serdars
* Microsoft Alias: **v-mahoffman**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
