### ISSUE TITLE
Update to teams. 

### ISSUE THREAD

**Issue by A55imilat0r** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8175]
It is great that this knowledge article is available, however......

Can someone please pass this on to the product team?
"There should be some detection built into a Teams update to detect affected Hardware / Drivers and disable hardware acceleration by default."

It should not be up to Microsoft's customer sys admin to deploy community sourced fixes to their fleet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e7f4e46-0e6a-3d42-022d-b07fd17792b3
* Version Independent ID: 5217778e-130d-6bed-beb7-f3834331f8ed
* Content: [Hardware decoder and encoder driver recommendations - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/hardware-decoders-and-encoders)
* Content Source: [Teams/hardware-decoders-and-encoders.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hardware-decoders-and-encoders.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
