### ISSUE TITLE
Missing policy setting doco - Roles that have presenter rights in Meetings

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8178]
There seems to be missing documentation on this page for the following setting:

- Roles that have presenter rights in Meetings 

A note could also be added about default being Everyone (being a Presenter as opposed to just being an Attendee), as this means after being admitted to a meeting any Presenter (default is everyone) can then admit others which may not be desired (solution to this is for Organizer to Set Meeting Options on who can present to either Only Me or Specific people).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4521de2b-1aae-93de-ee1a-222146194700
* Version Independent ID: b4f9087c-e1a3-8b47-917c-7c294d46fcca
* Content: [Manage meeting policies for participants and guests - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/meeting-policies-participants-and-guests?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/meeting-policies-participants-and-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-participants-and-guests.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @SvenBell, thank you for your feedback.

Could you share a screenshot? I cannot see that setting in the Participants & guests section.

**Comment by SvenBell** [comment]
Teams has changed and improved so much in the last 12 months since I made this comment. I think this has been addressed in the interim with the addition of the link in section: 'Who can present in meeting' to 'Roles in a Teams meeting' - https://support.microsoft.com/office/c16fa7d0-1666-4dde-8686-0a0bfe16e019
