### ISSUE TITLE
final step: "just wait longer"

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#818]
I did all of the steps above and continued to get an error saying i was not authorized. looking at the troubleshooting guide revealed the tenant wasn't setup for external users, even after I enabled this. After several hours of troubleshooting, I went to bed, to come back the next day to find it works now. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams Guest Access checklist](https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @romanma
* Microsoft Alias: **romanma**

**Comment by AndreaBarr** [comment]
@Mike-Crowley Thank you for this feedback

Yeah sometimes it takes time for things to show enabled. I agree this should be stated in the article. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
