### ISSUE TITLE
Please correct and rephrase

### ISSUE THREAD

**Issue by ChristianJBergstrom** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8181]
["As of November 2021, admins can also control whether specific users or groups of users can let anonymous users join the meetings they organize. This per-organizer policy is more restrictive than and overrides the organization-wide anonymous user settings below that admins manage in the Teams admin center."

The more restrictive will be used, i.e. the organizer policy will not override the tenant-wide setting.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Manage meeting settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by HowlinWolf-92** [comment]
Please change to this:

"Admins can also control whether specific users or groups of users can let anonymous users join the meetings they organize. This per-organizer policy overrides the organization-wide anonymous user settings below that admins manage in the Teams admin center. The more restrictive setting will be used."

**Comment by ChristianJBergstrom** [comment]
Hey, thanks for the reply. Perhaps I wasn't clear enough, my apologies. If you scroll down on this page you get to this part with a much better description. The above is simply not true.

"Since both the organization-wide and per-organizer policies control anonymous join, the more restrictive setting will be effective. For example, if you don't allow anonymous join at the organization level, that will be your effective policy regardless of what you configure for the per-organizer policy. Therefore, in order to allow anonymous users to join meetings, you must configure both policies to allow anonymous join by setting the following values:"

-DisableAnonymousJoin set to $false
-AllowAnonymousUsersToJoinMeeting set to $true

**Comment by HowlinWolf-92** [comment]
Rewrite the second paragraph as:

"Through a per-organizer policy setting, admins can control whether specific users or groups of users can let anonymous users join the meetings they organize. The per-organizer and organization-wide policy settings both control anonymous join, and the more restrictive takes effect."

**Comment by ChristianJBergstrom** [comment]
I've never updated a page, if you're asking me to do it?

**Comment by HowlinWolf-92** [comment]
I'll do it.
