### ISSUE TITLE
Confirmation on process for using API to add sensitivity labels

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8182]
In the section Sensitivity labels aren't supported by Teams Graph APIs, PowerShell cmdlets, and templates it is mentioned that you need to create a group with sensitivity labels and then convert it to a Team.

Using Graph API I have successfully created a Team and then updated the Group to add the sensitivity label. 

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ede6de99-ead2-fdb1-22f4-8b8240829732
* Version Independent ID: ed36687a-c091-44e3-1d8e-1025d1209fec
* Content: [Sensitivity labels for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-gb/MicrosoftTeams/sensitivity-labels)
* Content Source: [Teams/sensitivity-labels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sensitivity-labels.md)
* Service: **msteams**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@nikki-c  I'm not sure whether you're asking if the statement "sensitivity labels aren't supported by Teams Graph APIs" is still true, or you're offering an alternative method of getting around the limitation.  The intent of the statement is that you can't use a single Teams Graph API to do this, and this limitation remains.

**Comment by nikki-c** [comment]
The article implies that you can only create a sensitivity label when creating a group and then you can Teamify the group. I wanted to show that you can add a sensitivity label to an existing Team. This is important as most organizations will create sensitivity labels after they have many Teams to they need a way to add sensitivity labels to existing Teams. Hope this is clearer

**Comment by cabailey** [comment]
@nikki-c  Thanks for clarifying.  I'll check with the PM whether she wants this added here.

**Comment by cabailey** [comment]
Because the target audience for this article is Teams admins, the PM didn't feel it was appropriate to add that alternative here, but thanks for leaving the tip for others:

We are just stating that you cannot update existing teams with a sensitivity label using a Teams API. If there is a great understanding of how groups and teams are connected (not necessarily the case for this article's target audience), sure, they can use Groups API to make the updates.
