### ISSUE TITLE
Which specific Power BI licenses needed

### ISSUE THREAD

**Issue by jiorblommaert** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8184]
Hello in the documentation it's mentioned the following "You can customize these query templates and distribute them to anyone in your organization who has a Power BI license and CQD admin permissions.". However which specific Power BI license is needed? Is it enough to use Power BI Free or does the user needs to have Power BI Pro?

**Comment by scanum** [comment]
@jiorblommaert Thanks for pointing this out, could you please link the document you are referring to? Thanks.

**Comment by jiorblommaert** [comment]
> @jiorblommaert Thanks for pointing this out, could you please link the document you are referring to? Thanks.
@scanum I'm referring towards following document: https://docs.microsoft.com/en-us/microsoftteams/cqd-power-bi-query-templates
In the beginning of the documentation the following sentence is mentioned "You can customize these query templates and distribute them to anyone in your organization who has a Power BI license and CQD admin permissions.". Some customers wants to know which specific Power BI license they need for this integration.

**Comment by get-itips** [comment]
Hello @jiorblommaert I am looking into this.

**Comment by get-itips** [comment]
Hello @jiorblommaert adjusting the article with the information I could get.

**Comment by ParkesJ** [comment]
There are a lot of ways to license users for Power BI (see here: https://docs.microsoft.com/en-us/power-bi/consumer/end-user-license) and technically you could make do with a free Power BI license provided that the organization has a Premium subscription and a user with a Power BI Pro license assigned shares the report with you. Without that Premium subscription, a free license won’t work and you’d need Pro licenses.

Given all the possible licensing combinations that customers may have with respect to Power BI that would satisfy the requirements for sharing the CQD Power BI templates, it isn’t feasible to make prescriptive statements on Power BI licensing in CQD's documentation.
