### ISSUE TITLE
MessageUpdated events and Graph API note

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8185]
Can you please double-check with the engineering team what the expected behavior for MessageUpdated (and all the other Advanced events for Teams) is supposed to be? The note you've added states:

"1 An audit record for this event is only logged when the operation is performed by calling a Microsoft Graph API. If the operation is performed in the Teams client, an audit record will not be logged"

Yet I'm able to see "Updated a message"/MessageUpdated events just fine even when the operation was performed via the Teams client. Moreover, it makes zero sense to me to only audit message updates that have been executed via the Graph. 

I can see that many of the other advanced events are targeted to application scenarios, so the notes are relevant. However I'd expect a predictable experience for any other event that can be performed via the client too, i.e. MessageSent. Although that last one doesn't seem to generate audit records atm, so it adds to the confusion.

![image](https://user-images.githubusercontent.com/38553333/143202273-39033a8b-10b3-4acb-b544-fc30037fbd1f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e51e97-ff97-c5eb-6517-21ce9a563ca4
* Version Independent ID: d3dc21b2-d90a-fbe7-8473-fff0b55feafb
* Content: [Search the audit log for events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audit-log-events#teams-activities)
* Content Source: [Teams/audit-log-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audit-log-events.md)
* Service: **msteams**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
