### ISSUE TITLE
Calendars and Events

### ISSUE THREAD

**Issue by MClauwaert** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8186]
I was unable to find documentation on how Teams and Exchange synchronize users their calendars and events/appointments.

A user  can have multiple Calendars (eg. default, CalendarA, CalendarB). Can a user or administrator somehow configure that only certain calendars show up in a users' teams calendar? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @MClauwaert Maarten
Teams will query the built-in default calendar and AFAIK it is the only _user_ calendar that Teams handles at the moment.
Please let me know if I understood correctly your query.
Thanks, Andrés
