### ISSUE TITLE
Not clear definition of  'Teams not managed by an organization'

### ISSUE THREAD

**Issue by TheITguy666** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8187]
What do you mean by 'external Teams users whose accounts are not managed by an organization'
Are this Teams free / private users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external access (federation) - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/manage-external-access)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @TheITguy666, thank you for your feedback.

This feedback was previously reported, follow it for updates:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8112

Thank you again!
