### ISSUE TITLE
Typo in Desktop Logs location and name

### ISSUE THREAD

**Issue by jaredburnett** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8189]
![image](https://user-images.githubusercontent.com/76020255/143326330-3ebdad09-700f-47d6-8d2d-8e98de6b091b.png)

Typo in second paragraph of this section https://docs.microsoft.com/en-us/microsoftteams/log-files#collect-and-enable-logging
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d5e6d3-b7e0-d79f-0dea-ed423186a157
* Version Independent ID: ec6e68aa-552f-ab45-3c8e-92eff526b173
* Content: [Use log files in troubleshooting Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/log-files)
* Content Source: [Teams/log-files.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/log-files.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Thanks for your feedback!
