### ISSUE TITLE
Rocording folder name

### ISSUE THREAD

**Issue by Anders-Claesson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8190]
The name of the recording folder in OneDrive is localized which is not mentioned in any articles. It should have reference (variable) where you could find the folder name. If you want to run a script and find the folder it's extra complicated to test every language that's represented in the Tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8935e913-806f-a92c-d09e-e67df4ffd1b4
* Version Independent ID: c7a41cde-66dd-d7cd-1316-42d20ed4841a
* Content: [Use OneDrive for Business and SharePoint for meeting recordings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/tmr-meeting-recording-change)
* Content Source: [Teams/tmr-meeting-recording-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tmr-meeting-recording-change.md)
* Service: **msteams**
* GitHub Login: @serdars
* Microsoft Alias: **v-mahoffman**

**Comment by get-itips** [comment]
Hello @Anders-Claesson 
I tried to reproduce to see if we need to adjust the information in the article however, even though my profile was non-English, the folder name was still "Recordings"
Can you give me more details about your scenario/screenshot?
About product feedback I can propose you [this resource](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472) as here we are limited to documentation changes.
Thank you
