### ISSUE TITLE
Update beginning section to state Organizer must explicitly share with external users

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8192]
At the beginning of the article it states
'When a meeting is recorded, it's automatically:
Uploaded to OneDrive for Business or SharePoint Online
Permissioned to the people invited to the meeting'

However only internal users are permissioned to the recording by default. The organizer need to explicitly share with external users. This is detailed further down in the article.  Can you change the wording at the beginning to make it clear as it is misleading.

'When a meeting is recorded, it's automatically:
Uploaded to OneDrive for Business or SharePoint Online
Permissioned to internal people invited to the meeting (Organizer must explicitly share with external users)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/Microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
