### ISSUE TITLE
Where are Meeting transcriptions stored and what governance and compliance controls are there

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8193]
There are no details in this article on where are Meeting transcriptions stored and what governance and compliance controls are there

1. Where the meeting transcription is stored apart from accessing via meeting tab
2. Is the meeting transcription retention aligned with the meeting recording auto deletion rules ( I assume not as it is stored elsewhere)
3. Can you apply a retention policy to transcriptions. If not how do you delete them
4. Can you add sensitivity labels to the transcriptions
3. Can the meeting transaction be surfaced via eDiscovery

Some information is detailed in the following Office support article but I can find no reference in Microsoft Docs articles
https://support.microsoft.com/en-gb/office/view-live-transcription-in-a-teams-meeting-dc1a8f23-2e20-4684-885e-2152e06a4a8b#:~:text=Teams%20live%20transcript%20is%20stored%20in%20the%20meeting,Teams%20until%20a%20meeting%20organizer%20deletes%20the%20transcript.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by lindspea** [comment]
@nikki-c thank you for pointing this out and helping to improve Microsoft Documents.  The docs are improved continuously but in the meantime I will add this link you suggested to help other users. Let me know if you need help with anything else. Thanks again.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
