### ISSUE TITLE
Clarity needed on the known issue with B2B users

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8197]
I am not sure what is meant by the following paragraph regarding B2B guests. 
'B2B guests will not be able to collaborate on live component that is shared with them via Company Share Link unless tenant sets external access option to allow B2B guests have same access level as tenant members.'

Can further clarity be provided about the Admin controls that need to be configured. Are you describing the OneDrive external sharing controls managed in the SharePoint Admin Center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62fa48ba-86fc-85d1-4f32-c22f862536ff
* Version Independent ID: 778b3266-914d-db5f-d7df-66bda022d65c
* Content: [Manage live components in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/live-components-in-teams)
* Content Source: [Teams/live-components-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/live-components-in-teams.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by get-itips** [comment]
Hello @nikki-c Nikki,

I understand this is talking about this setting in AAD admin center:

![image](https://user-images.githubusercontent.com/36666927/144059040-98c8dc71-b5fd-4c7a-915d-f03eaf6fc07d.png)

I'll try to confirm.

Thanks,
