### ISSUE TITLE
Bandwidth requirements page

### ISSUE THREAD

**Issue by PB6565b** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8199]
Please consider including a conversion explanation from mbps to kbps just below your bandwidth requirements chart(s).  Even better, a conversion engine where we can enter our known information (kbps or mbps) and it lists which services will be supported and maybe a quality indication)

I was checking on the bandwidth requirements for a teams meeting.  I had checked my up & down speed online and got and answer in MBPS, not KBPS.  Not being particularly tech literate it took me a while to find and complete the conversion.

Thanks,  helpful article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d996cf7-9f48-2b30-7759-afaf3fe82caa
* Version Independent ID: 24dd6cdf-d35f-53b2-06c2-0a27891825d4
* Content: [Prepare your organization's network for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/prepare-network)
* Content Source: [Teams/prepare-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/prepare-network.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @PB6565b,

While we welcome your feedback, this is the first time we've received a comment like this on this article. I don't think an update is needed here as the conversation is very simple to do manually or with an online tool.

We have received other types of comments for this section, but not like this one. For instance:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7847
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7831
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7685
