### ISSUE TITLE
What else you should know section incorrect

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#82]
Hi, I followed the instructions around Set-CsOnlineDialInConferencingTenantSettings cmdlet to change the address but it didn't work. I logged a support case and was informed this feature was deprecated a year ago and will not work. 
You should remove this section from the documentation or replace it with text saying this feature is now deprecated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4da721d-9286-c9d8-87d3-3149a378e036
* Version Independent ID: 001cd381-4bdc-2770-80ca-d5947c43e569
* Content: [Enable or disable sending emails when their settings change](https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/enable-or-disable-sending-emails-when-their-settings-change)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/enable-or-disable-sending-emails-when-their-settings-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/enable-or-disable-sending-emails-when-their-settings-change.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by tonysmit** [comment]
@thommck I confirmed that is was deprecated. I've updated the topic and republished.  I appreciate the feedback! Thanks, Tony
