### ISSUE TITLE
Disable Autolaunch

### ISSUE THREAD

**Issue by kirby14** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#820]
Instructions say:
msiexec /i Teams_windows.exe OPTIONS="noAutoStart=false"

But shouldn't that be .msi, not .exe for msiexec?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b13006b-d1de-8bc7-e0c6-b7022af0e731
* Version Independent ID: d29dae65-bb28-8767-cfd7-07d2ed5fd460
* Content: [Install Microsoft Teams using MSI](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @Lester-Hewett
* Microsoft Alias: **lehewe**

**Comment by carloshenzel** [comment]
The **OPTIONS="noAutoStart=false"** parameter is not working. Even by exchanging .exe for .msi, the Autolaunch not disable.

**Comment by rtawney13** [comment]
I submitted for this as well. They noted it is incorrect and will it will be fixed, but nothing  yet.

**Comment by thomasbinder** [comment]
I'm trying to verify if this feature has already shipped.

**Comment by AndreaBarr** [comment]
@kirby14 I have this in the backlock to get looked at and investigated to see what's going on here. I am going to close this until we have an update on that. 

@thomasbinder Do you have any updates on what is going on with this paramiter?
