### ISSUE TITLE
Deleting the substrate Data Storage (SDS) statement in this document

### ISSUE THREAD

**Issue by yu1625** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8203]
Could you delete the substrate Data Storage (SDS) statement in this document? 
I quoted it below. The reason is that office 365 administrators often don't know about SDS, and it's about the architecture behind Office 365, so we don't need to tell the customer about it. I would like you to delete "group shards" of SDS and "tenant shard" of SDS as well.

`The approval templates are stored in Substrate Data Storage (SDS), which is a compliant storage platform used internally only inside Microsoft. The organization-scoped templates are stored in “tenant shard” of SDS, and team-scoped templates are stored in “group shards” of SDS. This means that the org-scoped templates share the same lifetime of the tenant and team-scoped templates share the same lifetime of the team. So, permanently deleting the team deletes the related templates.`

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 055b01ff-ee6c-7d5a-74bd-0e8eed7ee6b5
* Version Independent ID: 13c4174f-2a2a-2ef9-14c5-2f10817cc66a
* Content: [Approvals application availability in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/approval-admin?source=docs)
* Content Source: [Teams/approval-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/approval-admin.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by dariomws** [comment]
Hi @yu1625, thank you for your feedback.

If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=yu1625

**Comment by dariomws** [comment]
![image](https://user-images.githubusercontent.com/33589238/144364447-60f4b3a9-e163-4d16-b012-4695e57ea6a7.png)yu1625, I need confirmation before remote that sentence. Please, give me some time.

@yu1625 @daisyfell, could you kindly help me here to confirm this information? Thanks!

**Comment by daisyfell** [comment]
@yu1625 and @dariomws I'm going to check with the PM and get this sentence either removed or adjusted as soon as I hear back. Thanks for bringing this to my attention

**Comment by daisyfell** [comment]
> @yu1625 and @dariomws I'm going to check with the PM and get this sentence either removed or adjusted as soon as I hear back. Thanks for bringing this to my attention

The document has been updated to remove language referencing substrate
