### ISSUE TITLE
Add Teams phone to supported Teams clients

### ISSUE THREAD

**Issue by shtakeda** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8205]
Please add Teams phones to supported Teams clients.
It has been announced on Teams Blog.
https://techcommunity.microsoft.com/t5/microsoft-teams-blog/what-s-new-in-microsoft-teams-november-2021/ba-p/3015700
Teams app version: 1449/1.0.94.2021101205 supports SBA.
https://support.microsoft.com/en-us/office/what-s-new-in-microsoft-teams-devices-eabf4d81-acdd-4b23-afa1-9ee47bb7c5e2#ID0EBD=Desk_phones
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 183fc921-e9b1-cc74-2bcb-26d32b994919
* Version Independent ID: 1765bda3-dd62-76d7-1e2d-9f5496ac9094
* Content: [Direct Routing SBA - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-survivable-branch-appliance)
* Content Source: [Teams/direct-routing-survivable-branch-appliance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-survivable-branch-appliance.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Thanks for your feedback

**Comment by get-itips** [comment]
@scanum information was added to the article, please close.

**Comment by shtakeda** [comment]
@get-itips , thanks.
Teams for Mobile has been added. Are there any additional resources for that? I cannot find out any information on Docs.

**Comment by get-itips** [comment]
> @get-itips , thanks. Teams for Mobile has been added, too. Are there any additional resources for that? I cannot find out any other information on Docs.

Here is the PR that added mobile https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/8241 but I am afraid I can not find more information at the moment.

**Comment by shtakeda** [comment]
@get-itips , Teams Engineering team told that Teams mobile supported SBA. Please close the case.

**Comment by shtakeda** [comment]
@get-itips , Teams Engineering team told that Teams mobile supported SBA. Please close the case.
