### ISSUE TITLE
Details needed for restarting Teams

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8208]
Hi,
You wrote; 
_Go to Settings > General, select the Enable logging for meeting diagnostics (requires restarting Teams) check box, restart Teams, and reproduce the issue._
Not sure do you agree, but when I do sign-out and sign-in again, that selection is removed.

Only option to keep that setting active is to you "quit" option:
![image](https://user-images.githubusercontent.com/43988151/144335578-78abddaa-7342-40e9-90b2-5f8aeb4379f1.png)
And after that when you start Teams client the setting is still selected. But following your instructions, I'm not sure if this is enough clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d5e6d3-b7e0-d79f-0dea-ed423186a157
* Version Independent ID: ec6e68aa-552f-ab45-3c8e-92eff526b173
* Content: [Use log files in troubleshooting Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/log-files#media-logs)
* Content Source: [Teams/log-files.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/log-files.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by Petri-X** [comment]
Hi @get-itips 

When you go to regular end user and ask them to restart Teams, they most likely press [ X ] on up right corner. Next group of them could find the "sign-out" as that is still found from Team's own menus. As that seems to be way to activate some of the settings.

To find Quit is so much harder to found for regular users. So if you are expecting them to do this correctly without detailed instructions, this would most likely not end with successful results.

Also we could discuss why sign-out/sign-in clears that configuration and why on that page is not warning to that. The whole concept of Quit/Logout on Teams is made super confusing. See e.g.: [sharepains.com: Log in to Microsoft Teams, log-out and log out again](https://sharepains.com/2017/11/29/microsoft-teams-log-in-log-out-and-log-out/). So that could requires own docs.microsoft.com article.

But this is just how I see this, and so often I have been so wrong :D

**Comment by Petri-X** [comment]
Hi again, 

Just a comment, see what Microsoft gives instructions on the learning portal:

[Explore audio and video quality issues](https://docs.microsoft.com/en-us/learn/modules/troubleshoot-microsoft-teams-voice-issues/2-explore-audio-video-quality-issues):
_Sign out and log back into the Teams client after selecting Enable logging for meeting diagnostics (requires restarting Teams). Just closing Teams and opening it again in not sufficient. Although the setting appears to have been saved, the changes won't take effect without signing out and logging back in again._

So the whole sign-out/quit/login/restart process is super confusing on Teams.

**Comment by get-itips** [comment]
Thanks for sharing that @Petri-X I am already proposing to clarify that thru a PR.
