### ISSUE TITLE
Missing examples of situations where Microsoft won't use voice recognition data

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8210]
There is following statement in the document: "For example, Microsoft won't use the data in the following situations:" but it does not mention any situations.

Can we get some examples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ec8f04d-0386-3141-ff03-0149589fe876
* Version Independent ID: 2dd04344-50a7-7214-fc5f-0f92eafcf8ac
* Content: [Tenant Administration control for voice recognition (voice profile) in Teams Rooms - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/voice-recognition)
* Content Source: [Teams/rooms/voice-recognition.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/voice-recognition.md)
* Service: **msteams**
* GitHub Login: @serdars
* Microsoft Alias: **v-mahoffman**

**Comment by dariomws** [comment]
Hi @Larryngolog, thank you for your feedback.

@v-mahoffman, could you kindly help here?

**Comment by dariomws** [comment]
@v-mahoffman, could you kindly help here?

**Comment by dariomws** [comment]
@v-mahoffman, could you kindly help here?

**Comment by scanum** [comment]
@dstrome and @SerdarSoysal hope all is well. Is this something you can help us with? Thanks!

**Comment by scanum** [comment]
@dstrome and @SerdarSoysal hope all is well. Is this something you can help us with? Thanks!

**Comment by scanum** [comment]
@dstrome and @SerdarSoysal hope all is well. Is this something you can help us with? Thanks!
