### ISSUE TITLE
MFA as stated in Surface Hub account configuration

### ISSUE THREAD

**Issue by Kevindf34** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8213]
Its entirely possible I have missed some information in this extensive volume of documentation.  But it seems that MFA isn't mentioned in this section regarding MTR room device account configuration.  It was pointed out to me when being assisted by a Microsoft Rep when I was setting up a Surface Hub account.

It was also mentioned by a well known Microsoft community influencer/community member.

I am wondering that if the same rules of "no MFA or conditional access policies" also applies to these MTRs when setting up device accounts

Here is the link in reference

Under Configuration Overview part 3 and 4

https://docs.microsoft.com/en-us/surface-hub/create-and-test-a-device-account-surface-hub

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 834f564b-d32a-25ba-437b-1cb74adbf485
* Version Independent ID: 9bdb6864-caa0-d0fa-ce06-eaaa1fd18fe3
* Content: [Configure accounts for Microsoft Teams Rooms - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-configure-accounts)
* Content Source: [Teams/rooms/rooms-configure-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-configure-accounts.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @Kevindf34, thank you for your feedback.

Yes, the same rules for CA and MFA apply for Microsoft Teams Rooms device accounts. As these accounts are not associated with a particular user, they must be excluded from any Conditional Access policy.

**Comment by dstrome** [comment]
Will add this to the topic in a future update.
