### ISSUE TITLE
Deploy Microsoft Teams Rooms with Exchange on Premise

### ISSUE THREAD

**Issue by ihntremmel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8217]
The SkypeRoomProvisioningScript.ps1 has a "1" character on line 334 that causes the script to error out

`$strDisplayName = Read-Host -Prompt "Please enter the display name you would like to use for $strUpn"1`
removal of the 1 at the end of the line makes the script work properly.  Please revise the script to remove this character.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91cd0219-b3b0-da60-6416-c6b5a67623e3
* Version Independent ID: 983d08b5-4a2c-838a-52eb-821045d2c9df
* Content: [Deploy Microsoft Teams Rooms with Exchange on-premises - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-exchange-on-premises)
* Content Source: [Teams/rooms/with-exchange-on-premises.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-exchange-on-premises.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by cazawideh** [comment]
This script is no longer in the documentation
