### ISSUE TITLE
Device support for SBA

### ISSUE THREAD

**Issue by tommyjh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8218]
The Direct Routing SBA page lists only the Windows and Mac clients as supported.  Lab testing shows Teams phones work (not 3pip for obvious reasons).  Is this supported but omitted from the page in error or is there still no official support?
Thank you
Tom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 183fc921-e9b1-cc74-2bcb-26d32b994919
* Version Independent ID: 1765bda3-dd62-76d7-1e2d-9f5496ac9094
* Content: [Direct Routing SBA - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-survivable-branch-appliance)
* Content Source: [Teams/direct-routing-survivable-branch-appliance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-survivable-branch-appliance.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @tommyjh, thank you for your feedback.

This is the same as:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8205
Work is in progress to add this information.
