### ISSUE TITLE
Link Not working

### ISSUE THREAD

**Issue by MIBadran** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#822]
Here are common use cases for each application in Office 365. For detailed usage guidance, visit the FastTrack Productivity Library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e1b8fbb-3047-dd3a-6a9c-ae6b1d5a0222
* Version Independent ID: 42c418d1-8473-2243-81bc-558e0a0688aa
* Content: [Overview of Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-overview?ui=en-US&rs=en-US&ad=US#feedback)
* Content Source: [Teams/Teams-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@MIBadran Thank you for this feedback

I went to see what the link gives for an error and it worked fine for me. I am using edge to open it. It could be a browser issue or it may have been a glitch somewhere. Can you try the link again and see if you can get it opened up. If it still doesn't work contact support so we can figut out what is wrong. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by MIBadran** [comment]
Hi

Its still not working ; I am referring to this part in the Page  in highlight

Here are common use cases for each application in Office 365. For detailed usage guidance, visit the FastTrack Productivity Library<https://go.microsoft.com/fwlink/?linkid=854630>.

**Comment by MIBadran** [comment]
Hi I dont think you understood my reporting ; i am referring to a Link in the Page 
Its still not working ; I am referring to this part in the Page  in highlight 

"Here are common use cases for each application in Office 365. For detailed usage guidance, visit the **FastTrack Productivity Library.**" 

The link address is https://go.microsoft.com/fwlink/?linkid=854630

**Comment by AndreaBarr** [comment]
@MIBadran Thank you for the clarification. I double checked I was looking at the correct link. I also tested all the other links in the article as well and I can open up all the links. What error does it give you. Can you attach a screenshot of it?

**Comment by MIBadran** [comment]
Can you see the attached step recorder?

Regards

**Comment by MIBadran** [comment]
Can you see the attached step recorder?

Regards 
[Recording_20180927_1311.zip](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/files/2425191/Recording_20180927_1311.zip)

**Comment by AndreaBarr** [comment]
@MIBadran yes I can see the step recorder. Thank you for showing what it was giving you. 


For me both internally on microsofts network and externally on my phone it works so I want to make sure we figure out what is going on with this link. I am going to have us tackle this on two fronts. I am going to put this in the Teams/Skype for Business backlog and I also want you to open a Support ticket. This way we can get it handled on two sided and get this figured out quickly. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 

. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by LolaJacobsen** [comment]
We recently updated and republished this article, and it no longer includes the FastTrack link originally mentioned in the issue. Closing this now.
