### ISSUE TITLE
Error in KQL query?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8220]
I am by no means experienced in KQL, but it seems there is a slight error in the 1st query below **Expanding your threat hunting opportunities**

``` kusto
OfficeActivity
| where TimeGenerated > ago(time_window)
```
(Line 37)

references `time_window`  but the `let` statement defines `timeRange`
```kusto
let timeRange = 1d;
```
When I fix that, the next error is `'where' operator: Failed to resolve table or column or scalar expression named 'Members'`, but that could be me or my data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0157c71c-b57d-ecdf-d2de-1d6f02eaf238
* Version Independent ID: 25eae9c1-9730-a88b-066d-75e9116f389c
* Content: [Azure Sentinel and Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-sentinel-guide)
* Content Source: [Teams/teams-sentinel-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-sentinel-guide.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by andrePKI** [comment]
@scanum Hi Manuela, the error in the KQL (`time_window` versus `timeRange`) is still there, for that I am not going to open a support ticket...
