### ISSUE TITLE
Teams Chat limits

### ISSUE THREAD

**Issue by MargonMink** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8225]
on the Dutch  page other information
English: Number of people in a private chat1 | **250**2
English: https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams
![image](https://user-images.githubusercontent.com/58948477/144916427-12baa6b1-ab13-4865-89c3-9441ff45812c.png)

Dutch: Aantal personen in een privéchat1 | **100**
Dutch: https://docs.microsoft.com/nl-nl/microsoftteams/limits-specifications-teams
![image](https://user-images.githubusercontent.com/58948477/144916510-1438d648-bc5c-46eb-acf1-7a3be143bdd9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#feedback)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
@TinaMcN, could you kindly help? Thanks.

**Comment by TinaMcN** [comment]
@MargonMink thank you for highlighting this.  It's odd because we don't usually translate the Microsoft Teams articles into Dutch,  it looks like a previous version was accidentally translated but not the latest version.  I'm looking into it and will let you know.

**Comment by TinaMcN** [comment]
@MargonMink I discovered that some of the articles were mistakenly machine translated into Dutch.  The Dutch content is now unpublished and you should see the English content instead.   Thank you for letting us know of this issue.

**Comment by cdowling1971** [comment]
@MargonMink - Outdated Dutch content was accidentally published and displaying Dutch but that's been rectified and restored to English, thanks again for reporting this issue.
FYI @TinaMcN
