### ISSUE TITLE
Bunch of Teams admin center links are wrong. 

### ISSUE THREAD

**Issue by ASeabrook36** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8229]
There are a bunch of links to the Teams admin center that go to places like admin-teams.microsoft.net which will obviously not work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05173ea8-db7c-a20d-3783-178b3d649190
* Version Independent ID: 05173ea8-db7c-a20d-3783-178b3d649190
* Content: [Configure SIP Gateway - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sip-gateway-configure)
* Content Source: [Teams/sip-gateway-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sip-gateway-configure.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by ASeabrook36** [comment]
Duplicate of issue already noted by other users.

**Comment by CarolynRowe** [comment]
Not sure what the duplicate issue # is, but I've fixed the links.  Should go live tomorrow.
