### ISSUE TITLE
Add custom audio file types and sizes

### ISSUE THREAD

**Issue by martinboam** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8233]
[Would be helpful to include custom audio file types and sizes as well]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed4beab-bb0d-fba4-814e-147d22fd97e5
* Version Independent ID: 8ed4beab-bb0d-fba4-814e-147d22fd97e5
* Content: [Routing calls to unassigned numbers - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/routing-calls-to-unassigned-numbers)
* Content Source: [Teams/routing-calls-to-unassigned-numbers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/routing-calls-to-unassigned-numbers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @martinboam Martin, how are you?

The file type and max size is specified in the [Import-CsOnlineAudioFile](https://docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps) article.

>The Content parameter represents the content of the audio file. Supported formats are WAV (uncompressed, linear PCM with 8/16/32-bit depth in mono or stereo), WMA (mono only), and MP3. The audio file content cannot be more 5MB.

Do you mean that it would be useful to also have it detailed in this article?

Thanks for clarifying,

**Comment by martinboam** [comment]
Hi Andres,

Yes, I think so.

We have this listed for call queues and auto attendants so i assumed it was the same but if someone doesn't know that it may be confusing what file types and max sizes they can use for announcement files.

Thanks
Martin
________________________________
