### ISSUE TITLE
Quantity in text is wrong

### ISSUE THREAD

**Issue by coletham** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8234]
Mentions "for several reasons" but then bullets three.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4d56b6e-a220-710c-f051-6e78bf0883fe
* Version Independent ID: d1aa0964-725e-0b99-00c0-7ddcfad46920
* Content: [Sign out of Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-gb/MicrosoftTeams/sign-out-of-teams)
* Content Source: [Teams/sign-out-of-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sign-out-of-teams.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@coletham thank you for reaching out and helping to improve Microsoft Docs. The term 'several' can mean any number from 3 - 5 usually, so the terminology will remain as is.
