### ISSUE TITLE
View Designer No Longer Available to Create Tiles

### ISSUE THREAD

**Issue by bdegs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8238]
Hello, under this section (https://docs.microsoft.com/en-us/microsoftteams/rooms/azure-monitor-deploy#create-a-microsoft-teams-rooms-dashboard-manually) of the doc the View Designer is no longer available to create new views as of 11/30/2020 as stated here (https://azure.microsoft.com/en-gb/updates/view-designer-in-azure-monitor-is-retiring-on-31-august-2023/).

With this said can this document be modified to either create the tiles using an Azure Workbook?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c813d7c-1789-d0c9-c833-cbdd3f60e2b8
* Version Independent ID: e5b7e6a7-2f78-dd58-b450-0d173935e26c
* Content: [Deploy Microsoft Teams Rooms management with Azure Monitor - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/azure-monitor-deploy#Define_Views)
* Content Source: [Teams/rooms/azure-monitor-deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/azure-monitor-deploy.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @bdegs, thank you for your feedback.

There is an important note in the article about this:

> [!IMPORTANT]
> [View Designer in Azure Monitor is retiring on 31 August 2023](https://azure.microsoft.com/updates/view-designer-in-azure-monitor-is-retiring-on-31-august-2023/) and create and clone functionalities have been disabled on 30 November 2020. Workbooks can be used instead. For more information on the view designer transitioning guide to workbooks, see [Quickstart with preset view designer templates](/azure/azure-monitor/visualize/view-designer-conversion-tasks#quickstart-with-preset-view-designer-templates).
