### ISSUE TITLE
Enrollment feature code?

### ISSUE THREAD

**Issue by jpjm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8239]
In the "Provision and enroll SIP devices as common area phones" section, step 4 mentions dialling an enrollment feature code. This is the first mention of such a feature code in the document - can you clarify where this code comes from?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05173ea8-db7c-a20d-3783-178b3d649190
* Version Independent ID: 05173ea8-db7c-a20d-3783-178b3d649190
* Content: [Configure SIP Gateway - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sip-gateway-configure)
* Content Source: [Teams/sip-gateway-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sip-gateway-configure.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Adding @danny-levin to this conversation.

**Comment by danny-levin** [comment]
Agree. "feature code", is well know term in telephony to invoke features, such as 411 to get local time in USA.  I believe that it self-explanatory, but the text   should be:  "On the SIP device, dial the enrollment feature code *55* , (used by SIP Gateway for code validation),  followed by the verification code that is generated in Teams Admin Center for this particular device. For example, if the verification code is 123456, dial *55*123456 to enroll the device."

**Comment by Chandranshu-Singh** [comment]
Minor edit to Danny's comment above, the feature code is <*55*>. So we should make sure to add the <*> before and after <55>.

So the text should read  as follows -
"On the SIP device, dial the enrollment feature code shown within angular brackets <*55*> (used by SIP Gateway for enrollment one-time-verification code validation), followed by the verification code that is generated in Teams Admin Center for this particular device. For example, if the verification code is 123456, dial *55*123456 to enroll the device."

**Comment by Chandranshu-Singh** [comment]
Not sure why Github removes the "*"
