### ISSUE TITLE
S4B joining MS Teams meetings

### ISSUE THREAD

**Issue by andrescolombia** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#824]
Could you clarify whether S4B -or other users using SIP meeting services- can join MS Teams meetings? Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d53d0cb0-90a6-5932-f78e-7de6fcc4d481
* Version Independent ID: 3d468027-cc37-5199-32ec-819bf62b2caa
* Content: [Understand coexistence and interoperability of Skype for Business and Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability)
* Content Source: [Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md)
* Service: **msteams**
* GitHub Login: @arachmanGitHub
* Microsoft Alias: **arachman**

**Comment by AndreaBarr** [comment]
@andrescolombia Thank you for this feedback

I am not sure on the answer for this but I'll get it over to the Teams/S4B team so we can get this updated into the article. If you need an immediate answer please contact Support they can handle this to resolution as well. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by sam-fakhreddine** [comment]
Was this issue ever solved?

**Comment by AndreaBarr** [comment]
@sam-fakhreddine no it hasn't been resolved yet.

**Comment by AndreaBarr** [comment]
@nsshommo Could you investigate this please?

**Comment by scanum** [comment]
@nsshommo Following up on this issue, could you please investigate this issue? Thanks

**Comment by nsshommo** [comment]
You cannot join meetings in Teams from Skype/S4B. Hopefully, Microsoft is working on this but as of now, it is not possible. If you want to join Teams meeting or message teams people, they need to setup a free Teams and they would have to invite you to their team or vise Versa as a guest. For more information, you can see the following link:

https://docs.microsoft.com/en-us/microsoftteams/coexistence-chat-calls-presence

**Comment by scanum** [comment]
@andrescolombia  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
