### ISSUE TITLE
Call Queue Support

### ISSUE THREAD

**Issue by martinboam** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8243]
[Maybe good to advise if SIP handsets are supported in Call Queues, i assume not as its not mentioned]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44863905-42d1-cd3f-0d97-af2570649e89
* Version Independent ID: 44863905-42d1-cd3f-0d97-af2570649e89
* Content: [Plan SIP Gateway - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sip-gateway-plan)
* Content Source: [Teams/sip-gateway-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sip-gateway-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by lindspea** [comment]
@martinboam thank you for reaching out and helping to improve Microsoft Docs. If the information is not specified in the article then it's usually not supported, but let me do some more investigating to confirm.

**Comment by lindspea** [comment]
@martinboam the article has been updated recently with more information. Please let me know if you need further assistance. Thanks again.
