### ISSUE TITLE
Typo: Managing partner roles section

### ISSUE THREAD

**Issue by klstclair** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8244]
In the section:
Managing partner roles
Partner roles allow for delegation of responsibilities to additional personnel. The concept of these roles is the same as described in Role-based access control, but in context of each customer. Further, it is important to note that partner roles are distinct from the customer’s roles. The partner roles can be deleted by the customer.

The Primary admins role is the only built-in role for each on-boarded customer and has almost all permissions —– in context of the customer —– for the TRM service (see table 1). Partner** role permissions only extend as far as the rooms designated by the customer. For example, if the **cCustomer** is a global organization and assigns the Partner to manage All US rooms, the primary admin would only be able to manage and delegate permissions for those rooms. The Partner has no visibility to other rooms the Customer may have in other countries.

"cCustomer" should be replaced by "customer".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1d8c451-a643-1109-438c-f40b13ec5980
* Version Independent ID: f1d8c451-a643-1109-438c-f40b13ec5980
* Content: [Multi-tenant customer management for partners - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/multi-tenant-management-partner)
* Content Source: [Teams/rooms/multi-tenant-management-partner.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/multi-tenant-management-partner.md)
* Service: **msteams**
* GitHub Login: @donnah007
* Microsoft Alias: **v-donnahill**

**Comment by lindspea** [comment]
@klstclair thank you for pointing this out and helping to improve Microsoft Docs. It seems the typo has been fixed in the interim. Thanks again.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
