### ISSUE TITLE
Typo: Navigating the MTM portal section

### ISSUE THREAD

**Issue by klstclair** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8245]
In the section:
Typo: Navigating the MTM portal section

In the Section:
Navigating the MTM portal
The MTM portal has two interactive models to navigate between customer data:
Aggregate views **were** data from all your customers is consolidated in a single list and can be filtered.

"were" should be replaced by "where"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1d8c451-a643-1109-438c-f40b13ec5980
* Version Independent ID: f1d8c451-a643-1109-438c-f40b13ec5980
* Content: [Multi-tenant customer management for partners - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/multi-tenant-management-partner)
* Content Source: [Teams/rooms/multi-tenant-management-partner.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/multi-tenant-management-partner.md)
* Service: **msteams**
* GitHub Login: @donnah007
* Microsoft Alias: **v-donnahill**

**Comment by lindspea** [comment]
@klstclair thanks again for your help improving Microsoft Docs. This typo has also been fixed.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
