### ISSUE TITLE
Unable to upload Music On Hold to Microsft Teams via Powershell

### ISSUE THREAD

**Issue by MichaelRasmus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8246]
Not sure if this is the right spot to post but anyway.

I tried uploading custom music on hold file to microsoft teams via powershell and i keep getting the below error.
I have already double checked the file size and its 969KB or 3,843KB and it gives me that exact same error response. 

Any help on this would be much appreciated.

Sending data to a remote command failed with the following error message: The current deserialized object size of the
data received from the remote client computer exceeded the allowed maximum object size. The current deserialized
object size is 10572800. The allowed maximum object size is 10485760. For more information, see the
about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OperationStopped: (api.interfaces....s.microsoft.com:String) [], PSRemotingTransportExce
   ption
    + FullyQualifiedErrorId : JobFailure
    + PSComputerName        : api.interfaces.records.teams.microsoft.com

**Comment by MichaelRasmus** [comment]
I am following the guide from this link: https://docs.microsoft.com/en-us/microsoftteams/music-on-hold

This is the command i am running:
>> $Content = Get-Content "G:\UBR3CXAudioFiles\SIP280920-16bit.mp3" -Encoding byte -ReadCount 0
>> $AudioFile = Import-CsOnlineAudioFile -FileName "SIP280920-16bit.mp3" -Content $content
>> $AudioFile

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by MichaelRasmus** [comment]
I have now been able to upload a different file. the one that was successful was only 30 seconds long where as the other file i was trying to upload was 4 mins+. 
Do you know what the max length the audio file can be?

**Comment by MichaelRasmus** [comment]
Ok i have now been able to upload the files to the MS Teams platform with the help from Microsoft.
The issue was that the Teams powershell module wasn't on the latest version. once i updated the version to 3.0.0 i was able to upload the music file successfully.
Just thought i would update you.
