### ISSUE TITLE
RFC 4566

### ISSUE THREAD

**Issue by SidChat93** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8247]
This document mentions [RFC 4566](https://datatracker.ietf.org/doc/html/rfc4566), which is obsolete per [RFC 8866](https://datatracker.ietf.org/doc/html/rfc8866). Does it need to be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33613b2d-d607-ec47-1254-ae540d07ad59
* Version Independent ID: aba728f0-0d3c-73fd-c7fe-68e69b6a753f
* Content: [Security guide for Microsoft Teams overview - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-security-guide#media-encryption)
* Content Source: [Teams/teams-security-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-security-guide.md)
* Service: **msteams**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by get-itips** [comment]
Hello @SidChat93 I am looking into this.

**Comment by SidChat93** [comment]
> Hello @SidChat93 I am looking into this.

How long will it take?
