### ISSUE TITLE
Can't pipe identity from get-csonlineuser to set-csuser

### ISSUE THREAD

**Issue by zcmott** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8253]
I use to be able to Get-CsOnlineUser test@domain.com | Set-CsUser -LineURI tel:+1231231234
i get an error that says Set-CsUser: One or more errors occurred. ([NotFound] : userId was not found)

i tested both 3.0.0 and 3.0.1 and both have the same issue.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
