### ISSUE TITLE
compliance recording is not applicable for Direct routing

### ISSUE THREAD

**Issue by 2kiran** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8255]
Customers asking questions about whether direct routing is available for compliance recording.
Note from dev: 
[12/10/2021 12:00 PM] Stephen Sulzer
once CR comes into the picture, the conversation will escalate to a group call hosted in the cloud, so media bypass is essentially N/A as the media flow will have to flow from the on-prem SBC up to the Azure cloud where the group call is hosted. What would have been a 1:1 PSTN:Teams call where media is flowing locally/directly on the customer network now becomes a cloud-hosted group call

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10b198f4-9576-a14d-4359-1e8cc0319cda
* Version Independent ID: ba7c3252-21d4-9be1-2a84-de2d51646f7b
* Content: [Plan for media bypass with Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan-media-bypass)
* Content Source: [Teams/direct-routing-plan-media-bypass.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan-media-bypass.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
