### ISSUE TITLE
Does not need to be Teams Service admin to archive or restore a team

### ISSUE THREAD

**Issue by anttikivivallisovelto** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8256]
Apparently the features have changed and this page is outdated:

"Archive a team
Follow these steps to archive a team. You must be a Teams service admin to make these changes. See Use Teams administrator roles to manage Teams to read about getting admin roles and permissions."

It is enough to be a team owner to be able to archive a team or restore and archived team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf689b7-a7c1-121f-578e-029e8a89c4f0
* Version Independent ID: 7e6b449e-bd77-2fc4-2c3d-1f2e364e1b76
* Content: [Archive or delete a team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/archive-or-delete-a-team#archive-a-team)
* Content Source: [Teams/archive-or-delete-a-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/archive-or-delete-a-team.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @anttikivivallisovelto How are you?
Please take into account that these instructions are to be run from the Teams admin center, so the TAC permissions are the ones specified.
Hope this clarifies it for you.
Thanks
