### ISSUE TITLE
Lack of simple walkthroughts for simple scenarios

### ISSUE THREAD

**Issue by zikalino** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8258]
I am developing a bot that I would like to add it to my company Teams.
I have uploaded my extension (bot manifest) and I want admin to approve.
I would like to be give our admin exact instructions how to, do it, for instance:, go there, you will see this, press this button. Unfortunately I am not able to do it because I don't know how this looks from admin perspective. The link that appears in App Studio does lead only to top level page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbcabee-fa96-2878-e983-3c966f84ee15
* Version Independent ID: 02fa4fd8-77e0-5cb2-a4af-576cbb68322f
* Content: [Manage your apps in the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/manage-apps)
* Content Source: [Teams/manage-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-apps.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by get-itips** [comment]
Hello @zikalino Zim,
I tested this publishing an app through App Studio/Dev portal, and then, from the admin side, I experienced this, as the article says:

> Approve a custom app
The Pending approvals widget on the Manage apps page notifies you when a developer submits an app by using the Teams App Submission API. A newly submitted app is listed with a Publishing status of Submitted and an Status of Blocked. Go to the app details page to see more information about the app, and then to publish it, set Publishing status to Publish.

> You're also notified when a developer submits an update to a custom app. You can then review and publish (or reject) the update on the app details page. All app permission policies and app setup policies remain enforced for the updated app

So can you share those details to your tenant's admin? Hope this information helps you,

Andrés

**Comment by get-itips** [comment]
@scanum
