### ISSUE TITLE
Download link to the Champions program guide does not work

### ISSUE THREAD

**Issue by myfope** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8259]
Hi,

the link to the Champions program guide does not work. Can someone check this please?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67a07193-29b0-359b-1104-aed6077360cd
* Version Independent ID: 1a8e42ef-8d23-f9d6-f5ec-2324f5a250f0
* Content: [Create your champions program for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-adoption-create-champions-program)
* Content Source: [Teams/teams-adoption-create-champions-program.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-adoption-create-champions-program.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by get-itips** [comment]
Hello @myfope looking into this. thanks

**Comment by get-itips** [comment]
@myfope Peter, I could get the actual link, however it is currently, not working, will try to confirm
