### ISSUE TITLE
CreateSRSMedia.ps1 asking for Win10 2004 install media. Not avail in VLSC?

### ISSUE THREAD

**Issue by NiiWiiCamo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8260]
Hi everyone,
I am facing a similar issue to https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4181#issue-583103860, where I am unable to create the SRS install media.

With 21H1 iso:
`Your Windows installation media is version 10.0.19041.1348. Your SRSv2 kit requires version 10.0.19041.631.`
[PowerShell_transcript.PC-155.JqsqAKNU.20211216150352.txt](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/files/7728104/PowerShell_transcript.PC-155.JqsqAKNU.20211216150352.txt)
 
With 21H1 iso:
`Your Windows installation media is version 10.0.19041.1288. Your SRSv2 kit requires version 10.0.19041.631.`
[PowerShell_transcript.PC-155.1nxOZAMG.20211216153746.txt](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/files/7728186/PowerShell_transcript.PC-155.1nxOZAMG.20211216153746.txt)

This seems to indicate that it wants Win 10 Enterprise 2004, which is not available in VLSC.
The PC I am running these scripts on is on build 19044.1348 (21H2).

Is there any way to get the installation media working with a somewhat recent Windows build or do I need to go to our fileserver and hope we have that iso archived somewhere?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
