### ISSUE TITLE
Invalid Link

### ISSUE THREAD

**Issue by ClemensLode** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8268]
The proper Link needs to be https://admin.teams.microsoft.com/ not ... microsoft.net
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Manage meeting settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by HowlinWolf-92** [comment]
@scanum The customer is right. It should be ([https://admin.teams.microsoft.com/](https://admin.teams.microsoft.com/))

Can you fix this?

**Comment by HowlinWolf-92** [comment]
See this pull request, which will go live tomorrow morning:

- [https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/pull/8615](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/pull/8615)

**Comment by HowlinWolf-92** [comment]
OK, it's live now.
