### ISSUE TITLE
Clarify subdomain activation (multi-tenant) : remove useless(?) objects

### ISSUE THREAD

**Issue by fdelavier** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8270]
In section "Register a subdomain name in a customer tenant", once the subdomain is activated,
Could you clarify if we can :
- Remove the DNS TXT entry
- Remove the unique user associated with the domain

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure Session Border Controller - Multiple tenants - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @fdelavier,

After you have verified a domain in Microsoft 365 or Office 365, you can safely remove the TXT record.

After you successfully added the SBC to your tenant, you can remove the user you added to activate the domain. (or assign a different SIP address)

**Comment by fdelavier** [comment]
Thanks @dariomws !

Would it be possible to add this information in the documentation ?

**Comment by dariomws** [comment]
@fdelavier, the steps to add a domain to Office 365 are detailed here but if you want to have more detailed information about this process, I suggest that you review more specific articles like:
https://docs.microsoft.com/microsoft-365/admin/setup/add-domain

About the removal of the user, I think there is a related note:

> [!NOTE]
> The Carrier tenant must keep at least one Phone System license assigned to the tenant to avoid removal of the Skype for Business configuration.

**Comment by fdelavier** [comment]
Hi @dariomws,

Actually the main need is to clarify if we can remove the user associated to the customer tenant.

This seems to be very much related to multi-tenant subdomain particularities (subdomain not used by o365 users, beyond activation).

Wouldn't it be better to detail this in Teams/direct-routing-sbc-multiple-tenants.md ?

**Comment by dariomws** [comment]
@fdelavier, I understand that the same applies to customer tenants. But in that case, you will keep a Phone System license for sure.

**Comment by fdelavier** [comment]
Hi @dariomws,

I'm not convinced. On the contrary the requirement to keep the user seems to be specified only for the carrier tenant.

**Note: I don't understand why the user in the carrier tenant is needed "to avoid removal of the Skype for Business configuration". As far I know it is/was just required in order to validate new derived trunk FQDNs.**

**Comment by dariomws** [comment]
@fdelavier, while there are no official articles that provide another way to activate the domain, the information in this article is all that I can say. To activate the domain using a supported process you need to follow the steps in this article.

In the same way, you need to keep the license in the carrier tenant. This is what you need to keep, at least one Phone System license assigned to the tenant.
