### ISSUE TITLE
Invalid Parameter in PSDoc New-CsOnlineVoiceRoutingPolicy

### ISSUE THREAD

**Issue by Ryu-Syrius** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8271]
https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-analog-devices#step-4-assign-the-voice-route-to-the-pstn-usage

-Name is an invalid parameter for New-CsOnlineVoiceRoutingPolicy

SfB Command Reference:
https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlinevoiceroutingpolicy?view=skype-ps

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea0bc170-d9d9-c17a-adc8-d37cb5fe3df5
* Version Independent ID: 3c761043-bea5-0cfb-d85e-13671ed0fe9a
* Content: [Direct Routing - Connecting analog devices - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-analog-devices)
* Content Source: [Teams/direct-routing-analog-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-analog-devices.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Thanks for your feedback!
