### ISSUE TITLE
Team meeting recording location issue

### ISSUE THREAD

**Issue by tony-hu-avepoint** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8272]
Team channel recordings stored in a folder named " Teams Meeting Recordings" in drive library some times, not in specific channel Recordings folder.
There's no document about the folder " Teams Meeting Recordings ", would you please help to confirm and add document for this folder?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8935e913-806f-a92c-d09e-e67df4ffd1b4
* Version Independent ID: c7a41cde-66dd-d7cd-1316-42d20ed4841a
* Content: [Use OneDrive for Business and SharePoint for meeting recordings - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/tmr-meeting-recording-change#set-up-the-meeting-recording-option-for-onedrive-for-business-and-sharepoint)
* Content Source: [Teams/tmr-meeting-recording-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tmr-meeting-recording-change.md)
* Service: **msteams**
* GitHub Login: @serdars
* Microsoft Alias: **v-mahoffman**

**Comment by lindspea** [comment]
@tony-hu-avepoint thank you for reaching out and helping improve Microsoft Docs. Please have a look at this link and let me know if it helps at all - https://techcommunity.microsoft.com/t5/microsoft-teams/microsoft-teams-meeting-record-location/m-p/1752697
