### ISSUE TITLE
Teams Direct Routing Multi-tenant : DNS configurations clarifications

### ISSUE THREAD

**Issue by fdelavier** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8275]
Hi,

The documentation doesn't specify if we should create additional DNS records (A/CNAME entries on sbc1.customers.adatum.biz & co) for subdomains, even if we can create a wildcard DNS record *.customers.adatum.biz.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure Session Border Controller - Multiple tenants - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @fdelavier,

I think it's specified in the article:

"Carrier will need to setup DNS record resolving derived trunk FQDN to carrier SBC ip address."

**Comment by fdelavier** [comment]
Hi @dariomws,

Actually the subject here is directly related to issue #8270 "Clarify subdomain activation (multi-tenant) : remove useless(?) objects"

- If we create a wildcard DNS record (e.g. *.customers.adatum.biz) in order to resolve derived trunk FQDN
- And if the customer didn't remove the user associated to the derived trunk
=> Then we notice DNS conflicts with "lyncdiscover" subdomain when upgrading to Teams (because the command line "Grant-CsTeamsUpgradePolicy" checks "lyncdiscover" subdomain on the FQDN associated to each user).

We typically have this kind of error:

-----------
PS C:\WINDOWS\system32> Grant-CsTeamsUpgradePolicy -PolicyName UpgradeToTeams -Global

AVERTISSEMENT : *All* users in this tenant are now full Teams-only users, except for any users that have an explicit policy assignment of TeamsUpgradePolicy. Teams-only users cannot use Skype for Business clients, except to join Skype for Business meetings.

For details, see http://aka.ms/UpgradeToTeams.

This organization cannot be upgraded to Teams Only mode. One or more M365 domains have a public DNS record that points to an on-premises Skype for Business Server deployment. The domain records at fault are

{[lyncdiscover.sbc1.customers.adatum.biz,customers.adatum.biz];}. To upgrade this tenant to Teams Only, first complete the migration of all users from on-premises Skype

for Business Server to the cloud (using Move - Cs User), and then disable Skype for Business hybrid configuration for this tenant and update the DNS records to point to M365. After these steps are complete, you can execute this command, after which all

users and any subsequently created new users will be Teams Only.

    + CategoryInfo          : NotSpecified: (:) [Grant-CsTeamsUpgradePolicy], ArgumentException

    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.Rtc.Management.AD.Cmdlets.CopyOcsTeamsUpgradePolicyCmdlet

    + PSComputerName        : api.interfaces.records.teams.microsoft.com
-----------
 
That's why I was wondering if we could use wildcard DNS record, in order to resolve derived trunk FQDN.
(or If we should remove the user, as discussed in issue #8270)

**Comment by dariomws** [comment]
I cannot help with this error and the information in your last comment. I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.
