### ISSUE TITLE
Explicitly mention Device class to let customer know which devices can benefit from this article

### ISSUE THREAD

**Issue by maddfremann** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8278]
[Enter feedback here]

Please add the device class this article is applicable to. For example, Step 3 is applicable only to MTR-Windows, we have a customer pointing to this doc and is trying to enable it to on MTR-A. 

Please explicitly mention Device class MTR Windows whenever possible to avoid confusion.

Microsoft Alias: maddfremann from MTR-A team

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c62081e-2421-80b9-8ba9-aaf8fd55e432
* Version Independent ID: 5df3c5e5-978f-cfa7-9e5c-3cd7f65fa8ff
* Content: [Enable Teams Rooms devices to join third-party meetings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/third-party-join)
* Content Source: [Teams/rooms/third-party-join.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/third-party-join.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=maddfremann

**Comment by dariomws** [comment]
Hi @maddfremann, thank you for your feedback.

I'm adding the following note:

> [!NOTE]
> Currently, this feature is only available on the Teams Rooms Windows version.

Do you think this feature will be available in March 2022 on Android?
https://www.microsoft.com/en-ww/microsoft-365/roadmap?filters=&searchterms=direct%2Cguest%2Cjoin

Thanks!
