### ISSUE TITLE
Disable auto lanuch for the MSI installer - two typos in the command prompt

### ISSUE THREAD

**Issue by alegala** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#828]
Hello, you have a typo here in "Disable auto lanuch for the MSI installer", it has to be "launch". Also in a command it has to be .MSI and not .EXE and the value has to be True and not False. Tested it on my side and it works with the command msiexec /i Teams_windows.msi OPTIONS="noAutoStart=true"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b13006b-d1de-8bc7-e0c6-b7022af0e731
* Version Independent ID: d29dae65-bb28-8767-cfd7-07d2ed5fd460
* Content: [Install Microsoft Teams using MSI](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment#disable-auto-lanuch-for-the-msi-installer)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @Lester-Hewett
* Microsoft Alias: **lehewe**

**Comment by AndreaBarr** [comment]
@alegala Thank you for this feedback

I'll make sure these get looked at and corrected. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by lindspea** [comment]
@alegala Thank you for reaching out and for your valuable contribution.  I will investigate further to correct this as soon as possible.

**Comment by lindspea** [comment]
@yogkumgit @AndreaBarr These changes requested have already been implemented.  This issue can be closed thank you.
