### ISSUE TITLE
set-up-tagging-by-shift, it doesn't work

### ISSUE THREAD

**Issue by Peter-Wxin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8282]
Excuse me, no new tags were applied after [Set up tagging by shift](https://docs.microsoft.com/en-us/microsoftteams/manage-tags#set-up-tagging-by-shift)

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b16e659e-cf07-268a-e224-fa444749ac29
* Version Independent ID: ee822a8d-b331-998f-e336-b1fa510f35c0
* Content: [Manage tags in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-tags#set-up-tagging-by-shift)
* Content Source: [Teams/manage-tags.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-tags.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by dariomws** [comment]
@Peter-Wxin, thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.
