### ISSUE TITLE
How to change a setting but never how to check the current setting first?

### ISSUE THREAD

**Issue by natv** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8289]
This isn't only a problem with this particular document but in general, MS docs often show _how_ to change something, **but not how to check what the setting is first before making any changes!**

Specifically for this doc, it outlines how to view all available policies, and how to change a specific user's policy, and even how to change the policy for the entire tenant.  **BUT WHAT IS THE COMMAND TO FIRST CHECK WHAT POLICY IS ASSIGNED?**

If these commands set a policy for the entire tenant or a specific user:

Grant-CsDialoutPolicy -PolicyName <policy name>  -Global 
Grant-CsDialoutPolicy -Identity <username> -PolicyName <policy name> 

One might hope that perhaps replacing Grant- with Get- might show the current configuration, but no that doesn't work - and nowhere in this doc explains how or where to view the current configuration for the tenant or user.

UPDATE - I finally figured out that this works when using the first command on the page (the command that includes the 'online' in the command) with Get- instead of Grant-:

Get-CSOnlineDialOutPolicy -Identity Global

But c'mon... you should be documenting how to check settings before documenting how to change them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 305a21ef-6e99-3f0d-99a0-990489a93715
* Version Independent ID: 5edc67ee-0d68-50a3-fafd-f764d8762fa5
* Content: [Outbound call restrictions - Audio Conferencing & PSTN calls - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/outbound-calling-restriction-policies)
* Content Source: [Teams/outbound-calling-restriction-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/outbound-calling-restriction-policies.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by get-itips** [comment]
Hello @natv I'll propose adding the information to the article. If it gets approval, it will be on the published version of it.
Thank you
