### ISSUE TITLE
Get-CsExternalAccessPolicy -include all

### ISSUE THREAD

**Issue by JatinKPatel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8290]
[Enter feedback here]

The section:

See New-CsBatchPolicyAssignmentOperation for additional examples of how to compile a user list.

You can see the new policy by running Get-CsExternalAccessPolicy -Include All.

See also New-CsExternalAccessPolicy and Set-CsExternalAccessPolicy.

The include option with -All does not work; error below

Get-CsExternalAccessPolicy -Include All
A parameter cannot be found that matches parameter name 'Include'.
    + CategoryInfo          : InvalidArgument: (:) [Get-CsExternalAccessPolicy], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Rtc.Management.Internal.GetExternalAccessPolicyCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external access (federation) - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/manage-external-access?WT.mc_id=TeamsAdminCenterCSH#block-unsolicited-contact-with-external-unmanaged-teams-users)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for reporting @JatinKPatel
