### ISSUE TITLE
Clarity needed on UDP and TCP port information

### ISSUE THREAD

**Issue by lte-deankier** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8291]
> **Open the UDP port**. Open UDP port in the range 49152 to 53247.
What IP address ranges need this to be open?

> **Open the TCP port.** Open TCP port 5061 for IP ranges 52.112.0.0/14 to 52.120.0.0/14. 
Should the to be replaced with and.  Is it 52.112.0.0/14 and 52.120.0.0/14?  Current suggests that the range is inclusive from 52.112.0.0 to 52.123.255.254

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05173ea8-db7c-a20d-3783-178b3d649190
* Version Independent ID: 05173ea8-db7c-a20d-3783-178b3d649190
* Content: [Configure SIP Gateway - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sip-gateway-configure)
* Content Source: [Teams/sip-gateway-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sip-gateway-configure.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @lte-deankier I am looking into this.
