### ISSUE TITLE
A typo spotted on the page regarding Teams Direct Routing

### ISSUE THREAD

**Issue by The-Bad-Guy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8294]
Hello,

Saw below screenshot to change the typo in the sentence... Thanks.

![image](https://user-images.githubusercontent.com/79818134/147633984-21e58b05-e930-4960-accb-c4e24c8c4d53.png)

**Comment by scanum** [comment]
Hi @The-Bad-Guy Thanks for the feedback, could you please help us by linking the article you are referring to? Thanks!
