### ISSUE TITLE
Direct Routing Customers

### ISSUE THREAD

**Issue by labanex** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8295]
There are several articles that may be misleading (or interrupted incorrectly) if the tenant is using Direct Routing. I think a NOTE can be added to each article that states that a calling plan is needed for all user to have a phone number. That's all. Thanks!
Please see Rave case # 28821467 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92b4c9a-d509-7711-a07f-d5c2e1f00665
* Version Independent ID: 4316f16a-9e0c-6a24-a9c2-52b8769a7bc4
* Content: [Create Microsoft 365 users, add Business Voice licenses, and assign phone numbers - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/business-voice/create-users)
* Content Source: [Teams/business-voice/create-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/business-voice/create-users.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @labanex how are you?
In the [overview](https://docs.microsoft.com/microsoftteams/business-voice/set-up-overview) article, before this one, there is an important note that states:

> Important
> **The information in these articles is applicable to Business Voice with Calling Plan only.** Business Voice with Calling Plan is available only in select countries and regions. Before you start setting up Business Voice, check Country and region availability for Business Voice to see whether your country or region supports Business Voice with Calling Plan.

Thank you,

**Comment by get-itips** [comment]
@scanum
