### ISSUE TITLE
Ambiguous information for Calling Plan or Direct Routing options

### ISSUE THREAD

**Issue by JoshPSL** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8296]
The statement "You need one unassigned phone number for each user that needs to make or receive calls to or from external phone numbers." only, apparently, applies to Calling Plan. With Direct Routing, users do _not_ need a number to make or receive calls to or from external phone numbers. Simply assigning a Caller ID Policy to the user to present the number of a resource account is sufficient.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92b4c9a-d509-7711-a07f-d5c2e1f00665
* Version Independent ID: 4316f16a-9e0c-6a24-a9c2-52b8769a7bc4
* Content: [Create Microsoft 365 users, add Business Voice licenses, and assign phone numbers - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/business-voice/create-users)
* Content Source: [Teams/business-voice/create-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/business-voice/create-users.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @JoshPSL, thank you for your feedback.

Yes, this article talks about Business Voice with a calling plan as it is the recommended and most common scenario for small businesses.
