### ISSUE TITLE
Licensing reference for 'Microsoft Teams Phone Standard' or 'Microsoft Teams Phone Standard - Virtual User'

### ISSUE THREAD

**Issue by mladewig** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8303]
https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/virtual-user
https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-states-u-s
https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/assign-teams-add-on-licenses
https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=small-business
https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=enterprise

These are just a few of the docs that need to be updated with new licensing as announced on https://techcommunity.microsoft.com/t5/small-and-medium-business-blog/teams-phone-with-calling-plan-available-in-33-markets-on-january/ba-p/2967643. 

Also, I reviewed my purchased licensing today and it appears as part of this change that the 'Phone System' licensing has been renamed to 'Microsoft Teams Phone Standard'. Also 'Microsoft 365 Phone System – Virtual User' was renamed 'Microsoft Teams Phone Standard - Virtual User'. 

I can't find any reference for 'Microsoft Teams Phone Standard' or 'Microsoft Teams Phone Standard - Virtual User'. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2b2f00a-d4ee-28ab-8c9f-fdc858eb30a4
* Version Independent ID: 07d9aa8b-7e6c-a340-bc75-f0c8159f6c57
* Content: [Availability in the United States (U.S.) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-states-u-s)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-states-u-s.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-states-u-s.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
@mladewig, thank you for your feedback.

@CarolynRowe, do you know if there is work in progress to update the license rebranding? Do you also know if there is an update in progress to update the Teams Phone System rebranding to Teams Phone? Thanks!

**Comment by CarolynRowe** [comment]
@dariomws 
Thanks for looping me in on this discussion.  This needs to be part of a larger discussion with Marketing that is taking place offline.  Regarding Phone System rebranding, yes, we are in the process of scheduling the Teams Phone System rebranding.

**Comment by dariomws** [comment]
@CarolynRowe, thank you! If I can help in some way please let me know.
