### ISSUE TITLE
Not helpful ! Where is the setting

### ISSUE THREAD

**Issue by jasc76** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8305]
Your help is not helpful. The place you write to set this policy does not exist! You give no helpful direction where to find this setting. But this is not only on this help page, this is common ! You must better help the user to find the setting. 
You write:
Using a work or school account that has been assigned the Teams or global administrator role, sign in to the Teams admin center.
Go to Other settings > Enhanced encryption policies.

The link does not go to the teams admin center 
there is no "Other settings->Enhanced Encryption"

this is very annoying and frustrating and sadly is common for your help pages, that you never a detailed enough so a user can find the setting you talk about

REgards
Jan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56b532a-ab80-0e4c-dcd8-829a0a68c08e
* Version Independent ID: e56b532a-ab80-0e4c-dcd8-829a0a68c08e
* Content: [End-to-end encryption for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-end-to-end-encryption)
* Content Source: [Teams/teams-end-to-end-encryption.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-end-to-end-encryption.md)
* Service: **msteams**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by get-itips** [comment]
Hello @jasc76 thanks for your feedback, I am looking into this.

**Comment by get-itips** [comment]
Hello, as the feature is in preview, it is subject to changes, I could verify the option was pulled off from the TAC, when it comes back I'll edit the article. Many thanks for your feedback

**Comment by get-itips** [comment]
@scanum
