### ISSUE TITLE
Custom Teams App of configurableTabs is not available in Setup policies.

### ISSUE THREAD

**Issue by ivanmaria** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8306]
Custom teams app of configurableTabs is not visible in **Teams apps > Setup policies > Select Add > Add apps under Installed apps.**
Only the custom teams app having personal tabs (staticTabs) is visible in **Teams apps > Setup policies > Select Add > Add apps under Installed apps.**
Also, there is no provision to add the custom tab to all channels in teams.

Is there any other way for an admin to add custom channel tab application in each channels of every teams?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f91604a-35b0-dfbb-55b2-b601cb0841b0
* Version Independent ID: 84bcd0d7-b4ed-f13e-c84b-2ec6a7661ae9
* Content: [Manage app setup policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-app-setup-policies#install-apps)
* Content Source: [Teams/teams-app-setup-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-setup-policies.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by dariomws** [comment]
Hi @ivanmaria, thank you for your feedback.

I'm not sure if I understand your comment. Are you talking about adding these custom apps to the Setup Policy, as we can see in the following screenshot?
<img width="984" alt="image" src="https://user-images.githubusercontent.com/33589238/148608524-559c3cfb-cfa6-45e3-b322-40dc49d7e996.png">

**Comment by ivanmaria** [comment]
Hi @dariomws,

Yes. In the 'Add apps' option under 'Installed apps', teams channel tab application are not visible.

**Comment by ashishguptaiitb** [comment]
Hi @ivanmaria , for custom apps, the policies don't work as suggested above and as updated in the docs now. Shall we close this issue with this updated info?

**Comment by dariomws** [comment]
@scanum, please close this issue. Thanks!
