### ISSUE TITLE
Invalid email address listed

### ISSUE THREAD

**Issue by GitRomney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8310]
The email address listed on this site, in section "Request access to the Teams app," TeamsForHealthcare@microsoft.com, is not a valid email address.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8eccf9f4-52ba-903b-f08f-672f4e493565
* Version Independent ID: 4f523b6c-046b-7bdb-5106-c3e3419ed40c
* Content: [Virtual visits with Teams - Integration into Epic EHR - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/expand-teams-across-your-org/healthcare/ehr-admin)
* Content Source: [Teams/expand-teams-across-your-org/healthcare/ehr-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/expand-teams-across-your-org/healthcare/ehr-admin.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanachin**

**Comment by get-itips** [comment]
Hello @GitRomney I am looking into this, thanks for your feedback
