### ISSUE TITLE
Not able to download Video TMT 2.3 for Skype

### ISSUE THREAD

**Issue by Kelvin0226** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8312]
The download link is no longer available, could you help where to download the tool

https://docs.microsoft.com/en-us/skypeforbusiness/certification/test-spec

Thanks for your help

Regards
Kelvin

**Comment by dariomws** [comment]
@DhurataJ,

I think you can help here. Thanks!

**Comment by DhurataJ** [comment]
@dariomws - As part of C+E skilling team I had to remove the broken link from the content. Not sure if there are any updates on the right target. I came across to this issue as well https://github.com/MicrosoftDocs/msteams-docs/issues/2903, which was open in March 2021.
