### ISSUE TITLE
Highlight that you can't add a (new) external user from TAC

### ISSUE THREAD

**Issue by ChristianJBergstrom** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8313]
[Hi, would you mind updating the info and add/highlight that you cannot use Teams admin center to add external users to a team if the external users are not already being present (added) in AAD.

*edit* I'm aware of the following sentence when you scroll down "Guests you have already added via Azure AD B2B, Microsoft 365 Groups, or SharePoint are ready to go." But still think it should be more clear and/or rephrased. 

Thanks!]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93906e31-cd28-702d-bb7e-fcc2529df363
* Version Independent ID: afe4d6ed-cdcb-77e0-0951-f3c69e2463e1
* Content: [Add a guest to a team - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/add-guests)
* Content Source: [Teams/add-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/add-guests.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @ChristianJBergstrom, thank you for your feedback.

To be honest I'm not sure how I can help here. It seems that you found the information in the article.

**Comment by ChristianJBergstrom** [comment]
Hello @dariomws 

It's just not structured right. Beginning with this.

"As an admin, you can add a new guest to the organization in a couple of ways:
Global admins or Teams admins and team owners add a guest to a team in the Teams clients or in the Teams admin center."

Going down on the page. "Guests you have already added via Azure AD B2B, Microsoft 365 Groups, or SharePoint are ready to go."

The latter part should either be removed or added together with the initial information. I wouldn't use "are ready to go" as wording either. But rather something like "can be selected" or similar.
