### ISSUE TITLE
Clarify "manage Connectors" limitation for On-Premises Mailboxes

### ISSUE THREAD

**Issue by sgreenlee11** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8317]
Hi,

There is a limitation for vNext or On-Premises mailboxes called out regarding the inability to manage connectors in this paragraph:

Users hosted on Exchange Online Dedicated (Legacy) must be synchronized to Azure Active Directory on Microsoft 365 or Office 365. They can create and join teams and channels, add and configure tabs and bots, and make use of the chat and calling features. However, they cannot modify profile pictures, manage meetings, access outlook contacts, or manage connectors.

Users with mailboxes hosted on-premises must be synchronized to Azure Active Directory. They can make use of all the features in the above scenario, but additionally, they can manage meetings if the requirements listed on Requirements for mailboxes hosted on-premises section are met.

However, based on my testing I was able to create and update a connector for a Teams channel using an account with an on-premises mailbox. In my test I was using the Incoming Webhooks App. Can you please clarify what limitations exist for on-premises mailboxes when it comes to managing connectors?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @sgreenlee11 
How are you?

>based on my testing I was able to create and update a connector for a Teams channel using an account with an on-premises mailbox.

but that would be covered with this sentence 

> Users with mailboxes hosted on-premises must be synchronized to Azure Active Directory. They can make use of all the features in the above scenario

And there is a Yes in the table of Actions supported, for that scenario.

Please let me know if I understood you correctly,

**Comment by sgreenlee11** [comment]
Hi Andres, Thaks for the response!

The confusing part for me is the bolded section below:

> Users hosted on Exchange Online Dedicated (Legacy) must be synchronized to Azure Active Directory on Microsoft 365 or Office 365. They can create and join teams and channels, add and configure tabs and bots, and make use of the chat and calling features. However, **they cannot modify profile pictures, manage meetings, access outlook contacts, or manage connectors.**
> 
> Users with mailboxes hosted on-premises must be synchronized to Azure Active Directory. They can make use of all the features in the above scenario, but additionally, they can manage meetings if the requirements listed on Requirements for mailboxes hosted on-premises section are met.

The On-Premises paragraph seems to suggest the behavior matches that of EXO Dedicated, with the exception of being able to manage meetings. So, I read that as being unable to manage connectors but it's possible I'm misunderstanding it. 

Also, the Yes in the table of actions supported includes footnote # 5:

> 5 If one of the owners of a team can add connectors, everyone else in that team will be able to do so, even if their mailboxes are homed on-premises.

If an on-premises user is able to add connectors regardless, then this footnote seems unnecessary. This to me suggests the documentation is saying that at least one owner of a team needs an Exchange Online mailbox to add a connector. In my testing that did not seem to be the case.

Please let me know if any of that doesn't make sense. Thanks!

**Comment by get-itips** [comment]
>However, based on my testing I was able to create and update a connector for a Teams channel using an account with an on-premises mailbox

While I try to test this without an owner that can add connectors, in your scenario, you also already have owners that can add connectors?
