### ISSUE TITLE
Files section mentions ShareFile. Teams admin portal Citrix Files is used

### ISSUE THREAD

**Issue by timhaintz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8320]
Hello,

In the [Files section of the documentation](https://docs.microsoft.com/en-us/microsoftteams/enable-features-office-365#files) _ShareFile_ is written. In the [Teams Admin Portal](https://admin.teams.microsoft.com/company-wide-settings/teams-settings) _Citrix files_ is used. 

This is confusing.

Please update the documentation to use _Citrix files_ to be consistent.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9b7f77-061d-a224-ff1c-8d3e15d21221
* Version Independent ID: 00fa9550-c4c4-3398-ffbb-271cc724048f
* Content: [Manage settings for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/enable-features-office-365#files)
* Content Source: [Teams/enable-features-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enable-features-office-365.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by timhaintz** [comment]
![image](https://user-images.githubusercontent.com/19178488/148303582-b0808dd6-bbdf-4dca-ad7c-c776f6f6fa58.png)

**Comment by get-itips** [comment]
Thanks for your feedback!
