### ISSUE TITLE
Calling plan required for resource accounts used as Caller ID from voice enabled channels?

### ISSUE THREAD

**Issue by JMCA2** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8330]
According to Microsoft Support (case 28948227) and our own testing, it seems a calling plan license is required to be assigned to resource accounts so they can be used ID is used as caller ID for voice enabled channels.

If this is indeed required, it should be mentioned on https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue#resource-accounts  and on https://docs.microsoft.com/en-us/microsoftteams/plan-auto-attendant-call-queue

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b755d9ae-13ac-019f-f5f4-a95b1eee2989
* Version Independent ID: f7afd8ad-e6e0-6c79-aed1-4ee87d48ba12
* Content: [Create a call queue in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue)
* Content Source: [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-call-queue.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by JMCA2** [comment]
It shoudl be noted that if the tenant has communication credits then it would also work without calling plans. The credits would be consumed even if the user and resource account don't have credits license assigned. We have verified this behaviour and has been confirmed by Microsoft support on case 28948227.

**Comment by get-itips** [comment]
Hello @JMCA2 how are you? unfortunately, we do not have access to the support cases, I am looking to confirm this behavior. Thanks for your feedback

**Comment by JMCA2** [comment]
@get-itips Hi, thanks. If it helps, I can provide in private the emails from Support and the names of the Support Escalation Engineers involved or any other details

**Comment by tiburd** [comment]
@JMCA2 @get-itips 
Thank you, both! 
Microsoft has confirmed the requirement and has updated the information - the change should appear live after 3:30 PM Pacific Time today.
Closing this issue.
