### ISSUE TITLE
Add On License Differences

### ISSUE THREAD

**Issue by leethomas787** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8331]
Looks like the new add on licenses are either "Domestic" OR "International" rather than a license that does both. So you would need to assign each license if you wanted both.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 243fa83d-b7bf-323a-a14a-026915d3d058
* Version Independent ID: fd4a310b-3144-4a8b-1bde-c2efd0c87377
* Content: [Calling Plans for Microsoft 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/calling-plans-for-office-365)
* Content Source: [Teams/calling-plans-for-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/calling-plans-for-office-365.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by Reeced40** [comment]
@leethomas787 thank you for pointing this out and helping improve Microsoft Docs. There was another issue mentioning that after a Common Phone license was purchased they were able to go back and purchase a Domestic license for the plans. Please let me know if this helps or if you suggest adding a note for clarity to the article.

**Comment by leethomas787** [comment]
Sorry, my suggestion is that the image shows a "Domestic and International - joint plan" this does not show when you go to licensing in 365 - Only single Domestic or International plans. Some customers may find that confusing!
