### ISSUE TITLE
Step 2 for Private Channel Messages Shouldn't Include '-Role Member'

### ISSUE THREAD

**Issue by VShrubowich** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8334]
Under [Include private channel messages in an eDiscovery search](https://docs.microsoft.com/en-us/microsoftteams/ediscovery-investigation#include-private-channel-messages-in-an-ediscovery-search), the command in Step 2 includes '-Role Member' at the end.  This excludes Owners which can also create messages.  Therefore, an eDiscovery based on the results of Step 2 will likely miss some messages.

The code for Step 2 should be:
`Get-TeamChannelUser -GroupId <GroupID> -DisplayName "Engineering"`

Step 3 should also be updated to say, 

> Include the mailboxes of all members **and owners** ...

It would also help to have a step before Step 1 in this section that shows how to get the GroupID of a team.  For example:

1. Run the following command to get the GroupID of the team:
`Get-Team -MailNickName "BusinessDevelopment"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 840dd36b-8c29-9738-4adc-ea9a7d277fd0
* Version Independent ID: b12c43c3-ed81-ace5-dfeb-77cac0f97fe9
* Content: [Conduct an eDiscovery investigation of content - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/ediscovery-investigation#ediscovery-of-private-channels)
* Content Source: [Teams/eDiscovery-investigation.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/eDiscovery-investigation.md)
* Service: **msteams**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@VShrubowich Thanks very much for the feedback. I will implement your recommendations.
