### ISSUE TITLE
Video link just reloads same page instead

### ISSUE THREAD

**Issue by lefrinj** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8336]
The video link under 'check out these videos...' near the top before the comparison tables just points back to this same page and not a video; the link is https://support.office.com/article/join-a-team-as-a-guest-928d1eef-61e2-49ec-b754-c2fe86b34824 

Minor thing, thought you'd want to know. I don't know where the link should go, that's what I went to eh page to find.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [Guest experience in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-experience?redirectSourcePath=%252farticle%252fjoin-a-team-as-a-guest-928d1eef-61e2-49ec-b754-c2fe86b34824&view=o365-worldwide)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by Reeced40** [comment]
@lefrinj thank you for pointing this out and helping to improve Microsoft Docs. I'm looking into this and will fix the article soonest.
