### ISSUE TITLE
Setting Resource Account Telephone Number

### ISSUE THREAD

**Issue by dannyh22** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8339]
In the original page it mentions to use pwshell command Set-CsOnlineApplicationInstance for onprem phone numbers. There is another command for non-onprem phone numbers: Set-CsOnlineVoiceApplicationInstance. 

This command has the -Telephone parameter which can be assigned for non-onprem telephone numbers for non-direct routing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/manage-resource-accounts?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by JensTrier** [comment]
Thanks for the feedback. We'll be changing this page to use the new phone number assignment cmdlet Set-CsPhoneNumberAssignment that works for phone numbers of all types.
