### ISSUE TITLE
Document does not say what indication is provided if capacity is exceeded (e.g. 503 Server Unavailable) and where the errors are logged.

### ISSUE THREAD

**Issue by rhmclean** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#834]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4146039-6a62-7a47-9f02-5600cb026c6c
* Version Independent ID: ab460f03-0253-4cdc-df42-4268f8987be2
* Content: [Plan for the Response Group application in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/enterprise-voice-solution/response-group)
* Content Source: [Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/response-group.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/response-group.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by get-itips** [comment]
Hi @rhmclean thanks for your feedback, we really appreciate it.
Document intention isn't to include such error codes so you won't be find this information there. @yogkumgit can you kindly help here? 
Thank you!

**Comment by yogkumgit** [comment]
@rhmclean  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
