### ISSUE TITLE
Location of logs in Windows 11 is incorrect?

### ISSUE THREAD

**Issue by dcaddick** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8346]
Location listed in doc is:

To collect logs for Windows:
The files will be available in the following locations:
%userprofile%\Downloads\MSTeams Diagnostics Log\meeting\media-stack\\\*\.blog
%userprofile%\Downloads\MSTeams Diagnostics Log\meeting\skylib\\\*\.blog

This should read:
%UsersProfile%\AppData\Roaming\Microsoft\Teams\media-stack

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d5e6d3-b7e0-d79f-0dea-ed423186a157
* Version Independent ID: ec6e68aa-552f-ab45-3c8e-92eff526b173
* Content: [Use log files in troubleshooting Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/log-files)
* Content Source: [Teams/log-files.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/log-files.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @dcaddick David,

Actually, the current path is correct, if you download with    <kbd>Crtl</kbd> + <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>1</kbd> the *.blog files will be in the documented folder
 
(yes, blog files are also to be found in the location %UserProfile%\AppData\Roaming\Microsoft\Teams\media-stack

Thanks

**Comment by get-itips** [comment]
@scanum
