### ISSUE TITLE
When the owner of private channel is removed from organization, other member of channel should get promoted as Owner, this isn't happening

### ISSUE THREAD

**Issue by Wazid20** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8348]
[Enter feedback here]
When the owner of private channel is removed from organization, as per this article, other member of channel should get promoted as Owner, this isn't happening.
Multiple customers have reached out to us on this issue. If this is expected that private channel turns into Orphan state when owner is removed, then please correct article accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels?WT.mc_id=365AdminCSH_RAVE)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @Wazid20, thank you for your feedback.

I have done some testing and it works as expected for me. Another member was promoted to owner after removing the last one.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by Wazid20** [comment]
Greetings,
I did followed up with engineering Team.
As per engineering Teams statement:
Promotion happens when last owner is being removed from Team, but promotion doesn't happens when last owner leaves organization.
But in customers case last owner left the company and as per this (Private channels in Microsoft Teams - Microsoft Teams | Microsoft Docs<https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels?WT.mc_id=365AdminCSH_RAVE>) official document, it says promotion should happen even when private channel owner leaves organization. Please correct this document to avoid confusion.

Wazid Ali Syed
Support Escalation Engineer        Office: +1 (425) 5388309
Skype for Business Online           Email: ***@***.******@***.***>
Microsoft Teams                         Working hours: 9AM-6PM PST M-F

[Logo    Description automatically generated]

**Comment by dariomws** [comment]
Hi @Wazid20,

I have tested it and another member was promoted to owner when I removed the only owner that the private channel had.
