### ISSUE TITLE
Addition of reference to operator connect

### ISSUE THREAD

**Issue by Richard-Barr3tt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8351]
For all of these countries there is a section under calling plans which says _If Calling Plans are not available to purchase, consider using Phone System Direct Routing. With Direct Routing, you can use Phone System with virtually any telephony carrier._

Can I suggest this is changed to something like:

_If Calling Plans are not available to purchase, consider using Phone System Direct Routing or Operator Connect. With these optiojns, you can use Phone System with virtually any telephony carrier._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cb7019a-62dc-2dd0-cde3-2631a31fd7cd
* Version Independent ID: d17075df-11ce-4f94-8162-13534360f9d7
* Content: [Availability in South Africa - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-south-africa)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-south-africa.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-south-africa.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @Richard-Barr3tt Richard how are you?

Operator Connect has its owns characteristics and requirements, especially about carriers, as the description for it states

>existing carrier is a participant in the Microsoft Operator Connect program

However I'll check if another different mention to OC can be added.

Thanks for your feedback,

**Comment by CarolynRowe** [comment]
Hello,
Thanks for the feedback.  Instead, we will change the text to be more generic, but point to the definitive article for all PSTN connectivity options.
**If Calling Plans are not available to purchase, see [PSTN connectivity options](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8351) for all available options.**

**Comment by CarolynRowe** [comment]
https://docs.microsoft.com/en-us/microsoftteams/pstn-connectivity

**Comment by Richard-Barr3tt** [comment]
Sounds perfect Carolyn, thanks for looking at it so quickly
________________________________
