### ISSUE TITLE
Number of users in a Teams free org. 300 vs 500 000 depending on creation date

### ISSUE THREAD

**Issue by ChristianJBergstrom** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8352]
[Hi, I believe this is important information that should be added to the article. I've had several individuals in MTC asking/complaining about the inconsistent information.

Please see this response from the PG https://techcommunity.microsoft.com/t5/microsoft-teams/adding-members-to-my-organization-free-version/m-p/3061353/emcs_t/S2h8ZW1haWx8ZW1haWxfbWVzc2FnZXxLWUVET01SV1pGOU00UnwtMXxPVEhFUlN8aEs#M106137

Not sure if you're involved in the support articles but they also need to be updated.
https://support.microsoft.com/en-us/office/manage-your-teams-free-classic-organization-5208c55a-5d66-416c-b99a-1028c3fef637
https://support.microsoft.com/en-us/office/differences-between-microsoft-teams-and-microsoft-teams-free-classic-0b69cf39-eb52-49af-b255-60d46fdf8a9c

*edit* Got a response from the Teams PG that they will work the PMM's to sort things out as well.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce24a74-5dc2-3754-af64-1bbec243deb8
* Version Independent ID: 1d3f9154-6ba9-3fd0-8280-25af8a86afc9
* Content: [Upgrade Microsoft Teams Free (classic) to subscription - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/upgrade-freemium)
* Content Source: [Teams/upgrade-freemium.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-freemium.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by lindspea** [comment]
@ChristianJBergstrom thank you for reaching out and helping to improve Microsoft Docs. I'm involved on the Microsoft Docs side for writing/edits, etc. not on the support documents. I see you have referenced the article "Upgrade Microsoft Teams Free (classic) to subscription - Microsoft Teams. Please let me know if there is anything you're suggesting having amended in this article and I'll look into it.

**Comment by lindspea** [comment]
@scanum please can you reach out to the author for help on this?

**Comment by scanum** [comment]
@SerdarSoysal Hope this message finds you well. Could you please kindly help us on this issue? Thanks!

**Comment by tiburd** [comment]
This issue was resolved via a [Microsoft Teams Tech Community conversation](https://techcommunity.microsoft.com/t5/microsoft-teams/adding-members-to-my-organization-free-version/m-p/3061353/emcs_t/S2h8ZW1haWx8ZW1haWxfbWVzc2FnZXxLWUVET01SV1pGOU00UnwtMXxPVEhFUlN8aEs#M106137).

Closing this issue.

@scanum @SerdarSoysal
