### ISSUE TITLE
Only record shared content, video, and audio as needed

### ISSUE THREAD

**Issue by fmuecke** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8354]
With Skype for Business it was possible to explicitly select the streams you wanted to publish as a recording result: participants‘ video, audio and shared content.

Is this somehow possible with MS Teams recordings?

As a facilitator I like to have videos of the participants during the session to be able to see their reactions to the presented content.
I do not need those to be recorded every time.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
