### ISSUE TITLE
no Teams Public Preview features in Teams

### ISSUE THREAD

**Issue by mathewlowry** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8355]
I have followed the instructions - see screenshot - but I see no Teams Public Preview features in Teams (eg Loop components.

I am the only user of my organisation.
I am in Office Current Channel (Preview) - see screenshot.
I have an update policy of Follow Office Preview (default) - see screenshot.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5f1cdd1-09ff-f95d-6d50-e7880d34020f
* Version Independent ID: 59219640-305b-30c1-bc10-87e2633d95db
* Content: [Public preview in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-gb/MicrosoftTeams/public-preview-doc-updates)
* Content Source: [Teams/public-preview-doc-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/public-preview-doc-updates.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman*
![1](https://user-images.githubusercontent.com/19875849/149619715-5425b0b9-29c8-4500-9e91-68d99997ca2b.png)
![2](https://user-images.githubusercontent.com/19875849/149619718-50f70354-0569-4f5a-84d8-21be193087c1.png)
![3](https://user-images.githubusercontent.com/19875849/149619720-62a49fb5-f87a-49ba-8281-3b7d7738307f.png)
*

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
