### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by PeteHaigh-MSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8358]
Check **Stream classic migration** for more information.

That link ain't workin...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8935e913-806f-a92c-d09e-e67df4ffd1b4
* Version Independent ID: c7a41cde-66dd-d7cd-1316-42d20ed4841a
* Content: [Use OneDrive for Business and SharePoint for meeting recordings - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/tmr-meeting-recording-change)
* Content Source: [Teams/tmr-meeting-recording-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tmr-meeting-recording-change.md)
* Service: **msteams**
* GitHub Login: @serdars
* Microsoft Alias: **v-mahoffman**

**Comment by lindspea** [comment]
@PeteHaigh-MSFT thank you for pointing this out. Do you think this is the correct link to be added? - https://docs.microsoft.com/stream/streamnew/migration-details

**Comment by PeteHaigh-MSFT** [comment]
Looks right to me! 👍

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
