### ISSUE TITLE
"Islands" and "Skype for Business Only" still the only options in the Admin portal

### ISSUE THREAD

**Issue by bagobones** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#836]
Islands and Skype for Business Only are still the only two visible options in the portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49921e8a-55ac-f547-d4e2-d329f5089c2e
* Version Independent ID: 91c3433a-3684-95cd-3426-4a5877b33106
* Content: [Migration and interoperability guidance for organizations using Teams together with Skype for Business](https://docs.microsoft.com/en-us/microsoftteams/migration-interop-guidance-for-teams-with-skype)
* Content Source: [Teams/migration-interop-guidance-for-teams-with-skype.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/migration-interop-guidance-for-teams-with-skype.md)
* Service: **msteams**
* GitHub Login: @arachmanGitHub
* Microsoft Alias: **MyAdvisor**

**Comment by AndreaBarr** [comment]
@bagobones Thank you for this feedback

I'll make sure to get this visible options issues in front of the Teams/Skype for Business team for investigation. If you need this issues expedited please contact Support since they can also handle this to resolution. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by MarcoCarampanta** [comment]
This usually means your tenant hasn't been migrated to allow a "Teams Only" environment.

**Comment by bagobones** [comment]
I seem to get a different answer from each section about this. Support said it is still in preview, the road map states is is released, and this thread indicates it is still rolling out.

**Comment by kcsportal** [comment]
Yes, I'm having the same issue. I only see "Islands" and "Skype for Business Only."

**Comment by kcsportal** [comment]
2nd update: Even though everyone is now set to "Teams only" I am having trouble sending Teams chats to certain individuals. It says the person is still using Skype for Business and that the administrator has disabled chat for that person. 
![image](https://user-images.githubusercontent.com/41445124/46956417-4e5f2c80-d063-11e8-8643-38c01f946827.png)

**Comment by bjwhalen** [comment]
Teams only mode is not yet available to all tenants in the admin portal. But it is available to all tenants via powershell. look up Grant-CsTeamsUpgradePolicy.

**Comment by kcsportal** [comment]
I used this command and upgraded all my users but Skype for Business is still referenced in multiple places. In Outlook on the web, there is a Skype icon in the top right, but when you click on it, it tells you to use Teams. Why not just put a Teams icon there?


________________________________

**Comment by manny122** [comment]
I have SFB Online users in my org, and transitioned my first account to TeamsOnly mode.  It appears that this account in TeamsOnly mode, can receive SFB chats from same tenant and external tenants. However, NOT from consumer Skype clients.  Question #1, when will this work?   Question #2 This Teams user also can NOT add external tenant SFB contacts into his Chat folders as the querying in the Teams client doesn't appear query external orgs or tenants yet.  Is this safe to assume is normal for now?

**Comment by kcsportal** [comment]
Yes, I would also like for my education Teams users to be able to connect with Skype consumer. Mostly, this is to support "[Skype in the Classroom](https://education.microsoft.com/skype-in-the-classroom/overview)."

**Comment by MarcoCarampanta** [comment]
>           I seem to get a different answer from each section about this. Support said it is still in preview, the road map states is is released, and this thread indicates it is still rolling out.

Sorry to have missed your remark... 
The fact that the Road Map states "released..." doesn't mean it will instantly reach every single Tenant under Microsoft. (personally i have only seen a few dozens) - out of thousands.

**Comment by AndreaBarr** [comment]
@heyadamGIT Could you please answer these inquiries?

**Comment by SusanKocerka** [comment]
@AndreaBarr Thank you vice versa @heyadamGIT :-)
I read the whole docs about "Coexistence modes" multible times, so I guess PS is the only option to change the (Portal) behavior and therefor the associated TeamsUpgradePolicy for now. Right?

**Comment by heyadamGIT** [comment]
@bjwhalen docs.microsoft.com under Fundamental Concepts | #6 bullet point that reads "assign TeamsOnly mode to that user using either PowerShell or the Teams Admin Center." should read "assign TeamsOnly mode to that user using PowerShell (see Grant-CsTeamsUpgradePolicy help at https://docs.microsoft.com/en-us/powershell/module/skype/grant-csteamsupgradepolicy)."

Reason: confirmed Teams Admin Center does not have TeamsOnly mode exposed in the dropdown.

**Comment by heyadamGIT** [comment]
@kcsportal Good point about the icon! Can you please submit this via Feedback in the Office Admin portal? Thanks.

**Comment by heyadamGIT** [comment]
@manny122 Support for Skype consumer has currently been declined by engineering: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/16958347-skype-integration-consumer-federation You can vote up the feature request there.

Furthermore, autofill for external orgs and tenants who are federated is on the convergence roadmap here https://microsoftteams.uservoice.com/forums/555103-public/suggestions/20566714-federation

**Comment by JBFulc** [comment]
I'm stuck in the loop too:
![using skype and disabled](https://user-images.githubusercontent.com/41430508/50977011-3b84b880-14e9-11e9-8860-d839b0b037e4.PNG)
If you click on the start new chat:
![clicking on the skype option](https://user-images.githubusercontent.com/41430508/50977030-46d7e400-14e9-11e9-87f7-5ab94a0b9e0e.PNG)

Cant chat in teams p2p.

**Comment by bjwhalen** [comment]
TeamsOnly is now available to all in the admin UX.   Support for external contacts is in TAP and should be available publicly soon.  Support for Skype Consumer is not officially planned at this point.

**Comment by JBFulc** [comment]
> TeamsOnly is now available to all in the admin UX. Support for external contacts is in TAP and should be available publicly soon. Support for Skype Consumer is not officially planned at this point.

Unfortunately doesn't change the issues above. Cant chat in Teams... 'Administrator has disabled chat for this user' Even though chat is enabled and settings are teams only. Going to skype takes you to Teams.

**Comment by JBFulc** [comment]
> 'Administrator has disabled chat for this user' ---> did you check the user policies?
> 
> Get-CsOnlineUser -Identity [xxxx@contoso.com](mailto:xxxx@contoso.com) | fl TeamsMessagingPolicy
> Get-CsTeamsMessagingPolicy -Identity ######
> 
> And confirm if they have chat enabled on the policy assigned to the user, you can also manage the policies on the portal.
> 
> Note: While the full rollout of the setting has started... not everyone has it available yet, some Tenants are not yet migrated (older tenants, and most from US & Asia/Pac. should be already though.)
> 
> ie: out of ~10 tenants i have access to, teamsonly is only available in 3.

Yep all enabled.

**Comment by JBFulc** [comment]
In a drastic turn of events. 3 users one of which is my own account are able to chat. All three accounts have the same policies applied as the others.

**Comment by bagobones** [comment]
I can confirm that FINALLY "Teams Only" is now available as a per user migration policy in the portal.

Note to self, that rolling out to call customers / generally available can mean greater than 3 months.
