### ISSUE TITLE
Entering all devices in device alerting

### ISSUE THREAD

**Issue by kurtvanbalen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8361]
Would it be possible to add the possibility to add all users to the device alerting? Adding them all manually is impossible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad4aa355-090d-7315-aaf1-ed31a654e942
* Version Independent ID: 6bf8a83b-2bb6-6932-2e0d-6ccc742d1777
* Content: [Microsoft Teams Devices Monitoring and Alerting - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/alerts/device-health-status)
* Content Source: [Teams/alerts/device-health-status.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/alerts/device-health-status.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by lindspea** [comment]
@kurtvanbalen thank you for reaching out and helping to improve Microsoft Docs. Just for clarity, are you requesting to add to the functionality of Microsoft Teams Devices or are you requesting a change to the article with updated information?

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
