### ISSUE TITLE
Admins can or not control the client updates?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8364]
Hi Team,

On the same page you wrote:
_Teams doesn't give admins the ability to deploy updates through any delivery mechanism._
But also you wrote on the VDI section:
_You must uninstall the current version to update to a newer version._

I'm reading this so, that there IS a possibility to control the updates on regular workstations like on the VDIs. So perhaps you should be a bit more specific on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6da28da-eb7b-d3ae-4c2f-8f87803b1830
* Version Independent ID: 8c42d7a2-80c6-86dd-347a-ed6d8d909c41
* Content: [Teams updates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-client-update)
* Content Source: [Teams/teams-client-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-client-update.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @Petri-X,

I think the article clearly states that they are different processes:
- Non-VDI clients: update automatically
- VDI clients: you must run the MSI

Any process not included in the article is not supported, like running the VDI MSI to update Teams desktop client.

**Comment by Petri-X** [comment]
Hi @dariomws,
We could of course discuss if the message is "clearly" as this:
[Can admins deploy updates. . .](https://docs.microsoft.com/en-us/microsoftteams/teams-client-update#can-admins-deploy-updates-instead-of-teams-auto-updating)
Does not make any differences between non VDI and others.

But you made that very clear now.

Someone else of course could ask: what makes so big difference between VDI and non-VDI for Teams client that there must be so strong lines (supported vs. not supported). As at the end, it is still the same client.

But thank you for your reply.
