### ISSUE TITLE
Lack of clarity Section: Direct Routing (media bypass) – PSTN hairpin call (due to call forward/transfer)

### ISSUE THREAD

**Issue by rossual** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#837]
Great article but there is a real lack of clarity on the section around call forwarding. Could this be expanded upon?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c84773-337e-9df7-7fbd-fc9d94280711
* Version Independent ID: 223a78a0-67fd-8b96-be3f-153bb400101b
* Content: [Microsoft Teams Online Call Flows](https://docs.microsoft.com/en-us/microsoftteams/microsoft-teams-online-call-flows)
* Content Source: [Teams/microsoft-teams-online-call-flows.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/microsoft-teams-online-call-flows.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@rossual Thank you for this feedback

I agree this article needs expanding in the call forwarding section. I'll get this over to the Teams/Skype for Business team so we can get this area expanded. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @tonysmit are you able to provide more info on this scenario? Thank you

**Comment by CarolynRowe** [comment]
What is the exact issue?  We are working on a document about media bypass with Direct Routing, which will be published soon.

**Comment by get-itips** [comment]
Hi @rossual as @CarolynRowe said, a document with more information will be published soon. Hope this information helps you.
Thank you!

**Comment by rossual** [comment]
Do you have a time frame? The request has been open for 5 months.

Thanks.

**Comment by yogkumgit** [comment]
@get-itips  and @CarolynRowe  Thank you very much for the contribution and sharing this explanation. @rossual  it will be difficult for team to give you the exact time frame. However your valuable feedback is noted and is the part of the implementation plan. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by rossual** [comment]
Can we leave this open until it is delivered?

**Comment by kenwith** [comment]
@yogkumgit - we can leave this open until the content from @CarolynRowe is public and can then add a link here and close.

**Comment by CarolynRowe** [comment]
Please see the following docs:
- Plan for media bypass with Direct Routing: https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-plan-media-bypass 
- Configure media bypass with Direct Routing:  https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-configure-media-bypass
