### ISSUE TITLE
AllowCloudRecording should be **AllowTranscription** 

### ISSUE THREAD

**Issue by dendave** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8370]
Hi,

I see there's is typo in the use case scenario section
[333724](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording?ns-enrollment-type=Collection&ns-enrollment-id=q82jhdygq7k2kz#turn-on-or-turn-off-recording-transcription)

In the last scenario you mention 
<html>
<body>

I want transcription to be disabled for the majority of the users but selectively enable specific users who are allowed to transcribe. | Confirm Global CsTeamsMeetingPolicy has **AllowCloudRecording** = False.
-- | --

</body>
</html>

AllowCloudRecording should be **AllowTranscription** 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording?ns-enrollment-type=Collection&ns-enrollment-id=q82jhdygq7k2kz)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
