### ISSUE TITLE
Where's group chat analytics which is mentioned in the article?

### ISSUE THREAD

**Issue by raaghavvv** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8372]
As per below screenshot, it says we can track Analytics for group chat messages in teams but in Teams admin center there is no such report
![image](https://user-images.githubusercontent.com/61713813/150170166-da2b8598-368f-4f25-99f4-414f161306ac.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2758a3d6-c646-dcb0-2a31-c7b9b84e780b
* Version Independent ID: 8704c9fe-f8b0-82d2-bd83-3fd1a9ad638d
* Content: [Microsoft Teams user activity report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report)
* Content Source: [Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by raaghavvv** [comment]
![image](https://user-images.githubusercontent.com/61713813/150170675-a1cb2a2a-49b3-47f5-8795-dfa87608a12b.png)

**Comment by Reeced40** [comment]
@raaghavvv thank you for reaching out and helping improve Microsoft Docs. Please have a look at this link and let me know if it helps - https://docs.microsoft.com/microsoftteams/teams-analytics-and-reports/view-analytics
