### ISSUE TITLE
No SharePoint license - still possible to share files in chats

### ISSUE THREAD

**Issue by ChristianJBergstrom** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8373]
[Hi, this is more of a technicality but should perhaps be added or rephrased in the current wording, you decide.

I'm referring to "If users aren't assigned SharePoint licenses, they don't have OneDrive storage in Microsoft 365. File sharing works in standard channels, but users won't be able to share files in chats without OneDrive storage in Microsoft 365."

It's true that OneDrive won't be accessible but you will still be able to share files in chats, but one isn't compliant when it comes to the licensing terms and agreements.

Thanks.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60fd4eb7-6f1a-2dfa-27db-01c3a0d00f30
* Version Independent ID: c1688075-18bf-534d-f402-ee062840d83f
* Content: [How SharePoint and OneDrive interact with Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sharepoint-onedrive-interact)
* Content Source: [Teams/sharepoint-onedrive-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sharepoint-onedrive-interact.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by Reeced40** [comment]
@ChristianJBergstrom thank you for reaching out. Would you suggest adding a section after that sentence confirming this? Please let me know what you suggest and I'll look into making the change soonest.

**Comment by ChristianJBergstrom** [comment]
@Reeced40 thanks for the reply. I actually noticed that it works as described in the above quote when setting up a **new user without a SharePoint license**. If removing an **already existing SharePoint license** though the file sharing continues to work in channels and chats, but the user cannot access their OneDrive storage anywhere except from within Teams when sharing. It makes me wonder if this has something to do with the OneDrive retention period. But still, that should only be happening when the user account is deleted (30 days default, 93 days site collection bin). Is this something you can investigate with Microsoft or add someone to this thread? Thanks!

**Comment by scanum** [comment]
Hi @MikePlumleyMSFT Hope this message finds you well. Could you please kindly help us on this issue? Thanks!

**Comment by MikePlumleyMSFT** [comment]
@StephenRiceMSFT might be able to comment on how licensing affects sharing. The article in question has been retired in favor of [Overview of Teams and SharePoint integration](https://docs.microsoft.com/en-us/sharepoint/teams-connected-sites?bc=%2fmicrosoftteams%2fbreadcrumb%2ftoc.json&toc=%2fmicrosoftteams%2ftoc.json) and [Manage settings and permissions when SharePoint and Teams are integrated](https://docs.microsoft.com/en-us/sharepoint/manage-teams-sharepoint-experiences?bc=%2fmicrosoftteams%2fbreadcrumb%2ftoc.json&toc=%2fmicrosoftteams%2ftoc.json).

**Comment by ChristianJBergstrom** [comment]
@MikePlumleyMSFT @StephenRiceMSFT Thanks, I would still love to know about the above sharing scenario (when removing an existing SPO-license).
