### ISSUE TITLE
Exchange only more clearly conveyed.

### ISSUE THREAD

**Issue by lauramcdms** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8377]
Could we consider moving the info that this is Exchange accounts only earlier in the doc? The earlier references to M365 subscriptions are getting consumers with a personal subscription excited about the closer Teams integration with Outlook, followed by disappointment. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Use the Microsoft Teams Meeting add-in in Outlook - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by dariomws** [comment]
Hi @lauramcdms, thank you for your feedback.

This documentation is dedicated to admins for Teams for enterprise, if you check the main sections:
https://docs.microsoft.com/MicrosoftTeams/
https://docs.microsoft.com/microsoftteams/teams-overview
