### ISSUE TITLE
Misleading sentence in the Further information section

### ISSUE THREAD

**Issue by aalejandroaraujo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8379]
[Enter feedback here]
The sentence "Walkie Talkie should work well in low bandwidth situations, **or situations where your smartphone is connected and working**. " is misleading. Needs rewording to be meaningful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d91ddefc-3722-8bc2-bd9b-4a90ede28944
* Version Independent ID: 35e56a9d-a01c-4126-3750-aae1ed984f55
* Content: [Walkie Talkie application in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/walkie-talkie)
* Content Source: [Teams/walkie-talkie.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/walkie-talkie.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by dariomws** [comment]
Hi @aalejandroaraujo, thank you for your feedback.

I agree with you at the beginning but after reading the complete sentence I'm not convinced to reword it:
"Walkie Talkie should work well in low bandwidth situations, or situations where your smartphone is connected and working. **Walkie Talkie will not work when there is no connectivity at all**."

**Comment by aalejandroaraujo** [comment]
This way of rewording makes sense to me to. Thanks!

Alejandro Araujo Rajzner

On 30 Jan 2022, at 23:37, Manuela Scanu ***@***.***> wrote:

﻿

Closed #8379<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SkypeForBusiness%2Fissues%2F8379&data=04%7C01%7C%7C257c89add8024e2f0f1a08d9e441063d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637791790206714833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mIg%2F0IGqVdLCSe4BBKMwk6Ck5Gu%2BPlZAsA08DC1jeKg%3D&reserved=0>.

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SkypeForBusiness%2Fissues%2F8379%23event-5977149591&data=04%7C01%7C%7C257c89add8024e2f0f1a08d9e441063d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637791790206714833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=E4iBOEnwgwtDCL9XUelBPVl9fwSSon3PTvQi5kiSSag%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIWCBVN2TQCQFWENHM2MENDUYW4QTANCNFSM5MMEBYTQ&data=04%7C01%7C%7C257c89add8024e2f0f1a08d9e441063d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637791790206714833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1YGDpWOFH0SppPSH%2Fslsl%2FUWDHxqoMeXFJuFXqj6U64%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C257c89add8024e2f0f1a08d9e441063d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637791790206714833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KIiKUKKYAPWn9j980f0IHnJkeQ37aJ2V4M2oBENERzE%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C257c89add8024e2f0f1a08d9e441063d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637791790206714833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Y%2BiOEnwVIeWldPTQ%2F1yED3pkixskL%2FENc2PnVgY6dxc%3D&reserved=0>.
