### ISSUE TITLE
Next steps suggestions?

### ISSUE THREAD

**Issue by kmilessmg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#838]
Perhaps add instructions for those wishing to purchase phone plans, etc. e.g. Who to call, chat, message, etc.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae54019f-73df-4e8a-be75-3310fd585a61
* Version Independent ID: 581970cc-d568-b626-2895-3a66ee934f57
* Content: [Availability in Canada](https://docs.microsoft.com/en-ca/MicrosoftTeams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-canada#feedback)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-canada.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-canada.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@kmilessmg Thank you for this suggestion. 

I agree the information for people wanting to purchase phone plans should be included in the article. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by kenwith** [comment]
@kmilessmg - sorry for the long delay. I am working to find an answer on this.

**Comment by CarolynRowe** [comment]
Thank you for the suggestion.  We will consider this for a future release.

**Comment by yogkumgit** [comment]
@kmilessmg Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
