### ISSUE TITLE
Perfectly useless page - Uses circular links rather than specific steps with useful hyperlinks.

### ISSUE THREAD

**Issue by gholbrookEMD** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8385]
The page purports to include step by step instructions for adding minutes to a Skype/Teams account. It does no such thing. It monologues in generic terms about roughly what a person must do. Because it does not contain specific, actionable steps it does not actually enable the reader to take action. For example, where do I assign licenses? Where do I purchase minutes? Rather than answering these questions the page engages in circular linking with similar useless pages. At this point I have to decided whether to participate in this madness or simply purchase from a company that has streamlined the purchasing process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0b2993f-74b2-a59a-fee1-0a5ddcf9e9ff
* Version Independent ID: 01a02c95-cd74-9c82-f5a4-a6bc9adb52a9
* Content: [Set up Calling Plans - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-calling-plans)
* Content Source: [Teams/set-up-calling-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-calling-plans.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @gholbrookEMD 
An improvement to the article has been pushed recently and you should see it shortly in the published version.
Thanks for your feedback,

**Comment by MarceloPiresMagni** [comment]
Hello
I am having this same problem.
The step described as "Look for Communication  Credits under the additions". is not located.
I cannot effectuate the purchase of credits
Can you help me?
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/125655573/219623791-62b8e711-5dc9-46c1-8022-1dbba19a58fe.png)
