### ISSUE TITLE
Missing release notes for ver. 3.1.0

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8390]
Hi,
I'm very sorry, I should not be this fast :)
But just noticed that PS version 3.1.0 is out, but no documentation is published from that.

Do you have plans to add some what does that version contains? It is slightly interesting to see the release notes as amount of the commands seems to be the same (579) between 3.0.0 and 3.1.0 versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 173b5929-529b-938b-b6ab-59f05a5d69a8
* Version Independent ID: 0a3dfe5e-938f-933d-637e-b7449e3b8aa5
* Content: [Microsoft Teams PowerShell Release Notes - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-release-notes)
* Content Source: [Teams/teams-powershell-release-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-release-notes.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **gothambi**

**Comment by get-itips** [comment]
Hello @Petri-X thanks for your feedback, working on it

**Comment by get-itips** [comment]
article was updated. thanks!
