### ISSUE TITLE
Entire section needs to be updated - 'Let anonymous people start a meeting'

### ISSUE THREAD

**Issue by ChristianJBergstrom** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8392]
[Hello, the setting in the below attached link isn't only associated with dial-in scenarios, but really controls if an anonymous user can start a meeting or not. For example, picture this: An organization allows anonymous _join_ in their meetings and later decides that those users also should be able to _start_ a meeting. This includes any anonymous user with access to the meeting link.

When these anonymous settings (join and start) are enabled the anonymous users can consequently join and start a meeting. The graphical UI was recently updated when I made the Teams team aware of the misleading informational text in TAC. You can see the improved info in the Teams meeting policies under Participants & guests when hovering.

Thanks,

https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-participants-and-guests#let-anonymous-people-start-a-meeting
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4521de2b-1aae-93de-ee1a-222146194700
* Version Independent ID: b4f9087c-e1a3-8b47-917c-7c294d46fcca
* Content: [Manage meeting policies for participants and guests - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-participants-and-guests)
* Content Source: [Teams/meeting-policies-participants-and-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-participants-and-guests.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by lindspea** [comment]
@ChristianJBergstrom thank you for reaching out. Just for clarity, are you suggesting having a note added advising that anonymous users can join/start a meeting if they have the meeting link?

**Comment by ChristianJBergstrom** [comment]
@lindspea Hello! Well, more of removing all of the "dial-in" wording as this setting goes beyond that. It's basically a setting to decide if an anonymous user should be able to _start_ a meeting, and not only _join_ a meeting which is a separate setting.

This is just an example of how I would like to change it.

Original:

This setting is a per-organizer policy that allows for leaderless dial-in conferencing meetings. This setting controls whether dial-in users can join the meeting without an authenticated user from the organization in attendance. By default, this setting is turned off, which means dial-in users will wait in the lobby until an authenticated user from the organization joins the meeting.

Updated:

This setting is a per-organizer policy that allows an unauthenticated user to start a meeting. This setting controls whether anonymous users can join the meeting without an authenticated user from the organization in attendance. By default, this setting is turned off, which means unauthenticated/anonymous users will wait in the lobby until an authenticated user from the organization joins the meeting.

**Comment by CarolynRowe** [comment]
Let's do some research on this.  If this article pertains specifically to audio conferencing, then the dial-in conferencing  reference is correct.

**Comment by ChristianJBergstrom** [comment]
Hello again, this is the suggested text I gave the Teams PG.

![Anonymous info TAC](https://user-images.githubusercontent.com/90273807/154861525-2cf59de6-da43-4b39-a78d-f99bd49400f9.png)

This is how the changed it in Teams admin center as it's not only for dial-in.

![TAC](https://user-images.githubusercontent.com/90273807/154861599-5bde08d6-ca24-4cfc-8f95-d0bb9b26c0eb.PNG)

**Comment by ChristianJBergstrom** [comment]
@scanum The dial-in reference is unchanged. Should be updated as the setting controls all unauthenticated users. Thanks.

**Comment by iagdtd444** [comment]
Finally find the answer here, thanks!
We have some meetings that want to let the unauthenticated users join first and start the meeting from the meeting link. Without any authenticated users to join the meeting first.
I think this is the key option setting.
