### ISSUE TITLE
Will templates ever be supported in EDU?

### ISSUE THREAD

**Issue by cdkimmel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8393]
The page states that templates aren't available for EDU.  Will this ever be available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da3d209-eb82-1a62-9bd5-81ba18792cd4
* Version Independent ID: 94dca200-ab33-7a57-1504-e3ee7e5c610a
* Content: [Create a custom team template in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/create-a-team-template)
* Content Source: [Teams/create-a-team-template.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-team-template.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
