### ISSUE TITLE
Need to know Win 10 version needed

### ISSUE THREAD

**Issue by sysadmin-scs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8396]
What version of Windows 10 is required? Please include this in the article.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Build a Microsoft Teams Rooms image - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/console#Reimage)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by Reeced40** [comment]
@sysadmin-scs thank you for reaching out. You can find the version here:
https://docs.microsoft.com/microsoftteams/rooms/requirements#required-software-downloads

**Comment by MatthewCKelly** [comment]
The link does not provide the correct version..
during the process, one step is downloading the Deployment Kit (https://go.microsoft.com/fwlink/?linkid=851168)
it then extracts the files and uses the following file to verify the iso
SRSv2\Skype Room System Deployment Kit\$oem$\$1\Rigel\x64\Scripts\Provisioning\config.json

however this file also contains the incorrect VlscName of the image..
done in another issue [https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8934](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8934)
