### ISSUE TITLE
Microsoft Teams Rooms Standard without Audio Conferencing

### ISSUE THREAD

**Issue by flcev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8403]
Please add: 
Microsoft Teams Rooms Standard without Audio Conferencing
to the comparison

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-licensing.md)
* Service: **skype-for-business-online**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @flcev 
There is currently a row for Audio Conferencing and a subindex indicating that the availability may vary by region.
Did I understand correctly your feedback?
Thank you!

**Comment by flcev** [comment]
Yes and no, there is a cheaper separate license called
Microsoft Teams Rooms Standard without Audio Conferencing

But only the two other licenses in the comparison table.
I can’t remember the url know though.


Med venlig hilsen - Kind regards - Mit freundlichen Grüssen
Esben Vidstid
Kunderådgiver
***@***.***
FLC Danmark ApS
Olof Palmes Allé 47
DK8200 Aarhus N
www.flc.dk<http://www.flc.dk>
Tlf
Helpdesk
Mobil
Direkte
Email

+45 70 25 09 55
+45 70 20 92 96
+45 28 19 81 84
+45 36 98 35 74
***@***.******@***.***>


***@***.***

Fra: Andres Mariano Gorzelany ***@***.***>
Sendt: Wednesday, 26 January 2022 23.20
Til: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Esben Vidstid ***@***.***>; Mention ***@***.***>
Emne: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Microsoft Teams Rooms Standard without Audio Conferencing (Issue #8403)


Hello @flcev<https://url12.mailanyone.net/v1/?m=1nCqeB-0005Yw-3e&i=57e1b682&c=e-g5bkr06ldMbVeFxy3HpjYvkr6EaoI3iVvE9aS37jWOOcUKsF3aX4jenjT4iPzU-uHm1EYG2DTmgMzkAp573Rw4RB1-SvWbVGm6i_9Sdf3BIj_xza3P9inxlQisLSlT372pfEPrrEf5yfRgDZQXsDe_lR2qXFN60CdN38-xuxhiGLxL2TVthu16FI9_ZQedqYYGbN3vyZOnTf9BxUf2kBvQZwZc2xOMjDxCuuPMuQ8>
There is currently a row for Audio Conferencing and a subindex indicating that the availability may vary by region.
Did I understand correctly your feedback?
Thank you!

—
Reply to this email directly, view it on GitHub<https://url12.mailanyone.net/v1/?m=1nCqeB-0005Yw-3e&i=57e1b682&c=s8EbfmRYA3uoLut2tDZwkW77xUsGttj-hlcAjjazI89g5bQyotgT-0kj_RSjyjSTDwlayRyi0Pi_sBqelCPsRhv9KAWz3TRUSlXtinUpiuKconG-n4HqdOAVxNvWZ2QBQgW-YlRPvlFZhvKGKOJzHatSJuGCg24c-rH9AEN6aTFKtLKAP7qL8iaEOd2itbt81cJnY-WpmAhgCGCmT0Mhloff99636zfolO2E3OUd0l05EfvRmKOIjPpWs2hILgKCsw3BIfHzOp9qZJgW74Sv7YNcGj-OyEEF4j307wAPAbIWD2_WmBVylYowKhcq-l-z>, or unsubscribe<https://url12.mailanyone.net/v1/?m=1nCqeB-0005Yw-3e&i=57e1b682&c=y_WXIqFNRAnHrZEJZJ9OYWSDnNeVTe-Dg38SNBJqRuMemThG5KG0Kv8wUInwkQwMfgCPaj39qJmRqpYuljtb9-sQBVRuTWNNAjzoghCgwI02Bsuj01FVL5xtzz1tvJRm7o8mX7XHySGZffnqMGL1767BYIK0XbkcdVDggLssKdvulzEeyqwc20RX4-6K7BuqRJbzl2IOTrAFXYHKF-xQ6kxgAqIndagt_P0q0DfOnp3C9ZzCSpxr6g9RzykJ-of61WJUyG-F4LrDWh0B1oBJR6qZc-Etv0xLJsoktjon1K9e8CAOpvUK9DNKq2HnDvf2>.
Triage notifications on the go with GitHub Mobile for iOS<https://url12.mailanyone.net/v1/?m=1nCqeB-0005Yw-3e&i=57e1b682&c=KrUQz5_qz3we46s4x8FeoozfGd0LZVCpfnxVOhlLoKUfCc0bVLRLVHoTPlQ7OJxGslH2ZpFJ-PtHA0LCXmkYm8sb02JedwWqsr6NGaM6dSCz4YkPAE8cYkjiOBmnkmcSIZaUQ9NxwbfYiVFg6h38Qi6FcCaX4TZPHZ7g-F3AFDfewITlX5pMwJW7rC7bqgSoc5c0zev6gfzOJxh_5ghbOSogs1ezrBFqUi9zjfjidwVZgytlcC3kZuOStymtIqjyNqcctG6MnM6e-M33uvGJ81LAqswysx2KuKkSrlgqpYnVA8vz_tPFzPhb4SBq0U7-> or Android<https://url12.mailanyone.net/v1/?m=1nCqeB-0005Yw-3e&i=57e1b682&c=-nf1HT27eznlsGR-A7JPZrN-eU-qQnzl7VC0CZMqOPbbXAnnZGJH_UM1nQQevp8Llmu7f_eSNfzlc0V5fbh_QIk_y9PcdsrdVdrOCmw4klP7qDZlRsc3UNyGuRmtYLv6Q0qo0AAGvUwZ8uCK98U70P6Z3ul71SmSN5-bNZHyVu0DGW-Hdy1ZGxqWltWu3_K9i0CzWcehOoHOSm9v4gExKnUTz4ToslduGTx2MpLjwuXUbk148bD2hq0K9NLiAoiWFjfgEvzm4jUJmpASgs5WnEzeLhnc-jf68Wp9nhzpaxygVIfq2vv8dnCihKOwVcM1R9HSoalidtKwc3tn0_JPPTObtlEY5tTfjwfxIkY26uwVNRQc1160lJVJBENyPS0IqubTMRJ4AZlv3YtOImVGVQ>.

**Comment by get-itips** [comment]
@flcev Will ty to confirm

**Comment by get-itips** [comment]
I checked internally with the product group, and it was decided to leave as-is. I also was told the price does not differ.
Thanks for the feedback!
