### ISSUE TITLE
Version 3.1.0 is published, but no release notes available

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8407]
Title

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 173b5929-529b-938b-b6ab-59f05a5d69a8
* Version Independent ID: 0a3dfe5e-938f-933d-637e-b7449e3b8aa5
* Content: [Microsoft Teams PowerShell Release Notes - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-release-notes)
* Content Source: [Teams/teams-powershell-release-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-release-notes.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **gothambi**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by DEberhardt** [comment]
Well, I have opened a ticket and was advised to open this issue here...

>I hope you are well. I wanted to follow up with you and advise the next steps.
On the documentation page https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-release-notes ,  select Feedback > This page and feedback will go straight to GitHub. You can also follow the 'is this page helpful' link and send feedback directly.
>
>Please confirm if this was helpful.
>
>Kind Regards
><Name Removed>
>Microsoft 365 Support Ambassador
