### ISSUE TITLE
Legacy option to show remanining minutes missing?

### ISSUE THREAD

**Issue by Bmumpower2929** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8409]
Was the limit increased from 60 to 900 on the 1/14/2022
And i'm not seeing the legacy reporting option to check the available minutes anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be7b92a3-be5b-fd38-fb9e-7811212386fa
* Version Independent ID: da10315a-a190-4433-1e82-d22aef8ef1a0
* Content: [Complimentary dial-out period - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/complimentary-dial-out-period)
* Content Source: [Teams/complimentary-dial-out-period.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/complimentary-dial-out-period.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
Duplicate

**Comment by Bmumpower2929** [comment]
This one is specifically about the Legacy reporting options not being an option anymore. The 60-900 question was a duplicate
