### ISSUE TITLE
Old commands in refreshed page

### ISSUE THREAD

**Issue by dusansk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8412]
Hi,
How come you are using old (from SkypeonlineConnector module) commands in MicrosoftTeams module as commands do not exist? This page is not up-to-date. SkypeOnlineConnector module is not available and commands you are offering in this article simply cannot work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb2a9717-6565-8443-8833-f7fdce562781
* Version Independent ID: db88c4d6-5864-a481-86cf-465feb452d75
* Content: [Enable users for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-enable-users)
* Content Source: [Teams/direct-routing-enable-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-enable-users.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by JensTrier** [comment]
@dusansk thanks for the feedback! Is it possible for to you copy and paste the commands you are referring to?

**Comment by dusansk** [comment]
Hi Jens,My bad... updated the MS Teams module and of course get-csOnlineUser is available. I was barking up the wrong tree.regards,DusanOn 26 Jan 2022, at 15:24, Jens Trier Rasmussen ***@***.***> ***@***.*** thanks for the feedback! Is it possible for to you copy and paste the commands you are referring to?—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by JensTrier** [comment]
Hi @dusansk no worries! And please keep the feedback coming.
