### ISSUE TITLE
Powershell Cmdlet not available

### ISSUE THREAD

**Issue by DarlishaCampbell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8419]
[Enter feedback here]
The -AllowSIPDevicesCalling cmdlet is not available in Powershell and is not documented under "-Set-CsTeamsCallingPolicy"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05173ea8-db7c-a20d-3783-178b3d649190
* Version Independent ID: 05173ea8-db7c-a20d-3783-178b3d649190
* Content: [Configure SIP Gateway - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sip-gateway-configure)
* Content Source: [Teams/sip-gateway-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sip-gateway-configure.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by JensTrier** [comment]
@DarlishaCampbell Thanks for the feedback!

Which Teams PowerShell Module are you using?

If you use the latest Teams PowerShell Module GA version 3.1.0 I do see the -AllowSIPDevicesCalling switch on both New-CsTeamsCallingPolicy and Set-CsTeamsCallingPolicy. You can see it by using the gcm cmdlets like this "gcm New-CsTeamsCallingPolicy -Syntax" and "gcm Set-CsTeamsCallingPolicy -Syntax"

**Comment by CarolynRowe** [comment]
What PowerShell module version are you using?

**Comment by CarolynRowe** [comment]
Ah, I see Jens answered.  Thanks, Jens. Closing this Issue.
