### ISSUE TITLE
Instructions to setup Teams Account miss the most common scenario of Active Directory on Prem and Office 365

### ISSUE THREAD

**Issue by wadeal** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8422]
The instructions are a \<removed> nightmare to follow to setup an account for Teams Rooms as Microsoft seem to forget the most common scenario of having AD on prem and synced via AAD and using then Office 365.

The instructions given are to setup a new resource mailbox but you can't do that as "federated". Other options/scenarios give nothing about AD on prem or are about having Exchange or Skype for Business on prem.

What a nightmware.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-office-365)
* Content Source: [Teams/rooms/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-office-365.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by dstrome** [comment]
We do not tolerate profanity in our repositories. Please review the [Code of Conduct](https://opensource.microsoft.com/codeofconduct/) if you wish to continue participating in docs.microsoft.com repositories.
