### ISSUE TITLE
"automatically promoted to be the private channel owner" may be false

### ISSUE THREAD

**Issue by Peter-Wxin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8423]
> If a private channel owner leaves your organization or if they are removed from the Microsoft 365 Group associated with the team, a member of the private channel is automatically promoted to be the private channel owner.

It may not be true according the recent issue we've got in our Teams and this post: https://docs.microsoft.com/en-us/answers/questions/100064/teams-unknown-user-as-only-private-channel-owner.html

Do you mind verifying it, the "automatically promoted" thing?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Peter-Wxin Peter
Thanks for your feedback!
I tested this, and a member of the private channel was automatically promoted to owner. Both when the owner is deleted or the owner is removed from the group.
Thank you!

**Comment by get-itips** [comment]
@scanum
