### ISSUE TITLE
batch and status check commands

### ISSUE THREAD

**Issue by mohadadel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8424]
Hi there, 

In this line the variable is wrong with extra **s**
$user_ids = Get-Content .\users_ids.txt
New-CsBatchPolicyAssignmentOperation -PolicyType TeamsAppSetupPolicy -PolicyName "HR App Setup Policy" -Identity $user**s**_ids -OperationName "Example 1 batch"

Also this command is having extra **$**
**$**Get-CsBatchPolicyAssignmentOperation -OperationId f985e013-0826-40bb-8c94-e5f367076044 | fl

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888fe05b-1160-452f-90ba-deb19adb740f
* Version Independent ID: 4091c5e4-7a90-7fe4-2741-16bbb1f297c1
* Content: [Assign policies to users and groups - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/assign-policies-users-and-groups#assign-a-policy-to-a-batch-of-users)
* Content Source: [Teams/assign-policies-users-and-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-policies-users-and-groups.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
