### ISSUE TITLE
Please add live MS Teams alert so that assignee will know that they are tagged in the live components. Alert in email is not too helpful!

### ISSUE THREAD

**Issue by kwokric** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8425]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62fa48ba-86fc-85d1-4f32-c22f862536ff
* Version Independent ID: 778b3266-914d-db5f-d7df-66bda022d65c
* Content: [Manage live components in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/live-components-in-teams)
* Content Source: [Teams/live-components-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/live-components-in-teams.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
