### ISSUE TITLE
Reporting and auditing for external access?

### ISSUE THREAD

**Issue by jcrowland** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8426]
If the document explains how to manage external access, it would be helpful to understand how to report/audit on external access to understand if the feature is already being used (if the default is to be fully enabled) and what contact is occurring.  There's a lot to "managing" that isn't simply disabling/enabling.

There are lot of security/compliance issues to address with this new feature that is enabled by default.  I completely understand this document isn't supposed to address all of that, but it should at least be pointing administrators in some direction.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external access (federation) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access#block-unsolicited-contact-with-external-unmanaged-teams-users)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @jcrowland John,

how are you?

I am trying to confirm however I think that, currently, there isn't an usage report available related to that activity

https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-usage-report
