### ISSUE TITLE
The documentation relative to the Teams module has been removed from the meeting room management

### ISSUE THREAD

**Issue by vincentkurmi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8427]
Hi, 

As we can see here: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commits/live/Teams/rooms/with-office-365.md
You removed all the info regarding the Teams and SfbO module. 

I am surprised about that, what does it mean exactly? The "Enable-CsMeetingRoom" is not required anymore?
What is the best practice to manage the voice part of the meeting room?

Thanks for your help. 

Regards, 

Vincent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Deploy Microsoft Teams Rooms with Office 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-office-365)
* Content Source: [Teams/rooms/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-office-365.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @vincentkurmi, thank you for your feedback.

The article currently includes all the steps to enable MTR for Microsoft Teams. The steps to enable an MTR for Skype for Business Online were removed because the service is deprecated.

**Comment by vincentkurmi** [comment]
So it means, the cmdlet "Enable-CsMeetingRoom"  is not useful anymore and deprecated? 
https://docs.microsoft.com/en-us/powershell/module/skype/enable-csmeetingroom?view=skype-ps

**Comment by dariomws** [comment]
@vincentkurmi, if the cmdlet is not included in this article it should not be required to deploy MTR with Microsoft 365/Teams.

**Comment by vincentkurmi** [comment]
ok.

**Comment by danielniccoli** [comment]
> if the cmdlet is not included in this article it should not be required to deploy MTR with Microsoft 365/Teams.

@dariomws @vlethiec That is not sufficient, in my opinion. You cannot just remove an entire sections and not offer an updated way to enable a teams meeting room with a phone number.
