### ISSUE TITLE
Unclear support for Teams Noise suppression

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8428]
Hello,

This document doesn't answer the questions of whether Microsoft Teams supports noise suppression features within Citrix VDI environments.  Would be great if the status/limitations could more clearly provide guidance on that topic.

FYI - This other related document briefly notes "For this option, your computer's processor must support Advanced Vector Extensions 2 (AVX2)":
https://support.microsoft.com/en-us/office/reduce-background-noise-in-teams-meetings-1a9c6819-137d-4b3b-a1c8-4ab20b234c0d

Thanks,
Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @serdars
* Microsoft Alias: **v-mahoffman**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @chrisweis I am looking into this.

**Comment by get-itips** [comment]
Hello @chrisweis 

I could find this resource where you can see the feature support per platform, including VDI and the status of noise suppression

https://support.microsoft.com/en-us/office/meetings-and-live-events-5c3e0646-dc37-45ad-84a4-1666fac62d4e
