### ISSUE TITLE
Typo in the examples

### ISSUE THREAD

**Issue by Juan-Pablo-Rodrigo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8429]
As you can see below, the example codes are using  "$user_ids" as a variable
Then that variable is used as parameter in the New-CsBatchPolicyAssignmentOperation :   ... " -Identity $users_ids" ..

The problem is that the variable is called "user_ids" but in the command is changed to "users_ids" (extra 's' after 'user')
So when you copy/paste the code and run it,  you get an error saying that "$users_ids is null"

$user_ids = Get-Content .\users_ids.txt
New-CsBatchPolicyAssignmentOperation -PolicyType TeamsAppSetupPolicy -PolicyName "HR App Setup Policy" -Identity $users_ids -OperationName "Example 1 batch"

Thanks
JP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888fe05b-1160-452f-90ba-deb19adb740f
* Version Independent ID: 4091c5e4-7a90-7fe4-2741-16bbb1f297c1
* Content: [Assign policies to users and groups - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/assign-policies-users-and-groups#assign-a-policy-to-a-batch-of-users)
* Content Source: [Teams/assign-policies-users-and-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-policies-users-and-groups.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@scanum this can be closed thank you.
