### ISSUE TITLE
Unassigning policies?

### ISSUE THREAD

**Issue by angoo-atea** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8430]
There are no instructions regarding how to unassign policies for individuals or groups of users. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9cdd2f0-86e0-6001-1600-e1617b14e338
* Version Independent ID: c9cdd2f0-86e0-6001-1600-e1617b14e338
* Content: [Assign policies in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/policy-assignment-overview)
* Content Source: [Teams/policy-assignment-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/policy-assignment-overview.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by M0rfic** [comment]
Hi @angoo-atea 

Had a similar train of thought recently, and discovered they're somewhat hidden within the `Grant-***` docs, as there's no dedicated cmdlet yet (that I know of). Take for example [`Grant-CsOnlineVoiceRoutingPolicy`](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csonlinevoiceroutingpolicy?view=skype-ps), if you scroll to `Example 2`, you'll see:

![image](https://user-images.githubusercontent.com/909971/151520901-37570db7-e371-448e-9970-3e0c462e5d46.png)

Scrolling further down below, a similar thing is described for the `-PolicyName` parameter:

![image](https://user-images.githubusercontent.com/909971/151521147-d1f5c81c-c81f-43b1-8057-71730c47d518.png)

Same thing applies to `Grant-CsTeamsCallingPolicy` & `Grant-CsTenantDialPlan`

Kind regards

**Comment by M0rfic** [comment]
Hi @angoo-atea 

You didn't specify if you were using the Teams Admin Center, or PowerShell. If it's PS, I had a similar train of thought recently, and discovered they're somewhat hidden within the `Grant-***` docs, as there's no dedicated cmdlet yet (that I know of). Take for example [`Grant-CsOnlineVoiceRoutingPolicy`](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csonlinevoiceroutingpolicy?view=skype-ps), if you scroll to `Example 2`, you'll see:

![image](https://user-images.githubusercontent.com/909971/151520901-37570db7-e371-448e-9970-3e0c462e5d46.png)

Scrolling further down below, a similar thing is described for the `-PolicyName` parameter:

![image](https://user-images.githubusercontent.com/909971/151521147-d1f5c81c-c81f-43b1-8057-71730c47d518.png)

Same thing applies to `Grant-CsTeamsCallingPolicy` & `Grant-CsTenantDialPlan`

Not sure about groups of users though, I only needed to do this on a per user basis.

Kind regards

**Comment by angoo-atea** [comment]
@M0rfic 
Thanks for the reply. 

This activity for unassigning should be available in both the Teams admin center and PowerShell in a logical manner.
The Teams GUI today is seriously underdeveloped. The current 'Manage users' which appears in the most logical place is not in fact 'manage users' since you can only add here. There's no possibility here to see all the users assigned to the app and you can't unassign them here.

![image](https://user-images.githubusercontent.com/29600904/151548331-c7ee14f4-8c10-4717-ab38-0a09d81b72e4.png)

As for Powershell, there needs to be a logical positive and negative command for everything e.g. 'Grant-' or better 'Assign-' and 'Unassign-'  instead of the current only positive with a binary true/false parameter.

**Comment by M0rfic** [comment]
@angoo-atea 

In the GUI, you can filter the users using the dedicated button in the top-right corner of the table:
![image](https://user-images.githubusercontent.com/909971/151551483-93219f3a-c9d5-42b0-934f-37bdd7aec963.png)


You can then provide your filter conditions, which will display only the matching entries:
![image](https://user-images.githubusercontent.com/909971/151551757-89f4b93f-6a40-4e3f-8921-1228664670cf.png)

Next, you can select as many users as you want from the results, click the `Edit settings` button on the top-left of the table, and to unassign a voice routing policy for example, from the appropriate dropdown, select `Global (Org-wide default)`, and apply the changes:
![image](https://user-images.githubusercontent.com/909971/151552080-81a8486c-eb98-4615-83e3-5dc032e731a2.png)

Cheers

**Comment by angoo-atea** [comment]
@M0rfic 
Yes, found that, eventually. But it's not necessarily the most logical place to go looking for that administrative activity. Especially when the very obvious place is via the misleading "Manage users" button on the actual policy.
Microsoft generally, even though things have improved somewhat, still has a lot of problems with usability. 
These admin interfaces need to be far more user friendly.

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
