### ISSUE TITLE
Need clarification on instructions to set up derived trunk without powershell?

### ISSUE THREAD

**Issue by jlon125** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8433]
The documentation states:

_Sbc1.customers.adatum.biz – the derived trunk in a customer tenant that does not need to be created in PowerShell. You can simply add the name of the derived trunk in the customer tenant in the online voice routing policy without creating it (use derived trunk FQDN when setting up voice routing policy in TAC under Teams-Voice-Direct Routing-Voice Routes field SBCs enrolled)._

However currently it does not seem possible, as when adding a voice route in TAC, you can't manually enter an SBC, you can only choose from already defined SBCs, (so the list is empty). And since you don't add an SBC in a derived trunk scenario, the list will always be empty. 

The instructions need to be updated to clarify that you have to create the voice route for a derived trunk in PowerShell. The current instructions are inaccurate, unless there is a step that is being missed when setting up a derived trunk.

**Comment by scanum** [comment]
@jlon125 Thanks for submitting feedback. Could you please link the article you are referring to? Thanks!

**Comment by lindspea** [comment]
@jlon125 thank you for reaching out. Please can you let me know what article you are referring to?

**Comment by jlon125** [comment]
@lindspea  Hi Lindsay, here is the article:

https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants

**Comment by lindspea** [comment]
@jlon125 thank you for that. I see the article was updated last week. Please can you have a look and let me know if you need further assistance.

**Comment by jlon125** [comment]
Hello, this instructions still seem to be incorrect. 

_Sbc1.customers.adatum.biz – the derived trunk in a customer tenant that doesn't need to be created in PowerShell. You can add the name of the derived trunk in the customer tenant in the online voice routing policy without creating it (use derived trunk FQDN when setting up voice routing policy in TAC under Teams-Voice-Direct Routing-Voice Routes field SBCs enrolled)._

I can not see how you can add a voice route in TAC as they instruct, as you have to choose and SBC, and are not able to enter in an FQDN manually. 

The only way to achieve the derived trunk voice route IS in powershell, contrary to this excerpt. Can someone please confirm this?
