### ISSUE TITLE
creating image logo for meeting invitations should have references to MS recommended options

### ISSUE THREAD

**Issue by charlesmccann** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8434]
It would be great if the logo for meetings had an upload option...
but for this doc, we should at least have references to MS recommended hosting options (Azure Blob Storage + CDN). 
https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams#tips-for-creating-a-logo-for-meeting-invitations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Manage meeting settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@charlesmccann thank you for reaching out and helping to improve Microsoft Docs. I'll investigate, but in the meantime which link are you recommending having added to the article?
