### ISSUE TITLE
Please state clearly that pinning an app via setup policy will also install it.

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8436]
This is not explicit from the docs, which can be interpreted to mean that pin and install setup policies are exclusive (i.e., pin only pins the app and does not install)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f91604a-35b0-dfbb-55b2-b601cb0841b0
* Version Independent ID: 84bcd0d7-b4ed-f13e-c84b-2ec6a7661ae9
* Content: [Manage app setup policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-app-setup-policies)
* Content Source: [Teams/teams-app-setup-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-setup-policies.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by ashishguptaiitb** [comment]
The help article is updated. 
See "Pinning an app via an app setup policy also installs it." at https://docs.microsoft.com/microsoftteams/teams-app-setup-policies
@lindspea , @scanum , and @aosolis , shall we close this issue?
