### ISSUE TITLE
How via powershell?

### ISSUE THREAD

**Issue by itthing** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#844]
How can this be done via powershell?  I don't typically assign global admin permissions to my regular user and would like to avoid doing so, yet I would like to use an admin account for creating an org-wide team.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by carlalundberg** [comment]
It would be great to have the powershell command to create since we blocked users from adding sites so we don't have access through the app.

**Comment by AndreaBarr** [comment]
@carlalundberg Thank you for this feedback. 

I will make sure this is added to the backlog item.

**Comment by carlalundberg** [comment]
Thanks!  I also noticed that if the TeamAlias is multiple words, the script fails. I ended up adding a TeamsAlias to the CSV instead of using the TeamsName.

**Comment by expiscornovus** [comment]
Can this option be added to -AccessType parameter of the New-Team PowerShell cmdlet? So that you have the option to create a private, public or org-wide accesstype team?
https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps

**Comment by LolaJacobsen** [comment]
Hi, @itthing and @expiscornovus. 

Here's the reply from the feature PM: 

We currently don't support creating an org-wide team via PowerShell, and don't have any planned work to support this in the near term.

We don't expect regular users to be able to create an Org-wide team. At this point in time our recommendation is to sign-in with an global admin account to create the org-wide team. In the future Teams Service Admins will have persmissions to create this team type.

To help us better prioritize this request, we recommend that you post this feature suggestion on our product UserVoice (https://microsoftteams.uservoice.com/forums/555103-public?query=Org-wide%20Teams).

Thanks for the feedback.
