### ISSUE TITLE
Wrong information about Guest users interacting with Bots

### ISSUE THREAD

**Issue by marcus-castro-sp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8440]
The following statement is wrong:

"Bots can proactively message guest users, but guests can't interact with the bot. Guests can't message the bot one-to-one, mention the bot, or interact with adaptive cards that communicate with the bot."

Guest users are actually able to interact with the bot including with Adaptive Cards. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0735d322-f6f5-7cc8-9994-1420e3fb7baa
* Version Independent ID: f9b25b51-eb9c-63fa-b30e-e1490c8d31b6
* Content: [Teams apps behavior for non-standard users - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/non-standard-users#bots-installed-to-a-channel)
* Content Source: [Teams/non-standard-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/non-standard-users.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@marcus-castro-sp thank you for reaching out and helping improve Microsoft Docs. Are you suggesting removing the wording after "Bots can proactively message guest users"?

**Comment by marcus-castro-sp** [comment]
Hi @lindspea, no. I am suggesting remove:

"Guests can't message the bot one-to-one, mention the bot, or interact with adaptive cards that communicate with the bot"

Guest users are actually able to mention the bot and interact with Adaptive Cards.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
