### ISSUE TITLE
Please add additional non-supported content types

### ISSUE THREAD

**Issue by shung818** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8441]
[Enter feedback here]

Loop components are not supported for full-text search: eDiscovery for Loop components works like any other WXP file, but there are limitations. Full-text search (and, consequently, eDiscovery) may not find results for a given query if the matching text was only among the final edits to a file. Making new edits to the file will resume updating the search index.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 840dd36b-8c29-9738-4adc-ea9a7d277fd0
* Version Independent ID: b12c43c3-ed81-ace5-dfeb-77cac0f97fe9
* Content: [Conduct an eDiscovery investigation of content - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/ediscovery-investigation)
* Content Source: [Teams/eDiscovery-investigation.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/eDiscovery-investigation.md)
* Service: **msteams**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@shung818 thank you for reaching out and helping improve Microsoft Docs. Just for clarity, are you suggesting this in a note for the article as you stated above?

**Comment by shung818** [comment]
Hi there,

Apologies for the late response. It may be confusing for customers as the

Documentation indicates https://docs.microsoft.com/en-us/microsoftteams/loop-components-in-teams#loop-components-and-fluid-files
Loop components created in Teams are backed by a .fluid file stored in the creator's OneDrive. Being a file in OneDrive means that users can create, discover, and manage Loop components (.fluid files) as easily as any Office document. .fluid files work with data governance features like eDiscovery, auditing, reporting, and legal hold.

However, PG had helped to confirm:
.fluid files and discoverability:  Although the files are discoverable, the content itself is not readable.
