### ISSUE TITLE
Default deletion in 60 days and not 120 days

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8442]
The default deletion for meeting recording is set for 60 days and not 120 days as described in the page
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee6d4c1c-6f16-b1a4-c4a9-be4e6d1f95b7
* Version Independent ID: 50ad835d-ed7f-18c6-34ba-322c1574f9c2
* Content: [Meeting policies and meeting expiration in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/meeting-expiration#changes-to-meeting-expiration)
* Content Source: [Teams/meeting-expiration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-expiration.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@nikki-c The default expiration date was changed from 60 to 120, however, if there is already a policy in place, the default expiration date won't be updated. This new default expiration date only applies to organizations that don't currently have any meeting expiration policies.

**Comment by gregorybrunn** [comment]
Are you saying if someone started with the default of 60 days and did not apply any specific policy then the 120 days would never take effect? @lindspea

**Comment by lindspea** [comment]
@gregorybrunn from what I understand the default expiration date won't be updated if there is a meeting expiration policy in place already, meaning the default expiration date for that will be 60 days, not 120 days.
