### ISSUE TITLE
Please add statement manually delete appdata folder is  unsupported scenario in "Non-persistent setup"

### ISSUE THREAD

**Issue by myuge001** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8443]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/90367937/151923168-a31de050-3ab7-4c4c-9418-3af98bc87608.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/EN-US/microsoftteams/teams-for-vdi?source=docs)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @serdars
* Microsoft Alias: **v-mahoffman**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by myuge001** [comment]
Hello, @scanum , Team.

Could you let us know ETA and accelelate of update.
As I describe below Business Impact, This update is indispensable to explain customer.

For issues that we are currently addressing, it will be a description necessary to prove to the customer that it is not an issue with Teams and customer is using an unsupported scenario.
 
Business Impact:
Issue is occurring S500 customer, and about 40,000 users are affected this issue.
Customer's CIO and other executive is concerned this issue.

Thank you!

**Comment by dariomws** [comment]
Hi @myuge001, thank you for your feedback.

Could you kindly share the content of the screenshot in text format, please?

**Comment by dariomws** [comment]
If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=myuge001

**Comment by myuge001** [comment]
hi, @dariomws 
I'm sorry to see a slow reply.I will share text format.
And I have Microfsoft alias (myuge) , so I will check guidanse you shared.


Customer is using Non-Persistent environment especially Volatile client machine and Teams desktop app cannot start after rebooting PC and it will show "We are sorry-we've run into an issue"
The investigation found that manually delete the following cache folder is an unsupported scenario.

　C:\Users\username\AppData\Local\Microsoft\IdentityCache (%localAppdata%\Microsoft\IdentityCache)
　C:\Users\username\AppData\Roaming\Microsoft\Teams (%appdata%\Microsoft\Teams)

IcM: https://portal.microsofticm.com/imp/v3/incidents/details/279259445/home

Ensure that customers understand exactly that they are out of support, could you add below statement on this article.

-statement
In Volatile Client Machine and Non-Persistent Setup Machine, mannualy deleting Teams Cache stored in the followings locations is NOT supported due to resulting in Broken State in Teams. The only supported scenarios is to sign-out Teams and to uninstall Teams Client using Windows Installer afterward.
C:\Users\username\AppData\Local\Microsoft\IdentityCache (%localAppdata%\Microsoft\IdentityCache)
C:\Users\username\AppData\Roaming\Microsoft\Teams (%appdata%\Microsoft\Teams)

**Comment by tiburd** [comment]
This issue can be closed after PR #8482 is merged.
