### ISSUE TITLE
 Scripts on this page need updating with the new Set-CSPhoneNumberAssignment cmdlet.

### ISSUE THREAD

**Issue by reload-dev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8448]
Scripts on this page need updating with the new Set-CSPhoneNumberAssignment cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5566de7d-1d1e-ba92-743b-dc772b49752a
* Version Independent ID: c15342ff-eb3a-5f14-4bba-217c31aa1299
* Content: [Decide how to manage attributes after decommissioning - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/cloud-consolidation-managing-attributes)
* Content Source: [Skype/SfbHybrid/hybrid/cloud-consolidation-managing-attributes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/cloud-consolidation-managing-attributes.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by JensTrier** [comment]
@reload-dev Thanks for the feedback! We'll get it fixed.

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by JensTrier** [comment]
@scanum I'm investigating this, no need for others involvement at the moment.

**Comment by JensTrier** [comment]
This has been fixed. Please close

**Comment by CarolynRowe** [comment]
Closing this issue....
