### ISSUE TITLE
International Calling plan

### ISSUE THREAD

**Issue by JMCA2** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8450]
According to this page (and other on the docs) there are 2 options: 1) Domestic Calling Plan 2) Domestic+International Calling Plan

However, there is a third calling plan (maybe it was introduced recently? as I dont remember it been there before) which is International Calling Plan (at same price as the domestic plan).

It is my understanding that this plan allows to place international calls, but not domestic calls, but have not tried.
But maybe it's an add-on only available to add international calls to a domestic plan?
This would need to be confirmed before adding to the docs.
![image](https://user-images.githubusercontent.com/802183/152028539-8e12b986-a14e-406a-affb-d623533330a1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 243fa83d-b7bf-323a-a14a-026915d3d058
* Version Independent ID: fd4a310b-3144-4a8b-1bde-c2efd0c87377
* Content: [Calling Plans for Microsoft 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/calling-plans-for-office-365#feedback)
* Content Source: [Teams/calling-plans-for-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/calling-plans-for-office-365.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by JMCA2** [comment]
It's also missing for all countries on https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @JMCA2, thank you for your feedback.

I cannot see that calling plan in my demo tenant. Could you kindly let me know where your tenant is located?

**Comment by JMCA2** [comment]
@dariomws Spain

**Comment by dariomws** [comment]
@JMCA2, I have verified in another tenant located in Spain and I cannot see it. My apologies but I cannot add it to the article without confirmation.

**Comment by JMCA2** [comment]
@dariomws with further testing I have confirmed the option appears only if you have a domestic calling plan. so it seems like an additional plan only available if you already have domestic, allowing you to also make international calls
