### ISSUE TITLE
Audio Conferencing using User minutes

### ISSUE THREAD

**Issue by JMCA2** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8451]
On this page it mentions that after the complimentary audioconferencing minutes run out, communication credits are required.

This is not true. We have tested on our own that after the complimentary minutes run out, minutes are taken from the calling plan assigned to the user who initialed the audioconference. This has also been confirmed by Microsoft Support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be7b92a3-be5b-fd38-fb9e-7811212386fa
* Version Independent ID: da10315a-a190-4433-1e82-d22aef8ef1a0
* Content: [Complimentary dial-out period - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/complimentary-dial-out-period)
* Content Source: [Teams/complimentary-dial-out-period.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/complimentary-dial-out-period.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @JMCA2 I am looking into this.

**Comment by get-itips** [comment]
Hello @JMCA2 
I checked internally with the product group and I received confirmation that what is currently in the article remains and no further edits are necessary.
Thank you
