### ISSUE TITLE
Teams Meeting and Office 2021 compatibility

### ISSUE THREAD

**Issue by dhammondhelient** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8453]
Hello,

Under "Teams Meeting add-in in Outlook for Windows" on this page, only Office 2013, 2016, and 2019 are listed as being supported by Teams.  Is Office 2021 also supported now?  If not, will there be a new release of Teams soon that will support MS Office 2021, or version 2102 more specifically?

Thank you for your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Use the Microsoft Teams Meeting add-in in Outlook - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook#feedback)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
