### ISSUE TITLE
Maximum lengths?

### ISSUE THREAD

**Issue by zippy72** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8459]
[Enter feedback here]
Maximum lengths for team, channel and folder names would be really helpful. It took a lot of time and error to find that channels seem to be limited to 50 character names (at least through the version of the Graph API that I'm using at the moment), while so far I haven't run into a similar issue with teams or folders, I expect it's a matter of time. Can you add this information please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by dariomws** [comment]
Hi @zippy72, thank you for your feedback.

This issue is the same as:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8026
An update is in progress to add this limit to the article.

**Comment by adrichema** [comment]
Hi @scanum, Could you please inform me about the reason for closing this issue? The referenced documentation have not been updated since 11/13/2021. Hope to hear from you, thanks!
