### ISSUE TITLE
There is a syntax error in this sample script

### ISSUE THREAD

**Issue by stevepogue** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8460]
t C:\temp\CleanUpTeams.ps1:25 char:71
+ ...   Write-Output "Uninstall failed with exception $_.exception.message"
+                                                                         ~
The string is missing the terminator: ".
At C:\temp\CleanUpTeams.ps1:12 char:1
+ {
+ ~
Missing closing '}' in statement block or type definition.
At C:\temp\CleanUpTeams.ps1:27 char:2
+ }
+  ~
The Try statement is missing its Catch or Finally block.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a316aa8-e3c9-c6d3-2509-6b4601ad3e8a
* Version Independent ID: 1e90dd88-4afd-ef8c-2f16-0263416ce5bb
* Content: [PowerShell script sample - Teams deployment cleanup - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/scripts/powershell-script-deployment-cleanup)
* Content Source: [Teams/scripts/powershell-script-deployment-cleanup.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/scripts/powershell-script-deployment-cleanup.md)
* Service: **msteams**
* GitHub Login: @HowlinWolf-92
* Microsoft Alias: **v-mahoffman**

**Comment by dariomws** [comment]
Hi @stevepogue, thank you for your feedback.

It works for me:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/33589238/153707062-2f0d9149-fe90-4708-8f04-ba5d0dcb7064.png">
