### ISSUE TITLE
Version Numbers

### ISSUE THREAD

**Issue by timr1972** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8462]
When you refer to version numbers, do you want to update this to a minimum support version ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 344ac314-e98e-ab21-ef47-fb0da80ec884
* Version Independent ID: 8f3d2fe8-5d96-4298-f875-fb3e64688afc
* Content: [Remote provisioning and sign in for Teams Android devices - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/remote-provision-remote-login)
* Content Source: [Teams/devices/remote-provision-remote-login.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/remote-provision-remote-login.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by Reeced40** [comment]
@timr1972 thank you for reaching out and helping to improve Microsoft Docs. Would it be helpful to have this link added to the article - https://support.microsoft.com/office/system-requirements-for-teams-for-personal-and-small-business-use-dae0234b-839c-4f85-ae75-d14ad2baa978

**Comment by timr1972** [comment]
Really sorry i didn’t get a notification for this comment; yes that link would be useful!
