### ISSUE TITLE
Information about anonymous policy usage doesn't make sense - please update

### ISSUE THREAD

**Issue by ChristianJBergstrom** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8470]
[Hello, in the below link there's contradictory information.

Example:

"You can use either policy, organization-wide or per-organizer, to manage anonymous join." (not really true, it's depending on what you want achieve. You can't only use per-organizer policy for allowing).

Followed by:

"Since both the organization-wide and per-organizer policies control anonymous join, the more restrictive setting will be effective."

Also the purple box doesn't really make sense. Please consider rephrasing that part too.

https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams#using-powershell-to-configure-per-organizer-policy

You can perhaps use this purple box instead? https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps
-AllowAnonymousUsersToJoinMeeting (located at this parameter)

]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Manage meeting settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams#using-powershell-to-configure-per-organizer-policy)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by lindspea** [comment]
@ChristianJBergstrom thank you for reaching out. The article does mention that organization-wide policy setting will be deprecated in the future and the per-organizer policy will be the only way to control anonymous join, so it might be better to leave the wording as is, but please let me know if you still recommend having anything changed.
