### ISSUE TITLE
Usage of Service Principal For the Dataset Authentication

### ISSUE THREAD

**Issue by Avinash1919** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8472]
Hi

I am trying to configure a service principal with the necessary role assigned. I updated the ownership and the dataset credentials using the powerbi rest API using powershell.

I get the following error

The credentials provided for the MicrosoftCallQuality source are invalid. (Source at MicrosoftCallQuality.). The exception was raised by the IDbCommand interface

Wondering if the service principal is allowed to be used with the live connection dataset.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 067e8376-df94-9a44-5263-cd1fc84879bf
* Version Independent ID: 924240c8-52c5-42db-36b8-28751f838784
* Content: [Install Power BI Connector to use CQD query templates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cqd-power-bi-connector#limitations)
* Content Source: [Teams/CQD-Power-BI-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-Power-BI-connector.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by Reeced40** [comment]
@Avinash1919 thank you for reaching out and helping to improve Microsoft Docs. Please can you let me know if this links helps at all - https://community.powerbi.com/t5/Service/PowerShell-scripts-with-Service-Principal-As-Member-scope/td-p/1207223
