### ISSUE TITLE
Removal Of Custom Praise Badges?

### ISSUE THREAD

**Issue by JordanTheITGuy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8479]
Is there any particular reason why Microsoft decided to remove the custom praise badges? We actually used them to praise people internally when they were caught promoting our core company values as a way to acknowledge each other's hard work... 

Why get rid of such a nice and valuable customization? With no explanation?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
