### ISSUE TITLE
[MS Teams] Is there transaction fee for apps?

### ISSUE THREAD

**Issue by jychaaacha** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8480]
[Enter feedback here]

I want to know the details of the price policy for Apps.
I wonder if there is an additional fee related to app installation and use from the perspective of developers and users.
e.g. transaction fee for connectors, bot, message extensions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2081f0e-cc69-8c64-2fe9-5ba8a9e36ed3
* Version Independent ID: 629041e6-01c5-f78c-84c6-8ede02ee0ade
* Content: [Apps, bots, & connectors in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/deploy-apps-microsoft-teams-landing-page)
* Content Source: [Teams/deploy-apps-microsoft-teams-landing-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/deploy-apps-microsoft-teams-landing-page.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @jychaaacha, thank you for your feedback.

I understand that each app has its terms of use, licensing model and price. You should check directly with the app vendor.
