### ISSUE TITLE
Dial Plan issue

### ISSUE THREAD

**Issue by dmcher** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8481]
[Enter feedback here]
(Optional) Configure a dial plan

Hi Team,

According to my test dial plan only works for users who have enabled with Phone System license. If Administrator assigns dial plan without Phone System client will  not get any dial plan rules during sign in.

Can you check it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d4b1670-ab39-621e-025e-17d7d747cc09
* Version Independent ID: dcdd8284-ad29-4e46-4731-63fbbce08fb0
* Content: [On-network Conferencing for Audio Conferencing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-on-network)
* Content Source: [Teams/audio-conferencing-on-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-on-network.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by dariomws** [comment]
Hi @dmcher, thank you for your feedback.

I have verified and I could assign a dial plan to a user without the Teams Phone Standard license.
