### ISSUE TITLE
Steps to Assign Dial Plan to Group

### ISSUE THREAD

**Issue by scrubbles** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8487]
Hello,

I have the task of assigning dial plans to various users would like steps to do this via group. The article says you can assign policies in batch or by group but I do not see any way to do that? If it is not possible could you change the text below or add a note that it is not possible so people do not spend time trying to figure out how to do it?

> Assign a dial plan to users
> You assign a dial plan in the same way you assign policies. You can assign a policy directly to users, either individually or at scale through a batch assignment (if supported for the policy type), or to a group that the users are members of (if supported for the policy type).To learn about the different ways that you can assign policies to users, see [Assign policies to your users in Teams](https://docs.microsoft.com/en-us/microsoftteams/policy-assignment-overview).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 451b44cf-961a-5bf5-e4b3-16b96e008dd7
* Version Independent ID: 54e706e1-aaa2-3a03-b8c6-5e96244b85ac
* Content: [Create and manage dial plans - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-and-manage-dial-plans)
* Content Source: [Teams/create-and-manage-dial-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-and-manage-dial-plans.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @scrubbles 

Have a look at https://docs.microsoft.com/en-us/powershell/module/teams/new-csbatchpolicyassignmentoperation?view=teams-ps for batch assignment

and

https://docs.microsoft.com/en-us/powershell/module/teams/new-csgrouppolicyassignment?view=teams-ps for group assignment

Using the Teams PowerShell

Hope this answers your question,

**Comment by get-itips** [comment]
@scanum
