### ISSUE TITLE
Question about phone system license

### ISSUE THREAD

**Issue by kongqi0** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8488]
https://docs.microsoft.com/en-us/microsoftteams/here-s-what-you-get-with-phone-system

For cloud voicemail, the doc says "Note that users do not need a Phone System license, nor do they need to be voice enabled to use Cloud Voicemail features."

For call transfer, the doc says "Note that users do not need to be voice enabled to receive transferred calls from another user."

So for user who need receive transferred calls still need Phone System license?

Are "voice enabled" and "Phone System license" same thing or different thing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cfead3c-b0d8-c22a-aa22-63e79fe53ed3
* Version Independent ID: 10745875-3d3e-42bb-e324-ff4c83968ccf
* Content: [Here's what you get with Teams Phone - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/here-s-what-you-get-with-phone-system)
* Content Source: [Teams/here-s-what-you-get-with-phone-system.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/here-s-what-you-get-with-phone-system.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
