### ISSUE TITLE
Clarify we are talking about common area phone objects

### ISSUE THREAD

**Issue by JohanVeldhuis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8495]
This part is confusing for some customers:

Accounts for common area phones from the Skype for Business Server can't be migrated to Microsoft Teams. Follow the steps in this article to recreate those accounts for Teams, and, if required, migrate your PTSN connectivity.

Would recommend calling out that this is applicable to common area phone objects created in SfB in which case they cannot be migrated to Teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ab5215-f24f-75cf-bb92-16ac0ff5e5ca
* Version Independent ID: 701cc58f-d2ea-cbb6-f5fc-47b9fbfb1119
* Content: [Set up the Common Area Phone license - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-common-area-phones)
* Content Source: [Teams/set-up-common-area-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-common-area-phones.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by lindspea** [comment]
@JohanVeldhuis thank you for reaching out and helping to improve Microsoft Docs. I see the article has got a note covering this information you requested.  Please let me know if you need help with anything further.

**Comment by JohanVeldhuis** [comment]
Hi Lindsay,

Please talk to Tony Woodruff about it we discussed the issue via chat also and he agreed that it needs to be updated.

Regards,
Johan

**Comment by cazawideh** [comment]
@JohanVeldhuis Can you elaborate on why we need to call this out as a common area phone 'object', versus what is currently in the note?

CC: @scanum @lindspea

**Comment by JohanVeldhuis** [comment]
Hi Caitlyn,

Because in SfB common area objects were not normal user accounts they were special objects. While in Teams these are normal user objects however with a common area license. This is also the reason we cannot migrate them. In some cases, customers have created "normal" user objects which they are using for common area phones. For that last scenario it is supported to move them to Teams.

Hope this answers your question.

Regards,
Johan

**Comment by cazawideh** [comment]
Updated the article with this change. Thanks.
