### ISSUE TITLE
No information on the Sentinel Solution for Teams

### ISSUE THREAD

**Issue by lkchild** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8498]
The new Sentinel Solutions preview has a Teams solution.  The Usage Information + Support tab of that solution links here for documentation, but there is no content or "getting started" here for installing that solution, it's all the older way of doing things.  

There doesn't appear to be any instructions on using the Sentinel Solution for Teams, and if you click Create and then Review+Create it fails as it requires inputs to be added which are not explained (e.g. there's a box for a user ID, but no information on what user ID is needed, is this a user ID for the solution to use to scan all the time like a service account, or is this the admin user ID who's creating it which we wouldn't want saved?)

Please can you update this guide?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0157c71c-b57d-ecdf-d2de-1d6f02eaf238
* Version Independent ID: 25eae9c1-9730-a88b-066d-75e9116f389c
* Content: [Azure Sentinel and Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/teams-sentinel-guide?WT.mc_id=Portal-Microsoft_Azure_Marketplace)
* Content Source: [Teams/teams-sentinel-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-sentinel-guide.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **tracyp**

**Comment by lindspea** [comment]
@lkchild thank you for reaching out and helping to improve Microsoft Docs. This information will be updated in the upcoming weeks. See note in one of the linked articles - "Azure Sentinel is now called Microsoft Sentinel, and we’ll be updating these pages in the coming weeks. "
