### ISSUE TITLE
Missing package in documenation

### ISSUE THREAD

**Issue by gertjan015** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#850]
We miss the creation of this package in the steps: "SRS v2 - Configure SRS Setup Software package"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29b0551a-0c9b-8934-5e4b-d34fe292ec8e
* Version Independent ID: 1e19dcb0-59cd-5e9f-0afc-e30bc4cbf80f
* Content: [Deploy Skype Room Systems by using System Center Configuration Manager](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/room-systems-scale)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/room-systems-scale.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/room-systems-scale.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @Turgayo
* Microsoft Alias: **jambirk**

**Comment by AndreaBarr** [comment]
@gertjan015 Thank you for this feedback

I agree we need the steps for SRS v2 - Configure SRS Setup Software package. I will get this over to the Teams/Skype for Business team so we can get these steps documented. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by jambirk** [comment]
We believe this issue is resolved by PR 1209. Please let us know if this still needs attention.
