### ISSUE TITLE
Repeated words

### ISSUE THREAD

**Issue by tiagoroxo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8501]
In this paragraph seems that there are some repeated words, check below:

"To assign, configure, and list number manipulation rules on SBCs, use the [New-CSOnlinePSTNGateway](https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlinepstngateway) and [Set-CSOnlinePSTNGateway](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinepstngateway) cmdlets together with the InboundTeamsNumberTranslationRules, InboundPSTNNumberTranslationRules, OutboundTeamsNumberTranslationRules, OutboundPSTNNumberTranslationRules, InboundTeamsNumberTranslationRules, InboundPSTNNumberTranslationRules, OutboundTeamsNumberTranslationRules, and OutboundPSTNNumberTranslationRules parameters."

thanks team

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6981866f-a685-d802-d64f-98685a5c658d
* Version Independent ID: a1f83744-abb7-4c33-6f60-19ff2732871c
* Content: [Translate phone numbers for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-translate-numbers)
* Content Source: [Teams/direct-routing-translate-numbers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-translate-numbers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Thanks.  I'll fix this one.  Closing this issue.
