### ISSUE TITLE
How to contact "Call Quality Dashboard team"

### ISSUE THREAD

**Issue by g-martinse** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8502]
The issue is about section "Error Codes" on this page

There the following sentence is written:
_If you encounter any additional errors outside of this scope, please notify the **Call Quality Dashboard team** so that we can help troubleshoot the issue and update the documentation as appropriate._

Please provide details how to contact "Call Quality Dashboard team"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 067e8376-df94-9a44-5263-cd1fc84879bf
* Version Independent ID: 924240c8-52c5-42db-36b8-28751f838784
* Content: [Install Power BI Connector to use CQD query templates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cqd-power-bi-connector)
* Content Source: [Teams/CQD-Power-BI-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-Power-BI-connector.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
