### ISSUE TITLE
How to remove package policy or revert to default policy?  Once assigned there is no easy away to revert back

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8504]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3f54e11-f5b6-1ab9-6148-f053c66dd79b
* Version Independent ID: 27b514bf-1500-ef6d-ac11-e1860416ec04
* Content: [Manage policy packages in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-policy-packages)
* Content Source: [Teams/manage-policy-packages.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-policy-packages.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by robinpoulose1** [comment]
One of my client accidently assigned  Healthcare and patient room  package policy to Microsoft team group where all org user were member of it.  Once the policy was assigned chat and call apps were disabled immediately.  Now, when we try to revert back there is no easy way or we cannot revert back now. 
One click we can assign all package policy but there is no one click way to revert back no proper docs to revert the changes

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
