### ISSUE TITLE
Power BI using CQD data 

### ISSUE THREAD

**Issue by eblingus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8505]
Text says: "For example, a filter on Duration (Minutes) < "065", would show streams with duration less than 2 minutes (The leading '0' is needed for the filter to work as expected)."

It is not possible to filter that field in Power BI using "<", or any other numeric comparison, as Power BI sees it as text data and only allows use of text filters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a455280-ea8e-2ddf-2965-60d9dcc0e21d
* Version Independent ID: 7fb320d3-fa69-23fa-113c-53e9d2e11ada
* Content: [Dimensions and measurements - Call Quality Dashboard (CQD) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/dimensions-and-measures-available-in-call-quality-dashboard)
* Content Source: [Teams/dimensions-and-measures-available-in-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/dimensions-and-measures-available-in-call-quality-dashboard.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @eblingus 
How are you?
The text is talking about the filter in the CQD portal

>The <sort order string> is used to control the sort order when presenting the data **and can be used for filtering**. For example, a filter on Duration (Minutes) < "065", would show streams with duration less than 2 minutes (The leading '0' is needed for the filter to work as expected).

an example of that filter

![image](https://user-images.githubusercontent.com/36666927/153951563-621256f0-1969-4199-b246-ee6a49ff7926.png)

For the utilization of PowerBI with CQD you can refer to https://docs.microsoft.com/en-us/microsoftteams/cqd-power-bi-query-templates

Does this answers your question?

Thank you

**Comment by eblingus** [comment]
It makes sense that it is talking about the filter in the CQD portal rather that Power BI, but even on the CQD portal, it is impossible filter on Duration using > 065.  If you found a way that it works, please post the URL and exactly which report allows that so I can test for myself.

**Comment by get-itips** [comment]
Hello @eblingus how are you? So I am able to reproduce, can you share more details about how are you using CQD with PowerBI? Are you using the provided templates? Please share all the details that might help me reproduce, thank you!

**Comment by eblingus** [comment]
Forget Power BI.  Just try to use a filter of Duration > 065 on any CQD report with that dimension.  Then you will understand.  Thanks.

**Comment by get-itips** [comment]
Hello @eblingus how are you? hope you are doing well!

Tried this, please kindly let me know if this is the same you are doing:

![image](https://user-images.githubusercontent.com/36666927/154545537-2e878618-3b06-43ae-80d3-ab7d50d71939.png)

![image](https://user-images.githubusercontent.com/36666927/154545647-52e0ec97-7a9d-4cf7-a0e5-0e9b4ae0a7bd.png)

![image](https://user-images.githubusercontent.com/36666927/154545748-abfcf033-ead3-4798-8032-236e8c921e60.png)

**Comment by get-itips** [comment]
Hello @eblingus Could you see my last comment? Thank you!

**Comment by eblingus** [comment]
No, I do not have those options when using CQD from the teams admin page.  The GUI I get is much more limited

**Comment by eblingus** [comment]
This is what I see
![image001](https://user-images.githubusercontent.com/29779255/155204137-074418c6-d976-4653-ae45-6dca62636bb1.png)

**Comment by get-itips** [comment]
I think this is the same report that you are showing me:

![image](https://user-images.githubusercontent.com/36666927/155208815-ef602185-fa02-4dbc-93fa-056efc61365c.png)

![image](https://user-images.githubusercontent.com/36666927/155208907-528d6054-c3dd-45a5-bfce-3d5a74ff4a45.png)


![image](https://user-images.githubusercontent.com/36666927/155208749-0e44c187-9591-46ea-9529-03247b80011c.png)

**Comment by eblingus** [comment]
Ok.  How do you enter > there?  Your previous screen shots show a query editor interface that I do not see.  The interface I posted only allows me to check boxes

**Comment by get-itips** [comment]
> Ok. How do you enter > there? Your previous screen shots show a query editor interface that I do not see. The interface I posted only allows me to check boxes

Exactly, that is the query editor for reports. Some reports have the edit enabled and also the custom reports you make, there, you can add filters and use the < > = symbols.

In the last images you sent, that allowed me to understand better where you were using filters at, I can not use < > = symbols.

**Comment by get-itips** [comment]
Hello @eblingus how are you? could you see my last message?

**Comment by eblingus** [comment]
Yes.  I understand now.  If you use the Editor to customize the online version of the CQD reports, then that answer makes sense.  But all the other times, it does not.

**Comment by get-itips** [comment]
@scanum
