### ISSUE TITLE
Many items here do not work as described - Guessing Admin center is broke.

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8508]
Sorry, but EMERGENCY LOCATION is all messed up in Teams Admin Center.  Addresses are messed up.  You can't delete locations as they are assigned to numbers that are not assigned to people.  If they are not assigned, you can't save.
When you create a location it puts the street name twice in the address.

Either these instructions need to be redone, of Teams admin center for Emergency locations need to be reviewed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd65a979-367c-001c-7462-ead0f0cfd989
* Version Independent ID: f430e334-25d4-b457-4350-7819953e199e
* Content: [Add, change, remove emergency locations - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/add-change-remove-emergency-location-organization)
* Content Source: [Teams/add-change-remove-emergency-location-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/add-change-remove-emergency-location-organization.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by lindspea** [comment]
@Karr thank you for reaching out and helping to improve Microsoft Docs. Not sure if the note is relevant to your area - "Note
In Belgium, France, Germany, Ireland, Netherlands, and Spain, it's important to understand that to successfully activate a phone number in Microsoft 365, the address set up in the emergency location, which is used to acquire the number, must match the phone number's area code." Also, did you try edit the address manually and then try save?
