### ISSUE TITLE
Why is this option Missing from Manage Teams App 

### ISSUE THREAD

**Issue by richardojel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8512]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/74375062/153917735-f8576b0c-0a88-480e-8fcf-179fc10fb267.png)
The Filter - Third Party Apps - Allow 3rd app purchase is missing from Teams Admin Center - The ask is why is it gone ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbcabee-fa96-2878-e983-3c966f84ee15
* Version Independent ID: 02fa4fd8-77e0-5cb2-a4af-576cbb68322f
* Content: [Manage your apps in the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-apps)
* Content Source: [Teams/manage-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-apps.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by get-itips** [comment]
Article was updated to reflect current options on https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/65274fcd2cdc4cf6b714fb46f74b8f5c556ac5e8

Closing
