### ISSUE TITLE
GCCH - Team member limit is now 25k

### ISSUE THREAD

**Issue by brily21** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8516]
[Enter feedback here]
The members per team in GCCH should be at 25k now making the statement below (note #6) incorrect?  https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=25k     

I think it should now only say DOD has a limit at 2,500 members.  

"*6 Teams in GCC can accommodate 25,000 members but teams in GCCH/DoD can only accommodate 2,500 members. Further note that teams/channel mentions are blocked in teams with over 10,000 members.**_"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#teams-and-channels)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by lindspea** [comment]
@scanum this can be closed thank you. PR done on another issue.
