### ISSUE TITLE
Typo webcab should be webcam

### ISSUE THREAD

**Issue by JohanVeldhuis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8519]
Typo in this line:

Use Teams to share content from the presenters **webcab** and screen.

This should be

Use Teams to share content from the presenters **webcam** and screen.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64cc650b-b313-cfab-9f45-190b94c128f4
* Version Independent ID: 9e93ac07-3f1b-9fd4-1907-17f0075bd837
* Content: [Teams devices for Shared Spaces feature comparison between Windows and Android - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/teams-devices-feature-comparison)
* Content Source: [Teams/rooms/teams-devices-feature-comparison.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/teams-devices-feature-comparison.md)
* Service: **msteams**
* GitHub Login: @amandafrechinjackson
* Microsoft Alias: **v-amandaf**

**Comment by Reeced40** [comment]
@JohanVeldhuis thank you for reaching out. I've just looked through the article but I can't find the typo. Perhaps it's been changed in the interim. Please can you confirm. Thanks.

**Comment by JohanVeldhuis** [comment]
Looks like it has been updated since visiting it. You can close this issue

**Comment by Reeced40** [comment]
This can be closed thanks @scanum
