### ISSUE TITLE
Clarification of Teams Guest settings

### ISSUE THREAD

**Issue by davidkench** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8520]
Can a sentance be added to clarify the behaviour when the setting "Let anonymous people start a meeting" is set to On?  Particularly highlighting any dependancies or interactions with the setting "Allow dial-in users to bypass the lobby".  ie. Can the former be turned On if the latter is Off?

Thanks,

David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4521de2b-1aae-93de-ee1a-222146194700
* Version Independent ID: b4f9087c-e1a3-8b47-917c-7c294d46fcca
* Content: [Manage meeting policies for participants and guests - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/meeting-policies-participants-and-guests?WT.mc_id=TeamsAdminCenterCSH#let-anonymous-people-start-a-meeting)
* Content Source: [Teams/meeting-policies-participants-and-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-participants-and-guests.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by davidkench** [comment]
Also, depending on how the page is edited based on this issue, the sentance under "Allow dial-in users to bypass the lobby" that reads "When this setting is turned on, dial-in users will automatically join the meeting when an organization user joins the meeting" should read "When this setting is turned on, dial-in users will automatically join the meeting if an organization user has already joined the meeting."

**Comment by Reeced40** [comment]
@davidkench thank you for reaching out and helping to improve Microsoft Docs. I see the article was updated a few days ago with more information. Please can you let me know if you need further assistance.

**Comment by davidkench** [comment]
Hi Reece,

Thanks for checking back.  I think this has been improved.  I wonder though, if the below highlighted text should still be added for clarification:
Allow dial-in users to bypass the lobby
This is a per-organizer policy. This setting controls whether people who dial in by phone join the meeting directly or wait in the lobby regardless of the Automatically admit people setting. By default, this setting is turned off. When this setting is turned off, dial-in users will wait in the lobby until an organization user joins the meeting with a Teams client and admits them. When this setting is turned on, dial-in users will automatically join the meeting when an organization user joins the meeting with a Teams client.
Thanks and kind regards,

David Kench
M365 Engineer | Intelligent Workspace

501 Ann Street, Fortitude Valley, QLD 4006, Australia
Email: ***@***.******@***.***> | Mobile: +61 435 160 796
www.datacom.com.au<http://www.datacom.com.au/>

***@***.***
