### ISSUE TITLE
Inconsistent list of countries for calling plan availablity

### ISSUE THREAD

**Issue by kannanramesh26** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8521]
In the spreadsheet with all countries and regions for AC and calling plan availability on this page, there are inconsistencies in the list of countries listed.
For MS calling plan availability, in the Tab "Calling Plans purchase" it list 31 countries.
However, in the "Calling Plans minutes" Tab, it only lists 27 countries (excluding Australia)
and in the "Make outbound calls" Tab, it only lists 17 countries.

Why are they inconsistent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b07cfcf-8f31-91ed-b1de-c7826a1ab91d
* Version Independent ID: dfbc4212-8f47-326a-f872-8186a915ae1e
* Content: [Country/region availability - Audio Conferencing, Calling Plans - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by dariomws** [comment]
Hi @kannanramesh26, thank you for your feedback.

I have opened the spreadsheet and I can count 33 countries with Calling Plans. Australia and Japan with third-party Calling Plans. I can see the missing information in the "Calling Plan minutes" sheet.

@MicrosoftHeidi, could you kindly help here to update the spreadsheet?

This is the list of countries missing in the "Calling Plan minutes" sheet:
Croatia
Estonia
Japan
Latvia
Lithuania
Slovenia
We can see the Calling Plans available for them directly in the article.

In addition, South Korea is listed in the "Calling Plan minutes" sheet, but not in the "Calling Plans purchase" sheet.

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
