### ISSUE TITLE
Is custom background in meeting supported for Guest users?

### ISSUE THREAD

**Issue by XixiHuang333** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8527]
Here is feedback from customers: Guest users cannot find 'add new' button at the top of the background settings menu of meeting. Could you please check and update this docs to include the statement if custom background in meeting is supported for Guest users?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [Guest experience in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/guest-experience)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @XixiHuang333, thank you for your feedback.

Could you kindly provide more detail? Are you talking about the "Apply background effects" option in the Teams client? I think guest users should be able to apply them.
