### ISSUE TITLE
API call not allowed for non-Compliance Recording call

### ISSUE THREAD

**Issue by Mishra-Saurabh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8528]
[Enter feedback here]

I CREATED POLICY BUT I AM NOT ABLE TO RECORD TEAM MEETING, I AM GEETING THIS ERROR:     

 Microsoft.Graph.ServiceException: 'Code: 8506 Message: API call not allowed for non-Compliance Recording call Inner error: AdditionalData: date: 2022-02-17T04:46:09 request-id: cc852547-ee8d-44cd-9163-00ff7ba85ae6 client-request-id: cc852547-ee8d-44cd-9163-00ff7ba85ae6 ClientRequestId: cc852547-ee8d-44cd-9163-00ff7ba85ae6 '
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 896e3ed7-aaf5-ad40-9a5f-1374d85c3e82
* Version Independent ID: 253d2a6b-9225-723a-cbc1-c296c3cfd36c
* Content: [Introduction to Teams Policy-based Recording for Calling & Meetings - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-recording-policy)
* Content Source: [Teams/teams-recording-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-recording-policy.md)
* Service: **msteams**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
