### ISSUE TITLE
Incorrect example in https://docs.microsoft.com/en-us/microsoftteams/direct-routing-enable-users

### ISSUE THREAD

**Issue by donlassini** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8530]
"As an admin, you use the Microsoft Teams admin center or PowerShell to set external access settings to control whether Teams users in your organization can communicate with Skype users. By default, this capability is turned on for new tenants. However, there's a prerequisite that the following DNS SRV record needs to be configured by the IT Admin if not already available for your domain, **for example _sipfederationtls.contoso.com.**"

The last part should be
.... "for example _sipfederationtls.**_tcp**.contoso.com"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3de87096-6253-ba71-f27a-0b161a36f0e2
* Version Independent ID: 8b61b40d-496c-6069-8a60-38a6282e072a
* Content: [Teams and Skype interoperability - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-skype-interop)
* Content Source: [Teams/teams-skype-interop.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-skype-interop.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for the feedback!
