### ISSUE TITLE
The information about Teams Live Events in China is not up-to-date

### ISSUE THREAD

**Issue by Antti-Kiviniemi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8535]
The page needs to be updated with the information that streaming endpoint in China is backed by Azure CDN.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-live-events/plan-for-teams-live-events#regional-availability)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @Antti-Kiviniemi how are you?
I am having some trouble finding the roadmap/announcement about that, can you please share it here? thank you!

**Comment by get-itips** [comment]
Hello @Antti-Kiviniemi could you see my last comment?
Thank you

**Comment by get-itips** [comment]
Closing, for now, @scanum this can be reopened if the author returns with the requested information. Thanks!
