### ISSUE TITLE
Teams Phone standalone license not a license available in price list, change to product names

### ISSUE THREAD

**Issue by carloxsf** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8538]
When you said "Teams Phone standalone license" is a litle confusing because looks like a license name but the real name is for example the available in the CSP price list:
![image](https://user-images.githubusercontent.com/30153991/154761548-24804349-fa4d-47b3-a626-f865e59aa251.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abae7324-861d-7ca7-7239-a5df8fd927d5
* Version Independent ID: 8a30bd2f-9bc3-a0a8-8b31-d53836ead4d0
* Content: [Microsoft Teams add-on licenses - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=small-business)
* Content Source: [Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @carloxsf how are you?
I think that refers to the Teams Phone Standard in the list you provided, (as it refers to Teams Phone without a CP, as the description states), but I understand that you feel is not clear enough in the article?
Thanks for clarifying,

**Comment by get-itips** [comment]
@scanum
