### ISSUE TITLE
Fourth reason for signing out of teams

### ISSUE THREAD

**Issue by wUEZRs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8544]
It may be worth mentioning as we see this as the main reason for signing out of Teams:
When signing out, the contact cache seems to update. Users who have changed names will have the "old" name for week(s) but if one signs out they get the updated name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4d56b6e-a220-710c-f051-6e78bf0883fe
* Version Independent ID: d1aa0964-725e-0b99-00c0-7ddcfad46920
* Content: [Sign out of Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/sign-out-of-teams)
* Content Source: [Teams/sign-out-of-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sign-out-of-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @wUEZRs, thank you for your feedback.

While I understand your point and it's valid, I think the purpose of the article is other and this is not the correct place to add that information.
