### ISSUE TITLE
https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-lifecycle-support

### ISSUE THREAD

**Issue by khansaif786** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8549]
[Enter feedback here]
Hello Team,

As per this document Microsoft Teams Rooms support Windows OS is 20H2 where as when downloading teams room imaging is coming with latest images based on the windows device using to download the Image. How can we get with Teams room 20H2 image  rather then latest Image.

Version | Availability date | Microsoft Teams Rooms support status | Microsoft Teams Rooms Minimum application version | Recommended OS build
21H1 | 2021-05-18 | Not Supported | — | —-- | -- | -- | -- | --
20H2 | 2020-10-20 | Supported,Recommended | 4.10.10.0 | 19042.631

https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-lifecycle-support

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Build a Microsoft Teams Rooms image - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/console#Prep_Media)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @khansaif786, thank you for your feedback.

I understand that you are talking about the following process:
https://docs.microsoft.com/MicrosoftTeams/rooms/console

Please have in mind that it's intended only for mass deployment in large companies. And you have to download the Windows 10 image from the Volume Licensing Service Center.
