### ISSUE TITLE
Org-wide Teams not visible for Global Admins that are AD Connect synced

### ISSUE THREAD

**Issue by pgdrews** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8550]
I seen some other comments in the wild on the issue when some GA's don't see the option to create Org-wide teams when their GA account is an AD Synced account.  My account, which is AD synced and GA, did not allow me see the org-wide option as well.   

Currently this article states the following:

"If you don't see the Org-wide option when creating a team and you're a global admin, you might have reached the five organization-wide teams limit, or your organization might have more than the current size limit of 10,000 members. We're looking to increase this limit in the future. Org-wide teams aren't yet available for Teams for Education."

This does not apply to my org, as we have no org-wide teams in existence. 

To validate the issue, I found that if I used a different Global Admin account that was created in O365 (either with @company.com  or @x.onmicrosoft.com) the option to create a Org-wide team did appear. 

I suggest that some information be appended to this doc that gives that as another reason a GA may not see the org-wide option when they are using an account that is synced from on-premise Active Directory. 

Thanks!

Patrick 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an organization-wide team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @pgdrews, thank you for your feedback.

I have tried this and I were not able to reproduce it.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.
