### ISSUE TITLE
Failover mechanism for SIP Signaling - table incomplete? 

### ISSUE THREAD

**Issue by tylerstosic** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8554]
Hi Team, 

Are you please able to provide some additional information regarding the "Failover mechanism for SIP Signaling" section.
This section only lists three data centers; EMEA, NOAM and ASIA.

However, if we review the "Media traffic: Media processors geography", it is stated that "Media processors are placed in the same datacenters as **SIP proxies**", the lists 7 different locations with SIP proxies/media processors. 

I would then expect in the "Failover mechanism for SIP Signaling", we would see the table include the relationships between primary, secondary and tertiary for 7 locations that include SIP proxies? 

Let me know if more information/clarification is required.

Cheers,
Tyler 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e26faf8c-529e-b317-5934-cd41cfe8fa24
* Version Independent ID: 3ddd5d0a-6dbb-4940-1814-8346e293701b
* Content: [Plan Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-plan#sip-signaling-fqdns)
* Content Source: [Teams/direct-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by lindspea** [comment]
@tylerstosic thank you for reaching out. I see the article has been updated a few days ago. Please can you have a look and let me know if anything needs to be amended/added. Thanks again.

**Comment by tylerstosic** [comment]
Hi @lindspea 
Thanks for getting back to me, I have have been misinterpreting the information in the document to begin with and I don't believe the level of details I'm looking for would be possible to get clarity on. I'll close this issue out. 

Cheers,
Tyler
