### ISSUE TITLE
Remove Teams Exploratory from subscriptions

### ISSUE THREAD

**Issue by JuanZQ** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8563]
[Please explain how an admin can remove the Teams Exploratory Subscription from their tenant. Not only the license for every user but the whole subscription.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-exploratory)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @JuanZQ 
I think this other article is what you are looking for https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/cancel-your-subscription?view=o365-worldwide

**Comment by get-itips** [comment]
@scanum
