### ISSUE TITLE
Update license names

### ISSUE THREAD

**Issue by mprentice22153** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8564]
I believe this page should be reviewed for updated licensing product names.  For example "Phone System" is now "Microsoft Teams Phone Standard". There might be more. A single listing of 

Maybe in step 1 or 2, clearly identify what licenses are needed, and why each is needed. Help make it clear what is needed and why.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cad07c2d-dc0c-faa4-9fde-0377c413dc0f
* Version Independent ID: e5a76596-eb09-88eb-46ca-4353061bd631
* Content: [Set up Phone System in your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/setting-up-your-phone-system#feedback)
* Content Source: [Teams/setting-up-your-phone-system.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/setting-up-your-phone-system.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Thanks for the feedback.  We're in the process of updating this entire article--to include information about all PSTN connectivity options, etc.  At that time, we'll also update the licensing info or point to the add-on licenses article.  Stay tuned...  This is in the works... so closing this issue.
