### ISSUE TITLE
wrong commandlet

### ISSUE THREAD

**Issue by reisi1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#857]
"NewRgsTimeRange" should be "New-CSRgsTimeRange". Last example 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c2cb3f4-ea7e-a592-a28c-aada77bf9c4f
* Version Independent ID: a464fc09-36f4-c382-f5ee-228e8aac5268
* Content: [(Optional) Define Response Group business hours in Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-enterprise-voice/optional-define-response-group-business-hours?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json)
* Content Source: [Skype/SfbServer/deploy/deploy-enterprise-voice/optional-define-response-group-business-hours.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-enterprise-voice/optional-define-response-group-business-hours.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment]
@reisi1 Thank you for this feedback

I have submitted a pull request with the cmdlet changes you suggested. I am waiting approval then we can merge the update to the live document.  Thank you for helping make the docs better.

**Comment by kenwith** [comment]
Confirmed this is fixed in the PR. @AndreaBarr - just a note on Pull Requests that I learned.. you can paste the URL of this Issue in the comments of the Pull Request and it will automatically add a reference link. Just wanted to pass that along.

Thanks for fixes on these!
