### ISSUE TITLE
Teams 1.5.00.2164 machine wide installer

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8571]
Can you clarify if there are new Command Line switches to enable the generation of the Teams Desktop Shortcut with version 1.5.00.2164?  

This feature appears to no longer be the default when installing the Machine Wide 1.5.00.2164 installer vs 1.4.0.26376 Users are now accustomed to waiting for it to appear after login on our Classroom machines, which it no longer is. 

It does however still create a start menu item in C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
