### ISSUE TITLE
Live Events can be attended by users from China now

### ISSUE THREAD

**Issue by StainlessSteele** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8573]
We have enabled Azure CDN for users from China to enable them to have higher quality experiences. we should update this part of our document. this doesn't need to be used anymore. 
<img width="662" alt="image" src="https://user-images.githubusercontent.com/55393986/156185470-eadfe8f7-eb4f-42d9-9ad9-6f0031369843.png">

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
