### ISSUE TITLE
Call out specific IP addresses and/or URLs necessary for on-premises mailboxes

### ISSUE THREAD

**Issue by PaulRNewell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8578]
This is a well-written and structured article which I have referenced to customers many times in the past. I have a suggestion on making the [Requirements to create and view meetings for mailboxes hosted on-premises](https://docs.microsoft.com/en-us/MicrosoftTeams/exchange-teams-interact#requirements-to-create-and-view-meetings-for-mailboxes-hosted-on-premises) section more helpful - include a reference to where the connections will be originating. 
The article states that Autodiscover and EWS must be available, but some organizations still like to limit which IP addresses can connect to the Exchange servers, so including that information would be very helpful. 
This information is likely already published in the [Skype for Business Online and Microsoft Teams](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#skype-for-business-online-and-microsoft-teams) section of the [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide) article, so I think the only thing that would need to be noted is to refer back to the article and specify which ID (I suspect 12?) needs to be made available. 

Thanks for your time and consideration!

Paulnew

**Comment by dariomws** [comment]
Hi @PaulRNewell, thank you for your feedback.

If you want, you can check the Pull Request and let me know if you are happy with the proposed update.

Thank you again!

**Comment by PaulRNewell** [comment]
Hi Dario,
Thanks! 
I'm specifically looking for which section(s) from the _Office 365 URLs and IP address ranges_ I need to allow to communicate with my Exchange Servers. For example, the [Other endpoints not included in the Office 365 IP Address and URL Web service](https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide) article indicates services & tools which may need to communicate with your on-prem Exchange Server organization. I'm looking for something similar in this Teams article (or maybe add it to that article instead). 
If I am looking at this article for the first time, I don't know which section (since there are 160) should be allowed to access my on-prem Exchange Servers. Is it a section under _Exchange Online_ or one under _Skype for Business Online and Microsoft Teams_? 
With some testing, it seems it is section 12 (under _Skype for Business Online and Microsoft Teams_), but I'm hoping someone can get clarification from the PG and add it to this article. 

If you'd like to discuss further next week let me know and I can create a Teams meeting for us. I'm paulnew at microsoft.com. 

Thanks again, and have a nice weekend!
Paulnew
