### ISSUE TITLE
Make Teams more resilient to packet delays

### ISSUE THREAD

**Issue by sicotteh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8580]
Teams screen sharing does not use a lot of bandwith (about 1Mbps), the issue is dropped packet. Teams is not very tolerant of packet delays. I have a DSL line in a rural area, 5% of my packets get delayed by anywhere from 90 to 300ms (I am guessing that due to noise the packet is lost and resend by the DSL modem hardware) and normally they take 37ms (because they have to go through a VPN). For some reason that I cannot understand the Teams packet loss rate is a lot higher (30%). The screen usually freezes and/or updates only every 2 minutes.

Nevertheless, there are two 4  fixes that the programming team can do (the first two are really easy)
1.  Implement a longer and faster jitter buffer (300 ms) for reconstruction of packet order.
2. Have the option to send every packet twice (as zoom does automaticalkt) and drop the packets that get there twice. THe desktop sharing usually uses 1 Mbps .. so going from 1 to two Mbps is OK. Sending double packets will take 5% packet being delayed to 0.025.
3. Use a video codec algorithm that can handle the occasional missing packet.
4. Use a separate stream of control for rendering mouse movements  independent of the video (will help the experience a lot) .. and the mouse movements are more crucial .. so send those 2-3 times.[you can put my name on that patent.. thank you very much]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9745711a-f2a6-c551-db56-f4ec81a119b6
* Version Independent ID: b1711f90-3fe2-0ccd-8abb-646fd3079aa9
* Content: [Microsoft Teams low-bandwidth guidance for EDU - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/edu-remote-low-bandwidth)
* Content Source: [Teams/edu-remote-low-bandwidth.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/edu-remote-low-bandwidth.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
