### ISSUE TITLE
Missing information regarding custom meeting backgrounds and required license or not

### ISSUE THREAD

**Issue by sgrienen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8581]
Hi,
I'm lacking a bit of information about how the custom meeting background apply, if the Advanced communications license is a MUST or not, we recently noticed on Windows 10 PC, where the user didn't have that license that background are made available, we're also considering that option for managing iPads, but we do not really want to pay extra license for that, still the documentation is quite unclear regarding that topic.
Thanks in advance !
Stéphane

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Teams: Manage meeting policies - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/meeting-policies-in-teams?WT.mc_id=TeamsAdminCenterCSH#customimages)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by get-itips** [comment]
Helllo @sgrienen Stéphane,

Please confirm if you refer to **Org-Wide** Backgrounds https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=Advanced%2CCommunications

**Comment by sgrienen** [comment]
Hi,

Yes I'm talking about Org-Wide backgrounds. Ok, thanks for that hint.

Cheers,
Stéphane

**Comment by get-itips** [comment]
@scanum
