### ISSUE TITLE
Meeting Link Expiration Inefective

### ISSUE THREAD

**Issue by mclaughlin716** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8583]
There needs to be a way for our admin to expire specific meetings by link or by the Conference ID #. We have students, that are minors, accessing and sharing old meeting join links. In some cases, the organizer sets the meeting options to not allow anyone to bypass the lobby, but these options revert to allowing all to bypass on the following day. I suspect this has something to do with setting up the meeting as reoccurring. (I'm sorry if this is not the correct place for this, but I am struggling with how to find a solution to this problem.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee6d4c1c-6f16-b1a4-c4a9-be4e6d1f95b7
* Version Independent ID: 50ad835d-ed7f-18c6-34ba-322c1574f9c2
* Content: [Meeting policies and meeting expiration in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/meeting-expiration)
* Content Source: [Teams/meeting-expiration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-expiration.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by get-itips** [comment]
Hello @mclaughlin716 
Thanks for your feedback, here, we are limited to changes/improvements against the documentation, for your inquiry, the [Feedback Portal](https://feedbackportal.microsoft.com/) is a resource that can be used to submit your idea and it can reach the product group, for example, I found a very similar suggestion [here](https://feedbackportal.microsoft.com/feedback/idea/ff7ca919-584c-ec11-a819-0022484f092b)

Hope this helps you,

**Comment by get-itips** [comment]
@scanum
