### ISSUE TITLE
Private Channels and AzureAD SAML group claims

### ISSUE THREAD

**Issue by carlo-quinonez** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8588]
Is it possible to include membership in a Teams Private Channel in AzureAD  SAML claims (group or otherwise)? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/private-channels)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @carlo-quinonez Carlo,

I think that is not currently possible, you can suggest feedback to reach the product team here 
https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472

**Comment by get-itips** [comment]
@scanum

**Comment by get-itips** [comment]
> If anyone else lands here, I opened a [feedback](https://feedbackportal.microsoft.com/feedback/idea/ecc44e26-0a9f-ec11-a81c-00224850e48f) for this issue. Please vote for it!

Voted
