### ISSUE TITLE
Teams Rooms on Android version information

### ISSUE THREAD

**Issue by martinboam** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8589]
[Could we include Teams Rooms on Android release notes and versions on this page as well ? 

We seem to have this on another site so it feel disjointed for Teams Rooms on Android.
https://support.microsoft.com/en-gb/office/what-s-new-in-microsoft-teams-devices-eabf4d81-acdd-4b23-afa1-9ee47bb7c5e2#ID0EBD=Teams_Rooms_on_Android. 

Also Teams Rooms on Windows is listed on this pages as well but content is out of date ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1365f9b8-001c-daa7-592e-d88b9bb3a10e
* Version Independent ID: ffba1b4d-1f19-4dac-0b55-053d98fe26b7
* Content: [Release notes for Microsoft Teams Rooms - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-release-note)
* Content Source: [Teams/rooms/rooms-release-note.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-release-note.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @martinboam Martin, I am looking into this

**Comment by tiburd** [comment]
Thank you for bringing this to our attention. We have notified the documentation team of your request.
