### ISSUE TITLE
QoS Setting for Client Update Request

### ISSUE THREAD

**Issue by greganth1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#859]
Recommend updating this document to reflect QoS port configurations for both Hybrid/Online/Teams since the SfB Server documentation points back to this Lync Server 2013 documentation for QoS.
Port range - Modality.
50000-50019 Audio
50020-50039 Video
50040-50059 App/Desktop Sharing

Also the existing cmdlet examples when copied and run have a space between the hypen - and the parameter which need to be removed (this - ClientFileTransferPort 42020 to this -ClientFileTransferPort 42020) for the cmdlet to run properly with copy/paste.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e11441ac-62cb-9e72-9069-f7e61c8c02a4
* Version Independent ID: 70619c9b-aae7-277c-3d3a-35d82379f19b
* Content: [Lync Server 2013: Configuring Quality of Service policies for clients running on Windows 7 or Windows 8](https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-configuring-quality-of-service-policies-for-clients-running-on-windows-7-or-windows-8)
* Content Source: [Lync/LyncServer/lync-server-2013-configuring-quality-of-service-policies-for-clients-running-on-windows-7-or-windows-8.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Lync/LyncServer/lync-server-2013-configuring-quality-of-service-policies-for-clients-running-on-windows-7-or-windows-8.md)
* GitHub Login: @dstrome2

**Comment by AndreaBarr** [comment]
@greganth1 Thank you for this feedback

I agree this should be updated to reflect the QOS port configurations. I am going to get this over to the Teams/ Skype for Business team so we can get that added and the cmdlet updated as well. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by CrystalThomasMS** [comment]
Thanks for your feedback and your patience. This content has been updated and published in the 2015 doc set: https://docs.microsoft.com/en-us/SkypeForBusiness/manage/network-management/qos/configuring-port-ranges-for-your-skype-clients#configure-quality-of-service-policies-for-clients-running-on-windows-10
