### ISSUE TITLE
How to remove/change sign-in account?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8591]
Hi,
Would you be so kind and add instructions to also, how to remove the sign-in account from the device's details on Teams Admin Center? Even I remove the device and provision it again, the same account is assigned automatically.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ff0b460-9f13-fefe-37b1-b40d5062fb86
* Version Independent ID: 6ff0b460-9f13-fefe-37b1-b40d5062fb86
* Content: [Remote sign in and sign out for Teams Android devices - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/remote-sign-in-and-sign-out)
* Content Source: [Teams/devices/remote-sign-in-and-sign-out.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/remote-sign-in-and-sign-out.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by get-itips** [comment]
Hello @Petri-X 
To understand better and try to reproduce, are you performing a Remote Sign-Out before removing the device? is the device being factory reset before re-provision?
Thanks

**Comment by Petri-X** [comment]
Hi @get-itips 
When looking for this: [Teams phone - Remote sign out](https://docs.microsoft.com/en-us/microsoftteams/devices/remote-sign-in-and-sign-out#remote-sign-out)
It does not give too much information where I should be. But I tested by select from User Phones view:
![image](https://user-images.githubusercontent.com/43988151/158336538-1770e41b-9271-415c-b0bb-b3dfb9693b2e.png)

But I tried also when I have open the phone: 
![image](https://user-images.githubusercontent.com/43988151/158336593-bfdc7c0d-3231-4b67-9c44-3b4105ec2d5d.png)

So do you know if there is some other place for sign-out as well?

**Comment by get-itips** [comment]
Hello @Petri-X sorry for the delay

I understand, will check that. Have you seen my other question?

>is the device being factory reset before re-provision?

**Comment by Petri-X** [comment]
Hi,
I'm not sure what role the factory reset plays on this? Let say your phone went broken, as the user account is on phone object in the Teams Admin Center.

. . .but in these days I have learnt something more :)
Intune (Endpoint Manager) have a role on this game as well. The phone device is marked on there, and in there I can actually see the link between phone device and my account. Sounds like there is a bug in TAC code, when you remove the phone devices from TAC, that does not remove phone device from Endpoint Manager.

**Comment by get-itips** [comment]
> when you remove the phone devices from TAC, that does not remove phone device from Endpoint Manager.

Hello @Petri-X I had information that removing the device from TAC does not unenroll the device from Intune and that is currently by design

**Comment by Petri-X** [comment]
I wish I could use "...by design..." statement at home as well, when I have forgot to clean, or made food :D
I believe more realistic answer would be: "someone had a bit rush, and this was forgot to do".

But perhaps this will be fixed in future.

Big thanks @get-itips to your effort again _o/

**Comment by Petri-X** [comment]
@get-itips 
Just an extra note, normally CAP license does not includes the intune license. But because it accidentally sign-in with my own account, which had intune license, and because of that it appears to endpoint manager.

And yes, the factory reset was required on the device. My own account was still sign-in to that device, which I found from factory reset view. Need to say, it was quite well hided =)
