### ISSUE TITLE
Restrictions need to be updated

### ISSUE THREAD

**Issue by stemy-msft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8592]
"Music on Hold is only available in commercial cloud."
Music on hold is also available in GCC but is not currently available in GCCH or DOD forests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 416f3cdb-ca75-8224-bc04-985e5f7ea9dd
* Version Independent ID: 6e8c6f33-8043-e367-b44b-74b5f5ee96f2
* Content: [Music on Hold - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/music-on-hold?source=docs)
* Content Source: [Teams/music-on-hold.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/music-on-hold.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Thanks for your feedback @stemy-msft
