### ISSUE TITLE
"Owners can delete sent messages" effect is ambiguous

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8593]
"**Owners can delete sent messages** Use this setting to let owners delete messages that users sent in chat."
https://review.docs.microsoft.com/en-us/microsoftteams/messaging-policies-in-teams#messaging-policy-settings

I'm 95% sure this setting allows owners of a Team to delete channel posts made by other people. However, it says 'chat', which makes people think more about meetings/group chat than things tied to a team. If it works as I think it does, then could we update the description to say:

"**Owners can delete sent messages** Use this setting to let team owners delete channel posts made by others."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34f3188-0af5-f972-9d28-959f5f7866a2
* Version Independent ID: fab26e11-a729-92a4-3ea6-8668dca55dd0
* Content: [Manage messaging policies in Teams - Microsoft Teams](https://review.docs.microsoft.com/en-us/microsoftteams/messaging-policies-in-teams#messaging-policy-settings)
* Content Source: [Teams/messaging-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/messaging-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Thanks for your feedback @npherson

**Comment by npherson** [comment]
The changes don't address the issue and make it less clear/correct. @tiburd  @get-itips

**Comment by npherson** [comment]
My understanding is that this only applies to a channel. There are no 'messages' in channels, but there are in meetings and chat. If this truly only affects channels, then use this:

Use this setting to let **team** owners delete **channel posts** made by others.

**Comment by get-itips** [comment]
@npherson Nash,

how are you? hope you are doing great

Channels do have messages, some examples where that verbiage is used

https://support.microsoft.com/en-us/office/send-a-message-to-a-channel-in-teams-5c8131ce-eaad-4798-bc73-e33f4652a9c4
https://docs.microsoft.com/en-us/graph/api/channel-list-messages
https://support.microsoft.com/en-us/office/first-things-to-know-about-channels-8e7b8f6f-0f0d-41c2-9883-3dc0bd5d4cda

And on my tests, the setting only applied to Channels, not to meetings or chat as you said.

Let me know if I understood you correctly and have a great day
