### ISSUE TITLE
How can I contribute to correct wrong Japanese translation?

### ISSUE THREAD

**Issue by yutaro113** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8596]
Hi team, 
I found multiple incorrect Japanese translation in this page but how can I feedback it?
In the English version page, I could find feedback button but it doesn't exist in the Japanese (local) version doc.

ex)
Title of this page is translated as "管理センターでアプリMicrosoft Teamsする" but it should be "Microsoft Teams管理センターでアプリを管理する".

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbcabee-fa96-2878-e983-3c966f84ee15
* Version Independent ID: 02fa4fd8-77e0-5cb2-a4af-576cbb68322f
* Content: [Manage your apps in the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-apps)
* Content Source: [Teams/manage-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-apps.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by yutaro113** [comment]
@scanum , 
thanks for the handling! any updates on this?

**Comment by TinaMcN** [comment]
@yutaro113 thanks for reporting the issue.  Can I ask you to please log a bug from this site: https://globalservices.powerappsportals.com/Global/ - see the "Report a translation bug" link.
I see that the article is machine translated and we can get it human translated.

**Comment by cdowling1971** [comment]
@yutaro113 I already went ahead and logged the bug below (31/04) from the Hub website https://globalservices.powerappsportals.com/Global/ Tina shared with you. 

You can use the "Follow" feature in ADO to see how this request is progressing. Please log future translation feedback issues on the Hub using the below bug as a sample for how to do this, thanks in advance.

Bug: https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/172420

FYI @TinaMcN

**Comment by tiburd** [comment]
@scanum
