### ISSUE TITLE
Using App Studio is still recommended rather than using Developer Portal?

### ISSUE THREAD

**Issue by yutaro113** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8597]
Hi Team,

Just to clarify...
In below section, using "App Studio" seems to be recommended to create application package.
But as far as I know now Developer Portal is GA so should Microsoft recommend using Developer Portal? (or recommend both?)

https://docs.microsoft.com/en-us/MicrosoftTeams/manage-apps?toc=%2Fmicrosoftteams%2Fplatform%2Ftoc.json&bc=%2Fmicrosoftteams%2Fplatform%2Fbreadcrumb%2Ftoc.json#upload-an-app-package

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbcabee-fa96-2878-e983-3c966f84ee15
* Version Independent ID: 02fa4fd8-77e0-5cb2-a4af-576cbb68322f
* Content: [Manage your apps in the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/manage-apps?toc=%2Fmicrosoftteams%2Fplatform%2Ftoc.json&bc=%2Fmicrosoftteams%2Fplatform%2Fbreadcrumb%2Ftoc.json)
* Content Source: [Teams/manage-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-apps.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
