### ISSUE TITLE
Download Key missing

### ISSUE THREAD

**Issue by replicatress** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8598]
I would like to ask if the process for enrollment has changed? The Self-Enrollment keys is missing in settings despite having the correct roles.  https://docs.microsoft.com/en-us/microsoftteams/rooms/monitor-software-installation-guide#adding-proxy-settings-optional

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
