### ISSUE TITLE
.........and why does this work then?

### ISSUE THREAD

**Issue by indomtrading** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#86]
Nothing infuriates me more than following a set of instructions that don't work. I've waited the 24 hours for this stupid retarded piece of **** technology to make the relevant changes and I STILL see the "company policy" message. If you're going o take the time to write a help article, make sure you know how the ******* product works BEFORE you start pressing keys. Complete waste of time.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee122b1c-c1c6-bb32-38db-a7f7c52c1f28
* Version Independent ID: 1f335848-baeb-9396-f753-8f72017447ce
* Content: [Allow users to contact external Skype for Business users](https://docs.microsoft.com/en-gb/SkypeForBusiness/set-up-skype-for-business-online/allow-users-to-contact-external-skype-for-business-users?ui=en-US&rs=en-GB&ad=GB)
* Content Source: [Skype/SfbOnline/set-up-skype-for-business-online/allow-users-to-contact-external-skype-for-business-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-skype-for-business-online/allow-users-to-contact-external-skype-for-business-users.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by tonysmit** [comment]
@indomtrading. I added a video to this. The missing part of the article was that the admin in the other domain/organization must also do the same steps. I noted that as well. Thank you for the feedback.
