### ISSUE TITLE
Other room layout images were really important

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8603]
A recent update stripped out most of the room layout images which were VERY important in explaining our vision for meeting rooms. The only one left has everyone facing a wall.

Is there any way to get the other room layouts/images brought back to the article?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e16a13-c655-a78d-cdf5-8395bcfe54d6
* Version Independent ID: f06b064f-a9f2-8ed7-48f7-8d4e21934e6a
* Content: [Meeting room guidance for Teams - Microsoft Teams](https://review.docs.microsoft.com/en-us/microsoftteams/teams-meeting-room-guidance?tabs=uses)
* Content Source: [Teams/teams-meeting-room-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-meeting-room-guidance.md)
* Service: **msteams**
* GitHub Login: @amandafrechinjackson
* Microsoft Alias: **v-amandaf**

**Comment by get-itips** [comment]
Hello @npherson Nash, I am looking into this

**Comment by get-itips** [comment]
Hello @npherson Nash,
I could get information that a complete overhaul of the topic is in the works and that the images will get back as part of it.
Hope this information helps you understand why they aren't currently in the article.
Thanks!

**Comment by get-itips** [comment]
@scanum

**Comment by npherson** [comment]
Is there any ETA on the complete overhaul? This disrupts H2 strategic emphasis on teams rooms.
