### ISSUE TITLE
What group types are supported? 

### ISSUE THREAD

**Issue by marina-hayrapetyan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8605]
[Enter feedback here]
The documentation needs to clearly state what types of groups are supported. Specifically, can modern office groups be assigned? dynamic groups? DLs? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888fe05b-1160-452f-90ba-deb19adb740f
* Version Independent ID: 4091c5e4-7a90-7fe4-2741-16bbb1f297c1
* Content: [Assign policies to users and groups - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/assign-policies-users-and-groups)
* Content Source: [Teams/assign-policies-users-and-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-policies-users-and-groups.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by lindspea** [comment]
@marina-hayrapetyan thank you for reaching out and helping to improve Microsoft Docs. Please let me know if this link helps at all. - https://docs.microsoft.com/microsoftteams/batch-group-policy-assignment-edu

**Comment by marina-hayrapetyan** [comment]
Not really - this article is about assigning policies to security groups, so I can deduce that security groups are supported, but it doesn't answer the core question that my feedback was about - what types of groups are supported?

**Comment by lindspea** [comment]
@marina-hayrapetyan I found another article that might help - https://docs.microsoft.com/powershell/module/teams/new-csgrouppolicyassignment?view=teams-ps

**Comment by marina-hayrapetyan** [comment]
Thanks, my feedback was about updating the core documentation and specifying the types of groups that are supported. This article talks about using powershell commands with security groups and DL, yet again it doesn't answer the question what all types of groups that are supported.

**Comment by lindspea** [comment]
@marina-hayrapetyan I've done some more research and it seems that security groups and organizational units are supported for now.

**Comment by marina-hayrapetyan** [comment]
Thanks! Can the docs be updated to state that?
