### ISSUE TITLE
Steps 4 and 5 under the Setup section need to be swapped

### ISSUE THREAD

**Issue by dolesh84** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8607]
Hi, under Setup, steps 4 and 5 need to be swapped.

![image](https://user-images.githubusercontent.com/33043978/157296427-cafb1fd9-8071-4438-8611-9de156a11813.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 067e8376-df94-9a44-5263-cd1fc84879bf
* Version Independent ID: 924240c8-52c5-42db-36b8-28751f838784
* Content: [Install Power BI Connector to use CQD query templates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cqd-power-bi-connector)
* Content Source: [Teams/CQD-Power-BI-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-Power-BI-connector.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by lindspea** [comment]
@dolesh84 thank you for reaching out and helping to improve Microsoft Docs. Please have a look at this link and let me know if you still think the two steps must be swapped around. https://docs.microsoft.com/power-bi/connect-data/desktop-quickstart-connect-to-data
