### ISSUE TITLE
Step 9

### ISSUE THREAD

**Issue by Fat-Elllllls** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8614]
[Enter feedback here]
Maybe I'm misunderstanding the purpose of step 9. Should the second IF should include $user.LineUri.Replace("tel:+","") instead of just $user.LineUri to correctly match the lineuri in the file with the new output of Get-CSOnlineUser

if ($u.LineURI -ne $user.LineUri.Replace("tel:+","") -or $u.EnterpriseVoiceEnabled -ne $true)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5566de7d-1d1e-ba92-743b-dc772b49752a
* Version Independent ID: c15342ff-eb3a-5f14-4bba-217c31aa1299
* Content: [Decide how to manage attributes after decommissioning - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/cloud-consolidation-managing-attributes)
* Content Source: [Skype/SfbHybrid/hybrid/cloud-consolidation-managing-attributes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/cloud-consolidation-managing-attributes.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
