### ISSUE TITLE
Explore more training and tutorials link broken

### ISSUE THREAD

**Issue by ryanhelmer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8616]
I'm getting a 404 error when clicking the "more training and tutorials" link in step 4.

Thanks!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8177d07-3c8a-00df-8d8e-36dd2e1b1f1b
* Version Independent ID: 7f07f6f0-819a-a78d-33f3-9dba1e8e1a88
* Content: [Understand calling in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/tutorial-calling-in-teams?tutorial-step=8)
* Content Source: [Teams/Tutorial-Calling-in-Teams.yml](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Tutorial-Calling-in-Teams.yml)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **tbinder**

**Comment by lindspea** [comment]
@ryanhelmer thank you for pointing this out and helping to improve Microsoft Docs. Would it be helpful to replace the current link with this one - https://docs.microsoft.com/microsoftteams/itadmin-readiness#technical-training ?
