### ISSUE TITLE
RegistrarPool no longer in Get-CsOnlineUser output

### ISSUE THREAD

**Issue by didadadida93** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8617]
Based on the documentation, we could check if user homed online by looking at RegistrarPool parameter, which needs to have a value in the infra.lync.com domain. But `Get-CsOnlineUser` cmdlet no longer have RegistrarPool in it's output.
So is there another way we could use to check if user is homed online?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb2a9717-6565-8443-8833-f7fdce562781
* Version Independent ID: db88c4d6-5864-a481-86cf-465feb452d75
* Content: [Enable users for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-enable-users)
* Content Source: [Teams/direct-routing-enable-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-enable-users.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by vlethiec** [comment]
Hi @didadadida93, 

I think you should be able to use the attribute named "HostingProvider". This is the one I use. 

![image](https://user-images.githubusercontent.com/52075388/157873725-4bd46fa0-8d80-4cf0-8814-9176173ac878.png)

**Comment by dariomws** [comment]
Hi @didadadida93, thank you for your feedback.

You can look at the parameter that @vlethiec suggests.

@vlethiec thank you for your comment!

**Comment by didadadida93** [comment]
awesome, thanks guys @dariomws @vlethiec
