### ISSUE TITLE
A little missing info

### ISSUE THREAD

**Issue by RNR1995** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8626]
run Set-ExecutionPolicy Unrestricted, then Import-Module MicrosoftTeams, before this, Connect-MicrosoftTeams
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd283f6e-3865-ed70-d663-cc461ee8ba57
* Version Independent ID: 2450d311-fc04-d8b6-b4a2-b1890ec6fc3e
* Content: [Install Microsoft Teams PowerShell - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install)
* Content Source: [Teams/teams-powershell-install.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-install.md)
* Service: **msteams**
* GitHub Login: @brandber
* Microsoft Alias: **brandber**

**Comment by get-itips** [comment]
Hello @RNR1995 
What error did you receive if you did not change the restriction policy? I could successfully connect and use the module using RemoteSigned.
Also, the Connect-MicrosoftTeams will implicitly load the module.
Thanks

**Comment by get-itips** [comment]
Hello @RNR1995 could you see my last comment?

**Comment by RNR1995** [comment]
Sorry on the road
Trying to run Connect-MicrosoftTeams resulted in an error
Trying to Import-Module MicrosoftTeams resulted in an error
Once I unrestricted the policy I could then run both commands
If you need the exact errors I could try them again on the same or a fresh VM of W10

**Comment by get-itips** [comment]
Hello @RNR1995 
As I could not reproduce I do not identify a need to update the article, also verified on a different host.
Thanks for your feedback!

**Comment by RNR1995** [comment]
Hello

I understand what I wrote now

I had to unrestrict PowerShell before I could import the Teams Module that is all

That step is not on the page

This was a pretty fresh W10 pro VM

Thank you

Ron
