### ISSUE TITLE
The article is outdated

### ISSUE THREAD

**Issue by misha-franz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8639]
[Enter feedback here]

The article needs to be updated.

For example it doesn't list LCP devices like AudioCodes C435, for which remote sign in makes the most sense.

Also it lists firmware 1.10.120 for AudioCodes phone which had tons of bugs and remote sign in did not work reliably.

Not sure it covers remote sign out since it was introduced later.

Microsoft support uses this article as guidance, which introduced a lot of confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 344ac314-e98e-ab21-ef47-fb0da80ec884
* Version Independent ID: 8f3d2fe8-5d96-4298-f875-fb3e64688afc
* Content: [Remote provisioning and sign in for Teams Android devices - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/remote-provision-remote-login)
* Content Source: [Teams/devices/remote-provision-remote-login.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/remote-provision-remote-login.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @misha-franz, thank you for your feedback.

@cazawideh, do you think we can refresh this article? Thanks!

**Comment by cazawideh** [comment]
@dariomws Yes, there are plans in-progress to update this article soon.
