### ISSUE TITLE
Online licensing requirements missing

### ISSUE THREAD

**Issue by itthing** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#864]
At present, the URL for the online licensing requirements (https://docs.microsoft.com/en-us/SkypeForBusiness/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/skype-room-systems-v2.md) is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 515e5db8-20be-f979-5de9-3998713518dd
* Version Independent ID: a284fee3-f324-2984-431e-df14d3c4bd2d
* Content: [Skype Room Systems v2 requirements](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/requirements)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by AndreaBarr** [comment]
@itthing Thank you for this feedback

We apricate you letting us know the URL is missing. I will get this over to the Teams/Skype for Business so we can get this updated with the URL. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by jambirk** [comment]
Added the link suggested. It should go live shortly.
