### ISSUE TITLE
Incorrect documentation for New Zealand

### ISSUE THREAD

**Issue by timwelchnz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8642]
The process for obtaining phone numbers is totally different to this documentation in New Zealand. 

Apparently we are classed as a "preview market" and as such phone number orders are submitted manually and "may take up to 15 days or more to fill"

It would be great if the documentation was at least updated to reflect the process in New Zealand and highlight that it is different for preview markets than the current documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e37f13b-cb86-955e-147c-fa916da063f9
* Version Independent ID: 4dd77188-abcb-fae2-3cf3-12b82b591bad
* Content: [Getting phone numbers for your users - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/getting-phone-numbers-for-your-users#get-new-phone-numbers-for-your-users)
* Content Source: [Teams/getting-phone-numbers-for-your-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/getting-phone-numbers-for-your-users.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by timwelchnz** [comment]
It appears that there is documentation of the New Zealand experience but its not linked to this documentation in any way.
https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization/phone-number-management-for-new-zealand

Also if you make a phone number request via the Teams Admin Portal with a Global Admin account that is not email enabled you won't get notified in any way about the progress of the request. 
The portal for this is hidden away but you can access it directly at https://pstnsd.powerappsportals.com/

**Comment by get-itips** [comment]
Hello @timwelchnz 
Thanks for your feedback!

There is already, a note about that in the article

>Use a request form for new numbers. Sometimes **(depending on your country or region)** you won't be able to get your new phone numbers using the Microsoft Teams Admin Center or you'll need specific phone numbers or area codes. See [Manage phone numbers for your organization](https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization) for more information.

And the note includes the link to the index document to review every country's special consideration.

Thank you!

**Comment by get-itips** [comment]
@scanum
