### ISSUE TITLE
Unassigned Number Treatment for Org-Wide

### ISSUE THREAD

**Issue by SternalLime626** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8643]
The feature either needs to be expanded, or a bug is in the current application to limit the amount of numbers users in a treatment.  To cover off an org in a region  (ie....^\+1770\d{7}$)    cannot be used and will caused Teams calls to fail.  The largest available rule seems to be a "d{4}"

There should be an ability to cover ANY number that comes in, but is unassigned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed4beab-bb0d-fba4-814e-147d22fd97e5
* Version Independent ID: 8ed4beab-bb0d-fba4-814e-147d22fd97e5
* Content: [Routing calls to unassigned numbers - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/routing-calls-to-unassigned-numbers)
* Content Source: [Teams/routing-calls-to-unassigned-numbers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/routing-calls-to-unassigned-numbers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by JensTrier** [comment]
@SternalLime626 Thanks for the feedback. Please open a Microsoft support case to identity the root cause of the issue you are seeing.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
