### ISSUE TITLE
Org-wide settings no longer apply

### ISSUE THREAD

**Issue by azha23** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8648]
This page needs to be updated with accurate instructions, the Org-wide section doesn't exist anymore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffbf0bfd-c15e-b10b-0cc9-6a27ac1e6634
* Version Independent ID: 58575371-9e09-fadb-76f6-7491df8580a3
* Content: [Set your coexistence and upgrade settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/setting-your-coexistence-and-upgrade-settings)
* Content Source: [Teams/setting-your-coexistence-and-upgrade-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/setting-your-coexistence-and-upgrade-settings.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by lindspea** [comment]
@azha23 thank you for reaching out and helping to improve Microsoft Docs. This has been corrected in another PR and we are just waiting for it to be approved, then it will reflect correctly in the article.
