### ISSUE TITLE
Page is not clear about Firefox support

### ISSUE THREAD

**Issue by emardee** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8650]
This document is not fully clear on Firefox support, or lack thereof! There are two issues.... the lack of support for Firefox itself, which appears to be arbitary, rather than technological in basis.... and then how this document reports the support (or lack thereof).

Firstly the lack of support for Firefox itself, (which is noted in the browser list for Firefox on this page, as being "not supported"). It appears that Mozilla have fixed all the issues middle of last year, and if you tell your Firefox browser to pretend to be Edge in the user agent string, then everything works properly including video calls. So reporting this as "unsupported" appears to be based not on technological limitations, which seems to be an odd choice... (given that encouraging ease of call and meeting attendance without download, must surely reduce barriers to takeup of the product, and encourage more to use it). Can we reduce this arbitary limitation, and start supporting Firefox now, since it clearly already just works! There is even Firefox add-on to change user agent for you, but not practical to tell non-techy users to download add-ons or plugins.... (or Teams clients for that matter!).... just to join one call! 
Here's the Add-on that pretends to be Edge to makes Teams work in Firefox browser: 
https://addons.mozilla.org/en-US/firefox/addon/teams-phone-fix/

In terms of the feedback on this page itself, we noted that this page, in the browser table, lists Firefox browser as "not supported", yet lower down the page we have a purple box which appears to contradict that, by saying:
`Note
As long as an operating system can run the supported browser, Teams is supported on desktop computers. For example, running Firefox on the Linux operating system is an option for using Teams.`

This infers that Firefox is a supported browser, and is therefore a way to run Teams on Linux... however, this is clearly not what the browser list says higher up the page. 

Would be great to get Firefox officially supported for all Teams meeting and call features alongside the other main browsers (especially since it seems to already work just fine!). But until then, this page might need tidying up (especially in the purple box) to better reflect the current situation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c86f401-cff4-93b3-ff69-b9787a87e644
* Version Independent ID: c0808bd3-cf63-0625-4c3c-65469c26fb3e
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients?tabs=Windows#web-client)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
