### ISSUE TITLE
Correction on password expiration

### ISSUE THREAD

**Issue by danielscott1709** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8651]
Hi
On the Azure AD 2.0 password expiration section, shouldn't it be firstly to use Connect-AzureAD ? Then to use Set-AzureAdUser?
It currently has the on-prem connection steps I think?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Create resource accounts for rooms and shared Teams devices - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-office-365?tabs=m365-admin-center%2Cazure-active-directory2-password%2Cactive-directory2-license)
* Content Source: [Teams/rooms/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-office-365.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
