### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by kovacszo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8652]
This link is broken: https://www.verba.com/solutions/microsoft-teams-recording
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 896e3ed7-aaf5-ad40-9a5f-1374d85c3e82
* Version Independent ID: 253d2a6b-9225-723a-cbc1-c296c3cfd36c
* Content: [Introduction to Teams Policy-based Recording for Calling & Meetings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-recording-policy)
* Content Source: [Teams/teams-recording-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-recording-policy.md)
* Service: **msteams**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by Reeced40** [comment]
@kovacszo thank you for reaching out. Could this be the correct article to link here? https://www.verint.com/engagement-data-management/microsoft-teams-recording/?msclkid=7a6b2828a6ae11ec9c68fb452402fd42
