### ISSUE TITLE
Update transfer VoIP calls to PSTN and simultaneous ringing tables

### ISSUE THREAD

**Issue by jagonzal01** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8653]
Hi,

I find the table for transferring VoIP calls to the PSTN a little bit confusing, it is said that all users are able to make the transfer through Gateway1 based on their voice routing policy, does it mean that the only requirement is to have Gateway1 on their VRP even if they don't have permissions to make the call? I mean:
- User3: this user may have Gateway1 in his VRP but it does not have permissions to make an outbound call from Site2 through Gateway1 because the gateway is LBR enabled and in a different site (Site1), so in this case, the transfer would work or fail?
- User4: this user is not LBR enabled so it doesn't make sense to have Gateway1 in his VRP, so I guess the transfer would fail always, but in the case Gateway1 is added to his VRP, would it work?

The same doubts for Simultaneous ringing. Would it be possible to update those tables to clarify a little bit how it works? If the only requirement is to have the Gateway on the VRP because what is checked is the permission of the user that is transferred (not the one who is transferring) then I guess the table is fine although it would be great to have a more detailed explanation, if the user who is transferring the call needs to have permissions to make the call through the destination Gateway then I think only the scenario for User2 would work, the rest of them would fail.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e427e0b-ef18-6947-27a6-eb75ddbdead7
* Version Independent ID: baf34a47-7d43-8291-7792-dd0b5dac1931
* Content: [Plan Location-Based Routing for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/location-based-routing-plan#teams-user-transfers-or-forwards-call-to-pstn-endpoint)
* Content Source: [Teams/location-based-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/location-based-routing-plan.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by lindspea** [comment]
@jagonzal01 thank you for reaching out and helping to improve Microsoft Documents. I noticed that the article has been updated recently. Please can you let me know if you still need further assistance.

**Comment by jagonzal01** [comment]
Hi @lindspea, I see the article has been updated but not the tables that I comment on my post, I think those tables are wrong or at least misleading as people may think that users in different sites can transfer VoIP calls from LBR enabled User1 to the PSTN if they have Gateway1 in their VRP but in fact (at least as far as I know) this is not possible due to users in a different location than a LBR enabled Gateway cannot use it. 
In my opinion the table should be similar to this one, where only User2 is allowed to make the transfer:
https://docs.microsoft.com/en-us/microsoftteams/location-based-routing-plan#user-enabled-for-location-based-routing-2

**Comment by lindspea** [comment]
@scanum please can you check with the author if this needs to be updated?

**Comment by JensTrier** [comment]
@jagonzal01 Thanks for the feedback! Both tables are in fact correct. In both tables, the caller is the LBR enabled User1 in Site1. User1 is only able to make outbound PSTN calls via Gateway1 in Site1. In both scenarios User1 will be connected to a PSTN user by means of either a transfer or simultaneous ringing. No matter who performs the transfer or simultaneous ringing, it will be only work if the PSTN call they generate is routed out of Gateway1 in Site1. That's why the tables looks like they do.

I'll try to make the tables a bit clearer

**Comment by jagonzal01** [comment]
Thanks for the answer @JensTrier , I totally agree that User1 can only be transferred to the PSTN through Gateway1 but I disagree that "no matter who performs the transfer or simultaneous ringing" due to as far as I know the user who transfers the call (or makes the simultaneous ringing) needs to have also permissions to use Gateway1, otherwise the transfer or simultaneous ringing will fail. Based on the architecture of the article and the scenarios shown in the tables, the only user that has permissions to make the transfer or simultaneous ringing is User2, all other users will receive an error when they try to do it even if they have Gateway1 in their VRP.
If the point of those tables is to indicate that any user with permissions to use Gateway1, no matter where they are, would be able to make the transfer or simultaneous ringing to the PSTN, then I agree with that point, but if we follow the architecture then in my personal opinion they should indicate that all scenarios except the one for User2 would fail.
Thank you very much for your help, really appreciate it. Best regards.

**Comment by JensTrier** [comment]
That is what it means :-)

Whether it fails for User2 to User6 only depends if they have online voice routes that will allow the call to be routed out of Gateway1. 

If they have, then it will work. 

If they don't, the call will route out some other gateway that User1 is not allowed to use and then the call will fail due to LBR restrictions for User1.

The LBR state of User2 to User6 is not taking into account, since they will not be the resulting party talking to the PSTN. That is User1 in all cases.

**Comment by jagonzal01** [comment]
Ok, thanks, then everything is clear, my assumption was wrong as I thought LBR was checked for User2 to User6 as well to make the transfer (I know they are not going to talk to the PSTN but I though the authorization process was the same as if they were making a call to the PSTN).

**Comment by JensTrier** [comment]
No worries & thanks for taking the time to provide feedback! Please keep it coming.

Feel free to close this issue.
