### ISSUE TITLE
New phone number request for New Zealand Form is only in Maori

### ISSUE THREAD

**Issue by timwelchnz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8659]
The linked form "New phone number request for New Zealand (v.1.0) (mi-nz)" is only in Maori - there needs to be an English version for the other 96.3%* of us that can't converse in Maori.

* https://socialreport.msd.govt.nz/cultural-identity/maori-language-speakers.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10b53099-c0ba-9386-563f-78bb67180618
* Version Independent ID: ec2bb28a-304a-2925-8729-f7a5c9f6f07d
* Content: [Phone number management for New Zealand - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-for-your-organization/phone-number-management-for-new-zealand)
* Content Source: [Teams/manage-phone-numbers-for-your-organization/phone-number-management-for-new-zealand.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-phone-numbers-for-your-organization/phone-number-management-for-new-zealand.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by Reeced40** [comment]
@scanum please can you ask the author for help with the English version of the article that is linked here https://download.microsoft.com/download/4/a/a/4aa04212-a13d-46bf-b09e-1efbcbb2e622/new-phone-number-request-for-new-zealand-(v1.0)-(mi-NZ).pdf and I'll get the PR done.

**Comment by scanum** [comment]
Hi @SerdarSoysal Hope you are well. Could you kindly help with this issue? Thanks.

**Comment by itcentrenz** [comment]
Is anything happening with resolving this issue? @SerdarSoysal?

**Comment by scanum** [comment]
Hi @SerdarSoysal Hope you are well. Could you kindly help with this issue? Thanks.

**Comment by scanum** [comment]
Hi @SerdarSoysal Hope you are well. Could you kindly help with this issue? Thanks.

**Comment by scanum** [comment]
Hi @SerdarSoysal Hope you are well. Could you kindly help with this issue? Thanks.

**Comment by timwelchnz** [comment]
I think we can safely close this issue now that the original page has been totally updated and there is no longer a downloadable form in any language.
