### ISSUE TITLE
Loop files are not .loop, they are .fluid

### ISSUE THREAD

**Issue by TotallyInformation** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8661]
On the page [Overview of Loop components in Teams](https://docs.microsoft.com/en-us/microsoftteams/loop-components-in-teams), the page keeps referring to `.loop` files. But the files don't end in `.loop` at all, they end in `.fluid`.

[This page](https://docs.microsoft.com/en-us/sharepoint/manage-loop-components) uses the correct file extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 276b708d-786c-3981-7b22-2fdb5e96599a
* Version Independent ID: 276b708d-786c-3981-7b22-2fdb5e96599a
* Content: [Overview of Loop components in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/loop-components-in-teams)
* Content Source: [Teams/loop-components-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/loop-components-in-teams.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @TotallyInformation, thank you for your feedback.

The article was updated last Tuesday to change the file extension from .loop to .fluid.
