### ISSUE TITLE
How can I find such supported Teams apps?

### ISSUE THREAD

**Issue by TobiasAT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8670]
Am I wondering how I can find such supported Teams apps, to work in Outlook and on Office.com too? Is there an indicator somewhere for the supported apps?

Regards
Tobias 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 834c6ab3-58ea-17fd-9350-f6e419e8c6cc
* Version Independent ID: 834c6ab3-58ea-17fd-9350-f6e419e8c6cc
* Content: [Manage access to Teams apps across Microsoft 365 - Microsoft Teams](https://docs.microsoft.com/en-gb/MicrosoftTeams/manage-third-party-teams-apps)
* Content Source: [Teams/manage-third-party-teams-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-third-party-teams-apps.md)
* Service: **msteams**
* GitHub Login: @guptaashish
* Microsoft Alias: **guptaashish**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by TobiasAT** [comment]
Oh, the typical copy & paste answer. Just that the issue can be closed. As always in my replies to you, not customer orientated. If I open a support case for that situation the colleagues have no clue about the feature. You can bring this to your product teams too. Meanwhile, I'm not sure whether you are a bot with one predefined answer. Goodbye.
