### ISSUE TITLE
Virtual User license isn't required for nested resource accounts

### ISSUE THREAD

**Issue by Sanjeev017** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8674]
Hi,

please add a condition here that a license is not required when the resource account is a nested account. when reading the prerequisite, it suggests that a license is mandatory for all resource accounts.
From the article -A free Microsoft Phone System - Virtual User license for each resource account

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23ff8713-7e33-ad8e-99df-9308a7c006d7
* Version Independent ID: c9263eba-599b-831b-37fb-837046df9d6a
* Content: [Plan for Teams auto attendants and call queues - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/plan-auto-attendant-call-queue)
* Content Source: [Teams/plan-auto-attendant-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-auto-attendant-call-queue.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @Sanjeev017 
How are you? So I can test this to see if we need to edit the article, do you mean nested AA?
Thank you

**Comment by Sanjeev017** [comment]
Nested AA/CQ are the one where we don't want to assign a PSTN number. i.e. in below call flow-
AA(assigned a service number so it requires virtual user license)>CQ( this call is receiving calls from AA no license is required for the associated resource account)
PSTN caller--> AA>CQ>Agent

**Comment by get-itips** [comment]
Hello @Sanjeev017 thanks for detailing your scenario. 
That is mentioned in this other article that explains in more details the requirements

https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/virtual-user

> No license is needed for resource accounts that will be used with nested auto attendants or call queues that don't have a phone number assigned. See the following diagram for reference.

That article is linked in the article you opened the issue for.

Thank you!

**Comment by get-itips** [comment]
@scanum
