### ISSUE TITLE
Show Certification level

### ISSUE THREAD

**Issue by rquickenden** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8675]
[Enter feedback here]
I woudl liek to see the level of certification these partners have applied for - there are 3 levels so please show the levels that partners have applied/certifying for.

Thanks
Rob

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb24d873-4507-3a2f-1d0f-a38a305b8ff5
* Version Independent ID: 6a927fb3-5cc9-91de-b9ce-d057156d3523
* Content: [Teams Contact Center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-contact-center?tabs=connect)
* Content Source: [Teams/teams-contact-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-contact-center.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by dariomws** [comment]
Hi @rquickenden, thank you for your feedback.

@cazawideh, do you think we can provide that level of detail? Thanks!

**Comment by cazawideh** [comment]
@dariomws I'll bring this feedback to the product group and see if we can add this information.

**Comment by cazawideh** [comment]
Hi @rquickenden, to clarify, are you requesting that the article includes which of the three models (connect, power, or extend) that the partners are certified for?

**Comment by rquickenden** [comment]
Good evening
Yes, that's the request please...

Many thanks
rob
________________________________

**Comment by scanum** [comment]
@cazawideh hope all is well. Wanted to check in to see if there is an update here? Thanks.

**Comment by scanum** [comment]
@cazawideh hope all is well. Wanted to check in to see if there is an update here? Thanks.

**Comment by cazawideh** [comment]
Reassigning to @wlibebe who is the current writer for this topic

**Comment by scanum** [comment]
@wlibebe Hope all is well. is there an update on this issue? Thanks.

**Comment by scanum** [comment]
@wlibebe Hope all is well. is there an update on this issue? Thanks.

**Comment by wlibebe** [comment]
Hi @scanum ! I've discussed this with our team and we are considering this integration. Thank you! :)
