### ISSUE TITLE
It says you need to run 

### ISSUE THREAD

**Issue by jansenbro** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#868]
The setup steps for Office 365 say : You will need to connect to Azure Active Directory to apply some account settings. To connect to Azure AD, run the following cmdlet:

Connect-MsolService -Credential $cred

However this is no longer supported. 

What Steps/methodolgy can be used now instead of the MsolService to set this up? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41965bc8-45c0-e4eb-aa36-5ef5adbe460a
* Version Independent ID: 97de65ad-04fc-5b62-c7c7-fba8d0aeb1de
* Content: [Deploy Skype Room Systems v2 with Office 365](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/with-office-365)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/with-office-365.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by AndreaBarr** [comment]
@jansenbro  Thank you for this feedback

I want to make sure we get this cmdlet investigated. I am going to get this over to the Teams/Skype for Business team so they can address this properly. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by SharS** [comment]
@jansenbro - here's the answer to your question: 

Those (all *Mosl* cmdlets) have all been replaced by the Azure Active Directory 2.0 cmdlets. That one specifically is:

Connect-AzureAD -Credential $cred

https://docs.microsoft.com/en-us/powershell/module/azuread/connect-azuread?view=azureadps-2.0

**Comment by jambirk** [comment]
@jansenbro  @shars I've had another look, and that doesn't seem to be completely true according to https://docs.microsoft.com/en-us/powershell/module/msonline/?view=azureadps-1.0  the MSOL comdlets should still work fine IF you have installed the 1.0 module. If you have only installed the 2.0 module, then I'm sure you'd need to use the corresponding 2.0 commands instead.
