### ISSUE TITLE
 German version still states Public Preview

### ISSUE THREAD

**Issue by mwe-microsoft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8680]
German version still states Public Preview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56b532a-ab80-0e4c-dcd8-829a0a68c08e
* Version Independent ID: e56b532a-ab80-0e4c-dcd8-829a0a68c08e
* Content: [End-to-end encryption for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-end-to-end-encryption?msclkid=36d069f2aa9311ec93e0d7d0facb2582&source=docs)
* Content Source: [Teams/teams-end-to-end-encryption.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-end-to-end-encryption.md)
* Service: **msteams**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by lindspea** [comment]
@OfficeGlobal

**Comment by lindspea** [comment]
@mwe-microsoft thank you for reaching out. Just for clarity, is this a translation issue in the German article?

**Comment by mwe-microsoft** [comment]
Hi Lindsay,

no, the English article has the headline:

Use end-to-end encryption for one-to-one Microsoft Teams calls


The German Version:

Verwenden der End-to-End-Verschlüsselung für 1:1-Anrufe in Microsoft Teams (öffentliche Vorschau)

Where "(öffentliche Vorschau)" means "Public Preview"


I live in Teams and don't check email in time! If this needs my attention right away hit this link to chat with me in ***@***.***>

Mit freundlichen Grüßen / Best Regards

Marcel Weißkirchen

Teams Technical Specialist
Specialist Team Unit

Office:   +49 221 8010 2078
Mobile:  +49 151 44 01 27 35
Email: ***@***.******@***.***>
IM: ***@***.******@***.***>
***@***.***<https://twitter.com/microsoft>   ***@***.*** <https://www.facebook.com/Microsoft>    ***@***.*** <https://www.linkedin.com/company/microsoft>    ***@***.*** <https://www.youtube.com/user/Microsoft>    ***@***.*** <https://www.yammer.com/>
[MSFT_logo_Gray DE sized SIG1.png]



Microsoft Deutschland GmbH
Walter-Gropius-Straße 5, 80807 München
Microsoft - Official Home Page<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fde-de%3Fql%3D2&data=04%7C01%7Cmarcel.weisskirchen%40microsoft.com%7C1e891cd528d240528e4f08d8e4711765%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637510522654089654%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cd3ZyzPCjncO8HPOJqRcoSIImhsdklPdAe4W34zXZC8%3D&reserved=0>
Home | News Center Microsoft<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnews.microsoft.com%2Fde-de%2F&data=04%7C01%7Cmarcel.weisskirchen%40microsoft.com%7C1e891cd528d240528e4f08d8e4711765%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637510522654089654%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=W7hI%2B%2BYrG8i5kqQXcRItPLwgBpxdzuJyswKPRRYe2GY%3D&reserved=0>
Datenschutzerklärung von Microsoft - Microsoft-Datenschutz<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprivacy.microsoft.com%2Fde-DE%2Fprivacystatement&data=04%7C01%7Cmarcel.weisskirchen%40microsoft.com%7C1e891cd528d240528e4f08d8e4711765%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637510522654099605%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3h7DVI5FjQ1w1%2FsOLSfsCVktNn3ML%2FKcxMMFZ7PWEWg%3D&reserved=0>

Geschäftsführer*in: Dr. Marianne Janik (Vorsitzende), Thorsten Herrmann, Benjamin O. Orndorff, Keith Dolliver
Amtsgericht München, HRB 70438

Von: Lindsay ***@***.***>
Gesendet: Dienstag, 29. März 2022 10:12
An: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Marcel Weisskirchen ***@***.***>; Mention ***@***.***>
Betreff: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] German version still states Public Preview (Issue #8680)


@mwe-microsoft<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmwe-microsoft&data=04%7C01%7Cmarcel.weisskirchen%40microsoft.com%7C4e99ebd1e9d84397308b08da115bd764%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637841383415422902%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KGD%2BBAa3hntsNP1IYgJB2QdeJuwVOr8usgTTTibWzWQ%3D&reserved=0> thank you for reaching out. Just for clarity, is this a translation issue in the German article?

-

**Comment by lindspea** [comment]
@tiburd please can you assist?

**Comment by tiburd** [comment]
@TinaMcN 
Hi, Tina, 
Are you able to help with this one?
Thanks!

**Comment by TinaMcN** [comment]
@mwe-microsoft thanks for letting us know about it.  I asked the translators to fix the German version, it shouldn't say "public preview".   Should be fixed in 1-2 business days.

**Comment by tiburd** [comment]
Article title has been updated and no longer includes "(öffentliche Vorschau)":
<img width="409" alt="image" src="https://user-images.githubusercontent.com/54688693/196546804-cd1107ee-8c2d-4040-b230-0980a0e1b647.png">

Closing issue.

cc: @scanum
