### ISSUE TITLE
Update Teams Logical Architecture - Stream to ODSP

### ISSUE THREAD

**Issue by satishkr9506** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8685]
Team,
This document is still referencing Teams recording to Stream. We should update this to ODSP.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ad624-9792-91b7-c85f-09b839b1ea44
* Version Independent ID: e8288f91-11bd-599b-8a88-074917b315a4
* Content: [Microsoft Teams IT architecture and voice solutions posters - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-architecture-solutions-posters)
* Content Source: [Teams/teams-architecture-solutions-posters.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-architecture-solutions-posters.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @satishkr9506, thank you for your feedback.

There is work in progress to update this poster. I have no ETA but it should be updated in a few weeks.
