### ISSUE TITLE
Geographical availability of Operator Connect Conferencing licenses

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8686]
Can you please provide in this article information in which countries customers can aquire the 0$ license for Operator Connect Conferencing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90af45ab-6698-a390-2769-2baf55f64b17
* Version Independent ID: 90af45ab-6698-a390-2769-2baf55f64b17
* Content: [Plan for Operator Connect Conferencing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/operator-connect-conferencing-plan)
* Content Source: [Teams/operator-connect-conferencing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/operator-connect-conferencing-plan.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by dariomws** [comment]
Hi @Larryngolog, thank you for your feedback.

Could you provide more detail, please? I cannot find any mention of a free license for Operator Connect Conferencing in this article.

**Comment by Larryngolog** [comment]
That's exactly my point - there is no mention of the Operator Connect Conferencing availability. OCC is not available everywhere so it would be good if this article would mention where OCC is available and where it's not available. If this article is not a proper place for this information then maybe it's possible to add it here https://docs.microsoft.com/en-us/MicrosoftTeams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans

**Comment by DaniEASmith** [comment]
Hello,

I'm adding @Heidi ***@***.***> to this email thread as she owns Audio Conferencing documentation.

For context, this request is to mention the region and country availability of Operator Connect Conferencing (OCC) in this article: https://docs.microsoft.com/en-us/microsoftteams/operator-connect-conferencing-plan<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoftteams%2Foperator-connect-conferencing-plan&data=04%7C01%7Cdanismith%40microsoft.com%7C08635c5c66194888e76608da0d91bb52%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637837216825894115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=adediV4UUqOPgkRT9KL32FTglTs621M1B4O0gcfX1YE%3D&reserved=0>.

It was also asked whether a mention of OCC should be included in this article: https://docs.microsoft.com/en-us/MicrosoftTeams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2FMicrosoftTeams%2Fcountry-and-region-availability-for-audio-conferencing-and-calling-plans%2Fcountry-and-region-availability-for-audio-conferencing-and-calling-plans&data=05%7C01%7Cdanismith%40microsoft.com%7C0fab9836e9d9431e63c208da29b1aef0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637868140426529040%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qZwW48xSmBARLVJC2DVP1vW7%2BGjfM3gaNoBtRXyRSdI%3D&reserved=0>; however, I'm not sure how granular this doc is meant be as it doesn't mention Operator Connect in general.


Dani Smith
she/her
Technical Writer 2
E+D MARVEL
***@***.******@***.***>

[Microsoft Logo]



________________________________

**Comment by DaniEASmith** [comment]
I can start an investigation into this request, and make a determination as to the best location for this information. I agree that putting it into an article that people don't look to for Operator Connect information probably isn't going to help them discover it there.

Heidi P.

**Comment by scanum** [comment]
Hi @DaniEASmith hope all is well. Wanted to check if there is an update here.

**Comment by DaniEASmith** [comment]
@scanum I just re-reached out to the PM for details. I hope to hear back soon so we can get the AC licensing issues resolved.

**Comment by scanum** [comment]
Thank you @DaniEASmith!

**Comment by dariomws** [comment]
Hi @DaniEASmith hope all is well. Wanted to check if there is an update here. Thanks!

**Comment by DaniEASmith** [comment]
I'm trying to reach the PM to answer this question. I re-pinged him this morning, so fingers crossed!


Dani Smith
she/her
Technical Writer 2
E+D MARVEL
***@***.******@***.***>

[Microsoft Logo]



________________________________

**Comment by DaniEASmith** [comment]
@dariomws After speaking with the PM, there are 2 different lists of country/region availability for Operator Connect Conferencing: where the license can be purchased and where phone numbers can be acquired. 

It has also been brought to my attention that all of the Calling Plan and Audio Conferencing Availability topics no longer belong to my team. They have been moved to a self-service repo where PMs can make their own edits an contributions.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
