### ISSUE TITLE
sample payload not valid

### ISSUE THREAD

**Issue by AlexRademeyer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8687]
the sample payload is not actually valid Json.....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad4aa355-090d-7315-aaf1-ed31a654e942
* Version Independent ID: 6bf8a83b-2bb6-6932-2e0d-6ccc742d1777
* Content: [Microsoft Teams Devices Monitoring and Alerting - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/alerts/device-health-status)
* Content Source: [Teams/alerts/device-health-status.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/alerts/device-health-status.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by get-itips** [comment]
Hello @AlexRademeyer thanks, looking into this
