### ISSUE TITLE
Superscript confusing

### ISSUE THREAD

**Issue by chaseWillden** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8696]
The superscript being a number is very confusing. For a while, I thought it was 250 squared and spent time figuring out why I couldn't go passed 249. See the screenshot as an example.

https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams

<img width="245" alt="Screen Shot 2022-03-28 at 10 32 11 AM" src="https://user-images.githubusercontent.com/3342754/160444848-e9ed29e5-e3da-4b5e-a083-fabc372484b6.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by dariomws** [comment]
Hi @chaseWillden, thank you for your feedback.

We'll take it into consideration. If more people complain about the same situation, we'll proceed to improve the article.
