### ISSUE TITLE
initial templates agent timelines page shows a blank as a particular agent when filtering

### ISSUE THREAD

**Issue by jtrich** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8699]
[Enter feedback here]
default templates for agent timeline page, when filtering is leaving out 1 agent in each queue and leaving it as a blank. All other agents show up in each queue but 1 each do not. Nothing I can find seems to indicate why. Ideas? I have 2 queues and each one has a blank agent. We have not had enough volume to see if it aggregates those blanks when not filtered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb8d8b48-561b-6817-1ce0-4b2aedc261a8
* Version Independent ID: dfd5cf4a-509a-3ed1-0267-6281c251fbef
* Content: [Set up Call Quality Dashboard (CQD) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/turning-on-and-using-call-quality-dashboard#assign-admin-roles-for-access-to-cqd)
* Content Source: [Teams/turning-on-and-using-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/turning-on-and-using-call-quality-dashboard.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @jtrich Rich, how are you?
Can you please include a screenshot (hiding any specifics about your tenant) of what you are experiencing so I can understand if an improvement to the article is required? (We are limited to documentation changes and improvements)
Thank you

**Comment by jtrich** [comment]
Thanks, not sure why this would show a user as blank so is it report, is it user, is it a property in ad it is pulling or logic that does not match

I tried to take it a few different ways. It is the default powerbi template I have changed nothing but if it hit that drop down for agent name it shows a blank name, since we have only a handful of agents I can deduce which agent(s) is/are affected but cannot figure out the why.

Hope that helps

**Comment by get-itips** [comment]
@scanum

**Comment by jtrich** [comment]
Ok thanks!
