### ISSUE TITLE
Step 6 in "Install Windows 10 and the Skype Room Systems v2 console app" obsolete

### ISSUE THREAD

**Issue by Travis-Snoozy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#87]
In the section titled _Install Windows 10 and the Skype Room Systems v2 console app_, step 6 is obsolete, and the paragraph afterwards needs to be adjusted, due to how the section titled _Prepare the installation image_ was recently changed.

Step 6 and the paragraph following it should be changed to read something more like:

6. When installation is complete, the system will shut down.

After the system has shut down, it is safe to remove the USB Setup Disk. At this point, you can place the tablet in the dock and attach the peripherals needed for your meeting room. Refer to the manufacturer instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51d42140-9f7b-a6f3-7a3e-76cc7331cf22
* Version Independent ID: a7dacc56-c2df-55fb-76a3-ecb194564fae
* Content: [Configure a Skype Room Systems v2 console](https://docs.microsoft.com/en-us/SkypeForBusiness/deploy/deploy-clients/console#)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/console.md)
* Service: **unspecified**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
pull request approved, closing issue
