### ISSUE TITLE
inconsistent with blog post

### ISSUE THREAD

**Issue by TobieFysh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#870]
Hi,

this doc is not consistent with original blog post:

https://blogs.technet.microsoft.com/nexthop/2018/04/18/disabling-tls-1-01-1-in-skype-for-business-server-2015-part-1/

Which should be considered authoritative?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8abfab81-725e-2c4c-6409-d796b82ee5b1
* Version Independent ID: 5f506445-eed0-3e0c-2979-5e20a13257c9
* Content: [Disable TLS 1.0/1.1 in Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/manage/topology/disable-tls-1.0-1.1)
* Content Source: [Skype/SfbServer/manage/topology/disable-tls-1.0-1.1.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/topology/disable-tls-1.0-1.1.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @heidip
* Microsoft Alias: **heidip**

**Comment by AndreaBarr** [comment]
@TobieFysh Thank you for this feedback

I am not sure which article is authoritative. Let me get this over to the Teams/Skype for Business team so we can get this addressed. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by MicrosoftHeidi** [comment]
Please be clear in what you think is inconsistent between the two pieces of documentation.

**Comment by get-itips** [comment]
Hi @MicrosoftHeidi how are you?

I think the user @TobieFysh refers to these points:

In Fully tested and supported servers section:
 
Docs does not mention this
 
_Survivable Branch Appliance (SBA) with Sfb Server 2015 CU6 HF2 or higher (it is the vendor's responsibility to package the appropriate CU and provide it, be sure to confirm with your vendor that the updates have been made available for your appliance)
Survivable Branch Server (SBS) with SfB Server 2015 CU6 HF2 or higher
Lync Server 2013 Edge Role Only**_
 
in Out of Scope section: Docs does not list:
 
_Lync Server 2010
Skype for Business for Windows Phone - Retired
Cloud Connector Edition***_

at least, those are the diffs I found.

**Comment by yogkumgit** [comment]
@MicrosoftHeidi please share your comments on the required clarification, given by @get-itips

**Comment by scanum** [comment]
@TobieFysh We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
