### ISSUE TITLE
Support for on-net conferencing for Select Dial-Out SKU

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8705]
Hello

Is the new Audio Conferencing Select Dial-Out SKU for On-Network Conferencing for AC? In other words - are user with this license entitled to use the On-net conferencing?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d4b1670-ab39-621e-025e-17d7d747cc09
* Version Independent ID: dcdd8284-ad29-4e46-4731-63fbbce08fb0
* Content: [On-network Conferencing for Audio Conferencing - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/audio-conferencing-on-network)
* Content Source: [Teams/audio-conferencing-on-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-on-network.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hello @Larryngolog I am looking into this

**Comment by Larryngolog** [comment]
Hello! Any update on this?

**Comment by get-itips** [comment]
> Hello! Any update on this?

Hello @Larryngolog I am still working on this one

**Comment by get-itips** [comment]
Hello @Larryngolog I just got this answer "customers with the $0 Audio Conferencing with dial-out to USA/CAN add-on SKU are eligible for On-network conferencing"

Hope this information helps you,

**Comment by get-itips** [comment]
@scanum
