### ISSUE TITLE
List should be updated or removed.

### ISSUE THREAD

**Issue by lcansby** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8706]
Missing some devices here that are certified, Teams Panels from Yealink and Logitech should be added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 344ac314-e98e-ab21-ef47-fb0da80ec884
* Version Independent ID: 8f3d2fe8-5d96-4298-f875-fb3e64688afc
* Content: [Remote provisioning and sign in for Teams Android devices - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/remote-provision-remote-login?source=docs)
* Content Source: [Teams/devices/remote-provision-remote-login.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/remote-provision-remote-login.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by dariomws** [comment]
Hi @lcansby, thank you for your feedback.

This issue is the same as:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8639

The message there from the article owner is:
"Yes, there are plans in-progress to update this article soon."
