### ISSUE TITLE
URL is broken

### ISSUE THREAD

**Issue by tiagoroxo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8708]
Hi team.

The URL https://aka.ms/qertemplates is broken. Can you please fix it?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 718b597f-258b-3d61-17b8-1d41c8436d07
* Version Independent ID: 78f3333e-36cd-384a-8b5b-29bae7e1ed88
* Content: [Data and reports in Call Quality Dashboard (CQD) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cqd-data-and-reports#import-the-cqd-report-templates)
* Content Source: [Teams/CQD-data-and-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-data-and-reports.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by Reeced40** [comment]
@tiagoroxo thank you for pointing this out and helping to improve Microsoft Docs. I'll do some research to find the correct link and have it fixed.
