### ISSUE TITLE
Does Teams mode SfBWithTeamsCollab support conversation in channels?

### ISSUE THREAD

**Issue by hansarh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#871]
Does Teams mode SfBWithTeamsCollab support conversation in Teams channels? If so is conversations also supported when the linked SfB user is homed on Skype for Business server on-prem?

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: 49921e8a-55ac-f547-d4e2-d329f5089c2e
* Version Independent ID: 91c3433a-3684-95cd-3426-4a5877b33106
* Content: [Migration and interoperability guidance for organizations using Teams together with Skype for Business](https://docs.microsoft.com/nb-no/MicrosoftTeams/migration-interop-guidance-for-teams-with-skype)
* Content Source: [Teams/migration-interop-guidance-for-teams-with-skype.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/migration-interop-guidance-for-teams-with-skype.md)
* Service: **msteams**
* GitHub Login: @arachmanGitHub
* Microsoft Alias: **MyAdvisor**

**Comment by AndreaBarr** [comment]
@hansarh Thank you for this feedback

I am not sure on the answer of what is supported on the Teams channel with the S4B users. Let me get this over to the Teams/Skype for Business team so we can get this answered. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@hansarh Thank you for this clarification. The Teams/Skype for Business teams will see this and address it properly.

**Comment by bjwhalen** [comment]
Yes, SfBWithTeamsCollab  will support conversation in the channel. Note that right now, all of the Teams UX is still available regardless of mode, but the intent is for that to change.

**Comment by LolaJacobsen** [comment]
I've updated the article - it'll go live later today. Thanks for the input!
