### ISSUE TITLE
"2 curated CQD templates" broken link

### ISSUE THREAD

**Issue by almaucla** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8710]
"2 curated CQD templates" broken link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a04f5de-2679-37c7-7d00-607471ea516d
* Version Independent ID: c96ec0af-910a-d9f8-9d3b-95564b39d7fa
* Content: [Use CQD to manage call and meeting quality in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/quality-of-experience-review-guide#feedback)
* Content Source: [Teams/quality-of-experience-review-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/quality-of-experience-review-guide.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by Reeced40** [comment]
@almaucla thank you for pointing this out and helping to improve Microsoft Docs. Could this be the correct link - https://www.microsoft.com/download/details.aspx?id=102291&msclkid=ab588574b4df11eca4800ecd117389fe
