### ISSUE TITLE
Switch accounts used to authenticate Google Calendar for Teams add-on

### ISSUE THREAD

**Issue by lissa2882** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8712]
I need to know how to switch the account used to authenticate the Google Calendar for Teams add-on in Google Calendar. I need to change it from a free personal account to my licensed work account but cannot find any way to do so in the Teams app or in Google Calendar.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by lissa2882** [comment]
It turns out that you can re-authenticate by using the Teams icon at the far left flyout menu. Problem solved!
