### ISSUE TITLE
generally available??

### ISSUE THREAD

**Issue by AlexRademeyer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8719]
Documentation claims Loop is "available" and mentions nothing about preview or targeted release.
However I (and other customers) don't see it. is it generally avialable?
If so, any feedback for customers who don't see it? instructions to enable it maybe?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 276b708d-786c-3981-7b22-2fdb5e96599a
* Version Independent ID: 276b708d-786c-3981-7b22-2fdb5e96599a
* Content: [Overview of Loop components in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/loop-components-in-teams)
* Content Source: [Teams/loop-components-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/loop-components-in-teams.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
