### ISSUE TITLE
Message Center alerts

### ISSUE THREAD

**Issue by realmnm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#872]
How often or at what intervall are the "Problem detected: Operability for Skype for Business" messages send out to a tenant? Begining of this month we got about 30 messages regarding "Operability for SFB" and most of the contained the same information. How come?

**Comment by AndreaBarr** [comment]
@realmnm Thank you for this feedback

I am not sure why you got so many messages regarding the same thing for Skype for Business. Let me get this over to the Teams/ Skype for Business team for investigation. If you need an expedited answer please open up a support ticket. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by kenwith** [comment]
@realmnm - I am still working on finding out the information and figuring out where we can put this in the documentation. If you have a place that you would expect to see it in the documentation let me know and I will add it to that location so it is in a place people would expect to find it.
