### ISSUE TITLE
AllowMsiOverride Undocumented

### ISSUE THREAD

**Issue by georgeescott** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8722]
`HKLM\Software\Policies\Microsoft\Office\16.0\Teams\AllowMsiOverride` is undocumented on docs.microsoft.com. The only Microsoft reference I could find is on [https://github.com/microsoft/TeamsMsiOverride/blob/main/Details.md#teams-msi-override](https://github.com/microsoft/TeamsMsiOverride/blob/main/Details.md#teams-msi-override).

I think this is an important setting to document as the %APPDATA% updater can be a little temperamental and not always update. It would be nice to know exactly how to force Teams to update from the Teams Machine-Wide Installer if the %APPDATA% version is older than the Machine-Wide version, especially in the event of any big security fixes in Teams that might need to be enforced where the Machine-Wide Installer is redistributed to clients.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Bulk install Teams using Windows Installer (MSI) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @georgeescott, thank you for your feedback.

I don't think that the use of that registry key is officially supported. That's why you don't see it documented here or in another article.

If you have problems updating the Teams desktop client, you can check the following article or contact Microsoft support:
https://docs.microsoft.com/en-us/microsoftteams/troubleshoot-installation
