### ISSUE TITLE
Update Document to display appropriate information

### ISSUE THREAD

**Issue by chelsea-york** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8726]
Working with customers and the Product Group, many have expressed confusion over Call Queues not respecting end user settings when it comes to forwarding calls or the simultaneous ring feature. Document clearly states forwarding not working but makes no mention of Calls "Also Ring" me/group/etc not supporting this with CQ. PG has confirmed that it isn't supported, so can we update the documentation to reflect the same?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e94dd85e-2ca7-23a6-90be-022ef5e08915
* Version Independent ID: 59cd2a22-f1bb-0702-149a-f672e7878d71
* Content: [Answer auto attendant and call queue calls - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/answer-auto-attendant-and-call-queue-calls#handling-an-auto-attendant-or-call-queue-call)
* Content Source: [Teams/answer-auto-attendant-and-call-queue-calls.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/answer-auto-attendant-and-call-queue-calls.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @chelsea-york 

Thanks for your feedback!
