### ISSUE TITLE
No Desktop icon or app registration when disabling autostart

### ISSUE THREAD

**Issue by hippman257** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#873]
We are including Teams in our default Windows image however we do not want it to autostart automatically when a user first logs in.

This past week we updated the install to the latest MSI (Teams_windows_x64.msi - 1.1.0.25457) and used the new option:

msiexec /i Teams_windows_x64.msi OPTIONS="noAutoStart=true"

Teams is installed for new users however Teams is not registered and cannot be found from via Win10 search and also there is no desktop icon for the user.

Ideally there needs to be a middle ground where we can install Teams per machine but choose to let the user initiate first launch.

**Comment by AndreaBarr** [comment]
@hippman257 Thank you for this feedback

It seems like a few things didn't work right. I want to get you over to Support. They have the resources to troubleshoot this with you and find a resolution. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
