### ISSUE TITLE
Latest Supported OS Release for Teams Rooms - 2 years old?

### ISSUE THREAD

**Issue by B123Stano** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8732]
Based on this documentation the most recently supported OS version for Teams Room systems on Windows is from 2020. 
Is that correct? Is there not a more recent supported Windows 10 version available that's been tested?

thanks!

-js 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ecd6ee6-8850-f346-5684-9c5d2444789f
* Version Independent ID: a55a7a01-211d-147a-5332-b68e1051a2a1
* Content: [Microsoft Teams Rooms app version support - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-lifecycle-support)
* Content Source: [Teams/rooms/rooms-lifecycle-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-lifecycle-support.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
