### ISSUE TITLE
Contradictory Text

### ISSUE THREAD

**Issue by HiltonGiesenow** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8734]
The last section of this page discussed Anonymous users, but the two paragraphs seem contradictory, specifically:

1. Anonymous users **can't** directly use apps in meetings.
2. [they] **can** interact with apps in Teams meetings if the user-level permission policy has enabled the app

My questions:

1. Which of the above is correct?
2. Can the page please be changed to word this better?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0735d322-f6f5-7cc8-9994-1420e3fb7baa
* Version Independent ID: f9b25b51-eb9c-63fa-b30e-e1490c8d31b6
* Content: [Teams apps behavior based on types of users - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/non-standard-users#:%7E:text=An%20anonymous%20user%20is%20a,their%20Microsoft%20or%20organization%27s%20account.)
* Content Source: [Teams/non-standard-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/non-standard-users.md)
* Service: **msteams**
* GitHub Login: @guptaashish
* Microsoft Alias: **guptaashish**

**Comment by get-itips** [comment]
Hello @HiltonGiesenow Hilton,

How are you?

The way I see it, the key is the word **directly** there, they can't interact with apps unless 

>the user-level permission policy has enabled the app. Anonymous users can only interact with apps that are already available in a meeting and can't acquire and/or manage these apps.

**Comment by HiltonGiesenow** [comment]
Thanks @get-itips . I'm still a bit confused though. For an example scenario, let's say a meeting organizer installs a meeting sidebar app - can the anonymous users use it? This sentence makes me think that it's No - "Native users can continue to use meetings apps if anonymous users are present."

**Comment by get-itips** [comment]
Hello @HiltonGiesenow Hilton,

What I understood when I first read that other sentence is that usage for native users is not affected by the presence of anonymous users in the meeting.

And the answer if they will be able to interact with the app -> if the user-level permission policy has enabled the app.

Let me know if that helps/you agree or still have some doubts,

**Comment by HiltonGiesenow** [comment]
No, it's still not clear to me. I haven't personally tested the scenario, so I'm not sure what will/won't happen, and the doc, as I read it, is contradicting itself. What do you think about this instead, for those two paragraphs:

> Depending on the global default permission policy in the organization, anonymous users may or may not be able to interact with an app that has been added to a meeting. Anonymous users can not, however, install an app to a meeting nor can they manage any apps that are within the meeting. Anonymous user are able to interact with Adaptive Cards sent by apps into meeting. 
> 
> Native users in the tenant are not affected by the presence of anonymous users and they can continue to use meetings apps irrespective of whether or not anonymous users are present in the meeting. For more information, see [Allow anonymous users to join meetings](https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams#allow-anonymous-users-to-join-meetings).

Could that work instead?

**Comment by get-itips** [comment]
Hello @HiltonGiesenow 

I tested the scenario, the anonymous user could only interact with an adaptive card _if an app sends an adaptive card in the chat_ as the article says. 

So nothing expressly mentioned -> will not be able to do.

No mention to bot possible, no interact with tab, nor message extensions.

If you take for example the other types of users in the article:

> Guest users can mention the bot and interact with adaptive cards.

Externals

>People from other organizations cannot add apps in meeting chats **but can interact with bots, tabs and message extensions once added to the chat.**

I'll analyze if an improvement to the section is necessary and if it gets approval, it will be reflected in the article

Thank you

**Comment by HiltonGiesenow** [comment]
oh wow, so a guest can't even interact with a meeting tab or bot? I didn't know that - very important! Thanks for checking and definitely worth updating the docs to make that more clear.

**Comment by get-itips** [comment]
Article was updated on https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/aa79ad8c27666003954014101d2cb3350dcae178 thanks @HiltonGiesenow !
