### ISSUE TITLE
Ability to add Tabs to Microsoft Teams Shared Channels

### ISSUE THREAD

**Issue by EdAlexander** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8735]
After configuring cross-tenant settings and created a shared channel there is no ability to channel owner to add a tab.  According to the documentation a team owner should have that ability.  Is there some undocumented setting required?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e6deaf-68f5-e3c9-7259-775ed7662d85
* Version Independent ID: 82e6deaf-68f5-e3c9-7259-775ed7662d85
* Content: [Shared channels in Microsoft Teams (Preview) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/shared-channels)
* Content Source: [Teams/shared-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/shared-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by EdAlexander** [comment]
![image](https://user-images.githubusercontent.com/13755026/162333235-4bc4ea49-02f5-47c2-b406-c75e5ca89bcf.png)
Missing member permissions in my test channel... Channel owner can also not add tabs/apps

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by EdAlexander** [comment]
case is open (Case #:30603177)
