### ISSUE TITLE
Team Live Events is available in GCCH

### ISSUE THREAD

**Issue by J227668** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8737]
Teams live events is available in GCCH but documentation states that it is not available today. Can we please update this documentation. Right now the document says: 

"These countries/regions and clouds aren't supported

Government Community Cloud (GCC)-H
Department of Defense (DOD)"

We should REMOVE Government Community Cloud (GCC)-H from the regions that are not supported. 

This was Roadmap feature 82954

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-live-events/plan-for-teams-live-events)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @J227668 I am looking into this

**Comment by get-itips** [comment]
Updated in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/fccae6549f2cbf993c118096bcd8a089170b3756

closing @scanum

**Comment by J227668** [comment]
Thank you @get-itips

**Comment by J227668** [comment]
One more question @get-itips  you list that this IS available for GCC. Should we list the same for GCCH? 

"Teams live events is now available for US Government Cloud Community (GCC) organizations." change to "Teams live events is now available for GCC, GCCH, and DoD"
