### ISSUE TITLE
Grant-CsTeamsEnhancedEncryptionPolicy is incorrect

### ISSUE THREAD

**Issue by CatalinDobreMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8739]
Hi,

While working on a case, I've found that this command is incorrect: Grant-CsTeamsEnhancedEncryptionPolicy -Identity Global -CallingEndtoEndEncryptionEnabledType Disabled

When I run it, it returns the following error:

![image](https://user-images.githubusercontent.com/103252032/162411858-c53e6dd8-3786-4490-8117-4e330394517c.png)

If you use SET instead of GRANT, it works (Set-CsTeamsEnhancedEncryptionPolicy -Identity Global -CallingEndtoEndEncryptionEnabledType Disabled)

![image](https://user-images.githubusercontent.com/103252032/162411968-e62ac6f5-8d26-4ef2-af14-b3f67564e315.png)

Let me know if additional info is needed.

Regards,
Catalin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56b532a-ab80-0e4c-dcd8-829a0a68c08e
* Version Independent ID: e56b532a-ab80-0e4c-dcd8-829a0a68c08e
* Content: [End-to-end encryption for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-end-to-end-encryption)
* Content Source: [Teams/teams-end-to-end-encryption.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-end-to-end-encryption.md)
* Service: **msteams**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
