### ISSUE TITLE
Default volume levels descriptions missing

### ISSUE THREAD

**Issue by mjtart** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8740]
The template has the elements for default volume levels,  <AudioRenderDefaultDeviceVolume> and <AudioRenderCommunicationDeviceVolume>,  but the lower description chart does not mention them. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25a70665-5bf1-14f7-1df0-7596effcaf48
* Version Independent ID: 813cf005-2777-9419-d1ce-3f9401ac267c
* Content: [Remotely manage Microsoft Teams Rooms device settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/xml-config-file)
* Content Source: [Teams/rooms/xml-config-file.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/xml-config-file.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
