### ISSUE TITLE
Manage org-wide app settings for Microsoft 365 Government (2)

### ISSUE THREAD

**Issue by ldickerson3** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8741]
The "Manage org-wide app settings for Microsoft 365 Government" section references GCC, GCCH and DoD environments multiple times as if these instructions work in all three but the note contradicts this by saying "In GCCH and DOD clouds, the third-party apps are not available.".

Microsoft support reps are using this article to say that we should be able to access third-party apps in GCCH.  The screen shots don't match and the settings are not there.  My belief is that GCCH and DOD should not be mentioned in this section, with the exception of the note.  

This can be further verified by reviewing https://docs.microsoft.com/en-us/office365/servicedescriptions/teams-service-description where the first feature, "Apps, Bots & Connectors", has a footnote for the Yes under GCC-High and DOD:

_1 Third-party applications and application publishing are not available in these clouds at this time._

The only apps that appear to be available in GCCH are the Microsoft published apps (first-party apps).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b51eda6c-168c-7d99-7cc1-992b3d8feef2
* Version Independent ID: 118a1b8f-f4b7-a778-70b1-d3161fc548ab
* Content: [Manage app permission policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-app-permission-policies#manage-org-wide-app-settings-for-microsoft-365-government)
* Content Source: [Teams/teams-app-permission-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-permission-policies.md)
* Service: **msteams**
* GitHub Login: @guptaashish
* Microsoft Alias: **guptaashish**

**Comment by get-itips** [comment]
Hello @ldickerson3 I am looking into this

**Comment by get-itips** [comment]
Hello @ldickerson3 I could get information that _org-wide app settings_ for GCC/H and DoD is under "Permission policies", I am now trying to confirm if that differs in GCC and if an update to the screenshot/instructions is needed.
Thank you

**Comment by tiburd** [comment]
We have received confirmation that the article will be updated soon.

**Comment by ashishguptaiitb** [comment]
Thanks folks. The updates are published live at https://docs.microsoft.com/en-us/MicrosoftTeams/teams-app-permission-policies#manage-org-wide-app-settings-for-microsoft-365-government . Hope it helps. We are happy to do more enhancements as required - please keep the feedback coming.
