### ISSUE TITLE
Updated to include correct working example

### ISSUE THREAD

**Issue by timr1972** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8749]
Having just used this link I found the information incorrect, although this may be user error!

Please consider including this example code snippet:

$UserObjectId = (Get-CsOnlineUser -Identity user01@contoso.com).Identity
New-CsTeamsUnassignedNumberTreatment -Identity VacantRoute -Pattern "^\+441473\d{6}$" -TargetType User -Target $UserObjectId -TreatmentPriority 1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed4beab-bb0d-fba4-814e-147d22fd97e5
* Version Independent ID: 8ed4beab-bb0d-fba4-814e-147d22fd97e5
* Content: [Routing calls to unassigned numbers - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/routing-calls-to-unassigned-numbers)
* Content Source: [Teams/routing-calls-to-unassigned-numbers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/routing-calls-to-unassigned-numbers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @timr1972 

The examples included in the article are to route to a _resource account_  or  _announcement service_, what do you see is incorrect on those?

The example that you share is very similar to this one https://docs.microsoft.com/en-us/powershell/module/teams/new-csteamsunassignednumbertreatment?view=teams-ps#example-3

Let me know if I understood you correctly

**Comment by get-itips** [comment]
Hello @timr1972 Tim, could you see my last comment? Thank you

**Comment by get-itips** [comment]
@scanum
