### ISSUE TITLE
Please provide examples on this page

### ISSUE THREAD

**Issue by GitRomney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8751]
The "Customize store" section of the Teams Admin Center provides places to upload, "Organization logo," "Organization logomark," "Background image," and "Text color of your organization name." Can you please show examples of each of these on this page? This is the only support page I can find on these features and there doesn't appear to be any example available.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfaea5f2-b19c-6170-8f7c-a20712358b46
* Version Independent ID: 974ed15e-e9a3-1559-1a5c-9636f09240b2
* Content: [Custom apps store - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/customize-your-app-store?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/customize-your-app-store.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/customize-your-app-store.md)
* Service: **msteams**
* GitHub Login: @guptaashish
* Microsoft Alias: **guptaashish**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
