### ISSUE TITLE
Missing Spam filtering and SIP devices explanations

### ISSUE THREAD

**Issue by DanScottExpo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8752]
Hi

This is missing the explanations for Spam filtering options and the SIP devices being used.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410fc30b-f530-8443-0602-9150c9cba115
* Version Independent ID: c5b33b25-147b-f7d4-056a-987088950e7c
* Content: [Calling policies in Microsoft Teams: Calling and call-forwarding features - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-calling-policy)
* Content Source: [Teams/teams-calling-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-calling-policy.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **tonysmit**

**Comment by JensTrier** [comment]
This has been fixed by above PR
