### ISSUE TITLE
Location of Shifts data UTL link is broken

### ISSUE THREAD

**Issue by Rangeball** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8758]
The URL link in this section isn't working. 

Location of Shifts data
Shifts data is currently stored in Azure in data centers in Asia Pacific (APAC), the European Union (EU), and North America. For more information about where data is stored, see [Where is my data](http://o365datacentermap.azurewebsites.net/)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58ea9573-59b1-1499-fb83-517d0ee0f034
* Version Independent ID: bf98f739-ff51-0b90-dbc5-c594d3dacecd
* Content: [Manage the Shifts app for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams)
* Content Source: [Teams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanachin**

**Comment by lindspea** [comment]
@Rangeball thank you for reaching out and helping to improve Microsoft Docs. Is this link helpful at all - it points to a few places for data storage. https://docs.microsoft.com/microsoft-365/enterprise/o365-data-locations?view=o365-worldwide
