### ISSUE TITLE
Clarity on Definitions - "Interpret the report" section, table in step 7

### ISSUE THREAD

**Issue by jebeckham** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8759]
In the section "Interpret the report" and the table in step 7.  Can we provide more clarity on:

"Channel messages is the number of unique messages that the user posted in a team channel during the specified time period."
"Reply messages is the number of unique reply messages that the user posted in a team channel during the specified time period."
"Post messages is the number of unique post messages that the user posted in a team channel during the specified time period."

Meaning, define what "Post messages" are vs. "Reply messages" and that the "Channel messages" is a sum of the two (or whatever it is because I'm working with a customer who provided some data and post+reply does not equal channel).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2758a3d6-c646-dcb0-2a31-c7b9b84e780b
* Version Independent ID: 8704c9fe-f8b0-82d2-bd83-3fd1a9ad638d
* Content: [Microsoft Teams user activity report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report)
* Content Source: [Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by jebeckham** [comment]
I see some other discussions in other feedback provided, though it seems that it would warrant further clarification.

**Comment by dariomws** [comment]
Hi @jebeckham, thank you for your feedback.

@quentinhurdazure, could you kindly help again with this question? I think we need to clarify what other messages can count for "channel messages". It's not always "post" + "reply" messages.

Thanks!

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
