### ISSUE TITLE
Screenshot out of date

### ISSUE THREAD

**Issue by rishire** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8768]
The screenshot for assigning/unassigning a service number is out of date.  https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts

![resource-account-assign-phone-number](https://user-images.githubusercontent.com/48099582/163845731-2d7f192a-ce77-49bd-b9b6-588859af628e.png)

**Comment by get-itips** [comment]
Hello @rishire Rick,

Please include the URL to the article you are opening the issue for.

Thank you!

**Comment by rishire** [comment]
Added the URL to the article in the original post.

**Comment by get-itips** [comment]
Thanks, working on updating the screenshot...
