### ISSUE TITLE
Channel email receiving limits

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8770]
Hello,

I recently opened [Case #:29973438] and learned there is an email delivery limit of 30/msg/min per sender/teams channel recipient address (sending limit for EXO)

> Teams uses EXO sending/receiving limit as described in the article Exchange Online limits - Service Descriptions | Microsoft Docs and should be considered by customer.
>
> https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#sending-limits-across-standalone-options

I propose adding this info to the following section
https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#emailing-a-channel

The limits were lower and the delivery failure generated is not intuitive, we opened the above ticket and the throttling policy changes went live in commercial cloud on 4/7

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#emailing-a-channel)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hello @jonwbstr how are you?

Unfortunately, we do not have access to the support cases, so let me ask you to clarify, the limit reported was 30 messages per minute? asking this because later in your post you say "The limits were lower"

Thanks for the clarification,

**Comment by jonwbstr** [comment]
Apologies for the confusion and bad formatting

Before 4/7 the limit was lower,
After 4/7 the limit is currently 30/msg/min

**Comment by get-itips** [comment]
Thanks @jonwbstr 

The article [Exchange Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits) is already being linked on that section so I am not sure, do you feel that is not clear enough the idea that Teams is affected by EXO sending limits?

Thank you!

**Comment by get-itips** [comment]
Hello @jonwbstr could you see my last comment here? Thank you

**Comment by jonwbstr** [comment]
Hello,

That note currently references the entire page, while I was proposing adding a reference to the specific section that talks about the limit of 30/msg/min.

As someone who incorporates teams into automated workflows, knowing the sending limit is pretty important. I opened a support ticket because messages failed with a 'weird' failure reason and spent a month tracking down this info because the page as written wasn't obvious to me, or any of the support engineers who went on that journey with me :).

Teams doesn't use the 'receive' limit which is different from the sending limit. So, yes I think it is important to specify which sending limit it uses and including that info directly on the page opposed to sending admins to another page and letting them guess which limit applies the sending or receiving limit.

You might even consider including the wired delivery failure and say that the error means you hit the throttling policy. Can't recall if I shared the delivery failure... Of if you're interested in that much detail.

Regards,
-jon

**Comment by get-itips** [comment]
@jonwbstr Could you see my last comment? Thanks

**Comment by jonwbstr** [comment]
I am unable to confirm that. We received an error sending 5 message. On all
5. Randomly every 3-6mo.

We opened a support ticket to track down the cause and the product group
said the throttling policy was adjusted to those settings to resolve the
issue.

I have not verified the information was correct.

I can send you the conversation and/or the participant email addresses if
you would like.

**Comment by get-itips** [comment]
Hello @jonwbstr but can you confirm the error was while sending **TO the channel's email address from an internal user**?

**Comment by jonwbstr** [comment]
Ah, Yes. I can confirm the NDR was for an internal user sending to a teams
channel email address

**Comment by jonwbstr** [comment]
Yay just got another delivery failure. Digging around I notice I never shared the delivery failure that happens when a message hits the throttling policy. 

Delivery failure when throttling policy is triggered:
```
Could not create the email message on Microsoft Teams: the channel's folder was deleted or renamed.
```

As you can probably guess, the channel and folder have not been deleted and resending the message worked just fine. Don't know why we hit the throttling policy again but it sure looks that way.

**Comment by get-itips** [comment]
@jonwbstr Thanks for sharing that

**Comment by get-itips** [comment]
article was updated
