### ISSUE TITLE
Windows PowerShell

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8774]
I think it is a bit odd to have a section on "Windows PowerShell" as I don't believe it is OS specific anymore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dc173c-0c98-1b94-a2f7-0a34781c985a
* Version Independent ID: a1c44ccb-67f3-f98e-6569-f938e88ddc63
* Content: [Set the phone numbers included on invites - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/set-the-phone-numbers-included-on-invites-in-teams)
* Content Source: [Teams/set-the-phone-numbers-included-on-invites-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-the-phone-numbers-included-on-invites-in-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hello @thommck Thom, how are you?

I've just checked with the product team to confirm if this is still true

>Microsoft Teams PowerShell module is currently supported for use with PowerShell 5.1 on Windows. 

And it is still true. Once the support for Core/7 is released, I'll propose the change to the articles.

Thank you,
