### ISSUE TITLE
Very, very poor translation

### ISSUE THREAD

**Issue by Clemens2000** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8778]
The german translation of this page makes no sense because "Loop" is translated literaly in either "endless" / "endlos" or "Schleife", which would sound similar like "ribbon".

Would be cool, if Loop could be used within a Teams Channel. Using it in a personal chat is much less useful.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 276b708d-786c-3981-7b22-2fdb5e96599a
* Version Independent ID: 276b708d-786c-3981-7b22-2fdb5e96599a
* Content: [Overview of Loop components in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/loop-components-in-teams)
* Content Source: [Teams/loop-components-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/loop-components-in-teams.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by cdowling1971** [comment]
@Clemens2000 Thanks for reporting this problem, I have logged an internal case/ticket, and we will continue to follow up internally to make this fix.
FYI @TinaMcN @scanum

**Comment by tiburd** [comment]
Closing this issue. Translation bug was scheduled with Global Services, who handles it from there.

cc: @scanum
