### ISSUE TITLE
incorrect information

### ISSUE THREAD

**Issue by itsbrad4669** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8780]
(https://docs.microsoft.com/en-us/microsoftteams/sip-gateway-plan#compatible-devices claims Trio 8800 is compatible with this service but is not

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44863905-42d1-cd3f-0d97-af2570649e89
* Version Independent ID: 44863905-42d1-cd3f-0d97-af2570649e89
* Content: [Plan SIP Gateway - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sip-gateway-plan#compatible-devices)
* Content Source: [Teams/sip-gateway-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sip-gateway-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @itsbrad4669 I am looking into this

**Comment by get-itips** [comment]
Hello @itsbrad4669 

I received confirmation that the device was tested against sip gateway and I managed to get this information for you from the team, specific to this model

>1. Restore to factory defaults
>2. Point the device to provisioning URL via DHCP options or manually (same flow as for all other devices)
>3. Add the MAC address in TAC (Teams Devices–>SIP Devices-->Action–> Provision Devices–> Waiting on Activation–> Add) 
>4. Select the MAC and click on Generate verification code (OTP) 
>5. There are two screens, first screens looks like below, to bring up the dial pad need to press Place a Call or Click to Dial on the bottom of the screen
>![image](https://user-images.githubusercontent.com/36666927/165366899-26222b7a-2555-4dc1-9ac2-609d1ad05ecd.png)

>6. After it press on handset icon near to “Click to Dial” text and dial [**55*OTP*] - the system will play confirmation tone 

>![image](https://user-images.githubusercontent.com/36666927/165366977-5035902c-9be8-43b9-8f88-44cef10c9b29.png)

>7. TAC: Waiting for sign in - select the MAC address and click on Sign in a user to obtain URL and Pairing Code
Open web browser and navigate to [https://www.microsoft.com/devicelogin](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fdevicelogin&data=05%7C01%7Cv-tibur%40microsoft.com%7C45d30419658a4bf266dc08da278a4e7b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637865772249012150%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=P%2FNzKDXp8Zjtwjzw1bDILH7GZi%2B%2BG4o%2BDGmYQ4AEn80%3D&reserved=0) --> enter the pairing code and complete Sign In with desired user account.


In case you still run into issues, please contact support, as here we are limited to documentation fixes.
