### ISSUE TITLE
Document meeting modalities that are not available for guest and anonymous users

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8782]
Meeting stage, sidepanel and task module is not available for guest and anonymous users in Meetings

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0735d322-f6f5-7cc8-9994-1420e3fb7baa
* Version Independent ID: f9b25b51-eb9c-63fa-b30e-e1490c8d31b6
* Content: [Teams apps behavior based on types of users - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/non-standard-users)
* Content Source: [Teams/non-standard-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/non-standard-users.md)
* Service: **msteams**
* GitHub Login: @guptaashish
* Microsoft Alias: **guptaashish**

**Comment by dariomws** [comment]
Hi @TheBluLion, thank you for your feedback.

@guptaashish, I cannot confirm this information. Could you help? Thanks!

**Comment by dariomws** [comment]
@TheBluLion, I see that you are an MS employee. Could you confirm where/how you think we should add this information? Thanks!
