### ISSUE TITLE
fAgentTimelineAnalytics CQD fields description and note have conflicting information - which is correct?

### ISSUE THREAD

**Issue by datafishnz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8783]
Hi team, 

As in the title, on this page the fAgentTimelineAnalytics CQD fields description and note have ambiguously worded or conflicting information on the definition of "Call Count" in this table. 

The **field description** says 
Call Count | Whole number | Summarize: SumNumber of calls _presented and answered by agent_

Yet the **note** (in purple) under it says 
Every call queue call presented to an agent is counted on this report, _even if it wasn't answered by the agent_. 

I am customising this report for my client, so I need to know what description of the call count is correct - ie does it include or exclude calls not answered by the agents. 

Thank you very much. 
Sophia

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 628345c6-f5f9-fe8e-bfff-faea00a8a25c
* Version Independent ID: 30f2d051-5af5-0063-7099-38b5b08ec1e4
* Content: [Auto Attendant & Call Queue Historical Report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/aa-cq-cqd-historical-reports)
* Content Source: [Teams/aa-cq-cqd-historical-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/aa-cq-cqd-historical-reports.md)
![Capture](https://user-images.githubusercontent.com/104106046/164332247-caca13cd-0f9b-4024-a66b-e4c43f27c257.PNG)

* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @datafishnz an update to the article is coming soon, thanks for your feedback!

**Comment by get-itips** [comment]
Article has been updated in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/34ea59feefe5c7ae082e754156d469f8f47a4e3d
Thanks
@scanum
