### ISSUE TITLE
Availability for GCCH customers

### ISSUE THREAD

**Issue by J227668** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8785]
This feature is not available to GCCH customers. Can you please confirm that on this page? Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f76bc0c-a899-b572-588a-b86acae1b740
* Version Independent ID: 3c5b6414-c796-7e50-9e03-b578c7995071
* Content: [Microsoft Teams Rooms managed service - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/microsoft-teams-rooms-premium)
* Content Source: [Teams/rooms/microsoft-teams-rooms-premium.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/microsoft-teams-rooms-premium.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by J227668** [comment]
Hi @get-itips - I do not see a call out for commercial, GCC, GCCH, or DoD within the URL you shared.

**Comment by get-itips** [comment]
> Hi @get-itips - I do not see a call out for commercial, GCC, GCCH, or DoD within the URL you shared.

Hello @J227668 here it is what I was talking about

> Microsoft Teams Rooms is not supported in Microsoft 365 or Office 365 operated by 21Vianet, or DoD environments.

**Comment by J227668** [comment]
Thank you for calling that out. Meeting Teams Rooms ARE available in GCC and GCCH. Is that correct? 
If yes, is Teams Rooms Managed Service/Premium available to GCCH customers. I believe it is not available to GCCH customers. Can we update this page https://docs.microsoft.com/en-us/microsoftteams/rooms/microsoft-teams-rooms-premium to specify that the managed service is NOT available to GCCH customers, assuming that is correct? Thank you.

**Comment by dstrome** [comment]
MTR Premium has been absorbed into Teams Rooms Pro, which is available in GCC and GCCH - https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing. Note that the Microsoft-managed portion of the service will be deprecated Oct 1st 2022. I'm closing the PR as the distinction is no longer needed and availability is called out in the link I pasted above.
