### ISSUE TITLE
I couldn't make Microsoft Teams Connect shared channels on Teams admin center.

### ISSUE THREAD

**Issue by dshimogawa** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8786]
[Enter feedback here]
Hi, Team.

I couldn't make Microsoft Teams Connect shared channels on Teams admin center, but I could make shared channels on Microsoft Teams client. Is it correct specification?

Best regards,
Daishi Shimogawa.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e6deaf-68f5-e3c9-7259-775ed7662d85
* Version Independent ID: 82e6deaf-68f5-e3c9-7259-775ed7662d85
* Content: [Shared channels in Microsoft Teams (Preview) - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/shared-channels)
* Content Source: [Teams/shared-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/shared-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
