### ISSUE TITLE
Caller ID - CRM

### ISSUE THREAD

**Issue by BakkerJan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8787]
"Calls from inside the company display a detailed caller ID that pulls information from the corporate directory, showing picture ID and job title instead of just a phone number. For calls from external phone numbers, the caller ID as provided by the phone service provider is displayed. If the external phone numbers are secondary numbers in the corporate directory, then the information from the corporate directory will be displayed."

If I have CRM Dynamics, will this data be used as a corporate directory? In other words: where do I need to populate this information for external contacts? B2C, B2B, member, external contact, GAL?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
