### ISSUE TITLE
 For supported audio formats and maximum file size, please see Import-CsOnlineAudioFile

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8790]
As per article it redirects for file size to another article 
" For supported audio formats and maximum file size, please see Import-CsOnlineAudioFile"

However , there is no limit details given. Please provide the file size limit details and format.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 416f3cdb-ca75-8224-bc04-985e5f7ea9dd
* Version Independent ID: 6e8c6f33-8043-e367-b44b-74b5f5ee96f2
* Content: [Music on Hold - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/music-on-hold)
* Content Source: [Teams/music-on-hold.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/music-on-hold.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by JensTrier** [comment]
@robinpoulose1 Thanks for the feedback. The supported formats and file size limit are listed in the Import-CsOnlineAudioFile page under the -Content parameter description.
