### ISSUE TITLE
Safe Links Do not rewrite list suggestions are insecure

### ISSUE THREAD

**Issue by blakebourgeois** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8793]
The safe links dot not rewrite entries are insecure and do not follow the suggested syntax here: https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links?view=o365-worldwide#do-not-rewrite-the-following-urls-lists-in-safe-links-policies

Instead of "*.webex.com*" the do not rewrite entry should be "*.webex.com/*"
Likewise, the zoom entries should be as follows:
*.zoom.us/*
*.zoom.com/*
*.zoomgov.com/*

For example, as written, the following malicious example would not be rewritten under policy and could open users to phishing/safelinks protection bypass: malicious[.]webex[.]com[.]baddomain[.]tld

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c62081e-2421-80b9-8ba9-aaf8fd55e432
* Version Independent ID: 5df3c5e5-978f-cfa7-9e5c-3cd7f65fa8ff
* Content: [Enable Teams Rooms devices to join third-party meetings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/third-party-join)
* Content Source: [Teams/rooms/third-party-join.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/third-party-join.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by dariomws** [comment]
Hi @blakebourgeois, thank you for your feedback.

The example entries were updated on May 12th. That's what you are suggesting if I'm not wrong. Anyway, please have in mind that the article includes the following sentence:

"For a complete list of URLs to add to your Defender for Office 365 Safe Links Do not rewrite list or third-party URL rewrite exception list, contact the third-party meeting service provider you want to accept meeting invites from."
