### ISSUE TITLE
Filters do not work

### ISSUE THREAD

**Issue by hharris75** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8794]
The filters used in step 7 and 9 do not work. I have tried the current version of the Teams module and version 2.6.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5566de7d-1d1e-ba92-743b-dc772b49752a
* Version Independent ID: c15342ff-eb3a-5f14-4bba-217c31aa1299
* Content: [Decide how to manage attributes after decommissioning - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/cloud-consolidation-managing-attributes)
* Content Source: [Skype/SfbHybrid/hybrid/cloud-consolidation-managing-attributes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/cloud-consolidation-managing-attributes.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by hharris75** [comment]
Appears the issue is with UserValidationErrors. The filter works without that property.

**Comment by hharris75** [comment]
Without the UserValidationErrors it only works in version 2.6.0
Also step 11 only works in 2.6.0

**Comment by get-itips** [comment]
Hello @hharris75 I am looking into this

**Comment by get-itips** [comment]
UserValidationErrors can't be used in filters anymore and ProvisioningStamp is not present anymore so I'll look for the current example, thanks for  your feedback

**Comment by isrumnon** [comment]
Hi all, UserValidationErrors and ProvisioningStamp are currently not supported as filters at present

**Comment by get-itips** [comment]
Hello @hharris75 I can add that, _isSipEnabled_ was recently re-enabled as Filter in 4.3.0 so the cmdlet in step 7 should work.

**Comment by get-itips** [comment]
Hello @hharris75 checking back to understand if you could read our comments, thank you
