### ISSUE TITLE
Updates needed to enablement steps

### ISSUE THREAD

**Issue by CCDanC** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8795]
The section "Use the Teams admin center to configure end-to-end encryption" needs to be updated to include the current steps for enabling E2E encryption. "Enhanced encryption policies" is no longer listed under "Other Settings", and the relevant "End-to-end call encryption" option is now "Disabled User Override"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56b532a-ab80-0e4c-dcd8-829a0a68c08e
* Version Independent ID: e56b532a-ab80-0e4c-dcd8-829a0a68c08e
* Content: [End-to-end encryption for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-end-to-end-encryption)
* Content Source: [Teams/teams-end-to-end-encryption.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-end-to-end-encryption.md)
* Service: **msteams**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by get-itips** [comment]
Hello, thanks for your feedback @CCDanC
