### ISSUE TITLE
Missing information on Direct routing Call Type

### ISSUE THREAD

**Issue by TheITguy666** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8798]
I see more call types (related to Call Queues and Autoattendants) on my reports for Direct Routing, probably a rename?

- dr_out_bot = dr_out_ucap (?)
- dr_in_bot = dr_in_ucap (?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ad0c889-56d5-35fe-de15-177b6d922d07
* Version Independent ID: e4363647-33e1-b665-5881-169fb619a5b3
* Content: [Microsoft Teams PSTN usage report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/pstn-usage-report)
* Content Source: [Teams/teams-analytics-and-reports/pstn-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/pstn-usage-report.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @TheITguy666 Luis, I am looking into this
