### ISSUE TITLE
The Number Shown after applied translation rule is incorrect.

### ISSUE THREAD

**Issue by nitingeu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8807]
This example creates a rule that adds +1 to any ten digits number. For example, 2065555555 will be translated to +1206555555
In this example the translated number has one digit sort. There should be 6 5s but only 5 5s are there. Please correct me if i am wrong.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6981866f-a685-d802-d64f-98685a5c658d
* Version Independent ID: a1f83744-abb7-4c33-6f60-19ff2732871c
* Content: [Translate phone numbers for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-translate-numbers)
* Content Source: [Teams/direct-routing-translate-numbers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-translate-numbers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @nitingeu, thank you for your feedback.

Could you let me know what example? 1, 2, 3 or 4? I cannot find the problem.
