### ISSUE TITLE
Force Blur Background

### ISSUE THREAD

**Issue by giles-day** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8813]
Can you add force blur background/force image background
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5d3a28c-7a66-831f-e610-9bf7d4edf9eb
* Version Independent ID: 0bc4a251-816e-0d77-efb2-53b7ffccb0f5
* Content: [Manage meeting policies for audio and video - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-audio-and-video)
* Content Source: [Teams/meeting-policies-audio-and-video.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-audio-and-video.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
I know the product teams are always looking for user feedback and how to make SharePoint better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice 

Skype for Business: https://www.skypefeedback.com/.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.
Thank you for your contribution to make the docs better! Much appreciated!
