### ISSUE TITLE
Can this page be updated please?

### ISSUE THREAD

**Issue by Jon-Horner** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8814]
I don't believe was are allowing Microsoft Teams GCC audio/video servers to leverage processing capacity in our commercial datacenters, as well as in our government datacenters any longer... if this is the case, can we please update this page? currently customers are thinking this make Teams no longer compliant.

Thanks,

Jon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7faee29-6d56-f3bf-766c-6deaefe92e34
* Version Independent ID: 6029b6f8-7d49-6474-fa40-2793000c74a4
* Content: [Microsoft 365 Government - GCC deployments - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/plan-for-government-gcc)
* Content Source: [Teams/plan-for-government-gcc.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-for-government-gcc.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hello @Jon-Horner I am looking into this

**Comment by get-itips** [comment]
Hello @Jon-Horner I've been notified that an update to the note is coming soon
