### ISSUE TITLE
IVR to redirect to a "Person in the organization" and enterprise voice

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8817]
A few pieces of feedback here,
1) the article says "Auto attendants can direct calls, based on callers' input, to one of the following destinations:" but the only reference for many of these options in the entire article is just the reference in this section. Not helpful. It can be done but we aren't going to tell you how, you have to sort of figure that part out.

    Operator - 13 results
    Person in the organization - 1 result
    Voice app - 1 result
    Voicemail - 3 results
    External phone number - 2 results
    Announcement (Audio file) - 1 result
    Announcement (Typed) - 1 result

2) I want an auto attendant to direct calls to a person in the organization, how do I see the instructions for doing that? read the whole article and look for something that doesn't contain the words "person in the organization" that looks like it might be applicable is about the best option I see. (yes I know it's the right answer, but not because the article told me!)

    the ["redirect to bullet of the menu options section"](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-auto-attendant#menu-options
) section looks promising. The screenshot only shows two redirect to options, and the list at the top doesn't explicitly say those are the available "redirect to" options. Consider making this relationship more clear by either using the "redirect to" language, or a link to the section the list is referring to.

3) redirecting to a person in the organization is generating an error that enterprise voice is not enabled. How does one enable enterprise voice? that would be worth covering in the section that talks about redirecting to 'person in the organization' similar to how you discuss redirecting to a resource. 
   * I asked how does one enable enterprise voice. the answer to this question is not obvious. more google searching suggests the only way to enable enterprise voice is to use powershell. Okay, but yuck.
   * This article says to assign a phone number to automatically enable enterprise voice, and then provides a powershell command. Assigning a phone number can also be done without powershell. But can enterprise voice be enabled without assigning a phone number, without powershell? hmmmm
      > "If you are managing the user's phone number online, you need to assign the phone number to the user by using the following command in Teams PowerShell. The user is automatically Enterprise Voice enabled by the command"
https://docs.microsoft.com/en-us/microsoftteams/direct-routing-enable-users#configure-the-phone-number-and-enable-enterprise-voice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a42f9e2c-aeee-76c4-620a-668cce21ba10
* Version Independent ID: 6ff06eab-9c80-9c30-95ef-c17e157fbea1
* Content: [Set up an auto attendant for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-auto-attendant)
* Content Source: [Teams/create-a-phone-system-auto-attendant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-auto-attendant.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CLYVR** [comment]
Hi @jonwbstr, thanks for your feedback - we will look to make the instructions more clear/informative on how to do this.

To immediately address redirecting to a person in the organization - there are two ways to do this:

- Dial by name/number options - users reached this way do **NOT** need to be EV enabled

> This option can be enabled under the Call flow -> Call routing options portion of the Auto Attendant.  Select Play menu options, provide some instructions (no need to have an actual menu) and then select the "Dial by name" or "Dial by number" options.

- Via an auto attendant menu option - users reached this way **must** be EV enabled.

**Comment by jonwbstr** [comment]
Let me try a different approach

Please change the line 'Auto attendants can direct calls, based on callers' input, to one of the following destinations:"  to read
> Auto attendants can **redirect calls**, based on callers' input, to one of the following destinations:

Include the bold formatting because "redirect calls" is a phrase that can be found in the instructions below where it is also bold. Also consider updating "If you select **Redirect call**, you can choose one of the call routing destinations." to read
> "If you select **Redirect call**, you can choose one of the call routing destinations described earlier in the article."

**Comment by jonwbstr** [comment]
I just noticed the section I referenced didn't exist when this was initially created. That [commit](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/177462b6fac1907eba7b88f8f534ea014d7d1833) was an excellent step in the right direction. Building the relationship mentioned in the previous comment would tie it all together nicely IMHO.

**Comment by jonwbstr** [comment]
3. Actually, it should be a person with a Phone License assigned if I'm not wrong. Let me double-check it.

Assigning a phone license to a user should enable enterprise voice? That would be cool if true!

**Comment by DaniEASmith** [comment]
@CLYVR Just bubbling this back on your radar. Any recommendations for how to update the auto attendant doc per this request?

**Comment by CLYVR** [comment]
@DaniEASmith Have tried to address with: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/pull/10030

**Comment by DaniEASmith** [comment]
@CLYVR Thank you, Colin! I've reviewed the PR and have signed off on it to be published today.
