### ISSUE TITLE
Errors in SRSDeploymentKit-4.12.126.0 - Windows 10 Version information incorrect

### ISSUE THREAD

**Issue by andyman198** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8820]
SRSDeploymentKit-4.12.126.0 has the following issues

1) the media askes to use an iso that is for 2022 but the file name says 2020 and the file is not in the VLSC with that name

The correct media for this release has the following characteristics:

     Major release: 21H2
     Name in VLSC: Windows 10, Version 21H2 (released Nov 2020) 64-bit English
     Size (bytes): 5750394880
     SHA256: 1323FD1EF0CBFD4BF23FA56A6538FF69DD410AD49969983FEE3DF936A6C811C5

   You must supply an ISO that matches the exact characteristics above to proceed.

2) when setting up without drivers, the setup gets stuck asking you to remove the teams room device from the dock - which cannot be done if it is not a docked device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1365f9b8-001c-daa7-592e-d88b9bb3a10e
* Version Independent ID: ffba1b4d-1f19-4dac-0b55-053d98fe26b7
* Content: [Release notes for Microsoft Teams Rooms (Windows) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-release-note)
* Content Source: [Teams/rooms/rooms-release-note.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-release-note.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by andyman198** [comment]
For those needing to find the correct version, I have found that the CRC matches the windows version in the VLSC service center that has the following details:

Windows 10, version 21H2 (released Nov 2021) 64-bit English | 64 bit | 5484 MB | ISO
1323FD1EF0CBFD4BF23FA56A6538FF69DD410AD49969983FEE3DF936A6C811C5

**Comment by get-itips** [comment]
Hello @andyman198 Andy, how are you?
Here, we are limited to documentation fixes and improvements.

For what you report here, I'll try to pass this on, surely will help if anyone looks for the same information.
Thank you
