### ISSUE TITLE
Get-CsTenant no longer returns Identity property

### ISSUE THREAD

**Issue by JeffBrownTech** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8822]
When running the command:

`Get-CsTenant | ft identity`

From the "Important" section under "[Required administrative credentials](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/move-users-between-on-premises-and-cloud#required-administrative-credentials)", the command no longer returns the Identity property. This renders the remaining instructions unusable as you cannot find the necessary letters to complete the migration URL.

I am running this command using MicrosoftTeams v4.0.0 PowerShell module.

The closest I can find is looking at the "ServiceInstance" property. For example, my tenant has "MicrosoftCommunicationsOnline/NOAM-4A-S7" as the value. From my experience, the "4A" looks pretty close to what I'm looking for to complete the URL. Is this accurate?

Request to determine if this value can be found anywhere else. If so, update documentation or remove as it is no longer technically accurate.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9144d9e4-1894-e4a3-212b-7e765a8d6079
* Version Independent ID: bb9c62be-58b3-31d5-4933-fe1b0374351a
* Content: [Move users between on-premises and cloud - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/move-users-between-on-premises-and-cloud)
* Content Source: [Skype/SfbHybrid/hybrid/move-users-between-on-premises-and-cloud.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/move-users-between-on-premises-and-cloud.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by JensTrier** [comment]
Thus has been fixed by above PR

**Comment by JeffBrownTech** [comment]
Just clarifying, was my method confirmed to be accurate?

**Comment by JensTrier** [comment]
Yes, thanks. ServiceInstance should be used.

Feel free to close this issue

**Comment by CarolynRowe** [comment]
Closing this issue.
