### ISSUE TITLE
Supported Windows versions for Teams Rooms out-of-date

### ISSUE THREAD

**Issue by ralish** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8823]
The latest Teams Rooms media creation script (`CreateSrsMedia.ps1` v1.7.0) requests the following Windows ISO:

```
Major release: 21H2
Name in VLSC: Windows 10, Version 21H2 (released Nov 2020) 64-bit English
Size (bytes): 5750394880
SHA256: 1323FD1EF0CBFD4BF23FA56A6538FF69DD410AD49969983FEE3DF936A6C811C5
```

However, the page lists Windows 10 v21H1 as _Not Supported_ while Windows 10 v21H2 is not listed at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ecd6ee6-8850-f346-5684-9c5d2444789f
* Version Independent ID: a55a7a01-211d-147a-5332-b68e1051a2a1
* Content: [Microsoft Teams Rooms app version support - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-lifecycle-support)
* Content Source: [Teams/rooms/rooms-lifecycle-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-lifecycle-support.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by get-itips** [comment]
Hello @ralish Samuel,

I could confirm that 21H2 is now added to the article, and 21H1 stays the same (what was the script checking in reality was the version of Windows used to run the script).

Thank you for your feedback!
