### ISSUE TITLE
Please let me disable "on hold" music for 1:1 calls

### ISSUE THREAD

**Issue by SamEmam** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8825]
I was surprised when my pc suddenly started playing music, I noticed that my colleague had put me on hold.
So naturally I started digging in settings, trying frantically to disable the music without muting Teams entirely.
This is the only documentation I can find on this issue, and from what I can tell, it is only the admin who can disable the on hold music.

Please please please give me the option to disable the on hold music for 1:1 Teams calls, it is driving me crazy!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 416f3cdb-ca75-8224-bc04-985e5f7ea9dd
* Version Independent ID: 6e8c6f33-8043-e367-b44b-74b5f5ee96f2
* Content: [Music on Hold - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/music-on-hold)
* Content Source: [Teams/music-on-hold.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/music-on-hold.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
I know the product teams are always looking for user feedback and how to make SharePoint better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice 
Skype for Business: https://www.skypefeedback.com/.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.
Thank you for your contribution to make the docs better! Much appreciated!
