### ISSUE TITLE
outdated?

### ISSUE THREAD

**Issue by marekrevak** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8828]
Is this page really up to date? according to my info some of the firmwares are not supported or MS requires to upgrade.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaaef9e1-8f1c-ebf0-7856-4c007342a2c3
* Version Independent ID: 3eaf671f-375e-8787-9c66-3947c3606559
* Content: [Devices for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/teams-ip-phones#certified-teams-phones)
* Content Source: [Teams/devices/teams-ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/teams-ip-phones.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by dariomws** [comment]
Hi @marekrevak, thank you for your feedback.

Several updates were applied to this article since you opened this issue. Do you still think it needs more updates?
