### ISSUE TITLE
Default retention period is incorrect

### ISSUE THREAD

**Issue by starwispy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8830]
This help article states that the default expiration set in each tenant is 120 days, however the default set in our tenant is for 60 days. Presumably this is the case across all tenants. Please update the documentation to reflect the actual default period. Thank you.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee6d4c1c-6f16-b1a4-c4a9-be4e6d1f95b7
* Version Independent ID: 50ad835d-ed7f-18c6-34ba-322c1574f9c2
* Content: [Meeting policies and meeting expiration in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-au/MicrosoftTeams/meeting-expiration)
* Content Source: [Teams/meeting-expiration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-expiration.md)
* Service: **msteams**
* GitHub Login: @KarliStites
* Microsoft Alias: **kastites**

**Comment by get-itips** [comment]
Hello @starwispy 
How are you?
I checked in several tenants and 120 is the default
Thanks
