### ISSUE TITLE
Include a reference about how to add the derived trunk on the customer tenant and update the references to VRP

### ISSUE THREAD

**Issue by jagonzal01** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8834]
Hi, I've checked this article several times and discussed it internally with some colleagues and we find it a little bit confusing. It is indicated several times that the derived trunk must be added to the customer's tenant on the Voice Routing Policies, but there is no example on how to do it. First of all I think the reference to the VRPs is confusing as the VRPs only contain PSTN Usages, not SBCs, in my personal opinion all VRP mentions should be replaced by Voice Routes, as it is here where you introduce the SBC FQDN. Aslo it would be good to include in the examples section the command to do that;
New-CsOnlineVoiceRoute -Identity < RouteName > -NumberPattern < Pattern > -OnlinePstnGatewayList < SBC FQDN > -Priority < Priority > -OnlinePstnUsages < PSTN Usage Name >
New-CsOnlineVoiceRoute -Identity Route1 -NumberPattern .* -OnlinePstnGatewayList Sbc1.customers.adatum.biz -Priority 1 -OnlinePstnUsages TeamsVoice

Best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure Session Border Controller - Multiple tenants - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-sbc-multiple-tenants#create-a-trunk-and-provision-users)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Thanks for your feedback!

**Comment by jagonzal01** [comment]
Sorry @get-itips , @CarolynRowe , I completely missed your answers. You said that this has been completed in #8892 but checking the article I still see references to VRPs that are wrong:
_Sbc1.customers.adatum.biz – the derived trunk in a customer tenant. You can add the name of the derived trunk in the customer tenant in the **online voice routing policy** without creating it._ --> The derived trunk must be created in a Voice Route, not into the Voice Routing Policy

Also, I don't see any example about how to create the derived trunk on the customer tenant, this point is really confusing for everyone, so I really encourage you to include the PowerShell command as an example (check my original post).

Best regards

**Comment by get-itips** [comment]
Thanks @jagonzal01 that other sentence slipped into the cracks of the edit, will fix.

I'll dig into adding an example.
