### ISSUE TITLE
The very first 2 Crestron consoles in the list are discontinued by the vendor. There may be more?

### ISSUE THREAD

**Issue by luisfocosta** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8835]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf01435-a73b-4bf2-5845-e4cf50c4c3a2
* Version Independent ID: 166e1800-80b1-2496-7160-3040c5b23c3d
* Content: [Microsoft Teams Rooms requirements - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/requirements)
* Content Source: [Teams/rooms/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/requirements.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by dariomws** [comment]
Hi @luisfocosta, thank you for your feedback.

Yes, there are more devices on the table that are discontinued.

From the article, just before the table:
"All current Microsoft Teams Room devices and bundles are available in the [Room Systems product showcase](https://products.office.com/microsoft-teams/across-devices/devices/category?devicetype=20&page=1&filterIds=)."
