### ISSUE TITLE
Module 4.3.0 for MS Teams - Error: "InvalidAuthenticodeSignature"

### ISSUE THREAD

**Issue by WhiteZorin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8838]
Hi,

The newest package for Microsoft Teams module (4.3.0) seems to be having problems with Autheticode Signature and cannot be installed.
Error: "InvalidAuthenticodeSignature"

Installing via -requiredVersion 4.2.0 works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 173b5929-529b-938b-b6ab-59f05a5d69a8
* Version Independent ID: 0a3dfe5e-938f-933d-637e-b7449e3b8aa5
* Content: [Microsoft Teams PowerShell Release Notes - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-release-notes)
* Content Source: [Teams/teams-powershell-release-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-release-notes.md)
* Service: **msteams**
* GitHub Login: @sumitb18
* Microsoft Alias: **subadjat**

**Comment by get-itips** [comment]
Hello @WhiteZorin Bart, how are you?
Here we are limited to documentation fixes, despite that, i was able to install 4.3.0 without errors.
Thank you,

**Comment by WhiteZorin** [comment]
Hello @get-itips 
Thank you for your fast response! I have tested and the installation goes smoothly right now (sb updated AuthenticodeSignature :))

for the future: where could I send such feedback about this kind of problem? I looked around and this was the most simple / corresponding place to write to MSFT :)

Kind regards,
WZ

**Comment by get-itips** [comment]
@WhiteZorin Bart, thanks for returning and sharing your feedback.

You can write that kind of feedback [here](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)
