### ISSUE TITLE
Es posible hacer jerarquías de equipos?

### ISSUE THREAD

**Issue by chavesrdj** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#884]
A veces hay equipos grandes que se subdividen a su vez en otros más pequeños, es posible modelar esto en teams?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 06059d07-6687-2924-7d0a-3c03220a1650
* Version Independent ID: bb293f92-9394-b156-2e08-0baead5c3bbe
* Content: [Información general de los equipos y canales en Microsoft Teams](https://docs.microsoft.com/es-es/microsoftteams/teams-channels-overview)
* Content Source: [Teams/teams-channels-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.es-ES/blob/live-sxs/Teams/teams-channels-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@chavesrdj Thank you for this feedback

I am not sure if we can equip hierarchies or not in Teams. Let me get this on over to the Teams/Skype for Business team so we can get this investigated and get some answers for you. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by chavesrdj** [comment]
I'm very grateful. I Will be awating future answers.

Danilo

**Comment by get-itips** [comment]
Hi @chavesrdj thanks for your feedback!
It's not possible to have a subTeam, maybe the channel feature fills the situation you are describing and it works for you?
If not, please kindly visit Teams UserVoice to propose that idea https://microsoftteams.uservoice.com/

Thank you!
