### ISSUE TITLE
Missing Deployment guide for Android based MTR systems

### ISSUE THREAD

**Issue by Seilmeister** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8846]
Hi =)
Upon studying the deployment guide for Teams Room Systems based on Android, I struggle to find a configuration guide which Microsoft Endpoint Manager policies, profiles and such are recommended.

Our enterprise is about to deploy multiple Android based MTR systems and our engineering department is using Trial&Error to find the best setup.

E.g. shall we use Android Enterprise or still work with Android device administrator?

Best regards,
Emanuel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df34eea9-3e9e-acbf-3dde-ecf8e66956d1
* Version Independent ID: bab87875-e7a1-f109-f9cb-4dbe940908f3
* Content: [Deploy Microsoft Teams Rooms on Android - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/collab-bar-deploy?msclkid=347c84c1d02a11ecaa9dceb4de2f65d7)
* Content Source: [Teams/devices/collab-bar-deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/collab-bar-deploy.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by get-itips** [comment]
Hello @Seilmeister how are you?

I think this is what you are looking for https://docs.microsoft.com/en-us/microsoftteams/devices/phones-displays-deploy

let me know if it helps

Thanks

**Comment by get-itips** [comment]
Hello @Seilmeister Emanuel, could you see my last comment here? thank you
