### ISSUE TITLE
Set-TeamTargetingHierarchy is a missing cmdlet.

### ISSUE THREAD

**Issue by Fath3ad** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8847]
This web page provides instructions to create a Teams Hierarchy. 
The only option provided is to use Powershell. The latest version of the MicrosoftTeams module in Powershell 5.2 and Powershell 7 DO NOT have the required cmdlet: Set-TeamTargetingHierarchy, nor does Azure Cloud Shell.
This page needs to say that the documentation is there but the supporting modules are not.
If there is any way to create a Teams Hierarchy then please let me know.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c03584a-ee6c-2594-1601-07dc2ae32371
* Version Independent ID: f8dc6040-5495-ef0b-bb78-0b3b1a7a14bd
* Content: [Set up your team targeting hierarchy - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-your-team-hierarchy)
* Content Source: [Teams/set-up-your-team-hierarchy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-your-team-hierarchy.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @Fath3ad, thank you for your feedback.

You need to use the public preview version of the module to run these cmdlets. From the article:

> [!NOTE] 
> To perform this step, you must install and use the Teams PowerShell public preview module from the PowerShell Gallery. For steps on how to install the module, see [Install Teams PowerShell](https://docs.microsoft.com/microsoftteams/teams-powershell-install).

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
