### ISSUE TITLE
How many Holidays can be added to a Holiday Set?

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8850]
Hello,

this document states that 20 Holidays are able to be used in a Holiday Set, yet the Admin Center does only allow to add 10 (I think I remember this to be 20 in the beginning as well and cannot find any documentation as to why this was limited to 10...).

Has the number changed, should this read 10 now? Are we advised to create a second HolidaySet/Schedule Object for the next 10 Holidays? Comparing national holidays, we find between 5 and 17 worldwide for a given year, so having at least 15 or 20 would be a good equilibrium for usability.

I am asking as I am preparing documentation that queries Holiday sets for setup with PowerShell (we create one Holiday Set per country and year). With the TPM, there does not seem to be a limit of 10 currently in place, though the additional holidays are not visible in the Admin center... with may lead to confusion...

May I ask to get confirmation on what the desired maximum number is and that it is harmonised across the board please?

Thank you,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a42f9e2c-aeee-76c4-620a-668cce21ba10
* Version Independent ID: 6ff06eab-9c80-9c30-95ef-c17e157fbea1
* Content: [Set up an auto attendant for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/create-a-phone-system-auto-attendant?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/create-a-phone-system-auto-attendant.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-auto-attendant.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by isrumnon** [comment]
Hi @DEberhardt I'm not sure about this as I don't own this feature. @pbafna03 any idea about this?

**Comment by dariomws** [comment]
Hi @DaniEASmith,

Could you help here? Thanks!

**Comment by DaniEASmith** [comment]
Hi, Dario!

I'm trying to get ahold of the right point of contact, someone who has the answer.

I'm hoping for a resolution soon!


Dani Smith
she/her
Technical Writer 2
E+D MARVEL
***@***.******@***.***>

[Microsoft Logo]



________________________________

**Comment by CLYVR** [comment]
@DaniEASmith @dariomws 10 dates within a holiday (not specifically called out in the docs), up to 20 holidays attached to an AA (called out in the docs).
We are currently working to expand the number of dates within a holiday - that shoud launch this year.

**Comment by scanum** [comment]
Hi @CLYVR Hope all is well. Wanted to check in to see if there is an update here? Thanks.

**Comment by scanum** [comment]
Hi @CLYVR Hope all is well. Wanted to check in to see if there is an update here? Thanks.

**Comment by CLYVR** [comment]
@scanum sorry for delay - I was having testing problems and then went on vacation for a day.  It's 20 holiday sets, each holiday set can contain 10 dates - the documentation isn't clear so I will submit an update today.

**Comment by CLYVR** [comment]
@scanum PR10798 submitted and I've tagged DaniEASmith to review and merge - thanks!
