### ISSUE TITLE
Maximum number of contacts that can be blocked on Teams is 300

### ISSUE THREAD

**Issue by nagarjunreddy43** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8852]
The maximum limit is up to 300 limits. However, size of the contact matters, so sometime if limit reaches at 275, it might possible contacts will not get store. Reference support case 30359544

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams?msclkid=f3478ff6d05a11ec98cd41420fb80153)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hello @nagarjunreddy43 Thanks for your feedback, unfortunately, we do not have access to support cases, but I'll dig into this.

**Comment by get-itips** [comment]
Hello @nagarjunreddy43 can you confirm if you are using Teams Personal or small business? Thanks

**Comment by nagarjunreddy43** [comment]
Hi Andres,

No, we are 120,000 users tenant.

Regards,
Naga

**Comment by get-itips** [comment]
Hello @nagarjunreddy43 ok, thanks for providing more information, can you please clarify this to me

You are talking about this blocking feature?

_From the Chat tab, hover your mouse over the person you want to block.
Select More options .
Select Block._

source https://support.microsoft.com/en-us/office/block-a-contact-in-teams-for-personal-and-small-business-use-025e381e-8bff-4370-9a7f-c7ed7ebdcca7

Thanks for clarifying to me

**Comment by nagarjunreddy43** [comment]
Hi Andres,

That's right, we are blocking spam calls here instead of Teams users in our use case.

Regards,
Naga

**Comment by get-itips** [comment]
@nagarjunreddy43 Got it, one more thing, are we talking of numbers blocked at tenant (from PowerShell) or user level (from teams)? Thanks

**Comment by nagarjunreddy43** [comment]
Hi Andres,

This is on user level from Teams client as we don't block at tenant level.

Regards,
Naga
