### ISSUE TITLE
Question about (excluding ATA device users)

### ISSUE THREAD

**Issue by southwick7320** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8854]
Question regarding steps 5 & 6 both of which list "excluding ATA device users". 
The article, from my understanding, is specifically about connecting an Analog Telephony Adapter (ATA) to Teams Direct Route.  Why is the article excluding the type of user/account intended to be used?  Is "ATA device user" a special class/license of user to be used with the ATA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea0bc170-d9d9-c17a-adc8-d37cb5fe3df5
* Version Independent ID: 3c761043-bea5-0cfb-d85e-13671ed0fe9a
* Content: [Direct Routing - Connecting analog devices - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-analog-devices)
* Content Source: [Teams/direct-routing-analog-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-analog-devices.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
