### ISSUE TITLE
MSI Installer no longer adds desktop shortcut

### ISSUE THREAD

**Issue by JasonNVSD** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8855]
The document states, "a shortcut to start Teams is added to the user's desktop."  This was previously true, but is no longer true with the recent versions of the installer.  It's not clear whether this change is a bug or a feature.  Ideally, there should be a parameter for this.

Several organizations have reported this change starting in December 2021: https://docs.microsoft.com/en-us/answers/questions/678107/no-desktop-shortcut-teams-msi.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Bulk install Teams using Windows Installer (MSI) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment#feedback)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @JasonNVSD 
I could reproduce and I'll try to inform about this and see if an update to the article is necessary as here we are limited to documentation fixes.
Thank you!

**Comment by JasonNVSD** [comment]
Thanks @get-itips.  Can you tell me how to get the change/bug to the attention of the MSI Installer developers?  When I tried enterprise support, I was sent to our 365 partner that doesn't even touch Teams.

**Comment by get-itips** [comment]
Hello @JasonNVSD 
I could get information that this is now intended, updating the article.
