### ISSUE TITLE
Custom emergency disclaimer guidance

### ISSUE THREAD

**Issue by 3017mark** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8856]
The "guidance" describes the desired behavior but provides no reference on how to actually enable banner. Only references that it is done via PowerShell.  Please add a link to the page that references the PowerShell cmdlet. 

https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlineenhancedemergencyservicedisclaimer?msclkid=26e29a25d15c11ec82c9a7102206d453&view=skype-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634810fc-7a47-f794-7803-9f3941d664dd
* Version Independent ID: 52587955-5054-a003-6d03-948ce02838dd
* Content: [Plan and manage emergency calling - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/what-are-emergency-locations-addresses-and-call-routing)
* Content Source: [Teams/what-are-emergency-locations-addresses-and-call-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-emergency-locations-addresses-and-call-routing.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by JensTrier** [comment]
The disclaimer can now be set via Teams admin center under Voice -> Emergency policies -> calling policies -> Emergency calling policy.

For PS it is Set-CsTeamsEmergencyCallingPolicy -EnhancedEmergencyServiceDisclaimer

**Comment by 3017mark** [comment]
We need to remove the reference in the documentation that this is only available via PowerShell.  The "purple" box references it is only available via powershell.

**Comment by JensTrier** [comment]
@3017mark Yes, I have a PR in the works to do that

**Comment by JensTrier** [comment]
@3017mark My PR has merged. The PS note has been removed and the disclaimer is mentioned in the section on managing emergency calling policies that describes how to manage it via TAC or PS. 

Feel free to close this issue.

**Comment by CarolynRowe** [comment]
Closing this issue.
