### ISSUE TITLE
teams app does not load

### ISSUE THREAD

**Issue by DaStivi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#886]
the Teams app on Surface does not load? i don't see any controls on the side when joining ah Teams Meeting? also the store page still Shows the warning that Surface hub must be in joined the Insider program?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f256cd5b-3ec8-2d55-9ae4-ff9849d52eae
* Version Independent ID: 52c2271b-df38-5dc9-c2a1-553cdf3b5496
* Content: [Deploy Microsoft Teams for Surface Hub](https://docs.microsoft.com/en-us/microsoftteams/teams-surface-hub)
* Content Source: [Teams/teams-surface-hub.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-surface-hub.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by dmoore4** [comment]
We're having the same problem on our hubs.  Any resolution from support?

**Comment by dmoore4** [comment]
I've called support. One day later the Skype team called and moved my case to the Surface Hub team.  Then 15 hours later I received an email linking me to this article.  I'll share back if we progress from here.

**Comment by YolineN** [comment]
We're having the same issue, I've also logged a ticket at Office 365's admin center. Hopefully there will be a solution soon.

**Comment by peteredmi** [comment]
I'm having the same issue. no app to run.
Can't see the the teams app installed, except in the settings.
have rebooted several times.

**Comment by NatanGlaich** [comment]
Same issue over here on multiple surface Hubs.

**Comment by YolineN** [comment]
Our issue has been resolved.
The problem was that there was no Teams (Office 365) license assigned the the user that was configured on the Surface Hub.
Hope this will help some of you.

**Comment by yogkumgit** [comment]
@DaStivi  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link https://www.youtube.com/watch?v=puuOy0sEg1Y

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with your valuable piece of information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by dmoore4** [comment]
Hi @yogkumgit, or anyone else who might be interested and have the ability to track internal support cases.  Here's my case **#118103119292043] Microsoft Teams is not showing call controls after install on Surface Hub**

It's been open for months.
