### ISSUE TITLE
Discovery support scenaios

### ISSUE THREAD

**Issue by assaf-grth** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8863]
In addition to the detailed scenarios in the article, can you share if these additional scenarios are supported for discovery?
- 1:1 or Group chats that were started by an external user
- Meeting that is hosted externally with users from my organization

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 840dd36b-8c29-9738-4adc-ea9a7d277fd0
* Version Independent ID: b12c43c3-ed81-ace5-dfeb-77cac0f97fe9
* Content: [Conduct an eDiscovery investigation of content - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/ediscovery-investigation#search-for-content-for-guest-users)
* Content Source: [Teams/eDiscovery-investigation.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/eDiscovery-investigation.md)
* Service: **msteams**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by get-itips** [comment]
Hello @assaf-grth I tested this and I was able to discover content from the scenarios you described.
Hope this information helps you,
