### ISSUE TITLE
Difference between 2 settings

### ISSUE THREAD

**Issue by jozeflambrecht** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8864]
What is the difference between these 2 settings?

1. **Delete sent messages** Use this setting to let users delete messages that they sent in chat.
2. **Delete chat** Use this setting to let users delete messages that they sent in chat.

![image](https://user-images.githubusercontent.com/11506957/168615258-235e0a2f-9a9d-4195-a5fc-602bc9f555ab.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34f3188-0af5-f972-9d28-959f5f7866a2
* Version Independent ID: fab26e11-a729-92a4-3ea6-8668dca55dd0
* Content: [Manage messaging policies in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/messaging-policies-in-teams?WT.mc_id=365AdminCSH_SupportCentral#feedback)
* Content Source: [Teams/messaging-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/messaging-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
