### ISSUE TITLE
PowerShell Cmdlet using -Encoding byte is wrong

### ISSUE THREAD

**Issue by erik365online** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8879]
Hello there, could you please check the PowerShell snippet using -Encoding byte? This does not work. 

Affected line:
C:\> $content = Get-Content "C:\tmp\customMoH1.mp3" -Encoding byte -ReadCount 0
Please also see PowerShell cmdlet reference for the Get-Content cmdlet https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-content?view=powershell-7.2

"... -Encoding
Specifies the type of encoding for the target file. The default value is utf8NoBOM.

The acceptable values for this parameter are as follows:

ascii: Uses the encoding for the ASCII (7-bit) character set.
bigendianunicode: Encodes in UTF-16 format using the big-endian byte order.
bigendianutf32: Encodes in UTF-32 format using the big-endian byte order.
oem: Uses the default encoding for MS-DOS and console programs.
unicode: Encodes in UTF-16 format using the little-endian byte order.
utf7: Encodes in UTF-7 format.
utf8: Encodes in UTF-8 format.
utf8BOM: Encodes in UTF-8 format with Byte Order Mark (BOM)
utf8NoBOM: Encodes in UTF-8 format without Byte Order Mark (BOM)
utf32: Encodes in UTF-32 format. ..."

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 416f3cdb-ca75-8224-bc04-985e5f7ea9dd
* Version Independent ID: 6e8c6f33-8043-e367-b44b-74b5f5ee96f2
* Content: [Music on Hold - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/music-on-hold)
* Content Source: [Teams/music-on-hold.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/music-on-hold.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by JensTrier** [comment]
@erik365online Thanks for the feedback. 

The PS cmdlet sample referenced on this page is based on Windows PS 5.1. I'll add that to the page.

In the PS cmdlet page for Import-CsOnlineAudioFile we have example 4 that shows how to do it for Windows PS 6.0 or later using AsByteStream as you found out.

Feel free to close this issue
