### ISSUE TITLE
Parent Connection in Teams question

### ISSUE THREAD

**Issue by MVA11** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8880]
You mention that once a chat between Educator and Parent is done the Educator can Block the parent.

1) If this a little less blunt that 'you have been blocked'. 'ie This chat has now been closed.

2) Can the teacher initiate another chat with parent once the original communication was blocked?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d84a498-f519-2828-4979-efd79ab86d86
* Version Independent ID: b173c9d8-8cde-61a7-8a32-d74ce62af9bb
* Content: [Admin setup of Parents in Teams for Education - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/edu-parents-app)
* Content Source: [Teams/edu-parents-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/edu-parents-app.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by get-itips** [comment]
Hello, I am looking into this

**Comment by get-itips** [comment]
Hello @MVA11 

1. It's not that the blocked users will receive a notification stating that but as Docs says "The blocked user won't be able to start additional chats with the class owner."
2. Once unblocked it can re-start communication

Hope this information helps you,
