### ISSUE TITLE
Supervised chats

### ISSUE THREAD

**Issue by MVA11** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8881]
This mentions existing private chats between students may continue. Is there no way of resetting this so we ave a clean start point where only supervised communication is possible?

Thanks

Matt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 464c5a33-c12e-ec70-adf1-2e83d2ea9cd9
* Version Independent ID: cefecb3c-524a-0f13-ed7b-9f56cc434e13
* Content: [Use supervised chats - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/supervise-chats-edu)
* Content Source: [Teams/supervise-chats-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/supervise-chats-edu.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @MVA11, thank you for your feedback.

There is no way to achieve what you are asking currently. I know the product teams are always looking for user feedback and how to make Microsoft products better. They keep a close tab on user feedback and it would be awesome if you could add your voice to the Microsoft Feedback Portal: https://feedbackportal.microsoft.com/feedback/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to making the docs better! Much appreciated!
