### ISSUE TITLE
DSCP Value for App Sharing on macOS

### ISSUE THREAD

**Issue by georgalthaus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8887]
You documented the DSCP Vales for Audio and Video for macOS. Whats missing is the value for App Sharing.
Cloud you please update the documentation.

Thanks Georg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76c2487c-044d-1349-708a-5841fcb21ab8
* Version Independent ID: b7033454-1a9c-48d4-8004-78415c5feb89
* Content: [Implement Quality of Service in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/qos-in-teams)
* Content Source: [Teams/QoS-in-Teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/QoS-in-Teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Thanks for your feedback, I could get information from the team and an update to the article is being proposed
