### ISSUE TITLE
Supported Clients (Browser, VDI)

### ISSUE THREAD

**Issue by paul-lange** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8888]
Can you add more details about the supported clients for compliance recording?
Are users using a Browser or a VDI session supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 896e3ed7-aaf5-ad40-9a5f-1374d85c3e82
* Version Independent ID: 253d2a6b-9225-723a-cbc1-c296c3cfd36c
* Content: [Introduction to Teams Policy-based Recording for Calling & Meetings - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-recording-policy)
* Content Source: [Teams/teams-recording-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-recording-policy.md)
* Service: **msteams**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by get-itips** [comment]
Hello @paul-lange Paul,

Web is mentioned in the article as supporting the notification so I think we can conclude it is included, let me check on VDI.

Thank you
