### ISSUE TITLE
"People from my organization and trusted organizations"

### ISSUE THREAD

**Issue by cdowling1971** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8891]
Please check if "from" should be "in" in this string: 

"{1}People **from** my organization and trusted organizations{2} - Authenticated users and external users from Teams and Skype for Business domains that are in the external access allowlist can bypass the lobby. All other users will wait in the lobby until admitted."

The option elsewhere in this article is "People **in** my organization and trusted organizations". 

Please also verify that the UI options strings mentioned in this article in Fabric references as "People in my organization, trusted organizations, and guests" in Skype fabric tenant, not a single string without the "guests". Since the article mentions Microsoft 365 admin center, I figured out that the options are in Chicago tenant. This is what I found:

![image](https://user-images.githubusercontent.com/29043399/169359806-16975e43-1a82-4ac6-8d02-9d98baa35be3.png)

If the options are to be found in Skype tenant as this is Teams-related, then there is a source issue: "People from/in my organization and trusted organizations" should be "People in my organization, trusted organizations, **and guests**". We need to be sure about the correct tenant to search for the correct UI translations to be used in the localized version of the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33613b2d-d607-ec47-1254-ae540d07ad59
* Version Independent ID: aba728f0-0d3c-73fd-c7fe-68e69b6a753f
* Content: [Security guide for Microsoft Teams overview - Microsoft Teams](https://review.docs.microsoft.com/en-us/microsoftteams/teams-security-guide#participant-admittance)
* Content Source: [Teams/teams-security-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-security-guide.md)
* Service: **msteams**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by get-itips** [comment]
Thanks for your feedback @cdowling1971
