### ISSUE TITLE
"Invalid Teams Environment name for Migration API" -  error when connecting to GCCH environment

### ISSUE THREAD

**Issue by ckarawani** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8896]
Hello, 

I could not find any documentation around which TPM versions are supported in a GCCH environment. 
Seems 4.0.0 is not yet supported as it returns an error when connecting:

Command Being Used:
```
 Import-Module MicrosoftTeams -RequiredVersion 4.0.0;Connect-MicrosoftTeams -TeamsEnvironmentName TeamsGCCH
```

Response:
```
Message        : Invalid Teams Environment name for Migration API
ParamName      : 
TargetSite     : Void setMigrationEndPoint(System.String, Microsoft.TeamsCmdlet
                 s.Powershell.Connect.Models.AzureEnvironment)
Data           : {}
InnerException : 
HelpLink       : 
Source         : Microsoft.TeamsCmdlets.PowerShell.Connect
HResult        : -2147024809
StackTrace     :    at Microsoft.TeamsCmdlets.Powershell.Connect.Models.TeamsEn
                 vironment.setMigrationEndPoint(String teamsEnvironmentName, 
                 AzureEnvironment azureEnvironment)
                    at Microsoft.TeamsCmdlets.Powershell.Connect.ConnectMicroso
                 ftTeams.BeginProcessing()
```

**Comment by dariomws** [comment]
Hi @ckarawani, thank you for your feedback.

I'm not getting the same error, only a warning. Could you check with the latest version? (4.3.0)

If the issue persists, the best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information provided at [Get support](https://docs.microsoft.com/microsoft-365/business-video/get-help-support). Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).

**Comment by ckarawani** [comment]
hey @dariomws, yes it's just a warning as you say.  

Although the session initializes, I have noticed a couple of behavioural discrepancies. (ex. https://github.com/MicrosoftDocs/office-docs-powershell/issues/9476)

Apparently the modernization has not yet completed on the GCCH environments which is why the warning is popping up. 
(ref. https://github.com/MicrosoftDocs/office-docs-powershell/issues/9476#issuecomment-1139719256) 

A change was one to the Documentation around `Get-CsOnlineUser` cmdlet here to mention this:
https://github.com/MicrosoftDocs/office-docs-powershell/commit/aec7f8170c183d7ec11415129f846790f3dfe04c

You can probably consider this a duplicate? Or maybe add some more details elsewhere about the warning. 

Good either way! Thanks for the follow up!

**Comment by dariomws** [comment]
Thanks, @ckarawani.

I agree, I think we can consider this a duplicate and the new information in the Get-CsOnlineUser article should be enough.

**Comment by SamErde** [comment]
Noting that I get the warning, but my scripts continue when using version 4.6.0 of the MicrosoftTeams module. (I just noticed that 4.7.0 is available.)
