### ISSUE TITLE
Policy settings read the same

### ISSUE THREAD

**Issue by ray-wright** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8898]
The description of two messaging policies reads exactly the same. Here are the two policies as listed in the documentation:

- Delete sent messages Use this setting to let users delete messages that they sent in chat.
- Delete chat Use this setting to let users delete messages that they sent in chat.

Is there a difference between them? If so, can the descriptions be expanded to indicate that difference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34f3188-0af5-f972-9d28-959f5f7866a2
* Version Independent ID: fab26e11-a729-92a4-3ea6-8668dca55dd0
* Content: [Manage messaging policies in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/messaging-policies-in-teams)
* Content Source: [Teams/messaging-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/messaging-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @ray-wright I am looking into this
