### ISSUE TITLE
How this reflects Azure AD group membership and other services?

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#890]
How does this "org-wide" team, reflects in Azure AD portal under groups?
How is membership maintained, is this, dynamics membership (if so, what about additional license?) or which service handles the new users and removal for this kind of group?
How is this kind of group special, what about other services like exchange, sharepoint, yammer or power bi, for "org-wide" teams?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by AndreaBarr** [comment]
@hkusulja Thank you for this feedback

I am not sure how the membership is maintained or what service handles the new users or removal of this kind of group. I am going to get this over to the Teams/Skype for Business team for investigation so we can get some answers for you. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by hkusulja** [comment]
@AndreaBarr any info on this topic?

**Comment by AndreaBarr** [comment]
@nsshommo  can you please investigate this?

**Comment by hkusulja** [comment]
It seems, that this is normal Office 365 group, also in Azure AD with fixed/dedicated membership, so no dynamic membership is used and no additional license is needed.

Anyhow, which service is in-charge for updating/managing the membership, and more details on this service is needed (how it works, what is included, what is not) and how to manage this service (how to create block list / exclusions etc. etc.)

**Comment by scanum** [comment]
@nsshommo Any updates on this? Thanks

**Comment by nsshommo** [comment]
Nothing yet.

**Comment by hkusulja** [comment]
It is very bad from customer perspective that Microsoft does not want to communicate how service works and where is data stored....

**Comment by scanum** [comment]
@nsshommo Any updates on this? Thanks

**Comment by scanum** [comment]
@hkusulja thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by hkusulja** [comment]
@scanum the support does not know the answer / no info given from product group, please ask through your channel...
