### ISSUE TITLE
Article header

### ISSUE THREAD

**Issue by igorexplorer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8904]
[Enter feedback here]
Correct writing "Availability in Ukraine" insted of "Availability in the Ukraine"   
BR
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07064cfa-d530-727e-27d9-15f84ee473a4
* Version Independent ID: c8e900bf-75f6-352a-66ec-70cbd31218d1
* Content: [Availability in the Ukraine - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-ukraine)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-ukraine.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-ukraine.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
