### ISSUE TITLE
Org-wide custom app setting - Off - does not block Interaction with all custom apps is blocked for your organization

### ISSUE THREAD

**Issue by dipinn26592** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8908]
Org-wide Custom app setting turned off does not block interaction with all custom apps. To block communication we need to explicitly block each app under Manage Apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d51bb7b1-801e-6801-dcaf-afa3e38e6941
* Version Independent ID: d8e726a1-cbf2-53c7-da4d-cc155b48612b
* Content: [Manage custom app policies and settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-custom-app-policies-and-settings)
* Content Source: [Teams/teams-custom-app-policies-and-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-custom-app-policies-and-settings.md)
* Service: **msteams**
* GitHub Login: @guptaashish
* Microsoft Alias: **guptaashish**

**Comment by dariomws** [comment]
Hi @dipinn26592, thank you for your feedback.

This setting is intended to prevent the use of custom apps for your entire organization. If after 24 hours of enabling it your users can still use custom apps, I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by ashishguptaiitb** [comment]
Hello @dariomws and @scanum , do we need to keep the doc issue open and wait for further issues to be reported by @dipinn26592 or can we close it for now and rely that @dipinn26592 will re-open as required?

**Comment by dariomws** [comment]
@ashishguptaiitb, we can close it and he'll be able to re-open it if needed.

@scanum, could you close it?

Thanks!
