### ISSUE TITLE
Add "Meet Now" functionality in comparison chart

### ISSUE THREAD

**Issue by sklinger83** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#891]
In iOS, Skype for Business has a "Meet Now" button like the desktop client.  It does not appear this exists on the Android version.  Can this be addressed in this article?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 257dc4a1-8091-23db-64c4-f46b0519e14e
* Version Independent ID: c5094b34-c69d-9e8d-40cb-9197b924e632
* Content: [Mobile client feature comparison for Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/mobile-feature-comparison)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/mobile-feature-comparison.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/mobile-feature-comparison.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by AndreaBarr** [comment]
@sklinger83 Thank you for this feedback

I will get this information about the button not being there on the Android version over to the Teams/Skype for Business team so this can be addressed appropriately. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @sklinger83 

Thanks for sharing your feedback, we really appreciate it.

Meet now functionality is present in comparison chart, you have to look under Conferencing Support chart, option "Start an unscheduled group conversation with multiple participants directly from your client or device "
That option refers to Meet Now functionality.

Hope this information helped you out!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @sklinger83  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
