### ISSUE TITLE
Ambiguity and consistency in instructions

### ISSUE THREAD

**Issue by csnyderTAG** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8914]
This page has some ambiguity when it comes to information regarding Macs.

Under "Debug Logs" it mentions how to collect the logs and where they will be in relation to Linux and Windows only. While the description mentions Mac instructions from above, it fails to provide information in the sections below.

"Media logs", seems to show all possibilities Windows, Mac, and Linux, and the data is setup in a way that makes sense, 

When we get back down to "Desktop Logs" we have omitted Mac instructions again. Here it shows the file locations for Linux and Windows, but fails to mention where they would be in a Mac.

- I was able to find the Mac log in [~/Library/Application Support/Microsoft/Teams/log.txt], but this isn't explicitly stated anywhere. 

Since when Microsoft support reps simply link the article and provide no additional information or assistance when logs are requested, it can be very frustrating since I'm just looking for instructions to grab and not have to play guessing games to ensure I get what is needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d5e6d3-b7e0-d79f-0dea-ed423186a157
* Version Independent ID: ec6e68aa-552f-ab45-3c8e-92eff526b173
* Content: [Use log files in troubleshooting Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/log-files)
* Content Source: [Teams/log-files.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/log-files.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @csnyderTAG I'll propose to add that information to the article, thanks
