### ISSUE TITLE
Could you tell me specification about audit log about shared channel?

### ISSUE THREAD

**Issue by dshimogawa** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8918]
[Enter feedback here]
Hi, Team.
I want to know specification about audit log about shared channel. 
[Environmental information]
・Resource of the Teams shared channel: Tenant A
・Tenants invited to the Teams shared channel: Tenant B
・User X in Tenant B
・User Y in Tenant B

[Case]
User X invited User Y for shared channel.

[Question]
I want to keep a record User X action. In this case, is this keep on audit log on Tenant A?

Best regards,
Daishi Shimogawa.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e51e97-ff97-c5eb-6517-21ce9a563ca4
* Version Independent ID: d3dc21b2-d90a-fbe7-8473-fff0b55feafb
* Content: [Search the audit log for events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audit-log-events)
* Content Source: [Teams/audit-log-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audit-log-events.md)
* Service: **msteams**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
