### ISSUE TITLE
Missing details on 2001

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8924]
Please add details on the difference between the two fields in the 2001 error:

- Signin status
- Teams Signin status

We see all sorts of failures on signin status, but the device is authenticated fine and there are 0 failures in AAD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3de2dce0-681a-8237-62d5-bd45b00e47c0
* Version Independent ID: 3d1cafce-6c64-452c-e596-ff5ee4d39bde
* Content: [Monitor Microsoft Teams Rooms devices with Azure Monitor - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/azure-monitor-manage)
* Content Source: [Teams/rooms/azure-monitor-manage.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/azure-monitor-manage.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @danmyhre Dan,

From my experience, Sign in status corresponds solely to SfB and you can see unhealthy on it while seeing a healthy state in Teams sign in status, so it depends on your environment and configuration.

Is that what you are seeing?

**Comment by danmyhre** [comment]
Yes, that seems to be correct. The documentation should clarify that. One of the problems is that since SfB is no longer a thing, Teams rooms systems continually log unhealthy on the Signin status, which broken monitoring by generating constant false alarms.
