### ISSUE TITLE
Firmware upgrades

### ISSUE THREAD

**Issue by ppbass** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8928]
Hi, 
when jumping to https://docs.microsoft.com/en-us/microsoftteams/devices/teams-ip-phones#firmware-versions-1 I could spot that e.g. the firmware for Poly devices X30/X50 was not up to date. (I think for x Series FW 3.11 with 2022 Update #1 would be the most recent build including a newer Teams App then 3.9 with 2021 Update 2F, which is shown as the most recent at the moment).
This might be irritating for users as it doesn't match the info on TAC.
Best regards
RS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaaef9e1-8f1c-ebf0-7856-4c007342a2c3
* Version Independent ID: 3eaf671f-375e-8787-9c66-3947c3606559
* Content: [Devices for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/teams-ip-phones)
* Content Source: [Teams/devices/teams-ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/teams-ip-phones.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
