### ISSUE TITLE
Download link produces a 404

### ISSUE THREAD

**Issue by PrMinisterGR** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8931]
The download link gives a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4fa80cf-0319-c006-e886-4929a508b04c
* Version Independent ID: 9d598765-fc30-17f0-6594-57de81d8aa39
* Content: [Manually update a Microsoft Teams Rooms device - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/manual-update#step-1-download-the-offline-app-update-script)
* Content Source: [Teams/rooms/manual-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/manual-update.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @PrMinisterGR, thank you for your feedback.

Could you double-check the link, please? It's working now.
