### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by davidisler** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8935]
The download link "https://go.microsoft.com/fwlink/?linkid=851168" is forwarding to an 404 - File or directory not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13376c1b-df70-83de-8e6a-8ddc940774b5
* Version Independent ID: 6a2531ee-ac88-ee83-b858-1928d6cb4c65
* Content: [Use the Microsoft Teams Rooms recovery tool - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/recovery-tool#feedback)
* Content Source: [Teams/rooms/recovery-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/recovery-tool.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by lindspea** [comment]
@davidisler thank you for reaching out and helping to improve Microsoft Docs. I've had a quick look and the link seems to be working from my side now. Please can you check again to see if it works from your side as well. Thanks.
