### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by davidisler** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8936]
Link "https://go.microsoft.com/fwlink/?linkid=2151817" is forwarding to an 404 - File or directory not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4fa80cf-0319-c006-e886-4929a508b04c
* Version Independent ID: 9d598765-fc30-17f0-6594-57de81d8aa39
* Content: [Manually update a Microsoft Teams Rooms device - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/manual-update)
* Content Source: [Teams/rooms/manual-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/manual-update.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@davidisler thanks for providing feedback, there is already an open issue for this link.
