### ISSUE TITLE
CQ report - some entries missing agent name

### ISSUE THREAD

**Issue by LD-TQSTICT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8937]
We're using this report for Teams Telephony Call Queue statistics.

Unfortunately we are seeing multiple entries in the report without any agent name.
It's not a large percentage of the queues total calls, but it is not an insignificantly small number either.

Is there anyway to understand who or what these entries represent?
Or why the report is unable to retrieve a name for the agent responsible for them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 628345c6-f5f9-fe8e-bfff-faea00a8a25c
* Version Independent ID: 30f2d051-5af5-0063-7099-38b5b08ec1e4
* Content: [Auto Attendant & Call Queue Historical Report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/aa-cq-cqd-historical-reports)
* Content Source: [Teams/aa-cq-cqd-historical-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/aa-cq-cqd-historical-reports.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe*
![missing agent name](https://user-images.githubusercontent.com/106575556/171099744-0b79ed80-9f58-4f7e-9dde-67d945da174b.png)
*

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
