### ISSUE TITLE
Need more detail in this Doc page on how to enforce dialing restrictions from CAP phones

### ISSUE THREAD

**Issue by JasonSmith-MS** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8944]
Examples of dialing restrictions customers might request for CAP:
- Disallow long-distance / international calling
- Only allow calls to users/devices within the company, i.e. no outside line allowed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ab5215-f24f-75cf-bb92-16ac0ff5e5ca
* Version Independent ID: 701cc58f-d2ea-cbb6-f5fc-47b9fbfb1119
* Content: [Set up the Common Area Phone license - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-common-area-phones)
* Content Source: [Teams/set-up-common-area-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-common-area-phones.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by get-itips** [comment]
Hello @JasonSmith-MS 
The procedure focuses on what is available with a CAP license, an a CAP license does not include domestic or international calling, for that, you would have to assign a Calling Plan. If you decide to assign a CP, you could use dial plans and outbound calling restrictions as with any other user.
Please let me know if I understood you correctly,
Thanks

**Comment by get-itips** [comment]
@scanum
