### ISSUE TITLE
Dialing out from an Audio Conference meeting to your mobile phone with the Microsoft Teams app or Skype for Business app installed to destinations that aren't already included in your subscription

### ISSUE THREAD

**Issue by XixiHuang333** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8946]
[Enter feedback here]

Hello Team,

How can we understand this sentence? “Dialing out from an Audio Conference meeting to your mobile phone with the Microsoft Teams app or Skype for Business app installed to destinations that aren't already included in your subscription.”
[What are Communications Credits? - Microsoft Teams | Microsoft Docs](https://docs.microsoft.com/en-us/microsoftteams/what-are-communications-credits)

![image](https://user-images.githubusercontent.com/40224592/171375536-58ad7fe7-49c6-4d54-adee-72709189daa5.png)

It may be understood in two ways:
1)	Teams uses from Teams mobile app in audio conference meeting dials out to a PSTN number, but this PSTN destination is not included in this Teams user’s Calling Plan and ACP subscription. I prefer to this way as below context: 

 
![image](https://user-images.githubusercontent.com/40224592/171375572-da730aab-088f-470f-98b8-e9d945774cf0.png)

However, Calling Plan and ACP subscription feature or limitation applied to both of Teams desktop client and mobile client, why the sentence mentioned ‘to your mobile phone with the Microsoft Teams app or Skype for Business app installed’, this may make us or customer to understand it as below way, which doesn’t make sense.
2)	Dialing out from an Audio Conference meeting to other teams user and this teams user accept this ACP call from teams mobile application, but teams mobile application software is not included in this teams user’s M365 subscription.

This sentence really confused the customer or reader, really appreciate any comments for this.

Thanks a lot.
Xixi Huang
xixih@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d52a9779-b72d-dea0-eac2-6c04a8c282eb
* Version Independent ID: d3c3d968-9e54-ec42-3438-9320e23d68b9
* Content: [What are Communications Credits? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/what-are-communications-credits?toc=%2Fskypeforbusiness%2Fsfbotoc%2Ftoc.json&bc=%2Fskypeforbusiness%2Fbreadcrumb%2Ftoc.json)
* Content Source: [Teams/what-are-communications-credits.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-communications-credits.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by XixiHuang333** [comment]
@scanum  I am a Teams support engineer who handle the support ticket. 
Do we have PM or writer who provided this content or sentence here to verify if my understanding is correct?
sentence : Dialing out from an Audio Conference meeting to your mobile phone with the Microsoft Teams app or Skype for Business app installed to destinations that aren't already included in your subscription.
My understanding: Teams uses from Teams mobile app in audio conference meeting dials out to a PSTN number, but this PSTN destination is not included in this Teams user’s Calling Plan and ACP subscription.
