### ISSUE TITLE
Can you please clarify how this will allow teams access?

### ISSUE THREAD

**Issue by lmccord** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8948]
I have a conditional access policy to block sharepoint which looks exactly like this policy except that it blocks rather than grant.  I want to change it to allow teams as mentioned in the first paragraph, but I don't understand how changing it to grant access will do that while blocking sharepoint.  Can you clarify the "workaround" part of this?  thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2308e7ef-1a9a-0fd1-53c4-7b6e5387978a
* Version Independent ID: 9d9a661f-841c-6b3b-b579-f4e507bcbddd
* Content: [Block access to SharePoint for specific users - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/block-access-sharepoint?source=docs)
* Content Source: [Teams/block-access-sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/block-access-sharepoint.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
