### ISSUE TITLE
Switch Name for -ReplaceExistingRgsSettings Incorrect

### ISSUE THREAD

**Issue by Atreidae** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#895]
Hi all, first docs edit here
on this article the switch to replace existing settings is listed as "-ReplaceExistingSettings" when it should be "-ReplaceExistingRgsSettings" as per
https://docs.microsoft.com/en-us/powershell/module/skype/Import-CsRgsConfiguration?view=skype-ps

I've tested this in a production environment and confirmed the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd0eb601-562d-b40e-bc8f-d23679739d28
* Version Independent ID: 0bd267da-a5af-e008-9f2c-ce67d5014a22
* Content: [Lync Server 2013: Moving response groups to a new pool](https://docs.microsoft.com/en-us/lyncserver/lync-server-2013-moving-response-groups-to-a-new-pool)
* Content Source: [Lync/LyncServer/lync-server-2013-moving-response-groups-to-a-new-pool.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Lync/LyncServer/lync-server-2013-moving-response-groups-to-a-new-pool.md)
* GitHub Login: @dstrome2

**Comment by AndreaBarr** [comment]
@Atreidae Thank you for this feedback

I have created a pull request to fix this typo. I am waiting on the review and approval to merge the request to the live article. I will let you know when the pull request has been merged. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@Atreidae The update has been approved and merged. I am closing this issue as resoled.
