### ISSUE TITLE
Update outdated Syndication Partner Customer to CSP

### ISSUE THREAD

**Issue by naizatan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8951]
Please update "Syndication Partner Customer" to Cloud Solution Provider customer/CSP customer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-exploratory?source=docs#feedback)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by tiburd** [comment]
The product team is aware of this suggestion.
Closing this issue.
