### ISSUE TITLE
Memory Requirements incorrect

### ISSUE THREAD

**Issue by JoshJ-MSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8954]
The memory requirements state 4GB Ram.  This article used to clarify that 4GB Ram was necessary for the Teams application exclusively.

Teams will not run properly with all modalities on a system that has only 4GB RAM.

Support refers customers to this article when they are running insufficient hardware.  As the article is now worded it is not useful for this purpose.  Customer will run support tickets for poor performance on machines that are not sufficient.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29a61ff5-b3a5-158d-149a-dec344060e05
* Version Independent ID: 97fac351-a283-aaa8-cde1-fbd9cf4e8504
* Content: [Hardware requirements for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/hardware-requirements-for-the-teams-app)
* Content Source: [Teams/hardware-requirements-for-the-teams-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hardware-requirements-for-the-teams-app.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @JoshJ-MSFT, thank you for your feedback.

Not sure if that's true. I never see Teams consuming 4 GB RAM, usually slightly less than 1 GB. Please also check the following issue and the article "How Microsoft Teams uses memory":
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9090

You can also see that the information you are requesting to add to the article was added:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/6e58d7454f0b75d7eff1d7398c60ab682364008a
And then removed:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/b3d7b8b5f9eb8043143f63a0fd8866d99618648a

**Comment by JoshJ-MSFT** [comment]
Just going to register an objection here.  This is now a published article saying Teams will run on a system with 4GB of ram.  It will start and run, yes.  When users try to use full modalities such as video and desktop sharing it will generate a support ticket.  

@dariomws Sorry, just now being notified of your comment in July.  A basic idle Teams client will be less than 1GB ram, yes.    When modalities are added the usage climbs.  A system with 4GB total system RAM will not be able to provide this.  We then see memory manager consuming CPU to keep up with zeroing pages.  As a 4GB system is typically a low power CPU system as well we get a collapse in performance.

We (Escalation level support engineers) need to be able to point to a public document that has accurate hardware requirements.  4GB of total system RAM is not adequate.

Feel free to ping me directly if questions - JoshJ

**Comment by sschiem** [comment]
@dariomws I work with Josh Jones, and fully agree with his comments. Customers trying to run Teams on 4 or even 8-gig RAM machines are a substantial part of our case load. Teams will run on 4 gigs RAM, but it will not run well. Also in play are other apps running on the system. No one expects end users to ONLY run Teams. They also run Outlook and sometimes many tabs of Edge or Chrome, for example. The OS itself needs at least 1 gig RAM. I invite you to run Teams yourself on a 4-gig RAM machine, virtual or physical. You can ping Josh or me for support when you are unhappy with Teams performance. 

At a minimum, I think we should say, in that article, that Teams will run, but be more clear about the impact that multiple Teams modalities, other applications, and the OS requirements will have on Teams performance. 

why was the previous version of the article, addressing some of these points, removed?
