### ISSUE TITLE
Permissions tab of self-created app is empty.

### ISSUE THREAD

**Issue by gp1105739** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8957]
I created a Teams app for our Organization and published it to our org-level Teams app store. The app is not approved yet. When I go to Teams admin center, the permissions tab is empty and there is no way to grant admin consent to the app, which is contradictory to what it says on https://docs.microsoft.com/en-us/microsoftteams/app-permissions-admin-center 

Can anyone take a look?  Thanks!
![Screen Shot 2022-06-03 at 1 44 58 PM](https://user-images.githubusercontent.com/17413956/171955205-cb3fe20b-927e-4938-b6cf-e49f27a65bfd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa7ace5-8129-5f9c-e8b1-7a10b985c8ff
* Version Independent ID: e4b85639-1cf9-e3f2-8429-c7e92391f5c2
* Content: [View app permissions and grant admin consent in the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/app-permissions-admin-center#feedback)
* Content Source: [Teams/app-permissions-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/app-permissions-admin-center.md)
* Service: **msteams**
* GitHub Login: @guptaashish
* Microsoft Alias: **guptaashish**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
