### ISSUE TITLE
Purchasing Communication Credits requires Audio Conferencing

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8966]
Hello,

We are setting up a toll-free number and the article correctly says
> You will need to set up Communications Credits if you would like to use toll-free numbers...

According to step 1 of this article, 
> To do so, **you need to assign an Audio Conferencing or a Phone System license** to your users.
https://docs.microsoft.com/en-us/microsoftteams/set-up-communications-credits-for-your-organization#step-1-assign-an-audio-conferencing-or-calling-plan-license-to-your-users

Unfortunately, a phone System license does not enable the ability to purchase communication credits because we have phone system licenses assigned to users and cannot purchase communication credits.

We opened a ticket with MS and learned that we must have an audio conferencing license to purchase communication credits so I recommend updating the article as follows:
> To do so, **you need to assign an Audio Conferencing license** to your users.

I'm not sure if assigning the license is required to enable the purchase area, but we certainly don't need to assign an Audio Conferencing license to more than one user allow the purchase of communication credits for our toll-free number.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 277cf140-5c6c-82c7-cc56-490ef2188754
* Version Independent ID: 72e7de29-fd71-23bf-15a7-172634c2a5fd
* Content: [Set up Communications Credits for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-communications-credits-for-your-organization)
* Content Source: [Teams/set-up-communications-credits-for-your-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-communications-credits-for-your-organization.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Document has been updated recently to clarify procedure and requirements.
