### ISSUE TITLE
Missing which roles allow assignment of policies

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8967]
Missing details on which roles allow assignment but not creation/editing of teams policies (helpdesk admin) as well as what M365 user and delegated helpdesk admins can do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b434530-6bf2-6e00-6eae-6fa043d022ce
* Version Independent ID: caab785f-e3a4-831a-87d8-26934a9f834f
* Content: [Use Microsoft Teams administrator roles to manage Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/using-admin-roles)
* Content Source: [Teams/using-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/using-admin-roles.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @TheBluLion, thank you for your feedback.

Could you provide more detail, please? If I try to access the Teams Admin Center with a Microsoft 365 Helpdesk Admin I get the following error:
![image](https://user-images.githubusercontent.com/33589238/180732017-49a017d1-ed75-4015-89e7-9878b7811236.png)

This article is dedicated to Teams roles, so admin roles like Global Admin are not included here.
