### ISSUE TITLE
Impacts

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8968]
It should be added to this page that there are side-effects of turning this on. For example, it removes the search box from Teams for users to be able search for and join teams. It also blocks the recommended public teams from displaying on the "join or create  a team" screen in Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84066c98-38a4-e59a-893f-da38a4a11bf3
* Version Independent ID: 890a4978-0e9b-2691-a2ab-8b5512e5e76f
* Content: [Limit who users can see when searching the directory in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-scoped-directory-search)
* Content Source: [Teams/teams-scoped-directory-search.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-scoped-directory-search.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Dan, to understand better and being able to reproduce, did you experience that right after toggling on _Scope directory search using an Exchange address book policy_? and which option from the two available did you choose? Thanks

**Comment by get-itips** [comment]
Nevermind, I've just enabled scope directory search and that was enough to disable the functionality, I'll propose adding that, if it gets approval, it will be in the article. Thanks

**Comment by danmyhre** [comment]
Thanks! I think it may take 24 hours to see the change in Teams, but the search and recommended public teams will no longer be shown.

**Comment by itazlin** [comment]
Hello! Can anyone inform me as to why this is the intendet behaviour? I'd like for us to be able to seperate some non personal users from showing up but now my users cannot use the join teams function...

**Comment by scanum** [comment]
Hi @itazlin 
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
