### ISSUE TITLE
Instructions to Enable or disable anonymous callers from joining a meeting are inaccurate

### ISSUE THREAD

**Issue by argumemnon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#897]
These instructions are inaccurate. This is the behavior observed:

1. In the left navigation, click Users. -- OK

2. Select a user in the list, and then click Edit at the top of the page. -- OK

3. Next to Audio Conferencing, click Edit. -- OK

4. In the Audio Conferencing pane, enable or disable Unauthenticated callers can be the first person in a meeting. -- this option is unavailable. All I see is a button to turn Audio Conferencing on or off for this user, the Toll-free dial-in number that has been assigned with the license, and the "Dial-out from meetings" option. There is no option to enable or disable Unauthenticated callers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b4d417-8a1f-daca-381a-b1beed2dbdac
* Version Independent ID: d3e59d94-b0b7-fdfc-3a04-00dc4188e63d
* Content: [Start an Audio Conference over the phone without a PIN in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/start-an-audio-conference-over-the-phone-without-a-pin-in-teams)
* Content Source: [Teams/start-an-audio-conference-over-the-phone-without-a-pin-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/start-an-audio-conference-over-the-phone-without-a-pin-in-teams.md)
* Service: **-msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@argumemnon Thank you for this feedback

I'm not sure why you aren't seeing the enable or disable button. I am going to get this over to the Teams/Skype for Business team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by kenstifle** [comment]
I am having the same issue (option unavailable).

**Comment by dschuette01** [comment]
I am having the same issue -- this option does not appear where the article describes. It says only "Audio Conferencing" (on or off), "Toll Number," and "Dial-out from meetings." I previously interacted with this setting in the Skype for Business legacy admin portal, but the functionality does not seem to be there in the Teams admin portal.

**Comment by kenstifle** [comment]
I was able to get this working. It looks like this is a policy setting now. However, modifying the Global (Org-wide default) policy has no effect, so you need to create a new policy.

I believe the steps should be:

1. In the left navigation, expand Meetings.
2. Click Meeting policies
3.  Click New policy.
4. Under "Participants & guests, turn on "Allow anonymous users to start meetings" and set "Automatically admit users" to Everyone.
5. In the left navigation, click Users.
6. Select a user in the list, and then click Edit at the top of the page.
7. Next to Assigned policies, click Edit.
8. Select the new policy you just created in step #3 in the Teams Meeting policy drop down and save.

**Comment by kenstifle** [comment]
@Mark7even 
It will ask for a PIN but if you just press pound the meeting will start.

**Comment by get-itips** [comment]
Hi @argumemnon 

Thanks for all the shared feedback, we really appreciate it.

I can confirm that the option is present using Global default policy, which has "Allow anonymous users to start meetings" off and "Automatically admit users" to Everyone in your organization, maybe it wasn't present at the time you submitted the issue?

Thanks also to everyone that also commented on this issue.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @argumemnon  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
