### ISSUE TITLE
Modern authentification / service principal not supported on MicrosoftTeams PS module cmdlets

### ISSUE THREAD

**Issue by T630Dev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8971]
Hi,

we are using M365DSC which in turn uses PS cmdlets from the MicrosoftTeams module.
The problem here is that several cmdlets only work with the classic auth. (username + pwd) instead of service principals that do work with App registrations (GUID + secret or certificate thumbprint).
We use the current teams version: 4.4.1

A few examples of cmdlets that we need / use:
TeamsMessageingPolicy,TeamsMeetingPolicy,TeamsMeetingBroadcastPolicy,TeamsChannelsPolicy,TeamsUpgradeConfiguration,TeamsClientConfiguration,TeamsGuestMessagingConfiguration,TeamsGuestCallingConfiguration,TeamsGuestMeetingConfiguration,TeamsCallingPolicy

Is there any plan or roadmap to change these to also support service principals?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
