### ISSUE TITLE
How to add numbers from the SBC?

### ISSUE THREAD

**Issue by flattery103** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8975]
The document says how to get numbers from Microsoft but it doesn't say how to set numbers to a user that are coming through an SBC SIP Trunk

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5399db17-aa9c-0cdf-5452-9fc9f6b7fe16
* Version Independent ID: bc6c8ea0-33cf-6822-d3de-3363d630a45a
* Content: [Manage phone numbers for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-landing-page)
* Content Source: [Teams/manage-phone-numbers-landing-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-phone-numbers-landing-page.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
