### ISSUE TITLE
How to certified my SBC of company?

### ISSUE THREAD

**Issue by postren** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8978]
Hello,
How to certified (Session Border Controllers certified for Direct Routing) my SBC of company?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d964547-6b38-cc5f-6b2b-7a50a1c7dae9
* Version Independent ID: fa5850f9-1b92-9727-c344-bcffc227cbd6
* Content: [Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-landing-page)
* Content Source: [Teams/direct-routing-landing-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-landing-page.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
