### ISSUE TITLE
Descriptions of the table breakdown are confusing

### ISSUE THREAD

**Issue by brianleesmith** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8987]
Under the Interpret the Report section, callout 7 talks about the different column headers.  Unfortunately, there are no links that define the types of messages.  Specifically, the difference between channel and post messages.  Reply, chat, and urgent messages all make sense.  Channel and post sound similar, but there is no clarification (or link to one) as to what the differences are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2758a3d6-c646-dcb0-2a31-c7b9b84e780b
* Version Independent ID: 8704c9fe-f8b0-82d2-bd83-3fd1a9ad638d
* Content: [Microsoft Teams user activity report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report)
* Content Source: [Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @brianleesmith, thank you for your feedback.

I hope the following similar issue helps you to clarify this:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4545

**Comment by brianleesmith** [comment]
Although this does help, just to be clear…”team chat” is a very specific term (in my mind) that conflicts with the term “channel messages.”   Teams are full of _channels_.  The Teams app also has _chats_, which are not _channels_.  Hence the confusion and original my point.  The terms are not aligning with one another.  Either the term “channel messages” needs to be changed OR the phrase “posted in a team chat” needs to be refined.  Having _Channel_ and _chat_ in the same sentence that is the definition is confusing.

from the other post you referenced…

As per definition
• Channel messages is the number of

unique messages
that the user posted in a team chat during the specified time period.

• Reply messages is the number of

unique reply messages
that the user posted in a team channel during the specified time period.

• Post messages is the number of

unique post messages
that the user posted in a team channel during the specified time period.
