### ISSUE TITLE
Updates missing from S4B Server 2015 Update History

### ISSUE THREAD

**Issue by bubbletroubles** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#899]
The "Skype for Business Server 2015 update history" section is missing the following updates"

**March 2018 CU6/HF2 9319.516**
https://support.microsoft.com/en-au/help/4075225/march-2018-cumulative-update-6-0-9319-516-for-skype-for-business
https://support.microsoft.com/en-au/help/4086059/march-2018-cumulative-update-6-0-9319-516-for-skype-for-business
https://support.microsoft.com/en-au/help/4075222/march-2018-cumulative-update-6-0-9319-516-for-skype-for-business
https://support.microsoft.com/en-au/help/4086058/march-2018-cumulative-update-6-0-9319-516-for-skype-for-business

**January 2018 - CU6/HF1 9319.514**
https://support.microsoft.com/en-au/help/4074702/january-2018-cumulative-update-6-0-9319-514-for-skype-for-business
https://support.microsoft.com/en-au/help/4074704/january-2018-cumulative-update-6-0-9319-514-for-skype-for-business

**Dec 2017 - CU6 9319.510**
https://support.microsoft.com/en-au/help/4036311/dec-2017-cumulative-update-skype-for-business-server-2015-core-compone
https://support.microsoft.com/en-au/help/4036312/dec-2017-cumulative-update-for-skype-for-business-server-2015-front-en
https://support.microsoft.com/en-au/help/4036317/dec-2017-cumulative-update-for-skype-for-business-server-2015-enterpri
https://support.microsoft.com/en-au/help/4036314/dec-2017-cumulative-update-for-skype-for-business-server-2015-web-comp
https://support.microsoft.com/en-au/help/4036310/dec-2017-cumulative-update-skype-for-busines-server-2015-and-unified-c
https://support.microsoft.com/en-au/help/4036315/dec-2017-cumulative-update-skype-for-business-server-2015-video-intero
https://support.microsoft.com/en-au/help/4036318/dec-2017-cumulative-update-skype-for-business-server-2015-web-conferen
https://support.microsoft.com/en-au/help/4036316/dec-2017-cumulative-update-for-skype-for-business-server-2015-persiste

**Feb 2017 - CU4/HF1**
https://support.microsoft.com/en-au/help/3207502/february-2017-cumulative-update-6-0-9319-277-for-skype-for-business-se
https://support.microsoft.com/en-au/help/3207506/february-2017-cumulative-update-6-0-9319-277-for-skype-for-business-se
https://support.microsoft.com/en-au/help/3207503/february-2017-cumulative-update-6-0-9319-277-for-skype-for-business-se
https://support.microsoft.com/en-au/help/3207504/february-2017-cumulative-update-for-skype-for-business-server-2015-and
https://support.microsoft.com/en-au/help/3207505/february-2017-cumulative-update-6-0-9319-277-for-skype-for-business-se

**Sep 2015 - RTM/HF2 9319.88**
https://support.microsoft.com/en-au/help/3098601/september-2015-cumulative-update-6-0-9319-88-for-skype-for-business-se

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be9f745c-5925-3a7b-9430-b5e61b4384ba
* Version Independent ID: bc23dce3-f38b-9e81-1614-d16aed1d8684
* Content: [Skype for Business Server updates](https://docs.microsoft.com/en-us/skypeforbusiness/sfb-server-updates#skype-for-business-server-2015-update-history)
* Content Source: [Skype/SfbServer/sfb-server-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/sfb-server-updates.md)
* Product: **skypeforbusiness-server-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by Atreidae** [comment]
The latest CU for Lync 2013 is also missing
https://docs.microsoft.com/en-us/skypeforbusiness/sfb-server-updates#lync-server-2013-update-history

**Comment by AndreaBarr** [comment]
@bubbletroubles and @Atreidae Thank you for this feedback

I will get this information about server update list histories missing to the Teams/Skype for Business team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by jambirk** [comment]
The page owner has updated the page to show that  the master KB 3061064 contains all the Cumulative Updates. Adding the same info onto this page will be redundant.

**Comment by bubbletroubles** [comment]
> The page owner has updated the page to show that the master KB 3061064 contains all the Cumulative Updates. Adding the same info onto this page will be redundant.

I'm sorry, but I disagree. The page does not show the full Skype for Business Server Update History. Update history is important when
- Service providers and contracts have clauses for keeping software current at n-1. Without the history, its hard to determine
- Skype for Business installations globally will be at the previous hotifx levels. This should be the authoritative page where technicians can see what baseline they are currently on, and what they need to get to.
- The KB 3061064 doesn't list the March 2018 (and other) hotfixes.

**Comment by jambirk** [comment]
@Ariantor  can you please comment further?

**Comment by Ariantor** [comment]
The KB I mentioned is the master list. It will have the history of all the CUs we have released. Please take a look at the KB 3061064. It is risky for us to say the same twice on 2 different places.

**Comment by bubbletroubles** [comment]
> The KB I mentioned is the master list. It will have the history of all the CUs we have released. Please take a look at the KB 3061064. It is risky for us to say the same twice on 2 different places.

This article is the "Skype for Business Update History". The updates listed include some CUs, but many are missing. The expectation would be that all CUs are listed, given its the "Update History". KB3061064 is not the "Skype for Business Update History"

**Comment by Ariantor** [comment]
Please let me know what is missing, we will have to fix the master KB. We should not have missing KBs in the master KBs since it is being used as the reference point.  All info is originating from the master KBs. All the fixes that require KBs are recorded in the master KB - that is our base line, our knowledge starts there :). We create this page so the customers have 1 stop shopping for all KBs (SfB and Lync Server). Please note, each of the major product releases have its own master KB. That means, SfB Server 2015 and Lync Server 2013 (2809243) have separate master KBs. SfB Server 2019 will have a separate master KB when we issue CU1.

**Comment by jambirk** [comment]
@bubbletrouble and @Atreidae  we've made the updates you pointed out to this page. We'll need to sort out ownership of maintenance for this page.

**Comment by bubbletroubles** [comment]
Excellent - the new page looks great :) Thanks for your help!
