### ISSUE TITLE
List contains features you already get without Phone System License so its misleading/inaccurate

### ISSUE THREAD

**Issue by dinocaputo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8992]
[Enter feedback here]
This table is not accurate https://docs.microsoft.com/en-us/microsoftteams/here-s-what-you-get-with-phone-system#phone-system-features

It contains features you would get without a Phone System License and should be updated.
ie - device switching, make and receive a video call, secondary ringer, callerID, etc..  

Please review this list and ensure it only contains items features unlocked with Phone System.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cfead3c-b0d8-c22a-aa22-63e79fe53ed3
* Version Independent ID: 10745875-3d3e-42bb-e324-ff4c83968ccf
* Content: [Here's what you get with Phone System - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/here-s-what-you-get-with-phone-system)
* Content Source: [Teams/here-s-what-you-get-with-phone-system.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/here-s-what-you-get-with-phone-system.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @dinocaputo I am looking into this, thanks for your feedback

**Comment by CarolynRowe** [comment]
Hi @dinocaputo.  The article is true for Phone System.  We are discussing with the PMs about how we should distinguish the features that are also available without a Phone System license.  If we suddenly remove features, it might be very confusing to some customers.  I am closing this issue for now, but be aware that we are discussing.  Thanks for your feedback.
