### ISSUE TITLE
Is it possible to add which Team is using the app?

### ISSUE THREAD

**Issue by Darrelo365** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8993]
Hi, will it be possible in the future to show what Team is using what app and to filter by 1st party, 3rd party and in-house built app?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed4904e2-a072-56fc-bc54-4e7d2582d8fd
* Version Independent ID: c70894ac-67e3-be36-4fa6-a95c78fa736a
* Content: [Microsoft Teams app usage report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/app-usage-report)
* Content Source: [Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
