### ISSUE TITLE
Clarification Needed: Custom Content Types in Shared Channel sites

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8997]
The documentation states the following:

> A shared channel site syncs data classification from the site of the parent team.

What does this actually mean and does it have anything to do with the fact that adding custom Content Types published from the gallery is _disabled_ in these kinds of sites?
![image](https://user-images.githubusercontent.com/9206808/173370204-954c241e-8fa1-4e5e-b767-024b7d2f7641.png)

If the Shared Channel site is supposed to automatically have the same Content Types as those added to the document library in the parent Team's site, this is both broken (not working) and, in my opinion, quite a silly thing to do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e6deaf-68f5-e3c9-7259-775ed7662d85
* Version Independent ID: 82e6deaf-68f5-e3c9-7259-775ed7662d85
* Content: [Shared channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/shared-channels)
* Content Source: [Teams/shared-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/shared-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@sparkitect this is referring to the fact that shared channels will inherit the sensitivity label from the parent team if there is one. No relation to content types. I'll update the article to clarify.
