### ISSUE TITLE
Screenshot needs to be updated to show new store experience

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8999]
Screenshot needs to be updated to show new store experience
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a9e2a4f-0f02-d573-f3dc-692f4b75c581
* Version Independent ID: 38496171-4c3e-11a7-7676-f6b8f3666dd6
* Content: [Manage Microsoft Power Platform apps in the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/manage-power-platform-apps)
* Content Source: [Teams/manage-power-platform-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-power-platform-apps.md)
* Service: **msteams**
* GitHub Login: @guptaashish
* Microsoft Alias: **guptaashish**

**Comment by get-itips** [comment]
Screenshot was updated
