### ISSUE TITLE
Notifications Option not available in GCC Tenants

### ISSUE THREAD

**Issue by brianl1988** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9000]
Reviewing this documentation, there is no indication that GCC Tenants are not able to utilize this feature. Reviewing GCC Tenants though, this is not an option that has been made available, and was never planned for release for GCC High specifically. 

The Tenant I have reviewed is not GCC High, and was to be included on this back in June '21 release, however no release was ever performed for GCC.

Please update this document to reflect this accordingly for availability. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a627b5d-3edc-1add-b921-1dcd49c38653
* Version Independent ID: a2e2bd3a-31c0-471a-05fb-fd64bd942c4a
* Content: [Manage your devices in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/device-management)
* Content Source: [Teams/devices/device-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/device-management.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @brianl1988, thank you for your feedback.

I cannot find the word "notification" in this article. Could you highlight the section you are talking about?
