### ISSUE TITLE
Multi purpose rooms

### ISSUE THREAD

**Issue by randyhchapman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9001]
[Enter feedback here]

Your comparison says that multi-purpose rooms with 16+ people aren't available on MTRoA. But I'd argue with devices like Logitech RoomMate and eventually the Poly G7500 as standalone Android compute that you connect any camera and audio to, that they definitely tick the box. Multi-camera isn't yet supported on Android MTRs, but will be at some point. And complex audio is taken care of with alliances between the MTR OEM and 3rd parties such as Shure, Biamp and QSC. QSC also do multi-camera matrixes that can be connected to the RoomMate. In this regard, the standalone Android compute is no different to standalone Windows compute

So maybe change this from "not available" to "it depends".
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64cc650b-b313-cfab-9f45-190b94c128f4
* Version Independent ID: 9e93ac07-3f1b-9fd4-1907-17f0075bd837
* Content: [Teams devices for Shared Spaces feature comparison between Windows and Android - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/teams-devices-feature-comparison)
* Content Source: [Teams/rooms/teams-devices-feature-comparison.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/teams-devices-feature-comparison.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @randyhchapman Randy, I am looking into this

**Comment by dstrome** [comment]
Thanks for your feedback. We can't change this to available until multiple cameras are supported and dependent devices are certified.
