### ISSUE TITLE
Meetings Resent when licence removed - Missing Documentation

### ISSUE THREAD

**Issue by TaylorHassall** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9004]
When disabling the users Audio Conference licence it will normally send an email to say their settings have changed. You can disable this by following this documentation.

What this documentation lacks is to notify that if you remove the Audio Conference licence it will also re-send ALL the Meetings with Audio Conferencing turned on or dial in options enabled (All by default) with the same meeting but with no Conference/Dial in options. It doesn't affect accepted/declined status.

It documents this in the Meeting Migration Service, but, not in this documentation above. https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/setting-up-the-meeting-migration-service-mms 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0cd207e-eec4-11a5-9037-5d72a9ad5044
* Version Independent ID: b3757462-ceca-36ab-1b7a-8568a7481743
* Content: [Emails sent to users when their settings change - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/emails-sent-to-users-when-their-settings-change-in-teams#feedback)
* Content Source: [Teams/emails-sent-to-users-when-their-settings-change-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/emails-sent-to-users-when-their-settings-change-in-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hello @TaylorHassall 
I am trying to reproduce what you describe, I removed the license, the user already received the notification about this, but the scheduled meeting were not resent, I've waited one day.
Thanks for the feedback,

**Comment by TaylorHassall** [comment]
In our environment we had 700 users who had the Audio Conference. We removed this from 600 users. We noted that only 10-15 users had their meetings resent so perhaps it was something else they had setup in the Teams Meetings/Conference settings.

We noted the meetings that were resent were all originally sent with the Call/dial in option available. The only difference we noted was that the meetings that were re-sent were now missing this. Perhaps a red-herring.  The emails were re-sent after only approximately one hour of the licence removal. Will do more testing and investigate. 

According to the SFB this is how it should occur, just not quite well documented or presented in the Document noted above.

**Comment by get-itips** [comment]
Yes probably it was something else, I confirm I didn't receive anything and considerable time has passed.

**Comment by TaylorHassall** [comment]
Not sure at this point, nothing else was changed at the same time. We did reapply some licences. Perhaps try add them in your test environment and see if they change.

**Comment by lovenegotiation** [comment]
>> What this documentation lacks is to notify that if you remove the Audio Conference licence it will also re-send ALL the Meetings with Audio Conferencing turned on or dial in options enabled (All by default) with the same meeting but with no Conference/Dial in options.

We also experienced this behavior when **ADDING an Audio Conference license** to users, so that all previous ZOOM invitations were automatically resent with the added/new audio conference bridge number.
