### ISSUE TITLE
Missing in new Teams-admin interface?

### ISSUE THREAD

**Issue by ulflunqvist** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9005]
Is this missing in the new interface (Preview) per 2022-06-15? Can not find App policies anymore. Or is my admin roles spooking around?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f91604a-35b0-dfbb-55b2-b601cb0841b0
* Version Independent ID: 84bcd0d7-b4ed-f13e-c84b-2ec6a7661ae9
* Content: [Manage app setup policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-app-setup-policies)
* Content Source: [Teams/teams-app-setup-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-setup-policies.md)
* Service: **msteams**
* GitHub Login: @guptaashish
* Microsoft Alias: **guptaashish**

**Comment by dariomws** [comment]
Hi @ulflunqvist, thank you for your feedback.

I can see setup policies in the Teams Admin Center:
![image](https://user-images.githubusercontent.com/33589238/181254372-96193816-58d2-4c08-972c-493239b78714.png)

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by ashishguptaiitb** [comment]
Hello @dariomws and @scanum , do we need to keep the doc issue open and wait for further issues to be reported by @ulflunqvist or can we close it for now and rely that @ulflunqvist  will re-open as required?

**Comment by dariomws** [comment]
@ashishguptaiitb, we can close it and he'll be able to re-open it if needed.

@scanum, could you close it?

Thanks!
