### ISSUE TITLE
How to use Connect-MicrosoftTeams instead of the deprecated New-CSOnlineSession cmdlet? 

### ISSUE THREAD

**Issue by mwasham** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9009]
[Enter feedback here]

The article says to use Connect-MicrosoftTeams instead of New-CsOnlineSession.

I don't see any way of doing this - it would be great if the article would provide more details. 

When I try to use the return value of Connect-MicrosoftTeams with Import-PSSession I get the following:

Import-PSSession : Cannot bind parameter 'Session'. Cannot convert the "Microsoft.Open.Teams.CommonLibrary.PSAzureContext" value of type "Microsoft.Open.Teams.CommonLibrary.PSAzureContext" to type "System.Management.Automation.Runspaces.PSSession"

So our services are blocked due to a breaking change with no guidance.. appreciate an update. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c413445-e3d6-d6b8-4671-bd737bbdf130
* Version Independent ID: 8c413445-e3d6-d6b8-4671-bd737bbdf130
* Content: [Teams PowerShell Module - Supported Versions - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-supported-versions)
* Content Source: [Teams/teams-powershell-supported-versions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-supported-versions.md)
* Service: **msteams**
* GitHub Login: @pbafna03
* Microsoft Alias: **pbafna**

**Comment by pbafna03** [comment]
Hi @mwasham, 

Import-PSSession is not required with Connect-MicrosoftTeams.  You can directly run the cmdlets after Connect-MicrosoftTeams has completed. 

Few examples of the same are in https://docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps#example-2-connect-to-microsoftteams 

Thanks,

**Comment by mwasham** [comment]
Hmm - previously the only way to call the New-CsApplicationAccessPolicy  was after you imported the session from New-CSOnlineSession. 

After calling Connect-MicrosoftTeams I get:

New-CsApplicationAccessPolicy : The 'New-CsApplicationAccessPolicy' command was found in the module 'MicrosoftTeams', but the module could not be loaded.

I have updated the cmdlets and ran Import-Module MicrosoftTeams.

**Comment by mwasham** [comment]
Ahh never mind. I just realized I had an old version of MicrosoftTeams installed.

**Comment by pbafna03** [comment]
@mwasham - Yes, best to use the latest 4.x.x version.
