### ISSUE TITLE
No Teams Only option in Org-Wide or User level

### ISSUE THREAD

**Issue by WinArchitect** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#901]
I am the global administrator for two different organizations and when I access the Microsoft Teams & Skype for Business Admin Center and the Coexistence Mode in either Org-Wide  settings or on a User account, there is no Teams Only option. I have users that are ready to pilot the Teams Only mode to validate that all messages are re-directed to Teams but cannot configure them to do so.

Can you please inform me of when this will be available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffbf0bfd-c15e-b10b-0cc9-6a27ac1e6634
* Version Independent ID: 58575371-9e09-fadb-76f6-7491df8580a3
* Content: [Setting your coexistence and upgrade settings](https://docs.microsoft.com/en-us/microsoftteams/setting-your-coexistence-and-upgrade-settings)
* Content Source: [Teams/setting-your-coexistence-and-upgrade-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/setting-your-coexistence-and-upgrade-settings.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by MoochingTusk** [comment]
I have the same problem - no option to select teams only. I'd like to migrate a single user account to Teams as a test.

**Comment by mehetmet** [comment]
Same problem here, was just investigating this but only have the option for Islands of Skype for Business Only

**Comment by kenwith** [comment]
@bjwhalen is the product owner that owns this feature.. can you provide guidance BJ?  @bjwhalen - let me know if there is something I can help with regarding the doc.

**Comment by bjwhalen** [comment]
TeamsOnly mode can be granted via powershell to either users or entire tenant. see this url:
https://docs.microsoft.com/en-us/powershell/module/skype/grant-csteamsupgradepolicy?view=skype-ps

it is not yet broadly avail in Admin UX because there are a few items we need to resolve before we are ready to make it broadly avail. But for piloting it's fine.

**Comment by kenwith** [comment]
Thanks for info BJ! I am going to close this unless anyone has another issue to bring up. @AndreaBarr - would you please create a Bug in the backlog for Skype team to add this info BJ provided above to the doc in question.. we can add it as a note so it is clear this should be done through PowerShell for now.

**Comment by AndreaBarr** [comment]
@kenwith I have added it to the backlog

**Comment by bjwhalen** [comment]
why is this opened? Teams only is avail in the portal now.

**Comment by kenwith** [comment]
We must have had a coordinating VSO item that was open. We closed that one and will close this one again now too. Sorry for confusion.
