### ISSUE TITLE
Audio Conferencing page detail requested

### ISSUE THREAD

**Issue by BrissyScott** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9015]
I am having to research whether my client is ready for Audio Conferencing in teams and came to this page. I was looking for the addin license required and I was unable to find it on this page. I belive the license required is called Microsoft 365 Audio Conferencing. I would be nice to have that information available on this page. 

Regards
Scott T

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abae7324-861d-7ca7-7239-a5df8fd927d5
* Version Independent ID: 8a30bd2f-9bc3-a0a8-8b31-d53836ead4d0
* Content: [Microsoft Teams add-on licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing)
* Content Source: [Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @BrissyScott, thank you for your feedback.

You're right, you will find the Audio Conferencing add-on as "Microsoft 365 Audio Conferencing" in the Microsoft 365 Admin Center.
