### ISSUE TITLE
How to hide apps from store 

### ISSUE THREAD

**Issue by h2yildirim** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9017]
Great document, but it does not says in a clear way how to hide apps from the store so users  won't see it. disabeling is clear but hiding is not..  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbcabee-fa96-2878-e983-3c966f84ee15
* Version Independent ID: 02fa4fd8-77e0-5cb2-a4af-576cbb68322f
* Content: [Manage your apps in the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/manage-apps)
* Content Source: [Teams/manage-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-apps.md)
* Service: **msteams**
* GitHub Login: @guptaashish
* Microsoft Alias: **guptaashish**

**Comment by ndambrosio** [comment]
Going forward the ability to hide apps in the store will not be possible, they can be blocked, but they will still be visible.  This change has been communicated via Message Center (MC350372) and the Microsoft 365 Roadmap ID 84469

**Comment by ashishguptaiitb** [comment]
Closing this issue as answered. Worth calling out that even though end-users can see the apps but admins retain complete control of which users have access to what apps. Also, the controls remain the same.

The only change is that,
* Blocked apps are visible to end-users. 
* End-users can request admin approval but admins decide to either act on it or ignore it. More info at https://learn.microsoft.com/en-us/microsoftteams/user-requests-approve-apps.
