### ISSUE TITLE
Are Teams Meetings Transcripts eDiscoverable?

### ISSUE THREAD

**Issue by ericsteimel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9018]
[Enter feedback here]

Can you add Transcriptions to the table showing what is/is not discoverable? Its unclear if 1) Transcriptions are automatically generated for all teams meetings (vs for just when they are enabled by user or if meeting is recorded) or 2) if a transcription is created, is it discoverable or just searchable by the owner of the meeting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 840dd36b-8c29-9738-4adc-ea9a7d277fd0
* Version Independent ID: b12c43c3-ed81-ace5-dfeb-77cac0f97fe9
* Content: [Conduct an eDiscovery investigation of content - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/ediscovery-investigation)
* Content Source: [Teams/eDiscovery-investigation.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/eDiscovery-investigation.md)
* Service: **msteams**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by dariomws** [comment]
Hi @ericsteimel, thank you for your feedback.

Only meeting IM conversations and metadata is eDiscoverable at the moment. The initial release of Meeting Transcription did not support applying retention policies, eDiscovery, or legal hold. As a result, the lifecycle of meeting transcripts will depend on manual management by the meeting organizers.

**Comment by ericsteimel** [comment]
Thanks for the confirmation. Can you add this to the documentation (table) so I can refer to it later once this feature is added? (Transcriptions are missing from the table). Thanks.

**Comment by dariomws** [comment]
@ericsteimel, transcriptions are available during meetings, and the article includes the eDiscoverable features for meetings. Other features not included in the table, like meeting transcriptions, are not eDiscoverable.

**Comment by ericsteimel** [comment]
Hi Dario, I understand. My request was to add this as a "no" item under the table so its clear that transcripts are not eDiscoverable. (i spent a fair amount of time trying to find this information in your documentation and it was not clearly documented).
