### ISSUE TITLE
Self referential link for MAC reporting? 

### ISSUE THREAD

**Issue by ashishguptaiitb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9025]
The link [Teams activity reports in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/microsoftteams/teams-activity-reports) now redirects so has become self-referential. See if there's a new article that replaces the old one or else remove this link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ade1a4-092c-1132-44df-ee2c683fdd33
* Version Independent ID: 396b1aee-2f40-9895-9b00-07e38d11d31b
* Content: [Microsoft Teams analytics and reporting - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-reporting-reference)
* Content Source: [Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by lindspea** [comment]
@ashishguptaiitb thank you for reaching out and helping to improve Microsoft Docs. Would this be the correct link to add here? https://docs.microsoft.com/microsoft-365/admin/activity-reports/activity-reports?view=o365-worldwide

**Comment by ashishguptaiitb** [comment]
> Would this be the correct link to add here? https://docs.microsoft.com/microsoft-365/admin/activity-reports/activity-reports?view=o365-worldwide

Hello @lindspea , allow me to suggest that you reach out to @SerdarSoysal for accurate info on what the new destination should be.

**Comment by lindspea** [comment]
@tiburd

**Comment by tiburd** [comment]
Thanks, all! I merged the PR. Closing this issue.
