### ISSUE TITLE
Pricing???

### ISSUE THREAD

**Issue by actcanshr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9026]
[Enter feedback here]
I'm looking for pricing for using Teams phones for a nonprofit based in Ottawa, ON Canada. Ottawa is the capital of Canada, but is not listed on your "list of capitals and major cities" (but Winnipeg is)?? 

I've clicked through about five pages of content about phones (is it Teams Calling or Skype for Business??) what is the client software?? how much will it cost?? and will it be useful for my organization?? and am no wiser. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae54019f-73df-4e8a-be75-3310fd585a61
* Version Independent ID: 581970cc-d568-b626-2895-3a66ee934f57
* Content: [Availability in Canada - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-canada)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-canada.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-canada.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
