### ISSUE TITLE
Download links are out of date.

### ISSUE THREAD

**Issue by trojmn** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9028]
[Enter feedback here]
under
"Download the Teams MSI package that matches your VDI VM operating system using one of the following links:"

at this time link to:
https://statics.teams.cdn.office.net/production-windows/1.5.00.11865/Teams_windows.msi
https://statics.teams.cdn.office.net/production-windows-x64/1.5.00.11865/Teams_windows_x64.msi

I know there are at least two newer builds available for download.  Is this page intended to be source of the current production build of Teams for VDI?   Is it that any build of Teams can be used for VDI installations and this page is not intended to be the source specific for VDI installations?   Where/how can customers get the latest versions of teams for use in a VDI environment? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by lindspea** [comment]
@trojmn thank you for reaching out. Please see https://techcommunity.microsoft.com/t5/microsoft-teams/update-of-msi-download/m-p/2465905. I'm checking to see which version needs to be updated here. If you have any more information please let me know. In the meantime I'll do some more investigating.
