### ISSUE TITLE
Checking for directions to block guest users on custom app/BOT

### ISSUE THREAD

**Issue by Wazid20** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9029]
Greetings,
I see statement "To avoid guest from accessing bots, you can create more app setup policies, assign them to internal users, and install bots with the custom policies." on this page. 
Can you help us with directions how to block access for guest users on custom app/bot?
Thankyou!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0735d322-f6f5-7cc8-9994-1420e3fb7baa
* Version Independent ID: f9b25b51-eb9c-63fa-b30e-e1490c8d31b6
* Content: [Teams apps behavior based on types of users - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/non-standard-users)
* Content Source: [Teams/non-standard-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/non-standard-users.md)
* Service: **msteams**
* GitHub Login: @guptaashish
* Microsoft Alias: **guptaashish**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
