### ISSUE TITLE
Phone System is NOT required to make a federated call

### ISSUE THREAD

**Issue by dinocaputo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9030]
[Enter feedback here]

This is incorrect statement:

"Federated calling | Lets users securely connect, communicate, and collaborate with users in federated tenants."

You do NOT need a Phone System License to make a federated call.  This can be done with any Teams license without a Phone System add on/license from the Chat Application.  

Kindly remove this statement.  

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cfead3c-b0d8-c22a-aa22-63e79fe53ed3
* Version Independent ID: 10745875-3d3e-42bb-e324-ff4c83968ccf
* Content: [Here's what you get with Phone System - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/here-s-what-you-get-with-phone-system)
* Content Source: [Teams/here-s-what-you-get-with-phone-system.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/here-s-what-you-get-with-phone-system.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Thanks for your feedback, Dino.  I am working with the primary voice PM on this article.  The article is pointing out that these features are available with Phone System--not necessarily exclusive to Phone System.  I am discussing with the voice PM how best to distinguish the differences.  To the PubOps team, please do not make any changes to this article.  I am working with the PM on how best to handle.  I will close this issue as this discussion in happening internally.
