### ISSUE TITLE
Phone System Virtual User license has been renamed to Microsoft Teams Phone Resource Account

### ISSUE THREAD

**Issue by joelulrich** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9033]
Phone System Virtual User license has been renamed to Microsoft Teams Phone Resource Account, references need to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b755d9ae-13ac-019f-f5f4-a95b1eee2989
* Version Independent ID: f7afd8ad-e6e0-6c79-aed1-4ee87d48ba12
* Content: [Create a call queue in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue?tabs=general-info)
* Content Source: [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-call-queue.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by DaniEASmith** [comment]
Hello! I am actively working on updating our articles to reflect the license name change. The updated docs should be published within in the week.

**Comment by shivtorov** [comment]
Also, some articles in [MicrosoftDocs/office-docs-powershell](https://github.com/MicrosoftDocs/office-docs-powershell) repo needs this license name updated.

Content articles:

- [New-CsTeamsUnassignedNumberTreatment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md)
- [Set-CsTeamsUnassignedNumberTreatment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsTeamsUnassignedNumberTreatment.md)

**Comment by DaniEASmith** [comment]
@shivtorov I have most of the docs updated in my PR; however, I can't update the PowerShell docs as those aren't owned by our team.

**Comment by DaniEASmith** [comment]
@shivtorov & @joelulrich 
Here is the approved/merged PR with the updates: 
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/pull/9841.

The updated versions will publish today around 11 am PST.

The PowerShell docs have also been updated and will publish today around 11 am PST too.
