### ISSUE TITLE
Inconsistent value for max number of users assigned to a tag

### ISSUE THREAD

**Issue by ploete** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9034]
This article specifies a max number of 100 members assigned to a tag, while this article (https://docs.microsoft.com/en-us/microsoftteams/manage-tags) specifies 200. Which one is the correct value?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Thanks for your feedback, proposing to update the article
