### ISSUE TITLE
Client reset not supported (know issue)

### ISSUE THREAD

**Issue by adrianfleisch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9036]
May is should be documented, that it is not supported that the Teams Client cloud not be restarted during an internet outage or you can not start (like starting work in the morning) your Teams Client during an internet outage (even if you in the 24 hours token time)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 183fc921-e9b1-cc74-2bcb-26d32b994919
* Version Independent ID: 1765bda3-dd62-76d7-1e2d-9f5496ac9094
* Content: [Direct Routing SBA - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-survivable-branch-appliance)
* Content Source: [Teams/direct-routing-survivable-branch-appliance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-survivable-branch-appliance.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Thanks for sharing your point of view @adrianfleisch I'll analyze this to see if an update to the article is required.

**Comment by get-itips** [comment]
Hello @adrianfleisch 

> From what I've heard it was working about 1 month ago and now it's not working due to a client authentication change.

Do you have more details around this? I managed to ask the team and they are not aware of any recent change, thanks

**Comment by get-itips** [comment]
Hello @adrianfleisch could you see my last comment here? Thanks

**Comment by get-itips** [comment]
Closing for now, and it can be re-opened. @scanum
