### ISSUE TITLE
Is this still in preview?

### ISSUE THREAD

**Issue by daargued** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9044]
[Is this still in preview?? The roadmap show feedback policies are GA already]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bf3bc26-4cac-56c0-8669-6540adf3c502
* Version Independent ID: bd7cd483-e40e-88c2-b9ee-b21a9ea73005
* Content: [Manage feedback policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-feedback-policies-in-teams)
* Content Source: [Teams/manage-feedback-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-feedback-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @daargued I can't seem to find the roadmap item, can you share it? thank you

**Comment by get-itips** [comment]
Hello @daargued could you see my last comment? Thanks

**Comment by daargued** [comment]
> Hello @daargued could you see my last comment? Thanks

@get-itips, sorry, had some difficulty to find the item as well, I believe this is the entry:

https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=84004
