### ISSUE TITLE
Suggest missing Logitech Brio 4K Webcam

### ISSUE THREAD

**Issue by chdurand** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9047]
[Enter feedback here]
According to this page the device is certified.
https://www.microsoft.com/en-us/microsoft-teams/across-devices/devices/product/logitech-brio-4k-webcam/37
Please review and add.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b118e0a7-1fef-feae-6c6d-e24c4485a5b9
* Version Independent ID: ae18e2db-fbbf-f30c-3c56-17dd0d2b85d1
* Content: [Phones and Devices for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/usb-devices#certified-devices)
* Content Source: [Teams/devices/usb-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/usb-devices.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dstrome** [comment]
hi @chdurand - I spoke with our device certification team and confirmed the Logitech BRIO is not Teams certified. It is, however, certified for Skype for Business.

Our team is reaching out to Logitech to clarify this in their documentation and device specifications.
