### ISSUE TITLE
TMR Expiration Date Default Value - 120 days? 60 days?

### ISSUE THREAD

**Issue by shtakeda** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9048]
The docs says that the default value is 120 days. But, the blog says 60 days, and the default value on my tenant is 60 days, too. Which is correct?

Docs:
All newly created Teams meeting recordings (TMRs) will have a default expiration of 120 days.
Blog:
New recordings will automatically expire 60 days
https://techcommunity.microsoft.com/t5/microsoft-teams-blog/how-to-manage-microsoft-teams-meeting-recording-auto-expiration/ba-p/3053035

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee6d4c1c-6f16-b1a4-c4a9-be4e6d1f95b7
* Version Independent ID: 50ad835d-ed7f-18c6-34ba-322c1574f9c2
* Content: [Meeting policies and meeting expiration in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-expiration)
* Content Source: [Teams/meeting-expiration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-expiration.md)
* Service: **msteams**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by get-itips** [comment]
Hello @shtakeda 

Please see Message Center Id MC274188

>For any tenant that does not have a custom policy in place already, we are updating the default expiration days from 60 to 120 days.

**Comment by get-itips** [comment]
@scanum
