### ISSUE TITLE
UDP ports usage

### ISSUE THREAD

**Issue by TheITguy666** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9049]
The information might be outdated.
I have customer tenants with QoS disabled, but I can see on the meeting clients network traffic the UDP ports 3478-3481 in use...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Manage meeting settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams#set-how-you-want-to-handle-real-time-media-traffic-for-teams-meetings)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @TheITguy666 Luis, I am sorry, I am not sure I understand, those ports are required https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide
Let me know if I understood you correctly,

**Comment by TheITguy666** [comment]
Sorry @get-itips 
I open this on the wrong page :(
