### ISSUE TITLE
Enterprise Architect

### ISSUE THREAD

**Issue by paul-jensen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#905]
The Aruba models listed above are all older models. Newer models (eg. 310 series) need to be certified and added to this list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba1c5bd5-da94-25ac-4d42-d2573235fa84
* Version Independent ID: cda59715-81fe-8e04-13b7-03fa269d12e1
* Content: [Skype for Business - Networking Wi-Fi](https://docs.microsoft.com/en-us/skypeforbusiness/certification/networking-wifi)
* Content Source: [Skype/SfbPartnerCertification/certification/networking-wifi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbPartnerCertification/certification/networking-wifi.md)
* Service: **skype-for-business**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by dougand-MSFT** [comment]
@paul-jensen this page reflects certifications that have been completed. Currently the Wi-Fi networking certification is no longer active, therefore newer models will not be added to the page.

**Comment by yogkumgit** [comment]
@dougand  Thank you very much for the contribution and sharing this explanation. @paul-jensen  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
