### ISSUE TITLE
cgroups

### ISSUE THREAD

**Issue by gwm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9050]
This memory management regime does not seem to work when using cgroups to impose memory quotas on shared login environments. We limit each user to 12GB on our remote access platform and that stops any Electron application from starting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc21902c-d522-3851-8587-177f01bc085c
* Version Independent ID: 590bcc64-a86d-b61e-7d94-4e4322c4e71d
* Content: [How Microsoft Teams uses memory - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-memory-usage-perf)
* Content Source: [Teams/teams-memory-usage-perf.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-memory-usage-perf.md)
* Service: **msteams**
* GitHub Login: @msdmaguire
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
@scanum
