### ISSUE TITLE
Incorrect statement - dial in to check voicemail 

### ISSUE THREAD

**Issue by NickElniff** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9051]
[Enter feedback here]

The document has a statement that is incorrect "When you enable protected voicemail, users can listen to protected voicemail messages by calling into their voicemail mailbox or by opening the message in Outlook, Outlook on the web, or Outlook for Android or iOS."

This capability to dialing to listen to your voicemail is not available. It was deprecated when Exchange Online Unified Messaging went end of life.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8228f9b2-a7de-abb4-6f41-70db0b3af155
* Version Independent ID: 8fd9fafb-dd76-59a8-e609-56f06d539a31
* Content: [Set up Cloud Voicemail - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-phone-system-voicemail#enable-protected-voicemail-in-your-organization)
* Content Source: [Teams/set-up-phone-system-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-phone-system-voicemail.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by JensTrier** [comment]
@NickElniff thanks for the feedback. I'll fix it.

**Comment by JensTrier** [comment]
This has been fixed now. Feel free to close this item

**Comment by NickElniff** [comment]
Thanks @JensTrier :)
