### ISSUE TITLE
Change name of the App

### ISSUE THREAD

**Issue by ToddOmya** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9055]
Please change the name of this application, A new app that is enabled by default with a generic name that is impossible to search for when troubleshooting or looking for information is very frustrating. Please consider renaming this app to something searchable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c19d4972-fa39-2908-c33c-f7e1a84d06c5
* Version Independent ID: c19d4972-fa39-2908-c33c-f7e1a84d06c5
* Content: [Manage the Updates app for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-updates-app)
* Content Source: [Teams/manage-updates-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-updates-app.md)
* Service: **msteams**
* GitHub Login: @daisyfell
* Microsoft Alias: **daisyfeller**

**Comment by scanum** [comment]
@ToddOmya I know the product teams are always looking for user feedback and how to make SharePoint better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice 
SharePoint: https://sharepoint.uservoice.com/.
Skype for Business: https://www.skypefeedback.com/.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.
Thank you for your contribution to make the docs better! Much appreciated!
