### ISSUE TITLE
Azure IP Ranges and Service Tags  for Teams Direct Routing workloads

### ISSUE THREAD

**Issue by Balamurugan-dot** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9059]
Customer is working on deploying SBA by this documentation and this one mentions the below as part of the prerequisites: 

Azure IP Ranges and Service Tags for the Public Cloud should be defined according to the guidelines described at: https://www.microsoft.com/download/details.aspx?id=56519

However, it looks vague for Teams Direct routing workloads. 
Can someone help  which specific service tags or IP ranges should be considered for Teams Direct routing workloads?

Many thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 183fc921-e9b1-cc74-2bcb-26d32b994919
* Version Independent ID: 1765bda3-dd62-76d7-1e2d-9f5496ac9094
* Content: [Direct Routing SBA - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-survivable-branch-appliance)
* Content Source: [Teams/direct-routing-survivable-branch-appliance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-survivable-branch-appliance.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @Balamurugan-dot I am looking into this.

**Comment by get-itips** [comment]
Hello @Balamurugan-dot 
I managed to get an answer from the team, and all the azure ip ranges and service tags need to be considered at the moment.
Thanks!
