### ISSUE TITLE
New name for this license > This page needs some updates

### ISSUE THREAD

**Issue by LaureVDH** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9060]
The new name of the license is Microsoft365 Phone Resource Account. If you search for Virtual User, you won't find anything.
It's a quick one to update and will serve lots of admins.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6891495-01c6-117b-c28b-28232782ba74
* Version Independent ID: 1c23b35a-e9ba-ffdd-9baa-a3f83f4ed9ca
* Content: [Microsoft Teams Phone Standard – Virtual User licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/virtual-user)
* Content Source: [Teams/teams-add-on-licensing/virtual-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/virtual-user.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome*

**Comment by shivtorov** [comment]
In all my tenants the current name of this license is "Microsoft Teams Phone Resource Account"

In this repo, we can see all sorts of naming variants for this license:

- Microsoft 365 Phone System – Virtual User
- Microsoft Phone System - Virtual User
- Microsoft Teams Phone Standard – Virtual User
- Microsoft Teams Phone System - Virtual User
- Microsoft Teams Phone System Virtual User
- Phone System - Virtual User
- Phone System Virtual User
- Phone System–Virtual User
- Teams Phone Standard - Virtual User
- Teams Phone Standard – Virtual User
- Virtual User

All these license names should be replaced with a consistent name.

Content articles:

- [Skype/SfbHybrid/hybrid/configure-onprem-ra.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-onprem-ra.md)
- [Skype/SfbHybrid/hybrid/plan-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/plan-call-queue.md)
- [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-call-queue.md)
- [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
- [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
- [Teams/plan-auto-attendant-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-auto-attendant-call-queue.md)
- [Teams/routing-calls-to-unassigned-numbers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/routing-calls-to-unassigned-numbers.md)
- [Teams/toc.yml](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/toc.yml)
- [Teams/voice-case-study-call-queues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/voice-case-study-call-queues.md)
- [Teams/includes/create-call-queue-steps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/includes/create-call-queue-steps.md)
- [Teams/includes/set-up-resource-account-steps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/includes/set-up-resource-account-steps.md)
- [Teams/teams-add-on-licensing/virtual-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/virtual-user.md)

CC: @get-itips, @scanum

**Comment by DaniEASmith** [comment]
@shivtorov & @LaureVDH 
Here is the approved/merged PR with the updates:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/pull/9841.

The updated versions will publish today around 11 am PST.

The PowerShell docs have also been updated and will publish today around 11 am PST too.

**Comment by get-itips** [comment]
@scanum
