### ISSUE TITLE
Impact of GroupSetting AllowToAddGuests on Shared Channels

### ISSUE THREAD

**Issue by J-a-k-o-b** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9062]
The M365 Group Setting "AllowToAddGuests" (e.g. configurable via Graph: https://docs.microsoft.com/en-us/graph/api/groupsetting-update?view=graph-rest-1.0&tabs=http) has impact on the Shared Channels sharing possibilities. The Setting should manage the ability to add new guest to a team. But with this setting set to 'false' in the overlying group, you can not add external contacts to your shared channel. This should not be the case because shared channels do not make use of guests.

**Comment by dariomws** [comment]
@J-a-k-o-b, thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by J-a-k-o-b** [comment]
Hi,
meanwhile, the Case I've opened (#32350133) was closed with reference to the docs article:

https://docs.microsoft.com/en-us/microsoft-365/solutions/collaborate-teams-direct-connect?view=o365-worldwide
![image](https://user-images.githubusercontent.com/46894290/188381862-2aa5ae83-748e-42a8-a348-f9403491bc74.png)

I assume that the note was added recently. For me it is not straight forward to manage the ability to add external participants with this guest switch because that external participants are not guests at all...

**Comment by dariomws** [comment]
@J-a-k-o-b, thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make Microsoft products better. They keep a close tab on user feedback and it would be awesome if you could add your voice to the Microsoft Feedback Portal: https://feedbackportal.microsoft.com/feedback/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to making the docs better! Much appreciated!

**Comment by J-a-k-o-b** [comment]
for those who want to support the uservoice:

https://feedbackportal.microsoft.com/feedback/idea/6063f8c6-4a33-ed11-a81b-000d3a7dd504
