### ISSUE TITLE
Option en ligne de commande ALLUSER ou ALLUSERS ?

### ISSUE THREAD

**Issue by GowaP** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9068]
[Enter feedback here]
En regardant avec ORCA les paramètres possible, il semblerait que ce soit ALLUSER=1 qu'il faut utiliser.

Je note aussi qu'il n'y a toujours pas d'option pour ne pas avoir de raccourci sur le bureau.
Merci d'ajouter l'option "NODESKTOPSHORTCUP=1" ou quelque chose comme cela.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Bulk install Teams using Windows Installer (MSI) - Microsoft Teams](https://docs.microsoft.com/en-gb/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
