### ISSUE TITLE
Missing fields

### ISSUE THREAD

**Issue by Justinoficomm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9069]
[Need to add custom backgrounds to this table]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64cc650b-b313-cfab-9f45-190b94c128f4
* Version Independent ID: 9e93ac07-3f1b-9fd4-1907-17f0075bd837
* Content: [Teams devices for Shared Spaces feature comparison between Windows and Android - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/teams-devices-feature-comparison)
* Content Source: [Teams/rooms/teams-devices-feature-comparison.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/teams-devices-feature-comparison.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @Justinoficomm 
How are you? Do you refer to meeting backgrounds?
Thanks for clarification,

**Comment by Justinoficomm** [comment]
Hello Andres,

I am refrerring to Theme's for MTR's whilst not in a meeting. Currently you can have a custom theme on MTRoW but only specific Theme's on MTRoA.




Justin O'Meara
Unified Communications Consultant
T: +613 9348 5009 | M: +61 438 760 327
E: ***@***.***
A: 387 Flemington Road
North Melbourne, VIC  
3051
icomm.com.au

**Comment by scanum** [comment]
Hi @dstrome Hope all is well. Checking if there is an update on this issue? Thanks.

**Comment by scanum** [comment]
Hi @dstrome Hope all is well. Checking if there is an update on this issue? Thanks.
