### ISSUE TITLE
attendance report

### ISSUE THREAD

**Issue by erni19** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9071]
Please rectify the article:

"Only meeting organizers and co-organizers can view and download attendance reports." 

https://support.microsoft.com/en-us/office/view-and-download-meeting-attendance-reports-in-teams-ae7cf170-530c-47d3-84c1-3aedac74d310

It contradicts this one: 

https://support.microsoft.com/en-us/office/add-co-organizers-to-a-meeting-in-teams-0de2c31c-8207-47ff-ae2a-fc1792d466e2

**Comment by dariomws** [comment]
Hi @erni19, thank you for your feedback.

I couldn't find any mention of meeting reports in the second article. Anyway, here we are limited to docs.microsoft.com issues and improvements. We cannot update support.microsoft.com articles.

**Comment by erni19** [comment]
It has changed... Would you know where to submit feedback about support.microsoft.com articles? Thank you

**Comment by dariomws** [comment]
@erni19, I think the best way is by contacting support.

![image](https://user-images.githubusercontent.com/33589238/183370154-81f75086-86f4-42f9-871c-c57ee223c2dd.png)
