### ISSUE TITLE
Please link to TAC

### ISSUE THREAD

**Issue by prkosh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9075]
[Enter feedback here]
Could you link to TAC from this page? I see many references to TAC - please link back

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e2745e9-5876-8469-7152-6d63a14f42e0
* Version Independent ID: 5e2745e9-5876-8469-7152-6d63a14f42e0
* Content: [Overview of app certification by Microsoft - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/overview-of-app-certification)
* Content Source: [Teams/overview-of-app-certification.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/overview-of-app-certification.md)
* Service: **msteams**
* GitHub Login: @guptaashish
* Microsoft Alias: **guptaashish**

**Comment by get-itips** [comment]
Document has been updated.
