### ISSUE TITLE
live event fuction dettails

### ISSUE THREAD

**Issue by Sax84** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9076]
[Enter feedback here]
can you provide more details on MTR live event?

Many thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64cc650b-b313-cfab-9f45-190b94c128f4
* Version Independent ID: 9e93ac07-3f1b-9fd4-1907-17f0075bd837
* Content: [Teams devices for Shared Spaces feature comparison between Windows and Android - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/teams-devices-feature-comparison)
* Content Source: [Teams/rooms/teams-devices-feature-comparison.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/teams-devices-feature-comparison.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @Sax84 
As far as I know it is not yet possible to join a live event from a MTR device.

**Comment by get-itips** [comment]
@scanum

**Comment by Sax84** [comment]
Hi!
I have done some test. You can Join Live Event from MTRoW as Presenter. On MTRoA it's not yet possible.

**Comment by get-itips** [comment]
Hello @Sax84 It seems indeed that you can from MTRoW.
