### ISSUE TITLE
Chat in meetings

### ISSUE THREAD

**Issue by thewrabbit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9077]
(https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-participants-and-guests#chat-in-meetings)

This is listed as a per user setting.

This is true for user's in the tenancy but as this parameter also applies to anonymous users it based on the meeting organizer's policy it should also be listed as per organizer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4521de2b-1aae-93de-ee1a-222146194700
* Version Independent ID: b4f9087c-e1a3-8b47-917c-7c294d46fcca
* Content: [Manage meeting policies for participants and guests - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-participants-and-guests#chat-in-meetings)
* Content Source: [Teams/meeting-policies-participants-and-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-participants-and-guests.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @thewrabbit 

I did some tests, and I believe this is both a per participant and per organizer policy depending from the point of view.

For example, if a user that has _Turn it off for everyone_ joins a meeting where the organizer has _Turn it on for everyone_ it will not access the meeting chat.

If the same user organizes a meeting, meeting participants, regardless of its own setting, will not access the meeting chat. (even anonymous users).

If an organizer that has _Turn it on for everyone_ invites an anonymous user, the anonymous user will be able to access the chat.

Is this what you have experienced?

Thanks

**Comment by thewrabbit** [comment]
Yes that's what I expect.

The most restrictive policy applies.

If the organizer has meeting chat disabled then no-one will be able to chat.
If the organizer has meeting chat enabled then the participant policy applies - if they are anonymous they will be able to chat, if they are a tenancy user and have meeting chat disabled they won't be able to chat.
If the organizer has meeting chat enabled except for anonymous - if they are anonymous then they won't be able to chat, if they are a tenancy user it depends on their individual policy (disabled=no chat, enabled = chat).

And regardless of the settings the chat is visible to all users - the only impact is their ability to contribute to it.

So it is both a per organizer and a per user setting.  The support article has it listed only as a per user setting.

**Comment by get-itips** [comment]
An update is coming to the article.

**Comment by get-itips** [comment]
The article has been updated thanks to your feedback!

**Comment by jonnyc109** [comment]
There's still errors in this section.
In the table, the 2nd setting value should be "OFF" for everyone based on the behavior description.
The first bullet under examples says:
"If the organizer has Chat in meetings set to On for everyone or On for everyone but anonymous users, then a user's individual policy will apply and any users with On for everyone set won't be able to chat in the meeting."
 
I think this is wrong and it should say ...."any users with Off for everyone set won't be able to chat in the meeting"

The second bullet seems to be wrong as well:
"If the organizer has Chat in meetings set to On for everyone, the organizer's policy applies and no one will be able to chat in the meeting."
Shouldn't that read "If the organizer has Chat in meetings set to OFF for everyone...."?

Why would no one be able to chat if they organizer has it set to On for everyone.

**Comment by thewrabbit** [comment]
@jonnyc109 completely agree - they've changed it since they fixed it in August last.  I didn't trawl through the edit history to find out when.  As this is closed you might be better raising a new issue.
