### ISSUE TITLE
Windows Firewall

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#908]
In my experience two Windows Firewall rules called "teams.exe" to ALLOW, not BLOCK as documented here, both TCP and UDP for the program.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by vination** [comment]
Any updates on this? We are trying to deploy this in a enterprise environment with 500+ employees and been placed on hold until this is fixed due to this behavior when we deployed it to a test group of 50 employees.

**Comment by vination** [comment]
Thanks for providing a Powershell script, however that opens a new can of worms. By default remote and local Powershell execution is disabled, unless explicitly enabling it via GPOs. It is disabled by default for a reason, and allowing this can potentially allow any malicious Powershell scripts to run on all PCs.

**Comment by vination** [comment]
Further to this, in the Powershell script provided the cmdlet "Get-NetFirewallRule" does not exist for Windows 7 computers. This should be stated in the script to avoid confusion.

**Comment by AndreaBarr** [comment]
@cliffhobbs can you please address this issue?

**Comment by StephanGee** [comment]
I rewrote the powershell to address redirected userprofiles (some ppl use that) and that does not run when powershell version is less then 3.

If ($PSVersionTable.PSVersion.Major -le 2)
    {
        Write-Host "PowerShell Version lower than 3. Stopping Script"
    }
Else
    {
    $currentuserdir = $env:USERPROFILE
    $usersdir = $currentuserdir -replace $env:USERNAME,""
    $users = Get-Childitem $usersdir
    foreach ($user in $users) 
    {
        $Path = $usersdir + $user.Name + "\appdata\local\Microsoft\Teams\Current\Teams.exe"
        if (Test-Path $Path) 
	    {
	            $name = "Inbound teams.exe " + $user.Name
	            if (!(Get-NetFirewallRule -DisplayName $name))
		    {
	                New-NetFirewallRule -DisplayName $name -Direction Inbound -Profile Domain -Program $Path -Action Allow
		    }
	    }
    }    
    }

**Comment by yogkumgit** [comment]
@juanand  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link https://www.youtube.com/watch?v=puuOy0sEg1Y
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with your valuable piece of information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
