### ISSUE TITLE
Unsuported cmdlet

### ISSUE THREAD

**Issue by rramoscabral** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9080]
https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-auto-attendant-via-cmdlets

Get-CsOnlineTelephoneNumber : This cmdlet is no longer supported

> From https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps
> Note: This cmdlet will be deprecated. Use the new [Get-CsPhoneNumberAssignment](https://docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment) cmdlet instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts#assign-a-service-number)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by JensTrier** [comment]
@rramoscabral thanks for the feedback. I'll change it. Feel free to close this issue.

**Comment by rramoscabral** [comment]
@JensTrier  thank for the info :)
