### ISSUE TITLE
Document how to delete LOB apps from store

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9083]
Im looking for this info and couldn't find it. We docyment how to upload and how to update, butnot how to delete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 632a367f-0c30-fc21-5040-d2d80f184bdb
* Version Independent ID: 6cab37af-6dcf-d2c1-3d68-14fc7375f1f5
* Content: [Upload your custom apps in the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/upload-custom-apps)
* Content Source: [Teams/upload-custom-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upload-custom-apps.md)
* Service: **msteams**
* GitHub Login: @guptaashish
* Microsoft Alias: **guptaashish**

**Comment by get-itips** [comment]
Thanks for your feedback, I'll propose to add that to the article

**Comment by get-itips** [comment]
Document has been updated.
