### ISSUE TITLE
MSI installer - Users not able to manually launch Teams app

### ISSUE THREAD

**Issue by pedaleo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#909]
Hello
The default MSI installer install and auto-start the application which is okay but there's no built-in option for a user to manually launch Teams app in case the user decide to "Quit" Teams from the system tray Or disable the auto-start option; there's no shortcuts on the desktop and can't be found when is searched in the start menu.  

I experienced this issue with the MSI installer version 1.1.00.25457 in Win10 1709 and 1803. Alternatively with the "normal" exe installer seems okay, the user can search and find "Teams" in the start menu.

Apologies if this has been asked before.

![image](https://user-images.githubusercontent.com/44213366/47048611-368ac400-d19b-11e8-8cba-71a9a8ea4c66.png)
![image](https://user-images.githubusercontent.com/44213366/47048875-f7a93e00-d19b-11e8-9c37-d89ea8ad7fd2.png)

**Comment by AndreaBarr** [comment]
@pedaleo Thank you for this feedback

I want to make sure that your users are able to manually launch Teams. We need to get you over to Support. They have more resources to dig into this and figure out what's going on. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
