### ISSUE TITLE
RAM Requirements

### ISSUE THREAD

**Issue by bteams1221** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9090]
The RAM requirements for Teams, is this for Teams itself or for the entire PC?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29a61ff5-b3a5-158d-149a-dec344060e05
* Version Independent ID: 97fac351-a283-aaa8-cde1-fbd9cf4e8504
* Content: [Hardware requirements for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/hardware-requirements-for-the-teams-app)
* Content Source: [Teams/hardware-requirements-for-the-teams-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hardware-requirements-for-the-teams-app.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @bteams1221 this would be for the computer running Teams.

**Comment by bteams1221** [comment]
Thank you. What would be the RAM requirements for Teams running optimally if it had plenty of RAM to run? 1 GB or 2 GB of RAM? We are calculating RAM in our next desktops to have better performance with all of our applications running.

**Comment by get-itips** [comment]
I think this other article has the information you are looking for
https://docs.microsoft.com/en-us/microsoftteams/teams-memory-usage-perf

**Comment by get-itips** [comment]
@scanum
