### ISSUE TITLE
Target Machine requirements

### ISSUE THREAD

**Issue by ronnievanbuuren** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#91]
It currently lists: 32GB of disk space for each user profile (recommended).  Shouldn't this be 32MB?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b13006b-d1de-8bc7-e0c6-b7022af0e731
* Version Independent ID: d29dae65-bb28-8767-cfd7-07d2ed5fd460
* Content: [Install Microsoft Teams using MSI](https://docs.microsoft.com/en-us/MicrosoftTeams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @ninadara
* Microsoft Alias: **ninadara**

**Comment by zubisultan** [comment]
@ronnievanburren , where is mentioned 32 GB? as per the article it says 3GB of disk space for each user profile (recommended)?

**Comment by LolaJacobsen** [comment]
I fixed the article - it was supposed to be 3GB.
