### ISSUE TITLE
Missing details on meeting expiration

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9100]
Meeting expiration (new-er feature) should be added to this page as it is part of the policy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5a373db-4ab5-91ad-660a-9e3b0ee854f9
* Version Independent ID: fb83f07e-3523-ed1f-1666-ecd9742477ea
* Content: [Manage meeting policies for recording and transcription - Microsoft Teams](https://docs.microsoft.com/en-US/MicrosoftTeams/meetings-policies-recording-and-transcription?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/meetings-policies-recording-and-transcription.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meetings-policies-recording-and-transcription.md)
* Service: **msteams**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by lindspea** [comment]
@danmyhre thank you for reaching out. Please can you provide clarity on the above. Are you referring to the 60 day expiration period?

**Comment by danmyhre** [comment]
Correct - it may just need a reference to this (which isn't filed under the meeting policies section in the left nav):
https://docs.microsoft.com/en-us/microsoftteams/meeting-expiration

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
