### ISSUE TITLE
How to add Vanity URLs in 'Outlook on the web' application ?

### ISSUE THREAD

**Issue by Aaditya-Rane** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9101]
As mentioned in [Browsers and Single Sign-on](https://docs.microsoft.com/en-us/microsoftteams/teams-outlook-share-teams#browsers-and-single-sign-on). 
**For vanity domains, administrators need to add the appropriate Azure Active Directory reply URL.**

Can you please add more details about explaining 
1. Which azure applications the azure administrator needs to add these vanity URLs?
2. As multiple azure applications handling SSO are Microsoft's applications, where only the Service principal is visible to the administrator in which reply URLs can not be added. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 311beaec-73aa-da96-6793-c8750597b1fa
* Version Independent ID: c730e71d-45e8-d912-85b8-0556daa3a57c
* Content: [Share to Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-outlook-share-teams)
* Content Source: [Teams/teams-outlook-share-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-outlook-share-teams.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @Aaditya-Rane, thank you for your feedback.

I understand it's the Azure Active Directory reply URL for the Share to Teams app.

App id is 545d8236-721a-468f-85d8-254eca7cb0da. More information:
https://docs.microsoft.com/powershell/module/exchange/enable-app?view=exchange-ps#example-3
