### ISSUE TITLE
Conflict of information around presence sharing in Teams

### ISSUE THREAD

**Issue by mohafez88** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9104]
Could you please clear the conflict between the statements below in the article:

Note: **Teams respects your privacy configuration** so if you have enabled the privacy mode, your presence will not be visible to external users.

&

In Teams, presence sharing is always enabled for users in the organization. **Privacy (where you define who can see presence) configuration isn't available in Teams.**

Also the conflict with the information in another reference https://docs.microsoft.com/en-us/powershell/module/skype/set-csprivacyconfiguration?view=skype-ps

**Note: This cmdlet has been deprecated in Microsoft Teams and has no impact.**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a162ef5c-3099-7f58-4178-d29e3ec2b5a7
* Version Independent ID: 6ca31e56-052d-6c62-1323-b5aaaae1f04a
* Content: [User presence in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/presence-admins#user-configured-states-expiration)
* Content Source: [Teams/presence-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/presence-admins.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @mohafez88 thanks for your feedback, proposing to update both articles.
