### ISSUE TITLE
Active users in definition Team context is not clear

### ISSUE THREAD

**Issue by stasfeelin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9108]
I was looking into Active Users stats for Team and realized that I don't understand how Active Users are calculated (which actions it's based on?). Found [this doc](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/view-analytics) but it still not clear to me. What are the _intentional actions_ that increase number of Active Users in addition to included into engagement counters (Posts, Replies, Mentions, Reactions) and meetings?
![image](https://user-images.githubusercontent.com/33052570/180019295-a3d3eb65-c593-4322-8641-195d1108a606.png)

![image](https://user-images.githubusercontent.com/33052570/180018689-1220e5d7-46a9-42e9-a4df-f8882bf338ab.png)

In other words: Can you please expand _so on_ [here](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/view-analytics#:~:text=a%20meeting%2C%20and-,so%20on,-.%20We%20strip%20out) so I can understand what exactly 50 users did on July 12th to be counted as Active within the Team?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c93d512-6e5a-09c7-1c9f-c7eeb94555da
* Version Independent ID: f289f914-6b58-6c29-8997-a2fbd017ffe7
* Content: [View analytics in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/view-analytics)
* Content Source: [Teams/teams-analytics-and-reports/view-analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/view-analytics.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by stasfeelin** [comment]
++ with this knowledge would be great to understand how I can build the same dashboard using GRAPH API (which [reports](https://docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-1.0) I can use for that purpose)

**Comment by get-itips** [comment]
Hello @stasfeelin Please see this https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8098#issuecomment-1040595053

**Comment by stasfeelin** [comment]
Hello @get-itips thank you for your reply!

Now it's a bit clearer to me but I still not sure what exactly increments the number of active users in the reports above and how I can identify who exactly included in Active users count. Is it 

> when a user opens a channel message post but doesn't reply to it

or something different?
Do I understand it right that it's being counted like this:
I get notified about a post published -> open Activity tab and read it -> I'm counted as an active user in the total number (active_users = active_users +1)
and if I add reply or post right after it shouldn't increase the total of active users, correct?

Can I get more details on these actions per user somehow via GRAPH?
eg: can I find out which posts I've red or which channels visited?

**Comment by get-itips** [comment]
>Do I understand it right that it's being counted like this:
I get notified about a post published -> open Activity tab and read it -> I'm counted as an active user in the total number (active_users = active_users +1)
and if I add reply or post right after it shouldn't increase the total of active users, correct?

I could get the information that Active user is unique user. Irrespective of the activities the user performs, it should be counted as 1 active user.

> Can I get more details on these actions per user somehow via GRAPH?

What is currently supported to be exported is detailed here

https://docs.microsoft.com/en-us/microsoftteams/export-teams-content#what-is-supported-by-the-teams-export-apis

**Comment by get-itips** [comment]
@scanum
