### ISSUE TITLE
Provisioning USB devices

### ISSUE THREAD

**Issue by bteams1221** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9115]
Please add that USB devices can not be provisioned from the Teams Admin Center.

Also, could you make BTOE and make it work better than BTOB? BTOB is currently bad and needs improvements.
With BTOE, the direct connection would be from the PC port on the phone and network traffic will ALWAYS pass through the phone when wired connection is present.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 344ac314-e98e-ab21-ef47-fb0da80ec884
* Version Independent ID: 8f3d2fe8-5d96-4298-f875-fb3e64688afc
* Content: [Remote provisioning and sign in for Teams Android devices - Microsoft Teams](https://docs.microsoft.com/en-US/MicrosoftTeams/devices/remote-provision-remote-login?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/devices/remote-provision-remote-login.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/remote-provision-remote-login.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by lindspea** [comment]
@bteams1221 thank you for reaching out and helping to improve Microsoft Docs. Please have a look at this article and let me know if it helps. https://docs.microsoft.com/en-us/microsoftteams/devices/usb-devices. Please can I ask where you found information mentioning the above regarding USB devices?

**Comment by lindspea** [comment]
@tiburd please can you help with this and confirm if the information is correct regarding USB devices.

**Comment by tiburd** [comment]
@lindspea 
Apologies...I thought I had sent email to the author about this, but I cannot find it so that I can follow-up on it, so I sent email today.

**Comment by scanum** [comment]
Hi @tiburd Hope all is well. Wanted to see if there is an update here? Thanks!

**Comment by dstrome** [comment]
Supported devices are clearly outlined in the article.
