### ISSUE TITLE
Can we apply sensitivity label to team template from admin center

### ISSUE THREAD

**Issue by harshdamaniahd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9117]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef94e9a3-a0a5-11da-f27b-627ac4fa6186
* Version Independent ID: e49db873-ed77-de53-e4dd-be4fc571d734
* Content: [Get started with team templates in the Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/get-started-with-teams-templates-in-the-admin-console)
* Content Source: [Teams/get-started-with-teams-templates-in-the-admin-console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-started-with-teams-templates-in-the-admin-console.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanachin**

**Comment by dariomws** [comment]
Hi @harshdamaniahd, thank you for your feedback.

Yes, you can apply sensitivity labels when you create a team from the Admin Center:
https://docs.microsoft.com/microsoftteams/sensitivity-labels#microsoft-teams-admin-center

**Comment by harshdamaniahd** [comment]
it doesn't work

**Comment by dariomws** [comment]
@harshdamaniahd,

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.
