### ISSUE TITLE
Office app update script is not pointing to latest version of Teams rooms app - 4.12.139.0

### ISSUE THREAD

**Issue by Prasanna050** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9119]
Office app update script is not pointing to latest version of Teams rooms app - 4.12.139.0

Customer trying to update the Teams rooms app to 4.12.139.0 (latest) [Release notes for Microsoft Teams Rooms (Windows) - Microsoft Teams | Microsoft Docs](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-release-note#4121390-7142022) to resolve their ongoing issue wit Teams rooms app fails to start. They are trying to do manual update and the offline app update script is still pointing to previous version **4.12.138.0** [Manually update a Microsoft Teams Rooms device - Microsoft Teams | Microsoft Docs](https://docs.microsoft.com/en-us/microsoftteams/rooms/manual-update) .

Please update the script download link to latest version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4fa80cf-0319-c006-e886-4929a508b04c
* Version Independent ID: 9d598765-fc30-17f0-6594-57de81d8aa39
* Content: [Manually update a Microsoft Teams Rooms device - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/manual-update)
* Content Source: [Teams/rooms/manual-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/manual-update.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by Prasanna050** [comment]
@dstrome Have you got chance to look into this issue. appreciate your response! Thanks!

**Comment by get-itips** [comment]
The link now downloads the 4.13.132.0 version
