### ISSUE TITLE
What's the definition of "Enterprise Voice enabled"?

### ISSUE THREAD

**Issue by TeamsTechBear** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9121]
Morning!

We have had a bunch of customers come to the Microsoft FastTrack center asking what does "Enterprise Voice enabled" mean. Customers are asking for Agents to be added to Call Queues. We're unsure if it's Fully Licensed and Fully Configured to take PSTN calls or just licensed for Phone System with the "Enterprise Voice" flag in PowerShell set to True. I can confirm that it works by only having a E5 license assigned to a user that has Phone System license included and going into PowerShell for the user and changing "Enterprise Voice" to "True" and it works fine. The end user wouldn't be able to call back a PSTN user or transfer to a PSTN line since they don't have the ability to call PSTN lines but from a technical standpoint they are "Enterprise Voice enabled". A definition note here would be helpful to explain what "Enterprise Voice enabled" means from a Microsoft standpoint. Thank you for your time. 

Set-CsPhoneNumberAssignment
https://docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23ff8713-7e33-ad8e-99df-9308a7c006d7
* Version Independent ID: c9263eba-599b-831b-37fb-837046df9d6a
* Content: [Plan for Teams auto attendants and call queues - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/plan-auto-attendant-call-queue#prerequisites)
* Content Source: [Teams/plan-auto-attendant-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-auto-attendant-call-queue.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Please note that this information is available in the following article: https://docs.microsoft.com/en-us/microsoftteams/here-s-what-you-get-with-phone-system.  To ensure technical accuracy, eliminate maintenance overhead, and avoid content getting out of sync, we often consolidate requirements info into one article and not try to duplicate in numerous articles.  The reference article states the following:

"Be aware that most features require you to assign the Phone System license and ensure that users are "voice enabled." To assign the license, use the [Set-CsPhoneNumberAssignment cmdlet](https://docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps) and set the EnterpriseVoiceEnabled parameter to $true. A few features, such as cloud auto attendant, do not require a user to be voice enabled. Exceptions are called out in the table below."

I will go ahead and close this issue.

**Comment by LtCmdrKeene** [comment]
TeamsTechBear shares the anecdote that "simply setting a user to voiceEnabled=True by PowerShell works fine”, but that is not true for us. Yes I can successfully set a user’s EnterpriceVoiceEnabled status in PowerShell, but a user configured this way does not show up in a Call Queue until/unless we also purchase and assign a PTSN phone number to them.

The referenced page _https://learn.microsoft.com/en-us/microsoftteams/here-s-what-you-get-with-phone-system_ doesn’t classify the situation and never specifies if the user needs a PTSN phone number assigned to be able to participate in a call queue (or if the user must have a PTSN phone number assigned to be properly “Enterprise Voice Enabled”).

We’ve had to purchase and assign many numerous phone numbers for agents. We don’t **want** these agents to make/take calls to/from those local DID numbers, but we had choice: the users could not be in the Call Queue without assigning the numbers.  

While it doesn't matter, I'll also note that the call queue itself doesn't even take outside PTSN calls, internal users dial this queue "by name".

**Comment by TeamsTechBear** [comment]
@LtCmdrKeene 

**_The reason I asked for what Microsoft's Documentation means/says about their meaning of "Enterprise Voice Enabled" is because I don't want anyone getting into trouble via Microsoft's Terms and License usage agreements via this method. I would ask your Microsoft rep if this is acceptable and ok. I accept no responsibility and use at your own risk. I was just testing to see if we could technically do this._** 

I was able to get it to work fine without having to assign a number, communication credits, calling plans, etc. Not sure about your infrastructure but I was able to get it to work and I'll explain below what I did in my test environment and what I understand to be going on and maybe that will help you. I hope that this helps you and if you find out anything cool let us know. 

**_Use Case:_**
I want users to be able to receive calls from outside my company via PSTN calls (Cell/Landlines) via the "Call Queue" but I don't want them to be able to call back to those PSTN lines outside my company. I don't want/need to assign Communication Credits, Calling Plans, Phone Numbers, etc. to the end users. 

Now...remember in this use case the user won't be able to call out to PSTN lines so they won't be able to call users back if they called in via a PSTN line (Example: Cell Phone) or transfer to a PSTN line because they have NO PSTN FUNCATIONALITY (Call Outside Of Microsoft Teams)! They have the Phone System capabilities because they have the "Phone System" license and they are "Enterprise Voice Enabled" since we did that via PowerShell. I think if you assign a phone number to the user it "Enterprise Voice Enables" them automatically so that might be why in your case it only works after you assign a number. 

**_My test environment:_** 
My test environment is all cloud based. I had an SBC setup for on-prem calling to test that, but for this one it's all cloud so no syncing identities from on-prem which shouldn't matter to much in this case or worrying about SBC issues being in the middle. 

**_Call Queue:_**
My Call Queue is setup for membership by "Distribution list and groups" (Group) rather than "Users" (Individual Members) and I'm not using the "Teams" (Teams Channel) part and I haven't tested that either, but if it's working like I assume to be intended then I think it would work with Teams Channels also. The Reason "Old Joe" is there is because I didn't feel like waiting for the group replication to go through with "Old Joe" in it so I added him directly also. I also wanted to see if it stopped me from adding him to see if you might be running into that issue as well. I have a number assigned to the Resource Account assigned to this Call Queue but I typed in the name to test that than the number. 

<img width="679" alt="image" src="https://user-images.githubusercontent.com/81427715/195793825-aa649d28-de72-4340-b7ad-8ef93d6343b1.png">

**_Process:_**

1. I created a new user named "Old Joe" that has never had a number or calling plans assigned. I assigned this user an "Office 365 E5" license so that it would have the "Microsoft 365 Phone System" license assigned since I believe it's called out in my earlier post which links a Microsoft Docs page that you have to have that to be able to be "Enterprise Voice Enabled" as well as the PowerShell command. 

2. I added the new user to the "Group" that's used by the Call Queue in Azure AD. 
(I might have messed up here in added "Old Joe" to the Group that's used before he was "Enterprise Voice Enabled" which is why he didn't show up in the Call Queue's "Agents" list in PowerShell until I added him directly after everything. I'm just giving you my steps. :) )

3. I used the command "Get-CsCallQueue" to see my "Agents" in my "Call Queue" that I wanted. It lists the users by their "Azure AD Object ID" and shows there "Opt In/Out" status. 

<img width="497" alt="image" src="https://user-images.githubusercontent.com/81427715/195799852-b6fff3ad-0f84-41f4-a27f-a9edba1abed4.png">

4. I connected to Teams via PowerShell and used the "Get-CsOnlineUser" command to see "Old Joe's" "EnterpriseVoiceEnabled" status. It was "False" like I expected. I then changed his status to "True" using the command "Set-CsPhoneNumberAssignment".

<img width="454" alt="image" src="https://user-images.githubusercontent.com/81427715/195798385-fe59e943-a243-43b1-b9c7-369bc5c5552e.png">

<img width="632" alt="image" src="https://user-images.githubusercontent.com/81427715/195798779-eb2fcdef-48cb-4e70-aca0-0877c52d251b.png">

5. I ran the command "Get-CsCallQueue" again to see if he was listed and he wasn't. I went back to the "Call Queue" and added him directly because I either did it a little bit out of order and/or didn't want to wait until the group sync happens. It was probably a bit of both to be honest. 

<img width="497" alt="image" src="https://user-images.githubusercontent.com/81427715/195805931-5201ec7b-b64d-4091-a61f-5cd62e2670f1.png">

6. I tested and it worked fine. 

Links:

[Set-CsPhoneNumberAssignment (MicrosoftTeamsPowerShell) | Microsoft Docs](https://docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps)

[Get-CsOnlineUser (SkypeForBusiness) | Microsoft Docs](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps)

https://learn.microsoft.com/en-us/powershell/module/skype/get-cscallqueue?view=skype-ps

[Plan for Teams auto attendants and call queues - Microsoft Teams | Microsoft Docs](https://docs.microsoft.com/en-us/microsoftteams/plan-auto-attendant-call-queue#prerequisites)

<img width="620" alt="image" src="https://user-images.githubusercontent.com/81427715/195801509-a6ba7a57-40f3-4889-b1aa-e00742d73284.png">

https://learn.microsoft.com/en-us/microsoftteams/here-s-what-you-get-with-phone-system

<img width="614" alt="image" src="https://user-images.githubusercontent.com/81427715/195801673-33ebe504-d3ed-4f29-82a5-0df8ae210bc3.png">

**Comment by LtCmdrKeene** [comment]
Reviewing these steps, it sure looks like the only difference between you and me is that I'm using a teams channel as the method of assigning agents rather than directly. I'm going to experiment later today and see what I can learn here.

Shawn Keene<https://cmdrkeene.com/> | IT Systems Engineer, Cloud Services | ms mvp<https://insider.windows.com/en-us/mvps/shawn-keene> | CmdrKeene.com<http://www.CmdrKeene.com>
<https://aka.ms/AAb9ysg>
________________________________

**Comment by TeamsTechBear** [comment]
@LtCmdrKeene 

I just tested by creating a new Call Queue with no number assigned (I do not think calling in via the Resource Account directly or a PSTN line would matter much as far as testing the routing functionality to a non-number assigned user.), a brand new team, and channel. It worked as far as routing to "Old Joe" goes. I haven't played around with Calling Queues using the teams' channel membership much to be honest, so I'm not sure about it displaying the user in the teams client Calling Queue Membership GUI or when I'll see the "Calls" tab of the teams channel I just created. But even without all of that I was able to get it to route pretty much immediately. 

<img width="693" alt="image" src="https://user-images.githubusercontent.com/81427715/195859432-08ebe316-122d-45e0-ba9f-42b7116ff2c6.png">

https://support.microsoft.com/en-gb/office/manage-your-support-call-queue-in-teams-9f07dabe-91c6-4a9b-a545-8ffdddd2504e#:~:text=Manage%20your%20support%20call%20queue%20in%20Teams%201,availability%20...%206%20Collaborate%20with%20team%20members%20

<img width="587" alt="image" src="https://user-images.githubusercontent.com/81427715/195859560-7290edd5-42a9-47e6-beca-064470eeddf5.png">

**Comment by TeamsTechBear** [comment]
@LtCmdrKeene 

Did you get a chance to test?

**Comment by LtCmdrKeene** [comment]
I had another similar user to the ones we added to the queue, but whom didn't have a phone number assigned to her. So I added her to the team (from within Teams itself, I just went to "manage team" and added her as a member).

It's been 24 hours but she's still not showing on the Calls tab (and likewise, her ID is not listed in the output of Get-CsCallQueue.

So I went to run **Set-CsPhoneNumberAssignment -Identity user@domain.org -EnterpriseVoiceEnabled $true** and it told me the user doesn't have the required license.  Now I can't myself purchase (and I don't think assign) licenses, so I can't test further with her until Monday when my boss can again.

However I went back to my convo's with him right about a month ago and reviewed. A previous user we had added to the queue and saw the exact same behavior, we had added the **Teams Phone with Calling Plan** to that agent.  Following assigning that license I **WAS** able to flip the enterprise voice flag. 

![image](https://user-images.githubusercontent.com/4219926/195996799-594e4c48-216e-4bcd-8b24-424e10cc87bb.png)

Even after doing that however, the user didn't show in the queue. So our "solution" was to assign a real PTSN phone number to the user, but we'd love to not have to do this.

So if I'm on track, it seems to me I must still be lacking the knowledge of which license to assign to make it work without a PTSN. If it's answered in the docs it's sure not jumping out at me.

**Comment by TeamsTechBear** [comment]
@LtCmdrKeene 

Sorry if this is not the case, but it seems like you are missunderstanding how the master license (Bundle) and sub licenses (Bundled) work based on your explaination. I'll explain and hopefully that will help.  

In my case I have (Office 365 E5) Master Licenses. I think the new ones are Microsoft 365 E5 licenses now. These are the Master licenses that have a bunch of sub-licenses bundled into them that are automatacally turned on for the user once you assign it to them. Go to the user's account and then go to "Licenses and apps". After assigning the master license go to "Apps" at the bottom and expand it. 

<img width="996" alt="image" src="https://user-images.githubusercontent.com/81427715/196007238-576b63f4-5b37-435f-9ef2-d437f7c67327.png">

You can select which sub license's apps to show by using the drop down menu. 

<img width="398" alt="image" src="https://user-images.githubusercontent.com/81427715/196007366-dc3ec842-5aa5-4563-87f1-4cf63663c8d7.png">

The one that you are looking for is the "Phone System" sub license. In my case it's the "Microsoft 365 Phone System" license. I think thats the same for everyone. In the documentation I've already linked above it calls out that you have to have a "Phone System" license AND be enabled via PowerShell to be "Enterprise Voice Enabled". It might not be included (Sub-License) in the master license your assigning to those users if your using something like E3/F3, which is why you're having to use the "Teams Phone with Calling Plan" license. Now remember what I said in that I "Think" that when you assign a number to a user it changes that PowerShell flag on the user account to be "Enterprise Voice Enabled" so that would explain how come everything works after you assign the license "Teams Phone with Calling Plan" which I assume would give you the "Microsoft 365 Phone System" license and then you assign a phone number to the user which gives the "Enterprise Voice Enabled" equals "True" state.  Also remember from my testing is that I added the user to the membership BEFORE I had truly "Enterprise Voice Enabled" them which is why I had to go back and add them again directly to get them to show up. I would honestly try it this way. 

1. Assign the user a master license that includes a "Phone System" license. 
2. Via Powershell "Enterprise Voice Enabled" them. 
3. Assign them to the team that is being used for Calling Queue. 
4. Check the calling queue using "Get-CsCallQueue".
5. Check the Teams Call queue membership via the GUI. 

<img width="185" alt="image" src="https://user-images.githubusercontent.com/81427715/196007407-d28dedb8-894c-4cce-9db2-7f51f38ac5aa.png">

Sorry if you already knew this, but now if anyone sees this in the future it will be already be explained. Even with all this and getting it working I'm not sure about the Teams "Calls" tab part of this. I'm hoping if we get all of the foundations working it SHOULD work but in the future you might have to do it the way you were doing it for a BRAND NEW team based call queue to get it all setup via the teams "Calls" tab GUI but then after that you could use my method to add new members. It would just take testing to confirm or disprove sadly. 

I hope that all of this helps!

**Comment by TeamsTechBear** [comment]
@LtCmdrKeene 

I found out why I can't see the "Calls" tab in the documentation. I was trying to view it in a Teams Browser instance instead of the app. You can't see the "Calls" tab unless your in the Desktop app. 

<img width="622" alt="image" src="https://user-images.githubusercontent.com/81427715/196023890-c2ad20a1-13f3-4535-a538-868ca03fb7af.png">

https://learn.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue?tabs=general-info#call-queue-feature-compatibility

I'm able to see "Old Joe" on my account that has everything including a number, but on "Old Joe's" I see nothing. 

Mine
<img width="687" alt="image" src="https://user-images.githubusercontent.com/81427715/196023996-9661ff50-1fe4-441a-864d-71f4b1256978.png">

Old Joe's
<img width="230" alt="image" src="https://user-images.githubusercontent.com/81427715/196024040-cfc4721a-1002-4d16-bf5a-09ffca8c332e.png">
<img width="398" alt="image" src="https://user-images.githubusercontent.com/81427715/196024067-08182699-2747-46d4-8292-1cb5dd0ad236.png">

After I assigned "Old Joe" a plan that included a "Calling Plan" license and a number it started showing correctly. 

<img width="407" alt="image" src="https://user-images.githubusercontent.com/81427715/196024409-ef2e159d-ccfa-4edf-9ec3-ce3a2ee5bb5d.png">

<img width="688" alt="image" src="https://user-images.githubusercontent.com/81427715/196024387-410d2b96-e5e1-4d07-982a-03a9e92e5dcd.png">

I then removed just the number and "Old Joe" no longer sees the "Calls" tab again like before I assigned the number. Unless I'm missing something it seems like if you want to be able to use the "teams' channel membership based call queue" with the nice "Calls" tab GUI in Teams then you'll have to do it the way you were doing which is fully licensing and assigning a number. It will technically work with the method I proposed meaning that they'll see who called them in their "Calls" section in Teams not the channels "Calls" tab. They should be able to recieve voicemails and be in the queue, but they will not be able to view the "Calls" tab in that teams' channel. 

Does all that make sense? If you find out the last %5 I'm missing to get it to work the way you want let me know for sure! 

<img width="254" alt="image" src="https://user-images.githubusercontent.com/81427715/196024550-5f322e7c-37d6-4be3-aaae-f882a84f9ab8.png">

Interesting enough is that I was right in that when you assign or unassign a phone number it changes the PowerShell option for "Enterprise Voice Enabled" to "True" or "False". 

Removed the number.
<img width="457" alt="image" src="https://user-images.githubusercontent.com/81427715/196025306-cd5e24ce-cb20-4337-a380-c662f45375ef.png">

Added the number.
<img width="453" alt="image" src="https://user-images.githubusercontent.com/81427715/196025354-737914b3-f6af-4101-9e88-93f2ef092713.png">

**Comment by TeamsTechBear** [comment]
@LtCmdrKeene 

Did the above answer your question? Have you decided which method your going to use?

**Comment by LtCmdrKeene** [comment]
I think I'm misunderstanding the choice of methods here. 

You mentioned you were able to get the agent (old joe) to get mostly configured properly but that he didn't see the Calls tab in the team.  That's not really the major concern as much as Old Joe won't receive any incoming calls that hit that queue either. His phone doesn't ring.  The ability to answer calls in that queue is (apparently) directly tied to whether or not the agent sees the Calls tab in the team channel that hosts the queue.

When you asked which method I'm going to use, I'm not sure what the alternative here is. So there's no way to get an agent to be able to answer queue calls without buying phone numbers and assigning direct-dial PSTN phone numbers to 1400 call center agents?  I don't want the entire fleet of agents being able to make outbound calls or receive direct-dialed calls from the public. I just want agents to answer the queue.

**Comment by TeamsTechBear** [comment]
That's what I'm saying. I was able to get it to work fine with the method I proposed above. "Old Joe" was not able to see the "Calls" tab in the teams channel but he could still get calls from the call queue and he was still shwoing up as an agent in PowerShell and for others that could see the "Calls" tab in the teams channel. "Old Joe" would see the calls he get's in his "Calls" section in the Teams app not the "Calls" tab in the teams channel. 

Have you tested the above things I did? What do you see when you do all the steps that I have laid out and tested? What does your output from your "Call Queue" (PowerShell) look like? What's the Output (PowerShell) from a user that you tried the method above look like? 

Choices are as follows from my testing. 

A. Not assign a PSTN calling plan, etc. and number and have them in the call queue. With this method they WILL NOT be able to see the "Calls" tab in the teams channel but will still get calls from that "Call Queue". 

B. Fully license them so that they can see the "Calls" tab in the teams channel and get calls from that "Call Queue". 

Just to test I would abandon testing on that specific call queue and come back to it later to be honest after you test. I would create a brand new Call Queue and assign a user like we've been talking about ("Phone System" license, "Enterprise Voice Enabling" them via PowerShell, adding them to the Call Queue and checking via "PowerShell" if they are included as an agent.). Then I would call the Call Queue and see if it works. If it does then I don't see why doing it based on team membership is any different when we are talking about the routing of the calls. I'm not sure what you/we are missing to be honest. I did brand new testing with everything new besides the user doing the calling into the Call Queue and it seemed to work fine.

**Comment by LtCmdrKeene** [comment]
If the user does not see the Calls tab, they have no way to opt in and out of the queue with that little toggle on-off switch at the bottom right hand corner. Or see other members of the queue and their status. The things the queue members need to have. I just don't want them making or receiving external calls, this is internal people supporting internal users who call the queue "by name".

Shawn Keene<https://cmdrkeene.com/> | IT Systems Engineer, Cloud Services | ms mvp<https://insider.windows.com/en-us/mvps/shawn-keene> | CmdrKeene.com<http://www.CmdrKeene.com>
<https://aka.ms/AAb9ysg>
________________________________

**Comment by TeamsTechBear** [comment]
I understand, but from my testing if you want those things for that "Call Queue" then you'll have to assign the licenses and numbers to the users that you want to see the "Calls" tab in the teams channel. The way I was using it, it would funcation like a traditional "Call Queue" in nature but use the team for membership. I also use "Presence-based routing" in my call queue which would mean that if the user's presence is in anything but "Available" then they'll not get the call and it will go to the next "Agent" until the waiting time is hit and then go to voicemail in my case. 

Sorry I don't have a better answer for you. I would ask support and see if they have anything that could be helpful that I'm missing.

**Comment by LtCmdrKeene** [comment]
Alright that's unfortunate but clear to me the situation then. Sorry if I made you repeat yourself here but I do appreciate the clarification.

**Comment by TeamsTechBear** [comment]
No problem! It's a question that I have gotten a few times and have not had time to deep dive into it. Now I know this part in depth and I got around to playing with "Teams channel based Call Queue" membership. Glad that I was able to help answer it one way or the other. Have a wonderful rest of your week!
