### ISSUE TITLE
Are there instructions on properly setting up failover for a derived trunk setup?

### ISSUE THREAD

**Issue by jlon125** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9123]
Do the commands listed here, if performed on the Carrier Tenant, actually work for derived trunks in customer tenants?

Or is there a different method to enable failover for derived trunks, assuming the customer tenant has two voice routes, each to a different SBC?

Specifically, I mean the "CSOnlinePSTNGateway -Identity sbc1.contoso.com -FailoverResponseCodes "408" Command, which is not possible to employ on the customer tenant in a derived trunk scenario (there are no PSTN Gateways, just Voice Routes) For example, if I wanted to fail over on a "403" response. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 485ba3d8-4016-aeb6-214c-22645d4ed439
* Version Independent ID: 328e0dac-7821-7607-0d89-8fba7711b11c
* Content: [Trunk failover on outbound calls - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-trunk-failover-on-outbound-call)
* Content Source: [Teams/direct-routing-trunk-failover-on-outbound-call.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-trunk-failover-on-outbound-call.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @jlon125 
How are you?
To my understanding, the _FailoverResponseCodes_ would need to be configured in the carrier trunk, as the CSOnlinePSTNGateway object exists there.

>Carriers need to set up and manage only a single trunk (the carrier trunk in the carrier domain) by using the Set-CSOnlinePSTNGateway command. 

Considerations for setting up multi-tenant failover

https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants#considerations-for-setting-up-multi-tenant-failover

**Comment by jlon125** [comment]
Hi @get-itips ! Indeed, but that goes back to my original question, _Do the commands listed here, if performed on the Carrier Tenant, actually work for derived trunks in customer tenants?_

I guess I should go ahead and try it out and report back.

**Comment by get-itips** [comment]
Sorry, I misread your original question @jlon125 unfortunately I do not have such a lab to test, I think that they will work because 

> A derived trunk that doesn't require registration. It is simply a desired host name added in from of the carrier trunk. **It derives all of its configuration parameters from the carrier trunk.**

**Comment by jlon125** [comment]
@get-itips No apologies needed, I appreciate the clarification, and thank you!

**Comment by get-itips** [comment]
@scanum
