### ISSUE TITLE
Please add Microsoft 365 Business Basic/Business Standard/Business Premium plan

### ISSUE THREAD

**Issue by takeakitake** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9127]
Please add Microsoft 365 Business Basic/Business Standard/Business Premium plan to "Voice and PSTN connectivity" section. Pre-required licenses are explained in this section. However, these plans are not in.

Microsoft 365 Business Basic/Business Standard/Business Premium plan are listed for "Microsoft Teams Phone Standard" and "Microsoft Teams Phone with Calling Plan" in "License Prerequisites" table in "Product Terms".

Audio Services
https://www.microsoft.com/licensing/terms/en-US/productoffering/AudioServices/MCA
-----------
License Prerequisites

Microsoft Teams Phone Standard	Office 365 F3/E1/E3/A1/A3; Microsoft 365 Business Basic/Business Standard/Business Premium/F1/F3/E3/A3; Microsoft Teams Essentials (AAD Identity)

Microsoft Teams Phone with Calling Plan	Office 365 F3/E1/E3/A1/A3; Microsoft 365 Business Basic/Business Standard/Business Premium/F1/F3/E3/A3; Microsoft Teams Essentials (AAD Identity)
-----------

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abae7324-861d-7ca7-7239-a5df8fd927d5
* Version Independent ID: 8a30bd2f-9bc3-a0a8-8b31-d53836ead4d0
* Content: [Microsoft Teams add-on licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing)
* Content Source: [Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@takeakitake 

**Your ask is to update this text, correct?**

Buy a Microsoft 365 Business, E1/E3, A1/A3, or G1/G3 plan and add Teams Phone with Calling Plan bundle licenses.

- This model will give you Teams Phone System PBX capabilities and a Microsoft Domestic Calling Plan.
- Choose this setup if you want all phone number management and billing to be handled by Microsoft.
- Check to see if the [Teams Phone with Calling Plan bundle license is available in your region](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans).

Buy an E1/E3, A1/A3, or G1/G3 plan, add Teams Phone Standard licenses, and choose a Microsoft standalone calling plan or third-party PSTN carrier.

- This model will give you Teams Phone System, but you'll still need to connect to the PSTN.
- To view all your PSTN connectivity options, see [PSTN connectivity options](https://docs.microsoft.com/en-us/microsoftteams/pstn-connectivity).
- To learn about all voice solutions, see [Plan your Teams voice solution](https://docs.microsoft.com/en-us/microsoftteams/cloud-voice-landing-page).

----------------------
**Would this updated version suffice?**

Buy a _Microsoft 365 Business Basic/Standard/Premium_, E1/E3, A1/A3, or G1/G3 plan and add Teams Phone with Calling Plan bundle licenses.

- This model will give you Teams Phone System PBX capabilities and a Microsoft Domestic Calling Plan.
- Choose this setup if you want all phone number management and billing to be handled by Microsoft.
- Check to see if the [Teams Phone with Calling Plan bundle license is available in your region](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans).

Buy a _Microsoft 365 Business Basic/Standard/Premium_, E1/E3, A1/A3, or G1/G3 plan, add Teams Phone Standard licenses, and choose a Microsoft standalone calling plan or third-party PSTN carrier.

- This model will give you Teams Phone System, but you'll still need to connect to the PSTN.
- To view all your PSTN connectivity options, see [PSTN connectivity options](https://docs.microsoft.com/en-us/microsoftteams/pstn-connectivity).
- To learn about all voice solutions, see [Plan your Teams voice solution](https://docs.microsoft.com/en-us/microsoftteams/cloud-voice-landing-page).

**Comment by get-itips** [comment]
@takeakitake could you see @DaniEASmith comment here? Thanks

**Comment by DaniEASmith** [comment]
@takeakitake We've decided to close this issue for now because we haven't heard back from you. If needed, we can reopen this issue.

**Comment by takeakitake** [comment]
I appologize for late reply.
Yes, that updated version is suffice.
