### ISSUE TITLE
Is Logitech Rally Bar in Device Mode certified for MTRoW with Cortana?

### ISSUE THREAD

**Issue by UCNinja** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9132]
Is Logitech Rally Bar in Device Mode certified for MTRoW with Cortana? If so, please add to certified devices list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a80437e4-298e-f7ac-6edd-1067eb678ef4
* Version Independent ID: d06eab8d-47c4-5045-a5fe-a4c83e8b6b22
* Content: [Cortana voice assistance in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cortana-in-teams)
* Content Source: [Teams/cortana-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cortana-in-teams.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @UCNinja, thank you for your feedback.

I think you are talking about the Logi Rally Plus Conferencing System. It was added 13 days ago to the article.

**Comment by UCNinja** [comment]
Thanks. No, I was referring about the Rally Bar.

**Comment by dariomws** [comment]
I understand that only the Rally Plus is Cortana certified.
