### ISSUE TITLE
PAC no longer supported 

### ISSUE THREAD

**Issue by jerieger** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9135]
Per Madhu, PAC files are no longer supported by MTR and will prevent enrollment into TAC.
Per PG, static proxy or no proxy are only two options if goal is to have MTR enrolled in TAC .
The part in this doc where we show customers how to configure MTR for PAC should be removed OR a disclaimer should be added stating that if PAC is used .. the MTR will fail to enroll in TAC and cannot be managed in TAC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a711c07e-10b3-baf0-b92c-9dbcf6ab9474
* Version Independent ID: 2038cd48-44b1-1ed1-6e50-48290eef5605
* Content: [Prepare your Environment - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-prep)
* Content Source: [Teams/rooms/rooms-prep.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-prep.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @jerieger I am looking into this

**Comment by get-itips** [comment]
Hello @jerieger can you please detail if you refer to MTRoW or MTRoA or both? Thanks

**Comment by jerieger** [comment]
These are MTR-W

Jeff Rieger
Support Escal Eng
Us-Css-Skype For Business
Customer Services and Support
Office: +1 (469) 7754891
***@***.******@***.***>
[Microsoft Logo]
Team Manager | George Vordenbaum  | +1 469.775.4543 | ***@***.******@***.***>
If you have any feedback about my work, please let either me or my manager George know at ***@***.******@***.***>

**Comment by get-itips** [comment]
@jerieger Thanks, I am trying to confirm

**Comment by get-itips** [comment]
@scanum Closing for now as I did not get this confirmed. In any case it can be re-opened.
