### ISSUE TITLE
Microsoft Teams SBCs send # character unescaped

### ISSUE THREAD

**Issue by davemidd** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9145]
It was confirmed to me (in support ticket #‎31034933) that the Microsoft SBCs send the # character in a Request-URI un-escaped. i.e. it is sent as a '#' rather than '%23'.

e.g. If the Teams user dials #123, we receive over the Direct Routing trunk:

INVITE sip:#123@teams.mydomain.com:5081;user=phone;transport=tls SIP/2.0.

instead of:

INVITE sip:%23123@teams.mydomain.com:5081;user=phone;transport=tls SIP/2.0.

This is in violation of RFC-3261. (See Section 25  Augmented BNF for the SIP Protocol, Sub-section 25.1 Basic Rules).
This RFC exception should be documented on this page.

Regards,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe63a384-d262-ea29-c793-6266228035bf
* Version Independent ID: a1bc23e7-3241-bc8b-7e41-d34941d9f4ff
* Content: [Teams phone system direct routing: Definitions and RFC standards - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-protocols?source=docs)
* Content Source: [Teams/direct-routing-protocols.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-protocols.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @davemidd 
How are you?
Unfortunately, we have no access to support cases information.
I'll try to confirm this, thanks

**Comment by CarolynRowe** [comment]
Looping in @FilippSe

**Comment by get-itips** [comment]
@FilippSe Can you help clarify here? Thank you!

**Comment by FilippSe** [comment]
Under investigation at the moment

**Comment by get-itips** [comment]
Thanks @FilippSe

**Comment by get-itips** [comment]
@FilippSe How are you? Any update on the investigation? Thanks

**Comment by scanum** [comment]
@FilippSe Wanted to check here if there is any update on this investigation? Thanks!

**Comment by get-itips** [comment]
Change is now live. Closing.
