### ISSUE TITLE
Not available in GCC

### ISSUE THREAD

**Issue by akarimian** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9146]
Feature is not available in GCC tenants

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff254bd5-0d45-79c1-db9e-77768bbf1292
* Version Independent ID: ad980209-879d-5ca1-03b4-178cdc6e3548
* Content: [Microsoft Teams Monitoring and Alerting - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/alerts/teams-admin-alerts)
* Content Source: [Teams/alerts/teams-admin-alerts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/alerts/teams-admin-alerts.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by lindspea** [comment]
@akarimian thank you for reaching out and helping to improve Microsoft Docs. Please have a look at this article for more information and let me know if it helps clarify the issue. https://docs.microsoft.com/microsoft-365/compliance/alert-policies?view=o365-worldwide

**Comment by akarimian** [comment]
Hello, what you linked to is not relevant to the Teams monitoring and alerting page. The page should reference that this feature is not available in GCC/GCC-High tenants.

-Armen

From: Lindsay ***@***.***>
Sent: Monday, August 1, 2022 3:57 AM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Karimian, Armen ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Not available in GCC (Issue #9146)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@akarimian<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fakarimian&data=05%7C01%7Carmen.karimian%40akima.com%7Cd2a138aa9bdb44a4d1d208da73935d85%7C2061b72436484434937fdf745ded7595%7C0%7C0%7C637949374044065682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zPBco1qkSgSb%2FaD2kSjbBJLjzA95Wdv4G5qD0B%2BlS3U%3D&reserved=0> thank you for reaching out and helping to improve Microsoft Docs. Please have a look at this article for more information and let me know if it helps clarify the issue. https://docs.microsoft.com/microsoft-365/compliance/alert-policies?view=o365-worldwide<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fmicrosoft-365%2Fcompliance%2Falert-policies%3Fview%3Do365-worldwide&data=05%7C01%7Carmen.karimian%40akima.com%7Cd2a138aa9bdb44a4d1d208da73935d85%7C2061b72436484434937fdf745ded7595%7C0%7C0%7C637949374044065682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uGsN3Xb1cm8iVrpr%2FCXhVNMKQXVsodixmTHcseF4AZY%3D&reserved=0>

-

**Comment by lindspea** [comment]
@akarimian thank you for pointing this out. I was referring to the note in the article to say that it mentioned that alert policies are available to GCC tenants.. See at the end of the note. "Alert policies are available for organizations with a Microsoft 365 Enterprise, Office 365 Enterprise, or Office 365 US Government E1/F1/G1, E3/F3/G3, or E5/G5 subscription. Advanced functionality is only available for organizations with an E5/G5 subscription, or for organizations that have an E1/F1/G1 or E3/F3/G3 subscription and a Microsoft Defender for Office 365 P2 or a Microsoft 365 E5 Compliance or an E5 eDiscovery and Audit add-on subscription. The functionality that requires an E5/G5 or add-on subscription is highlighted in this topic. Also note that alert policies are available in Office 365 GCC, GCC High, and DoD US government environments."

**Comment by akarimian** [comment]
I have the appropriate licenses. Support told me that the Alert functionality within Teams Admin center which is referenced in the page I provided feedback on is not available in GCC.
Here is their response:
- Since it is a GCC tenant and the flighting keys for notification feature are turned off as of now.
- This feature will be rolled out by end of this semester/early January.
All I'm asking is that this page be updated to reflect that its not available in GCC tenants yet so others don't waste weeks working with support to figure out why it's not there.


From: Lindsay ***@***.***>
Sent: Tuesday, August 2, 2022 4:02 AM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Karimian, Armen ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Not available in GCC (Issue #9146)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@akarimian<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fakarimian&data=05%7C01%7Carmen.karimian%40akima.com%7C27ac4e74a9ad4a13381c08da745d37c7%7C2061b72436484434937fdf745ded7595%7C0%7C0%7C637950240992234992%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BK6jzArdaP%2BXpadCMvkwtSiNnGmwdXw9PRBwYE9UAHM%3D&reserved=0> thank you for pointing this out. I was referring to the note in the article to say that it mentioned that alert policies are available to GCC tenants.. See at the end of the note. "Alert policies are available for organizations with a Microsoft 365 Enterprise, Office 365 Enterprise, or Office 365 US Government E1/F1/G1, E3/F3/G3, or E5/G5 subscription. Advanced functionality is only available for organizations with an E5/G5 subscription, or for organizations that have an E1/F1/G1 or E3/F3/G3 subscription and a Microsoft Defender for Office 365 P2 or a Microsoft 365 E5 Compliance or an E5 eDiscovery and Audit add-on subscription. The functionality that requires an E5/G5 or add-on subscription is highlighted in this topic. Also note that alert policies are available in Office 365 GCC, GCC High, and DoD US government environments."

-

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
