### ISSUE TITLE
Clarification on fine points: Teams availability status, quiet time, multiple PSTN numbers

### ISSUE THREAD

**Issue by evilsizorm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9152]
We are piloting Teams Phone and there are some detailed configuration impacts which would be great to have covered in this page.  here are the questions
- If a Teams user is set to be notified and conferenced in when someone calls 911, will this call ring through if they have their status set to Do Not Disturb?
- If a Teams user is set to be notified and conferenced in when someone calls 911, will this call ring through on their phone if the the call occurs while they have Quiet time set in the Teams app?
- This page seems to indicate that it is only possible to enter 1 PSTN phone number.  But the tooltip in Teams Admin for this field says, "When you put in a phone number, it can be an E.164 formatted number or a series of numbers depending how your calls are being routed to the PSTN.".  If it is possible to enter multiple numbers, what is the syntax for users of the Microsoft Calling Plan?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66544770-c56b-ad8a-5b67-9e20cbc945f1
* Version Independent ID: d69667d5-d486-4b99-5e07-edb2fda7f5c7
* Content: [Manage emergency calling policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-emergency-calling-policies)
* Content Source: [Teams/manage-emergency-calling-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-emergency-calling-policies.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @evilsizorm I am looking into this

**Comment by get-itips** [comment]
Hello @evilsizorm Mark, about this:

>This page seems to indicate that it is only possible to enter 1 PSTN phone number. But the tooltip in Teams Admin for this field says, "When you put in a phone number, it can be an E.164 formatted number or a series of numbers depending how your calls are being routed to the PSTN.". If it is possible to enter multiple numbers, what is the syntax for users of the Microsoft Calling Plan?

I could find out that the tooltip in TAC might be incorrectly stating that it accepts multiple numbers, will try to confirm 100% soon.

**Comment by get-itips** [comment]
Hello @evilsizorm 

About this

>If a Teams user is set to be notified and conferenced in when someone calls 911, will this call ring through if they have their status set to Do Not Disturb?
If a Teams user is set to be notified and conferenced in when someone calls 911, will this call ring through on their phone if the the call occurs while they have Quiet time set in the Teams app?

Those would be regular calls, and are subject to client call routing settings like DND.

**Comment by evilsizorm** [comment]
Thank you for following up Andres.

**Comment by get-itips** [comment]
I could confirm that the tooltip in TAC will be updated.
Thanks
