### ISSUE TITLE
Add Operator Connect references in call flows documentation

### ISSUE THREAD

**Issue by dwhitney7** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9156]
Hello team! Short feedback, but have heard this is a few times in the last several months - can we please add specific references to Operator Connect on this call flows page?

Thanks!
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c84773-337e-9df7-7fbd-fc9d94280711
* Version Independent ID: 223a78a0-67fd-8b96-be3f-153bb400101b
* Content: [Microsoft Teams call flows - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/microsoft-teams-online-call-flows)
* Content Source: [Teams/microsoft-teams-online-call-flows.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/microsoft-teams-online-call-flows.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @dwhitney7 I am looking into this

**Comment by get-itips** [comment]
Hello @dwhitney7 David,
I managed to pass this feedback to the article's author and adding OC references will be taken into account.
Thank you for your feedback,

**Comment by dwhitney7** [comment]
Hi @get-itips, is there any update you can share back from the article author on if Operator Connect references are planned to be added to this article? Thanks so much!
