### ISSUE TITLE
Download link not valid anymore

### ISSUE THREAD

**Issue by ckordel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9158]
The donwload link thats called in the CreateSRSMedia.ps1 is invalid:

  1144  # Acquire the SRS deployment kit
  1145  $SRSDK = Save-Url "https://go.microsoft.com/fwlink/?linkid=851168" "deployment kit"
  1146  Test-Signature $SRSDK

This link leads to a 404 page. Script is currently now working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Build a Microsoft Teams Rooms image - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/console)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by lindspea** [comment]
@ckordel thank you for reaching out and helping to improve Microsoft Docs. I've just checked the link and it seems to be working now. Please can you check and let me know. Thanks so much.
