### ISSUE TITLE
MTR update script download link is not working

### ISSUE THREAD

**Issue by rito2k** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9159]
The link to download the latest version of the offline app update script is not working (https://go.microsoft.com/fwlink/?linkid=2151817)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4fa80cf-0319-c006-e886-4929a508b04c
* Version Independent ID: 9d598765-fc30-17f0-6594-57de81d8aa39
* Content: [Manually update a Microsoft Teams Rooms device - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/manual-update)
* Content Source: [Teams/rooms/manual-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/manual-update.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by lindspea** [comment]
@rito2k thank you for reaching out and helping to improve Microsoft Docs. It seems the link is working now. Please can you check from your side and let me know. Thanks.

**Comment by rito2k** [comment]
Hi @lindspea, it is working now, thanks a lot!
