### ISSUE TITLE
404 Link

### ISSUE THREAD

**Issue by onelegend** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9160]
The manual update ps1 script link is down:
https://download.microsoft.com/download/9/0/D/90D4826A-9FD2-47D2-B911-97BF1737F4F7/MTR-Update-4.12.138.0.ps1

Manually changing the version number to the current release is active:
https://download.microsoft.com/download/9/0/D/90D4826A-9FD2-47D2-B911-97BF1737F4F7/MTR-Update-4.13.132.0.ps1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4fa80cf-0319-c006-e886-4929a508b04c
* Version Independent ID: 9d598765-fc30-17f0-6594-57de81d8aa39
* Content: [Manually update a Microsoft Teams Rooms device - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/manual-update#step-1-download-the-offline-app-update-script)
* Content Source: [Teams/rooms/manual-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/manual-update.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by lindspea** [comment]
@onelegend thank you for reaching out and helping to improve Microsoft Docs. It seems the article has been updated and the link is now working. Please can you check and let me know. Thank you.
