### ISSUE TITLE
Diagram Missing

### ISSUE THREAD

**Issue by MartinDov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9166]
Diagram image is missing below the Tip

"No license is needed for resource accounts that will be used with nested auto attendants or call queues that don't have a phone number assigned. See the **following diagram** for reference."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6891495-01c6-117b-c28b-28232782ba74
* Version Independent ID: 1c23b35a-e9ba-ffdd-9baa-a3f83f4ed9ca
* Content: [Microsoft Teams Phone Resource Account licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/virtual-user)
* Content Source: [Teams/teams-add-on-licensing/virtual-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/virtual-user.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @MartinDov I am looking into this. I'll let you know.
