### ISSUE TITLE
Instructions not correct

### ISSUE THREAD

**Issue by woemoejack** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9167]
[Enter feedback here]
"Step 4. Select Add a resource mailbox to create a new room account. Enter a display name and email address for the account, select Add, and then select Close."

The option actually reads 'Add resource'. There is no Add option, only Save.  

_"5. By default, resource accounts are configured with the following settings:

Allow repeat meetings
Automatically decline meetings outside of the following limits
Booking window (days): 180
Maximum duration (hours): 24
Auto accept meeting requests
If you want to change them, select Set scheduling options before you select Close. If you want to change them later, go to Resources > Rooms & equipment, select the resource account. Then under Booking options, select Edit."_

The option to set scheduling options actually reads 'Edit booking options'

"Requiring users to change the password on a shared device will cause sign in problems. Uncheck Require this user to change their password when they first sign in, and select Reset."

The option to 'Reset' actually reads 'Reset password'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Create resource accounts for rooms and shared Teams devices - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/with-office-365?tabs=m365-admin-center%2Cazure-active-directory2-password%2Cactive-directory2-license#create-a-resource-account)
* Content Source: [Teams/rooms/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-office-365.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Thanks for your feedback!
