### ISSUE TITLE
Poly Rove Device missing

### ISSUE THREAD

**Issue by Pratikd-msft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9169]
Poly Rove appears to be certified for SIP Gateway but it's not listed as a certified device under Poly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44863905-42d1-cd3f-0d97-af2570649e89
* Version Independent ID: 44863905-42d1-cd3f-0d97-af2570649e89
* Content: [Plan SIP Gateway - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/sip-gateway-plan)
* Content Source: [Teams/sip-gateway-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sip-gateway-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @Pratikd-msft, thank you for your feedback.

Rove has been added 12 days ago:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/2c0c2c5c09f28763f62fb4a69bcbffe5ecb836c1
