### ISSUE TITLE
rate page broken

### ISSUE THREAD

**Issue by kitkatneko** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#917]
rate page broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d52a9779-b72d-dea0-eac2-6c04a8c282eb
* Version Independent ID: d3c3d968-9e54-ec42-3438-9320e23d68b9
* Content: [What are Communications Credits?](https://docs.microsoft.com/en-us/microsoftteams/what-are-communications-credits)
* Content Source: [Teams/what-are-communications-credits.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-communications-credits.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@kitkatneko Thank you for this feedback

I will make sure that this information about the rate page being broken gets over to the Teams/Skype for Business team. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by kenwith** [comment]
@kitkatneko - sorry for the long delay on this. I believe this is fixed now. If not please re-open. Thank you for taking the time to submit this and sorry again for the long delay. Much appreciated for letting us know about the issue.

**Comment by MikeDembek** [comment]
The "Rates for Calling" link bounces to https://products.office.com/en-us/microsoft-teams/online-meeting-solutions#Rates, and the "See plans & pricing" link there sends you to https://www.microsoft.com/en-us/microsoft-365/business/compare-more-office-365-for-business-plans, which just has a very broad overview of E1/E3/E5 licensing without any obvious information on calling rates.  Is there a better page this could be directed to?

**Comment by dstrome** [comment]
The "Rates for calling" link does send you to the right page - you just need to scroll down to the bottom to find the rates wizard. I'll add a little bit of text to make that clear. thanks for the feedback!
