### ISSUE TITLE
Delete sent messages vs delete chat

### ISSUE THREAD

**Issue by ChristianJBergstrom** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9173]
[Hello, from my understanding the "delete chat" is a new parameter for deletion of chat **threads**. The setting is available in TAC and in the Messaging policy but it has no effect. You can toggle it but it doesn't do anything.

The description here https://docs.microsoft.com/en-us/microsoftteams/messaging-policies-in-teams?msclkid=d7563491d14811ecabb24fc16aea1fcc#messaging-policy-settings says the following:

**Delete sent messages** Use this setting to let users delete messages that they sent in chat.

**Delete chat** Use this setting to let users delete messages that they sent in chat.

I've raised this to the Teams PG and they are investigating. But for now perhaps the "Delete chat" shouldn't even be there? At least not with that information.

There's no details in the Messaging policy either https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmessagingpolicy?view=skype-ps

Here's an official update from the Teams feedback portal about the possibility to delete chat threads https://feedbackportal.microsoft.com/feedback/idea/50748037-5e7d-ec11-8d21-002248226797

*edit* Good to see @get-itips here! We're trying to get some answers together in the Teams MVP team

Btw, this article is about deleting chats using Teams for personal use and Teams for small business which isn't applicable for work or school accounts, making it further frustrating for admins https://support.microsoft.com/en-us/office/delete-a-chat-in-teams-for-personal-and-small-business-use-ec4bfaa8-2197-4541-8bb4-edbef256f29e

Thanks!]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34f3188-0af5-f972-9d28-959f5f7866a2
* Version Independent ID: fab26e11-a729-92a4-3ea6-8668dca55dd0
* Content: [Manage messaging policies in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/messaging-policies-in-teams?msclkid=d7563491d14811ecabb24fc16aea1fcc)
* Content Source: [Teams/messaging-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/messaging-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by get-itips** [comment]
Hello @ChristianJBergstrom 

Thanks for adding additional information, there is already a past issue still open about this

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8898

As soon as I have confirmation I'll update the article, I also have a [PR](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/8985) open waiting for review.

**Comment by ChristianJBergstrom** [comment]
Ah.. my bad! Good news though 👍

**Comment by hollyanneu2** [comment]
OK I turned on the delete option for a Channel I own. However, while I am able to delete chats within the Channel, I am NOT able to delete any Power Automate posts that I created to post test tickets. Is this a missed issue or?
![Power Automate Post unable to delete](https://user-images.githubusercontent.com/51829765/185188751-c7d42b99-6044-4870-bd6f-3a37fc05d0fd.jpg)

**Comment by ChristianJBergstrom** [comment]
> OK I turned on the delete option for a Channel I own. However, while I am able to delete chats within the Channel, I am NOT able to delete any Power Automate posts that I created to post test tickets. Is this a missed issue or? ![Power Automate Post unable to delete](https://user-images.githubusercontent.com/51829765/185188751-c7d42b99-6044-4870-bd6f-3a37fc05d0fd.jpg)

Hey @hollyanneu2 It's on the backlog.. https://feedbackportal.microsoft.com/feedback/idea/e6ba0d0f-272e-ec11-b6e6-00224827bbc2
