### ISSUE TITLE
Update (or Remove) DNS entries (Teams Only)

### ISSUE THREAD

**Issue by FernandoGualano** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9175]
Hi!
I have a question. This Docs article said: 

![image](https://user-images.githubusercontent.com/50090959/183480933-47594a2c-edca-420d-b669-5e4f827d05ec.png)

If my organization is set to Teams Only, why do I need to update DNS records pointing to Microsoft 365? And in what scenarios could I remove them?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66c2d1fa-76a5-18d8-2a1a-3a21e3652b3f
* Version Independent ID: f2091ba7-a1a8-849f-4eef-3324e4139690
* Content: [Manage DNS entries when decommissioning your on-premises environment - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/decommission-manage-dns-entries)
* Content Source: [Skype/SfbHybrid/hybrid/decommission-manage-dns-entries.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/decommission-manage-dns-entries.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @FernandoGualano, thank you for your feedback.

@CarolynRowe, could you help here? Are these DNS records still required for TeamsOnly? Thanks!

When you add a new domain to the Microsoft 365 Admin Center, this is what we have:
![image](https://user-images.githubusercontent.com/33589238/183630102-a6875f5e-855a-4fab-977e-59f27cf7dcc1.png)
It says "Skype for Business in addition to Microsoft Teams".

**Comment by scanum** [comment]
Hi @CarolynRowe hope all is well. Wanted to check if there is an update here? Thanks.

**Comment by CarolynRowe** [comment]
According to the PM, yes.  I suggest the submitter contact support for help.  Closing this issue.
