### ISSUE TITLE
Error following the guide. 

### ISSUE THREAD

**Issue by jaller698** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9176]
When following the guide, after linking to the path where the .iso file is located the error, is thrown:

Export-WindowsImage : Either the Name or Index parameter is required
At C:\Users\User1\downloads\CreateSrsMedia.ps1:1464 char:9
+         Export-WindowsImage -DestinationImagePath "$NewInstallWim" -S ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Export-WindowsImage], PSArgumentException
    + FullyQualifiedErrorId : Export-WindowsImage,Microsoft.Dism.Commands.ExportWindowsImageCommand

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
