### ISSUE TITLE
Link to appsource

### ISSUE THREAD

**Issue by prkosh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9177]
[Enter feedback here]

Can the catalog be linked to Appsource ? 
https://appsource.microsoft.com/en-US/marketplace/apps?product=office%3Bteams&page=1
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2081f0e-cc69-8c64-2fe9-5ba8a9e36ed3
* Version Independent ID: 629041e6-01c5-f78c-84c6-8ede02ee0ade
* Content: [Know about apps in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/deploy-apps-microsoft-teams-landing-page?view=o365-worldwide)
* Content Source: [Teams/deploy-apps-microsoft-teams-landing-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/deploy-apps-microsoft-teams-landing-page.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @guptaashish
* Microsoft Alias: **guptaashish**

**Comment by ashishguptaiitb** [comment]
The article was updated for this feedback. Closing the issue.
