### ISSUE TITLE
Positive scenario

### ISSUE THREAD

**Issue by prkosh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9180]
[Enter feedback here] Please include Screenshots with Apps in Allowed state. Not Blocked.
Please remove the term " malicious or problematic apps."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcb5cdf7-9a02-cdf2-e152-38db69f0ae79
* Version Independent ID: d8e429a0-296d-1bf9-fb21-1ce13a6a59c3
* Content: [Overview of app policies to manage apps in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/app-policies)
* Content Source: [Teams/app-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/app-policies.md)
* Service: **msteams**
* GitHub Login: @guptaashish
* Microsoft Alias: **guptaashish**

**Comment by ashishguptaiitb** [comment]
Closing the issue.
Resolved via https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/pull/10069
