### ISSUE TITLE
Supported status for Safari browser is incorrect

### ISSUE THREAD

**Issue by Draykan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9184]
Web browser compatibility table states this for Safari 13.1+ and 14+ browsers:
"1:1 calls not supported. Group calls fully supported."

Actually, according to public roadmap item, it **IS** supported:
[Microsoft Teams: 1:1 Calling in Safari Web Browser](https://www.microsoft.com/en-us/microsoft-365/roadmap?searchterms=87312)

However, I don't know the minimum Safari version this feature is supported on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c86f401-cff4-93b3-ff69-b9787a87e644
* Version Independent ID: c0808bd3-cf63-0625-4c3c-65469c26fb3e
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients?tabs=Windows#web-client)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
