### ISSUE TITLE
Getting connector to work with MFA auth

### ISSUE THREAD

**Issue by jeromepaw** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9185]
We are having trouble to get the MicrosoftCallQuality connector working because we are using MFA on our tenant.
Is this something you will be implementing in a near future ?

Thanks !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e657b86-072e-1dff-0e96-1ec0efa8e4d7
* Version Independent ID: 81d2ec45-8c85-220c-760a-443971fd27f9
* Content: [View Microsoft Teams utilization in Power BI using CQD data - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cqd-teams-utilization-report)
* Content Source: [Teams/CQD-teams-utilization-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-teams-utilization-report.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
