### ISSUE TITLE
The descriptions for "channel messages", "reply messages" and "post messages" could be clearer 

### ISSUE THREAD

**Issue by Kath-Anne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9186]
Firstly:
The explanations currently refer to "channel messages"/"post messages", when I think the correct terminology that people are familiar with would be "conversations in the posts channel" of multiple teams. Unless comments outside of the posts channel are counted (e.g tab conversations)?

Secondly: 
The response by quentinhurdazure https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4545 explains that the channel messages is the combined sum of posts and replies... but in reality the exported statistics do not add up (I would say about 1/4 of the results are higher than the sum of posts and replies, indicating some other messages are counted?).

I think the descriptions could potentially be clearer, e.g.

• Channel messages:
The combined number of new conversation posts and replies that the user posted in the posts channel of any team during the specified time period. (*though if this is not the case, what is actually being measured if not reply messages + post messages).

• Reply messages:
The number of conversation reply messages that the user posted in the posts channel of any team during the specified time period.

• Post messages:
The number of new conversation messages that the user posted in the posts channel of any team during the specified time period.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2758a3d6-c646-dcb0-2a31-c7b9b84e780b
* Version Independent ID: 8704c9fe-f8b0-82d2-bd83-3fd1a9ad638d
* Content: [Microsoft Teams user activity report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report)
* Content Source: [Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @Kath-Anne I am looking into this

**Comment by get-itips** [comment]
Hello @Kath-Anne 
I tested this, with a brand new channel team and in my case, i did see that channel message = posts+replies, did you see otherwise?

![image](https://user-images.githubusercontent.com/36666927/185653314-b265fced-7797-4884-8652-2775ded4aac6.png)

**Comment by get-itips** [comment]
@Kath-Anne Thanks for adding more information, I'll try to get more details about this

**Comment by get-itips** [comment]
@scanum
