### ISSUE TITLE
LOB support is now supported as of 8/10/2022

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9187]
LOB and app support are now GA as noted here
https://techcommunity.microsoft.com/t5/microsoft-teams-blog/microsoft-teams-connect-shared-channels-is-moving-into-generally/ba-p/3568000

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e6deaf-68f5-e3c9-7259-775ed7662d85
* Version Independent ID: 82e6deaf-68f5-e3c9-7259-775ed7662d85
* Content: [Shared channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/shared-channels)
* Content Source: [Teams/shared-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/shared-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @TheBluLion, thank you for your feedback.

The bullet that you highlight was updated when the feature reached GA:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/9bc166635c7a55bfde7fc2660360e1e6de92079c

And the blog is referring to the following section:
![image](https://user-images.githubusercontent.com/33589238/185656181-374e4887-f126-4c61-acf7-4bae66180bff.png)

I understand that an update is not required.

**Comment by TheBluLion** [comment]
Hi Dario,
LOB apps are now supported -
as LOB is now supported line 148 should be updated to remove LOB so that it says:
Bots, connectors, and message extensions are not supported.

**Comment by dariomws** [comment]
@TheBluLion, ok, I have created a PR to apply this update.
