### ISSUE TITLE
MTRoW vs MTRoA

### ISSUE THREAD

**Issue by jlatessa** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9193]
Missed two major feature disparities:
Front row and Microsoft Teams Rooms Premium.
Front row is only supported on MTRoW.
MTR Premium is only available for MTRoW.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64cc650b-b313-cfab-9f45-190b94c128f4
* Version Independent ID: 9e93ac07-3f1b-9fd4-1907-17f0075bd837
* Content: [Teams devices for Shared Spaces feature comparison between Windows and Android - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/teams-devices-feature-comparison)
* Content Source: [Teams/rooms/teams-devices-feature-comparison.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/teams-devices-feature-comparison.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @jlatessa I'll propose to add those to the comparison table. Thank you
