### ISSUE TITLE
What should we do if...

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9194]
* We opened a ticket with the [TNS service desk](https://docs.microsoft.com/en-us/MicrosoftTeams/manage-phone-numbers-for-your-organization/contact-tns-service-desk), that is escalated and have not heard back from anyone on the status of our port order for over 48h and we requested the port to be completed tomorrow at 9am?

* A port is scheduled to complete at 9am, we opened a ticket with the [TNS service desk](https://docs.microsoft.com/en-us/MicrosoftTeams/manage-phone-numbers-for-your-organization/contact-tns-service-desk) asking to verify everything is set for our upcoming port order 2 days earlier and received no response... it is now 3pm on the day of the requested time and there is still no update?

* We are porting numbers from our old tenant to our new tenant (Inter tenant port). The numbers are assigned and actively used in the old tenant. To port the numbers they have to be unassigned, but given our concern with the above scenario we don't want to unassign the numbers until we are sure what time the Inter tenant port will start.

    I also understand the team doing the transfer is available from 8am-9pm (eastern time we presume)
    (It would be nice if Microsoft handled unassigning the numbers... but I understand why Ms might not want to do that without an admins approval... but Hi, admin here I am happy to give approval after I have all the information I need. Ask me and I'll say yes :) )

* We have a big project and want to talk to someone with experience about best practices?

If this feedback is better suited for the referenced TNS service desk article, or somewhere else, please accept my apologies in advance!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a17293e0-4c49-0e97-d5da-b48322f10928
* Version Independent ID: c38c0726-5dec-d374-6948-2188d43025ef
* Content: [What's a port order? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/phone-number-calling-plans/port-order-overview)
* Content Source: [Teams/phone-number-calling-plans/port-order-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phone-number-calling-plans/port-order-overview.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
I'm sorry, but the GitHub issues are related to issues with content--not the service desk.  I would suggest followth the procedures outlined the following article.  Or following our normal escalation channels.  https://docs.microsoft.com/en-us/MicrosoftTeams/manage-phone-numbers-for-your-organization/contact-tns-service-desk#view-and-manage-existing-cases

**Comment by jonwbstr** [comment]
@CarolynRowe Please reopen

**Comment by jonwbstr** [comment]
Another requirement of Intra Tenant ports I am suggesting is a gap in the existing content is:
service numbers and user numbers cannot be in the same port order.

In other words, create separate port orders for user numbers and service numbers.
