### ISSUE TITLE
Teams owners can archive teams via client UI

### ISSUE THREAD

**Issue by jmuehlenbein** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9195]
Seems like this article should mention that you don't need to be a Teams Admin in order to archive a team. It can be done via Teams client as long as the user is an owner of the team. Would be great if you could please clarify that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf689b7-a7c1-121f-578e-029e8a89c4f0
* Version Independent ID: 7e6b449e-bd77-2fc4-2c3d-1f2e364e1b76
* Content: [Archive or delete a team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/archive-or-delete-a-team)
* Content Source: [Teams/archive-or-delete-a-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/archive-or-delete-a-team.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @jmuehlenbein  I'll propose to add that to the article, if it gets approval, it will be in the published version of the article.
Thank you
