### ISSUE TITLE
Org-wide settings in TAC

### ISSUE THREAD

**Issue by mohmalik-MS** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9198]
Where is the Org-wide settings in TAC as mentioned in this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82f0c686-160c-100f-6d37-55033048e8d1
* Version Independent ID: 65b5b49b-5881-eb26-bfd0-4abb7eecb899
* Content: [Use supervised chats for non-educational tenants - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/supervised-chat-non-edu)
* Content Source: [Teams/supervised-chat-non-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/supervised-chat-non-edu.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
The option is now under **Teams**, thanks for your feedback, an edit to the article is coming soon
