### ISSUE TITLE
Duplicated paragraph

### ISSUE THREAD

**Issue by JorgeALeitao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9203]
Hi, there is a duplicated paragraph in section https://docs.microsoft.com/en-us/microsoftteams/app-permissions#considerations-1 

...
**By default, bots don't have the ability to act on behalf of the user, but bots can ask users to sign in; as soon as the user signs in, the bot will have an access token with which it can do additional things. Exactly what those other things are depends on the bot and where the user signs in: a bot is an Azure AD app registered at https://apps.dev.microsoft.com/ and can have its own set of permissions.**

When a file is sent to a bot, the file leaves the corporate network. Sending and receiving files requires user approval for each file.

**By default, bots don't have the ability to act on behalf of the user, but bots can ask users to sign in; as soon as the user signs in, the bot will have an access token with which it can do additional things. Exactly what those additional things are depends on the bot and where the user signs in: a bot is an Azure AD app registered at [Application Registration Portal](https://apps.dev.microsoft.com/?referrer=https:%2f%2fdocs.microsoft.com%2f#/appList) and can have its own set of permissions.**
.....

I suggest it's removed for clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0f81b0-eb71-1c7c-aa8c-25f114e57fd0
* Version Independent ID: 9103c060-c536-b3cc-170a-10c2fbfbc834
* Content: [Microsoft Teams apps permissions and considerations - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/app-permissions#considerations-3)
* Content Source: [Teams/app-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/app-permissions.md)
* Service: **msteams**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by get-itips** [comment]
Hello I am looking into this

**Comment by get-itips** [comment]
An edit by @ashishguptaiitb is coming soon

**Comment by get-itips** [comment]
Document has been updated.
