### ISSUE TITLE
Pay-As-You-Go Calling Plan is unclear

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9208]
Hello,

After working with the Microsoft 365 Support team, there seems to be a lot of confusion about the "Pay-As-You-Go Calling Plan" in this page.  It would be great if you could clarify what that plan is, how it can be purchased, and a link to more information.

Thanks!
Chris
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 243fa83d-b7bf-323a-a14a-026915d3d058
* Version Independent ID: fd4a310b-3144-4a8b-1bde-c2efd0c87377
* Content: [Calling Plans for Microsoft 365 - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/calling-plans-for-office-365)
* Content Source: [Teams/calling-plans-for-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/calling-plans-for-office-365.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Addiing @DaniEASmith

**Comment by DaniEASmith** [comment]
@chrisweis I am publishing a PR today that adds some clarifying information around this new PAYGo Calling Plan. Here is the updated text:

- **Pay-As-You-Go Calling Plan**: Licensed users can call out to numbers located in the country/region where their Microsoft 365 license is assigned to the user based on the user's location, and to international numbers in [196 countries/regions](country-and-region-availability-for-audio-conferencing-and-calling-plans/users-can-make-outbound-calls-to-these-countries-and-regions.md). Unlimited incoming minutes are included. No outgoing minutes are included. All outgoing calls are charged based on the minutes used, either with Communication Credits or Post Pay billing. Licenses are assigned to users based on their location. There are 2 options to choose from:
  - **Pay-As-You-Go Calling Plan Zone-1**: Buy this for users in the United States, including Puerto Rico, Canada, and the United Kingdom.
    - Zone 1 licenses aren't currently available for sale in the United States and Puerto Rico, but they can be provisioned to US and Puerto Rico users if bought in other countries.
  - **Pay-As-You-Go Calling Plan Zone-2**: Buy this for users in Austria, Belgium, Croatia, Czech Republic, Denmark, Estonia, Finland, France, Germany, Hungary, Ireland, Italy, Latvia, Lithuania, Luxembourg, Netherlands, New Zealand, Norway, Poland, Portugal, Romania, Singapore, Slovakia, Slovenia, South Africa, Spain, Sweden, and Switzerland.
    - Zone 2 licenses aren't currently available for sale in the United States and Puerto Rico.

Does this addition help add the level of clarity you're looking for?

**Comment by chrisweis** [comment]
Yes that clarifies that it can’t be purchased in the US, which explains why I wasn’t seeing it.  Thanks!

(I still have questions about why it can’t be purchased in the US, but that may be beyond the scope of this doc.)
