### ISSUE TITLE
Unable to delete Power Automate Posts in Teams Channel

### ISSUE THREAD

**Issue by hollyanneu2** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9210]
OK I turned on the delete option for a Channel I own. However, while I am able to delete chats within the Channel, I am NOT able to delete any Power Automate posts that I created to post test tickets. Is this a missed issue or
![Power Automate Post unable to delete](https://user-images.githubusercontent.com/51829765/185189082-18040f18-00c9-4590-9c38-5667b7507259.jpg)
?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
