### ISSUE TITLE
Ported numbers 

### ISSUE THREAD

**Issue by NickElniff** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9213]
The article does not mention numbers ported over from other carriers. Which don't count towards the limits outlined in the doc, would be ideal to have a footnote that customers can port as many numbers as they would like and they don't impact the numbers that can be acquired from Microsoft directly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad4b757-bff7-5fbc-9490-2eeadb9f7039
* Version Independent ID: e1b15411-ce16-41da-aec5-fc06844673c2
* Content: [How many telephone numbers can you get? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/how-many-phone-numbers-can-you-get)
* Content Source: [Teams/how-many-phone-numbers-can-you-get.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/how-many-phone-numbers-can-you-get.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @NickElniff, thank you for your feedback.

The following note is included in the article:

> [!IMPORTANT]
> The limits below don't include telephone numbers you have ported to Microsoft.
