### ISSUE TITLE
Update licensing references

### ISSUE THREAD

**Issue by fdelavier** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9220]
Hi,

The licensing bundles has changed.
E1/E3/E5 licenses doesn't exist anymore.
Same for business Voice licences, as explained here : https://docs.microsoft.com/en-us/microsoftteams/business-voice-to-teams-phone-licenses?tabs=single-user

Could you please change the old licencing references ?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb0c2ef-6274-9167-ecc6-3695d7460a8d
* Version Independent ID: aacf7318-02fc-a1c3-369c-65e6936fdb3c
* Content: [Configure Session Border Controller - Multiple tenants - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants)
* Content Source: [Teams/direct-routing-sbc-multiple-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-sbc-multiple-tenants.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @fdelavier Fabien, how are you?

To clarify, what do you mean by "E1/E3/E5 licenses doesn't exist anymore." ?

And Business Voice licenses are not mentioned in the _Configure a Session Border Controller for multiple tenants_ article

Thanks for clarifying and please let me know if I misunderstood you.

**Comment by fdelavier** [comment]
Hi Andres,

My mistake.

Technically E1/E3 still exist for Enterprises : https://www.microsoft.com/en-us/microsoft-365/compare-microsoft-365-enterprise-plans
But small & medium companies use other kind of packages : https://www.microsoft.com/en-us/microsoft-365/business/compare-all-microsoft-365-business-products

In our case we'd E1/E3 licenses (+ phone system), which have been migrated to "Microsoft 365 Business Basic/Standard/Premium" licenses (+ Microsoft 365 Business Voice, which call the phone system app) few years ago.
Now it seems that there is new changes in this licensing model.

So my point is: the licencing model detailed in the documentation doesn't match the one designed for small and medium companies.

Would it be possible to update the documentation (other pages may also be concerned. Ex: https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan) in order to take into account the different kind of licencing model proposed by Microsoft ?

Thanks,
Fabien

**Comment by get-itips** [comment]
Hello @fdelavier Fabien, thanks for detailing.
Just to clarify, probably you refer to the licensing requirements listed under _Activate the subdomain name_, right?. Thanks

**Comment by fdelavier** [comment]
Hi Andres,

Correct, my need is for section "Activate the subdomain name".

That being said, maybe it might be a good idea to also update other pages of the documentation.

Thanks

**Comment by CarolynRowe** [comment]
Adding @DaniEASmith ,
@JensTrier, @FilippS:  Can one of you help with this?

**Comment by DaniEASmith** [comment]
@JensTrier & @Filipps I emailed last week about this request, for reference.

In the "Activate the domain name" section, the doc lists which acceptable user accounts/licenses can activate the domain name.

The GitHub Issue submitter is stating that the user accounts and subscriptions listed are incorrect, or at least incomplete.

The submitter would like us to add that Microsoft 365 Business Basic/Standard/Premium are acceptable, as are G3/G5 plans.

Before updating this page, we want to confirm the Teams user account license requirements from you both.

**Comment by DaniEASmith** [comment]
@fdelavier & @get-itips This issue will be resolved with the publication of this PR today: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/9420.
