### ISSUE TITLE
PS command for Get-Content is incorrect

### ISSUE THREAD

**Issue by JG-Robo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9221]
$content = Get-Content "C:\tmp\customMoH1.mp3" -Encoding byte -ReadCount 0 
Should be
$content = Get-Content "C:\tmp\customMoH1.mp3" -AsByte -ReadCount 0
As the -Encoding parameter does not have a "byte" method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 416f3cdb-ca75-8224-bc04-985e5f7ea9dd
* Version Independent ID: 6e8c6f33-8043-e367-b44b-74b5f5ee96f2
* Content: [Music on Hold - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/music-on-hold)
* Content Source: [Teams/music-on-hold.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/music-on-hold.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @JG-Robo, thank you for your feedback.

From the article:
"An example of uploading an MP3 audio file using Windows PowerShell 5.1 is shown below"

Please check Get-Content help: for PS 5.1
https://docs.microsoft.com/powershell/module/microsoft.powershell.management/get-content?view=powershell-5.1
The parameter is -Encoding byte. You can also see it in Example 8.

PS 7.x:
https://docs.microsoft.com/powershell/module/microsoft.powershell.management/get-content?view=powershell-7.2
The parameter is -AsByteStream. You can also see it in Example 8.

**Comment by scanum** [comment]
@JG-Robo Hope all is well. Does this answer your questions? Thanks

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
