### ISSUE TITLE
The text in this page is misleading.

### ISSUE THREAD

**Issue by larhem** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9224]
Theese two (1 and 2) are copy/pasted from the article.  NR 1 is telling that you can still see apps but they are blocked, and NR 2 is saying that they will not appear at all. As far as i can when testing its only nr 2 that is correct behaviour when you block "Shared Power Apps".

1.
The Shared Power Apps and Shared Power Virtual Agent Apps apps in your organization's app store represent all apps created on that particular platform. If you block one or both these apps for entire org or for specific users, the users can view such apps as blocked apps, but can't install them in Teams. The users can [request admin approval to allow apps](https://docs.microsoft.com/en-us/microsoftteams/manage-apps#manage-user-requests-to-allow-apps).

2.
Keep in mind that you can control access to all apps created in Power Apps and Power Virtual Agents but you can't allow or block individual apps. The app creator decides who can access the apps they create through the sharing feature from within Power Apps and Power Virtual Agents. If a maker shared an app they created in Power Virtual Agents with a user and you blocked Shared Power Virtual Agents Apps for that user, the user won't be able to see or install any apps from that platform in Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a9e2a4f-0f02-d573-f3dc-692f4b75c581
* Version Independent ID: 38496171-4c3e-11a7-7676-f6b8f3666dd6
* Content: [Manage Microsoft Power Platform apps in the Microsoft Teams admin center - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-power-platform-apps)
* Content Source: [Teams/manage-power-platform-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-power-platform-apps.md)
* Service: **msteams**
* GitHub Login: @guptaashish
* Microsoft Alias: **guptaashish**

**Comment by get-itips** [comment]
Hello @larhem 
I am looking into this

**Comment by get-itips** [comment]
Hello @larhem 
I could verify that the behavior is indeed that the users won't be able to see the created in Power Platform apps.
I'll propose an edit to the article. Thanks for  your feedback
