### ISSUE TITLE
UK Calling Plans

### ISSUE THREAD

**Issue by d1bjo0** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9225]
The domestic calling plan for the UK support 3000 min domestic, the below show 1200, this is incorrect. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81c54644-ec0b-0f36-2977-e5aa9238269c
* Version Independent ID: 67a9ad22-007a-6eb1-5956-fb6950a7946f
* Content: [Availability in the United Kingdom (U.K.) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-kingdom-u-k)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-kingdom-u-k.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-kingdom-u-k.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello, I am trying to confirm this, can I kindly ask where did you see this update? Thank you

**Comment by get-itips** [comment]
I could not get any confirmation or more information about any change to the UK Calling plan minutes, in any case this can be re-opened. Thanks
