### ISSUE TITLE
Canada Domestic Calling Plan

### ISSUE THREAD

**Issue by d1bjo0** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9226]
The domestic calling plan for the UK &Canada both support 3000 min domestic, the below show 1200, this is incorrect. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81c54644-ec0b-0f36-2977-e5aa9238269c
* Version Independent ID: 67a9ad22-007a-6eb1-5956-fb6950a7946f
* Content: [Availability in the United Kingdom (U.K.) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-kingdom-u-k)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-kingdom-u-k.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-kingdom-u-k.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @d1bjo0, thank you for your feedback.

I'll try to confirm this information.

I see that you also opened another issue:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9225

Could you share a screenshot of your tenant with the availability of the domestic calling plan?

**Comment by dariomws** [comment]
Also very similar to:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9242

**Comment by dariomws** [comment]
@d1bjo0, I'm applying an update to the article. 3000 minutes for the US and Canada.

Do you mean the US instead of the UK?
