### ISSUE TITLE
Please add a section with supported clients

### ISSUE THREAD

**Issue by paul-lange** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9230]
My understanding is that the following clients are supported:
•	Teams Desktop (Windows und Mac)
•	Teams Mobile
•	Teams Rooms in Windows

Could you please add them in the article?

Sources:
https://techcommunity.microsoft.com/t5/microsoft-teams-blog/use-end-to-end-encryption-for-one-to-one-microsoft-teams-calls/ba-p/2867066
https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-release-note#4131320-822022

Regards,

Paul

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56b532a-ab80-0e4c-dcd8-829a0a68c08e
* Version Independent ID: e56b532a-ab80-0e4c-dcd8-829a0a68c08e
* Content: [End-to-end encryption for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-end-to-end-encryption)
* Content Source: [Teams/teams-end-to-end-encryption.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-end-to-end-encryption.md)
* Service: **msteams**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by get-itips** [comment]
Hello @paul-lange Paul, thanks for your feedback, I'll propose an edit to the article.
