### ISSUE TITLE
Add "Limits for shared channels" for OneDrive Client

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9233]
When i try to sync a Files in a SharedChannel from a Remote-Tenant, this should work or not?
Is this a Limitation for external User?

![image](https://user-images.githubusercontent.com/26062079/186161596-b6c51352-aa1e-435c-a6cf-b57fee0ea2a5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e6deaf-68f5-e3c9-7259-775ed7662d85
* Version Independent ID: 82e6deaf-68f5-e3c9-7259-775ed7662d85
* Content: [Shared channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/shared-channels)
* Content Source: [Teams/shared-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/shared-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@JasonLewisMSFT can you comment?

**Comment by JasonLewisMSFT** [comment]
Not sure where that screen is from. We don't support OneDrive for Business with Shared Channels. All files are hosted in SPO site for the channel.

**Comment by weyCC81** [comment]
This is not totaly right, i am able to sync a Shared Channel in my own organisation even when it has a strange name...
When i sync a second one it gets even better:
![image](https://user-images.githubusercontent.com/26062079/186437820-1ddba6bd-c679-4c38-a5df-8140c1d77d9d.png)

So this does just apply to external user?

**Comment by weyCC81** [comment]
Did something change here?, now this appearded:
![image](https://user-images.githubusercontent.com/26062079/191427015-5daba8d8-eb11-4cb6-972f-b866a48fb5f9.png)

**Comment by scanum** [comment]
Hi @MikePlumleyMSFT and @JasonLewisMSFT hope all is well. is there an update here? Thanks!

**Comment by scanum** [comment]
Hi @MikePlumleyMSFT and @JasonLewisMSFT hope all is well. is there an update here? Thanks!

**Comment by scanum** [comment]
Thanks @MikePlumleyMSFT !

@weyCC81 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by weyCC81** [comment]
MFA is not supported for B2B sync
[B2B Sync - SharePoint in Microsoft 365 | Microsoft Learn](https://learn.microsoft.com/en-us/sharepoint/b2b-sync)

Currently the sync client does not support interactive authentication UI when syncing external content. Any policy that would require a sign-in UI such as MFA (multi-factor authentication) or TOU (terms of use) prompt, will prevent the syncing of the external content from that tenant. If a tenant admin deploys such a policy before a guest starts syncing from that tenant, the user will be unable to establish the sync relationship. If the policy is deployed after a guest is syncing content from the tenant, that guest will receive an error and be unable to continue to sync from the tenant.
