### ISSUE TITLE
Page needs update to remove reference to unsupported features and text

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9235]
1. Teams doesn't support logomark anymore
2. Text on this page refers to the "Built for your tenant" section, but the wording used in product is actually "Built for your org"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfaea5f2-b19c-6170-8f7c-a20712358b46
* Version Independent ID: 974ed15e-e9a3-1559-1a5c-9636f09240b2
* Content: [Customize your app store in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/customize-your-app-store)
* Content Source: [Teams/customize-your-app-store.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/customize-your-app-store.md)
* Service: **msteams**
* GitHub Login: @guptaashish
* Microsoft Alias: **guptaashish**

**Comment by get-itips** [comment]
Hello @aosolis I am looking into this

**Comment by ashishguptaiitb** [comment]
This issue is resolved via the linked PR and doc updates will go live soon.
