### ISSUE TITLE
Wrong to use "at a minimum"

### ISSUE THREAD

**Issue by biilmanndk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#924]
Under the Azure AD B2B section, you write "At a minimum to support guests, Members can invite must be set to Yes." - but the following text box describes that this is an option - you can set the "Members can invite" setting to No - if you want your admins to be responsible for adding external users to Azure AD. So, it makes no sense to use "at a minimum" here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams Guest Access checklist](https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @romanma
* Microsoft Alias: **romanma**

**Comment by AndreaBarr** [comment]
@biilmanndk  The pull request has fixed this issue. I am closing this issue.
