### ISSUE TITLE
Resource Account license allocation

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9241]
Below statement seems incorrect  **"Teams Phone Standard and Teams Phone with Calling Plan licenses,"**   we need any one of the license Teams Phone Standard **or T**eams Phone with Calling Plan licenses.  We dont need both at same time.

Your organization is allotted Microsoft Teams Phone Resource Account licenses depending on its overall size. Any organization that has at least one license with Teams Phone System features, including Teams Phone Standard and Teams Phone with Calling Plan licenses,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6891495-01c6-117b-c28b-28232782ba74
* Version Independent ID: 1c23b35a-e9ba-ffdd-9baa-a3f83f4ed9ca
* Content: [Microsoft Teams Phone Resource Account licenses - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/virtual-user)
* Content Source: [Teams/teams-add-on-licensing/virtual-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/virtual-user.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @robinpoulose1, thank you for your feedback.

I think that sentence looks good. It means that Teams Phone Standard and Teams Phone with Calling Plan are both a subscription with Phone System features.

Next paragraph:
"For every 10 user licenses of Teams Phone Standard or Teams Phone with Calling Plan in your organization, one more Teams Phone Resource Account license becomes available."
