### ISSUE TITLE
Calling Plan Minutes- Correct or incorrect?

### ISSUE THREAD

**Issue by jamiee4lynne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9242]
[Hey folks, I'm a Teams Technical Specialist at Microsoft and there's a conflict of information I wanted to clear up. The Calling Plans listed at the bottom of this page reference having 1200 minutes for Domestic Calling Plans but the Country and Region Availability excel sheet provided at the top of the article shows that the US & Canada get 3000 minutes with Domestic Calling Plans. I also verified that both US and Canadian demo tenants reflect 3000 minute plans. So is our documentation incorrect or is something changing with our Calling Plan Capacities? Thanks! ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2b2f00a-d4ee-28ab-8c9f-fdc858eb30a4
* Version Independent ID: 07d9aa8b-7e6c-a340-bc75-f0c8159f6c57
* Content: [Availability in the United States (U.S.) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-states-u-s?source=docs)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-states-u-s.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-states-u-s.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe*
![Calling Plan minute reference in tenant](https://user-images.githubusercontent.com/70410593/186935526-34b6f53c-d1d5-49b6-83c8-7ef3d848757f.jpg)
![Calling Plans 1200 min reference](https://user-images.githubusercontent.com/70410593/186935543-33e4ed62-31ab-4a13-89d2-cfb8e0ad2558.jpg)
*

**Comment by get-itips** [comment]
Article has been updated.
