### ISSUE TITLE
Update steps 

### ISSUE THREAD

**Issue by gervs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9248]
Complete the following steps to provision a new device.

Sign in to the Teams admin center.
Expand Teams Devices.
Select Provision new device from the Actions tab.

It should be Teams admin center > Teams devices > Teams Rooms on Android > Actions on the right part of the page > Provision devices. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 344ac314-e98e-ab21-ef47-fb0da80ec884
* Version Independent ID: 8f3d2fe8-5d96-4298-f875-fb3e64688afc
* Content: [Remote provisioning and sign in for Teams Android devices - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/devices/remote-provision-remote-login)
* Content Source: [Teams/devices/remote-provision-remote-login.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/remote-provision-remote-login.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
