### ISSUE TITLE
To remove Assignments and Grades, both apps should be blocked instead of just Assignments

### ISSUE THREAD

**Issue by v-schintala** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9249]
Hi Team,

One of our customers created a case saying he couldn't block Grades following this documentation as it says to block assignments and grades apps for class team for the tenant, select Assignments to see them blocked. But we have to select both Assignments and Grades apps to block or disable and selecting one doesn't fix the issue. 

Please update the documentation that both the apps Assignments and Grades from Teams admin center needs to be blocked.

URL: https://docs.microsoft.com/en-us/microsoftteams/expand-teams-across-your-org/assignments-in-teams#removing-assignments-and-grades

![image](https://user-images.githubusercontent.com/89413884/187307385-159111b9-aad6-4bca-914c-4da8cf28a7b3.png)

Thanks,
Sashi.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dec403d-8a7f-376f-3af7-79c46f00868e
* Version Independent ID: 812a114b-1207-d560-b3e8-9a01dae29c6b
* Content: [Assignments for Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/expand-teams-across-your-org/assignments-in-teams#removing-assignments-and-grades)
* Content Source: [Teams/expand-teams-across-your-org/assignments-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/expand-teams-across-your-org/assignments-in-teams.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@v-schintala Here is a PR where I address this issue: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/9252. Is this sufficient?

**Comment by DaniEASmith** [comment]
@v-schintala and @scanum, the updated page has gone live. I believe we can close this issue now.

Link to the updated page: https://docs.microsoft.com/en-us/microsoftteams/expand-teams-across-your-org/assignments-in-teams#removing-assignments-and-grades.

**Comment by DaniEASmith** [comment]
Closing because this has been resolved with the above PR that has been published.

**Comment by v-schintala** [comment]
Thank you so much Dani!
