### ISSUE TITLE
Heading instead of issue

### ISSUE THREAD

**Issue by biilmanndk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#925]
There's a heading in here that should by a github issue: "Need a new screenshot for new Admin Center enablement." Just so it won't be forgotten!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams Guest Access checklist](https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @romanma
* Microsoft Alias: **romanma**

**Comment by AndreaBarr** [comment]
@biilmanndk The article has been updated and the screenshot is now current. I am closing this issue at this time. If this issue is not resolved please re-open this issue.
