### ISSUE TITLE
Incomplete sentence.

### ISSUE THREAD

**Issue by Atreidae** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9251]
in step 2 point 5 we state "Set the password for your common area phone manually to prevent."

What are we trying to prevent?
looking at the note below it I assume its sign-in issues for users

Suggest updating the page to read "Set the password for your common area phone manually to prevent sign-in issues for users"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ab5215-f24f-75cf-bb92-16ac0ff5e5ca
* Version Independent ID: 701cc58f-d2ea-cbb6-f5fc-47b9fbfb1119
* Content: [Set up the Common Area Phone license - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-common-area-phones)
* Content Source: [Teams/set-up-common-area-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-common-area-phones.md)
* Service: **msteams**
* GitHub Login: @cazawideh
* Microsoft Alias: **czawideh**

**Comment by dariomws** [comment]
Hi @Atreidae, thank you for your feedback.

The article was updated 2 months ago to fix this sentence:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8979
