### ISSUE TITLE
Can one give meeting in private channels a name or not

### ISSUE THREAD

**Issue by bjk17** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9253]
There is missing information about whether one can give meetings in private channels (using "Meet now" feature) a name or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @bjk17 
Instead of what can be done, the limitations are listed in the article, and for channel meetings it says

> Channel meetings can't be scheduled.

So Meet now (and I checked) is available.

Please let me know if I understood your inquiry correctly, thanks

**Comment by get-itips** [comment]
I re-read your question and now I understand better, you want to know if a name can be given to the meeting in a private channel, that doesn't seem possible at the moment.

**Comment by bjk17** [comment]
Hi @get-itips ,

> if a name can be given to the meeting in a private channel

Yes, this is what I find lacking in the documentation. I do agree that it doesn't _seem_ possible, but to be sure I ended up reading this documentation page. My suggestion is to make it clear in the documentation if or if not it's possible.

**Comment by get-itips** [comment]
@bjk17 I'll propose that. Thanks
