### ISSUE TITLE
Clarification regarding which connectors are possible to use in Government Community Cloud environments

### ISSUE THREAD

**Issue by brandonmcclure** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9255]
I would like some clarification regarding which connectors are possible to use in Government Community Cloud environments. The documentation says that : 
```
Custom connectors are not available in Government Community Cloud (GCC), Government Community Cloud-High (GCCH), and Department of Defense (DOD) environments.
```

I am being told by my administrator that this includes the basic incoming webhook, but this documentation does not make it clear if all connectors (such as a generic webhook) are blocked in a Government tennet or just custom ones that I publish to my org's app catalog. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5eb6a35-32fa-6703-8ed2-0855e602b7d5
* Version Independent ID: 7890ca09-d505-35a9-071a-8662a4b19275
* Content: [Manage Microsoft 365 and custom connectors - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/office-365-custom-connectors)
* Content Source: [Teams/Office-365-custom-connectors.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-custom-connectors.md)
* Service: **msteams**
* GitHub Login: @guptaashish
* Microsoft Alias: **guptaashish**

**Comment by get-itips** [comment]
Hello @brandonmcclure Brandon,

Does this answers your question?

https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=webhook

Let me know and thanks for your feedback

**Comment by get-itips** [comment]
Hello @brandonmcclure Could you see my comment here? thanks

**Comment by get-itips** [comment]
@scanum
