### ISSUE TITLE
5-digit Dial Plan Normalisation is wrong

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#926]
With a matching pattern of ^5(\d{4})$ and a translation rule of +1425555$1,  
50100 is translated to +142555550100
All these 5s are confusing, could you adapt the example please so that this can be understood easier? :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93aec556-e897-9651-55ce-bfee7fd7f021
* Version Independent ID: b411b2f5-49c6-d883-6570-d5526f636a6b
* Content: [Plan for outbound voice routing in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/enterprise-voice-solution/outbound-voice-routing)
* Content Source: [Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/outbound-voice-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/outbound-voice-routing.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by AndreaBarr** [comment]
@DEberhardt Thank you for this feedback. 

I will get this request to adapt the example to the Teams/Skype for Business team. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Thanks @DEberhardt for taking the time to submit feedback.
I checked the matching pattern and the translation rule. If you enter 50100 it will translate to +14255550100 as the documentation says:

You probably know this but ^5(\d{4})$ regex means: Must start with a 5 and keep the next 4 digit numbers so it will remove the first 5, because is not inside the parenthesis, only 0100 will be kept and it will end up being +14255550100 (four 5s)

In the other way, if the pattern would be ^(5\d{4})$ it will keep the digit 5.

Hope this information helps you out.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @DEberhardt  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by DEberhardt** [comment]
Thank you for the feedback!
So I have learned that only the numbers inside the parent his are kept - good.

Even though the example is correct, may I still ask for it to be changed so that the example is clearer?
(I could have figured it out, I think ;))

Thanks,
David

Best regards,
David

Apologies for the brief nature of this email as it has been sent from my phone.

________________________________

**Comment by CarolynRowe** [comment]
Thank you for your feedback.  555 is a common usage so that we don't publish a live phone number. I'm going to go ahead and close this.

**Comment by DEberhardt** [comment]
You can still change the extension....

Best regards,
David

Apologies for the brief nature of this email as it has been sent from my phone.

________________________________
