### ISSUE TITLE
Teams Memory Issues

### ISSUE THREAD

**Issue by PStoner3** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9264]
Reading through this article, I either have a serious issue with my laptop, or Teams is not functioning as described.

When I start Teams clean there are anywhere between 7 and 9 sub processes running at anyone time and the memory consumption is just under 600 MB. but as I start to run my development tools, the memory usage drops. but not significantly.

Teams initial start up
![teams_mem](https://user-images.githubusercontent.com/17929362/187710329-bce5c540-57cc-479e-85ab-4b75dd798071.png)

Teams with Intellij
![teams_mem_intellij](https://user-images.githubusercontent.com/17929362/187710457-45d47af5-4506-455a-9de3-ccd789d5a111.png)

Teams with Intellij and Docker Desktop
![teams_mem_intellij_docker](https://user-images.githubusercontent.com/17929362/187710540-ae632225-32df-4349-ad9a-5fb4e209119a.png)

So yes, the Teams memory usage did drop by 26.5 MB but I would not consider that enough to keep me from hitting out of memory issues.

My system has 16 GB of memory installed with 15.8 usable
![system_specs](https://user-images.githubusercontent.com/17929362/187711364-df04a763-35db-4ec8-8aab-b7dfa1a48b1e.png)

So is this an issue with Teams or my system?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc21902c-d522-3851-8587-177f01bc085c
* Version Independent ID: 590bcc64-a86d-b61e-7d94-4e4322c4e71d
* Content: [How Microsoft Teams uses memory - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-memory-usage-perf)
* Content Source: [Teams/teams-memory-usage-perf.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-memory-usage-perf.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @PStoner3 Paul,
Here, we are limited to documentation issues and fixes, for your inquiry, the best would be to open a support request from your tenant.
Thanks,

**Comment by get-itips** [comment]
@scanum
