### ISSUE TITLE
Analog Contact objects use of Dial Plans

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#927]
Hello,
may I have some clarification on which Dial Plans an Analog Contact object can have?
So far I found out that the Global Dial Plan - as stated - will be used by Analog Contact objects, but a User Dial Plan is not (despite being able to have one assigned).

Unclear is the combination of Contact Object and Pool or Site Dial Plan.
Can you please update/clarify.

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93aec556-e897-9651-55ce-bfee7fd7f021
* Version Independent ID: b411b2f5-49c6-d883-6570-d5526f636a6b
* Content: [Plan for outbound voice routing in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/enterprise-voice-solution/outbound-voice-routing)
* Content Source: [Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/outbound-voice-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/enterprise-voice-solution/outbound-voice-routing.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by AndreaBarr** [comment]
@DEberhardt Thank you for this feedback

I will get this over to the Teams/Skype for Business team for investigation. If you need an expidited answer please contact Support. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @DEberhardt 
Thanks for taking the time to submit feedback, we really appreciate it.
I analyzed the information you gave us.
Let me tell you that, exactly as you said, Global dial plan is used for analog devices/contacts. Unless you set a Site dial plan, if you set one, the Site Dial Plan will be used.

Hope that information answers your question, and again thanks for your submission.

**Comment by yogkumgit** [comment]
@get-itips   Thank you very much for the contribution and sharing this explanation. @DEberhardt 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
