### ISSUE TITLE
The "Shared Channel Creation" section contains zero information about how to create a shared channel

### ISSUE THREAD

**Issue by olofh-msft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9271]
This page: 

https://docs.microsoft.com/en-us/microsoftteams/shared-channels

is about Shared channels in Microsoft Teams.  There's a whole section called "Shared channel creation" with literally zero about how to create a shared channel.  I cannot fathom how this document came to be.  It's like a parody of bad documentation.

     

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e6deaf-68f5-e3c9-7259-775ed7662d85
* Version Independent ID: 82e6deaf-68f5-e3c9-7259-775ed7662d85
* Content: [Shared channels in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/shared-channels)
* Content Source: [Teams/shared-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/shared-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@olofh-msft this article is for Teams admins who will be administering shared channels for their organizations. The [resources](https://docs.microsoft.com/microsoftteams/shared-channels#resources-for-your-users) section has links to end user content that includes information on creating shared channels.
