### ISSUE TITLE
Dark Mode Teams App color

### ISSUE THREAD

**Issue by SamanthaSt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9274]
Hello, 

I customized my  Viva Connections to use our organisation color. This is working great in light mode. 
Now i realised if I switch Teams to dark mode that my customized color is ignored and we again use the default Teams primary color. 

I couldn´t find anything online. So is there a way to customize the teams app color in dark mode also? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cb13dd7-3253-5406-0738-8c53ffc47752
* Version Independent ID: f843f426-6f77-691f-496a-e833efe7309e
* Content: [Modify the appearance of apps in your organization's Teams store - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/customize-apps)
* Content Source: [Teams/customize-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/customize-apps.md)
* Service: **msteams**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by ashishguptaiitb** [comment]
Hi @SamanthaSt , there is no way to do app customization so that it works in the dark mode.
