### ISSUE TITLE
Auto Attendant and Call Queues not available in Georgia

### ISSUE THREAD

**Issue by lcansby** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9275]
Auto Attendant and Call Queue numbers are not available in Georgia, please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04e70e55-6e6f-3c16-ad5d-6368953bd12a
* Version Independent ID: d83a555c-71de-a473-becb-57a4d0a47b2f
* Content: [Availability in Georgia - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-georgia)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-georgia.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-georgia.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @lcansby I am looking into this, thanks

**Comment by get-itips** [comment]
Hello @lcansby 
I managed to get more information about this, 

The table _Phone System_ in this type of articles is only describing Phone System, it is not scoped only to Calling Plans.

The team is working on improving the clarity of these country availability pages as a whole.

Thanks for your feedback!
