### ISSUE TITLE
why is it saying i need an account license i just logged out and want to log in again!

### ISSUE THREAD

**Issue by srijesh2811** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9277]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af87d2a8-11f7-5384-0b2e-c1825f591347
* Version Independent ID: 501c7bff-cbf6-0288-d533-8f31dfc296a6
* Content: [Assign Microsoft Teams licenses for education - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-edu-licensing)
* Content Source: [Teams/teams-edu-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-edu-licensing.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
