### ISSUE TITLE
Teams client start menu entry missing (W7)

### ISSUE THREAD

**Issue by NorbertKlein-Ildefeld** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#928]
After installing current Teams version Teams_windows_x64-1.1.0.25457.exe I do no longer see any shortcut in Start Menu (Windows7). A bit of an issue if users disable autostart. 
From a previous installation I know the command line is
%localappdata%\Microsoft\Teams\Update.exe --processStart "Teams.exe"

**Comment by AndreaBarr** [comment]
@NorbertKlein-Ildefeld Thank you for this feedback

I want to make sure this missing shortcut issue is addressed properly. Let's get you over to Support, they have more resources to dig in and figure out what is going on. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by NorbertKlein-Ildefeld** [comment]
MSFT support have confirmed this to be a known issue. Response:
"With this mail I would like to inform you about the further actions regarding your service request No: 11844081. If anything is unclear feel free to get back to me by replying to this email. 
I just want to let you know, that this is a know issue which is being worked on and according to latest information, it should be resolved in Friday this week. And yes, I am able to reproduce this from my side as well.

**Comment by NorbertKlein-Ildefeld** [comment]
issue resolved in latest Teams client v1.1.00.28562
