### ISSUE TITLE
Walkie Talkie mode, but still not PTT in meetings?

### ISSUE THREAD

**Issue by brodiefairhall** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9280]
I'm not entirely sure who does market research for the MS Teams team, or whether they read the mountains of community feedback about teams. The Walkie Talkie feature seems like something that is dreamed up by a manager who is upset they can't walk into the office of remote workers to "talk at them" (not to be confused with "talk to them"). It's going to be turned off by everyone unless it is forced on by admin.
So much effort was put into this unwanted feature, but a much NEEDED feature like "Push To Talk" in meetings has been ignored.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d91ddefc-3722-8bc2-bd9b-4a90ede28944
* Version Independent ID: 35e56a9d-a01c-4126-3750-aae1ed984f55
* Content: [Walkie Talkie app in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/walkie-talkie)
* Content Source: [Teams/walkie-talkie.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/walkie-talkie.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanachin**

**Comment by get-itips** [comment]
Hello @brodiefairhall Brodie, how are you?

Here, we are limited to documentation fixes, like missing information or typos, or errors, to share feedback, the best resource is

https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472

Thank you
