### ISSUE TITLE
Please provide manual update script for Teams Rooms 4.14.24.0

### ISSUE THREAD

**Issue by DF9TS** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9282]
Please provide update script for 4.14.24.0 in the update article.

This article describes manual update for Teams Rooms:
https://docs.microsoft.com/en-us/microsoftteams/rooms/manual-update

The article proposes a Porshell script to update Teams Rooms to version 4.13.132.0
The newest version of Teams Rooms now is 4.14.24.0

Tnx

Gerd.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4fa80cf-0319-c006-e886-4929a508b04c
* Version Independent ID: 9d598765-fc30-17f0-6594-57de81d8aa39
* Content: [Manually update a Microsoft Teams Rooms device - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/manual-update)
* Content Source: [Teams/rooms/manual-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/manual-update.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by K2Kris** [comment]
Link has been updated and pointing to the correct file.
