### ISSUE TITLE
Diagram 5-8 are missing from Plan for Local Media Optimization for Direct Routing

### ISSUE THREAD

**Issue by bailey044** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9285]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbab466f-88f8-302a-7cda-d53bc743e831
* Version Independent ID: b5634fb3-6627-3fcd-101c-0ebc419d7b19
* Content: [Local Media Optimization for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-media-optimization)
* Content Source: [Teams/direct-routing-media-optimization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-media-optimization.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by bailey044** [comment]
https://docs.microsoft.com/en-us/microsoftteams/direct-routing-media-optimization

**Comment by get-itips** [comment]
Thanks for your feedback!
