### ISSUE TITLE
Update Skype for Business on Mac supportability

### ISSUE THREAD

**Issue by NicholasBurkhammer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#929]
Requesting documentation update.  Under Client and Server Support, it is listed that a conference will fall back to RDP if Skype for Business on Mac is used and the user is not homed online.  Skype for Business Server 2015 CU7 added support for meetings (https://support.microsoft.com/en-us/help/4132315/vbss-is-available-for-skype-for-business-on-mac).  Per RFC, P2P not explicitly tested.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43190e0d-852f-8066-510f-76cad6fcae85
* Version Independent ID: ee3209ad-6e6e-6640-c46d-4017d628358f
* Content: [Video based Screen Sharing for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/manage/video-based-screen-sharing)
* Content Source: [Skype/SfbServer/manage/video-based-screen-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/video-based-screen-sharing.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by AndreaBarr** [comment]
@NicholasBurkhammer Thank you for this feedback

I'll get this informaiton over to the Team/Skype for Business team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @NicholasBurkhammer thanks for sharing feedback, we really appreciate it.

Information regarding support in CU7 was added in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/8a76be75d9b5b3b36ae90cf1c0d9da7fb677eb8e#diff-8ecca33208baf83d736c01615af7a5bd

Thank you.

@yogkumgit I think we can close this one now.
