### ISSUE TITLE
Firewall ports requirements from CVI towards Microsoft Teams Infrastructure

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9293]
Hi,

There seems to be some confuses on the air what connections are required on here:
![image](https://user-images.githubusercontent.com/43988151/189108202-a264d212-4d9f-4c31-99d4-cb02e0f1cb76.png)

Vendors are referring to Microsoft's requirements: the destination port on where to connect on Microsoft Teams infrastructure should be **any**. This means that all the ports including well-known ports between 0 - 1023 should be open as well. From pure technical point if view this sounds super odd, and unsecure.

But also when comparing this to Microsoft own documentation: [Office 365 IPs and Ports for Skype/Teams](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#skype-for-business-online-and-microsoft-teams), there is big differences to this.

So is anybody on here aware of able to confirm what ports should be open towards Microsoft Teams infrastructure from the CVI setup?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 046dec87-2354-a9db-ae19-3bfaa2626bef
* Version Independent ID: 23e7d18f-bbab-75e1-7c85-9b0d0e8f4382
* Content: [Cloud Video Interop for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-video-interop)
* Content Source: [Teams/cloud-video-interop.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-video-interop.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @Petri-X how are you?
Let me clearly understand, do you mean from the partner point of view, not from the end user/customer, right?
Thanks for clarifying,

**Comment by Petri-X** [comment]
@get-itips 
We are planning to implementing this service by our own to our own Azure platform, as the vendor is offering such a deployment as well. When reading the deployment guide this FW rule question came up, and it just not make any sense. But as Microsoft makes the requirements to them, they cannot do anything for it. So I thought to ask if here is anybody how could open this puzzle anyhow.

**Comment by get-itips** [comment]
Thanks @Petri-X 
I could get information that the service can't be implemented on your own at the moment, so I cannot help you any further with the information you are looking for.

**Comment by Petri-X** [comment]
Ok, nice to hear.

Then this must be wrong:
[Planning, prerequisites and firewall ports for your Microsoft Teams integration](https://docs.pexip.com/admin/teams_planning.htm)

...or not, who knows. I believe there could be a tiny possibility that your source does not know all? 😄
