### ISSUE TITLE
ediscovery/content search is able to find all edited messages of a chat/channels message without a hold

### ISSUE THREAD

**Issue by Teamsgineer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9296]
Hi,
the statement:
" Important
When a user or group is placed on hold, all compliance copies of messages are preserved. For example, if a user posts a message in a channel and then modifies the message, both copies of the message are preserved. Without the hold, only the latest message is preserved. "

is not too accurate as when performing a Content Search **without a Hold**, all the edited messages in a channel/chat are able to be found, and not just the last edited message. all the edited messages can be found by doing a Content Search on the user, and using KQL filter Kind:microsoftteams .

feedback is to provide better written clarity in this doc, of what is able to be discovered in Content Search without the Hold for edited/deleted chat/channel messages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0c70e2a-c370-01ae-c46a-3a1d0b95fd61
* Version Independent ID: a3d2b15f-8900-491a-c71a-ab16db108376
* Content: [Place a Microsoft Teams user or team on legal hold - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/legal-hold)
* Content Source: [Teams/legal-hold.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/legal-hold.md)
* Service: **msteams**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by dariomws** [comment]
Hi @Teamsgineer,

The messages are removed in Teams after 1-7 days if there is not a retention policy. For more information:
https://learn.microsoft.com/microsoft-365/compliance/retention-policies-teams

**Comment by Teamsgineer** [comment]
hi @dariomws , 
it would be very useful for Teams/M365 admins to see the above note in this document. Any chance it can be added?
Many companies inquire for how long messages are discoverable in ediscovery without a hold, and without a retention policy. This legal hold doc  doesnt have a link to https://learn.microsoft.com/microsoft-365/compliance/retention-policies-teams which make it difficult to find this piece of info. I suggest a small note: " A chat message can be surfaced in ediscovery for only 1-7 days if there is no legal hold or no retention policy. For more information see https://learn.microsoft.com/microsoft-365/compliance/retention-policies-teams"

**Comment by dariomws** [comment]
Hi @Teamsgineer, thank you for your feedback.

"Learn about retention for Microsoft Teams" and a few more article links are listed at the bottom in the "Recommended content" section.

**Comment by scanum** [comment]
Hi @Teamsgineer hope all is well. does this answer your question? Thanks.

**Comment by Teamsgineer** [comment]
confirmed . thank you!
