### ISSUE TITLE
Page does not have information I need

### ISSUE THREAD

**Issue by ne0rrmatrix** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9298]
I was directed by help page to this page for information regarding switching from domain account and personal account sign in on teams. This page appears to be just an ad with how to subscribe and why? I would like it when I get a redirect for information that the result be useful and not an ad. I am not running a business. If teams is not longer meant for personal accounts that is fine. Just say so! I upgraded the version I had on my pc and it would not log in without a domain suddenly? I had one account that was personal and it had a domain I could sign in separately with. It was the same login. I found no way to log in as personal anymore! This is so confusing :(
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9cf9c6a-ae69-3bf6-9123-0d5b24c63c8c
* Version Independent ID: 3becb7ac-cddf-01f8-cf48-114b4771dc3f
* Content: [Manage the free version of Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-freemium?source=recommendations)
* Content Source: [Teams/manage-freemium.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-freemium.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by ne0rrmatrix** [comment]
Sorry. Please close ticket. I was referring to consumer account being unable to use teams. The solution I found was to wipe and reinstall windows 10. I have abandoned windows 11 because of long standing issues with hardware, and software incompatibility and system instability. Feels like Windows ME all over again.

I have tried upgrading and using windows 11 about 5 or 6 times over the last year and I have found with my hardware config and software use that I can't use it effectively. Things like teams not working at all with my consume account. Works find for work. 
No tenant issue at all. It was a consumer issue. I imagine this is the wrong forum for that sort of issue. I switch back and forth from dev account for work, personal dev account, personal account with no work or dev, etc. A few different accounts.

Switching back to windows 10 solved all of my issues. Will try upgrading again in a few monts.
