### ISSUE TITLE
Availability 

### ISSUE THREAD

**Issue by ckrafcky** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#93]
It's now April (Q2). When will this be available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9f904e5-d015-70b0-b809-9b0b62931ab5
* Version Independent ID: aa59fcc6-0a6d-c82f-6b5e-ffb85e08ea8a
* Content: [Manage Teams during the transition to the new Microsoft Teams and Skype for Business Admin Center](https://docs.microsoft.com/en-us/microsoftteams/manage-teams-skypeforbusiness-admin-center)
* Content Source: [Teams/manage-teams-skypeforbusiness-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-teams-skypeforbusiness-admin-center.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by LolaJacobsen** [comment]
Thanks for your question. I'm checking with the product group on the current progress of the new Microsoft Teams & Skype for Business Admin Center. I'll report back here.

**Comment by LolaJacobsen** [comment]
@ckrafcky Here's the summary answer:
Starting today, we're gradually migrating settings to the Microsoft Teams & Skype for Business Admin Center from both the current Skype for Business Admin Center and the Microsoft Teams settings in the Office 365 Admin center.

The new admin center will be rolled out in stages over the next coming weeks. Once the new admin center is available for you, you’ll see a notification in the Teams settings section in the Office 365 Admin Center that will redirect you to the new Microsoft Teams & Skype for Business Admin Center.

Check out our blog post where we announced the new admin center: https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/Announcing-the-new-Microsoft-Teams-amp-Skype-for-Business-Admin/ba-p/179534
