### ISSUE TITLE
El T-Bot es más eficiente en otro idiomas

### ISSUE THREAD

**Issue by Variedz97** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#930]
Es muy buena la actualización, pero afecta negativamente a los usuarios de otros países, en el lenguaje mio el T-Bot se comunica en español y las herramientas mostradas como Who, solo estan en ingles. Agradezco que sea más visible el T-Bot al menos en la versión de mi idioma, gracias.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 654bcf50-9c84-7509-ade7-af3300760fe2
* Version Independent ID: d9fc09ab-86f3-079d-fc25-6931eb5407a9
* Content: [Get help in Microsoft Teams](https://docs.microsoft.com/es-es/MicrosoftTeams/get-help-in-microsoft-teams)
* Content Source: [Teams/get-help-in-microsoft-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-help-in-microsoft-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@Variedz97 Thank you for this feedback

We appricate that you like the T-Bot in diffrent languges. We hope that you continue to enjoy it.
