### ISSUE TITLE
What is the limit for # of moderators?

### ISSUE THREAD

**Issue by davidjfriedman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9300]
If possible, could we please document the max amount of moderators?  For example, how many moderators can be added to a Teams Channel?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097ecd40-1157-98ae-f438-96f9208afc03
* Version Independent ID: ea36ff93-46dc-920d-8d52-9b3b81420958
* Content: [Set up and manage channel moderation - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-channel-moderation-in-teams)
* Content Source: [Teams/manage-channel-moderation-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-channel-moderation-in-teams.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Closing this issue as it is a duplicate
