### ISSUE TITLE
Correct Language issues

### ISSUE THREAD

**Issue by prkosh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9308]
[Enter feedback here]
I see Language errors in this page - please fix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f07d46fc-fafd-b775-be7c-667d1e090565
* Version Independent ID: f07d46fc-fafd-b775-be7c-667d1e090565
* Content: [User requests for admins to allow apps - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/user-requests-approve-apps)
* Content Source: [Teams/user-requests-approve-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/user-requests-approve-apps.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by TinaMcN** [comment]
@prkosh can you please let us know which language version the errors are in?  The link goes to the English article.
@scanum fyi, I have moved to a new project.  Can you please assign this and future localization issues to @martio instead, thanks!

**Comment by prkosh** [comment]
English language

The team has fixed the issues and the new pr went live yesterday

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by martio** [comment]
> [TinaMcN](/TinaMcN)

@TinaMcN This is probably a bad idea... :smirk:

**Comment by martio** [comment]
> @prkosh can you please let us know which language version the errors are in? The link goes to the English article. @scanum fyi, I have moved to a new project. Can you please assign this and future localization issues to @martio instead, thanks!

@TinaMcN This is probably a bad idea... 😏

**Comment by TinaMcN** [comment]
@martio sorry, I meant to say to assign the localization issues to @MartinOersted instead of you :-)  FYI @scanum

**Comment by ashishguptaiitb** [comment]
The issues were fixed in English. The original comment did not refer to any localized content but EN article. 
Let's close this issue. CC  @scanum and @TinaMcN
