### ISSUE TITLE
Possibility to extract Updates data to excel?

### ISSUE THREAD

**Issue by kurtvanbalen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9310]
Is there any way possible to extract the data which is filled in by the users towards excel? 

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c19d4972-fa39-2908-c33c-f7e1a84d06c5
* Version Independent ID: c19d4972-fa39-2908-c33c-f7e1a84d06c5
* Content: [Manage the Updates app for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-updates-app)
* Content Source: [Teams/manage-updates-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-updates-app.md)
* Service: **msteams**
* GitHub Login: @daisyfell
* Microsoft Alias: **daisyfeller**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
