### ISSUE TITLE
GCCH Operator Connect

### ISSUE THREAD

**Issue by J227668** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9314]
Is Operator Connect available to GCCH customers? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30fbee95-7a4d-7e50-efb2-52726553229c
* Version Independent ID: 60136744-9919-50a1-c371-d3e467700922
* Content: [Plan for Operator Connect - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/operator-connect-plan)
* Content Source: [Teams/operator-connect-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/operator-connect-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by J227668** [comment]
@scanum  I did confirm that operator connect is NOT available in GCCH. That should be called out in this document.
