### ISSUE TITLE
Tag this as MTR-W

### ISSUE THREAD

**Issue by cypheredout** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9315]
[Enter feedback here]
Just curious if this should be tagged for MTR-W's specifically.  Had a customer looking for when we started supporting GCCH on A and all they found was this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1365f9b8-001c-daa7-592e-d88b9bb3a10e
* Version Independent ID: ffba1b4d-1f19-4dac-0b55-053d98fe26b7
* Content: [Release notes for Microsoft Teams Rooms (Windows) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/rooms-release-note)
* Content Source: [Teams/rooms/rooms-release-note.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-release-note.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by cypheredout** [comment]
I missed that this was closed.  Can we get the first sentence changed from this:
This article discusses cumulative improvements in Microsoft Teams Rooms.
To this: 
This article discusses cumulative improvements in Microsoft Teams Rooms on Windows.

This makes is clearer for the distinction that this is Windows MTR's not Android.

Also I am not a customer. :) 
![image](https://user-images.githubusercontent.com/40000123/196804443-b6cf2ae5-763a-4d78-95f7-2008e7f417a4.png)
