### ISSUE TITLE
can we  deploy the recorder in cx physical machine or VM ?

### ISSUE THREAD

**Issue by tommyoo2** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9316]
I just find the description below in this doc that we can only support deploy the recorder in azure vm, is it necessary to deploy the bot in azure? If yes, could you please provide the explanations why it is a compulsory?
===========
- **_specific requirements that are fundamental for compliance recording scenario are:
- 
- Recorder bot must be deployed in Azure
- 
- Recorder bot must run on a Windows VM in Azure_**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 896e3ed7-aaf5-ad40-9a5f-1374d85c3e82
* Version Independent ID: 253d2a6b-9225-723a-cbc1-c296c3cfd36c
* Content: [Introduction to Teams Policy-based Recording for Calling & Meetings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-recording-policy)
* Content Source: [Teams/teams-recording-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-recording-policy.md)
* Service: **msteams**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by connordoner** [comment]
Did you ever get an answer to this, @tommyoo2? Apologies to reopen the ticket but I have little interest in fighting an uphill battle with support just to end up with no answer either way.
