### ISSUE TITLE
Reset pin via USP does not send email, needs to be called out

### ISSUE THREAD

**Issue by bbhargavi2020** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9318]
When you reset the audio conferencing PIN via USP page,it does not send email to the user. Needs to be called out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401f39f3-f614-6d63-adbd-1ed78ed804f0
* Version Independent ID: 26b45c86-8f6f-8704-d95a-f8c341e569ad
* Content: [Reset the Audio Conferencing PIN in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/reset-the-audio-conferencing-pin-in-teams)
* Content Source: [Teams/reset-the-audio-conferencing-pin-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/reset-the-audio-conferencing-pin-in-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Thanks for your feedback!
