### ISSUE TITLE
Wrong URL

### ISSUE THREAD

**Issue by tiagoroxo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9320]
The URL to download the POWERBI reports, is poiting to an old zip file.
The right and updated URL should be: https://www.microsoft.com/download/details.aspx?id=102291
This is what is mentioned here: https://docs.microsoft.com/en-us/microsoftteams/cqd-power-bi-query-templates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 718b597f-258b-3d61-17b8-1d41c8436d07
* Version Independent ID: 78f3333e-36cd-384a-8b5b-29bae7e1ed88
* Content: [Data and reports in Call Quality Dashboard (CQD) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cqd-data-and-reports)
* Content Source: [Teams/CQD-data-and-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-data-and-reports.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by lindspea** [comment]
@tiagoroxo thank you for reaching out and helping to improve Microsoft Docs. Just for clarity are you referring to the reports link that must be corrected or the templates link? If you could let me know under which section the correction is needed, I can look into it further. Thanks again.

**Comment by tiagoroxo** [comment]
Hello

So, the text says the following:
" Use direct queries to view your CQD data in Power BI using customizable
Power BI templates
<https://learn.microsoft.com/en-us/microsoftteams/cqd-power-bi-query-templates>
. Download Power BI query templates for CQD
<https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/downloads/CQD-Power-BI-query-templates.zip?raw=true>
."
If you check the URL:  Download Power BI query templates for CQD
<https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/downloads/CQD-Power-BI-query-templates.zip?raw=true>
. - it's not the same as shared in the following page customizable Power BI
templates
<https://learn.microsoft.com/en-us/microsoftteams/cqd-power-bi-query-templates>
-
in this last page the download button point to this different one -
https://www.microsoft.com/download/details.aspx?id=102291 - and this is the
one that should be used in both docs in my opinion as it contains the new
PBI templates: https://www.microsoft.com/download/details.aspx?id=102291

I hope this helps. Let me know if you have any questions.

thanks

Tiago Rôxo,



Lindsay ***@***.***> escreveu no dia quarta, 21/09/2022 à(s)
09:56:
