### ISSUE TITLE
Support for Audio Conferencing with dialout to US/CAN

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9321]
Hi!

Is the on-net conferencing supported with the new SKU for 0$ - AC with dialout to US/CAN (https://www.microsoft.com/en-us/microsoft-teams/audio-conferencing - Microsoft Teams Audio Conferencing with dial-out to USA/CAN)? 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d4b1670-ab39-621e-025e-17d7d747cc09
* Version Independent ID: dcdd8284-ad29-4e46-4731-63fbbce08fb0
* Content: [On-network Conferencing for Audio Conferencing - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/audio-conferencing-on-network)
* Content Source: [Teams/audio-conferencing-on-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-on-network.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by dariomws** [comment]
Hi @Larryngolog,

Thank you for your feedback. I understand that you got the information in the following issue:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8705
