### ISSUE TITLE
NO Create Teams button!!

### ISSUE THREAD

**Issue by fredphoesh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9322]
There is no button on the left side to create a team, so this software has me stumped at step #1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c9902e8-a0b7-b6af-4656-2024849a5e8b
* Version Independent ID: 85beb9a7-2682-b52e-210b-20e598e3dab3
* Content: [Create your first teams and channels - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/get-started-with-teams-create-your-first-teams-and-channels)
* Content Source: [Teams/get-started-with-teams-create-your-first-teams-and-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-started-with-teams-create-your-first-teams-and-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by fredphoesh** [comment]
The issue is, apparently, that Teams is dumbed down if you have the basic Office 365, and you have to have a more expensive version before you can actually use teams by creating a team yourself... this is hidden in both the info Microsoft use to sell you their versions, they list Teams as one of the software you can use, but it is not. This is dishonest and deceptive. There should be an asterisk next to Teams to explain it can only be used if someone else creates the Team!!
