### ISSUE TITLE
can't invite users from German tenant to US teams

### ISSUE THREAD

**Issue by supportguy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9323]
Hello:

Is there some kind of country restrictions with Shared channels? I have a shared channel that when I invite users from a German tenant I get the error "**you can't share this channel with people from this org**"

B2B settings are configure as follows in  both tenants

inbound access setting
- B2B collaboration: Allow Access | All users and groups | All Applications
- B2B direct: Allow Access | All users and groups | All Applications
- Trust Settings: Trust MFA

Outbound access setting
- B2B collaboration: Allow Access | All users and groups | All Applications
- B2B direct: Allow Access | All users and groups | All Applications

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
