### ISSUE TITLE
Clarify Permissions

### ISSUE THREAD

**Issue by BohrenAn** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9325]
Hi All,

Can you please clarify the needed Permissions.
Any Application Permissions needed or just add the App to the "Teams Administrator" Role?

Regards
Andres

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32304edf-550b-72a3-57df-6dcc29dba56d
* Version Independent ID: 32304edf-550b-72a3-57df-6dcc29dba56d
* Content: [Application-based authentication in Teams PowerShell Module - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-application-authentication)
* Content Source: [Teams/teams-powershell-application-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-application-authentication.md)
* Service: **msteams**
* GitHub Login: @pbafna03
* Microsoft Alias: **pbafna**

**Comment by pbafna03** [comment]
Hi @BohrenAn, 

Details on the same are added in the doc now - [link](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-application-authentication#:~:text=Assign%20API%20permissions,ReadWrite.All.).

**Comment by BohrenAn** [comment]
Perfect. Thank you very much!

Von: Prashant Bafna ***@***.***>
Gesendet: Friday, September 16, 2022 8:16 PM
An: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Bohren, Andres ***@***.***>; Mention ***@***.***>
Betreff: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Clarify Permissions (Issue #9325)


Hi @BohrenAn<https://che01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBohrenAn&data=05%7C01%7Ca.bohren%40icewolf.ch%7C8ba46dc877b24a6d299c08da980f864c%7C46bbad8429f04e038d34f6841a5071ad%7C0%7C0%7C637989489687717539%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=x2rl0qRw08GRoc1%2BlrIJWXuNUqMXYm4eBLuMvBUGsg0%3D&reserved=0>,

Details on the same are added in the doc now - link<https://che01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoftteams%2Fteams-powershell-application-authentication%23%3A~%3Atext%3DAssign%2520API%2520permissions%2CReadWrite.All.&data=05%7C01%7Ca.bohren%40icewolf.ch%7C8ba46dc877b24a6d299c08da980f864c%7C46bbad8429f04e038d34f6841a5071ad%7C0%7C0%7C637989489687872697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1I%2BVo6FcZO%2FxxpDhCxwMdT7Bjl44AerdguhfcuBYBU4%3D&reserved=0>.

-
