### ISSUE TITLE
Please clarify if there is a cost to this feature with an example.

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9328]
Hi, Could you please clarify if there is a cost to using this feature. i.e. could a hostile caller could call unassigned numbers and drain a Microsoft customer's Communications credits by repeatedly calling unassigned numbers if they have been set to re-route via CsTeamsUnassignedNumberTreatment to say the main auto-attendant?

Many thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed4beab-bb0d-fba4-814e-147d22fd97e5
* Version Independent ID: 8ed4beab-bb0d-fba4-814e-147d22fd97e5
* Content: [Routing calls to unassigned numbers - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/routing-calls-to-unassigned-numbers?source=docs)
* Content Source: [Teams/routing-calls-to-unassigned-numbers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/routing-calls-to-unassigned-numbers.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @SvenBell how are you?

Do you mean to expand/clarify these requirements?

> To route calls to unassigned Microsoft Calling Plan subscriber numbers, your tenant needs to have available [Communications Credits](https://learn.microsoft.com/en-us/microsoftteams/what-are-communications-credits).

> To route calls to unassigned Microsoft Calling Plan service numbers, your tenant needs to have at least one Microsoft Teams Phone Resource Account license.

Thanks

**Comment by get-itips** [comment]
Hello @SvenBell 
I could get this information 

_If you setup unassigned number routing for a CP subscriber number and a call is coming into the number and is being routed per the treatment, we will charge communications credits in the tenant the per-minute dial-in to toll rate from when the call is accepted._

**Comment by SvenBell** [comment]
Thanks for clarifying, much appreciated

**Comment by SvenBell** [comment]
It would also be good to clarify that the expected behaviour & cost applies to unassigned Call Plan numbers whether number provider if Microsoft (or Telstra) call plan, Direct route or Operator connect, and, no matter what location/country unassigned number is located.
