### ISSUE TITLE
Documentation is not clear regarding "Allow interaction with custom apps" org-wide setting

### ISSUE THREAD

**Issue by orandev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9329]
Hello,
"Allow interaction with custom apps" description in the Teams admin center and in the docs.microsoft.com page is not clear, based on what we saw by testing the 2 values for this setting (or we do not have the same definition of "Custom App").
Our use case was to forbid users from chatting with externals bots by deeplink (bot apps not uploaded to our tenant by a Teams admin, i.e. this feature: https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/debug/locally-with-an-ide#talk-to-your-bot-directly-by-id ; deeplink is like "https://teams.microsoft.com/l/chat/0/0?users=28:< GUID >"), but to allow them to use apps uploaded by a Teams admin in the "Manage apps" page of the Teams admin center (upload of a zip file).
And this can be done only by setting "Allow interaction with custom apps" to "Off", which is counter-intuitive and does not correspond to what is in the documentation, according to me.

You say:
"The Allow interaction with custom apps org-wide custom app setting on the Manage apps page applies to everyone in your organization and governs whether they can upload or interact with custom apps. This setting acts as a master on/off switch for the user and team custom app policy settings. It's intended to serve as a master on/off switch during security events."
I think you should say:
"The Allow interaction with custom apps org-wide custom app setting on the Manage apps page applies to everyone in your organization and governs whether they can upload or interact with custom apps (it does not govern interaction with custom apps uploaded by a Teams Service Admin or a Global admin). This setting acts as a master on/off switch for the user and team custom app policy settings. It's intended to serve as a master on/off switch during security events."

You say:
"Interaction with all custom apps is blocked for your organization"
I think you should say:
"Interaction with all custom apps is blocked for your organization. Interaction with custom apps uploaded by a Teams Service Admin or a Global admin is still allowed, if the custom app has the 'Allowed' status."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d51bb7b1-801e-6801-dcaf-afa3e38e6941
* Version Independent ID: d8e726a1-cbf2-53c7-da4d-cc155b48612b
* Content: [Manage custom app policies and settings - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-custom-app-policies-and-settings#org-wide-custom-app-setting)
* Content Source: [Teams/teams-custom-app-policies-and-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-custom-app-policies-and-settings.md)
* Service: **msteams**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by dariomws** [comment]
Hi @orandev, thank you for your feedback.

I think it's currently there:
"Interaction with all custom apps is blocked for your organization. **Custom apps can't be uploaded by anyone except a Teams Service Admin or a Global admin**."

**Comment by orandev** [comment]
Hello @dariomws 
It's not the same thing. There is "Interaction" on one side and "Upload" on the other side.
It says "Interaction is blocked for everyone" and "Custom apps can be uploaded by a Teams admin". For me, the second part does not imply that "interaction is allowed for custom apps uploaded by admins".

**Comment by dariomws** [comment]
Hi @orandev,

Why will an admin upload the app if users cannot interact with it? :)

Anyway, please check the update I have proposed 33 minutes ago.

**Comment by orandev** [comment]
In your PR, I would say "If this setting is set to Off, only a Teams Service Admin or a Global admin can upload custom apps and users will be able to interact with them." instead of "Only a Teams Service Admin or a Global admin can upload custom apps and users will be able to interact with them.".
