### ISSUE TITLE
Clarity on console licensing for Basic license

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9330]
Please provide clarity regarding the license requirement for console on MTRoA. In article it states:
"A Teams Rooms Basic license can be used to license a single certified Teams Rooms device in a room. If you want to log into more than one device in a room using the same resource account (**for example, a Teams Rooms console**, a Surface Hub, and a Teams panel), **you need to use a Teams Rooms Pro license.**"

As far as I to use a console for controling MTRoA you can usie a basic license for both signing in to the console and MTRoA.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-licensing)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-licensing.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @Larryngolog, thank you for your feedback.

The paragraph was updated a few days ago to provide clarity. Please check.

**Comment by scanum** [comment]
@Larryngolog Hope all is well. Does this answer your question? Thanks!

**Comment by Larryngolog** [comment]
Yes, thank you!

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
