### ISSUE TITLE
[Admin center] Unable to view Manage Apps on teams admin center as Teams Administrator

### ISSUE THREAD

**Issue by raguravindran** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9331]
Unable to view "Manage apps" option from [Teams Admin Center](https://admin.teams.microsoft.com)
See screenshot for more information

<img width="1445" alt="Screenshot 2022-09-19 at 11 53 13 PM" src="https://user-images.githubusercontent.com/36010645/191088371-58fb8b74-5d85-4149-a6c9-f52a695a4880.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbcabee-fa96-2878-e983-3c966f84ee15
* Version Independent ID: 02fa4fd8-77e0-5cb2-a4af-576cbb68322f
* Content: [Manage your apps in the Microsoft Teams admin center - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-apps)
* Content Source: [Teams/manage-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-apps.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by ashishguptaiitb** [comment]
I don't see Manage app page in the left sidebar @raguravindran . I'd suggest talking with Microsoft support to resolve this. Could be permissions or license issues? 
https://learn.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
