### ISSUE TITLE
No Android Information on Microsoft Teams Rooms maintenance and operations

### ISSUE THREAD

**Issue by yuki-iwagishi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9336]
[No Android Information on Microsoft Teams Rooms maintenance and operations]
All information written in this page is based on Microsoft Teams Rooms on Windows.
Better to add "Windows" on the title. Such as Microsoft Teams Rooms on Windows maintenance and operations
In other words, we cannot find Microsoft Teams Rooms on Android maintenance and operations including how to upgrade software. Please create or add pages of Microsoft Teams Rooms on Android side.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd52fe62-457b-c9e1-ad13-a9b1f24c9c38
* Version Independent ID: 6a8c3285-30e1-15a8-6472-f0cfe5b30e20
* Content: [Microsoft Teams Rooms maintenance and operations - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-operations)
* Content Source: [Teams/rooms/rooms-operations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-operations.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @yuki-iwagishi, thank you for bringing this to our attention. We've notified the documentation team of similar requests and will send you feedback as well.

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
