### ISSUE TITLE
Link is not correct in the note

### ISSUE THREAD

**Issue by mrik23** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#934]
The note on rates is redirecting to https://products.office.com/en-us/microsoft-teams/voice-calling which doesn't not offer the dial-in rates for pay-per-minute Audio Conferencing. The correct link is https://products.office.com/en-us/microsoft-teams/online-meeting-solutions#Rates which gives the option for pay-per-minute plan.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fac515b-9c6b-c70c-330e-53557dc23fd2
* Version Independent ID: d515841e-f412-286d-1a97-30507bb50040
* Content: [Audio Conferencing pay-per-minute](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-pay-per-minute)
* Content Source: [Teams/audio-conferencing-pay-per-minute.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-pay-per-minute.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@mrik23 Thank you for this feedback

I will get this link issue over to the Teams/Skype for Business team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by mrik23** [comment]
@AndreaBarr can close this, they merged my pull request.
