### ISSUE TITLE
Rooms up to 5 people in size in Deploy Microsoft Teams Rooms on Android

### ISSUE THREAD

**Issue by yuki-iwagishi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9340]
These recoomendation are old information when MTRoA was called "Collaboration Bar".
Recently, MTRoA certified devices are up to 16 people(Large). And most of operations don't require Touch Screen.

https://learn.microsoft.com/en-us/microsoftteams/devices/collab-bar-deploy
-Rooms up to 5 people in size
-Touch-enabled displays

https://learn.microsoft.com/en-us/microsoftteams/rooms/teams-devices-feature-comparison#feature-comparison-between-windows-and-android

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df34eea9-3e9e-acbf-3dde-ecf8e66956d1
* Version Independent ID: bab87875-e7a1-f109-f9cb-4dbe940908f3
* Content: [Deploy Microsoft Teams Rooms on Android - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/devices/collab-bar-deploy)
* Content Source: [Teams/devices/collab-bar-deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/collab-bar-deploy.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @yuki-iwagishi 
I am looking into this.

**Comment by dstrome** [comment]
Removed "up to 5" reference. Touch screens aren't a requirement but are a recommendation.
