### ISSUE TITLE
AzureAD and MSOL Powershell modules are retired

### ISSUE THREAD

**Issue by HSteindl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9341]
Since both AzureAD and MSOL powershell modules are going end-of-life rather soon, this page needs to be updated.
thanks for your consideration.
Best Regards
HST

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Create resource accounts for rooms and shared Teams devices - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/with-office-365?tabs=m365-admin-center%2Cazure-active-directory2-password%2Cactive-directory2-license)
* Content Source: [Teams/rooms/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-office-365.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
