### ISSUE TITLE
Group Assignment of Policy Not Available - Documentation needs to be updated

### ISSUE THREAD

**Issue by 3017mark** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9342]
The ability for a customer to assign voicemail policies via groups is not available and documentation is vague and unclear with regards to this ability.  Please update accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85634d87-7729-6449-9663-556097e75504
* Version Independent ID: b75446bd-07af-a7f2-d346-fe7634634548
* Content: [Manage Voicemail Policies - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-voicemail-policies?source=recommendations)
* Content Source: [Teams/manage-voicemail-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-voicemail-policies.md)
* Service: **msteams**
* GitHub Login: @crowe
* Microsoft Alias: **crowe**

**Comment by JensTrier** [comment]
Which policies that are available for group policy assignment are tracked via this page https://learn.microsoft.com/en-us/powershell/module/teams/new-csgrouppolicyassignment?view=teams-ps.

I don't think individual policy pages should go into this level of details.

**Comment by 3017mark** [comment]
Less concerned with the referenced page below but more so how some pages are not clear on the use of groups to assign policies via group policy assignment when in fact it is not available.  This has caused confusion with a few customers recently.

***@***.***

Manage Voicemail Policies - Microsoft Teams | Microsoft Learn<https://learn.microsoft.com/en-us/microsoftteams/manage-voicemail-policies>

Mark Brownell
Senior Teams Technical Specialist
U.S. State & Local Government
Office: +14255382012
Mobile: +17742809182
***@***.******@***.***>
