### ISSUE TITLE
Teams app version

### ISSUE THREAD

**Issue by lberlau** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9343]
Hi, 

It would be nice if this site could be updated with the latest Teams app version 

Thanks
Lars Berlau

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7ecd6ee6-8850-f346-5684-9c5d2444789f
* Version Independent ID: a55a7a01-211d-147a-5332-b68e1051a2a1
* Content: [Microsoft Teams Rooms app version support - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-lifecycle-support)
* Content Source: [Teams/rooms/rooms-lifecycle-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-lifecycle-support.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @lberlau 
I am not sure I understand sorry, can you please detail what you see is missing from the article you opened the issue for?
Is this instead what you are looking for? https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-release-note

**Comment by get-itips** [comment]
@lberlau  Could you see my comment here? thanks

**Comment by lberlau** [comment]
Sorry for the late response. 
The Teams app is now on 4.14, which is not in the documentation. 
But I now see that it says: **Minimum** application version

**Comment by get-itips** [comment]
Exactly, minimum version.
Thanks
