### ISSUE TITLE
Recordings and full storage quota.

### ISSUE THREAD

**Issue by jeff-bb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9346]
From the FAQ -- 
"Where does the recording go if the user doesn't have OneDrive for Business or SharePoint, or the storage quota is full?

The recording will land in our temporary storage location where it will be held for 21 days. During that time, the organizer must download the recording. If not downloaded within 21 days, the recording is deleted."

Where is this temporary storage location? How does the organizer access it? Is the method of access limited to the organizer, or the user who pressed record (if they are different)?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8935e913-806f-a92c-d09e-e67df4ffd1b4
* Version Independent ID: c7a41cde-66dd-d7cd-1316-42d20ed4841a
* Content: [Use OneDrive for Business and SharePoint for meeting recordings - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/tmr-meeting-recording-change)
* Content Source: [Teams/tmr-meeting-recording-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tmr-meeting-recording-change.md)
* Service: **msteams**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jeff-bb** [comment]
Opening a support ticket to update documentation? I was just hoping for a "The impacted user will receive a message in the chat of the meeting, with a link to download the file" type blurb. I assumed that "feedback for documentation" would be handled by a group that was capable of updating documentation, and would not require a support incident.
