### ISSUE TITLE
affect

### ISSUE THREAD

**Issue by nahloe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9347]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf54bf5d-1748-46bf-a503-5e978f56126c
* Version Independent ID: 5976a1df-52e9-eb19-fd41-c7b04fce74f8
* Content: [How different technologies effect Microsoft Teams sign-on, including restricting sign-on, and sign-in behaviours. - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/sign-in-teams)
* Content Source: [Teams/sign-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sign-in-teams.md)
* Service: **msteams**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by baf** [comment]
@scanum Why was this closed? I believe @nahloe was calling attention to the fact that this page’s title incorrectly uses “effect” instead of “affect.” That should be corrected.
