### ISSUE TITLE
Links for "what's available in the Teams public preview" show info about general release, not Public Preview

### ISSUE THREAD

**Issue by ryanhelmer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9351]
_Given past experiences: This is strictly a documentation issue/question, so please don't auto-reply to this post saying "I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP"._

"For a list of what's available in the Teams public preview, visit [Microsoft Teams Public Preview tech notes](https://techcommunity.microsoft.com/t5/microsoft-teams-public-preview/bd-p/MicrosoftTeamsPublicPreview), [Release Notes for Teams Admin Features](https://learn.microsoft.com/en-us/OfficeUpdates/teams-admin), and [What's new in Teams](https://support.microsoft.com/office/what-s-new-in-microsoft-teams-d7092a6d-c896-424c-b362-a472d5f105de)."

Unless I'm missing something, none of those links contain a list of what is in the _Public Preview_. Two of the links only show information about the current release, and the techcommunity.microsoft.com link is a forum that also doesn't appear to have a list, and it includes no information about the recently-released fix for the issue described here: https://answers.microsoft.com/en-us/msteams/forum/all/teams-yealink-mp50-unable-to-start-answer-or-end/bfba54b2-fd71-40ff-9c4e-f6d111e3f0b1?page=6

If I'm missing the info about the list of what's in Public Preview, could you point me to it, or otherwise clarify? Thank you for your assistance.

**Comment by dariomws** [comment]
Hi @ryanhelmer, thank you for your feedback.

Can you please tell us to which article(s) your question applies?

**Comment by ryanhelmer** [comment]
Thank you, @dariomws. My apologies not to include the link, I had thought I was offering feedback to that page. This is the article I had in mind: https://learn.microsoft.com/en-us/microsoftteams/public-preview-doc-updates.

**Comment by dariomws** [comment]
@ryanhelmer, thank you for your comment.

All public preview features are announced at [Microsoft Teams Public Preview - Microsoft Tech Community](https://techcommunity.microsoft.com/t5/microsoft-teams-public-preview/bd-p/MicrosoftTeamsPublicPreview). I understand there is no better place to search for public preview features.

**Comment by ryanhelmer** [comment]
Thank you, @dariomws. The page says "_For a list_ of what's available in the Teams public preview...." Is there a place that has such a list? I haven't found such a list on that Tech Community page. Even if you search that site, it also doesn't include the recently-released fix I had mentioned.
