### ISSUE TITLE
The content in "Configure mailbox properties" section is a duplicate of section "Turn off password expiration"

### ISSUE THREAD

**Issue by chenguyuan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9353]
The content in "Configure mailbox properties" section is a duplicate of section "Turn off password expiration"
(https://learn.microsoft.com/en-us/microsoftteams/rooms/with-office-365?tabs=m365-admin-center%2Cazure-active-directory2-password#configure-mailbox-properties)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 05282aa8-ae14-117b-5885-7d851ee66b89
* Version Independent ID: 85abe13c-d34c-f42c-e273-a69be8cd991e
* Content: [Create resource accounts for rooms and shared Teams devices - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/with-office-365?tabs=m365-admin-center%2Cazure-active-directory2-password)
* Content Source: [Teams/rooms/with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/with-office-365.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by lindspea** [comment]
@chenguyuan thank you for pointing this out and helping to improve Microsoft Docs. @tiburd please can you contact the author for the correct instructions under the "configure mailbox properties" section of the article.

**Comment by tiburd** [comment]
@dstrome 
I sent you email about this - thanks for fixing!

**Comment by dstrome** [comment]
Thanks all. I've fixed this and the article should be updated in the next few minutes.
