### ISSUE TITLE
Configuring call queues without Teams Administrator role

### ISSUE THREAD

**Issue by andreprakash** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9354]
We would like to delegate the setup of call queues to our telephony department and assigned them the role "Teams communications administrator" and "global reader" (which does not work within teams). 
This works fine expect they are unable to assign a team and channel to the call queue. The option is greyed out and an error message appears: "the user doesn't have permission to view the channel, users or groups. Conact your Global Administrator to assign permissions and try again" 

Is there a way to assign them the required permission without giving them the teams administrator role?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
