### ISSUE TITLE
Microsoft 365 Ports and URLs doc inaccurate for GCC Customers

### ISSUE THREAD

**Issue by brent-smith-msft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9358]
The Product Group made the decision to send all GCC customers' connections for Office Online Services to the GCC High cloud servers. As a result, the current documentation is incomplete/inaccurate for all GCC customers.

We need the public documentation at https://learn.microsoft.com/en-us/microsoftteams/office-365-urls-ip-address-ranges to be updated to reflect that, for GCC customers, they need to allow *.osi.office365.us traffic, as seen in ID 17 on the GCC High document at https://learn.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-u-s-government-gcc-high-endpoints?view=o365-worldwide

Without that in place, at least one GCC customer is not willing to allow that traffic through since our documentation is not specifically saying that it is needed.

Thanks for any help that can be given with this!

**Comment by brent-smith-msft** [comment]
Any update here? The doc that needs the update is actually here, now: https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide

**Comment by dariomws** [comment]
Hi @brent-smith-msft, thank you for your feedback.

These articles are updated through an automated process, I cannot manually add this endpoint:

"THIS FILE IS AUTOMATICALLY GENERATED. MANUAL CHANGES WILL BE OVERWRITTEN.
**Please contact the Office 365 Endpoints team with any questions**."

@kelleyvice-msft, maybe you can help.

**Comment by scanum** [comment]
Hi @kelleyvice-msft Hope all is well. Could you please help with this issue? thanks.

**Comment by kelleyvice-msft** [comment]
Closing this issue as the OP is contacting the engineering team for resolution.
