### ISSUE TITLE
Update -- Supported devices

### ISSUE THREAD

**Issue by NeeranjanShettar** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9361]
<html>
<body>

***

The below statement is not updated to latest information, it is still showing the surface Hub and MTR Android support coming in the second half of 2021, this has to be reviewed and update it accordingly. 

***

Supported devices | Certified Microsoft Teams Rooms systems and their peripherals.
**Surface Hub and MTR Android support coming in the second half of 2021**
-- | --

</body>
</html>
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8f76bc0c-a899-b572-588a-b86acae1b740
* Version Independent ID: 3c5b6414-c796-7e50-9e03-b578c7995071
* Content: [Microsoft Teams Rooms Pro management - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/microsoft-teams-rooms-premium?source=docs)
* Content Source: [Teams/rooms/microsoft-teams-rooms-premium.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/microsoft-teams-rooms-premium.md)
* Service: **msteams**
* GitHub Login: @altsou
* Microsoft Alias: **altsou**

**Comment by altsou** [comment]
Thanks for catching this! I've submitted a PR to fix.

**Comment by pl4nty** [comment]
Given we're almost at the end of 2022, is this still accurate? Neither MTRoA or Surface Hubs seem to support Pro Management on the latest updates
