### ISSUE TITLE
Blocked Numbers Not Doing Anything

### ISSUE THREAD

**Issue by bandwiches** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9364]
I receive a call from `(800) 123-4567` every single day, so I decide to block it.
Next day, I receive a call from +1 (800) 123-4567 - I block this number too.
Next day, I receive a call from `(800) 123-4567` - I was AFK, missed it (not sure if it rang)
Five minutes later, I receive a call from `+1 (800) 123-4567` - this came through and rang like normal.

I would love to be able to block these call distribution numbers that are just spamming me every single day.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91c40ca3-c19e-eac3-3adb-815e45ce2388
* Version Independent ID: 1193b36e-8870-aca9-cb9c-59c5fb1f5412
* Content: [Block inbound calls in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/block-inbound-calls)
* Content Source: [Teams/block-inbound-calls.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/block-inbound-calls.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
