### ISSUE TITLE
Teams Room Standard and Premium

### ISSUE THREAD

**Issue by StPhil** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9365]
As customers still own Standard and Premium licenses, we need to still have the features of those licenses available for them to review. This page has removed those details and they do not seem to live anywhere else publicly. Please re-add them or add a section. They do not align 1:1 with Basic or Pro.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-licensing.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dstrome** [comment]
hi @StPhil - We've added the content from the old Standard and Premium licenses article to a new 'legacy licenses' article available here - https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-legacy-licensing. We also added a link to that article in the main licensing article here - https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing#switching-from-teams-rooms-standard-and-teams-rooms-premium.

Thanks very much for your feedback!
