### ISSUE TITLE
Teams Room Standard and Premium licenses

### ISSUE THREAD

**Issue by StPhil** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9366]
The note in this article only mentions that Teams Room Pro licenses are required, but it should work with Teams Room Standard and Premium licenses which customers still own and need to be called out in the documentation.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27c7b5b4-963e-265b-decf-57fe4a614905
* Version Independent ID: 27c7b5b4-963e-265b-decf-57fe4a614905
* Content: [Conditional Access and compliance best practices for Microsoft Teams Rooms - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/conditional-access-and-compliance-for-devices)
* Content Source: [Teams/rooms/conditional-access-and-compliance-for-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/conditional-access-and-compliance-for-devices.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @StPhil 
I am looking into this

**Comment by dstrome** [comment]
hi @StPhil - I'm discussing this with the product group to see what we can do.

**Comment by dstrome** [comment]
Consolidating under #9365
