### ISSUE TITLE
Number of teams a user can be a member of... is it 1K or 7K?

### ISSUE THREAD

**Issue by VelinGeorgiev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9368]
According the [Groups limits table](https://learn.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups?view=o365-worldwide#group-limits), the number of Groups a user can be a member of is 7K. According to this current page the number of Teams a user can be a member of is 1K. Is this accurate? I assume the Microsoft Teams limit is based on the Microsoft 365 Groups limit therefore this document should be updated saying  "Number of Teams a user can be a member of is 7K".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by VelinGeorgiev** [comment]
I can see this marked as doc-bug. Can please someone confirm even in this thread what the actual 'Number of teams a user can be a member of' is? Thanks!

**Comment by dariomws** [comment]
Hi @VelinGeorgiev, thank you for your feedback.

The limit on this article is correct. These limits are not strictly related to the limits of the M365 groups.

**Comment by VelinGeorgiev** [comment]
Thanks, @dariomws!
