### ISSUE TITLE
Differentiate between Teams Usage report and Teams user activity report

### ISSUE THREAD

**Issue by Michael-Dahlke** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9370]
I have a customer who was looking for an explanation for the discrepancy in the numbers reported for the value: Total Meetings Organized (User activity report) and Total Organized Meetings (Usage report). The definitions in the respective docs are extremely similar and don't give context as to why the numbers can be so vastly different. 

User activity report: "Total Meetings organized is the sum of one time scheduled, Recurring, unplanned, and unclassified meetings a user organized during the specified time period."

Usage report: "Total organized meetings is the sum of one time scheduled, recurring, unplanned, and unclassified meetings a user organized during the specified time period."

Recommend adding an explanation to the definition in the User Activity report along the lines of: "Teams User Activity reports shows a list of activities enumerated by the number of users who have performed a specific activity in a specific amount of time." 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2758a3d6-c646-dcb0-2a31-c7b9b84e780b
* Version Independent ID: 8704c9fe-f8b0-82d2-bd83-3fd1a9ad638d
* Content: [Microsoft Teams user activity report - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report#feedback)
* Content Source: [Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @Michael-Dahlke I am looking into this

**Comment by get-itips** [comment]
Hello @Michael-Dahlke an update to the article is coming soon
