### ISSUE TITLE
Suggest to add MTR Windows & MTR Android references throughout https://aka.ms/mtrdocs

### ISSUE THREAD

**Issue by davidjfriedman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9372]
Customers would benefit from more specific guidance around which OS MTR docs apply to throughout the pages at https://aka.ms/mtrdocs.  Topics should be covered for both Windows and Android across all Teams Rooms docs, with labels for OS throughout.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c25c286-2a25-19d1-6847-f2324b3deb73
* Version Independent ID: 0c82ef28-f9c8-1845-c167-ce2756478d9c
* Content: [Plan for Microsoft Teams Rooms - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-plan)
* Content Source: [Teams/rooms/rooms-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-plan.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @davidjfriedman, thank you for bringing this to our attention. We've notified the documentation team of similar requests and will send you feedback as well.
