### ISSUE TITLE
Old Logical Architecture

### ISSUE THREAD

**Issue by AshishOnGit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9373]
The article and associated logical architecture requires an update on Stream , Call recording scenarios.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ad624-9792-91b7-c85f-09b839b1ea44
* Version Independent ID: e8288f91-11bd-599b-8a88-074917b315a4
* Content: [Microsoft Teams IT architecture and voice solutions posters - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-architecture-solutions-posters)
* Content Source: [Teams/teams-architecture-solutions-posters.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-architecture-solutions-posters.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @AshishOnGit, thank you for your feedback.

There is work in progress to update this poster. I have no ETA but it should be updated in a few weeks.

Same as:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9430
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8685
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7808
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7565

**Comment by scanum** [comment]
Hi @AshishOnGit Hope all is well. The documentation has been updated. Please let us know if this answers your request. Thanks.
