### ISSUE TITLE
Ability to add Power BI reports/dashboard to a  Microsoft Teams Shared channel

### ISSUE THREAD

**Issue by anamariaaaac** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9378]
At the moment, this capability is not supported, even though in a normal teams channel this is possible. Also, neither the workaround for this issue, using the website feature where you may add the embedded report link, is not working as expected.

**Comment by scanum** [comment]
@anamariaaaac Could you please add a related article you are referring to? Thanks!

**Comment by anamariaaaac** [comment]
https://learn.microsoft.com/en-us/microsoftteams/shared-channels

**Comment by dariomws** [comment]
@anamariaaaac - thank you for engaging with the community here for the docs.
 
I know the product teams are always looking for user feedback and how to make Microsoft products better. They keep a close tab on user feedback, and it would be awesome if you could add your voice to the Microsoft Feedback Portal: https://feedbackportal.microsoft.com/feedback/.
 
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.
 
Thank you for your contribution to making the docs better! Much appreciated!
