### ISSUE TITLE
Teams MSI - Deployment through Intune - Issue with shortcuts

### ISSUE THREAD

**Issue by berrywaanders** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#938]
Hello,

I've deployed the Teams MSI to my test endpoints through Intune.

The Teams application is installed in the users profile and it auto launches at logon, but all shortcuts are missing. (no desktop shortcut, no start menu shortcut)

Any tips?

**Comment by AndreaBarr** [comment]
@berrywaanders Thank you for this feedback

I am not sure why the shortcuts are missing. I want to get you over to Support so we can dig in and find out what is going on. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
