### ISSUE TITLE
Teams PowerShell command in step 11 is failing: where : The term 'UserValidationErrors' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by torstenegebirk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9380]
[The last Teams PowerShell command under step/section 11 is faling This one is working: Get-CsOnlineUser -Filter {IsSipEnabled -eq $True} | Where {$_.UserValidationErrors -ne $null} | fl SipAddress,InterpretedUserType,OnPremHostingProvider,UserValidationErrors  ]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5566de7d-1d1e-ba92-743b-dc772b49752a
* Version Independent ID: c15342ff-eb3a-5f14-4bba-217c31aa1299
* Content: [Decide how to manage attributes after decommissioning - Skype for Business Hybrid](https://learn.microsoft.com/en-us/skypeforbusiness/hybrid/cloud-consolidation-managing-attributes)
* Content Source: [Skype/SfbHybrid/hybrid/cloud-consolidation-managing-attributes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/cloud-consolidation-managing-attributes.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by JensTrier** [comment]
@torstenegebirk thanks! Will fix it.

**Comment by JensTrier** [comment]
feel free to close this issue
