### ISSUE TITLE
Outdated info: bluy my background *is* available with Teams in browser

### ISSUE THREAD

**Issue by mennomenno** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9382]
"2 Blur my background isn't available when you run Teams in a browser. This feature is only available in the Teams desktop client." - this is no longer true (tested in Chromium on Linux)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c86f401-cff4-93b3-ff69-b9787a87e644
* Version Independent ID: c0808bd3-cf63-0625-4c3c-65469c26fb3e
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/get-clients?tabs=Windows#browser-client)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Thanks for your feedback!
