### ISSUE TITLE
Missing limits for Teams name & description

### ISSUE THREAD

**Issue by a-goo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9383]
Missing character limitations for Teams name & description.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by lindspea** [comment]
@a-goo thank you for reaching out and helping to improve Microsoft Docs. I'll look into this.

**Comment by lindspea** [comment]
@a-goo this has been fixed in another issue and should go live soon.

**Comment by scanum** [comment]
Hi @lindspea hope all is well. Could you please link the other issue? Thanks.

**Comment by lindspea** [comment]
> Hi @lindspea hope all is well. Could you please link the other issue? Thanks.

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/8030

**Comment by scanum** [comment]
Thank you @lindspea!

Closing this issue as a duplicate since it is being handled in another issue. Thanks!
