### ISSUE TITLE
Please rewrite to use the Office 365 Cloud app instead

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9384]
[Enter feedback here]
Please modify, so that the "preferred" Office 365 Cloud app is targeted instead of SharePoint Online

https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-cloud-apps#office-365

The Office 365 suite makes it possible to target these services all at once. We recommend using the new Office 365 suite, instead of targeting individual cloud apps to avoid issues with [service dependencies.

/Kenneth

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2308e7ef-1a9a-0fd1-53c4-7b6e5387978a
* Version Independent ID: 9d9a661f-841c-6b3b-b579-f4e507bcbddd
* Content: [Block access to SharePoint for specific users - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/block-access-sharepoint?source=docs)
* Content Source: [Teams/block-access-sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/block-access-sharepoint.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @kennethvs, thank you for your feedback.

Could you provide more detail? My apologies but I don't understand your feedback.

This article is intended to block access to SharePoint files yet allow their employees to use Teams desktop, mobile, and web clients on unmanaged devices.

**Comment by kennethvs** [comment]
Hi @dariomws,

So in the CA policy you currently target Office 365 SharePoint Online, while MS best practise is to target the "Office 365" cloud application which contains Office 365 SharePoint Online.

Also another point of feedback, having 2 CA policies automatically created, targeting all users and being on by default is not a really good idea. If you want to create them while modifying the Unmanaged devices settings, please ask the users and give them options. (but this feedback is not related to the documentation, but more for the product team.. i know)

**Comment by dariomws** [comment]
But following the steps in this article, if you block Office 365, the user will lose access to the entire service. The purpose here is to block access to SharePoint files while the user still has access to Teams.

**Comment by kennethvs** [comment]
@dariomws. Owh.. then I misinterpreted the scenario. Why in that case not just block access to SharePoint from unmanaged devices in the CA policy, instead of using App Enforced Restrictions with a block on unmanaged as defined globally in the SharePoint Admin Center?

**Comment by dariomws** [comment]
@kennethvs, sorry but I don´t have the answer for the last question. Reading the article, I understand that App Enforced Restrictions automatically create the CA policy. Then you modify it to apply only for a subset of users.

**Comment by scanum** [comment]
Hi @kennethvs does this answer your question? Thanks.

**Comment by kennethvs** [comment]
Hi @scanum , 

So to explain, in the scenario described here, you create a CA policy which uses the "global block" setting of SharePoint Admin Center to block this scenario. Using this setting though, doesn't leave room for using other CA policies also leveraging app enforced restrictions.

If you want to block access to SPO in certain scenario, just build a block CA policy and don't use App Enforced Restrictions, App Enforced Restrictions could leverage the Global SharePoint settings, but also respect manual settings set on a per-SharePoint Site level or leverage Sensitivity Labels for Containers as well. 

By using this proposed CA policy, you pay the penalty of losing any flexibility in your CA setup.

/Kenneth
