### ISSUE TITLE
Needs rewrite - reads like Stream, needs to read like a Teams Live Event

### ISSUE THREAD

**Issue by StainlessSteele** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9385]
This should more read like:
Go to Teams Calendar
Use New Meeting drop down
select Live Event, enter event details and then on the second screen select "Teams Encoder" 
Once the meeting is scheduled use the meeting details when opening the event a producer to get the RTMP URL and Key for use in your encoder. The organizer can use the in-meeting options pane to alter the settings to turn off SSL or regenerate the key as needed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eca17625-0a35-38ae-93f7-23e11c9da382
* Version Independent ID: eca17625-0a35-38ae-93f7-23e11c9da382
* Content: [Creating a stream in Microsoft Teams - Microsoft Teams](https://review.learn.microsoft.com/en-us/MicrosoftTeams/teams-encoder-create-event?branch=heidip-encoder-based-RTMP)
* Content Source: [Teams/teams-encoder-create-event.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-encoder-create-event.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by dariomws** [comment]
Hi @StainlessSteele, thank you for your feedback.

Could you please share the public link to the article? It seems it's not public yet. If I click the link here in GH, it redirects me to https://review.learn.microsoft.com/.

**Comment by StainlessSteele** [comment]
@MicrosoftHeidi  is working on these docs.

**Comment by dariomws** [comment]
Thanks @StainlessSteele, I think it's better if you provide feedback to Heidi either directly or using an internal tool (not sure if there is one).
