### ISSUE TITLE
Not needed

### ISSUE THREAD

**Issue by StainlessSteele** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9386]
This page isn't likely needed as this one exists https://learn.microsoft.com/en-us/MicrosoftTeams/teams-live-events/set-up-for-teams-live-events and we might just want to add encoder settings into it. there aren't admin policy controls for live events RTMP encoder settings specifically. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 026d8745-6920-900d-2bd4-32bf0bbe08ce
* Version Independent ID: 026d8745-6920-900d-2bd4-32bf0bbe08ce
* Content: [Administration options for streaming in Microsoft Teams - Microsoft Teams](https://review.learn.microsoft.com/en-us/MicrosoftTeams/teams-encoder-administration?branch=heidip-encoder-based-RTMP)
* Content Source: [Teams/teams-encoder-administration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-encoder-administration.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by dariomws** [comment]
Hi @StainlessSteele, same issue here. It seems that this article is not public yet.
