### ISSUE TITLE
What does Detailed System and Configuration Information net the admin? 

### ISSUE THREAD

**Issue by SaladGoldRancher** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9387]
I currently don't meet the 25 device threshold to require Pro licensing. I would love it if I had better telemetry for the devices though. 

Please go into detail as far as what the Pro license provides for:

- Detailed system and configuration information
- Peripheral health management
- Remote configuration

This is pretty vital to me in order to justify asking for the budget to increase licensing. Otherwise, it's a black box which won't be very persuasive. 

Thank you, 
SaladGoldRancher

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-licensing.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
