### ISSUE TITLE
Updating an adaptive card from a Teams Bot doesn't reflect in the MS Teams UI, until after leaving the chat and returning to it again

### ISSUE THREAD

**Issue by sjkp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#939]
We have a built a MS team bot that uses the Adaptive card technology, to send approval/reject requests to people. The adaptive card uses the button submit functionality, and once the bot receive the message it updates to the card to prevent the user from submitting again on the same request. 
Unfortunately the MS teams client (windows) doesn't update the card, before the user navigates away from the chat with the bot. Is this intended behavior, or is it a bug that will be resolved, so we can update the adaptive card as a means of notifying the user that the response was handled. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@sjkp Thank you for this feedback

I am not sure if that is a bug or not. I want to get you over to support so we can investigate this potential bug. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
