### ISSUE TITLE
Document refers to a link but no link enabled "

### ISSUE THREAD

**Issue by eomullig** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9390]
[Enter feedback here]
Doc states 
"If you are running AV software on these devices, you should ensure that AV has exclusions in place for Teams and Skype dlls. See here for more details."

Here - no link exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dee798c6-ed17-a5ae-e9d5-0fa0958dfa3f
* Version Independent ID: dee798c6-ed17-a5ae-e9d5-0fa0958dfa3f
* Content: [Microsoft Teams Rooms Pro Management update management - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/update-management)
* Content Source: [Teams/rooms/update-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/update-management.md)
* Service: **msteams**
* GitHub Login: @altsou
* Microsoft Alias: **altsou**

**Comment by get-itips** [comment]
Hello @eomullig thanks for your feedback
