### ISSUE TITLE
Need to add a section on this doc about where recordings live

### ISSUE THREAD

**Issue by StainlessSteele** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9394]
We need to add content here about
If in Yammer - SharePoint drive of Yammer community meeting is hosted, both for QuickStart in Yammer and Teams Encoder in Yammer
If on Teams - 
If by Encoder, in OneDrive of organizer, if they joined. If they didn't then in OneDrive of first producer joined.
If Public, then in AMS for 180 days

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3694b84c-c1d9-42f3-729b-9ad83fc52c5c
* Version Independent ID: 3694b84c-c1d9-42f3-729b-9ad83fc52c5c
* Content: [Overview of the encoder for streaming in Microsoft Teams - Microsoft Teams](https://review.learn.microsoft.com/en-us/MicrosoftTeams/teams-encoder-overview?branch=heidip-encoder-based-RTMP)
* Content Source: [Teams/teams-encoder-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-encoder-overview.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by dariomws** [comment]
Hi @StainlessSteele, same issue here. It seems that this article is not public yet.
