### ISSUE TITLE
Possible Omission?

### ISSUE THREAD

**Issue by dotson98** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9399]
This article (dated 9/22) meshes Teams Meeting recording settings with 1:1 recording settings.  Articles we are reading and through trial and error state that the settings for 1:1 recordings are under Voice -> Calling Policies.  This was changes 5/31/21. 
 Can anyone Confirm?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by get-itips** [comment]
Hello @dotson98 
How are you?
I am afraid I don't fully understand your inquiry, can you please detail what you see is wrong with this article?
Thank you!

**Comment by get-itips** [comment]
Hello @dotson98 could you see my question here? thanks

**Comment by dotson98** [comment]
My question was a bit poorly worded; sorry.  We were just seeing differences in what we were reading and needed clarification.  No further help is required.
