### ISSUE TITLE
English, please

### ISSUE THREAD

**Issue by SCIS-guy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9400]
Please change the title of the article to use proper English by adding an appropriate article. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d45becfa-69d7-b956-cf97-4b14c97ad92c
* Version Independent ID: 81d5bad1-fc63-26dc-5c08-31c8d07c828d
* Content: [What is Phone System - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/what-is-phone-system-in-office-365)
* Content Source: [Teams/what-is-phone-system-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-is-phone-system-in-office-365.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Thank you for your feedback.  However, Phone System is the name of the product.  This is proper English.  For example, we don't say Here's what you get with The Windows.  Closing this issue.
