### ISSUE TITLE
Screenshot update

### ISSUE THREAD

**Issue by LiamSevier** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9401]
Looks like the screenshot for direct guest join options may be out of date (only shows Zoom, when WebEx is also available).  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c62081e-2421-80b9-8ba9-aaf8fd55e432
* Version Independent ID: 5df3c5e5-978f-cfa7-9e5c-3cd7f65fa8ff
* Content: [Enable Teams Rooms devices to join third-party meetings - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/third-party-join)
* Content Source: [Teams/rooms/third-party-join.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/third-party-join.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @LiamSevier, thank you for your feedback.

@dstrome, do you think we can update the screenshot? Thanks!

**Comment by scanum** [comment]
@dstrome Hope all is well. Wanted to check in to see if there is an update to this issue? Thanks.

**Comment by scanum** [comment]
@dstrome Hope all is well. Wanted to check in to see if there is an update to this issue? Thanks.

**Comment by scanum** [comment]
@dstrome Hope all is well. Wanted to check in to see if there is an update to this issue? Thanks.

**Comment by scanum** [comment]
@dstrome Hope all is well. Wanted to check in to see if there is an update to this issue? Thanks.

**Comment by scanum** [comment]
@dstrome Hope all is well. Wanted to check in to see if there is an update to this issue? Thanks.

**Comment by NancyForero** [comment]
There should be two screenshots added to the document:
1. This image below should replace the current one in https://learn.microsoft.com/en-us/microsoftteams/rooms/third-party-join#step-3b-enable-third-party-meetings-on-teams-rooms-on-android 
![MTRADGJ](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/63427703/19c4a6cb-e3a9-4019-917c-90ab717d6563)

2. This image below should be added to this section https://learn.microsoft.com/en-us/microsoftteams/rooms/third-party-join#use-device-settings under step 6.
![Meetings](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/63427703/519d6be4-3bfb-435a-9f01-00dfb1c44ad0)

**Comment by NancyForero** [comment]
@scanum @tonysmit updated documentation with new screenshots for MTR-W and MTR-A

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
