### ISSUE TITLE
Incorrect/outdated information

### ISSUE THREAD

**Issue by dkiehl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9404]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-resource-accounts)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Hi @dkiehl Hope you are well and thanks for the feedback, could you kindly help me explain a little bit more about what information is incorrect or outdated? Thanks!

**Comment by scanum** [comment]
@dkiehl Hope all is well. Wanted to follow up here. Thanks.
