### ISSUE TITLE
Grant-Cs* policy support. 

### ISSUE THREAD

**Issue by royalpritpal** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9406]
Hi there, 

Will there be support coming for 'Grant-CsTenantDialPlan' 'Grant-CsOnlineVoiceRoutingPolicy' and 'Grant-CsTeamsCallingPolicy'? 
I have app based authentication working but can't seems to grant these policies. 

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32304edf-550b-72a3-57df-6dcc29dba56d
* Version Independent ID: 32304edf-550b-72a3-57df-6dcc29dba56d
* Content: [Application-based authentication in Teams PowerShell Module - Microsoft Teams](https://learn.microsoft.com/en-gb/MicrosoftTeams/teams-powershell-application-authentication)
* Content Source: [Teams/teams-powershell-application-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-application-authentication.md)
* Service: **msteams**
* GitHub Login: @pbafna03
* Microsoft Alias: **pbafna**

**Comment by royalpritpal** [comment]
this is what I get. 
`Grant-CsOnlineVoiceRoutingPolicy: C:\Users\pritpal.karir\OneDrive - Holmes Group Ltd\Documents\PowerShell\TeamsAutomation.ps1:110:5
Line |
 110 |      Grant-CsOnlineVoiceRoutingPolicy -Identity $upn -PolicyName $Rout …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Access Denied.

Grant-CsTeamsCallingPolicy: C:\Users\pritpal.karir\OneDrive - Holmes Group Ltd\Documents\PowerShell\TeamsAutomation.ps1:127:5
Line |
 127 |      Grant-CsTeamsCallingPolicy -Identity $upn -PolicyName $CallingPol …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Access Denied.

Grant-CsTenantDialPlan: C:\Users\pritpal.karir\OneDrive - Holmes Group Ltd\Documents\PowerShell\TeamsAutomation.ps1:144:5
Line |
 144 |      Grant-CsTenantDialPlan -PolicyName $dialPhonePlan -Identity $upn
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Access Denied.`

**Comment by pbafna03** [comment]
@royalpritpal  - Grant-Cs* cmdlets are currently not supported for Application-based authentication but will be rolled out soon.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by royalpritpal** [comment]
@scanum  do you think opening a support ticket will help to speed up the process of making Grant-Cs* available to our tenant?

**Comment by pbafna03** [comment]
@royalpritpal  - This is rolled out now, ref - https://learn.microsoft.com/en-us/microsoftteams/teams-powershell-application-authentication

**Comment by royalpritpal** [comment]
> @royalpritpal - This is rolled out now, ref - https://learn.microsoft.com/en-us/microsoftteams/teams-powershell-application-authentication

yup I saw that last week. All working well now, Thanks :)
