### ISSUE TITLE
Broken Link - Manage Teams setting for your organization

### ISSUE THREAD

**Issue by packman83** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9407]
The link for 'Manage Teams setting for your organization' redirects to the current page. Navigating to the URL directly (https://learn.microsoft.com/en-us/microsoftteams/enable-features-office-365) also does not work. I could not find what the correct link should be.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: effdcda2-f15f-6acf-063d-35a8b3bd8669
* Version Independent ID: 2d12c30a-b43c-6a2f-7764-aa9c14225a57
* Content: [Manage and monitor Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-teams-overview)
* Content Source: [Teams/manage-teams-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-teams-overview.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Thanks for the feedback.  There isn't one all-up settings topic as indicated by the following in the article:
Some manage topics remain under the relevant workload sections. For more information, see the overview articles for the following...

I've removed the erroneous bulleted item and link.  Change should go live today.  Closing this issue.
