### ISSUE TITLE
Bad link in Teams Phone Mobile article

### ISSUE THREAD

**Issue by JAndre7** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9408]
There's a broken link at the top. I have attached a screenshot showing the bad link (404).

![image](https://user-images.githubusercontent.com/69250539/195704244-a329c87d-2715-4fbc-acf4-54ceb2e71766.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d80cd376-5bcb-2548-ae65-14fe0cc62445
* Version Independent ID: d80cd376-5bcb-2548-ae65-14fe0cc62445
* Content: [Plan for Teams Phone Mobile - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/operator-connect-mobile-plan)
* Content Source: [Teams/operator-connect-mobile-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/operator-connect-mobile-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Thanks for bringing this to our attention.  Fixing now...
