### ISSUE TITLE
Script URL not working

### ISSUE THREAD

**Issue by grahambird80** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#941]
When I try and download the SkypeRoomProvisioningScript.ps1 using the link it just takes me to the MS website - https://www.microsoft.com/en-gb/ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6e535af-4ee2-f682-db9f-631a2a2267d7
* Version Independent ID: 4e7c14c5-0fb4-127e-90c0-5034e3854daa
* Content: [Deploy Skype Room Systems v2 with Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/with-skype-for-business-server-2015)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/with-skype-for-business-server-2015.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/with-skype-for-business-server-2015.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by AndreaBarr** [comment]
@grahambird80 Thank you for this feedback

I will get this link issue to the Teams/Skype for Business team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
