### ISSUE TITLE
Step 8 may be better using UPN rather than sipaddress?

### ISSUE THREAD

**Issue by flagmanchris** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9411]
On step 8 the recommendation is to use:

```powershell
Set-CsPhoneNumberAssignment -Identity $user.SipAddress -PhoneNumber $user.LineUri.Replace("tel:","") -PhoneNumberType DirectRouting
```

However with our environment I found sipaddress doesn't always match UPN so UPN seems a better fit to ensure the correct user is updated:

```powershell
Set-CsPhoneNumberAssignment -Identity $user.UserPrincipalName -PhoneNumber $user.LineUri.Replace("tel:","") -PhoneNumberType DirectRouting
```

This may also be an issue in step 5 if the sip address in teams doesn't match the on prem sip address. Could possibly update the sip address post move.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5566de7d-1d1e-ba92-743b-dc772b49752a
* Version Independent ID: c15342ff-eb3a-5f14-4bba-217c31aa1299
* Content: [Decide how to manage attributes after decommissioning - Skype for Business Hybrid](https://learn.microsoft.com/en-us/skypeforbusiness/hybrid/cloud-consolidation-managing-attributes?source=docs)
* Content Source: [Skype/SfbHybrid/hybrid/cloud-consolidation-managing-attributes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/cloud-consolidation-managing-attributes.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
