### ISSUE TITLE
Doco clarification

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9413]
Could you add clarification around the new Teams Room licenses (Basic/Pro) and user interface. i.e. can adding a Teams room basic satisfy the license entitlement for the MeetingSignIn mode for a Teams certified handset?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62d58962-9b2f-0231-187b-58c845e52a0c
* Version Independent ID: b3045cca-8bcb-8d30-0dda-49aed3009172
* Content: [Set Microsoft Teams Android devices user interface - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/devices/Teams-Android-devices-user-interface)
* Content Source: [Teams/devices/Teams-Android-devices-user-interface.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/Teams-Android-devices-user-interface.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @SvenBell, thank you for your feedback.

I think the information about the licenses is included in the article:
"The license assigned to the user account must have at least the same license entitlements as the desired user interface. The Common Area Phone license only allows the Common Area phone user interface. The meeting room license allows meeting room and common area phone user interfaces. An E3 or E5 license supports all sign-in modes."

Then you need to have in mind the available features on each license, for example:
https://learn.microsoft.com/microsoftteams/rooms/rooms-licensing
You can assign an MTR license and change the user interface to Common Area Phone, but you won't be able to make or receive PSTN calls. Maybe you can use this CAP in the lobby or reception to reach internal users.

**Comment by scanum** [comment]
Hi @SvenBell Does this answer your question? Thanks.
