### ISSUE TITLE
Room Basic and Phone Standard

### ISSUE THREAD

**Issue by Korbyn72** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9415]
This page doesn't state one way or another, but can you assign the Phone Standard license with Teams Room Basic account to an account?  Thinking legacy systems that will get no value out of the Rooms Pro, but still need PSTN capability.  I would assume I can, but I currently don't have an environment to test with.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-licensing.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @Korbyn72, thank you for your feedback.

@dstrome, could you confirm this information? I think it works, but I can't confirm what the official support statement is. Thank you!

**Comment by Korbyn72** [comment]
I do not have an environment for which to “test” it with, hence me posing the question for clarification.  I too suspect it will work, but I’m not going to tell a customer that.  It’s bad enough as it is that they took the $15 product and made it a $60 product with no added benefit, but here’s something free that’s slightly above nothing.  They could at least say if it will be on par with the previous Meeting Rooms Std if you get the Basic and add Phone Standard and Audio Conf.

**Comment by Korbyn72** [comment]
Tom Arbuthnot appears to have done some testing:

Microsoft Teams Rooms Pro and Microsoft Teams Rooms Basic, everything you need to know. - Tom Talks<https://tomtalks.blog/microsoft-teams-rooms-pro-and-microsoft-teams-rooms-basic-everything-you-need-to-know/>

Can you add a Teams Phone licence and/or AAD P1 licence to Microsoft Teams Rooms Basic if you don’t want to jump to Pro but needed Teams Phone/AAD on your MTR?
Yes, You can “stack” multiple licences on a single account to have Teams Rooms basic plus Teams Phone or Azure AD P1 and/or a Teams Panel with a Basic room.

Can I use user licences (for example E3, E5) for Microsoft Teams Rooms instead?
No, this is not supported/against terms of service (reference). E licences are not for shared devices.


K.

**Comment by scanum** [comment]
Hi @dstrome Hope all is well. Wanted to check in with you if there is an update on this issue? Thanks.

**Comment by scanum** [comment]
Hi @dstrome Hope all is well. Wanted to check in with you if there is an update on this issue? Thanks.

**Comment by scanum** [comment]
@dstrome Hope all is well. Wanted to check in to see if there is an update to this issue? Thanks.

**Comment by scanum** [comment]
@dstrome Hope all is well. Wanted to check in to see if there is an update to this issue? Thanks.

**Comment by Korbyn72** [comment]
I haven't been able to test, but i hear it "should" work...

**Comment by scanum** [comment]
@dstrome Hope all is well. Wanted to check in to see if there is an update to this issue? Thanks.

**Comment by scanum** [comment]
@dstrome Hope all is well. Wanted to check in to see if there is an update to this issue? Thanks.

**Comment by tonysmit** [comment]
Closing this issue. Our official response is that stacking licenses is not recommended. This comes from the PMs and marketing.
