### ISSUE TITLE
Mentions in Lists etc seem not to be possible

### ISSUE THREAD

**Issue by J-a-k-o-b** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9416]
When trying to @ mention an external identity in a shared channel, the external user is not listed and its not possible to mention him.
The external participant can also not use @ mentions to tag members.

As you see here, there are more users that are complaining about this issue
https://techcommunity.microsoft.com/t5/microsoft-teams/mentioning-in-teams-shared-channels-seems-to-be-not-working-or/td-p/3552474

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by J-a-k-o-b** [comment]
Hi @scanum,
i've opened a ticket (#33519103) for this and it was already solved with a link to this list specific user documentation
https://support.microsoft.com/en-us/office/add-and-reply-to-comments-in-list-items-9407aab9-6d43-4756-af72-d38177814a6e
There is one point listed that mentions are not possible for guests & anonymous users.
I think this shared channel feature limitation should also be stated out here in the docs article
