### ISSUE TITLE
Script URL not working

### ISSUE THREAD

**Issue by grahambird80** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#942]
When I try and download the SkypeRoomProvisioningScript.ps1 using the link it just takes me to the MS website - https://www.microsoft.com/en-gb/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d495057-36be-b228-0483-aae89fd01666
* Version Independent ID: f02fa875-b84b-5501-5879-17ea3d017142
* Content: [Configure accounts for Skype Room Systems v2](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/room-systems-v2-configure-accounts)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/room-systems-v2-configure-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/room-systems-v2-configure-accounts.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by AndreaBarr** [comment]
@grahambird80 Thank you for this feedback
I will get this link issue to the Teams/Skype for Business team for investigation.
The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.
I made a note to request the team to update this when the work is complete.

**Comment by jambirk** [comment]
try it now. it should be working again.

**Comment by grahambird80** [comment]
Thats great thanks
