### ISSUE TITLE
View Only Mode Enhancements coming

### ISSUE THREAD

**Issue by bwilsonms** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9421]
Need to update information in regards to coming technology like OnePlayer and additions in this space

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2bf705c2-1f24-bdb5-e712-e8408b941aca
* Version Independent ID: ddedd7e0-7d85-06e0-7f20-8b83b3dccec7
* Content: [View-only meeting experience - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/view-only-meeting-experience)
* Content Source: [Teams/view-only-meeting-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/view-only-meeting-experience.md)
* Service: **msteams**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by dariomws** [comment]
Hi @bwilsonms, thank you for your feedback.

If these features are not yet in general availability, are you sure that we should include them here? If yes, could you provide the information to add?

**Comment by bwilsonms** [comment]
@StainlessSteele do you have one opened on this already?

**Comment by bwilsonms** [comment]
After discussion will open later with more information, thanks,
