### ISSUE TITLE
Export License Tables

### ISSUE THREAD

**Issue by KFMjr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9423]
Can you put the features tables into a separate csv file to make it easier to export the license information? Or provide graphics/image files that break the offers down? Aaron Dinanges GitHub hasn't doesn't provide an overview of Teams (it also hasn't been updated since Jan of this year). I tried using the importhtml function but it fails to parse the page properly. TIA

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-licensing.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @davidjfriedman, thank you for your feedback.

I'll forward your feedback, but I cannot promise that the content will be added to the article. In addition, you can copy and paste the tables to an Excel spreadsheet and save it to a CSV file or another format.

Aaron Dinnage site (https://m365maps.com/) is a third-party site for which Microsoft does not provide any support.

@dstrome, FYI.

**Comment by dariomws** [comment]
@davidjfriedman, yes, sure, my apologies for that. I'm wondering why I tagged you by mistake :)

Hi @KFMjr, thank you for your feedback.

I'll forward your feedback, but I cannot promise that the content will be added to the article. In addition, you can copy and paste the tables to an Excel spreadsheet and save it to a CSV file or another format.

Aaron Dinnage site (https://m365maps.com/) is a third-party site for which Microsoft does not provide any support.

**Comment by KFMjr** [comment]
Thanks for getting back. Copying & pasting is what I would rather avoid as I (and I suspect many others) don't want to have to spend additional time reformatting worksheets (or watching multiple YouTube videos on how to) when simply making the charts available in blob would make sense. This is speaking from the perspective of an 'accidental techie' so I'm sure this doesn't apply to power users but to me from even a sales perspective this would make sense. Again, thanks for the follow up and the effort that's put into creating and maintaining the document libraries.


Best regards,

Kevin Mulhall

Technical Customer Success Manager

***@***.******@***.***> | www.techsoup.org
<http://www.techsoup.org/>Schedule a Call with Me: Bookings ***@***.***/bookings/>

Office: +1 (650) 449-8149 (call or text)

Connect on LinkedIn - www.linkedin.com/in/kevin-mulhall-jr/<http://www.linkedin.com/in/kevin-mulhall-jr/>

____________________________________________



Connect. Activate. Transform.<https://wwwww.techsoup.org/growth-capital-campaign> #investtechsoup

________________________________

**Comment by dariomws** [comment]
@dstrome, FYI.
