### ISSUE TITLE
<DualScreenMode>0</DualScreenMode> does not seem to work, dual screen mode always on

### ISSUE THREAD

**Issue by TAz00** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9424]
`<DualScreenMode>0</DualScreenMode>` does not seem to work, dual screen mode always on.

Shows 'Dual Monitor Mode' as disabled in Teams Rooms Settings, and greyed out due to being a Teams Rooms Basic license.

But there is no conference video available, unless plugging in a second display. 

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til learn.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 25a70665-5bf1-14f7-1df0-7596effcaf48
* Version Independent ID: 813cf005-2777-9419-d1ce-3f9401ac267c
* Content: [Remotely manage Microsoft Teams Rooms device settings - Microsoft Teams](https://learn.microsoft.com/da-dk/MicrosoftTeams/rooms/xml-config-file?redirectedfrom=MSDN)
* Content Source: [Teams/rooms/xml-config-file.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/xml-config-file.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
