### ISSUE TITLE
Does this page apply to Teams?

### ISSUE THREAD

**Issue by nastassiar** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#943]
It isn't listed in the applies to section 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 151a352b-793a-c6a3-d70c-a4f785fde111
* Version Independent ID: c2e27fca-a954-ebbb-8f40-87eb5498599c
* Content: [Skype for Business certification program - How to Join](https://docs.microsoft.com/en-us/skypeforbusiness/certification/how-to-join)
* Content Source: [Skype/SfbPartnerCertification/certification/how-to-join.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbPartnerCertification/certification/how-to-join.md)
* Service: **skype-for-business**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by AndreaBarr** [comment]
@nastassiar Thank you for this feedback

I will get this over to the Teams/Skype for Business team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by jambirk** [comment]
page updated in PR 1611, we can close this.
