### ISSUE TITLE
Old references in the PDFs

### ISSUE THREAD

**Issue by Rangeball** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9430]
Some of these PDF/posters should be updates e.g. for Teams logical architecture Meeting Recordings still references Stream (Classic). This has largely been shifted to OneDrive for Business/SharePoint Online? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ad624-9792-91b7-c85f-09b839b1ea44
* Version Independent ID: e8288f91-11bd-599b-8a88-074917b315a4
* Content: [Microsoft Teams IT architecture and voice solutions posters - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-architecture-solutions-posters?source=docs)
* Content Source: [Teams/teams-architecture-solutions-posters.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-architecture-solutions-posters.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @Rangeball 
I am looking into this.

**Comment by get-itips** [comment]
Hello @Rangeball 
I could get the information that there is currently a work in progress to update these resources, no ETA yet.
Thanks for your feedback.
