### ISSUE TITLE
Remove Teams Phone Mobile Add-on SKU which doesn't exist

### ISSUE THREAD

**Issue by limp15000** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9431]
Hello, 
We still reference Teams Phone mobile add-on SKU which has been cancelled. 
Teams phone mobile is available via the Teams Phone System SKU or E5.
Many thanks for fixing,
Thomas
![image](https://user-images.githubusercontent.com/23700466/197182638-70b066b4-c187-405a-a819-6cdc104093ee.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d80cd376-5bcb-2548-ae65-14fe0cc62445
* Version Independent ID: d80cd376-5bcb-2548-ae65-14fe0cc62445
* Content: [Plan for Teams Phone Mobile - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/operator-connect-mobile-plan?source=docs)
* Content Source: [Teams/operator-connect-mobile-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/operator-connect-mobile-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @limp15000 I am looking into this

**Comment by get-itips** [comment]
I was notified that the Teams Phone Mobile Add-on SKU is indeed fully live now.
