### ISSUE TITLE
PhoneNumberType OCMobile does not exist

### ISSUE THREAD

**Issue by taskellood** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9438]
It seems like the PhoneNumberType OCMobile value does not exist today. I just tried to assign a user with it and received the following error message. But in the example, it clearly states that OCMobile should be used for assigning Teams Mobile numbers. The module used is 4.8.1-preview. 

![image](https://user-images.githubusercontent.com/100134956/197812999-23ba0345-2132-4e4c-a6f2-8d4df5059094.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69c67496-cace-f833-7cfc-dca7722fef3e
* Version Independent ID: 5a14f81c-529c-4971-5ce8-39633834d4d3
* Content: [Assign, change, or remove a phone number for a user - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/assign-change-or-remove-a-phone-number-for-a-user)
* Content Source: [Teams/assign-change-or-remove-a-phone-number-for-a-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-change-or-remove-a-phone-number-for-a-user.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by vlethiec** [comment]
Hi @dariomws, 

I saw in your commit, you removed the mention of OCMobile from the documentation page. Does it mean it is not available yet?
Thanks in advance for your help. 

Regards, 

Vincent

**Comment by dariomws** [comment]
Hi @vlethiec,

Yes, it is not available, and I can't say if it will be available later. For Teams Phone Mobile, you should also use -PhoneNumberType OperatorConnect.
