### ISSUE TITLE
URL contains premium not pro

### ISSUE THREAD

**Issue by mmistryms** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9444]
Hi - The URL of the Teams Rooms Pro page contains the word Premium.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8f76bc0c-a899-b572-588a-b86acae1b740
* Version Independent ID: 3c5b6414-c796-7e50-9e03-b578c7995071
* Content: [Microsoft Teams Rooms Pro management - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/microsoft-teams-rooms-premium?source=docs)
* Content Source: [Teams/rooms/microsoft-teams-rooms-premium.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/microsoft-teams-rooms-premium.md)
* Service: **msteams**
* GitHub Login: @altsou
* Microsoft Alias: **altsou**

**Comment by dariomws** [comment]
Hi @mmistryms, thank you for your feedback.

The article was updated after rebranding from Premium to Pro but the URL update will take some more time.
