### ISSUE TITLE
MTRoA vs MTRow

### ISSUE THREAD

**Issue by jlatessa** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9445]
Looks like some things are missing. 
For example, MTRoW supports multiple cameras and MTRoA does not.
Can this document be updated?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 64cc650b-b313-cfab-9f45-190b94c128f4
* Version Independent ID: 9e93ac07-3f1b-9fd4-1907-17f0075bd837
* Content: [Teams Rooms for Windows and Android feature comparison - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/teams-devices-feature-comparison)
* Content Source: [Teams/rooms/teams-devices-feature-comparison.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/teams-devices-feature-comparison.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @jlatessa, thank you for your feedback.

It's true that not all the features are included in the article. I'm extracting the following sentence from the article:
"To help guide you as to what features are available on different platforms, you can refer to the chart below, which will be updated periodically. Not all Teams Rooms features will be included on this list, so please continue to consult the [Microsoft 365 roadmap](https://www.microsoft.com/microsoft-365/roadmap) and Microsoft sales representatives for additional details."

**Comment by scanum** [comment]
Hi @jlatessa Hope all is well. Does this answer your questions? Thanks.
