### ISSUE TITLE
Microsoft Teams Audio Conferencing with dial-out to USA/CAN

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9446]
Please add the new "Microsoft Teams Audio Conferencing with dial-out to USA/CAN" add-on to the page.

The table of add-on's lists "Audio Conferencing" with a link to see pricing.
> For pricing info, see [Pricing for Audio Conferencing](https://go.microsoft.com/fwlink/?linkid=799762).

That page lists two add-on's. One is free and one is not.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: abae7324-861d-7ca7-7239-a5df8fd927d5
* Version Independent ID: 8a30bd2f-9bc3-a0a8-8b31-d53836ead4d0
* Content: [Microsoft Teams add-on licenses - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing)
* Content Source: [Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by jonwbstr** [comment]
Correction, it lists a free add-on, and E5, I do not see the $3 Audio Conferencing add-on listed. What's the story there?

**Comment by DaniEASmith** [comment]
@ruizoscar Maybe six months ago, in our Teams add-on licensing doc, we had removed quite a bit of Audio Conferencing plan information because a few things were still in flux. Can you please take a look at this GitHub issue and advise me on how we can update the doc to make sure it's current with what's available for Audio Conferencing options? Thank you, sir!

**Comment by jonwbstr** [comment]
My understanding as of this morning, 
Audio Conferencing is free for some plans, and $3/user/mo if you don't have a qualifying plan.

The pricing page could use some updates as well, as it doesn't seem to really address "free" with conditions. or $3. It send you to buy it in your tenant, which might tell people something. CSP customers (and partner sales people) would still be hard pressed to find clarification online.

**Comment by DaniEASmith** [comment]
@jonwbstr On the learn.microsoft.com site, we don't list prices for a couple of reasons. One, we don't own the sales pages where prices should be clearly stated. This helps ensure we don't ever contradict sales pages. Two, customers may be able to negotiate pricing with their Microsoft representative, which we can't accurately portray in our docs. The https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing article is written to be general and point readers to more detailed pages for additional information.
