### ISSUE TITLE
GCCH limitations

### ISSUE THREAD

**Issue by bradbrill** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9448]
PSTN reports don't appear to be available/supported in GCC-H/DoD. Could we include some clarification/documentation on whether PSTN reports are supported in GCCH.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ad0c889-56d5-35fe-de15-177b6d922d07
* Version Independent ID: e4363647-33e1-b665-5881-169fb619a5b3
* Content: [Microsoft Teams PSTN usage report - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/pstn-usage-report)
* Content Source: [Teams/teams-analytics-and-reports/pstn-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/pstn-usage-report.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @bradbrill, thank you for your feedback.

That information is included in the overview article:
https://learn.microsoft.com/microsoftteams/teams-analytics-and-reports/teams-reporting-reference

**Comment by scanum** [comment]
Hi @bradbrill Hope all is well. Does this answer your question? Thanks.

**Comment by bradbrill** [comment]
> Hi @bradbrill Hope all is well. Does this answer your question? Thanks.

Yes it does, thank you.
