### ISSUE TITLE
Calling Party Name option missing from this page

### ISSUE THREAD

**Issue by dinocaputo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9449]
[Enter feedback here]
This option is not displayed here and should be since its part of the policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2b8aefb-f373-fa6e-dd79-e97cded117e8
* Version Independent ID: 2c73f49c-d34f-c1da-648d-8675f10c0183
* Content: [Manage caller ID policies in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/caller-id-policies)
* Content Source: [Teams/caller-id-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/caller-id-policies.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by JensTrier** [comment]
@dinocaputo Thanks for the feedback. Will fix it. Feel free to close this issue
