### ISSUE TITLE
Article is not yet SfB 2019 aware

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#945]
This article doesn't list what versions of SfB it applies to, and does not clearly provide SfB2019 guidance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8c5958a-c5e5-5aba-211a-2886c86ba831
* Version Independent ID: e53ed9d2-4ee4-346a-054b-6cf44b6a189b
* Content: [Back End Server high availability in Skype for Business Server](https://docs.microsoft.com/en-us/SkypeForBusiness/plan-your-deployment/high-availability-and-disaster-recovery/back-end-server)
* Content Source: [Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/back-end-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/high-availability-and-disaster-recovery/back-end-server.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by AndreaBarr** [comment]
@TorrenManson Thank you for this feedback

We apricate you pointing out how we can improve this article. I will get this over to the Teams/Skype for Business team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@dariomws306 Could you please investigate this?

**Comment by dariomws306** [comment]
Hi @TorrenManson , almost SfB Server articles apply to both: 2015 and 2019. In this case you can see that all apply to both except for Database Mirroring, you have a note there where you can see that it's not supported by 2019.
Also, I am update SQL Server versions.
