### ISSUE TITLE
Missing information on external users

### ISSUE THREAD

**Issue by JMAvenant** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9450]
Kindly add limitations on external (Guest) user limitations or confirm that this is included in the number of users.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by dariomws** [comment]
Hi @JMAvenant, thank you for your feedback.

That information is more related to Azure AD:
https://learn.microsoft.com/azure/active-directory/enterprise-users/directory-service-limits-restrictions

- By default, a maximum of 50,000 Azure AD resources can be created in a single tenant by users of the Azure Active Directory Free edition. If you have at least one verified domain, the default Azure AD service quota for your organization is extended to 300,000 Azure AD resources.
- Resource limitations apply to all directory objects in a given Azure AD tenant, including users, groups, applications, and service principals.

**Comment by scanum** [comment]
Hi @JMAvenant Hope all is well. Does this answer your question? Thanks.

**Comment by JMAvenant** [comment]
Morning,

  Thank you - since this question was done on behalf of the community, I trust that you made this clarification in the documentation.

  A direct answer to my mailbox was not required - as it is not scalable.

Warm regards,
James M Avenant  | Partner Development Manager - Business Applications | Microsoft South Africa
View my availability or request a meeting ***@***.***/bookings/> on partner business development.

First line support queries are managed via Partner Support<https://www.microsoft.com/en-us/us-partner-blog/2019/01/25/partner-support-series-start-with-partner-frontline-support/> or the South Africa Partner Community Zone<https://www.microsoftpartnercommunity.com/t5/South-Africa-Partner-Zone/ct-p/SouthAfricaPartnerZone>
