### ISSUE TITLE
Distribution by Agent and Call Queue - Average Call Duration Broken

### ISSUE THREAD

**Issue by RobMSP** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9451]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/20458038/198993201-d28f2f10-f4be-4337-969e-3030e61379f1.png)

The Average call duration caculation is broken.. I suspect this user isn't spending an avergae of 5 hours on a call for 27 calls during a week.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 628345c6-f5f9-fe8e-bfff-faea00a8a25c
* Version Independent ID: 30f2d051-5af5-0063-7099-38b5b08ec1e4
* Content: [Auto Attendant & Call Queue Historical Report - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/aa-cq-cqd-historical-reports)
* Content Source: [Teams/aa-cq-cqd-historical-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/aa-cq-cqd-historical-reports.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by RobMSP** [comment]
Uh, I reported the problem 7 days ago.
9 Hours ago, you tagged the problem as 'haven't heard from me' not exactly sure what you were expecting to hear from me.

I guess a bug really is a feature, or cudo's for my staff having an average call duration of slightly more than 5 hours...

**Comment by CLYVR** [comment]
@RobMSP Thanks for bringing this to our attention.  Looking into this now and expect to publish an updated version of the template shortly.

**Comment by CLYVR** [comment]
@RobMSP While waiting for the new version to be released, if you would please do the following on your template as I believe this will resolve the issue:

Agent Timeline Tab

- Click in the "Distribution by Agent and Call Queue" box
- In the "Visualizations" field on the right side, find the "Tooltips" box
- Click on the down chevron and select "Average"

Save your template.

If this doesn't resolve the issue, please let me know.

Thanks!
