### ISSUE TITLE
Change HER to more inclusive THEIR

### ISSUE THREAD

**Issue by jerlev-p** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9453]
Should "her" gender-specific mentions be changed to more generic words like "their" or something similar?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a162ef5c-3099-7f58-4178-d29e3ec2b5a7
* Version Independent ID: 6ca31e56-052d-6c62-1323-b5aaaae1f04a
* Content: [User presence in Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/presence-admins)
* Content Source: [Teams/presence-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/presence-admins.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@jerlev-p I know the product teams are always looking for user feedback and how to make Teams better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice 

Skype for Business: https://www.skypefeedback.com/.
