### ISSUE TITLE
Multiple-tenant team

### ISSUE THREAD

**Issue by bernatagulloesbrina** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9455]
I don't see any mention of multiple-tenant teams
is it possible to create a team that includes all users from 2 AAD tenants and stays in sync? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an organization-wide team in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@bernatagulloesbrina it's not possible to create a team with members from multiple tenants, but you can use a shared channel within a team to collaborate with people from another tenant. See [Shared channels in Microsoft Teams](https://learn.microsoft.com/microsoftteams/shared-channels) and [Collaborate with external participants in a shared channel](https://learn.microsoft.com/microsoft-365/solutions/collaborate-teams-direct-connect) for details.
