### ISSUE TITLE
Teams VDI support for E911 work-from-home?

### ISSUE THREAD

**Issue by JasonSmith-MS** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9456]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 961b5563-e3bd-cb77-e411-80958052e0d1
* Version Independent ID: 961b5563-e3bd-cb77-e411-80958052e0d1
* Content: [Emergency addresses for remote locations - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/emergency-calling-dispatchable-location)
* Content Source: [Teams/emergency-calling-dispatchable-location.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/emergency-calling-dispatchable-location.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by JasonSmith-MS** [comment]
Will this page be updated to include how the new VDI support (for Citrix and Azure which are rolling out now)? Or will it be added on the Teams for VDI page instead?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
