### ISSUE TITLE
Missing Documentation Around Permissions required for Assigning Call Queues to Team Channels

### ISSUE THREAD

**Issue by ckarawani** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9458]
Seems **Teams Administrators** Cannot Assign/Modify Call Queue assignment to teams channels:

<img width="951" alt="image" src="https://user-images.githubusercontent.com/2483804/199748224-3264cc78-3391-4038-b3f5-b0360a1577c2.png">

(Perhaps this is due to the queue being assigned to a private channel?) It would be good to get some documentation around this.

**Comment by scanum** [comment]
Hi @ckarawani Wanted to follow up here one more time before we close this issue. Thanks!

**Comment by ckarawani** [comment]
hey @scanum sorry for the delay. The doc describing creating/configuring call queues is here:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-call-queue.md

It seemed at the time that being a teams administrator was not sufficient in being able to assign call queue to a teams channel so I was curious on the missing role required.  I must admit that I now cannot reproduce the screenshot provided.

**Comment by scanum** [comment]
@dariomws

**Comment by dariomws** [comment]
Hi @ckarawani, thank you for your feedback.

I can't reproduce the problem either. I can create a call queue with a Teams channel using an account assigned the Teams admin role. Not sure how we can improve the article.

**Comment by ckarawani** [comment]
Closing as invalid. Unable to reproduce.
