### ISSUE TITLE
Android Sign Out

### ISSUE THREAD

**Issue by JDCNS** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9460]
That's not right. I finally found the sign out myself by going to my face | Settings | Sign Out on Android. More only gives you other apps to run.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4d56b6e-a220-710c-f051-6e78bf0883fe
* Version Independent ID: d1aa0964-725e-0b99-00c0-7ddcfad46920
* Content: [Sign out of Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/sign-out-of-teams)
* Content Source: [Teams/sign-out-of-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sign-out-of-teams.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
