### ISSUE TITLE
Documentation states more phone services are available in Korea than the operators will actually provide

### ISSUE THREAD

**Issue by neilr8133** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9463]
Page says that calling and phone service is available for (South) Korea, however when you go to Operator Connect it lists 3 companies: Tata Communications, Intrado, and NTT.

* Tata Communications says they will only provide service for 100 employees or more;
* When you try to add Intrado as an Operator, it says they only provide Audio Conferencing dial-in numbers, and not Teams Phone Calling;
* And NTT says they don't provide service in Korea and have asked Microsoft to remove them from the list.

So really there is only one option (Tata Communications) and if you don't need 100 phone numbers then there is no option at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 46b3fba6-3afd-851b-33f8-30f4ea5e44f8
* Version Independent ID: 5fb7767e-e572-19b3-4456-2dbbe278d346
* Content: [Availability in South Korea - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-south-korea)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-south-korea.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-south-korea.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @neilr8133, thank you for your feedback.

My apologies but I don't understand what is the specific update that you are requestion for the article. Could you provide more detail?

**Comment by scanum** [comment]
Hi @neilr8133 Hope all is well. Could you help us clarify the question? Thanks.

**Comment by neilr8133** [comment]
I suggest/ask that the documentation be updated to reflect that these partners are *not* providing service except under the circumstances indicated in my first comment.  The incorrect information in this document (and in the Teams Admin Center) caused my group to waste days trying to sign up with these vendors and is quite frustrating.

-Neil

**Comment by dariomws** [comment]
@neilr8133, if I'm not wrong, the article does not provide the list of providers, only the services available on each country. I cannot add specific information about the providers.

NTT should be removed soon from TAC.
