### ISSUE TITLE
"Manage Tags": Add Section: How to create/manage tags

### ISSUE THREAD

**Issue by DarkTrick** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9465]
I'm specifically missing the "how you create tags" section.

I feel 90% of the page is explaining the concept and suggestions on how to use tags. But **it doesn't get to the point in a clear way**: How do you actually create/manage tags.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b16e659e-cf07-268a-e224-fa444749ac29
* Version Independent ID: ee822a8d-b331-998f-e336-b1fa510f35c0
* Content: [Manage tags in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/manage-tags)
* Content Source: [Teams/manage-tags.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-tags.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@DarkTrick using and managing tags in teams is covered in [Using tags in Teams](https://support.microsoft.com/office/using-tags-in-teams-667bd56f-32b8-4118-9a0b-56807c96d91e). There's a link at the bottom. I'll move it up to make it more prominent.

**Comment by DarkTrick** [comment]
Thank you very much for the quick response!

OT: Feature note: Would be nice, if there was a twitter-like tag-feature where no prior managing is needed, people can opt-in themselves and is working in Channels and chats equally
