### ISSUE TITLE
License for guest access

### ISSUE THREAD

**Issue by ZhangjianEdmond** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9466]
Hi,  Need to confirm if guest ascess is available for  Teams Essentials since it is not mentioned here.

I believe there is no License required for guest access since Teams free version can also use guest access.
Partner got confused since only  Microsoft 365 Business Standard, Microsoft 365 Enterprise, and Microsoft 365 Education  is mentioned here.
Could we make it clearer? 

Thank you and best regards,

～～～～～～～～～～～～
https://learn.microsoft.com/en-us/microsoftteams/set-up-guests?source=recommendations

Licensing for guest access
Guest access can be used with all Microsoft 365 Business Standard, Microsoft 365 Enterprise, and Microsoft 365 Education subscriptions. No additional Microsoft 365 license is necessary. The billing model for Azure AD External Identities applies to guests in Microsoft 365. Only people from outside your organization can be invited as guests.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2492e210-08f9-a476-97ec-008926def961
* Version Independent ID: adcb0dd9-4a3c-b665-6e34-ce3276c89b4d
* Content: [Guest access in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/guest-access?source=docs)
* Content Source: [Teams/guest-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @ZhangjianEdmond, thank you for your feedback.

It's not included here because it's not available. For more information, see https://www.microsoft.com/microsoft-teams/compare-microsoft-teams-options.

**Comment by scanum** [comment]
Hi @ZhangjianEdmond Hope all is well. Does this answer your question? Thanks.
