### ISSUE TITLE
Perhaps incorrect statement..

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#947]
"All Edge Servers need to have the exact same certificate with the same private key for the Media Relay Authentication service."

But if you do have multiple Edge pools, then you do not need to have the same certification on all of the Edges. The same certificate is required between the Edge servers with in the same Edge pool. This is kind of decreasing possible errors when all certificates does not expire at the same time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72d9c2af-b933-f9a2-e189-387c881cffd0
* Version Independent ID: a614d386-7ce8-5c96-690e-b40231e67118
* Content: [Edge Server environmental requirements in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/edge-server-deployments/edge-environmental-requirements)
* Content Source: [Skype/SfbServer/plan-your-deployment/edge-server-deployments/edge-environmental-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/edge-server-deployments/edge-environmental-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by Petri-X** [comment]
Thank you for all !

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Petri-X  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
