### ISSUE TITLE
Screenshots and Group-Based Licensing

### ISSUE THREAD

**Issue by santos-haw** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9470]
The screenshots on this page do not match up with the current M365 admin portal. Also, it should be noted that when using group-based licensing in AAD, you cannot add and remove licenses through the M365 admin portal - "This is inherited by group-based licensing and can't be changed here. Manage group-based licenses in the Azure portal."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cccdd91a-7f05-abd5-ed94-e82152b86914
* Version Independent ID: 3532d0a8-119c-f7d0-0d4f-a865ad32570f
* Content: [Manage user access to Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/user-access)
* Content Source: [Teams/user-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/user-access.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by get-itips** [comment]
Thanks for your feedback!
