### ISSUE TITLE
Only applicable to Commercial Cloud

### ISSUE THREAD

**Issue by jhall-conp** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9471]
The purchase process only works for users with a Commercial Cloud tenant. I have yet to figure out how to obtain a license for GCC, neither Basic nor Pro.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b79d13d8-9f2e-ef35-0459-c3430e5b05a7
* Version Independent ID: b79d13d8-9f2e-ef35-0459-c3430e5b05a7
* Content: [Step 1 - Purchase a license for the Teams Rooms console - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/hybrid-meetings-device-config-license)
* Content Source: [Teams/hybrid-meetings-device-config-license.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hybrid-meetings-device-config-license.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @jhall-conp I am looking into this

**Comment by dstrome** [comment]
Please contact your Microsoft representative or partner about purchasing GCC licenses.

**Comment by jhall-conp** [comment]
> Please contact your Microsoft representative or partner about purchasing GCC licenses.

We spent several months trying to do just that, but they were never able to help. A few weeks ago we tried following the posted instructions again and it was available! It looks like the ability to purchase licenses in AAD was added to GCC recently.
