### ISSUE TITLE
Incorrect installation path for Teams MSI

### ISSUE THREAD

**Issue by dknappettmsft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9472]
The article states:

"This process installs Teams to the %ProgramFiles(x86)% folder on a 32-bit operating system and to the %ProgramFiles% folder on a 64-bit operating system. At this point, the golden image setup is complete."

This is the wrong way round as %ProgramFiles(x86)% only exists on a 64-bit operating system. Running the 64-bit installer installs to %ProgramFiles(x86)%:

![image](https://user-images.githubusercontent.com/49432665/200586388-bf4229e9-42c3-47b3-abf5-7bd7aa8c781f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-for-vdi#deploy-the-teams-desktop-app-to-the-vm)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello, I am handling this, thanks for your feedback
