### ISSUE TITLE
Teams hogging memory troubleshoot in documentation

### ISSUE THREAD

**Issue by FormindGMO** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9475]
Hi, it would be greatly appreciated if the webpage below of Teams memory consumption could contain tips to troubleshoot memory hogging by Teams. It indicates what is problematic memory but not how to treat it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc21902c-d522-3851-8587-177f01bc085c
* Version Independent ID: 590bcc64-a86d-b61e-7d94-4e4322c4e71d
* Content: [How Microsoft Teams uses memory - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-memory-usage-perf)
* Content Source: [Teams/teams-memory-usage-perf.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-memory-usage-perf.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @FormindGMO 
I asked and was instructed that Support services might be able to help provide this information, so please open a support request from your tenant to ask for this specific information.
Thank you

**Comment by FormindGMO** [comment]
Hello,

Well, if the page doesn't mention how to troubleshoot memory issues by teams, then the section to help knowing if teams induces memory issues is useless.

At least, add a mention " if you encounter memory problems using teams, please contact support" to end documentation user story.

Still it's could have been better to have troubleshoot tips after the section directly.
