### ISSUE TITLE
License naming

### ISSUE THREAD

**Issue by benzini00** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9480]
'Common Area Phone' license is now called 'Microsoft Teams Shared Devices'

Please update this documentation accordingly.

Many thanks, 

Ben

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4ab5215-f24f-75cf-bb92-16ac0ff5e5ca
* Version Independent ID: 701cc58f-d2ea-cbb6-f5fc-47b9fbfb1119
* Content: [Set up the Common Area Phone license - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/set-up-common-area-phones)
* Content Source: [Teams/set-up-common-area-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-common-area-phones.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@dariomws & @scanum This ask is going to require a number of other docs to be updated as well as they reference the previous name. Apparently, the license name change was supposed to happen in December, but some folks are seeing the rename in their purchasing channels already.

**Comment by DaniEASmith** [comment]
@dariomws & @scanum This issue is resolved with the PR https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/pull/10795, which is getting published today.
