### ISSUE TITLE
Documenting the correct way to connect outbound

### ISSUE THREAD

**Issue by J227668** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9481]
Hi - The documentation does not have the appropriate information to connect to outbound calling. Can you please update the document with guidance on how to enable outbound calling? I can share how we got this running if needed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: baeaf242-70a7-c9c2-1cf3-d66534768235
* Version Independent ID: 53d14d92-8827-72eb-5c7d-8533c37cd6d6
* Content: [Audio Conferencing with Direct Routing, GCCH and DoD - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/audio-conferencing-with-direct-routing-for-gcch-and-dod?source=docs)
* Content Source: [Teams/audio-conferencing-with-direct-routing-for-gcch-and-dod.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-with-direct-routing-for-gcch-and-dod.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by dariomws** [comment]
Hi @J227668, thank you for your feedback.

Could you provide more detail? Are you talking about "Step 4: Define a global voice routing policy to enable the routing of outbound calls from meetings"?

**Comment by scanum** [comment]
Hi @J227668 Hope all is well. Wanted to follow up here, could you please clarify the questions @dariomws is asking? Thanks.
