### ISSUE TITLE
The part of retention policy is not clear enough

### ISSUE THREAD

**Issue by GSaaaam** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9482]
[Enter feedback here]
The "Recording expiration settings and Microsoft 365 retention policies in Microsoft Purview" part is not clear enough for end users. It is saying when a Purview retention policy is taking place, the recording cannot be deleted, however, in fact the recording will be deleted but be kept in Preservation hold library. Even though it's not permanently deleted, from user's perspective, from the frontend, it's been deleted.

Please help to make it more clear for users. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee6d4c1c-6f16-b1a4-c4a9-be4e6d1f95b7
* Version Independent ID: 50ad835d-ed7f-18c6-34ba-322c1574f9c2
* Content: [Manage meeting policies for recording and transcription - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/meetings-policies-recording-and-transcription#default-expiration-time)
* Content Source: [Teams/meetings-policies-recording-and-transcription.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meetings-policies-recording-and-transcription.md)
* Service: **msteams**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by get-itips** [comment]
Hello @GSaaaam I am looking into this
