### ISSUE TITLE
Teams Meeting Delegation with Exchange On-Prem in GCCH

### ISSUE THREAD

**Issue by bradbrill** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9484]
I am a SEE that specializes in GCC-H. I have confirmed with the Product Group that Teams meeting delegation isn't supported for Exchange On-Prem in GCCH. Please contact me directly if you need any clarification or supporting ICMs that confirmed this detail.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by bradbrill** [comment]
Requesting that we document the limitation on this document.

**Comment by JoanneHendrickson** [comment]
Thanks Bill!  PR created; revision will publish live this afternoon.  Closing issue.
