### ISSUE TITLE
Remove "Teams Phone Standard license" from "Assign a license" section

### ISSUE THREAD

**Issue by shtakeda** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9485]
Please remove "Teams Phone Standard license" from "For each resource account, you must assign a Microsoft Teams Phone Resource Account license or Teams Phone Standard license." in "Assign a license" section.

According to this page, don't assign a Teams Phone Standard license to a resource account.
https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/virtual-user

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dce496a3-6ea7-e65d-6afa-7786a82fa26d
* Version Independent ID: 18f78dda-014b-a184-6b9b-81836037ceac
* Content: [Set up a Microsoft Teams Phone System resource account - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/business-voice/set-up-resource-account)
* Content Source: [Teams/business-voice/set-up-resource-account.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/business-voice/set-up-resource-account.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@shtakeda & @scanum I've made this update to date with this PR https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/pull/10681. It'll publish today (11/22/22)

**Comment by scanum** [comment]
Hi @DaniEASmith Thanks for the help with this issue. I get a 404 error when I try the Pull request link. Could you please confirm that this is the right link? I do see the documentation was updated. Appreciate your time and help.

**Comment by get-itips** [comment]
Document has been updated. Thanks
