### ISSUE TITLE
Purchase additional resource account licenses

### ISSUE THREAD

**Issue by shtakeda** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9486]
Please correct the followings in "Resource Account license allocation" section.
----------
 In the event more Teams Phone Resource Account licenses are required, you can purchase more Teams Phone Resource Account licenses beyond the standard allocation through your Microsoft account representative.
----------

Customer can purchase Teams Phone Resource Account license via EA, EAS, EES, CSP, and Web Direct channels. So, remove and revise "through your Microsoft account representative".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d6891495-01c6-117b-c28b-28232782ba74
* Version Independent ID: 1c23b35a-e9ba-ffdd-9baa-a3f83f4ed9ca
* Content: [Microsoft Teams Phone Resource Account licenses - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/virtual-user)
* Content Source: [Teams/teams-add-on-licensing/virtual-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/virtual-user.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by get-itips** [comment]
Hello @DaniEASmith can you kindly confirm? Thank you

**Comment by DaniEASmith** [comment]
@get-itips Full list of purchasing channels should be EA, EAS, EES, CSP, Web Direct, NCE – Customer led, and NCE – Partner led" because customers can use the New Customer Experience for getting additional Resource Account licenses.
