### ISSUE TITLE
Teams Phones alerts only for Pro licenses ?

### ISSUE THREAD

**Issue by sgrienen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9487]
The new licensing model in Teams forces to use Teams Rooms Pro license for Teams phones if you want to be able to use Device Alerts? Is my assumption correct ? It was not the case before.

Thanks !
Stéphane

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff254bd5-0d45-79c1-db9e-77768bbf1292
* Version Independent ID: ad980209-879d-5ca1-03b4-178cdc6e3548
* Content: [Microsoft Teams Monitoring and Alerting - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/alerts/teams-admin-alerts)
* Content Source: [Teams/alerts/teams-admin-alerts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/alerts/teams-admin-alerts.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @sgrienen I could get information that the UI in TAC will be updated to clarify. Thanks
