### ISSUE TITLE
PTZ cameras written out incorrectly

### ISSUE THREAD

**Issue by TJ-SH** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9488]
PTZ should be written out as "pan-tilt-zoom camera"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5d3a28c-7a66-831f-e610-9bf7d4edf9eb
* Version Independent ID: 0bc4a251-816e-0d77-efb2-53b7ffccb0f5
* Content: [Manage meeting policies for audio and video - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/meeting-policies-audio-and-video)
* Content Source: [Teams/meeting-policies-audio-and-video.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-audio-and-video.md)
* Service: **msteams**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by get-itips** [comment]
Thanks for your feedback
