### ISSUE TITLE
Version history

### ISSUE THREAD

**Issue by Deewood** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#949]
Displaying the version history would be helpful?
for example Skype for Business Basic 16.0.8229.2086 or Microsoft Skype for Business 2016 16.0.9126.2295

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49add74a-4227-b4ab-fc37-06332051c2a2
* Version Independent ID: 1950ce72-3ce6-cf35-6676-4f998b5c0998
* Content: [Version Support](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/srs2-lifecycle-support)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/srs2-lifecycle-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/srs2-lifecycle-support.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by get-itips** [comment]
Hi @Deewood thanks for your comments!
You can find version details for Skype Room System here https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/srs2-release-note 

Hope this information is useful for you. Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Deewood  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
