### ISSUE TITLE
The license has been updated to Teams Shared Device lisense

### ISSUE THREAD

**Issue by akrupennikov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9490]
In the last Ignite it has been written that Microsoft Teams Shared Device license should be seen.
It was expected to appear in December, but one of our customers already got it in the licensing portal.
If it has already been implemented, the naming in the document should be changed accordingly.

-->
Microsoft Teams Shared Device license: As the new way of working has expanded the usage, importance, and range of experiences that are conducted on shared devices expands, the Common Area Phone license has been updated to include support for hot desking and panels. This follows updates made to enable a more complete calling experience on a shared device, including adding call queue and auto attendant support, call park and retrieve, cloud voicemail, and group pickup. To reflect these expanded scenarios, the Common Area Phone license branding is now updated to the Microsoft Teams Shared Device license.

[**Teams Phone Mobile general availability and other Teams Phone announcements from Ignite 2022 - Microsoft Community Hub**](https://techcommunity.microsoft.com/t5/microsoft-teams-blog/teams-phone-mobile-general-availability-and-other-teams-phone/ba-p/3644284)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4ab5215-f24f-75cf-bb92-16ac0ff5e5ca
* Version Independent ID: 701cc58f-d2ea-cbb6-f5fc-47b9fbfb1119
* Content: [Set up the Common Area Phone license - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/set-up-common-area-phones)
* Content Source: [Teams/set-up-common-area-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-common-area-phones.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
We're already aware of this renaming and working toward a solution as soon as possible.

**Comment by akrupennikov** [comment]
@DaniEASmith thank you!
