### ISSUE TITLE
Backwards installer paths?

### ISSUE THREAD

**Issue by SchoolITPro** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9491]
[Enter feedback here]
Isn't this backwards? Program Files = 64-bit apps and Program Files (x86) = 32-bit apps

`The Teams MSI places an installer in %SystemDrive%\Program Files\Teams Installer on 32-bit Windows and %SystemDrive%\Program Files (x86)\Teams Installer on 64-bit Windows.`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Bulk install Teams using Windows Installer (MSI) - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @SchoolITPro, thank you for your feedback.

- On Windows 10 32 bits you only have %SystemDrive%\Program Files
- On Windows 10 64 bits or Windows 11 you have %SystemDrive%\Program Files and %SystemDrive%\Program Files (x86). It doesn't matter if you install Teams 32 or 64 bits, it will be installed on %SystemDrive%\Program Files (x86).

**Comment by scanum** [comment]
Hi @SchoolITPro Could you please confirm this answers your question? Thanks.

**Comment by SchoolITPro** [comment]
I understand the comment but the practice described doesn't seem correct either:
> It doesn't matter if you install Teams 32 or 64 bits, it will be installed on %SystemDrive%\Program Files (x86).

Microsoft (in my experience) has historically directed its users to install 64-bit applications in Program Files and 32-bit applications in Program Files (x86). To have a Microsoft application that ignores this guidance seems to be antithetical to the Microsoft ethos.

On a 64-bit operating system, 64-bit Teams should install in Program Files while 32-bit Teams should install to Program Files (x86); this would help keep the lines of (versioning) distinction clear when troubleshooting issues.

On 32-bit systems, you only have one standard or choice, so it would obviously be the one to use.

**Comment by dariomws** [comment]
Thanks again for your comment @SchoolITPro. Documentation reflects how the product currently works. I was about to update it by mistake, but a colleague helped me realize my mistake. No need to update the article.

I know the product teams are always looking for user feedback and how to make Microsoft products better. They keep a close tab on user feedback and it would be awesome if you could add your voice to the Microsoft Feedback Portal: https://feedbackportal.microsoft.com/feedback/. 

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request. 

Thank you for your contribution to making the docs better! Much appreciated!

**Comment by SchoolITPro** [comment]
How right you are that the documentation is the primary source of the application's current state, and that it shouldn't be updated until the application is changed.

Now that I have verified the documentation is accurate to the operation I will offer my feedback in the Portal :-).
