### ISSUE TITLE
Cross Cloud Anonymous Join in Teams desktop VDI currently is not supported.

### ISSUE THREAD

**Issue by pavelgogit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9498]
Cross Cloud Anonymous Join in Teams desktop VDI currently is not supported in GCC-High cloud. Can we have the following documentation updated with this known limitation? https://learn.microsoft.com/en-us/microsoftteams/teams-for-vdi

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-for-vdi)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @pavelgogit, thank you for your feedback.

Could you please confirm the version of Teams client deployed on your VDI environment?

@dstrome, could you confirm if this is supported?

**Comment by dariomws** [comment]
@pavelgogit, I tested it on my lab environment, and it works with the latest GCCH client version.

**Comment by pavelgogit** [comment]
@dariomws I asked my customer to update the GCCH client version to the latest. I will let you know. But, engineering from Product Group mentioned me that is currently unsupported in VDI for GCCH users.

**Comment by dariomws** [comment]
If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html 



Here is the site you can use to see the mappings between GitHub and Microsoft aliases: [https://repos.opensource.microsoft.com/people?q=pavelgogit]

**Comment by pavelgogit** [comment]
Thank you @dariomws. I'm currently signed up with my MSFT account: 
![image](https://user-images.githubusercontent.com/118470430/203593097-099585d0-bb6a-4c5b-bdfd-0fc0ab56aaa0.png)

**Comment by pavelgogit** [comment]
@dariomws Was your test in a VDI environment? With the latest GCCH client version doesn't work either. PG confirmed us that Cross Cloud Anonymous Join in Teams Desktop in a VDI environment is currently unsupported.

**Comment by scanum** [comment]
@dariomws
