### ISSUE TITLE
Automated translation

### ISSUE THREAD

**Issue by renatewi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#95]
1. The German Translation for the sentence "You're also going to need to install SQL Server Reporting Services for the Monitoring Server role, but we need you to know this isn't going to be supported with SQL Always on until post-RTM." is really bad and difficult to understand.
Should say: Sie müssen auch die SQL Server Reporting Services für die Monitoring Server-Role installieren, aber Sie müssen wissen, dass diese Aufgabe mit SQL Always On erst Post-RTM unterstützt sein wird. 
2. I am missing Information on the System Requirements for Monitoring Servers.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7c475b5d-09ed-7f58-86d4-27f28e33ef7a
* Version Independent ID: f0ad50f3-ea93-9424-6de8-a0b778e90b23
* Content: [Serveranforderungen für Skype for Business Server 2015](https://docs.microsoft.com/de-de/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/server-requirements#feedback)
* Content Source: [Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.de-DE/blob/live-sxs/Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md)
* Service: **unspecified**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by LolaJacobsen** [comment]
@samanthaw #1 goes to you.

**Comment by kenwith** [comment]
@renatewi - just a quick update.. I am tracking this down with the localization team so they can incorporate it into the translation memory so your feedback can be used other places in the doc translations too. Thanks for reporting!

**Comment by kenwith** [comment]
I talked with @samanthaw and she getting this resolved. Closing this one out. Thanks for reporting!
