### ISSUE TITLE
Per other doc and user experience, T-bot being removed

### ISSUE THREAD

**Issue by ljr55555** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#950]
Per [https://docs.microsoft.com/en-us/microsoftteams/get-help-in-microsoft-teams](https://docs.microsoft.com/en-us/microsoftteams/get-help-in-microsoft-teams) the T-Bot assistance is being replaced. The bot is currently returning a generic card to any queries. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c2d3788-a41c-a75a-757c-8fe582f7a75a
* Version Independent ID: 43a37c51-64bc-c109-ec4b-538f97f7f74f
* Content: [Use T-Bot to help users with Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/t-bot)
* Content Source: [Teams/T-Bot.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/T-Bot.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@ljr55555 Thank you for this feedback

I don't have any information on the T-bot being replaced. Let me get this over to the Teams/Skype for Business team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by ljr55555** [comment]
MC151037 on the message center, with the title "Updated Feature: Microsoft Teams Help Experience"

**Comment by kenwith** [comment]
This page was removed due to the update referenced above.
