### ISSUE TITLE
Needs some additions

### ISSUE THREAD

**Issue by HSteindl** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9503]
Hello!
a) Pls add info, that on MTR-Ws (Teams Rooms Systems on windows) the app name is not teams.exe!! So the powershell scripts to setup the QoS will not work.
b) Pls clarify how this relates to the settings of "insert QoS markings for real-time media traffic" in TAC = Teams Administration Center!
Do we need both on Windows? Many people asssume that if one uses the option in TAC one does not need the manual steps in this very article? Confusion....
thanks for consideration
HST 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76c2487c-044d-1349-708a-5841fcb21ab8
* Version Independent ID: b7033454-1a9c-48d4-8004-78415c5feb89
* Content: [Implement Quality of Service in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/qos-in-teams)
* Content Source: [Teams/QoS-in-Teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/QoS-in-Teams.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @HSteindl, thank you for your feedback.

a) I think you are talking about Microsoft.SkypeRoomSystem.exe. You must include Teams.exe but let me check if you also need to include Microsoft.SkypeRoomSystem.exe.

b) Short answer is both. Long answer: "Even if these settings had nothing directly to do with MTR, you still want to enable this setting. Enabling this tells Android, iOS, and MacOS Teams clients to tag all media with QoS markers. Unlike Windows, the Teams app on those platforms does the tagging, not the operating system. As you probably know, when enabling QoS, you need to enable it on all devices, not just the MTR."

@MikePlumleyMSFT, could you help me to confirm this information?

**Comment by dariomws** [comment]
@flinchbot, maybe you can also help here.

**Comment by HSteindl** [comment]
Hello!
Indeed I am referring to Microsoft.SkypeRoomSystem.exe.

Asking @flinchbot is never ever wrong! ;-)
HST

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
