### ISSUE TITLE
Clarify plans for Cmdlets not supported

### ISSUE THREAD

**Issue by Dan-Newton** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9504]
> Cmdlets Supported
> 
> All cmdlets are supported now, except for the cmdlets mentioned below.
> 
>     New-Team
>     **[Get|Set|New|Sync]-CsOnlineApplicationInstance**
>     *-CsUserCallingSettings
>     *-CsUserCallingDelegate
>     *PolicyPackage*
>     *-CsTeamsShiftsConnection*
>     *-CsBatchTeamsDeployment*

The page no longer mentions whether or not support for these cmdlets will be eventually rolled out. Please clarify if these cmdlets will eventually be supported or if they will always be unsupported, in particular [Get|Set|New|Sync]-CsOnlineApplicationInstance

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32304edf-550b-72a3-57df-6dcc29dba56d
* Version Independent ID: 32304edf-550b-72a3-57df-6dcc29dba56d
* Content: [Application-based authentication in Teams PowerShell Module - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-powershell-application-authentication)
* Content Source: [Teams/teams-powershell-application-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-application-authentication.md)
* Service: **msteams**
* GitHub Login: @pbafna03
* Microsoft Alias: **pbafna**

**Comment by pbafna03** [comment]
Hi @Dan-Newton, 

These will be gradually rolled out.
