### ISSUE TITLE
Disable the automatic Attendance Report message in chats

### ISSUE THREAD

**Issue by natakazakova** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9505]
In Teams, after every meeting I get these annoying messages in meetings chats:
![image](https://user-images.githubusercontent.com/17986517/203104716-a7c1f0eb-30d1-4ee0-ae3b-dd5981d05351.png)

Is there any way to disable those messages? If I want to get the attendances, I can see the list of them in a separate tab. It is more than enough. I want to keep the chat history clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a8b1087-ae40-6813-16bc-a69c90e50d19
* Version Independent ID: b808e843-80d8-4a96-c6ed-e8175968eb73
* Content: [Microsoft Teams meeting attendance report - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/meeting-attendance-report)
* Content Source: [Teams/teams-analytics-and-reports/meeting-attendance-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/meeting-attendance-report.md)
* Service: **msteams**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
