### ISSUE TITLE
Licensing exchange mailbox for Teams Room

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9506]
Can you please add information that Teams Rooms license covers also rights for the Exchange Online mailbox?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-licensing.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @Larryngolog 
I am a little confused, isn't that covered by room accounts licensing?

https://learn.microsoft.com/en-us/microsoft-365/admin/manage/room-and-equipment-mailboxes?view=o365-worldwide#does-a-room-mailbox-or-equipment-mailbox-need-a-product-license

**Comment by Larryngolog** [comment]
Hi! Thanks for your answer. Yes, you are right - I mixed up two things. The EXO license is not coming from the MTR license but it's coming from the room account type in EXO.

**Comment by get-itips** [comment]
@scanum
