### ISSUE TITLE
Public vs. shared channels

### ISSUE THREAD

**Issue by rafaelborter** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9507]
Statement: "Only public channels are supported." under Notes.
Can you please clarify this statement? According to several of my test's, shared channels are not supported. Shouldn't it say "standard channels"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b755d9ae-13ac-019f-f5f4-a95b1eee2989
* Version Independent ID: f7afd8ad-e6e0-6c79-aed1-4ee87d48ba12
* Content: [Create a call queue in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue?tabs=general-info)
* Content Source: [Teams/create-a-phone-system-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-call-queue.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by get-itips** [comment]
Thanks for your feedback!
