### ISSUE TITLE
The name of the license being used here must be updated since this license is not visible on tenant billing.

### ISSUE THREAD

**Issue by jabangas** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9508]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81fa6268-92b2-546f-9200-f323bb48e90e
* Version Independent ID: 6ce89bc0-ae69-b6f1-df50-532e46b2e67b
* Content: [Manage resource accounts in Teams - Microsoft Teams](https://review.learn.microsoft.com/en-us/microsoftteams/manage-resource-accounts#feedback)
* Content Source: [Teams/manage-resource-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-resource-accounts.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@jabangas After reviewing this doc, I don't see where we have an incorrect license name. We use the license name that appears in the Microsoft admin center, not what shows on invoices. In the Microsoft admin center, the license is called "Microsoft Teams Phone Resource Account."

**Comment by scanum** [comment]
Hi @jabangas Hope all is well. Could you please confirm this answers your questions?
