### ISSUE TITLE
Teams Templates for education

### ISSUE THREAD

**Issue by CraigChamberlain** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9509]
There is a template called EDU_Class which includes a class notebook.  It isn't listed on this page, nor can I find it when I run the PWSH ````Get-CsTeamTemplateList````.  However, it does seem to work if I use the ````-Template```` parameter of ````New-Team````.
E.g

`    New-Team -Template EDU_Class -DisplayName "Your New Team"`

The team template ID seems to look more like this: ````com.microsoft.teams.template.ManageAProject```` which is the form I think I need for the New-CsBatchTeamsDeployment command?

When I try to use the EDU_Class in the csv file it fails with the following error

`{"code":"BadRequest","message":"A template with id 'EDU_Class' and locale 'en-us' could not be found."}`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef94e9a3-a0a5-11da-f27b-627ac4fa6186
* Version Independent ID: e49db873-ed77-de53-e4dd-be4fc571d734
* Content: [Get started with team templates in the Teams admin center - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/get-started-with-teams-templates-in-the-admin-console)
* Content Source: [Teams/get-started-with-teams-templates-in-the-admin-console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-started-with-teams-templates-in-the-admin-console.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanachin**

**Comment by get-itips** [comment]
Hello @CraigChamberlain 
I tested this and

**Comment by CraigChamberlain** [comment]
Hi so you have confirmed that docs are acurate and EDU_Class may or may not be coming as a batch template.

If there are no plans to add it, where can I raise a feature request?

I think there may be some way of achieving some batching using the SDS api by uploading some files. My concern with that is there may ge some expectation for the files supplied to maintain current state not simply add teams adhock. I don't know where I can post questions about sds.

**Comment by CraigChamberlain** [comment]
Great thanks:

https://feedbackportal.microsoft.com/feedback/idea/d0a569bf-f47b-ed11-a81b-000d3ae32cd0

**Comment by get-itips** [comment]
Voted.
Closing for now. @scanum
