### ISSUE TITLE
Needing to be finished?

### ISSUE THREAD

**Issue by andibnz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#951]
I think this page may need some minor adjustments :) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d71ae1a0-6551-e8c9-6786-b65ddd7d11d1
* Version Independent ID: c615c8a7-d883-26ef-bf11-8ec6d098ddca
* Content: [Using PowerShell to manage Teams](https://docs.microsoft.com/en-us/microsoftteams/using-powershell-to-manage-teams/manage-features-with-powershell)
* Content Source: [Teams/using-powershell-to-manage-teams/manage-features-with-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/using-powershell-to-manage-teams/manage-features-with-powershell.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@andibnz Thank you for this feedback

What exactly needs to be adjusted?

**Comment by andibnz** [comment]
The page is not complete, it appears to be just filer content.

For example under meeting policies it just lists:
Cmdlet name | What it does | Link to the Get-Help PS cmdlet
________________________________

**Comment by AndreaBarr** [comment]
@andibnz Thank you for the clarification. I'll get this over to Teams/Skype for Business for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by LanaChin** [comment]
This page has been removed. Thanks for reporting this and bringing it to our attention.
