### ISSUE TITLE
Teams Exploratory Licenses are EOL/Sunset

### ISSUE THREAD

**Issue by fancyHeat** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9514]
I believe that the Teams Exploratory Licenses have been sunsetted. We cannot get them added to new tenant’s despite meeting all the requirements.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-exploratory)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by get-itips** [comment]
I've checked this with the PM and they are still available. I suggest you open a support request from your tenancy to understand what is happening in your specific case. Thank you

**Comment by scanum** [comment]
@TobiasAT 
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by TobiasAT** [comment]
As of April Teams Exploratory is part of Self-service purchases. This is the reason why the previous method no longer works. Read the latest update in the message center post MC527446:  https://admin.microsoft.com/#/MessageCenter/:/messages/MC527446

**Comment by TobiasAT** [comment]
In the meanwhile, Self-service purchases for Teams Exploratory is active and the process to enable the trial is working again. 

![image](https://user-images.githubusercontent.com/7470044/230767437-21c304c2-dca6-4890-aaf0-aeae72131e48.png)
