### ISSUE TITLE
Common Area Phone license is missing on tenants due to name change

### ISSUE THREAD

**Issue by ddaanniieell9** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9515]
This article details the steps to obtain a Common Area Phone License, however this license was renamed to Microsoft Teams Shared Devices. Customers are opening cases to obtain help getting the license as they search using the old name.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4ab5215-f24f-75cf-bb92-16ac0ff5e5ca
* Version Independent ID: 701cc58f-d2ea-cbb6-f5fc-47b9fbfb1119
* Content: [Set up the Common Area Phone license - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/set-up-common-area-phones)
* Content Source: [Teams/set-up-common-area-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-common-area-phones.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
Hey, @ddaanniieell9! We're aware of the name change and have the work slated for December to update all docs that mention the Common Area Phone license to read as the Microsoft Teams Shared Devices license.
