### ISSUE TITLE
Global Reader Role unable to export the report

### ISSUE THREAD

**Issue by GSaaaam** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9516]
[Enter feedback here]

Hi team,

As mentioned in the KB, "You must be either a global admin, global reader, or Teams service admin to view the reports in Teams admin center", I will be able to "read" the reports. There is no doubt about this. However, I am not able to "export" reports in Teams admin center with only Global Reader role. According to the test, I need to combine "Global Reader + Report Reader" roles to export the report.

The concern is, it is not clear what is the minimum role or role combination to Export the reports in TAC. 

Could you please help to share an update in this KB about what is the role required to export Teams reports?

Much appreciated for your works!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b138331-2f10-a05d-7e88-68e62e0b3e4f
* Version Independent ID: f923b648-ffe4-8a8a-c189-6e31f1032c10
* Content: [Microsoft Teams usage report - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-usage-report)
* Content Source: [Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by patrickpooon02** [comment]
To be exact, the breakdown area of the usage report will show "You don't have sufficient permission to view data for this report.", and trying to export to Excel will show the same error and no file is downloaded.

**Comment by get-itips** [comment]
Hello @patrickpooon02 
I tested this and I could verify that Global Reader alone is not enough to view/export the report.
I'll propose an update to the article.
Thanks
