### ISSUE TITLE
Steps are confusing

### ISSUE THREAD

**Issue by pgmaclean** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#952]
Article states, "After patching a Back End Server that is part of an AlwaysOn Availability Group, you must republish the topology."  Why do we have to republish the topology if there are no changes made to the topology?  Also why isn't there a "Step 3. Republish Topology"?  By running these steps,  Are both the primary and secondary database serversin the Always on Availability Group  updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c35b1bb6-8e84-1112-1d95-3d8afb887dd0
* Version Independent ID: 88b604fd-46f7-ab82-c6d3-4538568ab6c2
* Content: [Patch or update a SQL Server in an AlwaysOn Availability Group in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/manage/topology/patch-or-update-sql-server)
* Content Source: [Skype/SfbServer/manage/topology/patch-or-update-sql-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/topology/patch-or-update-sql-server.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment]
@pgmaclean Thank you for this feedback

I don't know the answers for this issue. I will get this over to the Teams/Skype for Business team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by kenwith** [comment]
@pgmaclean - The product team has stated to us that a restart is required. I am not positive on the reasoning why and was told to leave this in the article. I will keep this on my radar and will add information if I can. Thanks for the feedback.
