### ISSUE TITLE
Not just for dialin users

### ISSUE THREAD

**Issue by satish84** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9525]
The article here implies that this option is for only dial-in users to join without a leader (company user). This option also allows for desktop/web based anonymous users to start the meeting. This I believe should be called out, else it may lead to a privacy concern

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4521de2b-1aae-93de-ee1a-222146194700
* Version Independent ID: b4f9087c-e1a3-8b47-917c-7c294d46fcca
* Content: [Manage meeting policies for participants and guests - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/meeting-policies-participants-and-guests?source=docs#let-anonymous-people-start-a-meeting)
* Content Source: [Teams/meeting-policies-participants-and-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-participants-and-guests.md)
* Service: **msteams**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by get-itips** [comment]
Thanks for your feedback
