### ISSUE TITLE
include information for all options

### ISSUE THREAD

**Issue by lotekjunky** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9526]
The documentation has sections for "calling plans" and "operator connect" but doesn't have anything listed for "Direct Routing". I'm to assume the options are not available for Direct Routing? It should be stated as such because there is conflicting information throughout.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c3e921c-6601-c176-b177-74e30b8960f4
* Version Independent ID: b0d962c3-e102-1ec0-78dc-36e418be2f29
* Content: [Search for telephone numbers for users - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/search-for-phone-numbers-for-users)
* Content Source: [Teams/search-for-phone-numbers-for-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/search-for-phone-numbers-for-users.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
The article does state that it applies to Calling Plans, Operator Connect, and Teams Phone Mobile.  It then links to an article with more information about Direct Routing:  https://learn.microsoft.com/en-us/microsoftteams/manage-phone-numbers-landing-page.  This is by design.
