### ISSUE TITLE
Please add the template download link

### ISSUE THREAD

**Issue by annerajb** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#953]
Please add the template download link here instead of just the text?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb8d8b48-561b-6817-1ce0-4b2aedc261a8
* Version Independent ID: dfd5cf4a-509a-3ed1-0267-6281c251fbef
* Content: [Turning on and using Call Quality Dashboard](https://docs.microsoft.com/en-US/microsoftteams/turning-on-and-using-call-quality-dashboard?WT.mc_id=TeamsAdminCenterCSH#BKMKTenantDataFile)
* Content Source: [Teams/turning-on-and-using-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/turning-on-and-using-call-quality-dashboard.md)
* Service: **skype-for-business-online**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by popibul** [comment]
the link is here: https://docs.microsoft.com/en-US/microsoftteams/learn-more-about-site-upload?WT.mc_id=TeamsAdminCenterCSH

**Comment by annerajb** [comment]
thanks!
