### ISSUE TITLE
Screen shots out of date

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9530]
The screen shots on this page don't reflect the options shown in the product any more and all need to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0c70e2a-c370-01ae-c46a-3a1d0b95fd61
* Version Independent ID: a3d2b15f-8900-491a-c71a-ab16db108376
* Content: [Place a Microsoft Teams user or team on legal hold - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/legal-hold)
* Content Source: [Teams/legal-hold.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/legal-hold.md)
* Service: **msteams**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by get-itips** [comment]
Thanks for your feedback!
