### ISSUE TITLE
FireFox support greatly expanded

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9531]
I don't think many of these limitations apply to FireFox any more. The April and October updates added all the basic features, including audio and screen sharing.

https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=firefox

Can this article get reviewed/updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 99361a9a-edf3-c477-9bba-82a1462d60d8
* Version Independent ID: 407bf24e-e7a0-f2e7-d80f-ea609f80a040
* Content: [Microsoft Teams meetings on unsupported browsers - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/unsupported-browsers)
* Content Source: [Teams/unsupported-browsers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/unsupported-browsers.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @npherson, thank you for your feedback.

I'm trying to push these updates from last year. Could you try to boost them by contacting the product team?

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/9222
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/8791
