### ISSUE TITLE
Firefox support greatly expanded

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9532]
I don't think many of these limitations apply to FireFox any more. The April and October updates added all the basic features, including audio and screen sharing.

https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=firefox

Can the FireFox section get reviewed/updated?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c86f401-cff4-93b3-ff69-b9787a87e644
* Version Independent ID: c0808bd3-cf63-0625-4c3c-65469c26fb3e
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/get-clients?tabs=Windows)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Same as https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9531.

**Comment by npherson** [comment]
@dariomws - same need, different page.
