### ISSUE TITLE
"Microsoft Teams Rooms help" link not working

### ISSUE THREAD

**Issue by rito2k** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9533]
In the TESTING section, the link [Microsoft Teams Rooms help](https://support.microsoft.com/en-us/office/microsoft-teams-rooms-help-e667f40e-5aab-40c1-bd68-611fe0002ba2?ui=en-us&rs=en-us&ad=us) is not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 99951587-c6ee-feb3-ab39-8d6b6969e939
* Version Independent ID: 1cb9d2e6-d4c1-628a-79bf-6ae405263f1d
* Content: [Deploy Microsoft Teams Rooms - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-deploy)
* Content Source: [Teams/rooms/rooms-deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-deploy.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
