### ISSUE TITLE
Nothing about Mobile limitations?

### ISSUE THREAD

**Issue by rmccondach** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9534]
Aside from one mention of Android/iOS on the page, can this be updated to state whether or not the limitations apply to mobile apps, or the mobile apps have different limitations?

For example, no mobile browsers work/are supported with Teams Mobile (including Chrome, which is listed as supported here).

I imagine there may be different filesize limits of PPTX and other documents sent over Teams due to the smaller amount of RAM available on mobile devices vs. desktops.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by dariomws** [comment]
Hi @rmccondach, thank you for your feedback.

I'll forward your request to the correct team.

@dstrome, FYI.
