### ISSUE TITLE
Connect-MicrosoftTeams Application based auth: Tenant Domain is empty

### ISSUE THREAD

**Issue by visch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9536]
When following the docs for Application based access tokens here https://learn.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps#example-5-connect-to-microsoftteams-using-application-based-access-tokens

And running the code

```
$ClientSecret   = "secret"
$ApplicationID = "appid"
$TenantID = "tennantid"

$graphtokenBody = @{
   Grant_Type    = "client_credentials"
   Scope         = "https://graph.microsoft.com/.default"
   Client_Id     = $ApplicationID
   Client_Secret = $ClientSecret
}

$graphToken = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$TenantID/oauth2/v2.0/token" -Method POST -Body $graphtokenBody | Select-Object -ExpandProperty Access_Token

$teamstokenBody = @{
   Grant_Type    = "client_credentials"
   Scope         = "48ac35b8-9aa8-4d74-927d-1f4a14a0b239/.default"
   Client_Id     = $ApplicationID
   Client_Secret = $ClientSecret
}

$teamsToken = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$TenantID/oauth2/v2.0/token" -Method POST -Body $teamstokenBody | Select-Object -ExpandProperty Access_Token

Connect-MicrosoftTeams -AccessTokens @("$graphToken", "$teamsToken")
Get-CsOnlineDialInConferencingTenantSettings
```

You recieve
```
Get-CsOnlineDialInConferencingTenantSettings: /home/visch/git/***/test_token.ps1:24                   
Get-CsOnlineDialInConferencingTenantSettings
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Tenant Domain is empty 
```

```
PS E:\code\teams> Get-Module MicrosoftTeams

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     4.9.1                 MicrosoftTeams                      {Add-TeamChannelUser, Add-TeamUser, Connect-Micro…

```
Version 4.9.1

The connect-microsoftteams portion of the script seems to work fine, just the other cmdlets do not.

**Comment by get-itips** [comment]
@pbafna03 Is that cmdlet supported for app-based auth? Thanks

**Comment by pbafna03** [comment]
Hi @visch & @get-itips - looking at the error above, it appears that the relevant AAD Admin Roles are not assigned to the app. Ref - https://learn.microsoft.com/en-us/microsoftteams/using-admin-roles#teams-roles-and-capabilities

**Comment by visch** [comment]
Granting the `Teams Administrator`  Role to the Application Service Principal worked!

Also since I was running on Linux I hit a seperate issue of `symbol lookup error: /opt/microsoft/powershell/7-lts/libmi.so: undefined symbol: SSL_library_init` which I fixed by installing PSWSMan by running

```
Install-Module -Name PSWSMan -Scope AllUsers
Install-WSMan 
```

re https://github.com/PowerShell/PowerShell/issues/12202 


Thank you!
