### ISSUE TITLE
GCC and GCCH links point at commercial resources

### ISSUE THREAD

**Issue by James-Lester** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9538]
For example, the Permission Policies link at "[For GCCH and DoD clouds](https://learn.microsoft.com/en-us/microsoftteams/manage-apps#for-gcch-and-dod-clouds)" points at https://admin.teams.microsoft.com/policies/app-permission instead of the corresponding government cloud endpoint. Attempting to log-in to the commercial link returns this error message: "Internal calls to PLS Service have failed. We can't find the tenant region for [redacted]. Please try again later."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fbbcabee-fa96-2878-e983-3c966f84ee15
* Version Independent ID: 02fa4fd8-77e0-5cb2-a4af-576cbb68322f
* Content: [Manage your apps in the Microsoft Teams admin center - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-apps)
* Content Source: [Teams/manage-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-apps.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by get-itips** [comment]
Hello @James-Lester I am looking into this

**Comment by ashishguptaiitb** [comment]
Hi @get-itips  and @James-Lester , I've updated the doc to remove the link for now.

**Comment by get-itips** [comment]
@scanum
