### ISSUE TITLE
Cloud Call Queue Agent Timeline internal calls not accurate

### ISSUE THREAD

**Issue by ntoryus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9540]
Cloud Call Queue Agent Timeline does not show accurate calls when the calls are an internal transfer. This looks like a known issue, but I am curious if there is an ETA on it getting fixed? Thanks!
![image](https://user-images.githubusercontent.com/119690897/205340585-b8a1cf06-577d-4b85-b7c5-151b06296416.png)
![image](https://user-images.githubusercontent.com/119690897/205340789-11c75a59-ac77-4491-bb63-dd676739cac7.png)

**Comment by CLYVR** [comment]
@ntoryus Which version of the Power BI template are you using?

**Comment by ntoryus** [comment]
I am using 3.04

**Comment by CLYVR** [comment]
@ntoryus Would you be able to attach some screenshots of the underlying data in the fCallQueueAnayltics, fCallQueueFinalStateAction and fAgentTimelineAnalytics tables?  That would be appreciated.  Alternatively, happy to have a live call with you so I can review this information - I would need your contact info (email address) and the time zone you're in so a meeting could be scheduled.

**Comment by ntoryus** [comment]
my contact info is salvatore.sella@rsmus.com and I am in PST.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
