### ISSUE TITLE
Permissions to access Voice Applications Analytics Collector

### ISSUE THREAD

**Issue by BlackC0ffee** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9542]
Hi

The document does not mention the minimum requirements to access the data from the Voice Applications Analytics Collector (VAAC). In the past we used the Reports Reader-role, but it looks like this is no longer enough and you need to have the Teams Administrator role active. Could you confirm and update the documentation for the 3.x.x prerequisites

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 628345c6-f5f9-fe8e-bfff-faea00a8a25c
* Version Independent ID: 30f2d051-5af5-0063-7099-38b5b08ec1e4
* Content: [Updated auto attendant and call queue historical reports - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/aa-cq-cqd-historical-reports)
* Content Source: [Teams/aa-cq-cqd-historical-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/aa-cq-cqd-historical-reports.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by get-itips** [comment]
Hello @BlackC0ffee 
It seems that, at minimum, Teams Communications Administrator is required to access the report without errors.
I'll check if an update is required. Thanks

**Comment by CLYVR** [comment]
Hi @get-itips I'm looking into this.  Any role that includes CQD access should work but I just tried Global Reader myself and it didn't.  I've brought this up with the team to look into.  Will let you know.

**Comment by CLYVR** [comment]
@get-itips Confirmed, this is a bug.  Global Reader should work.  This will be addressed after the freeze ends in January.

**Comment by get-itips** [comment]
Thanks @CLYVR !

**Comment by CLYVR** [comment]
@get-itips Global reader role is now working.
