### ISSUE TITLE
Name change license

### ISSUE THREAD

**Issue by BurgerhoutJ** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9544]
Hi,

The Common Area Phone license has been renamed to Microsoft Teams Shared Devices. Can you please change this in the article? It's confusing for the reader, I think.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4ab5215-f24f-75cf-bb92-16ac0ff5e5ca
* Version Independent ID: 701cc58f-d2ea-cbb6-f5fc-47b9fbfb1119
* Content: [Set up the Common Area Phone license - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/set-up-common-area-phones)
* Content Source: [Teams/set-up-common-area-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-common-area-phones.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
Hi, @BurgerhoutJ, we are already in the process of updating all of our docs to reflect the license name change.

**Comment by BurgerhoutJ** [comment]
Hi @DaniEASmith, That's good news that you are already changing the names in the docs. I will close this issue.
