### ISSUE TITLE
Non-working link for "user help FAQ" leads to 404 error

### ISSUE THREAD

**Issue by rito2k** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9545]
The link in the "Plan for operations" section for "FAQ is the user help" pointing to (https://support.microsoft.com/office/microsoft-teams-rooms-help-e667f40e-5aab-40c1-bd68-611fe0002ba2) leads to a non-existing page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c25c286-2a25-19d1-6847-f2324b3deb73
* Version Independent ID: 0c82ef28-f9c8-1845-c167-ce2756478d9c
* Content: [Plan for Microsoft Teams Rooms - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-plan)
* Content Source: [Teams/rooms/rooms-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-plan.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by rito2k** [comment]
Hi @scanum, sorry but I can't follow on your recommendation. There is a non-working link to a user FAQ in one of our general Teams articles, and I asked to update/correct it. 
I'm an FTE, so I'm not sure which tenant you exactly mean. How will opening a support ticket on a specific tenant going to help correcting a link for the general audience?

**Comment by get-itips** [comment]
@rito2k The en-us version of the link is giving 404, probably removed, other languages of the same article exist.
I'll try to dig into this if a replacement resource will be provided.

**Comment by rito2k** [comment]
If it helps, there is a copy here: https://web.archive.org/web/20220329173758/https://support.microsoft.com/en-us/topic/e667f40e-5aab-40c1-bd68-611fe0002ba2
