### ISSUE TITLE
Needs updating with latest Teams Room Shared Device license instead on Common Area Phone

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9546]
Hi, This page needs updating with latest Teams Room Shared Device license instead on Common Area Phone. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4ab5215-f24f-75cf-bb92-16ac0ff5e5ca
* Version Independent ID: 701cc58f-d2ea-cbb6-f5fc-47b9fbfb1119
* Content: [Set up the Common Area Phone license - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/set-up-common-area-phones?source=docs)
* Content Source: [Teams/set-up-common-area-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-common-area-phones.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@SvenBell We're already in the process of updating all our docs to reflect the license name change. The updated docs should be published in the next week or so.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
