### ISSUE TITLE
X50 & X30 supported firmware

### ISSUE THREAD

**Issue by joelulrich** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9547]
Poly Studio X50 & Poly Studio X30 4.0.0.100885 Firmware is not available via TAC, 3.14.1.374010 is the latest version that is offered.
What is the current latest Microsoft supported firmware?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aaaef9e1-8f1c-ebf0-7856-4c007342a2c3
* Version Independent ID: 3eaf671f-375e-8787-9c66-3947c3606559
* Content: [Devices for Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/devices/teams-ip-phones)
* Content Source: [Teams/devices/teams-ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/teams-ip-phones.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @joelulrich, thank you for your feedback.

I understand that the versions listed in the article are the latest Microsoft supported firmware. 4.0.0.100885 should be available in the TAC soon.
