### ISSUE TITLE
Clarify IB known issue section

### ISSUE THREAD

**Issue by ckordel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9548]
Cx is asking for a more clear statement regarding this part:

Known Issues
Users can't join ad-hoc meetings: If IB policies are enabled, users aren't allowed to join meetings if the size of the meeting roster is greater than the [meeting attendance limits](https://learn.microsoft.com/en-us/MicrosoftTeams/limits-specifications-teams). The root cause is that IB checks rely on whether users can be added to a meeting chat roster, and only when they can be added to the roster are they allowed to join the meeting.

It can be read as if a) the meeting limit (1000) or b) the groupchat limit (250) is the problematic part. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85a288bc-9192-8c65-4ce9-b5abb260206e
* Version Independent ID: 1f953ea6-e6e5-5e71-d541-3962637f25f9
* Content: [Information barriers in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/information-barriers-in-teams#known-issues)
* Content Source: [Teams/information-barriers-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/information-barriers-in-teams.md)
* Service: **msteams**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by dariomws** [comment]
Hi @ckordel, thank you for your feedback.

The article talks about **meeting attendance limits**, not group chat. I'm not sure how to provide more clarity, since that bullet is always talking about meetings, not group chat. But I'm open to ideas or more feedback if you still think the article requires improvement.

**Comment by ckordel** [comment]
Thx for the feedback. I think the confusion comes from the part where its stated that the active part of the meeting relies on the ability to add the user to the underlying group chat of the meeting. 

Maybe just a sentence stating that is not directly related to the limit of a regular group chats is enough.
