### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by DPIZee** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9549]
Using ICD version 2022.1118.0.0 downloaded from the Microsoft Store this morning.

* Use Windows Configuration Designer -> Step 3: On the next screen, there is no "WindowsTeamSettings" to choose. It appears the current version of ICD is configured this way by remaining in "simple" mode, and selecting "Add a Teams configuration file."
* Use Windows Configuration Designer -> Step 4: Instructions direct to "paste the single line of XML you created above," however the example provided wasn't a single line. Suggest changing wording to "....paste the XML file you created above" to avoid confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a6056049-5981-858a-a82b-9e814181cfe6
* Version Independent ID: 0719e1ec-e9b4-0004-030b-f8158e2898a6
* Content: [Manage Microsoft Teams configuration on Surface Hub - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/surface-hub-manage-config)
* Content Source: [Teams/rooms/surface-hub-manage-config.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/surface-hub-manage-config.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
