### ISSUE TITLE
Remove the RestrictedAnonymousAccess Teams meeting policy from users - invalid CMDlets

### ISSUE THREAD

**Issue by bastienperez** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9552]
`ObjectId` does not exist (at least with latest Microsoft Teams PowerShell Module 4.9.1) so we need to use `UserPrincipalName`.

`TeamsMeetingPolicy` is not a property, it's an `System.Object` with two properties `Authority` and `Name`.

Valid CMDlets are:
```powershell
Get-CsOnlineUser | Where-Object {$_.TeamsMeetingPolicy.Name -eq "RestrictedAnonymousAccess"} | ForEach-Object {Grant-CsTeamsMeetingPolicy -Identity $_.UserPrincipalName -PolicyName $null}
```
```powershell
$restrictedAnonymousUsers = @(Get-CsOnlineUser | Where-Object {$_.TeamsMeetingPolicy.Name -eq "RestrictedAnonymousAccess"} | ForEach-Object { $_.UserPrincipalName })
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a55f6ae5-c345-452e-ccdc-0debc3c02dbd
* Version Independent ID: 8625a20c-852c-c2f1-a708-0c2926c8dc9c
* Content: [Remove the RestrictedAnonymousAccess Teams meeting policy from users - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/meeting-policies-restricted-anonymous-access)
* Content Source: [Teams/meeting-policies-restricted-anonymous-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-restricted-anonymous-access.md)
* Service: **msteams**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by BlackC0ffee** [comment]
I can confirm this bug and used following commands to perform the correct actions:
`Get-CsOnlineUser -Filter "TeamsMeetingPolicy -eq 'RestrictedAnonymousAccess'"| Select Identity, DisplayName, TeamsMeetingPolicy | foreach {Grant-CsTeamsMeetingPolicy -Identity $_.Identity -PolicyName $null}`

**Comment by MikePlumleyMSFT** [comment]
Article has been retired.
