### ISSUE TITLE
Non-Native Chat for Cross Cloud Federation

### ISSUE THREAD

**Issue by bradbrill** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9555]
Please include the caveat in this article that cross cloud, for example GCC-High to Commercial is non-native federation. This article states that Teams only to teams only will always be native, but when users are in different clouds, it will use non-native federation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ac8f101-bdb5-2b55-d5f4-e070b70768d4
* Version Independent ID: 964d836e-d00b-b585-8f02-e03c5ec8dab9
* Content: [Native chat experience for external (federated) users in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/native-chat-for-external-users)
* Content Source: [Teams/native-chat-for-external-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/native-chat-for-external-users.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @bradbrill, thank you for your feedback.

@MikePlumleyMSFT, could you help to confirm this information? Between government clouds and commercial, and what about between different government clouds like GCC and Dod? Thanks!

**Comment by bradbrill** [comment]
@dariomws Yes, it applies to other clouds. DoD, GCCH, and WW (GCC is considered part of WW)

**Comment by dariomws** [comment]
@bradbrill,

If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html 


Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=bradbrill

**Comment by bradbrill** [comment]
@dariomws Thank you. I think I am now linked.
