### ISSUE TITLE
Teams Live Event Report for Govt/DoD

### ISSUE THREAD

**Issue by raul8a07** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9556]
The option for Teams Live Event usage report isn't available to govt/DoD customers. Is this something that will be available in the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d5372edb-6ffe-34a3-0839-587e48f66f6b
* Version Independent ID: 43903b13-37de-7dde-5b8c-739586cc2d87
* Content: [Microsoft Teams live event usage report - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-live-event-usage-report)
* Content Source: [Teams/teams-analytics-and-reports/teams-live-event-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-live-event-usage-report.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
