### ISSUE TITLE
Update gwmi / wmi to Get-CimInstance

### ISSUE THREAD

**Issue by mmatijas** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9558]
Hi,

The example scripts need to be updated. gwmi & wmi are no longer supported :-)
Thanks

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd52fe62-457b-c9e1-ad13-a9b1f24c9c38
* Version Independent ID: 6a8c3285-30e1-15a8-6472-f0cfe5b30e20
* Content: [Microsoft Teams Rooms maintenance and operations - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-operations#configuring-group-policy-for-microsoft-teams-rooms)
* Content Source: [Teams/rooms/rooms-operations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-operations.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @mmatijas, thank you for your feedback.

Could you share your source of information? I understand that 
"The WMIC tool is deprecated in Windows 10, version 21H1 and the 21H1 General Availability Channel release of Windows Server. This tool is superseded by [Windows PowerShell for WMI](https://learn.microsoft.com/en-us/powershell/scripting/learn/ps101/07-working-with-wmi)."

Get-WmiObject is still supported.

**Comment by mmatijas** [comment]
When I used these commands in PowerShell version 7, they don’t work. When I had a look on the internet, it was mentioned that there was an issue with certificates. So not sure if it is me or if there is something going on.

Regards,
Mladen Matijas

M: +33 6 86270472
E: ***@***.*** ***@***.***>

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
