### ISSUE TITLE
MediaRelayRoutingLocationOverride

### ISSUE THREAD

**Issue by jgre333** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9559]
In the SBC settings table, is the description for **MediaRelayRoutingLocationOverride** accurate? It states this is not applicable for Direct Routing and the default value is None. Though the default value is Auto, and the article below outlines how this setting is used with direct routing, which differs from the current description on this page.

https://learn.microsoft.com/en-us/microsoftteams/direct-routing-country-codes

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad7d5051-1177-c5cf-bf28-8639d7b6fbd1
* Version Independent ID: 2a9aa4e1-3767-cd46-50fe-f9dd8b0997be
* Content: [Connect your Session Border Controller (SBC) to Direct Routing - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/direct-routing-connect-the-sbc)
* Content Source: [Teams/direct-routing-connect-the-sbc.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-connect-the-sbc.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @jgre333, thank you for your feedback.

Both articles have the same comment:

https://learn.microsoft.com/microsoftteams/direct-routing-country-codes
"MediaRelayRoutingLocationOverride parameter is reserved for use with managed carriers"

https://learn.microsoft.com/microsoftteams/direct-routing-connect-the-sbc
"This parameter is reserved for use with managed carriers in Calling Plans"
