### ISSUE TITLE
Spreedsheet not updated with the latest country list e.g. Mexico

### ISSUE THREAD

**Issue by dipinn26592** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9561]
Spreadsheet not updated with the latest country list e.g. Mexico

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b07cfcf-8f31-91ed-b1de-c7826a1ab91d
* Version Independent ID: dfbc4212-8f47-326a-f872-8186a915ae1e
* Content: [Country/region availability - Audio Conferencing, Calling Plans - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans?source=docs)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by dariomws** [comment]
Hi @dipinn26592, thank you for your feedback.

The spreadsheet now includes Mexico in the Calling Plans Purchase sheet.

**Comment by dipinn26592** [comment]
Thank you, could please also validate if the spreadsheet is the latest. And apart from Mexico if we are missing any other region.

Regards,
Dipin Nair

**Comment by dariomws** [comment]
The spreadsheet is always updated to include the latest updates. Maybe it could take a few days after the launch of the new service, but it will be up to date.
