### ISSUE TITLE
known issues - Users can't join ad-hoc meetings

### ISSUE THREAD

**Issue by sunbansal** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9562]
[Enter feedback here]

In the known issues section - Users can't join **ad-hoc** meetings

In the heading it says ad-hoc meetings has known issue but, in the description, it has mentioned that it's for all meeting type like recurring etc. 

"A user joining a meeting once adds that user to the roster; hence for recurring meetings, the roster can fill up fast."

Based on working with engineering - ICM - 348337795, there were recurring meetings which were impacted due to IB policy.

Request you to change the heading so it will be more understandable by customers. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85a288bc-9192-8c65-4ce9-b5abb260206e
* Version Independent ID: 1f953ea6-e6e5-5e71-d541-3962637f25f9
* Content: [Information barriers in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/information-barriers-in-teams)
* Content Source: [Teams/information-barriers-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/information-barriers-in-teams.md)
* Service: **msteams**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by get-itips** [comment]
Hello @sunbansal how are you?
Unfortunately, we don't have access to the case you mention.
Doing some investigation on the article, the "ad-hoc" word was added later the "recurrent", however, I can understand that can be still a known issue, will try to confirm.
Thanks

**Comment by get-itips** [comment]
Feedback was sent to and received by Docs team.

@scanum closing
