### ISSUE TITLE
CAP license changed into "Microsoft Teams Shared Devices"

### ISSUE THREAD

**Issue by Emsabare** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9567]
["CAP license" has been changed to "Microsoft Teams Shared Devices". If you look for it in "purchase services" in admin portal, you will not find it anymore ]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4ab5215-f24f-75cf-bb92-16ac0ff5e5ca
* Version Independent ID: 701cc58f-d2ea-cbb6-f5fc-47b9fbfb1119
* Content: [Set up the Common Area Phone license - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/set-up-common-area-phones)
* Content Source: [Teams/set-up-common-area-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-common-area-phones.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@Emsabare We are currently updating all docs that reference this license name. There are many docs that need to be updated, but they will published this week.
