### ISSUE TITLE
The pricing links don't have pricing

### ISSUE THREAD

**Issue by mrbuckingham** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#957]
You pricing links go sites for teams that give pricing general Office 365 subscriptions but not the Audio Conferencing add in. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dc121be-72fc-e1c7-628b-b0b293520be2
* Version Independent ID: 678ed844-653d-6ad3-c0f4-341b2f56de9d
* Content: [Audio Conferencing in Office 365](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-in-office-365#feedback)
* Content Source: [Teams/audio-conferencing-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-in-office-365.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@mrbuckingham Thank you for pointing this out to us
I will get the information for this link issue to the Teams/Skype for Business team for investigation.
The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.
I made a note to request the team to update this when the work is complete.

**Comment by michaelwda** [comment]
Part of the way down the page there is blurb about pricing. From what I can tell it's going to be $4/mo for a single add-on license to our O365 E3. That license then needs to be applied to the user who will be creating and hosting the meetings. 

This add-on can be purchased through the O365 Admin Center.

**Comment by scanum** [comment]
@mrbuckingham  We appreciate any feedback that improves the content in the Microsoft docs, since the issue seems to have been resolved and we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
