### ISSUE TITLE
Missing link to licensing doc

### ISSUE THREAD

**Issue by coachsmitty** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9572]
In the Webinar section https://learn.microsoft.com/en-us/microsoftteams/quick-start-meetings-live-events#webinars, there is a placeholder where the link to the licensing doc should be. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 92fcb1f6-5cc2-f6bd-cfa9-11d811f1dbf1
* Version Independent ID: 9a571e6d-8cb3-9ff8-a5c2-62deab146264
* Content: [Meetings, webinars, and live events - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/quick-start-meetings-live-events#meetings)
* Content Source: [Teams/quick-start-meetings-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/quick-start-meetings-live-events.md)
* Service: **msteams**
* Sub-service: **meetings**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
This was fixed.
