### ISSUE TITLE
missing Teams Rooms app update versions

### ISSUE THREAD

**Issue by lberlau** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9576]
Hi Team, 

would be nice with this site being updated to latest Teams Rooms app version: 

https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-release-note#version-history

/Lars Berlau 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7ecd6ee6-8850-f346-5684-9c5d2444789f
* Version Independent ID: a55a7a01-211d-147a-5332-b68e1051a2a1
* Content: [Microsoft Teams Rooms app version support - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-lifecycle-support)
* Content Source: [Teams/rooms/rooms-lifecycle-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-lifecycle-support.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @lberlau, thank you for your feedback.

The article says "Microsoft Teams Rooms Minimum application version". It's the minimum version, not the latest one.
