### ISSUE TITLE
Include port for IPs and URLs

### ISSUE THREAD

**Issue by jagonzal01** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9577]
Hi team,

Into the first section "Configure SIP Gateway" I think it would be a good idea to include the port and protocol for IP addresses and URLs, something like:
Open TCP port 443 for the following IP addresses and URLs:
13.75.175.145
52.189.219.201
51.124.34.164
13.74.250.91
13.83.55.36
23.96.103.40
https://blobsdgapac.blob.core.windows.net/
https://blobsdgemea.blob.core.windows.net/
https://blobsdgnoam.blob.core.windows.net/
https://httpblobsdgapac.blob.core.windows.net/
https://httpblobsdgemea.blob.core.windows.net/
https://httpblobsdgnoam.blob.core.windows.net/

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 05173ea8-db7c-a20d-3783-178b3d649190
* Version Independent ID: 05173ea8-db7c-a20d-3783-178b3d649190
* Content: [Configure SIP Gateway - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/sip-gateway-configure?source=docs)
* Content Source: [Teams/sip-gateway-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sip-gateway-configure.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @jagonzal01, thank you for your feedback.

Since the article says "Open the following **https** endpoints", I think it's clear that it's TCP 443. If more people complain about that sentence, I think we can update it.

**Comment by jagonzal01** [comment]
Hi @dariomws , I already have a couple of customers who has asked me about this question, the point is that in the article the previous IP ranges indicate the specific ports and protocol, while for the https endpoints we don't have this information, which is confusing for them, also many people associate https to URLs but not IPs. On top of that, the protocol https normally goes over TCP 443, but can be also TCP 8443 or even any other port, so to avoid any confusion I think it would be better to include in the sentence "Open TCP port 443 for the following https endpoints". Thanks!
