### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9578]
The link in  the Additional resources section does not work

[Microsoft Teams Premium product site](https://www.microsoft.com/microsoft-teams/premium)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a5338e6-ae08-bb92-3769-4af2932bf02c
* Version Independent ID: 7a5338e6-ae08-bb92-3769-4af2932bf02c
* Content: [Microsoft Teams Premium - Overview for administrators - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/enhanced-teams-experience)
* Content Source: [Teams/enhanced-teams-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enhanced-teams-experience.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
That link is working for me and for others.  Please try again...

**Comment by nikki-c** [comment]
I get this error message  when I select the Microsoft Teams Premium product site link which goes to this URL https://www.microsoft.com/en-gb/microsoft-teams/premium?rtc=1
![image](https://user-images.githubusercontent.com/69439002/207971567-7cc901b2-7bf5-4467-ab28-53fdb1776f27.png)

**Comment by nikki-c** [comment]
I am getting the error on Edge and Google and mobile devices using different internet and mobile providers
