### ISSUE TITLE
No info

### ISSUE THREAD

**Issue by Rashantha** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#958]
This article just led me in a circle. Clicked the link from one page and ended up 2 pages at the same location with no value. Just marketing.

**Comment by AndreaBarr** [comment]
@Rashantha What article was it that had this issue? You opened an issue directly in the repo so we can't see what article you are referring to.

**Comment by yogkumgit** [comment]
@AndreaBarr  Thank you very much for the contribution. @Rashantha  Hope to log future issues with complete information. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
