### ISSUE TITLE
Updates App no Admin Docs

### ISSUE THREAD

**Issue by Torxsmind** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9582]
This page needs information for Administrators.  I.E.  How to do a admin deletes of a "Update" from a expired employee.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c19d4972-fa39-2908-c33c-f7e1a84d06c5
* Version Independent ID: c19d4972-fa39-2908-c33c-f7e1a84d06c5
* Content: [Manage the Updates app for your organization - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-updates-app)
* Content Source: [Teams/manage-updates-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-updates-app.md)
* Service: **msteams**
* GitHub Login: @daisyfell
* Microsoft Alias: **daisyfeller**

**Comment by daisyfell** [comment]
There isn't a specific flow for this in the app itself. You can either use the steps in this article https://learn.microsoft.com/en-us/power-apps/developer/data-platform/auditing/delete-audit-data?tabs=webapi to delete audit data, or you can delete their approval history using the steps in this article: https://learn.microsoft.com/en-us/power-automate/gdpr-dsr-delete#delete-approval-history-from-power-automate.
