### ISSUE TITLE
GCCH Cloud Video Interop Limitations

### ISSUE THREAD

**Issue by bradbrill** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9586]
I am a Teams support engineer that specializes in GCCH. I worked a case where we discovered that it is a known limitation that Pexip connectors need to be hosted in Arizona or Texas Azure regions. The Virginia region is not supported for hosting the Pexip connector in GCCH. I can provide case info and Teams PG engineering contacts to confirm this limitation.

Requesting that we include this guidance under the Office 365 US Government and third-party services section.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 046dec87-2354-a9db-ae19-3bfaa2626bef
* Version Independent ID: 23e7d18f-bbab-75e1-7c85-9b0d0e8f4382
* Content: [Cloud Video Interop for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/cloud-video-interop)
* Content Source: [Teams/cloud-video-interop.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-video-interop.md)
* Service: **msteams**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by dariomws** [comment]
@bradbrill, only GGCH? What about DoD?
