### ISSUE TITLE
No info here

### ISSUE THREAD

**Issue by Rashantha** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#959]
Just marketing. No steps. No how to. And just leads you in a circle back to this page. Waste of 10 minutes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7b32af2-59db-a872-6ed4-fc7b4cd910b3
* Version Independent ID: 38fd3a1a-ee6d-dd63-0de9-5f726d7419cf
* Content: [Skype for Business to Microsoft Teams upgrade](https://docs.microsoft.com/en-us/microsoftteams/journey-skypeforbusiness-teams#feedback)
* Content Source: [Teams/Journey-SkypeforBusiness-Teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Journey-SkypeforBusiness-Teams.md)
* Service: **msteams**
* GitHub Login: @dearbeen
* Microsoft Alias: **dearbeen**

**Comment by AndreaBarr** [comment]
@Rashantha Thank you for pointing this out. 

I will get this over to the Teams/Skype for Business team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by SharS** [comment]
@Rashantha - thanks again for your comment. Can you explain to me where you see this looping behavior?

**Comment by PHITDept** [comment]
I think she was confused and ended up at the same location.    I would agree that MS is making a huge effort to make this a great transition.  But at the same time it is an amazing undertaking for those coming from a basic system Such as skype for business.    Sounds to me that she was looking for a simple how to upgrade from Skype to Teams document or write up.   

The amount of information that has been made available is overwhelming.  You almost need a small business page for helping the smaller type admins get it straight.  That is my opinion.  Having more centralized information and path.

**Comment by LolaJacobsen** [comment]
@Rashantha I'm going to close this issue. We're continually updating the "Upgrade to Teams" content and want to make it as useful as possible. If you need specific information that's missing, please reopen this issue and I'll work with @dearbeen to get you the information you need.
