### ISSUE TITLE
[Doc-Bug] App setup policy pinned apps will install only when user clicks on it

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9593]
If the bot app is added under Pinned apps in app setup policy, app is not installed for the user. When user clicks on app name in teams, then app is installing and sending welcome message.  It is just from prepinned list as soon as the user clicks the app that is pinned it silently gets installed that sends the welcome message to user. 

But we don't see this information in documentation. Can you update the same?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6f91604a-35b0-dfbb-55b2-b601cb0841b0
* Version Independent ID: 84bcd0d7-b4ed-f13e-c84b-2ec6a7661ae9
* Content: [Manage app setup policies in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-app-setup-policies)
* Content Source: [Teams/teams-app-setup-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-setup-policies.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by get-itips** [comment]
Hello @SubbaReddi 
I am looking into this.

**Comment by get-itips** [comment]
Hello @SubbaReddi 
I tested this, and I think this differs from app to app, if the app has somehow some "initial setup", the user will indeed experience that, but it was pretty straightforward, so I am not sure what would be the required addition to the article.
Let me know if I understood you correctly.

**Comment by get-itips** [comment]
@scanum
