### ISSUE TITLE
Skype for Business Online retirement - What did Microsoft start at the beginning of October 2022? (unclear)

### ISSUE THREAD

**Issue by mbalint987** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9595]
[This article](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/skype-for-business-online-retirement.md)  ("Skype for Business Online retirement") said: 

"In addition, beginning in October 2022, Microsoft will begin decommissioning aspects of that infrastructure specific to hybrid organizations."

Does it mean that Microsoft has started to decommission a part of the SfBO infrastructure that is required for hybrid organizations? Please explain what this sentence means and how this process will impact the hybrid organizations.

**Comment by get-itips** [comment]
Hello @mbalint987 
I am looking into this.

**Comment by mbalint987** [comment]
> Hello @mbalint987 I am looking into this.

Hello [get-itips](https://github.com/get-itips),
Have you had a chance to look into this?

**Comment by get-itips** [comment]
Yes, however, I still have no answer from the article's owner.

**Comment by get-itips** [comment]
@bjwhalen BJ Can you help us here? Thanks

**Comment by get-itips** [comment]
@mbalint987 

>Does it mean that Microsoft has started to decommission a part of the SfBO infrastructure that is required for hybrid organizations? Please explain what this sentence means and how this process will impact the hybrid organizations.

Please note this is still current:

> Microsoft **fully supports** hybrid organizations with a mix of TeamsOnly users and on-premises Skype for Business users. Customers with hybrid deployments of Skype for Business Server or Lync Server 2013 should review Implications of Retirement of Skype for Business Online

Also this article https://learn.microsoft.com/en-us/skypeforbusiness/hybrid/plan-hybrid-connectivity#implications-of-the-retirement-of-skype-for-business-online

The current impact is described in the rest of the article.

**Comment by mbalint987** [comment]
Hello @get-itips 

Thank you but I would be still more than happy if I can know what does this mean: "In addition, beginning in October 2022, Microsoft will begin decommissioning aspects of that infrastructure specific to hybrid organizations.". What have been started on Microsoft end?

**Comment by get-itips** [comment]
Hello @mbalint987 I managed to ask the product team and received the answer I shared with you before, I do not have more expanded details than the ones I already shared, sorry.
What is important is that the note about support is still valid (as long as those conditions satisfy).
