### ISSUE TITLE
Extension period incorrect

### ISSUE THREAD

**Issue by dipinn26592** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9598]
Based on the doc here : https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams

"Microsoft 365 live event limit increases
To continue supporting our customers' needs, we will extend temporary limit increases for live events through June 30, 2023, including: "

This doc still says Dec 2022

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by dariomws** [comment]
Hi @dipinn26592, thank you for your feedback.

Sorry but I think both are the same article and it includes the following note:

> [!IMPORTANT]
> **Microsoft 365 live event limit increases**
>
> **To continue supporting our customers' needs, we will extend temporary limit increases for live events through June 30, 2023, including:**
>
>- Event support for up to 20,000 attendees
>- 50 events can be hosted simultaneously across a tenant
>- Event duration of 16 hours per broadcast
>
> Additionally, Live Events with up to 100,000 attendees can be planned through the Microsoft 365 assistance program. The team will assess each request and work with you to determine options that may be available. [Learn more](https://aka.ms/Stream/Blog/LiveEventOptions).

**Comment by dipinn26592** [comment]
Sorry i think this is a duplicate but for a different article
