### ISSUE TITLE
view-only limit 10,000 

### ISSUE THREAD

**Issue by dipinn26592** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9599]
View-only limit is 10,000.

"To continue supporting our customers' needs, we will extend temporary limit increases for live events through June 30, 2023, including:
Event support for up to 20,000 attendees "  as part of this exception the limit has been increased to 20,000

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hello @dipinn26592 
How are you?
That is specified in the linked article https://learn.microsoft.com/en-us/microsoftteams/view-only-meeting-experience
Thanks

**Comment by dipinn26592** [comment]
Hi @get-itips,

I am doing good. Thank you for looking at this. The ask is to make all the articles consistent. While purchasing a license if a customer lands on this page : https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md

and they would assume view-only limit as 20,000 default, while that is temporary. We should have the disclaimer in every article, or find a way to call out the view-only limit is 10K but extended to 20K.

**Comment by get-itips** [comment]
I'll check and get back

**Comment by get-itips** [comment]
disclaimer has been added to the article
