### ISSUE TITLE
OS Requirements for SfB Server 2019 are rather vague

### ISSUE THREAD

**Issue by marktorng** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#960]
Does not specify (like Exchange 2019 https://docs.microsoft.com/en-us/exchange/plan-and-deploy/system-requirements?view=exchserver-2019) 

> "Installing Exchange 2019 on a computer that's running Windows Server Core is fully supported and recommended. The Desktop Experience feature is no longer required."

Listing more comprehensive operating system support for Windows Server 2016/2019 non-desktop experience or core without GUI would be helpful.

**Comment by AndreaBarr** [comment]
@marktorng Thank you for this feedback

I will get this request for more information on the non-desktop experience over to the Teams/Skype for Business team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @marktorng Thanks for sharing feedback, we really appreciate it. Your issue does not reference an article in docs, but I think you refer to this one https://docs.microsoft.com/en-us/skypeforbusiness/plan/system-requirements

Server Core is not supported for SFB 2019 as this article confirms https://docs.microsoft.com/en-us/windows-server/get-started-19/app-compat-19

I will improve the referenced documentation to clearly state this.

Thank you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @marktorng  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
