### ISSUE TITLE
is it really possible to create a team out of a security group ?

### ISSUE THREAD

**Issue by erni19** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9604]
It doesn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43a2187e-570d-f235-3536-69df8eaa906a
* Version Independent ID: da949f22-1617-c737-d5a4-5c51704443e8
* Content: [Enhance existing Microsoft 365 groups - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/enhance-office-365-groups?source=recommendations)
* Content Source: [Teams/enhance-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enhance-office-365-groups.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@erni19 please try [Create a team from an existing group](https://support.microsoft.com/office/create-a-team-from-an-existing-group-24ec428e-40d7-4a1a-ab87-29be7d145865).
