### ISSUE TITLE
Misleading title

### ISSUE THREAD

**Issue by NeilJamesLewis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9607]
This is the top page in search results when looking for help with Teams connection issues. 
It doesn’t actually provide any troubleshooting steps.
What it provides is an explanation that the issue is probably down to corporate network configuration with links to how that should be set up, this is not helpful to an end user who needs to raise a ticket. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9777f6b3-740c-170c-3d16-5524fda9b1c6
* Version Independent ID: b80035a2-ea72-4d2c-ccb0-ac047ba8378a
* Content: [Troubleshoot connectivity issues with Teams client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/connectivity-issues)
* Content Source: [Teams/connectivity-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/connectivity-issues.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @NeilJamesLewis, thank you for your feedback.

Learn.microsoft.com (a.k.a. docs.microsoft.com) content is intended for ITPRos. The content for end-users is included in different places, for example:
https://support.microsoft.com/teams

**Comment by scanum** [comment]
Thank you for your feedback and contributing to the docs. Closing this issue as resolved.
