### ISSUE TITLE
Update documentation for Teams usage reports

### ISSUE THREAD

**Issue by jlsdxc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9610]
The Teams User Activity report no longer applies the selected date range to the data exported to Excel. The documentation does not reflect this which causes invalid expectations and confusion. The verbiage in the existing public KB documentation, https://clicktime.symantec.com/15uBY2kHDRqQKyMB4Nfrv?h=liKIlkM6HyLLiadDPl-HcZp8QU_iZv4mAHom4NZkjaM=&u=https://learn.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-usage-report%23interpret-the-report, should be modified to explain that the export button now includes exporting all of the available data by default (instead of the selected date range).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b138331-2f10-a05d-7e88-68e62e0b3e4f
* Version Independent ID: f923b648-ffe4-8a8a-c189-6e31f1032c10
* Content: [Microsoft Teams usage report - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-usage-report#interpret-the-report)
* Content Source: [Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @jlsdxc, thank you for your feedback.

I have verified the usage report in my demo tenant and I have to select a specific date range before run the report:
![image](https://user-images.githubusercontent.com/33589238/211764193-80747c6b-38a0-4c27-b03d-82efe97a5e8c.png)

**Comment by scanum** [comment]
Thank you for your feedback and contributing to the docs. Closing this issue as resolved.
