### ISSUE TITLE
Link from Sm Teams Managment console Learn more link arrives at this article - but article is only part of the help the link referenced.

### ISSUE THREAD

**Issue by Baldgyt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9612]
The article is fine but I arrived at it from a learn more link inside the teams management console (Manage teams, channels, type column info (i) ) which said:
"Shows if a channel is a private, standard, or shared channel. [Learn more]" (https://docs.microsoft.com/en-US/microsoftteams/private-channels?WT.mc_id=TeamsAdminCenterCSH)
This article says nothing about standard or shared channels i.e. the help link is not helpful [I wanted to know about a shared channel for instance].

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-US/microsoftteams/private-channels?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@Baldgyt thanks for the feedback. I'll pass this along to our content designers to look for a better article to link to.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
