### ISSUE TITLE
Microsoft Teams Display License requirement correction

### ISSUE THREAD

**Issue by yuki-iwagishi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9622]
There are three issues of [ Microsoft Teams displays](https://learn.microsoft.com/en-us/microsoftteams/devices/teams-displays#required-licenses) page.
Required License and Set up hot-desking on Teams displays sections need to be updated.

[Required License](https://learn.microsoft.com/en-us/microsoftteams/devices/teams-displays#required-licenses) section doesn't cover Teams Display has two mode for each licensing. 1. Personal 2. Hot Desking.

[Set up hot-desking on Teams displays](https://learn.microsoft.com/en-us/microsoftteams/devices/teams-displays#set-up-hot-desking-on-teams-displays) mentions Microsoft Teams Rooms licenses. This is incorrect. It requires Microsoft Teams Shared Devices licenses. Teams Rooms license resource accounts don't provide hot desking modes.

And the following statement was invalid after U4(Teams App: 1449/1.0.95.2022120505).

Current:
After you create resource accounts, you can create and assign a policy to enable hot-desking. See [New-CsTeamsIPPhonePolicy](https://learn.microsoft.com/en-us/powershell/module/skype/new-csteamsipphonepolicy) to learn more.

From release notes:
>"The Teams IP Phone policy setting for hotdesking will be disabled for displays and you will be able to invoke hotdesking using Teams accounts with the Teams Shared Device licenses"

Suggestion:
1.Additng hot-desking featuer summary to Features supported by Teams displays sections.
2.Adding Personal and Hot Desking modes information on Required license section with explaining Shared Device license.
3.remove hot-desking feature intro from Set up hot-desking on Teams displays then update license section.

Still I'm not familiar with Resource Accounts with Teams Rooms license cases. With the latest Teams Display, it works as Shared device without hot desking feautre.  If Teams Display has introduced MTR modes, it requires to be updated.

---

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: adb04e3a-276d-d882-7e1b-8878090594ae
* Version Independent ID: 12527964-b91a-242d-4070-7c9d656bf645
* Content: [Microsoft Teams displays - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/devices/teams-displays)
* Content Source: [Teams/devices/teams-displays.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/teams-displays.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
