### ISSUE TITLE
Secondary Camera Feature - MTR for Windows vs Android

### ISSUE THREAD

**Issue by aflien** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9624]
This comparison page is missing the secondary camera feature (not the content camera) as discussed in the links below.  From what I understand, this is not available for Android yet.

•	[Microsoft Teams Rooms is getting better multi-camera support - MSPoweruser](https://mspoweruser.com/microsoft-teams-rooms-is-getting-better-multi-camera-support/#:~:text=Users%20using%20Microsoft%20Teams%20Rooms%20set%20up%20with,on%20the%20chevron%20to%20select%20a%20different%20camera.)
•	[Microsoft Teams Rooms devices to get multi-camera support next month - OnMSFT.com](https://www.onmsft.com/news/microsoft-teams-rooms-multi-camera-support)
•	[Microsoft 365 Roadmap | Microsoft 365](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=85818) (Rolled out last year on MTR for Windows)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 64cc650b-b313-cfab-9f45-190b94c128f4
* Version Independent ID: 9e93ac07-3f1b-9fd4-1907-17f0075bd837
* Content: [Teams Rooms on Windows and Android feature comparison - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/teams-devices-feature-comparison)
* Content Source: [Teams/rooms/teams-devices-feature-comparison.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/teams-devices-feature-comparison.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @aflien, thank you for your feedback.

This is not an exhaustive list. You can read from the article:

"Not all Teams Rooms features will be included on this list, so please continue to consult the [Microsoft 365 roadmap](https://www.microsoft.com/microsoft-365/roadmap) and Microsoft sales representatives for additional details."

**Comment by aflien** [comment]
I can understand that not every feature won't be on this list.  But camera support is fairly essential to the Teams Room experience, therefore I believe it should be on this list, and the list should also include the Content Camera feature.

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
