### ISSUE TITLE
Join with Meeting ID not in list

### ISSUE THREAD

**Issue by paikan78** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9628]
No mention of the Join with Meeting ID.

See article below
https://support.microsoft.com/en-us/office/join-a-meeting-in-teams-1613bb53-f3fa-431e-85a9-d6a91e3468c9#:~:text=then%20select%20Join.-,Join%20with%20a%20meeting%20ID%20from%20your%20Teams%20app,a%20meeting%20ID%20and%20passcode

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 64cc650b-b313-cfab-9f45-190b94c128f4
* Version Independent ID: 9e93ac07-3f1b-9fd4-1907-17f0075bd837
* Content: [Teams Rooms on Windows and Android feature comparison - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/teams-devices-feature-comparison)
* Content Source: [Teams/rooms/teams-devices-feature-comparison.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/teams-devices-feature-comparison.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @paikan78, thank you for your feedback.

From the article:
"Not all Teams Rooms features will be included on this list, so please continue to consult the [Microsoft 365 roadmap](https://www.microsoft.com/microsoft-365/roadmap) and Microsoft sales representatives for additional details."
