### ISSUE TITLE
Adding SBC via TAC not available for GCCH

### ISSUE THREAD

**Issue by bradbrill** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9630]
The option to add an SBC via Teams Admin Center isn't available for GCCH tenants. GCCH tenants will have to use Powershell to add an SBC to a tenant. Could we include this limitation in this doc?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad7d5051-1177-c5cf-bf28-8639d7b6fbd1
* Version Independent ID: 2a9aa4e1-3767-cd46-50fe-f9dd8b0997be
* Content: [Connect your Session Border Controller (SBC) to Direct Routing - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/direct-routing-connect-the-sbc#using-powershell)
* Content Source: [Teams/direct-routing-connect-the-sbc.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-connect-the-sbc.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @bradbrill, thank you for your feedback.

Could you confirm if it's only GCCH? I understand that you can add the SBC via TAC on GCC, but what about DoD?

**Comment by bradbrill** [comment]
It applies to GCCH and DoD
