### ISSUE TITLE
Errors on Dimension table

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9640]
Hi,
I was using the great tool: [CQDPowerShell 2.0.1](https://www.powershellgallery.com/packages/CQDPowerShell/2.0.1) and got the dimensions which are available on the CQD. But when I compare those to your table, I could found the following dimensions which are missing from there:

- Detected Compute Device Causing Problem
- Detected Input Device Causing Problem
- Detected Leaking Echo Problem
- Detected Other User Uplink Problem
- First Audio Capture Connection Type
- First Audio Codec Average BW
- First Audio Device General Failure
- First Audio Devices Connection Type
- First Audio Render Connection Type
- First Capture Dev Name
- First Device Failure
- First Mic Connection Type
- First Mic Device Failure
- First Mic Device Is Speaker Device
- First Mic Initialization Failure
- First Mic Is Silent
- First Network Avg Loss Rate
- First No Mic Devices Enumerated Failure
- First No Speaker Devices Enumerated Failure
- First Recv Avg Freeze Duration
- First Recv Freeze Duration Percent
- First Recv Resolution Height
- First Recv Resolution Width
- First Recv Rms Freeze Duration
- First Render Dev Name
- First Send Mute Percent
- First Speaker Connection Type
- First Speaker Device Failure
- First Speaker Initialization Failure
- First Video Bit Rate Avg
- First Video Frame Rate Avg
- First Wifi Channel Reassociations
- First Wifi Channel Switches
- First Wifi Handovers
- First Wifi Retry Count
- Is Dominant Participant
- Is Dominant Participant Probability
- PII Scrubbed
- Second Audio Capture Connection Type
- Second Audio Codec Average BW
- Second Audio Device General Failure
- Second Audio Devices Connection Type
- Second Audio Render Connection Type
- Second Capture Dev Name
- Second Device Failure
- Second Mic Connection Type
- Second Mic Device Failure
- Second Mic Device Is Speaker Device
- Second Mic Initialization Failure
- Second Mic Is Silent
- Second Network Avg Loss Rate
- Second No Mic Devices Enumerated Failure
- Second No Speaker Devices Enumerated Failure
- Second Recv Avg Freeze Duration
- Second Recv Freeze Duration Percent
- Second Recv Resolution Height
- Second Recv Resolution Width
- Second Recv Rms Freeze Duration
- Second Render Dev Name
- Second Send Mute Percent
- Second Speaker Connection Type
- Second Speaker Device Failure
- Second Speaker Initialization Failure
- Second Video Bit Rate Avg
- Second Video Frame Rate Avg
- Second Wifi Channel Reassociations
- Second Wifi Channel Switches
- Second Wifi Handovers
- Second Wifi Retry Count
- Total User Count

If you are interest to fix those.. ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a455280-ea8e-2ddf-2965-60d9dcc0e21d
* Version Independent ID: 7fb320d3-fa69-23fa-113c-53e9d2e11ada
* Content: [Dimensions and measurements - Call Quality Dashboard (CQD) - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/dimensions-and-measures-available-in-call-quality-dashboard)
* Content Source: [Teams/dimensions-and-measures-available-in-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/dimensions-and-measures-available-in-call-quality-dashboard.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by ParkesJ** [comment]
Documentation is ongoing with CQD as we continue to add new dimensions and measurements to the product.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
