### ISSUE TITLE
Teams Admin App

### ISSUE THREAD

**Issue by Rlkonowi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9641]
We use separate accounts from our day to day account to Administer o365.  I like idea of having the Teams Admin app but cannot use it because my normal account does not have admin rights.   

Is there any way to enter my global admin credentials in the app?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d35393b-2e81-a3b8-69e1-5535f93b68b6
* Version Independent ID: 7d35393b-2e81-a3b8-69e1-5535f93b68b6
* Content: [Manage Microsoft 365 for your organization with the Admin app in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-US/microsoftteams/manage-admin-app#who-can-access-the-admin-app-in-teams)
* Content Source: [Teams/manage-admin-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-admin-app.md)
* Service: **msteams**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
