### ISSUE TITLE
Named report no longer listed.  Now:  PSTN & SMS ‎(‎preview)‎‎ usage

### ISSUE THREAD

**Issue by billvolt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9643]
Did the name of the available report change?  It appears the prior is no longer present.

![image](https://user-images.githubusercontent.com/2335095/213278635-73b56067-efe9-410d-97f4-223773123be4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ad0c889-56d5-35fe-de15-177b6d922d07
* Version Independent ID: e4363647-33e1-b665-5881-169fb619a5b3
* Content: [Microsoft Teams PSTN usage report - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/pstn-usage-report)
* Content Source: [Teams/teams-analytics-and-reports/pstn-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/pstn-usage-report.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @billvolt, thank you for your feedback.

Currently, it's "PSTN and SMS (preview) usage" report.
