### ISSUE TITLE
Zoom host can't see MRT users

### ISSUE THREAD

**Issue by whizzard-tt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9644]
Until the 4.15.54.0 the Zoom video and audio was very choppy and intermittent. It froze a lot despite having sufficient bandwidth. Now the Zoom video and audio seem to work fine since the update, however the Zoom users can't see and video from the Teams side. The MTR image is frozen on the MTR side.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
