### ISSUE TITLE
Image specification for Teams profile pic missing.

### ISSUE THREAD

**Issue by joshuaboys** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9646]
The specification for a Teams site profile pic is missing from the specifications page (or anywhere else) 
This is the profile pic that a Team.has not an individual.
Assumption is that it is 100x100 pixels

**Comment by scanum** [comment]
@joshuaboys Thanks for the feedback!

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
