### ISSUE TITLE
Include location path where the update logs can be found

### ISSUE THREAD

**Issue by rito2k** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9648]
We suggest to collect the MTR update logs, but do not inform where they are located. 
Please include a note to point these can be found under "C:\Users\Skype\AppData\Local\Packages\Microsoft.SkypeRoomSystem_8wekyb3d8bbwe\LocalState\Tracing\MTR-Update" if the script was successful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e4fa80cf-0319-c006-e886-4929a508b04c
* Version Independent ID: 9d598765-fc30-17f0-6594-57de81d8aa39
* Content: [Manually update a Microsoft Teams Rooms device - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/manual-update)
* Content Source: [Teams/rooms/manual-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/manual-update.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @rito2k, thank you for your feedback.

This is included in the article: "The script will provide you with the path to the log file."
