### ISSUE TITLE
Remove "Chrome" from Browser Section

### ISSUE THREAD

**Issue by tylergoodwell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9649]
[Enter feedback here]
I believe the portion of this document discussing browser functionality under VDI (https://learn.microsoft.com/en-us/microsoftteams/teams-for-vdi#teams-on-chrome-browser-versus-teams-desktop-app-for-vdi) should reference "browser," "web app," or "Chromium based browser." There is no reason to specifically reference Google Chrome to the exclusion of other browsers, especially Edge (a *Chromium* based browser). 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-for-vdi)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @tylergoodwell 
I asked internally and the decision is to leave it as-is.
Thanks for your feedback.
