### ISSUE TITLE
Indicate MTR update logs location and check EventLog if successful

### ISSUE THREAD

**Issue by rito2k** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9650]
In Step 3, we suggest to collect the MTR update logs, but do not inform where they are located. 
Please include a note like the following:

MTR update logs can be found under "C:\Users\Skype\AppData\Local\Packages\Microsoft.SkypeRoomSystem_8wekyb3d8bbwe\LocalState\Tracing\MTR-Update".

You can also look for EventID 3603 in the Skype Room System EventLog and search for "First healthy launch after update" to confirm latest update version matches with the expected one.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e4fa80cf-0319-c006-e886-4929a508b04c
* Version Independent ID: 9d598765-fc30-17f0-6594-57de81d8aa39
* Content: [Manually update a Microsoft Teams Rooms device - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/manual-update)
* Content Source: [Teams/rooms/manual-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/manual-update.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @rito2k how are you?
Step 3 says the script will provide the path to the log file, is that the same path you mention? Unfortunately, I don't have an MTR device to test at the moment.
Thanks

**Comment by get-itips** [comment]
@rito2k Alvaro, could you see my last message?

**Comment by get-itips** [comment]
@scanum

**Comment by rito2k** [comment]
Hi all, sorry for the delay in my response.

The path is not provided in neither case (successful or failing update), please see screenshots attached.

By reading the instructions in Step 3, the indication about the log path is only mentioned in the paragraph speaking about when "the script encounters a problem".

My proposal is to add the mentioned note at the end of the instructions at Step 3, so readers do know where to find the output log file in every situation:

MTR update logs can be found under: "C:\Users\Skype\AppData\Local\Packages\Microsoft.SkypeRoomSystem_8wekyb3d8bbwe\LocalState\Tracing\MTR-Update".

After device restart, you can also look for EventID 3603 in the Skype Room System EventLog and search for "First healthy launch after update" to confirm latest update version matches with the expected one.

![NoLogPath_when_error](https://user-images.githubusercontent.com/26970701/223722372-18f00309-494f-430d-9154-6d8b52b2c3a2.png)
![NoLogPath_when_success](https://user-images.githubusercontent.com/26970701/223722376-6f8259ed-2a18-43a9-8584-9176e7f79f92.png)
![MTR_update_log_location](https://user-images.githubusercontent.com/26970701/223723735-5a971b90-03b3-4a6f-984b-abfd1ef02874.png)
![MTR_update_Eventlog_entry](https://user-images.githubusercontent.com/26970701/223725836-ae95a1d4-4ea1-46f7-9372-92d917513e05.png)

**Comment by get-itips** [comment]
@rito2k I'll propose to add that to the article.
