### ISSUE TITLE
Steps to validate Automatic Update Enabled

### ISSUE THREAD

**Issue by sbv2291** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9651]
Can someone please add the steps to validate if the automatic update via Microsoft store is enabled or not? 

We have MTR which was not auto updated but we don’t know how to troubleshoot automatic update issue. Our MS store is not blocked 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e4fa80cf-0319-c006-e886-4929a508b04c
* Version Independent ID: 9d598765-fc30-17f0-6594-57de81d8aa39
* Content: [Manually update a Microsoft Teams Rooms device - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/manual-update)
* Content Source: [Teams/rooms/manual-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/manual-update.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @sbv2291 
Have you seen this resource https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-operations ?
In this case, the best would be to open a support request from your tenant, they will be able to help in your specific scenario.

**Comment by get-itips** [comment]
@scanum
