### ISSUE TITLE
Broken link: Implications of Retirement of Skype for Business Online

### ISSUE THREAD

**Issue by robeden** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9652]
The link for Implications of Retirement of Skype for Business Online reports a 404 error. Currently pointing to: https://learn.microsoft.com/en-us/skypeforbusiness/hybrid/plan-hybrid-connectivity.md#implications-of-the-upcoming-retirement-of-skype-for-business-online

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2cea1cc-731d-bfba-3ed5-63a6339ecf88
* Version Independent ID: 7681956e-e442-07a3-7f7b-f086a0aff173
* Content: [Skype for Business Online retirement - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/skype-for-business-online-retirement)
* Content Source: [Teams/skype-for-business-online-retirement.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/skype-for-business-online-retirement.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Many thanks for your feedback!
