### ISSUE TITLE
Please indicate how usage of Teams premium features can be measured after grace period

### ISSUE THREAD

**Issue by federicombo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9659]
Please indicate how usage of Teams premium features can be measured after grace period

Most customer who are interested in purchase Teams Premium would like to know how many of their internal users use Teams Premium features before decide whether to purchase them or not after the grace period is over. Is there any way a Teams IT admin can measure and analyze the amount of users who use each of the Teams premium features so they can decide to purchase them or not after the grace period?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a5338e6-ae08-bb92-3769-4af2932bf02c
* Version Independent ID: 7a5338e6-ae08-bb92-3769-4af2932bf02c
* Content: [Microsoft Teams Premium - Overview for administrators - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/enhanced-teams-experience)
* Content Source: [Teams/enhanced-teams-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enhanced-teams-experience.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
