### ISSUE TITLE
eSignature Providers - Office 365 GCC tenants

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9661]
https://learn.microsoft.com/en-us/microsoftteams/approval-admin#enable-or-disable-e-signature-providers

The "Settings" described for eSignature providers do not appear on the Manage Apps > Settings page for Approvals in Office 365 GCC tenants. Can you confirm if they are supposed to be there, and if not include a caveat in the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 055b01ff-ee6c-7d5a-74bd-0e8eed7ee6b5
* Version Independent ID: 13c4174f-2a2a-2ef9-14c5-2f10817cc66a
* Content: [Manage the Approvals app in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/approval-admin)
* Content Source: [Teams/approval-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/approval-admin.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanachin**

**Comment by dariomws** [comment]
Hi @npherson, thank you for your feedback.

The best way to confirm if we should be able to see these settings in GCC is to contact the product team or a program manager. We cannot contact them directly so I suggest that you contact them. If you confirm this information, I can add a note to the article to highlight that these settings are not available in GCC environments.

Thanks!

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
