### ISSUE TITLE
Anonymous Users

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9667]
Please add clarification that Q&A can't be used for anonymous join users. This is one of the core uses for webinars, but can't be done if participants are not authenticated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3b814e8-f9e4-7396-b016-62b8bd385585
* Version Independent ID: e3b814e8-f9e4-7396-b016-62b8bd385585
* Content: [Manage Q&A in Teams Meetings - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/manage-qna-for-teams)
* Content Source: [Teams/manage-qna-for-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-qna-for-teams.md)
* Service: **msteams**
* GitHub Login: @wlibebe
* Microsoft Alias: **wlibebe**

**Comment by wlibebe** [comment]
Hi @danmyhre thank you for reaching out! The allowed Q&A user types are listed under the "Who can use Q&A?" section. The inability of anonymous users to use Q&A is intended to be inferred, as this user type isn't listed under the section of allowed users. Thank you again and I wish you a fantastic day :)
