### ISSUE TITLE
Lacking information

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9670]
This document is entirely lacking information on what the guest experience is for the guests inside their team thick client or web client.  It should describe especially how native tenant user accounts and guest user accounts a managed by the various teams clients, and how guest experience for notifications are handled between different accounts in teams when teams has multiple accounts associated (e.g. native tenant and a guest account).  Please add the info.

Thanks

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [Guest experience in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/guest-experience)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @ssmiller60 
How are you?
Can you please help me better understand what you see this article is lacking?
If I understood correctly, you want to see differentiated Teams Desktop versus Web?

and can you expand please also the explanation about notifications?

Thanks

**Comment by get-itips** [comment]
@ssmiller60 Hello, could you see my last message here? thanks

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
