### ISSUE TITLE
Minimum to Maximum

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9671]
Images with minimum dimensions of 3840 px X 2160 px ---- minimum should be changed to maximum.

That should say:  Images with maximum dimensions of 3840 px X 2160 px

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c3d5c2e-7936-6966-078f-304b628c9b74
* Version Independent ID: 1c3d5c2e-7936-6966-078f-304b628c9b74
* Content: [Custom meeting backgrounds for Teams meetings - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/custom-meeting-backgrounds#enabling-the-custom-background-policy)
* Content Source: [Teams/custom-meeting-backgrounds.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/custom-meeting-backgrounds.md)
* Service: **msteams**
* GitHub Login: @wlibebe
* Microsoft Alias: **wlibebe**

**Comment by wlibebe** [comment]
Hi @Karr thank you for reaching out. I've updated the documentation and wish you a fantastic day :)
