### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9674]
This page could use some details about the storage of whiteboard data. In Teams, even if you create a whiteboard as a channel tab, it stores the data in the OneDrive of the creator, so this highly not recommended to be used. This is a terrible storage strategy since the data isn't stored in the Team's document library.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26085815-da9c-b727-5323-b0d7dc840fb8
* Version Independent ID: 105b742d-a730-fb7b-b0fd-7cb67919880a
* Content: [Manage the Whiteboard in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-whiteboard)
* Content Source: [Teams/manage-whiteboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-whiteboard.md)
* Service: **msteams**
* GitHub Login: @wlibebe
* Microsoft Alias: **wlibebe**

**Comment by get-itips** [comment]
Hello @danmyhre Dan

The info is here https://learn.microsoft.com/en-us/microsoft-365/whiteboard/manage-data-organizations?view=o365-worldwide#onedrive-for-business-storage-overview

I'll propose adding a link to this article.

Thanks for your feedback.
