### ISSUE TITLE
Pay-as-you-go Calling Plan

### ISSUE THREAD

**Issue by benstegink** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9677]
Can the documentation be updated to include a pay-as-you-go calling plan? It's a little vague from this documentation on if/when you can use a pay-as-you-go calling plan with a Teams Phone license vs. having to purchase bundled domestic or international minutes.

My understanding is that you don't need bundled minutes if you get a pay-as-you-go calling credit plan with your phone system licenses, but it would be nice to see it in the official documentation, especially the table of combinations.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: abae7324-861d-7ca7-7239-a5df8fd927d5
* Version Independent ID: 8a30bd2f-9bc3-a0a8-8b31-d53836ead4d0
* Content: [Microsoft Teams add-on licenses - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing)
* Content Source: [Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@benstegink The documentation we link out to in the https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing doc concerning Calling Plans includes a section discussing how to fund a Pay-as-you-go Calling Plan: https://learn.microsoft.com/en-us/microsoftteams/calling-plans-for-office-365#how-to-fund-a-pay-as-you-go-calling-plan. 

There are 2 ways to fund a PAYGo Calling Plan: purchasing Communication Credits or purchasing the PAYGo Calling Plan through the New Customer Experience model.

Does that provide clarity?

**Comment by benstegink** [comment]
@DaniEASmith thanks, it's more around does a Teams Phone Standard work with a Pay-as-you-go, or do those only work with the pooled domestic or international plan.

![image](https://user-images.githubusercontent.com/6474247/214952462-51cf2124-30c0-4106-a9dd-fb4c3c3c990b.png)

**Comment by DaniEASmith** [comment]
Yes, Teams Phone Standard works with PAYGo Calling Plan. I'll add that to the table.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
