### ISSUE TITLE
Teams Panels - License requirement missing info

### ISSUE THREAD

**Issue by yuki-iwagishi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9679]
[](https://learn.microsoft.com/en-us/microsoftteams/devices/teams-panels#license-requirement)

```
License requirement
To use Teams panels, you need a [Microsoft Teams Rooms License](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing).
```
There is another way to use Teams Panel as license perspective. Teams Shared Device license.
(https://learn.microsoft.com/en-us/MicrosoftTeams/teams-add-on-licensing/teams-shared-device-license)

So it should be:

License requirement
To use Teams panels, you need a [Microsoft Teams Rooms License](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing) or [Microsoft Teams Shared Devices licensing](https://learn.microsoft.com/en-us/MicrosoftTeams/teams-add-on-licensing/teams-shared-device-license).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6f6d4313-70e2-ac40-0e73-85bdb815c38b
* Version Independent ID: 78f8d192-8018-2988-db5c-44900a60833a
* Content: [Microsoft Teams panels - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/devices/teams-panels)
* Content Source: [Teams/devices/teams-panels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/teams-panels.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Thanks, document has been updated in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/f9be2cc9768bbc63d3514a62e3bad7dd8ecb608b
