### ISSUE TITLE
Call out that personal experience is no longer supported 

### ISSUE THREAD

**Issue by DarCampbell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9680]
The Note for the July 2023 change in license states that user sign-in is not supported. It does not directly say that the personal experience option that was previously in MTR -A will not be supported and to use the companion device experience to have this same experience. This will be helpful for the customers that use MTR in a personal executive room or Suite environment

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-licensing.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @DarCampbell how are you?

To understand better: do you feel the current note is not clear enough that personal accounts can't be used anymore and you want to specifically detail that.

Thanks for clarifying,

**Comment by get-itips** [comment]
@DarCampbell Could you see my last comment here? Thanks

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
