### ISSUE TITLE
Photoshop template is out of date, UI overlay does not match what is displayed on screen

### ISSUE THREAD

**Issue by TAz00** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9681]
Photoshop template is out of date, UI overlay does not match what is displayed on screen

Clock dosnt fit, and the message text below dosnt fit

Please supply an updated accurate template, or delete the current one so we wont have to waste our time with it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 25a70665-5bf1-14f7-1df0-7596effcaf48
* Version Independent ID: 813cf005-2777-9419-d1ce-3f9401ac267c
* Content: [Remotely manage Microsoft Teams Rooms device settings - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/rooms/xml-config-file#custom-theme-images)
* Content Source: [Teams/rooms/xml-config-file.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/xml-config-file.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @TAz00 I am working on this

**Comment by get-itips** [comment]
Hello @TAz00 
I could confirm that the file will be updated in the near future.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
