### ISSUE TITLE
Disable actionability vs disable missed activity emails

### ISSUE THREAD

**Issue by rhornArch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9682]
This documentation is not extremely clear if the SmtpActionableMessagesEnabled setting disables the actionable portion of the email only or how it affects the content of the email.  There is no reference to removing missed activity emails in total by an administrator here.  Our organization does not want copies of communication content stored and discoverable in BOTH Teams and Outlook items.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f34a4f9-bb6f-03e9-9c11-bb2f43dd9aeb
* Version Independent ID: a6e1ee45-8ce4-96b4-21ad-90ca8af646c4
* Content: [Manage actionable activity emails - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-outlook-email-integration)
* Content Source: [Teams/teams-outlook-email-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-outlook-email-integration.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @rhornArch 

I believe the scope of the setting is exactly defined in the article:

>Once the feature is disabled, the Reply option is replaced by Reply in Teams making the missed activity emails no longer considered actionable. Users will no longer be able to respond directly from Outlook and are directed to continue the conversation on Teams.

So that will only enable or disable action buttons in those email messages.
