### ISSUE TITLE
Microsoft Forms limitations update - total responses

### ISSUE THREAD

**Issue by joegasper** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9684]
The [number of Forms responses](https://support.microsoft.com/en-us/office/form-question-response-and-character-limits-in-microsoft-forms-ec15323d-92a4-4c33-bf88-3fdb9e5b5fea) has been increased from 50,000 to 5,000,000.

See this [section ](https://learn.microsoft.com/en-us/microsoftteams/manage-updates-app#data-limitations)for the update to the maximum response number.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c19d4972-fa39-2908-c33c-f7e1a84d06c5
* Version Independent ID: c19d4972-fa39-2908-c33c-f7e1a84d06c5
* Content: [Manage the Updates app for your organization - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-updates-app)
* Content Source: [Teams/manage-updates-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-updates-app.md)
* Service: **msteams**
* GitHub Login: @daisyfell
* Microsoft Alias: **daisyfeller**

**Comment by get-itips** [comment]
Thanks for your feedback!

**Comment by get-itips** [comment]
Document has been updated.
