### ISSUE TITLE
Teams - Search for people in other organizations - Incorrect about Guest users?

### ISSUE THREAD

**Issue by CJFranklin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9686]
I had a customer contact me about this page:
https://learn.microsoft.com/en-us/microsoftteams/guest-access

The line: 
Search for people in other organizations	Yes2	No

Users definitely seem to be able to search for guest accounts in Teams, so the "No" at the end appears to be incorrect?  Or may at least require a footnote to clarify what is being referred to here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5f080a5c-4268-1db4-566f-f1edc27920b5
* Version Independent ID: ac556a92-58af-3e05-f53b-0fc00afc96c0
* Content: [Use guest access and external access to collaborate with people outside your organization - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/communicate-with-users-from-other-organizations)
* Content Source: [Teams/communicate-with-users-from-other-organizations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/communicate-with-users-from-other-organizations.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @CJFranklin 
How are you?
From my point of view, the table shows what the external user or guest can do, so that would translate as:

External access users CAN Search for people in other organizations
Guests CAN'T Search for people in other organizations

Let me know if I understood correctly,

**Comment by CJFranklin** [comment]
The table is labeled "Things your users can do", I believe it's saying how your users are able to interact with Guests or External Users?

**Comment by get-itips** [comment]
I think that title could generate confusion, but if you read through it and specially the notes at the bottom of the tables, it is referring to the users in the columns.

**Comment by get-itips** [comment]
@scanum
