### ISSUE TITLE
Inconsistencies with Teams Premium Events summary

### ISSUE THREAD

**Issue by CaillinP** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9687]
The section that describes what Webinar features are available with Teams Premium is different from the full list at https://learn.microsoft.com/en-us/MicrosoftTeams/teams-add-on-licensing/licensing-enhance-teams.

I confirmed with our Microsoft account team that items like Presenter Bios are included in the standard Teams licence and don't require premium.  I believe the terms and conditions custom question may also not require premium.

![image](https://user-images.githubusercontent.com/124211336/216172535-e27d8b4b-533a-41bf-9bcf-116524033339.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a5338e6-ae08-bb92-3769-4af2932bf02c
* Version Independent ID: 7a5338e6-ae08-bb92-3769-4af2932bf02c
* Content: [Microsoft Teams Premium - Overview for administrators - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/enhanced-teams-experience)
* Content Source: [Teams/enhanced-teams-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enhanced-teams-experience.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by CarolynRowe** [comment]
Yes, that is why the doc states some of the features require Teams Premium.  The purpose of the article is to introduce the new webinar experience, but refer to the licensing doc for specifics on Teams Premium and E licensing.  This article is not specific to Teams Premium.
