### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Peter186** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9690]
The "full version" appears to be less full than the free version.   

(And I clicked on a link on https://learn.microsoft.com/en-us/microsoftteams/upgrade-freemium inviting feedback on the switch from Teams Classic to a paid Teams subscription, so why is this page a Github page regarding SkypeForBusiness?  Very confusing.) 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce24a74-5dc2-3754-af64-1bbec243deb8
* Version Independent ID: 1d3f9154-6ba9-3fd0-8280-25af8a86afc9
* Content: [Upgrade Microsoft Teams Free (classic) to subscription - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/upgrade-freemium)
* Content Source: [Teams/upgrade-freemium.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/upgrade-freemium.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by scanum** [comment]
I know the product teams are always looking for user feedback and how to make Teams better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice 
SharePoint: https://sharepoint.uservoice.com/.
Skype for Business: https://www.skypefeedback.com/.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.
Thank you for your contribution to make the docs better! Much appreciated!
