### ISSUE TITLE
Yealink 5x models EOL 

### ISSUE THREAD

**Issue by mushmasha** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9693]
Yealink 5x models are at EOL stage and discontinued https://www.yealink.com/en/product-detail/microsoft-teams-phone-t56a, please remove them from Teams certified phones, cause so far it is confusing. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aaaef9e1-8f1c-ebf0-7856-4c007342a2c3
* Version Independent ID: 3eaf671f-375e-8787-9c66-3947c3606559
* Content: [Devices for Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/devices/teams-ip-phones#certified-teams-phones)
* Content Source: [Teams/devices/teams-ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/teams-ip-phones.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @mushmasha, thank you for your feedback.

Yealink T55A, T56A, and T58A phones are not included in the certified Teams phone table/section. They are only included in the Firmware versions table/section because they are still under extended support for software bug fixes.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
