### ISSUE TITLE
Application Authentication Not Working

### ISSUE THREAD

**Issue by ThoughtContagion** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9698]
Application authentication still appears to not function properly.
The documentation states version 4.7.1-preview or later.
![image](https://user-images.githubusercontent.com/88730003/216988028-6c7ac823-8db9-45c2-971c-f17f746d13be.png)

Installed version is 4.9.3
![image](https://user-images.githubusercontent.com/88730003/216988326-86d5ed5a-0412-4a29-918f-74215856bf69.png)

Authentication works however, nothing afterwards appears to.
According to the docs, the Get-CsTenantFederationConfiguration cmdlet should function as it is stated 

> All cmdlets are supported now, except for the cmdlets mentioned below.
> 
> New-Team
> [Get|Set|New|Sync]-CsOnlineApplicationInstance
> *-CsUserCallingSettings
> *-CsUserCallingDelegate
> *PolicyPackage*
> *-CsTeamsShiftsConnection*
> *-CsBatchTeamsDeployment*

All commands after successful application authentication return the same error
![image](https://user-images.githubusercontent.com/88730003/216989897-67059c41-78be-45aa-a113-c01d55caeffd.png)

![image](https://user-images.githubusercontent.com/88730003/216989573-6f120ab2-e2ae-4c55-921e-ad1217ab2f08.png)

> Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error message : The WinRM client cannot process the request. The authentication mechanism requested by the client is not supported by the server or unencrypted traffic is disabled in the service configuration.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32304edf-550b-72a3-57df-6dcc29dba56d
* Version Independent ID: 32304edf-550b-72a3-57df-6dcc29dba56d
* Content: [Application-based authentication in Teams PowerShell Module - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-powershell-application-authentication)
* Content Source: [Teams/teams-powershell-application-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-application-authentication.md)
* Service: **msteams**
* GitHub Login: @pbafna03
* Microsoft Alias: **pbafna**

**Comment by pbafna03** [comment]
Hi @ThoughtContagion, 

Can you please confirm if the App has: 

(a) Microsoft Graph API permission - Organization.Read.All 

(b) AAD Admin Role assigned - ref https://learn.microsoft.com/en-us/microsoftteams/using-admin-roles#teams-roles-and-capabilities 

If any of the above is missing, please add the same and try with a fresh disconnect-MicrosoftTeams & Connect-MicrosoftTeams after a few minutes of addition. 

Thanks,

**Comment by ThoughtContagion** [comment]
Yes, the application has Organization.Read.All and application_access_custom_sba_appliance, among a host of other permissions.
I have also applied the roles of Global Reader, Teams Administrator, and finally Global Administrator while testing the authentication - all attempts met with the same error.
![image](https://user-images.githubusercontent.com/88730003/217035039-ff4275f9-72e0-4696-9071-3ef4da84e082.png)
![image](https://user-images.githubusercontent.com/88730003/217035834-f8d6f452-ef4d-405d-b937-87ebd25b62a3.png)

I even re-enabled winrm and made sure that client-side basic auth was enabled, as this was a previous requirement for the module to work.
![image](https://user-images.githubusercontent.com/88730003/217035570-3ec0c643-6f86-4ebd-a83e-c5c3a7a11548.png)

I have tested this on two separate tenants, a free development tenant with Developer E5 licenses, and a Small Business Premium production tenant with the same results.

**Comment by pbafna03** [comment]
Hi @ThoughtContagion, 

Thanks for sharing the details, please **_remove_** the "application_access_custom_sba_appliance" permission assigned to Skype and Teams Tenant Admin API. And post removing the permission, after a few minutes please do Disconnect-MicrosoftTeams and then Connect-MicrosoftTeams.

Also, client-side basic auth is not needed with TPM 4.x.x versions in the commercial environment. 

Thanks,
