### ISSUE TITLE
Clarification on what happens in Beta ring

### ISSUE THREAD

**Issue by cchambers-cap** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9701]
I noticed that users in the Preview ring of O365 should be receiving a Preview version of Teams and will get a "P" added to the profile pic to differentiate the version from standard. I'm in the beta ring of O365, but do not have a "P" in my Teams icon and wanted clarification if this meant I was getting a beta ring of teams that just isn't identified, or if there was a bug that means beta ring users are getting the standard ring version of Teams. If Beta users get a beta version that isn't identified, I'd suggest making note of it in this documentation.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5f1cdd1-09ff-f95d-6d50-e7880d34020f
* Version Independent ID: 59219640-305b-30c1-bc10-87e2633d95db
* Content: [Public preview in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/public-preview-doc-updates#enable-public-preview)
* Content Source: [Teams/public-preview-doc-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/public-preview-doc-updates.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @cchambers-cap, thank you for your feedback.

For the developer preview, you should see:
![image](https://user-images.githubusercontent.com/33589238/219008445-9c817241-ff10-43d8-a1a6-97122df87620.png)

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
