### ISSUE TITLE
Availability of the recap features is mixed up

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9704]
This article mentions the following on availability:
View time markers in meeting recordings when you joined or left a meeting (coming soon)
View when you were @mentioned

It looks like the markers for joining and leaving are not available and markers for mention are available now. But this article states the opposite:

https://www.microsoft.com/en-us/microsoft-365/blog/2023/02/01/microsoft-teams-premium-cut-costs-and-add-ai-powered-productivity/ "Available today, personalized timeline markers—that only you can see—call out when you joined or left a meeting in the meeting recording, so you can quickly click and listen in on what you missed. Personalized timeline markers will expand to include when your name was mentioned and when a screen was shared."

Can you confirm which is correct?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c100aa6e-f8a3-053f-f5c6-d3e543dea5a0
* Version Independent ID: c100aa6e-f8a3-053f-f5c6-d3e543dea5a0
* Content: [Microsoft Teams Premium licensing - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/licensing-enhance-teams)
* Content Source: [Teams/teams-add-on-licensing/licensing-enhance-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/licensing-enhance-teams.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@Larryngolog Since your submission of this GitHub Issue, the article has been updated to reflect availability of other features including those you mentioned in your Issue ticket. The article is showing what is currently available and what is coming soon.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
