### ISSUE TITLE
ZenDesk Integration 

### ISSUE THREAD

**Issue by gemmasnchez** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9705]
If using a ZenDesk connector, does that mean that integration stops or that we will just have to update the connector in the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5eb6a35-32fa-6703-8ed2-0855e602b7d5
* Version Independent ID: 7890ca09-d505-35a9-071a-8662a4b19275
* Content: [Manage Microsoft 365 connectors and custom connectors - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/office-365-custom-connectors#considerations-when-using-connectors-in-teams)
* Content Source: [Teams/Office-365-custom-connectors.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-custom-connectors.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
