### ISSUE TITLE
No Connectors for the new Shared channels?

### ISSUE THREAD

**Issue by gazmeist** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9711]
[Enter feedback here]

No Connectors for the new Sahred channels? Why not? Really need this!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5eb6a35-32fa-6703-8ed2-0855e602b7d5
* Version Independent ID: 7890ca09-d505-35a9-071a-8662a4b19275
* Content: [Manage Microsoft 365 connectors and custom connectors - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/office-365-custom-connectors)
* Content Source: [Teams/Office-365-custom-connectors.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-custom-connectors.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by ashishguptaiitb** [comment]
Hi @gazmeist , I'd request that you post it as a feature request https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472 
Alternately, you can search for existing requests and add your vote on those. For example, see [these search results](https://feedbackportal.microsoft.com/feedback/search/ad198462-1c1c-ec11-b6e7-0022481f8472?q=Connectors+shared+channels).

Given that there is no documentation update to be done at the moment, I am closing this issue.
