### ISSUE TITLE
The cmdlet Set-CsPhoneNumberAssignment is not available for GCCH and DoD clouds yet.

### ISSUE THREAD

**Issue by pavelgogit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9713]
To avoid GCCH/DoD customer confusions, please update the below documentations with a note that the cmdlet Set-CsPhoneNumberAssignment is only available in commercial and GCC cloud instances, not for GCCH or DoD. Tenants that are enabled for Regionally Hosted Meetings for Skype for Business Online (GCCH/DOD) should continue to use the Set-CsOnlineApplicationInstance cmdlet.
https://learn.microsoft.com/en-us/microsoftteams/manage-resource-accounts#assign-a-phone-number
https://learn.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps

**Comment by dariomws** [comment]
Hi @pavelgogit, thank you for your feedback.

https://learn.microsoft.com/powershell/module/teams/set-csphonenumberassignment contains the following sentence: "The cmdlet is only available in commercial and GCC cloud instances."

**Comment by pavelgogit** [comment]
Oh man, it's at the bottom of the documentation :( Thank you @dariomws

**Comment by ckarawani** [comment]
Hey @dariomws, I do think the doc lacks the alternative path to take?

How do you assign a PSTN number to a user for direct routing with GCCH? 
` Set-CsUser` is deprecated in the more recent TPM versions and `Set-CsPhoneNumberAssignment` is not available for GCCH, so what option do we have?

**Comment by dariomws** [comment]
@ckarawani, for GCCH and DoD, you still need to use Set-CsUser.

**Comment by ckarawani** [comment]
Ok thanks @dariomws
