### ISSUE TITLE
Microsoft teams room script failing CreateSrsMedia.ps1 script

### ISSUE THREAD

**Issue by sachinraj548** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9715]
![image](https://user-images.githubusercontent.com/111630460/218015035-dbcfcb2e-8945-48d6-9d77-d4a591faab86.png)

**Comment by dariomws** [comment]
@sachinraj548 - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.
