### ISSUE TITLE
How does this impact existing resource accounts that are not assigned a license?

### ISSUE THREAD

**Issue by dbradley-expo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9716]
What happens to existing resource accounts which are not assigned a number and not assigned a license?

Is there a requirement for them all to be identified and a license assigned?

There is no mention of this scenario in the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d6891495-01c6-117b-c28b-28232782ba74
* Version Independent ID: 1c23b35a-e9ba-ffdd-9baa-a3f83f4ed9ca
* Content: [Microsoft Teams Phone Resource Account licenses - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/virtual-user)
* Content Source: [Teams/teams-add-on-licensing/virtual-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/virtual-user.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@dbradley-expo If I'm understanding your questions correctly, a resource account doesn't have a Resource Account license assigned to it won't be active. For example, if it's assigned to a call queue, that call queue simply wouldn't work.

**Comment by dbradley-expo** [comment]
> @dbradley-expo If I'm understanding your questions correctly, a resource account doesn't have a Resource Account license assigned to it won't be active. For example, if it's assigned to a call queue, that call queue simply wouldn't work.

Thank you Dani, so it would be best to assume, for the many call queues I have implemented for customers without a resource account license, need to be re-visited and assigned a license before they just stop working?

**Comment by DaniEASmith** [comment]
> Thank you Dani, so it would be best to assume, for the many call queues I have implemented for customers without a resource account license, need to be re-visited and assigned a license before they just stop working?

@dbradley-expo, I have confirmed with my internal partners that you will need to assign a Teams Resource Account license to all resource accounts that you want to be functional. We don't have an official timeline as to when this will go into effect at this point, but the best course of action would be to revisit those accounts and add the Teams Resource Account license.

**Comment by dbradley-expo** [comment]
> > Thank you Dani, so it would be best to assume, for the many call queues I have implemented for customers without a resource account license, need to be re-visited and assigned a license before they just stop working?
> 
> @dbradley-expo, I have confirmed with my internal partners that you will need to assign a Teams Resource Account license to all resource accounts that you want to be functional. We don't have an official timeline as to when this will go into effect at this point, but the best course of action would be to revisit those accounts and add the Teams Resource Account license.

That is great, thank you for clarifying, I hope you don't mind if I contribute to the page to include that information! :)

**Comment by dbradley-expo** [comment]
Sorry Dani, I forgot to ask. Will there be a cost to purchase resource account licenses outside of your normal allocation?

For example if I had 10 Teams phone standard licenses, but used up all of my 26 allocated resource account licenses, would there be a cost to purchase more?

In the event of company merger etc... it is likely that this allocation will go over often..

**Comment by DaniEASmith** [comment]
@dbradley-expo

Yes, there's a cost for resource account licenses over your allocation. Do you have a Microsoft account representative or Sales contact?

**Comment by dbradley-expo** [comment]
> @dbradley-expo
> 
> Yes, there's a cost for resource account licenses over your allocation. Do you have a Microsoft account representative or Sales contact?

We do, I'll reach out to them. Is there no public information about the cost? everywhere I look resource accounts licenses show as no cost, or is it on a case by case basis?

**Comment by DaniEASmith** [comment]
I don't believe we advertise the cost of the Teams Resource Account license, and like many of our licenses, the price depends on the customer. I advise you to speak with your Microsoft rep as they may be able to increase your allotment of zero-cost Resource Account licenses.
