### ISSUE TITLE
Shared Channel "Inviter" role

### ISSUE THREAD

**Issue by Korbyn72** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9720]
So, for the error Due to admin policy, you can't add external people to the channel, the corporate policy for M365 Groups | Guests, has the "Let group owners add people..." cleared, what then?  External users can only be invited by Global Admin, or possibly Teams Admin, via the Teams Admin Console?  I'm experimenting with adding Guest Invite admin role to my user account, but so far (after a couple of hours) I still can't invite external people through the desktop client or web client.

Not looking to troubleshoot, just looking for alternate methods to administrate in the unfortunate event that someone has made the settings changes cause the problems.  I'm not sure if the Guest Inviter role applies to B2B Direct Connect, it appears it may only be for B2B Collaboration, unless that documentation is out of date and I just have wait a MS Minute (1-24 hours) for the Guest Inviter role to kick in on my Teams user account.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 138ac890-8786-c6e6-db7e-1e90a94e6c9b
* Version Independent ID: 138ac890-8786-c6e6-db7e-1e90a94e6c9b
* Content: [Shared channels errors in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/shared-channels-errors)
* Content Source: [Teams/shared-channels-errors.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/shared-channels-errors.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
