### ISSUE TITLE
Newest data columns/fields are missing

### ISSUE THREAD

**Issue by vdoplayer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9721]
"_Exported PSTN usage report_" is missing three columns/fields: "**Call Direction**", "**Operator**" and "**Source of Call Duration**"

"_Exported Direct Routing usage report_" is missing three columns/fields: "**AAD ObjectId**", "**External Country**" and "**Call Direction**"
___
Document Details

Version Independent ID: e4363647-33e1-b665-5881-169fb619a5b3
Content: [Microsoft Teams PSTN usage report - Microsoft Teams](https://learn.microsoft.com/microsoftteams/teams-analytics-and-reports/pstn-usage-report)
Content Source: [Teams/teams-analytics-and-reports/pstn-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/pstn-usage-report.md)

**Comment by vdoplayer** [comment]
@scanum I hope this observation was properly prepared by me?

Upon inspection of the generated CSV files, the differences with the documentation become evident.

Unless, the export has a "preview" mode setting?

Thank you kindly!

**Comment by vdoplayer** [comment]
I missed a **forth** column/field found within the exported CSV file: 

"_Exported PSTN usage report_" is missing **four** columns/fields: "**External Country**", "**Call Direction**", "**Operator**" and "**Source of Call Duration**"

"_Exported Direct Routing usage report_" is missing **three** columns/fields: "**AAD ObjectId**", "**External Country**" and "**Call Direction**"

**Comment by vdoplayer** [comment]
@dariomws, may I suggest a matching description to the fields size? (Also, is the 2nd "External Country" to be removed?)

Exported PSTN usage report
| # | Name | Data type (SQL Server) | Description |
| --- | --- | --- | --- |
| 14 | External Country | nvarchar(16) | Digit(s) country code dialed |

Exported Direct Routing usage report
| # | Name | Data type (SQL Server) | Description |
| --- | --- | --- | --- |
|5 | External Country | nvarchar(16) | Digit(s) country code dialed |

**Comment by dariomws** [comment]
@vdoplayer, I couldn't confirm that External Country also appears on "Exported Direct Routing usage report".
