### ISSUE TITLE
Confusing, circular information without pricing

### ISSUE THREAD

**Issue by BethCampbell22** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9728]
These pages should include hyperlinks for pricing. They have tons of links, but all are circular, and keep leading me back to the same pages. Very, very confusing information without a lot of clarity. There should be a simple view that compares the different plans and has pricing information included. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: abae7324-861d-7ca7-7239-a5df8fd927d5
* Version Independent ID: 8a30bd2f-9bc3-a0a8-8b31-d53836ead4d0
* Content: [Microsoft Teams add-on licenses - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing)
* Content Source: [Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by dariomws** [comment]
Hi @BethCampbell22, thank you for your feedback.

We cannot include price in learn.microsoft.com (a.k.a. docs.microsoft.com). It's technical information not sales information. If you access your tenant you'll be able to see all the add-ons that you can acquire and the price of each one. In addition, you can contact you account manager for more information.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
