### ISSUE TITLE
CsUserCallingDelegate not yet supported

### ISSUE THREAD

**Issue by markusgreinerdamovo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9730]
Hi,

and reason why CsUserCallingDelegate is not yet supported? We do have an app that will help setting Delegates much more convinient. But must customers do not like the idea of putting a admin-user into a script. So Appbased Auth would be highly needed. 
Could you share an outlook if or when this will be supported?

Thanks
Markus

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32304edf-550b-72a3-57df-6dcc29dba56d
* Version Independent ID: 32304edf-550b-72a3-57df-6dcc29dba56d
* Content: [Application-based authentication in Teams PowerShell Module - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/teams-powershell-application-authentication)
* Content Source: [Teams/teams-powershell-application-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-application-authentication.md)
* Service: **msteams**
* GitHub Login: @pbafna03
* Microsoft Alias: **pbafna**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
