### ISSUE TITLE
[Doc-Bug] User Pinned apps are clearing after cache clearance (Signout/signin to teams)

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9735]
Hi Team,
If the user pinned the app, it is saving to cache but not saving to backend immediately. So, if the user signout/signin back, user pinned apps are not showing. 
User pinned app details saving to cache and it is saving to backend after some time(May be 5-10 minutes). So, please add note for the same in documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6f91604a-35b0-dfbb-55b2-b601cb0841b0
* Version Independent ID: 84bcd0d7-b4ed-f13e-c84b-2ec6a7661ae9
* Content: [Manage app setup policies in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-app-setup-policies)
* Content Source: [Teams/teams-app-setup-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-setup-policies.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by dariomws** [comment]
Hi @SubbaReddi, thank you for your feedback.

Where are you suggesting to add the note?

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
