### ISSUE TITLE
Updates for MTR enrolled in Pro Portal

### ISSUE THREAD

**Issue by WilliamDO89** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9738]
How does this work when the MTR is enrolled via the Pro Portal and not via Intune or SCCM? Defender is showing the devices missing the updates however Pro Portal isn't showing the updates at all. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a306a58-674d-a784-9763-3d9884f4eb60
* Version Independent ID: dae89456-43a7-8a21-e418-24f83676d70c
* Content: [Manage Windows Updates for Microsoft Teams Rooms - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/updates)
* Content Source: [Teams/rooms/updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/updates.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @WilliamDO89, thank you for your feedback.

I think you can find this information in the following article:
https://learn.microsoft.com/microsoftteams/rooms/update-management

"Should be kept enabled and not redirected to WSUS, nor blocked from a networking perspective. Neither GPO nor MDM policies should be used to manage OS updates."

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
