### ISSUE TITLE
Connect-MicrosoftTeams -AccessToken token expiration issue

### ISSUE THREAD

**Issue by ITMonkey78** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9739]
Connect-MicrosoftTeams fails to connect when using the -AccessToken method unless the tokens used have an expiry time within 90 mins of each other.

Error seen:
```
> Connect-MicrosoftTeams -AccessTokens @("$graphToken", "$teamsToken")
Connect-MicrosoftTeams : The provided tokens must have less than 5400 seconds difference in the time range of expiration.
+ ...              Connect-MicrosoftTeams -AccessTokens @("$graphToken", "$teamsToken")
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This was an issue in the module a few versions back but was fixed by removing the time requirement as the token creation has a random period of time added to the default 3600 seconds (60mins) and the gap between them could be no more than 300 seconds (5 mins). Latest versions appear to have reintroduced this restriction but extended the difference from 300 to 5400 seconds (90mins)

Tested token generation for Teams, Graph and Azure, all created at the same time (16/02/2023 10:51:42 UTC) then checked their expiry times:
Teams Expires On UTC              02/16/2023 12:06:00
Azure Expires On UTC              02/16/2023 12:03:42
Graph Expires On UTC              02/17/2023 10:51:38

As seen above, while the Azure token and Teams token expire within a few minutes of each other (well within 5400 seconds) the Graph token expires after 24 hours, not 1 hour as with the Teams/Azure tokens, so the difference in token expiry is vastly more than 5400 seconds.

The -AccessToken method of connection requires BOTH a Teams token and a Graph token.

Please remove the token expiry time constraint from the connect command again.

**Comment by scanum** [comment]
Hi @ITMonkey78 thanks for your feedback. Could you please help me link the issue you are referring to here? Thanks.

**Comment by ITMonkey78** [comment]
see
https://techcommunity.microsoft.com/t5/teams-developer/authenticating-with-an-access-token-connect-microsoftteams/m-p/2926600/highlight/true#M4182
for details of the original issue. At the time when this was posted (November 2021) the difference required for the two tokens needed to be within 180 seconds. 

The issue has also been previously raised here in github under 
https://github.com/MicrosoftDocs/office-docs-powershell/issues/8623
and
https://github.com/MicrosoftDocs/office-docs-powershell/issues/9188

**Comment by dariomws** [comment]
Hi @ITMonkey78, thank you for submitting feedback. I'll send this information to the product group. Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
