### ISSUE TITLE
52.122.0.0/14 vs. 52.122.0.0/15

### ISSUE THREAD

**Issue by sbenzch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9744]
Hello together

Recently MSFT has changed the media ip subnet which is required for Microsoft 365, Office 365, and Office 365 GCC environments.

But currently documented subnet doesn't matched the specified Ip range:
52.122.0.0/14 (IP addresses from 52.122.0.1 to 52.123.255.254).

Either it's a /15 subnet which would match for the ip addreessed specified, or it's like it was before 52.120.0.0/14.

Thank you for clarification
Simon

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d964547-6b38-cc5f-6b2b-7a50a1c7dae9
* Version Independent ID: fa5850f9-1b92-9727-c344-bcffc227cbd6
* Content: [Plan Direct Routing - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/direct-routing-plan)
* Content Source: [Teams/direct-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @sbenzch, thank you for your feedback.

I have verified and this information is correct:
- 52.112.0.0/14 (IP addresses from 52.112.0.0 to 52.115.255.255).
- 52.120.0.0/14 (IP addresses from 52.120.0.0 to 52.123.255.255).

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
