### ISSUE TITLE
Remote sign in - Better way to sign-in

### ISSUE THREAD

**Issue by yuki-iwagishi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9745]
(Remote sign in and sign out for Teams Android devices)[https://learn.microsoft.com/en-us/microsoftteams/devices/remote-sign-in-and-sign-out?source=docs]

This page Remote Sign-in uses Action Menu. However, Microsoft Teams Room on Android - Touch Console doesn't show this option.
If we clicked devices, then Sign-in link, both Teams Rooms on Android and Touch Console have sign-in options.

There is no Sign-out option on Touch Console, so it's not necessary to update it on Sign-out side.

Current
--
To sign in a device that has been signed out, go to the corresponding device page.

Select the device you want to sign in.

Go to the Actions menu, and select Sign in a user.
--

Suggenstion

To sign in a device that has been signed out, go to the corresponding device page.

Select and click the device you want to sign in.

Go to Sign in a user.

---

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ff0b460-9f13-fefe-37b1-b40d5062fb86
* Version Independent ID: 6ff0b460-9f13-fefe-37b1-b40d5062fb86
* Content: [Remote sign in and sign out for Teams Android devices - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/devices/remote-sign-in-and-sign-out?source=docs)
* Content Source: [Teams/devices/remote-sign-in-and-sign-out.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/remote-sign-in-and-sign-out.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @yuki-iwagishi, thank you for your feedback.

Could you please give me more details? Maybe even some screenshots. My apologies, but I don't understand the improvement you suggest for this article.

Thanks!

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
