### ISSUE TITLE
Blunt statement about WiFi not supported

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9746]
Feedback is around clarity. PG confirmed MTR over WiFi is not supported, however this article uses very soft wording like "_In order to function properly_" or "_Be sure to use a wired 1 Gbps network connection to assure you will have the needed bandwidth_.".

WiFi is not supported and we should provide clarity by stating it clearly in this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a711c07e-10b3-baf0-b92c-9dbcf6ab9474
* Version Independent ID: 2038cd48-44b1-1ed1-6e50-48290eef5605
* Content: [Prepare your Environment - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-prep)
* Content Source: [Teams/rooms/rooms-prep.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-prep.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by pvernocchi** [comment]
I've submitted the following changes: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/9748
