### ISSUE TITLE
Clarity needed on compliance recording

### ISSUE THREAD

**Issue by dipinn26592** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9750]
" If your organization uses compliance recording, end-to-end encryption isn't available. For more info on how Teams supports compliance recording, see [Introduction to Teams policy-based recording for callings & meetings](https://learn.microsoft.com/en-us/microsoftteams/teams-recording-policy). "

The above description implies that e2ee is not available at all for the tenant if CR is enabled.. However the description should say CR won't work if the meeting is e2ee 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b601b72a-bcaa-2afd-22f7-8123856d2a97
* Version Independent ID: b601b72a-bcaa-2afd-22f7-8123856d2a97
* Content: [Require end-to-end encryption for sensitive Teams meetings - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/end-to-end-encrypted-meetings)
* Content Source: [Teams/end-to-end-encrypted-meetings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/end-to-end-encrypted-meetings.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by pvernocchi** [comment]
The published document seems correct. If an organization use Compliance Recording, E2EE will be disabled as CR prevails over E2EE. Perhaps the confusion is with regular meeting recordings?
It is also described in: https://support.microsoft.com/en-gb/office/use-end-to-end-encryption-for-teams-calls-1274b4d2-b5c5-4b24-a376-606fa6728a90

**Comment by dipinn26592** [comment]
Tagging ***@***.***> - Feature PM for E2EE recording to help with the correct wordings.

Based on the current wording it looks like if the customer is using compliance recording for even few users ( e.g. support agents ) E2EE as a feature will be disabled for the entire organization. Which does not seem correct.

Only the session where CR is enabled E2EE should not work. i.e for support agents the E2EE wont work, but for the other users E2EE can be enabled.

@***@***.***> can keep me honest on the above assumption.

Regards,
Dipin Nair

**Comment by pvernocchi** [comment]
Agreed! That's the clarification I was also thinking about :)

**Comment by dipinn26592** [comment]
Hi @***@***.***>,

Yes, only users who need compliance recording for them E2EE calls should be disabled but not for everyone in the tenant.

Is there a BrB that I can share with the devs for E2EE.

Thanks,
Maryam

From: Dipin Nair ***@***.***>
Sent: Tuesday, February 21, 2023 12:41 AM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>; MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>; Maryam Ahmad ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Clarity needed on compliance recording (Issue #9750)

Tagging ***@***.***> - Feature PM for E2EE recording to help with the correct wordings.

Based on the current wording it looks like if the customer is using compliance recording for even few users ( e.g. support agents ) E2EE as a feature will be disabled for the entire organization. Which does not seem correct.

Only the session where CR is enabled E2EE should not work. i.e for support agents the E2EE wont work, but for the other users E2EE can be enabled.

@***@***.***> can keep me honest on the above assumption.

Regards,
Dipin Nair

**Comment by dipinn26592** [comment]
Thanks Mayram, As compliance recording is a paid partner solution I don't have that set up in my test tenants. I will ask in the team if they have access, if so will file a BRB and share it here.

Regards,
Dipin Nair

From: Maryam Ahmad ***@***.***>
Sent: Tuesday, February 21, 2023 11:24 PM
To: Dipin Nair ***@***.***>; MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>; MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Clarity needed on compliance recording (Issue #9750)

Hi @***@***.***>,

Yes, only users who need compliance recording for them E2EE calls should be disabled but not for everyone in the tenant.

Is there a BrB that I can share with the devs for E2EE.

Thanks,
Maryam

From: Dipin Nair ***@***.******@***.***>>
Sent: Tuesday, February 21, 2023 12:41 AM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.******@***.***>>; MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.******@***.***>>; Maryam Ahmad ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>
Subject: RE: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Clarity needed on compliance recording (Issue #9750)

Tagging ***@***.***> - Feature PM for E2EE recording to help with the correct wordings.

Based on the current wording it looks like if the customer is using compliance recording for even few users ( e.g. support agents ) E2EE as a feature will be disabled for the entire organization. Which does not seem correct.

Only the session where CR is enabled E2EE should not work. i.e for support agents the E2EE wont work, but for the other users E2EE can be enabled.

@***@***.***> can keep me honest on the above assumption.

Regards,
Dipin Nair

**Comment by get-itips** [comment]
Thanks for your feedback
