### ISSUE TITLE
Documentation includes powershell script using deprecated cmdlets

### ISSUE THREAD

**Issue by MSPscripts** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9757]
The APIs allowing for license assignment using the MSOL and AzureAD powershell modules was deprecated last year. The powershell script in this "how to" includes the non-functional Set-AzureADUserLicense cmdlet. The script needs to be updated to use Graph, or maybe you guys can have the other team turn the API back on.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1078d9f1-e4d6-3a99-aa73-bb2740436528
* Version Independent ID: 1078d9f1-e4d6-3a99-aa73-bb2740436528
* Content: [Move from Business Voice to Teams Phone licenses - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/business-voice-to-teams-phone-licenses?tabs=powershell)
* Content Source: [Teams/business-voice-to-teams-phone-licenses.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/business-voice-to-teams-phone-licenses.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by get-itips** [comment]
Hello @MSPscripts 
I was able to notify the Docs team about this and they'll work on updating the script.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by MSPscripts** [comment]
Unless I'm missing something, I don't see any changes to the script - it's still referencing a cmdlet that is non-functional (Set-AzureADUserLicense).

**Comment by DaniEASmith** [comment]
@MSPscripts That's because the doc isn't updated yet. We're in the process of working with the engineer to rewrite the instructions with the Graph cmdlets. The updated doc probably won't go live until early April.
