### ISSUE TITLE
Check in and room release config options

### ISSUE THREAD

**Issue by pvernocchi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9758]
Check in and room release can be configured at the device level or with a Configuration Profile applied to 1 or multiple devices.
We should add the configuration profile documentation as well, otherwise it gives the impression that this feature needs to be configured device by device.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43db7773-69d4-9777-b202-e7cc3a942e6a
* Version Independent ID: 43db7773-69d4-9777-b202-e7cc3a942e6a
* Content: [Check-in and room release on Microsoft Teams panels - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/devices/check-in-and-room-release)
* Content Source: [Teams/devices/check-in-and-room-release.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/check-in-and-room-release.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Thanks for your feedback @pvernocchi
