### ISSUE TITLE
CsTeamsMeetingBrandingPolicy cmdlets not documented

### ISSUE THREAD

**Issue by thewrabbit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9760]
Release notes for Teams PowerShell Module 4.9.3 .
Releases [Get|Set|Grant|Remove|New]-CsTeamsMeetingBrandingPolicy cmdlets.

There is no documentation on this policy.  It seems to be related to Teams Premium, but there is no explanation as to what the parameters configure.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 173b5929-529b-938b-b6ab-59f05a5d69a8
* Version Independent ID: 0a3dfe5e-938f-933d-637e-b7449e3b8aa5
* Content: [Microsoft Teams PowerShell Release Notes - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes)
* Content Source: [Teams/teams-powershell-release-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-release-notes.md)
* Service: **msteams**
* GitHub Login: @sumitb18
* Microsoft Alias: **subadjat**

**Comment by dariomws** [comment]
Hi @thewrabbit, thank you for your feedback.

I have verified, and the documentation for those cmdlets is in progress and is expected to be published shortly.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
