### ISSUE TITLE
Users no longer must be signed on to comment or annotate

### ISSUE THREAD

**Issue by JorgeALeitao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9762]
[Enter feedback here]

At the beginning of this article, it says "Users can also comment on and annotate the PDF files for free after they sign in" however with the recent launch of V2.0.1 users no longer must be signed on to comment or annotate.

Please could you update the article?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e4c946e-ec50-995e-87ec-4de4ec9009fd
* Version Independent ID: 6e4c946e-ec50-995e-87ec-4de4ec9009fd
* Content: [Adobe Acrobat as a default PDF viewer in Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/adobe-acrobat-pdf-viewer-teams)
* Content Source: [Teams/adobe-acrobat-pdf-viewer-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/adobe-acrobat-pdf-viewer-teams.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by ashishguptaiitb** [comment]
Hi @JorgeALeitao , after our internal discussion, shall we close this issue as not to be documented?

**Comment by JorgeALeitao** [comment]
Hi Ashish, yes, I think we better close it for now and wait until April when the update version comes out.

Jorge
