### ISSUE TITLE
Wrong place to purchase licenses. 

### ISSUE THREAD

**Issue by bwjohnson207** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9764]
[Enter feedback here]
The page tells you to purchase licenses under billing->purchase services but it should be under the marketplace now which isn't under billing.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b79d13d8-9f2e-ef35-0459-c3430e5b05a7
* Version Independent ID: b79d13d8-9f2e-ef35-0459-c3430e5b05a7
* Content: [Step 1 - Purchase a license for the Teams Rooms console - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/hybrid-meetings-device-config-license?source=recommendations)
* Content Source: [Teams/hybrid-meetings-device-config-license.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hybrid-meetings-device-config-license.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @bwjohnson207, thank you for your feedback.

I think it's still the place to buy Teams Room licences:
![image](https://user-images.githubusercontent.com/33589238/227189891-5ce6bce9-72e0-495b-90f3-30c62347e6ea.png)

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
