### ISSUE TITLE
License requirement of Microsoft Teams Display

### ISSUE THREAD

**Issue by yuki-iwagishi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9766]
https://learn.microsoft.com/en-us/microsoftteams/devices/plan-device-deployment#task-2-what-are-your-licensing-requirements

>For phones and displays, the applicable licenses are the Microsoft Teams Shared Devices license and a **Microsoft Teams Rooms license.**

In my understanding, Teams Display only supports Microsoft Teams Shared Devices license. so better to remove "and a **Microsoft Teams Rooms license.**" in this section.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1942afa4-ed7f-8e8c-4dc7-eff2720c5cda
* Version Independent ID: 1942afa4-ed7f-8e8c-4dc7-eff2720c5cda
* Content: [Plan your deployment for Teams phone devices and Displays - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/devices/plan-device-deployment)
* Content Source: [Teams/devices/plan-device-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/plan-device-deployment.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
