### ISSUE TITLE
useless. nothign on this page is on the screen for me. no help at all

### ISSUE THREAD

**Issue by CanadianThomas** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9771]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2465e854-e3b1-6bd0-c834-c696121e857a
* Version Independent ID: 6b225ed2-0cd3-b3c3-0e3a-d7ce98031e16
* Content: [Broadcast meeting content - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/use-ndi-in-meetings)
* Content Source: [Teams/use-NDI-in-meetings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/use-NDI-in-meetings.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
