### ISSUE TITLE
Teams for Linux not found .deb is missing also

### ISSUE THREAD

**Issue by eugenevdm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9772]
The  page refers to downloading teams from a website or using `apt`, but actually all the files refer to something that does not exist. E.g. 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c86f401-cff4-93b3-ff69-b9787a87e644
* Version Independent ID: c0808bd3-cf63-0625-4c3c-65469c26fb3e
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/get-clients?tabs=Windows)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
The Linux client is not available anymore and the article was updated recently. Thank you for your feedback
