### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by jonnyc109** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9774]
The "Chat in meetings" section has some typos.

in the settings table, I believe the 2nd row setting value should be "**OFF** for everyone" instead of "On"

The under the table there's a couple of examples.  The first one states "if the Organizer has Chat in meetings set to On for everyone, or On for everyone but anonymous users, then a user's individual policy will apply and any users with On for everyone set won't be able to chat in the meetings.

This can't be right?  Why would a user policy ever apply over the organizer policy?  And if the user has it set to on for everyone why would chat be disabled for everyone.

The second bullet should read if the organizer has it set to "OFF for everyone"?

**Comment by scanum** [comment]
Hi @jonnyc109 Thanks for the feedback. Could you please help us link the article you are refering to?

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
