### ISSUE TITLE
Should Specify MTR Platform

### ISSUE THREAD

**Issue by jpalarchio** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9775]
I believe this only applies to MTRoW (MTR on Windows).  We should probably clarify that.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94992f4d-eb18-400e-5979-5301f9b4a6d7
* Version Independent ID: 403c8366-9324-cf9e-332a-f55a554375dd
* Content: [Set up coordinated meetings with Microsoft Teams Rooms and Surface Hub - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/coordinated-meetings)
* Content Source: [Teams/rooms/coordinated-meetings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/coordinated-meetings.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Thanks for your feedback, fixed in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/aada4c0a94862f9f96686158bd59955a1de9fc88
