### ISSUE TITLE
"Allow registered users to bypass the lobby" is not yet available

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9782]
The "Allow registered users to bypass the lobby" is not available yet. Please update the table with annotation "coming soon" for this item. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c100aa6e-f8a3-053f-f5c6-d3e543dea5a0
* Version Independent ID: c100aa6e-f8a3-053f-f5c6-d3e543dea5a0
* Content: [Microsoft Teams Premium licensing - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/licensing-enhance-teams)
* Content Source: [Teams/teams-add-on-licensing/licensing-enhance-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/licensing-enhance-teams.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@Larryngolog, I spoke with the product owner of this feature, and she stated that "Allow registered users to bypass the lobby" is mostly generally available, but they moved it out of Teams Premium. It is now a part of Teams core. I have updated the article to indicate as such.

@scanum

**Comment by scanum** [comment]
Thank you @DaniEASmith!

@Larryngolog Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
