### ISSUE TITLE
We can't upload the app because there's already an app in the catalog with the same app ID. To upload a new app, change the app ID and try again. To update an existing app, go to the app details page

### ISSUE THREAD

**Issue by JamaliShoaib** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9783]
All I followed the whole procedure by registering applications and their App ID and Secret ID and completed azure step.
But unfortunately once i try to upload on teams it is throwing error "We can't upload the app because there's already an app in the catalog with the same app ID. To upload a new app, change the app ID and try again. To update an existing app, go to the app details page"

<img width="455" alt="CaptureError3" src="https://user-images.githubusercontent.com/29330750/223043483-436f8282-2f27-4d94-9eea-b94f7e5588fb.PNG">

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
