### ISSUE TITLE
Definition for Last Activity Date is missing in the Teams Usage Document

### ISSUE THREAD

**Issue by wizneeraj** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9784]
Hi Team,

I noticed that the page does not define what constitutes to the Last Activity Date column in the Teams Usage Report Table. Please add the definition so that we know if includes only the activity done on the Teams or on the SharePoint site belonging to the Team as well.

Thanks,
Neeraj

**Comment by scanum** [comment]
Hi @wizneeraj hope all is well and thanks for the feedback. Could you please help me by linking the article you are referring to?

**Comment by wizneeraj** [comment]
@scanum - Apologies for the delay. Here is the [link](https://learn.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-usage-report). 

![image](https://user-images.githubusercontent.com/19283398/226906541-bae51ea8-960f-4c13-ba25-01b7a94d17b3.png)

**Comment by wizneeraj** [comment]
@MikePlumleyMSFT - Thanks for updating the documentation. Does it consider the activity within Teams only and not on the SharePoint site connected to the Team?
