### ISSUE TITLE
Wrong information in the line "Sign in to Graph Explorer on the left menu"

### ISSUE THREAD

**Issue by RipRapRob** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9785]
You sign in to Graph Explorer on the **top right**.

Also, please ad information on where to find the GroupID (I found it by selecting 'Microsoft Teams' in the left menu, and then 'GET my joined teams' where I found the ID.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b51b67a-d89c-723f-3520-87cb2dc93b90
* Version Independent ID: 78d10cbc-d75b-2b02-d49c-2c3fe1579807
* Content: [Manage teams in the Microsoft Teams admin center - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-teams-in-modern-portal)
* Content Source: [Teams/manage-teams-in-modern-portal.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-teams-in-modern-portal.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @RipRapRob, thank you for your feedback.

I'm updating the step to sign in in Graph explorer. Related to your 2nd concern, we can find the following sentence in the article:
"Replace {groupid} in the Query for the actual GroupId in question, which you can get via the Exchange Online PowerShell, with the "Get-UnifiedGroup" cmdlet, as the "ExternalDirectoryObjectId" attribute."
