### ISSUE TITLE
Missed some features in this section: Are there current Teams features that will move to Teams Premium?

### ISSUE THREAD

**Issue by rillc-orion** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9787]
Teams Organizational Backgrounds was removed from Teams Core functionality and added as a Teams premium feature. This should have been included in the section about "Are there current Teams features that will move to Teams Premium?"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c100aa6e-f8a3-053f-f5c6-d3e543dea5a0
* Version Independent ID: c100aa6e-f8a3-053f-f5c6-d3e543dea5a0
* Content: [Microsoft Teams Premium licensing - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/licensing-enhance-teams)
* Content Source: [Teams/teams-add-on-licensing/licensing-enhance-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/licensing-enhance-teams.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@rillc-orion 
Not including Org-defined backgrounds in the feature take-back section was intentional. That feature was actually only available in Teams core as a free public preview of a Teams Premium feature, so it's technically not a Teams core take-back feature.

cc: @scanum

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
