### ISSUE TITLE
Hybrid application endpoint - Unclear step 

### ISSUE THREAD

**Issue by PieDamen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9790]
Step 3 in Migrate hybrid application endpoints from on-prem to online states the following:

Associate the new Resource Accounts with the existing hybrid application endpoints.

how do you associate these? is there a command for this or something?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
