### ISSUE TITLE
Clarify resource account Caller ID substitution

### ISSUE THREAD

**Issue by JMCA2** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9793]
In both this page and https://learn.microsoft.com/en-us/microsoftteams/how-can-caller-id-be-used-in-your-organization

**it should be clarified if a calling plan is required to be assigned to the resource account when used for Caller ID Replacement.**

For the option to make calls "on behalf of" as described on https://learn.microsoft.com/en-us/microsoftteams/plan-auto-attendant-call-queue#prerequisites it says it is required.

But it's not clear if using global Caller ID substitution required the resource account to have a calling plan assigned or not. On my tenant, resource accounts without calling plan show up as options you can select for Caller ID policy.

**When using this feature are minutes taken from the resource account assigned plan (if any) or the user making the call?**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2b8aefb-f373-fa6e-dd79-e97cded117e8
* Version Independent ID: 2c73f49c-d34f-c1da-648d-8675f10c0183
* Content: [Manage caller ID policies for users - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/caller-id-policies)
* Content Source: [Teams/caller-id-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/caller-id-policies.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @JMCA2, thank you for your feedback.

The actual caller requires a calling plan (or other option) and is charged for the minutes. If it isn't and there is a global caller id policy to replace caller ID for everyone, then all minutes will be charged to the resource account, which doesn't make sense.

I hope this helps you to clarify this concern.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
