### ISSUE TITLE
Clarification requested on App validation check note

### ISSUE THREAD

**Issue by tinsheep** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9800]
Clarification requested:
"Note
Validation and checks by Microsoft are not available for a custom app as it is developed within your organization and is only available to members of your organization."
Can you clarify that this would also apply to custom apps sideloaded to customer tenants? (not in the store) 
thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 667936ab-077e-3bdb-679e-9f0e487f5c8c
* Version Independent ID: 667936ab-077e-3bdb-679e-9f0e487f5c8c
* Content: [Overview of app validation and app testing by Microsoft - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/overview-of-app-validation)
* Content Source: [Teams/overview-of-app-validation.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/overview-of-app-validation.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by tinsheep** [comment]
Meaning - An ISV has developed and app and it is sideloaded to several customer tenants - one of the customers is requesting validation checks. I assume from the note that it must be submitted to the store but it would help to have some additional clarification as it may is available to members outside of the app creators organization. thanks.

**Comment by ashishguptaiitb** [comment]
Hi @dariomws and @scanum , I am taking this up internally with the help of PMs. If you have content to share, please do. Otherwise, I am happy to take it fwd. (and doing so anyway). Great feedback @tinsheep .

**Comment by ashishguptaiitb** [comment]
Getting the updated doc published tonight.

**Comment by ashishguptaiitb** [comment]
Thanks @tinsheep . [The article](https://learn.microsoft.com/microsoftteams/overview-of-app-validation) is now updated. Let me know if this helps.

**Comment by tinsheep** [comment]
[like]  Michael Panciroli reacted to your message:
________________________________
