### ISSUE TITLE
Debian Teams Package not available

### ISSUE THREAD

**Issue by etellier** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9804]
The Debian Teams client package isn't available in repo  
https://packages.microsoft.com/repos/ms-teams

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c86f401-cff4-93b3-ff69-b9787a87e644
* Version Independent ID: c0808bd3-cf63-0625-4c3c-65469c26fb3e
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/get-clients?tabs=Linux)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @etellier, thank you for your feedback.

The Teams Linux client was retired in December. It was announced in the Microsoft 365 message center notification MC412007 in late August.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
