### ISSUE TITLE
Vague Wording on Availability

### ISSUE THREAD

**Issue by jpalarchio** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9805]
I have had multiple people struggle over the years with this line: "Only available through SoftBank for Japanese-based tenants."

Some read it as "If you have a Japan-based tenant, Calling Plans are available through SoftBank but if your tenant is based elsewhere, there is another option".  My understanding is that there is no other option.

Perhaps it would be more clear if it was worded something like "Only available for Japan-based tenants, those customers must purchase direct from SoftBank".  ...or something similar.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a26806ae-7525-7416-4b49-5ba49f563192
* Version Independent ID: eab3a3ee-deb6-3761-008b-cdd22e586176
* Content: [Availability in Japan - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-japan)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-japan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-japan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
@CarolynRowe,

It seems that we don't have permission to update these articles anymore. Could you check? Thanks!

**Comment by CarolynRowe** [comment]
Hmmmm....   We recently transferred ownership of all availabiity articles to the product team.  But I think this is a question for @dstrome .  David:  are the PubOps team still supposed to have access?

**Comment by CarolynRowe** [comment]
Also copying @pthakkar230

**Comment by simonibssa** [comment]
Hi all,

The suggested change is an accurate fix. I've created a PR to update this, should be approved once @pthakkar230 gets a chance to see it.

**Comment by simonibssa** [comment]
Change is live.

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
