### ISSUE TITLE
UK Calling Plans

### ISSUE THREAD

**Issue by leefai** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9807]
Under section for UK and Calling plans https://learn.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-kingdom-u-k#calling-plans  we have a 240 min domestic calling plan listed , my understanding is that plan was retired and no longer available to purchase?

Has this page been missed / not updated or have I misunderstood? The internal pricing tool does not have the 240 min SKU listed anymore, so assuming the pages been missed or not updated in line?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
