### ISSUE TITLE
Note in Allow custom background settings wrong

### ISSUE THREAD

**Issue by OtherPlans** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9814]
The note section in [Allow custom background settings](https://learn.microsoft.com/en-us/microsoftteams/meeting-policies-audio-and-video#allow-custom-background-settings) states that 'the admin account that you use to do this procedure must have a Teams license'. However, this does not appear to be true, as my account cannot make any hanges on this page, despite being a Global admin and having a Teams license via E5.

Perhaps this actually requires that the admin have a Teams Premium license?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5d3a28c-7a66-831f-e610-9bf7d4edf9eb
* Version Independent ID: 0bc4a251-816e-0d77-efb2-53b7ffccb0f5
* Content: [Manage meeting policies for audio and video - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/meeting-policies-audio-and-video#manage-audiovideo-for-meeting-participants)
* Content Source: [Teams/meeting-policies-audio-and-video.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-audio-and-video.md)
* Service: **msteams**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by dariomws** [comment]
Hi @OtherPlans, thank you for your feedback.

My apologies but I cannot the note and the section that you are referring to. Could you provide more detail or double-check the article? Maybe it was removed.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
