### ISSUE TITLE
Please review "Open the following IP addresses" section

### ISSUE THREAD

**Issue by davidjfriedman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9816]
Please review the following section:

-snip-
Open the following IP addresses:

13.75.175.145
52.189.219.201
51.124.34.164
13.74.250.91
13.83.55.36
23.96.103.40
-snip-

I believe we might need to provide more specific guidance, such as to open them up for HTTPS.

Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 05173ea8-db7c-a20d-3783-178b3d649190
* Version Independent ID: 05173ea8-db7c-a20d-3783-178b3d649190
* Content: [Configure SIP Gateway - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/sip-gateway-configure)
* Content Source: [Teams/sip-gateway-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sip-gateway-configure.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @davidjfriedman, thank you for your feedback.

I have proposed an update to include that information, you can check it here:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/9635/files
