### ISSUE TITLE
Teams Premium Takeback Preview Features

### ISSUE THREAD

**Issue by mwe-microsoft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9820]
From my perspective all the tookback features of Teams Premium as stated here:

https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/licensing-enhance-teams#are-there-current-teams-features-that-will-move-to-teams-premium

were in preview when Teams Premium was announced or we already announced that these features will be premium in the future.

There is a gap of a few days at life translation captions between GA and the announcement that it is going to Teams Premium. 

Why don't we make it clear in the documentation? Customers are now complaining, that we are not allowed to takeback feature during a running contract. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c100aa6e-f8a3-053f-f5c6-d3e543dea5a0
* Version Independent ID: c100aa6e-f8a3-053f-f5c6-d3e543dea5a0
* Content: [Microsoft Teams Premium licensing - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/licensing-enhance-teams)
* Content Source: [Teams/teams-add-on-licensing/licensing-enhance-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/licensing-enhance-teams.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@mwe-microsoft The decision to not include that information was intentional from the marketing team to not "open a can of worms" so to speak. As the doc stands, the take-back features listed and the language used is approved by Microsoft marketing, Business Planning, and CELA.

**Comment by mwe-microsoft** [comment]
OK and do you know if we have some kind of a written customer-ready statement?

From my perspective the current statement on the documentation open Pandora's box, with the preview state, we would be totally fine.

!!! I live in Teams and don't check email in time!  ***@***.***>
If this needs my attention right away hit this link to chat with me in Teams ***@***.***>

Mit freundlichen Grüßen / Best Regards

Marcel Weißkirchen

Teams Technical Specialist
Specialist Team Unit

Office:   +49 221 8010 2078
Mobile:  +49 151 44 01 27 35
Email: ***@***.******@***.***>
IM: ***@***.******@***.***>
***@***.***<https://twitter.com/microsoft>   ***@***.*** <https://www.facebook.com/Microsoft>    ***@***.*** <https://www.linkedin.com/company/microsoft>    ***@***.*** <https://www.youtube.com/user/Microsoft>    ***@***.*** <https://www.yammer.com/>
[MSFT_logo_Gray DE sized SIG1.png]



Microsoft Deutschland GmbH
Walter-Gropius-Straße 5, 80807 München
Microsoft - Official Home Page<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fde-de%3Fql%3D2&data=04%7C01%7Cmarcel.weisskirchen%40microsoft.com%7C1e891cd528d240528e4f08d8e4711765%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637510522654089654%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cd3ZyzPCjncO8HPOJqRcoSIImhsdklPdAe4W34zXZC8%3D&reserved=0>
Home | News Center Microsoft<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnews.microsoft.com%2Fde-de%2F&data=04%7C01%7Cmarcel.weisskirchen%40microsoft.com%7C1e891cd528d240528e4f08d8e4711765%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637510522654089654%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=W7hI%2B%2BYrG8i5kqQXcRItPLwgBpxdzuJyswKPRRYe2GY%3D&reserved=0>
Datenschutzerklärung von Microsoft - Microsoft-Datenschutz<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprivacy.microsoft.com%2Fde-DE%2Fprivacystatement&data=04%7C01%7Cmarcel.weisskirchen%40microsoft.com%7C1e891cd528d240528e4f08d8e4711765%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637510522654099605%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3h7DVI5FjQ1w1%2FsOLSfsCVktNn3ML%2FKcxMMFZ7PWEWg%3D&reserved=0>

Geschäftsführer*in: Dr. Marianne Janik (Vorsitzende), Florian Deter, Benjamin O. Orndorff, Keith Dolliver | Amtsgericht München, HRB 70438

Von: Dani Smith ***@***.***>
Gesendet: Mittwoch, 15. März 2023 16:01
An: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Marcel Weisskirchen ***@***.***>; Mention ***@***.***>
Betreff: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Teams Premium Takeback Preview Features (Issue #9820)


@mwe-microsoft<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmwe-microsoft&data=05%7C01%7Cmarcel.weisskirchen%40microsoft.com%7Cb3125c15298242f3963708db25661685%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638144892631624009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HksBvzAvGror3cjz8HT97HM3JeNz2l8n7uM6bJa4JPs%3D&reserved=0> The decision to not include that information was intentional from the marketing team to not "open a can of worms" so to speak. As the doc stands, the take-back features listed and the language used is approved by Microsoft marketing, Business Planning, and CELA.

-

**Comment by DaniEASmith** [comment]
Closing as internal submitter is discussing with marketing now.
