### ISSUE TITLE
Missing Version 4.16

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9824]
Seems that the update 4.16 mentioned in MC516349 is still missing there in description of new features, fixes, and changes after release.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1365f9b8-001c-daa7-592e-d88b9bb3a10e
* Version Independent ID: ffba1b4d-1f19-4dac-0b55-053d98fe26b7
* Content: [Release notes for Microsoft Teams Rooms (Windows) - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-release-note)
* Content Source: [Teams/rooms/rooms-release-note.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-release-note.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Version is already in the article, thanks for your feedback.
