### ISSUE TITLE
Port 80 can also be used

### ISSUE THREAD

**Issue by DarCampbell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9825]
We have a note that says" All network traffic between the MTR devices agent and the Microsoft Teams Rooms Pro Management portal is SSL over port 443*.* See [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise | Microsoft Docs](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide&preserve-view=true)." but port 80 is also used and should be noted. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 926bcf08-5326-ed74-8170-14b46fd5ade7
* Version Independent ID: 926bcf08-5326-ed74-8170-14b46fd5ade7
* Content: [Enroll a Teams Room device into Pro Management - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/enroll-a-device)
* Content Source: [Teams/rooms/enroll-a-device.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/enroll-a-device.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @altsou
* Microsoft Alias: **altsou**

**Comment by get-itips** [comment]
Hello @DarCampbell Darlisha, how are you?
While I try to dig into this, can you please provide more detail that can help me provide to the product team so I can adjust the documentation? In which situation did you see traffic against TCP 80 and against which endpoint? I appreciate it.

**Comment by get-itips** [comment]
Closing for now, it can be re-opened if issue raiser comes back with more information. @scanum
