### ISSUE TITLE
What happens when no menu input from user?

### ISSUE THREAD

**Issue by EndlessxWaltz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9826]
It doesn't mention what happens when the user does not input anything into the Auto-Attendant Menu. What happens? Also how long does it take before this happens?

Can any of the parameters be modified?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a9ee465f-fae3-0ea0-bdf3-f7b8c3d91709
* Version Independent ID: a9ee465f-fae3-0ea0-bdf3-f7b8c3d91709
* Content: [Set up an auto attendant for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/create-a-phone-system-auto-attendant-experiment?source=recommendations)
* Content Source: [Teams/create-a-phone-system-auto-attendant-experiment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-a-phone-system-auto-attendant-experiment.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
