### ISSUE TITLE
Don't make it hard for your customers to buy from you

### ISSUE THREAD

**Issue by SomeoneElseOSM** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9828]
The process to add a dial-in number to Teams leads through this page.
Much of what is here is completely inappropriate (e.g. "use powershell").
Just tell us which buttons to click in which MS 365 Admin Centre.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed46e6b1-48c5-5302-2f38-89c315d4bff7
* Version Independent ID: 81053999-79ca-888d-38fa-8978276b6228
* Content: [Assign Teams add-on licenses to users - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/assign-teams-add-on-licenses)
* Content Source: [Teams/teams-add-on-licensing/assign-teams-add-on-licenses.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/assign-teams-add-on-licenses.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by SomeoneElseOSM** [comment]
Thanks - https://learn.microsoft.com/en-us/microsoft-365/admin/manage/assign-licenses-to-users?view=o365-worldwide was one of the places that I looked, but that rather assumes that (a) I know that some extra licences are required and (b) I know what extra licences are required.  I know neither of those things, and therefore that page isn't especially helpful.  I've logged a case with Microsoft to try and get that resolved, but thought that it was helpful to provide direct feedback on this page too.

To be clear - we're a Microsoft 365 customer, and our licences (different "Business" versions for different users) already include Teams.

**Comment by DaniEASmith** [comment]
@SomeoneElseOSM Can you reference a specific paragraph or section of the article(s) that is causing confusion or difficulty?

**Comment by SomeoneElseOSM** [comment]
> Use the term "buy" instead of "add" when referring to purchasing.

Yes, that would definitely help!

> those are the only 2 that transferred to my ownership.

Understood.  

Hopefully the case I have open separately will answer the questions "what do we need to buy and how do we do that".

**Comment by DaniEASmith** [comment]
@SomeoneElseOSM  These updates will be published today.
