### ISSUE TITLE
How does this fit in the strategy of using Yammer for enterprise-wide (broad) communication?

### ISSUE THREAD

**Issue by bartbilliet** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#983]
At Ignite the strategy for communication & collaboration was described where Teams was meant for focused team-based collaboration, whereas Yammer is in the picture for broader enterprise-wide communication. 
Since we can now create org-wide teams in Microsoft Teams, how does this feature fit in this strategy? There seems to be an overlap? Does it change the recommended approach of when to use Teams & when to use Yammer? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by AndreaBarr** [comment]
@bartbilliet Thank you for this inquiry

I am not sure how this new feature fits in with this stratagy. Let me get this over to the Teams/Skype for Business team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by tophee** [comment]
The relationship between Yammer and Teams is also causing me some head-aches. Currently, the maximum number of members for a team is 2500 (while the maximum number of members for an org-wide team is 1000???, see: https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams). So, it seems to me that the main reason to start using Yammer today is that your organization is too big for org-wide teams. And this, honestly, makes no sense to me. Why such a low limit? I'd be curious to know a) whether there are any concrete plans for significantly increasing the maximum membership limit in the near future, and b) whether there is any on-premise workaround for that limitation that would allow a large organization to create larger teams?

**Comment by PhilFancy** [comment]
@tophee - see your link, Microsoft has increased the maximum org-wide team size from 1000 to 2500 members!

**Comment by tophee** [comment]
@PhilFancy Thanks for pointing that out. Unfortunately, it's still far from what we would need. So my question remains: why such a low limit?

**Comment by bartbilliet** [comment]
Re-opening: The question on how org-wide teams relates to the strategy with Yammer for enterprise-wide communications (=topic starter) was not answered. We are still waiting feedback on this.

**Comment by jamiekt** [comment]
I agree with @bartbilliet, the question at the top of this thread "How does this fit in the strategy of using Yammer for enterprise-wide communication" has not been answered. 

There is now, very clearly, an overlap between org-wide teams and Yammer (this seems to be endemic in Office 365, see SharePoint & OneDrive for another example). The "inner-loop" versus "outer-loop" rubbish is just marketing spin for the fact that (for legitimate historical reasons) there are two products that have considerable overlap.

Surely the time has come to simply turn Yammer off?

* inner-loop vs outer-loop : https://techcommunity.microsoft.com/t5/Community-Management/We-took-the-Inner-Loop-and-Outer-Loop-visual-a-little-further/td-p/123178

**Comment by yogkumgit** [comment]
@bartbilliet   Thank you very much for your kind feedback. Considering your valuable feedback, we have logged this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule.  You can create your own user voice also. Thanks again for taking out some time and sharing your feedback.

User Voice Link: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/33863491-need-to-be-able-to-add-a-disclaimer-for-the-use-of
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/19515259-merge-outlook-groups-skype-for-business-and-yamme

**Comment by sdecker** [comment]
We've turned off Yammer as it serves no value in our organization with everyone using Teams. MS needs to help organizations reduce collections points users have to poll for information rather than maintaining an ever growing number of services.
