### ISSUE TITLE
Feedback in Teams

### ISSUE THREAD

**Issue by JDCNS** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9830]
[Enter feedback here]
"Feedback policies aren't available in GCC, GCC High, or DOD deployments."

Apparently, feedback itself is not available either. More deafness from big tech.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1bf3bc26-4cac-56c0-8669-6540adf3c502
* Version Independent ID: bd7cd483-e40e-88c2-b9ee-b21a9ea73005
* Content: [Manage feedback policies in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-feedback-policies-in-teams)
* Content Source: [Teams/manage-feedback-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-feedback-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @JDCNS, thank you for your feedback.

What is the improvement that you are suggesting in the article? Could you provide more detail? Thanks!

**Comment by AReplikaLover** [comment]
Make it easier to provide feedback. Government users should not be excluded from providing feedback on any program, but especially one that is high use and high in issues.

**Comment by JDCNS** [comment]
It should be easier for government users to provide feedback. Government entities are paying for the product as well. The article I quoted shows that the feedback option isn't even available to GCC customers.

**Comment by dariomws** [comment]
@JDCNS - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make Microsoft products better. They keep a close tab on user feedback and it would be awesome if you could add your voice to the Microsoft Feedback Portal: https://feedbackportal.microsoft.com/feedback/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to making the docs better! Much appreciated!

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by dariomws** [comment]
@JDCNS, feedback is coming to GCC:
https://www.microsoft.com/microsoft-365/roadmap?featureid=123972

**Comment by JDCNS** [comment]
This is good news, indeed! Thanks for the followup!
