### ISSUE TITLE
Include Intune steps.

### ISSUE THREAD

**Issue by lee-halford** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9832]
Can you expand this page to include the steps for setting up an Intune policy as well as the GPO?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd90fec-827b-5b36-8576-5ae38b33e455
* Version Independent ID: 85815d3e-7796-b92d-fc3e-2d5c14743010
* Content: [Implement Quality of Service (QoS) in Microsoft Teams clients - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/qos-in-teams-clients)
* Content Source: [Teams/QoS-in-Teams-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/QoS-in-Teams-clients.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by bbriggs00** [comment]
Leave me the fuck alone !!!!

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by traya1** [comment]
Hi @bbriggs00 - You need to update your notification settings. The below link will provide the information you need to do that.

https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/about-notifications

If the above does not help/work, contact GitHub support and they should be able to help you with any notification issues you are experiencing.

Thanks!

**Comment by get-itips** [comment]
Hello @lee-halford Lee,
While I dig if the same procedure works for General Windows devices, have you seen 

https://learn.microsoft.com/en-us/surface-hub/manage-settings-with-mdm-for-surface-hub

**Comment by lee-halford** [comment]
Hello @get-itips,
That does look mighty close to what you could do, I assume you would use a custom policy. 
In future will Teams settings be added to the Office 365 Policy Management?

**Comment by get-itips** [comment]
I'm sorry don't have precision if those settings will be added to policy management.
Let me know if you'll try that procedure.
Thank you

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
