### ISSUE TITLE
Retention Policies and private channels

### ISSUE THREAD

**Issue by kpinel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9835]
Where retention policies have been applied to SharePoint, the site linked to the private channel needs to be exempt from those policies before the channel can be deleted.

This isn't obvious with an error message that simply says that the channel couldn't be deleted and to try again.
![image](https://user-images.githubusercontent.com/875143/226513295-9175e568-43b3-4439-80f2-6fd7caa94650.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/private-channels)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
An update to the article is on the works. Thanks for your feedback.
