### ISSUE TITLE
Document "Prepare your helpdesk for Microsoft Teams" / teams-adopt-helpdesk-guide.pdf has a broken link

### ISSUE THREAD

**Issue by levesquesamuel** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9838]
The link "Request and vote for features" links to "User voice" and should be changed to Feedback Portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e8b47aa-e7a9-7744-4344-23830ca3178a
* Version Independent ID: ddfc4477-255f-dbff-cae2-ff01b74f969c
* Content: [Tools and Downloads for Adoption - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/adopt-tools-and-downloads)
* Content Source: [Teams/adopt-tools-and-downloads.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/adopt-tools-and-downloads.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @levesquesamuel Samuel,
Can't seem to find that link in the article you opened the issue for, can you please specify where did you find it?
Thanks

**Comment by get-itips** [comment]
Hello @levesquesamuel Could you see my comment here? Thanks

**Comment by get-itips** [comment]
Hello @levesquesamuel I've just noticed you reference the file in the subject of the issue, didn't see that before, unfortunately, that file isn't hosted in Docs/Learn, so we can't modify it, but I'll try to pass this information on.
Thanks for your feedback.
