### ISSUE TITLE
[Doc-Enhancement] Users can discover blocked bot apps

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9841]
Hi Team,
If sideloading is disabled, user cannot discover blocked apps using app id and interact with the same.
If side loading is enabled(Enable "Upload custom apps" option in app setup policy), user can still discover blocked apps by searching with bot id and interact with the same.

As this information is not available in documentation, please add note related to the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dcb5cdf7-9a02-cdf2-e152-38db69f0ae79
* Version Independent ID: d8e429a0-296d-1bf9-fb21-1ce13a6a59c3
* Content: [Overview of app policies to manage apps in Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/app-policies)
* Content Source: [Teams/app-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/app-policies.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by ashishguptaiitb** [comment]
Hi @SubbaReddi , thanks for sharing this info. Are these blocked apps  LOB or 3P apps?

**Comment by SubbaReddi** [comment]
@ashishguptaiitb : I observed it is applicable for LOB apps.

Updated note:
If sideloading is disabled, user can discover blocked LOB apps using bot id but cannot interact with the same.

**Comment by scanum** [comment]
@ashishguptaiitb hope all is well. Wanted to follow up to see if there is an update here. Thanks!

**Comment by ashishguptaiitb** [comment]
Discussing internally with @SubbaReddi and the wider team. Closing this issue here. Tracking internally in an ADO work item.
