### ISSUE TITLE
Can we have an embed code for the video please?

### ISSUE THREAD

**Issue by colinrippeyfinarne** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#985]
It would be extremely useful if we can have an embed code for the video. On the Share menu. If I try to use the Share-&gt;Copy link menu option and then try to use the link on another webpage I get the following message: 

"This website doesn't support embedding using just the address. Try pasting the embed code instead. If it's important to embed from this site using just the address, please send us feedback."

Also, my current office pc is Windows 7 with IE11. If I browse to this content on that browser the video is rendered with a flash player. If I browse to the content on google chrome the video is rendered using an HTML5 video tag. IE11 supports the video tag so can this be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e1b8fbb-3047-dd3a-6a9c-ae6b1d5a0222
* Version Independent ID: 42c418d1-8473-2243-81bc-558e0a0688aa
* Content: [Overview of Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/Teams-overview)
* Content Source: [Teams/Teams-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-overview.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@colinrippeyfinarne Thank you for this feedback

I will the update request on over to the Teams team for investigation. 

I made a note to request the team to update this when the work is complete.

I know the product teams are always looking for user feedback and how to make Teams better. They keep a close tab on User Voice [https://microsoftteams.uservoice.com/forums/555103-public](https://microsoftteams.uservoice.com/forums/555103-public) and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too. 
 
Thank you for your contribution to make the docs better! Much appreciated!

**Comment by LolaJacobsen** [comment]
We updated this article recently. It now links to a video in a player that DOES have a Share command. Hope that helps!
