### ISSUE TITLE
Missing MTR and Phone PBIT description

### ISSUE THREAD

**Issue by Knollo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9850]
In the current CQD Power BI Query Templates there are a subfolder MTOE with reports for MTR and Phone System, what is very great and helpful. But this is missing as description in the table of available PBIT's.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dfbb1a90-d5f1-217e-1880-59afe121d979
* Version Independent ID: 7f6c85ae-f2c6-4b0b-6c8a-9bfcbe394328
* Content: [Use Power BI to analyze CQD data for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/cqd-power-bi-query-templates)
* Content Source: [Teams/CQD-Power-BI-query-templates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-Power-BI-query-templates.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by ParkesJ** [comment]
PR #11500 has merged to resolve this issue.

**Comment by get-itips** [comment]
Thanks @ParkesJ

**Comment by get-itips** [comment]
Document was updated.
