### ISSUE TITLE
This page should be updated monthly

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#986]
The nature of the this article content requires monthly review/update.
This article has not been updated since July 2018, thus information about client updates released in August/September/October are missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc1999a1-66c4-1236-54e5-6491c8b70c1c
* Version Independent ID: 8b423b6d-793b-52ee-0031-1f80ea453a3c
* Content: [Latest updates for versions of Skype for Business that use Windows Installer (MSI)](https://docs.microsoft.com/en-us/skypeforbusiness/sfb-client-updates?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json)
* Content Source: [Skype/SfbServer/sfb-client-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/sfb-client-updates.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by shivtorov** [comment]
It would be great if you could:
1) in the beginning of each section, clearly state when the information was last updated. E.g. "Lync 2013 client updates (as of 1st July 2018)"
2) add link to the article, where to look for more recent updates. This article is being updated monthly - https://docs.microsoft.com/en-us/officeupdates/office-updates-msi

**Comment by AndreaBarr** [comment]
@shivtorov Thank you for this feedback. 

I will get this over to the Teams/Skype for Business team for investigation. 

@jambirk I have created a backlog Item for this issue and assigned it to you.

**Comment by kenwith** [comment]
I see updates as of January 2019 now. Thanks for catch and getting this on the radar of the right person.
