### ISSUE TITLE
Key enrollment no longer supported

### ISSUE THREAD

**Issue by mjtart** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9860]
If you need to install the agent without the Teams App on the MTR being able to login to Teams, you can use our enrollment key as an optional process. Go to '?' (Help) on the top right corner of the portal, then select 'Download key (optional)'. When installing the agent, place the ‘Self-Enrollment key' (previously downloaded from the portal) on the C:\Rigel directory of the device.

^ This section is no longer valid as key enrollment has been deprecated and should be removed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 926bcf08-5326-ed74-8170-14b46fd5ade7
* Version Independent ID: 926bcf08-5326-ed74-8170-14b46fd5ade7
* Content: [Enroll a Teams Room device into Pro Management - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/enroll-a-device?source=docs)
* Content Source: [Teams/rooms/enroll-a-device.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/enroll-a-device.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @altsou
* Microsoft Alias: **altsou**

**Comment by get-itips** [comment]
fixed in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/1081ad9ab73b8e82688c00f5093ab334a5aef847
thanks!
