### ISSUE TITLE
[Doc-Bug] "Allow interaction with custom apps" - Add more details in documentation

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9863]
Hi Team,
Regarding "Allow interaction with custom apps":  
If this is "Off", 

- Users cannot interact with side loaded apps. 
- If user search with bot id, app name will be shown but cannot interact.

But Teams admin can upload app as LOB app to Teams admin center and then works for users.  As existing documentation is not clearly indicating that, i request to update in documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d51bb7b1-801e-6801-dcaf-afa3e38e6941
* Version Independent ID: d8e726a1-cbf2-53c7-da4d-cc155b48612b
* Content: [Manage custom and sideloaded app policies and settings - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-custom-app-policies-and-settings#org-wide-custom-app-setting)
* Content Source: [Teams/teams-custom-app-policies-and-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-custom-app-policies-and-settings.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by marianocalero** [comment]
Hi @scanum and @get-itips - is there any update on this doc change? Thank you!

**Comment by ashishguptaiitb** [comment]
Hi @SubbaReddi , I've now clarified this setting in the help article.

**Comment by ashishguptaiitb** [comment]
Between, the UI has recently changed ever so slightly to call the option as "Interaction with custom apps".

![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/49870256/d24fb298-c10d-44ed-8cec-98ce337c6be4)

**Comment by ashishguptaiitb** [comment]
> Hi @SubbaReddi , I've now clarified this setting in the help article.

Specifically, the second table in this section https://learn.microsoft.com/en-us/microsoftteams/teams-custom-app-policies-and-settings#understand-custom-apps-and-the-available-settings mentions that custom apps uploaded to org store continue to be available.

And the open paragraph in this section: https://learn.microsoft.com/en-us/microsoftteams/teams-custom-app-policies-and-settings#allow-your-users-to-use-custom-apps mentions that the setting applies to "_custom apps in their personal or team context_" only.

I'm closing this issue. If not adequate, please reopen and I'd be happy to further refine the docs.
