### ISSUE TITLE
Assign plicy to a group

### ISSUE THREAD

**Issue by olavase** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#987]
Is it not possible to assign a policy to a group of users? I want to assign a policy to 1500 students and i can not do this one by one student...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34f3188-0af5-f972-9d28-959f5f7866a2
* Version Independent ID: fab26e11-a729-92a4-3ea6-8668dca55dd0
* Content: [What are Messaging policies in Teams?](https://docs.microsoft.com/en-us/microsoftteams/messaging-policies-in-teams)
* Content Source: [Teams/messaging-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/messaging-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AnxiousArchangel** [comment]
I am baffled by the same assignment issue. 84,000+ accounts and my choice is global or per user assignment? No group assignment including and preferably dynamic groups? In education user accounts come and go every day so something dynamic is greatly needed. Maybe a hierarchy where an individual assignment overrides group or domain assignment. Most large organizations have some sort of identity management. Populating custom attributes to base dynamic group filters can be very powerful if the groups could be used. Either I am missing something or just failing to understand the logic of having a policy based system and only manual user based assignment.

**Comment by AndreaBarr** [comment]
@olavase Thank you for this inquiry

I don't know how to assing a policy to a group of users without using global. Let me get this over to the Teams/Skype for Business team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by bucketspodge** [comment]
The only way I have been able to assign policy to multiple users is by using powershell. Even that is limited to about 50 lines before it cracks it and stops working. Really needs to be a better option to assign policies to users. Here is the script I have been using if you want to give it a shot and make it better.
$UsersFile = Import-Csv "D:\Users\desktop\userslist.csv"
$credential = Get-Credential
Import-Module SkypeOnlineConnector -global
$sfboSession = New-CsOnlineSession -Credential $credential -OverrideAdminDomain "domain.onmicrosoft.com"
Import-PSSession $sfboSession -allowclobber 
foreach ($User in $UsersFile) {
  grant-CsTeamsMessagingPolicy -Identity $User.UPN -PolicyName EduStudent_Custom -ErrorAction SilentlyContinue}

**Comment by LolaJacobsen** [comment]
@nomorephones can you help us with this one?

**Comment by nomorephones** [comment]
@LolaJacobsen This capability is not currently available in the Teams admin center.  While the ability to make policy changes on groups of users is something that we are working on, unfortunately we don't yet have a committed date for release.

**Comment by b34ny1** [comment]
You've moved the settings from Settings > Services & add-ins > Microsoft Teams, to the new Teams and Skype dashboard and in that process removed the ability to apply settings easily to all our students licenses. Ridiculous 

It was super easy back in 2017: https://blogs.technet.microsoft.com/skypehybridguy/2017/08/24/microsoft-teams-disable-private-chat-how-to/

**Comment by Per-Torben** [comment]
I can't understand what possible reason you (Microsoft) have to remove the ability to assign policy to groups or Faculty/Students. You have always taught us to use groups for assigning permissions but in 2018 you suddenly step away from that principle? Also I can't understand why this would take so long to implement, I can't possibly be that difficult.

**Comment by SergePoint** [comment]
Any update on assigning policy to a group?

**Comment by alanbmhs** [comment]
Another month and still no word on licensing for groups. What was wrong with Settings by user/license type in the old services/addins section? As @Per-Torben says, it can't possibly be that difficult.

**Comment by scanum** [comment]
@olavase - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by WHPTrust** [comment]
Still doesn't seem possible. I just want to apply a policy to a group.

**Comment by markburland** [comment]
Aside from the spelling mistake in the title, I'm not sure why this got closed. It's as relevant as ever and I find myself here after searching around for potential solutions or suggestions.

**Comment by RobFullerGBHS** [comment]
@scanum why is this closed? This is still an issue support are unable to help with.

**Comment by bucketspodge** [comment]
I believe they closed it early but you can now set up policies to automatically assign to groups/security groups using powershell.
https://docs.microsoft.com/en-us/microsoftteams/teams-policies
They should have provided this information before closing it down.

**Comment by RobFullerGBHS** [comment]
@bucketspodge that's a cheat as it's pulling users from a group and using ForEach-Object command to apply at a per user level.
Certainly wouldn't do it automatically if this command wasn't running periodically.

**Comment by bucketspodge** [comment]
@RobFullerGBHS my apologises I did grab the wrong link. I believe this is the one I was thinking of.
https://docs.microsoft.com/en-us/microsoftteams/assign-policies

**Comment by RobFullerGBHS** [comment]
@bucketspodge New-CsGroupPolicyAssignment looks interesting thanks for the link!

**Comment by bucketspodge** [comment]
@RobFullerGBHS No problem, I'm still trying to work out the rankings for my workplace and will then test it myself but looks hopeful.

**Comment by RobFullerGBHS** [comment]
Getting, Set-CsGroupPolicyAssignment : Access Denied. How did you get on?

**Comment by bucketspodge** [comment]
Seen this update on the message center.
Updated March 4, 2020: To ensure the best experience we are adjusting the roll-out timeframe for this feature. We apologize for the inconvenience.
Teams administrators will soon be able to assign policies to a batch of users or to a group. We’ll be releasing this in late May (previously March).

This message is associated with Microsoft 365 Roadmap ID 61185.

**Comment by RobFullerGBHS** [comment]
> Seen this update on the message center.
> Updated March 4, 2020: To ensure the best experience we are adjusting the roll-out timeframe for this feature. We apologize for the inconvenience.
> Teams administrators will soon be able to assign policies to a batch of users or to a group. We’ll be releasing this in late May (previously March).
> 
> This message is associated with Microsoft 365 Roadmap ID 61185.

Yeah that would explain the access denied! Thanks for the heads up.
