### ISSUE TITLE
MS Private Channel icon when channel name is too long

### ISSUE THREAD

**Issue by mobcdi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9872]
The document does not mention how to identify if a channel is private when the channel name is too long to fit in the left part of the screen. Is it safe to assume if the icon is not visible then the channel is public?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [Private channels in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/private-channels)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @mobcdi 
I guess you mean the lock icon, I tested this with a long name and the lock icon was still present, any way, you should also see it if you hover the channel's name.
