### ISSUE TITLE
[Doc-Enhancement] Hiding teams app is not possible

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9873]
Hi Team,
Even if third-party apps are blocked, users can request access for it.  
But some organizations don't want to display blocked apps.
As it is not possible currently, please add note mentioning the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f07d46fc-fafd-b775-be7c-667d1e090565
* Version Independent ID: f07d46fc-fafd-b775-be7c-667d1e090565
* Content: [User requests for admins - Microsoft Teams](https://learn.microsoft.com/en-US/microsoftteams/user-requests-approve-apps)
* Content Source: [Teams/user-requests-approve-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/user-requests-approve-apps.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by ashishguptaiitb** [comment]
Hi @SubbaReddi , thanks for the feedback. I've updated the article and it will be published live on 3/30. CC @scanum and @get-itips

**Comment by ashishguptaiitb** [comment]
Closing this issue as the updated docs are published live.
