### ISSUE TITLE
Avatar is not available on our tenant apps list

### ISSUE THREAD

**Issue by mikewalker74** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9874]
Is this feature only available in USA based tenants, I am in the UK and all three of our tenants have got the Public Teams Preview enabled but the Avatar app is not listed in the apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 122d9ead-09d3-f605-1bfb-6ae0fce81636
* Version Independent ID: 122d9ead-09d3-f605-1bfb-6ae0fce81636
* Content: [Set up avatars for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/meeting-avatars)
* Content Source: [Teams/meeting-avatars.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-avatars.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by MentaRest** [comment]
I am experiencing the same problem as well. I looked at the following link but got an error. Could you please tell me again?
