### ISSUE TITLE
Wrong path for Policy Editor

### ISSUE THREAD

**Issue by Mhudson97** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9878]
Correct path is Computer Configuration / Administrative Templates / Windows Components / App package Deployment

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Version Independent ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Content: [The new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-gb/microsoftteams/new-teams-desktop-admin?tabs=teams-admin-center#policy-settings-restricting-download--install)
* Content Source: [Teams/new-teams-desktop-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/new-teams-desktop-admin.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
