### ISSUE TITLE
page corrections.

### ISSUE THREAD

**Issue by Mhudson97** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9879]
Correct path is Computer Configuration / Administrative Templates / Windows Components / App package Deployment

Missing space in MEC version
<html>
<body>

Monthly Enterprise Channel | Version 2301 (Build 16026.20222)Version2212 (Build 15928.20294)
-- | --

</body>
</html>

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Version Independent ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Content: [The new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-gb/microsoftteams/new-teams-desktop-admin?tabs=teams-admin-center#policy-settings-restricting-download--install)
* Content Source: [Teams/new-teams-desktop-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/new-teams-desktop-admin.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @Mhudson97, thank you for your feedback.

This is duplicated:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9878
