### ISSUE TITLE
no hyper links here

### ISSUE THREAD

**Issue by Strick1969** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#988]
We recommend that you confirm that your SBC has already been configured as recommended by your SBC vendor's:

AudioCodes deployment documentation
Ribbon Communications deployment documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df318fdb-6d58-86f8-de31-6eca533a9746
* Version Independent ID: a2248abf-bdf0-2c22-2604-74b482156684
* Content: [Configure Direct Routing](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-configure#feedback)
* Content Source: [Teams/direct-routing-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-configure.md)
* Service: **msteams**
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by AndreaBarr** [comment]
@Strick1969 Thank you for pointing this out

I will get this hyperlink issue over to the Teams team for investigaiton. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by LolaJacobsen** [comment]
Assigning VSO item to you too...

**Comment by LolaJacobsen** [comment]
Leaving VSO item assigned to @AndreaBarr but assigned the GitHub issue to @Nikokla

**Comment by jamesrhea** [comment]
Will do, @AndreaBarr.

**Comment by jamesrhea** [comment]
@AndreaBarr this issue was fixed by @NMuravlyannikov (see comments in #1411) and can be closed.
