### ISSUE TITLE
アプリの管理センターにAvatarsのアプリが表示されません。

### ISSUE THREAD

**Issue by MentaRest** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9882]
As per the subject line, the desktop version of Teams was able to display the Avatars app in public preview settings, but when I search for the app in the MS admin center, the app does not appear and I can create avatars, but cannot use them in Teams. How should we deal with this?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
