### ISSUE TITLE
Recording is controlled via cloud recording property in Teams meeting

### ISSUE THREAD

**Issue by tomaschladek** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9886]
Hi there,

I think that there is mistake in the public documentation:
https://learn.microsoft.com/en-us/microsoftteams/meeting-templates-sensitivity-labels-policies

Who can record, and automatically record meetings is controlled via "is cloud recording" property in Teams meeting policy, that should disable recording.

[Set-CsTeamsMeetingPolicy (SkypeForBusiness) | Microsoft Learn](https://learn.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: acbfea21-a333-7cc4-b7a1-c947033847cf
* Version Independent ID: acbfea21-a333-7cc4-b7a1-c947033847cf
* Content: [Use Teams meeting templates, sensitivity labels, and admin policies together for sensitive meetings - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/meeting-templates-sensitivity-labels-policies)
* Content Source: [Teams/meeting-templates-sensitivity-labels-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-templates-sensitivity-labels-policies.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
Talking to Tomas internally, so closing this.
