### ISSUE TITLE
SfB Server 2019 Server requirements link incorrect

### ISSUE THREAD

**Issue by Markusott7** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#989]
Server requirements for Skype for Business Server link incorrectly points to 2015 requrements instead of 2019 requirements:

At: Install prerequisites for Skype for Business Server
https://docs.microsoft.com/en-us/skypeforbusiness/deploy/install/install-prerequisites

Incorrect: Server requirements for Skype for Business Server
https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/server-requirements

Correct: System requirements for Skype for Business Server
https://docs.microsoft.com/en-us/skypeforbusiness/plan/system-requirements

This incorrect link is at 3 places on this site.

**Comment by AndreaBarr** [comment]
@Markusott7 Thank you for this feedback

I will get this information about the wrong links to the Skype for Business team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
