### ISSUE TITLE
SBA Firewall Requirements

### ISSUE THREAD

**Issue by jamescussen** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9891]
The current documentation says in the Prerequisites section that outbound TCP port 443 traffic is required to:

"Port 443 is used by Microsoft SBA Server to communicate with Microsoft 365 and should be allowed on the firewall.

Azure IP Ranges and Service Tags for the Public Cloud should be defined according to the guidelines described at: https://www.microsoft.com/download/details.aspx?id=56519"

If you download the Azure Public cloud IP Range list there is about 90,000+ address ranges in it and then add to that the Microsoft 365 address ranges. The documentation should be more specific about what actual DNS names/IP Addresses need to be accessible by the SBA as most secure deployments are not going to allow 443 to ANY towards the internet.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 183fc921-e9b1-cc74-2bcb-26d32b994919
* Version Independent ID: 1765bda3-dd62-76d7-1e2d-9f5496ac9094
* Content: [Direct Routing SBA - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/direct-routing-survivable-branch-appliance)
* Content Source: [Teams/direct-routing-survivable-branch-appliance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-survivable-branch-appliance.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @jamescussen I am working on this

**Comment by CarolynRowe** [comment]
Hello @get-itips.  We need an answer from @FilippSe.  Filipp, can you help here?

**Comment by get-itips** [comment]
Hello @jamescussen & @CarolynRowe 
I was confirmed that team is aware of this and working on it.
