### ISSUE TITLE
Additional Limitation

### ISSUE THREAD

**Issue by mbender-ith** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9892]
In my testing, using a shortcut (starting with the "/" character) in the top search bar does not work. This page does not seem to list this as a current limitation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Version Independent ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Content: [The new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-gb/microsoftteams/new-teams-desktop-admin?tabs=teams-admin-center)
* Content Source: [Teams/new-teams-desktop-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/new-teams-desktop-admin.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @mbender-ith, thank you for your feedback.

This article does not list the limitations of the new app. In the "What features are still missing?" section, you can see the following link:
https://aka.ms/newTeams

There you'll be able to see the "Features in the new Teams" section. In addition, you can see the "Try it now and let us know what you think!" section where you can leave your feedback including the inclusion of this feature.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
