### ISSUE TITLE
Avatar App is not there

### ISSUE THREAD

**Issue by Dburke225** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9893]
The documentation says to add the app to the Teams Preview app, but you can't add apps to the new teams. I also don't have the Avatar app in the admin center.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 122d9ead-09d3-f605-1bfb-6ae0fce81636
* Version Independent ID: 122d9ead-09d3-f605-1bfb-6ae0fce81636
* Content: [Set up avatars for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/meeting-avatars)
* Content Source: [Teams/meeting-avatars.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-avatars.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @Dburke225 
I checked and I have [Preview] Avatars app on lab tenant, if you don't have it I recommend opening a support request.
Also, this is intended for the current Teams app not the new one (that is currently in preview).

Thank you,

**Comment by Dburke225** [comment]
Actually its in the admin center but doesn't do anything, can't add it in Teams


Dillon Burke
Assistant Systems Engineer
Qosina Corp. | QOSMEDIX
2002-Q Orville Drive North
Ronkonkoma, NY 11779 USA
T: +1 (631) 940-6768
Email: ***@***.******@***.***>
www.qosina.com<http://www.qosina.com>  www.qosmedix.com<http://www.qosmedix.com>

From: Dillon Burke ***@***.***>
Sent: Tuesday, May 16, 2023 12:20 PM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>; MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Avatar App is not there (Issue #9893)

I just checked and I finally have it. It would be nice if Microsoft released stuff when they say they released it.


Dillon Burke
Assistant Systems Engineer
Qosina Corp. | QOSMEDIX
2002-Q Orville Drive North
Ronkonkoma, NY 11779 USA
T: +1 (631) 940-6768
Email: ***@***.******@***.***>
www.qosina.com<http://www.qosina.com>  www.qosmedix.com<http://www.qosmedix.com>
