### ISSUE TITLE
Missing new home screen design attributes

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9898]
This article is missing attributes mentioned in article about controlling the new home screen https://learn.microsoft.com/en-us/microsoftteams/rooms/mtr-home-refresh

```
<TeamsRoomsNewExperience>true</TeamsRoomsNewExperience> 
<RemoveFoRCalendar>true</RemoveFoRCalendar> 

```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 25a70665-5bf1-14f7-1df0-7596effcaf48
* Version Independent ID: 813cf005-2777-9419-d1ce-3f9401ac267c
* Content: [Remotely manage Microsoft Teams Rooms device settings - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/xml-config-file)
* Content Source: [Teams/rooms/xml-config-file.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/xml-config-file.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
