### ISSUE TITLE
Missing features requiring Pro license

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9900]
In MTR settings the following items have "Pro" marking indicating that they require Pro license but are not mentioned in this article:
- Masking name of the meeting
- End to end encryption
- Coordinated join
Can you please add information about these features requiring Pro license?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-licensing.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @Larryngolog, thank you for your feedback.

Could you share a screenshot?

This is what I see:
![image](https://user-images.githubusercontent.com/33589238/230673212-d87dec05-d5fd-4305-854d-e1eb3e12abf3.png)

**Comment by Larryngolog** [comment]
You need to have "Basic" license assigned to device to see it. Here is how it looks like:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/18740551/230977814-8c7bdb7a-6019-413a-94e2-55a15de92143.png)
![image](https://user-images.githubusercontent.com/18740551/230977971-615041aa-bd19-4d96-b337-f1f515962043.png)
