### ISSUE TITLE
Please update the limitations for Firefox.

### ISSUE THREAD

**Issue by venthur** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9903]
This page still claims that Calling - audio, video, and sharing is not supported in Firefox, while in fact it does work:
* Audio, Video and Screen sharing works for meetings.
* Direct calls technically work when you create an ad-hoc meeting in Team's calendar and share the link to someone you'd like to talk to. For some reason the button that would allow to do a direct call is greyed out and claims that feature is not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams#browsers)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hello @venthur Bastian, how are you?
One thing is "works" and another different is "supported", but I'll try to dig to understand if an update is required to the table.
Thanks,

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by venthur** [comment]
> We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

Weird, I was not under the impression that I was asked for additional information or anything like that that required a response. As far as I'm concerned the issue is still open.
