### ISSUE TITLE
Stacking Teams Rooms Basic & Teams Shared Device

### ISSUE THREAD

**Issue by unearthnz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9906]
Hi there, I have been led to believe if a room licensed with Teams Rooms Basic requires a Teams Panel, that a Teams Shared Device license can be added (ie so 1x Basic & 1x Shared Device license are assigned to the same account). This has been confirmed by several other websites and by our Microsoft licensing distributor, can you please confirm the same and if so, add a reference to it on this page? Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2070d20-21d1-c8bb-bbb4-697083efcd20
* Version Independent ID: f4998e3c-74ed-4a2b-fe7c-c55044b9a6b4
* Content: [Microsoft Teams Rooms licenses - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-licensing)
* Content Source: [Teams/rooms/rooms-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-licensing.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by unearthnz** [comment]
From two MVP's who regularly author content on Teams Rooms:

Graham Walsh: (The Teams Room Shared Device license is) only for use with Basic MTR licenses or where there is not a MTR in that space." https://www.thegrahamwalsh.com/mtdama-episode-30-september-2022/ 

Tom Arbuthnot: "Yes, You can “stack” multiple licences on a single account to have Teams Rooms basic plus ..... a Teams Panel." https://tomtalks.blog/microsoft-teams-rooms-pro-and-microsoft-teams-rooms-basic-everything-you-need-to-know/

**Comment by tonysmit** [comment]
I'm closing this item. I reached out to the PMs in the space and our official stance is that customers should not "STACK" licenses to get a desired result. Thanks.
