### ISSUE TITLE
What about intune?

### ISSUE THREAD

**Issue by chaplic** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9908]
Recommended config option is to use Group Policy... err dont you have a great product called intune? might be nice to provide guidance for that too.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Bulk install Teams using Windows Installer (MSI) - Microsoft Teams](https://learn.microsoft.com/en-gb/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @chaplic I'll propose to add information about intune
