### ISSUE TITLE
What protocol and ports should customers open?

### ISSUE THREAD

**Issue by howardzhangmsft** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9909]
Please clarify what protocol (TCP / UDP) and ports are required to be opened on firewall for the following statement:

Open the following IP addresses:

13.75.175.145
52.189.219.201
51.124.34.164
13.74.250.91
13.83.55.36
23.96.103.40
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 05173ea8-db7c-a20d-3783-178b3d649190
* Version Independent ID: 05173ea8-db7c-a20d-3783-178b3d649190
* Content: [Configure SIP Gateway - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/sip-gateway-configure)
* Content Source: [Teams/sip-gateway-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sip-gateway-configure.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @howardzhangmsft 
how are you?
The article says  

> for HTTP and HTTPS:

**Comment by get-itips** [comment]
@scanum
