### ISSUE TITLE
The info on this webpage is old... see below...

### ISSUE THREAD

**Issue by dusansk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9911]
[Enter feedback here]
The info on this webpage is old... see below...

Set-CsTenantFederationConfiguration -SharedSipAddressSpace $false

**Set-CsTenantFederationConfiguration : Processing data from remote server api.interfaces.records.teams.microsoft.com fai
led with the following error message: ⁠This scenario is not supported anymore. Please try with the latest Teams PowerSh
ell Module version or different parameter sets or refreshing Connect-MicrosoftTeams or refer to the public documentatio
n. For more information, see the about_Remote_Troubleshooting Help topic.**
At line:1 char:1
+ Set-CsTenantFederationConfiguration -SharedSipAddressSpace $false
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Set-CsTenantFederationConfiguration], PSRemotingTransportExcep
   tion
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Teams.C
   onfigApi.Cmdlets.SetCsTenantFederationConfiguration

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ce37c7f-6f13-8442-bfdb-47065a7339b3
* Version Independent ID: 9a2b5082-369d-7c04-4fa8-81c1440ea119
* Content: [Disable hybrid to complete migration to Teams Only - Skype for Business Hybrid](https://learn.microsoft.com/en-us/skypeforbusiness/hybrid/cloud-consolidation-disabling-hybrid)
* Content Source: [Skype/SfbHybrid/hybrid/cloud-consolidation-disabling-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/cloud-consolidation-disabling-hybrid.md)
* Service: **skype-for-business-server**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hello @dusansk 
How are you?
What version of Teams Ps are you running?
Thanks

**Comment by get-itips** [comment]
Closing for now... @scanum
