### ISSUE TITLE
Authorized user feature

### ISSUE THREAD

**Issue by dblankjr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9915]
[Enter feedback here]
I have been waiting for this feature (allowing authorized users to change their own greetings) but it is missing just one item.  The ability to allow the "authorized user" to change their own business hours.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bdc17ac9-a82b-8705-fc77-5d0ecdcb2b56
* Version Independent ID: bdc17ac9-a82b-8705-fc77-5d0ecdcb2b56
* Content: [Set up auto attendant and call queue authorized users - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/aa-cq-authorized-users)
* Content Source: [Teams/aa-cq-authorized-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/aa-cq-authorized-users.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by dariomws** [comment]
Same as https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9916.
