### ISSUE TITLE
Authorized user feature - missing feature

### ISSUE THREAD

**Issue by dblankjr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9916]
[I have been waiting for this feature (allowing authorized users to change their own greetings) but it is missing just one item.  The ability to allow the "authorized user" to change their own business hours.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bdc17ac9-a82b-8705-fc77-5d0ecdcb2b56
* Version Independent ID: bdc17ac9-a82b-8705-fc77-5d0ecdcb2b56
* Content: [Set up auto attendant and call queue authorized users - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/aa-cq-authorized-users)
* Content Source: [Teams/aa-cq-authorized-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/aa-cq-authorized-users.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@dblankjr Thank you for the product feedback. I'll forward this onto the product team. 

I want to note that if you read the https://learn.microsoft.com/en-us/microsoftteams/manage-voice-applications-policies#future-release-voice-applications-policy-settings article, you'll notice that there will be future releases for authorized users including the ability to manage business hours.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
