### ISSUE TITLE
Zones

### ISSUE THREAD

**Issue by jgre333** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9919]
The article mentions different zones for calling plans, but I can't find any details on what these zones actually mean. Under all plans it mentions zone 1 for US but then a note that you can't actually buy zone 1 US licenses in the US. Can we get details on what zones are and what you would purchase in the US?  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 33bfc660-573d-b57e-8b67-6aa1fbe820ad
* Version Independent ID: 53318fba-10e9-cd4b-f0ee-397cd10e8c0c
* Content: [Microsoft Calling Plans for Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/calling-plans-for-office-365)
* Content Source: [Teams/calling-plans-for-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/calling-plans-for-office-365.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
