### ISSUE TITLE
Not available

### ISSUE THREAD

**Issue by Dburke225** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9920]
This is not available yet. Please remove until it is, makes it very confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 122d9ead-09d3-f605-1bfb-6ae0fce81636
* Version Independent ID: 122d9ead-09d3-f605-1bfb-6ae0fce81636
* Content: [Set up avatars for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/meeting-avatars)
* Content Source: [Teams/meeting-avatars.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-avatars.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @Dburke225, thank you for your feedback.

This feature is available as part of the public preview program. The general availability rollout will start next month. I added a note to let readers know that it's in preview.

For more information:
https://techcommunity.microsoft.com/t5/microsoft-teams-blog/avatars-for-microsoft-teams-in-public-preview/ba-p/3774421
https://support.microsoft.com/office/join-a-meeting-as-an-avatar-in-teams-5384e7b7-30c7-4bcb-8065-0c9e830cc8ad
https://www.microsoft.com/microsoft-365/roadmap?rtc=1&searchterms=107969&filters=&searchterms=107969

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
