### ISSUE TITLE
missing error code that can block new Teams client deployment

### ISSUE THREAD

**Issue by orandev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9923]
Hello,
We have a "Restrict sign-in to other tenants" policy on our computers, and this blocks me from seeing the "Try the new Teams client" toggle.
Could you add the error code that is in my logs to the doc please? (in the "Check the code to find out the cause." section in "How do I know which one of the above policies is blocking me?" section)

Code = SIGNINRESTRICTED
Meaning = a "Restrict sign-in to other tenants" policy is in place on the computer

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Version Independent ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Content: [The new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin?tabs=teams-admin-center)
* Content Source: [Teams/new-teams-desktop-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/new-teams-desktop-admin.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by orandev** [comment]
Hello,
I already opened a service ticket and here is what they replied:

_Users with SignInRestriction (RestrictTeamsSignInToAccountsFromTenantList Configured) are currently not supported for the new Teams Experience and it's not determined if it will get supported in the future or not .
 
This is also documented here in our public article https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin

So the behavior encountered is expected and by design._

So I would like you to add the error code related to this requirement in the doc please, to cover all the use cases where new Teams client is not accessible.

**Comment by orandev** [comment]
Hello,
Could you reopen the issue please?
