### ISSUE TITLE
Authorized users for AAs and CQs

### ISSUE THREAD

**Issue by NDedev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9925]
Setting up the Voice Application Policy and assigning authorized users works fine from Teams Admin Portal. However on the client side, nothing really changes, tried all versions of the client. Although the feature is great, it still doesn't work :(.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
