### ISSUE TITLE
Presence-based routing in Call Queues

### ISSUE THREAD

**Issue by rgsteele** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9930]
This article ought to reference the Presence-based routing feature for Call Queues, as documented here: https://learn.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue?tabs=agent-selection#presence-based-call-routing

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a162ef5c-3099-7f58-4178-d29e3ec2b5a7
* Version Independent ID: 6ca31e56-052d-6c62-1323-b5aaaae1f04a
* Content: [User presence in Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/presence-admins)
* Content Source: [Teams/presence-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/presence-admins.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @rgsteele 
I'll propose to add a reference to the article.
Thank you
