### ISSUE TITLE
Unable to use app-based authentication

### ISSUE THREAD

**Issue by mariussm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9931]
Hi,

I am experiencing issues getting app-based authentication to work. I am able to connect successfully, but all cmdlets return the same thing:

```
PS C:\> Get-CsTeamsClientConfiguration
Get-CsTeamsClientConfiguration: The remote server returned an error: (404) Not Found
```

I am currently using example 6 here, with access tokens gotten using client secret, but I am getting the same thing with certificate based as well. I have also tested both app reg in the tenant with teams, and a multi tenant from another tenant - all the same:

https://learn.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps#example-6-connect-to-microsoftteams-using-application-based-access-tokens

This is the code that I use to reproduce:

```
$clientid = "c4a1705d-9278-4417-8d78-92014798407e"
$tenantid = "237098ae-0798-4cf9-a3a5-208374d2dcfd"
$clientsecret = "IRz8......."

$graphtokenBody = @{   
    Grant_Type    = "client_credentials"   
    Scope         = "https://graph.microsoft.com/.default"   
    Client_Id     = $clientid   
    Client_Secret = $clientsecret   
 }  
 
 $graphToken = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$tenantid/oauth2/v2.0/token" -Method POST -Body $graphtokenBody | Select-Object -ExpandProperty Access_Token 
 
 $teamstokenBody = @{   
    Grant_Type    = "client_credentials"   
    Scope         = "48ac35b8-9aa8-4d74-927d-1f4a14a0b239/.default"   
    Client_Id     = $clientid   
    Client_Secret = $clientsecret 
 } 
 
 $teamsToken = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$tenantid/oauth2/v2.0/token" -Method POST -Body $teamstokenBody | Select-Object -ExpandProperty Access_Token 
 
 Connect-MicrosoftTeams -AccessTokens @("$graphToken", "$teamsToken")

 Get-CsTeamsClientConfiguration # This returns the 404 error
```
![image](https://user-images.githubusercontent.com/426202/231562628-1757dfd8-5c0f-4e89-b880-b26db890aab7.png)

What is interesting is that if I check Fiddler, a request to this endpoint is made, causing a 400:

**Request:**
```
GET https://api.interfaces.records.teams.microsoft.com/Teams.Tenant/serviceDiscovery HTTP/1.1
Host: api.interfaces.records.teams.microsoft.com
Accept: application/json
Authorization: Bearer eyJ0eXA........
X-Ms-Tenant-Id: 237098ae-0798-4cf9-a3a5-208374d2dcfd
Connection: Keep-Alive
```

**Response:**
```
HTTP/1.1 400 Bad Request
Cache-Control: private, no-cache, max-age=0, s-maxage=0
Transfer-Encoding: chunked
Content-Type: application/json
Server: Microsoft-HTTPAPI/2.0
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Frame-Options: Deny
X-MS-Correlation-Id: 74321d79-2f52-44d9-afbe-861742d8a6bc
Date: Wed, 12 Apr 2023 19:01:27 GMT

5E
{"code":"BadRequest","message":"Bad request.","action":"Specify valid request and try again."}
0
```

After this, I see a 404 towards this endpoint:

**Request:**
```
GET https://webdir.online.lync.com/Autodiscover/AutodiscoverService.svc/root?Domain=goodworkarounddev.onmicrosoft.com HTTP/1.1
Host: webdir.online.lync.com
Accept: application/vnd.microsoft.rtc.autodiscover+xml;v=1
Connection: Keep-Alive
```

**Response:**
```
HTTP/1.1 404 Not Found
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/vnd.microsoft.rtc.autodiscover+xml; v=1
Expires: -1
X-MS-Server-Fqdn: AM30E00EDG30.infra.lync.com
X-MS-Correlation-Id: 6034e87c-e1ce-4f24-b1e1-75b31162eedb
x-ms-client-request-id: 488d24f4-29f7-4bca-b3aa-6ace70869dfa
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Date: Wed, 12 Apr 2023 19:01:26 GMT
Content-Length: 318

<?xml version="1.0" encoding="utf-8"?><AutodiscoverResponse xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><Reason><Code>ResourceNotFound</Code><Subcode>HomePoolNotFound</Subcode><Message>Domain is not known or not found.</Message></Reason></AutodiscoverResponse>
```

What is really interesting, is that it seems that the first serviceDiscovery endpoint is only called until it succeeds in a PowerShell session, than it is done. If I connect using Connect-MicrosoftTeams as a user in interactive login, then Disconnect-MicrosoftTeams and THEN reconnect using app based auth, it works just fine!

So essentially this works:
1. Connect-MicrosoftTeams - sign in interactively as user
2. Disconnect-MicrosoftTeams
3. Use the above example now suddenly works - and I can see inn fiddler that the bearer token used is for the app, not the user, and that the serviceDiscovery endpoint is never called.

![image](https://user-images.githubusercontent.com/426202/231563514-e0bea18a-5347-4a57-8fe4-40782bd80db1.png)

The service principals is Teams Administrator, and have Organization.Read.All as well as application_access scope consented for 48ac35b8-9aa8-4d74-927d-1f4a14a0b239 (Skype and Teams Tenant Admin API). 

Tried many different versions of the teams powershell module, including the latest.

**Comment by pbafna03** [comment]
Hi @mariussm, 

Can you please remove the "application_access" permission for Skype and Teams Tenant Admin API and try this again?

Thanks,

**Comment by mariussm** [comment]
Funny enough, that is what i did yesterday before you commented, and suddenly it worked! :)

**Comment by get-itips** [comment]
@scanum
