### ISSUE TITLE
Further clarification of footnote?

### ISSUE THREAD

**Issue by gr0m1t1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9932]
The article has a footnote for certain devices:

_1 Device supports dynamic emergency calling (E911) with SIP Gateway._

However, I have done some testing with different devices, and the behavior is the same for devices with the footnote (Polycom VVX501, AudioCodes 450HD) and one without (VVX410). Confirmed they are running the approved firmware version.

Making a call with any of them sends the pidflo method as "Registered" rather than "LIS". I have confirmed that the location I am testing is correctly configured for dynamic e911. (Testing with the same account on a PC with Teams application sends pidflo of LIS and correct address.)

So, the question I have is, if the device has that footnote, _should_ it be obtaining the address dynamically and sending the pidflo method as LIS? Or will it always send as "Registered?"

Note, I have already opened a support ticket, but wanted to ask the question here, since it is specific to this footnote. 

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44863905-42d1-cd3f-0d97-af2570649e89
* Version Independent ID: 44863905-42d1-cd3f-0d97-af2570649e89
* Content: [Plan SIP Gateway - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/sip-gateway-plan)
* Content Source: [Teams/sip-gateway-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sip-gateway-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @gr0m1t1, thank you for your feedback.

Please keep us posted here on the support ticket resolution to feed whatever information you discover into the article.

@CarolynRowe @Chandranshu-Singh, maybe you can also provide some ideas. Maybe VVX410 should also be included in that footnote.

**Comment by CarolynRowe** [comment]
We need @Chandranshu-Singh to provide input on this issue.

**Comment by Chandranshu-Singh** [comment]
Thanks @CarolynRowe for tagging me here. 

Poly devices from VVX series to which this footnote applies, are currently not able to support emergency calling due to a firmware issue, which we are working to fix over the next few weeks. However, VVX 410 will not be getting this firmware update so it will never be able to support dynamic emergency calling with SIP Gateway.

**Comment by gr0m1t1** [comment]
Thanks @Chandranshu-Singh. Just to clarify, when you say that it will support emergency calling, does that mean that once the firmware issue is resolved, it will then be able to send the pidflo method as "LIS" and not just "Registered"? (Assuming the rest of the dynamic emergency configuration is correct, of course.)

Also, does the AudioCodes 450HD have a similar firmware issue? Because that one is also listed as being able to support dynamic emergency calling, but it was also only sending the "Registered" method.

@dariomws, regarding the support ticket I opened, have not had much progress yet. Very slow going, so far. But if anything pertinent comes up, will let you know.

**Comment by gr0m1t1** [comment]
Well unfortunately the ticket I had open is being closed because they are saying this is a 3rd-party device issue. But I am still unclear as to what is meant in this documentation when it states that emergency services are supported for those devices specified with the footnote. 

What _should_ the behavior be for these devices? Should the pidflo method be "LIS" (if it can be obtained) or will it always use the "Registered" address?

**Comment by Chandranshu-Singh** [comment]
On some AudioCodes phones, only support LLDP in dynamic location, not subnet mask. I think the higher end phones do support subnet mask and it shouldn't just send "Registered" as pidflo.

For Poly phones, we are again rolling out the firmware change to support dynamic location, it should be done in a couple of weeks time.

**Comment by gr0m1t1** [comment]
Thanks for the additional information, @Chandranshu-Singh. Is there somewhere to keep an eye on to find out when the updated firmware for Poly gets released? Will it be announced in the Message Center or Service Health in the Admin Center?

**Comment by Chandranshu-Singh** [comment]
It's being rolled out currently, as I said above, expect to complete it by May 22nd. We don't have an MC post on it.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
