### ISSUE TITLE
Teams Rooms Version support does not cover Android topic

### ISSUE THREAD

**Issue by yuki-iwagishi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9934]
[Microsoft Teams Rooms app version support](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-lifecycle-support)
This page covers Microsfot Teams Rooms on Windows, however, there is no info of Android.
Better to put Microsoft Teams Rooms on Android and Windows uses different App/Version in the first section.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7ecd6ee6-8850-f346-5684-9c5d2444789f
* Version Independent ID: a55a7a01-211d-147a-5332-b68e1051a2a1
* Content: [Microsoft Teams Rooms app version support - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-lifecycle-support)
* Content Source: [Teams/rooms/rooms-lifecycle-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-lifecycle-support.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
