### ISSUE TITLE
Teams numbers for an organisation

### ISSUE THREAD

**Issue by aspo73** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9940]
Document states "See a list of telephone numbers in your organization" but command only brings back active numbers that have been assigned to a user.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 224b0537-e144-f5ed-6974-6e34733bceb2
* Version Independent ID: 4f1875c6-77ef-f636-669e-5f3af9691f7d
* Content: [See a list of telephone numbers in your organization - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/see-a-list-of-phone-numbers-in-your-organization)
* Content Source: [Teams/see-a-list-of-phone-numbers-in-your-organization.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/see-a-list-of-phone-numbers-in-your-organization.md)
* Service: **skype-for-business-online**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
