### ISSUE TITLE
OC Assigned Phone Number

### ISSUE THREAD

**Issue by sjackson0109** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9955]
The article is missing the fact 'Operator Connect users MUST have an assigned number,to be able to route outbound calls', without one, the line drops immediately.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 709c5bb1-843a-c243-16b6-86bd9f114d37
* Version Independent ID: e5e9415f-bd40-4084-e280-59be5cc186a6
* Content: [Configure Operator Connect - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/operator-connect-configure#set-up-phone-numbers)
* Content Source: [Teams/operator-connect-configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/operator-connect-configure.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by sjackson0109** [comment]
Evidence:
![image](https://user-images.githubusercontent.com/38080190/232709940-51e1d493-8b13-4c9b-9e0e-0049a8972ea5.png)

![image](https://user-images.githubusercontent.com/38080190/232710703-e231a8b6-c83c-4d33-981d-0d30711668b5.png)

**Comment by dariomws** [comment]
Hi @sjackson0109, thank you for your feedback.

Acquiring and assigning phone numbers is part of the article and you need to complete all the steps to enable Operator Connect. After you complete all the steps, the users that you enabled for the service will be able to make and receive PSTN calls.

**Comment by sjackson0109** [comment]
I feel you misunderstood. I'm to be clear I have implemented both DR and OC successfully, on multiple tenants. I don't have a configuration issue. Am raising a BUG!

Allow me to explain a scenario I've seen with half a dozen different PBXs.

Company A has a legacy PBX, with extensions and an ISDN30 circuit, with ONE main number (inbound DDI). This inbound DDI lands on a hunt group, possibly some IVR options and eventually rings on devices in the office (extensions).
All out our calls have CLI masquerade configured FROM the main number.

In this scenario EVERY employee has a handset, has an individual extension and they all SHARE a common DDI.

Moving to teams.. they want LIKE FOR LIKE. Not too much to ask, am sure you agree.

Option 1 >> DIRECT ROUTING:
- +4411112222 (main number) is assigned to an rss account, of type AA, linked to an AA and presents IVR options > CQs etc.
- Outbound CLI policy with number replacement linked to the above rss user. Applied to all staff.
- every user can have a number set as follows:
Set-CSPhoneNumberAssignment $user.userPrincipalName -PhoneNumberType DirectRounting -PhoneNumber '+4411112222;ext=$($user.extension)'

There is no checking going on - this is simply accepted as long as the digits following 'ext=' are unique.



Option 2 >> OPERATOR CONNECT.
- +4411112222 (main number) is assigned to an rss account, linked to an AA and presents IVR options > CQs etc.
 ^^ operator needs to provision this number on our tenant before we can complete this ddi assignment^^
- Outbound CLI policy with number replacement linked to the above rss user. Applied to all staff.
- Set-CSPhoneNumberAssignment $user.userPrincipalName -PhoneNumberType OperatorConnect -PhoneNumber '+4411112222;ext=$($user.extension)'
 This is where we have an issue.  The DDI (ending 2222) is already assigned - so the command cancels.  It should not.

Now does this bug make sense?

We should be allowed to set 'ext=' in the OperatorConnect phone number assignment, and not have the pre-requisite check strip the 'ext=' part from the e.164 supported line-uri given to the ps command; when making a comparison of prior number assignments. Matches should be whole string matches, and nothing else!
Ext= should be permitted regardless of carrier 'provisioning' - as long as the main number is provisioned.

**Comment by CarolynRowe** [comment]
Hello @sjackson0109:  We appreciate the feedback and will share it with the product team.  But the GitHub issues are really about content issues.  It is not the forum to request bug fixes with the product or to request technical support.  Again, we will share your feedback.  Closing this issue.
