### ISSUE TITLE
Ports are formatted incorrectly

### ISSUE THREAD

**Issue by sritodi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9958]
Please see the ports, that's used

UDP/SRTP | Transport Relay | SBC | 50 000 -59 999 | Defined on the SBC
UDP/SRTP | SBC | Transport Relay | Defined on the SBC | 50 000 – 59 999, 3478-3481

please use format as 50,000 or 50000, addition of spaces really is lack of basic proofreading 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 10b198f4-9576-a14d-4359-1e8cc0319cda
* Version Independent ID: ba7c3252-21d4-9be1-2a84-de2d51646f7b
* Content: [Plan for media bypass with Direct Routing - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/direct-routing-plan-media-bypass)
* Content Source: [Teams/direct-routing-plan-media-bypass.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-plan-media-bypass.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
