### ISSUE TITLE
October to December is three months

### ISSUE THREAD

**Issue by copenhaus** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9962]
under "How long does the Teams Exploratory experience last" > "Note" - math is wrong

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28550025-fde2-9a83-a826-f7e3ccb313db
* Version Independent ID: 2a304432-b10c-220f-3453-e19e7a155c67
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-exploratory#what-happens-to-legacy-microsoft-teams-commercial-cloud-trial-licenses)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@copenhaus This article along with the other Teams Exploratory article is receiving a major update in the next week or so. I have overhauled and rewritten this article, which should resolve your concern.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
