### ISSUE TITLE
Incorrect link brings you here

### ISSUE THREAD

**Issue by Milwank** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9964]
There is a link on the Group page in [Microsoft Teams Rooms Pro Management](https://portal.rooms.microsoft.com/) that it would seem should go to a page on Learn.microsoft.com which describes creating Groups, but instead it links to this page which is about Roles. There does not even appear to be a page which describes settings for Groups. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9211ee7-1c36-f653-9c3c-dfda04fdf77c
* Version Independent ID: b9211ee7-1c36-f653-9c3c-dfda04fdf77c
* Content: [Role-based access control in the Microsoft Teams Pro Management Portal - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-pro-rbac)
* Content Source: [Teams/rooms/rooms-pro-rbac.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/rooms-pro-rbac.md)
* Service: **msteams**
* Sub-service: **itpro-rooms**
* GitHub Login: @altsou
* Microsoft Alias: **altsou**

**Comment by dariomws** [comment]
Hi @Milwank, thank you for your feedback.

Here we are limited to updating the content of the article. To provide this type of feedback, you can try one of the following channels:
[Feedback portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)
[Microsoft Teams Rooms Pro Management - Create a support request](https://learn.microsoft.com/microsoftteams/troubleshoot/teams-rooms-and-devices/get-support-teams-rooms-pro-management#create-a-support-request)

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
