### ISSUE TITLE
Review and delete current locations and subnets

### ISSUE THREAD

**Issue by jeffbrushie** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9969]
[Enter feedback here]
After uploading the locations to "Reporting labels" section, there is no way to check the current locations and subnets nor is it possible to delete this information. From my point of view this is quite useless if we are not even able to verifiy the uploaded information. Any plans to change this? In addition the same information must be uploaded to CQD as well. Ever thought about to combine this two uploades? This would help us to reduce the administrative tasks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f8119c9-61af-b469-af98-ddd37764c0ca
* Version Independent ID: 7d829a74-9df7-5b6f-8e1c-44d3e5d38f75
* Content: [Add and update reporting labels - Microsoft Teams](https://learn.microsoft.com/en-US/microsoftteams/learn-more-about-site-upload?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/learn-more-about-site-upload.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/learn-more-about-site-upload.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
