### ISSUE TITLE
Please don't forget us Windows 10 S-Mode users :,(

### ISSUE THREAD

**Issue by bnunya** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#997]
It seems silly to not make your app available in the Windows 10 Store.....  YOUR store.  I'm keeping my Surface Go in S-Mode, please don't make me use the browser version :(   It doesn't even have a decent "Pin this page to Start" Live Tile logo :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients?ranMID=43674&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-HZq2JGHIdhkBeLnjtHxvIA&epi=je6NUbpObpQ-HZq2JGHIdhkBeLnjtHxvIA&irgwc=1&OCID=AID681541_aff_7795_1243925&tduid=(ir__is3f9oqajwgg2frr0z2jo9q2hf2xkqq1alf0bbuu00)(7795)(1243925)(je6NUbpObpQ-HZq2JGHIdhkBeLnjtHxvIA)()&irclickid=_is3f9oqajwgg2frr0z2jo9q2hf2xkqq1alf0bbuu00)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@bnunya Thank you for this feedback

I know the product teams are always looking for user feedback and how to make Teams better. They keep a close tab on User Voice. I have found an item that I upvoted to enable teams for the Surface [https://microsoftteams.uservoice.com/forums/555103-public/suggestions/18637267-surface-hub-extensibility](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/18637267-surface-hub-extensibility) and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too. 
 
Thank you for your contribution to make the docs better! Much appreciated!

**Comment by bnunya** [comment]
@AndreaBarr That link is for Surface Hub..... I'm talking about Windows 10 S-Mode.... If the Microsoft Teams app will not be available in the Microsoft Store, then any PC or tablet that is in S-Mode (i.e. Surface Go or Surface Laptop) cannot use Microsoft Teams unless they switch their devices out of S-Mode.

**Comment by AndreaBarr** [comment]
@bnunya oh okay sorry for the misunderstanding. The answer is mostly the same though. We have to get upvotes to get Teams in the Microsoft Store. I found one that shows that they are working on just that. I upvoted it already. https://microsoftteams.uservoice.com/forums/555103-public/suggestions/16935901-windows-app-should-be-in-the-windows-store
