### ISSUE TITLE
Improve context and clarity to instructions

### ISSUE THREAD

**Issue by DailenG** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9970]
I would consider revising instructions to improve context and clarity of the explanation by changing the following text

To sign in a device that has been signed out, go to the corresponding device page.
1. Select the device you want to sign in.
2. Go to the Actions menu, and select Sign in a user.

to this

To sign in a device that has been signed out, go to the corresponding device page.
1. Open the device you want to sign in.
2. Go to the Actions menu at the top right hand side of the page, and select Sign in a user.

Reasoning, in step 1, it sounds like you need to select the device using a check box. In step 2, I had no idea there was an actions button because it is so far out of sight and, frankly, hard to see being a white button on a white page

Thank you in advance,
Dailen

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ff0b460-9f13-fefe-37b1-b40d5062fb86
* Version Independent ID: 6ff0b460-9f13-fefe-37b1-b40d5062fb86
* Content: [Remote sign in and sign out for Teams Android devices - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/devices/remote-sign-in-and-sign-out)
* Content Source: [Teams/devices/remote-sign-in-and-sign-out.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/remote-sign-in-and-sign-out.md)
* Service: **msteams**
* Sub-service: **itpro-devices**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment]
Hello @DailenG Dailen, how are you?
I revised this and I'm not so convinced about this addition, however, I'll propose it and let's see if it gets approval
Thank you,

**Comment by get-itips** [comment]
Proposal was rejected.
Closing issue.
