### ISSUE TITLE
Clarification needed on conditional access and the Approvals app in MS Teams

### ISSUE THREAD

**Issue by morismm99** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9973]
Per this document, there is a line that reads:

"Currently, the Approvals app in Teams does not support Conditional Access policies that are set for Microsoft Teams.”

Due to this, one of my clients has the Approvals app blocked in MS Teams. However, if MS Teams, Power Automate, Power Apps, CDS (Dataverse) and Outlook are protected by conditional access, how would an end user get to the Approvals data? There is no standalone Approvals application that a user could use to get around conditional access. Correct? I feel that if admins are accounting for MS Teams, Power Automate, Power Apps, SharePoint Online, Outlook and Dataverse in the conditional access policy, there will be no way for an end user to get around conditional access to get this data, correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 055b01ff-ee6c-7d5a-74bd-0e8eed7ee6b5
* Version Independent ID: 13c4174f-2a2a-2ef9-14c5-2f10817cc66a
* Content: [Manage the Approvals app in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/approval-admin#conditional-access-policies)
* Content Source: [Teams/approval-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/approval-admin.md)
* Service: **msteams**
* GitHub Login: @daisyfell
* Microsoft Alias: **daisyfeller**

**Comment by get-itips** [comment]
Hello @morismm99 
I'm working on this.
Thanks

**Comment by get-itips** [comment]
Hello @morismm99 
Article is in the process of being updated regarding Conditional Access.
Thanks

**Comment by morismm99** [comment]
Awesome, thanks for the update!

**Comment by get-itips** [comment]
Article has been updated and it is published.
Closing
