### ISSUE TITLE
Column Name Inconsistant? Plan Name vs Product Name

### ISSUE THREAD

**Issue by jmtread** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9981]
Hi There

Is there a meaningful difference between the Plan Name vs Product Name headings?
There is a Faculty SKU table and Student Sku table on this page.
The heading of the first column of each table is different.
The Faculty's first column is labeled "Plan Name"
The Student's first column is labeled "Product Name"

As both tables are displaying the same type of data is would make sense to keep the headings consistent.
I'd recommend labeling them both as Product Name.

On other pages like 
https://learn.microsoft.com/en-us/azure/active-directory/enterprise-users/licensing-service-plan-reference#:~:text=You%20can%20also%20download%20a%20CSV%20version%20of%20this%20table
the CSV files calls Product Name Column the Product Display Name. 

Regards,

Jason

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae22e4df-3f88-8c54-c55e-a3cd4f720cbc
* Version Independent ID: 3be05aac-9860-e78c-aca7-c62de044c48b
* Content: [Education SKU reference - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/sku-reference-edu)
* Content Source: [Teams/sku-reference-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/sku-reference-edu.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
