### ISSUE TITLE
[teams] API permissions required for application-based authentication

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9985]
Could you please double-check that all API permissions listed in the `Setup Application-based authentication` section of the article are still required for the latest `MicrosoftTeams` PowerShell module to use application-based authentication?

I'm referring to the following lines:

```markdown
2. Assign API permissions to the application
   - For \*-Cs cmdlets - the Microsoft Graph API permission needed is `Organization.Read.All`.
   - For Non \*-Cs cmdlets - the Microsoft Graph API permissions needed are `Organization.Read.All`, `User.Read.All`, `Group.ReadWrite.All`, `AppCatalog.ReadWrite.All`, `TeamSettings.ReadWrite.All`, `Channel.Delete.All`, `ChannelSettings.ReadWrite.All`, `ChannelMember.ReadWrite.All`.  
```

The reason I'm asking is because I suspect that v.5.1.0 of the module is only requesting `scope=AppCatalog.ReadWrite.All+Group.ReadWrite.All+User.Read.All+openid+profile+offline_access` when `Connect-MicrosoftTeams` cmdlet is executed without params

Environment:

```console
PS C:\> Get-Module -Name MicrosoftTeams

ModuleType Version    PreRelease Name
---------- -------    ---------- ----
Script     5.1.0                 MicrosoftTeams

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.0, 7.1.0, 7.2.0, 7.3.4}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32304edf-550b-72a3-57df-6dcc29dba56d
* Version Independent ID: 32304edf-550b-72a3-57df-6dcc29dba56d
* Content: [Application-based authentication in Teams PowerShell Module - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/teams-powershell-application-authentication)
* Content Source: [Teams/teams-powershell-application-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-powershell-application-authentication.md)
* Service: **msteams**
* GitHub Login: @pbafna03
* Microsoft Alias: **pbafna**

**Comment by pbafna03** [comment]
Hi @shivtorov, 

Yes, the permissions listed are needed for the Non *-Cs cmdlets. When using Connect-MicrosoftTeams without any param, the user-based flow gets invoked and that works a bit differently. 

Thanks,
