### ISSUE TITLE
Include exact make & model that matches how devices show up in Azure Active Directory for Conditional Access Device Filters

### ISSUE THREAD

**Issue by davidjfriedman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9986]
It would be helpful to IT admins to have columns that include the exact device make and model that matches how the device would show up in Azure Active Directory.

IT Admins do not currently know how a device will show up in Azure Active Directory, which makes it difficult for them to plan and configure Conditional Access policy device filters where they may want to pre-populate information such as make and model.

Since these are certified devices, it is presumed the information is available and could potentially be surfaced publicly for IT Admins.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aaaef9e1-8f1c-ebf0-7856-4c007342a2c3
* Version Independent ID: 3eaf671f-375e-8787-9c66-3947c3606559
* Content: [Devices for Teams - Microsoft Teams](https://learn.microsoft.com/en-us/MicrosoftTeams/devices/teams-ip-phones)
* Content Source: [Teams/devices/teams-ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/teams-ip-phones.md)
* Service: **msteams**
* Sub-service: **itpro-devices**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @davidjfriedman, thank you for your feedback. 

I will escalate this to the appropriate team for consideration and potential inclusion of this information in the article.
