### ISSUE TITLE
Clarify licensing for guest access in Teams

### ISSUE THREAD

**Issue by Alejaraz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9990]
On this page it says: "Guest access can be used with all Microsoft 365 Business Standard, Microsoft 365 Enterprise, and Microsoft 365 Education subscriptions" 

But in the Azure AD document says: "Your first 50,000 MAUs per month are free for both Premium P1 and Premium P2 features"
https://learn.microsoft.com/en-us/azure/active-directory/external-identities/external-identities-pricing

I'd like to clarify what licenses are required to add guests in Teams?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2492e210-08f9-a476-97ec-008926def961
* Version Independent ID: adcb0dd9-4a3c-b665-6e34-ce3276c89b4d
* Content: [Guest access in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/guest-access)
* Content Source: [Teams/guest-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by Alejaraz** [comment]
@JMCA2

**Comment by JMCA2** [comment]
@MikePlumleyMSFT @Alejaraz On https://www.microsoft.com/licensing/terms/productoffering/MicrosoftAzure/MCA it says

`For each User SL (or equivalent Subscription License Suite) Customer assigns to a user, Customer may also permit up to five additional [External Users](https://www.microsoft.com/licensing/terms/product/Glossary/all) to access the corresponding Azure Active Directory service level. This option is not available to new customers nor customers using (or who have used) the service under a Monthly Active User count. Only [External Users](https://www.microsoft.com/licensing/terms/product/Glossary/all) can use the Azure Active Directory External Identities pricing based on Monthly Active User count.`

Is the limit 5:1 or 50k?

**Comment by dariomws** [comment]
Hi @Alejaraz, thank you for your feedback.

I understand the answer is in the same article you shared:
"In your Azure AD tenant, guest user collaboration usage is billed based on the count of unique guest users with authentication activity within a calendar month. This model replaces the 1:5 ratio billing model, which allowed up to five guest users for each Azure AD Premium license in your tenant. When your tenant is linked to a subscription and you use External Identities features to collaborate with guest users, you'll be automatically billed using the MAU-based billing model.

Your first 50,000 MAUs per month are free for both Premium P1 and Premium P2 features. To determine the total number of MAUs, we combine MAUs from all your tenants (both Azure AD and Azure AD B2C) that are linked to the same subscription."

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
