### ISSUE TITLE
In Teams Admin center the lowest is 576 by 576

### ISSUE THREAD

**Issue by dipinn26592** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9996]
In Teams Admin center the lowest resolution is 576 by 576. however doc sayd 360 by 360. which is correct ? 

![image](https://user-images.githubusercontent.com/41346103/236439098-5159a0be-dfd0-4536-915c-c37a1ef9ea77.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 117ecfa2-d4f0-f0dd-105f-d7203fe8a1ba
* Version Independent ID: 117ecfa2-d4f0-f0dd-105f-d7203fe8a1ba
* Content: [Meeting themes for Teams meetings - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/meeting-themes)
* Content Source: [Teams/meeting-themes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-themes.md)
* Service: **msteams**
* GitHub Login: @wlibebe
* Microsoft Alias: **wlibebe**

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
